### ISSUE TITLE
"Windows x86 PE Exception Handling" Auto-Analysis pass is extremely slow

### ISSUE THREAD

**Issue by 3dsboy08** [NationalSecurityAgency/ghidra#10]
**Describe the bug**
The "_Windows x86 PE Exception Handling_" auto-analysis pass is extremely slow, to the point of making it unusable.

**To Reproduce**
1) Auto-Analyze a semi-large program with the "_Windows x86 PE Exception Handling_" pass enabled
2) Watch as the "Windows x86 PE Exception Handling" pass takes forever to complete. (for me, it was around ~6 functions per second out of 10000 functions to analyze)

**Expected behavior**
To make "Windows x86 PE Exception Handling" faster then it currently is.

**Screenshots**
![image](https://user-images.githubusercontent.com/14914815/53848538-b5ce3800-3f82-11e9-9083-63597f0b0ffb.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome
 - Version: 9

**Comment by quosego** [comment]
It's a relatvely fast process regarding auto-analysis speeds to that of other disassemblers, IDA for example. But it is also fairly thread oriented process which may be the reason sudden lag on your end. Complexity and chaining will also reduce execution analysis speed but that is to be expected throughout the analysis process steps. 

What settings did you use before running the auto analysis?

**Comment by emteere** [comment]
This is fixed in master and upcoming 9.2 release with GT-3341 which also sped up the media search, and RTTI processing.
