### ISSUE TITLE
Copy Special doesn't work on a single Row

### ISSUE THREAD

**Issue by ebfe2326** [NationalSecurityAgency/ghidra#1000]
**Describe the bug**
The copy special option doesn't work on a single line and will only work if multiple lines are selected.  The copy special / byte string is particularly useful for copying opcodes out as byte strings for yara rules.  Even though much of the time this would be on multiple rows, there are still situations where you would do this on a single row for long instructions.  This is not only quicker, but it prevents typing errors.

**To Reproduce**
select any individual row, right click, and the "copy special" option is greyed out

**Expected behavior**
It would be nice if the copy special would work on a single row in addition to an entire selection just as the normal copy does.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: OpenJDK 12
 - Ghidra Version: all, including 9.1 DEV built from github

**Comment by dragonmacher** [comment]
I am not seeing this when a row is selected, but I am seeing this with a single column selection.  For example, if I select part of some label text, then 'Copy Special' is not enabled.

Could you provide a small screen shot of the selection that is failing?

**Comment by ebfe2326** [comment]
Thanks for the information.  I didn't realize there was a difference when part vs all of a row was selected.  But if I select the entire row, then the copy special does work.  I didn't consider this because when I select multiple lines, even if only part of each line is selected, Ghidra automatically changes the selection to the entire row and the copy special works.

Given that, I think it would be a nice feature enhancement if the copy special worked without needing to select an entire row.  I can't think of a situation where I would be using the copy special and didn't intend for the entire row to be included  vs a specific column.

If you think that's feasible and it's possible to change this to a feature request vs a bug, that would make sense to me.  If you think this change would not be advisable or not an easy update, i can make sure the whole row is selected now that I know it makes a difference and the issue can an be closed.
