### ISSUE TITLE
R_MIPS_26 relocation bug

### ISSUE THREAD

**Issue by pkooiman** [NationalSecurityAgency/ghidra#1001]
R_MIPS_26 relocations are handled incorrectly when addend is not 0. The root cause is an operator precedence issue in  MIPS_ElfRelocationHandler.java:

value = (int) ((addend | ((offset + 4) & (0xfc000000 << shift)) + symbolValue) >> shift);

As "|" has lower precedence than "+", this ends up binary-oring the symbolvalue with addend, leading to interesting but almost never correct results if addend is not 0.

Also it seems to me the or-ing in of the current PC upper 6 bits into the result is undone later on by masking with MIPS_ElfRelocationConstants.MIPS_LOW26 anyway, so it can be removed from the value calculation.

I will submit a pull request fixing the issue.

**Comment by ghidra1** [comment]
Does the following simplified logic appear correct?  Not sure why it was so convoluted.

```
case MIPS_ElfRelocationConstants.R_MIPS_26:
case MIPS_ElfRelocationConstants.R_MIPS16_26:
case MIPS_ElfRelocationConstants.R_MICROMIPS_26_S1:
		int shift = (relocType == MIPS_ElfRelocationConstants.R_MICROMIPS_26_S1) ? 1 : 2;
		if (mipsRelocationContext.extractAddend()) {
			addend = oldValue;
		}
		if (!elfSymbol.isSection()) {
			addend = signExtend((int) addend, 26 + shift);
		}
		// TODO: cross-mode jump detection/handling is unsupported
		value = (int) (addend + symbolValue) >> shift;
		newValue = (oldValue & ~MIPS_ElfRelocationConstants.MIPS_LOW26) |
			(value & MIPS_ElfRelocationConstants.MIPS_LOW26);
		writeNewValue = true;
		break;
```

**Comment by ghidra1** [comment]
I could not find the basis for the local symbol handling as it was, although I did find different treatment of section symbols.

**Comment by pkooiman** [comment]
There is a shift for addend missing, otherwise this seems pretty much what binutils/bfd does. With the missing shift, the code becomes

```       
        case MIPS_ElfRelocationConstants.R_MIPS_26:
        case MIPS_ElfRelocationConstants.R_MIPS16_26:  
        case MIPS_ElfRelocationConstants.R_MICROMIPS_26_S1:
                int shift = (relocType == MIPS_ElfRelocationConstants.R_MICROMIPS_26_S1) ? 1 : 2;
                if (mipsRelocationContext.extractAddend()) {
                        addend = (oldValue & MIPS_ElfRelocationConstants.MIPS_LOW26) << shift;
                }
                if (!elfSymbol.isSection()) {
                        addend = signExtend((int) addend, 26 + shift);
                }
                // TODO: cross-mode jump detection/handling is unsupported
                value = (int) (addend + symbolValue) >> shift;
                newValue = (oldValue & ~MIPS_ElfRelocationConstants.MIPS_LOW26) |
                        (value & MIPS_ElfRelocationConstants.MIPS_LOW26);
                writeNewValue = true;
                break;
 ```

**Comment by pkooiman** [comment]
The original code appears to have been lifted from this [MIPS ABI document](https://www.linux-mips.org/pub/linux/mips/doc/ABI/mipsabi.pdf). The calculation is shown there complete with operator precedence error.

That document is probably also the reason for the different treatment for local symbols in the original code, it says the calculation without sign extension applies to "a symbol referenced by the
symbol table index in the relocation entry STB_LOCAL/STT_SECTION". 

I found an entry in the binutils Changelog-2016 that says "R_MIPS_26.... treat the addend as signed with local non-section symbols", but binutils only checks if the symbol is a section symbol as far as I can see.

**Comment by ghidra1** [comment]
Good catch on the missing addend shift. 

With the ABI specified local relocation expression "(((A << 2) |  (P & 0xf0000000) + S) >> 2" it would seem the relocation offset 'P' has no affect on the final 26-bit value produced.  Not sure why 'P' is used in the expression.  

To be safe I included check for both local or section based relocation which seems consistent with the ABI spec (

> local refers to a symbol referenced by the
> symbol table index in the relocation entry STB_LOCAL/STT_SECTION

).  Could you try with your binary and let me know if you think it is OK.  Thanks.

```
case MIPS_ElfRelocationConstants.R_MIPS_26:
case MIPS_ElfRelocationConstants.R_MIPS16_26:
case MIPS_ElfRelocationConstants.R_MICROMIPS_26_S1:
	int shift = (relocType == MIPS_ElfRelocationConstants.R_MICROMIPS_26_S1) ? 1 : 2;
	if (mipsRelocationContext.extractAddend()) {
		addend = (oldValue & MIPS_ElfRelocationConstants.MIPS_LOW26) << shift;
	}
	if (!elfSymbol.isLocal() && !elfSymbol.isSection()) {
		addend = signExtend((int) addend, 26 + shift);
	}
	// TODO: cross-mode jump detection/handling is unsupported
	value = (int) (addend + symbolValue) >> shift;
	newValue = (oldValue & ~MIPS_ElfRelocationConstants.MIPS_LOW26) |
		(value & MIPS_ElfRelocationConstants.MIPS_LOW26);
	writeNewValue = true;
	break;
```

**Comment by pkooiman** [comment]
I'm thinking the condition should be

```
    if (!(elfSymbol.isLocal() && elfSymbol.isSection()))
```
ie do the sign extension thing unless the symbol is both local and a section symbol. That would also fit better with the binutils comment "treat the addend as signed with local non-section symbols"

**Comment by pkooiman** [comment]
Otherwise the code works fine. If I find some time I will try to hunt down when exactly gas emits a negative addend for non-section local symbols and see if I can come up with a test case.

**Comment by ghidra1** [comment]
A section symbol is a special symbol (one per section) and is distinct from an arbitrary named symbol being local.  Most local symbols are not a section symbol.
