### ISSUE TITLE
Filtering Known Labeled Functions

### ISSUE THREAD

**Issue by inreverse-sec** [NationalSecurityAgency/ghidra#1004]
In a Ghidra script how do I list all functions in a program except for ones that have been named/labeled as known statically compiled functions? (e.g malloc).

**Comment by astrelsky** [comment]
> In a Ghidra script how do I list all functions in a program except for ones that have been named/labeled as known statically compiled functions? (e.g malloc).

You would need to iterate over all the functions and check their source type. Any source type with lower priority than SourceType.IMPORTED should be what you are looking for.

Here is a simple example.
```
private List<Function> getUnNamedFunctions() {
    FunctionManager functionManager = currentProgram.getFunctionManager();
    ArrayList<Function> functions = new ArrayList<>(functionManager.getFunctionCount());
    for (Function function : functionManager.getFunctions(true)) {
        if (function.getSignatureSource().isLowerPriorityThan(SourceType.IMPORTED)) {
            functions.add(function);
        }
    }
    functions.trimToSize();
    return functions;
}
```

**Comment by inreverse-sec** [comment]
> private List<Function> getUnNamedFunctions() {
>     FunctionManager functionManager = currentProgram.getFunctionManager();
>     ArrayList<Function> functions = new ArrayList<>(functionManager.getFunctionCount());
>     for (Function function : functionManager.getFunctions(true)) {
>         if (function.getSignatureSource().isLowerPriorityThan(SourceType.IMPORTED)) {
>             functions.add(function);
>         }
>     }
>     functions.trimToSize();
>     return functions;
> }

Andrew, thanks for the explanation and example!
