### ISSUE TITLE
Consider converting the codebase to Kotlin

### ISSUE THREAD

**Issue by XVilka** [NationalSecurityAgency/ghidra#1005]
Advantages of [Kotlin](https://kotlinlang.org/)
- Conciseness
- Interoperability
- Functional programming support
- Fail-fast system
- Null-safety through nullable and non-nullable types, safe calls and safe casts
- Extension functions
- Higher-order functions
- Data classes
- Immutability
- Type aliases
- [Kotlin Native](https://kotlinlang.org/docs/reference/native-overview.html) can be compiled into the native code, yay, no more JVM!

The porting process can be done in steps, since both Kotlin and Java are interoperable with no effort. And the automated conversion can be performed easily.

**Comment by ryanmkurtz** [comment]
Thank you for the suggestion, but we are committed to Java for the core of Ghidra.
