### ISSUE TITLE
Organize issues into Projects and more labels

### ISSUE THREAD

**Issue by XVilka** [NationalSecurityAgency/ghidra#1006]
Currently everything is mixed in, but it would be beneficial to have them structured. For example, I am more interested in the decompiler part of the Ghidra, so having a Decompiler project at https://github.com/NationalSecurityAgency/ghidra/projects with "TODO, In progress, Done" columns would be a top notch. It also makes sense to use the labels for a more fine grained structuring inside the projects.

**Comment by kant2002** [comment]
More labels would be helpful

**Comment by ryanmkurtz** [comment]
I agree, I'll work on this.  The default GitHub set is a decent start but our pull-requests and issues have grown large and need better organization.

**Comment by ryanmkurtz** [comment]
I've begun the process, so I am going to close this out.  It will develop and improve over time.

**Comment by astrelsky** [comment]
@ryanmkurtz is it possible to allow the author of an issue/pull-request to add labels?

**Comment by ryanmkurtz** [comment]
What do you see under the labels drop-down when you create a new issue?

**Comment by astrelsky** [comment]
> What do you see under the labels drop-down when you create a new issue?

There is no labels drop-down.

**Comment by ryanmkurtz** [comment]
Hmmm, did there used to be before I added all of these new labels?

**Comment by astrelsky** [comment]
> Hmmm, did there used to be before I added all of these new labels?

No, there were never any labels available.

You can choose from issue templates. The screens available are as follows:

![1](https://user-images.githubusercontent.com/46897303/71110418-3cac7400-2195-11ea-876d-e2cd8dd03f22.PNG)
![2](https://user-images.githubusercontent.com/46897303/71110426-41712800-2195-11ea-9cae-fb987a28aac7.PNG)

**Comment by astrelsky** [comment]
@ryanmkurtz so according to the information [here](https://help.github.com/en/github/managing-your-work-on-github/about-labels) only those with write-access can apply labels. While a bit invasive I wonder if it is possible to have a bot of some sort or another way to have labels added automatically if the title contains a magic string. Maybe something like `[Bug]` would cause the bug label to be applied and the tag would be automatically stripped from the title.
