### ISSUE TITLE
Context menu causes drawing issues

### ISSUE THREAD

**Issue by midnyteshade** [NationalSecurityAgency/ghidra#1009]
**Describe the bug**
When I right click for the context menu about 2 out of 10 times, it will cause issues with the GUI drawing to the point anytime I move the mouse it draws stuff everywhere. Closing the codebrowser and reopening the project doesn't resolve the issue, I have to completely close Ghidra and reopen.

**To Reproduce**
1. Happens in all projects, just play with the context menu a few times

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10 x64 with all current updates applied
 - Java Version: 11, IMPLEMENTOR_VERSION="18.9"
 - Ghidra Version: 9.0.4

**Additional context**
![image](https://user-images.githubusercontent.com/49591970/64908701-29d36080-d6c9-11e9-8892-c60499623573.png)

**Comment by mumbel** [comment]
possible dup of #123 or #1  maybe?

**Comment by midnyteshade** [comment]
Thanks @mumbel! #123 definetely got me pointed in the right direction.  In my case I had to stop the NahimicService.  Did a few tests and that seems to have done the trick.
