### ISSUE TITLE
Dissasemby is different for the same  binary code

### ISSUE THREAD

**Issue by Hardcore-fs** [NationalSecurityAgency/ghidra#1013]
the enclosed sample for  register moves.
the Arm manual gives them as 
mov r0,r4
mov r0,r6
Relevant addresses
402ba4bc

402ba4d0
402ba530

402ba538
402ba550
![mixed](https://user-images.githubusercontent.com/1309004/64914134-a1fc5d80-d77f-11e9-81fd-8773ca14d3bf.jpeg)

**Comment by mumbel** [comment]
what is the actual question?
`04 00 a0 e1` results in cpy r0, r4, for every case shown here  
`06 00 a0 e1` results in cpy r0, r6, for every case shown here

**Comment by Hardcore-fs** [comment]
402ba538, 402ba4d0
What are the data references & why is the mnemonic not the same as other breakdowns?

**Comment by LowLevelMahn** [comment]
402ba4d0 uses r4
402ba538 uses r6 
i also don't understand your question - could it be that you have no clue about how the operation encoding works on arm?

http://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=04+00+a0+e1&arch=arm&endianness=little&dis_with_addr=True&dis_with_raw=True&dis_with_ins=True#disassembly
http://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=06+00+a0+e1&arch=arm&endianness=little&dis_with_addr=True&dis_with_raw=True&dis_with_ins=True#disassembly

**Comment by LowLevelMahn** [comment]
i also don't understand what your problems are?

> What are the data references

what is wrong with the given references?

> why is the mnemonic not the same as other breakdowns?

the first is using the r4 the second the r6 - they can't be identical encoded - why do you think they should?

['06 00 a0 e1' disassembly](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=06+00+a0+e1&arch=arm&endianness=little&dis_with_addr=True&dis_with_raw=True&dis_with_ins=True#disassembly)
['04 00 a0 e1' disassembly](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=04+00+a0+e1&arch=arm&endianness=little&dis_with_addr=True&dis_with_raw=True&dis_with_ins=True#disassembly)

**Comment by ghidra1** [comment]
The CPY instruction is a synonym for MOV in this case.
The extended markup => is used when a replacement strategy can not be determined.  The Tool Options can be adjusted if you prefer not to see such markup.
    Edit -> Tool Options -> Listing Fields -> Operands Field (see Always Show Primary Reference)
