### ISSUE TITLE
PDB: IDiaSectionContrib pointer leak

### ISSUE THREAD

**Issue by Patuti** [NationalSecurityAgency/ghidra#1015]
**Describe the bug**
While trying to File->Load a PDB for a binary, the generated xml was incomplete.
After debugging pdb.exe, I noticed there was an assert failure while assigning a new value to pSecContrib in iterate.cpp :: iterateSections.

**To Reproduce**
pdb.exe pdbfile.pdb -fulloutput

**Expected behavior**
No assert failures.

**Environment (please complete the following information):**
 - OS: Win 10
 - Java Version: 11.2
 - Ghidra Version: master

**Additional context**
I used a known binary with a public pdb.
qrenderdoc.exe from RenderDoc 1.4 and its pdb to be found in its symbol server: https://renderdoc.org/symbols
Renderdoc 1.4 release: https://renderdoc.org/stable/1.4/RenderDoc_1.4_64.zip

**Comment by Patuti** [comment]
#1014

**Comment by ghizard** [comment]
Thank you for reporting this and submitting your PR. I was able to confirm the issue with the example you presented.
