### ISSUE TITLE
Negative Structure Ordinal produces positive value field

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1017]
**Describe the bug**
Accessing a structure with a negative value will produce the same results as if the value was positive.

**To Reproduce**
1. Compile below example code
2. Load and analyze in ghidra
3. Change getValue parameter from int* to A*

```
int getValue(int* a_ptr) {
    return a_ptr[-1];
}

typedef struct A {
    int a_data;
};

typedef struct B {
    int b_data; /* buffer for protection */
    struct A a;
};

int main() {
    struct B b;
    b.b_data = 5;
    printf("%d\n", getValue(&b.a));
    return 0;
}
```

**Expected behavior**
Unsure.

**Screenshots**
![ex](https://user-images.githubusercontent.com/46897303/64930637-acab0700-d800-11e9-9855-6ac3daa87f6d.PNG)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18362.356]
 - Java Version: 12.0.2
 - Ghidra Version: 9.1_DEV

**Comment by mumbel** [comment]
This is how pointers/memory work though, right?  You are giving it an array of `A`, and its getting the -1 index and returning `a_data`.  You might want to expand your example and what you're expecting.  `struct B` doesn't provide any value in your example, did you mean to cast `getValue(int *)` to `getValue(B *)`?

**Comment by astrelsky** [comment]
> This is how pointers/memory work though, right? You are giving it an array of `A`, and its getting the -1 index and returning `a_data`. You might want to expand your example and what you're expecting. `struct B` doesn't provide any value in your example, did you mean to cast `getValue(int *)` to `getValue(B *)`?

Oh yes, I misinterpreted what was going on.
