### ISSUE TITLE
Disassembler: add a toggle annotations feature

### ISSUE THREAD

**Issue by aldelaro5** [NationalSecurityAgency/ghidra#1018]
**Is your feature request related to a problem? Please describe.**
 
When I view the disassembly, often times, the annotations it put like naming the register for a certain range to denote variables are useful, but it can happen sometime where they get in the way. For example, say it decided to annotate the register EAX with a name like local_a or something, but in that range, the register AH is used. What would happen is I would see both for EAX and AH local_a, but they aren't exactly the same and the meaning of using AH vs EAX can be the difference between 5 minutes research to 30 minutes. 

Another common annoyance is when I'm analyzing a long function and say the decompiler has trouble so I check the disassembly to figure it out....but all the registers are named and to know which one is which name, I either have to right click and select instruction info which tells me the raw operands or I have to lookup at the top of the function's listing to see the assignments. This is very cumbersome especially when multiple instructions are involved in my reversing effort.

**Describe the solution you'd like**

The solution I am suggesting is to have a way to toggle between no annotations and having the annotations. It could be possible to bind it to a keyboard shortcut so I can quickly refer to the raw assembly before the annotations are applied. This would save me a lot of needlessly spent time trying to figure out the names or checking the instruction's details all the time.

**Describe alternatives you've considered**

None so far, but I am open to suggestions.

**Additional context**

N/A

**Comment by ghidra1** [comment]
- Register variable markup can be hidden using the Tool Options settings:
       Edit -> Tool Options -> Listing Field -> Operand Fields (see various Markup options)
- Raw instruction representation is shown in lower right corner of window for the current cursor location (no need to show Instruction Info).  It would be relatively simple to write a Ghidra Script which registers a key binding and toggles the state of the Operand Fields tool options mentioned above.

**Comment by aldelaro5** [comment]
Closing this because I can live with the markup options that I didn't know was there (though, the status bar doesn't help because I have to increase my font size due to poor sight and the text doesn't go all the way)
