### ISSUE TITLE
PE TLS callbacks not referenced

### ISSUE THREAD

**Issue by williballenthin** [NationalSecurityAgency/ghidra#102]
**Is your feature request related to a problem? Please describe.**
A PE file may specify TLS callbacks that are invoked before a new threads begins execution (including the main thread). When looking for malicious logic, its important to inspect TLS callbacks that may unpack, obfuscate, or subvert. ghidra does not highlight the entries of the TLS table, which makes it difficult to find malicious TLS routines.

**Describe the solution you'd like**
I would like TLS callbacks to be displayed in the symbol tree, possibly under a new root node named "TLS Callbacks".

**Describe alternatives you've considered**
Place the TLS callback entries under the "Exports" root node, which is conceptually like what IDA does (marks TLS callbacks as an "entrypoint").

**Additional context**
From IDA:

![image](https://user-images.githubusercontent.com/156560/53986386-4cae0800-40db-11e9-9614-1692ace0c440.png)

![image](https://user-images.githubusercontent.com/156560/53986406-5899ca00-40db-11e9-8f8f-b77703f787c3.png)

current view in ghidra:

![image](https://user-images.githubusercontent.com/156560/53986465-7e26d380-40db-11e9-8ed0-2d31e04afe9d.png)

**Comment by ryanmkurtz** [comment]
I added this for 9.1.  They are marked as entry points, which automatically puts them in the exports node.

**Comment by williballenthin** [comment]
awesome, thanks!
