### ISSUE TITLE
ProgramDB.setImageBase commits on false

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1022]
**Describe the bug**
Executing the method setImageBase with commit=false commits the new base address and commit=true does not.

**To Reproduce**
1. Open python window
2. execute currentProgram.setImageBase(toAddr(0), True)
3. Note that it can be undone.
4. Undo
5. execute currentProgram.setImageBase(toAddr(0), False)
6. Note that it cannot be undone.

**Expected behavior**
The changes to be committed on true and not on false as per the documentation.

**Environment (please complete the following information):**
 - Ghidra Version: 9.0.4-9.1.0_DEV

**Comment by ghidra1** [comment]
The 'false' commit parameter is not intended for use as you may think and is somewhat experimental in nature.  It is intended to be used with read-only programs during a debugger session where the image base must be temporarily changed to match a runtime image placement.  Specifying a commit of 'false' does not actually change the database so no transaction is created thus cannot be undone.  It simply changes how encoded addresses stored in the database are translated to an Address.  This is not a bug.

**Comment by astrelsky** [comment]
> The 'false' commit parameter is not intended for use as you may think and is somewhat experimental in nature. It is intended to be used with read-only programs during a debugger session where the image base must be temporarily changed to match a runtime image placement. Specifying a commit of 'false' does not actually change the database so no transaction is created thus cannot be undone. It simply changes how encoded addresses stored in the database are translated to an Address. This is not a bug.

Ok, thank you very much.
