### ISSUE TITLE
PDB.EXE causes failure if started from Ghidra

### ISSUE THREAD

**Issue by Rocketansky** [NationalSecurityAgency/ghidra#1024]
**Describe the bug**
Analyzing a binary and manually starting "Load PDB File ..." results in the error of the screenshot. If I start PDB.EXE manually with the same PDB file as input, it creates a perfect XML file without any errors.

**To Reproduce**
1. Open Code Browser and analyze a binary. Analyze stops with a comlaint about the PDB loading.
2. Start "Load PDB File ..." manually
3. See error

**Expected behavior**
Ghidra should be able to work with PDB.EXE without problems.

**Screenshots**
![Ghidra_PDB](https://user-images.githubusercontent.com/25251718/65145953-0a1aa000-da1b-11e9-88df-cf935b21a3de.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10 10.0 amd64
 - Java Version: AdoptOpenJDK 11.0.4
 - Ghidra Version: 9.0.4

**Additional context**
I loaded the manually produced XML file via "Load PDB File ..." and received an error about a non-matching signature. But at least a couple of function names could be resolved correctly.

**Comment by ryanmkurtz** [comment]
We made a lot of PDB fixes which will be released in 9.1.  If you would like to see if they resolve this issue immediately, you can always build Ghidra from the master branch.   Otherwise, we can wait until we have a 9.1 release to test it out.

**Comment by ryanmkurtz** [comment]
9.1-BETA has just been released.  It would be very helpful to us if you could retest with that version.

**Comment by Rocketansky** [comment]
Tried today with Ghidra 9.1-BETA. But unfortunately the same behavior:
![Ghidra91B_PDB](https://user-images.githubusercontent.com/25251718/65674403-c80de180-e04c-11e9-88c8-5e29cfd24763.PNG)
To be sure I compiled PDB.EXE and if I run in on CL it produces a fine XML file without errors.

**Comment by ghizard** [comment]
Did you register the msdia140.dll as described in docs/README_PDB.html?

**Comment by ryanmkurtz** [comment]
Are you using a 32 or 64-bit Java?

**Comment by Rocketansky** [comment]
@ghizard: yes
@ryanmkurtz: 64-bit
(for some reason I cannot paste screenshots anymore...)

**Comment by kant2002** [comment]
I see this kind of errors can be highlighted if error message from actual PDB.exe would be displayed. 

a. Maybe last couple lines would be enough for troubleshoot, and give some clues for the user. That way PDB.exe can inform about error conditions Ghidra. 

b. Or move all output from PDB.exe to some log inside Ghidra which user can be navigated to look for errors?

**Comment by Rocketansky** [comment]
PDB.EXE itself does not seem to be the problem because it works correctly if started by hand on command line.

**Comment by ryanmkurtz** [comment]
There is a class of bug where Ghidra thinks it's running on a different platform than it actually is, so it would look for a native binary in say, os/win32 instead of os/win64.  That's why I was wondering about the 32-bit vs 64-bit java.  Is your decompiler working correctly?  If it is, than it's not that class of bug.

**Comment by Rocketansky** [comment]
I would say so
![Ghidra_Decompiler](https://user-images.githubusercontent.com/25251718/65689233-dff55d80-e06c-11e9-8dff-030fb4af1d62.PNG)

**Comment by ghizard** [comment]
With the debugging done In #198, I was wondering if stderr was getting redirected to stdout, but I didn't get a follow-up that might confirm it. Perhaps the steps that were done there could be performed in your environment as well to see if the warning about the age is getting directed to the XML parser.

**Comment by Rocketansky** [comment]
@ghizard Thanks for the hint.
I checked the data as you requested and the age is the same with "1".
But I saw that the GUID is different: 
![Ghidra_PDB_age_guid](https://user-images.githubusercontent.com/25251718/65899107-54086c00-e3b3-11e9-8140-1f52d0708752.PNG)

**Comment by ghizard** [comment]
@Rocketansky I believe I have a fix coming for this.  Thanks for your help in diagnosing the issue.  See #198 for more details.
