### ISSUE TITLE
SuperH4 arch gone somewhere in between 2019-09-16 and 2019-09-19

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#1026]
ghidra_9.1_DEV_20190916_osx64.zip works:

![Skärmavbild 2019-09-19 kl  08 34 04](https://user-images.githubusercontent.com/175587/65191767-61bb1900-dab8-11e9-933a-b08576de7811.png)

ghidra_9.1_DEV_20190919_osx64.zip gone:

![Skärmavbild 2019-09-19 kl  08 24 50](https://user-images.githubusercontent.com/175587/65191768-61bb1900-dab8-11e9-83ba-517597c306b0.png)

**Comment by mumbel** [comment]
Are you packaging that? might be more helpful to share what commit you're on.  I see it in my list and SuperH projects haven't been touched in 8 (sh) and 12 (sh-4) days .

**Comment by brainstorm** [comment]
Yes, I'm packaging it myself, namely:

```bash
gradle --init-script gradle/support/fetchDependencies.gradle init
gradle yajswDevUnpack
gradle buildGhidra
```

On the Sept 16th build it worked commit https://github.com/NationalSecurityAgency/ghidra/commit/592436ae34c81b690eb165da3fde6f5e5ed946c6, but not on committ ef50280d10d92f928b1aaec839a51856f7776b04.

Hope that helps? 

FWIW, on HEAD (at the moment of writing this, now) I'm seeing that some of the SuperH4 objects are not being shipped, there's only a manifest in the jar:

```shell
$ pwd
~/dev/ghidra/Ghidra/Processors/SuperH4/build/libs
$ unzip SuperH4.jar
Archive:  SuperH4.jar
   creating: META-INF/
  inflating: META-INF/MANIFEST.MF

$ pwd
~/dev/ghidra/Ghidra/Processors/MIPS/build/libs
$ unzip MIPS.jar
Archive:  MIPS.jar
   creating: META-INF/
  inflating: META-INF/MANIFEST.MF
   creating: ghidra/
   creating: ghidra/app/
   creating: ghidra/app/util/
   creating: ghidra/app/util/bin/
   creating: ghidra/app/util/bin/format/
   creating: ghidra/app/util/bin/format/elf/
   creating: ghidra/app/util/bin/format/elf/extend/
  inflating: ghidra/app/util/bin/format/elf/extend/MIPS_ElfExtension.class
   creating: ghidra/app/util/bin/format/elf/relocation/
  inflating: ghidra/app/util/bin/format/elf/relocation/MIPS_Elf64Relocation.class
  inflating: ghidra/app/util/bin/format/elf/relocation/MIPS_ElfRelocationConstants.class
  inflating: ghidra/app/util/bin/format/elf/relocation/MIPS_ElfRelocationHandler$MIPS_ElfRelocationContext.class
  inflating: ghidra/app/util/bin/format/elf/relocation/MIPS_ElfRelocationHandler.class
  inflating: ghidra/app/util/bin/format/elf/relocation/MIPS_ElfRelocationHandler$MIPS_DeferredRelocation.class
   creating: ghidra/app/plugin/
   creating: ghidra/app/plugin/core/
   creating: ghidra/app/plugin/core/analysis/
  inflating: ghidra/app/plugin/core/analysis/MipsAddressAnalyzer$1.class
  inflating: ghidra/app/plugin/core/analysis/MipsPreAnalyzer.class
  inflating: ghidra/app/plugin/core/analysis/MipsAddressAnalyzer.class
  inflating: ghidra/app/plugin/core/analysis/MipsSymbolAnalyzer.class
   creating: ghidra/program/
   creating: ghidra/program/emulation/
  inflating: ghidra/program/emulation/MIPSEmulateInstructionStateModifier.class
```

**Comment by ryanmkurtz** [comment]
I just did a fresh clone of master (ef50280d10d92f928b1aaec839a51856f7776b04):

```
git clone git@github.com:NationalSecurityAgency/ghidra.git
cd ghidra
gradle --init-script gradle/support/fetchDependencies.gradle init
gradle buildGhidra
```

Unzipped the build in `build/dist`, imported a PE file, unchecked **Show only Recommended...** and I saw SuperH and SuperH4.

**Comment by ryanmkurtz** [comment]
Are you doing a fresh clone or a pull prior to rebuild?

**Comment by brainstorm** [comment]
I'm indeed doing pull prior to rebuild, I didn't expect this to be an issue to be honest :-S

I'll try the fresh clone instead from now on... any reason why this could be an issue? Some erroneous gradle caching of lack of idempotency in the build system? I don't do any local modifications at all :-S

**Comment by ryanmkurtz** [comment]
It definitely shouldn't be an issue, so I'd like to get to the bottom of it.  I was asking just to narrow down what is different about your setup vs mine.

**Comment by brainstorm** [comment]
Sure! Cloning it in another dir now...

**Comment by ryanmkurtz** [comment]
Also, the processor's jar shouldn't matter in this case...only its data/languages directory.

**Comment by ryanmkurtz** [comment]
In your two screen shots, were you using the BinaryLoader for both of them?

**Comment by brainstorm** [comment]
Yeah, I was trying to open the same binary memdump from a device, so same for both with checked/unchecked dialog box for the "Show only recommended Language/Compiler specs", same effect.

~70% through the recompilation from fresh copy. Testing again soon, I'll keep those details in mind and report better.

**Comment by ryanmkurtz** [comment]
It really shouldn't be the pull though.  Like @mumbel said, nothing about SuperH has changed between pulls.

**Comment by brainstorm** [comment]
The data/languages directory looks fine... I just noticed the "old" directory there though...

```
(base) brainstorm:languages romanvg$ ls -alh
total 3552
drwxr-xr-x  12 romanvg  staff   384B Sep 16 23:40 .
drwxr-xr-x   5 romanvg  staff   160B Sep 16 23:24 ..
-rw-r--r--   1 romanvg  staff   6.0K Sep 16 23:24 SuperH4.cspec
-rw-r--r--   1 romanvg  staff   1.1K Sep 16 23:24 SuperH4.ldefs
-rw-r--r--   1 romanvg  staff   692B Sep 16 23:24 SuperH4.opinion
-rw-r--r--   1 romanvg  staff   423B Sep 16 23:24 SuperH4.pspec
-rw-r--r--   1 romanvg  staff    75K Sep 16 23:24 SuperH4.sinc
-rw-r--r--   1 romanvg  staff   808K Sep 19 07:23 SuperH4_be.sla
-rw-r--r--   1 romanvg  staff   257B Sep 16 23:24 SuperH4_be.slaspec
-rw-r--r--   1 romanvg  staff   808K Sep 19 07:23 SuperH4_le.sla
-rw-r--r--   1 romanvg  staff   343B Sep 16 23:24 SuperH4_le.slaspec
drwxr-xr-x   6 romanvg  staff   192B Sep 16 23:24 old
(base) brainstorm:languages romanvg$ ls -alh old/
total 48
drwxr-xr-x   6 romanvg  staff   192B Sep 16 23:24 .
drwxr-xr-x  12 romanvg  staff   384B Sep 16 23:40 ..
-rw-r--r--   1 romanvg  staff   7.2K Sep 16 23:24 SuperH4-BE-16.lang
-rw-r--r--   1 romanvg  staff   275B Sep 16 23:24 SuperH4-BE-16.trans
-rw-r--r--   1 romanvg  staff   7.2K Sep 16 23:24 SuperH4-LE-16.lang
-rw-r--r--   1 romanvg  staff   275B Sep 16 23:24 SuperH4-LE-16.trans```

**Comment by ryanmkurtz** [comment]
The old directory should be there...shouldn't affect anything.

**Comment by ryanmkurtz** [comment]
I guess another thing you could do is check your application.log.  Maybe there is an error in there about SuperH.

**Comment by brainstorm** [comment]
Recompiled from fresh clone, all good:

![Skärmavbild 2019-09-19 kl  22 59 06](https://user-images.githubusercontent.com/175587/65246039-1abd3a00-db31-11e9-93be-44578be48934.png)

**Comment by brainstorm** [comment]
Now unzipped the `ghidra_9.1_DEV_20190919_osx64.zip` back again and it seems to work fine:

![Skärmavbild 2019-09-19 kl  23 02 22](https://user-images.githubusercontent.com/175587/65246296-95865500-db31-11e9-849d-7194cf9886ae.png)

Alright, it might have been perhaps with transient corruption of the project database related with https://github.com/NationalSecurityAgency/ghidra/issues/1023 ? At this point it's the only explanation I can find.

Anyway, closing, sorry to keep you guys chasing ghosts, my bad :/ Thanks for the attention and speed!

**Comment by brainstorm** [comment]
For completeness I just checked `application.log` and other than a ton of NPEs from the database and recovery snapshots being created and restored, I see nothing strange.

Case closed nevertheless.

**Comment by ryanmkurtz** [comment]
Ok, let us know if you happen to see it again.  Thanks.
