### ISSUE TITLE
AdvancedDevelopment course 5 lab answer bug

### ISSUE THREAD

**Issue by knofl** [NationalSecurityAgency/ghidra#1028]
**Describe the bug**
I was learning the ghidra scripting and found bug in the scripting lab5 answer. The program goes into infinite cycle if reversing file has instructions with less or more than 2 arguments.

**To Reproduce**
1. Copy lab5 scripting answer  
2. create a new script with Ghidra and insert copied data
3. Start script on any binary file, that contains any assembler instructions with less or more than two arguments

**Expected behavior**
Infinite cycle with ghidra stops responding

**Environment:**
 - OS: macOS 10.14.6
 - Java Version: 11.0
 - Ghidra Version: 9.1

**Comment by ryanmkurtz** [comment]
Good catch, thanks.
