### ISSUE TITLE
cant disasm e_bdnz - PowerPC32 VLE 

### ISSUE THREAD

**Issue by arkup** [NationalSecurityAgency/ghidra#103]
**Describe the bug**

Ghidra cant disassemble PowerPC32  VLE : ```7A 20 FF F8 ``` 
IDA prints **e_bdnz** 

**Expected behavior**

IDA
```
seg000:00040296 7A 20 FF F8                 e_bdnz    loc_4028E
```
Ghidra (press F12)
```
        00040296 7a              ??         7Ah    z
        00040297 20              ??         20h     
        00040298 ff              ??         FFh
        00040299 f8              ??         F8h
```

**Comment by gnooby22** [comment]
For some reason within `Ghidra/Processors/PPC/data/languages/ppc_vle.sinc` the `CC32 `(condition code) has the "z" and "nz" case commented-out.  I think it's possible these should be changed to "dz" and "dnz" and uncommented.

**Comment by arkup** [comment]
@gnooby22 yeah that seems to work, thanks!

**Comment by ryanmkurtz** [comment]
This will be fixed in our next release.
