### ISSUE TITLE
Access entropy calculations from API 

### ISSUE THREAD

**Issue by bufu1003** [NationalSecurityAgency/ghidra#1035]
I have searched the docs and the only reference to entropy I see in the API is `ghidra.app.util.bin.format.pe.DllCharacteristics.IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA` 

Is there any way to access the entropy:address information as shown in the GUI from within the API?

Thank you

**Comment by bufu1003** [comment]
@ryanmkurtz Apologies if this is a redundant question, assuming by addition of "Feature:API" tag this means that accessing entropy calculations is current not available via the API?

**Comment by ryanmkurtz** [comment]
The tags just mean this is a question about our API.  I started to look into this this morning but couldn't quite find an answer I was happy about responding with.  I'll just show you some things I found:

A service to access entropy info:
https://github.com/NationalSecurityAgency/ghidra/blob/cbf4c9d34aa57cbeb49c714d69271bb4790953a4/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/overview/entropy/EntropyOverviewColorService.java#L56-L61

A screenshot generator that uses the service:
https://github.com/NationalSecurityAgency/ghidra/blob/cbf4c9d34aa57cbeb49c714d69271bb4790953a4/Ghidra/Test/IntegrationTest/src/screen/java/help/screenshot/OverviewPluginScreenShots.java#L39-L45

Definitely not a lot of scripting-level API options for entropy it seems.

**Comment by bufu1003** [comment]
Understood, thank you for the effort. Do you know how entropy is calculated in Ghidra as I might have to find some sort of workaround script? Is it calculated for every address line, block, etc?

**Comment by ryanmkurtz** [comment]
All of the math is in [EntropyOverviewColorService.java](https://github.com/NationalSecurityAgency/ghidra/blob/cbf4c9d34aa57cbeb49c714d69271bb4790953a4/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/overview/entropy/EntropyOverviewColorService.java).  It's calculated for a 256-byte sliding window.

**Comment by ryanmkurtz** [comment]
There is also this class: [EntropyCalculate.java](https://github.com/NationalSecurityAgency/ghidra/blob/cbf4c9d34aa57cbeb49c714d69271bb4790953a4/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/entropy/EntropyCalculate.java).  For some reason the GUI entropy plugin isn't using this (so its existence wasn't obvious) but it might be appropriate for your case.
