### ISSUE TITLE
"Char" in tooltip is incorrect

### ISSUE THREAD

**Issue by justanotheranonymoususer** [NationalSecurityAgency/ghidra#1038]
See screenshot. Windows, x86-64 binary. Expected: 'a'. Got: '\0'. I suspect it might be an endianness issue.

![image](https://user-images.githubusercontent.com/5781692/65395246-f1a2e080-dda0-11e9-99a9-b42f28a656c0.png)

**Comment by ryanmkurtz** [comment]
I feel like this may have been fixed.  What version of Ghidra were you using?

**Comment by justanotheranonymoususer** [comment]
Latest from the website

**Comment by ryanmkurtz** [comment]
Ok I'll check to see if it's been fixed in master.

**Comment by ryanmkurtz** [comment]
9.1-BETA has just been released.  It would be very helpful to us if you could retest with that version.

**Comment by justanotheranonymoususer** [comment]
Looks like it works now. Thanks.
![image](https://user-images.githubusercontent.com/5781692/65453803-94646900-de4c-11e9-86ad-c4d468b4d230.png)

**Comment by Waterman178** [comment]
> 9.1-BETA has just been released. It would be very helpful to us if you could retest with that version.

Where is 9.1? I only found the 9.0.4 release.
