### ISSUE TITLE
[Question] How would I run the program, inside the debugger?

### ISSUE THREAD

**Issue by trollmad3** [NationalSecurityAgency/ghidra#105]
A lot of debugging programs like `x64dbg` allows you to run the `.exe` inside the program. How would I do it? Is there a way?

**Comment by nsadeveloper789** [comment]
Ghidra does not currently have a debugger.

**Comment by trollmad3** [comment]
@nsadeveloper789 I was talking about CodeBrowser

**Comment by Ristovski** [comment]
@trollmad3 CodeBrowser is a tool within Ghidra, so the statement that it does not support debugging still applies.

**Comment by rogerclarkmelbourne** [comment]
I was looking for the same thing, e.g. connection to GDB.

I guess this could be raised as a feature request

**Comment by trollmad3** [comment]
@rogerclarkmelbourne I know this is off topic, but how would I create a feature request? I'm sure someone already made a request for this.

**Comment by rogerclarkmelbourne** [comment]
Just create an issue and then on the first screen, press the button to indicate it’s an enhancement or feature request rather than a bug,  I think this automatically adds a tag to the issue

**Comment by nsadeveloper789** [comment]
Sorry it's taken a while to follow up... The debugger (as announced in our RSA talk) is a work in progress. It's come quite a long way, but unfortunately, I don't have an ETA for you.
