### ISSUE TITLE
Standard Lib Functions showing up as ".text" 

### ISSUE THREAD

**Issue by ryancor** [NationalSecurityAgency/ghidra#1051]
**Describe the bug**
When analyzing a PE file, all standard lib functions (I.E., printf, fopen, strcpy) show up as ".text"

**To Reproduce**
1. Import a PE file
2. Go to imported functions
3. You'll see a whole list of ".text" labeled functions

**Expected behavior**
Expected behavior is to see the correct function signature.

**Screenshot**
<img width="1276" alt="Screen Shot 2019-09-23 at 8 03 46 PM" src="https://user-images.githubusercontent.com/15078524/65478288-0da88f80-de3e-11e9-99d9-654019d198f4.png">

**Environment (please complete the following information):**
 - OS: macOS 10.14.2
 - Java Version: 11.2
 - Ghidra Version: 9.1

**Comment by ryanmkurtz** [comment]
Thanks for the report.  Do you know if this is behaving correctly in 9.0.4?

**Comment by ryanmkurtz** [comment]
I'm not able to reproduce this on stock windows binaries.  Is there anything special about your test case?

**Comment by astrelsky** [comment]
> I'm not able to reproduce this on stock windows binaries. Is there anything special about your test case?

It was probably compiled with mingw. Likely related to #761

**Comment by ryancor** [comment]
Yes this was compiled with mingw, apologies for failing to mention that! thanks @astrelsky

**Comment by ryanmkurtz** [comment]
Could you provide a simple binary that has the bad behavior?

**Comment by astrelsky** [comment]
> Could you provide a simple binary that has the bad behavior?

[main.zip](https://github.com/NationalSecurityAgency/ghidra/files/3658726/main.zip)

The code for the above binary is below. I used it to triple check #1017 after I realized what was really supposed to happen.


```
float getValue(float* a_ptr) {
    return a_ptr[-4];
}

int getOne(int *a_ptr) {
    return a_ptr[-3];
}

int getTwo(int *a_ptr) {
    return a_ptr[-2];
}

int getThree(int *a_ptr) {
    return a_ptr[-1];
}

typedef struct A {
    int one;
    int two;
    int three;
};

int main() {
    struct A a[2];
    a[0].one = 1;
    a[0].two = 2;
    a[0].three = 3;
    printf("One: %d\n", getOne(&a[1]));
    printf("Two: %d\n", getTwo(&a[1]));
    printf("Three: %d\n", getThree(&a[1]));
    return 0;
}

```

**Comment by ryanmkurtz** [comment]
Thank you.  What did you use to zip that?

**Comment by astrelsky** [comment]
7zip
