### ISSUE TITLE
Minor, selecting a function  in symbol tree, not focusing reliably

### ISSUE THREAD

**Issue by Hardcore-fs** [NationalSecurityAgency/ghidra#1052]
Set a  function label....

Scroll thru some code.

Select the function label in "symbol tree"

Listing then homes to the function

Scroll tru some more code, select  function label (double click it's highlight)
listing window will not home, it will not home to function

Fix
deselect symbol tree  label,  by selecting another symbol tree label, then re-select  old symbol tree label.

Seems the trigger is tied to the wrong event?  focus not mouseclicked?

**Comment by dragonmacher** [comment]
This sounds like the same issue as described here https://github.com/NationalSecurityAgency/ghidra/issues/453.

**Comment by dragonmacher** [comment]
The fix for #453 will address this ticket.
