### ISSUE TITLE
Upload binaries to releases page instead of self-hosting on ghidra-sre.org

### ISSUE THREAD

**Issue by cblichmann** [NationalSecurityAgency/ghidra#1056]
**Is your feature request related to a problem? Please describe.**
See title. Download rates from ghidra-sre.org are slow (at least from Europe). And especially when there is a new version.

**Describe the solution you'd like**
Upload the release .zip file to the GitHub releases page, ideally signed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
Ghidra 10.0-BETA has been added to the [releases page](https://github.com/NationalSecurityAgency/ghidra/releases)
