### ISSUE TITLE
byte mapping previously byte mapped memory causes disassembly to fail

### ISSUE THREAD

**Issue by pixel-stuck** [NationalSecurityAgency/ghidra#106]
**Describe the bug**
When you create a second byte mapped memory region from an already byte mapped region, the data appears at the new memory location, but will not disassemble.

**To Reproduce**
1. Go to "Memory map" window in the code browser
2. Click on "+" button
3. Set type to "Byte mapped", set source address, new memory region address and size and click OK
4. Back in the "Memory map" window, click the "+" button again
5. Set type to "Byte mapped", set source address to previous byte mapped memory region, set size and new memory region address.
6. Go to byte mapped memory region set up in step 5 and attempt to disassemble instructions there

**Expected behavior**
Expected data at the memory region set up in step 5 to disassemble properly. These instructions disassemble properly at the original memory location as well as the byte mapped region set up in step 3, but not at the region in step 5. The data matched what was at the original location as well as the byte mapped location set up in step 3. NOTE: this was only tested with MIPS support.

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: chromium
 - Version: first public release

**Comment by ryanmkurtz** [comment]
Closing because i could not reproduce.  We can reopen it if you provide more details, such as screenshots of the problem you are seeing.  It's also possible this has been fixed in master...we made a lot of changes to the memory block code.
