### ISSUE TITLE
Decompilation broken for MIPS:BE:32:default

### ISSUE THREAD

**Issue by zeroKilo** [NationalSecurityAgency/ghidra#1060]
**Describe the bug**
Decompilation fails with error 
` Low-level Error: Could not find op at target address:`

**To Reproduce**
1. have MIPS:BE:32:default asm 
2. opcodes clearly gets disassembled 
3. functions are found, but 
4. on decompilation it fails with above mentioned message

**Screenshots**
 ![Example](https://i.imgur.com/MWZFS04.png)

**Environment:**
 - OS: Win7
 - Java Version: 12.0.2
 - Ghidra Version: 9.1-BETA

**Additional context**
I have developed a loader for [N64 Roms](https://github.com/zeroKilo/N64LoaderWV) and want to upgrade it for ghidra 9.1 (the code in that repo was already upgraded for 9.1 but the dist was left for 9.0.4)

**Comment by emteere** [comment]
Can you post the decompile debug .xml output file for this function?  The issue may not be at the instruction, as I can't duplicate the issue with a similar set of instructions.

**Comment by zeroKilo** [comment]
Sure, here 4 examples
[debug.zip](https://github.com/NationalSecurityAgency/ghidra/files/3650604/debug.zip)

**Comment by yaz0r** [comment]
For what it's worth, I'm seeing the same issue with the SH2 processor and 9.1-Beta, so probably not CPU related.
This is from a database upgraded from 9.0.4 and I'm also using a bunch of overlays. Let me know if you need extra info.

**Comment by emteere** [comment]
Possilbe overlay related.  It may be related to the new syscalls features, or the upgrade from 9.0.4.

**Comment by emteere** [comment]
@zeroKilo are any of your memory blocks overlays?

**Comment by zeroKilo** [comment]
well im not sure what you mean by overlayed. I create an InputStream for most blocks from a single byte[] array, the rom, and the 2 .spXXX blocks that are zeroed byte arrays. these blocks dont overlap in memory, the layout is like following:
![](https://i.imgur.com/xatOck7.png)

[here the bytestring of fun_800007ec](https://pastebin.com/msSN0Rrk)
[here the disassembly of fun_800007ec](https://pastebin.com/8HTe442R)
[here the actual rom file](https://github.com/NationalSecurityAgency/ghidra/files/3653831/GoldenEye.zip)
[here the function making blocks](https://github.com/zeroKilo/N64LoaderWV/blob/master/src/main/java/n64loaderwv/N64LoaderWVLoader.java#L146)
[here is how the makeblock function is used](https://github.com/zeroKilo/N64LoaderWV/blob/master/src/main/java/n64loaderwv/N64LoaderWVLoader.java#L118)

**Comment by yaz0r** [comment]
I reproduced the issue on my end with a clean new project in 9.1-dev and 2 segments (still with SH2)
Should I just attach the .gar file here? (1.7mb)

**Comment by emteere** [comment]
This is definitely an issue with overlays.  Your second parameter to MemoryBlockUtil.createInitialedBlock is actually creating an overlay block.

There appears to be a lookup issue with the decompiler and overlays, possibly associated with the new reference overrides for syscalls.

**Comment by zeroKilo** [comment]
yes you seem to be right, changing the second parameter to false lets the decompilation finish
![works](https://i.imgur.com/mGW6RrF.png)

is there anywhere to read about what overlays mean? I still dont understand the difference, whats it used for normally?

**Comment by yaz0r** [comment]
@zeroKilo overlays are used when you have multiple code segments that can be loaded at the same address in memory. Their address would overlap in memory, so you need to create them a separate overlays.

The root issue remains, as overlays are basically unusable in 9.1 due to this.

**Comment by emteere** [comment]
Agreed.  The overlay issue is a regression related to system call override changes, it is being diagnosed and will be fixed before release.

**Comment by zeroKilo** [comment]
@yaz0r thanks for the explanation

**Comment by yaz0r** [comment]
I would hardly call this issue resolved. @emteere do you need a new issue to track the overlay problem or want to reopen this?

**Comment by ryanmkurtz** [comment]
Fixed by bf4a17b67dff93b6a2555ceb4eed9ba85d019e05
