### ISSUE TITLE
Finding instances of a user defined StructureDataType using a script

### ISSUE THREAD

**Issue by esemwy** [NationalSecurityAgency/ghidra#1061]
I've been able to create structures in Ghidra, even via script. Now how do I find all the instances of a struct? By this I mean, I've defined many instances in memory of a user defined structure, and I now want to retrieve a list of all those addresses.

I can retrieve the ```DataType```.

```
DataType [] dtypes = getDataTypes("MyStruct");
```
I get back what I expect in ```dtypes[0]```. Now what? I haven't found anything helpful in the API docs or searching the source. Obviously I'm looking for the wrong thing.

**Comment by astrelsky** [comment]
There should be a method in DataTypeManager to retrieve all structures. As for in memory,  once it is created it becomes a StructureDB instance. You can iterate over all the defined data and check isStructure and get the address with getAddress.

**Comment by dev747368** [comment]
In the UI, right click on the struct, choose "Find Uses of".

For a script, you can model you code after the logic in FindReferencesToDataTypeAction.

**Comment by esemwy** [comment]
Thanks for the quick responses. I’ll give both of those a try, but it seems a bit complicated for what I thought was a common function.

**Comment by esemwy** [comment]
Got it! Thanks for the help. 
```java
DataTypeManager dtm = currentProgram.getDataTypeManager();
TaskMonitor monitor = getMonitor();
DataType struct = dtm.getDataType("/MyStruct");
Data d = getFirstData();
while (d != null) {
	if (monitor.isCancelled()) break;
        if (d.isStructure()  && struct.equals(d.getDataType())) {
		println(d.getDataType().getDisplayName()+" "+d.getAddress().toString());
	}
	d = getDataAfter(d);
}
```

**Comment by astrelsky** [comment]
Just for clarification, you are looking for the created data of the structures you defined in memory correct? To do it from the user interface you may do as dev747368 stated above.

Here is an example python function for use in a script. This will work if you are looking for the actual data in memory. It is a bit 'brute-force' but less complex.

```
def getAllDefinedData():
    data = getFirstData()
    while data:
        yield data
        data = getDataAfter(data)

def getDefinedStructures(structure_name):
    return [data for data in getAllDefinedData() if data.isStructure() and data.getDataType().getName() == structure_name]
```

I see you got it, was just about to add a java example. I will leave this here for reference if someone wants to do it in python.
