### ISSUE TITLE
Symbols are created but not processed

### ISSUE THREAD

**Issue by zeroKilo** [NationalSecurityAgency/ghidra#1063]
**Description**
when using any of these functions

`SymbolUtilities.createPreferredLabelOrFunctionSymbol`
`program.getSymbolTable().addExternalEntryPoint`
`program.getSymbolTable().createLabel`

it does create symbols in the symbol table but these are never processed. when clicking on them it says `address not found`

**Expected behavior**
It should start disassembling at those offsets and it should send me to the address when I click the symbol in the symbol table

**Screenshots**
 ![Example](https://i.imgur.com/x2DI7PA.png)
(architecture is PowerPC:BE:64:VLE-32addr)

**Environment:**
 - OS: Win7
 - Java Version: 12.0.2
 - Ghidra Version: 9.1-BETA

**Comment by dev747368** [comment]
Address offsets are specific to a address space.  How are you creating your address objects and does that match the address space where your function lives?

**Comment by zeroKilo** [comment]
seems I did it wrong before:
`Address addr = program.getAddressFactory().getDefaultAddressSpace().getAddress(address);` ([see here](https://github.com/zeroKilo/N64LoaderWV/blob/master/src/main/java/n64loaderwv/N64LoaderWVLoader.java#L202))

now im doing it like this: [https://pastebin.com/C7e4FzYH](https://pastebin.com/C7e4FzYH)

is there an easier way to create the address object?

**Comment by ghidra1** [comment]
The red symbols correspond to address locations not contained within any defined memory block.  Navigation within the Listing is limited to defined memory blocks only.

I believe the loader you wrote is creating Overlay memory blocks which do not correspond to the default address space.  I suspect your memory blocks should not be Overlay blocks which is intended for special cases where multiple blocks occupy the same physical address region.
