### ISSUE TITLE
Datastructure utility throws error

### ISSUE THREAD

**Issue by zeroKilo** [NationalSecurityAgency/ghidra#1064]
**Description**
When using the function `DataUtilities.createData` an exception is thrown:

> ghidra.program.model.util.CodeUnitInsertionException: Could not create Data at address

**To Reproduce**
Example function (that worked before): [https://pastebin.com/ArmFumAD](https://pastebin.com/ArmFumAD)

**Expected behavior**
It should create a data structure

**Environment (please complete the following information):**
 - OS: Win7
 - Java Version: 12.0.2
 - Ghidra Version: 9.1-BETA

**Comment by dev747368** [comment]
Is there a stack trace you can share?  Also, the size of your struct and the size of your memory block?

**Comment by zeroKilo** [comment]
well I should have added this as additional info like on my previous issue; I wrote a loader for N64 roms (just download any for testing) that worked before and is now broken, the exact use case would be [this line](https://github.com/zeroKilo/N64LoaderWV/blob/master/src/main/java/n64loaderwv/N64LoaderWVLoader.java#L115) in it, and here a deeper stack trace [https://pastebin.com/4kngEnwi](https://pastebin.com/4kngEnwi) that I made with `Msg.error(this, ExceptionUtils.getStackTrace(e));`

I hope that helps

**Comment by dev747368** [comment]
Size of the struct, and memory block?

**Comment by zeroKilo** [comment]
struct is 0x40 in size, and memory block is as big as the loaded rom

**Comment by dev747368** [comment]
My first guess is that you are trying to use an address from the default address space instead of from the address space of your overlay memoryblock.
The MemoryBlockUtils.createInitializedBlock() will return a MemoryBlock.  Use its start address (.getStart) as the address of your structure.

**Comment by zeroKilo** [comment]
thanks, that solved it! [I changed it to this](https://pastebin.com/9QZV9dpz) and that works now, but can you explain why addresses have to be dealt with in this way? why cant addresses be normal integers?

**Comment by dev747368** [comment]
Different computer architectures have different memory capabilities.  In this case, your overlay memory blocks represent a chunk of memory that isn't unique in 'owning' its offset.  (ie. paged memory, etc)

**Comment by zeroKilo** [comment]
hmm, I dont understand why it cant choose the right block by itself, but thanks for the answer
