### ISSUE TITLE
Export Tool does not save all user preferences

### ISSUE THREAD

**Issue by ebfe2326** [NationalSecurityAgency/ghidra#1065]
**Describe the bug**
The export tool options does not seem to export all user preferences.  All of the options located in the Edit / Tool Options appear to be saved, but if an option is not in the tool options, it does not get saved.  A few examples I've noticed are below.  Without these preferences being saved, it means you can not share settings with other analysts or copy Ghidra into a new VM without manually setting everything up again.  The "Edit Code Block Fields" setting not being saved are especially troublesome because these are settings that greatly affect readability of the code.

- if the script directories are modified, it is not saved in the exported tool

- In the Graph view, no customization's appear to be saved.  Specifically, I've notice the following settings are not saved in the exported tool:
  * block hover mode
  * block focus mode
  * any changes made to the Edit Code Block Fields

Most of these preferences seem to be stored in the tool.tcd file, e.g. code_browser.tcd, but don't get exported to the tool file, e.g. code_browser.tool

**To Reproduce**
1. Set user preferences such as the Edit Code Block Fields
2. Export Code_Browser Tool
3. Import Code_Browser Tool into Ghidra in a new VM
4. Notice code block field changes are not present

**Expected behavior**
I'd expect that when you export the code_browser tool, all user preferences should be saved in this export

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: OpenJDK 12.0
 - Ghidra Version: 9.1_Beta

**Comment by Hardcore-fs** [comment]
Confirmed this when I moved to 9.1
in the listing  display, the formatting changes made in the "listing fields"  do not appear to get carried over.

**Comment by dragonmacher** [comment]
This may be an issue of poor/unintuitive design.  
If you modify and then export your tool *without saving it*, then the results you describe appear (at least with regard to the Field Formatter changes).

However, if you change you base tool as desired and then either save it or simply close it (which performs a save) before exporting, then the changes should appear in the new tool.

Can you please test this approach to see if it fixes any/all of the issues you have mentioned?

**Comment by ebfe2326** [comment]
short answer is saving the tool doesn't seem to fix any of the issues.  All off the "Edit field listings" options still aren't being saved with the exported tool..

To test it out, I opened Ghidra on my base machine.  Here I have the default codebrowser tool and a codeBrowser_1 that I have modified.  I opened a file in the modified codeBrowser_1 tool, verified everything was set as expected, selected file / save tool, then did file / export tool.

I spun up a fresh VM and installed ghidra 9.1_beta and imported my modified codeBroswer_1 tool.  When I opened up a file in this new VM, all of the settings in the edit / tool options were present, but everything outside of that was still missing (primarily the edit field listings, but also the other options such as block hover mode, block focus mode, etc.)

If I look in %USERPROFILE%\\.ghidra\\.ghidra_9.1_BETA_DEV\\tools\\ and compare the _code_browser__1.tcd file to the exported code_browser_1.tool file, I see the modified times are the same, but the file sizes are pretty different.  The .tcd file ghidra is using is 104kb while the exported .tool file is only 76kb.    I'm assuming the 30 missing kb accounts for the missing settings.

I also opened up the two files to compare.  For one example, i searched for "hover" to see if i could find the block hover mode settings.  There are a few entries in the working .tcd file, but no "hover" string at all in the exported .tool file.

**Comment by dragonmacher** [comment]
While investigating this I see that there are 2 code paths for exporting the tool: one from the tool itself and one from the Front End's tool button in the Tool Chest (available when you right-click the icon).

The File - > Export action will *exclude* the current tool's config state (not sure why).  The Front End button's export code does not seem to do this.   **The settings do get included for me when I use the Front End's version of the action.**

There should not be 2 code paths.   This is something we should address.

**Comment by Hardcore-fs** [comment]
I would have to say that might only be a partial solution.
My tools for the code were saved over several days in multiple save events.
I then opened 9.0, exported, shut it down ,opened 9.4 imported and found my code layouts had reverted to default.

It might be related to some "home" issue, where if you put 9.4 over the same location of 9.0 it recovers the data correctly, but in my case the 9.4 prog was in a different folder before the import.
The other thing, was that i had to delete the "tool" file "x.gpr" before the import, becasue  the previous attempt at import into 9.4 complained the  file already existed, even it did not show up in the projects.

**Comment by dragonmacher** [comment]
@Hardcore-fs Not sure if this is related to what you are seeing, but Ghidra, on a fresh install, will pull in your tools from your most recently used version.  This will only happen when your first launch the new Ghidra installation.

**Comment by ebfe2326** [comment]
Thanks for the help!  It looks like the 2 export paths was the problem for me.  

The settings not saved from inside the tool itself are ones that I've also tried changing, closing down Ghidra, re-opening, and then later exporting from within the tool and it still didn't save all of the settings.  I'm not sure why they weren't exported since they weren't recent changes and they were saved in a location that Ghidra found when I re-opened the tool.

But in any case, if I export the tool from the front end's tool button like you suggested, then all of my settings do appear to be exported and it works as expected.  If I check the exported tool file against the .tcd file, the file sizes also match.

I think it's a lot more intuitive to export the tool from inside the tool itself.  If both export paths export the tool in the same manner, that would be a good fix for this bug.
