### ISSUE TITLE
User defined Data types not tracking changes

### ISSUE THREAD

**Issue by Hardcore-fs** [NationalSecurityAgency/ghidra#1066]
if you define a data structure say:
fulldisplay
long
long
long 
long

then apply it to whatever data you are working with, it formats the data

but if you then go in and change the structure
fulldisplay
pointer
long
long 
long

save the update, the changes are not reflected in any structure made before the change
only after the change.  so any pointers to strings don't display correctly.

I would expect the formatting to be reapplied to all relevant structures
the images show 3 cases:

1. the default definition
2. the same area with the changed definition
3. the area stripped & the definition from 2 re-applied

so it appears the only way to get a changed struct type to display correctly after a change is to reapply it, to all instances.
Oh.. and by default if the display data was wrong, after the struct update all old applicable structures display wrong data

1.
![default](https://user-images.githubusercontent.com/1309004/65564824-ad6e3680-df80-11e9-9beb-5731bafb4271.jpeg)

2.
![updated](https://user-images.githubusercontent.com/1309004/65564838-b9f28f00-df80-11e9-87f5-818bb6ba478d.jpeg)

3.
![reapplied](https://user-images.githubusercontent.com/1309004/65564856-c4148d80-df80-11e9-988c-b59f31bba5ac.jpeg)

Also in the data structure, it should warn  about your computer bursting into flames if you change the size of the structure... then there is the situation with recursion & user-defined structures.. it may even need a whole new display for conflict resolution on size change.

 - OS: [e.g. macOS 10.13.2]
 - Java Version: [11.0]
 - Ghidra Version: [9.1]

**Additional context**

**Comment by ghidra1** [comment]
This is a know issue.  Reconciling composite Data instantiations against composite modifications is non-trivial and requires an exhaustive search of uses (including nested instances) plus proper correlation of components to be able to move or delete old markup (e.g., references, settings, comments, etc.).   It may be best to clear and recreate data containing modified structures when it is warranted.  We will continue to consider how to better cope with this situation but any short-term solution is unlikely.  If you are not concerned with any explicit markup/settings on composite Data instances, it would be very straight forward to write a script to clear and recreate all composite Data instances (including composite Typedefs).

**Comment by Hardcore-fs** [comment]
Yep I know it's non trivial, 
but perhaps the user data types could be treated like "functions" and  added into the structure tree so that their exact location is known...
Then if their overall size is not changed, it's a simple "slot in", if the size is changed a pop-up window with snap-links, for the user to go thru & appy manually....

**Comment by ghidra1** [comment]
It's not as simple as you indicated.  This does not account for nested structures or any user markup which may have been made at locations internal to a structure.  While we can quickly identify the placement of the outer-most structure, it becomes more involved to identify the nested instances - although this is all doable albeit slow.  While structures currently do update within the listing, their markup does not (e.g., references, settings, comments, etc.) which you initial complaint.  It is the markup reconciliation which is the real dilemma.

**Comment by Hardcore-fs** [comment]
Looking at it,
when the data structure edit window is open
The user defined data types tracks the total size of all nested elements, so as long as there is not an overall size change, it should just be a case of re-triggering the  type on the already selected section (as per a user would) to reapply any formatting & markup, I can already do this manually and it works.
any overall size changes would be a different matter ,
However:
 sub elements would have to be checked to ensure they were not applied to any areas as "Stanalones",  or other data structures  (if it were the sub element that had changed)
so as not to break the initial size change rule.
don't see why it would be slow, as it would be a perfect case for multiple threading, using an entry table as the initial filter(for container & sub-container elements), if it ain't in , it becomes trivial as long as NO size changes.

**Comment by ghidra1** [comment]
It should be straight forward if you are familiar with Eclipse.  See the [developers guide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md) for more info.

**Comment by Hardcore-fs** [comment]
Yep it was.... the instructions are a bit mangled for osx.
few thousand warnings... about datatype "casts"  but got it built & tested on osx64 bit

Due to the scale of the project the learning curve is steeper than the Matterhorn
any pointers on where to start ref  above?

**Comment by ghidra1** [comment]
Are you interested in the easy approach of re-creating all structure data to pickup any changes which may have been made, or were you considering something much more ambitious?
