### ISSUE TITLE
9.1 Changelog: Missing Info About SuperH SH-1, SH-2, and SH-2A

### ISSUE THREAD

**Issue by VGKintsugi** [NationalSecurityAgency/ghidra#1067]
I glanced at the 9.1 Beta package. I noticed that the changelog doesn't mention the addition of the SuperH SH-1, SH-2, and SH-2A processor modules.

**Comment by mumbel** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/91e4fd7fb7e00a970c8f35f05c4590133937e174/Ghidra/Configurations/Public_Release/src/global/docs/ChangeHistory.html#L167

**Comment by ryanmkurtz** [comment]
For some reason it's in the bugs section.

**Comment by ryanmkurtz** [comment]
Fixed by 36b07777d727b982798557fa87bc77f4c1c3d7c0
