### ISSUE TITLE
An Error occurred while connecting to the server. Connection reset

### ISSUE THREAD

**Issue by phate1** [NationalSecurityAgency/ghidra#1068]
**Describe the bug**
while trying to connect to Ghidra server receiving "error occurred while connecting to the server Connection reset". Ghidra was built from source to get access to the new switch for nat'ed environments as this is running in OpenStack.
security group set to allow 13100 13101 and 13102 TCP also tried allowing all TCP and UDP getting the same result.
connecting to DNS or direct to IP gives the same issue.

although the connection reset occurs 90% of the time it also sometimes returns non-JRMP server at remote endpoint

**To Reproduce**
1. install server after building from source
2. change server.conf argument -ip <dns name> -i <localip>
3. try to connect to the server using new project - shared
4. enter dns name port 13100
5. See error

**Expected behavior**
the connection should establish successfully

**Screenshots**

**Attachments**

[wrapperlog.txt](https://github.com/NationalSecurityAgency/ghidra/files/3651797/wrapperlog.txt)

[serverconf.txt](https://github.com/NationalSecurityAgency/ghidra/files/3651741/serverconf.txt)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Java Version: 11.0.4
 - Ghidra Version: ghidra_9.1_DEV

**Additional context**
out of idea's how to resolve this any assistance gratefully received

**Comment by dev747368** [comment]
Can you capture the network traffic to see the socket open/close activity?

**Comment by phate1** [comment]
attached a capture while trying a connection:
[caputure.txt](https://github.com/NationalSecurityAgency/ghidra/files/3653393/caputure.txt)

**Comment by dev747368** [comment]
Thanks for the capture.

I'm not seeing any attempts to connect to any other RMI ports on the server.  Was the capture file filtered?  And was the capture on the client or server side?

Could you verify that you can connect to your server on port 13100-13102 from the client using <removed_hostname>.net as the name?

**Comment by phate1** [comment]
hi so this was tcdump on the server side just filtering out ssh (sudo tcpdump -i ens3 port not 22)
so i can telnet to all those ports from the client and it connects ok using the domain name

**Comment by dev747368** [comment]
Is there anyway to see the socket connection activity from the client side?

**Comment by dev747368** [comment]
also, far shot, could you try the beta build that was just released, for both the client and server?

**Comment by phate1** [comment]
![image](https://user-images.githubusercontent.com/1298031/65621873-787fd500-dfbc-11e9-8b43-8e456b251d9d.png)
does this show what you want to see just filtered on src or dst being the IP of the server

ill get client and server rebuilt using the latest beta shortly and see how i get on as im running the public build for client and the dev build on server could be it.

**Comment by dev747368** [comment]
I would try updating the client to the beta release first.

**Comment by dev747368** [comment]
And instead of filtering on IP, can you filter on just the port numbers (13100-13102)?  In case the client is trying to use a bad address.

**Comment by phate1** [comment]
updating client to beta solved the issue thanks !
