### ISSUE TITLE
ApplicationUtilities/GhidraClassLoader jarmanifest support

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1071]
**Is your feature request related to a problem? Please describe.**
Ghidra is unable to launch when a jarmanifest is used to shorten the command line. Some IDEs use this method when launching a java project. Notably the vscode java test runner.

**Describe the solution you'd like**
ApplicationUtilities.findPrimaryApplicationRootDir should check if the classpath returned by System.getProperty("java.class.path") is a jarmanifest iff classpath.length == 1.

**Describe alternatives you've considered**
Opening an issue at https://github.com/microsoft/vscode-java-test for there being no option for how the command line is shortened. However, having this done here may ease difficulties with using other popular IDEs besides Eclipse. 

**Additional context**
The local variable classpath before entering the loop is:
`classpath: String[1]@43 "c:\Users\astre\AppData\Roaming\Code - Insiders\User\workspaceStorage\8b07a3b88fd3fded0d9e897a7bef724a\vscjava.vscode-java-test\1569444187407\path.jar"`
Also my terminology may be horridly incorrect here. Still new to Java.

Below is an example of the changed method which I am using to make it work in the meantime. I'm not exactly sure if this is the best way to accomplish this though.

```
private static ResourceFile findPrimaryApplicationRootDir() {
		String[] classpath = System.getProperty("java.class.path").split(File.pathSeparator);
		if (classpath.length == 1 && classpath[0].endsWith(".jar")) {
			try {
				JarFile jar = new JarFile(new File(classpath[0]).getCanonicalPath());
				Attributes attributes = jar.getManifest().getMainAttributes();
				classpath = attributes.getValue("Class-Path").replace("file:///", "").split(" ");
			} catch (IOException e) {
				Msg.error(ApplicationUtilities.class, "Invalid Jar Manifest Class-Path", e);
			}
		}
		for (String pathEntry : classpath) {
			try {
				ResourceFile pathFile = new ResourceFile(new File(pathEntry).getCanonicalPath());
				while (pathFile != null && pathFile.exists()) {
					if (new ResourceFile(pathFile, ApplicationProperties.PROPERTY_FILE).exists()) {
						return pathFile;
					}
					pathFile = pathFile.getParentFile();
				}
			}
			catch (IOException e) {
				Msg.error(ApplicationUtilities.class, "Invalid class path entry: " + pathEntry, e);
			}
		}
		return null;
	}
```

**Comment by ryanmkurtz** [comment]
Ghidra requires the Utility module to be on the classpath at launch time.  Where are those classes/jar when launched from vscode?  In path.jar?

**Comment by ryanmkurtz** [comment]
From: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug

> shortenCommandLine - When the project has long classpath or big VM arguments, the command line to launch the program may exceed the maximum command line string limitation allowed by the OS. This configuration item provides multiple approaches to shorten the command line. Defaults to auto.
> none - Launch the program with the standard command line 'java options classname [args]'.
> jarmanifest - Generate the classpath parameters to a temporary classpath.jar file, and launch the program with the command line 'java -cp classpath.jar classname [args]'.
> argfile - Generate the classpath parameters to a temporary argument file, and launch the program with the command line 'java @argfile [args]'. This value only applies to Java 9 and higher.
> auto - Automatically detect the command line length and determine whether to shorten the command line via an appropriate approach.

Can you control it with that?

**Comment by astrelsky** [comment]
> From: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug
> 
> > shortenCommandLine - When the project has long classpath or big VM arguments, the command line to launch the program may exceed the maximum command line string limitation allowed by the OS. This configuration item provides multiple approaches to shorten the command line. Defaults to auto.
> > none - Launch the program with the standard command line 'java options classname [args]'.
> > jarmanifest - Generate the classpath parameters to a temporary classpath.jar file, and launch the program with the command line 'java -cp classpath.jar classname [args]'.
> > argfile - Generate the classpath parameters to a temporary argument file, and launch the program with the command line 'java @argfile [args]'. This value only applies to Java 9 and higher.
> > auto - Automatically detect the command line length and determine whether to shorten the command line via an appropriate approach.
> 
> Can you control it with that?

Unfortunately the test runner automatically sets it as jarmanifest regardless of the launch settings.  The entire classpath is being put into the parh.jar's manifest file. I opened an issue  for the viscose have test runner for controlling that option. I can fully debug ghidra from viscose I just can't run the tests from it. I'm not entirely sure if this is really something ghidra should support or not.

**Comment by ryanmkurtz** [comment]
Ah ok, i understand.  Let's see what the vscode-java-test people say about it and go from there.

**Comment by astrelsky** [comment]
> Ah ok, i understand. Let's see what the vscode-java-test people say about it and go from there.

Ok that sounds good. Just for reference here is a link to the issue. https://github.com/microsoft/vscode-java-test/issues/824

**Comment by astrelsky** [comment]
Considering this is likely unnecessary I'm going to close this.
