### ISSUE TITLE
Support current Intel x86/x64 manuals (again)

### ISSUE THREAD

**Issue by aamcintosh** [NationalSecurityAgency/ghidra#1078]
Version 9.1 of Ghidra has switched to Intel's 325383-60US manual for the instruction set reference.  Thank you.  This is still available on Intel's website.  However they appear to have issued 325383-70US in May of this year.  It is what you get if you start here: https://software.intel.com/en-us/articles/intel-sdm.  The two manuals are off by 1 page on the last opcode so it's not a big deal.  However, someone might want to consider updating the index file sometime.

**Comment by GhidorahRex** [comment]
Fixed in 4c31ac66ce3d80d7b0aabfa8fa7a6267b3ef60b6

**Comment by lmstearn** [comment]
As of late, pointed to the Instruction Set Reference, A-Z (O/N 2016) for the Intel® 64 and IA-32 Architectures
Software Developer’s Manual, Volume 2 (2A, 2B, 2C & 2D) on the following page:
https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html#inpage-nav-2
Link redirected according to website reshuffle.
