### ISSUE TITLE
Deadlock while analysing firmware

### ISSUE THREAD

**Issue by chrismiller** [NationalSecurityAgency/ghidra#108]
**Describe the bug**
Deadlock while analysing ARM firmware

**To Reproduce**
I can't provide the firmware I'm analysing due to copyright reasons unfortunately.

**Expected behavior**
The analysis to complete successfully.

**Screenshots**
The stacktrace below shows the deadlock

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: Ghidra 9

**Additional context**

[thread dump moved to an attachment]

**Comment by nneonneo** [comment]
Please provide the log as an attachment; it's hard to read as formatted text.

**Comment by chrismiller** [comment]
Here you are:

[thread-dump.txt](https://github.com/NationalSecurityAgency/ghidra/files/2945198/thread-dump.txt)

**Comment by ryanmkurtz** [comment]
Closing due to inability to recreate.
