### ISSUE TITLE
Fallthrough override doesn't work

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#1083]
Usual example:
Function uses a data, that is located just after the function call, like this:
```
call printf
ds "my string"
ret
```

When I'm trying to change it using Auto override, or by specifying "JUMP_OVERRIDE_UNCONDITIONAL" it doesn't change anything in decompiler output.

**Comment by lab313ru** [comment]
I can't point to `ret` in this case so it will be shared with the decompiler.

**Comment by ghidra1** [comment]
We need to correct the fallthrough override case where the default pcode does not perform an explicit  branch to the next instruction resulting in a normal fallthrough.  If the last pcode operation is not an unconditional jump and additional fallthough override jump should get injected.
