### ISSUE TITLE
Many different overriding features

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#1084]
I found:
- Fallthrough override (CALL, BRANCH, CALL_TERMINATOR)
- CALL/JUMP_OVERRIDE_UNCONDITIONAL
- CALLOTHER/JUMPOTHER_OVERRIDE_UNCONDITIONAL

Why not start using the Fallthrough override instead of that all strange and the-same-looking types?

**Comment by ghidra1** [comment]
These all target specific cases and are intended to override the default pcode flow as interpreted by the decompiler and other forms of analysis.  The fallthrough reference override only addresses the drop-through case where the fallthrough address does not immediately follow an instruction.  For instance, a call instruction has both a fallthrough flow and a call flow.  The fallthrough override is intended to only override the fallthrough flow destination.  All of these override mechanisms have limitations which can influence there effectiveness.
