### ISSUE TITLE
Display Function Call Tree button won't open a new tab.

### ISSUE THREAD

**Issue by DaniloNC** [NationalSecurityAgency/ghidra#1087]
**Describe the bug**
`Display Function Call Tree` button won't open a new tab to the function under the cursor.

**To Reproduce**
1. Go to any function
2. Click on the `Display Function Call Tree` button
3. `Call tree` window will appear
4. Go to another function
5. Click on the `Display Function Call Tree` button
6. New call tree tab * won't* open

**Expected behavior**
Whenever one click on the `Display Function Call Tree` button, a new tab (or if present, switch to that tab) should be created to the current function under cursor.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: 11.0.4
 - Ghidra Version: 9.1-Beta

**Comment by dragonmacher** [comment]
For better or worse, this is as designed.

1. Pressing the button on the toolbar will reuse the same provider window
2. Right-clicking on a function and pressing **References - > Show Call Trees** will show the selected function in a new tab.

This setup allows for 2 modes of usage: to have the main window track the function under the cursor in the Listing; or to have a new window open upon request that will not track locations by default.

**Now, all of that being said, the tracking feature appears to not be working correctly.**
