### ISSUE TITLE
Getting function call parameter values

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1088]
I'm looking to grab the values of constants which are being passed as parameters in a function call. My intention in doing this is to make use of calls to __dynamic_cast to determine instances of classes in memory and class variables. I know I could take a reference to __dynamic_cast and back track to previous constant references but I need to know which parameter is which.

**Comment by astrelsky** [comment]
Well I managed to figure it out. It's not very straightforward because the Varnodes you get from and instructions PcodeOP and the Variables you get from the Function interface don't actually hold any values. If you want to retrieve the value you have to run the SymbolicPropogator through the function.

**Comment by Alex97** [comment]
Any chance you could share the code for doing that? I'm trying to get the arguments used when calling a function. One of them is not exactly a constant value, but it is computed from constant values, so it should be possible to derive its value. The decompilation view correctly computes it, but I have no idea how to do it myself in code and this issue is the closest thing I could find to what I need, beside a couple of blog posts about trying to derive the value from the P-Code.

**Comment by astrelsky** [comment]
> Any chance you could share the code for doing that? I'm trying to get the arguments used when calling a function. One of them is not exactly a constant value, but it is computed from constant values, so it should be possible to derive its value. The decompilation view correctly computes it, but I have no idea how to do it myself in code and this issue is the closest thing I could find to what I need, beside a couple of blog posts about trying to derive the value from the P-Code.

@Alex97 you can see a concrete example of what is needed [here].(https://github.com/astrelsky/ghidra_scripts/blob/ac3caaf7762f59a72bfeef8e24cbc8d1eda00657/PrintfSigOverrider.java#L292-L317) Once you have the [SymbolicPropogator](https://ghidra.re/ghidra_docs/api/ghidra/program/util/SymbolicPropogator.html) from the analyzeFunction method you should be able to get the parameter value you're looking for as long as it is in a register. Unfortunately it does not work for calling conventions that pass parameters on the stack. I have yet to figure out how to correctly do the analysis for stack parameters.

**Comment by Alex97** [comment]
Thank you for the quick response. I will check it out.

**Comment by astrelsky** [comment]
> Thank you for the quick response. I will check it out.

No problem.  I've actually submitted pr #1489 which adds a utility class for this purpose. You can just copy and paste those methods and it should serve your purposes.

**Comment by ryanmkurtz** [comment]
Have you tried the [ShowConstantUse](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/ghidra_scripts/ShowConstantUse.java) script that comes with Ghidra?
