### ISSUE TITLE
Unresponsive GUI with large stack frame (~1600 local vars)

### ISSUE THREAD

**Issue by rmbreak** [NationalSecurityAgency/ghidra#109]
**Describe the bug**
GUI becomes unresponsive for an unreasonable amount of time when analyzing the attached file. Attached file consists of a single function that has its stack frame initially set to ~1600 local vars of type undefined1. After a couple of minutes the UI becomes responsive, but if you click around in the Decompile view it freezes again.

**To Reproduce**
1. Create a new project in Ghidra
2. Unzip and Import the attached file, [bigstack.zip](https://github.com/NationalSecurityAgency/ghidra/files/2944051/bigstack.zip) to the project (x86:LE:32:default:windows)
3. Open bigstack.bin in the CodeBrowser
4. When prompted to begin analysis, press yes and accept the defaults

**Expected behavior**
GUI is responsive.

**Environment (please complete the following information):**
 - OS: Win10

**Comment by dragonmacher** [comment]
I believe this has been fixed by #2351
