### ISSUE TITLE
Move sleigh to separate repository

### ISSUE THREAD

**Issue by jstaursky** [NationalSecurityAgency/ghidra#1098]
I'm interested in incorporating the sleigh decompiler in a personal project, and it would be nice to have it in its own repo, so I don't need to clone all of ghidra. 

I also think it would get more attention by the community if it were put in a separate repo to emphasize its use outside of ghidra.

It would also help because projects wanting to use sleigh as a dependency can `git pull` from a repo rather than a subfolder of another repo (not even sure thats possible).

**Comment by VGKintsugi** [comment]
Duplicate of #473
