### ISSUE TITLE
Ghidra appearing to not find referenced libraries

### ISSUE THREAD

**Issue by Kreeblah** [NationalSecurityAgency/ghidra#110]
**Describe the bug**
When I try to import certain binaries, Ghidra warns that it can't find some referenced library files.  Except, when I look at the locations where it says they weren't found, they're there.

**To Reproduce**
1. Use Homebrew to install xz (brew install xz)
2. Create a new project in Ghira
3. Import the xz binary into Ghira
4. Leave the default import settings
5. See the below error:

`----- Loading /usr/local/Cellar/xz/5.2.4/bin/xz -----`
`Skipping segment: __PAGEZERO (xz)`
`  [/usr/local/Cellar/xz/5.2.4/lib/liblzma.5.dylib] -> not found`
`  [/usr/lib/libSystem.B.dylib] -> not found`

6. Look for the referenced libraries:

`$ ls -l /usr/local/Cellar/xz/5.2.4/lib/liblzma.5.dylib`
`-r--r--r--  1 user  staff  134356 Feb  9 17:06 /usr/local/Cellar/xz/5.2.4/lib/liblzma.5.dylib`

`$ ls -l /usr/lib/libSystem.B.dylib`
`-rwxr-xr-x  1 root  wheel  60880 Jan 15 17:21 /usr/lib/libSystem.B.dylib`

**Expected behavior**
I'd expect that warning to not show up, and for the import to finish cleanly.

**Environment (please complete the following information):**
 - OS: macOS 10.14.3
 - Java: OpenJDK 11.0.2+9
 - Ghidra: 9.0_PUBLIC_20190228
 - xz binary version: 5.2.4

**Additional context**
I'm also wondering whether this could be related to the following errors I receive after analyzing the binary using the default analysis settings:

`Failed to create "no return" function __la_symbol_ptr::___stack_chk_fail at 10000c078`
`Failed to create "no return" function __la_symbol_ptr::_exit at 10000c0a0`

**Comment by zhangbo** [comment]
Same issue too

**Comment by ryanmkurtz** [comment]
Possibly related to #136

**Comment by adamopolous** [comment]
Turns out this is a different animal than #136; that one describes a failure to properly parse universal binaries. This ticket is the result of failing to properly recurse through the dependencies of the external libraries being loaded. As @Kreeblah noted, the libraries exist but we don't process them. 

And I don't believe this is specific to any particular binary type (at least it shouldn't be).

**Comment by EmpRamses** [comment]
This problem also occurs in my projects. However, my Ghidra is the latest version compiled with jdk 12.
