### ISSUE TITLE
Is there a scripting function to set the automatic comments?

### ISSUE THREAD

**Issue by ebfe2326** [NationalSecurityAgency/ghidra#1100]
I've been looking for a scripting method to set or clear the automatic comments.  I see I can get the automatic comments via the DisplayableEol.getAutomaticComment, but I can't find any scripting function that allows me to change or delete the automatic comment.  Am I just missing the function or is this not possible with the scripting API?

**Comment by astrelsky** [comment]
There is clearComments in the Listing interface:
void clearComments​(Address startAddr, Address endAddr)

**Comment by astrelsky** [comment]
you can use setEOLComment and pass in null or an empty string as the comment. (I passed None in python)

To grab the address of the DisplayableEol use eol.getProgramLocation().getAddress(). I believe this will do what your looking for.

If your looking to clear comments in a range of addresses, you can try the clearComments in the Listing interface, but it will remove everything.

**Comment by ebfe2326** [comment]
hmm, i'm still learning about ghidra scripting.  but unless i'm missing something, both setEOLComment and clearComments don't affect the automatic comments.  When i tested them out, setEOLComment only sets the end of line comment, not the automatic comment.  clearComment appears to clear all the user defined comments, but not the ghidra generated automatic comment. 
 
The DisplayableEoL has a function, getAutomaticComment, that will get the ghidra generated automatic comment, but no way to set it.  It seems like if there's a get method, there would also be a set method, but i can't find it.

**Comment by astrelsky** [comment]
> DisplayableEoL

My apologies, I believe I misunderstood. For some reason I thought you wanted to remove them.

This is the documentation for the method hasAutomatic
`Return whether this code unit has an automatic comment. (i.e. any memory reference from this code unit has a function defined at the reference's to address, or if the to address is a pointer.)`

I believe this might be used internally. If you have a string pointer in a data section and create the pointer the automatic eol comment would be " = stringPointedTo"

**Comment by ebfe2326** [comment]
I appreciate the help, but hasAutomatic doesn't do anything for setting the automatic comments.  Hopefully a ghidra developer can chime in to say if there is an API that allows me to set these automatic comments.

**Comment by astrelsky** [comment]
> I appreciate the help, but hasAutomatic doesn't do anything for setting the automatic comments. Hopefully a ghidra developer can chime in to say if there is an API that allows me to set these automatic comments.

No problem. I showed the documentation for hasAutomatic because it provides an example of what the automatic comment is. I'm have a feeling that you may be misusing DisplayableEol which is why I asked  what you were looking to do. Maybe a more appropriate question would have been why are you trying to set/clear automatic comments. 

I will leave this for a developer to answer. However explaining why you are looking to do this may help if there is a more appropriate class to use.

**Comment by dragonmacher** [comment]
> Hopefully a ghidra developer can chime in to say if there is an API that allows me to set these automatic comments.

There currently is no API for controlling auto comments.   Typically uses will simply apply comments as desired from the GUI or a script.  All non-automatic comments will get saved to the program database.  **If you really wish to control the Listing display *dynamically* (as does the auto comments field), then you can create your own custom Field Factory, replacing the behavior of the `EolCommentFieldFactory`.**   Field Factories are `ExtensionPoint`s in Ghidra (just as are `Plugin`s).  If you create a new factory and ensure that it is on the classpath, then Ghidra will find it and make it available for use in the tool.

**Comment by ebfe2326** [comment]
thanks for the info.  i didn't realize the auto comments field was applied dynamically.  given how many api's there are, i thought i must just be missing the function to set automatic comments.  I'll look into the Field Factory.  I'm interested in minimizing automatic function comments, but want to keep all of the rest of the automatic comments.  Most are pretty helpful, but the function prototype comments just clutter up the view for me without adding much value.

**Comment by dragonmacher** [comment]
Just as a clarification, the EOLCommentsFieldFactory is responsible for the end-of-line comments.   Within that factory, there are 2 types of comments: 1) those in the database and 2) those that are generated dynamically.

The API allows users to set EOL comments, which will be stored in the database; the dynamic comments are not in the database and are created on-the-fly.

My hope is that we update the Tool Options so that you can more finely control how the *automatic* comments work, allowing you, in this case, to turn off the auto function comments.

**Comment by ebfe2326** [comment]
Updating the tool options would be  great.  Just to give you some user feedback.  If there was an option in Tool options to hide **just** the automatic function comments without hiding the other automatic comments, that would be wonderful.  I've found most of the automatic comments on things like data variables are helpful.  The only exception I've had are the function automatic comments.  Normally they wouldn't bother me too much, but because make heavy use of the graph view and the function comments are so long without adding and real value, it tends to just supersize all of the code blocks for no reason so less code blocks are visible on the screen.

The best work around I have so far is a script to add a space to all function repeatable comments.  That way, instead of seeing the long automatic comment, you only have a single space added which isn't noticeable.  This is kind of a kuldgy work around that I was hoping I could do more elegantly with an API that I couldn't find, but it'd be even better to have a legit option for this.  Thanks for all the hard work so far.
