### ISSUE TITLE
Cant even get it to open...

### ISSUE THREAD

**Issue by zSerity** [NationalSecurityAgency/ghidra#1107]
![Capture](https://user-images.githubusercontent.com/56057431/66014128-859c3880-e482-11e9-99e2-0a0aecf341f4.PNG)
This is all I get, made sure everything was installed. Had all environmental variables set.
I have Java RunTime and JDK all latest, and setup correctly.

**Comment by ryanmkurtz** [comment]
What OS version is that?  I want to say windows 10, but your X button and close button look weird.  Does Ghidra 9.1-BETA start up for you?

**Comment by zSerity** [comment]
Yeah, its windows 10. All versions suffer from the same thing, wont get passed the start up:)

**Comment by ryanmkurtz** [comment]
Do you have any 3rd party GUI mods installed?

**Comment by zSerity** [comment]
Yes, however I disabled it back to default windows 10. Same thing happens.

**Comment by ryanmkurtz** [comment]
This looks like a similar problem: https://www.filebot.net/forums/viewtopic.php?t=5614

Are you able to get past the exception and change Ghidra's theme under Edit -> Tool Options... -> Tool -> Swing Look and Feel?

**Comment by zSerity** [comment]
Cant get passed the main load, nothing opens up. Just gets stuck there
endlessly.

**Comment by dragonmacher** [comment]
The Look and Feel can be changed directly in the preferences.

1. Close Ghidra
2. Text edit `user home/.ghidra/.ghirda_version/preferences`
3. Change (or add) the entry 'LastLookAndFeel' to use a non-windows value, like:
`
LastLookAndFeel=Nimbus
`
4. Save the preferences file and restart Ghidra

**Comment by zSerity** [comment]
How do I know which non windows value to use?

**Comment by dragonmacher** [comment]
'Metal' should be available on all platforms.

**Comment by zSerity** [comment]
I can't even find that path on the system.

**Comment by zSerity** [comment]
Wait I found the file, let me try this.

**Comment by zSerity** [comment]
Alright perfect, now's it's working thank you:)

**Comment by dragonmacher** [comment]
I am going to close this for now, assuming that you have a Java-based UI bug for your particular OS.
