### ISSUE TITLE
When parsing avr8eind.sla, use DEFAULT_REGISTER_SPACE instead of the one defined.

### ISSUE THREAD

**Issue by felberj** [NationalSecurityAgency/ghidra#1108]
When parsing `ghidra_9.1-BETA_DEV/Ghidra/Processors/Atmel/data/languages/avr8eind.sla`, the DEFAULT_REGISTER_SPACE is used instead of the one defined in the sla file. Is this intended behaviour?

The file `avr8eind.sla` contains the following spaces:

```xml
<spaces defaultspace="code">
<space_other name="OTHER" index="1" bigendian="false" delay="0" size="8" physical="false"/>
<space_unique name="unique" index="2" bigendian="false" delay="0" size="4" physical="true"/>
<space name="code" index="3" bigendian="false" delay="1" size="3" wordsize="2" physical="true"/>
<space name="register" index="4" bigendian="false" delay="1" size="1" physical="true"/>
<space name="mem" index="5" bigendian="false" delay="1" size="2" physical="true"/>
</spaces>
```

We are looking at the *register* space. Because it has delay *1*, it is assigned RAM type instead of REGISTER
https://github.com/NationalSecurityAgency/ghidra/blob/23d1e9ad22b875d68c70b6d22cb74767cf03be3e/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/app/plugin/processors/sleigh/SleighLanguage.java#L903-L910

So here, the DEFAULT_REGISTER_SPACE is used, because there is no space with REGISTER type:

https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/address/DefaultAddressFactory.java#L115-L117

**To Reproduce**

1. download ghidra_9.1-BETA_DEV
2. ./ghidraRun
3. open sla file.

**Expected behavior**
Not sure, but I would expect the register space of the SLA file to be used.

**Environment (please complete the following information):**
 - OS: macOS
 - Ghidra Version: ghidra_9.1-BETA_DEV

**Comment by felberj** [comment]
FYI: same holds for avr8.sla, avr8e.sla and avr8eind.sla.
No other sla files have this problem.

**Comment by GhidorahRex** [comment]
Looks like the issue is with the definition of the register space in the .sinc file: `define space register type=ram_space size=1;`

**Comment by emteere** [comment]
The register space has been moved out of a ram_space to a register_space.
The change is in master and the upcoming 9.2 release.
This was changed with the addition of support for the xmega chip and the movement of the generic registers out of memory on the xmega.
