### ISSUE TITLE
FR: Add Offset to Equates Tables for Sorting

### ISSUE THREAD

**Issue by securitykitten** [NationalSecurityAgency/ghidra#111]
**Description**
When using the Equates Table there is no way to sort quickly by offset

**Describe the solution you'd like**
Add offset as a sortable column in the Equates Table.  Currently these are the only options for Columns.

![image](https://user-images.githubusercontent.com/5833122/54003090-f19e0480-411e-11e9-8a38-0a0dbec27571.png)

I've attached a screenshot of a CTF challenge where I highlighted the CMP's that happen in order and it'd be nice to quickly browse them in the Equates Table. 

![image](https://user-images.githubusercontent.com/5833122/54002981-88b68c80-411e-11e9-9d26-4f742cecd939.png)

Thank you for making this useful tool available to the public!

**Comment by dragonmacher** [comment]
I am not sure what you mean by 'offset', but I will assume you mean the offset from the entry point of a function.    The Equates Table provider shows all equates for the entire program.  As such, it doesn't make sense to add an 'offset' column to that provider.

We have a script that allows you to show all equates within the current selection, or the current function when there is no selection, inside of a table.    I'm attaching the script (remove the .txt extension after download), which can be added to your Ghidra Scripts collection.

[ShowEquatesInSelectionScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/2947856/ShowEquatesInSelectionScript.java.txt)

**Comment by securitykitten** [comment]
Thank you for the script.  Apologies on the ambiguous wording.  Address/Location is what I meant by offset.

I can close this FR as it can be quickly addressed (via the script) without having to add an additional column.  Thanks again!
