### ISSUE TITLE
Can it show disassembly window without symbols?

### ISSUE THREAD

**Issue by ddbb2017** [NationalSecurityAgency/ghidra#1121]
I can't seem to find how to clear the disassembly window of the symbols. This stuff (outlined in red);

![Capture1](https://user-images.githubusercontent.com/33359889/66369115-e37fc300-e94f-11e9-9c2f-9ad28e8b8f26.PNG)

It makes disassembly unreadable, There should be an option to remove those. What am I missing?

**Comment by 0x6d696368** [comment]
Code Browser: Edit -> Tool Options: Options > Listing Fields > Ops Fields: ... there disable `Markup Register Variable References`.

**Comment by ddbb2017** [comment]
Thank you.

Although that shouldn't be buried away and probably placed somewhere in the right-click context menu after a click on one of those "markup register variables" in the disassembly window:

![Capture1](https://user-images.githubusercontent.com/33359889/66416509-d2b46900-e9b2-11e9-9ee8-c66a29719a6f.PNG)
