### ISSUE TITLE
Interpretation of memory derefencing with segment registers on x86-64

### ISSUE THREAD

**Issue by ddbb2017** [NationalSecurityAgency/ghidra#1122]
The best way is to illustrate it with a sample. Say this assembly code (using Windows 10, x64):

![Capture1](https://user-images.githubusercontent.com/33359889/66382329-dffc3400-e96f-11e9-99e0-89a5c50b3e6e.PNG)

That first line `MOV        RAX,qword ptr GS:[0x60]` is getting a pointer to the `_PEB` structure (or, process environment block on Windows.)

Originally the source window translated it into this, which is unreadable:

![Capture2](https://user-images.githubusercontent.com/33359889/66382473-1b96fe00-e970-11e9-983b-2494a8a92c72.PNG)

So to correct it, I tried to do "Retype variable" for `longlong in_GS_OFFSET;` to change it to `_PEB *`:

![Capture3](https://user-images.githubusercontent.com/33359889/66382546-441ef800-e970-11e9-8169-26d77558782d.PNG)

But this made the following incorrect conversion of the source line:

![Capture4](https://user-images.githubusercontent.com/33359889/66382609-61ec5d00-e970-11e9-8a6e-cee844a77144.PNG)

If you look at the definition of the `_PEB` struct:

![Capture5](https://user-images.githubusercontent.com/33359889/66382638-6dd81f00-e970-11e9-8fd1-2160a8c127b5.PNG)

we have `hProcessHeap` at the offset `0x30`.

Is this a bug?

**Comment by 0x6d696368** [comment]
`local_GS_OFFSET` should be a `TIB*` then adding the `0x60` offset will be the `PEB*` you are after.

**Comment by ddbb2017** [comment]
Oh, I see. I got confused by that original weird type cast it did. So if I re-type that original `longlong in_GS_OFFSET` from `longlong` to `_TEB64*` it now works fine. Thank you,
