### ISSUE TITLE
Setting a function signature from script

### ISSUE THREAD

**Issue by james-tate** [NationalSecurityAgency/ghidra#1126]
For the life of me I cannot fine a script API call for setting a functions signature. I have found, FunctionUtility.updateFunction​(dst,src), and how the GUI does it in EditFunctionSignatureDialog.java. I have been able to setVarArgs(). Does script API call exist for setting a function's arguments? If so can someone point me to it?

**Comment by dragonmacher** [comment]
I was a bit surprised at just how unobvious this actually was (I would have expected more related methods in the scripting API).

The 'Ghidra Way' of modifying items that are stored in the database, such as a function, involves using an existing **Command** (or creating one as needed).   In this case, you should be using the `ghidra.app.cmd.function.ApplyFunctionSignatureCmd` class.  It has multiple constructors, with the base constructor taking an Address and a FunctionSignature.     So, in you script, build a FunctionSignature to you liking and use that to create the above command.  Then, use the script API `runCommand(command)` method to have the new signature applied.

**Comment by james-tate** [comment]
Perfect! I found the ApplyFunctionSignatureCmd class, but could not figure out how to run the command after it was constructed. I was looking for an execute(cmd) and totally missed the runCommand(cmd). Thanks!

**Comment by astrelsky** [comment]
> Perfect! I found the ApplyFunctionSignatureCmd class, but could not figure out how to run the command after it was constructed. I was looking for an execute(cmd) and totally missed the runCommand(cmd). Thanks!

Can also use cmd.applyTo(currentProgram)

**Comment by crashingstatic** [comment]
I wrote a Ghidra script which does the correction automatically.

https://gist.github.com/crashingstatic/71f9ca586e43178fbea3317a93e1df59
