### ISSUE TITLE
Text being cut

### ISSUE THREAD

**Issue by esppc** [NationalSecurityAgency/ghidra#1129]
So, I recently installed ghidra with the purpose of replacing IDA (it costs 10k less!) but one thing that I cannot find anywhere is how to remove this "simplification" of text

![image](https://user-images.githubusercontent.com/34080739/66530356-cda00880-eadd-11e9-9123-5e66b02a2db7.png)

The same thing occours for the symbol tree. How can I show the full text?

**Comment by ghizard** [comment]
Check out #99.
