### ISSUE TITLE
Ghidra is confused by 2-tier Symbol Store

### ISSUE THREAD

**Issue by snowkoan** [NationalSecurityAgency/ghidra#113]
**Describe the bug**
Ghidra is not finding symbols in my symbol server that has 2-tier hierarchy enabled. See more about this here: https://channel9.msdn.com/Shows/Defrag-Tools/Defrag-Tools-87-Symbol-Folder-Hierarchy-index2-txt

Basically, instead of just having a root that contains PDB directories, there is an intermediate level with the first two letters of the binary. So, kernel32.pdb will be under c:\symbols\ke\kernel32.pdb (for example).

**To Reproduce**
1. Set PDB path to a symbol server with Symbol Folder Hierarchy enabled.
2. Run the PDB analysis. Ghidra tells me that the symbol could not be found.

**Expected behavior**
Symbols should be found. WinDbg has no problems with this scenario.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Win 10
- Ghidra: Version 9.0
- JDK: Open JDK 11

**Comment by ghizard** [comment]
@snowkoan 
I found reference to [Symbol path for Windows debuggers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symbol-store-folder-tree) regarding the use of index2.txt file in the root to indicate that a two-tier structure is used.
I have some questions:
- Are you aware of whether two-tier is only used on symbol servers?  Or can it also be found in other places, such as the local cache? I cannot tell if your example above represents the file system on the symbol server or for your local cache or just a generic example.
- Do you have the URL for a publicly available symbol server and a valid URL for a PDB file that exists on that symbol server?  I can write code and tests for one-tier/two-tier, but would benefit from witnessing interaction with real data.
- My intention would be to first test the server to see if index2.txt exists, then only request the one-tier or two-tier structure based on that result. Does your experience with two-tier make you believe that this is an appropriate way to approach this issue?

**Comment by snowkoan** [comment]
@ghizard 

Thank you for looking at this. 

The whole notion of a 'symbol server' is a bit funny -- it's really just a file layout that dbghelp.dll recognizes. I have a 'symbol server' on my local dev machine and I use the 2-tier layout for ease of organizing giga-bytes of PDB files.

Your instinct is correct -- you can look for index2.txt in the root of the symbol server and then proceed based on its existence (or non-existence).

As for a reproduction environment, I don't know of a public 2-tier symbol server. What if I were to share a very small symbol server layout with you? Say, just the root, index2.txt and one or two PDB files. Would that be enough for you?

**Comment by ghizard** [comment]
@snowkoan 
I'm cannot promise how soon we would be able to give this area the attention it needs, but I am interested in seeing how we might approach this work while consolidating some of our code that supports PDB, and we might be able to make some simple steps to getting there. Part of this requires a better understanding of the big picture in order to map out the steps.

The searches I had done made me believe that there might be provisions in some of the later Visual Studio or other Microsoft product for us to set up and maintain a symbol server.  It might be best if we could set something up on our end.  Are you using anything in particular to host your server in terms of server software/packages?

Thank you for the offer to set up a small server.  I might come back to you on this, but if we could set up our own, it might serve some of our other needs as well. Any advice in this area would be greatly appreciated.

**Comment by snowkoan** [comment]
The only tools you need are in the Debugging Tools for Windows package (the same package that contains Windbg). Since this isn't urgent, I'll get back to you after my vacation with some suggestions.

**Comment by ghizard** [comment]
@snowkoan 
Excellent. Enjoy your vacation.

**Comment by ghizard** [comment]
@snowkoan Regarding support for two-tier PDB Symbol Store...
We are looking into supporting both one- and two-tier symbols stores on a remote server as well as support for Ghidra to create and use its cached local symbols in flat, one-, or two-tier stores.  My question of you is whether you expected Ghidra to support an "existing" "local" directory that is one- or two-tier in structure, such as in your example where you showed the local folder in the c: drive (c:\symbols\ke\kernel32.pdb). Scenario would be, you have the store as you had shown and you would like to point Ghidra at the base folder (c:\symbols) and expect Ghidra to be able to find the PDB file?

**Comment by snowkoan** [comment]
>Since this isn't urgent, I'll get back to you after my vacation with some suggestions.

Oops. I had a really long vacation. Sorry about that. Let me know if you still need suggestions.

Yes, my use-case involves existing symbols. I use windbg side-by-side with Ghidra and in my mind, it shouldn't matter who downloads the symbols. They should be able to share them.

**Comment by dev747368** [comment]
2-tier symbol store is addressed in 22675e9f39dd23bb1f0df775ef3cc2c8f22e81a7.
