### ISSUE TITLE
Identify thumb functions from Python?

### ISSUE THREAD

**Issue by raycewest** [NationalSecurityAgency/ghidra#1132]
Messing with an existing (already analyzed) target from within the Python console and trying to figure out which of the functions are thumb (they are correctly annotated within the GUI/listing).  I think the answer lies in getting the "TMode" register given a certain context, or perhaps the Register Manager (which I cannot find an API for).  What's the best way to do this?  Seems overly difficult to script...

**Comment by astrelsky** [comment]
You may try the following.

```
def isThumbFunction(func):
    r = currentProgram.getRegister("TMode")
    value = currentProgram.programContext.getRegisterValue(r, func.entryPoint)
    return value.unsignedValueIgnoreMask == 1
```

**Comment by raycewest** [comment]
perfect! thanks so much!

**Comment by astrelsky** [comment]
You're welcome.
