### ISSUE TITLE
Get call sites of a given function (Python scripting)

### ISSUE THREAD

**Issue by raycewest** [NationalSecurityAgency/ghidra#1133]
I see function objects have getCalled/CallingFunctions(), which are nice to have, but is there a likewise convenient way to get the locations of a functions call sites/locations without having to work backwards through the reference manager object (and its child objects)?  Could save a lot of resources.

**Comment by dragonmacher** [comment]
I will assume you wish to walk the function call graph of a program.   I have created a script to do that generically.    This will show you how the API is setup.


Rename the script to remove the .txt extension.
[GraphFunctionScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/3718150/GraphFunctionScript.java.txt)

**Comment by dragonmacher** [comment]
I realized I misunderstood your question above.

**We currently have no API that will allow you to extract the incoming and outgoing addresses for a given function** without using the `ReferenceManager`.   It would be possible for us to make an API (probably out of the code we use below).   For us to create such an API we would have to have example Use Cases that explain how the feature would be used.

For anyone that may be seeking examples within our current API of finding such information, as well as other function related navigation, here are some pointers.

1) Retrieving a single function's incoming and outgoing references/addresses.

Outgoing:  https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/calltree/OutgoingCallNode.java#L74

Incoming: https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/calltree/IncomingCallNode.java#L83

These classes will load child nodes based upon references data for the selected function.  This can be viewed in the UI via the Call Tree Plugin.


2) To create a graph of all program functions in dependency order:

`AcyclicCallGraphBuilder builder =
    new AcyclicCallGraphBuilder(program, true);
AbstractDependencyGraph<Address> graph = builder.getDependencyGraph(monitor);`


3) To create a graph of a single function's code blocks, see the script in my previous comment.
