### ISSUE TITLE
Get basic blocks of a given function (Python scripting)

### ISSUE THREAD

**Issue by raycewest** [NationalSecurityAgency/ghidra#1134]
Is it possible to get a given function's BB's without having to iterate over the entire program using BasicBlockModel or similar objects?

**Comment by dragonmacher** [comment]
Try this:

`CodeBlockModel blockModel = new BasicBlockModel(controller.getProgram());`
`AddressSetView addresses = function.getBody();`
`CodeBlockIterator iterator = blockModel.getCodeBlocksContaining(addresses, monitor);`
