### ISSUE TITLE
Reset the object class associated with an ObjectPropertyMap

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#1137]
We have a set of GhidraScripts that manipulate some additional data associated with a Program.  This information is saved in an ObjectPropertyMap.  That seems a good fit, since the information is associated with a particular address in the Program.

However, since the objectClass does not exist within ghidra itself, when ghidra starts up, it cannot create a tokenInstance from the class, so it resorts to GenericSaveable.  This means that when one of our scripts does run and attempt to retrieve objects, they have the wrong class.

Probably the easiest change that would solve this problem would be to add a method to ObjectPropertyMap to set the object class, other than creating a new PropertyMap.  If there is danger in just changing the class, then perhaps it could only be set if the class was GenericSaveable (which is treated as an exception in several places).

(I won't mention the ugly work-around we currently employ, although the previous developer resorted to parsing the GenericSaveable.toString() output...)

Further, if there is any way to get ahold of the Program's AddressSpace in the .restore() method, that would allow handling of Address objects much easier.  As it is, we are resorting to a shadow object with Long holding the Address.getOffset() value and always copying between the real and shadow objects in a context where we can get at the AddressSpace to construct an Address.

**Comment by dragonmacher** [comment]
You have bumped into a common issue we see with scripting.  It is difficult for users to create libraries of code to be shared in the scriping environment.  We tell users that scripts are for relatively small tasks that can uses existing APIs.   The opposite end of the Ghira development spectrum is Extensions and Plugins.  We intend for users to add new features via Plugins, ExtensionPoints, etc.   In your case, you are ostensibly just marking up a program via the API.  However, as you pointed out, you have run into the issue that Ghidra does not know about your new type.  While not a new feature per se, you do have to now be able to provide your code to Ghidra, which is somewhat like an extension.  The issue gets compounded if you intend to share your scripts with other people, as they too will need Ghidra to see your new code.

At this point, I would say, if you intend to share your work with others, then you should consider building a Ghidra Extension, even if that extension is comprised only of scripts and classes.   By building an Extension deliverable, other users can install your code into Ghidra, which works around the issue you now have.

You could work around the issue a bit by pre-compiling your Savable object and then pointing Ghidra at either the compiled output directory or a jar containing the class.  You can tell Ghidra about this via the Front End at 'Edit -> Plugin Path...'   Adding your code to the 'plugin path' updates Ghidra's classpath to include your missing type(s).  Once this is done, the 'objectClass' value should be correctly set.

Regarding the issue of not having the Program object available during the 'restore()' call, we would have to consider what would could change here.  For now, it sounds like what you are doing is right thing.  Although, you should consider saving the value of Address.toString() and then using the AddressFactory.getAddress(String) to restore it, as this approach handles address spaces.

**Comment by marcushall42** [comment]
I have re-worked our scripts to pack our data into a string and use StringPropertyMap instead of ObjectPropertyMap.  I don't see any way forward to use ObjectPropertyMap from a script since the script's classes will not be present when ghidra opens the program and ghidra demands to be able to load the class at that time or it defaults to GenericSaveable and there is no coming back from that.  It's actually just about as easy to pack/unpack a string as the hack to get things into/out of GenericSaveable, so we're happy enough (just have to be careful escaping the char we use as a delimiter!)
