### ISSUE TITLE
Big structs are laggy to edit

### ISSUE THREAD

**Issue by jimbowhales** [NationalSecurityAgency/ghidra#1141]
**Describe the bug**

The struct editor is slow with big structs.

**To Reproduce**
1. Create a struct type containing an array of 2.5 million elements (like an inline buffer). The struct type editor should already be laggy after this (try toggling "show numbers in hexadecimal").
2. Create another small field in the struct, and hit Alt-M to duplicate it a few dozen times. 
3. Select all the fields and try to delete them.

**Additional context**
A quick profiling shows that the problem is in BitFieldPlacementComponent.java. I have sort of patched away the problem for myself in https://github.com/jimbowhales/ghidra/commit/48d8a732c634fb9b4a4a44100fe829212b9ea716, but ideally you would actually properly update the UI at a higher level instead of just hiding one element and returning early from a few functions and hoping for the best.

**Comment by ghidra1** [comment]
While I will look into the bit view component performance there are many other behaviors of the structure editor which do not scale well for extremely large structures with many components.  You will quickly see this if you attempt to right-click on structure table with 2.5 million undefined components.
