### ISSUE TITLE
Sleigh BitRange Registers (Bad Symbol Xml)

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1144]
**Describe the bug**
All bitrange registers as described in the sleigh documentation section 4.5 compile successfully with sleigh. Upon loading the .sla file, ghidra throws `throw new SleighException("Bad symbol xml");` in SymbolTable.java line 158. It appears that the below XmlElement is being parsed in the restoreSymbolHeader method which there is no case for. I'm not sure if sleigh has compiled it wrong, or if the symbol table class has not been updated to handle the bitrange registers.

```
XmlElementImpl@59 "<subtable_sym(2) name="instruction" id="0x0" scope="0x0" numct="57"> @(165:66)"
```

**To Reproduce**
1. Add the bitrange example in the sleigh documentation section 4.5 "Bit Range Registers" to a language of your choice.
2. Load a binary with said language definition.

I added the example to 6502.slaspec and changed the offset of statusreg to 0x60. The resulting .sla file is relatively small so I will attach it below. The cause of the exception is line 165.

**Attachments**

[6502.sla.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/3722010/6502.sla.tar.gz)

**Environment (please complete the following information):**
 - OS: Windows 10 10.0 amd64
 - JVM Version: Oracle Corporation 12.0.2
 - Ghidra Version: Ghidra Version: 9.1 04f7366a62798068903252c729799a067d714412

Edit: In regards to the closing and re-opening, I had forgotten the exception isn't thrown until ghidra tries to load the sla file.

**Comment by chaoticgd** [comment]
I've run into this too. Same as #660 although that report seems to have gone fairly unnoticed.

**Comment by astrelsky** [comment]
This appears to have been resolved by a recent commit.
