### ISSUE TITLE
SleighEditor sqrt table issue

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1153]
**Describe the bug**
Creating an instruction with the mnemonic sqrt appears to cause an issue with the SleighEditor parser. This might occur with other built in names, but I only happened to notice with sqrt.

**To Reproduce**
1. Load/Install SleighEditor in eclipse.
2. Create a *.sinc file and an instruction with the mnemonic sqrt

**Screenshots**
Named :sqrt
![ex](https://user-images.githubusercontent.com/46897303/66927657-2a2f8600-effe-11e9-89a8-3c7e61d71aef.PNG)

Changed name:
![ex2](https://user-images.githubusercontent.com/46897303/66927679-33b8ee00-effe-11e9-8fc6-2ecccedcc674.PNG)

**Environment (please complete the following information):**
 - SleighEditor: 1.0.0 (packaged with ghidra 0.9.1_BETA)

**Comment by GhidorahRex** [comment]
sqrt is a keyword (used for the sqrt pcode op). It should work if you place quotes around the name sqrt

`:"sqrt" "Q", vuft^ftf is ...`

**Comment by astrelsky** [comment]
> sqrt is a keyword (used for the sqrt pcode op). It should work if you place quotes around the name sqrt
> 
> `:"sqrt" "Q", vuft^ftf is ...`

Oh I see. I was aware it was a keyword but I thought that anything determined to be a mnemonic was interpreted literally. ie it would appear with the quotes. This doesn't appear to be the case and it appears appropriately with the quotes.

Thank you.
