### ISSUE TITLE
Follow up to #411: Copied text starts and ends with quotes

### ISSUE THREAD

**Issue by larsborn** [NationalSecurityAgency/ghidra#1155]
**Describe the bug**
When the cursor is over a string in the Decompile view and the user presses Ctrl-C, the string is copied to the clipboard. This was requested in #411. The copied text includes the encompassing `"` signs though. Example: if the cursor is over the string `LocalFree` for example, the clipboard contains `"LocalFree"` after pressing Ctrl-C.

**To Reproduce**
1. Find a string in the Decompile window
2. Left-click the string to highlight it (don't create any selection, just click on the string)
3. Press Ctrl-C
4. Paste the clipboard content into a text-editor, the result starts and ends with `"`

**Expected behavior**
The content of the clipboard should not include the encompassing `"` signs. So just `LocalFree` in the example above. This would enable easy usage of the content, for example, to rename a variable afterwards.

**Environment**
 - OS: Ubuntu 18.04.3 LTS
 - Java Version: 11.0.4
 - Ghidra Version: 9.1-BETA

**Comment by ryanmkurtz** [comment]
I can't reproduce this in 9.1.2 or master.  Is it still an issue for you?

**Comment by larsborn** [comment]
![quotes](https://user-images.githubusercontent.com/1826897/83780494-83cbea00-a68d-11ea-8ff5-9b212bad7949.gif)

Yes, it is still the case (both in the Decompile View and the Assembly Listing btw). Is there anything else, I can do to help?

**Environment:**

* OS: Windows 10
* Java Version: 11.0.7
* Ghidra Version: 9.1.2

**Comment by ryanmkurtz** [comment]
Ah ok, I was copying from the decompiler.

**Comment by ryanmkurtz** [comment]
BTW, how do you create those screen capture recordings?

**Comment by aerosoul94** [comment]
> BTW, how do you create those screen capture recordings?

I use ShareX: https://github.com/ShareX/ShareX
![image](https://user-images.githubusercontent.com/12718188/83782829-9296aa80-a655-11ea-87ae-7945894481ba.png)

**Comment by larsborn** [comment]
![decompileview](https://user-images.githubusercontent.com/1826897/83785762-166e8800-a692-11ea-85e7-2da03b1cb85d.gif)
it was just an example, I have the same issue with the Decompile View (btw, I switched OS between my two reports, if that matters).

For screen recordings, I use https://chocolatey.org/packages/screentogif.

**Comment by EmosewaMC** [comment]
Is there an update to this one?

**Comment by dragonmacher** [comment]
bump

**Comment by larsborn** [comment]
Ahhh now I see where the problems with this issue lie :-)

I'd say that you could just leave those string as is (i.e. still having quotes at the start and end). Another suggestions would be to use this semi-standardized format of `Text\xAA\xBBtext` (without the quotes).

**Comment by ghidra007** [comment]
This is working as intended. The word that the cursor is on is what is put in the copy buffer not the highlight. If you want less, then you need to do a character selection which will color in green. Just drag with mouse to select the exact text you want to copy. You could also open the Window-Defined Strings window and look in the string value column. If you click on a defined string in the listing that table will navigate you to the correct string. then you can select the string in the Value column.

**Comment by EmosewaMC** [comment]
> This is working as intended. The word that the cursor is on is what is put in the copy buffer not the highlight. If you want less, then you need to do a character selection which will color in green. Just drag with mouse to select the exact text you want to copy. You could also open the Window-Defined Strings window and look in the string value column. If you click on a defined string in the listing that table will navigate you to the correct string. then you can select the string in the Value column.

The only reason we say it's not working as intended is specifically with strings, you generally want the string word and not the quotes encapsulating it.  Personally, when renaming fields used for lua tables, I have to do several extra keystrokes to get rid of the encapsulating L"" when I really just needed the word.  The feature may be working as intended, but could this not be seen as a feature request?

**Comment by ghidra007** [comment]
Some people may want the quotes if they are copying into source code that requires the quotes. We are considering writing a script for this. We will update the ticket if/when a script gets written.

**Comment by EmosewaMC** [comment]
> Some people may want the quotes if they are copying into source code that requires the quotes. We are considering writing a script for this. We will update the ticket if/when a script gets written.
> 
> Also, in the listing/decompiler have you tried selecting (not highlighting) the part of the string you want then copying? That would be the easier way. I was just giving alternatives.

Yes I do use the manual selecting.  Appreciate the reminder on the alternatives, was just trying to help suggest a feature to make naming fields in some contexts flow better.  It is likely far more useful to people to get the full string with quotes so not a hill im going to die on.

**Comment by ghidra007** [comment]
We will let you know if/when we get a chance to write a script to do this.

**Comment by ryanmkurtz** [comment]
> There is now a tool option that lets you decide whether to include or not include the quotes when you do a copy on a string in the listing or decompiler. If you type "copy" into the filter in the tool options you will see it: "Copy Strings Without Quotes".

Note that this will not be available in `master` until this ticket is closed.
