### ISSUE TITLE
Support current Intel x86/x64 manuals

### ISSUE THREAD

**Issue by Kreeblah** [NationalSecurityAgency/ghidra#116]
**Is your feature request related to a problem? Please describe.**
The processor manual feature is fantastic, but for Intel processors, it references 253666-029US and 253667-029US, dated November 2008.  These have been superseded by 325383-060US (as a single file, rather than two), and as far as I can tell, the two files used by Ghidra are no longer distributed by Intel.

**Describe the solution you'd like**
It would be nice if Ghidra's references were updated to use the current document.

**Describe alternatives you've considered**
An alternative would be to provide links to where Intel distributes the currently-referenced documents.

**Comment by ckuethe** [comment]
See also #38

**Comment by Kreeblah** [comment]
That definitely helps, but it also seems odd for the only supported versions to be ones which aren't currently distributed through any official method.  I didn't realize the index format was so simple, though.  I might take a crack at updating it myself later.

**Comment by Kreeblah** [comment]
I went ahead and updated the x86.idx file to reference the following publications:
Intel 64 and IA-32 Architectures Software Developer's Manual Volume 2 (2A, 2B, 2C & 2D): Instruction Set Reference, A-Z, Sep 2016 (325383-060US)
AMD64 Architecture Programmer's Manual Volume 3: General-Purpose and System Instructions, Rev 3.26 May 2018 (24594)
AMD64 Architecture Programmer's Manual Volume 4: 128-Bit and 256-Bit Media Instructions, Rev 3.23 Feb 2019 (26568)
AMD64 Architecture Programmer's Manual Volume 5: 64-Bit Media and x87 Floating-Point Instructions, Rev 3.15 May 2018 (26569)
AMD64 Technology 128-Bit SSE5 Instruction Set, Rev 3.01 August 2007 (43479) (this one is unchanged from the provided .idx file since I can't find a newer version of the publication that lists the same instructions)

I'd love if that could be included in Ghidra.  I made it available at https://github.com/Kreeblah/ghidra_files/commit/33843d75f5dff25956076712aa79d57ded8bcba9

**Comment by Kreeblah** [comment]
I added this as a pull request at https://github.com/NationalSecurityAgency/ghidra/pull/366, so I'll close this to keep discussion of it over there.
