### ISSUE TITLE
PowerPC VLE offset sometimes incorrect (e_add2i, e_add2is, e_mull2i, e_cmp16i, e_cmph16i)

### ISSUE THREAD

**Issue by revofrank** [NationalSecurityAgency/ghidra#1160]
**Description:**

Certain PowerPC VLE instructions may have an incorrect signed 16 bit immediate value (SIMM16) if one of the instruction fields (SIMM_0_10_VLE) is negative.

**To reproduce:**

1. Create binary file holding bytes "72 C6 96 7D"
2. Load binary as PowerPC PowerISA-VLE-64-32addr
3. Make sure vle bit is set to 1 in code browser processor options (right click in listing and select processor options from context menu)
4. Disassemble

**Expected behaviour:**

`00000000 72 c6 96 7d     e_add2is   r6,-0x4983`

Actual:

`00000000 72 c6 96 7d     e_add2is   r6,-0x183`

The SIMM16 value of -0x183 is incorrect.  From the instruction info display the constant -0x183 comes from the following bit fields:

     Op-Objects	const:-0x183
     Operand Mask	00000011 11100000 00000111 11111111
     Masked Value	00000010 11000000 00000110 01111101

SIMM16 should be 10110 11001111101 (-0x4983)
SIMM16 actually is 11111 11001111101 (-0x183)

If we look in ppc_vle.sinc we find SIMM16 defined as:

`SIMM16: val						is SIMM_0_10_VLE & SIMM_21_25_VLE [ val = (SIMM_21_25_VLE << 11) | SIMM_0_10_VLE ;] { export *[const]:2 val; }`

It appears that in our example SIMM_0_10_VLE (11001111101) was sign extended to a full 16 bits (11111 11001111101).  This or'd 11111 over the SIMM_21_25_VLE bits (10110).

Using IMM_0_10_VLE in place of SIMM_0_10_VLE seems to fix the problem:

`SIMM16: val						is IMM_0_10_VLE & SIMM_21_25_VLE [ val = (SIMM_21_25_VLE << 11) | IMM_0_10_VLE ;] { export *[const]:2 val; }`

**PowerPC VLE instructions affected:**  e_add2i, e_add2is, e_mull2i, e_cmp16i, e_cmph16i

**Environment:** ghidra_9.1-BETA_DEV_20190923

**Comment by mumbel** [comment]
@GhidorahRex   I noticed sh-2 suffered from this type of issue/bug class as well from just a quick grep and taking a guess by names being OR'd (#1161 )

**Comment by GhidorahRex** [comment]
@mumbel Thanks! I'll take a look at the pull request too
