### ISSUE TITLE
Can I make Ghidra know an offset is a local stack variable?

### ISSUE THREAD

**Issue by ebfe2326** [NationalSecurityAgency/ghidra#1164]
related to issue #1120, I've come across a number of locations where Ghidra is not recognizing the local stack variables, but it should be.  In the screenshot below, the same local variable (0xffffff3f8) is used in two adjoining instructions.  The stack offset is not recognized in the first instruction, but the instruction immediately following it is recognized as local_c0c.

![image](https://user-images.githubusercontent.com/44279601/67209699-d817a780-f3e5-11e9-970f-b9fafed50c92.png)

Is there a way for me to force Ghidra to recognize and label this offset as a local stack variable in the first instruction?  In Ida Pro, i could press the "k" shortcut key to cycle between the actual offset and the labeled, local stack variable.  I searched the options in Ghidra and can not find an equivalent, but I'm hoping I may just be missing it.

**Comment by saruman9** [comment]
I think you can create reference to everywhere (memory, external memory, stack, register), label also will be created. Right click on the line in Listing, `References`, `Add/Edit...` (or press `R` key).
But decompiler wouldn't respect the changes most of time.

**Comment by ebfe2326** [comment]
thanks, that looks like it works.  i wish i knew why ghidra has a hard time labeling all the stack locations, but at least this allows me to manually fix it.

**Comment by saruman9** [comment]
>  i wish i knew why ghidra has a hard time labeling all the stack locations

Seems, that Ghidra could label all the stack locations early (as you point to #1120). If you share the file, then maybe I would try to find the reason.
