### ISSUE TITLE
'Window' window extends past screen

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1168]
**To Reproduce**
1. Click 'Window' tab with all default plugins enabled.

**Expected behavior**
The drop down list to fit on the screen.

**Screenshots**
![example](https://user-images.githubusercontent.com/46897303/67341891-d2fa4b80-f4fe-11e9-86b1-b59925207833.png)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18362.418]
 - Java Version: 12.0.2
 - Ghidra Version: 9.1

**Comment by ryanmkurtz** [comment]
Duplicate of #566

**Comment by astrelsky** [comment]
> Duplicate of #566

I plead guilty of not checking first this time. Should have known better.
