### ISSUE TITLE
Is it possible to decompile any file and generate its true code?

### ISSUE THREAD

**Issue by JafferWilson** [NationalSecurityAgency/ghidra#1173]
Hello developer,
I am really delighted to see this repository. It is wonderful tool as per demos I saw.
I have tried something I will share.
I try to open an .ex5 file which is a Metatrader 5 file.
I saw the binary level code and even try to check if I could decompile it and get the source out of it or even the traces of the source.
I was not able to do so with this wonderful tool, which had helped me in viewing different tools.
But I am amazed to witness that it was not at all helpful to me there.
Please developer can you tell whether I can get the de-compilation and traces of the source of any .ex5 file.
If needed I will share one with you so that you can check.
Please do let me know your suggestions.

**Comment by ryanmkurtz** [comment]
Ghidra does not support the .ex5 file format.  A custom Ghidra Loader would have to be written to handle it.

**Comment by JafferWilson** [comment]
@ryanmkurtz That would be an awesome solution. But I wonder whether it is feasible to decode ex5 or not?

**Comment by ryanmkurtz** [comment]
We are not familiar with that format, so it's hard to say.  Ghidra needs a loader to bring in the file and lay it out in memory, and then a processor/language module to decode the instructions.  Do you know what processor these files are meant to run under?  x86?

**Comment by JafferWilson** [comment]
Yes x86. I am using on my PC. 
It is compiled using MQL5 language. It is I guess customized c++ language compiler or something. I am not able to understand it.

**Comment by ryanmkurtz** [comment]
The file might be compressed or something...that's where the loader would come in.

**Comment by JafferWilson** [comment]
Yes, you are right. You need terminal.exe for loading the ex5.

**Comment by ryanmkurtz** [comment]
I am going to go ahead and close this ticket, as this proprietary file format it outside of the Ghidra team's scope.

**Comment by JafferWilson** [comment]
@ryanmkurtz But can you suggest me something that will help me analyze this ex5,please?

**Comment by ryanmkurtz** [comment]
I know of nothing, sorry!

**Comment by pargara** [comment]
@JafferWilson Did you find a way to decompile it?

**Comment by Twapa** [comment]
yes

**Comment by pargara** [comment]
how?

**Comment by pargara** [comment]
> yes

How?

**Comment by JoaojpAxx** [comment]
Cadê a resposta chefe ??

**Comment by cfournel** [comment]
> > yes
> 
> How?

@ryanmkurtz  load ea in strategy tester, then dump memory with GDB then export it to efl format and load it in ghidra as a gcc / c++ / x64

**Comment by alfazappy** [comment]
> yes

please share me how you decompile .ex5 file..
