### ISSUE TITLE
Symbol Tree 的文件夹只显示两个字符...

### ISSUE THREAD

**Issue by wengxianxun** [NationalSecurityAgency/ghidra#1176]
Symbol Tree 的文件夹只显示两个字符，怎么显示文件夹全称呢？
![image](https://user-images.githubusercontent.com/831898/67552861-76856f00-f73e-11e9-9082-4d84e0dde295.png)

**Comment by beketata** [comment]
[#54](https://github.com/NationalSecurityAgency/ghidra/issues/54)
