### ISSUE TITLE
Setting Swing Timeout

### ISSUE THREAD

**Issue by fkt** [NationalSecurityAgency/ghidra#1179]
Hi,

I'm constantly running in a Swing Timeout:
`Caused by: ghidra.util.exception.UnableToSwingException: Timed-out waiting for Swing thread lock in 20 SECONDS`

I tried setting the timeout in launch.properties by adding:
`VMARGS=-Dswing.timeout.seconds="300"`
but it still took the 20s default timeout.

The corresponding code should be this:
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/Utility/src/main/java/ghidra/util/Swing.java#L38

How to customize this setting for good?

Thanks in advance!

**Comment by dragonmacher** [comment]
The actual system property should be `-Dghidra.util.swing.timeout.seconds=300`  Your example was missing the package name of the 'swing' class.  

I am curious to know when you are running into this issue.  You can run into it when working with a debugger, but we have not seen the issue in a normal Ghidra build.   Are you seeing this in a Ghidra build while not debugging?

**Comment by fkt** [comment]
Thanks for the prompt reply. This worked. A colleague and me were running into this issue while simply analyzing a 30MB binary using the current 9.1-BETA-DEV release build. Unfortunately I'm not able to share that binary. From what it looked like, the issue was in a 'Demangle' stage.

**Comment by dragonmacher** [comment]
Thanks for the info.  The feature is relatively new.  It is meant to prevent deadlocks from errant code.    I think we will have to consider changing the timeout value.
