### ISSUE TITLE
Script Key Bindings not working (works in 9.04)

### ISSUE THREAD

**Issue by 0x6d696368** [NationalSecurityAgency/ghidra#1182]
**Describe the bug**
Key Bindings assigned to scripts don't work.

**To Reproduce**
1. Go to 'Script manager'
2. Enable `HelloWorldScript.java`
3. Hit assigned default key binding ALT+SHIFT+COMMA
4. Script doesn't run

**Expected behavior**
Script runs.

**Environment (please complete the following information):**
 - OS: CentOS 7
 - Java Version: 11.0.5
 - Ghidra Version **broken**: 9.1-BETA
 - Ghidra Version **working**: 9.04

**Additional context**
Changing the key binding to other keys (F5, X, etc.) also doesn't work.
**This works in 9.04.**

**Comment by astrelsky** [comment]
This has been fixed after the release of 9.1-BETA.

**Comment by 0x6d696368** [comment]
> This was fixed after the release of 9.1-BETA. I cannot seem to find the specific commit which fixed it. However I have confirmed in a newer build of 9.1 that it is functional.

Thanks for the heads up!
Seems Ghidra is the new r2 when it comes to keeping up with the fixes.
