### ISSUE TITLE
Option to disable debug "line" comments

### ISSUE THREAD

**Issue by tzizi** [NationalSecurityAgency/ghidra#1184]
**Is your feature request related to a problem? Please describe.**
I'm analysing an executable with debug symbols, and both the disassembler and the decompiler can show up to thousands of lines of lines like:

`00401fa0 -> Line #3`

One such function was more than 70,000 lines of code, where the actual code itself without those comments was less than 100. This renders it nearly impossible to read the actual code.

**Describe the solution you'd like**
An option to disable this

**Describe alternatives you've considered**
I'm not sure, maybe an option to condense these comments?

**Additional context**
Here's a screenshot of the issue in the decompiler:

![ghidraline](https://user-images.githubusercontent.com/41488180/67627335-2fb37a00-f80f-11e9-860e-19e932a75010.png)

In the disassembler:

![ghidralinedis](https://user-images.githubusercontent.com/41488180/67627347-65586300-f80f-11e9-97b3-80039c9e0719.png)

**Comment by astrelsky** [comment]
What is the debug format? If it is DWARF, the DWARF Line Number analyzer is a prototype and disabled by default. PDB doesn't appear to have any options other than search paths.

**Comment by tzizi** [comment]
@astrelsky Thanks for replying, it uses PDB.

**Comment by astrelsky** [comment]
I think it would be a good idea for a debug analyzer interface or abstract class to be implemented to set a standard for the options when importing debug information. There is a vast difference between the options available for DWARF import and PDB information.

**Comment by ghizard** [comment]
These line numbers are seemingly from the PE Loader and not the PDB.
