### ISSUE TITLE
When loading ARM BE8 binaries instruction set does not default to V8LEInstruction

### ISSUE THREAD

**Issue by jonwilson030981** [NationalSecurityAgency/ghidra#1187]
**Describe the bug**
When loading an ARM BE8 ELF file, the instruction set defaults to an incorrect value and is the only “recommended” setting.

Examination has shown the ELF loader does not parse the architecture specific flags in the ELF header. Whilst this can be overcome by unchecking the “only show recommended languages” box, this selection does not seem to propagate for any dependant binaries which are selected to be loaded (e.g. it’s imported libraries). This is problematic for binaries with a large number of imports.

**To Reproduce**
 Compile an ARM binary with the flag -mbe8 set. Then import into Ghidra in the normal way. 

**Expected Behavior**
The correct instruction language is selected by default. Any manually selected alternative is also applied to any dependent libraries which are also loaded.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: 11.0
 - Ghidra Version: 9.0.2

**Comment by ghidra1** [comment]
It may be possible to update the ARM.opinion file with examination of the ELF header e_flags field (secondary opinion attribute).

**Comment by jonwilson030981** [comment]
I have a workaround at the minute which is a custom plugin which extends the ELF loader, but it would be good to get a fix upstream. Although I appreciate BE8 isn’t the most popular architecture.

**Comment by ghidra1** [comment]
A new ELF Loader / plugin is not the correct way to handle this situation.

For ARM-32, a mixed-endian processor variant is required (v7LEInstruction or v8LEInstruction) with an appropriate import opinion to steer the default language choice to one of these variants.    Alternatively, you can select the appropriate variant during import.

For ARM-64 (AARCH64) the big-endian V8a variant always has little-endian instruction encoding.

**Comment by jonwilson030981** [comment]
I agree, it was just a vey quick and ugly workaround to let me move on with the task at hand. Sorry, it is not intended for public consumption and I'm certainly not knowledgeable enough in the internals of ghidra to say what the right clean fix should be.

I did try selecting the correct variant during import, but the dependent libraries didn't pick up this option, instead reverting to the default.

Since the binary I was working on had a very large number of imports, this wasn't something I could fix in a practical way manually.

**Comment by ghidra1** [comment]
That library import issue should probably be entered as a bug.  Two issues as I see it:
1. Library import should utilize language choice made for primary program
2. ARM import opinions should consider ELF e_flags

**Comment by WorksButNotTested** [comment]
Proposed fix in #2066.

**Comment by ghidra1** [comment]
PR has been merged for Ghidra 9.2
