### ISSUE TITLE
Allow Multiple Extension Versions

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1193]
**Is your feature request related to a problem? Please describe.**
Currently only one ghidra version may be specified in an extension.properties version field. This requires either an extension distributor to release multiple different releases of an identical extension with the only difference being the version field or requiring the end user to change the value to their version of ghidra.

**Describe the solution you'd like**
Allow either a range of ghidra version to be specified or to specify a comma separated list of versions.

**Describe alternatives you've considered**
See the Building section of this repository's [README](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer).

**Comment by lab313ru** [comment]
I think it's impossible because of base classes changing. Some methods are changing its signatures, some ideas become unused. So, how would you plan to support such things?

**Comment by astrelsky** [comment]
> I think it's impossible because of base classes changing. Some methods are changing its signatures, some ideas become unused. So, how would you plan to support such things?

If the extension/plugin maker knows their plugin wouldn't be compatible with older/newer versions they would omit the version. If nothing changed between versions which affects the plugin why should it need to be redistributed with the only change being a version number.

**Comment by ryanmkurtz** [comment]
This is a big limitation with our extension system.  What you are suggesting doesn't address the real problem, but it would be simple to implement and make it slightly less annoying to distribute.  It would be up to extension writer to thoroughly test their extension with new versions of Ghidra before bumping the supported range up.

**Comment by astrelsky** [comment]
This idea is pretty much useless.

**Comment by ryanmkurtz** [comment]
This has become OBE because we now allow mismatched extension versions to be installed with a warning.
