### ISSUE TITLE
Setting a default function name within a namespace deletes the function name

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1194]
**Describe the bug**
Editing the label through the listing to set a namespace to a function removes the function name.

**To Reproduce**
1. Go to a function label
2. stick a namespace and :: before the function name

**Expected behavior**
The function to keep its name and be added to the specified namespace. 

**Screenshots**
Before:
![before](https://user-images.githubusercontent.com/46897303/67900066-fdb95500-fb39-11e9-846e-01d73ec5c3e0.PNG)

Changing Name:
![mid](https://user-images.githubusercontent.com/46897303/67900072-001baf00-fb3a-11e9-9980-064d952db365.PNG)

After Change:
![after](https://user-images.githubusercontent.com/46897303/67900075-014cdc00-fb3a-11e9-903d-3e2cdbfd443c.PNG)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18362.418]
 - Java Version: 13.0.1
 - Ghidra Version: 9.2

**Comment by dragonmacher** [comment]
I have not seen that before.   My guess is that we don't allow you to name a function using the default  function name pattern.   Further, once the name is removed from the string, it no longer looks like a namespace/name combination, so it just takes what is given as the name.

We should update the dialog to prevent this behavior, prompting the user as needed.

**Comment by astrelsky** [comment]
> I have not seen that before. My guess is that we don't allow you to name a function using the default function name pattern. Further, once the name is removed from the string, it no longer looks like a namespace/name combination, so it just takes what is given as the name.
> 
> We should update the dialog to prevent this behavior, prompting the user as needed.

This always worked prior to 9.2. I have always set the namespace this way.

**Comment by astrelsky** [comment]
Ok to make things less confusing I'm creating another comment.

@dragonmacher I found that if you take an existing function that is not a default name and is within a namespace and then rename the function to its default function name, the function name gets deleted.

Before:
![before](https://user-images.githubusercontent.com/46897303/67902919-a9fe3a00-fb40-11e9-95ae-8310e9b8d3a7.PNG)


Changing name to default:
![mid](https://user-images.githubusercontent.com/46897303/67902938-b2ef0b80-fb40-11e9-9479-3d14e06fb014.PNG)


After change:
![after](https://user-images.githubusercontent.com/46897303/67902948-b8e4ec80-fb40-11e9-83b8-7a1240680b5b.PNG)

**Comment by dragonmacher** [comment]
I see.  Sounds like a regression then. 

Thanks for the info.

**Comment by dragonmacher** [comment]
I just tried this and it works as expected.   Is this still broken for you?

**Comment by astrelsky** [comment]
> I just tried this and it works as expected. Is this still broken for you?

It appears to have been resolved by a recent commit. Thank you!
