### ISSUE TITLE
Plugin development

### ISSUE THREAD

**Issue by meromwolff** [NationalSecurityAgency/ghidra#1198]
Hi,

Is it possilbe currently to develop a Plugin for Ghidra using only the Python API?

Thanks in advance.

**Comment by dev747368** [comment]
I don't think so.  The plugin system uses java reflection to find Plugin implementations and lets the user enable / disable them in the config screen.
As a bit of a hack, you could have a stub java class that Ghidra finds and deals with, and then it would forward the relevant calls to the python implementation.

**Comment by astrelsky** [comment]
> I don't think so. The plugin system uses java reflection to find Plugin implementations and lets the user enable / disable them in the config screen.
> As a bit of a hack, you could have a stub java class that Ghidra finds and deals with, and then it would forward the relevant calls to the python implementation.

I guess you could consider it the same thing you would do when extending python with c, just in reverse.

**Comment by meromwolff** [comment]
Thanks! Ill look into it.
