### ISSUE TITLE
Make public build fully reproducible 

### ISSUE THREAD

**Issue by abenson** [NationalSecurityAgency/ghidra#1199]
1. Currently, 9.1 is missing a tag/release.
2. Would you be able to attach source tarballs with the dependencies ready for build of -PUBLIC versions?

**Comment by ryanmkurtz** [comment]
1. Done
2. Not sure what you are exacting for exactly.  Can you provide more details?

**Comment by abenson** [comment]
According to the concept of reproducible builds, I should be able to take the source and build an identical version to the one as released. Building from the tag, I'd still be building "DEV", not the "PUBLIC" as released on the website. I was trying to ask for a build-ready tarball with the deltas between DEV and PUBLIC.

**Comment by ryanmkurtz** [comment]
Ah ok.  We do a custom multi-platform build, which includes a couple of other steps like editing the application.properties to change the release name.  I'll rename this ticket so it's a bit more clear what you are asking for.

**Comment by ryanmkurtz** [comment]
We discussed this a bit and at this time have no plans to try to provide a reproducible build.
