### ISSUE TITLE
Any sort of rebase option?

### ISSUE THREAD

**Issue by Merculous** [NationalSecurityAgency/ghidra#12]
I'm no expert with all programs, and I took the time to look at the manual. Either I'm missing something, or this program does not contain any set of tools to make this happen. My program I want to debug relies on a  certain memory address contained within the program itself, iBoot. I need to make my memory output as 0x5FF00000 and right now, its increment is from 0x0. Basically, all I need is to have the memory layout as such rather than starting from 0x0. Anyone who has solved this, please let me know!

**Comment by xzcvczx** [comment]
there is the options button (Base Address) in the import file dialog, (it works for raw binary) not sure what you file format is but can that do what you need?

**Comment by Merculous** [comment]
This was exactly what I needed! Sorry about the noob question as I just realized I totally didn't see the button. I was a little too excited and completely looked over the button to find what I needed! Thanks!

**Comment by WasserEsser** [comment]
For a rebase after the binary has been loaded, open the Memory Map window and press the house at the top right.

**Comment by WasserEsser** [comment]
!(image)[https://files.watercod.es/c09514b90.png]
