### ISSUE TITLE
ObjectiveC2 Analysis: "Symbol Name can't be empty" in 9.1-BETA and above

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#1200]
**Describe the bug**
Some IPhone app binaries lead to the ObjectiveC2 Class analysis failing with "Symbol Name can't be empty" when using the 9.1-BETA or recent master 305160120630366d2b2e09807af1fdd83633a310

**To Reproduce**
1. Import https://github.com/angr/binaries/raw/master/tests/armhf/FileProtection-05.arm64.macho
2. Run the Auto Analysis Defaults, specifically "Objective-C 2 Class"
3. Get the report that includes "Symbol Name can't be empty" 

**Expected behavior**
Same as 9.0.4 and below

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11
 - Ghidra Version: Both own build of recent master ( 305160120630366d2b2e09807af1fdd83633a310 ) and ghidra_9.1_PUBLIC_20191023 release.  No issues when using the 9.0.2 or 9.0.4 release

**Comment by fmagin** [comment]
Bisected this, the commit that introduced the issue seems to be b8f042da801a983f536ec402dc42662e67e76940 by @ryanmkurtz 
This commit changes a lot so I don't expect that I will be able to easily track down what exactly broke this. Would be nice to get some feedback if some official maintainer will be working on this or if I need to invest more time.

**Comment by ryanmkurtz** [comment]
Thanks for tracking it down...I'll take a look.

**Comment by fmagin** [comment]
I found a bit more, the first issue seems to happen when the `SITAppDelegate` Class is read.

ghidra.app.util.bin.BinaryReader#readAsciiString(long) reads from address 0x1000076ad which contains the string `SITAppDelegate` ( no matter if opening the binary in a working or non working version of Ghidra). This returns the empty string in the broken versions because `index < provider.length()` is false in that case.

**Comment by fmagin** [comment]
The provider can actually read the data just fine as tested with evaluating `provider.readBytes(index, 10)` while inside `provider.readBytes(index, 10)`.
`provider.length()` just returns 0 and that breaks things. Which happens because `ghidra.app.util.bin.MemoryByteProvider#length` attempts to get the block `memory.getBlock(baseAddress)` but `baseAddress` is 0 and it `getBlock` returns `null`

**Comment by ryanmkurtz** [comment]
Thanks, I am working on a fix!

**Comment by ryanmkurtz** [comment]
For now I simply undid the change that broke this...which was originally done to speed the method up.  We are going to look into preventing the provider length coming back as 0 as a separate issue.  You'll notice the code I reverted back to is also checking the provider's length, but it turns out to be a non-issue for the problem you found here.

**Comment by fmagin** [comment]
Thanks for the help!
