### ISSUE TITLE
Your official website has been unable to open

### ISSUE THREAD

**Issue by Waterman178** [NationalSecurityAgency/ghidra#1202]
![111](https://user-images.githubusercontent.com/14991217/68046157-26964180-fd16-11e9-8443-4f99c7cd6e27.png)
website:https://ghidra-sre.org/
Sometimes it can be opened, but when I download version 9.1, the connection is suddenly disconnected.

**Comment by astrelsky** [comment]
Might be regional. I was able to connect and download ghidra 9.1 within 30 seconds.

**Comment by Waterman178** [comment]
> 可能是区域性或本地性。我能够在30秒内连接并完成ghidra 9.1的下载。

I have tried it for a few days, disconnected every time.Can you upload it to github?Thanks!

**Comment by Waterman178** [comment]
> Might be regional or local. I was able to connect and finish the download for ghidra 9.1 within 30 seconds.

I have tried it for a few days, disconnected every time.Can you upload it to github?Thanks!

**Comment by OronDF343** [comment]
Hi, I am also experiencing the same error when trying to browse to the home page.

**Comment by saruman9** [comment]
Dup of #32

**Comment by ryanmkurtz** [comment]
Duplicate
