### ISSUE TITLE
FunctionID: FAILS_MINIMUM_SHORTHASH_LENGTH

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#1205]
I'm trying to use FunctionID, and after populating database from programs, I'm getting this:
`FAILS_MINIMUM_SHORTHASH_LENGTH: 2224`
Does it mean that these 2224 functions has too small body? How can I increase (or fix) tit?

**Comment by lab313ru** [comment]
I found why: https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/FunctionID/src/main/java/ghidra/feature/fid/service/FidService.java#L45

For example, I have a function:
```
.text:00000674                 lbu     $v0, byte_3452
.text:0000067C                 jr      $ra
.text:00000680                 nop
```
Will it be added?

**Comment by astrelsky** [comment]
No. This is a good thing as if that function were to be added to the database you would get a match for that everywhere. Before I figured out how to build an FIDB and was using old flair signatures I found on the web I was getting annoyed by having 1000+ functions marked as ~__pbase_type_info and such.

If you truly want to match that for something, you could add it as a pattern in processor/data/patterns/{file_name}.xml depends on what processor your working with.

**Comment by lab313ru** [comment]
Patterns cannot be named (like signatures).

Also, Playstation 1 (MIPS) BIOS calls are usually contain only three instructions. So it requires minimum three instructions as the threshold.

**Comment by astrelsky** [comment]
> Patterns cannot be named (like signatures).
> 
> Also, Playstation 1 (MIPS) BIOS calls are usually contain only three instructions. So it requires minimum three instructions as the threshold.

[Named pattern](https://github.com/beardypig/ghidra-emotionengine/blob/9c8e9f34792c89c1eb36853eb39f5ff21f796f81/data/patterns/r5900_LE_patterns.xml#L47-L50)

**Comment by lab313ru** [comment]
Thanks! It looks useful.
