### ISSUE TITLE
XML parser entity limit reached while handling large PDB.

### ISSUE THREAD

**Issue by UnknownMiscreant** [NationalSecurityAgency/ghidra#1207]
Hi,

I'm currently trying to apply a 500MB PDB file to a 38MB exe (yes I'm well aware its massive) I'm running into issues with the XML parser object limit. (System memory isn't an issue, the system has 32GB ram and I'm running ghidra with a 8GB ram limit, of which around 4.5GB is being used.

`Problem parsing or applying PDB information: org.xml.sax.SAXParseException; lineNumber: 14565172; columnNumber: 328; JAXP00010004: The accumulated size of entities is "50,000,001" that exceeded the "50,000,000" limit set by "FEATURE_SECURE_PROCESSING".`

I can give the stack output etc if that helps. 

I gather this is something to do with the XML library to prevent denial of service attacks or similar. I have tried disabling FEATURE_SECURE_PROCESSING in the XmlUtilities class by calling the `setFeature` method with `false` but to no avail. 

It gave me the error while applying symbols, and yet it seems to have continued applying functions.
Does anyone have any ideas?
Thanks in advance.

**Comment by UnknownMiscreant** [comment]
Update: same error about an hour later while applying functions.

**Comment by UnknownMiscreant** [comment]
2nd update: finished processing the ~200k functions okay but theres a few ~100 that haven't been assigned names.

**Comment by ghizard** [comment]
Sounds awfully large.  Are the binary and PDB available at a public site that I can trust (e.g., Microsoft, Amazon)? The largest I have is a 50MB PDB and associated qrenderdoc.exe file that someone else (#1015) gave public download information for.

I don't have any ideas on the XML at this time, but am working on a newer, non-DIA/non-XML PDB capability.  I'm interested in how it will perform on large files and whether we need to support a random-access processing model for them.

**Comment by UnknownMiscreant** [comment]
I was disasembling the leaked debug build and PDB of Generation Zero (futuristic game where you fight robots) a bunch of debug builds and PDB files were leaked in the free weekend on steam (sadly it ended ~12hrs ago.) The debug builds/pdb may still be included, but its a $60 gamble to find out although you could probably get a refund.

Totally understand not wanting random people sending you executable code. However sadly given the free weekend has ended I don't know of any trusted sources.

The entire PDB analysis for me only took ~3hrs using ghidra 9.1. Mind you my computer is in the more overkill end of the spectrum. 

As a side note for large files I've noticed the RTTI analysis often runs for a very long time and never completes, I've left it running over 36hrs in one instance. Re running analysis with it disabled finishes up in around 3hrs.

**Comment by ghizard** [comment]
I've asked some other folks about large PDBs, and they don't seem to have any like yours.  Consider yours a treasure, I guess.  Perhaps you will have the opportunity to try again when we have improved the PDB capability.  But your ticket gives us a data point to try to plan for.  We could also try to fix the XML parser with a large non-PDB XML file to see how to safely get beyond the 50M node limit, but I don't know where that would fall in priorities.

I believe there was a report early on (maybe around Mar-Apr) about RTTI analysis running slowly. It needs a bit of work regarding speed/performance and in the realm of missing TypeInfo structure.

**Comment by UnknownMiscreant** [comment]
More than happy to test stuff for you guys. Although bear in mind I haven't been able to get the ghidra source building yet. Going to look into that more.

Attached is a screenshot of the error message. This was from an unedited version of 9.1.
I'm currently trying to disassemble the 300MB PDB for the release version. Been running for ~2hrs and no errors yet.
![ghidra issues](https://user-images.githubusercontent.com/36900279/68167002-f88c5800-ffc8-11e9-9b03-0b54eecee21b.jpg)

**Comment by ghizard** [comment]
Thanks for the screen shot.

I do not have much knowledge of the build system; I'm used to having a lot of the build done for me, and I tend to just work out of eclipse.  Last week, I decided I wanted to play with some stuff at home, including running a particular set of unit tests out of eclipse and find that I probably need to do a bit of set-up to get into the state where I can do simple work.  I have Linux at work and Windows at home, and am trying to work through the developer guide, but have questions too.

**Comment by UnknownMiscreant** [comment]
It might be its all written for linux setup. Alot of my issues would probably have gone away had I managed to get gradle installed properly.

**Comment by UnknownMiscreant** [comment]
Update: the 40/300MB exe/pdb disassembled fine. Took around 6hrs to run to completion. 

There was a ton of disassembly/pdb analysis related errors, but it stayed within the 50million xml entries.

**Comment by ryanmkurtz** [comment]
I just made some changes to make the Windows build a little less strict about what version of Visual Studio and the Widows SDK's you have installed, so you might want to try building again with the latest master.  If you are still having problems, I'd be happy to help you with build issues.

**Comment by SamB** [comment]
Sounds like something doesn't do a good job distinguishing between a [Billion laughs attack](https://en.wikipedia.org/wiki/Billion_laughs_attack) and a file that just happens to be really big. Seems like the parser shouldn't really complain unless the expanded:raw size ratio is high, rather than flat-out refusing to process anything that expands to more than 50 million characters ...

Anyway, it looks like you can at least adjust this with the `jdk.xml.totalEntitySizeLimit` system property, or the `http://www.oracle.com/xml/jaxp/properties/totalEntitySizeLimit` API property...

Oh look, it's even documented: https://docs.oracle.com/javase/tutorial/jaxp/limits/limits.html

**Comment by spacehamster** [comment]
Hi, I'm getting the same issue trying to disassemble Unity 2018.4.0f1. The pdb is 475 MB, the exe is 75 MB (the pdb included with the install is much smaller but the full Pdb is available on the symbol server). Is there a command line argument or setting that can work around the issue?

**Comment by ghizard** [comment]
I have a PDB where I just validated the issue today.

I applied these three VM arguments (https://stackoverflow.com/questions/42991043/error-xml-sax-saxparseexception-while-parsing-a-xml-file-using-wikixmlj) to the ghidra launch.properties file and was able to confirm that the PDB analyzer got past the 50M limit.  I have not yet determined if all the properties are needed or what their default values are, but believe the SAX parser is limited on purpose to a value that they believe is appropriate.

I just want to inform you of what I found and am not recommending that you make this change.

We hope to have a different solution available soon.

**Comment by ghizard** [comment]
@SamB Thanks for that information. I didn't read what you wrote until now.  That helps.

**Comment by ghizard** [comment]
I ran a couple of more times, to find out that the key variable for me is:
```VMARGS=-Djdk.xml.totalEntitySizeLimit=50000000```
where I adjusted the 50000000 (default) to a larger value.

```VMARGS=-DtotalEntitySizeLimit=some_limit``` by itself, it did not help.
```VMARGS=-DentityExpansionLimit=some_limit``` did not seem to be needed.

**Comment by ghizard** [comment]
Work-around, as suggested above, works.
