### ISSUE TITLE
Can't launch Ghidra on Windows

### ISSUE THREAD

**Issue by stefan-stoj** [NationalSecurityAgency/ghidra#121]
Java JRE and JDK are both installed and PATH environment variable is configured properly.

When I run the ghidraRun.bat file a terminal windows opens and immediately closes afterwards.
In task manager I can see a OpenJDK Platform binary process being created each time I run the ghidraRun.bat file but Ghidra doesn't launch.

when I run support/ghidraDebug.bat I get the following output and then the terminal just stalls and does nothing:
```
INFO  Using log config file: jar:file:/C:/Users/Stefan/Ghidra/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)
INFO  Using log file: C:\Users\Stefan\.ghidra\.ghidra-9.0\application.log (LoggingInitialization)
INFO  Loading user preferences: C:\Users\Stefan\.ghidra\.ghidra-9.0\preferences (Preferences)

```

**Comment by ryanmkurtz** [comment]
Can you please provide the output of:

- java -version
- javac -version
- The contents of C:\Users\Stefan\.ghidra\.ghidra-9.0\java_home.save

**Comment by stefan-stoj** [comment]
```
C:\Users\Stefan>java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

C:\Users\Stefan>javac --version
javac 11.0.2
```

C:\Users\Stefan\.ghidra\.ghidra-9.0\java_home.save
```
C:\Java\jdk-11.0.2
```

**Comment by ryanmkurtz** [comment]
Thanks.  What version of Windows are you on?  Does the support/pythonRun.bat script work?

**Comment by stefan-stoj** [comment]
Windows 10 Pro
Version 1803
OS build 17134.590

Output of support/pythonRun.bat
```
INFO  Using log config file: jar:file:/C:/Users/Stefan/Ghidra/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)
INFO  Using log file: C:\Users\Stefan\.ghidra\.ghidra-9.0\application.log (LoggingInitialization)
INFO  Loading user preferences: C:\Users\Stefan\.ghidra\.ghidra-9.0\preferences (Preferences)
INFO  Class search complete (702 ms) (ClassSearcher)
INFO  Initializing SSL Context (SSLContextInitializer)
INFO  Initializing Random Number Generator... (SecureRandomFactory)
INFO  Random Number Generator initialization complete: SHA1PRNG (SecureRandomFactory)
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/C:/Users/Stefan/Ghidra/Ghidra/Features/Python/lib/jython-standalone-2.7.1.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43)
[OpenJDK 64-Bit Server VM (Oracle Corporation)] on java11.0.2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
Then it defaults into a python prompt

**Comment by ryanmkurtz** [comment]
Since pythonRun seems to be working, it's probably GUI related.  Are you remote desktopped in to your Windows machine?  Is there anything weird about your graphic setup?

**Comment by stefan-stoj** [comment]
Looks like my third monitors was the problem.
I'm running a triple monitor setup, and my third monitor is actually a TV screen. I've had some issues previously where apps would launch on that monitor but not be displayed initially. I could see that they had been launched because of the icon in the taskbar and could then move them to another monitor, and back to the TV which would make them display properly.

The issue with Ghidra is that the initial EULA doesn't create an icon in the taskbar so I didn't know that it had been launched but just not displayed properly. Disconnecting my third monitor made the EULA show up on one of my regular monitors and everything works as expected from there :)
