### ISSUE TITLE
How to prevent generic_clib from automatically opening?

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1212]
Every time I reopen my project, the generic_clib is automatically re-opened regardless of how many times I close it and save the project. There are no datatypes in the project or datatype managers which are relying on the archive. I need to keep the archive out of the project due to #1116 .

**Comment by dragonmacher** [comment]
Presumably, there is some dependency from your program's archive to the clib archive.

To test this I:

1. Closed all open programs from the Listing
2. Closed all Standard Archives still open
2. With the Tool open, I closed Ghidra from the Front End

When I restarted, I had an empty tool with no Standard Archives open.   When I reopened my last program in the Tool, the clib archive was reopened.    This tells me that my program's archive is using data types from clib.

If you right-click on the program's archive, you should see in the popup menu an action named 'Disassociate Datatypes from'.  From this action, you can click the clib archvie entry.  This will present to you a dialog with all types used from clib.   This shows you any dependencies that a particular program has on clib.

**Comment by astrelsky** [comment]
Thank you that did the trick. I must have accidentally run the analysis with the apply datatype archives analyzer enabled and not didn't notice.

@dragonmacher if the program was depending on types from the archives shouldn't have I been unable to close it?
