### ISSUE TITLE
x86_64 Linux SYSCALL ignoring dependencies

### ISSUE THREAD

**Issue by kazkansouh** [NationalSecurityAgency/ghidra#1216]
**Describe the bug**

I am reversing a binary and have noticed an issue that in the decompiler it appears that the register dependencies on  `SYSCALL` are ignored.

For example. Consider the following simple program that essentially calls `ptrace(PTRACE_TRACEME,0,0)` using `SYSCALL` and prints the result:
```c
#include <stdio.h>

int main() {
  register long int result = 101; // ptrace syscall number

  asm volatile
    (
     "movq %0, %%rax\n"
     "movq $0, %%rdi\n"
     "movq $0, %%rsi\n"
     "movq $0, %%rdx\n"
     "syscall\n"
     "movq %%rax, %0\n"
     : "+r" (result)
     : // no inputs
     : "rax", "rdi", "rsi", "rdx"
     );

  switch (result) {
  case 0:
    printf("not being debugged\n");
    break;
  case -1:
    printf("being debugged\n");
    break;
  default:
    printf("unsure, result = %ld\n", result);
  }
  return 0;
}
```

After compiling with:

```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc -Wall -c syscall-ptrace.c 
```

the following asm is obtained:

```asm
0000000000000000 <main>:
   0:   55                      push   rbp
   1:   48 89 e5                mov    rbp,rsp
   4:   53                      push   rbx
   5:   48 83 ec 08             sub    rsp,0x8
   9:   bb 65 00 00 00          mov    ebx,0x65
   e:   48 89 d9                mov    rcx,rbx
  11:   48 89 c8                mov    rax,rcx
  14:   48 c7 c7 00 00 00 00    mov    rdi,0x0
  1b:   48 c7 c6 00 00 00 00    mov    rsi,0x0
  22:   48 c7 c2 00 00 00 00    mov    rdx,0x0
  29:   0f 05                   syscall 
  2b:   48 89 c1                mov    rcx,rax
  2e:   48 89 cb                mov    rbx,rcx
  31:   48 83 fb ff             cmp    rbx,0xffffffffffffffff
  35:   74 13                   je     4a <main+0x4a>
  37:   48 85 db                test   rbx,rbx
  3a:   75 1c                   jne    58 <main+0x58>
  3c:   48 8d 3d 00 00 00 00    lea    rdi,[rip+0x0]        # 43 <main+0x43>
  43:   e8 00 00 00 00          call   48 <main+0x48>
  48:   eb 22                   jmp    6c <main+0x6c>
  4a:   48 8d 3d 00 00 00 00    lea    rdi,[rip+0x0]        # 51 <main+0x51>
  51:   e8 00 00 00 00          call   56 <main+0x56>
  56:   eb 14                   jmp    6c <main+0x6c>
  58:   48 89 de                mov    rsi,rbx
  5b:   48 8d 3d 00 00 00 00    lea    rdi,[rip+0x0]        # 62 <main+0x62>
  62:   b8 00 00 00 00          mov    eax,0x0
  67:   e8 00 00 00 00          call   6c <main+0x6c>
  6c:   b8 00 00 00 00          mov    eax,0x0
  71:   48 83 c4 08             add    rsp,0x8
  75:   5b                      pop    rbx
  76:   5d                      pop    rbp
  77:   c3                      ret    
```

However, after loading this into Ghidra, the following decompilation is presented:

```c
/* WARNING: Removing unreachable block (ram,0x001006c6) */
/* WARNING: Removing unreachable block (ram,0x001006d4) */

undefined8 main(void)

{
  syscall();
  printf("unsure, result = %ld\n",0x65,0);
  return 0;
}
```

As can be seen it ignores any relation between `SYSCALL` and the registers it affects.

For me, I think this is a fairly important issue as the `ptrace` trick above is often used by malware to detect being debugged. However, it appears that in Ghidra it also causes problems for a different reasons in that neither of the expected branches of the case statement are presented in the decompilation.

That is, when running the binary normally the first case is taken:
```
$ ./syscall-ptrace 
not being debugged
```
And when running in GDB the second case is taken:
```
$ gdb ./syscall-ptrace 
GNU gdb (Ubuntu 8.1-0ubuntu3.1) 8.1.0.20180409-git
....snip....
(gdb) r
Starting program: syscall-ptrace 
being debugged
```
But Ghidra presents the third case only.

**Expected behavior**
Decompiler notices that `RDI`, `RSI`, `RDX` are set before `SYSCALL` and that `RAX` is set afterwards.

**Environment (please complete the following information):**
 - OS: Linux x64_86
 - Java Version: 11.0.4
 - Ghidra Version: 9.1 Public 2019-Oct-23
 - GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by astrelsky** [comment]
You can run [ResolveX86orX64LinuxSyscallsScript](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/ghidra_scripts/ResolveX86orX64LinuxSyscallsScript.java) to resolve them. It may be found in the Analysis category.

Output after running script:
```
undefined8 issue1216(void)

{
  long lVar1;
  
  lVar1 = ptrace(PTRACE_TRACEME,0,0);
  if (lVar1 == -1) {
    puts("being debugged");
  }
  else {
    if (lVar1 == 0) {
      puts("not being debugged");
    }
    else {
      printf("unsure, result = %ld\n",lVar1);
    }
  }
  return 0;
}
```

More information on this is available in the Recon MTL 2019 presentation by @ghidracadabra and @emteere . https://github.com/NationalSecurityAgency/ghidra/wiki/Presentations

**Comment by kazkansouh** [comment]
Hello @astrelsky  - Many thanks for the help and presentation link. It nicely resolves the issue.
