### ISSUE TITLE
ARM: VMUL not decompiled properly with VFPv2/VFPv3

### ISSUE THREAD

**Issue by lioncash** [NationalSecurityAgency/ghidra#1217]
**Describe the bug**
When decompiling any binary built with VFPv2/VFPv3 vector extensions for the 32-bit variant of ARM, these instructions get decompiled as CDP instructions. While not necessarily wrong, this does make the instructions significantly more annoying to read.

This [appears](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/ARM/data/languages/ARMneon.sinc#L2992-L3002) to be due to the fact that Sleigh constructors only exist for the NEON A1/T1 variants of VMUL.

There doesn't seem to be constructors for the VFPv2/VFPv3/VFPv4 A2/T2 variants that allow a condition code on the A2 variant.

Just figured that I'd report this in case it was an oversight.

**To Reproduce**
1. Decompile any application variant that makes use of VFPv2/VFPv3 variants of VMUL.
2. Notice that it gets decompiled as a CDP instruction.
3. Despair

**Expected behavior**
The instructions get decompiled as VMUL variants, and not as CDP instructions.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 12.0
 - Ghidra Version: 9.1

**Comment by emteere** [comment]
Fixed by #2677
