### ISSUE TITLE
Display Doesn't Update From Scripts That Use Java Swing GUI

### ISSUE THREAD

**Issue by ebfe2326** [NationalSecurityAgency/ghidra#1218]
**Describe the bug**
If I create a java or jython script that uses swing gui components to make changes to the program, the changes are made but the display is not updated in Ghidra until i perform some action that causes the display to be updated such as changing functions.  If I execute the identical function from a script that doesn't use a gui component, the display is immediately updated in ghidra without needing to perform any additional action.   

For example, if i have a script that updates a function name, the displayed function name immediate changes.  If i tie the identical script to a javax swing button, the function name will change, but the display will not update.  The only way I'm able to verify the change has been made is to check the function name through a script.

**To Reproduce**
1. Create a simple script with a javax swing gui and button who's action is to update the current function name
2. click the gui button to change the current function name and observe the current function name has not changed
3. check the function name via a script to see that it has indeed changed, e.g. getFunctionContaining(currentAddress)

**Example Script**
```
//TODO write a description for this script
//@author 
//@category _NEW_
//@keybinding 
//@menupath 
//@toolbar 

import ghidra.app.script.GhidraScript;
import ghidra.program.model.util.*;
import ghidra.program.model.reloc.*;
import ghidra.program.model.data.*;
import ghidra.program.model.block.*;
import ghidra.program.model.symbol.*;
import ghidra.program.model.scalar.*;
import ghidra.program.model.mem.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.lang.*;
import ghidra.program.model.pcode.*;
import ghidra.program.model.address.*;

import ghidra.util.exception.*;
import javax.swing.JFrame;
import javax.swing.JButton;
import java.awt.event.*;

public class ghidraIssue extends GhidraScript {

    public void run() throws Exception {
        JFrame frame = new JFrame("test frame");
        frame.setSize(400, 400);
        frame.setLocation(200, 200);
        frame.setTitle("Java swing frame");
        frame.setVisible(true);frame.setLayout(null);

        JButton button1 = new JButton("Change Function Name");
        button1.setBounds(0,0,100,50);
        button1.addActionListener(new ActionListener() {
          public void actionPerformed(ActionEvent e) {
            try {
              getFunctionContaining(currentAddress).setName("test",
                ghidra.program.model.symbol.SourceType.USER_DEFINED);
            } catch(Exception e1) {};
        }});

        frame.add(button1);
    }
}
```
**Expected behavior**
I'd expect the current program's display to update when a function is executed from a gui component just the same as when the function is executed in a script outside of a gui element.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: OpenJDK 12
 - Ghidra Version: 9.1

**Comment by dev747368** [comment]
When you do stuff that modifies ghidra data in the database, it needs to be in a "transaction".  When you run inside a GhidraScript's run() method, you get that for free.
In your example, you are creating the button while in the GhidraScript's transaction, but the button action callback is executed at a later time, in a different thread.

**Comment by dragonmacher** [comment]
I hope @dev747368 has answered you question.

Scripts are intended for simple API usage and program modification.  Once users start creating UI elements, we recommend that they create a Plugin.   You can still create code as you did in your example, but you have to wrap any work you do in a transaction, as @dev747368  mentioned.

```
int txId = program.startTransaction("My Script Transaction");
boolean commit = false;      
try {
	// perform script calls here

	// commit if there is no exception
	commit = true;
}
finally {
	curentProgram.endTransaction(txId, commit);
}
```

**Comment by ebfe2326** [comment]
thanks for the info.  I'll look into the Plugin, but i was a little confused from the documentation i found so far.  One quick question in the meantime until i figure out how to make the plugins.

Is there a way for me to access the current ghidraState from within the GUI?

If i use the transaction method you showed in your example, it works, but the ghidra state doesn't get updated once i enter the gui component.  For example, the currentAddress doesn't get updated as I select new instructions, it stays at whatever the address was when i launched the gui.  that makes sense that the ghidra state isn't getting passed into the action event.  I've looked, but haven't found a way to access the ghidra state through the scripting API so that I could get the updated currentAddress after I launch the gui.  Ideally, i'd like to be able to track the currentAddress from within the gui element as a stop gap measure until i learn more about writing the plugin.

**Comment by dragonmacher** [comment]
If tracking the current location is all you need, then you can do that via the `ghidra.app.services.CodeViewerService`. 

```
CodeViewerService codeViewer = state.getTool().getService(CodeViewerService.class);
ProgramLocation location = codeViewer.getCurrentLocation();
Address adress = location.getAddress();
```
