### ISSUE TITLE
DataUtilities.createData() gives unexpected results

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#1219]
When Invoking DataUtilities.createData(), if the existing data was an address the result seems to be a pointer to the DataType I am attempting to create, even if I specify CLEAR_ALL_CONFLICT_DATA.  I have to clear the listing before invoking createData() to get consistent results.

**To Reproduce**
Invoke DataUtilities.createData to create some data, let's say some structure X.  If the existing data is "address", this will end up creating a pointer to structure X.  If the existing data is anything else, or if it is undefined, it will end up creating a structure X.

**Expected behavior**
The result should be an instance of the DataType passed in existing at the address specified, regardless of whatever existed or not before the call (at least, if CLEAR_ALL_CONFLICTING_DATA is specified).

**Comment by astrelsky** [comment]
Try setting the stackPointers parameter to false.

**Comment by marcushall42** [comment]
Yea, Okay..  I had been moving around some old code and came across my working around this.  From the comment in the code, I gather that this parameter used to be called "convertPointers" and seemed to be less well documented.  I believe that I set it to true without looking a lot deeper with the thought "Of course.  Convert everything to my new DataType.  I don't care what was there."

But, although it seems like a weird option to have, and kind of strange behavior, it *is* documented well enough (and I can no longer speak to how well it may have been described previously).  I still don't know that "stackPointers" encompasses the idea, but I certainly couldn't suggest anything better.
