### ISSUE TITLE
Cant set DecompileOptions maxWidth.

### ISSUE THREAD

**Issue by WhattaSkilL** [NationalSecurityAgency/ghidra#1221]
Hello! DecompileOptions has not set method to do this. how i can change it for postscripting in headless mode? First think its a change default values and compile project but this do nothing. Some one have ideas?

**Comment by dragonmacher** [comment]
I noticed two things about that part of the API:

1. You are correct, there is no 'set' method for 'maxWidth'.  It is only changeable via the Tool options in the UI.
2. The code that uses 'maxWidth' is only in the UI.  So, changing the value would not help in headless scripting.

If you really need to change the Decompiler output in headless mode, then you will have to write code to do this in your script or in some other post-processing software.

**Comment by WhattaSkilL** [comment]
When I try to rebuild first time i make some mistakes. Now I added set method and change default values and its work ok. Would be greate if that thing was added to project. Because automatic analyze of CCode with line warps it's a hard thing.

**Comment by dragonmacher** [comment]
This should be easy for us to fix.  

I will change this to a feature request.
