### ISSUE TITLE
Prepackaged .export files not loaded/used.

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1223]
See discussion further below. In summary the prepackaged data files, mainly the .export files seen [here](https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Features/Base/data/symbols) are not loaded from the location they are unzipped in. Many user may potentially go on using ghidra without knowing they exist. It would likely be a good idea to have them either moved into the ~/.ghidra folder or loaded from the directory in the repo layout.

So I have a windows binary loaded into ghidra which is dynamically linked to mfc42.dll among others. The main problem I'm having are all the Ordinal_{number} functions. It appears that Ghidra/Features/Base/data/symbols/win32/mfc42.exports is to be used to resolve these except there doesn't appear to be any script or relative information on how to make use of them. 

Admittedly it would be straightforward to write a script to parse it and apply the correct symbols, but I feel that they should have been automatically applied and I may have done something that caused them to not be.

**Comment by 0x6d696368** [comment]
> but I feel that they should have been automatically applied and I may have done something that caused them to not be.

They should be. However, some DLLs do export some functions only via ordinal. This could be the case. For example, the mfc110d.exports file I got only contains ordinals (see https://raw.githubusercontent.com/0x6d696368/ghidra-data/master/symbols/win32/mfc110d.exports).

You would need to load mfc42.dll and its PDB to get the names and then generate a mfc42.exports from those names, see (because it may be a bit tricky): https://github.com/NationalSecurityAgency/ghidra/issues/316

**Comment by astrelsky** [comment]
> > but I feel that they should have been automatically applied and I may have done something that caused them to not be.
> 
> They should be. However, some DLLs do export some functions only via ordinal. This could be the case. For example, the mfc110d.exports file I got only contains ordinals (see https://raw.githubusercontent.com/0x6d696368/ghidra-data/master/symbols/win32/mfc110d.exports).
> 
> You would need to load mfc42.dll and its PDB to get the names and then generate a mfc42.exports from those names, see (because it may be a bit tricky): #316

Well the thing is there was already a mfc42.exports file in the ghidra installation. I actually took a lazy approach and did some regex replace to transform it into a json file and used python to load all the symbols.

So, the file existed and the library was loaded it just didn't apply them. I wonder if it was because the release library was loaded instead of the debug one and ghidra preferred the exports of the loaded library over the values in the .export file.

**Comment by 0x6d696368** [comment]
> Well the thing is there was already a mfc42.exports file in the ghidra installation. I actually took a lazy approach and did some regex replace to transform it into a json file and used python to load all the symbols.
> 
> So, the file existed and the library was loaded it just didn't apply them. I wonder if it was because the release library was loaded instead of the debug one and ghidra preferred the exports of the loaded library over the values in the .export file.

Ah, didn't know Ghidra ships with `.exports` files.

What did you set in the import options? Maybe "Load External Libraries" causes Ghidra to use the names of the DLL directly instead of the .exports files. Or do you have a `mfc42.exports` file in `~/.ghidra/.ghidra-<VERSION>/symbols/`? I don't know whether symbols in the config directory take precedence over symbols in the install path.

My understanding on usage: You import a DLL once with the "Create Export Symbols" option enabled. Then you have the `.exports` file in your local config directory in `$HOME/.ghidra/.ghidra-<VERSION>/symbols/`. Whenever any binary imports a DLL Ghidra will use the symbols from the `.exports` files in that local config directory. These symbols will only be used during import. So you can't use them to rename already imported binaries' imports.

Hope that helps to narrow the problem down.

**Comment by astrelsky** [comment]
> > Well the thing is there was already a mfc42.exports file in the ghidra installation. I actually took a lazy approach and did some regex replace to transform it into a json file and used python to load all the symbols.
> > So, the file existed and the library was loaded it just didn't apply them. I wonder if it was because the release library was loaded instead of the debug one and ghidra preferred the exports of the loaded library over the values in the .export file.
> 
> Ah, didn't know Ghidra ships with `.exports` files.
> 
> What did you set in the import options? Maybe "Load External Libraries" causes Ghidra to use the names of the DLL directly instead of the .exports files. Or do you have a `mfc42.exports` file in `~/.ghidra/.ghidra-<VERSION>/symbols/`? I don't know whether symbols in the config directory take precedence over symbols in the install path.
> 
> My understanding on usage: You import a DLL once with the "Create Export Symbols" option enabled. Then you have the `.exports` file in your local config directory in `$HOME/.ghidra/.ghidra-<VERSION>/symbols/`. Whenever any binary imports a DLL Ghidra will use the symbols from the `.exports` files in that local config directory. These symbols will only be used during import. So you can't use them to rename already imported binaries' imports.
> 
> Hope that helps to narrow the problem down.

Oh so they weren't in the right directory then. I just unzipped the packed installation and went to work. All the exports actually exist in the repo. Now my results are fantastic.

https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Features/Base/data/symbols

**Comment by 0x6d696368** [comment]
> Oh so they weren't in the right directory then. I just unzipped the packed installation and went to work. All the exports actually exist in the repo. Now my results are fantastic.

So Ghidra doesn't use the .exports files that it ships? Or did you have some other mfc42.exports file in your local config directory?

**Comment by astrelsky** [comment]
100% ghidra does not use the .exports files that it ships with. I'm going to reopen this because this shouldn't be.

**Comment by ryanmkurtz** [comment]
We actually have someone already doing work on this feature...I need to figure out what he is improving exactly.  Perhaps it will address this issue.  I'll also run this through the debugger to see why it's not using the .export files from the installation directory...it should be (I see the code for it):

https://github.com/NationalSecurityAgency/ghidra/blob/dff40c562ab35dabae2ba71d74d5b3287fc711f3/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/LibraryLookupTable.java#L261-L290

**Comment by astrelsky** [comment]
> We actually have someone already doing work on this feature...I need to figure out what he is improving exactly. Perhaps it will address this issue. I'll also run this through the debugger to see why it's not using the .export files from the installation directory...it should be (I see the code for it):
> 
> https://github.com/NationalSecurityAgency/ghidra/blob/dff40c562ab35dabae2ba71d74d5b3287fc711f3/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/LibraryLookupTable.java#L261-L290

Cool. I noticed the code yesterday as I quickly stepped through it with a debugger myself. It did indeed find the file in the installation directory and return it. However, I had also already copied the files into the %HOME%/.ghidra directory so the issue may be somewhere else. I ran out of time yesterday and was planning on taking another look today if I have the free time but it doesn't seem like I will.

**Comment by ryanmkurtz** [comment]
Ok, I'll let you know what I find.

**Comment by ryanmkurtz** [comment]
Were you using the default loader settings?  Did you have `Load External Libraries` checked?

**Comment by astrelsky** [comment]
> Were you using the default loader settings? Did you have `Load External Libraries` checked?

Ok so I purged everything and started with a fresh project and ghidra installation. With the import external libraries disabled, it loaded the .export file just fine. However, after deleting it and enabling imports it then created an export file in the home directory (version mismatch) which was populated full of only 'Ordinal_*' names. So my best guess is that it actually is currently working as intended and was possibly something on my end.

I don't have a way to check at the moment, but what would ghidra have done if the library versions matched, but the new .export file was only 'Ordinal_*' names? Would it fall back to using the provided .export file?

**Comment by emteere** [comment]
If there isn't a .exports file delivered with Ghidra at the time you load the .dll or program that needs a .dll (that is found), Ghidra will create one in your local .ghidra directory.  This is necessary to get the purge for the functions in the .dll.  A bit hidden, and should probably be done a better way or better managed.

There was a fix in 9.1, I think, to allow you to create a .ord file I think, using the MSVC utility dumpbin.  If the change isn't there, it is in master.

**Comment by ryanmkurtz** [comment]
>  If the change isn't there, it is in master.

Not quite in master yet...it's still in review.

**Comment by emteere** [comment]
@ryanmkurtz was just about to add that in.  You beat me to it, by that much.
