### ISSUE TITLE
Graph Service - AST

### ISSUE THREAD

**Issue by JustAnotherCoderOnASaturday** [NationalSecurityAgency/ghidra#1228]
Hi! I want to be able to utilize the scripts, GraphAST/GraphASTAndFlow/GraphSelectedAST in Ghidra, but it requires Graph Service. Do you have any scripts that could fulfill the Graph Service or have any plugins that can do so?

**Comment by dragonmacher** [comment]
We currently do not have an implementation of the Graph Service that you can use.  However, we hope to have one soon.

**Comment by saruman9** [comment]
Dup of #174
