### ISSUE TITLE
Indirect jump resolution

### ISSUE THREAD

**Issue by Docteur-Lalla** [NationalSecurityAgency/ghidra#1229]
Hello everyone,

I am writing a headless script to recover an overapproximation of the interprocedural control-flow graph of a program. I have been able to have all the direct jump targets and a few function-pointer addresses using SimpleBlockModel. I can use, using the whole Ghidra interface, that switch statements are pretty well recovered, even though I have not found how to do it from the Java API yet.

My questions are: is there already a way to get what I want implemented in Ghidra? Otherwise, where in the API should I look at to implement it myself?

Thank you in advance.

**Comment by emteere** [comment]
Not quite sure what you are asking for.
You can use the CallBlockModel which will only give you inter-procedural references.

The indirect references, if they have been recovered will be part of the simple block model as I recall.  It will be an indirect reference.  I think it creates a SimpleBlock at the destination, even for data, but it is possible it does not.
If it doesn't, you would need to get the data at the destination of the indirect simpleblock, call the getAddress(0) method for the first operand.  Then go back to the simpleblock model and ask for the block at the address.

**Comment by Docteur-Lalla** [comment]
Thank you for the reply.

I currently have a CodeBlockModel and I am doing more or less what you just wrote. My problem is that most indirect jumps are not resolved. My question was whether Ghidra provides functionalities to help me get an approximation of the set of destinations for such jumps.
