### ISSUE TITLE
Window corruption in CodeBrowser and Program Manager

### ISSUE THREAD

**Issue by jkgriesser** [NationalSecurityAgency/ghidra#123]
**Describe the bug**
Window corruption in CodeBrowser and Program Manager. See the screenshots.

**To Reproduce**
1. Open a binary in CodeBrowser (In this instance, I've used Windows' own notepad.exe, but have encountered the issue on every binary).
2. Navigate to the entry point, and hover over a local variable or parameter name in the Listing window.
3. A subsequent click within the Listing window will cause the corruption.

**Expected behavior**
No window corruption.

**Screenshots**
![codebrowser](https://user-images.githubusercontent.com/33034154/54032844-a4677480-41aa-11e9-8fca-1d4b5a20f8ea.png)
![program manager](https://user-images.githubusercontent.com/33034154/54032848-a7fafb80-41aa-11e9-8e6f-833aaf25f688.png)

**Environment (please complete the following information):**
 - OS: Windows 10 [Version 10.0.17134.590] (latest)
 - Java versions: Oracle JDK 11.0.2 2019-01-15 LTS (latest), as well as OpenJDK 11.0.2

**Additional context**
 - GeForce (GTX 980 Ti) driver version: 419.17, as well as 419.35 (latest)
 - Screen resolution: 1920x1200 (not scaled)
 - Screen orientation: Landscape
 - Swing Look and Feel: Windows (default); NB: Changing this option doesn't affect the outcome.

**Comment by jkgriesser** [comment]
I found the root cause: ASUS' Sonic Suite 2, specifically SS2Svc64.exe, which came with my motherboard's Realtek HD Audio driver.

**Resolution**
Do one of the following:
* Close Sonic Suite via the system tray icon before starting Ghidra.
* Kill the SS2Svc64.exe process before starting Ghidra.
* Remove SS2UILauncher.exe from the Task Manager's start-up tab and reboot.

Not sure if v3 of Sonic Suite exhibits the same problem.

**Comment by ryanmkurtz** [comment]
Thanks for posting the resolution to this issue.
