### ISSUE TITLE
Decompiler does not parse arguments

### ISSUE THREAD

**Issue by 4el0ve4ik** [NationalSecurityAgency/ghidra#124]
Hi, I noticed that the decompiler does not see the arguments of functions that are pushed onto the stack via the mov instruction. For example:
`8b 0d e4 a0 21 10      MOV        ECX,dword ptr [DAT_1021a0e4]                     
`
`e8 33 d9 ff ff     CALL       FUN_100637c0                             
`

in decompiler looks like:
![image](https://user-images.githubusercontent.com/25685041/54033071-65461d00-41c4-11e9-9490-f85136b44de0.png)
__thiscall function prototype

**Comment by nsadeveloper789** [comment]
The MOV is from memory (perhaps static space) to ECX. On 32-bit system, this is not usually a parameter. If you think ECX is being used to pass a parameter, you can edit the function's conventions. Right-click on the function name in the disassembly listing and select Edit Function. Then check Use Custom Storage, and add the parameter. Double-click the Storage cell to modify it.
