### ISSUE TITLE
Decompiler: add support for bracing style option

### ISSUE THREAD

**Issue by aldelaro5** [NationalSecurityAgency/ghidra#1240]
**Is your feature request related to a problem? Please describe.**
Due to personal preference, I prefer to read code where the opening braces is on its own line as I have an easier time to see the closing one as it's aligned vertically.  Currently, the decompiler doesn't have an option to switch to this particular style which would help me read its output.

**Describe the solution you'd like**
Simple: an option in the decompiler display setting to allow to change the bracing style. It could just be a drown down menu or a checkbox, but just a way for the decompiler to do a newline before the opening brace.

**Describe alternatives you've considered**
None, this is a pretty minor suggestion.

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
Duplicate of #81
