### ISSUE TITLE
SLEIGH: How to mark register as volatile?

### ISSUE THREAD

**Issue by xyzz** [NationalSecurityAgency/ghidra#125]
In my custom processor module some registers are accessed using special instructions, `ldc` to load and `stc` to store. This includes both "normal" (as in, commonly considered general-purpose registers) `lp` (link pointer) as well as system control registers (`cfg`, etc). I've implemented it as follows:

```
define register offset=0x2000 size=4 [
	pc    lp    sar   res03 rpb   rpe   rpc   hi
	lo    res09 res10 res11 mb0   me0   mb1   me1
	psw   id    tmp   epc   exc   cfg   res22 npc
	dbg   depc  opt   rcfg  ccfg  res29 res30 res31
];

Creg: regaddr is op0000 & op0407 [ regaddr = ((op0000 << 4) | op0407) * 4 + 0x2000; ] { export *[register]:4 regaddr; }

:ldc rn, Creg is op0103=5 & op1215=7 & rn & Creg {
	rn = Creg;
}

:stc rn, Creg is op0103=4 & op1215=7 & rn & Creg {
	Creg = rn;
}
```

However, the decompiler elides writes to these registers as it doesn't think they are used. Is there a way to force some of the registers as volatile? If I try to hack around it with a custom pcodeop to ensure there's a data dependency, e.g.

```
:stc rn, Creg is op0103=4 & op1215=7 & rn & Creg {
	Creg = rn;
	control_reg_write(Creg);
}
```

the decompiler just inlines the write and I see something like `control_reg_write(in_cfg | 2)` so it's not clear which register is being written. I guess another alternative would be to display register label, so I've tried obtaining its address like this:

```
:stc rn, Creg is op0103=4 & op1215=7 & rn & Creg {
	Creg = rn;
	local addr:4 = &Creg;
	control_reg_write(addr, Creg);
}
```

but this results in the decompiler displaying the numeric address instead of the register name: `control_reg_write(0x2054,in_cfg | 2);`

**Comment by emteere** [comment]
Try this instead:

:stc rn, Creg is op0103=4 & op1215=7 & rn & Creg {
	Creg = control_reg_write(rn);
}

**Comment by xyzz** [comment]
Unfortunately this results in just `control_reg_write(in_cfg | 2);`, so it's the same as `Creg = rn;
 control_reg_write(Creg);` - there's no assignment in the decompiled code.

**Comment by xyzz** [comment]
I've worked around it similar to what I saw in mips for `mtc0`/`mfc0`:

```
:ldc rn, Creg is op0103=5 & op1215=7 & rn & Creg {
	rn = Creg;
}
:stc rn, Creg is op0103=4 & op1215=7 & rn & Creg {
	write_control_reg(Creg, rn);
}
```

so `stc` doesn't actually store the register.
