### ISSUE TITLE
getProjectRootFolder() from flatAPI does not seem to be working in 9.1

### ISSUE THREAD

**Issue by james-tate** [NationalSecurityAgency/ghidra#1250]
**Describe the bug**
A clear and concise description of the bug.
This does not seem to be working in https://ghidra.re/ghidra_docs/api/ghidra/program/flatapi/FlatProgramAPI.html#getProjectRootFolder()

**To Reproduce**
1. Open Python inside of GUI
2. Execute getProjectRootFolder() inside of Python window

**Expected behavior**
Similar functionality to https://ghidra.re/ghidra_docs/api/ghidra/app/script/GhidraScript.html#askProjectFolder(java.lang.String)

**Screenshots**
>>> getProjectRootFolder()
Traceback (most recent call last):
  File "python", line 1, in <module>
NameError: name 'getProjectRootFolder' is not defined

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: [Linux]
 - Java Version: [12.0]
 - Ghidra Version: [9.1]

**Comment by astrelsky** [comment]
It is accessible from a GhidraScript but not from Python. At first I thought it was because it is a protected method but this does not appear to be the case as both currentProgram and monitor are protected members yet are accessible from python.

**Comment by ryanmkurtz** [comment]
Here is the code that explains the behavior:

https://github.com/NationalSecurityAgency/ghidra/blob/a0aff4fdecf0baba6026d8af2a4a516e4b99ef04/Ghidra/Features/Python/src/main/java/ghidra/python/GhidraPythonInterpreter.java#L322-L359

Only public methods are getting added to the python environment.  I can't think of a good reason why this is being done, since it should mimic the java environment as closely as possibly.

**Comment by astrelsky** [comment]
@ryanmkurtz that is what I had thought. It is strange though because currentProgram is a protected member yet it is accessible.

**Comment by ryanmkurtz** [comment]
Im working on a fix.

**Comment by ryanmkurtz** [comment]
Doh, the obvious/simple fix of just adding protected methods didn't quite work:

```
>>> getProjectRootFolder()
Suppressing exception: exceptions.SystemErrorSystemError: Attempted to make
Java method visible, but it isn't callable[method=getProjectRootFolder, class=class
ghidra.app.script.GhidraScript]
```

I'll have to dig into this more.

**Comment by ryanmkurtz** [comment]
Looks like it's Jython blocking it:

```
    public void addMethod(Method m) {
        // Only add public methods unless we're overriding
        if (!Modifier.isPublic(m.getModifiers()) && Options.respectJavaAccessibility) {
            return;
        }
```
Just have to figure out how to set `Options.respectJavaAccessibility` programmatically.

**Comment by astrelsky** [comment]
> Looks like it's Jython blocking it:
> 
> ```
>     public void addMethod(Method m) {
>         // Only add public methods unless we're overriding
>         if (!Modifier.isPublic(m.getModifiers()) && Options.respectJavaAccessibility) {
>             return;
>         }
> ```
> 
> Just have to figure out how to set `Options.respectJavaAccessibility` programmatically.

It's not programmatically, but try specifying -D python.security.respectJavaAccessibility=false when launching ghidra.

**Comment by ryanmkurtz** [comment]
It seems to be working.  I'll put the fix in.
