### ISSUE TITLE
Dex strings skip every second byte in 9.1

### ISSUE THREAD

**Issue by justfoxing** [NationalSecurityAgency/ghidra#1255]
**Describe the bug**
Dex strings are displayed incorrectly in 9.1, skipping every second byte. 

**To Reproduce**

1. Import a dex file as a single file in 9.1
2. Carry out analysis with default auto-analyzers.
3. Once complete, head over to the strings_data section.
4. Open up any string_data structure.
5. Observe that while the comment and the name of the structure show the correct string, the "data" field skips every second byte.
6. This effect also appears in Defined Strings window, as well as when the structure data is queried directly through the scripting API.

**Expected behavior**
As per 9.0.4, display the full string, with no missing bytes.

**Screenshots**
![strings_bug](https://user-images.githubusercontent.com/18512672/69012085-bc43f900-09c5-11ea-8e3d-a5459db09b90.png)

**Attachments**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 12.0.1
 - Ghidra Version: 9.1

**Additional context**

**Comment by astrelsky** [comment]
Likely related to #1209
