### ISSUE TITLE
Clipboard copy of file entries in project view is not working

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#1257]
#### Describe the bug
When using the **Copy** option in the context menu of any sample in Ghidra's main project window (or the shortcut <kbd>Ctrl</kbd>-<kbd>C</kbd>), the name of the sample is not stored in the clipboard. Instead, the clipboard is emptied.

#### To Reproduce
1. Create a non-shared project
2. Import a sample
3. Select the imported sample in the list, right-click it, and select **Copy**
4. Attempt to paste the name of the sample elsewhere

#### Screenshots
![image](https://user-images.githubusercontent.com/11869704/69016229-d7e6d980-099c-11ea-9bd6-216542b14cc6.png)

#### Environment (please complete the following information)
- OS: Windows 10, Version 1903
- Java Version: 11.0.2
- Ghidra Version: 9.1-PUBLIC

**Comment by dragonmacher** [comment]
I verified this.  

The copy command is working for copying/pasting nodes withing the tree.   We should also put the node name/path on the clipboard as well.
