### ISSUE TITLE
Large program opens a defined strings window will be stuck

### ISSUE THREAD

**Issue by csersoft** [NationalSecurityAgency/ghidra#1259]
**Large program opens a defined strings window will be stuck**
I tried to analyze a 14MB ELF program. After a long wait and analysis, I tried to open the defined strings window. When the progress bar went to about 10%, the program will get stuck.

**To Reproduce**
1. Import the "wlAR-5382u_CTL.o_save" file in the attachment and analyze it.
2. Waiting for analysis to complete.
3. Open the defined strings window.
4. Waiting for get stuck.

**Expected behavior**
Open the defined strings window normally.

**Attachments**
[wlAR-5382u_CTL.zip](https://github.com/NationalSecurityAgency/ghidra/files/3856603/wlAR-5382u_CTL.zip)

**Environment (please complete the following information):**
 - OS: [Windows 10 18.03]
 - Java Version: [11.0.5]
 - Ghidra Version: [9.1]

**Comment by dragonmacher** [comment]
Is the entire GUI locked-up?   If so, then please run tthe `jstack` command from a terminal and provide the output to us.

**Comment by csersoft** [comment]
> Is the entire GUI locked-up? If so, then please run tthe `jstack` command from a terminal and provide the output to us.

[jstack.log](https://github.com/NationalSecurityAgency/ghidra/files/3861371/jstack.log)

**Comment by dragonmacher** [comment]
From the given trace, the tool is not in a deadlock state.  It sounds like the GUI is effectively frozen while the **Defined Strings** window is loading.

If you let it run long enough, will it ever finish loading?

As an alternative, you can use the `Search->For Strings...` feature to find strings based upon  restrictive search criteria.  Not only can you restrict the scope of the results, the table that appears will load incrementally, showing results as they are discovered.  Given the potential number of strings in a binary, the **Defined Strings** widget should probably also load incrementally.

**Comment by csersoft** [comment]
After running for a long time, the loading was completed once.
However, during the loading process, the entire window is in a deadlock state. Unable to close the window.

**Comment by dev747368** [comment]
@csersoft commit 4fbbe98 should fix a majority of the issue that you were seeing.  There still can be some laggy-ness in the UI when the database is being hit hard by the strings table when it is loading / refreshing, but hopefully this change improves the situation enough to make it usable.
