### ISSUE TITLE
Python fails to initialize

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1270]
@ryanmkurtz this is most likely due to 4496e51b0be1b717dc3f218fef84e6914d04ba63

**Attachments**
Here is a fresh log, although it isn't entirely helpful.
[application.log](https://github.com/NationalSecurityAgency/ghidra/files/3872853/application.log)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18362.476]
 - Java Version: 13.0.1
 - Ghidra Version: 9.2 2f0b64a31a78ca6af6c977955b893629e50d89b9

**Additional context**
I traced it back as far as imp.class line 1012 before I decided to call it quits for the night.
Set a breakpoint to break on condition `name.equals("nt")`

**Comment by ryanmkurtz** [comment]
Ok thanks.  What version of Java is Ghidra being run with?

**Comment by astrelsky** [comment]
> Ok thanks. What version of Java is Ghidra being run with?

I'm using JDK 13.0.1

**Comment by ryanmkurtz** [comment]
I think this is an issue of the new Java module system not exporting/exposing certain methods to the Ghidra's module, which is the "unnamed module".

**Comment by ryanmkurtz** [comment]
Ok I'm on 11.  I'll try 13...I bet they changed something.

**Comment by astrelsky** [comment]
Ok. Just for reference,  this would be the first issue I've encountered that could be related to using  jdk 13.0.1. At least with ghidra.

**Comment by ryanmkurtz** [comment]
Are you launching from the Eclipse environment with the Ghidra run configuration we provide?  If so, did you change any of the JVM args?  I am seeing a warning about the illegal reflective access but no exceptions.

**Comment by ryanmkurtz** [comment]
Also, what JDK distribution are you using?  Amazon Corretto? AdoptOpenJDK? Oracle?

**Comment by astrelsky** [comment]
> Are you launching from the Eclipse environment with the Ghidra run configuration we provide? If so, did you change any of the JVM args? I am seeing a warning about the illegal reflective access but no exceptions.

The reflective access warning has been around since the first public release of ghidra. I don't use Eclipse as I spend more time waiting for it to load than I do working.

When I made the fresh log, I launched it directly from the normal ghidra run bat file as a sanity  check to ensure it wasn't my dev environment.

**Comment by ryanmkurtz** [comment]
I can't reproduce it, but I think it's safe to say that the change in 4496e51 is too invasive.  I'll just change that one method in FlatProgramAPI from protected to public.  Jython doesn't seem to provide a way for us to set the access rights of just our script hierarchy methods.

Thanks for finding this before it went out the door!

**Comment by astrelsky** [comment]
> I can't reproduce it, but I think it's safe to say that the change in [4496e51](https://github.com/NationalSecurityAgency/ghidra/commit/4496e51b0be1b717dc3f218fef84e6914d04ba63) is too invasive. I'll just change that one method in FlatProgramAPI from protected to public. Jython doesn't seem to provide a way for us to set the access rights of just our script hierarchy methods.
> 
> Thanks for finding this before it went out the door!

Sounds good and is probably best if the previous solution would grant access to private members/methods of all packages.
