### ISSUE TITLE
Renaming a local variable in the decompiler can result in an "Invalid Storage" message

### ISSUE THREAD

**Issue by snemes** [NationalSecurityAgency/ghidra#1272]
**Describe the bug**
Occasionaly (when the decompiler-generated local variable has a data type with larger storage requirements than the original local variable in the listing pane), renaming a local variable in the decompiler window will behave in a strange way:
- a local variable with the new name will be created and visible in the listing window, but will have an exclamation mark next to it, with the message "Invalid Storage"
- the local variable in the decompiler window will not reflect the new name, and will use an autogenerated variable name instead.

**To Reproduce**
1. Extract the attached `sample.zip` (pw: 'infected'), then import and open the attached `icedid.dll.gzf` file.
2. Go to the function with name `FUN_1000d135`
3. In the decompiler window, rename the `local_60` variable to something else, e.g. `buffer`
4. Note the "Invalid Storage" in the listing window, and the autogenerated variable name in the decompiler window.

**Expected behavior**
If the decompiler-generated local variable is larger than the original, then the storage size should be appropriately set, so there should be no "Invalid Storage" message, and the new name should be reflected in the decompiler pane too (instead of an autogenerated name).

**Screenshots**
![Screenshot from 2019-11-22 13-37-24](https://user-images.githubusercontent.com/6277790/69436382-901bd580-0d41-11ea-9d33-9aea78b4ad94.png)
![Screenshot from 2019-11-22 13-40-53](https://user-images.githubusercontent.com/6277790/69436403-95792000-0d41-11ea-8f97-4d786efe106e.png)

**Attachments**
[sample.zip](https://github.com/NationalSecurityAgency/ghidra/files/3880078/sample.zip) (password: 'infected')

**Environment:**
 - OS: Linux Mint 19.2 Tina
 - Java Version: openjdk 11.0.2
 - Ghidra Version: 9.1

**Additional context**
Renaming the local variable from the listing pane works, and will not cause problems like this.
Could be related to bug #873 too.

**Comment by snemes** [comment]
Based on my investigation, renaming a local variable in the decompiler pane will result in a call to `ghidra.program.model.pcode.HighFunctionDBUtil.updateDBVariable(var, newname, null, ghidra.program.model.symbol.SourceType.USER_DEFINED)`. The 3rd argument to this command is the data type, if it is null, then the variable type should not be changed. So far, so good.

In the corresponding source file, in the updateDBVariable method there is something that looks like a bug:

If the data type is null, then it will automatically fall back to the compiler-inferred data type of the variable (which could be different than the data type shown in the listing pane): https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/HighFunctionDBUtil.java#L457

A few lines below that the `resized` variable is checked to see if the storage requirements have changed:
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/HighFunctionDBUtil.java#L464

However this `resized` variable is set at the beginning of the function, and at that time the fallback to the compiler-generated data type hasn't happened yet (so the data type is still null):
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/HighFunctionDBUtil.java#L419

Due to this, the function will fail to recognize the data type size change, and will not resize the storage with the new requirements.

Potential fix ideas:
A) Add a line that recalculates the `resized` variable whenever the user provided data type is changed within the function. E.g. `resized = (dataType.getLength() != var.getSize());` could be added between lines 462 and 463 (https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/HighFunctionDBUtil.java#L463).

B) A quick and dirty local solution could be applied to https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/main/java/ghidra/app/plugin/core/decompile/actions/RenameVariableTask.java#L58, by explicitly specifing the data type in the call to `updateDBVariable()`:
```
HighFunctionDBUtil.updateDBVariable(var, newName, var.getDataType(), srctype);
```
This would only fix this the specific variable rename issue in the decompiler pane, but keeping the same, slightly flawed logic in HighFunctionDBUtil.java (just in case some other code would rely on that specific bug).

**Comment by xushangning** [comment]
This problem can be easily reproduced with the following code:

```c
#include <stdio.h>

int main(void)
{
    int a[4];
    for (int i = 0; i < 4; ++i)
        printf("%d ", a[i]);
    putchar('\n');

    return 0;
}
```

### Steps to reproduce
1. Analyze [the attached binary](https://github.com/NationalSecurityAgency/ghidra/files/3883387/a.out.zip) with code browser.
1. Rename the variable in the compiled code corresponding to the array `a` in the source above (`local_38` -> `a` in my case).
1. The "Invalid storage" error should appear in the assembly listing.

By the way, if `local_38` is retyped before rename, then there will be no error.

### Environment

- Arch Linux
- OpenJDK 11.0.5.u10
- Ghidra 9.1

**Comment by snemes** [comment]
This seems to have been fixed by commit https://github.com/NationalSecurityAgency/ghidra/commit/5f9b93c064b1338bab15336d384eb5f0fe835a8e

**Comment by xushangning** [comment]
> This seems to have been fixed by commit [5f9b93c](https://github.com/NationalSecurityAgency/ghidra/commit/5f9b93c064b1338bab15336d384eb5f0fe835a8e)

Thanks for pointing out! I compiled the master just now and this error didn't show up in my case. I should have tested the development version though...

**Comment by ryanmkurtz** [comment]
Can we go ahead and close this?

**Comment by snemes** [comment]
Sure, closing.
