### ISSUE TITLE
Null pointer in Listing window

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#1273]
Please, don't highlight variables `pointer`, `int*`, `byte*`, etc with value = 0 like erroneous.

Currently this pointers highlighted with red:
![image](https://user-images.githubusercontent.com/12969211/69439961-ffe98a80-0d58-11ea-9d98-31bc6fe55e6d.png)

**Comment by dev747368** [comment]
The red highlight just indicates that the destination of the pointer is not a valid memory location.

If you were to create a memory block at ram:0, this addr pointer would no longer be red.
