### ISSUE TITLE
Opening as 'Raw Binary' and 'PE' yield different results with the same language

### ISSUE THREAD

**Issue by NotStirred** [NationalSecurityAgency/ghidra#1274]
![delete me](https://user-images.githubusercontent.com/16853282/69474628-538cc000-0dbb-11ea-927a-9fd18d651280.png)

Is this intended, or am I misunderstanding how this should work?

Attatching a debugger to the running .exe I was examining shows that the 'PE' version of the binary is the 'correct' one, I can directly use the addresses found in the debugger to look in my ghidra project. But the 'Raw Binary' one doesnt.

**Comment by ryanmkurtz** [comment]
The PE loader will load the binary into Ghidra in a way that mimics how the real Windows loader would load it into memory at runtime.  The Raw Binary loader is simply laying down the entire file as it appears on disk.  If you look at the Memory Map in the two different loaded versions, you will see how the layout differs.  Everything you are seeing is the intended behavior.
