### ISSUE TITLE
Enable build (for master/PRs)?

### ISSUE THREAD

**Issue by gliptak** [NationalSecurityAgency/ghidra#1283]
Would there be an interest adding a (Github Actions based) build for master/PRs? If so, I can contribute an initial version.

https://github.com/NationalSecurityAgency/ghidra/issues/1199
https://github.com/NationalSecurityAgency/ghidra/issues/1019

**Comment by snemes** [comment]
I have a fork where I'm already using this, and this workflow config seems to work nicely: https://github.com/snemes/ghidra/blob/snemes-patch-1/.github/workflows/gradle.yml

So this is a great idea in general!

**Comment by ryanmkurtz** [comment]
We use something else for CICD, so I'm going to go ahead and close this.  We might have an interest in GitHub Actions at some point in the future, but the implementation will likely come the dev team.
