### ISSUE TITLE
Javadoc JDK 13 Compatibility (HTML5)

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1284]
This is merely for documentation purposes.

The option --no-module-directories has been removed from javadoc. [info](https://bugs.openjdk.java.net/browse/JDK-8215582)
There are also numerous errors due to bad usage of > and <.

I will edit this with more information later today.

**Comment by ryanmkurtz** [comment]
I'm going to consider this an enhancement since we officially support JDK 11 LTS.  I'll look into it though.

**Comment by astrelsky** [comment]
> I'm going to consider this an enhancement since we officially support JDK 11 LTS. I'll look into it though.

I just figured it best to open the issue and document it. Would there be any issues with changing html to html5? ie changing name attributes to id and such?

I'm currently going through and fixing minor mistake with angle brackets and wrong links.

**Comment by ryanmkurtz** [comment]
Yes we definitely appreciate the issue being reported.   `--no-module-directories` was put in to address #129.  If there is a better solution out there we'll put it in!

**Comment by astrelsky** [comment]
> Yes we definitely appreciate the issue being reported. `--no-module-directories` was put in to address #129. If there is a better solution out there we'll put it in!

I'll look into another solution after class this afternoon.  I have most of the html errors and outdated links out of the way already.

**Comment by astrelsky** [comment]
> Yes we definitely appreciate the issue being reported. `--no-module-directories` was put in to address #129. If there is a better solution out there we'll put it in!

According to the [openjdk bug report](https://bugs.openjdk.java.net/browse/JDK-8205593) this was fixed in JDK 12. Since JDK 11 LTS is being targeted I've simply added a check in distribution.gradle to apply the option only if it is Java11.

I'll submit a pr along with a bunch of fixes for javadoc errors.

**Comment by astrelsky** [comment]
It appears the -notimestamp is occuring in thecreateJsondocs task. I'll try seeing if adding a dummy option to JsonDoclet prevents the error.
