### ISSUE TITLE
Does ghidra run in parallel?

### ISSUE THREAD

**Issue by Ruturaj4** [NationalSecurityAgency/ghidra#1285]
I have created following script to run ghidra in parallel:

```
def worker(filename):
    # Run ghidra script
    os.system(f"/projects/ruturaj/ghidra_9.0.3-DEV/support/analyzeHeadless /projects/ruturaj/ghidra_learning/ TEST2 -import {filename} -postscript /projects/ruturaj/ghidra_9.0.3-DEV/support/test3.py -deleteproject")

def main():
    pwd = os.getcwd()
    # pool of processes
    with concurrent.futures.ProcessPoolExecutor() as executor:
        # sorting here destroyes generator advantage of os.walk
        # but I don't want that feature too badly in this case anyways
        walk = sorted(os.walk(pwd))
        fn_gen = itertools.chain.from_iterable((os.path.join(root, file) for file in files) for root, dirs, files in walk)
        executor.map(worker, fn_gen)
```

`ERROR Abort due to Headless analyzer error: ghidra.framework.store.LockException: Unable to lock project! /projects//ruturaj/ghidra_learning/TEST2 (HeadlessAnalyzer) java.io.IOException: ghidra.framework.store.LockException: Unable to lock project! /projects/ruturaj/ghidra_learning/TEST2
`

I believe that this happens when I try to run scripts in parallel - and script runs fine the first time (i.e. only on first file) - I get errors like above for the rest.

Is it possible at all to run ghidra in parallel?

**Comment by dev747368** [comment]
It is possible, but the project you are importing into needs to be a shared project hosted on a ghidra server.

**Comment by Ruturaj4** [comment]
Can you provide some hints/ posts? I know how the shared project works, but using ghidra GUI

**Comment by dev747368** [comment]
First, fire up a ghidra server.  In your <ghidra_install_dir/server>, run ghidraSvr.  There are docs and readme files that explain running the server.

In the client, create a project, choose "shared", and enter the server details, which could be localhost if you are running on the same machine, and follow the prompts.

For your headless analyzer, when you specify the project, it will be in the format: "ghidra://server_name/shared_project_name".
