### ISSUE TITLE
docs search.js bug leads to search result redirecting to wrong address

### ISSUE THREAD

**Issue by kasif-dekel** [NationalSecurityAgency/ghidra#129]
**Describe the bug**
When using the search box in the GHIDRA docs (GHIDRAapi_javcadoc) and click on some result line, navigation is redirected to a wrong address resulting in 404.

**To Reproduce**
1. Navigate to GHIDRAapi_javcadoc\api\index.html
2. Search for something in the search input field
3. Click some result line

**Suggested Fix**

in **GHIDRAapi_javadoc\api\search.js**, change the line at 53 from: 

`if (ui.item.p == item.l) {`

to: 

`if (ui.item.p == item.l && item.m != undefined) {`

**Comment by ryanmkurtz** [comment]
@ryanmkurtz , here's a reference to [possible fix](https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url).

**Comment by kasif-dekel** [comment]
One way or the other, whether or not you're using 
`<additionalJOption>--no-module-directories</additionalJOption>`

you need to add the check I suggested to the **search.js** file so it'll work in both cases.

**Comment by ryanmkurtz** [comment]
This will be fixed for our next release.
