### ISSUE TITLE
Bookmark with different categories overwrite each other

### ISSUE THREAD

**Issue by MabryTyson** [NationalSecurityAgency/ghidra#1291]
**Describe the bug**
A second NOTE bookmark at the same address overwrites an earlier NOTE bookmark at that address that had a different category.

**To Reproduce**
1. Run Ghidra 9.1
2. Run a script with this body:
```
   	Address addr = currentAddress;
    	Bookmark b1 = createBookmark(addr, "Category 1", "comment 1");
    	printf("Bookmark b1: ID: %d; category: %s; comment: %s\n", b1.getId(), b1.getCategory(), b1.getComment());
    	Bookmark b2 = createBookmark(addr, "Category 2", "comment 2");
    	printf("Bookmark b2: ID: %d; category: %s; comment: %s\n", b2.getId(), b2.getCategory(), b2.getComment());
    	printf("Bookmark b1: ID: %d; category: %s; comment: %s\n", b1.getId(), b1.getCategory(), b1.getComment());
```
3. See the output:
```
Bookmark b1: ID: 281474976747085; category: Category 1; comment: comment 1
Bookmark b2: ID: 281474976747085; category: Category 2; comment: comment 2
Bookmark b1: ID: 281474976747085; category: Category 2; comment: comment 2
```
**Expected behavior**
The third line of output should have been the same as the first.  Bookmark b2 should have been a different bookmark and not overwritten b1.
 
The [documentation](https://ghidra.re/ghidra_docs/api/ghidra/program/flatapi/FlatProgramAPI.html#createBookmark(ghidra.program.model.address.Address,java.lang.String,java.lang.String)) for createBookmark indicates
> if a NOTE book mark already exists at the address with same category, it will be replaced.

This implies that if two NOTE bookmarks are created with different categories at the same address, both can exist.

Note that the documentation of getBookmarks also implies that multiple NOTE bookmarks can exist at the same address.
> Returns all of the NOTE book marks defined at the specified address.

**Screenshots**
None

**Attachments**
None

**Environment:**
 - OS:  macOS 10.14.6
 - Java Version: 12
 - Ghidra Version: 9.1

**Additional context**
I wish to create multiple bookmarks at a single address.  In my case, the address is the call to a function, and the bookmarks are related to separable information extracted from a string argument to that function.  Per the API documentation, I'll have to use a different category for each bookmark at the address.

**Comment by dragonmacher** [comment]
The code inside of `createBookmark()` is quite deliberate.  Specifically, it contains this:
```
Bookmark[] existingBookmarks = getBookmarks(address);
if (existingBookmarks != null && existingBookmarks.length > 0) {
	existingBookmarks[0].set(category, note);
	return existingBookmarks[0];
}
```

Looking though historical data, we can see that the issue is the GUI will allow only one Note bookmark at a given address, **regardless of the category**.   It is not clear why the GUI enforces this restriction.  The documentation for this method is  incorrect.

You can bypass this code by adding bookmarks yourself:
```
BookmarkManager bkm = currentProgram.getBookmarkManager();
bkm.setBookmark(address, BookmarkType.NOTE, category, note);
```

If you do this, then you can add multiple notes, each with a different category.  However, if you edit the notes from the GUI, you may lose bookmarks.  Also, you could use a different type than NOTE.
