### ISSUE TITLE
Editing the type of a bitfield in a struct doesn't cause the 'Save' button to enable

### ISSUE THREAD

**Issue by sf2platinum** [NationalSecurityAgency/ghidra#1297]
**Describe the bug**
When changing a bitfield's type within a struct, the 'Save' button doesn't enable, and the struct dialog will not prompt to save changes when closing, leading to loss of work. It's necessary to make some other change to enable to save button.

**To Reproduce**
1. Open a struct containing a bitfield
2. Edit the bitfield, and change its type

**Expected behavior**
The 'Save' button should enable, and the struct dialog should prompt to save changes when closed.

**Environment (please complete the following information):**
 - macOS 10.14.5
 - Java Version: openjdk 11.0.5 2019-10-15
 - Ghidra Version: 9.1

**Comment by ghidra1** [comment]
Fixed for 9.1.2
