### ISSUE TITLE
Don't remove class part from method names

### ISSUE THREAD

**Issue by Piruzzolo** [NationalSecurityAgency/ghidra#1298]
Ghidra sistematically deletes the class part `Foo` of C++ names `Foo::bar()`,
This is very confusing when reversing binaries; it also adds significant amount of work
to figure out if the function is a method of which class.

Function signatures should keep this part of the name, if Ghidra detects they are C++ methods - good heuristics: PDB infos, thiscall convention, etc.

Even and much better, Ghidra could rewrite methods calls the C++ way, as described in #992 

Please consider this problem, thanks

**Comment by dragonmacher** [comment]
I assume you are referring to the function signature in the Listing.   There is a tool option to have the function display its namespace at `Edit -> Tool Options -> Listing Fields -> Function Signature Field`.
For functions that live in classes, the Listing will display the function signature with the class name.

**Comment by Piruzzolo** [comment]
It works, thanks! Didn't notice that option
