### ISSUE TITLE
Extending from HeadlessScript in Python

### ISSUE THREAD

**Issue by daqo** [NationalSecurityAgency/ghidra#1306]
I'm interested in calculating Analysis Time in Ghidra. I was going to log the start_time at the end of my preprocessor script (storing it temporarily using the `storeHeadlessValue` method). Later, I was going to get the current time at the beginning of my postprocessor function and do a simple `endTime - beginningTime`.

A couple of questions:
1. Is there a better way to get the analysis time?
2. Is there a way to inherit from HeadlessScript in python? My understanding is that I need to extend from that to be able to use `storeHeadlessValue`.

**Comment by astrelsky** [comment]
Technically you can inherit any java class in jython as long as it's visible, but I'm not sure this would be helpful.

Analysis time is calculated and logged automatically even in headless mode. If you wish to fetch that information you may retrieve it a formatted string by the following:
```
AutoAnalysisManager mgr = AutoAnalysisManager.getAnalysisManager(currentProgram);
String result = AutoAnalysisManager.getTaskTimesString();
```
of course making modifications as necessary for python.

The AutoAnalysisManager class is not documented but it is public and located in the package ghidra.app.plugin.core.analysis

**Comment by daqo** [comment]
Thank you for your quick response. Closing the ticket.
