### ISSUE TITLE
Sleigh: Motorola 6805: typo in BSET instruction

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#1307]
**Describe the bug**
`BSET` instruction looks like erroneous copy of `BCLR` one.

https://github.com/NationalSecurityAgency/ghidra/blob/7e4dd35859e40233cd1b71248e0da411f0ac0812/Ghidra/Processors/6805/data/languages/6805.slaspec#L243

https://github.com/NationalSecurityAgency/ghidra/blob/7e4dd35859e40233cd1b71248e0da411f0ac0812/Ghidra/Processors/6805/data/languages/6805.slaspec#L150

Please fix it with
```
:BSET n,DIRECT	is op4_7=1 & bit_0=0 & n; DIRECT {
	local mask = (1 << n);
	DIRECT = DIRECT | mask;
}
```

**Comment by esaulenka** [comment]
Update. 
`CPX` instruction is not correct too.
Carry flag should be computed relatively `X` register, not `A`.

https://github.com/NationalSecurityAgency/ghidra/blob/7e4dd35859e40233cd1b71248e0da411f0ac0812/Ghidra/Processors/6805/data/languages/6805.slaspec#L319

**Comment by esaulenka** [comment]
Also `SWI` instruction looks suspicious.

At 0x3FF0 .. 0x3FFF located addresses of interrupt handlers, not code. Consequently, `SWI` should read word at 0x3FFC (SWI_VECTOR) and only after that execute goto to readed value.

https://github.com/NationalSecurityAgency/ghidra/blob/7e4dd35859e40233cd1b71248e0da411f0ac0812/Ghidra/Processors/6805/data/languages/6805.slaspec#L630

**Comment by GhidorahRex** [comment]
Looks good. I'll include those fixes in the issue
