### ISSUE TITLE
GnuDemangler format selecting

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1308]
**Is your feature request related to a problem? Please describe.**
While the `--format` and `-s` options are available in the native demangler_gnu binary there is currently no way to select these options when running the demangler in ghidra. Unfortunately the auto format detection isn't perfect and there are times where I would like to use the hp, gnu, or gnu-v3 options.

**Describe the solution you'd like**
The ability to select the format option to use prior to demangling a symbol. In order to achieve this modifications to the main function in cplus-dem.c must be made to check for the option to use a specified demangling format for the next input.

**Describe alternatives you've considered**
Make an entire copy of GnuDemanglerNativeProcess where the format option is specified and another DemanglerAnalyzer which uses a modified GnuDemangler with a hackjob usage of GnuDemanglerParser to parse the demangled output. It really isn't pretty but can be done. This also results in having an additional process running for each different format you wish to use.

**Additional context**
Enabling this feature would also allow more mangling formats to be added to the demangler_gnu such as the dlang and rust mangling formats available in GNU c++filt 2.33.1
@Piruzzolo gave a similar suggestion in #648 
Which is especially necessary with binaries comprised of objects from different compilers as in the above issue.

**Comment by dragonmacher** [comment]
Are you requesting an API-level update?  And/or would you like this to be a setting that you can tweak from the UI (such as an option or analyzer setting)?

**Comment by astrelsky** [comment]
> Are you requesting an API-level update? And/or would you like this to be a setting that you can tweak from the UI (such as an option or analyzer setting)?

I think both. I think a simple dropdown box that contains each of the available format selections in the UI of the demangler analyzer and a processor spec property to change the default value would suffice.

C++filt doesn't allow the changing of the current mangling format on the fly. Either the process would need to be restarted with the new format or a way to change it in the current process would need to be added.
