### ISSUE TITLE
Fail to build latest version since Gradle Could not determine GCC metadata

### ISSUE THREAD

**Issue by EmpRamses** [NationalSecurityAgency/ghidra#1316]
**Describe the bug**
Task :Decompiler:compileDecompileLinux64ExecutableDecompileCpp FAILED

* What went wrong:
Execution failed for task ':Decompiler:compileDecompileLinux64ExecutableDecompileCpp'.
> No tool chain is available to build for platform 'linux64':
    - Tool chain 'visualCpp' (Visual Studio):
        - Visual Studio is not available on this operating system.
    - Tool chain 'gcc' (GNU GCC):
        - Could not determine GCC metadata: could not find vendor in output of /usr/bin/gcc.   
    - Tool chain 'clang' (Clang):
        - Could not find C compiler 'clang' in system path.

**To Reproduce**
1. Use automatic script instruction to setup dependencies
2. Build on CentOS 7 with instruction "gradle buildNatives_linux64"
3. Error occur

**Expected behavior**
According to the instructions, the Ghidra should be build successfully

**Environment (please complete the following information):**
 - OS: CentOS 7.2
 - Compile: GCC 4.8.5, g++ 4.8.5
 - Java Version: 12.0.2
 - Ghidra Version: 9.2

**Additional context**
I install gcc with yum. However, it may indicate that my gcc has some problem that not match its needs. I think it may caused by gradle. But I have no idea what's wrong in gradle or your codes.

**Comment by ryanmkurtz** [comment]
What version of Gradle are you using?

**Comment by ryanmkurtz** [comment]
I found this on the Gradle site:

> Note that if you are using GCC then you currently need to install support for C++, even if you are not building from C++ source. This restriction will be removed in a future Gradle version.

**Comment by EmpRamses** [comment]
@ryanmkurtz emm... the master branch

**Comment by ryanmkurtz** [comment]
> @ryanmkurtz emm... the master branch

Gradle, not Ghidra.

**Comment by EmpRamses** [comment]
@ryanmkurtz 6.0.1 The latest version. Maybe I should use a legacy version? I didn’t find an instruction which gradle works well.

**Comment by ryanmkurtz** [comment]
I have tried the latest gradle and it works, but I'm on Windows.  Did you try installing g++?

**Comment by EmpRamses** [comment]
> I found this on the Gradle site:
> 
> > Note that if you are using GCC then you currently need to install support for C++, even if you are not building from C++ source. This restriction will be removed in a future Gradle version.

I’ve also notice that. But my GCC does support for C++. So that made me confused.🤔

**Comment by EmpRamses** [comment]
> I have tried the latest gradle and it works, but I'm on Windows. Did you try installing g++?

You mean that I should reinstall g++ separately? I’ll try it later after my getting up.😴

**Comment by astrelsky** [comment]
> > I have tried the latest gradle and it works, but I'm on Windows. Did you try installing g++?
> 
> You mean that I should reinstall g++ separately? I’ll try it later after my getting up.😴

What is the output of gcc -v?
I ask because I found this information [here](https://stackoverflow.com/questions/55653649/gradle-cpp-application-not-detecting-gcc-in-windows) and am wondering if the gcc target isn't what gradle is expecting. A cause would be if gcc was unexpectedly targeting a 32-bit system or if gcc doesn't exactly target your system's architecture.

**Comment by EmpRamses** [comment]
> > > I have tried the latest gradle and it works, but I'm on Windows. Did you try installing g++?
> > 
> > 
> > You mean that I should reinstall g++ separately? I’ll try it later after my getting up.😴
> 
> What is the output of gcc -v?
> I ask because I found this information [here](https://stackoverflow.com/questions/55653649/gradle-cpp-application-not-detecting-gcc-in-windows) and am wondering if the gcc target isn't what gradle is expecting. A cause would be if gcc was unexpectedly targeting a 32-bit system or if gcc doesn't exactly target your system's architecture.

@astrelsky The target of my gcc is "x86_64-redhat-linux". This gcc was installed with my CentOS 7 system. I've never changed it. Following info is the output.

> 使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by ryanmkurtz** [comment]
[Here is the code](https://github.com/gradle/gradle/blob/4b850efa1544ad0e14ac45d56059ec3a3d7f4a90/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/metadata/GccMetadataProvider.java#L78-L112) that is throwing the error:

What is your output of `gcc -dM -E -v -`

**Comment by EmpRamses** [comment]
> [Here is the code](https://github.com/gradle/gradle/blob/4b850efa1544ad0e14ac45d56059ec3a3d7f4a90/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/metadata/GccMetadataProvider.java#L78-L112) that is throwing the error:
> 
> What is your output of `gcc -dM -E -v -`

> 使用内建 specs。
COLLECT_GCC=gcc
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
COLLECT_GCC_OPTIONS='-dM' '-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/cc1 -E -quiet -v - -mtune=generic -march=x86-64 -dM
忽略不存在的目录“/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include-fixed”
忽略不存在的目录“/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/include”
#include "..." 搜索从这里开始：
#include <...> 搜索从这里开始：
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include
 /usr/local/include
 /usr/include
搜索列表结束。

I have wait for a while. It seems just stop here. Some directories like “/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include-fixed” are ignored since they are not disappeared. And it just find 3 directories.

**Comment by ryanmkurtz** [comment]
Gradle may not be able to handle parsing the non-ascii character set.

**Comment by ryanmkurtz** [comment]
They are looking for the word "version" but your output has "版本" instead.

**Comment by EmpRamses** [comment]
> They are looking for the word "version" but your output has "版本" instead.

You are right! Our IT just change the system language for me. And it worked. Thanks a lot!
