### ISSUE TITLE
M68000: roxr.l decompiles as uint5

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#1319]
For now decompiler outputs these strings as the result of decompiling.

Source:
```
    move.l    -(endcrun),D5
    roxr.l    #0x1,D5
```
Result:
```
    puVar10 = puVar10 + -1;
    uVar4 = CONCAT14(bit,*puVar10);
    bit = (*puVar10 & 1) != 0;
    token = (uint)(uVar4 >> 1);
```

where `uVar4` has type `uint5`. This type is impossible, because the max type is 32-bit, not 48.

**Comment by lab313ru** [comment]
xorx uses XF `bit`, but not `byte` to join.

**Comment by itismrsuits** [comment]
https://maxkersten.nl/binary-analysis-course/malware-analysis/corona-ddos-bot/

https://en.m.wikipedia.org/wiki/Coronavirus

https://www.spiegel.de/wissenschaft/medizin/coronavirus-zahl-der-todesopfer-in-
china-steigt-auf-25-a-7090f634-0c7c-417e-9394-3f08c88674bf


Am Donnerstag, 23. Januar 2020 schrieb GhidorahRex <notifications@github.com
