### ISSUE TITLE
Fails to disassemble MIPS32 LE jr instructions

### ISSUE THREAD

**Issue by 0xf15h** [NationalSecurityAgency/ghidra#132]
**Bug Description**
I've noticed that Ghidra is having issues disassembling MIPS32 little-endian jr instructions. I've tried disassembling the code sections in Disassembled View by pressing the d key, right-click + Disassemble, right-click + Disassemble (Restricted), right-click + Disassemble (Static), right-click + Disassemble - MIPS, and right-click + Disassemble - MicroMips with no success.

**To Reproduce**
Try to disassemble:
0800e003 - jr $ra
08002003 - jr $t9

**Expected behavior**
Disassemble 0800e003 to `jr $ra` and 08002003 to `jr $t9`.

**Environment:**
 - OS: Ubuntu 18.04.2 LTS
 - Java Version: 11.0.2
 - Ghidra Version: 9.0

**Additional notes**
This is a high impact bug because it frequently breaks the Function Graph's control flow and results in the decompiler producing functions consisting of only `halt_baddata();`.

**Comment by emteere** [comment]
Putting a branch instruction in the delay slot is unpredictable behavior.  There is code in the mips processor spec to not decode a branch in the delay slot.  In the R6 spec it will be an invalid instruction exception.

I suppose if you set both ra and t9 to the same address you would get predictable behavior and end up at the correct address.

The processor could be changed to allow the instruction patterns were it to be encountered with a warning of unpredictable results, and an arbitrary branch to the first jump address.  Is that the behavior your binary is exhibiting?

**Comment by emteere** [comment]
There is code in sleigh parsing to invalidate instructions with a delayslot already in a delay slot.

The change would need to be added to nullify the delay slot branch if the instruction is already in a delay slot.

**Comment by 0xf15h** [comment]
The `jr $ra` and `jr $9` instructions are two separate examples of Ghidra failing to disassemble jr instructions. The disassembly failures were found in different functions. I apologize for the miscommunication and would like to clear it up with an example.

This is from a .plt entry that calls pthread_create by loading the value at the pthread_create .got address into t9 and jumping to it at 0x4043cc.
```
...
004043c0 41 00 0f 3c     aui        t7,zero,0x410000
004043c4 e0 36 f9 8d     lw         t9,offset ->pthread_create(t7)
004043c8 e0 36 f8 25     addiu      t8,t7,0x12e0
004043cc 08              ??         08h
004043cd 00              ??         00h
004043ce 20              ??         20h     
004043cf 03              ??         03h
004043d0 41 00 0f 3c     aui        t7,zero,0x410000
...
```
Ghidra fails to disassemble `jr $t9` at 0x4043cc. Note that `jr $ra` is not at address 0x4043d0.

**Comment by mumbel** [comment]
"aui" implies it thinks REL6=1, but since your "jr" has 8 as (0,5) instead of 9 the sleigh fails

**Comment by fuzzywalls** [comment]
I am having the same issue with MIPS LE and wondered if there had been update on this since March? I attached a screenshot to show the error. The op-codes should disassemble to `jr ra`. 

![Screen Shot 2019-12-20 at 10 20 19 AM](https://user-images.githubusercontent.com/39141855/71264598-6e971500-2312-11ea-86f0-d7b44541278b.png)

**Comment by GhidorahRex** [comment]
@mumbel is correct. The "aui" instruction implies that REL6=1, however the "jr" instruction is being encoded with a function code of 0x8. I suspect if you load the binary with MIPS:LE:32:default instead of MIPS:LE:32:R6 you will see better results. In this case, the "aui" instructions decode to "lui", which looks correct.
@fuzzywalls - which processor variant are you working with in this binary?

**Comment by fuzzywalls** [comment]
@GhidorahRex When I loaded the binary Ghidra defaulted to using MIPS:LE:64:64-32R6addr:default, which seems to not be the correct language. Once I changed the language to not include the R6 it decompiled properly. A `file` of the binary I am looking at indicates it was compiled with MIPS version 1 so maybe there is a problem with identification. Much like @0xf15h I saw "aui" instructions so maybe their binary was incorrectly identified as well.

**Comment by wrongbaud** [comment]
> @GhidorahRex When I loaded the binary Ghidra defaulted to using MIPS:LE:64:64-32R6addr:default, which seems to not be the correct language. Once I changed the language to not include the R6 it decompiled properly. A `file` of the binary I am looking at indicates it was compiled with MIPS version 1 so maybe there is a problem with identification. Much like @0xf15h I saw "aui" instructions so maybe their binary was incorrectly identified as well.

I had the same problem with this and stumbled upon this issue. The issue for me was that the binary was not being identified correctly, applying your described fix solved this issue.

**Comment by GhidorahRex** [comment]
Closed since I believe this has been suitably addressed.
