### ISSUE TITLE
how to manage ghidra settings when moving to new version

### ISSUE THREAD

**Issue by dummys** [NationalSecurityAgency/ghidra#1328]
Hi,

Do you plan or is there a way to manage this ? for example, when we upgrade the version, the settings are auto copied or something like this.

**Comment by ryanmkurtz** [comment]
When you install and launch a new version of Ghidra, it should use the settings from your previous version (stored in the `~/.ghidra` directory).  However, a breaking change was made in 9.1 that made it impossible to find the previous installation.  It should work for future versions of Ghidra though.  To test it, you can go into the `Ghidra/application.properties` file of your 9.1 installation, increment the `application.version` property, and the settings should carry over on the next launch.  The first entries of the application log should indicate what settings it's using.
