### ISSUE TITLE
Low-level Error: XML error: syntax error caused by bad enum name

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#1329]
A function being decompiled references a DataType which contains an Enum where one of the enum names contains the '<' character causes the decompilation to be unparsable.

A tool that built enums from strings created "bad" enum labels, which eventually caused many functions to be no longer decompilable.  This seems to be like an "SQL injection" problem where various data is not protected from the XML parser that parses the decompiler output.  I suspect that there are more places where names may contain unexpected characters that may cause parsing failure.  Restricting the identifier to valid "C" symbols may be a solution (although that is very "C"-centric).  Probably just restricting '<' and '>' may be good enough, but doesn't seem the "proper" solution.

**Comment by ryanmkurtz** [comment]
Fixed by 2d1bd78759aa79d5c07a14a701d0e61f52cc9794
