### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by stonedreamforest** [NationalSecurityAgency/ghidra#133]
Just need to analyze it:

![111111](https://user-images.githubusercontent.com/16742566/54072688-3e1d4780-42b9-11e9-8530-ae01350bb506.png)
111111.png -> 111111.rar
pwd:123

-----

![ODrKJoWopx](https://user-images.githubusercontent.com/16742566/54072758-5f326800-42ba-11e9-99af-b7f47177a8d0.gif)

---------

![image](https://user-images.githubusercontent.com/16742566/54072700-69079b80-42b9-11e9-856d-33958eb24d3a.png)

---

![image](https://user-images.githubusercontent.com/16742566/54073096-22687000-42be-11e9-8a51-ec3e1d39ba1e.png)

**Comment by ghidra1** [comment]
Could you please provide a stack trace

**Comment by stonedreamforest** [comment]
@ghidra1 
[gif: https://vgy.me/delete/Vacahn5JzK6E](https://vgy.me/delete/Vacahn5JzK6E)

-------------
download file:
https://user-images.githubusercontent.com/16742566/54072688-3e1d4780-42b9-11e9-8530-ae01350bb506.png

pwd: 123

**Comment by ghidra1** [comment]
We prefer you comment with stack trace text instead of providing URL link.
