### ISSUE TITLE
MIPS: Overlayed code

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#1332]
Is it possible to use overlayed memory blocks in GHIDRA?

This is example of such blocks usage:

> The PSYQ development kit offered a uniqu feature called Overlays which allowed developers to switch out parts of the executable at run time, meaning they could load different executable code into memory at different times. This allowed better use of memory as developers were not limited to just the space of RAM.

So, during disassembly, it looks like at the same address can be more than one different code, or data. So, labels will overlap, bytes will be different, etc. Usually this code placed in RAM, and has RWX restrictions. Is there such functionality in Ghidra? If no, can it be implemented?

**Comment by astrelsky** [comment]
Yes. See [Memory.createInitializedBlock(String, Address, long, byte, TaskMonitor, boolean)](https://ghidra.re/ghidra_docs/api/ghidra/program/model/mem/Memory.html#createInitializedBlock(java.lang.String,ghidra.program.model.address.Address,long,byte,ghidra.util.task.TaskMonitor,boolean))

**Comment by lab313ru** [comment]
And how to specify at which block a function must be created? Is that be a different address space, right?

**Comment by astrelsky** [comment]
> And how to specify at which block a function must be created? Is that be a different address space, right?

Yes, the created overlay MemoryBlock will have an AddressSpace other than default. In order to create functions or data within the overlay you would need to ensure that the address used when creating the CodeUnit has the same AddressSpace as the overlay memory block. Here is some pseudo-code:

```
MemoryBlock block = currentProgram.getMemory().create("dummyOverlay",start, dummySize, (byte) 0, monitor, true);
AddressSpace overlaySpace = block.getStart().getAddressSpace();
Address functionAddress = overlaySpace.getAddress(functionOffset);
createFunction(functionAddress, null);
```

**Comment by lab313ru** [comment]
And how the decompiler works with that? Which address space does it use?

**Comment by lab313ru** [comment]
I mean, for example, some instruction can point to more than one block. How does the decompiler select which one to use?

**Comment by astrelsky** [comment]
> I mean, for example, some instruction can point to more than one block. How does the decompiler select which one to use?

I see. It depends on how the instruction is defined in sleigh. As an example:
```
define space dummy type=ram_space size=4;
*:3 &var = imm24; -> Default address space (usually ram)
*[ram]:3 &var = imm24; -> Ram address space
*[register]:3 &var = imm24; -> Register address space
*[dummy]:3 &var = imm24; -> Dummy address space
```

I'm not entirely sure which AddressSpace is used in an overlay so you'd need to check.

**Comment by lab313ru** [comment]
Example in PSX: you can define many overlays at the same name and the same address. Mips doesn't have any "address space" pointing instructions. But you can specify which overlay will be used at current moment (it's a compiler feature). So, I want to understand how the decompiler will manage that. Will it use Primary reference info?

**Comment by astrelsky** [comment]
> Example in PSX: you can define many overlays at the same name and the same address. Mips doesn't have any "address space" pointing instructions. But you can specify which overlay will be used at current moment (it's a compiler feature). So, I want to understand how the decompiler will manage that. Will it use Primary reference info?

I'm not sure. The best way to find out would be to define an overlay memory block, copy existing code from one block, put the bytes in the overlay block and then disassemble and see what happens.

**Comment by lab313ru** [comment]
Yes, it requires manual Reference switching. But it works! Thanks.
