### ISSUE TITLE
How can I output analyzed code

### ISSUE THREAD

**Issue by EmpRamses** [NationalSecurityAgency/ghidra#1334]
I would like to use the analysis results of Ghidra to do some further analysis with python.
But I don't know how to transfer assembly code or decompiled code to a python script.
Or output these code to files that can be read by python.

**Comment by ryanmkurtz** [comment]
If you do `File --> Export Program` you'll see a variety of choices.

**Comment by EmpRamses** [comment]
But it need user to click those buttons. I'd like to use the headless analyzer, so that a python script would get these exported programs automatically. Besides, I failed to notice any instructions about exporting programs in the analyzeHeadlessREADME.html

**Comment by ryanmkurtz** [comment]
Ahh.  You can call the same exporters from a script.  For example, if you wanted to export as ascii (in java):

```
Exporter exporter = new AsciiExporter();
exporter.export(file, currentProgram, null, monitor);
```
Take a look at the [Exporter](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/util/exporter/Exporter.java) class hierarchy to see what other exporters are available.  You could also study the code of one of the exporters to see how they work if you want to do something more customized.  They'll typically do something like this

`CodeUnitIterator cuIterator = listing.getCodeUnits(addressSet, true);`

and then iterator over the code units, extracting what they needs and converting it however they want.

**Comment by DarrylC03** [comment]
@EmpRamses I do the same just want the raw assembler like IDA does using the command line. Exporting it as an ascii file will create a pseudo asm file with lots of extra fluff but coding in python (I use perl) will be easily processed. 

Let us know how you get on as I have reverted back to IDA in the interim as it does a significantly  better job of finding the asm in the binary analysis (another post). Just for 1 vehicle I have over 160 different operating systems so using a GUI is not productive and I have not found the script to find the next undecoded instruction and get it encoded ( cntrl-alt-U and D).

**Comment by EmpRamses** [comment]
@ryanmkurtz The Iterator is so excellent. It works much better than write and read a file. But Jypthon only support python2. I think I have to figure out how to transfer the iterator to a python3 script.
Plus, I still need to export a pure assembly code file with function names just like the Disassembled View in Ghidra shows. But I don't know how to use the exporter.setOptions() to do this.

**Comment by EmpRamses** [comment]
> @EmpRamses I do the same just want the raw assembler like IDA does using the command line. Exporting it as an ascii file will create a pseudo asm file with lots of extra fluff but coding in python (I use perl) will be easily processed.
> 
> Let us know how you get on as I have reverted back to IDA in the interim as it does a significantly better job of finding the asm in the binary analysis (another post). Just for 1 vehicle I have over 160 different operating systems so using a GUI is not productive and I have not found the script to find the next undecoded instruction and get it encoded ( cntrl-alt-U and D).

@DarrylC03 I'm still working on it. I have get assembly code and their address following instructions of @ryanmkurtz (You can get more info from the iterator if you like). And I also found a repository [https://github.com/VDOO-Connected-Trust/ghidra-pyi-generator](url) that can transfer Ghidra's api to python api. Now I'm looking for methods how to analyze binary code directly in python script rather than using shell command (the "analyzeHeadless" command). Once I have done, I will publish my code in this issue.

**Comment by EmpRamses** [comment]
@DarrylC03 I've partly done my work with ghidra_bridge [https://github.com/justfoxing/ghidra_bridge.git](url). Since it still cannot be close clearly with python or other script with instruction rather than cancel with keyboard interruption, there always be some error messages when I want to close one binary file and open another, which indicates that the port have been occupied by another process. But these errors do not keep me from fetch code from Ghidra. So it seems to be useable. 
And as you said that you want to get assembly code from multiple operating systems, I think you can run multiple "analyzeHeadless" command on multiple machines or VMs, which are listening different ip addresses or ports. In that case, you may not trigger those error as I met.

You can just visit [my new repo](https://github.com/EmpRamses/ghidra_py_Instr) to get my code. And I'll close this issue since I've got almost anything of this problem.
