### ISSUE TITLE
How is it possible to decompile a nasm generated binary using Ghidra?

### ISSUE THREAD

**Issue by TheOnlyArtz** [NationalSecurityAgency/ghidra#1341]
I have this Binary which has been compiled using `nasm`, while IDA has no issues decompiling it, Ghidra just can't seem to do it?

https://filebin.net/t6qbu38q6s3yiipk
This is the file I'm trying to decompile.

EDIT: The file is MS-DOS 16bit mode btw

**Comment by ryanmkurtz** [comment]
What processor did you select in Ghidra?  If you highlight the first byte and press "d" on your keyboard, it doesn't disassemble?

**Comment by TheOnlyArtz** [comment]
Oh ... so looks like I had to do the `d` on my keyboard part! thank you ♥♥
