### ISSUE TITLE
C++ Formatter Settings (for ghidra C++ code)

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1343]
**Is your feature request related to a problem? Please describe.**
Opening some of the c++ source code in the repository displays funny without the correct formatting settings due to the mixed use of tabs and spaces.

**Describe the solution you'd like**
A .clang-format file with the correct settings to use or at least have them listed somewhere in the repo.

**Describe alternatives you've considered**
Converting all tabs to 8 spaces in the c++ source code. Using 8 spaces because that is what the tab size appears to have been.

**Additional context**
This is what some of the code looks like when opened in notepad++ and vscode with the default tab size of 2.

![default_tab_size_results](https://user-images.githubusercontent.com/46897303/70853564-5be98f80-1e7d-11ea-9b16-e874edaa3804.PNG)

The only text editor I've opened code in with this issue where it has been displayed correctly by default is the default windows notepad. (For testing purposes of course). Apparently vim displays a tab as 8 characters by default as well.

**Comment by astrelsky** [comment]
@caheckman do you have a configuration or settings profile for the editor you use that can be shared?

**Comment by astrelsky** [comment]
Resolved by 30d02ac371e532b62d93c0d648ffdc28e9ebec97

**Comment by caheckman** [comment]
I see you found it...

There is an Eclipse CDT formatter for the C++ code in the repo now at
  $ROOT/eclipse/GhidraCDTFormatter.xml

Assuming the CDT is installed in your Eclipse environment, you can import the formatter via

 Windows -> Preferences
   C/C++ -> Code Style -> Formatter
     Import ...
