### ISSUE TITLE
Location of ghidra_scripts directory

### ISSUE THREAD

**Issue by LCRERGO** [NationalSecurityAgency/ghidra#1347]
Is it possible to change the location where ghidra_scripts directory and others are stored?

**Comment by ryanmkurtz** [comment]
It is.  In the Script Manager, click the "Script Directories" toolbar icon (left of the red + icon).  From there you can control where Ghidra searches for scripts.

**Comment by msimms** [comment]
I think the OP was asking if he could change the location, not just select which of the scripts locations are used. I personally cannot stand having the ghidra_scripts directory in my user dir and wish I could put it somewhere else.

**Comment by dragonmacher** [comment]
> I think the original poster was asking if he could change the location, not just select which of the scripts locations are used. I personally cannot stand having the ghidra_scripts directory in my user dir and wish I could put it somewhere else.

Yes, using the method referenced above, you can remove your user home scripts location.  You can also add any other locations you desire.

**Comment by ryanmkurtz** [comment]
I think `~/ghidra_scripts` may continue to recreated at startup tho.

**Comment by dragonmacher** [comment]
> I think `~/ghidra_scripts` may continue to recreated at startup tho.

That would be very Ghidra-like and unfortunate.
