### ISSUE TITLE
Filesystem Error while decompiling binaries in ghidra (Linux)

### ISSUE THREAD

**Issue by 4NONYM4U5** [NationalSecurityAgency/ghidra#1350]
I am facing issue in decompiling file using ghidra. Whenever i import a file in ghidra it shows me filesystem error. I use openjdk 11.0.6 running on kali linux. Can anybody help me in resolving this issue. Thank you in advance

**Comment by astrelsky** [comment]
https://github.com/NationalSecurityAgency/ghidra/wiki/Frequently-asked-questions#why-am-i-getting-access-denied-errors-running-ghidra-from-a-read-only-installation

**Comment by 4NONYM4U5** [comment]
@astrelsky It dint resolve my issue.

**Comment by ryanmkurtz** [comment]
Are you getting a java stack trace?  If so, can you include it here?

**Comment by astrelsky** [comment]
> @astrelsky It dint resolve my issue.

Sorry,  I may have jumped the gun.

**Comment by 4NONYM4U5** [comment]
This is the output of the command:-
▶ jstack -l -e 1849
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
1849: Unable to open socket file /proc/1849/root/tmp/.java_pid1849: target process 1849 doesn't respond within 10500ms or HotSpot VM not loaded

**Comment by 4NONYM4U5** [comment]
Downloaded the package from ghidra official page .This resolved my issue
