### ISSUE TITLE
Version Tracking crash

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#1352]
Attempting to use the version tracking tool (public 9.1) on two versions of firmware and coming across when starting analysis:

```
An unexpected error occurred while processing the command: Auto Version Tracking Command
java.lang.Runtime.Exception: different number of codeunits
        at ghidra.app.plugin.match.ExactInstructionsFunctionHasher.commonBitCount(ExactInstructionsFunctionHasher.java:49)
```

Is this from something I did in the firmwares when I loaded them or just an issue in analysis (i.e. can I do something to fix?)

**Comment by dragonmacher** [comment]
The code throwing the exception is checking that the instruction count between the functions is the same.  That code expects that the client has validated the code unit count before it is called.   However, the client code is only checking that the number of addresses in the functions are the same.  In this case you must have two functions that have been matched-up, with the same number of addresses in the body, but with a different number of instructions.

This is a bug.  We need to update the `FunctionMatchProgramCorrelator` to validate the code unit count before calling the `FunctionHasher`.

As far as a workaround, you can turn off the **Exact Function Instructions Match** correlator when performing correlation.
