### ISSUE TITLE
Negative offset from a pointer shows the wrong field.

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#1353]
I finally concluded that ghidra is lying to me in the decompilation.

I am looking at binary code that seems to be indexing into a table of structures.  The structures are 28 bytes long, so the code multiplies the index by 28 and adds to the base.  But, unusually, the code references the elements with negative offsets of the pointer.  So, I presume that the source code originally was something like "table[index-1]" and the -1 was pulled out by the compiler.

Anyway, I see the assembly code like " ldr.w  r3,[r4,#-0x18]", where r4 is the pointer to the struct.  This *should* be something like "entry[-1].field_4" (ie. 4 bytes into the previous record) but ghidra is showing me "entry[-1].field_8".  The structure editor shows the table element as 28 bytes, and ghidra groks indexing into the table correctly to get the pointer, but the reference itself seems to get things confused.  The p-code appears correct as subtract 24 from r4 then reference memory.

This is ghidra 9.0.3 working on ARM thumb code.

**Comment by saruman9** [comment]
I think it relates to #573.

**Comment by marcushall42** [comment]
Perhaps it is, but it looks like that is an issue that the pointer to the structure is not aligned to begin with.  In my case, my pointer is properly aligned, the code just makes a reference to the previous element.  The binary code is essentially doing:
                   *(int *)((int)ptr - 24)
For a 28 byte structure element, This should be the same as:
                  *(int *)(   (int)ptr - 28 + 4 )
                  *(int *)(   (int)(ptr-1) + 4 )
                   ptr[-1].field_4
But, somehow ghidra is coming up with
                   ptr[-1].field_8
If the offset is positive, it correctly calculates the element number (ie: something like ptr[4].field_4), but if the offset is negative, it somehow loses 4 bytes in the calculation.  Will have to check my notes to see if I can find the spot in the binary again to see if ghidra 9.2 is any better at this...

**Comment by marcushall42** [comment]
I think that there is no hope of reproducing this, and it is unlikely to be stumbled upon again (if the problem even still exists).  Time to close this...

**Comment by Wall-AF** [comment]
@marcushall42 I think I've raised this as well in https://github.com/NationalSecurityAgency/ghidra/issues/5758.  It's definately reproducable and exists elsewhere!
