### ISSUE TITLE
Keyboard shortcut for "Apply Editor Changes" does not persist

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#1355]
Keyboard shortcuts for the **Apply Editor Changes** action are permanently forgotten if the code browser is used without ever opening a structure to edit. 

It seems likely that keyboard shortcuts for plugins are permanently forgotten if a session ends where the plugin was not used.

1. Create a new Ghidra project and import any file
2. Open the file in the code browser and create a structure
3. Assign a keyboard shortcut to the "Apply Editor Changes" action
4. Close the code browser
5. Open the same file again the code browser
6. Close the code browser
7. Open the same file one final time in the code browser
8. Open the previously created structure for editing
9. Make changes to the structure
10. Attempt to use the previously set hotkey to save the changes

**Environment (please complete the following information):**
 - OS: Windows 2008 Server R2
 - Java Version: 11.0.2
 - Ghidra Version: 9.1-PUBLIC

**Comment by dragonmacher** [comment]
Good explanation.  I have confirmed it is broken.
