### ISSUE TITLE
Hotkey F2 for the "Rename" action in the Symbol Tree does not work

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#1356]
I have set the shortcut <kbd>F2</kbd> for the action **Rename Symbol** of the **SymbolTreePlugin**:

![image](https://user-images.githubusercontent.com/11869704/71041827-55cc0b00-212a-11ea-8de3-087d3f86337a.png)

However, pressing <kbd>F2</kbd> while having an entry selected in the symbol tree has no effect, even though the shortcut is displayed in the context menu, and using the context menu entry allows to edit the entry.

**Environment (please complete the following information):**
 - OS: Windows 2008 Server R2
 - Java Version: 11.0.2
 - Ghidra Version: 9.1-PUBLIC

**Comment by dragonmacher** [comment]
The F2 key was conflicting with Java's built-in edit key binding.   This should be an easy fix.  In the meantime, you can use any other key binding that is not F2.
