### ISSUE TITLE
Keyboard shortcut support for the Edit Data Type action

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#1357]
I often use the **Edit Data Type** context menu entry when working with heavily structured data (i.e. code that was written in C++). It currently seems impossible to assign a keyboard shortcut to this action, and I am hoping that it would not be too much effort to implement this. I attempted to set a keyboard shortcut for this context menu option as follows:

![image](https://user-images.githubusercontent.com/11869704/71042195-5d3fe400-212b-11ea-9efd-d6da7f7c3e81.png)

However, this seems to either be another action or the assignment is buggy:

![image](https://user-images.githubusercontent.com/11869704/71042230-7779c200-212b-11ea-8238-ace653eb93ed.png)

Attempting to press <kbd>Shift</kbd>+<kbd>Y</kbd> does not launch the struct editor for the corresponding type either.

**Comment by dragonmacher** [comment]
So, the action is in the options, but it is listed under 'EditDataType', with no spaces.   We will fix that.

Also, FYI, you can assign a key binding to any action from a toolbar button or a menu item by hovering over that item and pressing F4.  So, in the case above, you currently can hover over the menu item and use the F4 command to set the key binding.

**Comment by huettenhain** [comment]
Oh that is awesome, thank you for the tip!
