### ISSUE TITLE
ARM Cortex-M: IT instruction with ALWAYS condition not supported

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#1359]
**Describe the bug**
I found that there is no support for `ITTTT, AL` instruction
According to [official manual](http://class.ece.iastate.edu/cpre288/resources/docs/Thumb-2SupplementReferenceManual.pdf) "always" is correct condition in "IT" block.

I dont know, what the meaning of such condition, but IAR ARM can generate it...

**To Reproduce**
* create binary with `E1 BF` bytes
* load as ARM:LE:32:Cortex (1.102)
* try to disassembly

**Screenshots**
![image](https://user-images.githubusercontent.com/12969211/71099999-477efd00-21c5-11ea-8d22-b220ffcba184.png)

**Environment (please complete the following information):**
 - Ghidra Version: latest master

**Comment by GhidorahRex** [comment]
This is definitely valid ARM. The` itttt al` instruction will unconditionally execute the next four instructions (orr, lsr, orr, lsr). Ghidra is erroneously excluding the 'AL' case.

**Comment by Hardcore-fs** [comment]
Actually it's  "Thumb" mode

There may be an issue at instruction "c4 f1 20 07 " it might actually be operating on a ".w"
as well as the missing instruction.

![image](https://user-images.githubusercontent.com/1309004/71173497-d6f7df00-229d-11ea-867c-690faba20318.png)

**Comment by GhidorahRex** [comment]
@Hardcore-fs the instruction itself is correct, but the mnemonic is wrong. It looks like the ".w' width specifier was placed on the wrong encoding. That should most likely be a separate issue.

**Comment by GhidorahRex** [comment]
Fixed in 498abf1a31b16da52a6c8051142392f6316356f4

**Comment by GhidorahRex** [comment]
Fixed in 5ff5426ffc18aee93488a2252716a7b5a9aca7d2
