### ISSUE TITLE
Skipping library which is the wrong architecture

### ISSUE THREAD

**Issue by torarnv** [NationalSecurityAgency/ghidra#136]
**To Reproduce**
1. Import a MachO 64-bit exectuable on e.g macOS 10.14.3
2. Enable loading of external libraries
3. Observe failure to load libraries

```
Searching for referenced library: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit ...
Skipping library which is the wrong architecture: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
Unable to find external library: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
Searching for referenced library: /usr/lib/libc++.1.dylib ...
Skipping library which is the wrong architecture: /usr/lib/libc++.1.dylib
Unable to find external library: /usr/lib/libc++.1.dylib
```

**Expected behavior**
External libraries are loaded, as the executable i 64-bit too (x86:LE:64:default (2.8)

**Environment (please complete the following information):**
 - OS: macOS 10.14.3
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Comment by ryanmkurtz** [comment]
Possibly related to #110

**Comment by adamopolous** [comment]
This appears to be a problem with loading any external libs that are universal binaries. Should be a simple fix. Thanks for finding this!
