### ISSUE TITLE
PIC16 LSLF and LSRF are wrongly identified 

### ISSUE THREAD

**Issue by Abuhendi** [NationalSecurityAgency/ghidra#1362]
ghidra can not correctly recognize LSLF and LSRF instructions of the PIC16F family.
It identifies the both instruction as RETLW instruction.

**Comment by wgc1212** [comment]
Several Enhanced PIC16 instructions were missed.  This includes the LSLF and LSRF, as well as CALLW and ASRF.  They are defined in the PIC-16F.idx file, but not in the pic16_instructions.sinc file.  It is also possible that RETLW is misdefined for PIC16F, providing for its incorrect assignment .

**Comment by Abuhendi** [comment]
can I modify the pic16_instructions.sinc file and add the missing instructions? would that be enough to make ghidra identify these instructions?

**Comment by wgc1212** [comment]
That is my understanding of the issue. I have started adding them, but I haven't tested them yet and I'm new to SLEIGH so it's been slow going.

**Comment by GhidorahRex** [comment]
I went through the list of PIC16 instructions from the manual, here are the ones that are not included in the .sinc file:

- ASRF
- CALLW
- LSLF
- LSRF
- ADDFSR

Surprised those are missing, since they're clearly in the manual (and in the index file).
