### ISSUE TITLE
ARM thumb RSB instruction incorrect ".w" width specifier

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#1365]
**Describe the bug**

@Hardcore-fs found that 32-bit ORR instruction incorrectly displayed.

please, add ".w" on this line
https://github.com/NationalSecurityAgency/ghidra/blob/5b7bc64b6d97864df2807f9b4d711172701ec411/Ghidra/Processors/ARM/data/languages/ARMTHUMBinstructions.sinc#L2932

**To Reproduce**

look at examples at #1359

**Comment by GhidorahRex** [comment]
That line is correct as-is. The ORR (immediate) variant does not have a wide specifier because it does not occur in a narrow format. This can be observed in address 0x1012 of the image shared by @Hardcore-fs

**Comment by Hardcore-fs** [comment]
For constancy it would be better to show it, that way there is no mental gymnastics needed.
Whilst it may be syntactically correct... it look "odd" esp. for people that are not deeply familiar with the product line. 
(nothing worse than disassembling to mnemonics and having to look up every dammed thing)
