### ISSUE TITLE
How to predict offset addition to addresses

### ISSUE THREAD

**Issue by Enkelmann** [NationalSecurityAgency/ghidra#1366]
I want to import the results of another binary analysis tool as bookmarks into Ghidra. But it is unclear to me how to correctly compute the corresponding addresses in Ghidra.

For small test binaries, all addresses in the binary are smaller than Ghidras base address, so Ghidra adds the base address (which I get with `currentProgram.getMinAddress()`) as an offset to all addresses. For other binaries, the base address as encoded in the binary itself is already larger than the base address of Ghidra, so Ghidra does not add an offset to the addresses.

How can I get Ghidra to tell me whether it added an offset to addresses or not? I couldn't find an API call for this and I assume that my current workaround (testing whether addresses are smaller than  `currentProgram.getMinAddress()` or not) will not work in general.

**Comment by ryanmkurtz** [comment]
What loader/file format are you working with?  ELF? PE? BinaryLoader?  Ghidra will load an image into memory at a certain image base, which is accessible from a script with `currentProgram.getImageBase()`.  It will be up to each loader to appropriately map a file offset to a memory address.  Hopefully Ghidra and the other tool are doing this the same way, with the exception of the image base possibly being different.

**Comment by Enkelmann** [comment]
Right now I am working with ELF files, but I hope to find a solution that will also work with other file types.

I tested `currentProgram.getImageBase()` right now and it yields non-zero offsets for both cases, even when there should not be an offset.

AFAIK the other tool reports addresses as they would be in memory when using the offsets defined in the ELF headers. Ghidra seems to do the same except when it would yield addresses smaller than the base offset. But since I didn't find any documentation on this, I don't know whether this is true or not.

**Comment by ryanmkurtz** [comment]
For ELF, the desired image base specified by the file can be gotten with:

`ElfLoader.getElfOriginalImageBase(currentProgram);`

This is ELF specific though.  We currently don't have a generic way to do it across all loaders.

**Comment by Enkelmann** [comment]
I can't find this function in the online documentation and my python script also cannot find it. Do I need to switch to the master branch to use it?

I any case, thanks for the help! I will look at it again after the holidays.

**Comment by ryanmkurtz** [comment]
If you use functions outside of the GhidraScript/FlatProgramAPI class hierarchy, you need to explicitly export the classes you use.  Try adding:

`from ghidra.app.util.opinion import ElfLoader`

**Comment by astrelsky** [comment]
> I can't find this function in the online documentation and my python script also cannot find it. Do I need to switch to the master branch to use it?
> 
> I any case, thanks for the help! I will look at it again after the holidays.

So unfortunately the online documentation at https://ghidra.re/ghidra_docs/api/index.html is out of date with the public releases. `ElfLoader.getElfOriginalImageBase(currentProgram);` is available in ghidra 9.1. Your best bet for docs when you want to search through them would be to extract the `GhidraAPI_javadoc.zip` in `$GHIDRA_INSTALL_DIR/docs` and bookmark the index.html file in your web browser.

**Comment by Enkelmann** [comment]
`ElfLoader.getElfOriginalImageBase(currentProgram)` works as intended, thanks! I also noticed that the online documentation was updated, so thanks again!
