### ISSUE TITLE
Ghidra build failes because of errors

### ISSUE THREAD

**Issue by binlaveloos** [NationalSecurityAgency/ghidra#1368]
**Describe the bug**
The current version of ghidra will not build. The code has multiple errors in it that cause the build to fail. 
I'm building on:
Windows 10 x64, gradle 5.6.3, AdoptOpenJDK (build 11.0.5+10), visual studio 2017
I tried both msys2 and windows cmd shell, both give the same results

the first build error i encountered:
* Where:
Script 'K:\ghidracompile\ghidra5\gradle\support\ip.gradle' line: 87
* What went wrong:
Execution failed for task ':Docking:ip'.
> Could not find matching constructor for: java.io.File(File)

i looked at the code. The error is in Line 87 of ghidra\gradle\support\ip.gradle:
String libName = new File(lib).getName()  // get just the filename without the path

It should probably be like this: (lib is already type File)
String libName = lib.getName()  // get just the filename without the path

after i changed this building failed again:

FAILURE: Build failed with an exception.
* Where: Script 'K:\ghidracompile\ghidra4\gradle\support\ip.gradle' line: 89
* What went wrong: Execution failed for task ':FileFormats:ip'.
> No License specified for external library: lib/jsr305-1.3.9.jar in module K:\ghidracompile\ghidra4\Ghidra\Features\FileFormats. Expression: map.containsKey(relativePath)

I fixed this one by adding this line to Module.manifest
MODULE FILE LICENSE: lib/jsr305-1.3.9.jar BSD

after this there is another one, and another on and another....
I fixed them by adding
lib/jsr305-1.3.9.jar
lib/commons-cli-1.2.jar
lib/guava-19.0.jar
to the Ghidra\Features\FileFormat\Modules.manifest

and: lib/guava-19.0.jar to Ghidra\Framework\Graph\Module.manifest
and: lib/ST4-4.0.8.jar to Ghidra\Framework\SoftwareModeling\Module.manifest

and then the next error:

K:\ghidracompile\ghidra\Ghidra\Features\Base\src\main\java\ghidra\program\flatapi\FlatProgramAPI.java:581: error: reference not found
         * of the comment.  Contrastingly, calling {@link #getRepeatableCommentAsRendered(Address)} will
                                                          ^
K:\ghidracompile\ghidra\Ghidra\Features\Base\src\main\java\ghidra\program\flatapi\FlatProgramAPI.java:586: error: reference not found
         * @see #getRepeatableCommentAsRendered(Address)
  
The errors above are related to javadoc comments. To fix them, i changed (on line 581):
 * of the comment.  Contrastingly, calling {@link #getRepeatableCommentAsRendered(Address)} will
to this:
 * of the comment.  Contrastingly, calling {@link GhidraScript#getRepeatableCommentAsRendered(Address)} will

and on line 586:
 * @see #getRepeatableCommentAsRendered(Address)
to:
 * @see GhidraScript#getRepeatableCommentAsRendered(Address)

After this, it will complete the build. There are still more errors left (and lots of warnings too) :

K:\ghidracompile\ghidra4\Ghidra\Framework\Generic\src\main\java\generic\concurrent\ConcurrentQ.java:117: error: malformed HTML
 * QItemListener<ITEM, RESULT> itemListener = new QItemListener<ITEM, RESULT>() {
                ^
K:\ghidracompile\ghidra4\Ghidra\Framework\Generic\src\main\java\generic\concurrent\ConcurrentQ.java:117: error: bad use of '>'
 * QItemListener<ITEM, RESULT> itemListener = new QItemListener<ITEM, RESULT>() {
                             ^
K:\ghidracompile\ghidra4\Ghidra\Framework\Generic\src\main\java\generic\concurrent\ConcurrentQ.java:117: error: malformed HTML
 * QItemListener<ITEM, RESULT> itemListener = new QItemListener<ITEM, RESULT>() {
                                                               ^
K:\ghidracompile\ghidra4\Ghidra\Framework\Generic\src\main\java\generic\concurrent\ConcurrentQ.java:117: error: bad use of '>'
 * QItemListener<ITEM, RESULT> itemListener = new QItemListener<ITEM, RESULT>() {
                                                                            ^
K:\ghidracompile\ghidra4\Ghidra\Framework\Generic\src\main\java\generic\concurrent\ConcurrentQ.java:118: error: malformed HTML
 *     public void itemProcessed(QResult<ITEM, RESULT> result) {
                                        ^
K:\ghidracompile\ghidra4\Ghidra\Framework\Generic\src\main\java\generic\concurrent\ConcurrentQ.java:118: error: bad use of '>'
 *     public void itemProcessed(QResult<ITEM, RESULT> result) {

**Attachments**
i attached patch file with the changes i made, and the buildlog:

[gradle_daemon.log](https://github.com/NationalSecurityAgency/ghidra/files/3989840/gradle_daemon.log)
[ghidra_fix_build_errors.patch.txt](https://github.com/NationalSecurityAgency/ghidra/files/3989866/ghidra_fix_build_errors.patch.txt)

**Environment (please complete the following information):**
windows:
Microsoft Windows [Version 10.0.18362.535]

java --version:
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

gradle version:
Gradle 5.6.3

Build time:   2019-10-18 00:28:36 UTC
Revision:     bd168bbf5d152c479186a897f2cea494b7875d13

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.5 (AdoptOpenJDK 11.0.5+10)
OS:           Windows 10 10.0 amd64

ghidra version:
last commit is 5b7bc64b6d97864df2807f9b4d711172701ec411

bison --version:
bison (GNU Bison) 3.4.1
Written by Robert Corbett and Richard Stallman.

flex --version:
flex 2.6.4

**Comment by ryanmkurtz** [comment]
The `getRepeatableComment` errors have been fixed by 75a90485a1fac6be8bea1a5fe39f36e82599eb8d.  I am doing a fresh build now and so far, so good.

**Comment by ryanmkurtz** [comment]
Ok I got the `:Docking:ip` issue.

**Comment by ryanmkurtz** [comment]
I reverted a recent change that is the likely culprit.

**Comment by astrelsky** [comment]
> The `getRepeatableComment` errors have been fixed by [75a9048](https://github.com/NationalSecurityAgency/ghidra/commit/75a90485a1fac6be8bea1a5fe39f36e82599eb8d). I am doing a fresh build now and so far, so good.

Not exactly related, but any javadoc errors won't cause the build to fail because createJavadocs.failOnError is set to false. I have it set to true locally to catch them so they don't just continuously pile up.

**Comment by ryanmkurtz** [comment]
Fixed by ccabecec3a476330c799a6c7d591f9d0996de647
