### ISSUE TITLE
x86: Decompilation of BT is incorrect

### ISSUE THREAD

**Issue by yifanlu** [NationalSecurityAgency/ghidra#1369]
Code: `0f b7 d2 48 bb 00 00 00 00 80 84 00 00 48 0f a3 d3 0f 83 8d 01 00 00`

Ghidra decompiles this into:
```c
if ((0x848000000000U >> ((ulonglong)uVar4 & 0x1f) & 1) == 0) goto LAB_0001688c;
```

But it should be
```c
if ((0x848000000000U >> ((ulonglong)uVar4 % 64) & 1) == 0) goto LAB_0001688c;
```

The `movzx` zero-extends RDX from 16-bits to 64-bits. Then the BT does a bit test using RDX as the bit offset.

According to https://www.felixcloutier.com/x86/bt

> If the bit base operand specifies a register, the instruction takes the modulo 16, 32, or 64 of the bit offset operand (modulo size depends on the mode and register size; 64-bit operands are available only in 64-bit mode).

It seems like Ghidra's decompiler is assuming that the bit offset operand must be < 32. I haven't tested the modulo size behavior, but in the very least it should work with 64 bit bit base.

**Comment by mumbel** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/ccabecec3a476330c799a6c7d591f9d0996de647/Ghidra/Processors/x86/data/languages/ia.sinc#L1939

Looks like a copy/paste error from the 32-bit `BT` a few lines up

**Comment by yifanlu** [comment]
But according to specs, of all register size it should be a mod instead of a mask. I haven’t tested this before so my understanding might be wrong but if you have, for example 10000 as the offset. Then it will be 10000 % 64 (if using 64 bit operand) or 10000 % 32 (if 32 bit operand) etc.

**Comment by mumbel** [comment]
They are equivalent here

http://graphics.stanford.edu/~seander/bithacks.html#ModulusDivisionEasy

**Comment by yifanlu** [comment]
Oh right, for some reason I didn’t make the connection that it’s always going to be a power of 2!
