### ISSUE TITLE
macOS: Mouse move cancels right click context menu

### ISSUE THREAD

**Issue by torarnv** [NationalSecurityAgency/ghidra#137]
**Describe the bug**
The native behavior on macOS when triggering the right click (two finger tap) context menu is that even if the mouse cursor it moved a bit, the context menu still appears. In Ghidra the context menu only appears if you keep the mouse cursor on the exact same position. 

**To Reproduce**
1. Double tap in the code browser e.g.
2. Move the mouse slightly before the context menu appears

**Expected behavior**
Context menu appears

 - OS: macOS 10.14.3
 - Java: 11.0
 - Ghidra Version: 9.0

**Comment by ryanmkurtz** [comment]
I've been using a mac a lot recently and haven't had any issues with this.
