### ISSUE TITLE
Anyone here Who can unlock This indicator?

### ISSUE THREAD

**Issue by ashrafulcg** [NationalSecurityAgency/ghidra#1372]
[BinarySniper.zip](https://github.com/NationalSecurityAgency/ghidra/files/3991150/BinarySniper.zip)

**Comment by astrelsky** [comment]
Please provide more information as to what this is.

**Comment by ashrafulcg** [comment]
This is Forex and binary indicator

**Comment by ryanmkurtz** [comment]
Our GitHub issues page is not the appropriate venue for this question...closing.
