### ISSUE TITLE
NullPointerException when running in Headless mode

### ISSUE THREAD

**Issue by am06** [NationalSecurityAgency/ghidra#1374]
INFO  Using log config file: jar:file:/C:/Users/Adrian/Documents/ghidra_9.1_PUBLIC_20191023/ghidra_9.1_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: C:\Users\Adrian\.ghidra\.ghidra_9.1_PUBLIC\application.log (LoggingInitialization)  
INFO  Loading user preferences: C:\Users\Adrian\.ghidra\.ghidra_9.1_PUBLIC\preferences (Preferences)
INFO  Class search complete (656 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: SHA1PRNG (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)
INFO  HEADLESS Script Paths:
    C:\Users\Adrian\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Features\Base\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Features\BytePatterns\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Features\Decompiler\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Features\FileFormats\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Features\FunctionID\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Features\GnuDemangler\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Features\Python\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Features\VersionTracking\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Processors\8051\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Processors\DATA\ghidra_scripts
    C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\Ghidra\Processors\PIC\ghidra_scripts (HeadlessAnalyzer)
INFO  HEADLESS: execution starts (HeadlessAnalyzer)  
INFO  Opening existing project: C:\Users\Adrian\Documents\Ghidra-projects\Windows.gpr (HeadlessAnalyzer)
INFO  Opening project: C:\Users\Adrian\Documents\Ghidra-projects\Windows.gpr (HeadlessAnalyzer$HeadlessProject)  
ERROR Abort due to Headless analyzer error: null (HeadlessAnalyzer) java.lang.NullPointerException
        at ghidra.app.util.headless.HeadlessAnalyzer.processFolderNoImport(HeadlessAnalyzer.java:1319)
        at ghidra.app.util.headless.HeadlessAnalyzer.processNoImport(HeadlessAnalyzer.java:1350)
        at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:435)
        at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
        at ghidra.GhidraLauncher.main(GhidraLauncher.java:79)

**Comment by ryanmkurtz** [comment]
Can you provide your command line arguments to the headless analyzer?

**Comment by am06** [comment]
` C:\Users\Adrian\Documents\ghidra_9.1_PUBLIC_20191023\ghidra_9.1_PUBLIC\support\analyzeHeadless.bat C:\Users\Adrian\Documents\Ghidra-projects Windows.gpr -postScript post

_script.py 4224 -process playsndsrv.dll -noanalysis`

post_script.py is bellow:

`import sys
import urllib2
import base64
import json
import os
import csv

# Maximum depth to search
MAX_DEPTH = 5

# CSV field names
fieldnames = ['type', 'module', 'name','address', 'calledby', 'calledbymodule']

# Output files for CSV
fdext = open("log-ext2.csv", 'a')
fdint = open("log-int2.csv", 'a')
fdrpc = open("log-rpc2.csv", 'a')

#todo: fix excel files, delimiter seems wrong 

csvext = csv.DictWriter(fdext, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL, fieldnames=fieldnames)
csvext.writeheader()

csvint = csv.DictWriter(fdint, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL, fieldnames=fieldnames)
csvint.writeheader()

csvrpc = csv.DictWriter(fdrpc, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL, fieldnames=fieldnames)
csvrpc.writeheader()

# Recursively called to parse called functions
def GetCalled(f, depth):

    # Traverse through to MAX_DEPTH
    if depth > MAX_DEPTH:
        return

    if f == None:
        return

    called = f.getCalledFunctions(getMonitor())

    if len(called) != 0:
        for c in called:
            if c.isExternal():
                csvext.writerow({'type': 'ExtFunction', 'module': c.getExternalLocation().getLibraryName(), 'name': c.getName(
                ), 'address': 0, 'calledby': f.getName(), 'calledbymodule': f.getProgram().getExecutablePath().replace("\\", "/")})

            else:
                csvint.writerow({'type': 'IntFunction', 'module': c.getProgram().getExecutablePath().replace("\\", "/"), 'name': c.getName(
                ), 'address': c.getEntryPoint(), 'calledby': f.getName(), 'calledbymodule': f.getProgram().getExecutablePath().replace("\\", "/")})

            # Parse further functions
            GetCalled(c, depth+1)


args = getScriptArgs()

for arg in args[0].split(","):
    i = int(arg)
    functionBase = currentProgram.getImageBase().add(i)
    f = getFunctionAt(functionBase)

    if f == None:
        # Weird bug in Ghidra where some functions aren't defined, let's check to see if this is the case for this
        if getSymbolAt(functionBase) != None:
            # Create our function
            print ("[*] Creating function")
            f = createFunction(functionBase, None)
            print ("[*] Function created with name %s" % (f.getName()))

        else:
            print ("[!] Could not find function %s" % (arg))
            continue
    else:
        print ("[*] Processing function %s" % (f.getName()))

    csvrpc.writerow({'type': 'RpcFunction', 'module': f.getProgram().getExecutablePath().replace("\\", "/"), 'name': f.getName(), 'address': f.getEntryPoint(), 'calledby': '', 'calledbymodule': ''})
    GetCalled(f, 0)
`

**Comment by ryanmkurtz** [comment]
When you use `-process`, Ghidra expects the file (in this case, `playsndsrv.dll`), to be already imported.  If it's not, you'll want to use the `-import` flag instead of `-process`.  I am guessing this is what you intended, since you also specified the `-noanalysis` flag, which is contradicts `-process`.

We should definitely clean up the uncaught exception though and provide a more useful error message.
