### ISSUE TITLE
Don't check for memory conflict when adding an overlay memory block

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#1375]
**Describe the bug**
When we add initialized memory block with Overlay type to the program, we get the warning message about memory conflict (see Fig. 1).

**To Reproduce**
1. Import any program.
2. Open the program.
3. `File` → `Add To Program...`. Choose any file.
4. In options input same Base Address as in the program, for example. And set `Overlay` option.
5. Click `OK`.

**Expected behavior**
An overlay memory block should be added without memory conflicts.

**Screenshots**

![Add overlay memory block](https://user-images.githubusercontent.com/4244396/71313093-0e54c000-2445-11ea-8475-e45cf4f7425e.png)
> Fig. 1. *Add to program...* the Overlay Memory Block

**Environment (please complete the following information):**
 - OS: Linux 5.3.11
 - Java Version: 13.0.1
 - Ghidra Version: ccabecec

**Comment by RobBrooks** [comment]
I believe I've just encountered a similar issue.

![image](https://user-images.githubusercontent.com/17879728/113424796-ab343600-93c8-11eb-89bd-f2b5f41a2491.png)

![image](https://user-images.githubusercontent.com/17879728/113424994-ff3f1a80-93c8-11eb-85a3-d966a2684044.png)

![image](https://user-images.githubusercontent.com/17879728/113425051-1978f880-93c9-11eb-9d39-7b7ff9c920a2.png)

![image](https://user-images.githubusercontent.com/17879728/113424868-c737d780-93c8-11eb-9109-b42e892a887c.png)

**Comment by ryanmkurtz** [comment]
@RobBrooks would you mind making a new issue for this?

**Comment by RobBrooks** [comment]
Have done that now.
Hope it makes sense.
