### ISSUE TITLE
.mdebug support (MIPS Debug Format)

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1379]
**Describe the solution you'd like**
Support for parsing the .mdebug section in MIPS binaries. According to [mips-tdump.c](https://github.com/pathscale/absoft/blob/master/svn/trunk/ekopath-gcc/ekopath-gcc-4.2.0/gcc/mips-tdump.c) in older versions of gcc it is stabs encapsulated in ECOFF.

**Describe alternatives you've considered**
No known alternatives. I've even done a hackjob of separating mips-tdump from gcc and still don't get proper output.

**Additional context**
I have been digging through code in both gcc and gdb the past few days trying to figure out how to handle this. Most of whats required already exists in the classes for handling the coff binary format. Below are links to the relative files for handling the section from gdb.

[mdebugread.c](https://github.com/bminor/binutils-gdb/blob/master/gdb/mdebugread.c)
[mdebugread.h](https://github.com/bminor/binutils-gdb/blob/master/gdb/mdebugread.h)

Here is a compiled and unlinked sample.
<details><summary>source code</summary>

```
typedef struct _Dummy {
    char a;
    short b;
    int c;
    long d;
    long long e;
} Dummy;

typedef struct _BigDummy {
    Dummy super_Dummy;
    float f;
    double g;
} BigDummy;

int main() {
    printf("hello world\n");
    for(;;);
    return 0;
}
```
</details>

[main.o.gz](https://github.com/NationalSecurityAgency/ghidra/files/3993470/main.o.gz)

**Comment by aerosoul94** [comment]
I wanted to make an issue for this as well. As STABS doesn't appear to be supported at all by Ghidra, I want to point out that STABS is not exclusive to Mips binaries. I've seen them present mostly in Mach-O and some Windows (Mingw) binaries as well. As an alternative, you might be able to use `objdump -g` to dump STABS to C header file that may be loadable.

**Comment by astrelsky** [comment]
@ryanmkurtz may you also add the loader/ELF label to prevent any confusion as these are ELF files which contain a COFF section.

**Comment by astrelsky** [comment]
I've managed to find proper documentation on the section (sourceware mailing archive and waybackmachine to the rescue)

I can implement marking up the section in MIPS_ElfExtension for now as it's fairly straight-forward. Whatever debug format it actually contains would probably be left up to an analyzer.

Here is where I've obtained the information. There is plenty of information here I'm sure users would love.
https://web.archive.org/web/20010628021622/http://reality.sgi.com/davea/objectinfo.html

**Comment by astrelsky** [comment]
> I wanted to make an issue for this as well. As STABS doesn't appear to be supported at all by Ghidra, I want to point out that STABS is not exclusive to Mips binaries. I've seen them present mostly in Mach-O and some Windows (Mingw) binaries as well. As an alternative, you might be able to use `objdump -g` to dump STABS to C header file that may be loadable. That has helped in the past, at least for the Windows binary I was analyzing.

I have the ECOFF structs for the .mdebug section laid out so the next few logical steps would be to parse the stabs strings. From what I've read it seems fairly straightforward but then again I won't know for sure until I'm in too deep.

**Comment by burninrubber0** [comment]
What sort of progress has been made on this so far? I noticed #1460 but am unsure how significant that is in providing .mdebug support.

**Comment by astrelsky** [comment]
> What sort of progress has been made on this so far? I noticed #1460 but am unsure how significant that is in providing .mdebug support.

Unfortunately it is quite significant. I have most of the ground work laid out along with a *mostly* functional prototype. The only way to get data types from it is if stabs is embedded as I was never able to figure out their encoding and the documentation I had was just not clear enough. I also could not figure out how to handle the compressed line numbers. Symbols, file names, and procedures (functions) work without a problem though. I can put up what I have later today if you'd like but it is by no means stable or complete.

**Comment by burninrubber0** [comment]
> Unfortunately it is quite significant. I have most of the ground work laid out along with a _mostly_ functional prototype. The only way to get data types from it is if stabs is embedded as I was never able to figure out their encoding and the documentation I had was just not clear enough. I also could not figure out how to handle the compressed line numbers. Symbols, file names, and procedures (functions) work without a problem though.

It's progressed quite a bit further than I'd realized, then. I was previously under the impression it hadn't yet reached a workable state. In the communities I'm in, there's been substantial interest in .mdebug support for Ghidra, so maybe people will be willing to contribute.
> I can put up what I have later today if you'd like but it is by no means stable or complete.

That would be much appreciated, thank you.

**Comment by astrelsky** [comment]
It seems I forgot. I hope to put up what I have by the end of the weekend though.

**Comment by astrelsky** [comment]
@burninrubber0 https://github.com/astrelsky/ghidra_mdebug

I'm going to close this. I don't think its usefulness is worth being supported by the ghidra team.

**Comment by JayFoxRox** [comment]
On a related note: The .mdebug extension isn't typically useful because I typically also have DWARF and *.map symbol files.
What I'm typically missing is primarily type information and source code mappings, which are in the .mdebug STABS.

STABS support in the .mdebug extension depends on this PR: https://github.com/NationalSecurityAgency/ghidra/pull/1460
