### ISSUE TITLE
Small strings confuse the decompiler

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#1380]
Given the following `small-str.c` file:

```c

#include <string.h>

char path[100];

void f()
{
    char foo[6] = "/foo/";
    char bar[5] = "bar/";

    strcat(path, foo);
    strcat(path, bar);
}
```

Compiled with `gcc -Os -fno-stack-protector -c small-str.c`, leads to the following in Ghidra listing and decompiler (after a few renaming and retyping):

```
00100000 48 83 ec 18                 SUB          RSP,0x18
00100004 48 8d 3d f5 0f 00 00        LEA          RDI,[path]                         = ??
0010000b 48 8d 74 24 0a              LEA          RSI=>foo,[RSP + 0xa]
00100010 c7 44 24 0a 2f 66 6f 6f     MOV          dword ptr [RSP + foo[0]],"/foo"
00100018 66 c7 44 24 0e 2f 00        MOV          word ptr [RSP + foo[4]],'/'
0010001f c7 44 24 05 62 61 72 2f     MOV          dword ptr [RSP + bar[0]],"bar/"
00100027 c6 44 24 09 00              MOV          byte ptr [RSP + bar[4]],'\x00'
0010002c e8 3f 10 00 00              CALL         strcat                             char * strcat(char * __dest, char * __
00100031 48 8d 74 24 05              LEA          RSI=>bar,[RSP + 0x5]
00100036 48 8d 3d c3 0f 00 00        LEA          RDI,[path]                         = ??
0010003d e8 2e 10 00 00              CALL         strcat                             char * strcat(char * __dest, char * __
00100042 48 83 c4 18                 ADD          RSP,0x18
00100046 c3                          RET
```

```c
/* WARNING: Could not reconcile some variable overlaps */

void f(void)

{
  char bar [5];
  char foo [6];
  
  foo._0_4_ = 1869571631;
  foo._4_2_ = '/';
  bar._0_4_ = 796025186;
  bar[4] = '\0';
  strcat(path,foo);
  strcat(path,bar);
  return;
}
```

The following signs show that the decompiler is confused:
- inappropriate variable overlaps warning
- converts to strings in the listing didn't populate to the decompiler
- string-chunk pattern not detected.

**Environment**:
- Ghidra 9.1
- Linux x86_64
- GCC 9.2.0

Note: this is an actual real-case scenario (different strings but same lengths) observed in the wild with an old i386 binary.

**Comment by astrelsky** [comment]
How is the string data being defined in the data section? (string, char[size], etc.) Also what is the defined data's mutability setting?

**Comment by ubitux** [comment]
> How is the string data being defined in the data section? (string, char[size], etc.) Also what is the defined data's mutability setting?

In this particular case there is no such thing string in the data section, the string characters are stored in dword chunks and assigned directly: `MOV          dword ptr [dst], 0x6f6f662f ; ['/', 'o', 'o', 'f']`

**Comment by astrelsky** [comment]
> > How is the string data being defined in the data section? (string, char[size], etc.) Also what is the defined data's mutability setting?
> 
> In this particular case there is no such thing string in the data section, the string characters are stored in dword chunks and assigned directly: `MOV dword ptr [dst], 0x6f6f662f ; ['/', 'o', 'o', 'f']`

I see. This is more likely the reason the decompiler is getting confused.

**Comment by agatti** [comment]
Can this be related to #1209?

**Comment by ubitux** [comment]
> Can this be related to #1209?

I don't think so.

Anyway, the issue is also observable with 64-bit registers:

```c
#include <string.h>

char path[100];

void f()
{
    char dir[]  = "/etc/ssh/";
    char file[] = "cert.pem";

    strcat(path, dir);
    strcat(path, file);
}
```

Using `gcc -Os -fno-stack-protector -c small-str-2.c`:

Disassembly:
```c
/* WARNING: Could not reconcile some variable overlaps */

void f(void)

{
  char file [9];
  char dir [10];
  
  dir._0_8_ = 7526486049635460399;
  dir._8_2_ = 0x2f;
  file._0_8_ = 7882830067606381923;
  file[8] = '\0';
  strcat(path,dir);
  strcat(path,file);
  return;
}
```

Listing (after constant convert):
```asm
SUB          RSP,0x28
LEA          RDI,[path]                                      = ??
MOV          RAX,"/etc/ssh"
MOV          qword ptr [RSP + dir[0]],RAX
LEA          RSI=>dir,[RSP + 0x16]
MOV          RAX,"cert.pem"
MOV          word ptr [RSP + dir[8]],0x2f
MOV          qword ptr [RSP + file[0]],RAX
MOV          byte ptr [RSP + file[8]],0x0
CALL         strcat                                          char * strcat(char * __dest, char * __
LEA          RSI=>file,[RSP + 0xd]
LEA          RDI,[path]                                      = ??
CALL         strcat                                          char * strcat(char * __dest, char * __
ADD          RSP,0x28
RET
```

Linux x86_64, GCC 9.2.1, also reproducible with Clang 9.0.1.

**Comment by huettenhain** [comment]
More likely related to #2285, this is a case of stack strings as well.
