### ISSUE TITLE
Don't decompile some instructions (x86-32)

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#1384]
**Describe the bug**
Ghidra don't decompile some instructions from basic block of the function. I have tried to use various versions of Ghidra, but none solved the problem.

**To Reproduce**
1. Import program from attachment (use `x86:LE:32:default` language ID).
2. Disassemble the code.
3. Create the function.

**Expected behavior**
Decompiler should add a code to the `while` block.

**Screenshots**

![asm](https://user-images.githubusercontent.com/4244396/71447729-558fc900-2743-11ea-98ee-53cb3653f2b3.png)
> Fig. 1. Listing

![decompiler](https://user-images.githubusercontent.com/4244396/71447730-558fc900-2743-11ea-9d0d-6cfa12a025f0.png)
> Fig. 2. Decompiler

**Attachments**

- [Decompiler debug XML file](https://github.com/NationalSecurityAgency/ghidra/files/4000575/debug.zip);
- [raw binary with the code](https://github.com/NationalSecurityAgency/ghidra/files/4000574/code.zip).

**Environment (please complete the following information):**
 - OS: Linux 5.3.11
 - Java Version: 13.0.1
 - Ghidra Version: 26cab55a
 - Language ID:	x86:LE:32:default (2.9)
 - Compiler ID:	gcc

**Comment by ryanmkurtz** [comment]
You have to set a return type on your function so the decompiler knows it should care about `AL`.

**Comment by saruman9** [comment]
Many thanks @ryanmkurtz. It was such a foolish mistake...
