### ISSUE TITLE
Ghidra cannot find jdk folder

### ISSUE THREAD

**Issue by JimChrModder** [NationalSecurityAgency/ghidra#1385]
**Describe the bug**
Trying to install Ghidra and executed  ghidraRun.bat after I installed jdk 11.
So it tells me that it did not find Java folder.But instead let me put the right path of the java folder, it tells me to check the installation guide. So I gone in there and it tells me to edit the environment variables etc. So I added at system variables a variable with the name JAVA_HOME and value C:\Program Files\Java\jdk-11.0.5 (tried even C:\Program Files\Java\jdk-11.0.5/bin). 
Restarted cmd but it says that it still cannot find it.... any help?
Is there any option that let's me edit the jdk path?

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.5
 - Ghidra Version: 9.1.1

**Comment by ghizard** [comment]
Could you be experiencing the issue seen in #921?

**Comment by ryanmkurtz** [comment]
Ghidra does not use the `JAVA_HOME` environment variable.  When Ghidra prompted you for the path of your jdk 11, what path did you give it?  What are the contents of your `c:\Users\<username>/.ghidra/.ghidra_9.1.1_PUBLIC/java_home.save` file?

**Comment by ryanmkurtz** [comment]
@JimChrModder, did you ever get this working?

**Comment by JimChrModder** [comment]
I execute the ghidraRun.bat and I get this:
Java runtime not found.  Please refer to the Ghidra Installation Guide's Troubleshooting section.
Press any key to continue . . .
and when I press a button,it closes.

(I tried it when it was published and it showed me to put java's path and it worked. For some reason it does not ask me to put the right path if it does not find it in this version...)

**Comment by ryanmkurtz** [comment]
You need Java 1.7 or later on your `PATH` environment variable for Ghidra to try to find the correct version of java to use.  If you do `java -version` from a command prompt, what is the output?

**Comment by JimChrModder** [comment]
Fixed it by entering java's bin path in the environment variable with the name "path" instead of adding a new one.

**Comment by h3cjun** [comment]
I have the same problem

**Comment by arentoos** [comment]
winget install Microsoft.OpenJDK.17

**Comment by codemasters1** [comment]
I had the same problem in Windows. I solved it by downloading the latest version of Java and add it to  environment variable path.

**Comment by m-attz** [comment]
**NOTE**: In my case (I'm using Fedora) installing the **java-latest-openjdk-devel** worked for me. 

Reference: [Here](https://forums.fedoraforum.org/showthread.php?330023-Can-t-install-Ghidra-JDK-is-missing-javac-executable&p=1867265)
