### ISSUE TITLE
Missing code in decompiler output armv7 binary

### ISSUE THREAD

**Issue by antisec** [NationalSecurityAgency/ghidra#1388]
**Missing assignment to global struct in decompiler**
the new public version of ghidra didnt decompile an assignment whitch is first statement of a stripped armv7 function. older versions of ghidra produce correct results.

**To Reproduce**
1. Download the the stripped example binary from <https://github.com/james-tate/ghidraExampleSource/blob/master/example_stripped>  
2. import and analyze with default settings.
3. go to main function witch is at offset `00010fe6` from there click the first function `00010a7e`
4. this function fills in a global struct but the first assignment witch points to a string is missing.

**Expected behavior**
the fist field in the struct shoult be seen in decompiled output.

**Screenshots**
this is the expected behavor:  
![Selection_001](https://user-images.githubusercontent.com/1088426/71503460-8a03a200-2875-11ea-8258-9ff36b4280dc.png)

but in ghidra 9.1 public oct-23.19 build 1737 it dosnt show up anymore.
![Selection_002](https://user-images.githubusercontent.com/1088426/71503559-f7173780-2875-11ea-9805-f9ccc525bbce.png)

while the code in listing clearly shows up correct.
![Selection_004](https://user-images.githubusercontent.com/1088426/71503576-0b5b3480-2876-11ea-9e0b-90eb387e5350.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

here is a side by side view.
![Selection_005](https://user-images.githubusercontent.com/1088426/71503589-17df8d00-2876-11ea-8ae7-208ed9c10d94.png)

**Environment (please complete the following information):**
 - OS: [linux]
 - Java Version: [ 11.0]
 - Ghidra Version: [ 9.1 build 1737]

**Additional context**
the binary is from <https://github.com/james-tate/ghidraExampleSource>  
the renamed functions dont matter the problem is right after autoanalysis but for completness i renamed the structs like the steps from <http://hwreblog.com/projects/ghidraVideos.html> video _How to create structures in Ghidra

i attached the binary after compressing it in zip format.
[example_stripped.zip](https://github.com/NationalSecurityAgency/ghidra/files/4004398/example_stripped.zip)

**Comment by caheckman** [comment]
This issue was fixed in the 9.1.1 release.  Thank you for reporting it.
