### ISSUE TITLE
File offset to Address

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1389]
How may I get the address with the correct address space from its absolute offset in the file? The ECOFF Records give offsets relative to the start of the file and I can't seem to find how to easily correlate them.

**Comment by ryanmkurtz** [comment]
```
AddressSpace space = program.getAddressFactory().getDefaultAddressSpace();
Address addr = space.getAddress(offset);
```

That may not be the offset from the start of the file though if it's mapped into memory differently.

**Comment by astrelsky** [comment]
> ```
> AddressSpace space = program.getAddressFactory().getDefaultAddressSpace();
> Address addr = space.getAddress(offset);
> ```
> 
> That may not be the offset from the start of the file though if it's mapped into memory differently.

Unfortunately it's mapped differently. I need to make references to functions, data, etc. and use addresses for things which may be in an overlay such as debug or relocation entries.

**Comment by ryanmkurtz** [comment]
The solution is kind of loader-specific.  Here's what I did for the DYLD loader:
https://github.com/NationalSecurityAgency/ghidra/blob/cbe5b9e9cae03ce4dea117799afc03e4ad32a488/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/macho/dyld/DyldCacheHeader.java#L664-L697

**Comment by ryanmkurtz** [comment]
If you don't have access to the original section information in an easy to access object, you can get it from the MemoryBlocks and FileBytes API's.

**Comment by astrelsky** [comment]
> If you don't have access to the original section information in an easy to access object, you can get it from the MemoryBlocks and FileBytes API's.

Well I could fetch all the elf sections, get their offsets and subtract from them like I'm doing with the section I'm working with. It just has a tendency to get a bit messy or I just don't like the way it 'feels'.

**Comment by ryanmkurtz** [comment]
I think any solution is going to end up needing a method call to do some kind of translation, even if we could somehow provide it generically.

**Comment by astrelsky** [comment]
Aha. ElfHeader has methods to fetch the SectionHeader containing the file offset. I could probably pull the info needed from there.

Thank you!

**Comment by ryanmkurtz** [comment]
Cool, that must have come up in enough other places in ELF to put the helper method in.

**Comment by astrelsky** [comment]
@ryanmkurtz turned out I was overthinking it and the address in the DefaultSpace was good enough.
