### ISSUE TITLE
Add the ability to customise any grid's colors (ex: the struct editor)

### ISSUE THREAD

**Issue by aldelaro5** [NationalSecurityAgency/ghidra#1390]
**Is your feature request related to a problem? Please describe.**
This problem occurs when I try to have a pleasing dark theme UI solution meaning to have a dark theme, but not use the inverted colors option because it looks unpleasing. I have either choice to use the system look from my Gtk theme (arc-dark here) or even better, I found this guide which allows to override the look and field to a more pleasing dark themed one: http://enigmatrix.me/blog/2019/11/30/dark-ghidra/

The issue is on both of these solution, ANY grid in the entire program (struct editor, memory mapping editor, etc...) is rendered grey on white and it's impossible to customise the colors to something more readable. After a long time trying these solutions, it appears to be the last breaking issue for me to have a proper dark themed Ghidra which is why I am submitting this suggestion in the first place.

**Describe the solution you'd like**
Either a way for the grids to obey the system looks when chosen OR a way to select the colors. Honestly, anything that would allow to optionally have the grids rendered white on black would already be huge. It could even be something simple like invert the colors of JUST the grids for now.

**Additional context**
Here's an example of a functions list grid affected by this issue after I select the system look with arc-dark installed:
![Screenshot from 2019-12-27 14-43-38](https://user-images.githubusercontent.com/8932978/71530347-59445c80-28b7-11ea-859e-f01d9818f775.png)

**Comment by dragonmacher** [comment]
Inverted colors have been removed.   You can now change most application colors, icons and fonts by editing the current Theme.

Fixed by e657a701416877f7a77b635662d30cfc25f1b5f0
