### ISSUE TITLE
Missing structure names in decompiler view

### ISSUE THREAD

**Issue by dzidaV8** [NationalSecurityAgency/ghidra#1393]
**Describe the bug**
Having created structure types for variables in Motorola 68k disassembly, the structure members names are not displayed correctly in decompiler output:
![obraz](https://user-images.githubusercontent.com/57442721/71556465-596c6580-2a39-11ea-9f79-6b3fb9163216.png)

As shown above, the 3rd word of the structure is named TCR1_VALUE and displayed correctly in disassembly listing, but in the decompiler output the name is just a genereic _4_4_.
Suprisingly it works for the first member of the structure and shows the name correctly in decompiler, but this time the decompiler listing is missing the structure element name, shows just the whole structure name.

The structure is set like this:
![obraz](https://user-images.githubusercontent.com/57442721/71556477-7acd5180-2a39-11ea-8aa4-68e998a41d4c.png)

**Expected behavior**
![obraz](https://user-images.githubusercontent.com/57442721/71556560-984eeb00-2a3a-11ea-9266-f5bb00840fa2.png)

**Environment:**

    OS: Windows 10
    Java Version: Amazon Coretto 11.0.5
    Ghidra Version: 9.1.1_PUBLIC

**Comment by mumbel** [comment]
This is probably related to #1394

**Comment by GhidorahRex** [comment]
@mumbel, I believe you are correct.

**Comment by GhidorahRex** [comment]
Fixed in 4c81e68
