### ISSUE TITLE
Patch Binary like fill with nops

### ISSUE THREAD

**Issue by AhmedZero** [NationalSecurityAgency/ghidra#1397]
how to patch binary like call function and replace it with nops with one click?

**Comment by ryanmkurtz** [comment]
I don't know of a built-in way to do this, but you could write a script to do it and bind it to key.

**Comment by ryanmkurtz** [comment]
Actually, we have a script to do it already...`EditBytesScript.java`

**Comment by ryanmkurtz** [comment]
It probably doesn't do exactly what you want it to do, but you could modify it to work on a selection, instead of just the cursor's current location.
