### ISSUE TITLE
Support 680x0 line A instructions

### ISSUE THREAD

**Issue by p2mate** [NationalSecurityAgency/ghidra#140]
MacOS classic uses line A instructions (instructions with the highest 4 bits set to 1010) as an interface to the OS and the toolbox. Ghidra however considers these illegal, making disassembly of MacOS classic code difficult. It would be useful if Ghidra disassembles those as LineA #0xyyy where yyy are the lower 12 bits of the instruction word.

**Comment by mumbel** [comment]
http://mirror.informatimago.com/next/developer.apple.com/documentation/mac/OSUtilities/OSUtilities-170.html#HEADING170-48

- op11=0 - Operating System routine
    - push exception stack frame
    - op0910 = flags: routine dependent
    - op8 = return/save A0 bit: op8=0: A0 is returned from OS routine, op8=1: A0 is not returned
    - op7 = trap number
    - saves:  D0,D1,D2,A1,(A2?),A0 if op8=0
    - low(D1)=$AXXX
    - may alter D0-D2, A0-A2; preserve D3-D7, A3-A6; may return in D0 (and A0 if op8=0)
    - restore D1,D2,A1,A2,A0 if op8=0
    - values in D0 and A0 if op8=1 are not restored
    - param: D0 data value and A0 for addresses (or parameter block when more than 2 params)
- f11=1 - Toolbox routine
    - op10 = auto-pop bit: forces trap dispatcher to remove 4bytes of stack before dispatching, will return to glue routine was called
    - op9 = trap number
    - may alter D0-D2,A0,A1
    - parameters and return are stack based and passed as pointers to actual storage

No clue how to write sleigh, and more to it ^^^, but something like this in 68000.sinc for starters

```@@ -76,7 +76,9 @@
   opbig  = (8,15)
   op02 = (0,2)
   op03 = (0,3)
+  op07 = (0,7)
   op08 = (0,8)
+  op09 = (0,9)
   op015 = (0,15)
   op34 = (3,4)
   op35 = (3,5)
@@ -94,6 +96,7 @@
   op8 = (8,8)
   quick = (9,11)
   op811 = (8,11)
+  op11 = (11,11)
   copcc1 = (0,5)
   d8base = (0,7) signed
 @ifdef COLDFIRE
@@ -300,6 +303,8 @@
 
 define pcodeop kfactor;
 define pcodeop ftrap;
+define pcodeop atrap;
+define pcodeop toolbox;
 define pcodeop trap;
 define pcodeop reset;
 define pcodeop saveFPUStateFrame;
@@ -741,6 +746,9 @@
 :asr.l cntreg,regdn		is op=14 & cntreg & op8=0 & op67=2 & op34=0 & regdn		{ getbit(CF,regdn,cntreg-1); regdn=regdn s>>cntreg; resflags(regdn); }
 :asr eaw			is (opbig=0xe0 & op67=3 & $(MEM_ALTER_ADDR_MODES))... & eaw				{ getbit(CF,eaw,0); eaw=eaw s>>1; resflags(eaw); }
 
+:atrap	"#"^op07    	  	is op=10 & op11=0 & op07  { tmp:4 = op07; atrap(tmp); }
+:toolbox "#"^op09    	  	is op=10 & op11=1 & op09  { tmp:4 = op09; toolbox(tmp); }
+
 :b^cc^".b" addr8		is op=6 & cc & addr8						{ if (cc) goto addr8; }
 :b^cc^".w" addr16		is op=6 & cc & d8base=0; addr16					{ if (cc) goto addr16; }
 :b^cc^".l": addr32		is op=6 & cc & d8base=255; addr32				{ if (cc) goto addr32; }
```

**Comment by p2mate** [comment]
Thanks. That helps. Next thing to do is probably to write a script which tells Ghidra which registers have changed by the trap.

**Comment by ryanmkurtz** [comment]
Duplicate of #487

**Comment by hippietrail** [comment]
I'm guessing there are typos in at least these two parts:

>   * op7 = trap number
>   
>   * op9 = trap number

Those would mean single bit fields. I'm guessing it should be:

>   * op07 = trap number
>   
>   * op09 = trap number

I'm not sure if there were other typos.
