### ISSUE TITLE
Does Ghidra tell apart local vars at the same stack offset? (with pdb info supplied)

### ISSUE THREAD

**Issue by Piruzzolo** [NationalSecurityAgency/ghidra#1401]
Say I have this stack layout (from a pdb-generated XML)
```xml
        <function name="MY_FUNCTION" address="0x27600" length="0xc6f">
            <stack_variable name="this" kind="ObjectPointer" offset="0x0" datatype="MY_NICE_DATATYPE" length="0x0" />
            <stack_variable name="dwSize" kind="Parameter" offset="0x4" datatype="ulong" length="0x0" />
            <stack_variable name="CommBuff" kind="Parameter" offset="0x8" datatype="char *" length="0x0" />
            <stack_variable name="dcoFromID" kind="Parameter" offset="0xc" datatype="ulong" length="0x0" />
            <stack_variable name="dcoReceiveID" kind="Parameter" offset="0x10" datatype="ulong" length="0x0" />
            <stack_variable name="fromHold" kind="Parameter" offset="0x14" datatype="int" length="0x0" />
            <stack_variable name="msg_str" kind="Local" offset="0xffffff9c" datatype="char[100]" length="0x0" />
            <stack_variable name="InContent" kind="StaticLocal" offset="0x0" datatype="char *" length="0x0" />
            <stack_variable name="InContentSize" kind="StaticLocal" offset="0x0" datatype="ulong" length="0x0" />
            <stack_variable name="sack" kind="Local" offset="0xfffffe80" datatype="MSGFORMAT_ACKNOWLEDGE_GUARANTEED" length="0x0" />
            <stack_variable name="txpingpong" kind="Local" offset="0xfffffe80" datatype="MSGFORMAT_LATENCY" length="0x0" />
            <stack_variable name="msg" kind="Local" offset="0xfffffe9c" datatype="char[256]" length="0x0" />
            <stack_variable name="txpingpong" kind="Local" offset="0xfffffe80" datatype="MSGFORMAT_LATENCY" length="0x0" />
            <stack_variable name="msg" kind="Local" offset="0xfffffe9c" datatype="char[256]" length="0x0" />
            <stack_variable name="NextSerialNumber" kind="Local" offset="0xfffffe80" datatype="uint" length="0x0" />
            <stack_variable name="dropcount" kind="StaticLocal" offset="0x0" datatype="uint" length="0x0" />
            .... line numbers
```
As you can see, some local vars are at the same offset. They're pushed presumably in different points of the execution so they don't overlap.

My question is: can Ghidra figure out the order of pushes and create all the locals accordingly? Or it just chooses one and stick with it?

**Comment by ghizard** [comment]
We cannot currently do what you are asking.  There are two parts to this.  One is understanding what is going on in the source through to compile.  The other is in the ability to model or incorporate what is going on.

My assumption was that there are local scope variables where the stack space is getting reused.  I had some source code where I was doing this with static locals but not with regular locals, so I modified my source to include this example.  I have yet to figure out appropriate compile options to cause the stack to be reused.  I had been using VS2012, but also just tried 2019.  However, I did find similar reuse of stack space in one of the linked libraries in my 2019 compile. I'll continue to investigate ways for me to see this happen with source and compile options that I control.  If anyone else knows what to do, I'd be interested.

The example I have shows:
```
        <function name="?type_case_c_tchar@?$output_processor@_WV?$stream_output_adapter@_W@__crt_stdio_output@@V?$positional_parameter_base@_WV?$stream_output_adapter@_W@__crt_stdio_output@@@2@@__crt_stdio_output@@AAE_N_W@Z" address="0x30597" length="0xad">
            <stack_variable name="this" kind="Local" offset="0x0" datatype="__crt_stdio_output::output_processor&lt;wchar_t,__crt_stdio_output::stream_output_adapter&lt;wchar_t&gt;,__crt_stdio_output::positional_parameter_base&lt;wchar_t,__crt_stdio_output::stream_output_adapter&lt;wchar_t&gt; &gt; &gt; *" length="0x0" />
            <stack_variable name="__formal" kind="Local" offset="0x8" datatype="wchar" length="0x0" />
            <stack_variable name="wide_character" kind="Local" offset="0xfffffffc" datatype="wchar" length="0x0" />
            <stack_variable name="local_buffer" kind="Local" offset="0xfffffffc" datatype="char[2]" length="0x0" />
```
The pdb.xml format does not currently contain the information necessary to see what is happening or pass this information along, but with information that I have from my current PDB work, I can see that there are defined ranges for each variable name.
```
wide_character 0x305ef - 0x30618
local_buffer 0x30619 - 0x30625
```
So we could have this information in the future.

Regarding applying this information in Ghidra, we do have the ability to do this for register variables, but currently cannot do this for stack variables.  If you find a place in the program Listing (disassembly) where a value is being assigned to a register, you can right-click on it, choose References -> Create Register Reference.  The option is only available on register assignment operations and should allow new reference names at each location where this reference can be created.

Presumably, there should be a way to also do this for stack variables, but they are handled a little differently than registers (which are treated as globals) and would also need to be handled by the decompiler.  I do not know how much work that could entail.

**Comment by Piruzzolo** [comment]
Thanks for the info! That's great to know

**Comment by Wall-AF** [comment]
> ...
> 
> My assumption was that there are local scope variables where the stack space is getting reused. I had some source code where I was doing this with static locals but not with regular locals, so I modified my source to include this example. I have yet to figure out appropriate compile options to cause the stack to be reused. I had been using VS2012, but also just tried 2019. ...

@ghizard did you try something like having several independent loops that each create either a C++ object (say a CString) or allocate some memory, holding that in a variable created within each loop which is then assigned to a global array?  That should work as I don't believe specific compiler options would be the cause.

Conceptually each loop would be something like:
```
for (int i=0; i<sizeofarray(x); ++i) {
    TYPE *var = new TYPE();
    ...
    x[i] = var;
}
```
