### ISSUE TITLE
Website Blocking - Hacker Alert!

### ISSUE THREAD

**Issue by assafnativ** [NationalSecurityAgency/ghidra#1419]
The blocking of https://ghidra-sre.org/ to Israeli IP address is broken! Some hacker I know was able to bypass that with what he called web proxies. He pointed me to a service called HMA, so I suggest you block it and all of its kind. Also, it seems like Google is conspiring with the enemy and creating a backdoor to the site with their innocent-looking service of Google Web Site Translate, so please block Google as well.

**Comment by ryanmkurtz** [comment]
Thanks for the info!
