### ISSUE TITLE
Parsing C header varargs function signatures

### ISSUE THREAD

**Issue by james-tate** [NationalSecurityAgency/ghidra#1420]
When importing a C/C++ header I am currently unable to get Ghidra to identify functions with __VA_ARGS__. 

For example, attempting to import {int varargFunc(int ...);} does not work. 

Ghidra does export functions signatures with varargs, but even if I try to reimport a Ghidra exported header file that has vararg signatures, importing the same file does not work.

**Comment by astrelsky** [comment]
> When importing a C/C++ header I am currently unable to get Ghidra to identify functions with **VA_ARGS**.
> 
> For example, attempting to import {int varargFunc(int ...);} does not work.
> 
> Ghidra does export functions signatures with varargs, but even if I try to reimport a Ghidra exported header file that has vararg signatures, importing the same file does not work.

That's not a legal function signature. A header with only the signature `int test(int, ...);` parsed without a problem.

However attempting to parse `int test(...);` produces an error **as expected.**
Attempting to compile a test c file with the declaration `int test(...);` in gcc produces the following error:
```
varargs_test.c:2:10: error: ISO C requires a named argument before ‘...’
    2 | int test(...);
```

**Comment by james-tate** [comment]
ah, I missed the ',' earlier for `int varargFunc(int ...);`

Anyway, I tried on a different computer and it seemed to work. I will try to replicate the problem I had on the other computer tomorrow. It could be an earlier version of Ghidra installed on that machine.

I will close for now.
