### ISSUE TITLE
Null Pointer Exception in Structure Editor

### ISSUE THREAD

**Issue by MabryTyson** [NationalSecurityAgency/ghidra#1426]
**Describe the bug**
When editing a cell in the last column of any row of the Structure Editor, hitting TAB causes uncaught null pointer exception

**To Reproduce**
1. Edit some structure
2. Enter some non-empty value in the last column of some row (typically Comment, but can be some other column if you have reordered columns).
3. While still in that cell, enter the TAB character on your keyboard
4. A pop-up appears for an unhandled exception.

**Expected behavior**
Other than the last column, TAB finishes the edit of that cell and takes you to edit the next column.  In the last column, TAB should take you to the first column of the next row (as it does if you are merely selecting cells but not editing them, and tabbing from one to the next).

**Error information**
From the pop-up:
Uncaught Exception! 
java.lang.NullPointerException

---------------------------------------------------
Build Date: 2019-Dec-18 1306 EST
Ghidra Version: 9.1.1
Java Home: /Library/Java/JavaVirtualMachines/jdk-12.jdk/Contents/Home
JVM Version: Oracle Corporation 12
OS: Mac OS X 10.14.6 x86_64

**Environment (please complete the following information):**
 - OS: 10.14.6 x86_64
 - Java Version: 12
 - Ghidra Version: 9.1.1

**Additional context**
This bug existed in 9.1 as well.
This is a low priority bug (only an annoyance), but I expect it will be easy to fix.
To get the error, you have to be editing the cell (the cell is normal video (ie, the cell has black text on white background), while the rest of the line is in reverse video), not just simply have the cell selected (the cell & rest of line are reverse video, with a box around the cell).  There is no error if you tab from cell to cell without ever editing the content.

If I reorder columns so an editable column(Name) is followed by an uneditable column(Offset), I do not get the error tabbing out of the editable column.  So I suspect the error has to do with the fact that you're in the last column of the row, rather than the next column (ie, the first column in the next row, typically Offset) is uneditable.

**Comment by astrelsky** [comment]
This may have been fixed in a recent commit after the release of 9.1.1 as I cannot reproduce it. I have previously seen it though.

**Comment by ghidra1** [comment]
I believe this has been fixed
