### ISSUE TITLE
AVR skip instructions do not modify control flow graph

### ISSUE THREAD

**Issue by ahroach** [NationalSecurityAgency/ghidra#1427]
**Describe the bug**
The control flow implications of AVR skip instructions (cpse, sbic, sbis, etc.) are not indicated in the same manner as other control-flow-altering instructions, e.g. with flow arrows in the listing window and function graph. As an example, see the screen shot below. If Wlo == Whi at 0xe0, the next instruction executed will be at 0xe2. If Wlo!=Whi, the next instruction executed will be at 0xe1. Ideally, the instruction at 0xe1 would be in its own basic block, with a conditional branch indicated by arrows from 0xe0 to 0xe1 and 0xe2.

The various skip instructions are currently implemented with the use of a context variable (see avr8.sinc). If the skip context variable is set, the next instruction results in a  'goto inst_next' rather than a 'build instruction'. It seems that this mechanism is not understood by the tools that build the control flow graph.

Since AVR has variable sized instructions, it would not be trivial to have the various skip instructions modify the program counter directly as the various branch instructions do. We would have to know the size of the next instruction to know how far to advance PC. 

The loss of control-flow indicators is somewhere between annoying and problematic for me, depending on how attentive I am being to watch out for skip instructions. I can't think of a straight-forward way to address this. Is there a precedent for handling such instructions in other languages in a way that would result in correct control flow graph construction?

**Screenshots**
![image](https://user-images.githubusercontent.com/1512551/72212050-9148c380-34a3-11ea-9e92-04aab742de22.png)

**Environment (please complete the following information):**
 - OS: Debian Sid
 - Java Version: OpenJDK 11.0.6
 - Ghidra Version: 9.1.1

**Comment by ahroach** [comment]
I should add that the current mechanism works acceptably when the instruction following the skip instruction is something like rjmp. In that case, the SKIP context variable makes rjmp be treated like a conditional branch with some remote target location, and everything works reasonably well. The trouble really arises when the instruction following one of the skip instructions is not a jump of some kind, like the ldi instruction in the example above. In that case, ldi is also treated as a conditional branch if the SKIP context variable is set, but the target is just the next instruction, and none of this is rendered with control flow arrows.

**Comment by GhidorahRex** [comment]
The issue here is that `goto inst_next` is not considered a jump (there are many cases where this would be undesirable behavior). This can be corrected by adding a `CONDITIONAL_JUMP` reference to the skip instruction (i.e. `cpse`) to the code address of the instruction following the skipped instruction.

Depending on the size of the binary, this may be easy enough to do by hand by searching memory for the five skip instruction mnemonics. Otherwise a script would be a better solution.

**Comment by GhidorahRex** [comment]
Try this and let me know if you like the results:
[SkipAVR8Fixup.txt](https://github.com/NationalSecurityAgency/ghidra/files/4055277/SkipAVR8Fixup.txt)

**Comment by ahroach** [comment]
Thanks for the quick reponse and for taking the time to write the script! It does indeed greatly improve the situation.

If I may be allowed one last neurotic quibble, unconditional jump instructions following skip instructions maintain their conditional jump targets after running the script, which unnecessarily clutters the control flow graph. I thought I would try to address this by changing the `CONDITIONAL_JUMP` references to `UNCONDITIONAL_JUMP` references for subsequent jump instructions as in the script below. But, alas, there was no change in the control flow graph. I'm guessing at this point this is because of the `CBRANCH *[code]..., SKIP` pcode ops, which are acting independently of the reference type.

For reference, I've attached a nonsensical AVR binary with various arrangements of skip instructions in the main function at code:0042. If there is a straightforward way to clean up those last jump instructions, I would appreciate hearing about it. If there is not, consider me both sufficiently satisfied by the solution that you gave and very grateful for your help.

[SkipAVR8Fixup2.txt](https://github.com/NationalSecurityAgency/ghidra/files/4057286/SkipAVR8Fixup2.txt)

[nonsense.zip](https://github.com/NationalSecurityAgency/ghidra/files/4057287/nonsense.zip)

**Comment by GhidorahRex** [comment]
I think you're correct about the reason why those `CONDITIONAL_JUMP` references are not being removed. A better course of action may be that since we already know that the flow graph is handling the skip->jump flow, we could just not add the reference at `cpse` if we know that the next instruction after a skip instruction is a jump.

**Comment by ahroach** [comment]
That is definitely the better course of action. The attached script gives me great results. Thanks again!
[SkipAVR8Fixup3.txt](https://github.com/NationalSecurityAgency/ghidra/files/4062353/SkipAVR8Fixup3.txt)
