### ISSUE TITLE
Ghidra should use/upgrade existing config in ~/.ghidra rather than create a fresh one

### ISSUE THREAD

**Issue by zcutlip** [NationalSecurityAgency/ghidra#1432]
When I upgrade Ghidra, it creates a fresh `.ghidra_<VERSION>` under `~/.ghidra/`, so any customizations I've applied don't get carried forward. If I delete that new config and copy the most recent one:

```
$ rm -rf ~/.ghidra/.ghidra_<NEW_VERSION>
$ cp -a ~/.ghidra/.ghidra_<OLD_VERSION> ~/.ghidra/.ghidra_<NEW_VERSION>
```
...then Ghidra happily uses (and upgrades?) the copy of the previous version's configuration.

**Describe the solution you'd like**
I'd like for ghidra to (optionally?) do this automatically. Check for an existing configuration and either copy it and upgrade it or upgrade it in place. This behavior could possibly be enabled by command-line option, environment variable, or similar.

Here's a listing of my Ghidra config directory. In it you can see all the separate config subdirectories for the various Ghidra versions I've run.
```
❱ ls -1a ~/.ghidra
./
../
.ghidra-9.0.2/
.ghidra-9.0.4/
.ghidra_9.1-BETA_DEV/
.ghidra_9.1.1_PUBLIC/
.ghidra_9.1_PUBLIC/
backup/
```

**Comment by dragonmacher** [comment]
Ghidra is supposed to search for and use your most recently used `.ghidra` settings directory.  From this directory will be pulled preferences and existing tools.  The options you configure in you Code Browser tool (the green dragon), that live in the previously used directory, should appear in your new Ghidra when you run it for the first time.  That is, the Code Browser tool you see in your new version of Ghidra should be the previously used tool.

If something is not getting pulled into your new Ghidra, then this is either a bug or some setting that  is not saved in the tool.

**Comment by zcutlip** [comment]
I'm definitely not seeing my settings until I explicitly copy  `~/.ghidra/.ghidra_<OLD_VERSION>` to `~/.ghidra/.ghidra_<NEW_VERSION>`

**Comment by zcutlip** [comment]
Is there any logging or other diagnostics I can gather and submit?

**Comment by dragonmacher** [comment]
My guess is that the algorithm for finding old directories is failing.

To see logging messages for this code you can look in the `userhome/.ghidra/.ghidra_new_version/application.log` file.    To ensure the info is in the log file, you can delete the newest `.ghidra` directory and then restart the new version.   Once it has launched, examine the `application.log` file.    You should see an entry that looks like this near the beginning:

```
    DEBUG No tools found; Installing default tools   (DefaultProjectManager.java:324)
```

If the algorithm is working, then you should see more text related to processing existing tools.  If there are no more debug messges from the `DefaultProjectManager`, then the code did not find any of your old `.ghidra` directories.

**Comment by dragonmacher** [comment]
I will point out that the logic for finding compatible `.ghidra` directories is to compare the running Ghidra version's **release name** against the previous release name.  So, based on your directory listing above, you effectively have 3 different release names available: &lt;empty&gt;, BETA_DEV, and PUBLIC (the release name is the trailing text on the directory name).

If your newest version is 'PUBLIC', then our algorithm should pick either `.ghidra_9.1.1_PUBLIC/` or `.ghidra_9.1_PUBLIC/`, depending upon the directory timestamps.

**Comment by zcutlip** [comment]
Okay thanks for the help. I looked at the application log which reflected merging existing tools, so I double checked and my settings are carried over as they should be. I could have sworn they weren't before.

I'll close this for now and open a new issue if the problem returns.

**Comment by dragonmacher** [comment]
Based upon my previous comment regarding release names, it is possible that you were in a situation where the settings were not pulled-in, specifically, when the release names changed.

**Comment by zcutlip** [comment]
This seems to be the case. When I pared my `~/.ghidra/` directory down to the following:
```
.ghidra-9.0.2/
.ghidra-9.0.4/
backup/
```
... and then run ghidra 9.1.1, I see nothing in `application.log` about merging existing tools.

**Comment by dragonmacher** [comment]
Should you ever wish to force the usage of an incompatible directory, you should be able to append the release name to an existing directory in order to convince Ghidra to use it.

**Comment by zcutlip** [comment]
Okay thanks.

It seems to be working more or less as expected now. I think I was confused by: 

- Being prompted to re-accept EULA
- Not reopening previously open project
- Possibly once instance in the past of actually failing to merge tool settings from 9.0.4 due to directory name.

And so I assumed settings had not been copied over. 

Not sure if failing to merge settings from 9.0.4 is a bug or not, but merging tool settings from 9.1_PUBLIC to 9.1.1_PUBLIC does seem to work.

**Comment by ryanmkurtz** [comment]
See #1328

**Comment by zcutlip** [comment]
Got it thanks. Closing this issue.
