### ISSUE TITLE
Selecting an instruction can highlight other instructions of the same type (excluding operands) for easy browsing of disassembly

### ISSUE THREAD

**Issue by BYEMAN** [NationalSecurityAgency/ghidra#144]
**Is your feature request related to a problem? Please describe.**
Not related to any problem I am aware of.

**Describe the solution you'd like**
In IDA, if you click on / place the cursor on an instruction (say, CALL), it will highlight all the other occurrences of that selection in yellow. This makes it easy to see all the calls in a function, for example. It would be nice if this were something that Ghidra could also do.

**Describe alternatives you've considered**
I've tried to get this to work by searching and other means, but haven't been able to get it to work like I wanted it to. It would be great if this could be implemented. After spending a bit of time with Ghidra, this is the only thing (admittedly a minor thing) that I miss about IDA.

**Comment by saruman9** [comment]
Clicking the middle mouse button will highlight all the other occurrences of instruction/operand/other. For changing the setting see `Edit -> Tool options... -> Listing Fields -> Cursor Text Highlight -> Mouse Button To Activate`.

**Comment by BYEMAN** [comment]
Great, thanks. This is exactly what I meant.

**Comment by MartinLeNizon** [comment]
How to make it work in the decompiler as well?
