### ISSUE TITLE
Memory segment overread when creating XML export .bytes file

### ISSUE THREAD

**Issue by mborgerson** [NationalSecurityAgency/ghidra#1442]
**Describe the bug**
When exporting a program to XML, a .bytes file containing the memory blocks/sections is also created. If the block currently being dumped is > 32KiB in length, and there is a second block directly following the current block, there may be an overread into the next block. The XML file reports the correct lengths of the blocks, so the data from the overread appears as padding in the file between adjacent blocks.

The root of the problem appears to be here, where there is a memory read bounded only by the chunking buffer size:
https://github.com/NationalSecurityAgency/ghidra/blob/6ae0c1ce239932882b7e4577d76ebd7d23779a09/Ghidra/Features/Base/src/main/java/ghidra/app/util/xml/MemoryMapXmlMgr.java#L397

On a block > 32KiB in size, subsequent reads in this chunking loop will always attempt to read into the 32KiB buffer. If there is no adjacent block, only the bytes remaining in the block will be returned. If there is a block adjacent however, the read may extend into that next block and it will be dumped to the file if the block range is not aligned to 32KiB.

**To Reproduce**
Have a binary file containing memory layout as described above. Import the binary, then run `File > Export Program...` and select XML.

**Expected behavior**
Dumping of memory blocks to a file should read only the block currently being dumped.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: 11.0
 - Ghidra Version: 9.1.1

**Additional context**
I have a need to redistribute the analysis of a binary, but prefer to not distribute the binary itself. I was creating a script that can reproduce the .bytes file given the original binary and discovered this unusual padding between blocks.

**Comment by dev747368** [comment]
@mborgerson - I'm not yet seeing a problem when exporting a binary, but I did run into an issue that might be related when I was resizing memory sections to create a binary to approximate your conditions.  The resize operation caused bad data to appear in the new memory ranges.

Could you give some exact sizes / layouts for your memory blocks?

**Comment by dev747368** [comment]
Closing.  This issue was probably fixed by various memory block fixes.  Feel free to reopen if you still have an issue.
