### ISSUE TITLE
Not correct highlighting in the decompiler window

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#1445]
**Describe the bug**
Element in the decompiler window sometimes not highlighted when you press middle button of mouse (or other button for highlighting), if you click again, than maybe element will be highlighted.

**To Reproduce**
1. Hover over the decompiler element (variable, for example).
2. Press middle mouse button.

**Expected behavior**
You should see all highlighted elements.

**Environment (please complete the following information):**
- OS: Linux 5.3.11
- Java Version: 13.0.1
- Ghidra Version: 6ae0c1ce239932882b7e4577d76ebd7d23779a09

**Additional context**
I found problem commit, is d307623f67f10598a7b787c480b337cde7907fca, but I think, that real problem in commits, that were made earlier.

**Comment by dragonmacher** [comment]
I am seeing a slightly odd behavior.  If I middle-mouse a datatype, I sometimes see that type highlight in all uses very briefly.  Then, after the cursor flashes, only the item under the cursor remains highlighted.
Does this sound similar to what you are seeing?

**Comment by saruman9** [comment]
Yes, everything is exactly as you described.
