### ISSUE TITLE
CParser does not work with a size_t prototype

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#1455]
Using the following `/tmp/test.h`:

```c
#include <stddef.h>
size_t foo(void);
```

And trying to parse it like this (here using `/bin/ls` as program):

![parse-size_t](https://user-images.githubusercontent.com/34467/72679596-fbb7c000-3ab0-11ea-80c1-dabcf4645da3.png)

...leads to the following error:

![2020-01-19-114150_428x171_scrot](https://user-images.githubusercontent.com/34467/72679599-0d00cc80-3ab1-11ea-90c2-07d803924e63.png)

`CParserPlugin.out` just contains the following:

```

#line 1: "/tmp/test.h"
 
#line 1: "/tmp/test.h"

size_t foo(void);

```

The issue is not present if I replace `size_t` with `int`.

It is on the other hand reproducible with `ssize_t`, `off_t`, `time_t`, `FILE`, ...

**Env**:
- Linux x86_64
- Ghidra 9.1.1

**Comment by astrelsky** [comment]
Is size_t defined? What about the define guards needed for size_t to be defined?

**Comment by ubitux** [comment]
> Is size_t defined? What about the define guards needed for size_t to be defined?
> 
> This should be helpful. https://stackoverflow.com/questions/2224334/gcc-dump-preprocessor-defines

It's not present as a define (because likely defined as compiler typedef), but I added my header at the end of the `generic_clib_64` headers (see screenshot), where `size_t` is actually defined if I look through the Data Type Manager.

**Comment by astrelsky** [comment]
> `CParserPlugin.out` just contains the following:
> 
> ```
> 
> #line 1: "/tmp/test.h"
>  
> #line 1: "/tmp/test.h"
> 
> size_t foo(void);
> ```

It doesn't seem like stddef.h is being parsed. The source filed marked in red indicate that they are not found.

**Comment by ubitux** [comment]
> It doesn't seem like stddef.h is being parsed. The source filed marked in red indicate that they are not found.

Right, but then how come it appears in the Data Type Manager under the same `generic_clib_64` I'm derivating?

**Comment by astrelsky** [comment]
> > It doesn't seem like stddef.h is being parsed. The source filed marked in red indicate that they are not found.
> 
> Right, but then how come it appears in the Data Type Manager under the same `generic_clib_64` I'm derivating?

You're using the parser profile that was used to create the archive, not the archive itself. If you are parsing to the program try copying size_t into the programs DataType manager and then see if it works.

**Comment by ubitux** [comment]
> You're using the parser profile that was used to create the archive, not the archive itself.

Of course, but if that specific parser profile was able to figure out `size_t` once, why can't it be done again?

> If you are parsing to the program try copying size_t into the programs DataType manager and then see if it works.

I can try as a workaround, but I already have one (adding `-Dsize_t="unsigned long"` and similar for other types). Even if what you propose works, it's still kind of broken.

**Comment by emteere** [comment]
Cuurently the cparser needs everything defined.  As a second pass,  the parsed types are matched against all open archives and made dependent on them.
An option to include open archives when looking up datatypes or the current programs datatypes if parsing directly into a program should be added.  There are drawbacks as the parsed datatypes could collide, so it should be an option.  Not having this option does make it difficult to quickly parse additional archives.

**Comment by therealchjones** [comment]
See #716
