### ISSUE TITLE
External references for raw binary

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#148]
**Describe the bug**
Functions from external programs in raw binary file dispayed in decompiler as `func_0x00009190` or `func_0x1`

**To Reproduce**
1. Load raw binary file (module of firmware), which contains calls of external functions.
2. Load additional raw binary file (shared library for modules of firmware) and set it as external program.
3. Open module of firmware in CodeBrowser and find undefined call of function
    ![2019-03-10_135341_579834901](https://user-images.githubusercontent.com/4244396/54084185-b4b05880-433e-11e9-8d4a-157b73f70093.png)

4. Add external reference for `CALL`
    ![2019-03-10_141449_360263728](https://user-images.githubusercontent.com/4244396/54084205-e75a5100-433e-11e9-840b-a691975a8cdd.png)

    ![2019-03-10_135238_373525765](https://user-images.githubusercontent.com/4244396/54084223-17a1ef80-433f-11e9-9627-f10ad7f31550.png)

    Name of function in decompiler:
    ![2019-03-10_135304_749179163](https://user-images.githubusercontent.com/4244396/54084228-2c7e8300-433f-11e9-8d6c-7d474dff3334.png)

    or
    1. Create new block of memory (addresses of shared library).
    2. Create reference in called function.
        ![2019-03-10_135605_340318275](https://user-images.githubusercontent.com/4244396/54084231-32746400-433f-11e9-9b62-32bb6ecc479f.png)

        Name of function in decompiler:
        ![2019-03-10_135615_665112316](https://user-images.githubusercontent.com/4244396/54084236-3bfdcc00-433f-11e9-83fa-b1300505f80d.png)

**Expected behavior**
Name of function in decompiler should be displayed as in external function. 

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Additional context**
How can I create external reference in idiomatic way for raw binaries? Adding external reference for all `CALL` (`JMP` and others) is a very time consuming process. Can I automate it without script?

How can I export functions (signatures too) from `Exports` of shared library to `Import` of module of firmware and synchronize them in future? I do it manually now: reverse engineering functions in shared library, then changing signatures in functions of `Imports` in module of firmware.

**Comment by saruman9** [comment]
I developed a script for temporary use. It find all references to functions from all external programs (shared libraries) and set external references, set name and prototype (signature) of functions.

[script.zip](https://github.com/NationalSecurityAgency/ghidra/files/2950093/script.zip)

![test](https://user-images.githubusercontent.com/4244396/54091733-88272b80-4394-11e9-87d0-a8c1f79f8b0e.gif)

**Comment by goosenphil** [comment]
Could you make the script into a PR?

**Comment by saruman9** [comment]
> Could you make the script into a PR?

I developed the script in the context of the project at work (NDA). When I finish the project, I will make a PR. While you can use prototype.

**Comment by saruman9** [comment]
As I promised, I'm publishing [the script for finding external references](https://gitlab.com/saruman9/ghidra_scripts/-/blob/master/FindExternalReferences.java) in raw binaries. It's far from ideal, but you can use it as example for developing more complex scripts/plugins.

**Comment by goosenphil** [comment]
> As I promised, I'm publishing [the script for finding external references](https://gitlab.com/saruman9/ghidra_scripts/-/blob/master/FindExternalReferences.java) in raw binaries. It's far from ideal, but you can use it as example for developing more complex scripts/plugins.

Thank you very much for this contribution :)
