### ISSUE TITLE
Win x64 calling convention: wrong XMM registers assignment

### ISSUE THREAD

**Issue by amineyosas1957** [NationalSecurityAgency/ghidra#1480]
Register assignment is incorrect for Windows x64 calling convention when a function accepts arguments of type `double` or `float`.

Here is the minimal example showing the problem:

```cpp
__declspec(noinline) __declspec(dllexport)
int func3(int a, double b, int c, float d) {
    return a * b + (int)(b / d);
}
```

Compile it with Visual C++ as `cl repro.cpp /LD`, then import resulting DLL into Ghidra with default settings, run default analysis.

Windows x64 calling convention is described on [this documentation page](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019#parameter-passing). Pay special attention to [example 3](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019#example-of-argument-passing-3---mixed-ints-and-floats), which reads:

    func3(int a, double b, int c, float d);
    // a in RCX, b in XMM1, c in R8, d in XMM3

This is what Ghidra deduces for this function:

```
   int    <RETURN> EAX:4
1  int    param_1  ECX:4
2  double param_2  XMM0_Qa:8
3  int    param_3  EDX:4
4  float  param_4  XMM1_Da:4
```

```cpp
/* int __cdecl func3(int,
                     double,
                     int,
                     float) 
   int __cdecl func3(int,double,int,float) */

int func3(int param_1,double param_2,int param_3,float param_4)

{
  undefined4 in_XMM1_Db;
  float in_XMM3_Da;
  
                    /* 0x1000  1  ?func3@@YAHHNHM@Z */
  return (int)((double)param_1 * (double)CONCAT44(in_XMM1_Db,param_4) +
              (double)(int)((double)CONCAT44(in_XMM1_Db,param_4) / (double)in_XMM3_Da));
}

```

**Environment:**
 - OS: Windows 7 x64
 - Java Version: 11.0.5
 - Ghidra Version: 9.0.4 2019-May-16 1545 EDT

**P.S.** I have got used to switching all encountered functions with double arguments to "Use Custom Storage" and fixing register assignments. But now I'd like to make decompiler understand virtual function calls using the manual approach described [here](https://github.com/NationalSecurityAgency/ghidra/issues/516#issuecomment-487051576) (from #516), and it turns out that I cannot define custom register assignment for a function pointer type (reported as #1436).

**Comment by coldino** [comment]
Can confirm this is still a significant issue on 9.2.3.
