### ISSUE TITLE
Python ghidra script doesn't "allow" copyright header

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1484]
**Describe the bug**
Adding a copyright header to a python script causes the description, category, author, keybinding, etc so not be parsed.

**To Reproduce**
1. Create a useful ghidra script in python.
2. Add description, category, author, etc.
3. Add copyright header.
4. Notice loss of description, category, etc.

**Expected behavior**
The copyright header should be ignored just like a ghidra script written in Java.

**Environment (please complete the following information):**
 - Java Version: 13.0.2
 - Ghidra Version: 9.2

**Additional context**
Repeatable examples [here](https://github.com/astrelsky/ghidra_scripts)

**Comment by dragonmacher** [comment]
I think this has been fixed by 0f235d029c75e2e

**Comment by astrelsky** [comment]
> I think this has been fixed by [0f235d0](https://github.com/NationalSecurityAgency/ghidra/commit/0f235d029c75e2ed55cc819c0c4ebc7c17fa617f)

https://github.com/NationalSecurityAgency/ghidra/blob/bda7e0df453fca4c8df51e898404ed6e5314ec61/Ghidra/Features/Python/src/main/java/ghidra/python/PythonScriptProvider.java#L49-L57

What if someone does this though?
```python
""""
"Block Comment" Here
"""
```
