### ISSUE TITLE
Reducing single jar size

### ISSUE THREAD

**Issue by sgboyd** [NationalSecurityAgency/ghidra#1487]
Is there any documentation on how to reduce the size of Ghidra when using it as a single jar?

I have done a lot of googling but not really been able to find much. 

I don't really need much other than its disassembly abilities but I am not sure what I can and can't leave out.

**Comment by ghidra1** [comment]
The BuildGhidraJarScript can be modified to include/exclude specific modules. 
Modules from Features can certainly be reduced to essential modules required for your use.  This script is intended be run from an installed build of Ghidra and may not work properly from a Ghidra development layout.

Module dependencies will dictate which modules can safely be omitted.  This is most easily determined within a Ghidra development environment using Eclipse where Processor and Feature projects can be turned on/off until the desired mix is achieved.

**Comment by sgboyd** [comment]
Yeah, I read that in the documentation but it's not really that helpful. I was looking for something more.

**Comment by ghidra1** [comment]
If you intend on performing full auto-analysis about the only modules you should omit are processors you do not need, GUI-only Feature modules (e.g.,  FunctionGraph, FunctionGraphDecompilerExtension, GraphFunctionCalls, ProgramDiff, SourceCodeLookup, VersionTracking), and the GhidraServer module.

If you will not be using the GUI you can always prune more from the resulting jar file (e.g., help, docs, etc.).
