### ISSUE TITLE
errors resolving mach-o indirect symbols 

### ISSUE THREAD

**Issue by zcutlip** [NationalSecurityAgency/ghidra#1496]
**Describe the bug**
On a toy mach-o, x86_64  "hello world" program, Ghidra resolves imported symbols incorrectly.

**To Reproduce**
1. Disassemble my 'hello' program
2. Go to imports such as `__TEXT,__stubs` or `__DATA_CONST,__got`, and see that those names are not resolved correctly
For example the stub for `printf()` gets resolved as `__call_block_invoke`, and the stub for `free()` gets resolved as `dyld_stub_binder`.

The screenshots below show Ghidra's name resolution.

__TEXT,__stubs:
<img width="836" alt="__TEXT __stubs" src="https://user-images.githubusercontent.com/2158303/73578570-d625a180-4434-11ea-9356-dc5c25ba05fa.png">

__DATA_CONST,__got:
<img width="663" alt="__DATA_CONST __got" src="https://user-images.githubusercontent.com/2158303/73578593-df167300-4434-11ea-86b7-7d0764112c04.png">

__DATA,__la_symbol_ptr
<img width="721" alt="__DATA __la_symbol_ptr" src="https://user-images.githubusercontent.com/2158303/73578608-e9d10800-4434-11ea-8adf-86f7ba5bdb91.png">

**Expected behavior**
Running displaying the indirect symbols using `objdump` shows the expected symbol name resolution:
```
$ objdump -macho -indirect-symbols hello
hello:
Indirect symbols for (__TEXT,__stubs) 3 entries
address            index name
0x0000000100000f5e     7 _free
0x0000000100000f64     8 _printf
0x0000000100000f6a     9 _strdup
Indirect symbols for (__DATA_CONST,__got) 2 entries
address            index name
0x0000000100001000     6 __NSConcreteStackBlock
0x0000000100001008    10 dyld_stub_binder
Indirect symbols for (__DATA,__la_symbol_ptr) 3 entries
address            index name
0x0000000100002000     7 _free
0x0000000100002008     8 _printf
0x0000000100002010     9 _strdup
```

**Attachments**
Zipped `hello` binary executable is attached.
[hello.zip](https://github.com/NationalSecurityAgency/ghidra/files/4141637/hello.zip)

**Environment (please complete the following information):**
 - OS: macOS 10.15.3 (19D76)
 - Java Version: OpenJDK 13.0.2
 - Ghidra Version: 9.1.1

**Comment by zcutlip** [comment]
Actually I just realized this is probably a dupe of #1446

**Comment by GhidorahRex** [comment]
Yep, this looks like a duplicate of #1446

**Comment by arandomdev** [comment]
This still seems to be an issue for me on version 9.1.2. Various calls to objc_sendmsg are mislabeled. Am I missing a setting or something?
