### ISSUE TITLE
issued during analysis mt2iq bot

### ISSUE THREAD

**Issue by xan911** [NationalSecurityAgency/ghidra#150]
pdb> incomplete pdb information (GUID/Signature and/or age) associated with this program Either the program is not a PE
or it was not compiled with debug information windows x86 PE RTTI Analyzer> couldn't find type info structure

![error ghidra](https://user-images.githubusercontent.com/46980747/54088878-ffc76d00-4338-11e9-8af6-d7339a1f981b.png)

**Comment by alfrrr** [comment]
Not an issue. When prompted to analyze, inside _Analysis Options_ window untoggle the PDB

**Comment by xan911** [comment]
hello

I did that untoggle the PDB but now show this and decompile don't work

[image: image.png]

**Comment by emteere** [comment]
The message is just a warning there is no pdb information for the PE.  I'M HOME it shouldn't be displayed.
