### ISSUE TITLE
How to access ELF format methods from a GhidraScript

### ISSUE THREAD

**Issue by niemand108** [NationalSecurityAgency/ghidra#1500]
I am trying to access the ELF from a GhidraScript and I am wondering is there any direct way to access the Dynamic Symbol Table or the ELF sections. I have thought that the solution is to create a new ELF using the package "ghidra.app.util.bin.format.elf.ElfHeader" but I find it is a bit redundant. I have tried to do it from the ELFLoader and all the paths lead me to the same thing: create the ELF again from the ByteProvider.

**Comment by astrelsky** [comment]
> I am trying to access the ELF from a GhidraScript and I am wondering is there any direct way to access the Dynamic Symbol Table or the ELF sections. I have thought that the solution is to create a new ELF using the package "ghidra.app.util.bin.format.elf.ElfHeader" but I find it is a bit redundant. I have tried to do it from the ELFLoader and all the paths lead me to the same thing: create the ELF again from the ByteProvider.

Unfortunately I don't think so. Even the dwarf parser takes the route of reopening the program, get a byte provider and then create a new ElfHeader.
