### ISSUE TITLE
dsPIC30F program space strings

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1507]
I compiled a simple dsPIC30F binary using the following code:
```
#include <stdio.h>

__prog__ const char __attribute__((space(prog))) str[] = "Hello!";

int main() {
    printf("%s\n", str);
}
```
Because I am forcing the string into program space, it ends up looking like this in Ghidra:

![ss](https://user-images.githubusercontent.com/5378554/73675863-40328680-4681-11ea-99f6-197fb260b9a7.png)

Note the extra 0x00's in between some of the string's characters.  This is due to the weird size and wordsize of the PIC program (ROM) space.  Is there any way for Ghidra's string datatype to be made aware of these various features of the address space the string is contained in?  Similar question for the string search feature.

**Comment by ghidra1** [comment]
This is the result of the dsPIC30F Harvard Architecture and mapped memory space regions.  The string you show in program memory [rom] is in reality accessed via the data space [ram] which does not map byte-for-byte.  While Ghidra does not currently offer a suitable memory space/block mapping scheme to produce the corresponding data blocks in the [ram] space this could certainly be scripted to generate such memory blocks from corresponding program memory [rom] bytes and symbols.

**Comment by ryanmkurtz** [comment]
That makes sense...thanks!
