### ISSUE TITLE
NullPointerException when running any Python script

### ISSUE THREAD

**Issue by carlmiller307** [NationalSecurityAgency/ghidra#1513]
---
name: NullPointerException when running any Python script
about: When attempting to run the attached Python script, or indeed any Python script, in Ghidra, a NullPointerException matching the output attached is thrown.
title: 'NullPointerException when running any Python script'
labels: bug
assignees: ''

---

**Describe the bug**
When attempting to run [the attached Python script](https://github.com/NationalSecurityAgency/ghidra/files/4156108/ApplySig.py.txt), or indeed any Python script, in Ghidra, a NullPointerException matching [the output attached](https://github.com/NationalSecurityAgency/ghidra/files/4156104/exception.txt) is thrown.

**To Reproduce**
1. Open the Script Manager window.
5. Select a Python script.
6. Press the “Run Script” button.
7. See the error.

**Expected behavior**
I expected [the attached script](https://github.com/NationalSecurityAgency/ghidra/files/4156108/ApplySig.py.txt) to import FLIRT signatures for Nintendo 64 SDK functions into Ghidra to aid in decompiling N64 games.

**Screenshots**
No applicable screenshots.

**Attachments**
[One of the scripts that I was trying to run](https://github.com/NationalSecurityAgency/ghidra/files/4156108/ApplySig.py.txt), and [the error message Ghidra throws](https://github.com/NationalSecurityAgency/ghidra/files/4156104/exception.txt), are attached.

**Environment (please complete the following information):**
 - OS: Sparky Linux Stable 5.10 amd64 (based on Debian 10 “Buster”)
 - Java Version: AdoptOpenJDK 13.0.2
 - Ghidra Version: 9.1.1

**Additional context**
Python 2 and 3 are both installed, as they are each required by varying parts of my system.

**Comment by astrelsky** [comment]
I've had this occur a few times but have never been able to consistently reproduce it. Does it occur if you try running the script after restarting ghidra?

**Comment by carlmiller307** [comment]
Yes, it does; indeed it occurs all of the time for me.

**Comment by astrelsky** [comment]
> Yes, it does; indeed it occurs all of the time for me.

The attached script ran without a problem for me. May you attach the application.log file? It may be found in `$HOME/.ghidra/.ghidra_9.1.1_PUBLIC`. Since you can consistently reproduce this it may be helpful to move the existing log, reproduce the issue and then attach the new log since it'll be much shorter.

What happens when opening the Python window in ghidra? Also, the python ghdra is using is Jython and not a system installed python.

**Comment by carlmiller307** [comment]
[Here is application.log.](https://github.com/NationalSecurityAgency/ghidra/files/4161278/application.log)

**Comment by dragonmacher** [comment]
Looking at the stack trace, it appears as though the real exception is being masked by the Python code.  Specifically, 
   `at org.python.core.Py.dispatchToChecker(Py.java:2490)`  

is generating a `NullPointerException` while Ghidra is in the process of reporting a different exception.   

Debugging this by putting a breakpoint at the above line will allow you to see the original exception.

**Comment by carlmiller307** [comment]
I'm afraid to state it here for fear of being yelled at or simply run out of town on a rail, but I don't know how to do that. I am a complete know-nothing when it comes to Java development and little better when it comes to programming in general. Additionally, I am unable to figure out for myself how to set breakpoints within Ghidra itself, and I cannot even find a file named `Py.java` within either the latest release or the current source code of Ghidra. :(

**Comment by carlmiller307** [comment]
I'm afraid to admit it for fear of ridicule, but I don't know how to do that.

**Comment by dragonmacher** [comment]
No worries.  Quite a few of our users are not Java developers.   My previous message was really a note for the community at large.    Naturally, those of us not experiencing the problem cannot debug it.  My hope is that someone else will eventually run into the same issue and then be able to debug it.

As a reference, for those so interested,  Ghidra does integrate well with the Eclipse IDE.   If you run Ghidra from within Eclipse, then you can debug to your heart's content.

**Comment by carlmiller307** [comment]
While asking an N64 decompilation Discord server that I'm on about how to debug Ghidra itself, I noted that I couldn't find `Py.java` in the source or `Py.class` in the binary, and was told that it might be a Gradle dependency, whereupon I realized that Jython might be an external dependency. Naïvely, I ran to my package manager\* and installed Jython, which also pulled down Oracle Java 11; not only does Ghidra run, but I'm no longer getting the errors, so I assume it was related to Jython not being present. \*shrug\*

(\* As noted earlier, I was using AdoptOpenJDK 13.0.2 instead of the Oracle Java 11 provided by Debian Buster's package manager; this was out of a (likely mistaken) belief that Ghidra requires Java 12 or newer.)

**Comment by astrelsky** [comment]
> While asking an N64 decompilation Discord server that I'm on about how to debug Ghidra itself, I noted that I couldn't find `Py.java` in the source or `Py.class` in the binary, and was told that it might be a Gradle dependency, whereupon I realized that Jython might be an external dependency. Naïvely, I ran to my package manager* and installed Jython, which also pulled down Oracle Java 11; not only does Ghidra run, but I'm no longer getting the errors, so I assume it was related to Jython not being present. *shrug*
> 
> (* As noted earlier, I was using AdoptOpenJDK 13.0.2 instead of the Oracle Java 11 provided by Debian Buster's package manager; this was out of a (likely mistaken) belief that Ghidra requires Java 12 or newer.)

Check for files in `Ghidra/Features/Python/lib` path is relative to the ghidra installation directory.

**Comment by carlmiller307** [comment]
> Check for files in Ghidra/Features/Python/lib path is relative to the ghidra installation directory.

``` ~/D/g/G/F/P/lib  ls -lahc                                                                                                                                                                                    Wed 05 Feb 2020 05:28:36 PM EST
total 40M
drwxr-xr-x 2 halian halian 4.0K Feb  3 22:19 ./
drwxr-xr-x 5 halian halian 4.0K Feb  3 22:19 ../
-rwxr-xr-x 1 halian halian  40M Feb  3 22:18 jython-standalone-2.7.1.jar*
-rw-r--r-- 1 halian halian 106K Feb  3 22:18 Python.jar
-rw-r--r-- 1 halian halian  24K Feb  3 22:18 Python-src.zip
 ~/D/g/G/F/P/lib  unzip Python-src.zip                                                                                                                                                                        Wed 05 Feb 2020 05:28:37 PM EST
Archive:  Python-src.zip
   creating: ghidra/
   creating: ghidra/python/
  inflating: ghidra/python/PythonScriptExecutionThread.java  
  inflating: ghidra/python/PyDevUtils.java  
  inflating: ghidra/python/PythonRun.java  
  inflating: ghidra/python/PythonPluginExecutionThread.java  
  inflating: ghidra/python/PythonScript.java  
  inflating: ghidra/python/GhidraPythonInterpreter.java  
  inflating: ghidra/python/PythonPlugin.java  
  inflating: ghidra/python/PythonUtils.java  
  inflating: ghidra/python/PythonPluginInputThread.java  
  inflating: ghidra/python/PythonScriptProvider.java  
  inflating: ghidra/python/PythonCodeCompletionFactory.java  ```

**Comment by dragonmacher** [comment]
Closing, as this seems resolved.  Feel free to post any additional relevant details.
