### ISSUE TITLE
CR16C LOAD/STOR with abs20 operand not remapped correctly

### ISSUE THREAD

**Issue by The6P4C** [NationalSecurityAgency/ghidra#1518]
**Describe the bug**
LOAD/STOR instructions on CR16C with an abs20 operand greater than `0xEFFFF` are not OR'd with the required constant `0xF00000`.

This is due to [an error in the CR16C sinc file (line 288)](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/CR16/data/languages/CR16C.sinc#L288) where the boundary is specified as `0xEFFFFF` rather than `0xEFFFF` (one nibble too wide).

**To Reproduce**
1. Disassemble CR16C code which utilises a LOAD/STOR instruction with an abs20 operand greater than `0xEFFFF`.
2. Observe that the required constant `0xF00000` is not OR'd with the operand to generate the correct address.

**Screenshots**
The LOADB instruction specifies an abs20 operand of `0xFFD8C` which should become an address of `0xFFFD8C`, however the correct OR mask is not applied due to the incorrect boundary constant.

![](https://user-images.githubusercontent.com/7885480/73912764-17b8bf80-4901-11ea-9604-b3bf74fa1ed1.png)

**Comment by GhidorahRex** [comment]
I've got a fix I'm working on. The sample you posted disassembles correctly. If you would be willing to, could you verify the fix on a binary that demonstrates the problem?

Replace the abs20: subconstructor on line 290 with the following:
`abs20:  tmp     is n5=0xf & dw_w2       [ tmp = 0xff0000 | dw_w2; ]   { 
    export *[const]:3 tmp; 
}

abs20:  tmp     is n5 & dw_w2       [ tmp = (n5 << 16) + dw_w2; ]   { 
    export *[const]:3 tmp; 
}`

**Comment by The6P4C** [comment]
Thanks - appears to work perfectly for both high and low abs20 values. I don't have any other CR16C binaries I can test on but everything appears fine re-disassembling the original binary.

![](https://user-images.githubusercontent.com/7885480/73996107-6c624600-49a6-11ea-9ccd-836c5fbe8aea.png)
