### ISSUE TITLE
Trouble with Endianness

### ISSUE THREAD

**Issue by tahg** [NationalSecurityAgency/ghidra#1519]
Probably the same issue as #1422 

I have a definition for a MOV instruction that I've had to define as follow:

:MOV [rs+imm3],rd is (op2_7=0x4d & rd & rs & imm3) {
	*:1 (rs+imm3) = rd[24,8];
}

It's the same situation as in the other issue issue.  Big endian instruction decode, Little endian memory.  In ldefs I've set endian="little", and instructionEndian="big". In the sinc I've done define endian=big.  This largely works, as instructions are fairly straightforward to implement, and Ghidra treats multibyte data in the memory correctly.  The above makes the decompiler use the right byte of the register.

My question really then, is this going to cause any issues for me down the line where bytes might be in the wrong order? Should I instead treat the whole thing as little endian, and just do the combine myself when I have multibyte values in instructions?

**Comment by tahg** [comment]
I had originally thought this was an issue with how SUBPIECE works, as the docs say that is the p-code equivalent to :x, (x) and [x,n], however the compiled sla seems to do it entirely with STORE, not using SUBPIECE at all.

**Comment by agatti** [comment]
@tahg how did you get it working this far? I spent some time playing the endianness flags and giving up after a while but without getting anywhere, really.

**Comment by ghidra1** [comment]
The data endianess in ldefs must match the slaspec 'set endian'.  The ldef instruction endianess setting is a runtime indicator which impacts instruction token byte ordering only.  I believe you should use 'set endian=little' in the slaspec.

**Comment by ghidra1** [comment]
Is this still an issue for you?  Can this ticket be closed?
