### ISSUE TITLE
Key binding for the Data "Recently Used" action is reset on startup

### ISSUE THREAD

**Issue by xyzz** [NationalSecurityAgency/ghidra#152]
**Describe the bug**
The key binding for the Data "Recently Used" action (RecentlyUsedAction.java) (from context menu `Data`->`Last Used`) is reset between restarts.

**To Reproduce**
1. Go to `Edit`->`Tool Options`->`Key Bindings`
2. Search for "Recently Used"
3. Remove the keybinding or set a different key
4. Observe that the new keybinding is used
5. Restart CodeBrowser
6. Observe that the default keybinding is used again (`Y`)

**Expected behavior**
The key binding setting is kept between restarts.

**Environment (please complete the following information):**
 - OS: Windows 7
 - Java Version: 11.0.2
 - Ghidra Version: 9.0

**Comment by ryanmkurtz** [comment]
This will be fixed in our next release.
