### ISSUE TITLE
How to use search memory in script?

### ISSUE THREAD

**Issue by carnifexV2** [NationalSecurityAgency/ghidra#1524]
Hi,

is it possible to use the search memory feature in a script?

	class Test {
		String name;
		String hex;

		public Test(String n, String h) {
			name = n;
			hex = h;
		}
	}

	@Override
	public void run() throws Exception {
		ArrayList<Test> testList = new ArrayList<Test>();

		testList.add(new Test("test1", "48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 85 C0 74 3B 45 33 C9"));

		testList.forEach(t -> println(t.name + " -> " + SearchMemory(t.hex)));

	}

	private String SearchMemory(String hex) {
               // search..

		return "value or not found";
	}

**Comment by ryanmkurtz** [comment]
Check out the findBytes() methods in the GhidraScript/FlatProgramAPI.

**Comment by carnifexV2** [comment]
Thank you! Got it to work.

Can you disassemble that address? Or get the output of Disassembled View?
I've found DisassembleCommand and PseudoDisassembler. 
Not sure how to use this, though.

**Comment by quosego** [comment]
@carnifexV2 you could also check out a program I made a while back to create signatures:
https://github.com/Randshot/ghidra.fizz

It may help you.

https://github.com/Randshot/ghidra.fizz/blob/master/Fizz/src/main/java/ghidra/utilities/memory/MemorySignature.java

**Comment by carnifexV2** [comment]
Thank you for your reply.
To be honest i kind of forgot about that issue.
I figured it out myself, with the help of some other scripts.
This is for sure not the best solution, but it does what i want it to.

This is my first java code and GhidraScript so be gentle.

`import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;
import ghidra.program.flatapi.FlatProgramAPI;
import ghidra.program.disassemble.*;
import ghidra.util.task.ConsoleTaskMonitor;
import ghidra.app.util.importer.MessageLog;
import ghidra.app.util.PseudoData;
import ghidra.program.model.mem.DumbMemBufferImpl;
import java.util.ArrayList;

public class FindWowOffsets extends GhidraScript {

	class AoB {
		String name;
		String bytesStr;

		public AoB(String n, String h) {
			name = n;
			bytesStr = h;
		}
	}

	Address lastAddress;
	ArrayList<AoB> testList = new ArrayList<AoB>();

	@Override
	public void run() throws Exception {
		AddAoB("test", "48 8D 0D ? ? ? ? E8 ? ? ? ? 48 85 C0 74 3B 45 33 C9");

		testList.forEach(t -> println(t.name + " -> " + GetAddress(t.bytesStr)));
	}

	private void AddAoB(String name, String bytesStr){
		testList.add(new AoB(name, bytesStr));
	}

	private String GetAddress(String hex) {
		Address addr = GetMemoryAddress(hex);

		return DisassembleAddress(addr);
	}

	private String DisassembleAddress(Address addr) {
		String notFound = "not found";

		if (addr.equals(null))
			return notFound;

		try {
			Disassembler disassembler = Disassembler.getDisassembler​(currentProgram, getMonitor(), DisassemblerMessageListener.CONSOLE);
			var region = currentProgram.getMemory().getLoadedAndInitializedAddressSet().intersectRange(addr, addr);

			DumbMemBufferImpl memBuffer = new DumbMemBufferImpl(currentProgram.getMemory(), region.getMinAddress());

			var lastPseudoInstructionBlock = disassembler.pseudoDisassembleBlock(memBuffer, null, 1);

			String instruction = lastPseudoInstructionBlock.getInstructionAt​(addr).getDefaultOperandRepresentation​(1);

			lastAddress = addr;

			return instruction;
		} catch (Exception e) {
		}

		return notFound;
	}

	private Address GetMemoryAddress(String hex) {
		try {
			return findBytes(lastAddress, BuildRegexStrFromHexStr(hex));
		} catch (Exception e) {
		}

		return null;
	}

	private String BuildRegexStrFromHexStr(String hex) {
		String[] splitStr = hex.trim().split("\\s+");
		String ret = "";
		int counter = 0;

		for (int i = 0; i < splitStr.length; i++) {

			if (splitStr[i].equals("?")) {
				counter++;
			} else {
				if (counter > 0) {
					ret += ".{0," + counter + "}";
					counter = 0;
				}

				ret += "\\x" + splitStr[i];
			}
		}

		return ret;
	}
}`
