### ISSUE TITLE
Decompilation of MIPS LWL/LWR/SWL/SWR doesn't work

### ISSUE THREAD

**Issue by Arcnor** [NationalSecurityAgency/ghidra#153]
**Describe the bug**
When LWL/LWR/SWL/SWR instructions are found, the decompilation just ignores the code it should generate for them.

As you can see on the example, the first line of generated code is at `0x80020efc`, while all the code before that is ignored (it should be many consecutive assignments to the `local_20` array and other places)

![Ghidra_Bug](https://user-images.githubusercontent.com/28616/54092599-fdd7cb00-4385-11e9-8f12-a5de3210c0bc.jpg)

**Environment (please complete the following information):**
 - OS: macOS 10.14.2
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Comment by emteere** [comment]
What can see occurring between the red/green arrow is loads from your structure into local variables on the stack.  Those loads may be seen to have no result and may be removed from the code as having no effect, or the effect or usage may be further in the function.  If a fals if jumps around any usage of the stored locals within the if block, then the decompiler will remove them as dead code since they have no lasting effect.

You can try turning off the dead code removal in Edit->ToolOptions->Decompiler->analysis. to see if that reveals anything.

If this doesn't solve your issue, copy/pasting the byte string for the function, will make it easier to diagnose.

**Comment by Arcnor** [comment]
Thanks for your response.

I've tried disabling the dead code elimination, but nothing has changed, at all (which is strange, I was hoping to see things like the stores to the stack on the prelude of the function, for example). I tried reanalyzing and pressing on the Refresh, but no changes were seen.

Not sure what you mean by the "byte string", I guess you mean the bytes from the function? I can certainly do that, or if you have some way for me to send you the DB/binary I can also do that.

Thanks again.

**Comment by emteere** [comment]
You can select the bytes of the function, then choose copy special...->byteString from the pop-up menu in the listing.

If you create a data type on the stack that covers the locations that are loaded, and then the data type is passed to a function, I believe the Decompiler will show the data loads.  I would need to see the rest of the function to be sure how the bytes on the stack are actually used.

**Comment by Arcnor** [comment]
There you go (however, what you describe is actually what's happening, more or less, the stack has a type & size (`byte[20]`) and the variable is being used as an array)

Here is the full decompilation:

```
void func(char *buf,ushort size,ushort sceneId)

{
  uint sceneId_32bit;
  uint index_32bit;
  ushort index;
  byte local_20 [32];
  
  if (0x1f < sceneId) {
    do {
      sceneId -= 0x20;
    } while (0x1f < sceneId);
  }
  index = 0;
  if (size != 0) {
    index_32bit = 0;
    do {
      sceneId_32bit = (uint)sceneId;
      sceneId += 1;
      buf[index_32bit] = buf[index_32bit] ^ local_20[sceneId_32bit];
      index += 1;
      if (0x1f < sceneId) {
        sceneId = 0;
      }
      index_32bit = (uint)index;
    } while (index < size);
  }
  return;
}
```

And here is the full byte string:

```
e0 ff bd 27 21 40 80 00 21 38 c0 00 01 80 06 3c 80 0f c6 24 03 00 c2 88 00 00 c2 98 07 00 c3 88 04 00 c3 98 0b 00 c4 88 08 00 c4 98 03 00 a2 ab 00 00 a2 bb 07 00 a3 ab 04 00 a3 bb 0b 00 a4 ab 08 00 a4 bb 0f 00 c2 88 0c 00 c2 98 13 00 c3 88 10 00 c3 98 17 00 c4 88 14 00 c4 98 0f 00 a2 ab 0c 00 a2 bb 13 00 a3 ab 10 00 a3 bb 17 00 a4 ab 14 00 a4 bb 1b 00 c2 88 18 00 c2 98 1f 00 c3 88 1c 00 c3 98 1b 00 a2 ab 18 00 a2 bb 1f 00 a3 ab 1c 00 a3 bb ff ff e2 30 20 00 42 2c 09 00 40 14 21 30 e0 00 e0 ff 03 34 21 38 e3 00 ff ff e2 30 20 00 42 2c fd ff 40 10 21 38 e3 00 23 38 e3 00 21 30 e0 00 ff ff a5 30 13 00 a0 10 21 38 00 00 ff ff e4 30 21 20 04 01 ff ff c2 30 21 18 a2 03 00 00 82 90 00 00 63 90 01 00 c6 24 26 10 43 00 00 00 82 a0 ff ff c2 30 20 00 42 2c 02 00 40 14 01 00 e7 24 21 30 00 00 ff ff e2 30 2b 10 45 00 f0 ff 40 14 ff ff e4 30 20 00 bd 27 08 00 e0 03 00 00 00 00
```

**Comment by 3789037** [comment]
Currently discussing this issue in the responses to my tweet here. Extremely similar to an issue I experienced on powerpc, I do not think it is architecture specific. I expect when we figure it out it may warrant a documentation clarification... 

https://twitter.com/0x9268FE/status/1107116827241517056

**Comment by 3789037** [comment]
![image](https://user-images.githubusercontent.com/29120895/54496282-ed62ab80-48c3-11e9-82b9-5e03c602be83.png)

something is really wrong here, but I am not seeing anything incorrect in the sleigh or pcode

**Comment by Arcnor** [comment]
So it looks like another function that also heavily uses `LWL/LWR` pairs (and their counterpart) is working properly.

<img width="1393" alt="Screen Shot 2019-03-17 at 20 45 15" src="https://user-images.githubusercontent.com/28616/54497678-9970ba80-48f5-11e9-927f-933c89d27833.png">

This is the function byte string, in case it's useful:

```
80 bf bd 27 6c 40 b5 af 90 40 b5 8f 01 80 02 3c ec 0d 42 24 7c 40 bf af 78 40 be af 74 40 b7 af 70 40 b6 af 68 40 b4 af 64 40 b3 af 60 40 b2 af 5c 40 b1 af 58 40 b0 af 03 00 43 88 00 00 43 98 07 00 48 88 04 00 48 98 0b 00 49 88 08 00 49 98 0f 00 4a 88 0c 00 4a 98 1b 00 a3 ab 18 00 a3 bb 1f 00 a8 ab 1c 00 a8 bb 23 00 a9 ab 20 00 a9 bb 27 00 aa ab 24 00 aa bb 13 00 43 88 10 00 43 98 17 00 48 88 14 00 48 98 18 00 49 80 19 00 4a 80 2b 00 a3 ab 28 00 a3 bb 2f 00 a8 ab 2c 00 a8 bb 30 00 a9 a3 31 00 aa a3 03 00 43 88 00 00 43 98 07 00 48 88 04 00 48 98 0b 00 49 88 08 00 49 98 0f 00 4a 88 0c 00 4a 98 3b 00 a3 ab 38 00 a3 bb 3f 00 a8 ab 3c 00 a8 bb 43 00 a9 ab 40 00 a9 bb 47 00 aa ab 44 00 aa bb 13 00 43 88 10 00 43 98 17 00 48 88 14 00 48 98 18 00 49 80 19 00 4a 80 4b 00 a3 ab 48 00 a3 bb 4f 00 a8 ab 4c 00 a8 bb 50 00 a9 a3 51 00 aa a3 30 00 c6 24 30 00 84 24 21 b8 a0 00 21 f0 e0 00 1a 00 a6 a3 74 7c 00 0c 3a 00 a4 a3 18 00 b0 27 ff ff 42 30 04 00 40 14 38 00 b4 27 02 00 02 34 61 85 00 08 06 00 a2 a6 01 00 04 34 0b 00 05 34 26 00 06 34 0f 00 07 34 01 00 02 34 39 69 00 0c 10 00 a2 af 01 80 04 3c b0 0f 84 24 0c 00 05 34 0d 00 06 34 21 38 00 00 ff ff 12 24 fe 53 00 0c 10 00 b2 af d1 8d 00 0c 0a 00 04 34 2d 55 00 0c 00 00 00 00 21 20 00 02 59 ff 00 0c 01 00 05 34 21 80 40 00 21 20 00 02 58 00 b1 27 21 28 20 02 5d ff 00 0c 00 20 06 34 65 ff 00 0c 21 20 00 02 d1 8d 00 0c 0a 00 04 34 21 20 80 02 59 ff 00 0c 01 00 05 34 21 98 40 00 21 b0 20 02 2d 00 72 16 ff ff 11 24 58 20 b0 27 21 20 00 02 21 28 00 00 88 60 00 0c 00 20 06 34 21 20 00 02 06 80 05 3c 38 20 a5 24 46 60 00 0c 00 02 06 34 21 20 80 02 01 00 05 3c 59 ff 00 0c 00 02 a5 34 21 98 40 00 08 00 71 16 00 00 00 00 3d 55 00 0c 00 00 00 00 bb 7c 00 0c 05 00 04 34 03 00 02 34 61 85 00 08 06 00 a2 a6 65 ff 00 0c 21 20 60 02 d1 8d 00 0c 05 00 04 34 21 20 80 02 59 ff 00 0c 02 00 05 34 21 98 40 00 21 20 60 02 21 28 00 02 61 ff 00 0c 00 20 06 34 65 ff 00 0c 21 20 60 02 d1 8d 00 0c 0a 00 04 34 21 20 80 02 59 ff 00 0c 01 00 05 34 21 98 40 00 21 20 60 02 58 20 b0 27 21 28 00 02 5d ff 00 0c 00 20 06 34 65 ff 00 0c 21 20 60 02 d1 8d 00 0c 0a 00 04 34 38 00 a4 27 59 ff 00 0c 02 00 05 34 21 98 40 00 ff ff e4 32 40 21 04 00 00 02 84 24 21 20 04 02 ff ff c5 33 40 29 05 00 00 02 a5 24 21 28 c5 02 46 60 00 0c 20 00 06 34 21 20 60 02 21 28 00 02 61 ff 00 0c 00 20 06 34 65 ff 00 0c 21 20 60 02 3d 55 00 0c 06 00 a0 a6 01 00 04 34 0b 00 05 34 26 00 06 34 f1 69 00 0c 0f 00 07 34 7c 40 bf 8f 78 40 be 8f 74 40 b7 8f 70 40 b6 8f 6c 40 b5 8f 68 40 b4 8f 64 40 b3 8f 60 40 b2 8f 5c 40 b1 8f 58 40 b0 8f 80 40 bd 27 08 00 e0 03 00 00 00 00
```

**Comment by 3789037** [comment]
The big difference I can find is that the target of the LWX/SWX instruction sequence is accessed as a byte array in the failig function,  and only passed as a pointer to a callee in the working function.
The decompiler/autoanalysis assigns local_20 to a byte array in the former without manual annotation. might be related might not? 

Also looking at the rest of the failure case, it looks like a general failure of local variable analysis, and there are other operations missing from the output. It _does_ display a complaint if the globals accessed in the hidden code overlap, so it seems to be at least processing those instructions

Even by (attempting to) manually set register references and types, the decompiler still fails
![image](https://user-images.githubusercontent.com/29120895/54497892-83073680-48d6-11e9-80ea-d10b33d4e16b.png)

**Comment by emteere** [comment]
You are right the decompiler is not displaying the initialization as it should.  I suspect if the pointer were passed to a function the initialization might show up, but I can't confirm that.

I suspect it has more to do with an aliasing problem in the decompiler or stack save/restore dead code removal.  The LWR/SWR are pair instructions used to access possibly un-aligned pointers when normal instruction loads can't access unaligned memory.  So they need to be handled in pairs when they appear that way so that the pcode is sane.  Implementing the LWR/SWR instructions in full pcode causes complexity that normally doesn't matter in code.  So I don't think that is the issue.

I did duplicate your issues and tried numerous ways to force the decompiler to include the loads into the stack based array.  You can even try setting the global memory locations to volatile, and the volatile reads show up, but aren't assigned to a variable.

My suspicion a bug was introduced due to a change in the decompiler late in the test cycle for the release.

**Comment by EgorKin** [comment]
Hope you also fix not recognized instructions like LWX. And please look at addiu (Ghidra) vs la (IDA) instruction at 8007DEEC
![1](https://user-images.githubusercontent.com/4955678/55059092-20a0f980-507f-11e9-8238-1e02cb4e4f2b.png)
![2](https://user-images.githubusercontent.com/4955678/55059093-20a0f980-507f-11e9-91a2-5cece64ae5bd.png)

**Comment by nihilus** [comment]
For an implementation of unaligned loads and stores in MIPS one can always look at my implementation for snowman over at github.com/nihilus/snowman

**Comment by nihilus** [comment]
@EgorKin The LWX instruction is iirc part of the DSP ASE and needs the whole ASE to be implemented to make any sense,

**Comment by hllhll** [comment]
I'm getting similar issues on Atmel AVR32(LD.B LD.W LD.D ST.B ST.W ST.D), and a friend of mine on ARM(ldmia stmia).

In both cases, code is OK at the beginning, but after "Commit locals" or renaming/retyping in decompiler, some of the code vanishes (Stack initialization, but function calls to memset on stack are kept); initialization still missing if we define variables at the stack position. In addition, in both cases P-Code looks OK too.
( Note: arrived here via [other issue](https://github.com/NationalSecurityAgency/ghidra/issues/200#issuecomment-473715120 )

**Comment by caheckman** [comment]
This is not an issue with the LWL/LWR/SWL/SWR instructions but is due to over aggressive dead-code elimination. A fix will be available in master on the next update. I was able to verify that this particular example now shows more initialization code.  Thanks for submitting this.
