### ISSUE TITLE
Make it possible to display the offset column of the Structure Editor in hexadecimal

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#1536]
Offsets are generally expressed in hexadecimal everywhere (listing, auto-named fields `field_0x...` in the decompiler, ...), except in the Structure Editor where they are in decimal. As a result, making relationships between the Structure Editor and the rest is pretty clunky and awkward, especially as a struct grow larger and larger.

**Comment by aerosoul94** [comment]
You can set it to display hexadecimal values by default if you change your settings. This setting can by found by navigating to Edit > Tool Options > Editors > Structure Editor and then toggle "Show Numbers In Hex" on.

There is also a drop down menu in the Structure Editor window that has an option to toggle on "Show Numbers in Hexadecimal" but this will only last while you have the window open as the setting I first mentioned will override this feature every time you open the Structure Editor.

**Comment by ubitux** [comment]
> You can set it to display hexadecimal values by default if you change your settings. This setting can by found by navigating in the Code Browser to Edit > Tool Options > Editors > Structure Editor and then toggle "Show Numbers In Hex" on.

Mmh I should have look there, thanks.

> There is also a drop down menu in the Structure Editor window that has an option to toggle on "Show Numbers in Hexadecimal" but this will only last while you have the window open as the setting I first mentioned will override this feature every time you open the Structure Editor.

I'm not sure how I missed that. Maybe that's because the inverted color thing displays the black arrow on dark gray... Thanks for pointing it out.
