### ISSUE TITLE
Add alignement data type in the default list

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#1538]
I found through the Condense Filler Bytes prototype analyzer the "Alignment" type which I now use to hardcode padding/filler bytes in the listing. It would be convenient to have it available through the right click → Data menu in the listing view. Otherwise, without knowledge of that specific type, I don't see any other mean of flagging that kind of data.

**Comment by ghidra1** [comment]
You have the ability to specify a datatype as a favorite which will make it appear in the popup menu. 
 Right-click on the datatype in the datatype manager tree and select the Favorite action.
  Favorite datatypes are indicated by a heart icon.
