### ISSUE TITLE
Show File Offset for Currently Selected Address

### ISSUE THREAD

**Issue by OothecaPickle** [NationalSecurityAgency/ghidra#154]
Is there a way to get Ghidra to always show the *file offset (in hex) for the currently selected address somewhere?

**Comment by ryanmkurtz** [comment]
Currently there is nothing built-in to do this.  The file offset to memory address mapping is lost during import.  You would have to write a script to figure out the file offset, which would be specific to your binary's file format.

**Comment by OothecaPickle** [comment]
@ryanmkurtz is this something that may be added in a future release?

**Comment by ryanmkurtz** [comment]
I have switched this over to an enhancement so we can consider it for a future release.

**Comment by OothecaPickle** [comment]
@ryanmkurtz cool :)

**Comment by OothecaPickle** [comment]
@ryanmkurtz was this implemented in v9.0.1?

**Comment by ryanmkurtz** [comment]
@OothecaPickle, no, it was not implemented for the patch release.

**Comment by ryanmkurtz** [comment]
This has been implemented for 9.1.  You can test it out in the master branch.

**Comment by OothecaPickle** [comment]
great :)

**Comment by oshogbo** [comment]
Hym, I don't see where the data are displayed. Can you help me with this?

**Comment by ryanmkurtz** [comment]
You have to hover on an address in the listing.  There's also a new field in the Memory Map to show where each memory block was mapped from in the file.

**Comment by jabedude** [comment]
@ryanmkurtz is this available in the Ghidra API? i.e. converting an address to it's file offset?

**Comment by ryanmkurtz** [comment]
Yes. From `Memory` you can get the `MemoryBlock`s, and then for each block you can get its `MemoryBlockSourceInfo`, and then you can `getFileBytesOffset(Address)`.

**Comment by elig0n** [comment]
Is there a way to "Goto" the file offset's equivalent address?
