### ISSUE TITLE
Incorrect decompile of test and jle combo

### ISSUE THREAD

**Issue by Jaguar83** [NationalSecurityAgency/ghidra#1546]
**Describe the bug**
TEST       EAX ,EAX
JLE        LAB_004bf245

Decompiles to "if (uVar4 != 0xffffffe0) {"

**Expected behavior**
Should decompile to "if ((int)uVar4 <= 0) {"

**Screenshots**
![func_dec_debug2](https://user-images.githubusercontent.com/4597230/74804594-c95de480-5334-11ea-9335-fecf79e7f162.png)

**Attachments**
[func_dec_debug2_xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/4223249/func_dec_debug2_xml.txt)

**Environment:**
 - OS: Windows 10
 - Java Version: 11.0.6
 - Ghidra Version: 9.1.1

**Comment by Jaguar83** [comment]
Why has this been mis-labelled as invalid?

**Comment by pelrun** [comment]
Ghidra's doing the right thing here. Since uVar4 can only take one of two possible values from the expression just above it, "uVar4 == 0xffffffe0" is 100% equivalent to "(int)uVar4 <= 0", and simpler.

If you want Ghidra to interpret uVar4 as signed, you need to change the variable's type yourself.
