### ISSUE TITLE
Incorrect Dissassembly of MIPS Function Prologue (Big Endian) 

### ISSUE THREAD

**Issue by tulipszs** [NationalSecurityAgency/ghidra#1549]
**Describe the bug**
Ghidra disassembles the function prologue as follows:
```
.text:004fad64               lui                  gp,0x57
     assume t9 = <UNKNOWN>
     assume gp = <UNKNOWN>
.text:004fad68               addiu             gp,gp,0xfcc
.text:004fad6c               addu              gp,gp,t9
.text:004fad70               addiu             sp,sp,-0x48
.text:004fad74               sw                  ra,local_4(sp)
.text:004fad78               sw                  s4,local_8(sp)
.text:004fad7c               sw                  s3,local_c(sp)
...
```

Ida's version:
```
.text:004FAD64                 la      $gp, loc_570FCC
.text:004FAD6C                 addu    $gp, $t9
.text:004FAD70                 addiu   $sp, -0x48
.text:004FAD74                 sw      $ra, 0x48+var_4($sp)
.text:004FAD78                 sw      $s4, 0x48+var_8($sp)
.text:004FAD7C                 sw      $s3, 0x48+var_C($sp)
```
Binary Ninja:
```
004fad64  3c1c0057… li      $gp, 0x570fcc
004fad6c  0399e021   addu    $gp, $gp, $t9
004fad70  27bdffb8   addiu   $sp, $sp, -0x48
004fad74  afbf0044   sw      $ra, 0x44($sp) {__saved_$ra}
004fad78  afb40040   sw      $s4, 0x40($sp) {__saved_$s4}
004fad7c  afb3003c   sw      $s3, 0x3c($sp) {__saved_$s3}
```

As a result, Ghidra bases the decompilation off of an incorrect $GP value resulting in an incorrect decompilation:

```
void FUN_004fad64(undefined8 param_1,undefined8 param_2,longlong param_3)

{
  undefined *puVar1;
  int iVar2;
  undefined4 uVar3;
  code *pcVar4;
  longlong lVar5;
  ssize_t sVar8;
  longlong lVar6;
  undefined4 *puVar9;
  ulonglong uVar7;
  int iVar10;
  sockaddr *local_24;
  undefined *local_20;
  socklen_t *in_stack_ffffffe4;
  
  local_20 = &_gp;
  FUN_00643480();
  if (param_3 < 0) {
    puVar1 = *(local_20 + -0x2a3c);
    *puVar1 = 0;
    lVar5 = (**(local_20 + -0x5858))(0,0xff03);
    if (lVar5 != 0) {
      (**(local_20 + -0x6dc4))(puVar1,0x400,0,0xff03);
      (**(local_20 + -0x6c34))(*(local_20 + -0x6380),0xff03,0,puVar1);
    }
    lVar5 = (**(local_20 + -0x3540))(0,0xff03,0,0);
    if (lVar5 != 0) {
      if (**(local_20 + -0x2a3c) == '\0') {
        (**(local_20 + -0x6dc4))(*(local_20 + -0x2a3c),0x400,0,0xff03);
      }
      (**(local_20 + -0x6c34))(*(local_20 + -0x5930),0xff03,0,*(local_20 + -0x2a3c));
    }
  }

....

```

**To Reproduce**

Function bytes: 
```
3c 1c 00 57 27 9c 0f cc 03 99 e0 21 27 bd ff b8 af bf 00 44 af b4 00 40 af b3 00 3c af b2 00 38 af b1 00 34 af b0 00 30 af bc 00 28 8f 99 9f fc 03 20 f8 09 00 c0 80 21 06 01 00 44 8f bc 00 28 8f 91 d5 c4 a2 20 00 00 00 00 20 21 8f 99 a7 a8 03 20 f8 09 34 05 ff 03 10 40 00 19 8f bc 00 28 af a0 00 10 af a0 00 14 af a0 00 18 8f 82 80 60 24 42 90 6c af a2 00 1c 8f 82 80 48 24 42 7e c0 af a2 00 20 02 20 20 21 24 05 04 00 00 00 30 21 8f 99 92 3c 03 20 f8 09 34 07 ff 03 8f bc 00 28 af b0 00 10 8f 84 9c 80 34 05 ff 03 00 00 30 21 8f 99 93 cc 03 20 f8 09 02 20 38 21 8f bc 00 28 00 00 20 21 34 05 ff 03 00 00 30 21 8f 99 ca c0 03 20 f8 09 00 00 38 21 10 40 02 3b 8f bc 00 28 8f 84 d5 c4 80 82 00 00 14 40 00 0f 8f 82 80 60 af a0 00 10 af a0 00 14 af a0 00 18 24 42 90 6c af a2 00 1c 8f 82 80 48 24 42 7e c0 af a2 00 20 24 05 04 00 00 00 30 21 8f 99 92 3c 03 20 f8 09 34 07 ff 03 8f bc 00 28 af b0 00 10 8f 84 a6 d0 34 05 ff 03 8f 87 d5 c4 8f 99 93 cc 03 20 f8 09 00 00 30 21 10 00 02 20 8f bc 00 28 8f 99 aa 5c 03 20 f8 09 24 04 06 72 10 40 01 cb 8f bc 00 28 00 40 90 21 00 40 20 21 00 00 28 21 8f 99 b9 30 03 20 f8 09 24 06 06 72 8f bc 00 28 af a0 00 10 af a0 00 14 02 00 20 21 02 40 28 21 24 06 06 72 8f 99 88 84 03 20 f8 09 00 00 38 21 8f bc 00 28 1c 40 00 4d 00 40 80 21 8f 83 d6 20 8c 62 01 3c 24 42 00 01 ac 62 01 3c 8c 62 01 38 24 42 00 01 ac 62 01 38 8f 90 d5 c4 a2 00 00 00 24 04 00 02 8f 99 a7 a8 03 20 f8 09 24 05 00 0d 10 40 00 18 8f bc 00 28 af a0 00 10 af a0 00 14 af a0 00 18 8f 82 80 60 24 42 90 6c af a2 00 1c 8f 82 80 48 24 42 7e e8 af a2 00 20 02 00 20 21 24 05 04 00 24 06 00 02 8f 99 92 3c 03 20 f8 09 24 07 00 0d 8f bc 00 28 8f 84 9c 80 24 05 00 0d 00 00 30 21 8f 99 93 cc 03 20 f8 09 02 00 38 21 8f bc 00 28 24 04 00 02 24 05 00 0d 00 00 30 21 8f 99 ca c0 03 20 f8 09 00 00 38 21 10 40 00 1a 8f bc 00 28 8f 84 d5 c4 80 82 00 00 14 40 00 0f 8f 82 80 60 af a0 00 10 af a0 00 14 af a0 00 18 24 42 90 6c af a2 00 1c 8f 82 80 48 24 42 7e e8 af a2 00 20 24 05 04 00 24 06 00 02 8f 99 92 3c 03 20 f8 09 24 07 00 0d 8f bc 00 28 8f 84 a6 d0 24 05 00 0d 8f 87 d5 c4 8f 99 93 cc 03 20 f8 09 00 00 30 21 8f bc 00 28 8f 99 d4 10 03 20 f8 09 02 40 20 21 10 00 01 bd 8f bc 00 28 24 04 00 01 8f 99 a5 44 03 20 f8 09 02 40 28 21 8f bc 00 28 14 40 00 46 00 40 88 21 8f 90 d5 c4 a2 00 00 00 24 04 00 02 8f 99 a7 a8 03 20 f8 09 24 05 00 0d 10 40 00 18 8f bc 00 28 af a0 00 10 af a0 00 14 af a0 00 18 8f 82 80 60 24 42 90 6c af a2 00 1c 8f 82 80 48 24 42 7f 0c af a2 00 20 02 00 20 21 24 05 04 00 24 06 00 02 8f 99 92 3c 03 20 f8 09 24 07 00 0d 8f bc 00 28 8f 84 9c 80 24 05 00 0d 00 00 30 21 8f 99 93 cc 03 20 f8 09 02 00 38 21 8f bc 00 28 24 04 00 02 24 05 00 0d 00 00 30 21 8f 99 ca c0 03 20 f8 09 00 00 38 21 10 40 00 1a 8f bc 00 28 8f 84 d5 c4 80 82 00 00 14 40 00 0f 8f 82 80 60 af a0 00 10 af a0 00 14 af a0 00 18 24 42 90 6c af a2 00 1c 8f 82 80 48 24 42 7f 0c af a2 00 20 24 05 04 00 24 06 00 02 8f 99 92 3c 03 20 f8 09 24 07 00 0d 8f bc 00 28 8f 84 a6 d0 24 05 00 0d 8f 87 d5 c4 8f 99 93 cc 03 20 f8 09 00 00 30 21 8f bc 00 28 8f 99 d4 10 03 20 f8 09 02 40 20 21 10 00 01 71 8f bc 00 28 ac 50 00 08 8f 82 d6 20 8c 52 0b 54 12 40 00 02 00 00 a0 21 8e 54 01 00 8e 33 00 00 8f 90 d5 c4 a2 00 00 00 24 04 00 03 8f 99 a7 a8 03 20 f8 09 24 05 00 01 10 40 00 18 8f bc 00 28 af a0 00 10 af a0 00 14 af b2 00 18 8f 82 80 60 24 42 90 90 af a2 00 1c 8f 82 80 48 24 42 7f 3c af a2 00 20 02 00 20 21 24 05 04 00 24 06 00 03 8f 99 92 3c 03 20 f8 09 24 07 00 01 8f bc 00 28 8f 84 9c 80 24 05 00 01 00 00 30 21 8f 99 93 cc 03 20 f8 09 02 00 38 21 8f bc 00 28 24 04 00 03 24 05 00 01 00 00 30 21 8f 99 ca c0 03 20 f8 09 00 00 38 21 10 40 00 1a 8f bc 00 28 8f 84 d5 c4 80 82 00 00 14 40 00 0f 8f 82 80 60 af a0 00 10 af a0 00 14 af b2 00 18 24 42 90 90 af a2 00 1c 8f 82 80 48 24 42 7f 3c af a2 00 20 24 05 04 00 24 06 00 03 8f 99 92 3c 03 20 f8 09 24 07 00 01 8f bc 00 28 8f 84 a6 d0 24 05 00 01 8f 87 d5 c4 8f 99 93 cc 03 20 f8 09 00 00 30 21 8f bc 00 28 8e 30 00 08 2e 02 00 e8 10 40 00 4f 26 23 00 28 8f 83 d6 20 8c 62 01 44 24 42 00 01 ac 62 01 44 8c 62 01 38 24 42 00 01 ac 62 01 38 8f 93 d5 c4 a2 60 00 00 24 04 00 02 8f 99 a7 a8 03 20 f8 09 24 05 00 01 10 40 00 1b 8f bc 00 28 af a0 00 10 af a0 00 14 af b2 00 18 8f 82 80 60 24 42 90 90 af a2 00 1c 8f 82 80 48 24 42 7f 5c af a2 00 20 02 60 20 21 24 05 04 00 24 06 00 02 8f 99 92 3c 03 20 f8 09 24 07 00 01 8f bc 00 28 af b0 00 10 24 02 00 e8 af a2 00 14 8f 84 9c 80 24 05 00 01 00 00 30 21 8f 99 93 cc 03 20 f8 09 02 60 38 21 8f bc 00 28 24 04 00 02 24 05 00 01 00 00 30 21 8f 99 ca c0 03 20 f8 09 00 00 38 21 10 40 00 94 8f bc 00 28 8f 84 d5 c4 80 82 00 00 14 40 00 0f 8f 82 80 60 af a0 00 10 af a0 00 14 af b2 00 18 24 42 90 90 af a2 00 1c 8f 82 80 48 24 42 7f 5c af a2 00 20 24 05 04 00 24 06 00 02 8f 99 92 3c 03 20 f8 09 24 07 00 01 8f bc 00 28 af b0 00 10 24 02 00 e8 af a2 00 14 8f 84 a6 d0 24 05 00 01 8f 87 d5 c4 8f 99 93 cc 03 20 f8 09 00 00 30 21 10 00 00 77 8f bc 00 28 ae 30 00 24 ae 33 00 0c a2 20 00 28 24 02 00 02 a0 62 00 01 24 02 00 43 a4 62 00 02 8f 99 be 20 03 20 f8 09 02 20 20 21 12 40 00 03 8f bc 00 28 16 80 00 5d 02 80 20 21 8f 90 d5 c4 a2 00 00 00 24 04 00 02 8f 99 a7 a8 03 20 f8 09 24 05 00 0d 10 40 00 25 8f bc 00 28 af a0 00 10 af a0 00 14 af b2 00 18 8f 82 80 60 24 42 90 90 af a2 00 1c 8f 82 80 48 24 42 7f 9c af a2 00 20 02 00 20 21 24 05 04 00 24 06 00 02 8f 99 92 3c 03 20 f8 09 24 07 00 0d 8f bc 00 28 8f 99 c0 30 03 20 f8 09 00 00 20 21 8f bc 00 28 af b2 00 10 af a2 00 14 af b4 00 18 8e 22 00 10 af a2 00 1c 8e 22 00 14 af a2 00 20 8e 22 00 24 af a2 00 24 8f 84 9c 80 24 05 00 0d 00 00 30 21 8f 99 93 cc 03 20 f8 09 02 00 38 21 8f bc 00 28 24 04 00 02 24 05 00 0d 00 00 30 21 8f 99 ca c0 03 20 f8 09 00 00 38 21 10 40 00 35 8f bc 00 28 8f 84 d5 c4 80 82 00 00 14 40 00 11 8f 99 c0 30 af a0 00 10 af a0 00 14 af b2 00 18 8f 82 80 60 24 42 90 90 af a2 00 1c 8f 82 80 48 24 42 7f 9c af a2 00 20 24 05 04 00 24 06 00 02 8f 99 92 3c 03 20 f8 09 24 07 00 0d 8f bc 00 28 8f 99 c0 30 03 20 f8 09 00 00 20 21 8f bc 00 28 af b2 00 10 af a2 00 14 af b4 00 18 8e 22 00 10 af a2 00 1c 8e 22 00 14 af a2 00 20 8e 22 00 24 af a2 00 24 8f 84 a6 d0 24 05 00 0d 8f 87 d5 c4 8f 99 93 cc 03 20 f8 09 00 00 30 21 10 00 00 0d 8f bc 00 28 8f 99 a7 7c 03 20 f8 09 00 00 28 21 8f bc 00 28 a2 20 01 78 02 40 20 21 8f 99 cb 34 03 20 f8 09 02 20 28 21 30 42 00 ff 14 40 00 07 8f bc 00 28 02 20 20 21 8f 99 b9 98 03 20 f8 09 24 05 00 01 10 00 00 5c 8f bc 00 28 92 22 01 54 14 40 00 07 24 02 00 01 02 20 20 21 8f 99 b9 98 03 20 f8 09 24 05 00 01 10 00 00 53 8f bc 00 28 10 00 00 51 a2 22 01 55 8f 83 d6 20 8c 62 01 50 24 42 00 01 ac 62 01 50 8c 62 01 38 24 42 00 01 ac 62 01 38 af a0 00 10 af a0 00 14 02 00 20 21 00 00 28 21 00 00 30 21 8f 99 88 84 03 20 f8 09 00 00 38 21 8f bc 00 28 8f 90 d5 c4 a2 00 00 00 00 00 20 21 8f 99 a7 a8 03 20 f8 09 24 05 00 0d 10 40 00 18 8f bc 00 28 af a0 00 10 af a0 00 14 af a0 00 18 8f 82 80 60 24 42 90 6c af a2 00 1c 8f 82 80 48 24 42 7f f4 af a2 00 20 02 00 20 21 24 05 04 00 00 00 30 21 8f 99 92 3c 03 20 f8 09 24 07 00 0d 8f bc 00 28 8f 84 9c 80 24 05 00 0d 00 00 30 21 8f 99 93 cc 03 20 f8 09 02 00 38 21 8f bc 00 28 00 00 20 21 24 05 00 0d 00 00 30 21 8f 99 ca c0 03 20 f8 09 00 00 38 21 10 40 00 1a 8f bc 00 28 8f 84 d5 c4 80 82 00 00 14 40 00 0f 8f 82 80 60 af a0 00 10 af a0 00 14 af a0 00 18 24 42 90 6c af a2 00 1c 8f 82 80 48 24 42 7f f4 af a2 00 20 24 05 04 00 00 00 30 21 8f 99 92 3c 03 20 f8 09 24 07 00 0d 8f bc 00 28 8f 84 a6 d0 24 05 00 0d 8f 87 d5 c4 8f 99 93 cc 03 20 f8 09 00 00 30 21 8f bc 00 28 8f bf 00 44 8f b4 00 40 8f b3 00 3c 8f b2 00 38 8f b1 00 34 8f b0 00 30 03 e0 00 08 27 bd 00 48
```

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Java Version:
```
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
 - Ghidra Version: Ghidra_9.1-BETA_DEV

**Comment by ghidra1** [comment]
Is this 32-bit or 64-bit MIPS?  Using 32-bit produced the best match.

The snippet of Ghidra assembly code is correct and consistent with IDA/Binary Ninja.  The only difference is IDA and Binary Ninja have combined the lui and addiu into a single macro instruction.

You can verify this by clicking the leftmost gp operand at 4fad68 and running the script MultiInstructionMemReference.java to markup the final gp value.

What makes you believe the gp value is incorrect?  I am not sure what I should be looking for in the decompilation view that you think is incorrect.  Below is my result, although I am missing the pointer tables which accounts for the indirect function calls.  Without the entire binary it is difficult to resolve the references outside the function itself.

```
void FUN_004fad64(undefined4 param_1,undefined4 param_2,int param_3)

{
  char *pcVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  undefined4 *puVar5;
  uint uVar6;
  undefined4 uVar7;
  
  // I created a constant pointer to a function to get this first function call
  // to be consistent with your sample above
  FUN_00643480();  
  pcVar1 = pcRam00a692f4;
  if (param_3 < 0) {
    *pcRam00a692f4 = '\0';
    iVar2 = (*pcRam00a664d8)(0,0xff03);
    if (iVar2 != 0) {
      (*pcRam00a64f6c)(pcVar1,0x400,0,0xff03,0,0,0,iRam00a63d90 + -0x6f94,iRam00a63d78 + 0x7ec0);
      (*pcRam00a650fc)(uRam00a659b0,0xff03,0,pcVar1,param_3);
    }
    iVar2 = (*pcRam00a687f0)(0,0xff03,0,0);
    if (iVar2 != 0) {
      if (*pcRam00a692f4 == '\0') {
        (*pcRam00a64f6c)(pcRam00a692f4,0x400,0,0xff03,0,0,0,iRam00a63d90 + -0x6f94,
                         iRam00a63d78 + 0x7ec0);
      }
      (*pcRam00a650fc)(uRam00a66400,0xff03,0,pcRam00a692f4,param_3);
    }
  }
...
```

**Comment by tulipszs** [comment]
It's 32 bit mips. 

I assumed it was incorrect by adding the two values with python and comparing the result to ida/binja:
```
>>> hex(0x57 + 0x0fcc)
'0x1023'
```
probably messed up by not accounting for endian? either way, thanks for noting that script. I've never used it before. I assumed it was incorrect because ghidra seems to not be resolving the indirect calls in the decompiler but after looking a second time, it seems that the calls are properly resolved in the listing but not being displayed in the decompiler. 

![2020-02-19-140324_839x417_scrot](https://user-images.githubusercontent.com/22307502/74866300-a88b9400-5320-11ea-9131-fab351236dd3.png)


I have uploaded the binary: 
[binary.zip](https://github.com/NationalSecurityAgency/ghidra/files/4226806/binary.zip)


Any ideas on how I could clean up the decompilation so it displays the jalr targets better?

Thanks for the quick reply.

**Comment by astrelsky** [comment]
> It's 32 bit mips.
> 
> I assumed it was incorrect by adding the two values with python and comparing the result to ida/binja:
> 
> ```
> >>> hex(0x57 + 0x0fcc)
> '0x1023'
> ```
> 
> probably messed up by not accounting for endian? either way, thanks for noting that script. I've never used it before. I assumed it was incorrect because ghidra seems to not be resolving the indirect calls in the decompiler but after looking a second time, it seems that the calls are properly resolved in the listing but not being displayed in the decompiler.
> 
> ![2020-02-19-140531_1296x352_scrot](https://user-images.githubusercontent.com/22307502/74866479-ee485c80-5320-11ea-9ea7-8fae990b8e97.png)
> 
> I have uploaded the binary:
> [binary.zip](https://github.com/NationalSecurityAgency/ghidra/files/4226806/binary.zip)
> 
> Any ideas on how I could clean up the decompilation so it displays the jalr targets better?
> 
> Thanks for the quick reply.

lui is load upper immediate. `lui gp, 0x57` results in a go value of 0x570000.

**Comment by DualTachyon** [comment]
While the OP may have been confused with his analysis a bit, there is still a real bug. I found some code in a file I'm analysing that produces the same kind of "crazy" code as shown in the first post.

In my case, I get both GP and T9 shown as "assumed XX = <UNKNOWN>" early in the disassemble, even though in the function itself they are known.

Unfortunately I cannot share the binary itself. However you can see below a copy of the function in the disassembly view.
Notice how very early on, GP = 0x9925cff0 and T9 = 0x9903632c but on the first instruction itself, it shows "UNKNOWN".


                             *************************************************************
                             *                            FUNCTION                         
                             *************************************************************
                             undefined  __stdcall  Blabla  (Ch_t
                               assume gp = 0x9925cff0
                               assume t9 = 0x9903632c
             undefined         v0:1           <RETURN>
             Ch_t              a0:4           param_1
             undefined4        a1:4           param_2
             undefined4        a2:4           param_3
             undefined4        Stack[0x8]:4   local_res8                              XREF[2]:     99036354 (W) , 
                                                                                                   990363f8 (R)   
             undefined4        Stack[0x4]:4   local_res4                              XREF[8]:     99036350 (W) , 
                                                                                                   990363b0 (R) , 
                                                                                                   99036400 (R) , 
                                                                                                   99036430 (R) , 
                                                                                                   99036448 (R) , 
                                                                                                   99036458 (R) , 
                                                                                                   99036460 (R) , 
                                                                                                   9903647c (R)   
             undefined4        Stack[0x0]:4   local_res0                              XREF[10]:    9903634c (W) , 
                                                                                                   99036358 (R) , 
                                                                                                   990363f4 (R) , 
                                                                                                   990364c0 (R) , 
                                                                                                   990364e4 (R) , 
                                                                                                   990364f8 (R) , 
                                                                                                   99036500 (R) , 
                                                                                                   99036508 (R) , 
                                                                                                   99036510 (R) , 
                                                                                                   99036528 (R)   
             undefined4        Stack[-0x4]:4  local_4                                 XREF[2]:     9903633c (W) , 
                                                                                                   99036578 (R)   
             undefined4        Stack[-0x8]:4  local_8                                 XREF[2]:     99036340 (W) , 
                                                                                                   9903657c (R)   
             undefined4        Stack[-0x50]   local_50                                XREF[1]:     99036494 (W)   
             undefined4        Stack[-0x54]   local_54                                XREF[1]:     99036444 (W)   
             undefined4        Stack[-0x70]   local_70                                XREF[9]:     99036348 (W) , 
                                                                                                   9903636c (R) , 
                                                                                                   990363ac (R) , 
                                                                                                   990363f0 (R) , 
                                                                                                   9903642c (R) , 
                                                                                                   990364b4 (R) , 
                                                                                                   990364d8 (R) , 
                                                                                                   99036540 (R) , 
                                                                                                   9903656c (R)   
             undefined4        Stack[-0x78]   local_78                                XREF[3]:     99036380 (W) , 
                                                                                                   990363c4 (W) , 
                                                                                                   99036518 (W)   
                             BlaBla                                          XREF[4]:     Entry Point (*) , 
                                                                                          99256568 (*)   
        9903632c 22  00  1C       lui        gp ,  0x22
                 3C
             assume t9 = <UNKNOWN>
             assume gp = <UNKNOWN>
        99036330 C4  6C  9C       addiu      gp ,  gp ,  0x6cc4
                 27
        99036334 21  E0  99       addu       gp ,  gp ,  t9
                 03
        99036338 78  FF  BD       addiu      sp ,  sp ,  -0x88
                 27
        9903633c 84  00  BF       sw         ra ,  local_4 (sp )
                 AF
        99036340 80  00  BE       sw         s8 ,  local_8 (sp )
                 AF
        99036344 25  F0  A0       or         s8 ,  sp ,  zero
                 03

**Comment by DualTachyon** [comment]
You can see below an example of the crazy code. If I try to set register via CTRL-R, it will immediately mark both registers as UNKNOWN on the next instruction.

![image](https://user-images.githubusercontent.com/4077499/167035486-8b63f52d-2437-40d4-9121-7ee862fd214b.png)

**Comment by emteere** [comment]
This is the correct behavior for setting a register value currently.  To display the value of the register further with that field, it would need to be calculated constantly.  The field only shows where it is explicitly set.

The value of a register is only considered at the beginning of the function for both reference analysis and the decompiler.
The register value may change over the life of the function, so it can't be assumed.  There are cases where one might want to specify the explicit value at a location, but there are many mechanisms that are usually sufficient.

There are other mechanisms that could be at play, like specifying a registers value is preserved or changed by a call.

That said, I haven't looked closely at the above, but will take a look.

**Comment by emteere** [comment]
There is a known issue with the decompiler that may be this issue.  The decompiler is keeping the value of the representative for GP as a variable, and not simplifying accesses from it.  I'll check and see if that's the problem.  I don't at first glance see side-effects above since it happens early in the function.

**Comment by emteere** [comment]
Is the memory at the label _gp_1 allocated?

**Comment by DualTachyon** [comment]
It is not in my binary. It's originally a .o file that I rebased to 0x99000000 (with mips-*-ld -o -r -Ttext 0x99000000 bla.o).
_gp_1 is an external symbol. You can see it in red in the screenshot.

![image](https://user-images.githubusercontent.com/4077499/167139479-ced164b3-e438-4b7e-aeac-6d5031f8e707.png)
.

**Comment by DualTachyon** [comment]
I have run the FindPotentialDecompilerProblems script. While I fixed/improved functions that needed some attention, it didn't solve the weird problem discussed here. I still have some functions that have problems because some take very large structures 
 by value through the stack, but aren't tied in anyway to the one above. I checked that the function above doesn't deal with "structs by value on the stack".

In my case, the value inside _gp_1 doesn't matter for anything because only the address is used to calculate a final location.
As you can see in my screenshot, it does "local_70 = &_gp_1", i.e., only taking its address. It then adds/subtracts offsets but doesn't think (my guess) that local_70 is a constant value.

The pattern in the disassembly is pretty much the same as in any other function that has no issue.

**Comment by emteere** [comment]
@tulipszs in your issue, you say you are using Ghidra_9.1-BETA_DEV is that correct?  That's a fairly old version.  The decompiler is constantly improved.

My disassembly of your same routine in 10.1.3, does collapse the GP value + offset to a constant.  I have no values at the memory referenced, so the actual address can't be computed from a value loaded there.

**Comment by DualTachyon** [comment]
I'm using Ghidra latest version (10.1.3), the binary is using "MIPS:LE:32:default (1.6)". I attached a file with the opcode bytes.
As far as I can see, there are no big structures on the stack based on "addiu sp, sp, -0x88". For comparison, other functions with much bigger stack space have no issue.

The base address of the instructions is 0x9903632c. It has these assumed register values:
- assume gp = 0x9925cff0
- assume t9 = 0x9903632c

The calling convention is the default __stdcall. The signature is "void bla(somestruct_t *, uint, uint)". (My comments on large structs by value were on those functions found by FindPotentialDecompilerProblems, not this one).

The structure is:

typedef struct {
   anotherstruct_t a;
   uint a;
   uint b;
   ushort c;
   ushort d;
   <32 bytes of 'undefined'>
   uint e;
   uint f;
} somestruct_t;

typedef struct {
   uint a;
   uint b;
   uint c;
   uint d;
} anotherstruct_t;


[Opcodes.txt](https://github.com/NationalSecurityAgency/ghidra/files/8642114/Opcodes.txt)

**Comment by DualTachyon** [comment]
I have some obvious typo in the first struct (2 fields named 'a'). I was typing out the structures without the original names.

**Comment by emteere** [comment]
Didn't pay attention to the age of this issue.  Probably should have been closed as the OP issue was fixed.  This additional issue is something a bit different.

I've been able to reproduce.  I've seen this issue before.  I'll see if there is anything you can do to coax the decompiler to trust and simplify the GP value in local_70

**Comment by emteere** [comment]
So I think you will get better results if you use the MIPS:LE:64:64-32addr processor.  You can just close the program and set the language in the project manager then re-open it.  You might want to re-import using that processor to get clean results (YMMV).  You will probably need to re-analyze the code either way.  The mips does some sign extending on addresses and the compiler might have used instructions knowing that it would run on a 64-bit mips with a 32-bit address space.  Not necessarily the case, but using the above processor definitely helps.

```
void FUN_9903632c(int param_1,int param_2,undefined4 param_3)

{
  longlong lVar1;
  void *local_70;
  undefined auStack104 [20];
  undefined *local_54;
  undefined *local_50;
  undefined auStack76 [76];
  
  lVar1 = (*_DAT_9925501c)(param_1);
  (*_DAT_99255004)(lVar1 != 0,1,_DAT_99255000 + 0x7a20,_DAT_99255000 + 0x79e0);
  (*_DAT_99255004)(param_2 != 0,1,_DAT_99255000 + 0x7a70,_DAT_99255000 + 0x79e0);
  *(undefined4 *)(param_1 + 0x3c) = param_3;
  func_0x9924ca74(auStack104,param_2,0x60);
  if (*(int *)(param_2 + 0x14) != 0) {
    local_54 = auStack76;
  }
  if (*(int *)(param_2 + 0x18) != 0) {
    if (*(int *)(param_2 + 0x18) == param_2 + 0x1c) {
      local_50 = auStack76;
    }
    else {
      local_50 = auStack76 + *(byte *)(param_2 + 0x12);
    }
  }
  (*(code *)(_DAT_99255738 + 0x675c))(auStack104);
  lVar1 = (*(code *)(_DAT_99255738 + 0x709c))(param_1,auStack104);
  if ((lVar1 != 0) && (*(int *)(param_1 + 0x10) != -1)) {
    (*(code *)(_DAT_99255738 + 0x725c))
              (param_1,*(undefined2 *)(param_1 + 0x18),param_1 + 0x1c,
               *(undefined2 *)(param_1 + 0x1a));
  }
  (*_DAT_992554a8)(auStack104,0x60);
  return;
}
```
If there was memory at 0x99255000 + 0x7a20 it would most likely simplify.  Give it a try and see if it works better for you.  I don't have the rest of the code so I can't see the effect on all the offsets.  Notice the variable that held the original &gp_1 is gone.

**Comment by DualTachyon** [comment]
Wow, thanks for that tip!! The function is fully readable now! There is still some minor issue (the in_stack_xxx), but I'll work on that on a separate bug if needed.

Thanks for this, and feel free to close this issue.

![image](https://user-images.githubusercontent.com/4077499/167181714-563c623b-2136-4f44-99f6-ca504ba06d84.png)

**Comment by emteere** [comment]
Great.  Feel free to open another.  I'll close this one.
