### ISSUE TITLE
Interpret common ARM Linux Software Interrupts as a syscall function.

### ISSUE THREAD

**Issue by beaubell** [NationalSecurityAgency/ghidra#155]
**Is your feature request related to a problem? Please describe.**
The following assembly gets decompiled to `software_interrupt(0);`
```
...
c0 70 a0 e3     mov        r7,#0xc0
00 00 00 ef     swi        0x0
```

**Describe the solution you'd like**
In IDA, it properly parses the syscall to `linux_eabi_syscall(__NR_mmap2, a1, a2, a3, a4, a5, a6, a7);`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Arignir** [comment]
Same problem for x86 actually, any manual syscall invocation using `int 0x80` isn't properly recognized by Ghidra (I haven't tested if `sysenter` is properly detected) .

**Comment by enovella** [comment]
I wanted to open an issue for the same purpose!

**Comment by kevinferrare** [comment]
This issue is particularly impacting when analysing DOS programs relying extensively on interrupts.

Since Ghidra does not know that the interrupt handler uses some registers as input / output, their values calculations are removed from the decompilation listing.
Due to this, a lot of logic can be lost.

Example for DOS int 0x21 / 0x09 (WRITE STRING TO STANDARD OUTPUT)
Assembly:
```assembly
// String to output at address DS:5A
MOV  DX,0x5a
MOV  AH,0x9
INT  0x21
```

Current decompile result
```C
// Note that there are no reference to 0x5A anymore
pcVar4 = (code *)swi(0x21);
(*pcVar4)();
```
Should be something like this instead:
```C
msdos_display_string((char*)0x5A);
// AL = 24h after this interrupt, should maybe be taken into consideration if there are subsequent usages of AL register.
```

Note that interrupt handling is implemented by the reko decompiler for various platforms: https://github.com/uxmal/reko/blob/master/src/Environments/Msdos/realmodeintservices.xml

Maybe something similar could be put in place?

**Comment by Arcnor** [comment]
Will it be possible to write a custom plugin to "hint" to the decompiler that we want said function call, instead of a `(code*)swi(0x21)` or similar?

**Comment by ghidracadabra** [comment]
We have a solution for this that will be available in 9.1.  

It's already checked in to master, so you can try it out now if you build Ghidra yourself.  There is documentation: see slide 50 of improvingDisassemblyAndDecompilation.pdf in the "Advanced" class.  There's also an example script called "ResolveX86orX64LinuxSyscallsScript.java".  

Essentially the idea is to add a special reference type on the instruction which has the effect of changing the CALLOTHER op (called swi in your example) to a CALL op to whatever address you specify.  You can then create a special address space where you can define the called functions.  You don't need any code for them, just a name and a signature.

**Comment by Arcnor** [comment]
Thanks @ghidracadabra . I don't completely understand yet (at least until I try that doc you mention) so I hope you don't mind me asking a question about it:

In the MS-DOS world, there are different functions using the same "syscall" number, and they are differentiated by using registers (so you can have `int(0x21)` which is the "syscall" itself, and `AX=42` and that's a different function than `int(0x21)` and `AX=24`). Will this new system support me adding said CALL to a different function depending on potentially arbitrary factors besides the syscall code?

I hope my explanation is clear, and thanks in advance!

**Comment by ghidracadabra** [comment]
Yes, that should work.  The docs show how to do it manually for an instance of a particular instruction.  The script shows how to do it for all the relevant instructions in the program.

A syscall instruction and your example both have the same issue: in order to determine which function is called, you have to do some analysis on the code to try to determine the value in a given register at each instance of the instruction.  In the script, this is done using the Symbolic Propagator. You could modify that script to find all instances of `int(0x21)` and then for each instance determine the value of `AX` and then lay down the appropriate reference.

**Comment by Arcnor** [comment]
Yeah, I've just checked the code and saw the SymbolycPropagator, I'm sure
it will be really useful for my case.

Thanks again!

**Comment by Arcnor** [comment]
After testing this for a while, it looks like it's going to work, but I'm having a small issue that I'm not sure I can fix.

When setting the reference type on some `INT 0x21` example to `CALL_OVERRIDE_UNCONDITIONAL` I'm getting the following decompilation:

![Screen Shot 2019-09-26 at 14 49 40](https://user-images.githubusercontent.com/28616/65694074-2b0f7080-e06d-11e9-9731-95c34db693b8.png)

Everything works, except that the `swi(0x21)` call should not be there

If I set the type to `CALLOTHER_OVERRIDE_CALL` instead, I get the following:

![Screen Shot 2019-09-26 at 14 50 44](https://user-images.githubusercontent.com/28616/65694132-45494e80-e06d-11e9-88d8-df9fd191da0c.png)

...which is worse, although the `swi` has disappeared. Is there anything I'm missing @ghidracadabra ?

**Comment by kevinferrare** [comment]
@Arcnor Do you plan on sharing your code? It would be nice if standard dos / bios interrupts were interpreted by default.

**Comment by Arcnor** [comment]
@kevinferrare Yeah, I'm planning on sharing it, after I fix a few things, including the one I reported.

I've also worked on creating a machine parseable list of interrupts, so it can be improved with the help of other people and it's not hardcoded.

I'll share both things at some point.

**Comment by ghidracadabra** [comment]
Short explanation of what's happening: the SLEIGH specification of INT 21 predates overriding references, so it's not written to take advantage of them.  

Add the following lines to ia.sinc as lines 3363 and 3364:

3363 n21: "21"	is epsilon			{ tmp:1 = 0x21; export tmp; }
3364 :INT n21         is vexMode=0 & byte=0xcd; byte=0x21 & n21           {swi();}
3365 :INT imm8 ... (existing code)

Then override using CALLOTHER_OVERRIDE_CALL references.  Note that this will work locally but you won't be able to share these files with anyone who hasn't modified ia.sinc.

Long explanation: The existing specification for INT 21 uses a CALLOTHER op to get a function and then an indirect call to call it.  The (completely reasonable) model is that you have a block-box CALLOTHER op named "swi" that gets an address of a function for you, and then that function is called.  

If you want to see this, enable the "Pcode" field in the Listing (click on the icon in the Listing toolbar that looks like a brick wall with an arrow pointing down under it, select the Instruction/Data tab, then right-click on the Pcode field).

Using the CALLOTHER_OVERRIDE_CALL reference on this address overrides the CALLOTHER but not the indirect call, and using the CALL_OVERRIDE_UNCONDITIONAL reference overrides the indirect call but not the CALLOTHER.  So we need to change the spec.

There is documentation for the overriding references: search the Ghidra help for "Reftypes", then scroll down to the Ref-Types table (insert joke about a "Beware of the Leopard" sign here).

Undoubtedly there will be other situations that require modifying SLEIGH be able to get the most out of the overriding references.  Furthermore, as a new feature, we're still trying to narrow down exactly what the best practices should be.

Hope this helps.

**Comment by Arcnor** [comment]
Thank you very much for the explanation.

I don't think I'll edit the file, as 0x21 was just an example, there are 0xFF of them 😄. But in case I need that, I'll bookmark this 🙂.

I assume I'll need to wait until you narrow down those best practices until this works "out of the box"?

Many thanks!

**Comment by ghidracadabra** [comment]
Oh, in that case you could just edit one line of ia.sinc: change line 3363 to 

:INT imm8       is vexMode=0 & byte=0xcd; imm8                      { swi(); }
(so the only change is to the stuff in the braces)

When I say "narrow down best practices" I mean "decide on the best SLEIGH implementation for instructions that will have overrides applied".  In general there are many ways to implement instructions in SLEIGH and we want decompilation, emulation, and in some cases overrides to work, which might influence which implementation to choose.  I'm fairly confident in the one I suggested but at some point it might change.  

I imagine there will be plenty of cases, including this one, that won't work out of the box until the SLEIGH is changed.  So don't wait on us before sharing your code. On the contrary, seeing different use cases will help sort things out!

**Comment by deliciouslytyped** [comment]
xref https://github.com/NationalSecurityAgency/ghidra/issues/3936
