### ISSUE TITLE
Renaming Global Variables and Labels 

### ISSUE THREAD

**Issue by outomla** [NationalSecurityAgency/ghidra#1561]
In the decompiler view, it supports renaming global variables (e.g. DAT_******* synthetic/dynamic symbols).  How can I rename these via a Ghidra Script?  I've tried finding these through symbol tables, etc., but haven't found a way to access these.

I'd also like to rename Unconditional Jump Labels as well, so it would be good to know how to access these via a script.

**Comment by AGDCservices** [comment]
Have you tried getSymbolAt(toAddr(<DAT_ADDR>)).setName(<New_Name>, ghidra.program.model.symbol.SourceType.USER_DEFINED)

That should update the label at whatever address you feed it.

**Comment by outomla** [comment]
Thank you so much for your help. This was exactly the kind of reply I needed. 

For others who may have the same question, here is my implementation for iterating through all the addresses and printing out symbol names. 

`AddressSetView initialized = currentProgram.getMemory().getLoadedAndInitializedAddressSet();
		AddressIterator addrIter = initialized.getAddresses(true);

		while (addrIter.hasNext() && !monitor.isCancelled()) {
			Address addr = addrIter.next();
			Symbol sym = getSymbolAt(addr); 
			
			if (sym != null) {
				printf("Symbol at 0x%x", addr.getOffset());
				printf(" = %s\n", sym.getName());
			} 
		}`
