### ISSUE TITLE
Graph View Code Block Not Sizing Correctly

### ISSUE THREAD

**Issue by AGDCservices** [NationalSecurityAgency/ghidra#1563]
**Describe the bug**
I fairly regularly come across code blocks in the graph view that don't properly resize and cut off instructions.  This is occurring when the "operand" field from the "edit code block fields" options is large enough that the entire instruction should be displayed.

**Expected behavior**
I would expect the code blocks to resize based on the instruction size, up to the maximum size listed in the "edit code block fields" option.

**Screenshots**
Error screenshot
![image](https://user-images.githubusercontent.com/57851463/75103284-b4987f80-55c6-11ea-9ffa-87cca7a509f2.png)

screenshot showing the operands field should be large enough
![image](https://user-images.githubusercontent.com/57851463/75103290-d72a9880-55c6-11ea-8842-aa333e67e13d.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - Java Version: openJDK 12
 - Ghidra Version: 9.1.2

**Comment by dragonmacher** [comment]
I believe this is a dup of #1008.  There is a fix for this in the pipeline.
