### ISSUE TITLE
macOS dyld_shared_cache is not recognized

### ISSUE THREAD

**Issue by MichielDerhaeg** [NationalSecurityAgency/ghidra#1566]
When importing a dyld shared cache that originated from an iPhone, it is recognized correctly as a shared cache.
Ghidra doesn't know what to do with the ones for macOS itself, located in `/private/var/db/dyld`.

**Comment by ryanmkurtz** [comment]
I can't confirm this, but I think that particular file is some sort of Universal Binary format that Ghidra doesn't know how to parse.  It didn't seem to follow the Universal Binary spec.

**Comment by MichielDerhaeg** [comment]
I can confirm that this is not the case. I used the structs from https://opensource.apple.com/source/dyld/dyld-625.13/launch-cache/dyld_cache_format.h.auto.html to parse it and it works on these as well as those from the iPhone.

**Comment by MichielDerhaeg** [comment]
There is also a separate file present for every architecture.

**Comment by ryanmkurtz** [comment]
Oh I might be thinking of the kernel cache file on macOS.
