### ISSUE TITLE
Is there some telling me how to install it.

### ISSUE THREAD

**Issue by 01043li** [NationalSecurityAgency/ghidra#1568]
Could you just teach me how to install that.I have no idea about it after scaning all courses which tell me to open the .bat file,but where is it! I am just a rookie proguamer who want to learn some assemble.ToT

**Comment by astrelsky** [comment]
Try https://www.ghidra-sre.org/InstallationGuide.html#Install

**Comment by GhidorahRex** [comment]
This has been answered sufficiently. Thanks @astrelsky!
