### ISSUE TITLE
Ghidra doesn't disassemble valid indirect call instruction on amd64

### ISSUE THREAD

**Issue by mcfi** [NationalSecurityAgency/ghidra#157]
**Describe the bug**

This byte sequence, `48ff153e8f3a00`, is a valid indirect call instruction on amd64, but Ghidra cannot recognize it.

**Expected behavior**
Ghidra should disassemble the sequence as an indirect call.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 19H1]
 - Java Version: [e.g. 11.0.2]
 - Ghidra Version: [e.g. 9.0]

**Comment by mumbel** [comment]
dup #22
