### ISSUE TITLE
No spaces between words in the GUI v 9.1.2

### ISSUE THREAD

**Issue by huornlmj** [NationalSecurityAgency/ghidra#1571]
I'm seeing #1185 again in the latest v 9.1.2 downloadable from https://ghidra-sre.org/ and running the ./ghidraRun script on Ubuntu 18.04 desktop.  I deleted my ~/.ghidra directory and tried again but still same issue.

**Comment by 0x6d696368** [comment]
#1185 is still present. Starting a new version of Ghidra here always results in spaces missing from the GUI. Accepting the User Agreement and closing Ghidra and starting it again always fixes the issues.

**Comment by VorpalBlade** [comment]
I'm also seeing this on Ubuntu 18.04, using X.Org, with the latest public download from https://ghidra-sre.org (`ghidra_9.1.2_PUBLIC_20200212.zip`). Issue should be reopened, as while there is a workaround, there is still a bug present that confuses new users.
