### ISSUE TITLE
Instruction Pattern Search false positives

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1578]
I have an x86 instruction `LEA ESI, [EDI + 0x44]`.

If I select it, perform an _Instruction Pattern Search_ masking out the _Mnemonic_ and _Operand 1_, I get `[........][........][.....111] 44` in the _Search String Preview_ window.  

When I do a _Search All_, I get some correct matches, but a lot of false positives too.  An example of a false positive is:

`33 db    XOR EBX, EBX`

**Comment by ryanmkurtz** [comment]
It seems like most of the bad matches are on instructions with a smaller size than the pattern you are searching for, and the match is actually in the next instruction.

**Comment by GhidorahRex** [comment]
The match is technically starting at bytes within the code unit (in this case it's the 2nd byte of the `XOR` instruction) being reported in the match. The match may be `db 00 ff 1f 44` for instance. The pattern search doesn't respect instruction byte boundaries.

**Comment by ryanmkurtz** [comment]
Yes, I didn't expect consecutive fully masked off bytes at the beginning of the pattern encompassing entire instructions you don't care about.  Thanks!
