### ISSUE TITLE
Auto Analysis throughs error when demangling a symbol

### ISSUE THREAD

**Issue by kye4u2** [NationalSecurityAgency/ghidra#1580]
**Describe the bug**
When auto analyzing the QT binary libQt5core.so.5.12.7, Ghidra reports errors with respect to demangling which result in the disassembly not finishing after 12 hours for a 75 MB file.  With demangling disabled, disassembly completed in 10 minutes.  

An excerpt of the errors can be found below:

ERROR Unable to demangle symbol at 001be826; name: _ZN15QMessagePattern15BacktraceParamsC1Ev. Message: class ghidra.program.database.data.TypedefDB cannot be cast to class ghidra.program.model.data.Structure (ghidra.program.database.data.TypedefDB and ghidra.program.model.data.Structure are in unnamed module of loader ghidra.GhidraClassLoader @279f2327) (DemanglerCmd)

ERROR Unable to demangle symbol at 001be842; name: _ZN15QMessagePattern15BacktraceParamsD1Ev. Message: class ghidra.program.database.data.TypedefDB cannot be cast to class ghidra.program.model.data.Structure (ghidra.program.database.data.TypedefDB and ghidra.program.model.data.Structure are in unnamed module of loader ghidra.GhidraClassLoader @279f2327) (DemanglerCmd)

ERROR Unable to demangle symbol at 001be85e; name: ZN15QMessagePattern15BacktraceParamsC1ERKS0. Message: class ghidra.program.database.data.TypedefDB cannot be cast to class ghidra.program.model.data.Structure (ghidra.program.database.data.TypedefDB and ghidra.program.model.data.Structure are in unnamed module of loader ghidra.GhidraClassLoader @279f2327) (DemanglerCmd)

:ERROR Unable to demangle symbol at 001bee26; name: ZN15QMessagePattern15BacktraceParamsC1EOS0. Message: class ghidra.program.database.data.TypedefDB cannot be cast to class ghidra.program.model.data.Structure (ghidra.program.database.data.TypedefDB and ghidra.program.model.data.Structure are in unnamed module of loader ghidra.GhidraClassLoader @279f2327) (DemanglerCmd)

**To Reproduce**
Disassemble the  QT binary libQt5core.so.5.12.7 with Demangling enabled in the auto analysis and run the analysis

**Expected behavior**
I expected the analysis to complete within 30 mins to an hour (worst case) ,but it didn't terminate.

**Screenshots**

**Attachments**
I tried to attach the file as .7z, but even with ultra compression, it exceeds the threshold of 10 MB (~12 MB).

**Environment (please complete the following information):**
 - OS: Ubuntu 18.94
 - Java Version: OpenJKD 11
 - Ghidra Version: 9.1.1

**Additional context**
Please reach out to me and I can provide a  link to the file on my amazon cloud

**Comment by dragonmacher** [comment]
The errors above are not catastrophic, in terms of analysis.   Also, they should not be contributing to the long analysis run time.

I have verified that Ghidra can demangle the symbols shown above, but is running into an error applying the output of the demangle to your binary.  Specifically, I can see at least one spot in the code where a cast to `Structure` is being made without verifying the type first.   In your case, some other analyzer has created a `Typedef` for `QMessagePattern::BacktraceParams::~BacktraceParams()` before the demangler is attempting to make a class structure for that name.

I will update the code to verify the type before making the cast.  This fix will be soon merged-in, along with various other demangling fixes.  At that point you can try to analyze again, but I suspect there will still be other unresolved issues.

**Comment by kye4u2** [comment]
@dragonmacher  Thanks for the quick response

**Comment by dragonmacher** [comment]
The errors are fixed by 1161916.  

I am not sure if the speed issue has been fixed.    There are speed improvements for demangling currently being worked.  Some of these will appear in 9.2.3 and some will be in the next major release.
