### ISSUE TITLE
Infinite heap usage when attempting to decompile a function

### ISSUE THREAD

**Issue by HashFail** [NationalSecurityAgency/ghidra#1581]
**Describe the bug**
Infinite heap usage when attempting to decompile a function

**To Reproduce**
1. Download [DxeCore.zip](https://github.com/NationalSecurityAgency/ghidra/files/4269212/DxeCore.zip)
2. Extract "DxeCore"
3. Import into Ghidra
4. (optional) open htop or similar and sort by memory usage, so you can kill the decompiler process before it halts your machine
5. Go to FUN_000137e4 and attempt to decompile
6. Watch as your memory usage steadily climbs

**Expected behavior**
The function should be decompiled or fail.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: 1.8.0_232
 - Ghidra Version: 9.1.2

**Comment by caheckman** [comment]
Thanks for reporting this.  There is a fix for this in the master branch now, and it will be in the 9.2 release.
