### ISSUE TITLE
Ghidra unresponsive during DWARF import

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1584]
**Describe the bug**
Importing DWARF information causes ghidra to become unresponsive.

**To Reproduce**
1. Import binary containing DWARF debug
2. Import DWARF information
3. Ghidra hangs until the import completes if at all

**Expected behavior**
Ghidra should be responsive during import and should import the information at an acceptable rate.

**Screenshots**

**Attachments**
Unlinked arm binary
[rpi-i2c.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/4271181/rpi-i2c.tar.gz)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18363.657]
 - Java Version: 13.0.2
 - Ghidra Version: 9.2

**Additional context**
This appears to be a regression as it wasn't an issue until this week.

**Comment by astrelsky** [comment]
Another note is that it appears to take longer with the anonymous structure option enabled.

**Comment by dev747368** [comment]
eh, don't put too much effort into tracking this down.  We're aware of some non-dwarf changes to the data type manager that destabilized everything and we're working on it. Thanks for the heads up about it effecting dwarf so strongly.

**Comment by astrelsky** [comment]
> eh, don't put too much effort into tracking this down. We're aware of some non-dwarf changes to the data type manager that destabilized everything and we're working on it. Thanks for the heads up about it effecting dwarf so strongly.

Ah it is the dtm. I normally would have edited the comment in but didn't because it had already been seen and labeled. I'll change the title to reflect the underlying issue.

**Comment by astrelsky** [comment]
@dev747368 I just stumbled across something that may be of interest. I noticed that there is a MASSIVE performance difference with `DataTypeManager.resolve` when using the KEEP/REPLACE handlers. It may be that components of composite/function datatypes are being recursively replaced unnecessarily. It could be as simple as adding a check somewhere to see if the type is equivalent to what currently exists before replacing it.

**Comment by ghizard** [comment]
@astrelsky I've run into performance issues in these conflict handler for PDB.  @ghidra1 was looking at some possible improvements in this area that I think will help with PDB (and DWARF), and I believe @dev747368 might have had some changes in the works as well for DWARF. Not promising anything, and not sure if it would address this issue here. I'm mainly noting that we are aware of performance issues and hope for improvement.

**Comment by astrelsky** [comment]
@ghizard If you'd like I can put together a script and attach it along with a gdt built from libstdc++ that would make profiling the handlers a breeze.
