### ISSUE TITLE
"java.lang.RuntimeException: Unhandled relocation: RelocSmRepeat" when importing PEF/PPC file

### ISSUE THREAD

**Issue by jduerstock** [NationalSecurityAgency/ghidra#1587]
**Describe the bug**
The PEF loader throws an error about an unhandled relocation while loading a PEF file

**To Reproduce**
1. Attempt to import an affected PEF file
2. See error

**Expected behavior**
The file is valid and should be loaded properly

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0
 - Ghidra Version: 9.1

**Comment by beshelto** [comment]
FYI, I have a pull request out that fixes this: https://github.com/NationalSecurityAgency/ghidra/pull/5178
