### ISSUE TITLE
Error Language version when opening file in older Ghidra version

### ISSUE THREAD

**Issue by henryfung3a27** [NationalSecurityAgency/ghidra#1588]
So I have updated Ghidra to 9.1.2 when it released. Now I have discovered a new plugin and I want to use it. However it only supports Ghidra 9.1 and 9.1.1. When I opened Ghidra 9.1 with the same workspace as 9.1.2 and tried to open my file in CodeBrowser, an error shows up saying
 `Error Opening test.dll: Language version (V2.9 or later) required for 'x86:LE:32:default'`. 

I have generated a `x86_LE_32_default_29.lang` and `x86_LE_32_default_29.trans` when I have opened the file in CodeBrowser in 9.1.2 as mentioned [here](https://ghidra.re/courses/languages/versioning.html). I also found their 'friends' in the directory `ghidra_9.1-BETA_DEV\Ghidra\Processors\x86\data\languages\old` so I copied them to there. However, I still cannot open my file in Ghidra 9.1. Any help?

I think I should register the language or specifically ask my file to use it but I cannot find the button.

Also, I know I can just create a new workspace and import the file as fresh but I have already made changes and comments to it and I don't wanna lose them/manually edit them again. 

Thanks

**Comment by astrelsky** [comment]
What plugin? It might be easier to go forward instead of backward. Rebuilding the plugin for 9.1.2 should suffice as any required changes would be subtle.

**Comment by GhidorahRex** [comment]
You won't be able to simply generate the .lang and .trans files to open the program in 9.1. The x86 parse tree is functionally different between the two versions. Your code won't be able to find what it's looking for.

I would strongly suggest following @astrelsky's advice with rebuilding the pluging for 9.1.2.

**Comment by henryfung3a27** [comment]
Thanks. Rebuilding it to 9.1.2 works.
