### ISSUE TITLE
Building Ghidra from source

### ISSUE THREAD

**Issue by mikeybro** [NationalSecurityAgency/ghidra#1597]
I've been unable to work around this error, any tips suggestions or further info needed to assist me?

![error](https://user-images.githubusercontent.com/13041084/75943686-ef19dc00-5e52-11ea-90f8-43f71cc1491d.PNG)

**Comment by astrelsky** [comment]
> I've been unable to work around this error, any tips suggestions or further info needed to assist me?
> 

The output of `"C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe"` would be useful. The gradle scripts use the output from that command to set the `VISUAL_STUDIO_TOOLS_VERSION_DEFAULT` variable which I think might be the issue.

If you get `... is not recognized as an internal or external command...` then any details of your visual studio installation would be helpful.

**Comment by mikeybro** [comment]
I am uninstalling and reinstalling VS2017, what packages from the installer should I include? Earlier I had an error saying something NVIDIA, I think I had to many SDKs installed.

**Comment by mikeybro** [comment]
Well Uninstalling and removing some of the many SDK's and components and reinstalling VS 2017 with ATL and other components seemed to do the trick.... Now I can teach myself how to program and reverse engineer, or something.... 
![works](https://user-images.githubusercontent.com/13041084/75953142-f4385480-5e6d-11ea-931e-ac668ac51134.PNG)

**Comment by astrelsky** [comment]
Wonderful. As a side note you seem to also be encountering #1592 . That should be fixed soon. 

If you're starting with no prior programming or reversing experience the best advice I can give is to not get discouraged. Its common do give up and find yourself coming back to try and learn again years later. If you don't have any prior knowledge of asm I'd recommend starting with a risc architecture, instead of x86 based, as the instructions would be easier to follow.

**Comment by mikeybro** [comment]
![works](https://user-images.githubusercontent.com/13041084/76029497-d57ba180-5ef1-11ea-898d-7ee73b858a50.PNG)

**Comment by mikeybro** [comment]
It works thanks

**Comment by astrelsky** [comment]
> Thanks for the motivation, I have a degree, this here piece of paper is all I need :P, plus 10 hours of study and working on my workstation everyday
> I've pulled the update lets build and click around
> ![normal](https://user-images.githubusercontent.com/13041084/76028868-ab75af80-5ef0-11ea-80f9-bf4fed412dc5.PNG)
> 
> Are all these errors normal? Does it look normal?

Those will only effect the documentation output and can be ignored. I have them fixed in #1552
