### ISSUE TITLE
AssertException - Cannot add the same action more than once. Action: Change Password (FrontEndPlugin)

### ISSUE THREAD

**Issue by magcius** [NationalSecurityAgency/ghidra#1604]
**Describe the bug**
This error seems to happen occasionally when working on shared projects.

**To Reproduce**
Unfortunately, I have no consistent repro steps. It seems to happen randomly when doing unrelated actions. I was retyping a variable when it happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/40890/76146960-ac235880-604c-11ea-92b4-73299fbec22e.png)

**Environment (please complete the following information):**
Screenshot has build information.

**Comment by ghidra1** [comment]
Problem will be fixed with Ghidra 9.2 (change made to master branch)
