### ISSUE TITLE
Modify non-returning function behaviour

### ISSUE THREAD

**Issue by Alex97** [NationalSecurityAgency/ghidra#1611]
It seems to me that when a code path inside a function ends with a call to a non-returning function,
the whole function gets marked as non-returning. For example, if I have the following, decompiled code:

```
void f() {
    if (cond) {
        exit(1);
    } else {
        return;
    }
}
```

The function f gets marked as non-returning, because exit is non-returning. Is there a way to modify this behavior, given the fact that not all code paths end in non-returning calls?

**Comment by astrelsky** [comment]
Are you sure the entire function is being marked as no return? If so then this affects every function where an assert statement is used.

**Comment by Alex97** [comment]
This is the disassembly of the function where I first encountered this problem:
![git](https://user-images.githubusercontent.com/6563124/76326001-ae0d4600-62f0-11ea-9fb9-89abc6714588.png)
The whole `decodeString` function is being marked as non-returning, despite having a single path
ending in an exit. I have observed the same behavior with other functions, for example some
calling `__stack_chk_fail()`.
This is an ARM shared object.
I haven't done much research besides this, but I will try to reproduce the issue and come back with
an actual file that exhibits the problem.

**Comment by emteere** [comment]
Your decompilation doesn't show that decodeString () is marked as noreturn.  It is not normal behavior to mark a function as non-returning, even if the function has a single path to a non-returning function.
So the following would not cause the function foo() to be non-returning:
   int foo() {
      exit(-1);
   }
foo() is detected as non-returning, if the functions calling foo() show some indication that the compiler knew foo() was non-returning, such as dropping directly into a known function right after a call to foo().

In the assembly listing, is the function decodeString() actually marked non-returning?
If it is, that would imply that there are some code flow issues in functions calling decodeString().

stack_chk_fail() is marked as a known non-returning function, however functions calling stack_chk_fail() would not cause the calling function to be marked non-returning.
