### ISSUE TITLE
Abort during analysis due to ghidra.util.exception.UnableToSwingException

### ISSUE THREAD

**Issue by yaspoon** [NationalSecurityAgency/ghidra#1613]
While auto analysing a 333MB Windows PE Executable Ghidra fails after about the 3 hour mark due to: ERROR	(BackgroundCommandTask) Command Failure: An unexpected error occurred while processing the command: Auto Analysis java.lang.RuntimeException: Timed-out waiting to run a Swing task--potential deadlock!

It would appear that it is at least near completion when this happens and is quite frustrating as it throws away all of the auto analysis data and you must start from scratch again.

I found https://github.com/NationalSecurityAgency/ghidra/issues/1179 and have increased the swing timeout to 300 seconds and am attempted for the 3 time. (I also tried Ghidra 9.1)

Attached is a copy of the error log.
[ghidra_error.txt](https://github.com/NationalSecurityAgency/ghidra/files/4310717/ghidra_error.txt)

1. Import 333MB Windows PE Executable
2. Click auto analyze
3. Aftrer 3 hours two error dialogs pop up saying an unexpected error has occurred.
4. Click OK
5. All the auto analysis upto that point is gone.

Arch Linux 5.4.14-zen1-1-zen
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
Ghidra 9.1.2 PUBLIC

**Comment by dragonmacher** [comment]
This is a problem we need to fix.

In the meantime, you can change the timeout value so this should no longer happen.   Assuming you are running from a production distribution, edit the `{install dir}/support/launch.properties` file to add this line:
`VMARGS=-Dghidra.util.Swing.timeout.seconds=3600`

where **3600** can be any value you wish.  The default is **20**.   Setting this to a a high value effectively disables the timeout.

**Comment by dragonmacher** [comment]
> I found #1179 and have increased the swing timeout to 300 seconds and am attempted for the 3 time. (I also tried Ghidra 9.1)

I just saw this in your message.   My suggestion above still applies, in the sense that you can completely disable the feature with a long enough timeout.  I suggested an hour.  Keep in mind that while the work is being processed for the **Swing** call, the UI will be locked.

**Comment by dragonmacher** [comment]
Also, while looking at the stack trace you provided, we cannot see why your work would have been lost.  This would normally require a `RollbackException` to have happened.    Are there other messages near this one in your application log file (in `{user home}/.ghidra/.ghidra-version/`)

**Comment by yaspoon** [comment]
I've uploaded some screen shots of the log and error dialog. I'm not sure that they really give much more information. I set the swing timeout to 300 seconds and it still failed which is where these screen shots came from. Anything else you would recommend I try to provide better debug output?

![Screenshot from 2020-03-11 17-36-18](https://user-images.githubusercontent.com/807332/76403243-bd67be80-63d8-11ea-984f-e4906a59a447.png)
![Screenshot from 2020-03-11 17-50-35](https://user-images.githubusercontent.com/807332/76403248-be98eb80-63d8-11ea-93de-117da425d8d4.png)
![ghidra_log](https://user-images.githubusercontent.com/807332/76403253-bf318200-63d8-11ea-925e-99a8f954b15f.png)

**Comment by dragonmacher** [comment]
>  I set the swing timeout to 300 seconds

Try something much larger, like 3600.   The UI will be unresponsive when the issue above happens, but it should eventually return.

**Comment by yaspoon** [comment]
I tried Ghidra 9.0.4 today and it worked. I think I've been setting the swing timeout wrong so I read your post properly this time and modified {install dir}/support/launch.properties for Ghidra 9.1.2 and am reanalysing the binary. I'll also check the application log you mentioned.

**Comment by uBadRequest** [comment]
@dragonmacher Getting the same error while analyzing a Go binary. I have installed this extension -> https://github.com/felberj/gotools, and select this as the language, x86:LE:64:golang:default. 

Added this to my launch properties: "VMARGS=-Dghidra.util.Swing.timeout.seconds=3600"

```
Uncaught Exception! 
RuntimeException - Timed-out waiting to run a Swing task--potential deadlock!
java.lang.RuntimeException: Timed-out waiting to run a Swing task--potential deadlock!
	at ghidra.util.Swing.runNow(Swing.java:180)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at ghidra.framework.data.DomainObjectChangeSupport.flush(DomainObjectChangeSupport.java:143)
	at ghidra.framework.data.DomainObjectAdapter.flushEvents(DomainObjectAdapter.java:246)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.taskFailed(ToolTaskManager.java:451)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:143)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: ghidra.util.exception.UnableToSwingException: Timed-out waiting for Swing thread lock in 20 SECONDS
	at ghidra.util.Swing.waitFor(Swing.java:259)
	at ghidra.util.Swing.runNow(Swing.java:238)
	at ghidra.util.Swing.runNow(Swing.java:166)
	... 7 more

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /usr/lib/jvm/java-11-openjdk-amd64
JVM Version: Debian 11.0.7-ea
OS: Linux 5.6.0-kali2-amd64 amd64
Workstation: NitroZeus.onebyte

```

**Comment by pabx06** [comment]
hi.
same issue on a 100MB ARM:BE:v8t firmware.
```
Uncaught Exception! 
RuntimeException - Timed-out waiting to run a Swing task--potential deadlock!
java.lang.RuntimeException: Timed-out waiting to run a Swing task--potential deadlock!
	at ghidra.util.Swing.runNow(Swing.java:180)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at ghidra.framework.data.DomainObjectChangeSupport.flush(DomainObjectChangeSupport.java:143)
	at ghidra.framework.data.DomainObjectAdapter.flushEvents(DomainObjectAdapter.java:246)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.taskFailed(ToolTaskManager.java:451)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:143)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: ghidra.util.exception.UnableToSwingException: Timed-out waiting for Swing thread lock in 20 SECONDS
	at ghidra.util.Swing.waitFor(Swing.java:259)
	at ghidra.util.Swing.runNow(Swing.java:238)
	at ghidra.util.Swing.runNow(Swing.java:166)
	... 7 more

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /usr/lib/jvm/java-13-oracle
JVM Version: Oracle Corporation 13.0.2
OS: Linux 4.15.0-99-generic amd64
Workstation: localhost

```
the **exception message** seems to use a constant strings: it always reports 20 SECONDS. i expect 7600seconds even with :
```
$ grep timeout support/launch.properties 
VMARGS=-Dghidra.util.Swing.timeout.seconds=7600

$ grep MAX  ghidraRun
# the physical memory available to the OS. Uncomment MAXMEM setting if non-default value is needed.
MAXMEM=8G
```

**Comment by dragonmacher** [comment]
@pabx06 Thanks for debugging this.  You have pointed out that the case is incorrect in my previous suggestion.

@uBadRequest @yaspoon When you change this value in the `{install dir}/support/launch.properties` file, be sure that the 's' in 'Swing' is lower-case.  This is the correct text:
`VMARGS=-Dghidra.util.swing.timeout.seconds=3600`

**Comment by dragonmacher** [comment]
Analysis has been updated to not undo all changes when an exception happens.     The timeout issue can be changed as needed by users, as seen above.
