### ISSUE TITLE
release install pack which does not require java installation

### ISSUE THREAD

**Issue by houjingyi233** [NationalSecurityAgency/ghidra#1614]
**Is your feature request related to a problem? Please describe.**
As you may have known that many people are having problems using ghidra because ghidra requires install and setup java properly. And some people may do not want to contaminate his system and they do not want to install java.

**Describe the solution you'd like**
We can release install pack which does not require java installation so people can use it out of box. For example, we can pack jar to exe on windows and we can make a dmg on macos which contains JDK and already set everything properly. Someone already did it:

https://gist.github.com/yifanlu/e9965cdb148b550335e57899f790cad2

**Comment by ryanmkurtz** [comment]
Ghidra supports launching with Java's that have contaminated the system via an installer, as well as in-place Java extractions that minimally impact the system.  I recommend you read the [Installation Guide](https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/master/GhidraDocs/InstallationGuide.html) to see all the possibilities.
