### ISSUE TITLE
Ghidra Disassembler and Decompiler Doesn't Recognize Puts...

### ISSUE THREAD

**Issue by mendax47** [NationalSecurityAgency/ghidra#162]
**To Reproduce**
1. Just Write A Sample HelloWorld Program In C
2. Open It On Ghidra
3. Baaammmm... .text insted of puts...? XD 

**Screenshots**
1. Retdec
![image](https://user-images.githubusercontent.com/6140928/54122924-9e7ec700-4428-11e9-8cd6-2a73163402b6.png)

2. IDA:
![image](https://user-images.githubusercontent.com/6140928/54122943-ab031f80-4428-11e9-846a-cb5286ad8e12.png)
![image](https://user-images.githubusercontent.com/6140928/54122975-b9e9d200-4428-11e9-8054-31d9b3325713.png)

3. Meanwhile In Ghidra:
![image](https://user-images.githubusercontent.com/6140928/54123048-e1409f00-4428-11e9-8a6d-8e98400e9f96.png)
![image](https://user-images.githubusercontent.com/6140928/54123084-fa495000-4428-11e9-88a2-fd04db04c42d.png)

**Comment by StepS-** [comment]
More info on this here: https://twitter.com/marcan42/status/1103628581060587521

**Comment by ryanmkurtz** [comment]
Duplicate of #761
Duplicate of #1061
