### ISSUE TITLE
68000/big/32/MC68020 decompile fail

### ISSUE THREAD

**Issue by oziphantom** [NationalSecurityAgency/ghidra#1620]
**Describe the bug**
There is a really simple function and the tool just translates it to "return"

**To Reproduce**
Given the following 68K
```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined getDistaceD1_2toD5_6inD7()
             undefined         D0b:1          <RETURN>
             undefined2        Stack[-0x8]:2  local_8                                 XREF[1]:     0002098e(R)  
                             getDistaceD1_2toD5_6inD7                        XREF[1]:     FUN_00020994:000209a2(c)  
        0002097a 48 a7 60 00     movem.w    {  D2w D1w},-(SP)
        0002097e 94 46           sub.w      D6w,D2w
        00020980 6c 02           bge.b      LAB_00020984
        00020982 44 42           neg.w      D2w
                             LAB_00020984                                    XREF[1]:     00020980(j)  
        00020984 92 45           sub.w      D5w,D1w
        00020986 6c 02           bge.b      LAB_0002098a
        00020988 44 41           neg.w      D1w
                             LAB_0002098a                                    XREF[1]:     00020986(j)  
        0002098a d2 42           add.w      D2w,D1w
        0002098c 3e 01           move.w     D1w,D7w
        0002098e 4c 9f 00 06     movem.w    (SP=>local_8)+,{  D1 D2}
        00020992 4e 75           rts
```
and it gives you

```
void getDistaceD1_2toD5_6inD7(void)

{
  return;
}
```
**Expected behavior**
this function is clearly should be something along the lines of 
```
D2 = abs((short)D6-(short)D2);
D1 = abs((short)D5-(short)D1);
D7 = D1+D2;
return D7;
```

**Screenshots**

**Attachments**
I've attached the xml log from the "Debug Function Compilation" button in the Decompile Window. [68K0002097a.zip](https://github.com/NationalSecurityAgency/ghidra/files/4317864/68K0002097a.zip)

**Environment (please complete the following information):**
 - OS: Windows 10.0.18363 
 - Java Version: 11.0.6.10.1-1 corretto 
 - Ghidra Version: 9.1.2_PUBLIC_20200212

**Additional context**
I have this plug in installed which I patched to work on 9.1.2 by changing the version number in the properties file. https://github.com/lab313ru/ghidra_sega_ldr

**Comment by GhidorahRex** [comment]
For whatever reason, the function isn't getting the proper spec. You could manually edit the function to add inputs and specify the return value as being in D7, since the default spec for the 68000 has the return value being placed in D0.

The unaffected register list looks wrong in the .cspec at first glance. Clearly there are multiple 'unaffected' registers that are being affected by this function.

Are there a lot of functions in the binary that use D7 as the output register?

**Comment by oziphantom** [comment]
D1 seems to be the most common, but only starting to dig around. D7 only has a few so far that I have seen. 
Doing the manual edit ( the interface seems really clunky is there a faster way to do it than add select word, give name, then scroll to find register, then do this per each one?? )
```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             word getDistaceD1_2toD5_6inD7(word D1X, word D1Y, word D
             word              D7w:2          <RETURN>
             short              D1w:2          D1X
             short              D2w:2          D1Y
             short              D5w:2          D2X
             short              D6w:2          D2Y
             word              Stack[-0x8]:2  local_8                                 XREF[1]:     0002098e(R)  
                             getDistaceD1_2toD5_6inD7                        XREF[1]:     calcDistanceD1_D2toCharD0inD7:00
        0002097a 48 a7 60 00     movem.w    {  D1Y D1X},-(SP)
        0002097e 94 46           sub.w      D2Y,D1Y
        00020980 6c 02           bge.b      LAB_00020984
        00020982 44 42           neg.w      D1Y
                             LAB_00020984                                    XREF[1]:     00020980(j)  
        00020984 92 45           sub.w      D2X,D1X
        00020986 6c 02           bge.b      LAB_0002098a
        00020988 44 41           neg.w      D1X
                             LAB_0002098a                                    XREF[1]:     00020986(j)  
        0002098a d2 42           add.w      D1Y,D1X
        0002098c 3e 01           move.w     D1X,D7w
        0002098e 4c 9f 00 06     movem.w    (SP=>local_8)+,{  D1X D1Y}
        00020992 4e 75           rts

```
now yields
```
word getDistaceD1_2toD5_6inD7(word D1X,word D1Y,word D2X,word D2Y)

{
  short sVar1;
  short sVar2;
  word local_8;
  
  sVar2 = D1Y - D2Y;
  if (D1Y < D2Y) {
    sVar2 = -sVar2;
  }
  sVar1 = D1X - D2X;
  if (D1X < D2X) {
    sVar1 = -sVar1;
  }
  return sVar1 + sVar2;
}
```

**Comment by oziphantom** [comment]
How do you make it understand that a register gets a value from RAM and its not passed it?
Given
```                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             word getRAMAddrForceMemberStats(byte param_1)
             word              D0w:2          <RETURN>
             char              D0b:1          param_1
                             getRAMAddrForceMemberStats                      XREF[29]:    getForceMemberLevel:000223b8(c), 
                                                                                         ..snip..
        000225f2 4a 00           tst.b      param_1
        000225f4 6a 0a           bpl.b      LAB_00022600
        000225f6 02 00 00 7f     andi.b     #0x7f,param_1
        000225fa 41 f8 c6 28     lea        (DAT_ffffc628).w,A0                              = ??
        000225fe 60 04           bra.b      LAB_00022604
                             LAB_00022600                                    XREF[1]:     000225f4(j)  
        00022600 41 f8 9c 92     lea        (DAT_ffff9c92).w,A0                              = ??
                             LAB_00022604                                    XREF[1]:     000225fe(j)  
        00022604 02 40 00 ff     andi.w     #0xff,param_1
        00022608 c0 fc 00 28     mulu.w     #0x28,param_1
        0002260c d0 c0           adda.w     param_1,A0
        0002260e 4e 75           rts
```
It gives
```
word getRAMAddrForceMemberStats(char param_1)

{
  ushort uVar1;
  
  uVar1 = (ushort)(byte)param_1;
  if (param_1 < '\0') {
    uVar1 = (ushort)(param_1 & 0x7f);
  }
  return (word)(uVar1 * 0x28);
}
```
which completely misses the "looks up value from RAM and then add Param_1 * 0x28 to it"

**Comment by GhidorahRex** [comment]
@oziphantom In this case it looks like it's expecting the return value to be in D0w rather than A0.

**Comment by oziphantom** [comment]
so if the c code doesn't think the register is "used" it strips out all and any code that involves the register?

**Comment by GhidorahRex** [comment]
Yes, and usually that's a good thing. Sometimes code is written that only needs one of the result register values, while the rest are considered extraneous - especially flag and status registers, but there are other examples.

Normally, Ghidra does very well at this because the code is produced by a compiler or is written to adhere to a specific calling convention. In the case of your binary it appears that it is hand-written assembly that is not adhering to the normal 68000 calling convention (or any convention for that matter).

**Comment by oziphantom** [comment]
is there a script or some other method to make it scan and add "all registers" that are modified, save ones that are explicitly push/pop'd to the param list? I would think a lot of 68K code is either 100% ASM or at least partly hand ASM. I also wouldn't be surprised if C compilers from back in the day don't adhere to a "standard" for calling and/or change the calling between revisions. 

How do I set the CCR for the return type. Having a bool based in the C flag for example?

**Comment by GhidorahRex** [comment]
For the 68000, you would set the return register to be whatever status flag you're concerned about. For the C flag, it would be the `CF` register. For the Z flag, the `ZF` register, etc. If you want to return the entire CCR, you would use the `SR` (status register).

**Comment by GhidorahRex** [comment]
I'm going to close this, since I believe the issue has been sufficiently addressed.

**Comment by oziphantom** [comment]
So it's not possible to do in a script?
