### ISSUE TITLE
Copy/Export (DWARF) Program Tree and Symbol Tree

### ISSUE THREAD

**Issue by r4bit999** [NationalSecurityAgency/ghidra#1623]
With the case having an binary with lots of debug information i have a LOT of entries in my Symbol Tree and also in the DWARF Program Tree; e.g. 1000 < 10000, classnames, function names etc.

How can i copy or access this entries? This would really help me a lot in my current student research. Thanks a lot!

Example feature could be:
(Selection of Entries) => Right Click => Copy Tree as LIST | XML | JSON

**Comment by dragonmacher** [comment]
You can pick a node in the tree, right-click and select **Export C Header...**   If this output is not sufficient, then you could always write a script to perform the work.    I will attach an example script you could use to get started.

[DeveloperDumpAllTypesScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/4324724/DeveloperDumpAllTypesScript.java.txt)

**Comment by r4bit999** [comment]
I found your named export function at the "DataTypeManager"; Thanks! I have the following:

```
ProgramTrees:
...
...
 + ServiceV1.cpp
 + Network.c
 + SystemService.h
 - Console.cpp
     loadConfig
     initConsole
 + Webserver.cpp
...
...
_________________________
-------------| DWARF  x |
```

What i primarily need is a list of that cpp,h,c files which are listed in the Program Tree

`import ghidra.app.services.DataTypeManagerService;`

So there is probably a `ghidra.app.services.ProgramTreeService;` which i can access?

**Comment by dragonmacher** [comment]
The **Symbol Table** will allow you to export all/any rows you choose into a `CSV` format.   This table has all symbols applied in the program.

The `ProgramTreeService` will only allow you to manipulate the UI, but not in any meaningful way.  I believe while it is technically possible to get what you seek from the **Program Tree**, there is no service interface to do so.  Further, to do this would be advanced programming for which we have no examples.

You *should* be able to get the info you need from The **Data Type Manager**  and or **Symbol Table** widgets.

**Comment by r4bit999** [comment]
Window -> **Symbol Table** and export as `CSV` worked well. 

Thanks a lot @dragonmacher ! 

Luckily the table structure has the `namespace` column which contain almost the information i mentioned above. Unfortunately it does not always match the .cpp or .c filenames in the Program Tree.

Well it run a few minutes and i got over 300.000 entries. I think i can work for now with that information (namespace).

**Comment by r4bit999** [comment]
If someone get a solution for retrieving the **Program Tree** entries thanks for sharing!
