### ISSUE TITLE
Add a desktop entry

### ISSUE THREAD

**Issue by abelfodil** [NationalSecurityAgency/ghidra#1624]
**Is your feature request related to a problem? Please describe.**
I want to open ghidra using an application launcher (as opposed to using the command line).
Application launchers usually read desktop entries (https://wiki.archlinux.org/index.php/Desktop_entries)

**Describe the solution you'd like**
Add https://aur.archlinux.org/cgit/aur.git/tree/ghidra.desktop?h=ghidra-desktop

**Describe alternatives you've considered**
See https://bugs.archlinux.org/task/65812

**Additional context**
See https://bugs.archlinux.org/task/65812

**Comment by anthraxx** [comment]
best would be great if that desktop file could include icons.

PS: I would consider removing the Version, otherwise it may be required to create the desktop file as part of a build stage so the Version will not be out of sync or require manual editing before releases.

**Comment by ryanmkurtz** [comment]
See #1556

**Comment by anthraxx** [comment]
thx, i guess this can be closed

**Comment by flavioarp** [comment]
If it would be any helpful, this Windows equivalent of this is creating a .bat file that calls ghidraRun.bat, for instance:

```
@echo off
C:\ghidra\ghidraRun.bat
```

Furthermore, you can create a shortcut for the created batch file on your desktop and also set ghidra's icon on it, which lives in ```C:\ghidra\support\ghidra.ico```
