### ISSUE TITLE
Ghidra application version mismatch

### ISSUE THREAD

**Issue by abelfodil** [NationalSecurityAgency/ghidra#1625]
**Describe the bug**
I tried to install [ret-sync](https://github.com/bootleg/ret-sync/blob/master/ext_ghidra/dist/ghidra_9.1.2_PUBLIC_20200310_retsync.zip) and [Ghidra-Cpp-Class-Analyzer](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/releases/download/1.4/ghidra_9.1.2_PUBLIC_20200226_Ghidra-Cpp-Class-Analyzer.zip) on ghidra 9.1.2 but could not because apparently it is incompatible with my current version of ghidra (which is not true).

**To Reproduce**
Install the listed extensions on ghidra 9.1.2

**Expected behavior**
Installation should succeed

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Java Version:  11.0.6
 - Ghidra Version: 9.1.2

**Additional context**
After changing this [line](https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_9.1.2_build/Ghidra/application.properties#L2) to 9.1.2, the installation succeeds.

**Comment by ryanmkurtz** [comment]
Pretty much a duplicate of #1193.
