### ISSUE TITLE
Navigation history in snapshot views operates on the main listing view

### ISSUE THREAD

**Issue by jroimartin** [NationalSecurityAgency/ghidra#1626]
**Describe the bug**
Navigation history in snapshot views operates on the main listing view instead of the snapshot view itself.

**To Reproduce**
1. Click on the snapshot view icon, for instance, in the listing view.
2. Move to a different location inside the snapshot view (e.g. double click on a function name).
3. Click on the "Go to previous location" icon in the snapshot view's toolbar.
4. See that it is the main listing view the one going back in the location history.

**Expected behavior**
I would expect the "Go to previous location" icon in the snapshot view's toolbar to operate on the snapshot view.

**Environment (please complete the following information):**
 - OS: GNU/Linux
 - Java Version: 11.0.6
 - Ghidra Version: 9.1.2

**Additional context**
If instead of clicking the  "Go to previous location" icon, you open the location history list pushing the black arrow next to it, clicking in a previous history item would actually operate on the snapshot view, as expected.

Also, snapshot view's help states that global actions operate now on whatever component that has the focus, which fits the described expected behavior.

**Comment by dragonmacher** [comment]
I confirmed this is broken in 9.1.2.

This is working as expected in master.  The fix should be in 9.2
