### ISSUE TITLE
How to delete/prevent auto-analysis / decompiling from auto-adding memory references?

### ISSUE THREAD

**Issue by brandonros** [NationalSecurityAgency/ghidra#1627]
I want to feed Ghidra listing decompiler output to an emulator.

![image](https://user-images.githubusercontent.com/8949910/76588242-ea8d9d00-64bc-11ea-9efb-35e6715054b0.png)

Instead of showing `st.w [a2]0x6020,d15`, export + display keep translating this to instruction to `ram:80375ee0 59 2f 20 06     st.w       [a2]offset DAT_f0036020 &0xffff, d15`, which is extremely annoying.

I've tried lots of settings. How can I disable this `[a2]0x6020` -> `[a2]offset DAT_...` conversion that breaks the decompiled output from being usable in an emulator?

**Comment by pelrun** [comment]
I think you need to supply some more information about what you're actually trying to accomplish, because this approach is probably not the best way to do it.

First, that's the disassembly listing, not the decompiler (which generates C-like code). 

Second, you're kinda asking Ghidra to not do the very thing it's designed for, so it's not surprising that it's making your life difficult. Is it not possible to just feed your emulator the raw machine code bytes for the block you're interested in instead? After all, all it's going to do with an assembly listing is reassemble it to those bytes anyway...

**Comment by emteere** [comment]
Are you trying to feed the disassembly to an emulator that takes assembly code?

You can run a script to dump the instructions in any format you want.  The display is for visual consumption and markup.

There is also an emulator in ghidra that works on the pcode semantics that are attached to each instruction.  Not a real hardware emulator/simulator, but more of a model of the instruction.

**Comment by brandonros** [comment]
I just feel like this is either a bug or a feature request.

Make it so that what is displayed in `disassembly listing` (or what is exported in File -> Export Program -> ASCII) has the option to print the *actual* disassembled instruction (`st.w [a2]0x6020,d15`) instead of translating it into a format that is not readable by a machine with automatic memory reference addition with no way to turn it off (`st.w [a2]offset DAT_f0036020, d15 `)

**Comment by brandonros** [comment]
> You can run a script to dump the instructions in any format you want. The display is for visual consumption and markup.

Can you give me an example or a sample on how to do that?

**Comment by pelrun** [comment]
Look at IterateInstructionsScript.java and mark_in_out.py in the Script Manager, both of which read individual Instruction objects from the program.

**Comment by brandonros** [comment]
For anybody else:

Window -> Script Manager -> Create New Script icon

```python
instructions = currentProgram.listing.getInstructions(True)
for instruction in instructions:
  formatted_bytes = ''.join(format(x, '02x') for x in bytearray(instruction.bytes)) 
  print "%s %s %s %s" % (instruction.address,  instruction.getLength(), formatted_bytes, instruction)
```

voila
