### ISSUE TITLE
Large structures crash the editor

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#1631]
**Describe the bug**
Large structures crash the editor

**To Reproduce**
1. Create a big structure (around 0x20000 bytes or more)
2. Open editor
3. OOM crash

**Expected behavior**
It should be possible to disable the byte viewer for large structures

**Comment by ryanmkurtz** [comment]
Possibly fixed by #1141 in 9.2.  What version of Ghidra are you running?

**Comment by sad-dev** [comment]
> Possibly fixed by #1141 in 9.2. What version of Ghidra are you running?

9.1.2

**Comment by ghidra1** [comment]
As @ryanmkurtz  indicated it is fixed for 9.2 and is in the master branch.  Note that this fix only addresses rendering issues related to the bit view component - but it was a big performance problem.  There are other performance related issues which can arise when manipulating very large non-aligned structures.
