### ISSUE TITLE
Exception in AbstractAddressSpace.makeValidOffset

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#1632]
**Describe the bug**
Calling HighFunction.getVarnodes(getAddressFactory().getAddressSpace("stack")) can lead to an exception in AbstractAddressSpace.makeValidOffset

min    = ffff ffff 8000 0000
max   = 7fff ffff
offset = 7fff ffff ffff ffff

**To Reproduce**

The easiest trigger I have is (where currentLocation is in the decompiler)
AddressSpace stackSpace = getAddressFactory().getAddressSpace("stack");
HighFunction hf = ((DecompilerLocation) currentLocation).getDecompile().getHighFunction();
hf.getVarnodes(stackSpace);

**Screenshots**
![Exception](https://user-images.githubusercontent.com/55233728/76627722-7e6f6f80-6576-11ea-9b66-c4caf51aa1eb.png)

**Environment (please complete the following information):**
ghidra 9.1.2

**Comment by sad-dev** [comment]
I peeked into the source code:

in VarnodeBank.java

	public Iterator<VarnodeAST> locRange(AddressSpace spaceid) {
		VarnodeAST searchvn1 = new VarnodeAST(spaceid.getAddress(0),0,0);
		searchvn1.setInput(true);
		**VarnodeAST searchvn2 = new VarnodeAST(spaceid.getAddress(Long.MAX_VALUE),0,0);**
		searchvn2.setInput(true);
		return locTree.subSet(searchvn1,searchvn2).iterator();
	}

using LONG (64 bit) on 32 and below address spaces appears to trigger the crash

**Comment by caheckman** [comment]
Fix is available in the master branch and will be in the 9.2 release.
