### ISSUE TITLE
Cannot Edit Component for a struct pointer array

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#1633]
9.2 / linux

```
enum foobars {
    FOOBAR_1 = 1,
    FOOBAR_2 = 2,
    FOOBAR_3 = 3,
};
struct foobar {
    unsigned char *mem;
    unsigned int size;
};
struct foobar_list {
    foobar *[1000] items;
    enum foobars[1000] types;
    unsigned int pos;
};
```

If you have the above structs created as data types, trying to edit the component `items` in the Structure Editor results in an error `Can only edit a structure, union or enum.`.  You can however edit the `types`

Is this an issue of a struct pointer array being treated as an opaque pointer array?

**Comment by astrelsky** [comment]
It appears that you can't edit the component if items is declared as `foobar **items` either. The `getDataType` method of an array or pointer is most likely only being invoked once instead of recursively.
