### ISSUE TITLE
M68000 doesn't support BHS instruction.

### ISSUE THREAD

**Issue by theclashingfritz** [NationalSecurityAgency/ghidra#164]
Currently the Motorola 68000 disassembler does not support the BHS instruction. Which is used in various thing including Sonic 3 disassemblies. 

Support for the BHS instruction would be nice as the BCC instruction works similar but isn't the BHS instruction and will not disassemble properly in place of the BHS instruction. 

References if needed: http://wpage.unina.it/rcanonic/didattica/ce1/docs/68000.pdf

**Comment by mumbel** [comment]
The link states they are mnemonics and are the same

**Comment by theclashingfritz** [comment]
Just because you can replace one with another doesn't mean they process the same. 
![image](https://user-images.githubusercontent.com/24818734/54249547-f3990680-4516-11e9-8303-5985c44175cc.png)

**Comment by theclashingfritz** [comment]
And if you can replace one with the other in terms of processing, BCC doesnt support .s or any of those sub-extensions. Which is an issue.

**Comment by mumbel** [comment]
lol, suggesting mnemonics aren't the same thing without anything to back it up?

```
00000000 <Is20OrHigherBCC-0x12>:
   0:	0c79 0000 0000 	cmpiw #0,0 <Is20OrHigherBCC-0x12>
   6:	0000 
   8:	6408           	bccs 12 <Is20OrHigherBCC>
   a:	33fc 0000 0000 	movew #0,0 <Is20OrHigherBCC-0x12>
  10:	0000 

00000012 <Is20OrHigherBCC>:  
  12:	0c79 0000 0000 	cmpiw #0,0 <Is20OrHigherBCC-0x12>
  18:	0000 
  1a:	6408           	bccs 24 <Is20OrHigherBHS>
  1c:	33fc 0000 0000 	movew #0,0 <Is20OrHigherBCC-0x12>
  22:	0000 
```
```     
        cmpi.w    #$0020,d0
        bcc.s     Is20OrHigherBCC
        move.w    #$0000,d0
Is20OrHigherBCC:
        cmpi.w    #$0020,d0
        bhs.s     Is20OrHigherBHS
        move.w    #$0000,d0
Is20OrHigherBHS:
```

```
                             LAB_00010000                                    XREF[1]:     _elfSectionHeaders::00000034(*)  
        00010000 0c 79 00        cmpi.w     #0x0,(DAT_00000000).l
                 00 00 00 
                 00 00
        00010008 64 08           bcc.b      Is20OrHigherBCC
        0001000a 33 fc 00        move.w     #0x0,(DAT_00000000).l
                 00 00 00 
                 00 00
                             Is20OrHigherBCC                                 XREF[1]:     00010008(j)  
        00010012 0c 79 00        cmpi.w     #0x0,(DAT_00000000).l
                 00 00 00 
                 00 00
        0001001a 64 08           bcc.b      Is20OrHigherBHS
        0001001c 33 fc 00        move.w     #0x0,(DAT_00000000).l
                 00 00 00 
                 00 00

```

BCC and BHS produce the same bytes,  You may not like how ghidra handles it, but stop with the BCC and BHS aren't the same instruction.

**Comment by theclashingfritz** [comment]
Fair enough, It seems it's just bad disassembling on my end.

You have made yourself completely clear.
Understood.
I, your humble servant, will follow you to the utmost...
