### ISSUE TITLE
About Bytes View

### ISSUE THREAD

**Issue by mafusuke** [NationalSecurityAgency/ghidra#1641]
How do I correctly display the ?? in the image below?
Displayed correctly in HxD.
![image](https://user-images.githubusercontent.com/43488869/76859624-0918dd00-689d-11ea-8752-778eced49eb6.png)

Information about file:
![image](https://user-images.githubusercontent.com/43488869/76859716-306faa00-689d-11ea-8729-c9273e9f8cba.png)

**Comment by astrelsky** [comment]
What MemoryBlockType is the Memory block at that address? This should only occur for uninitialized or volatile memory.

**Comment by mafusuke** [comment]
Thank you for reply
When I enter the code you gave me, it is displayed as follows
![image](https://user-images.githubusercontent.com/43488869/76865446-1090b400-68a6-11ea-833f-55a135d20729.png)

**Comment by astrelsky** [comment]
> Thank you for reply
> When I enter the code you gave me, it is displayed as follows
> ![image](https://user-images.githubusercontent.com/43488869/76865446-1090b400-68a6-11ea-833f-55a135d20729.png)

So the `??` are due to the block being initialized. You can initialize the block yourself and fill it with a default value if you'd like. For reference, what does HxD show at that address? In HxD do you have the binary opened as a file or are you viewing the process memory?

Below is some code to initialize the memory block to remove the `??` please note that the values will all be initialized to 0.

```
mem = currentProgram.getMemory()
block = getMemoryBlock(currentAddress)
block = mem.convertToInitialized​(block, b'\x00')
```

**Comment by ryanmkurtz** [comment]
The ??'s represent uninitialized memory.  You can think of them as garbage bytes that haven't been written to yet, kind of like an uninitialized variable.  In some cases, Ghidra should have initialized them but didn't for efficiency reasons.  In this case, you can think of them as all 0's.  If you would like to see them as all 0's, you can go into the Memory Map and check the Initialized box for the memory you care about.

**Comment by mafusuke** [comment]
When I opened in HxD(as a file), I found an interesting string, but in Ghidra it was '??'.  In other words, I want to initialize the '??'  So, are there any settings or countermeasures that do not result in '??'
 (Sorry for my bad English)

**Comment by ryanmkurtz** [comment]
Ghidra presents a view of your file as it would look when loaded into memory by, in your case, the Mach-O loader.  The file offsets and the memory addresses will not necessarily match up.  Try using Ghidra's string search feature to locate the string, and note its memory address vs. its file offset.

**Comment by mafusuke** [comment]
I'm sorry, it's exactly the function name and wants to see the disassembly code in the listing view.

**Comment by ryanmkurtz** [comment]
> I'm sorry, it's exactly the function name and wants to see the disassembly code in the listing view.

Sorry, but I don't know what you are asking.

**Comment by astrelsky** [comment]
@mafusuke as Ryan has previously stated 
 the file offsets you have from viewing the file in hxd don't have a 1 to 1 correspondence to the address in ghidra. In hxd you are looking at an unloaded file. When you execute a binary it gets loaded into memory and each section of the binary may be loaded into different addresses depending on format and purpose. This address layout is what is shown by Ghidra.

The offset 0x10157dd40 you have located in hxd is not the same as the address 0x10157dd40 in Ghidra. There is a search feature that you can use to search for the string or bytes to locate the proper address.  Hopefully this helps clear things up.

**Comment by dev747368** [comment]
On a side note, another possibility (but not for @mafusuke) is that the memory block is a byte mapped memory block.  The ByteViewer incorrectly treats those as un-initialized blocks.
In @mafusuke 's  case though, they have a default type memory block, so the tips from @ryanmkurtz  and @astrelsky  are correct.

**Comment by mafusuke** [comment]
Thanks. I understand that The offset 0x10157dd40 you have located in hxd is not the same as the address 0x10157dd40 in Ghidra.＝）

By the way, I got  "??" in ListView too. Is this the same reason?

![image](https://user-images.githubusercontent.com/43488869/77143047-5bd4dd80-6ac5-11ea-855c-4c454d27f13e.png)

**Comment by mafusuke** [comment]
So, is there any setting to prevent it from becoming "??" when importing file?

**Comment by ryanmkurtz** [comment]
No, but you can go into the Memory Map after the load finishes and check any unchecked boxes to initialize all of memory.

**Comment by emteere** [comment]
Resolved issue.  Works as intended.
