### ISSUE TITLE
NullPointerException in Function Graph window when moving mouse

### ISSUE THREAD

**Issue by gkso** [NationalSecurityAgency/ghidra#1643]
**Describe the bug**
This happened a few times. I have Listing (Assembly code), Decompile, and Function Graph in the same pane. 
After clicking a code block in the Function Graph, then switching to the Listing window, the following exception occurs:

> Uncaught Exception! 
> IllegalArgumentException - Component is not on screen: ghidra.app.plugin.core.functiongraph.graph.FGPrimaryViewer[,0,0,1073x571,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=8,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=4000,height=4000]]
> java.lang.IllegalArgumentException: Component is not on screen: ghidra.app.plugin.core.functiongraph.graph.FGPrimaryViewer[,0,0,1073x571,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=8,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=4000,height=4000]]
> 	at generic.util.WindowUtilities.ensureOnScreen(WindowUtilities.java:283)
> 	at docking.widgets.PopupWindow.doShowPopup(PopupWindow.java:240)
> 	at docking.widgets.PopupWindow.showOffsetPopup(PopupWindow.java:214)
> 	at ghidra.app.plugin.core.hover.AbstractHoverProvider.showPopup(AbstractHoverProvider.java:191)
> 	at ghidra.app.plugin.core.functiongraph.graph.vertex.ListingGraphComponentPanel$ListingHoverAdapter.showPopup(ListingGraphComponentPanel.java:711)
> 	at ghidra.app.plugin.core.hover.AbstractHoverProvider.mouseHovered(AbstractHoverProvider.java:148)
> 	at docking.widgets.fieldpanel.HoverHandler.mouseHovered(HoverHandler.java:119)
> 	at docking.widgets.fieldpanel.HoverHandler.actionPerformed(HoverHandler.java:96)
> 	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
> 	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> 
> ---------------------------------------------------
> Build Date: 2020-Feb-12 1149 EST
> Ghidra Version: 9.1.2
> Java Home: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
> JVM Version: Oracle Corporation 13.0.1
> OS: Mac OS X 10.15.2 x86_64
> Workstation: localhost

After that, I switch back to the Function Graph window, whenever I move my mouse in the window, it keeps popping out the following NullPointerException:

> Uncaught Exception! 
> java.lang.NullPointerException
> 	at docking.widgets.PopupWindow$2.mouseMoved(PopupWindow.java:118)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:338)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:337)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:337)
> 	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6681)
> 	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3360)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6405)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4560)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> 
> ---------------------------------------------------
> Build Date: 2020-Feb-12 1149 EST
> Ghidra Version: 9.1.2
> Java Home: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
> JVM Version: Oracle Corporation 13.0.1
> OS: Mac OS X 10.15.2 x86_64
> Workstation: localhost

**To Reproduce**
Haven't found a deterministic way to reproduce the behavior. What I did before are as follows:
1. Make the Listing, Decompile, and Function Graph in the same pane.
2. Run [a Ghidra script](https://github.com/NationalSecurityAgency/ghidra/files/4347401/ColorStabbedNodes.py.txt) to change the background color of some code blocks. 
3. Double click a function in the Function Graph to jump into that function.
4. Click a code block in the Function Graph.
5. Switched between Function Graph, Listing and Decompile window. 

**Expected behavior**
When moving my mouse in the Function Graph, the exception keeps popping out.

**Environment (please complete the following information):**
 - OS: macOS 10.15.2
 - Java Version: 13.0.1
 - Ghidra Version: 9.1.2

**Comment by dragonmacher** [comment]
I have not seen this before.  It may be related to using Java 13.
