### ISSUE TITLE
ElfLoader NPE

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1646]
**Describe the bug**
A NullPointerException is thrown when loading an elf file where the first section, section 0, is NULL.

**To Reproduce**
1. Load an elf file that has a NULL 0 section.

**Expected behavior**
The NullPointerException should be caught and ignored for section 0.

**Screenshots**
<details><summary>readelf output</summary>

![Capture](https://user-images.githubusercontent.com/46897303/76892013-57f45180-6860-11ea-925c-f51edb0ed9de.PNG)
</details>

**Environment (please complete the following information):**
 - Ghidra Version: 9.0-9.2

**Additional context**
The binaries are still loaded without an issue. It is likely sufficient to remove it from the message log.

**Comment by ghidra1** [comment]
Could you please provide a stack trace.  Initial attempt to reproduce failed to generate error.

**Comment by astrelsky** [comment]
> Could you please provide a stack trace. Initial attempt to reproduce failed to generate error.

I can't seem to trace it myself as it is actually being caught since the error is being logged into the importer message window. I'm attaching an archive of a recent application.log and of an elf file which can duplicate it. The binary is just a set of test cases for a bare metal raspberry pi zero environment.

[firmware.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/4377842/firmware.tar.gz)

**Comment by ghidra1** [comment]
Issue has been resolved with ELF loader improvements.  Should be working in latest release.
