### ISSUE TITLE
ScriptMgrPlugin: Auto recompilation

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#1651]
**Is your feature request related to a problem? Please describe.**
1.) Create MyHelloWorldScript.java and MyHelloWorldClass.java
The script uses the class in some way
2.) run the script
3.) modify MyHelloWorldClass
4.) rerun MyHelloWorldScript. since the .class files are already extant and the base script has not been changed, ghidra does not recompile. 

**Describe the solution you'd like**
ScriptManagerPlugin should automatically recompile when necessary, or provide an easy way to force recompilation

**Describe alternatives you've considered**
I have a bash script to clear my /bin/ folder

**Comment by dragonmacher** [comment]
The automatic compilation of dependencies is quite a difficult problem to fix.  
I think it would make sense to have an action to allow users to **Rebuild** all scripts.

**Comment by ryanmkurtz** [comment]
Even if there was an action to rebuild all scripts, how would this this non-script dependency file get recompiled?

**Comment by dragonmacher** [comment]
@ryanmkurtz Presumably this file lives in the scripts directory.  I imagine an action that would clear all class files and build any Java file found in all scripts dirs.

**Comment by ryanmkurtz** [comment]
You might be able to use the `jdeps` tool that comes with java.  [This API](https://docs.oracle.com/javase/9/docs/api/jdk.jdeps-summary.html) might help.

**Comment by dragonmacher** [comment]
@ryanmkurtz You sound like just the person for the job!  :grin:

**Comment by dragonmacher** [comment]
We have updated how scripting is managed in the master branch.   That should fix this issue.
