### ISSUE TITLE
dsPIC hex doesn't seem to analyze

### ISSUE THREAD

**Issue by tbednarchuk** [NationalSecurityAgency/ghidra#1657]
**Describe the bug**
A dsPIC hex file is read correctly, the analyzer seems to go thru the motions and then nothing. Listing window just shows the hex. Decompiler shows No Function. 
Other PIC hexfiles (PIC18) seem to work correctly.
MPlabX reads the HEX and disassembles it fine so it's unlikely to be a file format problem.
**To Reproduce**
1. Create a new project
2. Drag and drop app10104.155.hex
3. Set language to dsPIC30
4. Analyze using default

**Expected behavior**
At minimum a disassembly of the HEX in listing, ideally Decompiler window output of some kind.
**Screenshots**
![image](https://user-images.githubusercontent.com/17200996/77090496-9c592c00-69dd-11ea-9de6-eda13e9417c6.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.
[Archive.zip](https://github.com/NationalSecurityAgency/ghidra/files/4355770/Archive.zip)
]
contains application.log and app10104.155.hex that I used
**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.15.3]
 - Java Version: [e.g. 11.0.6]
 - Ghidra Version: [e.g. 9.1.2

**Additional context**

**Comment by ryanmkurtz** [comment]
What happens if you click on address 0 and then hit `d`?

**Comment by tbednarchuk** [comment]
Well Damn! 
Thanks Ryan, obviously new user error here (not knowing about the d key).
I guess I'll just close this now - jeez - and print out the cheat sheet

**Comment by ryanmkurtz** [comment]
Often times you don't have to do anything, the analyzers will figure out where things start and disassemble from there, but in this case, you had to help it out a little.

**Comment by tbednarchuk** [comment]
Yeah not knowing that.....
still have sections that are blank but have data there - assuming some sort of disassembler sync problem? These files might be a bootloader plus app so I wonder if that messes the disassembler up.

Again thanks for the push in the right direction
