### ISSUE TITLE
Tail Call Optimization

### ISSUE THREAD

**Issue by bin2415** [NationalSecurityAgency/ghidra#1658]
Is there any option to enable tail-call optimization?

**Comment by emteere** [comment]
The Shared Return Calls analyzer will detect Tail Call Optimization and turn the tail jump to another function into a call/return to the function.

There are two options on the analyzer.  Assume contiguous functions only, will consider a jump over another function to be a call to that function.  Allow Conditional Jumps, will consider conditional jumps to another function as a conditional call/return to that function.

**Comment by bin2415** [comment]
Thanks! :)
