### ISSUE TITLE
Add support for GDB MiniDebugInfo symbols

### ISSUE THREAD

**Issue by mikeryan** [NationalSecurityAgency/ghidra#1659]
**Is your feature request related to a problem? Please describe.**
Many stripped binaries ship with minimal debug symbols in the `.gnu_debugdata` section. Resolving these otherwise standard symbols would greatly aid in the reversing process.

**Describe the solution you'd like**
Extract symbols from `.gnu_debugdata` during the analysis phase.

**Describe alternatives you've considered**
As a workaround, it is possible to manually extract the symbols and use a script to decorate functions.

**Additional context**
Information about the format available in [GDB documentation](https://sourceware.org/gdb/onlinedocs/gdb/MiniDebugInfo.html). An example of how to extract and decompress the section using `objcopy` can be found on [this StackOverflow answer](https://stackoverflow.com/questions/53572342/where-are-gdb-symbols-coming-from). They appear to be an otherwise standard but mostly empty ELF file that only retains a handful of symbol-related sections.

[ls.zip](https://github.com/NationalSecurityAgency/ghidra/files/4357291/ls.zip) contains `/bin/ls` from Fedora 31, which includes the `.gnu_debugdata` section.

**Comment by mumbel** [comment]
```
// https://mvnrepository.com/artifact/org.tukaani/xz
// compile group: 'org.tukaani', name: 'xz', version: '1.8'
import org.tukaani.xz.XZInputStream;
byte tmp[] = new byte[(int)revisedLength];
fileBytes.getOriginalBytes(fileOffset, tmp, 0, (int)revisedLength);
ByteArrayInputStream bais = new ByteArrayInputStream(tmp);
XZInputStream xz = new XZInputStream(bais);
byte tmp2[] = new byte[16000]; //hack, whats real output size
xz.read(tmp2, 0, 16000);
xz.close();
HexDump.dump(tmp2,0,System.out,0);
```
Didn't play around with it too much, but did this to verify the .gnu_debugdata.  Also wrote the section out to a file and ran `xz -d` getting an ELF:
```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x68a0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          12920 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         13
  Size of section headers:           64 (bytes)
  Number of section headers:         30
  Section header string table index: 29
```

**Comment by grant-h** [comment]
This section is very important for Android native daemons. The current build system Soong embeds this section on production binaries in order to symbolize stack traces during tombstone creation. Adding built-in support for extracting this would help Android reversing immensely (and other Linux binaries with this section).

Here's an IDA Gist that does the extraction - https://gist.github.com/rpw/caf82a1b657011cadd7c8b8664f10204

Here's some more context - https://sourceware.org/gdb/current/onlinedocs/gdb/MiniDebugInfo.html

**Comment by nneonneo** [comment]
Re-upping this: I'm seeing `.gnu_debugdata` more often on binaries in the wild, and IDA has built-in support whereas Ghidra does not.

The implementation would be to decompress the section, then import the resulting ELF file into the program (or even just merge the sections - the debugdata ELF is devoid of actual code and data).

**Comment by ghidra1** [comment]
Using master branch we already support importing symbols from this section.  This change was made in December 2021
![Screenshot at 2022-07-13 10-39-16](https://user-images.githubusercontent.com/48333017/178761397-61676d75-04cf-4bdf-9ff1-1667b576190b.png)
.

**Comment by grant-h** [comment]
Should Ghidra 10.1.3 be extracting this section then? I don't see this behavior or any log messages related to this section after import. Only if I decompress and merge the ELF back in does Ghidra display symbols.

**Comment by ghidra1** [comment]
This change will be in 10.2 release

**Comment by djjfjegjjas** [comment]
> This change will be in 10.2 release

If we have databases created prior to 10.2, can we somehow trigger Ghidra to extract symbols from the `.gnu_debugdata` section and apply them to the existing database?

I am trying to avoid re-importing the binary from scratch, and thus losing all work done on it.

**Comment by dev747368** [comment]
Would importing a fresh copy (and not doing any analysis) and then using program diff to copy anything new to your real binary work?
