### ISSUE TITLE
Issue with GUI rendering Ubuntu 16.04

### ISSUE THREAD

**Issue by GideonWolfe** [NationalSecurityAgency/ghidra#166]
**Describe the bug**
After downloading Ghidra and JDK, Ghidra shows a cliiped/glitched version of the full GUI. I had to click around randomly to even get passed the welcome screen.

**To Reproduce**
1. Download Ghidra
2. Point to JDK 
3. run ./ghidraRun

**Expected behavior**
I expect the ghidra GUI to open correctly, like on my Arch system.

**Screenshots**
https://i.imgur.com/v0E172Z.png

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Java Version: openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
 - Ghidra Version: 9.0

**Comment by ryanmkurtz** [comment]
Are you running Ghidra on a HiDPI monitor?

**Comment by GideonWolfe** [comment]
2015 MacBook Pro, which has a retina display.

**Comment by ryanmkurtz** [comment]
Thanks for getting back to me with that info.  I am going to close this issue since it is a duplicate of issue #1 .  If you take a look at that issue, some people have a potential workaround that you could try until we figure out what is going on with Java.
