### ISSUE TITLE
Null pointer exception during Import File while navigating between folders

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#1660]
**Describe the bug**
NullPointerException occurred while navigating among folders during *Import File...*

**To Reproduce**

1. I was using a currently empty project from which I had recently (earlier today) deleted about 78000 accidentally imported files removed. 
2. I selected *File->Import File...* from the Ghidra main window menus. It started out in my home folder. I double clicked a sub-folder, and another one or two levels of sub-folder below that.
3. I clicked the "up arrow" icon to move up one level in the folder tree. This induced a NullPointerException.
I never actually tried to import anything.

**Expected behavior**
I expected the file system navigation window to open the parent folder of the current [folder.]

**Attachments**
The attached log file begins with a very long sequence of messages produced by the deletion of the 78000 or so files that I did earlier.

Initially, you may want to start at the bottom.

[application.log](https://github.com/NationalSecurityAgency/ghidra/files/4361784/application.log)

**Environment (please complete the following information):**
 - OS: macOS 10.13.6
 - Java Version: 12.0.1
 - Ghidra Version: 9.1.2

**Comment by dragonmacher** [comment]
This is a duplicate of #1706.  

A fix for this is coming soon.
