### ISSUE TITLE
cdt-8.6.0.zip isn't persisted to flatRepo, is lost if "gradle clean" is performed

### ISSUE THREAD

**Issue by dev747368** [NationalSecurityAgency/ghidra#1663]
**Describe the bug**
If you use "gradle --init-script gradle/support/fetchDependencies.gradle init" to pull down necessary external dependencies, the cdt-8.6.0.zip is lost if you ever do a clean.

**To Reproduce**
1. gradle --init-script gradle/support/fetchDependencies.gradle init
2. gradle clean
3. gradle prepDev 

which fails with:
```
> Task :GhidraDevPlugin:cdtUnpack FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':GhidraDevPlugin:cdtUnpack'.
> Cannot expand ZIP 'C:\.......\ghidra.bin\GhidraBuild\EclipsePlugins\GhidraDev\buildDependencies\cdt-8.6.0.zip' as it does not exist.


```

**Expected behavior**
cdt-8.6.0.zip should persist just like the other dependencies in the flatRepo directory.

**Comment by ryanmkurtz** [comment]
If clean blows away the build directories, then there are other things retrieved by fetchDependencies.gradle that will be lost by a clean too, like PyDev and yajsw.
