### ISSUE TITLE
JDK 14+ Support (JEP 359)

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1668]
JDK14's preview features contains the [java.lang.Record](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/Record.html) implementation.  Unfortunately this creates a bunch of ambiguous references with uses of [db.Record](https://ghidra.re/ghidra_docs/api/db/Record.html)

**Comment by ryanmkurtz** [comment]
Do you have to enable the preview feature for the errors to occur?

**Comment by astrelsky** [comment]
> Do you have to enable the preview feature for the errors to occur?

Working on figuring that out now. At the moment they only appear to be build errors. I haven't actually tired launching ghidra with the preview features enabled.

**Comment by ryanmkurtz** [comment]
I ran into this same issue when Java 9 introduced java.lang.Module.  Ghidra used a custom Module class that ultimately had to be renamed everywhere.

**Comment by astrelsky** [comment]
> I ran into this same issue when Java 9 introduced java.lang.Module. Ghidra used a custom Module class that ultimately had to be renamed everywhere.

It's pretty simple to fix via regex. I did a regex search and replace for \bRecord\b and then only had to manually fixup 3 files and replace every "import db.db.Record;" back to "import db.Record;"

I don't think it should be changed until Record is moved out of preview as the only use for db.Record is internally.

**Comment by Arcnor** [comment]
Will a PR for this be accepted if it qualifies all Record uses with `db.Record`? Or will a rename be needed instead? I'm running into this and is highly annoying...

**Comment by ryanmkurtz** [comment]
I think dealing with a PR for this would be more work for the Ghidra team than them just doing it themselves.  Eclipse has a refactor feature that makes switching it trivial.  

Depending on how annoying you are finding it, you might consider switching to the only version of Java that Ghidra officially supports...Java 11 LTS.  At some point Ghidra will have to deal with this issue in order to support Java 17 (the next LTS version due to be released in 2021).

**Comment by astrelsky** [comment]
> Will a PR for this be accepted if it qualifies all Record uses with `db.Record`? Or will a rename be needed instead? I'm running into this and is highly annoying...

I have a local branch buildable with JDK 14 if you'd like me to put it up. I didn't submit a pull request for the reason Ryan mentioned above. If record is moved out of preview and becomes standard I think it would be better to rename the class to something like `GRecord` in the same fashion as `GModule`. I'm currently building something using Ghidra's database implementation and having to see db.Record everywhere is an eyesore.

My local branch that is buildable with jdk 14 does have some other changes from several pull requests but I will put it up anyway.

**Comment by nauliajati** [comment]
Hi, look like i have a similar issue here, this system is using currently:
**Ubuntu 16.04 LTS, openjdk 15 (build 15+36-1562). Gradle 6.7**

i got this error when i run this command:
**$ gradle --init-script gradle/support/fetchDependencies.gradle init (no error)
$ gradle buildGhidra (in attached file)**

[error1.txt](https://github.com/NationalSecurityAgency/ghidra/files/5505006/error1.txt)

**Comment by astrelsky** [comment]
Fixed by db1e3d1b6296fde793006e12c708e07e77009c5c
