### ISSUE TITLE
16bit instructions sometimes fail to disassemble

### ISSUE THREAD

**Issue by baeda16V** [NationalSecurityAgency/ghidra#1669]
I'm working on a HC11 processor module. The 8bit CISC Architecture also includes 16bit instructions marked with a prebyte. Here's how I've defined 16bit instructions:

`define token withprebyte(16)`
`	pre		= (0,16);`
`define token byte(8)`
`	op8		= (0,7);`

`OFF: op8	is op8 		{ export *[const]:2 op8; }`
`IMM8: op8 is op8 		{ export *[const]:1 op8; }`

`:bsetY OFF,IMM8 is pre=0x181C; OFF; IMM8`
`{`
`	local temp = *:1 (Y+OFF);`
`	temp = temp | (IMM8);`
`	*:1 (Y+OFF) = temp;`
`}`
`:bclrY OFF,IMM8 is pre=0x181D; OFF; IMM8`
`{`
`	local temp = *:1 (Y+OFF);`
`	temp = temp & (~IMM8);`
`	*:1 (Y+OFF) = temp;`
`}`

The Disassembler correctly translates all 8bit instructions and some 16bit instructions but fails to disassemble the same 16bit instruction at other places. Here is an example where the same instruction fails to disassemble and is correctly disassembled right after
            c164 18              ??         18h
            c165 1d              ??         1Dh
            c166 21              ??         21h    !
            c167 01              ??         01h
            c168 18 1c 21 02     bsetY      0x21,0x2
            c16c 18              ??         18h
            c16d 1c              ??         1Ch
            c16e 22              ??         22h    "
            c16f 01              ??         01h
            c170 18 1d 21 04     bclrY      0x21,0x4
            c174 18 1c 21 08     bsetY      0x21,0x8
            c178 18 1c 22 02     bsetY      0x22,0x2

**Comment by mumbel** [comment]
I would reference the HC12 implementation, they're probably very similar.  

nothing sticks out really though with you sample, except pre=(0,15) instead of (0,16) which probably makes sense as all the ones that work don't have the LSB set in IMM8, but the failures do
