### ISSUE TITLE
Comments in the decompiler often destroy if statements

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#1670]
**Describe the bug**
Comments are tied to the listing, not to the decompiler. The rendering of decompiler output naively inserts listing comments, resulting in broken C output. This is problematic because a common scripting pattern is "if address fits pattern, add comment at address".

**To Reproduce**
Find any if statement in the decompiler of the form
`if ( _ && _ && _ && ...)`
such a statement often corresponds to multiple instructions and addresses.
Try commenting various elements in the if statement
The resulting insertion of /* */ blocks into the if statement causes the decompiler output to break. 

There might be other error cases but this is the most common example

**Expected behavior**
Comments should be placed sensibly in the decompiler output

**Environment (please complete the following information):**
 - Ghidra Version: 9.1.2

**Comment by ghidra1** [comment]
Corrected for Ghidra 9.3
