### ISSUE TITLE
Ghidra Server: -u doesn't work in "no authentication" mode

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1678]
When running the Ghidra Server in the "no authentication" mode, -u is ignored.  It would be nice if you could still specify a custom username in this situation.

**Comment by dev747368** [comment]
As an alternative, you could enable jaas auth in ghidra server.conf, enable the "example_external_auth" in jaas.conf (by changing its name to "auth"), and tweaking the jaas_external-program.example.sh to always return success.

**Comment by ghidra1** [comment]
If you really need to specify a user I suggest you enable password authentication.  Use of the no-authentication mode is generally discouraged and intended more for testing.  Such a change would probably be a very low priority.

**Comment by ryanmkurtz** [comment]
I ran into a problem where using -a0 -u resulted in immediate disposed handles for the user (after a successful remote login).  Turning off authentication fixed that issue for some reason, which is when I realized the -u didn't work with it.  It was just a temporary debugging situation.   

Closing due to very low priority.
