### ISSUE TITLE
Can't clear tool keybindings for plugin actions permanently

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#1681]
**Describe the bug**
Clearing to tool keybindings for plugin actions do not persist

**To Reproduce**
1. Try to bind a script to the '2' key
2. Hit 2 and realize it is bound to program diff plugin
3. ~~Change~~ Clear the key binding for view program differences
4. Close and reopen ghidra
5. Hit 2 again and realize its till bound

**Expected behavior**
The tool should allow key bindings to be cleared entirely.

**Environment (please complete the following information):**
9.1.2

**Comment by sad-dev** [comment]
Changing the key binding persists, but not clearing. Edited the issue to reflect that.

**Comment by dragonmacher** [comment]
Verified.  This is a regression.

**Comment by dragonmacher** [comment]
Fixed in aa11179c
