### ISSUE TITLE
dsPIC30 mov issue

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1687]
Not sure if this is working as intended, or a bug.  Here is a small program for the dsPIC30.

```
#include <stdio.h>

int main(void) {

    printf("Hello World\n");
}
```
<img width="524" alt="Capture" src="https://user-images.githubusercontent.com/5378554/77928375-52dacd80-7276-11ea-9b32-af41fcf8dbde.PNG">

[Test.X.production.zip](https://github.com/NationalSecurityAgency/ghidra/files/4403699/Test.X.production.zip)

At `rom:0007a2`, it looks like it's moving a constant into `W0` rather than a memory address.  When you double click on `#0x870e`, it tries to navigate to `rom:00870e` rather than `ram`.  Is there anything than can be done to fix this behavior?  The decompiler seems to get it right.

**Comment by ghidra1** [comment]
In the absence of a reference the navigation logic is simply operating on the scalar value.  Ideally this operand should have a reference which would avoid this issue.

**Comment by ryanmkurtz** [comment]
I don't need this addressed anymore...closing.
