### ISSUE TITLE
Is there a way to configure GhidraScripts to not print their names when run?

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#1691]
Running a script results in console output:

MyScript.java> Running...
"Hi from MyScript.java!"
MyScript.java> Finished!

Is there a property in GhidraScript that I can set to prevent the "Running" and "Finished" messages from being displayed?

**Comment by ryanmkurtz** [comment]
No, there is no such option.
https://github.com/NationalSecurityAgency/ghidra/blob/1df6fa79da8f6923cfca7af2cadf0cf6b317f100/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/script/RunScriptTask.java#L53-L59

**Comment by sad-dev** [comment]
Thanks; closing
