### ISSUE TITLE
Parsing RTTI table too slow

### ISSUE THREAD

**Issue by 2020karaulov2020** [NationalSecurityAgency/ghidra#1694]
**Describe the bug**
Big binary with 10000+ RTTI entries, HGIRDA parsing/creating this data very slow.
Created 1-2 RTTI data in second. 

**To Reproduce**
Open big Win32 binary with big rtti table and do analyze

I can't send this binary. Sorry.

**Comment by ryanmkurtz** [comment]
Some RTTI speedups were recently put into master.  What version of Ghidra are you running?  Can you try the latest build?

**Comment by 2020karaulov2020** [comment]
@ryanmkurtz thanks for answer. I use latest version from website. 
1-4 RTTI data created in 5 seconds. 

I tried analyze big file, not protected, 32bit Windows, compiled with Visual Studio 2005 (msvcr80.dll)
10000+ RTTI entries.

**Comment by ryanmkurtz** [comment]
Ok, the speedups will be in 9.2 whenever it gets released.  Or, you could build it yourself to test it out.  I'm not sure the changes will address your problem...I just know work was done in that area.

**Comment by 2020karaulov2020** [comment]
@ryanmkurtz you don't know, no automatic (teamcity/ci.appveyor) builds ?

**Comment by ryanmkurtz** [comment]
Nope, know automated builds that I know of.
