### ISSUE TITLE
Question: How would I export it to an exe?

### ISSUE THREAD

**Issue by trollmad3** [NationalSecurityAgency/ghidra#17]
I want to export the program back into a `.exe` after done editing it. How would I do that? 
![image](https://user-images.githubusercontent.com/7843719/53855589-dd79cc00-3f93-11e9-8b1c-f7554a43afac.png)

**Comment by rszibele** [comment]
You need to select binary as the export format which recreates the executable. You can also press F1 anywhere which opens up the help with the current context.

**Comment by trollmad3** [comment]
@rszibele Thanks for your help but when I export it as a .bin the file output is this:
![image](https://user-images.githubusercontent.com/7843719/53886553-e1ced500-3fe5-11e9-9b40-8ceea795ba52.png)
and the file does not output onto the Desktop.

**Comment by SmurfRP** [comment]
Oi! Why are you trying to decompile citizen hack? Lmaooooooooo chm_client is very very familiar.

**Comment by trollmad3** [comment]
@SmurfRP Wanted to see how it works.

**Comment by rszibele** [comment]
I'm unable to reproduce the saving issue. After importing an executable on Windows and exporting it, it does save the executable where I wanted it to save it. Ghirda automatically adds ".bin" to the file name, which you will have to remove to be able to run it.
![image](https://user-images.githubusercontent.com/1387224/53898897-ebc9f580-4030-11e9-8532-3d05bbb93353.png)

Windows is currently also affected by this other bug https://github.com/NationalSecurityAgency/ghidra/issues/19 so you _must_ import the executable as raw to be able to run the exported executable afterwards.

It's possible that something is blocking Ghirda from saving on your end.

Check the Ghirda logs for any errors, which should be located at:
`C:\Users\{USERNAME}\.ghirda\.ghirda-9.0\application.log`

**Comment by Kushagra3911** [comment]
Select the PE option,PE stands for Portable Executable

**Comment by ImJoke** [comment]
How about this one?

<img width="292" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/55929550/b2c773a6-13b0-4e34-8438-1da0e7dabed3">

What should I choose?

**Comment by ryanmkurtz** [comment]
This is currently done though the "Original File" exporter.

**Comment by 20urc3** [comment]
> This is currently done though the "Original File" exporter. It is no longer restricted to PE and ELF.

The Original File exporter isn't working for me on latest version for me. It pop-up the export Windows in front of the export summary, in a infinite loop. 
![image](https://github.com/NationalSecurityAgency/ghidra/assets/94982366/a813eb27-e7a3-4170-8c37-cd81fd8956c3)

**Comment by ryanmkurtz** [comment]
Ghidra 10.3.1?

**Comment by 20urc3** [comment]
Yes @ryanmkurtz

**Comment by ryanmkurtz** [comment]
So you import your binary, then then immediately export Original File and it freaks out?

**Comment by 20urc3** [comment]
- Import PE
- Patch an instruction 
- Export Program > Original File
- Freaks out and loop as shown above

**Comment by 20urc3** [comment]
The issue reside in patching instruction without respecting the right offset i guess. I've fixed my patched and now it exports. Maybe try to replace a "PUSH EBP" by a "JMP [ADDRESS]" with a too large instruction size, it overlap on the next instruction then messed up the export on Orginal File.

Still tho imo it should display error message, not loop

**Comment by ryanmkurtz** [comment]
Did you spill over into a relocation?

**Comment by Thinkish30** [comment]
I also faced the same issue in new ghidra version but you can save the file by selecting the format as Original file and ..........export  the folder in the source folder of your exe so it can fetch all the required .dll files and any other resources files.
 
![image](https://github.com/user-attachments/assets/76fcb349-08d8-4e54-bcd6-90a748e4b5d5)
