### ISSUE TITLE
Dealing with leftover .merge temp file

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#1701]
I have seen several times when ghidra has hung, or the machine crashed during a merge from the server.  This leaves a .ghidra.XXX.merge temporary file in the repository.  Subsequent merges fail because the merge file already exists.

We had found no solution for this and in the past we have abandoned repositories and pulled files back from the server after this happened.  I have made a (rather dirty) ghidrascript that invokes cleanupTempFiles() in the LocalFileSystem, which seems to clear things up.

Is there any better way to handle this?  It would be nice if the merge routine would detect this and offer to remove the file instead of just failing with an exception.

**Comment by domenukk** [comment]
Care to share the script? Better to have a dirty solution than no solution :)

**Comment by domenukk** [comment]
Since I just ran into this issue again, note to future self: I removed all lines containing the `.merge` filename from `<projectfolder>/idata/~index.data` and `<projectfolder>/idata/~journal.bak` and it seemed to have helped.

**Comment by ghidra1** [comment]
That approach does not properly cleanup the associated database files and only removes from the index.  If the index were to get rebuilt they would reappear.

**Comment by marcushall42** [comment]
Long time coming followup..  I actually don't have the script around anymore, but it was on an air-gapped system, so I couldn't copy it off if it was still there..

But, basically the script gets the file manager from Tool, then walks through all of the DomainObjects starting with the root directory.  If the DomainObject is a file and ends with ".merge", then it invokes .delete().

It would be most useful when ghidra encounters an existing .merge file to instead of just complaining that the .merge file exists, if it opened up a dialog that offered to remove the .merge file (with sufficient warnings that it looks like a merge is in progress, or maybe failed).  Bonus to just silently remove the .merge if it is beyond some threshold age..

**Comment by ghidra1** [comment]
It's been a very long time since I worked with the merge code in this area.  I was thinking the working files were hidden.  Apparently not, based upon your observations.  I will have to look into this in more detail.

**Comment by marcushall42** [comment]
It is possible that things are better now, we haven't run into any issues in several years.

What we were seeing is that when merging in changes from the server to update to a new version of a program, there were times when the merge failed and left the .merge DomainFile around.  (At first, we were looking for a regular linux file, but eventually decided that wasn't the case.)  Then when we would re-start ghidra and go to re-run the merge, ghidra would just say that the .merge file already existed and refuse to go any further.  It seemed to be an unresolvable barrier.  More than once we have abandoned a repository and started over because the old one was unusable.  Then I put together a quick script to look for a DomainFile named xxx.merge and discovered that was what was causing the pain.  Invoked .delete() on it and things were happy again.

Like I said, though, we haven't been hit with problems in years, but it does look like domenukk did earlier this year.  It seems that a dialog to determine if there is still a merge going on or if it's a stale file would likely not be too difficult and would certainly alleviate a frustrating situation.

**Comment by marcushall42** [comment]
Maybe it's the heat..  It seems my mind is definitely going somewhere...

My quick and dirty script was essentially three lines:
   DomainFolder folder = currentProgram.getDomainFile().getParent();
   LocalFileSystem fs = folder.getLocalFilesystem();
   fs.cleanupTemporaryFiles(folder.getPathname());
But, it's complicated (and the *dirty* applies) because it is necessary to use reflection to invoke the methods involving LocalFileSystem.

I put this into our git repository in April 2020, and looking at the installed ghidra versions, I think that this was 9.1.1.  So, it's been a little over a year since we saw it, and the last year really didn't see a lot of action, so unless things changed with 10.0 I don't see any reason that it would be much better.

I think that the problem manifests itself when the merge process invokes allocateItemStorage() in the LocalFileSystem object and that throws a DuplicateFileException.  So, the merge process would need to catch that and perform some remedial action if it is thrown.

**Comment by ghidra1** [comment]
I assume the DuplicateFileException is fallout from the old .merge file(s) and not the original cause for aborting the merge.  Do you know the original reason for the failed merge which left the merge files around.

**Comment by marcushall42** [comment]
Right, it's trying to carry on after an original merge failed..

I can't recall definitively what failed before.  I seem to recall some things like out of memory conditions, seeming to run forever (and thus the "killall java" "solution"), or maybe just taking an exception for something.  Given my track record above, I really wouldn't trust my memory of specifics all that much.  But I don't think it was anything "worse than normal", just sort of the average background failure rate.  It just happened at an inopportune window when the .merge file was there.  The merge almost always works properly..
