### ISSUE TITLE
Allow setting ACL Rules via commandline

### ISSUE THREAD

**Issue by Thalhammer** [NationalSecurityAgency/ghidra#1703]
**Is your feature request related to a problem? Please describe.**
There is a commandline helper for server administration which allows various commands to be executed at runtime. However there is no way to give a user permission to access a repository without making him an admin of the repository. There should be a command similar to 
`-admin <sid> "<repository-name>"`
to add readonly and readwrite users adn remove them or prefereable a version which accepts an permission level like for example this:
`-acl <sid> "<repository-name>" <R|RW|A|N>`
for readonly, readwrite, admin and none respectively.

**Describe the solution you'd like**
Either add a new method to the command queue parser or even better:
Reload the acl file if it changed since last load.

**Describe alternatives you've considered**
Currently to change an acl via commandline you need to shutdown the server, edit the acl file and start the server again. This is not acceptable for an environment where users want to work concurrently.

**Additional context**

**Comment by ghidra1** [comment]
There is a separation of roles which precludes this.  The server administrator is not intended to be a repository (i.e. shared project) administrator which is the responsibility of the shared project ADMIN which is a client-side role.  The ACL can be managed from the client-side via the remote repository GUI and API by a user with the appropriate ADMIN role for each repository in question.

**Comment by Thalhammer** [comment]
I know that I can manage users in the client and that works fine. However not having a cli makes automation really hard.
This is a general problem, but in my case I would like to add users to a repo based on an external system. I don't see a reason not to support this.
I might do a PR if it is something that would get merged.

**Comment by ghidra1** [comment]
Since repository data is not really secured from a privileged server administrator accessing it, there is probably no additional harm in adding such a feature.  I have submitted an internal ticket to add improvements in this area although it has not yet been scheduled.
