### ISSUE TITLE
Document ghidraServer Queue Interface

### ISSUE THREAD

**Issue by Thalhammer** [NationalSecurityAgency/ghidra#1705]
**Is your feature request related to a problem? Please describe.**
Add a proper documention about the protocol used between the svrAdmin tool and the ghidraServer.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ghidra1** [comment]
There is no protocol.  The command line is simply stored into a file within the ~admin directory and processed in a delayed fashion.  There is no communications interface between svrAdmin and the running server process.
