### ISSUE TITLE
NullPointerException in front end GUI while browsing around in file selection window.

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#1706]
**Describe the bug**
A NullPointerException occurred while I was using this window:
![Capto_Capture 2020-04-02_03-21-06_PM](https://user-images.githubusercontent.com/52077/78295107-909b5880-74f9-11ea-8bf4-da9cddfbab4b.png)

It seemed to happen no matter what I clicked on. See the log file attached below.

**To Reproduce**
Don't know how.

But there are a lot of NullPointerExceptions occurring in the Mac GUI for the front end.

**Attachments**

[application.log](https://github.com/NationalSecurityAgency/ghidra/files/4423286/application.log)

**Environment (please complete the following information):**
 - OS: macOS 10.13.6
 - Java Version: 12.0.1
 - Ghidra Version: 9.1.2

**Comment by gtackett** [comment]
Immediately after launching Ghidra I'm able to trigger an error that looks a lot like this (NPE involving date and time).

Just now I selected **File->Open Project...** and immediately got the attached error message, and when I dismissed it, the **Open a Ghidra Project** appeared.
[log 2.txt](https://github.com/NationalSecurityAgency/ghidra/files/4576887/log.2.txt)

**Comment by gtackett** [comment]
The problem might have to do with browsing into a directory where there is a link to a zero-length file.

I did:
`$ cd ~/
$ touch myzerofile   # to create a zero-length file
$ ln -s myzerofile myzerolink
$ ls -l myzero*
-rw-r--r--  1 gtackett  staff   0 Jul  9  2016 myzerofile
lrwxr-xr-x  1 gtackett  staff  10 May  4 16:02 myzerolink -> myzerofile`

After that, I get the _2nd_ error when I try to open a project in my home directory.

Even if I remove 'zerolink' the problem persists until I exit Ghidra. Once I relaunch Ghidra, then, there is no errorl

**Comment by mumbel** [comment]
just as a data point I can't repro on ubuntu 18.04 with 9.1.2 or master.   I tried your empty file w/ symlink setup.  Did import file, open project, open file system, and batch import; and all recognized them as empty files

**Comment by ryanmkurtz** [comment]
I think it's a mac-specific error. I also remember fixing this exact error at some point...I'll have to look at the git history.

**Comment by ryanmkurtz** [comment]
Nevermind, I think this is something else.  This class looks questionable:

https://github.com/NationalSecurityAgency/ghidra/blob/bcb825fb029232175625bc85653ec0e810b1252e/Ghidra/Framework/Docking/src/main/java/docking/widgets/filechooser/GhidraFileChooser.java#L2130-L2177

Seems dangerous to have those nulls in there!

**Comment by dragonmacher** [comment]
This turns out to be an interesting bug.  The fix is pending.  For now, if you wish to avoid the exception, switch the File Chooser mode to have 'show details' off.
