### ISSUE TITLE
Will the code of Renoir (graph service provider) be open source?

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#1710]
I found [the package](https://github.com/NationalSecurityAgency/ghidra/blob/33b308570670abd54ec697939aae9ef33903ac4d/Ghidra/Configurations/Public_Release/src/main/resources/defaultTools/CodeBrowser.tool#L8), that was previously used in Ghidra (or now but not in public). It's [Renoir](https://wikileaks.org/gifiles/attach/40/40933_T2%20fact%20sheet%20-%20Renoir.pdf). Also I found other places, where graph service was [loaded](https://github.com/NationalSecurityAgency/ghidra/blob/33b308570670abd54ec697939aae9ef33903ac4d/Ghidra/Framework/Generic/src/main/java/generic/jar/ApplicationModule.java#L100) and used:

- as [graph service provider](https://github.com/NationalSecurityAgency/ghidra/blob/33b308570670abd54ec697939aae9ef33903ac4d/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/graph/GraphSelectionHandler.java#L20) (issue #174);
- for deserializing and drawing of controlflow graph [dumped by `decomp_dbg`](https://github.com/NationalSecurityAgency/ghidra/blob/33b308570670abd54ec697939aae9ef33903ac4d/Ghidra/Features/Decompiler/src/decompile/cpp/graph.cc) (issue #1418).

Can we hope to get Renoir? If not, than can we get serialize format of controlflow graph?

P. S. Source code was be in `Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/renoir/`.

**Comment by mumbel** [comment]
Renoir is a commercial/licensed product, so not likely.

**Comment by saruman9** [comment]
Ghidra also was commercial/licensed product. Maybe NSA are generous.

**Comment by mumbel** [comment]
Ghidra is most certainly not commercial.  Why are you assuming its NSA's to give away

**Comment by saruman9** [comment]
Developers began to develop graph module. https://github.com/NationalSecurityAgency/ghidra/commit/410af5a2720c1377586df7e1eff758db818d5030 — is start commit (very big one commit).
It works, but it's buggy for now. I [fixed some problems](https://gitlab.com/saruman9/ghidra/-/commit/3ca5eacd4cd1ee682990051159384bad30fd83fc) for building of `master` version of Ghidra.

**Comment by eyeofnet** [comment]
There is an open-source GraphService provider for Ghidra 9.1.2 named [Monet](https://github.com/eyeofnet/Monet). It looks like they are improving the Graph framework design for Ghidra 2.0.

**Comment by dragonmacher** [comment]
Closing.   The graph services api now provides a basic graph implementation.
