### ISSUE TITLE
Bad decrementing for far jumps (x86)

### ISSUE THREAD

**Issue by Tim---** [NationalSecurityAgency/ghidra#1715]
**Describe the bug**
When decompiling a CALLF instruction in 32 bits mode (addrsize=1 & opsize=1), the stack pointer is decremented by 2 bytes instead of 4 when CS is pushed. 

**To Reproduce**
Create a program in 32 bits mode with a CALL [EAX] instruction (ff 18).
The generated pcode shows that ESP is decremented by 2 (see screenshot)

**Expected behavior**
Perhaps I missed something, but I think that SP should be decremented by 4. 
It seems consistent with the alignment of the stack, and the manual specifies:

> IF OperandSize = 32
>     Push(CS); (* Padded with 16 high-order bits *)

**Screenshots**
![callf_sub2](https://user-images.githubusercontent.com/5160665/78503887-c21a5b00-7769-11ea-9903-4fbbc3f429a8.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Java Version: 11
 - Ghidra Version: 9.1.2

**Additional context**

I think it is due to a mixup between push42 and push24. See the relevant lines in the sleigh files:

https://github.com/NationalSecurityAgency/ghidra/blob/bcb825fb029232175625bc85653ec0e810b1252e/Ghidra/Processors/x86/data/languages/ia.sinc#L2085
https://github.com/NationalSecurityAgency/ghidra/blob/bcb825fb029232175625bc85653ec0e810b1252e/Ghidra/Processors/x86/data/languages/ia.sinc#L1074-L1078
https://github.com/NationalSecurityAgency/ghidra/blob/bcb825fb029232175625bc85653ec0e810b1252e/Ghidra/Processors/x86/data/languages/ia.sinc#L1060-L1065

**Comment by saruman9** [comment]
@Tim---, I created the draft PR. Could you test it? Could you share the binary file for me?

**Comment by Tim---** [comment]
Thansk saruman9 !

Unfortunately, the code binary is part of a CTF with several steps, so I can't really share it :/. Anyway, the assembly is a pile of garbage so it's probably not the best way to validate the patch :).

The stack decrement is fixed, I created a minimal example of far call (ptr16:32) based on the following code, with some tweaks in the assembly :
```C
#include <stdio.h>
int func(int a, int b) { return a + b; }
int main() {
    int a = 1, b = 2, c = 3;
    c = func(a, b);
    printf("%d + %d = %d\n", a, b, c);


    a = 10; b = 20; c = func(a, b);
    printf("%d + %d = %d\n", a, b, c);
}
```
```bash
$ gcc -fno-asynchronous-unwind-tables -fcf-protection=none -m32 -fno-pie -S -o main.S main.c
# replace the calls to func with : lcall $0x23,$func
# replace the return of func with : lret
# add 4 to the arguments offset in func
$ gcc -fno-asynchronous-unwind-tables -fcf-protection=none -m32 -fno-pie -o main main.S
$ ./main
1 + 2 = 3
10 + 20 = 30
```

Test file: [far-call-9A.zip](https://github.com/NationalSecurityAgency/ghidra/files/4452074/far-call-9A.zip)
The code decompiles cleanly if we add a first ushort argument to func, corresponding to the saved CS.

However, I did not manage to create a working example of call in the form `lcall *(%eax)`.
The sleigh code considers that it's a call to the same segment, with the address given in eax.
But the documentation suggests that eax is a pointer to a segment16:addr32 data structure, and that the addr32 is ignored (because of magic call gate mechanisms). 
Anyway, any attempt that I tried ended up with segfaults, so I can't confirm which one is right :/

**Comment by saruman9** [comment]
Thank you for testing @Tim---!
I reproduce your test successfully. For testing of the indirect lcall of `eax` I use patching in Ghidra. It's not the right approach, of course, but I just needed to see how the assembly is translated into PCode.

**Comment by Tim---** [comment]
Oh yes, I know about the instruction patching but I wanted to test the binaries to be sure that I didn't completely misunderstand the Intel manual :).

I finally managed to create a proper sample program with indirect far calls: [far-call-FF.zip](https://github.com/NationalSecurityAgency/ghidra/files/4463136/far-call-FF.zip)


The current sleigh code is indeed wrong, the indirect address points to a 6 bytes structure (4 bytes offset, 2 bytes segment).

I made a quick fix to test my sample, which seems to work:

```
m1632: Mem is Mem { CS = *:2 (Mem + 4); reloc:4 = *:4 Mem; export reloc; }
:CALLF m1632       is vexMode=0 & addrsize=1 & opsize=1 & byte=0xff; m1632 & reg_opcode=3 ... { pushseg44(CS); build m1632; push44(&:4 inst_next); call [m1632]; }
```

Also, just a small nitpick, I modified the pushseg44 macro to zero-fill the unused bytes of the segment :

```
macro pushseg44(x) {
  mysave:4 = zext(x);
  $(STACKPTR) = $(STACKPTR) - 4;
  *:4 $(STACKPTR) = mysave;
}
```

Should I create a separate pull request to fix the other CALLF/JMPF instructions ?

**Comment by saruman9** [comment]
Sorry for the late response, I tested your binary file with my PR and your fixes. Your are fully right, sleigh code of `callf` instruction for x86_32 is wrong. Yes, could you create a PR for all `callf` instructions, please?

> just a small nitpick, I modified the pushseg44 macro to zero-fill the unused bytes of the segment

I created [the PR](https://github.com/NationalSecurityAgency/ghidra/pull/1378), which fixes the pushing of segment register onto a stack, but I forget about zero-extending. It may not matter for disassembling, but for emulating it will be important. Since you found a mistake, could you also create PR for that?
