### ISSUE TITLE
More division with magic constants

### ISSUE THREAD

**Issue by clienthax** [NationalSecurityAgency/ghidra#1718]
As an extension of https://github.com/NationalSecurityAgency/ghidra/issues/668

PPC64 32bit addressing

It seems some patterns are still unrecognized.
```
uVar1 = (uint)((ulonglong)((longlong)(int)unk_1 * 0x51eb851f) >> 0x20);
uVar1 = (uint)((ulonglong)((longlong)(int)(uint)date_time.year * 0x66666667) >> 0x22
      days_in_years =
           (longlong)
           (int)(((year_uint * 0x16d + ((int)(year_uint + 3) >> 2)) -
                 (uint)((ulonglong)((longlong)(int)(year_uint + 99) * 0x51eb851f) >> 0x25)) +
                 (uint)((ulonglong)((longlong)(int)(year_uint + 399) * 0x51eb851f) >> 0x27) +-0x16e
                );
```
The last one ends up being this after neatening
```
	s64 days_in_years = ((((year * 365ULL) + ((year + 3) / 4)) - ((year + 99) / 100)) + ((year + 399) / 400) + -366);
```

**Comment by Swyter** [comment]
Here's a pattern that Ghidra 9.1.2 can't handle:

![imagen](https://user-images.githubusercontent.com/690187/82763514-9f6eff00-9e08-11ea-9876-48eac5a0a509.png)

It shows up like this:

![imagen](https://user-images.githubusercontent.com/690187/82763535-b4e42900-9e08-11ea-826a-85f617a867e9.png)

**Comment by caheckman** [comment]
Was missing some corner cases.  Should be fixed now in the master branch.
