### ISSUE TITLE
Ownership issue when copying a project between users

### ISSUE THREAD

**Issue by BigJim** [NationalSecurityAgency/ghidra#172]
On Windows (but I suspect will happen on the other OSes as well) if you create a project under your current username then try to give it to someone else, or otherwise just copy it to another machine or VM with a different user name you will get an error:
"..Failure to open project ... NoOwnerException: Project is not owned by xxx.."

To Reproduce:
1. Create a project using username "Bob"
2. Copy that project over a to a different machine (or different user on the same machine, VM, etc), say "Sam" for example.
3. Ghidra will not load the project under a different user (by name) but show an error box instead.

Expected behavior:
It's understandable there needs to be a "user" tracking for collaboration reasons, yet, I'm sure people will want to copy their projects around, to share them, etc.
Maybe as more of a "feature request", Ghidra could simply have a dialog option to either ignore the user mismatch, or switch the config to the current user automatically.

Environment"
 - OS: Any Windows OS
 - Java Version: 11.0.2
 - Ghidra Version: Latest

Additional context:
To get around the issue it's an easy fix for now, just manually edit "project.prp" (an XML file) and change the "VALUE" to the current user.
I.E. '<STATE NAME="OWNER" TYPE="string" VALUE="Sam" />'

![owner_error](https://user-images.githubusercontent.com/424358/54169267-5d96aa80-4448-11e9-9c8e-10b65273a688.png)

**Comment by ahroach** [comment]
If you intend to share the project, export the project to an archive using File->Archive Current Project. On the receiving end, the archive file can be read in with File->Restore Project with no ownership issues.

**Comment by ryanmkurtz** [comment]
@BigJim, is @ahroach 's import/export suggestion sufficient for your needs?  If so, we can go ahead and close the ticket.

**Comment by BigJim** [comment]
Sure that will work. Later I plan to revisit as I setup a dev environment and learn the source in the .zip files.

**Comment by flarn2006** [comment]
What if you're on the receiving end and don't have the archived version? It happened to me once and I seem to remember getting it to work by renaming or editing files or something—creating a temporary user with the correct name would probably work as well—but is there an easier way?

**Comment by Moonslate** [comment]
> 
> 
> What if you're on the receiving end and don't have the archived version? It happened to me once and I seem to remember getting it to work by renaming or editing files or something—creating a temporary user with the correct name would probably work as well—but is there an easier way?

I got this error now, by installing Windows 8 with my actual name instead of my nickname and I could not load the project anymore. For anyone else with this error, you should edit the `project.prp` file:

`<?xml version="1.0" encoding="UTF-8"?>
<FILE_INFO>
    <BASIC_INFO>
        <STATE NAME="OWNER" TYPE="string" VALUE="Your name here" />
    </BASIC_INFO>
</FILE_INFO>`

It's located at `{PROJECTNAME}.rep\project.prp`

I think that the project should be shared by default.

**Comment by flarn2006** [comment]
Yeah, that sounds similar to what I did. Thanks for explaining. Seems like
a thing it should do automatically, but I guess given how Ghidra began it's
understandable they wouldn't have had a need for it.

**Comment by RenaKunisaki** [comment]
Are there any security concerns with importing an archive you find online? I noticed there seems to be built-in capability to execute commands in comments?

**Comment by userse31** [comment]
> If you intend to share the project, export the project to an archive using File->Archive Current Project. On the receiving end, the archive file can be read in with File->Restore Project with no ownership issues.

The project archiving feature is a genuinely nice touch, but I can't help but sit here and wonder why this user id checking this here in the first place.

"What's the f*****ing point!?"
