### ISSUE TITLE
Unable to see the decompiler screen on the right 

### ISSUE THREAD

**Issue by bhaviksec** [NationalSecurityAgency/ghidra#1720]
This was working until reporting this issue. With no changes made I could not see the decompiler tab . I also do not see an option to get it back 

Have the decompiler.java file 

Attaching snapshot. Appreciate your help
<img width="1666" alt="Screenshot 2020-04-07 at 3 42 29 PM" src="https://user-images.githubusercontent.com/62103691/78657760-e0f22c00-78e6-11ea-8b6d-07faedd15965.png">

**Comment by bhaviksec** [comment]
> This was working until reporting this issue. With no changes made I could not see the decompiler tab . I also do not see an option to get it back
> 
> Have the decompiler.java file
> 
> Attaching snapshot. Appreciate your help
> <img alt="Screenshot 2020-04-07 at 3 42 29 PM" width="1666" src="https://user-images.githubusercontent.com/62103691/78657760-e0f22c00-78e6-11ea-8b6d-07faedd15965.png">

Do not see the decompiler under window . 

total 8
drwxr-xr-x@  7 bhavsha2  staff  224 Feb 12 12:10 .
drwxr-xr-x@ 24 bhavsha2  staff  768 Feb 12 12:10 ..
-rw-r--r--@  1 bhavsha2  staff  730 Feb 12 12:10 LICENSE.txt
-rw-r--r--@  1 bhavsha2  staff    0 Feb 12 12:10 Module.manifest
drwxr-xr-x@ 17 bhavsha2  staff  544 Feb 12 12:10 ghidra_scripts
drwxr-xr-x@  4 bhavsha2  staff  128 Feb 12 12:10 lib
drwxr-xr-x@  5 bhavsha2  staff  160 Feb 12 12:10 os
<img width="272" alt="Screenshot 2020-04-07 at 3 48 17 PM" src="https://user-images.githubusercontent.com/62103691/78658099-607ffb00-78e7-11ea-8f6c-a70c93ce09c8.png">

**Comment by ryanmkurtz** [comment]
It looks like your CodeBrowser tool got corrupted, possibly by closing Ghidra in a bad state.  Try this:

1. In the Ghidra Front End window, right click on the green dragon (under Tool Chest), and click Delete...
2. In the Front End windows, go to Tools -> Import Default Tools...
3. Select defaultTools/CodeBrowser.tool and hit OK

It should be fixed now. 

Alternatively, you could just delete your ~/.ghidra directory and everything will get loaded fresh the next time you start Ghidra.

**Comment by bhaviksec** [comment]
It fixed thanks

**Comment by ryanmkurtz** [comment]
Sure thing!  Feel free to close the issue.

**Comment by bhaviksec** [comment]
the solution provided worked
