### ISSUE TITLE
View script path of script in Script Manager

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1724]
**Is your feature request related to a problem? Please describe.**
When duplicate scripts are detected it can be difficult to track down where the duplicates are.

**Describe the solution you'd like**
It would be useful to be able to view the path of the selected ghidra script from within the Script Manager. This could be done on mouse hover by option on right click.

**Describe alternatives you've considered**
You can see the path by right clicking the script and selecting rename. However this seems a bit evasive if you don't actually want to rename the script.

**Comment by ryanmkurtz** [comment]
There is a hidden "Path" column in that table.

**Comment by astrelsky** [comment]
I didn't realize that there were more columns I could add or remove. Thank you!

**Comment by ryanmkurtz** [comment]
> I didn't realize that there were more columns I could add or remove. Thank you!

No problem.  Most of the tables have hidden columns...some can be pretty useful.
