### ISSUE TITLE
Visual editing of Java Dialogs

### ISSUE THREAD

**Issue by beketata** [NationalSecurityAgency/ghidra#1725]
My working environment is Windows 7 64 and I use Eclipse for editing/debugging Java code.
I am trying to add some new features to the decompiler but have run into the problem of editing Java dialogs.
I installed Swing WindowBuilder in Eclipse. Unfortunately, for example, **FunctionEditorDialog** class does not open in the designer with a few errors. By slightly modifying the source code, it finally opened.

![WindowBuilder](https://user-images.githubusercontent.com/7413903/78707068-eaed4c80-7931-11ea-8a37-4b2b22a62996.jpg)

Therefore, I have a question, maybe there is another way of dialogs visual editing?

**Comment by ryanmkurtz** [comment]
The Ghidra GUI is not written using visual editors....it is all hand written Swing.

**Comment by beketata** [comment]
Making dialogs manually is superb of course! But have you considered a way to implement visual editing to involve new members who aren't so cool? :smiley:

**Comment by ryanmkurtz** [comment]
I doubt that would ever get implemented, it would be a massive effort.  Ghidra has so many custom widgets and ways of doing GUI things that it's almost its own GUI framework.

**Comment by dragonmacher** [comment]
As @ryanmkurtz mentioned, we have no tools for visual editing.  You can certainly create your own widgets any way you choose and then use them as plugins to Ghidra.
