### ISSUE TITLE
How to use "Find Uses of" feature of Ghidra in Headless Analyzer?

### ISSUE THREAD

**Issue by zrezapou** [NationalSecurityAgency/ghidra#1727]
I have a C++ program, and the source code of this program consists of various structs. Given an address showing an assembly instruction, my goal is to find the field of the structure that is accessed by the instruction using headless analyzer.   

For example, for the instruction at address "0020c6a6", I should get field “num_object” of structure “record”. 

![qqq - Copy](https://user-images.githubusercontent.com/63321713/78725535-c7a8aa00-78fd-11ea-974b-269546c36727.PNG)

The “Find Uses of” feature in ghidra GUI is quite useful. But is there a way to use this feature in headless analyzer? 

“Find Uses of” feature provides all references to a datatype in addition to  all the decompiled c codes, assembly codes, and the addresses of related instructions.

**Comment by saruman9** [comment]
Relates to #1803, I think.

**Comment by dragonmacher** [comment]
You can call the API that performs that search directly from a script by calling:
`ghidra.app.plugin.core.navigation.locationreferencesReferenceUtils` methods such as:

```
	public static void findDataTypeReferences(Accumulator<LocationReference> accumulator,
			DataType dataType, Program program, boolean discoverTypes, TaskMonitor monitor)
			throws CancelledException {
```
