### ISSUE TITLE
dex to jar abort between 60% to 90%

### ISSUE THREAD

**Issue by n82freak** [NationalSecurityAgency/ghidra#173]
I try to analyse some apk files.
At dex to smali works fine 
but if i tried dex to jar the process stuck after 60% and abort with a bug message before reaches 90% or more !
I tried with a lot different apks but always get the same issue... 
How to fix that ?

**Comment by yakamoz147** [comment]
For me it works without issues so you should provide more information about your setup.

**Comment by ryanmkurtz** [comment]
Closing issue since we never got any follow up info.  We can reopen it if more information is provided.
