### ISSUE TITLE
Support Fat Mach-O binaries

### ISSUE THREAD

**Issue by AntonKukoba1** [NationalSecurityAgency/ghidra#1737]
Ghidra can now only load a separate Mach-o slide of a single architecture, so when adding Fat Mach-O file into the project, it's detected as Raw Binary. 
The file should be detected as Fat Mach-O, not as Raw Binary. Then the menu with the slide selection should be shown, as it's done in IDA.
![image](https://user-images.githubusercontent.com/35240638/79003216-d0e28280-7b5a-11ea-9d2d-84c8a21fd6a4.png)

**Comment by ryanmkurtz** [comment]
Ghidra should detect this type of file as a file system.  Try opening it in the File System Browser.

**Comment by ryanmkurtz** [comment]
Any luck with this?
