### ISSUE TITLE
Graph service provider

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#174]
When I try to run script `GraphAST`/`GraphASTAndFlow`/`GraphSelectedAST`/ (may be others) I get a message "_GraphService not found: Please add a graph service provider to your tool_". I think, that I can search it in Configure Tool, but I can't. How can I add a graph service provider?

**Comment by dragonmacher** [comment]
The version of Ghidra you are using does not currently contain an implementation of the Graph Service.  Thus, the actions you mention will not currently work.

The ghidra.app.services.GraphService service interface is built into the system.   As such, it is possible for developers to create an implementation of this interface.   If Ghidra detects any implementation(s) for this service, then the above mentioned actions, as well as others, will become functional.
