### ISSUE TITLE
A potential NPE in GhidraServerApplicationLayout

### ISSUE THREAD

**Issue by HermioneSW** [NationalSecurityAgency/ghidra#1742]
**Describe the bug**
1. In ```ResourceFile.java``` (Ghidra/Framework/Utility/src/main/java/generic/jar/ResourceFile.java
), function ```getParentFile()``` returns null when ```parent``` is null.

2. In ```GhidraServerApplicationLayout.java``` (Ghidra/Features/GhidraServer/src/main/java/ghidra/server/remote/GhidraServerApplicationLayout.java), line 47 ```applicationInstallationDir = getApplicationRootDirs().iterator().next().getParentFile();``` ```applicationInstallationDir``` will be assigned null.

3. line 49 ```applicationInstallationDir = applicationInstallationDir.getParentFile();``` will NPE

**To Reproduce**
See above

**Expected behavior**
N/A

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
A Ghidra application root directory is always the parent directory of the `Ghidra/application.properties` file (i.e., the directory named "**Ghidra**").  In other words, it can't be a filesystem's root directory.  So, `getParentFile()` in this case will never return `null`.  I'd be happy to be proven wrong though with a stack trace.  Otherwise, this ticket can be closed.

**Comment by HermioneSW** [comment]
@ryanmkurtz thanks for the reply. Actually one question would clarify if ```getParentFile()``` never return null, why not  simply do 

    public ResourceFile getParentFile() {
         Resource parent = resource.getParent();
         return new ResourceFile(parent);
    }

Thanks!

**Comment by ryanmkurtz** [comment]
getParentFile() can definitely return null sometimes, but not in the GhidraServerApplicationLayout case you highlighted.

**Comment by HermioneSW** [comment]
great to know! Close the issue
