### ISSUE TITLE
Allow renaming of labels in decompiler view

### ISSUE THREAD

**Issue by pedrib** [NationalSecurityAgency/ghidra#1751]
**Is your feature request related to a problem? Please describe.**
Currently we can rename labels in the disassembly view, but not the decompiler view. This is a bit painful, and it's a standard feature in IDA that I'd love to see done here.

**Describe the solution you'd like**
Same as IDA: right click / rename (or press the shortcut key) while in decompiler view on top of a label should allow it to be renamed.

**Comment by ryanmkurtz** [comment]
You can rename a lot of things in decompiler view.  What exactly are you trying to rename?

**Comment by pedrib** [comment]
Check the label highlighted in the decompiler view in the attached screenshot. It can be renamed in the disassembly view, and then the decompiler view will change to reflect the new name.

However ideally it would mimic IDA behaviour - you could just change the name directly on the decompiler view.

![highlighted_label](https://user-images.githubusercontent.com/5311656/79073331-2744f200-7d10-11ea-9109-515a917ed1ba.jpg)

**Comment by 99r** [comment]
Still relevant

**Comment by dragonmacher** [comment]
Not sure how this has gone unnoticed for so long.

**Comment by pedrib** [comment]
You guys are da bomb
