### ISSUE TITLE
Reference searching cross multiply dex files

### ISSUE THREAD

**Issue by yangxiaomin08** [NationalSecurityAgency/ghidra#1757]
**Is your feature request related to a problem? Please describe.**
Many apps are too large and have multiply dex files.  So far, I didn't see Ghidra support the cross reference searching among these dex files, such dex A calls method in dex B. If I am wrong, please correct me. thanks. 

**Describe the solution you'd like**
Loads and analysis all the dex files inside APK file rather than one dex file by one. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanmkurtz** [comment]
Duplicate of #4276. Please follow that ticket for updates.
