### ISSUE TITLE
[MIPS] RFE instruction not present.

### ISSUE THREAD

**Issue by nicolasnoble** [NationalSecurityAgency/ghidra#1764]
The MIPS instruction set contains an instruction called "RFE", for "Return From Exception". Its encoding is well specified, with no parameters: http://people.cs.pitt.edu/~don/coe1502/current/Unit4a/Unit4a.html

This document translates "RFE" to the opcode 0x42000010

The point of the RFE instruction is to restore cop0 status flags atomically while returning to the user space. Its pseudo-code implementation can be seen as the following:

```
    COP0.Status = (COP0.Status & 0xfffffff0) | ((COP0.Status & 0x3c) >> 2);
```

The explanation of this behavior is simple: when triggering an exception, the MIPS CPU does the following atomically, in order to save usermode flags:

```
    COP0.Status = (COP0.Status & ~0x3f) | (CP0.Status & 0xf) << 2);
```

When disassembling a MIPS exception handler from a MIPS kernel with ghidra, it will currently fail to disassemble that instruction properly, nor recognize it as even an executable instruction:

![image](https://user-images.githubusercontent.com/7281574/79148711-cdc5dd00-7d7a-11ea-82cc-e41f7c5b7362.png)

**Comment by nicolasnoble** [comment]
Other disassemblers that support this instruction properly:

![image](https://user-images.githubusercontent.com/7281574/79150049-f4851300-7d7c-11ea-89fc-5e64f7cf7e91.png)

**Comment by mumbel** [comment]
This is the instruction I referenced in your other ticket.  I couldn't find any instruction to match this in any PDFs. You could copy this into mips32Instructions.sinc and see if it helps 

```
# 0100 0010 0000 0000 0000 0000 0001 0000
:rfe                           is $(AMODE) & prime=0x10 & fct=0x10 & bit25=1 & copfill=0  {
    Status = (Status & 0xfffffff0) | ((Status & 0x3c) >> 2);
}
```

**Comment by nicolasnoble** [comment]
> This is the instruction I referenced in your other ticket.
Oh, I see what you're saying now.

> I couldn't find any instruction to match this in any PDFs.
You need to dive into kernel development to start hearing about it. In fact, some assemblers won't even recognize the instruction, and writing portable kernel mips code requires to do some trickery such as this horror:

```mips
    jr    $k0
    .word 0x42000010 /* rfe */
```

You could copy this into mips32Instructions.sinc and see if it helps
> 
> ```
> # 0100 0010 0000 0000 0000 0000 0001 0000
> :rfe                           is $(AMODE) & prime=0x10 & fct=0x10 & bit25=1 & copfill=0  {
>     Status = (Status & 0xfffffff0) | ((Status & 0x3c) >> 2);
> }
> ```
Yep, this sort of works nicely.

![image](https://user-images.githubusercontent.com/7281574/79157087-cf969d00-7d88-11ea-8363-0cc3dc37ca5d.png)

I would've expected it to be printed `_rfe` however, since it's in the delay slot of the `jr` above. But that's not really a big deal.

Decompilation is a bit wonky, but that sort of code isn't really meant to be written in plain-C anyway, so it's fine the decompilation doesn't necessarily make total sense.

**Comment by mumbel** [comment]
the _ is interesting, guessing its just because you might have already had the jr disassembled (which failed to do all the logic involved with delay since the delay slot instruction was broken) so when you disassembled the rfe, it had no clue it should be in the delay slot

submitted a PR for this fix

**Comment by nicolasnoble** [comment]
> the _ is interesting, guessing its just because you might have already had the jr disassembled (which failed to do all the logic involved with delay since the delay slot instruction was broken) so when you disassembled the rfe, it had no clue it should be in the delay slot

Oh, that's correct. I cleared the whole function and re-disassembled it, and now the underscore shows up.

> submitted a PR for this fix

Thanks!

**Comment by AllbrittonKevin** [comment]
The#,_is interesting further still.

**Comment by mumbel** [comment]
@AllbrittonKevin _ is ghidra's notation for delay slot instruction(s). What is interesting and where are you seeing "#,_"

**Comment by emteere** [comment]
Has been fixed and should be in patch and master soon.
Thanks for fixing.
