### ISSUE TITLE
CreateFunction(address,name) cannot create some functions when evoked via analyzeHeadless  

### ISSUE THREAD

**Issue by gsrishaila** [NationalSecurityAgency/ghidra#1765]
**Describe the bug**
A clear and concise description of the bug.
The createFunction function does not create a function at certain addresses when we use the analyzeHeadless  script to evoke it. However, functions can be created manually or by calling the function by running the script  by using Ghidra GUI.

**To Reproduce**
1.	Use the analyzeHeadless script to import  binary, mymainRealOwari_mips03Strip into Ghidra. This is done by the autoGhidraScript2.py.
2.	User the analyzeHeadless script to run the createNewFunc.java script. This script uses the createFunction function to create functions at these addresses:
0x 401d40
0x 403894
0x 403eb8
0x 4049e0
0x 405558
0x 40618c
0x 406fa8
0x 407fac
3.	Notice that the functions were not created at the following addresses:
0x 4049e0
0x 40618c
0x 407fac
4.	However, you can manually use the right click>create function option to create functions at these address locations in the Ghidra GUI or run the createNewFunc.java script by using the script manager in the Ghidra GUI.

**Expected behavior**
We expect that functions will be created at a certain address when the createFunction function is called by using the analyzeHeadless script or via the Ghidra API.

**Screenshots**
![Screenshot (189)](https://user-images.githubusercontent.com/5535776/79155734-73cb1480-7d86-11ea-8481-a5fbcef6906d.png)

Function could not be created at 0x 4049e0 when createNewFunc.java script was executed via the analyzeHeadless script.

![Screenshot (198)](https://user-images.githubusercontent.com/5535776/79155863-aaa12a80-7d86-11ea-9d5d-2859b3efb60c.png)

Function created at 0x 4049e0 when createNewFunc.java script was executed via the script manager in Ghidra GUI.

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.
[files.zip](https://github.com/NationalSecurityAgency/ghidra/files/4471924/files.zip)

**Environment (please complete the following information):**
 OS: Ubuntu 18.04 LTS and Windows 10 Home Ed
Java Version: Open jdk version 11.0.6
Ghidra Version: Ghidra 9.0.4 and Ghidra 9.1

**Additional context**

**Comment by ryanmkurtz** [comment]
Are you doing -preScript or -postScript?

**Comment by gsrishaila** [comment]
I have attached all the files i have used in files.zip. I used -postscript.

**Comment by 0x0ACB** [comment]
I am noticing the same issue. Works fine when running the script manually from the script manager. However in headless mode createFunction sometimes fails.

**Comment by Martmists-GH** [comment]
Noticing the same behavior in 10.1.5:

```kotlin
// This is code from a class extending ghidra.app.services.AbstractAnalyzer
// api is a FlatProgramAPI wrapping an externally linked library
if (api.getFunctionAt(addr) == null) {
    api.createFunction(addr, "${moduleName}_anonymous_${importSegment}_${importOffset.toString(16)}")
}
val externalFunction = api.getFunctionAt(addr)
```

**Comment by ryanmkurtz** [comment]
I'm having trouble reproducing this.  Would someone with the issue mind trying in 10.2?
