### ISSUE TITLE
Allow using a name that differs from hostname when connecting to shared projects

### ISSUE THREAD

**Issue by MaryWeeb** [NationalSecurityAgency/ghidra#1768]
I use Ghidra on multiple devices across multiple OSes, and due to the way windows behaves, I have no proper control over the username. This causes me to have to request adding another user to the server every time I use a new device, which would be easily avoided if I could choose the username to be the same as my linux usernames.

EDIT: #357 seems to indicate `-Duser.name=...` can be used, but I don't see this documented anywhere. Additionally, this should really be configurable through the UI somewhere, whether it's a preference setting or when connecting to a repository.

**Comment by ryanmkurtz** [comment]
`-Duser.name=...` it kind of a hack with some possibly undesirable consequences.  You are basically telling the entire JVM what the username of the system is.  One consequence of this is that Ghidra will store files in `~/.ghidra`, where `~` is the "user's" home directory.

**Comment by dev747368** [comment]
Does the server.conf parameter "wrapper.app.parameter.NN=-u" not help?

**Comment by martmists** [comment]
I don't have access to the server sadly, as it's used for quite a large organization.

**Comment by ghidra1** [comment]
This is a Ghidra Server installation policy decision to enable this capability.

**Comment by henke37** [comment]
What does that even mean?

It's pretty standard stuff to let users specify both username and password when logging in to a service.

**Comment by larkwiot** [comment]
@ghidra1 Does that mean this is something that's enabled by default but can be changed by the server admin at install time, or something else?
