### ISSUE TITLE
Calculating cyclomatic complexity

### ISSUE THREAD

**Issue by localacct** [NationalSecurityAgency/ghidra#177]
Hi

I am trying to understand how I can use the APIs to calculate the cyclomatic complexity of a particular function/sub routine.

I came across generic.stl.RedBlackNode<K,​V> which might fit my needs? However, I am not exactly sure how to use the class and its functions getSuccessor, getPredecessor etc.

Do I do something such as

````
import generic.stl.RedBlackNode

x=generic.stl.RedBlackNode.getPredecessor()"
````

There is no constructor so I don't have to instantiate one but I do get an error

````
TypeError: getPredecessor(): expected 1 args; got 0
````

Sorry, I am not too familiar with using Jython, so my apologies.

**Comment by saruman9** [comment]
It can be so:
```
import java
from generic.stl import RedBlackTree


class Comparator(java.util.Comparator):
    def compare(self, a, b):
        return a > b

tree = RedBlackTree(Comparator(), False)
tree.put("1", 1)
tree.put("2", 2)
tree.getFirst() # 1
```

Also can be useful: `ComputeCyclomaticComplexity` from Script Manager.

**Comment by localacct** [comment]
Hi

Thanks for the quick response. Would you happen to know how to code it in Python? I saw the script in the Script Manager and I think it answers my question.
