### ISSUE TITLE
GnuDemangler IOExceptions with External Options

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1770]
**Describe the bug**
Specifying an older demangling format causes an IOException when attempted to be used with `demangler_gnu_v2_33_1`

**To Reproduce**
1. Go to DemanglerGnu in Analyzers
2. Set "Use External Demangler Options" to  `-s gnu`
3. See IOException in log

**Expected behavior**
Older demangling formats which do not exist in demangler_gnu_v2_33_1 shouldn't be passed as the format option.

**Environment (please complete the following information):**
 - Ghidra Version: 9.2

**Additional context**
The simplest fix would probably to not attempt to use the new demangler if demangling fails when "Use Deprecated Demangler" is set.

**Comment by dragonmacher** [comment]
In this particular case, the modern demangler fails, but the deprecated demangler still gets called.  This is not clear from the error message.   

We can fix this a few ways.  As @astrelsky mentioned we could ignore the modern demangler when using the deprecated demanger.  However, this is currently a feature that both get called.   We could attempt to validate the arguments, but this would be difficult and error-prone in a free-form text field.

Two reasonable choices: add a second text field for options so that each demangler would have its own arguments, or perhaps better, ignore the specific 'unknown demangling style' exception when also using the deprecated demangler for which the option is valid.

**Comment by astrelsky** [comment]
> In this particular case, the modern demangler fails, but the deprecated demangler still gets called. This is not clear from the error message.
> 
> We can fix this a few ways. As @astrelsky mentioned we could ignore the modern demangler when using the deprecated demanger. However, this is currently a feature that both get called. We could attempt to validate the arguments, but this would be difficult and error-prone in a free-form text field.
> 
> Two reasonable choices: add a second text field for options so that each demangler would have its own arguments, or perhaps better, ignore the specific 'unknown demangling style' exception when also using the deprecated demangler for which the option is valid.

I was thinking of using an enum to represent the available formats with a selection box to choose from instead of the free-form text. It would simplify its use since the free-form requires knowing which formats are supported. Using an enum would make it easier to maintain if formats are added/removed in the future since the selection box could be populated with say `DemanglerFormat.values()` and the required arguments and display name populated via it's methods. It's been something I've been wanting to implement and submit but I've just been swamping myself with things on my todo list on top of job hunting and haven't gotten around to it yet.

**Comment by dragonmacher** [comment]
> It's been something I've been wanting to implement and submit but I've just been swamping myself with things on my todo list on top of job hunting and haven't gotten around to it yet.

Well, I can easily say that you are currently the largest outside contributor, with regard to code and user help.  Thanks!

IMO, I think the other stuff you are working on is more important than this particular issue.

**Comment by ryanmkurtz** [comment]
> on top of job hunting

Mind if I ask what type of work you are looking to get into after college?

**Comment by astrelsky** [comment]
> > on top of job hunting
> 
> Mind if I ask what type of work you are looking to get into after college?

Preferably something ghidra or reverse engineering related. I could probably fall back to embedded software development.
