### ISSUE TITLE
Scrolling speed on the "Python Interpreter" pane depends on its size

### ISSUE THREAD

**Issue by Arcnor** [NationalSecurityAgency/ghidra#178]
**Describe the bug**
As the title mentions, the mouse/trackpad scrolling speed on the Python Interpreter pane (maybe in others, but it seems there are 3 kinds of pane: one for source editors, one for TreeViews and the rest?) depends on the size. If you make it very small, the scrolling goes by a fraction of a line, but if you make it almost the size of the screen it will skip many lines at a time.

**Expected behavior**
The scrolling should be the same in every pane: smooth.

**Environment (please complete the following information):**
 - OS: macOS 10.14.3
 - Java Version: AdoptOpenJDK 11.0
 - Ghidra Version: 9.0

**Comment by adamopolous** [comment]
This is the default behavior of the JTextPane (increments are always 10% of panel size) and it seems to be a fairly standard way to do things (eg: eclipse editors do this). We can revisit at some point if this really seems to bug people.

**Comment by Arcnor** [comment]
This is of course up to you, but I don't think that "Eclipse doing this" is the same as "being standard", which I think it's actually the opposite (no major UI toolkit does this AFAIK). Even if it were, the current behavior is just annoying because of its unpredictability (you don't know how much you're going to scroll, because now it depends on its content).

Also, it's not consistent to how things scroll in other parts of the app, which makes it even more annoying.
