### ISSUE TITLE
How does the API expose basic blocks the way the function graph shows them?

### ISSUE THREAD

**Issue by mark-griffin** [NationalSecurityAgency/ghidra#1781]
Is there a clean way to get a graph or other data structure describing the basic blocks of a function and their successors the way the Function Graph shows them?

Currently I'm iterating the blocks from a BasicBlockModel and their destinations and removing destinations where the flowType.isCall() or if flowType == INDIRECTION, which seems suboptimal and may be incorrect in some cases. The function graph shows the basic blocks and edges that I want, so either it is already stored or the logic to do this exists, but my question is where/how?

**Comment by ryanmkurtz** [comment]
I think this has been asked a bunch of times.  Check out some of [these issues](https://github.com/NationalSecurityAgency/ghidra/issues?q=is%3Aissue+%22basic+block%22+is%3Aclosed+)...you might find a good answer in there.

**Comment by mark-griffin** [comment]
I have looked at those issues; they aren't quite what I'm asking. 

The crux of my issue is that the data contained the iterators returned by getCodeBlocks* functions from any of the CodeBlockModel subclasses don't exactly match what is shown in the Function Graph.

For example, in the Function Graph, call instructions don't split blocks, but using BasicBlockModel.GetCodeBlocksContaining(address_set, monitor) returns blocks which include destinations other than the outgoing edges shown in the graph (such as destinations relating to call instructions). I'm asking if there is a way to get a block model that doesn't include those destinations in the blocks, or if not, what's the correct logic for discarding destinations to always get the same structure that is displayed in the Function Graph window? 

Thanks for any help 👍

**Comment by cetfor** [comment]
Hey @mark-griffin ,

Can you check out [Issue 855](https://github.com/NationalSecurityAgency/ghidra/issues/855) and see if it helps you? There's some example Python code that addresses the issue of out of function basic blocks appearing due to calls.

It basically uses `getFunctionAt()` to check if the basic block in the `BasicBlockModel.GetCodeBlocksContaining` iterator is internal to the function or exists outside of the function. It's worked well for me, but I'm also looking for other methods of doing this.

Using this code should produce a set of `ghidra.program.model.block.CodeBlockImpl` that contain edges corresponding exactly to the graph view generated by Ghidra.

**Comment by mark-griffin** [comment]
Thanks @cetfor, this is the kind of thing I was looking for. 

I have a counterexample that breaks the logic as laid out in issue 855, but it's close.  In a basic Linux binary I've been using for testing, the first PLT function (objdump names it `.plt`, Ghidra gives it an anonymous function name based on address) has a destination address in an external section `.got.plt` for which `getFunctionAt()` returns None. However, inverting the logic and only including destinations for which `getFunctionAt()` matches the function of the original block seem to work (so far), and this makes sense intuitively.

I'll leave this open for a bit in case anybody knows if there are corner cases that might affect this logic... for example, is it possible to overlay blocks or do other strange things to make `getFunctionAt` yield a false positive or negative.
