### ISSUE TITLE
inconsistent description and language spec

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#1782]
**Describe the bug**
i am trying to map a raw binary DATA file in some adresse.
So i import the file's raw data as a binary in the project. Then i had to select the language :
I have two choice for language Spec.
![image](https://user-images.githubusercontent.com/4013370/79514252-0816cf00-8046-11ea-9f6c-41f6a0645b2c.png)
But description for both the little and big Endian says "Little Endian"

**Expected behavior**
Language spec to be Consistent with it's description.

**Environment (please complete the following information):**
 - OS: linux
 - Java Version: 13
 - Ghidra Version: 9.1.2 release

**Additional context**
ARM v8 big endian project

**Comment by astrelsky** [comment]
I've confirmed it is just a copy/paste error in the description. Everything else in the language definition file is correctly defined as big endian.
