### ISSUE TITLE
Concerns with extensions using the program database

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1789]
I have recently been informed of issues with memory usage for my [Ghidra-Cpp-Class-Analyzer](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer). I have begun developing and testing DatabaseObject implementations along with a ManagerDB in order to resolve it. I wish to inform the dev team of this and would like to hear any concerns with using the program's DBHandle before making anything public. I became aware during testing that if an IOException occurs and the program is informed of a dbError, Ghidra immediately closes the program and informs the user. I'm sure this is done to prevent any loss of data and to protect the existing database from corruption.

I have implemented steps to inform the user that an exception has originated from my extension whenever one occurs to prevent what occurred with #1750.

The ManagerDB I have implemented inserts its own tables into the program's dbHandle. It doesn't access any other tables in any way. The Schema's I'm using are relatively simple and mostly consist of Address encoded longs in the same fashion done by the SymbolManager and long keys as references to other DatabaseObjects created by my extension. I would like to include key's to things such as Symbol id's so that the the Ghidra Class doesn't need to be constantly looked up. However, I am unsure of the consistency of these keys and am aware that they can change.

For reference this is currently the base Schema being used for ClassTypeInfo database implementations.
```
public static final Schema SCHEMA =
    new Schema(
        VERSION,
        "Key",
        new Class[] {
            StringField.class,
            ByteField.class,
            LongField.class,
            LongField.class,
            BooleanField.class,
            LongField.class,
            BinaryField.class
        },
        new String[] {
            "type name",
            "typeinfo type id",
            "address",
            "datatype id", // DataType's UniversalID
            "vtable searched",
            "vtable key",
            "model specific data"
        }
);
```

**Comment by hedgeberg** [comment]
Is there not some higher-level API that allows for adding class objects from scripts without directly accessing and modifying the database? If not, this feels like a major gap in the API's capabilities. How does ghidra's demangler analysis go about adding new class objects? 

@astrelsky if you're interested, there's a discord where a few ghidra plugin devs collaborate over at https://discord.gg/en8Wx2U, we'd love to have you come hang out there and help you figure out another way to do this, especially since we've all made use of your plugin at this point.

**Comment by astrelsky** [comment]
> Is there not some higher-level API that allows for adding class objects from scripts without directly accessing and modifying the database? If not, this feels like a major gap in the API's capabilities. How does ghidra's demangler analysis go about adding new class objects? 
> 
> @astrelsky if you're interested, there's a discord where a few ghidra plugin devs collaborate over at https://discord.gg/en8Wx2U, we'd love to have you come hang out there and help you figure out another way to do this, especially since we've all made use of your plugin at this point. 

There is Savable, but I'm currently in quite deep and would prefer to directly manage the table. 

I just don't want to cause the dev team a headache by putting things in the programs db if it might cause problems.

**Comment by astrelsky** [comment]
Well, if there's any problem with it I consider it too late now.
