### ISSUE TITLE
How can I get Elf Program Headers with Ghidra api

### ISSUE THREAD

**Issue by TinyNiko** [NationalSecurityAgency/ghidra#1794]
I want to get ElfProgramHeaders  info but I can't find useful api to get that. Do anyone konw it ?

**Comment by astrelsky** [comment]
> I want to get ElfProgramHeaders info but I can't find useful api to get that. Do anyone konw it ?

Unfortunately you cannot. If you need to obtain the ElfProgramHeaders you must rebuild them. You may do so using the same method used by ElfSectionProvider. ElfSectionProvider has no getter for it's ElfHeader so you have to copy the code.

https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/dwarf4/next/sectionprovider/ElfSectionProvider.java#L40-L64

**Comment by TinyNiko** [comment]
Thank you

**Comment by saruman9** [comment]
@astrelsky is right, you can't get `ElfProgramHeaders` by using API. I [wrote the script](https://gitlab.com/saruman9/ghidra_scripts/-/blob/master/GetEntryPoints.java) for similar task (parsing PE header), you can use it as example.
