### ISSUE TITLE
MacOS cannot verify software fix

### ISSUE THREAD

**Issue by mayankmetha** [NationalSecurityAgency/ghidra#1799]
**Is your feature request related to a problem? Please describe.**
Currently on macOS Catalina, apps needs to be signed. Due to this issue this app won't execute now on the latest macOS build.

**Describe the solution you'd like**
Fix the issue.

**Comment by ryanmkurtz** [comment]
I have had no problems running Ghidra on macOS 10.15.4.  What error/popup from macOS are you getting?

**Comment by DrTsukamoto** [comment]
With Catalina, you need to be careful about copying vs downloading.  If 
you download software and then attempt to run it, you get the option to 
mark it in Settings->Security as OK.  If you copy it over, you don't get 
that option and enabling it is considerably more work.

**Comment by mayankmetha** [comment]
> With Catalina, you need to be careful about copying vs downloading.  If you download software and then attempt to run it, you get the option to mark it in Settings->Security as OK.  If you copy it over, you don't get that option and enabling it is considerably more work.
> […](#)

This seems to fix the issue. Thanks @DrTsukamoto
