### ISSUE TITLE
Does ghidra support FLIRT signature?

### ISSUE THREAD

**Issue by hax0kartik** [NationalSecurityAgency/ghidra#18]

**Comment by quosego** [comment]
No extensions have been included with those features as of 9.0. There is a compare analysis script. Someone in the community will probably provide one they made in the following days to come. 

Tons of sample code in here to get started.

**Comment by hax0kartik** [comment]
https://gist.github.com/hax0kartik/e358ce447a4537bcef534aa8de84817c
