### ISSUE TITLE
Getting Library from Data Relocation

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1800]
I'm looking to get the correct [Library](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Library.html) for a relocation and open it in ghidra if it exists in the project. Since ghidra doesn't perform any data relocations it is necessary to open the program in order to get the data necessary for analysis. I'm currently brute forcing this but there has to be a better way. This is what I'm currently using.

```
// reloc is a Relocation
ExternalManager manager = program.getExternalManager();
for (String name : manager.getExternalLibraryNames()) {
	if (name.equals(EXTERNAL)) {
		continue;
	}
	String path = manager.getExternalLibraryPath(name);
	if (path == null) {
		continue;
	}
	Program exProgram = openProgram(path);
	if (exProgram != null) {
		SymbolTable exTable = exProgram.getSymbolTable();
		if (exTable.getSymbols(reloc.getSymbolName()).hasNext()) {
			return exProgram;
		}
	}
}
```

While it does work it doesn't make sense to go through each library and search its entire symbol table for the symbol.

**Comment by ccarpenter04** [comment]
While it's not an API level improvement nor is it an optimal solution, and assuming you're doing more than one lookup, you could use a HashMap<String, Program>

**Comment by astrelsky** [comment]
> While it's not an API level improvement nor is it an optimal solution, and assuming you're doing more than one lookup, you could use a HashMap<String, Program>

While this would work if I kept a reference to the map in the analyzer handling the external Program is still a pain. I'm not entirely sure how a user would feel or does feel (since I'm technically already doing it) about opening another program in the project and making changes to it. Of course the changes aren't saved without them doing so themselves, but watching a bunch of tabs in the listing open could be a nuisance.

The only thing I can think of to fully handle it would be to create a database from the dynamic libraries required in the project and go through the program to place in the missing data and external locations before running analysis. While it does require combing through each library at least it would only occur once. I could probably also distribute the packed databases for common libraries like libstdc++.so
