### ISSUE TITLE
rpm problems: Missing +x permissions on all os/linux64 binaries

### ISSUE THREAD

**Issue by rurban** [NationalSecurityAgency/ghidra#1801]
**Describe the bug**
All the /usr/share/ghidra*/**/os/linux64/* binaries are missing the executable permissions
when being installed via the fedora 31 rpm
leading to error 13 errors on analyze, ...

**To Reproduce**

```
sudo rpm -i https://forensics.cert.org/cert-forensics-tools-release-31.rpm
sudo dnf --enablerepo=forensics install ghidra

ls -al /usr/share/ghidra_9.1.2_PUBLIC/GPL/DemanglerGnu/os/linux64/demangler_gnu
/usr/share/ghidra_9.1.2_PUBLIC/GPL/CabExtract/os/linux64/cabextract
/usr/share/ghidra_9.1.2_PUBLIC/Ghidra/Features/Decompiler/os/linux64/decompile
/usr/share/ghidra_9.1.2_PUBLIC/Ghidra/Features/Decompiler/os/linux64/sleigh

```
RELEASE PUBLIC_20200212.1.fc31
linux64
version 9.1.2

----

If I remember correctly the starter script
`/usr/share/applications/ghidra.desktop`
pointed to /usr/share/ghidra_9.1.2/ without the _PUBLIC suffix.

**Comment by mumbel** [comment]
this is a distribution issue, not ghidra.  The only official binary release for ghidra is ghidra-sre.org.  File a bug with forensics.cert.org or whoever packaged it.

**Comment by rurban** [comment]
Ah thanks. I thought so after I bugged you here :)
