### ISSUE TITLE
Is it possible to use Python script to find the xref to the field of a structure

### ISSUE THREAD

**Issue by albertlab0** [NationalSecurityAgency/ghidra#1803]
Similar to the ask of 
https://github.com/NationalSecurityAgency/ghidra/issues/474

But I need to do it programatically, i.e. using scripts.

Thanks a lot

**Comment by saruman9** [comment]
I wrote the [script in Java](https://gitlab.com/saruman9/ghidra_scripts/-/blob/master/FindRefsField.java), I hope that you will not have difficulty in rewriting the script to Python.

**Comment by albertlab0** [comment]
Many thanks. Exaclty what I have been looking for.
