### ISSUE TITLE
Divide by zero bug in Pdb.exe

### ISSUE THREAD

**Issue by midshell-ghoul** [NationalSecurityAgency/ghidra#1804]
**Describe the bug**
Location of the bug:
&nbsp;&nbsp;&nbsp;&nbsp;Binary: pdb.exe
&nbsp;&nbsp;&nbsp;&nbsp;File: <path-to-ghidra>\Ghidra\Features\PDB\src\pdb\cpp\print.cpp
&nbsp;&nbsp;&nbsp;&nbsp;Function: printType()

Ghidra is failing to parse Rust PDBs, due to a divide-by-zero bug. This occurs in printType() when the tag is a SymTagArrayType, and lenElem and lenArray are both 0. Only lenElem is checked as equal to zero, but is blindly set to lenArray.

**To Reproduce**
This applies to any Rust application. You can have a simple or even completely empty main function. Compile the program, then load the exe and pdb into Ghidra for analysis, and analysis will fail with a SAXParseException. pdb.exe crashes during analysis, so the xml parsed by Ghidra is incomplete.

**Expected behavior**
Symbols from the pdb should load correctly.

**Screenshots**
The divide by zero crash in WinDbg, when running pdb.exe directly.
![divide by zero](https://user-images.githubusercontent.com/64363319/80309400-29cb3f80-8818-11ea-871a-1dfb30a87987.PNG)

Ghidra throws this error:
![SAXParseException during analysis](https://user-images.githubusercontent.com/64363319/80309608-7b27fe80-8819-11ea-9fe2-8eea1a6778eb.PNG)

An example rust program which causes the bug
![example rust program](https://user-images.githubusercontent.com/64363319/80309415-45364a80-8818-11ea-92aa-a011a2e4ae34.PNG)

**Attachments**
[ghidra_rust_pdb_bug.zip](https://github.com/NationalSecurityAgency/ghidra/files/4536768/ghidra_rust_pdb_bug.zip)

**Environment (please complete the following information):**
 - OS: Windows 10 (version 1909)
 - Java Version: AdoptOpenJDK 11.0.7
 - Ghidra Version: 9.1.2
 - rustc and cargo Versions: 1.42.0

**Comment by astrelsky** [comment]
May you please attach that example program and pdb. This way it can be reproduced without installing rust on windows.

**Comment by midshell-ghoul** [comment]
No worries, I have added a zip to the Attachments section with the compiled program and its pdb file.

**Comment by toshipiazza** [comment]
Seems like pdb.exe is dying processing `alloc::collections::btree::node::LeafNode<(), ()>`. The empty tuple is a zero-sized type so I guess `lenArray == lenElem == 0` is expected.

**Comment by ghidra1** [comment]
I believe these may correspond to flex arrays.  See comments in #1818 - more work is required.

**Comment by ghizard** [comment]
We believe this is fixed with: bb1b810
Please reopen if this is not the case.
