### ISSUE TITLE
Scripting API should use Collections rather than Lists

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1808]
It would be more convenient if the Scripting API used Collections rather than Lists in methods like askChoice().  I am finding that I frequently have Sets (usually as a result of getting a Map's keySet or valueSet) and it would save a little code to not have to convert them to Lists.

**Comment by gtackett** [comment]
I don’t know whether or not this would affect scripts in Jython. But please don’t leave them out when considering Ryan’s request.

**Comment by ryanmkurtz** [comment]
Closing...not needed anymore.
