### ISSUE TITLE
Ghidra and GitHub’s “discussions” beta

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#1813]
It would be great to have a place here on GitHub, as a part of this project, for informal discussions outside the issue-ticketing system.

GitHub has a feature for this in beta release right now. 

Is it usable yet, here in the Ghidra project?

**Comment by mumbel** [comment]
The description of discussions makes me think that is only a feature open to the organization team members, right?  I've never used it or seen it in use (also not part of any organizations)

just an observation though, even if it is actually open to anyone, I would be very surprised if the NSA/ghidra devs would want to moderate off-topic / non-issue / non-pull-request related discussions, and certainly wouldn't leave it un-moderated.  There seem to be plenty of other resources for informal discussion (discord/slack/telegram/matrix/reddit/etcc...)

**Comment by gtackett** [comment]
You could be right about that, as there are plenty of other places. I just thought one that was more integrated into the project might be nice, but I do see your point.

**Comment by astrelsky** [comment]
I think it would be nice for some things even if it wasn't completely open to the community. For example in a situation similar to the current one, a collaborator could put up approximately when development could be expected to be resumed.

ps I've been trying really hard not to ask.

**Comment by ryanmkurtz** [comment]
Is Gitter popular?

**Comment by mumbel** [comment]
@gtackett  dont know if you saw, but looks like I assumed incorrectly and they enabled it yesterday

**Comment by gtackett** [comment]
@mumbel Indeed! Perhaps someone will find helpful a link to the [introduction to Ghidra Discussions](https://github.com/NationalSecurityAgency/ghidra/discussions/2563).
