### ISSUE TITLE
ARM THUMB pop instruction formatting

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#1814]
**Describe the bug**

The `{` bracket in `pop` instruction is disappeared.

**To Reproduce**
Try to disassembly any binary for Arm Cortex-M processor

![image](https://user-images.githubusercontent.com/12969211/80418804-a164a180-88e0-11ea-8456-15853ae2d449.png)
![image](https://user-images.githubusercontent.com/12969211/80419137-3bc4e500-88e1-11ea-9a5f-5f704dc6deeb.png)

But here without `PC` it works OK:
![image](https://user-images.githubusercontent.com/12969211/80419045-0e783700-88e1-11ea-9f7e-a2bb1247a974.png)
![image](https://user-images.githubusercontent.com/12969211/80419230-6c0c8380-88e1-11ea-9118-c8d8f11235da.png)

I didnt figure out, what @GhidorahRex did in [this commit](https://github.com/NationalSecurityAgency/ghidra/commit/0ec0e703b311a5072532b9e8461e1e870aa3d86e), but it linked with this issue.

**Environment (please complete the following information):**
 - Ghidra Version: latest master

**Comment by emteere** [comment]
Minor issue, found and fixed.  Will push out soon.
The printing of the '{' was moved from a sub-sub-constructor, and one place didn't get updated.
ARMTHUMBinstructions.sinc:878
pclbrace:{ldlist^"," pc }	is ldlist & pc			{ build ldlist; pc = *mult_addr; mult_addr = mult_addr + 4; }

**Comment by emteere** [comment]
Thanks for finding this @esaulenka
