### ISSUE TITLE
TaskDialog missing progressbar

### ISSUE THREAD

**Issue by Learath2** [NationalSecurityAgency/ghidra#1819]
**Describe the bug**
TaskDialog seems to have a race condition, progressbar is randomly missing or there. Sleeping a while before calling `monitor.initialize()` seems to show the progress bar consistently. The progress bar also seems to show consistently on the first run of the script.

**To Reproduce**
1) Try `ProgressExampleScript.java` observe that it shows with the indeterminate progress animation.
2) Add a small `Thread.Sleep()` before `monitor.initialize(10)`. Observe that it shows the progress bar as intended.

**Expected behavior**
I expect the progress bar to show

**Screenshots**
<img width="665" alt="image" src="https://user-images.githubusercontent.com/490500/80592736-99177e00-8a28-11ea-93d4-19e74b198d69.png">
< The original script

**Environment (please complete the following information):**
 - OS: macOS 10.15.4
 - Java Version: 11.0.7 || 14.0.1
 - Ghidra Version: 9.1.2

**Comment by astrelsky** [comment]
I did a bit of debugging. I think the race condition is here but I don't know for sure. https://github.com/NationalSecurityAgency/ghidra/blob/7b76afee937f2309ac1f4ebf17ab91980a6d6874/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/script/GhidraScriptComponentProvider.java#L437-L444

**Comment by Learath2** [comment]
I debugged this issue but I'm not quite sure how to fix it. When initialize happens too early the delegate is not set to the dialog thus the `WrappingTaskMonitor` passes the initialize to the initial `BasicTaskMonitor` thus the initialize is invisable to the actual `TaskDialog`.

I'd guess some type of copying of state from the `BasicTaskMonitor` when setting the delegate could work but I'm not sure of the implications.
