### ISSUE TITLE
Can't start: Error: Uncaught Exception! IllegalAccessError - tried to access method docking.DialogComponentProvider$PopupHandler [...]

### ISSUE THREAD

**Issue by Falqun** [NationalSecurityAgency/ghidra#1821]
Ghidra does not start; There are no windows visible.
`/launch.sh fg ghidra 2G "" ghidra.GhidraRun` continuously spits out some `ERROR Error: Uncaught Exception!`.

Environment:
 - Ghidra: 9.1.2
 - OS: Arch Linux
 - Kernel: 5.6.7-arch1-1
 - Shell: zsh 5.8
 - WM: i3
 - JDK: java-11-openjdk

The complete output is:
```
java version "11-ea" 2018-09-18
Java(TM) SE Runtime Environment 18.9 (build 11-ea+7)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11-ea+7, mixed mode)
INFO  Using log config file: jar:file:/opt/ghidra/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/falqun/.ghidra/.ghidra_9.1_DEV/application.log (LoggingInitialization)  
INFO  Loading user preferences: /home/falqun/.ghidra/.ghidra_9.1_DEV/preferences (Preferences)  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ghidra.framework.GhidraApplicationConfiguration (file:/opt/ghidra/Ghidra/Features/Base/lib/Base.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of ghidra.framework.GhidraApplicationConfiguration
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR Error: Uncaught Exception! 
IllegalAccessError - tried to access method docking.DialogComponentProvider$PopupHandler.<init>(Ldocking/DialogComponentProvider;)V from class docking.DialogComponentProvider (SwingExceptionHandler) java.lang.IllegalAccessError: tried to access method docking.DialogComponentProvider$PopupHandler.<init>(Ldocking/DialogComponentProvider;)V from class docking.DialogComponentProvider
        at docking.DialogComponentProvider.<init>(DialogComponentProvider.java:89)
        at ghidra.framework.main.UserAgreementDialog.<init>(UserAgreementDialog.java:39)
        at ghidra.framework.GhidraApplicationConfiguration.lambda$showUserAgreement$0(GhidraApplicationConfiguration.java:95)
        at ghidra.util.Swing.lambda$runNow$2(Swing.java:230)
```
(After that `ERROR Error: Uncaught Exception!  ... ` repeats endless)

I've already tried:

*Using another WM (since it is apparently related to some swing/awt stuff), this did not make any difference (tried: Xfce)
* Switching the JDK: I've used `java-11-jdk`, `java-11-openjdk`, `java-8-openjdk`, `java-13-openjdk`; No difference here.
* Using an older version: 9.1.0 dies the same way as 9.1.2 does.
* Reading up on [#780](https://github.com/NationalSecurityAgency/ghidra/issues/780) and [#44 ](https://github.com/NationalSecurityAgency/ghidra/issues/44): setting `_JAVA_AWT_WM_NONREPARENTING=1` Did not do anything for me, as expected after I tested it in Xfce.

**Comment by ryanmkurtz** [comment]
What happens if you go into ~/.ghidra/.ghidra-<version>/preferences and set 

USER_AGREEMENT=ACCEPT

**Comment by Falqun** [comment]
The Folder `.ghidra/.ghidra_9.1.2_PUBLIC` for example exists but the file `preferences` does not. (only a whole bunch of `application.log-*` and `java_home.save`). Creating it with said value as its soul content does not help. Maybe a complete file would do the trick, but I couldn't fine one online. What should this file look like?

**Comment by ryanmkurtz** [comment]
I just made this fresh one:

```
#User Preferences
#Wed Apr 29 15:29:48 EDT 2020
USER_AGREEMENT=ACCEPT
SHOW_TIPS=false
ViewedProjects=
SHOW.HELP.NAVIGATION.AID=true
GhidraShowWhatsNew=false
RecentProjects=
TIP_INDEX=1
```

**Comment by Falqun** [comment]
Nope, this did not help. The behavior, sadly, is still the same.

**Comment by ryanmkurtz** [comment]
According to your application.log, Ghidra is being launched with an early access version of Java 11.  You could try launching with [something newer](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html).  I know you tried other ones, but you'll need to verify in application.log that they are actually being used. Ghidra has a Java discovery mechanism that might result in an unexpected one being used.

**Comment by Falqun** [comment]
That did the trick! I thought this would be taken care of by `pacman`, apparently not.
I now use the `jdk-openjdk` package, which yields version `13.0.2.u8-1`. Thanks for the help, kind stranger!

(if you read this and want to do the same: don't forget set the default version, e.g. `archlinux-java set java-13-openjdk`)

**Comment by ryanmkurtz** [comment]
Great, glad you got it worked out!
