### ISSUE TITLE
Ghidra Freezes On Running

### ISSUE THREAD

**Issue by TBeazley** [NationalSecurityAgency/ghidra#1822]
**Describe the bug**
Using Kali Linux, Ghidra was running fine, but when i have run again, it looks for a project ( says opening project) then it says searcing languages and doesnt do anything.
Is there a way of doing a hard reset?

**Environment (please complete the following information):**
 Using Ghidra 9.1.2

![image](https://user-images.githubusercontent.com/63407453/80617132-a2f5ad00-8a39-11ea-996c-64ce07750de3.png)

**Comment by ryanmkurtz** [comment]
You could try deleting your ~/.ghidra directory.

**Comment by TBeazley** [comment]
Will try that, what command?

**Comment by ryanmkurtz** [comment]
`mv ~/.ghidra junk`

**Comment by TBeazley** [comment]
Ryan, That has worked thank you

**Comment by ryanmkurtz** [comment]
Sure thing, you are safe to delete the `junk` directory now.

**Comment by emteere** [comment]
I would close the issue, but I'm curious why it got in this state.
The processor modules are getting loaded at this point.  It is possible that there was a hidden dialog waiting for input, possibly an upgrade a previously open program or other query, as I've never seen Ghidra hang here before.
If this is the likely culprit, then we can close the issue out.

**Comment by jmpalk** [comment]
For what it's worth, I had the same issue, also on Kali, also Ghidra 9.1.2. Deleting/moving the .ghidra directory also fixed it.
