### ISSUE TITLE
Decompiler low-level Error: PTRSUB off of non-pointer type

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1826]
**Describe the bug**
The decompiler process dies attempting to decompile __gxx_personality_v0.xml in an arm binary

**To Reproduce**
1. See attached decompilation debug xml

**Attachments**
[arm__gxx_personality_v0.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/4559003/arm__gxx_personality_v0.xml.txt)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18363.815]
 - Java Version: 14.0.1
 - Ghidra Version: 9.2

**Comment by caheckman** [comment]
reproducing

**Comment by caheckman** [comment]
Should be fixed in master.  Thank you for the report.

**Comment by astrelsky** [comment]
> Should be fixed in master. Thank you for the report.

No, thank you!
