### ISSUE TITLE
Filter out strings containing a space ?

### ISSUE THREAD

**Issue by SeleDreams** [NationalSecurityAgency/ghidra#1828]
Hello, I am trying to mod a game and noticed most of the game classes contain a function similar to typeof().name of C# so it allows me to see most of the game classes, however some other strings containing spaces are shown and I'd like to not see them. I am wondering if there are any ways to filter out strings with a space ?
I tried this but it doesn't accept a space as a valid input
![image](https://user-images.githubusercontent.com/16335601/80743064-a57d0300-8b1c-11ea-876c-fab1f5141b33.png)

**Comment by mumbel** [comment]
You can use regex for a work around: (these should be equivalent, just how you look at it)
`\S*`    would be only contains non-whitespace
`[^\s]*`  would be does not contain whitespace

**Comment by SeleDreams** [comment]
I didn't think about using regex, thanks !
