### ISSUE TITLE
The decompiler culls unused volatile reads

### ISSUE THREAD

**Issue by nicolasnoble** [NationalSecurityAgency/ghidra#1832]
### Bug description:
When a piece of code reads from a piece of volatile memory and not use the resulted read, the generated decompiled C code will ignore these reads.

### Reproducing:
Here's a very synthetic way to reproduce this:
- One volatile data segment
- One data segment with one pointer into the volatile data segment
- A piece of code that reads from the volatile memory indirectly through the pointer in the data segment, without actually using that data.

### Context:
Sometime in machine code, you want to reads data from a device and "throw away" such data, in order to reach the data you should care about. Here's an example of such code:

```C
uint32_t readSomeDataFromDevice(volatile uint32_t * device) {
    if (*device == SOMEMAGICVALUE) {
        *device; // skip 3 reads, keep the 4th's
        *device;
        *device;
        return *device;
    }
    return 0;
}
```

Due to the volatile nature of the pointer, the compiler will issue these 4 reads, and throw away the results: https://godbolt.org/z/F-L2dc

### Practical example:
![image](https://user-images.githubusercontent.com/7281574/80898731-b2842880-8cbb-11ea-949a-85b51500e77f.png)
The highlighted line in assembly is not present at all in the decompiled C code on the right. The assembly code loaded a pointer that contained the address of a volatile hardware register (`CDReg1`), and then promptly discards the first read from it by loading it into a dummy register.

I can give access to the remote ghidra repository if it helps looking into the issue.

### Analysis:
In general, reading from the volatile segment directly will issue synthetic volatile read calls in the decompiled C code, such as this decompiled code fragment:

![image](https://user-images.githubusercontent.com/7281574/80898809-bd8b8880-8cbc-11ea-8cbe-c09dfe231f65.png)

However, ghidra doesn't do this if the code doesn't actively use the results, and seems to be culling out the read from the decompiled C code.

### Potential solution:
Reads from a volatile section should be considered a full barrier function call, and not be culled away by the decompiler.

**Comment by caheckman** [comment]
Similar to #393 
I believe this was fixed in master with 875eed4 commit in master.
