### ISSUE TITLE
Retrieving external location from symbol address

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1833]
I'm looking to get the external location for the symbol located at an address. Here is a screenshot showing what is present at the address in ghidra.
![Capture](https://user-images.githubusercontent.com/46897303/80921512-db043500-8d44-11ea-9d4a-d52cca0558d3.PNG)

As can be seen the external symbol is properly defined and appears to be at this address. However the SymbolTable.getSymbols only gives one symbol at that address which is neither dynamic or external. It is in the global namespace and Symbol.getObject yields a FunctionDB instance. ExternalManager.getExternalLocation(symbol) for the symbol at the address yields no results as well. I can get it using ExternalManager.getExternalLocations(libraryName, label) however this requires the name of the containing library to be known in advance which it is not and cannot be retrieved.

Double clicking on the symbol brings me to the address in libstdc++.so.6 just fine so I don't understand why I cannot retrieve the external location programmatically.

It is also worth mentioning that the MemoryBlock containing the shown address is in fact `EXTERNAL`

**Comment by astrelsky** [comment]
I figured it out. I can use the primary symbol at the given address to get the symbol name and then use SymbolTable.getExternalSymbol to get the corresponding external symbol which may then be used with ExternalManager.getExternalLocation(Symbol)

**Comment by 6r0k3d** [comment]
![image](https://user-images.githubusercontent.com/42014669/153725691-68fee067-d7f7-4e31-a447-78a72428c66e.png)

This approach worked until it didn't...

The symbol is Ordinal_540, but somehow the Ghidra GUI knows its ACTUALLY Ordinal_307, but I can't figure out how to do that resolution programmatically. Any ideas?
