### ISSUE TITLE
Unable to demangle PE files with GCC mangling

### ISSUE THREAD

**Issue by midshell-ghoul** [NationalSecurityAgency/ghidra#1839]
**Describe the bug**
Ghidra is unable to demangle the function names in a PE file with GCC mangling. This affects Rust legacy mangling and mingw64 compiled windows binaries. This issue has sort of come up before in issues  #761 and #1051, however the fix (https://github.com/NationalSecurityAgency/ghidra/commit/5b283be163ce58209520039eb950da545813354a) seems to have just corrected the primary symbol, without a fix to the mangled names. 

Looking into Ghidra's demanglers the GnuDemangler supports GCC demangling, but not PE files, and the MicrosoftDemangler takes PE files, but doesn't do GCC demangling. If you take the same code, and compile it as an ELF file, then Ghidra can demangle the function names successfully.

I know it has been mentioned in the past that the Gnu demangler is looking to be replaced ( #1470), however this bug applies to the Microsoft demangler. Unless that is also being looked at?

I'm unsure of the correct solution to this problem. Is this a fix to include GCC support in MicrosoftDemangler? Should the GnuDemanger accept PE files? Would the new demangler mentioned earlier solve this?

**To Reproduce**
1. Compile a windows binary using either mingw64, or Rust (only applied to its legacy mangling scheme. V0 is a separate feature to add). These two use the GCC mangled function names.
2. Load into Ghidra for analysis

**Expected behavior**
Example mangled function name:  _ZN5breed8getColorB5cxx11Ev
Expected demangled function name:  breed::getColor

**Attachments**
[example_programs.zip](https://github.com/NationalSecurityAgency/ghidra/files/4579642/example_programs.zip)

**Environment (please complete the following information):**
-   OS: Windows 10 (version 1909)
-   Java Version: AdoptOpenJDK 11.0.7
-   Ghidra Version: 9.1.2
-   rustc and cargo Versions: 1.42.0
-   x86_64-w64-mingw32-g++ (GCC) 9.3-win32 20200324

**Comment by astrelsky** [comment]
Is the language set correctly? By default PE files are set to `*:*:*:default:windows` where the * are binary dependent. Setting it to `*:*:*:default:gcc` should fix this.

![Capture1](https://user-images.githubusercontent.com/46897303/81081264-b2547a80-8ebf-11ea-8225-b7a4d51e33d1.PNG)
![Capture2](https://user-images.githubusercontent.com/46897303/81081272-b41e3e00-8ebf-11ea-8397-b5698472f302.PNG)

**Comment by midshell-ghoul** [comment]
Hmm, changing the language works for the mingw binary, but not the Rust one. It is able to demangle the name, but associates the wrong primary symbol. 

For example, this Rust code:
`use std::io::stdin;`
`stdin();`

mangles the name to be:
_ZN3std2io5stdio5stdin17h2b8a8abe02b5129bE

and demangles to:
'h2b8a8abe02b5129b' in the namespace of std::io::stdio::stdin

It seems that the Rust legacy mangler ends with a hash suffix. Looking at their implementation (https://github.com/rust-lang/rust/blob/57e1da59cd0761330b4ea8d47b16340a78eeafa9/src/librustc_codegen_utils/symbol_names/legacy.rs#L134) it uses the form ("17h" + 16 byte hash + "E"). I don't know if this is part of the Itanium IA-64 C++ ABI, however this is is demangling correctly as an ELF, so Ghidra must have code to account for this in the GnuDemangler.

**Comment by astrelsky** [comment]
> Hmm, changing the language works for the mingw binary, but not the Rust one. It is able to demangle the name, but associates the wrong primary symbol.
> 
> For example, this Rust code:
> `use std::io::stdin;`
> `stdin();`
> 
> mangles the name to be:
> _ZN3std2io5stdio5stdin17h2b8a8abe02b5129bE
> 
> and Ghidra demangles to:
> 'h2b8a8abe02b5129b' in the namespace of std::io::stdio::stdin
> 
> It seems that the Rust legacy mangler ends with a hash suffix. Looking at their implementation (https://github.com/rust-lang/rust/blob/57e1da59cd0761330b4ea8d47b16340a78eeafa9/src/librustc_codegen_utils/symbol_names/legacy.rs#L134) it uses the form ("17h" + 16 byte hash + "E"). I don't know if this is part of the Itanium IA-64 C++ ABI, however this is is demangling correctly as an ELF, so Ghidra must have code to account for this in the GnuDemangler.

In ghidra 9.2 the ability to pass options to the demangle has been made available. You'll be able to pass `-s rust` to set the gnu demangler to demangle rust format

**Comment by midshell-ghoul** [comment]
Sweet! I will await 9.2 then.
