### ISSUE TITLE
No module named jintrospect

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#1842]
Not sure what triggers it, but after Ghidra has been running a while (treat as multiple day/week+) I come across this issue where when the python window tries to do the `Resetting python` pop-up an error occurs (that's when I notice the issue at least) and then from then on python scripts will fail as well as attempting to use the python window.

Closing the tool doesn't seem to fix, only a complete restart of Ghidra.

windows 10
ghidra 9.1.2
java 11.0.2
python 2.7.16

**Comment by ryanmkurtz** [comment]
Is there any chance your user temp directory is getting cleared?

**Comment by mumbel** [comment]
good thinking, I will check my `APPDATA\Local\Temp\mumbel-Ghidra\jython_cachedir\python-src` next time it happens (I restarted Ghidra as I was submitting this, so its all fresh ATM).  

I'd guess it would have to be mumbel-Ghidra related as I do have month old files in my Temp

**Comment by ryanmkurtz** [comment]
It's worth checking but since you are on Windows, I wouldn't expect it to be a problem.  I know macOS will just delete files right out from under you in its temp directory.

**Comment by mumbel** [comment]
I have also come across weirder issues with jython_cachedir not having the correct permissions maybe, like ghidra is unable to create the directory (so maybe its a mumbel-Ghidra permissions issue) which ultimately I manually delete mumbel-Ghidra, but I've only had that happen once and no clue what caused it or why I noticed it (in terms of ghidra messages)

**Comment by astrelsky** [comment]
I've also encountered this a few times. It was usually when I'd leave it ghidra and the python interpreter running and go to class. It seems to happen after being idle for long periods of time.

**Comment by ryanmkurtz** [comment]
I have it sitting all day today.

**Comment by mumbel** [comment]
@ryanmkurtz  its more on the order of weekly, probably bi-weekly.  I basically never exit ghidra or reboot that machine

**Comment by ryanmkurtz** [comment]
Ah ok.  I just went in and deleted the jython_cachedir from the temp directory and when I reset the interpreter I got a popup saying:

`"Resetting Python... - Uncaught Exception: ImportError: No module named jintrospect"`

Is that the exact error?

**Comment by mumbel** [comment]
Correct. (at Py.java:334)

**Comment by ryanmkurtz** [comment]
@jeff5, do you happen to know if Jython ever cleans out its cachedir?

**Comment by jeff5** [comment]
I don't think so, on its own initiative. It will create a new cache file for a JAR if it finds it can't read an existing one. (They number up, ISTR.)

We made a couple of changes in 2.7.2 to the cache, in location (cwd) and permissions (user only). This was in response to a CVE. You seem to be choosing your own location already, which was sensible. Hard to see why the permissions would be wrong if they work at all.

Obviously you can toast it when you need to if Jython is stopped. Deleting and remaking files when running always seems to be a problem on Windows. Files are open unexpectedly and can't be deleted. Sometimes it's the code. In other cases I resort to blaming the AV, meaning it's a mystery.

**Comment by ryanmkurtz** [comment]
Ok, thanks for the response!

**Comment by mumbel** [comment]
Okay, finally hit.  Sure enough my jython_cachedir (created 5/5/20) has 0 bytes, 0 Files, 0 Folders.

**Comment by ryanmkurtz** [comment]
Yes, about 2 weeks.  Are you willing to run procmon with a filter on that directory so we can see who's doing the delete?

**Comment by mumbel** [comment]
Yeah I think that should be okay

Think a filter w/ capturing path contains jython_cachedir is sufficient?

**Comment by ryanmkurtz** [comment]
I was just playing with it and if that is your only filter, you will get a ton of extra stuff.  To further reduce it you can add a 2nd filter that is `Operation is SetDispositionInformationFile`

**Comment by ryanmkurtz** [comment]
It does look like Jython at least has the capability to delete a cache file.  I'm not sure what triggers it though:

https://github.com/jythontools/jython/blob/b8d7aa4cee50c0c0fe2f4b235dd62922dd0f3f99/src/org/python/core/packagecache/CachedJarsPackageManager.java#L456-L472

    private Map<String, String> readCacheFile(JarXEntry entry, String jarcanon) {
        String cachefile = entry.cachefile;
        long mtime = entry.mtime;


        debug("reading cache of ''{0}''", jarcanon);


        DataInputStream istream = null;
        try {
            istream = inOpenCacheFile(cachefile);
            String old_jarcanon = istream.readUTF();
            long old_mtime = istream.readLong();
            if ((!old_jarcanon.equals(jarcanon)) || (old_mtime != mtime)) {
                comment("invalid cache file: {0} for new:{1}({3}), old:{2}({4})", cachefile, jarcanon,
                        old_jarcanon, mtime, old_mtime);
                deleteCacheFile(cachefile);
                return null;
            }
            ...

**Comment by ryanmkurtz** [comment]
You should be able to see that `comment()` message if you launch ghidra with `-Dpython.verbose=comment`

**Comment by mumbel** [comment]
so annoyed with myself right now, I had that running this whole time, but had some network issues last night and killed everything.  Completely forgot about this setup when I started stuff this morning

**Comment by ryanmkurtz** [comment]
Doh!

**Comment by aboood40091** [comment]
> Ah ok. I just went in and deleted the jython_cachedir from the temp directory and when I reset the interpreter I got a popup saying:
> 
> `"Resetting Python... - Uncaught Exception: ImportError: No module named jintrospect"`
> 
> Is that the exact error?
For me personally, I get `"Resetting Python Uncaught Exception: java.lang.NullPointerException"`.

**Comment by ryanmkurtz** [comment]
A new issue would be good, especially if you can provide the entire stack trace.

**Comment by mumbel** [comment]
came into a procmon exception on my login screen and the jython directory gone.  Yay! /s

**Comment by ryanmkurtz** [comment]
This ticket is cursed!  Maybe there is a procmon log file?

**Comment by ryanmkurtz** [comment]
Doesn't look like there is by default.

**Comment by astrelsky** [comment]
Instead of fighting this why not just move jython_cachedir to `Application.getUserSettingsDirectory()/"dev"` which is where the ghidra scripts go?

**Comment by mumbel** [comment]
If there is some piece of code in ghidra or libs that deletes this directory and its not just my system, what does moving the directory solve?

**Comment by astrelsky** [comment]
> If there is some piece of code in ghidra or libs that deletes this directory and its not just my system, what does moving the directory solve?

https://github.com/NationalSecurityAgency/ghidra/blob/bdbbca30a155502b79a38874c0186a7ac496dfeb/Ghidra/Framework/Generic/src/main/java/ghidra/framework/Application.java#L601-L615

On windows the user temp and user cache directories are the same. The documentation notes that the returned temp directory can removed by periodic system cleanup. So it's not the best place to be putting these to begin with.

Also, moving the directory would have the benefit of only having to wait a bit when starting the python interpreter for the first time used in ghidra as opposed to the first time every ghidra session.

**Comment by ryanmkurtz** [comment]
> On windows the user temp and user cache directories are the same. The documentation notes that the returned temp directory can removed by periodic system cleanup. So it's not the best place to be putting these to begin with.

That's backwards.  On Linux and Mac they are the same.  On Windows, they are 2 distinct locations.  We've seen Mac rip temp files right out from underneath you in the past, but I wasn't aware of Windows doing that unless you invoke a Disk Cleanup.  

Like @mumbel said, the concern is that if Jython is deleting the directory, moving it won't help.  If @mumbel wasn't willing to help with the debug, I would probably just move the jython cache directory to the cache dir (which would only do something different on Windows) and I would also have the interpreter's reset action check for the existence of the directory each time, in case it is Jython that is deleting it.  That may end up being what we do anyway, but it would be great to know who is actually deleting the files so we can understand the problem we are implementing the solution for.

**Comment by astrelsky** [comment]
@ryanmkurtz oh yes, my mistake, it appears I remembered incorrectly.

Why does the python interpreter use the user temp directory when ghidra scripts use `%USERPROFILE%\.ghidra\.ghidra_9.2_DEV\dev\ghidra_scripts\bin` for example? Just seems to be a bit inconsistent.

**Comment by ryanmkurtz** [comment]
Yes, that is inconsistent.  Adding too much stuff to the "settings" directory is bad for systems with roaming profiles.  We'll have to consider this as part of the final solution, once we have all the info.

**Comment by astrelsky** [comment]
Well, this just occurred after running ghidra for a few hours. I was actively using ghidra and then ran the decompiler parameter id and calling convention ids and then came back about 45 minutes later. Next time I tried to launch a python script I got the error. I had the debugger running So I have some warnings that might be helpful?

<details><summary>log</summary>

```
Jun 21, 2020 11:03:49 PM org.python.core.packagecache.SysPackageManager warning
WARNING: failed to write cache for 'C:\Users\astre\.gradle\caches\modules-2\files-2.1\org.python\jython-standalone\2.7.2\15592c29538abd36d15570eda9fa055ed1a618ba\jython-standalone-2.7.2.jar' (The system cannot find the path specified)
Jun 21, 2020 11:03:49 PM org.python.core.packagecache.SysPackageManager warning
WARNING: failed to write index file (The system cannot find the path specified)
Jun 21, 2020 11:03:51 PM org.python.core.packagecache.SysPackageManager warning
WARNING: failed to write cache for 'C:\Users\astre\.gradle\caches\modules-2\files-2.1\org.python\jython-standalone\2.7.2\15592c29538abd36d15570eda9fa055ed1a618ba\jython-standalone-2.7.2.jar' (The system cannot find the path specified)
Jun 21, 2020 11:03:51 PM org.python.core.packagecache.SysPackageManager warning
WARNING: failed to write index file (The system cannot find the path specified)
ERROR make_strings.py: Error running script: make_strings.py
org.python.core.PyException: ImportError: No module named jintrospect  (RunScriptTask.java:65)
org.python.core.PyException: ImportError: No module named jintrospect
	at org.python.core.Py.ImportError(Py.java:329) ~[jython-standalone-2.7.2.jar:2.7.2]
	at org.python.core.imp.import_first(imp.java:1200) ~[jython-standalone-2.7.2.jar:2.7.2]
	at org.python.core.imp.load(imp.java:1016) ~[jython-standalone-2.7.2.jar:2.7.2]
	at ghidra.python.GhidraPythonInterpreter.<init>(GhidraPythonInterpreter.java:120) ~[Python.jar:?]
	at ghidra.python.GhidraPythonInterpreter.get(GhidraPythonInterpreter.java:89) ~[Python.jar:?]
	at ghidra.python.PythonScript.runInNewEnvironment(PythonScript.java:110) ~[Python.jar:?]
	at ghidra.python.PythonScript.run(PythonScript.java:48) ~[Python.jar:?]
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365) ~[Base.jar:?]
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220) ~[Base.jar:?]
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198) ~[Base.jar:?]
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57) ~[Base.jar:?]
	at ghidra.util.task.Task.monitoredRun(Task.java:126) ~[Generic.jar:?]
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94) ~[Docking.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
ERROR Unexpected Exception: ImportError: No module named jintrospect  (ConsoleComponentProvider.java:332)
org.python.core.PyException: ImportError: No module named jintrospect
	at org.python.core.Py.ImportError(Py.java:329) ~[jython-standalone-2.7.2.jar:2.7.2]
	at org.python.core.imp.import_first(imp.java:1200) ~[jython-standalone-2.7.2.jar:2.7.2]
	at org.python.core.imp.load(imp.java:1016) ~[jython-standalone-2.7.2.jar:2.7.2]
	at ghidra.python.GhidraPythonInterpreter.<init>(GhidraPythonInterpreter.java:120) ~[Python.jar:?]
	at ghidra.python.GhidraPythonInterpreter.get(GhidraPythonInterpreter.java:89) ~[Python.jar:?]
	at ghidra.python.PythonScript.runInNewEnvironment(PythonScript.java:110) ~[Python.jar:?]
	at ghidra.python.PythonScript.run(PythonScript.java:48) ~[Python.jar:?]
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365) ~[Base.jar:?]
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220) ~[Base.jar:?]
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198) ~[Base.jar:?]
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57) ~[Base.jar:?]
	at ghidra.util.task.Task.monitoredRun(Task.java:126) ~[Generic.jar:?]
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94) ~[Docking.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
</details>

Don't worry about where it says the cache is as it's probably due to how I have things setup to debug with vscode.

**Comment by ryanmkurtz** [comment]
Ok thanks for helping to debug it.

**Comment by mumbel** [comment]
@ryanmkurtz   procmon finally hit and didn't die... but neither did the python interpreter.

yesterday morning, didnt look at procmon I guess till this morning, `cleanmgr.exe` did:
SetDispositionInformationFile on   `...\jython_cachedir\python-src` (result `NOT EMPTY`)
SetDispositionInformationFile on   `...\jython_cachedir\packages` (result `SUCCESS`)
SetDispositionInformationFile on   `...\jython_cachedir` (result `NOT EMPTY`)
and this morning another (just the 1)
SetDispositionInformationFile on   `...\jython_cachedir\python-src` (result `NOT EMPTY`)

**Comment by ryanmkurtz** [comment]
Ok.  It needs both `SetDispositionInformationFile` and `Delete: True` for it to represent a delete attempt.  I guess you had `Delete: False`?

**Comment by ryanmkurtz** [comment]
Do you have this task setup to run?

![image](https://user-images.githubusercontent.com/5378554/85771450-ee4ed380-b6e9-11ea-9df7-c261158f5541.png)

You can right click on it to manually run it, and see if it blows away your cachedir.

**Comment by ryanmkurtz** [comment]
I'm playing with it now...I let you know what I find.

**Comment by mumbel** [comment]
Yeah, that was the trigger, same single message.  Guess the first time yesterday did successfully remove packages/

Interpreter still works and opened another image in a new CodeBrowser (while keeping the other open) to force the refresh

**Comment by ryanmkurtz** [comment]
Is your VM low on diskspace?

**Comment by ryanmkurtz** [comment]
It looks like cleanmgr.exe also takes a file's Last Accessed time into account before deleting it.  

I think based on your procmon results we can assume that it's Windows cleaning it up and not Jython.  The right thing to do would be to get it out of the temp directory, which we always expected, but it's nice to understand what's going on.
