### ISSUE TITLE
How to auto import FIDBs

### ISSUE THREAD

**Issue by revolver-ocelot-saa** [NationalSecurityAgency/ghidra#1847]
Hello all,

If I download all of the FIDB files from [https://github.com/threatrack/ghidra-fidb-repo](https://github.com/threatrack/ghidra-fidb-repo) and place the FIDBs in my Ghidra/Features/FunctionID/data folder the FIDBs are not loaded into Ghidra.

If I open Tools -> Function Id -> Choose Active Fidbs the newly added fidbs do not show up.  I have to attach and add the fidbs one at a time to make them appear. Is there something I am missing here?

I checked out [https://github.com/NationalSecurityAgency/ghidra-data/blob/master/FunctionID/FID.md](https://github.com/NationalSecurityAgency/ghidra-data/blob/master/FunctionID/FID.md) and it seems to indicate that Ghidra will unpack the FIDBs on first use.  Does that mean we have to manually attach each FIDB?

Apologies if I missed something obvious.

**Comment by astrelsky** [comment]
Try adding the directory where the fidb files are located to ghidra's plugin path. If that doesn't work then the ones which are packaged with ghidra are loaded from $GHIDRA_HOME/Features/FunctionID/data

**Comment by revolver-ocelot-saa** [comment]
@astrelsky Thank you for responding! I currently have the FIDBs in the $GHIDRA_HOME/Features/FunctionID/data folder.  So that option does not seem to work.

I moved the FIDBs to a new directory and added that directory to the plugin path, unfortunately that did not work either.

I validated by checking if the FIDB appeared in Tools -> Function ID -> Choose Active Fidbs

**Comment by astrelsky** [comment]
> @astrelsky Thank you for responding! I currently have the FIDBs in the $GHIDRA_HOME/Features/FunctionID/data folder. So that option does not seem to work.
> 
> I moved the FIDBs to a new directory and added that directory to the plugin path, unfortunately that did not work either.
> 
> I validated by checking if the FIDB appeared in Tools -> Function ID -> Choose Active Fidbs

There didn't appear to be anyway to do this from the ui so I wrote a script to tackle this. I was able to import all 47 fidb files before I even knew there were 47 of them.

https://github.com/astrelsky/ghidra_scripts/blob/master/AttachFidsScript.java

**Comment by revolver-ocelot-saa** [comment]
@astrelsky Thank you for doing this, I'm sure it'll benefit plenty of folks in addition to myself.
