### ISSUE TITLE
Align bytes

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#185]
How can I align bytes without Condense Filler Bytes? I create arrays now, but it is wrong approach.

That's what I mean:

![2019-03-13_160708_137796123](https://user-images.githubusercontent.com/4244396/54281134-204a2e00-45aa-11e9-800d-3eb46f865aa7.png)

**Comment by emteere** [comment]
Create a selection, and apply the filler bytes data type.  The Alignment data type is similar to a string in that it can have a variable size.

You can also apply the Alignment data type with a size from within a script.
