### ISSUE TITLE
Need management tools for function ID libraries

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#1852]
**Is your feature request related to a problem? Please describe.**

The Function ID plugin provides virtually no tools for management of Function ID libraries.

[Please pardon any vagueness or incorrectness as to Function ID library concepts and terminology. I'm still pretty new to using the plugin.]

**Describe the solution you'd like**
At a minimum, I'd like to have these abilities for function ID libraries:

- Navigation of Function ID libraries
- Table of function names and module names in a library, including:
-- Optional table columns for short hash, long hash, function size in code units
-- A way to save the to a text file (typical Ghidra table cut/paste would work for me)
- Search for function names or module names
- Delete function names or module names from a library

**Describe alternatives you've considered**
- Ghidra script(s) might be written that could provide much or all of the desired functionality. Perhaps this could be an interim solution until the next alternative could be implemented. Probably few in the user community (outside NSA, at least) have the requisite internal knowledge of the plugin.
- Integrating the desired functionality into the plugin itself might be a better long-term solution, so that the code is "all in one place" and easier (if not actually easy) to understand and maintain.

**Comment by astrelsky** [comment]
In the tool browser goto `File->Configure...->Experimental` and check the FidDebugPlugin. Close and reopen the code browser. There will now be a 'Table Viewer' option under `Tools->Function Id`

**Comment by gtackett** [comment]
Thanks, Andrew, this is helpful for now.

In the long run, though, ability to display and edit such information should perhaps be part of the Fid plugin itself?
