### ISSUE TITLE
Build cspec documentation for Decompiler

### ISSUE THREAD

**Issue by rchildre3** [NationalSecurityAgency/ghidra#1856]
**Describe the bug**
`cspec` documentation files exist in `Ghidra/Features/Decompiler/src/main/doc/` yet are not built alongside its siblings in the `build.gradle` script for the Decompiler

**Expected behavior**
The docs are built. Looks like they may have just been left out of the `buildDecompilerDocumentationPdfs` and `buildDecompilerDocumentationHtml` tasks

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 11.0.7
 - Ghidra Version: 9.1.2

**Additional context**
#472

**Comment by bevanweiss** [comment]
Any chance the pspec docs could be added also? (or am I being dense and they are there already?)

**Comment by starfleetcadet75** [comment]
Unfortunately there are no pspec docs in `Ghidra/Features/Decompiler/src/main/doc/` in the first place. The cspec ones were already there, they just weren't being compiled.

There is the Relax spec at `Ghidra/Framework/SoftwareModeling/data/languages/processor_spec.rxg` for reference, but it doesn't describe the fields.

**Comment by bevanweiss** [comment]
So the way to get the documentation would be to reverse engineer the Java sourcecode behind the main Ghidra program? :(

**Comment by rchildre3** [comment]
> So the way to get the documentation would be to reverse engineer the Java sourcecode behind the main Ghidra program? :(

I wouldn't say reverse engineer, more so just reading the source code (looks like it is in `C++`: `Ghidra/Features/Decompiler/src/decompile/cpp/architecture.cc`).  It is unfortunate that there aren't docs, but with the spec @starfleetcadet75 pointed out and the various `*.pspec` files in the source code, You should be able to get a decent overview of what goes in the file.

**Comment by SamB** [comment]
@rchildre3 did you close this by mistake? The original proposal was just to include the cspec docs along with the other decompiler stuff, and I have a PR that does only slightly more than that -- the only extra things I remember doing were remove hardcoded distro-specific paths to the docbook XSLT stylesheets, and add a missing trailing slash to a path somewhere.
