### ISSUE TITLE
How to add a new code browser listing field?

### ISSUE THREAD

**Issue by aguerriero1998** [NationalSecurityAgency/ghidra#1857]
I am trying to add a new field to the code browser plugin similar to NeatMonster's in issue #315. I was wondering what the best way to do this is. It seems that I would need to implement a new FieldFactory and then maybe use an analyzer to populate it? I've been looking for similar examples but I can't seem to find anything that is similar. Could I get some pointers to either examples or how I could do this?

Thanks.

**Comment by ryanmkurtz** [comment]
I've never written a FieldFactory, but there are many existing examples you could look at:

<img width="208" alt="Capture" src="https://user-images.githubusercontent.com/5378554/81837917-764e9480-9513-11ea-81b0-c6947eb8834d.PNG">
