### ISSUE TITLE
Question about SLEIGH when designing a language based on a variable register piece

### ISSUE THREAD

**Issue by aldelaro5** [NationalSecurityAgency/ghidra#186]
I am trying to implement a PowerPC language variant for the Gekko and Broadway CPU used in the Nintendo GameCube and Nintendo Wii respectively. The current state of the language can be found here (Only implemented the required parts for the disassembly): https://github.com/aldelaro5/ghidra-gekko-broadway-lang I am now trying to implement the semantic, but got into a blocking issue that I would like to know possible ways to resolve. 

At the end of the slaspec file, there's instructions exclusive to both CPU called paired singles instructions. These are instructions that allows to operate on 2 floats at once, but the load and store instructions supports quantization with 4 possible integers types (signed and unsigned 8 and 16 bits). To select the type, the index of a register called a GQR must be provided in the I operand. The GQR contains the settings of the load and store type for quantization as well as a scaling factor to apply when performing the quantization.

The problem I have is these settings are present within specific bits of the desired GQR. When trying to implement the semantic with SLEIGH, I can easily get the GQR by attaching I to them, but I couldn't find any way to have different constructors or sub constructors that would give a different semantic based on the bit range of the type setting of the GQR. The semantic has to be different because the size and signed/unsigned varies between the types as well as having the possibilities to skip the quantization entirely so I need multiple constructors, but I cannot put the appropriate restriction on the GQR attached by I.

My question: does the semantic of such a language possible to implement with the current SLEIGH language? If yes, how? if no, what can be done for this to become possible?

**Comment by emteere** [comment]
Are the values of the bits in the GQR registers known only at run-time?
If so, you cannot match on the bits during the sleigh parse.

I'm sure it is implementable.  If the values are known only at run-time, then you would need to implement conditional semantics with if () goto <internal label>;  logic.
An example of the construct would be in the x86 sgx.sinc file.

There may be other ways depending on the exact details.

**Comment by aldelaro5** [comment]
it's funny you mention this because I only realised you could define labels in the semantics a few hours ago and I was about to try this as this seems to be exactly what I want.

Yes, they are known at runtime, but this isn't an issue because the targets usually sets them and never touch them again so the user can simply set the register values globally and the decompiler should take as these values. I expected that it would have been done this way, but I can at least tell where the settings comes from.

I'll try to implement with if goto logics and if that seems to work, I'll close the issue.

**Comment by xyzz** [comment]
Maybe you could make GQR a context register, then you would be able to match the instructions based on its value. Though there are so many possible combinations it'd probably result in a huge slaspec file.

**Comment by aldelaro5** [comment]
Ok the if logic does work, so I will close this. I might end up defining it as a pcode op because it's complex enough that it can look very ugly in the decompiler, but anyway, it's definitely possible which answered my question, thanks for the help!
