### ISSUE TITLE
Archiving a large project fails with FileNotFoundException

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#1860]
**Describe the bug**
I attempted to archive a fairly large project, probably a few thousand programs with a **.rep** folder about 50 GB.

After running for ten minutes or so, there was a FileNotFoundException.

Notice that after that exception, the archival appeared to continue for another 9 minutes or so before the "INFO" message saying that it had failed.

![Capto_Capture 2020-05-13_01-17-13_PM](https://user-images.githubusercontent.com/52077/81843812-27592d00-951c-11ea-873e-eea8ca2b278a.png)

**To Reproduce**
I am attempting to reproduce the problem, but it takes 20 minutes or so to try.

Clearly, I can't send you a project archive in this case. :-)

If all else fails, I'll create a zip archive and attach it.

Unless the archive exceeds some github size limit.

**Environment (please complete the following information):**
 - OS: macOS 10.13.6
 - Java Version: 12.0
 - Ghidra Version: 9.2 dev

**Comment by gtackett** [comment]
After closing and reopening the project I was able to archive it successfully. <Insert "puzzled" emoji here.>

**Comment by dev747368** [comment]
My guess would be that the file disappeared between being found when the directory was scanned and when it was attempted to be read to add to the archive zip.  The ~journal.dat does get moved to ~journal.bak by some unknown to me mechanism, so I'm guessing it was just a timing issue that exposed this problem.
