### ISSUE TITLE
bug in Mask.complementMask()

### ISSUE THREAD

**Issue by ChuckFoo** [NationalSecurityAgency/ghidra#187]
**Describe the bug**
MaskImpl.complementMask() ORs the resulting bytes into the output byte array instead of simply overwriting the bytes with the input data ANDed with the complement of the Mask.

I discovered this trying to use the same byte array as source and destination (applying the complemented Mask in place) and seeing the wrong results.  So I looked at the source code for complementMask and saw it doing "results[i] |= b" where it should be "results[i]=b" instead.

I can work around it by creating a new byte array for the result (created 0 initialized) and replacing the source array reference with that array like so:

    byte [] output = new byte[input.length];
    input = mask.complementMask(input,output);

but it'd be nice to not have to do that.

**To Reproduce**
Use the complementMask API on some bytes as both the input and the output, see it not work.

**Expected behavior**
For the actual complement of the Mask to be applied to the bytes correctly without the ORing with the existing contents of the output buffer behavior.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 18.04)
 - Java Version: OpenJDK 11.0.2
 - Ghidra Version: 9.0

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
This will be fixed in our next release.
