### ISSUE TITLE
Ghidra cannot load the x86 16bit binary with big segment offset

### ISSUE THREAD

**Issue by NyaMisty** [NationalSecurityAgency/ghidra#1876]
**Describe the bug**
Some executables have a code segment at 0xffe, and in Ghidra's MzLoader.java, it's using 
```space.getAddress(Conv.shortToInt(dos.e_cs()) + csStart, 0);``` to calculate the segment value.
The Conv.shortToInt will zero padding the higher 16 bit, resulting an unsigned short. 
However the dos.e_cs() can be negative, and this is causing problem.
Several places in MzLoader.java also have this problem :)

**Attachments**
This example is from DEFCON Quals 2020
[BBS.zip](https://github.com/NationalSecurityAgency/ghidra/files/4645480/BBS.zip)

**Environment (please complete the following information):**
 - Ghidra Version: 9.1 & Master branch manually built version

**Comment by lkempf** [comment]
I also encountered this problem and have mostly fixed it in my fork. I'm still working on a bug where the wrong address space is used by the decompiler view and then I'll create a pull request for this.
