### ISSUE TITLE
Accessing External Function Address Space

### ISSUE THREAD

**Issue by ghidrarocks** [NationalSecurityAgency/ghidra#1882]
Hello,

I would like to know if it's possible, and what's the best practice, regarding accessing a "Thunked-Function" which points to an EXTERNAL library. I'd like to be able to decompile that function and retrieve the associated High Function.

Looking around seems there are many similar issues/questions regarding retrieving information from external locations - #1236, #1833, #578... 

I guess a way to accomplish this could be creating a "program" from every external location and working with them, but this seems very inefficient. Would be possible to get the specific thunked function address space and load it in a new memory block, making it available from the currentProgram?

Thanks.

**Comment by 6r0k3d** [comment]
I finally figured out how to do this, trick was seeing the "Go to External Location" prompt when you right click the name in the Symbol Tree. Pulled the code for that and implemented it in Python:

```
from ghidra.app.util import SymbolPath
from ghidra.app.util import NamespaceUtils

# Have to sub in your own address
# The address should be the address of the Thunk
externalLocation = getFunctionAt(toAddr("004341fe")).getThunkedFunction(True).getExternalLocation()
externalSymbol = externalLocation.getSymbol()
program = externalSymbol.getProgram()

# Need to open the external program
# Adapted from https://github.com/saruman9/ghidra_scripts/blob/master/FindExternalReferences.java
libPath = currentProgram.getExternalManager().getExternalLibrary(externalLocation.getLibraryName()).getAssociatedProgramPath()
projectData = state.getProject().getProjectData()
libFile = projectData.getFile(libPath)
externalProgram = libFile.getImmutableDomainObject(libFile, DomainFile.DEFAULT_VERSION, monitor)


# [Adapted from GoToHelper](https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/gotoquery/GoToHelper.java)
label = externalLocation.getOriginalImportedName()
symbolPath = SymbolPath(label)

for x in NamespaceUtils.getSymbols(symbolPath, externalProgram):
    print(x)
    if x.isExternalEntryPoint():
        sym = x

loc = sym.getProgramLocation()
print(loc.getAddress())
fn = prog.getFunctionManager().getFunctionAt(loc.getAddress())
```

**Comment by Victor725** [comment]
fsd
