### ISSUE TITLE
___chkstk_ms not recognized automatically

### ISSUE THREAD

**Issue by heinrich5991** [NationalSecurityAgency/ghidra#1888]
**Describe the bug**
The x86-64 processor cspec is missing a callfixup for `___chkstk_ms`. It behaves the same way as `__chkstk` and friends.

**To Reproduce**
1. Get the sample binary: [sample.zip](https://github.com/NationalSecurityAgency/ghidra/files/4659655/sample.zip)
2. Go to the function at 0x004c5910.
3. Check the decompiler output.
4. See that the function's local variables are messed up. The decompiler even created a variable for the stack pointer.

**Expected behavior**
In the decompiler output, the stack assignments should be omitted.

**Environment (please complete the following information):**
 - OS: Arch Linux (up to date on 2020-05-21)
 - Java Version: jre11-openjdk 11.0.6.u10-1
 - Ghidra Version: ghidra 9.1.2-1 from the Arch Linux repos.

**Comment by bravosierra99** [comment]
upvoted
