### ISSUE TITLE
x86-32: Decompiled functions return prematurely

### ISSUE THREAD

**Issue by ThePBone** [NationalSecurityAgency/ghidra#1896]
**Describe the bug**
I am trying to inspect a shared library (language id: `x86:LE:32:default`). I noticed that several functions (quite a lot of them) seem to instantly call the same non-returning subroutine (see screenshot; red marker) and then return to the parent function without executing the rest of the instructions beneath it (see screenshot; green marker). This marked section below had to be manually disassembled, it was not detected by Ghidra as code.

**To Reproduce**
1. Import program from attachment (use `x86:LE:32:default` language ID)
2. Run the auto-analyser (default settings)
3. Goto one of the affected functions (for example at: 0x0005ff30, 0x0005ee40 or 0x00014fa0)

**Expected behavior**
I have an ARM version of the same library, which did not show this issue at all. The affected functions in the ARM version are lacking the CALL instruction at the beginning of the function (which is good) and their code was completely found and analyzed.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/38386967/82736503-8c85fd00-9d2a-11ea-8853-4b9ccfbb57d2.jpg)

**Attachments**
[Decompiler XML debug file](https://github.com/NationalSecurityAgency/ghidra/files/4672205/function_0005fea0.zip)
[Raw binary](https://github.com/NationalSecurityAgency/ghidra/files/4672210/libWavUtils.zip)

**Environment:**
 - OS: Windows 10 (Version 2004, Build 19041)
 - Java Version: 11.0.6
 - Ghidra Version: 9.1.2 (Feb-12)

**Additional context**
By default, Ghidra overrode the flow with `CALL_RETURN`. Changing or removing this flow override did not make a difference.
The aggressive instruction finder was actually able to recognize some of the missing function bodies, but they were treated as separate undefined functions since they were detached from the head of the actual function.
Patching the false 'CALL' instruction with NOP helped to restore the program flow, but I don't think this is the right way to solve this issue.

I had the same issue with other x86-32 shared libraries.

**Comment by wanchouchou** [comment]
It's not a bug but a not smart behavior :D). You can fix the control flow following the steps as below:
1. Right click on the instruction `call FUN_0001409b`, and click the **Edit Function** item;
2. In the Function Attributes panel, uncheck the **No Return** box, then click the **Ok** button.
3. Right click on the instruction `call FUN_0001409b` again, and click the **Clear Flow and Repair...** item, then the instructions below it will be removed; 
4. Press **D** on the address of `call FUN_0001409b`, the new control flow will be re-paired;
5. Have fun.

**Comment by ThePBone** [comment]
Thanks, that helped. I did the code flow repair before but it seems I forgot to press D.
