### ISSUE TITLE
Importing executable files with auto-detected format exports corrupted binaries

### ISSUE THREAD

**Issue by rszibele** [NationalSecurityAgency/ghidra#19]
**Describe the bug**
If you import an ELF binary with the format as `Executable and Linking Format (ELF)` and then export that binary, it creates a corrupted binary that segfaults.

However, if you import it as "Raw binary" and manually select the language, then the exported file works as expected.

**To Reproduce**
1. Import the `cp` ELF binary into your project (default settings).
2. Right-Click it and click `Export...`
3. Select `Binary` as the format.
4. Export it.
5. Make the exported binary executable.
6. Run the exported binary.

**Expected behavior**
The exported binary should work instead of segfaulting (happens with multiple binaries that I've tested).

**Screenshots**
Default:
![image](https://user-images.githubusercontent.com/1387224/53855568-116de500-3fc6-11e9-848a-c94767ce77c3.png)
Import as Raw binary:
![image](https://user-images.githubusercontent.com/1387224/53855596-29ddff80-3fc6-11e9-87f6-ff2a3e9311be.png)

**Environment (please complete the following information):**
 - OS: Kubuntu 18.10
 - Ghira Version 9.0

**Additional context**
Happens with both i386 and x86_64 binaries.

**Comment by rszibele** [comment]
Just tested it on Windows and it's the same story with PE executables. They also need to be imported raw, else you can't run them.
![image](https://user-images.githubusercontent.com/1387224/53898405-e3bd8600-402f-11e9-9388-b4ad3e4b43b8.png)

**Comment by Ristovski** [comment]
Can confirm. The exported `ls` becomes ~3kb larger than the original. 
Some binaries also end up with missing headers.

**Comment by Ristovski** [comment]
Note: Loading as `Raw Binary` does not seem to produce the same analysis/disassembly output at all.

The disassembly after analysis is missing various things ranging from functions not being disassembled to missing Xrefs.

It also appears to analyze the binary much faster than when imported as `ELF` indicating it is either unable to analyze is as thoroughly when loaded as a `Raw Binary` or just skips a bunch of analysis options which are enabled/supported only under `ELF`.

Thus, loading as `Raw Binary` should not be considered a workaround for this as the output differs.

**Comment by gnooby22** [comment]
The binary export is not intended to create a valid executable.  It simply dumps the memory blocks that exist within Ghidra void of any address placement information.

**Comment by Ristovski** [comment]
@gnooby22 Would be nice if there was a way to imitate the behavior when loading a binary as `Raw Binary` (which when exported creates a valid verbatim copy of the loaded program) but retaining all the analysis options when loading it as `ELF`.

One would expect that `Export Program` as `Binary` would create a valid executable when loaded as `ELF` as well.

This means that executables as of now can't be nicely patched like in IDA.

**Comment by bratao** [comment]
Yeah,
Working exported binaries is a very important feature for many workflows.

**Comment by Corallo** [comment]
Once I imported as Raw Binary what can I do to produce the same binary analysis of an ELF? At least to automatically show assembly code.

**Comment by Ristovski** [comment]
@Corallo It currently sadly does not seem to be possible

**Comment by johnalanwoods** [comment]
Also have this issue.

When I make patches to apps, I can't export a binary without seg fault, nor does it make the change to the underlying binary referenced by the project.

**Comment by looterz** [comment]
Same issue here with every binary I have tested.

**Comment by johnalanwoods** [comment]
Does 9.0.1 fix this?

**Comment by najamelan** [comment]
@johnalanwoods Don't worry, it won't be long. Imagine all these poor agents at the NSA who can't work because their hacking toy is broken. They won't let this linger long. LOL

**Comment by Ristovski** [comment]
@najamelan it does not appear to be a bug

One of the devs (whose account is now deleted) mentioned this:

> The binary export is not intended to create a valid executable - there is no export for doing this. It simply dumps the memory blocks that exist within Ghidra void of any address placement information.

I doubt this will be "fixed"

**Comment by johnalanwoods** [comment]
@Ristovski interesting. To me this would seem like a basic feature. The ability to edit the binary and run that binary independently of Ghidra. I’m shocked this is seen as normal behaviour. Even IDA does this.

**Comment by Ristovski** [comment]
@johnalanwoods I agree. I don't see why the binaries loaded as ELF should not export the same way they do when loaded as Raw Binary. I haven't looked into the bundled source code yet, but _maybe_ this could be trivial to fix.

**Comment by ryanmkurtz** [comment]
A few things to add:

- This was not addressed in 9.0.1.  The effort is most likely too large to appear in a patch release.  
- I'm changing this from a bug to an enhancement because while the feature isn't working as requested, it's working as documented (see help page for exporting files).  
- #154 is related, because the file offset to memory address mapping is lost during import.  Keeping track of that mapping would be required to properly go back to file-form.

**Comment by johnalanwoods** [comment]
Thank you for the clarification @ryanmkurtz.

It seems unusual to me that, as sophisticated as Ghidra is, it doesn't include this feature.

How much utility can there be without being able to generate an edited executable?

Anyway, not to worry.

Regards,
John

**Comment by valentinbreiz** [comment]
Same problem.

**Comment by bernky** [comment]
So what are people supposed to do without the ability to export a working binary for windows? Re-write the program or?

**Comment by johnalanwoods** [comment]
I agree with @bernky, there are things which can be done without export. Such as exfiltration of data and there is python scripting etc, but still the ability to export is very important.

**Comment by ertosns** [comment]
alright then, i can't finish my root-me assignments using ghidra, what i should do without export, use other tools, what is the point, this is high priority bug.

**Comment by Jest25** [comment]
Great find, almost lost my mind trying to figure it out.

**Comment by bernky** [comment]
> alright then, i can't finish my root-me assignments using ghidra, what i should do without export, use other tools, what is the point, this is high priority bug.

I think they are considering this as an "Enhancement feature"

**Comment by johnalanwoods** [comment]
I just went back to IDA, at least I can export from it easily and I don’t have to run it inside 4 nested VMs to avoid myself being backdoored ;)

**Comment by benjaminkoffel** [comment]
As others have said export works fine when you import as `Raw Binary`.

**Comment by johnalanwoods** [comment]
> As others have said export works fine when you import as Raw Binary.

Raw badly affects the quality of the disassembly. It makes it really hard to work in.

**Comment by johnalanwoods** [comment]
Does 9.0.4 fix this?

**Comment by ryanmkurtz** [comment]
No, 9.0.4 is mostly a bug fix release.

**Comment by tomruk** [comment]
The problem still persists, are you gonna solve it?

**Comment by ryanmkurtz** [comment]
Ghidra 9.1 will add the ability to retain and access the original imported program bytes.  This was a key requirement for this type of exporter to be written properly.  However, Ghidra 9.1 will not introduce any new exporters.  Writing an exporter to take a loaded memory image back to a runnable binary is a pretty sizeable task (to do it correctly and completely), and it is specific to each loader (there is no generic solution).  However, now that the infrastructure is in place, you might start seeing the community take a stab at it for the more popular file formats (PE, ELF).

**Comment by brandonros** [comment]
Will it be possible to put a header on top of a raw binary file? Use case:

`$ qemu-system-tricore -M tricore_testboard -kernel firmware.bin`

firmware.bin won't work, but if you slap an ELF header on the raw instructions, they will parse.

**Comment by schlafwandler** [comment]
I have written a python script to write back small patches to a copy of the original PE/ELF binary:
https://github.com/schlafwandler/ghidra_SavePatch

It's still experimental and far away from a complete export feature; but if you are only dealing with few and small modified locations it might be a good enough workaround.

**Comment by ghidra1** [comment]
Note that the Binary export is not broken, it is simply misunderstood.  This exporter simply dumps the initialized memory blocks defined within Ghidra in binary form.  The blocks are appended sequentially.  It was never intended to recreate a loadable/executable binary.  While this is certainly a desirable feature, it does not yet exist within Ghidra.

The binary exporter can provide a means of exporting a selected memory region as binary such that it can be subsequently added to another Ghidra program.  This can be useful if a specific section needs to be unpacked and loaded to a specific memory address within Ghidra.

**Comment by johnalanwoods** [comment]
@ghidra1 understood thanks. 

However this means Ghidra can’t be used to patch a binary. Which is the primary reason I use IDA. 

Otherwise the use is restricted to inspecting methods and watching output.

**Comment by ghidra1** [comment]
The request is a reasonable improvement, although as an analysis tool re-writing binaries has not been a high priority.

I am closing this ticket and deferring the issue to #1505 as an enhancement/improvement.

**Comment by SmallJoker** [comment]
Does this issue cover the following bug as well? (see first instruction after LAB_*)
I made changes to a PE64 dll, but did not save the project for try&error patching. However, the unsaved changes are still exported after they were reverted in Ghidra.

![grafik](https://user-images.githubusercontent.com/1497498/97784362-4d43be00-1b9e-11eb-9c94-c95c56ceccbb.png)

**Comment by ryanmkurtz** [comment]
#1505 was merged in, so there are now PE and ELF exporters that behave how you thought the Binary exporter should have behaved.  No changes were made to the Binary exporter...that one still just dumps the memory image to a file as-is. The PE and ELF exporters can be used to save basic byte modifications back to a new runnable PE/ELF file.  

Here is the help for the PE exporter:

![image](https://user-images.githubusercontent.com/5378554/112303648-eae57a00-8c72-11eb-8fe0-211a7213459c.png)
