### ISSUE TITLE
shouldAskToAnalyze is broken

### ISSUE THREAD

**Issue by edmcman** [NationalSecurityAgency/ghidra#1920]
**Describe the bug**
I am using [shouldAskToAnalyze](https://ghidra.re/ghidra_docs/api/ghidra/program/util/GhidraProgramUtilities.html#shouldAskToAnalyze(ghidra.program.model.listing.Program)) to determine if analysis has been run.  This code always returns false for me because my projects were created after `ANALYSIS_START_DATE` in 2007.  My only guess is that the following code was meant to check that projects were created AFTER 2007, and if so to then check the analysis flag.  If so, changing `< 0` to `> 0` should fix the problem.

``` java
       public static boolean shouldAskToAnalyze(Program program) {
                try {
                        SimpleDateFormat format = new SimpleDateFormat(Program.ANALYSIS_START_DATE_FORMAT);
                        Date analysisStartDate = format.parse(Program.ANALYSIS_START_DATE);
                        Date creationDate = program.getCreationDate();
                        if (creationDate.compareTo(analysisStartDate) < 0) {
                                return false;
                        }
        }
```

**To Reproduce**
I can provide a script if desired, but this seems like a straight-forward error.

**Expected behavior**
`shouldAskToAnalyze` behavior matches the documentation.

**Comment by astrelsky** [comment]
@edmcman the comparison shown there returns a value of less than 0 if the creation date was prior to the analysisStartDate. I double checked this with a fresh project and that is functioning correctly.

However the description of the method is a bit confusing. I have linked a pull request to this which fixes the description.

Also, this method is what is used to control the pop up dialog that states "${program name} has not been analyzed. Would you like to analyze it now?" when you first import and open a program in the code browser.

**Comment by edmcman** [comment]
Let me look again to make sure I'm not being crazy, but I believe the function always returns `false` when I call it.  In other words, I don't believe this is (just) a documentation issue.

**Comment by edmcman** [comment]
Sorry, you are right.  It's not a problem with the Date comparison.  But my program contains `Program.ANALYZED` even if I say no to the auto analysis prompt.

**Comment by edmcman** [comment]
Oh.  Apparently I figured out this issue a while back and forgot about it.  Here's the check I'm using in my code that works:

``` java
      if (!currentProgram.getOptions(Program.PROGRAM_INFO).getBoolean(Program.ANALYZED, false)) {
        Msg.showError(this, null, "Error", "Please run auto analysis before using the OOAnalyzer Ghidra Plugin");
        return;
      }
```

The code in `shouldAskToAnalyze` checks for the existence of the `Program.ANALYZED` flag but does not examine the value.  If this is the desired behavior, I think the docs need to be updated again.

**Comment by edmcman** [comment]
This is only tangentially related in the sense that it is related to the `ANALYZED` flag, but I was also surprised that `GhidraProject::analyze` did not set the `ANALYZED` flag on the program it analyzed.

**Comment by astrelsky** [comment]
In my opinion I would find it bothersome to be constantly asked if I want to analyze the program upon reopening if I have already said no. However, I think there should be a method to get the value of the flag specifically for this use case.

**Comment by edmcman** [comment]
`Program::isAnalyzed` would be nice.  But honestly, part of the reason I got so confused was because of the misleading documentation of `shouldAskToAnalyze`, so clearing that up too would be a big help.
