### ISSUE TITLE
Ghidra cannot find jdk

### ISSUE THREAD

**Issue by xmhwws** [NationalSecurityAgency/ghidra#1923]
jdk：OpenJDK11U-jdk_x64_windows_hotspot_11.0.7_10
![image](https://user-images.githubusercontent.com/42903751/83477818-cabbb300-a4c6-11ea-8eb8-d62a202f0fe2.png)

run `ghidra-Ghidra_9.1.2_build\Ghidra\RuntimeScripts\Windows\ghidraRun.bat`
![image](https://user-images.githubusercontent.com/42903751/83477877-efb02600-a4c6-11ea-98fb-edd00608607b.png)

**Comment by simeonpilgrim** [comment]
the directory of your Java location needs to be in the $PATH

```
C:\data\jdk-12.0.1>java --version
openjdk 12.0.1 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

C:\data\jdk-12.0.1>echo %PATH%
...;C:\data\jdk-12.0.1\bin;...

thus you should set in your local path:

![image](https://user-images.githubusercontent.com/3347507/83483958-f1dea880-a4f7-11ea-8082-cae04c7222e7.png)

**Comment by xmhwws** [comment]
![image](https://user-images.githubusercontent.com/42903751/83485897-981bb580-a4da-11ea-93e5-f084d3556f4e.png)
![image](https://user-images.githubusercontent.com/42903751/83485986-c7cabd80-a4da-11ea-9ffe-bb67cb6c95d5.png)
![image](https://user-images.githubusercontent.com/42903751/83485916-a8339500-a4da-11ea-8afb-6dfc8ad0b56a.png)

Thank you for your reminder, but it still fails to start, I don't know where the problem is.

**Comment by xmhwws** [comment]
I found the reason. The release page of github is the source code, I thought it was a built program.
![image](https://user-images.githubusercontent.com/42903751/83486486-d665a480-a4db-11ea-8a1e-e07130ab91a5.png)

Go to https://ghidra-sre.org/ to download the built program and it will start normally.
![image](https://user-images.githubusercontent.com/42903751/83486562-02812580-a4dc-11ea-8b02-b6560c925687.png)
