### ISSUE TITLE
Plugin test with CI

### ISSUE THREAD

**Issue by Le-non** [NationalSecurityAgency/ghidra#1931]
Hey there,
We are currently working towards developing a plugin. We want to integrate CI. I have tests that depend on Ghidra's source code. Currently, for each PR or push to master [our Gradle build ](https://github.com/rossgibb/ghidra-nsis-extension/blob/intitial_ci_commit/.github/workflows/gradle.yml) downloads Ghidra from the official website from scratch each time. We would like to avoid downloading from your servers each time. Is this something that is acceptable? We would like to know what approach would be preferred.
Thanks

**Comment by ryanmkurtz** [comment]
The binaries on ghidra-sre.org only get updated a few times a year when official releases come out.  Why is it necessary to redownload them everytime something is pushed to master on GitHub?

**Comment by astrelsky** [comment]
> The binaries on ghidra-sre.org only get updated a few times a year when official releases come out.  Why is it necessary to redownload them everytime something is pushed to master on GitHub?

I believe @Le-non meant when a pull request is opened and a push to master occurs in the NSISLoader repository. That is common behavior for CI.

I am honestly not familiar with setting up CI or with docker. However, wouldn't it be possible to use docker with a ghidra installation and use that for the tests?

**Comment by Le-non** [comment]
Yes that is what I meant. The testing environment always runs from scratch and it is not possible to port files between each test env with Github actions. 

I'll check if it is possible to use docker with a ghidra installation, I like that idea

**Comment by Le-non** [comment]
Thanks for the idea with Docker!
