### ISSUE TITLE
Don't check for memory conflict when adding an overlay memory block #1375

### ISSUE THREAD

**Issue by JonathanDotCel** [NationalSecurityAgency/ghidra#1933]
Revival of this issue:
https://github.com/NationalSecurityAgency/ghidra/issues/1375

(Adding an overlay shouldn't conflict with existing memory blocks, but does).

![image](https://user-images.githubusercontent.com/61208676/83622872-77119e00-a588-11ea-92a8-02ae1f0ffdb0.png)

Cheers.

**Comment by pelrun** [comment]
Have you tried the nightly, or are you still using 9.1.2 which predates the fix?

**Comment by JonathanDotCel** [comment]
> Have you tried the nightly, or are you still using 9.1.2 which predates the fix?

My bad; just spotted it's been fixed but hasn't reached an official release.
Thanks.
