### ISSUE TITLE
Handle Mach-O encrypted sections better

### ISSUE THREAD

**Issue by TheDauntless** [NationalSecurityAgency/ghidra#1935]
**Describe the bug**
The attached file gives an error when performing Auto Analysis.

The full error message:

```
Failed to create "no return" function __got::_longjmp at 00620358
Failed to create "no return" function __la_symbol_ptr::__ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv at 00620900
Failed to create "no return" function __la_symbol_ptr::__ZNKSt3__121__basic_string_commonILb1EE20__throw_length_errorEv at 00620908
Failed to create "no return" function __la_symbol_ptr::___stack_chk_fail at 00620c18
Failed to create "no return" function __la_symbol_ptr::_abort at 00620c38
Failed to create "no return" function __la_symbol_ptr::_exit at 00620d58
Failed to create "no return" function __la_symbol_ptr::_longjmp at 00620f58
Failed to create "no return" function __la_symbol_ptr::_objc_exception_throw at 00621048
Objective-C 2 Class> Symbol name can't be empty string
```
After this error, only a very limited number of classes/functions are available.

**To Reproduce**
1. Open the file in Ghidra
2. Choose default options for Auto Analysis
3. Receive error; file is not parsed correctly

**Expected behavior**
Auto analysis completes successfully 

**Attachments**
[Flutter.zip](https://github.com/NationalSecurityAgency/ghidra/files/4722874/Flutter.zip)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
 - Ghidra Version: 9.1.2 and same on 9.0.2

**Comment by TheDauntless** [comment]
I have now realized that this framework file is still encrypted (it was extracted from an iOS app). I suggest Ghidra verifies this before analyzing and indicate if the file is encrypted and thus analysis probably won't succeed.

**Comment by ryanmkurtz** [comment]
This ticket will soon be closed with a change that warns the user that encryption was encountered.  We have plans to handle the encryption more intelligently in the near future.
