### ISSUE TITLE
Support for alternative indentation styles

### ISSUE THREAD

**Issue by js53867** [NationalSecurityAgency/ghidra#1937]
**Is your feature request related to a problem? Please describe.**
When using the C-language decompiler the output text is currently printed using [K&R indentation styling](https://en.wikipedia.org/wiki/Indentation_style#K&R_style), e.g.:

```
while (x == y) {
    something();
    somethingelse();
}
```
My own preference is for [Allman styling](https://en.wikipedia.org/wiki/Indentation_style#Allman_style):

```
while (x == y)
{
    something();
    somethingelse();
}
```

I find the increased spacing between code blocks makes the process of understanding complicated code quicker and simpler.

**Describe the solution you'd like**
Since it is probably going to be the case that each individual developer would tend to prefer one or another indentation style, I propose firstly adding support for multiple styles and secondly adding the option to change the indentation style to the decompiler preferences.

**Comment by aerosoul94** [comment]
duplicate issue #81
