### ISSUE TITLE
C Parser #error behaviour

### ISSUE THREAD

**Issue by Learath2** [NationalSecurityAgency/ghidra#1940]
**Describe the bug**
C Parser doesn't halt on #error

**To Reproduce**
Parse a header file with just `#error error`
 
**Expected behavior**
`#error` should stop the parsing immediately and point out the line at which the error occured and in which file. At the very least the errors should be logged and displayed at the end of parsing. Either would make debugging the very frustrating parsing process easier.

**Environment:**
 - OS: macOS 10.15.4
 - Java Version: 11.0.7
 - Ghidra Version: 9.2

**Potential fix**
Instead of/alongside using `Msg.error` inside the parsers we should probably return an `ArrayList` of errors which we can display to the user.

`ghidra.app.util.importer.MessageLog` could also be adapted instead of an `ArrayList`

**Comment by emteere** [comment]
PreProcessor will display error message results for the pre-processing step and the C-parsing step in a scrollable dialog box.

A better refactoring of the error message logging during parse would be useful as a future change and is being considered.
