### ISSUE TITLE
No Horizontal Scroll in Basic Script Editor (MacOS)

### ISSUE THREAD

**Issue by slw07g** [NationalSecurityAgency/ghidra#195]
**Describe the bug**
There does not appear to be any horizontal scrolling available in the built-in script editor _when multiple files are open in the editor_. The only workaround is to resize the window/pane.

**To Reproduce**
1. Open Script Manager
2. Right-click a script
2a. Edit with basic editor
3. Find line of code longer than the width of the editor pane
4. Attempt to view the full line without having to resize the window.

**Expected behavior**
I expected a scroll bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/8406059/54357745-1a4d5f00-4635-11e9-8cb4-bfe6a92f3267.png)

**Attachment
N/A

**Environment (please complete the following information):**
 - OS: MacOS 10.14.3 (Mojave - Dark mode)
 - Java Version: 11.0.2
 - Ghidra Version: 9.0

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
It's working for me with an Apple Mighty Mouse.  What type of device are you using?

**Comment by ryanmkurtz** [comment]
If you have only one tab open for that window (I see you have 2 in that screenshot), does it change anything?

**Comment by slw07g** [comment]
Yep, it appears the issue is linked to having multiple files open in the editor.

**Comment by dev747368** [comment]
Could you try switching your Look and feel to something else?
(Main window -> Edit -> Tool Options -> Tool -> Swing Look and feel, then restart Ghidra)

**Comment by dev747368** [comment]
Closing, no response.
