### ISSUE TITLE
C-Parser does not understand extern "C" with brackets.

### ISSUE THREAD

**Issue by ipatix** [NationalSecurityAgency/ghidra#1957]
**Describe the bug**
The C-Parser throws an error when trying to parse a C-file which contains an `extern "C"` directive that uses `{ }` brackets to define multiple C symbols.

**To Reproduce**
1. Create a file with the following contents:
```
extern "C" {
  typedef unsigned int size_t;
}
```
2. Click on 'File -> Parse C Source'
3. Copy any configuration to create a new one.
4. In this new configuration, delete all header files and all parse options
5. Add a path to the file we created in 1.
6. Click on "Parse to File...'
7. The following error is shown:
```
C Parser: Encountered errors during parse.
  in C:\temp\test.h near line 2
  near token: "C"
  Last Valid Datatype: - none -
  Check around CParserPlugin.out around line: 3
```

**Expected behavior**
I'd except the parsing to succeed the same way it does for this file:
```
extern "C" typedef unsigned int size_t;
```
Manually having to convert all my headers to that format seems a bit wrong to me.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 Pro, Version 10.0.18362 Build 18362
 - Java Version: OpenJDK 13.0.2
 - Ghidra Version: 9.1.2

**Additional context**
I was trying to parse some old MSVC headers which have been preprocessed by cl.exe. However, Ghidra starts to fail at importing these with error above because these headers use that bracket style for extern "C".

**Comment by pelrun** [comment]
`extern <string literal>` over a block is C++ syntax. In pure C it's only applicable to variables and functions.

**Comment by ipatix** [comment]
So "Parse C Source" is only C and not C++?

**Comment by pelrun** [comment]
Yes, it's currently a fairly basic C-only parser.
