### ISSUE TITLE
NullPointerException when launching the Python interpreter

### ISSUE THREAD

**Issue by aboood40091** [NationalSecurityAgency/ghidra#1965]
When I try to launch the Python interpreter, I get a pop up saying:
`"Resetting Python Uncaught Exception: java.lang.NullPointerException"`

Here is the window expanded:
![image](https://user-images.githubusercontent.com/10743814/84184350-3a6d0780-aa9e-11ea-89af-d53aaabd9e3e.png)

**Comment by ryanmkurtz** [comment]
Do you have an entry in your Ghidra log that reads "Problem getting Ghirda Python interpreter".  If so, can you provide that stack trace too?

**Comment by aboood40091** [comment]
![image](https://user-images.githubusercontent.com/10743814/84185169-a56b0e00-aa9f-11ea-905a-fbf835ce0af4.png)

**Comment by ryanmkurtz** [comment]
Does the directory `C:\Users\USR\AppData\Local\Temp\USR-Ghidra` exist?

**Comment by aboood40091** [comment]
No.

**Comment by ryanmkurtz** [comment]
Ok, that would be the problem.  Ghidra's Python Plugin is assuming that something would have already created Ghidra's temp directory.  I'll have to look into how that can be.

**Comment by aboood40091** [comment]
Yeah, creating it manually fixes the problem.
One way to fix this, I suppose, is to check the existence of such folder and create it before trying to create `jython_cachedir`.

**Comment by ryanmkurtz** [comment]
Yea, that would be a good thing to do.  When I start my Ghidra, something is creating that directory though...I'd curious to see what it is and why it's not creating it for you.

**Comment by ryanmkurtz** [comment]
I see where it's being created.  How are you launching Ghidra...by running ghidraRun.bat?  Did you have any other errors/exceptions in your log?

**Comment by aboood40091** [comment]
![image](https://user-images.githubusercontent.com/10743814/84199736-b70be000-aab6-11ea-92d5-83c7c6c3e3ba.png)

**Comment by mumbel** [comment]
Ah, yeah, I've seen this probably too https://github.com/NationalSecurityAgency/ghidra/issues/1842#issuecomment-624228112

**Comment by ryanmkurtz** [comment]
What is that screen shot showing?  What you get when you run ghidraRun.bat?

**Comment by aboood40091** [comment]
Right, it may be that issue for both timeout _and_ find.
`timeout.exe /NOBREAK 1` produces and error, whereas `%SystemRoot%\System32\timeout.exe /NOBREAK 1` doesn't.

**Comment by ryanmkurtz** [comment]
Ghidra 9.2 will make that error go away.  We still don't know why you don't have a Ghidra temp directory though.  

Right after you launch Ghidra, does `C:\Users\USR\AppData\Local\Temp\USR-Ghidra` exist?

**Comment by aboood40091** [comment]
Closing this since the issue no longer exists as Ghidra successfully creates the temp folder automatically now.
