### ISSUE TITLE
Find uses of enum member

### ISSUE THREAD

**Issue by jtuu** [NationalSecurityAgency/ghidra#1967]
**Is your feature request related to a problem? Please describe.**
Currently you can search for uses of an enum but not for uses of a specific member of an enum. I think being able to search for uses of a specific member of an enum would be a useful feature.

**Describe the solution you'd like**
Add a new option in the "References" menu when right-clicking an enum type. Something like "Find uses of [enum member name]".

**Describe alternatives you've considered**
I was thinking about writing a script to do this but I think it would also be a good built-in feature.

**Additional context**
None

**Comment by IvanDSM** [comment]
Agreed, this would be really nice to have.
