### ISSUE TITLE
Disassembling MIPS on odd bytes

### ISSUE THREAD

**Issue by Jaguar83** [NationalSecurityAgency/ghidra#1970]
I have a MIPS library where some of the functions start on odd-numbered bytes. For example, when I press "D" to disassemble the bytes at _0000bdc7_, Ghidra instead disassembles from _0000bdc6_.

I realise this is unusual for a MIPS system, but is there a way to tell Ghidra to allow disassembly on odd bytes?

**Comment by simeonpilgrim** [comment]
It baked into the processor sla, in `<project root>\Ghidra\Processors\MIPS\data\languages\mips.sinc` on line 173 there is this:

    define alignment=2;

changing that to 1 and rebuilding the MIPS processors would do the trick.

I would be more inclined to define a new class of MIPS based off the one you are using and use a build directive to toggle between them, but if you have done a lot of work already that would be maybe too painful.

but from the `<project root>\support\` directory run the command sleigh -a ..\Ghidra\Processors\MIPS\` will rebuild them once you have alter the `=2` to `=1`

**Comment by Jaguar83** [comment]
That worked.
I'd already created a new class to add extra PSX instructions, so creating another, unaligned class was no issue.
