### ISSUE TITLE
Getting all open PluginTools

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1974]
I would like to be able to get a Collection of all open PluginTool instances in a static context. Is there currently such a way to do so?

**Comment by ryanmkurtz** [comment]
I see ways to do it if you have a tool already.  Do you?

**Comment by ryanmkurtz** [comment]
If you are running from the GUI, you can do `AppInfo.getFrontEndTool()` to get a tool.

**Comment by astrelsky** [comment]
> I see ways to do it if you have a tool already. Do you?

Nope. I need to get one to determine if my plugin is activated and only return true if it is in Analyzer.canAnalyze. I'm not able to use the AutoAnalysisManager approach because at the type Analyzer.canAnalyze is invoked the AutoAnalysisManager has not been fully constructed. Thus invoking AutoAnalysisManager.getAnalysisManager continues forever until the maximum stack depth is reached or the jvm is out of memory.

> If you are running from the GUI, you can do `AppInfo.getFrontEndTool()` to get a tool.

I will take this approach. Thank you.

Also I looked a bit further and it may be possible in headless mode via `AppInfo.getActiveProject().getToolServices().getRunningTools()` or `AppInfo.getActiveProject().getToolManager()...`

**Comment by ryanmkurtz** [comment]
AppInfo is worth remembering.  Whenever I can't seem to get access to something I really need, I always look there.
