### ISSUE TITLE
Enable Auto Analyzer by Jython

### ISSUE THREAD

**Issue by ightelsentearten** [NationalSecurityAgency/ghidra#1976]
How would one enable an auto analyzer from Jython?

The GUI example would be checking the `Enabled` check box from the **Analysis -> Auto Analyze '...'** menu.

I can see the the `get(set)AnalysisOption*` methods in [GhidraScript](https://ghidra.re/ghidra_docs/api/ghidra/app/script/GhidraScript.html), but I do not see the ability to set the analyzers run. 

Any hints as to which class/methods I need to call?  Thanks!

**Comment by ryanmkurtz** [comment]
I believe you want to use the `AutoAnalysisManager` class.

**Comment by ightelsentearten** [comment]
hey @ryanmkurtz , thanks for replying.

I looked at the [AutoAnalysisManager](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/analysis/AutoAnalysisManager.java) class and it looks like [scheduleOneTimeAnalysis()](https://github.com/NationalSecurityAgency/ghidra/blob/bdbbca30a155502b79a38874c0186a7ac496dfeb/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/analysis/AutoAnalysisManager.java#L218) is the best bet.

Doesn't appear to be a way to enable/disable before running auto analysis on a program.

Example usage:
```python
from ghidra.app.plugin.core.analysis import AutoAnalysisManager

aam = AutoAnalysisManager.getAnalysisManager(currentProgram)

# Doesn't appear to be a direct way to get the list of registered analyzers, use the menu for the string or list the options
analyzer_to_run = aam.getAnalyzer('ASCII Strings')

# Probably not the easiest way to get an address set, but meh
mem = currentProgram.getMemory()
asv = mem.getAllInitializedAddressSet()

aam.scheduleOneTimeAnalysis(analyzer_to_run, asv)
```
