### ISSUE TITLE
Make json-simple available to scripts

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1982]
Sometimes I want to use JSON in a GhidraScript, but Ghidra only uses json-simple at build time...it is not available at runtime.  I think it can be included in Framework Generic.

**Comment by astrelsky** [comment]
There is the [https://ghidra.re/ghidra_docs/api/generic/json/JSONParser.html](JSONParser) although it isn't that fun to use and is not intuitive. This is an example of using it

```
@SuppressWarnings("unchecked")
public static Map<String, Object> parseJson(String jsonData) throws Exception {
    JSONParser parser = new JSONParser();
    LinkedList<JSONToken> tokens = new LinkedList<>();
    switch (parser.parse(jsonData.toCharArray(), tokens)) {
        case JSMN_ERROR_INVAL:
            throw new Exception("JSON contains invalid character");
        case JSMN_ERROR_NOMEM:
            throw new Exception("Not enough tokens");
        case JSMN_ERROR_PART:
            throw new Exception("Malformed or missing JSON data");
        case JSMN_SUCCESS:
            break;
    }
    return (Map<String, Object>) parser.convert(jsonData.toCharArray(), tokens);
}
```

The reason for the unchecked conversion to String keys is because the json standard required that the key be a string. https://en.wikipedia.org/wiki/JSON#Data_types_and_syntax

**Comment by ryanmkurtz** [comment]
Didn't know about that...thanks.  Is there anything to take a map and produce a JSON string?

**Comment by astrelsky** [comment]
> Didn't know about that...thanks.  Is there anything to take a map and produce a JSON string?

Actually I don't think there is. To be honest I would love to see this parser replaced with something much more user friendly.

Of course there are existing alternatives, but none I'd actually recommend. [Bad alternative](https://www.adam-bien.com/roller/abien/entry/converting_json_to_map_with)

**Comment by ryanmkurtz** [comment]
I've used json-simple before (for Ghidra and other things).  It's pretty good.

**Comment by dragonmacher** [comment]
FYI, if you simply wish to turn Java objects to pretty JSON strings, then you can use our new `generic.json.Json` class's `toString()` methods.

**Comment by ryanmkurtz** [comment]
I was looking to go both directions with it.

**Comment by revolver-ocelot-saa** [comment]
I know this is closed, but just wanted to say thank you for doing this!  Adding a way to import GSON saves me from making most of my Ghidra script's into full extensions (since that was the best way to bring that JAR along).

**Comment by pabx06** [comment]
if i remember well i think i saw google's gson in the path of ghidra  9.2. Pretty handy lib easy to use.
there is always  the option to add a jar : via plugin path
![image](https://user-images.githubusercontent.com/4013370/99963248-c5626580-2d91-11eb-81a2-e5c196026fb5.png)

**Comment by astrelsky** [comment]
> if i remember well i think i saw google's gson in the path of ghidra  9.2. Pretty handy lib easy to use.
> there is always  the option to add a jar : via plugin path
> ![image](https://user-images.githubusercontent.com/4013370/99963248-c5626580-2d91-11eb-81a2-e5c196026fb5.png)
> 

Was just about to say this.

Anyone have a simple example for using gson? Python's `json` has spoiled me rotten.

**Comment by dragonmacher** [comment]
> Anyone have a simple example for using gson? Python's json has spoiled me rotten.

There is a trivial example in the `ExportFunctionInfoScript`.
