### ISSUE TITLE
getParameterCount() not working

### ISSUE THREAD

**Issue by cssaheel** [NationalSecurityAgency/ghidra#1984]
Hello, I am trying to write Ghidra python script that iterate through all the functions and output the functions parameters count:
```
fiter = currentProgram.getFunctionManager().getFunctions(True)
while (fiter.hasNext()):
	function = fiter.next()
	if (monitor.isCancelled()):
		break
	print str(function.getName()) + ":" + str(function.getParameterCount()) + "\n"
```

in the decompiler I see that FUN_00001000 has two parameters (which is correct):
void FUN_00001000(char *param_1,longlong param_2)

but in the script output I see that function has no parameter (which is wrong)!
FUN_00001000:**0**

am I doing something wrong or this is a bug? is there a way around this? Thank you.

**Comment by saruman9** [comment]
> in the decompiler I see that FUN_00001000 has two parameters

Are you commited params/return of the function from Decompiler to Listing?

Right click on a name of the function, `Commit Params/Return` or `P` hotkey.

**Comment by cssaheel** [comment]
Thank you! this worked perfectly.
