### ISSUE TITLE
How to run headless script in parallel

### ISSUE THREAD

**Issue by dlmgary** [NationalSecurityAgency/ghidra#1990]
Hello, 

I have a shared project with thousands of binaries. I've written a script that needs to process all of the binaries, is there a way to parallelize the headless analysis? 

Thanks,
-Gary

**Comment by ryanmkurtz** [comment]
Ghidra does not provide a built-in means to do it in parallel.  Typically users will just start several instances of the analyzeHeadless script to achieve something similar.  You may have to reorganize your project in a way that will support this though so analysis does not overlap from instance to instance.
