### ISSUE TITLE
Convert SLEIGH parser from ANTLR to Tree-Sitter

### ISSUE THREAD

**Issue by XVilka** [NationalSecurityAgency/ghidra#1993]
Currently SLEIGH parser grammar implemented with ANTLR. But there exist much more modern and flexible parser generator framework - [tree-sitter](https://github.com/tree-sitter/tree-sitter). Apart from the normal "static" parser Tree-sitter designed to be more error-forgiving and able to parse things on the fly being incremental, since the main design goal was to use it for the syntax parsing in the editors. It is able to generate high-performance C code with [many various bindings](https://github.com/tree-sitter/tree-sitter/blob/master/docs/index.md#language-bindings).

Moreover, with the switch you will get the support of the SLEIGH files in the Visual Studio Code, NeoVim, [Emacs](https://github.com/ubolonton/emacs-tree-sitter), etc. It will simplify other tools integration as well.

**Comment by astrelsky** [comment]
I don't see Java listed in the available language bindings.

**Comment by XVilka** [comment]
@astrelsky there is https://github.com/JetBrains/jsitter

**Comment by saruman9** [comment]
Also exists other parsers:
- [Xtext](https://github.com/NationalSecurityAgency/ghidra/tree/master/GhidraBuild/EclipsePlugins/GhidraSleighEditor/ghidra.xtext.sleigh)
- [flex](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/decompile/cpp/slghscan.l) + [bison](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/decompile/cpp/slghparse.y)

**Comment by XVilka** [comment]
Fast-forward a few years, and Tree-Sitter became even more popular. Currently, the most updated Java bindings are https://github.com/bonede/tree-sitter-ng and are on Maven.

**Comment by ryanmkurtz** [comment]
Our team just discussed the pros/cons of this and while we see some pros, it's not currently worth the time investment on our end.  I am going to close it to indicate that the team will not be working on this.
