### ISSUE TITLE
Extracting Info from Ghidra Listing Window

### ISSUE THREAD

**Issue by sajjadirn** [NationalSecurityAgency/ghidra#1994]
I have written a script which extracts all the assembly code from a PE using this code in ghidra
`
instructionList = []
for instr in currentProgram.getListing().getInstructions(True):
    instructionList.append(instr)
`
but the issue is that, is changes all the .DLL calls in the assembly code. For example, if the listing window shows
`
CALL        dword ptr [->MSVCRT.DLL::signal] 
`
The output I get is
`
CALL dword ptr [EBP + -0x14]
`
Is there a way to get the assembly code exactly as it is in the listing window

**Comment by saruman9** [comment]
See example [in the script](https://github.com/saruman9/ghidra_scripts/blob/9f57380f9b2998fd5e47fa257a84b2d232e9ce34/TestMarkup.java).
Import needed modules for using `CodeUnitFormat` and `CodeUnitFormatOptions` in Python:
```python
from ghidra.program.model.listing import CodeUnitFormatOptions
from ghidra.program.model.listing import CodeUnitFormat
```
And [set](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/CodeUnitFormat.html#%3Cinit%3E(ghidra.program.model.listing.CodeUnitFormatOptions)) needed [options](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/CodeUnitFormatOptions.html#%3Cinit%3E(ghidra.program.model.listing.CodeUnitFormatOptions.ShowBlockName,ghidra.program.model.listing.CodeUnitFormatOptions.ShowNamespace,java.lang.String,boolean,boolean,boolean,boolean,boolean,boolean,boolean)), for example:

```python
codeUnitFormat = CodeUnitFormat(
    CodeUnitFormatOptions(
        CodeUnitFormatOptions.ShowBlockName.ALWAYS,
        CodeUnitFormatOptions.ShowNamespace.ALWAYS,
        "",
        True, True, True, True, True, True, True
    )
)

```

**Comment by sajjadirn** [comment]
> See example [in the script](https://github.com/saruman9/ghidra_scripts/blob/9f57380f9b2998fd5e47fa257a84b2d232e9ce34/TestMarkup.java).
> Import needed modules for using `CodeUnitFormat` and `CodeUnitFormatOptions` in Python:
> 
> ```python
> from ghidra.program.model.listing import CodeUnitFormat, CodeUnitFormatOptions
> ```
> 
> And [set](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/CodeUnitFormat.html#%3Cinit%3E(ghidra.program.model.listing.CodeUnitFormatOptions)) needed [options](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/CodeUnitFormatOptions.html#%3Cinit%3E(ghidra.program.model.listing.CodeUnitFormatOptions.ShowBlockName,ghidra.program.model.listing.CodeUnitFormatOptions.ShowNamespace,java.lang.String,boolean,boolean,boolean,boolean,boolean,boolean,boolean)), for example:
> 
> ```python
> codeUnitFormat = CodeUnitFormat(
>     CodeUnitFormatOptions(
>         CodeUnitFormatOptions.ShowBlockName.ALWAYS,
>         CodeUnitFormatOptions.ShowNamespace.ALWAYS,
>         "",
>         True, True, True, True, True, True, True
>     )
> )
> ```

Thank You for your reply!
I made some tweaks as you suggested and got what i wanted.
