### ISSUE TITLE
Duplicated "New Folder" button in file importer's project tree dialog 

### ISSUE THREAD

**Issue by jroimartin** [NationalSecurityAgency/ghidra#1996]
**Describe the bug**
The project tree dialog in the file importer shows the "New Folder" button twice. 

**To Reproduce**

1. From the frontend, import file
2. Select the file to import
3. Click the browse button ("...") next to "Destination Folder:"
4. Right click anywhere in the project tree

**Expected behavior**
There should be only one "New Folder" button in the pop-up dialog.

**Screenshots**

![image](https://user-images.githubusercontent.com/1223476/84933139-b63a0600-b0d5-11ea-9468-0e6a0cde5b63.png)

**Environment**
 - OS: GNU/Linux
 - Java Version: openjdk 11.0.7
 - Ghidra Version: git master (commit id bdbbca30a155502b79a38874c0186a7ac496dfeb)

**Comment by dragonmacher** [comment]
Fixed by 3ea1125
