### ISSUE TITLE
Scripting: get function signatures from GUI decompiler to script api

### ISSUE THREAD

**Issue by milsegv** [NationalSecurityAgency/ghidra#1999]
I'm posting an issue here because I could not find any related answer anywhere, not on the web nor in the documentation.

Using CodeBrowser I loaded a binary with some functions. The Ghidra Decompiler is able to automatically set up every function parameters as expected and has the correct signature.

However, when I use a script on this function and try to get a function's signature, I got a default signature with an undefined return type and a single void parameter.
I guess that is because automatic signatures are only defined in the Decompiler view. 

Is there a way to "push" signatures from the Decompiler view to the Scripting API ?

Thanks for any help !

**Comment by ryanmkurtz** [comment]
Sounds like you need to commit your parameters and return value from the decompiler to the listing.  Right click on your function definition in the decompiler, and click "Commit Params/Return."

**Comment by milsegv** [comment]
Effectively that fixed it, thanks for your help !

**Comment by ryanmkurtz** [comment]
Sure thing.  There is also an analyzer called Decompiler Parameter ID that you might want to play with when you first analyze your binary.  It's turned off by default for larger binaries.

**Comment by saruman9** [comment]
Also you can get [return type and parameters](https://github.com/saruman9/ghidra_scripts/blob/288a2226893fd6801f1234971eef99b69590547e/CommitParamsReturn.java#L48-L55) of the function without commiting. Or commit params/return [by API](https://github.com/saruman9/ghidra_scripts/blob/288a2226893fd6801f1234971eef99b69590547e/CommitParamsReturn.java#L58-L59). It may be useful, if you use headless analyze.

**Comment by milsegv** [comment]
Thanks, those are indeed really useful for headless mode !
