### ISSUE TITLE
OSX: scrolling only goes down

### ISSUE THREAD

**Issue by yifanlu** [NationalSecurityAgency/ghidra#2]
On OSX 10.14.1, when you use the mouse's touch scroll or the touchpad's touch scroll, it will only scroll down regardless of the direction you are scrolling. If mouse scroll direction is set to "Natural" then it's a bit better as upward scrolling works somewhat but it's still buggy because it seems to "resist" the scroll.

**Comment by GGG-KILLER** [comment]
This is happening on Windows 10 as well

**Comment by JujharSingh** [comment]
I'm also getting this issue on Windows 10 on my Surface Pro 3 trackpad.

**Comment by zzzanderw** [comment]
Can confirm with MBP 2018 trackpad, macOS 10.14.1

**Comment by zzzanderw** [comment]
One thing of note is that the scrolling behaves correctly on the symbol tree, program trees, and data type manager. Just the asm and decomp views appear to be misbehaving.

**Comment by EthanArbuckle** [comment]
+1

**Comment by zzzanderw** [comment]
Another thing I found out is if you scroll really fast, it will let you scroll up. Not sure how/why the scroll velocity is a differentiator, but that's a possible workaround. Only tested this on Mac trackpad.

**Comment by GGG-KILLER** [comment]
Can confirm that is a possible "workaround" on Windows 10 as well.

**Comment by nneonneo** [comment]
FIXED!

```diff
diff --git a/src/Docking/docking/widgets/fieldpanel/FieldPanel.java b/src/Docking/docking/widgets/fieldpanel/FieldPanel.java
index 7194951..4e097fd 100644
--- a/src/Docking/docking/widgets/fieldpanel/FieldPanel.java
+++ b/src/Docking/docking/widgets/fieldpanel/FieldPanel.java
@@ -1420,6 +1420,8 @@ public class FieldPanel extends JPanel
         @Override
         public void mouseWheelMoved(MouseWheelEvent e) {
             int wheelRotation = e.getWheelRotation();
+            if(wheelRotation == 0)
+                return;
             int scrollAmount = (wheelRotation < 0) ? -40 : 40;
             if (hoverHandler.isHoverShowing()) {
                 hoverHandler.scroll(scrollAmount);
```

Attached is the fixed `Docking.jar` - replace `Ghidra/Framework/Docking/lib/Docking.jar` with this copy. (Compressed again as a .zip so it can be attached).

Tested and working on macOS 10.14.3, Java 11.0.2.

[Docking.jar.zip](https://github.com/NationalSecurityAgency/ghidra/files/2934940/Docking.jar.zip)

**Comment by nneonneo** [comment]
Second fixed version that uses floating points, which makes it support flinging/high-speed motions and smooth scroll. Scrolling is now *buttery-smooth* with my trackpad.

```diff
diff --git a/src/Docking/docking/widgets/fieldpanel/FieldPanel.java b/src/Docking/docking/widgets/fieldpanel/FieldPanel.java
index 7194951..2d72151 100644
--- a/src/Docking/docking/widgets/fieldpanel/FieldPanel.java
+++ b/src/Docking/docking/widgets/fieldpanel/FieldPanel.java
@@ -1419,8 +1419,10 @@ public class FieldPanel extends JPanel
     public class BigFieldPanelMouseWheelListener implements MouseWheelListener {
         @Override
         public void mouseWheelMoved(MouseWheelEvent e) {
-            int wheelRotation = e.getWheelRotation();
-            int scrollAmount = (wheelRotation < 0) ? -40 : 40;
+            double wheelRotation = e.getPreciseWheelRotation();
+            int scrollAmount = (int)(wheelRotation * 40);
+            if (scrollAmount == 0)
+                return;
             if (hoverHandler.isHoverShowing()) {
                 hoverHandler.scroll(scrollAmount);
             }
```

[Docking.jar.zip](https://github.com/NationalSecurityAgency/ghidra/files/2934980/Docking.jar.zip)

**Comment by mehdideveloper** [comment]
Thanks for the fixes; They don't work on my systems for some reason (MacBook Pro 2015 and 2018, latest macOS). Replacing the Docking.jar does not change the behaviour :/

**Comment by nneonneo** [comment]
Did you restart Ghidra completely after replacing the files?

**Comment by OothecaPickle** [comment]
@nneonneo how do i build all the stuff from Docking-src.zip myself?

**Comment by nneonneo** [comment]
@OothecaPickle I didn't build the whole .jar, I just found the file that needed patching and replaced it.

Here's my command, assuming the source is in `src/Docking` and you're in that directory:

    javac -cp $(printf "%s:" $(find ../.. -name '*.jar'))  docking/widgets/fieldpanel/FieldPanel.java 
    jar -uf ../../Ghidra/Framework/Docking/lib/Docking.jar $(find . -name '*.class')

**Comment by mehdideveloper** [comment]
> Did you restart Ghidra completely after replacing the file?

Yes

**Comment by OothecaPickle** [comment]
@nneonneo your patch works great and i was able to compile with those commands. thanks! :)

**Comment by OothecaPickle** [comment]
after further testing, it only works some of the time, but still, better than before!

**Comment by nneonneo** [comment]
Interesting that the fix doesn’t work all the time. What sorts of things are you seeing when it doesn’t work, @OothecaPickle?

**Comment by OothecaPickle** [comment]
@nneonneo if i scroll quickly, scrolling up works fine, but if i scroll slowly it scrolls down.

**Comment by 6661696c** [comment]
Those changes work for me (although I clearly was in a different dir when I built the jar and had to change that a bit), scrolling works perfectly for me now regardless of speed.

**Comment by OothecaPickle** [comment]
@6661696c are you using a trackpad or magic mouse?

**Comment by 6661696c** [comment]
Trackpad on 2017 MacBook Pro running 10.14.3.

**Comment by ryanmkurtz** [comment]
Thanks for the suggested fix...it will be included in the next release!

**Comment by jiva** [comment]
> @OothecaPickle I didn't build the whole .jar, I just found the file that needed patching and replaced it.
> 
> Here's my command, assuming the source is in `src/Docking` and you're in that directory:
> 
> ```
> javac -cp $(printf "%s:" $(find ../.. -name '*.jar')) docking/widgets/fieldpanel/FieldPanel.java 
> jar -uf ../../Ghidra/Framework/Docking/lib/Docking.jar $(find . -name '*.class')
> ```

This works nicely - thanks for the fix!

Does your sideways scroll work on MacOS? Mine doesn't seem to work properly.

**Comment by TheHolyC** [comment]
@jiva Looks like it would take quite a bit of work to make that work, the layout handler doesn't support horizontal scrolling and the java API being used here doesn't understand that touchpad scrolling exists :/
