### ISSUE TITLE
How to obtain the listing name including external lib/function name as in the Listing windows

### ISSUE THREAD

**Issue by pawlos** [NationalSecurityAgency/ghidra#2001]
Assuming I have the such code in my binary:

          005c9cfc ff  15  54  f2  b7  00                   CALL      dword ptr [-> MSVCP140.DLL::std::basic_ios<char,struct_std::

but when I print this instruction from python script using such code

    currentProgram.getListing().getInstructionAt(toAddr(0x5c9cfc))

what I'm getting is "only" `CALL dword ptr [0x00b7f254]`.

Is there a way to obtain the same listing in script so that it include external's lib/function name?

**Comment by ryanmkurtz** [comment]
Check out #1994 from yesterday.

**Comment by pawlos** [comment]
OK, I guess it based on the same question from SO: https://reverseengineering.stackexchange.com/questions/25322/extracting-info-from-ghidra-listing-window
