### ISSUE TITLE
Modules for the decompiler c++ code ?

### ISSUE THREAD

**Issue by Myshtea** [NationalSecurityAgency/ghidra#2002]
I am trying to set up a way to add rules in the decompiler in order to be able to add de-obfuscation that can persistently modify pCode (and then pseudo-C code).

Right now It's pretty easy to add rules but is there a way to have this using modules ? I know that it is possible for Java/jython code using the api but is it possible for deeper c++ code ?

I mean it would be practical to have this without having to buildGhidra everytime ...

**Comment by astrelsky** [comment]
You don't have to run `buildGhidra` each time. You can build each module individually from gradle. For example, may not be accurate, `gradle :Decompiler:build` 

You can get the list of available tasks via `gradle tasks` and the list of projects via `gradle projects`. After building what you want just find the output and place it in the corresponding directory in your ghidra installation.

**Comment by Myshtea** [comment]
Thanks I'm not really used to gradle yet so that helped me.

Still is it possible to have a module changing inner decompiler code ? Seems to me that this is not possible but it would be very useful to be able to use inner mechanics of the code

**Comment by astrelsky** [comment]
> Thanks I'm not really used to gradle yet so that helped me.
> 
> Still is it possible to have a module changing inner decompiler code ? Seems to me that this is not possible but it would be very useful to be able to use inner mechanics of the code

I think it might be possible but you would still have to compile the code. I'm thinking something along the lines of shared library injection. I'm sure some users may have security concerns with it though and I'm honestly not familiar with it. Just brainstorming here.

**Comment by toshipiazza** [comment]
XREF https://github.com/NationalSecurityAgency/ghidra/issues/1907, though that issue is concerned with modifying the clang AST (not the optimized pcode AST) from java before displaying
