### ISSUE TITLE
Resize Structures on resolve, replaceWith, add, etc from archive

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2007]
**Is your feature request related to a problem? Please describe.**
Resolving or using replaceWith with the source Structure coming from a DataTypeManager that has a long size smaller than the destinations results in broken structures and failed decompilation where the structure is used.

**Describe the solution you'd like**
Grow the structure to accommodate for the difference in field size.

**Describe alternatives you've considered**
Manually fixing 1000s of these by hand.

**Comment by ghidra1** [comment]
Structures with alignment enabled should grow and repack to accommodate type size changes.  That is what makes them preferable over "unaligned" structures which do not reposition components.  If using unaligned structures it is important that they are created using a "target" data type manager with the appropriate compiler specification.  When placed into an archive the default data organization is used and may distort them but in most cases once applied to a program with the original "target" data organization they should return to their original layout.  For this reason I do not recommend ingesting directly into an datatype archive.  This is particularly problematic for bitfields within unaligned composites which can get messed-up when transitioning in/out of an archive to a program.

**Comment by astrelsky** [comment]
> Structures with alignment enabled should grow and repack to accommodate type size changes. That is what makes them preferable over "unaligned" structures which do not reposition components. If using unaligned structures it is important that they are created using a "target" data type manager with the appropriate compiler specification. When placed into an archive the default data organization is used and may distort them but in most cases once applied to a program with the original "target" data organization they should return to their original layout. For this reason I do not recommend ingesting directly into an datatype archive. This is particularly problematic for bitfields within unaligned composites which can get messed-up when transitioning in/out of an archive to a program.

Aha. I was not aligning the structures and checking for changes. I was not aware of that aligned structures would reposition themselves while unaligned structures would not. Thank you!
