### ISSUE TITLE
Structure Editor Move Component Up/Down Key Bug

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2008]
**Describe the bug**
The `alt`+up/down key shortcuts only work using the left alt key and not the right alt key.

**To Reproduce**
1. Open Structure Editor
2. Use the left `alt` + up/down to move components
3. Use the right `alt` + up/down to move components

**Expected behavior**
It should work using the right or left alt key.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.329]
 - Java Version: 14.0.1
 - Ghidra Version: 9.2 bdbbca30a155502b79a38874c0186a7ac496dfeb

**Comment by NZSmartie** [comment]
The right `alt` key also does not for for both _Next Location in History_ and _Previous Location in History_

**Comment by Wall-AF** [comment]
I would like to see the `Right Alt` key used to bring up the context menu, as an alternative to `Right Mouse Click`.

**Comment by NZSmartie** [comment]
> 
> 
> I would like to see the `Right Alt` key used to bring up the context menu, as an alternative to `Right Mouse Click`.

Typically, the hot key to bring up the context menu (right click) is `shift` + `F10`. which unsurprisingly, doesn't work in Ghidra

**Comment by Wall-AF** [comment]
`Right Alt` or `Shift F10` either one would significantly increase usability imho!

**Comment by gtackett** [comment]
I reported this problem with left-alt and right-alt months ago to the Ghidra team myself via a different channel. I believe they weren't able to reproduce the problem, but I have no trouble at all reproducing it.

**Comment by dev747368** [comment]
> I reported this problem with `Left Alt` and `Right Alt` months ago to the Ghidra team myself via a different channel. I believe they weren't able to reproduce the problem, but I have no trouble at all reproducing it.

I think its a platform issue.  With windows10 desktop at home my right-alt (ie. r-alt-leftarrow) does nothing.

**Comment by dev747368** [comment]
Right-Alt key on windows: https://bugs.openjdk.java.net/browse/JDK-8194873

Looks like some platform specific elbow-grease is needed.

**Comment by Wall-AF** [comment]
`Right Alt` (or `AltGr`) is technically a different key and has its own virtual key code (`VK_RMENU`).

**Comment by Wall-AF** [comment]
> 
> 
> `Right Alt` or `Shift F10` either one would significantly increase usability imho!

`Right Alt` (or `AltGr`) is the wrong name for what I was thinking!  I should have said the `Context Menu` key!  (Duh, brain dead!!!)
