### ISSUE TITLE
runtime exception importing 16 bit ne dll

### ISSUE THREAD

**Issue by goshhhy** [NationalSecurityAgency/ghidra#2012]
**Describe the bug**
importing pidgen.dll from the windows 98 se retail installation environment fails with a runtime exception error

java.lang.RuntimeException: NE - ResourceType - name lookup required - 36
(see screenshot for full trace)

**To Reproduce**
1. create a new project
2. import "PIDGEN.DLL" from the windows 98 se retail installation environment

**Expected behavior**
the dll imports successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/37872995/85095463-89e5be80-b195-11ea-8043-d49b4c3b8856.png)

**Attachments**
(not attaching dll for copyright reasons)

**Environment (please complete the following information):**
- OS: Bedrock Linux 0.7.17 Poki x86_64 (alpine linux edge + arch linux + gentoo)
- Java Version: openjdk version "11.0.7" 2020-04-14
- Ghidra Version: ghidra_9.1.2_PUBLIC

this may be a duplicate of  #1596

**Comment by emteere** [comment]
Can you try this in the master branch to see if it is still an issue?   I believe this may have been fixed but not gotten into a release, yet.

**Comment by goshhhy** [comment]
i can test it in a few hours, and will let you know of the results.

**Comment by emteere** [comment]
Should be fixed in master/9.2
