### ISSUE TITLE
Can't add the OTHER overlay memory block

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#2020]
**Describe the bug**
When you try to create a memory block in the OTHER address space, you should use an overlay memory type, but the dialog of creating memory block show warning message (_Blocks defined in the OTHER space must be overlay blocks_) even if you set the overlay flag.

**To Reproduce**
1. Open the Memory Map, open the Add Memory Block dialog.
2. Input the Block Name, select the OTHER address space, set the Length, set the Overlay flag.
3. See error as a hint.

**Expected behavior**
The overlay memory block located in the OTHER address space should be created without problems. 

**Screenshots**
![2020-06-22_10-59-38](https://user-images.githubusercontent.com/4244396/85263207-7e391700-b477-11ea-93bf-7dd1c531eb08.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11.0.7
 - Ghidra Version: bdbbca3

**Additional context**
If you change something and return it, then warning will disappear. Problem commit is 6ff98a409.

**Comment by ghidra1** [comment]
PR Merged for 9.2
