### ISSUE TITLE
Cannot cancel DecompilerParameterID Analyzer

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2025]
**Describe the bug**
It is not possible to cancel the DecompilerParameterID  analyzer.

**To Reproduce**
1. Start the DecompilerParameterID analyzer
2. Cancel the task
3. Notice the analyzer continue

**Expected behavior**
The analysis should stop when cancelled.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.329]
 - Java Version: 14.0.1
 - Ghidra Version: 9.2 bdbbca30a155502b79a38874c0186a7ac496dfeb

**Additional context**
The problem lies with `DecompilerParameterIdCmd` and the `ConcurrentGraphQ`

**Comment by dragonmacher** [comment]
This feels vaguely familiar.  I tweaked the messaging and cancellability of this code a bit in 30db29d. 

IIRC, the first phase of the analyzer is to build a dependency graph.  This was not checking for the cancelled state before my change.    Also, I noticed that when you cancel the analyzer, any functions being actively decompiled will continue, as the Decompiler is not getting the cancelled signal.   

Let us know if you are seeing something different.

**Comment by astrelsky** [comment]
> This feels vaguely familiar. I tweaked the messaging and cancellability of this code a bit in [30db29d](https://github.com/NationalSecurityAgency/ghidra/commit/30db29d1ce2a65c34f778032a3a2778ff42a397d).
> 
> IIRC, the first phase of the analyzer is to build a dependency graph. This was not checking for the cancelled state before my change. Also, I noticed that when you cancel the analyzer, any functions being actively decompiled will continue, as the Decompiler is not getting the cancelled signal.
> 
> Let us know if you are seeing something different.

I started debugging it to figure out where it wasn't being cancelled and couldn't reproduce it again. I'll try again another time and if I can't reproduce it again I'll close this.

**Comment by ryanmkurtz** [comment]
@astrelsky Is this ready to be closed?

**Comment by astrelsky** [comment]
> @astrelsky Is this ready to be closed?

1 year later... yes I forgot.
