### ISSUE TITLE
How to change tooltip delay time

### ISSUE THREAD

**Issue by shahril96** [NationalSecurityAgency/ghidra#2026]
Hi,

![image](https://user-images.githubusercontent.com/2675341/85413844-ec77f980-b59d-11ea-9746-9cbd7bfbeffd.png)

How can I change how long the tooltip is delayed before it being shown? I went searching into Options and can't find anything that refers to it (or I am just bad at searching thing :-)

In IDA, it shows much more faster (and unfortunately I am getting used to that :-)

**Comment by dragonmacher** [comment]
We do not have this as a tool option.  You can use a script to change this (you will have to run it each time you start Ghidra).

```
import javax.swing.ToolTipManager;

import ghidra.app.script.GhidraScript;

public class TooltipDelayScript extends GhidraScript {
	@Override
	public void run() throws Exception {
		ToolTipManager.sharedInstance().setInitialDelay(100);
	}

}
```
