### ISSUE TITLE
sleigh: inst_start evaluates to 0 in the bit pattern section

### ISSUE THREAD

**Issue by yatli** [NationalSecurityAgency/ghidra#2027]
I'm working on motorola dsp56k, and here is the primary rule in the instruction table to replicate the hardware do-loop behavior:

```
:^inst is inst & loopActive=1 & loopEnd=inst_start [loopActive=0; globalset(inst_next, loopActive);] { 
  build inst;
  lc = lc - 1;
  local tmp:3=ssh;
  if (lc == 0) goto <end_of_loop>; 
  goto [tmp];
  <end_of_loop>
  stack_pop(tmp, sr);
  stack_pop(la, lc);
}
```

In the pattern section I have `loopEnd=inst_start`, where `loopEnd` is a context variable set by a `do` instruction, and I compare it to the current instruction address to trigger the loop behavior. But it looks like this pattern is never hit because `inst_start` evaluates to 0 -- found this with the ghidra sleigh debugging script:

```
check pattern[1 of 2]: {line# 1729} <inst>
   context pattern: mask=11111111.11111111.11111111.10000000
          context(0..31)=00000000.00000001.01011100.10000000
             match-value=00000000.00000000.00000000.10000000 Failed
               loopActive(24,24) == 0x1 Match
               loopEnd(0,23) == 0x0 Failed (=0x15c)
check pattern[2 of 2]: {line# 1740} <inst>
   byte pattern: always-Matched
```

pattern 1 is the loop behavior, and pattern 2 is the fallback default (just build the instruction).

The debug output represents the decoding process of this code snippet:

![image](https://user-images.githubusercontent.com/20684720/85414275-7758f400-b59e-11ea-986e-99cd4019058b.png)

... where at 0x159 the `do` instruction activates loopActive(24, 24) and sets loopEnd(0, 23) properly to 0x15c, but at 0x15c, the context failed to match against a zeroed inst_start.

**Comment by ghidra1** [comment]
The use of inst_start and inst_next is not permitted within the pattern match.  Its use is only permitted within pcode and the [ ] section.

**Comment by emteere** [comment]
Suggest you try to use a LoopEnd bit in the context set at the LoopEnd address, instead of putting the whole address there.  This works if the LoopEnd address is computable when the loop starts.

Also suggest you use the Sleigh Editor within Eclipse.  This is a flagged as an error there.
