### ISSUE TITLE
Can't connect to Ghidra server ("Connection to server failed (...)")

### ISSUE THREAD

**Issue by VelocityRa** [NationalSecurityAgency/ghidra#2028]
**Describe the bug**
I've set up a Ghidra Server and noone else beside me can connect to it.
They get a "Server Error" (with my IP correctly resolved to a host name).

**To Reproduce**
- Set up a Ghidra Server with these settings
```
wrapper.app.parameter.1=-a0
wrapper.app.parameter.2=-u
wrapper.app.parameter.3=${ghidra.repositories.dir}
```
I've also tried adding another one with `-ipXXX` where XXX is my WAN IP.
I've changed `ghidra.repositories.dir` to an absolute one. I changed nothing else.
- Run `ghidraSvr console` from and Admin cmd prompt
- Get this
![image](https://user-images.githubusercontent.com/6632271/85442282-b1bf9280-b598-11ea-9830-d4bbb2b5a333.png)
- Get no additional messages in the log when anyone tries to connect (except me, and I can even use my WAN IP)

_Sidenote_: I have no clue what `Server remote access address: 100.90.213.27` is. That's not my WAN IP.

**Expected behavior**
Other people being able to connect to my server.

**Screenshots**
- The error on the clients
![image](https://user-images.githubusercontent.com/6632271/85441219-7f616580-b597-11ea-93dd-7dd85a3a7f24.png)

- I've opened ports 13100-13102 and they're correctly routed to my LAN IP (static `192.168.1.2`)
![image](https://user-images.githubusercontent.com/6632271/85441354-a5870580-b597-11ea-8d9e-18fe224d0c3d.png)

**Attachments**
[server.log](https://github.com/NationalSecurityAgency/ghidra/files/4821197/server.log)
[server.conf.txt](https://github.com/NationalSecurityAgency/ghidra/files/4821203/server.conf.txt)

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Java Version: We are all using `AdoptOpenJDK 11.0.7.10-hotspot`
 - Ghidra Version: We are all using 9.1.2

**Additional context**
- I **can** connect to my own server, even if I use my WAN IP (`85.75....`).
- https://canyouseeme.org/ can see my ports 13100-13102 being open
- When someone tries to connect to 13101 instead, I _do_ get something, some errors are printed to the console.
- I have not tried setting up a Ghidra server before, this is not a migration it's all fresh.

**Comment by ryanmkurtz** [comment]
Do you have any other IP interfaces active?  Perhaps Ghidra is binding to a different one and its IP is 100.90.213.27.

**Comment by ryanmkurtz** [comment]
Are you forwarding both UDP and TCP?

**Comment by VelocityRa** [comment]
> Do you have any other IP interfaces active? Perhaps Ghidra is binding to a different one and its IP is 100.90.213.27.
Oh, yeah I do have. Let me try to disable them. (though I'd imagine my using the `-ip` option before would get around that).

> Are you forwarding both UDP and TCP?
Yes. Also tried with just TCP initially.

**Comment by VelocityRa** [comment]
That fixed it! Thanks.
Is there a way to set which one Ghidra picks or do I have to disable everything else always?

**Comment by ryanmkurtz** [comment]
You can use the -i argument for that.

**Comment by VelocityRa** [comment]
Oh, that's what it's for. Thank you so much, have a nice day. :)

**Comment by 77920** [comment]
I'm doing the same thing as user above. On my Lan/Wan I can connect to my server but no one outside my home can. Forwarded 13100-13102 on both TCP/UDP fails to connect looking for help.

**Comment by ryanmkurtz** [comment]
Are you using the -i argument to bind to a specific interface?
