### ISSUE TITLE
Limit tooltip size

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2029]
**Is your feature request related to a problem? Please describe.**
<details><summary>tooltip screenshot</summary>

![Capture](https://user-images.githubusercontent.com/46897303/85490113-32818d00-b59f-11ea-96e5-8f9a65f02b9d.PNG)
</details>

**Additional context**
The size of my display is 1366x768, the tooltip's size was... 1366x768

**Comment by dragonmacher** [comment]
That is a bit excessive.   How did you generate this tooltip?

**Comment by astrelsky** [comment]
> That is a bit excessive.   How did you generate this tooltip?

It appeared when placing my mouse over the type in the DataType tree.

**Comment by pabx06** [comment]
look like i have same issue: tooltip of edit function Signature  i wanted to check the size of datatypehovering over it : but truncated as well. cant see the last line indicating the size

here :
![image](https://user-images.githubusercontent.com/4013370/96196276-48043380-0f4f-11eb-8458-bb74c57d979a.png)

it get rapidly annoying when trying to fix datatypes... 

may be a wrapping the tooltip with a JScrollPane  ?

**Comment by dragonmacher** [comment]
The data type tooltips should be truncated to a reasonable length.

For those that may be unaware, the Data Types provider has a preview window that you can open, which is placed below the data types tree.  This window shows what you see in the tooltip and provides some navigation capability.

**Comment by sad-dev** [comment]
I havn't used hover/tooltips pretty much since the start for pretty much this reason
