### ISSUE TITLE
Add docker support for ghidra

### ISSUE THREAD

**Issue by Kalanamith** [NationalSecurityAgency/ghidra#203]
It is essential to have the docker support and this will ensure to run the tool in a sandbox environment and easy to use.

**Comment by ryanmkurtz** [comment]
Can you be more specific?  Is there some aspect of Ghidra that is preventing it from working in a docker container or are you asking for official pre-made containers to be generated and distributed?  Thanks!

**Comment by d-millar** [comment]
Note also:
https://hub.docker.com/r/0xf15h/ghidra
https://github.com/kjcolley7/docker-ghidra-server

**Comment by ryanmkurtz** [comment]
Thanks @d-millar.  It looks like the community is already on top of the docker support.

**Comment by d-millar** [comment]
Update - also:
https://github.com/bskaggs/ghidra-docker
https://github.com/blacktop/docker-ghidra
