### ISSUE TITLE
What is a SourceType

### ISSUE THREAD

**Issue by TylerKann** [NationalSecurityAgency/ghidra#2031]
I am trying to do commitParamstoDatabase, and that requires a SourceType. Can anyone explain to me what it is, and an example of how i obtain one? 

Thank you!

**Comment by astrelsky** [comment]
[SourceType](https://ghidra.re/ghidra_docs/api/ghidra/program/model/symbol/SourceType.html) it is used a means of knowing who or what made the changes (user, importer, analyzer, etc). This way when an analyzer or something goes to make changes there is a means of preventing users modifications from being overwritten.

**Comment by TylerKann** [comment]
@astrelsky what "changes" ? Once I have the binary, who would be making these changes? I don't fully understand what that would mean. Would someone be modifying the binary? And what would the default one be if it is an unmodified binary? Thanks

**Comment by astrelsky** [comment]
> @astrelsky what "changes" ? Once I have the binary, who would be making these changes? I don't fully understand what that would mean. Would someone be modifying the binary?

Ghidra

> And what would the default one be if it is an unmodified binary? Thanks

`DEFAULT`
However, if YOU are applying changes then consider using `USER_DEFINED` so that your changes aren't overwritten when running the analyzers.

**Comment by TylerKann** [comment]
@astrelsky and then how exactly would I create this enum type? Would I just pass a string in place of the param? Or is there a specific function call with output of SourceType. Thank you

**Comment by astrelsky** [comment]
> @astrelsky and then how exactly would I create this enum type? Would I just pass a string in place of the param? Or is there a specific function call with output of SourceType. Thank you

```java
import ghidra.program.model.symbol.SourceType;
...
commitParamsToDatabase(highFunction, useDataTypes, SourceType.USER_DEFINED);
```

```python
from ghidra.program.model.symbol import SourceType
...
commitParamsToDatabase(highFunction, useDataTypes, SourceType.USER_DEFINED)
```

**Comment by TylerKann** [comment]
@astrelsky Thank you!
