### ISSUE TITLE
decompiler getHighFunction() returning None? 

### ISSUE THREAD

**Issue by TylerKann** [NationalSecurityAgency/ghidra#2032]
Can someone explain to me why getHighFunction() from a decompiler will give me None? Why does this happen and how can I fix/prevent it (I want to do it automatically so w/o the ghidra GUI) (this happens for multiple functions). Thank you!

```
iface = ghidra.app.decompiler.DecompInterface() 
f = getFirstFunction 
d = iface.decompileFunction(f, 5, None) #I am using none because I want this to be automatic w ghidra_bridge, hence no monitor 
type(d.getHighFunction()) # None 
```

**Comment by astrelsky** [comment]
There are a few problems here. One I suspect is just a typo but `f` is a python function object and not a ghidra Function as it should be `f = getFirstFunction()`. Another issue is that you need to have the decompInterface open the program. This, along with checking that f isn't None and that the the decompiler doesn't have an error should help get the results you are looking for. You must also be sure to invoke `dispose` on the decompInterface when you are finished to prevent a resource leak. 

I would recommend looking into the FlatDecompilerAPI as it is meant to make things easier for using the decompiler within a ghidra script.

**Comment by TylerKann** [comment]
Yep. It was the decompInterface. Thanks!
