### ISSUE TITLE
How does Ghidra keep track of addresses? 

### ISSUE THREAD

**Issue by TylerKann** [NationalSecurityAgency/ghidra#2037]
For example, if I open something in IDA it will show a value at 0000064a. If I open the same program in ghidra it will be 0010064a. In some spots its like 003... or 000.... . How can i convert from IDA/typical addresses to Ghidras address?

**Comment by saruman9** [comment]
Probably you want to change the Image Base address to 0. `Window` → `Memory Map` → `Set Image Base`.
![2020-06-26_08-12-55](https://user-images.githubusercontent.com/4244396/85822953-d9734e00-b784-11ea-98f9-15dbb0ca0804.png)

**Comment by TylerKann** [comment]
Is there a command to do this in a ghidra python script? Thanks @saruman9

**Comment by saruman9** [comment]
https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Program.html#setImageBase(ghidra.program.model.address.Address,boolean)

**Comment by TylerKann** [comment]
@saruman9 thanks!

**Comment by dev747368** [comment]
Also worth mentioning, its probably best to set the image base when importing the binary (check the "Options" button in the import dialog) before importing.  Ghidra tries to avoid a 000000 image base to help with analysis, but its totally up to you.
