### ISSUE TITLE
Are there any examples of headless anaylzer?

### ISSUE THREAD

**Issue by TylerKann** [NationalSecurityAgency/ghidra#2039]
I am trying to use ghidra / ghidra_bridge with the headless analyzer. There are very few/ no examples, and personally I find the API hard to read. I have a binary ptest in the ghidraRoot/support file . The project part also confuses me . I have this (note: I am the ghidraRoot/support dir) : 
`./analyzeHeadless /home autotest -import ./ptest -scriptPath /home/ghidra_scripts -postscript ghidra_bridge_server.py` 
but I get this error returned . 
` ERROR Abort due to Headless analyzer error: Unable to lock project! /home/autotest (HeadlessAnalyzer) java.io.IOException: Unable to lock project! /home/autotest
	at ghidra.framework.project.DefaultProjectManager.createProject(DefaultProjectManager.java:106)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:425)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:78)
`

Can someone please explain how to fix my error, as well as what `project directory` and `project` should be

**Comment by james-tate** [comment]
Looks like you need to close the GUI that probably has the project you are attempting to run the script on open. Close all instances of Ghidra and try to run the script.

**Comment by TylerKann** [comment]
I closed all instances ghidra.. still same error. @james-tate . What exactly should my project path/project be?

**Comment by james-tate** [comment]
I see. I assumed you already had a project created called autotest using the GUI, but that might not be the case. Have you already created a project, or are you trying to create a project with analyzeHeadless? 

This is not meant to be a plug, but I have a video here https://www.youtube.com/watch?v=ObLA0Za2PhY on using the analyzeheadless method. You can skip to ~13 minutes to the part I show an example on the headless analysis.

**Comment by TylerKann** [comment]
@james-tate  so in your example, in the project spot you said you are creating a repo. What does this mean exactly. Thanks
