### ISSUE TITLE
Fails to disassemble MIPS32 LE swr and swl instructions

### ISSUE THREAD

**Issue by 0xf15h** [NationalSecurityAgency/ghidra#204]
**Bug Description**
I've noticed that Ghidra is having issues disassembling MIPS32 little-endian swr and swl instructions.

**To Reproduce**
Try to disassemble:
030058a8 - swl $t8, 3($v0)
000058b8 - swr $t8, ($v0)

**Expected behavior**
Disassemble 030058a8 to `swl $t8, 3($v0)` and 000058b8 to `swr $t8, ($v0)`.

**Environment:**
 - OS: Ubuntu 18.04.2 LTS
 - Java Version: 11.0.2
 - Ghidra Version: 9.0

**Comment by mumbel** [comment]
Looks REL6 related in .sinc, works fine with MIPS:LE:32:default:default, but MIPS:LE:32:R6:default is broken

**Comment by emteere** [comment]
This is by design and correct behavior for MIPS 32 REL6.

From the Mips 6.04 manual:

**Format:** SWL rt, offset(base)  **MIPS32, removed in Release 6**
**Format:** SWR rt, offset(base) **MIPS32, removed in Release 6**

**Comment by emteere** [comment]
The normal thinking on processor modules when designed is to allow all instructions for different versions of the processor, unless there is some conflict with a previous version.  That way you can just use the latest version of the processor in most cases, however not in this case where it was explicitly made invalid in the latest R6.

I'll close this for now, unless you feel the instruction should be included in all variants.

**Comment by 0xf15h** [comment]
I'd like to keep this opened because I think Ghidra should support more than just R6. Buildroot's current default MIPS32 variant is R1 which leads me to believe a lot of low-end devices will not be compiled with R6.  
  
Source:   https://github.com/buildroot/buildroot/blob/0af24710da70b04947229333c9450c86499b3108/arch/Config.in.mips#L37  
  
Additionally, I think Ghidra should take after the Capstone disassembler which is a more mature project in terms of time being open source. Capstone supports both SWL and SWR.  
  
Source:  
https://github.com/aquynh/capstone/blob/4156eefd32479dbea8011612ff14a4946dbcc4a2/arch/Mips/MipsGenInstrInfo.inc#L1668  
https://github.com/aquynh/capstone/blob/4156eefd32479dbea8011612ff14a4946dbcc4a2/arch/Mips/MipsGenInstrInfo.inc#L1675

**Comment by mumbel** [comment]
You might be missing something here.

Your post said those 2 did not disassemble.  When I looked at the sinc the only way I noticed those not working was on REL6, if that isn't true then you should correct my assumption with the exact language variant.

If you are on rel6, then those instructions do not exist and nothing changes that. And would be a bug in capstone.

Ghidra supports more than just rel6 mips not sure where u got that idea from.

**Comment by 0xf15h** [comment]
You're right it does. I left the disassembler on the default `MIPS:LE:64:64-32addr-R6addr` when I should have been using `MIPS:LE:32:default`. Thank you @mumbel and @emteere for the help and I apologize for my misunderstanding.
