### ISSUE TITLE
Getting labeled instructions include register => using ./analyzeheadless

### ISSUE THREAD

**Issue by DeadShotCS** [NationalSecurityAgency/ghidra#2044]
Goes off of question issue #795 which involved getting labeled instructions the answer there was below.
`getCodeUnitFormat().getRepresentationString(currentProgram.getListing().getCodeUnitAt(currentAddress))`

This works to change addresses to their variable names, but I am unsure how to get the value of registers like in the GUI.

An instruction in the ghidra gui will look like:
`LEA RDI=>local_418,[RBP + -0x410]`

But when utilizing the original command will look like:
`LEA RDI,[RBP + -0x410]`

I am unsure what the `=>` directly means besides value, and I don't see a register getValue() in the api.

Any help would be greatly appreciated.

**Comment by mumbel** [comment]
`getInstructionAt(toAddr(0x001bd1d8)).toString()` gives me `ldrh.w r3,[sp,#0x76]` vs `ldrh.w     r3=>local_2a,[sp,#0x76]` in CodeBrowser

**Comment by DeadShotCS** [comment]
@mumbel yeah I'm trying to get the instruction with the `=>`. I would like to return `ldrh.w r3=>local_2a,[sp,#0x76]`, but I can't seem to figure out how to get.

**Comment by saruman9** [comment]
See the example [there](https://github.com/NationalSecurityAgency/ghidra/issues/569#issuecomment-489534590).

**Comment by DeadShotCS** [comment]
@saruman9 You are the best! Many thanks.
