### ISSUE TITLE
API Python goto() label rather than address

### ISSUE THREAD

**Issue by astewart43-gtri** [NationalSecurityAgency/ghidra#2047]
I am working on a script that interacts with the GUI. I have a list of addresses and labels. I am using the goto() function to jump to different locations in the binary.

I am doing this as follows:
```
addr_and_label = ['0001', '0002', 'label1', 'label2']

for I in addr_and_label:
    goto(currentProgram.addressFactory.getAddress(i))
```

This functions for the addresses, but obviously not for the labels as the .getAddress function takes in a string representation of an address. How do I go about getting the address of the label in the api?

I believe that this should be possible as the "goto" window (G shortcut) allows for inputting a label. I took a look at how this window handles this in ghidra.app.plugin.core.gotoquery, but was not able to figure it out.

**Comment by ryanmkurtz** [comment]
You can call this directly from your script:

```
	/**
	 * Returns a list of all the symbols with the given name in the given namespace.
	 * @param name the name of the symbols to retrieve.
	 * @param namespace the namespace containing the symbols, or null for the global namespace.
	 * @return a list of all the symbols with the given name in the given namespace.
	 */
	public final List<Symbol> getSymbols(String name, Namespace namespace) {
		return currentProgram.getSymbolTable().getSymbols(name, namespace);
	}
```

There is then another `goTo()` method that takes a `Symbol`.

**Comment by astewart43-gtri** [comment]
This seems to have solved my problem! Thank you.
As a followup question, I am just using "None" for the namespace. Will this cause any long term problems? It is my understanding that this will just have it search all name spaces.

**Comment by ryanmkurtz** [comment]
Using None will default to the global namespace, which is probably what you want.

**Comment by astewart43-gtri** [comment]
perfect. Thank you.
