### ISSUE TITLE
API to calculate the entropy of an executable

### ISSUE THREAD

**Issue by sajjadirn** [NationalSecurityAgency/ghidra#2048]
I am writing a python script for feature extraction and was wondering if there are any APIs which calculate the entropy of an executable as I couldn't find any.

**Comment by ryanmkurtz** [comment]
Ghidra uses `EntropyOverviewColorService` for this.  It looks like only an entropy color is exposed through the API though.  There's also the `EntropyCalculate` class, but nothing seems to use it, so I'm not sure what it's current state is (in terms of correctness).

**Comment by sajjadirn** [comment]
Thank you!
