### ISSUE TITLE
Adding support for non ASCII string

### ISSUE THREAD

**Issue by Godzil** [NationalSecurityAgency/ghidra#205]
**Is your feature request related to a problem? Please describe.**
Not all executable are using the same charset, some are using charset like JIS or other funny charset.
I can't find anywhere in Ghidra how to say "this is probably a string with this charset" and that would be really helpful to have such a functionality.

**Describe the solution you'd like**
Being able for a whole project, or on a per string basis the ability to set "this use or could use this charset"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dev747368** [comment]
Please check the help pages for strings and charset settings.
