### ISSUE TITLE
Calculating the Cyclic Complexity of each function.

### ISSUE THREAD

**Issue by sajjadirn** [NationalSecurityAgency/ghidra#2052]
I am writing a python script to iterate over every function and calculate it cyclic Complexity.
My code is :
```python
for func in currentProgram.getListing().getFunctions(True):
             print calculateCyclomaticComplexity(func,monitor)
```
but i get an error stating 
`TypeError: calculateCyclomaticComplexity(): expected 3 args; got 2`

But in the documentation it mentions we only need two arguments. 
Am I missing something?

**Comment by aerosoul94** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/util/CyclomaticComplexity.java#L38

Looks like `calculateCyclomaticComplexity()` is not a static method. In this case you need to create an instance of `CyclomaticComplexity `. There is an example script included in ghidra: 
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/ghidra_scripts/ComputeCyclomaticComplexity.java

**Comment by sajjadirn** [comment]
Thank you for your reply.
Do i need to do that even for python? Isn't importing it like ` from ghidra.program.util.CyclomaticComplexity import *` enough?

**Comment by ryanmkurtz** [comment]
That would only work if the calculateCyclomaticComplexity method was static.  It probably should be declared static, but since it wasn't, you'll need to instantiate a new object like @aerosoul94  said.

**Comment by sajjadirn** [comment]
Thank you, I got a bit confused. It works now!

**Comment by GhidorahRex** [comment]
I'm going to close this since the question was answered.
