### ISSUE TITLE
Should output a for loop

### ISSUE THREAD

**Issue by rfalke** [NationalSecurityAgency/ghidra#2053]
**Describe the bug**
Ghidra outputs a do-while-loop but a for-loop is more appropriate when the number of iterations is constant.

**To Reproduce**
1. Decompile https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/cfg/ia32_elf/subject.exe

**Expected behavior**
Output should look like
```
int basic_7_for_loop()
{
	for (int i = 0; i < 10; i++) {
		putchar('0' + i);
	}
	return 0;
}
```

It currently is:
```
undefined4 basic_7_for_loop(void)
{
  int __c;
  int iVar1;
  
  __c = 0x30;
  do {
    iVar1 = __c + 1;
    putchar(__c);
    __c = iVar1;
  } while (iVar1 != 0x3a);
  return 0;
}
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "11.0.5" 2019-10-15
 - Ghidra Version: 9.1.2_PUBLIC

**Additional context**
I'm not sure if this is a bug or a feature. IMHO it is an improvement.

**Comment by ryanmkurtz** [comment]
Duplicate of #644
