### ISSUE TITLE
val xor val => 0

### ISSUE THREAD

**Issue by rfalke** [NationalSecurityAgency/ghidra#2056]
**Describe the bug**
Ghidra doesn't implement this transformation which makes the output harder to understand

**To Reproduce**
1. Decompile https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/exp/ia32_elf/subject.exe

**Expected behavior**
Output should look like
```
undefined4 intermediate_4_swap_with_xor(uint param_1,uint param_2)

{  
  putchar(param_2);
  putchar(param_1);
  return 0;
}
```

It currently is:
```
undefined4 intermediate_4_swap_with_xor(uint param_1,uint param_2)

{
  uint __c;
  
  __c = param_2 ^ param_1 ^ param_2;
  putchar(param_1 ^ param_2 ^ __c);
  putchar(__c);
  return 0;
}
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "11.0.5" 2019-10-15
 - Ghidra Version: 9.1.2_PUBLIC

**Additional context**
I'm not sure if this is a bug or a feature. IMHO it is an improvement.

**Comment by Myshtea** [comment]
Yeah a xor chain handler is missing in this kind of situation.
Depending on the optimisation of your compiler it could or could not be handled and simplified.
After downloading you easily see this:

  __c = param_2 ^ **param_1 ^ param_2;**
  putchar(**param_1 ^ param_2** ^ __c);

The two bolded expressions are actually considered as the same varnode in the code so I think that the simplification rules aren't able to handle it by themselves as deleting the first bolded **param_2** would automatically delete the second bolded **param_2**.

I wrote a simplification rule to be able to simplify it by creating a new branch when deleting a Varnode so it's technically possible to do.

**Comment by rfalke** [comment]
But doesn't have addition also this problem? So if I have:
```
x=a+b-a
y=a+b-b
```
and "a+b" is a shared node I would still expect to end up with
```
x=b
y=a
```

**Comment by caheckman** [comment]
Added a rule specifically for the "swap" case in the original example.
