### ISSUE TITLE
Drag and Drop File import "Locks" Windows Explorer

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2058]
**Describe the bug**
Dragging and dropping a file from windows explorer into a ghidra project causes the windows explorer window to be "locked". Until "ok" or "cancel" is selected in the import dialog it is impossible to bring up the windows explorer window to view the directory contents.

**To Reproduce**
1. Drag and drop file into ghidra
2. Before selecting import settings, attempt to view the explorer window.

**Expected behavior**
Windows explorer should be unaffected by this operation

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.329]
 - Java Version: 14.0.1
 - Ghidra Version: 9.2 c5a31bb129944560f7d70deccb836c4f63349d82

**Additional context**
This has been occurring for a while I just hadn't reported it yet. I'm not certain if it is present in the public build or not.

**Comment by xiaoyinl** [comment]
Yes. This issue exists in Ghidra 9.1.2 public build too.

**Comment by dev747368** [comment]
fyi, something similar (but milder) happens to mac, the same change fixes both.
