### ISSUE TITLE
Segmentation fault after export binary file in Ghidra even without any changes

### ISSUE THREAD

**Issue by Zx-EvM** [NationalSecurityAgency/ghidra#2059]
I trying solve some https://crackmes.one/ simple quests. I newbie on it. But after export binary file (even without any changes), when I run the program in the terminal, I get the message "segmentation fault".

I use ghidra 9.1.2 in Kali Linux in VBox with 5 CPUs and 8 Gb RAM. Host: Ryzen 5 3600, 16 Gb DDR4.

I have record a video with demo of reproducing this issue: https://www.youtube.com/watch?v=M4RKXHRBNM8\

But I don't have such problems when I try solve windows `exe` crackmes on my host Windows 10 machine.

Also I note that after analysis in bookmarks appeared message with description: `Non-Returning Function Identified` with any crackmes.

**Comment by saruman9** [comment]
Duplicate of #19.

**Comment by Zx-EvM** [comment]
> Duplicate of #19.

But before import file I see `file filename` output that shows me that file ELF format.

Also loading as Raw Binary does not seem to produce the same analysis/disassembly output at all.

**Comment by Zx-EvM** [comment]
hm. I saw this message: https://github.com/NationalSecurityAgency/ghidra/issues/19#issuecomment-478396977

> The binary export is not intended to create a valid executable - there is no export for doing this. It simply dumps the memory blocks that exist within Ghidra void of any address placement information.

But how in this case I can execute my program after patching in Linux? 😑 On Windows this working properly although

**Comment by saruman9** [comment]
You can use the patch #1505 or script from the PR.

**Comment by Zx-EvM** [comment]
Okay. Looks this python script works for me (for now) https://github.com/NationalSecurityAgency/ghidra/issues/19#issuecomment-560485351 but we still need opportunity to patching binary files in Ghidra. I don't have thousands $ for IDA
