### ISSUE TITLE
Support for 16-bit Windows (Real & Protected Mode)

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#2063]
[DetectScan.xlsx](https://github.com/NationalSecurityAgency/ghidra/files/4864342/DetectScan.xlsx)

Hi

I am using the Ghidra tool (v9.1.2) to try and recreate an up-to-date version of an old Windows 16-bit tool.  When I import the executable into Ghidra, it won't load the dependent DLLs, even though they are in the path.  Am I doing anything wrong, or is there some more files I need to load into Ghidra before this support is available?

I have spoken to the company that produced the tool and they said that over the years and acquisitions they had "lost" the original source code!  In the included spreadsheet is a list of applications and trying to recreate and some information on the type of file that they are (this came from the tool "EXE Explorer x64" v 2.7.1.0 based upon "MiTeC PE Reader 2.4")

I have tried several methods, the first being to load just one executable in this case (VOICEBAR.EXE) into a new project whereupon I get the following errors in the "application.log":
----- Loading /D:/DDWIN302/VOICEBAR.EXE -----
  [DGNSRVR] -> not found
  [DGNSCRIP] -> not found
  [DRAGDEV] -> not found
  [COMMDLG] -> not found
  [GDI] -> not found
  [KERNEL] -> not found
  [KEYBOARD] -> not found
  [LZEXPAND] -> not found
  [MMSYSTEM] -> not found
  [SHELL] -> not found
  [TOOLHELP] -> not found
  [USER] -> not found
  [WIN87EM] -> not found

I then tried importing all the independent DLLs and EXEs required by the application (including Windows 16-bit DLLs and EXEs) into the project first, but that didn't have the desired effect either.

Can you point me in the right direction please?

FYI, I have a copy of the old MSVC 1.51 with the Windows include files and the debug EXEs and symbol files.

**Comment by mumbel** [comment]
Are your DLL names matching whats not found?  for example `DGNSRVR` is not the same as `DGNSRVR.DLL`, `Dgnsrvr`, `Dgnsrvr.dll` , `dgnsrvr` or `dgnsrvr.dll` (or whatever extension it might have).  I came across a similar issue in #906 

(your title does not seem match this issue at all btw)

**Comment by Wall-AF** [comment]
Fantastic.  I saw that issue, but I was looking for a more complicated solution!

For reference, I just went ito the directories containing these files and ran the following commands:
DIR *.
COPY *.DLL *.
COPY *.EXE *.

The initial "DIR *." just checks for any existing files wih no extension so you don't accidentally overwrite one!
