### ISSUE TITLE
Extracting Symbols used by each Namespace 

### ISSUE THREAD

**Issue by sajjadirn** [NationalSecurityAgency/ghidra#2064]
I am writing a python script to extract all the external symbols used by an exe file 
Currently I am able to extract all the external symbols using 
```python
sm = currentProgram.getSymbolTable()
symb = sm.getExternalSymbols()
```
What I want to do is, extract all the symbols based on the DLL they are in.
For example if an EXE uses KERNEL32.DLL and MSVCRT.DLL i want to extract all the symbols under each DLL

I was not able to file any function which extracts all the Namespaces used in an EXE
I found 
`getNamespace​(Address addr)` 
but this requires an address

Is there a way where I can get all the Namespaces and use
`getSymbols​(Namespace namespace)`

to iterate over every symbol in that namespace

**Comment by astrelsky** [comment]
You can use [ExternalManager.getExternalLibrary(String)](https://ghidra.re/ghidra_docs/api/ghidra/program/model/symbol/ExternalManager.html#getExternalLibrary(java.lang.String)). You can then use the returned library as a Namespace

**Comment by sajjadirn** [comment]
@astrelsky Thank you, that was what I needed.
What I did was, I used `getExternalLibraryNames()` which returned all the external libraries and used that as input for `getSymbols`

**Comment by ghidra1** [comment]
From a library "name" you will need to get the library "namespace" using ```getExternalLibrary(String libraryName)``` then get the symbols associated with namespace using the symbol manager.  Alternatively, for each library "name" you can use the ```getExternalLocations(String libraryName)```.
