### ISSUE TITLE
Is it possible to convert a physical address to a logical address with ghidra python?

### ISSUE THREAD

**Issue by Te-k** [NationalSecurityAgency/ghidra#2067]
Hi,

I am trying to fix a bug in a python Ghidra script and I need to convert a physical address in the PE file into a logical address, to add a bookmark and comment. The only thing I would need for that is to access the raw address of the sections.
This information is available in the memory map Windows since lat year, and the list of sections is available in python with `currentProgram.getMemory().getBlocks()` but I could not find any way to get access to the raw address of the sections in python. 

Is it possible to do that?

**Comment by ryanmkurtz** [comment]
From a `MemoryBlock` you can call `getSourceInfos()`, which returns a list of `MemoryBlockSourceInfo`'s.  You can examine the source info for each memory block until you find the one that contains your file offset (physical address).  You can then add the proper offset to the corresponding block's start address to get the logical address.

**Comment by astrelsky** [comment]
> From a `MemoryBlock` you can call `getSourceInfos()`, which returns a list of `MemoryBlockSourceInfo`'s. You can examine the source info for each memory block until you find the one that contains your file offset (physical address). You can then add the proper offset to the corresponding block's start address to get the logical address.

Once you have the MemoryBlockSourceInfo which contains the address you can then use [MemoryBlockSourceInfo.getFileBytesOffset(Address)](https://ghidra.re/ghidra_docs/api/ghidra/program/model/mem/MemoryBlockSourceInfo.html#getFileBytesOffset(ghidra.program.model.address.Address)). I'm currently using the below to go the other way (file offset to address).
mem is a Memory instance.
```java
Address findAddress(long offset) {
	return Arrays.stream(mem.getBlocks())
		.filter(Predicate.not(MemoryBlock::isMapped))
		.filter(MemoryBlock::isInitialized)
		.map(MemoryBlock::getSourceInfos)
		.flatMap(List::stream)
		.filter(info -> containsOffset(info, offset))
		.findFirst()
		.map(info -> getAddress(info, offset))
		.orElse(null);
}
```

**Comment by Te-k** [comment]
It worked, thanks a lot !
