### ISSUE TITLE
Is it possible to merge files?

### ISSUE THREAD

**Issue by VelocityRa** [NationalSecurityAgency/ghidra#2069]
Ghidra supports merging in shared projects when you check files in/out, but is it possible to **merge a file to _another_ one** at will?

The only reason I need this is because I was working on a file with another person, he made some changes, I wanted to check them in, I got a file I/O error, and my changes got moved to a .keep file.

So I can't merge them to the main project now.
I have to do it by hand, or we lose commit history.

This or similar bugs have happened to us other times too.
If we could merge projects it could at least provide a workaround without much manual/duplicated work.

**Comment by TheOnlyZac** [comment]
This issue has plagued my project multiple times. I try to merge my changes with the latest version from the server, but a file I/O error occurs during the merge which results in all my local changes disappearing. Hours of work down the drain, even though I save religiously.

Of course, all my changes are still there in the .keep file, but I can't find any way to merge those changes back into the actual project file. I have no choice but to meticulously copy and paste every little change in every symbol, comment, type assignment, etc.

**Comment by saruman9** [comment]
For merging/diffing the same files you can use the Diff View. You can use the Version Tracking tool for merging the files with some differences (for example, updated versions, patched files).

**Comment by VelocityRa** [comment]
We found it:

Open the main file in Code Browser, in the menubar go to Tools > Program Differences and select the file you want to merge onto it.

**Comment by TheOnlyZac** [comment]
> For merging/diffing the same files you can use the Diff View. You can use the Version Tracking tool for merging the files with some differences (for example, updated versions, patched files).

It took me a while to realize what you meant by "merging/diffing the same files" because from my POV I had two distinct files I was trying to merge, but I once I realized the Diff View was the way to go rather than version control, it became clear. Thanks.
