### ISSUE TITLE
Any way to show full asm in Function Graph? (getting cut off with ...)

### ISSUE THREAD

**Issue by LWSS** [NationalSecurityAgency/ghidra#207]
![cutoff](https://i.imgur.com/sx6nZjN.png)

Notice how the text is getting cut off with ....

Is there any way to get it to show the full lines in graph view?

**Comment by ryanmkurtz** [comment]
Check out issue #99.  Does that fix it for you?

**Comment by LWSS** [comment]
Yes it does, thank you.

This program has a ton of neat options
