### ISSUE TITLE
TypeDescriptorModel.hasVFPointer Poor Performance

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2075]
![results](https://user-images.githubusercontent.com/46897303/86861387-008b2300-c095-11ea-9b56-30135cde05ef.PNG)

[profile.zip](https://github.com/NationalSecurityAgency/ghidra/files/4887813/profile.zip)

**Additional context**
https://github.com/NationalSecurityAgency/ghidra/blob/c5a31bb129944560f7d70deccb836c4f63349d82/Ghidra/Features/MicrosoftCodeAnalyzer/src/main/java/ghidra/app/cmd/data/TypeDescriptorModel.java#L255-L259

The method short circuits when it is 64-bit but will run `Memory.findBytes` every time on a 32 bit program.

As for resolving this I think the following approach would be best:

* Check the Program's DataTypeManager for the existance of `TypeDescriptor` and verify it before recreating the Structure.
* Remove the `hasVFPointer` field and instead use the `VF_TABLE_OR_HASH_ORDINAL` component of the datatype.

Also while not entirely relevant my `WindowsCppClassAnalyzer` was only 6% complete when I decided I had enough data.

For even more context, I hardcoded `TypeDescriptorModel.hasVFPointer(Program)` to return true, which is ok for the program I'm testing. I reached the same point as I did when I canceled it before in 27 seconds.

**Comment by emteere** [comment]
Searching for that magic string really should only have been done once for the program.  I see other places it could have been called.  Your Analyzer must be causing this code to get exercised more than in existing code.  It should be gotten rid of.

I'll take a look.

**Comment by astrelsky** [comment]
> Searching for that magic string really should only have been done once for the program. I see other places it could have been called. Your Analyzer must be causing this code to get exercised more than in existing code. It should be gotten rid of.
> 
> I'll take a look.

It currently happens every time `TypeDescriptorModel::new` is invoked, which I do a lot.

**Comment by astrelsky** [comment]
@emteere searching the symbol table for the typeinfo type descriptor may also be an appropriate way of avoiding the memory search.
