### ISSUE TITLE
Ghidra can't handle extra large functions

### ISSUE THREAD

**Issue by chago** [NationalSecurityAgency/ghidra#2076]
Ghidra has been running for a day and night and has not been decompiled

Example:
Platform: AARCH64
Format: Crop binary

Ghidra:
<img width="1440" alt="截屏2020-07-08 上午10 27 09" src="https://user-images.githubusercontent.com/2239471/86867565-9eb6d180-c105-11ea-93af-0cfbc29a4695.png">

IDA:
<img width="858" alt="截屏2020-07-08 上午10 20 13" src="https://user-images.githubusercontent.com/2239471/86867040-b477c700-c104-11ea-8ecc-e3cd138745a4.png">

File:
[Example.zip](https://github.com/NationalSecurityAgency/ghidra/files/4888081/Example.zip)

**Comment by caheckman** [comment]
Reproducing.  Looks like a combinatorial problem.

**Comment by caheckman** [comment]
Should be fixed in master now.  Thanks for reporting this.

**Comment by chago** [comment]
It done ,think you!
