### ISSUE TITLE
Specifying the number of files to analyze to headless analyzer 

### ISSUE THREAD

**Issue by sajjadirn** [NationalSecurityAgency/ghidra#2078]
I wrote a script and I want to run it using headless analyzer.
My import folder contains around 9k files, but I want to run the script only on 1000 files at first.
Is there a way where I can specify this while running the script in headless analysis mode?

**Comment by ryanmkurtz** [comment]
If you extend `HeadlessScript` instead of `GhidraScript`, you can use some of the following methods from `HeadlessScript` to keep track of how many things you've processed, and then abort when you've reached your limit:

```
- storeHeadlessValue()
- getStoredHeadlessValue()
- setHeadlessContinuationOption()
```

This will only work if you write your script in Java.

**Comment by sajjadirn** [comment]
@ryanmkurtz Thank you for your reply.
My script is in python, so there is no workaround for python?

**Comment by ryanmkurtz** [comment]
`PythonScript`'s are stuck extending `GhidraScript`, so nothing I said above is applicable.  I don't have any Python-specific ideas...sorry.

**Comment by sajjadirn** [comment]
@ryanmkurtz no problem, thank you
