### ISSUE TITLE
byte mapped Memory maps and hexEditor view

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2080]
i was wondering why 'byte mapped memory map' are display as 'undefined bytes' in the hex view :

this make it hard to spot strings that ghidra analysis missed...

![image](https://user-images.githubusercontent.com/4013370/86953707-13652c80-c155-11ea-8043-bac5ba4b158a.png)

![image](https://user-images.githubusercontent.com/4013370/86953838-4b6c6f80-c155-11ea-89ad-0e38fd4ad8db.png)

**Comment by dev747368** [comment]
The byte viewer is incorrectly tagging these blocks as un-initialized and therefore displays them as ??s.  Tis a simple fix, hopefully will be available soon.

**Comment by ghidra1** [comment]
This has been resolved for Ghidra 7.2 and is contained in the master development branch.
