### ISSUE TITLE
assertThisIsABackgroundThread

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2081]
... and my description got nuked. 

Anyway I think a utility method similar to [SystemUtilities.assertThisIsTheSwingThread](https://ghidra.re/ghidra_docs/api/ghidra/util/SystemUtilities.html#assertThisIsTheSwingThread(java.lang.String)) may be useful.

**Comment by dragonmacher** [comment]
The above method now delegates to `Swing.assertSwingThread()`.   Are you requesting something as simple as `Swing.assertNotSwingThread`?

**Comment by astrelsky** [comment]
> The above method now delegates to `Swing.assertSwingThread()`. Are you requesting something as simple as `Swing.assertNotSwingThread`?
> 
> How would you like to use this method?

I'm more or less just looking to ensure that a piece of code is running in a ghidra Background-Task. This may be as simple as the following.

```java

public static void assertThisIsTheSwingThread(String errorMessage) {
	boolean isProductionMode = !isInTestingMode() && !isInDevelopmentMode();
	if (isProductionMode) {
		return; // squash during production mode
	}

	if (!Thread.currentThread().getName().startsWith("Background-Task")) {
		Throwable t =
			ReflectionUtilities.filterJavaThrowable(new AssertException(errorMessage));
		Msg.error(SystemUtilities.class, errorMessage, t);
	}
}
```

**Comment by astrelsky** [comment]
Nevermind, I guess checking would just be `!SystemUtilities.isEventDispatchThread()`
