### ISSUE TITLE
24 hour "changeme" password

### ISSUE THREAD

**Issue by Ekultek** [NationalSecurityAgency/ghidra#2090]
If the password isn't changed in 24 hours, what happens to the account? Does the password get randomly generated, or does the account get deleted? 

If randomly generated where is it stored so that i can provide it to the user?

**Comment by ghidra1** [comment]
The account gets locked and requires the Ghidra Server administrator to run ```svrAdmin -reset <userSID>``` to reset the password.  The expiration period may be set with the server -e configuration parameter but is 24-hours by default.

**Comment by Ekultek** [comment]
Thank you
