### ISSUE TITLE
[Feature Request] Display Plate comments for structure members

### ISSUE THREAD

**Issue by VelocityRa** [NationalSecurityAgency/ghidra#2091]
**Describe the bug**
* I had some Plate comments.
* I made a struct that started before them, which included those fields that had the plate comments.
* The plate comments **don't show up** anymore, but they're still there if I open to the Comments dialog.

**Expected behavior**
My comments to show up in the assembly listing.

**Screenshots**
Here's the comment that exists but doesn't appear in the listing.
![image](https://user-images.githubusercontent.com/6632271/87245756-b4ebc700-c450-11ea-9c05-a6ba3f7017ea.png)

**Environment (please complete the following information):**
 - OS: Win 10
 - Java Version: 11.0.7
 - Ghidra Version: 9.1.2

**Comment by dragonmacher** [comment]
This is currently working as designed.    Ghidra does not show plate comments for structure members.   

If you would like it to work differently, then we could consider this a feature request.    I'm assuming it was decided in the past that showing plate comments for structure fields would make the UI messy.   How would you like them to be displayed?

**Comment by VelocityRa** [comment]
> If you would like it to work differently, then we could consider this a feature request.

Yeah I should have probably submitted it as a feature request. I will edit the post.

> I'm assuming it was decided in the past that showing plate comments for structure fields would make the UI messy. How would you like them to be displayed?

I'm not sure how would it look messier for structured members.
Unless I'm missing something, they can be displayed the same way as they are for non-structured members - in the same block, of text, above the assembly line.

**Comment by dragonmacher** [comment]
The field factory for the 'Open Data' field does not allow users to add the plate comment field.   This may be a simple fix.
