### ISSUE TITLE
SH-2A fldi0 and fldi1 operations fail to disassemble

### ISSUE THREAD

**Issue by a33b** [NationalSecurityAgency/ghidra#2092]
When using SH-2A language, fldi0 and fldi1 operations fail to disassemble. Attempting to patch the instruction does bring up the operations as options, but Ghidra does not recognize the operation as valid.

**Environment:**
 - OS: Win 10
 - Java Version: OpenJDK 11.0.7
 - Ghidra Version: 9.1.2

![Image 121](https://user-images.githubusercontent.com/34362613/87381985-2e6bde00-c553-11ea-8f62-b6ec9871ee14.png)

**Comment by GhidorahRex** [comment]
The instruction set documentation gives the fldi0 and fldi1 instructions as 0x8d and 0x9d respectively. Where did the 0x3d byte come from?

**Comment by mumbel** [comment]
for some reason, `fldi1` does not like  ctrl+alt+g  when frN is odd ... which doesn't make sense at first glance

**Comment by GhidorahRex** [comment]
Do you mean ctrl+shift+g for patch instruction? I don't know of a default key-binding for ctrl+alt+g.

Incidentally, I tested ctrl+shift+g with frN odd (fr9) and it worked fine.

**Comment by mumbel** [comment]
Yeah, sorry, had it in my head wrong s/alt/shift/g when I typed it out

Are you on master or it worked in 9.1.2 (I don't have a dev setup ATM)?

fixed by #1265 (not sure if there is a dup issue)

**Comment by GhidorahRex** [comment]
Yes, I'm on master. That makes sense. It wouldn't be able to parse the instruction if the low-order bit of the register must be 0. That also causes the fldi instructions to fail to disassemble with odd registers. So this is likely a duplicate.

**Comment by a33b** [comment]
So this bug will be addressed in Ghidra 9.2 if I understand correctly? Sorry for the duplicate, didn't see it in the open issues.

**Comment by GhidorahRex** [comment]
That's correct. It's already been addressed in master, just not in a current release. If you want to fix it locally, replace the line `fop_00_07 =  (0,  8)` with `fop_00_07 =  (0,  7)` in `Processors/SuperH/data/languages/superh.sinc`

I'm going to mark this issue as closed for now.
