### ISSUE TITLE
Ghidra SDK: commit function parameters into DB via API

### ISSUE THREAD

**Issue by milsegv** [NationalSecurityAgency/ghidra#2098]
Hello !

I am trying to get the Ghidra API to auto-analyze a function, guess the parameters and commit it into the ghidra analysis database for further inspection. I have tried the solution described [here](https://github.com/saruman9/ghidra_scripts/blob/288a2226893fd6801f1234971eef99b69590547e/CommitParamsReturn.java#L58-L59) but couldn't make it work .... 

Here is the simplified code sample I am working on:

```java
Program prog = currentProgram;
DecompInterface decomp = new DecompInterface();
decomp.openProgram(prog);
FunctionManager functions = prog.getFunctionManager();
for (Function f: functions) {
	DecompileResults decomp_res = decomp.decompileFunction(f, 30, null);
	HighFunction hf = decomp_res.getHighFunction();
	HighFunctionDBUtil.commitReturnToDatabase(hf, SourceType.ANALYSIS);
	try {
		HighFunctionDBUtil.commitParamsToDatabase(hf, true, SourceType.ANALYSIS);
	} catch (DuplicateNameException e) {
		e.printStackTrace();
	} catch (InvalidInputException e) {
		e.printStackTrace();
	}
	for (Parameter p: f.getParameters()) {
		println(p.toString()); // This prints nothing as f.getParameters() returns an empty array
	}
}
```
As indicated, `f.getParameters()` returns an empty array, even when functions in the binary I'm analyzing have parameters.
Do you have any idea on how to get the API to successfully commit parameters definitions into database ?

**Comment by ghidra1** [comment]
It certainly looks like it should work.  Have you stepped through with debug to verify what gets pushed to the function.updateFunction method invoked by HighFunctionDBUtil?

**Comment by milsegv** [comment]
All right, after rebooting my computer this seems to work, thanks for your time !
