### ISSUE TITLE
How do I get the address along with the instructions using the API?

### ISSUE THREAD

**Issue by sajjadirn** [NationalSecurityAgency/ghidra#2099]
I have this python code which extracts all the instructions.
```python
for instr in currentProgram.getListing().getInstructions(True): 
    instructionList.append(instr)
```
This gets me the output like 
`PUSH EBP`

But I want the output to have the address too, like

`00401000 PUSH EBP`

How do I get the output in this format?

**Comment by ryanmkurtz** [comment]
Try working with code units instead of instructions.  You can iterate over the code units with currentProgram.getListing().getCodeUnits().

**Comment by ghidra1** [comment]
Instructions are CodeUnits.  The toString methods do not include address info.  You will need to format the output as needed.  The address can be obtained from the instruction, instruction.getAddress(), and prepended to the instruction representation you are currently getting.

**Comment by ghidra1** [comment]
There are few methods, although they are all subject to the manner that an instruction has been implemented.  In general, if an operand only shows a single register you may be able to use the method `Instruction.getRegister(int opIndex)`.  If it is complex operand you can sift through the operand representation list using `Instruction.getDefaultOperandRepresentationList()` looking for `Register` objects.
