### ISSUE TITLE
Where do function names come from for "Non-Returning Functions - Known"

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2101]
The **Non-Returning Functions - Known** analyzer "Locates known functions by name, that generally do not return (exit, abort, etc)…".
![Capto_Capture 2020-07-15_12-52-42_PM](https://user-images.githubusercontent.com/52077/87572841-21a5d200-c69a-11ea-8fe2-92fca6b84d65.png)

Only two such functions are explicitly named here: `exit` and `abort`.

- Are these and any remaining "known" function names enumerated somewhere? 
  This information should be documented, either in Ghidra's Help or in the analyzer's **Description**.
  If you think that merits a formal improvement request, I can create one.

- Can the list of known functions easily be changed by the user?

**Comment by ryanmkurtz** [comment]
The are defined per loader:

[ELF](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/data/ElfFunctionsThatDoNotReturn)
[MachO](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/data/MachOFunctionsThatDoNotReturn)
[PE](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/data/PEFunctionsThatDoNotReturn)

**Comment by astrelsky** [comment]
If you would like to define your own for a custom loader the program property for which file to use is "functionNamesFile".

**Comment by ryanmkurtz** [comment]
Yes, what you say is true.  The problem is highlighted in the ELF case, because so many different things use ELF.

**Comment by gtackett** [comment]
> The problem is highlighted in the ELF case, _etc_

By this, Ryan tells me he means that the way this works is especially problematic for ELF binaries.

I have enough information now to close this specific ticket.

But I'll follow up with a ticket about non-exiting functions when using BinaryLoader.

**Comment by ghidra1** [comment]
See #2103 where I have discussed some ways of adding your own non-returning function data files with additional constraints when that data file should be used.
