### ISSUE TITLE
Is there anyway to get analyzeHeadless to spit out a gzf file? or a gar file?

### ISSUE THREAD

**Issue by DootBoi** [NationalSecurityAgency/ghidra#2104]
Trying to automate some analysis and want to be able to easily package it up into a gzf file post-processing. Currently I am just reopening in the gui and using the File -> Export option.

**Comment by ghidra1** [comment]
Assuming the associated DomainFile has been saved, you can invoke the DomainFile.packFile method.  Program DomainFiles would correspond to *.gzf.  This could be accomplished via a suitable Ghidra script run by analyzeHeadless.

Unfortunately, the ArchiveTask which generates project archives (*.gar) is not exposed for API use.

**Comment by beigela** [comment]
Here's a quick implementation of what ghidra1 described.

`<ghidra_scripts>/export_to_gzf.py`
```
from java.io import File

prog = getCurrentProgram()
df = prog.getDomainFile()
outfile = File("output.gzf")
df.packFile(outfile, monitor)
```

Run with:
```
<ghidra>/support/analyzeHeadless <ghidra_projects> <project>/<file_path_in_project> -noanalysis -scriptPath <ghidra_scripts> -postScript export_to_gzf.py
```

It'll create a gzf called `output.gzf` in the current directory.

**Comment by SourceCodeDeleted** [comment]
I receive this when I run this 

`ghidra.util.ReadOnlyException: ghidra.util.ReadOnlyException: Read-only DB directory lock, file creation not allowed: output1.gzf
`

**Comment by crashingstatic** [comment]
I'm getting the following error with your script and Googling isn't getting me anywhere. Any ideas?

```
INFO  SCRIPT: /root/ghidra_scripts/export_to_gzf.py (HeadlessAnalyzer)
Traceback (most recent call last):
  File "/root/ghidra_scripts/export_to_gzf.py", line 6, in <module>
    df.packFile(outfile, monitor)
        at db.DBHandle.saveAs(DBHandle.java:772)
        at db.DBHandle.saveAs(DBHandle.java:862)
        at ghidra.framework.store.db.PackedDatabase.packDatabase(PackedDatabase.java:625)
        at ghidra.framework.data.DomainFileProxy.packFile(DomainFileProxy.java:541)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
ghidra.util.exception.AssertException: ghidra.util.exception.AssertException: Can't save during transaction
```

**Comment by ghidra1** [comment]
Scripts by default have an open transaction on the current program.  You must first end that transaction and possibly save/saveAs to DomainFile before invoking the pack method.   Any subsequent changes to `currentProgram` would require starting the transaction first.
```
// end current transaction
end(true);
		
// Save any unsaved changes
if (currentProgram.canSave()) {
	currentProgram.save("saved changes before packing", monitor);
}
		
currentProgram.getDomainFile().packFile(new File(currentProgram.getName() + ".gzf"), monitor);
```
