### ISSUE TITLE
pdb.exe recompile failed msb3073

### ISSUE THREAD

**Issue by iggymazda** [NationalSecurityAgency/ghidra#2113]
**Describe the bug**
rebuild of pdb.exe failed. with the following code and description:

msb3073, 

The command "
rem copy /y /v /b "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\DIA SDK\bin\amd64\msdia*.dll" "C:\tools\ghidra_9.1.2_PUBLIC\Ghidra\Features\PDB\src\pdb\..\..\build\os\win64\"
set OS_DIR=C:\tools\ghidra_9.1.2_PUBLIC\Ghidra\Features\PDB\src\pdb\..\..\os
if exist "%OS_DIR%\win64" (
   mkdir "%OS_DIR%"
   mkdir "%OS_DIR%\win64"
   xcopy /Y /S "C:\tools\ghidra_9.1.2_PUBLIC\Ghidra\Features\PDB\src\pdb\..\..\build\os\win64\" "%OS_DIR%"
)
  
:VCEnd" exited with code 4.	pdb	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	149	

**To Reproduce**
1. Open Ghidra\Features\PDB\src\pdb\pdb.vcxproj in Visual studio
2. Right click on pdb in "solution explorer" 
3.  Select "retarget projects" 
4. Scroll down to '10.0(latest Version)'
5 Select OK
6. In the menu bar click 'build'
7. Select 'rebuild solution'
8 error shows up in 'error list' once compile fails. 

[pdb.zip](https://github.com/NationalSecurityAgency/ghidra/files/4939647/pdb.zip)
![pdb compile error](https://user-images.githubusercontent.com/68409523/87821087-decc3180-c834-11ea-8c4f-9bb569953594.PNG)

**Expected behavior**
recompile pdb.exe

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Win10 Pro version 1909
 - Java Version: 8  build 1.8.0_251-b08
 - Ghidra Version:  9.1.2
- Microsoft Visual Studio Community 2019
Version 16.6.4

**Additional context**

**Comment by ghizard** [comment]
I suspect that the issue is that build of PDB.exe for Ghidra 9.1.2 does not support VS 2019 tool chain. See #999 where support for VS 2019 seems to be ready for Ghidra 9.2. If I recall, new data is passed in more recent PDB.exe processing, so PDB.exe from Ghidra 9.2 likely will not work with Ghidra 9.1.2.

**Comment by ghizard** [comment]
https://github.com/NationalSecurityAgency/ghidra/pull/1032 is what allowed the build with VS2019, and that was merged in for Ghidra 9.2.
