### ISSUE TITLE
Font rendering is really bad on linux

### ISSUE THREAD

**Issue by TomJansen** [NationalSecurityAgency/ghidra#212]
**Describe the bug**
When running Ghidra, the font rendering is really bad on Linux (have not tested on other OSes).

**To Reproduce**
1. Start Ghidra
2. Notice the bad font rendering

**Expected behavior**
Clear and readable fonts

**Environment:**
 - OS: Arch Linux
 - Java Version: 11.0.2
 - Ghidra Version: 9.0-3

**Solution**
This issue can be fixed by adding `VMARG_LIST+="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"` in `launch.sh` (I added this on line 114 in `launch.sh`).

Before:
![pic-window-190316-1553-49](https://user-images.githubusercontent.com/2716208/54476936-3e5e9b00-4803-11e9-944b-3e9803c04279.png)

After adding the line:
![pic-window-190316-1556-01](https://user-images.githubusercontent.com/2716208/54476985-92697f80-4803-11e9-852c-4c327d9ecdff.png)

Can this line be included standard in the package?

**Comment by ryanmkurtz** [comment]
If you just do `-Dswing.aatext=true"`, does that improve it?  Or do you also need to add the `-Dawt.useSystemAAFontSettings=on`?

**Comment by ryanmkurtz** [comment]
Also, if you just do `-Dawt.useSystemAAFontSettings=on`, does that improve it?  Or do you also need to add the `-Dswing.aatext=true`

**Comment by ryanmkurtz** [comment]
In our next release, `-Dawt.useSystemAAFontSettings=on` will be set in support/launch.properties.  `-Dswing.aatext=true` doesn't seem to be necessary.

**Comment by TomJansen** [comment]
Yes, I can confirm that `-Dswing.aatext=true` is not necessary. Thanks!

**Comment by ryanmkurtz** [comment]
Thanks for double checking on that!

**Comment by mbana** [comment]
There is something definitely up with the font rendering of, at least, the Flatpak distributed version of the application. Links: 

1. <https://flathub.org/apps/org.ghidra_sre.Ghidra>
2. <https://github.com/flathub/org.ghidra_sre.Ghidra>

I am not sure this is specific to Flatpak though.

Could we please keep this issue open?

**Comment by ryanmkurtz** [comment]
@mbana I don't think it makes sense to reopen it unless you provide more info that demonstrates your issue, so that we could potentially take an action. Useful things would be:
* A screen shot of your bad font rendering.
* Info about your linux distro
* Your `launch.properties` file
* Confirmation that the official Ghidra distro is showing the problem
