### ISSUE TITLE
Add a Count Leading Zeroes PcodeOp?

### ISSUE THREAD

**Issue by hedgeberg** [NationalSecurityAgency/ghidra#2121]
**Is your feature request related to a problem? Please describe.**
Currently working on my 4th SLEIGH spec, and each architecture I've designed a SLEIGH spec for thus far has had some kind of instruction that counts leading zeroes. Counting leading zeroes requires generating a large body of pcode in the form of a loop, which the decompiler struggles to optimize away cleanly. 

**Describe the solution you'd like**
Adding a new pcodeop for the purpose of the Count Leading Zeroes operation would significantly improve the decompilation output around this operation, especially since most architectures implement this behavior using just asynchronous gates, so in hardware this operation is usually atomic. If we assume that there should be a pcodeop for each "fundamental" building block of instructions, the lack of a count leading zeroes pcode is a significant vacancy. It would be much easier to generate good decompiler output if this operation could be reduced to a single pcode.

**Describe alternatives you've considered**
It's possible to manually define a pcodeop, or just live with the output, but manually defining a pcodeop will not provide good output from the decompiler since context propagation terminates on manually defined pcode ops. It's also possible to just live with the decompiler output, but it could be significantly better with this change.

**Comment by ghidra1** [comment]
The accepted solution is to create a user pcodeop and treat as a function call.  Generally you don't want to see such an operation as a function call in the C decompiled output instead of a bunch of confusing pcode.  The pcode propogation should work if you specify the correction inputs and output when using the pcodeop:
`
RDest = countLeadingZeros(RSrc);
`

**Comment by hedgeberg** [comment]
But if the countLeadingZeros' Pcodeop behavior is not defined as part of the spec, `RDest = countLeadingZeros(RSrc)` will produce an undefined value for RDest in the initial PCode output, so unless I'm seriously misunderstanding the context propagation algorithm, that varnode will be marked as undefined until it's set, or just treated as an unknown variable.

If a Count Leading Zeros operation is used to do something like derive a constant, it should be within the realm of feasibility for the decompiler to resolve that as well. In addition, since Count Leading Zeros is a common atomic operation, it makes sense to include as a standardized pcodeop for the purposes of the emulation engine. While I understand that `define pcodeop countLeadingZeros;` gets the job done for a lot of the decompilation output currently, I don't think it makes sense as a permanent solution.

**Comment by ghidra1** [comment]
Language implementations have the ability to define an `EmulateInstructionStateModifier` implementation identified by the `emulateInstructionStateModifierClass` property in the pspec (see ARM for example) .  This allows custom pcodeops to model their behavior in Java code for emulation purpose.  

While the decompiler can simplify constant expressions, is it really likely this operation would be used all constants?   I believe the pcodeop use would remain within the AST data flow allowing you to retain an association between input values and the resulting output value.

**Comment by hedgeberg** [comment]
I mean, I've seen it used at least twice in the last week with constant inputs, so while that maybe doesn't count as "likely" necessarily, it does happen. In the end I think it comes down to a design philosophy decision -- there seem to be native pcodeop definitions for basically every other "fundamental" arithmetic operation, i.e. any operation that would be implemented in a combinational ALU. CLZ is one of those fundamental operations, and compilers/optimizers tend to treat it as such, so if a memory read & potential cache miss can be avoided by reusing a constant instead of loading from memory, that's probably what the optimizer will default to. I think, considering that, that adding a CLZ pcodeop seems like the right design decision. Past that, I defer to y'all's judgment on whether or not this feature would be an appropriate use of dev time & energy.

**Comment by ryanmkurtz** [comment]
Fixed by 9cf60faef09734632a9e89d53d64241fdc8c57ca
