### ISSUE TITLE
[API] Load binary from a JUnit test

### ISSUE THREAD

**Issue by milsegv** [NationalSecurityAgency/ghidra#2122]
Good morning, 

I am starting to push some unit tests for my extension based on the Ghidra API. One of my tests requires to have access to a `Program` instance, based on a compiled binary. I am looking for a way to properly load a binary using ghidra's api, from a JUnit test perspective (meaning I don't have access to the methods supplied by `GhidraScript`). I have stumbled upon the `AutoImporter` class that provides useful methods that I believe could fulfill my requirements, but whenever I try to use it like:
```java
Program p = AutoImporter.importByUsingBestGuess(new File("/path/to/my/binary.o"), null, this, new MessageLog(), null);
```
I got the following error:
```
No load spec found for import file: /path/to/my/binary.o
```
Is there maybe an easier/hidden way to get a `Program` instance of a binary ?

**Comment by ryanmkurtz** [comment]
What type of file is binary.o?

**Comment by milsegv** [comment]
```bash
$> file binary.o
binary.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

**Comment by ryanmkurtz** [comment]
Can Ghidra import this file through the GUI by default?  Does it want to use the ElfLoader or BinaryLoader?

**Comment by ryanmkurtz** [comment]
I assume your loader is required to load this file?  Is it working through the GUI?

**Comment by milsegv** [comment]
Actually it is a normal, GCC-compiled C file, I am just trying to load it through ghidra API calls, so of course the GUI is able to analyze it and disassemble it. 

I am not implementing a new loader, I just want to get an easy-to-use instance of a binary to call some custom analysis on it.

**Comment by ryanmkurtz** [comment]
I would have to run it through the debugger to see what's happening.  Does it work with the headless analyzer (headless analyzer uses the AutoImporter).

**Comment by astrelsky** [comment]
Is your test class extending [AbstractGhidraHeadedIntegrationTest](https://ghidra.re/ghidra_docs/api/ghidra/test/AbstractGhidraHeadedIntegrationTest.html) or [AbstractGhidraHeadedIntegrationTest](https://ghidra.re/ghidra_docs/api/ghidra/test/AbstractGhidraHeadedIntegrationTest.html)? You don't have to but they get most of the necessary setup out of the way. I have seen similar problems caused by not having all the modules loaded.

[AbstractProgramBasedTest](https://ghidra.re/ghidra_docs/api/ghidra/test/AbstractProgramBasedTest.html) may also serve your needs nicely.

**Comment by milsegv** [comment]
Extending [AbstractGhidraHeadlessIntegrationTest](https://ghidra.re/ghidra_docs/api/ghidra/test/AbstractGhidraHeadlessIntegrationTest.html) solved the issue actually ! As I don't use any GUI feature, I thought this one would be a more convenient solution ;)

Thanks for your help !
