### ISSUE TITLE
api how to make MemoryBlock.setName("") update Program Tree pannel 

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2124]
![image](https://user-images.githubusercontent.com/4013370/88053181-af326780-cb5b-11ea-8e75-b4034ccc495b.png)
![image](https://user-images.githubusercontent.com/4013370/88053271-cd986300-cb5b-11ea-8449-c3b1166e5025.png)
in a Loader that extends AbstractLibrarySupportLoader class

**Comment by ryanmkurtz** [comment]
From a `Listing` object (`program.getListing()`), check out the `*RootModule()` methods.

**Comment by pabx06** [comment]
look like FragmentDB is what i am looking for but it has a private access.

**Comment by dragonmacher** [comment]
Did `MemoryBlock.setName()` not work for you?

Also, you should always be programming to the public interfaces and not the DB implementations.  For example, `FragmentDB` implements (indirectly) an interface named `Group`, which has a `setName()`.    At any rate, it seems like `MemoryBlock.setName()` should have worked for you.

**Comment by pabx06** [comment]
> Did `MemoryBlock.setName()` not work for you?
> 
> Also, you should always be programming to the public interfaces and not the DB implementations. For example, `FragmentDB` implements (indirectly) an interface named `Group`, which has a `setName()`. At any rate, it seems like `MemoryBlock.setName()` should have worked for you.

MemoryBlock.setName() rename OK the block in the 'Memory Map' Pannel not the programm tree

**Comment by dragonmacher** [comment]
I see now.   There is a bit of confusion in Ghidra surrounding the Program Trees and the Memory Map.    The Memory Map shows the current memory sections.  The Program Trees shows an organization of code in the program *that is initially named based upon the memory sections**. However, renaming the memory sections does not affect the Program Trees' nodes.

Here is a snippet that you can run in a script to rename Program Tree nodes:
```
		String[] treeNames = currentProgram.getListing().getTreeNames();
		for (String name : treeNames) {
			println("program tree name: " + name);
		}

		ProgramModule rootModule = currentProgram.getListing().getDefaultRootModule();
		if (rootModule == null) {
			rootModule = currentProgram.getListing().getRootModule(treeNames[0]);
		}

		Group[] children = rootModule.getChildren();
		for (Group group : children) {
			println("\t" + group.getName());

			// TODO rename some group
			// group.setName("newGroupName");
		}
```
