### ISSUE TITLE
Error attempting to packFile with script post headless analysis: "Can't save during transaction"

### ISSUE THREAD

**Issue by DootBoi** [NationalSecurityAgency/ghidra#2127]
attempting to run the following code in a post headless analysis script results in an error stating "Can't save during transaction
". However, when ran using the GUI it works perfectly. I attempted to release the consumers for "currentProgram" but that lead to the target domain file not being accessible. What am I missing?
```
public void run() throws Exception {
    	DomainFile target = currentProgram.getDomainFile();
    	File outputFile = new File("testoutput.gzf");
	target.packFile(outputFile,monitor);
    }
```

**Comment by ryanmkurtz** [comment]
The GhidraScript runs in a transaction started behind the scenes so its effects can be undone.  Some API calls don't like being run in a transaction.  Try calling` end(true)` before you call `packFile`.

**Comment by DootBoi** [comment]
That will do it. Thank you.
