### ISSUE TITLE
Recover lost function documentation from older repository version

### ISSUE THREAD

**Issue by Kevinn1109** [NationalSecurityAgency/ghidra#2128]
I am working on a Ghidra server for a very large project. Initially, knowledge of Ghidra was limited and the decompilation process didn't go very well. We managed to work around these issues, but recently I decided to clean up the code by re-evaluating large sections of the assembly.

Unfortunately this led to many functions losing all their parameter names, types and local variables. I have been reading through the Python documentation to find a way to import this information from the other revision, but without success. Is there any way to recover the lost documentation without resetting the repo to this older revision? Everything from this older revision is still accessible, so the only real problem is merging the information with the cleaned up version.

The Ghidra version I'm working with is 9.1.2.

Thanks in advance.

**Comment by dragonmacher** [comment]
We may have a better way of doing this, but I know you can use both the Diff Plugin and Version Tracking to do this.  The Diff Plugin will be more straight forward, I think.  Version Tracking may give you much more control, at the expense of complexity.

To use the Diff Plugin on an older version of a check-in, I performed the following steps:

- From the Front End Project window, right-click on the binary of interest
- Choose Show History
- Find the version of interest in the list
- Right-click on that version in the table and selection Open in Default Tool
- Once open in the tool, select File -> Save Foo As...
- Give the program a clear name for later opening, such as Foo.v26

At this point, you have a copy in your local project of the previous version.  To pull-out the differences, use the Diff Plugin:
- With Foo.v26 open in the tool, select the Open Diff View icon in the Listing header (the icon is two vertical bars, with a line between them)

At this point, you should have the Diff Plugin open, with arrow icons in the header that allow you to jump from change to change.  There is an icon to show you the Diff Details (the magnifying glass icon).

See the help entry title Program Differences for complete mastery.

The Version Tracking tool is an entirely different tool in  Ghidra (the tool icon with the 2 blue feet).  That tool is intended to allow you to pull your annotations from one of your existing binaries into a newer copy of a **similar** binary.   If you are not familiar with that tool, the learning curve is steeply moderate.  This is why I recommend trying the Diff Plugin first.


(It seems that this process should be more streamlined.  It is quite possible I am missing something.  Hopefully I will be corrected if there is an easier way.)
