### ISSUE TITLE
idaxml.py negative memory references causes errors

### ISSUE THREAD

**Issue by isJuhn** [NationalSecurityAgency/ghidra#213]
When trying to export a CELL (ppc64-32) ida database I ran into trouble as every time in the markup stage it would return the following error
```
<type 'exceptions.TypeError'> Expected an ea_t type
```
after some digging I found that the instructions that caused this error all had negative memory offsets. Here is an example instruction:
![image](https://user-images.githubusercontent.com/26828095/54478325-14ac7080-4811-11e9-9311-72633eb15b9a.png)
The problem with this arises in that operands are stored in unsigned integers when returned from the IDA plugin SDK API. This combined with pythons automatic type promotion creates a problem. If we inspect the code at idaxml.py:1195
```
target = insn.ops[op].value - ri.tdelta + ri.base
```
here the `insn.ops[op].value` will return `18446744073709551612`(-4) in the case of the instruction shown above. `ri.tdelta` is 0 but `ri.base` is not, so when you add that on to the huge number python promotes it to a bigger type instead of overflowing. This creates an error when a call is made with `target` on line 1202 as the function expects an ea_t type.

A solution to this would be to either confine it to 64 bits with an and:
```
target = (insn.ops[op].value - ri.tdelta + ri.base) & ((1 << 64) - 1)
```
Or you could use ctypes:
```
target = ctypes.c_ulonglong(insn.ops[op].value - ri.tdelta + ri.base).value
```

**Comment by emteere** [comment]
Good find and fix.  The second seems like a better fix.
