### ISSUE TITLE
Duplication of files in most Feature jar files in a built distro

### ISSUE THREAD

**Issue by dev747368** [NationalSecurityAgency/ghidra#2144]
Most of the Features/*/lib/*.jar files duplicate the files under the "help/" path.

To see the duplicate files, in an unzip'ed Ghidra distro directory, run (for example):

`unzip -l Ghidra/Features/VersionTracking/lib/VersionTracking.jar | cut -c31- | sort | uniq -c | sort`

you will see a list of counts of each file listed in the zip.

>....
>1 images/user-busy.png
>1 images/user-online.png
>1 images/viewmag.png
>1 images/view-refresh.png
>1 images/view-split-left-right.png
>1 images/warning.png
>1 images/wizard.png
>1 images/zoom_in.png
>1 images/zoom_out.png
>2 help/shared/arrow.gif
>2 help/shared/close16.gif
>2 help/shared/menu16.gif
>2 help/shared/note.png
>2 help/shared/note.yellow.png
>2 help/shared/note-red.png
>2 help/shared/redo.png
>2 help/shared/tip.png
>...

You should be able to see that most files are only included once, but for the help files they are included twice.

There should only be one copy of a specific path/filename in a zip.  Putting the same file in a zip multiple times isn't great.

**Comment by ghizard** [comment]
Closed by merge of branch faa9518
