### ISSUE TITLE
 Low-level Error: Overlapping input varnodes

### ISSUE THREAD

**Issue by vfsfitvnm** [NationalSecurityAgency/ghidra#2149]
**Describe the bug**
Some functions in the target shared library cannot be decompiled: the error `Low-level Error: Overlapping input varnodes` shows up.

**Attachments**
Debug log: [debug.txt](https://github.com/NationalSecurityAgency/ghidra/files/4994988/debug.txt)

**Environment:**
 - OS: Manjaro kde 5.6.19
 - Java Version: 11.0.7
 - Ghidra Version: 9.1 dev, 9.1.2 public

**Comment by caheckman** [comment]
This is triggered by functions that contain AARCH64 neon instructions that are unimplemented.  These instructions are now largely implemented in master (and will be in the Ghidra 9.2 release).  This particular example is fixed in master.

**Comment by racerxdl** [comment]
Just happened here while decompiling a x86_64 function from Minecraft Bedrock Server 1.17.41. The ServerInstance::initializeServer
