### ISSUE TITLE
Missing CMP instruction for x86

### ISSUE THREAD

**Issue by RobertBaruch** [NationalSecurityAgency/ghidra#215]
**Describe the bug**
Disassembling [TELEN.EXE](https://www.dosgamesarchive.com/download/telengard/) (a game for DOS from 1985) yields bad instructions, specifically decoding machine instructions starting with 0x82.

**To Reproduce**
1. Download TELEN.ZIP, unzip to get TELEN.EXE. Analyze with Ghidra.
2. Go to address 1000:880b, see the decompilation:

```
/* WARNING: Control flow encountered bad instruction data */

uint FUN_1000_880b(uint param_1)

{
  if ((-1 < (int)param_1) && ((int)param_1 < 0x24)) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  return param_1 & 0xff00;
}
```

The cause is the instruction at 1000:882e, which should be disassembled as follows:

```
1000:882e 82 BC B4 27 00    CMP  byte ptr [si+27B4], 0
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Comment by RobertBaruch** [comment]
The fix is to change this line (2769) in `Processors/x86/data/languages/ia.sinc`:

```
:CMP spec_rm8,imm8       is vexMode=0 & byte=0x80; spec_rm8 & reg_opcode=7 ...; imm8        { subflags(  spec_rm8,imm8 ); local tmp =   spec_rm8 -   imm8; resultflags(tmp); }
```

to:

```
:CMP spec_rm8,imm8       is vexMode=0 & (byte=0x80 | byte=0x82); spec_rm8 & reg_opcode=7 ...; imm8        { subflags(  spec_rm8,imm8 ); local tmp =   spec_rm8 -   imm8; resultflags(tmp); }
```

This looks to have been an oversight, because all the other 0x82 instructions are present.

**Comment by mumbel** [comment]
#22 and #53 have more info

**Comment by emteere** [comment]
Thanks for the find and fix.  I've posted a patch for this and many others in issue #22.
