### ISSUE TITLE
this ignored with uncommitted params/return

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2151]
**Describe the bug**
When the function parameters and return type have not been committed the decompiler ignores the this parameter for __thiscall functions. 

**To Reproduce**
1. Create a function. 
2. Add function to GhidraClass
3. Set calling convention to __thiscall 
4. See missing this parameter in decompiler 

**Expected behavior**
The this parameter should be present and used regardless of whether or not the parameters or return type have been committed. It is quite common to know that a function is __thiscall but not know the parameters or return type. 

**Environment (please complete the following information):**
 - Ghidra Version: 9.0 - 9.2

**Additional context**
It is important to ensure that the this parameter is used to aid in type propagation for other unknown variable/parameter types.

**Comment by ghidra1** [comment]
This is by design.  The decompiler ignores "default" signatures so that it may adapt and dynamically determine the function parameters based upon the data flow.  It either locks in one parameter or all parameters based upon either the signature source-type or presence of "define" parameters with "defined" types.

**Comment by astrelsky** [comment]
> This is by design. The decompiler ignores "default" signatures so that it may adapt and dynamically determine the function parameters based upon the data flow. It either locks in one parameter or all parameters based upon either the signature source-type or presence of "define" parameters with "defined" types.

This appears to be a flaw in the design though as the `this` parameter will never be determined unless propagated from somewhere else. Having to go through all the functions and determine what arguments you can manually just to get the `this` parameter to propagate is a ton of work. If the calling convention is set it should at least respect it.

**Comment by astrelsky** [comment]
@ghidra1 that doesn't make sense. If the decompiler attempts to determine the parameters/return type before they are committed then there is absolutely no reason for the decompiler to be determining the first parameter to not be `this` when "guessing" the types. I don't see how this is not a bug.

**Comment by astrelsky** [comment]
@ghidra1 if the decompiler knows that the calling convention is __thiscall shouldn't it also know to determine param_1 to be `Manager *` instead of an int?
![Capture](https://user-images.githubusercontent.com/46897303/88934297-79be0600-d24e-11ea-8a16-3ffad9c79cbd.PNG)

**Comment by ghidra1** [comment]
Unfortunately, the decompiler takes parameters as all or nothing and when taking them they must be pinned-down to specific varnode storage.   While this is not my area of expertise @caheckman may be able to offer more insights.

**Comment by astrelsky** [comment]
> Unfortunately, the decompiler takes parameters as all or nothing and when taking them they must be pinned-down to specific varnode storage. While this is not my area of expertise caheckman may be able to offer more insights.
> 
> If you know there are no parameters other than 'this' you could try setting the Signature Source Type to USER_DEFINED via API or within the function editor specify "void" within the formal parameter signature then click OK. e.g.,
> `undefined getIndex(void)`

For this example I'm fairly certain that the field is a size_t as it's used to access an array element somewhere. I just picked the quickest one I could find, deleted and recreated the function and set it to __thiscall as a quick demonstration.

**Comment by astrelsky** [comment]
There are still a few situations where it doesn't work but it is much better. I will see if I can get an example that I can share.

**Comment by caheckman** [comment]
I believe "called" functions are addressed now in master.

**Comment by astrelsky** [comment]
> I believe "called" functions are addressed now in master.

Thank you!
