### ISSUE TITLE
HiDPI display is far too small to use

### ISSUE THREAD

**Issue by wt** [NationalSecurityAgency/ghidra#2159]
**Describe the bug**
I have a laptop with a HiDPI screen.

**To Reproduce**
1. Download ghidra
2. Unzip it
3. run `cd ghidra_9.1.2_PUBLIC && ./ghidraRun`
4. Look at the UI

**Expected behavior**
A UI that this readable and proportionally sized to other apps on my desktop.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - Java Version: openjdk 11.0.8 2020-07-14
 - Ghidra Version: 9.1.2 from the zip file on the website

**Comment by wt** [comment]
So, I did find that I can manually set "sun.java2d.uiScale=2" in support/launch.properties. However, this seems a little manual when the system is configured for 200% scaling via whatever mechanism the gnome settings uses to set it. Is there any way to detect that and manually use it instead of the 1 that is in that properties file by default?

**Comment by hedgeberg** [comment]
HiDPI scaling is fundamentally a Swing issue and not a ghidra issue -- its pretty common for cross-platform gfx frameworks to have scaling issues on Linux. QT has the same issue. 

That being said, **https://wiki.archlinux.org/index.php/HiDPI#Java_applications** contains some workarounds and tips, specifically: 
```
Since Java 9 the GDK_SCALE environment variable is used to scale Swing applications accordingly.

Note that at this point, Java AWT/Swing (up to including OpenJDK 13) only effectively supports integer values. A setting of -Dsun.java2d.uiScale=250% or GDK_SCALE=2.5 will be treated as if it were set to -Dsun.java2d.uiScale=2 resp. GDK_SCALE=2. 
```
Setting GDK_SCALE in your GNOME user profile (see: **https://help.gnome.org/admin/system-admin-guide/stable/dconf-profiles.html.en**) should resolve this, and you should be able to query the scale value you have configured in settings at login using `dconf` or `gsettings`.

**Comment by ryanmkurtz** [comment]
sun.java2d.uiScale=2 is the recommended solution.  When I'm on Linux on my 32" 4k display, uiScale=1 is a little too small, and uiScale=2 is way too big.  I really want 1.3, but that fractional scalings don't seem to be supported.  Because there is no perfect solution for all users and setups, I think it should remain a fixed value that the user can tweak however they like.

**Comment by hedgeberg** [comment]
@ryanmkurtz Swing doesn't support non-integer scale factors, unfortunately. Any non-integer value is rounded to an integer. I don't know too many apps or frameworks that handle non-integer scale factors well, but the point is moot; even if there were a framework that enabled it, I don't think anyone wants to rebase the ghidra UI framework away from Swing. 

On linux systems, particularly gnome, `sun.java2d.uiScale=N` is usually copied from the GDK_SCALE environment variable, so modifying that environment variable /should/ solve the scaling issue on its own.

**Comment by snhirsch** [comment]
I'm having the same issue but adding sun.java2d.uiScale=2 to the load properties file has no effect at all.  Fonts are too small to read.  This is Kubuntu 18.04 and I'm running openjdk-11.

**Comment by ryanmkurtz** [comment]
Do your display settings in `support/launch.properties` look exactly like this?

```
# The following options affect rendering on different platforms.  It may be necessary to play
# with these settings to get Ghidra to display and perform optimally on HiDPI monitors or in VM's.
VMARGS=-Dsun.java2d.opengl=false
VMARGS_LINUX=-Dsun.java2d.pmoffscreen=false
VMARGS_LINUX=-Dsun.java2d.xrender=true
VMARGS_LINUX=-Dsun.java2d.uiScale=2
VMARGS_LINUX=-Dawt.useSystemAAFontSettings=on
VMARGS_WINDOWS=-Dsun.java2d.d3d=false
```

**Comment by snhirsch** [comment]
<sigh...>  I finally figured out that the properties file already had this statement.  Originally I added '..uiScale=2' as a VMARGS= line at the very end of the file.  This really should be mentioned in the FAQ.  When I searched issues it turned up advice that apparently predates this.  All good now, thanks.
