### ISSUE TITLE
Perf: deleting a large selection of fields in the Structure Editor has quadratic cost

### ISSUE THREAD

**Issue by mateon1** [NationalSecurityAgency/ghidra#2160]
**Describe the bug**
The Structure Editor handles operations on ranges of fields suboptimally, which can lead to long freezes in normal usage.

**To Reproduce**
1. Go to 'Structure Editor'
2. Change size to 1024/2048/4096, generating over a thousand 'undefined' one-byte fields
3. Select almost all fields, from, let's say, 16 to the end of the structure
4. Press 'delete'
5. Observe Ghidra freezing for a couple seconds/a dozen seconds/about a minute.

**Expected behavior**
The structure editor should be able to perform this action nearly instantly, as it already does if you truncate the size of the struct by lowering the size.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: `Linux ceres 5.4.23 #1-NixOS SMP Fri Feb 28 16:22:29 UTC 2020 x86_64 GNU/Linux`
 - Java Version: 11.0.7 (as reported by Ghidra)
 - Ghidra Version: 9.1.2; Build PUBLIC 2020-Feb-12 1149 EST

**Additional context**
N/A

**Comment by astrelsky** [comment]
Just double checked and can confirm this has been fixed in 9.2.
