### ISSUE TITLE
How to permanently rename (or add symbol) a function

### ISSUE THREAD

**Issue by Ruturaj4** [NationalSecurityAgency/ghidra#2161]
I wrote a simple logic using python to detect and rename main function (assuming stripped binary compiled using gcc).

```
# logic to find and rename the main function
ifc = DecompInterface()
ifc.setOptions(DecompileOptions())
ifc.openProgram(currentProgram)
entryfunction = getGlobalFunctions("entry")[0]
res = ifc.decompileFunction(entryfunction, 60, monitor)
m = re.search("__libc_start_main\((.+?),", res.getCCodeMarkup().toString())
if m.group(1)[0] != "main":
    getGlobalFunctions(m.group(1))[0].setName("main", SourceType.ANALYSIS)
```

I can rename the function this way in the analysis interface. But, my question is how to commit these changes to the actual binary (using symbol or something else)?

**Comment by astrelsky** [comment]
If you mean that you wish to save the binary, open it in a debugger and see the symbol "main", you cannot.
