### ISSUE TITLE
`BT R12D, EAX` disassembles incorrectly

### ISSUE THREAD

**Issue by cpast** [NationalSecurityAgency/ghidra#2162]
In an x86-64 executable, there's an instruction encoded as `41 0f a3 c4`. This should be `BT R12D, EAX`. However, Ghidra is disassembling it as `BT ESP, EAX`. It seems to be ignoring REX.W bits R and B, according to the Instruction Info mask (specifically, bit B is 1 in this instruction, which should extend the destination operand from `100=ESP` to `1100=R12D`). Furthermore, attempting to patch in `BT R12D, EAX` fails. The Instruction Info:

![Instruction Info](https://user-images.githubusercontent.com/8211353/89135238-18ba5a80-d4fa-11ea-9c9b-8f30be60ac47.png)

**Comment by mumbel** [comment]
This is fixed in master.

**Comment by 0xd4d** [comment]
See also https://github.com/NationalSecurityAgency/ghidra/issues/2033
