### ISSUE TITLE
THUMB typo in uqsub16

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#217]
**Describe the bug**
Looks like possible copy/paste typo in ARMTHUMBinstructions.sinc in uqsub16. Discovered with
`support/sleigh -t ARM6_le.slaspec`
`Warning: temporary is written but not read in constructor`
tmp2 is never used, and is probably meant for the Rd0811[16,16]
```
Rd0811[ 0,16] = tmp1[0,16];
Rd0811[16,16] = tmp1[0,16];
```

**Environment (please complete the following information):**
 - Ghidra Version: 9.0

**Comment by emteere** [comment]
Thanks for the find.  It does look like a typo.
The change will be added to the bl half change for #39.

**Comment by mumbel** [comment]
Fixed in 9.0.1
