### ISSUE TITLE
LaunchSupport expected 2 to 4 arguments but got 1

### ISSUE THREAD

**Issue by comosedice2012** [NationalSecurityAgency/ghidra#2176]
I have installed ghidra and jdk version 11.0.8 (the only version 11 I can find), both in the "Program Files" folder on a Win 10 VM in VMWare Pro.

When I run java -version, I get:
java version "11.0.8" 2020-07-14 LTS 
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode) 

Here is my system path variable string:
C:\Program Files\bin;C:\cygwin64\bin;C:\Program Files\Java\jdk-11.0.8\bin\
I even added the java bin path to its own new line, just in case.

This is my error message:
C:\Program Files\ghidra_9.1.2_PUBLIC>ghidraRun.bat 
LaunchSupport expected 2 to 4 arguments but got 1 
LaunchSupport expected 2 to 4 arguments but got 1 
LaunchSupport expected 2 to 4 arguments but got 1 

Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section. 

I have deleted and re-downloaded and installed ghidra but I still get the same message. Any ideas what else I can do here?
Thanks,
Ryan

**Comment by ryanmkurtz** [comment]
What do you get when you run 

`javac -version`

**Comment by ryanmkurtz** [comment]
Does it work if you run Ghidra out of a different directory, like your desktop?

**Comment by astrelsky** [comment]
I just double checked if it was the space and it's definitely not.

**Comment by ryanmkurtz** [comment]
It could be the fact that you have cygwin on the PATH.  Sometimes those tools behave differently than what ships with Windows, and Ghidra doesn't test against them.

**Comment by mumbel** [comment]
is this #2141?

**Comment by AndnixSH** [comment]
I had the same problem. I replaced `%INSTALL_DIR%\` to `%INSTALL_DIR%` that mumbel mentioned the PR and it worked

**Comment by comosedice2012** [comment]
Do you mean a "\" at the end of my path, like below?
C:\Program Files\bin;C:\cygwin64\bin;C:\Program Files\Java\jdk-11.0.8\bin

I double checked my path and that is not it.

**Comment by comosedice2012** [comment]
I have also tried to run it from a different directory and I get the same error

**Comment by comosedice2012** [comment]
Oops I noticed I accidentally forgot the "/" in my comment above about the path. I meant a / not "" in the path.

**Comment by comosedice2012** [comment]
I also tried removing cygwin from the path but that didn't help either

**Comment by comosedice2012** [comment]
Huh, well I moved the ghidra folder from "Program Files" back to the root directory, and it seems to work, for whatever reason.  Actually, I ran my VM back to a previous state, which had it in root directory before I tried to put everything in the Program Files. Anyways, it seems to be okay now. Thanks for all your help.

**Comment by matt-kempster** [comment]
I hit this too. I believe it is because there is a space in the name of the "Program Files" folder. Actually I didn't put mine here, but in a folder I call "Programs Backend". If I move it to another one without a space - I moved it to "Temporary" - then it installs without issue. :/

**Comment by thebadzero** [comment]
This problem can be fixed - there should be no gaps in the Ghidra path

**Comment by alexvnesta** [comment]
Same issue here. In my case, my windows user directory name had a space in it. Putting ghidra in C:/ghidra fixed it.

**Comment by ryanmkurtz** [comment]
> Same issue here. In my case, my windows user directory name had a space in it. Putting ghidra in C:/ghidra fixed it.

What version of Ghidra were you running?  What was the full path of Ghidra?

**Comment by M9k** [comment]
Same problem, moving the Ghidra folder to a location without any space fix it.
I have cygwin in the path too but it works fine with it.

**Comment by ryanmkurtz** [comment]
I would expect the latest Ghidra to work with spaces in the path.  The only thing that doesn't work are paths with exclamation points in them.

**Comment by M9k** [comment]
There is a bug about how LaunchSupport.jar manage the first argument.
On my system che .bat launch this command:
java -cp "D:\Ghidra test\support\LaunchSupport.jar" LaunchSupport "D:\Ghidra test\support\..\\" -jdk_home -save
and it get this error:
LaunchSupport expected 2 to 4 arguments but got 1
Meanwhile If i remove the last \ in the path:
java -cp "D:\Ghidra test\support\LaunchSupport.jar" LaunchSupport "D:\Ghidra test\support\..\" -jdk_home -save
It works fine:
C:\Program Files\Java\jdk-12

**Comment by ryanmkurtz** [comment]
What version of Ghidra are you using?

**Comment by ryanmkurtz** [comment]
Any how are you launching Ghidra?  Double-clicking ghidraRun.bat?  Running ghidraRun.bat from a command prompt?  From powershell?  Something else?

**Comment by M9k** [comment]
> What version of Ghidra are you using?

I'm using the last public beta (10.0 - 2021-May-21 1607 EDT).

**Comment by M9k** [comment]
Found the problem, it's the JDK version.
It works fine with:
java 11.0.11 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

It it get this bug with my old version (my default one):
java 12.0.2 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

**Comment by M9k** [comment]
I thinks the two \\ in the argoments are escaping the ", so the string end with the new line at the end of the command.
To fix this problem the solution can be replace every "LaunchSupport "%INSTALL_DIR%\"" with "LaunchSupport "%INSTALL_DIR%""

**Comment by ryanmkurtz** [comment]
Unfortunately I cannot reproduce this error using java 11 or java 12 on the latest Windows 10 and Windows Server 2016.

**Comment by M9k** [comment]
I try on another PC with Java 12.0.2 2019-07-16 (build 12.0.2+10) and it works fine even with spaces.
So the problem only occurs if there is a space and the double \\\\ at the end of the first argument with JDK 12.0.2, but there is another condition to bring up the bug.
There must be a reason why the parameter is interpreted differently between the two systems, despite having the same JDK.
I try with both cmd and Powershell so the problem doesn't seem the cli used.

**Comment by ryanmkurtz** [comment]
Are they both standard fully updated Windows 10 machines?  I agree, this problem has something to do with the environment.

**Comment by M9k** [comment]
> 
> 
> Are they both standard fully updated Windows 10 machines? I agree, this problem has something to do with the environment.

Yes, both are upgraded Windows 10, one is a Enterprise version and the other one is a Educational version.
I'll made more test this evening, right now I don't have the pc with the problem (the Educational one) with me.

**Comment by M9k** [comment]
I just retry on the PC that works fine with jdk-12.0.2, it doesn't works with jdk-1.0.11, both with PowerShell and cmd.
This one seem to works the opposite of the other one.
It's probably not the version of JDK that matters, but how it's set up. On one pc I have JDK 11 by default and it works with 12, on the other I have 12 as default and it works with 11. 
What happens if we remove the last \ in the path? I try on my pc and it worked fine to me.

**Comment by ryanmkurtz** [comment]
Whenever I've tested the PR's that remove the backslash, I get the error.  That's under jdk 11.  That's why i've never accepted the PR's.

**Comment by Wall-AF** [comment]
Looking at the current `launch.bat` file I see that where `INSTALL_DIR` is set (in 2 places), it is assigned a trailing `\` character.  Therefore, in the 4 uses in question (of the form `"%INSTALL_DIR%\"`), the additional `\` is unnecessary and probably should be removed.

**Comment by M9k** [comment]
> Whenever I've tested the PR's that remove the backslash, I get the error. And I've never seen the error with the backslash. That's under jdk 11, our officially supported version. That's why i've never accepted the PR's.

What error do you get without the extra \? Maybe we can fix it to remove the problem altogether, the path with the double \ at the end isn't theoretically correct.
For me, without the extra \, works in every case, so I don't understand the problem.

**Comment by ryanmkurtz** [comment]
Let me play with it a bit more and I'll get back to you.

**Comment by M9k** [comment]
Hello,
I try to remove both backslash and it seems to works fine with every JDK, let me know if it can be a good solution.

I open the pull request #3121 with this fix.
