### ISSUE TITLE
How to disable a default enabled analyzer programmatically?

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#2179]
For now a user must switch off some analysis by a mouse click in the dialog. But my plugin requires some analysis options to be switched off. How to switch them?

**Comment by dev747368** [comment]
Check out FunctionIDHeadlessPrescript.java.

**Comment by astrelsky** [comment]
In case you don't have access to or are not using a GhidraScript, here is the method which enables/disables the analyzers.

https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/script/GhidraScript.java#L1316-L1350

**Comment by lab313ru** [comment]
Thank you!

So the result is:
```cpp
Options anOpts = program.getOptions(Program.ANALYSIS_PROPERTIES);
anOpts.setBoolean("Decompiler Switch Analysis", false);
```

**Comment by astrelsky** [comment]
> Thank you!
> 
> So the result is:
> 
> ```java
> Options anOpts = program.getOptions(Program.ANALYSIS_PROPERTIES);
> anOpts.setBoolean("Decompiler Switch Analysis", false);
> ```

It is worth mentioning that you can set default enablement/disablement of some analyzers from the `.pspec` if you have a use for it.

**Comment by lab313ru** [comment]
And how to do that?

Andrew Strelsky <notifications@github.com> 5 августа 2020 г. 00:50:39 написал:

**Comment by astrelsky** [comment]
> And how to do that? Andrew Strelsky <notifications@github.com> 5 августа 2020 г. 00:50:39 написал:
> […](#)
> Thank you! So the result is: Options anOpts = program.getOptions(Program.ANALYSIS_PROPERTIES); anOpts.setBoolean("Decompiler Switch Analysis", false); It is worth mentioning that you can set default enablement/disablement of some analyzers from the .pspec if you have a use for it. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

https://ghidra.re/ghidra_docs/api/ghidra/program/model/lang/GhidraLanguagePropertyKeys.html

Unfortunately it doesn't appear like the switch analysis is one of them.
