### ISSUE TITLE
Class "TestAddress" referenced by the documentation does not exist

### ISSUE THREAD

**Issue by RolfRolles** [NationalSecurityAgency/ghidra#218]
Title says it all; `TestAddress` exists in the documentation, such as the one online at https://ghidra.re/ghidra_docs/api/ghidra/program/model/address/TestAddress.html. However, if you actually try to import that class, you get an error:

    ThreeValuedAbstractInterpreter.java:50: error: cannot find symbol
    import ghidra.program.model.address.TestAddress;
                                       ^
      symbol:   class TestAddress
      location: package ghidra.program.model.address

`TestAddress` is indeed not present in the "unofficial" source code extracted from the .zip files, such as the one online at https://github.com/0xeb/Ghidra-unoffical-src/tree/d998c7e6104874f0658b0207e8b182a88711d973/src/SoftwareModeling-src/ghidra/program/model/address

It is possible to instantiate other classes in that package such as `GenericAddress`. I worked around by creating a GenericAddressSpace named "TEST".

**Comment by ghidra1** [comment]
This is a test class and is not intended for general use.  We will look into eliminating adhoc test classes from Javadocs.

**Comment by ghidra1** [comment]
Addresses must be instantiated via the AddressFactory or AddressSpace.  An AddressFactory can be obtained from the Program or Language.  The AddressFactory from the Program should generally be used since it will be augmented with a stack space and any relevant overlay spaces.
