### ISSUE TITLE
Does Ghidra have an API that allows you to delete a file from the project?

### ISSUE THREAD

**Issue by sarahcxh** [NationalSecurityAgency/ghidra#2180]
I would like to write a script to do some post-processing on Ghidra on Headless Mode, and afterward delete the file from the project. (I just want to delete the file only, not the project.) Is there a way to do that, like is there some API which Ghidra provides?

**Comment by dragonmacher** [comment]
From the script API you can get project folders (see `getProjectRootFolder()`).  From a project folder you can get project files, which are `DomainFile` objects.  You should be able to call `DomainFile.delete()` to remove the file.

**Comment by dev747368** [comment]
If his answer wasn't enough, just reopen this issue.
