### ISSUE TITLE
Not null-terminated strings in decompiler view

### ISSUE THREAD

**Issue by padorka** [NationalSecurityAgency/ghidra#2181]
Hi,

I am working on a couple of scripts to analyze golang binaries. I am trying to recover strings in the binary. As these strings are not null terminated I use the location and length combination to find and define the strings. When I define a string with a specific length, in the decompiler view a string will be visible instead of the address of the data, but it will look for the null termination, so a much longer string is visible than the one I defined. Is there a way to tell the decompiler to use only the defined string with a specific length?

Thank you for your help.

**Comment by dev747368** [comment]
It depends on how you create your string in Ghidra.  There are both null terminated string types as well as fixed length string types.
Are you specifying a fixed length data type?

**Comment by padorka** [comment]
Thank you for your answer.
I used the createAsciiString​(Address address, int length) method to create the strings.

**Comment by dev747368** [comment]
Sounds like you are creating the string correctly.  If you hover over the data element in the listing window, the popup window should specifically state fixed or null term.
As far as the decompiler goes, I'll have to leave that to others.

**Comment by padorka** [comment]
Yes, it looks good in the listing view, but ugly in the decompiler view. You can see it on the screenshots below. 

![string1](https://user-images.githubusercontent.com/66425539/89508378-227be080-d7ce-11ea-8e90-7f8765922674.png)
![string2](https://user-images.githubusercontent.com/66425539/89508383-2445a400-d7ce-11ea-8041-5433d3d90e57.png)
![string3](https://user-images.githubusercontent.com/66425539/89508385-2576d100-d7ce-11ea-85c1-ba283033ce59.png)

**Comment by dev747368** [comment]
what is the prototype of runtime.concatstring2?

**Comment by padorka** [comment]
Unfortunately Ghidra cannot recover golang functions correctly. 

It looks like this now:
void runtime.concatstring2(undefined param_1)

It should be the following according to golang documentation:
func concatstring2(buf *tmpBuf, a [2]string) string

But in the example above we can see that a string parameter has two values, the actual data and the length. That's why it has five input parameters.

I just couldn't figure out a way to tell the decompiler to show only the string with the specific length that I set with createAsciiString​(Address address, int length) method .

**Comment by caheckman** [comment]
The issue of non-null terminated strings in the decompiler is resolved for the upcoming 9.2 and is available currently in the master branch if your in a position to do your own build.

**Comment by padorka** [comment]
Hi,
it is great news. Thank you very much.

**Comment by dwattttt** [comment]
Can this issue be re-opened? The decompiler is still following string data after a fixed length char array in Ghidra 10.1.4.

**Comment by dwattttt** [comment]
Sure.

strs.exe is built in release from the provided source [strs_src.zip](https://github.com/NationalSecurityAgency/ghidra/files/8819136/strs_src.zip) (rustc 1.61.0 (fe5b13d68 2022-05-18)). I can provide the binary upon request.

```
use std::io::{self, Write};

fn main() -> io::Result<()> {
    let mut stdout = io::stdout().lock();

    stdout.write_all(b"Hello, world!")?;
    stdout.write_all(b"I'm a string!")?;
    stdout.write_all(b"I'm another string")?;
    stdout.write_all(b"Boy I love strings")?;

    Ok(())
}
```

In the built binary, the main strings are continguous at RVA 0x1e3b0. The function at RVA 0x1010 is the main function which references these (Ghidra has trouble detecting this function during auto analysis). If the contiguous string is cleared, then a char array of 13 bytes formed in its place (the size of the first "Hello, world!" string), the decompilation of main continues to show the full string as the parameter even after using the "Push at any time to trigger a re-decompile" button.

Additionally, when loading the PDB, Ghidra assigns the type `void func(void)` to `write_all`, which prevents the strings in main from appearing in the decompilation; either preventing the PDB load, or fixing the `write_all` call to take the string as the second parameter restores the strings in the decompiled view.

**Comment by ryanmkurtz** [comment]
Thanks we'll take a look.
