### ISSUE TITLE
Be able to persist changes to the auto-analysis defaults

### ISSUE THREAD

**Issue by vanhauser-thc** [NationalSecurityAgency/ghidra#2182]
I searched previous issues for a similar feature request but could not find any, so here it goes.
(I originally posted this to the Ghidra subreddit, but nobody new how to do that, but the upvotes show that there is interest :) https://ps.reddit.com/r/ghidra/comments/i1bk7v/change_the_autoanalysis_defaults/)

**Is your feature request related to a problem? Please describe.**
I am usually analyzing arm and aarch64 embedded Linux binaries and the "Non Returning Functions - Discovered" module identifies functions like memcpy as non-returning, making the analysis trash. (see #1981)

As there are many binaries and libraries I use the headless feature to import and auto-analyze the many files overnight so I can have a look at them in the morning.

However due the issue with the "Non Returning Functions - Discovered" module this does not work and I have to do all auto-analysis by hand.

**Describe the solution you'd like**
I would like to be able to change the modules active by default for auto-analysis and persist these changes by having a "save as default" in the "Analyze Options" window.

**Describe alternatives you've considered**
I load every binary manually into codebrowser and deselect the offending module by hand, and also select Decompiler Parameter ID manually and it costs a lot of time :(
(I now use a headless prescript as pointed out by dragonmacher as a workaround. Still this is a feature that is missing IMHO)

**Comment by vanhauser-thc** [comment]
@dragonmacher I got the workaround working, thank you!
I still think this would be a missing feature that should be implemented (a "save as default" button in the windows).

**Comment by ryanmkurtz** [comment]
Fixed by da3a80f4fe86a7ddae8951366fa19f658fcb3fb3
