### ISSUE TITLE
Popups storm

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2185]
**Describe the bug**
in a GhidraScript: i had loaded datatype from over 200  DataType File Archive. They were closed by the script. Then the script try to use those java datatype instance loaded.

Resulting in a storm of **over 200  modal pop-up** . And off course the active pop-up is behind 200 others modal pop-up.
this time consuming and annoying like having a web-page opens popups on a loop.

**To Reproduce**

**Expected behavior**
1)Error from scripts should be stacked inside a Jlist or something to not open more than pop-up even if the script run throws errors/exception on a loop...
2) At least make the **OK** button active by default instead of **details** so i can hit the keyboard 200 times to close them all.

**Screenshots**
![image](https://user-images.githubusercontent.com/4013370/89555857-da31e200-d810-11ea-8ef4-8fa0b759f038.png)
![image](https://user-images.githubusercontent.com/4013370/89556664-039f3d80-d812-11ea-9db2-4932a8620fe0.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: linux kde plasma desktop
 - Java Version: 13
 - Ghidra Version: 9.1.2 public

**Additional context**

**Comment by dragonmacher** [comment]
This is a contender for one of the most beautiful screenshots I've seen.

**Comment by ryanmkurtz** [comment]
Is that their default layout?  It's like the developer put in an algorithm to make them pop up beautifully.

**Comment by astrelsky** [comment]
> This is a contender for one of the most beautiful screenshots I've seen.

I once screwed up and had a NPE while getting the icon for a GTreeNode for every node in a tree of 1000+ nodes. The boarders of the popup tend to produce a drop shadow effect after stacking so many.

> Is that their default layout? It's like the developer put in an algorithm to make them pop up beautifully.

I think they were just spread out to show there is a lot of them.

**Comment by pabx06** [comment]
> Is that their default layout? It's like the developer put in an algorithm to make them pop up beautifully.

nope i was willing to click them all but before that ! 
but only one of them had button enabled.

 is had to dig deep and move them around to find the one with button action enabled (in java : modal popup stacked are bad). the plaque of modal popup

**Comment by ghizard** [comment]
Should be addressed by merge of branch: fc994cd
If not, please reopen.
