### ISSUE TITLE
How to convert function to a string ? 

### ISSUE THREAD

**Issue by TylerKann** [NationalSecurityAgency/ghidra#2186]
within the functionDB class, using a HighFunction i can do `function.getParameters()` , which gives me a list of parameters. I can then put these into an array of `params`. If I do 
`print(params[0])` it will print `[byte * param_1@RDI:8]`. However, I want to get this as a string, not just print it. Is there any method on the `Parameter` class that I can use to get a string ?

**Comment by astrelsky** [comment]
Object.toString() or from python just use str(params[0])

**Comment by TylerKann** [comment]
Thanks. I dont think str() works but .toString() does!

**Comment by astrelsky** [comment]
> Thanks. I dont think str() works but .toString() does!

str() just invokes Object.toString() under the hood.

**Comment by TylerKann** [comment]
hmm, i must have tried something else (i thought i did try str() ). Thats good to know though, thanks
