### ISSUE TITLE
M68000: doesn't disassemble MOVEM.L D0-D1, (addr).l

### ISSUE THREAD

**Issue by NTxC** [NationalSecurityAgency/ghidra#219]
Ghidra's Motorola 68000 does not disassemble MOVEM.L D0-D1, (addr).l (marked in red):

![ghidra](https://user-images.githubusercontent.com/25325789/54501616-9510c580-4926-11e9-8854-11daf7ff460e.png)

Seems to disassemble other MOVEM.L variants fine.

**Comment by theclashingfritz** [comment]
M68000 is very finicky in what it wants to disassemble automatically for some reason. I still don't know why

**Comment by mumbel** [comment]
```
:movem.l r2mfl0,(d32)".l"       is opbig=0x48 & op67=3 & mode=7 & regan=1; r2mfl0; d32  { movemptr = d32; build r2mfl0; }
```

I think this is semi-correct, just add this to your 68000.sinc.

**Comment by emteere** [comment]
There are three more that were missed, so all 4 additional movem instructions are:

```
:movem.w r2mfw0,(d16)".w"	is opbig=0x48 & op67=2 & mode=7 & regan=0; r2mfw0; d16	{ movemptr = d16; build r2mfw0; }
:movem.w r2mfw0,(d32)".l"   is opbig=0x48 & op67=2 & mode=7 & regan=1; r2mfw0; d32  { movemptr = d32; build r2mfw0; }

:movem.l r2mfl0,(d16)".w"	is opbig=0x48 & op67=3 & mode=7 & regan=0; r2mfl0; d16	{ movemptr = d16; build r2mfl0; }
:movem.l r2mfl0,(d32)".l"   is opbig=0x48 & op67=3 & mode=7 & regan=1; r2mfl0; d32  { movemptr = d32; build r2mfl0; }
```

**Comment by NTxC** [comment]
Thanks mumbel and emteere. Your suggested code works great.

**Comment by lab313ru** [comment]
Which game is it?:
- Blockbuster World Video Game Championship II
- Video Game Championship II
- Daffy Duck in Hollywood
- Judge Dredd - The Movie

**Comment by NTxC** [comment]
Daffy Duck in Hollywood. Hah, how'd you know? That protection code? Is it something only Probe Entertainment did?

**Comment by lab313ru** [comment]
I just seeked for bytes of that function in GoodGEN collection. I don't sure about protection. Maybe some compiler shit.
