### ISSUE TITLE
DWARF Parser error on 0-width struct elements

### ISSUE THREAD

**Issue by hedgeberg** [NationalSecurityAgency/ghidra#2191]
**Describe the bug**
When the DWARF parser encounters a struct member with 0 width (i.e. some lock elements, depending on the compiler, version, and target), it produces an error. It continues to operate, but will record a huge number of errors, and seems to produce a huge number of `.conflict` structs. 

An example error line is: 
`ERROR Unable to add member raw_lock to structure /DWARF/_UNCATEGORIZED_/rwlock_t[DWARF DIE 238323b], skipping: Offset 0 is beyond end of structure (0). (DWARFDataTypeImporter)`

**To Reproduce**
1. Build a copy of the Linux Kernel with debugging symbols with GCC 4.x for an ARM target using buildroot or some other build system
2. Run the DWARF analyzer.
3. If it manages to finish without crashing (it will eat up memory rapidly -- upwards of 8 GB if available) the output will be filled with `.conflict` structs, and the log will be full of errors. 

**Expected behavior**
While I'm assuming this is a really odd edge case, the DWARF parser should probably be updated able to handle it without failing if at all possible.

**Environment (please complete the following information):**
 - OS: Several -- Arch Linux w/ Kernel 5.7.8, Custom Linux with Kernel 4.x, Windows 10 
 - Java Version: 11.0.2
 - Ghidra Version: 9.2 DEV (latest commit)

**Additional context**
I'm trying to rebuild the kernel to see if buildroot using newer versions of GCC generate DWARF files that have the same issue. Unfortunately, I can't provide the binary as this build is done on an airgapped machine but it shouldn't be terrible to reproduce if needed.

**Comment by dev747368** [comment]
'Fixed' in 75fb14933fa33741d50ab8f6c400c07dc9302910.

Zero width fields are detected and logged in the comment of the individual structure data type.
