### ISSUE TITLE
AssertException: Multiple modules collided with same name

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2193]
**To Reproduce**
1. Install an extension which is already installed

**Expected behavior**
The existing plugin should be replaced

**Environment (please complete the following information):**
 - Ghidra Version: 9.2 c1095fe9383b153fffdfa7453679512124a60d87

**Comment by mitp0sh** [comment]
This is just an assumption, but I believe that this is happening because cached class files in the ghidra user home folder are not properly deleted on removal (on windows e.g. following path: %USER%\.ghidra\.ghidra_9.2_DEV\Extensions\NAMEOFYOUREXT)

The very simple WORKAROUND is to remove the cached extension folder. Once done, there error is gone at least as long as removing the extension fails again.

Hope that helps for the moment. Hope this is gonna be fixed, it's annoying ;D

mitp0sh

**Comment by ryanmkurtz** [comment]
When you uninstall an extension through the GUI, it is simply marked for delete.  The next time you startup Ghidra, Ghidra should delete any of these marked extensions completely from disk.

**Comment by astrelsky** [comment]
> When you uninstall an extension through the GUI, it is simply marked for delete. The next time you startup Ghidra, Ghidra should delete any of these marked extensions completely from disk.

How is it marked for deletion? I did follow the instructions to restart Ghidra. If it is scheduled for removal through the os then the deletion occurs upon reboot.

**Comment by ryanmkurtz** [comment]
> How is it marked for deletion? I did follow the instructions to restart Ghidra. If it is scheduled for removal through the os then the deletion occurs upon reboot.

When an extension is uninstalled, its `Module.manifest` file is renamed to `Module.manifest.uninstalled`.  When Ghidra starts up the next time, it looks for these files and deletes their extension directories.

**Comment by astrelsky** [comment]
> > How is it marked for deletion? I did follow the instructions to restart Ghidra. If it is scheduled for removal through the os then the deletion occurs upon reboot.
> 
> When an extension is uninstalled, its `Module.manifest` file is renamed to `Module.manifest.uninstalled`. When Ghidra starts up the next time, it looks for these files and deletes their extension directories.

hmm. Are they removed before or after classes are loaded? I'm wondering if the class loader is finding them before they are deleted and then failing or something. It could also be that because the extensions are stored in the new location and nothing is found there that the extension in the old `Ghidra/Extensions` path aren't actually being marked for removal.

**Comment by ryanmkurtz** [comment]
After the classes are loaded.  Also, with the new location of the extensions, i don't think it's possible to remove extensions stored in Ghidra/Extensions through the GUI.
