### ISSUE TITLE
RISC-V: lui assumes signed immediates

### ISSUE THREAD

**Issue by derSteFfi** [NationalSecurityAgency/ghidra#2198]
**Describe the bug**
```lui``` wrongly assumes immediates as signed.

**To Reproduce**
disassemble any binaries with e.g. ```lui a0,0x80000```, will show ```lui a0,0xFFF80000``` or ```lui a0,-0x80000```

**Expected behavior**
Listing should show e.g. ```lui a0,0x80000```
(works correctly for immediates without highest bit set, e.g. ```lui a0,0x20000```)

**Environment (please complete the following information):**
 - OS: Archlinux
 - Java Version: 14.0.2
 - Ghidra Version: 9.2.0-DEV

**Comment by mumbel** [comment]
@derSteFfi   yeah, looks like I had a note there that something wasn't making sense at the time, thanks for reporting.  Put in a PR for a fix.

**Comment by ghidra1** [comment]
#2333 has been merged.  Does that merge resolve this issue?

**Comment by ghidra1** [comment]
#2333 has been merged.  Does that merge resolve this issue?

**Comment by mumbel** [comment]
Can close this one as well

**Comment by emteere** [comment]
Fixed with PR #2333.  Will be in 9.2 and master
