### ISSUE TITLE
Invalid parsing of GuardCFFunctionTable (PE x64 / CFG)

### ISSUE THREAD

**Issue by marpie** [NationalSecurityAgency/ghidra#220]
**Describe the bug**
Ghidra correctly recognizes the `IMAGE_LOAD_CONFIG_DIRECTORY64` structure. Then it seems to categorize the `GuardCFFunctionTable` as containing an array of `ImageBaseOffset32` (`ibo32`) entries.

**Edit**:
It seems like the error is originating in `markupCfgFunctionTable` of [`/src/Base-src/ghidra/app/util/bin/format/pe/ControlFlowGuard.java` Line `131`](https://github.com/0xeb/Ghidra-unoffical-src/blob/d998c7e6104874f0658b0207e8b182a88711d973/src/Base-src/ghidra/app/util/bin/format/pe/ControlFlowGuard.java#L131).

**To Reproduce**
1. Load any CFG-protected binary into Ghidra (e.g. AMSI.dll)
2. Perform default analysis
3. Navigate to `GuardCFFunctionTable`

**Expected behavior**
The `GuardCFFunctionTable` should be parsed as an array of *dword*s separated by `\x00` as shown in the second screenshot below.

**Screenshots**

Ghidra-parsed `GuardCFFunctionTable`:
![image](https://user-images.githubusercontent.com/703785/54510512-e3858a80-494d-11e9-9612-caff942e855e.png)

IDA-parsed `GuardCFFunctionTable` :
![image](https://user-images.githubusercontent.com/703785/54510530-fb5d0e80-494d-11e9-85c4-bcc402ecc5b5.png)

**Environment (please complete the following information):**
 - OS: Win10
 - Java Version: jdk-11.0.2
 - Ghidra Version: 9.0

**Additional context**

I used the following sample:
Filename: `AMSI.dll`
SHA256: `F675D2A8686A7CFD7A7056AC490E159A17D6B728420CF15C4EE26C670437370A`
MD5: `21EAA9941DB9CA4B41A5FFCBFE4CA9A5`

**Comment by ryanmkurtz** [comment]
For PE, ibo32 is often used in place of a DWORD that represents an RVA (relative virtual address).  It is an intentional convenience, as it allows you to easily see and navigate to the target RVA defined by the DWORD.

**Comment by ryanmkurtz** [comment]
For the extra 0 byte between table entries, we'll have to investigate a bit.  Thanks for reporting this!

**Comment by ryanmkurtz** [comment]
We need to take the top 4 bits of `IMAGE_LOAD_CONFIG_DIRECTORY64.GuardFlags` into account when laying down the `GuardCFFunctionTable`.  This represents the additional # of bytes for each table entry.

Can you please post your GuardFlags value to confirm this is the issue?  Thanks!

**Comment by ryanmkurtz** [comment]
This will be fixed in our next release.

**Comment by marpie** [comment]
> We need to take the top 4 bits of `IMAGE_LOAD_CONFIG_DIRECTORY64.GuardFlags` into account when laying down the `GuardCFFunctionTable`. This represents the additional # of bytes for each table entry.

Yes, this seems to work. Thank you for your quick triage.
