### ISSUE TITLE
Question: Plt analysis process inside Ghidra

### ISSUE THREAD

**Issue by 08A** [NationalSecurityAgency/ghidra#2201]
I am currently working on plt analysis for Radare2.
And we have currently have a problem with the identification of each entries.
https://github.com/radareorg/radare2/issues/17300

So i tried to understand what Ghidra is doing.
From what i understand Ghidra separate the binary loading and the plt analysis.
I didn't found where is analysis is done. Could you explained how you identify each plt entries, and associate them with a got entry.
(my supposition is that you use some king of emulation and xref)
Bonus: some study papers or the location of the files responsible for this part of the analysis inside Ghidra

**Comment by ghidra1** [comment]
During ELF import processing the 'ElfProgramBuilder' invokes the method 'processGotPlt' on the load adapter which may be customized for a specific processor (e.g., 'MIPS_ElfExtension').  The adapter may manipulate the PLT to the extent necessary to achieve linkage to external functions to satisfy Ghidra's needs (e.g., decompilation).  Markup of PLT thunk functions generally occurs during analysis as they are encountered within the program flow.

**Comment by 08A** [comment]
Why did you choose this method?

Is there any paper on the subject that explain your choice?

**Comment by ghidra1** [comment]
Methods developed for Ghidra are purely to obtain adequate listing markup within the tool.  They may not be applicable for other applications.  Sorry, no papers on the subject.
