### ISSUE TITLE
Set data type of external data

### ISSUE THREAD

**Issue by Elmegaard** [NationalSecurityAgency/ghidra#2206]
I am having an issue with setting the type of some externally referenced data. 

It always assumes the datatype is "undefined" as seen in this screenshot:
![](https://i.imgur.com/Ra92wGF.png)

I can't figure how to change that data type. I have already changed it both in the external location and where that is referenced. But it doesn't seem to stick. In the external location it works as intended, but everywhere it is referenced externally it doesn't work.

And I get decompiled code that looks like this:
![](https://i.imgur.com/yt49uN8.png)

But since I already have that struct created I would like for it to automatically assume that is the data type everywhere it is used.

If I right click anywhere the reference is used and hit retype global, I get this:
![](https://i.imgur.com/YB4NrZc.png)

If I change that and save, it does nothing and when I attempt to retype it again I can see it never changed the type.

**Comment by ghidra1** [comment]
We apologize, however setting data types on external symbols and not yet fully supported.
