### ISSUE TITLE
Changing format of constants in decompile window

### ISSUE THREAD

**Issue by alexdevsec** [NationalSecurityAgency/ghidra#221]
Is there a way to change the way that constants are displayed in the decompile pane?

In the following screenshot (of decompiled /bin/ls), it renders the second parameter as 0x3e. It's more intuitive that that be shown in decimal ('62'). 

I found out about the tooltip, but I'd like my changes to be saved and rendered inline (in the same way I can change function names, etc).

There's probably a way but I don't see it in the UI.

- A

![del-ghidra](https://user-images.githubusercontent.com/47580386/54550134-d08cad80-4981-11e9-9431-61c9510b14c8.png)

**Comment by alexdevsec** [comment]
Okay, that works, thanks.

It is a *bit* awkward, thought. I don't know what's involved, but having that as a popup menu item when highlighting the constant in the decompile window would be a useful feature.

Is that worth opening a feature request for?

- A

**Comment by emteere** [comment]
We've had this question previously.  I'll have to look if a feature request was noted.  When the last question came in we did discuss that it should be done directly in the decompiler window.
