### ISSUE TITLE
False negatives in getParameters()

### ISSUE THREAD

**Issue by jahatfi** [NationalSecurityAgency/ghidra#2212]
Opening a new issue for this function, as I'm pretty sure there is in fact a bug (or is it a poor feature?) in getParameters(). This function returns false negatives (doesn't not detect actual parameters) when parameters are not copied onto the stack.  For example, for something like this code:
```c
#include<stdio.h>
void print(int a){
   printf("My number: %d\n", a);
}

void print_proxy(int b){
   print(b);
}

int main(void){
   int x = 5;
   print_proxy(x);
   return 0;
}
```
Ghidra's getParameters() seems to think that print_proxy() takes no parameters, because b is never copied onto the stack.  Obviously my trivial example above is almost too simple to be of concern, but I have encountered real-world functions that never copy (some) parameters to the stack.  I think this is a bug, not a feature.  I got around this problem in a script by getting the decompiled code (which seems to be correct, even in this case), and just parsing the parameters out of the decompiled code string.  Thoughts?  Would you like me to take a crack at patching it?

_Originally posted by @jahatfi in https://github.com/NationalSecurityAgency/ghidra/issues/2085#issuecomment-675243580_

**Comment by astrelsky** [comment]
Have the parameters for `print_proxy` been committed? I may be mistaken but I believe `Function.getParameters()` only returns committed parameters/return types.

**Comment by jahatfi** [comment]
Is there any other way to get parameters that haven't been committed?   It seems that it would defeat the purpose of scripting to have to go make manual changes/commits before an API feature could be of any use.

**Comment by astrelsky** [comment]
You would need to interface directly with the Decompiler. This can be done utilizing the [FlatDecompilerAPI](https://ghidra.re/ghidra_docs/api/ghidra/app/decompiler/flatapi/FlatDecompilerAPI.html) and the [DecompInterface](https://ghidra.re/ghidra_docs/api/ghidra/app/decompiler/DecompInterface.html). You would use the DecompInterface to get the DecompileResults->HighFunction->FunctionPrototype. You should be able to get what you need from the FunctionPrototype obtained this way.

**Comment by jahatfi** [comment]
Ah, this looks like what I need.  I'll take a look!  Thank you!
