### ISSUE TITLE
Creating a bookmark or comment from a Ghidra plugin causes a NoTransactionException

### ISSUE THREAD

**Issue by rlee287** [NationalSecurityAgency/ghidra#2217]
**Describe the bug**
See title. (Note that this is about the **plugin** interface for extending GUIs, not the **scripting** interface.

**To Reproduce**
1. Unzip the attached Zip file.
2. Build the plugin extension with `GHIDRA_INSTALL_DIR=[location] gradle`.
3. Install the plugin in Ghidra.
4. Configure the CodeBrowser tool to include the plugin.
5. Open a new binary (arbitrary, can be auto-analyzed, but no other changes) in CodeBrowser.
6. Enter a valid address into the text box of the plugin GUI.
7. Press either "Add pre-comment" or "Add note bookmark".
8. Observe the error message that appears.

**Expected behavior**
The bookmark or comment is created successfully.

**Attachments**
Zip file of the plugin source code (The `tracebacks_java.txt` file contains the stack traces that appeared when the Uncaught Exception propagated upwards.)

[ghidra_annotation_bug_proj.zip](https://github.com/NationalSecurityAgency/ghidra/files/5104396/ghidra_annotation_bug_proj.zip)

**Environment (please complete the following information):**
OS: Linux Mint 19.3
Java Version: OpenJDK 11.0.8
Ghidra Version: 9.1.2 and 9.2-DEV (c1095fe9383b153fffdfa7453679512124a60d87)

**Additional context**
This may not be the correct way to create bookmarks/comments from a plugin, but I've found no documentation about any other way to do this.

**Comment by dragonmacher** [comment]
All modifications to the program must happen in a transaction.  This is handled for you if you submit modifications inside of a command using the tool.  

A command is a simple interface/abstract class that has a callback for you to perform work.  This work is can be done in a background thread (via `tool.execuateBackroundCommand()`) so that the UI does not lock-up.  Also, transaction management is done for you.

As an example, this is a snippet from Ghidra's `BookmarkPlugin`:

```
	public void setNote(Address addr, String category, String comment) {

		CompoundCmd cmd = new CompoundCmd("Set Note Bookmark");

		if (addr != null) {
			// Add address specified within bookmark
			cmd.add(new BookmarkDeleteCmd(addr, BookmarkType.NOTE));
			cmd.add(new BookmarkEditCmd(addr, BookmarkType.NOTE, category, comment));
		}
		else {

			// Create address set with first address only
			AddressSet set = new AddressSet();
			AddressRangeIterator iter = currentSelection.getAddressRanges();
			while (iter.hasNext()) {
				Address minAddr = iter.next().getMinAddress();
				set.addRange(minAddr, minAddr);
			}

			// Add a bookmark at the first address of each address range in
			//   the current selection
			cmd.add(new BookmarkDeleteCmd(set, BookmarkType.NOTE));
			cmd.add(new BookmarkEditCmd(set, BookmarkType.NOTE, category, comment));
		}
		tool.execute(cmd, currentProgram);
	}
```

**Comment by rlee287** [comment]
Thanks for replying. I will look it over, and if this works correctly for me I will close the issue.

**Comment by rlee287** [comment]
I can confirm that using this method of creating bookmarks and comments works as expected. While this should be documented better, I will close this issue now.
