### ISSUE TITLE
Ghidra extension `lib` Dependency Management through Gradle

### ISSUE THREAD

**Issue by rlee287** [NationalSecurityAgency/ghidra#2219]
**Is your feature request related to a problem? Please describe.**
Ghidra extensions are built using Gradle, but the jars for external dependencies need to be placed in the `lib` folder manually.

**Describe the solution you'd like**
A modification to the `GhidraBuild/Skeleton/buildTemplate.gradle` file to include Gradle tasks that automatically copy the JARs into the `lib` folder.

**Describe alternatives you've considered**
Manually copying the dependency JARs over, as is the current workflow.

**Additional context**
I have a patch for this ready (which I wrote for my own Ghidra plugin's build process), but I am gauging interest in adding this feature first.

**Comment by ryanmkurtz** [comment]
The intent was that if your extension requires a jar, you put it in the extension's lib directory and it will get automatically bundled.  When the extension gets installed into Ghidra, Ghidra knows to put anything found in lib directories onto the classpath.  Is this what you are referring to as placing them manually?

**Comment by rlee287** [comment]
That was what I was referring to as "placing them manually". The patch that I have would allow the specification of dependencies in Gradle (e.g. downloading from MavenCentral), and would then copy those jars from Gradle's Jar storage location into the lib folder as part of the build process. If the dependencies were only specified in Gradle, the build would succeed, but Ghidra would throw errors due to being unable to find the dependency Jar at runtime.
