### ISSUE TITLE
Cant Import anything

### ISSUE THREAD

**Issue by JujharSingh** [NationalSecurityAgency/ghidra#222]
**Describe the bug**
Whenever I try to import anything it shows the error "Could not find importer service". I have tried reinstalling Ghidra.

**To Reproduce**
Force shutdown your computer while Ghidra is running (not completely sure if this caused it)

**Expected behavior**
I expect it to import my file.

**Screenshots**
![image](https://user-images.githubusercontent.com/9494428/54581486-dc579d00-4a71-11e9-9e63-4c8c980d73f8.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Additional context**

**Comment by JujharSingh** [comment]
I deleted %USERPROFILE%\.ghidra and it worked! seemed to be an issue with the configuration file for the UI.

**Comment by ryanmkurtz** [comment]
They mean `c:\users\<user>\.ghidra\`
