### ISSUE TITLE
Decompiler sees strange input register

### ISSUE THREAD

**Issue by rfalke** [NationalSecurityAgency/ghidra#2222]
**Describe the bug**
The register is fully defined but ghidra sees an `in_EDX`. For example in `inst_0_values_var_0()`.

Minor:
- return type should be a 32bit type. Maybe this is also the cause of this bug.
- even if it is an input it should be added to the function signature as a parameter

**To Reproduce**
1. decompile https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/stress_int_ia32/ia32_elf_base_inst__1_var__no_complex/subject.exe
2. Output is:
```
longlong inst_0_values_var_0(void)

{
  uint in_EDX;
  
  return (ulonglong)in_EDX << 0x20;
}
```

**Expected behavior**
Output should be:
```
int32_t inst_0_values_var_0(void)

{ 
  return 0;
}
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "11.0.5" 2019-10-15
 - Ghidra Version: 9.1.2_PUBLIC

**Additional context**
- Background: http://kronotai.com/wordpress/339/testing-decompiler-semantics/

**Comment by astrelsky** [comment]
![Capture](https://user-images.githubusercontent.com/46897303/90987381-a2d56c00-e558-11ea-81ae-d57e77e6b95c.PNG)

That is on Ghidra 9.1.2_PUBLIC. I get the same results on 9.2.

**Comment by rfalke** [comment]
Then this is related to how ghidra is called?!

From https://github.com/rfalke/decompiler-subjects/blob/master/scripts/update_ghidra.sh:
```
...
(cd "$dir" && "$GHIDRADIR/support/analyzeHeadless" project_loc project_name -import subject.exe -scriptPath $root/scripts -postScript ghidra_script.java >>out 2>&1 ; echo "$?" >error_code) || true
...
```

And https://github.com/rfalke/decompiler-subjects/blob/master/scripts/ghidra_script.java is:
```
import java.util.List;
import java.util.ArrayList;
import java.io.File;

import ghidra.app.script.GhidraScript;
import ghidra.app.util.Option;
import ghidra.app.util.exporter.CppExporter;

public class ghidra_script extends GhidraScript {

    @Override
    public void run() throws Exception {
        String execPath = currentProgram.getExecutablePath();
        String execDir = execPath.substring(0, execPath.lastIndexOf(File.separator) + 1);
        File outputFile = new File(execDir + "/ghidra.c");

        CppExporter cppExporter = new CppExporter();
        List<Option> options = new ArrayList<Option>();
        options.add(new Option(CppExporter.CREATE_HEADER_FILE, new Boolean(false)));
        cppExporter.setOptions(options);
        cppExporter.setExporterServiceProvider(state.getTool());
        cppExporter.export(outputFile, currentProgram, null, monitor);
        println("Wrote " + outputFile);
    }

}
```

How could this differ from your way of using the GUI?

**Comment by astrelsky** [comment]
It has nothing to do with how ghidra is started. When the parameters, return type and calling convention of a function have not been committed the decompiler will make educated guesses by looking at register usage and possible calling conventions to produce output to aid the **user** in determining the correct parameters, return type and calling convention. Setting the return type to int32_t, parameters to void and calling convention to default will produce the expected output.

**Comment by rfalke** [comment]
Ok than the bug report is that for the given input program ghidra should make a better initial guess regarding the function return type (assuming that it is the reason for the output from the initial comment).

**Comment by rfalke** [comment]
I have now constructed a similar test for x64 at https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/stress_int_x64/x64_elf_base_inst__1_var__no_complex/subject.exe

Sadly the behavior of ghidra is similar: it sees the return type twice the real width. In this case 16 bytes instead of 8 bytes.

Output:
```
undefined  [16] inst_0_values_var_0(undefined8 param_1,undefined8 param_2,ulong param_3)

{
  return ZEXT816(param_3) << 0x40;
}
```

Expected:
```
long/int64_t/... inst_0_values_var_0()
{
  return 0;
}
```

It looks like there is some reason why ghidra sees the double width. Any idea what it could be? I may change the code in the test subject to work around this.

**Comment by ghidra1** [comment]
Frequently smaller operations utilize larger registers whose most-significant bytes are unaffected from their original input state.  Without constraining the varnode to its proper smaller datatype things may not appear as you would like to see.  With such a simple function the best constraint is to set the proper smaller return datatype or full signature.  Without any constraints, the full size return register associated with the calling convention prototype model will be used with its preferred datatype.

**Comment by rfalke** [comment]
For a 32bit i386 executable ghidra sees a longlong return type. This is odd. Sure it is possible to return these 64 bit in the register pair edx:eax but this not the common case. There is no 64bit register for this executable.

For a 64bit x64 executable ghidra sees a 16 byte return type. Same here: it is odd, not common and there is no 128 bit return register.

**Comment by caheckman** [comment]
These examples aren't following the standard gcc compiler calling conventions. In particular, a compiler would not generally treat EDX/RDX as a saved register: this is why the decompiler emits the odd return value.  Because EDX/RDX is not usually saved and restored, the decompiler treats the PUSH/POP instructions as evidence that EDX/RDX is important both as some kind of incoming value and as an important piece of whats returned by the function.

If these samples were produced (as I assume) using inlined assembly, you could try removing the PUSH EDX and POP EDX instructions in the first sample and the PUSH RDX and POP RDX in the second sample.

If there really is a different calling convention, this would need to be modeled in the compiler specification (.cspec) in order to decompile these samples automatically as expected.

**Comment by rfalke** [comment]
Thank you for this hint. I expected something not obvious like this.

For 32bit (x86) this fixes all return types. For 64bit (x64) from 840 cases 100 are now ok but the remaining 740 have the same double size return type. Independent of the return type the code in the body is now ok since there are no more strange `ZEXT816` and `CONCAT88` calls.

From my side this issue can be closed but this behavior may be stated more explicit in same way (documentation, output comment,...).
