### ISSUE TITLE
Renaming user account locks owner out of project

### ISSUE THREAD

**Issue by notyouraveragehooman** [NationalSecurityAgency/ghidra#2229]
**Describe the bug**
If the owner of a Ghidra project renames their user account, they will be locked out of the project.

**To Reproduce**
1. Rename user account.
2. try to open project.
3. Error stating that the project does not belong to you.

**Expected behavior**
Ghidra should have some other way of detecting whether or not a user the owner of a project. With the current method, a user who is not the owner is able to gain write access to a project simply by changing their account name.

**Environment (please complete the following information):**
 - OS: macOS 10.15.6
 - Java Version: 14.0.1
 - Ghidra Version: 9.1.2

**Comment by ghidra1** [comment]
In this situation you must edit the project property file (project.prp) with a text editor and change your user name associated with the OWNER attribute.  This is an XML file and is located at the root of the Ghidra project directory (*.rep)

**Comment by inakilbss** [comment]
in case anyone else finds this through web search, if there is no project.prp one will be generated when you open the project, so if you want to use git you can gitignore this file, just make sure there's nothing else in it
