### ISSUE TITLE
NeLoader and supporting classes fail to recognise referenced API names (16-bit Windows)

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#2233]
**Describe the bug**
When loading a Windows 16-bit "NE" file to analyse, the external references to functions in dependent libraries (like KERNEL, USER etc.) don't reflect thier API names and instead appear as "Ordinal_xxx".

(Also, it appears that the compilers of those days didn't store the file extension of dependent librares either (so to find the "USER.DLL", I had to create a copy called "USER"!)

**To Reproduce**
1. Load a Windows 16-bit "NE" file into a Ghidra project to analyse
2. Go to the Decompile Tool
3. Look at the Thunks in the "Listings: ..." view and/or look into the "Imports" section of the "Symbol Tree" view
4. See the names imported!

**Expected behavior**
To see the correct API name, and therefore be able to analyse better.  (Those old Microsoft libraries only seem to hold the exported API names in capital letters, so some additional lookup is required.)

**Screenshots**
![image](https://user-images.githubusercontent.com/67698927/91635831-98512180-e9f3-11ea-97a0-f2763a7f79d8.png)

**Attachments**
See screenshot.

**Environment (please complete the following information):**
 - OS: Windows 10 (2004)
 - Java Version: [e.g. 11.0.2
 - Ghidra Version: 9.1.2 and current Master branch (9.2-DEV) commit  c1095fe9383b153fffdfa7453679512124a60d87

**Additional context**
My solution is to modify the method "private void processModuleReferenceTable" in class "/Features Base/src/main/java/ghidra/app/util/opinion/NeLoader.java" to add the following:

1) the reference below:
`		ReferenceManager refManager = program.getReferenceManager();`

2) and within the "for loop" after the call to "functionManager.createThunkFunction(...);" add the following:
```
					refManager.addExternalReference(addr, moduleName,
							callname, null, SourceType.IMPORTED, 0, RefType.DATA);
```

PS, other simple issues include:

1) registers now are in capitals, so in method "private void setRegisterDS(...)":
`		Register ds = context.getRegister("`**ds**`");
`
becomes
`		Register ds = context.getRegister("`**DS**`");`

2) I believe library names should be case insensitive.  Therefore the below needs adding to the same class:
```
	@Override
	protected boolean isCaseInsensitiveLibraryFilenames() {
		return true;
	}
```

3) when loading dependent libraries (like "USER.DLL") the ".export" files produced seem to contain multiple exports that are for the same ordinal value (so far I've noticed they all refer to ones named "Ordinal_xxx" apart from 1)!  We need a way to pick up that one.  The current implementation of class "/Features Base/src/main/java/ghidra/app/util/opinion/LibrarySymbolTable.java" uses "org.jdom.*" which cannot sort the "Element" objects.  Maybe Ghidra need updating to use "org.jdom2.*", a bigger job than I wanted!

**Comment by Wall-AF** [comment]
There is also something strange going on if an ".export" file is (re)created during the import of a file and its dependendents. (i.e. the date in the ".export" file doesn't match the file system date of the dependent file).

The correct API names are missing again.

During my investigation I had my "user.export" file recreated every run!  I determined it was a wierd bug in the method "write(...)" in class "/Features Base/src/main/java/ghidra/app/util/opinion/LibrarySymbolTable.java" that converted the date 'Sun Jun 21 **13**:41:38 BST 2020' (the USER file date) to 'Sun Jun 21 **01**:41:38 BST 2020' when writing the file!

**Comment by emteere** [comment]
In the created .exports file are the name to oridinal mappings correct?
Are you using the original windows .DLL files for Windows 3.10?
Do the .DLL files contain the name, or just the ordinal?

Will take a look at the date format.

**Comment by emteere** [comment]
The .exports files for 16-bit aren't provided.  I'm not sure they would be searched depending on the code.  I'd have to look further.  I don't recall when microsoft started just using the ordinal for many .dll files.
You may need to generate the .exports file if the ordinal/name mapping is not occurring in the generated .exports file.
See: [Ghidra/Features/Base/data/symbols/README.txt](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/data/symbols/README.txt)

**Comment by Wall-AF** [comment]
I believe that the ".exports" files are correct except they have multiple references for the same ordinal (which seems to be expected), however only one isn't "Ordinal_xxx".
I have both the original Windows DLLs from my Windows 3.11 and the DEBUG ones provided with MSVC 1.51.
The apps I'm trying to RE use ordinals (to import), but my copy of the Windows libraries export pascal-like (all uppercase) names.

I've include a couple of the generated ".exports" files here:
[win16_exports.zip](https://github.com/NationalSecurityAgency/ghidra/files/5149671/win16_exports.zip)

**Comment by ryanmkurtz** [comment]
@Wall-AF #4474 has revealed some other bugs with the exports files that might be related to this issue.  Can you provide a test binary with at least one dll that isn't working?

**Comment by Wall-AF** [comment]
Included [here](https://github.com/NationalSecurityAgency/ghidra/files/9349682/ExampleNEFiles.zip) are several Windows 3.11 system files and 1 of the files I'm trying to reverse.

**Comment by ryanmkurtz** [comment]
Thanks! I'll use these for testing as we make improvements to the library code.  It appears that when there are multiple exports at 1 address we are applying the wrong symbol name with its associated ordinal, like we are for PE.

**Comment by mwehrmeyer** [comment]
How can the .export files linked above be imported into ghidra?

**Comment by ryanmkurtz** [comment]
@Wall-AF I'm working on this now.  Do you know if NE wil always leave the library extensions off?  Or do you think the references can exist with the extension as well?

**Comment by Wall-AF** [comment]
AFIK the extensions aren't used in this situation.

**Comment by ryanmkurtz** [comment]
@Wall-AF [Here is a branch](https://github.com/ryanmkurtz/ghidra/tree/NeLoader_libs) i'm working on if you want to test it out.

**Comment by Wall-AF** [comment]
@ryanmkurtz [See my comment in your branch](https://github.com/NationalSecurityAgency/ghidra/commit/e29a4b3ae9e8116c4b715ce84223d3b7857a883e#commitcomment-82405628)

**Comment by ryanmkurtz** [comment]
@Wall-AF The branch has been updated to handle all extension types and recursive library import should be working now too.

**Comment by ryanmkurtz** [comment]
> Included [here](https://github.com/NationalSecurityAgency/ghidra/files/9349682/ExampleNEFiles.zip) are several Windows 3.11 system files and 1 of the files I'm trying to reverse.

@Wall-AF, do you think it makes sense to include pre-generated .exports files for these samples in the Ghidra release?  I am enabling support for a win16 directory.  If so, I just wanted to confirm that all the files you provided are from a standard Windows install (I am not considering VOICEBAR)

Also, if you have worked with the older MZ format, do you know if those files can import/export by ordinal? Thanks!

**Comment by Wall-AF** [comment]
@ryanmkurtz The files I included (apart from VOICEBAR.EXE) are from a clean Windows 3.11 install.

**Comment by ryanmkurtz** [comment]
Thanks i've used to to generate `.exports` files that we can include in the release.

**Comment by ryanmkurtz** [comment]
Do you happen to know about the MZ format and if it uses ordinals? Hopefully not.

**Comment by ryanmkurtz** [comment]
Ok thanks I'll research it.  I thought maybe you came across it in your 16-bit travels.

**Comment by greg-kennedy** [comment]
> Thanks i've used to to generate `.exports` files that we can include in the release.

Would you accept more Win16 exports?  These are just a sample of files from a 3.11 install but I've found others (SOUND.DRV, KEYBOARD.DRV, WINSOCK.DLL etc) getting pulled in by files I'm reversing.  Would be nice to have a full set :)

**Comment by ryanmkurtz** [comment]
@greg-kennedy, sure!

**Comment by Wall-AF** [comment]
@ryanmkurtz I notied you've left the
https://github.com/NationalSecurityAgency/ghidra/blob/f62320a50bfc481dc0c95387735afdddc71bb6f4/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/NeLoader.java#L566-L569
unimplemented.  Can this be looked at?

In the `KERNEL.EXE` & `KRNL386.EXE`, I know that constants `__AHINCR` & `__AHSHIFT` are exported at `Ordinal_113` & `Ordinal_114` (although I've conflicting information as to which is which!), but they aren't recognised and appear in red in the `Symbol Tree`.

**Comment by ryanmkurtz** [comment]
Sure, but would you mind opening a new ticket?

**Comment by Wall-AF** [comment]
> @Wall-AF I'm working on this now. Do you know if NE wil always leave the library extensions off? Or do you think the references can exist with the extension as well?

Hi @ryanmkurtz.  I know this is closed, but I've found some relevent information regarding this from the book "Undocumented Windows." by Andrew Schulman (Subtitle: A programmer's guide to reserved Microsoft Windows API functions (Covers Windows 3.1 and 3.0)) stating that:
![image](https://user-images.githubusercontent.com/67698927/197751632-e68a6825-63c4-4652-a5b5-72d03ec0e4da.png)
Therefore, in order for Ghidra to find and add related "modules" into your project, it needs to examine all files in the directories listed and if there's more than one file using that "module" name, give the user the list to choose which one they require!  What are your thoughts???

**Comment by ryanmkurtz** [comment]
Very interesting, thanks for completing our understanding of how it is supposed to work.  I wonder how the real loader deals with multiple matches when it searches.  Or, does it even search?  Does it instead always rely on the library files being called out by name in a `.ini` file, like mentioned in the last paragraph?

**Comment by Wall-AF** [comment]
I think I'm right in saying they come from the `system.ini` `[boot]` section.

Here's one I made earlier from my virtual machine!!!!!!
```
[boot]
shell=progman.exe
network.drv=wfwnet.drv
mouse.drv=mouse.drv
language.dll=
sound.drv=mmsound.drv
comm.drv=comm.drv
keyboard.drv=keyboard.drv
system.drv=system.drv
386grabber=SVGA256.3GR
oemfonts.fon=vgaoem.fon
fixedfon.fon=vgafix.fon
fonts.fon=vgasys.fon
display.drv=SVGA256.DRV
drivers=mmsystem.dll
```

**Comment by ryanmkurtz** [comment]
Well, I guess `NeLoader` could have an additional option that is the path to an `.ini` file, which could be used during the generic library search.  That should make it so we don't have to parse each library looking for a matching module...the `.ini` would just specify it.  Am I understanding things correctly?

**Comment by Wall-AF** [comment]
That would work.  However I wonder if that solution puts too much on the (especially novice) user.  Having Ghidra see what files have the appropriate module name may help.

**Comment by ryanmkurtz** [comment]
Yea, it's not perfect.  I have a couple of concerns with searching for the modules though:
* It will be slow, especially if the novice user never changes the default library search paths on disk.  What is currently a quick file name comparison will turn into a parse of every file encountered.
* It's seemingly not was the real loader does.  
* It doesn't fit into our current design very well.  While this is in general not a good reason not to do something, it will make the task much more complicated, and the extra development time needs to be weighed against the value gained.

Since this doesn't seem to be a blocker for anyone at the moment, there's some time to think of a good solution.  I am also dealing with other loaders needing to evolve to keep pace with what their real counterparts are doing in modern versions of operating systems, which could also affect the overall design of how we load libraries.  Perhaps this is moving to a model where it makes for sense for every loader to handle their own library searching/loading in their own custom way.
