### ISSUE TITLE
how convert asm file a lenguaje c in ghidra?           ¿Cómo convertir un archivo asm a lenguaje c en ghidra?

### ISSUE THREAD

**Issue by crisdax** [NationalSecurityAgency/ghidra#2234]
Hello everyone i need convert asm file ( example : program.s) a lenguaje c , i dont now how , i will happy your help me , or indications to get it
gracias.

Hola a todos, necesito convertir un archivo asm (ejemplo: program.s) a lenguaje c, no sé cómo, estaré encantado de que me ayuden o indicaciones para obtenerlo
thanks

**Comment by emteere** [comment]
If I understand you correctly.  You would need to assemble the program.s into an object file program.o using an appropriate assembler like gnu-as.  You can then import the binary object file, and use the decompiler to produce c-code.

**Comment by crisdax** [comment]
> If I understand you correctly. You would need to assemble the program.s into an object file program.o using an appropriate assembler like gnu-as. You can then import the binary object file, and use the decompiler to produce c-code.

Which decompile should I use?

**Comment by dp1** [comment]
The built-in decompiler, just open the assembled file in ghidra
