### ISSUE TITLE
How to programmatically determine assignments to (members of) a variable?

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#2236]
I am trying to programmatically determine the arguments passed to a function call. That is: Given a function `CallMe`, I want to list all calls to `CallMe` and determine the values that are passed to it. The situation is a little more complex as this function receives a single argument which is a pointer to a structure which holds the actual arguments:
```c
  Input = (Input*)operator_new(0x10);
  Input->SomeBuffer = CONSTANT_SYMBOL;
  Input->SomeValue = 0x12;
  Input->SomeOtherValue = 0x22431;
  CallMe(Input);
```
I am looking to programmatically determine that `SomeBuffer` was `CONSTANT_SYMBOL` (identified by its memory address), `SomeValue` was `0x12`, and `SomeOtherValue` was `0x22431` when `CallMe` was called.

I know how to obtain the `HighVariable` that represents `Input`, but I have not figured out a way to obtain the values that are being assigned to its members right before the call to `CallMe`. These assignments always happen within the same scope as the call, i.e. it always looks very similar to the mock-up pseudocode I presented above.

I would be very happy if someone could point out a way to determine these.

**Comment by astrelsky** [comment]
Seems like a standard inlined constructor. Unfortunately there really is no simple way to programmatically get these values. The best way I can think of to do it would be to collect references from the listing to the function,  decompile all functions containing the function call, split the output into ClangLines, find the function call and get the HighVariable from the ClangLine and then assuming it has already been marked as the structure filter out the ClangLines which contain the found HighVariable, a ClangFieldToken, and an assignment. You should be able to get the assigned global value from the ClangLine.

I'm certain it isn't intended to be done this way but I don't know of any alternative. There is still a lot you would need to play with and figure out on your own from my suggestion above. If anyone has any other ideas I'd like to know because I can't find any other way of doing something like this.

**Comment by huettenhain** [comment]
Dear @astrelsky, thank you very much, **`ClangLines`** was the hint I needed. I have a working prototype for my particular case and I am now working on making it a little less fragile. If I manage to cook up something reasonably useful I will comment here with a link to the code.

For those in search of answers, here are some keynotes:

- Get a decompiler interface like so:
  ```java
   DecompInterface decompInterface = new DecompInterface();
   decompInterface.openProgram(currentProgram);
   DecompileResults decompiled = decompInterface.decompileFunction(someFunction, 120, monitor);
   ```
- For a function call happening at the address `addr`, you can use the following code to get the high variable that corresponds to the `k`-th argument that is passed to this function call.
   ```java
   Iterator<PcodeOpAST> pCodes = decompiled.getHighFunction().getPcodeOps(addr);
   HighVariable argument = null;
   while (pCodes.hasNext()) {
   	PcodeOpAST instruction = pCodes.next();
   	if (instruction.getOpcode() == PcodeOp.CALL) {
    		argument = instruction.getInput(k).getHigh();
   		break;
   	}
   }
   ```
- Use `DecompilerUtils.toLines(decompiled.getCCodeMarkup())` to get an iterator over `ClangLine` objects representing a line in the decompiled code of `someFunction`.
- Use the `getAllTokens()` method of each `ClangLine` to get a list of `ClangToken` objects (named `token`).
- Use `token.getPcodeOp()`, `token.getVarnode()`, and `token.getHighVariable()` to navigate your way around the tokens, trying to puzzle together whether this line represents a variable assignment or not.
- If `token.getPcodeOp() != null` and `token.getPcodeOp().getOpcode() == PcodeOp.STORE`, then some constant value is being assigned in this line. These are the ones that interest me in my case.
- If `token.getPcodeOp() != null` and `token.getPcodeOp().getOpcode() == PcodeOp.PTRSUB`, this means you are looking at a "subfield" operation (and absolutely *not* a pointer subtraction!). Unfortunately, you could now be looking at a constant memory address or access to a member variable of the struct you are interested in. If `token.getHighVariable()` is the same as the `argument` you determined earlier, then it is the latter.

That's all I got, and it was good enough for my case. Hence I'll close this out.

**Comment by astrelsky** [comment]
Glad you managed to figure it out. I still think it shouldn't be necessary to have to parse the clang nodes but it will hopefully get better in the future. Just keep in mind that the DecompInterface has an underlying decompiler process and needs to be disposed of. `DecompInterface.dispose()`

**Comment by huettenhain** [comment]
Thank you again for the reminder, I would not have noticed that I am responsible to call `dispose()` there.
