### ISSUE TITLE
How do I merge two subroutines?

### ISSUE THREAD

**Issue by AnonN10** [NationalSecurityAgency/ghidra#2237]
I can't figure out how to delete or merge subroutines, how do I do that?

**Comment by quosego** [comment]
I noticed a similar question on reddit are you the same person?
https://www.reddit.com/r/ghidra/comments/bz0hp1/how_do_i_merge_function_labelsnamespaces/

I'll try to address this as simple as possible. Hopefully this stops people from trashing their ghidra projects after they make such a silly mistake.

### Step 1
Say we created a funciton but no longer want it so we delete it.
![NXL6PuElKP](https://user-images.githubusercontent.com/71137080/92998001-40cbaf00-f4e5-11ea-94bd-7748a6168ef5.png)

### Step 2
Now we have an annoying subroutine that we no longer want.
![javaw_sZEoGVBTN6](https://user-images.githubusercontent.com/71137080/92998639-edf3f680-f4e8-11ea-82db-91b7b81e72be.png)

### Steps 3 - 6
The gif clip got snipped but keep with me I have some reference steps below. 
![wyXovCJS5U](https://user-images.githubusercontent.com/71137080/92998703-61960380-f4e9-11ea-9c75-d0a3fc794053.gif)

### Step 3
We first go to a reference address calling the targeted subroutine.
![nLs4nPMZSl](https://user-images.githubusercontent.com/71137080/92998945-17ae1d00-f4eb-11ea-8220-e56d25d26cb9.png)

### Step 4
Then right click the address and select "References" -> "Delete Memory References."
![MlXS6OvgTA](https://user-images.githubusercontent.com/71137080/92998754-de28e200-f4e9-11ea-89dc-4944e0c1b043.png)

### Step 5
Now we need to "clear" out the "settings" for the disassembly at this address. 
![javaw_V5cQZK52Mv](https://user-images.githubusercontent.com/71137080/92998809-1f20f680-f4ea-11ea-92bb-246ac8e129a9.png)

### Step 6
Then re-disassemble the bytes. Which will restore it as usually just an address with a label.
![javaw_Sxxpxu0xwM](https://user-images.githubusercontent.com/71137080/92998825-45df2d00-f4ea-11ea-939d-f7ca17bdd155.png)

### The Result
![javaw_F0Kbu6oZYM](https://user-images.githubusercontent.com/71137080/92999005-94d99200-f4eb-11ea-9865-76ffe4ce8a46.png)


Hopefully this will help you and some others out. If you need anything else just ask.

Best of luck with your reversing.
