### ISSUE TITLE
Batch import screen - ctrl or shift selecting multiple "Import Sources" in List Box, then hitting remove, only removes 1 item

### ISSUE THREAD

**Issue by RedDragonWebDesign** [NationalSecurityAgency/ghidra#2238]
**Describe the bug**

Batch import screen - ctrl or shift selecting multiple "Import Sources" in the List Box, then hitting remove, only removes 1 item

**To Reproduce**
1. Go to Batch Import
2. Add multiple files
3. Select a couple to remove, at one time, by holding down ctrl or shift and clicking on file names
4. Click "Remove"

**Expected behavior**
All selected items should be deleted. But only 1 is deleted.

**Screenshots**
![2020-08-31_015956](https://user-images.githubusercontent.com/43397938/91702609-d2bed980-eb2d-11ea-9460-8043581280f8.png)

**Environment (please complete the following information):**
 - OS: Windows 7 Professional x64
 - Java Version: 1.8.0_261
 - Ghidra Version: 9.1.2

**Comment by dev747368** [comment]
Fixed
