### ISSUE TITLE
Misdecompilation while using a negative offset on a given address (x86)

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#224]
**Env**: Ghidra 9.0, Linux, x86

**Disas**:

```
49 89 44        MOV        qword ptr [R12 + -0x8],vector48
24 f8
49 c7 04        MOV        qword ptr [R12],0x0
24 00 00 
00 00
49 c7 44        MOV        qword ptr [R12 + 0x8],0x0
24 08 00 
00 00 00
49 c7 44        MOV        qword ptr [R12 + 0x10],0x0
24 10 00 
00 00 00
```

**Decomp**:

```
    vector48_data->p1 = vector48;
    vector48_data->p0 = NULL;
    vector48_data->p1 = NULL;
    vector48_data->p2 = NULL;
```

`R12` corresponds to `vector48_data`. If it's not obvious, the first decompilation line is wrong (it's interpreting the `-8` as `+8`).

For the context, `vector48_data` is a pointer to a struct with 3 pointers (`void *p0`, `void *p1`, `void *p2`). As far as I can remember, that issue was already present before assigning a struct type to `vector48_data`.

**Note**: the decompiler might be confused because `vector48_data` is an aligned pointer derived from a classic heap allocated buffer (that first pointer assignment is actually a way of storing the original allocated data pointer).

**Comment by emteere** [comment]
The decompiler isn't completely off base, since the vector48_data pointer is a pointer to a structure of a certain size.  The pointer can also act as a pointer to an array of the structures.

Agree it isn't correct, and the better option would be to display the negative access in another way.  If the structure size is changed to just 2 fields you get:
```
  param_1[-1].field_0x8 = in_RAX;
  param_1->field_0x0 = 0;
  param_1->field_0x8 = 0;
  param_1[1].field_0x0 = 0;
```
Which seems much closer to correct for the accesses to the structure.  The single negative index didn't try and turn it into an array, however the positive index past the end of the structure changed the access into an array access.

There has been discussions of allowing negative offsets for structure fields for this type of situation.

**Comment by ubitux** [comment]
Just to help with this issue (because I believe it's an important one), here is a reproducible case:

```
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>

struct x {
    const int *a;
    const int *b;
    const int *c;
};


/*
 *       .---> +--------+ <-- heap alloc
 *       |     :        :
 *       |     :        :
 *       |     +--------+
 *       `---- |  orig  |
 *             +--------+
 *             |   a    |
 *             +--------+
 *             |   b    |
 *             +--------+
 *             |   c    |
 *             +--------+
 *             :        :
 *             :        :
 *             +--------+
 */

static const int x_a[] = {1, 2, 3};
static const int x_b[] = {4, 5, 6};
static const int x_c[] = {7, 8, 9};

static struct x *aligned_x_alloc(void)
{
    const size_t header_size = sizeof(uintptr_t) /* orig */
                             + 16;               /* align padding */
    const size_t buf_size = header_size + sizeof(struct x);

    void *buf = malloc(buf_size);
    if (!buf)
        return NULL;

    struct x *x = (struct x *)((uintptr_t)(buf + header_size) & ~0xf);
    x->a = x_a;
    x->b = x_b;
    x->c = x_c;

    void **orig = (void **)(((uint8_t *)x) - sizeof(uintptr_t));
    *orig = buf;

    return x;
}

void aligned_x_free(struct x *x)
{
    void **orig = (void **)(((uint8_t *)x) - sizeof(uintptr_t));
    printf("free-ing struct x %p {%p,%p,%p} @ heap-alloc %p\n",
           x, x->a, x->b, x->c, orig);
    free(*orig);
}

int main(void)
{
    struct x *x = aligned_x_alloc();
    if (!x)
        return -1;

    aligned_x_free(x);
    return 0;
}
```

Built with `gcc -O2` (GCC 8.3.0 on Linux / x86_64), here is the best I could obtain with Ghidra 9.0.2:

```
int main(void)

{
    int ret;
    void *buf;
    x *x;
    
    buf = malloc(0x30);
    ret = -1;
    if (buf != NULL) {
        x = (x *)((long)buf + 0x18U & 0xfffffffffffffff0);
        x->a = (int *)0x102060;
        x->b = x_b;
        x->c = x_c;
        x->b = buf;
        aligned_x_free(x);
        ret = 0;
    }
    return ret;
}
```

Again of the context, the problematic line is `x->b = buf`.

I'm not sure this is related but you may also notice that for some reason Ghidra is confused about `x->a` type:

![2019-04-22-194525_1001x372_scrot](https://user-images.githubusercontent.com/34467/56515195-a5285000-6537-11e9-85a9-2dc518ecd532.png)

**Comment by caheckman** [comment]
I was able to duplicate the problem from your source sample. Thanks for the concise bug report. I have a fix in a branch that should get merged shortly. The bug was basically an unsigned remainder that should have been signed.  Your example now looks like

> x * aligned_x_alloc(void)
> 
> {
>   int *buf;
>   x *x;
>   
>   buf = (int *)malloc(0x30);
>   if (buf == (int *)0x0) {
>     x = (x *)0x0;
>   }
>   else {
>     x = (x *)((ulong)(buf + 6) & 0xfffffffffffffff0);
>     x->a = (int *)0x400708;
>     x->b = x_b;
>     x->c = x_c;
>     x[-1].c = buf;
>   }
>   return x;
> }
>

**Comment by ubitux** [comment]
Ah nice, that's much better, thank you. Should I open another issue about `x->a = (int *)0x400708;`?
