### ISSUE TITLE
NullPtrException on applying data types

### ISSUE THREAD

**Issue by archie426** [NationalSecurityAgency/ghidra#2240]
**Describe the bug**
Importing ntddk_64 and on applying the symbols it fails with the following error:
java.lang.NullPointerException
	at ghidra.framework.plugintool.mgr.ToolTaskManager.taskFailed(ToolTaskManager.java:451)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:87)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**
1. Import a data type kit
2. Click on apply symbols

**Environment (please complete the following information):**
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Java\jdk-11.0.7
JVM Version: Oracle Corporation 11.0.7
OS: Windows 10 10.0 amd64

if I can provide any more info can provide, this is my first time using Ghidra so I am sorry if this is braindead lol

**Comment by ghidra1** [comment]
Could you please be more specific.  Not exactly sure what you mean by "import a data type kit" and "apply symbols".  Please use exact naming from Ghidra menus and messages.

**Comment by archie426** [comment]
Sorry, realised I had made a really stupid mistake 🤦 I should've closed this earlier. Sorry for wasting your time
