### ISSUE TITLE
Detecting inlined functions

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#225]
Compilers tend to inline relatively large chunks of code, bloating quite a bit the decompiled form. If a given code chunk is defined as a function, is it possible to detect (even if manually) where it could have been used elsewhere and replace it with a virtual call in the decompiled form?

**Comment by lab313ru** [comment]
Updating issue: it is possible to set "inline" flag for functions, but I don't sure, if it will search for such functions as inlined ones.

**Comment by nihilus** [comment]
Actually it is not easy to detect if a function is inlined or not since the compiler will substitute the arguments.

One would certainly need to have some sort of function signatures for making this feasible in the short-term.

**Comment by lab313ru** [comment]
If some function have been already defined as inlined, user or Ghidra may look for signatures of such functions.

**Comment by ubitux** [comment]
The apparent "inlining" is also often due to C macro or C++ templating, where factoring in a function isn't actually possible. I'm not sure how this could fit in the engine and UI of Ghidra, but some kind preprocessor layer in the decompiler (and listing?) could be a direction to look into.

Alternatively, and maybe as a much simpler workaround, visual folding of a given scope could also help filtering-out these blobs and focus on the non-redundant parts.

**Comment by ubitux** [comment]
May I ask why this issue was closed? Should I open a feature request instead?

**Comment by ryanmkurtz** [comment]
Apologies, i read through it and assumed the conversation answered your question.  If you think you have a specific enhancement to request, I think it would be best to create a new issue describing what specific feature you would like.
