### ISSUE TITLE
Setting AnalyzerType to ONE_SHOT_ANALYZER throws an error while opening file

### ISSUE THREAD

**Issue by TheAifam5** [NationalSecurityAgency/ghidra#2250]
**Describe the bug**
Java plugin with analyzer type set to `ONE_SHOT_ANALYZER` throws an error
`ERROR Unknown Analysis Type: Unexpected Analysis type One Shot Analzyer  (AutoAnalysisManager.java:187)`

**To Reproduce**
1. Create empty analyzer plugin
2. Set analyzer type to `ONE_SHOT_ANALYZER`

**Expected behavior**
Should not throw an error while this type of analyzer will be executed only manually and once.

**Screenshots**
![image](https://user-images.githubusercontent.com/2192274/92309289-9ca5ad80-efa4-11ea-8657-7704cdc4b967.png)

**Environment:**
 - OS: ArchLinux
 - Java Version: openjdk 11.0.8 j9
 - Ghidra Version: 7e5f015d651b9c5e7825cb10bc50338b5af67538

**Comment by ghidra1** [comment]
`AnalyzerType.ONE_SHOT_ANALYZER`  is not supported and should not be used.  It appears to have been added in attempt to facilitate an "analysis recipe" concept which was never fully implemented.  There are no existing analyzers which make use of this type and it should probably be removed.

All analyzers are currently event-driven with the option of also allow one-shot use which is facilitated by the `Analyzer.supportsOneTimeAnalysis()`.  If this method returns true, the analyzer will be included in the Analysis->One Shot menu.  At this point an analyzer which does not respond to events is handled using a Ghidra Script.  A Ghidra Script can declare a menu path and be added to your Code Browser tool or can simply be run from the Script Manager window.

**Comment by ghidra1** [comment]
The unsupported `AnalyzerType.ONE_SHOT_ANALYZER` has been removed for Ghidra 9.2
