### ISSUE TITLE
Multiple bugs in handling of iOS "crushed PNGs"

### ISSUE THREAD

**Issue by kaibolay** [NationalSecurityAgency/ghidra#2252]
### Faulty handling of ADAM7 interlacing

Small mistakes were made when translating the [C source](https://github.com/soffes/pngdefry) to Java:

- incorrect calculation of row filter bytes
- incorrect processing of IDAT chunk

Reproduce by processing any "crushed" file which uses ADAM7 interlacing.

Fixed with #1854  

### Problems rewriting IDAT chunk

- should check if rewriting is needed
- produces multiple copies of same "uncrushed" chunk if input has multiple chunks

Reproduce by processing files where the IDAT chunk doesn't need to be rewritten and processing any file with multiple IDAT chunks.

Fixed with #1874 

### Problems with compression

- doesn't check too much compressed input
- incorrectly truncates compressed output at  64 kB (INITIAL_REPACK_SIZE)

Reproduce by processing any file where the compressed data in IDAT is larger than the image size and any image where the compressed output would exceed 64 kB.

Fixed with #1875

**Comment by dev747368** [comment]
This should be merged in now.  Please verify and reopen if you see any issues.
