### ISSUE TITLE
RecognizerService and Recognizer

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2255]
Just curious if this is something that is no longer used and/or no longer needed. The only result I got for RecognizerService when searching through all the java files was RecognizerService itself. SevenZipFileSystemFactory also appears to be the only use of the Recognizer interface.

**Comment by dev747368** [comment]
Yep, a mostly unused corner of ghidra.  Probably should be refactored out of existence.
