### ISSUE TITLE
Ghidra Server Not Working in version 9.1.2

### ISSUE THREAD

**Issue by rsmets** [NationalSecurityAgency/ghidra#2256]
**Describe the bug**
Seems as though Ghidra server connection from clients is not working in Version 9.1.2.

**To Reproduce**
1. Start the Ghidra server on a cloud instance
2. Open ports 13100-13002
3. Try to connect to from your host machine's Ghidra client on the default port (13100)

**Expected behavior**
The login prompt is presented. However, it is not. 

**Environment (please complete the following information):**
 - OS: Ubuntu 18.0.4
 - Java Version: open jdk 11
 - Ghidra Version: 9.1.2

**Additional context**
Upon bumping down to Ghidra server version 9.0 and attempting also a failing. Seems as though the Ghidra client version must match the server version? Unclear. I did not also decrement my client version when after degrading my server version.

**Comment by dev747368** [comment]
Could you provide more details about how its "not working"?

I would suggest setting up a server on your local machine, verifying that you can configure it and connect to it, and then trying your real setup. 

If you are still having problems, please attach log files from the server that show the failed connection attempts, etc.

**Comment by dev747368** [comment]
Waiting for response.  Feel free to re-open this issue.
