### ISSUE TITLE
how to find usage of structure types using headless script

### ISSUE THREAD

**Issue by Ruturaj4** [NationalSecurityAgency/ghidra#2259]
I am writing a script using headlessanalyser in python. I want to get address references of variables.

For e.g.
I can do `refmanager.getReferencesTo(var)` to get listing addresses references for variable var. But the problem with that approach is the structure type.

For e.g. consider follwing simple code.

```
#include <stdio.h>

struct B
{
  int arr[10];
};

int main()
{
  struct B b;
  b.arr[9] = 1;
  for (int i=0; i<10; ++i)
    printf("%i\n", b.arr[i]);
  return 0;
}
```

```
int main()
{
  401126:       55                      push   rbp
  401127:       48 89 e5                mov    rbp,rsp
  40112a:       48 83 ec 30             sub    rsp,0x30
  struct B b;
  b.arr[9] = 1;
  40112e:       c7 45 f4 01 00 00 00    mov    DWORD PTR [rbp-0xc],0x1
  for (int i=0; i<10; ++i)
  401135:       c7 45 fc 00 00 00 00    mov    DWORD PTR [rbp-0x4],0x0
  40113c:       eb 1e                   jmp    40115c <main+0x36>
    printf("%i\n", b.arr[i]);
  40113e:       8b 45 fc                mov    eax,DWORD PTR [rbp-0x4]
  401141:       48 98                   cdqe
  401143:       8b 44 85 d0             mov    eax,DWORD PTR [rbp+rax*4-0x30]
  401147:       89 c6                   mov    esi,eax
  401149:       bf 10 20 40 00          mov    edi,0x402010
  40114e:       b8 00 00 00 00          mov    eax,0x0
  401153:       e8 d8 fe ff ff          call   401030 <printf@plt>
  for (int i=0; i<10; ++i)
  401158:       83 45 fc 01             add    DWORD PTR [rbp-0x4],0x1
  40115c:       83 7d fc 09             cmp    DWORD PTR [rbp-0x4],0x9
  401160:       7e dc                   jle    40113e <main+0x18>
  return 0;
  401162:       b8 00 00 00 00          mov    eax,0x0
}
```

Notice that the instruction at `401143` belongs to `b.arr`.

But refmanager.getReferencesTo(var) only says that instruction `40112e` belongs to b.arr. Is there any way to get all the references? Note that ghidra gui also gives me only one reference to `b`. But if I right click of type `B` and click on `usage  of B` then it gives me correct instruction references (belong to type `B`). Is there any way to do this in CLI using python api?

**Comment by saruman9** [comment]
I think [this example](https://github.com/saruman9/ghidra_scripts/blob/288a2226893fd6801f1234971eef99b69590547e/FindRefsField.java) might help you. But you should use `findDataTypeReferences` without `fieldName` parameter:
```java
ReferenceUtils.findDataTypeReferences(accumulator,
                                      baseDataType,
                                      null,
                                      currentProgram,
                                      monitor);
```

**Comment by Ruturaj4** [comment]
@saruman9 thanks so much for your answer. I tried:

`ref = ReferenceUtils.findDataTypeReferences(accumulator, component.getDataType(), None, currentProgram, monitor)`

But it gives me following WARNING:

`WARN  Decompiling 00405000, pcode error at 00405000: Unable to disassemble EXTERNAL block location: 00405000 (DecompileCallback)`

And gives me `ref=None`

**Comment by dragonmacher** [comment]
You are now embarking on a slightly more advanced journey.  It's dangerous to go alone! Take this :hammer_and_wrench: :

```
	List<DataTypeReferenceFinder> finders =
		ClassSearcher.getInstances(DataTypeReferenceFinder.class);
	if (finders.isEmpty()) {
		println(
			"Could not find a " + DataTypeReferenceFinder.class + " service implementation");
		return;
	}

	DataTypeReferenceFinder finder = finders.get(0);
	Consumer<DataTypeReference> callback = ref -> println("ref: " + ref);
	DataType dt = var.getDataType();
	finder.findReferences(currentProgram, dt, callback, monitor);
```

This is a Java snippet.  Adapt to Python as needed.


This code snippet will give you you all the info that the search has found.   But, if you were looking for a `Reference` object, that is not in there.  Not all of the search results are based on Ghidra references, as the Decompiler may figure that out on its own.     These search results will give you: an address, the data type being accessed, (optionally,  the field name being accessed) and the function that contains the data access.
