### ISSUE TITLE
Strings displays as the label in decomp view

### ISSUE THREAD

**Issue by james-tate** [NationalSecurityAgency/ghidra#2262]
I am sure I am missing something silly, but I cannot seem to find a setting that converts a string displayed in the decompiler view from the label to the string representation. Sometimes it displays correctly. 

Is there a setting I am missing somewhere?

![Capture](https://user-images.githubusercontent.com/10095640/92658963-1697a880-f2bd-11ea-81ae-ae2d32de303b.PNG)
![Capture1](https://user-images.githubusercontent.com/10095640/92659150-6eceaa80-f2bd-11ea-858f-045beb899da7.PNG)

**Comment by astrelsky** [comment]
Go to the string, right click->data->settings->mutability then choose constant. I usually just set the default to be constant for strings.

**Comment by james-tate** [comment]
Works like a charm. Thanks!

**Comment by saruman9** [comment]
> Go to the string, right click->data->settings->mutability then choose constant. I usually just set the default to be constant for strings.

Or make the memory block, which contains the string, not-writeable.

**Comment by astrelsky** [comment]
> > Go to the string, right click->data->settings->mutability then choose constant. I usually just set the default to be constant for strings.
> 
> Or make the memory block, which contains the string, not-writeable.

This doesn't always work. I have a script to iterate over all defined data in read only blocks and mark them as constant because of it. There should be an open issue about it somewhere.
