### ISSUE TITLE
ClassCastException GnuDemanglerParser.OverloadOperatorHandler

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2267]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. demangle "_ZTINSt6__ndk110__function6__funcIZZN5dummy2it5other9Namespace8functionEfENK3$_2clEPNS4_9NamespaceEEUlS8_E_NS_9allocatorIS9_EEFiS8_EEE"

**Attachments**

<details><summary>stacktrace</summary>

```
Traceback (most recent call last):
  File "python", line 1, in <module>
  File "C:\Users\astre\.ghidra\.ghidra_9.2_DEV\dev\jython_cachedir\python-src\sitecustomize.py", line 37, in demangle
    return DemanglerUtil.demangle(__main__.currentProgram, mangled)
	at ghidra.app.util.demangler.gnu.GnuDemanglerParser$OverloadOperatorHandler.build(GnuDemanglerParser.java:1281)

	at ghidra.app.util.demangler.gnu.GnuDemanglerParser.parse(GnuDemanglerParser.java:323)

	at ghidra.app.util.demangler.gnu.GnuDemangler.parse(GnuDemangler.java:218)

	at ghidra.app.util.demangler.gnu.GnuDemangler.demangle(GnuDemangler.java:110)

	at ghidra.app.util.demangler.Demangler.demangle(Demangler.java:53)

	at ghidra.app.util.demangler.DemanglerUtil.demangle(DemanglerUtil.java:83)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:564)

java.lang.ClassCastException: java.lang.ClassCastException: class ghidra.app.util.demangler.DemangledVariable cannot be cast to class ghidra.app.util.demangler.DemangledFunction (ghidra.app.util.demangler.DemangledVariable and ghidra.app.util.demangler.DemangledFunction are in unnamed module of loader 'app')

```
</details>

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.450]
 - Java Version: 14.0.2
 - Ghidra Version: 9.2_DEV f97e60483bd359fa996daeaea3313cde268fd65d

**Additional Context**
The binary I'm working with does have symbols present and there were none at the address. This is a mangled symbol I've created myself during analysis. It should still be valid and I have yet to investigate why there is not one present in the elf symbol table.

**Comment by dragonmacher** [comment]
I am taking a look at this.   I cannot wrap my head around the demangled output of the give mangled symbol.  It does not match any construct that I have seen.  It also has some unbalanced syntax elements, like a trailing '>' char.   This is what I am seeing:

```
function(float)::$_2::operator()(dummy::it::other::Namespace*) const::{lambda(dummy::it::other::Namespace*)#1}, std::__ndk1::allocator<{lambda(dummy::it::other::Namespace*)#1}> int (dummy::it::other::Namespace*)>
```

Is there a chance that the mangled symbol is invalid?  If not, is there a copy/paste error?

**Comment by astrelsky** [comment]
> I am taking a look at this. I cannot wrap my head around the demangled output of the give mangled symbol. It does not match any construct that I have seen. It also has some unbalanced syntax elements, like a trailing '>' char. This is what I am seeing:
> 
> ```
> function(float)::$_2::operator()(dummy::it::other::Namespace*) const::{lambda(dummy::it::other::Namespace*)#1}, std::__ndk1::allocator<{lambda(dummy::it::other::Namespace*)#1}> int (dummy::it::other::Namespace*)>
> ```
> 
> Is there a chance that the mangled symbol is invalid? If not, is there a copy/paste error?

The demangled output should be: `typeinfo for std::__ndk1::__function::__func<dummy::it::other::Namespace::function(float)::$_2::operator()(dummy::it::other::Namespace*) const::{lambda(dummy::it::other::Namespace*)#1}, std::__ndk1::allocator<{lambda(dummy::it::other::Namespace*)#1}>, int (dummy::it::other::Namespace*)>`
At least that is the raw output produced by demangler_gnu_v2_33_1.exe

**Comment by dragonmacher** [comment]
OK.  I see it was my copy/paste mistake.   (Oddly, the command line is not demangling for me, but Java is.)

**Comment by astrelsky** [comment]
> OK. I see it was my copy/paste mistake. (Oddly, the command line is not demangling for me, but Java is.)

I noticed that using c++filt in linux didn't work but ghira's demangler_gnu_v2_33_1.exe does. I think it may have to do with the presence of `$` as c++filt returns what I entered up until `$`. iirc the special character `$` used in lambdas is platform specific among gcc and clang.

**Comment by dragonmacher** [comment]
> I noticed that using c++filt in linux didn't work but ghira's demangler_gnu_v2_33_1.exe does. I think it may have to do with the presence of `$` as c++filt returns what I entered up until `$`. iirc the special character `$` used in lambdas is platform specific among gcc and clang.

Cofirming this idea, if I escape the '$' in my shell with a '\', then it works as expected.
