### ISSUE TITLE
Creating ExtensionPoints for a plugin

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2272]
I'm looking to create an ExtensionPoint in a plugin but am having difficulty getting the ClassSearcher to find it when running in the debugger. It seems that my workspace directory is not being considered a Module as invoking `Application.getMyModuleRootDirectory()` from one of my classes returns null. I have `-Declipse.project.dir=${workspaceFolder}` set in the vmArgs when launching vscode's Java debugger which is the magic behind getting the GhidraClassLoader to load my plugin's classes but I don't see an option for a Module. I do have the necessary `data/ExtensionPoint.manifest` file and the corresponding ExtensionPoint suffix.

**Comment by ryanmkurtz** [comment]
`eclipse.project.dir` isn't used anymore.  It's done like this now (line 170 is the part relevant to you).

https://github.com/NationalSecurityAgency/ghidra/blob/0ffdb9c49423708331222d79e1333e74f953c9fa/Ghidra/Framework/Utility/src/main/java/ghidra/GhidraApplicationLayout.java#L138-L199

**Comment by astrelsky** [comment]
I see. So the reason it isn't detecting it is because the eclipse jdt.ls has `${workspaceFolder}/bin/main` and `${workspaceFolder}/bin/test` in the classpath and no `${workspaceFolder}/bin` entry. Since only one parent is checked it isn't detected as a module. I got around this by explicitly adding `${workspaceFolder}/bin` to the classpath in my gradle script. Thank you!

**Comment by ryanmkurtz** [comment]
Seems like the logic there should be robustified.

**Comment by astrelsky** [comment]
> Seems like the logic there should be robustified.

Probably. I think it would be ok to check if the path contains 'bin/' and use it's parent as long as there is a `.class` file found within a subdirectory. That would be a bit more robust while not being too lenient. My concern with checking for the presence of `bin/` is if there's some really wacky setup with `/dir1/bin/plugin/bin` it'd be necessary to ensure the correct one is taken.
