### ISSUE TITLE
ghidra scripting: ghidra unable to resolve string type

### ISSUE THREAD

**Issue by Ruturaj4** [NationalSecurityAgency/ghidra#2274]
I have following code:

```
#include <stdio.h>

char somes[10] = "good job!";
char somes1[8] = "another";
char somes2 [5] = "job";

int func()
{
  printf("You did a %s\n", somes);
  // func(10);
}

int main()
{
  printf("You did a %s\n", somes1);
  printf("You did a %s\n", somes2);
  printf("garb");
  printf("sharp");
  func();
}
```

I want to get sizes of strings defined in the code. Ghidra behaves strangely in such cases, even with symbol information. For e.g. in the above program, ghidra accurately detects lengths (or sizes of) all strings except. "garb" - it says that its size is 1 and defined as a single character "g" (`s.getObject()`). I feel this very strange, as even with debugging information, ghidra fails to detect this. Is there anything I can do to get such sizes (or correct string representations)?

I am doing something like:

```
symbols = set(currentProgram.getSymbolTable().getAllSymbols(True))
for s in symbols:
    if s.isGlobal():
        // gives me size of object
        print(s.getObject().getLength())
```

![image](https://user-images.githubusercontent.com/17796905/93051793-a5dced00-f62a-11ea-8971-9c4fd8e800b5.png)

**Comment by astrelsky** [comment]
There is a minimum string size setting in the ASCII Strings analyzer. It's default value is 5. It is set this way to prevent types whose value may appear to be a string from being incorrectly typed. It is not uncommon on some architectures for pointers to look like common 3 letter words.

**Comment by Ruturaj4** [comment]
thanks for  your answer, I actually figured that out from the documentation. Is there any way to change this size, or change this size limit or change the data type of symbol directly. Using headless analyzer script? I can see such options in GUI mode, but I didn't find any way to do that in scripting mode.

**Comment by astrelsky** [comment]
From a GhidraScript you may use `setAnalysisOption(currentProgram, "ASCII Strings.Minimum String Length", "LEN_{length}")` where length is any number between 4 and 25. It is an enum so it gets set by parsing the enum name.

**Comment by dragonmacher** [comment]
@astrelsky :clap:  Thanks for the help

This is an example of users accessing the inner-workings of our APIs that we did not originally design for scripting.   Feedback on these APIs is welcome.  I can see a future where controlling analysis is much easier.

**Comment by astrelsky** [comment]
> @astrelsky 👏 Thanks for the help
> 
> This is an example of users accessing the inner-workings of our APIs that we did not originally design for scripting. Feedback on these APIs is welcome. I can see a future where controlling analysis is much easier.

I'm not entirely sure that this wasn't intended for scripting because there is an example provided for this [GetAndSetAnalysisOptionsScript.java](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/ghidra_scripts/GetAndSetAnalysisOptionsScript.java). However, as can be seen from this script, the static fields for the analyzer and option names should become public to prevent scripts from breaking when the fields are changed. The example script doesn't work as intended because the names are case sensitive.

**Comment by Ruturaj4** [comment]
Thanks so much @astrelsky ! closing

**Comment by elig0n** [comment]
> There is a minimum string size setting in the ASCII Strings analyzer. It's default value is 5. It is set this way to prevent types whose value may appear to be a string from being incorrectly typed. It is not uncommon on some architectures for pointers to look like common 3 letter words.
> "ASCII Strings.Minimum String Length", "LEN_{length}") where length is any number between 4 and 25. 

@astrelsky 
Is there no way to change the minimal length to less than 4 characters long? 
Why force it upon the user and not just do with having it as a default option ? YMMV.

**Comment by astrelsky** [comment]
> > There is a minimum string size setting in the ASCII Strings analyzer. It's default value is 5. It is set this way to prevent types whose value may appear to be a string from being incorrectly typed. It is not uncommon on some architectures for pointers to look like common 3 letter words.
> 
> > "ASCII Strings.Minimum String Length", "LEN_{length}") where length is any number between 4 and 25.
> 
> @astrelsky
> Is there no way to change the minimal length to less than 4 characters long?
> Why force it upon the user and not just do with having it as a default option ? YMMV.

Unfortunately the StringsAnalyzer is using an enum for some unknown reason. Because of this it is not possible to change the length outside of the range 4-25;
