### ISSUE TITLE
"-max-cpu" option does not work.

### ISSUE THREAD

**Issue by greagen** [NationalSecurityAgency/ghidra#2280]
I am using Headless command to run ghidra and set -max-cpu to 1 or 2, but it seems the option does not work. And during Ghidra running, all 8 cpus(4 cores @ 8 threads) are used, occupancy 50% - 100%, why "-max-cpu" does not work? Is there any effective method to limit Cpu number that Ghidra uses?

OS: Ubuntu 16.04
Ghidra 9.1.2
Java 11

**Comment by dev747368** [comment]
The option limits the number of worker threads that Ghidra allocates.  There will be several other misc threads that don't generally do a lot of work.  Equating the number of threads with the load you are seeing isn't a good metric.

You can use java's jstack to dump the list of threads in the running headless process and get a better idea of the threads that are allocated.
