### ISSUE TITLE
FunctionManager.getFunctionContaining returns null for valid address

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2281]
**Describe the bug**
FunctionManager.getFunctionContaining returns null when provided an address which is contained by a function. This only occurs when the address is not the start of an instruction.

**To Reproduce**
1. get the entry point of a function
2. add 1 to the entry point
3. invoke FunctionManager.getFunctionContaining(entryPoint+1)
4. see null result

**Expected behavior**
The result should be the function containing the address.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.508]
 - Java Version: 14.0.2
 - Ghidra Version: 9.2_DEV 0ffdb9c49423708331222d79e1333e74f953c9fa

**Additional context**
For now I can utilize Listing.getInstructionContaining and then use the address of the instruction. The reason I have an offset function address to begin with is likely due to some shady LTO.

**Comment by dragonmacher** [comment]
This works as expected for me on a simple ELF binary.   Is this failing for multiple functions in your example binary?

**Comment by astrelsky** [comment]
> This works as expected for me on a simple ELF binary. Is this failing for multiple functions in your example binary?

Oh. Seems there is something strange with that function. I'll investigate further but will close this for now.

**Comment by astrelsky** [comment]
@dragonmacher I've never seen this before. 
![Capture](https://user-images.githubusercontent.com/46897303/93258684-b2695e80-f76c-11ea-9688-576a4b8b8d05.PNG)

Deleting and recreating the function did appear to fix it. Tracking down what caused that in the first case is unlikely though.

**Comment by dragonmacher** [comment]
There appears to be an offcut reference to the second byte in the function.  Maybe having the reference confused Ghidra?

**Comment by astrelsky** [comment]
> There appears to be an offcut reference to the second byte in the function. Maybe having the reference confused Ghidra?

It's possible. I'm seeing this a lot on native arm android libraries. Might be related to some sort of LTO although I'm not exactly sure what is going on.

I'm wondering if attempting to create the function at the offset address is what caused it.
