### ISSUE TITLE
Safeguarding against proliferation of unwanted java preview feature

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2284]
**Describe the bug**
jdk 14 introduced a 'preview feature' java.lang.Record : https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/Record.html 

that make ``db.Record`` & ``java.lang.Record`` ambiguous for oracle's jdk 14 javac compiler 

compiling the master branch gives: few hundred of these :

```
> Task :Project:compileJava
/home/user/TOOLS/ghidra/Ghidra/Framework/Project/src/main/java/ghidra/framework/data/OptionsDB.java:224: error: reference to Record is ambiguous
        private Record getPropertyRecord(String propertyName) {
                ^
  both class db.Record in db and class java.lang.Record in java.lang match
```
although the [documentation](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md#catalog-of-dependencies)  recommends jdk11 for building. might i suggest locking the source version  & may be also  target version with gradle : 

```
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11
```
or

```
compileJava {    options.compilerArgs += ["-source 11 -target 11"]}
```

**Comment by ryanmkurtz** [comment]
Ghidra already does this:

https://github.com/NationalSecurityAgency/ghidra/blob/0d8bdd3182a90dc388088a3dece381f3428c28db/gradle/javaProject.gradle#L35-L38

https://github.com/NationalSecurityAgency/ghidra/blob/0d8bdd3182a90dc388088a3dece381f3428c28db/Ghidra/application.properties#L1-L8

**Comment by pabx06** [comment]
good find.
I switched from oracle's jdk14 to oracle jdk 11. And i still having the same ```error : reference to Record is ambiguous.```

 i was able to build commit 7e5f015d651b9c5e7825cb10bc50338b5af67538 with jdk 14 no problem's whatsoever...

**Comment by ryanmkurtz** [comment]
When you launch Ghidra, what version of Java is it showing?

<img width="191" alt="Capture" src="https://user-images.githubusercontent.com/5378554/93496416-2cb8f080-f8dd-11ea-851f-a59b22d5644f.PNG">

**Comment by pabx06** [comment]
after the switch to jdk 11:

# jdk 11

ghidra version commit : 7e5f015d651b9c5e7825cb10bc50338b5af67538

```
$sudo update-java-alternatives -s java-11-oracle

$ java -version
java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

$~/ghidra_9.2_DEV/ghidraRun

```
`ps auwxf|grep ghidra.GhidraRun`
```
user    14337  0.0  0.0  17744  1140 pts/6    S+   18:04   0:00              \_ grep --color=auto ghidra.GhidraRun
user    13016  0.0  0.0  18364  2284 ?        S    18:01   0:00 bash /home/user/ghidra_9.2_DEV/support/launch.sh bg Ghidra   ghidra.GhidraRun
user    13018 41.1  4.2 8029856 688516 ?      Sl   18:01   1:16  \_ /usr/lib/jvm/java-11-oracle/bin/java -Djava.system.class.loader=ghidra.GhidraClassLoader -Dfile.encoding=UTF8 -Duser.country=US -Duser.language=en -Duser.variant= -Dsun.java2d.opengl=false -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Dghidra.cacerts= -Dcpu.core.limit= -Dcpu.core.override= -Dfont.size.override= -Dpython.console.encoding=UTF-8 -Dghidra.util.swing.timeout.seconds=7600 -Dswing.systemlaf=com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatDraculaContrastIJTheme -Dsun.java2d.pmoffscreen=false -Dsun.java2d.xrender=true -Dsun.java2d.uiScale=1 -Dawt.useSystemAAFontSettings=on -showversion -cp /home/user/ghidra_9.2_DEV/support/../Ghidra/Framework/Utility/lib/Utility.jar:/home/user/ghidra_9.2_DEV/support/flatlaf-0.40.jar:/home/user/ghidra_9.2_DEV/support/flatlaf-intellij-themes-0.40.jar ghidra.GhidraLauncher ghidra.GhidraRun
```

![image](https://user-images.githubusercontent.com/4013370/93497366-a28a7f80-f910-11ea-93bb-855753fac8e3.png)

**gives error: restoring bundle state - Uncought Exception**


# jdk 14
```
$ sudo update-java-alternatives -s java-14-oracle

$ java -version
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

~/ghidra_9.2_DEV/ghidraRun
```

`ps auwxf|grep ghidra.GhidraRun`

```
$ ps auwxf|grep ghidra.GhidraRun
user    15592  0.0  0.0  17744  1052 pts/2    S+   18:16   0:00  |   |   \_ grep --color=auto ghidra.GhidraRun
user    15434  0.0  0.0  18500  2180 pts/2    S    18:14   0:00 bash /home/user/ghidra_9.2_DEV/support/launch.sh bg Ghidra   ghidra.GhidraRun
user    15439 60.0  3.2 8008532 531428 pts/2  Sl   18:14   1:00  \_ /usr/lib/jvm/java-14-oracle/bin/java -Djava.system.class.loader=ghidra.GhidraClassLoader -Dfile.encoding=UTF8 -Duser.country=US -Duser.language=en -Duser.variant= -Dsun.java2d.opengl=false -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Dghidra.cacerts= -Dcpu.core.limit= -Dcpu.core.override= -Dfont.size.override= -Dpython.console.encoding=UTF-8 -Dghidra.util.swing.timeout.seconds=7600 -Dswing.systemlaf=com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatDraculaContrastIJTheme -Dsun.java2d.pmoffscreen=false -Dsun.java2d.xrender=true -Dsun.java2d.uiScale=1 -Dawt.useSystemAAFontSettings=on -showversion -cp /home/user/ghidra_9.2_DEV/support/../Ghidra/Framework/Utility/lib/Utility.jar:/home/user/ghidra_9.2_DEV/support/flatlaf-0.40.jar:/home/user/ghidra_9.2_DEV/support/flatlaf-intellij-themes-0.40.jar ghidra.GhidraLauncher ghidra.GhidraRun
```


![image](https://user-images.githubusercontent.com/4013370/93498422-0eb9b300-f912-11ea-8844-338842cf09c3.png)

**Comment by jpleasu** [comment]
You may have compiled some of your script directories with java 14 and java 11 can't load them.  Open window -> bundle manager and click the refresh button.

**Comment by astrelsky** [comment]
Just a side note. You have to explicitly enable preview features to use them. I have no idea why the java compiler doesn't care and fails anyway even though it knows the features are disabled and and older version of java is being targeted.

**Comment by pabx06** [comment]
used a different build env: 

> Just a side note. You have to explicitly enable preview features to use them. I have no idea why the java compiler doesn't care and fails anyway even though it knows the features are disabled and and older version of java is being targeted.

i was thinking the same:  i used amazon's correcto jdk's 11 same build error.
then i used travis to build and it passed : https://github.com/pabx06/buildghidra/tree/master
still have no idea why it fails on desktop

**Comment by pabx06** [comment]
> good find.
> I switched from oracle's jdk14 to oracle jdk 11. And i still having the same `error : reference to Record is ambiguous.`
> 
> i was able to build commit [7e5f015](https://github.com/NationalSecurityAgency/ghidra/commit/7e5f015d651b9c5e7825cb10bc50338b5af67538) with jdk 14 no problem's whatsoever...

`gradle --warning-mode all -info buildGhidra`

shows that gradle  was using jdk 14 with preview feature enabled because of env variable `JAVA_HOME=/usr/lib/jvm/java-14-oracle` was overriding `$PATH`. and ubuntu's `update-java-alternatives -s java-11-amazon-corretto` didn't update `JAVA_HOME` value.
what worked for me:
```
update-java-alternatives -s java-11-amazon-corretto
export JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto
```
