### ISSUE TITLE
How to improve the decompiler representation of stack strings

### ISSUE THREAD

**Issue by recvfrom** [NationalSecurityAgency/ghidra#2285]
The following function uses a fairly basic stack string, but the decompiler output isn't optimal for it:

![image](https://user-images.githubusercontent.com/36489577/93534822-d024f800-f913-11ea-991b-617151da0f86.png)

If the data type of local_20 is manually changed to `CHAR [22]` instead of `CHAR`, the output is a bit prettier:

![image](https://user-images.githubusercontent.com/36489577/93534938-fc407900-f913-11ea-894e-e8144d6ee850.png)

Would it be possible to have the decompiler show something more elegant, like `strcpy(local_20, "CreateTimerQueueTimer");`?  If so, what would be the best way to implement that?

**Comment by huntergregal** [comment]
+1 for handling stack strings. I need the Ida users to stop dunking on me with facts.
