### ISSUE TITLE
Wrong result for x64-lea with different prefixes

### ISSUE THREAD

**Issue by rfalke** [NationalSecurityAgency/ghidra#2286]
**Describe the bug**
A lea instruction for x64 doesn't compute the expected value.

**To Reproduce**
1. decompile https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/x64_lea/x64_elf/subject.exe
2. Output is:
```
undefined8 main(void)

{
  printf("lea1 should=0x1a2a3a4a5a6a7b8b/1885383485026892683 is=0x%016lx\n",0x1a2a3a4a5a6a7b8b);
  printf("lea2 should=0x1a2a3a4a5a6a7b8b/1885383485026892683 is=0x%016lx\n",0x1a2a3a4a5a6a7b8b);
  printf("lea3 should=0x000000005b6b7b8b/         1533770635 is=0x%016lx\n",0x5b6b7b8b);
  printf("lea4 should=0x000000005b6b7b8b/         1533770635 is=0x%016lx\n",0x1a2a3a4a5b6b7b8b);
  printf("lea5 should=0x1b2b3b4b5b6b7b8b/1957723657864969099 is=0x%016lx\n",0x1b2b3b4b5b6b7b8b);
  printf("lea6 should=0x000000005b6b7b8b/         1533770635 is=0x%016lx\n",0x5b6b7b8b);
  return 0;
}
```

lea4 is wrong. Asm instructions:
```
  4010bb:       48 b8 8a 7a 6a 5a 4a    movabs $0x1a2a3a4a5a6a7a8a,%rax
  4010c2:       3a 2a 1a 
  4010c5:       48 bb 8b 7b 6b 5b 4b    movabs $0x1b2b3b4b5b6b7b8b,%rbx
  4010cc:       3b 2b 1b 
  4010cf:       67 8d 03                lea    (%ebx),%eax
```

**Expected behavior**
Output should be:
```
  printf("lea4 should=0x000000005b6b7b8b/         1533770635 is=0x%016lx\n",0x5b6b7b8b);
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "11.0.5" 2019-10-15
 - Ghidra Version: 9.1.2_PUBLIC

**Comment by ghidracadabra** [comment]
Thanks for reporting this, looks like we're missing a zero extension here.  There are some other instructions with similar issues.

BTW, does that description actually go with this ticket?  I don't see anything about `in_PF`.

**Comment by rfalke** [comment]
I copied the description from another issue. I fixed it.
