### ISSUE TITLE
Can't change data (DATA) region to function (maybe because F context hotkey is aliased?)

### ISSUE THREAD

**Issue by mick-p1982** [NationalSecurityAgency/ghidra#2287]
I received a suggestion to use the C hotkey to "clear" my data region from the following Reddit conversation. But it doesn't work in my case. There is a Clear Code Bytes (C) option in the context-menu. Version is 9.1.2

https://www.reddit.com/r/ghidra/comments/itep0b/help_create_function_f_at_address_already/
> 
> **Help? Create function (F?) at address already designated as data (DAT_?) where F creates "float" instead of "function"?**
> 
> Sorry to be that guy, but I've learned (through interactions with people) I can press F to create a function in memory where I know there is one (that's either non existent or designated by "Undefined", disabled code) ... note I don't see F anywhere, it's just Ghidra magic (EDITED: Actually it's contextual, I'm unsure what enables Create Function (F).)
> 
> EXCEPT IN THIS ONE CASE I have a function pointer table, and one of the pointers is already decided by Ghidra to be data marked DAT_0040a3e0 and I can't figure out how to tell Ghidra it's not data. Even setting the type to "undefined" like the surrounding memory doesn't help, and what's worse is when I press F on it, it chooses a FLOAT data type instead of a FUNCTION.

The disassembly looks like this. The 45a890 reference is circular, in that it's the only reference, and it's inside the function-ptr table I'm trying to fix, so I don't know how Ghidra decided this entry in the table is data, since there's no code referencing it that Ghidra can find with the References search feature. I assume it was just marked as "data" since the project was first imported. (There's only reference to the table itself, i.e. the first address in the table/array, which is the call site.

```
                             DAT_0040a3e0                                    XREF[1]:     0045a890(*)  
        0040a3e0 8b              ??         8Bh
        0040a3e1 4c              ??         4Ch    L
        0040a3e2 24              ??         24h    $                                         ?  ->  018b0824
        0040a3e3 08              ??         08h
        0040a3e4 8b              ??         8Bh
        0040a3e5 01              ??         01h
        0040a3e6 33              ??         33h    3
        0040a3e7 d2              ??         D2h
        0040a3e8 66              ??         66h    f
        0040a3e9 8b              ??         8Bh
        0040a3ea 50              ??         50h    P

```

EDITED: I noticed the `?  ->  018b0824` part in the disassembly since the right-hand column is well offscreen in Ghidra. I don't know if it's significant, but it looks like it's interpreting those 4 bytes as a pointer even though they don't really have a type as such. It just has this distinction of "DAT_" that changes the meaning of F in the context menu, The data-type is "undefined".

**Comment by dev747368** [comment]
The step you are missing is the "Disassemble" command.  The bytes need to be recognized as instructions first before a function can be laid down at that location.

**Comment by mick-p1982** [comment]
Thanks! 

I wish I could use the documentation but in my experience it's not really geared for providing answers to these kinds of questions, maybe some section is, but it's really hard to know where to open the documentation up to so-to-speak.

Ghidra uses the "code" data-type to refer to function pointers and things, it would be good if that was one of the data types and that would automatically try to disassemble code. Or if the Make Function feature worked anywhere, at least in some form. Maybe put  Disassemble (D) beside the other features that change the representation of bytes, just some suggestions. 

It would just make it more foolproof. It should have occurred to me the bytes didn't look like normal disassembled data, but I didn't make the connection.
