### ISSUE TITLE
Handling "SFUs" when implementing new ISAs for Ghidra

### ISSUE THREAD

**Issue by moonheart08** [NationalSecurityAgency/ghidra#229]
# SFUs
I'm considering adding support for the MC88100 and MC88110 to Ghidra, and am wondering how SFUs would be handled.

The 88k ISA reserves a large chunk of opcode space for Special Function Units, which all use the same encoding.

There can be up to seven SFUs per chip, and the order/number of SFUs varys between units.

In reality only two 88k processors were ever released, and SFU mixing never actually happened, but let's pretend it did.

How would Ghidra know what instructions are assigned to which SFU, and what SFUs are active in which slots at the time, or is this not supported?

Oh, and one other potentially big issue (Haven't checked this one yet): SFUs get their own set of registers. Each SFU is given 64 registers that it can choose to use, not use, etc.

For reference, see the following pages in the [MC88110 Manual](http://www.bitsavers.org/components/motorola/88000/MC88110UM_88110_Users_Manual_1991.pdf) (Thanks Bitsavers!) for extra information on the problem.
10-095 (SFU Opcode Encoding)
10-096 (FPU aka SFU1, same on all systems)
10-097 (GPU aka SFU2, only on MC88110)
02-010 (Processor Status Register, contains SFU toggle bits)

**Comment by caheckman** [comment]
Ghidra and SLEIGH in particular have various mechanisms to support this kind of thing, but ultimately its up to the specification designer to decide exactly how to lay things out. Ghidra distinguishes between different processors using a 4 field "Language ID" (like x86:LE:32:default), which includes family, endianness, register size, and variant fields. The variant field would typically be used for this kind of thing. The designer would decide on an encoding scheme for the different SFUs that might be present and put particular encodings in the variant field. The different variants are layed out in the .ldefs file for the processor family, which associates the Language ID with the particular SLEIGH specification (the .slaspec file and its compiled .sla form).

Within the SLEIGH specifications, traditional "include" and macro definition mechanisms can be used to define the different processor variants, while still sharing the part(s) of the specification that are common to all the variants.  See the "Preprocessing" chapter within the SLEIGH documentation (under docs/languages in the distribution) in particular. Different register layouts are possible this way, and by putting instruction subsets in different files, a specification for a variant can be easily built up, that remaps a particular portion of the opcode space.

Take a look at the way the PowerPC specifications are layed out, as a good example. The files are under Ghidra/Processors/PowerPC/data/languages.  Start with the ppc.ldefs file. Different specification components are put in the .sinc files, and then a full specification is built in a .slaspec file using "include" and "define" statements.
