### ISSUE TITLE
Vertical Distance between Nodes in the DefaultGraphDisplay provider is unnecessarily large

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#2292]
**Describe the bug**

The vertical distance between vertexes in the DefaultGraphDisplay provider is huge 

**To Reproduce**
1. Use the `GraphAST.java`script

I don't know if this is enough already, or if this is an issue with High DPI screens. I have a debugging setup and can look into things to clarify if I can get some hints.

**Expected behavior**

The graph layout algorithms using the vertical space efficiently 

**Screenshots**

Generated Layout
![image](https://user-images.githubusercontent.com/8415354/93721587-94976180-fb91-11ea-9d06-d54995acd3c7.png)

After manual vertical shrinking
![image](https://user-images.githubusercontent.com/8415354/93721677-0f607c80-fb92-11ea-80c4-b1831a3a8b2d.png)

The hard to read font is another issue and can be mitigated by increasing `DEFAULT_FONT_SIZE`, but this requires absurdly huge numbers to work, so there is definitely some other issue. The following is a font size of 1024 instead of the default 12 (not a typo)

![image](https://user-images.githubusercontent.com/8415354/93722049-48015580-fb94-11ea-8453-76560836fe6d.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Java Version: 11
 - Ghidra Version: 02e017f50754d8ce8c91fa63b8adb931b4ec7796
 - 4k 26" Screen

**Comment by tomnelson** [comment]
Thanks for trying this out. I'm very interested in your feedback.
By default, the initial graph display tries to expand to use the entire window area. I'm not sure if it is in the branch yet, but there is a feature where you can CTRL mouse wheel or ALT mouse wheel to scale in only one axis at a time. 
Its a bit of a trade-off to make graphs of very different sizes work.
I'll look at how to make the default font more flexible, perhaps by using one of these properties:
[sample.jungrapht.properties](https://github.com/tomnelson/jungrapht-visualization/blob/master/jungrapht-visualization/src/main/resources/sample.jungrapht.properties)

**Comment by fmagin** [comment]
I found that feature, but this seems to only change the view itself. This results in the text getting squashed like this:
![image](https://user-images.githubusercontent.com/8415354/93779384-34eb9580-fc27-11ea-9518-66324daf5556.png)

Maybe this is the wrong approach for this problem though. What if we treat actual layout and distance between the 1D points as sensible, and require the nodes to render differently:
![image](https://user-images.githubusercontent.com/8415354/93779761-9875c300-fc27-11ea-8995-7ad713db0423.png)

The UI text is still readable and that level of readability for the node labels would already be a huge improvement. Especially of the ALT+mouse wheel scaling would not squish the text and node shapes.

**Comment by tomnelson** [comment]
I think that the single axis scaling should never squish the vertices and labels. I'll address that as a jungrapht bug.

**Comment by tomnelson** [comment]
If you want to try out the current 1.0-SNAPSHOT version of the graph code, it has some changes to the single-axis scaling. I'm not quite settled on the best solution. We can move that discussion here, if you like: [https://github.com/tomnelson/jungrapht-visualization/issues/18](https://github.com/tomnelson/jungrapht-visualization/issues/18)

**Comment by emteere** [comment]
Fixed in master, and will be included in 9.2

**Comment by fmagin** [comment]
@emteere 
I don't think this is fixed yet, or it broke again. I just did a clean build from current master 027ba3884a805f6736232e2ad399c3cea4ca5aa5 and the original problem persists.


@tomnelson 
This might also be a regression in jungraph because the vertex labels are getting squished too

**Comment by tomnelson** [comment]
Someone changed the jungrapht versions back to 1.0-RC9 instead of 1.0-SNAPSHOT.
If you update the version to just 1.0, you should see the fixes that you helped inspire.
Thanks again!

**Comment by fmagin** [comment]
yep, just looked into this further, works fine with `com.github.tomnelson:jungrapht-visualization:1.1-SNAPSHOT` 
So I guess the regression is https://github.com/NationalSecurityAgency/ghidra/commit/afd5baa914bd9b1b082531879272cd63fe03f489 by @ghidravore

**Comment by tomnelson** [comment]
You should use 1.0, not 1.1-SNAPSHOT
