### ISSUE TITLE
cxxfilt.c compilation fails on xcode 12

### ISSUE THREAD

**Issue by Roarrk** [NationalSecurityAgency/ghidra#2294]
**Describe the bug**
Building of newest ghidra fails on newest public xcode release. 

3 errors are generated from compiling cxxfilt.c due to missing explicit decleration, xcode clang has -Werror=implicit-function-declaration on by default. 

Edit: Add string.h and stdlib.h to cxxfilt.c to solve the implicit warnings (now errors). Or do like I did, don't read the error messages properly and add -Wno-error=implicit-function-declaration to compiler flags, that works too. 

**To Reproduce**
1. Git clone ghidra
2. Try to build (gradle buildGhidra) with newest Xcode 12 installed
3. See error

**Expected behavior**
Installation should succeed without overriding the Werror flag.

**Attachments**
compiling cxxfilt.c failed.
/Users/User/git/ghidra/GPL/DemanglerGnu/src/demangler_gnu_v2_33_1/c/cxxfilt.c:81:7: error: implicit declaration of function 'free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      free (result);
      ^
/Users/User/git/ghidra/GPL/DemanglerGnu/src/demangler_gnu_v2_33_1/c/cxxfilt.c:135:3: error: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]
  exit (status);
  ^
/Users/User/git/ghidra/GPL/DemanglerGnu/src/demangler_gnu_v2_33_1/c/cxxfilt.c:135:3: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
/Users/User/git/ghidra/GPL/DemanglerGnu/src/demangler_gnu_v2_33_1/c/cxxfilt.c:246:42: error: implicitly declaring library function 'strchr' with type 'char *(const char *, int)' [-Werror,-Wimplicit-function-declaration]
      while (c != EOF && (ISALNUM (c) || strchr (valid_symbols, c)))
                                         ^
/Users/User/git/ghidra/GPL/DemanglerGnu/src/demangler_gnu_v2_33_1/c/cxxfilt.c:246:42: note: include the header <string.h> or explicitly provide a declaration for 'strchr'
3 errors generated.

**Environment (please complete the following information):**
 - OS: MacOS 10.15.6
 - Java Version: openjdk@11
 - Ghidra Version: git ghidra (9.2 DEV)

**Comment by dragonmacher** [comment]
We will update `cxxfilt.c` to include `stdlib.h`

**Comment by Roarrk** [comment]
String.h is required as well, for the third error
