### ISSUE TITLE
Unable to locate script class: ... jdk 15

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2296]
**Describe the bug**
Attempting to run any ghidra script in Ghidra running on jdk 15 results in "Unable to locate script class: ..."

**To Reproduce**
1. Launch Ghidra with jdk 15
2. Try to run HelloWorldScript.java

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.508]
 - Java Version: 15
 - Ghidra Version: 9.2_DEV 02e017f50754d8ce8c91fa63b8adb931b4ec7796

**Additional context**
This is just for documentation purposes. There are no errors logged when trying to run a script.

**Comment by ryanmkurtz** [comment]
I think you love when new versions of Java come out even more than me!

**Comment by astrelsky** [comment]
> I think you love when new versions of Java come out even more than me!

I do it with everything. I don't do windows insider builds anymore though because I once dealt with an issue where my anti virus wouldn't cooperate to changes with windows explorer which would cause the explorer to crash after about 60 seconds of use.

Not sure why I do but I manually check for updates on everything when I start my laptop lol.

**Comment by jpleasu** [comment]
We'll need to update bndlib.  Until then, you can replace `Ghidra/Features/Base/lib/biz.aQute.bndlib-5.0.0.jar`
with [this one](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bndlib/5.1.2/biz.aQute.bndlib-5.1.2.jar) or update `Ghidra/Features/Base/build.gradle`, replacing 5.0.0 with 5.1.2, and rebuild.

**Comment by astrelsky** [comment]
> We'll need to update bndlib. Until then, you can replace `Ghidra/Features/Base/lib/biz.aQute.bndlib-5.0.0.jar`
> with [this one](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bndlib/5.1.2/biz.aQute.bndlib-5.1.2.jar) or update `Ghidra/Features/Base/build.gradle`, replacing 5.0.0 with 5.1.2, and rebuild.

That worked. Thank you.

**Comment by fenugrec** [comment]
Having the same issue on 10.1.4, java 18.0.1.1 ... would it the same root cause (i.e. bndlib ) ?

**Comment by ryanmkurtz** [comment]
Not sure, but bndlib has been upgraded in 10.2-DEV.  Can you try that?

**Comment by fenugrec** [comment]
> Not sure, but bndlib has been upgraded in 10.2-DEV. Can you try that?

Sorry, not before a few weeks

**Comment by ryanmkurtz** [comment]
Ok, just let us know if that doesn't end up fixing it for you.

**Comment by fenugrec** [comment]
> Ok, just let us know if that doesn't end up fixing it for you.

I tried my distro's 10.1.5 (still failed), but compiling from git @ 03bd4b45d00c2bdd46632b01408de2544d87287c and forcing jre18 , seems to work. I didn't bisect to see when it started working though.
Am I going to have problems with jre18, should I run with jre17 still ?

**Comment by ryanmkurtz** [comment]
When Ghidra 10.2 gets released, the official JDK it supports will be 17, which is an LTS release.  Having said that, if problems pop up with JDK 18 or later, we will do our best to fix them.

**Comment by tuxfobux** [comment]
Same issue, same solution. Thanks.
