### ISSUE TITLE
Overzealous new project path validation (Eclipse Plugin)

### ISSUE THREAD

**Issue by peterbelm** [NationalSecurityAgency/ghidra#2298]
**Describe the bug**
When the path to a new project directory starts with the path to the Ghidra installation (even if they are two different directories) the wizard won't proceed, presenting a "Project root directory cannot reside inside of the selected Ghidra installation directory" error.

**To Reproduce**
1. Create a Ghidra installation in C:\Ghidra
2. Create a C:\GhidraExtensionDev directory
2. Attempt to create a GhidraDev project of any type with the project root inside the C:\GhidraExtensionDev directory

**Expected behavior**
The wizard should detect that C:\Ghidra and C:\GhidraExtensionDev are different paths and allow the project to be created.

**Environment:**
 - OS: Windows 10 (10.0.18363 Build 18363)
 - Java Version: 8 (Update 251 build 1.8.0_251-b08)
 - Ghidra Version: 9.1.2

**Additional context**
While I'm using the C:\Ghidra path in the reproduce steps, it's worth noting that my actual paths were on a network mapped drive. A casual look at the wizard code seems to indicate this doesn't effect the issue - but I'm not experienced enough with Java to know for sure.

**Comment by dragonmacher** [comment]
Closed by 7391472

**Comment by ryanmkurtz** [comment]
@dragonmacher, i don't think my commit that fixed it made it in when the #1922 was merged in.  See #2314.
