### ISSUE TITLE
questions regarding to python3 support

### ISSUE THREAD

**Issue by Auxy233** [NationalSecurityAgency/ghidra#23]
I notice that there is a python console. However, it's a pretty old Python2. Do you support to use Python 3 as JPython integration?

**Comment by marcan** [comment]
There is no Jython 3.x, which I guess is the reason why Ghidra is stuck with Python 2.

**Comment by Auxy233** [comment]
So Python2 and Java are out only choices? Terrible ORZ. Do NSA guys consider use Scala or Kotlin for scripting?

**Comment by wsxarcher** [comment]
You can use any jvm language if you output a .jar implementing the correct interface.

For python script I suggest to move to https://github.com/graalvm/graalpython to support python3 and native python modules.

**Comment by ryanmkurtz** [comment]
Python and Java are the only implemented scripting languages, but Ghidra's scripting framework can be extended to support additional languages.  

Ghidra uses Jython as its Python implementation, which is stuck on Python 2.
