### ISSUE TITLE
How to add call to inlined function?

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2309]
I have a function that has been inlined. The non-inlined function itself exists in the program which I have marked as 'inline'. I cannot seem to figure out what needs to be done to convert the instructions to an inlined function call. I've tried selecting the corresponding instructions, creating a function and setting it's body to the currentSelection. I've tried creating a function out of the instructions and setting it as a thunk to the non-inlined version of the function (because ghidra does special things with thunked functions).

The help document isn't very helpful for this either. It states: "Inline enablement (if enabled, callers will inline function code)". Ok. That is what the compiler does. How do I make Ghidra undo it?

**Comment by ghidra1** [comment]
The existing `inline` function attribute in Ghdra is intended to handle the reverse of what you are trying to accomplish.  When this attribute is set it forces the decompiler to inline that functions pcode at any call site instead of handling as a call.  We have no means of handling the case you are referring to which can complicate things greatly when analyzing optimized code.  Frequently the inlined code can get quite entangled.

**Comment by astrelsky** [comment]
> The existing `inline` function attribute in Ghidra is intended to handle the reverse of what you are trying to accomplish. When this attribute is set it forces the decompiler to inline that functions pcode at any call site instead of handling as a call. We have no means of handling the case you are referring to which can complicate things greatly when analyzing optimized code. Frequently the inlined code can get quite entangled.

Oh. I see how that could be useful though, especially when a function is returning a constant.

**Comment by sad-dev** [comment]
One way you could try to do this is create a fake function (with the appropriate calling conventions) from those inlined instructions, and then replace instances of the inlined function with a call to the fake function by patching. 

It is probably unfeasible once you aren't dealing with small functions, but should work relatively neatly as long as you have enough bytes to patch in a call. Even on relatively small functions you would still need to take care that the decompiler knows which registers are (not) spoiled by the fake function.

**Comment by larkwiot** [comment]
Commenting because I'd really like this functionality to become possible even if it takes a script to define a function from bytes.

**Comment by ghidra1** [comment]
This has been a long standing issue.  The problem is compounded with optimized code where inlined function symbols may be placed causing the entry point analyzer to improperly create functions in the middle of other functions.  This is a very difficult problem to resolve and is not in the development plan at this point in time.

**Comment by Phlosioneer** [comment]
For anyone arriving via google search:
If you're REALLY need the inlined function separated out, especially when the inlined code is very long, there is a workaround. It's **awful** but it usually does the job well enough.

Before modifying anything, always make a backup of your workspace. Some of these steps may not be undo-friendly.

First, make a new memory region in the Tools->Memory Map window. Put its address somewhere normally unreachable. In my example, the original code was at 0xc20, so I chose 0x70000c20. (This inline is so small that this is overkill, but I'm using it as a real-world example.)

![2023-01-02_19-29](https://user-images.githubusercontent.com/4657718/210287780-ef7581d8-c97e-445c-aa1b-49a9dcad4e19.png)


Go to that part of the code, disassemble it (shortcut `d`), create a function (shortcut `f`). Back in the memory map window, add some extra bytes below it for a return statement. In my case, `ret` is 2 bytes.

![image](https://user-images.githubusercontent.com/4657718/210286499-69034556-6cb3-447a-854e-54de6f7f5e57.png)

Go back to the assembly view, right click the first new byte, and choose "patch instruction" (shortcut `ctrl+shift+G`).

![image](https://user-images.githubusercontent.com/4657718/210286567-534cfa22-95bd-4789-95ff-e2794d6bda2e.png)

Type in whatever opcode does a return in your language. Now go to the function you created, and fill in the details. Be sure to use Custom Storage to handle inputs/outputs correctly. Mine looks like this, but yours will differ:

![image](https://user-images.githubusercontent.com/4657718/210286720-fb3230a5-e753-4ab9-af32-702520cca51f.png)

And finally, the trick: Use the instruction patch to jump to the new memory address, followed by a jump to the next valid instruction. Then right click the branch to the new inlined function, choose the Modify Instruction Flow option, and use the `CALL` flow.

Final assembly: 
![image](https://user-images.githubusercontent.com/4657718/210287565-5b8e973c-0205-4529-8ae4-41b82fd3e0cb.png)

And decompiler output: 
![image](https://user-images.githubusercontent.com/4657718/210287596-0c1e126d-381c-47be-aebe-aa797ab07560.png)

In more advanced cases where there are intermixed but unrelated instructions, you may be able to move them to the bottom of the inlined area.
