### ISSUE TITLE
'Automatically Save Tools' option is set on startup

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#231]
**Describe the bug**
Option `Automatically Save Tools` (in main window of Ghidra: `Edit -> Tool Options... -> Tool`) is set between restarts.

**To Reproduce**
1. Unset option `Automatically Save Tools`
2. Close and open Ghidra
3. Option `Automatically Save Tools` is set

**Expected behavior**
The option setting is kept between restarts.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Comment by kant2002** [comment]
Same as #40

**Comment by saruman9** [comment]
Also didn't save some key bindings (the keys were set using F4: open Decompiler, close Tool, etc) after restarting. Was tested on Ghidra 9.0.1 release too. See also #152.
