### ISSUE TITLE
Decompiler Secondary Highlighting: Support Highlighting of Individual Tokens

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#2313]
**Describe the bug**
decompilerPanel.reapplySecondaryHighlights applies highlights by name. This means that the following can lead to undesirable results as it does not play nice with scripts that are context-sensitive:

**To Reproduce**
1.) Write a script that applies secondary highlights onto specific tokens (for example, a script that colors an entire block of code black to show that it is irrelevant/unreachable). 
2.) Switch function in the decompiler window and go back, or rename a variable in the window to force reapplication of secondary highlights.
3.) Any token that shares a name (including whitespace) with any token you applied a secondary highlight onto is highlighted (and all of them end up with a default color). 

**Environment (please complete the following information):**
 Ghidra master

**Desired behaviour**
Reapplication of secondary highlights should be token specific and preserve the original color they were given.

**Comment by dragonmacher** [comment]
Will you provide a small script code snippet that we could use to show this behavior?

**Comment by sad-dev** [comment]
The following snippet highlights the token under the cursor. 

`
DecompilerProvider decompilerProvider = (DecompilerProvider) tool.getComponentProvider("Decompiler");
DecompilerPanel decompilerPanel = (DecompilerPanel) (decompilerProvider.getComponent().getComponent(0));
ClangHighlightController chlc  = decompilerPanel.getHighlightController();

DecompilerLocation dloc = (DecompilerLocation) currentLocation;
ClangToken tokenAtCursor = dloc.getToken();
Color hlColor = new Color(128, 128, 128, 128);

chlc.addSecondaryHighlights(Set.of(token), hlColor);

`

**Comment by dragonmacher** [comment]
Thanks for the snippet.  This helps us understand how you would like to use the feature.

It appears as though you would like the current feature to have additional capabilities.  Specifically, you would like the ability to apply a secondary highlight to *individual tokens*, as opposed to all tokens that match the given text.  Is this correct?

Assuming this is what you would like, then this ticket should be considered feature request, not a bug.

It is certainly possible to update the existing feature.   Based on the fact that you are using this from a script, it is apparent to me that we need to provide a service for users to manipulate various parts of the Decompiler.    This service should provide a nice interface to allow users to manipulate the secondary highlights.

**Comment by Snorlax-lgtm** [comment]
Yes, that description is accurate. 

I agree that its probably closer to a feature request than a bug, given how tightly the secondary highlights are tied to token names in the decompilerPanel (I did spend a long time deliberating initially whether to submit it as a feature or bug report).

One benefit that you would probably have to give up if the secondary highlights are unpaired from token names is that renaming variables and other light changes won't lead to highlights being preserved anymore. I do think that this isn't a problem long term, as the 'correct' thing to do should be to perform an inline modification of the decompiler tree, which also avoids flushing the decompiler cache.

**Comment by sad-dev** [comment]
Yes, that description is accurate. 

One thing that you would lose by unpairing secondary highlights / token names is the persistence of secondary highlights across various changes in the program state that trigger a flushing of the decompiler cache. I do think that it isn't a problem long term as the largest cause of this is a renaming of a variable - which should be dealt with by performing an inline modification of the pcode/clang token tree anyway.
