### ISSUE TITLE
Building the GhidraDev Eclipse plugin from the command line or a Jenkins job

### ISSUE THREAD

**Issue by philpem** [NationalSecurityAgency/ghidra#2316]
I have a Jenkins job which periodically builds the HEAD of the Ghidra master branch and my fork. This works fine, but I have to build the Eclipse plugin separately. It would be nice to get a GhidraDev plugin zip file as part of the build process (which already produces a Ghidra installation .zip file)

Is there a known or recommended way to build the GhidraDev Eclipse plug-in from the command-line, or a Jenkins job?

**Comment by ryanmkurtz** [comment]
No, it would definitely be done that way if there was a known way that works.  There is a gradle plugin that is supposed to be able to do it, but I didn't have much luck with a while ago.
