### ISSUE TITLE
Support native Linux packages (rpm, deb)

### ISSUE THREAD

**Issue by mikemadden42** [NationalSecurityAgency/ghidra#2321]
On Linux, I use the zip release of ghidra.  It would be nice if native Linux packages such as rpm & deb were available as well.

Alternatively, it would be nice to have a universal package format like snap or flatpack available.

**Comment by mumbel** [comment]
that really seems like an OS issue.  Their target is 1 zip file that works for all supported operating systems, personally it doesn't make much sense to change that approach for a myriad of packaging you're asking for.  Arch Linux for example has already added Ghidra into their official repo

**Comment by mikemadden42** [comment]
Hi @mumbel . Thanks for the reply.  I think you're correct; the `zip` distribution could be seen as a universal format.

I was able to find some third-party support for CentOS & Fedora:
https://pkgs.org/download/ghidra

I have not found something similar for Ubuntu or Debian.

**Comment by ryanmkurtz** [comment]
We don't have any plans to distribute releases this way.
