### ISSUE TITLE
gradle buildGhidra fails with java version 

### ISSUE THREAD

**Issue by OrenGitHub** [NationalSecurityAgency/ghidra#2323]
I'm trying to build ghidra according to the manual.
Everything goes fine until I get to
```
$ gradle buildGhidra
```
Where I get the error:
```
Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'
```
However, my java version seems to be correct:
```
$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```
Can anyone help me to solve this?

**Comment by ryanmkurtz** [comment]
What is your JAVA_HOME variable set to?

**Comment by OrenGitHub** [comment]
It's actually empty.
Here is my java location:
```
$ which java
/usr/bin/java
```

**Comment by mendax47** [comment]
SET Your JAVA_HOME to Your JAVA 11 Directory...

**Comment by OrenGitHub** [comment]
Do you mean `$ export JAVA_HOME=/usr`?
Because I tried that and nothing changed

**Comment by ryanmkurtz** [comment]
What is your output of `javac -version`? (note the "c" on the end of java)

**Comment by OrenGitHub** [comment]
```
$ javac --version
javac 11.0.8
```

**Comment by mumbel** [comment]
how about output of `update-alternatives --config java` and `update-alternatives --config javac`    since it looks like you have 8 and 11, maybe something still thinks 8 is preferred, this might be another place that could toggle that

**Comment by OrenGitHub** [comment]
```
$ update-alternatives --config java
There is only one alternative in link group java (providing /usr/bin/java): /usr/lib/jvm/java-11-openjdk-amd64/bin/java
Nothing to configure.
```
similar results for `javac`:
```
$ update-alternatives --config javac
There is only one alternative in link group javac (providing /usr/bin/javac): /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
Nothing to configure.
```
and gradle version:
```
$ gradle --version

------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_265 (Private Build 25.265-b01)
OS:           Linux 5.4.0-48-generic amd64
```

**Comment by ryanmkurtz** [comment]
It looks like Gradle is trying to use java 8.  Try running this (all on one line):

`JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 gradle buildGhidra`

**Comment by OrenGitHub** [comment]
@ryanmkurtz still no go, I get the same error

**Comment by ryanmkurtz** [comment]
what if you do:

`JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 gradle --version`

**Comment by OrenGitHub** [comment]
still `JVM:          1.8.0_265 (Private Build 25.265-b01)`

**Comment by mumbel** [comment]
Do you have a `~/.gradle/gradle.properties` file? if so does it specify `org.gradle.java.home` maybe to version 8?

**Comment by ryanmkurtz** [comment]
Hmmm, it's as if Gradle is not getting your JAVA_HOME variable.  You could try going into build.gradle in the top-level Ghidra folder and adding:

`project.ext.JAVA_HOME = "/usr/lib/jvm/java-11-openjdk-amd64"`

to line 27.

**Comment by OrenGitHub** [comment]
```
/***************************************************************************************
 * Define the location of JAVA_HOME
 ***************************************************************************************/
if (System.env.JAVA_HOME) {
	// Allow Gradle's default JAVA_HOME to be overridden by an environment variable we set
	project.ext.JAVA_HOME = System.env.JAVA_HOME;
}
else {
	project.ext.JAVA_HOME = "${System.properties.'java.home'}"
}
project.ext.JAVA_HOME = "/usr/lib/jvm/java-11-openjdk-amd64"
```
but still not working

**Comment by OrenGitHub** [comment]
@mumbel no, I don't have the file `~/.gradle/gradle.properties`

**Comment by ryanmkurtz** [comment]
I'm stumped.  Maybe your problem is similar to this:

https://stackoverflow.com/questions/22307516/gradle-finds-wrong-java-home-even-though-its-correctly-set

**Comment by OrenGitHub** [comment]
Thanks @ryanmkurtz , @mendax47 , @mumbel for all your help !
After some blood sweat and (yes) tears, I have managed to put the blame on gradle.
I upgraded to [gradle 6.7](https://services.gradle.org/distributions/gradle-6.7-rc-3-bin.zip)
**without any change** to java, JAVA_HOME, JAVA_PATH etc. and re-ran `gradle-6.7 --version`. I got:
```
------------------------------------------------------------
Gradle 6.7-rc-3
------------------------------------------------------------

Build time:   2020-09-30 19:16:51 UTC
Revision:     836e96a80625c9c48b612e662e3b13bd2e2f4c3b

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.8 (Ubuntu 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OS:           Linux 5.4.0-48-generic amd64
```
which kinda "proves" gradle is indeed "guilty".
From that point on, gradle manages to build correctly

**Comment by ryanmkurtz** [comment]
I switched my gradle to the one you were using and I didn't have any problem.  I also didn't have any Java 8's installed though.  Anyway, I'm glad you got it working.
