### ISSUE TITLE
Support for Golang binaries

### ISSUE THREAD

**Issue by mikemadden42** [NationalSecurityAgency/ghidra#2327]
Does ghidra have support to reverse engineer Windows/Linux/macOS binaries that were written in Golang?  I did see a similar issue that was closed:

https://github.com/NationalSecurityAgency/ghidra/issues/2207

The mentioned project (https://github.com/felberj/gotools) only adds basic functionality for Linux x86_64 Golang binaries.  It would be great if ghidra fully supported Golang binaries.  Thanks.

**Comment by ZoltanBalazs** [comment]
Please watch this space, as more and more Golang support is added: 
https://github.com/getCUJO/ThreatIntel/tree/master/Scripts/Ghidra

**Comment by marcushall42** [comment]
The golang parameter convention (at least on the x86-64) is annoyingly different from the C convention.  It would be really useful to have a 'golang' compiler spec attached to some languages so that at least argument passing would decompile properly.

**Comment by dev747368** [comment]
closed by 87c16f9cd0439427b6c3196c9af2470770c4ef6d
