### ISSUE TITLE
Return value not set in MIPS

### ISSUE THREAD

**Issue by bigianb** [NationalSecurityAgency/ghidra#233]
I've been working a little on a MIPS extension to add the PS2 Emotion Engine opcodes. I think I understand the sleigh code, but I'm a little confused as to what the decompiler is doing with the return value. All of the decompiled functions return no value rather than v0. See the function below .. it is about as simple as it gets.
It appears there is some confusion between v0_lo and V0 (v0_lo is the 32 bit version of the 64 bit v0 register). This is the original MIPS code and so I don't think it is directly anything I have done by adding the EE instructions.
Any ideas? Is it something to do with the compiler spec?

![image](https://user-images.githubusercontent.com/2781371/54649647-fd84b180-4aa2-11e9-89f6-377f444e288a.png)

**Comment by emteere** [comment]
The default return is undefined, so it is showing the smallest register that will fit the 1 byte value.  That isn't the issue.  The load is a 4 byte load from memory.

longlong FUN_00107b68(void)
{
  return (longlong)_DAT_00449528;
}
                             longlong  FUN_00107b68 (void )
             longlong          v0:8           <RETURN>
                             FUN_00107b68
        00107b68 45  00  03  3c         lui        v1 ,0x45
        00107b6c 28  95  62  8c         lw         v0 ,-0x6ad8 (v1 )=> DAT_00449528
        00107b70 08  00  e0  03         jr         ra
        00107b74 00  00  00  00         _nop

For your function the decompiler in the stock MIPS:LE:64:64-32addr (1.5) displayed the return value dynamically.  I locked in the longlong return to show the bigger register.

undefined4 FUN_00107b68(void)
{
  return _DAT_00449528;
}

Did you copy the language, or just edit the existing one?
Did you make any changes to the .cspec file?
In the ldefs file did you add an entry for your variant or is it the same?

**Comment by xyzz** [comment]
Your function signature in the decompiler is set to return void, I'm not sure why it happens but sometimes I also get function signature desync between disassembly and decompile listings. You can right click the decompile window, select "Edit function signature", and set a proper return type (e.g. int)

**Comment by bigianb** [comment]
Thanks for taking a look. I made a copy of the files to reduce the complexity with a possible aim of merging changes back into mips at later stage.
The cspec file is here: 
https://github.com/bigianb/ghidra-ps2ee/blob/master/data/languages/ps2ee.cspec

It looks to have the return value set. I didn't change it other than removing the configurations that are not relevant.

**Comment by bigianb** [comment]
I think the issue here is probably that I don't fully understand the cspec format. Closing this with a request that .cspec specification is documented in the future (I guess we can figure it out when the full code is open sourced)
