### ISSUE TITLE
BUG: ELF imports are not correct on stripped ET_EXEC w/ only DYNAMIC 

### ISSUE THREAD

**Issue by Jegeva** [NationalSecurityAgency/ghidra#2334]
**Describe the bug**
A clear and concise description of the bug.

When loading a stripped elf (ET_EXEC) with no sections (only relying on DYNAMIC), ghidra can sometimes mixup the import and the exports, acting as if the functions and DT_PLTGOT are actually exports of a ET_DYN.

**To Reproduce**
import the rshell.stripped vs the rshell.notstripped (a uclibc so is included so you can see the linkage).

**Expected behavior**
imports are solved as imports on the left menu
**Attachments**
[ghidra.issue.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/5328063/ghidra.issue.tar.gz)

If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Debian
 - Java Version: 11
 - Ghidra Version: 9.0-> 9.2_DEV

**Additional context**
merge request on its way

**Comment by ghidra1** [comment]
Issue resolved with GP-252

**Comment by Jegeva** [comment]
i confirm, this works. Thanks :)
