### ISSUE TITLE
Creating string-utf16 creates ascii string

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2338]
**Describe the bug**
Creating a type specified at `string-utf16` creates an ascii string

**To Reproduce**
1. Select some utf-16 string data
2. Press `t`
3. type `string-utf16` and hit enter
4. See ascii string

**Expected behavior**
The charset of the created string should be utf-16 like when `string-utf8` is chosen, or the
`Unrecognized data type of "string-utf16"` message should be displayed.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.508]
 - Java Version: 15
 - Ghidra Version: 9.2_DEV 2b08598dbabe6a9c911e712bd928e5f84fb00ee8

**Additional context**
I decided to submit this only because the type `string-utf16` was accepted.

**Comment by dev747368** [comment]
what is this string-utf16 you speak of?

**Comment by astrelsky** [comment]
> what is this string-utf16 you speak of?

That's the thing, afaik it isn't a built-in type, yet it is accepted as a valid type.

**Comment by dev747368** [comment]
I'm not able to duplicate that.  Is this an issue with only that exact type name, or is it something more general like if you match a prefix portion of a real data type name?
Is there any timing issues with name search/hint list?

**Comment by astrelsky** [comment]
> I'm not able to duplicate that. Is this an issue with only that exact type name, or is it something more general like if you match a prefix portion of a real data type name?
> Is there any timing issues with name search/hint list?

wow. Ok so this is occurring for anything. If you enter any valid datatype name, then `-` followed by anything it accepts it.

ex: creating an `int-vndjsvnkdjv` will just create an int.

![Capture](https://user-images.githubusercontent.com/46897303/95266174-aec37780-0800-11eb-9e27-3246c4355aed.PNG)

**Comment by dev747368** [comment]
Is this happening in any binary/code browser tool/project/without any extra data type archives open?  Could you try the pre-built 9.1.2 distro instead of your dev9.2?

**Comment by astrelsky** [comment]
> Is this happening in any binary/code browser tool/project/without any extra data type archives open? Could you try the pre-built 9.1.2 distro instead of your dev9.2?

I got it. This is related to having #2189
