### ISSUE TITLE
Decompiler: Vararg parameters not always handled

### ISSUE THREAD

**Issue by nezza** [NationalSecurityAgency/ghidra#234]
**Describe the bug**
In quite some cases the decompiler does not identify parameters to vararg functions such as printf/sprintf correct.y

**To Reproduce**
1. Get a wannacry sample, for example https://www.virustotal.com/gui/file/24d004a104d4d54034dbcffc2a4b19a11f39008a575aa614ea04703480b1022c
2. Go to function `FUN_00407ce0`
3. Scroll down to the sprintf calls at offset `407e18`
4. See that three arguments are pushed to `sprintf` but only two are identified.

**Expected behavior**
The call should look like
`sprintf(&local_104,s_C:\%s\qeriuwjhrf_00431344,"WINDOWS")`

**Screenshots**
<img width="1140" alt="Screenshot 2019-03-20 at 12 48 09" src="https://user-images.githubusercontent.com/208596/54684407-85ef6a80-4b14-11e9-8704-77ad3ce530d1.png">
<img width="800" alt="Screenshot 2019-03-20 at 12 48 19" src="https://user-images.githubusercontent.com/208596/54684409-87b92e00-4b14-11e9-8db8-d64e92688d87.png">

**Environment (please complete the following information):**
 - OS: macOS 10.14.3
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Comment by marcushall42** [comment]
Varargs can sometimes be difficult to tell apart from local stack variables on many processors.  It is possible to provide a function signature override at the calling site.  This can specify the appropriate types for the various arguments on this particular call.  It helps the decompiler understand what's going on elsewhere in the function as well.

**Comment by nezza** [comment]
Yep, that was my workaround, but in this case the call on the assembly-side is pretty clear (and handled fine by other decompiler), that's why I think it might be a bug

**Comment by sbingner** [comment]
The workaround doesn't really work when the arguments are on the stack anyway - you can't override a single call with stack args (it only lets you provide a signature not custom storage).  You would have to edit ALL calls from your program, and not all calls will be the same.

**Comment by mytbk** [comment]
I found this problem, and I want the decompiler to handle this. I see in the function signature window supports varargs, but I don't know how to specify the storage of it.

**Comment by ariccio** [comment]
+1 found this problem while reversing a program that uses wsprintf
![epsonScan](https://user-images.githubusercontent.com/2142308/96772201-c8dc8880-13b0-11eb-8a27-5de4487f0443.png)

**Comment by Wall-AF** [comment]
The current solution is to use the manual "Override Signiture" option and DIY.
![image](https://user-images.githubusercontent.com/67698927/96927077-708bb080-14ae-11eb-85da-40637c0f49ae.png)

**Comment by ghidracadabra** [comment]
The "Variadic Function Signature Override" analyzer will find calls to these functions, parse the format strings, and apply the correct signature override.  It's off by default, but you can enable it during initial analysis or run it as a one shot analyzer via Analysis->One Shot->Variadic Function Signature Override.

Note that this analyzer didn't exist when this issue was initially reported.

**Comment by Wall-AF** [comment]
@ghidracadabra it still fails when the base pointer size (as defined in the `x86****.cspec`) differs from the actual pointer size used in the code.  I.e. when segment based pointers are in play!
