### ISSUE TITLE
Sleigh compiler crash with specific slaspec

### ISSUE THREAD

**Issue by sualk-27o** [NationalSecurityAgency/ghidra#2342]
**Describe the bug**
Compiling the attached minimal slaspec the sleigh compiler crashes and doesn't output anything.
If i comment out the two marked lines with "# this" at the end, the compilation works as expected.
To my understanding the slaspec should be fine.

**To Reproduce**
Compile the slaspec file with
`sleigh minimal.slaspec minimal.sla`
This will exit with code 1 and no output or .sla file generated.

**Expected behavior**
A succesfull compilation of the slaspec file or at least an error message what is wrong with the slaspec.

**Attachments**
[minimal.txt](https://github.com/NationalSecurityAgency/ghidra/files/5342887/minimal.txt)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk 11.0.8
 - Ghidra Version: 9.1.2 stable

**Comment by mumbel** [comment]
have you tried the debug flags to get more information?

line 28, you cannot `[offset = uimm15; ]` either `offset: uimm15` or `[offset = uimm15 + 0;]`

you might try renaming the action variable to see if that changes anything so the name wouldn't conflict with the table ie `[imm = uimm15 * 4; ]`

**Comment by emteere** [comment]
This has been addressed in master and 9.2 with some recent fixes for error messages in the sleigh compiler.
You used to have to just know not to do this as @mumbel has learned the hard way.

In 9.2 when compiling this you get:
Error: operand offset has an issue: for table "offset" constructor from minimal.slaspec:28

Still not what I would call crystal clear.
We could add a check for this in the SleighEditor so it will make it an error if you just copy in the match action.

**Comment by astrelsky** [comment]
> This has been addressed in master and 9.2 with some recent fixes for error messages in the sleigh compiler.
> **You used to have to just know not to do this** as @mumbel has learned the hard way.
> 
> In 9.2 when compiling this you get:
> Error: operand offset has an issue: for table "offset" constructor from minimal.slaspec:28
> 
> Still not what I would call crystal clear.
> We could add a check for this in the SleighEditor so it will make it an error if you just copy in the match action.

A lot of sleigh is like that.

**Comment by sualk-27o** [comment]
Using `offset = uimm15+0` or `offset = uimm15*1` fixed the issue.
Renaming the table had no effect, but in the complete slaspec the table is currently named differently. Just used `offset:` in this minimal example.

Thanks a lot!
