### ISSUE TITLE
Z80 and Z180 incorrect CPIR instruction decompile

### ISSUE THREAD

**Issue by depili** [NationalSecurityAgency/ghidra#2343]
**Describe the bug**
The CPIR instruction in z80.slaspec file has a logic error that inverts the end condition of the compare loop.
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/Z80/data/languages/z80.slaspec#L656
The implemented instruction returns to the start of the compare loop if the compare result is 0, when it should only do so if the result is nonzero.

This screenshot shows the incorrect decompilation with senseless end condition for the while loop:
<img width="992" alt="Screenshot 2020-10-08 at 11 16 06" src="https://user-images.githubusercontent.com/3681069/95432714-b0ec1a00-0957-11eb-8618-d02c75beba4f.png">

**Expected behavior**
The while loop should end with `while (some_searched_byte != byte_under_test || i != 0);`

**Environment (please complete the following information):**
 - OS: macOS 10.15.6
 - Java: 13.0.2
 - Ghidra Version: Running a fork from https://github.com/astrelsky/ghidra.git for support for jdk14, sleigh files from 5b112cf

**Comment by esaulenka** [comment]
@depili, can you check `CPDR`? Looks like same issue in it.

**Comment by depili** [comment]
Yes, CPDR has the exact same issue on https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/Z80/data/languages/z80.slaspec#L686 it should be cmp != 0

The rom I'm currently working with doesn't use that instruction so didn't check that one.

I feel that the whole z80 slaspec could use an audit, for example the flags in F should be named as currently the decompilation with conditionals tends to get extra messy, but that is stuff for another issue / pull request.

**Comment by neuromancer** [comment]
Can this issue be closed or it is still affecting the decompilation?

**Comment by depili** [comment]
The fix in #2437 looks good to me.
