### ISSUE TITLE
struct creation containing itself clears other elements

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#2345]
9.1.2 / windows 10

This is just from typing too fast, not sure its that big of an issue, but maybe worth eventually looking into.

If you create a struct with itself as like a next pointer and just go to fast without getting the asterisk in, upon pressing enter/tab it will clear the entire struct instead of just erroring out trying add itself.

**Comment by astrelsky** [comment]
Can reproduce on 9.2_DEV 341f07f1a2668ce88bdda11894372137e88e3c74

When the error msg is produced all unsaved data is cleared. This occurs whether you have had way too much coffee or are about to fall asleep at your desk.

**Comment by mumbel** [comment]
Ah, yeah, I thought I had verified that, guess not.  It is only unsaved data that is lost
