### ISSUE TITLE
Editing the Initialized status of a MemoryBlock bytemaped

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2346]
hi.
let says i have this memory block named '.intercall' in the memory Map:
![image](https://user-images.githubusercontent.com/4013370/95570647-7fdb1a80-0a27-11eb-97da-f0ec1187560f.png)

for somme reason i  used a script to change the bytes ie:

```
MemoryBlock block ...
block.putBytes(block.getStart(), aByteArray);
```
Question how do i change is Initialized checkbox ? The User interface didn't allow to tick checkbox.
and the [api](https://ghidra.re/ghidra_docs/api/ghidra/program/model/mem/MemoryBlock.html) dont have a method.
this is issue seems to be only related to Byte Mapped type of block

because i later use a script : 
```
if(block.isInitialized()) {
//do stuff
}

**Comment by pabx06** [comment]
Also is there a filter text filed to search for a specific block by name . in the case where there is over 40 blocks of memory ?

**Comment by astrelsky** [comment]
You can use `Memory.convertToInitialized(MemoryBlock, byte)` but I'm not exactly sure you would want to do this for a byte mapped block. When you utilized `MemoryBlock.putBytes` did you do so on the `.intercall` block or the block containing what `.intercall` is mapped to? I would expect some sort of exception from attempting to write data into a byte mapped block and a `MemoryAccessException` is supposed to be thrown by `MemoryBlock.putBytes` if the block is uninitialized.

**Comment by pabx06** [comment]
i dont remember witch block i overiten. Either source or the bytemapped one...

solved by replacing ``(block.isInitialized())`` with ``(block.isInitialized()|| block.isMapped())``
