### ISSUE TITLE
Indirect function call showing in HighFunction Pcode as CALL rather than CALLIND

### ISSUE THREAD

**Issue by LiptonB** [NationalSecurityAgency/ghidra#2349]
**Describe the bug**
When a function in a windows binary calls a library function it can do so using an indirect `CALL` instruction like the following:
```
CALL       qword ptr [->KERNEL32.DLL::CreateDirectoryA]
```
where `->KERNEL32.DLL::CreateDirectoryA` represents a location in the Import Address Table that contains the address of the library function to call.

When a HighFunction is extracted from this calling function, this call is represented in the Pcode as
```
 ---  CALL (ram, 0x180011000, 8) , (unique, 0x1000003a, 8) , (const, 0x0, 8)
```
where 0x180011000 is the address of the Import Address Table slot. This seems wrong, because the description of the CALL/BRANCH opcode states, "The varnode parameter input0 encodes the destination address (address space and offset) of the jump. The varnode is not treated as a variable for this instruction and does not store the destination." Based on that description, this appears to be a jump to address 0x180011000, not a jump to an address stored at 0x180011000. See screenshots below for a better look at the function and target.

**To Reproduce**
1. Load a Windows binary that calls imported functions via an indirect `CALL` instruction, such as the attached example.dll
2. Locate the function that makes the indirect `CALL` (FUN_180001020 in the attached DLL)
3. Use the attached decompile_to_pcode.py to decompile to a HighFunction and display its Pcode
4. Note CALL Pcode operation with input0 that is the address of a function pointer, not a function

See screenshots below for the output I'm getting from this procedure.

**Expected behavior**
I believe the generated Pcode for this scenario should be:
```
 ---  CALLIND (ram, 0x180011000, 8) , (unique, 0x1000003a, 8) , (const, 0x0, 8)
```
The CALLIND/BRANCHIND opcode states, "The address to branch to is determined dynamically (at runtime) by examining the contents of the variable input0," which sounds exactly like what is happening in this code.

**Screenshots**
Calling function:
![Screen Shot 2020-10-09 at 5 11 55 PM](https://user-images.githubusercontent.com/467965/95632075-da3da080-0a52-11eb-9e7f-fd39637358fe.png)

Contents of memory location 0x180011000, a.k.a `->KERNEL32.DLL::CreateDirectoryA`:
![Screen Shot 2020-10-09 at 5 09 08 PM](https://user-images.githubusercontent.com/467965/95632116-f0e3f780-0a52-11eb-81ff-95f88ab65a8d.png)

Raw Pcode of the two nearly identical `CALL` instructions
![Screen Shot 2020-10-09 at 5 13 09 PM](https://user-images.githubusercontent.com/467965/95632208-27ba0d80-0a53-11eb-9d52-0b73fc826689.png)

Pcode produced by decompile_to_pcode.py (script attached below) uses CALL for one instruction and CALLIND for the other. Both addresses are the addresses of the function pointer, not the function itself.
![Screen Shot 2020-10-09 at 5 17 27 PM](https://user-images.githubusercontent.com/467965/95632291-546e2500-0a53-11eb-9ee1-d7857a0d49d4.png)

**Attachments**
[decompile_to_pcode.py](https://github.com/NationalSecurityAgency/ghidra/files/5357600/decompile_to_pcode.py.txt)
[example_dll.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/5357647/example_dll.tar.gz)

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - Java Version: openjdk version "12.0.2" 2019-07-16
 - Ghidra Version: 9.0.4 and 9.1.2

**Comment by LiptonB** [comment]
Debug xml file: [example.dll.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/5366321/example.dll.xml.txt)

It seems like the CALLIND -> CALL change happens [here](https://github.com/NationalSecurityAgency/ghidra/blob/f7f366b261589a65696c17852812566b9e6659bb/Ghidra/Features/Decompiler/src/decompile/cpp/coreaction.cc#L1176) in `ActionDeindirect::apply`. The CALLIND goes to an external ref, so this action resolves the external ref to a function and changes the CALLIND to a CALL to that function. Unfortunately, both the external ref and the function have the address 0x180011000 in the xml. So this resolution changes an indirect call to 0x180011000 into a direct call to 0x180011000.

External ref symbol:
```
          <mapsym>
            <externrefsymbol name="CreateDirectoryA_exref">
              <addr space="ram" offset="0x180011000"/>
            </externrefsymbol>
            <addr space="ram" offset="0x180011000"/>
            <rangelist/>
          </mapsym>
```
Function symbol for `KERNEL32.DLL::CreateDirectoryA` 
```
          <mapsym>
            <function name="CreateDirectoryA" size="2">
              <addr space="ram" offset="0x180011000"/>
...
            </function>
            <addr space="ram" offset="0x180011000"/>
            <rangelist/>
          </mapsym>
```

Is it correct for the external ref and the function itself to have the same address?

**Comment by ghidra1** [comment]
Any time an indirect call/branch occurs using a constant pointer (read from read-only memory) the transformation to a direct call/branch will occur.  In addition, if the pointer has an External reference that reference will be used in place of following the pointer.    If you remove the External reference from the pointer and disable the tool option `Decompiler->Analysis->Respect readonly flags` you will see it revert to an indirect call representation in the Decompiler.

The External reference refer to an External Location which may, or may not, have an associated address within the memory space.  In this case the pointer from the import address table was copied to the External Location definition.
