### ISSUE TITLE
Possible 9.2 file import issue--FYI only, not a fix request.

### ISSUE THREAD

**Issue by hachinijuku** [NationalSecurityAgency/ghidra#2354]
**Describe the bug**
Ghidra_9.2_dev (that I somehow found somewhere--I'm sorry I can't reconstruct where I got it)
throws an "IllegalArgumentException: Invalid block name" importing a specific file.
I'm not sure if this will happen with current dev version, but I just wanted you to be aware of the possibility.
![Screen Shot 2020-10-11 at 14 54 07](https://user-images.githubusercontent.com/27042925/95687527-0d5a6e00-0bd2-11eb-9b37-08a28fd32b75.png)

It loads in 9.1, but the headers seem to be broken in some way--the program tree is bad.
![Screen Shot 2020-10-11 at 14 54 07](https://user-images.githubusercontent.com/27042925/95687509-f451bd00-0bd1-11eb-8455-6658d3b15011.png)

**To Reproduce**
1. Download this sample from Hybrid Analysis:
https://www.hybrid-analysis.com/sample/adba3b08e6bde38cc0e035b3169c17b298fb2aea692770aecd9144bedef02b7b?environmentId=100
2. Import it into a Ghidra_9.2 project using File->Import File
3. Wait momentarily while the import crashes.
**Expected behavior**

**Screenshots**

**Attachments**
Screens shot attached:
1. Failed load under 9.2
2. Loading under 9.1.2 but with broken Program Tree (sections not shown properly).

**Environment (please complete the following information):**
 - OS: Linux remnux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - openjdk 11.0.8 2020-07-14
  OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
  OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
 - Ghidra Version: 9.2_dev from approx July 31 -- yes I don't know where I found this distro, but I have it

**Additional context**
Thanks for your tireless efforts!

![Screen Shot 2020-10-11 at 14 48 49](https://user-images.githubusercontent.com/27042925/95687538-2bc06980-0bd2-11eb-9038-ebabb06e6867.png)
![Screen Shot 2020-10-11 at 14 54 07](https://user-images.githubusercontent.com/27042925/95687539-2cf19680-0bd2-11eb-854a-ebd9b33f1a42.png)

**Comment by astrelsky** [comment]
Maybe fixed by #2329?

**Comment by ghidra1** [comment]
Block naming constraints have been tightened for 9.2 so it may have gone through without detection in 9.1.  As @astrelsky  indicated, hopefully #2329 will resolve which should will be merged shortly.

**Comment by ryanmkurtz** [comment]
I cannot download the sample, but looking at the section names that hybrid analysis provides, I feel safe closing the ticket as being fixed by #2329 for 9.2.  Please reopen if you are still having an issue with it.
