### ISSUE TITLE
How to compile the decompiled code?

### ISSUE THREAD

**Issue by anwarmamat** [NationalSecurityAgency/ghidra#236]
I could not re-compile the code generated by the decompiler.  For the simple code below 
#include<stdio.h>
int main(){
  int a;
  scanf("%d",&a);
  int b = a * 2;
  printf("%d\n", b);
  return 0;
}

ghidra decompiler generates hundreds lines of code. main function looks like this:

undefined8 main(void)
{
  long in_FS_OFFSET;
  int local_18;
  uint local_14;
  long local_10;
  
  local_10 = *(long *)(in_FS_OFFSET + 0x28);
  __isoc99_scanf(&DAT_00100814,&local_18);
  local_14 = local_18 * 2;
  printf("%d\n",(ulong)local_14);
  if (local_10 != *(long *)(in_FS_OFFSET + 0x28)) {
                    // WARNING: Subroutine does not return
    __stack_chk_fail();
  }
  return 0;
}
 
Now, how do I compile this code? There is no definition for ulong, uint, code, scanf etc. Am I missing the flag or something when I decompiled?

**Comment by d-millar** [comment]
Hi anwarmamat,

As you may know, compilation is an inherently lossy process.  Information such as variable names and types are lost unless explicit steps are taken to preserve then in the compilation process, for example by requesting debug symbols.  Once compiled, variables are basically just unnamed, unsized locations in the memory or register space.  

The decompiler attempts to make some reasonable deductions regarding types based on how the variables are used in order to produced something resembling the original code.  For instance, in your example, it concluded that the local variables local_14 and local_18, corresponding to b and a, were originally defined to be unsigned and signed integers.  The type definitions were buried in the files you #include'd in your original code but that information is not present in the executable.  In some cases, it makes sense for the decompiler to guess; in others, it really has insufficient information.

For you to recompile the code produced by the decompiler, you'll have to explicitly supply some bits of information that were lost.  In particular, you'll need to add the #include's so that your compiler has information about types like "uint" and function definitions like "_isoc99_scanf".  You'll also have to link against the library containing "scanf" as your executable was probably not statically linked.

Shout if any of this is unclear,
Dave

**Comment by d-millar** [comment]
More follow-up (and something I didn't know, so thanks for asking this question!):  if you choose File->ExportProgram from the CodeBrowser tool and select "Format: C/C++", the output file (by default in your home directory) does (at least on the sample I tested) write out all the typedef information, including function prototypes, that you'll need to re-compile.  I.e. should obviate the need for adding a #include.  Again, if the program wasn't statically linked originally, you'll need to link against the standard I/O lib for scanf, printf, etc., but...

**Comment by anwarmamat** [comment]
I can recompile the decompiled code after adding a header or a missing type etc.  Can you show me a simple example that can be re-compiled without manually modifying the decompiled code?

**Comment by DrTsukamoto** [comment]
I think you should always expect to have to do some manual work - that is to say, any example I could provide would likely be extremely contrived.  In particular, there are known problems with the exported output emitting variable names the are not legal or not unique.  Some of these are perhaps fixable, but again there are always losses in the compilation process that make a perfect decompilation unlikely.

**Comment by d-millar** [comment]
I think you should always expect to have to do some manual work - that is to say, any example I could provide would likely be extremely contrived.  In particular, there are known problems with the exported output emitting variable names the are not legal or not unique.  Some of these are perhaps fixable, but again there are always losses in the compilation process that make a perfect decompilation unlikely.

**Comment by ThorvaldAagaard** [comment]
I agree, that when exporting the decompiled code, we might have to make some manual changes before being able to compile the application, but it would be nice with some hints about what is needed to be changed.

So here is an example, where I did as suggested by Dave

```choose File->ExportProgram from the CodeBrowser tool and select "Format: C/C++",```

This generated a .h-file and a .c

My target is running this as a command-line application in windows

Now when I look at the generated code, the first problem I hit was

![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/3f8f55b1-d160-449d-ab39-a00ac033e451)

So I need a definition for pointer32 

ImageBaseOffset32 is defined in winnt.h as a DWORD, so I add 
```typedef dword pointer32;```

Going thru the genered .h file the next thing I noticed was 

![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/aaafb653-fe67-4e2b-9db3-d65b07cea54c)

So a long list of repeated definitions, where you could expect Ghidra to reuse the definition, but we will leave that for now as it will not be a problem for the compiler :-)

So the next definition with a problem is
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/e8191276-bd1e-4e16-82c0-2d37f8eea9ce)

Now I am not sure what a float10 is, but I can see it is casted to a float some places in the code, so I will add
```#define float10 float```

So next problem is
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/cd3770b1-7f6f-42f2-8b0c-fd5b91143974)

So I added 
```typedef int bool;```
but noticed 
```typedef int BOOL;```
So I could probably also just replace bool with BOOL (Or perhaps Ghidra should do that)

The last problem with typedefinitions was 
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/3eacfb17-a3fc-4e39-a507-534d4c8868fa)

__ftol2 is a part of the windows platform an returns a long, so I added
```typedef unsigned long long ulonglong;```
but also noticed, that Ghidra had added
```typedef unsigned long long undefined8;```

so it would probably be nice refactoring to replace undefined8 with ulonglong.

Now that was the simple ones, as we are getting to the calling conventions
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/dfaa3e68-8ada-483d-9e60-9b2a9f18c70e)

__thiscall i as c++ calling convention and according to https://learn.microsoft.com/en-us/cpp/cpp/thiscall?view=msvc-170 it doesn't have a C name decoration scheme. So Ghidra should probably not generated this for c-code.

Should I also remove all __fastcalls too? - well until the compiler complains I will leave it.

I will just remove these.

Now it is getting more tricky as the next problem is
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/678bbfb3-39bc-4e2f-a66d-16218e13c2f1)

Here Ghidra have failed to define the return type undefined5, and looking at the generated definitions it is not clear what is missing
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/f3e4d60f-d9fd-478c-be8b-4135da3716ef)

But looking at the generated code for the function it returns 
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/636ce3f8-f25b-477c-8319-e801e7f68d2f)

a function not defined in the generated source.

Well then we look at where the function is called, and the result is typecasted to float10, so for now I defined the return type as float10, but still wonders what will happen, when CONCAT14 is called.

Now the next one is very tricky as it is a call to a function passing a function
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/97bbd4db-568f-4a79-b63d-54e028c358ef)

I will assume it is a pointer to the function so I add
#define _PtFuncCompare pointer32

Now we are almost done

![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/d2ee7cd0-a081-4a94-991b-643ef45382db)

Ok, this is c++ code, and I would like to keep it as pure c. I have 11 of these and it seems all are calling functions in the windows system, so I replace "__cdecl FID_conflict:" with "" for all the calls.

Now this looks like some generator problem
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/c1828d21-1187-4df0-8bc9-bf3863d2aaa9)
as the implementation is 

![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/9f055657-9acc-4c33-93c9-2294c0a2573c)

So in the comments the @-sign is mentioned.

I replace the @ with _
After fixing another call to a function with a function as parameter, the .h-file finally compiled without any problems.

Now this was just a small step for compiling the program as I have about 250 compilation-errors when compiling the c-file. 
The considerations for that part will come in my next post

**Comment by ThorvaldAagaard** [comment]
Ok, now we have to compile the application, but to me it seems like the generated source is missing some definition

I have this code
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/f77be52e-b6d1-4bea-8c52-8657c5477b56)
and it is generated fine in the source-file

![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/e18b2890-06ea-419e-a031-2e64f97b3f5b)

But I get compilation errors as there is no definition of some variables that looks like global variables
  DAT_00664814;
  _DAT_00a7e8f0;
DAT_0066a0cc;

So looking at the listing in CodeBrowser I can see the following
![image](https://github.com/NationalSecurityAgency/ghidra/assets/10560652/efb67267-6008-410e-a7f6-7d792b480da6)

But it is nowhere in the generated code.

Hmmm, perhaps I should create my own list of global variables, but I would have expected Ghidra to handle this.

**Comment by GidyMane** [comment]
You need to understand the code generated in the .c file and the .h. After this, make the necessary changes and your app should run.

**Comment by Vadru93** [comment]
Ghidra is not a tool for just copy pasting, it's a tool to help you understand how a program works faster and easier. But if you want to decompile a big program it will still take quite some time and it's simply not possible to make it copy pastable unless debug info is in the exe.

Undefined1,2,3.. etc just means that ghidra see the program reads xxx bytes from memory. Same with float10 it's probably an array of floats, or it could be a class with floats and ints, ghidra just guesses that it is an array of floats.

DAT_XXXX just means that program reads from that address, for example 
`
int example;
int exampl2 = example;
`
This in ghidra would look like
`
DAT_XXXXX = DAT_XXXXX
`

The qsort function is a standard C library function, if you look inside <stdlib.h> you will see what _PtFuncCompare is
