### ISSUE TITLE
Bad Base Address for high Base Addresses in PE header

### ISSUE THREAD

**Issue by yair-c** [NationalSecurityAgency/ghidra#2361]
**Describe the bug**
When PE image with high Base Address loaded the image rebased to 0x10000.
It's happens when the Base Address lower than 0 as signed int.
In EFI PE images high Base Addresses (> 0xff000000) are very common and this is a bad behavior.
[This is the bad condition](https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/OptionalHeaderImpl.java#L552) (It's should be removed)

**Expected behavior**
Load the image to the embedded PE Header Base Address, and not to 0x10000.

**Comment by astrelsky** [comment]
You can change the image base in options when selecting the loader during import.

**Comment by yair-c** [comment]
Of course, but the current default behavior of *ignoring* high Base Addresses doesn't make sense.

**Comment by ryanmkurtz** [comment]
I believe you can only change the image base of ELF files at load time.

**Comment by yair-c** [comment]
Thanks you all about the solution. It's not about how to fix the bug manually by the end user in load time. This is a bug in the source code, it's ignore the Base Address embedded in the binary and force the user set it manually without any good reason.
