### ISSUE TITLE
Ghidra Analyse linux kernel ko module DOS.

### ISSUE THREAD

**Issue by hac425xxx** [NationalSecurityAgency/ghidra#2370]
open and analyse the ko file, ghidra could dos

[note.zip](https://github.com/NationalSecurityAgency/ghidra/files/5385145/note.zip)

**Comment by hac425xxx** [comment]
bug version: 7357b755f4ac658ac3e630d301160f16070ff842

**Comment by astrelsky** [comment]
I'm assuming you intended to report the deadlock encountered in the DWARF Analyzer? If so I suggest changing the title to something along the lines of "Deadlock during DWARF Analysis".

It appears that both the analyzer background thread and the AWT event thread are being blocked. The DWARFAnalyzer is stopped in `DWARFDataTypeManager.doGetDataType` in the do nothing `SystemUtilities.runSwingNow` while the swing thread is currently blocked awaiting access to the lock for the DBHandle.

**Comment by dragonmacher** [comment]
For those writing analyzers, background commands, etc, you should not call in `invokeAndWait()` on the Swing thread if you hold the program DB lock.   Generally, you should avoid holding locks while calling an `invokeAndWait()` operation (which is what `Swing.runNow()` and `SystemUtilities.runSwingNow()` both call).

**Comment by astrelsky** [comment]
> For those writing analyzers, background commands, etc, you should not call in `invokeAndWait()` on the Swing thread if you hold the program DB lock.   Generally, you should avoid holding locks while calling an `invokeAndWait()` operation (which is what `Swing.runNow()` and `SystemUtilities.runSwingNow()` both call).

Iirc locks/synchronization should be limited to the critical section. What isn't clear here is where the analyzer is obtaining the lock prior to the lock and wait.

**Comment by dev747368** [comment]
turns out the lock was being lost somewhere else due to a bad try-catch-finally.  its being fixed.

**Comment by ghidra1** [comment]
I believe the related issues have been corrected and merged for 9.2 and into master
