### ISSUE TITLE
NullPointerException at docking.widgets.pathmanager.PathManager.isValidPath(PathManager.java:539)

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2372]
**Describe the bug**
In the Script Manager's Script Directories window, if I click on the Path field for any entry, I get at NPE.

This leaves me unable to reorder the list or to remove items from it. (I do know about the check box for enabling or disabling individual path entries.)

This may be MacOS specific, and if so, perhaps it's related to a problem that seemed MacOS-related, which @ryanmkurtz looked into with me some months back--but I don't recall whether we created a ticket.
> Uncaught Exception! 
> java.lang.NullPointerException
> 	at docking.widgets.pathmanager.PathManager.isValidPath(PathManager.java:539)
> 	at docking.widgets.pathmanager.PathManager$1.getTableCellRendererComponent(PathManager.java:248)
> 	at docking.widgets.table.GTableCellRenderer.getTableCellRendererComponent(GTableCellRenderer.java:114)
> 	at java.desktop/javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7154)
> 	at java.desktop/javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7541)
> 	at java.desktop/javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:7056)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:497)
> 	at java.desktop/javax.swing.JTable.changeSelectionModel(JTable.java:2378)
> 	at java.desktop/javax.swing.JTable.changeSelection(JTable.java:2447)
> 	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1134)
> 	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1057)
> 	at java.desktop/javax.swing.plaf.basic.BasicTableUI$MouseInputHandler.mousePressed(BasicTableUI.java:816)
> 	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
> 	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
> 	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
> 	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
> 	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
> 	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
> 	at java.desktop/java.awt.Component.show(Component.java:1716)
> 	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
> 	at java.desktop/java.awt.Window.setVisible(Window.java:1021)
> 	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
> 	at docking.DockingDialog.setVisible(DockingDialog.java:341)
> 	at docking.DockingWindowManager.lambda$7(DockingWindowManager.java:1727)
> 	at ghidra.util.Swing.doRun(Swing.java:292)
> 	at ghidra.util.Swing.runNow(Swing.java:208)
> 	at ghidra.util.Swing.runNow(Swing.java:163)
> 	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1731)
> 	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1763)
> 	at ghidra.app.plugin.core.script.PickPathsDialog.show(PickPathsDialog.java:59)
> 	at ghidra.app.plugin.core.script.GhidraScriptComponentProvider.pickPaths(GhidraScriptComponentProvider.java:137)
> 	at ghidra.app.plugin.core.script.GhidraScriptActionManager$9.actionPerformed(GhidraScriptActionManager.java:356)
> 	at docking.menu.ToolBarItemManager.lambda$0(ToolBarItemManager.java:128)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> 
> ---------------------------------------------------
> Build Date: 2020-Oct-15
> Ghidra Version: 9.2
> Java Home: /Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home
> JVM Version: Oracle Corporation 12.0.1
> OS: Mac OS X 10.13.6 x86_64
> Workstation: supermac
> 

**To Reproduce**
Be on a Mac. 😁 (I don't have Ghidra Dev installed on my Windows VM or laptop so I couldn't try it there.)

Open any Ghidra project, then launch the Ghidra tool. You don't need to open any program, and it doesn't matter which project you use. 

Open the Script Manager, then open its Script Directories window.

In the Path column, click on any entry.

Boom.💣

**Expected behavior**
There should be no error (of course), and the Path that I clicked should be selected.

**Screenshots**
[GhidraCapture.mp4.zip](https://github.com/NationalSecurityAgency/ghidra/files/5386687/GhidraCapture.mp4.zip)

**Attachments**
[application.log](https://github.com/NationalSecurityAgency/ghidra/files/5386730/application.log)

**Environment (please complete the following information):**
 - OS: MacOS 10.13.6
 - Java Version: Oracle Corporation 12.0.1
 - Ghidra Version: 9.2

**Comment by jpleasu** [comment]
what version are you on?  I see a `PickPathsDialog` in your stack trace, and that was renamed [a while back](https://github.com/NationalSecurityAgency/ghidra/commit/931a9e823008c70fa250398a49829c7118abcdf0#diff-f1c08476993cb3db34673b965651040a39815edaa64615520b25be29d85b4501).

**Comment by gtackett** [comment]
That commit is from July 28, and I'm pretty certain my build was done before that. (I'm at work and can't check on it right now.) I'll try to update my local copy with git, but I may be missing something. I tried that a week or so ago and git told me that my copy was up to date.

**Comment by jpleasu** [comment]
maybe you are on a branch?

**Comment by gtackett** [comment]
It appears I am using master:
> $ git status
Refresh index: 100% (13266/13266), done.
On branch master
Your branch is up to date with 'origin/master'.
.
.
.

**Comment by jpleasu** [comment]
how do you start Ghidra? to uses the latest, you need to either `gradle buildGhidra` and use the generated distribution, or run from the `ghildra.launch` run configuration in eclipse (see https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md ) .

Maybe you're using the GhidraDevPlugin run configuration?  To run the latest, you want the one **without** the icon in eclipse:
![image](https://user-images.githubusercontent.com/1778531/96610792-061a1b00-12ca-11eb-8252-77e57137c049.png)

**Comment by jpleasu** [comment]
and just to make sure, there was a `git pull` before that `git status`, right?

**Comment by gtackett** [comment]
I built Ghidra with a lot of help from @ryanmkurtz. (If I had to build it again starting from scratch--with none of the prerequisites, etc., I'd probably need some help again.) I recall using gradle and eclipse. I run Ghidra from within eclipse. I'll have to check when I get back home to make sure I'm running the latest. (At work, githubusercontent is blocked so I can't see the icon image.)

And I didn't do a `git pull`, so I'll have to try doing that and then try `git status` again.

**Comment by gtackett** [comment]
I had to stash two uncommitted changes I was given by one of the developers. Then after doing a `git pull` I watched for the automatic build to finish, but I didn't see any activity at all in the Eclipse console window, though. Doing a Build All didn't produce any, either. So I'm looking in to that at the moment.

**Comment by gtackett** [comment]
When I launched the rebuilt Ghidra, it didn't load the script manager plugin because there was a build problem with that plugin.

I'm way out of my depth here. If someone more knowledgeable could take a look at the log file, maybe they can tell what's wrong.
[application.log](https://github.com/NationalSecurityAgency/ghidra/files/5418689/application.log)

**Comment by dragonmacher** [comment]
Based on the log file it seems as though you are missing the new jar file dependencies that the Ghidra script plugin now requires.   I am not sure of your exact setup, but the suggestions below assume your setup is similar to the standard development setup.  

I'll take a stab at helping you.

Close Eclipse.

To get all of the required jar files, you will need to run a gradle command from with the `ghidra` repo (these instructions are taken from https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md):
`gradle --init-script gradle/support/fetchDependencies.gradle init`

This should download all required jar files for you to run. 

To make sure you Eclipse projects are up-to-date, you should also run:
`gradle prepDev cleanEclipse eclipse`

Relaunch Eclipse and import any new projects:

- `File -> Import -> Existing Projects Into Workspace`
- Pick the `ghidra` repo root directory
- Check the box 'Search for nested projects'
- In the list that appears, you should see all projects, with any new projects already checked.
- Press 'Finish'

At this point, if all has gone well, you should:

1. Have the new jar files
2. Have all new/updated Eclipse projects
3. Have Eclipse fully built with no errors
4. Be able to run  Ghidra 


Good luck!

**Comment by gtackett** [comment]
My problem is resolved, thanks to @dragonmacher and everyone who chimed in!
