### ISSUE TITLE
When will ghidra release next version?

### ISSUE THREAD

**Issue by spotthediff** [NationalSecurityAgency/ghidra#2381]
ghidra does not release something release that bugfix or new feature update since february.
All issues has closed in milestone issues.

When will you do next update?(9.1.3?)

I am looking forward to use new feature including ghidra!😀

**Comment by mumbel** [comment]
when its ready

**Comment by dragonmacher** [comment]
Just between us, rumor has it that the next version of Ghidra is almost done baking, but is not yet cool enough to put on the icing.  (Dragon Cakes :dragon: :cake:)

The Ghidra team is busy finalizing the details for the 9.x release.  Much thanks to the community for contributions and feedback.  The help has made this one of the easiest releases yet.

**Comment by gtackett** [comment]
It must take a while for a cake to cool down once @dragonmacher has directed his flames toward the next cake coming down the flameproof conveyor belt.

**Comment by dragonmacher** [comment]
> It must take a while for a cake to cool down once @dragonmacher has directed his flames toward the next cake coming down the flameproof conveyor belt.

It turns out that we dropped that cake on the floor.  But, we have a backup cake that we are now icing.

**Comment by MPINTERNATIONAL** [comment]
When can I help? GHIDRA and my QCBR5500e!
