### ISSUE TITLE
Install on Windows10

### ISSUE THREAD

**Issue by Bowenduan** [NationalSecurityAgency/ghidra#2382]
I downloaded ghidra-Ghidra_9.1.2_build.zip and JKD 11.0.8.
![image](https://user-images.githubusercontent.com/33278320/96548052-c65e2e00-12df-11eb-8567-3b55b9f75ddc.png)

When I run ghidraRun.bat, it shows following errors.

`Error: java.lang.ClassNotFoundException: LaunchSupport`
`Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section.`

I also tried Ghidra 9.1 and Ghidra 9.0.4 and they all led to the same results.

**Comment by ryanmkurtz** [comment]
Where are you downloading them from? The name of your zip file looks "unofficial."

**Comment by Bowenduan** [comment]
I download from [Releases](https://github.com/NationalSecurityAgency/ghidra/releases).

**Comment by ryanmkurtz** [comment]
Try downloading them from ghidra-sre.org

**Comment by Bowenduan** [comment]
When I visit ghidra-sre.org, it shows:
`403 ERROR`
`Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.`

I think maybe ghidra-sre.org is not accessible in my area. Is there another place I can download from?

**Comment by ryanmkurtz** [comment]
It looks like what you were downloading from the Releases page were just the zipped up git repositories where release tags were made, so it makes sense why that would not run...it has to be built.

I know there are mirrors out there, and people putting up nightly builds.  @astrelsky, do you know of a link?

**Comment by astrelsky** [comment]
There are a few cli builds of 9.2_dev floating around on github. Be careful of what you use though as some contain unmerged pull requests. 

I don't know of any 9.1.2 mirrors. I'm assuming you are encountering the error on the official site due to being outside the us. I'm sure there are ways around it but I won't say how.

**Comment by xiaoyinl** [comment]
I suggest you to compile `master` locally, or use GitHub Actions to compile it and then download the artifacts (#1315 and #2142 are good examples about how to write GitHub Actions workflow files).

**Comment by jack1-software** [comment]
I download from ghidra-sre.org. Then, use 7zip do unzip.
fold:  ghidra_9.1.2_PUBLIC_20200212 
double click on ghidraRun.bat  file to run, error message
"Java runtime not found."

jdk 11 seem  be installed, ok.
C:\Program Files\Java\jdk-11\bin>java --version
java 11.0.9 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

I set system variable:
JAVA_HOME      C:\Program Files\Java\jdk-11\bin

I set user variable:
Path     C:\Program Files\Java\jdk-11\bin

But, it still gave out error, fail to start.  
How to do fix this issue?
Do you set path:  C: Jdk11\bin  ?

What path is used in ghidra?

**Comment by Wall-AF** [comment]
I think you should remove the `\bin` from `JAVA_HOME` like
```
JAVA_HOME=C:\Program Files\Java\jdk-11.0.2
```

Also, check `where java` to ensure its picking the correct one.

**Comment by mikemadden42** [comment]
I agree.  I believe having `bin` in `JAVA_HOME` is the issue.

I have mine set to the following and ghidra works.

```
PS C:\Users\hulk> echo $env:JAVA_HOME
C:\Program Files\OpenJDK\openjdk-11.0.8_10
```

**Comment by mikemadden42** [comment]
By the way, if you are a user of `choco`, there is a package available to ghidra.

https://chocolatey.org/packages/ghidra/

For me it was as easy as `choco install ghidra` which installed `openjdk11` and then ghidra.

**Comment by jack1-software** [comment]
Thank you for help.
I powered off PC to eat something. Then, back to power on.
It work now. 
Ghidra look pretty. I need time to try it from now.

**Comment by jack1-software** [comment]
Thank you, Michael,

I will try Choco.  
I like learning choco.

Jack
Melbourne


Sent from Mail for Windows 10

**Comment by mikemadden42** [comment]
@jack1-software , I'm glad you got it working.  Best of luck learning `choco`  and `ghidra`!
