### ISSUE TITLE
Add bytes?

### ISSUE THREAD

**Issue by aFakeCmd** [NationalSecurityAgency/ghidra#2384]
Why does the file add 3072 bytes after exporting the file unchanged?

**Comment by ryanmkurtz** [comment]
What importer did you use?  Binary?

**Comment by aFakeCmd** [comment]
> 

yes

**Comment by ryanmkurtz** [comment]
Do you end up with just one memory block in Ghidra?  Does the size of the memory block match the file size?  If you have more than one memory block, does the sum of all their sizes match the file size?  I think the Binary Exporter is simply writing the memory block contents to a new file.

**Comment by aFakeCmd** [comment]
> What importer did you use? Binary?



> Do you end up with just one memory block in Ghidra? Does the size of the memory block match the file size? If you have more than one memory block, does the sum of all their sizes match the file size? I think the Binary Exporter is simply writing the memory block contents to a new file.

Yes, the memory block size matches the file size. Is it possible to get rid of the Binary Exporter writing the contents of the memory block?

**Comment by ryanmkurtz** [comment]
The sole purpose of the Binary Exporter is to write the memory blocks to a file.
