### ISSUE TITLE
Equates not propagating to Decomple View

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#2386]
**Describe the bug**
Updating constants to an EQUATE in Listing View dosn't show in some decompiled statments (like `if (x == ?)`).

**To Reproduce**
1. Check your Decompile View for a statment like `if (x == 1)`
2. Go to the Listing View and update the constant "1" to any appropriate EQUATE constant
2. Look back at the Decompile View
3. See error

**Expected behavior**
Number replaced with EQUATE constant

**Example**
Listing View
 ```
  1018:0d9b 83 3e 7c        CMP        word ptr [WAVEOUTCAPS_1030_7f7c],MM_MICROSOFT    = 
                 7f 01
       1018:0da0 75 15           JNZ        LAB_1018_0db7
       1018:0da2 83 3e 7e        CMP        word ptr [WAVEOUTCAPS_1030_7f7c.wPid],MM_MSFT_   = null
                 7f 0f
       1018:0da7 74 07           JZ         LAB_1018_0db0
       1018:0da9 83 3e 7e        CMP        word ptr [WAVEOUTCAPS_1030_7f7c.wPid],MM_MSFT_   = null
```

Decompile View
```
          if ((WAVEOUTCAPS_1030_7f7c.wMid == 1) &&
             ((WAVEOUTCAPS_1030_7f7c.wPid == 0xf || (WAVEOUTCAPS_1030_7f7c.wPid == 0x13)))) {
```

**Comment by ghidra1** [comment]
Issue has been address for Ghidra 9.2 and has been merged into master
