### ISSUE TITLE
Misdocumentation in pcode reference description of LOAD

### ISSUE THREAD

**Issue by drew-yao** [NationalSecurityAgency/ghidra#2390]
In GhidraDocs/languages/html/pcodedescription.html

"""
The “pointer” comes in two pieces. One piece, input1, is a normal variable containing the offset of the object being pointed at. The other piece, input1, is a constant indicating the space into which the offset applies. 
"""
It doesn't make sense that the two pieces should both be input1.  I think 'The other piece' is supposed to be input0.

**Comment by caheckman** [comment]
This is fixed in 9.2
