### ISSUE TITLE
Ghidra1's fixes for ConstantPropagationAnalyzer and PseudoDisassembler

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2391]
@Ghidra1 provided @ryanmkurtz and me with two fixes, one for each of ConstantPropagationAnalyzer and PseudoDisassembler, that have not yet been committed here on github. Could he please commit them? Thanks, @Ghidra1, for helping so much with those and other issues.
:smile:

(I don't think there were any github issues created for those problems.)

**Comment by astrelsky** [comment]
Speaking of ConstantPropagationAnalyzer's there is this also. https://github.com/NationalSecurityAgency/ghidra/pull/2157

**Comment by ghidra1** [comment]
Although things were a bit disorganized at the time I believe I incorporated all of the relevant changes into Ghidra for release with Ghidra 9.2 which should also be in master.  Sorry to trouble you but could you please report any outstanding bugs/issues into this ticket that you believe should have been resolved.  I checked my repository where I was working at the time and all changes I had made at the time appear to be present in the GitHib repo.

See [commit](https://github.com/NationalSecurityAgency/ghidra/commit/7906d65aa24d658c8c11b30d6d63d63eac906e2b#diff-1ddd58e758dc471475380b70ccd4f84d18238dc1d08f9c1da5b3031bd3cc99a6)

**Comment by ghidra1** [comment]
> Speaking of ConstantPropagationAnalyzer's there is this also. #2157

I passed this other issue onto @emteere

**Comment by gtackett** [comment]
It does look like the commit resolves the problems that I asked about in this issue, so I'm closing this.
