### ISSUE TITLE
TypeDef struct pointer type doesn't decay

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2393]
**Describe the bug**
This is most likely worded incorrectly but I don't know how else to describe it. If a typedef is a pointer to a struct, when compared with the address of an instance of said struct, an unnecessary cast is produced.  Consider the following:

```c
#include <stdbool.h>
struct dummy {
};

typedef struct dummy *dummy_t;

struct dummy gMyDummy;

bool isMyDummy(dummy_t d) {
	return d == &gMyDummy;
}
```

This results in:
<details><summary>screenshot</summary>

![Capture](https://user-images.githubusercontent.com/46897303/96925475-399fa580-1482-11eb-8029-f0bae7b578c7.PNG)
</details>

**Expected behavior**
There should be no typecast as the address of the struct instance is a `dummy_t`

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.572]
 - Java Version: 15
 - Ghidra Version: 9.2_DEV 3c683ae770cf495deb32588202b00b88e125a4a4

**Comment by dev747368** [comment]
+1 for the mspaint!

**Comment by ryanmkurtz** [comment]
It makes me suspect that the image has been doctored.

**Comment by astrelsky** [comment]
> It makes me suspect that the image has been doctored.



> It makes me suspect that the image has been doctored.

As you can see it is an entirely authentic screenshot.

**Comment by astrelsky** [comment]
How do you determine if a `DataType` is a typedef? There doesn't seem to be a `type_metatype` entry for a typedef.

**Comment by RazielZnot** [comment]
I had the same issue recently.

**Comment by astrelsky** [comment]
The root of the problem is that the decompiler actually does **not** have typedef support. It currently just slaps a different name on the type for every typedef. The problem occurs because an entire copy of a struct is created with a different name but `struct A{}; != struct B{};`.

**Comment by astrelsky** [comment]
@ryanmkurtz still doesn't work properly. An example from what I'm seeing is as follows:

```c++
_SYSTEMTIME time;
GetLocalTime(&time);
```

However the decompiler still produces this:
```c++
_SYSTEMTIME time;
GetLocalTime((LPSYSTEMTIME)&time);
```

**Comment by ryanmkurtz** [comment]
Ok hopefully @caheckman can weigh in.

**Comment by caheckman** [comment]
Could you post a "Debug Function Compilation" XML dump of the function?

**Comment by astrelsky** [comment]
> Could you post a "Debug Function Decompilation" XML dump of the function?
[typdef_decay.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/7219282/typdef_decay.xml.txt)

**Comment by astrelsky** [comment]
Oh probably important to note that the version of ghidra I dumped that on doesn't contain 8aed810. I put together a sample real quick on my local computer since I can't share work stuff.

**Comment by caheckman** [comment]
Thanks.  I'm reproducing now.  Working on a patch.

**Comment by astrelsky** [comment]
> Thanks. I'm reproducing now. Working on a patch.

Great thank you.
