### ISSUE TITLE
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the loader property is specified

### ISSUE THREAD

**Issue by tommai78101** [NationalSecurityAgency/ghidra#2400]
Hello, this is a question.

I'm getting a warning message that's displayed at the top of the console window upon Ghidra startup, given as follows:

```
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "ghidra.GhidraClassLoader"). To use archived non-system classes, this property must not be set
```

May I ask what this message is hinting, what do I need to do to make it no longer print this message each time I launch Ghidra?

Java version: OpenJDK 12.0.1
OS: Windows Pro x64
Ghidra:   9.1.2_PUBLIC

**Comment by ryanmkurtz** [comment]
There's a jvm argument that can go in support/launch.properties to suppress this message. I can't remember it off the top of my head, but it's googleable. I'll make a PR on Monday to make it go away.

**Comment by tommai78101** [comment]
Thank you.

All I know is this message was added to the commit in OpenJDK:

http://hg.openjdk.java.net/jdk/jdk/rev/840e26123940#l7.39
