### ISSUE TITLE
ElfSectionHeaderType value out of range

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2401]
I am attempting to create an `ElfSectionHeaderType` for the `.mwcats` elf sections. The value for this type is `0xca2a82c2` which is "larger" than `Integer.MAX_VALUE`.

```
public static final ElfSectionHeaderType SHT_MW_CATS = new ElfSectionHeaderType(
		0xca2a82c2, "SHT_MW_CATS", "Unknown Section from Metrowerks CATS Utility");
```

**Comment by ghidra1** [comment]
Restriction removed for 9.2.3 release
