### ISSUE TITLE
Merge Version Tracking Session is slow

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2402]
I had added a bunch of correlators to a version tracking session have it had been several hours now. It is adding 659084 match objects which doesn't seem to be too much. I've already gone ahead an profiled this.

This seems to be a problem. There should be a means of directly obtaining the correct VTAssociationDB with the correct destination address directly without iterating over all of them.
https://github.com/NationalSecurityAgency/ghidra/blob/3c683ae770cf495deb32588202b00b88e125a4a4/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/db/AssociationDatabaseManager.java#L336-L343

Edit: It would help if I remembered to attach the results.
[Live-call-tree.html.txt](https://github.com/NationalSecurityAgency/ghidra/files/5436450/Live-call-tree.html.txt)

**Comment by dragonmacher** [comment]
This is likely a case where the normal behavior does not show the performance problem.  The snippet above should only bog down when the source address has many associations, where many probably means hundreds to thousands.   This could certainly be converted to a lookup instead of an iteration, but would likely require a database change.

**Comment by astrelsky** [comment]
> This is likely a case where the normal behavior does not show the performance problem. The snippet above should only bog down when the source address has many associations, where many probably means hundreds to thousands. This could certainly be converted to a lookup instead of an iteration, but would likely require a database change.

I am working on a simple implementation which doesn't require one. Testing it now.

**Comment by astrelsky** [comment]
So it seems that `Table.findRecords` is just iterating over all the keys in the table column and checking if they match. I'm having a serious case of déjà vu here. As it stands improvements can be made without altering the database but this is definitely the limiting factor.

**Comment by dragonmacher** [comment]
I haven't looked at it, but this is fairly common with Ghidra, and databases in general.   Our initial db designs often miss use cases we did not foresee.  We will change tables when needed, although adding tables is much easier.

**Comment by astrelsky** [comment]
> I haven't looked at it, but this is fairly common with Ghidra, and databases in general. Our initial db designs often miss use cases we did not foresee. We will change tables when needed, although adding tables is much easier.

Is this supposed to return a set of records that contain either the source or destination address or a set of records that contains both the source and destination address?
https://github.com/NationalSecurityAgency/ghidra/blob/3c683ae770cf495deb32588202b00b88e125a4a4/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/db/VTAssociationTableDBAdapterV0.java#L96-L112

**Comment by dragonmacher** [comment]
It is *either*.  The name is certainly unclear.  I found docs for this higher-up in the client chain on the `VTAssociationManager` 

	/**
	 * Returns a collection of all defined associations that have the either the given source
	 * address or the given destination address
	 * @param sourceAddress the source address to use to search for associations.
	 * @param destinaitionAddress the source address to use to search for associations.
	 * @return a collection of all defined associations that have either the given source
	 * address or the given destination address.
	 */

**Comment by astrelsky** [comment]
> It is _either_. The name is certainly unclear. I found docs for this higher-up in the client chain on the `VTAssociationManager`
> 

I'll create an additional method for both then as it enables a few opportunities for some short circuiting.

**Comment by dragonmacher** [comment]
This should be fixed by e55550ed
