### ISSUE TITLE
Exception while decompiling X: process: timeout

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2406]
**Describe the bug**
Decompiler process always results in a "timeout".

**To Reproduce**
1. Decompile any function

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.572]
 - Java Version: 15
 - Ghidra Version: 9.2_DEV b605ad03274edaa20c83107d30f681850848ff84 (kinda)

**Additional context**
As soon as I step over this line the DecompileProcess nativeIn stream gets closed.
https://github.com/NationalSecurityAgency/ghidra/blob/b605ad03274edaa20c83107d30f681850848ff84/Ghidra/Features/Decompiler/src/main/java/ghidra/app/decompiler/DecompileProcess.java#L532

Even though I have commits locally that may effect this, I didn't have a problem until jumping from 3c683ae770cf495deb32588202b00b88e125a4a4

**Comment by mumbel** [comment]
seeing this as well (tried both eclipse and building a zip) on linux/11.0.8

**Comment by tjschweizer** [comment]
I am getting the same error, Windows 10.0.19041, clean build b605ad0 of Ghidra. I think it is related to dc7e457 - specifically Ghidra/Framework/Generic/src/main/java/ghidra/util/timer/GTimer.java changed from 
`if (delay <= 0) {`
to
`if (delay < 0 ){`
on lines 43 and 65.

I don't have a dev environment set up yet so I can't check for sure, but that's my hunch.

**Comment by astrelsky** [comment]
> I am getting the same error, Windows 10.0.19041, clean build [b605ad0](https://github.com/NationalSecurityAgency/ghidra/commit/b605ad03274edaa20c83107d30f681850848ff84) of Ghidra. I think it is related to [dc7e457](https://github.com/NationalSecurityAgency/ghidra/commit/dc7e45762d34560396e681f11e925db769c05cae) - specifically Ghidra/Framework/Generic/src/main/java/ghidra/util/timer/GTimer.java changed from
> `if (delay <= 0) {`
> to
> `if (delay < 0 ){`
> on lines 43 and 65.
> 
> I don't have a dev environment set up yet so I can't check for sure, but that's my hunch.

Ah yes. `0 * x = 0;` `ghidra.app.decompiler.component.Decompiler` is initialized with no timeout.

Here is the culprit:
https://github.com/NationalSecurityAgency/ghidra/blob/b605ad03274edaa20c83107d30f681850848ff84/Ghidra/Features/Decompiler/src/main/java/ghidra/app/decompiler/component/DecompilerManager.java#L50-L57

**Comment by pabx06** [comment]
looked at the source and a timeout zero sounds legitimate use for not timeout for user to cancel a task.
and timeout value look to be used a delay value for launching Timer task.
same error here
so i Tried to debug and found :
https://github.com/NationalSecurityAgency/ghidra/blob/b605ad03274edaa20c83107d30f681850848ff84/Ghidra/Features/Decompiler/src/main/java/ghidra/app/decompiler/DecompileProcess.java#L152

is throwing ` java.io.IOException: Stream closed`

![image](https://user-images.githubusercontent.com/4013370/97309713-ab9d3380-1862-11eb-95c9-fed7f8cafc11.png)

if it is a timeout issue i would expect the GTimer$GTimerTask.wasCancelled == true


https://github.com/NationalSecurityAgency/ghidra/blob/b605ad03274edaa20c83107d30f681850848ff84/Ghidra/Features/Decompiler/src/main/java/ghidra/app/decompiler/DecompileProcess.java#L532 
first args is (timeoutSecs * 1000) one would expect a timeout value of 0 sec multiplied by 1000 == 0  but it is a delay:

https://github.com/NationalSecurityAgency/ghidra/blob/b605ad03274edaa20c83107d30f681850848ff84/Ghidra/Framework/Generic/src/main/java/ghidra/util/timer/GTimer.java#L42

**Comment by dragonmacher** [comment]
This is a regression.  We will soon have a fix.
