### ISSUE TITLE
Patched binary loose information.

### ISSUE THREAD

**Issue by BoomProgrammer** [NationalSecurityAgency/ghidra#241]
**Description**
As i said in the title, when i try to patch out a binary file, even with just a changed value, the file gets smaller and unusable.
I found a video on YouTube wich shows the problem, here: https://www.youtube.com/watch?v=5xdaLy9gtIY&t=565s

**Environment**
 - OS: [Windows 10]
 - Java Version: [11.0]
 - Ghidra Version: [9.0]

**Comment by Ristovski** [comment]
Duplicate of #19

**Comment by ryanmkurtz** [comment]
Please track #19 for more information on this issue.
