### ISSUE TITLE
Could not find decompiler executable decompile (DecompileProcessFactory)

### ISSUE THREAD

**Issue by marcomafcorp** [NationalSecurityAgency/ghidra#2410]
**Describe the bug**
When using ghidra headless I continue to get the ERROR "Could not find decompiler executable decompile (DecompileProcessFactory)" and get partial analysis of the binary

**To Reproduce**
I'm using this executable (f8bc1638ec3b04412f708233e8586e1d91f18f6715d68cba1a491d4a7f457da0) which loads completely fine in Ghidra Gui but doesn't have the same results when using headless.

**Attachments**
I've attached the application.log
![decompilprocess](https://user-images.githubusercontent.com/4383090/97473380-25d3c380-1908-11eb-85e5-370ff3a163f0.jpg)
[application.log](https://github.com/NationalSecurityAgency/ghidra/files/5453762/application.log)

**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.15.6]
 - Java Version: [e.g. 11.0]
 - Ghidra Version: [e.g. 9.1.2]

**Comment by ryanmkurtz** [comment]
What does the rest of that first line of error say?

**Comment by marcomafcorp** [comment]
020-10-27 13:42:00 ERROR (DecompileProcess) Please report this stack trace to the Ghidra Team java.io.IOException: Cannot run program "/Users/marcof/Documents/DisAss_Tracking/ghidra-headless-decompile/ghidra_9.1.2_PUBLIC/Ghidra/Features/Dec$
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)

**Comment by dev747368** [comment]
that's strange that the decompiler path is truncated.

**Comment by marcomafcorp** [comment]
[IOexception from app.log](https://github.com/NationalSecurityAgency/ghidra/files/5454016/IOexception.from.app.log)

**Comment by ryanmkurtz** [comment]
And this file exists?

`/Users/me/Documents/myproject/myproject2/ghidra_9.1.2_PUBLIC/Ghidra/Features/Decompiler/os/osx64/decompile`

**Comment by dev747368** [comment]
if it doesn't exist, you may need to re-install your Ghidra from the original zip.  If it does exist, maybe the execute permissions got messed up?

**Comment by marcomafcorp** [comment]
thanks ryan and dev I fixed the issue by doing the re-install the execute permissions were messed up :)
