### ISSUE TITLE
Markup DWARF sections 

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2413]
**Is your feature request related to a problem? Please describe.**
DWARF debug sections are not marked up and the data is left undefined.

**Describe the solution you'd like**
Having the data created by the dwarf analyzer would be nice and would help with error checking. 

**Describe alternatives you've considered**
Keep things the way they are.

**Comment by dev747368** [comment]
in addition to the 'level of effort' reason for plain .debug_info, it would be even more effort to handle compressed sections, sections in external files, etc.

**Comment by astrelsky** [comment]
> in addition to the 'level of effort' reason for plain .debug_info, it would be even more effort to handle compressed sections, sections in external files, etc.

You mean you can't add markup to sections in external files that aren't present?

**Comment by dev747368** [comment]
> You mean you can't add markup to sections in external files that aren't present?

I think I'm detecting some sarcasm.... ?  :smile: 

But yeah, external tools like readelf seem more useful in most cases.

**Comment by astrelsky** [comment]
> > You mean you can't add markup to sections in external files that aren't present?
> 
> I think I'm detecting some sarcasm.... ? 😄
> 
> But yeah, external tools like readelf seem more useful in most cases.

Me, sarcastic? No, never.
