### ISSUE TITLE
8048 : cannot manually specify bank (SEL MB1), and minor typo DFB -> DBF

### ISSUE THREAD

**Issue by fenugrec** [NationalSecurityAgency/ghidra#2423]
**Describe the bug**
While working on 8048 code, with patterns such as 
```
       CODE:0690 f5              SEL        MB1
       CODE:0691 d4 0d           CALL       LAB_CODE_060c+1
```
The call destination is incorrect (should be 0x0E0D since MB1 sets bit 11, i.e. adds 0x800); trying to instruct the analyser (right-click, Set register values, DFB = 1) seems to have no effect even after re-analyzing.

Also, in the Intel docs, they call it "DBF - Memory bank flip-flop", and not DFB, so a minor typo here.

**To Reproduce**
1. I'm working on this firmware dump, http://www.ko4bb.com/getsimple/index.php?id=download&file=01_ROM_Images_and_Drivers/HP_3478A_03478-65501_dc118.zip
2. Open only the first 0x1000 bytes (this device uses hardware bank-switching which is a whole other bag of problems)
3. Scroll to 0x0690 as shown above
4. try to set DBF=1

**Expected behavior**
correct `call` destination as explained

**Environment (please complete the following information):**
 - Java Version: 11.0.8
 - Ghidra Version: 9.1 dev 2020/02/20 from arch linux repos

Probably something for @zeldin if he's still around ? I found other 8048 issues I may report too.

**Comment by esaulenka** [comment]
@fenugrec, please test my fix: https://github.com/esaulenka/ghidra/commit/3756e1bcee19225d854aa41658c4ac7e4c5e8a37

How to do it:
- update .slaspec file
- delete .sla file, for Ghidra to recompile it
- check call / jmp instructions

**Comment by fenugrec** [comment]
Thanks for the instructions, and the quick fix ! I was able to regenerate the .sla file (had to run `sleigh -a ...`);
trying on the first call instruction I found, I tried setting DBF=1 but getting the following error:

> Context register change conflicts with one or more instructions

**Comment by fenugrec** [comment]
Sorry, to clarify : if I just re-analyze , the disasm doesn't change, but if I  `Clear code bytes` then Disassemble, that seems to work as expected. But I still can't force the DBF value for a single Call opcode.

**Comment by esaulenka** [comment]
Yes, you are right. But I dont know, how to override context register (now DBF is not regular register) value. We need to wait someone from Ghidra team to help.

I experimented a little: if you clear code first, then you can set DBF value and disassembly same address again. I think its a bug in ghidra.
