### ISSUE TITLE
Getting the object name through the Ghidra Script

### ISSUE THREAD

**Issue by heshananupama** [NationalSecurityAgency/ghidra#2425]
I have a script written to work with ghidra. I am doing some analysis in the script and save the results in a file. Right now, I am passing the name when a prompt ask the file name to save upon running the script. Though this is ok for one, I need to run this script in more than 100 objects at once(using the headless analyzer) and I want the file name to automatically taken from the object name. How could I do this?

For example, let's say I have an object file called "mqtt.o" I need to take this name(mqtt) while saving the file which contains the results. I looked through the API, but still could not find a way to get the name of the object of analysis. Any help is appreciated. Thanks.

**Comment by astrelsky** [comment]
I'm going to make an assumption here that object is the currentProgram. If so you can just use `currentProgram.getName()`. This should hold true for any `DomainObject`.

**Comment by heshananupama** [comment]
I dont know how I missed this. Thanks!

**Comment by astrelsky** [comment]
> I dont know how I missed this. Thank you very much!

You're welcome.
