### ISSUE TITLE
x87: missing code for fbld

### ISSUE THREAD

**Issue by rfalke** [NationalSecurityAgency/ghidra#2427]
**Describe the bug**
I'm pretty sure that the semantic of the fbld instruction is not correctly represented.

**To Reproduce**
1. Decompile https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/i386_x87_fpu/ia32_elf/subject.exe

**Expected behavior**
Output may look like

```
undefined4 FBLD(void)

{
  float10 in_ST1 = __read_bcd(0x804c4fd);
...
```

It currently is:
```
undefined4 FBLD(void)

{
  unkbyte10 in_ST0;
  float10 in_ST1;
  
  readbuffer = (byte)in_ST0;
  _readbuffer = in_ST0;
  printf(
         "FBLD(0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x): should=-123456789088776656.000000/  -1.234568e+17 is=%12f/%15e\n"
         ,(uint)readbuffer,0x66,0x77,0x88,0x90,0x78,0x56,0x34,0x12,0x80,(double)in_ST1,
         (double)in_ST1);
  return 0;
}
```

in_ST0 and in_ST1 is not set. The address where the BCD is (0x804c4fd) is not used in the code.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "11.0.5" 2019-10-15
 - Ghidra Version: 9.1.2_PUBLIC

**Comment by GhidorahRex** [comment]
We're definitely not implementing `fbld` correctly.

As far as `fild` we do support it. According to the manual the opcode should be `db` or `df`. I don't see either represented in the code sample though, unless I'm missing something.

**Comment by GhidorahRex** [comment]
For the `fbld` we would need to update the sleigh file.

Probably replace the constructor with something like:
```
define pcodeop convert_from_bcd;
:FBLD  spec_m80     is vexMode=0 & byte=0xDF; reg_opcode=4 ... & spec_m80
{
    fdec(); ST0 = convert_from_bcd(spec_m80);
}
```

As for the other issue with the interrupt replacing the emulation of the x87 instructions, that's much trickier. You might have a script that would go through and replace the bytes for `cd 3x` with `98 dy` bytes.

**Comment by GhidorahRex** [comment]
I'm confused about the meaning of some of these things.

These:
```
 1000:0585 cd 38           INT        0x38                                           
 1000:0587 16              PUSH       SS
 1000:0588 32 35           XOR        DH,byte ptr [DI]
```

are clearly the original bytes. But `CD38165235     INT       38 ;FCOM     QWORD PTR [3552] ` looks  wrong.  At least I can't encode that FCOM instruction in a way that would make sense for the bytes here. What processor version are you using?

**Comment by GhidorahRex** [comment]
I couldn't see your screenshot but I worked it out. I had been assuming it was 32-bit, but it's 16-bit, in which case the bytes for the `FCOM` instruction do make sense (it also took me a minute to realize that those values were hex, not decimal).

> In this example it's doing a float compare with top value from the FPU stack with a double value stored @ DS:0x3532, but Ghidra's disassembly is missing that data operand completely. Maybe once this is fixed it might help improve the decompilation. Right now I don't see any floating point math in the C code at all looks like this:

It's missing everything. Because the opcodes for the x87 instructions are obfuscated by the `int` instructions, ghidra can't understand that there's any floating point going on.

I haven't come across the x87 emulation before. The choices are writing a script to replace the bytes, updating them manually, or updating all of the x87 `dx` opcodes to support the emulated version of `3x` in the sleigh module. That's a non-trivial change - made even worse because of the special handling needed to use the `int 0x3c` instructions. The wine emulator linked to in the stackexchange post doesn't even try to handle those.

**Comment by GhidorahRex** [comment]
For `CD38165235     INT       38 ;FCOM     QWORD PTR [3552]` clear the bytes and change `CD` to `98` and `38` to `DC`, then click on the `98` byte and press the D key for disassmbly. In general, these instructions will result in an `FWAIT` followed by an FPU instruction.

**Comment by GhidorahRex** [comment]
Sorry, I might require glasses... that should be `0x9b` for the `fwait` instruction.

**Comment by GhidorahRex** [comment]
> Any ideas how I can script this? I assume with python, but have no experience with the API. Also, do you know the byte swapping rules for the FPU instructions?
> 
> Many thanks once again.

The byte swapping rules are laid out in the stackexchange post you mentioned and several of the links. For the barebones basic you can look at the link to the wine fpu code in the accepted answer, but there's also some useful and more detailed information in the links in the comments to the question.

**Comment by GhidorahRex** [comment]
@palmerj You can take a look at `EditBytesScript.java` as far as the commands to replace the bytes and disassemble again. It's just a matter of walking through the binary and finding the `INT` instructions, then replacing the bytes with `9b xx` and disassmbling again.
