### ISSUE TITLE
Advice on packaging/distributing my code

### ISSUE THREAD

**Issue by RolfRolles** [NationalSecurityAgency/ghidra#243]
My [abstract interpretation-based analysis](https://github.com/RolfRolles/GhidraPAL) is basically ready for publication. Mostly it is intended for programmatic use as a library -- something that clients can call from their scripts/code as though it were part of the SDK -- instead of something that a human would invoke manually. I intend to separate all of the classes in my script into their own files, to make the individual components reusable by other developers.

I find myself lost in the sea of options listed in the "Advanced Development" training material. I originally developed it as a "script" to assist rapid development. Which type of project is best suited here? A "script", a "plugin", an "extension", or a "tool"? (Can a "script" even be spread across multiple .java files?) Sorry for my ignorance.

**Comment by mumbel** [comment]
Sounds like you'd want an extension if its going to be a larger multi file project.  I don't know the answer to the chained scripts, but that certainly would be achieved in a jar file within an extension.  There are some nice examples/skeletons it looks like in Extensions/Ghidra  (file-> import extensions  from the main ghidra window).  For example the ghidra_9.0_PUBLIC_20190928_SampleTablePlugin.zip gives a new item in the CodeBrowser Window menu 'Sample Table provider'

**Comment by d-millar** [comment]
Just to expand on mumbel's answer (which is, I believe, on the money), scripts are generally single-function and often ad hoc.  I think you could chain scripts, but that would in essence go beyond the intent of the scripting interface.  Plugins are the base components of everything in the GUI and vary considerably in size, but are intended to be re-composable units out of which larger components are made.  Extensions are a relatively new addition to Ghidra, composed of sets of plugins.  I would say that extensions generally provide functionality not in the core repositories, e.g. custom loaders, interfaces to other tools, plugin assemblies for very narrowly-targeted tasks, etc.  Tools are the core plugin assemblies provided by Ghidra, such as the code browser and version tracking tool.

So, concurring with mumbel, code for abstract interpretation would, I think, make an excellent extension, with an eye in the future to larger tools focused on general program analysis.

**Comment by RolfRolles** [comment]
Thanks, both of you; that's exactly what I needed. Built as an extension, and then installed in Ghidra, now scripts can just `import ghidra.pal.PathBasedTVLAbstractInterpreter;` and then make use of that functionality. Great! I will distribute all of my code this way in the future.
