### ISSUE TITLE
x87: modelling of reading the status word wrong/confusing

### ISSUE THREAD

**Issue by rfalke** [NationalSecurityAgency/ghidra#2435]
**Describe the bug**
The `in_FPUStatusWord` variable arrives by magic and it not initialized.

**To Reproduce**
1. Decompile https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/i386_x87_fpu/ia32_elf/subject.exe

**Expected behavior**
Output may look like

```
uint TOP(void)
{  
  return (uint)(__read_FPUStatusWord() >> 0xb) & 7;
}
```

Or pass it in as a function parameter.

It currently is:

```
uint TOP(void)

{
  ushort in_FPUStatusWord;   <==== no value
  
  return (uint)(in_FPUStatusWord >> 0xb) & 7;
}
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "11.0.5" 2019-10-15
 - Ghidra Version: 9.1.2_PUBLIC

**Comment by Danil6969** [comment]
You should have FINIT instruction which initializes all the fields including TOP, without that the code could not be mapped to C directly anyway as it's platform dependent with all the uninitialized variables which must be mapped somehow by hand latter to the CPU state registers. We cannot violate that rule as no pcode can ovewrite variables which may have valid values and we don't know if it's initialized by FINIT or just left as is. There may be some code which could initialize TOP and scan it later after doing loop with FPU stack manipulation. The following example shows valid usage of TOP (Language ID: x86:LE:64:default, raw binary):
```
                             *************************************************************
                             *                          FUNCTION                         
                             *************************************************************
                             ushort FUN_00000000(float10 param_1, float10 param_2)
             ushort            AX:2                <RETURN>
             float10           ST0:10              param_1
             float10           ST1:10              param_2
             undefined1        TOP:1               bVar2                                   XREF[1]:     00000000(W)  
             undefined2        CX:2                sVar1                                   XREF[1]:     00000003(W)  
                             FUN_00000000
        00000000 9b db e3      FINIT
  0
        00000003 66 b9 10 00   MOV               sVar1,0x10
  0
                             LAB_00000007                                    XREF[1]:     0000000f(j)  
        00000007 dd d8         FSTP              ST0
        00000009 66 ff c9      DEC               CX
        0000000c 66 e3 02      JCXZ              LAB_00000011
        0000000f eb f6         JMP               LAB_00000007
                             LAB_00000011                                    XREF[1]:     0000000c(j)  
        00000011 9b dd 3c 24   FSTSW             word ptr [RSP]
        00000015 66 8b 04 24   MOV               AX,word ptr [RSP]
        00000019 66 c1 e8 0b   SHR               AX,0xb
        0000001d 66 83 e0 07   AND               AX,0x7
        00000021 c3            RET

```
Decompilation using [this ia.sinc](https://github.com/Danil6969/ghidra/blob/master/Ghidra/Processors/x86/data/languages/ia.sinc):
```
ushort FUN_00000000(float10 param_1,float10 param_2) {
  short sVar1;
  byte bVar2;
  
  bVar2 = 0;
  sVar1 = 0x10;
  do {
    bVar2 += 1;
    sVar1 += -1;
  } while (sVar1 != 0);
  return (ushort)(bVar2 & 7);
}
```
Here FSTP increments bVar2 (stored in TOP) by 1 and there shouldn't be any register specific reads as it would become unportable.

**Comment by Danil6969** [comment]
Also don't put FPUStatusWord register into parameters list as you only use several (or just one) bits from this word and if you do that you will end up with a lot of other flags uninitialized at call site which actually are not used by the `TOP` subroutine. Just make the `TOP` function marked "inline".

**Comment by rfalke** [comment]
Closed because the test was not a good one.
