### ISSUE TITLE
Cant Import anything

### ISSUE THREAD

**Issue by ByamB4** [NationalSecurityAgency/ghidra#2439]
**Describe the bug**
Whenever I try to import anything it shows the error "Could not find importer service". I have tried reinstalling Ghidra.

**To Reproduce**
Force shutdown your computer while Ghidra is running (not completely sure if this caused it)

**Expected behavior**
I expect it to import my file.

**Screenshots**
![1](https://user-images.githubusercontent.com/43212232/98240686-c24f3300-1fa4-11eb-9b71-89b1e8b9f8c4.png)
![1](https://user-images.githubusercontent.com/43212232/98240732-d135e580-1fa4-11eb-9a9e-1b8bc0f72307.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Java Version: 11.0
 - Ghidra Version: 9.1

**Comment by ryanmkurtz** [comment]
I'm not sure if this is 100% your problem, but it looks like you are missing some default tools.  Try going to Tools --> Import Default Tools and enable the CodeBrowser.

**Comment by dev747368** [comment]
To echo what Ryan said, your screen shot only had a version tracking tool listed, which is pretty weird.

Also, the File menu screen shot you included didn't show some normal menu options that should be there, so your configuration does look like its been messed up.  Is this a standard Ghidra install source (ie. from ghidra-sre.org) or another packaging?

**Comment by ByamB4** [comment]
> I'm not sure if this is 100% your problem, but it looks like you are missing some default tools. Try going to Tools --> Import Default Tools and enable the CodeBrowser.

Importing default tools solved problem, thanks again

**Comment by dev747368** [comment]
FYI, importing the default CodeBrowser tool will fix it when you are in the CodeBrowser, but you probably will still not have the things that you normally should have in the FrontEnd tool window.  If (in the frontend tool) you check your File | Configure -> Ghidra Core you might need to enable some plugins that got disabled (ie. ImporterPlugin)

**Comment by ByamB4** [comment]
> FYI, importing the default CodeBrowser tool will fix it when you are in the CodeBrowser, but you probably will still not have the things that you normally should have in the FrontEnd tool window. If (in the frontend tool) you check your File | Configure -> Ghidra Core you might need to enable some plugins that got disabled (ie. ImporterPlugin)

Big thanks
