### ISSUE TITLE
Adding empty RAM Fragments

### ISSUE THREAD

**Issue by WodkaRHR** [NationalSecurityAgency/ghidra#244]
I wanted to analyze a Gameboy Advance ROM with Ghidra. The memory layout is such, that the ROM is loaded to 0x8000000 (I imported it as raw binary and specified 0x8000000 as file offset) whereas there are different RAM sections in between 0x0 and 0x7FFFFFF. Everything works fine, except that I was not able to add the RAM section to my project.
How do I this? Currently all references are just resolved as "DAT_XXXXXXXXX", and I am told that the address is not in memory.
Thanks in advance!

**Comment by mumbel** [comment]
What did you already try (re: "I was not able to add the RAM section") and do you have a RAM image?  You can goto Window->Memory Map and add a new block to memory with offset/size, can set RWX permissions and then initialized or not if you want to have specific data there.
