### ISSUE TITLE
Decompiler: Unable to initialize the DecompilerInterface: Did not accept decompiler options

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2440]
**Describe the bug**
The decompiler window shows the message **Decompiler: Unable to initialize the DecompilerInterface: Did not accept decompiler options**

**To Reproduce**

1. Restore the project archive from [Dropbox](https://www.dropbox.com/s/groyc2dhcflacsu/GhidraSupport_2020_11_05.gar.zip?dl=0). I'm also going to share it with @ghidra1 via Dropbox.
2. Open program `rename.Leo` in folder `liblega-pic30-elf.a`. (I suspect a number of the related modules in the liblega-pic30 library will probably show the same error, but this is where I got it.)
3. Go to location `rom:10004` and look at the decompiler window.

**Expected behavior**
The decompiler window should either:

- Show C code that approximates this function, or,
- Show a comment explaining in language understandable to mere mortals why the decompile isn't working, and what I can do to fix that.

**Screenshots**

![rename Leo](https://user-images.githubusercontent.com/52077/98302219-01bc5600-1f8a-11eb-8b8a-54251c63b88e.png)

**Attachments**

**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.14.2]
 - Java Version: [e.g. 11.0]
 - Ghidra Version: [e.g. 9.0]

**Additional context**
This project may be useful to the Ghidra developers and others in the community. It contains much of Microchip's so-called "legacy" runtime library code for their xc16 compiler v1.50. It's freely available on their website so I don't believe there should be any copyright issues.

(Microchip calls them "legacy", even though they're current, because at one point they had re-implemented their runtime library, but it didn't work, so they deprecated the "new" libraries.)

**Comment by ghidra1** [comment]
@gtackett , Could you please test this with 9.1.2 and/or the latest master.  It shows that you are using 9.0.

**Comment by ghidra1** [comment]
BTW, While the decompiler should not ever produce this error, I would not expect great results from the decompiler for the PIC30 processor family since there are so many pointer and mapped-memory concepts not handled.  Also, using newer language concepts within an older version of Ghidra could cause such a failure.

**Comment by astrelsky** [comment]
> @gtackett , Could you please test this with 9.1.2 and/or the latest master. It shows that you are using 9.0.

I think that section just wasn't filled in as they are the default e.g. values. Iirc the graph menu wasn't present in 9.1.

**Comment by ghidra1** [comment]
@astrelsky good point.  @gtackett could you please indicate what version/commit you were using.

**Comment by gtackett** [comment]
Sorry, I just missed that part of the template.

I am indeed using Ghidra 9.2 though I don't have the commit handy here at work. I can check on that when I get home, or over the weekend.

(P.S. Does that information get stashed in the project database? If not, it might be handy to have there.)

**Comment by ghidra1** [comment]
If running from a build I believe the commit info does get recorded in the application.properties file.  If running from Eclipse you would have to check your git history/log.

**Comment by gtackett** [comment]
A pull followed by a complete rebuild (perhaps overkill) solved the problem.

(Something that I did, unknown to me, triggered the tests to run. I couldn't figure out why Ghidra kept starting and quitting, at first. 😆 )

**Comment by ghidra1** [comment]
I you execute `gradle build` it will run the units tests

`gradle buildGhidra` is the corerct way to just build a Ghidra zip
