### ISSUE TITLE
extension mechanism adding cspecs to  existing ldefs

### ISSUE THREAD

**Issue by cm68** [NationalSecurityAgency/ghidra#2450]
I'm building analyzers and loaders for a bunch of z80 binary formats: 
microsoft .rel, hitech-c, whitesmiths's, bds-c, and so forth. 

 the z80 "language" is already known to ghidra, and the extension model does not seem to cleanly support adding compilers to language ldefs, since you need to edit them in.  
each of these compilers has different calling sequences for functions, so there's not a lot of overlap there; 
I'll need cspec files for each of them.

there ought to clean way to do this using the Extension mechanism.  I should not have to fork the ghidra z80 language to do this.

**Comment by ghidra1** [comment]
A compiler specification extension mechanism has been added which will allow you to add taylored prototype models to a Program.  These take the form of an XML file that you add as a Program option (see menu **Edit->Options for _program_->Specification Extension**) and related help [Specification Extensions](https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.2.3_build/Ghidra/Features/Decompiler/src/main/help/help/topics/DecompilePlugin/DecompilerOptions.html#ExtensionOptions).

**Comment by ghidra1** [comment]
Capability exists in Ghidra.  This was added with Ghidra 10.0.
