### ISSUE TITLE
SuperH: "could not recover jumptable at X. Too many branches" on a fixed, unconditional jump

### ISSUE THREAD

**Issue by fenugrec** [NationalSecurityAgency/ghidra#2452]
[sentra_8U92A.zip](https://github.com/NationalSecurityAgency/ghidra/files/5541624/sentra_8U92A.zip)

**Describe the bug**
[**EDIT** : possibly a duplicate of #640 ; feel free to close this one ]
Not sure if it's a bug or just ghidra being over-cautious, or possibly an option I haven't set properly ?

Seems the decompiler can't digest a common code pattern, where `jmp @rn`  is used to skip over a literal pool or code, such as

```
        00005042 97 01           mov.w      @(DAT_00005048,pc),r7                            = 54DCh
        00005044 47 2b           jmp        @r7=>LAB_000054dc
        00005046 e5 10           _mov       #0x10,r5   ;just the delay slot opcode, nothing after this
[ ....]
```
The decompiler shows only partial decompilation, with
```
[...]
  (*pcVar1)(0xf,in_stack_00000000 & 0xff);
                    /* WARNING: Could not recover jumptable at 0x00005044. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)(int)DAT_00005048)(param_1,0x10);
  return;
```
In this particular case there are no code paths that could skip the first `mov.w` and execute the jmp with a different r7 value.

**To Reproduce**
Try "Sentra_8U92A.bin" (attached)

1. load at address 0, SH3B instructions. default options
2. goto 0x5044 and observe decompilation.

**Expected behavior**
Complete function decompilation.
As a side-note (or should be a separate issue ?), the decompiler never shows indirect data / function names; in the example above, it's shown as `(*(code *)(int)DAT_00005048)(param_1,0x10)`. It's obviously jumping to LAB_000054dc , as the disassembler figured out correctly; is there a way to get the decompiler to be more helpful ?

Another example in the same ROM  @ 0xf912 :
```
           (*(code *)(int)DAT_0000f998)
                     ((int)DAT_0000f996,PTR_DAT_0000f9c4,PTR_DAT_0000f9c8,
                      (int)*(short *)((int)DAT_0000f994 + 0x18) & 0xffff,
                      *(undefined *)(iVar5 + 0x52));

   actual function call : 
 FUN_00004f04(BYTE_ARRAY_00006ad1, DAT_00007f44, DAT_00007f48, DAT_ffff869c, DAT_ffff85fa)
```

**Environment (please complete the following information):**
 - Java Version: 11.0.8
 - Ghidra 9.1 dev 2020/02/22

**Comment by esaulenka** [comment]
Please, load sample binary in different place. RomRaider requires registration to download files.

**Comment by fenugrec** [comment]
> RomRaider requires registration to download files.

Sorry, I forgot about that. I uploaded as an attachment in first comment.

**Comment by GH0st3rs** [comment]
I have the same problem. This [Solution](https://reverseengineering.stackexchange.com/questions/25917/what-do-these-2-ghidra-warnings-mean/25919) not worked...

**Comment by fenugrec** [comment]
Ah. Almost 2 years later, I figured it out : by default the memory map is set as Writeable. The solution is to edit memory areas and set the ROM area as only Readable and Executable. This fixes a lot of decompiler weirdness, since ghidra was assuming all kinds of things could vary !

On the same topic, the peripheral memory area should similarly be defined as Volatile, otherwise some read/writes can be hidden by the decompiler.
