### ISSUE TITLE
Add Equate Actions to Decompiler Plugin

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2453]
**Is your feature request related to a problem? Please describe.**
Currently equates can only be created or assigned through the listing. This makes it impossible to assign an equate to a scalar which is the result of multiple instructions.

**Describe the solution you'd like**
The equate actions should be accessible in the decompiler window.

**Comment by ryanmkurtz** [comment]
Duplicate of #1231
