### ISSUE TITLE
Python Interpreter multi-line edit and paste

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2456]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm using the python interpreter, writing a for loop or function and screw up. Normally it's not a problem as I'm human and can fix it but having to manually go up to each line and resubmit them is a pain.

**Describe the solution you'd like**
The ability to toggle a multi line mode to allow editing in case of a mistake. 

**Describe alternatives you've considered**
Creating a script and running it. This leads to clutter and a ton of little scripts that are only used once.

**Additional context**
You can currently paste multiple lines and it appears to be interpreted correctly until you try to execute it.

**Comment by dragonmacher** [comment]
I can think of a few ways of implementing this, but I'm having trouble envisioning the user experience.

How do you see using this?   For example, would you choose a selection of lines from a UI that shows the recent history?    Would you then see those lines in the console input field, with the ability to edit before pressing enter?

**Comment by astrelsky** [comment]
I think there could be a few ways to approach it. The most simplest one would be if you hit enter while holding shift it will insert a new line but not submit it. Another would be a toggle button where enter doesn't submit the code and there would be a button to explicitly submit it. For editing I think it would be need to edit it directly in the history and then have it quietly re-submitted without a new history entry. You would select the text and then enable editing.

**Comment by ryanmkurtz** [comment]
One day I dreamed of adding a free-form text area to the interpreter (maybe another tab or something) where you could just type up a little script snippet and run it in one shot from memory.

**Comment by fmagin** [comment]
I think a good (ideal?) user experience would basically be for it to behave like an IPython shell. I'd expect this to be intuitively familiar to most people with Python scripting experience.

**Comment by astrelsky** [comment]
> I think a good (ideal?) user experience would basically be for it to behave like an IPython shell. I'd expect this to be intuitively familiar to most people with Python scripting experience.

That is probably a good idea. I wasn't aware it was a thing as I don't use IPython or any of the python shells for that matter.

**Comment by fmagin** [comment]
Depending on what you are doing it might be worth to check out https://github.com/justfoxing/ghidra_bridge
I used this heavily via an IPython (with Python3) shell  for anything interactive with Ghidra. I also hacked together https://github.com/fmagin/ipyghidra which includes a IPython magic that allows you to do something like

```
%%ghidra_eval
[ f.name for f in currentProgram.functionManger.getFunctions(True) ]
```
which evaluates the entire cell directly inside the Ghidra Python context. This should basically cover your use case.

Nowadays I am using an embedded Kotlin kernel via Jupyter, but that still needs a bit of work before it will be released, though hopefully this won't be long anymore.

**Comment by er28-0652** [comment]
I agree that it'll be great help for better coding experience if Ghidra Python Interpreter will implement IPython or Jupyter-like UI. But as workaround, without any additional installation, I'm doing like this;

1. create a new python file in Script Directories (say "utils.py")
2. write function, class or whatever and save
```python
# this must be located at the head of script to use Ghidra API from script
from __main__ import *

def get_all_functions():
    func = getFirstFunction()
    while func is not None:
        yield func
        func = getFunctionAfter(func)
```
3. then import and use it in Ghidra Python Interpreter
```python
>>> import utils
>>> funcs = utils.get_all_functions()
```
4. if you update a code in the script, reload the module in Interpreter  
```python
>>> reload(utils)
```

**Comment by dev747368** [comment]
@astrelsky 0fad371a8386ae2dc9e746caf20c61510c8b4aff should have fixed the issue with pasting a multi-line string into the python interp panel.
