### ISSUE TITLE
Up/down arrow keys no longer work in Structure Editor

### ISSUE THREAD

**Issue by magcius** [NationalSecurityAgency/ghidra#2459]
**Describe the bug**
It seems like the up/down arrow keys to go to the previous/next data field no longer work in Ghidra 9.2.

**To Reproduce**
1. Open a struct in the Structure Editor
2. Highlight a Data Type field and press F2 to edit it
3. Press the down arrow key

**Expected behavior**
The focus is moved to the next field

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.7
 - Ghidra Version: 9.2

**Comment by magcius** [comment]
Update: it seems like up/down arrow keys can work, but only when editing the Name column.

It would also be appreciated to make left/right work for editing between fields as well. I believe this also used to work, but no longer does.

**Comment by dragonmacher** [comment]
I would be surprised if they have been broken.   We have always relied on 'Tab' and 'Shift-Tab' for forward and backward navigation while editing.  This is Java's default navigation mechanism.    The arrow keys will fail, depending upon the type of edit taking place, as they are used to move the text cursor.

The arrow keys do work while not editing.
