### ISSUE TITLE
Decompiler not detecting bitfields in structures

### ISSUE THREAD

**Issue by magcius** [NationalSecurityAgency/ghidra#2462]
**Describe the bug**
This is PPC / Gekko. See given screenshot. I believe I have set up my bitfield so that field_0x1ec is fully covered by a bitfield full of 1-bit flags. Setting 0x20 should result in code that says `this->mb5 = 1;` or similar, but Ghidra seems unable to generate this. It's possible this is a bug in the PPC / Gekko definitions.

**To Reproduce**
I can give access to a copy of the Ghidra DB on request.

**Expected behavior**
The code generated directly sets the bitfields referenced instead of casting to byte*.

**Screenshots**
![image](https://user-images.githubusercontent.com/40890/99122557-68a5c480-25b3-11eb-9dc5-c39e63f372ae.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.2
 - Ghidra Version: 9.2

**Comment by emteere** [comment]
Bitfields are currently not directly supported in the decompiler.  Support for them is on the books.

In the meantime, a bitfield can be simulated  by creating an enumerated type that has valuess for each bit.
The decompiler will generate a set of ||'s for each enum value that makes up the value assigned to the enum data type.

**Comment by a1batross** [comment]
Would like to see any improvements on Ghidra understanding bit fields.

**Comment by theclub654** [comment]
> Would like to see any improvements on Ghidra understanding bit fields

I second this

**Comment by ryanmkurtz** [comment]
Duplicate of #647
