### ISSUE TITLE
Automatically name symbol strings in different charsets

### ISSUE THREAD

**Issue by magcius** [NationalSecurityAgency/ghidra#2463]
**Is your feature request related to a problem? Please describe.**
While it's possible to change a string to use a different charset in the assembly view by right-click on a string and choosing Data -> Settings..., the automatic symbol name seems to be limited to ASCII only. It is possible to set a Unicode label for a symbol, so it's not like the system cannot support it, it just seems unwilling to do so for the auto-generated symbol names.

While I imagine this is a way of preventing garbage from showing up, it might make more sense to do this if a non-default charset is being selected, as this implies the user knows that the symbol itself has data they care about it.

**Describe the solution you'd like**
Make the automatically generated symbol name for strings more valuable for non-ASCII charsets.

**Describe alternatives you've considered**
This is a minor feature request, so it's not impossible to work without it.

**Additional context**
Simple example, where I have a string, marked as Shift-JIS, which gets the symbol name `s__8056b3ac`.

![image](https://user-images.githubusercontent.com/40890/99123624-62184c80-25b5-11eb-937b-996d6766518d.png)

**Comment by dev747368** [comment]
The decompiler just improved its handling of strings with charsets (and translated values) so that it could display the actual string instead of a label. (your screen shot implies that the decompiler's representation was at issue)
Could you try 9.2 and see if that handles your situation?

**Comment by magcius** [comment]
This screenshot was taken on 9.2.

**Comment by astrelsky** [comment]
> This screenshot was taken on 9.2. Is there any additional setting I need to enable to display strings directly?

Set the mutability of the string to constant. You may do this by right clicking on the string in the listing, then go to `Data->Settings->Mutability` and select constant.

**Comment by magcius** [comment]
Thank you! This appears to get the string to be identified as a constant string, but it shows as tofu in 9.2, it appears...

![image](https://user-images.githubusercontent.com/40890/99125934-0603f700-25ba-11eb-97ca-7063abab198f.png)

**Comment by dev747368** [comment]
In addition to what astrelsky said, typically string data is in a read-only memory block and you get this for free.

**Comment by astrelsky** [comment]
> In addition to what astrelsky said, typically string data is in a read-only memory block and you get this for free.

Nope. In my experience the decompiler doesn't care if the block is read-only. I usually cirumvent this by making constant the default for strings. I also have a script that iterates over all defined data in read only sections to mark them as constant.

**Comment by magcius** [comment]
In my case, I also tried unchecking the W checkbox in a Memory Map and it seemed to work as well, but also generated tofu. So that appears to work correctly.

**Comment by dev747368** [comment]
@magcius I copied the visible bytes of your string into an example binary I have and the decompiler did not mess up the characters in the string... ie. I got the same characters as the listing showed.

**Comment by magcius** [comment]
Any help I can provide in debugging this, or log files I can dig into? The called function simply accepts a `char*`.

Increased the font size so you can see the rendering, and provided more bytes in the screenshot.

![image](https://user-images.githubusercontent.com/40890/99126589-56c81f80-25bb-11eb-9812-0d62f73ccd9c.png)

**Comment by dev747368** [comment]
You can use the drop down menu in the upper right of the decompiler to "Debug Function Decompilation".  This has you pick a file to save the xml payload that is transferred to the decompiler process.
You can grep through it and see if the bytes at 8056b3ac are getting there correctly, and the param info regarding the function call.
I'm no expert on whats in the file, but maybe something is obviously wrong and stands out to you.

**Comment by dev747368** [comment]
And the only other long shot is make sure the font choosen for the decompiler window has those characters defined.  If the font can't display them, you will get that character.

**Comment by magcius** [comment]
Ah, yes, I was trying to figure out where the fonts were set, but I couldn't find the Assembly Listing settings (turns out it's called "Listing Display"). It seems that the Assembly Listing defaulted to "Monospaced", while the Decompiler defaulted to "Consolas". Setting the Decompiler view to Monospaced made the text show up correctly.

**Comment by dev747368** [comment]
Boom! :)
