### ISSUE TITLE
9.2: createInitializedBlock() No Longer Supports Memory Region Names with Spaces

### ISSUE THREAD

**Issue by VGKintsugi** [NationalSecurityAgency/ghidra#2465]
**Describe the bug**
I am trying to compile my loader with Ghidra 9.2. However it appears 9.2 no longer allows spaces in memory region names. Here is a snippet of my code:
```
addr = program.getAddressFactory().getDefaultAddressSpace().getAddress(startAddress);
block = program.getMemory().createInitializedBlock(regionName, addr, endAddress-startAddress, (byte)0x00, monitor, false);
block.setRead(read);
block.setWrite(write);
block.setExecute(execute);
```
I get the following exception: 
java.lang.IllegalArgumentException: Invalid block name: SMPC Registers
at ghidra.program.database.mem.MemoryMapDB.checkBlockName(MemoryMapDB.java:821)

This used to work on Ghidra 9.1.2. Looking at the source code for checkBlockName():

```
	void checkBlockName(
			String name, boolean isOverlay)
			throws IllegalArgumentException, DuplicateNameException {
		if (!Memory.isValidAddressSpaceName(name)) {
			throw new IllegalArgumentException("Invalid block name: " + name);
		}
		if (isOverlay && getAddressFactory().getAddressSpace(name) != null) {
			throw new DuplicateNameException(
				"Block name conflicts with existing address space: " + name);
		}
	}
```
```
	/**
	 * Validate the given address space or block name: cannot be null, cannot be an empty string, cannot contain blank
	 * or reserved characters (e.g., colon).
	 * @return true if name is valid else false
	 */
	public static boolean isValidAddressSpaceName(String name) {
		if (name == null || name.length() == 0) {
			return false;
		}
		for (int i = 0; i < name.length(); i++) {
			char c = name.charAt(i);
			if (c <= 0x20 || c >= 0x7f || c == ':') {
				return false;
			}
		}
		return true;
	}
```
So this is clearly an intentional change. Why was the ability to have spaces in region names removed?

**Comment by ghidra1** [comment]
The issue stems from the 1:1 naming between block names and associated overlay names when they are used.  On a typical import, block collisions in memory can cause a section (or portion) to be forced into an overlay block.  We must be able to parse overlay address strings which are prefixed by the address space name.  In most cases the bounds of the address string is known, in which case a space would not be an issue, however the ':' character will be a definite problem.  If address strings appear in messages or other unquoted uses (e.g., command line arguments) identifying start and end of an address could become problematic.  In order to loosen this restriction I am looking at eliminating the 1:1 overlay address space naming restriction, although this could cause some confusion when seeing overlay space addresses.

Could you tell me what the origin of the block name was.  I would not think a compiler or toolchain would permit such a name.

**Comment by VGKintsugi** [comment]
Thanks for the quick response. I basically just copied the names from a memory map of the device: 

		// 0x00000000 	0x000FFFFF 	Boot ROM
		// 0x00100000 	0x0017FFFF 	SMPC Registers
		// 0x00180000 	0x001FFFFF 	Backup RAM
		// 0x00200000 	0x002FFFFF 	Work RAM Low
		// 0x02000000 	0x03FFFFFF 	A-Bus CS0
		// 0x04000000 	0x04FFFFFF 	A-Bus CS1
		// 0x05000000 	0x057FFFFF 	A-Bus Dummy
		// 0x05800000 	0x058FFFFF 	A-Bus CS2
		// 0x05A00000 	0x05AFFFFF 	68000 Work RAM
		// 0x05B00000 	0x05BFFFFF 	SCSP registers
		// 0x05C00000 	0x05C7FFFF 	VDP1 VRAM
		// 0x05C80000 	0x05CFFFFF 	VDP1 Framebuffer
		// 0x05D00000 	0x05D7FFFF 	VDP1 Registers
		// 0x05D80000 	0x05DFFFFF 	Lockup When Read2
		// 0x05E00000 	0x05EFFFFF 	VDP2 VRAM
		// 0x05F00000 	0x05F7FFFF 	VDP2 CRAM
		// 0x05F80000 	0x05FBFFFF 	VDP2 Registers
		// 0x05FE0000 	0x05FEFFFF 	SCU Registers
		// 0x05FF0000 	0x05FFFFFF 	Unknown Registers
		// 0x06000000 	0x07FFFFFF 	Work RAM High
		// 0xFFFFFE00 	0xFFFFFFFF	On Chip Registers

So clearly these names have spaces in them. This worked prior to 9.2. For 9.2 compatibility I ended up replacing all spaces with "_".

**Comment by ghidra1** [comment]
Those look like comments and not actual names which would be utilized by a compiler toolchain for section naming.

**Comment by VGKintsugi** [comment]
Yeah that's correct. My device doesn't have a image sections, everything is bare metal PIC as far as a I know.

**Comment by eShuttleworth** [comment]
For what it's worth, I have run into a case where sections were named with spaces in them by a real compiler. 

```➜  objdump -s root.elf | grep -p "Contents of section"
Contents of section .shstrtab:
Contents of section .strtab:
Contents of section .symtab:
Contents of section A1 rw:
Contents of section P1 ro:
Contents of section A4 rw:
Contents of section P1 ro:
Contents of section A3 rw:
Contents of section A2 rw:
Contents of section P2 s0:
Contents of section P2 zi:
Contents of section P2 ui:
Contents of section .debug_abbrev:
Contents of section .debug_frame:
Contents of section .debug_info:
Contents of section .debug_line:
Contents of section .debug_loc:
Contents of section .debug_macinfo:
Contents of section .debug_pubnames:
Contents of section .debug_ranges:
Contents of section .iar.debug_line:
Contents of section .comment:
Contents of section .iar.rtmodel:```

**Comment by dev747368** [comment]
@eShuttleworth any info on the tool chain / build options that caused it to produce those sections?

**Comment by ghidra1** [comment]
I believe those are section permissions and not part of the section name

**Comment by ghidra1** [comment]
Either way, we are looking to restore this block naming capability

**Comment by autinerd** [comment]
@dev747368
> @eShuttleworth any info on the tool chain / build options that caused it to produce those sections?

The IAR C compiler/linker does this automatically, Here is a description of the developer on what the sections stand for: https://www.iar.com/support/tech-notes/linker/what-are-p1-p2-a1-a2-etc-in-the-.map-file-v.5.xx/

**Comment by eShuttleworth** [comment]
> @dev747368
> 
> > @eShuttleworth any info on the tool chain / build options that caused it to produce those sections?
> 
> The IAR C compiler/linker does this automatically, Here is a description of the developer on what the sections stand for: https://www.iar.com/support/tech-notes/linker/what-are-p1-p2-a1-a2-etc-in-the-.map-file-v.5.xx/

Yep it's IAR, I don't have any more insight unfortunately

**Comment by ghidra1** [comment]
The `patch` and `master` branches have been updated to allow this
