### ISSUE TITLE
Server: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass 

### ISSUE THREAD

**Issue by ghidra-server** [NationalSecurityAgency/ghidra#2468]
**Describe the bug**
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass 

**To Reproduce**
1. Start with Ghidra 9.2 (pretty sure it affects older versions too)
2. Run svrInstall

**Expected behavior**
No WARNINGs:

Installing Ghidra Server...
YAJSW: yajsw-stable-12.12
OS   : Linux/3.10.0-957.5.1.el7.x86_64/amd64
JVM  : Red Hat, Inc./11.0.9//usr/lib/jvm/java-11-openjdk-11.0.9.11-0.el7_9.x86_64/64
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/ghidra/Software/ghidra_9.2_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/./lib/extended/groovy/groovy-all-2.4.11.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Linux/3.10.0-957.5.1.el7.x86_64/amd64
 - Java Version: Red Hat, Inc./11.0.9//usr/lib/jvm/java-11-openjdk-11.0.9.11-0.el7_9.x86_64/64
 - Ghidra Version: 9.2 and suspected 9.x

**Additional context**
Doesn't seem to cause any problems: but I'm worried about the "WARNING: All illegal access operations will be denied in a future release"

**Comment by astrelsky** [comment]
This is caused by `org.codehaus.groovy.reflection.CachedClass` not Ghidra.

**Comment by ghidra-server** [comment]
Thanks - you're right and there's an issue with a fix in a Beta: https://issues.apache.org/jira/browse/GROOVY-8339

**Comment by ghidra1** [comment]
This is a known issue.  Can we close this ticket?

**Comment by ghidra1** [comment]
These reflection warnings are a known issue.  Another case for Ghidra occurs during startup:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ghidra.framework.GhidraApplicationConfiguration (file:/home/jdirish/git-ghidra/ghidra/Ghidra/Features/Base/bin/main/) to field sun.awt.X11.XToolkit.awtAppClassName
```
Such warnings will likely persist until we figure out a way to work around them.
