### ISSUE TITLE
Renaming parameters that have function pointer types drops the type

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#247]
**To Reproduce**
1. Create a new function definition from the data type manager
2. 'Retype' a parameter in the decompiler window to be a pointer to this function definition
3. 'Rename' that same parameter to a different name
4. The parameter type is dropped and changed to undefined

**Expected behavior**
The parameter type should be maintained

**Comment by caheckman** [comment]
I'm duplicating this. The decompiler isn't correctly passing back function pointer datatypes, so the datatype is getting lost by the rename action within the decompiler window. Thanks for reporting this.

A workaround is to either rename from the listing window or to rename first and then retype.

Putting a patch in (which unfortunately looks like its too late for the 9.0.1 build)

**Comment by caheckman** [comment]
Patch is complete and scheduled for 9.0.2.
