### ISSUE TITLE
Mouse Pointer Invisible following use of Graphing

### ISSUE THREAD

**Issue by ghidra-server** [NationalSecurityAgency/ghidra#2471]
**Describe the bug**
Mouse pointer vanishes and remains invisible within all Ghidra Windows during/after new graphing (e.g code flow) tool use.

**To Reproduce**
1. Load binary in code browser
2. Navigate to Graph Menu...Code Flow
3. Drag Graph Window to 2nd screen (different Graphics card)
4. Move mouse pointer back to code browser
5. Mouse pointer vanishes

**Expected behavior**
Mouse pointer should not vanish and remain invisible

**Screenshots**

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 1909 18363.1198
 - Java Version: jdk-11.0.9+11
 - Ghidra Version: 9.2

**Additional context**
Could not replicate on single monitor, so suspect multiple monitor, or multiple Graphics Card (one GTX one Intel P-series) issue.
Quitting Ghidra and restarting Ghidra resolved the issue, but then it re-occurred on next use of Graphing.

**Comment by dragonmacher** [comment]
Closing this now as we cannot reproduce the issue and it is likely specific to the setup listed above.
