### ISSUE TITLE
Bulk Program upgrade tooling

### ISSUE THREAD

**Issue by ghidra-server** [NationalSecurityAgency/ghidra#2472]
**Is your feature request related to a problem? Please describe.**
Manually opening, upgrading, saving and closing Programs on a Shared Ghidra Server is annoying.

**Describe the solution you'd like**
CLI command and/or GUI tooling to bulk upgrade Programs within Ghidra server to cope with Client version changes.
Should include booting existing checkouts, checking out, opening, upgraging, saving, checking in each program specified in a list, ensuring these is also tooling to extract lists of Programs to act on and regex/pick from.

**Describe alternatives you've considered**
Wondering whether the headless Ghidra mode could be used to accomplish this.

**Additional context**
N/A

**Comment by ghidra1** [comment]
There is a script which may accomplish what you are asking: `RepositoryFileUpgradeScript.java`

**Comment by ghidra1** [comment]
Note: The above mentioned script is intended to be used in GUI mode due to the interaction dialogs.  It could easily be dumbed-down to work in a headless fashion, although I'm not sure this is ideal since all check-outs need to be addressed before all files can be properly upgraded.

**Comment by ghidra-server** [comment]
Thanks - that should do the job.
