### ISSUE TITLE
ghidra-data repo is outdated

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#2474]
The official Ghidra 9.2 release contains `vs2017_x64.fidbf`, `vs2017_x86.fidbf`, `vs2019_x64.fidbf`, `vs2019_x86.fidbf` in the `Ghidra/Features/FunctionID/data` directory, but they are not available in the [NationalSecurityAgency/ghidra-data](https://github.com/NationalSecurityAgency/ghidra-data) repo yet. Could you please update the ghidra-data repo?

Thank you!

**Comment by ghidra1** [comment]
Sorry for the delay.  The [ghidra-data](https://github.com/NationalSecurityAgency/ghidra-data) repo has been updated with the 9.2 FID datasets.
