### ISSUE TITLE
Failed to find a supported JDK Ghidra 9.2 Windows 10

### ISSUE THREAD

**Issue by QuentinGruber** [NationalSecurityAgency/ghidra#2476]
When i launch ghidra 9.2 i got this error :

![image](https://user-images.githubusercontent.com/47059878/99153456-eac3e500-26a8-11eb-8586-1c2096b1c501.png)

And here is my `java --version` 
![image](https://user-images.githubusercontent.com/47059878/99153472-fc0cf180-26a8-11eb-8033-ba80aa215637.png)

Ghidra 9.12 work for me so i don't understand what have changed.

**Comment by mumbel** [comment]
Do you have other JRE/JDK's installed by chance (could you also paste your `javac --version`, `where java`, and `where javac` outputs)?

**Comment by QuentinGruber** [comment]
result of `javac--version` : 
`javac 11.0.9`
result of `where java` : 
`C:\Program Files\AdoptOpenJDK\jdk-11.0.9.11-hotspot\bin\java.exe`
`C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe`
result of `where javac` : 
`C:\Program Files\AdoptOpenJDK\jdk-11.0.9.11-hotspot\bin\javac.exe`

do you have any advice on how to have a clean java installation?

**Comment by mumbel** [comment]
I guess there is the ever so slight chance ghidra is somehow picking up the `Program Files (x86)` java.exe which would fail due to 32-bit.  Sorry not a big windows user.  You might see if Oracle Java is listed in installed programs and see if you can remove it (should be safe since you have the AdoptOpenJdk anyways, and worse case just reinstall Oracle Java, but see if 64-bit is an option).

**Comment by QuentinGruber** [comment]
I uninstalled the x86 version and tried to put `JAVA_HOME_OVERRIDE=C:\Program Files\AdoptOpenJDK\jdk-11.0.9.11-hotspot\bin` but it didn't fix my error sadly :(

**Comment by mumbel** [comment]
I'm at a loss.  You might try deleting the unzipped directory, delete (rename if you want to keep in case) your .ghidra in your home directory, and re-unzip the 9.2 release.

**Comment by QuentinGruber** [comment]
ok I just re-downloaded ghidra and that's it ^^ thank you for your time.

**Comment by ghizard** [comment]
Same situation seemed to have occurred in #1732. Can you recall if you did anything different between your first and second installation of 9.2?

**Comment by ryanmkurtz** [comment]
It seemed that the `application.properties` file was missing from your install installation.
