### ISSUE TITLE
Clearer Server Upgrade Documentation

### ISSUE THREAD

**Issue by ghidra-server** [NationalSecurityAgency/ghidra#2479]
**Is your feature request related to a problem? Please describe.**
Current Server upgrade documentation (in the Ghidra Server Readme) does not state that ./ghidraSvr stop needs to be run first.

**Describe the solution you'd like**
Document as part of a server upgrade that ./ghidraSvr stop must be run before svrUninstall 
Similar for Windows.

**Describe alternatives you've considered**
Adding the stop commands (or even just checking for running processes and warning)  into the uninstall scripts for Windows and Linux.

**Additional context**
N/A

**Comment by ghidra1** [comment]
It was my understanding that the wrapper uninstall will stop the installed service.  It is important that the uninstall be done from the old Ghidra installation and not the new one.
