### ISSUE TITLE
Show selected number of bytes/lines during selection operation

### ISSUE THREAD

**Issue by raminsadre** [NationalSecurityAgency/ghidra#2482]
**Is your feature request related to a problem? Please describe.**
When selecting several addresses in the listing view by left-clicking and dragging the mouse (or by holding the shift key and moving the cursor with the cursor keys), the listing view does not show how many bytes and lines are currently selected. Only when the mouse button is released, the title bar of the listing view shows the number of selected addresses.

**Describe the solution you'd like**
The list view should show how many bytes and lines are currently selected during the selection operation (i.e. while dragging the mouse), not just when the selection has finished,

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by emteere** [comment]
A good suggestion.
Another way to select some number of bytes is Select->Bytes.  You can specify the exact number of bytes from the cursor location.
