### ISSUE TITLE
Replacing function calls with pcode

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2483]
I'm looking to replace calls to soft library functions with the equivalent pcode. If I understand correctly this is possible with callfixup in the cspec file but I cannot seem to get it to work correctly. Here is an example of what I have tried:

```xml
<callfixup name="dpadd">
  <pcode>
    <input name="dp1"/>
    <output name="dp"/>
    <input name="dp2"/>
    <body><![CDATA[
      dp = dp1 f+ dp2;
      ]]></body>
  </pcode>
</callfixup>
```

**Comment by emteere** [comment]
I would get rid of the input/output, and use the actual locations used as inputs and outputs directly.
Normally input/output is used to supply pcode to pcode userops.
Also you would need to assign the callfixup to the function by hand (edit function), unless you add 
<target name="dpadd"/>

The above only defines a call fixup named dpadd, it doesn't automatically assign it to functions named dpadd.

**Comment by astrelsky** [comment]
> I would get rid of the input/output, and use the actual locations used as inputs and outputs directly.
> Normally input/output is used to supply pcode to pcode userops.
> Also you would need to assign the callfixup to the function by hand (edit function), unless you add 
> <target name="dpadd"/>
> 
> The above only defines a call fixup named dpadd, it doesn't automatically assign it to functions named dpadd.

I see. I initially had hard coded the locations and tried my example later. I had used an entry from one of the x86 cspecs. I wasn't aware that I had to manually assign it but I can just script it. 

It would be pretty cool to have this done for the built in gcc functions for processors that can't add longs and such. Of course assuming they weren't inlined.

**Comment by astrelsky** [comment]
Setting the call-fixup in the function signature did what I was looking for. Thank you.

**Comment by sollyucko** [comment]
You could also try adding `<target name="dpadd"/>`  within `<callfixup>`. (Also for anyone else who comes across this issue.)
