### ISSUE TITLE
Stack depth after Set Stack Depth Change on indirect call is 4 less than expected

### ISSUE THREAD

**Issue by FrozenFish24** [NationalSecurityAgency/ghidra#2484]
**Describe the bug**
When using `Set Stack Depth Change...` on an indirect call i.e. `CALL dword ptr [ECX + 0xC8]` you must specify a value 4 larger than expected in order to get the desired change.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find an indirect `CALL` that is followed by a `- ? -` stack depth
2. Right click the call, `Function` -> `Set Stack Depth Change...`
3. Enter any value

**Expected behavior**
If the stack depth was `0dc` when the call is made and the change entered was `0xc` the stack depth on the next instruction should be `0d0`, instead it is `0d4`

**Screenshots**
![bug](https://user-images.githubusercontent.com/12547453/99193553-bc333080-27b4-11eb-958b-c8e33a04bc08.png)

**Attachments**
n/a

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 14
 - Ghidra Version: 9.2

**Comment by emteere** [comment]
Currently overriding the stack depth change includes the purge done by the called function.
In your case the three 4 byte values plus the 4 byte return, which is 16 bytes.
The stack depth 0xdc is that stack depth at the start of the instruction.  The instruction pushes on the 4 byte return.
If it wasn't done this way, you couldn't correct the stack depth of a function that doesn't purge the return value from the stack.

**Comment by FrozenFish24** [comment]
That makes sense, the equivalent facility in IDA doesn't seem to account for the return address which is what led to my confusion, thanks for the explanation.
