### ISSUE TITLE
Ghidra 9.2 regression arm64e PAC instructions Pcode operations are missing

### ISSUE THREAD

**Issue by uint63t** [NationalSecurityAgency/ghidra#2488]
With Ghidra 9.2, when I disassemble any iOS arm64e binary, I observe:
In the Listing window, when I enable the Pcode view with the "Edit the Listing fields" button under Instruction/Data, most instructions do show the Pcode operations that make up the instruction, but none are listed under the PAC instructions like pacia:

        00001100 10 72 0a 91     add        x16,x16,#0x29c
                                                      $U23d0:8 = COPY 0x29c:8
                                                      tmpCY = INT_CARRY x16, $U23d0:8
                                                      tmpOV = INT_SCARRY x16, $U23d0:8
                                                      $U23f0:8 = INT_ADD x16, $U23d0:8
                                                      tmpNG = INT_SLESS $U23f0:8, 0:8
                                                      tmpZR = INT_EQUAL $U23f0:8, 0:8
                                                      x16 = COPY $U23f0:8
        00001104 10 01 c1 da     pacia      x16,x8
        00001108 f0 47 00 f9     str        x16=>___Block_byref_object_copy_,[sp, #local_68]
                                                      $Uca0:8 = INT_ADD sp, 0x88:8
                                                      STORE ram($Uca0:8), x16

Additionally, when Python scripting to look at these instructions, if I do something like:
code_unit =  getState().getCurrentProgram().getListing().getCodeUnitAt(addr)
str(code_unit) is pacia x16,x8
code_unit.getClass() is ghidra.program.database.code.InstructionDB
code_unit.getInputObjects() returns an empty array, which seems wrong because there are 2 operands.

**Comment by emteere** [comment]
There was a change in Ghidra 9.2 to support some of the more complicated instructions with implicit side-effects that don't normally affect compiled code, and are added by the compiler.
There are new flags you can set on the program to show the semantics of certain instruction classes.

	ShowPAC 
	PAC_clobber
	ShowBTI 
	ShowMemTag
The plan is to eventually change the way this is done, however issues with the decompiler dead code removal and other factors. They were implemented with context registers at the current time.
Unfortunately to have these show up you need to set them across the program memory with the SetRegisterValue...
Then if the code has already been disassembled, it needs to be cleared and re-disassembled.
If you would always like to have them on by default, you can change the AARCH64.pspec file to set them.
```
  <context_data>
    <context_set space="ram">
<!-- These context registers are only modified by the user, e.g. with the "Set Registers..." command. -->
      <set name="ShowPAC" val="0" description="1 to show PAC operations in decompiler"/>
      <set name="PAC_clobber" val="0" description="1 to let PAC operations overwrite their operands in decompiler"/>
      <set name="ShowBTI" val="0" description="1 to show BTI effects in decompiler"/>
      <set name="ShowMemTag" val="0" description="1 to show memory tag checks in decompiler"/>
    </context_set>
  </context_data>
```

**Comment by uint63t** [comment]
Thanks, I verified editing the AARCH4.pspec file addresses the issue.
