### ISSUE TITLE
Is it possible to create custom GhidraScript providers in Ghidra 9.2?

### ISSUE THREAD

**Issue by edmcman** [NationalSecurityAgency/ghidra#2490]
I am the author of a [Ghidra plugin for writing GhidraScripts in Scala](https://github.com/edmcman/ghidra-scala-loader).  I am trying to update the plugin for Ghidra 9.2, which uses bundles for GhidraScripts.

But I'm starting to wonder if it is really possible to implement new GhidraScript providers in Ghidra 9.2.  There seems to be an assumption that any source directory containing scripts is handled by GhidraSourceBundle which assumes the source code is Java.  This happens in BundleHost, which I don't think I can change:

https://sourcegraph.com/github.com/NationalSecurityAgency/ghidra@8f1be0932ac035c3da550f2bcd9ddefbc5918362/-/blob/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/osgi/BundleHost.java#L162

Is it possible to implement new GhidraScript providers?  If so, how?  If not, is it intentional?

**Comment by astrelsky** [comment]
It is possible. I believe there is a javascript one floating around but I may be mistaken. To create a new one simply follow the same rules as other `ExtensionPoint`s. Simply extend `ghidra.app.script.GhidraScriptProvider` and the class's name must end in `ScriptProvider`

**Comment by edmcman** [comment]
Yes, prior to Ghidra 9.2 this was very easy.  But as a result of the changes to 9.2 it is no longer clear (to me, anyway) that this is possible.  

 If you are aware of an example in Ghidra 9.2, I would be very interested to see it.

**Comment by astrelsky** [comment]
> Yes, prior to Ghidra 9.2 this was very easy. But as a result of the changes to 9.2 it is no longer clear (to me, anyway) that this is possible.
> 
> If you are aware of an example in Ghidra 9.2, I would be very interested to see it.

Hmm unfortunately I am not. What exactly isn't clear? I don't directly see anything that changed that may cause a problem other than the new usage of apache felix. @jpleasu would probably know.

**Comment by edmcman** [comment]
The JavaScriptProvider uses the new bundle infrastructure.  I don't think it's possible to create new bundles for other source code languages.

I guess it's still possible in theory to implement a new script provider as long as it doesn't use bundles, but at the expense of not being able to reuse any code used by the JavaScriptProvider.

**Comment by edmcman** [comment]
I'm trying to write a script provider without using bundles, but it's an uphill battle because `GhidraScriptUtil` seems to have been gutted, which was used heavily in previous versions.

**Comment by jpleasu** [comment]
[Jython scripting](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Python/src/main/java/ghidra/python/PythonScriptProvider.java) is implemented with a ScriptProvider as @astrelsky points out.

The `JavaScriptClassLoader` class is no longer necessary, so it's been removed.  You could add the old implementation to your plugin with updates to construct the Java classpath from the bundle classes [as the current Jython implementation does](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Python/src/main/java/ghidra/python/GhidraPythonInterpreter.java#L141).

Scala, Kotlin, etc. class files dropped into a compiled-bundles/XXXX directory will be deleted by the new change detection, so you'll need to decide where to cache your class files (the old "bin" location is as good as any).

If there's interest in scripting extensions that participate in OSGi, I'm open to working on it.

**Comment by edmcman** [comment]
@jpleasu Thanks for the reference.  I'm a bit puzzled because the Jython code you linked to doesn't actually appear to produce .class files.  I noticed the same thing in `JavaScriptProvider`.  I'm very confused as to where/when I'm supposed to be actually producing the .class file now.

**Comment by jpleasu** [comment]
Jython doesn't produce class files, but it has access to the class files generated by Java scripts.  If your scripts don't need to access the classes from Java scripts you can ignore that comment.

How you get from a .scala file to a `GhidraScript` class in your plugin's implementation of `GhidraScriptProvider#getScriptInstance` is up to you.  You [might not](https://www.scala-lang.org/api/current/scala-compiler/scala/tools/nsc/interpreter/index.html) need generate any class files.  If you do, though, don't put them in the compiled-bundled/XXX directory, they'll be deleted.
