### ISSUE TITLE
Removing  unnecessary casts

### ISSUE THREAD

**Issue by WhoAteDaCake** [NationalSecurityAgency/ghidra#2491]
I have the following bit of code

```
void FUN_00010b76(int rand_num)

{
  Derived *this;
  undefined4 uVar1;
  code **ppcVar2;
  code *local_18;
  byte *local_14;
  
  std::operator<<((basic_ostream *)std::cout,"========Pointer==============\n");
  this = (Derived *)operator.new(0x14);
  Derived::Derived(this);
  (*(code *)((this->Base)._vptr)->__cxa_pure_virtual)(this,(int)(short)rand_num)
```

The variable `rand_num` was initially a short, however, I modified it to be an `int` type, now on line:

```
 (*(code *)((this->Base)._vptr)->__cxa_pure_virtual)(this,(int)(short)rand_num)
```

The cast `(int)(short)rand_num` is not needed. Is there a way to remove it ? Thanks

**Comment by astrelsky** [comment]
You can override the function signature if you are certain the current type is correct and the cast will go away. I **always** override the signatures for `new`, `malloc`, `delete`, `free` and for custom allocators. It also helps keep the decompiler's type propagation system from getting confused about what they type should be.

**Comment by jpleasu** [comment]
Hmm.. are you sure that `rand_num` isn't passed through a 2 byte register? or stored in only 2 bytes of stack?

`(short)(int)` would be redundant, but `(int)(short)` narrows when applied to an `int`.

**Comment by WhoAteDaCake** [comment]
Thanks for the responses.
You were right @jpleasu . I've looked into the source code and `__cxa_pure_virtual` takes `int16_t`, so I guess it makes sense that it gets cast?

**Comment by astrelsky** [comment]
`__cxa_pure_virtual` takes no arguments and terminates the program if executed. It is never supposed to be executed as it is a placeholder in a vtable for a virtual function. The function which is actually being invoked is determined at runtime.

**Comment by jpleasu** [comment]
Independent of @astrelsky 's comment, I think we can figure out the weird double cast.

if `(*(code *)((this->Base)._vptr)->__cxa_pure_virtual)` is defined to have type `void (*) (Derived *, short )`, you shouldn't see that outer `(int)` cast, only the `short` cast is necessary.  If it's defined `void (*) (Derived *, int )`, you're correct to expect no cast at all!  That inner cast _probably_ corresponds to some computation.  The decompiler might be inferring the second prototype for you.

Why a double cast?  By declaring `rand_num` with type `int` in the function prototype, the incoming value (varnode) will be a 4 byte register.  I'm guessing there is a narrowing operation that corresponds to that inner cast to `short` somewhere in the data flow from input to that call to `__cxa_pure_vritual`.

Can you post the listing for `FUN_00010b76`?

**Comment by WhoAteDaCake** [comment]
The full decompiled function:

```

/* WARNING: Heritage AFTER dead removal. Example location: r0 : 0x00010bb2 */
/* WARNING: Restarted to delay deadcode elimination for space: register */
/* WARNING: Exceeded maximum restarts with more pending */

void current(int rand_num)

{
  Derived *this;
  ulong uVar1;
  code **ppcVar2;
  undefined4 uVar3;
  code *local_18;
  byte *local_14;
  
  std::operator<<((basic_ostream *)std::cout,"========Pointer==============\n");
  this = (Derived *)operator.new(0x14);
  Derived::Derived(this);
  (*this->Base->112a8)(this,(int)(short)rand_num);
  (*this->Base->11338)(this,rand_num & 0xffff);
  uVar1 = (*this->Base->11306)();
  printf("U16 = %d\n",uVar1);
  uVar1 = (*this->Base->1131e)();
  printf("U32 = %d\n",uVar1);
  printf("Nest32 = 0x%4X\n",*(undefined4 *)((int)this->field_0x10 + 4));
                    /* WARNING: Load size is inaccurate */
  (**(code **)(*this->field_0x10 + 4))(this->field_0x10);
                    /* WARNING: Load size is inaccurate */
  (***this->field_0x10)(this->field_0x10);
  local_14 = (byte *)this->string;
  while (*local_14 != 0) {
    putchar((uint)*local_14);
    local_14 = local_14 + 1;
  }
  std::basic_ostream<char,std::char_traits<char>>::operator<<
            ((basic_ostream<char,std::char_traits<char>> *)std::cout,
             std::endl<char,std::char_traits<char>>);
  printf("{%s}\n",*(undefined4 *)((int)this->field_0x10 + 0xc));
  ppcVar2 = (code **)operator.new(0x14);
  FUN_000113bc(ppcVar2);
  (**(code **)*ppcVar2)(ppcVar2,(int)(short)rand_num);
  (**(code **)(*ppcVar2 + 0xc))(ppcVar2,rand_num & 0xffff);
  uVar3 = (**(code **)(*ppcVar2 + 4))(ppcVar2);
  printf("U16 = %d\n",uVar3);
  uVar3 = (**(code **)(*ppcVar2 + 8))(ppcVar2);
  printf("U32 = %d\n",uVar3);
  printf("Nest32 = 0x%4X\n",*(undefined4 *)(ppcVar2[4] + 4));
  (**(code **)(*(int *)ppcVar2[4] + 4))(ppcVar2[4]);
  (***(code ***)ppcVar2[4])(ppcVar2[4]);
  local_18 = ppcVar2[1];
  while (*local_18 != (code)0x0) {
    putchar((uint)(byte)*local_18);
    local_18 = local_18 + 1;
  }
  std::basic_ostream<char,std::char_traits<char>>::operator<<
            ((basic_ostream<char,std::char_traits<char>> *)std::cout,
             std::endl<char,std::char_traits<char>>);
  printf("{%s}\n",*(undefined4 *)(ppcVar2[4] + 0xc));
  if (this != (Derived *)0x0) {
    (*this->Base->11288)();
  }
  if (ppcVar2 != (code **)0x0) {
    (**(code **)(*ppcVar2 + 0x14))(ppcVar2);
  }
  return;
}
```

The original source code: https://github.com/james-tate/ghidraExampleSource/blob/master/ghidra_test.cpp

**Comment by jpleasu** [comment]
I'm sorry, by "listing" we usually mean Ghidra's assembly listing: from the code browser, Window -> Listing.

**Comment by jpleasu** [comment]
I tool a look at the example, and it's what I suspected, the incoming value is truncated.  Here's the breakdown:

`local_2c` gets the incoming first argument here:
```
        00010b7c 78 60           str        r0,[r7,#local_2c]
```
Then just prior to the call on `00010bb2`, it's fetched and sign extended from 16 bits to 32 with [`sxth`](https://developer.arm.com/documentation/dui0473/m/arm-and-thumb-instructions/sxth).

```
        00010baa 7a 68           ldr        r2,[r7,#local_2c]
        00010bac 12 b2           sxth       r2,r2
        00010bae 11 46           mov        r1,r2
        00010bb0 78 69           ldr        r0,[r7,#local_1c]
        00010bb2 98 47           blx        r3
```

The correspondence between the `(short)` narrowing operation and that `sxth` instruction can be found by selecting the cast operation (drag the cursor over it) in the decompiler window - the sxth instruction in the listing will show the corresponding selection:

![image](https://user-images.githubusercontent.com/1778531/99676855-059aae80-2a47-11eb-93ff-0e2500cbf507.png)

**Comment by WhoAteDaCake** [comment]
Thanks for all the support 😊. I'll close it as it wasn't really a bug.
