### ISSUE TITLE
Renaming function pointers in decompiler

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#2495]
9.2 / windows 10

Within the decompiler window, I have something like  `param_1->proc = FUN_AABBCCDD;`.  Attempting to rename the function results in a error pop-up `Rename Failed`: `Memory storage not found for global variable`.  Rename from listing still works and renaming other globals (`DAT_`) works in either.

**Comment by caheckman** [comment]
This was fixed in 9.2.1 by @astrelsky,  see #2415

**Comment by mumbel** [comment]
Thanks @caheckman   I did try to repro the other day and couldn't, guess I should have updated here
