### ISSUE TITLE
I broke my clone of Ghidra development build trying to fix a problem with PyDev interpreter

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2499]
I updated my clone of the Ghidra repo and rebuilt it and the native images using gradle.

At that point Ghidra itself was working fine (running it from Eclipse of course).

But in eclipse, PyDev was complaining that I didn't have an interpreter configured. I went off trying to find a suitable jython<em>xxx</em> .jar but couldn't find one for some reason. 

There's one that I was pretty sure wasn't the right one in `/Users/gtackett/git/ghidra/GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin/build/data/buildDependencies/pydev/plugins/org.python.pydev.jython_6.3.1.201802272029/jython.jar`.

But since I couldn't find another one anywhere on my filesystem, I tried selecting it.

Now, when I try to start Ghidra I get this in the Eclipse console:
![image](https://user-images.githubusercontent.com/52077/99456766-e80aff00-28f7-11eb-997f-268719a6548f.png)

**Comment by ryanmkurtz** [comment]
The short answer is that Ghidra doesn't provide proper Eclipse/Python script development when you are working out of the Ghidra repo.

If you want to develop Python scripts with the full Ghidra support, you'll need to install the GhidraDev eclipse plugin, and point it at an external Ghidra installation.

If you are just trying to make PyDev happy so you can edit some python files in your environment, you can either download Jython independently from the Jython website and point your PyDev do it, or you can even point your PyDev to an existing installation of CPython.  However, if you are looking for your Python script development to be "Ghidra aware", you have to go the GhidraDev/Ghidra installation route.
