### ISSUE TITLE
65816 support (SNES)

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#250]
Hi,

For now there is no support of 65816 processor. It would be great to add it.

**Comment by achan1989** [comment]
I've started to work on it.  I'll post a link once the basics are in place.

**Comment by digarok** [comment]
Any progress on this?  I'm happy to help contribute.  I'm interested in using it for Apple IIgs binaries.

**Comment by achan1989** [comment]
I had got it to the stage where it might be useful for disassembly only, but the data flow analysis would certainly be wrong.  I'm now in the middle of re-working it for correct data flow -- it's in a bit of an ugly state at the moment, but I'm getting there.

**Comment by achan1989** [comment]
Hokay, the initial release is available at [https://github.com/achan1989/ghidra-65816](https://github.com/achan1989/ghidra-65816) :)

Please not that it's at an early stage. It probably has some bugs, and it might not be as easy to use as it could be.  I'd recommend checking out the readme.

Feedback is welcome!

**Comment by GhidorahRex** [comment]
We may implement new processors and variants via pull-requests but we aren't planning on specifically incorporating the 65816 at this time.

**Comment by nonchip** [comment]
"completed"

**Comment by MasterKnightDH** [comment]
I DLed the ZIP file. No matter what I do, the file, whether unzipped or not, refuses to show up as an Extension to add and I'm stuck getting error messages when trying to handle files involving 65816.

**Comment by GhidorahRex** [comment]
> I DLed the ZIP file. No matter what I do, the file, whether unzipped or not, refuses to show up as an Extension to add and I'm stuck getting error messages when trying to handle files involving 65816.

You want to place the files under the Ghidra/Processors directory, then relaunch Ghidra. It will auto-detect the new language. There are some additional instructions in the readme for the 65816 download that may be helpful.

**Comment by MasterKnightDH** [comment]
<img width="1912" height="1200" alt="Image" src="https://github.com/user-attachments/assets/336d4be5-d0fa-4515-a6e7-48c80be3e182" />
I am getting this error with version 9.1, which I used in the past. And updating to a more recent version is doing nothing to help.
