### ISSUE TITLE
UPX Packed x86/x86_64 EXEs???

### ISSUE THREAD

**Issue by CanadianJeff** [NationalSecurityAgency/ghidra#2501]
I downloaded a program called Romlus Rom Manager ** http://www.mediafire.com/file/l92gdhd44g7ghbp/Romulus048.zip/file ** which is compressed in this UPX format
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

Usage: upx [-123456789dlthVL] [-qvfk] [-o file] file..

Commands:
  -1     compress faster                   -9    compress better
  -d     decompress                        -l    list compressed file
  -t     test compressed file              -V    display version number
  -h     give more help                    -L    display software license
Options:
  -q     be quiet                          -v    be verbose
  -oFILE write output to 'FILE'
  -f     force compression of suspicious files
  -k     keep backup files
file..   executables to (de)compress

Type 'upx --help' for more detailed help.

UPX comes with ABSOLUTELY NO WARRANTY; for details visit https://upx.github.io
```
tried to open this in Ghidra and it did not Auto Analyze when it was UPX packed but after I used UPX -d on the EXE it Analyzed just fine

**Comment by ryanmkurtz** [comment]
Are you requesting that Ghidra do a better job of analyzing the entry point/unpacker code, or add support for unpacking UPX prior to analysis?

**Comment by CanadianJeff** [comment]
maybe both?

**Comment by ryanmkurtz** [comment]
Let's focus on the first thing, since there exists a great workaround for unpacking the code (i.e., using the unpacking utility before importing into Ghidra).

When you say it did not Auto Analyze, what do you mean exactly?  I have used Ghidra on packed UPX binaries and it seems to analyze the entry point fine.

**Comment by CanadianJeff** [comment]
I am actually live on twitch right now trying to use Ghidra on this UPX packed EXE @ https://twitch.tv/linux_canadajeff

**Comment by dev747368** [comment]
I'm going to close this.  It sounds like analyzing the unpacked binary works fine.

**Comment by CanadianJeff** [comment]
unpacking outside of ghidra works but not inside of ghidra itself

**Comment by ryanmkurtz** [comment]
Ghidra does not support unpacking...you need to rely on a 3rd party tool for that.

**Comment by CanadianJeff** [comment]
honestly ghidra should warn and tell users that it does not support unpacking I thought this was NSA level tool

**Comment by aerosoul94** [comment]
It would be impractical to support packed binaries. There are too many varieties and even modifications of packers, which is kinda the point of packing in the first place (to obfuscate). You know, you are welcome to write a loader, like many of us have been doing, to support any unsupported binaries. Personally, I'd just simply use upx to unpack it myself.

**Comment by CanadianJeff** [comment]
fair enough
