### ISSUE TITLE
Wrong x86-64 disassembly for memory references with displacement of zero

### ISSUE THREAD

**Issue by gsuberland** [NationalSecurityAgency/ghidra#2504]
**Describe the bug**
When disassembling instructions that have a displacement of zero, e.g. `mov qword ptr [reg+0], reg`, the instruction is incorrectly decoded.

As an example, the bytes `48 89 54 24 00` are decoded as `mov qword ptr [rsp + rsp*0x1], rdx`, when they should be decoded as `mov qword ptr [rsp+0], rdx`.

**Background**

A practical example is as follows:

```
0:  48 83 ec 18             sub    rsp,0x18                   ; LARGE_INTEGER value;
4:  4c 8b c9                mov    r9,rcx
7:  4d 8b 41 18             mov    r8,QWORD PTR [r9+0x18]     ; int* buffer = (int*)Irp->AssociatedIrp.SystemBuffer;
b:  41 8b 08                mov    ecx,DWORD PTR [r8]         ; int address = *buffer;
e:  0f 32                   rdmsr                             ; value.QuadPart = __readmsr(address);
10: 48 c1 e2 20             shl    rdx,0x20 
14: 48 0b d0                or     rdx,rax 
; ++ DECODING FAULT OCCURS HERE IN GHIDRA:
17: 48 89 54 24 00          mov    QWORD PTR [rsp+0x0],rdx    ; *(LARGE_INTEGER*)buffer = value;
1c: 8b c2                   mov    eax,edx
1e: 41 89 00                mov    DWORD PTR [r8],eax 
21: 8b 44 24 04             mov    eax,DWORD PTR [rsp+0x4] 
25: 41 89 40 04             mov    DWORD PTR [r8+0x4],eax 
29: 49 c7 41 38 08 00 00    mov    QWORD PTR [r9+0x38],0x8    ; Irp->IoStatus.Information = 8
30: 00
31: 33 c0                   xor    eax,eax                    ; return 0
33: 48 83 c4 18             add    rsp,0x18
37: c3                      ret
```

**To reproduce**
1. Open an x86_64 binary containing the following instruction bytes: `48 89 54 24 00`.
2. Open disassembly at that instruction.
3. Observe that the instruction is incorrectly decoded as `mov qword ptr [rsp + rsp*0x1], rdx`.

**Expected behavior**
Instruction decoded as `mov qword ptr [rsp+0], rdx`.

**Environment (please complete the following information):**
 - OS: Win10 1909
 - Java Version 14.0.2
 - Ghidra Version: 9.2 (2020-Nov-13 111 EST]

**Comment by GhidorahRex** [comment]
It looks like the sleigh is matching on the wrong modr/m prefix for these instructions. This is an ordering issue in the x86 sleigh module.
