### ISSUE TITLE
Minor: amount of errors in title bar is always appended

### ISSUE THREAD

**Issue by justanotheranonymoususer** [NationalSecurityAgency/ghidra#2506]
**Describe the bug**
A window with errors gets updated, but the title always has the counter added near the end one. See screenshot.

**To Reproduce**
I used a buggy script.

**Expected behavior**
The title is replaced with a fresh counter each time.

**Screenshots**
![image](https://user-images.githubusercontent.com/5781692/99738546-65d73200-2ad3-11eb-873e-6d4d8adfcebe.png)

**Environment (please complete the following information):**
 - OS: Win10
 - Java Version: 
 - Ghidra Version: 9.2

**Comment by ghidra1** [comment]
Corrected for Ghidra 9.2.3
