### ISSUE TITLE
Architecture-specific instruction information

### ISSUE THREAD

**Issue by find0x90** [NationalSecurityAgency/ghidra#251]
I've been looking around through the Java API documentation as well as the provided scripts and the included source code and I have some questions about what information is available from an instruction, specifically for x86_64 but it would be helpful if there was a generic way to do this for any architecture. 

I'd like to be able to determine programmatically which registers an instruction interacts with and how it does so. This seems mostly answerable using the Instruction, InstructionPrototype, PcodeOp, and Varnode classes. You can easily retrieve for each instruction operand if a register is directly read or written to and which flags in RFLAGS are updated. But I don't see a straightforward way to tell if a register is used in an address calculation. If you already know that an instruction involves an address calculation, it's easy to retrieve the base and index but only if you already have that information. Pcode seems like a potential way to figure this out but I'm not sure I really understand it well enough get that information from it. 

I also want to see if an instruction interacts with RIP in any way. Again, answerable in a roundabout way but I was wondering if there was a way to see if an instruction reads from RIP and/or if it changes RIP. Once again, I thought this might be answerable with Pcode but it looks like for both relative jmp/call instructions and relative mov/lea instructions, that information is lost when machine code is converted to Pcode and an absolute address is used. Obviously, if the Pcode op type is BRANCH/BRANCHIND, CBRANCH, CALL/CALLIND or RETURN, that tells you that it changes RIP but it doesn't tell you if RIP was used to calculate the new value.

I expect there's an easy way to do this. The fact that relative jmp/call instructions resolve cross-references correctly means that the information must be there, I just can't find it. If I can't get a direct answer to these questions, even where to look in the source code for examples would be helpful.

**Comment by caheckman** [comment]
The getPcode() method on an Instruction object (the one that takes no parameters) returns a complete description of the instruction as an array of PcodeOp objects. Inspecting the Varnode inputs and output of each PcodeOp should reveal registers involved in all aspects of the instruction, including an address calculation. The description should be complete up to what's included in the SLEIGH specification for the processor. Take a look at the MarkCallOtherPcode.java script for a simple example of using getPcode().

The RIP register (as with the program counter register for any processor) unfortunately tends to be "special" in that spec designers don't model it directly because the control-flow of p-code itself indirectly models it. You can always search for the branch PcodeOp instructions to figure out the possible ways the program counter might change, and fall-through semantics of course indirectly make use of the previous value of the program counter. But there currently isn't an easy way to determine if a branch is relative or not. In theory, you could walk through the SLEIGH parse for the instruction and look for references to StartSymbol and EndSymbol (see SleighDebugLogger for a non-trivial example), but this seems like it might be more trouble than its worth.

**Comment by find0x90** [comment]
I'm taking a closer look at the PcodeOp objects and you're right, the instruction is completely described and it should be possible to find address calculations and which registers are used specifically for that. Looking for LOAD/STORE operations and seeing if their pointer arguments are generated based on a register should be enough for what I want to do. 

For finding RIP-relative operations, I think I'll probably use Capstone since it has Java bindings so it won't be too difficult to use alongside Ghidra. Ideally, I would like to do everything with Ghidra's scripting API but I agree that parsing the SLEIGH files seems like it's probably more effort than it's worth, especially since I know Capstone does exactly what I want. 

As a last ditch effort to do this entirely with Ghidra, where would be a good place to start looking in the source/scripts at how cross-references and Pcode operations are constructed from the machine instructions? I realize that is a pretty big question. I'm sure the conversion of machine instructions -> user friendly representation isn't easily described. So far what I've been doing to figure out the API is finding a class in the documentation I think might be helpful and then searching the scripts and unzipped source files for "new ClasImInterestedIn" and seeing how it's used. That's mostly been enough to get started but sometimes it doesn't get me anywhere so any pointers would be appreciated. 

Thanks for the help!

**Comment by emteere** [comment]
You could change the definitions for the operations in sleigh that are PC relative to include a read of the PC.  Then your analysis can look for a read of the PC.  For writes to the PC, you can make sure the PC register is used as the variable for the goto [PC].  When I write a language, I tend to assign to the PC, and then use the value in the PC as the target for this type of situation.

The current spec's are defined to use a constant value whenever possible and the PC is a known constant when the instruction executes.  In most cases this is fairly easy to find.  They will have inst_next inside [] to compute the RIP.

A good example in X86 is:
addr64: [riprel] is mod=0 & r_m=5; simm32 [ riprel=inst_next+simm32; ] { export *[const]:8 riprel; }

Could be changed to:
addr64: [riprel]  is mod=0 & r_m=5; simm32 [ riprel=inst_next+simm32; ] { local tmp:8 = RIP + simm32; export *[const]:8 riprel; }

Not sure it is worth the pain, but it would get you what you need.

**Comment by find0x90** [comment]
That is exactly what I need. Unfortunately, I don't think it's worth me keeping a separate version of the x86_64 spec around just for this. If I got something like this working would it be possible to merge it into the main x86_64 spec? I'm not sure it's a good idea to make changes to it just to serve my purposes but on the other hand it's not like the changes would be any less correct, just more explicit. I also don't know if it would impact existing code analysis in a negative way. When I tried the change you suggested everything looked normal except I was able to see RIP as an input to the PcodeOp. I'd be happy to work on it if there's a chance of it being accepted but if not, I'll probably just use Capstone.

**Comment by emteere** [comment]
We'll have to think about it.  It does generate more pcode to clean out, but it should have little real effect.

I don't think there would be too many locations that would be effected.

There are many PC relative instructions like relative branches. Do you need those annotated with the PC as input?

**Comment by find0x90** [comment]
Yes, ideally I would like any instruction that uses RIP to be explicitly dependent on it and show it as an input object like any other register, including branches. I can go through the processor specification and see if I can make the changes I need while not obviously breaking anything. When I'm done I'll post it here and get some feedback. It looks like it will just be changing the inst_next calculations with PC and moving it from the disassembly actions section to the semantic section. 

Another thought, I've been focused on changing the instruction definitions to use RIP/EIP/IP but it would also be fine to see that inst_next is used. Could I just move the "riprel=inst_next+simm32;" from the disassembly actions section to the semantic section? Or would the Pcode generation have an issue with exposing a non-architectural, predefined symbol as an input object?

**Comment by emteere** [comment]
Not really because the actions area will actually compute a constant value and export a constant address.  The changes I made were more semantic dead code, just so you could see the PC was set.
The branches can be computed, however that is extra computation that is always constant.  It could cause alot of extra work if one were using the pcode for theorem proving.

I had thought about an additional method on InstructionPrototype that could return if inst_next was used in the disassembly actions.  The use of inst_next doesn't always mean the PC was used as part of the calculation.  It can be used in conditional or looping flows to get to the next fall-through instruction.

Another possiblilty is an ifdef around this added semantic code if it is finally deemed objectionable to have the code in all the places you need it.

**Comment by find0x90** [comment]
Actually having a method like that on InstructionPrototype would probably be enough for me. If the instruction doesn't use inst_next it can't be relative. If the instruction uses inst_next and the pcode contains any branch/call operations to any non-fall-through flows, it's a relative branch instruction. It will be a little tricky distinguishing relative mov/lea instructions from REP prefixed instructions since they are both fallthrough but both use inst_next. But if I understand how that's implemented in pcode, REP prefixed instructions will have both a cbranch op to the fallthrough and a branch op to the current instruction address while mov/lea obviously won't have any branch/cbranch instructions. Finally, cmov instructions are a problem because they can both use inst_next to conditionally branch to the fall-through but they can also use it for a RIP-relative data access. One hacky way around that would be to subtract the data access address from the address of the next instruction and if you can find the result encoded in the instruction bytes as a 16-bit/32-bit little-endian signed immediate then it's very likely a RIP-relative instruction. 

If those are the only edge cases I think a usesInstNext() method would fine for my purposes. Are there any other potential edge cases you can think of that use inst_next? That sounds like it would work to me but I'm not familiar enough with Sleigh to be sure.

**Comment by emteere** [comment]
If the computation with inst_next is in the semantic pcode section, it would be easy to see how it is used.  A direct goto to handle the fall-thru is not PC relative.  It would need to be used as part of a computation.  The tricky part is knowing that it is used in the [action] section and the use of inst_next is not in the actual value, only the final constant value.  That would be possible to do as @caheckman mentioned previously.

**Comment by find0x90** [comment]
Sorry I think I misunderstood a couple things. 

It is possible to move the inst_next calculation to the semantic section without having that performance cost you mentioned? Or was that cost a result of using RIP directly? 

Also, I didn't realize that the SleighinstructionPrototype would actually give me access to inputs such as inst_next. Is that class already capable of giving me the information I need? Or would it only work after some changes?

**Comment by find0x90** [comment]
Any update on this? I think adding a usesInstNext() function would work for me.
