### ISSUE TITLE
Decompiler plugin persistent X key binding

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#2519]
**Describe the bug**
x is bound to the Decompiler (DecompilePlugin) action and this persists when Ghidra is reopened, even after being changed to something else explicitly. This is rather frustrating as I find myself changing the key from something like ctrl+alt+e to ctrl+alt+f each time I reopen ghidra to force the binding temporarily.

Appears to be related to https://github.com/NationalSecurityAgency/ghidra/issues/1681, which also seems to be back to play :(

**To Reproduce**
edit> tooloptions > key bindings: bind decompiler to something other than X
close and reopen Ghidra, saving tool settings if necessary
observe that the decompiler action is still bound to X

As a sidenote, while having the screen spin around when using listing action from listing is funny and all that, I would much prefer to be able to bind the listing and decompiler actions to the same key and toggle quickly between the two without having to select from a popup. Ideally listing action should only be selectable from outside the listing and similarly for the decompiler action

**Environment (please complete the following information):**
Ghidra 9.2

**Comment by dragonmacher** [comment]
Hey @sad-dev, there is a lot to unpack here, here it goes:

> x is bound to the Decompiler (DecompilePlugin) action and this persists when Ghidra is reopened, even after being changed to something else explicitly. This is rather frustrating as I find myself changing the key from something like ctrl+alt+e to ctrl+alt+f each time I reopen ghidra to force the binding temporarily.

I just verified that I can reassign the Decompiler provider's keybinding via the `Window` menu and it persists until the next launch of Ghidra.   I also tried changing the binding using the steps you mentioned and it worked as expected.

> As a sidenote, while having the screen spin around when using listing action from listing is funny and all that,

In addition to being funny, this actually serves the purpose of identifying an already open widget that the user did not notice.   There is an option in the Front End tool to disable animations.   However, *I just verified that this particular animation is not honoring this option*    This is a bug that we will fix.

> I would much prefer to be able to bind the listing and decompiler actions to the same key and toggle quickly between the two without having to select from a popup. 

Unfortunately, we do not have any notion of a sharable/togglable provider keybinding.   We do have an action that will show the last used provider.  If you are usually switching back and forth between just these 2 providers, then this action will work for you in this case.   The action is listed in the keybindings options:

    `Go To Last Active Component | Ctrl-F6 | ProviderNavigationPlugin`


> Ideally listing action should only be selectable from outside the listing and similarly for the decompiler action

I assume you mean that you would like the 'show listing action' to do nothing if the listing is already active?   The only problem with this is that it would disable the above mentioned feature of any provider highlighting itself in case the user does not see it.

**Comment by sad-dev** [comment]
I gave the Last Active Component a try but it didn't seem to navigate between them consistently based on my usual usage patterns. Coming from IDA, I'm accustomed to the tab key toggling between disassembly/decompiler. I have bound my decompiler/listing actions to adjacent keys for now, which (non persistence issues aside) is 'good enough' for me.

I am not too familiar with the source code for PluginActions. If something like
```
	@Override
	public boolean isValidContext(ActionContext context) {
		return (context instanceof DecompilerActionContext || context instanceof ListingActionContext) 
	}
```
is viable, then I'll put in a separate feature request

**Comment by dragonmacher** [comment]
I'm attaching a script that will toggle between the 2 providers each time it is run.   With that being said, the script exposes a small defect in Ghidra, whereby the script takes 1 full second to run, which it should not.  Thus, the script will probably be too slow to be useful until the bug fix goes in.

[ListingDecompilerToggleScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/5618344/ListingDecompilerToggleScript.java.txt)

**Comment by sad-dev** [comment]
@dragonmacher 
I did the following:
1.) Downloaded 9.2.1
2.) deleted the old .ghidra folder
3.) Moved the decompiler binding from ctrl+e to ctrl+shift+y
4.) Added my script and bound it to x
5.) Hitting x still results in the select action dialog between Decompiler and my script.

**Comment by sad-dev** [comment]
I downloaded 9.2.1, cleared my .ghidra folder, and am still observing the X key rebinding to the decompiler after re-opening Ghidra

**Comment by dragonmacher** [comment]
I just tried this and am not seeing the issue.  This  is what I did to test:

1. Open a Ghidra Code Browser tool
2. From the Window menu, hover over 'Decompile'
3. Press F4
4. Change the keybinding (I chose Ctrl-Shift-Y)
5. Close Ghidra *by closing the Front End tool*
6. Re-open the Code Browser tool 


The binding persisted for me as expected.   I verified it was written into the tool file as well.   Open: 
`<user home>/.ghidra/.ghidra_version/tools/_code_browser.tcd`

That file should contain an entry for your binding, mine is:
```         
 <WRAPPED_OPTION NAME="Decompiler (Shared)" CLASS="ghidra.framework.options.WrappedKeyStroke">
         <STATE NAME="KeyCode" TYPE="int" VALUE="89" />
         <STATE NAME="Modifiers" TYPE="int" VALUE="195" />
 </WRAPPED_OPTION>
```

**Comment by sad-dev** [comment]
I was doing 
5. Close the Code Browser Tool
6. Close the Front End tool
7. Reopen the front end tool and then the code browser tool.

I was able to get the binding to persist with your steps. In either case, the bindings will be written to code_browser.tcd

**Comment by sad-dev** [comment]
In full, the steps I did were:

1.) Delete the .ghidra folder
2.) Open Ghidra, accept the license agreement, and open the Code browser tool
3.) Bind a script to the X key
4.) Change the binding of decompiler from Ctrl+E (the default) to Ctrl+Shift+Y
5.) Close Code Browser
6.) Close the Front End tool
7.) Reopen both
8.) Pressing X leads to a dialog asking to choose between your script and the decompiler

**Comment by dragonmacher** [comment]
I just performed your steps and it worked correctly.    

The contents of `_code_browser.tcd` now contains these entries for my options:
```
        <OPTIONS>
            <CATEGORY NAME="Listing Fields">
                <WRAPPED_OPTION NAME="Cursor Text Highlight.Highlight Color" CLASS="ghidra.framework.options.WrappedColor">
                    <STATE NAME="color" TYPE="int" VALUE="-6710785" />
                </WRAPPED_OPTION>
            </CATEGORY>
            <CATEGORY NAME="Key Bindings">
                <WRAPPED_OPTION NAME="ProgressExampleScript.java (GhidraScriptMgrPlugin)" CLASS="ghidra.framework.options.WrappedKeyStroke">
                    <STATE NAME="KeyCode" TYPE="int" VALUE="88" />
                    <STATE NAME="Modifiers" TYPE="int" VALUE="0" />
                </WRAPPED_OPTION>
                <WRAPPED_OPTION NAME="Decompiler (Shared)" CLASS="ghidra.framework.options.WrappedKeyStroke">
                    <STATE NAME="KeyCode" TYPE="int" VALUE="89" />
                    <STATE NAME="Modifiers" TYPE="int" VALUE="195" />
                </WRAPPED_OPTION>
            </CATEGORY>
            <CATEGORY NAME="Decompiler">
                <WRAPPED_OPTION NAME="Display.Color for Current Variable Highlight" CLASS="ghidra.framework.options.WrappedColor">
                    <STATE NAME="color" TYPE="int" VALUE="-10066177" />
                </WRAPPED_OPTION>
            </CATEGORY>
        </OPTIONS>
```

The items of interest here are the 2 key bindings.  What do you now have?

**Comment by sad-dev** [comment]
```
        <OPTIONS>
            <CATEGORY NAME="Key Bindings">
                <WRAPPED_OPTION NAME="Decompiler (Shared)" CLASS="ghidra.framework.options.WrappedKeyStroke">
                    <STATE NAME="KeyCode" TYPE="int" VALUE="89" />
                    <STATE NAME="Modifiers" TYPE="int" VALUE="195" />
                </WRAPPED_OPTION>
            </CATEGORY>
        </OPTIONS>
...
        <PLUGIN_STATE CLASS="ghidra.app.plugin.core.script.GhidraScriptMgrPlugin">
            <ARRAY NAME="BundleHost_FILE" TYPE="string">
                <A VALUE="$GHIDRA_HOME/Features/VersionTracking/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Features/Python/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Features/Base/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Processors/8051/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Features/FileFormats/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Processors/PIC/ghidra_scripts" />
                <A VALUE="$USER_HOME/Desktop/ghidra-test-scripts" />
                <A VALUE="$USER_HOME/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Features/GnuDemangler/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Features/Decompiler/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Features/BytePatterns/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Processors/DATA/ghidra_scripts" />
                <A VALUE="$GHIDRA_HOME/Features/FunctionID/ghidra_scripts" />
            </ARRAY>
            <ARRAY NAME="Scripts_Actions_Key" TYPE="string">
                <A VALUE="$USER_HOME/Desktop/ghidra-helper-scripts/DecompilerX.java" />
            </ARRAY>
            <ARRAY NAME="BundleHost_ACTIVE" TYPE="boolean">
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="true" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="false" />
            </ARRAY>
            <STATE NAME="DEFAULT_FONT_NAME" TYPE="string" VALUE="monospaced" />
            <ARRAY NAME="BundleHost_SYSTEM" TYPE="boolean">
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="false" />
                <A VALUE="false" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
            </ARRAY>
            <STATE NAME="DecompilerX.java" TYPE="string" VALUE="X" />
            <STATE NAME="DEFAULT_FONT_SIZE" TYPE="int" VALUE="12" />
            <STATE NAME="DEFAULT_FONT_STYLE" TYPE="int" VALUE="0" />
            <ARRAY NAME="BundleHost_ENABLE" TYPE="boolean">
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
                <A VALUE="true" />
            </ARRAY>
            <STATE NAME="DESCRIPTION_DIVIDER_LOCATION" TYPE="int" VALUE="545" />
            <STATE NAME="FILTER_TEXT" TYPE="string" VALUE="" />
        </PLUGIN_STATE>
```

**Comment by dragonmacher** [comment]
The interesting thing there is that you do not have the script's binding saved in the `<OPTIONS>` element.   It is not clear why my file has it and yours does not.     I tried editing my file remove the options' script entry, but I still did not see the problem.

Here is my guess: you are getting a conflict with the value of the script keybinding that is saved in the options and that which is defined in the header of `DecompilerX.java`.    Does that script's header metadata define a keybinding?

**Comment by sad-dev** [comment]
The script's header metadata does not (and neither do any of the scripts in the folder) define a keybinding

```
// This is IDA X
//@category My_Scripts
import ghidra.app.script.*;
...
public class DecompilerX extends GhidraScript {
...
}
```

**Comment by sad-dev** [comment]
I tried again and observed the following:

1. delete .ghidra and open fresh code browser
2. add a folder to scripts and bind DecompilerX.java to "X"
Pressing X pops up dialog for both the DecompilerX.java script and the Decompiler action

**Comment by dragonmacher** [comment]
> Renaming the script to NotDecompilerX.java does not trigger the bug

Wow.   I entertained that notion for a second, but figure that couldn't be it.   I can try making a script with that same name.

**Comment by dragonmacher** [comment]
I was able to reproduce it using that name.   I cannot even imagine how this is happening.  I will update when I find out.

**Comment by dragonmacher** [comment]
Seems like a simple enough coding mistake.  This:

```
if (!optionName.startsWith(getName())) {
    return; // not my binding
}
```

should have been this:

```
if (!optionName.equals(getFullName())) {
    return; // not my binding
}
```

When the script's binding was applied, a listener was then applying that change to the 'Decompiler' action as well, since it's option name started with the script name.

Thanks for the debugging help!
