### ISSUE TITLE
Issue in char[] conversion

### ISSUE THREAD

**Issue by lucasamp94** [NationalSecurityAgency/ghidra#2527]
![IMG_2339](https://user-images.githubusercontent.com/62544838/100382859-885dd380-301c-11eb-9fa3-b3cd11541766.jpeg)
Hi, I have an issue while I’m trying to convert in char[](see images)
Instead of having char[] LE “john”, I can convert in char[] “nhoj”.
Someone know how to fix it?

**Comment by dev747368** [comment]
right now this is by design (treating it as big endian).  In some use cases cases this matches what the user needs, and in some cases its not matching what you need.
