### ISSUE TITLE
Ghidra on M1 Mac?

### ISSUE THREAD

**Issue by pwmoore** [NationalSecurityAgency/ghidra#2533]
I'm wanting to get one of the new Apple Silicon Macs, but Ghidra is one of my most used applications, so I don't want to make the switch until I know it works well. I know Ghidra is mostly Java, but IIRC the decompiler is x86 so that would have to be rebuilt. Does Ghidra run well on the M1, either natively or via Rosetta 2? Or if not, are there plans to support it?

**Comment by ryanmkurtz** [comment]
I heard from someone that Ghidra runs on the M1 mac.  The existing decompiler seems to run fine under Rosetta 2.

**Comment by pwmoore** [comment]
Good enough for me, thanks!

**Comment by tomnelson** [comment]
[https://github.com/NationalSecurityAgency/ghidra/pull/2644](https://github.com/NationalSecurityAgency/ghidra/pull/2644)
