### ISSUE TITLE
Make DWARFSectionProvider an extension point

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2535]
**Describe alternatives you've considered**
Add more to `DWARFSectionProviderFactory.sectionProviderFactoryFuncs` via reflection.

**Comment by dev747368** [comment]
maybe.  what did you run into?

**Comment by astrelsky** [comment]
> maybe. what did you run into?

It would just make sense if a non standard binary format used dwarf.

The main reason I would need to is related to #2318 and to avoid a NPE in my solution. I'm dealing with a non standard elf format which, iirc, its dynamic table reports its offset as 0. This causes the ElfHeader to ignore it so the dynamicTable is null and somewhere in the process of running the DWARF analyzer I get a NPE.

As can be seen above I really didn't put too much thought into it. It just seems to me to be something that should be an ExtensionPoint unless someone wishes to rewrite all of the dwarf classes to support another format. (Or just go nuts with reflection so it cooperates with ghidra)

**Comment by astrelsky** [comment]
I'll come back to this and reopen if necessary. I should have waited until I've investigated further before opening.
