### ISSUE TITLE
x86: Refs to data segment aren't recognized

### ISSUE THREAD

**Issue by RobertBaruch** [NationalSecurityAgency/ghidra#254]
**Describe the bug**
In many cases, instructions that reference data segment addresses do not result in assigning symbols in the data segment.

**To Reproduce**
1. Decompile TELEN.EXE (from https://www.dosgamesarchive.com/download/telengard)
2. Look at the disassembly at 1000:0177, note that Ghidra has correctly created symbols in the data segment for these instructions.
3. Follow the call that's immediately after, to FUN_1000_ab35.
4. Look at the disassembly at 1000:ab3b, note that this is a DS access, but Ghidra has not assigned a symbol for it.
5. Attempt to create a symbol for it in the data segment. Note that Ghidra does not apply the symbol to the instruction.

**Expected behavior**
Ghidra should recognize accesses to the data segment.

**Screenshots**
Screenshots of the above steps to reproduce the behavior:

![yes_ds](https://user-images.githubusercontent.com/1783950/54883009-c2c1a700-4e1d-11e9-902a-6697d194bd90.jpg)

![no_ds](https://user-images.githubusercontent.com/1783950/54883010-c81ef180-4e1d-11e9-8942-09469defd84a.jpg)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0
 - Ghidra Version: 9.0

**Comment by Godzil** [comment]
I've also noted in real mode x86 on my own project that sometimes Ghidra seems to ignore the value of DS/ES when trying to figure where an offset it, even when the value of DS/ES is forced and need in that case to change by hand the reference which is a bit annoying. (also Ghidra alway resolve an address to a linear one, then convert it again to seg:offset, so thing like FD90:0000 will be transformed into F000:D900 which make us to loose some information, but that's a different problem will open an issue about that)

**Comment by emteere** [comment]
Set the ES, DS registers at the beginning of the function, or across a selection.  They are used in the address calculation.

```
       14000 a0 0f 00        MOV        AL,[0xf]
                                           $U1350:8 = CALLOTHER "segment", DS, 15:2
                                           $U1360:1 = LOAD ram($U1350)
                                           AL = COPY $U1360
```
This will affect the decompiler, and the reference creation if you re-analyze.  Ghidra could assume the ES,DS value, but they may not be correct if set outside the function.  The references created in the listing might still need some work, but hopefully will be closer to what you want.

**Comment by Godzil** [comment]
I don’t have the project with me at the moment so can’t check, but on code I know to have a specific DS value, I forced the whole segment with DS at that value and there are still occasion where it try to reference far pointer with DS==0.

BUT as it was already analysed code it may have not updated the ref, so maybe it would need to rerun the analysis, but I’m afraid to loose some of the change I’ve made by hand to point certain non trivial things to the correct value.

Aka I don’t know if the tool knows which ref was automatically generated and can override them and one set by hand

**Comment by RobertBaruch** [comment]
I selected the entire program and set DS to the right value. It fixed up a bunch of things.

However, now I have two issues that are somewhat related to DS and pointers, but might be considered separate bugs or help requests :) The first issue is that it doesn't look like near pointer arguments in functions can have their segment specified. Instead, it seems to assume the near pointers are to the CS segment. That's not completely unreasonable, because they could be pointers to any segment, but I'd like to at least get the chance to say which segment they are for.

Here's one example:

![ds1](https://user-images.githubusercontent.com/1783950/55271127-34a65000-5265-11e9-8b19-026e11cec6c1.JPG)

![ds2](https://user-images.githubusercontent.com/1783950/55271136-543d7880-5265-11e9-9bad-214517fb893f.JPG)


The second issue is that the [SI + disp] indexed displacement addressing mode seems to default to the interpretation that SI is a base address, and disp is some offset. While really, SI (and DI) are probably most often used as offsets (i.e. index) and the disp is the base of an array. I'd like to at least have the choice of interpretation, otherwise the code becomes less readable, and you don't get the opportunity to use nice data segment labels for the arrays.

![si_addrmode](https://user-images.githubusercontent.com/1783950/55271246-cd899b00-5266-11e9-9d44-90019a5570ad.JPG)

**Comment by Godzil** [comment]
The problem is linked with an enhancement I've submitted ( #199 ), Ghidra don't understand the notion of near and far tainted pointer, so any native pointer is just a near pointer (16bit), and the only way around is to use the built-in "pointer32" but even there you loose other information like what is the type so that's a bit useless in the end.


And I do agree with SI/DI, and your interpretation makes even more sense when you thing about x86 instruction like `MOVSx` / `STOSx` expecially linked with the `REPx` prefix. DI and SI are both incremented.
And well `I` for both mean `index` not `base` :)

**Comment by sirus20x6** [comment]
> I selected the entire program and set DS to the right value

How is this done? I'm not following
