### ISSUE TITLE
nitpic: doc formatting: italics in a plain-text document?

### ISSUE THREAD

**Issue by theorbtwo** [NationalSecurityAgency/ghidra#2540]
https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Framework/SoftwareModeling/data/languages/Steps%20to%20creation%20of%20Format%20Opinion.txt#L5

Terribly minor, but this file says that the attributes listed in italics are optional.  Sadly, it is a plain-text file, so has no way of expressing italics.  Does it mean those in parentheses (which would be all of them)?  It appears this was copy-and-pasted from something like a .doc file, since it also uses "smart quotes" in XML.

**Comment by ryanmkurtz** [comment]
This file is ancient...it should just be deleted.
