### ISSUE TITLE
Java JDK Not Found by Ghidra

### ISSUE THREAD

**Issue by lyellread** [NationalSecurityAgency/ghidra#2543]
- Windows 10 Pro 20H2, 19042.630
- Ghidra 9.2
- Java JDK 11.0.9

Java is installed:

```
C:\Users\username>java --version
java 11.0.9 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)
```

It's in path:

```
C:\Users\username>echo %PATH%
...;C:\Program Files\Java\jdk-11.0.9\bin;...
```

But Ghidra does not find it:

```
C:\Users\username\Desktop\ghidra>ghidraRun.bat                                                                        
LaunchSupport expected 2 to 4 arguments but got 1                                                                       
LaunchSupport expected 2 to 4 arguments but got 1                                                                       
LaunchSupport expected 2 to 4 arguments but got 1                                                                                                                                                                                               Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section.               
```

Has anyone encountered a fix for this? 

Cheers! 

~Lyell

**Comment by ryanmkurtz** [comment]
Is this a version of Ghidra you downloaded from ghidra-sre.org?

**Comment by lyellread** [comment]
> Is this a version of Ghidra you downloaded from ghidra-sre.org?

Yes, the link on the home screen of that site

**Comment by tomnelson** [comment]
The first place I would look is at the space between 'Program Files' in your PATH
Maybe putting it in quotes or using the short name:
C:\Progra~1\Java\jdk-11.0.9\bin
would help...

**Comment by Wall-AF** [comment]
The space doesn't matter on my Windows setup.  However, have you setup your `JAVA_HOME` like:
`JAVA_HOME=C:\Program Files\Java\jdk-11.0.9`
without the `\bin`!

**Comment by lyellread** [comment]
> The space doesn't matter on my Windows setup. However, have you setup your `JAVA_HOME` like:
> `JAVA_HOME=C:\Program Files\Java\jdk-11.0.9`
> without the `\bin`!

Just set this, rebooted, it persisted, still Ghidra will not run.

**Comment by lyellread** [comment]
> The first place I would look is at the space between 'Program Files' in your PATH
> Maybe putting it in quotes or using the short name:
> C:\Progra~1\Java\jdk-11.0.9\bin
> would help...

I tried this in both `JAVA_PATH` and `Path` and this did not change the symptoms. 

Also, I bumped the `jdk` path up to the first position in the `Path`, and still nothing.
