### ISSUE TITLE
Can't install GhidraSleighEditor Eclipse plugin in macOS

### ISSUE THREAD

**Issue by bikeNomad** [NationalSecurityAgency/ghidra#2549]
**Describe the bug**
When I try to install the GhidraSleighEditor Eclipse plugin, I am unable to select the editor for installation.
Where there should be a Ghidra category, instead I see only "There are no categorized items".
I was able to install the GhidraDev plugin successfully in this Eclipse instance.

**To Reproduce**
 1. Start an instance of Eclipse IDE for GNU ARM & RISC-V C/C++ Developers (2019-09)
 2. Help/Install new software/Add.../Archive.../select GhidraSleighEditor-1.0.0.zip
 3. observe that there is no way to select this plugin for installation

**Expected behavior**
I expected to be able to select this plugin for installation as I was able to install the GhidraDev plugin in this way.

**Screenshots**
![sleigh_editor_install_problem](https://user-images.githubusercontent.com/99482/101396358-0bcebe80-3880-11eb-9cf8-00601d419612.png)

**Attachments**
I've attached a screenshot of the resultant dialog, and a dump of my Eclipse configuration.
[sleigh_editor_install_problem_configuration.txt](https://github.com/NationalSecurityAgency/ghidra/files/5654867/sleigh_editor_install_problem_configuration.txt)

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Java Version: 11.0.2
 - Ghidra Version: 9.2 PUBLIC
 - Eclipse: Version: 4.13.0.v20190916-1323 (2019-09)

**Comment by emteere** [comment]
When you go to import the SleighEditor, uncheck the box towards the bottom "Group items by category".
We'll need to fix that so the editor has a category.

**Comment by bikeNomad** [comment]
Thanks!
