### ISSUE TITLE
Mismatched pattern sizes -- 2 vs 1: for table "instruction" constructor

### ISSUE THREAD

**Issue by ikuyas** [NationalSecurityAgency/ghidra#2553]
I'm trying to define new operation as follows:
```
#Bcond adr17 - 00000111111Dcccc|ddddddddddddddd1`
:b^c0003 adr17 is op0515=0x03f & c0003 & adr17    <= line 51 in Special.sinc
```
adr17 in Extras.sinc 
```
adr17: res is s0404; op1731 & op1616=1
[ res = ((s0404 << 16) | (op1731 << 1)) + inst_start; ]
{
      export *:4 res;
}
```
I'v got the following error from sleigh.
```
Error: Mismatched pattern sizes -- 2 vs 1: for table "instruction" constructor from Special.sinc:51
```
What should I fix ? 
What does the "2 vs 1" means?

**Comment by mumbel** [comment]
Think you want to look into using `...` for including the adr17 bit pattern so Bcond knows it reads from this token and the next

**Comment by ikuyas** [comment]
Thank you very much.
I followed your advice and modified the following and it worked without error. Thanks again.
```
:b^c0003 adr17 is (op0515=0x03f & c0003) ... & adr17
```
