### ISSUE TITLE
PE format delay-load imports

### ISSUE THREAD

**Issue by anastmag** [NationalSecurityAgency/ghidra#2554]
**Is your feature request related to a problem? Please describe.**
Ghidra doesn't resolve delay-load imports on PE binaries. 

**Describe the solution you'd like**
Will you accept any pull requests that resolve delay-load imports or you're not planning to add support for that?
I guess it can be done during the initial analysis, although detecting delay-load structures is not perfect.

**Describe alternatives you've considered**
An alternative solution will be to add a script that does it.

**Additional context**
This is the actual call of the delay loaded function
![pic1](https://user-images.githubusercontent.com/1755995/101912121-00ee9380-3bca-11eb-9e05-db1218548b13.png)

This is the memory contents
![pic2](https://user-images.githubusercontent.com/1755995/101912138-051ab100-3bca-11eb-84dc-1abdf3411d9c.png)

Which point into this function that overwrites the contents of the address at 0x1800e0f90
![pic3](https://user-images.githubusercontent.com/1755995/101912150-08ae3800-3bca-11eb-95db-2c8ba53392ce.png)

**Comment by anastmag** [comment]
I can work on this if you don't mind

**Comment by tnrn9b** [comment]
I've submitted a merge request that handles delayed imports. tnrn9b:Delay-load-imports
