### ISSUE TITLE
Download PDB as part of analysis

### ISSUE THREAD

**Issue by justanotheranonymoususer** [NationalSecurityAgency/ghidra#2556]
**Is your feature request related to a problem? Please describe.**
To analyze a binary with PDB that I'd like to download from a symbol server, I do the following steps:
1. Import the binary to workspace.
2. Open the imported binary.
3. When asked about analysis, decline, since I don't have the PDB yet.
4. Use File -> Download PDB File...
5. Analyze.

**Describe the solution you'd like**
I want to be able to say yes in step 3, and have the analysis download the PDB for me, just like it loads an already existing one.

**Describe alternatives you've considered**
Doing the clumsy steps I'm already doing.

**Additional context**
Maybe like this:
![image](https://user-images.githubusercontent.com/5781692/102015260-16e38c00-3d63-11eb-889c-90c076645375.png)

**Comment by dev747368** [comment]
This functionality is now available in commit 22675e9f39dd23bb1f0df775ef3cc2c8f22e81a7, and you should see it in the 10.0 release.
