### ISSUE TITLE
Low-level Error: Flow exceeded maximum allowable instructions

### ISSUE THREAD

**Issue by xmaple555** [NationalSecurityAgency/ghidra#2557]
i have got a problem

![螢幕擷取畫面 (82)](https://user-images.githubusercontent.com/54590608/102022805-2b0ba580-3dc4-11eb-9bb7-9fe411fa595b.png)

i have check about tool option ,but still not find relevant about maximum instruction  or max_insn,
does anyone know how to fix it? 
thank in advance

**Comment by mrexodia** [comment]
There is some code that allows you to customize the `max_instructions` of the decompiler (which causes this error): https://github.com/NationalSecurityAgency/ghidra/blob/2b08598dbabe6a9c911e712bd928e5f84fb00ee8/Ghidra/Features/Decompiler/src/decompile/cpp/options.cc#L822 no idea how to set that option though.

**Comment by mrexodia** [comment]
Awesome, thanks a lot!

**Comment by Nambers** [comment]
For later viewers, you can change the limit under `Edit -> Tool Options` and
![image](https://github.com/user-attachments/assets/a01bfda3-3568-4a98-8252-72317ee7ce4a)
