### ISSUE TITLE
ARM: Incorrect disassembly of some thumb2 bl instructions as vst4.x in Ghidra 9.2

### ISSUE THREAD

**Issue by reedmideke** [NationalSecurityAgency/ghidra#2559]
**Describe the bug**
Ghidra 9.2 disassembles thumb2 bl <negative offset around 0x3xxxxx> as vst4.x and adds warning bookmark
"Instruction pcode is unimplemented"

Ghidra 9.1.2 and other disassemblers correctly disassemble the same code as bl

**To Reproduce**
 - Use the attached .o file or compile the .S to .o with arm gcc (I verified the test case using 4.9.3, but it should work in anything that understands the assembly syntax)
`arm-none-eabi-gcc -c -march=armv7-a -o ghidra-bl-bug.o ghidra-bl-bug.S`
 - Import the .o file in Ghidra, accept default options
 - Open and analyze with default options

**Expected behavior**
The disassembly at 0034301e should be
`0034301e cc  f4  ef  ff    bl         bl_target`

not
`0034301e cc  f4  ef  ff    vst4.64    {d31 [],d1[],d3[],d5[]},[r12 ]`

**Attachments**
Attached file is a zip with source and .o file of a minimal test case to reproduce the issue.
[ghidra-bl-bug.zip](https://github.com/NationalSecurityAgency/ghidra/files/5692137/ghidra-bl-bug.zip)

**Environment:**
 - OS: Windows 10
 - Java Version: 11.0.2
 - Ghidra Version: 9.2 public release

**Additional context**
I haven't determined the exact bit pattern that triggers the problem, but it seems to happen for a wide range around -0x3xxxxx.

Ghidra defaults to loading the .o as armv8le (likely related to #1521), but the disassembly is the same if you force armv7le to match the -march option.

**Comment by emteere** [comment]
Does look like a copy/paste problem. I've accepted and committed the PR. Good find and diagnosis.

**Comment by ghidra1** [comment]
Corrected for 9.2.2 release
