### ISSUE TITLE
Ghidra 9.2 HeadlessScript not working

### ISSUE THREAD

**Issue by Martyx00** [NationalSecurityAgency/ghidra#2562]
**Describe the bug**
After updating to 9.2, my previous headless scripts written in Java no longer work with the following error:

```
ERROR REPORT SCRIPT ERROR: /tmp/hello.java : Failed to find source bundle containing script: /tmp/hello.java (HeadlessAnalyzer) java.lang.ClassNotFoundException: Failed to find source bundle containing script: /tmp/hello.java
	at ghidra.app.script.JavaScriptProvider.loadClass(JavaScriptProvider.java:118)
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:81)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:877)
	at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1039)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1532)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1670)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1735)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:443)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:82)
```

**To Reproduce**
1. Create sample headless script (or use for example `Decompile.java` script from release 9.1.2):
```java
//Hello

import ghidra.app.script.GhidraScript;
import ghidra.app.util.headless.HeadlessScript;

public class Decompile extends HeadlessScript {

	@Override
	public void run() throws Exception {
		System.out.println("HelloWorld!");
	}
}
```
2. Run the headless analysis with a `-postscript` option: `./ghidra_9.2_PUBLIC/support/analyzeHeadless "/tmp/out" "hello_binary" -import "/tmp/hello_binary" -postscript "/tmp/hello.java"`

**Expected behavior**
The script runs as it does in version `9.1.2`.

**Environment (please complete the following information):**
 - OS: `Ubuntu 20.10`
 - Java Version: `openjdk 11.0.9.1`
 - Ghidra Version: `9.2`

**Comment by dev747368** [comment]
I'm not an authority on scripting issues, but just wanted to make sure that your example "hello.java" script had "public class hello" inside of it instead of "public class Decompile".

Also, with 9.2 we started using osgi to manage scripting.  I'm making a w.a.g. but you might want to try having the script in a built-in script directory like ~/ghidra_scripts.

**Comment by Martyx00** [comment]
The `Decompile` class was a result of hasty copy pasting. The same error appears for the correct file (tried with both upper and lower case and from different directories). I have originally stumbled upon this issue when I was trying to run the `Decompile.java` script from version 9.1.2 from the `Ghidra/Features/Decompiler/ghidra_scripts` with the same error.
Corrected file:
```java
//Hello

import ghidra.app.script.GhidraScript;
import ghidra.app.util.headless.HeadlessScript;

public class Hello extends HeadlessScript {

	@Override
	public void run() throws Exception {
		System.out.println("HelloWorld!");
	}
}
```

**Comment by dev747368** [comment]
yeah, I kinda suspected that it was just a bug-report copy/paste thing.  I'll back out slowly and fade into the bushes.

**Comment by Martyx00** [comment]
No worries. Thanks for spotting that. I kind of failed to find any 9.2 specific documentation for scripting (could be just me being blind).

**Comment by jpleasu** [comment]
As @dev747368 suggested, you can either move your script to a default scripting directory, or add your alternative directory with the `-scriptPath` option.  The argument to `-postScript` is the name of the script, not a path to the script.  The fact that specifying a path used to work is a really a bug, see `<Ghidra distro>/support/analyzeHeadlessREADME.html`
```
 -postScript <ScriptName.ext> [<arg>]* ...
This parameter expects the script name only; do not include the path to the script.
The Headless Analyzer searches specific default locations for the named script, 
but additional script director(ies) may also be specified (see the -scriptPath argument for more information).
```

Your call should be 
`./ghidra_9.2_PUBLIC/support/analyzeHeadless "/tmp/out" "hello_binary" -import "/tmp/hello_binary" -scriptPath "/tmp" -postScript "Hello.java"`


If you press F1 in Ghidra, you can navigate to "Ghidra functionality->Scripting".

There _is_ a bug with non-java scripts: https://github.com/NationalSecurityAgency/ghidra/issues/2561.

**Comment by Martyx00** [comment]
Thanks!
