### ISSUE TITLE
Reusing the FunctionComparisonPlugin.java from a custom plugin possible?

### ISSUE THREAD

**Issue by arquicanedo** [NationalSecurityAgency/ghidra#2576]
Hi, I'm trying to reuse the [FunctionComparisonPlugin](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/functioncompare/FunctionComparisonPlugin.java) from a custom plugin that I'm developing.

Essentially, I'd like to be able to pick two functions from two binaries and compare them using the FunctionComparisonPlugin similar to how the standard Functions window implements this:

![image](https://user-images.githubusercontent.com/44371316/102824536-0a86b100-43ab-11eb-93ca-3ced83993598.png)

I spend some time searching for plugin code examples that reuse other plugins but I was not able to find any.

I also found this comment in [FunctionComparisonPlugin](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/functioncompare/FunctionComparisonPlugin.java). 
```
/**
 * Allows users to create function comparisons that are displayed
 * side-by-side in a provider. Comparisons can be initiated via the listing 
 * or function table and are displayed in a {@link FunctionComparisonProvider}.
 * <p>
 * The underlying data backing the comparison provider is managed by the
 * {@link FunctionComparisonService}. 
 */
```

Is the use of this plugin restricted to the listing or the function table? Or is it possible to reuse it from a custom plugin?

I'm aware of the [DecompilerCodeComparisonPanel](https://ghidra.re/ghidra_docs/api/ghidra/app/decompiler/component/DecompilerCodeComparisonPanel.html) but I suspect that reusing the FunctionComparisonPlugin is easier.

Thanks in advance.

**Comment by astrelsky** [comment]
You can retrieve the `FunctionComparisonService` through the `PluginTool` for your plugin. One of them will be a `FunctionComparisonPlugin` instance. If your plugin depends on the `FunctionComparisonPlugin` be sure to add the service to your plugin's `PluginInfo` annotatio under the servicesRequired field.

You can see an example of using another plugin [here](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/blob/master/src/main/java/cppclassanalyzer/plugin/ClassTypeInfoManagerPlugin.java) as I am using the DataTypeManagerPlugin.

**Comment by arquicanedo** [comment]
@astrelsky thanks for the pointer. The DataTypeManagerPlugin is a good reference. I've made some progress. 

Another question, is it possible to call scripts from a plugin programmatically?

It looks like the plugins are tightly coupled to the GUI elements and events, whereas the scripts can make use of the ghidra API and are much more straightforward to write. I'm trying to take advantage of this to avoid all the bookkeeping on the GUI-side.

**Comment by arquicanedo** [comment]
For more context, I found the [ProgramManagerPlugin](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/progmgr/ProgramManagerPlugin.java) and I'm able to use the ProgramManager service from my plugin.

The interesting part comes when trying to open a user-specified program.

```
					URL patchURL = null;
					try {
						patchURL = new File(patchFilePicker.getSelectedFilePath()).toURI().toURL();
					} catch (MalformedURLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
					getProgramManager().openProgram(patchURL, getProgramManager().OPEN_VISIBLE);
```

Ghidra complains that the "Ghidra URL does not reference a Ghidra Program"

Here a comment from the ProgramManagerPlugin.

```
	/**
	 * This method notifies listening plugins that a programs has been added to
	 * the program manager. This is not used for actually opening a program from
	 * the database and will act strangely if given a closed Program object.
	 *
	 * @see ghidra.app.services.ProgramManager#openProgram(ghidra.program.model.listing.Program)
	 */
```
I'm guessing that opening a program needs to be done via other standard GUI menus. Through clicking I am able to see multiple programs opened in the Listing window, and I'm able to get the array from the ProgramManagerPlugin.

**Comment by astrelsky** [comment]
> @astrelsky thanks for the pointer. The DataTypeManagerPlugin is a good reference. I've made some progress.
> 
> Another question, is it possible to call scripts from a plugin programmatically?
> 
> It looks like the plugins are tightly coupled to the GUI elements and events, whereas the scripts can make use of the ghidra API and are much more straightforward to write. I'm trying to take advantage of this to avoid all the bookkeeping on the GUI-side.

You may run a GhidraScript programmatically by utilizing the `GhidraScriptService`. From there it should be much easier to use the `GhidraScript`'s `askProgram` method.

**Comment by arquicanedo** [comment]
Thanks. I'll give it a try!

**Comment by astrelsky** [comment]
> Thanks. I'll give it a try!

No problem. May I ask the purpose of your plugin? I'm curious.

**Comment by arquicanedo** [comment]
The `GhidraScriptService.runScript` worked well and I'm able to open programs using the `askProgram` as you suggested. Thanks again.

We are developing a plugin to reliably situate patches. Right now I'm building a demo to show how to automatically establish function equivalence between two binaries (e.g., stripped vulnerable vs non-stripped patched). The GUI will give the option to pick two binaries (i.e., via the `askProgram`), do the processing, and show the equivalence results in a table that calls the `FunctionComparisonPlugin`. If you're interested in this let's connect privately.

I'm closing this issue. Thanks for all the help!

**Comment by astrelsky** [comment]
> The `GhidraScriptService.runScript` worked well and I'm able to open programs using the `askProgram` as you suggested. Thanks again.
> 
> We are developing a plugin to reliably situate patches. Right now I'm building a demo to show how to automatically establish function equivalence between two binaries (e.g., stripped vulnerable vs non-stripped patched). The GUI will give the option to pick two binaries (i.e., via the `askProgram`), do the processing, and show the equivalence results in a table that calls the `FunctionComparisonPlugin`. If you're interested in this let's connect privately.
> 
> I'm closing this issue. Thanks for all the help!

If I'm understanding correctly it sounds a lot like version tracking. Just in case version tracking automatically compares two programs, one source and one destination, depending on what filters you choose. After comparison it generates a table of matches from which you can reject, accept as a match, apply the function/symbol names and other markup.

**Comment by arquicanedo** [comment]
@astrelsky that's interesting. I played a bit with the version tracking but I didn't get to the part of applying functions and symbols. I'll look into it and get back to you after these holidays. Thanks for the pointers.
