### ISSUE TITLE
The font family setting isn't kept between restarts

### ISSUE THREAD

**Issue by xyzz** [NationalSecurityAgency/ghidra#258]
**Describe the bug**
The font setting resets (only for certain fonts?) when CodeBrowser is restarted.

**To Reproduce**
1. Download and unpack [Fixedsys.ttf.gz](https://github.com/NationalSecurityAgency/ghidra/files/3001087/Fixedsys.ttf.gz)
2. Place Fixedsys.ttf to `~/.fonts`
3. In CodeBrowser set the decompiler and disassembly font to Fixedsys Excelsior 3.01
4. Observe the font has changed as expected
5. Close and reopen CodeBrowser
6. Observe that an arbitrary font is used in place of fixedsys

**Expected behavior**
The font setting is kept between restarts

**Screenshots**
Before restart:
![image](https://user-images.githubusercontent.com/1065521/54888725-18c23900-4e76-11e9-9e1a-69d5a2f5fe4a.png)

After restart:
![image](https://user-images.githubusercontent.com/1065521/54888719-0ba54a00-4e76-11e9-985c-30eb7707a864.png)

**Attachments**
[Fixedsys.ttf.gz](https://github.com/NationalSecurityAgency/ghidra/files/3001087/Fixedsys.ttf.gz)

**Environment (please complete the following information):**
 - OS: Gentoo 17.0
 - Java Version: 11.0.2
 - Ghidra Version: 9.0

**Comment by dragonmacher** [comment]
Ghidra's font usage relies on the OS to resolve font names when requested by the application.  It seems like there is a disconnect between font name that is initially loaded and the name that is saved in the tool options file.  If these two values do not match then the JVM will pick a font it things is a suitable replacement when the tool is restarted.

If you have setup Ghidra for debugging, then you can check these two values to see if they are inconsistent.

The code that uses the chosen font is in `docking.options.editor.FontPropertyEditor`  You can see the valid value that is picked (the `fontNameChoice` value) at line 216:
'font = new Font(fontNameChoice, styleChoice, sizeChoice);'

The code that saves the font to the options file is in `ghidra.framework.options.WrappedFont` starting at line 68:
```
	String family = font.getFamily();
	int pos = family.indexOf(".");
	if (pos > 0) {
		family = family.substring(0, pos);
	}
	saveState.putString(FAMILY, family);
```

Assuming these values do not match, then it is possible the code inside of `WrappedFont` needs to be updated.

**Comment by dev747368** [comment]
I tried, can't dup with a custom font in my ./fonts directory.  Closing.
