### ISSUE TITLE
Unable to edit text strings

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [NationalSecurityAgency/ghidra#259]
**Is your feature request related to a problem? Please describe.**
Addresses which contain strings, can be marked as a string data type, but there does not seem to be a way to edit these strings.

**Describe the solution you'd like**
Add the ability to enable the text of the string to be edited. e.g. add right click "edit text" 

**Describe alternatives you've considered**
I'm currently opening the "Bytes" window, then selecting edit, and then editing the hex values of the string

**Additional context**

**Comment by dev747368** [comment]
If you are talking about assigning an alternate display value to the string, search for "Translate" in the help.  If you want some assistance in changing the byte values of the string, that isn't a feature we currently have.

**Comment by dev747368** [comment]
also, the "Bytes" window has an Ascii column that you can turn on in its settings, and then you can just input plain text for those bytes.
