### ISSUE TITLE
[Debugger] on MacOS - Java: Could not detect GDB's interpreter mode

### ISSUE THREAD

**Issue by JohnnyCurran** [NationalSecurityAgency/ghidra#2591]
**Describe the bug**
I cannot connect to a debugging target on macOS Big Sur (11.0.1)

**To Reproduce**
1. Click 'Create a new connection to a debugging target' on the Debugging Targets pane of the Debugger window in Ghidra
2. Select "IN-VM gnu gdb local debugger" and enter path to gdb executable ( /usr/local/bin/gdb )
3. Press connect

**Expected behavior**
Ghidra creates a connection to GDB

**Screenshots**
<img width="546" alt="image" src="https://user-images.githubusercontent.com/18315178/103220000-c6346d00-48e4-11eb-9c8d-1369f978a079.png">

**Attachments**
Exception:
```
java.util.concurrent.CompletionException: java.io.IOException: Could not detect GDB's interpreter mode
---------------------------------------------------
Build Date: 2020-Dec-27 1528 CST
Ghidra Version: 9.3
Java Home: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home
JVM Version: Oracle Corporation 11.0.2
OS: Mac OS X 10.16 x86_64
Workstation: johnnys-mbp.domain
```

**Environment (please complete the following information):**
 - OS: macOS 11.0.1
 - Ghidra Version: 9.3 build DEV
 - Java Version: 11.0.2

**Comment by d-millar** [comment]
Thanks for the information - need a little bit more to track this down.  What version of gdb are you running for starters?  Does it support the "new-ui" command?

**Comment by JohnnyCurran** [comment]
@d-millar 

GDB 10.1:
```
gdb --version
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

> Does it support the new-ui command?

Yes, it appears so:

```
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin20.1.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
*(gdb) new-ui
Usage: new-ui INTERPRETER TTY*
```

**Comment by nsadeveloper789** [comment]
Just verified this works on Linux with GDB 10.1, but I don't have a macOS environment ready to go. I'd need a bit more information about the exception...

Does the error happen immediately, or after a 10-second timeout?

Best I can tell, it was thrown on Line 561 of GdbManagerImpl.java. If you add e as the "cause" parameter, rebuild, retry, and then post the complete stack trace, I might be able to figure it out.

**Comment by JohnnyCurran** [comment]
> Does the error happen immediately, or after a 10-second timeout?

The error occurs after a 10-second timeout every time

I added `e` as the "cause" parameter and rebuilt. Here is the trace from `application.log`

```
2020-12-28 15:05:42 DEBUG (Pty) New Pty: /dev/ttys002 at (144,147)  
2020-12-28 15:05:43 DEBUG (GdbManagerImpl) Terminating agent.gdb.manager.impl.GdbManagerImpl@49492091  
2020-12-28 15:05:43 ERROR (GdbModelTargetSession) Could not get GDB version java.util.concurrent.CompletionException: java.lang.IllegalStateException: GDB is terminating
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at ghidra.async.AsyncReference.dispose(AsyncReference.java:371)
	at agent.gdb.manager.impl.GdbManagerImpl.terminate(GdbManagerImpl.java:680)
	at agent.gdb.manager.impl.GdbManagerImpl$PtyThread.run(GdbManagerImpl.java:136)
Caused by: java.lang.IllegalStateException: GDB is terminating
	at ghidra.async.AsyncReference.dispose(AsyncReference.java:369)
	... 2 more
 
2020-12-28 15:05:43 DEBUG (PtyThread) STDOUT,null reader exiting because java.io.IOException: Underlying input stream returned zero bytes  
2020-12-28 15:05:52 ERROR (DebuggerConnectDialog) Could not connect: java.util.concurrent.CompletionException: java.io.IOException: Could not detect GDB's interpreter mode  
```

Here is the change I made to add e as the cause parameter:

```diff
diff --git a/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java b/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java
index 5fd9d018f..0b3d32b01 100644
--- a/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java
+++ b/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java
@@ -558,7 +558,7 @@ public class GdbManagerImpl implements GdbManager {
                                iniThread.hasWriter.get(10, TimeUnit.SECONDS);
                        }
                        catch (InterruptedException | ExecutionException | TimeoutException e) {
-                               throw new IOException("Could not detect GDB's interpreter mode");
+                               throw new IOException("Could not detect GDB's interpreter mode", e);
                        }
```

**Comment by nsadeveloper789** [comment]
Thanks for the extra info. The log is actually more useful than just the stack trace :) . The "reader exited" line indicates we couldn't read the first line of output from GDB. This means either our use of PTYs on macOS is not quite working, GDB crashed before we got the first line, or your launch command is incorrect. Do `which gdb` and verify your GDB launch command in the dialog matches.

If it does, then I'd like to examine the exception caught and logged at GdbManagerImpl:137. If you add `e` as a parameter to `Msg.debug`, the log will include the stack trace.

**Comment by d-millar** [comment]
Wow, well I can re-create the problem, but gdb on osx is a bit of a nightmare now.  For starters, looks like you may have to codesign the executable after installing, and at least the homebrew version doesn't appear to support Mach-O binaries by default.  Not sure about macports. @JohnyCurran: Any chance you've built your version of gdb from the Apple source and already codesigned it?

**Comment by JohnnyCurran** [comment]
@nsadeveloper789 

The gdb path is correct:

```bash
$ which gdb
/usr/local/bin/gdb
```

Here is the new log:

```
2020-12-29 12:30:15 DEBUG (Pty) New Pty: /dev/ttys003 at (141,145)  
2020-12-29 12:30:16 DEBUG (GdbManagerImpl) Terminating agent.gdb.manager.impl.GdbManagerImpl@12dbd36f  
2020-12-29 12:30:16 ERROR (GdbModelTargetSession) Could not get GDB version java.util.concurrent.CompletionException: java.lang.IllegalStateException: GDB is terminating
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at ghidra.async.AsyncReference.dispose(AsyncReference.java:371)
	at agent.gdb.manager.impl.GdbManagerImpl.terminate(GdbManagerImpl.java:680)
	at agent.gdb.manager.impl.GdbManagerImpl$PtyThread.run(GdbManagerImpl.java:136)
Caused by: java.lang.IllegalStateException: GDB is terminating
	at ghidra.async.AsyncReference.dispose(AsyncReference.java:369)
	... 2 more
 
2020-12-29 12:30:16 DEBUG (PtyThread) STDOUT,null reader exiting because java.io.IOException: Underlying input stream returned zero bytes java.io.IOException: Underlying input stream returned zero bytes
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at agent.gdb.manager.impl.GdbManagerImpl$PtyThread.run(GdbManagerImpl.java:111)
 
2020-12-29 12:30:25 ERROR (DebuggerConnectDialog) Could not connect: java.util.concurrent.CompletionException: java.io.IOException: Could not detect GDB's interpreter mode  
```

Here's my diff:

```diff
diff --git a/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java b/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java
index 5fd9d018f..21db3bd51 100644
--- a/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java
+++ b/Ghidra/Debug/Debugger-agent-gdb/src/main/java/agent/gdb/manager/impl/GdbManagerImpl.java
@@ -134,7 +134,7 @@ public class GdbManagerImpl implements GdbManager {
                        }
                        catch (Throwable e) {
                                terminate();
-                               Msg.debug(this, channel + "," + interpreter + " reader exiting because " + e);
+                               Msg.debug(this, channel + "," + interpreter + " reader exiting because " + e, e);
```

@d-millar 
Unfortunately, I have neither built gdb from source nor codesigned it. My gdb was installed through homebrew. If it would be helpful I can build gdb ([from here?](https://opensource.apple.com/source/gdb/)), codesign it, and try again

**Comment by d-millar** [comment]
I think the actual problem is the Mach-O format.  Before you do anything else, try running your version of gdb on your target from the command line.  Am betting even money it's unhappy.  If not, then I think I need to do more digging on my end.  If so, that link is the right one!

**Comment by JohnnyCurran** [comment]
Seems like you're on to something with the file formats:

```bash
$ file `which ls`
/bin/ls: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/bin/ls (for architecture x86_64):	Mach-O 64-bit executable x86_64
/bin/ls (for architecture arm64e):	Mach-O 64-bit executable arm64e
$ gdb /bin/ls
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin20.1.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
"0x7ffeea1ba730s": not in executable format: file format not recognized
(gdb) 
```

**Comment by ryanmkurtz** [comment]
You may have to manually extract the Mach-o file you want to debug from the Universal Binary container file.

**Comment by d-millar** [comment]
Yeah, unfortunately, that doesn't help you out in this case.  The binaries extracted by something like lipo are still unrecognized by the brew version of gdb.

**Comment by JohnnyCurran** [comment]
Okay so I wrote a tiny C program, compiled it with `clang`, and tried to launch it with `gdb`. Crashes completely when I try to run it:

Clang:
```bash
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

source:
```c
#include<stdio.h>
#include<stddef.h>

char *series_sum(const size_t n);

int main() {
    printf("%s", series_sum(0));
}

char *series_sum(const size_t n) {
    if (n == 0) return "0.00";
}
```

when I load to GDB:

```
$ clang -o s seriesSum.c 
seriesSum.c:12:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
1 warning generated.
$ file s
s: Mach-O 64-bit executable x86_64
$ gdb s
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin20.1.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from s...
(No debugging symbols found in s)
(gdb) run
Starting program: /Users/johnny/cprograms/s 
[New Thread 0x2803 of process 72451]
[New Thread 0x1903 of process 72451]
../../gdb/target.c:2149: internal-error: void target_mourn_inferior(ptid_t): Assertion `ptid == inferior_ptid' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) 
```

Ghidra still crashes with same error as the original issue.

Is this not a Ghidra issue then? Is it a MacOS gdb problem?

@d-millar Should I compile & sign my own gdb?

**Comment by d-millar** [comment]
I must concede I don't think I have a complete grasp of the real problem, but I can give you my best guess.  Googling for the error message we're getting, you find things like this reference:

[(https://stackoverflow.com/questions/52529838/gdb-8-2-cant-recognized-executable-file-on-macos-mojave-10-14)]

Obviously, this is an older version of MacOS and an older version of gdb, but, given the move away from gdb toward lldb since Mavericks, I would not be surprised if the problem is similar or the same.  Natively compiled MacOS executables, of course, use the Mach-O file format, and may be further packed into Universal Binaries, as noted by @ryanmkurtz.  If changes are made to the build chain that have not been matched by changes in gdb with regard to the format, gdb is likely to fail.  I do not actually no whether the version maintained by homebrew or macports can, in fact, handle Mach-O binaries built on, say, Big Sur.  It's possible they can, and we're just missing some setting that tells gdb what to do.  Will keep looking into this, but honestly I don't know.

The simplest setup with the fewest possible paths to failure would be to repeat what you've done, i.e. compile a very simple program with Clang.  Make sure the output is a single Mach-O (rather than a Universal Binary).  Build gdb from the opensource.apple.com, and sign the resulting executable.  Then test the result and cross your fingers.

I'm sure there may be issues after that related to Ghidra, but, sadly, this is not really a Ghidra problem.  This is more of a MacOS vs gdb issue.  Ghidra debugger at its core is only a wrapper around the native functionality, and, if the native debugger fails, Ghidra can do little to save it.

Which isn't to say, we're uninterested in the results here - we definitely are.  We were hoping the current versions of lldb would work with the gdb machine interface, but it appears Apple is moving away from support for GDB/MI in favor of the LLDB.Framework API.  Support for this in Ghidra will entail writing a new lldb model - probably a month or so of dedicated work - so anything we can do to get interim versions running on MacOS would be a huge win.

Appreciate all your efforts on this!

**Comment by nsadeveloper789** [comment]
I think it's both-and in terms of the problems. Since GDB can run well enough to get a REPL, Ghidra should have at least been able to connect, but Ghidra doesn't appear even to receive GDB's first line of output. For that issue, it seems like a simple I/O problem with the Pty. That said, if GDB isn't a viable solution on macOS, anyway, figuring out the I/O issue won't get us much mileage.

In the hopes that we find the magic setting for GDB, we can try using some of the unit tests to test the Pty theory:

https://github.com/NationalSecurityAgency/ghidra/blob/debugger/Ghidra/Debug/Debugger-agent-gdb/src/test/java/agent/gdb/ffi/linux/PtyTest.java

FWIW, even on Linux, these tests can be iffy. If you have Eclipse set up, you can run them the usual way. They're even iffier under Gradle (who knows why?), but you can do that without Eclipse:

```
gradle Debugger-agent-gdb:test --tests=agent.gdb.ffi.linux.PtyTest
```

Our dependency graph for tests in Gradle is a little obtuse, so be patient while it builds. I don't think that command will produce an HTML report, but there should be few enough tests that you can just examine the console output.

**Comment by JohnnyCurran** [comment]
Thank you everyone for all of your help on this, I greatly appreciate it.

@d-millar 
I uninstalled gdb through brew `brew uninstall gdb`

So on opensource.apple.com, the latest GDB version I could find was from 2012. I did download that tarball ( https://opensource.apple.com/tarballs/gdb/gdb-1824.tar.gz ) But I could not get it to build on my machine (Is there a more up-to-date source from Apple I missed?)

So I downloaded the 10.1 source from http://ftp.gnu.org/gnu/gdb/gdb-10.1.tar.gz and built & code signed (self-signed cert) the binary successfully. Unfortunately, no dice on launching gdb. (Same source & Mach-O binary as previous comment). Log looks to be the same:

```
2020-12-30 12:00:09 DEBUG (Pty) New Pty: /dev/ttys002 at (160,161)  
2020-12-30 12:00:09 DEBUG (GdbManagerImpl) Terminating agent.gdb.manager.impl.GdbManagerImpl@1a435b6f  
2020-12-30 12:00:09 ERROR (GdbModelTargetSession) Could not get GDB version java.util.concurrent.CompletionException: java.lang.IllegalStateException: GDB is terminating
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at ghidra.async.AsyncReference.dispose(AsyncReference.java:371)
	at agent.gdb.manager.impl.GdbManagerImpl.terminate(GdbManagerImpl.java:681)
	at agent.gdb.manager.impl.GdbManagerImpl$PtyThread.run(GdbManagerImpl.java:136)
Caused by: java.lang.IllegalStateException: GDB is terminating
	at ghidra.async.AsyncReference.dispose(AsyncReference.java:369)
	... 2 more
 
2020-12-30 12:00:09 DEBUG (PtyThread) STDOUT,null reader exiting because java.io.IOException: Underlying input stream returned zero bytes  
2020-12-30 12:00:19 ERROR (DebuggerConnectDialog) Could not connect: java.util.concurrent.CompletionException: java.io.IOException: Could not detect GDB's interpreter mode  
```

@nsadeveloper789 
I don't have eclipse set up - Running the tests under gradle throws lots of IllegalAccessExceptions (and then hangs at 99% executing), see output:

```
$ gradle Debugger-agent-gdb:test --tests=agent.gdb.ffi.linux.PtyTest
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :Debugger-agent-gdb:test
:Debugger-agent-gdb:test started: Wed Dec 30 12:05:38 CST 2020
Test Machine Name: Unknown.domain
Root Test Dir: build
Test Output Dir: /Users/johnny/ghidradebugger/build/output
Test Temp Dir: /Users/johnny/ghidradebugger/Ghidra/Debug/Debugger-agent-gdb/build
Test Report Dir: /Users/johnny/ghidradebugger/Ghidra/Debug/Debugger-agent-gdb/build/JUnit/reports
Java Debug Port: 18344
Listening for transport dt_socket at address: 18344
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/Users/johnny/.gradle/caches/modules-2/files-2.1/org.python/jython-standalone/2.7.1/942c3294840dc9dfb3528d775f4d02a6d57c421f/jython-standalone-2.7.1.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

agent.gdb.ffi.linux.PtyTest > testForkIntoNonExistent STANDARD_OUT
    New Pty: /dev/ttys003 at (97,98)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/Users/johnny/.gradle/caches/modules-2/files-2.1/org.python/jython-standalone/2.7.1/942c3294840dc9dfb3528d775f4d02a6d57c421f/jython-standalone-2.7.1.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.RuntimeException: errno=2: No such file or directory
        at agent.gdb.ffi.linux.PtySessionLeader.checkErr(PtySessionLeader.java:47)
        at agent.gdb.ffi.linux.PtySessionLeader.run(PtySessionLeader.java:60)
        at agent.gdb.ffi.linux.PtySessionLeader.main(PtySessionLeader.java:31)

agent.gdb.ffi.linux.PtyTest > testSessionBash STANDARD_OUT
    New Pty: /dev/ttys003 at (97,98)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/Users/johnny/.gradle/caches/modules-2/files-2.1/org.python/jython-standalone/2.7.1/942c3294840dc9dfb3528d775f4d02a6d57c421f/jython-standalone-2.7.1.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.RuntimeException: errno=2: No such file or directory
        at agent.gdb.ffi.linux.PtySessionLeader.checkErr(PtySessionLeader.java:47)
        at agent.gdb.ffi.linux.PtySessionLeader.run(PtySessionLeader.java:60)
        at agent.gdb.ffi.linux.PtySessionLeader.main(PtySessionLeader.java:31)
<============-> 99% EXECUTING [19m 55s]
> :Debugger-agent-gdb:test > 1 test completed
> :Debugger-agent-gdb:test > Executing test agent.gdb.ffi.linux.PtyTest
```

I'll update this output if the test finishes

**Comment by nsadeveloper789** [comment]
It won't finish. I probably need a timeout there, too :) No matter. This definitely found the Ghidra part of the problem. It deals in trying to connect the GDB subprocess to the Pty. For whatever reason, it thinks the Pty doesn't exist. (See PtySessionLeader:60 as reported in the stack trace). I'm assuming this didn't show up in the application log, because it gets printed to stderr (we're in the subprcess at this point, preparing to execve, so we can't use the application log). This is not an issue I'm prepared to resolve at the moment, though the comment on Line 58 might be a clue. Unfortunately, I forgot to note the URL where I read about this.

**Comment by nsadeveloper789** [comment]
FWIW, we've discussed the idea of writing an alternative connector that accessed GDB/MI over SSH. If we were to move forward with that, and it were successful, it would likely overcome this Pty issue.

**Comment by JohnnyCurran** [comment]
Appreciate all your work looking into this. I'll keep the issue open as something to reference for whichever implementation route you choose to take (Unless you deem it suitable to close - I'm no maintainer so I have no decision making power here). For me, I'll continue on in Linux userland for running GDB for now

**Comment by NeutralKaon** [comment]
I'm having this issue too. 

Some thoughts: 
1. macports gdb lives (for me) in a different location, and perhaps not what one expects: 
```bash
$ port  contents gdb|tail -n +2|xargs -n 1 -I {} find '{}'  -perm +111 -type f
    /opt/local/bin/ggdb
    /opt/local/bin/ggdb-add-index
```
2. Don't forget (patronisingly) that SIP needs tweaking for debugging support -- either `csrutil disable` or `csrutil enable --without debug` to taste 
3. Gdb requires codesigning. This is a [giant pain in the arse](https://stackoverflow.com/questions/33162757/how-to-install-gdb-debugger-in-mac-osx-el-capitan). Alternatively, running it as root works (but is moderately stupid, especially with an untrusted binary...but then you should be doing it all in a VM anyway, with plenty of snapshots and probably no network access, right?)   
4. The version of gdb I have (10.2) can't deal with phat Mach-O binaries. `lipo -thin x86_64 /Path/To/App.app/Contents/MacOS/App -output /tmp/App` and then move the new thin binary in place. Swap x86_64 for aarch64 if relevant. Hope that the target doesn't independently check its own `.app` bundle. 
4. I then found that using GDB/MI over SSH "just worked" with Ghidra.

**Comment by d-millar** [comment]
Going with 5 :)

That said, support for lldb is well-under way.  Doesn't save you from the codesigning issue, however, if you're attaching the debugger vice launching the executable directly.
