### ISSUE TITLE
Support ARM for Ghidra Server

### ISSUE THREAD

**Issue by RobertLarsen** [NationalSecurityAgency/ghidra#2595]
Since I would really like to share my projects between different workstations and laptops using my Raspberry Pi as a server.

I have Ghidra Server running, but get "Connection to server failed" in the GUI. The logs provide no clue as to what went wrong and all the SSL makes til difficult to peek at the packets (yes, I know that is the entire purpose...but it sucks for debugging).

**Comment by RobertLarsen** [comment]
I use this Dockerfile for containerizing the server:
[Dockerfile.txt](https://github.com/NationalSecurityAgency/ghidra/files/5752459/Dockerfile.txt)

**Comment by dev747368** [comment]
Have you tried your docker file on anything other than your raspberry pi to ensure it works?

I think you've got some parameters wrong for the server in your docker file.

The "-ip0.0.0.0" parameter should be "-i" if you are trying to configure which interface ghidra listens on... but 0.0.0.0 is the default already.  Also should have a space.

    #   -i #.#.#.# : server interface IPv4 address to listen on (default will listen on all interfaces).
    #   -ip <hostname> : identifies the remote access IPv4 address or hostname (FQDN) which should be 
    #                       used by remote clients to access the server.

And if there is some NATing going on, you will need a "-ip" to advertise to the clients what your 'real' IP address is... something like "-ip 192.168.0.42", if that was the "public" address of the docker server.

**Comment by RobertLarsen** [comment]
Damn...I misread that. Yes, it works now. Thanks.
