### ISSUE TITLE
Any way to use lowercase mnemonics?

### ISSUE THREAD

**Issue by JujharSingh** [NationalSecurityAgency/ghidra#26]
I'm looking to use lowercase mnemonics, I can only find the `Display In Upper Case` option for the bytes field.

**Comment by gnooby22** [comment]
No.  The displayed instructions and register names (including use of upper/lower case) is baked into the sleigh spec files associated with each language.  Unfortunately, the use of upper/lower-case can vary language to language.

**Comment by Andoryuuta** [comment]
For anybody that comes across this issue: I've made a very hacky modification for Ghidra 9.0 to add options to force mnemonics and operands to lowercase @ https://github.com/Andoryuuta/Ghidra-lowercase.

Fair warning: I simply don't understand Ghidra's internals enough to do this in a proper way, as such, **forcing operands to lowercase with my modification will break cursor highlighting for operands**. This does not effect mnemonic highlighting.

![](https://github.com/Andoryuuta/Ghidra-lowercase/raw/master/screenshots/before_after.png)
