### ISSUE TITLE
Export - Intel Hex - Selected only, option does not export the entire selected range

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [NationalSecurityAgency/ghidra#260]
**Describe the bug**
When part of the binary is exported, to Intel Hex format, using the Export Program function, with the "Selection only" checkbox ticked, the saved binary does not include all the selected data.

Specifically the last instruction does not seem to be saved.

Note. Exporting to "Binary" seems however to work OK. This only applies to Intel Hex format.

Update.
Selecting less than 16 bytes e.g. just 2 bytes, also causes problems, whether either nothing gets exported, or the entire binary gets exported.

**To Reproduce**
Select an entire function in the Listing view.
From the File menu, select "Export Program"
From the Format dropdown select "Intel Hex"
Make sure the "Selection Only" checkbox is ticked
Export the file.
Open the file in an editor that can read Intel Hex format, e.g. use Segger J-Flash 
Compare the last bytes in the file with the last bytes selected in the disassembly.

**Expected behavior**
All selected instructions and data should be exported

**Environment (please complete the following information):**
 - OS: Windows 7 Pro
 - Java Version: 11
 - Ghidra Version: 9.0

**Additional context**
The disassembly is ARM Cortex Little endian.

**Comment by rogerclarkmelbourne** [comment]
FYI. I just updated the bug, because I was in the Listing view not the disassembly view

**Comment by adamopolous** [comment]
Thanks for the info @rogerclarkmelbourne. This is happening because we currently restrict output to only 16-byte records; anything left-over is ignored. eg: if you select 36 bytes you'll get two 16-byte records in the output with the remaining 4 left out.

We're looking at making this more flexible so users can configure the record size and/or ensure that all bytes are present in the output.

**Comment by rogerclarkmelbourne** [comment]
Thanks 

My workaround is to export as a binary, and then use Segger J-Flash to load the binary, where I manually enter the start address. I then resave the binary as Intel Hex using J-Flash.

( there are probably other prograns that could be used for this)

I don’t really understand why you would quantise the size to 16 bytes for intel hex but not for binary.
Perhaps you could remove the quantisation altogether. But I presume there must be a reason for doing it.

**Comment by rogerclarkmelbourne** [comment]
PS. When you. Release the source code for Ghidra I would probably change the intel hex export and send a PR

**Comment by rogerclarkmelbourne** [comment]
@adamopolous 

I just found another bug with the Intel Hex

I only selected 2 bytes, but when I exported the Selection only, I either got nothing or at one time I seemed to get  the whole file.

I'll update my original bug post

**Comment by adamopolous** [comment]
The way things are currently implemented I would expect a 2 byte selection to result in nothing every time - not sure how it would get the whole file; if it's doing that then there's certainly something buggy going on. Any more info you can provide on that scenario would be helpful. 

But that all might be moot - I'm looking at removing the restriction altogether.
