### ISSUE TITLE
In a Python scrypt, how can I specify data length when creating a data instance

### ISSUE THREAD

**Issue by LRFLEW** [NationalSecurityAgency/ghidra#261]
Working with the scripting system in the Python window, I found the `createData` method and used it to procedurally define the data of some parts of my program that the analyzers couldn't figure out. However, I was messing with a data type that can use user-specified lengths (Alignment), and can't figure out a way to specify the length. In the case I'm trying to script, the bytes aren't all the same value, so the automatically determined length is too short. From my research, I couldn't figure out if such a method existed, so if there isn't a way of doing this, then this is a feature request.

**Comment by ryanmkurtz** [comment]
The createData() method is a wrapper to currentProgram.getListing().createData(Address, DataType).  The listing object has a createData(Address, DataType, int), where the 3rd parameter is the length.

**Comment by LRFLEW** [comment]
Thanks. I tested this, and it worked perfectly for me.

I do think that this should be added as an overload for the basic `createData` (From what I can tell from messing with it, the Python window uses the methods in `ghidra.app.script.GhidraScript`, so the overload would be there). However, this basic workaround works, so it's not completely necessary.
