### ISSUE TITLE
Debugger: NoSuchMethodException

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2615]
**Describe the bug**
`DbgEngNative.INSTANCE` fails to initialize due to:
`java.lang.NoSuchMethodError: 'com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class)'`

**To Reproduce**
1. Open pe in debugger.
2. Start session.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19042.685]
 - Java Version: **15.0.1**
 - Ghidra Version: 9.3_DEV

**Additional context**
I'm not sure if this is a result of a newer Java version or something in my debugger setup.

<details><summary>stacktrace</summary>

```
java.lang.NoSuchMethodError: 'com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class)' at agent.dbgeng.jna.dbgeng.DbgEngNative.<clinit>(DbgEngNative.java:32)
DbgEngNative.java:32 at agent.dbgeng.dbgeng.DbgEng.debugCreate(DbgEng.java:147)
DbgEng.java:147 at agent.dbgeng.manager.impl.DbgManagerImpl.lambda$start$0(DbgManagerImpl.java:347)
DbgManagerImpl.java:347 at agent.dbgeng.gadp.impl.DbgEngClientThreadExecutor.init(DbgEngClientThreadExecutor.java:50)
DbgEngClientThreadExecutor.java:50 at agent.dbgeng.gadp.impl.AbstractClientThreadExecutor.run(AbstractClientThreadExecutor.java:113)
AbstractClientThreadExecutor.java:113 at java.base/java.lang.Thread.run(Thread.java:832)
Thread.java:832
```
</details>

**Comment by d-millar** [comment]
Agreed re #2616, hanging forever, and giving something more enlightening as far as an error message.  Regarding the base error, which flavor of the underlying debugger did you install, i.e. did you install dbgeng.dll using Visual Studio, the Windows SDK, a straight install of the debugger package, or something else?

**Comment by astrelsky** [comment]
> Agreed re #2616, hanging forever, and giving something more enlightening as far as an error message. Regarding the base error, which flavor of the underlying debugger did you install, i.e. did you install dbgeng.dll using Visual Studio, the Windows SDK, a straight install of the debugger package, or something else?

Hmm I'm not sure. Hopefully this will be more enlightening. [.vsconfig](https://github.com/NationalSecurityAgency/ghidra/files/5762700/vsconfig.txt). However, from the exception I'm under the impression that the actual `com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class)` method doesn't exist? Unless that is what occurs when the dll isn't found.

**Comment by d-millar** [comment]
Yeah, I'm actually not positive what the error message is telling us - will test it out tomorrow on a system without the relevant dll's installed.  Dbgeng.dll not being on your load path would have been my first guess, but it's just that - a guess.  I'm using the same version of windows, same JDK, and obviously same version of Ghidra and not seeing that result, so I doubt those are the culprits.  "debugCreate", referenced in the stack trace, is in dbgeng.dll, which normally gets installed in the system directory or under the DDK/SDK/WDK directory in C:\Program Files (x86), but, as you've pointed out, it might be the load function itself at fault.

**Comment by nsadeveloper789** [comment]
Based on the error, my guess is the version of JNA; though, if that dependency is being resolved by Gradle, I don't know why it would be wrong You might double-check your run-time classpath just to be sure. Linkage issues at the native level *should* instead cause UnsatisifedLinkError.... I've not tested on anything later than Java 11, so your version 15 is what I'd suspect next. If it's not too much trouble, you might just try executing with version 11.

**Comment by d-millar** [comment]
hmmm, good point - looks like my Eclipse has 15 loaded but is using 11, so....I suspect that's it.

**Comment by astrelsky** [comment]
I opened up the python terminal in Ghidra for a sanity check and got the following results.

```
>>> from com.sun.jna import Native
>>> Native
<type 'com.sun.jna.Native'>
>>> Native.load
Traceback (most recent call last):
  File "python", line 1, in <module>
AttributeError: type object 'com.sun.jna.Native' has no attribute 'load'
```

**Comment by astrelsky** [comment]
Uncommenting the `Native.loadLibrary` one and commenting the `Native.load` seems to work.

**Comment by nsadeveloper789** [comment]
That's an indication that you're somehow using an older version of JNA. `loadLibrary` is marked as `@Deprecated` in the version we use (5.4.0). You're welcome to revert from `load` to `loadLibrary`, but the apparent dependency clash may be a sign of bad times to come.

**Comment by astrelsky** [comment]
> That's an indication that you're somehow using an older version of JNA. `loadLibrary` is marked as `@Deprecated` in the version we use (5.4.0). You're welcome to revert from `load` to `loadLibrary`, but the apparent dependency clash may be a sign of bad times to come.

Oh boy. Any advice on how to ensure I would be using the "latest and greatest"?

**Comment by astrelsky** [comment]
@nsadeveloper789 it appears that the `jna-4.5.0` from yajsw-stable-12.12 is being used instead of `jna-5.4.0` from Debugger-agent-dbgeng

**Comment by nsadeveloper789** [comment]
Oh interesting. I would only expect that for the GhidraServer, but it wouldn't surprise me if that snuck into our general configuration. 5.4.0 is not the latest and greatest, anymore. They've released 5.6.0. The question of when to upgrade is classic CM. The version we use is declared in our Gradle scripts. That doesn't necessarily spare us from Jar hell, though. Anyway, thanks for pointing out we have a 4.5.0 version clash via yajsw.

**Comment by ryanmkurtz** [comment]
@astrelsky how did you build and launch Ghidra when you saw this?  Who generated the classpath?  Was it something like Visual Studio Code doing it?

**Comment by astrelsky** [comment]
> @astrelsky how did you build and launch Ghidra when you saw this?  Who generated the classpath?  Was it something like Visual Studio Code doing it?

I don't remember if I encountered this while launching from vscode or normally.  When launching from vscode it gets setup from the gradle script [here](https://www.github.com/astrelsky/vscode-ghidra-skeleton/tree/master/skeleton%2Fbuild.gradle). However that is really just for the eclipse jdt.ls as `GhidraLauncher` puts everything in the class path when starting. I'm not sure if it clears the classpath first or not or even if that matters.

**Comment by ryanmkurtz** [comment]
Ghidra should never be including its bundled version of JNA on the classpath.  That is only used when the Ghidra Server is started up.  I'd be curious what your classpath was when you encountered this.

**Comment by astrelsky** [comment]
> Ghidra should never be including its bundled version of JNA on the classpath.  That is only used when the Ghidra Server is started up.  I'd be curious what your classpath was when you encountered this.

Seems like this was most likely my fault then as it was probably included by the gradle script. I'll explicitly exclude it in the future.
