### ISSUE TITLE
how to display and extract the undefined array data

### ISSUE THREAD

**Issue by greagen** [NationalSecurityAgency/ghidra#2620]
I am using Ghidra to analyze libpng. There are some undefined data like 001203c0 shown in the figure.
![Screen Shot 2021-01-05 at 2 02 42 PM](https://user-images.githubusercontent.com/12275904/103612119-afce8700-4f5e-11eb-9ba3-92e069ad7c54.png)
I checked it and it is a string array. But Ghidra report it an undefined data and it can't be displayed in the defined data window. I tried to use the API 
```
if (toAddress.toString().equals("001203c0")) {
    Data data = program.getListing().getDataContaining(toAddress);
}              
```
But it cannot get what I want, the string array.
I wanna know how to extract the array data like string array and integer array?

**Comment by greagen** [comment]
I am using Ghidra to analyze libpng. There are some undefined data like 001203c0 shown in the figure.
![Screen Shot 2021-01-05 at 2 02 42 PM](https://user-images.githubusercontent.com/12275904/103612119-afce8700-4f5e-11eb-9ba3-92e069ad7c54.png)
I checked it and it is a string array. But Ghidra report it an undefined data and it can't be displayed in the defined data window. I tried to use the API 
```
if (toAddress.toString().equals("001203c0")) {
    Data data = program.getListing().getDataContaining(toAddress);
}              
```
But it cannot get what I want, the string array.
I wanna know how to extract the array data like string array and integer array?

**Comment by dev747368** [comment]
@greagen When you encounter bytes that Ghidra hasn't automatically assigned a data type to, you can manually define it yourself.  In this case, you could define it as an array of char[4]s.
There are settings that control how Ghidra auto-detects string values.  In your case, because each of these strings are so short,  they probably were excluded.

**Comment by greagen** [comment]
Is there any method to extract the array data automatically by Jar Api?
