### ISSUE TITLE
How to convert DecompInterface() program into Headless Analyzer.

### ISSUE THREAD

**Issue by usaribbon** [NationalSecurityAgency/ghidra#2621]
Hello, I'm trying to convert GUI ghidra script into Headless Analyzer program however DecompInterface() raises NullPointerException on Headless Analyzer.
I confirmed that this code works on GUI script.

Does someone know how to fix this error or other decompiler code?

```
	private DecompInterface setUpDecompiler(Program program) {
		DecompInterface decomplib = new DecompInterface();
        
		DecompileOptions options;
		options = new DecompileOptions(); 
		OptionsService service = state.getTool().getService(OptionsService.class);
		if (service != null) {
			ToolOptions opt = service.getOptions("Decompiler");
			options.grabFromToolAndProgram(null,opt,program);    	
		}
		decomplib.setOptions(options);
        
		decomplib.toggleCCode(true);
		decomplib.toggleSyntaxTree(true);
		decomplib.setSimplificationStyle("decompile");
		
		return decomplib;
	}
```

```
INFO  SCRIPT: C:\Users\docs\ghidra_scripts\MyHeadlessAnalyzer20210105.java (HeadlessAnalyzer)
INFO  MyHeadlessAnalyzer20210105.java> DEPTH 1 START (GhidraScript)
ERROR REPORT SCRIPT ERROR:  ( C:\Users\doc\firmware-sample )  C:\Users\docs\ghidra_scripts\MyHeadlessAnalyzer20210105.java : null (HeadlessAnalyzer) java.lang.NullPointerException
        at MyHeadlessAnalyzer20210105.setUpDecompiler(MyHeadlessAnalyzer20210105.java:277)
        at MyHeadlessAnalyzer20210105.run(MyHeadlessAnalyzer20210105.java:137)
        at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
        at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
        at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
        at ghidra.app.util.headless.HeadlessAnalyzer.runScript(HeadlessAnalyzer.java:580)
        at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:918)
        at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:985)
        at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1558)
        at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1696)
        at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1762)
        at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:438)
        at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
        at ghidra.GhidraLauncher.main(GhidraLauncher.java:79)
```

Thank you :)

**Comment by dragonmacher** [comment]
I can't tell from your snippet exactly where the NPE is happening.  I will assume it is that your `tool` is null.    Remove these lines from the snippet above:
```
    OptionsService service = state.getTool().getService(OptionsService.class);
    if (service != null) {
        ToolOptions opt = service.getOptions("Decompiler");
        options.grabFromToolAndProgram(null,opt,program);    	
    }
```

**Comment by astrelsky** [comment]
Would the options be grabbed by default with the `FlatDecompilerAPI`? You could do the setup as simply as
`FlatDecompilerAPI decompApi = new FlatDecompilerAPI(this);` when using a java GhidraScript.

**Comment by dragonmacher** [comment]
> Would the options be grabbed by default with the `FlatDecompilerAPI`? You could do the setup as simply as
> `FlatDecompilerAPI decompApi = new FlatDecompilerAPI(this);` when using a java GhidraScript.

I have not verified, but that is probably equivalent.  The original code listing was an attempt to keep the script's decompile options in sync with the tool.   Obviously, that is not needed if there is no tool.   In these 2 cases, the default options should be used.

**Comment by usaribbon** [comment]
Dear all,
Thank you for your comment!

I modified my code following your advice and `FlatDecompilerAPI` worked for me 👍 

```
	private String functionDecompile(Function function) throws Exception {
		FlatDecompilerAPI decompApi = new FlatDecompilerAPI(this);
		if(decompApi.getDecompiler() == null) {
			decompApi.initialize();
		}
		
		return decompApi.decompile(function);
	}
```

Thank you so much!

**Comment by dragonmacher** [comment]
I recommend that make the `decompApi` a field in your script and create/initialize it one time.  Doing so will make your script a bit more performant.

**Comment by astrelsky** [comment]
> I recommend that make the `decompApi` a field in your script and create/initialize it one time. Doing so will make your script a bit more performant.

Yes.

Also, the for the `FlatDecomilerAPI` you need to invoke `FlatDecomilerAPI.dispose`. You may do so by overriding
`public void cleanup​(boolean success)` in your script and invoke it there.

**Comment by astrelsky** [comment]
> > I recommend that make the `decompApi` a field in your script and create/initialize it one time. Doing so will make your script a bit more performant.
> 
> Yes.
> 
> Also, the for the `FlatDecomilerAPI` you need to invoke `FlatDecomilerAPI.dispose`. You may do so by overriding
> `public void cleanup​(boolean success)` in your script and invoke it there.


@dragonmacher this isn't really related, but is there a way to make Eclipse or the Java compiler in general warn you when `Disposable.dispose` isn't invoked in a similar fashion it does for a resource leak when something isn't closed?

**Comment by dragonmacher** [comment]
> @dragonmacher this isn't really related, but is there a way to make Eclipse or the Java compiler in general warn you when `Disposable.dispose` isn't invoked in a similar fashion it does for a resource leak when something isn't closed?

There is no tool-based solution to do this that I know of.  It would probably be pretty easy to bake this into the scripting system so that the `FlatDecompilerAPI` gets a chance to issue a warning during script exit (or it could just perform the cleanup itself).
