### ISSUE TITLE
0x0 pointers -> use nullptr in decompiled code

### ISSUE THREAD

**Issue by PELock** [NationalSecurityAgency/ghidra#263]
**Is your feature request related to a problem? Please describe.**

Null pointer referenced:

        01001f75 83 7d 14 00     CMP        dword ptr [EBP + param_4],0x0

are decompiled to:

(LPCWSTR)0x0

**Describe the solution you'd like**

Just use

nullptr

**Describe alternatives you've considered**

**Additional context**

**Comment by saruman9** [comment]
Are you check `Edit -> Tool Options... -> Decompiler -> Display -> Print 'NULL' for null pointers`?

**Comment by ryanmkurtz** [comment]
Thanks @saruman9, that is the best way to do it.
