### ISSUE TITLE
UI freezes when the auto-completion window pops up in large file.

### ISSUE THREAD

**Issue by goddade** [NationalSecurityAgency/ghidra#2630]
When I press Ctrl+Shift+G to patch instruction, an auto-completion window will pop up, and the UI will freeze for a long time.
Is there an option to close this window?

**Comment by Hatem-Saad** [comment]
I have the same issue.

**Comment by Form1ca** [comment]
same issue

**Comment by dragonmacher** [comment]
Presumably there is some long-running initialization that is happening in the UI thread.   We should be able to put this initialization into a background thread with a dialog to prevent the UI from locking.  Whether or not it can be cancelled once started is less clear.

**Comment by nsadeveloper789** [comment]
How large is the file, and what is the processor? Looking for info to reproduce it.

**Comment by Form1ca** [comment]
> How large is the file, and what is the processor? Looking for info to reproduce it.

178mb .dll file
x86 64bit

with new project just open dll without auto analyze - freeze about 10seconds
with analized - freeze about 40sec

**Comment by nsadeveloper789** [comment]
OK. From what I can tell, this has to do with auto-completion and symbols. We don't index symbols by name in the database (at least not yet), and so I end up loading all the symbols and indexing them during auto-completion, which is on the Swing thread :/ .

**Comment by Form1ca** [comment]
> OK. From what I can tell, this has to do with auto-completion and symbols. We don't index symbols by name in the database (at least not yet), and so I end up loading all the symbols and indexing them during auto-completion, which is on the Swing thread :/ .

In my case, I don't need symbols at all in the autocomplete. 
It is enough to output the syntax of the assembler commands.
Can add a setting - does not display symbols.

**Comment by nsadeveloper789** [comment]
I don't think a toggle is really necessary here. We do actually have an index on symbols names, but the SymbolTable API doesn't let us scan it. My plan is to fix that and then use it to significantly speed up the assembler's symbol search.

**Comment by unknown321** [comment]
Still an issue on 11.3.1. 

200mb x86:LE:64 binary, 600k symbols, binary is analyzed. UI becomes non-interactable for a couple of minutes after typing left bracket (`[`) into operands. Freezes keep happening in the same session even after the initial indexing.

![Image](https://github.com/user-attachments/assets/006ef65c-2f90-4ca7-9741-e0a2c212ceb6)

**Comment by nsadeveloper789** [comment]
Okay. I've opened a new internal ticket to try to track this, but I don't know when I'll actually get to it. I'm also going to open a new issue here on github.
