### ISSUE TITLE
How to skip importing files via HeadlessAnalyzer if AutoImporter doesn't find a loader.

### ISSUE THREAD

**Issue by usaribbon** [NationalSecurityAgency/ghidra#2636]
Hello,
I would like to import all execution file to Ghidra from specific folder and
I know that some files don't match a file loader of Ghidra.
(I got an error in HeadlessAnalyzer that `ERROR REPORT: Import failed for file:` `No load spec found for import file:`)

Could someone tell me an option to skip an import and continue importing next file if AutoImported fails to import?

Thank you !

**Comment by ghidra1** [comment]
If performing a recursive import of a directory's content, the import should report such an import error but continue importing/processing the remaining files.

**Comment by ryanmkurtz** [comment]
I've confirmed that even though Ghidra logs errors on files it cannot import, it does indeed continue pass the errors and import the rest of the files in the directory.
