### ISSUE TITLE
Key bindings not working in Function Graph view

### ISSUE THREAD

**Issue by monabomble** [NationalSecurityAgency/ghidra#2641]
**Describe the bug**
I frequently use Function Graph view and was previously able to insert EOL comments and edit function lables by placing my cursor on the desired instruction within a graph node and using the assigned key binding (e.g. SHIFT+L for label or SEMICOLON for comment). In 9.2 none of the key bindings appear to work. I have tried re-assigning and resetting to defaults. I have confirmed with others that they see the same behaviour.

**To Reproduce**
1) Open the code browser and switch to Function Graph view.
2) Place the cursor on any instruction in the body of a function and attempt to apply a comment using the SEMICOLON key or rename a variable using SHIFT+L
3) Nothing happens

**Expected behavior**
I would expect the Function Graph view to behave the same as the Listing view (where key bindings appear to work correctly). Also in Function Graph view I can apply labels or comments using the relevant context menu option, but this is obviously sub-optimal.

**Screenshots**
N/A - the behaviour results in no change at all.

**Attachments**
N/A The Ghidra User Log shows no entries during the times I try to use key bindings in Function Graph View.

**Environment (please complete the following information):**
 - OS: Pop_OS 20.04 LTS
 - Java Version:
    openjdk 11.0.9.1 2020-11-04  
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
 - Ghidra Version: 9.2

**Additional context**
[UPDATE] It appears that key bindings work in Function Graph view if the window is **undocked**. In the default (docked) layout, key bindings do not work.

**Comment by dragonmacher** [comment]
I confirmed this behavior.   As mentioned, they failure happens when docked in the primary tool window.

**Comment by ghidra1** [comment]
Corrected for 9.2.3 release
