### ISSUE TITLE
NullPtr 'FunctionDB.getCallingFunctions' when passing a null monitor.

### ISSUE THREAD

**Issue by wund3rcr4zy** [NationalSecurityAgency/ghidra#2643]
Using Ghidra Version: 9.2.1_PUBLIC

The JavaDoc api documentation states that the Function.getCallingFunctions Monitor parameter 'may be null'. In practice this caused a nullptr. 

[JavaDoc - getCallingFunctions](https://ghidra.re/ghidra_docs/api/ghidra/program/database/function/FunctionDB.html#getCallingFunctions(ghidra.util.task.TaskMonitor))

[JavaDoc - getCalledFunctions](https://ghidra.re/ghidra_docs/api/ghidra/program/database/function/FunctionDB.html#getCalledFunctions(ghidra.util.task.TaskMonitor))

This seems to be a simple case of requiring a null check before checking if the monitor is cancelled. I am willing to submit a PullRequest.

[Possible NullPtr Location](https://github.com/NationalSecurityAgency/ghidra/blob/881282d96a1712e94958de3f2820497a55c045c7/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/database/function/FunctionDB.java#L2730)

ERROR REPORT SCRIPT ERROR: <my script location> null (HeadlessAnalyzer) java.lang.NullPointerException
	at ghidra.program.database.function.FunctionDB.getCallingFunctions(FunctionDB.java:2725)

**To Reproduce**
Assuming analysis has already taken place on your input:
Run any script in headless mode while calling function.getCallingFunctions(null) on a valid function.

**Expected behavior**
The set of calling functions is returned.

**Comment by dragonmacher** [comment]
That should be fixed.  Until then, you can pass in `TaskMonitor.DUMMY` to prevent this.

**Comment by wund3rcr4zy** [comment]
Thanks for the follow up. I will use this workaround.

**Comment by ghidra1** [comment]
Corrected for 9.2.3 release
