### ISSUE TITLE
[Debugger] Bad practice in gadp.proto

### ISSUE THREAD

**Issue by nicolasnoble** [NationalSecurityAgency/ghidra#2648]
I've left a comment on the commit that added the gadp.proto file in the debugger branch [here](https://github.com/NationalSecurityAgency/ghidra/commit/8201baef2b1374709ccb84e2c1e143c155ba67cd#r45980752), but I thought it'd be also a good idea to open an issue and describe the problem.

The gadp.proto file you've created in the debugger branch is having enums that have bad keywords in them, such as UINT, VOID, or UNDEFINED. The code will be generated as-is in all languages, and particularly in C++ when compiling under Windows, a lot of these all-caps words will collide with Microsoft's headers.

For instance, winnt.h contains a `#define VOID void` which will make the resulting gadp.proto.h file not working fine when compiling under Windows with the Windows API included. This will greatly reduce the interoperability of ghidra with agents written in other languages.

The common way of creating enums here would be to prepend a small namespace, such as:

```
enum ExecutionState {
	ES_INACTIVE = 0;
	ES_ALIVE = 1;
	ES_STOPPED = 2;
	ES_RUNNING = 3;
	ES_TERMINATED = 4;
}

enum PrimitiveKind {
	PK_UNDEFINED = 0;
	PK_VOID = 1;
	PK_UINT = 2;
	PK_SINT = 3;
	PK_FLOAT = 4;
	PK_COMPLEX = 5;
}
```

**Comment by nsadeveloper789** [comment]
On it. Thanks for the tip.
