### ISSUE TITLE
Is there a way to retroactively map .dlls/.so's after the intiial project creation?

### ISSUE THREAD

**Issue by agnosticlines** [NationalSecurityAgency/ghidra#265]
Hi folks,

I've got a project I exported from an IDA database. 

Am I right in saying there's currently no way to tell Ghidra about program libraries/dependencies after the project has been initially created? If there is I can't find it in the documentation, and if there isn't I think this would be an important feature to add.

Thanks

**Comment by emteere** [comment]
If you have imported the .dll into your project, in the Symbol Tree for the program under Imports you can associate the DLL name with the program .dll you imported.  Just choose the name for the .dll, and then Set External Program.

It may be that the imports entries are missing from the imported IDA .xml file.  In which case the easiest thing might be to import the .exe into Ghidra, then apply the IDA export .xml file, but choose add to program.  You can selectively choose what to import, for example just names or comments.

**Comment by agnosticlines** [comment]
Yeah youre right, I thought it was the external program, turns out it's an issue with the IDA Pro plugin to export the XML form. I'm writing a fix, will pull request when the source is actually on here.

**Comment by agnosticlines** [comment]
I tried your suggestion, the mappings are off, I'll look into why that is in the plugin/IDB now. Appreciate your help.
