### ISSUE TITLE
Unable to build native binaries on new Mac with XCode 12

### ISSUE THREAD

**Issue by brian-rose-sp** [NationalSecurityAgency/ghidra#2653]
**Describe the bug**

I got a new Mac and started completely clean and  I followed the instructions for building Ghidra (building the debugger branch).  I installed XCode 12 and then built using `gradle buildGhidra`.  When building the native binaries, it fails with various "no member found" exceptions.  I have tracked it down to XCode 12 (apparently, 10+ as well) to not having the libstdc++ libs included or supported anymore and should be using libc++.  The instructions for building don't mention anything regarding this.  I think builds work for most people if they have had previous XCode versions or some other installations that have libstdc++.

Here is an example of on of the errors:

`sleighbase.cc:230:18: error: no member named 'emplace_back' in 'std::__1::vector<FloatFormat, std::__1::allocator<FloatFormat> >'
    floatformats.emplace_back();
    ~~~~~~~~~~~~ ^
`

**To Reproduce**
Steps to reproduce the behavior:
1) Use a completely clean Mac or a Mac with no libstdc++
2) Install XCode 12
3) run `buildNatives_osx64`

**Expected behavior**
The native binaries to build properly

**Environment (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7
 - Ghidra Version: latest debugger branch
 - Clang 12.0

**Comment by tomnelson** [comment]
I'm not sure this will solve everything, but it sounds similar to problems I was having with the M1 mac.
In the file Ghidra/Features/Decompiler/build.gradle, insert 

				b.cppCompiler.args "-std=c++11"

at around line 549 so it looks like this:

			else if (b.toolChain in Clang) {
				b.cppCompiler.args "-std=c++11"
				b.cppCompiler.args "-Wall"

Hope this helps. If it does, I will make a PR for it.

**Comment by tomnelson** [comment]
I just confirmed that on 10.15.7, the master branch fails without the above change but it builds after making the change.
The debugger branch also builds. I did not try running the debugger, however.

**Comment by d-millar** [comment]
@tomnelson Re debugger, there's no current support for lldb, and the versions of gdb commonly available for the Mac, e.g. homebrew, don't support the Pty interface we're using.

**Comment by brian-rose-sp** [comment]
> @tomnelson Re debugger, there's no current support for lldb, and the versions of gdb commonly available for the Mac, e.g. homebrew, don't support the Pty interface we're using.

So there will be no debugger support on OSX?  Or there just isn't yet?

**Comment by brian-rose-sp** [comment]
> I'm not sure this will solve everything, but it sounds similar to problems I was having with the M1 mac.
> In the file Ghidra/Features/Decompiler/build.gradle, insert
> 
> ```
> 			b.cppCompiler.args "-std=c++11"
> ```
> 
> at around line 549 so it looks like this:
> 
> ```
> 		else if (b.toolChain in Clang) {
> 			b.cppCompiler.args "-std=c++11"
> 			b.cppCompiler.args "-Wall"
> ```
> 
> Hope this helps. If it does, I will make a PR for it.

I just pulled your fix and it built successfully.  thanks!!

**Comment by d-millar** [comment]
@brian-rose-sp there isn't any yet - we had hoped current versions of lldb would support the gdb/MI out-of-the-box, but the lldb developers seem to have gone a different route. Support for osx will require building up a fresh model based on the lldb API, which is unfortunately a good bit more work.

**Comment by ghidra1** [comment]
The ability to build on an Apple M1 has been addressed for `patch` and `master`.  While builds for this platform will not be provided with standard distributions of Ghidra, it should build for a user on an M1 in support of the local architecture.
