### ISSUE TITLE
Scaling Overview/Entropy.

### ISSUE THREAD

**Issue by Marsfan** [NationalSecurityAgency/ghidra#2656]
I am working on disassembling a flat binary file for the LPC11U3x series of microcontrollers. However, this binary file does not cover the entire memory space of the processor. As a result, once I set up all of the memory regions, I have a large amount of space in my project that is filled with undefined bytes, and only a small portion that actually has data. The end result is that after defining the memory regions, the Entropy and Overview sidebars are largely unusable, as most of them is simply black. 

Is there a way to scale or minimize portions of the overview and entropy displays, so that I have I can have a better visualization of the data? 

My apologies if this is a simple question, I am just starting to learn about reverse engineering. 

Example: 
![image](https://user-images.githubusercontent.com/9311953/104856654-2b222800-58d1-11eb-8465-869baea36e09.png)

**Comment by Tim---** [comment]
Hi,

There are several ways that come to mind:

You can can use the "Program Tree" window to create a new tree. You will be able to add or remove the segments you're interested in. And you can always switch back to the original tree to see all the segments.

Creating arrays is also a good solution if you have large chunks of data you don't care about. This will reduce the size of the data in the margin.
If you want to automatically condense long runs of the same byte (00 or ff for example), you can use on of the Condense* scripts in the "Script Manager".

**Comment by Marsfan** [comment]
@Tim--- Thank you very much. Turns out I don't even need to change anything. Just double clicking on the memory region in the program tree zoomed in to the region that I wanted to examine.
