### ISSUE TITLE
[question] SLEIGH: How to use tables describing multiple operands with pcode? 

### ISSUE THREAD

**Issue by black-caviar** [NationalSecurityAgency/ghidra#2659]
I am working on a Zilog Z8 processor module. Z8 microcontrollers have no internal RAM and instead use a large 256 byte register file containing 236 general purpose registers. 
``` 
define endian=big;
define alignment=1;

define space pmem    type=ram_space      size=2  ;
define space reg     type=register_space size=1  default;
```
The most common instruction pattern encodes the addressing mode in the lower nibble of the first instruction byte which then determines the length of the entire instruction (either 2 or 3 bytes). There are a total of 6 addressing modes that I have described in the following table. 
```
define token opbyte (8)
  op8 = (0,7)
  op4_4 = (4,7)
  op0_4 = (0,3)
;
define token data8 (8)
  reg0_4 = (0,3)
  reg4_4 = (4,7)
;
define token data16 (16)
  reg0_8 = (0,7)
  reg8_8 = (8,15)
;
# modes 2 & 3 use 4 byte "work group" addressing
addrmode: "r"^reg4_4,"r"^reg0_4 is op0_4=2; reg4_4 & reg0_4 {}
addrmode: "r"^reg4_4,("r"^reg0_4) is op0_4=3; reg4_4 & reg0_4 {}
# other modes use byte addressing
addrmode: reg0_8,reg8_8 is op0_4=4; reg8_8 & reg0_8 {}
addrmode: reg0_8,(reg8_8) is op0_4=5; reg8_8 & reg0_8 {}
addrmode: reg8_8,"#"^imm8 is op0_4=6; reg8_8 & imm8 {}
addrmode: (reg8_8),"#"^imm8 is op0_4=7; reg8_8 & imm8 {}

#ADD dst,src 
:ADD addrmode is op4_4=0 ... & addrmode {}
```
This makes describing instructions very easy, but I don't see how I can use this for pcode representations. In this case addrmode represents two opperands but I don't know how to separate them. The solution I came up with involves creating separate tables for each operand but that duplicates essentially the same code. 
```
# work group addressing works by combining the upper nibble of the 
# register pointer with a 4-bit register operand into an 8 bit address
rshort_l: "r"^reg0_4 is reg0_4 {
	local RP_copy = RP;
	local tmp:1 = *[reg]:1 (RP_copy & 0xF0 + reg0_4);
	export tmp;
}
rshort_h: "r"^reg4_4 is reg4_4 {
	local RP_copy = RP;
	local tmp:1 = *[reg]:1 (RP_copy & 0xF0 + reg4_4);
	export tmp;
}
dst: rshort_h is op0_4=2; rshort_h {export rshort_h;}
src: rshort_l is op0_4=2; rshort_l {export rshort_l;}
dst: rshort_h is op0_4=3; rshort_h {export rshort_h;}
src: (rshort_l) is op0_4=3; rshort_l {export *[reg] rshort_l;}
dst: reg0_8 is op0_4=4; reg0_8 {export * reg0_8;}
src: reg8_8 is op0_4=4; reg8_8 {export * reg8_8;}
#... incomplete specification 
:ADD dst,src is op4_4 = 0x0 ... & dst & src {
	dst = dst + src;
	#setflags(dst)
}
```
How can I rewrite this to be less confusing with less code duplication? 
As a reference I am using the Zilog Z8 user manual which is available from their website. The instruction summary begins on page 157. 
http://www.zilog.com/docs/um0016.pdf

**Comment by esaulenka** [comment]
Try to use contextreg.
For example, save `op0_4` into context reg `addrmode` and then check it in `src`/`dst` tables.

But I didnt understand. If you have only 8 pairs of `src`/`dst` variants that are suitable for any instruction, I think its a better way to describe it all once.

**Comment by Danil6969** [comment]
> How can I rewrite this to be less confusing with less code **duplication**?

On this page:
https://ghidra.re/courses/languages/html/sleigh_constructors.html#sleigh_with_block
Almost the same thing you need is described:
"To avoid tedious **repetition** and to ease the maintenance of specifications already having many, many constructors and tables, the with block is provided."
But you must omit table header as src and dst are different. Like so:
```
with : op0_4=2 {
  dst:rshort_h is rshort_h {export rshort_h;}
  src:rshort_l is rshort_l {export rshort_l;}
}
with : op0_4=3 {
  dst:rshort_h is rshort_h {export rshort_h;}
  src:(rshort_l) is rshort_l {export *[reg] rshort_l;}
}
```
(Assuming you group by op0_4 restriction, did not consider other grouping variants though but they exist as well)

**Comment by ghidra1** [comment]
Without digging in deep, my first reaction is that you are not leveraging register attach tables which could simplify what you are attempting.  The various token fields which correspond to a register decode should have registers attached to them.  The following example is from *z80.slaspec*:
`attach variables [ reg0_3 reg3_3 ] [ B C D E H L _ A ];`
