### ISSUE TITLE
Low-level Error: Trying to find whole on free varnode

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#266]
https://www.carpeludum.com/download/Fusion364.zip
File: `Fusion.exe`

WinMain function at 0x45C990 cannot be decompiled with this error: `Low-level Error: Trying to find whole on free varnode`.
What does it mean and how to fix?

**Comment by saruman9** [comment]
What version of Ghidra are you using? I can't reproduce the error.

**Comment by lab313ru** [comment]
9.0.1 on Windows 10 x64

**Comment by saruman9** [comment]
I was able to reproduce the bug only when use Decompiler Parameter ID analyzer. I advise using this analyzer only when a lot of information about function is known. But I could be wrong.

> Decompiler Parameter ID
> This analyzer can be quite useful when you have some rich type information, such as known types from library calls. However, if you run this analyzer too early or before fixing problems, you can end up propagating bad information all over the program.
> Note: this analyzer will commit the signature of each function.

I have not found any information about error message of decompiler (found only during reverse engineering `decompile` executable).

**Comment by lab313ru** [comment]
I thought, that it decompiles all functions and then uses that info for specifying parameters. Really, I don't know how it works.

**Comment by lab313ru** [comment]
It works now.
