### ISSUE TITLE
Cannot cancel 'Connecting to server...' for shared project

### ISSUE THREAD

**Issue by grant-h** [NationalSecurityAgency/ghidra#2661]
**Describe the bug**
If a shared project has been moved and the DNS entry has been changed, connecting to it cannot be canceled in a timely manner.

**To Reproduce**
1. Connect to a previously available shared project
2. It will show 'Connecting to ...'
3. Hit the red X to cancel and hit yes
4. It still says connecting

**Expected behavior**
The operation should cancel immediately and fallback to an offline view (if it was synced before) or to a blank project if this is a first time connection

**Environment (please complete the following information):**
 - OS: macOS 10.14.6
 - Java Version: 11.0.2
 - Ghidra Version: 9.2 PUBLIC

Related to issue #2660

**Comment by fmagin** [comment]
This also applies when you have a server that is only accessible from a VPN, you forgot to activate the VPN beforehand and some firewall prevents you from even getting the response that the port is closed.

**Comment by ghidra1** [comment]
I have added as an enhancement task, although no target release has been established

**Comment by larsw** [comment]
Just to chip in, I can confirm that this issue still exists in 10.0.

![ghidra-server-cancel](https://user-images.githubusercontent.com/63235/141643713-0f444f01-dbd2-425d-bc47-db6a4ce83011.png)
4
