### ISSUE TITLE
C-PARSER cannot parse __declspec(deprecated("abc" "def"))

### ISSUE THREAD

**Issue by madebr** [NationalSecurityAgency/ghidra#2666]
**Describe the bug**
The Windows SDK headers use `__declspec(deprecated(...)` to annotate functions and structs as deprecated.
This construct can be found in `ucrt\corecrt_memory.h`, `ucrt\corecrt_wstring.h`, `ucrt\string.h`.
Ghidra's C parser does not recognize this.

The string is splitted in multiple strings, which is valid C syntax.

**To Reproduce**
1. Create a header with the following contents:
    ```c
    __declspec(deprecated("abc" "def"))
    void old_function(void);
    ```
2. Add this header in the `Parse C Source` util in the `CodeBrowser`
3. Click on `Parse to File` or `Parse to Program` + click OK until it starts parsing

**Expected behavior**
Parsing works and gdt is created or added to program datatype manager.

**Screenshots**
![image](https://user-images.githubusercontent.com/4138939/105139662-d3650600-5af6-11eb-9eb6-7e5488b0d2dc.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 14.0.2 2020-07-14
 - Ghidra Version: 9.2.1

**Additional context**
I am trying to parse Windows' `ddraw.h`.+

**Comment by therealchjones** [comment]
You note that there are several ucrt headers that describe the __declspec(deprecated(...)). However, it appears these are not listed in the parsing dialog from your screenshot. They need to be listed before deprecated.h in order for those to be recognized. (See #716 for a similar problem and more details.)  It's certainly possible that the C parser still won't get it, but the parser is quite basic---it certainly won't work without explicitly defining the construct before using it.
