### ISSUE TITLE
Debugger for Ghidra?

### ISSUE THREAD

**Issue by Wolfhounds227** [NationalSecurityAgency/ghidra#267]
Hi I noticed you have the ability to add plug-ins, do you have any compatible plug-ins to add a debugger feature? Or is there a built in debugger in the near future planned?

**Comment by ImNotAVirus** [comment]
There is currently no way to debug your code but yes, the NSA seems to be working on it.

Cf. https://github.com/NationalSecurityAgency/ghidra/issues/24#issuecomment-470676329
