### ISSUE TITLE
Ghidra collapse when I switch input method to Chinese

### ISSUE THREAD

**Issue by Coldwave96** [NationalSecurityAgency/ghidra#2678]
**Describe the bug**
Every time when I switch input method to Chinese, Ghidra collapse. Even when I switch input method in another APP, Ghidra also collapse.

**To Reproduce**
1. Open Ghidra
2. Switch input method to Chinese
3. Ghidra collapse

**Screenshots**
![截屏2021-01-25 15 11 46](https://user-images.githubusercontent.com/14369991/105672654-c04f9d00-5f1f-11eb-9a28-293ba75955b4.png)

![截屏2021-01-25 15 12 23](https://user-images.githubusercontent.com/14369991/105672713-d65d5d80-5f1f-11eb-992d-a75aea597060.png)

**Environment (please complete the following information):**
 - OS: macOS 11.1
 - Java Version: 11.0.10
 - Ghidra Version: 9.2.2

**Comment by jpleasu** [comment]
This appears to be an issue with the JDK itself: https://bugs.openjdk.java.net/browse/JDK-8257242
