### ISSUE TITLE
Pixelated Icon when creating desktop file

### ISSUE THREAD

**Issue by Mindslave** [NationalSecurityAgency/ghidra#2679]
Hey,

I just installed Ghidra on a new Linux (Fedora) device. I wanted to create a desktop file for it. While I was able to do so no problem I noticed that the Icon in $hdira_path/support/ghidra.ico is a pixelated mess for me. I don't know too much about image files and have no idea why this might happen, but it also occurs if I download the icon from https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/RuntimeScripts/Windows/support/ghidra.ico

This is how the icon looked for me:

![ghidra-icon-pixels](https://user-images.githubusercontent.com/38843153/105737594-6c9c7e00-5f36-11eb-9c82-314e93b170ac.png)

**Comment by dev747368** [comment]
Yes, under linux the Windows icon does look bad.  I don't know enough about the icon format (or what linux considers the icon file format) to know if linux should be able to recognize / disregard a Windows icon or not.
