### ISSUE TITLE
Decompiler doesn't work with refs to overlay

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#2680]
So, the problem is related to: #1412 
When double clicking at any overlayed ref in the decompiler output, Ghidra points you at the default RAM: space, not into overlayed one.

Output:
![изображение](https://user-images.githubusercontent.com/7189309/105748997-e42cd600-5f53-11eb-94ff-c38585f08813.png)

Double clicked in the decompiler:
![изображение](https://user-images.githubusercontent.com/7189309/105749098-06beef00-5f54-11eb-8af3-a03da8e6cc2c.png)

Double clicked in the disassembly:
![изображение](https://user-images.githubusercontent.com/7189309/105749192-23f3bd80-5f54-11eb-910c-d463036463fc.png)

**Comment by lab313ru** [comment]
By the way, double clicking in the decompiler's output based on Overlayed code works how it's needed.

**Comment by lab313ru** [comment]
Any updates?

**Comment by lab313ru** [comment]
So, the problem is that the decompiler doesn't know anything about any new overlayed space. It can only convert `const` into the `ram` space.

Here is that line:
https://github.com/NationalSecurityAgency/ghidra/blob/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1/Ghidra/Features/Decompiler/src/decompile/cpp/coreaction.cc#L1136

That `inferPtrSpaces` is only updated in these places:
https://github.com/NationalSecurityAgency/ghidra/blob/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1/Ghidra/Features/Decompiler/src/decompile/cpp/architecture.cc#L680

and:
https://github.com/NationalSecurityAgency/ghidra/blob/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1/Ghidra/Features/Decompiler/src/decompile/cpp/architecture.cc#L816

which are only callable at the project opening.

**Comment by lab313ru** [comment]
The initial bug isn't fixed!

**Comment by donnie-j** [comment]
I am having issues with the decompiler and overlays also.  Attached is a 8039 (8048) ROM from an HP 3468 meter.

Steps to reproduce:

- New project
- Import file [3468-65501.bin.gz](https://github.com/NationalSecurityAgency/ghidra/files/10291573/3468-65501.bin.gz) (gunzip first)
  Language 8048
  Options
    Block Name: block1
    File offset 0x1000
    Length 0x1000
- Open file
  Don't analyze
- Add To Program
  Same file
  Options
    Overlay
    Block Name: block0
    File offset 0x0000
    Length 0x1000
    Processor labels off
- Select block1, Auto Analyze All Open
- Select block0
   Select addr range 0-0x0fff
- Disassemble
- Select block1

So far, so good.  From this point, either user error or a bug

- At block1 addr 0009 function
  ANL P1, #0xef  _<- switch to bank 0_
  Function -> Select Thunked Function:  block0::000c
- Double click block1 0009 function takes us to block0 000c (good)
- block1 0009 function has no way to know the bank switches, set NOP fall through to bank0 _<- is this the correct way?_
- block1 000b
   Fallthough -> Set -> User, block0:: 000c

 Low-level Error: Could not find op at target address: (block0,0x000c)

**Comment by lab313ru** [comment]
They closed it as resolved, but isn't.

**Comment by fenugrec** [comment]
> I am having issues with the decompiler and overlays also. Attached is a 8039 (8048) ROM from an HP 3468 meter.

Have you tried the patches from https://github.com/NationalSecurityAgency/ghidra/pull/4825 ? I take a different approach for this kind of 8048 ROM with software banking, it works quite well on the 3478 ROM !
