### ISSUE TITLE
Data Type Manager: Cannot specify both size and alignment of structure

### ISSUE THREAD

**Issue by LunarLambda** [NationalSecurityAgency/ghidra#2681]
In my workflow, when defining a new structure, usually the first thing I want to do is specify its size and alignment, since that is the minimum amount of information needed to for example define arrays.

However, when ticking the align box in the structure editor, it forcibly resets the size I specified.

Not being able to specify the size is fine when all members of the structure are known, but for potentially huge structures, manually specifying padding between dozens or hundreds(!) of fields quickly becomes tedious and error-prone, especially since offsets cannot be edited directly, only the padding inserted between (known) fields.

Is it meant to work like this? Is there a better approach to procedurally filling in large structs?

**Comment by ghidra1** [comment]
Yes, it is intended to work as you observed.  There is a fundamental issue currently with non-aligned composites in Ghidra - their external alignment is always 1.  Aligned composites are sized based upon their content.  If you want to utilize an aligned composite without knowing the content, you will have to use filler bytes (e.g., undefined1) and set the alignment explicitly.  Ideally, you should be able to set the alignment on a non-aligned composite.

**Comment by ghidra1** [comment]
Composite revision have been completed which now allow this.
