### ISSUE TITLE
Cleaning up decompiled code

### ISSUE THREAD

**Issue by Marsfan** [NationalSecurityAgency/ghidra#2683]
I have been using Ghidra for analysis of microcontrollers. While the decompilation does a pretty good job, it sometimes adds additional lines of code that are unnecessary, or creates a large number of unnecessary variables. 
Is there a way to edit/tweak the decompilation (whether manually or by adjusting settings)? 

Below is an example of Ghidra adding unnecessary lines of code, and the actual source code that it decompiled. Note the creating of an unnecessary variable, and the stretching of single lines of code into two lines each. 

**Decompiled By Ghidra**
![image](https://user-images.githubusercontent.com/9311953/105813049-7640d880-5f6c-11eb-8def-3aa8e664a8e4.png)
**Original Source Code**
![image](https://user-images.githubusercontent.com/9311953/105813065-7b9e2300-5f6c-11eb-988f-e05e5915e30d.png)

**Comment by Danil6969** [comment]
Explicit varnode automatically stretches single line into two lines every time so there's no wonder. The register (global varnode) representing bVar1 was read (has descendants) so many times that the decompiler decided that explicit variable is more feasible than implied. Currently decompiler does not count writes to the same varnode so this is actually the first thing to implement. If it would count writes then it could reset reads count but this requires additional checks along with counting descendants.

**Comment by Marsfan** [comment]
@Danil6969 I am a total beginner with this stuff. If I am understanding you correctly there is no way I can tell the compiler to make stuff single lined like in the original source code, as the decompiler tries to make one line per instruction?

Or are you saying it is something to do with how the registers are defined? I copied and modified the avr8 pspec file to add the registers for the specific AVR microcontroller that I am using, is that not the optimal way?

**Comment by jpleasu** [comment]
@Marsfan  The `read_volatile` and `write_volatile` functions are there to preserve semantics:   see code browser -> Help -> contents -> search "volatile" -- their use "prevents constant propagation and other transforms" by the decompiler analysis. (note there is no `volatile` type qualifier in the Ghidra type system)

If you're asking about eliding the `bVar1` temps for a tidier syntax (like `write_volatile_1(x,read_volatile_1(x)&7f)`), it's been considered, but nothing concrete is planned.

<welcome_to_the_rabbit_hole>
If you really want the decompiler to avoid inserting the read/write-volatile builtins **at the cost of over-aggressive simplification and potentially incorrect decompilation results**, you can do this pretty easily by editing `Ghidra/Processors/Atmel/data/languages/avr8.pspec` (or `atmega256.pspec` depending on your language type).  Just comment out the `<volatile>...</volatile>` section (e.g. -> `<!-- <volatile>...</volatile> -->`), and re-open your program.

Note -- I tested this out and it lead to dead code elimination _I really didn't want_. Just understand that you're breaking the warranty if you do this :-)
</welcome_to_the_rabbit_hole>

**Comment by Marsfan** [comment]
@jpleasu Cool. My concern is more about getting rid of the bVar1 temps. Being able to drop them would go a long way towards making the code look more like the original, so I guess you can consider this my support for being able to simplify code that way. Maybe have a option in settings to switch between modes. 

`read volatile` and `write volatile` are actually somewhat useful for me as they provide a reminder that something is being done to a peripheral register, so I don't really care about whether or not I can see them.

**Comment by fmagin** [comment]
Can you split out the `bVar1` variable after each use? Then Ghidra might treat them as separate variables, each just written and read once and might start to inline them. `Commit Locals` then right click on a new write to bVar1 and select "Split out" or something like that in the context menu.

**Comment by Marsfan** [comment]
@fmagin I am pretty busy with other stuff right now, but I will look into that when I have time.

**Comment by Marsfan** [comment]
Just realized I never got back to this. I never got rid of the `read_volatile` and `write_volatile` stuff, so I just learned to live with it. Closing this
