### ISSUE TITLE
MAX_UNIQUE_SIZE may be also used in other 2 java files

### ISSUE THREAD

**Issue by Danil6969** [NationalSecurityAgency/ghidra#2693]
Just to make 128 byte uniques support more complete.
This line:
https://github.com/NationalSecurityAgency/ghidra/blob/ceba3171b767a95ba0c922d442d2e064f22e4db0/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/pcodeCPort/slgh_compile/PcodeParser.java#L136
And probably (not sure) this one:
https://github.com/NationalSecurityAgency/ghidra/blob/ceba3171b767a95ba0c922d442d2e064f22e4db0/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/lang/PcodeInjectLibrary.java#L163
Also should use SleighBase.MAX_UNIQUE_SIZE instead of 16 due to added support of extended sizes (128 bytes) of uniques just like in these two lines:
https://github.com/NationalSecurityAgency/ghidra/blob/ceba3171b767a95ba0c922d442d2e064f22e4db0/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/pcodeCPort/slgh_compile/SleighCompile.java#L695
https://github.com/NationalSecurityAgency/ghidra/blob/ceba3171b767a95ba0c922d442d2e064f22e4db0/Ghidra/Features/Decompiler/src/decompile/cpp/slgh_compile.cc#L1920

**Comment by ghidracadabra** [comment]
Good eye!  Thanks for letting us know!
