### ISSUE TITLE
Failed to find a supported JDK in mac OS

### ISSUE THREAD

**Issue by gagaxiaolong** [NationalSecurityAgency/ghidra#2697]
+ macOS Catalina 10.15.4
+ ghidra-Ghidra_9.2.2_build
+ Java JDK 11.0.7

Java is already installed:
```
$ java --version
java 11.0.7 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```

Java Path:
```
echo $PATH
/Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home/bin
```

which java
```
$ which java
/Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home/bin/java
```

I download Ghidra_9.2.2_build from Github, Then execute the command:
```
~/Downloads/ghidra-Ghidra_9.2.2_build/Ghidra/RuntimeScripts/Linux ⌚ 10:49:51
$ ./ghidraRun
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport

Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section.
``` 

Above is what I see. Actually, I tried multiple java versions like AdoptOpenJDK and Oracle Java JDK, All encountered the same problem.

Any suggestions are appreciated!

**Comment by xiaoyinl** [comment]
The Ghidra_9.2.2_build file on GitHub is Ghidra's source file. You need to build it first, and then run it.

**Comment by ryanmkurtz** [comment]
Calling the scripts in `RuntimeScripts` will only work if you've imported all of the projects into Eclipse and Eclipse successfully compiled Ghidra without errors.  If you will not be setting up Eclipse for Ghidra development, you'll have to do a full `gradle buildGhidra` build like @xiaoyinl mentioned.

**Comment by gagaxiaolong** [comment]
Thanks for your reply! I'm not familiar with Java Project. Is there a tutorial for a beginner that to use gradle to build Ghidra. I tried to build Ghidra like below:
```
cd ~/Downloads/ghidra-Ghidra_9.2.2_build
gradle --init-script gradle/support/fetchDependencies.gradle init
gradle buildGhidra
```

The same error occurred:
```
$ ./Ghidra/RuntimeScripts/Linux/ghidraRun
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport

Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section.
```

**Comment by xiaoyinl** [comment]
The guide for building Ghidra is at https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md. If you have successfully built Ghidra, there should be a zip file at `./build/dist/`. Unzip it, and run the `ghidraRun` from the unzipped files.

**Comment by gagaxiaolong** [comment]
Thanks a lot! Everything is OK now! It seems that I ignored the important Developer's Guide.
