### ISSUE TITLE
Ghidra no longer handles script files that are symlinks

### ISSUE THREAD

**Issue by aamcintosh** [NationalSecurityAgency/ghidra#2698]
**Describe the bug**
Ghidra cannot handle user scripts that are symlinks.  It complains that "script" is null.   This used to work, but broke after a recent upgrade.

**To Reproduce**
```
$ cd $HOME/ghidra_scripts
$ mkdir ../foo
$ sed 's/HelloWorldScript/HelloWorldScript2/' /opt/ghidra/Ghidra/Features/Base/ghidra_scripts/HelloWorldScript.java > ../foo/HelloWorldScript2.java
$ ln -s ../foo/HelloWorldScript2.java .
$ # Sanity check...
$ grep HelloWorldScript2 HelloWorldScript2.java
public class HelloWorldScript2 extends GhidraScript {
```
1. Bring up Script Manager window
2. Click on 'Refresh Script List'
3. Note that HelloWorldScript2 is now visible.
4. Select HelloWorldScript2 and then select 'Run Script' or just double click on HelloWorldScript2
5. Console says `> Unable to locate script class: HelloWorldScript2.java`
6. See error as shown in attached screen dumps.
It makes no difference if the symlink is absolute instead of relative.

**Expected behavior**
Execute the script.

**Screenshots**
![ghidra-manager](https://user-images.githubusercontent.com/6467050/106232615-70dccb80-61c2-11eb-95a0-7e2cedbbb182.png)
![ghidra-error](https://user-images.githubusercontent.com/6467050/106232631-7a663380-61c2-11eb-9340-538c79fa580e.png)

**Attachments**
Screenshots of the script manager and the expanded error window.

**Environment (please complete the following information):**
Does not work with:
 - OS: Ubuntu 20.04
 - Java Version: 15.0.2
 - Ghidra Version: 9.2.2_PUBLIC
Works with:
 - OS: Ubuntu 18.04
 - Java Version: 11.0.7
 - Ghidra Version: 9.1.2_PUBLIC
 
**Comment**
Sorry that several things changed at once.

**Comment by ghidra1** [comment]
Merged for Ghidra 9.2.3

**Comment by H0r53** [comment]
Still receiving this issue in Ghidra 9.2.3. Custom scripts will not run unless directly placed in `Ghidra/ghidra_9.2.3_PUBLIC/Ghidra/Features/Base/ghidra_scripts`

**Comment by ryanmkurtz** [comment]
I'll take a look.

**Comment by ryanmkurtz** [comment]
I created a custom script and put it in `$HOME/foo/`.  I then went into Ghidra's Script Manager, clicked "Manage Script Directories", added `$HOME/foo/`, then my script appeared in the Script Manager table.  When I doubled clicked it, it ran successfully.  Is this similar to what you did?

**Comment by H0r53** [comment]
I seem to be able to run my scripts from`$HOME/ghidra_scripts/` after adding that directory to the Ghidra Script Manager. However, I was originally attempting to run the scripts from a directory within my Eclipse project. Something like `~/MyProject/ghidra_scripts/` does not work. Within `~/MyProject/` is a build.gradle file and a couple of other files. Would that effect anything? It's very strange that none of the scripts within this project directory can execute (they did work some time in the past). I use Eclipse when developing Ghidra extensions so it would be nice to have the scripts centrally located here if possible. Any ideas?

**Comment by H0r53** [comment]
This may be related. In the Bundle Manager under my Eclipse project dir I'm seeing this under Build Summary: `activating bundle: RESOLVE_ERROR -  me.ayrx.apat.decompiler`.

**Comment by ryanmkurtz** [comment]
Is `MyProject` an Eclipse module project that you created with the GhidraDev Eclipse plugin?

**Comment by H0r53** [comment]
Yes

**Comment by ryanmkurtz** [comment]
Are you launching Ghidra via the `My Project` Ghidra run configuration in Eclipse?

**Comment by H0r53** [comment]
No :( That fixed it. My apologies for the simple issue, but thank you for your patience and assistance!

**Comment by ryanmkurtz** [comment]
Sure thing.  When you launch Ghidra via Eclipse that way, the GhidraDev plugin passes along your project's path to Ghidra via a JVM argument so Ghidra knows to include it as a new module.
