### ISSUE TITLE
How to create new Function ID signatures

### ISSUE THREAD

**Issue by agnosticlines** [NationalSecurityAgency/ghidra#270]
Hey,

Last question, I've read all the docs and can't find any references to buliding new function ID signatures, I wanted to build fID sigs for core c functions like strcpy as currently it doesn't correctly name the variables, and for some reason won't keep the names I give it.

How would I go about building a new FID set?

I'd also like to make some for the WDK

As an example, the types and naming for a known function is messed up:

![2019-03-27-12:29:49](https://user-images.githubusercontent.com/23334509/55075961-26e9a280-508c-11e9-8665-29e6b538f7db.png)

and if I copy the declaration from the msdn docs: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strncpy-strncpy-l-wcsncpy-wcsncpy-l-mbsncpy-mbsncpy-l?view=vs-2017

Ghidra can't understand `const char`, how would I go about correctly filling this in? I don't want to make a new issue as I'm sure it's just me being dumb.

**Comment by partoftheworlD** [comment]
%Ghidra%/Features/FunctionID

The file common_symbols_win32.txt contains the symbols that were considered common when generating the
.fidb files for Windows 32-bit system code.

The main entry point for building adding libraries to a .fidb file is the dialog
      Tools -> Function ID -> "Populate FidDb from programs ...".
This takes on optional file parameter called "Common Symbols File".  The .fidb files currently being
distributed with Ghidra were generated by supplying common_symbols_win32.txt here.
After a library is built, starting from this dialog, a final window provides a list of the most
common symbols encountered for that particular library.  For Windows system code, the top 70 or so symbols from
each list, generated for the libraries listed below, were merged and deduped to produce the final common_symbols_win32.txt.

Visual Studio 1998 Debug
Visual Studio 1998 Release
Visual Studio 2003 Debug
Visual Studio 2003 Release
Visual Studio 2005 Debug
Visual Studio 2005 Release
Visual Studio 2008 Debug
Visual Studio 2008 Release
Visual Studio 2010 Debug
Visual Studio 2010 Release
Visual Studio 2012 Debug
Visual Studio 2012 Release
Visual Studio 2015 Debug
Visual Studio 2015 Release

Each .fidb was generated by supplying common_symbols_win32.txt as the "Common Symbols File" parameter.
After this completed, adjustments were performed by running the RemoveFunctions.java script on the database.
This makes the following modifications:

1)  Auto-fail is set for functions which match a list of full hashes.
2)  Auto-fail is set for functions whose name matches specific regular expressions.
3)  Force-relation is set for functions which match a list of full hashes.
4)  Force-specific is set for functions which match a list of full hashes.
5)  Auto-pass is set for functions which match a list of full hashes.

Auto-fail means a full-hash match will not be returned under any circumstances (even though the function is still in the database)
Force-relation means a full-hash match will only be returned if one of the function's parents or children also matches.
Force-specific means a full-hash match will only be returned if the specific hash matches as well.
Auto-pass means a full-hash match is always returned, even if the function is tiny.

The final .fidb was defragmented using the RepackFid.java script to make the disk image as small as possible.

**Comment by agnosticlines** [comment]
Can these txt files contain parameter names? How did you generate this initial list, is it just the mangled symbols list?

**Comment by agnosticlines** [comment]
Also I'm right in saying there's no way to build that text file from within ghidra right? If you've got a library like libc.so loaded, and everything renamed, there's no way to export that into the format for fID?

**Comment by partoftheworlD** [comment]
Additional information in ghidra help, search "Function ID Plug-In", i think it's what you need.

**Comment by agnosticlines** [comment]
Ah, I didn't have the debug tools enabled. Thank you, it might be worth making an issue for an enchancement to make it easier to hash individual functions
