### ISSUE TITLE
Another 9.2 "Invalid block name" regression: Importing Mach-O files

### ISSUE THREAD

**Issue by LeonardKoenig** [NationalSecurityAgency/ghidra#2702]
**Describe the bug**
When importing a mach-o object file, the following stack trace is printed and the file cannot be imported:

```
Invalid block name: 
java.io.IOException: Invalid block name: 
at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:101)
at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:349)
at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:88)
at ghidra.util.task.Task.monitoredRun(Task.java:124)
at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
```

**To Reproduce**
1. Download the Mach-O fat binary at https://github.com/SafeExamBrowser/seb-mac/blob/9f0b0d082e21bf98628e7299fc8e8adc5bf211be/SEB/Frameworks/libSEBSupport.a
2. Use the `llvm-lipo` tool to extract a thin binary, e.g.:
   ```
   $ llvm-lipo -thin arm64 libSEBSupport.a -output libSEBSupport-arm64.a
   ```
3. Import the file as "Batch Import"
4. No file could be imported, despite a .o being listed (which is probably a separate UX bug, as it "silently" errors)

In order to see the file, first extract the archive using `ar -xvf libSEBSupport-arm64.a` and import the (only) resulting object file.

**Expected behavior**
The file is imported correctly, as with Ghidra v9.1.  If an import error occurs, the import error is printed, instead of simply silently failing.

~~**Screenshots**~~
~~If applicable, add screenshots to help explain your problem.~~

**Attachments**
GitHub doesn't allow uploading files with a .o extension, **so I renamed it .zip**:
[UIWindow+SEBExtensions.o.zip](https://github.com/NationalSecurityAgency/ghidra/files/5894887/UIWindow%2BSEBExtensions.o.zip)

**Environment (please complete the following information):**
 - OS: Current ArchLinux [testing] on 5.10.11-zen2-1-zen
 - Java Version: tested 11.0.10.u8 and 15.0.1.u9
 - Ghidra Version: 9.2.2

**Additional context**
The binary loads fine in IDA as well.  From https://github.com/NationalSecurityAgency/ghidra/issues/2354 with 9.2:
> Block naming constraints have been tightened for 9.2 so it may have gone through without detection in 9.1.

Unfortunately the linked PR https://github.com/NationalSecurityAgency/ghidra/pull/2329 only fixed imports with PE files, not mach-o files.

**Comment by ghidra1** [comment]
The block appears to have no name.  When this same binary was loaded with Ghidra 9.1 what was the resulting block name.  It should have been shown in the error message above but it appears to be blank.

**Comment by LeonardKoenig** [comment]
@ghidra1 I attached an object module.  Is there a way to tell "at" which block it fails, or some way I can help track down the issue?

**Comment by ghidra1** [comment]
Debugger would be the easiest at `MemoryBlockDB.checkBlockName(String name)`.  There error printed out indicates the requested block name which is clearly blank.  My guess is that the Macho loader is not handling a missing block name.  I am curious what block names you see when imported with 9.1.

**Comment by ghidra1** [comment]
I am getting an error on the zip file you provided.

**Comment by LeonardKoenig** [comment]
@ghidra1 The file is no ZIP.  As noted above I only renamed it to get around the absurd GitHub name filter.  Sorry for the confusion.

I'm firing up the debugger, long time no Java for me :)

**Comment by LeonardKoenig** [comment]
@ghidra1 I just built master and I get `""` as name.  Now building under 9.1, but I suppose it's likely the same but simply "ignored"?

**Comment by ghidra1** [comment]
The name is read straight from the Macho header and is never checked

**Comment by LeonardKoenig** [comment]
With your hint with breaking at `checkBlockName()` I was able to build a patch like similar to the one in the above linked PR and I can confirm it works now!

```diff
diff --git a/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MachoProgramBuilder.java b/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MachoProgramBuilder.java
index e77ad1cf8..40f7791d0 100644
--- a/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MachoProgramBuilder.java
+++ b/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MachoProgramBuilder.java
@@ -18,6 +18,7 @@ package ghidra.app.util.opinion;
 import java.math.BigInteger;
 import java.util.ArrayList;
 import java.util.List;
+import java.util.ListIterator;
 
 import ghidra.app.util.MemoryBlockUtils;
 import ghidra.app.util.bin.ByteProvider;
@@ -215,15 +216,23 @@ public class MachoProgramBuilder {
 		}
 
 		// Create memory blocks for segments.
-		for (SegmentCommand segment : header.getAllSegments()) {
+		ListIterator<SegmentCommand> it = header.getAllSegments().listIterator();
+		while (it.hasNext()) {
+			final int i = it.nextIndex();
+			final SegmentCommand segment = it.next();
+
 			if (monitor.isCancelled()) {
 				break;
 			}
 
 			if (segment.getFileSize() > 0 && (allowZeroAddr || segment.getVMaddress() != 0)) {
-				if (createMemoryBlock(segment.getSegmentName(),
+				String segmentName = segment.getSegmentName();
+				if (segmentName.isBlank()) {
+					segmentName = "SEGMENT." + i;
+				}
+				if (createMemoryBlock(segmentName,
 					space.getAddress(segment.getVMaddress()), segment.getFileOffset(),
-					segment.getFileSize(), segment.getSegmentName(), source, segment.isRead(),
+					segment.getFileSize(), segmentName, source, segment.isRead(),
 					segment.isWrite(), segment.isExecute(), false) == null) {
 					log.appendMsg(String.format("Failed to create block: %s 0x%x 0x%x",
 						segment.getSegmentName(), segment.getVMaddress(), segment.getVMsize()));
@@ -323,7 +332,6 @@ public class MachoProgramBuilder {
 				return MemoryBlockUtils.createUninitializedBlock(program, false, name, start,
 					dataLength, comment, source, r, w, x, log);
 			}
-
 			return MemoryBlockUtils.createInitializedBlock(program, false, name, start, fileBytes,
 				dataOffset, dataLength, comment, source, r, w, x, log);
 		}

```

**Comment by ghidra1** [comment]
I just don't know how it would have worked with 9.1 unless we actually created blocks with no name

**Comment by ghidra1** [comment]
I think you change is the correct approach and will put in a ticket to handle this case.

**Comment by LeonardKoenig** [comment]
> I just don't know how it would have worked with 9.1 unless we actually created blocks with no name

Seems so, the linked issue/PR had some discussion, but mostly on duplicate names.

> I think you change is the correct approach and will put in a ticket to handle this case.

Great!  Feel free to close the issue then, thanks for your support!

**Comment by ghidra1** [comment]
I will leave it open until the Macho naming issue is resolved

**Comment by ryanmkurtz** [comment]
This issue is different from #2329 in that Mach-O object files (file type MH_OBJECT) are specified to have 1 segment with no name:

```
 * The file type MH_OBJECT is a compact format intended as output of the
 * assembler and input (and possibly output) of the link editor (the .o
 * format).  All sections are in one unnamed segment with no segment padding. 
 * This format is used as an executable format when the file is so small the
 * segment padding greatly increases its size.
```
All of the no-name segment's sections specify normal parent segment names, like __TEXT, __DATA, etc.  We'll either go with @LeonardKoenig's generic approach, or put some more specific support in for these object files.

**Comment by ghidra1** [comment]
Fix made for 9.2.3

**Comment by ryanmkurtz** [comment]
Just wanted to let you know I'm working on implementing the missing relocations that you probably ran into when looking at these object files.

**Comment by LeonardKoenig** [comment]
@ryanmkurtz Thank you very much for the heads up & the great work!
