### ISSUE TITLE
Add byte_mapped_address to processor spec

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2703]
**Is your feature request related to a problem? Please describe.**
The only way to currently add a byte mapped memory block is by implementing a loader. The `bit_mapped_address` attribute exists in `processor_spec.rxg` for a default memory block but none exists for byte mapped addressing.

**Describe the solution you'd like**
Add `byte_mapped_address` attribute to `processor_spec.rxg`

**Describe alternatives you've considered**
Doing it in a loader.

**Comment by ghidra1** [comment]
This will require some rework of the `MemoryBlockDefinition` class.  In addition, byte-mapped blocks should allow specification of the byte-mapping ratio.

**Comment by ghidra1** [comment]
See `/Ghidra/Framework/SoftwareModeling/data/languages/processor_spec.rxg` for XML specification changes

**Comment by astrelsky** [comment]
> See `/Ghidra/Framework/SoftwareModeling/data/languages/processor_spec.rxg` for XML specification changes affecting pspec `memory_block` tag.

Thank you.
