### ISSUE TITLE
When going to tool settings and changing the theme to GTK+ ghidra will fail to start.

### ISSUE THREAD

**Issue by CocaineJohnsson** [NationalSecurityAgency/ghidra#2709]
**Describe the bug**
Ghidra will not start when GTK+ is the selected theme, java will run with process state D (uninterruptable sleep) invoking the ghidra loader and then silently exits, emitting no diagnostic.

**Screenshots**
![image](https://user-images.githubusercontent.com/53689060/106374080-f5c11400-637f-11eb-8afd-4cb99f005481.png)

**To Reproduce**
1. Go to 'Tool Settings'
2. Click on 'Tool'
3. Select "Swing Look And Feel"
4. Scroll down to 'GTK+'
5. Ghidra will prompt you to restart to apply changes
6. Ghidra should fail to restart

**Expected behavior**
Expected behavior is starting again, removing the relevant line from `~/.ghidra/version/preferences` allows ghidra to start up again

**Environment (please complete the following information):**
 - OS: Arch Linux 5.10.5-arch1-1
 - Java Version: OpenJDK 11.0.10 2021-01-19
 - Ghidra Version: 9.2.2-1

**Comment by CocaineJohnsson** [comment]
Update: I didn't see the error log it generated in $HOME, it is attached:
[hs_err_pid295637.log](https://github.com/NationalSecurityAgency/ghidra/files/5899472/hs_err_pid295637.log)

**Comment by ryanmkurtz** [comment]
Could not reproduce on Ubuntu 20.10 with Ghidra 9.2.2.  It looks like it may be this bug within Java:

https://bugs.openjdk.java.net/browse/JDK-8255790

**Comment by CocaineJohnsson** [comment]
Huh, maybe. Though if it is that bug must've been in the codebase for a fairly long time since I'm using Java 11, other java based GTK applications appear to work so maybe there's a workaround until it can be fixed on the java end of things?

**Comment by dragonmacher** [comment]
This is a Java issue with the LaF making a native call.  My guess is that the native call is not correctly acquiring a lock.  We cannot fix this.

The above ticket states it is fixed in Java 17.   Until we migrate to that version, you will have to use a different look and feel to work around the issue.
