### ISSUE TITLE
SSA Form Exposed?

### ISSUE THREAD

**Issue by agnosticlines** [NationalSecurityAgency/ghidra#271]
Is the SSA form generated by the decompiler exposed anywhere inside ghidra or to the API? Or is that something done in the decompiler binary.

Would be really nice to expose things like DFG and SSA forms to the Ghidra API.

Again, I read the docs and couldn't find anything

I'm trying to do some value range analysis plugins but without SSA that's proving kinda difficult :p

**Comment by d-millar** [comment]
Hi @agnosticlines,

The SSA form is exposed by the Ghidra API as well as the decompiler binary.  If you check out the GraphAST.java Ghidra script, you can see the basic calls necessary to recover the per-function DFGs built on SSA.  For a little more detailed information regarding what can be dumped through the PCode API, I've created a new repo at https://github.com/NationalSecurityAgency/ghidra_pcode_scripts, which contains a few sample scripts I use for generating Datalog fact files from PCode.

**Comment by agnosticlines** [comment]
That repo currently 404's, but either way that's exactly what I was looking for, thank you!

**Comment by d-millar** [comment]
Oh, huh, default github behavior was not what I expected - oops!  Well, that's as good a place as any.  Enjoy.
