### ISSUE TITLE
Unable to start the app on macOS if System settings "Always open documents in Tabs" enabled.

### ISSUE THREAD

**Issue by JulyIghor** [NationalSecurityAgency/ghidra#2711]
**Describe the bug**
When I started ghidra I can't press anything, check out the video.
https://user-images.githubusercontent.com/3390357/106386494-85dd7880-63d5-11eb-85fa-91b393d94fd7.mov

1. Go to macOS system Settings, General, enable "Always open documents in Tabs"
2. Start the ghidra

**Expected behavior**
Mouse clicks to work

**Environment (please complete the following information):**
 - OS: macOS latest
 - Java Version: tried many
 - Ghidra Version: latest

**Comment by ryanmkurtz** [comment]
Duplicate of #2531
