### ISSUE TITLE
Error while building ghidra-debugger

### ISSUE THREAD

**Issue by SirEnder125** [NationalSecurityAgency/ghidra#2716]
Hey. I got the following error:
> Unable to find the local maven repo.  Ensure you have created the ghidra.repos.config file.

What do I do to fix this?

Gradle: v5.0

**Comment by ryanmkurtz** [comment]
You need to run this gradle command first:

`gradle --init-script gradle/support/fetchDependencies.gradle init`

More information can be found in the [Dev Guide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md).

**Comment by SirEnder125** [comment]
Oh, okay. Thanks! :P
