### ISSUE TITLE
Post-Build Error

### ISSUE THREAD

**Issue by SirEnder125** [NationalSecurityAgency/ghidra#2717]
**Describe the bug**
I ran the ghidraRun.bat after building and it says JDK could not be found.
I do have it, though. v9.2.2 works fine!

**To Reproduce**
1. Build. ("gradle eclipse")
2. run ghidraRun.bat

**Screenshots**
This means it built correctly, right?
![image](https://user-images.githubusercontent.com/69535694/106531084-2c4b7b80-64b3-11eb-84c6-a0fd088d281f.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 11
 - Ghidra Version: debugger

**Comment by ryanmkurtz** [comment]
When you do a `gradle buildGhidra`, it produces a zip file in the `build/dist` directory.  This file, when unzipped, is your new runnable Ghidra build.  When you unzip it, the unzipped directory should have a `ghidraRun.bat` file at the top level.  That's the one you want to run.

I recommend you move the zip file to some other directory outside of the ghidra git repo so you don't confuse all the different `ghidraRun.bat` files that may be laying around.

You basically never want to run the `ghidraRun.bat` file that's in the `RuntimeScripts` directory.  That one will only run if you have the Eclipse environment setup.

**Comment by SirEnder125** [comment]
Oh? So is `gradle` kinda like `make`? I put the name of the configuration or whatever after
`gradle`?

**Comment by SirEnder125** [comment]
I get this error now:
![image](https://user-images.githubusercontent.com/69535694/106533399-b7c70b80-64b7-11eb-8c96-c8becaae36ce.png)

**Comment by SirEnder125** [comment]
> a ghidraRun.bat file at the top level. That's the one you want to run.
Oh, I am using the debugger branch. Sorry.

**Comment by SirEnder125** [comment]
Does that image show what the problem is? It is trying to find jdk in the jre directory. Why?

**Comment by SirEnder125** [comment]
PLEASE HELP?
