### ISSUE TITLE
gradle buildGhidra: Searching for JDK in JRE directory

### ISSUE THREAD

**Issue by SirEnder125** [NationalSecurityAgency/ghidra#2718]
Hello, I am trying to build ghidra-debugger and it gives me the following error:
![image](https://user-images.githubusercontent.com/69535694/106540066-cc5dd080-64c4-11eb-84f6-80a2b9aae9c7.png)

It says that it is searching the jre dir for jdk? Why?!
Can anyone explain?

**Comment by SirEnder125** [comment]
If someone would answer soon that'd be great.

**Comment by ghidra1** [comment]
Gradle uses the java found within your execution PATH or JAVA_HOME environment variable.  You will need to ensure that JDK 11.x can be found via one of these two mechanisms before issuing gradle command.

**Comment by SirEnder125** [comment]
It does exist in C:\Program Files\Java\jdk-11.0.10

**Comment by SirEnder125** [comment]
And it is in the path.

**Comment by ghidra1** [comment]
You can examine the logic for the gradle command which is a script.  You may have more than one java installation in your path.  If this is the case you can correct the PATH (should only have one) or set JAVA_HOME to your JDK 11.x installation directory this should take precedence.  You can set this environment (Edit environment variables for your account).

**Comment by SirEnder125** [comment]
Okay, I reinstalled Jdk 11 and now I get this error:
> * What went wrong:
> java.io.FileNotFoundException: C:\Program Files\Java\jdk-11.0.10\lib\tzdb.dat (The system cannot find the file specified)

**Comment by ryanmkurtz** [comment]
In the command prompt that you are executing gradle from, what is the output of the following command:

`echo %JAVA_HOME%`

**Comment by SirEnder125** [comment]
Well, I was using Windows PowerShell, and that just printed "%JAVA_HOME%".
But I used a batch file and it printed "C:\Program Files\Java\jdk-11.0.10\" and I
could've guessed that, since I just created the JAVA_HOME system environment
variable last night.

**Comment by ryanmkurtz** [comment]
What JDK 11 distro are you using?

**Comment by SirEnder125** [comment]
Uhhh what do you mean?

**Comment by SirEnder125** [comment]
I downloaded it here: https://download.oracle.com/otn-pub/java/jdk/11.0.10%2B8/020c4a6d33b74f6a9d2bc6fbf189da81/jdk-11.0.10_windows-x64_bin.exe

**Comment by ryanmkurtz** [comment]
Can you give Amazon Corretto a try?

https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

**Comment by SirEnder125** [comment]
Oh, okay.

**Comment by ryanmkurtz** [comment]
It most likely installed to `C:\Program Files\Amazon Corretto\jdk11.0.10_9`.  Try setting your `JAVA_HOME` environment to that path.

**Comment by SirEnder125** [comment]
Okay.

**Comment by SirEnder125** [comment]
That path does not exist.

**Comment by SirEnder125** [comment]
Oops, I accidentally installed the x86 version

**Comment by ryanmkurtz** [comment]
Ghidra requires the 64-bit version

**Comment by SirEnder125** [comment]
I know, I'm reinstalling now. Sorry. Haha

**Comment by SirEnder125** [comment]
Trying buildGhidra again...

**Comment by SirEnder125** [comment]
Uhhh just got back, it compiled, but can the debugger connect to gdb stubs?

**Comment by d-millar** [comment]
If 3ds includes a gdb stub compatible with 7.0 or greater, you can use the "GNU gdb over GADP" interface.

**Comment by ryanmkurtz** [comment]
I'm going to close out this ticket since your build is now working.  The [Discussions](https://github.com/NationalSecurityAgency/ghidra/discussions) area is a good place to ask follow up questions about the debugger.
