### ISSUE TITLE
Autorenaming to bad names

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#272]
For example, I have a variable with `undefined4` type. After retyping to `char[1]` GHIDRA renames variable to shit like this `s_??..._007bb17f`. Dots is the part of the name.

![изображение](https://user-images.githubusercontent.com/7189309/55075655-94093200-50a4-11e9-9c39-acbc56a84026.png)

**Comment by dev747368** [comment]
If the string is showing "??..." for its value it indicates that there is a problem getting the bytes from memory or a character set problem.
Is 007bb17f near the end of a memory section, or have you manually assigned a character set to that string or set the default character set to something other than the default?

**Comment by lab313ru** [comment]
It is the string allocated in data section memory (not initialized). Sure, it will be without predefined bytes.
