### ISSUE TITLE
PIC24 Cannot rename RAM Variable - "memory storage not found for global storage"

### ISSUE THREAD

**Issue by EuanKirkhope** [NationalSecurityAgency/ghidra#2724]
I'm trying to rename "DAT_ram_0c66" in the following function, but it gives the following error after a long pause (around 5 secs):

"memory storage not found for global storage"

The function:

```
void ClearBuffer_60chars(void)
{
  undefined *puVar1;
  
  RCOUNT = 0x3c;
  puVar1 = &DAT_ram_0c66;
  while (RCOUNT != 0) {
    RCOUNT = RCOUNT + -1;
    *puVar1 = 0;
    puVar1 = puVar1 + 1;
  }
  DAT_ram_0ca2 = 0;
  DAT_ram_0ca3 = 0;
  DAT_ram_0ca4 = 0;
  return;
}
```

Image is from a PIC24FJ128GA202
Ghidra 9.2.2
Windows 10.

the other ram variables in the function can be renamed.

**Comment by gtackett** [comment]
There may not be a memory block that includes ```ram:0c66``` in it address range. Try going to ```ram:0c66``` in the assembly language listing pane. If the address doesn't exist, you won't be able to go there.  In that case, create a memory block in ```ram``` that includes the address.

If the address already exists, you can add your own label in the listing pane at ```ram:0c66```. I think that will take care of the name in the decompiler window as well.

**Comment by EuanKirkhope** [comment]
Thanks there was no ram map at all since I created the project.  I added a ram range, but it still didn't allow the decomplie to add the label, however the asm listing did allow it.

Some areas of the code were not disassembled.  When I click on the asm area and press 'D', I get the decompile, but with grey background.  how does one get to a editable white background?
