### ISSUE TITLE
GhidraDev Jython creates Java project

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#273]
I tried to create Ghidra module project and selected Jython to use. But after pressing Finish button it creates the same project as for Java. So, how to use Python in modules?

**Comment by ryanmkurtz** [comment]
All Eclipse Ghidra projects created by the GhidraDev plugin are Java projects.  When you enable Python for your Ghidra project, GhidraDev is simply adding the Python nature to the project, and adding Ghidra to Jython's path.  This allows you to use PyDev to edit/debug Python Ghidra scripts that live in your project.  

The only aspect of a module project that can be written in Python is Ghidra scripts.  Other parts of the module such as Analyzers, Loaders, Plugins, FileSystem's, etc. must be written in Java.

**Comment by lab313ru** [comment]
It would be great to use python loaders/analyzers, etc.
