### ISSUE TITLE
`GDirectedGraph` in Python/Jython interface

### ISSUE THREAD

**Issue by mrphrazer** [NationalSecurityAgency/ghidra#2733]
Heya,

I cannot create instances of `GDirectedGraph` in the Python/Jython interface:
 
```
>>> ghidra.graph.GDirectedGraph()
Traceback (most recent call last):
  File "python", line 1, in <module>
TypeError: No visible constructors for class (ghidra.graph.GDirectedGraph)
```

Is there a simple workaround?

**Comment by ryanmkurtz** [comment]
`GDirectedGraph` is an interface, which you can't instantiate.  You'll have to work with one of its class implementations:

![image](https://user-images.githubusercontent.com/5378554/107132199-f4757700-68aa-11eb-8af9-314e50dd6828.png)

**Comment by mrphrazer** [comment]
got it, thanks :) works now
