### ISSUE TITLE
Low-level Error: Redefinition of structure: PNG-Image

### ISSUE THREAD

**Issue by sfg-kujo** [NationalSecurityAgency/ghidra#2734]
**Describe the bug**
Same as issue #2359, except I am providing a repro exe and disassemble address

**To Reproduce**
1. "Decompile a function which has a direct reference to a png created by the embedded media analyzer."

**Expected behavior**
"The function should decompile"

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10 Pro [1909 build 18363.1316]
 - Java Version: 15.0.2
 - Ghidra Version: 9.2.2

**Additional context**
https://drive.google.com/file/d/1Z5A_MdjaZejgFyZUl_4HbzIJkj3lGzpS/view?usp=sharing
Disassemble the function at 0041ec50

**Comment by caheckman** [comment]
Reproducing this error.
