### ISSUE TITLE
x86 p-code incorrect jump destination

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#2736]
x86 p-code incorrect jump destination occurs for a very small test-function. The following is a listing of p-code in the problem area. 

![image](https://user-images.githubusercontent.com/22150653/107242972-8fc93200-69fa-11eb-8664-79c6c4cdee17.png)

In x86, CMP would set the Zero Flag (ZF) to 1 if the operands are EQUAL, and if so, JZ would branch to 0x400ca2, otherwise it would follow-through to address 0x400c95. In the p-code above, we are seeing that we will branch to 0x400ca2 if the operands are INT_NOTEQUAL, which is totally incorrect. Please let me know if I am interpreting this incorrectly. Funny enough, when I inspect the p-code basic block within which these instructions are found, and I call .getTrueOut() and .getFalseOut(), I get that the True destination is 0x400c95 and the False is 0x400ca2, which are the correct destinations if we use INT_NOTEQUAL. 

**Expected behavior**
If what I have described is in-fact an issue, we should expect either:
CMP's p-code to go from
`dfa.java> 		(register, 0x206, 1) INT_NOTEQUAL (unique, 0x17a0, 4) , (const, 0x9, 4)`
to
`dfa.java> 		(register, 0x206, 1) INT_EQUAL (unique, 0x17a0, 4) , (const, 0x9, 4)`

or the CBRANCH to go from 
`dfa.java> 		 ---  CBRANCH (ram, 0x400ca2, 1) , (register, 0x206, 1)`
to 
`dfa.java> 		 ---  CBRANCH (ram, 0x400c95, 1) , (register, 0x206, 1)`
This second option is less-preferred when compared to the first, as the first would mimic the behavior of CMP and keep the CBRANCH destination to the same as the one listed in JZ.

**Environment**
 - OS: Windows
 - Java Version: 15
 - Ghidra Version: 9.2.2

**Comment by ghidracadabra** [comment]
It looks like you're working with "high" pcode, i.e., pcode generated by the decompiler.  Essentially, the decompiler starts with "low" pcode generated from SLEIGH and applies various transformations and simplifications (similar to the optimization phase of an optimizing compiler).  During these transformations/simplifications, the decompiler is free to change conditionals in a semantics-preserving way.

If you like, you can examine the low pcode:
 `currentProgram.getListing().getInstructionContaining(currentAddress).getPcode()`
(in a script)

You can also enable the pcode field in the listing if you'd like to see the low pode alongside the other listing data (address/bytes/mnemonic/operands etc)

This will be at a much lower level and will likely be a closer match to what the processor is actually doing.  

Two caveats: 

1. The SLEIGH specification writer has some freedom in implementation (as long as semantics are preserved) 
2. The decompiler hasn't done any simplification of low pcode, so you will see all of the effects of an instruction (e.g., you'll see all of the flags that CMP sets, even if particular write to a flag is never read).

If I've misunderstood your question, please post the bytes of the small test function and we can take a closer look.

**Comment by aa-software2112** [comment]
Thank you for the response! The only issue I have with it is that even if the "high" pcode adds transformations and simplifications, should it not hold that, if it inverts the condition of a jump (!<actual condition>), it should also invert the destination of the jump? It seems that the destination of the jump has not changed in the "high" pcode (see CBRANCH), and yet the condition is inverted (see INT_NOTEQUAL). I'm not sure if there's still some deeper logic that occurs in SLEIGH that I'm not aware of that would make the condition inversion without destination inversion possible, in that sense I hope I am not wasting your time.

https://fromsmash.com/fQQsGbVFct-it

The link above will give you the source code and compiled binary - the function where this behavior occurs is called "struct_ptr_test_function".

**Comment by ghidracadabra** [comment]
We reserve the right to ignore user-supplied links and binaries :smile:

That being said, if you navigate to the function in Ghidra, you can select "Debug Function Decompilation" from the drop-down menu in the upper right corner of the Decompiler window. This will create an xml file; the bytes of the function will be near the beginning of that file.  If you paste them here I can take a closer look.

**Comment by aa-software2112** [comment]
@ghidracadabra I understand, here are the bytes that I was planning to use to bring you down! ; ) 

Thanks for the help again.

<bytechunk space="ram" offset="0x400ef0" readonly="true">
554889e54883ec4048897df8c645f071
c745f409000000488b7df8837f04090f
840d000000488d7df0e8d2ffffff4889
45d0c745ec630000008b45f40faf45ec
488b4df80341048945ec817decf40100
000f8d1900000048bf1b134000000000
00b000e8e8fbffff8945cce9f2000000
817decf40100000f8e17000000817dec
e80300000f8d0a000000e8c1fcffffe9
c9000000817dece80300000f8e1a0000
00817decd00700000f8d0d000000e8fd
fcffff8945ece99d000000817decd007
00000f8e3a000000817decb80b00000f
8d2d000000488d45f04883c004488945
e08b7dec488b0425382060008a08488b
55e00fbef1e8f6fcffff8945ece95100
0000817decb80b00000f8e3f00000081
7deca00f00000f8d32000000488d45f0
4883c004488945d88b7dec488b042538
2060008a08488b55d80fbef1e8fffcff
ff488945d8488b45d88b308975ece900
000000e900000000e900000000e90000
0000488b45f8c600628b4dec83c10648
8b45f8894804488b45f84883c4405dc3
</bytechunk>

**Comment by ghidracadabra** [comment]
Thanks!  With your example I was able to take a closer look and after that and some discussions with the decompiler guru I think I can clarify what's going on.

Basically, during the simplification process, the first input of the CBRANCH operation does not change - it will always be the original jump target.  However, the decompiler adds some state to the CBRANCH operation, which can change the _meaning_ of the operation (like whether the jump is taken on a true condition or a false condition).  Also, the branching structure is encoded in the block graph, which explains what you saw with the getTrueOut and getFalseOut methods.  Keep in mind that simplification can make some pretty drastic changes - for example, an entire block could be removed if its pcode ops were all simplified away.

Is there something specific you're trying to do with the high pcode?

**Comment by ghidracadabra** [comment]
Happy to help!

In case you haven't seen it, you might want to check out the script "GraphAST.java", which is included with Ghidra.  In particular, note that it sets the simplification style of the DecompInterface to "normalize" instead of "decompile" which I think is what you must be using.  The high pcode produced with the "normalize" style will not contain certain operations that might be unnecessary for what you're doing (such as CAST).
