### ISSUE TITLE
Function signature can't include flexible arrays

### ISSUE THREAD

**Issue by agnosticlines** [NationalSecurityAgency/ghidra#274]
**Describe the bug**
The function signature editor doesn't have the ability to understand flexible arrays, this seems to be due to the way it's parsing the text field, however it's also not possible to set up a flexible array in the custom storage options.

**To Reproduce**
1. Open up a binary
2. Edit function signature
3. In the text box type something like `int parse(int data[]) `

**Expected behavior**
The decompiler would register the type as `int data[]`

**Actual Behavior**
The functions name is changed to `data[]`

**Screenshots**
The name is changed, but the type isn't affected

![2019-03-27-15:41:22](https://user-images.githubusercontent.com/23334509/55090355-e21f3500-50a6-11e9-8c90-b4f9804dfab1.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11.0
 - Ghidra Version: 9.0.1

**Comment by dragonmacher** [comment]
In this example you have to specify the parameter not as an array, but as a pointer: 'int * data'

**Comment by agnosticlines** [comment]
Yeah I know you can do that, but GHIDRA has built in ability to do arrays that works quite well, showing the element numbers, it just can't be accessed in the decompiler, you have to go to the definition of the variable in the function prologue, right click->set type->Array

**Comment by dragonmacher** [comment]
To clarify, are you are asking simply for the ability to set the data type from with in the Decompiler?

The Decompiler will display pointer data types using array syntax when it detects the type is being indexed into.    Do you have a case where using the pointer type does not produce array accesses?   If so, we would be curious to see a screenshot comparing the use of a pointer type to that of the array type, highlighting what is missing for you.

**Comment by agnosticlines** [comment]
I do have a few examples, is the cleanest one.

Typed var in this case is `uStack60`

Difficult to read (ptr type):
![2019-03-27-16:31:58](https://user-images.githubusercontent.com/23334509/55094273-003c6380-50ae-11e9-94c8-bfb8429cddfb.png)

Easier to read (typed int with size):
![2019-03-27-16:32:16](https://user-images.githubusercontent.com/23334509/55094282-07fc0800-50ae-11e9-8bd0-da1555ad221b.png)

It's a readability thing, the first hurts my head, second I can just about reason with.

**Comment by agnosticlines** [comment]
I realise this issue sort of morphed from one thing to another, just happened to be a cause of another issue, so figured I'd mention it.

**Comment by dragonmacher** [comment]
We currently do not support the use of unsized arrays types in these variables.   The use of a pointer type should be interpreted as an array when appropriate.

The Decompiler attempts to present usage of an array variable as you have shown in your desired output, but showing array syntax.   The case where the Decompiler does not pick-up the use of an array is most likely a bug.   If you have an example that is not working as it should, then you can submit that as a bug by providing us the output of the **Debug Function Decompilation** command (available from the toolbar of the Decompiler).

**Comment by agnosticlines** [comment]
is there anywhere I can share this that isn't a public github issue?

**Comment by agnosticlines** [comment]
Attached: [files.zip](https://github.com/NationalSecurityAgency/ghidra/files/3014577/files.zip)

**Comment by agnosticlines** [comment]
Attached: [bug01.zip](https://github.com/NationalSecurityAgency/ghidra/files/3014588/bug01.zip)

**Comment by agnosticlines** [comment]
Sorry, that wasn't the original issue, I was showing a case where using the `int *` type doesn't correctly show indexes. The binary I am currently using the decompiler picks it up but I was just using that to demonstrate why `int *` isn't always sufficent. 

The project I'm working on right now is still failing to recognize array indexes.

I can attach the demo project it if you want still? But I've force changed the type of a uint to a `int *`.

Appreciate your responses, sorry for the confusion.
