### ISSUE TITLE
Unable to build Ghidra

### ISSUE THREAD

**Issue by wanitaqing** [NationalSecurityAgency/ghidra#2741]
Hi, I tried to build the Ghidra Development Environment using `gradle buildGhidra` but i received the following error:

> Task :createJavadocs FAILED
>
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':createJavadocs'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/home/intern/Desktop/git/ghidra/build/tmp/createJavadocs/javadoc.options'
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
>
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 25s
> 95 actionable tasks: 1 executed, 94 up-to-date

Here is the information of my installed Gradle:
![image](https://user-images.githubusercontent.com/47132451/107347987-479e2400-6a7b-11eb-95d7-8949af0bc34a.png)

When I execute `echo $JAVA_HOME`, I get the following output:
> /usr/lib/jvm/java-11-openjdk-amd64

I installed Java OpenJDK 11 using `sudo apt install default-jre`

I'm not sure why Javadoc is not generated? I even made sure that my Eclipse is aware of the location of the installed JDK. Is my Gradle too new? I would appreciate any help i can get! Thank you!

**Comment by ryanmkurtz** [comment]
I just built fine without error using the latest master.

What is your output of the command:

`javac -version`

**Comment by wanitaqing** [comment]
Ahh, silly me. I only installed JRE and didn't install JDK (missed out a segment while following online tutorial). Let me install JDK and try out the building again!

**Comment by wanitaqing** [comment]
Yes! It worked! Thank you @ryanmkurtz for pointing out that silly mistake of mine!
