### ISSUE TITLE
INDIRECT pcode op, input1 misunderstood

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#2744]
Hello,

I am curious as to how the INDIRECT works. I am creating a data-flow graph and am trying to figure out how to place INDIRECT operations into the flow (if necessary). Take for example the screenshot below:
![image](https://user-images.githubusercontent.com/22150653/107520733-bb295980-6b7f-11eb-871d-aff72714b7b5.png)
The 0x68 in the last input argument is supposed to be interpreted as another operation that could be affecting input0, however I could not find a pcode op with the value 104 (=0x68) from the documentation (../GhidraAPI_javadoc/9.2.2/api/constant-values.html#ghidra.program.model.pcode.PcodeOp.BOOL_AND). Could you expand on the the workings of INDIRECT? 

I would like to note that the folk managing this code-base has done a mighty fine job assisting me with my questions thus far, and I would like to thank you for that

**Comment by ghizard** [comment]
The 0x68 is not a p-code opcode here, but rather a sequence number of a particular p-code operation that is causing the INDIRECT.  To get the PcodeOp:  First, construct a SequenceNumber object using the Address from the INDIRECT op and the sequence number 0x68. Then, pass the SequenceNumber object to getPcodeOp() on the HighFunction to get the PcodeOp.

**Comment by aa-software2112** [comment]
> The 0x68 is not a p-code opcode here, but rather a sequence number of a particular p-code operation that is causing the INDIRECT. To get the PcodeOp: First, construct a SequenceNumber object using the Address from the INDIRECT op and the sequence number 0x68. Then, pass the SequenceNumber object to getPcodeOp() on the HighFunction to get the PcodeOp.

I have done what you've suggested and it worked wonderfully --- now I can see that the general trend is that the source of INDIRECT pcodes are function calls. I have some questions for you:

Is it true that Ghidra makes an INDIRECT pcode for each variable entering a call (as those variables can be modified within the call)?

Is it true that Ghidra makes an INDIRECT pcode for each _stack_ variable that exists at that point of a given call, regardless if that _stack_ variable is actually passed as an argument to the function? 

Is it true that Ghidra uses INDIRECT as a method for relaxing the need to inspect sub-calls in a function (i.e. to omit inter-procedural analysis during decompilation)?

Thanks again for your work @ghizard.

**Comment by M4tsuri** [comment]
I think that INDIRECT just an indicator that the varnode in output can be affected by the pcode indicated by it's input1.
So it's impossible for a varnode to be affected when it's both not the output of an instruction and it's not associated with the instruction through an INDIRECT. Am I right?
Thank you.

**Comment by aa-software2112** [comment]
@M4tsuri Makes a load of sense; thank you so much for the explanation
