### ISSUE TITLE
Support Hex/Decimal/Char popup display in Decompiler when hovering on integer (like in Listing)

### ISSUE THREAD

**Issue by Singo001** [NationalSecurityAgency/ghidra#2745]
Hi, I was trying to do some crack me. But i have a problem it is not showing decimal values, but when I cover my mouse over the answer can you help? And it says 
![image](https://user-images.githubusercontent.com/72432451/107559295-33be0380-6bdc-11eb-804c-e91d9eb08a57.png)

And this is what i need 
![image](https://user-images.githubusercontent.com/72432451/107560085-34a36500-6bdd-11eb-8369-c9f56f6de62c.png)

**Comment by ryanmkurtz** [comment]
Are you asking how to show decimal values by default in Ghidra?

**Comment by xiaoyinl** [comment]
@ryanmkurtz I think Singo001 means that when we put the mouse cursor on an integer literal on the Decompile panel, the popup can display both the hex and decimal values. This is supported on the Listing panel, but not on Decompile.

**Comment by ryanmkurtz** [comment]
Thank you, that makes sense.  I'm going to tweak the title of this ticket a bit.

**Comment by Singo001** [comment]
Yeah sorry about that but do you guys know how to do it?

**Comment by xiaoyinl** [comment]
> Yeah sorry about that but do you guys know how to do it?

As far as I know, there is no way for users to do it. You’ll have to wait for Ghidra team to add support for this feature first.

**Comment by caheckman** [comment]
As of https://github.com/NationalSecurityAgency/ghidra/commit/2143c4961db49d3f59c708f395e4397ccf1d3e78 , right-clicking on integers shows hex/dec/bin/oct/char  convert options and displays the converted values in the pop-up menu.  (This is not technically a "hover" as a mouse click is required)

**Comment by dragonmacher** [comment]
This issue should be fixed by 55ebf73af.
