### ISSUE TITLE
Possible P-code reference manual inaccuracy in description of CPUI_SUBPIECE

### ISSUE THREAD

**Issue by KipHamiltons** [NationalSecurityAgency/ghidra#2747]
In the P-Code reference manual, the [description for SUBPIECE](https://github.com/NationalSecurityAgency/ghidra/blob/master/GhidraDocs/languages/html/pcodedescription.html#L627) says 
"If the size of output is smaller than the size of input0 **plus** the constant input1, then the additional most significant bytes of input0 will also be truncated."
Upon inspecting the source ([here is a link to the line in question](https://github.com/NationalSecurityAgency/ghidra/blob/2b08598dbabe6a9c911e712bd928e5f84fb00ee8/Ghidra/Features/Decompiler/src/decompile/cpp/opbehavior.cc#L736)), I think it should say _minus_ instead of _plus_.

A concrete example:
I have an input varnode of size 8, and the subpiece call is to remove the 4 least significant bytes, with an output varnode of size 4. As it reads currently, this would require further truncation of additional most significant bytes, because 
`sizeof(input0) + input1 == 12`, which is greater than `sizeof(output)`. This doesn't make sense, and the code doesn't reflect this.
As I understand it, the code only truncates most significant bytes if `sizeof(input0) - input1 > sizeof(output)`.
Using the previous example, if `sizeof(output)` was 2, then 8 bytes with 4 bytes removed wouldn't fit, so in this case it would remove additional most significant bytes.

From what I can see, the paragraph in question is in two files: `pcoderef.xml` and `pcodedescription.html`. I am not sure if the html is automatically generated from the xml, but I am able to make a pull request changing this word in one or both of those files, given that someone can verify my finding.
This almost feels like too small a change to make an issue about, but I spent waayy too long confused about this myself :stuck_out_tongue:
(Sidenote: should this have been a BUG templated issue? I wasn't sure, so I went with a blank issue)

**Comment by ryanmkurtz** [comment]
You are indeed correct about the typo.  If you wanted to make a PR to fix it, we would accept it.  Or, we could just go in and fix it ourselves if you'd like since it's a trivial change.  The html is generated from the xml, but you/we can simply change it in both places to avoid having to regenerate the whole thing.

You are fine with not using the BUG template for this.

**Comment by KipHamiltons** [comment]
PR submitted (#2783)
