### ISSUE TITLE
Bug or confusing behavior with Python API getGlobalFunctions

### ISSUE THREAD

**Issue by sporst** [NationalSecurityAgency/ghidra#2753]
Hi folks,

not sure if this is a user error on my side, but at least I find it confusing. Here's a short snippet running on a disassembled x64 "grep" executable.

> print(currentProgram.getFunctionManager().getFunctionAt(address))
> print(currentProgram.getFunctionManager().getFunctionAt(address).getParentNamespace())
> print(getGlobalFunctions("malloc"))

Prints:
> malloc
> Global
> []

I would have expected getGlobalFunctions("malloc") to return a Function object for the "malloc" function at the given address. What do you think?

**Comment by ryanmkurtz** [comment]
Yes, there looks to be an inconsistency here.  `getGlobalFunctions()` doesn't find it because that API call sees it as `<EXTERNAL>` rather than `Global`.  What are your thoughts @ghidra1?

**Comment by ghidra1** [comment]
This method (`Listing.getGlobalFunctions`) only considers functions contained within the Global namespace.  Unfortunately, external functions are contained within a Library namespace which can complicate the lookup of external functions by name.  I hope this will be improved someday.  You could try the method `SymbolTable.getExternalSymbol` which will return the first external function with a given name (e.g., program.getSymbolTable().getExternalFunction("malloc")`).

**Comment by sporst** [comment]
Thank you for the feedback, folks. There are 2 functions/symbols called "malloc", the first being the a small function to set up the external call and one being external symbol.

(1)

```
                             **************************************************************
                             *                       THUNK FUNCTION                       *
                             **************************************************************
                             thunk void * malloc(size_t __size)
                               Thunked-Function: malloc
             void *            x0:8           <RETURN>
             size_t            x0:8           __size
                             malloc                                          XREF[20]:    0020e374(c), 0020e460(c), 
                                                                                          0020e68c(c), 
        001a08b0 70 37 00 90     adrp       x16,0x88c000
        001a08b4 11 86 46 f9     ldr        x17,[x16, #0xd08]=>->malloc                      = 01588100
        001a08b8 10 22 34 91     add        x16,x16,#0xd08
        001a08bc 20 02 1f d6     br         x17=>malloc                                      void * malloc(size_t __size)
                             -- Flow Override: CALL_RETURN (COMPUTED_CALL_TERMINATOR)
```

(2)

```
                             **************************************************************
                             *                       THUNK FUNCTION                       *
                             **************************************************************
                             thunk void * malloc(size_t __size)
                               Thunked-Function: <EXTERNAL>::malloc
             void *            x0:8           <RETURN>
             size_t            x0:8           __size
                             malloc                                          XREF[2]:     malloc:001a08b0(T), 
                                                                                          malloc:001a08bc(c), 0088cd08(*)  
        01588100                 ??         ??
        01588101                 ??         ??
        01588102                 ??         ??
        01588103                 ??         ??
        01588104                 ??         ??
        01588105                 ??         ??
        01588106                 ??         ??
        01588107                 ??         ??
```

I would have expected the first function to be returned by getGlobalFunctions.

What ultimately worked for me was the following code, inspired by one of the examples shipped with Ghidra:

```
        symbol = currentProgram.symbolTable.getExternalSymbol(functionName)
        if symbol and symbol.symbolType == SymbolType.FUNCTION:
            addresses = symbol.object.functionThunkAddresses
            if len(addresses) == 1:
                address = addresses[0]
```

**Comment by ghidra1** [comment]
Thunk function generally reside in the symbol table and its index with no name.  They thunk function symbol simply mirrors the name of the function it is thunking.  In this case that is an external function.  Hopefully we can improve upon the lookup of external functions by name.

**Comment by ghidra1** [comment]
Closing issue.  Expected behavior.
