### ISSUE TITLE
Equates not propagating to Decomple View at 9.2.1 and later

### ISSUE THREAD

**Issue by pinksawtooth** [NationalSecurityAgency/ghidra#2767]
**Describe the bug**

Equate does not work correctly under certain conditions.
An issue that was fixed in 9.2 reappears in 9.2.1 and later.
https://github.com/NationalSecurityAgency/ghidra/issues/2386

**To Reproduce**
1. Check your Decompile View for a statment like if (x == 1)
2. Go to the Listing View and update the constant "1" to any appropriate EQUATE constant
3. Look back at the Decompile View

**Expected behavior**
Scalar will be replaced by Equate.

**Screenshots**

Bug reproduction

9.2

![image (5)](https://user-images.githubusercontent.com/18203311/107920789-d990ba00-6fb0-11eb-930f-7f2e8f3825e3.png)

9.2.1 and later
![image (4)](https://user-images.githubusercontent.com/18203311/107920769-d1387f00-6fb0-11eb-9458-2a4e538fa5f6.png)

Other

9.2.1 and later

![2021-02-15 171318](https://user-images.githubusercontent.com/18203311/107920989-26749080-6fb1-11eb-8c5b-cf970a7dd71e.png)

**Environment (please complete the following information):**
 - OS: Windows10
 - Java Version: 11.0.9.1
 - Ghidra Version:  9.2.1 and 9.2.2

**Comment by caheckman** [comment]
I've not been able to reproduce this.  If you can provide a "Debug Function Decompilation" dump (from the menu in the upper right corner of the Decompiler Window), it might help to diagnose.

**Comment by pinksawtooth** [comment]
Attach the "Debug Function Decompilation" dump and the gzf of the exe that caused the problem.
This is a program for studying reverse engineering.
[bug.zip](https://github.com/NationalSecurityAgency/ghidra/files/6233528/bug.zip)

**Comment by caheckman** [comment]
Thanks for the sample. This was patched in Ghidra 10.0, specifically the commit 1743a70ede3f96e627442b845d108b729d5d6974
