### ISSUE TITLE
PDB files should not be automatically opened from untrusted locations

### ISSUE THREAD

**Issue by sghctoma** [NationalSecurityAgency/ghidra#277]
**Describe the bug**
Ghidra tries to automatically open PDB files from the location stored in a PE file, which could pose a risk on Windows, since using a file path that points to a Windows share could leak NTLMv2 hashes and also provides a possibility for an SMB relay attack. 

**To Reproduce**
1. Prepare a PE file that uses an UNC path pointing to a Windows share as PDB path. The screenshot below shows such an .exe:

![image](https://user-images.githubusercontent.com/214533/55101851-5d8fdf00-50c5-11e9-9cb4-e30b49942064.png)

2. Start a server on the "attacker" machine that captures or relays NTLMv2 hashes. I've used the auxiliary/server/capture/smb Metasploit module for simplicity's sake.

3. Import, open, and analyze the file. Selecting only the "PDB" analyzer is sufficient.

![image](https://user-images.githubusercontent.com/214533/55102859-a21c7a00-50c7-11e9-8b11-fb320c9e2a8c.png)

The analyzer will fail (well, unless you actually serve the right .pdb, of course).

3. Go back to the "attacker" machine, and be happy for your newly aquired hashes (or shells, if you relayed).

![image](https://user-images.githubusercontent.com/214533/55103430-aeed9d80-50c8-11e9-9f66-7c6d43522592.png)

**Expected behavior**
Ghidra should ask if the user really wants to open a PDB file from the location embedded into the PE file.

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 11.0.2
 - Ghidra Version: 9.0.1

**Comment by d-millar** [comment]
Problem verified (and, yes, bad from a security perspective):  PdbParserNEW's method getPathsFromAttributes() line 1489 should be wrapped with a GhidraDialog asking for confirmation.

**Comment by ghidra1** [comment]
Ghidra also supports unattended headless analysis and be batch processing a very large number of files.  Forcing user interaction could be problematic.  What would you suggest for this scenario?

**Comment by sghctoma** [comment]
I think completely ignoring the path set in the PE debug directory, and using only the filename to search for .pdb files in explicitly set symbol paths is the right way to do this. I can't really imagine a scenario where the reverser has the .pdb file at the same location the original developer had it, so I don't think this would negatively affect anything.

For example, given an executable with the `\\evilserver\shared\test.pdb` path, Ghidra could look for a `test.pdb` only in `C:\symbols`, where `C:\symbols` is the symbol path set by the user.

**Comment by d-millar** [comment]
While @ghidra1 makes a good point which I hadn’t really considered, @sghctoma’s contention is, I believe, correct.  The cases in which the embedded path is current and useful are few and far between, and the batch processing cases can always be handled (and in most cases are) by either co-locating the pdb’s or using a symbol server.

**Comment by ghizard** [comment]
Investigating solutions.

**Comment by ghidra1** [comment]
In your scenario, how did you get the user's machine to mount a share to the attacker's machine.  Sounds like the system was already compromised prior to running Ghidra.  In such a situation, the entire user's home directory could be redirected to an attacker's machine without Ghidra's involvement.  Or, any attempt to re-open a saved path which has now been compromised on the user's machine.  The scenario you present sounds very contrived.
