### ISSUE TITLE
disassembly xml export

### ISSUE THREAD

**Issue by jstaursky** [NationalSecurityAgency/ghidra#2774]
Is there a way of exporting the disassembly information to XML? 
I see https://ghidra.re/ghidra_docs/api/ghidra/app/util/exporter/XmlExporter.html
but I do not believe I can retrieve a disassembly view like
```xml
<insn>
  <opcode>
..
  <modRM>
...
<insn>
```
which would be helpful.

**Comment by ryanmkurtz** [comment]
There is nothing built-in....you would have to write a custom GhidraScript to do it.
