### ISSUE TITLE
Graph Not Rendered, Exceeded limit of 10000 nodes. Graph contained 50.000+ nodes.

### ISSUE THREAD

**Issue by SkybuckFlying** [NationalSecurityAgency/ghidra#2775]
I just tried GHindra version 9.2.2 for the first time. I am not reverse engineering expert, just noobie. Trying to reverse engineer one of my own software projects which is indeed large, like 65.000+ lines of code.

I found one of the strings and click show references to it. Then I finally end up in some application logic. Then I try to render the block or code flow graph and ghindra complains it cannot render it because there are too many nodes.

Is there a setting somewhere to increase the number of allowed nodes ? Is it still possible to render parts of it ?

Laptop has 6 GB of ram. Currently usage is 1.6 GB of RAM. Pagefile is setup to use 16 GB of ram.

**Comment by dragonmacher** [comment]
Currently that is hard cutoff.  The issue is that the performance of the graph would degrade at that scale.  Also, viewing 50k nodes is probably not going to be very useful.

Before you launch the graph, you can make selections in the Listing.   The graphs created will limit the graph to the blocks inside the selection.   This allows you to create more targeted graphs for a specific set of functions.  See the `Select` menu for useful actions to help create selections.

**Comment by tomnelson** [comment]
You can set this property and see your graph (eventually.... maybe...) Some layout algorithms will take much longer than others

-DmaxNodes=60000

you can set that as high as you like.

**Comment by databoose** [comment]
> You can set this property and see your graph (eventually.... maybe...) Some layout algorithms will take much longer than others
> 
> -DmaxNodes=60000
> 
> you can set that as high as you like.

Passing this into the command line paramaters doesn't seem to resolve the issue, it still says that my limit of nodes is 500, even when i set it to 500000

**Comment by ryanmkurtz** [comment]
A Ghidra release does not support JVM arguments on the command line.  You can put it in `support/launch.properties`.  Just take a look at how the other entries in that file are done, and do something similar.

**Comment by tomnelson** [comment]
It appears that the maxNodes property test was removed and replaced with something more consistent with Ghidra.
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/105223/215093776-b5f569cd-3d30-444c-b3af-7406d01f6fb6.png">

Perhaps you can set the value in the Options dialog:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/105223/215094245-10719169-0a59-48f9-a825-7ec074be1bac.png">

**Comment by databoose** [comment]
> It appears that the maxNodes property test was removed and replaced with something more consistent with Ghidra. <img alt="image" width="1251" src="https://user-images.githubusercontent.com/105223/215093776-b5f569cd-3d30-444c-b3af-7406d01f6fb6.png">
> 
> Perhaps you can set the value in the Options dialog: <img alt="image" width="930" src="https://user-images.githubusercontent.com/105223/215094245-10719169-0a59-48f9-a825-7ec074be1bac.png">
> 
> That said, I don't think a 500,000 node graph, if it appears at all, will be useful.

This has worked for me, thanks.
