### ISSUE TITLE
Include an icon for Windows

### ISSUE THREAD

**Issue by vidarrt9** [NationalSecurityAgency/ghidra#2776]
I was unable to find an icon that would work on Windows, so I used the 600px logo that can be found on the NSA website, to create one.

![Preview_Windows_icon](https://user-images.githubusercontent.com/69603080/108328781-4a142280-71cd-11eb-94e5-dc6f760562fe.png)

There is a zipped up icon at issue #463, which only contains RGB/A icons in various sizes. The following contains the most common sizes, but also 256 color versions and 16 color version (obviously those look a bit shoddy in small sizes).

[Ghidra logo.ico.zip](https://github.com/NationalSecurityAgency/ghidra/files/6001413/Ghidra.logo.ico.zip)

Perhaps it can be included in the future?

**Comment by ryanmkurtz** [comment]
There is an icon that lives at `support/ghidra.ico`.  If you tried that one, was it not rendering correctly on Windows for you?

**Comment by ryanmkurtz** [comment]
Closing since Ghidra already includes an icon for Windows.  If you are having a problem with this icon, we can reopen this ticket.
