### ISSUE TITLE
MIPS disasm vs decompiler difference

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#278]
I'm trying to decompile some things for MIPS and getting such results:

![изображение](https://user-images.githubusercontent.com/7189309/55115973-db201300-50f6-11e9-8ffb-c681fd824f54.png)

![изображение](https://user-images.githubusercontent.com/7189309/55116002-f7bc4b00-50f6-11e9-9df3-6f8e00f10a22.png)

Problem is that disassembler goes by offsets and find final result pointer, but decompiler outputs thing like `ptr_to_ptr_to + 0xC`.

**Comment by xyzz** [comment]
Did you set both data items to read only? In disassembly view you need to go to 0x80090904, create a 4-byte sized data, then right click it and go to Data->Settings->Mutability and set to "constant". Repeat for 0x8008f700 and it should work fine after that.

**Comment by lab313ru** [comment]
Hmm, you right! It helped.:)

**Comment by lab313ru** [comment]
How to change this behavior and calculate offsets for writeable and readable segments?

**Comment by emteere** [comment]
If the memory was writable, then most likely the location is actually a structure.  Define a structure there, and you will get more readable results.  If it wasn't, then the compiler in all likelyhood would not have done an offset reference.

If the memory is readable and writeable, the decompiler cannot trust the value currently at the location, then you will get an offset access.

One additional thing to try, put a label on the calculated location rather than the default, and see if the decompiler will display the label instead of the offset.

**Comment by lab313ru** [comment]
> If the memory is readable and writeable, the decompiler cannot trust the value currently at the location, then you will get an offset access.
It would be great to have ability to override such behavior (everywhere, locally). It is hard to analyze a code that located in RWX section.

**Comment by xyzz** [comment]
If you want to change this behavior just set the memory segment as RX (in Window->Memory Map), or split it into multiple with function pointers in a read-only segment and everything else still RWX.

**Comment by lab313ru** [comment]
But what will happen when I'll set RW ram address (external port) to RX? Will Decompiler use it as a constant value and will skip block of code that compares value in it?

**Comment by emteere** [comment]
You can create a separate, or split an existing memory block that represents the PORT locations and set the correct RW on that memory.
Another possibility is setting known locations (or regions of memory) as volatile in the .pspec file if the locations are known volatile locations for all processors.

**Comment by lab313ru** [comment]
Thank you.

**Comment by spein46** [comment]
I ve similar issue, I attach a screen that explain better than words

<img width="939" alt="Screenshot 2019-11-28 at 02 11 27" src="https://user-images.githubusercontent.com/17325529/69777710-ccb45a80-11a1-11ea-844a-dc0195d676dd.png">
Disassembler works well, but decompiler not..

**Comment by NoneShell** [comment]
<img width="1151" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/34933484/0fde8c0a-0be6-416d-929d-0957605ff48b">
the same problem
