### ISSUE TITLE
Can ghidra fold some custom choice region in Listing window.

### ISSUE THREAD

**Issue by huhuang03** [NationalSecurityAgency/ghidra#2784]
Like the picture, I want fold the `00 bf` region. How can I do this.

[The picture](https://ibb.co/z67BRSw)

**Comment by ryanmkurtz** [comment]
Ghidra only supports folding of data types such as structures and arrays.  If it won't affect your analysis, you could highlight the region you want to fold, press `c` to clear any existing data, then press `b` to make them all bytes, then press `[` to make it an array which can then be folded.
