### ISSUE TITLE
Problem installing server when JAVA_HOME set but java not on path

### ISSUE THREAD

**Issue by bigianb** [NationalSecurityAgency/ghidra#279]
If JAVA_HOME is set but %JAVA_HOME%\bin is not on the path, the server install batch fails because it cannot find the init label.

you can see at line 110 of ghidraSrv.bat:

if exist "%JAVA_EXE%" goto init

in this case JAVA_EXE does exist as it is correctly found but the batch file has no init label.

**Comment by ghidra1** [comment]
Sorry about that.  Will be corrected for 9.0.2.  Hopefully you were able to adjust the script to avoid the issue.

**Comment by bigianb** [comment]
Thanks. Yes I just modified the script locally to ignore the env variable.

**Comment by ghidra1** [comment]
Here is a corrected version of the file which can be droped into ghidra_9.0.1/server.  You will need to remove the ".txt" file extension.
[ghidraSvr.bat.txt](https://github.com/NationalSecurityAgency/ghidra/files/3020209/ghidraSvr.bat.txt)
