### ISSUE TITLE
Please allow invoking right click context menu using Windows Context menu key or at least using Shift+F10

### ISSUE THREAD

**Issue by TheIronWolfModding** [NationalSecurityAgency/ghidra#2790]
**Is your feature request related to a problem? Please describe.**
I am physically challenged person and using mouse is hard for me, so I try to use keyboard as much as possible.  One frustrating part is that Ghidra does not allow opening the context menu using standard Windows Context menu key or at least Shift+F10.

**Describe the solution you'd like**
Please allow invoking right click context menu using windows Context menu key or at least using Shift+F10

**Describe alternatives you've considered**
Use some 3rd party software to emulate right click

**Additional context**
N/A

**Comment by dragonmacher** [comment]
(Also mentioned in #2008)

**Comment by Wall-AF** [comment]
Please can this issue be reopened?

I have recently discovered a significant difference between using the mouse to right-click on a DataType Archive and using the Windows Context Menu Key to do the same!

Using the mouse (I am acually forced into using MouseKeys), I am presented with this menu:
![image](https://user-images.githubusercontent.com/67698927/143613437-3a9c0379-db44-4f2c-afd1-f6206169f5f0.png)

Whereas, using the Windows Context Menu Key, I see this menu:
![image](https://user-images.githubusercontent.com/67698927/143613544-c9b449e6-59f0-47f0-94b6-42d827e119df.png)

As I'm sure you'd agree, a significant and awkward difference!!!

**Comment by dragonmacher** [comment]
This should be something that is easy to fix.  Will you please create a new issue?
