### ISSUE TITLE
Different Function ID hashes for "same" code

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2792]
I'm seeing different Function ID hashes for two copies of a function. They are same function as disassembled, but for one having references to ```ram:0032``` where the other has ```ram:0800```. 

I believe that this address difference is related to the import warnings about _Unhandled Elf Relocation: type = 5..._ that occur when one of the two is imported.
![Import](https://user-images.githubusercontent.com/52077/108768522-bb353c00-7525-11eb-9474-7373021a4888.png)

~~I'm not familiar with how Ghidra creates Function ID hashes. Is the address difference the reason that the two functions are hashing differently? If so, is there some way to get around this?~~

I built the C program as an elf binary with Microchip's **xc16** compiler,  linked against their "legacy" libraries.

Within it, I've located a block of code at ```rom:0152``` that corresponds to the library function ```__data_init_standard``` from their library file ```liblega-pic30-elf.a``` 

The attached archive contains:

- The program, slightly adapted from rosettacode's C version of a [numerical integration algorithm](https://www.rosettacode.org/wiki/Numerical_integration#C).
- The module ```data_init_standard.o```as headlessly imported with the special pre- and post-scripts for Function IDs.
[FIDtesting_2021_02_22.zip](https://github.com/NationalSecurityAgency/ghidra/files/6024934/FIDtesting_2021_02_22.zip)
(It's a Ghidra project archive. Just change the ```.zip``` to ```.gar```)

Also attached is the elf object file ```data_init_standard.o``` extracted from the Microchip library.
[data_init_standard.o.zip](https://github.com/NationalSecurityAgency/ghidra/files/6024993/data_init_standard.o.zip)

I've used Version Comparison _(which I know is completely different and separate from Function ID)_ to create a convenient side by side view of the beginning of that function in both the program, and the library module:
![Version Tracking](https://user-images.githubusercontent.com/52077/108764335-778c0380-7520-11eb-83cb-1ff144f33d77.png)

The last screen capture shows the results of running the script ```FIDHashCurrentFunction.java``` on both instances of the function. As you can see, both FH and XH are different.
![Listing Windows](https://user-images.githubusercontent.com/52077/108765441-c5edd200-7521-11eb-9753-4abb3e1422c1.png)

----
In its freely downloadable distribution of **xc16**, Microchip includes both the object library ```liblega-pic30-elf.a``` and the source files for the library. To the best of my knowledge they impose no restriction on redistributing those.

**Comment by gtackett** [comment]
I should have realized this yesterday: By patching the instructions referring to ```DAT_ram_0800``` it's easy to make them refer to ```DAT_ram_0032``` instead.

After I did this, the function hashes were identical between the two copies of the routine--as I should have expected, they both have the two hashes ```FH: f33d6d9a0516d36d```,  ```XH: f724e1ad03adda7c```.

So I believe it's a question of the "ELF relocation type 5" not being handled. I'm going to read up some more on ELF relocation types. In the mean time, maybe @ghidra1 can comment.

**Comment by gtackett** [comment]
In ```PIC30_ElfRelocationHandler.java```, part of the ELF loader for this architecture, symbolic names for a long list of PIC30 relocation type values are defined. These four have to do with references to special function registers:
```
	public static final int R_PIC30_FILE_REG_BYTE = 4;

	public static final int R_PIC30_FILE_REG = 5;

	public static final int R_PIC30_FILE_REG_WORD = 6;

	public static final int R_PIC30_FILE_REG_WORD_WITH_DST = 7;
```

Further down in the same source file, we find a ```switch()``` statement that has a case for each of  7 relocation types:	

- ```R_PIC30_16:```
- ```R_PIC30_32```
- ```R_PIC30_FILE_REG_WORD_WITH_DST```
- ```R_PIC30_WORD```
- ```R_PIC30_WORD_TBLOFFSET```
- ```R_PIC30_WORD_TBLPAGE```
- ```R_PIC30_PCREL_BRANCH```

Relocation type 5, ```R_PIC30_FILE_REG```, falls into the switch statement's default case, which calls a method to mark as unhandled any relocation type that isn't specifically handled by the loader.

I don't understand the loader well enough to try to add support for this type, so I'm hoping that @ghidra1 or someone else who does understand it can have a look.

**Comment by ryanmkurtz** [comment]
If we have missing relocations, it's usually because we didn't have a sample to develop against.  Which one of your attached files has the unsupported relocation?  I wouldn't mind taking a shot at it.

**Comment by gtackett** [comment]
It's ```data_init_standard.o```.

In this case the reference is to ```TBLPAG``` special function register, so this may have some relationship to the still-uncorrected error of that symbol being defined as value 0x31 instead of 0x32.

**Comment by ghidra1** [comment]
I took a stab at this for the function you indicated (see image).  Does it appear to refer to the correct location?  The referenced symbol (_TBLPAG) is defined at rom:010800.  I assume that ram:0800 is mapped to this rom location.
![Screenshot at 2021-02-23 12-15-34](https://user-images.githubusercontent.com/48333017/108881404-44ee1380-75d1-11eb-83c2-c058f473c890.png)

**Comment by gtackett** [comment]
The reference isn't really relocatable, although one might get that idea.

Relocation type 5 is always a reference to a special function register, and the offset (```0x23``` in this case) is always relative to ```ram:0F```, because:

```
w0 → ram:001 | ram:000
w1 → ram:003 | ram:002
.
.
.
w15 → ram:00f | ram:00e
```

```0x23 + 0x0f = 0x32``` and, voila!, we have the address of TBLPAG!

**Comment by ghidra1** [comment]
Then why does the relocation refer to the symbol _TBLPAG?  The relocation at 0x10006 is a type 7, also refers to _TBLPAG, and produces the same result.

**Comment by ghidra1** [comment]
I suspect the symbol processing within the linker is responsible for mapping register symbols to there actual location in memory.   Ghidra's ELF importer does not currently do such register mappings and instead allocates a fake external address for _TBLPAG and performs a fixup based upon the fake address of 0x800.

We will likely need to remedy the symbol processing for such register symbols for this to work properly.  The actual location for the TBLPAG register can vary based upon specific CPU variant.

![Screenshot at 2021-02-23 14-34-10](https://user-images.githubusercontent.com/48333017/108897589-42e18000-75e4-11eb-9454-90dd49c1107a.png)

**Comment by ghidra1** [comment]
I added register symbol processing and now get the following result.  Let me know what you think.
![Screenshot at 2021-02-23 14-59-27](https://user-images.githubusercontent.com/48333017/108900661-e08a7e80-75e7-11eb-8ef5-f56cee5a2aae.png)

**Comment by ghidra1** [comment]
We currently suppress default reference production on instructions to memory-based registers resulting in the display of an address.  I have tweaked the code unit format to replace the address with the register name if found.  Unfortunately, this replacement does not consider access type or size when searching for a register name.  See result below:
![Screenshot at 2021-02-23 15-53-24](https://user-images.githubusercontent.com/48333017/108907140-bb017300-75ef-11eb-96ec-faf3098ee896.png)
