### ISSUE TITLE
ARM Unsupported Relocations

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2794]
**Is your feature request related to a problem? Please describe.**
The arm/thumb relocations R_ARM_THM_JUMP11, R_ARM_THM_MOVT_ABS, R_ARM_THM_MOVW_ABS_NC, R_ARM_TARGET2 and R_ARM_TARGET1 are currently unsupported.

**Describe the solution you'd like**
These relocations should be supported.

**Comment by astrelsky** [comment]
So as far as Ghidra is concerned these relocations are no-ops. It appears they were set to do nothing in the past but had been commented out. Now Ghidra creates unnecessary error bookmarks which will make the user think something is wrong.

**Comment by bytehow** [comment]
@astrelsky Did you find out why they were commented out? I'm running into these same unsupported relocations (`R_ARM_THM_JUMP11` specifically) for sample objects taken from .alf archive.

@ryanmkurtz Do you know if Ghidra intends to support these relocations in the future?

**Comment by astrelsky** [comment]
> @astrelsky Did you find out why they were commented out? I'm running into these same unsupported relocations (`R_ARM_THM_JUMP11` specifically) for sample objects taken from .alf archive.
> 
> @ryanmkurtz Do you know if Ghidra intends to support these relocations in the future?

I don't know why they are commented out. In my case the program was pre-linked so the relocations had actually already been performed.

**Comment by bytehow** [comment]
My object is not prelinked unfortunately, so some instructions were incorrect without the proper relocation applied. Do you mind reopening this issue?

**Comment by ryanmkurtz** [comment]
Perhaps @ghidra1 can comment on these relocations.

**Comment by ghidra1** [comment]
I will look into the implementation of these relocations

**Comment by ghidra1** [comment]
I am going to proceed with a fix without addressing R_ARM_TARGET1 and R_ARM_TARGET2 at this point.

**Comment by ghidra1** [comment]
@astrelsky , @bytehow : I pushed a fix out to patch and master.  If possible, could you please test and verify my fix for those relocations which are impacting you.  Thanks.

Feel free to close this ticket if you are satisfied with the current state.  If you run into an issue please let me know the details of any improper relocation fixup.

**Comment by astrelsky** [comment]
> @astrelsky , @bytehow : I pushed a fix out to patch and master.  If possible, could you please test and verify my fix for those relocations which are impacting you.  Thanks.
> 
> Feel free to close this ticket if you are satisfied with the current state.  If you run into an issue please let me know the details of any improper relocation fixup. 

I'm good on my end, only reopened by request.

**Comment by ghidra1** [comment]
Thanks for identifying that.  I have pushed an update if you could try again.  Thanks.

Their are inconsistencies in our ARM-32 adjustment for PC-relative ELF relocations.    Unclear why R_ARM_JUMP24 and some others perform an offset adjustment and these do not.

**Comment by bytehow** [comment]
I can confirm that master @ [1a1d06b] (https://github.com/NationalSecurityAgency/ghidra/commit/1a1d06b749d4d7e505c493e6f8cad34ecf3df28f) applied my `R_ARM_THM_JUMP11` relocations correctly. Thanks @ghidra1 !
