### ISSUE TITLE
UI elements are unreadable in inverted Metal theme

### ISSUE THREAD

**Issue by RenaKunisaki** [NationalSecurityAgency/ghidra#2797]
**Describe the bug**
Using the Metal theme with Inverted Colors enabled, the UI checkboxes, buttons, and menu headers are nearly impossible to read.

**To Reproduce**
1. Go to Edit -> Tool Options in Ghidra's main window
2. Change "Swing Look and Feel" to "Metal" and check "Use Inverted Colors"
3. Restart Ghidra
4. Open any UI window with checkboxes, buttons, or menus

**Expected behavior**
Checkboxes appear black with white checks inside. Buttons and menu headers appear black with white text.

**Screenshots**
![2021-02-24-114617_998x575_scrot](https://user-images.githubusercontent.com/1185585/109035759-f3a85780-7696-11eb-9768-4a84660c59ea.png)
![2021-02-24-115241_2720x1596_scrot](https://user-images.githubusercontent.com/1185585/109035762-f3a85780-7696-11eb-8f6a-f9ed5054d78e.png)

**Environment (please complete the following information):**
 - OS: Artix x64
 - Java Version: 15.0.2
 - Ghidra Version: 9.2.2 (problem has existed since first public release)
 - GTK Theme: oomox-neonblue

**Additional context**
Screenshot of how this GTK theme normally looks:
![2021-02-24-115550_667x472_scrot](https://user-images.githubusercontent.com/1185585/109036061-3e29d400-7697-11eb-8968-41cf536864a8.png)

**Comment by dragonmacher** [comment]
This is a known issue with the 'Inverted Colors' mode.   This mode is a prototype mode and is unsupported at this time.   This should be replaced by true Dark Theme support.    Ghidra has no plans to offer Theme support at this time.

**Comment by M-a-r-k** [comment]
This problem can be worked around by using the original "steel" metal look & feel. To do that, add these lines to your launch.properties file:
```
VMARGS=-Dswing.metalTheme=steel
VMARGS=-Dswing.boldMetal=false
```

**Comment by M-a-r-k** [comment]
This issue could be considered to be a duplicate of issue 142.
