### ISSUE TITLE
Patch ARM instruction cmp.w produces incorrect operand value

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [NationalSecurityAgency/ghidra#280]
**Describe the bug**
On ARM Cortex, little-endian.

Using the patch feature on a cmp.w instruction creates an incorrect instruction.

**To Reproduce**
Load an arm some ARM Cortext little-endian binary, which contains a cmp.w instruction.
e.g.

    00026420 b1 f5 a0 2f     cmp.w      r1,#0x50000

Use the patch feature to change the compare value e.g. 0x60000 . Notice the bytes of the instruction change to

    00026420 a1 f5 c0 2f     cmp.w      r1,#0x60000

Change the compare value back again to its original value e.g 0x50000 

Observer the instruction bytes are not the same as the original bytes, despite the disassembly appearing to be the same

    00026420 a1 f5 a0 2f     cmp.w      r1,#0x50000

**Expected behavior**
Patching the instruction should produce the correct machine code instruction.

**Environment (please complete the following information):**
 - OS: Windows 7 Pro
 - Java Version: 11
 - Ghidra Version: 9

**Comment by mumbel** [comment]
either its weirder than it looks or you typo'd something.
I'm getting:
```
f5b1 2fa0 	cmp.w	r1, #327680	; 0x50000
f5a1 2fc0 	sub.w	pc, r1, #393216	; 0x60000
f5a1 2fa0 	sub.w	pc, r1, #327680	; 0x50000
f5b1 2fa0 	cmp.w	r1, #327680	; 0x50000
f5b1 2fc0 	cmp.w	r1, #393216	; 0x60000
```
from: `as -mthumb test.s ; objdump -D -Mforce-thumb a.out`
```
        .text
        .thumb
        .syntax unified
        .byte 0xb1, 0xf5, 0xa0, 0x2f // your cmp.w r1, #0x50000                                                         
        .byte 0xa1, 0xf5, 0xc0, 0x2f // your cmp.w r1, #0x60000                                                         
        .byte 0xa1, 0xf5, 0xa0, 0x2f // your cmw.w r1, #0x50000 (2nd)
        cmp.w r1, #0x50000
        cmp.w r1, #0x60000
```

**Comment by rogerclarkmelbourne** [comment]
I'm cutting and pasting from Ghidra


I'm pretty sure something is wrong with this.

The code is part of a range check for values between 0x30000 and 0x50000 which I need to extend to at least 0x60000

When I patched the code, it failed when the value requested was 0x30000, because the cmp.W r1,0x60000 should have caused a branch  (bcc) but it didn't.
Hence some other code was executed and the function returned the wrong memory addresses.

How come if I change the instruction back to the same address it was before, the byte codes are different.

**Comment by mumbel** [comment]
looks like that warning about an untested assembler is spot on.  I'm getting the same results as you

**Comment by rogerclarkmelbourne** [comment]
I you put the instruction bytes into the online decompiler it gives this

https://onlinedisassembler.com/odaweb/8WjvcjEi/0

![image](https://user-images.githubusercontent.com/6146984/55130202-16115d80-516e-11e9-9f48-56ba3c17a8a7.png)

So basically its screwing up both the assembly and disassembly.

The correct bytes for 0x60000 would be

B1 F5 c0 2F 

The problem  is caused because its changing the first byte (A1) to a B1 as well as changing the A0 to a C0 (which is what its supposed to change)

I did try to manually edit the bytes in the binary editor, but Ghidra does not allow the editing of instruction bytes

**Comment by emteere** [comment]
The root issue isn't the assembler.  The assembler is inverting the disassembly patterns (inverting is a bit of an understatement of what it is doing).

The root cause is the bit constraints on the thumb cmp instruction:

```
diff --git a/Ghidra/Processors/ARM/data/languages/ARMTHUMBinstructions.sinc b/Ghidra/Processors/ARM/data/languages/ARMTHUMBinstructions.sinc
index a9c655d..4475e94 100644
--- a/Ghidra/Processors/ARM/data/languages/ARMTHUMBinstructions.sinc
+++ b/Ghidra/Processors/ARM/data/languages/ARMTHUMBinstructions.sinc
@@ -1614,7 +1614,7 @@
 
 @if defined(VERSION_6T2) || defined(VERSION_7)
 
-:cmp^ItCond^".w"    Rn0003,ThumbExpandImm12  is TMode=1 & ItCond & (op11=0x1e & thc0909=0 & sop0508=13 & Rn0003; thc1515=0 & thc0811=15) & ThumbExpandImm12
+:cmp^ItCond^".w"    Rn0003,ThumbExpandImm12  is TMode=1 & ItCond & (op11=0x1e & thc0909=0 & thc0404=1 & sop0508=13 & Rn0003; thc1515=0 & thc0811=15) & ThumbExpandImm12
 {
   build ItCond;
   th_subflags(Rn0003,ThumbExpandImm12);
```

It is a little more complicated than that.  This change causes the bad decode to shift to the sub instruction:
```
sub pc,r1,#0x60000
```
This form is listed as UNPREDICTABLE behavior in the latest ARM spec, but some processors might actually assign to the PC.  ARM has tightened up writes to the PC from various instructions.  This is most likely an issue in other uses of the PC.  The designers of the ARM processor did try to catch these types of issues, and there have been various automated methods applied to try and verify the decodes and semantics.

So an addition of constraints on the PC for the sub form and others will be necessary.
One possible fix is to add the following for sub instructions and possibly others.

```
define pcodeop UNPREDICTABLE;

Rd0811_noPC: pc is Rd0811=15 & pc { tmp:4 = UNPREDICTABLE(pc); export tmp; }
Rd0811_noPC: Rd0811 is Rd0811 { export Rd0811; }

:sub^thSBIT_CZNO^ItCond^".w"	Rd0811_noPC,Rn0003,ThumbExpandImm12 		is TMode=1 & ItCond & (op11=0x1e & thc0909=0 & sop0508=13 & thSBIT_CZNO & Rn0003; thc1515=0 & Rd0811_noPC) & ThumbExpandImm12
{
  build ItCond;
  build ThumbExpandImm12;
  th_subflags(Rn0003,ThumbExpandImm12);
  Rd0811_noPC = Rn0003-ThumbExpandImm12;
  resflags(Rd0811_noPC);
  build thSBIT_CZNO;
}
```

Adding special constraints to all the affected instructions, but that could be expensive in the match patterns.
A simpler solution is just to add another token, and attach table:
```
  Rd0811_noPC=(8,11)
...
  attach variables [ Rd0811_noPC ] [ r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 sp lr _ ];
```

It all depends on whether the instruction should disassemble and provide any semantics.

**Comment by nsadeveloper789** [comment]
@rogerclarkmelbourne In the assembler completions window, there is a little ?/0 button in the lower left. When the assembler "completes" an instruction, there are sometimes undefined bits left after applying all the patterns. By default, it simply sets those bits to 0. Clicking that button will allow those bits to be either 0 or 1, producing all the possibilities. Enabling that button will allow you to assemble the correct instruction.

A word to the wise: use that button carefully. If there are tons of undefined bits, it can grind to a halt.

**Comment by rogerclarkmelbourne** [comment]
@nsadeveloper789 

Thanks.

The code did grind do strange things after I patched it ;-)
Actually, I've patched a lot of simple instructions with this feature and its been OK.
This is the first time I had a problem, but perhaps 2 byte instructions are less ambiguous.

@emteere 
Unfortunately I don't know much about the ARM instruction set. I'm normally a C programmer, but in this case the C source is not available. Hence I'm having to fix bugs by patching the assembler.

**Comment by mumbel** [comment]
@emteere this kinda sparked me (found a few other issues) looking further into the various instructions that act like semi-mnemonic/SEE instructions.

A lot of instructions (at least) for ARM/THUMB seem to rely on Rx==15=>UNPREDICTABLE or SEE other.  Do you think there is a generic approach to this?  Based on your previous comment the `attach` code seems like a good approach.  Do you see any larger concerns there?

Looking at `support/sleigh` for ARM, it becomes pretty obvious that most of the results come down to not allowing Rn/Rd/Rm/Rt being PC (and also should any of these results be treated as false-positives (considering a `_noPC` approach)
