### ISSUE TITLE
Cannot create pascal string

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2800]
**Describe the bug**
Attempting to create a pascal string where one exists and is not defined results in "Invalid data location. Instruction exists at ..."

**To Reproduce**
1. Load a program written in pascal
2. Find a pascal string in memory
3. Attempt to create a pascal string

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19042.804]
 - Java Version: 15.0.2
 - Ghidra Version: 9.3_DEV
 - Ghidra Origin: locally built

**Additional context**
The location where the string is attempting to be created is cleared. Clear with options has been used with all options checked.

**Comment by astrelsky** [comment]
> What are the beginning bytes of the pascal string? Which pascal string type are you using?

![Capture](https://user-images.githubusercontent.com/46897303/109564242-c8ff3a00-7aae-11eb-954d-48ac196d582b.PNG)

**Comment by astrelsky** [comment]
I believe I misunderstood the types. I'm guessing `PascalString` expects a number bigger than 1 byte so I should have used PascalString255. My mistake.

**Comment by dev747368** [comment]
Yes, you want the PascalString255
