### ISSUE TITLE
Decompiled Source on Dev Build is different compared to Public v9.2.1 Build

### ISSUE THREAD

**Issue by wanitaqing** [NationalSecurityAgency/ghidra#2804]
Hi, 

I've created my own simple ATM executable with functions like deposit, withdrawal of money and check balance. 
However, when i import my atm.exe into both the Dev & Public Builds, I received the following errors:

![image](https://user-images.githubusercontent.com/47132451/109738751-55227600-7c03-11eb-9a24-fe38d5dcbede.png)

![image](https://user-images.githubusercontent.com/47132451/109738829-89963200-7c03-11eb-8573-a1baa69abb71.png)

When I viewed the decompiled source code using the Public v9.2.1 Build, the decompiled code seems readable as shown below. 
![image](https://user-images.githubusercontent.com/47132451/109751007-83f71700-7c18-11eb-911e-61882ddfae98.png)

However, when i import the same exe into the dev Build, the decompiled code seems weird and difficult to understand 
![image](https://user-images.githubusercontent.com/47132451/109748735-51e3b600-7c14-11eb-8b01-7628a15477cb.png)

Is it normal for me to receive the errors above? And is it normal for the decompiled code in Dev Build to be less readable?

**Comment by ryanmkurtz** [comment]
The ghidra repo does not contain all of the large Function ID database files, which are used to identify your missing library functions.  They can be found in this repo: https://github.com/NationalSecurityAgency/ghidra-data/tree/master/FunctionID

Here is another ticket that talks about how to get them imported into Ghidra: https://github.com/NationalSecurityAgency/ghidra/issues/1847

**Comment by wanitaqing** [comment]
@ryanmkurtz sflr, thank you for your reply, will try it out. But for the errors on the missing DLLs as shown in the first screenshot, is it normal to receive those?

**Comment by ryanmkurtz** [comment]
The `[KERNEL32.DLL] -> not found` means that when Ghidra was trying to resolve the external references of the program you imported, it failed to find an already imported `KERNEL32.DLL` program in your Ghidra project.  You could either manually import it, or when you go to import your main program, check the "Load External Libraries" option.  This is only useful if you want to also reverse engineer kernel32.dll and you want the convenience of being able to click on the external reference from your main program to have Ghidra automatically take you into kernel32.dll at the right spot.
