### ISSUE TITLE
API access to function graph edge labels

### ISSUE THREAD

**Issue by fcwze** [NationalSecurityAgency/ghidra#2805]
Would it be possible to provide guidance or an example on how to access the edge labels of function graphs?

I'd like to be able to programmatically provide my own annotations to edges to supplement the current '_If/Else_', '_Do loop_' labels. I've spotted the `FGEdgeImpl::setLabel(String label)` method which I think provides these labels but haven't been able to successfully access this from a script.

Thank you.

**Comment by dragonmacher** [comment]
Amazingly, this is the first time we've had a request to access the function graph API from a script.   Resultingly, no such access exists.   Currently, if you would like to change Function Graph behavior, then you will have to modify the plugin's source code directly.
