### ISSUE TITLE
Ghidra decompiler crashes on OLLVM obfuscated samples

### ISSUE THREAD

**Issue by enovella** [NationalSecurityAgency/ghidra#281]
**Describe the bug**
The decompiler crashes and pops out several windows with the same info.

**To Reproduce**
- Load ARM32 binary attached
- Decompile function `undefined8 Java_appsolid_Sdk_memhack(undefined8 uParm1,undefined8 uParm2)`

**Expected behavior**
Compiler crashes. Decompilation is shown though.

**Screenshots**
![ghidra-dec-crash](https://user-images.githubusercontent.com/14809754/55130112-8c33a700-5111-11e9-966b-91253d2d7a94.png)

**Attachments**
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	decompile.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5c99500f
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.23915
  Fault Module Timestamp:	59b94ee4
  Exception Code:	c00000fd
  Exception Offset:	000000000004dd43
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	e40b
  Additional Information 2:	e40b437217cd93cdfc50b1bfd29eb835
  Additional Information 3:	94af
  Additional Information 4:	94af25c5dd182d5d7aa5c44f5d14518e

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Environment (please complete the following information):**
 - OS: [Win7]
 - Java Version: [11.0]
 - Ghidra Version: [9.0.1]

**Additional context**

[samples.zip](https://github.com/NationalSecurityAgency/ghidra/files/3016187/samples.zip)

**Comment by mendax47** [comment]
Looks Fine To Me....

![image](https://user-images.githubusercontent.com/6140928/55133340-8b216a80-514f-11e9-92e2-b8634f7284b3.png)

**Comment by saruman9** [comment]
You load AArch64 binary on the screenshot, but `samples.zip` contains only x86, x86_64 and ARM32 binaries.

Btw, `Java_appsolid_Sdk_memhack` from `samples.zip` is decompiled well.

**Comment by enovella** [comment]
I loaded ARM32, but I got some crashes. The decompilation went `okay` though (or at least the decompiled code seems okay)

**Comment by GhidorahRex** [comment]
I wasn't able to reproduce this at present. If there are any additional decompiler crashes, please create a new issue.
