### ISSUE TITLE
Better keyboard integration (use of Accelerators)

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#2811]
**Is your feature request related to a problem? Please describe.**
When using the keyboard to navigate Ghidra, some menus have Accelerator Keys, but some don't.  Any long menus especially would benefit from this.

**Describe the solution you'd like**
Added Accelerator Keys to as many menu items as possible.  (Even duplicates would be preferable to none, as long as they aren't all using the same!)

**Describe alternatives you've considered**
Using the arrow keys, which can be cumbersum and not optimum.  The mouse in my case is difficult as I have to use the numeric keyboard to emulate it (under Windows, that's MouseKeys).

**Additional context**
Goes with the new `Context Menu` keyboard enhancement (thanks for that - commit ada8f0b4d77e0fd624828c03532d1a0c571cff22).

**Comment by dragonmacher** [comment]
I'm thinking about the best way to tackle this issue.    I was going to add the ability to set the menu mnemonic, but that seems like overkill due to the infrastructure needed and how much work it would be for the user to have to set so many mnemonic values.

I am now pondering a simpler solution, maybe with some sort if auto mnemonic generation for those items without a value set.

Is it safe to assume that you would also like mnemonics on the popup actions as well?  (Not sure how hard that would end up being.)

**Comment by Wall-AF** [comment]
> Is it safe to assume that you would also like mnemonics on the popup actions as well? (Not sure how hard that would end up being.)

That'd be fantastic too.

**Comment by dragonmacher** [comment]
Unusual idea: would it be useful if pressing a number on the keyboard caused the menu item to focus that menu item?     For example, if you press 8, the 8th item gets highlighted.     Repeated number presses could jump by that amount.    For example, you could press 4 repeatedly to jump from the 4th item to the 8th item, etc.

Also, we could add other shortcuts.  For example, `Page Up/Down` could jump between menu groups withing a particular menu.   `End/Home` could be used to jump to the top and bottom of the menu.

Admittedly, it may be hard to judge the utility of this without being able to try it.

We can certainly add more mnemonics to existing actions, but we would never be able get them all.   The above suggestion would allow you to move through the menus faster than using the arrow keys.

Thoughts/suggestions?

**Comment by Wall-AF** [comment]
> Unusual idea: would it be useful if pressing a number on the keyboard caused the menu item to focus that menu item? For example, if you press 8, the 8th item gets highlighted. Repeated number presses could jump by that amount. For example, you could press 4 repeatedly to jump from the 4th item to the 8th item, etc.

That's novel!  I like it!  Unsure what others would make of it though.


 
> Also, we could add other shortcuts. For example, `Page Up/Down` could jump between menu groups withing a particular menu. `End/Home` could be used to jump to the top and bottom of the menu.

That's good too. 


> Admittedly, it may be hard to judge the utility of this without being able to try it.

You'd get used to this.

> We can certainly add more mnemonics to existing actions, but we would never be able get them all. The above suggestion would allow you to move through the menus faster than using the arrow keys.

That'd be great.

**Comment by Wall-AF** [comment]
> > Unusual idea: would it be useful if pressing a number on the keyboard caused the menu item to focus that menu item? For example, if you press 8, the 8th item gets highlighted. Repeated number presses could jump by that amount. For example, you could press 4 repeatedly to jump from the 4th item to the 8th item, etc.
> 
> That's novel! I like it! Unsure what others would make of it though.

Having slept on this, I've had some additional thoughts:

- `0` -> could take you to the begining of the menu (i.e. 1st option)
- `1-9` -> could move the choice forward `n` items
- `[AccKey][1-9]` -> could move forward `n` items that share the same accelerator key (only required for really long, un-segmentable menus)

Maybe this style of access should be patented.

**Comment by dragonmacher** [comment]
@Wall-AF the code is in the repo now.  If you are setup to run from the repo, then you can try it.

**Comment by Wall-AF** [comment]
Great.  I might look at adding `a-z` to move `10-35` at some point.  Thanks alot folks.
