### ISSUE TITLE
Creating a new folder whose name is hidden by filter, leads to Null Pointer Exception

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2812]
**Describe the bug, and how to reproduce it**

1. In the Projects window, in Tree view, create a filter that will not allow "New Folder" to be displayed.
2. Create a new folder (I used the pop-up menu on the top level folder)
3. As expected, the new folder is not visible.
4. Try to clear the filter. (I had to click the "X" twice.)
5. A Null Pointer Exception occurs, and the filter is not cleared.
At this point, I had to close and re-open the project, in order to clear the filter. Then I could see the New "New Folder" Folder. 😄 

**Expected behavior**

- The filter would be cleared.
- No error would occur.

**Screenshots**
An mp4 screen recording is attached.

https://user-images.githubusercontent.com/52077/110176122-d5e29d00-7dd0-11eb-92f0-2c58ae3d40a3.mp4

**Attachments**
The Ghidra log file is attached.
[Ghidra.log](https://github.com/NationalSecurityAgency/ghidra/files/6093495/Ghidra.log)

**Environment (please complete the following information):**
 - **OS**: macOS 10.14.6
 - **Java Version**: jdk 12.0.1
 - **Ghidra Version**: 9.2.2 public
 - **Ghidra Origin**: Official ghidra-sre.org distro

_Although submitted against Ghidra 9.2.2 and on macOS 10.14.6, I have seen the same problem in 9.1 and perhaps earlier, and on Windows 10._

**Comment by gtackett** [comment]
Although submitted against Ghidra 9.2.2 and on macOS 10.14.6, I have seen the same problem in 9.1 and perhaps earlier, and on Windows 10.

**Comment by mumbel** [comment]
possibly not the same bug, but looks similar to #2799

**Comment by dragonmacher** [comment]
I just tried this with the fix for #2799 and it does not happen.   I believe it is the same bug.

**Comment by burakturkoglu54** [comment]
#2812
