### ISSUE TITLE
Relocations are "doubly-applied" on entry point functions

### ISSUE THREAD

**Issue by srmish** [NationalSecurityAgency/ghidra#2815]
**Describe the bug**
A bug was introduced in Ghidra 9.2 where it seems that relocation offsets are applied twice on entry points, causing the entry points to be defined in the wrong address.
For example, in the attached file, we can see entry point `_INIT_22` supposed to be defined at 0x**2**80b8:
![image](https://user-images.githubusercontent.com/8236550/110249152-66f67700-7f7d-11eb-82c7-64fbcb72b06a.png)
(The bytes were originally b8 80 **01** 00, but fixed up with relocation +0x10000, which is expected behavior)

However, the function itself ends up getting defined at 0x**3**80b8, an address which does not contain the correct function bytes:
![image](https://user-images.githubusercontent.com/8236550/110249189-a1f8aa80-7f7d-11eb-8044-f812448d846f.png)

Note that in Ghidra 9.1.2, this issue is not present. The bytes are still fixed up to 0x280b8 correctly but this time the function is also defined at that exact address:
![image](https://user-images.githubusercontent.com/8236550/110249209-c81e4a80-7f7d-11eb-84cd-6310a6b7d6b0.png)

**To Reproduce**
1. Import the attached ELF binary in Ghidra 9.2 (or later) and analyze using default analysis options
2. Go to label "_INIT_22"
3. See that function is defined at address 0x380b8 instead of 0x280b8

**Expected behavior**
The "_INIT_22" function should have been defined at address 0x280b8

**Attachments**
The binary that causes the issue -
[libserver.zip](https://github.com/NationalSecurityAgency/ghidra/files/6097653/libserver.zip)

**Environment**
 - OS: Windows & Linux
 - Java Version: 11.0.4
 - Ghidra Version: 9.2 (and later)
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**
I think the bug might be related to [this commit](https://github.com/NationalSecurityAgency/ghidra/commit/d68f3697e388732faced52063cda7fca3881ec9a), specifically due to this change -
![image](https://user-images.githubusercontent.com/8236550/110249035-9b1d6800-7f7c-11eb-9439-b25fb6b64397.png)
But I have not confirmed this

**Comment by ghidra1** [comment]
I believe this may have already been resolved.  Could you please try Ghidra 10.0 and verify that this is no longer an issue.

**Comment by ghidra1** [comment]
@srmish I assume this has been resolved.  If not please respond.
