### ISSUE TITLE
MIPS disassembler misses JR $ra   opcodes 

### ISSUE THREAD

**Issue by tlalonde** [NationalSecurityAgency/ghidra#2816]
**Describe the bug**
on disassembly the opcode 03 E0 00 08 is not disassembled to jr $ra

**To Reproduce**
        ```
00016528 8f be 00 00     lw         s8=>local_8,0x0(sp)
        0001652c 27 bd 00 08     addiu      sp,sp,0x8
        **00016530 03              ??         03h
        00016531 e0              ??         E0h
        00016532 00              ??         00h
        00016533 08              ??         08h**
        00016534 00 a0 10 25     or         v0,a1,zero
        00016538 00 85 18 26     xor        v1,a0,a1
```

**Expected behavior**
code is jr $ra

**Screenshots**

**Attachments**

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Java Version: [java version "1.8.0_101"]
 - Ghidra Version: [ 9.2.2]
 - Ghidra Origin: [official ghidra-sre.org distro] 

**Additional context**

**Comment by mumbel** [comment]
You probably need to clear out the instruction after it first so it can correctly process the branch delay slot

**Comment by GhidorahRex** [comment]
I'm not able to reproduce this. When I paste the bytes into ghidra 9.2.2 they disassemble correctly.

**Comment by tlalonde** [comment]
If I revert the disassembly of several bytes around the area then select and disassemble it works.
I will withdraw the bug.

Thanks

**Comment by GhidorahRex** [comment]
Issue was resolved.
