### ISSUE TITLE
Register used in Pcode PTRSUB defined from nowhere

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#2823]
Hello again!

I have a new question this time... I have encountered a pcode operation in which one of the inputs' definition comes from nowhere (i.e. a register with no "def").

![image](https://user-images.githubusercontent.com/22150653/110644494-25371d80-8183-11eb-8040-acb705285eb1.png)

This "nowhere" comes from checking the variable as such:
![image](https://user-images.githubusercontent.com/22150653/110644811-77783e80-8183-11eb-811c-0f119f4c475d.png)

I would like to know why this variable has no defining pcode. In other words, I am trying to determine what can be said about the contents of this register in relation to the rest of the program.

**Comment by ghidracadabra** [comment]
Is it an input to the function?  In that case there would not be a pcode operation which defines it.

Note that there is a method Varnode.isInput()

**Comment by ryanmkurtz** [comment]
Assuming that your question has been answered...closing.
