### ISSUE TITLE
Wrong Register Representation Due to Renamed Variable

### ISSUE THREAD

**Issue by chezwicker** [NationalSecurityAgency/ghidra#2827]
**Describe the bug**

When a variable is renamed in the "Decompile" component, this leads to registers being represented by that name as well in the "Listing" component. Unfortunately, this effect seems to be "stickier" than it should be: the register representation should be turned back to the register name when it is no longer used to hold the variable in question.

**To Reproduce**

The following code compiled with `gcc -std=c99 -pedantic -fno-stack-protector repro.c -o repro && strip repro` leads to the result shown in the screenshot.

```C
#include <stdio.h>
#include <string.h>

int main(int argc, char const* argv[]) {
	int diff = strcmp(argv[1], "xyz");
	printf("%s: %i", "Done", diff);
	return 0;
}
```

**Expected behavior**

Registers are only represented by names of variables they are used for.

**Screenshots**

![repro](https://user-images.githubusercontent.com/10724464/110786001-e761f400-826b-11eb-8d97-70b5f7d2e9af.png)

**Environment (please complete the following information):**

 - OS: 10.15.4
 - Java Version: 11.0.1
 - Ghidra Version: 9.3 DEV, commit b69c3d6c50c666ccece1fcc25e5ab7561ba57072
 - Ghidra Origin: locally built

**Additional context**

At the same time (but this is probably not a bug), it would be nice if the stack offsets where a variable's value is stored were represented by the same name (maybe with the possibility to apply different font formatting, e.g. italic). This might also avoid "unused variables" showing up in the Decompiler component when these labels are assigned a type - see #2828

**Comment by ghidra1** [comment]
A register variable only specifies its first-use offset and not its entire scope.  Within the **assembly** listing, Ghidra relies on a subsequent register variable to be defined which will come into scope.  without a subsequent variable for a given register, the last one will remain in-scope for the remainder of the function.  The variable scope mechanism employed is very simplistic and certainly has its limitations in this regard.

**Comment by ghidra1** [comment]
Closing this issue since this behavior is a consequence of our current scoping design which we have no current plans on revising.

**Comment by Wall-AF** [comment]
I don't think this should be dismissed as "Working as intended"!  To me it's a bug that hampers the reading of subsequent assembly, contributing to an already difficult process.  Following the example above, the user is naming the resulting return location from the function call to `_strcmp(...)` which is `local_1c` as `diff`.  I understand that the call uses register(s) to return results, but surely its possible to recognise this and name appropriately.

**Comment by chezwicker** [comment]
Just wondering if there was any input into this by @caheckman ?
