### ISSUE TITLE
GhidraDev absolute paths using

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#284]
In files that are located in Eclipse project directory there are so many absolute paths. So, when you want to port your old project to the new version of Ghidra it requires to change all these paths.

I think it is related to this issue: https://github.com/NationalSecurityAgency/ghidra/issues/283

**Comment by ryanmkurtz** [comment]
You can use the "Link Ghidra" GhidraDev command to point your Eclipse project to a new version of Ghidra.

**Comment by lab313ru** [comment]
Still NullPointerException with my project:(

**Comment by lab313ru** [comment]
> You can use the "Link Ghidra" GhidraDev command to point your Eclipse project to a new version of Ghidra.

It is not a good way to export source codes of any projects, I mean with absolute paths.

**Comment by ryanmkurtz** [comment]
Agreed, it's not ideal.  Ghidra basically doesn't properly support importing and exporting projects at this time.  I'll consider this issue an enhancement request.

**Comment by ryanmkurtz** [comment]
Relates to #283
