### ISSUE TITLE
Cannot click on the results from "string search", cannot take me to the place at the decompiled code.

### ISSUE THREAD

**Issue by sdajklfw389** [NationalSecurityAgency/ghidra#2842]
I am not sure if its just me, or it is by default? Or am I using it wrong?

My Ghidra version is 9.0.4

but I see tutorial that easily click on the results and then jump to the place in code.

![image](https://user-images.githubusercontent.com/15469832/111080362-6cfcd280-84fe-11eb-83aa-1b1e8a807c6b.png)

Many thanks in advance!

**Comment by ryanmkurtz** [comment]
Is your Defined Strings navigation toggle button turned on?

![image](https://user-images.githubusercontent.com/5378554/111150305-4c676380-8564-11eb-9572-f96ec5eab569.png)

**Comment by sdajklfw389** [comment]
@ryanmkurtz yes, it is turned on. But still..

But I installed the newest Ghidra and it works now.
