### ISSUE TITLE
Empty/Blank Window loads up

### ISSUE THREAD

**Issue by knight-byte** [NationalSecurityAgency/ghidra#2847]
OS: Arch Linux 
Ghidra ver: v9.2.2

**Issue:** I am using Arch linux with Xmonad Window Manager. When i start the application in It only show a Empty/Blank window
but works perfectly in Arch with KDE

https://user-images.githubusercontent.com/54370855/111292588-55dcf280-866e-11eb-8877-f93b866f0358.mp4

above video is the Xmonad config

**Comment by ryanmkurtz** [comment]
The problem is likely a problem with Java's support of that platform and not Ghidra.  You could try the solutions presented here:

https://stackoverflow.com/questions/41832881/java-gui-xmonad-not-working
