### ISSUE TITLE
ARM decode failure: spurious shift from ARM to THUMB

### ISSUE THREAD

**Issue by atlas0fd00m** [NationalSecurityAgency/ghidra#285]
**Describe the bug**
the original identification was that "BNE decodes as LSL in ARM mode"... but upon closer inspection, it appears the decoder is changing into THUMB mode without apparent cause:

                             LAB_009bb914                                    XREF[1]:     009bb908(j)  
        009bb914 00 00 54 e3     cmp        r4,#0x0
        009bb918 00 00 53 13     cmpne      param_4,#0x0
        009bb91c 01 00           lsl        param_2,param_1,#0x0
        009bb91e 00 1a           sub        param_1,param_1,param_1

when it should decode to the following:

    (from Vivisect)
    .text:0x027bb914  000054e3         cmp r4,#0x00
    .text:0x027bb918  00005313         cmpne r3,#0x00
    .text:0x027bb91c  0100001a         bne loc_027bb928

clearly the first two instructions are being decoded correctly, but then Ghidra is decoding the next instruction as THUMB LSL (btw, if imm5==0, it's supposed to be a MOV instruction).

**To Reproduce**
i believe you simply need to decode these bytes in this order, but since i'm not sure what's causing it, I'm not sure.  
if it makes any difference, this is taken from an ELF library compiled for Android.

**Expected behavior**
i expect the decoder to track the ARM/THUMB state correctly throughout analysis

**Environment (please complete the following information):**
 - OS: Linux (Kubuntu) 18.04.2 64-bit
 - Java Version: 11.0.2
 - Ghidra Version: 9.0 - public - released 2019-02-28

**Additional context**
i'm not sure what else to say.  it isn't the target of a branch that I can tell (unless the sudden mode change somehow doesn't show any XREFs to that address), so I'm not sure what would make Ghidra spontaneously shift gears like this.  this is 8-bytes after a branch target, so there's potential for a complicated bug involving the fact that ARM mode execution pipeline has "effective PC" 8 bytes beyond real PC in the Operand decoding context (ie. PC-relative addressing is 8-bytes greater than is intuitively pleasing.

**Comment by atlas0fd00m** [comment]
sadly the lib is very large and i cant share it. :(

**Comment by emteere** [comment]
Works fine for me.  If you clear it and re-disassemble does it come back this way?
Is there much non-returning functions that were fixed up in the binary?
Is there a red bookmark at the location?

It is possible there was bad thumb flow to the location, that was previously cleared because of non-returning functions, and the thumb mode is left there.

There is a hidden thumb register that specifies the mode to disassemble.  Ghidra is very careful to try and follow ARM/Thumb mode disassembly.  The most likely culprit is old flow that was cleared, or somehow the Thumb mode bit got set there (could even be from import).

You can turn the hiden registers on with:
Edit->ToolOptions...->Options->ListingFields->RegisterField->Display Hidden and Default Register values.

You can check before and after analysis to see when this starts occuring.  You can also turn analyzers off, like the Discover No Return functions analyzer to see if it is the culprit.

**Comment by atlas0fd00m** [comment]
awesome, thank you.  i'll look into it (i figured i'd learn something about Ghidra in the process).
i have not manipulated the binary in any particular way.  i don't know Ghidra enough to do anything fancy.  i've only ever renamed functions, and i don't think that was on this bin.  it should be in a pretty pristine state.

i'll check out what you indicated, and get back to you.  

thanks@

**Comment by atlas0fd00m** [comment]
yes, there is a red X by the first thumb instruction.
i did clear and reflow and it looks fine now.  i the closed without saving in case there's anything more i can tell you.

i turned on the hidden registers and the code block now looks like this:

                             LAB_009bb914                                    XREF[1]:     009bb908(j)  
        009bb914 00 00 54 e3     cmp        r4,#0x0
        009bb918 00 00 53 13     cmpne      param_4,#0x0
             assume TMode = 0x1
        009bb91c 01 00           lsl        param_2,param_1,#0x0
        009bb91e 00 1a           sub        param_1,param_1,param_1
        009bb920 02 00           lsl        param_3,param_1,#0x0
        009bb922 a0 e3           b          LAB_009bc066
             assume TMode = 0x0  (Default)

**Comment by emteere** [comment]
Something definitely flowed there incorrectly as thumb before.  Suspect it was a non-returning function that didn't clean up, however it should have cleared.

There is a potential it is an instruction start pattern gone wild.  Or a found heuristic flow from cleared bad code.

If you re-import from scratch, then save.

If you import from scratch and this section is labeled as having the Thumb bit on, then that would be an issue with the import ELF loader

Try analyzing with the Discover NonReturning functions analyzer off, there might be leftover code here.
If it is still the same, then undo and disable another one.  There really aren't many that could cause this though.

I'd try to see how and when the location flowed there as Thumb.  You could try firing up Ghidra in eclipse under debug, and then stopping when a create instruction call is made to the program API, but that might be a little deep.  If you go to the location during before analysis, then analyze, you may catch what it is doing during analysis when the thumb is laid down.

The processor designer must have missed the MOV as the preferred variant.  When building a processor module we try to catch them all, but it is a large instruction set with many variants.

Hope you find Ghidra useful.  It is good to have a full toolbox.

**Comment by atlas0fd00m** [comment]
yeah, the recommended ARM aliases have changed a lot over the years, including a massive UAL change, to align ARM and THUMB assembly mnemonics.

thanks.  i'll give these a whirl and see what i can figure out.

**Comment by GhidorahRex** [comment]
The conversation seems to have ended here, and possibly resolved the issue. I'll go ahead and close the ticket.
