### ISSUE TITLE
Possible infinite loop on decompiling simple functions on x86 and ARMv8 binaries

### ISSUE THREAD

**Issue by XVilka** [NationalSecurityAgency/ghidra#2851]
**Describe the bug**
For both `harp-utils.c-gcc-arm64-O0.o` and `s_ceill.c-gcc-x86-O2.o` files Ghidra decompiler stuck forever for particular functions

**To Reproduce**
### `harp-utils.c-gcc-arm64-O0.o`
1. Go to `harp_get_valid_min_for_type` function
2. Try to decompile
3. It stuck forever

### `s_ceill.c-gcc-x86-O2.o`
1. Go to `ceill_long_double` function
2. Try to decompile
3. It stuck forever

**Expected behavior**
Successful decompilation or at least some error/warning message

**Screenshots**

![image](https://user-images.githubusercontent.com/203261/111413256-e1ab5900-8718-11eb-801f-1a63fb9308f1.png)

**Attachments**

[harp-utils.c-gcc-arm64-O0.o.zip](https://github.com/NationalSecurityAgency/ghidra/files/6153682/harp-utils.c-gcc-arm64-O0.o.zip)
[s_ceill.c-gcc-x86-O2.o.zip](https://github.com/NationalSecurityAgency/ghidra/files/6153683/s_ceill.c-gcc-x86-O2.o.zip)

Files are compiled from open source software and freely redistributable, feel free to use it in your testsuite.

**Environment (please complete the following information):**
 - OS: any
 - Java Version: any
 - Ghidra Version: any
 - Ghidra Origin: any

(We confirmed the bug on multiple computers/platforms, it also happens in RzGhidra.

**Additional context**

https://github.com/rizinorg/rz-ghidra/issues/204#issuecomment-800394952

**Comment by caheckman** [comment]
I'm reproducing this infinite loop.  Looks like a decompiler rule is erroneously indicating it has made a change, when it hasn't.  Thanks for the report.
