### ISSUE TITLE
Proper language Analyzing a non-executeable dat file

### ISSUE THREAD

**Issue by Marsfan** [NationalSecurityAgency/ghidra#2857]
I am using Ghidra as a way to annotate a binary data file that is not an executable programs since Ghidra has standard C types built in. Is there a specific language that I should select when importing the binary file?

**Comment by dev747368** [comment]
There are some languages named "data".

**Comment by astrelsky** [comment]
As stated above there is a "data" language selection. You can also choose the endianess as well.
