### ISSUE TITLE
Java decompiler failure: Error getting pcode snippet for java 8 streams

### ISSUE THREAD

**Issue by afranco20** [NationalSecurityAgency/ghidra#287]
**Describe the bug**

The decompiler throws the error when attempting to view a function that utilizes java 8 streams.

```
  Low-level Error: Error getting pcode snippet: class
       ghidra.javaclass.format.constantpool.ConstantPoolInterfaceMethodReferenceInfo cannot be cast
       to class ghidra.javaclass.format.constantpool.ConstantPoolMethodReferenceInfo
       (ghidra.javaclass.format.constantpool.ConstantPoolInterfaceMethodReferenceInfo and
       ghidra.javaclass.format.constantpool.ConstantPoolMethodReferenceInfo are in unnamed module of
       loader ghidra.GhidraClassLoader @27abe2cd)
``` 

**To Reproduce**

1. Save the following snippet into a file named `Foo.java`
2. Compile the code using `javac Foo.java`
3. Open Ghidra and import `Foo.class`
4. Auto analyze `Foo.class`
5. Go to the symbol tree and click on `main` under the `Functions` folder
6. View the decompiler output `Ctrl + E`

```java
import java.util.stream.IntStream;

class Foo {
  public static void main(String[] args) {
    // print values 1 - 10 using IntStream
    IntStream.rangeClosed(1, 10).forEach(i -> System.out.println(i));
  }
}
```

**Expected behavior**

The expected behavior is for the decompiler to produce java code

**Environment**
OS: Linux (Arch)
Java Version: 1.8.0_212
Ghidra Version: 9.0.1

**Comment by ghidracadabra** [comment]
Thanks for reporting this!

**Comment by ryanmkurtz** [comment]
[Fixed](https://github.com/NationalSecurityAgency/ghidra/commit/e3ae5a0370808fb4f1050ac3d72d5c2705601a00) for 9.1.
