### ISSUE TITLE
Error java.lang.ClassNotFoundException: LaunchSupport  Installation on Windows

### ISSUE THREAD

**Issue by cherry-licongyi** [NationalSecurityAgency/ghidra#2872]
Download the latest ZIP from GitHub, when running ghidraRun.bat (on Windows 10) will appear the following error;
```
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport
Error: Could not find or load main class LaunchSupport
Caused by: java.lang.ClassNotFoundException: LaunchSupport
```
java version
```
C:\Users\seed>java --version
java 15 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```
System environment variables are set as follows:
```
JAVA_HOME=C:\Program Files\Java\jdk-15
Path=C:\Program Files\Java\jdk-15\bin
```

**Comment by astrelsky** [comment]
The releases on GitHub are not built and only contain the source code. You must either build it yourself by following the instructions in DevGuide.md or use the pre-built release provided on the [project homepage](https://www.ghidra-sre.org/)

**Comment by ryanmkurtz** [comment]
I am going to add a check in the launch scripts to make this common error more clear about what is going on.

**Comment by ryanmkurtz** [comment]
Relates to #2697 and #337
