### ISSUE TITLE
how to add Function tag column in function reference window

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2873]
i am wondering how can i display and filter let say ref to strncpy that i have a Tag 
![image](https://user-images.githubusercontent.com/4013370/112750833-29f53180-8fcb-11eb-8779-783407197dbf.png)

Tag:

![image](https://user-images.githubusercontent.com/4013370/112751003-e2bb7080-8fcb-11eb-8b37-7cc39752c012.png)

**Comment by dragonmacher** [comment]
There is no way to do this at the moment.  This should be easy to implement.

**Comment by dragonmacher** [comment]
The column should have been available to that table (and others), but was not due to a programming mistake.  It has been fixed and is making its way through our process.
