### ISSUE TITLE
block.cc unused variable

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2874]
https://github.com/NationalSecurityAgency/ghidra/blob/b9e67994b1f37512be3fe4d6d429e891bc8d530e/Ghidra/Features/Decompiler/src/decompile/cpp/block.cc#L826

I'm reporting this instead of just removing it incase it is supposed to be used.

**Comment by mumbel** [comment]
fixed by 601757fb0932e041534b5894cf4b418c1b56c0ad
