### ISSUE TITLE
LaneDivide::WorkNode unused private field vn

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2875]
The private field vn in LaneDivide::WorkNode is unused. One would expect the field to be set below.
https://github.com/NationalSecurityAgency/ghidra/blob/b9e67994b1f37512be3fe4d6d429e891bc8d530e/Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc#L2022-L2027

If the field isn't needed then it should be removed. Otherwise it should at least be set here as it could be inadvertently used uninitialized somewhere down the road.

**Comment by mumbel** [comment]
fixed by 601757fb0932e041534b5894cf4b418c1b56c0ad
