### ISSUE TITLE
double.hh MultForm and LessThreeWay unused private fields

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2876]
The private fields `LessThreeWay::loslot` and `MultForm::sublo` are unused. If they aren't needed they should be removed.

**Comment by mumbel** [comment]
fixed by 601757fb0932e041534b5894cf4b418c1b56c0ad

**Comment by astrelsky** [comment]
@mumbel Thank you! I was looking for these when I saw the commit yesterday but couldn't find them.
