### ISSUE TITLE
Ghidra with jdk16

### ISSUE THREAD

**Issue by xunforce** [NationalSecurityAgency/ghidra#2879]
When l use adoptopenjdk16 ,it doesn't works,but on jdk15 ,it works well 
Just like this
![IMG_20210330_135637](https://user-images.githubusercontent.com/24850363/112941518-4dea7b80-9161-11eb-83e8-2a79df340f59.jpg)

**Comment by Elhamshry** [comment]
same problem

**Comment by ryanmkurtz** [comment]
In your `support/launch.properties` file, uncomment the setting of this property:

```
# The ContinuesInterceptor allows the import process to proceed if parsing corrupted headers
# generates uncaught exceptions.  Disabling it can be helpful when trying to debug what went
# wrong because the ContinuesIntercepter affects the usefulness of the stack trace.
VMARGS=-DContinuesInterceptor.disabled=true
```

It looks like something that's been deprecated for a long time now was finally removed in Java 16.

**Comment by ryanmkurtz** [comment]
What I said in my previous comment will work, but I didn't describe the problem completely.  In java 16, they changed the default value of the `--illegal-access` JVM option from `permit` to `deny` ([reference](https://bugs.openjdk.java.net/browse/JDK-8255363)).  

A better solution will be for us to not rely on the default value for this command line argument, setting out ourselves.  I recommend you add the following line to `support/launch.properties`.  It will likely be the fix we put in as well.

`VMARGS=--illegal-access=permit`

**Comment by ryanmkurtz** [comment]
In the long-term, we should prioritize removing our usage of the `cglib` library in the Loaders.  Loaders should handle parse errors more intelligently with proper exception handling.

**Comment by xunforce** [comment]
Thanks.

**Comment by wbsdty331** [comment]
Maybe we can create a link in `README.md`? such as:

---

# Troubleshooting
[For JDK 16 User](https://github.com/NationalSecurityAgency/ghidra/issues/2879)

**Comment by astrelsky** [comment]
> In the long-term, we should prioritize removing our usage of the `cglib` library in the Loaders.  Loaders should handle parse errors more intelligently with proper exception handling.

That would also be a great time to take care of #2318 too ;)

**Comment by dragonmacher** [comment]
> That would also be a great time to take care of #2318 too ;)

The people have spoken.   If you look at that ticket, there are a lot of  "thumb's up"
