### ISSUE TITLE
There is no Property Viewer Window

### ISSUE THREAD

**Issue by jstaursky** [NationalSecurityAgency/ghidra#2883]
**Describe the bug**
The Ghidra Help Docs reference a Property view and give directions to display it. There is no entry corresponding to the instructions.
![image](https://user-images.githubusercontent.com/25406664/113035439-3e6b3280-9161-11eb-8ca8-489e5e023d02.png)

Now following these instructions I see 

![image](https://user-images.githubusercontent.com/25406664/113035639-6ce90d80-9161-11eb-8228-ec40ca2ef280.png)

Which as you can see has no **Manage Properties** entry

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Java Version: openjdk 11.0.10 
 - Ghidra Version: 9.2.2
 - Ghidra Origin: official ghidra-sre.org

**Comment by dragonmacher** [comment]
This view is provided by a plugin that is not enabled by default.   You can enable this plugin via the Configure dialog:
- From the menu bar, File -> Configure...
- Under 'Ghidra Core' click 'configure'
- Find the `PropertyManagerPlugin` in the table and select its checkbox

The view should now be in the Window menu.

**Comment by jstaursky** [comment]
`PropertyManagerPlugin` is under 'experimental' rather than 'Ghidra Core' (at least in my case) thanks.
