### ISSUE TITLE
CParser documentation incorrectly states CParser will use archive files for undefined types

### ISSUE THREAD

**Issue by therealchjones** [NationalSecurityAgency/ghidra#2885]
The help file notes:

https://github.com/NationalSecurityAgency/ghidra/blob/2b08598dbabe6a9c911e712bd928e5f84fb00ee8/Ghidra/Features/Base/src/main/help/help/topics/CParserPlugin/CParser.htm#L155-L156

However, @emteere notes in https://github.com/NationalSecurityAgency/ghidra/issues/716#issuecomment-505419863:
> Currently parsing doesn't pull the types from the already open archives until the header files are all parsed. Then a reconciliation of equivalent types is done on the newly parsed data types.

and #716 provides an example and workaround. Am I interpreting this correctly as an error in documentation? (At least, that is, unless the suggestion from @emteere in that issue is implemented?) Happy to submit a simple documentation PR if others agree.

**Comment by astrelsky** [comment]
Parsing headers would get a lot easier if you could just use the generic c lib archives for the types in standard headers.

**Comment by therealchjones** [comment]
Yes, that’s true, that’s what @emteere suggested in #716, and that would be a useful addition. In the meantime, it seems that’s what is stated in the help document without being what actually happens. I’m recommending starting by fixing the documentation rather than waiting for that to be implemented. If others think that’s reasonable, I’m happy to edit and submit a PR.

**Comment by ljrk0** [comment]
I think a PR to update the documentation would be really helpful, right now it's very misleading (and did cost me quite some time...)

**Comment by emteere** [comment]
This will be addressed in an upcoming branch to be pushed to master.
