### ISSUE TITLE
Global pointer array

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#2890]
I have a pointer to an array of pointers in .data

I initially assigned the type `pointer` to the array pointer, then realized it was an array and tried assigning `pointer *`.  This resulted in `addr **` in the mnemonic view and if I open the retype window it is `pointer * *`.  If I retype to `pointer *` or even `pointer`  it just keeps adding more `*` (ie `pointer * * * * * * *`).  I have to clear first to reassign `pointer` or `pointer *` in this case.

Ubuntu 18.04 / 11.0.10 / master

**Comment by astrelsky** [comment]
This is the result of the pointer boolean parameter in `DataUtils.createData`. I forget the name of the parameter.

**Comment by Danil6969** [comment]
Just undefine datatype of bytes with clear action ("C" key by default) and enter the desired datatype using retype action at the beginning of array.

**Comment by mumbel** [comment]
@Danil6969  I said that in my post

**Comment by mumbel** [comment]
Wasn't able to repro with master.  This appears to be fix as of d0a8291e93741aec29fb3727985be12984baab9b at least
