### ISSUE TITLE
ghidra不能识别中文

### ISSUE THREAD

**Issue by xunforce** [NationalSecurityAgency/ghidra#2893]
![IMG_20210402_164114](https://user-images.githubusercontent.com/24850363/113399140-4b428d00-93d2-11eb-9bf6-c291ddd991b9.jpg)

**Comment by xunforce** [comment]
Thanks,ghidra can not recognize chinese.

**Comment by xunforce** [comment]
Thanks,I mean ghidra can not recognize chinese.

**Comment by dev747368** [comment]
The character set can be manually set on a string, assuming the string has been defined.  Once the correct character set is choosen, the string should display correctly as long as the font has those characters defined.

Right click on a string, Data -> Settings -> Charset.
