### ISSUE TITLE
Import the actual source code to GitHub, including build instructions

### ISSUE THREAD

**Issue by cblichmann** [NationalSecurityAgency/ghidra#29]
**Is your feature request related to a problem? Please describe.**
With the code drop on ghidra-sre.org, there is no obvious way to build Ghidra from source.

**Describe the solution you'd like**

- Judging from the plugin examples, Ghidra uses Gradle, so it'd be cool to have the Gradle project on GitHub.
- Upload the actual source code to GitHub, not just `*-src.zip` next to the `*.jar` files
- Update the README with build instructions and a quick start

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nneonneo** [comment]
> This repository is a placeholder for the full open source release. Be assured efforts are under way to make the software available here. In the meantime, enjoy using Ghidra on your SRE efforts, developing your own scripts and plugins, and perusing the over a million lines of Java and Sleigh code released within the initial public release. The release can be downloaded from our project homepage. Please consider taking a look at our contributor guide to see how you can participate in this open source project when it becomes available.

Sounds like they're working on it. Note that one of the big pieces yet unrevealed is the source code for the decompiler.

**Comment by cblichmann** [comment]
Having a tracking bug seems like a good idea anyways. I'm glad they do this at all, I can't imagine the bureaucratic hurdles one has to jump through to make this happen.

**Comment by Escapingbug** [comment]
Will the decompiler be open source eventually?

**Comment by nsadeveloper789** [comment]
Per our FAQ, we are working diligently toward releasing the source repo. In the meantime, we're happy to have released the binary build with the Sleigh and Java source.

**Comment by Adubbz** [comment]
Do you have a rough timeframe as to when that may be? Are we looking at weeks or months do you think?

**Comment by ryanmkurtz** [comment]
The full source code is now available!

**Comment by rolandh** [comment]
Are there build instructions anywhere?

**Comment by kant2002** [comment]
@rolandh https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md

**Comment by rolandh** [comment]
```
task CheckToolChain {
	// Native C/Cpp plugins will trigger failure if no tool chain found
	doFirst {
		if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
		
			project.ext.VISUAL_STUDIO_INSTALL_DIR = project.ext.VISUAL_STUDIO_BASE_DIR + "\\Preview"
```

The code above in nativeBuildProperties.gradle should also check for 
Enterprise
Preview

and also check for VS2019

**Comment by kant2002** [comment]
See discussion in
https://github.com/NationalSecurityAgency/ghidra/pull/730 regarding VS
support
