### ISSUE TITLE
Function call stack operations showing as discrete statements in decompilation with custom SLEIGH processor

### ISSUE THREAD

**Issue by GMMan** [NationalSecurityAgency/ghidra#2900]
I am currently working on improving a SLEIGH processor for GeneralPlus µ'nSP, found [here](https://github.com/GMMan/sleigh-unsp/tree/discrete-registers). Currently I'm running into a problem where the PC and SR push that occurs in a call instruction are being shown as discrete operations rather than being part of the function call.

Ghidra version 9.2.1 public

### Background
µ'nSP has a 22-bit address space, of which there is a 16-bit program counter (PC), and a 6-bit code segment (CS) inside a 16-bit status register (SR). The original processor code used bitranges to index the CS and other fields within the SR, which produced a lot of extraneous decompilation output showing updates to the SR as discrete operations. I took a page from the ARM SLEIGH processor and separated out the SR fields into separate registers, only packing and unpacking it if it's accessed.

The stack of µ'nSP is limited to segment 0. The stack is a bit odd in that the stack pointer (SP) points to the next unused stack address rather than the last used stack address. When making a function call, it will push the next PC and the SR on to the stack, and when returning SR and PC are popped from the stack. Here's a diagram from their compiler manual:

![image](https://user-images.githubusercontent.com/2154355/113609039-84fcd900-9608-11eb-8a95-0c33e9fcf977.png)

The compiler pushes arguments by first decrementing SP by the number of arguments, then storing the arguments relative to SP. After the call returns, SP is incremented.

### Problem
Ghidra's decompilation sees the stack allocation and argument assignment as regular memory writes, then inserts the two pushes, before showing the function call, with zero arguments by default. If the arguments are locked in, it'll show the arguments as being read from memory rather than the actual associated values.

![image](https://user-images.githubusercontent.com/2154355/113609518-208e4980-9609-11eb-9e0e-222345acc3b7.png)

Here's the PCode for the call:

![image](https://user-images.githubusercontent.com/2154355/113609605-3996fa80-9609-11eb-9d1f-e8baf3f12d53.png)

The first bunch of lines until SR assignment is just packing SR from the individually separated fields. Even if I don't pack SR, I still get the two pushes as discrete operations. I also checked the push macro, it looks pretty much like x86-16's `push22()` ~~except decrements stack pointer after writing value instead of before~~ I'm decrementing first and writing after in the screenshot, same effect.

So what am I doing wrong here?

**Comment by astrelsky** [comment]
The way for compensating for this is in the prototype definition in the `.cspec` files. There are `extrapop` and another parameter used for this behavior.

**Comment by GMMan** [comment]
I have it set to the following:

```xml
<prototype name="__cdecl" extrapop="0" stackshift="4">
```

If I'm understanding correctly, it should ignore the two 16-bit words pushed to the stack, and on return, the same two words are popped back without any additional pops. Does `extrapop` refer specifically to all of the operations performed by the return and `stackshift` is not included as a part of that?

**Comment by GMMan** [comment]
OK I got it, I have it set as the following.

```xml
<prototype name="__cdecl" extrapop="2" stackshift="2">
```

Units are in the same units as stack pointer, so since the address spaces consists of words rather than bytes, 2 is the correct value. `extrapop` is for return, `stackshift` is for call, and they are separate. Still getting extraneous output when packing SR, but that's a different issue that I'll have to dig into more.

**Comment by astrelsky** [comment]
Good luck. Things are currently a real pain when dealing with different sized pointers.

I've found that sometimes it is easier to loosely model a processor as opposed to modeling it as exactly as possible. It may produce better results if you don't pack/unpack them and use separate "fake" registers for them. You could also try ignoring the pack/unpack if it can't possibly change as a result of the call. If it can't then modeling it in sleigh just produces noise that the decompiler has to deal with.

**Comment by GMMan** [comment]
Yeah, for readability currently I've just omitted packing before calling and it seems to look alright. Only concern is if the code touches the stored SR on the stack for some reason, though so far I've only seen that done with switch tables by pushing an address and returning, but that's not a function call so should be OK.
