### ISSUE TITLE
Ghidra isnt showing other formats to choose from

### ISSUE THREAD

**Issue by Kazuto455** [NationalSecurityAgency/ghidra#2904]
I just got ghidra a couple days ago and haven't been able to use it for a single thing. I have done lots of youtube tutorials, documentation reading, and google searches to find a solution to this problem. From day one ghidra has only allowed me to choose the Raw Binary format when importing a file. I would like to import a .exe but no matter which one I choose I only get the Raw Binary option. After selecting Raw Binary and my language I always get exactly 2 "Error in plugin event listener" pop ups (I can post the details if asked) then a result summary that basically says nothing has been found. No instructions, defined data, functions, symbols, or data types. I have downloaded straight from the official website multiple times. I've tried earlier versions. I've also seen videos where an analysis window pops (I've never seen that on mine). I would love some help in fixing these issues. Thank you.

**Comment by ryanmkurtz** [comment]
This is most likely due to Ghidra not fully supporting Java 16 yet.  You'll just need to add

```
VMARGS=--illegal-access=permit
```

to your `support/launch.properties` file.

**Comment by vitecd** [comment]
I still can not choose any Format other than "Raw Binary". Why?

**Comment by vitecd** [comment]
It was my fault in the Loader code. Fixed.
