### ISSUE TITLE
Tag latest build of Ghidra as latest in Github

### ISSUE THREAD

**Issue by bennyamcc** [NationalSecurityAgency/ghidra#2905]
We are looking at using Ghidra in a CI/CD pipeline and would love the ability to pull the latest build using the Github latest tag, not the string Ghidra<version> build.

**Comment by ryanmkurtz** [comment]
Checking out the `stable` branch should get you exactly what you need.

**Comment by ryanmkurtz** [comment]
Closing issue. We can reopen if the `stable` branch won't work for you for some reason.
