### ISSUE TITLE
ARM A32/T32 strb.w ldrb.w data acces size of undefined1 somtimes, undefined2 others times

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2907]
**1.  DAT_c28f9080** 
strb.w  ldrb.w are marking the data as undefined1
![image](https://user-images.githubusercontent.com/4013370/113871080-d3e67200-97b2-11eb-9fe4-e0d6e2717af3.png)
![image](https://user-images.githubusercontent.com/4013370/113871595-5bcc7c00-97b3-11eb-9b81-60f353a5e272.png)

**2. DAT_c34eb5aa** 
ldrh.w access data as undefined2

![image](https://user-images.githubusercontent.com/4013370/113872117-df866880-97b3-11eb-8105-29a9b5adff34.png)

any idea why the size mismatch btw the two data ?

**Comment by mumbel** [comment]
Maybe I'm missing something, but as opposed to?  

strb.w and ldrb.w are 1 byte operations which ghidra will default to undefined1, and strh.w and ldrh.w are 2 byte operations which ghidra will default to undefined2.  

Are you getting confused by the `.w` maybe?  That just allows high registers (note the thumb instruction but 4 byte decoding)

**Comment by pabx06** [comment]
> Maybe I'm missing something, but as opposed to?
> 
> strb.w and ldrb.w are 1 byte operations which ghidra will default to undefined1, and strh.w and ldrh.w are 2 byte operations which ghidra will default to undefined2.
> 
> Are you getting confused by the `.w` maybe? That just allows high registers (note the thumb instruction but 4 byte decoding)

my mistake b for byte and h for half word. and w for word size addr encoding. kinda mixed it all up together with lack of sleep.
thanks mumbel.
