### ISSUE TITLE
[Decompiler]Low-level Error: Shared type id

### ISSUE THREAD

**Issue by homes410** [NationalSecurityAgency/ghidra#2909]
Please take a look at the attachment. These two type doesn't have same type id. 

**To Reproduce**
1. download [stdin.gz](https://github.com/NationalSecurityAgency/ghidra/files/6274104/stdin.gz)
2. gzip -d -c "stdin.gz"|decompiler
3. Low-level Error: Shared type id: 8000000000000ea

**Screenshots**
If applicable, add screenshots to help explain your [problem.](url)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - Ghidra Version: 9.2.2

**Additional context**

**Comment by homes410** [comment]
Please feel free to apply this kludge.

[0001-a-kludge.patch.txt](https://github.com/NationalSecurityAgency/ghidra/files/6287206/0001-a-kludge.patch.txt)

Below are changes involved.
Thanks.

Ghidra/Features/Decompiler/src/decompile/cpp/type.cc : (TypeEnum::compareDependency) Fix Enum type comparison.
 (TypeCode::restoreXml) Mark flags before base method is called.

**Comment by caheckman** [comment]
Reproducing the error.  Thank you for the report.
