### ISSUE TITLE
ghidra 9.2.3  crash on arm64

### ISSUE THREAD

**Issue by ddkwork** [NationalSecurityAgency/ghidra#2910]
![Screenshot_20210408_090120_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/113952990-65a0be80-9849-11eb-806d-dc19572a0c2c.jpg)
![Screenshot_20210408_090812_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/113953269-042d1f80-984a-11eb-80ba-f3a15eb45332.jpg)

Os: manjaro linux arm64 on android10 mobile phone installed by termux

**Comment by fjh1997** [comment]
9.2.2 didn't support arm64,please consider 9.2.3.
See here:#2644

**Comment by DiskGetor** [comment]
> 9.2.2不支持arm64（请考虑9.2.3.
> 看看这里：#2644

How to build ghidra 9.2.3 use clion or idea?thank you.

**Comment by ryanmkurtz** [comment]
Check out the [DevGuide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md).  To general steps to produce a build are:
```
git clone git@github.com:NationalSecurityAgency/ghidra.git
cd ghidra
gradle --init-script gradle/support/fetchDependencies.gradle init
gradle buildGhidra
```
The build will be in build/dist/.

**Comment by fjh1997** [comment]
> > 9.2.2不支持arm64（请考虑9.2.3.
> > 看看这里：#2644
> 
> How to build ghidra 9.2.3 use clion or idea?thank you.

I's recommend to build using the command line, see guides above.

**Comment by DiskGetor** [comment]
> Check out the [DevGuide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md). To general steps to produce a build are:
> 
> ```
> git clone git@github.com:NationalSecurityAgency/ghidra.git
> cd ghidra
> gradle --init-script gradle/support/fetchDependencies.gradle init
> gradle buildGhidra
> ```
> 
> The build will be in build/dist/.

Thank you,i will try.

**Comment by DiskGetor** [comment]
> 检查出 [DevGuide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md). 一般的步骤，以产生一个建设是：
> 
> ```
> git clone git@github.com:NationalSecurityAgency/ghidra.git
> cd ghidra
> gradle --init-script gradle/support/fetchDependencies.gradle init
> gradle buildGhidra
> ```
> 
> 该建设将是在建立/dist/.

i can not install gradle on arm64, can you build it for me,thank you.

**Comment by fjh1997** [comment]
> > 检查出 [DevGuide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md). 一般的步骤，以产生一个建设是：
> > ```
> > git clone git@github.com:NationalSecurityAgency/ghidra.git
> > cd ghidra
> > gradle --init-script gradle/support/fetchDependencies.gradle init
> > gradle buildGhidra
> > ```
> > 
> > 
> > 该建设将是在建立/dist/.
> 
> i can not install gradle on arm64, can you build it for me,thank you.

Do you know cross-build？ It's not necessary to build on arm64. You could also build on x86.

**Comment by DiskGetor** [comment]
> > > 限 [DevGuide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md). 一般的步骤，以产生一个建设是：
> > > ```
> > > git clone git@github.com:NationalSecurityAgency/ghidra.git
> > > cd ghidra
> > > gradle --init-script gradle/support/fetchDependencies.gradle init
> > > gradle buildGhidra
> > > ```
> > > 
> > > 
> > > 该建设将是在建立/dist/.
> > 
> > 
> > 我不能安装摇篮上arm64（你可以建立它对我来说，谢谢你。
> 
> 你知道跨建立？ 这是没有必要建立在arm64（. 你也可以建立在x86。
> PS:不要尝试是免费的车手，否则你会学到什么。


Uploading SVID_20210415_105011_1.mp4…

**Comment by ryanmkurtz** [comment]
My takeaway from your video is that our decompilers built for x86_64 Linux, Windows, and macOS platforms will not run on your arm64 Linux platform, which is the expected behavior. I suggest that we add some checks so we don't even try to run the native binaries on an unsupported architecture/platform, and report a more friendly error message.
