### ISSUE TITLE
 Decompiler: Unable to initialize the DecompilerInterface: Broken pipe

### ISSUE THREAD

**Issue by FlameFury20** [NationalSecurityAgency/ghidra#2912]
**Describe the bug**
I am trying to decompile a simple c++ hello world exe file and the decompiler would give me the following error: "Decompiler: Unable to initialize the DecompilerInterface: Decompiler process died"

**To Reproduce**
1. Open the code borwser on a c++ exe file
2. Analyze the file
3. Try to decompile the main function
4. You should get the error in the decompiler tab

**Expected behavior**
Decompile the code normaly

**Screenshots**
![code](https://user-images.githubusercontent.com/45979391/114026180-9f3fec80-987e-11eb-9204-40a5b52d7563.png)
![ghidra](https://user-images.githubusercontent.com/45979391/114027570-2cd00c00-9880-11eb-897f-f1ba2bfa15a9.png)

**Attachments**
Github would not let me upload any .exe or .cpp files

**Environment (please complete the following information):**
 - OS: Linux kali 4.19.127-Re4son-v8l+ #1 SMP PREEMPT  aarch64 GNU/Linux
 - Java Version: openjdk version "11.0.11-ea" 2021-04-20
 - Ghidra Version: 9.2.2
 - Ghidra Origin: ghidra-sre.org

**Additional context**

**Comment by ryanmkurtz** [comment]
Similar to #2910

**Comment by FlameFury20** [comment]
Tried the solution in #2910 and got this:
FAILURE: Build failed with an exception.                                   
                                                                           
* Where:                                                                   
Build file '/home/thek0der/ghidra/ghidra/build.gradle' line: 306           
                                                                           
* What went wrong:                                                         
A problem occurred evaluating script.                                      
> Unrecognized current platform -> osName = Linux, archName = aarch64      
                                                                           
* Try:                                                                     
Run with --stacktrace option to get the stack trace. Run with --info or --d
ebug option to get more log output. Run with --scan to get full insights.  
                                                                          
* Get more help at https://help.gradle.org * 

BUILD FAILED in 3s
