### ISSUE TITLE
Unable to open project file (java.io.EOFException)

### ISSUE THREAD

**Issue by HJfod** [NationalSecurityAgency/ghidra#2913]
**Describe the bug**
For some reason, when I tried to open a file I had worked on reverse engineering before, I got greeted by a `java.io.EOFException`. This has happened to me before with different files, and back then I just decompiled the file again as I didn't have many changes done to it, but this reverse engineering project is something I've worked on for months and would really prefer to not lose all that work.

I've tried updating my JDK but that didn't help. I'll be happy to provide any extra info you need.

**To Reproduce**
I am not sure how to reproduce this. It has happened on seemingly random occasions to multiple files.

**Expected behavior**
What I expected is for the project to load normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/60038575/114062506-21341380-9887-11eb-9665-0e9e143cebcf.png)

I have [ghidra-dark](https://github.com/zackelia/ghidra-dark) installed, but I believe that to not be the issue as I got this problem with a different file before.

**Attachments**
Log file
[error.txt](https://github.com/NationalSecurityAgency/ghidra/files/6280075/error.txt)

**Environment**
 - OS: Windows 10 19042.867
 - Java Version: 16
 - Ghidra Version: 9.2.2
 - Ghidra Origin: Official ghidra-sre.org distro

**Comment by dev747368** [comment]
Looking at the stack trace, Ghidra is having a problem reading the database files that used to store your work.

Ghidra is very forgiving when it comes to being shut down / terminated unexpectedly and can usually just recover or rollback to the last good state.  However, it seems the database files got truncated or corrupted in some manner.  Did you have any OS or hardware issues?  

On a side note, you listed java16 as your java version.  From reports of other users this will cause issues running Ghidra.  (probably not your issue though)

**Comment by HJfod** [comment]
I shouldn't have any OS or hardware issues, although now that you mention it, on bootup Windows often wants to "fix" my F: drive which is where my Ghidra projects are located. I don't know why Windows wants to try to fix it, I've never noticed anything wrong with it, but it might be that which is causing the issue. I'll try moving my projects away to a different drive and see if the issue appears again.

Can you think of a way I could recover data from the project that got corrupted? Doing all of the RE work again would be one pain

**Comment by dev747368** [comment]
I don't have any suggestions other than using backup software to protect against this type of issue, especially if your OS is marking your file system as damaged.

You can also manually export a ghidra project or a single program to a file to make manual 'backups'.

**Comment by HJfod** [comment]
Alright, thank you for the help :)
