### ISSUE TITLE
Ghidra cannot locate root dir when special chars like "&" are used in path name.

### ISSUE THREAD

**Issue by KleinByte** [NationalSecurityAgency/ghidra#2914]
**Describe the bug**
On Windows, Ghidra cannot parse a path that has special characters in the file path, e.g. "&". 
These characters are somehow breaking the file path and Ghidra only sees whats directly after the
special character. 

ex: My path "C:\Users\Klein\Dev\etc\R&D\Reverse_Engineer\ghidra_9.2.2_PUBLIC_20201229"
     gets sent to Ghidra as "D\Reverse_Engineer\ghidra_9.2.2_PUBLIC_20201229" , which breaks the init obviously. 

**To Reproduce**
1.  Put a legal special character in Ghidra's file path.
2.  Run GhidraRun.bat
3.  Ghidra never makes it to . /support folder to init launch-helper script.
4. See error.

**Expected behavior**
The expected behavior should be more robust when handling file paths. Although the easy fix is to not put special characters in your file path, more problems could arise down the road due to this issue. New users may also get frustrated with the errors as they don't describe the problem accurately.

**Screenshots**
![image](https://user-images.githubusercontent.com/57239407/114099979-2c049d80-98b3-11eb-83da-a5dab8b0e230.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows10
 - Java Version: [AWS 11.0]
 - Ghidra Version: [e.g. 9.2.2]
 - Ghidra Origin: [official ghidra PUBLIC] 

**Additional context**
Pretty simple bug, hopefully, it's not clogging the issue backlog. New to open-source bug reports.

**Comment by ryanmkurtz** [comment]
I don't have the issue #'s handy, but the ampersand issue has been fixed in the master branch.

**Comment by KleinByte** [comment]
+1
