### ISSUE TITLE
CONCAT, SUB, ZEXT

### ISSUE THREAD

**Issue by DiskGetor** [NationalSecurityAgency/ghidra#2916]
Hello,what is CONCAT, SUB, ZEXT, you can found them in __aulldiv func from msvc2003 lib

**Comment by EuanKirkhope** [comment]
this is assembly code that has no c equivalent.  

Ghidra Functionality > Decompiler > Internal Decompiler Functions

CONCAT31(x,y) - Concatenation operator - PIECE
The digit '3' indicates the size of the input operand 'x' in bytes.
The digit '1' indicates the size of the input operand 'y' in bytes.
The parameters 'x' and 'y' hold the values being concatenated.
	    CONCAT31(0xaabbcc,0xdd) = 0xaabbccdd 
	  
Concatenate the bytes in 'x' with the bytes in 'y'. 'x' becomes the most significant bytes, and 'y' the least significant bytes, in the result.

SUB41(x,c) - Truncation operation - SUBPIECE
The digit '4' indicates the size of the input operand 'x' in bytes.
The digit '1' indicates the size of the output value in bytes.
The parameter 'x' is the value being truncated.
The parameter 'c' is the number of least significant bytes being truncated.
	    SUB42(0xaabbccdd,1) = 0xbbcc

ZEXT14(x) - Zero-extension operator - INT_ZEXT
The digit '1' indicates the size of the input operand 'x' in bytes.
The digit '4' indicates the size of the output in bytes.
	    ZEXT24(0xaabb) = 0x0000aabb
	  
Extend the operand 'x' to a larger size by appending zero bytes, which become the most significant bytes of the result.

https://www.reddit.com/r/ghidra/comments/bjc782/concat_instructions_noob_question_please_dont_eat/

**Comment by ddkwork** [comment]
I found the aulldiv mul ctx fun  don't save edx value, the bug found from x64dbg
