### ISSUE TITLE
Context Dependent Decoding of Jump Instructions

### ISSUE THREAD

**Issue by chezwicker** [NationalSecurityAgency/ghidra#2918]
**Is your feature request related to a problem? Please describe.**

*Ghidra* decodes `0F 84` as `JZ` following a comparison with a non-zero value.

![image](https://user-images.githubusercontent.com/10724464/114182542-058e4300-9943-11eb-97e6-7f6718812537.png)

**Describe the solution you'd like**

Wouldn't it be nicer to decode as `JE`?

**Environment**

OS: Windows 10 10.0 amd64 (VM)
Java Version: AdoptOpenJDK 11.0.10
Ghidra Version: 9.3 DEV, commit b69c3d6
Ghidra Origin: locally built

**Comment by homes410** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/35d84d5ebde78872ddc309d51ce410ee37c8c0a7/Ghidra/Processors/x86/data/languages/ia.sinc#L2827-L2830

At least you can help ghidra decode an instruction better by further restricting those `if (cc)' in action part of sleigh specification of x86 processor.

:J^cc rel8      is vexMode=0 & row=7 & cc; rel8                                       { if ((cc&1)) goto rel8; }
:J^cc rel16     is vexMode=0 & bit64=0 & opsize=0 & byte=0xf; row=8 & cc; rel16       { if ((cc&1)) goto rel16; }
:J^cc rel32     is vexMode=0 & opsize=1 & byte=0xf; row=8 & cc; rel32                 { if ((cc&1)) goto rel32; }
:J^cc rel32     is vexMode=0 & opsize=2 & byte=0xf; row=8 & cc; rel32                 { if ((cc&1)) goto rel32; }

It will give you lesser # of if statement in decompiler output.

**Comment by homes410** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/35d84d5ebde78872ddc309d51ce410ee37c8c0a7/Ghidra/Processors/x86/data/languages/ia.sinc#L2827-L2830

At least you can help ghidra decode an instruction better by further restricting those `if (cc)' in action part of sleigh specification of x86 processor.

```
:J^cc rel8      is vexMode=0 & row=7 & cc & ccfailedtobranch; rel8                                       { if (cc) goto rel8; build ccfailedtobranch; }
:J^cc rel16     is vexMode=0 & bit64=0 & opsize=0 & byte=0xf; row=8 & cc & ccfailedtobranch; rel16       { if (cc) goto rel16; build ccfailedtobranch; }
:J^cc rel32     is vexMode=0 & opsize=1 & byte=0xf; row=8 & cc & ccfailedtobranch; rel32                 { if (cc) goto rel32; build ccfailedtobranch; }
:J^cc rel32     is vexMode=0 & opsize=2 & byte=0xf; row=8 & cc & ccfailedtobranch; rel32                 { if (cc) goto rel32; build ccfailedtobranch; }
```

condition of `ccfailedtobranch` is same as `cc` but you can inject pcode to improve analysis of instruction, or not.

**Comment by homes410** [comment]
The above modification of specification creates 'materialized predicate` for both branch and You can reveal hidden semantics without headache in SSA-like IR with label.
Depending on the project you are working on, you need to materialize condition of another pcode that did cause altered eflags.
More revealed semantics, More deobfuscated code.
