### ISSUE TITLE
I can't get ghidra to find JDK

### ISSUE THREAD

**Issue by Hardeitor** [NationalSecurityAgency/ghidra#2919]
Sorry in advance for any potential misspelings.

So i am trying to get ghidra to run for the first time but it just says "Failed to find a supported JDK" and quits. I tried adding to PATH in multiple ways (the home folder, the bin, just ignoring windows config and doing it throug the command prompt) but it still fails to find the proper JDK version.
![2021-04-10-03-51-33](https://user-images.githubusercontent.com/82256385/114261279-1759ff80-99b0-11eb-83ee-4edac78fd1a3.png)

For clarification 
Windows 10 64bit
I believe JDK 16 is the installed version so i am trying to get ghidra to reconize the OpenJDK 11 or the Amazon Corretto 11
How the current PATH looks like
![2021-04-10-03-53-19](https://user-images.githubusercontent.com/82256385/114261450-0c539f00-99b1-11eb-815d-37650a67e4c6.png)

**Comment by Wall-AF** [comment]
Take a look at https://github.com/NationalSecurityAgency/ghidra/issues/2718.

Meanwhile:
1. Ensure you `JAVA_HOME` is set correctly
2. Check your `PATH`
3. Run `java -version` and check those results.

**Comment by Hardeitor** [comment]
I got it working, after i discovered that Windows dosen't naturaly create a JAVA_HOME i tryed creating one and it still didn't work, then i figured that it was indeed version 16 and i tryed using the installer for the amazon corretto and ading that to JAVA_HOME and it managed to run
![](https://i.imgur.com/4bMkmCx.png)

Since i had downloaded the .zip files for the JDK 11 it might have had something to do with the unziping but either way its working now thanks
