### ISSUE TITLE
Import IDA database

### ISSUE THREAD

**Issue by martmists-gh** [NationalSecurityAgency/ghidra#2921]
**Is your feature request related to a problem? Please describe.**
I'm continuing some work on projects that have long been abandoned by the original authors, and while they used IDA, I simply don't have the $2k to get IDA Pro, so I cannot use the supplied XML Exporter (as the project uses a non-x86 architecture)

**Describe the solution you'd like**
Add a way to import .idb files in ghidra.

**Describe alternatives you've considered**
The only other alternative is to purchase IDA Pro just to export to Ghidra, which would cost me a quarter of my savings and should not be considered a good solution.

**Comment by aerosoul94** [comment]
I don't think they're going to add an entire IDA database loader. IDA uses a proprietary format for their databases that changes from time to time. You could try using this:
https://github.com/williballenthin/python-idb

You'd have to write a script using that library that generates the xml that can be imported into ghidra.

**Comment by ryanmkurtz** [comment]
Supporting the `.idb` format is outside of the scope of the Ghidra project.

**Comment by non-bin** [comment]
@ryanmkurtz did you ever get this working?

**Comment by ryanmkurtz** [comment]
No, we still have no plans to support this.
