### ISSUE TITLE
Is Ghidra Supposed to Support OpenJDK 16?

### ISSUE THREAD

**Issue by larkwiot** [NationalSecurityAgency/ghidra#2933]
I'm not sure if Ghidra is supposed to support OpenJDK 16 or not. Currently, it explodes when running under JDK 16. If it supposed to support it, then this is a massive bug stemming from the use of sun.awt.image.SurfaceManager, which is an internal object of the JDK not meant to be touched by an application. JDK 16 is worth supporting because it brings major performance upgrades due to C++14 usage and proper use of SIMD instructions in the JVM.

**Comment by ryanmkurtz** [comment]
Ghidra is only supposed to support JDK 11 LTS.  However, we do our best to support the later non-LTS versions for convenience. To get Ghidra working under JDK 16, add the following line to your `support/launch.properties` file:

`VMARGS=--illegal-access=permit`

I haven't seen any issues with `sun.awt.image.SurfaceManager`.  Did you experience an error regarding this?

**Comment by larkwiot** [comment]
Ah, so the error I got is about illegal accesses to the class "sun/awt/image/SurfaceManager" and the GUI malfunctions as a result. Your VMARGS addition works though, so thank you!
