### ISSUE TITLE
Equate vs symbol

### ISSUE THREAD

**Issue by jstaursky** [NationalSecurityAgency/ghidra#2939]
What is the difference between an equate and a symbol?

the docs say 
```
An Equate is a string substitution for scalar (a numeric value) in any code unit (instruction operand or data).
```
and 
```
A Symbol is an association between an Address, a String name.
```

This sounds like an equate is the same as a symbols label. Or maybe I am just confused.

**Comment by dragonmacher** [comment]
An equate is an alternate name that maps to a scalar *value*.   A symbol maps to an address.    Scalar values are literal numbers, whereas an address is a location.    If you map BOB to the value of 1, then bob can be used anywhere you see a value of 1.   If you add a symbol to an address, that symbol will appear only at that address.

**Comment by jstaursky** [comment]
I think I get it, equate is sort of like using an `enum` in like C-lang then?

**Comment by dragonmacher** [comment]
Sure.   In Ghidra it is a convenient way to make numbers more readable.

**Comment by jstaursky** [comment]
I'll accept that, thanks
