### ISSUE TITLE
Build failure if followed the new manual download instructions

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#2940]
**Describe the bug**
There is some discrepancy between what `fetchDependencies.gradle` does and what the [manual download instructions](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md#manual-download-instructions) tell people to do. The build script expects to find files where `fetchDependencies.gradle` saved. The build fails if I follow the manual download instructions.

The discrepancies are:
1. `fetchDependencies.gradle` saves `yajsw-stable-12.12.zip` to `${REPO_DIR}/dependencies/GhidraServer`, while the manual download saves this file to `${REPO_DIR}/dependencies`
1. `fetchDependencies.gradle` saves `PyDev 6.3.1.zip` to `${REPO_DIR}/dependencies/GhidraDev`, while the manual download saves this file to `${REPO_DIR}/dependencies`
1. `fetchDependencies.gradle` saves `cdt-8.6.0.zip` to `${REPO_DIR}/dependencies/GhidraDev`, while the manual download saves this file to `${REPO_DIR}/dependencies`
1. The manual download instructions lack the step to download .fidb files from ghidra-data and save them under `${REPO_DIR}/dependencies/fidb`

**Comment by ryanmkurtz** [comment]
Thanks, I've followed your PR commit with these fixes.
