### ISSUE TITLE
LLVM/Clang for Windows support

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2942]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to build Ghidra on windows without a visual studio ide installed. Having only the Visual Studio 2019 Build Tools and LLVM doesn't work. 

**Describe the solution you'd like**
If a C++ compiler is available or should be used.

**Describe alternatives you've considered**
Install a garbage visual studio ide that just takes up space and is never used.

**Comment by Danil6969** [comment]
You could use MSYS2 as a unix shell and terminal with mingw and install gcc or clang with gdb (if you need the latter) using ``pacman`` command. Then you just use the ``g++.exe`` or ``clang++.exe`` file downloaded by ``pacman``. Also define macros for windows as [here](https://github.com/Danil6969/ghidra/blob/37a7bd21675421d61202a05f9be12c787d95e5ab/Ghidra/Features/Decompiler/build.gradle#L545) and [here](https://github.com/Danil6969/ghidra/blob/37a7bd21675421d61202a05f9be12c787d95e5ab/Ghidra/Features/Decompiler/build.gradle#L585).

**Comment by astrelsky** [comment]
> You could use MSYS2 as a unix shell and terminal with mingw and install gcc or clang with gdb (if you need the latter) using ``pacman`` command. Then you just use the ``g++.exe`` or ``clang++.exe`` file downloaded by ``pacman``. Also define macros for windows as [here](https://github.com/Danil6969/ghidra/blob/37a7bd21675421d61202a05f9be12c787d95e5ab/Ghidra/Features/Decompiler/build.gradle#L545) and [here](https://github.com/Danil6969/ghidra/blob/37a7bd21675421d61202a05f9be12c787d95e5ab/Ghidra/Features/Decompiler/build.gradle#L585).

No, can just install llvm for windows. This is a build problem as there is no way to tell it to use clang.

**Comment by Danil6969** [comment]
You may use this ["selector"](https://github.com/Danil6969/ghidra/blob/462102d75856b003a8cee8c13fc241bbf8e712f5/GPL/nativeBuildProperties.gradle#L30).

**Comment by Danil6969** [comment]
As of "IDE" I have installed MS Build tools and the folder is also named as it contains full IDE, not just MSVC compiler while this is false and it takes much less space on HDD because of compiler only presence. Don't pay attention very much to this strange path naming scheme. Maybe it's just a historic issue because Microsoft forgot to rename to "MS-C++-compiler". I have the only folder named "BuildTools" in "C:\Program Files (x86)\Microsoft Visual Studio\2019".

**Comment by astrelsky** [comment]
> You may use this ["selector"](https://github.com/Danil6969/ghidra/blob/462102d75856b003a8cee8c13fc241bbf8e712f5/GPL/nativeBuildProperties.gradle#L30). Also replace the path to a valid one and cut out `vc(VisualCpp) {...}`. And put `if (false)` instead of `if (org.gradle.internal.os.OperatingSystem.current().isWindows())` [here](https://github.com/Danil6969/ghidra/blob/462102d75856b003a8cee8c13fc241bbf8e712f5/GPL/vsconfig.gradle#L30).

I'll give this a shot on Monday. As long as it uses the Visual Studio Build Tools and not make it should work.

**Comment by ryanmkurtz** [comment]
I'm interested in getting Ghidra to build on Windows with no admin required (so no Visual Studio).  Did you achieve this?

**Comment by astrelsky** [comment]
> I'm interested in getting Ghidra to build on Windows with no admin required (so no Visual Studio). Did you achieve this?

Yes. However, clang requires having the Visual Studio build tools so you still need admin.

**Comment by ryanmkurtz** [comment]
I'll give this setup a try.  Not needing admin would be ideal, but not having to register your visual studio after 30 days would be a win too.

**Comment by astrelsky** [comment]
> I'll give this setup a try. Not needing admin would be ideal, but not having to register your visual studio after 30 days would be a win too.

That's why I ended up going this route. It was easier to spend the time to figure this out then to jump through hoops to get a Pro license at work.

You don't need admin to create an offline install. So if you have a situation where you need to move it to an offline workstation where you do have admin rights but don't have admin rights where you can run the installer to download the layout you can still make it work.

**Comment by astrelsky** [comment]
Gradle has built in plugins for c/c++ projects. Has using them been tried? It makes more sense to me to let gradle handle it then to try to implement the logic from scratch. 

https://github.com/gradle/native-samples

**Comment by astrelsky** [comment]
@ryanmkurtz I just tried a default created c++ project using the gradle init script on a system without a visual studio ide (only the build tools). Gradle managed to build it and use the build tools without a problem. It may be more efficient to use the gradle `cpp-application` plugin instead of custom stuff.

**Comment by ryanmkurtz** [comment]
> Gradle has built in plugins for c/c++ projects. Has using them been tried? It makes more sense to me to let gradle handle it then to try to implement the logic from scratch.

What do you mean implement the logic from scratch?  Do you mean the stuff we have in there that discovers visual studio?

**Comment by astrelsky** [comment]
> > Gradle has built in plugins for c/c++ projects. Has using them been tried? It makes more sense to me to let gradle handle it then to try to implement the logic from scratch.
> 
> What do you mean implement the logic from scratch? Do you mean the stuff we have in there that discovers visual studio?

I did mean that. Is that not custom?

**Comment by ryanmkurtz** [comment]
The Gradle changes I made to support building on ARM are still making their way through the pipe.  Once the dust settles on that, I'll revisit LLM on Windows.

**Comment by ryanmkurtz** [comment]
How that Ghidra supports VS Build Tools, is this request still important?  We don't have LLVM/Clang support, but you no longer have to install the VS IDE.
