### ISSUE TITLE
Dark mode in Ghidra on Kali 2021.1 is set by swing look and feel [GTK+] have some bugs ?

### ISSUE THREAD

**Issue by masterwishx** [NationalSecurityAgency/ghidra#2945]
Hello and Thanks for great Software
im using Ghidra in Kali , founded that Dark mode can be enabled by set swing look and feel GTK+.
(is any way to set Dark mode in Windows too ?)
but having some problem:  

1. Import files ,open project (browser to open files) where to select files is white and files is white to so i cant see files !
2. Listing and Decomiler display is not changed to dark mode after changed to GTK+

will be this problem fixed in future? or maybe there is some fix or i can fix it somehow?

many peaple like to work in dark mode...
Thanks

**Comment by dragonmacher** [comment]
Related to #13 

The Inverted Colors mode is a prototype feature and is not actively being supported.

> many peaple like to work in dark mode...

Dark Mode is is one of the most requested features.   There is currently community support for accomplishing this task.   See #13 for some examples.

**Comment by masterwishx** [comment]
> Related to #13
> 
> The Inverted Colors mode is a prototype feature and is not actively being supported.
> 
> > many peaple like to work in dark mode...
> 
> Dark Mode is is one of the most requested features. There is currently community support for accomplishing this task. See #13 for some examples.

i didnt used inverted color ,only GTK+ that gives me Dark Mode ...

**Comment by dragonmacher** [comment]
I see.  I misunderstood.    The changes required to fix the issues you are seeing would be related to the changes required to solve #13 as well.    We have no plans to fix this currently.
