### ISSUE TITLE
Ghidra Gradle build tasks using `compile`, `runtime`, `testCompile`, `testRuntime` fail on Gradle +v7.0 due to being removed

### ISSUE THREAD

**Issue by GavinRay97** [NationalSecurityAgency/ghidra#2949]
**Describe the bug**
See title

**To Reproduce**
Try to compile an extension with Gradle 7

**Expected behavior**
README is modified with prominent info stating that Gradle +7 is not supported, or build scripts have deprecated syntax replaced.

(The latter may not help much, as there's obviously a dependency on third-party extensions to ensure compatibility in their scripts, too)

**Screenshots**
![image](https://user-images.githubusercontent.com/26604994/115153640-1a568f00-a045-11eb-8bd2-512de60effcc.png)

Build w/ Gradle v7.0
- ![image](https://user-images.githubusercontent.com/26604994/115153715-61dd1b00-a045-11eb-8a66-b27de8fcdffa.png)

Build w/ Gradle v6.8.3
- ![image](https://user-images.githubusercontent.com/26604994/115154571-8c30d780-a049-11eb-83c8-7c009363b765.png)

https://github.com/NationalSecurityAgency/ghidra/blob/e7488245fd3e85dea6050e0dd66bb4a4dbeeb53b/Ghidra/RuntimeScripts/Common/support/buildExtension.gradle#L50-L55

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10 Insider
 - Java Version: 15
 - Ghidra Version: 9.2.3
 - Ghidra Origin: Official

**Additional context**
Hope this is useful =)

**Comment by astrelsky** [comment]
This will be an issue in other places but may you try changing/removing the `testCompile` in the `build.gradle` for my extension and see if it builds.

**Comment by ryanmkurtz** [comment]
I've been working on Gradle 7 support.  You can expect it for the next major release.

**Comment by ryanmkurtz** [comment]
Fixed by 15d22e81643f4647fc2b985f61e44d9cdcee15da
