### ISSUE TITLE
Request:  when passing first field of struct, pass it instead of struct

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#2950]
**Is your feature request related to a problem? Please describe.**
When working with functions that have committed parameter types, when passing a struct of a different type, instead of reading the first field that does match the prototype it will cast itself.

**Describe the solution you'd like**
If the struct does not match and the first field does match a committed prototype, use the first field.

**Describe alternatives you've considered**
Its fairly obvious whats going once, just a minor annoyance, have just worked with it.

**Additional context**
There is probably a lot I'm not considering, but just wondering about committed or not.  Sometimes it will know some type information, but then lose that down the call stack, so you may lose type information if too aggressive with down casting.

```
extern void baz(int);
struct thing {
   char *name; // this is just a dummy example... maybe the real case would be some like `char name[0x20];` instead
   int x;
};
void foo2(struct thing *a)
{
    baz(a->x);
}
void foo1(struct thing *a)
{
    // from here you know that start of `thing` is a `char *`
    // but if too aggressive might decide to drop `thing` and just keep `char *`
    if (strcmp(a->name, "hello")) {
        foo2(a);
    }
}
void fooA(char *y)
{
    // from here you know that start of `thing` is a `char *`
    // y isn't used anymore, no chance of data loss from the type change
    if (strcmp(y, "world")) {
        baz(0);
    }
}
void foo0(struct thing *a)
{
    fooA(a->name); // this currently just shows as `fooA((char *)a)`
    foo1(a);
}
```

**Comment by mumbel** [comment]
@caheckman / @ghidra1    is 58558981d5988100d89e9c9f08d159fe9fdbaf13 `testStructOffset0` a fix for this (don't know if you made the rounds yet of closing tickets w/ the most recent set of pushes to github)

**Comment by ghidra1** [comment]
@mumbel, Can this ticket be closed based upon your previous comment?
