### ISSUE TITLE
Lots of empty data lines in the disassembled code

### ISSUE THREAD

**Issue by icedice** [NationalSecurityAgency/ghidra#2951]
While following a tutorial I see a lot of lines in the disassembled code that are basically empty. I'm unsure if it's related to the warning I see after finishing automatic analysis.
I'm on Ghidra 9.2.2 on a macbook pro M1, but I tried on a Intel macbook as well and had the same issue.
Any help would be highly appreciated.  Here is what I see:

<img width="1169" alt="Screenshot 2021-04-11 at 20 12 14" src="https://user-images.githubusercontent.com/5115869/115156449-a20fbe00-a084-11eb-986e-2e295a901949.png">
<img width="897" alt="Screenshot 2021-04-11 at 20 13 18" src="https://user-images.githubusercontent.com/5115869/115156453-a340eb00-a084-11eb-90c2-aa4df0f20ed7.png">

**Comment by mumbel** [comment]
add your JDK version info (only JDK 11 64-bit are officially supported, but they try to make it work with later versions) and 9.2.3 is out, might try that to see if it helps

**Comment by icedice** [comment]
> add your JDK version info (only JDK 11 64-bit are officially supported, but they try to make it work with later versions) and 9.2.3 is out, might try that to see if it helps

I have now tried with Ghirda updated to 9.3.3 and JDK 11 however the result is the same...

**Comment by icedice** [comment]
As it turs out hitting "d" on the "bald spots" fixed the issue and disassembled the code correctly. I have no idea why this is necessary but it works for what I needed to do.
