### ISSUE TITLE
Ghidra can't handle float/integer mixed on Microsoft x64 calling convention

### ISSUE THREAD

**Issue by topia** [NationalSecurityAgency/ghidra#2952]
I suspect Ghidra found bad parameters when mixed float/integer parameter.
according to [Microsoft document](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-160#parameter-passing), `(int, float, int)` should be passed as `(ECX, XMM1, R8D)`.
But Ghidra also found XMM0 and RDX, and it starts extraout_blahblah. I feel confused about that.

I think some fix is required on [its prototype defintion](https://github.com/NationalSecurityAgency/ghidra/blob/e7488245fd3e85dea6050e0dd66bb4a4dbeeb53b/Ghidra/Processors/x86/data/languages/x86-64-win.cspec#L42), but I can't understand what the correct fix is.

**Comment by midgen42** [comment]
I am also seeing this issue. Ghidra does not properly handle XMM0, XMM1, XMM2, XMM3 as parameters to pass floating point values. As an example, I have a this call which passes four params:  RCX, XMM1, XMM2, R9D.  Ghidra says the func has the following parameters:  XMM0, XMM1, XMM2, RCX, RDX, R8, R9D.

It seems that whenever XMM registers are involved, Ghidra requires that all XMM registers up to and including the last one used be passed and always passes them first. It does not understand that RCX and XMM0 are both the first param, RDX and XMM1 are the 2nd param, and so on.
