### ISSUE TITLE
Relocation(?) incorrect on MOV.W and RCALL instructions

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2956]
In the module sqrt.eo from the **xc16** library ```libm-elf.a```, there are a couple of disassembly problems that I think might have something to do with relocation entries that aren't handled correctly--but I could be wrong about that.

1. Where the source file ```sqrt.s``` has the following ```mov``` instructions:

```
     mov.w   #WREG11,w13             ; (w13) = &t
     mov.w   #WREG3,w14              ; (w14) = &q
```

and the Microchip assembly listing has:

```
 136 000044  0D 00 20 	        mov.w   #WREG11,w13             ; (w13) = &t
 137 000046  0E 00 20 	        mov.w   #WREG3,w14              ; (w14) = &q
```

Ghidra's disassembler listing shows an immediate value for the source operands:

```
                    rom:010044 1d 80 20 00     mov.w                          #0x801,W13
                    rom:010046 2e 80 20 00     mov.w                          #0x802,W14
```

2. Where the source file has

```
    rcall   __dpack
```
 (```dpack``` is an external symbol), and the Microchip assembly listing has:

```
 191 00008e  00 00 07 	        rcall   __dpack                 ; Round and pack
```
Ghidra has:

```
                    rom:01008e b9 03 07 00     rcall                          WREG3             undefined WREG3()
```

I'm attaching the source file as it comes from Microchip, the object module extracted from the library, and an archive of the sample Ghidra project (with the extension changed from ```.gar``` to ```.zip``` to please **github**.)

[sqrt.s.txt](https://github.com/NationalSecurityAgency/ghidra/files/6337908/sqrt.s.txt)
[sqrt.eo.zip](https://github.com/NationalSecurityAgency/ghidra/files/6337918/sqrt.eo.zip)
[GhidraSupport-sqrt.o-20210419.zip](https://github.com/NationalSecurityAgency/ghidra/files/6337937/GhidraSupport-sqrt.o-20210419.zip)

**Comment by mumbel** [comment]
have you looked at the Window->Relocation Table to check if there's an entry for that address?  It has the location/type/value/original bytes (also has the new bytes, but not default)

**Comment by gtackett** [comment]
That's a good idea, @mumbel. It would help to isolate the problem, and having relocation entries would probably make it easier to write a script to repair the errors.

**Comment by gtackett** [comment]
There are relocations for both of the MOV instructions 

```
Location       | Type | Values | Original Bytes | Name
rom:010044     | 0x8   | 0xdd   | 0d 00 20 00    | WREG11
rom:010046     | 0x8   | 0xde   | 0e 00 20 00    | WREG3
rom:00108e     | 0x1c  | 0xdf   | 00 00 07 00    | __dpack
```
So, I think Ghidra **is** getting these relocations wrong. Note that the entries in the "Name" column are what they should be.

**Comment by ghidra1** [comment]
My first guess is that the WREG11 and WREG3 symbols have been defined improperly.   I would think these should be register locations defined by the language (but we name them differently (W0..W15 instead of WREG0..WREG15).  Since they are not found as registers, they are treated like external symbols at an unknown location and placed in the  EXTERNAL block at arbitrary locations - which apparently are too large for the instructions to handle properly.  I will have to look into this further when I have more time.  Hopefully we can specify these names as an alias within the psec.

**Comment by ghidra1** [comment]
While I have a possible solution which can get the correct constant value for relocation processing.  Markup of the instruction is another matter.   Result:

```
      rom:010044 6d 01 20 00     mov.w      #0x16,W13
      rom:010046 6e 00 20 00     mov.w      #0x6,W14
```
This was accomplished by allowing the WREG names to be assigned as an alias for the W named registers (e.g., WREG11 alias for W11).

**Comment by ghidra1** [comment]
After running the script I wrote (`CreateRelocationBasedOperandReferences`) the code gets an appropriate reference applied to the operands:
```
      rom:010044 6d 01 20 00     mov.w      #WREG11,W13
      rom:010046 6e 00 20 00     mov.w      #WREG3,W14
```

**Comment by gtackett** [comment]
Does this also take care of the anomalous `rcall WREG3` which should be `rcall __dpack`?

**Comment by ghidra1** [comment]
I am working on that now.  This may stem from an alignment issue for fabricated addresses within the EXTERNAL block.
