### ISSUE TITLE
Structure Editor: Byte Offset in the preview remains in decimal despite show number in hexadecimal

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2959]
**Describe the bug**
Structure Editor Byte Offset in the preview remains in decimal despite "show number in hexadecimal"

**To Reproduce**
1. Edit a large structure size over 10 bytes then top right drop-down menu "show number in hexadecimal"
3. The table now display offset in hex but the preview graph under it remain in decimal
4. See picture botom part Offset 0...9,10,... instead of 0,...9,0xA,...

**Expected behavior**
Both the table and preview are in hex when hex mode is toggled 

**Screenshots**
![image](https://user-images.githubusercontent.com/4013370/115309154-2e48e080-a16c-11eb-906f-bc1a3f4a20ad.png)

**Environment (please complete the following information):**

![image](https://user-images.githubusercontent.com/4013370/115309238-49b3eb80-a16c-11eb-9428-faa6c243921b.png)

**Comment by ryanmkurtz** [comment]
Fixed by 539e09ee3d69df61d835b87503b6bd33ef2f9fb1
