### ISSUE TITLE
Offline building and local dependency repo setup

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#2963]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to build Ghidra an a machine with no internet and it fails because neither `mavenCentral` or `jcenter` can be accessed.

**Describe the solution you'd like**
A script that can be run on a machine with internet access to fetch the dependencies from those repos and place them in the `dependencies` folder. This folder may then be added as a repo to `build.gradle` as follows:

```gradle
if (flatRepo.isDirectory()) {
	allprojects {
		repositories {
			mavenLocal()
			maven {
				url "flatRepo/../repository"
			}
			mavenCentral()
			jcenter()
			flatDir name: "flat", dirs:["$flatRepo"]
		}
	}
}
```

**Describe alternatives you've considered**
Wait for the next release? This alternative is no fun though.

**Additional context**
The dependencies may be copied out of the gradle cache with a task as seen [here](https://discuss.gradle.org/t/need-a-gradle-task-to-copy-all-dependencies-to-a-local-maven-repo/13397/14) and below:
```gradle
task cacheToMavenLocal(type: Copy) {
  from new File(gradle.gradleUserHomeDir, 'caches/modules-2/files-2.1')
  into repositories.mavenLocal().url
  eachFile {
    List<String> parts = it.path.split('/')
    it.path = parts[0].replace('.','/') + '/' + parts[1] + '/' + parts[2] + '/' + parts[4]
  }
  includeEmptyDirs false
}
```
This is what I previously used to get the dependencies to build offline. Unfortunately you must first build Ghidra on another machine before running the above task in order to populate the repository. Having a task or script to get all these dependencies and setup the repo without going through a complete build would be appreciated. It would also be nice to have some sort of override with an enviroment variable or something to change the `dependencies` folder location as I would like to use a network drive so they can be shared with my teammates.

**Comment by razorapid** [comment]
There is a plugin for that (found in the link with referenced task snippet):

https://github.com/mdietrichstein/gradle-offline-dependencies-plugin

**Comment by ryanmkurtz** [comment]
How about just doing:
```
gradle -g dependencies/gradle buildGhidra
```

**Comment by razorapid** [comment]
> How about just doing:
> 
> ```
> gradle -g dependencies/gradle prepdev
> ```

This way, if user has gradle.properties file there with custom configuration, one will have to remember to move it to custom location as well, otherwise it won't apply.

**Comment by ryanmkurtz** [comment]
@astrelsky I think:
1. `gradle -I gradle/support/fetchDependencies.gradle init`
2. `gradle -g dependencies/gradle prepdev`
2. Move ghidra directory to different system
3. `gradle -g dependencies/gradle buildGhidra`

Should address this ticket.  What do you think?

**Comment by astrelsky** [comment]
> @astrelsky I think:
> 
> 1. `gradle -I gradle/support/fetchDependencies.gradle init`
> 2. `gradle -g dependencies/gradle prepdev`
> 3. Move ghidra directory to different system
> 4. `gradle -g dependencies/gradle buildGhidra`
> 
> Should address this ticket. What do you think?

This will fetch all the maven dependencies as well?

**Comment by astrelsky** [comment]
> Yes, `-g` tells gradle to use the specified argument as the gradle user home, so by making that go inside the Ghidra installation directory, you'll be moving all of the stuff gotten from maven along with Ghidra.

Interesting. I will give this a shot either this afternoon or tomorrow morning.

**Comment by astrelsky** [comment]
This worked without a problem. However there are two things:

1. Is it possible to have this done automatically when there is no internet connection?
2. May the `dependencies/` in `.gitignore` be moved to the top with a comment or something to not move it? This would allow the creation of a fork on an air-gapped or local network that may be updated from a bot with a git bundle without ever having to worry about conflicts. The maintainer could simple create a commit that comments out the line in `.gitignore.` and adds the dependencies folder to the fork.

**Comment by ryanmkurtz** [comment]
1. I thinking doing this technique is best left to manual control.  An individual can easily write their own trivial script to accomplish this though...I don't see a need to push it out to all Ghidra users/devs.
2.  I don't quite understand what you are asking for.  Are you wanting to check in your dependencies directory to your air-gapped fork but not have that conflict when you bring in updated versions of the GitHub repo?

**Comment by astrelsky** [comment]
1. Fair enough
2. Yes but without 1 then there isn't much point.

Basically I was hoping to be able to have an "offline" fork where it could be cloned and built without having to provide special instructions. Preventing conflicts would be ideal since the network administrator shouldn't be expected to know what to do when conflicts arise.

I'll probably continue manually updating from a git bundle for now. The solution is good enough for the initial issue and special instructions on my end *shouldn't* be too difficult.
