### ISSUE TITLE
lldb debugger support

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#2967]
It seems like it should be possible to use the existing gdb support to connect to `debugserver` like delve does: https://github.com/go-delve/delve/blob/master/pkg/proc/gdbserial/gdbserver.go

**Comment by mumbel** [comment]
@d-millar  discusses lldb in https://github.com/NationalSecurityAgency/ghidra/issues/2591 and https://github.com/NationalSecurityAgency/ghidra/issues/2653

**Comment by jrmuizel** [comment]
https://github.com/NationalSecurityAgency/ghidra/issues/2653#issuecomment-761936228 suggests that lldb doesn't support GDB/MI but I believe `delve` is successfully using it.

**Comment by d-millar** [comment]
@mumbel Thanks (I'd actually forgotten where I discussed this!)
@jrmuizel Appreciate the reference.  You're definitely (partially) correct, as I understand it.  The protocol used by gdb to talk to most existing gdb stubs is the Remote Serial Protocol (RSP), defined in their documentation.  This protocol was re-used by the lldb implementers, so, if you speak RSP, you can talk to both gdbserver and lldbserver and a host of gdb and gdb-like stubs, e.g. Mac devices booted in debug-mode.

In an older incarnation of the debugger, we actually supported RSP.  The problem with RSP is that it's not so much a standardized protocol, as a general outline.  Every flavor of gdb-gdbstub pair has variations, extra commands, choices of options, etc.  Implementing it is something of a nightmare.  Consider, for example, the z/Z packet.  In the docs, it describes the command:

‘z type,addr,kind’
‘Z type,addr,kind’

Z sets the breakpoint; z removes it.  Type 0 equals software; type 1 equals hardware.  Fine, except for the fact that, in reality, for some implementations, z sets the breakpoint and Z removes it.  For others, type 1 equals software and type 0 equals software.  And, so forth.

So, for the current implementation, the principal designer chose to go with the GDB/MI interface, which has a number of advantages.  It's a newer interface, certainly approaches being a standard, and is not plagued by many of the vagaries of RSP.  In the current implementation, the Ghidra client talks to an agent (over either SSH or our custom protocol), the agent wraps the native GDB/MI interface, which ultimately speaks RSP to the target.

So, you can run Ghidra on one machine, speak GADP to the agent running on the same or a different machine, and speak RSP from the agent to the target, which could be a third machine.  Theoretically (and I'll admit I haven't tried this), the Ghidra machine could be running Windows, Linux, or OSX, with the agent machine running Linux, and the target machine running OSX.  In other words, as long as you're willing to have Linux in the middle (or an OSX version of gdb), you may already be able to talk to lldbserver running as the "target".

Unfortunately, that's a little cumbersome.  Most people who want to debug OSX apps probably want to run Ghidra on the same box as the agent and the target, especially for user-mode targets. For this to work right now, you would need either (a) gdb compiled for OSX with the appropriate Pty support for our implementation, or (b) a version of lldb with support for a GDB/MI-style interface.

Having recently been made aware of a Windows implementation of Pty, I'm a little hesitant to say one doesn't exist for OSX, but your standard run-of-the-mill OSX implementation definitely doesn't have one.  So, (a) is a maybe, but not ideal.  Option (b) was, at one point, supported.  There are versions of lldb that support GDB/MI, but the developers, as referenced in the other issue discussions, have moved away from this in favor of their own API.  Given the fact that Apple is more of an out-with-the-old-and-in-with-the-new shop than, say, Microsoft, the questions becomes should we build toward what is likely to be supported in the future or go with what's an easier reach in the present.  Right now, we're leaning toward the former.

Let me know if any of this is unclear (or wrong!). This is an open question for us and likely to be on our development path in the near(ish) future, so we're happy to hear arguments, opinions, options, suggestions, whatever you've got!

Best, D

**Comment by d-millar** [comment]
P.S. I'm a Mac user myself, so am definitely in favor of progress on this issue!

**Comment by jrmuizel** [comment]
Ah, that makes sense. I had forgotten that the RSP was a different protocol than GDB/MI.

**Comment by jrmuizel** [comment]
I guess another option to getting this to work would be to connect `gdb` to `debugserver`. This currently seems broken so I filed https://sourceware.org/bugzilla/show_bug.cgi?id=27768

**Comment by nsadeveloper789** [comment]
We just pushed our SSH support for connecting to GDB which could sidestep the platform-dependent pty issue. That said, I've not tried connecting to a macOS target, yet. In theory, you can run Ghidra on macOS, and (assuming you have an SSH server and a functional GDB on your system) connect to GDB via ssh to localhost. You can do this without and VMs, etc., but last I checked GDB is no longer well supported on macOS, so your experience may still be rough.

**Comment by jrmuizel** [comment]
I get a NullPointerException when trying to connect to localhost on macOS with ssh.
```
java.lang.NullPointerException
	at agent.gdb.manager.impl.GdbManagerImpl.waitGdbExit(GdbManagerImpl.java:635)
	at java.base/java.lang.Thread.run(Thread.java:830)

---------------------------------------------------
Build Date: 2021-Apr.-23 1402 EDT
Ghidra Version: 9.3
Java Home: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
JVM Version: Oracle Corporation 13.0.1
OS: Mac OS X 10.15.6 x86_64
Workstation: localhost
```

**Comment by d-millar** [comment]
@jrmuizel Make sure you have the latest from the "debugger" repo and connect with SSH.  If you connect with IN-VM or GADP on OSX, it will try to instantiate a PtySession which unlikely to work.  SSH should side-step the issue, launch gdb, and connect without the pty.

**Comment by d-millar** [comment]
@jrmuizel ah - apologies.  Let me see if I can recreate....

**Comment by d-millar** [comment]
@jrmuizel  Still working on this - have made some progress but not enough to get excited about.  Was able to recreate your error, although am worried this crops up in a number of contexts.  One problem, for sure, is that any time gdb gets unhappy, it kills itself, and takes down the connection in a not terribly obvious way.

One mistake I made starting up was to use /usr/local/bin/gdb as the path.  That's the path, but it's a link to my Cellar install and apparently the SshPtySession is not happy about links.  Using /usr/local/Cellar/gdb/10.1/bin/gdb, got me further, but I can't seem to find an executable I can run in regular gdb from the terminal.  Everything generates a thread error and kills gdb.  If you have a good test target, send it my way.  :)

Anyway, will continue hacking on this - sorry this is so complicated!

**Comment by d-millar** [comment]
OK, so it appears the "thread.c:95 internal error" I'm getting is a known bug for gdb on Mojave.  Just out of curiosity what flavor of OSX are you running and which version of gdb?

**Comment by jrmuizel** [comment]
Ah. If I specify `/usr/local/bin/gdb` instead of just `gdb` it actually connects. I haven't tried actually debugging yet as my `gdb` is not signed.

I'm on 10.15 using gdb 10.1 from homebrew.
