### ISSUE TITLE
Wrong decompilation of NEON vld instruction

### ISSUE THREAD

**Issue by kirill9617** [NationalSecurityAgency/ghidra#2968]
**Describe the bug**
Instruction `vld1.8 {d16,d17},[r0]` is being decompiled as "fill d16 with r0[0] and d17 with r0[1]", while it should be "load 8 bytes from *r0 to d16 and 8 bytes from *(r0+8) to d17".  

**To Reproduce**
1. Load attached file.
2. Mark .text section as volatile
3. See 
`write_volatile_8(data2._0_8_,0xaaaaaaaaaaaaaaaa);
  write_volatile_8(data2._1_8_,0x1010101010101010);`
in decompiler output.

**Expected behavior**
It\`s expected to see 
`write_volatile_8(data2._0_8_,0x70605040302010aa);
  write_volatile_8(data2._1_8_,0xf0e0d0c0b0a09080);`
in decompiler output.

**Attachments**
[neon.zip](https://github.com/NationalSecurityAgency/ghidra/files/6357204/neon.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/536109/115692484-b2b38300-a367-11eb-8850-ccb0011ae39b.png)

**Environment (please complete the following information):**
 - OS: ArchLinux 
 - Java Version: OpenJDK 11.0.10
 - Ghidra Version: 9.2.3
 - Ghidra Origin: official ghidra-sre.org distro 

**Additional context**

**Comment by CmP-lt** [comment]
This has been fixed supposedly in 3be5defc15313436dc5d564095e3b45cf5b4bb04. In currently latest Ghidra version (10.3) code fragment of interest is decompiled correctly: 
![image](https://github.com/NationalSecurityAgency/ghidra/assets/61097734/098ab2e5-b579-499d-b3a7-0f197aa6deef)

**Comment by ryanmkurtz** [comment]
Thanks for following up.
