### ISSUE TITLE
m68k debugging support

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#2973]
It seems like the debugger doesn't work with m68k-elf-gdb. It looks like it might need something like GdbM68000DebuggerMappingOpinion.java

**Comment by d-millar** [comment]
@jrmuizel Correct - have added one, probably be pushed next week.  In the meantime, something like this should work if you want to try it out:

package ghidra.app.plugin.core.debug.platform;

import java.util.Set;

import ghidra.app.plugin.core.debug.mapping.DebuggerMappingOffer;
import ghidra.app.plugin.core.debug.mapping.DebuggerMappingOpinion;
import ghidra.dbg.target.TargetEnvironment;
import ghidra.dbg.target.TargetProcess;
import ghidra.program.model.lang.CompilerSpecID;
import ghidra.program.model.lang.LanguageID;

public class GdbM68kDebuggerMappingOpinion implements DebuggerMappingOpinion {
	protected static final LanguageID LANG_ID_68K_BE = new LanguageID("68000:BE:32:default");
	protected static final CompilerSpecID COMP_ID_DEFAULT = new CompilerSpecID("default");

	protected static class GdbM68kBELinux32DefOffer extends AbstractGdbDebuggerMappingOffer {
		public GdbM68kBELinux32DefOffer(TargetProcess process) {
			super(process, 100, "GDB on Linux m68k - 32-bit", LANG_ID_68K_BE, COMP_ID_DEFAULT,
				Set.of());
		}
	}

	@Override
	public Set<DebuggerMappingOffer> offersForEnv(TargetEnvironment env, TargetProcess process) {
		if (!env.getDebugger().toLowerCase().contains("gdb")) {
			return Set.of();
		}
		String os = env.getOperatingSystem();
		if (!os.contains("Linux")) {
			return Set.of();
		}
		String endian = env.getEndian();
		if (!endian.contains("big")) {
			return Set.of();
		}
		String arch = env.getArchitecture();
		if (arch.startsWith("mips:32")) {
			return Set.of(new GdbM68kBELinux32DefOffer(process));
		}
		return Set.of();
	}

}

**Comment by jrmuizel** [comment]
Yep, with something like that I was able to get things further along. I had registers updating but the dynamic listing didn't show anything. "Modules" is empty under "Inferior" so perhaps that needs to be fixed? I'm trying to debug using MAME's gdbstub so it likely has something to do with that.

**Comment by d-millar** [comment]
@jrmuizel Ah, yes, I believe you are correct again.  If the gdbstub fails to report any modules, the debugger believes it has no memory.  There's a file under Debug/Debugger/src/main/resources called "define_info_proc_mappings", which is a script for defining, basically, the complete 64-bit space.  If you run this from the Interpreter or as part of the gdb start-up, it *should* fix the problem.  (We, admittedly, need a better solution for this issue, but I think the hack works.)

**Comment by jrmuizel** [comment]
Yep, using that script (or rather a 32 bit version of it) made the dynamic listing show a disassembly. However, the dynamic listing was not synced with the regular listing.

I also noticed the dynamic listing not synced when with the regular listing when debugging a x86-64 Linux program. I was only able to see them synced when debugging a Linux dynamic library.

**Comment by d-millar** [comment]
Re syncing, I feel like this may also be a casualty of the lack of module list.  Are we still talking about that case?  I think the current logic uses the module tables to locate which static listing should be mapped to the dynamic listing, i.e. even if you've rebased the static listing to the correct base address, the current logic may be ignoring it.  May have to come up with another workaround, if so.

**Comment by jrmuizel** [comment]
Yeah, that sounds believable. I tried overriding `maintenance info sections ALLOBJ` which seems to be what Ghidra uses for determining the modules, but I get '"maintenance info sections" is not a prefix command.' so it seems like something more involved will be necessary.

**Comment by nsadeveloper789** [comment]
ALLOBJ is an argument to the `maintenance info sections` command, so perhaps try overriding it instead. There is also a way to introduce static-dynamic mappings from the UI, but it's a bit obtuse. It may be easier to do it from a Ghidra script....

From the UI:
- Window -> Debugger -> Static Mappings
- Probably dock that thing somewhere out of the way. I suggest tabbed with Regions, Stack, Watches, etc.
- In the Static Listing, select the port of code you want to map into the Target.
- In the Dynamic Listing, go to the address corresponding to the *minimum* address of your Static selection.
- From the new "Static Mappings" window, click the "Add Mapping from Listing Selections" action in its toolbar.

From a script, using starting address `ram:00400000` for example:
```java
public class AddMapping extends GhidraScript {
	@Override
	protected void run() throws Exception {
		DebuggerStaticMappingService mappings =
			state.getTool().getService(DebuggerStaticMappingService.class);
		DebuggerTraceManagerService traces =
			state.getTool().getService(DebuggerTraceManagerService.class);
		Trace currentTrace = traces.getCurrentTrace();
		AddressSpace dynRam = currentTrace.getBaseAddressFactory().getDefaultAddressSpace();

		AddressSpace statRam = currentProgram.getAddressFactory().getDefaultAddressSpace();
		mappings.addMapping(
			new DefaultTraceLocation(currentTrace, null, Range.atLeast(0L),
				dynRam.getAddress(0x00400000)),
			new ProgramLocation(currentProgram, statRam.getAddress(0x00400000)),
			0x10000, false);
	}
}
```

Note that the starting addresses between static and dynamic do not have to be equal.

**Comment by jrmuizel** [comment]
Yep, overriding `maintenance info sections` works and makes some a module show up, but I wasn't able to get the mappings to automatically work from that.

I was, however, able to add the mapping manually using your UI directions and that seems to get everything working.

Thanks for your help.

**Comment by jrmuizel** [comment]
@d-millar the 68k opinion mapping file that made it into `master` should use `arch.startsWith("m68k")` instead of `arch.startsWith("mips:32")`

**Comment by d-millar** [comment]
Oops - thanks!  Will fix - cut & paste sadness.
