### ISSUE TITLE
SSH support in debugger can't connect to Ubuntu 20.04

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#2974]
SSH support in debugger seems to only support a limited set of kexParameters

Ghidra supports:
```
diffie-hellman-group-exchange-sha1
diffie-hellman-group14-sha1
diffie-hellman-group1-sha1
```

The Ubuntu 20.04 default is:
```
curve25519-sha256
curve25519-sha256@libssh.org
ecdh-sha2-nistp256
ecdh-sha2-nistp384
ecdh-sha2-nistp521
diffie-hellman-group-exchange-sha256
diffie-hellman-group16-sha512
diffie-hellman-group18-sha512
diffie-hellman-group14-sha25
```

As can be seen, there are no matches between the two groups which prevents establishing a connection.

**Comment by jrmuizel** [comment]
It looks like something like https://github.com/SoftwareAG/ganymed-ssh-2/commit/ef7fbc4d34bb8eb4b59a9946d608a799f8f48ce5 is needed for this to work.

**Comment by d-millar** [comment]
Going to leave this one for @nsadeveloper789, who did the implementation of ssh.  There was some discussion of ganymed-ssh, and I apparently wasn't paying attention at the crucial moment.  :(

**Comment by jrmuizel** [comment]
FWIW, adding the following to the sshd config makes things work:
```
KexAlgorithms +diffie-hellman-group1-sha1
Ciphers +aes128-cbc
```

**Comment by nsadeveloper789** [comment]
Hmm. It looks like the project's original maintainers have abandoned it. The repo you linked is a fork. If they published to Maven Central, I'd be more inclined to use "version 263," but I don't see it there. It's good to hear you found a workaround, though. If you'd rather keep the more secure algorithms, you might consider "upgrading" on your own. If you've been taking the "build and install" route, you should be able to just replace the 262 jar with the 263 one. If you're running from Eclipse, then it's more complicated.

I think a better answer is for us to switch to JSch.... eventually. AFAICT, it is still maintained and has support for the newer exchange algorithms.
