### ISSUE TITLE
Gradle build task report "could not find helpIndexCompile() for arguments..."

### ISSUE THREAD

**Issue by DavveDP** [NationalSecurityAgency/ghidra#2977]
**Error***
Unrecognized method in helpProject.gradle "helpIndexCompile"

Tested gradle versions: 5.0, 6.8.3 and 7.0

Build attempt:
![image](https://user-images.githubusercontent.com/56189276/116091064-c848e580-a6a4-11eb-9154-c3837c401376.png)

**Environment**
 - OS: Windows 10 Pro [19042.928]
 - Java JDK Version: [11.0.11]
 - Attempted Ghidra Build Version: [e.g. 9.3.0-debugger fork]

**Comment by ryanmkurtz** [comment]
I think what you posted here was using Gradle 7, which Ghidra does not currently support.  Can you please post your output of Gradle 6.8.3?

**Comment by DavveDP** [comment]
It would appear my path variable wasn't updated correctly, tried with gradle 6.8.3 and got different build errors related to win64PDBMake. Not related to this issue so I guess we can close it. 

@ryanmkurtz Thanks for the quick reply!
