### ISSUE TITLE
Fid DB Search Results columns are not resizeable

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#2978]
~~While the FID Db Search window is open,~~ I can't resize any columns in the Fid DB Search Results Table. ~~Perhaps due to modality?~~

Can this be changed, and/or is it by design?

**Comment by ryanmkurtz** [comment]
Mine seem to be resizable when the FID Db Search window is open.  Sometimes columns are resizable but the cursor doesn't change when you hover over the right spot.  Could that be the issue?

**Comment by gtackett** [comment]
The cursor is changing but nothing happens when I click and try to drag it either direction.

**Comment by gtackett** [comment]
After closing and re-opening Ghidra I can't reproduce it either. I had had some errors logged during that session that might have interfered with the GUI.

However, the minimum width for many of the columns is overly wide. It's hard to imagine numbers of 18 digits or so (a rough estimate of what would fit currently) in the **Code Unit Size** or **Spec. +Size** columns.

I can easily imagine the **Name** column needing to be wide, but currently its minimum width is excessive.

**Comment by gtackett** [comment]
And while we're at it (but probably material for another issue), only being able, in the Search Results window, to Edit only one function at a time is really limiting if you have a few dozen likely matching functions. (That shouldn't be the case, I suppose, but I'm still working at getting these function IDs straightened out.)

**Comment by gtackett** [comment]
I've requested an improvement to column widths in issue [2989](https://github.com/NationalSecurityAgency/ghidra/issues/2989)
