### ISSUE TITLE
Improve DecompilerDataTypeReferenceFinder

### ISSUE THREAD

**Issue by homes410** [NationalSecurityAgency/ghidra#2986]
Current implementation of DecompilerDataTypeReferenceFinder doesn't consider type order found in buildTypeLineage... so if you need to find reference of datatype you wanted to, you become bored while having to sit until every function is decompiled. this shouldn't happen.

So, proposed change modifies HashSet to LinkedHashSet to preserve insertion order of `types'.
and filterFunctions returns Collection<?> instead of Set<?> 

And this change increases java version requirement to 1.8 although i don't know target version of `ghidra sre'.

Please have a look on this patch.
[0001-210429.txt](https://github.com/NationalSecurityAgency/ghidra/files/6396910/0001-210429.txt)
.
Thank you.

**Comment by dragonmacher** [comment]
There seems to be some misunderstanding about how this API currently works.

1. All applied data types are searched before the decompiler is used.  This means that the table of results will show information before any functions are decompiled.
2. The loading of the table is done on the fly.  As results are found, the table is updated.  This means that you do not have to wait for all functions to be decompiled before you can **see and use** the results.
3. The finder does not decompile every function.  It filters out those that do not return or take in the requested type.  This means less work overall is done.
4. The decompiler's results are searched for references.    This means that any usage of types found within the **body** of the function are found, in addition to the return type and parameters.
5. The ordering of types as they are discovered does not need to be maintained, as the results table showing the types allows the user to sort the information in any order.
6. You don't have to let the search for types finish.  If you see results you like in the table, then you can stop the search if you so choose.

**Comment by homes410** [comment]
I see your remarks and totally agree about you said. But,
> 5. The ordering of types as they are discovered does not need to be maintained, as the results table showing the types allows the user to sort the information in any order.

Well, The order matters when there is many related type.
For example you want to find dataType** so that which function dereference and assign some field, You don't want to see function with variables dataType* coming out first. This patch was meant to address the issue.

Regards.
