### ISSUE TITLE
Retpoline support

### ISSUE THREAD

**Issue by andreafioraldi** [NationalSecurityAgency/ghidra#299]
Ghidra stops disassembling after a jump to a retpoline:

![Screenshot at 2019-03-31 15-37-57](https://user-images.githubusercontent.com/16168186/55289911-b2d13680-53cc-11e9-862b-46973a1457b9.png)

The correct behaviour is to disassemble these instructions and also include them in the analyzed function. In the screenshot there is a jump table that is not recognized.

**Comment by mumbel** [comment]
I checked my kernel, and it has a __x86_indirect_thunk_rbx() for example in rb_advance_iter() and it did not recognize the indirect reference.  Wonder if this is more of an indirect reference issue than retpoline per se (I also didn't allow auto-analysis to finish so it might have eventually unsigned and linked it).

```
MOV RBX,qword ptr [-0x7e7e7298 + R10*0x8]
MOV RBX,qword ptr [0xFFFFFFFF81818D68 + R10*0x8]
MOV RBX,qword ptr [PTR_LAB_ffffffff81818d68 + R10*0x8]
```
I did change the negative to the unsigned value, then created the reference ALT-R to a table which pointed back into the function.  Is that anything similar to your issue?  This situation (again noting no auto-analysis) did break the decompiler.

**Comment by toshipiazza** [comment]
I wonder if you can solve this by using the same mechanism Ghidra has for lifting `get_pc_thunk_bx` (see x86gcc.cspec)

**Comment by andreafioraldi** [comment]
@mumbel yes it is similar, I used a test binary to avoid to lose time in the analysis of the kernel:

[test.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/3028107/test.tar.gz)

Stopping analysis after an indirect jump when you can't guess the target point it's a correct choice (maybe disassemble the following instruction anyways) but the issue is that retpolines should be recognized as a particular case.

**Comment by toshipiazza** [comment]
I added the following lines to x86-64-gcc.cspec:

```
<callfixup name="x86_indirect_thunk_rax">
    <target name="__x86_indirect_thunk_rax"/>
    <pcode>
        <body><![CDATA[
            goto [RAX];
            ]]></body>
    </pcode>
</callfixup>
```

Then, opening the test bin and triggering auto-analysis seems to analyze all the code after the __x86_indirect_thunk_rax (and decompilation looks good too).

Of course, for completeness you should also add one for __x86_indirect_thunk_rbx, and for all variations of architectures that you care about.

**Comment by andreafioraldi** [comment]
@toshipiazza cool! I'm not proficient with Ghidra and this seems a very good feature.
Consider also to recognize retpolines using code patterns because in a stripped binary there will not be the symbol.
Not doing this for stripped binaries is not the end of the world but at least, if you keep using symbols, define if for all GPR because the target register is chosen by the reg allocator (for instance in the same example that i attached in the previous comment clang uses r11).

**Comment by mumbel** [comment]
Looks like my kernel has a thunk for all gpr except rsp.  it also looks like gcc changed the symbol to essentially the 16bit name for the first 7 regs, but still r# for the next 8 (32bit would be a whole other set of thunks before this change too)

**Comment by toshipiazza** [comment]
> Consider also to recognize retpolines using code patterns because in a stripped binary there will not be the symbol.

I have no good ideas for this, aside from using something like flirt to symbolize these thunks in IDA, then export to Ghidra. Alternatively, this is hardly automatic but if you *do* come across an unsymbolized `__x86_indirect_thunk_rax` function you can specify the fixup manually in "Edit Function Signature" -> lower left dropdown (iirc).

**Comment by emteere** [comment]
You can add this into the pattern file x86-64gcc_patterns.xml to find the function when the symbols have been stripped.  It may also appear in the FID files at some point for Visual Studio so you wouldn't need to add it into the patterns file.  It would still need a callfixup entry.

All the variants would need to be done, since the names are different for each register.  We'll see if we can get it into the next patch.

```
<pattern>
  <data> 0xe8 0x07 0x00 0x00 0x00 <!-- CALL +7 -->
  0xf3 0x90                       <!-- PAUSE -->
  0x0f 0xae 0xe8                  <!-- LFENCE -->
  0xeb 0xf9                       <!-- JMP -7 -->
  0x48 0x89 0x04 0x24             <!-- MOV [RSP],{RAX] -->
  0xc3                            <!-- RET -->
  </data>
<funcstart label="__x86_indirect_thunk_rax" validcode="function"/>
</pattern>
```

**Comment by emteere** [comment]
An alternative that requires a bit more hands on surgery is to modify the instruction flow on the __x86_indirect_thunk_XXX routines.  Also the initial JUMP is changed into a call_return flow already, which is OK, however the __x86_indirect_thunk_XXX routines would need to be changed to inline as well. 

```
                             LAB_00400d0c                                    XREF[2]:     main:0040065a (j) ,  004c6468 (*)   
        00400d0c e8  07  00  00  00     CALL       LAB_00400d18
                                                      RSP  =  INT_SUB  RSP , 8:8
                                                      STORE  ram (RSP ), 0x400d11 :8
                                                      BRANCH  *[ram ]0x400d18 :8
                             -- Flow Override: BRANCH (UNCONDITIONAL_JUMP)
                             LAB_00400d11                                    XREF[1]:     00400d16 (j)   
        00400d11 f3  90               PAUSE
        00400d13 0f  ae  e8            LFENCE
        00400d16 eb  f9               JMP        LAB_00400d11
                                                      BRANCH  *[ram ]0x400d11 :8
                             LAB_00400d18                                    XREF[1]:     00400d0c (j)   
        00400d18 48  89  04  24         MOV        qword ptr [RSP ],RAX
                                                      $U1f70 :8 =  COPY  RAX
                                                      STORE  ram (RSP ), $U1f70
        00400d1c c3                  RET
                                                      RIP  =  LOAD  ram (RSP )
                                                      RSP  =  INT_ADD  RSP , 8:8
                                                      BRANCHIND  RIP
                             -- Flow Override: BRANCH (COMPUTED_JUMP)
```
The switch is recovered with this change as well.

A script or analyzer, to match the instruction patterns, could make the change to the instruction flows.
