### ISSUE TITLE
Crash on "Download PDB File..."

### ISSUE THREAD

**Issue by ApocalHyps** [NationalSecurityAgency/ghidra#2993]
Fresh installation of ghidra I'm trying to get my first analysis and the pdb file is not found so after looking on google I found that I can use a symbol server. Honestly, not very familiar with all of that. Anyway, proceeding and selecting "https://msdl.microsoft.com/download/symbols/" as the symbol server URL and about 4 s after clicking Download from URL I got an error that I joined after.

![image](https://user-images.githubusercontent.com/43624200/116784359-1fc7c680-aa94-11eb-8e69-2f101cdfc069.png)

for information : 
Ghidra Version: 9.2.3
Java Home: C:\Program Files\Java\jdk-11.0.11
JVM Version: Oracle Corporation 11.0.11
OS: Windows 10 10.0 amd64

Could you help me understand what should I do ? Or better if there is a way to decompile without all this when I got this message : 

PDB Universal> Unable to locate PDB file "C:\Users\[...]\source\repos\[...].pdb" with matching GUID.
 You can manually load PDBs using the "File->Load PDB File..." action.
 Alternatively, you may set the PDB Symbol Repository Path
 using "Edit->Options for [program]" prior to analysis.
PDB Universal> Cannot find candidate PDB files.

To note that I only have access to the compiled version and the path given by ghidra here on the PDB file doesn't exist for me.

**Comment by xiaoyinl** [comment]
I can reproduce this issue. I fixed it by editing the file `support/launch.properties` under your Ghidra installation directory: find the line `VMARGS=-Dhttps.protocols=TLS`. Change this line to `VMARGS=-Dhttps.protocols=TLSv1.2`. Microsoft symbol server doesn't support TLS 1.3.

I think this is related to #1717.

**Comment by ApocalHyps** [comment]
> I can reproduce this issue. I fixed it by editing the file `support/launch.properties` under your Ghidra installation directory: find the line `VMARGS=-Dhttps.protocols=TLS`. Change this line to `VMARGS=-Dhttps.protocols=TLSv1.2`. Microsoft symbol server doesn't support TLS 1.3.
> 
> I think this is related to #1717.

Worked perfectly thank you.

**Comment by dev747368** [comment]
Should be addressed by 22675e9f39dd23bb1f0df775ef3cc2c8f22e81a7
