### ISSUE TITLE
Decompiler shows uint8_t as char

### ISSUE THREAD

**Issue by shuffle2** [NationalSecurityAgency/ghidra#3004]
**Describe the bug**
Most of the time, especially dealing with unsigned data, I'd prefer to see the data in hex. I have `Options > Decompiler > Display > Integer Format = Force Hexadecimal`. However the decompiler still shows uint8_t typed data as char. In this case, uint8_t is coming from generic_clib, with base type of `uchar`.

This seems maybe similar to https://github.com/NationalSecurityAgency/ghidra/issues/2565

**To Reproduce**
1. Define a function taking uint8_t such as `void f(uint8_t)`
2. Have a call like `f(1)`
3. Decompiler shows `f('\x01')`

**Expected behavior**
Decompiler should show `f(1)` (or `f(0x01)`)

**Environment (please complete the following information):**
 - OS: Windows [Version 10.0.19042.928]
 - Java Version: openjdk 15.0.2 2021-01-19
 - Ghidra Version: f91ba90fe8b73d60df7ceb52427a61c8f4a8ebcf
 - Ghidra Origin: locally built

**Comment by caheckman** [comment]
A pending change allows the decompiler to respect the format settings on typedef data-types.  For the situation described here: you would find the uint8_t typedef within the Data Type Manager window and select the Settings... menu action from the right-click pop-up menu, then in the resulting dialog select "hex" from the Format drop-down menu.
