### ISSUE TITLE
Typedef Tooltip is backwards

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#3005]
**Describe the bug**
The tooltip for a typedef is displayed in the wrong order.

**To Reproduce**
1. Hover mouse over `ptrdiff_t` in the generic_clib archive.
2. See `typedef ptrdiff_t long`

**Expected behavior**
It should be `typedef int ptrdiff_t`

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/46897303/117080282-7e4aaa00-ad0b-11eb-9a31-72e85a5bb271.png)

**Environment (please complete the following information):**
 - OS: N/A
 - Java Version: N/A
 - Ghidra Version: 10.0_DEV
 - Ghidra Origin: N/A

**Comment by dev747368** [comment]
Have you noticed the array notation in a structure?  :)

**Comment by astrelsky** [comment]
> ![ghidra_struct_member_array](https://user-images.githubusercontent.com/48332326/117376142-825b0100-ae9e-11eb-8995-a7060fdf0058.png)
> Have you noticed the array notation in a structure? :)

Nice photoshop, there no way.

<details><summary>After opening ghidra and creating a test struct with array member</summary>

![](https://static.wikia.nocookie.net/meme/images/f/f9/Mother-of-god-meme_3997206.jpg/revision/latest?cb=20140417165010)
</details>

Details... minor details.

**Comment by astrelsky** [comment]
> 
> ![ghidra_struct_member_array](https://user-images.githubusercontent.com/48332326/117376142-825b0100-ae9e-11eb-8995-a7060fdf0058.png)
> Have you noticed the array notation in a structure?  :)

I also noticed that the array sizes are part of the field names in the pe headers the other day. 🤣

**Comment by ghidra1** [comment]
Our datatype renderings are not intended to represent valid C code.  This is also true within the decompiler where we do not prefix struct/union variable declarations as such.
