### ISSUE TITLE
Gradle build init: GPL/gpl.gradle doesn't exist.

### ISSUE THREAD

**Issue by SirEnder125** [NationalSecurityAgency/ghidra#3007]
Hello. Upon running `gradle -I gradle/support/fetchDependencies.gradle init` I got the following error:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\*\Downloads\ghidra-master\ghidra-master\GPL\CabExtract\build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':CabExtract'.
> Could not read script 'C:\Users\Mihai\Downloads\ghidra-master\ghidra-master\GPL\gpl.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
```

What should I do?

**Comment by SirEnder125** [comment]
I copied gpl.gradle from this repository, it did not download with the rest of the source for some reason.

**Comment by ryanmkurtz** [comment]
I just downloaded this repo as a zip file, unpacked it, ran `gradle -I gradle/support/fetchDependencies.gradle init` and didn't have any problems.  Is your problem repeatable?

**Comment by SirEnder125** [comment]
I'm not sure what happened, but gpl.gradle was left out of my download. I copied the file into GPL folder and Ghidra compiled.
