### ISSUE TITLE
how to import a mach-o fat binary with analysisHeadless

### ISSUE THREAD

**Issue by DogeWatch** [NationalSecurityAgency/ghidra#3009]
I use command like "analysisHeadless project_path project_name -import /path/of/this/mach-o/fat/binary -postScript xxx" and got error like "ERROR The AutoImporter could not successfully load xxx with the provided import parameters"
ghidra version: 9.2.3

**Comment by astrelsky** [comment]
As a sanity check may you try importing it in the gui and see what happens?

**Comment by DogeWatch** [comment]
> As a sanity check may you try importing it in the gui and see what happens?

with gui it give me three options to choose: single file, batch and file system, only the batch mode is correct. I just want to know how to import a single mach-o fat file with this batch mode

**Comment by ryanmkurtz** [comment]
Fat binary is treated as a "file system" in Ghidra, and the headless analyzer currently does not have the capability to dig into file systems to automatically extract and analyze their files (in this case, their files being the individual mach-o's).

**Comment by TorgoTorgo** [comment]
For anyone who finds this in the future, you can `lipo` the binary before processing it to extract the slice you want to analyze.

Check `man lipo`, for the `-thin` argument.

**Comment by ryanmkurtz** [comment]
You can also directly import the "slice" from Ghidra if you open it as a File System.
