### ISSUE TITLE
Jython Internals In Bad State After Exception

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#301]
**Describe the bug**
After a python script fails to execute due to an exception, it appears that some memory is not being freed.

**To Reproduce**
Write a python script that uses a decently large chunk of memory and than fails.

**Expected behavior**
Jython internals to be cleared, reset, or all allocated memory for the faulty jython script to be freed upon exit.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.379]
 - Java Version: 11.0.2
 - Ghidra Version: 9.0.1

**Additional context**
For reference, I am attempting to parse the json file created after running retdec up to its bin2llvmir and then use a python script to import the detected classes into ghidra. The size of the json file is a whopping 64.3Mb since it not only contains the detected 444 classes, but also every llvm variable found from the parsed binary (I'm sure someone was going to ask). It only fails to load this file after having failed due to an unhandled exception or typo after loading the json file. I suspect that the memory may not be freed after the script exits.

**Console Log**
```
Traceback (most recent call last):
  File "C:\Users\astre\Documents\ghidra_plugins\retdec-fileinfo\ImportClassesScript.py", line 83, in <module>
    make_labels(file_info['classes'])
  File "C:\Users\astre\Documents\ghidra_plugins\retdec-fileinfo\ImportClassesScript.py", line 61, in make_labels
    for virtual_table in virtual_tables(info):
NameError: global name 'info' is not defined
ImportClassesScript.py> Finished!
ImportClassesScript.py> Running...
C:\Users\astre\Documents\ghidra\Ghidra\Features\Python\data\jython-2.7.1\Lib\json\decoder.py:366: RuntimeWarning: PyTableCode.call caught a Throwable that is not an Exception:
org.python.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: Java heap space
Jython internals might be in a bad state now that can cause deadlocks later on.

```

**Additional Question**
I would like to ask as I cannot seem to find the relevant information online or in the documentation. Is there a function accessible from Jython that will allow me to create labels into the Classes in the Symbol Tree?

**Comment by GhidraKnight** [comment]
Once the JVM encounters an OutOfMemoryError, then the JVM is pretty much dead and needs a restart.  Try increasing the JVM memory in the ghidraRun.[sh|bat] file to a couple GBs.

To create a "Class" in the Symbol Tree:  currentProgram.getSymbolTable().createClass(Namespace,String,SourceType)

**Comment by astrelsky** [comment]
> Once the JVM encounters an OutOfMemoryError, then the JVM is pretty much dead and needs a restart. Try increasing the JVM memory in the ghidraRun.[sh|bat] file to a couple GBs.
> 
> To create a "Class" in the Symbol Tree: currentProgram.getSymbolTable().createClass(Namespace,String,SourceType)

I see, that is rater unfortunate. I will see if increasing the JVM memory helps. Also, thank you for pointing me in the write direction to parsing the classes.

Regards,
Andrew Strelsky
