### ISSUE TITLE
Fix memory leak in table control of Docking component 

### ISSUE THREAD

**Issue by homes410** [NationalSecurityAgency/ghidra#3013]
**Describe the bug**
After window that displayed table is closed, table model data is not garbage collected. 

**To Reproduce**
1. Launch tool in Search - For Address Tables...
2. A window pop up.
3. Click Search.
4. Dismiss the window.
5. Launch visualvm and attach ghidra
6. Take heap snapshot
7. Click a panel that is with title of instances by size.
8. HashMap$Node[] is placed at first. Expanding subtree reveals that table control is still referencing model.

**Attachments**
A patch file is attached.
[0001-210508.patch.txt](https://github.com/NationalSecurityAgency/ghidra/files/6444450/0001-210508.patch.txt)

**Environment (please complete the following information):**
 - Ghidra Version: [e.g. 9.2.2]

**Comment by dev747368** [comment]
I'll take a look at it as time allows.  There are different categories of memory leaks that warrant more or less concern when it comes to UI components.
