### ISSUE TITLE
Build failing due to helpIndexCompile not being found

### ISSUE THREAD

**Issue by loovjo** [NationalSecurityAgency/ghidra#3024]
**Describe the bug**
Trying to build the master branch on a MacBook M1, doing `gradle -I gradle/support/fetchDependencies.gradle init` fails.

```
$ gradle -I gradle/support/fetchDependencies.gradle init
URL: https://github.com/pxb1988/dex2jar/releases/download/2.0/dex-tools-2.0.zip
   Connecting...
   Downloading: 2362460 of 2362460 (100%)
[...]
Copying vs2019_x86.fidb to /path/to/ghidra/dependencies/fidb
Copying vsOlder_x64.fidb to /path/to/ghidra/dependencies/fidb
Copying vsOlder_x86.fidb to /path/to/ghidra/dependencies/fidb

FAILURE: Build failed with an exception.

* Where:
Script '/path/to/ghidra/gradle/helpProject.gradle' line: 62

* What went wrong:
A problem occurred evaluating script.
> Could not find method helpIndexCompile() for arguments [javax.help:javahelp:2.0.05] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 31s
```

**To Reproduce**
1. Follow the instructions specified in the [build section of the README](https://github.com/NationalSecurityAgency/ghidra#build) until the `Download additional build dependencies into source repository` step.

**Expected behavior**
The build dependencies being installed

**Environment (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Java Version: OpenJDK 11.0.2

**Additional context**
 - Gradle version 7.0.1

**Comment by ryanmkurtz** [comment]
Duplicate of #2977.  Ghidra does not currently support Gradle 7.  Support is coming soon though.

**Comment by ryanmkurtz** [comment]
In the meantime, i'll fix up the readme to mention that only 5.x and 6.x are currently supported.
