### ISSUE TITLE
Ghidra Loaders doesn't support JRE 16

### ISSUE THREAD

**Issue by wbsdty331** [NationalSecurityAgency/ghidra#3030]
**Describe the bug**
When I want to disassemble something, the "format" option is only "Raw Binary". Maybe the JRE/JDK update broke the Ghidra loaders.

**To Reproduce**
1. Install Java JRE 16
2. Open Ghidra and import a file
3. the format is only `Raw Binary` , and you can see the error message:
![image](https://user-images.githubusercontent.com/4280572/118155332-b6a86180-b44a-11eb-90fe-7b33c10ae667.png)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4280572/118154698-f28ef700-b449-11eb-8462-75975a1b5a01.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10 19042
 - Java Version: 16.0 
![image](https://user-images.githubusercontent.com/4280572/118155172-852f9600-b44a-11eb-95a7-b4d991142cc4.png)
 - Ghidra Version: 9.2.3
 - Ghidra Origin: official repo

**Additional context**
I found a discuss topic in Reddit: https://www.reddit.com/r/ghidra/comments/mfr39k/issue_with_ghidra_pe_loader/
They said: 
> I have solved the issue. I noticed JDK updated in March. Apparently the JDK update from 15->16 broke the Ghidra loaders. I uninstalled JDK 16 and installed 15 and it's working perfectly now.

**Comment by ryanmkurtz** [comment]
Duplicate of 2879.  See the following comment to enable support for Java 16.

https://github.com/NationalSecurityAgency/ghidra/issues/2879#issuecomment-810161137
