### ISSUE TITLE
After populating a FID database, can errors be corrected in Library Family Name, Version, or Variant?

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#3031]
Short of starting over on a FID database to correct typos or other errors, I know of no tools for after-the-fact correction of **Library Family Name**, **Library Version**, or **Library Variant**. Would such be possible, or are those things interwoven, or hashed into a table somewhere, etc., so that it isn't practical? (The same is true for **Base Library**, but I can guess how changing that after the fact might not be feasible.)

_Originally posted by @gtackett in https://github.com/NationalSecurityAgency/ghidra/issues/2931#issuecomment-837238185_

**Comment by astrelsky** [comment]
Yes it can be done but there are no tools for it.

```java

FidFileManager man = FidFileManager.getInstance();
List<FidFile> files = man.getFidFiles();
// get your file
FidFile file = null; // this is your file
FidDB fidb = file.getFidDB(true);

// for a limited time only while this method is still public
DBHandle db = fidb.getDBHandle();
// Have fun changing what you need. Just make some backups first.
```

**Comment by gtackett** [comment]
I don't have the source code available on the system where I use Ghidra the most. What import path(s) do I need for that example, @astrelsky ?

Do we know when `FidDB.getDBHandle()` will be going away, or what can be done (if anything) once it's gone?

**Comment by astrelsky** [comment]
```
import ghidra.feature.fid.db.FidFileManager;
import ghidra.feature.fid.db.FidFile;
import ghidra.feature.fid.db.FidDB;
import db.DBHandle;
```

I woudn't actually say that the method would be going away. I only said "for a limited time only" because it seems to be something that shouldn't be public. Bad things can happen when you screw up messing with the database.
