### ISSUE TITLE
Difference between `getName()` and `getDisplayName()`

### ISSUE THREAD

**Issue by cdisselkoen** [NationalSecurityAgency/ghidra#3032]
The `DataType` interface (`ghidra.program.model.data.DataType`) has methods `getName()` and `getDisplayName()`. It's not clear from the docs what the difference is - [the docs](https://ghidra.re/ghidra_docs/api/ghidra/program/model/data/DataType.html) say for `getName()`, `Return that name of the data type` [sic], and for `getDisplayName()`, `Gets the name for referring to this data type.`.  `AbstractDataType`, which seems to be the parent for most `DataType`s, defines the two methods to be the same, but empirically, they don't always produce the same result for all datatypes (e.g., for `FunctionDefinitionDataType`, although I'm not sure why the difference exists or what the two names represent).  Can someone explain the difference?  I'm happy to make a PR to update the docs if that would make things clearer for future users.

**Comment by dragonmacher** [comment]
I examined the uses of both methods.  My observations:
* `getDisplayName()` simply returns the value of `getName()` by default.
* The only subclass that changes that behavior is the `PointerDataType`
* Both methods are used roughly equally in the system

Based on other places we use similar verbiage in method names, I'd say the intent was to allow for `getDisplayName()` to be the 'pretty print' version of the name.   The pointer is an example of this, adding a nicer display to the value of `getName()`.

I seem to vaguely recall us adding the `getDisplayName()` with the notion that eventually subclasses of `AbstractDataType` could/would create pretty versions of their base name.

**Comment by cdisselkoen** [comment]
Interesting.  Yeah, from brief inspection of the code I also thought `PointerDataType` is the only subclass that changes the behavior.  But, I have observed a case where `getPrototypeString()` on a `FunctionDefinitionDataType` contains a different function name than `getDisplayName()` on that same datatype.  (Wildly different, not just different formatting.)  `getPrototypeString()` internally just accesses the `name` field, which I believe is equivalent to calling `getName()`.  So I think this means that `getName()` and `getDisplayName()` give different results for the `FunctionDefinitionDataType` in my example.  I'll work on a minimal reproducer for this if that's helpful.  Could be an error on my end as well, or something related to the Python scripting environment, which I'm using.

**Comment by cdisselkoen** [comment]
I discovered the cause of my issue, it was a bug in my code and not actually a difference between `getName()` and `getDisplayName()`.  (Instead, my code was confusing `getDisplayName()` on a typedef with `getName()` on the typedef's base type, which are clearly different by intention.)  Closing this, sorry for the bother and thanks for the help.
