### ISSUE TITLE
Gradle detected a problem with the following location ...

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#3039]
"Gradle detected a problem with the following location: 'C:\Users\astre\Documents\ghidra-src\build\dist\ghidra_10.0_DEV'. Reason: Task ':createJavadocs' uses this output of task ':assembleDistribution_win64' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem."

**Environment (please complete the following information):**
 - Ghidra Version: 10.0_DEV 15d22e81643f4647fc2b985f61e44d9cdcee15da

**Additional context**
Still builds without a problem. Just think this may be useful information.

There is also this one line but I'm sure there will be a few years to ignore it: "Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0"

**Comment by Wall-AF** [comment]
I have found a similar issue with `gradle prepDev`.   Here's the DOS output:
```
Z:\GIT_Sources\Ghidra.Latest\ghidra>gradle prepDev

> Configure project :
Searching for latest Visual Studio and required components...
  -> Installation Directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
  -> VCTools Version (default): 14.28.29910
  -> SDK Directory (default): C:\Program Files (x86)\Windows Kits\10\
  -> SDK Version (default): 10.0.19041.0
  -> SDK Version (override): N/A

> Task :GhidraServer:generateDevGhidraServerClasspath FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'Z:\GIT_Sources\Ghidra.Latest\ghidra\Ghidra\Features\GhidraServer\build.gradle' line: 156

* What went wrong:
Execution failed for task ':GhidraServer:generateDevGhidraServerClasspath'.
> 'other' has different root

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 40s
74 actionable tasks: 31 executed, 43 up-to-date
```

**Environment**
Ghidra Version :10.0_DEV 296360eb3479e70eb734a2abf2eded06b84e3d69
O/S: Windows 10

**Comment by ryanmkurtz** [comment]
@Wall-AF, your issue seems unrelated and more serious.  Unfortunately I can't reproduce it.  Would you mind creating a new issue for it?

**Comment by xiaoyinl** [comment]
> I have found a similar issue with `gradle prepDev`. Here's the DOS output:
> 

I think this issue is similar to #2409. Cloning ghidra to a directory under C: drive should work.

**Comment by Wall-AF** [comment]
> I think this issue is similar to #2409. Cloning ghidra to a directory under C: drive should work.

I don't have enough disk space there, however, creating a `Directory Junction` worked.  Thanks.
