### ISSUE TITLE
about print out codeUnits.getbytes

### ISSUE THREAD

**Issue by anzosasuke** [NationalSecurityAgency/ghidra#3042]
I am trying to find an opcode so, I tried to print out the bytes of an instruction to get opcode, here is my program,
 for codeUnit in codeUnits:
		print("Address = 0x{} : bytes = {} : Insruction = {}".format(
			  codeUnit.getAddress().getOffset(),
			  ' '.join("%x" % b for b in list(codeUnit.getBytes())),
			  codeUnit.toString()))

but I am getting that bytes in negative hex. How do I get the same in positive or as in the same as that displays in codebrowser. 
Please help me

**Comment by astrelsky** [comment]
> I am trying to find an opcode so, I tried to print out the bytes of an instruction to get opcode, here is my program,
> ```python
> for codeUnit in codeUnits:
>     print("Address = 0x{} : bytes = {} : Insruction = {}".format(
>        codeUnit.getAddress().getOffset(),' '.join("%x" % b for b in list(codeUnit.getBytes())),
>        codeUnit.toString()))
> ```
> 
> but I am getting that bytes in negative hex. How do I get the same in positive or as in the same as that displays in codebrowser.
> Please help me

Arrays in jython are a bit wonky, most notably byte arrays. This seemed to do the trick:
```python
def code_unit_to_hex(cu):
    return cu.bytes.tostring().encode('hex')
print("Address = 0x{} : bytes = 0x{} : Insruction = {}".format(codeUnit.getAddress(), code_unit_to_hex(codeUnit), codeUnit))
```

Here is some example output:
`Address = 0x00101070 : bytes = 0x31ed : Insruction = XOR EBP,EBP`

**Comment by anzosasuke** [comment]
Thanks so much. That works.

**Comment by astrelsky** [comment]
> Thanks so much. That works. 

You're welcome, anytime.
