### ISSUE TITLE
Can I print out .text section of a binary from ghidra using headless or ghidrascript?? if so, how would i do it?

### ISSUE THREAD

**Issue by anzosasuke** [NationalSecurityAgency/ghidra#3043]
Can I print out .text section of a binary from ghidra using headless or ghidrascript?? if so, how would i do it?

**Comment by ryanmkurtz** [comment]
Duplicate of #3041

**Comment by astrelsky** [comment]
Yes. You can use `getMemoryBlock('.text')` to get the memory block. What you do from there is up to you. The real question is why would you want to do this?
