### ISSUE TITLE
Can not build on windows 10.0.19042 with Visual Studio 2019 (16.10.0 Preview 4.0)

### ISSUE THREAD

**Issue by xNxExOx** [NationalSecurityAgency/ghidra#3045]
**Describe the bug**
Build fails

**To Reproduce**
1. Try build on windows 10.0.19042 with Visual Studio 2019 (16.10.0 Preview 4.0)
2. See error

**Expected behavior**
Build succed

**Attachments**
```
$ gradle buildGhidra

> Configure project :
Searching for latest Visual Studio and required components...
  -> Installation Directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
  -> VCTools Version (default): 14.29.30036
  -> SDK Directory (default): C:\Program Files (x86)\Windows Kits\10\
  -> SDK Version (default): 10.0.19041.0
  -> SDK Version (override): N/A

> Task :createJsondocs
Execution optimizations have been disabled for task ':createJsondocs' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'F:\gh\ghidra-master_2021_05_18'. Reason: Task ':createJsondocs' uses this output of task ':createJavadocs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'F:\gh\ghidra-master_2021_05_18\build\tmp\jsondoc'. Reason: Task ':createJavadocs' uses this output of task ':createJsondocs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :Decompiler:compileDecompileWin64ExecutableDecompileCpp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Decompiler:compileDecompileWin64ExecutableDecompileCpp'.
> No tool chain is available to build for platform 'win64':
    - Tool chain 'visualCpp' (Visual Studio):
        - Could not locate a Visual Studio installation, using the command line tool, Windows registry or system path.
    - Tool chain 'gcc' (GNU GCC):
        - Could not find C compiler 'gcc' in system path.
    - Tool chain 'clang' (Clang):
        - Could not find C compiler 'clang' in system path.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 48s
151 actionable tasks: 43 executed, 108 up-to-date
```

**Environment (please complete the following information):**
 - OS: Windows 10.0.19042
 - Java Version: openjdk 11.0.9.1 2020-11-04
 - Ghidra Version: master (296360eb3479e70eb734a2abf2eded06b84e3d69)
 - Ghidra Origin: locally built\*

**Additional context**
I modify https://github.com/NationalSecurityAgency/ghidra/blob/296360eb3479e70eb734a2abf2eded06b84e3d69/GPL/vsconfig.gradle#L47-L47 as in https://github.com/NationalSecurityAgency/ghidra/pull/2305/files

I tried `gradle buildGhidra --debug`, but I did not see any new lines for the task `:Decompiler:compileDecompileWin64ExecutableDecompileCpp`

**Comment by ryanmkurtz** [comment]
There is a PR that might fix this for you: #2305

**Comment by xNxExOx** [comment]
Well I used absolute path as a constant, so that PR would remove that step, but it return same value, so something else is wrong, 
In dependencies is only:
> A C/C++ compiler - We use GCC on Linux, Xcode (Clang) on macOS, and Visual Studio (2017 or later) on Windows. 

So after some investigation, I have installed C++ for VS 2017, default for VS 2019 (from the preset), and latest versions, but still same error, so I do not think it is a missing dependency.

I also could not find any part of this error in the source code :(
```
Execution failed for task ':Decompiler:compileDecompileWin64ExecutableDecompileCpp'.
> No tool chain is available to build for platform 'win64':
    - Tool chain 'visualCpp' (Visual Studio):
        - Could not locate a Visual Studio installation, using the command line tool, Windows registry or system path.
```
So I have no clue which if causes the problem.

**Comment by topia** [comment]
@xNxExOx I think running gradle with debug options (--verbose? --debug? --trace?) will help to debug that part

**Comment by xNxExOx** [comment]
As I write I tried only `gradle buildGhidra --debug`, and there was no additional info.
It started Task `:Decompiler:compileDecompileWin64ExecutableDecompileCpp`
And next line was that Task `:Decompiler:compileDecompileWin64ExecutableDecompileCpp` failed.
I can post that, if you think there might be some clue I missed in previous tasks, or the cleanup. (Which one of these 3 is most verbose?, or should I enable all 3?)

**Comment by topia** [comment]
From the provided error message, the exception thrown from Gradle internal. So, you want to start looking from 
https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/DefaultVisualStudioLocator.java#L233

**Comment by xNxExOx** [comment]
```
2021-05-19T10:37:41.084+0200 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :Decompiler - Mutating components.decompile.binaries.linux64Executable using NativeBinaryRules#assignTools(NativeBinarySpec, NativeToolChainRegistryInternal, ProjectLayout)
2021-05-19T10:37:41.085+0200 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe''. Working directory: C:\Program Files (x86)\Microsoft Visual Studio\Installer Command: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -all -legacy -format json -utf8
2021-05-19T10:37:41.085+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
2021-05-19T10:37:41.085+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'.
2021-05-19T10:37:41.092+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
2021-05-19T10:37:41.093+0200 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe''
2021-05-19T10:37:41.093+0200 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
2021-05-19T10:37:41.143+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
2021-05-19T10:37:41.143+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'' finished with exit value 0 (state: SUCCEEDED)
2021-05-19T10:37:41.145+0200 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.version.SystemPathVersionLocator] No visual c++ compiler found in system path.
2021-05-19T10:37:41.146+0200 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.LegacyWindowsSdkLocator] Ignoring candidate Windows SDK directory C:\Program Files (x86)\Windows Kits\10 as it does not look like a Windows SDK installation.
2021-05-19T10:37:41.148+0200 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.LegacyWindowsSdkLocator] Could not find Windows resource compiler in system path.
2021-05-19T10:37:41.149+0200 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.AbstractWindowsKitComponentLocator] Found Windows SDK 10.0.18362.0 at C:\Program Files (x86)\Windows Kits\10
2021-05-19T10:37:41.149+0200 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.AbstractWindowsKitComponentLocator] Found Windows SDK 10.0.19041.0 at C:\Program Files (x86)\Windows Kits\10
2021-05-19T10:37:41.150+0200 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.AbstractWindowsKitComponentLocator] Found Windows SDK 10.0.18362.0 at C:\Program Files (x86)\Windows Kits\10
2021-05-19T10:37:41.150+0200 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.AbstractWindowsKitComponentLocator] Found Windows SDK 10.0.19041.0 at C:\Program Files (x86)\Windows Kits\10
```
even thou it is quite far from the error, I think this is the log that should be interesting.
it uses "`vswhere.exe -all -legacy -format json -utf8`", so Gradle internaly also searches for VS and does not find it, because it is not listed by default

**Comment by topia** [comment]
I hadn't noticed about preview versions. Yes, Gradle looks for vswhere too: [CommandLineToolVersionLocator](https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/version/CommandLineToolVersionLocator.java#L58)
I can't find any override methods for this line, so I suggest add the directory of "cl.exe" to the PATH environment and use [SystemPathVersionLocator](https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/msvcpp/version/SystemPathVersionLocator.java#L46)

**Comment by xNxExOx** [comment]
just tried to add:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30036\bin\Hostx64\x64\cl.exe`
and
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30036\bin\Hostx86\x86\cl.exe`
to path, but it did not help.
I needed to add the folder instead:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30036\bin\Hostx64\x64\`
and now it builds, I am not sure if I add the right one, but the build succeeded.
Thanks for helping me with finding a workaround, and I hope that you will find also a solution.

**Comment by astrelsky** [comment]
In my opinion this really should be more - robust. Why not use cmake? It comes with the visual studio c++ tools and is easy to set up on every other os.

**Comment by xNxExOx** [comment]
I never meet cmake that would just work and did not take over hour to set up :(

**Comment by ryanmkurtz** [comment]
Can you post your version of this output:
```
> Configure project :
Searching for latest Visual Studio and required components...
  -> Installation Directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
  -> VCTools Version (default): 14.24.28314
  -> SDK Directory (default): C:\Program Files (x86)\Windows Kits\10\
  -> SDK Version (default): 10.0.18362.0
  -> SDK Version (override): N/A
```

**Comment by xNxExOx** [comment]
It is in the first post, but to have it also here:
```
> Configure project :
Searching for latest Visual Studio and required components...
  -> Installation Directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
  -> VCTools Version (default): 14.29.30036
  -> SDK Directory (default): C:\Program Files (x86)\Windows Kits\10\
  -> SDK Version (default): 10.0.19041.0
  -> SDK Version (override): N/A
```

**Comment by ryanmkurtz** [comment]
Ah yes, sorry I missed that.  So are you thinking that Gradle doesn't yet support the preview version?

**Comment by xNxExOx** [comment]
yes, here is PR https://github.com/NationalSecurityAgency/ghidra/pull/2305 that "fixes" if for ghidra, but not for the gradle, which can be worked around with adding the path to folder containing `cl.exe` to `PATH` env variable.

**Comment by ryanmkurtz** [comment]
Ok, I'll go ahead and close this issue then, since there is nothing to fix in Ghidra.  PR #2305 can remain open.

**Comment by xNxExOx** [comment]
As I said before, I still think this is just a work around. But I hope debugger will be released before I will want any new version, so I will not need to build it myself again.
