### ISSUE TITLE
`gradle prepDev` fails with v7

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3047]
**Describe the bug**
`gradle prepDev` fails build process when the source is located on a drive other than `C:`.

NB. If you create a `Directory Junction` to effectively place the source on the `C:` drive (or presumably have it located there - can't test, no space) the build succeeds!

**To Reproduce**
1. Get latest source (commit 296360eb3479e70eb734a2abf2eded06b84e3d69)
2. Use build command `gradle prepDev`
3. See failure.

**Expected behavior**
To build without errors!

**Screenshots** - command line output
```
Z:\GIT_Sources\Ghidra.Latest\ghidra>gradle prepDev
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Searching for latest Visual Studio and required components...
  -> Installation Directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
  -> VCTools Version (default): 14.28.29910
  -> SDK Directory (default): C:\Program Files (x86)\Windows Kits\10\
  -> SDK Version (default): 10.0.19041.0
  -> SDK Version (override): N/A

> Task :GhidraServer:generateDevGhidraServerClasspath FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'Z:\GIT_Sources\Ghidra.Latest\ghidra\Ghidra\Features\GhidraServer\build.gradle' line: 156

* What went wrong:
Execution failed for task ':GhidraServer:generateDevGhidraServerClasspath'.
> 'other' has different root

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 5s
74 actionable tasks: 31 executed, 43 up-to-date
```

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 20H2 (19042.985)
 - Java Versions: 11.0.2 & 16.0.1
 - Ghidra Version: 10_DEV 
 - Ghidra Origin: locally built (commit 296360eb3479e70eb734a2abf2eded06b84e3d69)
 - Gradle Versions: 7.0.1 & 7.0.2

**Additional context**
The last `Gradle` version this worked with was 6.6.1, and that used JDK 11.0.2.  (Using JDK 11.0.2 with Gradle 7.x.x fails with Java errors.)

**Comment by ryanmkurtz** [comment]
Thanks, I was able to reproduce it.

**Comment by ryanmkurtz** [comment]
The issue is that `:GhidraServer:generateDevGhidraServerClasspath` assumes all of the jar dependencies can be gotten relative to where your Ghidra is located, but some of the jars reside in your gradle cache, which by default is in your home directory located on C:

Until we can properly address it, you can force gradle to use a cache location on the same drive that Ghidra resides on:

`gradle -g dependencies/gradle_cache prepDev`
