### ISSUE TITLE
Elf Header section is improperly named

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#3054]
**Describe the bug**
The program fragment containing the elf header is not properly named.

**To Reproduce**
1. Import an elf file
2. In the program tree see a fragment named something like "segment_0.1"

**Expected behavior**
It should be "_elfHeader" in a similar fashion as the "_elfSectionHeaders"

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19042.985]
 - Java Version: 15.0.2
 - Ghidra Version: 10.0_DEV

**Comment by ghidra1** [comment]
These fabricated block names are only used when the header is not contained within a loaded program header (i.e., segment) or section.

**Comment by astrelsky** [comment]
> This is by design.  These fabricated block names are only used when the header is not contained within a loaded program header (i.e., segment) or section.  All loadable program headers, not contained within a section, produce one or more memory blocks named "segment_#[.#]".
> 

So then why `_elfSectionHeaders` and `_elfProgramHeaders`?

**Comment by ghidra1** [comment]
> So then why `_elfSectionHeaders` and `_elfProgramHeaders`?

These are produced when the corresponding file region does not have a designated memory load address (see ElfProgramBuilder.findLoadAddress(fileOffset, headerSize) ).  We try to keep Program Headers (segments) intact which are loaded into memory giving precedence to named sections (Section Headers).  Generally the _elfHeader if loaded into memory will be at the minimum memory address making it easy to find, this is not the case if not-loaded where we create OTHER overlay blocks with names like segment_1 or unallocated_1.  Naming these special blocks in this case makes it easier to find them.
From the _elfHeader the _elfProgramHeaders and _elfSectionHeaders are easy enough to navigate to in all cases.

**Comment by astrelsky** [comment]
> > So then why `_elfSectionHeaders` and `_elfProgramHeaders`?
> 
> These are produced when the corresponding file region does not have a designated memory load address (see ElfProgramBuilder.findLoadAddress(fileOffset, headerSize) ). We try to keep Program Headers (segments) intact which are loaded into memory giving precedence to named sections (Section Headers). Generally the _elfHeader if loaded into memory will be at the minimum memory address making it easy to find, this is not the case if not-loaded where we create OTHER overlay blocks with names like segment_1 or unallocated_1. Naming these special blocks in this case makes it easier to find them.
> From the _elfHeader the _elfProgramHeaders and _elfSectionHeaders are easy enough to navigate to in all cases.

Ok. I'm wondering if I had just not explained myself well enough. You can see it by loading `ghidra_10.0_PUBLIC/Ghidra/Features/Decompiler/os/linux64/decompile`. The only one out of `ELF_HEADER_BLOCK_NAME`, `ELF_PROGRAM_HEADERS_BLOCK_NAME` and `ELF_SECTION_HEADERS_BLOCK_NAME` that gets a named fragment is `ELF_SECTION_HEADERS_BLOCK_NAME`. The elf header and program headers are left in the fragment `segment_2.1`. It is unsightly having this being the only one named this way when all the section names are present. It is in a loadable segment starting at the image base but doesn't have a corresponding section and only contains the elf header and program headers.

It's tough for me to judge whether this was supposed to be a covered scenario with faulty conditions or if I'm just nitpicking.

**Comment by ghidra1** [comment]
For the decompile binary, it manifested in this fashion because both the main _elfHeader and _elfProgramHeaders were placed into a loadable segment by the Gcc compiler and the _elfSectionHeaders were placed in the file at non-loaded offsets.  I have no idea why - I have seen it all.  In either case if you don't want to see the non-loaded content, which results in OTHER overlays such as the one you mention, you can disable the "Import Non-Loaded Data" import option which will omit these unsightly blocks.  Personally I find the section_#[.#] blocks more unsightly - but we try to be complete and we make up names when there are none to be had.
