### ISSUE TITLE
Can you open the Ghidra website to Israeli IP addresses?

### ISSUE THREAD

**Issue by dukase** [NationalSecurityAgency/ghidra#3065]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bendkaye** [comment]
Just build it from source https://github.com/NationalSecurityAgency/ghidra or use a VPN

**Comment by ryanmkurtz** [comment]
Duplicate of #1095

**Comment by ryanmkurtz** [comment]
Closing due it being a duplicate issue.  

See https://github.com/NationalSecurityAgency/ghidra/issues/1095#issuecomment-851008561 for an explanation and guidance.
