### ISSUE TITLE
TableChooserDialog.doExecute() selectedRows deficiency

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#307]
**Describe the bug**
In TableChooserDialog.doExecute(), the first step is to collect the selected rows into an int[], then iterate through this and call executor.execute() on each row.  Problem is that if the execution is not trivial, or if there are a large number of rows selected, it is possible to interact with the table through the GUI and do things like re-sort the table.  This then throws off the list of selected rows, so further execution continues on the wrong rows.

This might be better if selectedRows was built as a List<AddressableRowObject> as deletedRowObjects is.

Additionally, as an enhancement, it would be useful if the executor function had some way of adding additional rows to deletedRowObjects (although then it may need to be a set instead of a list to deal with duplicates).  In some scripts I have built, executing on some rows eliminate other rows from further consideration and I currently jump through hoops to get these rows deleted.

Finally, after selecting multiple rows and running the executor, the pattern of rows that was selected is not cleared, and remains in effect for the next time around.  But after the 2nd execution, it *is* cleared.  Not a big issue, just a puzzling inconsistency.
**To Reproduce**
Build a script where the executor performs a sleep, select the first 10 rows of the table, start execution, then re-sort the table in the reverse order.  After the resort, execution continues with the rows that are sorted into the selected positions, not the rows that were originally selected.

**Expected behavior**
The rows that were originally selected should be the rows that the executor runs against, regardless of any manipulation of the table.

**Environment (please complete the following information):**
 - OS: observed on linux, but not significant
 - Java Version: anything
 - Ghidra Version: all

**Comment by dragonmacher** [comment]
The original intent of this dialog was to give script writers the ability to easily present the user with a table of data, with the optional ability to perform work on any of those data.

Once any script becomes large and/or complex, we recommend that it be converted to a Plugin.   Plugins have access to more features in the framework, such as events, persistence, actions, etc.  Typically, to create a meaningful UI and service, a Plugin is required.

That being said, you have pointed out that the dialog's code is overly simplistic.   **I believe we should considrer making the following changes:**

    1. Update the doExecute() to work on Objects and not rely on row numbers
    2. Address the issue of queued elements still being available in the UI
    3. Add a method to the Dialog Chooser API to allow the script writer to remove elements from the results
