### ISSUE TITLE
Constant 128 being decompiled to -128

### ISSUE THREAD

**Issue by Muqi-Zou** [NationalSecurityAgency/ghidra#3070]
Here is the source code I compile: 
```
int main(void) {
	char temp3; 
	temp3 = getchar();
	if (temp3 < 128){
			return 123;		
		}
	return 1111;

}
```

The decompiled code is like following:
```
undefined4 main(void)

{
  int iVar1;
  undefined4 local_c;
  
  iVar1 = getchar();
  if ((char)iVar1 < -0x80) {
    local_c = 0x7b;
  }
  else {
    local_c = 0x457;
  }
  return local_c;
}
```
As you can see, the `  if ((char)iVar1 < -0x80) {` should be replaced with `  if ((char)iVar1 < 0x80) {`.
I checked the p-code lifted by ghidra, and it is correct.
(The p-code generated for `  if ((char)iVar1 < -0x80) {` is as followed:
```
        00401149 0f be 4d fb     MOVSX      ECX,byte ptr [RBP + local_d]
                                                      $U3100:8 = INT_ADD RBP, -5:8
                                                      $Ubb00:1 = LOAD ram($U3100:8)
                                                      ECX = INT_SEXT $Ubb00:1
                                                      RCX = INT_ZEXT ECX
        0040114d 81 f9 80        CMP        ECX,0x80
                 00 00 00
                                                      CF = INT_LESS ECX, 0x80:4
                                                      OF = INT_SBORROW ECX, 0x80:4
                                                      $U28000:4 = INT_SUB ECX, 0x80:4
                                                      SF = INT_SLESS $U28000:4, 0:4
                                                      ZF = INT_EQUAL $U28000:4, 0:4
                                                      $U12c00:4 = INT_AND $U28000:4, 0xff:4
                                                      $U12c80:1 = POPCOUNT $U12c00:4
                                                      $U12d00:1 = INT_AND $U12c80:1, 1:1
                                                      PF = INT_EQUAL $U12d00:1, 0:1
        00401153 0f 8d 0c        JGE        LAB_00401165
                 00 00 00
                                                      $Ucd00:1 = INT_EQUAL OF, SF
                                                      CBRANCH *[ram]0x401165:8, $Ucd00:1
```
)

I checked the source code of ghidra then, I note that when dealing the `ECX = INT_SEXT $Ubb00:1` at `00401149`, `RuleSubvarSext::applyOp`  will be called to deal with the varnode related to constant 0x80 at `00401153`. 

From my notice, for some reason , 0x80 will be interpreted to 0x7f in `RuleSubvarSext::applyOp`. (I believe converting  "a < b" to "a > b-1" may make later decompiling easier)

By the following function process:
`RuleSubvarSext::applyOp` ([code](https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/Decompiler/src/decompile/cpp/ruleaction.cc#L7931))->
`SubvariableFlow::doTrace` -> 
`SubvariableFlow::processNextWork` ->
`SubvariableFlow::traceForwardSext` ->
`SubvariableFlow::createCompareBridge`-> 
`SubvariableFlow::ReplaceVarnode ` ->
`*SubvariableFlow::setReplacement`([code](https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc#L63))
, the return value of SubvariableFlow::setReplacement, when passing 0x7f, is "[addConstant((ReplaceOp *)0,mask,0,vn->getOffset());](https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc#L86)" 

However, when "128" is replaced with a bigger number like "158" ("9d"(158-1) will be passed in), the return value of above function process will be ["return (ReplaceVarnode *)0;"](https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc#L84)

Hence, I replaced 
`      if (sextval != cval)` at [line 83](https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc#L83)
with
` if (sextval != cval || sextval == uintb(127))`
The decompiled result turns correct.

I am pretty sure my modification is not a good solution for this issue. I also observe that when the constant value in the "if condition" is less than 128, sometimes, it will be decompiled to its corresponding char character. I am not quite sure how these observations will affect the result. But, I believe there must be some better way to solve this issue.

My OS is : ubuntu 18.04
JDK version :11.0.8
Ghidra Version: 10.0
Ghidra Origin: locally built, commit version: 68a9c0a5a37f26e3c5bc1085ee91aa4041ea7510

**Comment by mumbel** [comment]
Valid char range from -0x80 to 0x7f, your C is broken as every char is less than 128, but `(char)128` is -0x80

**Comment by Muqi-Zou** [comment]
I see your points. I agree that conditions like `(char a < 128 or any number larger than 128 )` should always be true. However, I do not think it makes sense to me that, for `char a`, both `if (a < 128) {` and `if (a < -128) {` will be decompiled to
```
char iVar;
if ((char)iVar1 < -0x80) {
```

**Comment by Muqi-Zou** [comment]
Alright, I double checked the rules used to decompile the constant and have the following found (correct me if I made any mistake there):
It looks like when ghidra has two different decompiling processes when facing the char type constant and int type constant. When dealing with `a< 128`, the RuleIntLessEqual treat 128 as a int type constant, it will convert `a< 128` to `a< =127` by replacing the varnode etc. However, 127 is in range of char, and in RuleSubvarSext,  127 is treated as a char type constant...
My above modification at line 83 should not be the correct way to solve this issue... Not sure how to correctly solve this.

**Comment by Muqi-Zou** [comment]
Btw, I am not talking about the integer promotions issue here. I know that `if (temp < 128)` is different from `if (temp < (char)128)` since the binary. Ghidra did a good job in lifting IR code from binary, it just messes up when decompiled the IR to c code.

**Comment by Muqi-Zou** [comment]
After reviewing the process, here is the whole picture:
Following _Rulesborrow_, following pcode  
```
...
OF = INT_SBORROW ECX, 0x80:4, 
$U28000:4 = INT_SUB ECX, 0x80:4,
SF = INT_SLESS $U28000:4, 0:4,
...
$Ucd00:1 = INT_EQUAL OF, SF
```
will generate a new pcode: `INT_SLESSEQUAL  0x80,ECX`,  _Ruleintlessequal_ will then be applied, we then have pcode `INT_SLESS 0x7f, ECX`. The _RuleSubvarSext_, being applied on `ECX = INT_SEXT $Ubb00:1`, notices that the constant changed from 0x80 to 0x7f. It then changes the size of varnode representing 0x7f from 4 bytes to 1 byte. Finally, in _ActionPreferComplement_, it changes the condition from sless to slessequal, 0x7f is added by one. However, the size of the constant is not enlarged from 1 byte to 4 bytes.  That is why in PrintC::pushConstant, 0x80 is considered as -128 in char rather than 128 in int.
The fundamental problem here is we should not change the size varnode from 4 bytes to 1 byte in rulesubvarsext. But, fixing this will be hard. One easy way I will say is do some changes in [_Rulintelessequal_](https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/Decompiler/src/decompile/cpp/ruleaction.cc#L600). Note that in the comment:
```
/// \class RuleIntLessEqual
/// \brief Convert LESSEQUAL to LESS:  `V <= c  =>  V < (c+1)`
```
But this rule also allows:
`c <= V  =>  c-1 < V`
By adding a check, whether the right side of the input op is a constant, should make the implementation strictly follow the comment:
```
  if (op->getIn(1)->isConstant()){
    if (data.replaceLessequal(op))
    return 1;
  }
  return 0;
```
This will not affect the correctness of this rule and solve the above bug as well.

**Comment by Muqi-Zou** [comment]
Just saw this, nice change!
