### ISSUE TITLE
GDB debugger: `info proc mappings` does not work with a remote and/or system-level debugger

### ISSUE THREAD

**Issue by DrChat** [NationalSecurityAgency/ghidra#3071]
Ghidra's GDB agent depends on the `info proc mappings` command to map memory addresses to Ghidra files.
However, this command does not work with a system-level debugger exposing a GDB server (such as qemu).

In the event that GDB's `info proc mappings` command fails, Ghidra should have a fallback method that allows the dynamic disassembly listing to continue working. At a minimum, the dynamic disassembly listing should be populated using basic memory queries via GDB.
Additionally, users should be able to have an option to synchronize the dynamic and static listings. This would be useful in systems where the virtual address always lines up with the base address specified for a Ghidra program, such as those running on bare metal systems.

I'd appreciate this support, because I commonly use Ghidra to reverse-engineer binaries running on bare metal systems :)

**Comment by d-millar** [comment]
There's a script in Debug/Debugger/src/main/resources called define_info_proc_mappings. Try modifying the script to match your address space (e.g. 32-bit values) and execute it from the Interpreter or the launch command.  (We realize this isn't ideal, but it should get you over that hurdle.)

**Comment by DrChat** [comment]
Ah - perfect! That seems to make Ghidra a little bit happier, but I'm still seeing a blank Dynamic view (as well as all the views on the right side of the screen).
The objects view shows accurate information though - and I even see my binary in the `Memory` tree.

**Comment by d-millar** [comment]
So, the thing to keep in mind is that only the Interpreter & Objects view are responding directly to the underlying debugger engine.  The other views are really responding to the information in the current trace.  For the Dynamic view to be active, several things have to be in place.  The first, as you've surmised, is there has to be some mapping between memory and the trace.  Second, the Threads view has to be populated and a thread selected.  Third (and this often gets out of whack), the caret on the right hand side of the Threads' view has to be pointing to a valid snap/time in the trace.  Fourth, well, tracing better be on.  The reason for all of this is the Dynamic view represents the view of memory for a given thread and a given time, i.e. if it changes, the view reflects that.  Self-modifying code, user mods to memory, structures laid down in memory, changes to heap, stack, etc. will be reflected (on a good day) in that view.  Not sure which thing is missing for you, but give us what details you have - we'll help you get it working.

**Comment by DrChat** [comment]
Thanks for the explanation - it's helpful!
Ah, I found the specific bug:

## Working
```
(gdb) set endian big
(gdb) target remote 127.0.0.1:9001
```

## Not working
```
(gdb) target remote 127.0.0.1:9001
(gdb) set endian big
```

Specifically, this is a `powerpc:common` target. Typically PowerPC is big endian, but our target XML (transferred over the GDB protocol) does not specify that so we have to set endianness manually.

**Comment by d-millar** [comment]
Excellent - nice catch!  Keep us posted - am sure something else will break, but....we're here!

**Comment by DrChat** [comment]
Of course! I'm excited for this debugger 😀

**Comment by DrChat** [comment]
P.S: Do you guys have a Discord / IRC / other official chat channel?

**Comment by d-millar** [comment]
Unfortunately, no.  This is the most official channel we have.  There is Ghidra Discord/Telegram channel, with plenty of good advice/info, but we have no connection to it.
