### ISSUE TITLE
I am trying to read .text section but don't know how to read from the input mem block  data stream

### ISSUE THREAD

**Issue by anzosasuke** [NationalSecurityAgency/ghidra#3075]
after using getMemoryBlock('.text'), I got the DB@address of .text mem block input stream. I can't use getByte as it is iterable and don't really know how to read from the section.

offset = 1052832
size = 533
data_in = getMemoryBlock('.text').getData()
data = data_in.read(byte[] b, 1052832, 533) .. I have no idea if this is the right way.. but this doesn't work

**Comment by dev747368** [comment]
MemoryBlock.getData() returns a java InputStream.  It's [read(byte[], int, int)](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[],%20int,%20int)) method probably isn't what you want as the offset value is the offset into the byte array of where to put the data being read, not the file offset.

If you use skip() on the InputStream to seek to the location you want to read from, you could then use read(my_byte_array, 0, 533) to read 533 bytes into the array.  (as long as my_byte_array already existed and was at least 533 bytes long)

**Comment by astrelsky** [comment]
You can utilize `java.nio.ByteBuffer.allocate(size).array()` to easily get a java byte array in jython.

**Comment by astrelsky** [comment]
You can utilize `java.nio.ByteBuffer.allocate(size).array()` to easily get a java byte array in jython.

**Comment by anzosasuke** [comment]
I tried different ways but wasnt able to get it. 
my program looks like this:
`from java.nio import ByteBuffer
from ghidra.program.model.mem import MemoryBlock
def make_byte_array(size):
	return ByteBuffer.allocate(size).array()

blocks = currentProgram.getMemory().getBlocks()

dot_text = getMemoryBlock('.text')
# print(dot_text.getData().toString())
# print(dot_text.getSize())
size1 = dot_text.getSize()
data_in = dot_text.getData()
addr =dot_text.getStart()

b = make_byte_array(size1)


# data = data_in.skip(0x1010a0)

# print(data)
data = data_in.read(b, 0, 533)
print(data)`

I tried both read and skip, but only "533" as output. I am doing something majorly wrong here. 

I just wanted to print out the .text section from headless. Like this for example... 
 0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000580  31ed 4989 d15e 4889 e248 83e4 f050 544c  1.I..^H..H...PTL
0x00000590  8d05 ba01 0000 488d 0d43 0100 0048 8d3d  ......H..C...H.=
0x000005a0  0c01 0000 ff15 2e0a 2000 f40f 1f44 0000  ........ ....D..
0x000005b0  488d 3d79 0a20 0048 8d05 790a 2000 5548  H.=y. .H..y. .UH
0x000005c0  29f8 4889 e548 83f8 0e76 1548 8b05 fe09  ).H..H...v.H....
0x000005d0  2000 4885 c074 095d ffe0 660f 1f44 0000   .H..t.]..f..D..
0x000005e0  5dc3 0f1f 4000 662e 0f1f 8400 0000 0000  ]...@.f.........

**Comment by dev747368** [comment]
@anzosasuke if you take a look at the docs for the read() call (I linked it in my reply a few days ago), you can see for yourself that the return value of read() is just the number of bytes that were successfully read from the stream.

In your case, you are assigning that value to 'data', and its telling you that it successfully read 533 bytes into the 'b' variable that you created earlier.

You should be looking at 'b' to get the bytes that you read from the stream.

**Comment by anzosasuke** [comment]
Thanks @astrelsky  and @dev747368 . I got to read .text section from there. But I got it in negative hex. Is there any way to change it to positve hex. The b is integer array.. encode('hex') didn't work.. hex(dot_text) gives me negative.. doing %x gives me negative hex as well. Any other way to get it postive??

**Comment by astrelsky** [comment]
> Thanks @astrelsky  and @dev747368 . I got to read .text section from there. But I got it in negative hex. Is there any way to change it to positve hex. The b is integer array.. encode('hex') didn't work.. hex(dot_text) gives me negative.. doing %x gives me negative hex as well. Any other way to get it postive??

`b & 0xff`?

**Comment by anzosasuke** [comment]
Oh thank you so much .. It worked now.
