### ISSUE TITLE
Cannot change datatype of existing data (must clear and re-create)

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#3077]
**Describe the bug**
In the listing window, if I try to change the datatype of existing data, the choose data type window accepts the new datatype, but the data is unchanged.  I have to clear the existing data before I can set it.

**To Reproduce**
Create a data object, say a pointer to an int.
With the cursor on the existing data, type 't' or Data->Choose Data Type
choose "char *" as the new data type.

**Expected behavior**
The "int *" datatype should be changed to "char *", but instead it remains "int *" unless I clear the data first, then set it to "char *"

 - Ghidra Version: 9.2.2
 - Ghidra Origin: official ghidra-sre.org distro,

**Comment by dragonmacher** [comment]
This code has changed a bit in master.  Now when you try to apply a type over existing data, you should be prompted to overwrite the data.

**Comment by marcushall42** [comment]
Good enough..  I know it *used* to just change the datatype on earlier versions.  I was just getting frustrated with this version seeming to accept the change, but silently ignoring it.
