### ISSUE TITLE
Updating struct through decompiler window does not set the changed flag

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#3078]
**Describe the bug**
Examining code in the decompiler window that uses a field within a structure, if I type 'l' over a field within the structure, I can re-name the field.  The structure editor shows the updated name correctly, but the datatype manager does not turn on the indicator to update the structure to the archive.  Presumably this is because the datatype changed notification is lost or not set.  This can lead to problems with the datatype and archive being out of sync.

**To Reproduce**
In the decompiler window, examine code that references a field within a structure that was copied from a datatype archive such as:

a = foo_struct.bar;

Over the "bar", type "l" and rename "bar" into "barX".

If the structure editor is opened on "foo_struct", it will show the field properly named "barX".

The datatype manager window will show foo_struct in the program but will not show the right arrow to indicate that it has changed and needs to be committed back to the archive.

**Expected behavior**
The right arrow should be displayed by the datatype manager and the datatype should know that it needs to be committed to the archive.

 - Ghidra Version: 9.2.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by ghidra1** [comment]
I believe this was corrected with the refactor which was done for Ghidra 10.0.  Could you please verify that your issue reported has been resolved.  Thanks.

**Comment by marcushall42** [comment]
Yes, it looks fine now.
