### ISSUE TITLE
Link project to Ghidra error

### ISSUE THREAD

**Issue by stephengeorgewest** [NationalSecurityAgency/ghidra#3087]
When I run LinkProject I get 

> IllegalArgumentException: Path must include project and resource name: /org.eclipse.buildship.core.gradleclasspathcontainer

I saw in the eclipse log it was happening at :
>	at ghidradev.ghidraprojectcreator.utils.GhidraProjectUtils.linkGhidraToProject(GhidraProjectUtils.java:392)

full stack trace:

> java.lang.reflect.InvocationTargetException
> 	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
> 	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1033)
> 	at ghidradev.ghidraprojectcreator.wizards.LinkGhidraWizard.performFinish(LinkGhidraWizard.java:68)
> 	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
> 	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
> 	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
> 	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
> 	at org.eclipse.jface.window.Window.open(Window.java:799)
> 	at ghidradev.ghidraprojectcreator.commands.LinkGhidraCommand.execute(LinkGhidraCommand.java:37)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
> Caused by: java.lang.IllegalArgumentException: Path must include project and resource name: /org.eclipse.buildship.core.gradleclasspathcontainer
> 	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
> 	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2122)
> 	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
> 	at ghidradev.ghidraprojectcreator.utils.GhidraProjectUtils.linkGhidraToProject(GhidraProjectUtils.java:392)
> 	at ghidradev.ghidraprojectcreator.wizards.LinkGhidraWizard.link(LinkGhidraWizard.java:103)
> 	at ghidradev.ghidraprojectcreator.wizards.LinkGhidraWizard.lambda$0(LinkGhidraWizard.java:69)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
> Root exception:
> java.lang.IllegalArgumentException: Path must include project and resource name: /org.eclipse.buildship.core.gradleclasspathcontainer
> 	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
> 	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2122)
> 	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
> 	at ghidradev.ghidraprojectcreator.utils.GhidraProjectUtils.linkGhidraToProject(GhidraProjectUtils.java:392)
> 	at ghidradev.ghidraprojectcreator.wizards.LinkGhidraWizard.link(LinkGhidraWizard.java:103)
> 	at ghidradev.ghidraprojectcreator.wizards.LinkGhidraWizard.lambda$0(LinkGhidraWizard.java:69)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

I'm guessing it is the second use of getFolder in that class:
https://github.com/NationalSecurityAgency/ghidra/blob/68a9c0a5a37f26e3c5bc1085ee91aa4041ea7510/GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin/src/main/java/ghidradev/ghidraprojectcreator/utils/GhidraProjectUtils.java#L391-L392

`<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
`
I think my .class file was generated when I opened the folder in VSCode. I'm not sure that the line
> <classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
is an invalid entry. The issue could probably be avoided by pulling the `IFolder entryFolder` inside the `if (entry.getEntryKind() == IClasspathEntry.CPE_SOURCE` check.
https://github.com/NationalSecurityAgency/ghidra/blob/68a9c0a5a37f26e3c5bc1085ee91aa4041ea7510/GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin/src/main/java/ghidradev/ghidraprojectcreator/utils/GhidraProjectUtils.java#L393

Workaround:
1. remove that line from the .classpath file
2. run "Link Ghidra..."
3. readd teh line to .classpath file

**Comment by ryanmkurtz** [comment]
Is the XML you posted your `.classpath` file before you tried to link ghidra to your project?  Was this a project you had created outside of the GhidraDev project creation wizards?

**Comment by stephengeorgewest** [comment]
Yeah, I cloned a project from github ( I guess that counts as created), then poked around in vsCode, then opened it up in eclipse a bit later to do the linking.
