### ISSUE TITLE
Debugger fails to load DLLs

### ISSUE THREAD

**Issue by Vovix** [NationalSecurityAgency/ghidra#3090]
**Describe the bug**
When attempting to start a debug session, the debugger fails to import some DLLs and does not launch.
 
**To Reproduce**
1. Select Windows executable in the project, click "Open With" -> "Debugger"
2.  Click "Debugger"->"Debug Executable.exe"-> "In dbgeng locally" (either option), then click "Connect"

**Expected behavior**
The target is launched and can be debugged.

**Screenshots**
The error output:
![debugbug](https://user-images.githubusercontent.com/7648798/120254960-d065e900-c23f-11eb-9185-716c5d7fca9f.PNG)

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Java Version: [JRE 1.8, JDK 15]
 - Ghidra Version: [10.0 BETA]
 - Ghidra Origin: [official] 

**Additional context**
dbghelp.dll and ntdll.dll are present on the system.

**Comment by d-millar** [comment]
@Vovix Hi and apologies for the delayed response.  Basically your issue is that system dlls can't be loaded on the fly, i.e. dlls in the Sytem32 folder.  Same issue as #2585.  The easy solution is to download the SDK or the debugging package.  If you prefer not to do that, I'd suggest copying the dbgXxx.dlls out to another location and modifying your path to pull those first.

**Comment by Vovix** [comment]
I do have the windows SDK with windbg installed. Is there something special I need to do for Ghidra to use it?

**Comment by Vovix** [comment]
I tried the "copy it out solution", even with the new location at the top of PATH, it's still trying to load the system32 version. Does Ghidra have its own search path I need to specify somewhere?

**Comment by d-millar** [comment]
Hmmm, good questions.  There's some stuff involved here that honestly I don't completely understand.  The JDK loads it's own version of dbgeng.dll, and that has implication for the other dlls.  Try this - I think this "has to" work although it's certainly not a great solution - take the contents of the windbg/SDK bin directory (the one with dbgeng, dbgmodel, dbghelp, etc) including the subdirs and copy them into C:\Program Files\Amazon Corretto\jdk_11.0.4_10\bin (your path to the the JDK may differ).  Then give it another shot and let me know what happens!

**Comment by d-millar** [comment]
Also, I should mention per comments by @jpoiret the jna.library.path and java.library.path are relevant and might provide a cleaner solution.  We just haven't quite worked out what it should be.

**Comment by Vovix** [comment]
Moving the DLLs to the JDK folder seems to work.

**Comment by d-millar** [comment]
Excellent - will keep you posted if we come up with a better embedded-path solution

**Comment by d-millar** [comment]
Closing this as #3019 essentially covers the same ground.

**Comment by d-millar** [comment]
NB: ping @Vovix if we ever find better resolution
