### ISSUE TITLE
Demangle Symbol> Unable to demangle symbol: _Z5threev.  Message: java.io.FileNotFoundException: os/win64/demangler_gnu.exe does not exist

### ISSUE THREAD

**Issue by zswaaa** [NationalSecurityAgency/ghidra#3099]
When i use the ghidra.jar on windows to decompile a .so file ,no functions  was demangled .And i get some error in the process.
For example:
Demangle Symbol> Unable to demangle symbol: _Z5threev.  Message: java.io.FileNotFoundException: os/win64/demangler_gnu.exe does not exist
Now i wonder to know 
1, why i get this error,and i build the jar by  buildGhidraJar.bat which the offical offered.
2, how can i solve this problem.
thank you very much

**Comment by zswaaa** [comment]
****

**Comment by topia** [comment]
Did you look at DevGuide? I think your problem covered in it.
https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md#building-the-natives

**Comment by zswaaa** [comment]
> Did you look at DevGuide? I think your problem covered in it.
> https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md#building-the-natives

Thank you.I find something in buildGhidraJarREADME,

**Comment by ryanmkurtz** [comment]
@zswaaa  What version of Ghidra did you use to build your `ghidra.jar` file?

**Comment by ryanmkurtz** [comment]
@zswaaa Nevermind, I was able to reproduce the problem.

**Comment by ryanmkurtz** [comment]
This has already been fixed in 10.0.  Note that `ghidra.jar` is broken for another reason in the 10.0-BETA release, so unfortunately you can't get the fix for this until the final version of 10.0 comes out.

**Comment by zswaaa** [comment]
@ryanmkurtz Thank u, OK, I will wait the 10.0. Good job.
