### ISSUE TITLE
UI and mouse navigation on displays with high refresh rate is sluggish

### ISSUE THREAD

**Issue by codecat** [NationalSecurityAgency/ghidra#31]
**Is your feature request related to a problem? Please describe.**
I'm running on a 144hz monitor, on which the mouse & UI respond very sluggishly (as if it were actually running at 60hz).

**Describe the solution you'd like**
For the program to support high refresh rates.

**Describe alternatives you've considered**
I considered just using this on a 60hz display, but I'd prefer to use my bigger 144hz display.

**Additional context**
OS: Windows 10 1803
Display: LG 34UC88-B 34" (with GSync on)

**Comment by codecat** [comment]
I actually don't seem to have the issue in the latest release of Ghidra at all. I have recently been messing around with Gsync options though (having the same issue in programs like Cubase), so that might have something to do with it.

**Comment by ryanmkurtz** [comment]
Ok, thanks for following up.  I'll go ahead and close the ticket.
