### ISSUE TITLE
TableChooserDialog immediately closes

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#3103]
**Describe the bug**
`TableChooserDialog` sometimes immediately closes when created from a `GhidraScript` with `getScriptAnalysisMode` overridden to return `AnalysisMode.DISABLED`

**To Reproduce**
1.) Override the analysis mode of a `GhidraScript` with `AnalysisMode.DISABLED`
2.) Create a simple table dialog and call `tableDialog.show()`.
3.) The first few times running the script, the `tableDialog` immediately closes.

**Expected behavior**
Table dialog should persist

Ghidra 10.0_DEV (master)

**Comment by dragonmacher** [comment]
I can reproduce the issue.   Working on a fix.
