### ISSUE TITLE
[Decompiler] Improve ActionDeindirect.

### ISSUE THREAD

**Issue by homes410** [NationalSecurityAgency/ghidra#3104]
**Describe the bug**
When the analysis of function is triggered by ActionDeindirect, not all overrides are not added to funcData, causing *exceeded maximum restart* warning is displayed in decompiler output because of not all overrides are added in previous analysis run.
Below patch addressed the problem.

**Attachments**
[0001-210604.patch.txt](https://github.com/NationalSecurityAgency/ghidra/files/6596814/0001-210604.patch.txt)

**Environment (please complete the following information):**
 - Ghidra Version: [9.2.2]

**Additional context**

**Comment by caheckman** [comment]
Its not clear how delaying the installation of overrides in this way helps with an "Exceeded maximum restarts..." exception.  Do you have an example function?

**Comment by homes410** [comment]
> Its not clear how delaying the installation of overrides in this way helps with an "Exceeded maximum restarts..." exception. Do you have an example function?
No, you don't need to *delay* installation. just call insert override *without condition* would work.
for explanation of `without condition', see below.

*function of actiondeindirect before this patch.
Make restriction on varnode. if fails, make pending restart.
for failed restriction, insert override on Funcdata.

*function of actiondeindirect after this patch.
Make restriction on varnode. if fails, make pending restart.
if there is any restart pending on Funcdata
 just put indirect, proto override to Funcdata regardless whether the restriction succeed.

**Comment by caheckman** [comment]
I believe I am reproducing this now.  Please try this patch.
[deindirect.txt](https://github.com/NationalSecurityAgency/ghidra/files/7107403/deindirect.txt)

**Comment by homes410** [comment]
> I believe I am reproducing this now. Please try this patch.
> [deindirect.txt](https://github.com/NationalSecurityAgency/ghidra/files/7107403/deindirect.txt)

I'm using this patch and found no issue related to #3104 so far.

**Comment by ryanmkurtz** [comment]
I am going to keep this open until the patch gets incorporated into source control.
