### ISSUE TITLE
[Decompiler] infinite decompilation time for a small function

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#3105]
Ghidra infinitely tries to decompile `unpack_linerep` function. This is my project for `BETA 10.0`.
[bad_func.zip](https://github.com/NationalSecurityAgency/ghidra/files/6600267/bad_func.zip)

**Comment by homes410** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc#L2300-L2305

[0001-210704.patch.txt](https://github.com/NationalSecurityAgency/ghidra/files/6759594/0001-210704.patch.txt)

Please don't hesitate to experiment above patch onto a decompiler.
Best regards.

**Comment by lab313ru** [comment]
How is it supposed to work?
```
  if (iter == enditer)
    return false;
  while(iter != enditer) {
```

**Comment by lab313ru** [comment]
It still doesn't work, and behavior is the same.

**Comment by lab313ru** [comment]
It never lives the loop in https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/decompile/cpp/action.cc#L348:
```
int4 Action::perform(Funcdata &data)
```

**Comment by lab313ru** [comment]
How is it related to doubles? My code doesn't contain double variables at all.

**Comment by caheckman** [comment]
The name of the file double.cc refers to "double precision" variables. Single variables stored across 2 or more registers.  Your example had them set as the return value on several functions.  Basically the decompiler transforms RuleDoubleIn and RuleSplitFlow were undoing each others work, causing an infinite loop.
