### ISSUE TITLE
Handle the importing and disassembling of .COM files more intelligently

### ISSUE THREAD

**Issue by volkertb** [NationalSecurityAgency/ghidra#3107]
**Is your feature request related to a problem? Please describe.**

Currently, when you import a .COM file in Ghidra, it detects it as being in `Raw Binary` format. That means that for these kind of files, the user has to select the correct language from a list, and manually set the starting offset (Base Address) to `0x100` under the `Options...` button. 

However, it should be perfectly possible for Ghidra to handle all of this automatically.

I know .COM files are of a bygone era, but as someone who likes to tinker with retro stuff I would appreciate this. :relaxed:

**Describe the solution you'd like**

There are some assumptions that can be reasonably made, regarding binary files with the `.COM` extension:

- COM files are either 8086 MS-DOS executables (`x86:LE:16:Real Mode:default`) or 8080/Z80 CP/M executables (`z80:LE:16:default:default`).
- In either case, COM files are supposed to be mapped to an offset of `0x100`.

So with these assumptions, it should be possible to improve Ghidra so that it detects the actual language, simply by assuming a base address of `0x100` and then disassembling the binary twice, once in 8086 opcodes, and once in 8080/Z80 opcodes. In most cases, one of those decodings will have invalid opcodes, which means the other decoding is likely the correct one. For increased efficiency, Ghidra could immediately stop the initial disassembly as soon as it encounters an invalid opcode, and then try the other.

This way, both the base address and the language should be detected automatically and preset in the Import options. That would be `0000:0100` in the case of `x86:LE:16:Real Mode:default` and `ram: 0100` in the case of `z80:LE:16:default:default`.

Also, in the `Format` field, a more specific format name could then be shown, such as `MS-DOS COM executable` or `CP/M COM executable`, instead of the generic `Raw Binary`.

**Describe alternatives you've considered**

Well, continuing to do it manually, which works, but is inconvenient, and error-prone. 😅

**Additional context**

![Screenshot from 2021-06-05 14-33-59](https://user-images.githubusercontent.com/518023/120891864-2b665a00-c60b-11eb-8cb1-118f41756ff0.png)

Thanks for considering this! :slightly_smiling_face:

**Comment by prino** [comment]
Just a question, once it's loaded, does Ghidra actually allow you to change the .COM into what's in essence a multi-segmented .EXE, like in the case of Pascal programs compiled with Turbo Pascal V1/2/3? 

"That" program can do this without any problem, and in fact I'm currently working on an script that can be used to recreate the code and data segments of such (Turbo Pascal V3.01a) .COM files (using the information set up by the compiler) and follows that by disassembling the code and data from the RTL inserted by the compiler - feel free to PM me for a copy, my website in my profile has contact details. The script works in the freeware version.

As for your suggested disassemble twice approach, this might fail on programs that intersperse code and data, something that's done very frequently in TP 1/2/3 generated programs:
```
cseg:1C26 sinpush:
cseg:1C26                 jmp     repush
cseg:1C26 ; ---------------------------------------------------------------------------
cseg:1C29 fltsin          db  58h, 9Dh, 39h, 9Fh, 3Fh,0D7h ; -1 / 15!
cseg:1C2F                 db  60h, 43h, 9Dh, 30h, 92h, 30h ;  1 / 13!
cseg:1C35                 db  67h,0AAh, 3Fh, 28h, 32h,0D7h ; -1 / 11!
cseg:1C3B                 db  6Eh,0B6h, 2Ah, 1Dh,0EFh, 38h ;  1 /  9!
```
or in the case of, and I have a quite a few of them, TP3 programs with inline coded 386(+) instructions. In other words, let the user decide, don't over-automate things.

**Comment by ryanmkurtz** [comment]
A new loader would have to be written to handle .COM files.  This requires a few steps:

1) Detecting that the file is a .COM file (ignoring extension)
2) Detecting the architecture
3) Mapping the file bytes into Ghidra's memory address space.
4) Other optional things like creating symbols, performing relocations, etc.

Can you describe how steps 1) and 2) can be achieved by examining the bytes of a .COM file?  From what I just read, .COM files have no header or metadata.

**Comment by prino** [comment]
There isn't really any way of reliably detecting that a file is a DOS or CP/M .COM file, and one of the most extraordinary examples is http://ideology.com.au/polyglot/ , a file that's just plain text, but rename it as polygrot.com, and it's a working .COM file. Another extreme example? A one byte file containing a 0xc3 (x86 retn instruction)

Realistically, you have to look at the extension, the size should be less than 65k - 256 bytes, and it should not start with two bytes containing "MZ" (or "ZM"), but that's about it. Just load polyglot.com into Ghidra, tell Ghidra that it's a 16-bit x86 .COM file and disassemble it, most of the generated assembler code is a total load of nonsense...

My humble advice? Don't waste your time on this.

**Comment by ryanmkurtz** [comment]
Those constraints are too broad to us to write a loader...we would get too many false positives.  My best piece of advice to save time is to use the headless analyzer to import your .COM file, specifying the processor on the command line, and a prescript/postscript to do any fix ups that you would want automated.

**Comment by astrelsky** [comment]
> Those constraints are too broad to us to write a loader...we would get too many false positives.  My best piece of advice to save time is to use the headless analyzer to import your .COM file, specifying the processor on the command line, and a prescript/postscript to do any fix ups that you would want automated.  

You could do something similar to how the "detection" is set for the raw bytes loader. Have it be an option, just not the first one.

**Comment by ryanmkurtz** [comment]
> You could do something similar to how the "detection" is set for the raw bytes loader. Have it be an option, just not the first one.

That would be the best we could do, but I don't think we'd be able to justify that Loader showing up as a choice for every binary, when it's such a rare thing to import.  You'd still have to pick the processor too.

**Comment by volkertb** [comment]
Indeed, .COM files have no headers or markers.

So do I understand that there is no simple approach like "disassembling it in architecture A yields sensible code, disassembling it in architecture B does not, so therefore we have just detected architecture A"?

At the end of the day, this request is purely for convenience, and yes, admittedly, for a niche use case. 

But if it's mostly the architecture detection part that's impractical, let's put that part aside then.

Would you consider just letting Ghidra automatically preset the default offset to 0x100 (`0000:0100`) whenever a binary file with a .com extension *and* a file size of less than `64 kilobytes minus 256 byes` is being imported?

**Comment by ryanmkurtz** [comment]
> So do I understand that there is no simple approach like "disassembling it in architecture A yields sensible code, disassembling it in architecture B does not, so therefore we have just detected architecture A"?

Correct, Ghidra relies on header information or a user selection to know what architecture to use. This all happens before disassembly.

> Would you consider just letting Ghidra automatically preset the default offset to 0x100 (0000:0100) whenever a binary file with a .com extension and a file size of less than 64 kilobytes minus 256 byes is being imported?

No, I feel like introducing a loader that keys off of only those 2 constraints would do more harm than good.  Perhaps if the loader offered a lot more capabilities it might be worth it, but if it's just setting the base address, you writing a little `GhidraScript` and possibly combining it with the headless analyzer seems like the best way to go to improve your workflow.

**Comment by SamB** [comment]
How much would it really hurt things to have such a loader show up in the dropdown *after* "Raw Binary", though? It could really save a lot of time wading through the umpteen variants of x86 ...

**Comment by matthewturk** [comment]
This is awesome -- thank you!
