### ISSUE TITLE
SourceArchive implementations should have an equals() method

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#3116]
**Is your feature request related to a problem? Please describe.**
The implementations of SourceArchive (SourceArchiveDB and BuiltinSourceArchive) do not implement an equals() method, so it defaults to Object.equals().  At issue is whether the SourceArchive found from the Program should be equal to the SourceArchive from the DataTypeManagerService?  They may have the same name (and I have learned the hard way to compare names and not the SourceArchive object itself!)
Perhaps they should be distinct and different.  Which one is returned by DataType.getSourceArchive()?

**Describe the solution you'd like**
Perhaps I'm overly frustrated by my code failing because SourceArchive.equals() didn't match what I thought should.  Object.equals() isn't my idea of "sameness", at least right now.

**Describe alternatives you've considered**
I have reverted to comparing SourceArchive.getName().equals() instead of SourceArchive itself.  This seems to be what I want, but it's all too easy to believe that SourceArchive.equals() is what I want.

**Comment by marcushall42** [comment]
Okay, perhaps a .equals() should compare UniversalID and name (since the name is settable).  Maybe there should be an isEquivalent() method that compares UniversalIDs only?  Maybe both?  It just seems that .equals() is too attractive to use without thinking and Object.equals() isn't what I was expecting.

**Comment by ryanmkurtz** [comment]
Reverted by d9788c0094d63661eb5bfa9364e5d3bd5d1338dc

**Comment by dragonmacher** [comment]
We decided in the end not to do this now, as there are some subtleties with this API that implied a change like this would need more thought.  Closing the ticket, since there is a workaround.
