### ISSUE TITLE
Persistent selection of Analysis Options

### ISSUE THREAD

**Issue by hochl** [NationalSecurityAgency/ghidra#312]
**Is your feature request related to a problem? Please describe.**
When analyzing a new binary you always have to select the same options by hand (f.e. :decompiler Parameter ID").

**Describe the solution you'd like**
Ghidra could remember the selection from last time, or, maybe better, make the checkboxes have 4 settings: `off`, `on`, `off and disable by default` and `on and enable by default`.

**Comment by adamopolous** [comment]
Hey @hochl , thanks for the suggestion - this is certainly something that could be improved. Right now the enabled/disabled setting are remembered for a particular program but like you said, won't affect other programs you analyze in the future. 

We'll take a look and see if there's a nice way to allow users to do what you're suggesting.

**Comment by ryanmkurtz** [comment]
Fixed by da3a80f4fe86a7ddae8951366fa19f658fcb3fb3
