### ISSUE TITLE
What is ?? mark means in CodeBrowser, is this mean invalid instruction ? 

### ISSUE THREAD

**Issue by ratsafalig** [NationalSecurityAgency/ghidra#3127]
I'm now trying to dissemble a `.so` file and I found a function like this :  

![image](https://user-images.githubusercontent.com/33503055/121656098-b5159c00-cad1-11eb-85cc-bce29a23dbfa.png)

But when I follow `FUN_004d9300`, this is what I found  

![image](https://user-images.githubusercontent.com/33503055/121656193-d5455b00-cad1-11eb-977e-77e8a82a6e00.png)

Now here is what puzzled me :  

- what is a `undefined __cdecl xxx`, specifically what is so called `undefined` function
- what is `??` mark shown in address `004d9e00`, is `??` mean invalid instruction ? If `??` do means invalid instruction, why can the program jump to a address with a invalid instruction still managed to run properly?  

Any suggestions would me huge appreciated

**Comment by astrelsky** [comment]
Clear that `align` and disassemble at the function entry point. Something wierd happened there.

**Comment by ratsafalig** [comment]
I'm new to this software, could you please tell me how to do so ... Thanks, Thanks !!

**Comment by topia** [comment]
move cursor to `align` line and run Clear Bytes from the context menu, and move cursor to the first line of function, `004d9e00`, and disassemble.
You may want to see [cheat sheet](https://ghidra-sre.org/CheatSheet.html) for frequently used operations.

**Comment by ratsafalig** [comment]
Thanks a lot
