### ISSUE TITLE
Address Overflow in subtract when loading elf with overlays

### ISSUE THREAD

**Issue by ethteck** [NationalSecurityAgency/ghidra#3128]
**Describe the bug**
There seems to be an error loading some kinds of elfs with overlapping ram regions:
`Address Overflow in subtract: .battle_item_dizzy_dial_lib::802a1cc0 - 0xcc0`

**To Reproduce**
1. Open ghidra and any project
2. Attempt to import the elf in [problematic.zip](https://github.com/NationalSecurityAgency/ghidra/files/6639669/problematic.zip) with any language option

**Expected behavior**
The elf is successfully loaded

**Environment:**
 - OS: Windows 10
 - Java Version: 11.0
 - Ghidra Version: 9.x or 10.x
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**
linker script to generate said elf (names and paths simplified):

```
SECTIONS
{
    .section1 0x802A1CC0 : AT(0x7285D0)
    {
        a/lib.c.o(.text);
    }

    .section2 0x802A1000 : AT(0x728EC0)
    {
        b/lib.c.o(.text);
        b/1.png.o(.data);
    }
}
```

We have observed that changing line 611 in `MemorySectionResolver.reconcileSectionRangeOverlap` as follows fixes the problem:

from `fileRange.rangeStartAddress.add(...`
to `fileRange.rangeStartAddress.addWrap(...`

**Comment by ghidra1** [comment]
While addWrap may squash the exception it is likely producing a bad result.  I will need to investigate further.

**Comment by ghidra1** [comment]
@ethteck, Could you please provide the stack trace produced by the error.

**Comment by ethteck** [comment]
Sure thing:
```
Address Overflow in subtract: .battle_item_dizzy_dial_lib::802a1cc0 - 0xcc0
ghidra.program.model.address.AddressOutOfBoundsException: Address Overflow in subtract: .battle_item_dizzy_dial_lib::802a1cc0 - 0xcc0
	at ghidra.program.model.address.AbstractAddressSpace.add(AbstractAddressSpace.java:446)
	at ghidra.program.model.address.OverlayAddressSpace.add(OverlayAddressSpace.java:18)
	at ghidra.program.model.address.GenericAddress.add(GenericAddress.java:237)
	at ghidra.app.util.opinion.MemorySectionResolver.reconcileSectionRangeOverlap(MemorySectionResolver.java:611)
	at ghidra.app.util.opinion.MemorySectionResolver.allocateSectionMemory(MemorySectionResolver.java:509)
	at ghidra.app.util.opinion.MemorySectionResolver.resolveSectionMemory(MemorySectionResolver.java:280)
	at ghidra.app.util.opinion.MemorySectionResolver.resolve(MemorySectionResolver.java:261)
	at ghidra.app.util.opinion.ElfProgramBuilder.load(ElfProgramBuilder.java:130)
	at ghidra.app.util.opinion.ElfProgramBuilder.loadElf(ElfProgramBuilder.java:100)
	at ghidra.app.util.opinion.ElfLoader.load(ElfLoader.java:153)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:349)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:88)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2020-Dec-29 1701 EST
Ghidra Version: 9.2.2
Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.10.9-hotspot
JVM Version: AdoptOpenJDK 11.0.10
OS: Windows 10 10.0 amd64
Workstation: 192.168.2.104
```

**Comment by ghidra1** [comment]
Could you please tryout the following fix, updating the lines in MemorySectionResolver around line 610.   The change is at the spot you pointed out and requires performing the `add` against the physical address and not the overlay address.

```
				// Perform address computation in physical space
				Address rangeStartAddr =
					fileRange.rangeStartAddress.getPhysicalAddress()
							.add(filePos - fileRange.rangeStartFileOffset);

				// Ignore use of overlay and compare physical address for match to avoid duplication
				if (!expectedRangeStart.getPhysicalAddress().equals(rangeStartAddr)) {
					// File load memory range does not correspond to target memory range
					if (conflictGapStart == null) {
						conflictGapStart = expectedRangeStart;
					}
					conflictGapEnd = expectedRangeStart.add(rangeSize - 1);
				}
```

**Comment by ethteck** [comment]
I tried that fix, and it appears to be working! I'll update my PR, but feel free to close it or whatever if you're implementing this fix elsewhere. As an aside, the elf loading is taking quite a long time now, as it seems to be very slow at discarding sections:

`DEBUG Removing discardable alignment/filler segment at ...`
It has to do this dozens of times, and there's a couple seconds between each one. I assume this may have to do with building it in a debug environment, but I thought I'd mention it anyway.

**Comment by ghidra1** [comment]
For me, the entire import takes only about 1 second and here is all the log output I get:
DEBUG Elf symbol table section .symtab linked to string table section .strtab   (ElfHeader.java:744) 
DEBUG Loading block .data at 802a1510 from file offset 70928   (ElfProgramBuilder.java:3227) 
DEBUG Loading block .battle_item_egg_missile at 802a1000 from file offset 69632   (ElfProgramBuilder.java:3227) 
DEBUG Loading block .rodata at 802a20b0 from file offset 8368   (ElfProgramBuilder.java:3227) 
DEBUG Loading block .reginfo at 802a2090 from file offset 8336   (ElfProgramBuilder.java:3227) 
DEBUG Loading block .battle_item_dizzy_dial_lib at 802a1cc0 from file offset 7360   (ElfProgramBuilder.java:3227) 
DEBUG Loading block segment_1.1 at 802a0000 from file offset 0   (ElfProgramBuilder.java:3227) 
DEBUG Loading block segment_1.2 at 802a1000 from file offset 4096   (ElfProgramBuilder.java:3227) 
DEBUG Loading block segment_1.4 at 802a20a8 from file offset 8360   (ElfProgramBuilder.java:3227) 
DEBUG Loading block .shstrtab at OTHER:00000000 from file offset 193989   (ElfProgramBuilder.java:3227) 
DEBUG Loading block .strtab at OTHER:00000000 from file offset 167704   (ElfProgramBuilder.java:3227) 
DEBUG Loading block .symtab at OTHER:00000000 from file offset 134488   (ElfProgramBuilder.java:3227) 
DEBUG Loading block .mdebug at OTHER:00000000 from file offset 73872   (ElfProgramBuilder.java:3227) 
DEBUG Loading block unallocated_1 at OTHER:00000000 from file offset 194105   (ElfProgramBuilder.java:3227) 
DEBUG Loading block unallocated_0 at OTHER:00000000 from file offset 8384   (ElfProgramBuilder.java:3227) 
DEBUG Removing discardable alignment/filler segment at unallocated_0::00000000   (ElfProgramBuilder.java:268) 
DEBUG Removing discardable alignment/filler segment at unallocated_1::00000000   (ElfProgramBuilder.java:268) 
DEBUG Loading block _elfSectionHeaders at OTHER:00000000 from file offset 194108   (ElfProgramBuilder.java:3227)

**Comment by ethteck** [comment]
The elf I attached here was a just the most minimal thing I could create that reproduces the issue. Our actual full elf for the project is 84 MB, so it's orders of magnitude larger. I'll try again testing outside of the Eclipse context and see if that changes anything. If not, I'll investigate and maybe submit a new issue

**Comment by ghidra1** [comment]
What is the total time for import (without analysis)?  I would suspect the import time would primarily be impacted by the total number of sections and program headers.  In addition, The time to inspect all bytes in candidate filler fragments (255-bytes or smaller each) could take some time along with their actually removal.  When both sections and program headers are present the memory section resolver is attempting to economize on defined memory blocks and discard leftover program header (i.e., segments) fragments which only contain 0's.

**Comment by ethteck** [comment]
I just timed the import, and it took 18 minutes. I think it emitted about 1000 of these debug prints about filler segments: 
![image](https://user-images.githubusercontent.com/2985314/122324705-38b50a00-cf64-11eb-9f16-c46c928393ce.png)
It's not the end of the world since we don't need to often import the elf over and over, but it was much faster (a matter of seconds) in 9.x.

If it's helpful, I could upload an elf with bogus data. I can't send the original, unfortunately, but it shouldn't matter for this.

**Comment by ghidra1** [comment]
I assumed the original failure would have existed in 9.x, preventing you from importing with 9.x.  Or are you referring to samples which did not trigger the failure case?

A larger sample would help for the purpose of profiling to identify the hotspot(s).  Off the top of my head I can't recall any big ELF import change for 10.0 that would cause this - but I wouldn't be the first time my memory has failed me.   I will have to review changes made this year which could impact the performance.  It may also be worth comparing a 10.0 clean import against a 9.x import to see if the results differ in someway.

**Comment by ethteck** [comment]
Both the elf I attached here and our large one triggered the failure case, which is now fixed from the patch you gave me. Unrelatedly, the large elf now takes a long time to load. I'll try to get a larger elf later today.

**Comment by ethteck** [comment]
It may be easier if I just can get you the actual elf. Do you have an email address I can send a google drive link to? The email in my github profile works.
