### ISSUE TITLE
Program:Win32/Uwamson.A!ml  in Ghidra_10.0_Beta

### ISSUE THREAD

**Issue by Nic4712** [NationalSecurityAgency/ghidra#3131]
file: F:\...\Downloads\ghidra_10.0-BETA_PUBLIC_20210521\ghidra_10.0-BETA_PUBLIC\Ghidra\Debug\Framework-Debugging\os\win32\expCreateThreadExit.exe

mfg

**Comment by magneticflux-** [comment]
Just got the same warning for `ghidra_10.0_PUBLIC\Ghidra\Debug\Framework-Debugging\os\win32\expCreateThreadSpin.exe`. Why did you close the original?

**Comment by ryanmkurtz** [comment]
Duplicate of #3160
