### ISSUE TITLE
Feature request: Frida as debugging agent

### ISSUE THREAD

**Issue by Manouchehri** [NationalSecurityAgency/ghidra#3134]
I often use Ghidra to assist with writing [Frida](https://frida.re/) scripts for Android targets. 

Would be incredibly handy if Ghidra used Frida as a debugging backend (instead of gdb), so I could dynamically instrument (and modify) functions _while_ reverse engineering with Ghidra at the same time. =)

(While it technically "works", it's way too messy to use Frida in a target that's also being debugged by gdb at the same time.)

**Comment by d-millar** [comment]
@Manouchehri  Frida wasn’t in the queue, but not a bad suggestion - thanks!
