### ISSUE TITLE
Expose GhidraLauncher Classpath Completion

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#3138]
**Is your feature request related to a problem? Please describe.**
In order to have the classpath filled out for Ghidra you can currently do a few hacky things.
* Copy the code from `GhidraLauncher`,
* Glob all the jar files in `{GHIDRA_INSTALL_DIR}/Ghidra` and add them. This will miss extensions and other things.
* Implement `GhidraLaunchable` to "launch" Ghidra. 

**Describe the solution you'd like**
Expose the classpath completion code via a static method in either a utility class or in `GhidraLauncher`.

**Additional context**
This could be used for a wide variety of things from ide plugins to projects that wish to use Ghidra as a java library.

**Comment by ryanmkurtz** [comment]
So you just want an easy way to get the classpath that Ghidra is using?  The `GhidraClassLoader` updates the `java.class.path` system property as it adds things.  

Or, are you not wanting to go through the `GhidraClassLoader`?  In this case it sounds like you want the functionality of the single big jar that the `buildGhidraJar` script produces, but using all the individual module jars instead of the 1 big jar.  Is that right?

**Comment by astrelsky** [comment]
> So you just want an easy way to get the classpath that Ghidra is using? The `GhidraClassLoader` updates the `java.class.path` system property as it adds things.
> 
> Or, are you not wanting to go through the `GhidraClassLoader`? In this case it sounds like you want the functionality of the single big jar that the `buildGhidraJar` script produces, but using all the individual module jars instead of the 1 big jar. Is that right?

Yes that seems about right. I want to be able to use Ghidra as a typical user would have it installed. I want to only have to add one thing to the classpath and then invoke the method and have it filled out. From there it could be dumped and exported or all of ghidra could be used in a program or something.

**Comment by ryanmkurtz** [comment]
This is basically the idea behind `GhidraLaunchable`.  You just need to add `Utility.jar` to your classpath, then launch `GhidraLauncher.main()`, passing in your `GhidraLaunchable` as its first command line argument.  You do need to also pass in the `GhidraClassLoader` as a JVM argument for this to work though.

However, `GhidraLauncher` could easily be refactored to have a public static method that returns the list of classpath entries that will get added to the `GhidraClassLoader` and `java.class.path`.

**Comment by astrelsky** [comment]
> This is basically the idea behind `GhidraLaunchable`. You just need to add `Utility.jar` to your classpath, then launch `GhidraLauncher.main()`, passing in your `GhidraLaunchable` as its first command line argument. You do need to also pass in the `GhidraClassLoader` as a JVM argument for this to work though.
> 
> However, `GhidraLauncher` could easily be refactored to have a public static method that returns the list of classpath entries that will get added to the `GhidraClassLoader` and `java.class.path`.

Right. I basically want everything loaded and ready to go, but I don't actually want to do anything.

```java
public class GhidraLaunchableImpl implements GhidraLaunchable {

    @Override
    public void launch(GhidraApplicationLayout layout, String[] args) {
        // do nothing
    }
}
```
