### ISSUE TITLE
p-code emulator has no meaningful error when monitor is None

### ISSUE THREAD

**Issue by wburton-intel** [NationalSecurityAgency/ghidra#3139]
**Describe the bug**
When using the EmulatorHelper (ghidra.app.emulator.EmulatorHelper) to step through p-code using Python, if the monitor passed in is None (rather than using the default monitor) the emulator will apparently step successfully, but the instruction pointer will not increment and getEmulateExecutionState() will return 'FAULT'.

Identical behavior is seen in GUI and headless mode.

**To Reproduce**
Use the script from https://github.com/HackOvert/GhidraSnippets#emulating-a-function to emulate (any) code, replacing the line:
success = emuHelper.step(monitor)
with 
success = emuHelper.step(None)

**Expected behavior**
A meaningful error message should be available somewhere, preferably through getLastError(). In addition the return value from step(xxx) should be False, not True.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: OpenJDK 14.0.1
 - Ghidra Version: 9.1.2
 - Ghidra Origin: official repo

**Additional context**
N/A

**Comment by ghidra1** [comment]
You must specify a monitor (null is not permitted).  If this is the case you may be getting an internal NullPointerException.  You should use TaskMonitor.DUMMY instead of null.  Unclear what you meant by "None" for task monitor.

**Comment by wburton-intel** [comment]
The internal NullPointerException doesn't get propagated to the Jython interface, so there is no error reported when using the code snippet above when using Python's None (which is, as you say, approximately the same as null). The request was to do some input validation and trigger an error if the user attempts to pass null/None rather than relying on the NullPointerException as debugging this issue took several hours in the larger codebase that I was using.

**Comment by ghidra1** [comment]
It may be better in this case just to handle the null monitor

**Comment by ghidra1** [comment]
I have put a fix in for 10.0.3
