### ISSUE TITLE
DataTypeChooserDialog.setFilterFieldEditable() doesn't set isFilterEditable

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#3140]
**Describe the bug**
The DataTypeChooserDialog contains an isFilterEditable property that affects the behavior of the getFocusComponent() method.  It also contains a setFilterFieldEditable() method that does invoke tree.setFilterFieldEnabled(), and annoyingly forces the filter to EXACT_MATCH if it is not enabled.  But, it never changes the local property isFilterEditable.

This is actually a minor ramification of setFilterFieldEditable() side-effects.  it should only do what it says, and shouldn't affect the filter strategy.  It would be more useful to have a separate method 'getFilterProvider()' that returns tree.getFilterProvider() so that the user may set the filter to whatever they desire.

Along the same lines, it seems that setFilterText() should not assume that if the text is non-null that it should not be editable.

**Comment by dragonmacher** [comment]
This is confusing for sure.  The feature was originally intended to allow clients to set filter text on the widget.  Once set, the end user would then not be allowed to change the text, hence making the field not editable.    This old feature could be implemented with a direct API that allows clients to control both the current filter text and the editable state.

Am I correct in assuming that you would like the API updated such that setting the filter text and the enablement state are separate concerns?

**Comment by marcushall42** [comment]
The name of the method doesn't imply that it affects the editable state, so that would argue that it shouldn't.  I would be fine with that if I could get ahold of the FilterProvider so that I could modify that.  The combined actions are just a little surprising from the name alone.

In my case, I was wanting to allow the user to select one of multiple implementations of a structure, so I wanted to pre-set the text to "myStruct_V" and then they could pick between "myStruct_V0", "myStruct_V1", etc.  So, I want to pre-set the text but still allow the user to finish off the selection.  As I recall, I think I resorted to reflection to get ahold of the FilterProvider, so just implementing a "getFilterProvider()" method would be sufficient.
