### ISSUE TITLE
Remove a circular reference of KeyedSoftReference

### ISSUE THREAD

**Issue by homes410** [NationalSecurityAgency/ghidra#3141]
DBObjectCache have non-static nested class named KeyedSoftReference.
I eventually found out that just making this class static improves response time of ghidra.
Please apply this patch for reliving excess gc pressure.
[0001-210617-inner-class-considered-harmful.patch.txt](https://github.com/NationalSecurityAgency/ghidra/files/6666224/0001-210617-inner-class-considered-harmful.patch.txt)

I don't know about exact inner working of jvm to tell you about. 

I know lifetime of an instance of non-static inner class became dependent to a referenced instance, and there is no way to remove a reference of outer instance from an instance of non-static nested class. and an instance of non-static nested class from DBObjectCache will be still reachable from GC root as long as an instance of DBObjectCache is reachable from GC root(*it's the case ghidra had encountered in*).

**Comment by astrelsky** [comment]
You can submit a pull request for this. I've already taken a look at it and the changes seem good.

**Comment by dragonmacher** [comment]
I see no issue with the change.    How were you able to observe the update's impact on performance?

**Comment by homes410** [comment]
I have a script written in python that replaces type of field from vtable structure. I can see there is less time spent in execution of the script. before this change the script did use to trigger outofmemory Error..
