### ISSUE TITLE
Decompiler Data Type Display Blocks Scalar Operand Display

### ISSUE THREAD

**Issue by Marsfan** [NationalSecurityAgency/ghidra#3142]
**Describe the bug**
When the Data Type Display popup is enabled for the decompiler, mousing over scalar values no longer shows the Scalar Operand Display, but instead show information about the data type casting being performed

**To Reproduce**
1. Open a program.
2. Select a function in the listing.
3. Right click on the decompiler window and select properties. 
4. Ensure that _Decompiler Popups->Data Type Display_ and _Decompiler Popups->Scalar Operand Display_ are enabled. 
5. Close properties
6. Mouse over a scalar value in the decompiler view
7. Notice that the scalar operand details display does not show up, but information about the variable size and type does.
8. Right click on the decompiler window and select properties. 
9. Uncheck _Decompiler Popups->Data Type Display_
10. Close Properties
11. Mose over a scalar value in the decompiler view
12. Notice that the Scalar Operand Display is now shown. 

**Expected behavior**
Both Data Type and Scalar Operand Display are shown simultaneously. 

**Screenshots**
Click to expand

<details> 
<summary> With both options enabled  </summary>

![image](https://user-images.githubusercontent.com/9311953/122343210-1347e200-cf0b-11eb-922b-2ce0c9527cdc.png)

</details>

<details>
<summary> With only Scalar Operand Display Selected </summary>

![image](https://user-images.githubusercontent.com/9311953/122343369-3e323600-cf0b-11eb-9c59-c71cbc8c1551.png)

</details>

<details> 
<summary> Conceptual display of both at once </summary>

![image](https://user-images.githubusercontent.com/9311953/122343848-c6184000-cf0b-11eb-814f-c6fef48503a9.png)

</details>

**Environment (please complete the following information):**
 - OS:  Windows 10 21H1
 - Java Version: 11.0.9.1
 - Ghidra Version: 9.2.3
 - Ghidra Origin: ghidra-sre.org download

**Comment by ryanmkurtz** [comment]
Fixed by 1726b680a865b09bbf80c500e878f7985f99a5c3
