### ISSUE TITLE
Mach-O library calls not handled properly

### ISSUE THREAD

**Issue by BlueAmulet** [NationalSecurityAgency/ghidra#3146]
**Describe the bug**
I'm working with a 32bit mach-o file, in the assembly view I can see various libstdc++.6.dylib calls such as `_ZNSolsEm` which should be `std::ostream::operator<<(unsigned long)`
It seems like Ghidra didn't handle any of the imports correctly, the `__jump_table` section is filled with garbage instructions and none of the functions there are demangled.
In the assembler view, I only see mangled names, and in the decompiler view, I get a generic `func_0x0005d251()`

**Expected behavior**
Library calls should be demangled and show up properly in both the assembler and decompiler views.

**Screenshots**
![2021-06-17_183427](https://user-images.githubusercontent.com/43395286/122488470-c01d7000-cf9a-11eb-9648-1ef8ff2b73e6.png)
![2021-06-17_183421](https://user-images.githubusercontent.com/43395286/122488502-cc093200-cf9a-11eb-96d7-827aaf7d0c18.png)

**Environment:**
 - OS: Windows 10 64bit 2004 (19041.928)
 - Java Version: Java 11
 - Ghidra Version: 10.0-BETA
 - Ghidra Origin: Official website

**Comment by ryanmkurtz** [comment]
Can you attach your binary?

**Comment by BlueAmulet** [comment]
Apologies for the close and open, accidentally clicked the button. Here is the binary
[x86binary.zip](https://github.com/NationalSecurityAgency/ghidra/files/6718777/x86binary.zip)

**Comment by ryanmkurtz** [comment]
Thanks, we'll take a look.

**Comment by ryanmkurtz** [comment]
We are incorrectly performing relocations over top of the jump table.  I am doing some redesign which will include a fix.

**Comment by ryanmkurtz** [comment]
The jump table corruption has been fixed in ac0d7f6d43dc88346f8450648251cba511f0ddff, but the demangling is still not happening because the symbols are not in the global namespace.

**Comment by ryanmkurtz** [comment]
Closed by 0b8365c679fefd4abf66cfcf0745fae7f6e87602
