### ISSUE TITLE
Can not create a pointer to a function pointer for C++ class methods

### ISSUE THREAD

**Issue by danielmoos** [NationalSecurityAgency/ghidra#3149]
**Describe the bug**
Trying to create a pointer to a function pointer in the Structure Editor yields the error "invalid bitfield specification: :" for a C++ class method

**To Reproduce**
1. In the Symbol Tree window create a class called Class1
2. In the Data Type Manager window create a structure called Class1
3. In the Data Type Manager window create a function definition "void Class1::handle(int a)" with __thiscall calling convention 
4. In the Data Type Manager window create a new structure and try to add a pointer to the function pointer Class1::handle * as field
5. Ghidra displays the error "invalid bitfield specification: :"

**Expected behavior**
Be able to create a field with the data type Class1::handle * *

**Environment (please complete the following information):**
 - OS: Debian 10
 - Java Version: 11.0.9.1
 - Ghidra Version: 9.2.2
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**
Without the Class1:: prefix I'm able to create a pointer to the function pointer, e.g. creating the function definition "void handle(Class1 *this, int a)" allows me to create the pointer handle * * to the function pointer

**Comment by astrelsky** [comment]
The DataTypeManager currently has no concept of namespaces and cannot handle `::` outside of of a template parameter. I'm surprised it accepted the function definition containing `::`. For now just leave off the `::`. The `this` parameter should get properly set when the definition is applied to a function or the pointer is dereferenced.

**Comment by danielmoos** [comment]
Okay, thank you for the clarification!
