### ISSUE TITLE
Feature Request: Multiline Textbox Popup Accessible From Script

### ISSUE THREAD

**Issue by philzook58** [NationalSecurityAgency/ghidra#3150]
We are building some python scripts that need ~10 lines of user input at multiple assembly locations. The `askString` method is very convenient and nice, but the textbox does not allow multiple lines or even copy and pasted newlines. This makes it basically unreadable and unusable for our purposes.

One alternative is to possibly use Ghidra comments instead of a popup as our text input method, but this is a hacky and strange solution that will be less intuitive to a user. Another alternative is to build a full fledged Ghidra plugin, but this is a much larger project.

I thought I'd ask, since perhaps this is a relatively easy feature to add or there may be some other workaround.

Thanks, 
Phil

**Comment by astrelsky** [comment]
You might want to tweak the title a bit. At first I thought the multi line text box was going to be used for scripting.

Out of sheer curiosity, what sort of user input is expected? I think you can build tables for user input with the scripting api and am wondering if this would be fitting here.

As far as a multiline `askString` goes I don't think it would be too difficult.

**Comment by philzook58** [comment]
The user input in this case is a language for writing patches and specifying what they should do. The project is largely external to Ghidra, but we're looking into if there is a nice convenient way to invoke it from Ghdira.

Thanks for the tip on the tables, I was not aware of the functionality. I'm guessing you're referring to this https://ghidra.re/ghidra_docs/api/ghidra/app/script/GhidraScript.html#createTableChooserDialog(java.lang.String,ghidra.app.tablechooser.TableChooserExecutor)  I don't think it quite fits what we want, but I'm having a hard time figuring out how to actually use it from the python api. Do you know if there is an example?

**Comment by astrelsky** [comment]
The table definitely won't fit your use case. If you are not using the jython provided with Ghidra then you wouldn't be able to use the table. In order to use it you need to create your own class that implements `TableChooserExecutor`. There may be a java example somewhere in the repo. If there isn't I know there was a past issue opened regarding the table chooser so you could search there. I think they provided their example. It was in java but sure be simple to translate over to python.

I don't see any reason why an `askString` with multiline support wouldn't be considered. Of course this is up to the devs and I'm just here to help.

**Comment by dragonmacher** [comment]
From your script you should be able to call:

    `OptionDialog.showInputMultilineDialog()` 

to get multiline data from the user.

**Comment by philzook58** [comment]
Thanks!

```python
import docking.widgets
user_string = docking.widgets.OptionDialog.showInputMultilineDialog(None, "my title", "my label", "my initvalue")
```

Does basically get me what I was looking for!

Feel free to close this unless anyone would like this as a note to add an easier to find function to the scripting api.

**Comment by dragonmacher** [comment]
I'll close this.   Upgrading the scripting API is something we do very sparingly.    

This is a good example of how users can branch out from scripting code into to full-featured APIs.
