### ISSUE TITLE
What should I do to connect to a Android Emulator process

### ISSUE THREAD

**Issue by ratsafalig** [NationalSecurityAgency/ghidra#3153]
Here's what I've done :  

- Using `Apktool` to extract all file in a `.apk` file. In it I found `libunity.so` for example.  
- Launch a android emulator via `emulator -avd [my-emulator-name]`  
- copy `gdbserver` from `ndk`  
- launch game, launch `gdbserver` and attach to game's pid. then forward all tcp connections to my `localhost`  
- open `libunity.so` in Ghidra and select debug in gdb via ssh, enter password

And then  
![image](https://user-images.githubusercontent.com/33503055/123031999-d3f02880-d417-11eb-89fe-eb293245abc6.png)

I've set `ssh` server properly on my windows localhost, and I've downloaded `gdb` on my localhost and it works fine.

**Comment by d-millar** [comment]
@ratsafalig Take a look at issue #2974 - our best guess is that your issue is related to our outdated Ganymed implementation of SSH, but, if, having read that, you're still stuck (or onto another issue), definitely post back.  We'll give it another try!

**Comment by ratsafalig** [comment]
hugely sorry for the late reply, what a busy week...
I check my ubuntu version and it is very likely the issue you mentioned.
I'll give it a go

**Comment by ratsafalig** [comment]
According to #2974 I fixed solved this problem. 
But for now there is new one occur when I try to use debugger to connect a ssh server in windows. 
It just jamed all the time showing this : 
![image](https://user-images.githubusercontent.com/33503055/123640946-43b94580-d854-11eb-9cf4-fae9788b0085.png)

Any advices?

**Comment by d-millar** [comment]
Can you expand that box to show the options above "SSH hostname"?  Also, anything potentially informative in the console log window?  Just to verify your set-up, am assuming you have the adb/gdbserver running in the emulator and you have some Windows version of gdb that you're using to connect.  What version?  We've tested using WSL, but not Cygwin, just as a point of reference.  Cygwin theoretically should work too. Did you verify that connecting with gdb without Ghidra works?  Also (maybe needless to say, but...) verify that the path in the Connect window to gdb is correct.  And that you can SSH into the emulator with the gdb pipeline.

**Comment by ratsafalig** [comment]
![image](https://user-images.githubusercontent.com/33503055/123658778-9c90da00-d864-11eb-88d4-4fad65afbe2d.png)
here is the whole screenshot, and gdb i use is downloaded from [gnutoolchains.com](https://gnutoolchains.com/)

I think maybe it has something to do with the gdb that I download from

**Comment by ratsafalig** [comment]
nope, I tried Cygwin, It still jamed. 
And yes, I can connect to gdb via command line

**Comment by d-millar** [comment]
ok, hmmmm - am leaning towards it being an initial SSH connection issue, i.e. SSH does some stuff the first time you connect which may require a response.  May seem pointless but can you SSH to localhost:22 and then re-try the connection?

**Comment by d-millar** [comment]
From @nsadeveloper789:  looks like from the log that your version of gdb is a Windows executable, i.e. gdb.exe - a gdb executable compiled for Windows.  If so, you need a legit Linux version of gdb running in a Windows subsystem.  We recommend WSL if you have it, although a version of gdb running in a VM should work too.   Cygwin or msys probably aren't going to work yet.  (We haven't implement a ConPTY-based version for Windows.)

**Comment by ratsafalig** [comment]
hello, sorry to bother you once again...this time with a irrelevant question...

I am trying to debug this time using IDA on a `.so` file for android device.  And I push `android_server64` which came along with IDA installation, into android device  

And then connect using IDA remote android debugger.  

It did successfully attach to the pid that I trying to.  But the thread window only display one thread.  

And that's not correct because that application is multi-thread.  

Is this a bug come alone with IDA or I mis-operate something.  

Here's the screenshot:  

![image](https://user-images.githubusercontent.com/33503055/124236738-57f98d00-db49-11eb-846f-e5a47d2ae521.png)

- - -

I realize this is not the right use of github issue section...and I'm deeply sorry for asking such irrelevant question...

**Comment by d-millar** [comment]
@ratsafalig Unfortunately, it’s been a while since I used the IDApro debugger, and I know less than zero about it’s internals.  Let me see if I can find the right forum for IDApro questions for you….

**Comment by d-millar** [comment]
This might be a starting place, especially the links at the bottom:  https://reverseengineering.stackexchange.com/questions/19793/how-to-use-ida-pro-debug-android-application

**Comment by ratsafalig** [comment]
Can I ask what is the relatively popular solution of reverse engineering a .so file in industrial world.  

I mean, there is quite a lot of debugger, isn't it? like ghidra, ida, ollygdb etc...

**Comment by d-millar** [comment]
Well, we’re not technically “industry” so maybe not the right people to ask 😊 but, for basic static analysis, IDApro has been the industry standard for more than two decades.  In the dynamic arena, the debugger tied to the OS development environment has typically been the dominant force.  For Linux, that has been gdb, Windows kd and its variants, and Apple first gdb and now lldb.

**Comment by ratsafalig** [comment]
just work out myself.
since android 10.0, it change the path of `libc.so` so IDA can't really know where it is.
you need to execute `export IDA_LIBC_PATH=/apex/com.android.runtime/lib/bionic/libc.so` before launch ida debugger
