### ISSUE TITLE
Functions folders scrambled after loading PDB

### ISSUE THREAD

**Issue by justanotheranonymoususer** [NationalSecurityAgency/ghidra#3154]
**Describe the bug**
See reproduction and screenshot.

**To Reproduce**
1. Load an executable (e.g. sort.exe, it's small)
2. Analyze **without PDB**
3. Wait for analysis
4. Open Functions in Symbol Tree
5. Choose File -> Load PDB
6. See there's a mess of **FUN_***** folders

**Expected behavior**
Folders are sorted and nice.

**Screenshots**
![image](https://user-images.githubusercontent.com/5781692/123167178-e782aa00-d47e-11eb-9d2e-a7746d2a57dc.png)

**Environment (please complete the following information):**
 - OS: Win10 x64
 - Java Version: 11.0
 - Ghidra Version: 10.0
 - Ghidra Origin: Official

**Comment by dragonmacher** [comment]
I imagine the functions have been renamed, but the tree did not update its folder structure after the rename.

**Comment by ghidra1** [comment]
> I imagine the functions have been renamed, but the tree did not update its folder structure after the rename.

... although the sort order of those showing is also questionable

**Comment by ghidra1** [comment]
Could you please retest with 10.0.2 release where the tree sort has been modified significantly and let us know what you observe.

**Comment by justanotheranonymoususer** [comment]
Better, now the folders are left empty.

![image](https://user-images.githubusercontent.com/5781692/128771930-acc51333-5a00-4555-9039-cc0b4fc25ce3.png)

**Comment by ghidra1** [comment]
Closing issue.  We may at some point improve cleanup of the empty folders.
