### ISSUE TITLE
MFC42D.DLL Ordinal vs Name Question

### ISSUE THREAD

**Issue by nedeulers** [NationalSecurityAgency/ghidra#316]
This is my first time posting anything so I am not sure how to mark this as a question.

I have tried everything to get the External Library function name instead of ordinal to show up in an executable designed in Visual Studio 6.0 for over a week now. I have tried to do the analysis on the MFC42D.DLL using the MFC42D.PDB file and create an FIDs file. I have tried to capture the data types and apply them. I have tried creating the .exports file using the Java Script provided. I can make the .exports file match exactly with the name to ordinals in the MFC42D.DEF file. When I do analysis on the exe file there are still functions pointing to MFC42D.DLL::Ordinal1061 instead of the string that I can see right below the 1061 statement. How do I get Ghidra to name the calls in the thunk_functions created in the analysis to have the string instead of the Ordinal?

The Test.exe is an MFC Application created in Visual Studio 6.0 a dialog form I added 1 button.

Here is the Project Setup.
![Project_Setup](https://user-images.githubusercontent.com/49213144/55440465-50636c00-556d-11e9-8eff-15b317a3cab9.png)

This is what the Exports looks like for the MFC42D.dll when I applied the PDB
![MFC_After_PDB_Applied](https://user-images.githubusercontent.com/49213144/55440548-94567100-556d-11e9-8e1f-a8665acbe134.png)

This is the Assembly of the CDialog from the MFC42D.dll
![CDialog_Assembly](https://user-images.githubusercontent.com/49213144/55440556-9caeac00-556d-11e9-903e-50b327d56926.png)

This is the Decompiled  version of CDialog
![CDialog_Decompile](https://user-images.githubusercontent.com/49213144/55440564-a1736000-556d-11e9-8505-0faaa5a492c9.png)

When I tied the External dll to the MFC that I did analysis on this is what the Test.exe imported
notice they are back to ordinal
![Test_MFC_import](https://user-images.githubusercontent.com/49213144/55440575-a801d780-556d-11e9-9342-5958992a824b.png)

This is the CDialog from the Test.exe analysis
![Test_CDialog_Assembly](https://user-images.githubusercontent.com/49213144/55440577-acc68b80-556d-11e9-938f-3fe0fc543194.png)

This is the CDialog from the Test.exe analysis decompiled
![Test_CDialog_Decompile](https://user-images.githubusercontent.com/49213144/55440584-b0f2a900-556d-11e9-8b65-fab960c65f4e.png)

Here is where I created the exports file from the Java Script
![Create_Exports](https://user-images.githubusercontent.com/49213144/55440593-b64ff380-556d-11e9-9500-1678c05a3000.png)

Here is where you can see 318 should get tied to CDialog
![Exports_MFC42D](https://user-images.githubusercontent.com/49213144/55440617-ca93f080-556d-11e9-9686-efa01a96d25a.png)

**Comment by ghidra1** [comment]
Could you show your import log for test.exe which would help identify what DLL imports were performed and what errors may have occurred when attempting to resolve the import libraries and symbols.

**Comment by emteere** [comment]
Please look in your .ghidra/ghidra_9.0.1/symbols directory.  If there aren't pre-existing .exports file, then one gets created here during import.  It is possible the .exports file exists here that is overriding your changes.

Also, I believe the .exports file is only applied at import time.  Are you re-importing the file after adding changes to the .exports file?

If this is the case, then a change may be needed to notice that a new .exports file has been added.

**Comment by nedeulers** [comment]
> Please look in your .ghidra/ghidra_9.0.1/symbols directory. If there aren't pre-existing .exports file, then one gets created here during import. It is possible the .exports file exists here that is overriding your changes.
> 
> Also, I believe the .exports file is only applied at import time. Are you re-importing the file after adding changes to the .exports file?
> 
> If this is the case, then a change may be needed to notice that a new .exports file has been added.

**Comment by nedeulers** [comment]
So just to let you know, your information about the .exports going to my .ghidra/symbols directory on import was the key (on a side note the checkbox on import to create .exports does not appear to do anything, it makes the exports in my ghidra folder either way). It is a little strange that you have to import the executable and let it pull in the Ordinals from MFC42D.dll then open the MFC42D in the editor add the PDB file let it rename everything run the java script that exports the modified .exports file into a folder that is not used for importing my executable. Then I have to open a new project because it remembers the information from the last time if was imported if you don't use a new project. Then put the correct .exports file from the Base\data\symbols folder into the .ghidra\symbols folder. Then re-import the executable and it will finally have the correct names for the classes from the MFC. Thanks for the great tool it is fun to dig into old exe files.
