### ISSUE TITLE
Windows 10 detects trojan Win32/Zpevdo.B in expCreateThreadExit.exe

### ISSUE THREAD

**Issue by cwgreene** [NationalSecurityAgency/ghidra#3160]
**Describe the bug**
Windows 10 detects trojan Win32/Zpevdo.B in expCreateThreadExit.exe after unzipping ghidra 10

**To Reproduce**
1. Unzip ghidra 10 in windows 
2. Wait for or run antivirus
3. Be alarmed when you are notified that a threat has been detected.

**Expected behavior**
Windows Antivirus should not trigger.

**Screenshots**

![image](https://user-images.githubusercontent.com/135558/123523789-e5853a80-d67a-11eb-9143-3e302b31f9b6.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: [e.g. 11.0]
 - Ghidra Version: 10
 - Ghidra Origin: https://ghidra-sre.org/

**Comment by d-millar** [comment]
While this is clearly a false alarm, why are the JUnit test executables being included in the distribution?

**Comment by astrelsky** [comment]
> While this is clearly a false alarm, why are the JUnit test executables being included in the distribution?

I had to restore about 15 files that my av "quarantined" because heuristics. This explains why there were so many.

**Comment by ryanmkurtz** [comment]
We will change things so they don't get built with `gradle buildGhidra`, which will also prevent them from being released in the next version of Ghidra.
