### ISSUE TITLE
Request: Way of working with filesystems

### ISSUE THREAD

**Issue by RobertLarsen** [NationalSecurityAgency/ghidra#3165]
# What I want to do
I want to add an "Import all dependencies" feature. It should query a programs ExternalManager for unresolved externals and fulfill them and fix up all their externals recursively.

# What I am trying
Getting from a program to the filesystem it came from seems way too complicated to me if at all possible. What I do so far is:
```
FSRLRoot root = FSRL.fromString(program.getMetadata().get("FSRL")).getFS();
```
This is pretty much magic, that I had to search through the source code to find out. But this is also where it all ends because I cannot get from this to a filesystem.
The `FileSystemService` class is not actually a service that you can get a handle to, however the `FileSystemBrowserService` is. But it can only open filesystems in the browser, not give you a handle to one.

# What I would like to do
Optimally I would like to add my "Import with dependencies" action directly to the filesystem browser so that I can work on the filesystem while it is definitely available.

But being able to do something like this would also be nice:

```
FSRLRoot root = program.getFSRL().getFS();
FileSystemRef ref = getService(FileSystemService.class).openFilesystem(root);
GFileSystem fs = ref.getFilesystem();
```
The `openFilesystem` could throw exceptions if it can no longer be found (which is why I would prefer to add my functionality directly to the browser).

**Comment by dev747368** [comment]
@RobertLarsen:

FileSystemService.getInstance() is probably what you are looking for to get an instance.

Additionally, if you are sure you need the file system your binary was imported from, you should probably do something like:

```
FileSystemService fsService = FileSystemService.getInstance();
try ( RefdFile ref = fsService.getRefdFile(fsrl, monitor) ) {
 GFileSystem fs = ref.fsRef.getFilesystem();
 ...etc...
}

```
(this way you don't need to manipulate the FSRL manually to get the container)

FYI, any methods that take a TaskMonitor need to be run in a background task thread instead of in the swing thread.

**Comment by dev747368** [comment]
re: adding actions to the file system browser ui.

The best example of doing this exact thing is in FileFormatsPlugin.  Take a look at one of the "createXYZAction()" methods.

The "isEnabledForContext()"  method is where the magic happens as far as getting your new menu item added to the file system browser's menu.

**Comment by RobertLarsen** [comment]
Holy shit, that was easy!
Also, I would never have found it on my own.

Hmm, this fully covers my need so unless you think my suggested api makes sense I think this issue can be closed.

**Comment by dev747368** [comment]
Looking at existing code is probably the quickest way to find out how things work.

Speaking of never finding it on your own, hitting Ctrl-F1 when hovering over a button or menu item will show you the class and method where that action was created.   You could then go look at that code and see how it did its thing.

(of course, you would have had to already know that some of the items in the file system browser were added there by a second plugin, to hover over those actions to see where they came from)

**Comment by RobertLarsen** [comment]
Ctrl-F1 is damn close to the best thing ever. Great tip.
Thanks a lot.

**Comment by dragonmacher** [comment]
> Speaking of never finding it on your own, hitting Ctrl-F1 when hovering over a button or menu item will show you the class and method where that action was created. You could then go look at that code and see how it did its thing.

Caveat: `Ctrl-F1` is only available in development mode (e.g., running from a git clone) and not in a production release.
