### ISSUE TITLE
Decompiler window is not showing

### ISSUE THREAD

**Issue by pernordeman** [NationalSecurityAgency/ghidra#3173]
Hey!

Just tried to install ghidra and when trying to launch it the decompiler window is gone.
It doesn't appear in the window section or in the toolbar. 
There was some authorization problem when first trying to analyze a problem which made the tool disappear. 

Is there any way I can reset this or fix it? 
I've seen the other bugs related to this bugs but all seem to check out.

Im running on Mac OS 11.2.1
Java: OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9

**Comment by ryanmkurtz** [comment]
Duplicate of #1720.

https://github.com/NationalSecurityAgency/ghidra/issues/1720#issuecomment-610351040
