### ISSUE TITLE
File got flagged by AV when decompressing ghidra 10 public

### ISSUE THREAD

**Issue by jumpeip** [NationalSecurityAgency/ghidra#3177]
Would it be normal for this file to get flagged and deleted by AV when decompressing the ghidra 10 zip file?

file:D:\ghidra_10.0_PUBLIC_20210621.zip>ghidra_10.0_PUBLIC/Ghidra/Debug/FrameworkDebugging/os/win32/expCreateThreadSpin.exe

Alert level: Severe
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Microsoft defender detected it and deleted it.  The file was identified as a trojan

**Comment by mumbel** [comment]
#3160

**Comment by astrelsky** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Debug/Framework-Debugging/src/expCreateThreadSpin/c/expCreateThreadSpin.c
