### ISSUE TITLE
Edit Function dialogue fails to accept spaces between the base type and a sized pointer

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3178]
**Describe the bug**
When using the `Edit Function` dialogue with sized pointers the default signature display includes a `<space>` between a base type and its pointer.  E.g.
![image](https://user-images.githubusercontent.com/67698927/124283625-069acf00-db44-11eb-93c0-5fcc6df1ec90.png)
The `<space>` causes a parsing error after other modifications in the dialogue.

If you remove the spaces, parsing also succeeds!

**To Reproduce**
1. Create a fn definition similar to above
2. Modify say the fn name
3. Either tab to the next edit box or click `OK`

**Expected behavior**
Should accept it.

**Possible Solution**
Modify the following line in method `replaceDataTypeIfNeeded` in class `FunctionSignatureParser`:
`String displayName = dataType.getDisplayName();`
to
`String displayName = dataType.getName();`

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.2 / 16.0.1
 - Ghidra Version: 10.X
 - Ghidra Origin: locally built

**Comment by Wall-AF** [comment]
> **Possible Solution**
> Modify the following line in method `replaceDataTypeIfNeeded` in class `FunctionSignatureParser`:
> `String displayName = dataType.getDisplayName();`
> to
> `String displayName = dataType.getName();`

Doesn't work if replacing an unsigned pointer (`void *`) with a signed one (`void *32`) because it gets the substitution text from the existing signture, not the text from the dialogue!

May have to do a either a more sophisticated replace or an additional initial lookup to add the size to the `displayName`.

**Comment by ghidra1** [comment]
We are aware of many parser deficiencies for the Edit Function dialog and have an open ticket on the issue.  Due to our inability to parse templates we have attempted to employ a substitution strategy during the parse which can trip-up on pointer and array tokens.  The work-around for this is to avoid use of the free-form entry and use the table-driven edits within the same dialog.
