### ISSUE TITLE
Jython Scripts __file__ is not defined

### ISSUE THREAD

**Issue by TheMatt2** [NationalSecurityAgency/ghidra#3181]
The `__file__` attribute is not defined when a script is run in Ghidra.

Python documentation says the `__file__` attribute should be defined if the module is loaded from a module, such as with Ghidra Scripts.

[https://docs.python.org/3/reference/import.html#\_\_file\_\_](https://docs.python.org/3/reference/import.html#__file__)
(I realize this is the Python 3 docs, Python 2 and Jython follow the same convention, but I couldn't find the doc link)

This behavior is in consistent within Ghidra, since while the main module does not a `__file__` attribute, imported modules do.

Therefore the `__file__` attribute can be obtained using the following snippet

```python2
# file_attr.py
# Run this as a Ghidra Script

try:
    __file__
except NameError:
    import file_attr
    __file__ = file_attr.__file__
    del file_attr
```

Since `__file__` is defined if the same script is run in Python2, Python3 or Jython, and is available in Ghidra through a module importing itself, this is a bug that should be corrected.

**To Reproduce**
Run this script as a Ghidra script

```python2
try:
    __file__
except NameError:
    print("__file__ is not defined")
else:
    print("__file__ is defined")
```

**Expected behavior**
The test script should print "__file__ is defined", and have the file path to the Ghidra script being run.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.LTS
 - Java Version: 11.0.11
 - Ghidra Version: 10.0 (Build PUBLIC 2021-Jun-21 1239 EDT)
 - Ghidra Origin: official ghidra-sre.org distro 

**Additional context**
Related issue in Jython (fixed) https://bugs.jython.org/issue1548

**Comment by Dumbo-programmer** [comment]
u didnt pass the parameter

**Comment by ryanmkurtz** [comment]
This is an easy fix.  You can expect it soon.

**Comment by ryanmkurtz** [comment]
@TheMatt2 Jython normally sets `__file__` to the relative path of the script from I believe your CWD.  The easiest thing for me to do is to make it an absolute path when launched from Ghidra.  Do you think that is sufficient?

**Comment by TheMatt2** [comment]
That would absolutely sufficient.
My understanding is that an absolute path for `__file__` follows Python's spec and is the form Python 3 formats `__file__` on imported modules.

So yes, that sounds just fine.
