### ISSUE TITLE
6502: SBC instruction carry/borrow handling is incorrect

### ISSUE THREAD

**Issue by philpem** [NationalSecurityAgency/ghidra#3189]
**Describe the bug**
Ghidra incorrectly handles the carry flag when decompiling an 'SBC' instruction on the 6502 processor.

**To Reproduce**
1. Disassemble and decompile any code which uses the 6502 "SBC" instruction preceded by a "SEC" (set carry) instruction.
2. On a 6502 SEC + SBC results in a direct subtract from the accumulator.
3. Note that the value Ghidra shows (in the decompilation) for the subtraction is one less than it should be.

For example:
```
   LDA #$34
   SEC
   SBC #$12
```

Should result in `#$12` being subtracted from the `A` register (initialised to `#$34`) -- giving `#$22` after execution on a real 6502.

Ghidra's decompilation shows that `#$13` is being subtracted, which leaves `A`-reg with an incorrect value.

References showing correct behaviour:
* https://wiki.cdot.senecacollege.ca/wiki/6502_Math
* http://www.righto.com/2012/12/the-6502-overflow-flag-explained.html

**Comment by GhidorahRex** [comment]
The dreaded add-with-carry and subtract-with-borrow instructions. We've found several errors in them in recent months, but this one is definitely the most egregious because it will always be wrong. I'll take a look. Thanks @philpem
