### ISSUE TITLE
Relocation table in AmigaOS hunks

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#319]
I'm implementing Amiga Executable Hunks loader, and this binary format has relocation tables, like in PE/NE files. There is `getRelocationTable()` method in `Program` object, which returns `RelocationTable` object. This table has `public Relocation add(Address addr, int type, long[] values, byte[] bytes, String symbolName);` method, but I don't understand what I must pass as `type`, `values`, and 'bytes' values.

`Type` is `int`, and values, that are used in other loaders, are for PE and ELF formats only.

**Comment by ryanmkurtz** [comment]
Typically the _type_ is the relocation type as defined in a header file, the _values_ are the new bytes after you fixed up the relocation, and the _bytes_ are the original bytes as they were before the relocation.  You have some freedom the make these what you want though...this table is more of a way for you describe what relocations you performed in your loader.

**Comment by lab313ru** [comment]
Values are longs, not bytes.

Ryan Kurtz <notifications@github.com> 3 апреля 2019 г. 15:36:46 написал:

**Comment by lab313ru** [comment]
And which header file do you mean?

**Comment by lab313ru** [comment]
I thought that Ghidra uses that table during xrefs calculation. But now it seems that this table must be used by you to patch memory with correct offsets, right?

**Comment by ryanmkurtz** [comment]
All 3 fields are arbitrary.  If you don't have a header file that defines different relocation types, you can just use 0 for the type.  The values are longs so you have the freedom to describe the relocation in different ways.

**Comment by ryanmkurtz** [comment]
> I thought that Ghidra uses that table during xrefs calculation. But now it seems that this table must be used by you to patch memory with correct offsets, right?

No, you must manually perform the relocation by modifying the bytes directly.  The relocation table is simply a way for you to display back to the user what relocations were performed.

**Comment by lab313ru** [comment]
Thank you:)

**Comment by lab313ru** [comment]
And what I should hook to apply new offsets when Ghidra changes ImageBase?

**Comment by ryanmkurtz** [comment]
You have to create a class that extends `RelocationFixupHandler`.

**Comment by ryanmkurtz** [comment]
And make sure your subclass name ends with "RelocationFixupHandler". That's how our extension point mechanism finds it at runtime.

**Comment by lab313ru** [comment]
It doesn't work for me.
1. I've updated RelocationTable in `load()` method during binary parsing.
2. Called program.setImageBase(0x123456).
3. My relocation handler methods never called:
![изображение](https://user-images.githubusercontent.com/7189309/55514222-32326480-5670-11e9-8a52-d147732ddcee.png)

![изображение](https://user-images.githubusercontent.com/7189309/55514246-3d859000-5670-11e9-9656-eb689a49fc20.png)

**Comment by ryanmkurtz** [comment]
What if you change the image base address through the GUI? (it's a button in the memory map)  Is your handlesProgram() method never being called?

**Comment by lab313ru** [comment]
Yes, it calls my relocator only when changing image base using GUI.

**Comment by lab313ru** [comment]
program.setImageImage() doesn't call it.

**Comment by ryanmkurtz** [comment]
Ok, would you mind submitting that as a separate bug issue?

**Comment by lab313ru** [comment]
https://github.com/NationalSecurityAgency/ghidra/issues/329
