### ISSUE TITLE
Incorrect packing in structures with unions

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#3191]
**Describe the bug**
Structures with unions can be incorrectly aligned

**To Reproduce**
On a 64-bit x86 binary, create ``testStruct`` and ``testUnion`` as follows:
```
union testUnion {
    dword a1
    qword a2
    pointer a3
}
struct testStruct {
  pointer
  pointer
  dword
  testUnion
  pointer
}
```
Pack ``testStruct`` with alignment 8 (which is usually the default). Observe that the testUnion member is placed at offset 0x14.

**Expected behavior**
Clicking align should put the testUnion at offset 0x18.

**Environment (please complete the following information):**
 - Ghidra Version: 10.1_DEV

**Comment by quietust** [comment]
For whatever reason, 64-bit values (such as "double" or "longlong") are only marked as requiring 4-byte alignment in x86 binaries, even though Microsoft's compilers always use 8-byte alignment for them.

Also, what packing/alignment settings did you apply to the Union?

**Comment by sad-dev** [comment]
The default alignment is 8, and yes, I clicked the Pack checkbox, which results in the following layout:

0x0: pointer
0x8: pointer
0x10: dword
0x14: testUnion
0x20: pointer

**Comment by quietust** [comment]
This might be a regression, then, since it works correctly in 10.0-PUBLIC when I click the Pack checkbox on both the Struct **and** the Union (if I uncheck it on the Union, then I get the incorrect alignment you're seeing).

**Comment by ghidra1** [comment]
> The default alignment is 8, and yes, I clicked the Pack checkbox, ...
@sad-dev , as @quietust questioned, did you enable packing on the Union definition as well as the Structure?  If not, it will emit a default alignment of 1-byte which would cause the bahvior you are seeing.

**Comment by sad-dev** [comment]
Marking the union as packed as well leads to a correct alignment; if the structure having this alignment when only the structure and not the union is marked as packed is expected behavior, I will close this issue

**Comment by ghidra1** [comment]
This is the correct behavior.  You also have the option of setting the minimum alignment on the non-packed union.  It is the unions alignment that dictates how it will be placed within the packed structure.
