### ISSUE TITLE
Failed to launch application in the debugger 

### ISSUE THREAD

**Issue by thej9111** [NationalSecurityAgency/ghidra#3194]
Hi , I'm **new** to ghidra and i was wondering does it come with a built-in debugger or i need to attach it to one ? 
the thing is when i try to lunch the program in the debugger i get the following : 
![2021-07-07_21-55-31](https://user-images.githubusercontent.com/67557724/124814564-d6519700-df6e-11eb-8162-fc0ae1a149f2.png)

![2021-07-07_21-56-43](https://user-images.githubusercontent.com/67557724/124814576-de113b80-df6e-11eb-9297-43ec371334a6.png)

any ideas to fix this  ?

**Comment by d-millar** [comment]
@thej9111  Well, hmmm, that should have worked, judging just from the info in the screen shot.  A couple of questions to narrow things down:

- did you have an active program loaded in the static listing when you used the quick launch button?
- assuming yes, was that program imported from its current location on the computer running Ghidra?
- can you verify that you have a copy of dbgeng.dll in your system $PATH (usually system32)?

**Comment by thej9111** [comment]
@d-millar , thanks for the response 

to answer your questions :
1- yes , it was loaded in the static listing 
2- yes the program  was imported from its current location on the computer running Ghidra
3- yes i have a copy of the dbgeng.dll in the system32 and syswow64 folders 

Regards

**Comment by DrTsukamoto** [comment]
Ahh, that's definitely helpful.  I  will try to hunt this down today. Will that executable normally execute from the command line?  Also, any chance there are spaces in the path?

**Comment by d-millar** [comment]
Ahh, that may be helpful.  I will try to look at this today.   Will that executable run from the command line?  Also, any chance there are spaces in the path?  Java gets unhappy about the spaces when we aren’t careful.

**Comment by d-millar** [comment]
Hmmm, spaces not the issue....

**Comment by d-millar** [comment]
Just as a sanity check, try launching something mundane like notepad.exe - that would at least confirm it's any issue related to the target.

**Comment by thej9111** [comment]
> Just as a sanity check, try launching something mundane like notepad.exe - that would at least confirm it's any issue related to the target.

@d-millar , sorry for the delay 
the same thing happens when i launch notepad.exe 

Regards

**Comment by d-millar** [comment]
No problem re delay - we’re always here.  Not working for notepad was not what I was expecting.   Typically, I’m testing on Windows server versions, so I’ll have to fire up a VM with a fresh install and see if I can reproduce your error.

**Comment by thej9111** [comment]
> No problem re delay - we’re always here. Not working for notepad was not what I was expecting. Typically, I’m testing on Windows server versions, so I’ll have to fire up a VM with a fresh install and see if I can reproduce your error.

thanks , waiting your reply

**Comment by d-millar** [comment]
OK, well, hmmm....I was unable to reproduce your problem, so let me list out exactly what I did and maybe it will be obvious where our paths differ:

1) I installed a fresh version of Windows 10 Home (I don't think that matters) in VMware - fired it up.
2) I installed the Amazon Corretto x64 JDK 11.
3) I downloaded Ghidra 10.0.1 from ghidra-sre.org.
4) I extracted the contents into my home directory.
5) I ran ghidraRun.bat and created a new project.
6) I launched the debugger tool and imported notepad.exe.
7) I hit the launch button in the toolbar.
8) I left the defaults in Connect window and started debugging.
9) I also tried the various other options:  dbgeng/dbgmodel IN-VM/GADP 
10) All of these worked

One thought though just occurred to me (courtesy Mr. Aitel):  have you tried executing with port 0 (the default)?  and, if not, any chance you picked a port that was already in use elsewhere?

**Comment by thej9111** [comment]
> 9\. I also tried the various other options:  dbgeng/dbgmodel IN-VM/GADP

usually I just hit the debugger button ,but i noticed the connect dialog box : 
![2021-07-13_21-43-26](https://user-images.githubusercontent.com/67557724/125507747-9c276d8e-f3ec-4480-9107-0e5db6ad0b2a.png)

can you tell me if I'm missing something ?

**Comment by d-millar** [comment]
So the debugger button up top (in the toolbar) takes your current default debugger (set using the pull-down right next to it), starts it up, and tries to run whatever is current in the listing.  Alternatively, you can do these steps one-at-a-time, i.e. in the Targets window, pick and start your preferred debugger, and then in the Objects window, run the program in the listing or something else depending on the selected Connector.

I think you get to that Connect window either way.  The one you posted above looks fine - it will pick a random port to connect to (because "Agent TCP port" is set to 0).  In the version you first sent, you obscured the port, so that led me to believe you might have picked an actual port to use, say 12345.  If the port number you picked was either a protected port (lower numbers) or a port that was in use already by some other program (or a previously started debugger agent), you would have gotten an error, although admittedly I don't think it would be the one you posted.

**Comment by thej9111** [comment]
> So the debugger button up top (in the toolbar) takes your current default debugger (set using the pull-down right next to it), starts it up, and tries to run whatever is current in the listing. Alternatively, you can do these steps one-at-a-time, i.e. in the Targets window, pick and start your preferred debugger, and then in the Objects window, run the program in the listing or something else depending on the selected Connector.
> 
> I think you get to that Connect window either way. The one you posted above looks fine - it will pick a random port to connect to (because "Agent TCP port" is set to 0). In the version you first sent, you obscured the port, so that led me to believe you might have picked an actual port to use, say 12345. If the port number you picked was either a protected port (lower numbers) or a port that was in use already by some other program (or a previously started debugger agent), you would have gotten an error, although admittedly I don't think it would be the one you posted.

could it be that Ghidra is lunching wrong version of windbg ? like 64 bit instead of 32 ?

**Comment by d-millar** [comment]
Well, hmmm, maybe?  Ghidra doesn't launch windbg directly - it loads the dbgeng dll or dbgeng+dbgmodel for the dbgmodel case, and wraps their functionality via JNA.  Which versions it loads is determined by a slightly complicated search strategy in Java, basically starts with the local Java install directory, then the System32 directory, then other system directory, then walks the PATH variable.  So, in your case, it "should" be loading the version in System32, which is presumably a 64-bit version and should work for either 64-bit or 32-bit targets.  If you wanted to, you could verify this using something like procexp64 from the SysinternalsSuite.

Somehow, I don't think that's the problem, but, that said, I don't have a great theory right now.  When you launch something like notepad are you getting that same "not a valid Win32 executable" message?  Also, have you tried the IN-VM version (accessible via the pull-down to the right of the launch button or the Targets window"?  Also, when you launch and get the error in the Interpeter, maybe check the "Debug Console" window - there might be some other clues if we're lucky.
