### ISSUE TITLE
Low-level Error: Bad size for array of type char

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#3196]
**Describe the bug**
Creating a class with the name "string" and allowing the `this` parameter to be applied to a function can cause the decompiler to produce an error.

**To Reproduce**
1. Import and open `ghidra_10.0_PUBLIC/Ghidra/Features/Decompiler/os/linux64/decompile`
2. After analysis go to `0x004be300`
3. In the symbol tree create a class named `string`
4. Set the symbol at `0x004be300` to be `string::power2Divide`
5. Change the calling convention to `__thiscall`
6. See `Low-level Error: Bad size for array of type char`

**Expected behavior**
This shouldn't be allowed.

**Environment (please complete the following information):**
 - Ghidra Version: 10.1_DEV cad6b3c9d9503da0cb6719f187dfa69528767158

**Comment by dev747368** [comment]
I've duplicated with a random hello world binary.  I'll update you as I find more.

**Comment by astrelsky** [comment]
> I've duplicated with a random hello world binary.  I'll update you as I find more.

Sounds good. My theory is that the `VariableUtils` method is searching for the class struct, finding the builtin string type, accepting that and sending it over to the decompiler which tries to interpret it as the builtin type and fails. Or the other way around. I have nothing to back that up though as I had not investigated at all.

**Comment by dev747368** [comment]
Thats kinda where I am also.  Trying other 'built-in' types didn't cause the same problem, but I'm sure we'll get to the bottom of it soon.

**Comment by ghidra1** [comment]
There are two issues at play here:
- Decompiler's inability to handle datatype impl's which may be supplied with auto-params (no requirement for the DB type to exist)
- Search for class structure failed to consider .conflict structures

**Comment by ghidra1** [comment]
> > I've duplicated with a random hello world binary.  I'll update you as I find more.
> 
> Sounds good. My theory is that the `VariableUtils` method is searching for the class struct, finding the builtin string type, accepting that and sending it over to the decompiler which tries to interpret it as the builtin type and fails. Or the other way around. I have nothing to back that up though as I had not done anything further than breaking it .

The VariableUtilities is returning a StructureDataType (impl) and the decompiler treats it like a built-in type only hanging onto its name.  Subsequent lookup finds builtin string datatype.  Impl types supplied by auto-params should be cached during decompilation.

**Comment by astrelsky** [comment]
I think this has been fixed.
