### ISSUE TITLE
I can't download ghidra from ghidra-sre.org.

### ISSUE THREAD

**Issue by kotenok2000** [NationalSecurityAgency/ghidra#32]
I only get this: https://imgur.com/a/KndYcnH 
403 ERROR
The request could not be satisfied.
Request blocked. 
Generated by cloudfront (CloudFront)
Request ID: RWmG64nozqTisFmuzINuj33wBrGbvVr9ArRkvQ46AldDPSPMnnBArg==
I think it nappened because i ran tor relay. But it was in august.

**Comment by codepupper** [comment]
Your Country might be blocking it!

You can download directly from either of these Sources!
https://flfy.org/ghidra_9.0_PUBLIC_20190228.zip
https://flfy.org/ghidra/cheatsheet/CheatSheet.html

The CheatSheet is the Official one in case that's blocked in your country as well!

**Comment by kotenok2000** [comment]
That was fast. Thank you.

**Comment by laserbat** [comment]
It seems like the website blocks requests by IPs from Russia. It is definitely not ISPs blocking it, as the https connection produces no errors:  https://i.imgur.com/IsfGMHd.png

**Comment by l29ah** [comment]
Yeah, reopen plz.

**Comment by etok0** [comment]
it looks like US gov site dont like when dude with russian IP downloads US hacking software from them =)
my solution -> just install any free vpn browser extension... working example - anonymox

**Comment by elig0n** [comment]
I get this too and I'm from Israel

**Comment by elig0n** [comment]
> it looks like US gov site dont like when dude with russian IP downloads US hacking software from them =)
> my solution -> just install any free vpn browser extension... working example - anonymox

Sound to me more like dumb/outdated IP range block from Cloudflare, not necessarily the NSA itself

**Comment by U-D13** [comment]
> ... dumb/outdated IP range block ...
> — @elig0n

Looks like it. I'm IPv6 tunneling from Latvia through Sweeden with a Californian service provider, but several geolocator services put me in St. Petersburg.

**Comment by al-lawrence** [comment]
Confirm still can't access from Israel. Either use TOR or any of the hidemyip sites to download.

**Comment by ShlomiRex** [comment]
> Confirm still can't access from Israel. Either use TOR or any of the hidemyip sites to download.

Thanks! TOR is a great alternative to VPN! So simple, how didn't I thought about it?
Also from Israel, why does NSA block it? We are allies with the US :'(

**Comment by OmerMor** [comment]
The site just refers to https://github.com/NationalSecurityAgency/ghidra/releases for downloads.
