### ISSUE TITLE
python api currentSelection not working?

### ISSUE THREAD

**Issue by PatchByte** [NationalSecurityAgency/ghidra#3200]
I am trying a little bit with ghidra out!

I want to use "currenSelection" from the api in a python script!

But it is None!

Can someone help me?

**Comment by ghidra2** [comment]
Try running the ExampleColorScriptPy.py Ghidra script from the Script Manager.  The script should color the selected bytes.  You can borrow the code from that script.

**Comment by astrelsky** [comment]
If `currentSelection` is `None`, it is because there is currently nothing selected.

**Comment by ryanmkurtz** [comment]
Sounds like your questions was probably answer, so I'll close this.  Feel free to reopen if you have additional questions about the `currentSelection`.
