### ISSUE TITLE
ghidra_10.0.1_PUBLIC_20210708 not starting on Windows if path contains spaces

### ISSUE THREAD

**Issue by LoZio** [NationalSecurityAgency/ghidra#3201]
**Describe the bug**
ghidra_10.0_PUBLIC_20210621 does not start if the zip file is uncompressed in a path that contains spaces.
Some quotes missing in the startup script

**To Reproduce**
1. Unzip the package in "c:\program files"
2. Start ghidrarun.bat (or launch.bat in support)

You get **Files was unexpected at this time.**

**Expected behavior**
Ghidra should start as any version before, including 10.0.0

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: [Win 10 x64 20H1
 - Java Version: Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
 - Ghidra Version: 10.0.1
 - Ghidra Origin: official download
 
**Additional context**
I suppose the problem is  here, line 42 of launch.bat

```
if not %SUPPORT_DIR:!=%==%SUPPORT_DIR% (
	echo Ghidra path cannot contain a "!" character.
	set ERRORLEVEL=1
	goto exit1
)
```

**Comment by djdv** [comment]
Had the same problem but didn't notice this issue first.
Pushed up a PR that should fix it https://github.com/NationalSecurityAgency/ghidra/pull/3205
(works in my environment)
Going to link them together now.

**Comment by visuttaja** [comment]
I have all my JVMs in C:\!Code2019\JAVA_RTS  to get dev things listed always first.
Is there some reason not to accept ! in path?

**Comment by ryanmkurtz** [comment]
> I have all my JVMs in C:!Code2019\JAVA_RTS to get dev things listed always first. Is there some reason not to accept ! in path?

@visuttaja These are my notes from when we disabled it:

> launch.bat doesn't like ! in the path to Ghidra, but even if we fix that, Java (and gradle) doesn't like it either because ! is used as a jar-separator in paths (affects Linux too).  We should prevent even trying to launch when ! is detected in the path to Ghidra.  We should also list this as a known limitation in the Installation Guide.

**Comment by visuttaja** [comment]
> > launch.bat doesn't like ! in the path to Ghidra, but even if we fix that, Java (and gradle) doesn't like it either because ! is used as a jar-separator in paths (affects Linux too).  We should prevent even trying to launch when ! is detected in the path to Ghidra.  We should also list this as a known limitation in the Installation Guide.

FYI: I have used this structure in Windows about last 10 years and have not have any issues with that ! and Java. But this is a simple local system.
Currently I use Intellij Community and Visual Studio for bridging dlls to Java. I mean at least not with this system no issue. 
I don't use gradle with it though. 
Yes it would be nice if it immedeiately stepped out with message and reason when finding a !
