### ISSUE TITLE
Decompiler issue: Decompiler process died

### ISSUE THREAD

**Issue by SidekickLx** [NationalSecurityAgency/ghidra#3202]
**Describe the bug**
We use a Ghidra java plugin to generate pseudocode of binaries. It works most of the time. But the decompiler is unable to open a program. And the DecompInterface.getLastMessage() shows "Decompiler process died". 

Here is the code snippet.

```		
                var inter = new DecompInterface();
		var opt = new DecompileOptions();
		
		opt.setMaxPayloadMBytes(700);
		inter.setOptions(opt);
		if (!inter.openProgram(currentProgram)){
			System.out.println("open program failed!");
			System.out.println(inter.getLastMessage());
		}
```

And the output

> INFO  SCRIPT: C:\...\ghidra\GhidraScripts\src\GenFunctionMetadata.java (HeadlessAnalyzer)
open program failed!
Decompiler process died

The target is a ARM:BE:32:v7 binary.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Attachments**

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Java Version: [ 11.0]
 - Ghidra Version: [10.0]
 - Ghidra Origin: [official ghidra-sre.org distro] 

**Additional context**
The GUI program can properly decompile the binary and the target function.

**Comment by SidekickLx** [comment]
FYI: It works on Ghidra 9.2.2

**Comment by caheckman** [comment]
I was unable to reproduce this error on a generic ARM binary (Ghidra 10.0, Windows 10).  The problem may be specific to the particular binary or Ghidra program.

**Comment by SidekickLx** [comment]
> I was unable to reproduce this error on a generic ARM binary (Ghidra 10.0, Windows 10). The problem may be specific to the particular binary or Ghidra program.

Thanks for your resposing. Yes, it is specific to a particular binary and the Ghidra version (10.0) I just tried it on Ghidra 10.0.1 and it works! 
I think one of the fixes might be related, that is 

> Decompiler. Fixed a bug in the Decompiler causing Overriding symbol with different type size exceptions. (GP-1041)

I am not sure what happens during the update from 9.2 to 10.0 But nothing to be worried about since it has been fixed.
