### ISSUE TITLE
Add svrAdmin option to set password for new user

### ISSUE THREAD

**Issue by ghidra-server** [NationalSecurityAgency/ghidra#321]
**Is your feature request related to a problem? Please describe.**
When administering a Ghidra server it's insecure to have new users issued with the 'changeme' password. It would be helpful to be able to set a user password as the user is added to the server.

**Describe the solution you'd like**
A CLI command of the form: svrAdmin -add mySID myPassword

**Describe alternatives you've considered**
An alternative command to set the password on an existing user.

**Comment by ghidra-server** [comment]
Current workaround is to login as the new user with the Ghidra Client and change the password before issuing the account to the new user.

**Comment by ghidra-server** [comment]
Looks like setPAssword in https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/GhidraServer/src/main/java/ghidra/server/UserManager.java just needs hooking up to https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/RuntimeScripts/Linux/server/svrAdmin and https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/GhidraServer/src/main/java/ghidra/server/UserAdmin.java

**Comment by ghidra1** [comment]
This could like be done by adding an optional salted password hash to the queued add user request.  The

**Comment by ghidra1** [comment]
Prefer not to diverge from the command queueing technique currently employed.  Will consider adding additional capability to specify initial password which will be retained as salted hash within queued command.  May also want to provide interactive console input to avoid passwords appearing in process table.

**Comment by ghidra-server** [comment]
Sounds good on that approach thanks.

**Comment by ghidra-server** [comment]
Can I tempt anyone to go ahead and implement this?

**Comment by ghidra1** [comment]
Change in the pipeline for 9.2

**Comment by ghidra1** [comment]
Change has been merged into master

**Comment by ghidra-server** [comment]
Thanks for implementing this - unfortunately I'm seeing an issue with the feature not working. I've raised https://github.com/NationalSecurityAgency/ghidra/issues/2469
