### ISSUE TITLE
API to get PcodeBasicBlocks splitted with both CALL and BRANCH

### ISSUE THREAD

**Issue by M4tsuri** [NationalSecurityAgency/ghidra#3210]
I'm trying to build interprocedural CFG for a program with the optimized pcode basic blocks from HighFunction.getBasicBlocks.

<img width="1113" alt="Screen Shot 2021-07-12 at 18 31 42" src="https://user-images.githubusercontent.com/51822222/125273354-69a81500-e33f-11eb-9193-cdb0dc8cd7a4.png">

However, there are CALL and CALLIND instructions in the middle of a block. I wonder if there are any APIs to get PcodeBasicBlocks splitted with both CALL and BRANCH like instructions. Thanks.

**Comment by ghidra1** [comment]
As far as I know, only Instruction-level block models are currently exposed in our API - although I could be wrong.  While the Decompiler uses this pcode block model concept internally, its code is written in C and is not exposed.

**Comment by M4tsuri** [comment]
OK, thank you.
