### ISSUE TITLE
Hardcoded addresses given in decompiler for end of structure iteration

### ISSUE THREAD

**Issue by EuanKirkhope** [NationalSecurityAgency/ghidra#3214]
In my project I frequently see a pointer taken to the start of an array.  The code loops through incrementing the pointer until the end of the array.

If we eventually give a structure definition to the pointer can we update the decomplication to something more sensible.

example:

```
void MainScreenMenu_FUN_00421550(void)

{
  item_t *pItem;
  
  pItem= g_baseItem;
  do {
    if (*pItem!= NULL) {
       Flag_B1(*pItem);
    }
    pItem= pItem+ 1;
    /* warning fixed address size */ << added by me to clean up later manually
  **} while ((int)pItem< 0x45a058);**
  return;
}

```

With perhaps the while loop being changed to the following as an example :

```
} while ((int)pItem< g_baseItem[20]);
```

Alternatively, perhaps a manual operation where there could be a option to click on the address and mark it as relation to g_baseItem, and its associated type, and thereby tell the decompiler that it is the last entry in the loop, and show some sensible decomp.

**Comment by quietust** [comment]
I've encountered the same thing, but often the pointer starts at a field in the *middle* of the structure and the final pointer is beyond the end of the list and halfway into another unrelated variable.

**Comment by EuanKirkhope** [comment]
Do you also see that when the pointer in the loop is not the first member that member references are negative offsets from the pointer?

example:

'''

struct soundBufferInfo 
{
    LPDIRECTSOUNDBUFFER;
    void* camera;
    int distance;
    short vol;
    short pan;
    short soundId2;
    short flags;
}

    /* oddity */
    psVar2 = &g_SoundBuffers[0].flags;
    do {
      bPlaying = xDSoundIsSoundPlaying(*(IDirectSoundBuffer **)(psVar2 + -9));
      if (bPlaying != 0) {
        xDSoundStopPlaying(*(IDirectSoundBuffer **)(psVar2 + -9));
        *(undefined4 *)(psVar2 + -9) = 0xffffffff;
        *(undefined4 *)(psVar2 + -7) = 0;
        *psVar2 = 0;
        psVar2[-3] = 0;
        psVar2[-2] = 0;
        *(undefined4 *)(psVar2 + -5) = 0xffffffff;
        psVar2[-1] = -1;
      }
      ptVar1 = (soundBufferInfo *)(psVar2 + 1);
      psVar2 = psVar2 + 10;
    } while (ptVar1 < g_SoundBuffers + g_ambientFxSlotCount);
'''

would be good to find solutions to these types of oddities.

**Comment by astrelsky** [comment]
Why not set an equate for `0x45a058` to `g_baseItem[20]`?

**Comment by EuanKirkhope** [comment]
I didn’t know you could do that. :). Will give it a go.  Can foresee a possible
Issue with variables overlapping but will investigate.  Thanks.

**Comment by EuanKirkhope** [comment]
Evaluate is a good fix, for want of a more automatic solution
