### ISSUE TITLE
"<" related errors in Decompiler References (Find Uses of) Window

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#3217]
**Describe the bug**
The "<" token results in unexpected output in the Decompiler References (Find Uses of) table, in particular, in the Context column

**To Reproduce**
1. Find an expression of the form ``if (a->b < 0x__)`` or ``if (0x__ < a->b)``
2. Use the Find Uses Of feature on the b field. 
3. In the Context Column, the "<" token is invisible.
4. Searching for "b < 0x" or similar in the filters yields no results
5. Using the Create Column Filter, select "Context", "Contains", and type "<" into the textbox.
``html> blah blah blah`` results popup in the preview.

**Expected behavior**
"<" tokens should display properly and be searchable in the Context Column. The html should not appear in the search window.

**Environment (please complete the following information):**
 - Ghidra Version: 10.1_DEV commit cad6b3c

**Comment by dragonmacher** [comment]
This should be an easy fix.
