### ISSUE TITLE
How to patch arm/thumb condition instructions?

### ISSUE THREAD

**Issue by sparktend** [NationalSecurityAgency/ghidra#3219]
I use Ghidra Script to deal with code obfuscation.
 I need to patch instruction in order to transform code.

For example,
The instructions below:
```
        00012000  cmp            param_1,param_3
        00012002  itt                eq
        00012004  movw.eq    r4,#0xfabc
        00012008  movt.eq      r4,#0x123d
```

What I want to achieve is:
```
        00012000  nop
        00012002  nop
        00012004  movw      r4,#0xfabc
        00012008  movt        r4,#0x123d
```

But the result is :
```
        00012000  nop
        00012002  nop
        00012004  movw.eq      r4,#0xfabc
        00012008  movt.eq        r4,#0x123d
```

The `.eq` will still exist after my patch. 
So `decompiler` still considers it a conditional assignment.
like:

```
if (xxx) {
   puVar = 0x123dfabc;
}

```

not what I want to achieve is:

```
puVar = 0x123dfabc;
```

The question is How to remove the influence of the instruction  `IT`?

The way I tried：
1.  Use `Patch Instruction` menu in the Ghidra IDE. Failed.
2. Patch instruction by Ghidra Script use `patchProgram()` or `assemble()` API. Failed.

Other info:
When I use IDA to patch Instruction at [0x12000,0x12002] to `nop` on the `Hex View`, the `.eq` will  disappear after my patch.

**Comment by astrelsky** [comment]
I could be mistaken but isn't the `.eq` part of the instruction in arm? You should only have to change `movw.eq` and `movt.eq` to `movw` and `movt` respectively.

PS: If this is completely wrong for arm then just ignore me.

**Comment by GhidorahRex** [comment]
> I could be mistaken but isn't the `.eq` part of the instruction in arm? You should only have to change `movw.eq` and `movt.eq` to `movw` and `movt` respectively.
> 
> PS: If this is completely wrong for arm then just ignore me.

You're correct. The conditional for the instruction is in the high-order byte (bits 28-31). If they're set to 0x0 it's an equality condition (checking the zero flag). If it's 0xf it always executes.

**Comment by GhidorahRex** [comment]
I didn't realize this was thumb (should have because of the itt...). It's likely that when you patched over the itt, there's still a context bit set in that instruction. You should be able to manually clear it out and set it to 0.

**Comment by sparktend** [comment]
> > I could be mistaken but isn't the `.eq` part of the instruction in arm? You should only have to change `movw.eq` and `movt.eq` to `movw` and `movt` respectively.
> > PS: If this is completely wrong for arm then just ignore me.
> 
> You're correct. The conditional for the instruction is in the high-order byte (bits 28-31). If they're set to 0x0 it's an equality condition (checking the zero flag). If it's 0xf it always executes.

 The `movw` instruction here doesn't carry any conditional information.
for example, the instruction below:
```
        000548d0 c5 28                 cmp        param_1,#0xc5
        000548d2 c4 bf                  itt        gt
        000548d4 4b f6 20 1a        movw.gt    r10,#0xb920
        000548d8 cb f2 c3 0a        movt.gt    r10,#0xb0c3
```
the `movw`at `0x548d4` bytes is `f6 4b 1a 20`.

it use ARMv7's A8.8.103 MOV (immediate) 
Encoding T3.
```
MOVW<c> <Rd>, #<imm16>
-------------------------------
15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0
-------------------------------
11110 | i | 10 | 0 | 1 | 0 | 0 | imm4 | 0 | imm3 | Rd | imm8

```
not the Encoding A2:
```
MOVW<c> <Rd>, #<imm16>
-------------------------------
313029282726252423222120191817161514131211 10 9 8 7 6 5 4 3 2 1 0
-------------------------------
cond | 0011 | 0000 | imm4 | Rd | imm12
```
so, I think only the `ITT` instruction influence the `mov` instruction. If I patch it, the impact will disappear.

I tried to patch `movw.gt` or `movt.gt` directly, but Ghidra seems to refuse me to modify it.

I thought of a less elegant way. 
Patch the instruction in the middle the original instruction address.
I thought it might have destroyed some kind of internal state. so the `eq` or `gt` disappear.
after patch:
```
        000548d0 00 bf                 nop
        000548d2 4b f6 20 1a        movw    r10,#0xb920
        000548d6 cb f2 c3 0a        movt     r10,#0xb0c3
        000548da  00 bf                 nop
``` 
It's the result I want, but it's not elegant.

I think it might be better：
```
     Instruction inst  = InstructionAt(0x548d2);
     inst.clearConditionState();
     patchSth();
     ...
```
Then the result is:
```
        000548d0 00 bf                 nop
        000548d2  00 bf                 nop
        000548d4 4b f6 20 1a        movw    r10,#0xb920
        000548d8 cb f2 c3 0a        movt     r10,#0xb0c3
```

**Comment by astrelsky** [comment]
See GhidorahRex's second response. You can do this from the ui by selecting the 4 instructions after patching, right clicking, clear with options and clear everything. Then just redisassemble the instructions a d it should work.

**Comment by sparktend** [comment]
> See GhidorahRex's second response. You can do this from the ui by selecting the 4 instructions after patching, right clicking, clear with options and clear everything. Then just redisassemble the instructions a d it should work.

Thanks, I made it.
This `clear with options` is what I'm looking for.
Just clear `code` and `register` and it'll work.
