### ISSUE TITLE
ghidra defaults to ___stddecl when the architecture should make it default to __cdecl

### ISSUE THREAD

**Issue by nihilus** [NationalSecurityAgency/ghidra#322]
**Describe the bug**
This is indeed a buggy behavior since for Linux/Unix systems and especially other than x86 the default have always been __cdecl. A fact established in the late 70ies.

It might be that __stddecl is defined as __cdecl on these architectures, however it makes no sense since there are actual PE/COFF files for WinCE/NT for a dozen of platforms that might use that convention.

**To Reproduce**
Load any 32-bit MIPS32 LE ELF file.

**Expected behavior**
Defaulting to __cdecl.

**Environment (please complete the following information):**
 - OS: [Ubuntu Xenial]
 - Java Version: [11.0]
 - Ghidra Version: [9.0.1]

**Comment by ghidra1** [comment]
Can you indicate the specific problem this causing.  Please indicate the specific "buggy" behavior caused by our use of __stdcall for MIPS which has a single calling convention per ABI standard.  Do you believe we are missing a calling convention for MIPS, if so, please indicate the applicable ABI standard.

**Comment by nihilus** [comment]
@ghidra1 since when did MIPS have 1 single calling convention per ABI? Never had and will have. The calling convention is up to the toolchain. MIPS is the 101 on the subject.

Since I've used IRIX since people over here weren't born I have a grip of this; examples gratis you couldn't use gcc and MIPSPro and interlink the code, why? Because they used different calling conventions, so that argument is obviously invalid even if it contradicts the question per C (pun intended).

So the bug is that I can from disassembly view mark things as using "__cdecl" and not in the decompiler view. Being perceived like "bug" but things work and they work very well I must say. I am preparing a DSP ASE pull request actually. Well spent tax dollars. ;-)

**Comment by nihilus** [comment]
Actually this is a great PDF on the subject: https://courses.cs.washington.edu/courses/cse410/09sp/examples/MIPSCallingConventionsSummary.pdf

**Comment by nihilus** [comment]
So the Green Hills Compiler, GHC may use a totally other calling convention than VxWorks DIAB, which in turn can use a totally different calling convention than GCC. LLVM however tends to try to be compatible with GCC luckily.

**Comment by ghidra1** [comment]
Ghidra has only implemented the specific ABI standard conventions (e.g., o32, n32, n64, o64, SystemV ..).  As with hand-assembled code anything goes in some situations in which case the user must define their own cspec or resort to using "custom storage" on a per function basis.  

While a comment may show "__cdecl" based upon Microsoft name demangling there is no mapping for it and it will not be retained by the function other than as a comment.  This seems to be the default for Microsoft function name mangling.
