### ISSUE TITLE
Finding destination symbols in similar symbol name correlator is extremely slow

### ISSUE THREAD

**Issue by gsuberland** [NationalSecurityAgency/ghidra#3221]
The "Finding destination symbols" step of correlation, performed by the SimilarSymbolNameProgramCorrelator, is extremely slow. A performance trace shows the following stack trace is where most of the time is spent:

```
   java.lang.Thread.State: RUNNABLE
        at java.io.RandomAccessFile.read0(java.base@14.0.2/Native Method)
        at java.io.RandomAccessFile.read(java.base@14.0.2/RandomAccessFile.java:368)
        at java.io.RandomAccessFile.readByte(java.base@14.0.2/RandomAccessFile.java:710)
        at db.buffers.LocalBufferFile.get(LocalBufferFile.java:663)
        - locked <0x00000000cc682158> (a db.buffers.LocalBufferFile)
        at db.buffers.BufferMgr.loadCachedNode(BufferMgr.java:906)
        at db.buffers.BufferMgr.getBufferNode(BufferMgr.java:825)
        at db.buffers.BufferMgr.getBuffer(BufferMgr.java:958)
        - locked <0x00000000cc682258> (a db.buffers.BufferMgr)
        at db.NodeMgr.getLongKeyNode(NodeMgr.java:257)
        at db.LongKeyInteriorNode.getLeafNode(LongKeyInteriorNode.java:414)
        at db.LongKeyInteriorNode.getLeafNode(LongKeyInteriorNode.java:416)
        at db.Table.getRecord(Table.java:696)
        - locked <0x00000000b2bb9550> (a db.DBHandle)
        at db.Table.getRecord(Table.java:718)
        - locked <0x00000000b2bb9550> (a db.DBHandle)
        at db.KeyToRecordIterator.next(KeyToRecordIterator.java:67)
        - locked <0x00000000b2bb9550> (a db.DBHandle)
        at ghidra.feature.vt.api.db.VTAssociationTableDBAdapterV0.getRelatedAssociationRecordsBySourceAndDestinationAddress(VTAssociationTableDBAdapterV0.java:102)
        at ghidra.feature.vt.api.db.AssociationDatabaseManager.isBlocked(AssociationDatabaseManager.java:264)
        at ghidra.feature.vt.api.db.AssociationDatabaseManager.getOrCreateAssociationDB(AssociationDatabaseManager.java:220)
        at ghidra.feature.vt.api.db.VTMatchSetDB.addMatch(VTMatchSetDB.java:162)
        at ghidra.feature.vt.api.correlator.program.SimilarSymbolNameProgramCorrelator.findDestinations(SimilarSymbolNameProgramCorrelator.java:176)
        at ghidra.feature.vt.api.correlator.program.SimilarSymbolNameProgramCorrelator.doCorrelate(SimilarSymbolNameProgramCorrelator.java:67)
        at ghidra.feature.vt.api.util.VTAbstractProgramCorrelator.correlate(VTAbstractProgramCorrelator.java:77)
        at ghidra.feature.vt.gui.wizard.AddToSessionTask.run(AddToSessionTask.java:119)
        at ghidra.util.task.Task.monitoredRun(Task.java:124)
        at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
        at ghidra.util.task.TaskRunner$$Lambda$747/0x0000000800c0c440.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@14.0.2/ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@14.0.2/ThreadPoolExecutor.java:630)
        at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

```

Looking at [the code](https://github.com/NationalSecurityAgency/ghidra/blob/2b1235814d83355088411bace66a5e228ed2bd84/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/correlator/program/SimilarSymbolNameProgramCorrelator.java#L57), `doCorrelate` calls `findDestinations`, which iterates through the destination map, finds matching members, then iterates through those and adds them to the match set:

```java
for (Entry<Symbol, LSHCosineVectorAccum> entry : destinationMap.entrySet()) {
	if (monitor.isCancelled()) {
		return;
	}
	monitor.incrementProgress(1);
	Symbol destinationSymbol = entry.getKey();
	LSHCosineVectorAccum vector = entry.getValue();
	Set<DominantPair<Symbol, LSHCosineVectorAccum>> neighbors =
		sourceDictionary.lookup(vector);
	List<VTMatchInfo> members =
		transform(matchSet, destinationSymbol, vector, neighbors, threshold, monitor);
	for (VTMatchInfo member : members) {
		if (monitor.isCancelled()) {
			return;
		}
		if (member != null) {
			matchSet.addMatch(member);
		}
	}
}
```

The call to [`addMatch`](https://github.com/NationalSecurityAgency/ghidra/blob/2b1235814d83355088411bace66a5e228ed2bd84/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/db/VTMatchSetDB.java#L160) then calls into [`getOrCreateAssociationDB`](https://github.com/NationalSecurityAgency/ghidra/blob/2b1235814d83355088411bace66a5e228ed2bd84/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/db/AssociationDatabaseManager.java#L208), which then calls [`isBlocked`](https://github.com/NationalSecurityAgency/ghidra/blob/2b1235814d83355088411bace66a5e228ed2bd84/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/db/AssociationDatabaseManager.java#L259), which looks like this:

```java

private boolean isBlocked(Address sourceAddress, Address destinationAddress) {
	long sourceID = session.getLongFromSourceAddress(sourceAddress);
	long destinationID = session.getLongFromDestinationAddress(destinationAddress);
	try {
		Set<DBRecord> relatedRecords =
			associationTableAdapter.getRelatedAssociationRecordsBySourceAndDestinationAddress(
				sourceID, destinationID);
		for (DBRecord record : relatedRecords) {
			VTAssociationDB associationDB = getAssociationForRecord(record);
			VTAssociationStatus status = associationDB.getStatus();
			if (status == ACCEPTED) {
				return true;
			}
		}
	}
	catch (IOException e) {
		session.dbError(e);
	}

	return false;
}
```

This is already looking somewhat O(n^3) in nature, since there are three nested loops, but it's actually the [`getRelatedAssociationRecordsBySourceAndDestinationAddress`](https://github.com/NationalSecurityAgency/ghidra/blob/2b1235814d83355088411bace66a5e228ed2bd84/Ghidra/Features/VersionTracking/src/main/java/ghidra/feature/vt/api/db/VTAssociationTableDBAdapterV0.java#L96) call before the loop that's causing problems here.

Internally, it does this:

```java
@Override
Set<DBRecord> getRelatedAssociationRecordsBySourceAndDestinationAddress(long sourceAddressID,
		long destinationAddressID) throws IOException {
	Set<DBRecord> recordSet = new HashSet<DBRecord>();

	RecordIterator iterator = getRecordsForSourceAddress(sourceAddressID);
	while (iterator.hasNext()) {
		recordSet.add(iterator.next());
	}

	iterator = getRecordsForDestinationAddress(destinationAddressID);
	while (iterator.hasNext()) {
		recordSet.add(iterator.next());
	}

	return recordSet;
}
```

The code is reading all source and destination addresses from a buffer file, and each call into `next` on the iterator ends up in [`BufferMgr.loadCachedNode`](https://github.com/NationalSecurityAgency/ghidra/blob/2b1235814d83355088411bace66a5e228ed2bd84/Ghidra/Framework/DB/src/main/java/db/buffers/BufferMgr.java#L900). This then calls [`LocalBufferFile.get`](https://github.com/NationalSecurityAgency/ghidra/blob/2b1235814d83355088411bace66a5e228ed2bd84/Ghidra/Framework/DB/src/main/java/db/buffers/LocalBufferFile.java#L651).

The code there performs a single-byte read from the file, then a 4-byte read from the file, as separate operations:

```java
// Read version 1 buffer prefix
byte flags = raf.readByte();

// Read buffer ID
buf.setId(raf.readInt());
```

This means that two very small disk reads are being performed for every record in the set, twice, for every call to `isBlocked`, which is itself being called within a nested loop. Since the size of the record set appears to increase with every step, this appears to be at least O(n^2 log n) operations, each of which cause small file reads.

On Ghidra 10.0.1 on Windows 10 x64, running this over approximately 3300 destination symbols took an hour or so to get to 30%, then 15 more hours to get to 85%. I had initially thought that this was a CPU-bound issue, since it was using 100% of one core of a Xeon 8276L, but I later noticed that the core clock was being scaled down (via SpeedStep) and the 100% value was erroneous - it was not actually CPU bound at all.

Some thoughts:

- Instead of doing a single-byte read followed by a 4-byte read to the file on disk, which triggers separate filesystem operations, this can probably be optimised down to a single read to halve the latency.
- The table's in-memory cache is probably not doing much here, given that there are so many reads back from disk to re-populate the cache. Might be worth investigating why. My guess is that since everything is iterated it's just repeatedly loading and unloading the cache.
- If the `getOrCreateAssociationDB` call can be avoided on each `addMatch` call it would improve the situation greatly.
- Since each matchSet entry in `SimilarSymbolNameProgramCorrelator` is only a hundred bytes or so, it probably makes a lot more sense to just collect results in memory rather than trying to put them into the database one record at a time, then flush the lot at once when a size limit is reached.
- If the disk IO bottleneck can be entirely avoided, correlation seems to be a good candidate for parallelism.

I'm not super familiar with Ghidra's table / record system, though, so someone with more experience may have a better idea of how to fix this.

**Comment by gsuberland** [comment]
Note: `isBlocked` also appears to be a bottleneck for the "Adding X match objects..." stage of the process, which may be even more problematic since the number of objects can easily balloon to >1M.

**Comment by dragonmacher** [comment]
Thanks the well done write-up.   It certainly seems wasteful that the db is loading every potential association just to find one that would cause the check for `isBlocked()` to fail:

```
	@Override
	Set<DBRecord> getRelatedAssociationRecordsBySourceAndDestinationAddress(long sourceAddressID,
			long destinationAddressID) throws IOException {
		Set<DBRecord> recordSet = new HashSet<DBRecord>();

		RecordIterator iterator = getRecordsForSourceAddress(sourceAddressID);
		while (iterator.hasNext()) {
			recordSet.add(iterator.next());
		}

		iterator = getRecordsForDestinationAddress(destinationAddressID);
		while (iterator.hasNext()) {
			recordSet.add(iterator.next());
		}

		return recordSet;
	}
```

This should be able to stop searching once a single blocker is found.   While wasteful, it is not clear how much this would improve things.

The call to check for blocked must happen for each new match being added, since a previous match may block a following match being added.   But, as you point out, the algorithm could be smart enough to ensure that the bulk of matches being added in one correlator run would not interfere with each other.   If that were true, then each pre-existing match just needs to be validated against the db values at the start of the bulk add.    Certainly, if we could load those into memory at the start, this would be huge for performance.

There may also be some db improvements that could help, for example, having a table of ACCEPTED matches by address would allow a simple lookup for `isBlocked()`, rather than iterating records at each step.

**Comment by gsuberland** [comment]
Thanks for the quick reply. Is there anything I can provide that'd help expedite performance improvements in this area? Right now it's a blocker for using correlation on any binary with a symbol count exceeding a few thousand.

**Comment by gsuberland** [comment]
As a more general thought, it may be a good idea to have a specialised iterator for cached tables where you don't care about the order of results. If you iterate through a cached table in storage order, and use a last-access cache, that cache is guaranteed to be useless if the table size is greater than the cache size.

To demonstrate, imagine a cache of size 4, and table with 5 elements in it. The cache starts empty. You iterate through the table, and the last 4 elements that were read are now in the cache, i.e. `[2,3,4,5]`. Now you iterate again. The first element read, index 1, is not cached. So you cache it, evicting 2 as the oldest item. Now the cache is `[3,4,5,1]`. This repeats forever and you never get a cache hit.

With particularly large tables this problem starts happening at the OS level, too, since last-usage caching of file data is also affected negatively by this iterator pattern.

When you don't care about order and know that it's likely that you'll be doing a full iteration, or at least restarting iterations (e.g. repeated calls), it makes sense to have an iterator that always returns the cached items first, or at least an iterator that doesn't do cache eviction. Out of those two, the former probably makes more sense, since it's better to give early-out optimisations in the caller as many opportunities to do so before doing any reads that cause a cache miss.

Unsure if this is already a general thing in Ghidra, but if not it might be a pattern that could improve performance all over the place.

**Comment by dragonmacher** [comment]
> Right now it's a blocker for using correlation on any binary with a symbol count exceeding a few thousand.

For now, you can avoid running these 2 correlators on large binaries unless you need to.   The more primitive correlators may find enough matches, depending upon the structure of changes to the binary.

**Comment by dragonmacher** [comment]
I'm exploring some of the ideas in this ticket.   I would like to be able to reproduce the slowness before I start making changes.   I started the process by use a binary with about 18k symbols.   I used this program as both the source and destination program for my version tracking session.   The `SimilarSymbolNameProgramCorrelator` finished in less than a minute.     I also tried running the exact correlators first, accepting all matches.

In your example, are you version tracking a binary with many more symbols than my example?   Do you know of any publicly available binaries that would exhibit the issue in this ticket?

**Comment by gsuberland** [comment]
I can't remember to be honest. If I was running this against ntoskrnl then it would've had around 50k symbols, but I can't remember if that was indeed the target.

I mentioned 3300 destination symbols in the original report, but I'm unsure if that's 3300 globally or 3300 possible targets for correlation.
