### ISSUE TITLE
[Sleigh] Custom slaspec freezes Ghidra

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#3227]
I'm trying to implement a custom proc and my implementation freezes Ghidra.

In this cpu strings are encoded into opcodes. For example `FF AA 'HELP ME' FF BB`, where `FF AA` is string printing opcode, and `FF BB` is string termination token.

I've created many variations of a string length in two ways:
```cpp
define token string16 (16)
    str16 = (0,15)
;

...

define token string512 (512)
    str512 = (0,511)
;
```

and this way:
```cpp
StrEnd: is AdcOp & (op_lsb=0x28 | op_lsb=0x20 | op_lsb=0x36) {}

Str1: str16 is str16 {}
Str2: str16 is str16 {}

...

Str: Str1 is Str1; StrEnd {}
Str: Str1,Str2 is Str1;Str2; StrEnd {}

...

Str: Str1,Str2,Str3,Str4,Str5,Str6,Str7,Str8,Str9,Str10,Str11,Str12,Str13,Str14,Str15,Str16,Str17,Str18,Str19,Str20,Str21,Str22,Str23,Str24,Str25,Str26,Str27,Str28,Str29,Str30,Str31,Str32,Str33,Str34,Str35,Str36,Str37,Str38,Str39,Str40 is Str1;Str2;Str3;Str4;Str5;Str6;Str7;Str8;Str9;Str10;Str11;Str12;Str13;Str14;Str15;Str16;Str17;Str18;Str19;Str20;Str21;Str22;Str23;Str24;Str25;Str26;Str27;Str28;Str29;Str30;Str31;Str32;Str33;Str34;Str35;Str36;Str37;Str38;Str39;Str40; StrEnd {}

```

Usage:
```cpp
:MSGOUT Str is op_msb=0xFF & op_lsb=0xAA; Str {
	msgout(Str);
}
```

Both variants make Ghidra freezed at the binary loading stage. CPU is 100%, Memory usage is high too.

Is there any way to implement variable strings or opcodes in Sleigh?

**Comment by lab313ru** [comment]
It looks like `OR` in `StrEnd` freezes Ghidra. Leaving only one variant resolves the problem. So, my question is still open.

**Comment by ghidra1** [comment]
While your slaspec is incomplete to properly evaluate, you should keep in mind that it is possible to produce infinite parsing loops in the slaspec.  I don't see a definition for `AdcOp`.

**Comment by ghidra1** [comment]
@lab313ru if you can attach your entire slaspec we can better evaluate.
