### ISSUE TITLE
[Sleigh] How to display a char?

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#3228]
I'm working on a sleigh-describing a cpu, which uses ascii strings encoded into opcodes. So I've defined a symbol:
```cpp
Char: " " is str8=0x20 & str8_2 { export 0x20:1; }
```

But how to display a `"` or other ascii symbols?

**Comment by astrelsky** [comment]
> I'm working on a sleigh-describing a cpu, which uses ascii strings encoded into opcodes. So I've defined a symbol:
> 
> ```c++
> Char: " " is str8=0x20 & str8_2 { export 0x20:1; }
> ```
> 
> But how to display a `"` or other ascii symbols?

Try `Char: ^" " is str8=0x20 & str8_2 { export 0x20:1; }`

**Comment by lab313ru** [comment]
I mean space is not a problem. The problem is `^`, `'`, `_` and other ascii chars. I don't sure they can be escaped like that.

**Comment by GhidorahRex** [comment]
If they're in the quotes I believe sleigh should be okay with it

**Comment by lab313ru** [comment]
How to make double quote `"` in quotes? I mean escaping some chars?

**Comment by GhidorahRex** [comment]
Yes, that one probably isn't possible in sleigh. I don't know of a mechanism for that.

**Comment by astrelsky** [comment]
Would using the unicode left/right double quote characters work?
