### ISSUE TITLE
Unable to decompile code

### ISSUE THREAD

**Issue by DoMINAToR98** [NationalSecurityAgency/ghidra#323]
Getting the error below on running ghidra on any binary
`
----- Loading /root/Desktop/absolute/crackme02 -----
Failed to properly markup GNU Hash table at 00100298: ghidra.program.model.util.CodeUnitInsertionException: Insufficent memory at address 001002b4 (length: 36 bytes)
  [libc.so.6] -> not found
----- [crackme02] Resolve 6 external symbols -----
Unresolved external symbols which remain: 6
`
Tried running ghidra on a vm (on the same system) but still getting the same error.
Unable to decompile or see the functions inside the binary. 

OS: MacOSX (high sierra)
Java Version: 11

**Comment by nihilus** [comment]
Probably because of ELFkickers 'sstrip' or something like it, try to manually recreate the ELF headers.

**Comment by GhidorahRex** [comment]
I wasn't able to reproduce this at present due to insufficient information. If there are any additional problems, please submit a new issue.
