### ISSUE TITLE
Java Swing IndexOutOfBoundsException when using the data type manager

### ISSUE THREAD

**Issue by diamante0018** [NationalSecurityAgency/ghidra#3240]
**Describe the bug**
The bug affects the data type manager. I have parsed a C header containing C structs successfully, these structs have been saved in a subfolder inside the data type manager window. I have later modified one of the structs inside this folder and since then I have been unable to open it or make use of any of the data structures defined in this subfolder.

**To Reproduce**
Steps to reproduce the behaviour:
** Disclaimer **
I have not kept track of every single step I took before I got this bug, I followed the documentation and the tutorials I found to learn how to parse C header files. The steps described below may not be 100% accurate.
1. Have a structure already defined in the datatype manager
3. Parse a C header containing a definition for the same structure (same name)
4. Now the two structures should be in the data type manager (same name but different folders/categories)
5. Delete "old" structure definition. Now there should be only one struct with the same name saved in the newly created category (saved by the C parser)
6. See error when trying to use the structure or opening the subfolder/category created by the C parser.

**Expected behaviour**
I would expect to use the struct the same way as if I created it manually using the Ghidra struct editor.

**Attachments**
[error.txt](https://github.com/NationalSecurityAgency/ghidra/files/6847954/error.txt)

**Environment (please complete the following information):**
Build Date: 2021-Jun-21 1239 EDT
Ghidra Version: 10.0
Java Home: C:\Program Files\Java\jdk-11.0.11
JVM Version: Oracle Corporation 11.0.11
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-BI42GK0

**Additional context**
I have probably caused the bug because I was careless about the naming of my structs (duplicate name but in a different subfolder) because that's the only thing that I recall that might be the source of my problem. What should I do? Delete the subfolder containing the parse structs and try again?

**Comment by dragonmacher** [comment]
My guess is that the database value for `numComponents` is out of sync with the number of items inside of `components`.   When the data type gets loaded from the database, there is no code to ensure that these values are consistent.   Clearly there is some set of operations that allowed the db record to get into this state, but it is not clear what are those steps.

I suggest deleting the bad type and trying to recreate it.  If you can not delete from the UI, you can try creating a script that will delete the type.

**Comment by diamante0018** [comment]
I have successfully deleted the bad type from the UI. It required a few attempts because interaction via the UI caused the same error multiple times. I was able to parse the type again with nor errors this time. I suspect even more it has to do with the duplicate name of the type although they were saved in different folders.

**Comment by dev747368** [comment]
@diamante0018 - you are probably focusing on a trivial issue (types with duplicate names in different folders).  Instead it is more likely a deficiency in the structure datatype's db code to handle events when embedded types are being changed out from underneath it.  (just trying to focus your troubleshooting efforts)

It would be very helpful if you happened to figure out what steps (ie. deleting / overwriting via drop-n-drop or importing/modifying), etc of embedded types, or whatever it was that triggers this.

**Comment by gtackett** [comment]
There used to be a bug in at least some windows that included filters (and specifically observable in Data Type Manager) that if you renamed something so that its name was filtered out of the view, you could get Java exceptions.
It may not be a concern here, as I believe that’s been fixed recently, and I see you’re using Ghidra 10.0.
Just mentioning it in case the fix didn’t make it in, or in case of a possible regression.

**Comment by diamante0018** [comment]
Hasn't happened anymore. Closing this as I can't add anything helpful to this topic.
