### ISSUE TITLE
"Set External Program" causes Ghidra to deadspin when connected to server

### ISSUE THREAD

**Issue by hedgeberg** [NationalSecurityAgency/ghidra#3245]
**Describe the bug**
When connecting to a Ghidra server, if the connection is active, using the "Set External Program" right-click option in the symbol tree causes the entire  JVM instance to hang and become nonresponsive. Issue observed in 10.0.1 for both Linux and Windows, but only tested with PE binary and DLL external programs.

**To Reproduce**
1. Make a new shared project and connect to a server
2. Load in a couple of windows .dll files
3. Add to version control so that they sync to the server.
4. Open one of the dll's, expand the "Imports" section on the symbol tree
5. Right click  on one of the external DLLs, select "Set External Program", ghidra will hang.

**Expected behavior**
"Set External Program" behaves as it would normally in an unshared project

**Screenshots**
What the bug looks like on Win 10:
![bugreport](https://user-images.githubusercontent.com/3290125/126400291-15bff53d-cc4b-4aa7-a25e-b14e5923c972.PNG)

**Attachments**
Reviewing the log after force-quitting and restarting ghidra shows the following: 
[bugreport_log.txt](https://github.com/NationalSecurityAgency/ghidra/files/6851451/bugreport_log.txt)

**Environment (please complete the following information):**
 - OS: Win10
 - OpenJDK 12.0
 - Ghidra Version: 10.0.1_Public
 - Ghidra Origin: Github releases page

(Also occurs on Arch Linux w/ same ghidra version and openjdk 14.0)

**Additional context**
Can be worked around by disconnecting from the server with the working file and the external programs checked out, setting the external programs in offline mode, and then reconnecting and checking the files back in.

**Comment by dev747368** [comment]
@hedgeberg how many items/folder does your shared project have?

It looks like the "Set External Program" action is trying to be helpful and is searching for a similarly named binary as the external that you clicked on.  This may be a bad idea when the project is huge.

**Comment by hedgeberg** [comment]
It's definitely a massive project. Something like 20k files due to some automated imports earlier on. That being said, I haven't had this issue on non-server projects, suggesting that the external program dialog is specifically struggling with whatever queries it's making to the server.

**Comment by dev747368** [comment]
There is definitely some RPC overhead when the project is remote and there are a lot of round-trips involved, which is the case when iterating a project.

**Comment by dragonmacher** [comment]
Sounds like this hasn't been tested at scale.  This can likely be fixed by putting the call into a task.
