### ISSUE TITLE
[PowerPC] Ghidra decompiler doesn't understand non-r2 SDA

### ISSUE THREAD

**Issue by NWPlayer123** [NationalSecurityAgency/ghidra#325]
Context: GameCube and Wii are compiled with two Small Data Area/Table Of Contents (SDA/TOC) registers, that it reserves for single-instruction data manipulation, r2 *and* r13. Right now it looks like it only understands r2.
Whenever it hits r13, it sets a variable and then manually shows the (r13 - 0x____) as a variable, instead of knowing that there's a variable there, which gives really terrible decompilation results.

![Screenshot_444](https://user-images.githubusercontent.com/3280345/55535642-ff3e9f80-5674-11e9-9287-6238d7f58900.png)

**Comment by tmbinc** [comment]
Some PowerPC code I've seen even uses r2,r13,r14,r15,r16 (GM E98 ECU; not sure which compiler this is).

**Comment by caheckman** [comment]
Just looking at the screenshot, it looks like r13 may be getting treated as a save register, which I think is a non-standard ABI.  You could try adding r13 to the unaffected list in the cspec to see if this helps decompilation. Its hard to tell from the screenshot, but I'm assuming you're using ppc_32_be.cspec. Look for the lines:

      <unaffected>
        <register name="r14"/>
        <register name="r15"/>
        <register name="r16"/>
        <register name="r17"/>

Add a "<register name="r13"/> line, then save and restart.

You also might want to investigate turning on in-lining or applying a call-fixup for the _savegpr_26 function. It looks suspiciously like an internal compiler function.

**Comment by NWPlayer123** [comment]
@caheckman yeah,
1) GameCube/Wii are big endian aka PPC32BE
2) restgpr and savegpr are part of the Metrowerks/CodeWarrior EABI w/e, I just didn't bother fixing the def and inlining for the screenshot
3) I'll try that and report back. I haven't figured out how to refresh decomp but I'll take your word that it just needs a restart

**Comment by NWPlayer123** [comment]
@caheckman it works, papa bless you
![Screenshot_450](https://user-images.githubusercontent.com/3280345/55662874-0c72a000-57d5-11e9-815c-c8dcb1581b61.png)
![Screenshot_451](https://user-images.githubusercontent.com/3280345/55662875-0c72a000-57d5-11e9-8b72-044744402960.png)

**Comment by derek57** [comment]
@NWPlayer123:

I came across this a few days ago:

https://github.com/aldelaro5/ghidra-gekko-broadway-lang

Would you mind creating a pull request which the guy maintaining this plugin could add there?

Thanks in advance

**Comment by aldelaro5** [comment]
> @NWPlayer123:
> 
> I came across this a few days ago:
> 
> https://github.com/aldelaro5/ghidra-gekko-broadway-lang
> 
> Would you mind creating a pull request which the guy maintaining this plugin could add there in order to make decompilation of the Broadway / Gekko stuff even better? I mean also this stuff you described here. I came across this as well upon decompilation of the debugger kernel which was a royal pain in the a**...
> 
> Thanks in advance.

It's already been fixed 20 days ago: https://github.com/aldelaro5/ghidra-gekko-broadway-lang/commit/d4a57a619f3659d0fc302f5478bc06042fb69dba

**Comment by RenaKunisaki** [comment]
Am I doing something wrong? It still doesn't seem to recognize labels relative to r13.

**Comment by derek57** [comment]
> 
> 
> Am I doing something wrong? It still doesn't seem to recognize labels relative to r13.

I'm also still having the same issue as you.

**Comment by NWPlayer123** [comment]
Did you actually set r2/r13? @derek57 @RenaKunisaki 
You need to actually set it, and then modify the address range to the whole thing, maybe a re-analyze, and then it should work.
If you're doing GameCube/Wii, https://github.com/Cuyler36/Ghidra-GameCube-Loader will auto-find the values for you with a custom analysis option.
<details>

![Screenshot_466](https://user-images.githubusercontent.com/3280345/70752676-5743a080-1cf0-11ea-9205-c82657f74329.png)
![Screenshot_467](https://user-images.githubusercontent.com/3280345/70752678-5743a080-1cf0-11ea-82b1-81a2a091d42a.png)
![Screenshot_468](https://user-images.githubusercontent.com/3280345/70752677-5743a080-1cf0-11ea-9b77-2cc535cdf2ff.png)
![Screenshot_469](https://user-images.githubusercontent.com/3280345/70752776-8823d580-1cf0-11ea-9ea0-cbbc8e2d4ffb.png)

</details>

**Comment by RenaKunisaki** [comment]
I did get it, but I'm really not sure how. It felt like it just decided to work.

**Comment by derek57** [comment]
Well, I finally got it done - thx to @NWPlayer123.

Isn't it possible to directly implement this into @aldelaro5's Ghidra Gekko repo?
