### ISSUE TITLE
Ghidra Logo is Invisible on Ubuntu

### ISSUE THREAD

**Issue by TheMatt2** [NationalSecurityAgency/ghidra#3253]
**Describe the bug**
When Ghidra Application is open, the icon in Dock is invisible.
Clicking and dragging the icon reveals the red dragon logo.

This seems to be related to screen resolution.

**To Reproduce**
1. Open Ghidra
2. Look at Dock
3. See that there is no Ghidra logo
4. Click and drag the Dock section, see that the logo is present while dragging.
5. In settings, change screen resolution. See logo now appears.

**Expected behavior**
The logo should be visible all the time.

**Screenshots**
Logo invisible, occurs with screen resolution 1920 x 950

![Invisible Ghidra](https://user-images.githubusercontent.com/22862051/126549177-5619d8ef-90db-4d0f-81c6-5745b51da518.PNG)

After changing screen size, the logo appears.
![Ghidra logo visible](https://user-images.githubusercontent.com/22862051/126549331-a4f2db28-11ce-4f49-91be-c6c98a74c906.PNG)

**Environment (please complete the following information):**
- OS: Ubuntu 20.04.2 LTS
- Java Version: 11.0.11
- Ghidra Version: 10.0.1 PUBLIC 2021-Jul-8 1512 EDT
- Ghidra Origin: Github releases page

**Additional context**
Despite this issue seeming to be partly a problem in the OS, it is the dock in Ubuntu, this issue seems unique to Ghidra.

**Comment by dev747368** [comment]
Duplicate of #463.

It sucks, but its an issue that can't be fixed from the java side.
