### ISSUE TITLE
NPE on Display Size Change in Virtual Machine

### ISSUE THREAD

**Issue by TheMatt2** [NationalSecurityAgency/ghidra#3255]
**Describe the bug**
Null Pointer Exception occurs when resizing windows in VirtualBox.
Occurred while enabling a second window in VirtualBox, with two physical monitors connected to the computer.

**To Reproduce**
Unable to reproduce reliably. This is roughly the step followed, but clearly there are additional factors.

1) Open Ghidra in VirtualBox machine
2) Enable second monitor in VirtualBox
3) Resize second window (the one that is blank)
4) Drag second window unto second physical window
5) Make second window full screen.
6) Observe the screen glitch out, as virtual box sets up windows.
7) Error report is created in Ghidra

**Expected behavior**
No error is created in Ghidra

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

[npe_ghidra.txt](https://github.com/NationalSecurityAgency/ghidra/files/6864563/npe_ghidra.txt)

**Environment (please complete the following information):**
- VM OS: Ubuntu 20.04.2 LTS
- Host OS: Win10
- Java Version: 11.0.11
- Ghidra Version: 10.0.1 PUBLIC 2021-Jul-8 1512 EDT
- Ghidra Origin: Github releases page
- Virtual Machine: VirtualBox 6.1.22 (Qt5.6.2)

**Additional context**
I've only ever managed to cause it on initial addition of the second window. To get the error a second time, it seems restarting the virtual machine is needed.

**Comment by ryanmkurtz** [comment]
This is typically a problem within the JDK.  Sometimes fiddling with the `sun.java2d.*` JVM arguments in `support/launch.properties` can help.  You also might want to try a "Look and Feel" other than **Nimbus**, which I see in the stack trace:

From the front end GUI:
* Edit --> Tool Options...
* Tool
* "Swing Look and Feel"

**Comment by TheMatt2** [comment]
To be clear, this error occurs rarely, and Ghidra continues to work properly. Though I will experiment with the Look and Feel settings available from the Ghidra Project Window.

**Comment by TheMatt2** [comment]
Update: Issue occurred again on resizing windows.

However, there were two instances of Ghidra open at the time. The error only occurred one instance. Seeming to indicate that this bug is some what random by its nature.

**Comment by ryanmkurtz** [comment]
Since this is an issue with the JDK on your platform, I am going to go ahead and close the ticket, keeping it available as a reference.  Hopefully a future release of the JDK will fix the issue.
