### ISSUE TITLE
Will you release the Sleigh grammar files?

### ISSUE THREAD

**Issue by NeatMonster** [NationalSecurityAgency/ghidra#326]
Hello there,

Will you release the Sleigh grammar files referenced everywhere in the project?

- `ghidra/sleigh/grammar/BaseLexer.g`
- `ghidra/sleigh/grammar/BooleanExpression.g`
- `ghidra/sleigh/grammar/DisplayLexer.g`
- `ghidra/sleigh/grammar/DisplayParser.g`
- `ghidra/sleigh/grammar/SemanticLexer.g`
- `ghidra/sleigh/grammar/SemanticParser.g`
- `ghidra/sleigh/grammar/SleighCompiler.g`
- `ghidra/sleigh/grammar/SleighEcho.g`
- `ghidra/sleigh/grammar/SleighParser.g`

Thank you!

**Comment by nsadeveloper789** [comment]
Yes! See `Ghidra/Framework/SoftwareModeling/src/main/antlr` in the repo.

**Comment by NeatMonster** [comment]
Thanks! I didn't expect it to be that fast. 😄

@nsadeveloper789 Could you also take a look at [this issue](https://github.com/NationalSecurityAgency/ghidra/issues/315) please?
