### ISSUE TITLE
possible SearchTextPlugin bug

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#3265]
I noticed ctrl+shift+r stopped working, but then noticed things like `s/`up/down/pgup/pgdn also stopped responding.  I had been using ctrl+shift+r and accidentally pressed ctrl+shift+e.

Looking at filters (and any text field for that matter once I touch it) starts with an <ins>e</ins> and cannot be deleted except with the red X.  Any typing in the filter will start with the <ins>e</ins>

Typing a bunch of characters and then opening a comment window (using the mouse) would have the <ins>e</ins> and all the characters

ctrl+shift+e, esc, or enter appears to exit this mode.  I did notice a small bubble pop-up in the corner with an `e` followed by characters

I tried getting this plugin to work like it should/could after I realized the key binding I had pressed, but never found anything functional.  I'm guessing the <ins>e</ins> being inserted is the core of it not working.  The Search->Program Text window through the menus works fine/as normal.

 - OS: ubuntu 20.04 /64-bit
 - Java Version: 11.0.11
 - Ghidra Version: master
 - Ghidra Origin: self-build (run through eclipse)

**Comment by dragonmacher** [comment]
I'm having a hard time parsing this.

Is there a series of steps we can try to reproduce the issue?

**Comment by mumbel** [comment]
Heh, sorry

I should just said `cannot use shortcut ctrl+shift+e to open Search Text Plugin`

On my setup, 20.04 and running from eclipse/master, a small text bubble pops up in the bottom left and the search text window does not appear.  The next text box I use will have an underlined `e` and any printable characters pressed since the shortcut combo.  The e cannot be deleted, but the box text can be cleared (backspace vs red X)

**Comment by dragonmacher** [comment]
This sounds to me like a system-level Input Method Editor feature.  Since you say it is not in other apps, maybe it is specific somehow to Ghidra.   As far as I know, Java does not provide this functionality, which means it must be done by the OS.   But, maybe your IME tool can have it work only within the app you are running.

**Comment by mumbel** [comment]
Well I guess I should have done a quick google search for the combo

https://askubuntu.com/questions/1083913/what-does-ctrl-shift-e-do-while-typing-text

**Comment by ryanmkurtz** [comment]
Was just entering that link.  I've confirmed that unassigning it in `ibus-setup` fixes it.
