### ISSUE TITLE
Add "Calling Convention" to .gdt file

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3267]
**Is your feature request related to a problem? Please describe.**
After defining lots of function prototypes and having had to manually update the calling convention, transferring these to a second application loses the calling convention.

**Describe the solution you'd like**
The calling convention should be stored as part of the function protocol.

**Describe alternatives you've considered**
Maintaining a list of functions and their protocols outside Ghidra and writing a script to reimport these.

**Additional context**
N/A.

**Comment by astrelsky** [comment]
This could be achieved by adding a table into the gdt to store the calling convention names as well as the language version (in case they are changed). Then storing the index into said table instead of the index of the generic calling convention enum would not require a schema change for `FunctionDefinitionDB`.

**Comment by Wall-AF** [comment]
Same issue in `.fidb` files too!

**Comment by ghidra1** [comment]
We are aware of the possibility and hope to address in the future.

**Comment by Wall-AF** [comment]
> 
> 
> It is only a symbol name that is saved and applied by FID. As mentioned, this works best with mangled names. FID can apply multiple symbols based upon possible matches at the same location - this would not be possible with a complete function spec.
> 
> If you add the FID related plugins you can view the actual FID tables and data stored.

Thanks for that explanation.  I hadn't delved into it and just assumed the hashes were all encompassing!

Maybe some alternative is required as its a pain!

**Comment by ghidra1** [comment]
Assuming you don't have mangled names.  You could create your own mangling scheme - just need to avoid existing GNU and Microsoft mangled prefixes.  Mangle the names of all the functions being hashed before generating your FID data.  Create your own corresponding demangler to process the applied mangled names after FID applies them.  It could be worth it if you expect to benefit from FID.

**Comment by DualTachyon** [comment]
@Wall-AF Thanks a lot for your patch! While it may be temporary, it solved my immediate problems! I have just tested it now and it is indeed using my local convention and the decompiled output is now proper!.

@ghidra1 I'm OK to close this as a duplicate of the other issues.

**Comment by ryanmkurtz** [comment]
@DualTachyon I closed your other issue as a duplicate of this one.

**Comment by ghidra1** [comment]
The ability to preserve calling conventions with datatype archives is now supported.
