### ISSUE TITLE
Analysis options not enforced with follow-on analysis

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#3274]
With the change in analysis options to a saved profile, it looks like the analysis options that are saved are not enforced during the follow-on analysis from other actions (e.g. disassemble a new function could trigger analysis).  I have specific options disabled in my saved profile that break my images I load.  Before the saved profile feature I was able to disable these features while loading the image and doing initial analysis (first thing I typically did is open auto-analysis window disable things and escape the window, and then begin to apply scripts/structs/disassembly)

**To Reproduce**
1. load image
2. do not auto-analysis
3. open auto-analysis options and deselect/select options (in my case deselect noreturn)
4. run scripts/actions to parse image (disassemble image basically), this will trigger some additional analysis
5. noreturn will be used in prototypes and flow applied.

**Expected behavior**
If noreturn is deselected in the analysis options window, noreturn should not appear on any prototypes.

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: windows 10
 - Java 11.0.10
 - Ghidra 10.0.1
 - Ghidra Origin: official

**Additional context**
printf of all things is getting flagged noreturn in my firmware, which is obviously pretty breaking for flow.   I am making a huge assumption this is the cause (the saved profile), but I'm not sure where else noreturn would be toggled.  Also is there a term for this "follow-on" analysis phase vs the act opening up the auto-analysis window and starting it off?
(ppc 32 BE raw binary)

**Comment by ryanmkurtz** [comment]
Thanks, we are taking a look.

**Comment by ryanmkurtz** [comment]
I've been told that escaping the window no longer saves the changes like it used to...you have to hit Analyze.  There is talk of adding a 3rd button to the window that will save the options without running analysis.

**Comment by mumbel** [comment]
I was able to repro again.

- in frontend loaded firmware (PPC BE 32), set name and start offset
- in browser, broke memory into additional segments, set permissions
- opened auto-analysis window, verified noreturn option was unchecked and that the profile name was currently mine (didn't change drop-down and was not `Current Program Defaults` or `Standard Defaults`)
- clicked cancel in auto-analysis window
- ran script
- script finishes, analysis from all the disassembly continues and finishes
- printf is a noreturn with all callers having `Flow Override: CALL_RETURN (CALL_TERMINATOR)`

Would there possibly be some other setting to toggle `noreturn` that's new and I'm just incorrectly focusing on the profile stuff?

**Comment by ryanmkurtz** [comment]
I just got some additional info on this feature.  This confusion is that while the analysis options you see selected are correctly from your profile, they don't actually get applied into the program until you hit Analyze.  We are currently rethinking this feature to avoid the confusion.  A workaround would be to start and stop analysis, and then undo it.  This should result in your desired analysis options being loaded into the program for future actions to use.

**Comment by mumbel** [comment]
@ryanmkurtz  thanks for the info.  There's no reason I'm not analyzing really, but did have some issues in one image where .data was messing up .text (assigning DAT_ or misaligned instructions), so I started running this script first before auto-analysis to get fewer errors to cleanup.
