### ISSUE TITLE
Windows launch.bat doesn't support paths with spaces on 10.0.1

### ISSUE THREAD

**Issue by qwertymodo** [NationalSecurityAgency/ghidra#3275]
**Describe the bug**
Unable to launch from a path containing a space.

**To Reproduce**
1. Extract the ghidra 10.0.1 release on a Windows machine into a directory containing a space
2. Run ghidraRun.bat
3. Error is displayed: "portion\of\path\after\space==portion\of\path\before\space was unexpected at this time."

**Expected behavior**
Ghidra should open

**Environment (please complete the following information):**
 - OS: Windows 10 21H1
 - Java Version: 11.0.5
 - Ghidra Version: 10.0.1
 - Ghidra Origin: Official github release download

**Additional context**
The error seems to be in support/launch.bat, line 42:

if not %SUPPORT_DIR:!=%==%SUPPORT_DIR% (

Adding quotes like so fixes the issue:

if not "%SUPPORT_DIR:!=%"=="%SUPPORT_DIR%" (

**Comment by topia** [comment]
This is a known issue and already fixed in the repository; please wait for the next release.
https://github.com/NationalSecurityAgency/ghidra/commit/22962564641b443dc445ef61312496ff38c6b384
