### ISSUE TITLE
About the undefined

### ISSUE THREAD

**Issue by zswaaa** [NationalSecurityAgency/ghidra#3276]
When i use the Ghidra to decompile the so library , The result contains many undefined and undefined1, I use the result to compare with the formal parameters , so how can i convert those undefine to  right parameter, Thank you very much.

**Comment by Danil6969** [comment]
These are actually ghidra default datatypes.
Look at the header from `Export Program` action for better understanding (comments added for clarity):
typedef unsigned char   undefined; //size = 1

typedef unsigned char    byte; //size = 1
typedef unsigned char    dwfenc; //size = 1
typedef unsigned short    word; //size = 2
typedef unsigned int    dword; //size = 4
typedef long long    longlong; //size = 8
typedef unsigned long long    qword; //size = 8
typedef unsigned short    ushort; //size = 2
typedef unsigned int    uint; //size = 4
typedef unsigned long    ulong; //size = 4
typedef unsigned long long    ulonglong; //size = 8

typedef long double float10;

typedef unsigned char           undefined1; //size = 1
typedef unsigned short          undefined2; //size = 2
typedef struct { byte arr[3]; } undefined3; //size = 3
typedef unsigned int            undefined4; //size = 4
typedef struct { byte arr[5]; } undefined5; //size = 5
typedef struct { byte arr[6]; } undefined6; //size = 6
typedef struct { byte arr[7]; } undefined7; //size = 7
typedef unsigned long long      undefined8; //size = 8
