### ISSUE TITLE
Clear name to go back to default Ghidra assigned name

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#3285]
**Is your feature request related to a problem? Please describe.**
Currently you cannot enter in an empty name.  If an empty name is entered, let it default back to whatever Ghidra did or would name it.

**Describe the solution you'd like**
This could be for a global DAT_*, FUN_*, or SUB_* (maybe others).  If it is named but incorrect, it would be nice to be able to easily revert to the non-user assigned value and reset it back to a Ghidra value (this could have implications in source? or nothing really that would matter)

**Describe alternatives you've considered**
Determine the address from instructions or jumping to label for address and just rename DAT_ or FUN_ and append the address

**Additional context**
For unmapped memory, you cannot goto the label and delete it which would provide this functionality, and to get the address the instruction(s) operand(s) would need to be parsed to calculate the address

**Comment by dragonmacher** [comment]
This should happen now if you delete the existing non-default label.     When the label is removed, Ghidra will put back a default label.

**Comment by mumbel** [comment]
Ah, sorry @dragonmacher   It didn't click that I was using an older version of Ghidra right now (I'll double check when I get home and close this if its handling the use case I'm thinking of)

**Comment by dragonmacher** [comment]
This feature has been there since the beginning.   If it is not working for you, then either you have an edge case or I may not quite understand the issue.

**Comment by mumbel** [comment]
I think my issue was the reference wasn't in the listing window, so I didn't have a label there, only in the decompiler so that was throwing me off (I knew I had done this before, just forgot about `delete`).  So I guess the 4 use case I can think of would be something like: (where I guess I'm asking for all 4 to be available)

- listing window you can press `delete` any label and prompted to have it remove reference or label
- listing window you cannot rename label to empty
- decompiler you cannot press `delete`
- decompiler you cannot rename label to empty
