### ISSUE TITLE
"ghidra.program.model.util.CodeUnitInsertionException: Insufficent memory" during loading a Hello World executable

### ISSUE THREAD

**Issue by msmuenchen** [NationalSecurityAgency/ghidra#3287]
During ingestion of a Hello World CLI EXE compiled with Borland C++ 5.02 (compiler available at https://archive.org/details/Borland_C_Builder_Developers_Suite_V5), I get this error:

    2021-07-31 | 09:07:29 | ERROR | (PeLoader) Error laying down header structures ghidra.program.model.util.CodeUnitInsertionException: Insufficent memory at address 004003e8 (length: 40 bytes)

Apparently, Ghidra fails to initialize the .reloc section:
![image](https://user-images.githubusercontent.com/2284268/127732214-068bc44f-7335-4017-a23a-b12e2eb636ca.png)

Manually setting the data fields shows that it fails because the header segment is too tiny in the RAM allocation:
![image](https://user-images.githubusercontent.com/2284268/127732310-04b2b2dc-fbf2-4757-8349-c6017968cd5b.png)
![image](https://user-images.githubusercontent.com/2284268/127732349-c901dc10-0883-403f-b528-1f81cb5330cf.png)

I assume this is either a compiler bug or a size optimization by the compiler that Ghidra can't ingest - assuming the Windows Kernel/Linker loads the headers into a zero padded section of RAM, it will see all zeroes for the missing fields.

The binary is attached: [helloworld_cli.exe.zip](https://github.com/NationalSecurityAgency/ghidra/files/6910827/helloworld_cli.exe.zip)

**Comment by ryanmkurtz** [comment]
This is unfortunate.  I'm inclined to just not support this strange case.  It doesn't have an affect on the analysis of the binary...just laying down the fixed-size `IMAGE_SECTION_HEADER` structure.
