### ISSUE TITLE
missing definition for int_least8_t

### ISSUE THREAD

**Issue by micsthepick** [NationalSecurityAgency/ghidra#3294]
**Describe the bug**
int_least8_t, along with other definitions are missing when running "Parse C source"

**To Reproduce**
1. Open the Code browser with a g++ compiled application
2. Click: File -> Parse C Source
3. Select Clib.prf
4. change the Include directories in "Parse Options" to point to mingw32's gcc include directory (mine was -IC:\mingw32\lib\gcc\i686-w64-mingw32\8.1.0\include)
5. Click "Parse to Program" or "Parse to File"

**Expected behavior**
The parser recognises int_least8_t and other variants found in stdint-gcc.h, and successfully parses.

**Screenshots**
![image](https://user-images.githubusercontent.com/11528421/127757201-2c84ba44-f0be-42df-b751-0374a78a40f6.png)

**Attachments**
None.

**Environment (please complete the following information):**
 - OS: Windows 10, Version: 10.0.19043 Build 19043
 - Java Version: 11.0.11
 - Ghidra Version: 10.0.1
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by astrelsky** [comment]
The c parser does not use the compiler and therefore does not have the the compiler's built in preprocessor definitions. You can dump them with the command `i686-w64-mingw32-gcc -dM -E -v - < /dev/null` and then add them to the parse options. Just copy everything starting with `#define` to a text editor of your choice and use regex to convert them to the correct form. Be sure to add the default include paths from the output as well. You will still need a few custom options like the one for `__builtin_va_list` but this should cover most cases.

iirc the expression replacing `#define\s+(\S+)\s+(\S+)` with `-D$1=$2` should convert *most* of them.
