### ISSUE TITLE
Error when building Ghidra with Gradle 5.2.1

### ISSUE THREAD

**Issue by mewmew** [NationalSecurityAgency/ghidra#330]
**Describe the bug**

Following the build instructions outlined in the [DevGuide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md), an error is reported during the *Import Gradle Project* step, namely:

```
u@x1 ~/D/g/ghidra> gradle eclipse
FAILURE: Build failed with an exception.

* Where:
Build file '/home/u/Desktop/ghidra_play/ghidra/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating root project 'ghidra'.
> Requires Gradle 5.0, but was run with 5.2.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**To Reproduce**
1. Navigate to the root directory of ghidra.
2. Run `gradle eclipse` with Gradle version 5.2.1 installed

**Expected behavior**

Successful build.

**Environment (please complete the following information):**
 - OS: Arch Linux

```
$ uname -a
Linux x1 5.0.5-arch1-1-ARCH #1 SMP PREEMPT Wed Mar 27 17:53:10 UTC 2019 x86_64 GNU/Linux
```

 - Java Version: jdk-openjdk 11.0.3.u4-1

 - Ghidra Version: `49c2010b63b56c8f20845f3970fedd95d003b1e9` (Ghidra_9.0.2_build)

**Comment by ryanmkurtz** [comment]
Our DevGuide lists Gradle 5.0 as the proper dependency:

> Gradle 5.0 - Later versions may work, but you'll need to modify our version check.

**Comment by mewmew** [comment]
Hi @ryanmkurtz. Thanks for the very quick response!

I can confirm that Gradle 5.2.1 works. It may thus be possible to relax the strict requirement on Gradle version 5.0.

```
$ gradle eclipse
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
> Task :eclipseProject
> Task :6502:eclipseProject
...
> Task :Z80:eclipseJdt
> Task :Z80:eclipse

BUILD SUCCESSFUL in 8m 29s
205 actionable tasks: 205 executed
```

Cheers,
Robin

**Comment by ryanmkurtz** [comment]
Thanks for letting us know it works.  If we get enough feedback about other versions working, we will consider switching it to a warning.
