### ISSUE TITLE
Ghidra dosen't work with directories that have spaces in them

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [NationalSecurityAgency/ghidra#3306]
There is an issue where ghidra won't launch when launching in a directory with a space in the directory name.

This is easy to reproduce.
1. download and extract ghidra
2. copy ghidra to c:\program files or any other directory with a space
3. run ghidra
and it won't launch!

**Comment by ryanmkurtz** [comment]
Duplicate of #3201
