### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by lpingree** [NationalSecurityAgency/ghidra#332]
I see no documentation. Is there a wiki or documentation page I can go to?

**Comment by LABurn** [comment]
You can find the documentation for the project within the tool under the `Help -> Contents` or `Help -> Ghidra API Help`  sections.

**Comment by adamopolous** [comment]
You can also hit F1 on any UI element to see the help for that item

**Comment by lpingree** [comment]
Thanks. Saw the website after I asked.

**Comment by srcdes** [comment]
There isn't web-based docs?
