### ISSUE TITLE
Ghidra crash when using Simple Chinese as input

### ISSUE THREAD

**Issue by zszhere** [NationalSecurityAgency/ghidra#3320]
**Describe the bug**
Ghidra crashed when using Simple Chinese as input,meanwhile using English as input ghidra works well.

**To Reproduce**
1. select Simple Chinese as input
2. run ghidra using ```./ghidraRun.sh```
3. click new project,select folder,then ghidra crashed

**Expected behavior**
works well when using Simple Chinese as input

**Screenshots**
![image](https://user-images.githubusercontent.com/12715675/128725323-9a936274-63f5-4d45-bacf-c913f5a9811e.png)

**Attachments**
```
Process:               java [62621]
Path:                  /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java
Identifier:            com.oracle.java.11.0.12.java
Version:               1.0 (11.0.12)
Code Type:             X86-64 (Native)
Parent Process:        ??? [62620]
User ID:               501

Date/Time:             2021-08-09 22:29:48.402 +0800
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Bridge OS Version:     5.4 (18P4663)
Anonymous UUID:        8602AC02-0EFE-4885-8437-05E6ACD072CF

Sleep/Wake UUID:       2CD6AA3D-46CE-488F-A0BE-DC6BBBCB4D2E

Time Awake Since Boot: 230000 seconds
Time Since Wake:       4600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x119b1a3b8'
abort() called
terminating with uncaught exception of type NSException
```

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Java Version: 11.0.12 (x86_64) "Oracle Corporation" - "Java SE 11.0.12" /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home
 - Ghidra Version: ghidra_10.0.1
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x119b1a3b8'
abort() called
terminating with uncaught exception of type NSException
```
As the crash log i pasted,this may help.
Thanks for your help.

**Comment by ryanmkurtz** [comment]
This looks like a bug in the JVM that has possibly been fixed in JDK 16:

https://bugs.openjdk.java.net/browse/JDK-8257242

**Comment by ryanmkurtz** [comment]
Duplicate of #3033

**Comment by zszhere** [comment]
issue solved,thanks for your help.
```16.0.2 (x86_64) "Oracle Corporation" - "Java SE 16.0.2" /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home```
this jdk version works well.
