### ISSUE TITLE
Exporter appends a dot for ELF filename

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#3325]
**Describe the bug**
If a file doesn't have a default extension, the exporter appends a single dot to its filename, which is not desirable.

**To Reproduce**
1. Import /bin/ls (or any ELF files on Linux)
2. Click File -> Export Program ...
3. Select "ELF" as Format, and enter "/tmp/ls_patched" as Output File
4. The exported file is at `/tmp/ls_patched.` (The trailing dot is part of the filename.)

**Expected behavior**
The exported file should be `/tmp/ls_patched`

**Screenshots**
![ls_patched](https://user-images.githubusercontent.com/16713498/129015938-15f9ee0c-2d5a-467c-b180-9ca7df53d616.png)
![filename](https://user-images.githubusercontent.com/16713498/129016880-923599b5-442e-4fcc-8588-4bf10bd2eed0.png)

**Environment (please complete the following information):**
 - OS: Kali Linux
 - Java Version: 11.0.11 OpenJDK
 - Ghidra Version: master f5615aa240891d40085b8e956d41e34ced23be32
 - Ghidra Origin: locally built

**Comment by ryanmkurtz** [comment]
Thanks, I see the problem and will get it fixed.

**Comment by astrelsky** [comment]
Partially related. Most of the functionality where a file is saved that is supposed to have an extension is flawed. I found that difficult to word so for example if something is supposed to create an xml file, after the user chooses where to save it and the file name, if the filename doesn't contain the extension it isn't automatically added.

**Comment by ryanmkurtz** [comment]
You mean it is automatically added?  I just tried it and it was was automatically added.

**Comment by ryanmkurtz** [comment]
I feel like the extensions should be visible in the `Output File` text box to make it clear what is being written.

**Comment by astrelsky** [comment]
> You mean it is automatically added? I just tried it and it was automatically added.

No, I mean most of the time it is **not** automatically added. Of course now I can't immediately reproduce it so I will stay quiet for now.

**Comment by astrelsky** [comment]
> I feel like the extensions should be visible in the `Output File` text box to make it clear what is being written.

`Debug Function Decompilation` is an example of one which does not append the extension automatically when it should.
Also Exporting a c++ header with the extension `.hpp` results in `.hpp.h`.
