### ISSUE TITLE
Z80: Decompiler doesn't work with ghidra 10.0.2

### ISSUE THREAD

**Issue by depili** [NationalSecurityAgency/ghidra#3329]
**Describe the bug**
When trying to work with Z80 programs in ghidra 10.0.2 official release the decompiler doesn't work anymore. The decompiler window just has the error:
```
Decompiler: Unable to initialize the DecompilerInterface: Could not register program:
  Low-level Error: Missing userop attribute in segmentop tag
```
This error is present in old 9.x projects and when importing a new file. The decompiler seems to work on other projects, like M68000. The same binaries used to work with ghidra 9.x previously.

**To Reproduce**
* Open a Z80 program in ghidra 10.0.2
* Navigate to a function
* Look to the decompiler window and see the error

**Expected behavior**
Expected to see decompiler output

**Screenshots**
<img width="1440" alt="Screenshot 2021-08-12 at 16 51 58" src="https://user-images.githubusercontent.com/3681069/129209009-99065b65-90c0-4cab-8214-d0ce8bc8a460.png">

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: macOS 10.15.7 catalina
 - Ghidra Version: 10.0.2
 - Ghidra Origin: official distro via homebrew installer

**Comment by depili** [comment]
Removing the segmentop element from https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/Z80/data/languages/z80.cspec#L12-L24 seems to fix the decompiler, so this is somehow related to the memory segmentation and banking, judging by the contents of the segmentop tag.

**Comment by Wall-AF** [comment]
I'm working on a Windows 3.1X app (circa 1997) that uses 16-/32-bit (`near`/`far`) pointers, and I noticed that the segmentation ordering has been changed.  Maybe you could check that out.  Sorry I can't help further as I'm still struggling with these issues.

**Comment by depili** [comment]
That would be 05f292a5e715f2400acdc1ca62fe8450ee78623c but reverting it has no effect on this issue, it was the first thing I tried.

At least in 9.x the Z180 banking wasn't in a usable state anyway, as the address space is limited to 16bits anyway so one needs to have overlays for all of the banks that are being used.

**Comment by caheckman** [comment]
Argh. I apologize if this impacted you.  The problem should not have gotten past testing.  A workaround is to move the <segmentop> tag from the z80.cspec into z80.pspec (or the.pspec that applies to your specific variant).  The attached patch does this if applied at the root of Ghidra directory (works both on a Ghidra 10.0.x distribution or on the development environment.

```patch -p1 < z80.txt```
[z80.txt](https://github.com/NationalSecurityAgency/ghidra/files/7173885/z80.txt)

**Comment by Wall-AF** [comment]
> 
> 
> Argh. I apologize if this impacted you. The problem should not have gotten past testing. A workaround is to move the tag from the z80.cspec into z80.pspec (or the.pspec that applies to your specific variant). The attached patch does this if applied at the root of Ghidra directory (works both on a Ghidra 10.0.x distribution or on the development environment.
> 
> `patch -p1 < z80.txt`
> [z80.txt](https://github.com/NationalSecurityAgency/ghidra/files/7173885/z80.txt)

@caheckman if you have a processor the supports segments for `stacks, code, data, etc.`, how do you specify this in the `.pspec` file?

**Comment by caheckman** [comment]
Moving the <segmentop> from the cspec to the pspec is a workaround for the bug on current distributions. But if for some reason this doesn't work for your custom processor variant, we are working on a full patch that won't require the pspec or cspec to be changed.

**Comment by Wall-AF** [comment]
> 
> 
> > Argh. I apologize if this impacted you. The problem should not have gotten past testing. A workaround is to move the tag from the z80.cspec into z80.pspec (or the.pspec that applies to your specific variant). The attached patch does this if applied at the root of Ghidra directory (works both on a Ghidra 10.0.x distribution or on the development environment.
> > `patch -p1 < z80.txt`
> > [z80.txt](https://github.com/NationalSecurityAgency/ghidra/files/7173885/z80.txt)
> 
> @caheckman if you have a processor the supports segments for `stacks, code, data, etc.`, how do you specify this in the `.pspec` file?

Oops, I don't think I made this clear, sorry!  What I missed was that currently there seems to be just on `<segmentop ...>` tag and that only accepts one `<constresolve>` that in turn accepts one `<register ...>` tag.
