### ISSUE TITLE
Analysis state quering in AbstractAnalyzer added()

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#334]
I'm trying to control current values of registers to implement some special functionality. How is it possible?

**Comment by lab313ru** [comment]
For example, analysis finds that there is some value moved into registry by MOVE instruction. How to get it at some specific instruction?

**Comment by emteere** [comment]
The only place that is considered currently is the start of a function if you desire setting a value.  You can set the register value at the beginning of a function, then the value will be used by constant analysis and the decompiler.

If you just want a value from an instruction that isn't computed, you can get the instruction and use getAddress(), getScalar(), getRegister().

Normally each analyzer is stateless.  There isn't a global store for computed values, and they are computed on the fly as needed based on the current state.  In general there is an attempt not to lock things in by storing them if it can be helped.

Is this what you are looking for?

You can also try using the MultiInstructionMemRef script.  It is not coded as an analyzer, but it does allow access to computed values.  The constant analyzers use this code to inspect registers and values.

**Comment by lab313ru** [comment]
MultiInstructionMemRef seems is what I want. I'll check it

emteere <notifications@github.com> 4 апреля 2019 г. 19:59:28 написал:

**Comment by lab313ru** [comment]
It works. Thank you
