### ISSUE TITLE
createJavadocs: build errors and warnings mostly related to HTML formatting

### ISSUE THREAD

**Issue by mewmew** [NationalSecurityAgency/ghidra#335]
**Describe the bug**

When building the Javadocs for Ghidra, a range of errors and warnings are reported. Errors such as `attribute not supported in HTML5: name`, `malformed HTML` (when using `<` characters).

**To Reproduce**
1. Navigate to the root directory of Ghidra
2. Run `gradle buildGhidra` as described in step *Building the Package* of the [DevGuide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md#building-the-package)
3. See error reported by `Task :createJavadocs`

```
> Task :createJavadocs
/home/u/Desktop/ghidra_play/ghidra/Ghidra/Features/Base/src/main/java/ghidra/app/services/MarkerService.java:39: error: attribute not supported in HTML5: name
 * <a name="usage"></a>
      ^
/home/u/Desktop/ghidra_play/ghidra/Ghidra/Framework/Project/src/main/java/ghidra/framework/plugintool/Plugin.java:38: warning: empty <p> tag
 * <p>
   ^
/home/u/Desktop/ghidra_play/ghidra/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/cli/blobs/CliBlob.java:31: error: malformed HTML
 * - If the first four bytes are 110bbbbb_2, x, y, and z: size is (bbbbb_2<<24 + x<<16 + y<<8 + z) bytes.
                                                                                   ^
/home/u/Desktop/ghidra_play/ghidra/Ghidra/Features/Base/src/main/java/ghidra/app/util/viewer/format/actions/EnableFieldAction.java:38: warning: no @param for panel
    public EnableFieldAction(String owner, FieldHeader panel) {
           ^
100 errors
100 warnings

```

**Expected behavior**

Successful build of documentation.

**Environment (please complete the following information):**
 - OS: Arch Linux

```
$ uname -a
Linux x1 5.0.5-arch1-1-ARCH #1 SMP PREEMPT Wed Mar 27 17:53:10 UTC 2019 x86_64 GNU/Linux
```

 - Java Version: jdk-openjdk 11.0.3.u4-1

 - Ghidra Version: `49c2010b63b56c8f20845f3970fedd95d003b1e9` (Ghidra_9.0.2_build)

**Comment by ryanmkurtz** [comment]
This is a pretty large effort that we've decided to tackle a little bit at a time.  Our general strategy is to try to fix up the javadoc in the files we are touching, and then ensure all new code is properly javadoc'd.  We've set up some rules in our Eclipse preferences file to produce warnings on any bad javadoc so every contributor should make sure those are enabled.

So, over time, the errors and warnings should go down, but it's not a priority at this time to get it to 0 in the short term.
