### ISSUE TITLE
Ghidra Official API documentation

### ISSUE THREAD

**Issue by dummys** [NationalSecurityAgency/ghidra#3353]
Hi,

I'm searching for the official Ghidra API documentation because I found the https://ghidra.re/ghidra_docs/api/ but this documentation is old and outdated. Thanks

**Comment by ryanmkurtz** [comment]
You'll find the official Ghidra API documentation for a given release in the release itself, at `docs/GhidraAPI_javadoc.zip`.

**Comment by dummys** [comment]
ok thanks. Can you add this to your documentation ? Because I think I'm not the only one to didn't find it.

**Comment by ryanmkurtz** [comment]
Sure, where would you have seen it?

**Comment by dummys** [comment]
in the devGuid it could be nice.
