### ISSUE TITLE
Problem installing freshly compiled java extension

### ISSUE THREAD

**Issue by dummys** [NationalSecurityAgency/ghidra#3354]
Hi, 

I'm trying to port an old loader extensions written for ghidra 9.1 on the latest version of ghidra
I builded it using gradle -p path_ghidra_install
It build successfully without any error, and when I want to install it using install extensions I get this:

```
ERROR | (ExtensionTableProvider$1) Installation Error: Extension version for [ghidra_10.0.1_DEV_20210820_GhidraVmlinuxLoader.zip] is incompatible with Ghidra
```
Is there a way to debug this ?
If you want to see the code: https://github.com/dummys/GhidraVmlinuxLoader

**Comment by ryanmkurtz** [comment]
What is the `version` property set to in the extension's `extension.properties` file?

**Comment by dummys** [comment]
Excellent, I modified the version and now I call load it. 
As it is a loader for binary file, how I can use it to load my binary. Do I need to select it somewhere to use it, or it is automatically applied ?

**Comment by ryanmkurtz** [comment]
When you start Ghidra, Ghidra will dynamically find the Loader in the installed extension, and when you import a new file, the loader should be selectable in the popup where you select the processor.

**Comment by ryanmkurtz** [comment]
Note that Ghidra will only show you the loaders that match on the file you are importing (which each loader is responsible for figuring out)

**Comment by dummys** [comment]
ok I see I was missing something. Now the loader is selectable but I have another problem arise. On the older version of the loader, the guy was using: `ghidra.app.plugin.assembler.sleigh.util.GhidraDBTransaction`
This class seems to be deprecated, so I removed it but now I get another error:

```
Transaction has not been started
db.NoTransactionException: Transaction has not been started
```

Is there a new API to replace this one ? You can see the old code here: https://github.com/dobo90/GhidraVmlinuxLoader/blob/03636854c5a39bea09bd7cfe3efd752fad80f2bb/GhidraVmlinuxLoader/src/main/java/ghidravmlinuxloader/GhidraVmlinuxLoader.java#L129

And my new code here: https://github.com/dummys/GhidraVmlinuxLoader/blob/6e32d0abb447f54e2a64cbd573e7112a002f2e5e/GhidraVmlinuxLoader/src/main/java/ghidravmlinuxloader/GhidraVmlinuxLoader.java#L137

**Comment by ryanmkurtz** [comment]
Can you please put in the full stack trace?

**Comment by dummys** [comment]
sure here it is:

```
Transaction has not been started
db.NoTransactionException: Transaction has not been started
	at db.DBHandle.checkTransaction(DBHandle.java:396)
	at db.Table.putRecord(Table.java:938)
	at ghidra.program.database.symbol.SymbolDatabaseAdapterV2.createSymbol(SymbolDatabaseAdapterV2.java:209)
	at ghidra.program.database.symbol.SymbolDatabaseAdapterV2.createSymbol(SymbolDatabaseAdapterV2.java:192)
	at ghidra.program.database.symbol.SymbolManager.doCreateSymbol(SymbolManager.java:2653)
	at ghidra.program.database.symbol.SymbolManager.createFunctionSymbol(SymbolManager.java:2586)
	at ghidra.program.database.function.FunctionManagerDB.createFunction(FunctionManagerDB.java:390)
	at ghidra.program.database.function.FunctionManagerDB.createFunction(FunctionManagerDB.java:317)
	at ghidravmlinuxloader.GhidraVmlinuxLoader.loadProgram(GhidraVmlinuxLoader.java:150)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

---------------------------------------------------
```

**Comment by ryanmkurtz** [comment]
You could try moving the problem code to inside here:

https://github.com/dummys/GhidraVmlinuxLoader/blob/6e32d0abb447f54e2a64cbd573e7112a002f2e5e/GhidraVmlinuxLoader/src/main/java/ghidravmlinuxloader/GhidraVmlinuxLoader.java#L124-L133

**Comment by dummys** [comment]
didn't understand. I think I should fine the newer version of: ghidra.app.plugin.assembler.sleigh.util.GhidraDBTransaction

**Comment by ryanmkurtz** [comment]
On a related note, this Loader is written a little oddly.  The Ghidra Loader class hierarchy is intended to abstract away needing to deal with transactions.  It could probably benefit from a refactor at some point.

**Comment by dummys** [comment]
> On a related note, this Loader is written a little oddly. The Ghidra Loader class hierarchy is intended to abstract away needing to deal with transactions. It could probably benefit from a refactor at some point.

Yes thats what I want to do, but I have no time to restart from the beginning from now. There is too much to modify.

**Comment by ryanmkurtz** [comment]
The issue is that you are trying to perform some actions that need to be done in a transaction.  Usage of that class was a hack...the class actually belonged to totally unrelated features of Ghidra.  My suggestion to move your code into the open transaction block i linked in still applies.

**Comment by dummys** [comment]
oh but you mean moving the code that is at: https://github.com/dummys/GhidraVmlinuxLoader/blob/6e32d0abb447f54e2a64cbd573e7112a002f2e5e/GhidraVmlinuxLoader/src/main/java/ghidravmlinuxloader/GhidraVmlinuxLoader.java#L137 inside the try ?

**Comment by ryanmkurtz** [comment]
yes, sorry i wasn't clear about that.

**Comment by mumbel** [comment]
Nothing to add to issue at hand, just was gonna share https://github.com/mumbel/ghidra_scripts/blob/master/kallsyms.py

I was mostly messing around to play with API when I wrote this, don't think its a very efficient script and fairly untested, but could be useful as a reference to your plugin

**Comment by dummys** [comment]
oh great. Will check this thanks guy :D

**Comment by dummys** [comment]
> Nothing to add to issue at hand, just was gonna share https://github.com/mumbel/ghidra_scripts/blob/master/kallsyms.py
> 
> I was mostly messing around to play with API when I wrote this, don't think its a very efficient script and fairly untested, but could be useful as a reference to your plugin

I just tried your script and even if I give him all the info it said, finished but has done nothing. But clearly there should be something wrong on this kernel. It's a huawei.
