### ISSUE TITLE
[feature] Enum w/ Python into a Ghidra project

### ISSUE THREAD

**Issue by Montana** [NationalSecurityAgency/ghidra#3359]
I want to implement `ghidra.app.util.cparser.C` to parse a string of a `struct` into a `struct` object and add it into Ghidra using `data_type_manager.addDataType()` with Enumerates but I'm not sure how. If there is a better method to add an Enum I will gladly use it, I guess to add on to the latter question is, can `BitFields` ever appear outside of a `struct` via `StructureDataType` has a public method `insertBitFieldAt` which might be the intended way to create one, or at least I'm thinking it is. 

Just like in IDA, if you know the constants for registry keys start with `HKEY_` (or you looked it up on MSDN, now known as, docs.microsoft.com) you could start typing that and it would narrow down the choices. 

I'm looking at a `WndProc` function, with a prototype of `LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)`. Inside the function are a number of switch statements based on the msg `UINT,` which Ghidra `calls param_2`.

I'm currently running Windows in a VM, I notice it has my symbolic constant, it shows the entire string. That's just about everything I think I need to know about that API call:

![strings-decompiler-window](https://user-images.githubusercontent.com/20936398/130305074-87ca41b3-16a2-416a-8a24-8692438e85c0.png)

So I ended up doing some scripting and came up with, 

```python
from ghidra.program.model.data import EnumDataType

enum = EnumDataType("EnumName", length)
enum.add("One", 1)
enum.add("Two", 2)
enum.add("Three", 3)
enum.add("Four", 4)
enum.add("Five", 5)

dataTypeManager.addDataType(enum, None)
```

When running the script, for example this is `param_3`: 

![image](https://user-images.githubusercontent.com/20936398/130305845-80b84bbf-9b89-4abf-8e33-909e3a88c285.png)

Thanks, 
Montana Mendy.

**Comment by Wall-AF** [comment]
You can also use the `Parse C Source...` option (from the `File` menu) to import a `C/C++` definition of your enum.

E.g. create a (header) file like below:
```
enum X {
  a,
  b,
  c
}
```
And import it.

**Comment by Montana** [comment]
Will try creating the header this way and see if I get different results, thank you @Wall-AF, will report back .
