### ISSUE TITLE
Could not find decompiler executable decompile.exe

### ISSUE THREAD

**Issue by wj5449** [NationalSecurityAgency/ghidra#3375]
**Describe the bug**
 suddenly i can not start decompiler,
i replaced file with download zip ,it didn't work

**Screenshots**
![无标题](https://user-images.githubusercontent.com/87698389/130743355-3e0549a6-0687-4778-beeb-e2ce9f4ff6b7.png)

**Environment (please complete the following information):**
 - OS: [e.g. Win 10-- 10.0.19042]
 - Java Version: [Eclipse Foundation\jdk-11.0.12.7-hotspot\]
 - Ghidra Version: [e.g. 10.0.2]
 - Ghidra Origin: [https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.0.2_build]

**Comment by wj5449** [comment]
360tray.exe remove decompile.exe without any message

**Comment by wj5449** [comment]
类型:木马-HEUR/QVM202.0.7FB0.Malware.Gen
描述:木马是一种伪装成正常文件的恶意软件，会盗取您的帐号、密码等隐私资料。
扫描引擎:云特征引擎
文件路径:
文件大小:3.03M (3,173,376 字节)
文件指纹（MD5）:3d160f4cb1143665cfb7bbcc4439bd73
处理建议:隔离文件

**Comment by ryanmkurtz** [comment]
The hash looks genuine.  I guess it's just a false positive from 360.  If you google `Trojan-HEUR/QVM202.0.7FB0.Malware.Gen`, you'll see a lot of other people reporting the same false positive on their binary.

**Comment by astrelsky** [comment]
> The hash looks genuine.  I guess it's just a false positive from 360.  If you google `Trojan-HEUR/QVM202.0.7FB0.Malware.Gen`, you'll see a lot of other people reporting the same false positive on their binary.

Ah heuristics.
