### ISSUE TITLE
Radio button in Loader option window

### ISSUE THREAD

**Issue by IridiumXOR** [NationalSecurityAgency/ghidra#3384]
Hi,
is it possible to insert a custom option set which uses radio button in a Ghidra loader options window?
If yes how?
I have checked various sources and I have found only text or check fields inserted as custom options in loader options window.

**Comment by ryanmkurtz** [comment]
I think it should be possible by overriding the `ghidra.app.util.Option.getCustomEditorComponent()` method for your particular option, but i've never tried it.  There isn't anything in the `OptionsEditorPanel` that will do it automatically for you.

**Comment by dragonmacher** [comment]
We have not yet had a need for radio buttons in our options UI.  We have always used a drop-down widget for this case.   You can create your own custom options editors, with as much complexity as you desire.  See the `Options` interface for docs and to see example usage: https://github.com/NationalSecurityAgency/ghidra/blob/c51183f1a262c80d45aac48d4f3343c67b6bd41a/Ghidra/Framework/Generic/src/main/java/ghidra/framework/options/Options.java#L136-L150
