### ISSUE TITLE
Change Input method crash the Ghidra on mac

### ISSUE THREAD

**Issue by terrynini** [NationalSecurityAgency/ghidra#3385]
**Describe the bug**
The whole program crash and exit when the input method is not ABC.

**To Reproduce**
There are two way to trigger this
1. open Ghidra
2. Change input method to Japanese input method, e.g. Hiragana (Chinese input method also work)
3. program crash

or
1. Change input method to Japanese input method, e.g. Hiragana (Chinese input method also work)
2. open Ghidra
3. program crash

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: macOS 11.5.2
 - Java Version: 1.8.0_301
 - Ghidra Version: 10.0.2
 - Ghidra Origin: Github release

**Additional context**

**Comment by ryanmkurtz** [comment]
Duplicate of #3033 and #3320.  This is a known issue within Java.  You might want to give JDK 16 a try.
