### ISSUE TITLE
6502: wrong use of carry flag in SBC

### ISSUE THREAD

**Issue by Spongman** [NationalSecurityAgency/ghidra#3394]
https://github.com/NationalSecurityAgency/ghidra/blob/c51183f1a262c80d45aac48d4f3343c67b6bd41a/Ghidra/Processors/6502/data/languages/6502.slaspec#L421-L432

i believe this should be `local result = A - op1 - 1 + C;`

http://www.obelisk.me.uk/6502/reference.html#SBC :

> This instruction subtracts the contents of a memory location to the accumulator together with the **not** of the carry bit.

**Comment by mumbel** [comment]
Known issue  https://github.com/NationalSecurityAgency/ghidra/pull/3190

**Comment by ryanmkurtz** [comment]
Duplicate of #3189
