### ISSUE TITLE
Incorrect interpretation of 4 byte attributes to assembly commands

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3403]
**Describe the bug**
When disassembling 16-bit Windows application, some command use 32-bit immediate values in the assembly, overriding the 16-bit version with the prefix `0x66` and using extended registers (like `EAX`).  I have found that values are being incorrectly interpretated in that process.  See the example below:
```
      1028:09dc 66 3d 00        CMP        EAX,0x400
                04 00 00
                                                      CF = INT_LESS EAX, 0x400:4
                                                      OF = INT_SBORROW EAX, 0x400:4
                                                      $U1db80:4 = INT_SUB EAX, 0x400:4
                                                      SF = INT_SLESS $U1db80:4, 0:4
                                                      ZF = INT_EQUAL $U1db80:4, 0:4
                                                      $Ud900:4 = INT_AND $U1db80:4, 0xff:4
                                                      $Ud980:1 = POPCOUNT $Ud900:4
                                                      $Uda00:1 = INT_AND $Ud980:1, 1:1
                                                      PF = INT_EQUAL $Uda00:1, 0:1
```
this should be:
```
      1028:09dc 66 3d 00        CMP        EAX,0x40000
                04 00 00
```
(I'm not sure what the command breakdown would be!)

**To Reproduce**
1. Import the included xml from the `Debug Function Decompilation` option
[FUN_1028_094f.zip](https://github.com/NationalSecurityAgency/ghidra/files/7121905/FUN_1028_094f.zip)
2. Look at the instruction at `1028:09dc`

**Expected behavior**
The correct interpretation of the value.

**Screenshots**
![image](https://user-images.githubusercontent.com/67698927/132355792-0203536c-bebe-44e5-80c1-d803310bef2e.png)
This also highlights the failure in the `AND` command at `1028:09d6` as well.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.2
 - Ghidra Version: 10
 - Ghidra Origin: locally built

**Additional context**
I know that these values correspond to the window styles listed below:
```
#define WS_THICKFRAME       0x00040000L
#define WS_MINIMIZEBOX      0x00020000L
#define WS_MAXIMIZEBOX      0x00010000L
```
but what I am unsure about is how this has occurred, how to fix it, and whether it affects anything else!

**Comment by quietust** [comment]
The instruction `CMP EAX,0x40000` would be represented by the byte sequence "66 3d 00 **00 04** 00", not "66 3d 00 **04 00** 00".

**Comment by Wall-AF** [comment]
> The byte sequence `66 3d 00 04 00 00` _does_ represent the instruction `CMP EAX, 0x00000400`, not `CMP EAX, 0x00040000` - if it was supposed to be the latter, it would have to be "66 3d 00 **00 04** 00", not "66 3d 00 **04 00** 00".

Yes, that's what I was thinking.  But some work has happened recently (forgotten exactly where) that fixed some other byte ordering issue and I wondered if this could be a knock-on effect?  Due to context, I **know** it should be representing `0x40000` and not `0x400`.

**Comment by quietust** [comment]
Can you check the exact byte sequence that occurs within the binary?

If the binary itself contains `66 3D 00 00 04 00`, it's possible that there might be some sort of bug in the x86-16 importer that's performing endian conversion for some inexplicable reason; if it contains `66 3D 00 04 00 00`, however, it might actually be a **bug** in the original program.

**Comment by Wall-AF** [comment]
> 
> 
> Can you check the exact byte sequence that occurs within the binary?
> 
> If the binary itself contains `66 3D 00 00 04 00`, it's possible that there might be some sort of bug in the x86-16 importer that's performing endian conversion for some inexplicable reason; if it contains `66 3D 00 04 00 00`, however, it might actually be a **bug** in the original program.

This is a Windows NE file from a Borland compiler (I think v. 4.02 C/C++), and that sequence occurs several times.

**Comment by Wall-AF** [comment]
I'm wondering if (back then) when the prefix was used to override the normal 16-bit to a 32-bit, the word orderring was swapped???

**Comment by Wall-AF** [comment]
I've slept and Goooooooogled this and I think its a limitation (lack of) of Microsoft's documentation in regard to what can be returned from `GetWindowsLong(hwnd, GWL_STYLE)`.  Maybe its returning things like:
```
BS_LEFT
BS_RIGHT
BS_TOP
```

Has anyone expertise here???

**Comment by quietust** [comment]
Windows appears to only use the upper 16 bits of GWL_STYLE for its own purposes - perhaps this application was using the lower 16 bits for custom storage (which _seems_ to be a thing)?

**Comment by Wall-AF** [comment]
I'm also receiving error `Pcode: XML comms: Bad storage node` when trying to change the datatype of the variable returned from a `GetWindowLong(...)` call in other functions, even where an earlier variable was successfully updated!

**Comment by Wall-AF** [comment]
Seems like this may not / probably isn't a bug, but a lack of complete documentation from Microsoft in regard to what can be returned from the API `GetWindowLong(hwnd, GWL_STYLE)`!  Therefore I sincerely apologise to anyone looking into this in the interim.

As an asside, if anyone really knows ALL the values that can be returned by this (and any other incompletely documented Windows API), please let me know.  Thanks.

**Comment by sollyucko** [comment]
https://devblogs.microsoft.com/oldnewthing/20031203-00/?p=41633
