### ISSUE TITLE
~/.gdbinit contents can prevent debugger working, without a clear error message

### ISSUE THREAD

**Issue by pj58943** [NationalSecurityAgency/ghidra#3407]
**Describe the bug**
I had difficulties getting the Ghidra debugger to work on a different VM than usual.  It kept just failing to connect to gdb, either IN-VM or via GADP, even though gdb worked just fine outside Ghidra.  The error message I got for IN-VM debuggers was "Could not connect: ghidra.dbg.error.DebuggerModelTerminatingException", which appears to mean "the gdb process didn't start".

The problem turned out to be the local .gdbinit, which at this point contained the text

    set disassembly-flavor intel
    layout asm
    layout regs
    fs cmd

The last line appears to be the one that breaks things (although the previous two turn on the TUI mode which looks very strange in Ghidra's interpreter window!) – removing that line from the file solved the problem and I can use the debugger.

**To Reproduce**
1. Create a .gdbinit file with commands similar to the above.
2. Open a program in the debugger tool
3. Select "Debugger" -> "Debug activate" and pick local GDB (either IN-VM or GADP).
4. Try to connect.

**Expected behavior**
There are several behaviors that would be reasonable:
1. Ghidra launches gdb in a way that does not read .gdbinit files (e.g. using `--nx`)
2. The launch dialog includes a checkbox to skip .gdbinit files.
3. The launch dialog includes a means of specifying custom command-line flags.
4. If gdb fails to start, Ghidra checks some common causes and displays a friendlier message; e.g. it could I think easily distinguish between "the path given for gdb is wrong" and "gdb --version works but actually launching gdb fails, probably a configuration problem", and if ~/.gdbinit exists then it could suggest the user tries again without it.

**Environment (please complete the following information):**
 - OS: Fedora 34, x86_64
 - Java Version: 11.0.12
 - Ghidra Version: 10.1-DEV
 - Ghidra Origin: Local build of 'master' branch

**Comment by nsadeveloper789** [comment]
Interesting. There are two issues at play here. First, I wouldn't expect anything that requires a proper VT100 terminal to look nice in our interpreter window. At some point, I might try to switch that to something like jediterm, but that's way ahead if at all. Second, which I understand less, is that perhaps the final `fs cmd` is somehow preventing GDB from receiving/processing the first command we send it, which is the `new-ui mi2 ...` command.

That said, you might try the following workaround:
1. Start gdb outside of Ghidra and configure it to your liking.
1. In Ghidra, use the "Connect" button to manually start the GDB connector.
1. It should have an option to "Use existing session via new-ui". Check that.
2. Hit connect. At some point, it should tell you the name of the PTY it allocated.
3. Follow its instructions and type `new-ui mi2 /dev/pts/#` into your already-running gdb session.
4. You might need to dismiss the dialog giving you those instructions.
5. If all goes well, both Ghidra and your terminal's interpreter should now command the same gdb session.

**Comment by ryanmkurtz** [comment]
@pj58943 Did you ever get this working?

**Comment by d-millar** [comment]
bad .gdbinit commands reported as "bad commands" in the terminal
