### ISSUE TITLE
HeadlessAnalyzer: `'*'` prematurely expanded for `-process` on linux/macOS

### ISSUE THREAD

**Issue by podstanar0** [NationalSecurityAgency/ghidra#3409]
1. Using GUI, created new project called **default** in **~/GHIDRA/projects**, made new folder called **testapp** inside it, and imported binary to it.
2. Closed Ghidra GUI.
3. cd-ed to **~/GHIDRA/ghidra_10/support** and ran: _./analyzeHeadless ../../projects default/testapp -process "/*" -recursive_
3.1 Also tried without "/" in "/\*", so just "\*", still the same error.

What am i doing wrong here?

**Comment by ryanmkurtz** [comment]
Does it work if you use an absolute path to your project?

**Comment by podstanar0** [comment]
> Does it work if you use an absolute path to your project?

Forgot to mention that, no, it's the same :(

**Comment by ryanmkurtz** [comment]
Can you copy in the output your are getting from `analyzeHeadless`?

**Comment by ryanmkurtz** [comment]
Also, does it work if you put single quotes around your wildcard rather than double quotes?

**Comment by podstanar0** [comment]
Nope, single/double, it's all the same error.

**Comment by podstanar0** [comment]
> Can you copy in the output your are getting from `analyzeHeadless`?

Sure:

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
INFO  Using log config file: jar:file:/Users/jovana/Desktop/GHIDRA/ghidra_10.0.3_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)
INFO  Using log file: /Users/jovana/.ghidra/.ghidra_10.0.3_PUBLIC/application.log (LoggingInitialization)
INFO  Loading user preferences: /Users/jovana/.ghidra/.ghidra_10.0.3_PUBLIC/preferences (Preferences)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/jovana/Desktop/GHIDRA/ghidra_10.0.3_PUBLIC/Ghidra/Features/Base/lib/slf4j-nop-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/jovana/Desktop/GHIDRA/ghidra_10.0.3_PUBLIC/Ghidra/Features/GraphServices/lib/slf4j-nop-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
INFO  Class search complete (2972 ms) (ClassSearcher)
INFO  Initializing SSL Context (SSLContextInitializer)
INFO  Initializing Random Number Generator... (SecureRandomFactory)
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)
Exception in thread "main" java.lang.IllegalArgumentException: invalid filename specified
	at ghidra.app.util.headless.HeadlessOptions.setRunScriptsNoImport(HeadlessOptions.java:168)
	at ghidra.app.util.headless.AnalyzeHeadless.parseOptions(AnalyzeHeadless.java:292)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:113)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:82)
```

**Comment by ryanmkurtz** [comment]
Hmmm, i replicated everything you did exactly and it works.  I'm on windows though.  Are you on macOS?

**Comment by podstanar0** [comment]
yep, on my Win it also works, strange

**Comment by ryanmkurtz** [comment]
Does it work if you hardcode in the path to a file instead of using wildcards?

**Comment by ryanmkurtz** [comment]
I'm able to reproduce it now on Ubuntu

**Comment by podstanar0** [comment]
Like this?
_./analyzeHeadless ../../projects default/testapp -process ../../projects/default/testapp/myapp -recursive

**Comment by ryanmkurtz** [comment]
No, it would be like `./analyzeHeadless ../../projects default/testapp -process myapp -recursive`

**Comment by podstanar0** [comment]
> I'm able to reproduce it now on Ubuntu

Nice, we are getting close

**Comment by podstanar0** [comment]
> No, it would be like `./analyzeHeadless ../../projects default/testapp -process myapp -recursive`

This works!

**Comment by ryanmkurtz** [comment]
Yes.  I'll track it down.

**Comment by ryanmkurtz** [comment]
A few observations:
* The issue happens on macOS/Linux when the wildcard you used successfully expands to something in your current directory, which `*` will easily do.  The quotes around the wildcard argument are lost when Ghidra is actually called, so Ghidra receives what the wildcard expanded to, not the wildcard character.
* If the wildcard doesn't successfully expand to anything, then it's passed along to Ghidra as expected.  For example, i had `bash` in my project, and I did `bas*` on the command line, and it worked (nothing in my filesystem directory started with `bas`)
* Ghidra definitely doesn't like `/*`.  It will throw an `IllegalArgumentException` if it encounters a `/` in the "filename" argument.
* In your original case, if you want `'*'`, you actually don't need anything, except the -process and -recursive arguments.

Having said all of this, I think it's a bug that we aren't handlingi `'*'` correctly, so I am going to rename this issue to reflect that and keep it open until it's fixed.
