### ISSUE TITLE
Working at 4k resolution isn't possible

### ISSUE THREAD

**Issue by ValonK** [NationalSecurityAgency/ghidra#341]
**Describe the bug**
after loading the binary and maximizing the window, Ghidra (UI) completely shits the bed and it becomes unusable, which sucks.

**To Reproduce**
run in 4k

**Expected behavior**

**Screenshots**
https://imgur.com/a/kNz2QFc
https://imgur.com/a/Tceevpo

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10 1809 (Build 17763.379)
 - Java Version: 11.0.2   1.8.0_171-b11
 - Ghidra Version: 9.0.2

**Additional context**

**Comment by arminfelder** [comment]
I guess this is related to #1

**Comment by williballenthin** [comment]
works for me

![image](https://user-images.githubusercontent.com/156560/55643252-ef67ae00-578f-11e9-926b-199b84d8c053.png)

![image](https://user-images.githubusercontent.com/156560/55643278-01495100-5790-11e9-8234-fe4076167e9e.png)

**Comment by ryanmkurtz** [comment]
Thanks @williballenthin.  What JDK are you using?  OpenJDK, Oracle JDK, Amazon JDK?

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/55645326-83884400-5795-11e9-856f-4db30fccf81c.png)

**Comment by ryanmkurtz** [comment]
Thanks @williballenthin.  @ValonK, you could try the Oracle JDK to see if that fixes it for you.  Note that it's up to you to ensure that you meet the licensing requirements for use of the JDK...it can vary from vendor to vendor.

**Comment by seritools** [comment]
Hi, I've encountered the same problem, weirdly with other Java applications as well. Most of the time it seems to be some breakage with java 1.8+ rendering and multimonitor setups.

Examples of other software having the same behavior:
https://github.com/chatty/chatty/issues/27
https://github.com/fesch/Structorizer.Desktop/issues/536

In Ghidra, the rendering works just fine for me, until I do the very specific thing of hovering over a button, creating a tooltip *that crosses the outside of the window frame*, like this:

![image](https://user-images.githubusercontent.com/5844066/57972076-1ff95500-7996-11e9-996a-52bd2f638dc3.png)

Immediately after any tooltip crosses the window, every repaint garbles the screen.

Searching for a solution after giving up last time I've found that this seems to work for me: https://github.com/fesch/Structorizer.Desktop/issues/536#issuecomment-397363031

I've added the following lines to `support\launch.properties`:

```properties
VMARGS=-Dsun.java2d.noddraw=true
VMARGS=-Dsun.java2d.d3d=false
```

It seems to run fine now after setting these VM args.

**Comment by arminfelder** [comment]
I had the same issue with Ubuntu 19.04, setting 
```java
VMARGS=-Dsun.java2d.xrender=true
```
 did the trick for me

**Comment by ValonK** [comment]
@seritools thanks fixes the problem for me

**Comment by ryanmkurtz** [comment]
is setting nodraw to true necessary if d3d is set to false?  The documentation for nodraw seems to indicate it may not be necessary.

**Comment by seritools** [comment]
Just checked - `VMARGS=-Dsun.java2d.d3d=false` seems to be enough 👍

**Comment by ryanmkurtz** [comment]
Thanks...I'm just trying to narrow down what our default settings should be moving forward, and I can't actually test any of this myself.
