### ISSUE TITLE
`buildGhidraJar`  and Python support

### ISSUE THREAD

**Issue by mrphrazer** [NationalSecurityAgency/ghidra#3427]
Hi,

`buildGhidraJarREADME.txt` states `Use of other non-Java scripting languages such as Python is not supported when running 
from a single Ghidra jar configuration.`

I wonder why this is the case and what would be required to add python scripting support (on my own)?

**Comment by ryanmkurtz** [comment]
I'm guessing that Jython doesn't know how to find its own files when they exist only within the jar.  I'll have to play with it a bit more to give you an exact answer though.

**Comment by mrphrazer** [comment]
That would make sense. Thanks, I'll play around with that and close the issue for now.
