### ISSUE TITLE
PowerPC emulator forgets vle flag at every branch

### ISSUE THREAD

**Issue by epozzobon** [NationalSecurityAgency/ghidra#3428]
**Describe the bug**
When emulating a piece of PowerPC VLE-encoded code using an EmulationHelper object in a script, it seems that after every branch, the emulator "forgets" the value of the VLE context register, causing it to crash with `Instruction decode failed (Unable to resolve constructor at ...), PC=...`

**To Reproduce**

1. Load the following hex file in ghidra, choosing `PowerPC:BE:64:VLEALT-32addr` as language
```
:020000040800F2
:10000000C0432A04E20670B9E2FF1CA5BABEE805A7
:1000100070BBE6AE1CA5BEEFD05344004400E80020
:00000001FF
```
2. Attempt emulating the example by executing [ppc_vle_emulation_example.py](https://github.com/NationalSecurityAgency/ghidra/files/7187001/ppc_vle_emulation_example.py.txt)
3. Verify that `stepTest` correctly outputs `src=0x20000000 -> 0xcafebabe` (because it writes 1 into the vle register before each emulator step), but `runTest` fails.

Both functions `runTest` and `stepTest` in the script should produce the same result, but `runTest` fails with `Instruction decode failed (Unable to resolve constructor at 0800001c), PC=0800001c`, because the branch to 0x8000018 caused it to lose the previous value of the VLE flag.
Furthermore, commenting the line `emu.setContextRegister(vle_enabled)` causes `stepTest` to fail `emu.readRegister("vle")`.

**Expected behavior**
The PPC emulator should preserve the state of the VLE context register unless an instruction explicitly changes it.

**Screenshots**
<img width="1663" alt="Capture" src="https://user-images.githubusercontent.com/5781229/133822526-f0029c15-7a5e-4f55-89a9-2378b2cc5db0.PNG">

**Attachments**
- [ppc_vle_emulation_example.py](https://github.com/NationalSecurityAgency/ghidra/files/7187001/ppc_vle_emulation_example.py.txt)
- [ppc-vle-sample.hex](https://github.com/NationalSecurityAgency/ghidra/files/7187056/ppc-vle-sample.hex.txt)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 14.0.1
 - Ghidra Version: 10.0.3
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**
The thumb flag in the arm emulator requires some [special handling](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/ARM/src/main/java/ghidra/program/emulation/ARMEmulateInstructionStateModifier.java#L152) after every branch instruction. Maybe the same is necessary for PowerPC VLE?

**Comment by ghidra1** [comment]
VLE mode requires context to be "painted" over the relevant memory regions.  The ELF loader attempts to do this automatically based upon section or program header flags (`SHF_PPC_VLE, PF_PPC_VLE`).  If needed, you can programmatically set context over a specific address range/set or all of loaded memory **prior to disassembly** as done in the sample code below.  An error will occur if an attempt is made to change the stored context where instructions already exist.
```
Register vleReg = program.getRegister("vle");
RegisterValue value = new RegisterValue(vleReg, BigInteger.ONE);
AddressSetView loadedMemory = program.getMemory().getLoadedAndInitializedAddressSet();
program.getProgramContext().setRegisterValue(loadedMemory.getMinAddress(), loadedMemory.getMaxAddress(), value);
```

**Comment by ghidra1** [comment]
Working as expected.  Need to paint context since you are performing a non-ELF import.
