### ISSUE TITLE
API: Structure.growStructure() does not actually grow the structure

### ISSUE THREAD

**Issue by Fexty12573** [NationalSecurityAgency/ghidra#3432]
**Description**
Calling growStructure(size) on a Structure does not actually increase its size. I don't know if I am doing something wrong but I can't seem to get this function to work.

**To Reproduce**
1. Use the ghidrapython api to get any structure from the DataTypeManager
2. Call growStructure() on it
3. Check size/length of structure again

**Expected behavior**
After growing the size of an 8 byte structure by 600 bytes it should be 608 bytes long afterwards.

**Additional Info**
Here is the code:
```
for struct in dtm.getAllStructures():
        name : str = struct.getName()
        if name.find("_FROM_SCRIPT") != -1:
            size = SIZE_MAP[name]

            struct.growStructure(size)
            print(F"Grew structure {name} by {size} bytes. Is now {struct.getLength()} bytes long")
```
![image](https://user-images.githubusercontent.com/60443001/133890747-823a609a-a4b4-4aad-b161-1dced4632eea.png)

**Environment:**
 - OS: Windows 10, build 19042.1165
 - Java Version: 14.0.1
 - Ghidra Version: 10.0
 - Ghidra Origin: Releases tab of this repo

**Comment by mumbel** [comment]
Are they packed (you cannot call this method on packed)?

**Comment by Fexty12573** [comment]
Oh you're right they are. Is there a way I can generate unpacked structures using the API?

**Comment by Fexty12573** [comment]
Or maybe a way to unpack a packed structure using the API?
