### ISSUE TITLE
Creating an unpacked structure using the GhidraPython API

### ISSUE THREAD

**Issue by Fexty12573** [NationalSecurityAgency/ghidra#3436]
Hello. I would like to know if there is a way to create an **unpacked** structure using the GhidraPython API.

I have tried using `#pragma pack(push, 0)` for the C parser but that did not work. I have also tried calling `Structure.pack(0)` on the structure after creating it. And trying to pass `Structure.NOT_PACKING` gives me
`AttributeError: 'ghidra.program.database.data.StructureDB' object has no attribute 'NOT_PACKING'`

I have not found any way to create an unpacked structure or unpack it after creating it using the API. Any help would be greatly appreciated.

**Comment by Fexty12573** [comment]
Is this even possible in the first place?

**Comment by ghidra1** [comment]
All structures produced with the C parser are packed in a fashion consistent with a compiler.    The `#pragma pack` directive is supported but that simply alters the packing parameters (e.g., `#pragma pack(1)`).  Creating a StructureDataType via the API is by default non-packed (i.e., packing disabled).  In this state all bytes are accounted for by component where undefined components exist for unoccupied offsets.  Within a packed structure components only exist for defined components which are placed automatically based upon the pack value and component alignment requirements.  A packed structure does not utilize undefined components for padding locations.

**Comment by Fexty12573** [comment]
Ahhh ok that makes a lot more sense now. Thank you very much for the help! Closing this now.
