### ISSUE TITLE
Code stripped out.

### ISSUE THREAD

**Issue by nihilus** [NationalSecurityAgency/ghidra#344]
**Describe the bug**
 I was surprised to look at DecompilerInitializer.java and see a comment about it being reviewed and it has obviously been tampered with.

**Comment by emteere** [comment]
Files get reviewed as part of the software development process, this is an old tag as part of a code review process we no longer do.  Many files have this tag which could be cleaned out.

Can you be more specific as to the change you are seeing or tampering indication?  This particular file has not been changed for quite a while, even internally before the public release.

**Comment by nihilus** [comment]
A magician never reveals his secrets. :-)

**Comment by nihilus** [comment]
So now we know that code for certain was stripped out / modified before the public release. That's valuable information as well.

**Comment by Deledrius** [comment]
> So now we know that code for certain was stripped out / modified before the public release. That's valuable information as well.

That's precisely the opposite of what was said, and you have presented no evidence to support your vague claim.  What are you really suggesting?

**Comment by nihilus** [comment]
@Deledrius It is exactly what is implicated. You are just doing a non sequitur.

**Comment by Ristovski** [comment]
I don't see how the following comment implies the code has been tampered with, nor how it being "Reviewed" is bad.

Comment in question for context/the lazy:
```
/* ###
 * IP: GHIDRA
 * REVIEWED: YES
 *
 [SNIP]
```
