### ISSUE TITLE
Overlapping register allocations in user-defined cspec call convention

### ISSUE THREAD

**Issue by 00xc** [NationalSecurityAgency/ghidra#3440]
I'm currently trying to add a new x86-64 call convention to Ghidra. I have taken `Ghidra/Processors/x86/data/languages/x86-64-gcc.cspec` and added a new `<prototype>` section. I want my new call convention to work exactly as `__stdcall` except it can take multi-register parameters (e.g. a 16 byte struct as a first parameter would be passed through RDI and RSI). I added the following pentries inside the `<input>` subsection for the prototype:

```xml
<prototype name="__mycall" extrapop="8" stackshift="8">

	<input>

		<!-- regular registers ... -->

		<!-- My added pentries -->
		<pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RDI" piece2="RSI"/>
		</pentry>
		
		<pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RSI" piece2="RDX"/>
		</pentry>
		
		<pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RDX" piece2="RCX"/>
		</pentry>

		<pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RCX" piece2="R8"/>
		</pentry>

		<!-- Stack as a last resource -->
		<pentry minsize="1" maxsize="500" align="8">
			<addr offset="8" space="stack"/>
		</pentry>

	</input>

	<!-- (...) -->

</prototype>
```

Take for example this function. With the standard call convention I get:

![1](https://user-images.githubusercontent.com/48725664/134087508-9a552826-97fd-4bd9-88ee-8eff1918c23f.PNG)

This is what I would want as a result of applying my new call convention:

![2](https://user-images.githubusercontent.com/48725664/134087517-99219518-187e-4400-bfe8-b0cf834c5f3a.PNG)

However this is what I get:

![3](https://user-images.githubusercontent.com/48725664/134087525-1d1e2c3c-7937-480d-be9d-d430e8e581b0.PNG)

According to the docs this should not happen:

> Standard Strategy
>
> For this strategy, the <pentry> subtags under the \<input\> tag are viewed as an ordered resource list. When assigning storage locations from a list of datatypes, each datatype is evaluated in order. The first <pentry> from the resource list that fits the datatype and hasn't been fully used by previous datatypes is assigned to that datatype.

The standard strategy is the default. In my example RDI is assigned fully (along with RSI) to the first parameter, and then it is assigned again to the second parameter.

Is there a way to avoid RDI being assigned twice while retaining the logic I explain above? I have not marked the issue as a bug since I am not sure this is the expected behavior or not. Thanks in advance.

**Comment by ghidra1** [comment]
The `pentry` items need to be in ordinal order.  When I interleaved as shown below they appeared to work as you were intending.  There are unrelated issues with the free-form signature string parser, but the individual parameter datatype selection appeared to work.
```
    <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM0_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM1_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM2_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM3_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM4_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM5_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM6_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM7_Qa"/>
        </pentry>
        <pentry minsize="1" maxsize="8">
          <register name="RDI"/>
        </pentry>
        <pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RDI" piece2="RSI"/>
		</pentry>
        <pentry minsize="1" maxsize="8">
          <register name="RSI"/>
        </pentry>
        <pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RSI" piece2="RDX"/>
		</pentry>
        <pentry minsize="1" maxsize="8">
          <register name="RDX"/>
        </pentry>
        <pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RDX" piece2="RCX"/>
		</pentry>
        <pentry minsize="1" maxsize="8">
          <register name="RCX"/>
        </pentry>
        <pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RCX" piece2="R8"/>
		</pentry>
        <pentry minsize="1" maxsize="8">
          <register name="R8"/>
        </pentry>
        <pentry minsize="1" maxsize="8">
          <register name="R9"/>
        </pentry>
```

**Comment by 00xc** [comment]
I interleaved the `pentry` items as shown above and I get the same issue where RDI gets assigned twice. I am working with version 10.0.3, and also tried with 10.0.1, with the same results.

I am attaching the original binary in case it is of any use for replication; there's a call to a function that has this issue at address 0x10b134 (it is not the original example I was using, as I was manually adding an additional parameter to it for other reasons).

[example.zip](https://github.com/NationalSecurityAgency/ghidra/files/7224662/example.zip)

**Comment by ghidra1** [comment]
I am seeing this as well. Now I am unsure what I was seeing when trying this last night.  I am going to defer to @caheckman

**Comment by caheckman** [comment]
Overlapping \<pentry\> tags like this aren't supported within the \<input\> tag.  But we are currently working on adding this feature.

**Comment by ghidra1** [comment]
A fix is in the works for 10.1.  Here is what your input spec ordering should look like once the fix is in place.
```
    <input>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM0_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM1_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM2_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM3_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM4_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM5_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM6_Qa"/>
        </pentry>
        <pentry minsize="4" maxsize="8" metatype="float">
          <register name="XMM7_Qa"/>
        </pentry>
        <pentry minsize="1" maxsize="8">
          <register name="RDI"/>
        </pentry>
        <pentry minsize="1" maxsize="8">
          <register name="RSI"/>
        </pentry>
        <pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RDI" piece2="RSI"/>
		</pentry>
        <pentry minsize="1" maxsize="8">
          <register name="RDX"/>
        </pentry>
        <pentry minsize="1" maxsize="8">
          <register name="RCX"/>
        </pentry>
        <pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RSI" piece2="RDX"/>
		</pentry>
        <pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RDX" piece2="RCX"/>
		</pentry>
		<pentry minsize="1" maxsize="8">
          <register name="R8"/>
        </pentry>
        <pentry minsize="9" maxsize="16">
			<addr space="join" piece1="RCX" piece2="R8"/>
		</pentry>
        <pentry minsize="1" maxsize="8">
          <register name="R9"/>
        </pentry>
        <pentry minsize="1" maxsize="500" align="8">
          <addr offset="8" space="stack"/>
        </pentry>
      </input>
```

**Comment by ghidra1** [comment]
smaller pentry specs which mention a register must come before the larger ones that mention the same register

**Comment by 00xc** [comment]
> Smaller pentry specs which mention a register must come before the larger ones that mention the same register. Is this a standard calling convention? It is not as symmetric as I would expect.

It is currently Rust's internal call convention (at least on x86-64 Linux), but [it is not considered stable](https://prev.rust-lang.org/en-US/faq.html#why-no-stable-abi) and it is not documented as far as I can tell.

Looking at `Ghidra/Processors/HCS12/data/languages/HCS12.cspec`, it seems that something similar is done for the `__asm_xgate` call convention, and in fact the `<pentry>` tags are ordered as you noted above. However, it uses the `register` strategy, so I am not sure the same logic applies.
