### ISSUE TITLE
Layout Algorithm name error

### ISSUE THREAD

**Issue by tomnelson** [NationalSecurityAgency/ghidra#3441]
A saved layout algorithm name, like 'Hierarchical', set via Tool Options will result in this error:

Attempted to set an action state by a user type not contained herein: Hierarchical
ghidra.util.exception.AssertException: Attempted to set an action state by a user type not contained herein: Hierarchical
	at docking.menu.MultiStateDockingAction.setCurrentActionStateByUserData(MultiStateDockingAction.java:240)
	at ghidra.graph.visualization.DefaultGraphDisplay.setInitialLayoutAlgorithm(DefaultGraphDisplay.java:1049)
	at ghidra.graph.visualization.DefaultGraphDisplay.lambda$doSetGraphData$47(DefaultGraphDisplay.java:1042)
	at ghidra.util.Swing.lambda$runNow$2(Swing.java:227)
	
possibly because the saved layout algorithm name String from the AbstractOptions valueMap is compared using == instead of .equals here in MultiStateDockingAction.java:

	public void setCurrentActionStateByUserData(T t) {
		for (ActionState<T> actionState : actionStates) {
			if (actionState.getUserData() == t) {.   <<<<<<<<<<<< maybe use .equals ?
				setCurrentActionState(actionState);
				return;
			}
		}

Note that the 'value' for 'Hierarchical' in the below screenshot shows 2 different objects

![image](https://user-images.githubusercontent.com/105223/134177413-48a63f09-1dea-44dd-a228-0d6b86ae205e.png)

**Comment by dragonmacher** [comment]
This code has recently been going through changes.  Can you provide the commit hash that exhibits this behavior?

**Comment by dragonmacher** [comment]
I was able to reproduce it.  Should be easy to fix.

**Comment by tomnelson** [comment]
There's also a typo here:
			layoutFunction.apply(LayoutAlgorithmNames.COMPACT_HIERACHICAL).build();

in LayoutTransitionManager.java

in the symbol name. Might as well fix that too.
