### ISSUE TITLE
(LoaderService) Unexpected Loader exception from Old-style DOS Executable (MZ) java.lang.RuntimeException: java.lang.IllegalAccessException: class generic.continues.ContinuesFactory cannot access a member of class ghidra.app.util.bin.format.pe.debug.DebugCOFFSymbolAux$AuxFile with modifiers "public"

### ISSUE THREAD

**Issue by bravosierra99** [NationalSecurityAgency/ghidra#3442]
**A PE that I have loaded before on Ghidra 10.2 will not load properly on Ghidra 10.3.  It is identified as Raw Binary as opposed to PE.  Even when I manually select the proper language, it fails to identify almost everything and throws the above error**

**To Reproduce**
1. drag and drop attached file in 10.3
2. see it fail to identify the file as PE
3. select language manually `x86 | default | 64 | little | Visual Studio`
4. click analyze
5. see exceptions raised, missing many functions

**Expected behavior**
The file should load as well as it does on 10.2

**Screenshots**
10.2, aka expected behavior
![image](https://user-images.githubusercontent.com/8898577/134275749-6d06f216-afc5-4984-bf54-b8f1b91d6078.png)
![image](https://user-images.githubusercontent.com/8898577/134275830-e0b25c79-8584-4ac8-afc5-2a8bab70058b.png)
10.3 aka the bugs
![image](https://user-images.githubusercontent.com/8898577/134275906-202e6f49-944d-435b-bb96-ab006e09d73a.png)
manually selected proper language and then
![image](https://user-images.githubusercontent.com/8898577/134275982-b30b7f8b-0073-4575-88a8-68329f56a4c6.png)

**Attachments**
[application.log](https://github.com/NationalSecurityAgency/ghidra/files/7207437/application.log)

**Environment (please complete the following information):**
 - OS: [Windows 10 20H2 19042.1237 ]
 - Java Version: [e.g. 12.0.2]
 - Ghidra Version: [e.g. 10.0.3]
 - Ghidra Origin: [official ghidra-sre.org distro] 

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
To restore the behavior of 10.0.2, uncomment this line in your `support/launch.properties` file:
```
#VMARGS=-DContinuesInterceptor.enabled=true
```
Can you please share the binary so we can fix it with the above line commented out?

**Comment by ryanmkurtz** [comment]
Actually no need to share the binary...we have it fixed in master already.

**Comment by bravosierra99** [comment]
GitHub only sends me email... sometimes. I'll give this a try locally, and glad to hear it's fixed!

**Comment by bravosierra99** [comment]
and that worked like a charm.

**Comment by ryanmkurtz** [comment]
I'll backport the fix so it ends up in our next bug-fix patch release.
