### ISSUE TITLE
Double Clicking XRef moves cursor to wrong field

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#3445]
**Describe the bug**
Double clicking on an XRef field to go to that location results in the one below it being selected and going to that location instead.

**Environment (please complete the following information):**
 - OS: Win 10
 - Java Version: 11
 - Ghidra Version: 10.1_DEV f00f7afa6b0d30f9032a9e3dbee43d3e340cc36a
 - Ghidra Origin: locally built

**Additional context**
This is a bit more difficult to reproduce than described but if you try it enough times you should encounter it.

**Comment by dragonmacher** [comment]
This just changed recently.   I will see if I can find an example case.
