### ISSUE TITLE
Debugger: I get a "Couldn't step into" error despite the stepping actually working

### ISSUE THREAD

**Issue by aldelaro5** [NationalSecurityAgency/ghidra#3452]
**Describe the bug**
When setting up Ghidra to work with a gdb stub on mgba (a Nintendo GameBoy Advance emulator) and clicking on "step into" from the object window, the stepi command will be correctly issued to gdb as well as the actual stepping will work, but Ghidra will throw an error message saying it "Couldn't step into". Manually issuing a stepi command via the interpreter does not cause the error suggesting there is something wrong with how Ghidra works specifically when clicking the button to issue the command.

**To Reproduce**
1. Install mgba, you can find the repository with instructions here: https://github.com/mgba-emu/mgba
2. Install devkitarm to have a gdb called arm-none-eabi-gdb (gdb-multiarch and regular gdb will NOT work)
2. Download this open source ROM from the GBA jam 2021 (the .gba file) https://itch.io/jam/gbajam21/rate/1120303
3. Install this extension to allow to load .gba file into ghidra (you will need to change the extension.properties file to make it work with ghidra 10.0.3) https://github.com/SiD3W4y/GhidraGBA
4. Create a non shared project and import the .gba, it should say the format is GBA ROM. You may auto analyse as it can help with the rest.
5. Create a script file with the following commands: 
```
set architecture armv4t
define info proc mappings
echo 0x0 0xFFFFFFFF 0x100000000 0x0 mem \n
end
target remote localhost:2345
```
6. Launch mgba and go to file -> open rom and select the .gba, you should see a DVD logo bouncing continuously.
7. In mgba, go to tools -> start GDB server, leave everything default and click start, the emulation should pause on its own
8. Back to ghidra, start the debugger tool and open the .gba program to pupulate the static listing.
9. Create a new debugger connexion. Select IN-VM GNU gdb local debugger and place the path of your arm-none-eabi-gdb in your launch command and click connect. A gdb session should open in the terminal.
9. Execute the script you created earlier with a source command, you should now be connected to mgba.
10. Add an SW_EXECUTE breakpoint at 08000704, this just seems to be a function that runs continuously making it a good candidate to test breakpoints and stepping.
11. Issue a continue command to the interpreter or click continue in the object window, you should see the breakpoint being hit. (you may not see it and see the emulator getting frozen, but you can go to emulation -> reset on mgba and it should now work).
12. From this point, you can issue a stepi command and it should work as expected, but if you press step into from the object window instead, it will throw an error saying it couldn't step into, but a look at the interpreter would reveal the step actually took place.

**Expected behavior**
To not see an error message about a stepping operation that completed

**Environment:**
 - OS: Arch Linux
 - Java Version: 11.0.12
 - Ghidra Version: 10.0.3 (note, this MUST be done on this version because it introduced the map identically button as well as other fixes to make this setup work)
 - Ghidra Origin: Official ghidra-sre.org distro

**Attachements**
Here's a log of the error: 
[ghidra step into.txt](https://github.com/NationalSecurityAgency/ghidra/files/7232245/ghidra.step.into.txt)

**Comment by d-millar** [comment]
Well, hmmm, so I was able to reproduce the issue and understand the problem.  I thought at first arm-none-eabi-gdb was using the deprecated version of the mi2 command "-thread-select", but, after looking at it a little more closely, it appears it doesn't support any version of "-thread-select".  You can verify this yourself by running "interpreter-exec mi2 -thread-select --thread 1 1" or  "interpreter-exec mi2 -thread-select 1" in the console of a straight arm-none-eabi-arm session - generates the confusing "-thread-select: USAGE: threadnum" message.   Interestingly, this is also apparently an issue for gdb-multiarch.  Don't have a brilliant solution for you yet - need to talk to @nsadeveloper789 a bit and figure out what route we want to take.  Hopefully, back to you later today or tomorrow....

**Comment by d-millar** [comment]
OK, well, after much discussion and some more debugging, we have id'd the actual problem - I don't think you're going to like it, though.  So, both gdb-multiarch and arm-none-eabi-gdb DO support the '-thread-select" commands in all of their flavors, which is great, but your emulator does not.  In particular, if you look at the code in mgba/src/debugger/gdb-stub.c, am pretty sure there is no support for either the H or vCont packets.  Am guessing no one had any real need for them.

That said, right now, many of our commands attempt to set the active thread before proceeding.  We're going to try to re-work the code so this is less pervasive, i.e. check to see if the current thread is the thread requested and skip the activation for this case.  If you have a target that is multi-threaded and want to do something "off-thread", however, you're still going to get burned.  We may be able to suppress the error, but that functionality still won't be there and the debugger will probably not do what you expect/want it to do.  Thoughts?

**Comment by d-millar** [comment]
Going to correct one thing I just said - it looks like the packet that's actually being sent is the T packet.  The stub does have logic for H (which interestingly says, "This is faked because we only have one thread").

**Comment by d-millar** [comment]
Just following up, if you add a line to mgba/src/debugger/gdb-stub.c::_parseGDBMessage after line 630:
     case 'T':
the problem pretty much goes away.  Am not sure this is really a solution you'd be happy with, but it's a workaround for the moment.

**Comment by d-millar** [comment]
We have two new internal tickets on the docket one for minimizing the use of thread-select and the other for logging the errors of that kind in the console versus the pop-up.  The conversation about how to handle potentially unsupported commands has been ongoing for a while and will no doubt continue until we have some satisfactory solution.  If you have suggestions, we're all ears.  It's a tricky issue, and any input is appreciated.  In the meantime, keep us posted if you hit other issues and good luck with your projects!
