### ISSUE TITLE
Operator precedence for general pattern expressions

### ISSUE THREAD

**Issue by Freax13** [NationalSecurityAgency/ghidra#3457]
What is the precedence for the operators used in general expression patterns defined in section 7.5.2 of the sleigh manual?

**Comment by jrmuizel** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Features/Decompiler/src/decompile/cpp/slghparse.y#L82 lists the operators in order of lowest precedence to highest

**Comment by Freax13** [comment]
Thanks
