### ISSUE TITLE
Convert to char sequence displays as single char literal in decompiler

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#3458]
**Describe the bug**
Converting a scalar value to a character sequence in the listing causes it to display as a single character literal in the decompiler. This is often displayed in the wrong encoding since it is assumed to be a wide/utf-x literal.

**To Reproduce**
1. Find a scalar in the listing
2. Right-click->Convert->Char Sequence

**Expected behavior**
A converted char sequence should be displayed in the decompiler as such.

**Environment (please complete the following information):**
 - Ghidra Version: Since equates/conversions were added to the decompiler.

**Additional context**
I do not understand why this has not yet been reported.

**Comment by ghidra1** [comment]
Which listing was used to create converted Equate?  Decompiler or Assembly

How does the Equate appear in the 1) menu action name, 2) Equate and associated References table, 3) assembly listing, 4) decompiler listing?  You should be able to compare at least 3 of these 4 for the equate you created.  In the Equate Table the Value will be the String rendering used.  If the corresponding Ref Addr is a memory address you should more than likely see the applied Equate in the Assembly listing.  If Ref Addr is a big number (i.e., hash) this corresponds to a decompiler hashed location and would not be applied within the Assembly listing.  A sample constant and string for the 4 cases above would be helpful in better understanding the issue.

**Comment by ghidra1** [comment]
Creating equates (e.g., convert) in assembly listing is not guaranteed to render in decompiler listing, and those established in decompiler are not guaranteed to render in assembly listing.  This is due to the differences in how such equates are correlated to a particular scalar value in each listing.  We would need to fully understand a detailed scenario (and sample) to attempt to diagnose.

**Comment by astrelsky** [comment]
> Creating equates (e.g., convert) in assembly listing is not guaranteed to render in decompiler listing, and those established in decompiler are not guaranteed to render in assembly listing. This is due to the differences in how such equates are correlated to a particular scalar value in each listing. We would need to fully understand a detailed scenario (and sample) to attempt to diagnose.

I had not provided a sample or much detail because I had saw it as so obvious that something wasn't right. However trying to get an example does not produce what I remember it producing on older versions of Ghidra. There is definetly more going on here than meets the eye or I have finally lost my last remaining bit of sanity 🤣 . I'll close this as the current behavior is actually better then what I got while trying to come up with a sample. If I do encounter something I can reproduce and I actually haven't lost my mind I'll re-open it.
