### ISSUE TITLE
Implementation of Android's packed relocation format (APS2) displays offsets incorrectly

### ISSUE THREAD

**Issue by monabomble** [NationalSecurityAgency/ghidra#3462]
**Describe the bug**

When analysing an Android 11 (ARM32) shared object file (.so), the displayed relocation offsets within the AndroidElfRelocationTable in the .rel.dyn section (SHT_ANDROID_REL) appear to be incorrect. Specifically, this is evident when the relocation's *group_flags* has the value zero. 

**To Reproduce**

1. Load an Android .so into Ghidra and allow auto-analysis.
2. Navigate to the .rel.dyn section
3. Expand the 'AndroidElfRelocationTable' and first 'AndroidElfRelocationGroup'
4. Verify that group_flags is zero
5. Calculate reloc_offset_0 manually (signed LEB128 decode) and compare to displayed value (DAT_xxxx)
6. The values will differ and subsequent displayed values will also be incorrect.

**Expected behavior**

The ReadOnlyDataTypeComponent (DAT_xxxx) labelled *reloc_offset_N* (where N is a 0-based index), should increase from an initial sleb128 encoded value, by a delta offset encoded in the next *reloc_offset_N* element. So in the example provided below, the value of *reloc_offset_0* should be DAT_0004d004, but the displayed value is DAT_0009a008.

A secondary problem is that Ghidra uses a default image base of 0x10000. Ideally, the displayed value would account for this load bias so that auto-analysis can pick up any cross references. The *reloc_baseOffset* should account for this, but it remains at 0 - presumably the dynamic linker would modify this to reflect the load address, but I'm not sure what the best strategy for Ghidra would be (modify the binary or simply account for the current load address and add a comment to reflect this).

**Screenshots**
![image](https://user-images.githubusercontent.com/64267954/135074401-75d7197f-4db4-4c68-a438-6c4b400a50cc.png)

**Attachments**
N/A

**Environment:**

 - OS: Pop!_OS 21.04 (Linux)
 - Java Version: openjdk 11.0.9.1
 - Ghidra Version: 10.0.3
 - Ghidra Origin: Official ghidra-sre.org distro

**Additional context**

Interestingly, the stored value of *reloc_offset_N* (as opposed to the displayed value), appears to be correct. The code responsible for creating the ReadOnlyDataTypeComponent can be found [in the getAllComponents method](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/elf/AndroidElfRelocationGroup.java#L129) of the AndroidElfRelocationGroup class.

As the internal model information appears correct, this could suggest that the local variable *relocOffset* should be passed as the 5th parameter to the ReadOnlyDataTypeComponent constructor instead of the *sleb128.offset* value (as shown below):

```Java
sleb128 = LEB128Info.parse(reader, true);
relocOffset += sleb128.value;
DataTypeComponent dtc = new ReadOnlyDataTypeComponent(
    new AndroidElfRelocationOffset(dataMgr, relocOffset), this,
	sleb128.byteLength, list.size(), sleb128.offset, "reloc_offset_" + i,
	null);
list.add(dtc);
```

**Comment by ghidra1** [comment]
Note: The 5th argument of ReadOnlyDataTypeComponent is the relative byte offset from the start of the containing AndroidElfRelocationGroup datatype.

**Comment by ghidra1** [comment]
I have identified and corrected various issues related to the ELF Android relocation markup.  I have also added missing support for ELF Arm32 RELR.   These changes are in review but will hopefully appear in Ghidra 10.1.  Ticket will close when changes have been pushed to master branch.

**Comment by monabomble** [comment]
Fast work! Thank you
