### ISSUE TITLE
[FR] support native terminal launching for gdb

### ISSUE THREAD

**Issue by tbennett6421** [NationalSecurityAgency/ghidra#3464]
**Is your feature request related to a problem? Please describe.**
I am unable to SSH into localhost and do not have local admin.

**Describe the solution you'd like**
I'd be nice for Ghidra to support the native environment and either spawn a shell in which to run gdb or use the native terminal emulators such as iTerm2, gnome-terminal, or Terminator

**Describe alternatives you've considered**
If that is not feasible, would it be possible to connect to a raw socket locally exposed via some mechanism such as 
nc -nvlp 12345 -e /bin/bash

**Comment by d-millar** [comment]
@tbennett6421 Could you provide a little more info about what your native environment is?  Also, have you tried the GADP or IN-VM agents?

**Comment by tbennett6421** [comment]
I was using OS X big sur at work. That's the only thing I have tried out the debugger on. I only saw the one option for debugging via gdb over ssh and no other selections were available. I'm not sure how to use GADP or IN-VM agents or how to configure them. They weren't listed so I figured gdb was the only option.

Later on today I will try it on Windows 10 Pro, Ubuntu Desktop 20.04, and Kali Linux rolling, to see what options are there. Perhpahs it works fine out the box for those platforms, I was just reporting my experience under OS X. Generally Kali Linux, Windows 10 Pro or Ubuntu Desktop are my go-to for using Ghidra.

**Comment by d-millar** [comment]
OK, so on the OS X front, 10.1 will probably solve your problem - likely out sometime next month.  On Windows or Linux, I think the other options are what you are looking for.  GADP spawns a separate process that wraps the gdb MI2 interface;  IN-VM does the same from within the VM use by Ghidra (which, of course, means, if the debugger dies, Ghidra goes with it).  Give them a spin and let us know if they do what you're hoping for.

**Comment by tbennett6421** [comment]
Okay, I tried the debugger on windows and it seemed to work okay. I just wasn't sure on the options for OS X.

**Comment by d-millar** [comment]
For OSX, you'll need to wait for 10.1 unless you're interested in building gdb on OSX.

**Comment by tbennett6421** [comment]
okay, I just raised this since I thought that was the only method. Feel free to close it if this should be resolved in the next release
