### ISSUE TITLE
Debugging 32-bit Windows software on 64-bit Ghidra

### ISSUE THREAD

**Issue by Schala** [NationalSecurityAgency/ghidra#3479]
So, I've had a bit of a dilemma. When I try to debug a 32-bit Windows binary with Ghidra on a 64-bit Windows OS, I get "SECURE: Not allowed to be loaded: C:\Windows\System32\dbghelp.dll" in the interpreter and breakpoints seem to be ignored, labeled as "INEFFECTIVE."

Doing some research, it's most likely a problematic difference with 64 bit and 32-bit. Unfortunately, Java 8 seems to be the last 32-bit runtime for Windows. Is there a way to fix this issue?

**Comment by d-millar** [comment]
@Schala  Basically your issue is that system dlls can't be loaded on the fly, i.e. dlls in the Sytem32 folder. Same issue as #2585. The tricky bit is that you’re going to need to get a loadable copy of the debug DLL’s into the load path ahead of the system copy.  The easiest solution we’ve found is to copy the dbgXxxx.dll’s (dbgeng, dbgmodel, dbghelp) or in fact the entire bin portion of the SDK if you have it into the JDK.  Search for dbghelp in Issues above (without the is:open search key) for more details regarding where exactly to place them and why this happens.

**Comment by d-millar** [comment]
More detail from#3090:  copy them into C:\Program Files\Amazon Corretto\jdk_11.0.4_10\bin (your path to the the JDK may differ)

**Comment by Schala** [comment]
Appreciated, I'll try that.

**Comment by Schala** [comment]
@ryanmkurtz No, I have not unfortunately.

**Comment by ryanmkurtz** [comment]
@Schala Do you still need it triaged on our end?  It has been in limbo in the `Waiting on Customer` state because @d-millar was waiting for your response about your JDK.  

Would you like to continue the dialog or shall we close the ticket?

**Comment by Schala** [comment]
Oh shhot! Sorry! Yes. I am using JDK 17 for this.

**Comment by d-millar** [comment]
OK, well, still not clear that I understand what's going on, but here's my current understanding....

When you run javaw.exe on Windows, it automatically loads dbgcore.dll and dbghelp.dll, I believe, primarily for the purpose of symbol resolution.  By default, it will grab the versions in the WIndows/System32 directory.  Dbgeng and/or dbgmodel are loaded via JNA during the debugger start-up process.  Native.loadLibrary (used by the debugger), generally speaking, will respect the "jna.library.path" variable passed to java.  However, if the versions of dbgcore/help loaded by java directly are inconsistent with the versions of dbgeng/model, it appears the loads will fail and the debugger will hang.

You would think you could influence the load process for dbgcore/help with something like "-Djava.library.path" or just setting "Path", but these appear to have little affect.  I think the path is at least partially hardwired somewhere, so the only way to override the System32 versions of those libraries is to copy them into the bin directory that javaw.exe lives in.  If you do that, you can either copy the rest of the debugger dll's into jdk/bin or use "-Djna.library.path" to direct the JNA load to the correct versions.

It's a shame this is such a complicated mess, but seems to be unavoidable in its current state.

**Comment by Schala** [comment]
Will do, thank you! I'll get back to you once I try this out
