### ISSUE TITLE
Nearly 300 warnings when compiling pdb.exe

### ISSUE THREAD

**Issue by mcfi** [NationalSecurityAgency/ghidra#349]
**Describe the bug**
Nearly 300 warnings are shown when compiling pdb.exe of Ghidra in Visual Studio 2019. Of course, not all warnings are actual bugs, it's still good engineering practice to kill all of them and prevent future bugs.

**To Reproduce**
1. Clone Ghidra and open it in Visual Studio 2019 Enterprise
2. Go to Ghidra Source\Repos\ghidra\Ghidra\Features\PDB\src\pdb
3. Double-click the pdb.sln
4. Change configuration manager to Release x64 and click rebuild.
5. ~300 warnings show up.

**Expected behavior**
0 warning.

**Environment (please complete the following information):**
 - OS: Windows 10 19H1
 - Java Version: 12.0
 - Ghidra Version: 9.0.2

**Comment by d-millar** [comment]
@mcfi - excellent!  Thanks for the lead/suggestion!

**Comment by nihilus** [comment]
Wouldn't it be possible as well to make pdb.exe cross-platform as well, since MS open-sourced components of DIA related to CV and PDB?

**Comment by d-millar** [comment]
> Wouldn't it be possible as well to make pdb.exe cross-platform as well, since MS open-sourced components of DIA related to CV and PDB?

Excellent suggestion!
