### ISSUE TITLE
Ghidra 9.0.2 broke decompliation of dex files

### ISSUE THREAD

**Issue by F3real** [NationalSecurityAgency/ghidra#350]
**Describe the bug**
Decompilation of dex files stopped working on Ghidra 9.0.2.
Now I get errors like:
`XML processing error: Unknown attribute: metatype`

or

`Low-level Error: Unable to resolve type: Activity.initActivity`

in decompilation window.

**To Reproduce**
1. Add dex file
2. Click on function to show decompiled code

**Expected behavior**
Decompiled code is shown as in Ghidra 9.0.1

**Environment:**
 - OS: Win 10
 - Java Version: 11.0.2
 - Ghidra Version: 9.0.2

**Comment by caheckman** [comment]
I'm reproducing the problem and working on a patch. Thanks for reporting this.
