### ISSUE TITLE
10.0.3 Debugger Resync Issue

### ISSUE THREAD

**Issue by resrever** [NationalSecurityAgency/ghidra#3509]
**Describe the bug**

I am getting "Resync: Missed loaded module/library: /home/user/testarm" when debugging a binary using qemu-arm.  I can get the dynamic view and debugging working in 10.0.2, but I get the Resync error in 10.0.3 and 10.0.4 and I cannot debug.

**To Reproduce**
1. Build a static ARM binary (I'm using a simple hello world binary for now)
2. Run the binary `qemu-arm -g 2345 testarm`
3. In the Ghidra debugger, use "IN_VM GNU gdb local debugger" and the launch command "/usr/bin/gdb-multiarch"
4. Run the following commands in the interpreter window:
`set architecture arm`
`file /home/user/testarm`
`source /home/user/gdb_info_proc_mappings/substitute_mappings.py` (optional)
`target remote :2345`
`starti`
5. The Debug Console table has the following lines:
`Listener ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider$MyObjectListener@31a299fd caused exception processing attributesChanged`
`Resync: Missed loaded module/library: /home/user/testarm`
`Error processing GDB output`
`local Pty session. PID = 6995`

The last two lines also occur on the working 10.0.2 version, but the first two occur on 10.0.3 and 10.0.4.

**Expected behavior**
The disassembly shows up in the Dynamic view.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.4
 - Java Version: OpenJDK 11.0.11
 - Ghidra Version: Works in 10.0.2, stopped working in 10.0.3 and 10.0.4
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**

The substitute_mappings.py script is one that I wrote to use the data from `maintenence info sections` to populate the `info proc mappings` command so Ghidra 10.0.2 would sync the dynamic view and listing.  The bug occurs regardless of whether I include that line.

**Comment by resrever** [comment]
Github doesn't seem to like attachments with the .py extension, so remove the .txt I had to add.  It is a GDB python script that can be loaded by running "source substitute_mappings.py" after loading the file.

[substitute_mappings.py.txt](https://github.com/NationalSecurityAgency/ghidra/files/7355312/substitute_mappings.py.txt)

**Comment by d-millar** [comment]
Awesome - thank you!

**Comment by resrever** [comment]
If I don't set the architecture then it doesn't work.  Strangely, it appears to work if I use "set architecture armv5t", but the disassembly in Dynamic vs. Listing view do not match because my target is 32-bit LE armv8.  It seems like the default architecture detected by gdb-multiarch is the same as "set architecture arm", and I don't know of a more specific architecture string I can specify.

**Comment by d-millar** [comment]
Hmmm, I'd be curious as to what "show architecture" returns after you've done "target remote" w/o first setting the architecture.  You probably know this, but "set architecture" with no param will dump all the possibilities.  I will try to see if I can figure out a best match for "32-bit LE armv8".

**Comment by resrever** [comment]
Oh no I didn't know about "set architecture" with no param.  If I don't set the architecture, it says it is currently "arm".  I don't see anything beyond armv5, so maybe they are all lumped into "arm" because the bytecode hasn't really changed?

**Comment by d-millar** [comment]
I guess what I'm wondering is, in your third case, do you always get the "AddressSpace 'ram'" error or is it sporadic?

Will try the armv5t case - see if I can reproduce.
Re ANSI codes, we don't process the color codes in the Interpreter yet.  Would recommend just turning them off.

**Comment by resrever** [comment]
[substitute_mappings.py.txt](https://github.com/NationalSecurityAgency/ghidra/files/7367465/substitute_mappings.py.txt)
Here is the substitute_mappings.py script I'm using with the fix for the '[0]' line beginnings to work with gdb 9.2.

**Comment by d-millar** [comment]
OK, I will give you a shout once they're pushed.  They be in the "patch" branch.  Slight delay in our push schedule right now, as we have tests that are failing.

Your scenario may also trigger another bug we haven't fixed yet - if you're missing registers, you may need to issue "shell stty -icanon" in the Interpreter as part of your setup before hitting "target remote".  Am hoping today/tomorrow to also take a look at the Dynamic/Static listing errors you mentioned - see if I can reproduce those.

**Comment by d-millar** [comment]
Hmmm, OK, we need an actual fix for that second bug.  My workaround doesn't seem to work, and am pretty sure the disassembly issue is caused by the inability of the debugger to read the registers, i.e. it's defaulting to thumb mode because it can't read the register that would tell it otherwise.

**Comment by resrever** [comment]
Ah, 4 works to synchronize, but it doesn't help 5.  There are no modules listed though, and I am setting breakpoints using the listing view.  Will submit a new issue.
