### ISSUE TITLE
Add ability to import symbols from .debug files

### ISSUE THREAD

**Issue by mogery** [NationalSecurityAgency/ghidra#3513]
**Is your feature request related to a problem? Please describe.**
When debugging certain software, especially Unity games, it is very essential to be able to import symbols from a `.debug` file.
[GDB already has this functionality.](https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html)

**Describe the solution you'd like**
An "Import PDB"-esque option to provide the path to a `.debug` file.

**Describe alternatives you've considered**
An included script would also do a job just fine. I have attempted to use objdump in conjunction with ImportSymbolsScript.py in order to accomplish this but it left me with a lot of warnings and lag.

**Additional context**
These ELF files have a bunch of debug symbols but no code inside of them.

**Comment by ryanmkurtz** [comment]
Fixed by f023b8ad3f125f2285646df812737d6e1fa77e48

**Comment by userse31** [comment]
Does it uh... Does it do absolutely nothing for anyone else?

`ImportSymbolsScript.py> Running...
Created label 0x7650f35a at address None
Traceback (most recent call last):
  File "/opt/ghidra_11.4.2_PUBLIC/Ghidra/Features/Jython/ghidra_scripts/ImportSymbolsScript.py", line 62, in <module>
    createLabel(address, name, False)
java.lang.NullPointerException
java.lang.NullPointerException: java.lang.NullPointerException
ImportSymbolsScript.py> Finished!`

**Comment by dev747368** [comment]
Seems like you are having a problem running @mogery 's ImportSymbolsScript.py.  You should probably contact him directly for that.
