### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by squidboy7** [NationalSecurityAgency/ghidra#3514]
**Describe the bug**
wont let me build ghidra

**To Reproduce**
1. run gradle buildGhidra

Error: 

> Task :Utility:compileJava
/home/myName/Desktop/Clones/ghidra-master/Ghidra/Framework/Utility/src/main/java/ghidra/Ghidra.java:18: error: cannot find symbol
import java.awt.Taskbar;
               ^
  symbol:   class Taskbar
  location: package java.awt
/home/myName/Desktop/Clones/ghidra-master/Ghidra/Framework/Utility/src/main/java/ghidra/GhidraLauncher.java:72: error: cannot find symbol
        @Deprecated(since = "10.1", forRemoval = true)
                            ^
  symbol:   method since()
  location: @interface java.lang.Deprecated
/home/myName/Desktop/Clones/ghidra-master/Ghidra/Framework/Utility/src/main/java/ghidra/GhidraLauncher.java:72: error: cannot find symbol
        @Deprecated(since = "10.1", forRemoval = true)
                                                 ^
  symbol:   method forRemoval()
  location: @interface java.lang.Deprecated
/home/myName/Desktop/Clones/ghidra-master/Ghidra/Framework/Utility/src/main/java/ghidra/Ghidra.java:44: error: cannot find symbol
                Taskbar.isTaskbarSupported();
                ^
  symbol:   variable Taskbar
  location: class ghidra.Ghidra
4 errors

> Task :Utility:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Utility:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

**Environment (please complete the following information):**
 - OS: Arch Linux x86_64
 - Java Version: OpenJDK11
 - Ghidra Version: newest version as of today
 - Ghidra Origin: cloned from github

**Comment by astrelsky** [comment]
Did you run `gradle -I gradle/support/fetchDependencies.gradle init` first?

**Comment by squidboy7** [comment]
> Did you run `gradle -I gradle/support/fetchDependencies.gradle init` first?
> 
> Edit: Looking further it seems this may be an os specific issue.
> 
> As a sanity check may you try frame a fresh clone?

yes i did run that
