### ISSUE TITLE
Setting multiple register values combines into one, degrades decompiler

### ISSUE THREAD

**Issue by pd0wm** [NationalSecurityAgency/ghidra#3515]
**Describe the bug**
I'm working on a V850 binary, which needs to two global register values to be set for `gp` and `tp` to correctly compute references. However, if I set them both using "Set Register Values" they get combined into a 64 bit register `r4r5`. This results in degraded compiler behavior. It clearly still knows what the register is set to, but any relative addresses are not computed correctly. If I remove `r4r5` from the v850 sleigh (which is possible since it's not used anywhere), behavior is correct.

**To Reproduce**
1. Open a V850 binary
2. "Set Register Values" for both `gp` and `tp`.
3. Observe they are combined into `r4r5` and degraded decompilation results.

**Expected behavior**
I expect the compiler to compute any relative addresses to `gp` and `tp` for me and show the correct references/labels instead of `puVar2 = &<addr of gp>; puVar2[-0x...] = ....`.

I'm not sure on the expected behavior of combining the registers into one "assume". Are they supposed to stay separate, or is the decompiler supposed to handle this better?

**Screenshots**
Combined register value after setting both `tp` and `gp`
![2021-10-17-154028_441x131_scrot](https://user-images.githubusercontent.com/1314752/137630248-c0c68c2a-19c6-4fbf-b4b7-58d68535e318.png)

Wrong decompilation results (`tp=0x3ff8100`)
![2021-10-17-154202_646x861_scrot](https://user-images.githubusercontent.com/1314752/137630261-353cf421-581d-4f9b-b0bf-de191c4e0b9a.png)

Correct decompilation results after removing `r4r5` from the sleigh.
![2021-10-17-154558_715x811_scrot](https://user-images.githubusercontent.com/1314752/137630266-baaaff5d-0ced-4e11-9e48-fb2612fcbcba.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Java Version: Openjdk 16.0.1+9-Ubuntu-120.04
 - Ghidra Version: ghidra_10.0.4_PUBLIC_20210928
 - Ghidra Origin: github releases zip file

I'd like to help fix the issue, but I'm not exactly sure where the issues lies. Is this a bug in the v850 sleigh or does this go deeper?

**Comment by esaulenka** [comment]
I think, this issue should be fixed in decompiler, not in sleigh.
I am faced with same behavior in Tricore - it also uses two registers for relative addressing.

In my opinion, if user fixed two separate registers, decompiler should not cosider they as one large register, even if they overlap.

**Comment by esaulenka** [comment]
@pd0wm Willem, I found a more clear workaround for this issue.
You can specify `r4r5` as unaffected by function call in `V850.cspec` file.

I am tested same trick with Tricore (there is the same bug), and it is working!

@ Ghidra team, please look at this trouble. For V850 processor, `r4` and `r5` registers (also known as `gp` and `tp`) already present in `unaffected` section of cspec file. But decompiler consider, that they can be changed by function call. To change it, one can delete definiton of `r4r5` or force add it to unaffected.

**Comment by vergil-SI** [comment]
> @pd0wm Willem, I found a more clear workaround for this issue. You can specify `r4r5` as unaffected by function call in `V850.cspec` file.
> 
> I am tested same trick with Tricore (there is the same bug), and it is working!
> 
> @ Ghidra team, please look at this trouble. For V850 processor, `r4` and `r5` registers (also known as `gp` and `tp`) already present in `unaffected` section of cspec file. But decompiler consider, that they can be changed by function call. To change it, one can delete definiton of `r4r5` or force add it to unaffected.

This worked amazingly for me @esaulenka. You're a lifesaver. 

I'm curious if you can you think of a reason why this would be working on Linux, but not on a Windows device? 

I'm successfully able to fix the problem with your technique on my Manjaro install, however someone I'm working with remotely on the repository cannot seem to get the same results when they make the same fix on windows. I then spun up a Windows 10 VM myself, used the same ghidra version (10.3) and same jdk version 17.0.8 as my linux installation, and found they were correct. I couldn't get the change in the cspec file to fix the decompilation view (even after fully removing ghidra, the project, and all the hidden ghidra files, then making the change before having ever started a freshly unzipped ghidra release.

**Comment by emteere** [comment]
Can you post a copy paste of some of the bytes for a function that is showing issues in the v850.
We can add the registers as unaffected, but also might be able to use the prefersplit tag in the .cspec as well.

**Comment by pd0wm** [comment]
These are the bytes of the function shown above. Loaded at 0x000267a0 in case it matters.
```
031ed4ff63ff290063bf250063c7210063cf1d0063d7190063df150063e7110063ef0d00257f7995637f050005777c95860043770800a4c7b19a84cfb19ad83e0f0004d7b39a84dfb39ad8c29cc2da667f00c8620cd984bfb59adb00d8d29fd2d7ee0f00d8ba9cba06e0bfff9ef0845fb19aa457b19a848fb39aa487b39a435f0400847fb59a43570500438f060043870700437f08001c30193823660400636701000242054abfffd6ee245f30b38a5a811d247f28b38a7ac115f5df48028cda64dfb8b21b68ed00e0d1b2058069ed00646fb8b244c739b344ef1eb344bfb1b423bf250023c7210023cf1d0023d7190023df150023e7110023ef0d0023ff2900031e2c007f00
```

**Comment by emteere** [comment]
You can add the following lines to the V850.cspec and see if it solves your issues.
I believe it will.  I'll put in a change for it.

 ```
   <stackpointer register="sp" space="ram"/>
 
+  <prefersplit style="inhalf">
+    <register name="r2sp"/>
+    <register name="r4r5"/>
+  </prefersplit>
+  
   <default_proto>
     <prototype name="__stdcall" extrapop="0" stackshift="0">
```

**Comment by pd0wm** [comment]
@emteere That fixes the decompiler issues! The code listing still combines the assumed register into "r4r5", but maybe that's not a real issue.

I also think https://github.com/NationalSecurityAgency/ghidra/issues/3015 might be a dupe of this issue, so that can be closes as well when this is resolved.

@esaulenka mentioned he had the same issue with tricore. Which registers are combining for you? a0/a1 and a8/a9 maybe?

**Comment by emteere** [comment]
Yes, I see what you mean in the listing.  It would be better to change that to show the smaller register.
assume r4r5 = 0x3ff810000600000
The prefer split isnt currently available outside the decompiler.
There would need to be a tag possibly on the register in the .pspec.

assume r4r5 = 0x3ff810000600000

**Comment by esaulenka** [comment]
> the same issue with tricore. Which registers are combining for you? a0/a1 and a8/a9 maybe?

Yes, typically Tricore compiler uses a0 and a1, but sometimes can use a8 / a9 as well.
So, @emteere , could you also fix `tricore.cspec ` ?
```
  <prefersplit style="inhalf">
     <register name="p0"/>
    <register name="p8"/>
    <register name="e4"/>   <-- e4 / e6  was already here. Not sure that it is needed (typically compiler splits automatically), but leave it as is -->
    <register name="e6"/>
  </prefersplit>
```
