### ISSUE TITLE
Prepare the upgrade to the upcoming Gradle 8.x, there are some incompatible features for now:

### ISSUE THREAD

**Issue by XVilka** [NationalSecurityAgency/ghidra#3527]
It would be nice to prepare the upgrade to the upcoming Gradle 8.x, there are some incompatible features for now:
- https://github.com/gradle/gradle/milestone/164
- https://docs.gradle.org/current/userguide/upgrading_version_7.html

This is what `gradle help --scan` outputs:

![image](https://user-images.githubusercontent.com/203261/138092764-795a2fca-afd5-4ff3-8069-35931e89baa7.png)

_Originally posted by @XVilka in https://github.com/NationalSecurityAgency/ghidra/issues/3050#issuecomment-947615608_

**Comment by ryanmkurtz** [comment]
Yes, we will have to address this in the coming months.

**Comment by endrin** [comment]
I think there are more Gradle 8 -related issues than those already fixed here.

Arch repos got Gradle upgraded to 8.0 a few days ago, and now attempting to run `gradle --init-script gradle/support/fetchDependencies.gradle init` on a freshly cloned Ghidra repo ends with the following error:

```
FAILURE: Build failed with an exception.

* Where:
Script '<path omited>/ghidra-src/gradle/root/jacoco.gradle' line: 77

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'JacocoMerge' for root project 'ghidra-src' of type org.gradle.api.Project.
```

I believe this is somehow related to [this issue](https://github.com/gradle/gradle/issues/12767) but I don't know Gradle enough to say for sure.
