### ISSUE TITLE
export file error

### ISSUE THREAD

**Issue by weiwang999** [NationalSecurityAgency/ghidra#354]
I decompiled the binary of helloworld and then exported a file with binary format and got the file
helloworld.bin
I found the error 
helloworld.bin: ERROR: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld- error reading (Invalid argument)

readelf -h helloworld.bin 
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x4006b0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          8312 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         8
  Size of section headers:           64 (bytes)
  Number of section headers:         29
  Section header string table index: 26
readelf: Error: Reading 0x740 bytes extends past end of file for section headers

I don't know what's going on behind the error

**Comment by ryanmkurtz** [comment]
Duplicate of #19
