### ISSUE TITLE
Low-level Error: Symbol extends beyond the end of the address space

### ISSUE THREAD

**Issue by madebr** [NationalSecurityAgency/ghidra#3550]
**Describe the bug**
The decompiler shows the following error in the decompile window:
```
  Low-level Error: Symbol $$undef0000001c extends beyond the end of the address space
```

This might have something to do with me adding types + tagging functions (called by this function).
When going back to a much older revision of my reversing work, the function decompiles fine..
Because I don't understand what is causing the problem, I don't know where to start to fix this.

**To Reproduce**
1. Go to the function in question in the code browser, I don't know how I got this function in this broken state

**Expected behavior**
The function gets decompiled.

**Screenshots**
![image](https://user-images.githubusercontent.com/4138939/138754267-5761a714-e94f-44d5-8ea1-7065cc461fbd.png)

**Attachments**
I'ld love to provide more info when requested.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 15.0.2
 - Ghidra Version: 10.0.4
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by madebr** [comment]
This issue was because amateur-me used wrong types for the arguments.

**Comment by ryanmkurtz** [comment]
Thanks for following up!
