### ISSUE TITLE
Keyboard access to "Storage Address Editor"

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3561]
**Is your feature request related to a problem? Please describe.**
Any changes using this dialogue must be done by mouse.

**Describe the solution you'd like**
Things like _tabbing_, _shortcuts_ etc. need implementing.

**Describe alternatives you've considered**
Forced to use the mouse.  Inconvenient when user has to use _MouseKeys_.

**Additional context**
Here's the dialogue:
![image](https://user-images.githubusercontent.com/67698927/139450866-1ea9daf6-2744-468b-b1f0-62b6ddb992d6.png)

**Comment by dragonmacher** [comment]
I believe this can be used entirely from the mouse now, as of 19066d15.

**Comment by Wall-AF** [comment]
@dragonmacher It's the use of keyboard only, i.e. NO mouse, use Key `F2` instead on the selected datatype that doesn't fully work.  At least not on Windows 11.

**Comment by dragonmacher** [comment]
This is working for me on Linux.   Without using the mouse, F2 triggers the edit when the data type cell is already selected.  You can tell it is selected by the cell's updated border color.

With your cell selected, F2 still does not trigger the edit?

**Comment by Wall-AF** [comment]
@ryanmkurtz @dragonmacher This fix has broken the `F2` functionality for the `Structure Editor` dialog!!!
![image](https://user-images.githubusercontent.com/67698927/224757649-3c12a52a-d21d-4761-a54b-eb91b2f45d61.png)

**Comment by dragonmacher** [comment]
I am creating a fix for this.

**Comment by ryanmkurtz** [comment]
Should be working again.

**Comment by Wall-AF** [comment]
Unfortunately not!

Made the changes locally to class `CompositeEditorPanel` but I noticed that the `Structure Editor` dialog (class `StructureEditorProvider`) uses `CompEditorPanel` internally!
https://github.com/NationalSecurityAgency/ghidra/blob/3be7e2d0a6bdbf5fdf0413c1af4d3be902465dee/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/compositeeditor/StructureEditorProvider.java#L39

Not sure what to change in this though!

**Comment by Wall-AF** [comment]
@dragonmacher no, it doesn't.  I've noticed though, with the dialog in the state shown [above](https://github.com/NationalSecurityAgency/ghidra/issues/3561#issuecomment-1466427089), pressing `Ctrl+a` selected everything in the `Listing` and consequently `Decompile` panels instead of selecting the datatype!

Hope this info helps.

**Comment by Wall-AF** [comment]
@dragonmacher Oops, sorry, just discovered that **since this fix** the position of (for want of a better description) _the cursor_ **has** to be directly on the datatype column.  Previously, pressing `F2` on any the non-editable columns would move to the datatype column automatically and then open it for editing!  The same is/was true for the `Union Editor` and the (unchecked) others.

Is it possible for that to work again with this fix as well???

**Comment by dragonmacher** [comment]
> Is it possible for that to work again with this fix as well???

I will try to fix this.

**Comment by Wall-AF** [comment]
Thank you.

**Comment by Wall-AF** [comment]
> This should be fixed now in master.

It is, but we get NPE occasionally.  The fix is, replace
https://github.com/NationalSecurityAgency/ghidra/blob/d76f59ee69b39aef1490e455561d54750bc3dc43/Ghidra/Framework/Docking/src/main/java/docking/widgets/table/GTable.java#L954
with
`else if (null != editorComponent) {`
