### ISSUE TITLE
Listing view does not follow program when Debugging with remote target

### ISSUE THREAD

**Issue by staringatphones** [NationalSecurityAgency/ghidra#3563]
**Describe the bug**
While using Ghidra to debug a binary on a remote GDB server using Ubuntu, the "Listing" view does not track with program step/execution. 

**To Reproduce**
1. Install the GNU Arm Embedded Toolchain from the developer.arm.com website. The "gcc-arm-none-eabi-10.3-2021.10-aarch64-linux.tar.bz2" tarball was downloaded and extracted to `/opt/gcc-arm-none-eabi-10.3-2021.10/`. ([Link](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads) to downloads page, [Direct Download Link](https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-aarch64-linux.tar.bz2) to tarball).
2. Launch Ghidra.
3. Import an arm-compiled ELF file into the Ghidra project.
4. Analyze the ELF using the Ghidra CodeBrowser tool.
5. Open the analyzed ELF in the Ghidra Debugger tool.
6. Run any GDB server that has a connection to the intended microcontroller. I am using the ST-LINK_gdb_server on macOS running at `10.0.2.2:61234` for the purposes of this issue. 
7. Back in Ghidra on Ubuntu, in the Debugger Targets view, click the icon to "Create a new connection to a debugging agent."
8. Select "IN-VM GNU gdb local debugger" in the main dropdown.
9. In the "GDB Launch Command" entry, type `/opt/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gdb`
10. Leave the "Use existing session via new-ui" box unchecked. 
11. Click Connect. 
12. In the Interpreter view, there should now be a `(gdb)` prompt. Type `target remote 10.0.2.2:61234` and press enter. 

*The first screenshot below shows the Ghidra debugger in this state. Several error messages have already occurred in the Debug Console view, which can be seen in the screenshot. A .csv of all of the error messages is also included in the Attachments section.*

13. At the `(gdb)` prompt, run `ni` to step to the next instruction. GDB does successfully step, but the Listing view in Ghidra does not refresh to reflect this action. 

*The second screenshot show this state. Three new errors have also occurred, and can be seen in the screenshot.*

14. At the `(gdb)` prompt, type `load ~/Desktop/BluePillDemo_USART_Echo_Grinch.elf` (the binary intended to be debugged). 
15. Type `ni`, still the Listing view does not update. 

*The third screenshot shows this state.*

16. Type `file ~/Desktop/BluePillDemo_USART_Echo_Grinch.elf`
17. Type `ni`, still no update. 

*The fourth screenshot shows this state.*

**Expected behavior**
As the program was debugged using GDB, the Listing view should update to show the current line of assembly that GDB is executing. I am unsure whether the `load` and `file` commands were necessary or correct, I included screenshots of the results of those commands for the sake of completely documenting the steps I have tried. (Indeed, loading the symbols with the `file` command seems to have introduced a new problem regarding the libraries linked in the ELF.)

**Screenshots**
Please see italicized text in To Reproduce section above for descriptions of the screenshots and the state in which the Ghidra Debugger was in each one. 

![Screen Shot 2021-10-29 at 12 53 49 PM](https://user-images.githubusercontent.com/24702155/139473933-95025892-ada4-4b58-9d67-75368a7f25c3.png)

![Screen Shot 2021-10-29 at 12 54 19 PM](https://user-images.githubusercontent.com/24702155/139473948-8fb24d68-e960-450f-9ef0-56e1b8d328e0.png)

![Screen Shot 2021-10-29 at 12 55 03 PM](https://user-images.githubusercontent.com/24702155/139473962-d4806383-90cc-4347-b6fe-4cd7339ec8a2.png)

![Screen Shot 2021-10-29 at 12 55 42 PM](https://user-images.githubusercontent.com/24702155/139473980-be8e999c-1d24-48d9-be31-2680bdfb9fc3.png)

**Attachments**
[error_msgs.csv](https://github.com/NationalSecurityAgency/ghidra/files/7443726/error_msgs.csv)
This file contains the full text of the error messages from the Debug Console view. 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Java Version: 11.0.11
 - Ghidra Version: 10.0.4
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by staringatphones** [comment]
No, I did not. I have not revisited this in some time (the project I was doing at work has since wrapped up)

**Comment by ryanmkurtz** [comment]
Thanks for getting back to me.  I will close this issue.
