### ISSUE TITLE
Windows PE driver file has embedded symbols (function names etc.) which Ghidra ignores

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#3564]
[Example_driver_file.zip](https://github.com/NationalSecurityAgency/ghidra/files/7444056/Example_driver_file.zip)
I have been examining an old Windows .SYS driver file. The file has symbols; loading it into IDA all the functions have their proper names for example.

Ghidra does not recognise the function names embedded in the file. Not sure if that's a bug or missing feature but obviously it's quite frustrating...

Attached is a zip archive containing the file in question.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.12
 - Ghidra Version: 10.0.0.4
 - Ghidra Origin: ghidra-sre.org

**Comment by dev747368** [comment]
How many function names should be showing up?  (I do see 2 named functions)

**Comment by M-a-r-k** [comment]
Pretty much every function in the PE file has a name. Attached is a screenshot taken immediately after loading it into IDA. Also you can load the file into a binary/hex editor and see all the function names in it.
![Screenshot](https://user-images.githubusercontent.com/2737716/139495034-581a2530-d3df-4722-80b5-cc01f96f3960.png)

**Comment by dev747368** [comment]
I think I see what you are talking about.  It looks like Ghidra isn't even loading that portion of the binary when importing.  I'm no PE expert, but I'm guessing its debug info outside of the PE/COFF spec that we don't know about.

I'll talk to some others and see if there is a bug or its just something we don't support.

**Comment by M-a-r-k** [comment]
Here's another example. Also a Windows 98-compatible driver file, but from a different developer. Maybe both were built with Visual Studio 6.0? I think that would have been current at the time.
[IM120WDM.zip](https://github.com/NationalSecurityAgency/ghidra/files/7448495/IM120WDM.zip)
