### ISSUE TITLE
xml_importer.py, xml_exporter.py print function issue

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#3565]
The IDA import and export python files (xml_importer.py and xml_exporter.py) contain lines like this:
`print "\n" + msg`

I think they need to be changed to e.g.
`print("\n" + msg)`
in order to work properly.

Python 3.10 on Windows 10. I also got another error:
```
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/path/plugins/xml_exporter.py", line 71, in run
    xml.export_xml()
  File "C:\path\python\idaxml.py", line 286, in export_xml
    begin = time.clock()
AttributeError: module 'time' has no attribute 'clock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/path/plugins/xml_exporter.py", line 80, in run
    print("\n" + msg + "\n", sys.exc_type, sys.exc_value)
AttributeError: module 'sys' has no attribute 'exc_type'
```

**Comment by mumbel** [comment]
these scripts are python2,  `python "\n" + msg` is correct

**Comment by astrelsky** [comment]
> these scripts are python2,  `python "\n" + msg` is correct

Iirc from my own usage the python3 scripts provided are using the file containing the problem.

**Comment by ryanmkurtz** [comment]
The solution to this issue is to use Python 2.  Note that there are pull requests that deal with moving this code to be compatible with Python 3.
