### ISSUE TITLE
Ability to copy'n'paste data type in same category to create a new one.

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3568]
**Is your feature request related to a problem? Please describe.**
Whenever I need to create a new `data type` that is based upon another, I cannot just copy'n'paste the original one in the same `category` in the DTM.

**Describe the solution you'd like**
After copying said `data type`, `paste` should be enabled and when performing the `paste` opperation, a dialogue should appear requesting the new name.

**Describe alternatives you've considered**
1) Copy the original `data type`;
2) Creating a new temporary `category` (3 steps);
3) Paste into `new category`;
4) Rename copied type;
5) Cut newly renamed type; and finally
6) paste new type into original location (`category`) (2 steps).

**Comment by mumbel** [comment]
You might want to describe your problem a little better as after reading the issue, this is already feature (fairly sure since public release)

right click->copy or left click and ctrl+c the current type
right click->past or left click and ctrl+v the category

```
helloworld.bin
    Foo/
        bar
```
would then have
````
helloworld.bin
    Foo/
        bar
        Copy_1_of_bar
````

**Comment by quietust** [comment]
Part of the confusion might be over the fact that you must select a **folder** in order to paste - if you select an object within said folder, the Paste command is disabled.

**Comment by Wall-AF** [comment]
Thanks both for your comments above.  @quietust your clarification was precisely correct, and therefore it can be done.

However, with the caveats above, it should still work without having to move the caret to the **folder** in order to `paste`.  Consequently this becomes a _buglet_ with the current implementation so I'll leave this open for now.

**Comment by astrelsky** [comment]
Just another 2 cents here. I too would expect to be able to paste it on a type and have it go in the containing category. The prompt to replace should appear iff one with the name already exists and the existing one isn't what is in the clipboard. 

Drag n drop behavior should stay the same imo.
