### ISSUE TITLE
importFileAsBinary API behavior

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#3570]
I have a script that I run with `analyzeHeadless` on a flat binary file, like so:
`analyzeHeadless /tmp tmpProj -import path_to_bin_file -scriptPath path_to_script_folder -preScript my_script.py arg1 -loader BinaryLoader -noanalysis -processor ARM:LE:32:Cortex -deleteProject`

`my_script.py` is using the `PseudoDisassembler` to do some light disassembly on the unanalyzed file. It simply instantiates a `PseudoDisassembler` on the `currentProgram`, and runs a function called `disasm_analyzer`. Due to the overhead associated with starting Ghidra, I'd _like_ to import the file from within Ghidra, and not have to run `analyzeHeadless` for each file/languageID.

The alternative script that uses `importFileAsBinary` (which sounded like what I need) is roughly (Python pseudocode):
```
lang_ids = ['ARM:LE:32:default', 'ARM:BE:32:default', 'ARM:LE:32:Cortex']
f = File(file_path)
provider = SleighLanguageProvider()
for description in provider.getLanguageDescriptions():
    # Filter the desired lang_ids and analyze
    if str(description.languageID) in lang_ids:
        language = provider.getLanguage(description.languageID)
        default_cspec = language.getDefaultCompilerSpec()
        program = importFileAsBinary(f, language, default_cspec)
        disasm = PseudoDisassembler(program)
        # This function produces very different results here vs. when being run after the BinaryLoader
        disasm_analyzer(program, disasm) # Uses PseudoDisassembler to do stuff
```

My assumption was that `importFileAsBinary` could accomplish this, but I get wildly different results between importing this way vs. importing the file with the `-loader BinaryLoader -processor desired_langID` from the analyzeHeadless command. 

When running the `importFileAsBinary`-based script, some architectures produce the same results, but others appear to be unable to disassemble any instructions at all, which leads me to believe I'm missing an API call or step somewhere to properly instantiate the language/cspec before initializing the `PseudoDisassembler`, but I have not been able to find the right mechanism. Is there something I can add here that will properly simulate the `BinaryLoader`, or do I need to directly use that class instead of `importFileAsBinary`?

**Comment by ryanmkurtz** [comment]
The headless analyzer does things a little differently:

```
language = DefaultLanguageService.getLanguageService().getLanguage(new LanguageID(languageId));
if (compilerSpecId == null) {
	compilerSpec = language.getDefaultCompilerSpec();
}
else {
	compilerSpec = language.getCompilerSpecByID(new CompilerSpecID(compilerSpecId));
}
```
Can you give this a try in your script?

**Comment by ryanmkurtz** [comment]
So I'm guessing you would want:
```
language = DefaultLanguageService.getLanguageService().getLanguage(new LanguageID("ARM:LE:32:Cortex"));
default_cspec = language.getDefaultCompilerSpec();
program = importFileAsBinary(f, language, default_cspec)

**Comment by ryanmkurtz** [comment]
There's another difference too, so let me know if that doesn't work...I can dig deeper.

**Comment by bdemick** [comment]
Same result, unfortunately. Here's an attempt to iterate through all known LanguageIDs with a little more detail using your suggestion:

```
from ghidra.program.model.lang import LanguageID
from ghidra.program.util import DefaultLanguageService
from ghidra.app.plugin.processors.sleigh import SleighLanguageProvider
from ghidra.app.util import PseudoDisassembler
from java.io import File

def main():
    provider = SleighLanguageProvider() 
    f = File('/Users/user/bins/test.binary')

    for langd in provider.getLanguageDescriptions():
        # Try all of the possible language IDs known to Sleigh
        lang = DefaultLanguageService.getLanguageService().getLanguage(LanguageID(str(langd.languageID)))
        default_cspec = lang.getDefaultCompilerSpec()  # Get the default CompilerSpec object for the language
        program = importFileAsBinary(f, lang, default_cspec)
        disasm = PseudoDisassembler(program)
        disasm_analyzer(program, disasm, None)
```

The `disasm_analyzer` is excluded for brevity, but it just effectively scans the program for instructions that fit a raw PCode pattern. And I'm fairly convinced it isn't the problem here, because the implementation is shared between the `-loader BinaryLoader -processor language_id` script and the `importFileAsBinary` script. The difference is that the analyzer output is consistent between scripts _for a handful of LanugageIDs_, but for a majority of LanguageIDs in the latter script, there are simply no instructions decoded.

**Comment by ryanmkurtz** [comment]
Why are you iterating over language ID's?

**Comment by ryanmkurtz** [comment]
It would be helpful if you could come up with a single instance where the behavior of the headless command line is different than the behavior of your script version where you are trying to do the same exact thing as the headless command (i.e., 1 language id, 1 cspec)

**Comment by bdemick** [comment]
I'm developing some techniques for architecture guessing and detection. I work primarily with firmware, often with unknown architectures and often with multiple architectures packaged into an image. I'd actually like to do this with `libsla`, but this is a little faster to iterate on and I'm [running into some issues there as well](https://github.com/NationalSecurityAgency/ghidra/discussions/3556#discussion-3650707).

As an example, `ARM:LE:32:Cortex` produces the same results for both approaches. `6502:LE:16:default` looks fine using the BinaryLoader, but disassembles 0 instructions with `importFileAsBinary`. Actually now that I'm inspecting the results more closely, it looks like the discriminator is the address size. Anything with a 32-bit address size looks to be producing the same results, but 16 and 64 are not.

**Comment by bdemick** [comment]
I took a stab at following `BinaryLoader`'s logic explicitly, using the Python:
```
...
lang = DefaultLanguageService.getLanguageService().getLanguage(LanguageID(str(langd.languageID)))
load_spec_chooser = LcsHintLoadSpecChooser(lang, None)
loader_filter = SingleLoaderFilter(BinaryLoader)
loader_args_options_chooser = LoaderArgsOptionChooser(loader_filter)
byte_provider = RandomAccessByteProvider(f)
loader_map = LoaderService.getSupportedLoadSpecs(byte_provider, loader_filter)
load_spec = load_spec_chooser.choose(loader_map)
lang_cspec_pair = load_spec.getLanguageCompilerSpec()
cspec = lang.getCompilerSpecByID(lang_cspec_pair.compilerSpecID)
addr_factory = lang.getAddressFactory()
program = createProgram('tmp', lang.languageID, lang_cspec_pair.compilerSpecID)
log = MessageLog()
opts = loader_args_options_chooser.choose(load_spec.getLoader().getDefaultOptions(byte_provider, load_spec, None, False), addr_factory)
bl = BinaryLoader()
bl.loadInto(byte_provider, load_spec, opts, log, program, TaskMonitor.DUMMY)
disasm = PseudoDisassembler(program)
disasm_analyzer(program, disasm, None)
```

And whaddya know, this works. It's a heckuva way to arrive at this result, and it would be nice if `importFileAsBinary` were able to accomplish this, but it looks as though this does what I need.

**Comment by ryanmkurtz** [comment]
What happens if instead of using `importFileAsBinary`, you use:

```
	public static Program importByUsingSpecificLoaderClass(File file, DomainFolder programFolder,
			Class<? extends Loader> loaderClass, List<Pair<String, String>> loaderArgs,
			Object consumer, MessageLog messageLog, TaskMonitor monitor) throws IOException,
			CancelledException, DuplicateNameException, InvalidNameException, VersionException
```

This is now the headless analyzer imports when you specify BinaryLoader on the command line.

**Comment by bdemick** [comment]
I was looking at that, which is effectively what I'm attempting to simulate. The only argument I wasn't sure of to invoke this directly was what to use as the `consumer` object. Looks like in the headless analyzer that is the HeadlessAnalyzer object.

**Comment by ryanmkurtz** [comment]
You could just do something like:
```
consumer = Object()
```
It can be any object

**Comment by bdemick** [comment]
Okay, I get past the import, but it looks like the file wasn't loaded. 

```
lang = DefaultLanguageService.getLanguageService().getLanguage(LanguageID(str(langd.languageID)))
load_spec_chooser = LcsHintLoadSpecChooser(lang, None)
loader_filter = SingleLoaderFilter(BinaryLoader)
byte_provider = RandomAccessByteProvider(File(target_file))
loader_map = LoaderService.getSupportedLoadSpecs(byte_provider, loader_filter)
load_spec = load_spec_chooser.choose(loader_map)
lang_cspec_pair = load_spec.getLanguageCompilerSpec()
cspec = lang.getCompilerSpecByID(lang_cspec_pair.compilerSpecID)
log = MessageLog()
program = AutoImporter.importByUsingSpecificLoaderClassAndLcs(File(target_file), getProjectRootFolder(),
                                                              BinaryLoader, None, lang, cspec, Object(), log,
                                                              TaskMonitor.DUMMY)
disasm = PseudoDisassembler(program)
disasm_analyzer(program, disasm, None)
```

Yields:
```
Traceback (most recent call last):
  File "/Users/user/scripts/analyzer.py", line 145, in <module>
    main()
  File "/Users/user/scripts/analyzer.py", line 143, in main
    disasm_analyzer(program, disasm, None)
  File "/Users/user/scripts/analyzer.py", line 78, in disasm_analyzer
    gaddr = toAddr(addr)
	at ghidra.program.flatapi.FlatProgramAPI.toAddr(FlatProgramAPI.java:1844)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
java.lang.NullPointerException: java.lang.NullPointerException
```

**Comment by ryanmkurtz** [comment]
The only way I think I can help at this point is if you give me an example binary that doesn't work so I can reproduce it.

**Comment by bdemick** [comment]
Here's an example file (True language ID is `ARM:LE:32:Cortex`).
[demo.bin.zip](https://github.com/NationalSecurityAgency/ghidra/files/7474803/demo.bin.zip)

**Comment by ryanmkurtz** [comment]
Thanks, I'll play with it today and get back to you.  I'm going to focus on the auto_importer side of things because invoking the loader directly isn't really supported...I'm not sure what all the fallout would be with that.  But the auto importer should work, so if there's a bug in there, we can fix it.

**Comment by bdemick** [comment]
Much appreciated! I had a feeling I was greatly abusing things by invoking the BinaryLoader directly 😄

**Comment by ryanmkurtz** [comment]
A couple discoveries:

1. To get the askFile() line working in the GUI, you need to change it to ` target_file = askFile('Select a file to analyze', 'OK').getAbsolutePath()`
2. You'll want to do `byte_provider.close()` at the end of `auto_importer()`...i was getting a lot of warnings
3. I think the main reason the GUI was working for you but headless wasn't is because you had a program open in the GUI, which means the `currentProgram` variable was set to that open program.  If you look at `FlatProgramAPI.toAddr()`, it's doing everything based off of `currentProgram`.  That's probably why you were getting weird results.

**Comment by ryanmkurtz** [comment]
To fix 3, try:

```
from ghidra.program.flatapi import FlatProgramAPI
```
and then in `analyzer()`:
```
api = FlatProgramAPI(program)
...
gaddr = api.toAddr(addr)
```

**Comment by bdemick** [comment]
THANK YOU! Yeah that `askFile` was a typo on my part when hacking together the test script.

At any rate, this fixed it, and TIL about the `FlatProgramAPI` having that connection to `currentProgram`. I do see some warnings when disassembling 6502:

`WARN  Using unknown opinion: Raw Binary, 6502:BE:16:default:default (LcsHintLoadSpecChooser)`

But it doesn't appear to impact the disassembly at all.

Thank you again, you're the 💣

**Comment by ryanmkurtz** [comment]
Sure thing!

**Comment by bdemick** [comment]
One thing I noticed as I'm now running this at scale is that it's using a TON of memory and time, and I had to increase the JVM allocation to get this to run in a reasonable time on a fairly small (40KB) binary. I did add a `closeProgram()` call at the end of every loop in hopes that this would clean up resources, but that didn't seem to make a difference. 

Are there any subtle resources here that might not be getting released? For this program the memory usage should stay fairly static since we import and and close the program at each iteration of the loop. But it looks like there is definitely some stuff hanging around.

**Comment by ryanmkurtz** [comment]
Can I have a new version of your script?

**Comment by ryanmkurtz** [comment]
Sorry I haven't gotten back to you on this...I've been very busy with other things.  Did you figure anything out with it?

**Comment by bdemick** [comment]
No rush or anything. Haven't zeroed in on a leak culprit yet, though. Going to be testing it out on a much larger binary (> 1MB) today at some point to see if it eventually kills the 8GB JVM.

**Comment by ryanmkurtz** [comment]
You might want to play with `program.release(consumer)`.

**Comment by bdemick** [comment]
This appears to have helped quite a bit! The memory usage is definitely not as drastic now.

I simply added:
```
for consumer in program.getConsumerList():
    program.release(consumer)
```
prior to the `closeProgram` call.

Still seeing the java process memory increase about 350MB over the life of the program, so I think there may still be a leak somewhere but I'm not seeing anything else that I'm using that has a `release` or `close` method that can be invoked. It at least completes with a 2GB JVM environment for a 40k file. Will continue to examine.
