### ISSUE TITLE
What causes the database to be deleted by Headless Analyzer?

### ISSUE THREAD

**Issue by lemuellew** [NationalSecurityAgency/ghidra#3574]
### Discussed in https://github.com/NationalSecurityAgency/ghidra/discussions/3560

<div type='discussions-op-text'>

<sup>Originally posted by **lemuellew** October 29, 2021</sup>
The normal database file tree should look like this：
![image](https://user-images.githubusercontent.com/59448437/139408817-cb04c1e2-38de-48a1-94d8-2a5738d79536.png)

But I got wrong database file tree with headless analyzer.
![image](https://user-images.githubusercontent.com/59448437/139409344-7eff8141-606f-46b3-8f66-32e2c4576991.png)

</div>

**Comment by lemuellew** [comment]
According to `~journal.dat`, it seems to delete the domain file but I am sure I did not do any delete operation in my headless script.
```
IADD:00000000:/29b54fcc694f39f108ce0cf6cbf3b8f2b43165b72bfda95e755b52b037a443a7
IDSET:/29b54fcc694f39f108ce0cf6cbf3b8f2b43165b72bfda95e755b52b037a443a7:b9fabcac5f18863299237072744
IDEL:/29b54fcc694f39f108ce0cf6cbf3b8f2b43165b72bfda95e755b52b037a443a7
```

**Comment by bdemick** [comment]
I wonder if this is related at all to an issue I'm seeing in #3570 -- definitely a difference between headless and GUI modes for some things.

**Comment by lemuellew** [comment]
> I wonder if this is related at all to an issue I'm seeing in #3570 -- definitely a difference between headless and GUI modes for some things.

Actually, it’s not the same problem. I use a headless analyzer to analyze many files in batches, only this one database file lost the domain file. 
`IDEL` means `Item Delete`

**Comment by ghidra1** [comment]
Depending on how you are invoking headless and what scripts are doing the resulting program database may be considered temporary and deleted at the end of processing.  I would need to see how you are invoking headless (i.e., command line) and the script code being run against the imported program.

**Comment by ghidra1** [comment]
BTW - this is not a database file error.  It simply appears the program was deleted.
