### ISSUE TITLE
Function Discovery using LC_FUNCTION_STARTS

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#3586]
**Is your feature request related to a problem? Please describe.**
The MachO Header sometimes contains the load command `LC_FUNCTION_STARTS` which contains information about all the function starts in the binary. This often includes functions that are not discovered during the auto analysis of the binary, and due to the nature of e.g. ObjectiveC cannot be directly discovered by XRefs.

**Describe the solution you'd like**
Ghidra should save the list of function starts during the initial loading somewhere and provide an "analysis" that adds these addresses as functions. This analysis should probably be activated by default because in most cases it will be useful.

**Describe alternatives you've considered**
Don't see much of an alternative. I am not aware of any way to access the original binary file bytes in the actual CodeBrowser tool so without changes in the loader itself it doesn't seem to be possible to write a script for this either. It could be enough to expose this information so any kind of load command that isn't implemented in Ghidra could be handled via a user script easily, without having to spin up a development setup and change the loader source code.

**Additional context**

For example in
[this binary](https://github.com/NationalSecurityAgency/ghidra/files/7475243/iOS15_example.zip) Ghidra does not find the function at `000000010000738c` while https://github.com/horsicq/XMachOViewer clearly lists this (amonst others)
![image](https://user-images.githubusercontent.com/8415354/140325374-045521ed-c425-4e45-a089-bdbf94391fa0.png)

**Comment by ryanmkurtz** [comment]
Looks doable.  [This is useful](https://stackoverflow.com/questions/9602438/mach-o-file-lc-function-starts-load-command).

**Comment by ryanmkurtz** [comment]
@fmagin, I have this working, but on some apps it looks like some of the function starts are pointing to switch data.  Have you run into this?

**Comment by ryanmkurtz** [comment]
@fmagin Have you come across any LC_FUNCTION_STARTS addresses that are pointing to switch tables instead of real functions?  I seemingly have this working but for some newer samples we end up creating functions on data in some cases.

**Comment by fmagin** [comment]
@ryanmkurtz  I haven't looked into this much, I only did spot checks and for some binaries I dealt with recently I wrote my own script to do it, and all functions seemed sane.
How obvious is it that it is a switch table? Also which architecture are we talking about, aarch64 or x86?

**Comment by ryanmkurtz** [comment]
This was arch64, in the iOS 15 Weather app. There were several function starts that failed to disassemble, and Ghidra later marked them as switch tables. They were referenced by some kind of load instruction (can't remember the exact one). I should try your above program to see what it says about them.

**Comment by ryanmkurtz** [comment]
XMachOViewer is also identifying it as a function:

<img width="586" alt="Capture" src="https://user-images.githubusercontent.com/5378554/141780252-21b4619c-11fc-4b0e-81e1-0dc08ddb1ee4.PNG">

![image](https://user-images.githubusercontent.com/5378554/141780651-76a862ed-d830-490f-81da-829a75e8c03e.png)

![image](https://user-images.githubusercontent.com/5378554/141780409-5ce7caf9-f727-4339-b55f-8ee44c3e4746.png)

**Comment by ryanmkurtz** [comment]
It just looks like some addresses point to non-functions, for whatever reason.  I'm moving forward with doing the function creation in a very low-priority analyzer, so it ignores things that have already been processed there.  Seems to be getting the job done.
