### ISSUE TITLE
Is there a way to get the offsets of an instruction's opcodes within the instruction?

### ISSUE THREAD

**Issue by ILOVEPIE** [NationalSecurityAgency/ghidra#3588]
Is there a way to get the offsets of an instruction's opcodes within the instruction? I'm trying to get a list of bytes for a specific range of code with all address references zeroed out for a plugin i'm writing.

**Comment by emteere** [comment]
You can get the bits that define an instructions operand using:
```
instruction.getPrototype().getOperandValueMask(opIndex)
```

**Comment by ILOVEPIE** [comment]
Thank you.
