### ISSUE TITLE
Typing in DTM filter results in infinite error popup

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#3598]
**Describe the bug**
Typing a single character in the data type manager's filter results in an infinite pop-up of errors, the pop-up window will count up to 14 errors, all the same looks like, but once it is closed it just pops-up a new one to 14 errors again.  I can eventually clear the filter or trigger something else before the next to cause the pop-ups to stop.  No clue what type I added or imported that started triggering this (shared project and does import a shared type archive).

**To Reproduce**
unknown

**Attachments**
[nosuchobject.txt](https://github.com/NationalSecurityAgency/ghidra/files/7486869/nosuchobject.txt)

** Additional **
I noticed this on a 9.2 and upgraded the image, but did not solve, I can check my 9.2.4 logs if that would be helpful

**Environment (please complete the following information):**
JDK 11.0.10
Windows 10
Ghidra 10.0.4 (official)

**Comment by mumbel** [comment]
[outofbounds.txt](https://github.com/NationalSecurityAgency/ghidra/files/7486978/outofbounds.txt)

Took another look and missed this one.  but looks like all the others are the same

**Comment by dragonmacher** [comment]
The cause of the issue is unclear.  But, it seems like you are using an archive that is part of a shared repository.   The implication in the stack trace is that you have an enum in your DTM that is no longer in the remote repository.     You may be able to fix this by closing the shared archive and getting the latest copy from the repository.

**Comment by mumbel** [comment]
@dragonmacher  thanks for taking a look, ill try different setups/states of using that shared archive and see.  Just now closed the archive and I can't repro (and it was semi-consistent in the current state), so looks like the issue.

**Comment by dragonmacher** [comment]
Good to hear it helped.  I'll close this for now.  Please update with any new information.

**Comment by mumbel** [comment]
Sounds good.  Did the 2nd trace (don't know if you noticed that one) also indicate the same, but not enough info to track down anything in code for any potential fix?

**Comment by dragonmacher** [comment]
The second stack trace shows an issue with the Java JTree that we wrap with our GTree.  Unfortunately, that trace is generic to the point that we can't tell what caused that particular issue.   My guess would be that the first issue caused a failure in the tree loading that put it in an inconsistent/bad state.
