### ISSUE TITLE
How to programmatically set a well-known Win32 API function pointer type?

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#3599]
### Discussed in https://github.com/NationalSecurityAgency/ghidra/discussions/3569

I decided to cross-post this as an issue/question because so far, it has not received any attention:

<div type='discussions-op-text'>

<sup>Originally posted by **huettenhain** October 30, 2021</sup>
How would I programmatically, from a Ghidra script, obtain the `DataType` that represents a function pointer to the `CreateFileW` Windows API function? The data type clearly exists, and I can use it to retype variables through the UI without any problem:

![image](https://user-images.githubusercontent.com/11869704/139544659-9524b320-2688-42d0-bbd0-70707ff14663.png)

However, the `getDataTypes` method from the flat API does not find it, and the following code does not find it either:
```java
DataTypeManager dtm = currentProgram.getDataTypeManager();
for (SourceArchive a : dtm.getSourceArchives()) {
	for (DataType dt : dtm.getDataTypes(a)) {
		println(dt.getName());
	}
}
```
I have spent quite a bit of time trying to figure out how the Ghidra UI does it, without success. Thanks a lot in advance for any help!</div>

**Comment by goatshriek** [comment]
Have a look at the `ResolveX86orX64LinuxSyscallsScript` script included with Ghidra. Specifically, the snippet starting at [line 199](https://github.com/NationalSecurityAgency/ghidra/blob/bda7e0df453fca4c8df51e898404ed6e5314ec61/Ghidra/Features/Base/ghidra_scripts/ResolveX86orX64LinuxSyscallsScript.java#L199) has been useful for me in doing similar things to what I believe you are describing.

```java
AutoAnalysisManager mgr = AutoAnalysisManager.getAnalysisManager(currentProgram);
DataTypeManagerService service = mgr.getDataTypeManagerService();
List<DataTypeManager> dataTypeManagers = new ArrayList<>();
dataTypeManagers.add(service.openDataTypeArchive(datatypeArchiveName));
dataTypeManagers.add(currentProgram.getDataTypeManager());
ApplyFunctionDataTypesCmd cmd = new ApplyFunctionDataTypesCmd(dataTypeManagers,
	new AddressSet(syscallSpace.getMinAddress(), syscallSpace.getMaxAddress()),
	SourceType.USER_DEFINED, false, false);
cmd.applyTo(currentProgram);
```

**Comment by huettenhain** [comment]
Terrific @goatshriek, this is exactly what I needed! My code ended up being this:

	private DataType getDataType(String name, DataType fallback) {
		ArrayList<DataType> matchingDataTypes = new ArrayList<>();
		DataTypeManager dataTypeManager = currentProgram.getDataTypeManager();
		currentProgram.getDataTypeManager().findDataTypes(name, matchingDataTypes);
		if (matchingDataTypes.size() == 0) {
			AutoAnalysisManager am = AutoAnalysisManager.getAnalysisManager(currentProgram);
			DataTypeManagerService service = am.getDataTypeManagerService();
			for (SourceArchive a : dataTypeManager.getSourceArchives()) {
				String archiveName = a.getName(); 
				DataTypeManager dtm;
				try {
					dtm = service.openDataTypeArchive(archiveName);
				} catch (Exception e) {
					continue;
				}
				dtm.findDataTypes(name, matchingDataTypes);
				if (matchingDataTypes.size() > 0)
					break;
			}
		}
		if (matchingDataTypes.size() > 0)
			return matchingDataTypes.iterator().next();
		return fallback;
	}
