### ISSUE TITLE
Windows/arm support non-existent

### ISSUE THREAD

**Issue by woachk** [NationalSecurityAgency/ghidra#36]
**Describe the bug**

Enforcing Thumb for Windows on ARM should be done, as the platform always generates Thumb-2 code, without the ARM execution mode being used.

**Comment by kitlith** [comment]
Is ARM code disallowed/unusable? or is it just that the (most popular?) compiler for the platform only generates Thumb-2 instructions? If it's the former, it makes sense, but if it's the latter then enforcing that would break analysis of programs that, well, include ARM instructions.

**Comment by woachk** [comment]
@kitlith on each context switch, NT sets the architecture back to Thumb. Trying to run programs with ARM code just results in random crashes. (the limitation was relaxed for Astoria/early WSL in NT 10.0, but as NT 6.2 and 6.3 still have it today, toolchains only generate Thumb-2 code)

**Comment by woachk** [comment]
https://docs.microsoft.com/en-us/cpp/build/overview-of-arm-abi-conventions?view=vs-2017

"The instruction set for Windows on ARM is strictly limited to Thumb-2. All code executed on this platform is expected to start and remain in Thumb mode at all times. An attempt to switch into the legacy ARM instruction set may succeed, but if it does, any exceptions or interrupts that occur may lead to an application fault in user mode, or a bugcheck in kernel mode.

A side-effect of this requirement is that all code pointers must have the low bit set. This is so that when they are loaded and branched to via BLX or BX, the processor will remain in Thumb mode and not try to execute the target code as 32-bit ARM instructions."

**Comment by ghidra1** [comment]
Windows cspecs and import opinions have been added to Ghidra for 9.1 to include: ARM-32, Thumb2, and ARM-64 (i.e., AARCH64).
