### ISSUE TITLE
ObjC Methods of Classes are not recovered in iOS Binaries targeting iOS14 and above

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#3611]
**Describe the bug**

The ObjC2 Class analyzers fails to recover any method of a ObjC class if the MachO binary is built targetting iOS14 and above

**To Reproduce**
* Load the attached binary with a Ghidra version that includes https://github.com/NationalSecurityAgency/ghidra/commit/bda7e0df453fca4c8df51e898404ed6e5314ec61 so the pointers can be fixed up and the `class_t` can be found by the analysis 
* Run the auto analysis
* Observe that the class `_TtC22test_sit_fraunhofer_de9TestClass` is created as a symbol, but has no associated methods

**Expected behavior**
Regular recovery of the methods, i.e. all methods are added to the class and and an XRef is added from each of the relative Pointers to its respective target.

**Attachments**
[iOS15_example.zip](https://github.com/NationalSecurityAgency/ghidra/files/7502968/iOS15_example.zip)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11.0.12
 - Ghidra Version: 10.1_DEV, commit 766ff7f72e056f109ed3192b3c3333b80c9deb6c
 - Ghidra Origin: Locally built

**Comment by fmagin** [comment]
Just started stepping through the code, it seems that the small method list should be handled already, so the problem is something different here.

**Comment by fmagin** [comment]
Ah, this is problem has two components:

### Class Pointers use the lower 2 bits as flags

Part 1 is that in `ghidra.app.util.bin.format.objc2.ObjectiveC2_Class#readData` the pointer to the `class_rw_t` is read simply with `index = ObjectiveC1_Utilities.readNextIndex(reader, _state.is32bit);`. This value that is read into `index` isn't simply a pointer, but a pointer where the last two bits are flags, which must be cleared before treating this value as a pointer. In this binary, the class `_TtC22test_sit_fraunhofer_de9TestClass` has one of those bits set, and thus the pointer is wrong by 2 bytes and must be fixed with `index -= index & 0b11`. I don't have a proper development setup currently so I can only do this in the debugger right now, but when I do this I successfully get to the second part of the problem.

### Pointer to Selector Name in small Method list is treated as absolute, but is relative to image base

In `ghidra.app.util.bin.format.objc2.ObjectiveC2_Method#ObjectiveC2_Method`, when `isSmallList` is set, the `namePtr` is read, but this is pointer relative to the base address. I.e. `0x7C2A` is read, but this needs to be `0x100007c2a`. When this is fixed, the analysis successfully finishes. And the function is added to the class as expected.

### Leftover issues/artifacts

This does successfully add the method to the class, but various xrefs and addresses are not correctly modelled/displayed afterwards:

* At `10000c108` the value is treated as `DAT_10000c04a`, which is the literal value there, but this is the pointer where the last 2 bits are flags, and in reality this effectively points to the `class_rw_t` struct at `0x10000c048`
* The small `method_list_t` only indicates that this is an offset from this address, but doesn't seem to actually link it: 
![image](https://user-images.githubusercontent.com/8415354/140905676-90e95dae-2cc3-4008-b339-d5e25cab3463.png)
* The `class_rw_t` object at `10000c048` doesn't seem to get properly displayed, possibly because `10000c04a` already is defined as some kind of data, so the struct can't be applied?
![image](https://user-images.githubusercontent.com/8415354/140906149-31472ea3-e103-41b2-8106-ab2a19c5a8a7.png)

**Comment by fmagin** [comment]
@ryanmkurtz IMO this should also make it into the 10.1 release as this relates to the other MachO/iOS15 changes and AFAIK this isn't addressed in the 10.1-BETA yet. Is this on your radar yet?

**Comment by ryanmkurtz** [comment]
It's next on my list!

**Comment by ryanmkurtz** [comment]
@fmagin I have implemented the fixes for the first 2 main issues.  Where did you learn that the lower 2 bits are flags?  The header file?

**Comment by fmagin** [comment]
The one source I remember is that another library that parses those data structures had it as a [comment](https://github.com/datatheorem/strongarm/blob/27d7bc035186336d1cc8af39637fc15bd2345082/strongarm/macho/objc_runtime_data_parser.py#L570-L575). Large (all?) parts of the ObjC runtime are open source though, and I vaguely recall there being some methods that check those flags, but I'm currently not on the computer with the IDE setup for that code

**Comment by fmagin** [comment]
It might actually be that the lower 3 bits are flags:
The fact that the `class_rw_t` pointer is combined with flags is "documented" here

**Comment by ryanmkurtz** [comment]
Thanks, i came across this too and had the same thoughts but wasn't 100% sure...I'm glad you have the same opinion on it.  I'll mask off 3 bits if it's 64-bit and 2 bits if it's 32-bit.

**Comment by ryanmkurtz** [comment]
I am an Objective-C noob, but I'm starting to think patching our existing file isn't the right way to go in the long run.  We should probably have a whole new set of files that parse objc4 (and 3?).  Hopefully a lot of these changes are backwards compatible.  Regardless, I'm putting these fixes into our existing files.

**Comment by ryanmkurtz** [comment]
Ok, that's good to hear!  I haven't worked in these files much before so I don't know the history of what's changed over the years.

BTW, the fixes I am putting in will address only the 2 main issues you found.  The Leftover issues/artifacts will be addressed later with some changes we are putting in to make pointers more flexible.  We will use your attached binary as an example for testing that when the time comes.
