### ISSUE TITLE
Character colors making it impossible to be read after altering look and feel and on color inversions

### ISSUE THREAD

**Issue by LCRERGO** [NationalSecurityAgency/ghidra#3623]
**Describe the bug**
After Altering the look and feel of Ghidra to my system GTK theme([Adapta](https://github.com/adapta-project/adapta-gtk-theme)) I've noticed that a few submenus  get colors that make it impossible to understand what is writen. It also happens on color inversions but on different submenus
**To Reproduce**
1. Go to 'Edit>Tool Options>Tool>Swing Look And Feel'
2. Change the dropdown menu to 'GTK+'
3. Try creating a new project
4. See The color of the directories

**Expected behavior**
The text should be readable. 

**Screenshots**
Changing the look and feel:
![pic-211110-1421-28](https://user-images.githubusercontent.com/36491033/141163292-56ce2f33-713a-4262-b910-27875da2235f.jpg)
Inverting the colors:
![pic-211110-1425-10](https://user-images.githubusercontent.com/36491033/141163298-48378dcd-e420-48ab-8b5f-8cd29e77b28a.jpg)

**Environment (please complete the following information):**
 - OS: GNU/Linux Debian Bookworm
 - Java Version: openjdk 11.0.13
 - Ghidra Version: Ghidra_10.0.4+git766ff7f72e056f10
 - Ghidra Origin: locally built

**Additional context**
I am using a Window Manager(XMonad), and with Java applications Window Managers require workarounds to be able to show something. What I have done in my case is set the variable `_JAVA_AWT_WM_NONREPARENTING` to 1.

**Comment by dragonmacher** [comment]
Inverted colors have been removed.   You can now change most application colors, icons and fonts by editing the current Theme.

Fixed by e657a701416877f7a77b635662d30cfc25f1b5f0
