### ISSUE TITLE
"Edit Function Signature" does not use calling conventions from the cspec file

### ISSUE THREAD

**Issue by DualTachyon** [NationalSecurityAgency/ghidra#3624]
**Describe the bug**

To help the quality of decompilation, I created some function types so they can be used in structures containing function pointers.
My target CPU is MIPS based (R24K series I believe?) and uses a calling convention that is not available in mips*.cspec.
I added a new calling convention called "extended" in .cspec and this convention is working successfully across the entire program I'm analysing.
However, when I create a "function type", the calling convention list only contains some predetermined names that I found at Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/GenericCallingConvention.java.

My expectation is that "Edit Function Signature" would include the calling conventions declared in a .cspec

**To Reproduce**

1) Add a new calling convention to a cspec with a different name, e.g. "extended".
2) Create a function type, for example "int function_t(int)".

You should notice that the "Calling Convention" list box doesn't contain "extended".

**Expected behavior**

The "Calling Convention" list box should include the additional convention described in .cspec.

**Screenshots**

**Attachments**

I attached my mips cspec.

[mips32le.zip](https://github.com/NationalSecurityAgency/ghidra/files/7516743/mips32le.zip)

**Environment (please complete the following information):**
 - OS: Windows 10 with latest feature pack / updates
 - Java Version: "11.0.2" 2019-01-15 LTS
 - Ghidra Version: 10.0.4
 - Ghidra Origin: In this github repository
 
Many thanks.

**Comment by mumbel** [comment]
So it looks like they use the same/similar calling convention as MIPS 64-bit n32.  Do they ever use they ever use the standard MIPS 32-bit convention?  Any chance that its really 64-32n32?  Do any instructions fail to disassemble?  (I would take a look at the n32 cspec either way to see, there are some differences that look like minor bugs in your spec)

**Comment by DualTachyon** [comment]
I just double checked and the CPU is a "MIPS32® 34Kf™", which according to the datasheet is a 32-bit core.

> Do any instructions fail to disassemble?

Everything disassembles and decompiles fine with "MIPS n32 default".

In any case, the issue I have is not with the convention itself since that I described in my .cspec file works for my case. I don't know if mine differs in anyway with any other similar convention, I only implemented what I see in the binary. The system runs a custom OS (it's a single all-in-one executable) so it is possible that the convention is unusual.

Incomplete or otherwise, I would expect my "extended" convention to show up in the "Edit Function Signature" dialogue box. Am I misunderstanding this?

**Comment by Wall-AF** [comment]
Currently, Ghidra **only** uses built-in conventions in these dialogues (annoyingly).  I have converted the enum `GenericCallingConvention` into a class locally that then adds any protoypes I created to that list.  It is in no way fit to release as I'm sure it doesn't follow the Ghidra ethos!  (But I'm sure you could do something similar.)

**Comment by DualTachyon** [comment]
@Wall-AF Would you mind sharing your change?

Thanks.

**Comment by Wall-AF** [comment]
This is my version: [GenericCallingConvention.zip](https://github.com/NationalSecurityAgency/ghidra/files/7522491/GenericCallingConvention.zip)

It doesn't help with the issue https://github.com/NationalSecurityAgency/ghidra/issues/3273 though!!!

**Comment by ghidra1** [comment]
This is common complaint and recurring discussion.  While we hope to address this limitation in the near future, **Function Definition** data types are limited to fixed enumeration of **Generic Calling Conventions**.  On the other hand, **Functions** are able to refer to calling conventions specified by the associated compiler specification.  

The suggested change is not portable and should not be considered a viable approach to solving the issue.

I would prefer to close this issue as a duplicate.

**Comment by Wall-AF** [comment]
> The suggested change is not portable and should not be considered a viable approach to solving the issue.
> 
I agree.  But it works until we've a better solution.

**NB**: Anyone using it will need to export what they have before upgrading to a more permanent solution.

**Comment by ghidra1** [comment]
How can it handle use of data type archives and use of multiple program architectures/compiler-specs?

**Comment by Wall-AF** [comment]
Its temporary, and just works for someone using a single architecture.

**Comment by ryanmkurtz** [comment]
Duplicate of #3267
