### ISSUE TITLE
Headless Analyzer: Selective Analysis issue

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#3627]
Hello,

I am attempting to only decompile by "selection" in Ghidra headless mode. This is to mimic the following sequence of steps taken in the GUI-version of Ghidra:
1. Import a file
2. Skip the auto-analysis mode
3. Select a range of code to analyze
4. Run auto-analysis

Thus, only the selected code is analyzed. I have tried this and it worked wonderfully. I am now trying to emulate this behavior in Headless mode. I am making a selection in a pre-script as seen below just before analysis begins.

![image](https://user-images.githubusercontent.com/22150653/141361727-1d5ff6ae-b0be-47b1-a9b6-9a57347a67d1.png)

Yet, despite making this selection in the pre-script, the headless analysis runs on _all_ memory & code. I am inferring this from the fact that the time it takes to analyze the file is the same as when I did not have this pre-script. As well, part of the output of the headless analyzer is "INFO  ANALYZING all memory and code: A:\sandbox\0b0ee9f2cba8a89db149f7f8e369a5f6 (HeadlessAnalyzer)" Can you help with this? Much obliged

**Comment by aa-software2112** [comment]
I seemed to have traced the "problem" back to ghidra.app.util.headless.HeadlessAnalyzer, in function analyzeProgram(). It seems that the selection made in the pre-script is ignored by the headless analyzer, and thus nothing I have written regarding pre-selection is considered for auto-analysis. Is there a way to work around this, my research heavily depends on a small subset of thousands of binaries' functions, and running autoanalysis on the whole binary is simply overkill (and impossible time-wise) for me.

![image](https://user-images.githubusercontent.com/22150653/141366177-f6e53a98-0329-4ce8-affa-65722538a877.png)

**Comment by astrelsky** [comment]
Are you looking to run a specific analyzer on your selection or all of them? If you want to run a specific one then you can try disabling all of them and then using the analyzer class you want and run it directly. I would not recommend this outside of headless mode.

**Comment by aa-software2112** [comment]
Hello;
Actually I am looking to run all analysis, but only on a selection of code. I have taken the code above and put it in a pre-script that analyzes over my programmatically-selected range of code (changed mgr.reAnalyzeAll(null) -> mgr.reAnalyzeAll(addressSet)); works now. I suggest anyone else wanting to do this perform the same, namely:
1. pass -noanalysis to the headless analyzer 
2. in a -prescript, use the code in my above post reAnalyze over a selection
3. use a -postscript to perform whatever code you wish regarding your own RE task
