### ISSUE TITLE
Accessing instruction bytes in disassembly action section in SLEIGH

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#3628]
Hello there,

  is it actually possible to derive SLEIGH instruction operands from the instruction opcodes themselves?

  The documentation at https://ghidra.re/courses/languages/html/sleigh_constructors.html#sleigh_disassembly_actions mentions that it could be achieved by using Disassembly Actions Sections ("For certain kinds of instructions, there is a need to calculate values that depend on the specific bits of the instruction, but which cannot be obtained as an integer interpretation of a field or by building with an attach values statement."), but I cannot make it work.

  The SLEIGH slaspec file I'm working on can be minimised as such:

```
define token inst8 (8)
	opcode = (0, 7)
;

define token immediate8 (8)
	imm8 = (0, 7)
;

:BRES imm8, "#"bit is opcode=0x11 | opcode=0x13 | opcode=0x15 | opcode=0x17 | opcode=0x19 | opcode=0x1B | opcode=0x1D | opcode=0x1F ; imm8 [ bit = (opcode - 0x11) / 2; ] {
	# Implementation goes here.
}
```

  but compilation fails with an error on the `BRES` definition line saying "Global symbol 'opcode' is not allowed in action expression".

  Given that the documentation says it can be done, what am I doing wrong here?  I can always work around this by replicating the definitions 8 times, one per opcode with an hardcoded `bit` value, but I have 8 instructions that follow the same pattern and copying and pasting can get a bit tedious...

Thanks!

**Comment by mumbel** [comment]
That does seem odd.  Just grepping really quick I can't see any instructions that check the bit pattern value and also use it in the action like you do for 0x11-0x1f where it has to be one of multiple values.  I would guess easy answer is just make another op to go with it

```
define token inst8 (8)
	opcode = (0, 7)
        bits = (0,7)
        other_bits = (1,3)
;

define token immediate8 (8)
	imm8 = (0, 7)
;

:BRES imm8, "#"bit is bits & opcode=0x11 | opcode=0x13 | opcode=0x15 | opcode=0x17 | opcode=0x19 | opcode=0x1B | opcode=0x1D | opcode=0x1F ; imm8 [ bit = (bits - 0x11) / 2; ] {
	# Implementation goes here.
}
# could just entirely get rid of the action, if your example isn't semi-arbitrary
:BRES imm8, "#"other_bits is other_bits & opcode=0x11 | opcode=0x13 | opcode=0x15 | opcode=0x17 | opcode=0x19 | opcode=0x1B | opcode=0x1D | opcode=0x1F ; imm8  {
	# Implementation goes here.
}
```

hitting this as `value_symbol`
https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Framework/SoftwareModeling/src/main/antlr/ghidra/sleigh/grammar/SleighCompiler.g#L855

**Comment by agatti** [comment]
@mumbel Adding a second op fails with "Error: Mismatched pattern sizes -- 2 vs 1: for table "instruction" constructor from ...".

I'm not sure if I can get by with removing the action as different opcodes use a different base number to subtract to get the bit number to then divide by two.  If I extract a subset of the bits, I'd still have to mask them out somehow, which brings me to square one I guess.  I don't think there's a way to export two variables from a table, is there?

**Comment by mumbel** [comment]
this is stm8 right?   I would say that error is just progressing you along to a new error and your original issue is fixed.  Are you doing some top level "instruction" for a prefix?

change names however you feel, but reading through, this is how I'd implement those
```
define token inst8 (8)
	op = (0, 7)
        xx = (0,7) signed
        hi = (4, 7)
        pos = (1, 3)
        lo = (0, 0)
;
define token inst16(16)
        longmem=(0,15)
;
:BCCM longmem, "#"pos is op=0x90 ; pos & hi=1 & lo=1; longmem  {
	# Implementation goes here.
}
:BCPL longmem, "#"pos is op=0x90 ; pos & hi=1 & lo=0; longmem  {
	# Implementation goes here.
}
:BRES longmem, "#"pos is op=0x72 ; pos & hi=1 & lo=0; longmem  {
	# Implementation goes here.
}
:BSET longmem, "#"pos is op=0x72 ; pos & hi=1 & lo=1; longmem  {
	# Implementation goes here... which i think would be something like:
	*:1 longmem = *:1 longmem | (1<<pos);
}
:BTJF longmem, "#"pos, rel is op=0x72 ; pos & hi=0 & lo=1; longmem ; xx [ rel = inst_start + xx; ] {
	# Implementation goes here.
}
:BTJT longmem, "#"pos, rel is op=0x72 ; pos & hi=0 & lo=0; longmem ; xx [ rel = inst_start + xx; ] {
	# Implementation goes here.
}
```

**Comment by agatti** [comment]
Not STM8 but quite close, actually - [ST7](https://www.st.com/resource/en/programming_manual/pm0002-st7-family-programming-manual-stmicroelectronics.pdf). I was planning to tackle STM8 once ST7 and ST6 were done...

Anyway, ST7 needs indeed prefixes and such and I have them defined:

```
define token prefix_byte (8)
	prefix = (0, 7)
;

define token inst8 (8)
	opcode = (0, 7)
	kind = (0, 3)
	addressing = (4, 7)
;

define token immediate8 (8)
	imm8 = (0, 7)
	addr8 = (0, 7)
	rel = (0, 7) signed
;

define context contextreg
	# Pre-bytes - see page 30 of the programming manual.
	prefix_90 = (0, 0) noflow  # PDY
	prefix_91 = (1, 1) noflow  # PIY
	prefix_92 = (2, 2) noflow  # PIX
;

:^instruction is prefix=0x90; instruction [ prefix_90=1; ] {}
:^instruction is prefix=0x91; instruction [ prefix_91=1; ] {}
:^instruction is prefix=0x92; instruction [ prefix_92=1; ] {}
```

but `BRES` as defined in the first comment should just pass through the three prefix filters and not trigger any other rule (page 37 of the PDF linked above) - I am focusing on getting this to work with direct addressing modes before moving to indirect (and needing a prefix).

I'll see if your implementation can be patched up enough to work on this case as well.  If accessing opcode bytes from actions cannot really be done, well, then documentation has to be changed I guess.  

[ST6](https://www.st.com/resource/en/programming_manual/pm0001-st6-family-programming-manual-stmicroelectronics.pdf) may have the same problem with address and bit opcodes though (CALL, JP, JR\*, RES, and SET).

**Comment by mumbel** [comment]
Ooops, just googled `BRES instruction set manual` and STM8 was first  :D

ST7 does look very close and I think would still work with my approach.

I've not done much with contexts in depth really, do you need to clear the other two in each `^instruction` maybe, or is that part of your action in each instruction, or add a fourth default `^instruction` to clear them?

**Comment by agatti** [comment]
@mumbel anyway, I looked at your approach a bit more - it should indeed work in theory.  In practice, there are some opcodes for which it doesn't trigger even though it definitely should.  

For example using these definitions:

```
define token inst8 (8)
	opcode = (0, 7)
	kind = (0, 3)
	addressing = (4, 7)
	bit_upper = (4, 7)
	bit_lower = (0, 0)
	bit_position = (1, 3) dec
;

:BRES imm8, "#"bit_position is bit_upper=0x01 & bit_lower=0x01 & bit_position ; imm8 {
	local address:2 = imm8;
	local value = *:1 address;
	value = value & ~(1 << bit_position);
	*:1 address = value;
}

:BSET imm8, "#"bit_position is bit_upper=0x01 & bit_lower=0x00 & bit_position ; imm8 {
	local address:2 = imm8;
	local value = *:1 address;
	value = value | (1 << bit_position);
	*:1 address = value;
}
```

`11 12` gets correctly decoded as `BRES DAT_0012,#0x0`, but `14 12` makes Ghidra complain about not being able to find a constructor instead of decoding the opcode to `BSET DAT_0012,#0x2`.

Either I'm missing something really important here or I'm a bit at a loss...  Overlapping instruction definitions should have been caught at compile time, so I hope I can safely exclude that - but *missing* bit definitions in this case is definitely a bit weird.

Does anyone know any way to debug the decoding process?  As in a trace that says something like "Skipped table :$WHATEVER for opcode at $ADDRESS ($BYTES) => $field not matching" or similar.

**Comment by mumbel** [comment]
@agatti  there is a debug plugin script you can run, DebugSleighInstructionParse.java, with cursor (currentAddress) at the beginning of the instruction bytes.  You'll see it narrowing down instructions/variables/constructors/etc... should be helpful.

That's super weird, and that looks correct to me at least reading it.  Could it be the context I was mentioning in the last comment?

**Comment by agatti** [comment]
@mumbel That script is awesome indeed, thanks a lot!

So, it seems like it gives up right before evaluating BSET... https://gist.github.com/agatti/8b23b4596d678e52f1662af5f8099d32 which doesn't make sense - I'll keep on looking still.

**Comment by mumbel** [comment]
No problem, hope its not too hard to figure out from here.  Yeah, I agree, improved documentation/description/better error message would be nice there.

**Comment by agatti** [comment]
For that specific case I guess the order of the opcodes in the file matters.  I just put `BSET` before `SRL` and things magically worked. I'm still puzzled on why it didn't backtrack after `SRL` failed to match and end up evaluating `BSET`.  Looks like a bug to me, but maybe is it by design?

**Comment by ghidra1** [comment]
In reference to the original post:
```
:BRES imm8, "#"bit is bits & opcode=0x11 | opcode=0x13 | opcode=0x15 | opcode=0x17 | opcode=0x19 | opcode=0x1B | opcode=0x1D | opcode=0x1F ; imm8 [ bit = (bits - 0x11) / 2; ] {
	# Implementation goes here.
}
```
Pattern needs `opcode` field identified in a non-match form to be able to reference in action.  It also appears `( )` are needed to group or'd patterns.  Example:
```
:BRES imm8, "#"bit is bits & opcode2 & (opcode=0x11 | opcode=0x13 | opcode=0x15 | opcode=0x17 | opcode=0x19 | opcode=0x1B | opcode=0x1D | opcode=0x1F ); imm8 [ bit = (bits - 0x11) / 2; ] {
	# Implementation goes here.
}
```

**Comment by ghidra1** [comment]
Sorry - post went prematurely.  Still evaluating...

**Comment by mumbel** [comment]
@ghidra1  dont know if you came across the pull request yet, but the complete/updated code is here https://github.com/NationalSecurityAgency/ghidra/pull/3631

I think it is still a question/bug/documentation issue of "what does this error mean, and what exactly is wrong here to not allow it".  I hopefully didn't ruin that message/intent w/ helping @agatti  to get around the initial issue.

**Comment by agatti** [comment]
@ghidra1 if this should have been posted to the discussion board, I apologise - however in this case you may also want to remove the "question" and "feature request" options in the issue report submission template, or put a warning in the text template for those options pointing the user to the discussion board.

**Comment by ghidra1** [comment]
The original post was fine and had a clear answer to the issue.  The discussion appeared to stray from the original sleigh compile error and the title of this issue.   I came in rather late and simply wanted to answer the original issue as documented which was very straight-forward.

The original error "Global symbol 'opcode' " meant that `opcode` was undefined as a symbol.  Symbols available to an action include registers, token fields identified in the pattern **without a match**, and declared symbol names within the print-piece of the constructor.  A named token field can't be used for both a match and as a symbol - this is where a duplicate token field definition may be required.

**Comment by ghidra1** [comment]
Since this was a clarification issue which appears to be resolved, can this ticket be closed?  If you have a specific issue/bug regarding a language module in Ghidra a new ticket should be created.

**Comment by agatti** [comment]
@ghidra1 yep, that's fine by me - maybe you may want to expand the documentation a bit to incorporate your explanation, just in case.

Thanks again for clearing this up!
