### ISSUE TITLE
Assembler with x86 program adds unexpected filler bytes

### ISSUE THREAD

**Issue by erhlee-bird** [NationalSecurityAgency/ghidra#3632]
**Describe the bug**

I invoke the `SleighAssembler` to assemble an instruction to bytes and get an incorrect result.

**To Reproduce**

Look at the test `testAssemble_JMP_0x34` in file `x86AssemblyTest.java`.
The expected bytes don't seem correct.

```
    @Test                                                                                                                                                                        
    public void testAssemble_JMP_0x34() {                                                                                                                                        
        assertOneCompatRestExact("JMP 0x34", "e9:2f:00:00:c0", "JMP 0x00000034");                                                                                                
    }   
```

**Expected behavior**

The asserted byte pattern should be `e9:2f:00:00:00` instead.
I can confirm this by running both instruction byte patterns back through the disassembler.

```
ProgramBuilder builder = ...;
builder.setBytes("0x1000", "E9 2F 00 00 C0", true);
...
builder.getProgram().getListing().getInstructions(true);

---

JMP 0xffffffffc0000034
```

```
ProgramBuilder builder = ...;
builder.setBytes("0x1000", "E9 2F 00 00 00", true);
...
builder.getProgram().getListing().getInstructions(true);

---

JMP 0x00000034
```

**Environment (please complete the following information):**
 - OS: NixOS 21.05
 - Java Version: 11.0.13
 - Ghidra Version: 10.0.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by quietust** [comment]
At what address did you assemble that instruction? I ask because the opcode it chose uses a *relative* address, so it will only produce your expected output if it was assembled at address zero.

**Comment by mumbel** [comment]
The tests use 0x40000000 I think as the base address of the instruction

**Comment by erhlee-bird** [comment]
Yeah like @mumbel said, the test itself uses a base of `public static final long DEFAULT_ADDR = 0x40000000L;` and seems to use it for this particular test type.

This is a rough sketch of what I'm doing. 

```
ProgramBuilder builder = ...;
Address base = builder.addr(0x1000);
builder.createMemory(".code", base.toString(), 0x1000);
builder.setBytes(base.toString(), bytes, true);

// Get the instructions.
builder.getProgram().getListing().getInstructions(true);
```

I am notably using a different address `0x1000` instead. However, the instruction address shouldn't matter in this case. The `e9` opcode signifies a jump with a relative _offset_. For example, if you execute `e9 fb ff ff ff` it will loop infinitely as it is jumping to itself.

**Comment by mumbel** [comment]
I looked at it a little last night, but got lost in the code.  To me it looked like maybe an answer to make the test pass, somehow it got the e9 2f 00 00 00 and at some point (which is where I got lost) it made the last byte 0xC0.

In the code browser however, unless I just got mixed up, it is correct and `e9 2f 00 00 00`, `e9 2f 00 00 c0`, ctrl+g -> "JMP 0x34" and ctrl+g -> "JMP 0xc0000034" do what you think they'd do (similar to your `ProgramBuilder builder` code).

**Comment by erhlee-bird** [comment]
Thank you for investigating. I'll dig through the Code Browser assembling code and see if it's doing something that I'm not.

But yeah, I am certain that that extra 0xC0 byte is incorrect in the test.

**Comment by erhlee-bird** [comment]
I think I get what's happening now.

```
ProgramBuilder builder = ...;
builder.setBytes("0x1000", "E9 2F 00 00 C0", true);
...
builder.getProgram().getListing().getInstructions(true);

---

JMP 0xffffffffc0000034
```

1. The assembler is interpreting "JMP 0x34" as a jump to an absolute address and calculating a relative jump from 0x40000000 to 0x34.
2. The selected instruction candidate is `E9 XX XX XX XX` which is a relative jump with a rel32 offset. There is no relative jump instruction that takes a rel64.
3. The extra bytes are being truncated to fit as a rel32.

`E9 2F 00 00 C0` ~~FF FF FF FF~~

**Comment by erhlee-bird** [comment]
Separately, I can't seem to find a syntax to specify that I want a relative offset.

nasm allows
```
jmp $ + 0x34
```

gas
```
jmp . + 0x34
```

**Comment by GhidorahRex** [comment]
> I think I get what's happening now.
> 
> ```
> ProgramBuilder builder = ...;
> builder.setBytes("0x1000", "E9 2F 00 00 C0", true);
> ...
> builder.getProgram().getListing().getInstructions(true);
> 
> ---
> 
> JMP 0xffffffffc0000034
> ```
> 
> 1. The assembler is interpreting "JMP 0x34" as a jump to an absolute address and calculating a relative jump from 0x40000000 to 0x34.
> 2. The selected instruction candidate is `E9 XX XX XX XX` which is a relative jump with a rel32 offset. There is no relative jump instruction that takes a rel64.
> 3. The extra bytes are being truncated to fit as a rel32.
> 
> `E9 2F 00 00 C0` ~FF FF FF FF~

The test is using `e9 2f 00 00 c0` as a relative offset. The `c0` makes it negative - to the absolute address `0x34`. The reason your test above failed is you were using a base address of 0x1000, in which case you probably need to try it with an instruction like `e9 2f f0 ff ff`

**Comment by erhlee-bird** [comment]
Yeah the relative offset bytes make sense now. Thank you all for chiming in and helping me get my bearings. I'll close the issue now.
