### ISSUE TITLE
MIPS EABI32 support

### ISSUE THREAD

**Issue by lacraig2** [NationalSecurityAgency/ghidra#3633]
**Is your feature request related to a problem? Please describe.**

Ghidra does not support the EABI32 ABI for MIPS.

MIPS has supported a fairly large variety of ABIs over the years [[1]](https://en.wikipedia.org/wiki/MIPS_architecture#Calling_conventions). Ghidra should not necessarily be expected to support every ABI out there. Having said that EABI stands out because it is the only MIPS ABI currently supported by GCC that Ghidra does not support. [[2]](https://sourceware.org/gdb/current/onlinedocs/gdb/MIPS.html) Additionally, the commercial disassembler has support for EABI32.

**Describe the solution you'd like**

I think that an update to the processor spec with a new ABI would solve the issue. That looks like a new cspec file (and other surrounding code). 

**Describe alternatives you've considered**
I initially wrote up an example that allowed an "__eabicall" calling convention. This isn't a good solution because it's not a calling convention, but an ABI.

**Additional context**
I set up a [repo](https://github.com/lacraig2/Ghidra_MIPS_EABI32_Example) that has source and an example binary that demonstrate the issue. It contains:
- Minimal source code that shows the ABI issue
- A makefile that works with `mips-linux-gnu-gcc` (default from ubuntu apt)
- An example binary

As another example see the below function. It should have five arguments. Instead it shows 4 and one argument "in t0", which should be the 5th argument.
<img width="509" alt="Screen Shot 2021-11-15 at 4 26 41 PM" src="https://user-images.githubusercontent.com/7518336/141856096-839495ea-6f00-4a34-a003-011a05e01493.png">

There is, unfortunately, not a lot of documentation on the EABI32 format. You can get context from either the GCC source or this one [mailing list post](https://sourceware.org/legacy-ml/binutils/2003-06/msg00436.html).

*UPDATE:* I have a PR for review.

**Comment by astrelsky** [comment]
It doesn't support n32 either. #1895

**Comment by lacraig2** [comment]
Neat. However, that bug looks a lot more involved than EABI32. Seems like that particular ABI doesn't fit the current cspec model well.

This particular feature request is a relatively easy change.
