### ISSUE TITLE
Debugger entirely broken and wiped after Restore Defaults

### ISSUE THREAD

**Issue by Smileynator** [NationalSecurityAgency/ghidra#3642]
**Describe the bug**
Pressing the restore defaults in the Options for Debugger window, cleared out all but the most basic windows, and all but the most basic buttons in the action bar. Rendering the entire tool useless.

Restoring the windows i found out is impossible, restoring ghidra meant for me to go to the .ghidra folder in my user folder, and clearing it entirely. 

**To Reproduce**
1. Open the debugger
2. Open the options (Edit > Tool Options)
3. Clear some defaults (i don't know which specifically i clicked, i assumed it meant "all")
4. Possibly restart ghidra, i don't remember if i did or not.

It might have been the result of previous messing around and crashing of the debugger entirely, followed by me messing with the option defaulting. (implying the debugger was already acting up, and me fiddling with menus causing unexpected errors, followed by corruption of the settings files or something?)

Upon reboot of ghidra, no warnings or errors were given, just the same empty menu state ( i had like all of 5 windows, and no others available to me)

**Expected behavior**
Defaults to be restored, but not the entire program becoming corrupted.

**Environment (please complete the following information):**
 - OS: Win 10
 - Java Version: 11.0.8
 - Ghidra Version: 10.0.4
 - Ghidra Origin: Official release from the github releases page.

**Comment by dragonmacher** [comment]
In case you were unable to restore your tool after this bug, you should be able to re-import your default debugger tool via the Front End from the menu `Tools -> Import Default Tools...`.

**Comment by d-millar** [comment]
Also, you may want to open Window->Debugger and hit "Show all".  Probably, will open some stuff you don't care about, but easier to get rid of that than to add back.

**Comment by Smileynator** [comment]
While i am aware of the other fixes. It was a bug report, not a help request. Thanks for adding the info for future users though.

**Comment by dragonmacher** [comment]
As it stands now, since we cannot reproduce the issue, we cannot fix it.  I will close this for now.  If you happen to find repeatable steps to reproduce the issue, then please update the ticket.

**Comment by Smileynator** [comment]
I am sure you will run into it sooner or later if you try to do anything but the hotpath, and it somehow breaks on you. But if i find a specific trick i'll be back.
