### ISSUE TITLE
AutoAnalysisManager: Cancelling analysis after timeout

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#3649]
Hello,

I am using an AutoAnalysisManager to selectively analyze part of the program. If, after _n_ seconds the analysis does not complete, I would like to cancel it. I have tried AutoAnalysisManager.cancelQueuedTasks(), but that did not seem to cut it. Any suggestions regarding this? A small snippet of the manager being instantiated can be found below;

![image](https://user-images.githubusercontent.com/22150653/142473611-081eee27-dc07-49e3-a4d5-7dc7076a7442.png)

Thanks for the help!

**Comment by dragonmacher** [comment]
You seem to be doing something a bit unusual, which means you may run into other odd issues as you proceed.  However, for your immediate question, you should be able to cancel the analysis using the task monitor that is passed to `startAnalysis()`.  You can try something like this:
```
TaskMonitor monitor = TimeoutTaskMonitor.timeoutIn(10, TimeUnit.SECONDS);
mgr.startAnalysis(monitor);
```
This task monitor is designed to cancel itself after the given timeout.

**Comment by aa-software2112** [comment]
Fantastic, I will try this and let you know how it goes; as for your concern; I am merely attempting to analyze a _large_ batch of files, and that if they take _too long_ then I simply ignore them. Thus the cancellation of the analysis task leads to ignore the file as a whole.

**Comment by aa-software2112** [comment]
Worked like a charm! Thank you
