### ISSUE TITLE
Gradle build issue within 10.1-BETA for extension

### ISSUE THREAD

**Issue by BrentHoltsclaw** [NationalSecurityAgency/ghidra#3650]
**Describe the bug**
Attempt to build plugin fails at line 199 support/buildExtension.gradle

* Where:
Script 'D:\ghidra_10.1-BETA_PUBLIC\support\buildExtension.gradle' line: 199

* What went wrong:
A problem occurred evaluating script.
> Could not set unknown property 'mainClass' for task ':indexHelp' of type org.gradle.api.tasks.JavaExec.

**To Reproduce**
Attempt to build plugin with 10.1-BETA

**Expected behavior**
Build should be successful. Previously able to build in 10.0.*

**Screenshots**
![image](https://user-images.githubusercontent.com/29214623/142533343-8ecd57f1-e0d6-418d-ad5f-ed238cb6370d.png)

**Attachments**

**Environment (please complete the following information):**
 - OS: Win10
 - Java Version: 
 - Ghidra Version: 10.1-BETA
 - Ghidra Origin: github release 

**Additional context**
Changed line 199 and 250 of support/buildExtension.gradle from mainClass to main and build was successful

**Comment by ryanmkurtz** [comment]
What version of Gradle did you use?

**Comment by BrentHoltsclaw** [comment]
Looks like version 6.1.  Looks like I should update to the latest and try again.

**Comment by XVilka** [comment]
@BrentHoltsclaw even Gradle 6.8 should work, at least it works for me. The migration to the new property names happened in Gradle 6.4: https://docs.gradle.org/current/userguide/upgrading_version_6.html#new_properties_may_shadow_variables_in_build_scripts

**Comment by astrelsky** [comment]
> What version of Gradle did you use?

Can the gradle version be checked in the imported gradle script in the support folder to produce a more obvious error message?

**Comment by ryanmkurtz** [comment]
> Can the gradle version be checked in the imported gradle script in the support folder to produce a more obvious error message?

It's already being checked, but our minimum we allow is 6.0.

> @BrentHoltsclaw even Gradle 6.8 should work, at least it works for me. The migration to the new property names happened in Gradle 6.4:

Sounds like we need to up our minimum supported Gradle version from 6.0 to 6.4.  I'll verify a new minimum version and update our check, and consider that the fix for this issue.

**Comment by ryanmkurtz** [comment]
I've confirmed 6.4 builds, so that will be our new minimum version.
