### ISSUE TITLE
printerr(): Cannot see in scriptlog

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#3657]
Hello,

I am analyzing a file using the headless analyzer, passing a scriptlog path to the -scriptlog parameter. Calls to println() make it to the log file, however calls to printerr() simply do not appear. Any ideas? Below is a screenshot of some test code, as well as the output log file

![image](https://user-images.githubusercontent.com/22150653/142730139-f43efcd9-5258-40ac-b278-0d8c8d188729.png)

**Comment by ryanmkurtz** [comment]
I am reproducing this...we'll take a look.

**Comment by ryanmkurtz** [comment]
Looks like print() is also not being logged correctly.  It's an easy fix.

**Comment by aa-software2112** [comment]
Thanks for taking care of this!
