### ISSUE TITLE
Decompile is missing for Ghidra 

### ISSUE THREAD

**Issue by vardhan-saniko** [NationalSecurityAgency/ghidra#3663]
I am using mac lastest intel version.

I followed the steps as per installation guide. 

I don't find decompile file in ./Ghidra/Features/Decompiler/os/mac_x86_64/

I found decompile missing error while reverse engineering.

I checked this https://github.com/NationalSecurityAgency/ghidra/issues/1495, but it didn't resolve.

I am using jdk 11, 64 bit OS, X86 architecture

<img width="798" alt="Screen Shot 2021-11-21 at 7 02 44 PM" src="https://user-images.githubusercontent.com/90535201/142790951-2f3f161a-b9a5-4a4a-862b-1fd51b69c4cb.png">
<img width="518" alt="Screen Shot 2021-11-21 at 7 05 05 PM" src="https://user-images.githubusercontent.com/90535201/142790957-eb59fa06-74c9-4292-aa7b-0ed7471968a4.png">
<img width="1050" alt="Screen Shot 2021-11-21 at 7 08 10 PM" src="https://user-images.githubusercontent.com/90535201/142790958-b11f649d-cc2d-4530-80d0-1d35306e0871.png">

I have added 
export PATH=/Users/vishnuvardhan/Desktop/Ghidra/jdk-11.0.13+8/Contents/Home/bin:$PATH in ~/.zshrc

**Comment by GawdOfROFL** [comment]
This isnt IDA btw, you wont end up directly on the main function, to get the decompilation go to the main function manually

**Comment by vardhan-saniko** [comment]
I tried that, it is showing decompiler isn't there. 

<img width="796" alt="Screen Shot 2021-11-22 at 12 57 43 AM" src="https://user-images.githubusercontent.com/90535201/142824302-3bf2ecce-86e0-487d-9c2d-185f09f3de80.png">
<img width="1363" alt="Screen Shot 2021-11-22 at 12 58 11 AM" src="https://user-images.githubusercontent.com/90535201/142824310-c976786e-5ec3-4b50-92c7-3d48e2b60134.png">

**Comment by ryanmkurtz** [comment]
Duplicate of #3477.  macOS Gatekeeper is blocking Ghidra's native binaries from running.  Did you click "Move to Trash" or "Cancel"?  You will likely have to allow it to run as shown here: https://github.com/NationalSecurityAgency/ghidra/issues/1559#issuecomment-895972722

In 10.1 you can also run `support/buildNatives` to produces your own native binaries that Gatekeeper will not complain about.  Instructions for that can be found in the [Installation Guide](https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.1-BETA_build/GhidraDocs/InstallationGuide.html#Build).

**Comment by vardhan-saniko** [comment]
I clicked Cancel and allowed it from security and privacy, but still couldn't fix the issue 

But producing own native binaries as you mentioned resolved the issue. 

Thanks @ryanmkurtz
