### ISSUE TITLE
x86 application debugging, operator_new(0x10)/Malloc returns impossible address at runtime (elaboration of #3641)

### ISSUE THREAD

**Issue by Smileynator** [NationalSecurityAgency/ghidra#3667]
Like the title says, i am debugging a x86 application. At some point during initialization, it allocates, what i am confident are strings into some structs, those structs consist of 16 bytes and is mapped like:
```
0x0 vtable
0x4 data Pointer?
0x8 stringLength
0xc allocatedLength
```

Methods to initialize it use operator_new() to allocate storage for it. The size of it is stored in 0xc, the actual allocation pointed is stored in 0x4.
Later methods then try and write a char* to that 0x4, but if allocatedLength is not sufficient, it will first resize.
Once it's put there, 0x8 is updated with the actual char[] length

Now the problem is, all of this i can see perfectly fine, i even know what the string is that is being put in there. But the pointer in 0x4, points to an address, that i can't follow. Where normal program business is in the 0x00400000 and up region, some is at 0x010e8000 and up. But this thing seems to allocate at 0x02ffbff0 which is not known to the memory map, and while my static listing can go there, the dynamic listing says no.

I tried adding this region roughly, to the memory map, either with a new region, or by expanding the last block in there, to a point to include this memory. However this seems to make no difference.

All subsequent uses of this pointer, seem to directly talk to the data behind it, or overwrite the pointer entirely. It's not an offset, no math is done upon it to convert it to a legitimate pointer. So there should be nothing weird going on there.

Looking into the operator_new() it should just be allocating memory on the heap.

Am i missing something here?
Do i need to manually tell it that this is part of memory we need somehow?
Can i simply not get to this memory for any reason?
Is this because i am debugging on a x64 device for a x86 program?
Is there any other reason that heap memory is unobservable in this manner?

![image](https://user-images.githubusercontent.com/3433068/142936541-6b0c189d-6df6-491c-997c-f3f95578b422.png)
![image](https://user-images.githubusercontent.com/3433068/142936611-3ead1511-3c9a-44bd-9b1f-b24469d72e58.png)
![image](https://user-images.githubusercontent.com/3433068/142936863-bc5b4055-6132-4d0c-9815-09370800aa50.png)
Altered this last one, original region was MUCH smaller.

**Comment by d-millar** [comment]
So, just to be clear, editing the memory map of your program will have no effect whatsoever on the debugger.  That's purely a means of describing the static program and organizing your reverse engineering work.  

That said, if I understand you correctly, you're typing go (G) in the Dynamic listing, entering a value that you believe makes sense (i.e. you've gotten it from a register or the Dynamic memory values), and the Dynamic listing is not moving to that address - is that correct?

**Comment by nsadeveloper789** [comment]
Check the "Regions" window, which is the same concept as the "Memory Map," but for the Debugger. I don't think you can edit it, though. You might refresh the "Memory" node of your process in the "Objects" window to see if that loads the heap region.
I forget the command off the top of my head (either `!memory` or `!address`) you can type into the "Interpreter" window to verify that dbgeng knows about the heap, too. If the heap region doesn't show there, Ghidra won't know about it either.

**Comment by Smileynator** [comment]
@d-millar Correct, even though i usually just double click the address instead of using G, but the result is the same. I get a "Console?" message in ghidra (not actual console, just the status bar i guess?) that says "Address not found in program memory 0x########" with the address at the end there.
I am pretty confident they are heap allocations so, it would make sense that they exist.

@nsadeveloper789 As for what i could gather from your information. Both commands do.. little. I assume something broke for me. 
![image](https://user-images.githubusercontent.com/3433068/143093712-c5910d76-67eb-42dc-81ff-5bedb68c8d60.png)
So i am guessing that it has nothing to tell me at this moment as a result.

The regions window i can not find. If it is a window on itself. Though here is what i have gathered in the Objects window about memory. And as far as i can tell, the address i am currently after (0x0177c018 for example) does not appear to be anywhere near these ranges.
![image](https://user-images.githubusercontent.com/3433068/143094034-06277200-21b7-45b4-aaf6-6198bec84247.png)
The closest one i see if the very last region defined. Mostly because all other regions are either 6 digits long, and the others are all in the 12 digits long 0x7F---- range.
That last region is too small for it to contain the relevant pointer though.
![image](https://user-images.githubusercontent.com/3433068/143094363-5e040532-5e9f-4475-a817-02b1a18c3d05.png)


And finally, this is the only session and the only process. So i assume there is nothing missing to the information i just passed to you.
I should also probably sort out that static region i reallocated way too hugely. That is apparently stuck there now. But it doesn't seem to affect debugging like you both claimed it wouldn't. My bad on that one.

Thanks for the help so far!

**Comment by nsadeveloper789** [comment]
The regions window should be docked in the lower left with the Stack, Watches, etc. If it's no there, try Window->Debugger->Regions. Also, glad you found the regions under the "Objects" window. with "Memory" selected, click that Refresh button (rightmost in the pane's toolbar).

**Comment by Smileynator** [comment]
@nsadeveloper789 I totally missed that, so sorry! it's because it was the only thing that goes deeper than 1 layer.
Pretty much the same info in here though.
![image](https://user-images.githubusercontent.com/3433068/143130537-f41ae45b-97f7-4a1d-a4d3-6a7567712dcd.png)

**Comment by Smileynator** [comment]
So is there anything i can do to help ghidra understand what is going on? Or is there something i am doing wrong that causes it to not understand the heap?

**Comment by Smileynator** [comment]
@nsadeveloper789 @d-millar
I managed to get the commands working, by going off the "JDK not loading the right DLL things" off of other issues (dear lord what a dive into madness that is, and the workaround is less than ideal!)

!address does in fact seem to recognize the heap as heap, and knows of the memory address. But the issue remains much the same. It cannot access it nor does regions window show this in any way.
![image](https://user-images.githubusercontent.com/3433068/143504369-119f5cbd-8e8a-4978-8d63-5525a2872376.png)


Any ideas?

**Comment by Smileynator** [comment]
Official "bug" reported at #3676 and will close this question as to not confuse/clog the ticket system.
