### ISSUE TITLE
Ghidra raises its windows when focus-follows-mouse is enabled

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#367]
**Describe the bug**
This issue applies on Windows when the user has enabled focus-follows-mouse without window raising. With that setting, as you move the mouse pointer, the window under the pointer is activated but not raised. (You need to click to raise the window.)

When a Ghidra window is activated automatically as the user moves the mouse pointer over it, it seems Ghidra raises the newly-active window, obscuring any other Ghidra windows. It should not do that.

When Ghidra raises the newly-active window, it moves to the front of other Ghidra windows, but not in front of other programs that might be running. For example, if you have several Ghidra windows open plus Notepad, with Notepad on top, the Notepad window remains on top as you move the mouse over different Ghidra windows.

**To Reproduce**
1. Enable focus-follows-mouse without window raising. You can do that using [Winaero Tweaker](https://winaero.com/comment.php?comment.news.1836) or [X-Mouse Controls](https://joelpurra.com/projects/X-Mouse_Controls/). Run Winaero Tweaker and under XMouse Options, select _Enable window tracking_ and make sure _Enable window raising_ is not selected
2. Run Ghidra and ensure several windows are open. For example, open a project and open Help, then adjust the windows' size & position so the project selection window and the help window are in front of the larger CodeBrowser window.
3. Move the mouse around. Notice that as you move the mouse over the CodeBrowser window (which is beneath the other two windows) Ghidra raises it to cover the other two windows.

**Expected behavior**
Ghidra should not programmatically raise its windows when they become active. (Windows will raise them when the user clicks.)

**Environment (please complete the following information):**
 - OS: Windows 10 1803 x86-64
 - Java Version: 11.0.2
 - Ghidra Version: 9.0.2

**Additional context**
Visual Studio has had a very similar problem for over 10 years now. For a VS bug report with explanation of how to enable the focus-follows-mouse feature [see here](https://developercommunity.visualstudio.com/content/problem/21792/main-window-brings-itself-to-the-front-if-user-has-1.html).

**Comment by shoaniki** [comment]
This is unfortunately nothing to do with Ghidra.  It's a longstanding issue with the underlying Java platform.  All Swing apps have behaved this way since Java 7 -- for example, you'll see exactly the same thing happen if you open the AVD manager in Android Studio and then mouse over the main IDE window behind it.

I am not aware of any way to change this behavior, since it happens at a lower level than any application code, so there probably isn't anything the Ghidra team can do; you'd have to take this up with Oracle.

**Comment by aamcintosh** [comment]
This does not happen with Compiz/Ubuntu 16.04

**Comment by ryanmkurtz** [comment]
Closing due to it being an issue with Java, not Ghidra.

**Comment by drazisil** [comment]
@ryanmkurtz , I'm sorry to necro this issue, but https://stackoverflow.com/questions/18452446/how-to-prevent-a-java-graphical-program-from-stealing-focus-when-updating-the-wi seems to indicate that replacing `setVisible()` with `repaint()` might help. I was not able to tell from searching this was already coded this way, so I thought I would suggest it.
