### ISSUE TITLE
PIC Language: Incorrect P-Code Translation for swap Instruction

### ISSUE THREAD

**Issue by NicolaasWeideman** [NationalSecurityAgency/ghidra#3670]
**Describe the bug**
Ghidra translates the `swap` instruction of the PIC assembly language to P-Code equivalent to:
`x = ((x & 0xff) << 8) & ((x & 0xff00) >> 8);`

The instruction `swap Wn` should swap the two bytes of the register `Wn` (see the [manual](http://ww1.microchip.com/downloads/en/devicedoc/39905e.pdf), p262).
Therefore, this translation is incorrect.

**Expected behavior**
The translation should be equivalent to:
`x = ((x & 0xff) << 8) | ((x & 0xff00) >> 8);`

**Screenshots**
Below is a screenshot of the incorrect translation.
Note the three `INT_AND` instructions, the third being incorrect.
![pic_swap_incorrect_pcode](https://user-images.githubusercontent.com/2248306/143186950-0f281296-9c0a-4a9e-bb2e-a396b4532af2.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3
 - Java Version: 11.0.11
 - Ghidra Version: 10.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by ghidra1** [comment]
Fix will be made to 10.1 release

**Comment by ghidra1** [comment]
Sorry - I did not notice your pull-request until after I had applied the fix.
