### ISSUE TITLE
Can't automatically Map x86 application during start of debugging (elaboration of #3641)

### ISSUE THREAD

**Issue by Smileynator** [NationalSecurityAgency/ghidra#3675]
**Describe the bug**
When i start my x86 application named myprogram.exe I always have to manually go to modules, and either map it manually or press the "Map current" button there.

**To Reproduce**
1. Start debugger on x86 application
2. Notice no breakpoints can be "effective"
3. Manually map
4. Issue resolved

**Expected behavior**
Automatically map like the plugin bot for it intents to do.

**Environment (please complete the following information):**
 - OS: Win 10 latest patches
 - Java Version: 11.0.8
 - Ghidra Version: 10.0.4 & 10.1_BETA
 - Ghidra Origin: Github release page zip file

**Additional context**
Settings are correct, auto connect bot is enabled.
My application name does not match the module name.
Module name always starts as "image00000000'00400000" while that is not the name of the exe or project.
the auto resolve button in modules does work fine.
Using IN-VM dbgeng or dbgmodel, both produce the same results.

**Comment by d-millar** [comment]
Ticket already in for this. As noted before, the "easy" (albeit annoying) solution for now is to rename your imported program "image00000000'00400000".
