### ISSUE TITLE
Add the naming of Breakpoints to the Debugger

### ISSUE THREAD

**Issue by Smileynator** [NationalSecurityAgency/ghidra#3679]
**Is your feature request related to a problem? Please describe.**
I have a list of breakpoints that are important to me for certain bits of the program i am working on. But besides address, no tangible way to tell them apart. Which to activate, which to disable?

**Describe the solution you'd like**
Where we now see the "Image" column, i would like a custom name. Default name could be "ImageName-0x004023aa", but the "set breakpoint" window should probably allow you to set it immediately when creating. Persistence between sessions is also key to this request.

**Describe alternatives you've considered**
There are comments, but only for already "active" breakpoints in the lower part of the breakpoint window. I am not even sure if those comments persist between sessions.

**Additional context**
It would really help keeping my thoughts organized, instead of having to find out which breakpoint is which by trial and error. or by visiting all the addresses until i recognize one (often switching between breakpoint and decompiler to recognize the code, making it worse)

![image](https://user-images.githubusercontent.com/3433068/143634461-54117a8e-f46e-4a5e-a486-9678830e9cb7.png)

**Comment by nsadeveloper789** [comment]
Closed by https://github.com/NationalSecurityAgency/ghidra/commit/b4d038fe3066a18fb453fd4179e7b63ce33fc310
