### ISSUE TITLE
Auto analysis : Stack runs for several hours without terminating

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#3683]
**Describe the bug**
Autoanalysis takes several hours on the attached Windows binary at FallbackTelemetryCallback when trying to analyze the stack without success. When done from the UI, it cannot be cancelled without killing/forcibly exiting Ghidra.

**Environment (please complete the following information):**
openjdk 11
ubuntu 2004
ghidra master (42c6a66)

[stack.zip](https://github.com/NationalSecurityAgency/ghidra/files/7615282/stack.zip)

**Comment by emteere** [comment]
I see the issue.  Will fix for 10.1 release.
