### ISSUE TITLE
Calculate Hash of Basic Blocks

### ISSUE THREAD

**Issue by dinedag** [NationalSecurityAgency/ghidra#3684]
Having an issue with calculating a hash for each basic block in a given function. I've got a function to get all of the basic blocks in a given function address range, and another function to print the disassembly of each of the basic blocks. I'm now trying to get a hash of each basic block using HashStore.

For reference, my reason for using this function is to hash a set of basic blocks for a particular function in two different binary files and then eliminate blocks which have no changes, I believe that HashStore is designed to do exactly this, based on the description...

```Python
from ghidra.program.model.correlate import HashStore
from ghidra.program.model.correlate import HashCalculator

def blockDisasm(bb):
	listing = currentProgram.getListing()
	ins_iter = listing.getInstructions(bb, True)

	while ins_iter.hasNext():
		ins = ins_iter.next()
		hashCalc = HashCalculator.calcHash(1337, ins)
		print("{} {}".format(ins.getAddressString(False, True), ins))
		return hashCalc

def getBasicBlocks(funcManager):
    [...]

    hashStore = HashStore(func, monitor)
    [...]
    while(blocks.hasNext()):
	bb = blocks.next()
	hashCalc = blockDisasm(bb)
	dest = bb.getDestinations(monitor)
	while(dest.hasNext()):
		dbb = dest.next()
		if not getFunctionAt(dbb.getDestinationAddress()):
			counter = counter + 1
			print("\t[*] Count: {} Block: {}".format(counter, dbb))

	print("[*] Total Blocks: {}".format(counter))
	hashes = hashStore.calcHashes(0, 0, True, True, hashCalc)
	print(hashes)
```

However, I am getting this error...

```
    hashCalc = HashCalculator.calcHash(1337, ins)
TypeError: calcHash(): expected 3 args; got 2
```

Which suggests something isn't instantiated...? But it should work as far as I can see... Admittedly, Java would probably work better for this.

**Comment by dev747368** [comment]
HashCalculator is an interface that a class would implement, and the method you are trying to call would be valid on an instance of one of those classes... ie. a MnemonicHashCalculator or AllBytesHashCalculator.  Instead you are calling calcHash() it as if it were a static method, which it is not.

Other than that general java advice, I'm out of my depth with func diff stuff.
