### ISSUE TITLE
Function Prototypes and Override Signature

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3694]
**Describe the bug**
If I create a function prototype containing sized pointers (like `CDC *32`) when I edit that again the `32` (size) is lost somewhere.  The consequence of this during an attempt to use the `Override Signature` option is that the process fails with the following error (in the eclipse console log):
`ERROR Override Signature Failed: Error overriding signature: ghidra.util.exception.InvalidInputException: Unable to create datatype associated with symbol   (OverridePrototypeAction.java:270)`

This is due to the method `buildHashedDataType` of class `DataTypeSymbol` retrieving a preexisting type to compare.  But, despite stepping through the processes of creating/modifying the original prototype and the override process, the whereabouts of the size loss alludes me.  HELP...

**Expected behavior**
Use the override.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version:  11.0.2 / 16.0.1
 - Ghidra Version: 10.2 - DEV (commit https://github.com/NationalSecurityAgency/ghidra/commit/42c6a667c9924e6d8485d296099ddcac338ffcba)
 - Ghidra Origin: locally built

**Comment by Wall-AF** [comment]
FYI, I'm trying to RE a suite of Windows 3.1x applications compiled using the Windows NE format.  It uses some 16-bit pointers (converted to _the equivalent of_ 32-bit ones by adding an appropriate segment register).  By this conversion process, I'm wondering if the cspec file I used originally to import the suite is correct as it was the `x86-16.cspec` that defines pointers as 2 bytes.  Any ideas?

I'm experiencing lots of annoying issues due to having 2 pointer sizes.  For instance, most of the functions I'm disassembling use pointers to objects on the stack, and these pointers use the full 32-bit address.  This means I'm having to override the size (like `CDC *32`) to get the decompilation to use the correct parameters in the function bodies, all okay so far.  However, upon dereferencing I’m getting calculations instead of member references and arrays are even worse!

**Comment by ghidra1** [comment]
Can you share the code where you are creating the pointers and function definition.

**Comment by ghidra1** [comment]
The error you cited `Unable to create datatype associated with symbol` only occurs in one place and is caused by the method `DataTypeSymbol.buildHashedDataType`.  Are you able to debug this and convey to us the condition which is causing this method to return null?  Please provide a printed stack trace if a caught  exception occurs within this method.  Thanks.

**Comment by Wall-AF** [comment]
> Can you share the code where you are creating the pointers and function definition.

Here's the output from `Debug Function Decompilation` that I've been faffing with today.
[CWndGrid__Display.zip](https://github.com/NationalSecurityAgency/ghidra/files/7642709/CWndGrid__Display.zip)

Why don't the virtual function calls (denoted by vars `pfn...`) automatically populate their parameters?

**Comment by Wall-AF** [comment]
> The error you cited `Unable to create datatype associated with symbol` only occurs in one place and is caused by the method `DataTypeSymbol.buildHashedDataType`. Are you able to debug this and convey to us the condition which is causing this method to return null? Please provide a printed stack trace if a caught exception occurs within this method. Thanks.

The `DataType` returned from `CategoryDB.getDataType(...)` contains a different calling convention which causes the `FunctionDefinitionDB.isEquivalentSignature(...)` to fail.

No stack trace is produced.

**Comment by Wall-AF** [comment]
Got the reason.

The calling convention of the prototype Ghidra generated in category `auto_proto` wasn't updated when I corrected it in my category!

What's the correct way to fix that?

**Comment by Wall-AF** [comment]
Now there's a weird issue!  With all the _overrides_ in place, the Decompiled View is using incorrect variables as parameters to those virtual calls even though the Listing View is showing the correct ones!  Any ideas here???
![image](https://user-images.githubusercontent.com/67698927/144464404-556fb4c6-9318-47f8-979a-2df6f9d75053.png)

**Comment by ghidra1** [comment]
I will have to defer to @caheckman for these decompiler specifics.

**Comment by Wall-AF** [comment]
> Got the reason.
> 
> The calling convention of the prototype Ghidra generated in category `auto_proto` wasn't updated when I corrected it in my category!

That is not alone.

It seems that because my pointers have to add a size, that isn't being taken into consideration when generating the prototype string in the `generateHash(...)` call.  (That process is delegated indirectly to the method `getPrototypeString(boolean includeCallingConvention)` of class `FunctionDefinitionDataType` (an implementation of `FunctionSignature` interface).  Changing that method to use `getName()` instead of `getDisplayName()` for the `returnType` and parameter datatypes helped!  Should all implementations of interface `FunctionSignature` be modified or will that break something elswhere???)

**Comment by Wall-AF** [comment]
> > Got the reason.
> > The calling convention of the prototype Ghidra generated in category `auto_proto` wasn't updated when I corrected it in my category!
> 
> That is not alone.
> 
> It seems that because my pointers have to add a size, that isn't being taken into consideration when generating the prototype string in the `generateHash(...)` call. (That process is delegated indirectly to the method `getPrototypeString(boolean includeCallingConvention)` of class `FunctionDefinitionDataType` (an implementation of `FunctionSignature` interface). Changing that method to use `getName()` instead of `getDisplayName()` for the `returnType` and parameter datatypes helped! Should all implementations of interface `FunctionSignature` be modified or will that break something elswhere???)

@caheckman any thoughts on this?
