### ISSUE TITLE
Include SuperH4 support

### ISSUE THREAD

**Issue by davicr** [NationalSecurityAgency/ghidra#37]
**Is your feature request related to a problem? Please describe.**
Support for the SH-4 is mentioned in the documentation @ Assembler as having Platinum quality, but I can't seem to find any way to import SuperH4 binaries.

**Describe the solution you'd like**
Support for SuperH4:BE:32:default and SuperH4:LE:32:default included in Ghidra

**Comment by nihilus** [comment]
It can easily be added be yourself or someone who knows the ISA, unfortunately I'vent played around with SuperH since 2006 and even back then I didn't know much about it.

But you can look at how another RISC architecture is implemented and go from there. Personally I'd suggest using PPC as the basis.

**Comment by LemonHaze420** [comment]
Any news on this? Clearly there is some support for SH-4 considering that it is listed as 'platinum' quality. This could be really useful for me.

**Comment by emteere** [comment]
Planned for release in 9.1.

**Comment by mumbel** [comment]
Just to clarify, the current PR is SH-1, SH-2, SH-2A, and SH-2E as is.  The goal is likely to get the core SuperH in and then additional PRs for SH-3/SH-4/SH-4A/DSP/etc... or was that getting added on your side?

**Comment by emteere** [comment]
It will be added into the ghidra repo in the next week or so.  After that, there may need to be a merging of the two.  The SH4 wasn't ready to me merged at the time of initial release.  I hadn't realized there was as much overlap in the SH1/2/3/4 encoding and instructions until a cursory review of the sh1/2.

**Comment by paketto** [comment]
> Planned for release in 9.1.

Do you have any idea when 9.1 will be out?

Thanks!

**Comment by emteere** [comment]
A 9.1 beta build is planned soon.  Most features have been merged into main.  The SH4 will be merged in within the next few days.

**Comment by brainstorm** [comment]
I guess you are referring to PR https://github.com/NationalSecurityAgency/ghidra/issues/37, @emteere (doesn't seem to include SH4 refs though)? Or are there any other (internal?) branches to be aware of? I also happen to be very interested on SH4 right now.

**Comment by ArcadeHustle** [comment]
Will you folks push a compiled release out with this support enabled? https://ghidra-sre.org is still back on 9.0.4

**Comment by brainstorm** [comment]
@ArcadeHustle Just compile it yourself with this: https://github.com/dukebarman/ghidra-builder

**Comment by ArcadeHustle** [comment]
Thanks!
