### ISSUE TITLE
Invalid PCode generation for PMULUDQ

### ISSUE THREAD

**Issue by Satsuoni** [NationalSecurityAgency/ghidra#3716]
**Describe the bug**

Ghidra disassembly for command PMULUDQ  (XmmReg, m128) produces Pcode that reads the same 4 bytes of memory twice instead of distinct 4 bytes in 16-byte memory.
```
66 0f f4 95 20 dd  ff ff   PMULUDQ    XMM2,xmmword ptr [RBP + local_22e8]
              $U3200:8 = INT_ADD RBP, 0xffffffffffffdd20:8
              $Ua4d00:8 = INT_ZEXT XMM2_Da
              $U5300:4 = LOAD ram($U3200:8)
              $Ua4e00:8 = INT_ZEXT $U5300:4
               XMM2_Qa = INT_MULT $Ua4d00:8, $Ua4e00:8
               $Ua4f80:8 = INT_ZEXT XMM2_Dc
               $U5308:4 = LOAD ram($U3200:8)
               $Ua5080:8 = INT_ZEXT $U5308:4
               XMM2_Qb = INT_MULT $Ua4f80:8, $Ua5080:8
```
This results in invalid emulation, at the very least.

**To Reproduce**

Disassemble `66 0f f4 95 20 dd `

**Expected behavior**

Resulting pcode should properly access  memory at offset. 

**Environment (please complete the following information):**
 - OS:  Windows 7
 - Java Version: java 17 2021-09-14 LTS
 - Ghidra Version: 10.0.4
 - Ghidra Origin: official distro

**Additional context**

Of note is that the ia.sinc file is correct:
```
:PMULUDQ        XmmReg, m128     is vexMode=0 &  $(PRE_66) & byte=0x0F; byte=0xF4; XmmReg ... & m128
{
    local a:8 = zext(XmmReg[0,32]);
    local b:8 = zext(m128[0,32]);
    XmmReg[0,64]  = a * b;
    local c:8 = zext(XmmReg[64,32]);
    local d:8 = zext(m128[64,32]);
    XmmReg[64,64] = c * d;
} 
```

**Comment by mumbel** [comment]
There appears to be a generic issue with getting sub-pieces there.  It looks like a lot of the access to sub-pieces of m128 (not starting at 0) set `local m:16 = m128` first and work off that otherwise it fails to add any SUBPIECE pcode ops.  Instructions like PUNPCKHQDQ and PMINUW, to name a few, appear to suffer as well.

verified against 9.2 (when this PMULUDQ got added) and master bed44bd55dc88c7c6fab5f158cdb4b9daa087519

**Comment by mumbel** [comment]
@ryanmkurtz   I might even label this as a sleigh compiler bug, I looked through it pretty well from a slaspec POV and it made no sense.
