### ISSUE TITLE
Defining structure which has member pointing to same struct type

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#3721]
This issue is to report a couple of quirks related to manually defining structures.

Suppose you are entering/defining a structure, a member of which is a pointer to a structure of the same type. Here's a real-world example:
```
struct SCSIHdr {
  struct SCSIHdr *    qLink;                  /* (internal use, must be nil on entry)   */
  short               scsiReserved1;          /* ->     reserved for input          */
  UInt16              scsiPBLength;           /* -> Length of the entire PB        */
  UInt8               scsiFunctionCode;       /* -> function selector           */
  UInt8               scsiReserved2;          /* <-     reserved for output          */
  volatile OSErr      scsiResult;             /* <- Returned result               */
  DeviceIdent         scsiDevice;             /* -> Device Identifier (bus+target+lun)*/
  SCSICallbackUPP     scsiCompletion;         /* -> Callback on completion function     */
  UInt32              scsiFlags;              /* -> assorted flags            */
  BytePtr             scsiDriverStorage;      /* <> Ptr for driver private use   */
  Ptr                 scsiXPTprivate;         /* private field for use in XPT      */
  long                scsiReserved3;          /* reserved                    */
};
```

The first quirk is that you can't define a member as being a pointer to the same type of structure when you initially create it. But you can edit it later.

- In Data Type Manager, right click, New->Structure...
- Type the structure name in the Name: field, e.g. `teststruct`
- Defining the first member, enter `teststruct *` under DataType. An error message "Unrecognized data type of "teststruct" appears at bottom of window.
- To work around that, instead set the type of first member to `void * member1`.
- Then define a second member, e.g. `short dummy`
- Click the save icon then close the Structure Editor window.

If you edit the structure you just defined, you can change the type of the first member to `teststruct *`. However a second quirk happens when you do that:
- Edit the structure you just created. It has two members: `void * member1` and `short dummy`.
- Add another member, e.g. `dword test2`. You can add some more members too if you want.
- Change the type of the first member from `void *` to `teststruct *`
- When you do that, the extra member(s) you just defined (`dword test2` etc.) disappear from the list!

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.12
 - Ghidra Version: 10.1-BETA

**Comment by mumbel** [comment]
The first seems entirely expected behavior to me, you haven't saved it so it doesn't exist yet; therefore, you can't use it.  Save after creating the struct and you can immediately use `teststruct *` (you can save a 0 byte struct).  The 2nd one I've run into as well maybe, it sounds similar or at least related  (https://github.com/NationalSecurityAgency/ghidra/issues/2345)

**Comment by ghidra1** [comment]
@mumbel is correct for the first issue you mentioned - you must perform an initial save of the structure before you can refer to it as a pointer within the structure.  The second issue I was able to reproduce and does  appear to be a bug where new components get wiped-out in editor when setting a self-referencing pointer above the the new component.
