### ISSUE TITLE
Address calculation with indexed addressing modes on Hitachi HD6305Y2

### ISSUE THREAD

**Issue by paolosig** [NationalSecurityAgency/ghidra#3725]
I've added support for the Hitachi HD6305Y2 processor on Ghidra. My problem is that I cannot figure out how to make the "indexed with 8-bit offset" addressing mode work.
The basic idea is that an instruction supporting said addressing mode has an 8-bit argument (let's call it imm8) and the target address is calculated as imm8 + the value contained in the register X (also 8-bit); it's basically like the Zero Page Indexed mode on the 6502 but with the ability to address memory up to 0xFF+0xFF=0x1FE.
This is the relevant part of my slaspec file:
```
define endian=big;
define alignment=1;

define space mem type=ram_space size=2 default;
define space register type=register_space size=1;

define register offset=0     size=1 [A X CCR];
define register offset=0x18  size=2 [PC _ SP _];
define register offset=0x18  size=1 [PCH PCL SPH SPL];

@define C "CCR[0,1]"
@define Z "CCR[1,1]"
@define N "CCR[2,1]"
@define I "CCR[3,1]"
@define H "CCR[4,1]"

define token opcode (8)
	op = (0,7)
	hi = (4,7)
	lo = (0,3)
	bit = (1,3)
	first = (7,7)
	last = (0,0) 
	rmw = (6,7)
;
define token data8 (8)
	imm8 = (0,7)
	rel8 = (0,7) signed
;
define token data16 (16)
	imm16 = (0, 15)
;

macro pushINT() {
	*:1 (SP) = PCL;
	SP = SP-1;
	local tmp:1 = PCH;
	tmp[7,1] = 1;
	tmp[6,1] = 1;
	*:1 (SP) = tmp;
	SP = SP-1;
	*:1 (SP) = X;
	SP = SP-1;
	*:1 (SP) = A;
	SP = SP-1;
	tmp = CCR;
	tmp[7,1] = 1;
	tmp[6,1] = 1;
	tmp[5,1] = 1;
	*:1 (SP) = tmp;
	SP = SP-1;
}
macro pushSUB() {
	*:1 (SP) = PCL;
	SP = SP-1;
	local tmp:1 = PCH;
	tmp[7,1] = 1;
	tmp[6,1] = 1;
	*:1 (SP) = tmp;
	SP = SP-1;
}
macro popINT() {
	SP = SP+1;
	local tmp = *:1 SP;	
 	CCR = tmp[0, 4];
	SP = SP+1;
	A = *:1 SP;
	SP = SP+1;
	X = *:1 SP;
}
macro popSUB() {
}
macro NZflags(value) {
	$(Z) = (value == 0);
	$(N) = (value s< 0);
}

######### OPERANDS #########
# Branch instructions #

#Relative
REL: reloc is rel8 [reloc = inst_next+rel8;] {export *:2 reloc;}

# Register/memory #

#Immediate
OP1: "#"imm8	is hi=0xA; imm8		{tmp:1 = imm8; export tmp;}
#Direct ("zero page")
OP1: imm8	is hi=0xB; imm8		{export *:1 imm8;}
#Extended
OP1: imm16	is hi=0xC; imm16	{export *:1 imm16;}
#Indexed (16 bit offset)
OP1: imm16,X	is hi=0xD & X; imm16	{tmp:2 = imm16+zext(X); export *:1 tmp;}
#Indexed (8 bit offset)
OP1: imm8,X	is hi=0xE & X; imm8	{tmp:2 = zext(imm8+X); export *:1 tmp;}
#Indexed (No offset)
OP1: 0,X	is hi=0xF & X		{export *:1 X;}

# Read/modify/write #

#Implied (A)
OP2: A		is hi=0x4 & A		{export A;}
#Implied (X)
OP2: X		is hi=0x5 & X		{export X;}
#Direct
OP2: imm8	is hi=0x3; imm8		{export *:1 imm8;}
#Indexed (No offset)
OP2: 0,X	is hi=0x7 & X		{export *:1 X;}
#Indexed (8 bit offset)
OP2: imm8, X	is hi=0x6 &X; imm8	{tmp:2 = zext(imm8+X); export *:1 tmp;}

# Bit manipulation #

ADDR8: imm8	is imm8			{export *:1 imm8;}
```
if I write this way, the sleigh compiler reports no errors, but the final address is computed ignoring the carry, so the addresses after 0xFF wrap around like they would do on the 6502.
If instead i write it like this:
`OP2: imm8, X is hi=0x6&X; imm8 {tmp:2 = zext(imm8) + zext(X); export *:1 tmp;}`
the Sleigh compiler complains about not being able to determine the size. How can I fix it?
Thanks in advance

**Comment by agatti** [comment]
@paolosig from what I recall you should probably write that as `{ local tmp:2 = imm8 + zext(X); export *:1 tmp; }`.  That's how it's done in other processor definitions, by the way.  Could it be that the compiler is trying to sort out the final size of the addition result before taking the operation's target size?

**Comment by paolosig** [comment]
It works! I thought I had tried it before without success but apparently i was wrong; maybe I was using an old version of the compiler. Anyway, now it works, so thank you.

**Comment by paolosig** [comment]
Edit: spoke too soon; there's still a problem. Take for example this instruction:
`0xE7FF` with X=0x40
which gets interpreted as "STA 0xFF, X => DAT_003F"; "STA 0xFF, X" is correct, but 0xFF+0x40=0x13F and not 0x3F

**Comment by agatti** [comment]
@paolosig How about `{ local tmp:4 = imm8:4 + zext(X); local narrow:2 = tmp:2; export *:1 narrow; }` ?  (And by the way, check out the discussions section of this repository, maybe questions like these should be posted there instead :))

**Comment by paolosig** [comment]
I tried that, no change, then I reverted back to the previous solution and tried re-importing the file and it just worked. Calling ReloadSleighLanguage on the old binary file didn't have any effect for some reason. Still, now it's fixed. Also, next time I'll post on discussions, I thought I could post it here since I was having an issue with Sleigh AND there's a "question" option...
