### ISSUE TITLE
M68000: Recognize add.w reg, reg

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#373]
![изображение](https://user-images.githubusercontent.com/7189309/55687815-fa7e3200-5979-11e9-8712-b8a998c5ed23.png)

There is the function FUN_00013798 that changes register D4w. Then Motorola adds register to itself to multiply it by two. But decompiler recognizes that trick as:

![изображение](https://user-images.githubusercontent.com/7189309/55687823-2c8f9400-597a-11e9-9eb7-68e25babf27c.png)

Strange things.

**Comment by jrmuizel** [comment]
It's not clear what you think is going wrong here. Can you post some more context and what you think the decompilation should be?

**Comment by lab313ru** [comment]
There is no any `extraout_var` assigned before. There is only `sVar3`, assigned by `FUN_00013798`, so decompiled line must be `param3 = (short)(sVar3 * 2);` or something like that.

**Comment by emteere** [comment]
The extraout will usually show up if the decompiler thinks a variable is changed by the function above it.  This usually occurs when there are side-effects from a call, a non-standard calling convention, or the flow in the function is incorrect.
It is also possilbe the pcode is incorrect for some instructions (incorrect varnode sizes).

To diagnose this potential data flow issues, can you please provide post the debug decompiler .xml dump file produced from the arrow pull-down in the upper right of the decompiler.

**Comment by lab313ru** [comment]
Take it: [mk1_135f8.zip](https://github.com/NationalSecurityAgency/ghidra/files/3054250/mk1_135f8.zip)
