### ISSUE TITLE
Strange decompiler behavior with function containing switch statement.

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#3733]
Bit of a strange one this. I have been disassembling a classic Mac OS driver file (32-bit PowerPC PEF executable). There is a problem which may be related to decompiling a function which contains a switch statement.

If you try to make a change like adding a comment or setting an equate, the decompiler view jumps to an undefined function (actually a label within the function you were looking at). And the change you made didn't actually happen.

I'll try to explain step by step how to reproduce the issue using the attached project.

- Run Ghidra and open the project. Double-click SCUSBeeShim.data to open it in CodeBrowser.
- In the Functions window, click SCUSBee_NewOldCall.
- In the decompiler window, notice the switch statement: `switch(param_1->scsiSelector) {`
- Scroll down in the decompiled code until you see
```
case SCSIRBlind:
  param_2[0xa53] = param_2[0xa53] | 0x40000000;
```
- We're going to try to set an equate for the 0x40000000 value. Right-click that and select "Set Equate...". In the Set Equate window, double-click `scsiDirectionIn`.
- Notice the decompiled view changes to "UndefinedFunction_100036c0". That actually corresponds to a label inside `SCUSBee_NewOldCall()`; it's not an actual function entry point.
- If you scroll up in the disassembly listing and click near the start of `SCUSBee_NewOldCall()`, the previous (correct/better) decompiler output reappears.
- Notice that the set equate you attempted did not stick.
- A similar thing applies if you e.g. try to add a comment. The decompiler view jumps and the comment is not actually added.

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/2737716/145402713-2f4b5e07-fbef-4c89-b8d3-48a87e016e24.png)
![screenshot2](https://user-images.githubusercontent.com/2737716/145402732-fcb5826c-8bb6-40a7-800e-0385ebc35f6b.png)

**Attachments**
[Ghidra_SCUSBee_20211209.zip](https://github.com/NationalSecurityAgency/ghidra/files/7685271/Ghidra_SCUSBee_20211209.zip)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.12
 - Ghidra Version: 10.1-BETA
 - Ghidra Origin: Ghidra github

**Comment by emteere** [comment]
Try checking the body of the function.  There was a bug where the body of the function was not always recreated during analysis at locations that the importer had created a single byte function at the location to signal function/code.  I believe this issue is fixed in Ghidra 10.1.

You can choose function->Recreate on the function label to fix the body without loosing any information.

**Comment by M-a-r-k** [comment]
Thanks. Using Ghidra 10.1 now, I recreated the function. The problem seem to still be present.

I tried adding a comment in the decompilation window. The comment appeared, but only in the disassembly, and the decompilation view shifted to an undefined function as before.

**Comment by emteere** [comment]
If you go to the top of the function and select what ghidra thinks is the body of the function with Select->Function, is the code at  0x100036c4 hilighted?

**Comment by M-a-r-k** [comment]
No it isn't. Two regions are highlighted when I do that:
100035d0 (start of the function) to 10003637
and
100037a8 to 10003847 (the actual end of the function)

So the bit in the middle is not being considered part of the function. (Can I manually override that?)

The first un-highlighted address is LAB_10003638, which is the first switch case label. (The switch cases jump table is at 10003f2c, which is outside all the function code.)

**Comment by M-a-r-k** [comment]
Maybe Ghidra saw the jump table before it analyzed the function itself? And then thought there are separate functions at each of the table addresses. Even though the not-really-functions don't have the same "look" as the actual functions in the program (which all start with `mfspr r0,LR`).

**Comment by shao113** [comment]
> 
> So the bit in the middle is not being considered part of the function. (Can I manually override that?)
> 
Running into this issue as well. Manually selecting the entire range of instructions in the listing view and then running Re-create Function seems to fix it for me.

**Comment by homes410** [comment]
I had this issue too, but come with a WIP patch. I hope this helps.
[220407-issue-3733.patch.txt](https://github.com/NationalSecurityAgency/ghidra/files/8440134/220407-issue-3733.patch.txt)

**Comment by emteere** [comment]
This appears to have been fixed in the main branch / upcoming release.
The switch stmt references were not recovered in the listing, possibly due to older analysis.

If I clear the switch stmt at the BCTR, the switch stmt is recovered, and the body of the function fixed.

There are some other cases that would leave a 1-byte function that will soon be fixed in the main branch as well.

If you get a chance when the next version 10.2 comes out, please verify on your code and re-open this issue if the problem still occurs.
