### ISSUE TITLE
Login with custom JAAS module results in "No LoginModule found..."

### ISSUE THREAD

**Issue by matutter** [NationalSecurityAgency/ghidra#3737]
I'm using the _bug_ template for this - but this is clearly more of a question. TLDR; how do I add or load a JAAS module?

**Describe the bug**
I developed a JAAS LoginModule and configured Ghidra to load it when users login. However when I connect to the server and login I get the error in the server log:

```
ghidra_server | 81/0|INFO  Authentication callbacks requested by 192.168.80.1 (GhidraServer)  
ghidra_server | 81/0|INFO  Repository server handle requested (tester@192.168.80.1) (RepositoryManager)  
ghidra_server | 81/0|INFO  Login failed (No LoginModule found for org.test.ghidra.KeyCloakLoginModule) (tester@192.168.80.1) (RepositoryManager)  
```

There is a exception being thrown in `JAASAuthenticationModule.authenticate` from `loginCtx.login()`.

I've tried to get Ghidra to find the module by:

- Adding the `.jar` containing `org.test.ghidra.KeyCloakLoginModule` in the `patch/` folder.
- Setting `wrapper.java.additional.###=-Dclass.searcher.search.all.jars=true` in `server.conf`.
- Adding the `.jar` path to the `classpath.frag` file.

**To Reproduce**
1. Add a `.jar` with a JAAS `LoginModule` to Ghidra ( some how? ).
2. Open Ghidra
3. Create a new Shared Project
4. Enter user credentials
3. Login fails
4. See error in server logs & red-text on login prompt.

**Expected behavior**
The `LoginModule` class is loaded and invoked.

**Screenshots**

_N/a_

**Attachments**

Attached are my `jaas.conf` ( added .txt so I could attach it here. ) and `server.conf`

[jaas.conf](https://github.com/NationalSecurityAgency/ghidra/files/7686694/jaas.conf.txt)
[server.conf](https://github.com/NationalSecurityAgency/ghidra/files/7686707/server.conf.txt)

**Environment (please complete the following information):**
 - OS:  Ubuntu 20.04
 - Java Version: openjdk 11.0.12
 - Ghidra Version: 10.0.4
 - Ghidra Origin: Github assets ( here )

I've also switch to using the `blacktop/ghidra:10.0.4` docker image to make sure I'm trying this in a clean environment.

**Comment by dev747368** [comment]
have you tried putting the jar in Ghidra/Features/GhidraServer/lib?

**Comment by matutter** [comment]
@dev747368 This does work. Thanks. Adding them directly to the `server.conf` is the only thing I didn't try.
