### ISSUE TITLE
os/linux_arm_64/decompile does not exist 

### ISSUE THREAD

**Issue by h2th3k** [NationalSecurityAgency/ghidra#3746]
```---------------------------------------------------
Build Date: 2021-Dec-10 1523 EST 
Ghidra Version: 10.1 
Java Home: /usr/lib/jvm/java-11-openjdk-arm64 
JVM Version: Debian 11.0.12 
OS: Linux 4.19.0-17-arm64 aarch64 
Workstation: debian-gnu-linux-10.localdomain
```

Currently running on an arm machine `Linux debian-gnu-linux-10 4.19.0-17-arm64 #1 SMP Debian 4.19.194-3 (2021-07-18) aarch64 GNU/Linux`. When trying to decompile the binaries (no matter is a x86 or arm) this error will show up and the decompilation fails. Would like to know is there a workaround to solve this issue? Thank you.

screenshot:
<img width="1207" alt="Screen Shot 2021-12-11 at 9 26 59 PM" src="https://user-images.githubusercontent.com/33063404/145698129-1fe20735-c5d9-44ae-b9e2-fd6532a7edd6.png">

**Comment by ryanmkurtz** [comment]
https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.1_build/GhidraDocs/InstallationGuide.html#Build

**Comment by h2th3k** [comment]
> https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.1_build/GhidraDocs/InstallationGuide.html#Build

thanks so much man! sorry didn't check this

**Comment by h2th3k** [comment]
hello @ryanmkurtz 
In the middle of the building process I encountered with this same [issue](https://github.com/NationalSecurityAgency/ghidra/issues/2716) then I tried to locate `gradle/support/fetchDependencies.gradle` this file but could not find on the 7.3 version of `Gradle` 
Could you please give me a hint? Thank you!

**Comment by h2th3k** [comment]
```
URL: https://github.com/pxb1988/dex2jar/releases/download/2.0/dex-tools-2.0.zip
   Connecting...
   Downloading: 2362460 of 2362460 (100%)                                               
URL: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/android4me/AXMLPrinter2.jar
   Connecting...cripts
   Connection error! java.net.UnknownHostException: storage.googleapis.com
   Connecting (2/3)...
   Connection error! java.net.UnknownHostException: storage.googleapis.com
   Connecting (3/3)...
   Connection error! java.net.UnknownHostException: storage.googleapis.com

FAILURE: Build failed with an exception.
```

seems that it is because of the connection issue then I tried with myself, does not connect either.
```
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/android4me/AXMLPrinter2.jar -P /tmp
--2021-12-11 23:10:56--  https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/android4me/AXMLPrinter2.jar
Resolving storage.googleapis.com (storage.googleapis.com)... failed: Name or service not known.
wget: unable to resolve host address ‘storage.googleapis.com’
```
I wonder do we have another work around? thanks!

**Comment by h2th3k** [comment]
Successfully built. Appreciate the hard work! yyds Ghidra team

**Comment by Manouchehri** [comment]
@ryanmkurtz Is there any plans for eventually release official Linux ARM 64-bit binaries? Just wondering if I should go to the trouble of setting up automated builds for myself, or wait it out. =)

**Comment by ryanmkurtz** [comment]
No, we have no plans to build and distribute those binaries.
