### ISSUE TITLE
Problem showing negative short integer as decimal

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#3747]
I'm disassembling a Mac OS driver (32-bit PowerPC code). Mac OS error codes are negative. Depending on the context the code may be a 16- or 32-bit signed number.

Part of one decompiled function is `sVar3 = -0x1ebb;`. I want to show that number in decimal. Right-click on it in the decompiler window, choose Decimal: -7867 from the menu. After 5 or 6 seconds (on my old laptop), a Convert Failed window appears saying "Equate named -7867 already exists with value of 4294959429".

[Note: 4294959429 = 0xFFFFE145 which is -7867 as a 32-bit signed integer.]

A couple of seconds after dismissing that window, I right-clicked the number and chose Decimal again. This time a dialog box "Decompiler Action Blocked" appeared, saying "You cannot perform Decompiler actions while the Decompiler is busy".

Converting the value to binary or octal did work however. This problem may be specific to short integers, since I was able to change a long integer value elsewhere to decimal?

[In this project, I may have previously created an enum for Mac error codes. Ghidra doesn't support negative enum values so I might have entered 0xFFFFE145 as one of the enum values. But I deleted that enum a while ago. I also previously worked on the project with Ghidra 10.1-BETA. Could this problem be due to the project file getting corrupted?]

To reproduce this download the attached project (same file as for issue# 3733).

- Load the project. Open SCUSBeeShim.data
- In the Functions window, click SCUSBee_SIMAction.
- In the decompiler window, see `sVar3 = -0x1ebb;` near the start of the function.
- Right click etc. as explained above

**Attachments**
[Ghidra_SCUSBee_20211209.zip](https://github.com/NationalSecurityAgency/ghidra/files/7685271/Ghidra_SCUSBee_20211209.zip)

**Environment (please complete the following information):**
- Windows 10, Java 11.0.12, Ghidra 10.1

**Comment by RenaKunisaki** [comment]
This seems like the same bug I've encountered which can be recreated by finding two instances of a value that displays as negative hex, right-clicking, selecting Convert > Decimal, and repeating this for the other instance. Seems like the first time creates an equate and the second time fails to recognize that the equate already exists. Manually setting the equate also has this issue.
