### ISSUE TITLE
Debugger: the font size on the objects window is very small and cannot be enlarged

### ISSUE THREAD

**Issue by aldelaro5** [NationalSecurityAgency/ghidra#3752]
**Describe the bug**
The objects window has a very tiny font size and it is the only window afaik that does not honor the way I force the font size which is to add the line `VMARGS=-Dfont.size.override=22` in the launch.properties file. Everything else, this override works.

**To Reproduce**
1. Add the line `VMARGS=-Dfont.size.override=22` in launch.properties
2. Launch ghidra, notice the font gets overriden correctly everywhere.
3. Check the objects window in the debugger, see the font is still very small when displaying the tree.

**Expected behavior**
The font size being correctly overriden or a way for me to increase its size

**Screenshots**
This is a sample that shows the differences between the expected font size vs the objects window one
![Screenshot from 2021-12-13 13-18-33](https://user-images.githubusercontent.com/8932978/145866671-3b1ef55b-888a-4a4d-98bc-fc58c7f5c0d6.png)

**Environment (please complete the following information):**
 - OS: Arch Linux kernel 5.15.6
 - Java Version: 11.0.13
 - Ghidra Version: 10.1
 - Ghidra Origin: Official release from this repo

**Additional context**
This is mainly an issue as I am visually impaired making it hard to read the default font sizes of Ghidra so the override solves my issue.

**Comment by d-millar** [comment]
@aldelaro5  I see the code at fault.  Apologies - careless on my part.  Will try to get a fix in for the next patch cycle.
