### ISSUE TITLE
Sizeof struct is wrong for `_IO_FILE` in libc

### ISSUE THREAD

**Issue by ekilmer** [NationalSecurityAgency/ghidra#3756]
**Describe the bug**
Hello, I noticed that the reporting of `sizeof(struct _IO_FILE)` from `stdio.h` is wrong with Ghidra 10.1 for GLibc Linux x86_64.

On 10.0.4 the size is correct at 216 bytes, but 10.1 reports 256.

The field responsible for this change in size is the `_unused2` field with a complicated array size expression:
```
struct _IO_FILE
{
  ... 
  /* Make sure we don't get into trouble again.  */
  char _unused2[15 * sizeof (int) - 4 * sizeof (void *) - sizeof (size_t)];
};
```
as seen in this link https://code.woboq.org/userspace/glibc/libio/bits/types/struct_FILE.h.html#_IO_FILE::_unused2

**To Reproduce**

I grabbed the libc from a Ubuntu 20.04 Docker with md5sum:

```
d371da546786965fe0ee40147ffef716  /lib/x86_64-linux-gnu/libc-2.31.so
```

1. Open libc in Ghidra 10.1
2. Analyze with default settings
3. Search for `_IO_FILE` in Data Type Manager
4. Hover over `libc-2.31.so` -> `stdio.h` -> `_IO_FILE` to see size is `256`
5. Also look at the field sizes in `_IO_FILE` to see that `_unused2` is size `56` instead of 20

I confirmed that total size of 216 and `_unsed2` size of 20 is correct with the following simple C program:

```c
#include <stdio.h>

void main() {
  printf("sizeof _IO_FILE: %ld\n", sizeof(struct _IO_FILE));
  printf("sizeof _IO_FILE._unused2: %ld\n", sizeof(((struct _IO_FILE *)0)->_unused2));
  printf("complex array size: %ld\n", 15 * sizeof (int) - 4 * sizeof (void *) - sizeof (size_t));
}
```

and it prints
```
sizeof _IO_FILE: 216
sizeof _IO_FILE._unused2: 20
complex array size: 20
```

Actually, Ghidra 10.0.4 reports the `_unused2` size as `15` which isn't correct, but I guess some alignment created the correct total size.

**Expected behavior**

The correct total size is 216 bytes and `_unused2` size is 20 bytes

**Attachments**

Attached libc sample 
[libc-2.31-ubuntu-20.04.so.zip](https://github.com/NationalSecurityAgency/ghidra/files/7712857/libc-2.31-ubuntu-20.04.so.zip)

**Environment (please complete the following information):**

 - OS: macOS 11.6.2
 - Java Version: 11.0.13
 - Ghidra Version: 10.1
 - Ghidra Origin: Official Release

**Additional context**

I think the error might have been introduced in this commit https://github.com/NationalSecurityAgency/ghidra/commit/832dea6b6db831032db87c9ceb73d39c96892118? But I haven't built Ghidra locally to figure it out, mostly because I couldn't find where/how to run the `Ghidra/Features/Base/src/test/java/ghidra/app/util/cparser/CParserTest.java` test in Eclipse---code search didn't help. I would appreciate learning how to run this test for the future.

I believe it's the above commit because the source code for GLibc's `_IO_FILE` structure has a complicated `sizeof` expression for the field that has a changed size https://code.woboq.org/userspace/glibc/libio/bits/types/struct_FILE.h.html#_IO_FILE::_unused2

Thank you!

**Comment by emteere** [comment]
Thanks for reporting the bad size.  There are a couple of issues with this one.  We've diagnosed it to the parsing and handling of sizeof() operator with a parameter of a data type pointer.  This is being fixed for the next patch version.  We'll also need to re-parse the data types archives to fix this for a patch release.

There is also an issue with the underlying data organization and sizeof() when sizeof is used on a type like long which could change it's size on a 32 or 64 bit platform.  We should be able to address this issue along with a new feature coming most likely in 10.2.

**Comment by ekilmer** [comment]
Great! Thank you for the update and the details regarding the bug.

**Comment by Wall-AF** [comment]
> There is also an issue with the underlying data organization and sizeof() when sizeof is used on a type like long which could change it's size on a 32 or 64 bit platform. We should be able to address this issue along with a new feature coming most likely in 10.2.

Please don't forget about 16-bit platforms too..
