### ISSUE TITLE
API - How can i return Assembly/Decompiled Code

### ISSUE THREAD

**Issue by kiks7** [NationalSecurityAgency/ghidra#376]
From Jython APIs how can i retrieve raw assembly and/or decompiled code from a function?
I can't find anything related.

Thanks.

**Comment by saruman9** [comment]
Raw assembly:
```
listing = currentProgram.getListing()
currentFunction = listing.getFunctionContaining(currentAddress)
entryPoint = currentFunction.getEntryPoint()
instructions = listing.getInstructions(entryPoint, True)
for index, instruction in enumerate(instructions):
    print instruction
    if index > 5:
        break
```
[`Listing`](http://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Listing.html)

Decompiled code:
```
decompInterface = ghidra.app.decompiler.DecompInterface()
decompInterface.openProgram(currentProgram)
decompileResults = decompInterface.decompileFunction(currentFunction, 30, monitor)
if decompileResults.decompileCompleted():
    decompiledFunction = decompileResults.getDecompiledFunction()
    decompiledFunction.getC()
```
[`DecompInterface`](http://ghidra.re/ghidra_docs/api/ghidra/app/decompiler/DecompInterface.html)

You can use also `FlatAPI`:
    - [`FlatProgramAPI`](http://ghidra.re/ghidra_docs/api/ghidra/program/flatapi/FlatProgramAPI.html)
    - [`FlatDecompilerAPI`](http://ghidra.re/ghidra_docs/api/ghidra/app/decompiler/flatapi/FlatDecompilerAPI.html)

**Comment by kiks7** [comment]
Thanks !

**Comment by PerikiyoXD** [comment]
currentFunction ain't defined on python anymore¿
