### ISSUE TITLE
Add checkboxes to adjust Metal look & feel options

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#3773]
This is a small feature request relating to Swing themes.

There are currently six options for Swing look and feel: System, Metal, Nimbus, CDE/Motif, Windows and Windows Classic.

The Metal theme has options which can't be directly changed in Ghidra. You can add lines to launch.properties to change those manually, but a couple of GUI checkboxes would be nice.

The Metal theme can have two looks, Ocean or Steel. Screenshots of both are at https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html

I have added these lines to my launch.properties file:
```
VMARGS=-Dswing.metalTheme=steel
VMARGS=-Dswing.boldMetal=false
```
The first sets the steel look (which was the older/original style). The second tells it to not use bold text for everything.

The steel look seems to work quite well with the Use Inverted Colors option.

**Comment by astrelsky** [comment]
Are these options actually changeable at runtime?

**Comment by M-a-r-k** [comment]
Programs *can* change Swing look & feel at run time, but Ghidra doesn't support that so the change would only happen after quitting and relaunching.

For what it's worth the JDK file `src/java.desktop/share/classes/javax/swing/plaf/metal/DefaultMetalTheme.java` explains how it *could* be changed on the fly. I won't paste it all here but look for this text:
```
 * {@code DefaultMetalTheme} uses bold fonts for many controls.  To make all
 * controls (with the exception of the internal frame title bars and
 * client decorated frame title bars) use plain fonts you can do either of
```

**Comment by XVilka** [comment]
There is also FlatLaf that would certainly benefit from more configuration options: 
- https://github.com/zackelia/ghidra-dark/issues/23#issuecomment-962571705
- https://github.com/zackelia/ghidra-dark/issues/24#issuecomment-997502178

**Comment by M-a-r-k** [comment]
Changing the current `Metal` entry in the Swing Look and Feel drop-down to `Ocean` and adding a `Steel` entry would be nice.

An extra suggestion: add a `Default` entry to the drop-down too. That would allow the user to have two user-defined looks in their launch.properties and switch between them in Ghidra, e.g.
`VMARGS=-Dswing.systemlaf=my.favorite.laf1`
`VMWAGS=-Dswing.defaultlaf=my.favorite.laf2`

**Comment by dragonmacher** [comment]
Closing this since the new Theming capability completely changes how Look and Feels are managed.
