### ISSUE TITLE
Selection cannot be cancelled using just keyboard

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3778]
**Is your feature request related to a problem? Please describe.**
When in either the "Decompile:" or "Listing:" views, any selection (for copying etc.) requires a mouse click to remove.  If you're a primary keyboard user, this is a nuisance.

**Describe the solution you'd like**
Some key combination or (context) menu option to remove the selection.

**Comment by ghidracadabra** [comment]
You can add a keybinding to a menu item in Ghidra by hovering over the item and pressing F4.

There's a menu item to clear the selection under the "Select" menu in the Code Browser.

**Comment by Wall-AF** [comment]
> You can add a keybinding to a menu item in Ghidra by hovering over the item and pressing F4.
> 
> There's a menu item to clear the selection under the "Select" menu in the Code Browser.

There is no menu item for this.

**Comment by ghidracadabra** [comment]
Hmmm...from the Code Browser, if you go to File -> Configure, then click "Configure" under "Ghidra Core", is the CodeBrowserSelectionPlugin enabled?

**Comment by astrelsky** [comment]
Does escape not work? This is just a shot in the dark. I don't know of any other key that I could reasonably expect to be used to unselect something.

**Comment by Wall-AF** [comment]
@ghidracadabra all "Ghidra Core" plugins are enabled.
@astrelsky `Esc` doesn't work!`

The current process (which is quite clever/nice) allows multiple independent areas to be selected (using keys `Shift+Arrows`), but there's no way to perfom either a complete deselection or an unselect of the most recently added area.  Even using the same keys `Shift+Arrows` over the preselected area doesn't unselect

**Comment by dragonmacher** [comment]
Just to be clear, in your tool you do not have an action under the main menu for `Select -> Clear Selection` ?

**Comment by Wall-AF** [comment]
Oops, sorry, didn't see that!  (Need better specs!!!!)  Added `Esc` key and that works too...
