### ISSUE TITLE
Glitched GUI rendering on connections from RDP to GNOME Desktop on CentOS 7

### ISSUE THREAD

**Issue by eoksum** [NationalSecurityAgency/ghidra#378]
Hi there,

I installed Ghidra 9.0.2 on my CentOS 7 server which has GNOME as desktop GUI. When I connect to the server by RDP from my Windows 10 laptop I get a very bad and glitched GUI display of Ghidra.

**To Reproduce**
1. Deploy a CentOS 7 server,
2. Install GNOME desktop on it,
3. Install xRDP to server
4. Install Ghidra 9.0.2 on server
5. Connect through RDP to the server and start Ghidra.

These will be the finishing results: (SCREENSHOTS)
http://prntscr.com/n8te77
http://prntscr.com/n8tgbe

**Environment: **
 - OS: CentOS 7 Core (64 bits with GNOME Desktop as GUI and xRDP as RDP server daemon)
 - Java Version: 11.0
 - Ghidra Version: 9.0.2

**Comment by saruman9** [comment]
Glitched GUI only appears for Ghidra or other GUI apps or other Java apps (you can test BinDiff, for example)?

BTW, I use VNC and SSH with X forwarding. It is works very well for me (only Linux <-> Linux tested).

**Comment by ryanmkurtz** [comment]
Are you running multiple monitors?

**Comment by eoksum** [comment]
> Are you running multiple monitors?

Yes.

**Comment by ryanmkurtz** [comment]
I am going to close this as a duplicate of #161.  Please check out the conversation over there to see potential workarounds.
