### ISSUE TITLE
0xff with type "uint8_t" being decompiled as "-1"

### ISSUE THREAD

**Issue by Muqi-Zou** [NationalSecurityAgency/ghidra#3786]
Compile the following source code with "-g" in gcc:
```
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>

//test_uint8_ff
int test(uint8_t input){
	if (input < 0xff)
		{printf("input is less than 0xff\n");
			return 1;
		}
		printf("input is equal to 0xff\n");
			return 2;
}

int main(void) {
	uint8_t local = 0;
	scanf("%" SCNu8, &local);
	test(local);
}
```
And decompile the generated binary, ghidra will give us code like:

```
//test_uint8_neg_1
int test(uint8_t input){
	if (input == -1)
		{printf("input is equal to 0xff\n");
			return 2;
		}
		printf("input is less than 0xff\n");
			return 1;
}
```
I understand that "-1" and "0xff" are treated the same in uint8_t. But, if we compile both of the above two functions and run, they do not perform the same :
```
friends@friends-OptiPlex-5070:~/muqi/trash$ ./test_uint8_neg_1 
-1
input is less than 0xff
friends@friends-OptiPlex-5070:~/muqi/trash$ ./test_uint8_neg_1 
255
input is less than 0xff
friends@friends-OptiPlex-5070:~/muqi/trash$ ./test_uint8_neg_1 
254
input is less than 0xff

friends@friends-OptiPlex-5070:~/muqi/trash$ ./test_uint8_ff 
-1
input is equal to 0xff
friends@friends-OptiPlex-5070:~/muqi/trash$ ./test_uint8_ff 
255
input is equal to 0xff
friends@friends-OptiPlex-5070:~/muqi/trash$ ./test_uint8_ff 
254
input is less than 0xff
```
From readablity, 0xff being translated to -1 also confuses me. 
Anyhow, If we want to fix this, some change could be made in [PrintC::pushConstant ](https://github.com/NationalSecurityAgency/ghidra/blob/56ca81cfe85efec5a4f17a409f3f05fabf5f8e3f/Ghidra/Features/Decompiler/src/decompile/cpp/printc.cc#L1573).

**Comment by dev747368** [comment]
You should check your data type manager and see what the uint8_t type boils down to.  (tip: turn on the "Preview Window" from the drop down triangle menu in the upper-right corner of the DTM, and then you could just type "uint8_t" in the filter field to narrow the tree down.  You only want to look at the entries that are under your program name, and ignore the ones under generic_clib_xyz or windows_vs_123, etc)

Ideally, it should resolve to an unsigned character type, but you should make sure of that first.

**Comment by Muqi-Zou** [comment]
Thanks! I think the uint8_t is resolved to unsigned char type, I clicked the "Show Base data type" and it then points to "uchar" in ELF folder  -> my binary /program name folder -> Data Types

**Comment by dev747368** [comment]
So that was the limit of my suggestions.  FYI, when I compile:

```
#include <stdio.h>
#include <stdint.h>


int test(uint8_t val) {
	printf("testing: %d\n", val);
	if ( val < 0xff ) {
		printf("lt 0xff\n");
		return 1;
	}
	printf(" == 0xff\n");
	return 2;
}
int main() { blah blah }
```

and put it into ghidra I get:
```
int test(uint8_t val)

{
  int iVar1;
  
  printf("testing: %d\n",(ulong)val);
  if (val == 0xff) {
    puts(" == 0xff");
    iVar1 = 2;
  }
  else {
    puts("lt 0xff");
    iVar1 = 1;
  }
  return iVar1;
}
```

**Comment by Muqi-Zou** [comment]
Ha, I used an old version of ghidra~ Thanks for you time and sorry for the bother. Yes, you are right, it is correct now! After checking the result before and after [ commit 1391e83ce9f63faf7fafc0d17b875d77729d5716](https://github.com/NationalSecurityAgency/ghidra/commit/1391e83ce9f63faf7fafc0d17b875d77729d5716#diff-d93171b0de14b354e71423d8665c8d6443b677f7c1ed88611c340d54c8fba6a3), I am pretty sure this issue has been fixed~
