### ISSUE TITLE
Support PDB loading without dia by converting llvm-pdbutil YAML output to XML format.

### ISSUE THREAD

**Issue by ikelos** [NationalSecurityAgency/ghidra#379]
**Is your feature request related to a problem? Please describe.**
It's disruptive to workflow to have to start windows in order to get access to a new pdb file.  This is due to the use of DIA to fully access the contents of the pdb, however, LLVM has done a lot of work integrating the PDB format from Microsoft's open source implementation into the llvm-pdbutil tool.  As of llvm-8, this tool can extract almost all the pertinent information from a PDB file.

**Describe the solution you'd like**
I'd like to be able to download and convert a PDB file into a format that could be consumed by ghidra (either the existing .pdb.xml format, or LLVM's yaml format) directly within linux.

**Describe alternatives you've considered**
There are few other implementations of Microsoft's DIA available, but LLVM has converted the CCI implementation of the PDB file format into a component of llvm, so llvm-8 and above can dump a lot of information from PDBs into a more accessible format (YAML) already.

**Additional context**
Being able to directly download the pdb and then import it, if a locally available copy of llvm-pdbutil from a late enough version of LLVM were available, would be extremely useful but even just being able to get a PDB and convert it into a format that can be consumed by ghidra outside of ghidra into the appropriate XML format, without having to change operating systems just to do it, would be useful.

**Comment by cmueller-tp** [comment]
Just a hint to a possible alternative:
https://github.com/volatilityfoundation/volatility3/blob/master/development/pdbparse-to-json.py

**Comment by ghizard** [comment]
@ikelos @cmueller-tp Thank you both for input on ways to eliminate the pdb.exe. We now have the PDB Universal Analyzer and Loader capabilities, which no longer require the MSDIA-based pdb.exe processing on a Windows machine. We had the Universal capability in the works for a long period of time, also leveraging MSFT's "documentation." That said, there is still a lot of information within the PDB that we are not applying to programs, and we hope to continue to improve on making use of it.
