### ISSUE TITLE
ARCompact Ghidra support

### ISSUE THREAD

**Issue by korkikian** [NationalSecurityAgency/ghidra#3792]
Hi,

I am currently implementing ARCv2 support for Ghidra and I am using your ARCompact files for references.
ARC ISA is not that straightforward, so I am constantly checking the reference manual.
I have a question regarding shifting operations, e.g. asr_s. According to the manual, this operation shall keep the sign: bit 31

```
PSEUDOCODE
dest = src >> 1
if src[31]==1 then dest[31] = 1
if F==1 then
Z_flag = if dest==0 then 1 else 0
N_flag = dest[31]
C_flag = src[0]
```

In your code the sign seems not to be preserved:

```
:asr_s s_rb, s_rc, 1 is s_major_opcode=0x0f & s_u5=0x1c & s_rb & s_rc {
  s_rb = s_rc s>> 1;
}
```
Do you think the following description would make more sense?
```
:asr_s f16_gen_op_b, f16_gen_op_c is MAJOR_OPCODE=$(F16_GEN_OP) & f16_gen_op_b & f16_gen_op_c & f16_gen_op_U=0b11100 { 
  local sign_flag:4 = (f16_gen_op_c & 0x80000000:4);
  f16_gen_op_b = f16_gen_op_c >> 1;
  f16_gen_op_b = f16_gen_op_b | sign_flag;
}
```

--
Roman

**Comment by GhidorahRex** [comment]
the operation `s>>` is the signed right-shift, and preserves the sign. There's no need to update the sign bit, and doing so in the manner described here would be incorrect regardless.

**Comment by korkikian** [comment]
Right, mad bad.

**Comment by korkikian** [comment]
Closed
