### ISSUE TITLE
PortableExecutableRichPrintScript run error

### ISSUE THREAD

**Issue by lemuellew** [NationalSecurityAgency/ghidra#3805]
![image](https://user-images.githubusercontent.com/59448437/147349168-9e8eedab-7e78-4731-bf69-c7eefbf391ca.png)

![image](https://user-images.githubusercontent.com/59448437/147349139-d9f0e9b5-ddfa-4471-ace3-71c9bdff98aa.png)

**Comment by lemuellew** [comment]
It works on 9.2.4, but doesn't work on 10.0

**Comment by ryanmkurtz** [comment]
You'll need to attach your test binary so we can have some hope of diagnosing the issue.

**Comment by lemuellew** [comment]
In fact, all PE files will have this error when running the script on version 10.0 and 10.1.

Related to #3800

[store_b2917248d1269d0d35fc1cea42e3cff9930f48269165f8c6325f9e51c58797e3.zip](https://github.com/NationalSecurityAgency/ghidra/files/7783396/store_b2917248d1269d0d35fc1cea42e3cff9930f48269165f8c6325f9e51c58797e3.zip)

**Comment by ryanmkurtz** [comment]
Thank you.  This does not happen with all binaries, but I've confirmed that it is fixed by #3347.
