### ISSUE TITLE
Enum weird sorting state from add() vs using UI

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#3806]
**Describe the bug**
If you add() a negative number, it is converted to the unsigned equivalent in the UI; however, if you sort the value from add() is used and those values will appear out of order before lower unsigned values.

**To Reproduce**
1. Create a new enum with `{VAL_00000000: 0, VAL_FFFFFFFF: 0xffffffff}` using the UI
2. get a reference to this enum data type
3. `my_enum.add("VAL_FFFFFFFE", -2)`  (I am doing this in python)
4. Sort enum values in enum editor by value
5. see `{VAL_FFFFFFFE: 0xfffffffe, VAL_00000000: 0, VAL_FFFFFFFF: 0xffffffff}` 

**Expected behavior**
Sort consistently by their unsigned values
 `{VAL_00000000: 0, VAL_FFFFFFFE: 0xfffffffe, VAL_FFFFFFFF: 0xffffffff}` 

**Environment (please complete the following information):**
 - OS: 20.04
 - Java Version: 11.0.13
 - Ghidra Version: 436bb4873e8571b87a4d785bb828d9bf772b4867
 - Ghidra Origin: eclipse

**Additional**
if you double click to get the cursor into the value box and enter or arrow the value is then recognized as unsigned are sorted immediately when the cursor leaves.

Context on how I came across this is I initially had a struct field as uint and changed it to an enum type and scripted iterating my struct's usage and adding some sort of name to the value (the enum started with only `INVALID:0`), values used in the add() were retrieved with `x.getComponent(0).getValue().getValue()`.  If the struct field was the enum, when I did the getValue(), even though the value was not added to the enum yet, should/would this be treated as an enum.getValue(NAME) or just the 4-byte value and it decides its negative?

**Comment by astrelsky** [comment]
I'm a bit confused. The result you are seeing is actually insertion order? In the final step it doesn't appear to be sorted by key or value.

**Comment by dragonmacher** [comment]
@mumbel Can you confirm this is still not working?  I tried this and it seems to do the right thing.

**Comment by mumbel** [comment]
@dragonmacher   This appears to still be there on faf73e8ecb26320a998da6af1a0dcb81c427657f

create new enum  foobar,  4 bytes, with VAL_0 = 0x0  as the initial value, save/close enum editor
```python
x = getDataTypes("foobar")[0]
x.add("VAL_FFFFFFFF", 0xffffffff)
x.add("VAL_NEG2", -2)
```
open enum editor back with foobar

sort by value, its {VAL_FFFFFFFE: 0xfffffffe, VAL_0: 0x0, VAL_FFFFFFFF: 0xffffffff}

sort by name, its {VAL_0:0x0, VAL_FFFFFFFE: 0xfffffffe, VAL_FFFFFFFF: 0xffffffff}

So is it an issue the value  `-2` is displayed as `0xfffffffe`  and sorted as `-2`.

You cannot enter -2 via the UI, only script

**Comment by Wall-AF** [comment]
Related to https://github.com/NationalSecurityAgency/ghidra/issues/4616 I believe!
