### ISSUE TITLE
M68000: dbf loop end decompile bug

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#381]
In listing it looks like this:
![изображение](https://user-images.githubusercontent.com/7189309/55720172-dd447480-5a08-11e9-9c84-e28f6d6a024e.png)

Decompiler outputs the following lines:
![изображение](https://user-images.githubusercontent.com/7189309/55720203-f3eacb80-5a08-11e9-8d4a-d0d7d8957367.png)

Line:
`if (false) break;` is wrong.

**Comment by emteere** [comment]
Code like the if statement you mention will show up when you turn off "dead code removal" in the decompiler settings.  Unless I am misunderstanding the data flow I see, are you saying the if (false) should be something else?

**Comment by lab313ru** [comment]
dbf (Decrement and branch if false) decreases d2 register and sets corresponding flags when register becomes 0xFFFFFFFF.

**Comment by lab313ru** [comment]
It is strange: there is no such opcode (`dbf`/`dbra`) in `68000.sinc`.

**Comment by mumbel** [comment]
db^cc

**Comment by lab313ru** [comment]
I'm not familiar with SLEIGH code, but where is flags updating here?
`{ if (cc) goto inst_next; regdnw=regdnw-1; if (regdnw!=-1) goto addr16; }`

**Comment by jrmuizel** [comment]
It looks to me like the flags are not being updated.

**Comment by mumbel** [comment]
No flags are updated in DBcc per manual

**Comment by lab313ru** [comment]
Flags must be updated, because it compares `regdnw!=-1`.

**Comment by lab313ru** [comment]
Then there is strange output anyway.

**Comment by lab313ru** [comment]
I think decompiler should update internal (non Motorola's) flag related to condition, because it compares against `-1`.

**Comment by jrmuizel** [comment]
cc isn't updated. It's the initial condition for entering the loop.

**Comment by lab313ru** [comment]
So, where is the problem? `false` condition means that some state is not updatable in dbf loop.

**Comment by emteere** [comment]
The dead code is from the pcode in bold:

:db^cc regdnw,addr16	is op=5 & cc & op67=3 & op5=0 & op34=1 & regdnw; addr16	
    **if (cc) goto inst_next;**
    regdnw=regdnw-1;
    if (regdnw!=-1) goto addr16; 
}

The **if (false) break;** is from the **if (cc) ...**
This could be re-written to a sub-constructor to remove the pcode if the condition is always false, however the decompiler does dead code removal so it is unnecessary.

ccBranch: 'f' is  ..... { }
ccBranch: cc is cc {  if (cc) goto inst_next; }

:db^ccBranch   regdnw,addr16	is op=5 & ccBranch & op67=3 & op5=0 & op34=1 & regdnw; addr16	
    build ccBranch;
    regdnw=regdnw-1;
    if (regdnw!=-1) goto addr16; 
}

**Comment by lab313ru** [comment]
So, this output was just generated by switched off option? I'll check if it 
generates correct output in other case

emteere <notifications@github.com> 9 апреля 2019 г. 4:22:35 написал:

**Comment by lab313ru** [comment]
Yes, it shows `if (false)` only when eliminate dead code option enabled.
