### ISSUE TITLE
M68K addx doesn't handle carry properly

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#3818]
The current definition is
`{ local tmp =zext(XF)+Ty; addflags(tmp,Tx); Tx=Tx+tmp; extendedResultFlags(Tx); }`
If `Ty = 0xffff_ffff, Tx = 0 and XF = 1` `zext(XF)+Ty` will overflow but the carry will be discarded causing the operation to fail to  properly set the CF/XF.

It looks like the `ADDC` in ia.sinc handles this properly.

**Comment by GhidorahRex** [comment]
Good find. This should be updated to reflect the correct carry semantics.
