### ISSUE TITLE
Ability to use Ctrl+F4 to close tabs on views that can open mutlple tabs

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3826]
**Is your feature request related to a problem? Please describe.**
I often use various editors (eg Structure, Enum) and although it is possible to switch to the next tab (using Ctrl+Tab) there's no keyboard shortcut to close one.

Also you cannot switch to the previous tab (using Ctrl+Shift+Tab) either.

**Describe the solution you'd like**
The addition of a possibly configurable key combination to perform these actions.

**Describe alternatives you've considered**
For someone who finds the mouse difficult, MouseKeys is the alternative.  Great though that is, it can be a pain if you're using several multi-tabbbed views.

**Comment by Wall-AF** [comment]
Maybe the use of `Ctrl+<1-9>` could help in switching between the first 9 tabs also.

**Comment by dragonmacher** [comment]
Regarding the ability to close the tabbed provides, this should be possible now.  We previously added the ability to set a keybinding on the 'X' action in the upper-right corner of any provider.  This should be a global setting that will close the currently focused provider.  If that provider is in a set of tabbed providers, then it should work as you desire.

**Comment by dragonmacher** [comment]
Regarding tab navigation, you can also do this now, with a bit of clunkiness.  It appears that Java uses `Ctrl-PageUp/PageDown` for tab navigation.  This works in the structure editor tabs, as an example, *as long as the table in the editor does not have focus.*

In my testing, if the table is focused, I have to press `Ctrl-Tab` to leave the table (with focus going to the next field in the editor), then `Ctrl-PageUp/PageDown` seem to work as expected.

Assuming the table did not interfere with the navigation, then it seems like all items in the ticket are address, except for the ability to quickly jump to the nth tab.   It is not clear how easy it would be to tell the table to ignore navigation keystrokes.

**Comment by Wall-AF** [comment]
Here's the screenshot:
![image](https://user-images.githubusercontent.com/67698927/148644984-b522d329-9290-49b8-8533-2be9f5559f1d.png)
But there doesn't appear to be a way to assign a keystroke to either `X` at the bottom of the window.

**Comment by Wall-AF** [comment]
Thanks, works well once I realised the `X` at the top-right of the window just closed the current tab!!!!
