### ISSUE TITLE
Repeatedly invoking `gradle buildGhidra` produces broken build/dist zip archive every other time

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#3827]
Download ghidra-master.zip from github, unpack.

`gradle -I gradle/support/fetchDependencies.gradle init`
`gradle buildGhidra`
(build/dist zip size: 312,684,032)
`gradle buildGhidra`
(build/dist zip size: 19,617,529) <-- Obviously broken
`gradle buildGhidra`
(build/dist zip size: 312,684,061) <-- Probably OK again
`gradle buildGhidra`
(build/dist zip size: 19,617,534) <-- Whoops
`gradle buildGhidra`
(build/dist zip size: 312,684,060) <-- And OK again

The built .zip size alternates between completely broken (~19MB) and probably-OK on successive invocations of `gradle buildGhidra`.

I'm using Gradle 7.3.3, Visual Studio 2022, JDK zulu18.0.65-ea-jdk18.0.0-ea.28-win_x64

**Comment by mumbel** [comment]
I could repro on linux as well, I think looking at logs `assembleDistribution` and `assembleDistribution_linux_x86_64` were marked as UP-TO-DATE in the tiny build.  I don't know enough about gradle to dig further, did it manually, was basically looking at `diff -y <(gradle buildGhidra) <(gradle buildGhidra) | grep "> Task"`

**Comment by ryanmkurtz** [comment]
I've narrowed down the strange behavior to this:

https://github.com/NationalSecurityAgency/ghidra/blob/436bb4873e8571b87a4d785bb828d9bf772b4867/gradle/root/distribution.gradle#L521-L523

After we produce the final zip we delete the pre-zipped directory.  If you comment out the delete and preserve the directory that gets zipped, it works correctly each time.  Someone else on the team is going to investigate this further.
