### ISSUE TITLE
Buggy overlays code in PcodeEmit

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#3828]
This line has a misprint:
https://github.com/NationalSecurityAgency/ghidra/blob/436bb4873e8571b87a4d785bb828d9bf772b4867/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/app/plugin/processors/sleigh/PcodeEmit.java#L745

It should be:
```java
VarnodeData v = in[i];
```

**Comment by dev747368** [comment]
re: `in[0]` vs `in[i]`.  Superficially, I would agree with you that your suggestion is the correct fix, but looking at the code in that file, `in[0]` is a common and repeatedly used idiom.

The `for()` loop you're pointing out doesn't use the `i`, so something is squirrelly there, but could it be some other deficiency?

**Comment by lab313ru** [comment]
That code iterates over input and one output varnodes and updates address spaces for them. So, definitely, it should be `in[i]`.

**Comment by ghidra1** [comment]
@lab313ru I would agree with you.  I have assigned to @caheckman

**Comment by caheckman** [comment]
Yup, its a typo.  Thank you for reporting it.
