### ISSUE TITLE
Improper recognition of older PE files.

### ISSUE THREAD

**Issue by cocateh** [NationalSecurityAgency/ghidra#3830]
**Describe the bug**
Some older PE files are detected as old-school MZ exectuables

**To Reproduce**
1. Import a certain valid PE file

**Expected behavior**
Ghidra should recognize the file as proper PE

**Screenshots**
![ghidra_bug](https://user-images.githubusercontent.com/15251385/148214014-58d4d9e7-a374-4797-a23d-9f6a80a5470e.png)
Here is for comparison, summary of this file in Binary Ninja
![properly_parsed](https://user-images.githubusercontent.com/15251385/148214091-94ca0501-39c8-4340-959f-853d1b610516.png)

**Attachments**
If this is desired I can upload problematic files with WeTransfer

**Environment (please complete the following information):**
 - OS: Arch Linux, Linux 5.15.12
 - Java Version: 11.0.13
 - Ghidra Version: 10.1
 - Ghidra Origin: ghidra-sre.org

**Additional context**
This was discovered initialy [here](https://gamozolabs.github.io/fuzzing/2021/11/16/rust_on_nt_mips.html) but it isn't a MIPS issue or a MIPS PE  
issue as this bug occurs with any dll file (haven't checked any exes)
for any architecture from this certain Windows version.

**Comment by ryanmkurtz** [comment]
Is PE in the format list, with MZ being the default?  Or is PE totally missing as a choice?

**Comment by cocateh** [comment]
It is missing.

**Comment by cocateh** [comment]
[hexdump.txt](https://github.com/NationalSecurityAgency/ghidra/files/7815334/hexdump.txt)

**Comment by cocateh** [comment]
https://we.tl/t-rvERnvKT6p

**Comment by cocateh** [comment]
these are 4 files i tried to reverse in ghidra, and none of which were detected properly
