### ISSUE TITLE
How to access the decompiler results to modify them?

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#3832]
I want to change the decompiler listing, but how can I access HighFunction object in it to change something?

**Comment by astrelsky** [comment]
You can't. If you want to do this you would need to create your own decompiler window, controller, etc. Iirc some of the classes *might* have package visibility so extending them may be problematic. I could be mistaken on that though.

**Comment by lab313ru** [comment]
In order to access the decompiler window controller I did the same thing as their tests do:
```java
DecompilePlugin decompiler = (DecompilePlugin) tool.getManagedPlugins().stream().filter(
          p -> p.getClass() == DecompilePlugin.class).findFirst().get();
      
      DecompilerProvider provider = (DecompilerProvider)TestUtils.getInstanceField("connectedProvider", decompiler);
      DecompilerController controller = (DecompilerController)TestUtils.getInstanceField("controller", provider);
      HighFunction func = controller.getHighFunction();
```

They're accessing reflection info and modifying some fields visibility. But, changing this HighFunction does nothing.

**Comment by astrelsky** [comment]
Right because what is being modified is either not stored in a database or isn't saved. There is a `HighFunctionDBUtil` or something somewhere. May be worth looking into but I don't think you will get very far without reimplementating a lot of code. Feel free to prove me wrong though 😁



Also it seems I was wrong about the visibility.

**Comment by lab313ru** [comment]
Then it becomes too hard to fix that issue with overlayed references: the decompiler accesses only the default data space to map a constant value to an Address.
Also, calculated addresses like in MIPS arch cannot be modified to point to anything except a default AddressSpace.

**Comment by sad-dev** [comment]
You can 'fix' the current decompile results temporarily if you are willing to use the dark arts of reflection. You can access the decompiler cache like @astrelsky did in #2017, and modify the HighFunction from it before forcing the window to 'refresh' via ``DecompilerPanel.setDecompileData``.

**Comment by astrelsky** [comment]
> You can 'fix' the current decompile results temporarily if you are willing to use the dark arts of reflection. You can access the decompiler cache (``DecompilerController .decompilerCache``) like @astrelsky did in #2017, and modify the HighFunction in it before forcing the window to 'refresh' via ``DecompilerPanel.setDecompileData``. 

I don't actually reccomend doing that. I did it because I was lazy and didn't want to reimplement it :rofl:

**Comment by lab313ru** [comment]
What does it mean `before forcing the window to 'refresh'` ? Is there some callback for that? Or it just means to use `setDecompileData`?

Is there any `non-dark-arts` way to access the decompiler window?

**Comment by sad-dev** [comment]
As far as I can tell, there isn't yet a way to register hooks on decompiler results to perform modification before it goes to the decompiler panel (feature request?)

**Comment by lab313ru** [comment]
Yeah, it's a good idea to create a feature request.

**Comment by dragonmacher** [comment]
Closing this in light of #3834

**Comment by lab313ru** [comment]
By the way, I was able to set up my own callback for the decompiler, using this technique:
```java
decompProvider = (DecompilerProvider)TestUtils.getInstanceField("connectedProvider", decompiler);
			
			decompController = (DecompilerController)TestUtils.getInstanceField("controller", decompProvider);
			callbackHandler = (DecompilerCallbackHandler)TestUtils.getInstanceField("callbackHandler", decompController);

			TestUtils.setInstanceField("callbackHandler", decompController, new DecompilerCallbackHandler() {

				@Override
				public void decompileDataChanged(DecompileData decompileData) {
					if (updatingDecompiler) {
						return;
					}
					
					updatingDecompiler = true;
					
					if (decompileData != null) {
						DecompileResults results = decompileData.getDecompileResults();
						
						if (results != null) {
							if (results.decompileCompleted()) {
								HighFunction highFunc = decompileData.getHighFunction();
								if (highFunc != null) {
									decompileFunc(highFunc.getFunction());
								}
							}
						}
					}
					
					updatingDecompiler = false;
				
					callbackHandler.decompileDataChanged(decompileData);
				}

				@Override
				public void contextChanged() {
					callbackHandler.contextChanged();
				}

				@Override
				public void setStatusMessage(String message) {
					callbackHandler.setStatusMessage(message);
				}

				@Override
				public void locationChanged(ProgramLocation programLocation) {
					callbackHandler.locationChanged(programLocation);
				}

				@Override
				public void selectionChanged(ProgramSelection programSelection) {
					callbackHandler.selectionChanged(programSelection);
				}

				@Override
				public void annotationClicked(AnnotatedTextFieldElement annotation, boolean newWindow) {
					callbackHandler.annotationClicked(annotation, newWindow);
				}

				@Override
				public void goToLabel(String labelName, boolean newWindow) {
					callbackHandler.goToLabel(labelName, newWindow);
				}

				@Override
				public void goToAddress(Address addr, boolean newWindow) {
					callbackHandler.goToAddress(addr, newWindow);
				}

				@Override
				public void goToScalar(long value, boolean newWindow) {
					callbackHandler.goToScalar(value, newWindow);
				}

				@Override
				public void exportLocation() {
					callbackHandler.exportLocation();
				}

				@Override
				public void goToFunction(Function function, boolean newWindow) {
					callbackHandler.goToFunction(function, newWindow);
				}

				@Override
				public void doWheNotBusy(Callback c) {
					callbackHandler.doWheNotBusy(c);
				}
				
			});
```

**Comment by astrelsky** [comment]
> By the way, I was able to set up my own callback for the decompiler, using this technique:
> 
> - snip -
>

:eyes: `DecompilerController::callbackHandler` is a `final` and cannot be set. That should **not** work.

**Comment by lab313ru** [comment]
It's reflection things, and it does work!:)

**Comment by astrelsky** [comment]
> It's reflection things access, and it does work!:)

You can't set a final field even by reflection. It will pretend it worked and then you read the value back and it wasn't changed. Maybe it depends on the jdk?

**Comment by lab313ru** [comment]
I'm using `openjdk 11.0.13 2021-10-19`.

**Comment by astrelsky** [comment]
> I'm using `openjdk 11.0.13 2021-10-19`. If you will test my code snippet at your side it would be great.

I don't have anything to test it with as far as actually changing the results goes. Did you read the field back and see it was your anonymous class?

**Comment by lab313ru** [comment]
Yes, my callback overrides are callable. That code snippet works for me.
