### ISSUE TITLE
Callback to access the decompiler results before its output with modifying ability

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#3834]
It would be great to have an ability to modify the decompiler results. The best idea at my and @sad-dev's opinion would be some kind of a callback which receives a `HighFunction` object which can be modified.

**Comment by lab313ru** [comment]
Related: https://github.com/NationalSecurityAgency/ghidra/issues/3832

**Comment by astrelsky** [comment]
```java
import ghidra.app.ExamplesPluginPackage;
import ghidra.app.decompiler.DecompilerHighlightService;
import ghidra.app.decompiler.DecompilerLocation;
import ghidra.app.decompiler.component.DecompilerController;
import ghidra.app.plugin.PluginCategoryNames;
import ghidra.app.plugin.ProgramPlugin;
import ghidra.app.plugin.core.decompile.DecompilerProvider;
import ghidra.framework.plugintool.PluginInfo;
import ghidra.framework.plugintool.PluginTool;
import ghidra.framework.plugintool.util.PluginStatus;
import ghidra.program.model.pcode.HighFunction;
import ghidra.program.util.ProgramLocation;

@PluginInfo(
	status = PluginStatus.UNSTABLE,
	packageName = ExamplesPluginPackage.NAME,
	category = PluginCategoryNames.DECOMPILER,
	shortDescription = "",
	description = "",
	servicesRequired = { DecompilerHighlightService.class }
)
public class IHateNamingThingsPlugin extends ProgramPlugin {

	private DecompilerController controller;

	public IHateNamingThingsPlugin(PluginTool tool) {
		super(tool, true, false);
	}

	@Override
	protected void init() {
		DecompilerProvider service = (DecompilerProvider) tool.getService(DecompilerHighlightService.class);
		controller = service.getController();
	}

	@Override
	protected void locationChanged(ProgramLocation loc) {
		if (loc instanceof DecompilerLocation) {
			// NOTE: This is in the event queue. Gotta go fast or do it in another thread.
			HighFunction hf = ((DecompilerLocation) loc).getDecompile().getHighFunction();
			// do stuff
			controller.refreshDisplay(loc.getProgram(), currentLocation, null);
		}
	}

}
```

**Comment by lab313ru** [comment]
Is your implementation callable after all other calls?
I'm asking that because my first implementation was callable too, but after all my changes the decompiler refreshes display again to apply all updates.

**Comment by astrelsky** [comment]
> Is your implementation callable after all other calls? I'm asking that because my first implementation was callable too, but after all my changes the decompiler refreshed display again to apply all updates.

Hmm, I think I misunderstood what the `refreshDisplay` does. I *think* you could abuse `DecompilerController::doWhenNotBusy` though. Other than that I'm all out of ideas.

**Comment by lab313ru** [comment]
`doWhenNotBusy` calls a `Callback` only once after using this function. It disappears from the queue after execution.

**Comment by astrelsky** [comment]
> `doWhenNotBusy` calls a `Callback` only once after using this function. It disappears from the queue after execution.

Right, but it just gets re-added when the location changes and the function is called again. You actually don't even need to use the location given, you can just use the controller and `DecompilerController::getDecompileData`/`DecompilerController::setDecompileData`.

Then again if your other method does work, then it works.
