### ISSUE TITLE
Cannot disassemble the last instruction with delayed slot

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#3840]
PCodeEmit has the following code:
![image](https://user-images.githubusercontent.com/7189309/148623476-e045b271-9d49-4f33-96e7-e84fab2e4ea9.png)

Input:
1. `startAddress` with some address in any overlayed space

Output:
1. `(OverlayAddressSpace) myspace).getOverlayedSpace()` returns NON overlayed space, but an original `ram:` space

All that breaks decompilation and disassemblying of an overlayed data.

The same thing happens in this code:
![image](https://user-images.githubusercontent.com/7189309/148623670-e550986b-a43b-43cf-b6b3-eebf2660b90d.png)

Example project in the attachment. Try to disassemble last 4 bytes of every overlayed segment in it. It will fail.

[OVERLAYS.EXE.gzf.zip](https://github.com/NationalSecurityAgency/ghidra/files/7832043/OVERLAYS.EXE.gzf.zip)

Original executable binary and overlayed code blocks are here (source code included): https://www.beneaththewaves.net/Downloads/This_Dust_Remembers-OVERLAYS-1.0.zip

**Comment by lab313ru** [comment]
Related: https://github.com/NationalSecurityAgency/ghidra/issues/2680
Related: https://github.com/NationalSecurityAgency/ghidra/issues/1412

**Comment by lab313ru** [comment]
It happens because this code uses non overlayed space name to get the `AddressSpace`:
![image](https://user-images.githubusercontent.com/7189309/148647056-5fd4d13c-8b44-44ef-938d-95eb7bc1ed22.png)

**Comment by lab313ru** [comment]
It looks like it's impossible to create an overlayed address space without using some base address space which gives you wrong (non-overlayed addresses).

**Comment by lab313ru** [comment]
Many many usages of this code template:
![image](https://user-images.githubusercontent.com/7189309/148649875-adef70fe-b4ab-490e-8d70-1fd7ba3af5d9.png)

Which instead of using the overlayed space converts it into the default address space address.

**Comment by lab313ru** [comment]
Should `getAddressInThisSpaceOnly` be used instead?

**Comment by lab313ru** [comment]
To reproduce:
1. Load any program (MIPS cpu for example)
2. Add to Program -> any binary that contains code this the end of the binary, mark it as an overlayed.
3. Try to disassemble the code end in the overlay, you will have this:
![image](https://user-images.githubusercontent.com/7189309/148650600-219cd4c3-4fc0-4b22-809a-5fbdb0d1fbc6.png)

**Comment by lab313ru** [comment]
I've found the cause of the impossibility to disassemble the last instruction:
![image](https://user-images.githubusercontent.com/7189309/148661827-f7151f81-1edc-4e48-95e4-db51fdf45ad4.png)

**Comment by dev747368** [comment]
@lab313ru, could you make a change and see if it fixes your problem?

https://github.com/NationalSecurityAgency/ghidra/blob/56a8346e7842564313eaf4bd64910185de8242ef/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/database/code/CodeManager.java#L472-L479

Change it to something like:

```java
  int fallThruOffset = prototype.getFallThroughOffset(protoInstr.getInstructionContext());
  endAddr = startAddr.addNoWrap(fallThruOffset - 1);
```

**Comment by lab313ru** [comment]
So your fix does work? Haven't tested it yet.

**Comment by lab313ru** [comment]
![image](https://user-images.githubusercontent.com/7189309/149373852-a0b47a49-1600-4ca2-9d55-a781d27eb4bc.png)

Unfortunately, this behavior has appeared. It tries to disasm, but fails the last delayed instruction.

**Comment by lab313ru** [comment]
@dev747368 It looks like it works.
