### ISSUE TITLE
Qustion: BoolNegate Bahaviour on byte

### ISSUE THREAD

**Issue by zt-chen** [NationalSecurityAgency/ghidra#3862]
In this code, it is calculating the Boolean Negative as val^0x1. It only reverts the last bit of the value. However, there are 8bits in the value (a byte). If we have sth like !0x80, it will not have the correct result, which should be 0. 

Does it mean these kinds of scenarios are expected to be handled in the .pspec? e.g. to convert 0x80 to true(0x1)?

https://github.com/NationalSecurityAgency/ghidra/blob/82c42e648cdaa6635f38872412b034610781d927/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/pcode/opbehavior/OpBehaviorBoolNegate.java#L31

**Comment by RootCubed** [comment]
The "Bool" in `OpBehaviourBoolNegate.java` is refererring to the data type of the input/output varnode, not the type of negation (See the section "BOOL_NEGATE" in `/GhidraDocs/languages/html/pcodedescription.html`). This means the function input is guaranteed to be either 0 or 1.
The behaviour you are looking for is in `OpBehaviorIntNegate.java`.

**Comment by zt-chen** [comment]
Ok, got it, thank you. 
So that means the processor definition need to ensure the input be either 0 or 1 right?
