### ISSUE TITLE
Disabling default_symbols

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#3866]
Is there an API, GUI and/or property setting to disable application of default symbols either on a per pspec or global basis? I could have sworn I'd seen an option for this at one point, but I am unable locate it anywhere in the GUI, and the only API I see is for getting them.

In the short term I can simulate this with:
```
for ds in currentProgram.language.defaultSymbols:
    cu = currentProgram.listing.getCodeUnitAt(ds.address)
    removeSymbol(ds.address, ds.label)
    removeFunctionAt(ds.address)
    currentProgram.listing.clearCodeUnits(cu.minAddress, cu.MaxAddress, True)
```

However, it sure would be nice to just be able to prevent these from being applied globally.

**Comment by Pokechu22** [comment]
When importing a file, you should be able to select "Options" and then uncheck "Apply Processor Defined Labels"; is that what you're looking for?

**Comment by bdemick** [comment]
Thanks, exactly what I'm looking for! I had looked just about everywhere else. Looks like this can be done headlessly via the `-loader-applyLabels false` argument when specifying a loader.
