### ISSUE TITLE
extraout_EDX issue

### ISSUE THREAD

**Issue by wothke** [NationalSecurityAgency/ghidra#3873]
**Describe the bug**

Ghidra incorrectly introduces an uninitialized extraout_EDX variable - thereby breaking the generated code - in a scenario where EDX is actually well defined at all times.

**To Reproduce**
I did not create a minimalistic standalone test case but the basic structure of my example code should probably allow to reproduce the effect:

The main function in which the effect occurs (i.e. Ghidra is adding an "extraout_EDX" variable) specifically receives an EDX:4 param in the function signature and also returns EDX:4.

The function contains a switch statement and in exactly one of the case blocks the uninitialized "extraout_EDX" pops up: 

```
    if (uVar5 == piVar6)) {
      if (buf200->byte_0x24 != 0) {
        FUN_00407160(this,buf200);
        FUN_00407310(buf200);
        uVar5 = extraout_EDX;
      }
    }
```
The thing is that FUN_00407160 has a return type of EDX:4, i.e. it specifically sets EDX but for some reason that return value is not even used in the decompiler output (though it is this return value that should be assigned ot uVar5). The second FUN_00407310 is a very simple function that exclusively uses ESP and ECX, i.e. it doesn't touch EDX at all. The use of extraout_EDX at this point just makes no sense.

Actually I did find a hack that I can use in this MickeyMouse case (but which is impractical for scenarious where functions already have their own return values): When I just pipe the unchanged EDX through the FUN_00407310 by adding a respective EDX:4 param & return value, then the "extraout_EDX" disappears and the decompiled code suddenly uses the output from FUN_00407160.

```
        uVar5 = FUN_00407160(this,buf200);
        uVar5 = FUN_00407310(buf200,uVar5);
```

**Expected behavior**
I would have expected that Ghidra realizes that the last change of EDX comes from FUN_00407160 and that FUN_00407310 cannot change EDX. And that consequently there is no need for an "extraout_EDX".

**Environment (please complete the following information):**
 - Win10
 - Ghidra Version: 10.1.1 Build PUBLIC 2021-Dec-21 1319 EST
 - Java Version: 11.0.12

**Comment by ghidracadabra** [comment]
If FUN_00407310 uses a custom calling convention then you will have to tell that to Ghidra explicitly - it does not analyze bodies of callees to determine which registers are used (in general it couldn't do this anyway - consider indirect calls).  My best guess is that the calling convention it's using for FUN_00407310 has EDX listed as a register that a callee is allowed to change and the decompiler is trying to reconcile a use of EDX after the call with the fact that according to the calling convention it can't rely on EDX not changing.

If FUN_00407310 is a short function that only uses two registers you can probably fix this situation by marking it as inline.  To do this, right-click on FUN_00407310 in the decompiler window, select "Edit Function Signature", and then check the "In Line" box in the function attributes.

If that doesn't work, I'd need to know the language ID and compiler ID (which you can find from Help->About <program name> in the code browser), along with the calling conventions assigned to FUN_00407160 and FUN_00407310 (which are shown when you edit a function signature).

**Comment by wothke** [comment]
> calling convention ... EDX listed as a register that a callee is allowed to change

From what I see Ghidra assumes that EDX is a register that may be changed by all the available calling conventions and as you said it cannot generally know what some function actually does.

But having looked at the code I do know what some function does and it would be nice if the person performing the analysis could provide Ghidra with that extra information, e.g. by tagging functions accordingly. This would be a much more elegant way to get rid of phantom "errors" and maintain the readability of the code (I hate duplicated "inlined" code.. eventhough that works as a workaround).

**Comment by ghidracadabra** [comment]
We recently added the ability to specify calling conventions for a single program - search the Ghidra help for "Specification Extensions".  The "prototype" extension type is what you would use.  Note that you'll have to create an xml file for each convention.

Also, in case you were unaware, the file "improvingDisassemblyAndDecompilation.pdf" in the docs/GhidraClass/Advanced directory of a Ghidra installation gives a number of tips and tricks for dealing with imperfect decompilation.  That document predates the specification extensions though so there's no exercise involving them (yet).

I'll go ahead and close this issue.
