### ISSUE TITLE
3 issues related with "DWARF" option

### ISSUE THREAD

**Issue by Muqi-Zou** [NationalSecurityAgency/ghidra#3874]
The following three issues are related to the decompiler when using DWARF option on "-g" compiled code:
The first issue is about the input variable being decompiled as unknown parameter like "in_RDX". For example, for following source code:
```
struct abc {
 int name0;
 int name1;
 int name2;
};


int test( struct abc input){
	if (input.name1 == -1)
		{printf("input is equal to 0xff\n");
			return 2;
		}
		printf("input is less than 0xff\n");
			return 1;
	
}

int main(void) {
	struct abc local ;
	scanf("%ud", &local.name1);
	test(local);

}
```
the decompiled code is like:
```
int test(abc input)

{
  int iVar1;
  undefined8 in_RDI;
  int iStack20;
  
  iStack20 = (int)((ulong)in_RDI >> 0x20);
  if (iStack20 == -1) {
    puts("input is equal to 0xff");
    iVar1 = 2;
  }
  else {
    puts("input is less than 0xff");
    iVar1 = 1;
  }
  return iVar1;
}
```
For the  p-code, if we do not have "RDX = COPY RDI", the binary can be decompiled correctly (try comment "int name0;" ):
```
int test(abc input)

{
  int iVar1;
  
  if (input.name1 == -1) {
    puts("input is equal to 0xff");
    iVar1 = 2;
  }
  else {
    puts("input is less than 0xff");
    iVar1 = 1;
  }
  return iVar1;
}
```

The second one is related with "DuplicateNameException" in "updateFunctionSignatureWithFormalParams". When ghidra tries to "setUniqueParameterNames(gfunc, params)" for parameters with the same two names, it just searches the symbol in the namespace of function only. However, the symbol dwarf parameters may not be in there, which causes voidinputlock flag be set. 
One example is, if we decompile the object file generated from [pngdec.c](https://github.com/FFmpeg/FFmpeg/blob/1c2d8ff92b0cd8dffdf7e775a73edef72aec5da9/libavcodec/pngdec.c#L524) in ffmpeg, the decompiled code is like:
```
// WARNING: Unknown calling convention yet parameter storage is locked
int decode_text_chunk(void)
{

```

The third issue is about the order of parameters when DWARF is applied:
Ghidra will search info from DWARF and build its own parameter in function processSubprogram in DWARFFunctionimporter.java.
The order for Ghidra to build and arrange these parameters in functions are followed by how DWARF entries, which contain these parameters info, lay in the sections. Note order of entries in their sections does not follow the order of parameters. This can be fixed by sorting the parameters based on "DW_AT_decl_line" and "DW_AT_decl_column" info of parameters.
One example is, if we decompile the object file generated from [movenc.c](https://github.com/FFmpeg/FFmpeg/blob/f37e66b3937a914e16d89a9050f042ad89567245/libavformat/movenc.c#L3744) in ffmpeg, the decompiled code is like:
```
int mov_write_int8_metadata(AVIOContext *pb,char *name,char *tag,int len,AVFormatContext *s)
{
  int iVar3 = (int)s;
  if ((iVar3 == 1) || (iVar3 == 4)) {

```
Just note that the original code use "len" in the if condition rather than a structure pointer.

I tested above three cases in latest ghidra, and for your convenience, I attach the binary/object I use as well.
[test.zip](https://github.com/NationalSecurityAgency/ghidra/files/7878347/test.zip)

**Comment by dev747368** [comment]
re issue #3, reordering the formal params of mov_write_int8_metadata, Ghidra is going to go by the ordering in the DWARF info.  We're not going to respect the decl_line or decl_column as ways of ordering the params.

In your binary, the definition of mov_write_int8_metadata is split up into 2 locations (a generic and a more specific, which refers to the generic), each with their own version of the list of formal params.  The more specific location's version of the formal params has the bad ordering for param "s".  Looking at the DWARF information that the toolchain choose to include with the param, I'm guessing that the param wasn't used and it was partially omitted, but in the process it was re-ordered to the end of the param list when being written to DWARF.  (but that is just me guessing)

I'm still poking around with this and the other issues.

**Comment by dev747368** [comment]
re issue 2 (pngdec and DuplicateNameException), there is some bad data in the DWARF.

If you use `readelf -wi pngdec`
```
<2><6513>: Abbrev Number: 92 (DW_TAG_formal_parameter)
    <6514>   DW_AT_abstract_origin: <0x58ad>
 <2><6518>: Abbrev Number: 92 (DW_TAG_formal_parameter)
    <6519>   DW_AT_abstract_origin: <0x58ad>
```
again, we can see a split definition (abstract and concrete DIEs), where the param list at the concrete instance has some weird data, where it duplicates the reference to the abstract param 0x58ad.

The change that I made to handle the mis-sorted parameter issue will have a side-effect of 'fixing' this issue as it will wind up discarding the extra reference to the parameter when it reorders the params.

**Comment by dev747368** [comment]
@Muqi-Zou the 2 DWARF issues should have been fixed by the commit.  The first issue you mentioned (a struct that is passed in registers) isn't specific to DWARF.  I would suggest starting a new github issue with just that problem if it is still impacting you.
