### ISSUE TITLE
How to export symtab section

### ISSUE THREAD

**Issue by kkomakai** [NationalSecurityAgency/ghidra#3880]
I have analyzed a stripped ELF library (no .symtab section) and Ghidra generates a symbol table which I can view using the "Display Symbol Table".
I would like to re-export the library from Ghidra but with a .symtab section generated from the symbol table that Ghidra has created.
Is there a way to do this?

**Comment by dev747368** [comment]
Not really.  The current export feature does not handle changes to the footprint of the original binary, just changes to bytes in the program (ie. patching instructions / data)
