### ISSUE TITLE
Structure editor's "undefined *" auto-completion sucks

### ISSUE THREAD

**Issue by wothke** [NationalSecurityAgency/ghidra#3881]
**Describe the bug**
It seems to be near impossible to change some incorrectly typed field back to the "undefined" state. But instead, each time I type in "undefined" as the new type, the silly auto-completion changes my input to "undefined *" making it impossible to just undefine the uncorrectly typed field..

Example: The existing structure contains 8 bytes that have previously been incorrectly typed as two separate dwords:

536    4  ddw  dword mbr_0x218
540    4  ddw  dword mbr_0x21c

Lets say I have meanwhile realized that these two fields in fact represent one double, i.e. I have to get rid of the dword at offset 540 so that I can then change the type of the field at offset 536 to double. (Unfortunatly the editor does not allow me to directly change the first field and just overwrite/elimitate the definition of
2nd field - which would be my preferred option).

I can change the second field to "undefined1" which will render the next 3 bytes "undefined", but this will still block the 1st byte - blocking me from being able to extend the size of the previous field from 4 to 8 bytes.. this is just super annoying!

**Environment (please complete the following information):**
 - OS: Win10
 - Ghidra Version: 10.1.1

**Comment by dragonmacher** [comment]
> But instead, each time I type in "undefined" as the new type, the silly auto-completion changes my input to "undefined *" making it impossible to just undefine the uncorrectly typed field..

When you type 'undefined', the auto-complete shows you all matches with the first entry being 'undefined *'.   If you wish to take only the text you have typed, 'undefined' in this case, then press Escape before you press Enter.  This will close the auto-complete drop-down, allowing you to tell the editor to use only what you have typed.

Regarding the ability to edit the type such that it consumes what is required of the following types, that would be a new feature.  Likely, we would have to show a popup dialog confirming that you would like to overwrite existing types.

**Comment by wothke** [comment]
> When you type 'undefined', the auto-complete shows you all matches

From a UI usability perspective it would be nice if the built-in "undefined" would also appear somewhere in that list - it makes no sense that the 100% match currently is not even offered as an option.

Thanks for the "escape" workaround :-)
