### ISSUE TITLE
unnecessary mapping of byte write to CONCAT based int write

### ISSUE THREAD

**Issue by wothke** [NationalSecurityAgency/ghidra#3884]
**Describe the bug**
In my test-case the original ASM clearly sets one specific byte to 1.
```
        0040887b c6 44 24        MOV        byte ptr [ESP + local_11c[0].b4],0x1
                 13 01
```
The respective "local" data structure used here is basically an array of ints but since some byte are written individually (like in the above example) I modelled the "ints" as 4-byte structs with respective bytes named b1, b2, b3, b4. Clearly the ASM code correctly identifes the specific byte that needs to be set to 1. 

The correct decompiler output for this circumstance should be:

`              local_11c[0].b4 = 1;
`
but instead the actual, overly complicated output here is:

`              local_11c[0] = CONCAT13(1,local_11c[0]._0_3_);
`

The original ASM was at no point an int based operation and it makes no sense that the decompiler makes it look as if it had been (especially since the target data structure has that specific byte modelled).

Worse, within the very same function an almost identical write:

```
        00408812 c6 44 24        MOV        byte ptr [ESP + local_11c[6].b2],0x0
                 29 00
```
*is* correctly decompiled as:

`            local_11c[6].b2 = 0;
`

For some reason the decompiler handles the very same situation differently even within the same function. This makes no sense.

**Expected behavior**

`              local_11c[0].b4 = 1;
`

**Environment (please complete the following information):**
 - OS: Win10
 - Ghidra Version: 10.1.1

**Comment by Wall-AF** [comment]
Even editing the stack frame to have 4 individually named variables (1 byte each) doesn't help.  It actually leads to further confusion as one of the new variables is used within a `CONCAT` but isn't shown to be assigned to beforehand!
