### ISSUE TITLE
Ability to zoom on each windows

### ISSUE THREAD

**Issue by ImNotAVirus** [NationalSecurityAgency/ghidra#389]
**Is your feature request related to a problem? Please describe.**
I think it would be nice if people could zoom in and zoom out on the different windows like on function graph.
This feature would certainly be useful during conferences or videos presenting Ghidra.

**Describe the solution you'd like**
Add a button on the toolbar which allow to zoom in and out on some windows (Listing and Decompiler first of all).
Also bind key shortcuts Ctrl + and Ctrl - for, respectively, zoom in and zoom out when a window is focused.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by OverStruck** [comment]
I'd like to see this as well.

**Comment by Seluj78** [comment]
Up ?

**Comment by travelsonic** [comment]
Indeed, 220% agreed this is something I think would be beneficial as well (not just in sharing, but even in working)

**Comment by Ruaghain** [comment]
Yes, please add this. Screen resolutions are getting higher and I am unfortunately getting older. Being able to see what I'm doing would be beneficial.

**Comment by travelsonic** [comment]
But ... that's not "zooming," per-se that's adjusting font sizes, which is still useful but requires navingating to settings -it'd be nice if we could resize through something like ctrl+ mouse scroll wheel. to zoom where you are w/o having to go through settings to change font size (to just have to change them back manually later).

**Comment by dragonmacher** [comment]
We still do not have window zooming.

But, you can now (as of 10.3) change fonts via keyboard shortcuts in the Listing, Decompiler and Byte Viewer by pressing `Ctrl-+` and `Ctrl--`.   For the rest of the system fonts, you can adjust them from the theme configuration dialog accessible from the Front End menu via `Edit` -> `Theme` -> `Configure`.   This particular dialog is not modal, so it can be left open while using Ghidra.
