### ISSUE TITLE
AutoAnalysis: Demangler Microsoft - Apply Function Signatures option no effect?

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#3892]
Does this option do anything? I have not seen any difference with and without this box toggled.

**Comment by dragonmacher** [comment]
At a cursory glance, it appears that the option is indeed broken for the Microsoft Demangler.

**Comment by sad-dev** [comment]
I would also like to request for an option to _not_ set calling conventions based on demangled names - in my experience, the "cdecl" in the demangled name usually isn't a good indicator of the actual convention.
