### ISSUE TITLE
Change program Language?

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#3896]
I want to change language of already created project. How can I do that?
My new language is just a fork of one existing, but with some custom asm instructions added.

**Comment by lab313ru** [comment]
Already found a solution:
```java
SleighLanguageProvider lngProv = new SleighLanguageProvider();
LanguageID langId = new LanguageID("new:lang:id");
Language lng = lngProv.getLanguage(langId);
CompilerSpecID specId = new CompilerSpecID("default");

program.setLanguage(lng, specId, false, monitor);
```

**Comment by Pokechu22** [comment]
You can also right-click on the program in the main ghidra window and select "set language".
