### ISSUE TITLE
Get stack references of a function from the java api

### ISSUE THREAD

**Issue by felberj** [NationalSecurityAgency/ghidra#390]
How can one access all references to the stack (also outside of its frame) a [function](http://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Function.html) has via the Java Plugin API?

Example: This instructions write values **outside** of the stack frame of the function:

![](https://i.stack.imgur.com/L5ERd.png)

(I asked this question on [stackoverflow](https://reverseengineering.stackexchange.com/questions/21071/get-stack-references-in-ghidra-of-a-function-from-the-java-api) but it seems the community there is not yet large enough. I will update the question there if you reply here)

**Comment by ghidra1** [comment]
Assuming stack analysis has been performed and the function has been marked with stack references as shown above, you can iterate of the references "from" the body of the function (i.e., AddressSetView).  The references returned would need to be filtered as other type of references would also be returned.  Although there are a variety of ways to obtain references here is one example:

```
Function f;
Program p;
ReferenceManager refMgr = p.getReferenceManager();
    for (Address fromAddr : refMgr.getReferenceSourceIterator(f.getBody(), true)) {
        for (Reference ref : refMgr.getReferencesFrom(fromAddr)) {
            if (ref.isStackReference()) {
                // ref is a stack reference...
            }
        }
}
```
