### ISSUE TITLE
Restore Project crashes on M1 Mac

### ISSUE THREAD

**Issue by ViRb3** [NationalSecurityAgency/ghidra#3904]
**Describe the bug**
Restoring a packed Ghidra project `.gar` crashes during extraction, making it impossible to open an already packed project. The issue comes from `net.sf.sevenzipjbinding`, which apparently does not support arm64 on macOS (M1) yet. Ghidra 10.0.4 does not have this problem.

**Log**
[crash.txt](https://github.com/NationalSecurityAgency/ghidra/files/7921013/crash.txt)

**Environment (please complete the following information):**
 - OS: macOS 12.1 arm64 (M1)
 - Java Version: 17
 - Ghidra Version: 10.1.1
 - Ghidra Origin: ghidra-sre.org distro

**Comment by ryanmkurtz** [comment]
Perhaps it can be tricked into thinking it's x86 so Rosetta 2 kicks in.

**Comment by ViRb3** [comment]
I don't think you can do this unless you run the entire instance of Ghidra under Rosetta 2, which would be very bad for performance. 

Could maybe add a fallback to a pure Java decompressor for unsupported platforms, similar to how it was done pre-10.1? That may be faster than emulating decompression using Rosetta 2 anyway.

**Comment by ryanmkurtz** [comment]
Unless you built your own native binaries using gradle, the decompiler and other native binaries that ship with Ghidra are already running under Rosetta 2.  We don't build and ship `mac_arm_64` binaries with our distributions.

If you were to run an x86 JDK on your M1, then this error would likely go away with no tricking necessary (since Java will report it's running on an x86 machine).  This is probably the performance concern you are talking about though.

**Comment by emteere** [comment]
As a workaround, you can also just manually .zip up your <project>.gpr and associated <project>.rep directory.  Then use unzip or jar from the command line to restore your project to the correct location.
Not as integrated, but it should work for now.

**Comment by ViRb3** [comment]
> Unless you built your own native binaries using gradle, the decompiler and other native binaries that ship with Ghidra are already running under Rosetta 2. We don't build and ship `mac_arm_64` binaries with our distributions.
> 
> If you were to run an x86 JDK on your M1, then this error would likely go away with no tricking necessary (since Java will report it's running on an x86 machine). This is probably the performance concern you are talking about though.

I have executed the `support/buildNatives` script, which if I understood correctly will build arm64 natives and use them without any emulation involved. But apart from that, yes, it was the Java emulation slowdown that I was referring to. Would do everything to squeeze out the maximum performance out of Ghidra :)

> As a workaround, you can also just manually zip up your <project>.gpr and associated <project>.rep directory. Then use unzip or jar from the command line to restore your project to the correct location.
> Not as integrated, but it should work for now.

I indeed tried manually unzipping an existing archived project, but Ghidra would not recognize the `gpr` inside of it. I suppose if I zipped the folders myself instead of using the "archive project" option, then it would work, but a lot of my projects are already archived the Ghidra way. I will keep this suggestion in mind though, thank you.
