### ISSUE TITLE
Python API: How to query name of PC Register?

### ISSUE THREAD

**Issue by pjsoberoi** [NationalSecurityAgency/ghidra#3919]
I would like to get the name of the program counter register programmatically in Python. For example on x86 I would like to return "eip" etc. 

I have the following Python code for getting the stack register:

>     prog = getCurrentProgram()
>     spec = prog.getCompilerSpec()
>     reg = spec.getStackPointer()

But I don't see a way get PC. Thanks in advance.

**Comment by mumbel** [comment]
should be `reg = prog.getLanguage().getProgramCounter()` looks like

**Comment by pjsoberoi** [comment]
Yes that was it. Thanks again.
