### ISSUE TITLE
10.1.2 Release Hash Incorrect

### ISSUE THREAD

**Issue by nickg-ca** [NationalSecurityAgency/ghidra#3924]
**Describe the bug**
The 10.1.2 release has the hash listed as 64860a83d53aca19001d0026e5daf7db05218942dcbbf1ef0b1638242a09b8f6

**To Reproduce**
Download the 10.1.2 release zip file, and the SHA-256 hash is ac96fbdde7f754e0eb9ed51db020e77208cdb12cf58c08657a2ab87cb2694940.

**Expected behavior**
I'd expect the hash in the release notes to match the hash of the zip file.

**Screenshots**
n/a

**Attachments**
n/a

**Environment (please complete the following information):**
n/a

**Additional context**
I downloaded this twice just to double check it wasn't a corrupt file on my end, and obtained the same hash twice.

**Comment by ghidra1** [comment]
Fixed.  Copied incorrect hash.  Thanks for pointing this out.
