### ISSUE TITLE
Feature Request: GhidraScript ask_ API defaultValue

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#3937]
**Is your feature request related to a problem? Please describe.**
1.) It is sometimes desirable to call the ``askInt/askLong/askDouble`` APIs with a suggested value
2.) The suggested value may vary over runs of the ``GhidraScript``. In other words, the current ``askString`` only uses ``defaultValue`` the first time, and instead suggests the last used input; in some cases, I might want to dynamically decide what value to default to
e.g. 
```
currentName = tokenAtCursor.toString(); // Will vary across different runs
newName = askString("New Name", "", "__test__" + currentName)
```

**Describe the solution you'd like**
Extensions to the API of the form
``T askT(String title, String message, T defaultValue, bool usePrevious=True)`` which defaults to the previous input if usePrevious (or whatever name is reasonable) is true and defaultValue otherwise.

**Describe alternatives you've considered**
There are ways to hack around it, but the API extension seems reasonable to me

**Comment by dragonmacher** [comment]
I think we can address this by adding this method:

```
public void setReusePreviousChoices(boolean reuse);
```

This would allow you to toggle the use of previous choices as desired in your script.
