### ISSUE TITLE
M68000 TRAP instruction decompiles incorrectly

### ISSUE THREAD

**Issue by philpem** [NationalSecurityAgency/ghidra#394]
**Describe the bug**
The decompiler incorrectly displays the trap number as a parameter.

**To Reproduce**
1. Load a 68000 binary which contains TRAP instructions.
2. Decompile it.
3. Note that the parameter to the trap() function is neither the trap number nor the vector address.

**Expected behavior**
Decompiled trap() call parameter is either the trap number (direct parameter) or trap vector address.

**Screenshots**
Disassembly:
```
        00000584 4e 4e           trap       #0xe
```

Decompiled output:
```
trap(0x2e);
```

Expected output:
```
One of the following:
  trap(0xe);
  trap(14);
  trap(0xb8);
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: 11
 - Ghidra Version: 9.0.2

**Comment by lab313ru** [comment]
Hm... What are original bytes? 4E 4E?

**Comment by mumbel** [comment]
The manual states the 4 bit immediate Operand (vector) is added to 32 to get the vector number.  The 32-47 vectors are the TRAP #0-15 instruction vectors.  From an asm pov `TRAP #n` makes sense, but in pcode it looks like the idea is you'd want the actual vector it's going to `trap(n+32)`

**Comment by philpem** [comment]
> The manual states the 4 bit immediate Operand (vector) is added to 32 to get the vector number. The 32-47 vectors are the TRAP #0-15 instruction vectors. From an asm pov `TRAP #n` makes sense, but in pcode it looks like the idea is you'd want the actual vector it's going to `trap(n+32)`

That's true -- but the traps themselves are numbered from 0 to 15. I'd argue the instruction convention should be followed, because then you can go directly from seeing `trap(15)` in the code, to knowing that you should be looking for the `TRAP15` vector.

In practice if you have e.g. a ROM with a complete vector table, you'd load a structure at address 0 (start of vectors) which defines names for all the vector entries -- in that case if you wanted to follow a `TRAP`, you could just type `TRAP15` in the 'goto label' window.

An acceptable alternative would be to have the output be `trap((n+32)*4`, which would give the vector address. This would make double-clicking on the address move the disassembly view to the trap vector, which can then be followed to the handler function.

As things are, you have to take the parameter to `trap()` and either subtract 32 to get the trap number, or multiply by four to get an address. This is tedious if it has to be done repeatedly.

**Comment by philpem** [comment]
> Hm... What are original bytes? 4E 4E?

Yes.

**Comment by lab313ru** [comment]
Vectors table starts from 0, but in case of Sega Mega Drive there are user vector numbers starting 0x0F as I remember.

**Comment by philpem** [comment]
Exactly this @lab313ru. 

I've created PR #497 which removes the "add 32", so will show the user-vector number.
