### ISSUE TITLE
using "find" or "copy" with section in "pre-comment" doesn't work

### ISSUE THREAD

**Issue by wothke** [NationalSecurityAgency/ghidra#3946]
**Describe the bug**
When selecting a word in a "pre-comment" shown in the "decompiled code view" and using "ctrl-f" to search that word in the remaining decompiled code, the behavior of the respective "Decompiler Find Text" dialog is absolutely braindead:

Rather than using the actually selected word, the complete content of the comment is used as the "Find:" text.. it should be obvious that this is an absolutely useless "feature"! The same problem seems to also affect the regular copy/paste functionality - which also copies the complete comment rather than copying the explicitly selected word.

Adding insult to injury the layout of the "Decompiler Find Text" becomes unusable when an "overly long" text (like some random pre-comment) is among the texts of its "find" history; It seems that if one of the texts in the respective "Find:" input/dropdown field exceeds the width of the dialogs default width, then the height of the input/dropdown field collapses to 3-4 pixels - rendering is absolutely useless (this situation can be worked around by manually making the dialog wider .. but UI usability wise this is just bad).

**Expected behavior**
When some subset of a comment has been specifically selected, then operations like "search" and "copy" should obviously use that selected subset and NOT the complete comment.

There should never be a situation where the "Decompiler Find Text"'s "Find:" field collapses to some unusable form.

**Environment (please complete the following information):**
 - OS: Win10
 - Ghidra Version: 10.1.1

**Comment by dragonmacher** [comment]
This may be a regression.  I will take a look.

**Comment by dragonmacher** [comment]
I am seeing this with the `Find...` action, but not yet with the `Copy/Paste` actions.   

Do you have a particular set of instructions to reproduce the issue for `Copy/Paste`?

**Comment by wothke** [comment]
> Do you have a particular set of instructions to reproduce the issue for `Copy/Paste`?

my mistake.. I had pressed copy after CRTL-F and the focus had already switched to the "Find:" field, i.e. I had copied the text from the find-field instead of from the original location..

**Comment by dragonmacher** [comment]
OK.   I see the issue.  I'm pretty sure this has never worked.   I'm going to try to get a simple fix in place for this.

**Comment by wothke** [comment]
Just out of curiousity.. I've noticed that the various bug-reposts that I have posted during the past 1-2 weeks seem to land in 2 different buckets.. there are the UI usability bugs ones (like this one) where I am getting a response very quickly (thanks for that!) but then there are the more "serious" problems (e.g. flaws of the decompiler) where there seems to be no reaction whatsoever.. 

is there some dedicated team looking into respective bug reports or is this some kind of bottleneck situation where the one person familiar with a specific sub-system is just busy with something else?

**Comment by dragonmacher** [comment]
> is there some dedicated team looking into respective bug reports 

Yes, we are all dedicated :wink:

Our trend for responding to issues has been to more immediately address critical items.  Along with those, we also are able to address items that are relatively easy to fix, such as the UI items you've mentioned.   Many of the outstanding issues we still have are those that are nuanced and require a more in depth analysis to triage.  Unfortunately, the work required to address those items ends up slowing down the entire process.  I envision a future with an improved ticket processing, including faster response times.
