### ISSUE TITLE
struct fields are reset when changing their type from within the decompiled code view

### ISSUE THREAD

**Issue by wothke** [NationalSecurityAgency/ghidra#3951]
**Describe the bug**
Suppose a function uses a struct A that has a field "myLen" which has type "int".

When changing the type of that "myLen" field from int to uint using the "structure editor" then the behavior is as expected, i.e. the type changes - any nothing else. 

But when performing the "same" change via "CTRL-L" from within the "Decompile" view, not only the type is changed but the field loses its existing "myLen" name and is reset to a generic "field.." name.. this is annoying.

**Expected behavior**
As long as a retyped variable still fits the storage of the old type, an existing field name should not be reset by the "Retype Field" functionality,

**Environment (please complete the following information):**
 - OS: Win10
 - Ghidra Version: 10.1.1

**Comment by mumbel** [comment]
this was fixed in 10.1.2  https://github.com/NationalSecurityAgency/ghidra/issues/3783
