### ISSUE TITLE
Using code of the exe to extract encrypted files

### ISSUE THREAD

**Issue by marosis** [NationalSecurityAgency/ghidra#3958]
Hello is somehowly possible to extract encrypted binary files using exe wich is associated with that file? I've found all needed code for that, but don't know how do i import that file. File is encrypted using blowfish in CBC mode and i would like to use the exe code to see data of the encrypted file. Maybe small discussion i would appreciate. I can send some screenshots if they are needed

**Comment by marosis** [comment]
Maybe small discussion i would appreciate

**Comment by ryanmkurtz** [comment]
You would typically do this by dynamically executing the executable with a debugger up to the point your data gets unpacked/unencrypted in memory, and then save off that memory of interest. Ghidra does not provide an automated way to do this.  I suggest you ask this question in a more general reverse engineering forum, like [here](https://www.reddit.com/r/ReverseEngineering/).  There are likely better tools for the job than Ghidra for this type of thing.
