### ISSUE TITLE
Ablity to load external libraries after loading a project

### ISSUE THREAD

**Issue by redragonx** [NationalSecurityAgency/ghidra#396]
**Is your feature request related to a problem? Please describe.**
I'm not sure if it's currently possible to load external libraries after importing a file. When importing a file, you are able to load external libraries as shown below. 

![image](https://user-images.githubusercontent.com/3073252/55836929-21a14480-5add-11e9-8085-61dd671e8cee.png)

But what happens if you decided to analyze a library the code is calling, after the fact? E.G. Winsock

I don't see an option to analyze libraries in the codebrowser.

**Describe the solution you'd like**
Perhaps consider a menu entry in the analysis menu. 

**Additional context**
Not sure if I'm missing something obvious?

**Comment by redragonx** [comment]
Apparently you could also just import the libraries and link them afterwards.

**Comment by Ristovski** [comment]
@redragonx Could you elaborate on the 'import and link afterwards'?
Is that a feature that Ghidra has (and if so, how does one "link" the library?), or is that just an idea of how it could be implemented?

**Comment by pedrib** [comment]
I'd like to add to this with some examples.

I have imported a binary into a Ghidra project and analysed it. After a while, I realised that winsock functions were not being recognised (shown as below):
![image](https://user-images.githubusercontent.com/5311656/55900858-594de080-5bf2-11e9-9dfc-617893eaf393.png)

I then added wsock32.dll as an external library and made Ghidra analyse it.

Now when you click the WSOCK function handle in the first image, it goes into this:
![image](https://user-images.githubusercontent.com/5311656/55900935-7c789000-5bf2-11e9-9a42-339a5d5e7527.png)

And then if you click on the red function name it goes into the correct function in wsock32.dll:
![image](https://user-images.githubusercontent.com/5311656/55900973-9619d780-5bf2-11e9-825b-3b7d9f2aff18.png)

However, the function names in the binary listing (as shown in the first image) have not been updated.

**Comment by nemanjan00** [comment]
Hi, not sure if my problem is the same as this one. 

I have batch imported full fs of device I am analyzing and all of the necessary libs are inside project. 

But, when I analyze binary, all import are in `EXTERNAL` instead of appropriate lib and I can not see function code. 

![2019-07-13-165331_459x240_scrot](https://user-images.githubusercontent.com/448151/61173116-f96b2b00-a58e-11e9-8636-6965ff312a4c.png)

**Comment by mumbel** [comment]
@nemanjan00  once you have set all the shared libraries you care about to their external binary, you can run the `FixupELFExternalSymbolsScript` plugin

**Comment by nemanjan00** [comment]
@mumbel, thanks! Worked!

**Comment by Wall-AF** [comment]
How can we do the same for 16-bit Windows NE files?

**Comment by sollyucko** [comment]
FWIW, what worked for me is dragging the symbols from `<EXTERNAL>` to the correct library (ctrl+click and shift+click work).

**Comment by pedrib** [comment]
I also found another way to fix this.

First open the "External Programs" window. You'll see the various imported libraries there. Right click, then select "Set External Name Association" and link it to the library (which you must have previously imported into Ghidra).

Then finally go to "Script Manager", then choose the "Symbol" folder and run FixupELFExternalSymbolsScript.java.

Done!

**Comment by nemanjan00** [comment]
I think java is language plugin is written in

**Comment by draeath** [comment]
They are pointing at ELF in the filename, which is a Linux binary (contrast with, say, PE)

**Comment by pedrib** [comment]
Speaking of which, is there an equivalent solution for PE?

**Comment by MaKiPL** [comment]
bump for PE

**Comment by doraeric** [comment]
I encountered the import problem and found this issue.
In Ghidra v11.1.2, there is no `FixupELFExternalSymbolsScript.java` script. It is in `Analysis` -> `One Shot` -> `External Symbol Resolver` now.
