### ISSUE TITLE
Renaming a structure member in the decompiler does not mark the structure as "dirty"

### ISSUE THREAD

**Issue by Tim---** [NationalSecurityAgency/ghidra#3966]
**Describe the bug**
When a structure is associated to a DataType archive, a local change should mark the structure as "dirty", so that it can be committed to the archive (a little arrow to the right in the Data Type Manager should appear).

This works if we make changes in the structure editor, but renaming a field in the decompiler view does not. Since the structure is not marked as "dirty", we can't commit it to the archive.

**To Reproduce**
1. Open a program that uses structures. 
2. Create a datatype archive, pick a structure used in your program and associate it.
3. Rename a field in the Structure Editor and save. The structure is correctly marked as dirty in the Data Type Manager, and you can commit it to the archive.
4. Find a function that handles this structure and rename a field. Nothing happens in the Data Type Manager.

**Expected behavior**
The structure should be marked as dirty.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Java Version: openjdk version "11.0.13"
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by ghidra1** [comment]
Have you tried right-clicking in the datatype tree on the program node and selecting the popup menu action _Reset Sync Indicators For -> archive_?  This will hopefully identify those types which can be committed.  I noticed similar behavior the other day while working in this area and will explore more.  I understand the cause (`DatatypeManagerDB.updateLastChangeTime()` sets the last sync time on the associated archive which seems wrong and forces the need to manually reset datatype sync indicators).

**Comment by ghidra1** [comment]
A fix is in the works for 10.2
