### ISSUE TITLE
Question on 16-bit x86: STOSD.REP ES:EDI

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#3968]
The bytes ``66 f2 67 ab`` disassemble to STOSD.REP ES:EDI on 16-bit x86. The resulting Pcode mentions the registers EDI, EAX, ECX. Is this a bug?

**Comment by GhidorahRex** [comment]
No, this is not a bug. The 66 prefix tells the processor that this instruction uses a 32-bit operand, and the 67 prefix tells the processor to use 32-bit addressing.
