### ISSUE TITLE
Question:  What is the use case of .keep file data/diff

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#3973]
For the various reasons when working with a versioned image, a .keep file might be produced.

 I understand its to retain the currently saved image when the image checkout is undone.   What are the uses cases for using this keep file.  Mostly wondering if there is some mechanism to get the changes that might be in a .keep file that were not in the versioned image.  My thinking is setting up version tracker to try to grab as much as possible?  Can you merge it back onto the versioned file?

**Comment by ghidra1** [comment]
A .keep file is a non-versioned copy of a domain file (i.e., Program).  The most you can do with it for recovery purposes is to Program Diff with a current versioned checkout and apply selected differences.  Program Diff really only handles differences visible within the listing and not datatype differences.
