### ISSUE TITLE
from ghidra.python.PythonScript import getReferencesTo  TypeError why? 

### ISSUE THREAD

**Issue by nocbtm** [NationalSecurityAgency/ghidra#3979]
```
>>> name = "main"
>>> func = getGlobalFunctions(name)[0]
>>> getReferencesTo(func.getEntryPoint())
array(ghidra.program.model.symbol.Reference, [From: Entry Point To: 000194c0 Type: EXTERNAL Op: -1 DEFAULT])
>>> getReferencesTo
<bound method ghidra.python.PythonScript.getReferencesTo of python>
>>> from ghidra.python.PythonScript import getReferencesTo
>>> getReferencesTo(func.getEntryPoint())
Traceback (most recent call last):
  File "python", line 1, in <module>
TypeError: getReferencesTo(): expected 2 args; got 1
```

**Comment by astrelsky** [comment]
> ```
> >>> name = "main"
> >>> func = getGlobalFunctions(name)[0]
> >>> getReferencesTo(func.getEntryPoint())
> array(ghidra.program.model.symbol.Reference, [From: Entry Point To: 000194c0 Type: EXTERNAL Op: -1 DEFAULT])
> >>> getReferencesTo
> <bound method ghidra.python.PythonScript.getReferencesTo of python>
> >>> from ghidra.python.PythonScript import getReferencesTo
> >>> getReferencesTo(func.getEntryPoint())
> Traceback (most recent call last):
>   File "python", line 1, in <module>
> TypeError: getReferencesTo(): expected 2 args; got 1
> ```

The reason is explained above. You overwrote the global method bound to your `PythonScript` instance and then attempted to use it as an unbound method without giving it the `PythonScript` parameter.

**Comment by nocbtm** [comment]
I seem to understand.

**Comment by astrelsky** [comment]
> I seem to understand.

If you do the following it should be a bit more obvious

```python
getReferencesTo
 from ghidra.python.PythonScript import getReferencesTo 
getReferencesTo
```
The first time it'll say bound method and the second time it should say unbound method. I haven't actually checked myself though.
