### ISSUE TITLE
Update Gson to version 2.9.0

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#3992]
[Gson 2.9.0](https://github.com/google/gson/releases/tag/gson-parent-2.9.0) has been released. It fixed google/gson#1875. After updating to 2.9.0, I think we can remove `--add-opens java.base/java.util=ALL-UNNAMED`, which was previously [added](https://github.com/NationalSecurityAgency/ghidra/issues/3355#issuecomment-909326321) to workaround the illegal access issue.

**Comment by ryanmkurtz** [comment]
Nice, it pained me to add that JVM argument...thanks!
