### ISSUE TITLE
Unsaved work is lost when Windows automatically reboots e.g. after updating

### ISSUE THREAD

**Issue by GMMan** [NationalSecurityAgency/ghidra#3994]
**Describe the bug**
When Windows reboots itself (usually due to Windows Update), there is no opportunity given to save current changes prior to the reboot. There's something different between Windows-initiated reboot and Ghidra crashing, where in the latter case some recovery files are generated and restored upon next run, and in the former there's nothing. This causes a lot of loss of work because I tend to not save that often so I don't lose my undo stack, which saving clears.

**To Reproduce**
1. Wait for Windows to install updates that require a reboot
2. Open up any program in Ghidra
3. Relabel some functions, or otherwise make changes; don't save
4. Wait for Windows to automatically reboot
5. Reopen the same program in Ghidra after the reboot; observe the change is missing

**Expected behavior**
Ghidra should either retain recovery files on reboot so changes can be restored after the reboot, or delay the reboot until all unsaved changes are saved or discarded.

**Environment:**
 - OS: Windows 10 20H2
 - Java Version: 16.0.1
 - Ghidra Version: 10.1.1
 - Ghidra Origin: GitHub release

**Comment by d-millar** [comment]
Assuming you have access to the group policy editor on your machine, I might suggest disabling auto-restart on update:

1. Click on the “Start” button and type
gpedit.msc
press Enter.
2. In the Local Group Policy Editor, go to
Computer Configuration ->
->Administrative Templates->
-> Windows Components->
-> Windows Update
3. Double-click on “No auto-restart with automatic installations of scheduled updates”.
4. Select "Enabled", and then click "OK".
5. Close the local group policy editor.

**Comment by GMMan** [comment]
I'm using the home version of Windows, so no group policy and I think the registry key associated with it is completely ignored.

**Comment by d-millar** [comment]
Hmmmm, have you tried modifying the “active hours”: Home > Update & Security > Windows Update > Change active hours?

(I realize I’m still sidestepping your request, but….)

**Comment by d-millar** [comment]
Understood - will mention it to the rest of the team on Monday, but I’m not terribly hopeful.  I  don’t think Java gets notified on shutdown, but I could be completely wrong about that.  Fingers crossed!

**Comment by ryanmkurtz** [comment]
https://www.baeldung.com/jvm-shutdown-hooks

**Comment by ghidra1** [comment]
Ghidra periodically generates a snapshot of any Program currently open for update which has been modified.  This is intended to aid in the recovery from a crash or unexpected power-down.  This mechanism will not help for an active transaction or other tools such as the Debugger.  The default snapshot period is every 5 minutes (this time may be adjusted via the Project window Tool Options->Recovery setting).  When a program is re-opened with such recovery data the user will be prompted with a "Crash Recovery Data Found" dialog.

**Comment by GMMan** [comment]
I'm aware of that feature, however there's something different about a Windows-initiated shutdown that causes Ghidra to act as if all the save prompts have been answered "don't save" rather than a crash.

**Comment by ghidra1** [comment]
I think I may have found the issue in the BufferMgr shutdown hook which appears to dispose all open instances without retaining recovery data.  So it would appear a clean JVM shutdown would cause the recovery data to be lost.  I will put in ticket to address this.

**Comment by ghidra1** [comment]
Fix is in the works for Ghidra 10.2
