### ISSUE TITLE
FunctionID no longer working correctly

### ISSUE THREAD

**Issue by wburton-intel** [NationalSecurityAgency/ghidra#4000]
**Describe the bug**
Between versions 10.0.4 and 10.1 Function ID stops detecting Visual Studio 2019 memmove & memset

**To Reproduce**
1) Build a program using Visual Studio 2019 that uses memset and/or memmove
  - this may apply to other versions of VS, I haven't tested
  - I was building a test driver, I assume the issue also applies to dlls & executables
2) Drop the resulting file into Ghidra and auto-analyse
3) Look at the list of functions. In 10.0.4 and below memmove and memset are correctly identified. In 10.1 and above they are not
 - I tested on 10.1, 10.1.1 and 10.1.2 (current latest)

**Expected behavior**
Memmove and memset should be properly identified

**Screenshots**
From 10.0.4:
<img width="513" alt="Ghidra_1004_memmove" src="https://user-images.githubusercontent.com/78208397/154065630-ee189dcc-5fe6-40a9-b492-fa239cfd0e6f.png">
From 10.1
<img width="491" alt="Ghidra_101_memmove" src="https://user-images.githubusercontent.com/78208397/154065633-ec581f67-a96c-4129-8a7a-1f1d15d1c17a.png">

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 14.0.1
 - Ghidra Version: 10.0.4 and 10.1
 - Ghidra Origin: official distro (Github zip download)

**Additional context**
Copying the contents of Ghidra\Processors\x86\data\languages from 10.0.4 to 10.1's directory makes function ID work again.

**Comment by ryanmkurtz** [comment]
Likely a duplicate of #2877

**Comment by wburton-intel** [comment]
Yep, that looks identical. I'll close this.
