### ISSUE TITLE
Loading .gdt file in headless mode

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#4004]
Hello!

I would like to apply a windows 32 api .gdt file (which I already have) to a binary's functions before I grab their decompiled C-code. Is there a way I can do this programmatically in headless mode? I have searched online but the examples for this specific case were not very helpful. Many thanks!

**Comment by astrelsky** [comment]
```java
import java.util.List;

import ghidra.app.cmd.function.ApplyFunctionDataTypesCmd;
import ghidra.app.util.headless.HeadlessScript;
import ghidra.program.model.data.DataTypeManager;
import ghidra.program.model.symbol.SourceType;

public class SampleGhidraScript extends HeadlessScript {

    @Override
    public void run() throws Exception {
        List<DataTypeManager> managers = List.of(currentProgram.getDataTypeManager());
        ApplyFunctionDataTypesCmd cmd = new ApplyFunctionDataTypesCmd(
            managers, currentProgram.getMemory(), SourceType.USER_DEFINED, true, true);
        cmd.applyTo(currentProgram, monitor);
    }
}

**Comment by aa-software2112** [comment]
I am going to test this out today and see how it works! It's not clear to me how to load a gdt from the filesystem but I'm hoping the Ghidra API will reveal this functionality.

**Comment by astrelsky** [comment]
> I am going to test this out today and see how it works! It's not clear to me how to load a gdt from the filesystem but I'm hoping the Ghidra API will reveal this functionality.

I don't use headless mode so I'm not 100% sure of what is or isn't available. You would normally get the `DataTypeManagerService` to open it though. You would get the service via `getState().getTool().getService(DataTypeManagerService.class)` but I *think* the tool might be null in headless mode.

**Comment by aa-software2112** [comment]
I'm going to try that - for now I did this but it appears to do nothing to the decompilation results in GUI mode if ran as a GhidraScript

![image](https://user-images.githubusercontent.com/22150653/155218890-24af6130-ff3c-4f25-8723-8480714b2eda.png)

**Comment by aa-software2112** [comment]
OK, just got it working... For those who are curious of the solution, be **very** careful about the second parameter. As the constructor's javadoc states ->

> (param2): set of addresses containing labels to match against function names. The addresses must not already be included in the body of any existing function. If null, all symbols will be processed

Thus, by putting null, all functions called will be re-evaluated... putting currentProgram.getMemory() will force you to attempt to understand param2 which for the life of me I could not figure out.

![image](https://user-images.githubusercontent.com/22150653/155232406-9345a69a-6005-4857-be9e-dbd001bde332.png)

BEFORE
![image](https://user-images.githubusercontent.com/22150653/155233081-9de74dad-25bd-45b6-a563-2d26eaa10a04.png)

AFTER
![image](https://user-images.githubusercontent.com/22150653/155233024-d0525398-9ecf-4014-8889-050071c57c2b.png)

**Comment by astrelsky** [comment]
:rofl: that's what I get for not reading the docs. The intent behind what I originally showed as an example should have been using `null` instead of `currentProgram.getMemory()`.
