### ISSUE TITLE
could not find decompiler executable decompile (Alpine Linux)

### ISSUE THREAD

**Issue by aolszowka** [NationalSecurityAgency/ghidra#4005]
**Describe the bug**
Similar to #1495 an error is encountered when attempting to run Ghidra 10.1.2 in Alpine Linux 3.1.5.

As per instruction from @ryanmkurtz I have opened a new issue to better document this.

There is a solution that worked for me at the bottom of this post.

**To Reproduce**
I am actually building a Docker container on top of LinuxServer.io's wonderful rdesktop-web base container (https://github.com/aolszowka/docker-ghidra); here's an early version of my Dockerfile:

```dockerfile
FROM lsiobase/rdesktop-web:alpine

# set version label
ARG GHIDRA_RELEASE="https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.2_build/ghidra_10.1.2_PUBLIC_20220125.zip"

RUN \
  echo "**** install packages ****" && \
  apk add --no-cache --virtual=build-dependencies \
    curl unzip && \
  apk add --no-cache \
    openjdk11 && \
   echo "**** install ghidra from ${GHIDRA_RELEASE}****" && \
   curl -sL ${GHIDRA_RELEASE} --output /tmp/ghidra.zip && \
   unzip /tmp/ghidra.zip -d /usr/bin && \
   mv /usr/bin/ghidra_10.1.2_PUBLIC /usr/bin/ghidra && \
   echo "**** cleanup ****" && \
   rm -rf /tmp/* && \
   apk del --purge \
     build-dependencies


# add local files
COPY /root /

# ports and volumes
EXPOSE 3000
VOLUME /config
VOLUME /data
```

Build the Dockerfile:
```
docker build . --tag docker-ghidra:broken
```

Run an instance of this container:

```
sudo docker run -d \
  -p 3000:3000 \
  -v ~/ghidra-config:/config \
  -v ~/ghidra-data:/data \
  --shm-size="1gb" \
  docker-ghidra:broken
```

And connect to it via the web. Attempt to decompile a Windows Application (in my case I threw in Notepad2); this will error (ScreenToGIF Capture attached):

![GhidraError](https://user-images.githubusercontent.com/2592881/154407121-0825bd20-4137-40f1-ba9c-80145efca16d.gif)

Here's one of the frames with the stack trace:
![image](https://user-images.githubusercontent.com/2592881/154407030-100ae3e8-8d4e-4303-98b8-2e3d5b78d770.png)

**Expected behavior**
One would expect this not to crash

**Environment**
(See `Dockerfile` for usable environment)
 - OS: Alpine 3.15
 - Java Version: OpenJDK 11.0
 - Ghidra Version: 10.1.2
 - Ghidra Origin: GitHub Release
 - Platform: amd64 (in Docker)

**Additional context / Solution**
User @niqdev encountered the same issue on that thread, and was helpful enough to report his solution. The root cause of the problem seems to be that Ghidra is expecting `glibc` to be on the box. However Alpine ships with `musl`.

Their work around was to use a custom built distribution of `glibc`. The [Alpine Linux Wiki](https://wiki.alpinelinux.org/wiki/Running_glibc_programs) however suggests using [gcompat](https://git.adelielinux.org/adelie/gcompat) as a work around which is much more straight forward in my opinion.

I can confirm that this works, simply change the docker file to add this to the installer like so:

```
apk add --no-cache \
    openjdk11 gcompat && \
```

This avoids the crash.

**Comment by ryanmkurtz** [comment]
Thanks for documenting this.  Given that we are not going to distribute native binaries for Alpine, what action would you like to come from this ticket?  It looks like we can improve the error message...the "could not find..." is misleading since Ghidra found it and attempted to run it.

**Comment by aolszowka** [comment]
@ryanmkurtz I think closing this ticket as *wont_fix* is good enough for me,if someone else is heading down the same path at least there is a ticket specifically for this rather than being buried in an unrelated ticket.

Improving the error message would be great; but in the grand scheme of things probably not work the dev cycles. Thank you!
