### ISSUE TITLE
How to build Ghidra source jar file for attach debugging

### ISSUE THREAD

**Issue by fangxlmr** [NationalSecurityAgency/ghidra#4008]
I'd like to attach the source jar to `ghidra.jar` in vscode/eclipse when debugging. I found the script under `support` directory to build it: `./buildGhidarJar -srczip ghidra-sources.jar`. But I got this error afterwards
```
...
duplicate entry: ghidra/pcode/exec/
duplicate entry: ghidra/base/
duplicate entry: ghidra/base/widgets/
duplicate entry: ghidra/base/widgets/table/
duplicate entry: META-INF/
duplicate entry: META-INF/MANIFEST.MF
duplicate entry: defaultTools/
Can't create source zip!  Has source been downloaded and installed?
Done
```
I know that I `must have installed/unzipped the Ghidra source distribution into your install directory for the srczip option to work.`, but I though it should work with the released tarball. So what I was missing here and how to download and install them?

Related lines of codes:
https://github.com/NationalSecurityAgency/ghidra/blob/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1/Ghidra/RuntimeScripts/Common/support/buildGhidraJarREADME.txt#L30

https://github.com/NationalSecurityAgency/ghidra/blob/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1/Ghidra/RuntimeScripts/Common/support/buildGhidraJarREADME.txt#L35

https://github.com/NationalSecurityAgency/ghidra/blob/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1/Ghidra/Features/Base/src/main/java/ghidra/util/GhidraJarBuilder.java#L343

**Comment by astrelsky** [comment]
I use this hack up of a gradle script to debug Ghidra in vscode. It is a bit finicky sometimes but when it works it works.
https://github.com/astrelsky/vscode-ghidra-skeleton/blob/master/skeleton/build.gradle

**Comment by ryanmkurtz** [comment]
Sorry for the delay in responding @fangxlmr.  Did you ever get this working?

**Comment by fangxlmr** [comment]
It's too finicky, so I decided to run Ghidra in debugging mode and attatch to the pid through jvm

**Comment by ryanmkurtz** [comment]
Ok, sounds good.
