### ISSUE TITLE
Persistently modifying pcode?

### ISSUE THREAD

**Issue by RolfRolles** [NationalSecurityAgency/ghidra#401]
My abstract interpretation-based analysis determines when values within the pcode are constant. I build a control flow graph where the vertices contain lists of `PcodeOp` objects (copied from `PseudoInstructions`, obtained via a `PseudoDisassembler`). When I detect constant values, I create new `PcodeOp` objects, and replace the ones in the CFG with the new ones to incorporate the results of the analysis. This works perfectly, but the results are transient (i.e. only my copies of the objects are modified -- no changes persist within the database).

I wondered whether I could persistently modify the `PcodeOp` objects associated with the `Instruction` objects in the database. I obtained `Instructions` via disassembly (rather than `PseudoInstructions` as previously), and tried to use the `PcodeOp::setInput`, `PcodeOp::setOpcode`, and `PcodeOp::removeInput` methods to modify the `PcodeOp` listings in the database. However, this seems to have no effects on the pcode listing in the Code Browser.

Is it possible to persistently modify the `PcodeOp` associated with a given `Instruction` in the database? Or is the pcode regenerated from SLEIGH every time, and thus the objects truly are transient? Thanks in advance for your time.

**Comment by emteere** [comment]
The pcode is regenerated from sleigh each time, there are methods to surgically change operations such as a callfixup or pcodeop injection.  So yes, the pcode is currently transient.  It is a balance of consuming storage and locking in the current state of facts versus the ability to dynamically change as new information is uncovered.

**Comment by RolfRolles** [comment]
Well, that sounds reasonable. For most scenarios it would be a waste of space to store that stuff in the database when it can so easily be rematerialized. Mostly I wanted it for decorative purposes to show the user the results, so I just added comments instead, which is good enough. Thanks.
