### ISSUE TITLE
 Exception while decompiling ... Decompiler process died

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4012]
**To Reproduce**
```console
./decomp_dbg
restore arm_npe.xml
lo fu _24_a
```

**Expected behavior**
A one to one exact replica of the original source code complete with original comments.

**Attachments**
[arm_npe.xml](https://github.com/NationalSecurityAgency/ghidra/files/8111842/arm_npe.xml.txt)

**Environment (please complete the following information):**
 - Ghidra Version: 3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1

**Additional context**
<details><summary>The cause of the crash</summary>

[![](https://img.youtube.com/vi/bLHL75H_VEM/hqdefault.jpg)](https://www.youtube.com/watch?v=bLHL75H_VEM)
</details>

**Comment by caheckman** [comment]
I was unable to reproduce this.  The decompiler console mode doesn't rebuild .sla files automatically.  Were your .sla files in sync with https://github.com/NationalSecurityAgency/ghidra/commit/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1 ?

**Comment by astrelsky** [comment]
> I was unable to reproduce this. The decompiler console mode doesn't rebuild .sla files automatically. Were your .sla files in sync with [3e245c6](https://github.com/NationalSecurityAgency/ghidra/commit/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1) ?

Oh this was totally my fault. It appears I had some uncommitted changes to the decompiler that I long forgot about that broke this.
