### ISSUE TITLE
Search Memory:  Next, Previous, Search All buttons are disabled on unstoppable results

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4014]
**Describe the bug**
The only way to cancel a search that I'm aware of is using the red X in the bottom of the results window.  If that window is inadvertently/accidentally closed there is no way to cancel.  For a complex regex or over a large image this could be a significant amount of time with little feedback on when its done in the background.  Typically I will just save/quit/reopen the codebrowser.

Additionally, I have sometimes noticed this when I know nothing is being searched for the search buttons are disabled (and not sure how to troubleshoot that so not sure how many issues this should be if broken down).

**To Reproduce**
1. Create a search that should take a large amount of time (probably regex)
2. Begin searching
3. close the pop-up search results window
4. Try to search again

**Expected behavior**
Closing that window should cancel using the monitor or hold a reference to the search task (and/or results) somewhere to cancel manually.

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: 11.0.10
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official

**Additional context**
The 2nd case I mentioned is master/eclipse, so don't know if that's relevant, but I guess worth mentioning incase it would point out that there is also some corner case that doesn't enable the buttons after a search has completed.

**Comment by dragonmacher** [comment]
Closing the window should cancel the search.  I'm surprised this is not happening now.

**Comment by mumbel** [comment]
I'll do a few more tests, maybe I was hitting some weird condition

**Comment by dragonmacher** [comment]
I can see the buttons not getting re-enabled when closing the windows.   I believe the search has been cancelled, but the buttons are not getting updated.
