### ISSUE TITLE
"Name cannot be blank"

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4015]
**Describe the bug**
Attempting to set the namespace for a function from the listing results in the message "Name cannot be blank". While the message appears and it behaves as though it wasn't accepted, the namespace is, in fact, correctly set.

**To Reproduce**
1. Go to a function
2. Press 'l' on the function name or label
3. Set it to `MyNamespace::`
4. See the error message appear, the dialog box still present but the namespace correctly set.

**Expected behavior**
No message and the dialog box should disappear after correctly setting the namespace.

**Environment (please complete the following information):**
 - Ghidra Version: 3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1

**Comment by astrelsky** [comment]
This needs to be re-opened. It now says "Name cannot be blank while changing namespace" and no longer changes the namespace. I do not know the name and need it to stay the default name.

**Comment by dragonmacher** [comment]
It sounds like I did not understand your use case.   Are you trying to add a default label into a namespace?  Also, a new namespace and not one that is i the drop-down box?

**Comment by astrelsky** [comment]
> It sounds like I did not understand your use case. Are you trying to add a default label into a namespace? Also, a new namespace and not one that is in the drop-down box?

Yes and yes. Basically I have a function `FUN_01234567` and know that it is a string function and want to do `std::basic_string::` to put it in the existing classes namespace.

**Comment by dragonmacher** [comment]
I was just trying this and noticed interesting behavior, which may provide you with a workaround.

If I place my cursor on the function name or the function label (just below the params and locals) and then edit the label, the dialog is pre-populated with the default function name.  This allows you to enter a new namespace as you tried to do.

However, if you click on the address of the function and then start a label edit, then the function text is not placed in the dialog, which triggers the case you described.   This seems like an edge case that we may have missed.

When you trigger your edit, where is your cursor?

**Comment by astrelsky** [comment]
> I was just trying this and noticed interesting behavior, which may provide you with a workaround.
> 
> If I place my cursor on the function name or the function label (just below the params and locals) and then edit the label, the dialog is pre-populated with the default function name. This allows you to enter a new namespace as you tried to do.
> 
> However, if you click on the address of the function and then start a label edit, then the function text is not placed in the dialog, which triggers the case you described. This seems like an edge case that we may have missed.
> 
> When you trigger your edit, where is your cursor?

I have noticed the name appearing recently (after initially opening this). It may have been that I just started entering the new label and overwrote it before noticing. Would leaving the default function name present when setting the namespace in this fashion set the source type for the function name? I wouldn't want it to be changed to `USER_DEFINED` because if I later obtain an fidb that knows what it is I'd want the name to be applied (or something along that nature).

**Comment by dragonmacher** [comment]
Using the default name in this fashion will trigger the underlying code to set the source type to be `DEFAULT`.

**Comment by astrelsky** [comment]
> Using the default name in this fashion will trigger the underlying code to set the source type to be `DEFAULT`.

I think it is fine as it is then. I *think* `DEFAULT` is the lowest priority so if it doesn't interfere with anything or cause problems being changed then I see no problem how it is.
