### ISSUE TITLE
MIPS LE Pattern Assuming Ascending Stack

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#402]
In the file MIPS_LE_patterns.xml line 13 is the following line:
`<data>......00  `**`1`**`....... 10111101 00100111</data>             <!-- ADDIU SP,SP,-xxxx -->`

The bit in bold is the sign bit of the simmed field. This assumes an ascending stack which may not be the case for all processors. With the exception of a calling convention where the caller has to preserve the stack, I don't see a reason why the pattern wouldn't work with an ascending or descending stack by allowing the sign bit to be either or.

This also appears to be the case with all the patterns regarding a signed integer addition to the stack pointer in the pattern file.

An unfortunate result of this is the following decompiled warning in every single returning function.

`LAB_00250848:
                    /* WARNING: Could not recover jumptable at 0x00250860. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)*(undefined8 *)(iVar18 + -8))();
  return;`

**Comment by emteere** [comment]
The patterns file is purely for finding the start of a function.  Incorrect or over specified patterns in this file would only result in finding incorrect function starts or not finding valid function starts.

Is this what you are seeing, functions created past the initial function start, or not created at certain locations?

For the stack to grow positive, more changes would need to be made to other files, particularly the .cspec file which needs to know about stack growth and param/return locations, .ldefs file to specify a new variant, and the patterns file with the change you suggest.

**Comment by astrelsky** [comment]
Ah, maybe I misinterpreted the purpose of the pattern file. Essentially
what is happening is ghidra is presenting the jump table warning for every
jal and jalr instruction. The decompiled code above is of malloc. There is
no thunk or called function before the return.

**Comment by RenaKunisaki** [comment]
Sorry, how did you fix this? I'm having the same problem. I could live with the incorrect "unrecovered jumptable" message, but it also has the annoying effect of naming the return value UNRECOVERED_JUMPTABLE in every function, and not recognizing that it's actually being returned.

**Comment by astrelsky** [comment]
> Sorry, how did you fix this? I'm having the same problem. I could live with the incorrect "unrecovered jumptable" message, but it also has the annoying effect of naming the return value UNRECOVERED_JUMPTABLE in every function, and not recognizing that it's actually being returned.

If this is a custom sleigh language implementation then you need to be sure to use `return` instead of `goto` in the instruction definition. At least that is what was causing my problem.

**Comment by RenaKunisaki** [comment]
I'm just using Ghidra. Maybe I've selected the wrong MIPS variant?

**Comment by astrelsky** [comment]
> I'm just using Ghidra. Maybe I've selected the wrong MIPS variant?

If you're using a MIPS variant provided with Ghidra than that is most likely the case.

**Comment by RenaKunisaki** [comment]
Do you mean the provided ones are incorrect? I'm looking at `mips32Instructions.sinc` and it looks like `jr ra` is handled.

In my case, the problem appears to be that `ra` isn't being used.
```
  800057d4 FB 63        addiu    sp,-0x28
  800057d6 08 62        sw       ra,local_8(sp)
[...]
  8000582c 08 97        lw       a3,local_8(sp)
  8000582e 4C D9        sw       v0=>FUN_80005784+1,0x30(s1)=>DAT_8000c350     = 80005785h
  80005830 50 67        move     v0,s0
  80005832 07 91        lw       s1,local_c(sp)
  80005834 06 90        lw       s0,local_10(sp)
  80005836 00 EF        jr       a3
  80005838 05 63        _addiu   sp,0x28
```

Should I open a new issue for this, or is there just something I'm overlooking?

**Comment by astrelsky** [comment]
> Do you mean the provided ones are incorrect? I'm looking at `mips32Instructions.sinc` and it looks like `jr ra` is handled.
> 
> In my case, the problem appears to be that `ra` isn't being used.
> 
> ```
>   800057d4 FB 63        addiu    sp,-0x28
>   800057d6 08 62        sw       ra,local_8(sp)
> [...]
>   8000582c 08 97        lw       a3,local_8(sp)
>   8000582e 4C D9        sw       v0=>FUN_80005784+1,0x30(s1)=>DAT_8000c350     = 80005785h
>   80005830 50 67        move     v0,s0
>   80005832 07 91        lw       s1,local_c(sp)
>   80005834 06 90        lw       s0,local_10(sp)
>   80005836 00 EF        jr       a3
>   80005838 05 63        _addiu   sp,0x28
> ```
> 
> Should I open a new issue for this, or is there just something I'm overlooking?

That's an unusual pattern. In this case you can right click on the `jr a3` instruction, select `Modify Instruction Flow...` and choose `call return` from the drop down dialog.

However I find the `sw       v0=>FUN_80005784+1` to be a bit fishy.
