### ISSUE TITLE
Debugger Trace: Failure Map regions to open program

### ISSUE THREAD

**Issue by lacraig2** [NationalSecurityAgency/ghidra#4024]
**Describe the bug**
When attempting to map regions to open programs the MapRegionsDebuggerBot attempts to propose regions that might be in different address spaces.

**To Reproduce**
Load trace. Click forward a few times.

I'd be happy to provide a trace to reproduce this with.

**Expected behavior**
No error thrown.

**Screenshots**
Stack trace:
<img width="1004" alt="Screen Shot 2022-02-16 at 12 41 04 AM" src="https://user-images.githubusercontent.com/7518336/155243107-1a97731d-0d7d-4515-ab75-353b93cbec58.png">

**Environment (please complete the following information):**

- OS: macOS 11.6.4
- Java Version: 14.0.2
- Ghidra Version: https://github.com/NationalSecurityAgency/ghidra/commit/3e245c6f80b1fe6465a8d5f73c09bcd1fd823fb1
- Ghidra Origin: locally built

**Additional context**

**Comment by d-millar** [comment]
Thanks for these - will try to get your fixes into the next release!
