### ISSUE TITLE
process CoffSymbol error

### ISSUE THREAD

**Issue by lemuellew** [NationalSecurityAgency/ghidra#4028]
**Describe the bug**
run `PortableExecutableRichPrintScript` error

**Screenshots**
![image](https://user-images.githubusercontent.com/59448437/155283282-9be97a2b-c558-4173-9317-91e8e2344fd5.png)

**Attachments**
[msxml2.zip](https://github.com/NationalSecurityAgency/ghidra/files/8122806/msxml2.zip)

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: openjdk 11
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by ryanmkurtz** [comment]
I'm looking into it.  Our ability to parse PE's from memory instead of from file seems a bit incomplete.

**Comment by ryanmkurtz** [comment]
NOTE: The same issue happens with the sample provided in #1267.

**Comment by ryanmkurtz** [comment]
There are a couple of issues:

1. When we reparse the PE from memory, we aren't properly treating the symbol table offset from the file header as a file offset.
2. If we did treat it correctly, it still would not be in memory so we would not be able to recover the long section names.

Now that we have the `FileBytes` API, it may be better to get rid of the `SectionLayout.MEMORY` concept and just reparse the original `FileBytes` when we want to recreate the PE header java objects.
