### ISSUE TITLE
Mac M1 debugging

### ISSUE THREAD

**Issue by erfg12** [NationalSecurityAgency/ghidra#4035]
My Mac M1 is having an issue running Ghidra 10.1.2 as a Debugger.

When trying to debug, I get an error immediately stating LibLLDB not found. I have JDK11, LLDB and XCode installed. Ghidra itself opens fine and it can decompile the programs fine. But when trying to debug I get that error immediately.

NOTE: I tried version 17 of OpenJDK and both aarch64 and x64 builds. Both give the same result.

`jake@Jake-laptop ~ % where javac`

`/usr/bin/javac`

`jake@Jake-laptop ~ % where java`

`/usr/bin/java`

`jake@Jake-laptop ~ % java -version`

`openjdk version "`[`11.0.14.1`](https://11.0.14.1)`" 2022-02-08`

`OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)`

`OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)`

`jake@Jake-laptop ~ % javac -version`

`javac` [`11.0.14.1`](https://11.0.14.1)

`jake@Jake-laptop ~ % java -XshowSettings:properties`

`Property settings:`

`awt.toolkit = sun.lwawt.macosx.LWCToolkit`

`file.encoding = UTF-8`

`file.separator = /`

`ftp.nonProxyHosts = local|*.local|169.254/16|*.169.254/16`

`gopherProxySet = false`

`http.nonProxyHosts = local|*.local|169.254/16|*.169.254/16`

`java.awt.graphicsenv = sun.awt.CGraphicsEnvironment`

`java.awt.printerjob = sun.lwawt.macosx.CPrinterJob`

`java.class.path =`

`java.class.version = 55.0`

`java.home = /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home`

`java.io.tmpdir = /var/folders/_5/957hykns6vg0y71wgvjwjp000000gn/T/`

`java.library.path = /Users/jake/Library/Java/Extensions`

`/Library/Java/Extensions`

`/Network/Library/Java/Extensions`

`/System/Library/Java/Extensions`

`/usr/lib/java`

`.`

[`java.runtime.name`](https://java.runtime.name) `= OpenJDK Runtime Environment`

`java.runtime.version = 11.0.14.1+1`

[`java.specification.name`](https://java.specification.name) `= Java Platform API Specification`

`java.specification.vendor = Oracle Corporation`

`java.specification.version = 11`

`java.vendor = Eclipse Adoptium`

`java.vendor.url =` [`https://adoptium.net/`](https://adoptium.net/)

`java.vendor.url.bug =` [`https://github.com/adoptium/adoptium-support/issues`](https://github.com/adoptium/adoptium-support/issues)

`java.vendor.version = Temurin-11.0.14.1+1`

`java.version =` [`11.0.14.1`](https://11.0.14.1)

[`java.version.date`](https://java.version.date) `= 2022-02-08`

`java.vm.compressedOopsMode = Zero based`

[`java.vm.info`](https://java.vm.info) `= mixed mode`

[`java.vm.name`](https://java.vm.name) `= OpenJDK 64-Bit Server VM`

[`java.vm.specification.name`](https://java.vm.specification.name) `= Java Virtual Machine Specification`

`java.vm.specification.vendor = Oracle Corporation`

`java.vm.specification.version = 11`

`java.vm.vendor = Eclipse Adoptium`

`java.vm.version = 11.0.14.1+1`

`jdk.debug = release`

`line.separator = \n`

`os.arch = x86_64`

[`os.name`](https://os.name) `= Mac OS X`

`os.version = 12.1`

`path.separator = :`

`socksNonProxyHosts = local|*.local|169.254/16|*.169.254/16`

`sun.arch.data.model = 64`

`sun.boot.library.path = /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/lib`

`sun.cpu.endian = little`

`sun.cpu.isalist =`

`sun.io.unicode.encoding = UnicodeBig`

`sun.java.launcher = SUN_STANDARD`

`sun.jnu.encoding = UTF-8`

`sun.management.compiler = HotSpot 64-Bit Tiered Compilers`

`sun.os.patch.level = unknown`

[`user.country`](https://user.country) `= US`

`user.dir = /Users/jake`

`user.home = /Users/jake`

`user.language = en`

[`user.name`](https://user.name) `= jake`

`user.timezone =`

**Comment by d-millar** [comment]
@erfg12 good morning, and let's see if we can get you up and running.  I run off a Mac M1 so this is definitely do-able.  First, two questions:  (1) what is the actuall error?  i.e. if you run with ghidraDebug, is there a stack trace in the console and/or are there any useful messages in either the Interpreter or DebugConsole windows?  and (2) did you walk through the step in InstructionsForBuildingLLDBInterface.txt (in Ghidra/Debug/Debugger-swig-lldb)?  Until lldb decides to accept our patch submissions, you need to build the appropriate SWIG infrastructure.

**Comment by erfg12** [comment]
Hey @d-millar, Happy Friday. [Here's an exact screenshot of the error message](https://preview.redd.it/9mnyye9zzsj81.png?width=925&format=png&auto=webp&s=c80f54cd7d0b79084d4b9e1b26fb9ee6fcda789d). 

So I followed the `InstructionsForBuildingLLDBInterface.txt` instructions (at least I think this is correct):
```cd ghidra/Ghidra/Debug/Debugger-swig-lldb
export JAVA_HOME=$(/usr/libexec/java_home)
export LLVM_HOME=$(brew --prefix llvm)/bin
export LLVM_BUILD=$(brew --prefix llvm)
gradle build```

I get the error message `Unable to find the local maven repo.  Ensure you have created the flatRepo directory or ghidra.repos.config file.`

**Comment by d-millar** [comment]
Right, OK - so you need to get set up in development mode.  Try running:

gradle -I gradle/support/fetchDependencies.gradle init

**Comment by erfg12** [comment]
Nice, building started, but lldb is missing a file: 
```
/Users/jake/misc/ghidra/Ghidra/Debug/Debugger-swig-lldb/src/main/cpp/LLDBWrapJava.cpp:266:10: fatal error: lldb/lldb-public.h file not found

#include lldb/lldb-public.h
```

**Comment by d-millar** [comment]
Ah, I think that might be a shortcoming of the brew install, i.e. no header files.  You can resolve this by pulling the lldb source and either copying files or repointing LLVM_HOME at this, but let me see if (a) this is the case, and (b) there's a better fix.

**Comment by d-millar** [comment]
OK, so they're there, which is good, but the homebrew dir layout is a little different than the LLVM source tree.  If you open up buildNatives.gradle and look for references to "llvm_dir", you'll find the include path code.  I think you're going to need to edit this and replace references to "$llvm_dir/lldb/include" with "$llvm_dir/include".

**Comment by erfg12** [comment]
Got the libldb-java.a file from compilation, I'm guessing that's the file I need? I was expecting a .dylib or something.

**Comment by erfg12** [comment]
Sorry, I looked under the wrong dir, the dylib was located in `build/os/mac_arm_64`. I put it in extensions dir and debug seems to work now! Thank you @d-millar for all your help.

**Comment by d-millar** [comment]
My pleasure - glad you got it working!  Yell, if you hit any other hiccups.
