### ISSUE TITLE
XCHG RSP,RBP

### ISSUE THREAD

**Issue by PatchByte** [NationalSecurityAgency/ghidra#4040]
**Describe the bug**
```
MOV        RBP,LAB_7ff7f9a01b44
XCHG       qword ptr [RSP],RBP=>LAB_7ff7f9a01b44
```

If you use this assembler code (anti reversing trick) it will not show it as call!
Used by Arxan Anti Debugging and Anti reversing (Arxan Technologies or Digital.Ai)

**To Reproduce**
Compile the assembler code
Decompile it it will not show it as code!

**Expected behavior**
Should show as a call

**Screenshots**
https://imgur.com/zUdJMrh

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Win 10
 - Java Version: 11.X
 - Ghidra Version: 10.1.2
 - Ghidra Origin: ghidra-sre.org

**Comment by hedgeberg** [comment]
To confirm that I'm understanding correctly, the "call" instruction here would be the first return encountered _after_ the XCHG instruction is executed, no? It looks like the disassembly in question here loads a fake return address onto the stack, then does normal execution up until the return, at which point flow would branch to the address that was loaded into the stack. 

If that's the case, this may already be solvable by changing the flow control of the return instruction from CALL_RETURN to CALL. Give that a shot and see if the decompiler recognizes it.

**Comment by PatchByte** [comment]
Oh sorry i didnt know that you could do that!
Ok so i tried it but often it still doesnt recognize it as a "fake call"!
But it fixed some parts!

**Comment by hedgeberg** [comment]
What instruction are you using the "modify control flow" on? And, in some cases, you might want to clear the function and rebuild with the control flow modification applied. If it's not working in some parts, that's probably a sign that the constant propagation engine is failing to propagate the address across the stack variable to the return address that gets digested. That can happen for a number of reasons but usually ghidra's constprop engine is pretty good, so I suspect this is something you can make the decompiler understand using a script. If you add a jump destination reference to the return after modifying the control flow, then disassemble after the return and re-run analysis (you might want to make sure the "call fix-up" analysis step is enabled, too), it should figure most of them out. If it still doesn't, then it may be a bug in constant propagation that can be addressed. For now, though, try clearing the function, redisassembling it from scratch, then modify control flow, then add a reference, then do disassembly, then rerun analysis, and see if the decompiler still doesnt figure it out. If it does work, you can write a script to apply this set of steps to a function automatically.

**Comment by PatchByte** [comment]
yeah it kinda helps but it sill messes up many things! but yeah it helps
