### ISSUE TITLE
Modify decompiled code

### ISSUE THREAD

**Issue by erfg12** [NationalSecurityAgency/ghidra#4044]
Is it possible to modify the decompiled code? I want to observe the bytes and op codes needed for a patch.

**Comment by slzero-X** [comment]
I don't think it is, for now I guess we'll have to wait til such a feature is added. Implementing such a thing would be a daunting task.

**Comment by erfg12** [comment]
> I don't think it is, for now I guess we'll have to wait til such a feature is added. Implementing such a thing would be a daunting task.

Can IDA Pro or any other software do this?

**Comment by astrelsky** [comment]
> > I don't think it is, for now I guess we'll have to wait til such a feature is added. Implementing such a thing would be a daunting task.
> 
> Can IDA Pro or any other software do this?

You're going to need to approach this from a different angle. This should be helpful for what you are looking to do assuming the code you are looking to change isn't too dependent on pre-defined structures.

https://gcc.godbolt.org/

**Comment by pjsoberoi** [comment]
> Is it possible to modify the decompiled code? I want to observe the bytes and op codes needed for a patch.

IMHO this is not a reasonable ask for the Ghidra project. Ghidra is a disassembler\decompiler not a compiler. Ghidra would need to ship a compiler for every processor it supports. Also Ghidra's decompilation is pseudo C not (usually) compilable C code. 

Like @astrelsky mentioned, you would want to take your decompiled pseudo C, clean it up and compile it, tweak it, then disassemble it.
