### ISSUE TITLE
Tricore relocations are not handled

### ISSUE THREAD

**Issue by beigela** [NationalSecurityAgency/ghidra#4047]
**Describe the bug**
When importing a tricore object file, the Import Results Summary window shows this:
>ELF relocation handler extension not found!  Unable to process relocations.
>WARNING: At 00010008 no handler to process ELF Relocations to KERNEL_FUNC.
+ dozens more warning lines like this, including relocations to external funcs like `memcpy`

**To Reproduce**
1. Import a tricore object file.
2. Select a variant (it happens with all of them).

**Expected behavior**
My expectation is that the relocation table is read and applied so that external functions get labelled properly.

**Attachments**
I might be able to find an example I can add if needed, but any tricore object file should experience this problem.

**Environment (please complete the following information):**
 - OS: macOS
 - Java Version: 16.0.1
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by mumbel** [comment]
Not sure which relocations you need, but do have an pull request to add that feature. 
 https://github.com/NationalSecurityAgency/ghidra/pull/1449

**Comment by mumbel** [comment]
@ryanmkurtz  thought I had, but didn't link in the PR message
