### ISSUE TITLE
Decompiler not inferring string pointer for first argument (format string)

### ISSUE THREAD

**Issue by freetink3r** [NationalSecurityAgency/ghidra#4050]
**Describe the bug**

The decompiler is not inferring a string pointer for the format string argument (first argument) to printf. As a result, the format string does not show up in the decompiler view. Instead, it just shows the pointer arithmetic as shown in the example below.

![image](https://user-images.githubusercontent.com/5585976/156462021-29914d2b-023d-4b4f-ba51-03ee62e6c449.png)

I verified the following are true:

- The first argument in the function signature is set to "char *"
- Options -> Decompiler -> Analysis -> "Infer constant pointers" is checked
- The DAT_ADDR global variable resides in Read-Only memory in the Memory Map

I also tried to change the default string mutability to "constant" by right clicking on a string and setting Data -> Default Settings -> Mutability to "constant", but that didn't seem to make a difference.

**Expected behavior**

I would expect the decompiler to show a string instead of the pointer arithmetic. The disassembler is able to infer the string in all the same cases.

**Environment (please complete the following information):**
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by caheckman** [comment]
One last option to check:

Options -> Decompiler -> Analysis -> "Respect readonly flags" should be checked.  It is checked by default.

Otherwise we would need something like the output file from the "Debug Function Decompilation" menu option (upper right corner of the decompiler window) in order to diagnose.

**Comment by freetink3r** [comment]
Thanks, @caheckman. That was it! I'm not sure why it wasn't checked for me, because that's not an option I would have changed, at least not consciously.
