### ISSUE TITLE
Question: Easy way to move structures between folders?

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4053]
My datatype window often looks something like:

```
a_MyStructs
    interestingStruct1
    interestingStruct2
    ...
...
Demangler
    <thousands of useless stuff>
    interestingStruct
```

And I would like to move interestingStruct to the a_MyStructs folder.
Typing interestingStruct into the search bar I can 'cut' on it, but after removing the search term, I am not able to 'paste' into the a_MyStructs folder from the UI.

Is there an easy way to do this?

**Comment by astrelsky** [comment]
For some reason it seems that clearing the filter also removes it from the clipboard. The workaround I've been using is too select the one I want, remove the filter, let it reload with the cursor on the one you want and then cut and paste.

**Comment by dragonmacher** [comment]
I'll take a peek a the issue of the clipboard clearing.

Another way to move things that is much more convenient is to show a new Data Types window.  You can them have the destination folder in the primary window visible and waiting for copied/dropped items.    

To show the now window, use the Data Types drop-down arrow in its header, pressing the `Find Data Types by Name...`.  The new window is a copy of the primary Data Types view, but has a filter applied.   You can remove the filter in the new window to access the full tree.  You can use this new window to filter for the desired types you wish to move.

**Comment by dragonmacher** [comment]
Regarding the clipboard cleaning when removing the filter, I was unable to reproduce that issue.   If either of you can tell us how to reproduce that issue, then let us know.

**Comment by astrelsky** [comment]
> Regarding the clipboard cleaning when removing the filter, I was unable to reproduce that issue. If either of you can tell us how to reproduce that issue, then let us know.

It might be a bit more complicated to trigger than I let on. I'll pay closer attention to it next time I encounter it.
