### ISSUE TITLE
Add a right click option in the listing to "run to here" while debugging

### ISSUE THREAD

**Issue by aldelaro5** [NationalSecurityAgency/ghidra#4056]
**Is your feature request related to a problem? Please describe.**
It can happen that on some remote targets where unwinding the stack becomes difficult, step over in GDB can be erratic. It might not properly detect that you are on a function call and decides to step into instead. While I found some ways to combat this (such as making a thing to allow to import symbols from ghidra to gdb), it's not perfect and it can lead to inconveniences when trying to step over function calls. I almost always end up having to manually add a breakpoint under the call, run, let it break and remove the breakpoint after. This works, but it gets very inconvenient.

**Describe the solution you'd like**
Simply add a right click option that says "run to here" which would do these steps automatically. Many existing debuggers have that features, but here, it could be used to mitigate the limitations certain targets has that makes debugging inconvenient. It would simply add a temporary breakpoint that would get removed once hit. I think there might even be a way to tell GDB to do this via a command, but I am not sure.

**Describe alternatives you've considered**
Well I already tried them, but my idea was to tell GDB symbols like functions delimiters because I found that this helps. However I realised 2 problems with this: it's cumbersome to constantly sync the symbols bmanually and it's also not perfect; GDB still can sometime not step over properly. My realisation is that all I want is the convenience of "go through this function" which could be solved by a right click menu option.

**Additional context**
The target I have this particular issue is a GameBoy Advance game running on mgba, a GBA emulator. It turns out even this emulator itself cannot accurately unwind the stack at a precise moment in time without some aggressive tracking while the game runs so this is just an inherent limitation of the target I am working with.

**Comment by d-millar** [comment]
@aldelaro5  Will definitely consider this.  In general, we haven’t included a lot of breakpoint/step options in the GUI, which are very debugger-implementation specific, because they tend to clutter the GUI and tend to be easier to express as console commands.  

This might be an exception as it clearly adds functionality that benefits from the static/dynamic interaction.  Will have to figure out how to clarify step-over-to and step-into-to options for those debuggers that support them.

**Comment by nsadeveloper789** [comment]
We have an idea like this sort of planned. I had implemented a method wrapper for GDB's `advance` command, which if I understand correctly, does what you ask. The idea would be that methods which take a single address parameter could be invoked by right-clicking an address and selecting the method/command from the menu.

In the meantime, I might suggest two alternatives. 1) Not so great, but set a breakpoint at the desired address, continue, and then delete or disable the breakpoint. 2) Copy the address and use the Interpreter window to issue the `advance [address]` command manually.
