### ISSUE TITLE
Like registers and variables are not highlighted when clicked in disassembler or decompiler

### ISSUE THREAD

**Issue by seanthegeek** [NationalSecurityAgency/ghidra#4057]
**Describe the bug**
When clicking on a register such as EAX, all other instances of EAX should also be highlighted.

**To Reproduce**
1. Clink on any variable or register in the disassembly or decompiler windows 

**Expected behavior**
All instances of the clicked item should be highlighted.

**Environment (please complete the following information):**
 - OS:Windows 11
 - Java Version: 14.0.1
 - Ghidra Version: 10.1.2
 - Ghidra Origin: Official ghidra-sre.org distro

**Comment by ryanmkurtz** [comment]
Ghidra supports this via a middle-click.  Does that suit your needs?

**Comment by seanthegeek** [comment]
Ah, that worked. I could be mistaken, but that isn't what I remember from previous versions of Ghidra and tutorials I've worked with.

Is there a way to change that to a left click? I'm often using a laptop without a mouse, so I can't middle click.

**Comment by seanthegeek** [comment]
I found the option. Turns out the instructor of the course changed this setting for us in the VM provided for the course, so I thought it was a bug when it didn't work on other systems

![image](https://user-images.githubusercontent.com/44679/156929033-bd865d1d-79dd-4c7d-987d-40b439308ec6.png)
