### ISSUE TITLE
DAF is the trump treasonous

### ISSUE THREAD

**Issue by neffp** [NationalSecurityAgency/ghidra#4058]
**IPolicy <--"The Notice of Murdering in the meaning of a Man killing another, the Legal Basis for the reason of Partriot Act, and blocking leagal, lawful, and ethical coorpondance. Advanced Notice to file an injuction to the order to kill Mark Zackerburg, in a Federal Direstrict Court , here Eastern Dirstrict of the U.S. Federal Court, Fresno California. & S.E.C. for non investegation and DOJ for lack of ethical compliance, and Cal Bar Assciationation ; God v. United Stastes (DOES 1-1000) AS Murder is the basis for federal Agency to compile the Case but since they will not the actions will be out of Necessity of self and others, Stand my Ground and all basised on the U.S. Counstitation."-->
per S.E.C. and State of America in ecaxtly the same as enumerated from the U.S. Contitution , Meta Corp hs violated the purpose of a Publicly traded compary in actively committing actions that interfefer with the Mark Zackerburg safeguarding his own value market share, price, liabilites, and capital utlities. 
In blocking infromation prsons that present a aspect of undertaking the higher position of ethical conduct, the value of monitory is at risk of exposure. The polices of a publicly traded company must adhere to the U.S Constituition not any other standard here in America. see https://www.uscivilwarii.org and https://www.mixcloud.com/JDDJ_NRS/posts for this is the notice of Federal fililing of Nigel A. Marin J.D. v. Mark Zackerburg in the Eastern Distirict Court of the U.S. of America -Damages the Equity and Securtites of a Treasonous Corp all equity and all Board of Directors personal assests and 15 years inprisonment. Reference "Treason" #Partriot-Act# [nigel.marin@uscivilwarii.attorney].**

**S.E.C violations**
the law of whatJewThink or Law of What is known enumberated, and expressed in language of wrtien and implied, so what's the exuse Maggots, oh your Fggots but we all knew that sense that dildo up youir ass was not appreant of jacking off not complying to the law as you paid functioms, obviously or what else could it be? DAF retard, full-retard...What then i'm an idiot and cant anticipate your response, or I would state it and account for it but I donnot know, so make a statement or ignore, dont do anything the Biden way of a jackass.! my mules would do antthing for me, do nope i take thAt name of a jasckass ,back like a "white' of unethical maggot of a fly that only buzz's Around.

**working @un.org as Executive Intervention**
Could not process your request
We could not process your request. Please try again later.
then emails to investor relations get not responses and cc: to npr.or calbarassociation - nothing ; informed Newson of State of Cal. No action? so murder is justified in necessety of Protecting America per Civic Duty of a Federal Employee, same J.D. as Biden ,just not "white" as Nelson Mandela was "Willing to Die to tell the world of the inequality, I'M willing to Kill all that stand in my way to tell the entire world the same is true in the U.S. from an Tribal Nomadic humanity righjts ofGod in Madate from Heaven.
inJustification Defence Preparation of Malice and forethought, the mental ability is endless in legal warfare of the State of America.Patriot Act of interfener and your own laws are the result for your failure to compliance but for what_____________? answer because that is the question on the witness chair going to asked, and impeachment of your statement are by the actions you have conducted on you electonic devices. remember the only way to distory data is to physicall remove the hardrives, but in stacker, clould basis, and al other back ups, it is impossible to not hide your actions or inactions from a subpena. Do'hhh... thats what Homer said from the Odessay. Be about it and so will I. iRan, iFingeryou, iFunkified, iAlgorythemicInterface32circuirts -.{05|-|i/\/\.sys iMichanical NonMachinic so Monkeywrenching in your systemscarborationof NOS.Nitirs0><xide|-appily-inunKindness 4 all towitness. JW.org
**This Feature is Temporarily Blocked
You recently posted something that violates Facebook policies, so you're temporarily blocked from using this feature. For more information, visit the Help Center.
To keep from getting blocked again, please make sure you've read and understand Facebook's Community Standards.
The block will be active for 1 day and 7 hours more.
If you think this doesn't go against our Community Standards let us know.**
Could not process your request
We could not process your request. Please try again later.

**Comment by neffp** [comment]
THE MEMORANDUM OF YOUTUBES UNLAWFUL COMPLIANCE TO AMEICA.
Mailto: Department of Justice , Whitehouse.gov ; ontherecord@usmc.mil ; new@sec.gov
From: Nigel A. Marin J.D.
Date: 3/5/2022
Re: FEDERAL JUDICIAL NOTICE AND AMERICAN BAR ASSOCIATION 
OF UNETHICAL S.E.C. PRACTICES.
DEAR ALL LEAGEL DEPARTMENTS,
This Notice is to provide you all with the type of U.S. behavior has done to America that is protected by the Patriot act. And but for it effects the prospective of greed and injustice in unjust enrichment, does not allow anyone of any corporation to supersede the U.S. Constitution's Preamble. the propose of being able to form a more prefect union, ordain within the enumeration of the United States of America, but for The State of America against the United States. in the https://www.uscivilwarii.org . And the State of California's participation of the SJCL.EDU, CITY OF FRESNO, COUNTY OF FRESNO, AND GOVNOR NEWSOM'S FAULT IN BEING ASKED TO PROVIDE THE ENFORCEMENT OF LAW UPON MY THREADS OF DEATH UPON PERSONS A CRIMINAL OFFENSE AND NOTHING HAVING OCCURRED. So what is going on either I am sovereign but they are not providing notice as appropriate in proper actions of diplomatic consideration of a war and for human life.
The youtube tracking of a subpoena, to find the posts and those that deleted them is the 25 years in prison, 1,000,000.00 per word fine, and personal liability of ceasing all person and real property, as the Patriot Act has enforced upon my use of using it in the law of protecting America.
"The fake news, the statement that will cause this comment to be erased, means, this makes no sense. if you believe facebook and twitter are not the outlets that provide the fake news. I am an attorney of the uscivilwarii.org and notified the investor of Meta Corp to have Notice their blocking on my Lawful, Legal Notice on public forum is completely against the purpose of a corporation that has exchange consideration of S.E.C. but for the prevention of any new that risk it's value is considered a conflict of interest. in any event Freedom of speech and hate speech already have laws to support them, but allowing social media to not adhere to those laws makes it criminal and civilly against the America in the U.S. Constitution, and this idiot now wishes to report other than that about a Country he has no idea what is but for his reporting not on what is important to U.S. or America. SO I WILL KILL HIM IN MURDER UNDER THE PATRIOT ACT. AND SEE WHOM DELETES THIS AS IT SERVES A ADVANCED NOTICE FOR ALL TO SEE AND NOW IF DELETED THE USER IS COMMITTING TREASONOUS LEAGL AND UNLAWFUL ACTS AGAINST THE NOTIFICATION OF A MUDER TO A PERSON IN PUBLIC. TY /s/ NIGEL A. MARIN J.D. (electronic-signature) State of America Sea Dragon Administration Commander in Chief , email nigel.marin@uscivilwarii.attorney and https://www.mixcloud.com/JDDJ_NRS/posts Glory to God in this Earth"
Please print and retain a copy for Judicial attachment to the DA and DOJ prosecution of Youtube's Board of Directors and those that have deleted those posts on the morning of March 5 2022.
/s/ NIGEL A. MARIN J.D. (electronic-signature) 
State of America 
Sea Dragon Administration of Niram
Commander in Chief 
email nigel.marin@uscivilwarii.attorney 
and 
https://www.mixcloud.com/JDDJ_NRS/posts 
"Glory to God in this Earth"
Comments

**Comment by PatchByte** [comment]
what

**Comment by PatchByte** [comment]
uhm this is github.
