### ISSUE TITLE
M68000: Overriding signature doesn't work

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#406]
So, this problem makes my heart bleeding...
ROM: http://www.technopop.net/images/zerotole.zip
At the address `0xc5b38` there is a function that uses stack to pass arguments into the `FUN_000c5d2a`:
![изображение](https://user-images.githubusercontent.com/7189309/55986686-a8eee380-5ca8-11e9-86a6-0be57040179d.png)

Then, to get passed arguments, M68k calls `link a6, 0x0`, so the `A6` register becomes equal to the `SP` where arguments where stored:
![изображение](https://user-images.githubusercontent.com/7189309/55986888-05520300-5ca9-11e9-9754-40880330bac8.png)

Problem:
```
000c5d36  70 ff                  moveq        #-0x1,D0
000c5d38  2f 00                  move.l       D0,-(SP)=>local_8
000c5d3a  4e ba ff c2            jsr          FUN_000c5cfe
```
In disassembly it looks ok, and decompiler also shows -1 passed as function's argument. But, if we go into `FUN_000c5cfe` function, we will see that this function doesn't accept any argument:
![изображение](https://user-images.githubusercontent.com/7189309/55987103-72659880-5ca9-11e9-89ca-567b61f21075.png)

Ok, then I'm trying to use Override signature feature:
![изображение](https://user-images.githubusercontent.com/7189309/55987184-9d4fec80-5ca9-11e9-853e-0ce336bf508c.png)

![изображение](https://user-images.githubusercontent.com/7189309/55987216-af318f80-5ca9-11e9-8cc8-171bb1e34482.png)

But after going into that function again, I'm taking the same result: `FUN_000c5cfe` doesn't accept any argument.

So, how to specify that argument? How to tell Ghidra to use it without specifying it for every possible function?

Seems, that the next `FUN_000c5c9c` also uses this argument.

**Comment by nihilus** [comment]
A workaround would be to edit the signature with the option given from the list.
If it isn't working, maybe it should be removed and people should be enforced to click "Edit function signature" instead. If it is supposed to work there should be a key-binding to it.

**Comment by emteere** [comment]
Override signature is used only to override a signature such as printf, generally varags, where there are different number of parameters throughout the program and the arguments aren't detected correctly.
@nihilus is correct you should be using Edit Function signature to specify it takes a parameter, then it will show up that way everywhere it is used.
Also the fact that the function has a void suggests that one of the called functions in Fun_c5fce takes a parameter.
You can go into the leaf-functions in the decompiler and commit params/return.  There is also a paramID analyzer you can turn on, but that can also spread problems if there are issues in the code you haven't taken care of.

**Comment by lab313ru** [comment]
Problem is not editing function signature manually, but why Ghidra knows that function accepts one argument, and doesn't know that at the same time.

**Comment by KaisserbenDll** [comment]
And any one found an explanation for this ?
