### ISSUE TITLE
Getting the DefaultGraphDisplay resets the layout algorithm of the graph 

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#4060]
**Describe the bug**
Grabbing the `AttributedGraph` currently displayed in the Default Graph Display resets the layout algorithm to `Compact Hierarchical`, no matter the defaults for this kind of graph.

**To Reproduce**
1. Open any kind of function
2. Run the `Graph AST Control Flow` Decompiler Action
3. Observe that the Layout algorithm used by default is `Hierarchical Mincross Coffmann Graham`
4. Run the following code in the Jython Shell:
```python
graphService = state.tool.getService( ghidra.app.services.GraphDisplayBroker)
currentGraphDisplay = graphService.getDefaultGraphDisplay(True, None)
```
5. The Layout of the graph has changed and is now `Compact Hierarchical`

**Expected behavior**
There should be some way to get the currently displayed `AttributedGraph` from a REPL, that doesn't disturb the graph being displayed. I might be abusing this API somehow, but I see no other possibility to get the current graphDisplay. `ghidra.graph.visualization.DefaultGraphDisplayProvider#getVisibleGraph` and , `ghidra.graph.visualization.DefaultGraphDisplayProvider#displays` are both private 

**Environment:**
 - OS: Arch Linux
 - Java Version: 11.0.15
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official ghidra-sre.org distro 

**Additional Context**

I have a custom plugin that integrates Ghidra with our internal analysis tooling and am requesting certain graph results from it to display them in Ghidra for debugging/development purposes. Having those results directly in some reverse engineering tool with sync between nodes and the actual locations in the binary is awesome and makes developing this so much easier. Because I am also actively using a custom Kotlin REPL. I'd like some way to quickly get the graph, currently selected vertex, etc from my REPL to then look at the specific data associated with the node. Having the graph layout and view reset is fairly hindering in that scenario.

**Comment by dragonmacher** [comment]
I think the issue here, as mentioned, is that the graph service has no way for clients to get the currently displayed graph.  The call to `graphService.getDefaultGraphDisplay(True, None)` was meant to be used to get a graph display to be used to show a new graph, not to get the current graph.

A method to get the active graph display would fix this current issue.  There may also be other methods we could add to this service to make the API more useful.

**Comment by fmagin** [comment]
In theory it should be enough to just change `ghidra.graph.visualization.DefaultGraphDisplayProvider#getVisibleGraph` to public then.
If I bypass the private protection with reflection I can get the graph without any apparent issues:
```kotlin
val defaultGraphDisplay: ghidra.graph.visualization.DefaultGraphDisplay = (graphService.defaultGraphDisplayProvider::class.java.getDeclaredMethod("getVisibleGraph").let { it.isAccessible = true ; it}.invoke(graphService.defaultGraphDisplayProvider)
defaultGraphDisplay.graph
```

The reference to the `DefaultGraphDisplay` also allows me to get the currently selected vertex, so that's nice too.
