### ISSUE TITLE
Missing OpObjects for x86 instructions like SHR

### ISSUE THREAD

**Issue by erhlee-bird** [NationalSecurityAgency/ghidra#4064]
**Describe the bug**
A clear and concise description of the bug.

Certain x86 instructions seem to be missing `OpObjects` when calling `Instruction.getOpObjects()`.

The following example does not exhibit the issue and is how I would expect the instruction to look like when examining the operands.

```
SHR EAX,0x8
  0: EAX
  1: 0x8
```

But for a different form of the instruction, the operand is seemingly made implicit.

```
SHR EAX,1
  0: EAX
```

Looking at `Ghidra/Processors/x86/data/languages/ia.sinc`, this seems to happen for a handful of instructions that reference an `n1` construct (more in the file).

```
n1: "1" is epsilon          { tmp:1 = 1; export tmp; }
...
:RCL  rm8,n1 ...
:RCL  rm8,CL ...
:RCL  rm8,imm8 ...
...
:SHR  rm8,n1 ...
:SHR  rm8,CL ...
:SHR  rm8,imm8 ...
...
```

**To Reproduce**

```java
// Given an Instruction that is being examined, inspect the operands.
// Heads up, this is a rough pseudo-translation from Clojure and might not work as is.
Instruction instr;

System.out.println(instr.toString());
for (int i = 0; i < instr.getNumOperands(); i++) {
    for (Object opObj : instr.getOpObjects()) {
        System.out.println("  " + i + ": " + opObj.toString());
    }
} 
```

**Expected behavior**

I would have instead expected there to be an explicit Scalar OpObject representing the 1 value.

```
SHR EAX,1
   0: EAX
+  1: 0x1
```

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.14.2] NixOS 21.11
 - Java Version: [e.g. 11.0] openjdk 11.0.14
 - Ghidra Version: [e.g. 9.1.2] 10.1.2
 - Ghidra Origin: [e.g. official ghidra-sre.org distro, third party distro, locally built] official GitHub releases

**Additional context**

**Comment by ghidra1** [comment]
Fix for n1 subconstructor will be submitted:
`n1: one	is epsilon			[ one = 1; ] { export *[const]:1 one; }
`
