### ISSUE TITLE
how can i disassembler eeprom dashboard by ghidra

### ISSUE THREAD

**Issue by qusay09609447** [NationalSecurityAgency/ghidra#4069]
how can i disassembler eeprom dashboard by ghidra

**Comment by ghidra1** [comment]
Your post was very brief so I am somewhat guessing as to the real question.

A memory dump of the EEPROM would be required independent of Ghidra.   Most EEPROM programmers can also be used to read/dump the contents to a file.  A memory dump file can then be imported into Ghidra as a binary import where you select the appropriate processor and compiler spec.  It is important that a suitable import base address also be specified to properly disassemble code which executes from the ROM (i.e., boot strap).  In some case a boot strap sequence will unpack/copy code from the ROM into RAM, although this is very device/implementation dependent.  A similar binary import can be done for any unpacked/de-obfuscated RAM/ROM dump.

**Comment by qusay09609447** [comment]
Yes, I extracted the file by a programmer, but I mean how do I select the appropriate language for the EEPROM so that it is not assembled correctly

**Comment by ryanmkurtz** [comment]
When you import the new file, you click this button to choose the language:

![image](https://user-images.githubusercontent.com/5378554/161106711-77442983-e1b1-4a37-a5b1-68051df96934.png)

**Comment by ryanmkurtz** [comment]
When you import the file, you select this button to choose the language:

![image](https://user-images.githubusercontent.com/5378554/161108557-b7a61eee-952b-408f-9878-4d3c634eabf2.png)

**Comment by qusay09609447** [comment]
What the language of eeprom

**Comment by ryanmkurtz** [comment]
Ah, that is a different issue that Ghidra cannot solve for you.  You'll have to do some research on the model number of the chip you pulled the image from.

**Comment by qusay09609447** [comment]
Of course that is my problem i need to solve it

**Comment by ryanmkurtz** [comment]
I can't answer that, it depends how the chip is being used.  Is it a PC BIOS image?  Then it would likely be x86.  Is it from an embedded system?  Then it could be just about anything.  You need to provide more info for someone to make a guess.

**Comment by qusay09609447** [comment]
It used for automotive
Specifically in the dashboard, it is used to store the kilometer reading
and the temperature reading. It is part of the embedded systems

في الخميس، ٣١ مارس ٢٠٢٢ ٨:٢٠ م Ryan Kurtz ***@***.***> كتب:

**Comment by ryanmkurtz** [comment]
Sorry, that's still not the kind of info I'd need to offer any advice.  I don't think I'm going to be able to help anymore than I have.  Good luck!

**Comment by qusay09609447** [comment]
It's okay. You provided me with some information that will help me in
the future in this matter....... Thank you for your time. I hope I did
not bother you with my many questions and forgive me if I bothered you
in anything
I wish you always success in your work and life

**Comment by brainstorm** [comment]
It'd be nice to have a `raw/nolanguage/data` setting on the languages list as many EEPROMs just contain data (config, constants...), not opcodes from the main processor.

I suspect that this is what OP was asking here? Then one would define that "raw" eeprom in the memory map when analysing the flash (which eventually accesses eeprom values, not code).

**Comment by ryanmkurtz** [comment]
@brainstorm There is already a `DATA` processor.

**Comment by ghidra1** [comment]
@brainstorm This can be achieved by simply skipping auto-analysis on a binary import to prevent any automated markup.  Once imported simply disable all the analyzers.  You may still like to specify a suitable language if image corresponds to a specific memory space where word-size or endianess need to be considered.
