### ISSUE TITLE
Function call push listed seperately in decompiler output with custom SLEIGH processor

### ISSUE THREAD

**Issue by benpye** [NationalSecurityAgency/ghidra#4078]
I am trying to implement a SLEIGH processor for the TMS7000 architecture - [my current progress can be found here](https://github.com/benpye/tms7000). I am fairly confident at this point that the disassembly is correct, but I have run into trouble trying to get a useful decompiled output.

The TMS7000 is a somewhat odd architecture. The memory map is as follows:

| Addr  | Len | Desc |
| ---- | --- | ---- |
| 0x0 | 0x100 | Register File (A, B, R1-R255) |
| 0x100 | 0x100  | Peripheral File (P0-P255) |
| 0x200 | 0xFE00 | Memory |

In addition to this register file there is an 8-bit status register, an 8-bit SP and a 16-bit PC. The stack here is odd as it is an index into the register file, and the current value of SP points to the last byte pushed. Additionally the stack grows in the positive direction. As such a push is:

```
push(val)
  SP++
  *SP = val;
```

and a pop would be:

```
pop(ret)
  ret = *SP
  SP--
```

I am having trouble getting a function call decompiled correctly. The ROM I am using to test the processor is the download labeled "Original 7041rom" at http://www.alternative-system.com/en/?page=gemdos_lisa.
![Bad function call decompiled](https://user-images.githubusercontent.com/442623/158303384-dc069760-d711-4a90-a8e3-a6592e614365.png)

As shown by the p-code the call first pushes the return address onto the stack, and then performs the call, however the decompiled output is showing the push as a separate register write prior to the call - this is incorrect. I have played around with the values in the .cspec but I cannot seem to improve this output, this is the current state:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<compiler_spec>
  <data_organization>
    <pointer_size value="2" />
  </data_organization>
  <global>
    <range space="ram"/>
  </global>
  <stackpointer register="SP" space="ram" growth="positive"/>
  <returnaddress>
    <varnode space="stack" offset="-1" size="2"/>
  </returnaddress>
  <default_proto>
    <prototype name="__stdcall" extrapop="-2" stackshift="-2" strategy="register">
      <input>
        <pentry minsize="1" maxsize="1">
          <register name="A"/>
        </pentry>
        <pentry minsize="1" maxsize="1">
          <register name="B"/>
        </pentry>
      </input>
      <output>
        <pentry minsize="1" maxsize="1">
          <register name="A"/>
        </pentry>
      </output>
      <unaffected>
        <register name="SP"/>
      </unaffected>
      <localrange>
        <range space="stack" first="0x1" last="0x7c"/>
      </localrange>
    </prototype>
  </default_proto>
</compiler_spec>
```

I believe this should be correct, upon entry to the function the SP will point at the last byte of the return address, and so it's offset is -1. The local range is set to the range 1+ as stack index 0 is the last byte of the return address.

I did see similar issues in #2900 , #781 and #264 but seemingly nothing that would resolve the issue in my case. I also noticed that the MX51 processor definition omits the push/pop operations for function calls, but I'm hoping I can avoid that compromise.

As an aside I did try an experiment to define the stack space as a separate space - similar to the PIC processor - and that seemingly gave better decompiled output but is not functionally correct. There may be some way to make that work by mirroring writes to the stack space when doing any register writes, but I'm not really a fan of that approach. We can't make the register file a seperate space as even this first ROM I am using to test uses indirect memory writes (`STA`) to write to the register file.

One thing I have not tried is to eliminate the register names, I don't know if this would cause the decompiler to interpret this any differently? The alternative would be to treat all operations on R0-R255,P0-P255 as operations on their respective memory addresses and then define symbols for them.

**Comment by ghidra1** [comment]
You will likely need to define an extended 2-byte stack pointer and use that instead to keep decompiler happy.  The stack pointer should be the same size as the address space it is associated with (i.e., ram) and avoid ZEXT use on the stack pointer.  This can get tricky if the 1-byte SP is memory mapped.

In addition, based on the CALL pcode, you are storing a 2-byte value on the stack but only adjusting the stack by 1 ... seems like it should be adjusting by 2 (2-byte push).  Similarly, RETS should do a 2-byte pop.

**Comment by ghidra1** [comment]
Is memory big or little endian?  You should only use the 2-byte SP (i.e., SPX) which would eliminate the ZEXT.  I also believe your call should be using a post-increment based on the manual.  The 1-byte SP can overlap the 2-byte SPX (just be sure to factor in the endianess.  Pcode below (2-byte store) assumes big-endian.
```
$U800:2 = INT_ADD SPX, 1:2  # tmp = SP + 1
STORE ram ($U800:2), 0xf01f:2   # *tmp = 0xf01f
SPX = INT_ADD SPX, 2:1            # SP = SP + 2
CALL *[ram]0xf23d:1
```

**Comment by benpye** [comment]
Sorry, yes I was still referencing the original pcode. The memory is big endian. Unfortunately this still seems to give the same incorrect decompiler output as before.

The pcode for the CALL

```
$U580:2 = INT_ADD SPX, 1:2
STORE ram($U580:2), 0xf01f:2
SPX = INT_ADD SPX, 2:2
CALL *[ram]0xf23d:1
```

And the RETS

```
$U700:2 = INT_SUB SPX, 1:2
$U1680:2 = LOAD ram($U700:2)
SPX = INT_SUB SPX, 2:2
RETURN $U1680:2
```

![image](https://user-images.githubusercontent.com/442623/158465185-c7458621-c054-45eb-8b58-32415e25011a.png)

This is using SPX for the LDSP/STSP, using SP there (overlapping the SPX) gives a worse result

![image](https://user-images.githubusercontent.com/442623/158466568-9e06a78c-6781-41f5-84d6-3c3bb8c55430.png)

**Comment by benpye** [comment]
Ah - actually the SPX change does work, but not for the reset vector. Normal functions are working correctly but the interrupt/trap vectors are not. The call stack depth shows as `- ? -` on the LDSP and later... Still haven't found how I can make that work here but at the very least most code is now decompiling (seemingly) accurately.

**Comment by ghidra1** [comment]
Frequently interrupt processing utilizes that stack differently with its own calling convention (e.g., status may also get pushed onto stack).  If there are limited occurrences you can sometime just cope with the decompiler results as is.  Not sure we have ever added an interrupt handler calling convention to any cspec.

Please close ticket if your questions have been addressed.

**Comment by benpye** [comment]
The reset vector specifically is special. Whilst on reset the SP should be set to 1, in this case before the stack is used the SP is set to another value, and so it's from this assignment that the stack depth can be considered zero.

**Comment by ghidra1** [comment]
I was thinking of vector-based software interrupts which can act like a call.  For processor reset case I don't think you would want to alter it and I would not worry to much about the reported stack depth.  You could experiment with breaking the function into two functions after the point where the stack pointer has been initialized.
