### ISSUE TITLE
feature req from peers: don't file bug reports based on crackmes

### ISSUE THREAD

**Issue by nihilus** [NationalSecurityAgency/ghidra#408]
Just a simple and decent request from the rest of us; don't f**king file a bug request on files that works on a specific loader etc, file a bug request based on binaries that are supposed to be doing something of interest rather than being tailored for being difficult to reverse-engineer. 

Especially crackme-things, you don't see them in the wild and if you don't then there is no real interest in having that faulty PLT jumping to the GOT and changing the TLS. It just doesn't make sense, and if it doesn't make sense you must acquit!

It is out of the scope, fix it by the utils that are supposed to fix it in the first place, if that doesn't work then you screwed up. It is not a bug in ghidra per se.

**Comment by lab313ru** [comment]
You don't right, and be calmer please.
I just compiled that binary with default options using gcc.
