### ISSUE TITLE
Fix JavaDoc styling issues in UserAccessException.java

### ISSUE THREAD

**Issue by HakanIlbas** [NationalSecurityAgency/ghidra#4080]
In the JavaDoc of theOSFileNotFoundException.java class in the [Ghidra/Framework/FileSystem/src/main/java/ghidra/util/exception](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/FileSystem/src/main/java/ghidra/util/exception/UserAccessException.java) folder, there is an inconsistency regarding the JavaDoc styles (empty lines after the * and indentation issues). This issue will solve this small mistake.

**Comment by ryanmkurtz** [comment]
Hello!  Thanks for your interest in improving Ghidra!  In general, as you peruse the code, you will come across many, many javadoc inconsistencies, and even errors.  We try to address them as we touch those parts of code for coding updates, but it is typically not worth the overhead to open a PR to fix things like an extra new line in a javadoc comment.

**Comment by HakanIlbas** [comment]
Hello, thanks for your response. I understand. However is adding documentation OK?

**Comment by ryanmkurtz** [comment]
I wouldn't go out of your way to add it everywhere but if you find a particular complicated class lacking and feel like improved javadoc will help others that sounds good.

**Comment by HakanIlbas** [comment]
Hi to get back to this point. The main reason for me for contributing was because of a course I am taking at Uni together with two other students. We are supposed to make contributions to an opensource software project. I have looked at all the issues and they seem to be really hard for someone who has not used Ghidra before. Therefore i tried creating smaller issues myself that were somewhat easier. However obviously our goal is also to make some meaningful issues, for the course and for the project. Do you maybe have something easy but interesting for someone who is not really familiar with Ghidra to implement or fix?

**Comment by ryanmkurtz** [comment]
We have 1100+ open issues on GitHub, but you would likely have to make a considerable time investment learning the nuts and bolts of Ghidra to make meaningful contributions.

**Comment by HakanIlbas** [comment]
Yes, I have looked through a lot of them, but did not find any that is beginner friendly.... Considereint there are only 2-2.5 weeks left for the course, do you out of your head know something that we could tackle?

**Comment by ryanmkurtz** [comment]
I love completing an easy ticket, so if they are out there, I would have done them already :)
