### ISSUE TITLE
Analysis of big DEBUG/DWARF file fails

### ISSUE THREAD

**Issue by Kein** [NationalSecurityAgency/ghidra#4084]
**Describe the bug**
Analysis of big DEBUG/DWARF file fails

**To Reproduce**
1. Have an application with 1.7-2Gb .debug file
2. Increase item count over default 2000000 to meet the demand
3. Runa analysis

**Expected behavior**
DEBUG file processed

**Screenshots**
![image](https://user-images.githubusercontent.com/623756/158565584-3b469406-5283-4b27-af40-a521847cc6ad.png)

**Environment (please complete the following information):**
 - OS: Win10x64
 - Java Version: 11.0.13
 - Ghidra Version: 10,1,2
 - Ghidra Origin: official repo

**Additional context**
Total Ghidra memory usage (mapped) during analysis was about 3.5-4GB, I had about 10GB more left free

**Comment by Kein** [comment]
If I run it with default settings I can never complete because it always find more item records than I specify:

```
(These messages are also written to the application log file)

Skipping DWARF import because a precondition was not met:
TheMainBinary  has more DIE records (12561215) than limit of 12500000
Manually re-run the DWARF analyzer after adjusting the options or start it via Dwarf_ExtractorScript
```

**Comment by dev747368** [comment]
You will probably have to specify a larger max memory setting for your java vm to overcome the out-of-memory exception.  Uncomment the commented out 

```#MAXMEM=2g```

line in the ghidraRun start script and increase it drastically.

You can check the Help | Show VM Memory dialog to see how much memory your VM has available, and you  can keep it open when doing the dwarf import to see the damage, er, progress as it is doing its stuff.

**Comment by ryanmkurtz** [comment]
@Kein Did increasing the memory work for you?
