### ISSUE TITLE
[ARM] Invalid hex->character decoding in Decompile

### ISSUE THREAD

**Issue by mrx23dot** [NationalSecurityAgency/ghidra#4085]
Original source:
![2022-03-16 12_13_03-project - IAR Embedded Workbench IDE - Arm 8 32 1](https://user-images.githubusercontent.com/4163396/158587440-cb40f7a1-20ae-41e7-a956-3236d5464b5a.jpg)

ghidra Listing:
![2022-03-16 12_13_36-CodeBrowser_ stmdec__projec2t bin](https://user-images.githubusercontent.com/4163396/158587582-e187e7ee-ddd3-417b-af1d-d1a87df7f108.jpg)

ghidra Decompile:
![2022-03-16 12_14_15-CodeBrowser_ stmdec__projec2t bin](https://user-images.githubusercontent.com/4163396/158587639-dc9ea4d4-6e4f-4a39-a639-47e12b23e607.jpg)

should be `== 0x04` not '\0'

Project (attached) [project.zip](https://github.com/NationalSecurityAgency/ghidra/files/8262013/project.zip)
ARM:LE:32:Cortex (1.103)
Base addr 08000000

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: java 15.0.2 2021-01-19
 - Ghidra Version: 10.1.2
 - Ghidra Origin: github

**Comment by GhidorahRex** [comment]
sfsdf + 4 == 4. Subtracting 4 from both sides, sfsdf == 0. Am I missing something about the simplification?

**Comment by mrx23dot** [comment]
Hmm, looks like it still applies optimization even though I asked it to be fully off.

What about `cmp r0, #0x04` shouldn't that display == 4 in disassembly?
