### ISSUE TITLE
[ARM/Thumb2] Multi-register struct returns use bitops to retrieve fields instead of retrieving the fields directly

### ISSUE THREAD

**Issue by bigfarts** [NationalSecurityAgency/ghidra#4087]
**Describe the bug**
Multi-register struct returns do not use field names and instead use bitops to retrieve fields.

**To Reproduce**
Given this Thumb2 assembly:

```
        0801679e f7 f7 63 fe     bl         getslidedelta                                    vec2 getslidedelta(void)
        080167a2 28 77           strb       r0,[r5,#0x1c]
        080167a4 69 77           strb       r1,[r5,#0x1d]
```

where the function signature for `getslidedelta` is set to return a struct `vec2` with fields `x: uint32_t, y: uint32_t` in registers `r0`, and `r1`, respectively, the decompiler provides this output:

```
    vec2 vVar2;
    // lines omitted
    vVar2 = getslidedelta();
    unaff_r5->slidex = (uint8_t)((ulonglong)vVar2 >> 0x20);
    unaff_r5->slidey = SUB81(vVar2,0);
```

**Expected behavior**
The decompiler gives the following output:

```
    vec2 vVar2;
    // lines omitted
    vVar2 = getslidedelta();
    unaff_r5->slidex = (uint8_t)vVar2.x;
    unaff_r5->slidey = (uint8_t)vVar2.y;
```

**Environment (please complete the following information):**
 - OS: macOS 12.2.1
 - Java Version: 17.0.1
 - Ghidra Version: 10.1
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by caheckman** [comment]
This is addressed by 31b30adf2dfdd2688cc0e4e7cd01d125fc27c45b
