### ISSUE TITLE
Filter list of results in apply enum to only display options that match selected constant

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#409]
When analyzing Windows binaries in particular, it is often indispensable to rename certain numeric constants to an appropriate preprocessor macro / enum name. In Ghidra, this can be realized by using the _Apply Enum_ operation on the numeric constant. However, the list of suggested definitions is not limited to those that match the selected constant, making it near impossible in certain cases to find the correct name unless the analyst is able to discern the name by a separate lookup elsewhere. The case of Windows' `ERROR_` constants is a good example:

![56036017-05471700-5d2c-11e9-93b4-be259fbfd971](https://user-images.githubusercontent.com/11869704/56036276-bea5ec80-5d2c-11e9-988b-39aa8dd03155.png)

I think it would be great improvement to display only enums in the _Apply Enum_ dialog that actually contain an entry matching the selected constant, improving the usability of this very vital feature by magnitudes.

**Comment by huettenhain** [comment]
For everyone who is similarly new to Ghidra as myself, I will comment briefly about what I just realized: The _"Set Equate"_ action can be used to do something very similar to what I am requesting and might be what you are looking for. I will leave this issue open anyway because I think it would still be an enhancement to the _"Apply Enum"_ feature to filter out impossible options.

**Comment by dragonmacher** [comment]
We have decided not to change the feature at this time.  Admittedly, it is a bit awkward to use in its current form.   For 9.1, the **Apply Enum** action will only be enabled over a selections, which we hope will entice uses to use the **Set Equate** instead for single equate assignments.

**Comment by huettenhain** [comment]
Makes sense. As stated in my second comment, I figured out the _"Set Equate"_ a bit too late, but it is probably the better choice in many cases. Thanks for having a look!
