### ISSUE TITLE
Can IDA Pro completely replaced with Ghidra in 1 or so years ? Or maybe it can replaced now ?

### ISSUE THREAD

**Issue by Mandofskii** [NationalSecurityAgency/ghidra#4090]

**Comment by dragonmacher** [comment]
There will always be a place for both tools.  If you are referring to a specific task or architecture, then that is use-case dependent.

**Comment by Mandofskii** [comment]
@dragonmacher so I change my question.
Can one day ghidra decompiler be stronger like hexrays ?

**Comment by dragonmacher** [comment]
> @dragonmacher so I change my question. Can one day ghidra decompiler be stronger like hexrays ?

We are constantly improving and evolving the overall tool and the decompiler.  You will have to periodically try newer versions of Ghidra to see if the updates suit your needs.

**Comment by astrelsky** [comment]
> > @dragonmacher so I change my question. Can one day ghidra decompiler be stronger like hexrays ?
> 
> We are constantly improving and evolving the overall tool and the **decompiler**.  You will have to periodically try newer versions of Ghidra to see if the updates suit your needs.

 :pinocchio:
