### ISSUE TITLE
Windows Display Scaling Renders New UI Elements Off Screen

### ISSUE THREAD

**Issue by ajhalls** [NationalSecurityAgency/ghidra#41]
**Describe the bug**
I am running it on a 43" 4K monitor with scaling set to 150% and every window that opens in CodeBrowser is partially off the screen. To move it back on screen I use Alt-Space, select move and use keyboard to move it back down.

**To Reproduce**
Launch application. Also any time you select a menu item such as File Open, CodeBrowser or anything that opens a dialog will also open off screen.

**Expected behavior**
Open within confines of monitor display.

**Environment (please complete the following information):**
Windows 10 Pro 1809
Dell T7810
Nvidia Quadro M4000

**Comment by MaKiPL** [comment]
I can confirm this bug to happen also to me with 100% scalling, but TWO monitors in which the first one is vertical 1080x1920. Even though the application starts on my main horizontal 1920p screen it still gets off-screen. @ajhalls workaround works fine but the issue is quite frustrating

**Comment by ajhalls** [comment]
I also have a portrait mode monitor, but it isn't the primary.

**Comment by ajhalls** [comment]
Today working in CodeBrowser as I clicked to Export code, the ComboBox dropdown opened on a different monitor.
Here is my monitor layout:
![image](https://user-images.githubusercontent.com/5520815/54287822-02f66f00-456c-11e9-845f-afa3d68b6fcf.png)

In this next photo, the CodeBrowser is loaded in full screen mode on the far right monitor, Firefox is open to the left. When clicking the ComboBox to adjust format, it opens on the other monitor.
![image](https://user-images.githubusercontent.com/5520815/54287737-de01fc00-456b-11e9-8453-ccaf077d7e28.png)

As a side note, once after selecting something the position was then correct, but I was unable to duplicate that in subsequent attempts.

**Comment by ryanmkurtz** [comment]
We made some improvements to this which will be in our next release.  Please reopen the ticket if you continue to have problems after trying the new version.
