### ISSUE TITLE
Text edit fields in CDF/Motif not supporting clipboard operations

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#410]
**Describe the bug**
On Windows 10, when using the look & feel option _CDE/Motif_, it appears that all text edit fields stop to support the common shortcuts <kbd>Ctrl</kbd>+<kbd>C</kbd>, <kbd>Ctrl</kbd>+<kbd>V</kbd>, and <kbd>Ctrl</kbd>+<kbd>X</kbd> for the clipboard operations copy, paste, and cut, respectively.

**To Reproduce**
Steps to reproduce the behavior on Windows 10:
1. In the main Ghidra Window, select _Edit_ &rarr;  _Tool Options_.
2. Navigate to _Tool_.
3. Select the Entry _CDE/Motif_ for the _Swing Look and Feel_ option and apply these settings.
4. Restart Ghidra.
5. Attempt to use any common clipboard hotkey in a text field, for example the _Filter_ field in the Ghidra main window.

**Expected behavior**
The standard hotkeys are expected to implement the commonly known clipboard operations in all text fields.

**Environment (please complete the following information):**
 - OS: Windows 10, Version 1809, OS Build 17763.437
 - Java Version: 11.0.2
 - Ghidra Version: 9.0

**Comment by 0x6d696368** [comment]
This is a JDK **non**-issue issue (see https://bugs.openjdk.java.net/browse/JDK-6540957).
The Motif platform does not use `Ctrl+C`, hence the look and feel doesn't use it either.
They use:
```
"COPY", DefaultEditorKit.copyAction,
                          "PASTE", DefaultEditorKit.pasteAction,
                            "CUT", DefaultEditorKit.cutAction,
                 "control INSERT", DefaultEditorKit.copyAction,
                   "shift INSERT", DefaultEditorKit.pasteAction,
"shift DELETE", DefaultEditorKit.cutAction,
```
"COPY" etc. are actual keys.

**Comment by huettenhain** [comment]
Thanks a lot for looking into this, at least I now know the cause. I will close this out because it feels to me like altering this behavior in Ghidra is both out of scope and, if possible at all, much more effort than reasonable.
