### ISSUE TITLE
Debugger alters command line arguments 

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4106]
Compile the following on windows

```c
include <stdio.h>

int main(int argc, const char **argv) {
    if (argc < 2) return 0;
    puts(argv[1]);
    getchar();
    return 0;
}
```

Compile into an exe and run with the command line argument `https://www.google.com` and you will see the correct output. 

Load into Ghidra debugger, in dbgeng locally in vm, append the same command line argument and run until the results appear.

**Comment by d-millar** [comment]
@astrelsky There's a partial fix in master if you're running out of that and executing via the Objects View.  Am working on a better solution literally right now which should fix the more general case (i.e. running from the toolbar).

**Comment by d-millar** [comment]
@astrelsky No worries - one of our guys hit this on Friday, so am pretty sure I understand the issue.

**Comment by d-millar** [comment]
I want to say yes but no, i.e. not sure you can ever modify bytes from the listing - we've always forced you to go to the Byte Viewer.  However, I "think" you can modify bytes from the Dynamic equivalent of the Byte Viewer.

**Comment by astrelsky** [comment]
The memory view (debugger option under window->bytes) doesn't let you modify it.

**Comment by d-millar** [comment]
Hmmmm, yes, sadly that appears to be true.  I think there's a ticket in for this (may even be an active branch for it from @nsadeveloper789), but for the moment you may be stuck using the Interpreter window.

**Comment by astrelsky** [comment]
> Yes, the idea is to unify the machine-state modification story across the UI. Listing (via Patch Instruction, Patch Data, and Paste actions); Memory Bytes (via Paste action or editing the bytes); Registers; and Watches windows. Feature-wise, it's nearly complete, but I'm in the process of smoothing the rough edges, then testing.

Sweet. I'll be sure to break it when it's ready :p . Thanks Dans.
