### ISSUE TITLE
Hide casts

### ISSUE THREAD

**Issue by nofiv** [NationalSecurityAgency/ghidra#4108]
Is there an option to temporarily hide casts in the code listing like in [IDA](https://www.hex-rays.com/products/decompiler/manual/cmd_hide_casts.shtml) please? If not, it would be nice to add it. Hiding casts significantly improves the readability of the code in some cases.

**Comment by astrelsky** [comment]
Try the "Disable printing of type casts" option. It is located under edit, tool options, decompiler, display.

**Comment by nofiv** [comment]
Thanks a lot, it's exactly what I wanted.
