### ISSUE TITLE
Hash mismatch during download of dependency cdt-8.6.0

### ISSUE THREAD

**Issue by heryxpc** [NationalSecurityAgency/ghidra#4109]
**Describe the bug**
There is a hash mismatch for depdendency cdt-8.6.0.zip
**To Reproduce**
1. Run `gradle -I gradle/support/fetchDependencies.gradle init`
2. See error:
```
* Where:
Initialization script '/home/eryx/workspace/ghidra/gradle/support/fetchDependencies.gradle' line: 156

* What went wrong:
A problem occurred evaluating initialization script.
> assert(it.sha256.equals(generateHash(file)))
         |  |      |      |            |
         |  |      false  |            /home/eryx/workspace/ghidra/dependencies/downloads/cdt-8.6.0.zip
         |  |             '350a4015e9a3ddd49328a8af08e5c2bcfd76395e98964d241f686623e4459557'
         |  '81b7d19d57c4a3009f4761699a72e8d642b5e1d9251d2bb98df438b1e28f8ba9'
         ['name':'cdt-8.6.0.zip', 'url':'https://archive.eclipse.org/tools/cdt/releases/8.6/cdt-8.6.0.zip', 'sha256':'81b7d19d57c4a3009f4761699a72e8d642b5e1d9251d2bb98df438b1e28f8ba9', 'destination':/home/eryx/workspace/ghidra/dependencies/GhidraDev]
```

**Expected behavior**
Installation of dependencies should complete

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: [Fedora 35 kernel 5.16.13-200.fc35.x86_64]
 - Java Version: [e.g. 11.0.12]
 - Gradle Version: [7.4.1]
 - Ghidra Version: [e.g. 10.2.1]
 - Ghidra Origin: [Github Master https://github.com/NationalSecurityAgency/ghidra] 

**Additional context**
I noticed that the hash from manual download matches the expected hash:
```
$ sha256sum cdt-8.6.0.zip 
81b7d19d57c4a3009f4761699a72e8d642b5e1d9251d2bb98df438b1e28f8ba9  cdt-8.6.0.zip
```
I fixed the issue manually downloading the file and copying it to `dependencies/downloads/cdt-8.6.0.zip`

**Comment by ryanmkurtz** [comment]
I just tried this and it worked fine.  The hash we check against is the same hash you got on your manual download, so I'm not sure why it was different for you when the script downloaded it.  Is it still happening?

**Comment by ryanmkurtz** [comment]
I'm going to assume the issue was with your internet connection.  If you feel like something is wrong on Ghidra's end, please let us know and we can reopen this issue.
