### ISSUE TITLE
Allow copying currently highlighted symbol to the clipboard

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#411]
During analysis, it is often useful to copy the names of certain existing symbols in decompiled code, such as variable or function names. In Ghidra, clicking on a symbol does _highlight_ the symbol, but it does not select the text, therefore using the hotkey <kbd>Ctrl</kbd>+<kbd>C</kbd> does not copy the name of the symbol to the clipboard.

I suggest that the hotkey <kbd>Ctrl</kbd>+<kbd>C</kbd> copies the name of the currently highlighted symbol to the clipboard if the user has not selected a text region.

**Comment by huettenhain** [comment]
I just noticed that the disassembly listing already behaves in this way, but the decompiler does not. It would be very useful if the decompiler had the same feature.

**Comment by dragonmacher** [comment]
Currently, the <kbd>Ctrl</kbd>+<kbd>C</kbd> will only work in the Decompiler when there is a selection (not a highlight).  So, right now you will have to first select the symbol name before you can copy it.

I have updated, for 9.1, the copy action to copy the text under the cursor when there is no selection.
