### ISSUE TITLE
Missing tests for ArrayUtilities.java

### ISSUE THREAD

**Issue by HakanIlbas** [NationalSecurityAgency/ghidra#4110]
I noticed that ArrayUtilities.java located in ```Ghidra/Framework/Utility/src/main/java/utilities/util/``` did not have any tests. This is a beginner friendly issue. This issue's intention is to have unit tests added for ArrayUtilities.java. I also noticed that in one of the functions, there was typo, namely ```isArrayPrimativeEqual()``` should have been ```isArrayPrimitiveEqual```.

**Comment by ryanmkurtz** [comment]
This class was removed in 2a4a7747e68a9264ad8a6ef5a4c43c17d8f8ae79
