### ISSUE TITLE
Debugger: Occasional loss of memory regions

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4112]
This is going to be difficult to reproduce without a long running sample. Basically it is the same issue where you can't see the heap memory but it occurs after having been able to see it previously in the same session. Once it has disappeared it seems to be impossible to get it back. Refreshing the memory node and all of the objects does not work. It seems to happen after hitting a breakpoint, doing some stepping, refreshing some of the objects and then running for a bit until hitting a breakpoint and repeating. 

Also a minor nuisance is that some of the object nodes, notably the memory node, stay expanded and automatically re-expand themselves regardless of how many times you collapse it.

**Comment by d-millar** [comment]
@astrelsky Maybe a dumb question, but are those regions gone from the underlying debugger's point of view?  i.e. are these regions that have been freed?  If so, I guess we have several alternatives goign forward - vote for your preference.  (1) is to use the existing trace mechanism to view things, i.e. if you want to see memory from the past, use the Threads view to move back to that point.  (Guessing not your frst choice.) (2) would be to never remove memory.  (2) would not be my first choice, but might be ok if we can label it as stale in some fashion.  Adds a buch of complications for things like goto, i.e. what would the correct behavior be if the user asks to goto memory that is no longer there?  display nulls, display the last non-null value, cange the current tick to the last time in the past where it was good?

Re minor nuisance, that's weird - I have never seen that.  Which target?  All the time?  Reproducible?

**Comment by astrelsky** [comment]
The memory is still there, is valid and currently in use. It is not looking back in the trace it is in the present.


I _think_ the tree bug should be as simple to reproduce as expanding the memory node, refreshing the objects, attempting to close the node and then try to look elsewhere in the tree.

**Comment by d-millar** [comment]
No joy reproducing either today, sadly - will take another stab tomorrow.  If you hit upon other hints for reproducing, definitely post 'em.

**Comment by astrelsky** [comment]
> No joy reproducing either today, sadly - will take another stab tomorrow. If you hit upon other hints for reproducing, definitely post 'em.

I'll cook up something fun to reproduce it.

**Comment by astrelsky** [comment]
Well, I did not get very far, I gave up on what should have been a simple sample to work with. Didn't even get the chance to make it fun. The idea here is to set a breakpoint before the final string is destroyed so you have something to look at in memory. The random sleep time is to throw a wrench at the debugger.

```c++
#include <iostream>
#include <string>
#include <Windows.h>

int main() {
    for (;;) {
        int t = rand() & 0xff;
        std::string s = std::to_string(t);
        std::string msg = std::string("Sleeping for ") + s + std::string(" ms");
        std::cout << msg << std::endl;
        Sleep(t);
    }
}
```

**Comment by d-millar** [comment]
OK, got this running - thank you for the code!  And I think I have a fix.  Should be added to master next week.  Not entirely positive  I understand the problem despite the fix, so yell if you see this after the fix.

**Comment by astrelsky** [comment]
> OK, got this running - thank you for the code! And I think I have a fix. Should be added to master next week. Not entirely positive I understand the problem despite the fix, so yell if you see this after the fix.

I'm always yelling about something so you'll probably here me either way.

**Comment by d-millar** [comment]
LOL - think you've earned the right. :)

**Comment by astrelsky** [comment]
> LOL - think you've earned the right. :)

I meant more in general. You should hear me when I'm stuck working with python2 or something that hasn't been maintained in 10 years but gets used daily.

**Comment by astrelsky** [comment]
It seems to be working ok now. Unless I just got lucky. There's still the occasional comparison contract violation and things get weird when you kill the process from the objects view but I'll open separate tickets once I can get at least a log or way to reproduce those.

**Comment by astrelsky** [comment]
@d-millar regarding the fix and punting when setting a breakpoint fails. If the process being debugged is running when you try to set a breakpoint it will always punt. This means that no matter how many times you click ok to set it the popup box for setting a breakpoint will stay there. I actually sat there and held down enter to repeatedly submit it and it never took it. While it is probably an edge case a message saying you can't set it while it is running would be nice. 

As a bit of background context the process that I had in the debugger was python which was parked at a breakpoint in a python debugger which is why I didn't realize it was still technically running from Ghidra's viewpoint.

**Comment by d-millar** [comment]
@astrelsky Think I need more context.  Are you setting the breakpoint in Objects, in the Static Listing, in the Dynamic listing, in Breakpoints, or from the Interpreter?  Testing with notepad.exe (ok, not ideal in some sense, but...), breakpoints are disabled in Objects and the Breakpoint viewer, the Static listing succeeds but marks the breakpoint as "ineffective_enabled", the Dynamic listing does nothing from "OK" but you can "Cancel" out, and the Interpreter will hang but set the breakpoint on break.  Does that match what you're seeing?  Those seem sane to me, with the possible exception of bringing up the dialog at all for the Dynamic listing.  

On the other question, not sure I know what copy-on-write means in this context.  Refresh depends on the underlying API, which varies from object to object, i.e. it may provide a list, as for the registers in the dbgeng,  or it may force you to iterate, as for the modules.  It always will provide a full set - not a difference.  I can't think of any debugger that provides "new only" values, except through events.  Onec we have the set, we definitely iterate through them to compare the old and new lists.  This is necessary for the trace where we want to know creation and destruction times for the objects.

Sorry to be a little dense - coffee hasn't kicked in yet.

**Comment by astrelsky** [comment]
I was trying to set from the static listing. The bookmark gets added but is disabled so the breakpoint wasn't actually set and the popup for setting the breakpoint stays. I usually will just click ok a fewtimes and it will take it.

The copy on write is the name of the class. I don't have the documentation in front of me but you will see what I mean if you dig up the implementation details of GTree.

**Comment by d-millar** [comment]
Gotcha - will put in a ticket for the weird non-disappearing breakpoint dialog.

Re CopyOnWrite, uhh, at a loss still - CopyOnWriteSet, CopyOnWriteArraySet, CopyOnWriteArrayList?

**Comment by d-millar** [comment]
Followed up on the ObjectsTree with folks, here - understand what you were getting at now, but not the issue in this case.

**Comment by astrelsky** [comment]
> Followed up on the ObjectsTree with folks, here - understand what you were getting at now, but not the issue in this case.

Ok cool. Was just a thought and I wasn't able to check myself at the time.

**Comment by d-millar** [comment]
Yep, was a good thought and definitely worth checking - also will stop me from making that mistake in the future.
