### ISSUE TITLE
Advise needed for a .deb package.

### ISSUE THREAD

**Issue by grotius-cnc** [NationalSecurityAgency/ghidra#4114]
Hello,

I can write some c, c++ but have no experience with Ghidra. Before watching 72 hours of tutorials on Youtube i want to ask for advise.

Progress so far:
Currently i can load the `~/drafsight/linux/./drafsight` executable file into Ghidra this works. When i export the file the program starts.
I managed to get to the main function, rename argc & argv, rename some variables etc.
 
The question:
Is it possible to bypass the activation pop up window and just run the program?
I understand the c, c++ decompiler output code, and i know how to bypass it with c, c++. 
But it seems the decompiler output can not be (edited) or used to parse the assembly code backwards?

Link:
https://github.com/grotius-cnc/dump/releases/tag/1.2
https://github.com/grotius-cnc/dump/releases/download/1.2/draftSight.deb

I hope that someone can have a look at the .deb package and can give advice if this can be done?

**Comment by ryanmkurtz** [comment]
No, you cannot edit the decompiler output.  If you want to make changes to the program, export it, and run it with your changes, you are more or less limited to modifying existing assembly instructions in-place in the Listiing view.  As for your specific goals for modifying program behavior, we won't be able to help you with that.
