### ISSUE TITLE
Decompiling Function Never End

### ISSUE THREAD

**Issue by josuamanuel13** [NationalSecurityAgency/ghidra#4121]
the bug is about converting a hex value on  the decompiler to decimal "0xff" to 255 on the decompiler section, after clicking convert and pressing the decimal the decompiler start "thinking for ever" and changes never happened, after going any where(another function for example) and coming back to the function where the bug occur, the function never decompile and stay "decompiling for ever".

Steps to reproduce the behavior in my case:
1. i did Go to the Decompile of a specific function
![image](https://user-images.githubusercontent.com/60289470/161310656-09d1348c-f704-4231-95ca-1383ef16adb2.png)

2. i Clicked on convert to decimal on the 4th param, it converted ok, 
but after i clicked convert to decimal on the 5th param
![image](https://user-images.githubusercontent.com/60289470/161311437-db7a2fc6-5974-49ae-9011-283d5426aec6.png)
it just get infinite loop decompiling
![image](https://user-images.githubusercontent.com/60289470/161311566-b7df309e-7405-4230-be74-37298ee08bc5.png)

all i wanted it just to convert the hex to the decimal

Environment
 - OS: Windows 10
 - Java Version: 1.8.0_311
 - Ghidra Version: 10.0.0.2
 
![image](https://user-images.githubusercontent.com/60289470/161311993-d26b75ae-138d-4c5a-9dae-52c10dedd36b.png)

 - Ghidra Origin: official

**Comment by pjsoberoi** [comment]
Is there a reason you are on 10.0.2? 10.1.2 is the newest release of Ghidra: https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.1.2_build. 

I would recommend trying that out first. Otherwise if you can share the binary?

**Comment by josuamanuel13** [comment]
thanks for the answer, ill try the new version, if it fixed, ill report here, otherwise if error keep, ill send the binary, offset, convention, etc.

**Comment by josuamanuel13** [comment]
![image](https://user-images.githubusercontent.com/60289470/161411017-abf66e5a-6da3-46e5-b65c-ed557c475f40.png)
still happening in last version
[ac_client.zip](https://github.com/NationalSecurityAgency/ghidra/files/8403811/ac_client.zip)
Binary Image Address: 00400000
Function is intended to draw a text  in offset: 0041a150
"DrawText" Function SIgnature: void renderText (char * text, int x, int y, uchar colorx, uchar colory, uchar colorz, uchar colorw)
Reference to Usage Where Bug Happened: 461f86
Notice that i make it work converting through the disassembly convert instead the decompiler convert:
![image](https://user-images.githubusercontent.com/60289470/161411231-84194f6a-fa09-403c-bb80-cfa693231287.png)

**Comment by alex-bellon** [comment]
I am also having this issue, it's also occurring when I try to convert a hex value to binary.

```
OS: Manjaro (Linux) 21.1.6
Ghidra Version: 10.0.4 Build DEV
```
