### ISSUE TITLE
Stuck in init DB module 

### ISSUE THREAD

**Issue by sol-real** [NationalSecurityAgency/ghidra#4123]
I tried installing Ghidra today to do some CTF's and I couln't get it to run on my Manjaro Linux Machine. It always got stuck on the "init DB module" screen. I installed JDK11 and tried downloading it via git and pacman. If someone can help me getting it to start that would be awesome. If there are any logs that I should share so that it makes it easier to see what might be wrong with it then please tell me.

Thanks Sol

**Comment by dragonmacher** [comment]
You can check the application log in `{user home}/.ghidra/.ghidra_version/application.log.

Even better, the next time it is in that state, run these 2 commands from a console:
`jps`
`jstack {Ghidra pid from the last command}`

**Comment by ryanmkurtz** [comment]
@sol-real Did you get your Ghidra working?

**Comment by sol-real** [comment]
I just retried it and yes it works, but I don't know why. I haven't changed anything. Anyway thanks for the tips. If it happens again I will do what @dragonmacher recommended. Thanks for the helps everyone.
