### ISSUE TITLE
Sleigh: display variable defined in semantic section?

### ISSUE THREAD

**Issue by jjohnson651** [NationalSecurityAgency/ghidra#4129]
I'm trying to use a register in the display section that is not explicitly specified in the instruction. My situation is pretty much the same as section 7.7.1.6 in the HTML pages, where it's talking about the Address-Of operator and gives this example:
`:copyr r1 is op=0x3b & r1 { tmp:4 = &r1 + 4; r1 = *[register]tmp;}`
The only difference is I would actually like the tmp register to be displayed in disassembly output. What is the cleanest way to do this?

**Comment by mumbel** [comment]
If I understand your question, the easiest I can think will be attach another token to the registers but offset  the registers
```
define register offset=0x00  size=4 [ A B C D ];
opXY = (X,Y)
opXY0 = (X,Y)

attach variables [ opXY ] [ A B C D];
attach variables [ opXY0 ] [ B C D _ ]; # or "B C D A" if it wraps
```
`copyr opXY0 is op=0x3b & opXY0 & opXY { opXY0 = opXY; }`
