### ISSUE TITLE
How to input to stdin in the debugger?

### ISSUE THREAD

**Issue by securitytime** [NationalSecurityAgency/ghidra#4136]
I am running ghidra on Kali Linux to debug an Elf64 executable.
This binary reads from stdin via gets() or scanf().
Now when I debug this binary in ghidra via GDB/GADP the execution pauses when reaching gets(). How do I input to stdin?

**Comment by d-millar** [comment]
@securitytime Unfortunately, a known issue, and one we haven't had time to address.  That said, there are a number of workarounds.  Am going to point you to #3174 - the discussion towards the bottom should get you going.
