### ISSUE TITLE
Unable to load any default script 

### ISSUE THREAD

**Issue by lquinn2015** [NationalSecurityAgency/ghidra#4137]
**Describe the bug**
I have recently updated to ghidra_10.1.2 and all base scripts have become unavailable besides python? Not really sure what happened. I scrolled to the bundle manager and refreshed it and its returning the following 

![image](https://user-images.githubusercontent.com/16884061/162015052-36031360-e7f7-41a0-baee-418fc2195a5e.png)

I've checked for similar RESOLVE_ERROR and haven't found anything related. 

MacOS: BigSur 11.6.2
java18 via openjdk brew install:   /usr/local/Celler/openjdk/18/.... 
GHIDRA_HOME=/Applications/ghidra_10.1.2_PUBLIC/Ghidra/

**To Reproduce**
This is happening on any version of Ghidra i download,  10.1.2, 10.1, 10.0.4  

**Expected behavior**
I expect to be able to run the default scripts. When i try to i get back a cryptic "Unable to locate script class: MachO_Script.java"

**Environment (please complete the following information):**
 - OS: MacOS 11.6.2
 - Java Version: 18
 - Ghidra Version: 10.1.2
 - Ghidra Origin: github release

I've also emptied my ghidra_scripts directory

**Comment by dev747368** [comment]
Switch to jdk 11.

**Comment by ryanmkurtz** [comment]
Can you try deleting your `~/.ghidra/` directory and trying again?

**Comment by lquinn2015** [comment]
This was indeed a JDK issue. It would be cool if they tagged it better a unable to resolve error really lead me down the wrong path. Not to mention there was no logging or warning about having a newer a JDK.

**Comment by mildsunrise** [comment]
for anyone else hitting this, downgrading to JDK 11 isn't enough - you also need to delete `~/.ghidra` as indicated above
