### ISSUE TITLE
Win98 checked library symbol offset mismatch

### ISSUE THREAD

**Issue by korneliuszo** [NationalSecurityAgency/ghidra#4139]
**Describe the bug**
I'm using file with shas1um: 
d79de92ddc279c5f4d6936e08e906a9f9fb2debd  USBD.SYS
from win98ddk
and symbols don't load correctly.
I've also seen disrepancy between nm and objdump output
```
i486-w64-mingw32-objdump -t USBD.SYS  | grep Trace
[989](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00009a68 _USBD_Debug_Trace_Level

i486-w64-mingw32-nm USBD.SYS  | grep Trace
0001ed68 D _USBD_Debug_Trace_Level
```
**Steps to reproduce**
Load USBD.SYS into ghidra.
data is at address 0x00019a68
Symbol is at address 0x0001ed68

Offset of 0x15300 is start of .data section (section 2)

**Expected behavior**
Symbol and data points to same address

**Environment (please complete the following information):**
 - OS: Linux manjaro
 - Java Version: 17.0.3
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official build

**Comment by ryanmkurtz** [comment]
Can you either provide the binary or a link to where the proper DDK can be downloaded?

**Comment by korneliuszo** [comment]
Here:
[usbd.zip](https://github.com/NationalSecurityAgency/ghidra/files/8459035/usbd.zip)

**Comment by korneliuszo** [comment]
It looks like it's simmilar problem to #3564

**Comment by ryanmkurtz** [comment]
Thanks, this is something I'm currently looking into.

**Comment by ryanmkurtz** [comment]
Well, I fixed the invalid file index errors so the load completes without error, but I'm still dealing with  `_USBD_Debug_Trace_Level` being put at `0001ed68`.  How do you know it should go at `00019a68`?

**Comment by ryanmkurtz** [comment]
The issue seems to be that the symbols report that they are associated with a section, so we are dropping the symbol at their offset plus the start of that section.  But in reality, they should be placed at their offset plus the image base.

**Comment by korneliuszo** [comment]
It's my guess based on:
- see for example USBD_CreateDevice - there is line if(2 < _DAT_00019a68) which calls FUN_00014ee0 which checks again this variable and does DbgPrint
- subtracting section offset I land on this variable

**Comment by korneliuszo** [comment]
Can you just expose ignoring offset on checkbox when loading?

**Comment by ryanmkurtz** [comment]
I could as a last resort, but I'd rather understand the correct way of handling theses symbols.

**Comment by ryanmkurtz** [comment]
I think I have the solution.  Are you able to build Ghidra from source?

**Comment by korneliuszo** [comment]
didn't try but I should be able

**Comment by korneliuszo** [comment]
ok, I can build from sources.

**Comment by ryanmkurtz** [comment]
Ok I'll have something for you to try by tomorrow morning.

**Comment by ryanmkurtz** [comment]
If you build [my branch](https://github.com/ryanmkurtz/ghidra/tree/COFF-symbols) you can test out the changes.

**Comment by korneliuszo** [comment]
It solves some symbols, but PAGE section is offseted
For example:
i486-w64-mingw32-nm USBD.SYS | grep _USBD_CreateDevice@20
00025f50 T _USBD_CreateDevice@20
and this symbol is exact offseted by PAGE section offset
(  4 PAGE          0000446f  0001a1f0  0001a1f0  0000a1f0  2**2)
which is in export table located at 0x01bd60 (USBD_CreateDevice)

**Comment by ryanmkurtz** [comment]
Ok, what I did was kind of a guess, so it's back to the drawing board.  If you'd like to get it 100% working while I figure out when exactly to use section offsets vs image base offset, you can modify this snippet of code in my branch: 

https://github.com/ryanmkurtz/ghidra/blob/2304719c642db06ae6538fbc88f2ea8ba43ac20a/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/AbstractPeDebugLoader.java#L365-L378

Just put
```
address = program.getImageBase();
```
right before
```
address = address.add(Integer.toUnsignedLong(val));
```
on line 378

**Comment by korneliuszo** [comment]
Hack looks like it is working.

**Comment by ryanmkurtz** [comment]
Ok.  I'll probably have to use image base offsets for everything if it's a driver, even though I don't understand the true reason behind it.  Every tool I see is using section offsets which would get it wrong too, except IDA which knows something we don't I guess.
