### ISSUE TITLE
Running Ghidra Server behind NAT

### ISSUE THREAD

**Issue by Thalhammer** [NationalSecurityAgency/ghidra#414]
**Describe the bug**
Running the Ghidra server behind a NAT Firewall does not work.

**To Reproduce**
1. Install Ghidra Server on a Linux PC behind a Firewall
2. Forward Ports 13100, 13101 and 13102 to the PC
3. Try connecting from client PC using to the public side of the firewall

**Expected behaviour**
The connection should work fine.

**Environment (please complete the following information):**
 - OS: Debian 9, current updates, OpenJDK 11 via Backports
 - OS (Client): elementary OS 5, current updates, openjdk 11 from apt
 - Java Version: 11.0.1 2018-10-16 (client) / openjdk 11.0.3 2019-04-16 (server)
 - Ghidra Version: 9.0.2

**Additional context**
I did a Wireshark capture and I can see a connection getting opened and some information exchanged.
Wireshark:
The client opens TCP to port 13101 on public IP.
Some information is exchanged + TLS init.
The client tries to connect to server private IP port 13101 which obviously fails.
After some time it gives up and the GUI displays "Connection to server failed (<hostname>:13101)".

Apparently, it somehow transmits the private IP to the client, which not just causes it to fail, but is also a security problem (information leak).
How can I configure the server to use the public hostname instead of the private IP?

**Comment by dev747368** [comment]
This issue is similar to the issue with the ftp protocol, where it uses 2 ports and communicates information about opening the second connection via the first, which would cause failures when naively natted.
We don't have a solution for you that would allow this to work in a NAT env right now.

**Comment by Thalhammer** [comment]
Is there any workaround for this?
I tried setting java.rmi.server.hostname as well as java.rmi.server.useLocalHost in various combinations, however, it seems as if it is completely ignored by the server.

**Comment by ryanmkurtz** [comment]
See #645
