### ISSUE TITLE
SLEIGH: How to handle non-adjacent register bits?

### ISSUE THREAD

**Issue by pjsoberoi** [NationalSecurityAgency/ghidra#4140]
I am working on ticket #4125 for PowerPC VMX128 instruction support. I'm stuck on how to support register fields where the bits are non-adjacent. Here is an example:

```
# 000100AAAAABBBBBCCCCC0001000AA11
# lvewx128 vr0, r0, r0
:lvewx128 regA_02_03, regB_16_20, regC_11_15 is opcode_26_31=0b000100 & regA_02_03 & regB_16_20 & regC_11_15 & opcode_04_10=0b0001000 & regA_02_03 & opcode_00_01=0b11
{}
```
The lvewx128 instruction has three registers: vr0-vr127, r0-r31, and r0-r31. The bits for which vr register to use are bits 2-3 and bits 20-25. See the "A" bits in the above opcode example. How do I support this? I'm unclear what I need to do in my "attach variables" section. Thanks.

**Comment by GhidorahRex** [comment]
the best way to handle that is to have 4 attach statements for bits 2-3 being 00/01/10/11 and put them in subconstructors. See the ARMNeon.sinc file to see how we handle it for the D and Q registers.
