### ISSUE TITLE
Processor compiler combination required

### ISSUE THREAD

**Issue by kiranravindran90** [NationalSecurityAgency/ghidra#4147]
I have a Binary that was flashed on a processor with below specs.
I am not sure which exact Processor, Bit, Endian, Compiler combinations to use?
**Specs**
Architecture:             aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:               Little Endian
CPU(s):                      8
On-line CPU(s) list:    0-7
Model:                       0
Model name:             ARMv8 Processor rev 0 (v8l)
Compiler:                  aarch64-gnu-linux GCC compiler

Note: The Binary I am testing is just 1 of the 11 Binaries flashed on this processor.

**Comment by astrelsky** [comment]
> I have a Binary that was flashed on a processor with below specs.
> I am not sure which exact Processor, Bit, Endian, Compiler combinations to use?
> **Specs**
> Architecture:             **aarch64** <- processor 
> CPU op-mode(s):      32-bit, **64-bit** <- bits
> Byte Order:               **Little Endian** <- endianess
> CPU(s):                      8
> On-line CPU(s) list:    0-7
> Model:                       0
> Model name:             ARMv8 Processor rev 0 **(v8l)** <- variant (closest and only available is v8a)
> Compiler:                  aarch64-gnu-linux **GCC** compiler <- compiler (also the default)
> 
> Note: The Binary I am testing is just 1 of the 11 Binaries flashed on this processor.

 
`AARCH64:LE:64:v8A​:default`

**Comment by kiranravindran90** [comment]
@astrelsky Thank you for the quick response :)
Sorry for a very delayed follow up, I was caught up with something else.

I had tried as you mentioned. **AARCH64 : LE : 64 : v8A : default** quite straight forward & tried that, but the result didnt look complete. I could see some functions/instructions it did disassemble well but majority were just "??"

Below is just a snippet of the analyzed Binary. We can see some instructions have been identified while a lot are just "??"

![image](https://user-images.githubusercontent.com/90866692/176100605-9d7b3952-f169-4d0e-9d48-f4202e94ee21.png)

Want to know the reason for this. Is it something I am not selecting right or the input file is not supported or something?
