### ISSUE TITLE
Support for more than 65535 segments in ELF64

### ISSUE THREAD

**Issue by IridiumXOR** [NationalSecurityAgency/ghidra#4149]
Hi,
as specified by man elf and also in [ELF64 specs](https://docs.oracle.com/cd/E18752_01/pdf/817-1984.pdf)

`e_phnum` 

`This member holds the number of entries in the program header table.  Thus the product of e_phentsize and e_phnum gives the table's size in bytes.  If a file has no program header, e_phnum holds the value zero.
If the number of entries in the program header table is larger than or equal to PN_XNUM (0xffff), this member holds PN_XNUM (0xffff) and the real number of entries in the program header table is  held  in  the  sh_info member of the initial entry in section header table.  Otherwise, the sh_info member of the initial entry contains the value zero.`

`PN_XNUM
This is defined as 0xffff, the largest number e_phnum can have, specifying where the actual number of program headers is assigned.`

This is a issue if you try to load, for example, a QEMU virtual memory dump (`memsave` command) because the ELF64 contains more than 65535 segments and Ghidra is not able to show, access and operates on any segment on the file (returning only a big `unallocated_0` segment.)
Please can you fix it?

I attach [here](https://github.com/NationalSecurityAgency/ghidra/files/8466125/test_elf_segments.zip) a "synthetic" example: it contains 131070 segments, the firsts 65535 point to offset 0x1040 the second ones to the offset 0x2040. I created it because QEMU `memsave` dumps have a size equal to the VM RAM, so they are very big. `readelf` is able to parse it correctly, while `file` inform you that it has too much segments

**Comment by ghidra1** [comment]
I will add ELF support for this - but this will make for one really big Program.  Not sure where else Ghidra may start to squeak for such large programs.  Import is definitely very slow.  Fixing progress monitor to provide better feedback when loading blocks.

**Comment by ghidra1** [comment]
You sample (7,348,240 byte file) produced an initial program database which was 49,741,824 bytes (~7x growth) representing 275,775,504 bytes  in memory block storage.  FileBytes mapping for memory blocks accounts for the smaller database size, although there still appears to be a significantly larger footprint than the original file size.  This would not be the case for a real dump file where each block would correspond to a unique set of bytes from the file.  Given the amount of FileBytes mapping that should account for the bulk of the resulting program I am rather concerned about the increase in size and the poor performance during import.  This will require additional investigation.

**Comment by ryanmkurtz** [comment]
Closed by d7f9cdfe5cfaae205739501b62a7797baaec280a

**Comment by ghidra1** [comment]
@IridiumXOR some changes are in the works should greatly improve the import performance
