### ISSUE TITLE
Failed to identify call spec of `printf` for some compiler

### ISSUE THREAD

**Issue by ucasqsl** [NationalSecurityAgency/ghidra#4154]
**Describe the bug**
wrong `FuncCallSpec` of `printf` for some file compiled with `clang-10`

**To Reproduce**
1. compile the following file with clang-10
```C
#include <stdio.h>
#include <stdlib.h>
void foo() {
    int ****a = malloc(10 * sizeof(int**));
    for (int i = 0; i < 10; i++) {
        a[i] = malloc(10 * sizeof(int**));
        for(int j = 0; j < 10; j++) {
            a[i][j] = malloc(sizeof(int*));
            *a[i][j] = malloc(sizeof(int));
            **a[i][j] = i;
            printf("%d", **a[i][j]);
        }
    }
}

int main() {
    foo();
    return 0;
}
```
2. decompile it with ghidra

**Expected behavior**
function `printf` should be called correctly in function `foo`.

**Screenshots**
![image](https://user-images.githubusercontent.com/90229858/163335493-3e1c1ab1-8b1b-4a6b-97ef-5ab33cdb7f07.png)

**Attachments**
[0x13_ptr4.zip](https://github.com/NationalSecurityAgency/ghidra/files/8487195/0x13_ptr4.zip)

**Environment (please complete the following information):**
 - OS: Arch Linux 
 - Java Version: java-18-openjdk
 - Ghidra Version: 10.1.2-1
 - Ghidra Origin: archlinux community/ghidra 10.1.2-1

**Additional context**
Executable compiled with clang-13 can be decompiled properly.

The assembly of that bb for clang-10 version:
![image](https://user-images.githubusercontent.com/90229858/163338589-391d37f1-fb22-47d5-9bff-4b720e235a82.png)

The assembly of that bb for clang-13 version:
![image](https://user-images.githubusercontent.com/90229858/163338406-681ff443-a40d-4a6e-849e-040e72b6f8f2.png)

and the decompilation result
![image](https://user-images.githubusercontent.com/90229858/163338757-deeb496a-93e9-428e-be36-62b05302cfba.png)

Why is the result different for those almost identical codes?

**Comment by astrelsky** [comment]
https://user-images.githubusercontent.com/46897303/163356907-fa7ebce1-dec2-4bf9-afcb-3c2dc47ab0a5.mp4

Has the function signature for `printf` been properly set? You can also run the variadic function signature analyzer (I forget its name) which should automatically apply overrides to functions like `printf` to specify the parameter types in the call deduced from the format string.

**Comment by ghidracadabra** [comment]
To elaborate on what @astrelsky suggested: Analysis -> One Shot -> Variadic Function Signature Override (from the Code Browser)

The number of parameters to `printf` depends on the call site.  Without additional information, the decompiler attempts to determine the number of parameters passed to a callee based on the body of the caller.  Sometimes it gets it wrong.  Fortunately, for `printf`, the number of parameters (and their types) can just be read off of the format string and applied to that particular call site.  That's what this analyzer does.

**Comment by ucasqsl** [comment]
> 

thanks, but one shot analyses are grayed out on my computers
<img width="587" alt="image" src="https://user-images.githubusercontent.com/90229858/163502672-ecdbef93-e7fc-486c-a475-189ad65a0aa0.png">
should I do some additional configuration to use those analyses?
By the way, this is just an example of my problem, what I actually try to do is use ghidra's sleigh library to do some binary analysis, can I do this kind of analysis with sleigh C++ API? I want to obtain right FuncCallSpec the first time,

**Comment by emteere** [comment]
You can turn on the Variadic Function Signature Override analyzer mentioned above when you first analyze the binary after import.  If it works well for the binaries you are working with, you can turn it on by default all the time and save the options as you like them with the Save... button in the Analysis Options window.

Not sure why the One-Shot's are all greyed out.  Try putting the cursor in the listing to make sure the program has focus, and then go back to the OneShot menu.  It shouldn't be greyed out.

**Comment by astrelsky** [comment]
> Not sure why the One-Shot's are all greyed out.  Try putting the cursor in the listing to make sure the program has focus, and then go back to the OneShot menu.  It shouldn't be greyed out.

It is greyed out because the cursor isn't in the listing. If it is anywhere except the listing the whole menu is greyed out. Is this not the intended behavior?

**Comment by ucasqsl** [comment]
> 

Thanks @emteere @astrelsky , After putting the cursor in the listing, it works. It seems to be implemented in Java, so maybe it's not possible to access it in `sleigh`. :cry:

**Comment by ucasqsl** [comment]
Even with `Variadic Function Signature Override`, sometimes it cannot recover the parameter properly.
 for example, when the same code is compiled with `-O2` option, the code will look like this:
![image](https://user-images.githubusercontent.com/90229858/164246998-df8234bb-8522-458c-963c-495b13cb1cf5.png)
and the result won't change even if you run `Variadic Function Signature Override`.
[0x13_ptr4.zip](https://github.com/NationalSecurityAgency/ghidra/files/8522108/0x13_ptr4.zip)

**Comment by ucasqsl** [comment]
Can we reopen this issue? @ryanmkurtz

**Comment by ghidracadabra** [comment]
@ucasqsl  If you apply the correct overrides manually (by right-clicking on the calls to `printf` in the decompiler and selecting `Override Signature`) is the decompiler output correct?  (i.e., are the overrides not being applied by the analyzer or are they being applied by the analyzer but ignored by the decompiler)?

**Comment by ucasqsl** [comment]
>  If you apply the correct overrides manually (by right-clicking on the calls to printf in the decompiler and selecting Override Signature) is the decompiler output correct?

if I correct the overrides manually, the output is right, but the `Variadic Function Signature Override` won't change it for me when I put the cursor on the listing for the call, and run that one shot analysis.

**Comment by Katharsas** [comment]
Hi,
i think i have a very similar problem. The interesting thing is that i decompiles two executables that are almost exact copies. In one of them, Ghidra succesfully applied overrides automatically, while in the other it did not:

First (listing):
----
![grafik](https://user-images.githubusercontent.com/1922573/170843062-1c0599c4-1082-4c21-90aa-b93e403116a5.png)
----
First (decompiled):
----
![grafik](https://user-images.githubusercontent.com/1922573/170843124-2ac7f97a-a045-49f2-a1dd-e3deceea51ba.png)
----

Second (listing):
----
![grafik](https://user-images.githubusercontent.com/1922573/170843094-0db249ac-752d-4e00-bb76-80acc3555ce8.png)
----
Second (decompiled):
----
![grafik](https://user-images.githubusercontent.com/1922573/170843172-dd6008ee-ce57-4bba-9274-a6370c482d11.png)
----

What i find interesting is that in the first example, it correctly analysed that EAX is used first as input and then as return value for the call to `MySound_ErrorMessageLookup`, while in the second example it seems to mix them up. I tried manually doing `Commit Params/Return`, but i cannot fix it in the second example. In both examples, re-creating the function will end up with the decompilation shown above.

So i think the cause for the printf paramter problem in my case is not the printf itself, but that Ghidra struggles to identify its parameters before the call.

**Comment by ghidracadabra** [comment]
@ucasqsl I think the issue you are having is that because the format strings in your use case are so short, they are not defined as strings by the ascii string analyzer.  So, when the variadic override analyzer runs, it goes down a code path where it applies some quick heuristics to try to determine what the format string is.  I think it will be pretty easy to fix this particular case, but this should really be handled more generally.  There's some relevant discussion on issue #4281.

**Comment by ghidracadabra** [comment]
@Katharsas `My_printf` is not in the data type archives that are distributed with Ghidra.  Have you saved its signature and marked it as `Varargs` in your program?

**Comment by Katharsas** [comment]
@ghidracadabra yes i think so:
![grafik](https://user-images.githubusercontent.com/1922573/171287479-3ebaaa94-2841-44c0-a5c8-733a53190087.png)

**Comment by ghidracadabra** [comment]
@Katharsas Hmmm..not sure what's going on.  Have you committed the params and return of `MySound_ErrorMessageLookup`? I think you have but might as well verify.  If you've committed the params of `My_printf` and marked it as Varags then when you run the Variadic Function Signature analyzer it should apply the override.  This should inform the decompiler that the output of `MySound_ErrorMessageLookup` is being used and cause a local variable to be created.

What happens if you apply the override manually? (Right-click on the call to `My_printf` in the decompiler, select `Override Signature` and enter `int My_printf(char *, char *)`).  You might have to choose the correct calling convention as well - from your snippet I would guess `__cdecl`
