### ISSUE TITLE
GhidraScript access to gdb monitor commands

### ISSUE THREAD

**Issue by mfthomps** [NationalSecurityAgency/ghidra#4155]
I'm running gdb locally IN-VM and interacting with the Simics gdb server.  I'd like a GhidraScript to send gdb the monitor command and read the results.  Is there a way to access the GdbManagerImpl from a GhidraScript, or some other way to interact with gdb from a GhidraScript?

**Comment by d-millar** [comment]
@mfthomps Wow - interesting question.  This will require a little thought and maybe some testing, however, as I've never actually tried to access the debugger from a script....

**Comment by mfthomps** [comment]
The use-case is a Ghidra alternative to IDA Pro as the debug client for https://github.com/mfthomps/RESim  Most of the IDA Pro scripting for RESim uses Ida's SendGDBMonitor API, e.g., for reverse execution.   Thanks!

**Comment by astrelsky** [comment]
Here is how you can obtain the `GdbManagerImpl` instance from a `GhidraScript`.

```java

import ghidra.app.plugin.core.debug.gui.objects.ObjectUpdateService;

public class DebuggerSampleScript extends GhidraScript {

}

**Comment by mfthomps** [comment]
Thank you!

**Comment by d-millar** [comment]
@astrelsky thanks!  saving that example!

**Comment by astrelsky** [comment]
> @astrelsky thanks!  saving that example!

If it works out then maybe it's a good idea to make the manager more accessible through an interface so reflection isn't necessary. There may currently exist a better way I just saw what I initially thought was it and short circuited.
