### ISSUE TITLE
Bad Disassembly, Sea of Red Bookmarks

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4159]
**To Reproduce**
1. Compile the following code in a visual studio developer command prompt with the command `cl /Zi /clr main.cpp`
    ```cpp
    #include <iostream>

    int main() {
        std::cout << "Hello World" << std::endl;
        return 0;
    }
    ```
2. Import the resulting program into Ghidra and run analysis
3. See thousands of error bookmarks

**Expected behavior**
It should disassemble properly and not create error bookmarks everywhere. Alternatively, it should not disassemble at all. The former is preferred.

Insert generic *but IDA can do this* remark here.

**Attachments**
[main.zip](https://github.com/NationalSecurityAgency/ghidra/files/8498814/main.zip)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22000.613]
 - Java Version: 11.0.14.1
 - Ghidra Version: All public versions
 - Ghidra Origin: [e.g. official ghidra-sre.org distro, third party distro, locally built] All of the above

**Additional context**
Microsoft sucks

**Comment by emteere** [comment]
I see the issue.  It is mixed .NET Managed code and native code.
I have a prototype fix that should work for both the upcoming patch release, and master.

We're in the process of fully supporting .NET code in the near future.

**Comment by astrelsky** [comment]
> I see the issue. It is mixed .NET Managed code and native code. I have a prototype fix that should work for both the upcoming patch release, and master.
> 
> We're in the process of fully supporting .NET code in the near future.

Sweet, thank you. I actually struggled quite a bit finding something that could do both. It turned out I didn't actually need that though so I gave up.

**Comment by astrelsky** [comment]
@emteere when you say "in the process" and "in the near future" does this mean it is currently being worked on?  Is there a timeline for it? I don't mean to be pushy or impatient but I'm excited about it.

**Comment by emteere** [comment]
An update to the parsing of the .Net data structures is nearing closure.  The CLR processor is almost complete.  Can't promise a hard date or that it will be in 10.2, but is on the near term list to finish up.

**Comment by astrelsky** [comment]
> An update to the parsing of the .Net data structures is nearing closure.  The CLR processor is almost complete.  Can't promise a hard date or that it will be in 10.2, but is on the near term list to finish up.

Awesome. I'll go around telling people it's coming in 10.2 then :p. On a serious note I contemplated trying my hand at creating a .net sleigh spec last weekend. Glad I didn't waste my time :sweat_smile:
