### ISSUE TITLE
Missing struct field references when array accesses are involved

### ISSUE THREAD

**Issue by NeedsMoreFlux** [NationalSecurityAgency/ghidra#416]
**Describe the bug**

Ghidra does not find references to a struct field when it is accessed through an array that is indexed by a field from a different struct.

**To Reproduce**

1. Compile the following C program to an architecture of your choosing, making sure to include debug information. I've tested on x86_64 and ARM and have confirmed the bug on both.
```c
#include <stdio.h>

typedef struct A {
	int a1, a2;
} A;
typedef struct B {
	int b1;
	int index;
} B;
typedef struct C {
	int c1;
	A *as;
} C;

int test(C *c, B *b) {
	return c->as[b->index].a2;
}

int main(int argc, char **argv) {
	A as[3] = { 0 };
	B b = { 0, 1 };
	C c = { 0, as };
	printf("%d\n", test(&c, &b));
	return 0;
}
```
2. Import the binary into Ghidra, let it auto-analyze the file, and make sure that the function signatures have been correctly applied to the `test` function. (For some reason the x86_64 binary was not doing this automatically and I had to manually apply the `test` function signature from the data type manager, under `<binary name>/DWARF/test.c/test`).

For reference, here is the disassembly I get for the ARM binary:
```
                     **************************************************************
                     *                          FUNCTION                          *
                     **************************************************************
                     int __stdcall test(C * c, B * b)
     int               r0:4           <RETURN>
     C *               r0:4           c
     B *               r1:4           b
     undefined4        Stack[-0x4]:4  local_4                                 XREF[2]:     00010498(W), 
                                                                                           000104d0(*)  
     undefined4        Stack[-0xc]:4  local_c                                 XREF[2]:     000104a4(W), 
                                                                                           000104ac(R)  
     undefined4        Stack[-0x10]:4 local_10                                XREF[2]:     000104a8(W), 
                                                                                           000104b4(R)  
                     test                                            XREF[3]:     Entry Point(*), main:00010548(c), 
                                                                                  .debug_frame::00000018(*)  
00010498 04 b0 2d e5     str        r11,[sp,#local_4]!
0001049c 00 b0 8d e2     add        r11,sp,#0x0
000104a0 0c d0 4d e2     sub        sp,sp,#0xc
000104a4 08 00 0b e5     str        r0,[r11,#local_c]
000104a8 0c 10 0b e5     str        r1,[r11,#local_10]
000104ac 08 30 1b e5     ldr        r3,[r11,#local_c]
000104b0 04 20 93 e5     ldr        r2,[r3,#0x4]
000104b4 0c 30 1b e5     ldr        r3,[r11,#local_10]
000104b8 04 30 93 e5     ldr        r3,[r3,#0x4]
000104bc 83 31 a0 e1     mov        r3,r3, lsl #0x3
000104c0 03 30 82 e0     add        r3,r2,r3
000104c4 04 30 93 e5     ldr        r3,[r3,#0x4]
000104c8 03 00 a0 e1     cpy        r0,r3
000104cc 00 d0 8b e2     add        sp,r11,#0x0
000104d0 04 b0 9d e4     ldr        r11=>local_4,[sp],#0x4
000104d4 1e ff 2f e1     bx         lr
```

and the corresponding decompiled output is:

```c
int test(C *c,B *b)

{
  return c->as[b->index].a2;
}
```

For the x86_64 binary, the disassembly is:

```
                     **************************************************************
                     *                          FUNCTION                          *
                     **************************************************************
                     int __stdcall test(C * c, B * b)
     int               EAX:4          <RETURN>
     C *               RDI:8          c
     B *               RSI:8          b
     undefined8        Stack[-0x10]:8 local_10                                XREF[2]:     001006ae(W), 
                                                                                           001006b6(R)  
     undefined8        Stack[-0x18]:8 local_18                                XREF[2]:     001006b2(W), 
                                                                                           001006be(R)  
                     test                                            XREF[4]:     Entry Point(*), main:00100734(c), 
                                                                                  0010081c, 001008d0(*)  
001006aa 55              PUSH       RBP
001006ab 48 89 e5        MOV        RBP,RSP
001006ae 48 89 7d f8     MOV        qword ptr [RBP + local_10],RDI
001006b2 48 89 75 f0     MOV        qword ptr [RBP + local_18],RSI
001006b6 48 8b 45 f8     MOV        RAX,qword ptr [RBP + local_10]
001006ba 48 8b 50 08     MOV        RDX,qword ptr [RAX + 0x8]
001006be 48 8b 45 f0     MOV        RAX,qword ptr [RBP + local_18]
001006c2 8b 40 04        MOV        EAX,dword ptr [RAX + 0x4]
001006c5 48 98           CDQE
001006c7 48 c1 e0 03     SHL        RAX,0x3
001006cb 48 01 d0        ADD        RAX,RDX
001006ce 8b 40 04        MOV        EAX,dword ptr [RAX + 0x4]
001006d1 5d              POP        RBP
001006d2 c3              RET
```

which, after manually applying the function signature for `test`, decompiles to:

```c
int test(C *c,B *b)

{
  return c->as[(long)b->index].a2;
}
```
3. In the decompiler view for the `test` function, right click on `a2` and choose `Find Uses of A.a2`. Notice that the references list shows no usage of `A.a2` in function `test`.

**Expected behavior**

I would expect Ghidra to be able to find this struct field usage correctly. It's especially confusing when Ghidra reports zero references to a struct field that you just right clicked on to search for usages.

**Environment (please complete the following information):**

 - OS: Ubuntu 18.04 x86_64
 - Java Version: 11.0.1
 - Ghidra Version: 9.0.1 and 9.0.2

**Additional context**

I did a little bit of debugging and seem to have narrowed the bug down to the implementation of [DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.findVariablesInLine(ClangLine, List<DecompilerReference>)](https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/DecompilerDependent/src/main/java/ghidra/app/extension/datatype/finder/DecompilerDataTypeReferenceFinder.java#L339). The issue is that `findVariablesInLine` only performs a linear scan over the tokens in the line and assumes that every `ClangFieldToken` applies to the most recently seen `ClangVariableToken` - this is done by adding the current `ClangFieldToken` to `access`, which is the `VariableAccessDR` instance representing the last `ClangVariableToken` that has been processed.

In the test case of `c->as[b->index].a2`, as `findVariablesInLine` iterates over the tokens in the line, it first creates a `VariableAccessDR` for `c` and then adds `as` as a subfield to it. When it encounters the `ClangVariableToken` for `b`, it creates a new `VariableAccessDR` for `access` and sets its `variable` field to `b`. Similar to the handling of `c` and `as`, `index` is then added as a subfield of `b`. However, when the `a2` `ClangFieldToken` is reached, `access` is now the `VariableAccessDR` for `b` instead of `c`, and `a2` is added as an additional subfield to `b`, which is incorrect.

This behavior can be summarized by looking at the `DecompilerReference` instances that get added to `List<DecompilerReference> results` when `findVariablesInLine` parses the line `return c->as[b->index].a2;`. On ARM, the following two references are added:

```
{
	variable: 	{
		variable: c,
	},
	data type: C *,
	sub fields: 	[{
		variable: as,
	}],
	line 5: return c->[|as|][b->index].a2;,
	function: test
}, {
	variable: 	{
		variable: b,
	},
	data type: B *,
	sub fields: 	[{
		variable: index,
	}, {
		variable: a2,
	}],
	line 5: return c->as[b->[|index|]].a2;,
	function: test
}
```

and on x86_64, the situation is similar, though with some added casts:

```
{
	variable: 	{
		variable: c,
	},
	data type: C *,
	sub fields: 	[{
		variable: as,
	}],
	line 5: return c->[|as|][(long)b->index].a2;,
	function: test
}, {
	variable: 	{
		casts: [{
		variable: long,
	}],
		variable: b,
	},
	data type: B *,
	sub fields: 	[{
		variable: index,
	}, {
		variable: a2,
	}],
	line 5: return c->as[(long)b->[|index|]].a2;,
	function: test
}
```

In both cases, two `VariableAccessDR` instances are added to the `results` list - one for `c` and one for `b` - and the `a2` subfield is added to the `b` reference instead of `c`.

I would imagine that a fix for this would require keeping some sort of stack of `VariableAccessDR` for each line as it is processed, then pushing/popping appropriately based on the presence of certain tokens, e.g., `[` and `]`. I don't think array access is the only case that could trigger this bug either - I could imagine a line like `some_func(x->y)->z` resulting in the same issue.

**Comment by dragonmacher** [comment]
This an exemplary write-up.    We should be able to reproduce the issue using this information.
