### ISSUE TITLE
Function like GdbManagerImp.captureConsole to return gdb stderr within Debugger

### ISSUE THREAD

**Issue by mfthomps** [NationalSecurityAgency/ghidra#4160]
A gdb client displays the results of the "monitor" command using stderr.  The GdbManagerImp.captureConsole only provides stdout from gdb.  A function to capture gdb console stderr would allow for GhidraScripts that rely on "monitor" to enhance gdb, e.g., the RESim extensions to Simics.

**Comment by d-millar** [comment]
Putting in a ticket for this - thanks!

**Comment by nsadeveloper789** [comment]
I'm not sure the exact requirements you're asking for here, but I believe they are satisfied by the TraceRMI stuff (Python-based integration). All debugger output (stdout and stderr) is now printed into an embedded VTE in Ghidra. By default, the target's stdio is also via the same VTE, though gdb can be easily configured to route target stdio to a separate one (and we support that via a checkbox in the launcher).

If you need programmatic access to stdio, you may find it in the `TerminalService`. If you need to separate stdout from stderr, you may need to develop a custom launcher script. These are just bash scripts or batch files with special metadata in the headers to describe configuration parameters. You should be able to allocate additional VTEs and/or redirect your streams accordingly. Feel free to re-open or submit a new issue if you'd like to follow up.
