### ISSUE TITLE
M68000: Unknown lines in pseudo code

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#417]
Example:
![изображение](https://user-images.githubusercontent.com/7189309/56057357-4d375f80-5d67-11e9-827e-965fb9ca3edb.png)

Binary: [lv_bin.zip](https://github.com/NationalSecurityAgency/ghidra/files/3074632/lv_bin.zip)

**Comment by mumbel** [comment]
Did u turn on some dead code options or something?  That is the pcode for: `sp-=4; sp=pc`

**Comment by lab313ru** [comment]
Options are:
![изображение](https://user-images.githubusercontent.com/7189309/56062674-de153780-5d75-11e9-8765-8102bb8a0303.png)

**Comment by lab313ru** [comment]
I discovered it only happens on bsr.w opcodes.

**Comment by emteere** [comment]
These lines are there because the SP is set to a value earlier in the control flow.  The value will then be propagated as a constant.

Consider making a function at 0xf8c.

**Comment by lab313ru** [comment]
> These lines are there because the SP is set to a constant value earlier in the control flow. 

Is it possible to show that in pseudocode, instead of lines with assigning values to some strange places?

**Comment by lab313ru** [comment]
And yes: making function has helped.
