### ISSUE TITLE
Refresh Debugger UI after out-of-band change to target?

### ISSUE THREAD

**Issue by mfthomps** [NationalSecurityAgency/ghidra#4174]
Is there a function I can invoke from a GhidraScript to force the Debugger UI to refresh registers and memory from gdb?  I use the gdb "monitor" command from a GhidraScript to change the state of the target (in this case, a Simics simulation).  I would then like the GhidraScript to cause the UI to reflect the new state of the target.  I'm using a gdb client modified to update its state after the monitor command.  So gdb has the desired state, but the Ghidra Debugger UI needs to be refreshed.

**Comment by d-millar** [comment]
@mfthomps If you right click on the active node in the Targets window, you should see an option to flush the cache.  If you then Refresh the root node of the Objects tree, most of the debugger state should get updated.  (FYI, we’re working on making the a little simpler and a bit more obvious.)

**Comment by mfthomps** [comment]
Thanks.  I'm trying to do this from a GhidraScript, and am able to flush the cache from the script. But I'm not seeing how to refresh the root object from a script.

**Comment by mfthomps** [comment]
I was able to do this by adding a "getProvider" method to the DebuggerObjectsProvider.  I'm hoping there is a better way that doe not require changes to the core.  With that change, the following will refresh the UI:
```
                DebuggerObjectModel object_model = getObjectModel();
                object_model.invalidateAllLocalCaches();
                DebuggerObjectsProvider dbo = getDebuggerObjectsProvider();
                dbo.refresh();

        }
        private DebuggerObjectModel getObjectModel() throws Exception {
            DebuggerObjectsPlugin objects =
                (DebuggerObjectsPlugin) state.getTool().getService(ObjectUpdateService.class);
            DebuggerModelService models = objects.modelService;
            DebuggerObjectModel model = models.getModels()
                .stream()
                .filter(DebuggerObjectModel.class::isInstance)
                .map(DebuggerObjectModel.class::cast)
                .findFirst()
                .orElse(null);
            if (model == null) {
                return null;
            }
            return model;
        }
        private DebuggerObjectsProvider getDebuggerObjectsProvider() throws Exception {
            DebuggerObjectsPlugin objects =
                (DebuggerObjectsPlugin) state.getTool().getService(ObjectUpdateService.class);
            return objects.getProvider(0);
        }

```

**Comment by d-millar** [comment]
@mfthomps  As I think you've already realized, I clearly did not think through accessing these objects from a script.  I think your approach is actually the logical one and have no objection to adding that method.  Will add a ticket for getProvider and also I think a cleaner way to get the current model.

**Comment by mfthomps** [comment]
@d-millar Great!  I really appreciate the responses, and the product.

**Comment by mfthomps** [comment]
@d-millar The above strategy works to update the traces and stack info, but it does not update the Registers plugin values.  To do that, I add this method to GdbModelImpl.java:
```
+       public GdbModelTargetSession getSession() {
+           return this.session;
+       }
```
I then use the following (where impl is the GdbManagerImpl and model is the GdbModelImpl):
```
        protected void ghidraRegs(){

            impl.getKnownInferiors();
            Map <Integer, GdbInferior> knowInferiors = impl.getKnownInferiors();
            Msg.debug(this,  "ghidraRegs found inferiors count "+knowInferiors.size());
            GdbInferior inf = (GdbInferior) knowInferiors.values().toArray()[0];           
            if(inf == null) {
                Msg.error(this,  "inferior is null");
                return;
            }

            Map <Integer, GdbThread> threadmap = impl.getKnownThreads();
            Msg.debug(this, "ghidraRegs known thread count "+threadmap.size());
            GdbThread gdbthread = (GdbThread) threadmap.values().toArray()[0];

            GdbModelTargetSession s = model.getSession();
            GdbModelTargetInferiorContainer ic = s.getInferiors();
            GdbModelTargetInferior gif = ic.getTargetInferior(inf);
            GdbModelTargetThreadContainer tor = gif.getThreads();
            GdbModelTargetThread gdbModelThread = tor.getTargetThread(gdbthread);
            GdbModelTargetStack gdbStack = gdbModelThread.getStack();         
            CompletableFuture<? extends Collection<? extends TargetStackFrame>> cf = gdbStack.getFrames();
            Collection c = null;
            try {
                c = cf.get();
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
            Msg.debug(this,  "target stack frames, got count "+c.size());
            GdbModelTargetStackFrame tsf = (GdbModelTargetStackFrame) c.toArray()[0];
            GdbModelTargetStackFrameRegisterContainer regs = tsf.getRegisters();
            regs.requestElements(true);
        }
```
If there is an easier or cleaner way to achieve this, I'd appreciate hearing about it.  If not, can the change to GdbModelImpl.java be made?  
Thanks.

**Comment by d-millar** [comment]
@mfthomps I feel like there is a cleaner way to do this, but unfortunately am traveling at the moment and having a bit of trouble navigating the code from my phone.  Have asked @nsadeveloper789 to take a peek - am thinking it may be easier to trigger the changes you need from the bottom up vice top down.

**Comment by nsadeveloper789** [comment]
I've not tested this beyond "it compiles," but still, this should provide some good pointers around our service APIs. Biggest points: 1) You don't need to poke around the Objects provider to get the ModelService, or to force refreshes. 2) You don't need to cast to GDB to get at stuff. Use the schema to navigate the model generically.

```java
public class RefreshRegistersScript extends GhidraScript {
	@Override
	protected void run() throws Exception {
		// There is no need to fish this from the ObjectUpdateService, you can get it directly
		DebuggerModelService modelService = state.getTool().getService(DebuggerModelService.class);
		// The current model is retrieved with one method, no need to stream or filter
		DebuggerObjectModel model = modelService.getCurrentModel();

		/**
		 * Navigating a model generically requires some introspection. Use the schema. We used to
		 * decouple the descriptions (RegisterContainer) from the values (RegisterBank), but we
		 * always realize the two interfaces on the same no it seems. Still, we need to work with
		 * values, so we search for all the Banks.
		 */
		PathMatcher allBanksMatcher =
			model.getRootSchema().searchFor(TargetRegisterBank.class, true);
		for (TargetObject objBank : allBanksMatcher.fetchSuccessors(model.fetchModelRoot().get())
				.get()
				.values()) {
			// Because of a bug in our path search, this type check is still necessary :(
			if (!(objBank instanceof TargetRegisterBank)) {
				continue;
			}
			TargetRegisterBank bank = (TargetRegisterBank) objBank;
			// This is equivalent to hitting the "Flush Caches" button in the Target Provider
			bank.invalidateCaches().get();
			// If you know the names of the registers to read
			bank.readRegistersNamed("rax", "rbx").get();
			// Values are coupled to elements, so we can also just refresh them to re-read all
			bank.fetchElements(true).get();
		}

		/**
		 * Alternatively, to refresh just the bank for the current thread or frame, we need to
		 * determine the active frame. We'll do that by asking the TraceManagerService. Then,
		 * because that's in "trace land," we'll use the TraceRecorder to map that into "target
		 * land." Generally, you'd then need to navigate the schema as before, but relative to the
		 * target object. Because fetching registers is so common, this is already built in to the
		 * recorder.
		 */
		DebuggerTraceManagerService traceManager =
			state.getTool().getService(DebuggerTraceManagerService.class);
		// There are also getCurreentTrace(), etc., if you want just the one thing
		DebuggerCoordinates current = traceManager.getCurrent();

		// Now, we need to get the relevant recorder
		TraceRecorder recorder = modelService.getRecorder(current.getTrace());
		// There's a chance of an NPE here if there is no "current frame"
		TargetRegisterBank bank =
			recorder.getTargetRegisterBank(current.getThread(), current.getFrame());
		// Now do the same to the bank as before
		bank.invalidateCaches().get();
		bank.fetchElements(true).get();
	}
}
```

**Comment by nsadeveloper789** [comment]
I should note: As a general rule, for scripting calling `CompletableFuture#get()` is fine. If you start developing a plug-in, then you should take care never to call .get() on the Swing thread.

**Comment by mfthomps** [comment]
That is extremely helpful, thank you!  My development is now all plugins rather than scripts, and I appreciate the warning on CompletableFuture#get().

**Comment by mfthomps** [comment]
For future reference, to refresh the traces and stack info in the debugger UI use:
```
                    dbo = (DebuggerObjectsProvider) tool.getComponentProvider("Objects");
                    dbo.refresh("Threads");
```

**Comment by mfthomps** [comment]
Thanks.  Can I invoke those functions from a GhidraScript?

**Comment by nsadeveloper789** [comment]
I'll provide 2 alternatives:

1. If you're in the development branch, there's a relatively new `FlatDebuggerAPI` interface. It's easy to use from Java, but I haven't really tried from Jython:

```java
// Mix in the interface using "implements"
public class MyScript extends GhidraScript implements FlatDebuggerAPI {
    protected void run() {
        // This assumes GDB
        TargetObject threads = (TargetObject) getModelValue("Inferiors[1].Threads");
        refreshSubtree(threads);
    }
}
```
2. And probably the easiest from what you've already found: You can get the current tool from a script using `state.tool`.

**Comment by mfthomps** [comment]
Thanks.  My post that you just responded to seems to have come from a github time warp.  It may have been a draft from many months ago.  Anyway, thanks for help.

**Comment by mfthomps** [comment]
Hello again.  I'm back to this same question for Ghidra11, which no longer has getDebuggerObjectsProvider.  I have tried:
```
                    dbo = (DebuggerObjectsProvider) tool.getComponentProvider("Objects");
                    dbo.refresh("Threads");
```
But that does not do the refresh.  I notice that in the Objects window of the debugger, selecting "Threads" and doing "refresh" does not work either.  I must select "Stack" of the thread.  Any suggestions on how to do this with in my plugin?

**Comment by tactipus** [comment]
helloLe 5 mars 2024 à 17:38, Mike Thompson ***@***.***> a écrit :﻿
Hello again.  I'm back to this same question for Ghidra11, which no longer has getDebuggerObjectsProvider.  I have tried:
                    dbo = (DebuggerObjectsProvider) tool.getComponentProvider("Objects");
                    dbo.refresh("Threads");

But that does not do the refresh.  I notice that in the Objects window of the debugger, selecting "Threads" and doing "refresh" does not work either.  I must select "Stack" of the thread.  Any suggestions on how to do this with in my plugin?
