### ISSUE TITLE
macOS: exports from the shared dyld cache are too large

### ISSUE THREAD

**Issue by Kentzo** [NationalSecurityAgency/ghidra#4175]
**Describe the bug**
Binaries exported from the shared dyld cache have size larger than 500MB which cannot be true. E.g. exporting System/Library/PrivateFrameworks/TimeMachine.framework from /System/Library/dyld/dyld_shared_cache_x86_64 results in a binary that has size of 524994480 bytes. Same binary exported with https://github.com/keith/dyld-shared-cache-extractor has size of 872448 bytes.

**To Reproduce**
1. File -> Open File System…
2. Navigate to /System/Library/dyld and select dyld_shared_cache_x86_64
3. Navigate to System/Library/PrivateFrameworks/TimeMachine.framework
4. Right click and select Export all… 

**Environment (please complete the following information):**
 - macOS 11.6.5
 - Ghidra Version: 10.1.2

**Additional context**
- https://github.com/NationalSecurityAgency/ghidra/issues/4162
- https://github.com/NationalSecurityAgency/ghidra/issues/3345

**Comment by ryanmkurtz** [comment]
Typically the file is that big because they all share the same large `___LINKEDIT` segment, which we fully export for each dylib.  If you look at the resulting dylib's `segment_command` for `__LINKEDIT`, does it have a big `filesize`?  Does your smaller version that you exported with the other tool analyze without error in Ghidra?

**Comment by Kentzo** [comment]
> If you look at the resulting dylib's segment_command for __LINKEDIT, does it have a big filesize?

```
$ size ghidra_extracted/TimeMachine
__TEXT	__DATA	__OBJC	others	dec	hex
size: object: ghidra/TimeMachine truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 32 extends past the end of the file) 

$ size dyld_extractor/TimeMachine
__TEXT	__DATA	__OBJC	others	dec	hex
503808	67888	0	303016	874712	d58d8
```

> Does your smaller version that you exported with the other tool analyze without error in Ghidra?

I used it to fully extract the cache and then pointed Ghidra to the resulting directory for loading external libraries. Ghidra loaded all the references, External Programs also appears correct.

**Comment by ryanmkurtz** [comment]
Thanks, that's very helpful.  I didn't know about `size`.  I'll try to improve it.

**Comment by ryanmkurtz** [comment]
Yea, the size discrepancy is definitely from how we are handing the `__LINKEDIT` segment.  I am going to try packing ours down so it only includes the relevant `linkedit_data_command`s and see where that gets us.

**Comment by ryanmkurtz** [comment]
Note that the commit referenced above doesn't address the large exports, but it fixed some issues that caused the `size` command to fail.

**Comment by ryanmkurtz** [comment]
Looks like @arandomdev has had some success in [optimizing the `__LINKEDIT` segment](https://github.com/arandomdev/DyldExtractor/blob/master/src/DyldExtractor/converter/linkedit_optimizer.py).

**Comment by arandomdev** [comment]
My optimizer is essentially the reverse of apple's optimizer. Lucky most load commands like `data in code` and `function starts` are still separated, so you can just copy the data into the new linkedit and adjust the offsets.

As for the symbols and strings, with careful tracking, you can rely on the indices in the dysymtab command. Local symbols are in their own unmapped region, but it's possible to find the relevant ranges ([reference](https://github.com/arandomdev/DyldExtractorC/blob/2f56b6343c873706c7327a70d9423a0a8b5b0760/DyldExtractor/Converter/LinkeditOptimizer.cpp#L390)). The only problem is with indirect symbol entries, as some of them point to `0`, which is the redacted entry. I was able to symbolize them later when I was processing stubs and had access to more info.

It also appears that the same optimizations are done across platforms (accounting for pointer size).
[LinkeditOptimizer.h](https://github.com/arandomdev/DyldExtractorC/blob/main/DyldExtractor/Converter/LinkeditOptimizer.h)
[LinkeditOptimizer.cpp](https://github.com/arandomdev/DyldExtractorC/blob/main/DyldExtractor/Converter/LinkeditOptimizer.cpp)
