### ISSUE TITLE
Force Union Field can't change a field back and forth

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#4178]
**Describe the bug**
When I change a union field to a different member, I can't change it back.

**To Reproduce**
1. Download binary null.sys from https://msdl.microsoft.com/download/symbols/null.sys/01FE6381a000/null.sys, and null.pdb from https://msdl.microsoft.com/download/symbols/null.pdb/DFC419D36E2BB141A3B5F9A3EEA4BD341/null.pdb
2. Download Windows WDK gdt file: [windows_ntddk_x64_wdk_10_22000.zip](https://github.com/NationalSecurityAgency/ghidra/files/8540698/windows_ntddk_x64_wdk_10_22000.zip) Unzip it to get file `windows_ntddk_x64_wdk_10_22000.gdt`. 
3. Import null.sys to Ghidra.
4. Data Type Manager -> Open File Archive ...: Open windows_ntddk_x64_wdk_10_22000.gdt
5. In Data Type Manager, right click windows_ntddk_x64_wdk_10_22000. Click "Apply Function Data Types".
6. File -> Load PDB File: load the downloaded null.pdb
7. Analysis -> Auto Analyze null.sys: use the default analyzers.
8. The decompile of function `NlsRead` looks like this:
```
undefined8
NlsRead(undefined param_1,undefined param_2,undefined param_3,undefined param_4,undefined param_5,
       undefined param_6,undefined4 *param_7)
{
  *(undefined8 *)(param_7 + 2) = 0;
  *param_7 = 0xc0000011;
  return CONCAT71((int7)((ulonglong)param_7 >> 8),1);
}
```
9. Retype `param_7` to `PIO_STATUS_BLOCK`. Then the second line of the function body becomes: `(param_7->field0_0x0).Status = -0x3fffffef;` Right click `Status` -> Force Field: Change it from `Status` to `Pointer`
10. This line becomes: `*(undefined4 *)&(param_7->field0_0x0).Pointer = 0xc0000011;`
11. Right click `Pointer` -> Force Field: change it back to `Status`. Click OK. Nothing happens. The field remains as `Pointer`.

**Expected behavior**
I should be able to change the field between `Status` and `Pointer` back and forth.

**Screenshots**
![NlsRead](https://user-images.githubusercontent.com/16713498/164738679-a923b368-2e8a-4ce8-912b-ed8cd158ca17.png)

**Attachments**
* null.sys: SHA256: 876185b0fc0e802ff7954d84d6255fd61eeff217ace56e61510e1fa1f56cdef1
* null.pdb: SHA256: d3e5facdaf7c8c33af5f7b11f8b35cf057ae27d6f038f0a670ac4c369ad23aee

Download links are in the previous section.

**Environment (please complete the following information):**
 - OS: Kali Linux x64
 - Java Version: 17.0.2
 - Ghidra Version: 10.2 master, 47f76c7
 - Ghidra Origin: locally built

**Comment by dzik87** [comment]
This seems to be working properly on latest master build.
At least i haven't got any probems changing it that way.
