### ISSUE TITLE
"Unsupported mask/shift setting for segmented address" error

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4179]
**Describe the bug**
My Windows NE 16-bit application has strings in its data segments.  The addresses of these strings (including segment:offset - making 32-bit little endian pointers) make up arrays.  Upon trying to change some data types from `pointer32` (or anything) to something meaningful like `LPCSTR`, or clearing the current type and changing it to even `char *` results in the `Operand` column of the `Listing` view now showing this error `Unsupported mask/shift setting for segmented address`.  See before an after screenshots below.

**Expected behavior**
To recognise these addresses and display their contents as before.  Also, there are consequences in the generated decompilation that don't recognise things correctly.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/67698927/164777575-a4fcb161-d507-48e0-b78c-176ac2e52c4a.png)

After a simple `clear` and type setting:
![image](https://user-images.githubusercontent.com/67698927/164777751-71c7615a-3cc9-4126-a036-4b936a893485.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.2 & 16.0.1
 - Ghidra Version: 10.1.3
 - Ghidra Origin: locally built

**Additional context**
Could we have some more detailed information about the recent changes to segmentation support and those made to the C++ decompiler code?  Thanks in advance.

**Comment by ghidra1** [comment]
It appears an invalid error check was introduced with the pointer-typedef settings.  A fix will be pushed-out in the next day or two.
