### ISSUE TITLE
(Minor) Language ID / Project Set Language Updates Out of Sync

### ISSUE THREAD

**Issue by jmcarter9t** [NationalSecurityAgency/ghidra#4182]
When you set the language for a binary in the Ghidra Project Management GUI and save that selection is does not reflect that change when you choose about program in the right-click menu.  The select does effect the analysis, however (this is what is desired).  This issue is only relevant if you set the language spec AND THEN CHANGE it.
 
1. Select Binary
2. Rt Click, Set Language, Click Ok, Select Language Spec
3. Click SAVE
4. Select Same Binary
5. Rt Click, About Program
6. Language ID is NOT what you selected.
7. Analyze program.
8. In Code Browser, Select Help, About <file>
9. Language ID is CORRECT (based on previous selection)

Step 6 above is the item I think is an update problem.  It seems if you save the chosen language spec you should be able to see that change reflected in the project management dialog.  IOW: The About Program information should CONFIRM what you have chosen there for your analysis.  The BEHAVIOR seems to be correct when you finally do the analysis.

I observed this when working with a PPC binary.

 - OS: Linux 20.04
 - Java Version: open jdk 17
 - Ghidra Version: 10.1.3
 - Ghidra Origin: official ghidra site

**Comment by ghidra1** [comment]
If you make a subsequent change to the Program and save it the metadata should update correctly, although it still sounds like a issue.
