### ISSUE TITLE
M68000: SBCD instructions are decompiled incorrectly

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#4183]
**Describe the bug**

SBCD instructions are decompiled with swapped operands.

**To Reproduce**

1. Load the attached sbcd.bin file as a default M68000 binary; starting address does not matter 
2. Mark the whole binary as code (creating a function out of this does not affect the decompilation result)
3. The decompiled output will show the incorrect `bcdAdjust` call

**Expected behavior**

The operation is D1b - 1 - XF, but decompilation shows 1 - D1b - XF instead.  Documentation says that SBCD is "Destination10 – Source10 – X → Destination"

**Screenshots**

<img width="1245" alt="Screenshot 2022-04-23 at 17 07 24" src="https://user-images.githubusercontent.com/235740/164911853-fdc14035-e461-4c2a-a407-4dee890538a2.png">

**Attachments**

[sbcd.bin.zip](https://github.com/NationalSecurityAgency/ghidra/files/8547464/sbcd.bin.zip)

**Environment (please complete the following information):**
 - OS: macOS 12.3.1
 - Java Version: 18.0.1
 - Ghidra Version: 10.1.3
 - Ghidra Origin: GitHub binary release

**Comment by mumbel** [comment]
From manual:
`SBCD Dx,Dy`
`Dx, Dy`: `source and destination data registers, respectively`

From sleigh:
`:sbcd Tyb,Txb`
but the display is correct, so are the variables are named backwards?

Then it looks like they were used in the calculation as `:sbcd DST,SRC` instead of SRC,DST

**Comment by agatti** [comment]
@mumbel so for reference:

```asm

MOVEQ.L #$1, D0
MOVE.L #$20, D1
SBCD D0, D1
```

should produce #$19 in D1.  In this case, the calculation is the other way around then.
