### ISSUE TITLE
'Bad storage node' error when using 'Split Out As New Variable'

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4186]
While trying to use the `Split Out As New Variable` facility I came across this error:
`Pcode: XML comms: Bad storage node`

Upon further investigation, I've found that the _address space_ of type `TYPE_VARIABLE` is delibrately not added to the `spaceLookup` map during the process of creating the `ProgramAddressFactory` object.  This is causing method `checkVarnodes()` of class `VariableStorage` to throw the `InvalidInputException` which results in the error above being thrown from method `splitOutMergeGroup` in `HighFunction`!

I have 3 questions:
1) Should `VariableStorage.checkVarnodes()` be performing that check or can it be legitimately removed/ignored?
2) Should the process of creating the `ProgramAddressFactory` object actually add that factory to its lookup?
3) Does anyone have a more correct solution?

**Comment by phmarek** [comment]
Still happens in 10.1.5.

```
Pcode: XML comms: Bad storage node
---------------------------------------------------
Build Date: 2022-Aug-14 1349 UTC
Ghidra Version: 10.1.5
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Version: Debian 17.0.4
OS: Linux 5.17.0-1-amd64 amd64
```

The 10.2 milestone has no open issues, is there a (planned) release date?
Thanks!

**Comment by ryanmkurtz** [comment]
As you've noted, this has been fixed in a version of Ghidra that has not yet been released.  We don't have an exact release date for 10.2, but we are getting close.  If you would like this fixed immediately, you have the option of building the `master` branch, which contains all the things going into the upcoming 10.2 release.
