### ISSUE TITLE
68000: CMPI.B negative immediates turn to words when converted into unsigned values

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#4191]
**Describe the bug**
CMPI.B opcodes with immediate negative values are incorrectly sign-extended when converted to unsigned bytes.

**To Reproduce**

1. Load the attached cmpi.bin file as a default 68000 binary starting at 0x1000.
2. Disassemble the file starting from 0x1000.
3. Convert the immediate value -0x67 into an unsigned character.
4. The immediate value will be extended to 16 bits, with the MSB of the word being 0xFF.

**Expected behavior**
Conversion of a signed byte quantity into its unsigned counterpart should still result in a byte quantity.  In the sample binary, -0x67 should turn into 0x99.

**Screenshots**
Before conversion:
<img width="664" alt="before" src="https://user-images.githubusercontent.com/235740/165091790-2f0adde8-e39b-47c1-bc78-7224d113226d.png">

After conversion:
<img width="662" alt="after" src="https://user-images.githubusercontent.com/235740/165091802-1de36285-2ba8-499b-a5b2-eb93c3c1b65c.png">

**Attachments**
[cmpi.bin.zip](https://github.com/NationalSecurityAgency/ghidra/files/8554646/cmpi.bin.zip)

**Environment (please complete the following information):**
 - OS: macOS 12.3.1
 - Java Version: 18.0.1
 - Ghidra Version: 10.1.3
 - Ghidra Origin: GitHub binary release

**Comment by Brainulator9** [comment]
The same thing happens with the ori.b, addi.b, and subi.b instructions, but not andi.b or move.b.
