### ISSUE TITLE
Adjust Pointer Offset / Create Relative Pointer: What does it do?

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4200]
Commit ec5b6aada introduced a "relative pointer action" to the decompiler. 

Can I clarify whether supplying arguments ``DataType = MyType, offset=0x10, name="MyTypeDef"``, results in a typedef that represents a pointer to offset 0x10 in the ``MyType`` structure?

Also, is there an equivalent global action to create a similar offset typedef?

**Comment by astrelsky** [comment]
Also is it possible to create a pointer relative to an address instead of a datatype? This would enable virtual inheritance modeling.

**Comment by dev747368** [comment]
In DTM, the painful / manual way is to create a pointer to a type (right click on type, New | Pointer to typename), find the new pointer type, right click on it, and create a typedef to that, find the new typedef and right click on it and choose "Settings", and tweak.

**Comment by sad-dev** [comment]
> In DTM, the painful / manual way is to create a pointer to a type (right click on type, New | Pointer to typename), find the new pointer type, right click on it, and create a typedef to that, find the new typedef and right click on it and choose "Settings", and tweak.

Wow, that's a whole host of options in that dialog. Is there an example/tutorial of how we can use this to improve the quality of decompilation?

**Comment by ghidra1** [comment]
> Also is it possible to create a pointer relative to an address instead of a datatype? This would enable virtual inheritance modeling.

It does support this use.  You can simply use a default pointer typedef with the offset setting when defining the relevant pointer component.  See convenience factory class `PointerTypedef` for construction via API.  Via GUI, it is create a typedef from a default pointer (without a name) and set offset setting on the typedef.

This technique is currently being used by the `RecoverClassesFromRTTIScript`.

**Comment by ghidra1** [comment]
> > In DTM, the painful / manual way is to create a pointer to a type (right click on type, New | Pointer to typename), find the new pointer type, right click on it, and create a typedef to that, find the new typedef and right click on it and choose "Settings", and tweak.
> 
> Wow, that's a whole host of options in that dialog. Are there plans for a tutorial of how we can use this to improve the quality of decompilation e.g. to deal with the shifted pointers / negative offsets mentioned in #2189 and #573 ? It sounds like it would be a good addition to the GhidraDocs/GhidraClass

Within the master branch (i.e., 10.2) Most of the pointer-typedef settings are not currently supported by the decompiler (work-in-progress).  Partial support for the `Component Offset` setting does exist.

**Comment by astrelsky** [comment]
> > Also is it possible to create a pointer relative to an address instead of a datatype? This would enable virtual inheritance modeling.
> 
> It does support this use.  You can simply use a default pointer typedef with the offset setting when defining the relevant pointer component.  See convenience factory class `PointerTypedef` for construction via API.  Via GUI, it is create a typedef from a default pointer (without a name) and set offset setting on the typedef.
> 
> This technique is currently being used by the `RecoverClassesFromRTTIScript`.

I don't think I actually asked what I meant. I want to be able to have a pointer that would be assumed to have a  constant value, `void const *` for example, so that when the `_vptr` is dereferenced with a negative offset the decompiler will request the data at the calculated address, see it is defined as a constant `ptrdiff_t` and use that value and eliminate the pointer dereferencing. Then with the further application of decompiler simplification rules the loaded value which gets added to the `this` pointer would then translate into a member access of the correct virtual base.

**Comment by ghidra1** [comment]
I assume this would require a new `const` pointer-typedef setting.  The original post related to the "relative" pointer action within the decompiler which makes use of the `Component Offset` setting for a pointer-typedef.

**Comment by astrelsky** [comment]
> I assume this would require a new `const` pointer-typedef setting.  The original post related to the "relative" pointer action within the decompiler which makes use of the `Component Offset` setting for a pointer-typedef.   

Maybe. There would still need to be a way to set the value for the pointer though unless the offset would have a different meaning when const. Will let things settle and see what direction things go in first before requesting any additional settings or something.

**Comment by s5bug** [comment]
I don't see how I'm supposed to use this at all. I have an artifact of LTO where a pointer is passed in at an offset of 16;
```
struct Foo {
  Bar base_Bar; // size 16
  Qux base_Qux; // size 16
  int field1;
  int field2;
}
```
A method takes in a `offset(Foo*, 16)`, such that the pointer points to `base_Qux`.

![image](https://user-images.githubusercontent.com/7751296/175749707-fd667e6d-b8f7-47e3-befa-25afe978ff31.png)

I don't see any fancy dialog like the one in the commit would imply. 

Trying to edit a Typedef to a Pointer to a Struct just brings up the Struct editor.

**Comment by astrelsky** [comment]
> I don't see how I'm supposed to use this at all. I have an artifact of LTO where a pointer is passed in at an offset of 16;
> ```
> struct Foo {
>   Bar base_Bar; // size 16
>   Qux base_Qux; // size 16
>   int field1;
>   int field2;
> }
> ```
> A method takes in a `offset(Foo*, 16)`, such that the pointer points to `base_Qux`.
> 
> ![image](https://user-images.githubusercontent.com/7751296/175749707-fd667e6d-b8f7-47e3-befa-25afe978ff31.png)
> 
> I don't see any fancy dialog like the one in the commit would imply. 
> 
> Trying to edit a Typedef to a Pointer to a Struct just brings up the Struct editor.

You want to right click on the typedef and choose settings.

**Comment by s5bug** [comment]
![image](https://user-images.githubusercontent.com/7751296/175760285-f90c8e86-ee97-43fd-901c-97673fc228dc.png)

Where's Settings? Edit just brings up the menu to edit the `R_Player` struct. Perhaps this isn't shipped 10.1.4?

**Comment by ryanmkurtz** [comment]
> Perhaps this isn't shipped 10.1.4?

Correct, this is in master/10.2-DEV

**Comment by Fighter19** [comment]
With 11.3.2 (so from April),
it does not appear to work for me.

I'm analyzing a sample, that is supposedly malware,
according to most AVs,
but I think that's mostly, because it's handwritten ASM.

The function in question accepts a list of parameters via EBP.

But the offsets are negative.

So I expected to be able to use the "Adjust Pointer Offset" feature.
I pass in the structure of 4 bytes, which represent the offsets ebp-4 to ebp-1.

But even when specifying this offset or changing it, e.g. via the Data Type Manager, the changes are not reflected...

EDIT: By applying a positive offset instead it works....
What? So even though it's EBP-4 and the struct is defined to be at EBP-4, the value that has to be entered is 4 and everything looks correct.

**Comment by ghidra1** [comment]
The Pointer Offset setting mechanism is intended to work in very specific situations (i.e., pointers that refer into a specific offset of another structure datatype).  While applying a typedef with such a setting is fairly straight forward, the benefit is highly dependent on what and where you expected to see a benefit.  Although there may be other valid use case, this Pointer Offset mechanism was specifically added to support the pointer relationships between C++ Compiler generated structures (see the following link for some background on this topic: [Uncovering_Class_Hierarchies](https://www.researchgate.net/publication/311886461_MARX_Uncovering_Class_Hierarchies_in_C_Programs).

The Pointer Typedef is defined as a pointer to a specific Structure Datatype and the Pointer Offset setting reflecting where within that structure the pointer would refer to.

This Pointer Offset mechanism is not intended to be used for stack frame interpretation (e.g., EBP frame pointer).  The stack analyzer will apply stack references and create variables/parameters based upon uses of the stack pointer, including derived stack frame pointers, which may get initialized from the stack pointer value within a function.
