### ISSUE TITLE
C Parser doesn't recognize _Noreturn keyword

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#4202]
`_Noreturn` is a C11 keyword to mark a function as no-return. Ghidra doesn't recognize this specifier.

**To Reproduce**
Parsing the following C code fails in Ghidra:
```
_Noreturn void func(int a);
```

**Environment (please complete the following information):**
 - OS: Kali Linux
 - Java Version: 17.0.2
 - Ghidra Version: 10.2 (master, d0a8291e93741aec29fb3727985be12984baab9b)
 - Ghidra Origin: locally built

**Error Log**
```
INFO  (CParserTask$3) Parse Errors: C Parser:  Encountered errors during parse.
         in /.../test.h near line 1
Error: Encountered " <IDENTIFIER> "_Noreturn "" at line 3, column 1.
Was expecting one of:
    <INTEGER_LITERAL> ...
    <PRAGMA> ...
    "#line" ...
    <LINEALT> ...
    ";" ...

         near token: "/.../test.h"
Possibly Undefined : _Noreturn
         Last Valid Datatype: - none -
         Check around CParserPlugin.out around line: 3
```

**Comment by emteere** [comment]
Fixed in #4273
