### ISSUE TITLE
NPE in TableChooserDialog: Null address passed to ProgramLocation

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4204]
**Describe the bug**
Clicking the "Make a program selection from the selected rows" button with an empty selection results in an NPE and the error message:
"Null address passed to ProgramLocation. Trace and remove this problem".

**To Reproduce**
1. Run a script that creates a TableChooserDialog e.g. ShowConstantUse.java
2. Click the button with an empty selection as described above

**Environment (please complete the following information):**
ghidra 10.2 master (d0a8291)

**Comment by dragonmacher** [comment]
Do you have the stack trace?   There is likely one specific place that null is being passed.  The stack trace should allow us to see that.

**Comment by dragonmacher** [comment]
Thanks for the update.    This should be an easy fix.
