### ISSUE TITLE
What's the process to update Ghidra to a new version?

### ISSUE THREAD

**Issue by ddbb2017** [NationalSecurityAgency/ghidra#421]
Sorry, I don't seem to find the answer to this.

Say, if I had v.9.0 installed already, I assumed that for an upgrade to v.9.0.2 I would unzip its files into its own folder and run it from there. But then if I do that all my projects that I've been working in v.9.0 are gone.

So what's the process to upgrade to a new version while preserving your projects and other settings?

**Comment by marcomafcorp** [comment]
I agree with the above question, the pic is the way I have my instances of Ghidra setup and it's not ideal. There has to be a better way.

<img width="419" alt="Screen Shot 2019-04-15 at 1 33 31 PM" src="https://user-images.githubusercontent.com/4383090/56152964-1e95d080-5f83-11e9-85b7-5dca3c0621eb.png">

**Comment by ddbb2017** [comment]
@marcomafcorp yeah but how do you transfer all the projects and other settings?

I haven't tried it yet but maybe they want us to overwrite the files in existing folder with the ones from the new version.

**Comment by marcomafcorp** [comment]
You're right ddbb2017, I only transfer my scripts and then start with a fresh Ghidra instance... They have to come up with a way asap. Because this sucks the way I'm currently doing it. It's not scalable.

**Comment by ryanmkurtz** [comment]
@ddbb2017, you simply open your existing project in your new version of Ghidra (File --> Open Project...).

**Comment by Ristovski** [comment]
So far I have been renaming my `~/.ghidra/.ghidra-9.0*` folder to whatever the latest version I end up using is. This essentially 'migrates' all the configuration.

I reckon it's fine for now, but I can see how this could one day break when there are breaking changes in the configuration files.

**Comment by ryanmkurtz** [comment]
When you start up the new version of Ghidra, it should automatically pull your configuration from your newest ~/.ghidra/ directory and use that.  You then just reopen whatever project you were working on.  You can look at the first few lines of Ghidra's log to confirm it's doing that.
