### ISSUE TITLE
Offsetted pointers don't seem to apply to left-hand side of assignment sometimes

### ISSUE THREAD

**Issue by IvanDSM** [NationalSecurityAgency/ghidra#4224]
**Describe the bug**
In a situation where an offsetted pointer is being attributed to, the decompiler does not seem to be able to use the ADJ mnemonic to properly identify the structure field sometimes.

The following screenshot shows a real world example of this bug.

![image](https://user-images.githubusercontent.com/7508166/166400683-346f1dd7-2487-49b8-9f22-f81ac8e1370e.png)

**To Reproduce**
It is unclear how to reproduce this bug. I tried writing a sample C program to attempt to provide as an example but the decompiler managed to provide the expected result.

**Expected behavior**
Given the following structure:

```c
struct AStruct
{
    int a;
    int b;
}
```

and an offsetted pointer type X which points to member B of AStruct, an assignment of the number 2 to member a of an instance of AStruct pointed to by a pointer of type X should look like `ADJ(ptrAStruct)->a = 2`. An example of a well-formed decompilation using AStruct is shown in the following screenshot.

![image](https://user-images.githubusercontent.com/7508166/166402148-bf9bce0b-b226-446a-949b-00c629de80bf.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 21.10
 - Java Version: 17.0.3
 - Ghidra Version: 10.2-DEV (0b66c98)
 - Ghidra Origin: Locally built

**Comment by IvanDSM** [comment]
As I mentioned in #4236, there is some strange behavior in that while the program listing seems to be aware of what is being accessed, the decompiler cannot process those same references. Note the screenshot below, where the offsetted member access is properly detected by the program listing but not by the decompiler:

![image](https://user-images.githubusercontent.com/7508166/167526099-5f6c573f-f6c2-4e56-b12a-073d31cab451.png)

This may be a MIPS specific issue, given that the executable I'm using to demonstrate this issue is also for a MIPS CPU.

**Comment by caheckman** [comment]
Can you post the output file from the "Debug Function Decompilation" menu action, for the function showing the problem?  The action is in the menu accessible from the title bar of the Decompiler window.

**Comment by IvanDSM** [comment]
Absolutely, I can provide those in a few hours. I have other similar functions from the same project that have the same issue, would you also like the output for those?

**Comment by IvanDSM** [comment]
Here's the decompilation debug results for both the KingsFieldLoadEntities function as well as the AStruct example (which decompiles succesfully). If you'd like any more debug outputs from the similar functions I mentioned just let me know :)

https://gist.github.com/IvanDSM/8985223fb5d020da3f52cab23fef521a

**Comment by caheckman** [comment]
Thank you.  I'm reproducing this now.

**Comment by IvanDSM** [comment]
Hey, thanks a lot for the incredibly fast work! Using a build based on commit 849c6d195 did fix the KFLoadEntities example, but unfortunately a different function in the same project is still incorrectly decompiled.

![image](https://user-images.githubusercontent.com/7508166/173410174-078e34eb-3f62-4155-8a31-e9a613596d90.png)

I have added the decompiler debug output to the existing gist as "4224_KingsField_FAIL2_example.xml". I apologize for not providing this example earlier, and will keep an eye out for other cases where this error happens and provide the debug outputs ASAP.

**Comment by IvanDSM** [comment]
@ryanmkurtz Could we maybe reopen this given the new test case?

**Comment by IvanDSM** [comment]
I've added more sample outputs to the gist. FAIL3 has a variable called unstablePtr that seems to get decompiled correctly in some cases but incorrectly in others:

![image](https://user-images.githubusercontent.com/7508166/174473179-117210e0-3b25-4222-b779-7a571f462bb5.png)

FAIL4 has multiple similar looking failures (only one is demonstrated on the following screenshot) for different structures:

![image](https://user-images.githubusercontent.com/7508166/174473566-d073e519-6592-4c5d-9df7-0150eb313cfb.png)

These were obtained from the same build as the original debug outputs, but if necessary I can check again with a new build based on the latest commit.

**Comment by IvanDSM** [comment]
Quick update: tested out a fresh build based on commit d2883bbb8 and FAIL4 now seems to decompile properly:

![image](https://user-images.githubusercontent.com/7508166/174690228-ea341a1f-54cf-488e-9fc5-ff0e5aebc0ff.png)

FAIL2 and FAIL3 still remain broken unfortunately.

**Comment by caheckman** [comment]
Thanks for the examples. I am reproducing.  The problem occurs when the structure doesn't have a defined field at the component offset of the pointer.

The "unstablePtr" example in FAIL3 will work fully if you redefine the pointer to be relative to KingsFieldMetaTile, instead of KingsFieldTile, and use an offset of 9.
