### ISSUE TITLE
Error importing file, invalid index

### ISSUE THREAD

**Issue by cryptax** [NationalSecurityAgency/ghidra#4225]
**Describe the bug**
I try to import `/tmp/tmpablnkglr` (sha256: `751744a03611b04aa449577a6ee1e525d8627b14945652d5e6a5b701bd4778db`), and get an import error saying 
```
Invalid index: 307280 
java.io.IOException: Invalid index: 307280
```

**To Reproduce**
1. Create a project
2. Click on File > Import File
3. Select the sample and click on Select to Import
4. Click on OK
5. See error

**Expected behavior**
Importing the file to be able to decompile it.

**Screenshots**
![ghidra-error](https://user-images.githubusercontent.com/2493690/166422399-4541abc7-3d1a-4044-a442-28685cc67919.png)

**Attachments**
[sample.zip](https://github.com/NationalSecurityAgency/ghidra/files/8609127/sample.zip)
The password for the zip file is `infected`. Please be aware that the sample is possibly malicious. Handle with care!

**Environment (please complete the following information):**
 - OS: Linux Mint 20.3
 - Java Version: openjdk 11.0.15 2022-04-19
 - Ghidra Version:10.1.3
 - Ghidra Origin: official ghidra-sre.org distro 

**Additional context**
The sample is processed by Radare2.

**Comment by ghidra1** [comment]
Current import with master produces results:  (please try master branch)

----- Loading /tmpablnkglr -----
17 of 17 section headers are truncated/missing from file
Skipping segment[0, null] with invalid file offset
Skipping PT_LOAD segment[2, Loadable segment] with invalid file offset
Skipping segment[3, Thread-Local Storage template] with invalid file offset
Truncating block load for segment_1 which exceeds file length
Truncating block load for _elfSectionHeaders which exceeds file length
Failed to markup Elf section headers: Address Overflow in subtract: OTHER:00000000 - 0x1b419

**Comment by ryanmkurtz** [comment]
Since this seems to be resolved in master, I am closing it.  Feel free to reopen it if your testing reveals otherwise.
