### ISSUE TITLE
Ghidra can't find JDK even though it is installed and in PATH

### ISSUE THREAD

**Issue by WodkaRHR** [NationalSecurityAgency/ghidra#4228]
**Describe the bug**
I am trying to use Ghidra 10.1.3 on Ubuntu 20.04. On launch, I am informed it can't find a JDK even though a JDK is present and properly present in the `PATH` and `JAVA_HOME` environment variables.
In particular, the JDK is the correct version (11) and the following commands verify it is in fact installed:
```shell
dominik@dominik-IdeaPad-5-Pro-16IHU6:/media/data/romhacking/ghidra$ echo $PATH
/usr/lib/jvm/java-11-openjdk-amd64/bin:/usr/lib/jvm/java-11-openjdk-amd64/bin:/home/dominik/.local/bin:/opt/devkitpro/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
dominik@dominik-IdeaPad-5-Pro-16IHU6:/media/data/romhacking/ghidra$ echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-amd64
dominik@dominik-IdeaPad-5-Pro-16IHU6:/media/data/romhacking/ghidra$ which javac
/usr/lib/jvm/java-11-openjdk-amd64/bin/javac
dominik@dominik-IdeaPad-5-Pro-16IHU6:/media/data/romhacking/ghidra$ javac -version
javac 11.0.15
```
In particular, Ghidra gives the following output:
```shell
dominik@dominik-IdeaPad-5-Pro-16IHU6:/media/data/romhacking/ghidra$ ./ghidraRun
Application properties file does not exist: /media/data/romhacking/ghidra/Ghidra/application.properties
Application properties file does not exist: /media/data/romhacking/ghidra/Ghidra/application.properties
Application properties file does not exist: /media/data/romhacking/ghidra/Ghidra/application.properties

Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section.
```

**To Reproduce**
Run the launcher `ghidraRun`

**Expected behavior**
Ghidra should find the JDK.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Java Version: 11.0.15
 - Ghidra Version: 10.1.03
 - Ghidra Origin: ghidra-sre.org

**Comment by ryanmkurtz** [comment]
The real problem is your first error. Please verify that the application.properties is present. Ghidra will not be able to find Java without it.
