### ISSUE TITLE
UTF8 string handling in CliStreamStrings

### ISSUE THREAD

**Issue by dvsaf** [NationalSecurityAgency/ghidra#423]
While using ghidra.app.util.bin.format.pe.cli.streams.CliStreamStrings class in my script I've found that its method getString returns only leading ascii part of a string and breaks a string on first non-ascii character. So any UTF8-encoded string appears to be truncated.

The getString method uses BinaryReader.readAsciiString method which stops reading a string on first non-ascii char. 

Such behaviour is wrong because #Strings stream in CLI files in general contains UTF8 strings.

**Comment by ryanmkurtz** [comment]
Thanks for reporting this.  Looks like we should add a readUtf8String method to BinaryReader as well.
