### ISSUE TITLE
os/mac_x86_64/decompile does not exist [Silicon Mac]

### ISSUE THREAD

**Issue by imranur-rahman** [NationalSecurityAgency/ghidra#4231]
I have built ghidra natively on Macbook Air M1 2020. So, in the output zip I have GPL/DemanglerGnu/os/mac_arm_64 in the compressed output file. But when I run the ghidra it causes the following error analyzing a binary. The output is same whether I build locally using `gradle buildGhidra` or `gradle buildNative`.

```
os/mac_x86_64/decompile does not exist
---------------------------------------------------
Build Date: 2022-May-03 1018 BDT
Ghidra Version: 10.2
Java Home: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
JVM Version: Eclipse Adoptium 11.0.13
OS: Mac OS X 12.3.1 x86_64
Workstation: 192.168.0.107
```

And when I want to decompile a function, it says the following error in the decompile window.
```
GPL/DemanglerGnu/os/mac_arm_6
```

When I try to run this command according to this link (https://github.com/NationalSecurityAgency/ghidra/issues/1495#issuecomment-580742305) to find the system architecture, the output is: 
```
Python Interpreter for Ghidra
Based on Jython version 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK 64-Bit Server VM (Eclipse Adoptium)]
Press 'F1' for usage instructions
>>> from java.lang import System
>>> System.getProperty("os.arch")
u'x86_64'
```

**Environment (please complete the following information):**
 - OS: Mac OS X 12.3.1 x86_64
 - Java Version: Eclipse Adoptium 11.0.13
 - Ghidra Version: 10.2
 - Ghidra Origin: locally built

**Comment by ryanmkurtz** [comment]
I think all of your issues would go away if you would run the aarch64 version of java instead of the x86 version.

**Comment by ryanmkurtz** [comment]
Glad to hear.  JDK 17 is not "officially" supported, but it's been known to work well.

**Comment by ryanmkurtz** [comment]
And just for future reference/completeness, [Amazon Corretto](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html) is another JDK distro that provides JDK 11 for macOS aarch64.
