### ISSUE TITLE
M1 debugger unable to build

### ISSUE THREAD

**Issue by crismi2** [NationalSecurityAgency/ghidra#4237]
I have problems to built the debugger library
I read the document InstructionsForBuildingLLDBInterface.txt  and also  #4035

this is my system
Mac mini M1 
Monterey 12.3.1
ghidra_10.1.3_PUBLIC

lldb-1316.0.9.41
Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)

java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

I have done the follow to build

I skip the first 2 step because I just have lldb v 13 installed (not the brew version)

git clone https://github.com/llvm/llvm-project.git
export JAVA_HOME=$(/usr/libexec/java_home)
export LLVM_HOME=/Users/cri/llvm-project
export LLVM_BUILD=/Users/cri/llvm-project
gradle build

The modules decompiler , sleigh , demangler_gnu_v2_33_1 is built correct in arm64

but I received the follow message from gradle

> Configure project :Debugger-swig-lldb
OS: Mac OS X
Arch: aarch64 (gradle: arm-v8)
Using platform: mac_arm_64

> Configure project :Decompiler
OS: Mac OS X
Arch: aarch64 (gradle: arm-v8)
Using platform: mac_arm_64

> Configure project :PDB
OS: Mac OS X
Arch: aarch64 (gradle: arm-v8)
Using platform: mac_arm_64

> Task :Debugger-swig-lldb:checkLLVM
Debugger-swig-lldb: using LLVM_HOME=/Users/cri/llvm-project

> Task :Debugger-swig-lldb:linkMainMac_arm_64SharedLibrary FAILED
ld: warning: directory not found for option '-L/Users/cri/llvm-project/lib'
ld: library not found for -llldb
clang: error: linker command failed with exit code 1 (use -v to see invocation)

> Task :Debugger-swig-lldb:linkMainMac_x86_64SharedLibrary FAILED
ld: warning: directory not found for option '-L/Users/cri/llvm-project/lib'
ld: library not found for -llldb
clang: error: linker command failed with exit code 1 (use -v to see invocation)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':Debugger-swig-lldb:linkMainMac_arm_64SharedLibrary'.
> A build operation failed.
      Linker failed while linking liblldb-java.dylib.
  See the complete log at: file:///Applications/ghidra_10.1.3_PUBLIC/Ghidra/Debug/Debugger-swig-lldb/build/tmp/linkMainMac_arm_64SharedLibrary/output.txt
   > Linker failed while linking liblldb-java.dylib.

The content of the output file is

See file:///Applications/ghidra_10.1.3_PUBLIC/Ghidra/Debug/Debugger-swig-lldb/build/tmp/linkMainMac_arm_64SharedLibrary/output.txt for all output for linkMainMac_arm_64SharedLibrary.
linking liblldb-java.dylib failed.
ld: warning: directory not found for option '-L/Users/cri/llvm-project/lib'
ld: library not found for -llldb
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Finished linkMainMac_arm_64SharedLibrary, see full log file:///Applications/ghidra_10.1.3_PUBLIC/Ghidra/Debug/Debugger-swig-lldb/build/tmp/linkMainMac_arm_64SharedLibrary/output.txt.

And no dylib is created in the lib folder
 /Applications/ghidra_10.1.3_PUBLIC/Ghidra/Debug/Debugger-swig-lldb/build/libs

Is correct to set  export LLVM_BUILD=/Users/cri/llvm-project. like  LLVM_HOME. ?
The instructions tellto  set LLVM_BUILD “path_to_llvm_build_directory_or_whatever_contains_lib/liblldb.(so/dylib/dll)”
I can find any dylib named  liblldb

The path that appear in error message
ld: warning: directory not found for option '-L/Users/cri/llvm-project/lib'
Doesn’t exist in   llvm-project 

Thank you for your help

**Comment by d-millar** [comment]
@crismi2 OK, going to ask a stupid question, but....have you already built llvm_project?  During that build process, you would have specified the "build" library.  I usually put it in llvm_project, but some folks consider that a bit unsanitary.  In any case, if that build succeeded, llvm_project/build/lib should have liblldb.13.0.1.dylib and a link liblldb.dylib in it.  You want LLVM_BUILD to point to one of those.

**Comment by crismi2** [comment]
@d-millar  Thank you so much for your time
I made a big mistake

I compiled llvm using brew and modified the gradle.build as you explained and it was all sorted out in no time

Thanks again
