### ISSUE TITLE
Adding Plugin Creation Documentation

### ISSUE THREAD

**Issue by Mst1k** [NationalSecurityAgency/ghidra#4240]
what about adding a specific field, explaining step to add plugins, where to start coding this, windows plugins, etc implement, is this alredy documented? i personally want to implement a plugin and dont know where to start looking in the code base

**Comment by dragonmacher** [comment]
Most of the items you mention are covered in some form in the help.  If you hover the mouse over an item in the UI and press F1, you will get context sensitive help for that item.

Our help for writing plugins is pretty much non-existent.  That is something we should  have.   In the meantime, we usually point new plugin writers to the sample plugins that live in our repo.  For example, 
```
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Extensions/sample/src/main/java/ghidra/examples/HelloWorldPlugin.java
```
There are other items in that folder, as well as other sample items in different modules in the repo, such as:
```
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Extensions/SampleTablePlugin/src/main/java/ghidra/examples/SampleTablePlugin.java
```

**Comment by dev747368** [comment]
there is also a fairly large chunk of javadoc at the top of Plugin.java

**Comment by Mst1k** [comment]
ill take a look at those examples, ill try to guide myself  with thouse examples
