### ISSUE TITLE
Class VertexSet not visible 

### ISSUE THREAD

**Issue by Deatty** [NationalSecurityAgency/ghidra#4243]
**Describe the bug**
A clear and concise description of the bug.
The class VertexSet in package ghidra.util.graph has default package visibility and thus I can't import it for use in my script. The class DirectedGraph which is in the same package has a vertices() method which returns a VertexSet object, the bug makes me unable to declare a variable of type VertexSet  to assign the result of the Vertices() method

**To Reproduce**
1. Create a new java script in Eclipse IDE with ghidraDev extension
2. import ghidra.util.graph.*
3. Create a variable of type VertexSet
4. See error 'The type VertexSet is not visible'

**Expected behavior**
VertexSet should be visible in order to correctly create a variable of this type.

**Screenshots**
![Screenshot 2022-05-13 105021](https://user-images.githubusercontent.com/75331144/168239562-f0c07b47-7865-4dad-8271-9b8b8af148ed.png)

**Environment:**
 - OS: Windows 10
 - Java Version: 11.0.14.1
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by dragonmacher** [comment]
That class has been deprecated.   Instead, we suggest the use of:
```
ghidra.graph.GraphFactory.createDirectedGraph()
```
which creates `GDirectedGraph`s. 

There are also other useful classes in that package, such as the `GraphAlgorithms` class, which makes it easy to perform some common graph operations.

**Comment by Deatty** [comment]
Didn't know it was deprecated. I'll change my script, thanks for the answer.
