### ISSUE TITLE
Error in runing in windows

### ISSUE THREAD

**Issue by kabiri** [NationalSecurityAgency/ghidra#4250]
i download Ghida 10.1.3 ("ghidra_10.1.3_PUBLIC_20220421.zip") from this link https://github.com/NationalSecurityAgency/ghidra/releases 
and OpenJDK17U-jdk_x64_windows_hotspot_17.0.3_7 and eclipse-java-2022-03-R-win32-x86_64

but when i run ghidraRun.bat ("C:\ghidra-Ghidra_10.1.3_build\Ghidra\RuntimeScripts\Windows") show this error :
Ghidra cannot launch in development mode because Eclipse has not compiled its class files.

What is the problem?
What should I do to run the program?

**Comment by ryanmkurtz** [comment]
You downloaded the source repository, not the build.  [This](https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.3_build/ghidra_10.1.3_PUBLIC_20220421.zip) is the download you desire.

**Comment by kabiri** [comment]
OK thanks i download it, it`s ok
but can not find java

my java :
C:\Users\hamid\Desktop>java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

When i run ghidraRun.bat show this :
'java -cp "C:\ghidra-Ghidra_10.1.3_build\Ghidra\support\LaunchSupport.jar" LaunchSupport "C:\ghidra-Ghidra_10.1.3_build\Ghidra\support\.." -jdk_home -save' is not recognized as an internal or external command,
operable program or batch file.
******************************************************************
JDK 11+ (64-bit) could not be found and must be manually chosen!
******************************************************************
Enter path to JDK home directory (ENTER for dialog): C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot
Saved changes to C:\Users\hamid\.ghidra\.ghidra_10.1.3_PUBLIC\java_home.save
'java -cp "C:\ghidra-Ghidra_10.1.3_build\Ghidra\support\LaunchSupport.jar" LaunchSupport "C:\ghidra-Ghidra_10.1.3_build\Ghidra\support\.." -jdk_home -save' is not recognized as an internal or external command,
operable program or batch file.

Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section.
Press any key to continue . . .

**Comment by ryanmkurtz** [comment]
Hmmm.  How are you launching `ghidraRun.bat`?  Are you double clicking it from an explorer window, or running it from a command prompt?  Or something else?

**Comment by kabiri** [comment]
i right click on ghidraRun.bat and run as admin
open CMD and type ghidraRun.bat then press ENTER
when i double clicking ghidraRun.bat show Error : windows can not find 'c:\ghidra....

**Comment by ryanmkurtz** [comment]
Did you just download the zip and extract it, or did you move things around?  I see your top-level Ghidra directory looks a little non-standard.

**Comment by kabiri** [comment]
I tried both.
I just extracted the file you gave.
After I got into trouble, I moved the file to another path.
I downloaded the Java sdk file again from the Oracle site.
I also added the Java path in Windows

**Comment by kabiri** [comment]
i remove java path from windows path (enviroment variables) and problem solved
