### ISSUE TITLE
Ghidra treating literals as labels: How do i to delete false constants/labels? 

### ISSUE THREAD

**Issue by MagnificentS** [NationalSecurityAgency/ghidra#4257]
Hi,
I seem to have an issue where the decompiler/disassembler treats literals as constants.
This affects hour for loops or general array indices are decompiled and in some cases regular functions too
![image](https://user-images.githubusercontent.com/8756646/168797354-128c4b65-3d22-410a-b0a1-400e5626b993.png)

![image](https://user-images.githubusercontent.com/8756646/168777026-290dd798-ebdb-40c4-9f18-c02c8142aef4.png)
In this situation, DAT_00007d00 is actually a number.  I tried deleting the memory reference
It fixes the disassembler for a moment but not the decompiler. and eventually reverts back
![image](https://user-images.githubusercontent.com/8756646/168777293-a89a5527-9ae6-49c0-8db9-e7b34f0ecccb.png)

there are a lot of these and they often have arbitrary sizes 1, 7 13 ...
![image](https://user-images.githubusercontent.com/8756646/168777554-a214fa45-4520-4730-b3d4-6cd9837583f0.png)

Not sure if it is a bu, so I am asking for help first
thanks

**Comment by Swyter** [comment]
Maybe you are asking something else, but there's the whole mutability thing that lets you mark chunks of memory as read-only or not. That way the decompiler interprets them as constants, as long as the type for the field is right.

**Comment by emteere** [comment]
When you load the program, can you change the load address?  I realize you can't always do that if it isn't PIC code.
The main issue is the offset appears to be part of memory so it is seen as a potential memory location.

The constant propagation min/max memory location can be changed so you don't get references in the lower or upper part of memory when the reference is an offset from another value.  Although this won't help the decompiler references.

Do you need to define all of memory 0x00000000-0xffffffff for your 32-bit space as it appears you may have done?  If the memory block doesn't exist, neither the decompiler or constant propagation will consider those numbers potential memory locations.

**Comment by DualTachyon** [comment]
I wouldn't say it's a bug because there's no way for Ghidra to know whether a literal is just a value or an address.
However I think it would be a nice feature to remove a reference to an address so that Ghidra knows it's a constant.
I can remove an Xref from an address in the disassembly view, but that doesn't always mean the decompiler will not try to use the value as an address.

Relocating code is a workaround at best and often not usable. I have a binary that uses a "class ID" for data structures and the values span the entire 32bit address space, and no matter where I'd place it (it's not relocatable anyway), it would end up with multiple constants as addresses.

**Comment by MagnificentS** [comment]
> When you load the program, can you change the load address? I realize you can't always do that if it isn't PIC code. The main issue is the offset appears to be part of memory so it is seen as a potential memory location.
> 
> The constant propagation min/max memory location can be changed so you don't get references in the lower or upper part of memory when the reference is an offset from another value. Although this won't help the decompiler references.
> 
> Do you need to define all of memory 0x00000000-0xffffffff for your 32-bit space as it appears you may have done? If the memory block doesn't exist, neither the decompiler or constant propagation will consider those numbers potential memory locations.

Hi, thanks for the reply.  I think I get some of what you are saying.
I did not set the memory range. it was all default.
I would try the constant propagation min-max location adjustment but i dont really know where that option resides
(Forgive me i am still new to this tool and my version of ghidra has been strange eg cannot set functions to __stdcall convention)

![image](https://user-images.githubusercontent.com/8756646/169223524-f74a3156-53bb-4043-a39c-59408e29333c.png)
![image](https://user-images.githubusercontent.com/8756646/169223807-e60218cc-b298-43ad-b242-8860f5adf1d8.png)


PS What does PIC code mean? Google gives me bad results

**Comment by ryanmkurtz** [comment]
> PS What does PIC code mean? Google gives me bad results

[Position-independent code](https://en.wikipedia.org/wiki/Position-independent_code)

**Comment by emteere** [comment]
The Speculative reference min/max is what you can change to help the issue.
Max is the maximum from the last address in memory, so (MaxAddress - <reference max>).  That was done because we don't have hex values in the options currently.  So if the max address for the address space is 0xffff, and SpeculativeReferenceMin is 16, then the maximum address would be 0xfff0.

In your above settings, the speculative address range is 0x000001ff-0xffffff00. (Yeah, hex numbers would be nice).

In your case, I'd try changing the SpeculativeReferenceMin to 0xffff.  You might miss some reference creation in the listing for low addresses.

Unfortunately this won't help the decompiler.
If you actually fill out the structure above and put data types in the structure, that might help the decompiler.

**Comment by emteere** [comment]
@MagnificentS did any suggestions help your issue?

**Comment by MagnificentS** [comment]
> @MagnificentS did any suggestions help your issue?

Unfortunately it did not

**Comment by emteere** [comment]
@MagnificentS Can you submit a copy paste of the byte string for the entire function in question?
Now that I think about it more, it is possible it is the  ScalarOperandReference  Analyzer (I'd turn that off).  We are close to removing that analyzer.  Then clear the function causing the references and re-disassemble it to see if the references come back.  They won't get removed on their own.

**Comment by MagnificentS** [comment]
Here is the file.
Actually, I uploaded 2 as I could not find the one used in this example.
It is a common issue so I don't know which function would be a good example
[functionBytes.zip](https://github.com/NationalSecurityAgency/ghidra/files/9128502/functionBytes.zip)

**Comment by emteere** [comment]
Thanks, will try to identify the culprit.

**Comment by MagnificentS** [comment]
> 65537

Trying this out

**Comment by MagnificentS** [comment]
![image](https://user-images.githubusercontent.com/8756646/180660350-7f55835e-20ba-48b1-a166-3388b3e609af.png)
![image](https://user-images.githubusercontent.com/8756646/180660455-7e84abfa-3bf3-4994-9332-ea2b6eb3a062.png)

Clearing with options I still end up with the above results
I made the changes to the X86ConstantReferenceAnalyzer  as well

**Comment by emteere** [comment]
There was a bug introduced from a refactoring of code that was ignoring the min speculative pointer size.  That should be fixed patch today, and in 10.1.5 coming out soon.  There already was a check on load/store accesses where the value was a register+OFFSET, but it was ignored.  Also for 64-bit programs the value was a larger value and that was ignored.

**Comment by MagnificentS** [comment]
No memory at those addresses

**Comment by emteere** [comment]
Ok, so if the memory doesn't exist, I would cut it out of you memory map.  Based on your screen capture above, the memory blocks have been allocated to include low memory from 0x0000-0xffff.  I would split your memory blocks and delete the blocks that don't actually exist.  That will solve a major part of the issue.
You'll also need to select all the references to those sections as mentioned above, and delete them.  You might do that before you delete the memory that doesn't exist from the memory map.

10.1.5, does now pay attention to the minimum speculative address, but the above is a much easier solution.

**Comment by Wall-AF** [comment]
This happens to my 16-bit apps all the time!  A solution I've found is to set the data segment to `0` on the appropriate assembly instruction(s).
