### ISSUE TITLE
Shadow beneath text in some areas.

### ISSUE THREAD

**Issue by legendaryzyper** [NationalSecurityAgency/ghidra#4260]
**Describe the bug**
Shadow appears beneath text in some areas including Symbol Tree, Data Type Manager and the Project Manager. However it does not appear on Program Trees.

**Screenshots**
![image](https://user-images.githubusercontent.com/88670305/169025522-fc30554e-6732-4492-9b3b-378b16e0e48a.png)
![image](https://user-images.githubusercontent.com/88670305/169025903-4acb2929-fcd0-472e-90d1-98ebc12abad2.png)

**Environment:**
 - OS: Manjaro
 - Java Version: SE 18
 - Ghidra Version: 10.1.3
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by ryanmkurtz** [comment]
I've been seeing this in standard Ubuntu's for some time.

**Comment by astrelsky** [comment]
> I've been seeing this in standard Ubuntu's for some time.

![46-469978_hd-jackie-chan-meme-png-393765-transparent-png.png](https://user-images.githubusercontent.com/46897303/169279441-80d9da22-2437-4ceb-8686-052d792d2259.png)

**Comment by dev747368** [comment]
basically every tree except for the Program Tree looks bad.
