### ISSUE TITLE
trailing comma in global arrays display

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4261]
**Describe the bug**
Not really a bug maybe, just a UI and copy/paste-ability issue.

If there is a global array, `int[16]` for example you would see something like

```
AABBCC00 00 00 00            int...
                  00 00 00
                  00 00 00 ...
    AABBCC00  [0]                     0h,    0h,    0h,    0h
    AABBCC10  [4]                     0h,    0h,    0h,    0h
    AABBCC20  [8]                     0h,    0h,    0h,    0h
    AABBCC30  [12]                    0h,    0h,    0h,    0h
```

It would be nice if there was a trailing comma, probably/preferably only the last line w/o one.

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: 11.0.10
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official

**Comment by astrelsky** [comment]
I think the last element in an array can have a trailing comma in c too.
