### ISSUE TITLE
X86 disassembler fails to recognize FWAIT and FDISI

### ISSUE THREAD

**Issue by enderdrag64** [NationalSecurityAgency/ghidra#4262]
**Describe the bug**
In some situations the ghidra disassembler fails to recognize certain floating point instructions.

**To Reproduce**
1. If you disassemble the following binary blob (from the OpenWatcom C library - function __FPE2Handler) [50 53 51 52 56 57 55 1e 06 83 ec 1c 89 e5 d9 75 00 9b 9b db e2 9b db e1 fb e8 92 4b fb] you will get this:

        00109ac8 50              PUSH       EAX
        00109ac9 53              PUSH       EBX
        00109aca 51              PUSH       ECX
        00109acb 52              PUSH       EDX
        00109acc 56              PUSH       ESI
        00109acd 57              PUSH       EDI
        00109ace 55              PUSH       EBP
        00109acf 1e              PUSH       DS
        00109ad0 06              PUSH       ES
        00109ad1 83 ec 1c        SUB        ESP,0x1c
        00109ad4 89 e5           MOV        EBP,ESP
        00109ad6 d9 75 00        FNSTENV    [EBP]=>local_40
        00109ad9 9b              WAIT
        00109ada 9b db e2        FCLEX
        00109add 9b              WAIT
        00109ade db              ??         DBh
        00109adf e1              ??         E1h
        00109ae0 fb              STI

with an error bookmark at 00109ade saying "Error [Bad Instruction]: Unable to resolve constructor at 00109ade (flow from 00109add)"

**Expected behavior**
00109ad9 through 00109adf are not disassembled correctly here. If you look at the original assembly listing for the function in the OpenWatcom sources (https://github.com/open-watcom/open-watcom-v2/blob/6b9cb4438959d845a2b4dd4bf19f7908ecd608e9/bld/clib/math/a/fpeinth.asm) you'll see that they should be disassembled as:
FWAIT 
FDISI

**Screenshots**
![image](https://user-images.githubusercontent.com/33301226/169338962-f4ff5c4f-4f52-46c0-be2d-2b470f4fea8b.png)
![image](https://user-images.githubusercontent.com/33301226/169339117-2b3b2300-0879-42d4-8d9a-dc1b63f03dd2.png)

**Attachments**

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Java Version: 12.0.1
 - Ghidra Version: 10.1
 - Ghidra Origin: GitHub releases

**Additional context**

**Comment by GhidorahRex** [comment]
`WAIT` and `FWAIT` are identical instructions. However, the `FDISI` opcode appears to be valid x87 (and most likely should perform a nop). See (https://en.wikipedia.org/wiki/X86_instruction_listings). There's a few other valid but no longer used opcodes missing here.
