### ISSUE TITLE
Ghidra not disassembling NRF52 firmware without symbols

### ISSUE THREAD

**Issue by JeroenRobbenFirmalyzer1** [NationalSecurityAgency/ghidra#4263]
Hi,

I have run into an issue when analyzing NRF52 firmware binaries. It seems Ghidra is not disassembling the fimware correctly when imported as hex ([sample.hex.zip](https://github.com/NationalSecurityAgency/ghidra/files/8740678/sample.hex.zip)). When importing as elf (with symbols, [sample.elf.zip](https://github.com/NationalSecurityAgency/ghidra/files/8740679/sample.elf.zip)), everything works fine.

**To Reproduce**
1. Unzip [sample.hex.zip](https://github.com/NationalSecurityAgency/ghidra/files/8740678/sample.hex.zip)
2. Import sample.hex as ARM Cortex little-endian 32-bit
3. Run auto-analyzers

**Expected behavior**
Firmware file is disassembled correctly (e.g. Reset function handler at 0x308)

**Environment:**
 - OS: Ubuntu 22.04
 - Java Version: 15.0.2
 - Ghidra Version: 10.1.3
 - Ghidra Origin: Github release, ghidra_10.1.3_PUBLIC_20220421.zip

Thanks!

**Comment by emteere** [comment]
I've been able to duplicate the issue.

The Elf has extra markup that identifies code locations.

For the hex code there is no information other than the processor interrupt vectors, and possibly normal code start patterns.
The interrupt vector symbols are laid down, but are checked for pointing to a valid subroutine, which is sometimes incorrect as in this case.

I've made a prototype change to trust interrupt vectors that are code pointers the same way interrupt vectors that contain code are trusted.  The checking for valid subroutine won't occur.  The bulk of the code is disassembled with a minor amount of code not disassembled.
