### ISSUE TITLE
Ghidra 10.1.4 - Does not connect to defined shared ghidra server

### ISSUE THREAD

**Issue by dzik87** [NationalSecurityAgency/ghidra#4266]
**Describe the bug**
After reopening last shared project it does not connect to right server. Instead it connnects to this one always.
![image](https://user-images.githubusercontent.com/8008528/169577624-df7f0469-3178-49e2-9565-f2bb1b7f0425.png)

Even browsing repo with correct server address connects to this one instead
![image](https://user-images.githubusercontent.com/8008528/169582870-191cd7c5-cb23-4709-8f25-3b7e5ac4a3ae.png)

Also it appears that numbers in address are randomized somehow
![image](https://user-images.githubusercontent.com/8008528/169582370-185dcc24-4489-4ba6-8552-4e3f8fe0dfe9.png)

Ghidra 10.1.4
Windows 10

**Comment by dev747368** [comment]
The hostname that your screenshot shows is a google server's ip address.  (anything 1e100.net is google)

any-in-2415.1e100.net points to 216.239.36.21.  Is that the server you were trying to connect to?  (it seems like you redacted a part of your screenshot that shows the hostname you were connecting to).

Did this work previously and just stop?  Did it work with previous version of Ghidra?  Have you tried connecting to your Ghidra server from a different workstation?

What configuration options are used in the Ghidra server's server.conf?

**Comment by dzik87** [comment]
Seems like issue is on our end. Our domain is not pointing to correct ip address anymore. 

I'll close issue since its not an ghidra issue really.
