### ISSUE TITLE
Function pointer type as structure field

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#427]
For example, I have virtual table with function pointers and fields.
It is possible to create function definition in data types, and then specify it as the structure field type. But, it doesn't work:
![image](https://user-images.githubusercontent.com/7189309/56095685-fc9b4000-5ee7-11e9-929c-08d497d632b9.png)

Pseudo code still doesn't contain function pointer arguments specified. How to do that?

Function type is:
![image](https://user-images.githubusercontent.com/7189309/56095706-32402900-5ee8-11e9-97c8-d793ab82b48c.png)

**Comment by lab313ru** [comment]
Problem also is that FindTask accepts first argument in A1 register (Motorola) which is not default for first argument.

**Comment by philippTheCat** [comment]
You can override the function call locally in the calling function

**Comment by lab313ru** [comment]
How to do that?
There is no option for that

**Comment by ddbb2017** [comment]
yeah, I'd like to know too how do you add a vtable member to a custom struct. I was using FARPROC* type but it behaves pretty much just like if I had `undefined` in it:

![Capture1](https://user-images.githubusercontent.com/33359889/56161372-2f901300-5f7e-11e9-964b-a906a9070b82.PNG)

**Comment by philippTheCat** [comment]
@ddbb2017 that is different. You want to create a function type (in the data types window), and then use this as data type here.

@lab313ru I dont have ghidra available right now, but if I remember correctly you rightclick on the function call in the disassembly, there should be an option "override function call" or similar

**Comment by lab313ru** [comment]
There is no such option for the structure field

**Comment by z3ntu** [comment]
Yep, in the Data Type Manager, New -> Function Definition; enter the function you want to reference later (so for the struct member `int (*hdr_func)(P_STP_PARAMS_CONFIG pStpParamsConfig);` enter `int hdr_func(P_STP_PARAMS_CONFIG pStpParamsConfig)`), and use that function in the Structure Editor
![image](https://user-images.githubusercontent.com/3768500/58371522-277aaa00-7f12-11e9-8795-07bf1274b2cc.png)

**Comment by recvfrom** [comment]
Just to help others who may stumble across this ticket when looking for help defining/using function pointers in Ghidra; If you are trying to define a function pointer where the C equivalent is something like:
```
typedef void (*ATTACK_FUNC) (uint8_t, struct attack_target *, uint8_t, struct attack_option *);
```
Assuming you've defined the `attack_target` and `attack_option` structures in Ghidra, the function should be defined in Ghidra with:
```
void ATTACK_FUNC (uint8_t, attack_target *, uint8_t, attack_option *)
```

**Comment by martmists** [comment]
@recvfrom Does that still work in latest? I'm getting the following:
![image](https://user-images.githubusercontent.com/16361449/78837625-c5754700-79f4-11ea-852e-36ae79c7fcdf.png)
defined as 
```c
typedef FSResult (*FS_ARCHIVE_PROC_FUNC) (struct FSFile *, FSCommandType);
```
FSResult, FSFile and FSCommandType are all registered types.

**Comment by recvfrom** [comment]
@martmists Use `New->Function Definition...` instead of `New->Typedef...`.  So for the example I posted above, the popup should look like:
![image](https://user-images.githubusercontent.com/36489577/78856428-c9a16480-79f4-11ea-808d-ddff962ac2ac.png)
