### ISSUE TITLE
Custom plugins do not load after plugin package name is blacklisted?

### ISSUE THREAD

**Issue by mfthomps** [NationalSecurityAgency/ghidra#4283]
I am developing custom plugins for the Debugger by extending AbstractDebuggerPlugin.  
I start by copying a working plugin into a new package and refactoring its module names using Eclipse.
The new plugin then loads when I start the debugger, as reflected in messages to the log.
I then introduce an error into the new plugin, causing it to fail.
After fixing or reverting the error and rebuilding, the new plugin no longer loads when starting the debugger.
I have confirmed this sequence 3 times.  I have found that  re-using the name of a previously failed plugin within a new copy of a working plugin will prevent that new plugin from loading.
Also, if after failing and reverting the error, I refactor the name of the package to something new, the plugin loads fine.
It appears as if a failure in a plugin places the name of the package on a cached blacklist.  Is there a way to flush that cache or otherwise work around this?
Thanks.

**Comment by mfthomps** [comment]
I see, this is managed by the "exclude" field in _debugger.tcd beneath the ~/.ghidra directory.
As a work-around I can restore a good version of that file.
Is there a better solution?

**Comment by dev747368** [comment]
Can you re-enable the failed plugin in your debugger tool window?

File | Configure | <little plug shaped icon in upper right corner of window> | find your failed plugin and put a check next to it to turn it back on

**Comment by mfthomps** [comment]
Yes, that works.  I had missed that dialog.  Thank you!
