### ISSUE TITLE
Missing alternate 'return' mnemonic in context evaluator in class CallDepthChangeInfo

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4293]
In the embedded `ContextEvaluator` instance of class `CallDepthChangeInfo` the method `evaluateContext(...)` limits some changes to `stackPurge` to terminals using mnemonic 'ret'.  Shouldn't this also occur for those called 'retf'?

**Comment by Wall-AF** [comment]
The code secction:
https://github.com/NationalSecurityAgency/ghidra/blob/7a30cefebb91ddb25a6c4030e67001202fd20936/Ghidra/Features/Base/src/main/java/ghidra/app/cmd/function/CallDepthChangeInfo.java#L526-L544

**Comment by emteere** [comment]
You are right, it should set the purge specially for RETF as well.
