### ISSUE TITLE
Debugger doesn't work with gdb 12

### ISSUE THREAD

**Issue by ucasqsl** [NationalSecurityAgency/ghidra#4297]
**Describe the bug**
Ghidra debugger doesn't work with gdb 12, the dynamic listing and the memory view won't show the correct result.

**To Reproduce**
1. Use the Ghidra debugger with the gdb release on Ubuntu 22.04 or archlinux
2. Check the dynamic listing and memory view

**Expected behavior**
The dynamic listing should display the instructions being executed

**Screenshots**
![image](https://user-images.githubusercontent.com/90229858/171099318-16bbc69f-bac4-4b26-906e-a29f8941eee6.png)

**Attachments**
[secrecy.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/8802251/secrecy.tar.gz)

**Environment (please complete the following information):**
 - OS: [e.g. Archlinux]
 - Java Version: [11.0.15]
 - Ghidra Version: [10.1.4]
 - Ghidra Origin: [official ghidra-sre.org distro] 
 - Gdb  Version: [12.1]

**Comment by ucasqsl** [comment]
> @ucasqsl Happy to try to troubleshoot this - any chance you could run the following two commands, either in gdb proper or in the Interpreter window?
> 
> info proc mappings maintenance info sections ALLOBJ nosections
![Screenshot_20220601_143715](https://user-images.githubusercontent.com/90229858/171342777-1046c0ca-ca7a-4825-a622-d63a8fd707d7.png)

**Comment by d-millar** [comment]
Wow, hmmmm - those are the answers I would have expected, which should mean you’d have good values in the Modules and Regions views.  Bad/missing values there are typically the cause of the failure in the dynamic listing.  

The other possibility is that the trace itself has somehow failed.  I can’t see what’s in Threads, Registers, or most of the trace-driven windows in your screenshot, but the fact that you have entries in the Time window suggests a trace was started. 

Unfortunately, am on the road at the moment without my computer, but have asked @nsadeveloper789 to take a look at this too.

**Comment by nsadeveloper789** [comment]
I'm not sure I've seen that layout for `info proc mappings` before. I'm guessing GDB changed it. *sigh*. On the good news front, it looks like they added a "Perms" column!!! The "Debug Console" may provide some hint at the errors, but I suspect to solve this, we'll have to try GDB 12 ourselves. In the meantime, and I realize this may be unpleasant, the best workaround is probably to compile and install GDB 11. I recommend setting the install prefix to somewhere in your home directory, so you're not modifying your system out-of-band from the package manager.

To be sure this is the only issue, could you please expand the "Modules" node in the Objects tree and confirm the accuracy of that list? Or is it empty?

**Comment by ucasqsl** [comment]
> To be sure this is the only issue, could you please expand the "Modules" node in the Objects tree and confirm the accuracy of that list? Or is it empty?

![Screenshot_20220603_163631](https://user-images.githubusercontent.com/90229858/171819471-669b214e-b04c-4e46-a922-adb5f0e538bf.png)
Only `libc` and `ld`, but the program itself doesn't appear.

**Comment by nsadeveloper789** [comment]
Hmm. The address ranges are also 000s. I'll note that, too for GDB 12 compatibility. Thanks!
