### ISSUE TITLE
Do you know a forum for Ghidra?

### ISSUE THREAD

**Issue by kabiri** [NationalSecurityAgency/ghidra#4298]
I want to ask my questions there about Guidora and its settings and function and the definition of micro.
For example, what about the coldfire mcf5372 memory map?

**Comment by ryanmkurtz** [comment]
This is the official "forum". You could ask your question either in a new [Issue](https://github.com/NationalSecurityAgency/ghidra/issues) or new [Discussion](https://github.com/NationalSecurityAgency/ghidra/discussions).
