### ISSUE TITLE
Changing username when connecting to Ghidra server

### ISSUE THREAD

**Issue by flux1on** [NationalSecurityAgency/ghidra#43]
Currently, Ghidra seems to default to using your current account name when connecting to a Ghidra server instance even if you specify the `-u` option in the `server.conf` file.

**Comment by gnooby22** [comment]
That is the correct option.  Be sure you order and number the config parameters:

**Comment by gnooby22** [comment]
wrapper.app.parameter.1=-a0
wrapper.app.parameter.2=-u
wrapper.app.parameter.3=${ghidra.repositories.dir}

**Comment by flux1on** [comment]
I was originally testing it without any authentication (no `-a` option). Does the `-u` option only work if you have some form of authentication?

**Comment by gnooby22** [comment]
No authentication avoids the prompting, so no way to enter a different name.

**Comment by flux1on** [comment]
Okay, thanks for the clarification.

**Comment by wyattearp** [comment]
Should anyone else come across this, what's happening internally is that the Ghidra client is selecting the `System.getProperty('user.name')` from the JVM and using that as a default for authentication. You can see an example of this here: 

https://github.com/NationalSecurityAgency/ghidra/blob/21893b10f69905626018cd30db9f4a6b7964a17f/Ghidra/Framework/Utility/src/main/java/ghidra/util/SystemUtilities.java#L137

If you're in need of a workaround (let's you're authenticating across computer domains for some reason), you can manually modify the `./support/launch.properties` to override this value as follows:

```./support/launch.properties
# ... 
# ...
# ... 

# Set default encoding to UTF8
VMARGS=-Dfile.encoding=UTF8

# Set locale (only en_US is supported)
VMARGS=-Duser.country=US
VMARGS=-Duser.language=en
VMARGS=-Duser.variant=

# add a new JVM defined argument to overwrite System.getProperty('user.name')
VMARGS=-Duser.name=wyattearp

```

Tested and functions on Ghidra 11.2.1 with basic authentication - your mileage might vary.
