### ISSUE TITLE
Opening processor manual fails on Ubuntu 22.04 w/default snap installed Firefox due to snap sandboxing

### ISSUE THREAD

**Issue by oldmanludd** [NationalSecurityAgency/ghidra#4306]
**Describe the bug**
On Ubuntu 22.04, using the default snap based Firefox install, opening processor manuals via CodeBrowser Listing's right-click menu fails.

Firefox opens but displays the following error:

```File not found

Firefox can’t find the file at /tmp/pdfView12297125562363118529.html.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.
```

The HTML file is being created as expected in /tmp. However due to the way snap applications are sandboxed Firefox can't open it from that file path. On Ubuntu 22.04 Firefox maintains it's own separate tmp directory under the user's homedir at  ~/Downloads/firefox.tmp because that's a path snap sandboxing is permitted to access.

I realize this is less of a Ghidra issue and more of  a snap / Firefox making breaking changes issue but I thought it was worth raising here for visibility. If you disagree feel free to close.

**To Reproduce**
1. Install Ubuntu 22.04
2. Install Ghidra
3. Download and any processor manual PDF and move it to the correct directory under Ghidra/Processors/processor_name/data/manuals/
4. Import a binary of the same architecture as the manual into Ghidra and open it in the CodeBrowser
5. In the CodeBrowser's Listing view right-click anywhere and select Processor Manual...

**Expected behavior**
Listing View > right-click > Processor Manual... should successfully open available processor manual when using a browser installed from a snap

**Screenshots**

![Screenshot from 2022-06-02 21-24-14](https://user-images.githubusercontent.com/106788589/171770600-c6892964-97a7-4300-b6f9-e5ac1315e4e9.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: openjdk 11.0.15 
 - Ghidra Version: 10.1.3
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**

snapd bug discussing no access to /tmp files
https://bugs.launchpad.net/snapd/+bug/1972762

Firefox bug discussing the firefox.tmp dir in home dir
https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1958813

**Comment by ryanmkurtz** [comment]
Do you think they are going to stick with this sandboxing behavior?  I see [this](https://github.com/canonical/firefox-snap/commit/250d24a72953fd797a10ec2fe338fcd0fe2491ff) happened but I am not sure if that will fix the issue in the next Firefox release, or if that is doing something else that won't have an impact on this issue.

**Comment by dev747368** [comment]
In my testing just now, Ubuntu's file browser fails to open .html files that are anywhere other than the user home directory because of this snap issue.  Fun.

As a workaround, I could get it to work if

1) I edited my support/launch.properties and set my -Djava.io.tmpdir to a directory under my home directory. (it can NOT be a dot directory like ~/.ghidra/tmp)
2) my ghidra install was under my home directory (ie. ~/bin/ghidra_10.1.blah/)

If you only edit the launch.properties file, a web page will open, but it will be blank because that initial webpage is a small wrapper that points to the pdf inside the ghidra install directory, and firefox will fail if it is outside of the user's home dir.

**Comment by ryanmkurtz** [comment]
Thanks for the workaround info.  We are going to consider this a firefox issue and close it.  It shall continue to serve as a valuable reference though.

**Comment by knotapun** [comment]
For anyone looking back at this, I found that you can soft-link the manuals in a different folder. Firefox appears to dereference the symbolic link, despite the URL. 

I did something along the lines of:
```bash
mkdir ~/ghidra_manuals/
mv <ghidra-path>/Ghidra/Processors/<architecture>/data/manuals/<file-name> ~/ghidra_manuals/
ln <ghidra-path>/Ghidra/Processors/<architecture>/data/manuals/<file-name> ~/ghidra_manuals/<file-name> -s
```
