### ISSUE TITLE
Ghidra Ignores Sign-Extension of Memory Operand Displacement Values

### ISSUE THREAD

**Issue by sjcappella** [NationalSecurityAgency/ghidra#4310]
**Describe the bug**
Displacement values (as I understand them) when calculated as part of an effective memory address should be sign-extended to the size specified in the instruction encoding. While Ghidra correctly identifies the size of the displacement value, it does not sign-extend it. This produces inaccurate/misleading disassembly and incorrect instruction semantics in PCode.

Consider the following opcodes:
`64 48 8b 0c 25 c8 ff ff ff`

IDA Disassembly:
`mov     rcx, fs:0FFFFFFFFFFFFFFC8h`

Binary Ninja Disassembly:
`mov     rcx, qword [fs:0xffffffffffffffc8]`

Zydis Disassembly:
`mov rcx, qword ptr fs:[0xFFFFFFFFFFFFFFC8]`

Ghidra Disassembly:
`MOV          RCX,qword ptr FS:[0xffffffc8]`

Additionally, the PCode semantics for this instruction results in the following:
```
$U4f00:8 = INT_ADD FS_OFFSET, 0xffffffc8:8
$Uc000:8 = LOAD ram($U4f00:8)
RCX = COPY $Uc000:8
```

In this situation, the value `0xffffffc8` is of size `8` (64-bits), so the result of the add operation (which is also 64-bits in size) will not result in the correct result. Consider the semantics produced by two other popular analysis tools:

BinaryAnalysisPlatform (BAP) Semantics:
```
RCX := mem[FS_BASE - 0x38, el]:u64
```

Binary Ninja Semantics:
```
rcx = [fsbase - 0x38].q
```

**To Reproduce**
1. Write the opcodes `64 48 8b 0c 25 c8 ff ff ff` into a binary file
2. Load the file in Ghidra and disassemble as x86-64
3. View Disassembly and PCode

**Expected behavior**
The results of the disassembly to sign-extend the displacement in a manner consistent with other tools.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Java Version: 11.0.7
 - Ghidra Version: 10.1.4
 - Ghidra Origin: Official GitHub release

**Comment by mumbel** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/28e3c2b8db43a3296a7b6f292afb2910f7cc7eea/Ghidra/Processors/x86/data/languages/ia.sinc#L736

is the issue, its using `imm32_64` but maybe should be using `simm32_64` instead

> Generally, displacements and immediates in 64-bit mode are not extended to 64 bits. They are still limited to 32
bits and sign-extended during effective-address calculations. In 64-bit mode, however, support is provided for 64-
bit displacement and immediate forms of the MOV instruction.

**Comment by sjcappella** [comment]
That was my thought as well considering the use of `simm` elsewhere

**Comment by ghidra1** [comment]
This probably the result of directly using a token field in the print piece (i.e., operand).  This constant should be handled via subconstructor which exports the sign-extended constant to the correct size.

**Comment by mumbel** [comment]
> @mumbel I would probably agree with your observation although I have not verified.

Yeah, I didn't look much further than that, like if there is some insn that does expect that imm32_64.  I didn't know how to interpret that quote from the manual
