### ISSUE TITLE
Sleigh doc context variable example seems incorrect

### ISSUE THREAD

**Issue by rgov** [NationalSecurityAgency/ghidra#432]
§6.4 says, "Context variables are defined with a define context statement. The keywords must be followed by the name of a defined register."

§6.8 gives this example:

```
...
define register offset=0 size=4 [ r0 r1 r2 r3 r4 r5 r6 r7 ];
define register offset=0x100 size=4 [ s0 s1 s2 s3 s4 s5 s6 s7 ];
...
define context statusreg
  mode=(3,3)
;
...
```

Here, `statusreg` is used as the register for the context variable `mode`, but no such register exists.

**Comment by mumbel** [comment]
I would re-read that whole section. `mode` here is a global status, not a register (rN or sN in this example). Its state tells the instruction definition which registers to use, rN or sN, at runtime.

**Comment by rgov** [comment]
What I understand is that `define context` maps bits of a specific register's value to context variables, analogous to how `define token` maps bits of the encoded instruction to fields. In the example, the register whose bits we are mapping to context variables is called `statusreg`. But it is not defined.

Is that not a correct interpretation?

**Comment by mumbel** [comment]
Sorry misunderstood you question.  yeah I agree there should be a `define register` for `statusreg` in the example

**Comment by Ionut1994** [comment]
Good afternoon! I would like to solve this issue if nobody else is working on it. Is it ok if I do so?
