### ISSUE TITLE
Modulo Simplification

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4322]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see a bunch of shifts, division, logical and other arithmetic for the modulo operation.

**Describe the solution you'd like**
The operations to be simplified into the modulo operation.

**Describe alternatives you've considered**
Opening up the program in IDA to see what is really going on. I am guilty of doing exactly this as it still beats breaking out a pencil and paper to figure it out.

**Additional context**
```c
int mod6(int i) {
    return i % 6;
}
```

![image](https://user-images.githubusercontent.com/46897303/172498148-1f085773-eae4-4603-aadd-25b526002e27.png)

Here are some xml debug function decompilation outputs. (This one is guilty of not automatically appending the xml file extension)

[mod2.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/8857061/mod2.xml.txt)
[mod3.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/8857062/mod3.xml.txt)
[mod4.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/8857063/mod4.xml.txt)
[mod6.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/8857064/mod6.xml.txt)

See, I *do* know what the modulo operator is...

**Comment by pjsoberoi** [comment]
So you want to undo peephole optimization. Is there any way besides hardcoding a list of heuristics? Sounds like an interesting project.

**Comment by Swyter** [comment]
There has been a lot of progress with deoptimizing/recovering division by constants, this should be pretty similar, I think.

**Comment by astrelsky** [comment]
> So you want to undo peephole optimization. Is there any way besides hardcoding a list of heuristics? Sounds like an interesting project. 

This was compiled with `-O1`. I understand why it would be difficult to detect but it's extremely common. If it didn't obfuscate the decompilation results then I wouldn't complain about it.

**Comment by sad-dev** [comment]
Like @Swyter mentioned, work has been done for division by constants (see #1718, #668). Something like 2463cad should be doable eventually?

**Comment by astrelsky** [comment]
Thank you! @caheckman
