### ISSUE TITLE
Branch flow in delay slot not followed in disassembly

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4325]
**Describe the bug**
A ~~clear and concise~~ description of the bug.

The instruction pair and the corresponding pcode is as follows:
```
      ram:01cc55 61 e3           SKH
                                                      $Ud500:1 = INT_RIGHT PSW, 6:4
                                                      $Ud580:1 = INT_AND $Ud500:1, 1:1
                                                      $Ud600:1 = INT_AND PSW, 1:1
                                                      $Ud680:1 = INT_OR $Ud580:1, $Ud600:1
                                                      CBRANCH *[ram]0x1cc5a:3, $Ud680:1
                                                      BRANCH *[ram]0x1d692:3
      ram:01cc57 ee 38 0a        _BR        $!LAB_ram_01d692
                                                      BRANCH *[ram]0x1d692:3
```

However the instructions at `0x1d692` are not disassembled. The instructions directly following the delay slot are properly disassembled.

**Expected behavior**
Even though you can't have a branch in a delay slot on most architectures and that this is a hack, the flow should be followed and the instructions should be disassembled.

**Additional context**
#4241

**Comment by ghidra1** [comment]
Could you please indicate what revision of Ghidra was used (build or commit#)

**Comment by astrelsky** [comment]
> Could you please provide the Sleigh spec for the sample above. At a minimum the portions which relate to the sample.

I figure this link will kill 2 birds with one stone
https://github.com/astrelsky/RL78_sleigh/blob/aa5e9fb26a88c34455b1e9ac88164f5408d1eeca/data/languages/rl78_instructions.sinc#L1495

> Could you please indicate what revision of Ghidra was used (build or commit#)

bb5cab82058d2349798c11c289408431dd60d716


An example of the problem can be seen in this file [mcu-firm.bin](https://github.com/hedgeberg/RL78_sleigh/blob/master/test_bins/mcu-firm.bin) at address `0x002179`. Be advised that this processor is... well... fun. Just ignore all the error bookmarks. The one I've been working with is not nearly as bad at doing things the manual explicitly says you can't do, but I can't share it due to copyright issues.

**Comment by ghidra1** [comment]
The flow type of the delay slotted instruction (e.g., SKH) is not factoring in the delayslot code (e.g., BR) when establishing its flow flags which results in a simple flow type of FALL_THROUGH for the SKH instruction.  The flow flags are specific to the reusable instruction prototype which does not consider the pcode which gets injected by a delayslot.  The instruction flow type is key to the disassembler, blow models and analysis and is clearly wrong in this case.  This presents a dilemma as to this delayslot situation should be handled.  
```
:SKH is opcode=0x61; opcode=0xE3 {
    if ($(Z) | $(CY)) goto inst_next;
    delayslot(1);
}
:BR jaddr16 is opcode=0xED; jaddr16 {
    goto jaddr16;
}
```
![Screenshot at 2022-06-10 17-16-00](https://user-images.githubusercontent.com/48333017/173152410-6cf12c1a-2f3d-4bd2-846e-f87b9128f0d3.png)

**Comment by astrelsky** [comment]
> The flow type of the delay slotted instruction (e.g., SKH) is not factoring in the delayslot code (e.g., BR) when establishing its flow flags which results in a simple flow type of FALL_THROUGH for the SKH instruction. The flow flags are specific to the reusable instruction prototype which does not consider the pcode which gets injected by a delayslot. The instruction flow type is key to the disassembler, blow models and analysis and is clearly wrong in this case. This presents a dilemma as to how this delayslot situation should be handled.
> 
> ```
> :SKH is opcode=0x61; opcode=0xE3 {
>     if ($(Z) | $(CY)) goto inst_next;
>     delayslot(1);
> }
> :BR jaddr16 is opcode=0xED; jaddr16 {
>     goto jaddr16;
> }
> ```
> 
> ![Screenshot at 2022-06-10 17-16-00](https://user-images.githubusercontent.com/48333017/173152410-6cf12c1a-2f3d-4bd2-846e-f87b9128f0d3.png)

I see how this can be a problem. I think it might be more trouble than it is worth. Even if the disassembler is updated to handle this situation it might still be problematic for things like the `SymbolicPropogator` and stack analysis and other things that have to explicitly handle delay slots.

**Comment by astrelsky** [comment]
https://github.com/NationalSecurityAgency/ghidra/discussions/4241#discussioncomment-2929830
