### ISSUE TITLE
Shared data type or Copy data type with copy 

### ISSUE THREAD

**Issue by wj5449** [NationalSecurityAgency/ghidra#4331]
shared datatype in one project
or one of the folling
create data struct with copy and paste
create data struct with file

**Comment by ryanmkurtz** [comment]
Hello.  Would you mind elaborating on what you asking for by describing your use case and the problem you are trying to solve.  More details would be very helpful.

**Comment by dragonmacher** [comment]
Yous should be able to perform these actions now using our shared project and shared file archives.

**Comment by wj5449** [comment]
> Hello. Would you mind elaborating on what you asking for by describing your use case and the problem you are trying to solve. More details would be very helpful.

when i use edit data type , i find some data type is shared for two dll files, 
it's huge work when data type is lagre
so i think is't better to create shared datatype in different project files

**Comment by wj5449** [comment]
> You should be able to perform these actions now using our shared project and shared file archives.
Thanks for the reply.
I don't know how to share ,
I know  the Create Project  Page with shared feature,but what is server name? 
Is Any Link to the Server Name？

**Comment by Wall-AF** [comment]
If I understand you're issue correctly, you can drag'n'drop elements from one CodeBrowser's "Data Type Manager" window to another.  Not as good as sharing, but better than typing or export/import.

**Comment by dragonmacher** [comment]
If you are asking whether we have a server for sharing data types, then no, we do not have that.  This is something that would need to be created by the community.

As mentioned above, you can create your own reusable archives of data types that you can use repeatedly  when reversing.  Further, you can share these archives with your friends.   See the Ghidra help page titled "Data Type Manager", specifically, the section titled "Working with Data Type Archives" for more info on this concept.

As @Wall-AF mentioned, once you have created these archives, you can use copy/paste or drag-n-drop to move saved types from your archives to the program you are reversing.  There are also actions in the Data Type Manager to keep the data types in sync.
