### ISSUE TITLE
Boolean datatype not propagated into Varnode

### ISSUE THREAD

**Issue by RootCubed** [NationalSecurityAgency/ghidra#4338]
**Describe the bug**
If the return type of a function is marked as `bool`, the decompiler is unable to propagate this information into the corresponding `CPUI_CALL` opcode (i.e. `isCalculatedBool` returns false) and is therefore unable to apply any boolean-specific simplification rules such as RuleBooleanNegate.

This also occurs if the decompiler is unable to infer the boolean type of a variable on its own and the user manually marks it as `bool`.

However, if the compiler *is* able to infer the boolean type on its own (such as, if the function `getBoolean` from the example below is inlined), the boolean-specific simplification rules are applied as expected.

**To Reproduce**
1. Compile the following cpp program:
```cpp
bool getBoolean(int a) {
    return a > 5;
}

int test(int a) {
    if (getBoolean(a)) {
        return 0;
    }
    return a;
}

int main() {
    test(42);
}
```
2. Import into Ghidra.
3. Analyze the program with default settings.
4. Navigate to the function `test`.
5. Observe that the decompilation looks as follows:
```cpp
int __cdecl __Z4testi(int param_1)

{
  bool bVar1;
  
  bVar1 = __Z10getBooleani(param_1);
  if (bVar1 != false) {
    param_1 = 0;
  }
  return param_1;
}

```

**Expected behavior**
RuleBooleanNegate should apply here and the decompilation should read as follows:
```cpp
...
bVar1 = __Z10getBooleani(param_1);
if (bVar1) {
...
```

**Environment**
 - OS: Windows 11
 - Java Version: 15.0.1
 - Ghidra Version: 10.1.4
 - Ghidra Origin: official GitHub build

**Comment by RootCubed** [comment]
I can confirm that this fixes the provided example, thanks for the fix! Unfortunately, there are still cases where the PCodeOp is not marked as a (calculated) bool. This occurs if the Varnode is marked as a boolean by the user, such as if the parameter to the following function is manually set to be a boolean:
```cpp
int takesBool(bool bVar) {
    if (bVar) return 42;
    return 43;
}
```

In this case, Ghidra outputs:
```cpp
int __cdecl __Z9takesBoolb(bool param_1) {
  int res;
  if (param_1 == false) {
    res = 0x2b;
  } else {
    res = 0x2a;
  }
  return res;
}
```

Should I create a new issue for this or will this one be reopened?

**Comment by homes410** [comment]
Try pull request #3953 though I'm using workaround as described in #2918

**Comment by RootCubed** [comment]
> Try pull request #3953 though I'm using workaround as described in #2918

This issue is not related to `if` statements, it has to do with the decompiler not properly applying user-defined boolean types. Another example where the boolean variable is not used in an `if` statement:
```cpp
bool testfunc2(int a) {
    bool res = false;
    if (a == 5) {
        res = func2(a + 1);
    }
    return !res;
}
```

This is currently decompiled as (after setting `res` to be of type `bool`, whereas Ghidra originally marked it as `byte`):
```cpp
bool __cdecl testfunc2(int a) {
  bool res;
  
  res = false;
  if (a == 5) {
    res = func2(6);
  }
  return (bool)(res ^ 1);
}
```

Notice that in the final statement, Ghidra was unable to apply the boolean rules and instead produces `(bool)(res ^ 1)`.

**Comment by ryanmkurtz** [comment]
> Should I create a new issue for this or will this one be reopened?

@RootCubed Would you mind making a new ticket?  We are working on the other cases you brought up but the fix is independent of this issue.
