### ISSUE TITLE
 PowerPC VLE Floating-Point support

### ISSUE THREAD

**Issue by arkup** [NationalSecurityAgency/ghidra#434]
**Describe the bug**
Hi, would be great if you implement PowerPC VLE floating-point instructions support. Seems only IDA, objdump can disasm the FPU instructions.

**To Reproduce**

Create a file with the data ```10 60 02 D1 13 a3 02 c9 ``` open as PowerPC VLE
```
Language ID:	PowerPC:BE:64:VLEALT-32addr (1.5)
Processor:	PowerPC
Endian:	Big
Address Size:	32
```

**Expected behavior**

```
10 60 02 D1      efscfsi   r3, r0
13 a3 02 c9 	 efsdiv  r29,r3,r0
```

**Environment:**
 - Ghidra Version: [9.0.2]

**Comment by mumbel** [comment]
These look like bugs in Scalar_SPFP.sinc

Change OP=4 to 1 in `efscfsi`
Change OP=4 to 9 in `efsdiv`

**Comment by ghidra1** [comment]
"OP" is a 6-bit field so the existing patterns are correct.

See comments at end of ppc_64_isa_altivec_vle_be.slaspec

Unfortunately Ghidra does not separate all the valid combinations of PowerPC feature sets (EVX vs. Altivec).  The presence of Altivec support which is enabled in this variant by default precludes the presence of EVX.  We already have 19 variants of PPC, many more variants would be required to handle the various combinations not yet.

**Comment by arkup** [comment]
> You can try un-commenting the EVX support and comment-out the Altivec include. Restart Ghidra and try again.

exactly right, works now thanks @ghidra1 !
