### ISSUE TITLE
iOS16/macOS13 changed the dyld_shared_cache format again

### ISSUE THREAD

**Issue by blacktop** [NationalSecurityAgency/ghidra#4346]
Hello!

There were some minor-ish changes to the shared_cache in iOS16.  There is a NEW stub-island variant.  I believe you can detect this new version as a `cacheType`=2 (from the header)  

As a nicety, they have added the sub_cache extension to the sub_cache_entry structure so you can know after parsing the "primary" cache file all of it's sub_cache file names.

The `/usr/lib/dyld` binary has been moved into the cache and I believe they are re-using the accerlatorInfoAddr and accleratorInfoSize fields from the header to now be the dyldTextAddr and addr to the `_dyld_start` func.

The stubs have all been moved into sub_caches (no longer inside the dylibs themselves) these stub-subcaches can be identified by their size (~KBs), they will only contain a `_TEXT` mapping and after the header/mapping etc there will be no MachO headers it will just be stubs ASM.  I'm not sure if the stub_island sub_caches come right after the subcache with the dylibs that need them yet so you might have to "map" all the islands in order for the branch-to-stub symbols to resolve.

If you have ANY other question please don't hesitate to ask and I'll dig into it with you.

**Comment by blacktop** [comment]
@ryanmkurtz

**Comment by ryanmkurtz** [comment]
Thanks for the heads up.  I am trying to enable our Objective-C analyzer on the dyld_shared_cache and have been running into issues so I've been poking around Apple's open source repos and I stumbled upon the new headers.  I can't download the new iOS16 sample yet though for testing.

So are they officially calling the .1, .2, etc files "sub-caches?"

**Comment by blacktop** [comment]
they are actually now: .01, .02 .... .dylddata, .dydlinkedit, ... .42 😬 

There was a gotcha with objc in iOS15 that I figured out by looking at llvm's lldb code, there are new version 16 of the objc optimization structure - https://github.com/blacktop/ipsw/blob/master/pkg/dyld/objc.go#L63 which will get you the `RelativeMethodSelectorBaseAddressCacheOffset` that you need to add to each selector addr https://github.com/blacktop/ipsw/blob/01573ab3fe8c14b6951abf97fec20b9f93003f2c/pkg/dyld/image.go#L321

**Comment by ryanmkurtz** [comment]
Thanks for the tip!  I think you should write less Go, and more Java 😬

**Comment by ryanmkurtz** [comment]
The new base `dyld_shared_cache` and `kernelcache` files should now be loadable into Ghidra.  

You can also import individual dylib's from Ghidra's filesystem interface, but the same limitations that existed in iOS15 still apply (huge files, missing objc info, unfixed chained pointers, etc).  Work still needs to be done in this area.
