### ISSUE TITLE
Headless via Python: Deactivating large amount of analysis options always has some left activated

### ISSUE THREAD

**Issue by RedOctober45** [NationalSecurityAgency/ghidra#4348]
**Describe the bug**
I am running Ghidra in headless mode and using a Python prescript to deactivate all but 4 analysis options.  However, the following 5 are always turned on even when I set (and confirm) they are set to "false".  Even if I programmatically set every option to "false" these are still run:
- Call-Fixup Installer
- Function Start Search 
- Shared Return Calls
- Stack
- X86 Function Callee Purge

If I open the project in the GUI, I can see everything is not checked in the analysis options, or off, as expected.  If I try to only turn off one or a few of these options above (everything else default) then they are turned off as expected.  I tried both the setAnalysisOptions() and setAnalysisOption() API.

This is the simple Python code I used in my prescript to attempt to turn them all off as a test to verify nothing should be run:

```
analysis_opts = getCurrentAnalysisOptionsAndValues(currentProgram)

for key,value in analysis_opts.items():
    if "true" in analysis_opts[key]:
        analysis_opts.update({key: "false"})

setAnalysisOptions(currentProgram, analysis_opts)
```

If run getCurrentAnalysisOptionsAndValues() I can verify they are all set to "false" after I run this code.  However, the analysis still runs those 5 above.

**Environment:**
 - OS: Windows 10
 - Java Version: JDK - 17.0.2, JRE - 1.8.0_331
 - Ghidra Version: 10.1.4
 - Ghidra Origin: official release

**Comment by ryanmkurtz** [comment]
I'm having trouble reproducing this.  I am running headless in debug mode with a breakpoint at the start of each of those analyzers you've listed.  If i run your prescript no breakpoints hit, and if i comment out the part of your script that sets everything to false, the breakpoints hit.  Maybe I need your binary?

**Comment by RedOctober45** [comment]
> I'm having trouble reproducing this. I am running headless in debug mode with a breakpoint at the start of each of those analyzers you've listed. If i run your prescript no breakpoints hit, and if i comment out the part of your script that sets everything to false, the breakpoints hit. Maybe I need your binary?

I did some more investigation and I think it is relating to other code I am doing in the prescript.  I am essentially doing the exact same thing as the Ghidra built-in script "ImportSymbolsScript.py" to import my gcc symbols.  I made a standalone version to not do the GUI part and pass in what I needed as parameters, however, other than the GUI it is exactly the same.  But it seems like this code is triggering some extra analysis?  If I comment out this code and only disable the analysis then nothing runs as expected.

Also, I noticed if I run the original symbol import script above from within the GUI instead of headless then it looks like it does some extra things other than just setting names to addresses from the table.

**Comment by ryanmkurtz** [comment]
@RedOctober45 Did you ever get this sorted out?  Can we close this ticket?

**Comment by bdemick** [comment]
Something I've noticed just recently that while `createFunction` _does_ trigger _disassembly_ of the functions created, it _does not_ seem to trigger full auto-analysis. I have a preScript that is based on this API and is run with `-noanalysis`. 

However, when you reopen the database, you'll be prompted to run auto-analysis, even though the functions that symbols were created for have had initial disassembly done. I haven't tested this, but if you only want the labels added and not trigger the initial function disassembly that happens, maybe switching out the `createFunction` call for `createLabel` will have the desired effect.

**Comment by RedOctober45** [comment]
> @RedOctober45 Did you ever get this sorted out? Can we close this ticket?

Yes, thank you
