### ISSUE TITLE
[GUI] how to display a list with python script

### ISSUE THREAD

**Issue by kamou** [NationalSecurityAgency/ghidra#435]
Hello !

I'm trying to create a window displaying a list a bit like the `show`  function, but I want to be able to list pairs of string/hex value.

And I can't figure out how to do it, I tryed with `show` but it does not seem like it's possible.

Is there any way to do this in python ?

**Comment by dragonmacher** [comment]
For more advanced showing of desired items from a GhidraScript, see the method I reference below.  It allows you to control the type of object being displayed, as well as optionally adding columns to the table displayed.   It also allows for you to provide a button in the dialog that can execute a user-defined action on the items  currently selected in the table.

```
	/**
	 * Creates a TableChooserDialog that allows the script to display a list of addresses (and
	 * associated column data) in a table and also provides the capability to execute an
	 * action from a selection in the table.
	 * <p>
	 * This method is unavailable in headless mode.
	 * 
	 * @param title the title of the dialog
	 * @param executor the TableChooserExecuter to be used to apply operations on table entries.
	 * @return a new TableChooserDialog.
	 * @throws ImproperUseException if this method is run in headless mode
	 */
	public TableChooserDialog createTableChooserDialog(String title, TableChooserExecutor executor)
			throws ImproperUseException {

		return createTableChooserDialog(title, executor, false);
	}
```

**Comment by kamou** [comment]
Exactly what I needed, thanks !
