### ISSUE TITLE
CParser incorrectly parses anonymous function pointer argument

### ISSUE THREAD

**Issue by nneonneo** [NationalSecurityAgency/ghidra#4351]
**Describe the bug**
The C header import (CParser) incorrectly parses a declaration like `void f(void (*)(void))` ("function (pointer to function (void) returning void) returning void") as `void f(void *)` ("function (pointer to void) returning void").

**To Reproduce**
1. Create a `.h` file with the following content: `void takefunc(void (*)(void));`
2. Select File -> Parse C Source..., clear the list, and add the `.h` file
3. Parse the `.h` file. It should show success.
4. Look or edit the `takefunc` data type.

**Expected behavior**
The function's datatype should be `void takefunc(void (*)(void))`, or at least something like `void takefunc(_func *)`.

Instead, the function is shown as `void takefunc(void * )`.

**Environment (please complete the following information):**
 - OS: macOS 12.3.1
 - Java Version: 11.0.2
 - Ghidra Version: 10.1.4
 - Ghidra Origin: official GitHub distro

**Additional context**
The parser in the "Edit Function Signature" window gets confused by syntax like this too, although that's less surprising since it doesn't seem like it was designed to parse arbitrary C syntax.

The parser works correctly if a parameter name is supplied, e.g. `void takefunc(void (*arg)(void))`.

**Comment by emteere** [comment]
Verified this is an issue.  Will take a look at fixing it.
