### ISSUE TITLE
Exception reading .bss

### ISSUE THREAD

**Issue by lautalom** [NationalSecurityAgency/ghidra#4352]
**Description**
When reading bytes from .bss segment I get a Memory Access exception in a toy binary I am using

**To Reproduce**
1. Compile (using gcc version 12.1.0 just in case)
```c
#include <stdio.h>
#include <stdint.h>

const char pepe[] = { '\x3b', '\xf6', '\x82', '\0'};

int main() {
    printf("%s\n", pepe);
    return 0;
}
```
2. Import the executable in ghidra. Run in Python interpreter
```python
blocks = currentProgram.getMemory().getBlocks()
for b in blocks:
     	if b.getName() == '.bss':
            print(getBytes(b.getStart(),b.getSize()))
```
You may exclude the if clause to see expected behaviour

**Attachments**
```
Traceback (most recent call last):
  File "python", line 2, in <module>
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1396)
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1365)
	at ghidra.program.flatapi.FlatProgramAPI.getBytes(FlatProgramAPI.java:1901)
	at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
ghidra.program.model.mem.MemoryAccessException: ghidra.program.model.mem.MemoryAccessException: Unable to read bytes at ram:00104030
```

**Environment (please complete the following information):**
 - OS: Linux 5.15.41-1-MANJARO
 - openjdk version "11.0.15"
 - Ghidra Version: 10.1.4
 - Ghidra Origin: official GitHub distro

**Comment by bdemick** [comment]
In the ELF parlance, you generally want to look in `.rodata` or `.data` for initialized data. `.bss` is typically zeroed out when the executable is run, and doesn't contain any actual data in a compiled binary. I think what you're experiencing is the expected behavior.

**Comment by dgutson** [comment]
@bdemick is crashing with an exception an expected behavior?

**Comment by dev747368** [comment]
@dgutson - to expand what bdemick said, .bss isn't just zero'd out, its uninitialized, and all reads will get an exception.

Also, an exception isn't a crash... in your case its just an uncaught exception.  Exceptions happen all the time and the api of the methods you are calling need to consulted to determine what might happen and how to handle them.

**Comment by dgutson** [comment]
My bss (brain started by symbol) failed. I thought that the initial values of the global and static variables were there, but I see that it is only to tell the loader how much to allocate for uninitialized globals, meaning that other than its header, it is unreadable.
@lautalom feel free to close this and just skip the .bss during your iteration of content reading. Just take into account the size only.
