### ISSUE TITLE
Add a function that allows you to get the "source" or "destination" operand

### ISSUE THREAD

**Issue by alex-bellon** [NationalSecurityAgency/ghidra#4357]
**Is your feature request related to a problem? Please describe.**
I am trying to write a Ghidra script where this function would be very useful to have, and as far as I have seen there isn't a function that will do this. Currently I am just using `getOpObjects()` assuming for 2-operand instructions that the first operand is the source and the second is the destination (this is for M68000), but it would be nice to have a more robust function that could handle possible edge cases that I am not aware of. Additionally, there is a separate issue for M68000 where some 2-operand instructions are being interpreted as having 4 operands, which means my current workaround breaks in that case. 

**Describe the solution you'd like**
Two functions that would allow you to get the "source" and "destination" operand objects. I'm not sure how this would work with instructions that use 1 (maybe both return the same thing) or >2 operands. 

**Describe alternatives you've considered**
As mentioned above, I'm just assuming that for 2-operand instructions in M68000, that left is source and right is destination, but I'm sure there are cases where this won't work and I will run into issues.

**Additional context**
N/A

**Comment by astrelsky** [comment]
I believe you are looking for `getInputObjects` and `getResultObjects`

**Comment by alex-bellon** [comment]
lol, completely missed those functions. Thank you!
