### ISSUE TITLE
UI elements produced by GhidraScripts close when script manager is closed

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4363]
**Describe the bug**
UI elements produced by scripts e.g. ``ShowConstantUse.java`` and ``YaraGhidraGUIScript.java`` will close if the script was invoked from the script manager and the script manager was then closed. This necessitates the hotkeying of such scripts, which is a minor annoyance.

**To Reproduce**
1. Make a selection
2. Run ``YaraGhidraGUIScript.java`` from the script manager
3. Close the script manager. The panel brought up by the script closes as well.

**Expected behavior**
Panel should not close when script manager closes

**Environment (please complete the following information):**
Ghidra master c6cb8a0

**Comment by astrelsky** [comment]
This is quite annoying. As a work around I always run it, close the script manager window and then use the button to re-run the last script.

**Comment by dragonmacher** [comment]
We are looking into fixing this. 

The master branch has a feature created to allow users to bypass this behavior.  You use the new Script Quick Launcher to choose and run a script without opening the Script Manager.  The default key binding for the launcher is `Ctrl-Shift-S`.
