### ISSUE TITLE
Ghidra refuses to open projects after Linux login name change

### ISSUE THREAD

**Issue by LunarLambda** [NationalSecurityAgency/ghidra#4364]
**Describe the bug**
After changing my Linux login name, without changing anything else (Groups, UID, password), Ghidra refuses to open my local projects because they are "owned by \<old username\>"

**To Reproduce**
1. Create local project
2. Change Linux user login name (through usermod or /etc/passwd / shadow)
3. Restart user session, try to open project

**Expected behavior**
Ghidra recognizes that the UID has not changed, and allows me to open my project.

**Environment**
 - OS: Arch Linux
 - Java Version: openjdk 18.0.1,1
 - Ghidra Version: 10.1.4
 - Ghidra Origin: Arch Linux Repositories

**Comment by dev747368** [comment]
See issue #2229

**Comment by ghidra1** [comment]
This is working as intended and requires a manual change of the owner information within the project data file.  See issue #2229 as mentioned above for resolution.
