### ISSUE TITLE
Broken pcode injection configuration file for x86-16 applications

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4380]
**Describe the bug**
In recent changes to `inject_ghidra.cc` the method `void ExecutablePcodeGhidra::restoreXml(const Element *el)` has been replaced with `void ExecutablePcodeGhidra::decode(Decoder &decoder)` to give different pcode injection strategies.  However the `x86-16.pspec` hasn't been updated and is causing the decompiler to fail to start!

The part of `x86-16.pspec` that I believe is breaking the decompiler is the `<pcode>` tag below:
```
. . .
  <segmentop space="ram" userop="segment" farpointer="yes">
    <pcode>
      <input name="base" size="2"/>
      <input name="inner" size="2"/>
      <output name="res" size="4"/>
      <body><![CDATA[
        res = (zext(base) << 16) + zext(inner);
      ]]></body>
    </pcode>
    <constresolve>
      <register name="DS"/>
    </constresolve>
  </segmentop>
. . .
```

**To Reproduce**
1. Load a 16-bit app that requires the x86-16.cspec
2. Try to decompile it
3. See error

**Expected behavior**
When changes like this are made all appropriate configuration files should be updated.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.3.1
 - Ghidra Version: [e.g. 10.2-DEV
 - Ghidra Origin: locally built commit a59c42dd960d1c86e6ad2fbf57c18cef505eca33

**Comment by Wall-AF** [comment]
Looks like there could be deeper issues as XML validation is also problematic from within class `SleighLanguageValidator`.

**Comment by caheckman** [comment]
Yes. Exactly right.  `elemId != ELEM_PCODE` is missing from the `if` statement.

**Comment by Wall-AF** [comment]
Does this change need adding to method `void ExecutablePcodeSleigh::decode(Decoder &decoder)` in `inject_sleigh.cc` or is that different?
