### ISSUE TITLE
SuperH : decompiler incorrectly increments offset for `mov.b r0, @(#imm8, gbr)`

### ISSUE THREAD

**Issue by fenugrec** [NationalSecurityAgency/ghidra#4388]
**Describe the bug**
Decompiler misses a `var = var + 1` pattern : it increments the offset instead of the written value !

**To Reproduce**
1. Load the attached dump with mostly default options. Language is SuperH SH-2A
1. analyze
1. go to address 0x13686

**Screenshots**
disasm clearly shows "cnt_82e5" being incremented by one
```
        00013686 c4 c5           mov.b      @(0xc5,gbr),r0=>cnt_82e5                         = ??
        00013688 70 01           add        0x1,r0
        0001368a a0 07           bra        LAB_0001369c
        0001368c c0 c5           _mov.b     r0,@(0xc5,gbr=>cnt_82e5)                         = ??
```

Decompiler :

 ```
          *(undefined *)((int)puVar3 + 0xc5) = 0x0;
          *(undefined *)((int)puVar3 + 0xc6) = 0x0;
```

**Expected behavior**
 ```
          *(undefined *)((int)puVar3 + 0xc5) += 1;
```
or better, (related to #4387 
 ```
          cnt_82e5 += 1;
```

**Attachments**
[6Z68A.zip](https://github.com/NationalSecurityAgency/ghidra/files/8996477/6Z68A.zip)

**Environment (please complete the following information):**
 - OS: linux
 - Java Version: 18.0.1
 - Ghidra Version: 10.1.4
 - Ghidra Origin:  archlinux build

**Comment by mumbel** [comment]
You should double check your RE and make sure the decompiler output matches the disassembly addresses. Not seeing your issue, you posted the initialization C, not the increments which are there.

Selecting the disassembly will highlight the matching decompiler psuedo code

**Comment by fenugrec** [comment]
> not the increments which are there.

You were right. Sometimes the cursor doesn't quite sync perfectly between the disasm an decompiler view... totally missed the later if () block.

Thanks for having a look, sorry for the noise.
