### ISSUE TITLE
How to set a global variable new type (via a Script Java)?

### ISSUE THREAD

**Issue by AnFunctionArray** [NationalSecurityAgency/ghidra#4389]
I have the Address and the type as a string which I want to set (structure name) - however the only setter for DataType I've seen is for Variable which I don't know how to obtain (at all let alone for a global).

**Comment by dev747368** [comment]
If the structure already exists in the data type manager, and all you have is the name, then something like this should help:


```java
DataType mystruct = currentProgram.getDataTypeManager().getDataType("/path/to/mystruct");
Data newDataItem = createData(addr, mystruct);
```

**Comment by AnFunctionArray** [comment]
@dev747368 Thanks this solves my problem
