### ISSUE TITLE
API - How can i add parameter to function using jython?

### ISSUE THREAD

**Issue by dark-lbp** [NationalSecurityAgency/ghidra#439]
Hi, i am trying to add parameter to function using jython api `addParameter` , but don't known how to use it. 

The `addParameter` method need `Variable var` as input, but i can't find jython examples of how to create an Variable object.

**Comment by ryanmkurtz** [comment]
You can find examples of how to use it in Java.  For example, take a look at StringParameterPropagator.java.  The Jython API is identical to the Java API.

**Comment by dark-lbp** [comment]
@ryanmkurtz Thanks, might be it's a noob question, but i still looking for how to create `Variable` object using jython.

**Comment by dark-lbp** [comment]
@ryanmkurtz `ParameterImpl ` works, Thanks!!
```python
param = ParameterImpl("name", CharDataType(), toAddr(0x0), function.getProgram())
function.addParameter(param, SourceType.USER_DEFINED)
param = ParameterImpl("passwd", CharDataType(), toAddr(0x0), function.getProgram())
function.addParameter(param, SourceType.USER_DEFINED)
```
