### ISSUE TITLE
How to combine stack variables into a structure? (Decompiler)

### ISSUE THREAD

**Issue by AnFunctionArray** [NationalSecurityAgency/ghidra#4391]
Even from the GUI.

I tried Shift + [ and retyping (also commit local names) but it didn't budge.

**Comment by Wall-AF** [comment]
Create a datatype and use that as the type of the stack variable.

**Comment by Wall-AF** [comment]
I've found array support troublesome (I'm RE'ing a 16-bit Windows suit).  Try a structure or union.

**Comment by gtackett** [comment]
For some processors at least, using registers to **return** a structure that spans registers also has problems.

(A made-up example: some anonymous function does a division using two 16 bit parameters, quotient in R0 and remainder in R1, and returns results in subregisters, quotient in R1L and remainder in R0H.)
