### ISSUE TITLE
Disassembly of Raw Binary (ARM) not complete.

### ISSUE THREAD

**Issue by kiranravindran90** [NationalSecurityAgency/ghidra#4395]
Following up on a previous question I had asked --> https://github.com/NationalSecurityAgency/ghidra/issues/4147
Sorry for a very delayed follow up, I was caught up with something else.

I had tried as you mentioned in that issue. **AARCH64 : LE : 64 : v8A : default** seemed quite straight forward & tried that, but the result didn't look complete. I could see some functions/instructions it did disassemble well but majority were just "??"

Below is just a snippet of the analyzed Binary. We can see some instructions have been identified while a lot are just "??"

![image](https://user-images.githubusercontent.com/90866692/176594205-693fbba4-e78d-40ab-b22b-e231df0d3706.png)

Want to know the reason for this. Is it something I am not selecting right or the input file is not supported or something?

**Comment by ghidra1** [comment]
Analysis is not guaranteed to discover all instructions and often requires manual or scripted assistance to initiate disassembling specific locations.  Since there is no reference to address 36 this may be such a location.
