### ISSUE TITLE
pcode cbranch relative addressing

### ISSUE THREAD

**Issue by r4dr3fr4d** [NationalSecurityAgency/ghidra#4399]
Some CBRANCH operations seem to encode relatives ram addresses in certain situations (I've seen both forward and backward), while others seem to encode absolute ram addresses.  Is there a way to programmatically tell which way a jump target is encoded?

**Comment by GhidorahRex** [comment]
a way from what perspective? Analyzing the sleigh module, or reading the pcode from a script? You can look at the sleigh module to tell, but it won't be programmatic.

**Comment by r4dr3fr4d** [comment]
using a Python script with pypcode to lift and view the operations.  Some
branch targets seems to be ram[<absolute>] and others seem to be
ram[<relative>], but there's no label or attribute my script can use to
tell them apart.

**Comment by r4dr3fr4d** [comment]
I figured it out....the "relative" addresses were showing up due to me inadvertently translating from a fixed address for every instruction, rather than each instructions' own address.  I saw the (presumably correct/desired) "absolute" addresses in separate scripts where I wasn't mistakenly doing that.
