### ISSUE TITLE
the program's screen is all gray

### ISSUE THREAD

**Issue by Sirqwit** [NationalSecurityAgency/ghidra#44]
the program's screen is all gray except the tips on startup
maybe because i use dwm??

**Comment by Sirqwit** [comment]
Downloads/ghidra_9.0/support/ghidraDebug
Listening for transport dt_socket at address: 18001
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
INFO  Using log config file: file:/home/sam/Downloads/ghidra_9.0/support/debug.log4j.xml  (LoggingInitialization.java:59)
INFO  Using log file: /home/sam/.ghidra/.ghidra-9.0/application.log  (LoggingInitialization.java:60)
INFO  Loading user preferences: /home/sam/.ghidra/.ghidra-9.0/preferences  (Preferences.java:122)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ghidra.framework.GhidraApplicationConfiguration (file:/home/sam/Downloads/ghidra_9.0/Ghidra/Features/Base/lib/Base.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of ghidra.framework.GhidraApplicationConfiguration
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  Class search complete (792 ms)  (ClassSearcher.java:248)
INFO  Initializing SSL Context  (SSLContextInitializer.java:83)
INFO  Initializing Random Number Generator...  (SecureRandomFactory.java:37)
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking  (SecureRandomFactory.java:41)
INFO  Trust manager disabled, cacerts have not been set  (ApplicationTrustManagerFactory.java:95)
INFO  User sam started Ghidra.  (GhidraRun.java:81)
DEBUG Recovery snapshot timer set to 5 minute(s)  (RecoverySnapshotMgrPlugin.java:170)

**Comment by rhaamo** [comment]
> the program's screen is all gray except the tips on startup
> maybe because i use dwm??

I remember having issues like that when I used dwm or awesome, try that : https://wiki.gentoo.org/wiki/Dwm#Blank_.28grey.29_windows_of_Java_applications_.28such_as_netbeans.29

**Comment by huntergregal** [comment]
like rhaamo said it doesn't support certain window managers.

**Comment by Ristovski** [comment]
This can be fixed by running Ghidra like this `_JAVA_AWT_WM_NONREPARENTING=1 ./ghidraRun`

**Comment by Sirqwit** [comment]
thanks

**Comment by arumugamramaswamy** [comment]
Happened with EXWM as well.
Mentioning to help with searches:)

**Comment by haselwarter** [comment]
For the record, the same fix works on Sway.

**Comment by nwolovick** [comment]
For the record, the same fix works on XMonad

**Comment by oskhen** [comment]
For the record, the same fix works on BSPWM.

**Comment by LeCodingWolfie** [comment]
Also for Hyprland :D

**Comment by veil-ctf** [comment]
> This can be fixed by running Ghidra like this `_JAVA_AWT_WM_NONREPARENTING=1 ./ghidraRun`

Works on dwm aswell

**Comment by S31ZUR3** [comment]
is there any permanent way fix this instead of typing this _JAVA_AWT_WM_NONREPARENTING=1?

**Comment by ryanmkurtz** [comment]
> is there any permanent way fix this instead of typing this _JAVA_AWT_WM_NONREPARENTING=1?

You could put `export _JAVA_AWT_WM_NONREPARENTING=1` in either your `~/.bashrc` file (or equivalent) or in your Ghidra installation's `ghidraRun` file so you don't have to type it every time.

**Comment by ryanmkurtz** [comment]
Here's some additional info on this: 

* https://bugs.openjdk.org/browse/JDK-8058197
* https://github.com/openjdk/jdk/blob/a6594794839807d56434d6f28fe3d581fb1e36c0/src/java.desktop/unix/classes/sun/awt/X11/XWM.java#L606-L613
