### ISSUE TITLE
GUI icons not rendering correctly on Ubuntu 22.04

### ISSUE THREAD

**Issue by JSquared-dev** [NationalSecurityAgency/ghidra#4400]
**Describe the bug**
Many GUI icons will sporadically render with the incorrect icon, making GUI navigation more difficult.

**To Reproduce**
1. Create a new Ubuntu 22.04 VM
2. Update all packages to latest
3. Install openjdk 11 and Ghidra
4. Run Ghidra and open any binary in the code browser
5. See some icons will sporadically be incorrect.

**Expected behavior**
The icons to render with the correct images.

**Screenshots**
![IconBugExample1](https://user-images.githubusercontent.com/240331/176776392-dce643fd-9ad8-4ae0-8800-9c66e3879944.PNG)
![IconBugExample2](https://user-images.githubusercontent.com/240331/176776395-1a0ef039-c6f7-4ee5-bc7a-d3f5a1e2dd7f.PNG)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: openjdk version "11.0.15" 2022-04-19
 - Ghidra Version: 10.1.2 to 10.1.4 and latest dev
 - Ghidra Origin: Github and dev build from Github repo

**Additional context**
This appears to be very sporadic and non-deterministic. Some times the GUI will fully refresh upon opening a file and the icons will look fine, but other times it will get stuck with (presumably cached) incorrect icons on buttons and other UI controls.

I've also tried running Ghidra with the latest openjdk-17 packages in Ubuntu 22.04 and it suffers from similar issues.

Some icons will be fixed in certain circumstances. For example, if the Decompiler view title bar buttons render incorrectly when the code browser opens; navigating to a new function, thereby triggering the Decompiler view to update, will typically refresh these icons and they will be fixed. But this does not impact other icons which will stay broken for the duration that ghidra is running.

**Comment by ryanmkurtz** [comment]
Did you change any Ubuntu settings from the default, such as scaling?

**Comment by JSquared-dev** [comment]
I'm using VMWare Workstation, but have also seen this issue in VirtualBox. Both across multiple different devices.

Interestingly, rolling back to 20.04 seems to make the issue disappear, at least in the 10 or so test runs I've done. Haven't got extensive usage to confirm it's completely gone, as it's not always prominent or apparent in the same location each time.

I've not changed any ubuntu settings from defaults. However, I have tested with Workstation's auto size feature enabled and disabled and the issue persists regardless of this setting.

**Comment by emteere** [comment]
There was another user with a similar environment and issue VMWARE using Ubuntu 22.04
They were able to fix the issue by setting **VMARGS=-Dsun.java2d.opengl=true** in the <ghidra>/support/launch.properties file.

Most likely related to VMWare rendering acceleration.

**Comment by aerobinsonIV** [comment]
Thank you so much.

If there's still interest in reproducing, here's my setup:
VMWare Workstation 16 Pro 16.2.5 build-20904516
Windows 11 Pro 23H2 22631.3296 Host
Ubuntu 22.04.4 Guest, pretty much fresh install, containing:
OpenJDK 21.0.2 2024-01-16
Ghidra 11.0.1
