### ISSUE TITLE
C parser fails silently after static_assert

### ISSUE THREAD

**Issue by Tim---** [NationalSecurityAgency/ghidra#4401]
**Describe the bug**
When using `File > Parse C Source...` to parse a header with a `static_assert`, the parsing seems to stop after the assertion.
It doesn't matter whether the condition is true or false, and no errors are written in the `application.log` file.

**To Reproduce**
Parse the following file:
```c
typedef int test_before;
static_assert(1 + 1 == 2);
typedef int test_after;
```
Both typedefs should be added to the type manager, but only `test_before` is added.

---

Parse the following file:
```c
typedef int test_before;
static_assert(1 + 1 != 2);
typedef int test_after;
```
We would expect the parser to either:
- ignore the `static_assert` and parse both types anyway;
- throw an error in the GUI or in the `application.log` file because the assert fails.

However, the parser fails silently, and only imports the first typedef.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: openjdk version "11.0.15" 2022-04-19
 - Ghidra Version: 10.1.4
 - Ghidra Origin: official GitHub distro

**Comment by emteere** [comment]
Duplicated the issue.  WIll add it to the set of upcoming cparser fixes.
The StaticAssert() is currently only accepted within function statements.
Have created a test and changed parser to ensure they can appear in all locations, statements, with/within declarations.

**Comment by emteere** [comment]
closed this as [completed](https://github.com/NationalSecurityAgency/ghidra/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/NationalSecurityAgency/ghidra/commit/e42c1f1f3263e192d5d9042c14f1f25413931aa0
