### ISSUE TITLE
"Install Extensions" add button grayed out

### ISSUE THREAD

**Issue by mfthomps** [NationalSecurityAgency/ghidra#4404]
After a fresh build of the latest ghidra  10.2 - DEVELOPMENT (master) the add button on the "Install Extensions" dialog is grayed out, and the checkboxes on the existing extensions cannot be altered.  It is built on Ubuntu 20 with java 11.0.15 and otherwise seems to work fine.  I've previously built ghidra on an older Ubuntu and did not encounter this.  The application log reports no errors.

**Comment by ryanmkurtz** [comment]
I cannot reproduce this on a fresh 10.2-DEV build.  The only way that button can be disabled is if Ghidra detected that's it's running in development mode, or single-jar mode.  Are you launching Ghidra with the standard `ghidraRun` script?

**Comment by astrelsky** [comment]
Were the existing extensions built for a different version of Ghidra? ie not 10.2_DEV. If so, I think this is the expected behavior.

**Comment by mfthomps** [comment]
The fresh build has no extensions other than those distributed with Ghidra.
I start Ghidra with: Ghidra/RuntimeScripts/Linux/ghidraRun
What does "running in development mode" mean, and how can I test that?  I
run from the git repo, just as I do on my other dev environment.

**Comment by mfthomps** [comment]
I went back and rebuilt my old dev environment and now it also has a grayed
out add button.
So I guess "development mode" means running from a repo?  And extensions
are only intended for use in non-development installations?  I sure hope
not.
I don't understand how I was previously able to successfully work with
extensions in that development environment.

**Comment by ryanmkurtz** [comment]
When we refer to "a build" we are talking about the output of `gradle buildGhidra`, which produces a zip file to `build/dist/`.  The "build" is the extraction of this zip file.  In it, you will find a `ghidraRun` script in the top-level directory, and all of the Ghidra modules will have jar files in their `lib/` directories.

When we refer to "development mode" we are talking about the running from the git repo, where Ghidra is typically expected to be compiled by Eclipse.  When in this mode, you can launch Ghidra either from Eclipse, or directly via the `ghidraRun` scripts in the `Ghidra/RuntimeScripts/` directory.

With the way extensions currently work, the Add button will only be active in a build, not in development mode.  The reason behind this is that when running from a build, Ghidra looks for modules/extensions in jar form, and when in development mode, it looks for them in class file form.

**Comment by mfthomps** [comment]
Thank you for that explanation.  Now I understand how my old dev environment had a working  Add button, it had class files rather than just jars.
