### ISSUE TITLE
Tricore: decompiler low-level error

### ISSUE THREAD

**Issue by bdcht** [NationalSecurityAgency/ghidra#4409]
When analyzing a tricore binary (using lang tricore:LE:32:default), the decompiler now almost always fails with a "Low-level Error" message about pcode snippet "saveCallerState" and/or "restoreCallerState".

To reproduce, analyze any tricore binary that has a 'ret' instruction and go to the decompiler window for this function.

hint:
This seems to be associated to recent changes that have touch
Ghidra/Features/Decompiler/src/decompile/cpp/inject_ghidra.cc
most notably since:
git show d8c10bf22977b387d0729f374cd19dbdca1be911 -- Features/Decompiler/src/decompile/cpp/inject_ghidra.cc

 - OS: Linux
 - Java Version: 11.0.15
 - Ghidra Version: 10.2 BUILD DEV 2022 Jul 04 (commit f974b9d)
 - Ghidra Origin: official GitHub repo

**Comment by mumbel** [comment]
```
index d37931e5c..882eb7676 100644
--- a/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/app/plugin/processors/sleigh/SleighParserContext.java
+++ b/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/app/plugin/processors/sleigh/SleighParserContext.java
@@ -86,6 +86,7 @@ public class SleighParserContext implements ParserContext {
                nextInstrAddr = nAddr;
                refAddr = rAddr;
                destAddr = dAddr;
+               this.handleMap = new HashMap<>();
        }
 
        /**
```
not sure if this is the correct fix or not, but does let decompiler show output

**Comment by mumbel** [comment]
Oh already had a PR open #4403
