### ISSUE TITLE
Mt2iq terminal bot cracked

### ISSUE THREAD

**Issue by robertopher** [NationalSecurityAgency/ghidra#441]
Hi Devs

Anybody with a cracked version of Mt2iq terminal bot

https://mt2iq.com/order

Please

**Comment by robertopher** [comment]
I will appreciate if anyone can help me out with this solution

**Comment by ryanmkurtz** [comment]
Sorry, we can't help you with this!

**Comment by ryanmkurtz** [comment]
If you wish to report a bug, request an enhancement, or ask a detailed question about something that is causing you problems in Ghidra, feel free to create an issue!

**Comment by robertopher** [comment]
What is GHIDRA,❓
