### ISSUE TITLE
Lots of nops cause an error

### ISSUE THREAD

**Issue by justanotheranonymoususer** [NationalSecurityAgency/ghidra#4425]
**Describe the bug**
See the screenshot:
![image](https://user-images.githubusercontent.com/5781692/178036583-6d63c798-587a-480c-905e-e107d811ac6d.png)

**To Reproduce**
1. Patch a part of a binary to have lots of nops
2. Load with ghidra
3. See error

**Expected behavior**
No error

**Screenshots**
See above

**Attachments**

**Environment (please complete the following information):**
 - OS: Win10
 - Java Version: 11.0.7
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official GitHub distro

**Additional context**

**Comment by mumbel** [comment]
this looks to be working as intended.  out of control disassembly is not a good thing, tons of repeated bytes typically are not valid instruction bytes, so user interaction should be required for cases like this.
