### ISSUE TITLE
How to determine if a function has been manually edited?

### ISSUE THREAD

**Issue by alex-bellon** [NationalSecurityAgency/ghidra#4428]
I am currently writing a Ghidra script that will go through functions and mark certain registers as containing parameters for the function. However, I don't want to apply this change to functions where someone has already manually messed with the parameters. 

Right now I was thinking of passing the something with [lower `SourceType` precendence](https://github.com/NationalSecurityAgency/ghidra/blob/b8425e804d5b1c4c8d9d739827ed5260a9c4c9d1/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/symbol/SourceType.java#L22-L29) than `USER_DEFINED` into my call to [`replaceParameters()`](https://github.com/NationalSecurityAgency/ghidra/blob/b8425e804d5b1c4c8d9d739827ed5260a9c4c9d1/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/listing/Function.java#L379), but I looked through the source for `replaceParameters()` and I'm not sure that would work.

Is there a property or function that tells you if a function (or parameters) has been manually changed?

**Comment by dev747368** [comment]
if you are assigning custom storage for parameters to a function, and you don't want to step on functions with parameters that also were assigned custom storage, maybe you could just check the ```Function.hasCustomVariableStorage()``` flag.

If its more complicated than that, SourceType would be another option.  I'm not sure what issue you ran into.  Are you expecting ```replaceParameters()``` to not update if the SourceType precedence isn't met?  (I'm pretty sure you have to manually check it before trying to update the function)

**Comment by alex-bellon** [comment]
Yes, I was expecting `replaceParameters` to not update if the SourceType parameter was a lower precedence than the existing function. I may have misunderstood how it worked from just looking at the source code, though. 

How would you get the SourceType value for the function? Would `func.getSignatureSource()` be enough?

**Comment by dev747368** [comment]
yes, ```getSignatureSource()``` is your best bet.

**Comment by alex-bellon** [comment]
Thanks for your help!
