### ISSUE TITLE
Loop not recognized by the decompiler.

### ISSUE THREAD

**Issue by mzr** [NationalSecurityAgency/ghidra#443]
**Describe the bug**
Simple loop is ignored in the decompiler view.

**To Reproduce**
1. Download [the binary](https://hack.cert.pl/challenge/drain-waters-of-styx-harder) (may sound fishy but it's just a ctf-task binary).
2. Load it into CodeBrowser tool.
3. Do the default analyses.
4. Go to `FUN_00400c1f` aka main.
5. There should be a loop between `LAB_00400c50` and `LAB_00400cd3` in the decompiler view, but decompiler just ignores it, and show no loop whatsoever.

**Expected behavior**
The decompiler should recognize this loop.

**Environment (please complete the following information):**
 - OS: Manjaro 18.0.4 Illyria
-  Kernel: x86_64 Linux 5.0.5-1-MANJARO
 - Java Version: 11.0.3
 - Ghidra Version: 9.0.2

**Comment by 0x6d696368** [comment]
The decompiler thinks this is dead code ... which as far as I can tell it isn't (unless there is some call stack manipulation going on or something).

Workaround:
Edit -> Tool options... -> Decompiler -> Analysis -> [ ] Eliminate dead code

**Comment by caheckman** [comment]
Decompiler doesn't recognize some forms of switches that exit to themselves (in a loop). Working towards a fix.
