### ISSUE TITLE
How To Update this.currentAddress During Script Execution

### ISSUE THREAD

**Issue by H0r53** [NationalSecurityAgency/ghidra#4434]
I have an instruction address trace and I'd like to visualize it with Ghidra. I'm able to update the address via `this.currentAddress = this.currentAddress.getAddress(address);` (which feels like the improper way to update the cursor location), but when I update the address multiple times within a script the cursor is only ever updated to the final address at the end of the script execution. This makes it where I'm unable to watch the instruction trace at all.

Here is my script.

```java
public class TraceGoTo extends GhidraScript {

	@Override
	public void run() throws Exception {
		String addresses[] = new String[] {"0x10a094", "0x10a098", "0x10a09c"};
		
		System.out.println("TraceGoTo!");
		for (String address : addresses) {
			setAddress(address);
			TimeUnit.SECONDS.sleep(1);
		}
		
	}
	
	public void setAddress(String address) throws AddressFormatException
	{
		System.out.println("Setting address to " + address);
		this.currentAddress = this.currentAddress.getAddress(address);	
	}
}
```

1) What is the proper way to set `this.currentAddress`?
2) How can I get ghidra to render the updated address during the script execution (change the current cursor location)
3) Better yet, how could I make a dialogue of sorts, where I could just click a button for "Next Address" and then update `this.currentAddress`? This would actually suit my needs and seems like the ideal approach anyways.

**Comment by H0r53** [comment]
I came up with the following example using `show` which is very close to what I need.

```java
public class TraceGoTo extends GhidraScript {
        private static String addresses[] = new String[] {"0x10a094", "0x10a098", "0x10a09c"};

	public void run() throws Exception {
		
		System.out.println("TraceGoTo!");
		
		AddressSet addressSet = new AddressSet();
		
		for (String address : TraceGoTo.addresses) {
			addressSet.add(this.currentAddress.getAddress(address));
		}
		show("Trace", addressSet);
		
	}
	
	public void setAddress(String address) throws AddressFormatException
	{
		System.out.println("Setting address to " + address);
		this.currentAddress = this.currentAddress.getAddress(address);	
	}
}
```
The problem here is AddressSet appears to sort the address entries, which is understandable behavior for a Set but this entirely defeats the purpose of what I'm going for, keeping track of a specific address sequence.

Is there a way to use the `show` dialogue with a list of addresses that isn't sorted?

**Comment by H0r53** [comment]
I have the following and it seems to be working!
```java
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;

public class TraceGoTo extends GhidraScript {

	private static String addresses[] = new String[] {"0x10a094", "0x10a098", "0x10a09c", "0x10a0a0", ...};
	@Override
	public void run() throws Exception {
		
		System.out.println("TraceGoTo!");
		System.out.println(this.currentAddress);
		
		Address addrs[] = new Address[1000];
		for (int i = 0; i < 1000 && i < addresses.length; i++) {
			addrs[i] = this.currentAddress.getAddress(addresses[i]);
		}

		show(addrs);		
	}
}
```
Any advice on optimizing this? It feels very hacky.

**Comment by dev747368** [comment]
re: addresses, use ```toAddr(String)``` or ```toAddr(long)```

re: dialog.  I haven't played with the table convenience methods much, but using a dialog with a table does sound like a more user-friendly way to go.

**Comment by H0r53** [comment]
Thank you @dev747368 ! That is much better than what I was doing.

Regarding my most recent solution. It does work but the addresses are still sorted, which causes big issues when dealing with code that jumps back and forth between higher and lower addresses... Can anyone please help identify a way to get Ghidra's `show` dialog (or similar) to list the provided addresses in the order they are given?

**Comment by H0r53** [comment]
Closing this to report the address ordering of `show` in a new issue.

**Comment by H0r53** [comment]
I find it difficult to believe a model for something such as this doesn't already exist, or that you can't just tell the table to not automatically sort the location column.

**Comment by H0r53** [comment]
@dev747368 are you sure that this can be achieved with creating a new TableModel? I've been digging deeper into this issue and commenting my findings in https://github.com/NationalSecurityAgency/ghidra/issues/4435. 

By the way, I'm pretty certain my code should be using `AddressArrayTableModel` and not `AddressSetTableModel`. I would understand the Set version automatically sorting results but not the Array version.

**Comment by dev747368** [comment]
Creating TableModels for tables is just one of the those things you have to get comfortable with when you venture outside the easy, predefined helper methods published in GhidraScript / FlatProgramAPI.

You have the full might and power of java and the internal classes defined in Ghidra to create anything you want.  It just takes a bit of work.
