### ISSUE TITLE
show Dialog Changes Order of Provided Addresses

### ISSUE THREAD

**Issue by H0r53** [NationalSecurityAgency/ghidra#4435]
I have an instruction trace and I'm particularly interested in generating a Ghidra dialogue that lists each address I give it **in the order given**. I managed to nearly accomplish this with the `show` dialog. However, the address array I give the `show` function is implicitly sorted by Ghidra and that is not the behavior I want.

Here is a simple example. The addresses provided are arbitrary, the point is `0x10a09c` is the second item in the array and `0x10a098` is the third item in the array. You can replace these addresses with any valid addresses for your binary, just make sure they are not sorted.

```java
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;

public class TraceGoTo extends GhidraScript {

	private static String addresses[] = new String[] {"0x10a094", "0x10a09c", "0x10a098"};
			
	public void run() throws Exception {
		Address addrs[] = new Address[3];
		for (int i = 0; i < 1000 && i < addresses.length; i++) {
			addrs[i] = toAddr(addresses[i]);
		}
		show(addrs);		
	}
}
```

The `show` dialog should display a table with the addresses given in the exact order they are given. It should not automatically sort the results. I believe what is happening is the table is automatically sorting by address, which again is not what I want.

**Comment by H0r53** [comment]
I've tracked this down to `[docking.widgets.table.threaded.ThreadedTableModel](https://ghidra.re/ghidra_docs/api/docking/widgets/table/threaded/ThreadedTableModel.html)<ROW_TYPE,​[Program](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Program.html)>` and children where `Comparator<ROW_OBJECT>` is defined for a few routines. I would hate to have to modify Ghidra's internals at this level just to provide the simple ability of generating a table dialog that doesn't automatically sort addresses. This should be a feature as simple as not automatically sorting tables on load.

**Comment by H0r53** [comment]
Interface DynamicTableColumn<ROW_TYPE,​COLUMN_TYPE,​DATA_SOURCE> requires java.util.Comparator<[COLUMN_TYPE](https://ghidra.re/ghidra_docs/api/docking/widgets/table/DynamicTableColumn.html)> getComparator() for implementing classes. I'm guessing the class in my case is `AddressTableColumn`. That would mean the `getComparator` method comes from `AbstractDynamicTableColumn`. 

However, I looked at the source for `AbstractDynamicTableColumn` and it looks like `getComparator()` returns `null`. This is crazy. Is there really no way to tell Ghidra to create a table of addresses without automatically sorting it?

**Comment by dragonmacher** [comment]
> This is crazy.

There are much crazier things than this.

> Is there really no way to tell Ghidra to create a table of addresses without automatically sorting it? 

There are many ways to do this, but not via scripting.

>  It should not automatically sort the results. 

That depends on you use case.  It used to be that all tables were always sorted.   In those ancient times we would have simply added an ordinal column to go a long with the addresses, with the sort being on the ordinal column.  We added the ability to have tables be unsorted some years back.  The code below uses this ability.


Below is a script that shows a table with unsorted addresses with relatively few lines of code, taken from what the script code does internally.

Note: there are no 'Next' and 'Previous' buttons in this example.  However, you can simply use the arrow keys in the table to accomplish the equivalent behavior.   You could certainly build a more complicated custom dialog if you really wanted such buttons.

```
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

import docking.widgets.table.TableSortState;
import ghidra.app.plugin.core.table.TableComponentProvider;
import ghidra.app.script.GhidraScript;
import ghidra.app.util.query.TableService;
import ghidra.framework.plugintool.PluginTool;
import ghidra.program.model.address.Address;
import ghidra.util.Swing;
import ghidra.util.table.AddressArrayTableModel;

public class ShowAddressesScript extends GhidraScript {

	@Override
	public void run() throws Exception {

		PluginTool tool = state.getTool();
		TableService tableService = tool.getService(TableService.class);

		List<Address> list = new ArrayList<>();
		list.add(toAddr("00403510"));
		list.add(toAddr("00403530"));
		list.add(toAddr("00403590"));

		Address[] addresses = list.toArray(Address[]::new);

		Swing.runNow(() -> {
			AddressArrayTableModel model = new AddressArrayTableModel(getScriptName(),
				state.getTool(), currentProgram, null);
			model.setTableSortState(TableSortState.createUnsortedSortState());
			model.setAddresses(addresses);

			TableComponentProvider<Address> tableProvider =
				tableService.showTableWithMarkers("Unsorted Addresses", "GhidraScript", model,
					Color.GREEN, null, "Script Results", null);
			tableProvider.installRemoveItemsAction();
		});

	}
}
```

**Comment by H0r53** [comment]
@dragonmacher Thank you very much for your response and suggestion. Unfortunately, the code you provided is not preventing the table from sorting by Location (address) automatically. In your example the addresses are added to `list` in order. If you swap the `list.add` calls for `"00403530"` and `"00403590"` you can test for yourself and see.

Here is my Ghidra build information in case my version is outdated.
```
Version 9.2.3
Build PUBLIC
2021-Mar-25 1203 EDT
Java Version 16
```

**Comment by H0r53** [comment]
You mentioned the ability to add an ordinal to a table / dataset as a workaround. Since `model.setTableSortState(TableSortState.createUnsortedSortState());` does not seem to be working, do you mind showing how to add an ordinal to the table? I'm guessing a different table than `AddressArrayTableModel` would need to be used. It is of course preferred to understand why the suggested method is not working and resolve it if possible.

Thank you for your time.

**Comment by H0r53** [comment]
After building Ghidra from source the suggested code from @dragonmacher works as intended. Thank you! This is exactly what I needed.

**Comment by dragonmacher** [comment]
That is a fairly old version of Ghidra.  Perhaps there is a related bug.  I verified that changing the order of addresses in the list works as expected for me in Ghidra 10.1.5.

Glad to hear it worked!
