### ISSUE TITLE
Multiple issues with the HCS08/HC05 processor module

### ISSUE THREAD

**Issue by xyzz** [NationalSecurityAgency/ghidra#4444]
**Describe the bug**

I've discovered several issues while attempting to use the HC05 and specifically M68HC05TB processor modules:

- `HC05.ldefs` specifies `slafile="HC08.sla"` instead of `slafile="HC05.sla"`; this results in the decompiler utilizing registers that do not exist e.g. HIX
- `HCS_HC.sinc` does not implement the `oprx16_8_X` addressing mode when producing a processor module for HC05
- The `oprx8_8_X` and `comma_X` addressing use `export *:1 address` instead of `export address`; when this is then used in `ADDRI` and then further in a `JSR` instruction, this produces an excessive dereference. Instead, `oprx8_8_X` and `comma_X` should do `export address` and then `OP1: oprx8_8_X` and `OP1: comma_X` in turn should utilize `export *:1 oprx8_8_X;` etc

I've attempted to fix these issues and you can find the diff at https://gist.github.com/xyzz/b146eaf521e7b570dcb04776d339ee5d, however similar problems exist with the HCS08/HC08 implementation in addition to HC05.

**To Reproduce**
Using the HC05 processor, attempt to decompile a STA or JSR instruction utilizing the IX/IX1/IX2 addressing modes:

![image](https://user-images.githubusercontent.com/1065521/179122402-7c2e446f-6c53-49b4-9c64-35e9134923db.png)
![image](https://user-images.githubusercontent.com/1065521/179123417-9be8c0b2-c756-4e2b-8a75-50bf4d266250.png)

**Expected behavior**

- The `STA` instruction in IX/IX1/IX2 addressing mode should not use the non-existent HIX register
- The `JSR` instruction should not dereference the destination address before jumping to it

**Screenshots**

HIX is being erroneously used by the STA instruction. This results in confusing decompiler output with extra &0xFF00 operations. Note that the HIX register does not exist on HC05.
![image](https://user-images.githubusercontent.com/1065521/179123116-183244e0-685b-4692-a528-574de2bbfaac.png)
![image](https://user-images.githubusercontent.com/1065521/179123193-3fdb7db9-94cf-4403-8fbb-6b0952ce258d.png)

The JSR instruction includes an extra load from RAM. The decompiler is therefore not able to analyze the switch/case table correctly.
![image](https://user-images.githubusercontent.com/1065521/179123289-33a6be11-7475-445f-9702-af5cb4a98cf5.png)
![image](https://user-images.githubusercontent.com/1065521/179123333-e6affd43-382a-4a39-a857-39a42c854e54.png)

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Void Linux
 - Java Version: 10.0.12
 - Ghidra Version: 10.1.4
 - Ghidra Origin: official GitHub distro

**Additional context**
N/A

**Comment by GhidorahRex** [comment]
Sorry, I'm just now getting around to this ticket. Do you happen to have a sample binary I could use to test the changes with?

**Comment by xyzz** [comment]
[SC430929.BIN.zip](https://github.com/NationalSecurityAgency/ghidra/files/11739802/SC430929.BIN.zip)

Here's the file, it can be loaded at address 0x1000

**Comment by GhidorahRex** [comment]
Thanks!

**Comment by GhidorahRex** [comment]
I made a rough pass through and cleaned some stuff up. If you want to test it, please do. Just replace the files in HCS08/data/languages with these ones. I also edited the vector addresses in the pspec to be in line with the documentation for the M68HC05TB manual, but didn't modify the generic HC05.pspec file. It fixed some stuff up when I was trying to parse some of the code. The cspec isn't great, but I played around with it for quite a while and couldn't get the return addresses on the stack to go away in the decompile. Otherwise I think it's functional enough.

[hc05.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/11771591/hc05.tar.gz)
