### ISSUE TITLE
How to stop Ghidra from referring to address and show the value as literal?

### ISSUE THREAD

**Issue by Guusggg** [NationalSecurityAgency/ghidra#4447]
Hi,

Today I encountered a strange issue where Ghidra things a variable is referring to an adress, while it is actually a very big enum (OpenGL).

This is the disassembly (It's WASM with a plugin I found):
![image](https://user-images.githubusercontent.com/6216482/179213271-ffcdb8da-cd30-4e72-94cd-6d3339378668.png)
Which results in this call:
![image](https://user-images.githubusercontent.com/6216482/179213470-205ef6c2-0cd3-4b4a-b144-245dc8bdb8d1.png)
This is `s_halfAnimation`:
![image](https://user-images.githubusercontent.com/6216482/179213535-0cbdb780-0c8a-45b5-a56b-8ab1ae520cfc.png)

There are no references to `s_halfAnimation`, I get there's a `i32.const` instruction which might have Ghidra think that it's trying to refer to the string in question.

I have created a GLenum enum, and when set to 2 bytes it shows correctly:
![image](https://user-images.githubusercontent.com/6216482/179213880-8d303084-0c7f-4ac5-a27c-9c044ce2a61a.png)

However this creates other issues, as GLenum should be 4 bytes. 

Is there any way to instruct Ghidra to NOT interpret a hex value as an address? At this point, I don't mind cleaning everything myself but I tried just about everything and there's never a literal in the decompilation, always either the literal string (when setting `s_halfAnimation` to constant) or it's a `&LABEL`.... 

Things I tried:
- Creating an enum (which works half)
- Equating the value in the disassembly (Nothing changes)
- Deleting references (Nothing changes)
- Changing function signatures (With the enum above, works half)

Anything else to try?

Kind regards,

**Comment by RazielZnot** [comment]
> Deleting references (Nothing changes)

Look for pointers to this address in the entire listing, deleting them might help you as it helped me when I had similar issue.
