### ISSUE TITLE
rh850/e1m-s2 file will not disassemble properly

### ISSUE THREAD

**Issue by Pragasan** [NationalSecurityAgency/ghidra#4453]
Hello
I hope you are well.

I am trying to disassemble a Renesas rh850/e1m-s2 processor file  . I am using the v850 language. Most of the file disassembles correctly. There are some instructions that do not disassemble. See the attached code below. Line 8043d66c.

804d334c 40  96  80  00    movhi      0x80 ,r0,r18
        804d3350 f2  99           cmp        r18 ,r19
        804d3352 96  3d           blt        LAB_804d33c4
        804d3354 04  8d           sld.w      0x8 [ep],r17
        804d3356 e0  0f  42  94    cvtf.ws    r1,r18
        804d335a 40  86  80  3f    movhi      0x3f80 ,r0,r16
        804d335e e6  8f  20  74    cmpf.s     le,r17 ,r6,0x0
        804d3362 f0  97  62  84    subf.s     r16 ,r18 ,r16
        804d3366 04  95           sld.w      0x8 [ep],r18
        804d3368 e0  07  00  04    trfsr      0x0
        804d336c f0              ??         F0h
        804d336d 9f              ??         9Fh
        804d336e e0  94           sst.h      r18 ,0xc0 [ep]
        804d3370 b2  05           be         LAB_804d3376
        804d3372 06  55           sld.w      0xc [ep],r10
        804d3374 7f  00           jmp        [lp]

**Comment by pjsoberoi** [comment]
Do you have anything that disassembles this correctly? I tried: v850-elf-objdump.exe -b binary -D ~/temp/rh850.bin --adjust-vma=0 -m v850-rh850 and I was able to disassemble even less...

**Comment by pjsoberoi** [comment]
Trying some of the other v850 architectures, best guess it's fmaf.s instruction:

``
v850-elf-objdump.exe -b binary -D ~/temp/test.bin --adjust-vma=0 -m v850e2v4

/home/poberoi/temp/test.bin:     file format binary


Disassembly of section .data:

00000000 <.data>:
   0:	40 96 80 00 	movhi	128, r0, r18
   4:	f2 99       	cmp	r18, r19
   6:	96 3d       	blt	0x78
   8:	04 8d       	sld.w	8[ep], r17
   a:	e0 0f 42 94 	cvtf.ws	r1, r18
   e:	40 86 80 3f 	movhi	16256, r0, r16
  12:	e6 8f 20 74 	cmpf.s	le/nle, r17, r6, 0
  16:	f0 97 62 84 	subf.s	r16, r18, r16
  1a:	04 95       	sld.w	8[ep], r18
  1c:	e0 07 00 04 	trfsr	0
  20:	f0 9f e0 94 	fmaf.s	r16, r19, r18
  24:	b2 05       	be	0x2a
  26:	be 06 55 7f 	xori	32597, ep, r0
	...

**Comment by Pragasan** [comment]
> Do you have anything that disassembles this correctly? I tried: v850-elf-objdump.exe -b binary -D ~/temp/rh850.bin --adjust-vma=0 -m v850-rh850 and I was able to disassemble even less...

No

**Comment by pjsoberoi** [comment]
Add this to your **Ghidra/Processors/V850/data/languages/Instructions/Float.sinc**:

`# fmaf.s reg1, reg2, reg3 - rrrrr111111RRRRR|wwwww10011100000
:fmaf.s R0004, R1115, R2731 is R0004 & op0510=0x3F & R1115; R2731 & op1626=0b10011100000
{
	R2731 = (R1115 f* R0004) f+ R2731;
}`

**Comment by Pragasan** [comment]
804d3352 96  3d           blt        LAB_804d33c4
        804d3354 04  8d           sld.w      0x8 [ep],r17
        804d3356 e0  0f  42  94    cvtf.ws    r1,r18
        804d335a 40  86  80  3f    movhi      0x3f80 ,r0,r16
        804d335e e6  8f  20  74    cmpf.s     le,r17 ,r6,0x0
        804d3362 f0  97  62  84    subf.s     r16 ,r18 ,r16
        804d3366 04  95           sld.w      0x8 [ep],r18
        804d3368 e0  07  00  04    trfsr      0x0
        804d336c f0  9f  e0  94    fmaf.s     r16 ,r19 ,r18
        804d3370 b2  05           be         LAB_804d3376
        804d3372 06  55           sld.w      0xc [ep],r10
        804d3374 7f  00           jmp        [lp]

That one works. Thank you

        804d339c cf  15           bgt        LAB_804d33c4
        804d339e e0  8f  42  0c    cvtf.ws    r17 ,r1
        804d33a2 f3              ??         F3h
        804d33a3 0f              ??         0Fh
        804d33a4 e6  94           sst.h      r18 ,0xcc [ep]
        804d33a6 11  08           mov        r17 ,r1
        804d33a8 c2  0a           shl        0x2 ,r1
        804d33aa c7  09           add        r7,r1
        804d33ac 21  8f  0d  00    ld.w       0xc [r1],r17
        804d33b0 21  0f  11  00    ld.w       0x10 [r1],r1
        804d33b4 f1  0f  62  0c    subf.s     r17 ,r1,r1

Still have these instructions that aren't working

**Comment by pjsoberoi** [comment]
It's probably the fnmsf.s. 

```
v850-elf-objdump.exe -b binary -D ~/Disassembler/test.bin -m v850e2v4

Disassembly of section .data:

00000000 <.data>:
   0:	cf 15       	bgt	0x28
   2:	e0 8f 42 0c 	cvtf.ws	r17, r1
   6:	f3 0f e6 94 	fnmsf.s	r19, r1, r18
   a:	11 08       	mov	r17, r1
   c:	c2 0a       	shl	2, r1
   e:	c7 09       	add	r7, r1
  10:	21 8f 0d 00 	ld.w	12[r1], r17
  14:	21 0f 11 00 	ld.w	16[r1], r1
  18:	f1 0f 62 0c 	subf.s	r17, r1, r1
```

Add this to your **Ghidra/Processors/V850/data/languages/Instructions/Float.sinc**:

    # FNMSF.S reg1, reg2, reg3 - rrrrr111111RRRRR|wwwww10011100110
    :fnmfs.s R0004, R1115, R2731 is R0004 & op0510=0x3F & R1115; R2731 & op1626=0b10011100110
    {
        R2731 = -1 f* ((R1115 f* R0004) f- R2731);
    }

**Comment by Pragasan** [comment]
Thank you so much for your assistance. It seems all good now.
