### ISSUE TITLE
macos dark mode makes the menubar unreadable

### ISSUE THREAD

**Issue by loverics** [NationalSecurityAgency/ghidra#4454]
**Describe the bug**
On macOS Monterey when the system setting for dark mode is selected the Ghidra menubar is difficult to read. The background color of the menubar is a dark gray and the text remains black.

**To Reproduce**
1. open `System Preferences`
2. goto `General`
3. in `Appearance` select `Dark`

<img width="669" alt="image" src="https://user-images.githubusercontent.com/18367903/179820159-f3964e20-6939-4fd4-993b-6bf4aabe9980.png">

4. start ghidra
5. open a project

menubar will be dark and unreadable

**Expected behavior**
There could be several options here but just want to be able to see the text on the menubar. Even white text on a dark background would be fine.

**Screenshots**

when dark mode is selected in `System Preferences`
![image](https://user-images.githubusercontent.com/18367903/179819873-fcadbfcd-d679-4949-92a0-dc3bb229253f.png)

when light mode is selected in `System Preferences`
![image](https://user-images.githubusercontent.com/18367903/179819899-efea205a-a7d0-49d8-99f0-e826f7a32c19.png)

**Attachments**
n/a

**Environment (please complete the following information):**
 - OS: macOS Monterey version 12.4
 - Java Version: 13
 - Ghidra Version: 10.1.4 build public 22-May-19 0956 EDT
 - Ghidra Origin: official GitHub distro

**Additional context**
n/a

**Comment by ryanmkurtz** [comment]
Dude!  I'm running almost your exact same setup and don't have the issue.  Can you try upgrading to JDK 17.0.3 to see if the problem goes away?  I see you reported that you are using JDK 13 which hasn't received updates in some time.

**Comment by loverics** [comment]
Dude! Good to hear from ya!

I'll give that a shot!

**Comment by loverics** [comment]
I installed jdk 18.0.2 and this is no longer an issue! @ryanmkurtz thank you for pointing me in the right direction! I hope you're well my friend!

**Comment by ryanmkurtz** [comment]
Great!  I'm doing well!

**Comment by LukBukkit** [comment]
Hey,
the same issue appeared for me today while it was not present before (two months ago).
It doesn't bother me because there's the new dark theme in Ghidra, but it would be nice if there was some kind of fix for it.

OS: macOS Ventura 13.4
Java Version: 20.0.1 (Temurin SDK)
Ghidra Version: 10.3 2023-May-10 1508 EDT
Ghidra Origin: Homebrew

**Comment by LinuxDoku** [comment]
The same problem happens to me with a fresh homebrew setup. I also tried the official Github distribution file. Maybe a java sdk regression?

<img width="912" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/193365/f1fd49ff-1521-4c1f-bd89-a689310cf0ca">


OS: macOS Ventura 13.4 (M1 / ARM64)
Java Version: 20.0.1 (Temurin SDK)
Ghidra Version: 10.3 2023-May-10 1508 EDT
Ghidra Origin: Homebrew / GitHub

**Comment by dragonmacher** [comment]
We are working on a fix for the issue.  In the meantime, you can work around the issue by commenting out a property in `{install dir}/support/launch.properties`.  Specifically, comment out this line:
```
VMARGS_MACOS=-Dapple.awt.application.appearance=system
```

**Comment by wdormann** [comment]
Should this workaround still work in the latest Ghidra?
Using the latest Ghidra 10.3.2 on macOS with JDK 18.0.2.1 results in a mostly-unreadable menu color.
Commenting out `VMARGS_MACOS=-Dapple.awt.application.appearance=system` does nothing that I can see.

<img width="912" alt="Screenshot 2023-08-21 at 1 04 02 PM" src="https://github.com/NationalSecurityAgency/ghidra/assets/14325582/18ce02c6-a776-4a71-ba51-a8ffd5bc33f1">

**Comment by ryanmkurtz** [comment]
I just tried this with a fresh 10.3.2 install and JDK 17:

<img width="793" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/5378554/2692fcd4-d24a-4466-84ad-477fffb61279">

**Comment by wdormann** [comment]
Ah, so I guess that JDK 18 is older than JDK 17.  🤦‍♂️
I've tested with JDK 17 and JDK 20 and they both look fine.

**Comment by wdormann** [comment]
OK, so I tried installing in a VM and the font color is right.
I suppose I'll need to dig into what may be affecting this on my host...
