### ISSUE TITLE
.o binaries (Compiled unlinked) are loaded with +8 offsets to externs

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4455]
**To Reproduce**
Load the attached .o file in ghidra as an ELF (arm/LE/32/v8/default). Observe that the call to malloc points to 0x11008 instead of 0x11000
The file was compiled from the following source
```
#include <stdlib.h>

int main(){
	volatile char* foo = malloc(32);
	int i;
	for(i=0;i<32;i++){
		*foo = 0;
		foo++;
	}
}
```
by running
```
arm-none-eabi-gcc -c test.c
```

**Environment (please complete the following information):**
Ubuntu 20.04
Commit b8425e8
[test.zip](https://github.com/NationalSecurityAgency/ghidra/files/9148837/test.zip)

**Comment by dev747368** [comment]
looks like ARM_ElfRelocationHandler.java is testing for blx instruction to handle it specially, and missing the plain bl instruction(???)

```java
			case ARM_ElfRelocationConstants.R_ARM_GOT_PLT32:
				int oldValue = memory.getInt(relocationAddress, instructionBigEndian);
				newValue = (int) (symbolValue + addend);
				newValue -= (offset + elfRelocationContext.getPcBias(false));

				// is this a BLX instruction, must put the lower half word in bit24
				// TODO: this might not appear on a BLX, but just in case
				if ((oldValue & 0xff000000) == 0xfb000000) {
```

**Comment by ghidra1** [comment]
The PC Bias is not the issue.  It appears that the R_ARM_CALL relocation was only implemented to support the RELA and not REL case.  I will put in a ticket to correct this.  If working from our source you can patch `ARM_ElfRelocationHandler.java`:
```
                        case ARM_ElfRelocationConstants.R_ARM_JUMP24: // Target class: ARM Instruction
			case ARM_ElfRelocationConstants.R_ARM_CALL:
			case ARM_ElfRelocationConstants.R_ARM_GOT_PLT32:
				int oldValue = memory.getInt(relocationAddress, instructionBigEndian);
				if (elfRelocationContext.extractAddend()) {
					addend = (oldValue << 8) >> 6;
				}
```
