### ISSUE TITLE
Is there a way to automatically customize function boundaries?

### ISSUE THREAD

**Issue by LostBenjamin** [NationalSecurityAgency/ghidra#4473]
Given a stripped binary and a text file containing the correct boundaries of all functions in the binary, is there a way for ghidra to automatically apply the correct boundaries?

**Comment by ghidracadabra** [comment]
You can do this with a script; presumably you'd want to run the script before auto-analysis.  

Try 

```currentProgram.getFunctionManager.createFunction(...)```

Note that there are two methods with that name (one allows you to also provide a namespace for the function).  Also note that you'll need to supply the entry point.

**Comment by LostBenjamin** [comment]
Thanks for the quick reply!

Another question: The `.text` section of ARM binaries usually mixes ARM instructions, Thumb instructions, and data. Is there some APIs that can enable the ghidra disassembler to receive ground truth for distinguishing between instructions and data?

**Comment by emteere** [comment]
If you know that the code is ARM v.s. Thumb code at an address you can set a bit before disassembly at those locations.

```
if (thumbcode) {
    Register tmodeReg = currentProgram.getProgramContext().getRegister("TMode");
    currentProgram.getProgramContext().setRegisterValue(addr, addr, new RegisterValue(tmodeReg, BigInteger.ONE));
}
```

Also disassembly will flow and set the TMode state for calls from ARM to Thumb and Thumb to ARM if it can be detected.
But you need to start the disassembly in the correct mode.

**Comment by ghidracadabra** [comment]
In a script, you can call the ```disassemble``` method which takes an ```Address``` as a parameter.  It will start disassembling at the provided address and follow flow.

If you'd like finer control over what is disassembled, use the ```DisassembleCommand``` class.  This class has several constructors, allowing you to specify whether to follow flow, whether disassembly should be restricted to a certain set of addresses, etc.

To use that class in a script:
```DisassembleCommand cmd = new DisassembleCommand(<whatever>);```
    ``` boolean success = cmd.applyTo(currentProgram, monitor);```

In case it's helpful, you can go from the ground truth data to ```Address``` objects as follows:
```currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(<String/long>)```
