### ISSUE TITLE
Some symbols imported by ordinal not geting labeled with symbol's name

### ISSUE THREAD

**Issue by soroosh-chabi** [NationalSecurityAgency/ghidra#4474]
**Describe the bug**
In a PE file, usually when a symbol is imported by ordinal, beside the "Ordinal_\<number\>" label, it also gets another label with the name of the imported symbol. For certain symbols of certain DLL's this does not happen however (stressing the reproducibility of this problem for those symbols of those DLL's). This problem is independent of creation or presence of export symbol files for the containing DLL's.

**To Reproduce**
1. In the 'Project Window' go to 'File'
2. Click on 'Import File'
3. Select the attached file (after having unzipped it)
4. In the symbols imported from 'OLEAUT32.DLL' notice how "Ordinal_6" is not labeled with the symbol's name even though in 'OLEAUT32.DLL' it is exported both by name (SysFreeString) and ordinal.

**Expected behavior**
If a symbol is imported by ordinal and in the exporting DLL, the symbol is also exported by name, the imported symbol should also be labeled with the symbol's name. There should at least be an option to activate this behavior in case it is not a good idea to have it by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/12121215/181266693-2cc2b3f1-c0d4-42ac-a852-cbbee87b7ee4.png)

**Attachments**
[main.zip](https://github.com/NationalSecurityAgency/ghidra/files/9199620/main.zip)

**Environment:**
 - OS: Windows 10
 - Java Version: 11.0
 - Ghidra Version: 10.1.4
 - Ghidra Origin: locally built

**Comment by soroosh-chabi** [comment]
I did a little debugging and I think I know what the problem is.

### How things happen on a good day
A "Ordinal\__N_" label is created on two occasions:
1. When a symbol is exported:
https://github.com/NationalSecurityAgency/ghidra/blob/68a34fda2f456cf21ff4768774e240028cb5f2bf/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/PeLoader.java#L644-L645
2. When a symbol is imported by ordinal:
https://github.com/NationalSecurityAgency/ghidra/blob/68a34fda2f456cf21ff4768774e240028cb5f2bf/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/ImportDataDirectory.java#L315-L316

Considering how exported symbols are labeled, during the construction of `LibrarySymbolTabel`, exported symbols are found based on the "Ordinal_*" pattern:
https://github.com/NationalSecurityAgency/ghidra/blob/68a34fda2f456cf21ff4768774e240028cb5f2bf/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/LibrarySymbolTable.java#L106
All symbols found this way are taken to be exported and inserted in the symbol table with the symbol's name if possible or as a symbol named "Ordinal\__N_" if no name is found for the symbol:
https://github.com/NationalSecurityAgency/ghidra/blob/68a34fda2f456cf21ff4768774e240028cb5f2bf/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/LibrarySymbolTable.java#L115-L130

Later on, when the symbols imported by ordinal are to be labeled with the symbols' names, first the `LibrarySymbolTabel` of the exporting PE file is searched for a symbol named "Ordinal\__N_" and when such a symbol is not found, it will be searched for a symbol with ordinal _N_:
https://github.com/NationalSecurityAgency/ghidra/blob/68a34fda2f456cf21ff4768774e240028cb5f2bf/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/AbstractLibrarySupportLoader.java#L855-L863

### What goes wrong in a bad day
When a PE file exports a symbol with ordinal _N_ and also imports another symbol by ordinal, with an ordinal of _N_, there will be a symbol named "Ordinal\__N_" in its `LibrarySymbolTabel` which actually points to the imported symbol because the name of the imported symbol is not yet known at the time of construction of the `LibrarySymbolTable`. Nonetheless, this is the symbol found during the process of "labeling symbols imported by ordinal with their names" for another PE file that imported (by ordinal) the symbol with ordinal _N_ from the former PE file and thus, will prevent the creation of a label with the symbol's name.
Conceivably, a similar a situation could also be happen if in the previous scenario, the exported symbol with ordinal _N_ does not have a name associated with it.

**Comment by ryanmkurtz** [comment]
Thank you for the very detailed writeup!  Noting that imported symbols have a namespace of the target DLL and exported symbols are in the global namespace, I experimented with filtering out non-global symbols in this iterator
https://github.com/NationalSecurityAgency/ghidra/blob/68a34fda2f456cf21ff4768774e240028cb5f2bf/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/LibrarySymbolTable.java#L106
and that seemed to do the trick.  I need to discuss this approach with the team though to see if it's the best or even a reliable solution.

**Comment by soroosh-chabi** [comment]
Sorry if I bored you there. I guess I was subconsciously explaining the problem to a newcomer like myself but if as an expert you find it redundant, I could dial it back  a tad!

With regards to a solution, I was going to suggest `getExternalSymbols`:
https://github.com/NationalSecurityAgency/ghidra/blob/68a34fda2f456cf21ff4768774e240028cb5f2bf/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/symbol/SymbolTable.java#L426
There is a caveat however: unless I'm mistaken, labels with an "Ordinal_\*" name pattern are only used for exported and imported symbols of PE files and are not used in any other file format. As a result, the old method of finding exported symbols by finding the symbols with an "Ordinal_\*" name pattern would have essentially skipped over non-PE files and constructed an empty `LibrarySymbolTable`. But with my suggestion this will no longer be true. Am I correct?

**Comment by ryanmkurtz** [comment]
Sorry for the delay in responding, I plan on getting back to this today to try to get it resolved.  I am definitely not an expert in this code...I have only poked at it here and there, and it's probably been a few years, so your explanation is helpful.  I am going to step through all this code to reestablish myself as the "expert" on how it all works and then I can weigh in better on your suggestion.  Thanks!

**Comment by ryanmkurtz** [comment]
I don't think `public SymbolIterator getExternalSymbols()` is what you want, those correspond to the imports.

**Comment by ryanmkurtz** [comment]
Perhaps
```
		SymbolIterator iter = symTab.getSymbolIterator(SymbolUtilities.ORDINAL_PREFIX + "*", true);
		while (iter.hasNext()) {
			monitor.checkCanceled();
			Symbol sym = iter.next();
			if (!sym.isExternalEntryPoint()) {
				continue;
			}
```

**Comment by ryanmkurtz** [comment]
Sorry for the delay, I was going back and forth with the team to come up with the best solution.  The fix for this issue will still filter first by symbols starting with "Ordinal_".  An `if/continue` will be put inside the loop that makes sure the ordinal symbol is both in the global namespace and is an entry point.  There are some other more subtle errors inside the loop that will be fixed too.

With that being the solution, you are correct in that the `LibrarySymbolTable` will continue to be empty for non-PE files.  This was designed a long time ago with only PE in mind (despite it behind inherited by many other Loaders)

**Comment by soroosh-chabi** [comment]
No need to apologize; I appreciate how busy you guys are, trying to solve this (and other) problems and to be honest I wasn't strictly pushing to get my particular solution picked but rather trying to (subtly) point out a number of potentially more readable alternatives that don't quite work out because `LibrarySymbolTable` is being used in the wrong place (`AbstractLibrarySupportLoader`).

Speaking for myself (a somewhat novice reverse engineer), the whole business of export symbol files seemed really confusing at first: the option is present during the import of non-PE files, the Help does not say anything about it being used only for PE files or that besides stack purge information, it is used to find the names for symbols imported by ordinal and finally while I was trying to find out exactly what this option does, I came upon the bug reported in the current issue. With all of this in mind and noting what you said about all of this being designed a long time ago with a limited purpose in mind, wouldn't it be better if either the concept of export symbol files was expanded to support non-PE files (assuming there is a use for it) or certain aspects of it were redesigned (addressing such problems as the ones I have enumerated).

**Comment by Wall-AF** [comment]
Something similar also ocurrs with the NE loaders <https://github.com/NationalSecurityAgency/ghidra/issues/2233>.

**Comment by ryanmkurtz** [comment]
> wouldn't it be better if either the concept of export symbol files was expanded to support non-PE files (assuming there is a use for it) or certain aspects of it were redesigned (addressing such problems  ones I have enumerated).

Yes, definitely!  We should keep this issue about the original bug you found, but it is clear this whole area needs a refresh.  We haven't had a need to modify this code much over the years, but there are some things you just can't unsee.
