### ISSUE TITLE
Bug in Variadic Function Signature analyzer

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4478]
**Describe the bug**
When analyzing calls for variadic strings, any string that contains the "%" character is treated as a candidate. The results (``FunctionCallData``) are then applied in order by ``FormatStringAnalyzer.overrideCallList`` without checking if they are applicable.

``FormatStringAnalyzer`` is intended to act on prototypes of the form ``foo( _, _, char *, ...)``, as evidenced by 
```
	private boolean usesVariadicFormatString(Function function) {
		int paramCount = function.getParameterCount();
		return function.hasVarArgs() && paramCount > 0 &&
			isCharPointer(function.getParameters()[paramCount - 1].getDataType());
	}
```

Accordingly, ``PcodeFunctionParser.parseFunctionForCallData`` should only act on the appropriate parameter.

**To Reproduce**
Compile the following code and run variadic function signature from autoanalysis
```
#include <stdio.h>

int main () {
   for (int i = 0; i < 100; i ++) {
      // Override(char*, int, int, int)
      printf("%s World %d\n", "Hello %d %d %d", i);
   }  

   return(0);
}

```
The result is
```
     s_Hello_%d_%d_%d_00102004             XREF[1]:  main:00101163(*)  
     00102004 48 65       ds                 "Hello %d %d %d"
             6c 6c 
             6f 20 


undefined8 main(void)

{
  int in_ECX;
  int local_c;
  
  for (local_c = 0x0; local_c < 0x64; local_c += 0x1) {
    printf("%s World %d\n",0x102004,local_c,in_ECX);
  }
  return 0x0;
}
```

**Environment (please complete the following information):**
Commit d721fa5

**Comment by sad-dev** [comment]
Sorry, realized it was due to some changes I had made elsewhere

**Comment by sad-dev** [comment]
Reopened as during the triage I discovered another bug in Ghidra

**Comment by ryanmkurtz** [comment]
Did you edit your original post to represent the new bug?

**Comment by sad-dev** [comment]
> Did you edit your original post to represent the new bug?

Yes, the original post shows the new bug (the old being a false report)
