### ISSUE TITLE
Can't Select Union

### ISSUE THREAD

**Issue by elbiazo** [NationalSecurityAgency/ghidra#4480]
**Describe the bug**
A clear and concise description of the bug.

Can't Select union on this instance

**To Reproduce**
1. Download HEVD.sys from [hevd git](https://github.com/hacksysteam/HackSysExtremeVulnerableDriver/releases/tag/v3.00)
2. Load vulnerable/x64/HEVD.sys
3. Try to select union for _IO_STATUS_BLOCK.Status. Ex. in (IrpDeviceIoCtlHandler

## IrpDeviceIoCtlHandler line 172 should be param_2->IoStatus.Status but it is field0_0x0. It has correct type which is _IO_STATUS_BLOCK_u_0 union but cant select the field.

![image](https://user-images.githubusercontent.com/23147879/181826712-098ae2c0-e7b3-4b4e-b1ad-6fe6cbbd886e.png)
![image](https://user-images.githubusercontent.com/23147879/181827240-a57bc23e-e7f7-4899-852a-ca56a2d908cd.png)

**Expected behavior**
I believe from issue #1476  we should be able to select union but seems like it bugs out on this instance.

**Environment (please complete the following information):**
 - Java Version:1 1
 - Ghidra Version: 10.1.5

**Comment by astrelsky** [comment]
There is no decompiler support for unions in Ghidra 10.1. It is coming in Ghidra 10.2 and currently available in the master branch.

**Comment by ryanmkurtz** [comment]
Thanks @astrelsky
