### ISSUE TITLE
Granularity of references in the API

### ISSUE THREAD

**Issue by LostBenjamin** [NationalSecurityAgency/ghidra#4487]
Dear ghidra developers,

For my binary, ghidra GUI shows an instruction `ldr.w   r10, [r5=>DAT_000310cc,r6,lsl #0x3]`. Now I would like to find the reference `r5=>DAT_000310cc` through the API. The `Reference` class in the [documentation](https://ghidra.re/ghidra_docs/api/ghidra/program/model/symbol/Reference.html) has functions `getFromAddress` and `getOperandIndex`, which only allows me to find the reference from the second operand of the instruction (i.e., `[r5,r6,lsl #0x3]`) to `DAT_000310cc`. How can I find `r5=>DAT_000310cc`?

Best,
Jingxuan

**Comment by mumbel** [comment]
On mobile, but `Instruction` I thought had that ability. 
You might look into  `getInstructionAt()` or similar calls from the flat API and play around with that returned object and see if it has what you're looking for

**Comment by LostBenjamin** [comment]
Thank you for the quick reply!

`Instruction` indeed has more options for getting references by inheriting from the `CodeUnit` interface. However, I still failed to find the API that achieves my goal. As I looked at the [documentation](https://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/Instruction.html), all those options are about operand index.

Could you tell me how to find my target reference?

**Comment by LostBenjamin** [comment]
Any news on this?

**Comment by dragonmacher** [comment]
References in Ghidra are `Address`-based.   As mentioned by @mumbel, you can see various ways of finding references by looking at the `FlatProgramAPI` class.   There are various methods in that class that start with `getReference`.  You can look at the source code for those to see how they find references.  All of them use the `ReferenceManager`, which is the class that manages references in Ghidra.  Here is an example of one of the methods:
```
	public final Reference getReference(Instruction instruction, Address toAddress) {
		Reference[] references =
			currentProgram.getReferenceManager().getReferencesFrom(instruction.getMinAddress());
		for (Reference reference : references) {
			if (reference.getToAddress().equals(toAddress)) {
				return reference;
			}
		}
		return null;
	}
```

**Comment by LostBenjamin** [comment]
Hi @dragonmacher,

Thanks for the answer! I understand that `Reference`s are `Address`-based. However, in my example above, the reference `r5=>DAT_000310cc` in `ldr.w r10, [r5=>DAT_000310cc,r6,lsl #0x3]` is more fine-grained than what can be retrieved with `Address` and the `getOperandIndex` function of `Reference`. It is a reference from a register used in the second operand of an instruction to global data.  With what API can I retrieve `r5=>DAT_000310cc`?

Best,
Jingxuan

**Comment by dragonmacher** [comment]
The best way to see how references calculated for the Listing display, which includes how we draw operands and show references to each part, is to look at the code that creates those display elements.  That can be found in `CodeUnitFormat`.

*Warning: that code is not for the faint of heart*

That class will show you each "nuanced" API call we make and includes code in varying quality.
