### ISSUE TITLE
Undecorated (unmangled) symbols in symbol table

### ISSUE THREAD

**Issue by justanotheranonymoususer** [NationalSecurityAgency/ghidra#4488]
**Is your feature request related to a problem? Please describe.**
There are many columns to choose from in the symbol table (Ctrl+T), but no option for undecorated (unmangled) symbols, even though Ghidra has the capability to retrieve it.

**Describe the solution you'd like**
Add it as a possible column that can be added.

**Describe alternatives you've considered**
Doing unmangling manually. In fact, I don't know how to do this aside from creating a C++ tool to help me with it.

**Additional context**
![image](https://user-images.githubusercontent.com/5781692/182042025-a819663e-8ec7-427b-9dfc-0e52fca8ca0a.png)

**Comment by ryanmkurtz** [comment]
Ghidra has a demangling capability that runs during analysis.  Are you implying this is not running correctly, or are you asking for a new feature assuming our demangler did its job correctly?

**Comment by dragonmacher** [comment]
As @ryanmkurtz pointed out, we have analyzers that will demangle GNU and Microsoft symbols.  Mangled types from other tool chains are not currently supported.    If you are using a supported architecture, then running analysis will demangle the symbols and update the primary symbols at each respective address to use the demangled symbol instead of the mangled symbol.   Further, the original mangled symbol will still exist at the address *and is viewable in the Symbol Table.*    This allows you to see demangled symbol of interest by finding the mangled symbol in the Symbol Table and then double-clicking it to navigate to the applied address.   Once at the applied address you can see the demangled version of the symbol.

There is currently no column in the Symbol Table that allows you to see the demangled version without navigating to the applied address.

**Comment by justanotheranonymoususer** [comment]
> Are you implying this is not running correctly

Yes, see my other issue:
https://github.com/NationalSecurityAgency/ghidra/issues/4489

And even if it works during analysis, having a table to work with can be more convenient for some use cases. 

> There is currently no column in the Symbol Table that allows you to see the demangled version without navigating to the applied address.

That's what the issue is about :) it can be handy for several use cases. For example, viewing, filtering, copying, and also there's no "raw" string for the demangled version when I navigate to it, there's some version in comments but it's word wrapped and formatted.

**Comment by dragonmacher** [comment]
> That's what the issue is about :) it can be handy for several use cases. For example, viewing, filtering, copying, and also there's no "raw" string for the demangled version when I navigate to it, there's some version in comments but it's word wrapped and formatted.

I see.  This clarifies the request.  This should not be that difficult to implement.

**Comment by dragonmacher** [comment]
> also there's no "raw" string for the demangled version when I navigate to it, there's some version in comments but it's word wrapped and formatted.

There should be a primary symbol at the applied address that is the 'raw' demangled symbol.   Will you provide a screenshot of the issue you are describing here?

**Comment by justanotheranonymoususer** [comment]
Here's an example, if that's what you're asking. See how it spans across three lines with extra whitespace and such.

![image](https://user-images.githubusercontent.com/5781692/182184095-809bf1e5-02c7-400a-8d63-517273c66155.png)

**Comment by dragonmacher** [comment]
I see.  I was thinking how the symbols are used in the Listing, not the Decompiler.

**Comment by justanotheranonymoususer** [comment]
Yes, I have it in the listing:

![image](https://user-images.githubusercontent.com/5781692/182188548-3463de1a-9424-4ef3-a7f2-2f775127d6e9.png)

It's truncated, but turns out I can right click and copy it. I tried it before and it didn't work, maybe because I selected multiple lines. Good to know this solution exists, even though it doesn't help in the case of issue https://github.com/NationalSecurityAgency/ghidra/issues/4489

Is it possible to show all matching symbols in the listing for the relevant address? Actually, there are several cases where it can be useful, sometimes the optimizer uses the same implementation for several functions, but several symbols still point to it. Ghidra only chooses one of them. Perhaps I should create a new issue about it.

**Comment by justanotheranonymoususer** [comment]
See my other issue besides this one. And even if it works during analysis,
having a table to work with can be more convenient for some use cases.

**Comment by dragonmacher** [comment]
After some exploration, this feature is not trivial to implement using our current framework.  We currently do not demangle all symbols.  Also, we currently do not maintain the 'demangled -> mangled' symbol relationship.  To add this feature we would need more non-trivial demangler and database changes.   Such changes would be useful for implementing other features.  As such, we hope someday to return to this ticket if we are able to update the underlying framework.
