### ISSUE TITLE
With full and partial symbols available, Ghidra sometimes chooses partial

### ISSUE THREAD

**Issue by justanotheranonymoususer** [NationalSecurityAgency/ghidra#4489]
**Describe the bug**
Here's a random example:
The file `Taskbar.dll` version 10.0.22621.105.
There are two symbols for the same function:
* `CTrayAppIdentity::RuntimeClassInitialize`
* `?RuntimeClassInitialize@CTrayAppIdentity@@QEAAJPEBGU_GUID@@0@Z`

As you can see, the second symbol provides more information, but Ghidra uses the first and throws away that useful info.

![image](https://user-images.githubusercontent.com/5781692/182042401-c353d7bd-628c-4d89-bd6a-2ef937974d3d.png)

**To Reproduce**
1. Get the file: [Taskbar_10.0.22621.105.zip](https://github.com/NationalSecurityAgency/ghidra/files/9229597/Taskbar_10.0.22621.105.zip)
2. Download PDB from MS symbol server
3. Go to CTrayAppIdentity::RuntimeClassInitialize
4. See that no info of parameters exists

**Expected behavior**
Use the info from the C++ symbol

**Screenshots**
Above

**Attachments**
Above

**Environment (please complete the following information):**
 - OS: Win10
 - Java Version: 11.0
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official GitHub distro

**Comment by ghizard** [comment]
With MSDIA PDB Analyzer, we used to make the (public) mangled symbols "primary" as the (global) plain-name symbol did not carry additional information.  Being primary is what allows the demangler analyzer to do its job (in Ghidra, only one symbol at an address can be primary).  With PDB Universal, we changed this order to take advantage of the sequence of much more rich information that is available with the sequence of global symbols (that MSDIA PDB analyzer was not aware of) such as frame information, parameters, and variable scopes.  In addition, the demangler is only aware of structure and class names, not their members, but PDB global symbols can reference the "type" database within the PDB directly to give exact type definitions.  So this is usually the better solution.  However, for your PDB (like other MSFT PDBs), type information is not conveyed in the PDB.  Moreover, the sequence of globals for your function is only composed of the start/stop set of symbols and does not contain the other rich information.

There is a short-term fix that can be made for this where we just detect whether there is type information in the PDB to process accordingly.  But this change would likely only be temporary, as we have future plans for more sophisticated processing to deal with more complicated situations.

If you have ability to make a fix in the source for yourself, you can modify PdbApplicator (in Ghidra 10.1.5 or earlier) or DefaultPdbApplicator (master) to make a small fix.
At approximately lines 284-285 (DefaultPdbApplicator), you can replace
```
		processGlobalSymbolsNoTypedefs();
		processPublicSymbols();
```
with
```
		if (pdb.getTypeProgramInterface().getTypeIndexMaxExclusive() == pdb.getTypeProgramInterface().getTypeIndexMin()) {
			processPublicSymbols();
			processGlobalSymbolsNoTypedefs();
		}
		else {
			processGlobalSymbolsNoTypedefs();
			processPublicSymbols();
		}
```

**Comment by justanotheranonymoususer** [comment]
Thanks for the explanation. I assumed it might be tricky and with nuances.

> If you have ability to make a fix in the source for yourself

I'd rather not to, I'm using the compiled build for hobby stuff. It would be great to have it in the next version if possible.
