### ISSUE TITLE
Please suport a comand line option "--version" for analyzeHeadless

### ISSUE THREAD

**Issue by TodAmon** [NationalSecurityAgency/ghidra#449]
Please provide a "--version" command line option for analyzeHeadless.   At present I have to run a very simple script that asks the API for the version.  It would be handy to have this more readily available.

**Comment by ryanmkurtz** [comment]
What is your use case?  If you need access to the version # from a script you are writing, you could pretty easily get the version of Ghidra from Ghidra/application.properties.

**Comment by TodAmon** [comment]
This is for a script and supporting integration across changing versions -- your suggestion will work, as long as the existence of Ghidra/application.properties is stable.  Thank you.

**Comment by ryanmkurtz** [comment]
It is stable...you can count on it being there.
