### ISSUE TITLE
How to import the dyld_shared_cache with analyzeHeadless in the file system mode.

### ISSUE THREAD

**Issue by 1wc** [NationalSecurityAgency/ghidra#4498]
I want to make some automatic analysis on a dylib in dyld_shared_cache, so I hope to import the dyld_shared_cache in file system mode and load the target nested file. It is easy in Ghidra GUI, but when I tried to use analyzeHeadless's -import option, it costs a long time and seems to import the whole binary. How should I solve this issue? Thanks!

**Comment by dev747368** [comment]
Current the headless analyzer doesn't use / understand 'file system mode'.

You could manually handle importing using GFilesystem stuff yourself in a headless pre-script, but its a bit involved.

**Comment by 1wc** [comment]
Thanks for the reply! 
Could you tell me which part of the source code can I refer to for importing dyld_shared_cache with GFileSystem.

**Comment by 1wc** [comment]
Thanks for the reply!
I will close this issue and try it.
