### ISSUE TITLE
Question: How to automatically propagate thunked function signature to thunk function?

### ISSUE THREAD

**Issue by IceTDrinker** [NationalSecurityAgency/ghidra#4499]
Hello,

I am having this weird thing where all thunk functions more or less have the `void thunk_func(void)` signature while the actual function (from a windows .exe from 1998) are of the form e.g.

`int __fastcall actual_func(int param1)`

Making the analysis at call site tedious in the decompiler (basically just a `thunk()` call appears without any relevant parameter) without manually editing the function signature of the thunk function to match the actual function being called.

I'm wondering if it has something to do with the __fastcall calling convention, I'm not sure if other thunks behave better

Is there a way to automatically propagate the actual function signature to the thunk? Maybe it's not doable or easily doable, I'm new to reverse engineering, but that's a pattern I see in the executable I'm working on and manually editing thunk signatures is starting to get a bit old 😅 

Any pointers on how I could circumvent the issue/what is expected of a Ghidra user in that case is welcome (scripting maybe?).

Cheers, Ghidra is awesome, could be even more awesome once this can be done automatically :)

**Comment by mumbel** [comment]
Is your function definition committed for `actual_func`?   You can tell by looking at the listing window and comparing to the decompiler, both should show the same return type and params.  I am taking a guess that your decompiler shows `int acutal_func(int param_1)` and your listing window shows maybe `undefined actual_func()`.  

You can press `p` in the decompiler for `Commit Params/Return` to commit.  I think once that done and they match your thunks should have type information, at least in my experience.

**Comment by IceTDrinker** [comment]
Thanks, I'll see if it helps, it's kind of odd though as the function signature was generated by the decompiler itself, so does it mean that the signatures are uncommitted by default?

**Comment by mumbel** [comment]
Sorry, I don't know the answer to when/why params/return are committed or not, just that seems to be the cause when issues like this come up.  I try to commit as often as I can if I get a good prototype decided, or know to go back and change them later if I commit something similar to `undefined4`/`undefined *` types.

**Comment by ghidra1** [comment]
Your thunk function should set the thunked function.  There is both a Function action with popup (**Function->Set Thunked Function...**) and an API method on Function for doing this.

**Comment by ghidra1** [comment]
@IceTDrinker , Does my previous comment address your concern?  If so, I would like to close this ticket.
