### ISSUE TITLE
Defined Strings Rendering HTML found in binaries

### ISSUE THREAD

**Issue by fuzzywalls** [NationalSecurityAgency/ghidra#45]
**Describe the bug**
If a string is present in the binary with valid HTML tags it is being rendered in the "String Value" window. The <script> tag does not seem to be executed, but I didn't spend a lot of time messing with it.

**To Reproduce**
1. Compile this code: 
```
#include <stdio.h>

void main() {
        char *test = "<html><body><h2>Error: %s</h2> <p>%s</p></body></html>\r\n";
        printf("%s\n", test);
        return;
}
```
2. Load the compiled code into Ghidra.
3. View the rendered string in the "Defined Strings" window.
4. View the error. 

**Expected behavior**
HTML should not be rendered in this view.

**Screenshots**
![screen shot 2019-03-06 at 10 42 04 am](https://user-images.githubusercontent.com/39141855/53893608-83f9b780-3ffc-11e9-900d-30f93d39280f.png)

**Comment by oldmud0** [comment]
The string value column was probably set to rich text instead of plain text. It seems like the fix would be trivial.

**Comment by lillypad** [comment]
Have you tried something like:

```html
<html><body style="background-image: url("http://localhost:3000/script.js");>Test</body></html>
```

Would be interesting to see if that works.

:smile:

**Comment by ryanmkurtz** [comment]
This will be fixed in our next release.  Thanks for reporting it!
