### ISSUE TITLE
Intellij IDEA IDE support

### ISSUE THREAD

**Issue by Escapingbug** [NationalSecurityAgency/ghidra#450]
**Is your feature request related to a problem? Please describe.**
I know this is just a problem of personal bias. But supporting `IntelliJ IDEA` could be great for lovers of this IDE.

**Describe the solution you'd like**
Currently `IDEA` can be configured to build with just running `gradle buildGhidra` with all other preliminaries configured (dependency downloads, gradle init script setting...). Launching is possible through `LaunchSupport` but seems decompiler and some extensions (or plugins) missing. 

I wonder if it is possible to support `IDEA` with a plugin or just simple guide of how to configure the project in `IDEA`.

**Comment by lacasseio** [comment]
Highly suggest using the [native importer for IntelliJ](https://www.jetbrains.com/help/idea/gradle.html) which works great with [the latest Gradle version](https://docs.gradle.org/current/release-notes.html) and [the Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html).

For Eclipse, it's recommended to use [the Buildship plugin](https://projects.eclipse.org/projects/tools.buildship).

**Comment by Escapingbug** [comment]
That's actually what I do for now. But you still need a little more steps to do launching and debugging.  And of course, there's no document on that...

**Comment by lacasseio** [comment]
Right, for those you can react to the Idea plugin being applied during the import and execute some configuration. See https://github.com/gradle/gradle/blob/master/buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt for an example of how Gradle configure the native import. I'm unsure about the launching and debugging, but that can definitely be a feature request to JetBrains or Gradle depending where the limitation falls.

**Comment by ryanmkurtz** [comment]
Unfortunately we are not going to be able to offer official support for Intellij for the foreseeable future.  There is simply too much other work to do in more critical areas of Ghidra.  Perhaps it can be supported by the community without being tightly integrated into our official repo.

**Comment by XVilka** [comment]
There is a third-party repository for integrating it with the Intellij IDEA: https://github.com/garyttierney/intellij-ghidra

**Comment by mattfj10** [comment]
> Unfortunately we are not going to be able to offer official support for Intellij for the foreseeable future. There is simply too much other work to do in more critical areas of Ghidra. Perhaps it can be supported by the community without being tightly integrated into our official repo.

Other work? My brother in Christ the scripting experience in Ghidra is one of the worst things I've ever dealt with rivaled only by vim but visually flipped upside down and every hotkey inverted. A 19th century mercury poinsoned hat maker is probably more stable than the scripting environment provided by this thing

**Comment by bukowa** [comment]
Hey anyone successfully develops Ghidra using Intellij IDEA and could share some configurations?
