### ISSUE TITLE
ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB

### ISSUE THREAD

**Issue by LoverOfSadness** [NationalSecurityAgency/ghidra#4503]
Could not connect: ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB | [] | 

</body>
</html>�

i'm getting this error when i try to connect gdb  after enter ssh password

tried both ssh

localhost 
&
vps server 

same error are coming  

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/109886364/182841553-a76501b5-0844-4ade-a1f5-4589aa08a09f.png">

 - OS: [e.g. macOS 11.3.1]
 - Java Version:  14.0.1 2020-04-14
 - Ghidra Version: [e.g. 10.1.5]
 - Ghidra Origin: official GitHub distro

**Comment by d-millar** [comment]
@LoverOfSadness I see you closed this - did you figure it out?  Apologies for not answering quicker!
