### ISSUE TITLE
Using a "union of pointers" causes LowlevelError("PTRSUB off of non-pointer type")

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4508]
Using a `union` with pointer and `struct` containing pointers as in something like:
```
union LP<type> {
   struct __seg<type> {
        <type>*               __offset__;
        uint                  __segment__;
    }                         __np__;
    <type>*<n>                __lp__;
};
```
(see https://github.com/NationalSecurityAgency/ghidra/discussions/4469) causes the C++ `printc.cc` to throw the  "PTRSUB off of non-pointer type" error.

Whilst technically a `union` type isn't a `pointer` type, maybe something could be relaxed to show the issue in context rather than loosing the whole decompilation output.

I believe the situation occurs if a function `<f>` is called from within the current function being decompiled where `<f>` contains a `<type> *` parameter or return value.

**Comment by Wall-AF** [comment]
Another consequence is that if you use this type to define global data (in the Listing Panel), when the object is expanded, the addresses are no longer replaced with their values.  Ie. if you have a union describing function pointers, the function name isn't displayed, only its address.

**Comment by caheckman** [comment]
I can't reproduce this. Can you provide a "Debug Function Decompilation" dump for a function exhibiting the LowlevelError?

**Comment by Wall-AF** [comment]
Sorry for the delay, but here's an example [dragon_1178_0fad.zip](https://github.com/NationalSecurityAgency/ghidra/files/9576398/dragon_1178_0fad.zip), and note the error has changed to:
` Pcode: Decoding error: Expecting <doc> but did not scan an element`

The simplest way to enable decompilation is to revert the new unions back to standard Ghidra pointers (`*32`) for this assembly:
```
   1178:12c1 9a bf 1c     - ? -         CALLF      WriteBitSore                                     void WriteBitSore(LPDgnBitStore_
             d0 11
```
so the function signature becomes:
`void WriteBitSore (DgnBitStore_0xc_t *32 pBitStore, DgnDFileStream_t *32 pDFileStrm)`

Whilst looking for other ways I found that changing the function signature for the main function from
`void FUN_1178_0fad (undefined *32 param_1, undefined4 param_2)`
to
`void FUN_1178_0fad (undefined *32 param_1, undefined *32 param_2)`
also worked!

This 2nd way has something to do with the fact that the 2nd parameter (`param_2`) is recognised as `LPDgnDFileStream_t` from the call to `WriteBitStore(...)` and when declared as `undefined4` Ghidra is unable to produce the conversion.  Whereas, when the 2nd parameter of `WriteBitStore` is `DgnDFileStream_t*32`, Ghidra is able to convert `undefined4` into the pointer type.

I hope the above analysis helps...

-----------------------------------------------------------
As an asside, do you think this approach is the best way to handle mixed size pointers in Ghidra at the moment?  (As you'll see in the decompiled example, using this approach for the `vtable` structures enables Ghidra to _kind of_ interpret the virtual function calls correctly.)

**Comment by caheckman** [comment]
Thank you. I'm reproducing the error now.

**Comment by Wall-AF** [comment]
Also, is there a way to apply these `unions` to the `this` parameter of class function calls?
