### ISSUE TITLE
Missing functions in the Symbol Tree View when opening a (Rust) ELF object file

### ISSUE THREAD

**Issue by martinclauss** [NationalSecurityAgency/ghidra#4515]
**Describe the bug**
When opening an ELF object file the Symbol Tree View under *Functions* contains just a single entry although there exist multiple functions.

**To Reproduce**
1. Import and open the attached object file

**Expected behavior**
All recognized functions should be displayed under *Functions* in the Symbol Tree View.

**Screenshots**
missing functions:
![missing functions](https://user-images.githubusercontent.com/51541424/183449261-fbfe9146-9dc0-4de4-a6d5-72b81f943d75.png)

a simple script that is able to iterate over all the functions:
![script can iterate over functions](https://user-images.githubusercontent.com/51541424/183449771-2c8f4444-fa66-4222-b584-321f580ba787.png)

**Attachments**
[addr2line-3c55f33cd4464bbb.addr2line.ff5e4bca-cgu.3.rcgu.o.zip](https://github.com/NationalSecurityAgency/ghidra/files/9282879/addr2line-3c55f33cd4464bbb.addr2line.ff5e4bca-cgu.3.rcgu.o.zip)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 17.0.4
 - Ghidra Version: 10.1.5 Build PUBLIC 2022-Jul-26 15 43 EDT
 - Ghidra Origin: GitHub Release Page 

**Additional context**
This is a Rust object file compiled with rustc version 1.59.0. 

Thanks for your time and effort! :)

**Comment by dev747368** [comment]
You should be able to see the functions, in the Symbol Tree, if you browse under the "Classes" or "Namespaces" root node.

**Comment by martinclauss** [comment]
Thanks! I overlooked that ;) That solves this issue :)
