### ISSUE TITLE
AVR8 'W' Register

### ISSUE THREAD

**Issue by john-champagne** [NationalSecurityAgency/ghidra#4516]
The AVR8 has three combined registers that it uses for indirect addressing: X, Y, and Z.
For some reason, Ghidra defines a fourth register, W, which is composed of R25:R24.
Any operation involving R25 and R24 show up as 'Whi' and 'Wlo'.

This is non-standard notation. I can't really find any reference to the 'W' register in an AVR anywhere. See the diagram below from [an AVR8 datasheet.](https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/ProductDocuments/DataSheets/ATmega808-09-1608-09-DataSheet-DS40002172C.pdf)

![Capture2](https://user-images.githubusercontent.com/30150781/183455523-0aa61ffc-e3e9-4129-8c35-e30c47528670.PNG)

This notation in Ghidra appears to go back to the [initial release](https://github.com/NationalSecurityAgency/ghidra/blob/79d8f164f8bb8b15cfb60c5d4faeb8e1c25d15ca/Ghidra/Processors/Atmel/data/languages/avr8.sinc#L42). There's a comment on the line: "Technically, manual has R25R24 instead of W." 

Unless there's some advantage I'm not seeing, I think it should be removed as it is not standard and confusing.

**Comment by GhidorahRex** [comment]
I've seen exactly one reference to the W register, and I agree that it's confusing and non-standard as far as the Atmel documentation is concerned (although admittedly it's hard to do a search for references of a single letter).
