### ISSUE TITLE
Dependent data type archives not properly syncing

### ISSUE THREAD

**Issue by Schala** [NationalSecurityAgency/ghidra#4517]
**Describe the bug**
When parsing a new data type archive from C headers which relies on data types already in another, opened archive, the result is often the resulting archive having a mix of type associations with that other archive and straight up copying various structs, enums, functions, etc., without any association. This results in having to manually purge duplicate defines and anonymous enums, and overwriting other duplicates with associations, which can be tedious.

**To Reproduce**
1. Have an existing data type archive (msl80.gdt attached for this case) opened
2. Parse C headers whose contents depend on types in the existing GDT
3. When examining the resulting GDT (opengl12), the bug described above will be evident 

**Expected behavior**
All of the dependencies should be associated in the new archive (opengl12) with the existing, associated archive (msl80)

**Screenshots**
From msl80:
![Screenshot 2022-08-08 123025](https://user-images.githubusercontent.com/368708/183499698-9e66c833-026c-4790-bb37-ca87600f15b5.png)

From opengl12:
![bug](https://user-images.githubusercontent.com/368708/183499969-70d15c21-69be-41ee-aa03-d24f2b5b39cf.png)

**Attachments**
[Headers.zip](https://github.com/NationalSecurityAgency/ghidra/files/9284544/Headers.zip)
[msl80.zip](https://github.com/NationalSecurityAgency/ghidra/files/9284549/msl80.zip)
[opengl12.zip](https://github.com/NationalSecurityAgency/ghidra/files/9284552/opengl12.zip) (bugged result)
[opengl.zip](https://github.com/NationalSecurityAgency/ghidra/files/9284586/opengl.zip) (the parser profile I made for it)

If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 13.2
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official GitHub distro

**Comment by ghidra1** [comment]
This is likely caused by the CParser's use of `DataType.copy` instead of `DataType.clone` and should be easily resolved.

**Comment by Schala** [comment]
Also somewhat related. Apologies if I need to make this a separate issue but with generated GDTs, is there a way to disable packing types by default?

**Comment by ghidra1** [comment]
>  is there a way to disable packing types by default?
I believe packing is disabled by default for structures when instantiated.  Although, the C-parser always enables packing for ones it produces (e.g., those we provide in data type archives) which is the correct thing to do when complete structure definition and its referenced types are known.
