### ISSUE TITLE
Issue when using JAVA_HOME_OVERRIDE, not working or using it wrong?

### ISSUE THREAD

**Issue by RedOctober45** [NationalSecurityAgency/ghidra#4523]
I am trying to update the JAVA_HOME_OVERRIDE variable in \support\launch.properties file to point to the Java JDK, per the Ghidra documentation.  However, with trying different path formats I can't seem to get it to work and I can't find any solutions online.  I'm not sure if I am using the wrong format as I cannot find any examples either.

I need to use this parameter because I am running headless on a system which cannot guarantee a Java install so my plan was to package the JDK folder with Ghidra and use JAVA_HOME_OVERRIDE to point to it.

Ghidra 10.1.2 on Windows 10.

**Comment by ryanmkurtz** [comment]
What value are you giving it?

**Comment by ryanmkurtz** [comment]
Keep in mind that you need some kind of Java on the PATH for Ghidra to launch.  It can be as old as Java 8.  The launch script will use that Java to launch Ghidra with the one you have defined in JAVA_HOME_OVERRIDE.  If you have no Java on the PATH, Ghidra will not launch.  This is outlined in the InstallationGuide.

**Comment by RedOctober45** [comment]
> What value are you giving it?

To test, this is what I am trying to use: "C:\Program Files\Java\jdk-17.0.2\bin" w/wo quotes on it.  It works fine when I add it to my system PATH so the Java package is good.

**Comment by RedOctober45** [comment]
> Keep in mind that you need some kind of Java on the PATH for Ghidra to launch. It can be as old as Java 8. The launch script will use that Java to launch Ghidra with the one you have defined in JAVA_HOME_OVERRIDE. If you have no Java on the PATH, Ghidra will not launch. This is outlined in the InstallationGuide.

Ah ok, I misunderstood then.  I will mess around with that.

**Comment by ryanmkurtz** [comment]
You can also just hardcode the path right into launch.sh/bat if you need to, bypassing all of the Java discovery stuff.

**Comment by RedOctober45** [comment]
Thanks for the help, that makes sense now.  So where is it stored once Ghidra gets a valid JDK path?  It looks like it is cached somewhere in windows?  For example, if I delete the Ghidra folder, unzip it again and copy the JDK folder back in then it still works.

**Comment by ryanmkurtz** [comment]
Once Ghidra successfully launches with a supported JDK, the path to that JDK gets stored to `~/.ghidra/.ghidra_<version>/java_home.save`.  Here is the logic and order of events that happen to find a supported JDK:

https://github.com/NationalSecurityAgency/ghidra/blob/aad60ecdd319f4db6e5cbafc0516db218e56988b/GhidraBuild/LaunchSupport/src/main/java/LaunchSupport.java#L150-L192
