### ISSUE TITLE
How can I determine all the top level Java packages available in Ghidra at runtime?

### ISSUE THREAD

**Issue by clearbluejar** [NationalSecurityAgency/ghidra#4524]
Hello,

I've been trying to resolve an issue using the excellent python project `pyhidra`, but I'm stuck on something.
https://github.com/dod-cyber-crime-center/pyhidra/pull/18#issuecomment-1212435519

How can I dynamically list which top level classes are available in Ghidra at runtime (specifically Headless runtime)?  

I tried to statically build a list of all the top level base Ghidra java packages with:

```
$ find /ghidra/ -name *src.zip -exec sh -c "zipinfo -1 {}" \; | grep -v "/." | sort | uniq -c | grep '/'
      1 SWIG/
      4 agent/
      3 db/
      1 decompiler/
      1 dist/
      2 docking/
      1 foundation/
      1 functioncalls/
      3 generic/
     52 ghidra/
      2 help/
      1 lib/
      1 log/
      1 mdemangler/
      1 org/
      1 pdb/
      1 resource/
      1 resources/
      1 src.META-INF/
      1 src.win32/
      1 src/
      1 util/
      2 utilities/
      1 utility/
```
But that list isn't perfect, and could be different a runtime. 

Perhaps all the Java runtime classes are added here during initialization?https://github.com/NationalSecurityAgency/ghidra/blob/f9463e600d318a74e81462656e4a87f3e598ddec/Ghidra/Framework/Utility/src/main/java/ghidra/GhidraLauncher.java#L87-L105

Is there any way to create that list through the FlatProgramApi?

**Comment by dev747368** [comment]
Seems like the better solution is to refactor the code in the pdb package to ghidra.something.something.pdb.???

**Comment by clearbluejar** [comment]
It would be easier to change the namespace, but the hope is not directly modify the Ghidra source Java files.

**Comment by clearbluejar** [comment]
I think I found it. I was somewhat conflating classes with packages, but I found a way to get the top level Java packages. 
Found this [example](https://www.geeksforgeeks.org/package-getpackages-method-in-java-with-examples/)
```
// Java program to demonstrate
// getPackages() method
  
public class Test {
    public static void main(String[] args)
    {
  
        // get the Packages using getPackages() method
        Package[] packages = Package.getPackages();
  
        // print all packages, one by one
        for (int i = 0; i < packages.length; i++) {
            System.out.println(packages[i]);
        }
    }
}
```

Running this basically gets what I need!

Top level packages list:
```python
{'java', 'decompiler', 'foundation', 'help', 'mdemangler', 'dc3', 'log', 'pdb', 'docking', 'javax', 'agent', 'sun', 'resources', 'com', 'util', 'generic', 'net', 'utility', 'db', 'edu', 'functioncalls', 'SWIG', 'ghidra', 'jdk', 'org', 'utilities'}
```

Cheers!
