### ISSUE TITLE
Plz help me. Thanks

### ISSUE THREAD

**Issue by TrongChuongDao** [NationalSecurityAgency/ghidra#4525]
![image](https://user-images.githubusercontent.com/96568661/184268696-42f6e6c4-c7cd-42c1-96ca-dafdfb131dd1.png)

**Comment by Hinara** [comment]
Check if you have a version of jdk superior or equal to 11, if you have one, then might be the installer which didn't do his job of setting the necessary.
In apps you should see something like
"Java(TM) SE Development Kit XX.X.X"
If not type Java JDK in yousearch browser and install version 11 or newer (should be 1.17~1.18 currently)
If it is you need to specify where was it installed
