### ISSUE TITLE
MIPS 32: Missing instructions

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4526]
**To Reproduce**
The following byte sequences fail to disassemble in MIPS 32 (little endian):
``F8 FC 21 7C`` 
``B8 0C 3F 7C`` 
``01 00 60 41``
``21 00 60 41``

**Expected behavior**
Capstone (and IDA) returns:
```
<CsInsn 0x0 [f8fc217c]: wrdsp $at, 0x3f>
<CsInsn 0x0 [b80c3f7c]: rddsp $at, 0x3f>
```

https://onlinedisassembler.com/odaweb/ (mips isa32r2) and IDA return
```
01 00 60 41 dvpe
21 00 60 41 evpe
```

**Environment (please complete the following information):**
Commit 2d51b95

**Comment by pjsoberoi** [comment]
I added the instructions.
![mips32](https://user-images.githubusercontent.com/60081609/184424716-f06552ff-f1d5-4c83-86b8-c6df5c662bd8.png)

I need to understand the what the instructions do before submitting a PR. 

[diff.txt](https://github.com/NationalSecurityAgency/ghidra/files/9329262/diff.txt)

**Comment by GhidorahRex** [comment]
How were you able to add the instructions without knowing what they did?

Anyways, I would caution against a simple PR for this. It's more than just the two instructions. I think the MIPS module is lacking the entire DSP instruction set, but I haven't had time to fully evaluate it.

**Comment by pjsoberoi** [comment]
> How were you able to add the instructions without knowing what they did?

I added disassembly for the above four instructions (see the attached diff). I have not added the SLEIGH implementation yet. Relevant docs: https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00374-2B-MIPS32DSP-AFP-03.01.pdf and https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00378-2B-MIPS32MT-AFP-01.12.pdf. 

> Anyways, I would caution against a simple PR for this. It's more than just the two instructions. I think the MIPS module is lacking the entire DSP instruction set, but I haven't had time to fully evaluate it.

Understood, I will hold off on submitting a PR.

**Comment by GhidorahRex** [comment]
You're definitely welcome to work on it! Sorry, I didn't want to suggest that, just that it's not as straightforward as adding the two instructions.

 If you want to work on the PR, I would put the instructions in a separate .sinc file, and add lines to the manual  .idx file. The manual was the same one I was looking at. You could just add these two instructions, or some additional ones that are missing too if you felt the need. I'm wondering if OP's binary has additional DSP instructions.

As far as what to do for the actual operation, I would suggest defining a pcodeop for each of these two instructions and pass in the appropriate registers. We would need a dspcontrol register added as well. If we need to flesh out the actual dspcontrol register values in the instructions we can always add that later.

**Comment by sad-dev** [comment]
I'm still in the middle of reversing the binary, but as far I can tell these are the only DSP instructions I have.

**Comment by GhidorahRex** [comment]
We've got something coming along internally for this. Should be released in the near future.
