### ISSUE TITLE
Decompiler:  Ignore type after NULL check

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4527]
**Describe the bug**
When malloc or use a  getter function for assigning a pointer you would do a NULL check on the pointer followed by error handling.
If its NULL and the compiler knows  its NULL at that point it might use that register to NULL other things.

```C
struct foo *x;
struct bar *y;

x =  get_foo();
if ((struct foo *)0 == x) {
    return;
}
y = get_bar();
if ((struct bar *)0 == y) {
    free(x);
    //  This is just "x = NULL", but decompiler will  use compiler's optimization and
    //  use the register that currently holds the value for "y", which is  known to be NULL
    x = (struct foo *)y;
}
// do something with x  and y
```

Don't know if this is really a bug or just a readability thing that can be ignored (so maybe just a feature request).
Would this  put the decompiler into a weird state where types conflict?
Could a NULL variable in that scope lose it's type information and just be a literal?

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: 11.0.10
 - Ghidra Version: 10.1.4
 - Ghidra Origin: official

**Comment by ghidracadabra** [comment]
From the code browser, Edit->Tool Options...->Decompiler->Display->Print 'NULL' for null pointers (near the bottom of the list)

I think you will get the effect you want if you check that box.  If not let me know.

**Comment by Wall-AF** [comment]
> From the code browser, Edit->Tool Options...->Decompiler->Display->Print 'NULL' for null pointers (near the bottom of the list)
> 
> I think you will get the effect you want if you check that box. If not let me know.

Even with this checked, `NULL` doesn't appear when using https://github.com/NationalSecurityAgency/ghidra/issues/4508 to fix mixed size pointers.

**Comment by mumbel** [comment]
@ghidracadabra  sorry for the delay, was AFK all last week

with my example, I see
```C
struct foo *x;
struct bar *y;

x =  get_foo();
if (x == NULL) {
    return;
}
y = get_bar();
if (y == NULL) {
    free(x);
    //  This is just "x = NULL", but decompiler will  use compiler's optimization and
    //  use the register that currently holds the value for "y", which is  known to be NULL
    x = (struct foo *)y;
}
// do something with x  and y
```
` x = (struct foo *)y;`  remains unchanged it looks like.  My concern is if `x` / `get_foo` were un-typed, and `y` / `get_bar` was typed, this assignment would make x of type bar and might cause false positive that are more difficult to track in larger functions where a user might use this information while setting prototypes or struct field types

**Comment by mumbel** [comment]
still seeing in 10.3                                                                                 
                                                                                                     
```                                                                                                  
struct foo *x;                                                                                       
struct bar *y;                                                                                       
                                                                                                     
x = get_foo();                                                                                       
if (!x) {                                                                                            
    return NULL;                                                                                     
}                                                                                                    
y = find_bar();                                                                                      
if (!y) {                                                                                            
    y = get_bar();                                                                                   
    if (y) {                                                                                         
        if (init_bar(y)) goto succeed;                                                               
        free(x);                                                                                     
        x = y;                                                                                       
    }                                                                                                
    free(x);                                                                                         
    x = NULL;                                                                                        
} else {                                                                                             
succeed:                                                                                             
    // tries to initialize y, but gets cast x                                                        
}                                                                                                    
return x;                                                                                            
```

**Comment by ghidracadabra** [comment]
Thanks for letting us know; I'll take a look.

**Comment by ghidracadabra** [comment]
I'm not sure I understand this example.  Where is the offending cast inserted?  It looks like the `x = y` assignment happens at a point where both `x` and `y` are non-null, so this might be a different issue.

**Comment by mumbel** [comment]
Yeah, you're right, it's not the same as the original.  I'll create a new issue if I come across again and it's more of a type mismatch than known null/const
