### ISSUE TITLE
Missing assignments from assembly in decompiled output

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4529]
**Describe the bug**
No decompiled output is generated for copying one structures elements to another, in this case, missing out the fact that when replacing an existing structure with the contents of a newly created one, 3 of the existing elements need to be kept.

I'm unsure if this is due to the fact that in the assembly (shown below) the register used to temporarily hold the value being copied is an extended register `EAX` and my code is using the `x86-16.?spec` configuration files.  If so, do I need to add these extended registers to any config files and how?
```
11c8:1c29 c4 5e 06      LES BX,[BP + pHashBlk]
11c8:1c2c 66 26 8b      MOV EAX,dword ptr ES:[BX + 0x32]
          47 32
11c8:1c31 66 89 46 ec   MOV dword ptr [BP + hashBlk.field26_0x32],EAX
11c8:1c35 66 26 8b      MOV EAX,dword ptr ES:[BX + 0x36]
          47 36
11c8:1c3a 66 89 46 f0   MOV dword ptr [BP + hashBlk.m_nCount],EAX
11c8:1c3e 66 26 8b      MOV EAX,dword ptr ES:[BX + 0x3a]
          47 3a
11c8:1c43 66 89 46 f4   MOV dword ptr [BP + hashBlk.field28_0x3a],EAX
```

**To Reproduce**
1. Load the provided file (created from the "Debug Function Decompilation" menu
2. Locate (and select) the assembly illustrated above
3. See no decompilation that should be something like:
```
hashBlk.field26_0x32 = pHashBlk->field26_0x32;
hashBlk.m_nCount = pHashBlk->m_nCount;
hashBlk.field28_0x3a = pHashBlk->field28_0x3a;
```

**Expected behavior**
To reproduce decompiled code akin to the above.

**Screenshots**
![image](https://user-images.githubusercontent.com/67698927/184840432-a2b098d5-fc54-483b-825b-4f70144a702c.png)

**Attachments**
[dragon_!IncreaseHashTableSize.zip](https://github.com/NationalSecurityAgency/ghidra/files/9349296/dragon_.IncreaseHashTableSize.zip)

**Environment (please complete the following information):**

 - OS: Windows 11
 - Java Version: 17.0.3.1
 - Ghidra Version: [e.g. 10.2-DEV
 - Ghidra Origin: locally built commit 0590f9336ee61f8c60a7a7f5423646eb5cb00861

**Comment by Wall-AF** [comment]
Unfortunately, whilst this fixed the example above, it doesn't for others where the function call is indirect.

Here's an example:
[dragon_Write_11e0_1a94.zip](https://github.com/NationalSecurityAgency/ghidra/files/9583379/dragon_Write_11e0_1a94.zip)

**Comment by ryanmkurtz** [comment]
@Wall-AF, would you mind creating a new ticket for this new issue you found (even if it's directly related)?
