### ISSUE TITLE
consider perform a goto action when symbol tree symbol is double clicked

### ISSUE THREAD

**Issue by Escapingbug** [NationalSecurityAgency/ghidra#453]
**Is your feature request related to a problem? Please describe.**
Currently, when a symbol in symbol tree is firstly selected, a goto action will be performed so disassembly and decompile view will display that symbol instantly. But once some scrolling is done in disassembly view, we can never go back that symbol again just by double-clicking that symbol as it is already selected.

I know that this might be intended as double-click expands what that symbol contains, but is really annoying to find a way to go back to the symbol we previously selected.

**Describe the solution you'd like**
Implement go back when double-clicking a symbol in symbol tree even if it is already selected.

**Describe alternatives you've considered**
A workaround is to add a "go to" in the menu shows up when right clicked, but that is not very intuitional.

**Comment by dragonmacher** [comment]
We should be able to improve upon this behavior.

In the meantime, a simple (perhaps obvious) workaround is the deselect the node (via Control-left-click) and then select it again.

**Comment by BhaaLseN** [comment]
My workaround is selecting the symbol next to it and then going back; doesn't need additional movements on the keyboard ;)

**Comment by mumbel** [comment]
@dev747368 is this GT-2383?

**Comment by dev747368** [comment]
not quite.  I feel your pain though.

**Comment by Hardcore-fs** [comment]
Ok, I did search, but obviously missed #453
it's common in Java with tables, there's a few more display glitches,  it's hardly anything to burst into tears about.

**Comment by ryanmkurtz** [comment]
Fixed by 14ee95c3959785889ef227450fd757300b67b0a3
