### ISSUE TITLE
[analyzeHeadless] More verbose loader output

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#4530]
**Is your feature request related to a problem? Please describe.**
The error message when the loader fails in analyzeHeadless could be improved to display more information about which loader was used. 

**Describe the solution you'd like**
The `ERROR REPORT` messages for loaders contain the type of loader that had the error.

**Describe alternatives you've considered**
N/A

**Additional context**
In particular (and possible a separate issue), in the logs below I suspect that the AutoLoader chose the `IntelHexLoader` instead of `MotorolaHexLoader`, but this is not evident from the log messages. Indeed, supplying `-loader MotorolaHexLoader` in the analyzeHeadless command allows loading to succeed.

```
analyzeHeadless /tmp tmp -import /tmp/test/demo.srec -processor ARM:LE:32:Cortex
...
INFO  IMPORTING: /tmp/test/demo/demo.srec (HeadlessAnalyzer)
ERROR REPORT: Error: No memory blocks were defined for file '/tmp/test/demo/demo.srec'. (HeadlessAnalyzer)
ERROR REPORT: Import failed for file: /tmp/test/demo/demo.srec (HeadlessAnalyzer)
```

**Comment by ryanmkurtz** [comment]
I'll have `AutoImporter` log what Loader it ended up using.
