### ISSUE TITLE
Typedef Editor

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4544]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to change the base `DataType` for a `TypeDef` and can't readily do so. 

**Describe the solution you'd like**
An editor window to edit the `TypeDef` like there is for composites and function signatures. 

**Describe alternatives you've considered**
Opening the python interpreter, creating a new `TypeDefDataType` to the new base type and using `DataType.replaceWith`. This gets old pretty quick.

**Comment by dragonmacher** [comment]
Relates to #3113

**Comment by ghidra1** [comment]
Modification of a typedefs base type is not currently permitted at the API level.  Allowing a datatype to change its size carries with it the risk that any uses of it may become broken and no longer fit within their varnode container (e.g., variables, memory data).  With the potential for widespread use of a single Typedef, the negative consequences of a typedef size change could be huge.  This is not to say a datatype-replacement is any safer but is allowed.   A single composite size change generally has a smaller impact over a primitive size change that could be associated a typedef.  

Done properly, this capability will require a Typedef API change and impact the TypedefDB implementation.

A Typedef editor should warn user if the base datatype size changes and restrict disallowed changes (TBD, e.g., pointer typedefs, use of dynamic base datatypes, etc.).

**Comment by astrelsky** [comment]
99% of the time I change a typedef is to fix the wrong size.

**Comment by ghidra1** [comment]
I stand corrected.  I did not realize `DataType.replaceWith` was on the public interface - Ugh.  There is quite a bit on the public `DataType` interface which should not be (e.g., change callbacks) - this may be one of them.  It's on my list to eliminate some of these at some point.   It is too easy to do something really bad for which there are no safeguards (e.g, replace integer typedef with dynamic typedef such as PngDataType).  If Typedef was intended to support this it should have a method `Typedef.setBaseDataType` - which is what I was considering above.

**Comment by astrelsky** [comment]
I see. I will definitely be more careful about using it. However, does the same not apply when editing a `Composite` which has been applied to the listing? It's size doesn't even need to change and you can see the markup is stale just by converting one of its components from an integer to a pointer.

**Comment by ryanmkurtz** [comment]
> I like doing bad things. Bad things you shouldn't be able to do are my favorite.

I like to turn off my computer by holding in the power button.  It's a real adrenaline rush.

**Comment by astrelsky** [comment]
> > I like doing bad things. Bad things you shouldn't be able to do are my favorite.
> 
> I like to turn off my computer by holding in the power button.  It's a real adrenaline rush.

You should try a hammer. It shuts down faster with just the right amount of force.

**Comment by ghidra1** [comment]
> I see. I will definitely be more careful about using it. However, does the same not apply when editing a `Composite` which has been applied to the listing? It's size doesn't even need to change and you can see the markup is stale just by converting one of its components from an integer to a pointer.

Yes, there can be fallout with composite changes but generally does not impact variable variable storage allocations.  That and there are no issues with it changing its stripes as could be done with a Typedef.  So its more a matter of how much badness could occur.  Typedefs will likey impact many more storage assignments than a structure.

**Comment by ghidra1** [comment]
@astrelsky Attached is a Ghidra Script `ReplaceTypedefScript` which will interactively facilitate replacing an existing Typedef selected in the Data Type Tree with a new one using a selected base datatype.  NOTE: error handling could be improved somewhat and settings are not set on new typedef.  Would this satisfy your need?  At this point I am reluctant to make Typedef mutable.
[ReplaceTypedefScript.txt](https://github.com/NationalSecurityAgency/ghidra/files/9779340/ReplaceTypedefScript.txt)

**Comment by ghidra1** [comment]
The DataTypeManager knows what types make use of a Typedef (e.g., parent list).  Due to the potential ripple affects of a change (e.g., size/packing/alignment), the replacment approach or a fully integrated approach is required.  Slipping in a modified base datatype is inadequate on its own.  The ripple affects can cause other structures to change there size/packing/alignment and the dominos continue to fall.  `DataTypeManager.replaceDataType` for direct use by Data and Variables is a brute force search which is unfortunate (no index).  While a properly integrated approach is feasible it would entail a larger effort at a low priority.

**Comment by astrelsky** [comment]
Considering the concerns with altering a typedef and the limited number of cases where it would be necessary to actually alter it instead of replacing it, I think that an editorial for this is not worth the effort to do properly.
