### ISSUE TITLE
ComboBox widgets don't detect key presses 1-9 since Ghidra 10.1

### ISSUE THREAD

**Issue by shocoman** [NationalSecurityAgency/ghidra#4545]
I'm sorry if this was already addressed, but I din't find anything.
I found that ComboBox does not detect 1-9 key presses. One of those widgets is located in the "Storage Address Editor" window (the "Location" column).
![storageAddressEditor](https://user-images.githubusercontent.com/8329446/185987844-b4a33db7-af00-4d27-ada8-3b6f8e31875c.png)

This widget should support typing-in the item names. But when I enter “r2”, for example, the cursor stays at the “r0” position. By the way, NumPad keys work correctly. 

 I checked several Ghidra versions and found that this menu has been broken since Ghidra 10.1. I looked at the changelog and got to the issue #2811  which introduced new action maps for keys 1-9 inside menus. Compiling Ghidra without [those](https://github.com/NationalSecurityAgency/ghidra/blob/92b15fed6ef28cc08aad51c86305c893db66454d/Ghidra/Framework/Docking/src/main/java/docking/menu/keys/MenuKeyProcessor.java#L39) lines has solved the problem. 

 If it’s not supposed to be a feature, I may propose two solutions. Either remap those 1-9 actions using modifier keys if it’s possible (for example, to “Ctrl+1” or “Alt+1”) or just filter out menus that implement the “javax.swing.plaf.basic.BasicComboPopup” interface ([here](https://github.com/NationalSecurityAgency/ghidra/blob/92b15fed6ef28cc08aad51c86305c893db66454d/Ghidra/Framework/Docking/src/main/java/docking/menu/keys/MenuKeyProcessor.java#L55)). For some reason the offending keymap actions don’t work inside of them anyway.

**Comment by dragonmacher** [comment]
Nice diagnostic work.  We should be able to fix this pretty easily.  I think disabling this feature for combo boxes makes the most sense.

**Comment by astrelsky** [comment]
> Nice diagnostic work.  We should be able to fix this pretty easily.  I think disabling this feature for combo boxes makes the most sense.

Disabling which feature? The original functionality of the 1-9 numpad or the feature of the change that broke it?

**Comment by dragonmacher** [comment]
> > Nice diagnostic work.  We should be able to fix this pretty easily.  I think disabling this feature for combo boxes makes the most sense.
> 
> Disabling which feature? The original functionality of the 1-9 numpad or the feature of the change that broke it?

yes

**Comment by astrelsky** [comment]
> > > Nice diagnostic work.  We should be able to fix this pretty easily.  I think disabling this feature for combo boxes makes the most sense.
> > 
> > Disabling which feature? The original functionality of the 1-9 numpad or the feature of the change that broke it?
> 
> yes

No! Please don't disable the numpad keys I use them all the time.

It was early when I wrote that question :sweat_smile:

**Comment by dragonmacher** [comment]
I have a fix ready.  It will allow the combo box popup to work as it used to, as suggested by the user.  Menu bar menus and context menus will be unaffected by this change.
