### ISSUE TITLE
Add Gradle wrapper in the repository

### ISSUE THREAD

**Issue by lacasseio** [NationalSecurityAgency/ghidra#455]
**Is your feature request related to a problem? Please describe.**
It's not obvious which version of Gradle the project should be using as well as makes all development configuration more complicated.

**Describe the solution you'd like**
The[ Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) should be added to the repository. For security concern, always [verify the checksum of the wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification) when accepting PR that includes one.

**Describe alternatives you've considered**
The alternative, which is not providing a wrapper. Adds maintenance burden on the users and possibly on the team when answering questions regarding Gradle version to use. It's also the most idiomatic way of using Gradle.

**Additional context**
Feel free to raise any concern about using the Wrapper. The Gradle team is happy to address them.

**Comment by lacasseio** [comment]
See PR: https://github.com/NationalSecurityAgency/ghidra/pull/456

**Comment by ryanmkurtz** [comment]
Closing for now.  See [comment in pull-request](https://github.com/NationalSecurityAgency/ghidra/pull/456#issuecomment-512236529) for more info.
