### ISSUE TITLE
Ghidra Table Caching Previous Table Sort Inappropriately

### ISSUE THREAD

**Issue by H0r53** [NationalSecurityAgency/ghidra#4552]
I created the following Ghidra script based on a [previous issue](https://github.com/NationalSecurityAgency/ghidra/issues/4435)
```
public class ImportAddressTrace extends GhidraScript {

	@Override
	public void run() throws Exception {
		List<Address> list = new ArrayList<>();		

		try {
			File addrFile = askFile("Trace File", "Import");
			Scanner myReader = new Scanner(addrFile);
			while (myReader.hasNextLine()) {
				String addr = myReader.nextLine();
				if (addr.length() > 0) {
					list.add(toAddr(addr));					
				}
			}
			myReader.close();
		} catch (FileNotFoundException e) {
			System.out.println("An error occurred.");
			e.printStackTrace();
		}

		PluginTool tool = state.getTool();
		TableService tableService = tool.getService(TableService.class);
		Address[] addresses = list.toArray(Address[]::new);

		Swing.runNow(() -> {
			AddressArrayTableModel model = new AddressArrayTableModel(getScriptName(),
					state.getTool(), currentProgram, null);
			model.setTableSortState(TableSortState.createUnsortedSortState());
			model.setAddresses(addresses);

			TableComponentProvider<Address> tableProvider =
					tableService.showTableWithMarkers("Address Trace", "GhidraScript", model,
							Color.GREEN, null, "Script Results", null);
			tableProvider.installRemoveItemsAction();
		});
	}
}
```
The script above has been working perfectly for me. It allows for importing an address/PC trace and following along in Ghidra by simply navigating up and down on the generated table. However, I seem to have accidentally clicked one of the column headers which sorts the column. Clearly this corrupts the idea of an address trace because the table rearranges the order of the instructions.

The issue is now I cannot get Ghidra to run the above script and generate a table without applying a column sort! I've tried reloading the project and restarting my machine and each time I run the ImportAddressTrace script the table is automatically sorted after it loads. I can see for a brief moment that the table is unsorted but then the sort is applied after loading the data.

It appears that Ghidra is caching a previous column sort state and applying it each time I run the script, even though I'm specifying `model.setTableSortState(TableSortState.createUnsortedSortState());`.

How can I tell Ghidra to not sort the table and don't apply a previous column sort to a new table? This behavior has ruined my script.

Ghidra Version 10.2, Build DEV

**Comment by dragonmacher** [comment]
I don't recall if there is a way to signal to remove previously saved table sort settings.  For now, you should be able to control click click the sorted column to remove the sort.   Once the sort is removed, go to the **Front End** and select `File -> Save Project`.  This should use the current unsorted table as the preferred sort setting.

**Comment by H0r53** [comment]
When I CTRL + Click the column it appears to have the same behavior as right clicking the column. A dialog is shown with the following options:
```
Add/Remove Columns
Column Settings
```
In my case, Column Settings is grey'd out. I'm not seeing an option to remove the column sort.

**Comment by dragonmacher** [comment]
So, depending on your setup, you may need to press the `Alt` or `Command` key, just to the left of the spacebar in order for this to work.

**Comment by H0r53** [comment]
You are my hero :')
Thank you for the always responsive and professional help!
