### ISSUE TITLE
Decompiler gets stuck on large functions

### ISSUE THREAD

**Issue by zwyz** [NationalSecurityAgency/ghidra#4558]
**Describe the bug**
For some functions, the decompiler runs for hours without ever decompiling them.

**To Reproduce**
1. Download the attached file and open it in Ghidra.
2. Run auto-analysis with the default options.
3. Try to decompile `FUN_002e7b7c`.
4. The decompiler runs, but seems to never finish.

**Screenshots**
<img width="398" alt="image" src="https://user-images.githubusercontent.com/83980260/187055123-44460871-bf04-47d9-a51b-df4f78167e46.png">

**Attachments**
[osrs_207_4_arm64.zip](https://github.com/NationalSecurityAgency/ghidra/files/9439003/osrs_207_4_arm64.zip)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.1
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official

**Comment by homes410** [comment]
Yes. It's expected behavior. and nobody will fix it.
Cheers

**Comment by astrelsky** [comment]
Can reproduce in the master branch. I'm attempted to force a debug decompilation dump but it didn't work since it gets stuck. My best guess is it doesn't like this type of switch table.

**Comment by maskelihileci** [comment]
I'm having a similar problem right now.
