### ISSUE TITLE
How to go to a virtual address that corresponds to a given file offset?

### ISSUE THREAD

**Issue by mmm29** [NationalSecurityAgency/ghidra#4559]
Hello!
I often search matched YARA strings in Ghidra (yara outputs only file offset), but the virtual address is not always equal to `image_base + file_offset`. I often have to convert it manually depending on section which contains the code. 
It would be very helpful to have a feature to go to a virtual address that corresponds to a given file offset, like you can do it in x64dbg (CTRL + SHIFT + G). Is it possible?
Thanks!

**Comment by ryanmkurtz** [comment]
In the upcoming 10.2 release you'll be able to enter a file offset in the goto dialog. You'll also be able to add a file offset column to the Listing. These features are available now in the master branch.

**Comment by Wall-AF** [comment]
> In the upcoming 10.2 release you'll be able to enter a file offset in the goto dialog. You'll also be able to add a file offset column to the Listing. These features are available now in the `master` branch.
> 
> Implemented in [eb324a2](https://github.com/NationalSecurityAgency/ghidra/commit/eb324a2b206fa8768c5d0aa01f9ce4123dd27400)

Not available for Windows NE files!

**Comment by ryanmkurtz** [comment]
Yea, the feature requires the loader to use the `FileBytes` API when creating memory blocks.  The `NeLoader` is not currently doing that:
https://github.com/NationalSecurityAgency/ghidra/blob/2536099c0eb2683ee0e416a127f8a8795f8de853/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/NeLoader.java#L94-L97

**Comment by Wall-AF** [comment]
Questions:
1. Can this be rectified?
2. If so, how?
3. How can it be retro-fitted to an already loaded application suite?

Not much, I know!!!

**Comment by ryanmkurtz** [comment]
I need to dig into NeLoader more to see where the byte are manipulated.  Maybe it's just in one block and all the others can be creating via the `FileBytes` mechanism.

I don't think you can retro-fit it into an already imported program easily.

**Comment by class101** [comment]
Thank you for this feature, it is very very very very good :) :heart: :heart: :heart: :heart: :heart:
