### ISSUE TITLE
Symbol Table Corruption: editing symbol name introduces bogus association

### ISSUE THREAD

**Issue by robertzak133** [NationalSecurityAgency/ghidra#4566]
**Describe the bug**
sometimes the symbol table is corrupted during the process of assigning new names to functions and data.

Specifically, updating the name of a function/data always seems to correctly update that function/data name, but, occasionally, it also associates another (unrelated) function/data name to the same label.  Comes to light on inspection, or in finding a symbol associated with two or more functions.

**To Reproduce**
Steps I took to reproduce the behavior:
0. Open a highly annotated project based on MIPS32 binary with symbol table size of ~170K  
1. Edit the name, argument names, or arg types of a given symbol (e.g. "get_video_duration_from_enum()")
2. (some time later) Open c-source code inspector to list another function which should not call "get_video_duration_from_enum()" ; but should call another, unrelated function, say "appAWBBALGLib_WBParamSet()" -- see Photo1 screenshot.  Note highlighted (incorrect) call to "get_video..". 
3. Double click on "get_video_duration_from_enum()", which takes you to a different function (the correct one) "appAWBBALGLib_WBParamSet()" -- see Photo2
4. Examine symbol table and note that get_video_duration_from_enum() has two associated functions, the correct one at 0x8005d394; and an incorrectly associated function at 0x8000f4f4

**Expected behavior**
I expect edits to function and data names to effect only the edited symbol, and not create new, incorrect associations. 

**Screenshots**
See below

**Environment (please complete the following information):**
 - OS: Windows 10 21H1 19042.1889
 - Java Version: Oracle Version 8, Update 341
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official GitHub distro

**Additional context**
~4 MB MIPS-32 binary; symbol table size: ~170K

The extent of this bug seems limited, and I seem to be able to fix the inconsistencies by removing unwanted associations with the symbol table editor. 

![Photo1](https://user-images.githubusercontent.com/67118665/187727341-e6d342bf-2073-49a2-a71e-65339d66c244.png)
![Photo2](https://user-images.githubusercontent.com/67118665/187727346-5ef8ddf6-c35f-4e40-8fcd-3d9c66cef1b5.png)
![Photo3](https://user-images.githubusercontent.com/67118665/187727348-37f072ef-e290-43b8-b269-04b6c9b595c0.png)

**Comment by ghidra1** [comment]
@robertzak133 The function at 8005d394 is a thunk function for the one at 8000f4f4 and would normally carry the same name and signature.  It is possibly that the function was improperly marked as a thunk.  Can you show the assembly code at 8005d394 ?  A simple thunk just jumps to the thunked-function (e.g., trampoline function).  On occassion, the thunk is not a thunk but just looks like one.  If need be, the tunk relationship may be broken by clearing the thunked-function setting on the function at 8005d394.

**Comment by robertzak133** [comment]
@ghidra1 Thanks for quick response.  Yeap.  This is a simple (jump only) thunked-function -- see screen shot below. 

But there's still something fishy going on.   I.e. at one time the thunked function was correctly labeled "appAWBBALGLib_WBParamSet()", but somehow was later incorrectly labeled, "get_video_duration_from_enum()" -- not by me editing the label on the thunked function.  

![Photo4](https://user-images.githubusercontent.com/67118665/187751101-d827bcb3-ffae-40d1-9b7f-346c4901cb7b.png)

**Comment by ghidra1** [comment]
@robertzak133 in your code snippet above it appears a new name was assigned to the thunk and not the thunked function - which is permitted but possibly unintential.  It may be that the rename function action in the decompiler action did not detect and handle the thunk case properly resulting in its being renamed (if this is the case we should fix it).  A thunk with a default name will always mirror the name of its thunked-function.  A thunk may be renamed which will permit its name to differ from its thunked function.  Occasionally we see an imported symbol fall on the thunk and not the thunked-function, or possibly a different name on each.  Anything is possible, so sorting out the thunk and its naming is just part of the process.  If both names originated from the original import you may want to check a clean import prior to any analysis.

It was unclear in your original post if the function renaming from within the decompiler listing was renaming the thunk - which it should not.  Also keep in mind that a thunk may thunk another thunk.  Check the XREFs (this is cut off in your screenshot) for any thunk XREF to your thunk.

It is rather confusing without the sample in-hand and see the state before and after a rename action.  Prior to analysis (clean import) where do the symbols `get_video_duration_from_enum` and `appAWBBALGLib_WBParamSet()` reside in memory, assuming that is where they originated from?  Before the rename, what thunk relationships exist that involve the functions in question?

**Comment by robertzak133** [comment]
@ghidra1 just to be clear, none of these symbols existed in the import.  I started with a completely unlabeled binary and added all the symbol names in by hand. Yes, there are a lot of them now, and yes it took a long time.  Which is one of the reasons I'm concerned about inconsistencies in the database.

I do all of my renaming in the decompiler window.  So, yes, I think that somehow these edits are leaking into places they shouldn't.  I have no idea how.  I just see occasional cases (like the one I documented), where symbols that used to be correct, now are not.  I fix them as they come up, but I'd feel safer if the symbol database were more stable :/

**Comment by ghidra1** [comment]
I blieve the issue (not reflected by issue title) is how decompiler actions are incorerctly applied to thunk functions instead of the underlying thunked-function.  When determining the function to be modified the following fuction trversal logic must be added to the action's function determination:
```
// Ignore default thunks
		while (f.isThunk() && f.getSymbol().getSource() == SourceType.DEFAULT) {
			f = f.getThunkedFunction(false);
		}
```
