### ISSUE TITLE
Cropped text field in Data Type Chooser Dialog

### ISSUE THREAD

**Issue by jroimartin** [NationalSecurityAgency/ghidra#4577]
**Describe the bug**
The text field in the Data Type Chooser Dialog is cropped.

**To Reproduce**
1. Open a binary in CodeBrowser
2. Go to a function
3. In the Decompile window, retype a variable
4. The Data Type Chooser Dialog shows only part of the text field

**Expected behavior**
The layout of the Data Type Chooser Dialog should be shown correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1223476/188411699-add362a6-caf0-464f-908f-ebafa69f4dbf.png)

**Attachments**
None.

**Environment**
 - OS: Debian GNU/Linux bullseye (stable)
 - Desktop Environment: Gnome 3.38.5 (wayland and Xorg)
 - Java Version: Java 11 OpenJDK
 - Ghidra Version: 10.1.5
 - Ghidra Origin: Official GitHub distro

Also,

 - OS: Debian GNU/Linux bullseye (stable)
 - Desktop Environment: Gnome 3.38.5 (wayland and Xorg)
 - Java Version: Java 17 OpenJDK
 - Ghidra Version: master branch (5593df495c44cddcfe1c28a666d5d250f04b248d)
 - Ghidra Origin: GitHub repo 

**Additional context**
I could **not** reproduce this issue in:
- Windows 10 + Java 17 Temurin + Ghidra 10.1.5
- Debian bullseye + KDE 5.20.5 + Java 11 OpenJDK + Ghidra 10.1.5

**Comment by jroimartin** [comment]
The issue is also reproducible in Ubuntu 22.04 (default installation) with Java 11 OpenJDK and Ghidra 10.1.5.

**Comment by ryanmkurtz** [comment]
Similar to #1506 and likely fixed.  I will test tomorrow to confirm.

**Comment by jroimartin** [comment]
Yes and I can confirm that the severity varies from dialog to dialog. Here you have some more examples to check that the fix works:

![image](https://user-images.githubusercontent.com/1223476/188813966-33b43bfe-64d6-48c1-a94e-4bf64bf6a04f.png)

(The text field is slightly cut off at the bottom)

![image](https://user-images.githubusercontent.com/1223476/188814171-d85a991e-3f4f-4cc0-a0cf-ad3751d437c9.png)

(Both the progress bar and the sand clock are cut off at the bottom)

**Comment by ryanmkurtz** [comment]
> Similar to #1506 and likely fixed. I will test tomorrow to confirm.

I have confirmed this is **not** fixed in 10.2-DEV.

![image](https://user-images.githubusercontent.com/5378554/188916441-d4c7f18c-9c9c-426a-9290-8df7e42be2ab.png)

**Comment by ryanmkurtz** [comment]
Fixed by 20c3374b187102cb00cb08b34f6a486c0fb3b026
