### ISSUE TITLE
Ghidra is freezing in welcome view.

### ISSUE THREAD

**Issue by usaribbon** [NationalSecurityAgency/ghidra#4579]
Dear ghidra's developper.

Hello.
My ghidra is freezing from welcome view. (more than 10 mins...)
I could run other PCs but not this one.
Do you know hot to solve this or know to find error log?

Best Regards,

![スクリーンショット 2022-09-06 18 39 35](https://user-images.githubusercontent.com/2094358/188602237-07b087bc-19aa-4143-a331-fba82c5a6bb7.png)
![スクリーンショット 2022-09-06 18 37 22](https://user-images.githubusercontent.com/2094358/188602247-d0ce9d6b-2d94-49ef-a754-7d1415c5de0d.png)

**Comment by ryanmkurtz** [comment]
What linux distro and window manager is that?
Can you attach the results of jstack when its in this bad state?

```
jstack <pid>
```

A quick way to get the pid of a running java projcess is with the `jps` command.

**Comment by usaribbon** [comment]
Hi, ryanmkurtz.
Thank you for your reply.

I run my ghidra on docker ubuntu / VCN viewer.
I attached a result of jstack and jps.

<img width="659" alt="スクリーンショット 2022-09-07 12 10 46" src="https://user-images.githubusercontent.com/2094358/188780450-ba7f28cc-f14f-4541-b47e-a916087516bc.png">

I'd like to run Ghidra on docker ubuntu because I have many devices and want to run Ghidra on them without any custom.

Thank you for your support.

Regards,
Minami

**Comment by usaribbon** [comment]
Hi

I restarted my ghidra and jstack
（sorry for not text but images...）

<img width="1019" alt="スクリーンショット 2022-09-07 12 44 11" src="https://user-images.githubusercontent.com/2094358/188784383-3f2dc1a8-f6a1-4c6f-9459-8dc25e883688.png">
<img width="1008" alt="スクリーンショット 2022-09-07 12 44 46" src="https://user-images.githubusercontent.com/2094358/188784422-95ed665d-02af-483e-bbf6-2b04cddbb6bf.png">
<img width="1007" alt="スクリーンショット 2022-09-07 12 45 08" src="https://user-images.githubusercontent.com/2094358/188784552-6b5b8c2b-8291-4683-a0dc-812d042216b5.png">
<img width="1012" alt="スクリーンショット 2022-09-07 12 45 32" src="https://user-images.githubusercontent.com/2094358/188784594-88ef4712-ab9e-407a-b1c7-f2057cf58ec6.png">
<img width="1011" alt="スクリーンショット 2022-09-07 12 46 17" src="https://user-images.githubusercontent.com/2094358/188784665-84d10a57-b992-43ee-a048-349a971dfac2.png">

**Comment by ryanmkurtz** [comment]
Thank you, i see some clues in there.  Could you please attach your `~/.ghidra/.ghidra_<version>/application.log` (or screenshots of any error messages/stack traces you see in there)?

**Comment by usaribbon** [comment]
Hello. Thank you for your support.
I will attach application.log
[application.log](https://github.com/NationalSecurityAgency/ghidra/files/9504627/application.log)

**Comment by dragonmacher** [comment]
@usaribbon I took a peek at the log file.  There are exceptions in there that should not be possible unless you have modified Ghidra's source code.    Have you made any mods to Ghidra's source code?  Have you installed an extensions?

**Comment by ryanmkurtz** [comment]
Also, have you added any new JVM arguments?  

Does a fresh Ghidra 10,1.5 installation work?

**Comment by usaribbon** [comment]
Hello, I didn't install any extentions and modify source code...

Here is my Dockerfile.
I installed ghidra_10.0_PUBLIC_20210621 and Java JDK11.


```
FROM dorowu/ubuntu-desktop-lxde-vnc

RUN mkdir /root/firmusa/
RUN wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0_build/ghidra_10.0_PUBLIC_20210621.zip -O /root/firmusa/ghidra_10.0_PUBLIC_20210621.zip
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
RUN apt-get update && apt-get install -y zip unzip
RUN unzip /root/firmusa/ghidra_10.0_PUBLIC_20210621.zip -d /root/firmusa/
RUN apt-get install -y openjdk-11-jdk openjdk-11-jre make gcc g++
RUN echo 'PATH="$PATH:/usr/lib/jvm/java-11-openjdk-amd64/bin"' >> /root/.bashrc`

**Comment by ryanmkurtz** [comment]
Before I try to recreate your environment, can you please try Ghidra 10.1.5?

**Comment by ryanmkurtz** [comment]
Actually I went ahead and recreated your environment with the steps you outlined and I didn't run into any issues:

![image](https://user-images.githubusercontent.com/5378554/189167962-02d16264-1523-4812-80eb-d1ff21e21f58.png)

**Comment by usaribbon** [comment]
@ryanmkurtz Tnank you for your feed back.
It's surprising...
Do you use windows/Mac?
I use M1 Mac.

**Comment by ryanmkurtz** [comment]
My test was on an x86 Ubuntu 22.04 VirtualBox VM running on a Windows 11 PC.

**Comment by ryanmkurtz** [comment]
Are you running Docker under Rosetta 2?  Does your container think it's running on x86?

**Comment by ryanmkurtz** [comment]
I again used the docker steps you outlined on an M1 and didn't have the issue.  I'm not sure what more I can do at this point.

**Comment by usaribbon** [comment]
Thank you for you all

Finally I could run Ghidra on my docker.
I was able to run these on Windows11 and Ubuntu.  Only M1 Mac was fault to run.

Thank you for your support.
