### ISSUE TITLE
GFileSystem text file provider

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#4580]
**Is your feature request related to a problem? Please describe.**

In some of the filesystem loaders I've had to deal with, a few files I had to process were either compiled resources or binaries that aren't really bytecode but just tokenized data.  The `View as Text` menu entry in the filesystem tree isn't that good to display structured text (for which a monospace font would work better and maybe syntax highlighting could be added too).

**Describe the solution you'd like**

I was wondering if a text counterpart for `GIconProvider` could be added.  For some common file types for which this can be useful, think Android compiled XML resources, Windows installer property files, etc.  Adding the interface would mean that only filesystem implementers with specific needs can add this without changing any other code.

**Describe alternatives you've considered**

Right click, `Export...`, and opening the file in another editor is what I'm doing right now. It works but the workflow could be better...

**Additional context**

If there's any interest in this, I'm willing to give it a shot at doing the first implementation and submit it as a PR, or if you prefer to do it yourself, that's fine too - keep in mind that people might want to use something like https://github.com/bobbylight/RSyntaxTextArea instead of a plain `JTextArea` component to perform syntax highlighting themselves and (most probably) to use a monospaced font. For that, asking only for a `String`/`ByteBuffer`/`StringReader` to show is just half of the solution.

**Comment by ryanmkurtz** [comment]
We will discuss this and get back to you with further direction...thanks!

**Comment by ryanmkurtz** [comment]
Several years ago I tried incorporating RSyntaxTextArea into our basic GhidraScript text editor and I found it to not work for us for some reason...I wish I could remember why.  Maybe it was an issue with the autocomplete feature, which wouldn't apply here.

**Comment by dev747368** [comment]
Check out the FSBFileHandler interface added in 3f86719c0b441f89e88502aa50534da5076df9f0.

This should give you the tools to do this now.
