### ISSUE TITLE
xul.pdb fails to load

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#4584]
**Describe the bug**
`FileNotFoundException` when trying to load xul.pdb for xul.ddl

**To Reproduce**
1. Download https://ftp.mozilla.org/pub/firefox/nightly/2022/09/2022-09-04-09-39-56-mozilla-central/firefox-106.0a1.en-US.win64.zip
2. Load xul.dll from that zip file into Ghidra
3. Have Ghidra download the pdb using the mozilla symbol server
4. Try to load that pdb
5. Get  `java.io.FileNotFoundException: C:\symcache\000admin\ghidra_cab_extract_tmp_1662667546020 (The system cannot find the 
path specified)`

**Expected behavior**
The PDB should load

**Environment (please complete the following information):**
 - OS: Window 10
 - Java Version: 11.0.2
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official build

**Comment by dev747368** [comment]
Could you verify that the 000admin subdirectory exists in the c:\symcache directory?  If its missing, try creating it and attempting the operation again.

**Comment by jrmuizel** [comment]
the `000admin` directory did not exist. After creating importing `xul.pdb` got further along but did not succeed because of running out of heap space.

**Comment by ghizard** [comment]
We know that Ghidra has issues with large program/PDB combinations.  See #2485.
We are making some strides towards rectifying these issues, but it is taking some time.
Check #1997 about how to increase the memory in your JVM. It might take more than you might think or have to process xul.

**Comment by dev747368** [comment]
If the info in ghizard's reply (about memory) didn't help, please re-open this issue.
