### ISSUE TITLE
how to handle redirect to raw.githubusercontent.com during girdle initial run certificate-wise

### ISSUE THREAD

**Issue by user4856vw** [NationalSecurityAgency/ghidra#4585]
Hello support forum,
I am trying to build Ghidra with extended amount of nodes supported in graph view using Cygwin and upon attempt to run init run of girdle I get certificate error like this:

gradle -I gradle/support/fetchDependencies.gradle init
URL: https://github.com/NationalSecurityAgency/ghidra-data/raw/Ghidra_10.1.5/Fun
ctionID/vs2012_x64.fidb
   Connecting...
   Connection error! javax.net.ssl.SSLHandshakeException: PKIX path building fai
led: sun.security.provider.certpath.SunCertPathBuilderException: unable to find
valid certification path to requested target
   Connecting (2/3)...
   Connection error! javax.net.ssl.SSLHandshakeException: PKIX path building fai
led: sun.security.provider.certpath.SunCertPathBuilderException: unable to find
valid certification path to requested target
   Connecting (3/3)...
   Connection error! javax.net.ssl.SSLHandshakeException: PKIX path building fai
led: sun.security.provider.certpath.SunCertPathBuilderException: unable to find
valid certification path to requested target

running it with debug on I saw that it is at redirect to raw.githubusercontent.com where certificate failure happens. I have ca-certificates packages from Cygwin installed properly. 

How should this be handled ?

**Comment by ryanmkurtz** [comment]
What java version are you using?

**Comment by user4856vw** [comment]
> What java version are you using?

per java --version:
java 18.0.1.1 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

**Comment by dev747368** [comment]
Could you try something in jshell in your cygwin env?

Run "jshell", and then paste this snippet:

```java
void jget(String url) {
	try (InputStream is = new URL(url).openStream()) {
		long byteCount = is.transferTo(OutputStream.nullOutputStream());
		System.out.println("Read " + byteCount + " bytes");
	}
	catch (Throwable th) {
		th.printStackTrace();
	}
}
```

and then paste this:
```java
jget("https://github.com/NationalSecurityAgency/ghidra-data/raw/Ghidra_10.1.5/FunctionID/vs2012_x64.fidb")
```

You should get a "Read nnnnnn bytes" result, or an exception stack trace.

**Comment by user4856vw** [comment]
> Could you try something in jshell in your cygwin env?

> You should get a "Read nnnnnn bytes" result, or an exception stack trace.

Yes, it is exception stack trace, pretty close to the  one  in girdle:

 javax.net.ssl.SSLHandshakeException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:371)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:314)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:309)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.
checkServerCerts(CertificateMessage.java:1351)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.
onConsumeCertificate(CertificateMessage.java:1226)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.
consume(CertificateMessage.java:1169)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396
)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext
.java:480)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext
.java:458)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext
.java:201)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)

        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:15
00)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocke
tImpl.java:1415)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl
.java:450)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl
.java:421)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsCl
ient.java:578)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnecti
on.connect(AbstractDelegateHttpsURLConnection.java:183)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0
(HttpURLConnection.java:2887)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(
HttpURLConnection.java:2796)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0
(HttpURLConnection.java:1927)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(
HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputS
tream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1161)
        at REPL.$JShell$11.jget($JShell$11.java:7)
        at REPL.$JShell$12.do_it$($JShell$12.java:5)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Dire
ctMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectE
xecutionControl.java:209)
        at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteE
xecutionControl.java:116)
        at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectE
xecutionControl.java:119)
        at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.processComm
and(ExecutionControlForwarder.java:144)
        at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.commandLoop
(ExecutionControlForwarder.java:262)
        at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControl(Util.jav
a:77)
        at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControlAndIO(Uti
l.java:138)
        at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.main(RemoteExe
cutionControl.java:70)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed:
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find vali
d certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.
java:388)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXVal
idator.java:271)
        at java.base/sun.security.validator.Validator.validate(Validator.java:25
6)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509Trus
tManagerImpl.java:231)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X5
09TrustManagerImpl.java:132)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.
checkServerCerts(CertificateMessage.java:1335)
        ... 31 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to
 find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Sun
CertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBui
ld(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.ja
va:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.
java:383)
        ... 36 more

**Comment by dev747368** [comment]
Does jshell (with the jget snippet) work outside of cygwin, if just executed from a windows cmd line?

**Comment by user4856vw** [comment]
> Does jshell (with the jget snippet) work outside of cygwin, if just executed from a windows cmd line?
No, the same stracktrace:

jget("https://github.com/NationalSecurityAgency/ghidra-data/raw/Ghidra_10.1.5/FunctionID/vs2012_x64.fidb")
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1351)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1226)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1169)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        ....

**Comment by dev747368** [comment]
Ok.  I would try another jdk as your current one doesn't seem to be working.

**Comment by user4856vw** [comment]
> Ok. I would try another jdk as your current one doesn't seem to be working.

It appears to me that this is not the matter of jdk, as if something would be wrong with it, but the matter of certificate handling. There is SSLpoke test class, available here at GitHub, and the result of trying it on raw.githubusercontent.com is such:

java SSLPoke raw.githubusercontent.com 443
sun.security.validator.ValidatorException: PKIX path building failed: sun.securi
ty.provider.certpath.SunCertPathBuilderException: unable to find valid certifica
tion path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.
java:388)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXVal
idator.java:271)
        at java.base/sun.security.validator.Validator.validate(Validator.java:25
6)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509Trus
tManagerImpl.java:231)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X5
        ...
So, if you say that it is matter of jdk -- what is your outcome of the check and what is the certificate chain for java SSLPoke raw.githubusercontent.com 443 and what is the certificate chain to the site and then valid certificate of it ?

**Comment by dev747368** [comment]
It successfully connects to that hostname.

Looking at the source code for SSLPoke, it winds up doing the same thing the jshell snippet I showed you does.

Github's SSL cert probably isn't the issue as more people than just you would be complaining about connection problems.

Since java likes to do its own crypto / cert management (instead of deferring to the OS), I'm guessing the issue is probably with your jdk install.

Its pretty simple to grab another jdk bundle, unzip it into a temp directory, and run jshell (or whatever) directly from its <installdir>/bin directory and re-do this connection test.

There are multiple vendors that provide free JDK bundles.

**Comment by user4856vw** [comment]
»It successfully connects to that hostname.
»There are multiple vendors that provide free JDK bundles.

OK, if this is the case -- which jdk would you recommend then/which one did you use for your test where it worked ?

**Comment by dev747368** [comment]
Not to endorse any particular vendor / bundle, but pretty much any* works just fine.

Amazon's [Corretto](https://aws.amazon.com/corretto/)
Open Jdk [https://jdk.java.net/18/](https://jdk.java.net/18/) 
AdoptOpenJDK [https://adoptopenjdk.net/](https://adoptopenjdk.net/)

* amazon corretto has a funky bundle targeting a version of linux they use for their ec2 instances that doesn't include GUI stuff (its 'headless'), but all the other ones are fine.

**Comment by user4856vw** [comment]
ok, thank you, I will continue on Monday and will let you know.

**Comment by user4856vw** [comment]
I went for OpenJDK:
$ java --version
openjdk 18.0.2.1 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

 and the results are the same, for example in jshell (everything else is the same too):

jshell> jget("https://github.com/NationalSecurityAgency/ghidra-data/raw/Ghidra_1
0.1.5/FunctionID/vs2012_x64.fidb")
jget("https:                             Agency/ghidra-data/raw/Ghidra_1       10.1.5/FunctionID/vs2012_x64.fidb")                                              
                       javax.net.ssl.SSLHandshakeException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:371)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:314)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.ja
va:309)
....

Computer, is not under my own administration, so if you suggest for something else to be checked in terms of relevant or possibly relevant configuration -- please suggest.

**Comment by ryanmkurtz** [comment]
I think it would be worth trying a jdk 17 LTS distro from adoptium.net or amazon corretto.

**Comment by dev747368** [comment]
To me, its looking like a problem cause by a firewall / proxy wanting to MITM the connection and your jdk not allowing it.

I suspect that trying to fetch (with the "jget" method) from some other random https URL than github would also fail.

**Comment by user4856vw** [comment]
$ java SSLPoke github.com 443
Successfully connected

So, looks like it is redirect somehow causing (some of) it. Also, downloading the object under https://github.com/NationalSecurityAgency/ghidra-data/raw/Ghidra_10.1.5/FunctionID/vs2012_x64.fidb  from the Firefox browser works, so it can be particularly picky proxy about what it wants to MITM, it is possible with such constructs like white-listed applications -- but it not very probable, I guess.  <I will suppress all the obvious jokes about NSA  speaking with authority about MITM here ;-)>.  

Will try tomorrow with another recommended JDK, maybe there is some additional drill-down into all of it and will let you know.

**Comment by dev747368** [comment]
If you're thinking the redirect is triggering the failure, have you tried supplying the redirected location to the "jget" so that there are no redirects involved in the connection attempt?

**Comment by user4856vw** [comment]
jshell> jget("https://github.com/NationalSecurityAgency/")
Read 193296 bytes

without redirects, if this is what you meant. 

So, I am of two minds, sort of here with probabilities roughly like that: MITM -- some 20% , no MITM, strange Java-own issue --some 80%

**Comment by dev747368** [comment]
Actually, I meant:

```
jshell> jget("https://raw.githubusercontent.com/NationalSecurityAgency/ghidra-data/Ghidra_10.1.5/FunctionID/vs2012_x64.fidb")
```

**Comment by user4856vw** [comment]
Ah, but this is with redirect github.com vs. githubusercontent.com and it does lead to stacktrace. So, what should it be in your opinion -- some whitelisted domain vs. non-whitelisted where MITM is attempted/ something else ?

**Comment by dev747368** [comment]
I didn't parse your comment very well.

In an earlier comment of yours (https://github.com/NationalSecurityAgency/ghidra/issues/4585#issuecomment-1242293634), you showed an attempt to directly connect to raw.githubusercontent.com, so that kinda rules out a redirect being the problem. 

```
java SSLPoke raw.githubusercontent.com 443
sun.security.validator.ValidatorException: PKIX path building failed: sun.securi
ty.provider.certpath.SunCertPathBuilderException: unable to find valid certifica
tion path to requested target
```

**Comment by user4856vw** [comment]
Ah, OK, this is what is meant with redirect -- I thought it is both redirect in girdle's logic and also submitting different domain as compared to github.com explicitly. So, this leaves us, as far as I see it, with 2 options -- selective MITM on non-whitelisted domain (this is for sure possible, I know at least one vendor offering this "feature") or something else -- but I would not know what it might be in this case.  What would be your take ?

**Comment by user4856vw** [comment]
OK, I also tried gnutls-cli on certificate chain and it does report an error: The certificate is NOT trusted. The issuer is unknown. Here is the whole chain:

gnutls-cli --print-cert raw.githubusercontent.com
Processed 350 CA certificate(s).
Resolving 'raw.githubusercontent.com:443'...
Connecting to '146.112.53.229:443'...
- Certificate type: X.509
- Got a certificate list of 3 certificates.
- Certificate[0] info:
 - subject `CN=raw.githubusercontent.com,O=Cisco Systems\, Inc.,L=San Francisco,ST=California,C=US', issuer `CN=Cisco Umbrella Secondary SubCA fra-SG,O=Cisco', serial 0x7689c86c, RSA key 2048 bits, signed using RSA-SHA256, activated `2022-09-10 07:18:05 UTC', expires `2022-09-15 07:18:05 UTC', pin-sha256="Zw9chp0K8HSJFpgvOPzkuu3earAoCTtZy+yOs/lJV2Y="
        Public Key ID:
                sha1:449a67d9eef1c58bde8234051dc3c98a82c2a65c
                sha256:670f5c869d0af0748916982f38fce4baedde6ab028093b59cbec8eb3f9495766
        Public Key PIN:
                pin-sha256:Zw9chp0K8HSJFpgvOPzkuu3earAoCTtZy+yOs/lJV2Y=


-----BEGIN CERTIFICATE-----
MIIDYjCCAkqgAwIBAgIEdonIbDANBgkqhkiG9w0BAQsFADBAMQ4wDAYDVQQKDAVD
aXNjbzEuMCwGA1UEAwwlQ2lzY28gVW1icmVsbGEgU2Vjb25kYXJ5IFN1YkNBIGZy
YS1TRzAeFw0yMjA5MTAwNzE4MDVaFw0yMjA5MTUwNzE4MDVaMHwxCzAJBgNVBAYT
AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
MRwwGgYDVQQKDBNDaXNjbyBTeXN0ZW1zLCBJbmMuMSIwIAYDVQQDDBlyYXcuZ2l0
aHVidXNlcmNvbnRlbnQuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAyy9w1OZ8wemcM0AqugzG8aiW0ts7xk0pl69EucFK4BlNwh+EzCSGY0OvGet5
F8SuFSa4zFn5CWnxrSouBm/teUYBH7ilSiucHShWvVGbPrSvUvs1cVt4CNRmAW94
wnZ/vbu6XcvS51EqzqG0kIzXOhJPfrFAsDVSvMA3Xq+xIBWdK2W/QHwNRjWHvES1
xWpGY0RLuep2/YLs3x2XQRoCopxwh5oaupQGv7xM36WMToZviaX08zwuMclKwLE/
w6wLY71+LnefAR50XPU1NtCwivDBWl/jmhNisUUWlfOSqDRBjVN3IMDDCVMbIyEO
sJn7KAJFZaUdnLTjG0ayoC+mrwIDAQABoygwJjAkBgNVHREEHTAbghlyYXcuZ2l0
aHVidXNlcmNvbnRlbnQuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQBpYDblGFnbDoNj
QrdXWReqCFOdTi9jnsBrI9+uuvliss5agI8balUDqdA7BSyYvGNgA2boDfnQ8dJ1
s0bQTOi9kIWvmjH0M32dm3d+DuWvZqlQOhHP6BD8Y34EqyffMCWnhfknzRArTi2U
AspE0MEiTG8gorRob+HI1kIKyZEtlPcZVnLQoTpaALli76dDh5N6INpNEd2sHomg
diPkw32vyJqij2nbktIZIC3nQLnXMN8cyOWThV62NW3RfW4bqUwvwKjJQsjjNjhP
XkOACzm+m4szhB3vItQvZWe+NjtguarD7TJtTBjCmpjmOGS8twB5JEIdT2zc9bA0
Q2beH1Ka
-----END CERTIFICATE-----

- Certificate[1] info:
 - subject `CN=Cisco Umbrella Secondary SubCA fra-SG,O=Cisco', issuer `CN=Cisco Umbrella Primary SubCA,O=Cisco,L=San Francisco,ST=California,C=US', serial 0x00fdb4a40411b84b22a1b978d5db8ff278, RSA key 2048 bits, signed using RSA-SHA256, activated `2022-09-10 22:48:49 UTC', expires `2022-09-21 22:48:49 UTC', pin-sha256="Zw9chp0K8HSJFpgvOPzkuu3earAoCTtZy+yOs/lJV2Y="

-----BEGIN CERTIFICATE-----
MIIENjCCAx6gAwIBAgIRAP20pAQRuEsiobl41duP8ngwDQYJKoZIhvcNAQELBQAw
cTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNh
biBGcmFuY2lzY28xDjAMBgNVBAoMBUNpc2NvMSUwIwYDVQQDDBxDaXNjbyBVbWJy
ZWxsYSBQcmltYXJ5IFN1YkNBMB4XDTIyMDkxMDIyNDg0OVoXDTIyMDkyMTIyNDg0
OVowQDEOMAwGA1UECgwFQ2lzY28xLjAsBgNVBAMMJUNpc2NvIFVtYnJlbGxhIFNl
Y29uZGFyeSBTdWJDQSBmcmEtU0cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDLL3DU5nzB6ZwzQCq6DMbxqJbS2zvGTSmXr0S5wUrgGU3CH4TMJIZjQ68Z
63kXxK4VJrjMWfkJafGtKi4Gb+15RgEfuKVKK5wdKFa9UZs+tK9S+zVxW3gI1GYB
b3jCdn+9u7pdy9LnUSrOobSQjNc6Ek9+sUCwNVK8wDder7EgFZ0rZb9AfA1GNYe8
RLXFakZjREu56nb9guzfHZdBGgKinHCHmhq6lAa/vEzfpYxOhm+JpfTzPC4xyUrA
sT/DrAtjvX4ud58BHnRc9TU20LCK8MFaX+OaE2KxRRaV85KoNEGNU3cgwMMJUxsj
IQ6wmfsoAkVlpR2ctOMbRrKgL6avAgMBAAGjgfkwgfYwEgYDVR0TAQH/BAgwBgEB
/wIBADAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0OBBYEFJfn7xFBJfx7HRYNma9A0Cv3
WSEJMB8GA1UdIwQYMBaAFEVf9ZtxMyWpwE48AkTPPOhGBhbEMEwGCCsGAQUFBwEB
BEAwPjA8BggrBgEFBQcwAoYwaHR0cDovL2NybC5wcm9kLmNhZ2VuZXJhdG9yLnBr
aS5zdHJsbi5uZXQvY2EucGVtMEIGA1UdHwQ7MDkwN6A1oDOGMWh0dHA6Ly9jcmwu
cHJvZC5jYWdlbmVyYXRvci5wa2kuc3RybG4ubmV0L2NybC5wZW0wDQYJKoZIhvcN
AQELBQADggEBAAiF5xfW6bqKOHdZnPq5t7Lo5msldlKSXVsxpuaIPYbzzOvf67sH
+YwR9Szyl7JdWed1XUQyjQe+j6y2HoVTULke+ylwwOanZTcHPRo22L6aQP4+jnRH
fL97w26Te1FEPY0WGp0AEfcZFMVj/GOM+9eznLVHp2INX0EjuLSvyX5IGqqk6Ekq
45ZuxHvVFkHqxp/CoLp7hIz8oaDwKTz3iiJtfu0zVPKrbnHjRFLnZq/LqumBtoPG
8Lz6aYfrLMzsee/Ff2mOn/bCI56AuZEhAMCBjOB1vXmE91nyKaE2NjmOV5itcdEL
Cuq609BIzyVciTSL5HLUgTOONO6xKzkX558=
-----END CERTIFICATE-----

- Certificate[2] info:
 - subject `CN=Cisco Umbrella Primary SubCA,O=Cisco,L=San Francisco,ST=California,C=US', issuer `CN=Cisco Umbrella Root CA,O=Cisco', serial 0x01c437cc578dbca615, RSA key 2048 bits, signed using RSA-SHA256, activated `2019-05-21 19:53:18 UTC', expires `2024-05-21 19:53:18 UTC', pin-sha256="6mXdoCNmkhi0cS1cNTT33FPTQvsYALvjioE69pRMAVU="

-----BEGIN CERTIFICATE-----
MIIEuzCCA6OgAwIBAgIJAcQ3zFeNvKYVMA0GCSqGSIb3DQEBCwUAMDExDjAMBgNV
BAoTBUNpc2NvMR8wHQYDVQQDExZDaXNjbyBVbWJyZWxsYSBSb290IENBMB4XDTE5
MDUyMTE5NTMxOFoXDTI0MDUyMTE5NTMxOFowcTELMAkGA1UEBhMCVVMxEzARBgNV
BAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDjAMBgNVBAoM
BUNpc2NvMSUwIwYDVQQDDBxDaXNjbyBVbWJyZWxsYSBQcmltYXJ5IFN1YkNBMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuFEhA5TkN8CiGmW7XjaUbuve
U274v0kt6hRW8UUakmbyLnkI4d/BBQrGW71LYiT2QH4UaoYuihTXjuyAlzDxJ9OQ
Vje2NB9RdE3FcUCISeW5GrQs7vF2xFrjs2TGgG4ZXjE/8WymgFZP50nsTJYf7VqL
1r6Brs59DAbbQ1rVvsz/DFxoE3ruFagSFcOF07/watUxFrAPV+S/kK6Nb5TqrI1j
32hK6i49ujavDcbbb12aozwdoyPSyhs4cB0sCXFHK/yEdaE4CNXEAH8EjKUuj6O2
QUvRtBGM480688BId0T0ws3q+hSzRiVJ+dYCr3iufmTrAMhVwc+EzGjlEfLyXwID
AQABo4IBlDCCAZAwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
UgYDVR0gBEswSTBHBgorBgEEAQkVAR0AMDkwNwYIKwYBBQUHAgEWK2h0dHA6Ly93
d3cuY2lzY28uY29tL3NlY3VyaXR5L3BraS9wb2xpY2llcy8wHQYDVR0OBBYEFEVf
9ZtxMyWpwE48AkTPPOhGBhbEMEwGA1UdHwRFMEMwQaA/oD2GO2h0dHA6Ly93d3cu
Y2lzY28uY29tL3NlY3VyaXR5L3BraS9jcmwvY2lzY291bWJyZWxsYXJvb3QuY3Js
MIGHBggrBgEFBQcBAQR7MHkwSQYIKwYBBQUHMAKGPWh0dHA6Ly93d3cuY2lzY28u
Y29tL3NlY3VyaXR5L3BraS9jZXJ0cy9jaXNjb3VtYnJlbGxhcm9vdC5jZXIwLAYI
KwYBBQUHMAGGIGh0dHA6Ly9wa2ljdnMuY2lzY28uY29tL3BraS9vY3NwMB8GA1Ud
IwQYMBaAFENzAN4kukAaQFQsfXzVAEiJDHCkMA0GCSqGSIb3DQEBCwUAA4IBAQC6
P7ugvpQSkNxrzY1ZM0Nd9Q3LaoTERS4ItcxMsswFPl7ID/3Vk3v3ZT6KgtCZ+Nh0
MUgZztLATHf42ZppdSkdMf1HfCmLSWORz/eK+fZxztE63M1EGiZJoe8qFKT9z6qx
iDD989jyjY74sYfiSo5nbhcb5meUrUO6MQvOO5pUnlhWsDiBUg+yBzyfVoLnGRlY
2t7UZVTUz5kbBNFieTIt86yaYAumgOqriz/dCgQltFySbOkrgg/PN7cRv3IWm84C
uKQ9prsXbXLLbl8U+bGRH119prl3zJyRnQ0D+ursCqUnIfziBdKv7yLsupGDGt+Q
oqLzmkMPYE+WZmEi+3j5
-----END CERTIFICATE-----

- Status: The certificate is NOT trusted. The certificate issuer is unknown.
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.

Now what ?

**Comment by dev747368** [comment]
Here is what raw.githubusercontent.com looks like for me:

```
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=*.github.io,O=GitHub\, Inc.,L=San Francisco,ST=California,C=US', issuer `CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US', serial 0x0b8e33b5d1867a7ea5d1502ed7e31689, RSA key 2048 bits, signed using RSA-SHA256, activated `2022-03-18 00:00:00 UTC', expires `2023-03-21 23:59:59 UTC', pin-sha256="7nsWWLaS1TuZf1ZO548syKMw5c6zXzIuwPbL+gQfkVQ="
	Public Key ID:
		sha1:340d31153bfb96af64ef26fcc00cc8da0d2071d8
		sha256:ee7b1658b692d53b997f564ee78f2cc8a330e5ceb35f322ec0f6cbfa041f9154
	Public Key PIN:
		pin-sha256:7nsWWLaS1TuZf1ZO548syKMw5c6zXzIuwPbL+gQfkVQ=

```

The fact that you have the string "cisco" in your key is a good indication that its a firewall / proxy thing.
