### ISSUE TITLE
Jython2.7.2 coexisting with Ghidra as primary

### ISSUE THREAD

**Issue by SeniorChiefBMB** [NationalSecurityAgency/ghidra#4587]
Developers,
     I am at Colorado Technical University pursuing my Bachelors Degree in Computer Science CyberSecurity Engineering. I hold a 3.87 GPA with a classroom course curriculum average of 105.5. Now, with that being said, I am 50 y/o and was tasked with returning to university to update my verbiage and terminology. I was heavily recruited by Arizona State University because of their fledgling Cubesat program that is performing great, however, I chose Colorado Technical University because of the Department of Defense support and funding. I have been chosen for a student for hire program (OCS) with National GeoSpatial Intelligence Agency and currently completing the assessment phase of the process. I have been Cisco certified since 1999. My intent for future use is with the SATCOM server (preferably hand-built or GETAC) and Geosynchronous GeoSpatial electromagnetic gravitational harmonic vibrational spectrum physics anomaly telemetry calibration documentation. My current laptop is a Windows 7. I have access to a Windows 10. I prefer the 7, however, will upgrade the software, as well, on the 10 once this issue is complete.  I am not proficient with Python as I want to be, yet, I will be fast by the time I move to Colorado. I have applied for an internship at NORAD/USNORTHCOM and am updating documentation since they "lost" some it. Their website is vastly improved and I am looking forward to the move within a few weeks. Any explanation on which direction or path to take with reference to the 7 or 10 would be greatly appreciated. NSA Ghidra is exquisite software I would love to complete my 5 computer lab courses by Monday with on one of these laptops. You ALL are exemplary in my book.
Jython 2.y.2 will not open correctly with the Ghidra software and the file issue will not stay open in reference to the CLI. Experts, I need direction!

**Comment by SeniorChiefBMB** [comment]
I am, also, accruing credit toward my  Masters with a CISSP-ISSEP while pursuing and obtaining my Bachelors. Help me find a solution, Everyone. We should be able to communicate with proper hardware/software communication equipment to the Satellites that are now called Spacecraft. Google Spacecraft!

**Comment by SeniorChiefBMB** [comment]
National Security Agency Development Team,
     Never forget the encryption aspect. We should be able to use the lastest and stay out front with revisions in code. Think of the code ALL along in reference to Mobile SATCOM Engineers with Engineering degrees. I love SHA, however, I am the new guy. Help me.

**Comment by SeniorChiefBMB** [comment]
I have multiple design schematic blueprints that are being prototyped in several programs with several countries. I am working on two more and those are requested designs for people I know from the last several years of drafting these prints.

**Comment by SeniorChiefBMB** [comment]
HUA
Humble Understanding Always 
Non Desistas:Non Exieris 
Non Deficere

**Comment by ryanmkurtz** [comment]
@SeniorChiefBMB, can you please rephrase your specific Ghidra question in 1 or 2 sentences?

**Comment by ryanmkurtz** [comment]
Closing.  We can reopen it if you come back with a simplified description.
