### ISSUE TITLE
Autoanalysis: Microsoft Demangler does not respect the "Apply Function Calling Conventions" option

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4590]
**Describe the bug**
A fix for #3892 introduced the "Apply Function Calling Conventions" and "Apply Function Signatures" options to the Microsoft Demangler. However, calling conventions are still applied even when the  "Apply Function Calling Conventions" option is unchecked.

As a lazy 'fix', I modified ``MDMangGhidra.java`` to ignore the calling convention as follows:

![image](https://user-images.githubusercontent.com/55233728/189575282-c9e19435-7f19-4329-8b84-b86c46c92fbd.png)

However, this led to an unexpected result. When Autoanalysis is run with "Apply Function Calling Conventions" unchecked, the demangled functions are now left unchanged by the demangler, but multiple error bookmarks are generated:

![image](https://user-images.githubusercontent.com/55233728/189575478-69296648-35b9-4f3b-bdd5-fd24f9bfec77.png)

This string only appears in ``DemangledFunction.java``:
![image](https://user-images.githubusercontent.com/55233728/189575585-a01a99d3-26ce-46f2-862a-5e3d1af2fec6.png)

which implies that somehow the option set in the analyzer is not propagating to the ``DemangledFunction`` somehow. I haven't yet drilled down to the root cause for this though.

**Environment (please complete the following information):**
 - Commit 5593df4

**Comment by ghizard** [comment]
I believe I found the cause of this last week while visually reviewing an internal Demangler ticket.  I believe the problem is in MicrosoftDemanglerAnalyzer.optionsChanged method... so I expect we will fix this in the near future as part of the internal ticket.

**Comment by sad-dev** [comment]
> I believe I found the cause of this last week while visually reviewing an internal Demangler ticket. I believe the problem is in MicrosoftDemanglerAnalyzer.optionsChanged method... so I expect we will fix this in the near future as part of the internal ticket.

Ah I see it, thanks. The obvious patch seems to work for me.
