### ISSUE TITLE
Decompiler signature overrides leads to _guard_dispatch_icall appearing in results

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4591]
**Describe the bug**
This appears to be related to #3319 
Overriding signatures for calls to ``_guard_dispatch_icall`` result in the loss of the original variables that represent the callee:

![image](https://user-images.githubusercontent.com/55233728/189581473-8e2b8db1-b7f8-4b6d-987e-89310e3fab81.png)

![image](https://user-images.githubusercontent.com/55233728/189581726-fe95d075-e993-4026-8d79-6a1748f4acb7.png)

This happens when the call goes through ``CALL qword ptr __guard_dispatch_icall_fptr``
![image](https://user-images.githubusercontent.com/55233728/189586744-7e296c4c-448a-4f3a-a650-2bcb88f92586.png)

As a workaround, patching the call with ``CALL RAX`` will let you override the signature without having ``_guard_dispatch_icall` appear

**Environment (please complete the following information):**
 - commit 5593df4

**Comment by ghidracadabra** [comment]
Looks related to #1719.
