### ISSUE TITLE
typo in port address atmega256

### ISSUE THREAD

**Issue by Franck78** [NationalSecurityAgency/ghidra#4592]
https://github.com/NationalSecurityAgency/ghidra/blob/6a2cd8055086905c76bf4ac3fe0700d2db28652f/Ghidra/Processors/Atmel/data/languages/atmega256.pspec#L315

mem:0x1018 should be mem:0x108

also error line 303  (0x100c)

**Comment by GhidorahRex** [comment]
according to the manual, it should be 0x118, which matches it's position in this list. (http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-8393-MCU_Wireless-ATmega256RFR2-ATmega128RFR2-ATmega64RFR2_Datasheet.pdf). Either way, both lines are incorrect.
