### ISSUE TITLE
Is there any Backdoors or Monitoring Services behind GIHDRA?

### ISSUE THREAD

**Issue by aks852322** [NationalSecurityAgency/ghidra#46]
As the software was released to the public free of cost and its from NSA, common comments we get over some YouTube videos are this question title.
Is there any sort of Backdoor or Any other Monitoring Services in the Software ?

**Comment by oldmud0** [comment]
It's going to be open-source on the full release, so you can inspect and compile the code for yourself.

**Comment by aks852322** [comment]
If someone finds something related to this topic, what will be the NSA's reply?

**Comment by ctubbsii** [comment]
A strikingly similar question was asked and answered on https://github.com/NationalSecurityAgency/qgis-searchlayers-plugin/issues/6#issuecomment-367773492

In short:
1. the license disclaims any express or implied warranties (status quo for any open source project, not unique to NSA)
2. you're free to inspect and compile the code yourself (you don't need to trust the code's authors)
3. if you find anything you think is a problem, you are welcome to report it as a bug

**Comment by CharlesDardaman** [comment]
They said in their talk that there are no backdoors in this application, but you can always just decompile it and look for yourself until the source is out.
