### ISSUE TITLE
unimportant typo

### ISSUE THREAD

**Issue by Franck78** [NationalSecurityAgency/ghidra#4601]
https://github.com/NationalSecurityAgency/ghidra/blob/975db1919c9e13aeb794883f4e93603fc6c0ea7e/Ghidra/Processors/6502/data/languages/6502.slaspec#L74

Pseudo is better

**Comment by SeniorChiefBMB** [comment]
Euclidean Mathematics = 4/Halfway2Family. Echo on 3. National GeoSpatial Anomaly Detection.

**Comment by ghidracadabra** [comment]
`grep -irn psuedo * | wc -l `

**Comment by d-millar** [comment]
:)  guessing that got entered in the wrong window

**Comment by ghidracadabra** [comment]
Just a note that this particular spelling error happens several times throughout the code base and we should probably fix them all at once.

**Comment by ryanmkurtz** [comment]
I'll fix them all.
