### ISSUE TITLE
Error importing file, java.io.IOException: Invalid index

### ISSUE THREAD

**Issue by MurrayDu** [NationalSecurityAgency/ghidra#4605]
**Describe the bug**
I try to import so, and get an import error saying

Invalid index: 4294967295
java.io.IOException: Invalid index: 4294967295
	at ghidra.app.util.bin.FileByteProvider.ensureBounds(FileByteProvider.java:264)
	at ghidra.app.util.bin.FileByteProvider.readBytes(FileByteProvider.java:121)

**To Reproduce**
1. Create a project
2. Click on File > Import File
3. Select the sample and click on Select to Import
4. Click on OK
5. See error

**Expected behavior**
Importing the file to be able to decompile it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8066288/190960790-b53350f7-bba5-4d41-8771-d2e879f6c771.png)
![image](https://user-images.githubusercontent.com/8066288/190960810-c8479b62-eba7-430b-bec4-8d95c074dd1c.png)

**Attachments**
  If applicable, please attach any files that caused problems or log files generated by the software.

**Comment by dev747368** [comment]
Could you confirm that your Elf binary is a 32 bit file?
