### ISSUE TITLE
Tool Options does not accept hexadecimal values

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4607]
**Describe the bug**
I use the ``Options`` class to control the runtime behavior of some of my scripts. For some of these scripts it is more intuitive to type in their values in hexadecimal. Unfortunately it appears that the Tool Options window just ignores/fails on values in the form "0x..."

**To Reproduce**
Try changing (Edit -> Tool Options -> Tool ->) Max Navigation History Size to 0x40

**Comment by dragonmacher** [comment]
The underlying options store the given value as a Java integer, which we interpret visually as a decimal.  We have no mechansim to know if the original value was provided as hex or decimal.  It would be easy enough to allow the value to be entered as a hex value, but when the options are later accessed, they would be displayed as decimal.   The work to change this in the options framework is not something we will be doing at this time.    If this ticket gets enough upvotes, then we can revisit this in the future.
