### ISSUE TITLE
array inside struct not correctly decompiled

### ISSUE THREAD

**Issue by carlislemc** [NationalSecurityAgency/ghidra#461]
When an array is not the first field of a struct, a dereference in that array is not correctly decompiled.

**To Reproduce**
1. Download https://2018shell.picoctf.com/static/f29317f5d2ade2eb183ad05038bfc50a/cake
2. Analyze file in Ghidra
3. Define datatypes for cake and store
struct cake {
	long price;
	char name[8];
};

struct shop {
	long sales;
	long customers;
	struct cake *cakes[16];
}; 
4. Change function prototype for parameter to inspect to struct shop *store
5. Array dereference will indicate store->sales[i+2] instead of store->cakes[i]

**Expected behavior**
Array dereferences in inspect should use the array in the structure.

**Screenshots**
![image](https://user-images.githubusercontent.com/14895271/56362782-a87aaf00-61b8-11e9-9a79-7ce72d0b0de1.png)
![image (1)](https://user-images.githubusercontent.com/14895271/56362802-b7f9f800-61b8-11e9-8add-325439cee6b2.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: java version "1.8.0_201"
 - Ghidra Version: 9.0

**Comment by emteere** [comment]
Have duplicated here and evaluated.  The decompiler will need an additional simplification rule for this compiler optimization case.

**Comment by bennofs** [comment]
@emteere do you have an idea about the kind of rule to fix this? Maybe RulePtrArith needs to be extended to be a little bit more general?

**Comment by caheckman** [comment]
This is fixed in master now and in the upcoming 9.2.
