### ISSUE TITLE
Unable to rename some globals in decompiler

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4613]
**Describe the bug**
Some global pointers cannot be renamed in the decompiler.  The rename right click context menu item is gone.

Looks to bisect down to fcf20ed9a5ac862ce6e61511908637aca11c0e6a

**To Reproduce**
```C
void *g_func;
void foo() { return; }
void set_func(void *x) { g_func = x; }
void init() { set_func(foo); }
```
In `init` I cannot rename `foo` from the decompiler

**Environment (please complete the following information):**
 - OS: 20.04
 - Java Version: 17.0.4
 - Ghidra Version: 7e24c986ad72ce70a3e71c7a3d2adfd752b6e73f
 - Ghidra Origin: eclipse

**Comment by ghidra1** [comment]
When I tested using your sample code (built ELF binary) the `Rename Function` popup menu action was present/enabled and worked as expected. 
![before](https://user-images.githubusercontent.com/48333017/192302226-09bcff7c-8ae8-48cc-99e0-9425619f4898.png)
![after](https://user-images.githubusercontent.com/48333017/192302238-e8991d23-7276-4169-ac76-22a47934ce3b.png)

**Comment by mumbel** [comment]
@ghidra1  thanks for verifying.  Looks like there were a few merges, I'll pull those and double check tonight.  I guess it just depends on if I can rename after pulling, but I was able to bisect down to that one commit, are you able to rename on that commit?

**Comment by ghidra1** [comment]
Sorry, I am was in an older master branch when I tested.  Yea - I may have broken with GP-2520 merge.  Stay tuned...
