### ISSUE TITLE
Feature Request: Address Table Analyzer should bookmark the end of table too

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4617]
**Is your feature request related to a problem? Please describe.**
I often want to navigate to the end of pointer tables to check if analysis missed a few extra pointers. There isn't a goto command of the form 'goto currentAddress + 0x__ bytes" afaik, so I usually do something like the following:

1.) pop calc
2.) calculate table + numElems * pointerSize
3.) copy address (don't forget to convert to hex) and goto

I eventually modified Ghidra as follows:

![image](https://user-images.githubusercontent.com/55233728/192237135-86102823-66cd-43dd-9b29-8016443a76a6.png)

This helps me immediately see certain stuff, for example, the tables here probably could be merged (distance between them =0xC)
![image](https://user-images.githubusercontent.com/55233728/192237474-5dfe2277-263f-49f9-97fd-92ef99cc4afc.png)

Something like this (perhaps with yet another checkbox to control whether the end bookmark is created) would probably be quite useful. A utility to manage/merge address tables and the corresponding bookmarks would be nice sugar but not essential.

**Comment by ryanmkurtz** [comment]
If you enter  `+5` in the goto dialog that will take you 5 bytes past the current address.

**Comment by ryanmkurtz** [comment]
You can also do `+(5*8)`

**Comment by sad-dev** [comment]
Wow that's some nice black magic :+1:

**Comment by ryanmkurtz** [comment]
If you click those hyperlinks in the goto dialog it will detail all the different things you can do.

Is this black magic sufficient to replace your feature request?

**Comment by sad-dev** [comment]
I'm ok with using the goto expression for small cases (and making the bookmarks myself) and scripting (or using my mod) for large cases, so I'll close this issue.

**Comment by sad-dev** [comment]
> If you click those hyperlinks in the goto dialog it will detail all the different things you can do.
> 
> Is this black magic sufficient to replace your feature request?

I have been playing around with the goto expression and ironically (given how many issues I raise asking for hexadecimal everything), it treating all numbers as hexadecimal by default is a problem for me. 

By default the bookmark gives the number of entries in decimal. e.g. 1453 in the original post. trying to do "+1453*4" quite clearly won't work, so I still have to alt-tab to my favorite calculator - or modify the bookmark to also print the size in hex. Hacking around the issue is easy enough, so I'm fine with leaving the issue closed.

**Comment by ryanmkurtz** [comment]
Changing the bookmark addresses to use hex seems reasonable.  Changing the goto dialog to use 0x is probably too invasive at this point.
