### ISSUE TITLE
Set field type for regions of memory

### ISSUE THREAD

**Issue by Martmists-GH** [NationalSecurityAgency/ghidra#4621]
**Is your feature request related to a problem? Please describe.**
There is currently no good way to deal with union types in the decompiler view. You'll just see mystruct._2_2_ or ._4_1_ which is not very descriptive.

**Describe the solution you'd like**
Similar to how we can use "Set register value" on a region of memory, it'd be great to have a way to set the type of a union field on a variable.

**Describe alternatives you've considered**
Our current solution is to simply switch out the field's type every time we need to, but this is far from an ideal solution.

**Comment by astrelsky** [comment]
Union support in the decompiler has been recently been added and is currently only available in the master branch.
