### ISSUE TITLE
Data Type Manager - add structure size and use it as additional filter

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4622]
**Is your feature request related to a problem? Please describe.**
Locating potential candidate structures when seeing memory being allocated and assigned to a pointer.

**Describe the solution you'd like**
In the `Data Type Manager` it would help if the sizes of each datatype could be shown (in hex and/or dec - configurable) and also be used as an additional filter.

**Describe alternatives you've considered**
1. Tried modifying the DTM locally to append the size, that kinda works, but with screen space at a premium, it would be better shown at the beginning.
2. Tried modifying the DTM locally to prepend the size, but that messes with the sort order and using the first letter of the type to quickly find it no longer works (for those beginning with a letter that isn't used as an accelerator key!).
3. Finally I'm currently adding the hex size in the datatype name, but that can be a pain when creating C++ classes.

**Comment by Wall-AF** [comment]
Similarly it would be good to have variable names optionally configured to show their structure/stack(/union) offset as an appendage to their names.  This allows better visualisation between assembly constructs like:
```
                             LAB_11e0_1071                                   XREF[1]:     11e0:0feb(j)  
   11e0:1071 c4 5e f8     00e           LES        BX,[BP + pHeap]
   11e0:1074 66 8b 46 0a  00e           MOV        EAX,dword ptr [BP + pContext]
   11e0:1078 66 26 89 07  00e           MOV        dword ptr ES:[BX],EAX
   11e0:107c 66 8b 46 0e  00e           MOV        EAX,dword ptr [BP + nSize]
   11e0:1080 66 26 89     00e           MOV        dword ptr ES:[BX + 0x4],EAX
             47 04
```
and
```
   pHeap->pContents_0x0 = pContext;
   pHeap->nSize_0x4 = nSize;
```
As you can see (above) I've added the offsets to the `Heap` structure I created.

Having it as an option cleans up the decompilation for extracting.

**Comment by Wall-AF** [comment]
> > and also be used as an additional filter.
> 
> Ghidra now has the ability to `Find Data Types by Size` and `Find Structures by Size`.

Nice find, could do with these options available from the "Context Menu" as there doesn't appear to be an easy way to assign a keyboard shortcut to the DTM dropdown menu button!

> > it would help if the sizes of each datatype could be shown
> 
> The preview window for each type contains its length, but not in hex. In addition to having a hex option, are you also asking for the length value to appear in each tree node's text?

The "preview window" does do that, however that is limited to looking at individual datatypes The kind of thing I was thinking of is demonstrated below:
![image](https://user-images.githubusercontent.com/67698927/192579341-41d02a55-3569-42d6-9d84-309bc7c095cb.png)
As you can see, I've added the sizes to the name, and if I were searching for all my types of a specific size, I could place text lie `_0x2a_` in the filter to find them all.

**Comment by dragonmacher** [comment]
> Nice find, could do with these options available from the "Context Menu" as there doesn't appear to be an easy way to assign a keyboard shortcut to the DTM dropdown menu button!

You should be able to press `F4` while hovering over an individual drop-down item in order to assign a key binding.   Then you would be able to use the desired drop-down action without the need to actually show the drop-down menu.

> The "preview window" does do that, however that is limited to looking at individual datatypes The kind of thing I was thinking of is demonstrated below:

:+1:

**Comment by Wall-AF** [comment]
> > Nice find, could do with these options available from the "Context Menu" as there doesn't appear to be an easy way to assign a keyboard shortcut to the DTM dropdown menu button!
> 
> You should be able to press `F4` while hovering over an individual drop-down item in order to assign a key binding. Then you would be able to use the desired drop-down action without the need to actually show the drop-down menu. (The actions can also be bound in the Tool Options key binding section.)

Thought you had to click, not just hover, good call!  Just tried it with `Alt+Down` and then `F10`, neither actually performed the action, even though hovering over the button showed the shortcut!

**Comment by dragonmacher** [comment]
I just tried binding `Find Structures by Size...` to F10 and that worked for me while focus was in the Data Type Manager window.

**Comment by Wall-AF** [comment]
> I just tried binding `Find Structures by Size...` to F10 and that worked for me while focus was in the Data Type Manager window.

Not ideal as that menu has other interesting options and not as memorable as say `Ctrl+F` (already used), but it'll do for now, thanks.
