### ISSUE TITLE
Single cell copy from Instruction Info window does not copy to clipboard

### ISSUE THREAD

**Issue by cglmrfreeman** [NationalSecurityAgency/ghidra#4626]
**Describe the bug**
When using the context menu to navigate to the `Instruction Info...` window in any disassembly, the context menu that allows copying the text of a single cell appears to be broken. The hotkey `ctrl+c` for this command also does not work. The other functions such as `Copy Current Column` and `Copy Columns...` work as intended (as well as the `Export` options).

**To Reproduce**
See above description, as instructions are listed to describe the bug itself.

**Expected behavior**
The single selected cell's contents should copy to the clipboard.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: openSUSE 20220905 x86_64 Linux 5.19.2-1-default
 - Java Version: 11.0.16
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official GitHub distro

**Additional context**
N/A

**Notes**
I apologize in advance if this is a duplicate submission. I tried to comb through the issues searching `copy` and `instruction info` but did not see anything like this.

EDIT: Upon hitting that submit button a thought occurred that I had not tested this behavior in my other Ghidra builds (all official). This behavior is seen in 10.0.1 and 9.1.2. I could have tested more but I have a funny kind of feeling that the results will be the same.

EDIT2: To confirm that this wasn't a fluke with my own OS setup, I spun up a fresh OpenSUSE TW virtual machine and ran 10.1.5 on it and the behavior was replicated exactly.

EDIT3: Booted up my Win10 VM and surprise, nothing in the clipboard. 
 - OS: Win10 Pro 10.0.19044 Build 19044
 - Java Version: 11.0.15
 - Ghidra Version: 10.1.2
 - Ghidra Origin: official GitHub distro

**Comment by dragonmacher** [comment]
I confirmed this is broken.  The issue is that the table currently does not allow row selections, which interferes with the copy action.  This should be an easy fix.

**Comment by cglmrfreeman** [comment]
How long has this gone unnoticed? :laughing:

**Comment by biggestsonicfan** [comment]
It's been a while, but I'm just now revisiting this. Single cell copy still appears to be broken, the entire row is copied from the context menu.

**Comment by dragonmacher** [comment]
It looks like the fix made it into the 10.2.2 build.  Which version of Ghidra are you testing this on?

**Comment by biggestsonicfan** [comment]
> It looks like the fix made it into the 10.2.2 build. Which version of Ghidra are you testing this on?

10.2.2, the adjustment removed the `opTable.setRowSelectionAllowed(false);` line, but I don't think single cells were ever implemented in the first place. 

There's another issue here at play too. Going to the `Instruction Info...` and right clicking first to try to bring up the context menu on any cells won't work. You must first highlight any cell with left click, then right click on any cell will bring up the context menu. However, after this, right clicking on various cells seems to give a 50/50 chance of the context menu actually coming up.

The following is an example of the `copy` command in the context menu, it puts the entire row converted to html into the clipboard, just just the selected cell as plaintext.
```
<html>
<body>


Op-Objects | RCX, const:0x20 | const:0x1
-- | -- | --



</body>
</html>
```

Oh... it seems I've discovered the issue while writing this, and perhaps why  `opTable.setRowSelectionAllowed(false);`  was in the code in the first place. `Copy current column...` now copies the individual cell's contents, while `Copy columns...` seems to give an identical result:
```
<html>
<body>


dword ptr [RCX + 0x20]
--



</body>
</html>
```

Going back to 10.1.5, `Copy current column...` functions as I believe it was intended: (A true column, not a row)
(Operand-1 column)
```
<html>
<body>


dword ptr [RCX + 0x20]
--
dword ptr [RCX + 0x20]
 
 
 
 
RCX, const:0x20
00000000 00000111 11111111 00000000 00000000 00000000 00000000
00000000 00000001 00100000 00000000 00000000 00000000 00000000


</body>
</html>
```
As well as  `Copy columns...`
```
<html>
<body>


Operand | dword ptr [RCX + 0x20] | 0x1
-- | -- | --
Labeled | dword ptr [RCX + 0x20] | 0x1
Type |   | SCAL
Scalar |   | 0x1
Address |   |  
Register |   |  
Op-Objects | RCX, const:0x20 | const:0x1
Operand Mask | 00000000 00000111 11111111 00000000 00000000 00000000 00000000 | 00000000 00000000 00000000 11111111 11111111 11111111 11111111
Masked Value | 00000000 00000001 00100000 00000000 00000000 00000000 00000000 | 00000000 00000000 00000000 00000001 00000000 00000000 00000000


</body>
</html>
```

**Comment by dragonmacher** [comment]
I just tried this in my Ghidra and all seems to be working as expected.

`Copy` copies the entire row.  With multiple rows selected, all rows are copied.

`Copy Current Column` copies just the selected cell when an single row is selected.  With multiple rows selected, only cells in the selected column for each row are copied.

Major Caveat: If you do not have column / cell selected when you execute the action, then the behavior may not work as expected.

**Comment by biggestsonicfan** [comment]
Okay, so the trick here now is all cells/rows need highlighting before the copy command, whereas in prior versions of ghidra, the context menu command did that for you. That's fair enough.

I still think the labels need renaming , however.
`Copy` -> `Copy Highlighted/Selected Row`
`Copy Current Column` -> `Copy Selected Cells`
However `Copy Columns` is just `Copy Rows` without selecting which columns you want to include by highlighting them, where previously it was a `Copy All Selected` where Selected was each check mark per column.

However this is all semantics at this point, considering prior to this, individual row/cell copying was not possible and now it is.

**Comment by dragonmacher** [comment]
> However this is all semantics at this point

You just described most of my Ghidra career.
