### ISSUE TITLE
C Parser fails on #pragma inside enum definition

### ISSUE THREAD

**Issue by tomalla5120x** [NationalSecurityAgency/ghidra#4628]
**Describe the bug**
When trying to parse a C header where a `#pragma` directive is inside an enum definition, a syntax error is produced.

**To Reproduce**
Parse the following header file:

```C
enum test_enum
{
  FIELD1,
#pragma endregion
  FIELD2
};
```
It produces the following syntax error:

![image](https://user-images.githubusercontent.com/15930205/193104493-1d968ab9-b7e0-46cf-bd35-0be2a70b4b7c.png)

If you comment out the `#pragma` directive the C parser succeeds:

```C
enum test_enum
{
  FIELD1,
//#pragma endregion
  FIELD2
};
```

**Expected behavior**
A successful parse of enum definitions with intermingled `#pragma` directives.

**Environment:**
 - OS: Windows 7
 - Java Version: 12.0.1
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official GitHub distro

**Additional context**
I'm trying to parse the WinAPI header file `combaseapi.h` which contains the following convoluted typedef-ed enum definition:

```C
#pragma region Application Family

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)

/* Flags for Synchronization API and Classes */

typedef enum tagCOWAIT_FLAGS
{
  COWAIT_DEFAULT = 0,
  COWAIT_WAITALL = 1,
  COWAIT_ALERTABLE = 2,
  COWAIT_INPUTAVAILABLE = 4,

#endif // WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
#pragma endregion

#pragma region Desktop Family

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)

  COWAIT_DISPATCH_CALLS = 8,
  COWAIT_DISPATCH_WINDOW_MESSAGES = 0x10,

#endif // WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
#pragma endregion

#pragma region Application Family

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)

}COWAIT_FLAGS;

#endif // WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
#pragma endregion
```
As you can see the enum definition contains `#if`, `#endif` and `#pragma` directives mixed in. It is preprocessed into the following (empty lines removed from the result for brevity):

```C
 #pragma region Application Family
/// #if 1 ===true
typedef enum tagCOWAIT_FLAGS
{
  COWAIT_DEFAULT = 0,
  COWAIT_WAITALL = 1,
  COWAIT_ALERTABLE = 2,
  COWAIT_INPUTAVAILABLE = 4,
/// #endif ===true
 #pragma endregion
 #pragma region Desktop Family
/// #if 1 ===true
  COWAIT_DISPATCH_CALLS = 8,
  COWAIT_DISPATCH_WINDOW_MESSAGES = 0x10,
/// #endif ===true
 #pragma endregion
 #pragma region Application Family
/// #if 1 ===true
}COWAIT_FLAGS;
/// #endif ===true
 #pragma endregion
```
The C parser failed on the very first `#pragma endregion` directive inside the definition of the `COWAIT_FLAGS` enum.

**Comment by emteere** [comment]
Thanks for reporting the issue.

There are many changes that will soon be checked in for the CParser.
The above issue should be fixed in the soon to be committed branch.

**Comment by emteere** [comment]
closed this as [completed](https://github.com/NationalSecurityAgency/ghidra/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/NationalSecurityAgency/ghidra/commit/e42c1f1f3263e192d5d9042c14f1f25413931aa0
