### ISSUE TITLE
Ghidra app icon flaky on Ubuntu

### ISSUE THREAD

**Issue by b33f00d** [NationalSecurityAgency/ghidra#463]
I was wondering how I could add a Ghidra icon to the app on linux? I don't seem to have an icon.

Thanks

**Comment by ryanmkurtz** [comment]
What distro are you running?  It might be a bug.

**Comment by yuungH4x0r** [comment]
Im running ubuntu 18.04

**Comment by yuungH4x0r** [comment]
I noticed when I open up the ghidra.ico in the support directory it just shows a static image not sure if thats the icon its using for the app icon

**Comment by ryanmkurtz** [comment]
For some reason the dock icon is flaky in Ubuntu.  If you resize the dock when the Ghidra front-end GUI is up, does the icon magically appear?

**Comment by yuungH4x0r** [comment]
yes it actually does

**Comment by ryanmkurtz** [comment]
Yea that's a known bug...I'll switch your question over to a bug report.

**Comment by ryanmkurtz** [comment]
[This](https://github.com/NationalSecurityAgency/ghidra/blob/4ce178c419b0ce070d531951d8c88b690c0b9097/Ghidra/Features/Base/src/main/java/ghidra/framework/main/GhidraApplicationInformationDisplayFactory.java#L34) is the code that sets up the application icon.  I think it might a Java-problem, because the image has rough edges when it appears...it seems to be failing to choose the best size icon for the dock side.  Ideally the icon should always look clear, and certainly always visible.

**Comment by vanquishsecurity2** [comment]
I would love to see this working on Ubuntu/Debian 19.X as I like to create a launcher on the Desktop and select the ICON to go with it.

Thanks for all of your hard work!

**Comment by ReVoLt112** [comment]
i fixed the ico file in Gimp to work with Ubuntu
[ghidra_ico.zip](https://github.com/NationalSecurityAgency/ghidra/files/3853902/ghidra_ico.zip)

**Comment by ryanmkurtz** [comment]
Thanks I'll give it a try.  What did you do to fix it?

**Comment by ReVoLt112** [comment]
Added some more sizes to the icon and disabled compression for the 256x256 layer. But the icon still wont show in the taskbar. I think the reason is that a different ico file is used in the sourcecode

**Comment by ryanmkurtz** [comment]
Yea that ion is built up programmatically here:

https://github.com/NationalSecurityAgency/ghidra/blob/4ce178c419b0ce070d531951d8c88b690c0b9097/Ghidra/Features/Base/src/main/java/ghidra/framework/main/GhidraApplicationInformationDisplayFactory.java#L34-L44

What additional sizes did you add?

**Comment by ReVoLt112** [comment]
6x6
20x20
72x72
96x96

looked these up from other working icons

**Comment by FedericoHeichou** [comment]
Any news about how to solve this?

**Comment by dev747368** [comment]
This one seemed to fall thru the cracks.  
I looked at this way back when, and if I remember, correctly, it seemed to be related to the order of creation of the app's root window and the splash screen window confusing java swing.  I'll put this back on my todo list.

**Comment by dev747368** [comment]
Summary of this issue so far: it seems to be a ubuntu dock issue, with no real java based workaround or accommodation.  

copy/pasted from the dash-to-dock github issue I added a comment to:

Basically, even though Ghidra is using java methods to set the application icon for its window, the icon in the Ubuntu dock is blank until you force the dock to refresh by resizing it in Ubuntu's appearance settings... at which point the icon starts to show what it should.

I've poked around a little and have a small java jshell snippet that can be run to show the problem. Summary: when there are multiple java windows opened, the icon of the first JFrame ever opened by the application is what is used by the dock. If that JFrame is hidden / re-shown, it clears the dock icon and locks the dock icon from changing again. Conversely, if that first JFrame isn't ever hidden / re-shown, the application's dock icon updates as expected.

[ubuntu_icon_issue.jshell.txt](https://github.com/NationalSecurityAgency/ghidra/files/5875891/ubuntu_icon_issue.jshell.txt)

You can execute it by running: "jshell --startup ubuntu_icon_issue.jshell" or by just pasting it into a jshell session.

Note: this example shows the issue 90% of the time on my workstation. Occasionally timing issues might break the example from working as expected.

**Comment by TheMatt2** [comment]
Is this issue tracked by Ubuntu?

**Comment by dev747368** [comment]
@TheMatt2 I'm not 100% positive that my contribution to the "Icons not refreshing...." ticket (linked just a few entries up ^^^ that way) was the right place.  If you are more knowledgeable about Ubuntu reporting procedures, feel free to do that or direct me.

**Comment by TheMatt2** [comment]
I see. Unfortunately, I possess no such powers.

**Comment by sunset1204** [comment]
> 8x8 //forgot this 20x20 72x72 96x96
> 
> looked these up from other working icons



> Yea that icon is built up programmatically here:
> 
> https://github.com/NationalSecurityAgency/ghidra/blob/4ce178c419b0ce070d531951d8c88b690c0b9097/Ghidra/Features/Base/src/main/java/ghidra/framework/main/GhidraApplicationInformationDisplayFactory.java#L34-L44
> 
> What additional sizes did you add?

Hello, I use Ubuntu 20.04 and dash to dock. When I use Ghidra, icon not working. How to fix this, thank you.

**Comment by ryanmkurtz** [comment]
This actually seems to be working correctly now on Ubuntu 22.04.

**Comment by dev747368** [comment]
can confirm, seems to be working on 22.04.  Closing.
