### ISSUE TITLE
Add precompiled .deb and .rpm packages

### ISSUE THREAD

**Issue by erkinalp** [NationalSecurityAgency/ghidra#4637]
**Is your feature request related to a problem? Please describe.**
Ghidra would be used much wider if it had .deb and .rpm packages.

**Describe the solution you'd like**
As title says.

**Describe alternatives you've considered**
Manually compiling ghidra.

**Additional context**
Ubuntu, which uses .deb, is the most commonly used Linux distribution.

**Comment by ryanmkurtz** [comment]
Thank you for the reasonable suggestion.  Unfortunately, we have no plans to distribute official Ghidra releases in ways other than the standalone .zip file we put up on GitHub.
