### ISSUE TITLE
Build failure when MachineLearning extension is installed

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4644]
**Describe the bug**
Building Ghidra will fail when the MachineLearning extension is already installed in Ghidra. 

**To Reproduce**
1. Build Ghidra
2. Install the MachineLearning extension
3. Attempt to build Ghidra again 
4. See failure during the help build task due to a classpath conflict.

**Expected behavior**
The build should succeed.

**Additional context**
Deleting the installed MachineLearning folder from the user extensions directory allows the build to succeed.

**Comment by ryanmkurtz** [comment]
Thanks, I'm reproducing with any installed extension from the repo.
