### ISSUE TITLE
Request:  No project on startup option

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4650]
**Is your feature request related to a problem? Please describe.**
I work with a lot of shared projects, mostly all and switch between them and have multiple frontends throughout working with the different repos.  I would like a tool option to not try to open the last project when opening the front end

**Describe the solution you'd like**
A checkbox option in front end's `Tool Options`->`Tool` to start the front end with no project selected allowing me to choose to reopen without have to go through the process of `this project is already locked` because I have already opened a previous front end.  

**Describe alternatives you've considered**
Just have to click through a few things to ack that the other front end has a repo locked and then choose the other repo for this frontend

**Comment by daiplusplus** [comment]
(With apologies for any possible thread necromancy)

For the benefit of anyone looking for this option, it's here:

Step 1:

Open the _Tool Options_ window for the main Ghidra project window.

![image](https://github.com/user-attachments/assets/8a428754-8d47-462c-86d5-10526ad8a2a1)

Step 2:

Uncheck the "Restore previous project" checkbox.

![image](https://github.com/user-attachments/assets/c87ea81a-a840-4218-8f80-08a61d817024)
