### ISSUE TITLE
EnumDataType setLength() needs improved length validation

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4654]
**Describe the bug**
Working in a shared project, I came across DTM throwing endless amounts of errors.  All the traces were the result of a enums with a large length value.  I don't know the reasoning for whoever did this, but think lengths of like 40.

For example, index out of bounds
https://github.com/NationalSecurityAgency/ghidra/blob/35b58b31058663b4ed0ffed642149e28b71e5675/Ghidra/Features/Base/src/main/java/ghidra/app/util/html/EnumDataTypeHTMLRepresentation.java#L115

It looks like a created enum data type can have setLength called and the length is not validated, just the current values validated against the new length.   Looks to be a missing `length < 1 && length > 8`. 

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: 11.0.10
 - Ghidra Version: 10.1.5
 - Ghidra Origin: github

**Comment by mumbel** [comment]
I know the enums we care about and these are not them, so i just deleted everything bad to get DTM happy again (I may undo and fix, but for now they're just gone)
```
for dt in currentProgram.getDataTypeManager().getAllDataTypes():
    if isinstance(dt, (ghidra.program.database.data.EnumDB, ghidra.program.model.data.EnumDataType)):
        if not dt.getLength() in [1,2,4,8]:
            currentProgram.getDataTypeManager().remove(dt, monitor)
```

**Comment by mumbel** [comment]
I'm fairly ignorant on this data flow.  If I load another image, with an oversized enum, when this fix is released, do you think I'll hit that index out of bounds exception (so just need to iterate all the enums and i'll probably just set to 4byte vs deleting) or does this prevent that (or does it internally break the oversized enums to not even work in DTM anymore).

**Comment by dragonmacher** [comment]
The fix for this ticket is for preventing the enum length from being set to a bad value in the future. If you still have types with a bad size, then those will likely still cause exceptions.  In that case, you will have to fix those up yourself.
