### ISSUE TITLE
Debug information from Mach-O object file not applied

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#4659]
**Describe the bug**
```C
struct point {
        double x;
        double y;
};

struct point inc(struct point p) {
        p.x += 1;
        p.y += 1;
        return p;
}
```
Compiled with `clang -g -c test.c` on macOS.
A clear and concise description of the bug.

**To Reproduce**
- Load test.o
- Run autoanalysis

**Expected behavior**
Type information should be imported

**Attachments**
[test.zip](https://github.com/NationalSecurityAgency/ghidra/files/9787328/test.zip)

**Environment (please complete the following information):**
 - OS: macOS 10.15
 - Java Version: [e.g. 11.0]
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official

**Comment by dev747368** [comment]
there are 2 issues your binary shows.

The MachO loader in master fails when trying to import this binary.
The DWARF analyzer isn't finding the debuginfo sections (because it assumes they will be in a dsym file, which isn't the case for .o's), and that they have "__" name prefix.
