### ISSUE TITLE
Only question marks are displayed after file analyzing.

### ISSUE THREAD

**Issue by Sa1riil** [NationalSecurityAgency/ghidra#466]
I do not know if the resulted information after i imported the file and started analyzing it, is because of a lack of functionality or because of a bug: I start analyzing the following file which is a keygen seen as malware: `https://www.virustotal.com/gui/file/51700ec83a85b3dc7ac7358914218ba311b2ca1ba4ea72a241a84cd9c9180c4e/behavior/Tencent%20HABO) (file's MD5: f0c6fe75953566c00a7dc167e0989d1e)` - i suspect it is packed.
I have enabled all analyzers less 'Condense Filter Bytes (Prototype)'. I have imported it using the following default options:

> Imported file: Format: Portable Executable (PE)
> Language: x96:LE:32:default:windows

The first error appears imediatly after i imported it: I suspect it because the file is packed as i mentioned above. 

> Error:

>PDB> Incomplete PDB information (GUID/Signature and/or age) associated with this program.
Either the program is not a PE, or it was not compiled with debug information.
Windows x86 PE RTTI Analyzer> Couldn't find type info structure.
AggressiveInstructionFinder> Aggressive Instruction Finder Not Run.  Too few functions defined for proper analysis!

>Additional information fater the file was imported:
----- Loading C:/Users/g_bondrila/Downloads/2.exe -----
2.exe: failed to create pointer at 0045bd68: Conflicting data exists at address 0045bd68 to 0045bd6b
2.exe: failed to create pointer at 0045bd6c: Conflicting data exists at address 0045bd6c to 0045bd6f
2.exe: failed to create word at 0045be26: Conflicting data exists at address 0045be1a to 0045be26
2.exe: failed to create pointer at 0045bd70: Conflicting data exists at address 0045bd70 to 0045bd73
2.exe: failed to create word at 0045be36: Conflicting data exists at address 0045be28 to 0045be36
2.exe: failed to create pointer at 0045bd74: Conflicting data exists at address 0045bd74 to 0045bd77
2.exe: failed to create word at 0045be46: Conflicting data exists at address 0045be38 to 0045be46
2.exe: failed to create pointer at 0045bd78: Conflicting data exists at address 0045bd78 to 0045bd7b
2.exe: failed to create word at 0045be54: Conflicting data exists at address 0045be48 to 0045be54
2.exe: failed to create pointer at 0045bd7c: Conflicting data exists at address 0045bd7c to 0045bd7f
2.exe: failed to create pointer at 0045bd84: Conflicting data exists at address 0045bd84 to 0045bd87
2.exe: failed to create pointer at 0045bd8c: Conflicting data exists at address 0045bd8c to 0045bd8f
2.exe: failed to create pointer at 0045bd94: Conflicting data exists at address 0045bd94 to 0045bd97
2.exe: failed to create word at 0045be82: Conflicting data exists at address 0045be72 to 0045be82
2.exe: failed to create pointer at 0045bd9c: Conflicting data exists at address 0045bd9c to 0045bd9f
2.exe: failed to create word at 0045be8a: Conflicting data exists at address 0045be84 to 0045be8a
2.exe: failed to create pointer at 0045bda4: Conflicting data exists at address 0045bda4 to 0045bda7
2.exe: failed to create word at 0045be98: Conflicting data exists at address 0045be8c to 0045be98
2.exe: failed to create pointer at 0045bdac: Conflicting data exists at address 0045bdac to 0045bdaf
2.exe: failed to create pointer at 0045bdb4: Conflicting data exists at address 0045bdb4 to 0045bdb7
2.exe: failed to create BitmapResource at 0043ba4c: BitmapResource may only be applied on initialized memory (0043ba4c)
2.exe: failed to create BitmapResource at 0043f6dc: BitmapResource may only be applied on initialized memory (0043f6dc)
2.exe: failed to create BitmapResource at 0043f78c: BitmapResource may only be applied on initialized memory (0043f78c)
2.exe: failed to create BitmapResource at 004409f0: BitmapResource may only be applied on initialized memory (004409f0)
2.exe: failed to create BitmapResource at 00441c58: Failed to resolve data length for BitmapResource
2.exe: failed to create IconResource at 00446140: Failed to resolve data length for IconResource
2.exe: failed to create IconResource at 004471e8: Failed to resolve data length for IconResource
2.exe: failed to create IconResource at 00448290: Failed to resolve data length for IconResource
Index 1024 out of bounds for length 1024
Index 1024 out of bounds for length 1024
2.exe: failed to create GroupIconResource at 004534c0: Insufficent memory at address 004534c0 (length: 438178 bytes)
2.exe: failed to create GroupIconResource at 004534e8: Insufficent memory at address 004534e8 (length: 60094 bytes)
2.exe: failed to create TerminatedCString at 0045b9ac: Conflicting data exists at address 0045bcb4 to 0045bcb7
Searching for referenced library: USER32.DLL ...
Found and imported external library: C:\WINDOWS\SysWOW64\USER32.DLL
Searching for referenced library: COMCTL32.DLL ...
WARNING! Using existing exports file for COMCTL32.DLL which may not be an exact match
Found and imported external library: C:\WINDOWS\SysWOW64\COMCTL32.DLL
Searching for referenced library: COMDLG32.DLL ...
WARNING! Using existing exports file for COMDLG32.DLL which may not be an exact match
Found and imported external library: C:\WINDOWS\SysWOW64\COMDLG32.DLL
Searching for referenced library: SHELL32.DLL ...
Found and imported external library: C:\WINDOWS\SysWOW64\SHELL32.DLL
Searching for referenced library: WINMM.DLL ...
WARNING! Using existing exports file for WINMM.DLL which may not be an exact match
Found and imported external library: C:\WINDOWS\SysWOW64\WINMM.DLL
Searching for referenced library: KERNEL32.DLL ...
Found and imported external library: C:\WINDOWS\SysWOW64\KERNEL32.DLL
Searching for referenced library: GDI32.DLL ...
Found and imported external library: C:\WINDOWS\SysWOW64\GDI32.DLL
Searching for referenced library: OLE32.DLL ...
Found and imported external library: C:\WINDOWS\SysWOW64\OLE32.DLL
Finished importing referenced libraries for: 2.exe
  [KERNEL32.DLL] -> not found
  [COMCTL32.DLL] -> not found
  [COMDLG32.DLL] -> not found
  [GDI32.DLL] -> not found
  [OLE32.DLL] -> not found
  [SHELL32.DLL] -> not found
  [USER32.DLL] -> not found
  [WINMM.DLL] -> not found

Kind regards,

**Comment by emteere** [comment]
Ghidra will not automatically unpack your file.
You can bring up the entropy bar to see if an area is packed.

The other errors are normal.
The PDB analyzer is turned on, but a PDB can't be found.
The RTTI analyzer is on, and found something that looked like an RTTI structure but something was wrong with it.
The Aggressive instruction finder needs patterns of existing function starts to perform any analysis.  Not enough code has been found.

From the other errors, it appears the Resource section and possibly the PE headers have been doctored in your sample in order to obfuscate it.  Possibly there is code in the resource section masquerading as icons, and other resources.

You are dealing with malware that is most likely attempting to subvert automated RE analysis.  You may need to perform more detailed analysis on the code by hand before automated techniques can be applied to the code.

**Comment by Sa1riil** [comment]
> Ghidra will not automatically unpack your file.
> You can bring up the entropy bar to see if an area is packed.
> 
> The other errors are normal.
> The PDB analyzer is turned on, but a PDB can't be found.
> The RTTI analyzer is on, and found something that looked like an RTTI structure but something was wrong with it.
> The Aggressive instruction finder needs patterns of existing function starts to perform any analysis. Not enough code has been found.
> 
> From the other errors, it appears the Resource section and possibly the PE headers have been doctored in your sample in order to obfuscate it. Possibly there is code in the resource section masquerading as icons, and other resources.
> 
> You are dealing with malware that is most likely attempting to subvert automated RE analysis. You may need to perform more detailed analysis on the code by hand before automated techniques can be applied to the code.

Thank you for your answer.
