### ISSUE TITLE
C Parser can't parse (LONG64 const *)

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#4660]
**Describe the bug**
Ghidra can't parse the following C code:
```
typedef long long TEST_TYPE_A;
void funcA(TEST_TYPE_A const * arg);
void funcB(void)
{
    funcA((TEST_TYPE_A const *)0);
}
```
The error is:
```
C Parser:  Encountered errors during parse.
         in /home/.../bug.h near line 6
Error: Encountered " <CONST> "const "" at line 7, column 24.
Was expecting one of:
    "(" ...
    ")" ...
    "[" ...
... (removed for brevity)
    "*" ...
    "&" ...
    
         near token: TEST_TYPE_A
Possibly Undefined : *
         Last Valid Datatype: funcB
         Check around /home/.../CParserPlugin.out around line: 8
```
CParserPlugin.out is:
```

#line 1: "/home/.../bug.h"
typedef long long TEST_TYPE_A;
void funcA(TEST_TYPE_A const * arg);
void funcB(void)
{
    funcA((TEST_TYPE_A const *)0);
}
```
(Line 8 is `}`)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 17.0.4
 - Ghidra Version: 10.2 master 2d5762a45e9a29d71a07758d742c6c385cec50ad
 - Ghidra Origin:  locally built

<img width="666" alt="typedef bug" src="https://user-images.githubusercontent.com/16713498/195882991-f1cb134c-9ec4-4f7f-8d51-0054524420a2.png">

**Additional context**
This error occurs when Ghidra parses Windows WDK wdm.h at function `RtlCheckBit`:
```
__forceinline BOOLEAN RtlCheckBit(PRTL_BITMAP BitMapHeader, ULONG BitPosition)
{
    return _bittest64((LONG64 const *)BitMapHeader->Buffer, (LONG64)BitPosition);
}
```

**Comment by emteere** [comment]
Will take a look.

How does the parse look otherwise if you move the const before the LONG64, which the parser does accept?
Hoping most of the issues have been sqaushed with the latest set of changes.

You can also try using the CreateExampleGDTArchiveScript and creating a new one, say CreateWDKGDTArchiveScript, and putting the files/args you are using.  You might find easier to run and change.

**Comment by xiaoyinl** [comment]
@emteere 
> How does the parse look otherwise if you move the const before the LONG64, which the parser does accept?
Hoping most of the issues have been sqaushed with the latest set of changes.

Actually both `const LONG64 *` and `long long const *` are accepted. Only `LONG64 const *` fails.

> You can also try using the CreateExampleGDTArchiveScript and creating a new one, say CreateWDKGDTArchiveScript, and putting the files/args you are using. You might find easier to run and change.

Thank you for the suggestion. Will try.

**Comment by xiaoyinl** [comment]
> How does the parse look otherwise if you move the const before the LONG64, which the parser does accept?
Hoping most of the issues have been sqaushed with the latest set of changes.

Indeed most issues are fixed in latest master. There are three remaining issues before the preprocessed WDK header can be parsed successfully:
1. This issue. As you said, this can be worked around by changing `(LONG64 const *)` to `(const LONG64 *)`
2. #3526 . I worked around it by deleting the definition of function `RtlxQueryRegistryValues`
3. The enum `_POOL_TYPE` is forward declared. The code looks like this:
```
typedef  enum _POOL_TYPE POOL_TYPE;
typedef PVOID ALLOCATE_FUNCTION (POOL_TYPE PoolType, SIZE_T NumberOfBytes, ULONG Tag);
typedef   enum _POOL_TYPE {
    NonPagedPool,
    // ...omitted...
}   POOL_TYPE;
```
The C Parser fails to parse `POOL_TYPE PoolType`. The error message is:
```
CParser Messages:
Problem with type POOL_TYPE : null
```
This can be worked around by replacing the forward declaration with the actual enum `_POOL_TYPE` definition.

After making the three changes above, the header can be successfully parsed.
