### ISSUE TITLE
Documentation: How to build lldb with language bindings for Java?

### ISSUE THREAD

**Issue by watcher00090** [NationalSecurityAgency/ghidra#4662]
Hi folks,

I will quote the What's New guide for Ghidra 10.1:

"Working toward debugging macOS targets, we've added support for LLDB. Currently, some effort is required on the user's end to clone, patch, and build LLDB with language bindings for Java. Once done, the new connectors for LLDB can be used in the normal fashion. While intended for macOS, these connectors also work on Linux, and may work on Windows, too. This offers an alternative for those who prefer lldb to gdb."

Could someone please describe or produce a link to documentation which describes how to build LLDB with language bindings for Java? 

Thank you,
James Pedersen

[Ghidra Whats New.txt](https://github.com/NationalSecurityAgency/ghidra/files/9790921/Ghidra.Whats.New.txt)

**Comment by d-millar** [comment]
https://github.com/NationalSecurityAgency/ghidra/Ghidra/Debug/Debugger-swig-lldb/InstructionsForBuildingLLDBInterface.txt describes how to set lldb up, but Discussion #3654 might also help

**Comment by d-millar** [comment]
oops, correction: #3645

**Comment by watcher00090** [comment]
> https://github.com/NationalSecurityAgency/ghidra/Ghidra/Debug/Debugger-swig-lldb/InstructionsForBuildingLLDBInterface.txt describes how to set lldb up, but Discussion #3654 might also help

This is a broken link. I'll assume you mean:

https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Debug/Debugger-swig-lldb/InstructionsForBuildingLLDBInterface.txt

Thanks @d-millar, this is what I was looking for.
