### ISSUE TITLE
Propagate renamed exports

### ISSUE THREAD

**Issue by Martmists-GH** [NationalSecurityAgency/ghidra#4663]
**Is your feature request related to a problem? Please describe.**
I'm working on reverse-engineering 3DS files, which act like DLLs except their symbols are referenced by segment+offset. This means to resolve references between files, we need to create stub labels for functions and data during importing. These symbols are then linked together using the externals manager.

The problem we're now having, is that if we're renaming these functions, they don't propagate that renaming to the exports, which means thunked functions in other programs don't get renamed. 

**Describe the solution you'd like**
When a function which is an export is renamed, this should propagate to all modules that use the function as import.

**Describe alternatives you've considered**
We considered using a script for renaming these functions, but as things like RTTI analysis also perform renaming outside of our control, this is not a perfect option.

**Additional context**

**Comment by ghidra1** [comment]
We do not currently maintain external back-references between programs.  What you suggest would require searching all program's in your project to find those that refer to a given entry-point function which happened to be renamed.  This becomes a bigger issue if/when we add support for the external links to refer to programs contained within other projects (e.g., Ghidra Server) via a Ghidra URL.  In this later case the ability to propgate changes across projects could be complicated by access/permission issues as well.  This would also have to contend with establishing checkouts which could be problematic.
