### ISSUE TITLE
decompiler : `Pcode: Decoding error: Expecting <doc> but did not scan an element`

### ISSUE THREAD

**Issue by fenugrec** [NationalSecurityAgency/ghidra#4665]
**Describe the bug**
cannot decompile a certain function in this attached DLL. Disasm seems OK.

**To Reproduce**
- load attached DLL
- autoanalyze
- go to 0x1000aeaf

**Expected behavior**
some kind of decompilation.

**Screenshots**
Just an error message in the decomp window,
`Pcode: Decoding error: Expecting <doc> but did not scan an element`

**Attachments**
[sclock2.zip](https://github.com/NationalSecurityAgency/ghidra/files/9793372/sclock2.zip)

**Environment (please complete the following information):**
 - OS: archlinux
 - Java Version: 18.0.2
 - Ghidra Version: 10.1.5.r1199.03bd4b45d

**Comment by caheckman** [comment]
This bug is fixed in e98ddcc3b1df74c6dc468444ea7f4521af5d7265
