### ISSUE TITLE
MIPS address setting macroses

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#467]
For now Ghidra doesn't apply `lui`/`addiu` pairs, and sets reference only at the moment of the address using. But it will be great to find all references to some address, that was created from two parts.

Is it possible to add such functionality?

**Comment by emteere** [comment]
There is a setting in the MipsConstantRefernenceAnalyzer - Mark dual instruction references that should do what you want.  It is off by default.
