### ISSUE TITLE
C Parser fails to parse string literal concatenation

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#4677]
**Describe the bug**
C Parser fails to parse string literal concatenation, both single line and multi line: i.e. `"str1" "str2"` or
```
char a[] = "abc"
           "def";
```

**To Reproduce**
Parse the following code:
```
void singleLineStrings(void)
{
    char a[] = "Hello " "World";
}
void multilineStrings(void)
{
    char b[] = "This is a "
               "multiline string.";
}
```
The C Pasrser fails to parse both functions.

**Environment (please complete the following information):**
  - OS: Linux
  - Java Version: 17.0.4
  -  Ghidra Version: 10.2 master https://github.com/NationalSecurityAgency/ghidra/commit/480f1e3a8bed20854bf5c2ac68f2ee48a33db966
  -  Ghidra Origin: locally built

**Additional context**
This occurs when parsing Windows WDK wdm.h (the original file, not preprocessed by VS) at
```
_When_(Wait==1, __drv_reportError("Caution: 'Wait' argument does not provide"
                                      " any synchronization guarantees, only a hint"
                                      " to the system that the thread will immediately"
                                      " issue a wait operation"))
```

**Comment by ryanmkurtz** [comment]
Closed by 3bab8e42842da1847bfa012fac40a398f30d28b5
