### ISSUE TITLE
Analyze Headless Ownership issue between users

### ISSUE THREAD

**Issue by whoismikem** [NationalSecurityAgency/ghidra#468]
Question is related to closed issue [Project Ownership Issue](https://github.com/NationalSecurityAgency/ghidra/issues/172). Running into this problem using ghidra in headless mode when bulk processing and sharing projects with multiple users on different machines. Users are unable to open the projects for review and analysis as they see the same as error as reported. 
How does one use ghidra headless analysis to bulk process binaries and share the projects with others without this getting in the way and without server/client approach?

**Comment by ghidra1** [comment]
The only means to accomplish this is to modify the project ownership within the project properties file (project.prp) in the root of the project (*.rep) directory.
