### ISSUE TITLE
Unable to assemble an x86-64 MOV instruction

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#4688]
**Describe the bug**
Trying to patch an instruction to `MOV RDX, 0xffffffffffffffff` is not accepted ("Invalid instruction and/or prefix"): entering the last `f` is what makes the instruction fail.

Workaround: `MOV RDX, -1` works

**To Reproduce**
1. Go to the `Listing` view
2. Press `ctrl-shift-g` on one of the instruction
3. Try to change it to `MOV RDX, 0xffffffffffffffff`

**Expected behavior**
`0xffffffffffffffff` is `UINT64_MAX` and should be accepted.

**Screenshots**
![mov-1](https://user-images.githubusercontent.com/34467/197633097-edbd930a-4bf9-460c-8163-b9db5c144cc8.gif)

**Environment (please complete the following information):**
 - OS: Archlinux
 - Java Version: 11.0.17
 - Ghidra Version: 10.1.5
 - Ghidra Origin: Archlinux official packages

**Comment by mumbel** [comment]
seeing the same thing in master (2a86142a8d2496016fccc53abacc5d60671d5eb2)

**Comment by GhidorahRex** [comment]
This is a long-standing issue we've had with supporting unsigned 64-bit integers due to a limitation in integer size in Java.
