### ISSUE TITLE
What does it mean to see "Section [name] is not aligned!" on the console when importing PE executables?

### ISSUE THREAD

**Issue by gmestanley** [NationalSecurityAgency/ghidra#4698]
I opened Ghidra to import a PE file that I modified by hand on a hex editor, in which I included a hand-made section. The executable had header values for a initialized data size of 0x852400 and image size (both in memory) of 0xD7D000, which I increased to 0x853400 and 0xD7E000 respectively. Following the values of section alignment in file and in memory, the section had sizes in that way of 0x200 and 0x1000, and was placed at 0x84AE00 in the file (with a virtual address of 0xD7C200), which was the size of the original unmodified exe. 

![image](https://user-images.githubusercontent.com/25189686/198891995-352dd9c9-b903-4391-8d66-d3c6c1bc910d.png)

This is what I get when importing it. In the CodeBrowser tool's Listing window, it looks like a normal executable, but this does give a clue as to why it doesn't work. I'd like more elaboration on it however, because I tried to align the section correctly; in fact, trying the same technique with another PE executable worked, and Ghidra didn't give me the "Section is not aligned" warning with it. That file had initialized data and image size values of 0x317000 and 0x3D2000, although it also had equal in-memory and in-file section alignments (0x1000).

In both executables, the section also had read-only and "contains initialized data" characteristics if that helps with anything. The header value for the amount of sections was of course also increased (the main file being talked about here had 6 sections, while the other file where putting in the additional section worked originally had 4).

**Comment by ryanmkurtz** [comment]
Have you examined our code yet?  Also #327 and #418 are worth reading for some background on why this code was changed to what it currently is.
https://github.com/NationalSecurityAgency/ghidra/blob/0bd1c24b944d77f811bc009a6763ff576779bb1f/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/FileHeader.java#L334-L363
