### ISSUE TITLE
Ghidra doesn't handle floats in the MSVC x86-64 calling convention properly

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#4708]
Given a function like:
```c++
bool f(float y, longlong x)
```

Ghidra assigns `y` to xmm0 and `x` to rcx. However `x` is actually passed on `rdx`.

"Example of argument passing 3 - mixed ints and floats" on https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170&viewFallbackFrom=vs-2017 has a good example of how this is supposed to work.

**Environment (please complete the following information):**
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official

**Comment by jrmuizel** [comment]
@ghidracadabra it looks like this was perhaps fixed by https://github.com/NationalSecurityAgency/ghidra/commit/91eb96f109cc01d4b7e624c3caa6fd4f8fdf8fbe?

**Comment by ghidracadabra** [comment]
@jrmuizel Correct.  Note that this fix is included in 10.2, which was just released.
