### ISSUE TITLE
Add #107 Jython vulnerability to the Security Advisories

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#4712]
Since 10.2 is released, could we add #107:  "Uncontrolled Search Path Element when executing CMD." to the [Security Advisories](https://github.com/NationalSecurityAgency/ghidra/security/advisories)?

**Comment by ryanmkurtz** [comment]
I'll bring it up to the team.

**Comment by ryanmkurtz** [comment]
https://github.com/NationalSecurityAgency/ghidra/security/advisories/GHSA-pr2h-5qhx-9544
