### ISSUE TITLE
ARM disassembler for ARM:LE:32:v5t:default no longer works in Ghidra 10.2

### ISSUE THREAD

**Issue by johanngan** [NationalSecurityAgency/ghidra#4717]
**Describe the bug**
The ARM disassembler for language ARM:LE:32:v5t:default no longer works in Ghidra 10.2.

I assume the same issue might apply for other ARM versions, but I haven't checked.

**To Reproduce**
1. Create a new project.
2. Open the CodeBrowser.
3. Import an armv5t executable appropriate for the language setting ARM:LE:32:v5t:default, run analysis, and navigate to any function.
4. Observe that instructions are not disassembled. Explicitly disassembling at the offset gives an error with the message "Error [Bad Instruction]: Unable to resolve constructor at \<address\>".

**Expected behavior**
ARM disassembly should work. It used to work in Ghidra 10.1.2 (I've also tested Ghidra 10.1.5, and it still works there).

**Screenshots**
Disassembly worked in Ghidra 10.1.2: ![Working disassembly](https://user-images.githubusercontent.com/26724430/200147708-ddac3923-c4e9-4007-b048-3b12e2293f27.png)

Disassembly no longer works in Ghidra 10.2: ![Failed disassembly](https://user-images.githubusercontent.com/26724430/200147710-204a8081-1c3d-4898-a443-837dd58003a0.png)

**Attachments**
Here's a simple, no-op C program cross-compiled for armv5te (but the issue remains if compiled for armv5t) with `arm-none-eabi-gcc`: [a.out.zip](https://github.com/NationalSecurityAgency/ghidra/files/9944909/a.out.zip). The above screenshots are taken using this binary (`main()` is at offset 0x8000).

**Environment (please complete the following information):**
 - OS: macOS 11.7, but I've also tested on Windows 10 and the same issue occurs
 - Java Version: 17.0.1
 - Ghidra Version: 10.2
 - Ghidra Origin: official GitHub distro

**Comment by GaryOderNichts** [comment]
I'm having the same issue with `ARM:BE:32:v5t` and `ARM:BE:32:v5`.
Interestingly THUMB instructions can be disassembled (for v5t), but ARM will throw the error above.

**Comment by ryanmkurtz** [comment]
Fixed by 3cf13c25331a4d49184c05d58418e1978abba6cf
