### ISSUE TITLE
Is there any documentation for pspec and cspec files?

### ISSUE THREAD

**Issue by quantumbracket** [NationalSecurityAgency/ghidra#472]

**Comment by Escapingbug** [comment]
There are some refs at [here](https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Framework/SoftwareModeling/data/languages). But I'm also kind of feeling confused here, as many fields are not documented..

**Comment by bdemick** [comment]
Completely agree. I'd love to see some more extensive documentation on all of the processor-related files. The SLEIGH docs are great, but could use some more practical examples in-line vs. having to stare at the *sinc/*slaspec files for other architectures, and parse through a very large source tree to get the answers. This works, and does help with understanding the overall structure of the project, but would be much quicker if there were just a tad bit more documentation and perhaps a step-by-step overview that covers an outline for the derivation of one of the simpler existing architectures.

**Comment by rkfg** [comment]
The docs are [here](https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Features/Decompiler/src/main/doc), you'll need to `xsltproc` them to get a bunch of HTML files or a pdf. I had to install `docbook-xsl` to get the needed files for the conversion and I also changed the path in `cspec_html.xsl`. Then I ran `xsltproc cspec_html.xsl cspec.xml`.

**Comment by mumbel** [comment]
Thanks @rkfg 
Not sure if i was just missing a package or not, but on Debian I had to modify cspec_html.xsl.  Not sure if this change is correct, but it did produce html.
```
-<xsl:import href="/usr/share/sgml/docbook/xsl-stylesheets/html/chunk.xsl"/>
+<xsl:import href="/usr/share/xml/docbook/stylesheet/docbook-xsl/html/chunk.xsl"/>
```

**Comment by rkfg** [comment]
Yep, I did the same (and mentioned it, though it was pretty vague I admit).

**Comment by bdemick** [comment]
Double thanks @rkfg !

On a Mac I had to just install `docbook-xsl` via **brew** and fix up the import path:

    -<xsl:import href="/usr/share/sgml/docbook/xsl-stylesheets/html/chunk.xsl"/>
    +<xsl:import href="/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/html/chunk.xsl"/>
