### ISSUE TITLE
Unable to open mach-o executables without "__EDITLINK" segment.

### ISSUE THREAD

**Issue by kellermanrivero** [NationalSecurityAgency/ghidra#4729]
**Describe the bug**
Mach-O binaries without "__EDITLINK" segment cannot be opened. 

**To Reproduce**
1. Import a Mach-O binary without "__EDITLINK" segment.

**Expected behavior**
Able to import & analyse Mach-O executable.

**Screenshots**

**Attachments**
Cannot provide link to Apple binary here due to copyright issues, but I was analysing ISP.img4 from MacOS 12.3 (previously extracted payload using img4tool). 

**Environment (please complete the following information):**
 - OS: MacOS 13.0 (Ventura)
 - Java Version: OpenJDK 17
 - Ghidra Version:  10.2
 - Ghidra Origin: official GitHub distro

**Additional context**
I was trying to debug a Mach-O file from Apple Co-processors firmware and found this issue. After downgrade to 10.1 I was able to open the file without issues.

**Comment by ryanmkurtz** [comment]
This has been fixed by https://github.com/NationalSecurityAgency/ghidra/commit/2a4320b7a2d208ca6060f8020dd201c9b2957944 and will be available in the next patch release.
