### ISSUE TITLE
Consider seperate decompiler binary from main repo?

### ISSUE THREAD

**Issue by Escapingbug** [NationalSecurityAgency/ghidra#473]
**Is your feature request related to a problem? Please describe.**
Ghidra by its own is a very large project. Decompiler is a complicated part but seems to be self-contained enough to be separated from the main repo. This separation may allow decompiler C++ code itself to have better documentation (github page or any other form) (#452) or known better by C++ developers who have not much Java background.

Also, by applying a self-contained build system (currently makefile, or de-facto CMake solution in the future) it will make it possible to embed into other projects. This separation will make feel better to be used in such a scenario. And of course, decompiler binary only tests are good to have.

**Describe the solution you'd like**
Separate Ghidra decompiler binary C++ code to a separate repo, maybe use git submodule to initialize that when compiling along with the main repo (buildNative_*).

**Comment by despair86** [comment]
+1 to this, I use BSD and SVR4 primarily

**Comment by jstaursky** [comment]
If you are the impatient type, I have done this [here](https://github.com/jstaursky/byte-slide). Albeit, I can't guarantee feature parity indefinitely. Planning to do a thesis based on my own modifications.

**Comment by Escapingbug** [comment]
Actually, long ago I have proved that this can be done in my [repo](https://github.com/long-re/Long-decompiler). However, this is just a seperation, only decompiler tested. I have no time working on it after that, so I gave up.

But I think I made the point, decompiler part can be seperated.

**Comment by ryanmkurtz** [comment]
We have no plans in the future to separate the repos.
