### ISSUE TITLE
After update to 10.2 from 10.04 I get an error... 

### ISSUE THREAD

**Issue by port513** [NationalSecurityAgency/ghidra#4730]
~~
Traceback (most recent call last):
  File "... /ghidra_scripts/pwndra/scripts/UtilitiesGotoMain.py", line 11, in <module>
    import generic.continues.RethrowContinuesFactory as RethrowContinuesFactory
ImportError: No module named continues
~~

Have I missed something?

**Comment by ryanmkurtz** [comment]
The `RethrowContinuesFactory` has been refactored out.

**Comment by ryanmkurtz** [comment]
The change can be found here: 2e2380c927276112028d0c70bc4474385cee7b19
