### ISSUE TITLE
Ghidra issues with WinDbg dbghelp.dll and the start directory of debugged program

### ISSUE THREAD

**Issue by guccigang420** [NationalSecurityAgency/ghidra#4732]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. At the top menu select Debugger
2. Select debug {ProcessName}.exe
3. Select in dbgeng locally IN-VM

I can open the program by clicking the resume button.
The program opens and runs correctly, however the breakpoints I place are not triggered

I get a message:
SECURE: File not allowed to be loaded - C:\WINDOWS\SYSTEM32\dbghelp.dll

Which I suspect is the reason why the breakpoints are not triggered. I tried moving dbghelp.dll to some ghidra directories, and to the jvm binaries as pointed out by another fix. however, this message still keeps popping up.

Additionally, since the program I am running uses local paths instead of global paths to access it's files (such as fopen("file.txt")) it is required that it is launched from it's directory, like so

directory/of/program> ./program.exe

Instead what Ghidra does is

directory/of/ghidra> ./directory/of/program/program.exe

So now it's looking for its files, which are quite core to running the program, in the Ghidra installation directory. The workaround for this is to copy paste the entire ghidra installation to the program installation folder. This is a terrible workaround for obvious reasons.

**Expected behavior**
Breakpoints work and there is no dbghelp.dll error, especially when dbghelp.dll is present in the jvm binaries and ghidra folder, as indicated by the solution to issue #3090 https://github.com/NationalSecurityAgency/ghidra/issues/3090.

Also it is expected that the program is started from it's original directory, as if it were started manually, or at least I am given the choice from which working directory to start the program, so that it does not get confused as to where its local files are.

Definitely expected to not have to copy-paste the entire Ghidra program to the exe's installation directory just to debug the exe.

**Screenshots**
![image](https://user-images.githubusercontent.com/44866346/201076407-0fd94525-59b4-4241-a04e-c8b3b4a51af0.png)
.

**Environment (please complete the following information):**
- JVM Version: Microsoft 17.0.4.1
- OS: Windows 11 10.0 amd64
 - Ghidra Version: 10.2
 - Ghidra Origin: [official GitHub distro] 

**Additional context**

EDIT:

I appear to have fixed the dbgeng.dll issue by re-copying it in the jvm folder. I don't get the error anymore. I don't seem to get any error. But the breakpoints still do not work.

**Comment by d-millar** [comment]
@guccigang420 Sorry to hear you're having issues, although thanks for letting us know that you resolved the dbghelp location issue.

With regard to where the program executes, that is, I believe, controlled by two thing, where the executable was loaded from and what the Java user.dir value is set to.  So, for the first, if I loaded, say, notepad.exe from C:\Windows, it would run from that directory.  You can modify this behavior in several ways.  Easiest is to use the Targets windows to start "IN-VM MS dbgeng local debugger" and then use the Launch button in Objects to explicitly specify the path (and any arguments).  You can also change the properties of your analyzed executable, but, if I remember correctly, that gets a bit messy.

As far as the user.dir, you can set that explicitly by setting JAVA_USER_HOME_DIR_OVERRIDE to the location you want.  You may also be able to do it by adding "-Duser.dir=..." in the launch.bat but that also seems a bit more complicated.

None of this, unfortunately, has much bearing on the breakpoint issue.  Just as a test, could you try launching notepad.exe in the debugger?  When it stops on the initial breakpoint, hit K in the Dynamic Listing window a few lines down (i.e. on a line that's guaranteed to execute) and hit resume.  If that doesn't hit, we have a larger problem.

If that works, then the problem may have to do with where you've set the breakpoint, and the status of that code.  If you set breakpoints in the Static Listing, they only become active when the executable or dll they are in is resolved.  If, for some reason, they can't be resolved (for example, if the name in the Modules list doesn't match the program name), you have to explicitly map them in the Modules window so that the breakpoint address it mapped.

Let me know if any of this is unclear.  FIngers crossed - we'll get your setup working soon!

**Comment by guccigang420** [comment]
@d-millar I did try ./ghidraRun.bat -Duser.dir="C:\Windows\System32" and launching notepad, though ghidra gave me a message that that is not a ghidra project.
If I specify the path like you say when launching it, it still does it the following way:
directory/of/ghidra> ./path/specified/in/prompt/program.exe

With notepad there were no breakpoints active. 

![image](https://user-images.githubusercontent.com/44866346/201344067-9e593c22-4cee-4163-bd43-0f11274df539.png)

I noticed the following prompts in the debug messages:
![image](https://user-images.githubusercontent.com/44866346/201344849-380d913c-446e-4383-9d79-00bf308fc525.png)

Maybe this is somewhat helpful?

**Comment by guccigang420** [comment]
@d-millar Got this working, though it is weird. SO the breakpoints from the breakpoint list do not get automatically added, but if I find the code in teh listing, and then right click and add a hardware breakpiont, it does hit.

![image](https://user-images.githubusercontent.com/44866346/201346999-edfb99e2-f5d8-408a-bf8a-f770809c7961.png)

**Comment by guccigang420** [comment]
Though it is still quite lacking. I cannot for example hover over eax, esi, ecx and see what these registers hold. If I find a pointer to some data structure that I would like to observe, I also cannot see what is actually in that data. It would be nice if I could hover over variables in the decompiler and see their values.

**Comment by d-millar** [comment]
@guccigang420 Am looking into this now.... You are quite correct "-Duser.dir" does not behave at all like I had expected.  With a little luck, I will figure out how to set the runtime directory and get back to you.  Certainly would be better if we had an obvious way to set this.

Regarding breakpoints, yes, a little confusing.  We are, for better or worse, using the Linux model of breakpoints, which is not a great match for Windows.  In Linux, you can set a breakpoint in an executable or library that is not currently loaded into memory, and, when it loads, the debugger will ask if you want that breakpoint to become active.  Windows doesn't ask, so breakpoints stored in the static program only become active when you tell them to become active.  (Breakpoints set in the Dynamic window or in the Static window for programs that are already mapped into memory are assumed to be active on creation and can be turned on automatically.)

With respect to hovering over register, we should definitely implement that.  Now that you've mentioned it, it seems like an obviously desirable feature.  RIght now, the registers values are visible in the Registers window and in the Objects tree under Threads->Thread[N]->Registers, but a hover would be very very useful.  Thank you for that suggestion.

More soon (fingers crossed) when I figure out the path issue.

**Comment by d-millar** [comment]
OK, I think the easiest solution (and unfortunately the only one I can currently think of) is to run Ghidra from the command line in the directory of the command you wish to run.  For example, let's say Ghidra lives in C:\Program Files\ghidra_10.2_PUBLIC, my home directory is C:\Users\bob, and I wan't to run C:\Windows\System32\cmd.exe such that it defaults to starting in my home directory.  If I "cd C:\Users\bob", run "C:\Program Files\ghidra_10.2_PUBLIC\ghidraRun.bat", start the "IN-VM dbgeng agent" in Targets, and then run "C:\Windows\System32\cmd.exe" from the Launch dialog in Objects, I will get a cmd prompt in "C:\Users\bob".  I realize this may or may not be the affect you want.  Alternatively, you could conveivably start the GADP dbgeng agent by hand (I do not remember the invocation fro this off-hand) out of the directory of interest and use "GADP dbgeng" option specifying the agent's port to connect to it.

In any case, debugger targets should be running from the directory where they were imported from regardless of the launch method, but the "current directory" (in the "cwd" sense) will be where you started Ghidra from.

**Comment by guccigang420** [comment]
@d-millar Pleasant to see these concerns are being addressed. Glad to be of help. Please keep me updated!

**Comment by guccigang420** [comment]
@d-millar Thanks for the reply. Yes, that is indeed slightly better than copy pasting the project. Though, if it is possible, it would be handy if in the future this could be configurable somewhere in the tool. I think for now this issue has been resolved. Good luck on implementing this and the hover over register improvements!

**Comment by anthukne** [comment]
im having the above issue but moving the dll files to the JDK folder hasn't helped.

https://ibb.co/kG45nKy

Any ideas?

Thanks

**Comment by vix597** [comment]
I also moved the DLLs to the JDK folder and get the same error about failing to load the DLL but from the JDK path this time just like @anthukne

**Comment by anthukne** [comment]
> I also moved the DLLs to the JDK folder and get the same error about failing to load the DLL but from the JDK path this time just like @anthukne 

I managed to fix my dll errors. Can't remember how now but I'll take a look. However I still couldn't debug win32 applications. Random issues and no breakpoints working

**Comment by d-millar** [comment]
@vix597 hi and what is your actual error?  having trouble remembering the thread details

**Comment by vix597** [comment]
It's was the "SECURE: unable to load dbghelp" or whatever. It's exactly the error in the screenshot of this issue. One of my coworkers figured it out though. It was a matter of copying the correct dlls to the jdk directory. So the solution here works.
