### ISSUE TITLE
Incumplimiento ISP class UnionBD

### ISSUE THREAD

**Issue by DereckSantander** [NationalSecurityAgency/ghidra#4736]
Hola, me di cuenta que en la clase UnionBD se implementa la interfaz UnionTerminal, la cual hereda métodos que no son utilizados en la clase UnionBD. Esto rompe unos de los principios SOLID, por lo que mi sugerencia es crear una nueva interfaz que tenga los metodos no utilizados. Adjunto un UML y codigo para ilustrar mejor la idea.![ISP 1](https://user-images.githubusercontent.com/107958944/201409017-5a5790fb-5696-401d-9ae3-c864f9feafaf.png)
![image](https://user-images.githubusercontent.com/107958944/201409042-8ac279fb-7f7a-4cd8-813a-c70b6b653c31.png)

**Comment by ryanmkurtz** [comment]
Thank you for the suggestion.  Although we have no plans to modify this code, we will consider this in future refactorings.
