### ISSUE TITLE
Incumplimiento ISP class DataTypeBD

### ISSUE THREAD

**Issue by DereckSantander** [NationalSecurityAgency/ghidra#4737]
Hola, me di cuenta que en la clase DataTypeBD se implementa la interfaz DataType, la cual hereda métodos que no son utilizados en la clase DataTypeBD. Esto rompe unos de los principios SOLID, por lo que mi sugerencia es crear una nueva interfaz que tenga los metodos no utilizados. Adjunto un UML y codigo para ilustrar mejor la idea.
![image](https://user-images.githubusercontent.com/107958944/201409630-8c1c38b0-dc5b-4e48-9585-3edf09686f85.png)
![image](https://user-images.githubusercontent.com/107958944/201409716-51665d67-0a8a-4b9c-b5af-1cbb9a30ed0e.png)

**Comment by ryanmkurtz** [comment]
Thank you for the suggestion.  Although we have no plans to modify this code, we will consider this in future refactorings.
