### ISSUE TITLE
Incumplimiento ISP class ToolButton

### ISSUE THREAD

**Issue by DereckSantander** [NationalSecurityAgency/ghidra#4738]
Hola, me di cuenta que en la clase ToolButton se implementa la interfaz Draggable, la cual tiene métodos que no son utilizados en la clase ToolButton. Esto rompe uno de los principios SOLID, por lo que mi sugerencia es crear una nueva interfaz que tenga los metodos no utilizados. Adjunto un UML y codigo para ilustrar mejor la idea.
![image](https://user-images.githubusercontent.com/107958944/201411566-a5e4d2f6-7c2e-4987-b650-9e1d8e83ff02.png)
![image](https://user-images.githubusercontent.com/107958944/201411591-2ac8c61d-605a-448f-9987-2a208fc5ef1e.png)

**Comment by ryanmkurtz** [comment]
Thank you for the suggestion.  Although we have no plans to modify this code, we will consider this in future refactorings.
