### ISSUE TITLE
Incumplimiento LSP class DebuggerRegionsProvider

### ISSUE THREAD

**Issue by DereckSantander** [NationalSecurityAgency/ghidra#4739]
Saludos, revisando su proyecto me di cuenta que la clase DebuggerRegionsProvider hereda de la clase ComponentProvider. En la clase derivada existen ciertos métodos que no existen en la clase padre, esto rompe con los principios SOLID, por lo que mi sugerencia es implementar esos métodos en la clase padre y de esta manera, cumplir con el principio LSP. Adjunto UML y codigo para ilustrar mejor mi idea.
![image](https://user-images.githubusercontent.com/107958944/201429227-02a64c4b-10be-4c21-b09f-892f9447f2dd.png)
![image](https://user-images.githubusercontent.com/107958944/201429287-c7c4def7-00d1-4fa3-b038-7268f44a4bfd.png)

**Comment by ryanmkurtz** [comment]
Thank you for the suggestion.  Although we have no plans to modify this code, we will consider this in future refactorings.
