### ISSUE TITLE
Incumplimiento OCP clase GlobalSymbolMap

### ISSUE THREAD

**Issue by mbravop** [NationalSecurityAgency/ghidra#4741]
Hola, analizando su proyecto, dentro de la clase mencionada, se incumple el principio Open Closed de SOLID. Ya que realiza verificaciones según el tipo de símbolo. Les adjunto un UML y parte del código como una propuesta a solucionar este inconveniente:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/82302737/201482757-4f353996-39dd-4534-854f-34bf5f6c844c.png">

<img width="394" alt="image" src="https://user-images.githubusercontent.com/82302737/201482781-87ea50b2-b164-4b05-ac21-afd3aada18ae.png">

**Comment by ryanmkurtz** [comment]
Thank you for the suggestion.  Although we have no plans to modify this code, we will consider this in future refactorings.
