### ISSUE TITLE
Incumplimiento DIP en clase TestProgramManager

### ISSUE THREAD

**Issue by K3vR0ld4n** [NationalSecurityAgency/ghidra#4742]
Saludos, revisando su proyecto encontré una violación al SOLID y aunque sean recomendaciones podría ser de ayuda para el futuro mantenimiento del programa. En este caso podemos presenciar que la clase TestEnv depende muy directamente de la clase TestProgramManager, por esta razón le comparto una posible solución para no permitir tanta dependencia a esta clase: 
![image](https://user-images.githubusercontent.com/107887773/201484271-d012691c-8f1b-4f4a-9677-8fe117d4862e.png)
![image](https://user-images.githubusercontent.com/107887773/201484291-40b1bcd6-0142-491c-9828-79376938be15.png)
![image](https://user-images.githubusercontent.com/107887773/201484299-0587beb5-c14f-4a84-b601-60475dac0b46.png)

**Comment by ryanmkurtz** [comment]
Thank you for the suggestion.  Although we have no plans to modify this code, we will consider this in future refactorings.
