### ISSUE TITLE
Build failed due to missing license for lib/protobuf-java-3.21.8.jar on Mac M1

### ISSUE THREAD

**Issue by Durango2013** [NationalSecurityAgency/ghidra#4744]
**Describe the bug**
Tried building Ghidra from source on Mac M1 machine and got the following error:
FAILURE: Build failed with an exception.

* Where:
Script '/usr/local/src/ghidra/gradle/support/ip.gradle' line: 103

* What went wrong:
Execution failed for task ':Debugger-gadp:ip'.
> No License specified for external library: lib/protobuf-java-3.21.8.jar in module /usr/local/src/ghidra/Ghidra/Debug/Debugger-gadp. Expression: map.containsKey(relativePath)

**To Reproduce**
1. Cloned Ghidra to mac M1 machine: gh repo clone NationalSecurityAgency/ghidra
2. Setup Gradle dependencies: gradle -I gradle/support/fetchDependencies.gradle init
3. Build Ghidra: gradle buildGhidra

**Expected behavior**
I expect to have a clean build based on the DevGuide provided in the repo

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: MacOS Monterey version 12.4 aarch64
 - Java Version: OpenJDK Runtime Environment Zulu19.30+11-CA (build 19.0.1+10)
 - Ghidra Version: 10.2.1
 - Ghidra Origin: official GitHub distro
 - Gradle: 7.5.1

**Additional context**
N/A

**Comment by xiaoyinl** [comment]
To work around the error, run `gradle buildGhidra -x ip`
