### ISSUE TITLE
"error: package sun.awt is not visible" occurred during building

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#4754]
**Describe the bug**
There are two errors when building the latest master branch (279b58a6e298070114614d49d1a89fe996998757) The message is: "error: package sun.awt is not visible." The build is still successful though.

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 17.0.3
 - Ghidra Version: 10.3 279b58a6
 - Ghidra Origin: locally built

**Additional context**
```
> Task :FunctionGraph:compileJava
C:\ghidra\Ghidra\Framework\Docking\src\main\java\docking\test\AbstractDockingTest.java:61: error: package sun.awt is not visible
> Task :createJavadocs
import sun.awt.AppContext;
          ^
  (package sun.awt is declared in module java.desktop, which does not export it to the unnamed module)
C:\ghidra\Ghidra\Framework\Generic\src\main\java\generic\test\AbstractGenericTest.java:61: error: package sun.awt is not visible
import sun.awt.AppContext;
          ^
  (package sun.awt is declared in module java.desktop, which does not export it to the unnamed module)
2 errors
```

**Comment by ryanmkurtz** [comment]
Thanks.  I questioned why i didn't need that anymore.  I guess I just missed the error and focused on it succeeding.  I'll put the 1 needed entry back today.
