### ISSUE TITLE
Script Manager Rendering Issue

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4758]
**Describe the bug**
The script manager window does not render correctly

**To Reproduce**
1. Click the "play" icon in the code browser to open the script manager.

**Expected behavior**
Nice and bright and beautifully rendered like it was before.

**Screenshots**
<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/46897303/202576496-3fa80fb0-f731-4900-ae8b-9357c83531a3.png)

Can't leave any metadata in the image if you use a screenshot of the edited screenshot
![522x0](https://user-images.githubusercontent.com/46897303/202576881-e0220bef-76e1-4878-8c42-32968695ec73.png)

</details>

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22621.819]
 - Java Version: 17.0.4
 - Ghidra Version: 10.3_DEV 5b1eb8ef32152627d4d5f39e20cbd23b43e68572

**Additional context**
Parts of the window do render correctly after clicking around trying to highlight things.

**Comment by dev747368** [comment]
should print it out and then take a pic of the page with a potato cell phone.

**Comment by dragonmacher** [comment]
Seems to be working for me.   Any odd stack traces in your log file?

**Comment by astrelsky** [comment]
> should print it out and then take a pic of the page with a potato cell phone.

Next time. Unfortunately it would be in black and white which wouldn't be so great for this particular issue. Am typing this response on my potato cell phone though. 

> Seems to be working for me.   Any odd stack traces in your log file?

I'll have a look tomorrow afternoon. I was using it earlier on a different machine without a problem but I don't remember if I ever opened the script manager. So far this is the only problem I've encountered.

**Comment by astrelsky** [comment]
Nothing in the logs. Going to make a build from a fresh repo to be sure there isn't anything out of date laying around.

**Comment by astrelsky** [comment]
I did manage to get a bunch of errors thrown but foolishly deleted them when deleting `.ghidra\.ghidra_10.3_DEV`. Everything seems to be fine after removing that folder. It was a class cast exception, something about GIcon (popup window was mostly white as well). My best guess is some setting was causing an exception in the swing thread causing rendering to go awry?

**Comment by dragonmacher** [comment]
We emit traces when theme values cannot be found, but those are not real exceptions.   If you are seeing real exceptions, that could explain your issue, if the exception prevented proper initialization.

**Comment by astrelsky** [comment]
> We emit traces when theme values cannot be found, but those are not real exceptions. If you are seeing real exceptions, that could explain your issue, if the exception prevented proper initialization.

I'm not seeing anything anymore. I'm wondering if I had a script that had an icon set that caused it.

**Comment by astrelsky** [comment]
![image](https://user-images.githubusercontent.com/46897303/202822833-16c93d9c-8c46-4b46-9c3b-6c7c5562996c.png)

Note that selecting this menu yields intriguing results.

**Comment by dragonmacher** [comment]
There is quite a bit happening in this screenshot.  The spacing between each option key/value row is unusually large.  Presumably, one of the rows contains a property editor with a large height.

 The missing editor values are troubling as well.     My guess is that our property editors are not being correctly registered for the options.  (This happens in the `EditorInitializer` module initializer.)   

Unfortunately, since I cannot reproduce this, I cannot debug this issue.

**Comment by astrelsky** [comment]
> There is quite a bit happening in this screenshot.  The spacing between each option key/value row is unusually large.  Presumably, one of the rows contains a property editor with a large height.
> 
>  The missing editor values are troubling as well.     My guess is that our property editors are not being correctly registered for the options.  (This happens in the `EditorInitializer` module initializer.)   
> 
> Unfortunately, since I cannot reproduce this, I cannot debug this issue.

If you can't reproduce it then I'm gonna have to record this as entering the menu is hilarious.

**Comment by astrelsky** [comment]
@dragonmacher I have a fix that I'll put in tonight.

**Comment by astrelsky** [comment]
@dragonmacher I found the culprit for the original issue. It appears to be cause by the icon used to unnecessarily complain when two different scripts in two different categories have the same name.

[application.log](https://github.com/NationalSecurityAgency/ghidra/files/10303317/application.log)

**Comment by dragonmacher** [comment]
Coincidentally, I have just fixed this issue in a branch that I am working on.   If you see this again you can work around the issue for now by removing script icons or removing the table column that shows the icons.
