### ISSUE TITLE
FAQ addition suggestion: PowerShell command to update .sla timestamps on Windows

### ISSUE THREAD

**Issue by sylveon** [NationalSecurityAgency/ghidra#477]
```ps1
Get-ChildItem -Recurse -Include *.sla | ForEach-Object { $_.CreationTime = Get-Date; $_.LastWriteTime = Get-Date }
```

Changing only the creation time or changing only the last write time did not seem to work for me, but changing both did.

**Comment by Ionut1994** [comment]
Good afternoon! I would like to solve this issue if nobody else is working on it. Is it ok if I do so?

**Comment by sylveon** [comment]
Feel free, I can't edit the wiki myself.

**Comment by Ionut1994** [comment]
I cloned the wiki repository locally, added the powershell command and then ran "git diff". This is the output:

diff --git a/Frequently-asked-questions.md b/Frequently-asked-questions.md
index feb9ece..11e416c 100644
--- a/Frequently-asked-questions.md
+++ b/Frequently-asked-questions.md
@@ -65,4 +65,11 @@ On Linux, try
 touch `find . -name '*.sla'`
 ```
 
-from the installation directory.
\ No newline at end of file
+from the installation directory.
+On Windows, try
+
+```bash
+Get-ChildItem -Recurse -Include *.sla | ForEach-Object { $_.CreationTime = Get-Date; $_.LastWriteTime = Get-Date }
+```
+
+in the PowerShell console.
\ No newline at end of file

Is it ok?

**Comment by dev747368** [comment]
Wiki updated with @Ionut1994's suggestion.
