### ISSUE TITLE
Unable to delete more than an equate at a time in the equates table view.

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#4771]
**Describe the bug**

The equates table's equate view does not support multiple selection for deletion purposes.

**To Reproduce**

1. Open a file in CodeBrowser
2. Assign a few equates
3. Display the Equates Table
4. Try to select more than one equate

**Expected behavior**

More than one equate can be selected in order to be deleted in one single step.

**Screenshots**

N/A

**Attachments**

N/A

**Environment (please complete the following information):**

 - OS: macOS 13.0.1
 - Java Version: 17.0.5
 - Ghidra Version: git HEAD (8c0f32b24233562fed435c1adc3fbb7de4d3e035)
 - Ghidra Origin: locally built

**Additional context**

I understand that the references list table next to the equates list gets updated to reflect the selection, but would it be possible to enable multiple equate selection and in that case either disable the references table or display a message in there saying something like "More than one equate selected"?  In my case I had more than 100 equates to delete and I ended up having to script that; the alternative would have been to select and delete a single equate 100+ times.

**Comment by dragonmacher** [comment]
This should be easy to fix.
