### ISSUE TITLE
OMF loader reads wrong data from file.

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#4777]
**Describe the bug**
The OMF importer imports the wrong data from 8086+8087 real mode object files.

**To Reproduce**
1. Import the attached bcd.obj file as an OMF record file, using "x86:LE:16:Real Mode" as language
2. Do not perform automatic analysis and open the file
3. Jump to 0000:2037
4. The byte sequence starting at that address should be 0x9B 0xD9 0xC1, instead it is 0xAB 0x09 0xC1.

**Expected behavior**
The correct data should be read.

**Screenshots**
Ghidra and IDA Free 5.0 side by side (I've highlighted the bytes that are read incorrectly):

![SCR-20221127-np9-2](https://user-images.githubusercontent.com/235740/204145320-4e3225f1-5a81-4dcd-bb32-158d95c1f221.jpg)

The data block in question starts at offset 0x256 in the attached file.

**Attachments**

[bcd.obj.zip](https://github.com/NationalSecurityAgency/ghidra/files/10098683/bcd.obj.zip)

**Environment (please complete the following information):**
 - OS: macOS 13.0.1
 - Java Version: 17.0.5
 - Ghidra Version: git HEAD (522bda39e8fd14456d0e65662ce74fefb3049819)
 - Ghidra Origin: locally built

**Additional context**

Just to be sure, the error here is not about disassembled instructions, but in the bytes being put in the text segment to be disassembled.  I'll keep looking if I can find more examples in smaller files to reproduce the issue with less clutter in the file.

**Comment by dev747368** [comment]
@agatti, could you look at your other tools and check if they show a relocation at that address?  (and any meta data about that relocation)

And conversely, you can open Ghidra's relocation table and see that we've got a relocation there, and the original bytes before we changed them.

I've been going through the OMF spec and how it handles relocations and I'm not seeing much on our end that varies from the spec as defined.

**Comment by agatti** [comment]
@dev747368 regarding the relocation table you're absolutely right, it indeed shows the bytes being patched.

I've tried other tools (cutter, radare2, etc.) but unfortunately they just ignore relocation entries, so I cannot give more pointers on this.  The freeware version of IDA I'm using doesn't have an obvious way to show relocation entries, and doesn't expose that information to its scripting engine, as far as I can tell.  I've had a quick go at checking the library file the object was found in, but I couldn't find any special metadata that tells the linker to interpret those entries in a different way. 

Now, this object file was built using a now obsolete DOS-era C/C++ compiler, TopSpeed C.  Other object files built with that compiler don't seem to have problematic FIXUPP records - as in, the relocation entries make sense and are applied correctly.  However, since these relocations deal with FPU opcodes, I suspect they could have been FPU emulation traps, but the fact that they used valid opcodes to patch things with does not make much sense.

Considering that IDA handles those files just fine I believe it may mean one of these two things: either the relocations in that particular section are incorrect to begin with and IDA discards them, or Ghidra doesn't interpret those entries correctly.  The first case could be worked around with a way to ignore relocation entries when loading the file (say, a loader option flag) or shipping a Ghidra script to un-do the fixup operation.

Given all of this, I'll try to find the time to write a quick and dirty OMF parser to experiment with relocation parsing and see where this leads me.

**Comment by agatti** [comment]
The plot thickens.  So, I found a version of TopSpeed C to play with, and it comes with a tool to disassemble .OBJ files.  Now, what I got with that very file is as follows:

```
segment _TEXT(CODE,00028H) (*segment length = 00115H*)
                            public _3bcd__real_to_dec@Fri:
(*0000 55*)                   push  bp
(*0001 8B EC*)                mov   bp,sp
(*0003 83 EC 22*)             sub   sp,22H
(*0006 57*)                   push  di
(*0007 56*)                   push  si
(*0008 51*)                   push  cx
(*0009 9B*)                   (*fwait *)
(*000A D9 C1*)                fld     st(0),st(1)
(*000C 9B*)                   (*fwait *)
(*000D DB 7E DE*)             fstp    tbyte [bp][-22H],st(0)
(*0010 9B*)                   (*fwait *)
(*0011 D9 C2*)                fld     st(0),st(2)
(*0013 9B*)                   (*fwait *)
(*0014 DB 7E E8*)             fstp    tbyte [bp][-18H],st(0)
(*0017 9B*)                   (*fwait *)
(*0018 D9 C0*)                fld     st(0),st(0)
(*001A 9B*)                   (*fwait *)
(*001B DD DA*)                fstp    st(2),st(0)
(*001D 8B F0*)                mov   si,ax
(*001F 9B*)                   (*fwait *)
(*0020 DB 2E 00 00*)          fld     tbyte st(0),[$0]
(*0024 9B*)                   (*fwait *)
(*0025 DD D9*)                fstp    st(1),st(0)
(*0027 9B*)                   (*fwait *)
(*0028 D9 C0*)                fld     st(0),st(0)
(*002A 9B*)                   (*fwait *)
(*002B D8 DA*)                fcomp   st(0),st(2)
(*002D 9B*)                   (*fwait *)
(*002E DD 7E FE*)             fstsw   [bp][-2]
(*0031 90*)                   (*nop   *)
(*0032 9B*)                   fwait 
(*0033 F6 46 FF 41*)          test  byte [bp][-1],41H
(*0037 74 04*)                je    $4
(*0039 32 C0*)                xor   al,al
(*003B EB 0B*)                jmp   $5

[...]
```

Now, output of this tool is meant to be able to be reassembled straight away with its own assembler, and it uses Pascal-style comment markers.  From what it spits out, it looks like that the relocations are meant to patch out FPU synchronisation opcodes, which are optional on 80286+80287 and later but are required on 8086+8087.

This answers why the relocations are there but not why IDA ignores them...

**Comment by agatti** [comment]
@dev747368 if I read the specs correctly, Ghidra is indeed interpreting the relocations incorrectly.

Let's take the first one: 0xC4 0x09 0x56 0x02.  0xC409 is a 16 bits segment-relative FIXUP subrecord, at offset 9, where the first `FWAIT` instruction is located.  The second byte, 0x56 indicates frame method 5 and target method 6 (frame method encoded in the frame field, target explictly specified in the subrecord, using the last three bits as the target method index).  The specification mentions for target type 6 and frame method 5 (emphasis mine):

[...]
T6 Specified by a EXTDEF index only; **the displacement in the FIXUP subrecord is assumed to be 0**.

[...]
F5 The FRAME is determined by the TARGET's segment, group, or external index.

Which means no FRAME datum follows the frame/target specification but a TARGET datum does, which in this case is 0x02.  No more data should be read, and the displacement to apply to the target is 0.

This means the relocations in question, if I understood things correctly, should be simply ignored.

**Comment by agatti** [comment]
The relocation at 0000:204E is left alone and still points to 0000:2000.  The patch fixed the FWAIT relocations but unfortunately causes a regression...

Before the patch:

```
                             //
                             // _TEXT 
                             // Address:0x2022 Size:0xc
                             // ram:0000:2022-ram:0000:202d
                             //
       0000:2022 52              PUSH       DX
       0000:2023 51              PUSH       CX
       0000:2024 53              PUSH       BX
       0000:2025 50              PUSH       AX
       0000:2026 e8 d7 0f        CALL       __InitLoop               undefined __InitLoop()
       0000:2029 58              POP        AX
       0000:202a 5b              POP        BX
       0000:202b 59              POP        CX
       0000:202c 5a              POP        DX
       0000:202d c3              RET
```

After the patch:

```
                             //
                             // _TEXT 
                             // Address:0x2022 Size:0xc
                             // ram:0000:2022-ram:0000:202d
                             //
       0000:2022 52              PUSH       DX
       0000:2023 51              PUSH       CX
       0000:2024 53              PUSH       BX
       0000:2025 50              PUSH       AX
       0000:2026 e8 00 00        CALL       LAB_0000_2029
                             LAB_0000_2029                           XREF[1]:     0000:2026(*)  
       0000:2029 58              POP        AX
       0000:202a 5b              POP        BX
       0000:202b 59              POP        CX
       0000:202c 5a              POP        DX
       0000:202d c3              RET
```

Same thing for the CALLs at 0000:2069 (IDA turns that into `CALL __pow_int`), 0000:20A7, 0000:20B6 etc.  I'll take a closer look later today using my dumper to see what's going on.

**Comment by Gravelbones** [comment]
It seems the FID names have special meaning for the linker.
[OpenWatcom fppatche.h](https://github.com/open-watcom/open-watcom-v2/blob/master/bld/watcom/h/fppatche.h)
So the relocation routine should test for those and do the same special (linking) handling.
Ignore would be a safe start.
Working on a relocation patch anyway, so will look into this too.
