### ISSUE TITLE
Typo in "Save Theme Changes" Popup

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4779]
![image](https://user-images.githubusercontent.com/55233728/204226035-e64f7391-ec8c-4e1a-aeac-33f8798de48d.png)

"Do you want **to** save your changes"

**Comment by sad-dev** [comment]
Two instances of the typo:
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/Docking/src/main/java/docking/theme/gui/ThemeUtils.java#L50
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/Docking/src/main/java/docking/theme/gui/ThemeDialog.java#L101

**Comment by dragonmacher** [comment]
Thanks.  I'll fix this.
