### ISSUE TITLE
How to import third-party .jar files used by my script

### ISSUE THREAD

**Issue by wanchouchou** [NationalSecurityAgency/ghidra#479]
Hi, I write a script, in scripts manager, for doing some de-obfuscation operations. This script needs some external utility classes defined in a third-party .jar file, but I don't know how to import these third-party .jar files used by my script. Does GHIDRA support it? If it is, please tell me how to do it, thanks.

**Comment by ryanmkurtz** [comment]
If you are writing and sharing a script that requires a 3rd party jar, the supported way to do this is to create a Ghidra module with your script in the module's `ghidra_scripts` directory and your jar in the module's `lib` diretory.  You can then export your Ghidra module as a Ghidra extension (zip file) and deliver it that way.  Just be mindful of the licensing of your jar file to make sure it's compatible.

**Comment by kiritowch** [comment]
> If you are writing and sharing a script that requires a 3rd party jar, the supported way to do this is to create a Ghidra module with your script in the module's `ghidra_scripts` directory and your jar in the module's `lib` diretory. You can then export your Ghidra module as a Ghidra extension (zip file) and deliver it that way. Just be mindful of the licensing of your jar file to make sure it's compatible.

I also met the same problem, sorry I didn't understand your approach.
I loaded the third-party library through eclipse, and then it can be used normally, but it must be started from eclipse every time.
It seems that your method is better, I want to ask if there are any steps.....

**Comment by ryanmkurtz** [comment]
The approach I described assumed you are using our GhidraDev Eclipse plugin to create the Ghidra Module project, and the GhidraDev plugin to export that project as an extension.

**Comment by dlmgary** [comment]
This is an old thread but hopefully you find this info useful. 

I found that Ghidra checks adds the `--classpath` here https://github.com/NationalSecurityAgency/ghidra/blob/7b76afee937f2309ac1f4ebf17ab91980a6d6874/Ghidra/Features/Base/src/main/java/ghidra/app/script/JavaScriptProvider.java#L230-L231


If you trace that a bit, you'll see that `getClassPath()` adds everything in `System.getProperty("java.class.path")` . If you check that, you'll find that Ghidra adds all the `.jar`s in the `~/Ghidra/*` folder, but it also adds things from `~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins`.

### Solution

My fix was to add all my `.jar`s in  `~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins/`. If you do that all your scripts will have access to your extra dependencies. In my case, I had to create that folder because it wasn't already there.

### Example
``` bash
$ cd ghidra_9.X.X_PUBLIC

# You might or might not need to create this folder
$ mkdir -p ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins

$ ls ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins
(empty)

# Fails because it cannot find external library
$ ./support/analyzeHeadless ghidra://sample.ghidra.server.com:/PATH -postScript SCRIPT.java -process FILE.exe -connect USER -p 
...
SCRIPT.java:1: error: package javax.json does not exist
import javax.json.*;
^
...

# Copy your external libraries to be in Ghidra's classpath
$ mv ~/javax.json.jar ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins
$ ls ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins
javax.json.jar

# This time it success
$ ./support/analyzeHeadless ghidra://sample.ghidra.server.com:/PATH -postScript SCRIPT.java -process FILE.exe -connect USER -p 
```

**Comment by wanchouchou** [comment]
> This is an old thread but hopefully you find this info useful.
> 
> I found that Ghidra checks adds the `--classpath` here
> 
> https://github.com/NationalSecurityAgency/ghidra/blob/7b76afee937f2309ac1f4ebf17ab91980a6d6874/Ghidra/Features/Base/src/main/java/ghidra/app/script/JavaScriptProvider.java#L230-L231
> 
> If you trace that a bit, you'll see that `getClassPath()` adds everything in `System.getProperty("java.class.path")` . If you check that, you'll find that Ghidra adds all the `.jar`s in the `~/Ghidra/*` folder, but it also adds things from `~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins`.
> 
> ### Solution
> My fix was to add all the external dependencies to `~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins/`. If you do that, all your scripts will have access to them.
> 
> ### Example
> ```shell
> $ cd ghidra_9.X.X_PUBLIC
> 
> # You might or might not need to create this folder
> $ mkdir -p ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins
> 
> $ ls ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins
> (empty)
> 
> # Fails because it cannot find external library
> $ ./support/analyzeHeadless ghidra://sample.ghidra.server.com:/PATH -postScript SCRIPT.java -process FILE -connect USER -p 
> ...
> SCRIPT.java:1: error: package javax.json does not exist
> import javax.json.*;
> ^
> ...
> 
> # Copy your external libraries to be in Ghidra's classpath
> $ mv ~/javax.json.jar ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins
> $ ls ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins
> javax.json.jar
> 
> # This time it success
> $ ./support/analyzeHeadless ghidra://sample.ghidra.server.com:/PATH -postScript SCRIPT.java -process FILE -connect USER -p 
> ```

Thanks. This is real a useful approach, if some one did not want to create a Ghidra Module project.

**Comment by pabx06** [comment]
@dlmgary  
thanks for the ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins TIPS saved me time digging into lunch script logic .

May  i complement the first question ? 
now that **java.class.path**  is problems is solved 

is there a similar folder path for **java.library.path** ?

printing on the console gives me those value java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

i kinda looking for a portable user based solution since i think java >8 kinda don't like lib being added to jdk's lib cant remeber well... what was the story 

and modding the lunch script would lead me to forget what i did on the next install and rerun of my script ... since JNI ERROS  are not verbose => a pain to trouble shoots

**Comment by pabx06** [comment]
> @dlmgary
> thanks for the ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins TIPS saved me time digging into lunch script logic .
> 
> May i complement the first question ?
> now that **java.class.path** is problems is solved
> 
> is there a similar folder path for **java.library.path** ?
> 
> printing on the console gives me those value java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
> 
> i kinda looking for a portable user based solution since i think java >8 kinda don't like lib being added to jdk's lib cant remeber well... what was the story
> 
> and modding the lunch script would lead me to forget what i did on the next install and rerun of my script ... since JNI ERROS are not verbose => a pain to trouble shoots

that was a silly question my JNI libs are already in /usr/lib . so no setup required ... ghidra lunch script relay good.
thanks NSA

**Comment by jgru** [comment]
> ### Solution
> Add all the external dependencies to ~/.ghidra/.ghidra_9.1.2_PUBLIC/plugins/. If you do that, all your scripts will have access to > them.

I tried this approach of @dlmgary with Ghidra 10.0.1 and the directory `.ghidra/.ghidra_10.0.1_PUBLIC/plugins`, but had no success. 
Can somebody confirm, that this still works with 10.0.1? What might have been gone wrong?

Thanks already in advance!

**Comment by ryanmkurtz** [comment]
Support for the `plugins` directory may have been lost along the way.  You have a couple of other options though:

* Add jar to `<ghidra install dir>/Ghidra/patch/`
* Add jar to any `lib/` subdirectory in Ghidra
* Add the jar through the the front-end GUI:  `Edit -> Plugin Path`.

**Comment by ryanmkurtz** [comment]
It seems now the proper way to do this is to go into the Script Manager, click "Manage Script Directories", and add your jar there.

**Comment by jgru** [comment]
Thank you very much for getting back to me, @ryanmkurtz!

I tested all of those four options using Ghidra 10.0.1  on a Ubuntu 20.04 system with OpenJDK 11 installed. The following options work:
> Add jar to <ghidra install dir>/Ghidra/patch/
> Add jar to any lib/ subdirectory in Ghidra
> Add the jar through the the front-end GUI: Edit -> Plugin Path. 

However, the "preferred way" of using "Manage Script Directories" to add the jar, somehow does not work for me. I just want to let you know that. 

Thanks again for your help.

**Comment by ryanmkurtz** [comment]
Thanks for letting me know...I'll have to investigate what that feature is doing.  It is somewhat new and I'm not too familiar with it yet.

**Comment by aldelaro5** [comment]
> Thanks for letting me know...I'll have to investigate what that feature is doing. It is somewhat new and I'm not too familiar with it yet.

Hi, I happened to run into that same issue and I was wondering if you ended up verifying.

Having this option can make my particular script install instructions easier so it would be nice to know if it works this way. For now, the plugin path is suitable, but just verifying.

**Comment by ryanmkurtz** [comment]
Sorry I haven't looked into it yet.  I'll reopen this ticket so it doesn't get lost again.

**Comment by jpleasu** [comment]
Sorry I didn't see this earlier.  Using "Manage script directories" will require that the jar be an OSGI bundle and the dependency will need to be declared in the script using `// @import_package`.   It is documented in Ghidra Help.

Many jars are already packaged as OSGI bundles, and it's not hard (but can be tedious) to create a bundle from a jar.
