### ISSUE TITLE
Memory Map Includes "tdb" memory block with negative/invalid address post analysis

### ISSUE THREAD

**Issue by clearbluejar** [NationalSecurityAgency/ghidra#4790]
**Describe the bug**
The Memory Map after analysis of Windows binaries (perhaps others?), contains a memory block for 'tbd' with a seemingly negative or invalid address. 

**To Reproduce**
1. Import a windows binary. 
2. Review program metadata before 
![before_keymgr](https://user-images.githubusercontent.com/3752074/205111316-3679fb79-ef6c-4617-9736-4d84972d3396.png)
3. Open is codebroswer. Review Memory Map before analysis
![keymgr_memmap_before](https://user-images.githubusercontent.com/3752074/205111767-fef02bc4-dc66-42d4-bac7-a0eb63ff43de.png)

4. Review Memory Map after analysis
![keymgr_memmap](https://user-images.githubusercontent.com/3752074/205111904-48e6c1b0-1511-49e4-b034-a58b2d42a53b.png)

5. Review Program Metadata after analysis
![after_keymgr](https://user-images.githubusercontent.com/3752074/205112131-c11685a9-caa9-4402-b1c9-6989404efc1b.png)

This same invalid tdb code block appears in other binaries as well:
![ntoskrnl_memmap](https://user-images.githubusercontent.com/3752074/205112813-8e13663c-d853-4e87-a7b4-1bdeafac4a44.png)

**Expected behavior**
TDB, whatever that is, should be a reasonable address. 

**Impact**

By modifying the maximum address for the program, several analytics are made inefficient or inaccurate as the valid program address range becomes massive. 

**Environment (please complete the following information):**
 - OS: windows 11
 - Java Version: jdk 17
 - Ghidra Version: 10.2.2 (this does not occure in 10.1.5)
 - Ghidra Origin: official GitHub distro release

**Additional context**

The only code I saw that mentions tdb is this section, I just couldn't see where it updated the memory map. 

https://github.com/NationalSecurityAgency/ghidra/blob/a4111b159256a3bd19e636508268063253c40ba0/Ghidra/Features/Base/src/main/java/ghidra/app/util/datatype/microsoft/ThreadEnvironmentBlock.java#L75

https://github.com/NationalSecurityAgency/ghidra/blob/975db1919c9e13aeb794883f4e93603fc6c0ea7e/Ghidra/Features/FileFormats/src/main/java/ghidra/file/formats/dump/pagedump/Pagedump.java#L350-L354

**Comment by clearbluejar** [comment]
might be related to https://github.com/NationalSecurityAgency/ghidra/issues/4710 ?

**Comment by clearbluejar** [comment]
I retract my impact statement. I thought the address was causing inefficiencies in my program comparison script, turns out that Ghidra 10.2.2 identifies several more functions than 10.1.x.  Still interested to know if the memory block should exist in the memory map and how that affects the program max address.

**Comment by ryanmkurtz** [comment]
Yes, it looks related.  What version of Windows did you get your binary from?

**Comment by clearbluejar** [comment]
windows 11 -  10.0.22621.819.  I assume this would would apply though to any version. 

https://winbindex.m417z.com/?file=keymgr.dll

**Comment by ryanmkurtz** [comment]
My version of that file didn't have it. I'll check my copy of Win11.

**Comment by clearbluejar** [comment]
Try this file: https://msdl.microsoft.com/download/symbols/keymgr.dll/3F3941BD16000/keymgr.dll 

I have verified that the memory block only shows up when Thread Environment Block is checked (which looks to be default in 10.2) and that analyzer doesn't exist in 10.1.5. 

![thread-env-block](https://user-images.githubusercontent.com/3752074/205154642-a97ccac6-f787-44ae-8848-d76c81ae8219.png)

**Comment by clearbluejar** [comment]
Perhaps this? https://github.com/NationalSecurityAgency/ghidra/blob/a4111b159256a3bd19e636508268063253c40ba0/Ghidra/Features/Base/src/main/java/ghidra/app/util/datatype/microsoft/ThreadEnvironmentBlock.java#L792-L813

**Comment by ryanmkurtz** [comment]
Thanks, I didn't know about this analyzer.  I am going to ask @caheckman to weigh in since he is the author.

**Comment by ryanmkurtz** [comment]
The choice of default memory block addresses are intentional.

https://github.com/NationalSecurityAgency/ghidra/blob/d182ba8edb78122afe4be4965417e6d0256df3f1/Ghidra/Features/MicrosoftCodeAnalyzer/src/main/java/ghidra/app/plugin/prototype/MicrosoftCodeAnalyzerPlugin/TEBAnalyzer.java#L63-L84

There is an analyer option that allows you to change the block address.  I am not seeing any bugs here.

**Comment by clearbluejar** [comment]
Thank you for looking into this and helping me understand its origin. This analyzer was added by default in 10.2, and I was  thrown off by the extra memory block and max address change as you see above. I previously retracted my impact statement above and agree it isn't a bug.

**Comment by ryanmkurtz** [comment]
>  I was thrown off by the extra memory block and max address change

Me too!
