### ISSUE TITLE
NPE GadpValueUtils.java:605

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4791]
**Describe the bug**
Cannot invoke "Object.getClass()" because "value" is null.

Unfortunately it's not possible to provide the log file. It looks like desc.defaultValue is null in makeParameter

Ghidra version: 10.3_DEV

**Comment by astrelsky** [comment]
Seems to work fine with the 10.2.1 from github.

**Comment by nsadeveloper789** [comment]
Ah. Looks like this is fallout from #4732. We must not have tested with GADP....

**Comment by nsadeveloper789** [comment]
I was able to sort the NPE out, and we'll soon close this ticket, ... but it seems there are still issues with our Windows debug connectors, which I assume are what you were trying to use. We've filed an internal ticket to sort those out the rest of the way.
