### ISSUE TITLE
OMF loader reports unsupported relocation types

### ISSUE THREAD

**Issue by jibaer-izw** [NationalSecurityAgency/ghidra#4793]
On importing a x86-realmode obj file i get the following messages:

> Unsupported relocation type 2 at 0x2000
> Unsupported relocation type 3 at 0x49ff
> ...

**To Reproduce**
Import attached obj-file LD-NET.OBJ

**Screenshots**
![Ghidra - unsupported relocation](https://user-images.githubusercontent.com/56642420/205436756-809b0e6f-efba-463b-a75d-f6e55a51293e.PNG)

**Attachments**
[LD_NET.zip](https://github.com/NationalSecurityAgency/ghidra/files/10146183/LD_NET.zip)

**Environment (please complete the following information):**
 - OS: Win10
 - Java Version: 17
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub distro

**Comment by Gravelbones** [comment]
Seeing type 3 too, which is far relocations, instead of near relocations.
Any library with large/huge memory model should have plenty of these.
Willing to help with fixing/testing this.
