### ISSUE TITLE
Right click does not work in latest Ghidra (Apple silicon related?)

### ISSUE THREAD

**Issue by serhack** [NationalSecurityAgency/ghidra#4794]
Right click seems not to work with latest Ghidra version. Since I never saw this problem, I wanted to open this issue. I think it is kind of weird behavior by Ghidra because I did not have any problems with older versions. 

To reproduce it: open Ghidra, and try to right click. No context menu is shown by Ghidra.

The environment is characterized by the presence of Apple Silicon architecture, chip M1 Ultra. 

**Environment:**
 - OS: macOS 13.0.1
 - Java Version: 19.0.1
 - Ghidra Version: 10.2-10.2.2
 - Ghidra Origin: official Github distro 

Any idea to investigate more about this behavior? Thanks in advance.

**Comment by agatti** [comment]
@serhack if there's no active project, right clicking in the file tree pane doesn't do anything.

Does it happen after a project has been created or loaded?

**Comment by serhack** [comment]
It happens when a project has been created or loaded. It happens on Project overview windows and on CodeBrowser.

**Comment by agatti** [comment]
I'm usually on JDK17 but I've tried with JDK19 and right-clicking works just fine here.  The only apparent difference from your setup is the CPU, which is an M1 Max rather than an M1 Ultra.

Does your JDK/JRE come from Homebrew by any chance?

**Comment by serhack** [comment]
> Does your JDK/JRE come from Homebrew by any chance?
No, came from Oracle. Really weird issue.

**Comment by agatti** [comment]
Try with Homebrew's, then - that's what I'm using and it works here :)

**Comment by ryanmkurtz** [comment]
Cannot reproduce on macOS 13.0 using [Temurin JDK 17](https://adoptium.net) for aarch64.

Do you have any stack traces in your log?

**Comment by serhack** [comment]
Logs do not show anything relevant, there's no stack trace in my logs. Is there anything I can do to look for more detailed logs?

**Comment by serhack** [comment]
Sorry for the waiting. Downgraded to the LTS version suggested by @ryanmkurtz and it's always the same issue.

**Comment by serhack** [comment]
Yes, I can confirm.

**Comment by ryanmkurtz** [comment]
Unfortunately since I and others cannot reproduce this, there's not anything else I can think to do.  For this reason, I am going to go ahead and close the ticket to indicate there is no action for the Ghidra team to currently take.  Feel free to use this issue to continue the conversation though if you have any new findings.

**Comment by serhack** [comment]
At least is there any button or something that can show me the context menu in the next releases? :( I'm driving crazy to understand what the issue could be. No events are shown in debug log, and I do not know how to further debug Ghidra.

**Comment by serhack** [comment]
Okay, found the issue: [Two fingers tap generates wrong mouse modifiers on M2 MacBooks](https://bugs.openjdk.org/browse/JDK-8294426) and [PR](https://github.com/openjdk/jdk/pull/10429). Probably requires Apple investigation.

**Comment by ryanmkurtz** [comment]
Very weird that the behavior of M1 is different than M2 with regard to this.  Nice work tracking it down!
