### ISSUE TITLE
Cleared selected text loses ability to do kb shortcut actions

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4797]
**Describe the bug**
Once a section has been cleared, it loses the ability to have operations done on it until selected again. 

I select a section and press shortcuts `p` or `bbb` or `t` to enter a type, works fine.
I select a section, right click and clear with options, and try to do anything it does not work

**To Reproduce**
1. select memory
2. clear with options, default
3. attempt to type the memory with kb shortcuts
4. nothing happens
5. clear selection, re-select
6. attempt to type memory
7. works

**Expected behavior**
should be able to change datatype with kb shortcuts after clearing

**Environment (please complete the following information):**
 - OS: 20.04
 - Java Version: 17.0.5
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official

**Additional context**
right clicking data and using data menu still works

**Comment by ghidragon** [comment]
I'm unable to reproduce your issue. I have tried it in both master and the 10.2.2 release. Are you seeing it on a consistent basis? Does it happen on a fresh launch of ghidra or perhaps after doing something else?

**Comment by mumbel** [comment]
I will try again with another image and I'll do a master build as well.  I wasn't too descriptive the ways to clear, this does not happen with just a regular clear, only with the "clear with options", hopefully that stuck out in the repro steps.


My use case was an image didn't discover the inline switch table offsets, and I selected a large portion of .text and disassembled.  Resulting in alot of errors in those tables.  So I selected all of those offset bytes, cleared with options to remove the errors (may be that's trick, I'll double check non error regions) and then tried to b,b,b to make 4 byte offsets

**Comment by ghidragon** [comment]
I did exactly as you specified and it worked for me. Seems like it must be a focus issue or some other window/feature is interfering. Couple things to try. When you are in the state where it is not working, press cntrl-shift-alt F2, this will print some focus debug stuff to the console. For me, it looks like: 
INFO  ====================================   (ShowFocusInfoAction.java:64) 
INFO  Active Docking Window Manager: CodeBrowser: Foo:/empty_bytes.bin: 183016183   (ShowFocusInfoAction.java:65) 
INFO  Focused Docking Window: Listing:  empty_bytes.bin: 75065304   (ShowFocusInfoAction.java:68) 
INFO     (ShowFocusInfoAction.java:75) 
INFO  Active Java Window: Window (CodeBrowser: Foo:/empty_bytes.bin): 183016183   (ShowFocusInfoAction.java:78) 
INFO  Focused Java Window: Window (CodeBrowser: Foo:/empty_bytes.bin): 183016183   (ShowFocusInfoAction.java:79) 
INFO  Focused Java Component: docking.widgets.fieldpanel.FieldPanel: 1363310165   (ShowFocusInfoAction.java:80) 
INFO  Mouse-over Object: docking.widgets.fieldpanel.FieldPanel: 1363310165   (ShowFocusInfoAction.java:84) 
INFO  Focusable?: true   (ShowFocusInfoAction.java:85) 
INFO     (ShowFocusInfoAction.java:87) 

One more thing to try: start with a brand new codebrowser tool by going to the project window and invoke Tools->Import Default Tools... and then pick the CodeBrowser tool. Then try your scenario with that tool. That is the tool that I used, so then I now our tool configurations are identical.

**Comment by ryanmkurtz** [comment]
I just tried on Windows and it worked for me too in master.

**Comment by ryanmkurtz** [comment]
@mumbel, has this continued to be an issue for you?  Did you have a chance to try any of @ghidragon's debugging suggestions?

**Comment by mumbel** [comment]
I cant get that shortcut to do anything, but did try a fresh code browser.  Cannot repro on master any longer, but 10.2.2 is still showing

**Comment by mumbel** [comment]
How are you supposed to use this ctrl+shift+alt+f2?

That key combo does nothing.  I tried in master from eclipse (run/debug) and tried ghidraRun and ghidraDebug from 10.2.2 from command line.  It never produced any output

**Comment by dragonmacher** [comment]
> How are you supposed to use this ctrl+shift+alt+f2?
> 
> That key combo does nothing. I tried in master from eclipse (run/debug) and tried ghidraRun and ghidraDebug from 10.2.2 from command line. It never produced any output

This does not work a build.   This is working for me now in 'full dev mode'.   I'm not sure if it works in the 'mixed dev mode' using Eclipse and a build together.     If it works, there will be a message printed to the Eclipse console.  The message has Java focus information in it so that you can see what Java thinks the focus owner is.

**Comment by mumbel** [comment]
Wonder if it's some conflict with Ubuntu 20.04.  I was trying it the same way you described (both with a fan lock and with fn key added into combo)

**Comment by ryanmkurtz** [comment]
I just tried from an Ubuntu 22.10 VirtualBox VM with a different big mac keyboard, and `ctrl+shift+alt/option+fn+f2` worked.  Note the output appears in the Eclipse console.

**Comment by ryanmkurtz** [comment]
But this wouldn't work in your 10.2.2 release where you can reproduce it anyway.
