### ISSUE TITLE
Missing logo in readme

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4800]
Where did the beautiful Ghidra logo in the README go? For reference the file path was Ghidra/Features/Base/src/main/resources/images/GHIDRA_3.png

Should I get some crayons, draw a replacement logo and send it in the mail?

**Comment by dev747368** [comment]
looks like https://github.com/NationalSecurityAgency/ghidra/commit/f091a084c2775fc2aa66095123fef7c418372e0a is the commit that nuked that file.

Now our github main page looks very sad.

**Comment by ryanmkurtz** [comment]
This makes me sad

**Comment by ryanmkurtz** [comment]
We are back in business 1e9a7245750af2f6bc36051bb50b867d54d6ba69

**Comment by astrelsky** [comment]
> We are back in business 1e9a7245750af2f6bc36051bb50b867d54d6ba69

No hand drawn art then?

**Comment by ryanmkurtz** [comment]
No.  I ended up redrawing it in MS Paint from memory.
