### ISSUE TITLE
Failure for Analyzing and Decompiling SPARC JMPL Function Pointers (Indirect Jump) Instruction

### ISSUE THREAD

**Issue by cztian** [NationalSecurityAgency/ghidra#4805]
Current behavior: Ghidra mistake the address of `JMPL` instruction itself (`0024b008 9f c3 e0 00  jmpl   [o7],o7`) for the function pointer to be called. `(*(code *)0x24b008)(param_1);`
![image](https://user-images.githubusercontent.com/14105716/206658370-932e642f-e783-492a-97aa-6920f0c97683.png)
Expected behavior: `(*(code *)PTR_FUN_00575910)(param_1);`
Ghidra version: last commit nightly build.
Compiler: Sun Workshop SPARCompilers, for Solaris 2.5+.

**Comment by ghidracadabra** [comment]
Thank you for reporting this.  Should be an easy fix.
