### ISSUE TITLE
Ability to use an enum as an array index and definition

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4806]
**Is your feature request related to a problem? Please describe.**
Having array indices using numeric values doesn't help convey meaning.

**Describe the solution you'd like**
The ability to declare arrays using an `enum` type and those values appear as indices when decompiled.  Eg, instead of:
```
int[43] aVals;
aVals[0] = ...;
aVals[1] = ...;
aVals[2] = ...;
....
aVals[42] = ...;
````
you'd get
```
int[enumType] aVals;
aVals[line_level] = ...;
aVals[min_clip] = ...;
aVals[base_hithr] = ...;
...
aVals[do10ms] = ...;
```
where the `enumType` has names representing values 0..42 (it may be helpful if during the calculation to determine the number  of elements, this formula `max - min + 1` were used allowing for non-zero based arrays).

**Describe alternatives you've considered**
Using individual data assignments, however when an array regime is used to assign values (as in a `setter` of the form `int set(enumType nIdx, void* pvNewValue)`) an array is needed!

**Comment by sir-maniac** [comment]
This is related to #3186

**Comment by ryanmkurtz** [comment]
Duplicate of #3186
