### ISSUE TITLE
decompliation of passed function pointer

### ISSUE THREAD

**Issue by robinsch** [NationalSecurityAgency/ghidra#4813]
IDA PRO results in the correct decompliation:
```
void __usercall StaticDBLoadAll(void (__thiscall *fn)(WowClientDB *, char *, int)@<esi>)
```
StaticDBLoadAll gets function pointer passed in ESI when being called, this is the disassembly of it:
![](https://i.gyazo.com/a70c34756b4eb848b6ff7e5c22f9b7d9.png])

when I try to convert this in ghidra these are my steps:

1) Edit function StaticDBLoadAll to "Use Custom Storage" and assign ESI register to it:

![](https://i.imgur.com/Kxkqo6P.png])

2) Create new function definition in Data Type Manager
![](https://i.imgur.com/iUv2Zcq.png)

3) Use my new function as datatype for passed function pointer
4) decompilation looks like this:
![](https://i.imgur.com/c53FNDD.png)

Am I doing something wrong?

**Comment by Fips-e** [comment]
You have a typo in your signature. 
Check this for the syntax: [https://spinsel.dev/assets/2020-06-17-ghidra-brainfuck-processor-1/ghidra_docs/language_spec/html/pcodedescription.html#cpui_int_add](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
