### ISSUE TITLE
Labels for global variables are in the wrong place

### ISSUE THREAD

**Issue by pasccom** [NationalSecurityAgency/ghidra#4815]
**Describe the bug**
When analyzing a PE file with a partly-initialized section (i.e. a section for which `SizeOfRawData < VirtualSize`), the labels for global variables obtained using debugging information are misplaced. The offset corresponds to the size of initialized data (`SizeOfRawData`).

**To Reproduce**
1. Import a PE file with a partly-initialized section (i.e. a section for which `SizeOfRawData < VirtualSize`) with embedded debug information (sorry I cannot share the one I use).
2. Open it in **CodeBrowser** tool (do not auto analyze, it messes everything up due to the bug).
3. Some labels for global variables should be outside memory and the other ones are misplaced (NB labels for symbols in fully initialized or fully uninitialized sections are not affected).

**Expected behavior**
The symbols should be in the right place. 

**Root cause**
After investigation this is due to the section processing code in `processMemoryBlocks()`, which creates the `sectionToAddress` map, that is used to compute the addresses of the debug symbols.

When it encounters a partly initialized section, it creates two blocks:
- A first block containing the initialized data
- A second block containing the uninitialized data

Each time it creates a block it adds an entry in the `sectionToAddress` map (for initialized blocks, at https://github.com/NationalSecurityAgency/ghidra/blob/db932d222804311f08ee3c10273100395d58a082/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/PeLoader.java#L657 and, for uninitialized blocks, at https://github.com/NationalSecurityAgency/ghidra/blob/db932d222804311f08ee3c10273100395d58a082/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/PeLoader.java#L686). That is the issue: the address of the uninitialized block is overwritten over the address of the section.

**Proposed solution**
I replaced https://github.com/NationalSecurityAgency/ghidra/blob/db932d222804311f08ee3c10273100395d58a082/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/PeLoader.java#L686 by
```java
sectionToAddress.putIfAbsent(sections[i], address);
```
and everything worked fine (even auto-analysis). See [peLoader.patch.gz](https://github.com/NationalSecurityAgency/ghidra/files/10202411/peLoader.patch.gz)

**Environment (please complete the following information):**
 - OS: OpenSUSE Tumbleweed (Linux 6.0.10-1-default)
 - Java Version: openjdk 17.0.5
 - Ghidra Version: 10.3 (commit `db932d222804311f08ee3c10273100395d58a082`)
 - Ghidra Origin: locally built

**Comment by ryanmkurtz** [comment]
Thank you for the nice write up and proposed solution.  I agree with your solution, and will work on getting it committed in.

**Comment by pasccom** [comment]
Thanks for the correction!
