### ISSUE TITLE
Decompiler: Rebuild with Bison 3.8.2 without '#line' directives

### ISSUE THREAD

**Issue by jobermayr** [NationalSecurityAgency/ghidra#4816]
See https://github.com/jobermayr/ghidra-staging/blob/master/0000-Regenerate-with-Bison-3.8.2.patch

If it is a valid patch from "outside" I will create a pull request ...

**Comment by jobermayr** [comment]
On my ghidra-staging project I have some patches (pull requests from here) touching .y or .l files and require regeneration of .cc or some .hh files (e. g. 1409, 2810, 2969, 3271, 4812). #line directives pollute then the actual patch since all lines after the inserted one in .y or .l file are at least +1.  So if you insert a line at beginning of source file all #line directives in regenerated file(s) get updated.
If you build with `yacc -l` or `lex -L` only the relevant code gets changed and nothings gets polluted by #line changes.
There should be one commit to start with new style like I did ...

**Comment by ryanmkurtz** [comment]
Thank you for the explanation.  When we accept patches and pull-requests from the public, we need to review every character.  There are over 14,000 lines in this patch to sift through, so realistically, this will never be something we will move forward with.

**Comment by jobermayr** [comment]
Can you then regenerate it intern and publish it? To avoid build errors the actual change before regeneration is:
```
diff --git a/Ghidra/Features/Decompiler/src/decompile/cpp/pcodeparse.y b/Ghidra/Features/Decompiler/src/decompile/cpp/pcodeparse.y
index c858fa148..a77fd3371 100644
--- a/Ghidra/Features/Decompiler/src/decompile/cpp/pcodeparse.y
+++ b/Ghidra/Features/Decompiler/src/decompile/cpp/pcodeparse.y
@@ -14,6 +14,15 @@
  * limitations under the License.
  */
 %{
+/* Substitute the variable and function names.  */
+#define yyparse         pcodeparse
+#define yylex           pcodelex
+#define yyerror         pcodeerror
+#define yydebug         pcodedebug
+#define yynerrs         pcodenerrs
+#define yylval          pcodelval
+#define yychar          pcodechar
+
 #include "pcodeparse.hh"
 
   //#define YYERROR_VERBOSE
diff --git a/Ghidra/Features/Decompiler/src/decompile/cpp/xml.y b/Ghidra/Features/Decompiler/src/decompile/cpp/xml.y
index 8f5386237..5722caf2e 100644
--- a/Ghidra/Features/Decompiler/src/decompile/cpp/xml.y
+++ b/Ghidra/Features/Decompiler/src/decompile/cpp/xml.y
@@ -14,6 +14,15 @@
  * limitations under the License.
  */
 %{
+/* Substitute the variable and function names.  */
+#define yyparse         xmlparse
+#define yylex           xmllex
+#define yyerror         xmlerror
+#define yydebug         xmldebug
+#define yynerrs         xmlnerrs
+#define yylval          xmllval
+#define yychar          xmlchar
+
 #include "xml.hh"
 // CharData mode   look for '<' '&' or "]]>"
 // Name mode       look for non-name char
```

**Comment by ryanmkurtz** [comment]
I will assign this to someone on the team for further investigation.

**Comment by caheckman** [comment]
```#line``` directives were removed in commit 945d91fc935880026166c3a6b83c19d91cfef044

**Comment by jobermayr** [comment]
I cannot see the requested usage of a current Bison version. So I suggest to reopen it until this happens as well.

**Comment by ryanmkurtz** [comment]
Can you describe why the bison upgrade is needed?

**Comment by jobermayr** [comment]
> Can you describe why the bison upgrade is needed?

Counterquestion: Can you easily find your used 8,5 years old version 3.0.4 on many current OSes (esp. Linux distributions)?
