### ISSUE TITLE
Cannot override context registers

### ISSUE THREAD

**Issue by fenugrec** [NationalSecurityAgency/ghidra#4817]
**Describe the bug**
Not sure if this qualifies as a "bug", would appreciate input.

On e.g. mc68000, there are context registers such as `pcmode`. Attempting to change that on a single instruction is not allowed :

``` Context register change conflicts with one or more instructions ```

Yes, I know it conflicts, but I want to override it because I (hopefully) know better.

**To Reproduce**
1. open any mc68000 dump (e.g. https://github.com/NationalSecurityAgency/ghidra/files/8554646/cmpi.bin.zip )
2. no need to analyze, just diassemble any random instruction
3. Ctrl-R (Set Register value) , choose "pcmode" in dropdown, and enter '1' the new value.
4. Get error box

**Expected behavior**
Using the new context register value, possibly needing to re-analyze whatever flows from the selected instruction ?

**Environment (please complete the following information):**
 - Java Version: 19
 - Ghidra Version: 10.2.2
 - Ghidra Origin: distro

**Additional context**
I'm encountering this issue while testing (again) the proposed fix for #2423 , where it would be a normal workflow to manually adjust certain call/jmp opcodes to end up in the correct bank.

**Comment by mumbel** [comment]
You cannot change context of disassembled instructions, the instructions can depend on the context to decode.  This is working as intended.  Clear the instruction, change the context and disassemble.

**Comment by fenugrec** [comment]
> the instructions can depend on the context to decode

That's precisely why I want to change the context. But no matter, if it's intended behaviour, as long as I can work around it.

Thanks for the clarification.
