### ISSUE TITLE
Headless PE Import produces different results from GUI

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4821]
**Describe the bug**
Importing a PE in headless mode results in imported library functions being unresolved.

**To Reproduce**
1. Compile the example source code seen here https://learn.microsoft.com/en-us/windows/win32/winsock/complete-server-code
2. Run `analyzeHeadless . bugs -import main.exe`
3. Once complete open the project and file in the gui, go to the symbol tree, expand imports, expand WS2_32.DLL
4. See a ton of "Ordinal_xyz" imports.
5. Close the Code Browser, delete main.exe from the project and reimport it in the GUI.
6. Once importing is complete, open main.exe in the Code Browser, go to the symbol tree, expand imports, expand WS2_32.DLL
7. See that the imported functions are properly names.

**Expected behavior**
The importer should behave the same with the default options in both headless and GUI mode.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22621.900]
 - Java Version: 17.0.4
 - Ghidra Version: 10.2.1
 - Ghidra Origin: official GitHub distro

**Additional context**
This issue is also present in 10.3_DEV

**Comment by dragonmacher** [comment]
Are they consistently inconsistent?  I sometimes wonder if analysis is non-deterministic.  :thinking:

**Comment by astrelsky** [comment]
> Are they consistently inconsistent?  I sometimes wonder if analysis is non-deterministic.  :thinking: 

The library imports are resolved when loading. Analysis doesn't need to be run and this is consistent. I was initially trying to figure out why the imports weren't being resolved on linux for a docker container even though I had the exports files installed. I eventually discovered that they weren't being resolved at all.

Also I notice that there are no export files in %USERPROFILE%\.ghidra\.ghidra_10.3_DEV\symbols\win... which definitely should not be the case.

**Comment by astrelsky** [comment]
> I'm doing a lot of loader refactoring. Could you try [this branch](https://github.com/ryanmkurtz/ghidra/tree/loader)?

It looks like it works properly in this branch, at least on windows.

**Comment by astrelsky** [comment]
@ryanmkurtz just finished testing on a linux vm and it works as expected. 

Will this fix be backported to 10.2? Headless analysis on a pe is effectively useless due to this bug.

**Comment by ryanmkurtz** [comment]
It won't be, but I'll investigate your problem in the `patch` branch and try to put in a simple fix, once I figure out what the problem is.

**Comment by astrelsky** [comment]
> It won't be, but I'll investigate your problem in the `patch` branch and try to put in a simple fix, once I figure out what the problem is.

Thank you.

**Comment by ryanmkurtz** [comment]
I think I have a simple fix for it for `patch`.

**Comment by astrelsky** [comment]
@ryanmkurtz is there a timeline for 10.2.3? I'm in a situation where 10.1.x cannot be used due to the Jython vulnerability and 10.2 cannot be used due to this bug.

**Comment by ryanmkurtz** [comment]
I can't quote an exact timeline, but on the order of soonish.  There are likely workarounds we can do for both the jython issue and this issue with the versions you have available if you are interested.

**Comment by astrelsky** [comment]
> I can't quote an exact timeline, but on the order of soonish.  There are likely workarounds we can do for both the jython issue and this issue with the versions you have available if you are interested.

Unfortunately I'm just a middleman here and it's better to just wait for the fix. Thank you anyway!
