### ISSUE TITLE
Flexible arrays not properly created from zero-length arrays.

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#483]
Is it possible? For example, structure contains cstring, or some array.

**Comment by ryanmkurtz** [comment]
The structure editor allows you to add "flexible arrays."  You do this by specifying an array length of 0.  The is a section in the the Structure Editor's help called "Flexible Array Component" if you want to read more about it.

**Comment by lab313ru** [comment]
![изображение](https://user-images.githubusercontent.com/7189309/56765886-c8116900-67b0-11e9-8043-f0858947d44a.png)

It is not true.

**Comment by lab313ru** [comment]
Also:
![изображение](https://user-images.githubusercontent.com/7189309/56766032-1f173e00-67b1-11e9-8726-055548ad36fb.png)

**Comment by lab313ru** [comment]
So, it only works with that button, but not with the manual input:
https://youtu.be/JNeiBS82CY8

**Comment by lab313ru** [comment]
It must be marked as a bug!

**Comment by ryanmkurtz** [comment]
I'll reopen it as a bug for now and consult the designer of the feature.  Thanks!

**Comment by ryanmkurtz** [comment]
@ghidra1, can you give you opinion?

**Comment by ryanmkurtz** [comment]
I got a bit more info on this for you.  Ghidra does not support 0-length DataType's, which is why we can't parse byte[0] in that table field in the structure editor.  The help correctly describes the only way to add flexible arrays.

**Comment by dzik87** [comment]
What about pointer to variable size table ?

**Comment by ghidra1** [comment]
You would simply add a pointer component
