### ISSUE TITLE
Ghidra front-end and user experience is deplorably terrible

### ISSUE THREAD

**Issue by RagingSmith** [NationalSecurityAgency/ghidra#4831]
**Is your feature request related to a problem? Please describe.**
It is a pain to use Ghidra to reverse engineer software.
Take highlighting for example: If I wanna quickly see all references to a local variable, my instinct is to click on it so I can highlight it. However, in Ghidra, doing this highlights the variable on only the current line.
Furthermore, some parts of the GUI just make no sense. There may be ways to change this, although I searched for corresponding settings but found none to my avail. The font size is probably the worst part, I can barely see the decompiler output or data view.

**Describe the solution you'd like**
Improve the user experience.

**Describe alternatives you've considered**
I've considered to not use Ghidra for the moment, which is depressing because I quite like this software.

**Additional context**
I'm aware that the budget isn't great, but I would expect such simple features which save so much time to be implemented. Please take this into account.

**Comment by ryanmkurtz** [comment]
Thank you for the feedback.  This ticket is to broad for us to take any specific action on.  I'd recommend creating individual tickets that are targetted at specific bug fixes, feature enhancements, or questions you might have (1 per ticket).
