### ISSUE TITLE
Ghidra cannot disassemble a LDS instruction in real mode

### ISSUE THREAD

**Issue by kevinferrare** [NationalSecurityAgency/ghidra#4832]
**Describe the bug**
C5B70D03 is supposed to disassemble to LDS SI,DWORD PTR [BX+030D]
However in ghidra I get an error:
Error | Bad Instruction | Unable to resolve constructor at f000:0026 | f000:0026 |   | ?? C5h

**To Reproduce**
Create a project in real mode and import hex C5B70D03 in the bytes view, and try to disassemble it

**Expected behavior**
Ghidra disassembles a LDS instruction

**Screenshots**
![image](https://user-images.githubusercontent.com/11456837/208163198-c59feae9-51ad-46ac-ba5e-3f01aa29d950.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - Java Version: 17.0.4
 - Ghidra Version: 10.1.5_PUBLIC
 - Ghidra Origin: official GitHub distro

**Comment by GhidorahRex** [comment]
Looks like this is an issue of a collision with the 0xC5 vexmode byte.
