### ISSUE TITLE
Comments with null characters cause decoding error.

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4836]
**Describe the bug**
Creating a pre comment which contains a null character in the decompiler will cause the following error. "Pcode: Decoding error: Expecting <doc> but did not scan element".

**To Reproduce**
1. Create a pre comment in the decompiler that contains a null character. (Note it will be invisible in the set comment box)

**Environment (please complete the following information):**
 - OS: Win10
 - Java Version: 17
 - Ghidra Version: 10.3_DEV

**Additional context**
This occurred when pasting text into the set pre comment box while being unaware it contained a null character.

**Comment by ryanmkurtz** [comment]
I am reproducing this on Linux.  How did you get a null character on your clipboard in Windows?

**Comment by astrelsky** [comment]
> I am reproducing this on Linux.  How did you get a null character on your clipboard in Windows?

I copy/pasted it from somewhere. I'm not 100% sure but I think I copied it from Ghidra's console window. Makes sense since java allows null in strings.
