### ISSUE TITLE
Can't connect to GDB over SSH without ~/ssh/config file -- v10.2.2

### ISSUE THREAD

**Issue by SirEnder125** [NationalSecurityAgency/ghidra#4837]
When I attempt to connect to my WSL ubuntu distro, I get this error in later versions, that require a `.ssh/config` file.
`Error while connecting to GDB: SSH connection error`

**To Reproduce**
1. Try to connect to GDB over SSH without specifying `.ssh/config` path. (`~/.ssh/config` doesn't exist for me`)
2. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/69535694/208559834-ef6dc4ff-2ba8-4122-a4ae-f2f9a37e2406.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.3
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official Ghidra distro (this repo) 

**Additional context**
I am able to connect to the same SSH server on version 10.0.4, it's just 10.2.2 that I've seen give this error.
I tried setting the `ssh config` setting in the "GDB over SSH" option to blank, but I still get the same error.

**Comment by SirEnder125** [comment]
I created the file `~/.ssh/config` on my Ubuntu distro, and I was able to connect after writing some random Host this and HostName that inside of it... Not sure what it intends to find in this file, but it gives me a warning when I connect, but since I can connect I don't really care if it says the file is invalid. Feel free to close this if you want. 👍🏻

**Comment by d-millar** [comment]
Will take a peek at this in a couple of days - see if I can figure out why the odd default behavior.

**Comment by d-millar** [comment]
Will take a peek at this in a couple of days - see if I can figure out why the odd default behavior.

**Comment by d-millar** [comment]
@SirEnder125 Trying to reproduce your error without much success.  I know you found a workaround, but am sure someone else will hit this eventually.  Have tried "GDB over SSH" with (1)  param set to "~/.ssh/config" but no actual "config" file, (2) param set to blank with no actual config file, (3) param set to "~/.ssh/confg" with an empty "config" file, and (4) param set to blank with an empty "config" file.  Connects to the host in all four cases.  Any guesses as to what I'm doing differently?

**Comment by SirEnder125** [comment]
Hmm.  I'm not too sure, I thought ghisra just didn't like me... The error was about the file not being able to be parsed, but I think I got it when there wasnt even a `~/.ssh/config` file on my wsl.. :thinking: Then I added some random stuff to a new config file and I guess I got the error still.. but that's what you did you? For anyone else seeing this, please share if you encountered the same error??

**Comment by d-millar** [comment]
Just to be clear, I definitely am getting the warning (which probably should be suppressed for at least summer of the cases), but I'm not getting the error, which I'm a little more worried about.

**Comment by SirEnder125** [comment]
Huh. Forgot there was more to this than an error. 🤔 Well I think that got cleared up when I added a host to the config file... Which is odd if you're not getting the error as well .. or maybe I had the wrong IP address entered? I'm not too sure, sorry :(
