### ISSUE TITLE
Functions not correctly identified and named with PDB in 10.2.2

### ISSUE THREAD

**Issue by MHLoppy** [NationalSecurityAgency/ghidra#4842]
**Describe the bug**
(my knowledge of correct terminology is limited as I'm a novice amateur)

When loading a PDB file, function names are not correctly applied in 10.2.2. It appears that Ghidra does "know" what the names are, but the functions are seemingly not fully identified as functions (?) and are not given their "known" name. (see screenshots)

This behavior was checked in other versions including 10.2.0 and 10.2.1 and this issue was not present in those versions when using the same files in new projects.

**To Reproduce**
1. Create new project and import exe.
2. Open CodeBrowser for this exe, and load its PDB file (default settings, including Universal parser).
3. After the PDB is loaded (regardless of before/after further analysis is complete), functions are not correctly identified/named.

**Expected behavior**
I would expect these functions to be identified and named using the information in the PDB, as was observed in prior versions.

**Screenshots**
Screenshots are provided for behavior in both 10.2.1 and 10.2.2 for comparison:
![image](https://user-images.githubusercontent.com/12670674/209211901-fda078a9-2dc4-4ef9-aef8-8506f8d6a79e.png)
![image](https://user-images.githubusercontent.com/12670674/209211920-9ae24954-a87f-477d-8780-6f2b1e62c979.png)

**Attachments**
Both the executable and its PDB are proprietary, so I'm not sure if I'm able to share them but I'm happy to provide more details as required.

**Environment:**
 - OS: Windows 10 22H2 (10.0.19045)
 - Java Version: 17.0.5
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub releases

**Additional context**
I noticed in the [10.2.2 changelog](https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.2.2_build/Ghidra/Configurations/Public_Release/src/global/docs/ChangeHistory.html) that there was a change relating to overriding symbols on functions - related? I skimmed through issues from the past month and didn't see any that seemed to be what I'm experiencing.

**Comment by ghizard** [comment]
This was broken by #4735.  In that issue, I note the commit that will fix this regression in 10.2.3.

**Comment by ryanmkurtz** [comment]
Fixed by 88b7734608498065c92835ff5ee1d25ab9a9a19b
