### ISSUE TITLE
Call to virtual function is being decompiled ignoring specified calling convention.

### ISSUE THREAD

**Issue by kscieslinski** [NationalSecurityAgency/ghidra#4844]
Submitting this as a question, as I have a feeling that it's not a bug, but rather my missunderstanding of Ghidra api.

**Describe the question**
I've a problem with how a call to virtual function is being decompiled.

**To Reproduce**
I've defined vtable for `packet_t` structure as follows. 
Note that below is just a clike representation which was actually defined by using GUI interface (new->structure/new->function definition).
```c
// function definition
[...]
undefined4 __thiscall packet_func1(packet_t*);
[...]

// virtual table definition
struct vtable_packet_t {
    [...]
    packet_func1* func1;
    [...]
};

struct packet_t {
    vtable_packet_t* vtable;
    [...]
};
```

Now sample `foo` function with a call to `packet->vtable->func1`:
```asm
                        **************************************************************
                        *                          FUNCTION                          *
                        **************************************************************
                        void __thiscall foo(packet_t * this, undefined4 param_2, undefined4 param_3)
                        assume FS_OFFSET = 0xffdff000
        void              <VOID>         <RETURN>
        packet_t *        ECX:4          this
        undefined4        Stack[0x4]:4   param_2
        int               Stack[0x8]:4   param_3
                        packet::foo
PUSH       ESI
MOV        ESI,this
MOV        EAX,dword ptr [ESI]
MOV        EDX,dword ptr [EAX + 0x4]
CALL       EDX
```

gets decompiled like this:
```c
void __thiscall packet::foo(packet_t *this, undefined4 param_2, int param_3)
{
    undefined4 uVar1;
    uint uVar2;
    short *psVar3;
    packet_t *unaff_EBX;
    packet_t *unaff_ESI;
    int in_stack_0000000c;

    uVar1 = (*this->vtable->func1)(unaff_ESI);
    [...]
```

**Expected behavior**
I would expect it to use `ecx` register instead of `esi` register (as this is x86:LE:32:default windows architecture).
```c
void __thiscall packet::foo(packet_t *this, undefined4 param_2, int param_3)
{
    undefined4 uVar1;
    uint uVar2;
    short *psVar3;
    packet_t *unaff_EBX;
    packet_t *unaff_ESI;
    int in_stack_0000000c;

    uVar1 = (*this->vtable->func1)(this);
    [...]
```

**Environment**
OS: Windows 11
Java Version: openjdk 17.0.5
Ghidra Version: 10.2.2
Ghidra Origin: official GitHub distro

**Comment by lmichaelis** [comment]
I have run into a similar issue where I select the `fastcall` calling convention

![image](https://user-images.githubusercontent.com/20187490/209945677-92899ed3-a159-4818-b5c8-078c7ec00492.png)

But the resulting function call is being misinterpreted:

![image](https://user-images.githubusercontent.com/20187490/209945826-a3bb9564-529a-49cd-a672-8dd53861eacb.png)

![image](https://user-images.githubusercontent.com/20187490/209945864-38589d91-5dcc-4520-9574-65c5b8b670e4.png)
(where `param_1` is in ECX and `param_2` is in EDX)

I would expect it to generate 

```
(*param_2->vptr->WriteInt)(param_2, &s_pack, 0x1)
```

instead. Changing the calling convention back and forth doesn't change anything either.

**Comment by astrelsky** [comment]
Don't quote me on this but I think the same problem arises when overriding a variadic function signature.

**Comment by ghidra007** [comment]
@kscieslinski Try creating a structure with the name of your class packet and putting as the first element in the structure a pointer to your vftable structure. Your function definitions should not include the this param in the definition, only the other params in the function.  When you put a function into a class, the decompiler should assign the same named structure to the this. It can get confused if there are more than one of the same name and may use the wrong one. I think it gets the first one it finds unless you set an option for the preferred location to look.

**Comment by kscieslinski** [comment]
Hi. Sorry for late reply, but I missed the notification. Unfortunately the proposed solution did not worked. 

Moreover wouldn't it work only for a functions using`this` calling convention? As noted by the other users, this seems to be a more general problem (as other calling conventions also do not work).

**Comment by ghidra007** [comment]
@kscieslinski @lmichaelis @astrelsky One of our developers was able to recreate an example that caused this scenario in 10.2.2. In their example it is no longer happening in 10.2.3. Would you try 10.2.3 and let us know if you are still seeing the issue or not? Thanks!

**Comment by astrelsky** [comment]
I don't have a sample on hand that demonstrates the problem. Just didn't want to leave you hanging without any response.

**Comment by lmichaelis** [comment]
> @kscieslinski @lmichaelis @astrelsky One of our developers was able to recreate an example that caused this scenario in 10.2.2. In their example it is no longer happening in 10.2.3. Would you try 10.2.3 and let us know if you are still seeing the issue or not? Thanks!

Thanks, I can verify that my original example does now decompile properly. I can also confirm that calling conventions other than `__thiscall` work correctly as well.

I should probably mention that I am using a file I've upgraded from Ghidra 10.1.2, though I have changed and re-assigned the calling conventions as well as auto-analyzed the entire binary again.
