### ISSUE TITLE
Perform Library Ordinal Lookup can cause unwanted Libraries to be imported

### ISSUE THREAD

**Issue by soroosh-chabi** [NationalSecurityAgency/ghidra#4849]
**Describe the bug**
During the import of a PE file, if "Perform Library Ordinal Lookup" option is checked, checking either of "Load Local Libraries From Disk" and "Load System Libraries From Disk" will imply checking the other and thus all imported libraries of the file being imported are imported into the project.

**To Reproduce**
1. In an empty project, select File -> Import File...
2. In the file chooser dialog, select a PE file that if imported once with "Load Local Libraries From Disk" and another time with "Load System Libraries From Disk" checked, will cause other DLL's being imported into the project.
3. In the import dialog, press Options.
4. In the options dialog, make sure only one of "Load Local Libraries From Disk" and "Load System Libraries From Disk" is checked while "Perform Library Ordinal Lookup" is also checked.
5. Press OK on both dialogs and continue the import process.
6. As you can see, all the DLL's that would have been imported had "Load Local Libraries From Disk" and "Load System Libraries From Disk" been checked, are imported with only one checked simply because "Perform Library Ordinal Lookup" was checked.

**Expected behavior**
Checking "Perform Library Ordinal Lookup" should not cause the import of libraries that would otherwise not be imported.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 17
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
I am reproducing this, thanks.
