### ISSUE TITLE
float10 values are incorrect in the listing view

### ISSUE THREAD

**Issue by the-nerbs** [NationalSecurityAgency/ghidra#4853]
**Describe the bug**
Values of the `float10` data type are displayed incorrectly in the listing view.

**To Reproduce**
1. Compile the following C99 program with GCC or Clang targeting x86 without optimizations:
   ```c
   #include <stdio.h>
   
   long double float80Value = 1.0;
   
   int main() {
      // printf only to ensure the value is included in the built executable
      printf("%Lf, %p\n", float80Value, &float80Value);
   }
   ```

2. Load the resulting executable in Ghidra, selecting the appropriate compiler from the import options.

3. Open the executable in the Code Browser, and run the default analyzers when prompted.

4. Navigate to the `float80Value` label in the Symbol Tree.

5. Change the data type of the bytes at the label to `float10`.

6. Observe the value in the listing view is "1.5", not matching the value in the source.

**Expected behavior**
Expected is that the 10 byte float value in the Listing is "1", matching the 1.0 value in the source.

**Screenshots**
![image](https://user-images.githubusercontent.com/25137888/209631246-35df5483-4aa8-4d83-b4e1-4b5ed0b9af6c.png)

**Environment (please complete the following information):**
 - OS: Windows 7
 - Java Version: OpenJDK 19.0.1
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub distro

**Additional context**
I have tried a few simple cases with values 0.5, 1.0, and 2.0; resulting in 0.75, 1.5, and 3 respectively. Based on these and my own lack of knowledge of how Ghidra is reading these values, I suspect Ghidra may be treating the top-most bit of the mantissa as part of the fractional value when it is actually an explicit integer part (unlike the common single and double precision formats).

I ran another test with a more complex number, pi (3.1415926535897932384; float10 bits = 0x4000c90fdaa22168c000), for which Ghidra gave the value 3.57079632679489656. If I right-shift pi's mantissa bits one place, and set the mantissa's high bit (resulting in 0x4000e487ed5110b46000), this bit pattern has the same value that Ghidra displays, which also seems to line up with my suspicion.

For completeness sake, I compiled the test code from the reproduction steps using the following command lines in Cygwin:
- Clang (8.0.1): `clang main.c -O0 -std=c99 -o output-clang.exe`
- GCC (11.2.0): `gcc main.c -O0 -std=c99 -o output-gcc.exe`

**Comment by ghidracadabra** [comment]
I can reproduce this; thanks for reporting it.
