### ISSUE TITLE
[Sleigh] Operand manipulation results in "goto" low-level error

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#4855]
This is a valid operand description (jump destination, pointers are 24bit, but 32 bit is also doesn't work):
```
addr_pc: $imm16 is imm16 { export *:1 imm16; }

:JMP addr_pc is (op=0x4C); addr_pc { goto addr_pc; }
```

And this one is not (leads to low-level error):
```
addr_pc: $imm16 is imm16 { off16:3 = imm16; export *:1 off16; }

:JMP addr_pc is (op=0x4C); addr_pc { goto addr_pc; }
```

In the first case Sleigh generates the following p-code:
```
BRANCH *[ram]0x92cc:1
```

In the second case Sleigh generates the following p-code:
```
$U2380:3 = COPY 0x92cc:3
$U2400:1 = LOAD ram($U2380:3)
BRANCH $U2400:1
```

And the error is:
```
 Low-level Error: Could not find op at target address: (unique,0x00002400)
 ```

I wasn't able to fix my operand definition to generate a correct p-code. Even any simple modification of a `goto` target address does that.

**Comment by lab313ru** [comment]
There is no such error in `10.1.5 RELEASE`.

**Comment by lab313ru** [comment]
Here is an example: https://github.com/achan1989/ghidra-65816/

**Comment by GhidorahRex** [comment]
> This is a valid operand description (jump destination, pointers are 24bit, but 32 bit is also doesn't work):
> 
> ```
> addr_pc: $imm16 is imm16 { export *:1 imm16; }
> 
> :JMP addr_pc is (op=0x4C); addr_pc { goto addr_pc; }
> ```
> 
> And this one is not (leads to low-level error):
> 
> ```
> addr_pc: $imm16 is imm16 { off16:3 = imm16; export *:1 off16; }
> 
> :JMP addr_pc is (op=0x4C); addr_pc { goto addr_pc; }
> ```
> 
> In the first case Sleigh generates the following p-code:
> 
> ```
> BRANCH *[ram]0x92cc:1
> ```
> 
> In the second case Sleigh generates the following p-code:
> 
> ```
> $U2380:3 = COPY 0x92cc:3
> $U2400:1 = LOAD ram($U2380:3)
> BRANCH $U2400:1
> ```
> 
> And the error is:
> 
> ```
>  Low-level Error: Could not find op at target address: (unique,0x00002400)
> ```
> 
> I wasn't able to fix my operand definition to generate a correct p-code. Even any simple modification of a `goto` target address does that.

You need brackets around a varnode in this case. So the correct syntax would be `goto [addr_pc];`. However, there's very little reason for you to export the immediate as a varnode. You're better off exporting a constant value (`export *[const]:2 imm16`) in this instance. See, for example, the answer to this question: https://github.com/NationalSecurityAgency/ghidra/discussions/4851

**Comment by lab313ru** [comment]
Thanks, it works, but the decompiler shows something like that and doesn't automatically disassembles the destination:
```
                    /* WARNING: Could not emulate address calculation at 0x008213 */
                    /* WARNING: Treating indirect jump as call */
  (**(code **)((uint3)bVar3 << 0x10 | 0x92cc))();
```

Should it be processed using an analyzer?

**Comment by lab313ru** [comment]
Thanks, it works!
