### ISSUE TITLE
Decompiler view showing return address and function arguments as locals

### ISSUE THREAD

**Issue by JesseAusten** [NationalSecurityAgency/ghidra#4858]
**Describe the bug**
On many x86:LE:32:default binaries, the decompiler view is showing return addresses and function arguments being pushed on the stack as local variables.

**To Reproduce**
Import attached binary, auto analyze with default options.
Go to one of many functions, for example `FUN_08049839`.
See decompiler output at function calls, for example at `0804996b`.

**Expected behavior**
No return address should be shown, and arguments should be in the function call parenthesis.

**Screenshots**
![image](https://user-images.githubusercontent.com/13514555/210006569-f5841f9e-599d-4743-8869-ba49fd6432f1.png)

**Attachments**
[info.gz](https://github.com/NationalSecurityAgency/ghidra/files/10321887/info.gz)

**Environment**
 - OS: Ubuntu 20.04
 - Java Version: 14
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official GitHub distro

**Additional context**
I have seen this across a myriad of different x86 binaries. Even after giving every function the correct arguments and return types, ensuring stack depth is correct, giving local variables types, the issue persists.

**Comment by mumbel** [comment]
https://github.com/NationalSecurityAgency/ghidra/issues/4645

how is this not a dup of your other issue?
