### ISSUE TITLE
Decompiler interprets SHUFPS Z values as 0.

### ISSUE THREAD

**Issue by Joey35233** [NationalSecurityAgency/ghidra#4868]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. Compile
```c
#include <cstdio>
#include <xmmintrin.h>

int func(const __m128 v)
{
    __m128 x = _mm_shuffle_ps(v, v, 0x00);
    __m128 y = _mm_shuffle_ps(v, v, 0x55);
    __m128 z = _mm_shuffle_ps(v, v, 0xAA);

    __m128 s = _mm_add_ps(x, y);
    s = _mm_add_ps(s, z);

    return _mm_cvtt_ss2si(s);
}

int main(int argc, char** argv)
{
    __m128 v = _mm_setr_ps(30 * argc, 0.3 * argc, 0.4 - argc, 0);
    int sum = func(v);
    printf("Result: %d", sum);

    return 0;
}
```
2. Compile with MSVC (any version, at least from 2013 to latest)
3. The disassembly should say something akin to ``_func__cdecl_int_char_ptr("Result: %d",(int)((float)_Argc * 0.3 + (float)(_Argc * 30) + 0.0));``. Note the incorrect ``0.0`` in place of ``0.4 - (float)_Argc``.

**Expected behavior**
It appears that the result of ``SHUFPS XMM#, 0xAA`` gets turned into 0.0, which is very difficult to work with for many executables. Here's a direct example below:

**Screenshots**
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/13488195/210450610-616ff823-c803-4117-8bfc-772d282ef52a.png">

**File:**
- Language ID: x86:LE:64:default (2.13)
- Compiler ID: windows
- Processor: x86
- Endian: Little
- Address Size: 64

**Environment:**
 - OS: Windows 11 22621.963
 - Java Version: openjdk 19 2022-09-20
 - Ghidra Version: 10.2.2
 - Ghidra Origin: https://github.com/NationalSecurityAgency/ghidra/issues/releases

**Comment by ghidracadabra** [comment]
Thanks for reporting this.  There's an issue with the generated pcode; should be an easy fix.
