### ISSUE TITLE
Re-name TaskMonitor.checkCanceled() to checkCancelled()

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#4870]
**Is your feature request related to a problem? Please describe.**
It's a constant pain to remember which is mis-spelled between checkCanceled(), isCancelled(), or CancelledException.  At some point, it would be good to just bite the bullet and start spelling checkCancelled() correctly..

**Describe the solution you'd like**
Add checkCancelled() to TaskMonitor and deprecate checkCanceled().

**Comment by dragonmacher** [comment]
One of my long standing pet peeves.

Adding updated versions of all 'canceled' methods sounds like a reasonable request.   It would cause a large number of code changes to remove the old methods, but they can slowly be migrated over time.

**Comment by astrelsky** [comment]
https://www.grammarly.com/blog/canceled-vs-cancelled/

color, colour same thing. Both spellings may be technically correct.
