### ISSUE TITLE
PDB processing error in 10.2.2

### ISSUE THREAD

**Issue by cmon-meow** [NationalSecurityAgency/ghidra#4873]
When loading PDB for debug binary in 10.2.2 code generation changes dramatically, only labels are added, not function names or params.
Example of this "void cdecl _funccdeclfunccdecl_void_int_ptr_intfunccdecl_void_int_ptr(int param_1)"
Many functions named (type call func) repeatedly Eg."void cdecl void(void)", code generated isn't any better.
This is not so for 10.1.4 whereas the code is nicely generated/readable/fairly well labeled vs standard analyses.

**Comment by dev747368** [comment]
Looks like same issue as #4842, and it may already be fixed in https://github.com/NationalSecurityAgency/ghidra/commit/88b7734608498065c92835ff5ee1d25ab9a9a19b
