### ISSUE TITLE
Auto Create/Fill In Structure fails on large structures

### ISSUE THREAD

**Issue by dmchurch** [NationalSecurityAgency/ghidra#4879]
I'm reverse-engineering some code with incredibly large data structures, and my workload is much higher than it needs to be because the Auto Fill In Structure command arbitrarily stops working after offset 0x1000:

https://github.com/NationalSecurityAgency/ghidra/blob/a8cdc43bd4c885f5714f6267e6a4b29f05572bf9/Ghidra/Features/Decompiler/src/main/java/ghidra/app/plugin/core/decompile/actions/FillOutStructureCmd.java#L566

It's entirely reasonable to avoid improperly making huge structures, especially since they can slow Ghidra to a crawl, but can we change this value to be either (a) configurable in the UI or (b) reactive to the current size of the structure? I feel like

```
*(undefined8*)(this + 0xFF0) = 0;
*(undefined8*)(this + 0xFF8) = 0;
*(undefined8*)(this + 0x1000) = 0;
*(undefined8*)(this + 0x1008) = 0;
```

shouldn't stop creating fields in the middle just because an arbitrary limit got reached. Maybe something like `max(0x1000, current_size * 2)` would make more sense? Or at the very least, if using the "Fill In Structure" variant of the command, set that maximum to no less than the size of the existing structure.

**Comment by dmchurch** [comment]
Honestly the 4k default size limit seems reasonable enough, having a single allocated structure exceed a single memory page is a bad code smell. But sometimes we have to reverse-engineer stinky code, of course 😅

Nonetheless, I wouldn't want to ditch the size limit entirely, just because Ghidra has such trouble with large, unpopulated structures. I feel like it'd be simple enough to use Auto Recover to create the first 4k of the structure, see `this[0x26]` in the decomp output, manually increase the structure size, and then use Auto Fill In to snag the rest of the fields. So if that 0x1000 can just clamp itself to the existing structure size as a minimum, that'd be golden 🙂

**Comment by dmchurch** [comment]
@ryanmkurtz I've left some comments on the commit; you don't have to take them, of course, but I think they'll probably improve the code and the feature if so.

**Comment by ryanmkurtz** [comment]
I'll defer this to @dragonmacher

**Comment by dragonmacher** [comment]
> @ryanmkurtz I've left some comments on the commit; you don't have to take them, of course, but I think they'll probably improve the code and the feature if so.

Thanks for your input.   I responded to your comments.
