### ISSUE TITLE
Feature Request: HTML String column type for use in TableChooserDialog

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4880]
**Is your feature request related to a problem? Please describe.**
I would like to be able to format some strings that are displayed in a TableChooserDialog - for example, color, while preserving the ability to search using filters like "Starts With" or "Matches Regex"

**Describe the solution you'd like**
A ``HTMLStringColumnDisplay`` column type that behaves like ``StringColumnDisplay`` but renders with HTML. A corresponding row object type ``HTMLStringAddressableRowObject`` might help but I don't think it is strictly necessary.

**Describe alternatives you've considered**
The closest I have right now is some ugly black magic, but searching the table runs into problems e.g. "Starts With" no longer works as the string starts with ``<html>blah blah``.

```
private void configureTable(TableChooserDialog tableChooserDialog) {
...
	Field field = TableChooserDialog.class.getDeclaredField("table");
	field.setAccessible(true);
	Object obj = field.get(tableChooserDialog);
	if (obj instanceof GhidraTable) {
		table = (GhidraTable) obj;
		table.setHTMLRenderingEnabled(true);
	}
...
}
...

protected String htmlFormatString(String colorString, String s) {
	if (colorString == null) {
		return s;
	} else {
		return String.format("<html><span style= color:%s>%s</span></html>", colorString, s);
	}
}
```

**Additional context**
![image](https://user-images.githubusercontent.com/55233728/211245473-b199898a-4077-4df0-9ef5-a96a8bdd9de5.png)

**Comment by sad-dev** [comment]
Also, the html> ... appears in the search suggestions regardless of whether I call ``setHTMLRenderingEnabled`` on the table. I think this is probably a bug; does this need a separate issue?

**Comment by dragonmacher** [comment]
Hello @sad-dev!  You are treading dangerously close to the edge of what the `TableChooserDialog` was meant to provide.   This dialog is a layer of abstraction that sits on top of the core UI API.  What you seek in this ticket is possible with the full API, but has not been exposed in this simplified API. 

I was hoping to find a workaround, but it seems that this layer simply does not provided the method calls you would need for this request.    The changes required are probably trivial, but would only be available in a future release, which doesn't help  you now.

**Comment by dragonmacher** [comment]
There is now a change in the master branch that should allow you to do this.

The new relevant code added is in `ColumnDisplay`.  There is now a method you can override to specify a cell renderer for the column.  This gives you a hook to change both the display (to use html) and the filter text (to no use html).   

Here is an example, a custom `TableChooserDialog` table column, that uses the new code:

```
StringColumnDisplay htmlColumn = new StringColumnDisplay() {

	private GColumnRenderer<String> renderer = new AbstractGColumnRenderer<String>() {

		{
			setHTMLRenderingEnabled(true);
		}

		@Override
		public Component getTableCellRendererComponent(GTableCellRenderingData data) {

			JLabel label = (JLabel) super.getTableCellRendererComponent(data);

			String name = (String) data.getValue();
			setText("<html>Test of bold: <b>" + name + "</b>");

			return label;
		}

		@Override
		public String getFilterString(String t, Settings settings) {
			return "Test of bold: " + t;
		}
	};

	@Override
	public String getColumnName() {
		return "Html";
	}

	@Override
	public String getColumnValue(AddressableRowObject rowObject) {
		FuncBodyData data = (FuncBodyData) rowObject;
		return data.getFunction().getName();
	}

	@Override
	public GColumnRenderer<String> getRenderer() {
		return renderer;
	}
};
```

This example shows what is needed to use html, which is to provide your own renderer that allows you to enable the html rendering, create the html content, and to use the raw text without html that is used by the filtering code.
