### ISSUE TITLE
Can't change format from raw binary?

### ISSUE THREAD

**Issue by aaronsushinsky** [NationalSecurityAgency/ghidra#4885]
Hey everyone.
New user here. Decoded a base64 block of code and had Ghidra try to read this document (saved as a normal nano document and as a .c file). Every time I do, the only format option in the drop-down menu is Raw binary and I have to manually pick a language. The file decoded is an ELF file so I want it to be read that way. I made sure to manually install the JDK 17 file and set the path using the command `vi ~/.bashrc` PATH: `export PATH=</home/kali/Tools/jdk-17/bin>/bin:$PATH` still to no avail. Am I missing something?
Thanks

**Comment by ryanmkurtz** [comment]
If you run the Linux `file` command on your file, does it get reported as and ELF?

**Comment by aaronsushinsky** [comment]
No, the original file wasn't really a file, just a bunch of text I had access to (CTF challenge). The original file comes back as an ASCII text file (no surprise) but i copied the decoded stuff I got into another nano file, and the `file` command said this `decoded.c: Unicode text, UTF-8 text, with very long lines (352)`

**Comment by ryanmkurtz** [comment]
I didn't quite follow everything you laid out.  But, the file you are importing into Ghidra hoping to load as an ELF file...what does `file` output on that?  If it's not ELF, Ghidra would not be expected to offer ELF as a choice.

**Comment by aaronsushinsky** [comment]
Figured out what was wrong, this was a me problem. Long story short I used the decode function and just copy and pasted the characters straight from the terminal. I was supposed to do `base64 -d encrypted.txt > unencrypted.elf`. Ghidra wasn't allowing another option because I didn't have it in the right format to begin with. Thanks for helping me figure that out.
