### ISSUE TITLE
String "Starts With" filter fails for <html> strings

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4889]
Noticed this while playing with tables for #4880 , but this bug can be replicated in other string column filters.

**Screenshots**

![image](https://user-images.githubusercontent.com/55233728/211780813-f2e48670-8bbd-4454-a225-d10cd15ac8a6.png)

**Comment by dragonmacher** [comment]
In my testing, the display looks like  yours but the filter matches the text I enter as I would expect.

I'm looking into this.  What exactly is the behavior that is not working as expected?    Does applied filter not match?  Is the drop-down in your image not working as you expect?
