### ISSUE TITLE
Provide a mechanism to override java's username, or at least accept a username with '@' in it.

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#4891]
**Is your feature request related to a problem? Please describe.**
In my corporate environment, on my linux machine, I am forced to have a username from LDAP that looks line "user@domain".  It seems that java unconditionally uses getpwent() to retrieve the user name from linux, and that is then forced to be the user name sent to the ghidra server to log in.

But, the ghidra server rejects any user name with '@' in it as invalid.

I am currently working around this by adding another line in the /etc/passwd file with my preferred user name and the same uid as the LDAP uid.  I fear, however, that corporate policy will eventually catch up with me and I will be stuck.

**Describe the solution you'd like**
At a minimum, I really don't see any reason that the ghidra server should pick on the '@' character and reject user names containing that.

I would, however, prefer some mechanism to supply a user name of my own choosing and not relying on java's mechanism that is tied to getpwent().  Perhaps an environment variable "GHIDRA_USERNAME" or even "USERNAME", if present, could override the username supplied by java?

**Comment by RootCubed** [comment]
I had actually implemented this functionality quite some time ago at https://github.com/RootCubed/ghidra/commit/687dc163680db4f655db03c10a6c80e4cc36b0e3, but never submitted a PR. If someone on the Ghidra team can tell if they would be interested in this functionality, I can submit one. (Obviously, the server bug should be fixed too, but just to have that extra option as well)

**Comment by dev747368** [comment]
@marcushall42 if the ghidra server is configured to have a "-u" option in server.conf as one of its wrapper.app.parameter.NN params, the user will be given the chance to change their login name when connecting to the server.  Does this option not help your situation?

**Comment by RootCubed** [comment]
Ah, sounds like that probably is indeed what was initially asked for. For clarification, the commit I sent changes the name that appears in the label history view for example, which is currently always the system username. Some users may wish to not share this information, which is the problem that my commit intended to solve.

**Comment by marcushall42** [comment]
Yes, the -u works like a charm.  It seems perfectly happy to accept my "username@domain.name" and allows me to use my preferred name to log in..  Great!
