### ISSUE TITLE
Sleigh: Ghidra class loader not in use

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4893]
**Describe the bug**
Attempting to run sleigh.bat results in a `ClassNotFoundException`

**To Reproduce**
1. Open command prompt with `GHIDRA_INSTALL_DIR/support` in the `PATH`.
2. Run `sleigh.bat`
3. See error

**Expected behavior**
Sleigh compiler should run

**Screenshots**
![image](https://user-images.githubusercontent.com/46897303/212133998-ec37dcc0-dc1f-409c-9986-167749739b06.png)

**Environment (please complete the following information):**
 - Ghidra Version: 10.3_DEV 7971cc303d187cd4a8ed40c7f6035b7c48565a43 *I think*

**Comment by ryanmkurtz** [comment]
Looks like all the `.bat` scripts have this issue.  Until i can push up to GitHub, the manual fix is:

In `launch.bat`, line 132.  At the end of the `for` line, replace `%VMARG_LIST%` with `!VMARG_LIST!`.
