### ISSUE TITLE
Incorrect size for compiler specified datatypes in Project Archive

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#4898]
**Describe the bug**
Creating a structure datatype in a Project Archive (manually or using a script) that contain compiler specific sized datatypes (like a 2 byte `int`) is impossible as when adding say an `int` it is sized as 4 bytes, making it impossible to set something at 2 bytes later.

**To Reproduce**
1. Load a Windows 3.1X into Ghidra and analyse it (lots of issues with pointer sizes etc.)
2. Create a Project Archive
3. Create a structure containing 2 `int` types (in the Project Archive)
4. See the sizes are 4 bytes instead of 2!

**Expected behavior**
All datatypes that can be sized by a compiler spec should have that size in custom archives.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.3
 - Ghidra Version: 10.3
 - Ghidra Origin: locally built (commit a8cdc43bd4c885f5714f6267e6a4b29f05572bf9)

**Comment by mumbel** [comment]
https://github.com/NationalSecurityAgency/ghidra/issues/844#issuecomment-515596598

**Comment by dev747368** [comment]
If you use compiler dependent sizes, this is the problem you are going to run into with data type archives.  (until some enhancements are made to dt archives)

There are other data types that are not compiler dependent (byte, word, dword, qword).  If you use those instead, you can workaround this issue.

**Comment by astrelsky** [comment]
> If you use compiler dependent sizes, this is the problem you are going to run into with data type archives. (until some enhancements are made to dt archives)
> 
> There are other data types that are not compiler dependent (byte, word, dword, qword). If you use those instead, you can workaround this issue.

This isn't exactly an option for any archives containing parsed types or ones pulled from debug info. It's also the reason why I use things I know I'm not supposed to such as `DataType.replaceWith`.

ps: At this point you don't need to worry about me touching things you don't want me to touch... because I've already touched them.

**Comment by dev747368** [comment]
re: debug info.  Yeah, that is an issue.  2fa7a2df72f610fc94f05470d68e51f3b26357eb does address some use cases in DWARF, but it won't catch everything.

**Comment by ghidra1** [comment]
I have addressed this issue within a branch (GP-1633).  It is Still in the review queue.  It will optionally allow a datatype archive to have language/compiler-spec setting and adopt the corresponding data organization.   I will associate this issue# with that internal ticket.

**Comment by Wall-AF** [comment]
@ghidra1 thank you.
