### ISSUE TITLE
Marker legend not updated in inverted color mode (Listing view)

### ISSUE THREAD

**Issue by Xornithologist** [NationalSecurityAgency/ghidra#49]
When in inverted colors mode, the legend for the markers in listing view still shows the old colors

**To Reproduce**
1. Activate inverted color mode
2. Use metal theme

**Expected behavior**
The legend colors should correspond to the listing markers 

**Screenshots**

In these screenshot, we see the info annotations are red, but the legend says they should be blue
![info_on](https://user-images.githubusercontent.com/1145202/53895788-c4f3cb00-4000-11e9-8110-6910b291f95e.png)

With the info (blue) annotation disabled (hard to see, but they're the only  box not checked), only the red markers disappears : 

![info_off](https://user-images.githubusercontent.com/1145202/53895787-c4f3cb00-4000-11e9-8df6-9b4f2b79a377.png)

**Environment:**
 - OS: Ubuntu 18.04
- JDK: openjdk 11.0.1 2018-10-16

**Comment by dragonmacher** [comment]
Inverted colors have been removed.   You can now change most application colors, icons and fonts by editing the current Theme.

Fixed by e657a701416877f7a77b635662d30cfc25f1b5f0
