### ISSUE TITLE
GhidraDev update docs for requirements

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4900]
**Describe the bug**
Could other software requirements get added to `GhidraDev_README` that are more specific for help with getting setup on offline systems.

`gradle` for example.  `README.md` explains the whole gradle setup clearly, but this is missing from `GhidraDev_README`.  `gradle` is also listed as required for exporting which is discussed in that README and big cap/red font in export window.

Not sure what else might be missing, so far just noticed this.

**Environment (please complete the following information):**
 - OS: 22.04
 - Java Version: 17
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official
 - Eclipse: 22-12

**Comment by ryanmkurtz** [comment]
I'll add something about Gradle . Note that I won't be able to put exact version numbers in the document, since the supported Gradle version is dictated by what version of Ghidra you are linking against with GhidraDev.
