### ISSUE TITLE
How to replace binary/hex data in an elf file for analysis?

### ISSUE THREAD

**Issue by rollsch** [NationalSecurityAgency/ghidra#4904]
I have an infineon tricore ELF file. I have a HEX file that has been patched with minor changes and new code appended (eg the hex from the ELF but with minor diffs).

How can I "replace" the hex within the ELF file but not lose all the other metadata in the elf file for processing.

Is there anyway to import a HEX into an existing ELF project and have it override the binary it has already extracted?

Im sure a tool could be written to do this, I'm just trying to  save time and see if there is any existing functionality to do this. I am fairly inexperienced with ghidra.

Thanks

**Comment by emteere** [comment]
You can export an imported ELF if you have only made certain changes to the ELF.

How you overwrite the bytes is up to you.  You can copy and past the bytes into the correct locations.

You may be able to use File->AddToProgram... on the hex file.

You should be able to use File->ExportProgram... and choose ELF.  

If you are using your own build from the main branch, the File->ExportProgram... option has been changes to "Original File" and has an option to export changed bytes or export the bytes exactly as imported.  As long as there are no changes to locations with relocations or important ELF header bytes, the resulting ELF files should be usable.

The export does not build an ELF file.  It is simply exporting the original bytes with any changes made to bytes to the correct locations in the original ELF file.  I think this is what you were looking for.

**Comment by rollsch** [comment]
The problem is mainly I want to turn a hex file into an elf file. There are various ways I could script this, but if ghidra can do it out of the box that would be fantastic.

When I try export it doesn't show elf as an option.

Is there anyway to import a hex, define what is required in the dwarf section then allow it to export as an elf?

**Comment by ryanmkurtz** [comment]
No, Ghidra cannot do this.

**Comment by rollsch** [comment]
Thanks for the reply
