### ISSUE TITLE
Automatic detection for MinGW/GNU toolchain products for PE

### ISSUE THREAD

**Issue by vogelfreiheit** [NationalSecurityAgency/ghidra#4906]
**Is your feature request related to a problem? Please describe.**

PE executables/objects imported will (apparently) invariably have their default language set to the vstudio/MSVC variant. This can easily result in issues like https://github.com/NationalSecurityAgency/ghidra/issues/2208 (demangling fails). It is immediately obvious for someone familiar with Ghidra's processing quirks, but not so much how to "fix" it. Ironically, this could confuse users into thinking Ghidra is less capable than IDA, as the latter usually auto-identifies the PE and selects the right processing target.

The solution is to manually adjust the language to the GCC variant (32/64bit).

**Describe the solution you'd like**
Ideally:

-  Upon detection of DWARF data, Ghidra could verify the existence of a debug_info section.
- The data contained in this section could easily be used to identify MinGW/GCC builds:

```
                             //
                             // .debug_info 
                             // ram:...-ram:...
                             //
                             ..                                    XREF[1]:     ...(*)  
        .... 47 4e 55        ds         "GNU C99 ...

```

Do note that a crafty packer/malicious user could purposefully create a fake section to misdirect analysis (although this will not fool any reverse engineer with some experience). At that point you are likely dealing with other tricks.

There should also be assorted __mingw_ symbols present. (ex. pcinit).

This is a "quality of life" request, if anything.

**Describe alternatives you've considered**
The manual approach works just fine.

**Additional context**
N/A

**Comment by xiaoyinl** [comment]
I think this will be fixed by PR #4514 and #4520.
