### ISSUE TITLE
Nightbuilds ?

### ISSUE THREAD

**Issue by UnrealKaraulov** [NationalSecurityAgency/ghidra#4919]
How to download Nightbuilds ?

**Comment by ryanmkurtz** [comment]
The Ghidra team does not provide nightly builds.

**Comment by UnrealKaraulov** [comment]
@ryanmkurtz thanks for answer, who provide night builds if not ghydra?

**Comment by UnrealKaraulov** [comment]
> Sorry, but I don't know of anyone who provides that.

I know! https://github.com/roblabla/ghidra-ci
