### ISSUE TITLE
Question about Tools

### ISSUE THREAD

**Issue by Gravelbones** [NationalSecurityAgency/ghidra#4923]
I am trying to create a new tool, but I have problems getting only the wanted plugins enabled in the tool.
The same problems seems to be true for the default tools.

Inside the tool file you can do like this
  `<PACKAGE NAME="Ghidra Core">`
     `<INCLUDE CLASS="ghidra.app.plugin.core.console.ConsolePlugin" />`
     `<INCLUDE CLASS="ghidra.app.plugin.core.datamgr.DataTypeManagerPlugin" />`
  `</PACKAGE>`
But when I look into "Configure" in Ghidra, every single plugin in Ghidra Core is enabled. That is not what I want.
If I define the tool from inside Ghidra the result becomes
  `<PACKAGE NAME="Ghidra Core">`
      `<EXCLUDE CLASS="functioncalls.plugin.FunctionCallGraphPlugin" />`
       `<EXCLUDE CLASS="ghidra.app.decompiler.component.hover.DataTypeDecompilerHoverPlugin" />`
       `<EXCLUDE CLASS="ghidra.app.decompiler.component.hover.FunctionSignatureDecompilerHoverPlugin" />`
and the list goes on.
Even that might break if I add yet another plugin to Ghidra Core that plugin would get enabled.
Again something I most likely doesn't want.

For the default tools every single plugin is enabled even though those definitions also have a short list of classes to include.
Am I missing something?

Working on version 10.3 master branch.

**Comment by dragonmacher** [comment]
> Am I missing something?

No, I think you have stated it correctly.

The basic premise of a tool and how it loads plugins is that you pick a package, such as `Ghidra Core` and then everything not marked as excluded will be loaded.   Note:  this only applies to plugins that are marked as stable / released.  If a plugin is experimental, then it needs to be explicitly included.

Admittedly, this causes any new plugins to be added to the tool if they were not previously excluded.   Historically, this has not been a problem and thus is not something we have considered.    You should get the desired result for creating a tool if you do it via the UI (with the caveat that future Ghidra versions may add new plugins).   But, if you try to manipulate the xml to create a new tool, that will be quite difficult.

**Comment by Gravelbones** [comment]
Thanks for the clarification.
