### ISSUE TITLE
Canonical Name Resolution breaks DNS 

### ISSUE THREAD

**Issue by peoplesmeat** [NationalSecurityAgency/ghidra#4924]
**Describe the bug**
When hosting Ghidra server using an a cloud managed (AWS/Google/Azure) instance ghidra will resolve a canonical DNS hostname for whatever hostname is provided. In this case it will resolve a DNS entry of the type ec2-x-x-x-x.REGION.compute.amazonaws.com. So even if a DNS entry is created "my-ghidra-server.example.com", in the ghidra project file, the reverse IP entry is stored. This is because Ghidra uses `host = InetNameLookup.getCanonicalHostName(host);` prior to storing the host name that was entered by the user.

This happens https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/FileSystem/src/main/java/ghidra/framework/client/ClientUtil.java#L111

The problem is encountered when the IP address needs to change, either because the machine was cycled, or moved. Since ghidra is only storing the `getCanonicalHostName` and not the DNS entry the user provided, Ghidra will be unable to connect. 

**To Reproduce**
1. Run ghidra server on a cloud hosting provider
2. Create a DNS entry which maps to the that servers IP
3. Connect using the ghidra client to that shared workspace
4. Not in the project file that the canonical hostname is resolved, not the DNS entrry
5. Restart the cloud instance, update the DNS entry to point to the new IP

**Expected behavior**
Ghidra should respect the hostname the user provides and not try to resolve an additional hostname. In this specific case the DNS entry the user entered should be store

**Environment:**
 - OS: Mac 
 - Java Version: 11.0
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub distro

**Additional context**
This is helpful for ghidra servers which are ephemeral, and do not need to be running continuously.

**Comment by freetink3r** [comment]
This is definitely a bug and should be fixed. What's the point of using DNS to specify the Ghidra server if the Ghidra client is just going to effectively store an IP address?

**Comment by ghidra1** [comment]
Could you please post your `wrapper.app.parameter.*` entries from your `server.conf`.  Feel free to use fake hostname/IP addresses in place of real entries, if any.

**Comment by ghidra1** [comment]
A shared project should retain the original hostname/address as specified by the user during project creation within the `*.rep/project.prp` file.

**Comment by dtshepherd** [comment]
@ghidra1 I work with @peoplesmeat, here's a copy of the server.conf.  There are environment variables that are replaced during startup of the container:
```

#********************************************************************
# Service Wrapper Properties
#
# NOTE! The following properties contained within this file may be
# modified by the ghidraSvr script:
#   - Wrapper.fork_hack
#********************************************************************

# Initial Working Directory (i.e., absolute installation directory path)
wrapper.working.dir=${ghidra_home}

# Mac OS X launchd plist directory
wrapper.launchd.dir=/Library/LaunchDaemons

# Java Application
wrapper.java.command=${java}

# Establish default permissions for generated files
wrapper.java.umask=027

# Java Classpath
include=${classpath_frag}

# Java Library Path (location of native authentication support libraries)
wrapper.java.library.path.1=${os_dir}

# Java Additional Parameters
wrapper.java.additional.1=-Djava.net.preferIPv4Stack=true

# Establishes a minimum number of rolling server.log backups to be maintained
wrapper.java.additional.2=-DApplicationRollingFileAppender.maxBackupIndex=10

# Ensure that classpath_frag is defined for service startup
wrapper.java.additional.3=-Dclasspath_frag=${classpath_frag}

# A suitable cacerts file must be installed when using PKI authentication
#wrapper.java.additional.4=-Dghidra.cacerts=./Ghidra/cacerts

# If Ghidra clients must authenticate the server, the server will need to install
# a server key/certificate in a secure location (e.g., /etc/pki/...)
# and specify the location and password via the properties below.
# Be sure to properly set permissions on the Ghidra installation and this file
# if using these settings.
#wrapper.java.additional.5=-Dghidra.keystore=
#wrapper.java.additional.6=-Dghidra.password=

# Temporary Directory Setting - uncomment the following setting to override the Java default.
# This may be necessary on certain Windows platforms when installing as a service.
#wrapper.java.additional.7=-Djava.io.tmpdir=C:\\Windows\\Temp

# Enable/Disable use of compression for DataBuffer serialization and Block Streams
wrapper.java.additional.8=-Ddb.buffers.DataBuffer.compressedOutput=true

# Uncomment to enable remote debug support
#wrapper.java.additional.9=-Xdebug
#wrapper.java.additional.10=-Xnoagent
#wrapper.java.additional.11=-Djava.compiler=NONE
#wrapper.java.additional.12=-Xrunjdwp:transport=dt_socket\,server=y\,suspend=n\,address=*:18200
#wrapper.startup.timeout=0
#wrapper.ping.timeout=0

# Optional debug enablement instead of using the wrapper.java.additional arguments above
# This will cause application to start in a suspended state
#wrapper.java.debug.port=18200

# Uncomment to enable remote use of jvisualvm for profiling
# See JMX documentation for more information: http://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html
#wrapper.java.additional.13=-Dcom.sun.management.jmxremote.port=9010
#wrapper.java.additional.14=-Dcom.sun.management.jmxremote.local.only=false
#wrapper.java.additional.15=-Dcom.sun.management.jmxremote.authenticate=false
#wrapper.java.additional.16=-Dcom.sun.management.jmxremote.ssl=false

# Do not use process fork - use exec instead (MUST BE ENABLED FOR Mac OS X)
#  -Should be "true" for Mac OS X and Linux
#  -Should be commented-out or "false" for Windows
#  -Should remain commented-out in source control and initial distribution
#wrapper.fork_hack=true

# Pipe server output to console/log
#wrapper.console.pipestreams=true

# Monitor for Deadlock
wrapper.java.monitor.deadlock = true

# Main server application class
wrapper.java.app.mainclass=ghidra.server.remote.GhidraServer

# Initial Java Heap Size (in MB)
wrapper.java.initmemory=396

# Maximum Java Heap Size (in MB)
# See svrREADME.txt file for advice (Server Memory Considerations)
wrapper.java.maxmemory=768

# Specify the directory used to store repositories. This directory must be dedicated to this
# Ghidra Server instance and may not contain files or folders not produced by the
# Ghidra Server or its administrative scripts.  Relative paths originate from the
# Ghidra installation directory, although an absolute path is preferred if not using default.
# This variable is also used by the svrAdmin script.

ghidra.repositories.dir=${GHIDRA_REPOS_PATH}

# Ghidra server startup parameters.
#
# Command line parameters: (Add command line parameters as needed and renumber each starting from .1)
#   [-ip###.###.###.###] [-p#] [-a#] [-anonymous] [-ssh] [-d<ntDomain>] [-e<days>] [-u] [-n] <repositories_path>
#
#   -ip###.###.###.### : ip address to bound to (by default, uses IP address bound to hostname)
#   -p# : base TCP port to be used (default: 13100)
#   -a# : an optional authentication mode where # is a value 0 or 2
#         0 - Private user password
#         1 - NT Login Password (domain authentication requires -d option)
#         2 - PKI Authentication
#         3 - NT Login Password (domain authentication requires -d option) with optional private user password support
#   -anonymous : enables anonymous repository access (see svrREADME.html for details)
#   -ssh : enables SSH authentication for headless clients
#   -d<ntDomain> : specifies NT Domain to be used for authentication (-a1 and -a3 mode only))
#   -e<days> : specifies default password expiration time in days (-a0 mode only, default is 1-day)
#   -u   : enable users to be prompted for user ID (does not apply to -a2 PKI mode)
#   -n   : enable reverse name lookup for IP addresses when logging (requires proper configuration
#          of reverse lookup by your DNS server)
#   ${ghidra.repositories.dir} : config variable (defined above) which identifies the directory
#                       used to store repositories.  Use of this variable to define the
#                       repositories directory must be retained.
wrapper.app.parameter.1=-a0
wrapper.app.parameter.2=-u
wrapper.app.parameter.3=-ip${GHIDRA_PUBLIC_HOSTNAME}
wrapper.app.parameter.4=${ghidra.repositories.dir}

# Establish server process owner
# This should only be used when installing as a service using a nologin
# local user account.  Establishing a suitable account is left as a
# system administration task.  NOTE: the use of this feature is not
# yet supported for Windows installations.
#wrapper.app.account=ghidra

#********************************************************************
# Service Wrapper Logging Properties
#********************************************************************
# Format of output for the console.  (See docs for formats)
wrapper.console.format=PM

# Log Level for console output.  (use INFO to see Ghidra Server activity)
wrapper.console.loglevel=INFO

# Provide additional wrapper debug logging info
#wrapper.debug=true

# Log file to use for wrapper output logging.
wrapper.logfile=wrapper.log

# Format of output for the log file.  (See docs for formats)
wrapper.logfile.format=LPTM

# Log Level for wrapper.log file output.  (See docs for log levels)
wrapper.logfile.loglevel=INFO

# Maximum size that the log file will be allowed to grow to before
#  the log is rolled. Size is specified in bytes.  The default value
#  of 0, disables log rolling.  May abbreviate with the 'k' (kb) or
#  'm' (mb) suffix.  For example: 10m = 10 megabytes.
wrapper.logfile.maxsize=10m

# Maximum number of rolled log files which will be allowed before old
#  files are deleted.  The default value of 0 implies no limit.
wrapper.logfile.maxfiles=10

#********************************************************************
# Service Wrapper Windows Properties
#********************************************************************
# Title to use when running as a console
wrapper.console.title=Ghidra Server

#********************************************************************
# Service Wrapper Windows NT/2000/XP Service Properties
#********************************************************************
# WARNING - Do not modify any of these properties when an application
#  using this configuration file has been installed as a service.
#  Please uninstall the service before modifying this section.  The
#  service can then be reinstalled.

# Name of the service
wrapper.ntservice.name=ghidraSvr

# Display name of the service
wrapper.ntservice.displayname=Ghidra Server

# Description of the service
wrapper.ntservice.description=Repository server for Ghidra data files.

# Service dependencies.  Add dependencies as needed starting from 1
wrapper.ntservice.dependency.1=

# Mode in which the service is installed.
wrapper.ntservice.starttype=AUTO_START

# Linux service daemon priority for Ghidra Server (start/stop)
# It is important that the network interface has started and any file-system
# dependencies are mounted prior to the Ghidra Server starting.
# NOTE: uninstall the Ghidra Server service using svrUninstall script before changing
# the property wrapper.daemon.update_rc or wrapper.daemon.run_level_dir property.
wrapper.daemon.update_rc= 98 05

# Linux service daemon link directories
wrapper.daemon.run_level_dir=/etc/rcX.d

# Allow the service to interact with the desktop.
wrapper.ntservice.interactive=false

# Restart failed service after 1 minute delay
wrapper.ntservice.failure_actions.actions=RESTART
wrapper.ntservice.failure_actions.actions_delay=60000
```

**Comment by peoplesmeat** [comment]
Ghidra is using the entry from `*.rep/project.prp` 

The issue however is that when creating a new Shared Project Ghidra does not store the value the user enters in "Server Name" Instead ghidra will resolve that hostname, and then do a reverse lookup on that IP, then stores that hostname value in `*.rep/project.prp`.

**Comment by peoplesmeat** [comment]
The root issue is this code in ClientUtil.java
```
		host = host.trim().toLowerCase();
		try {
			host = InetNameLookup.getCanonicalHostName(host);
		}
		catch (UnknownHostException e) {
			Msg.warn(ClientUtil.class, "Failed to resolve hostname for " + host);
		}```

This should be changed to 
```		host = host.trim().toLowerCase();
		try {
		    InetNameLookup.getCanonicalHostName(host);
		}
		catch (UnknownHostException e) {
			Msg.warn(ClientUtil.class, "Failed to resolve hostname for " + host);
		}

**Comment by dtshepherd** [comment]
@ryanmkurtz @ghidra1 As an alternate solution to cloud canonical naming issues, PR #3396 enables SNI support to the Ghidra client.  Then we can use AWS NLBs in front of Ghidra Server that allow us to setup custom Reverse DNS records.  That PR never gained any traction, but I figured I'd make a shameless plug :)

**Comment by ghidra1** [comment]
> @ryanmkurtz @ghidra1 As an alternate solution to cloud canonical naming issues, PR #3396 enables SNI support to the Ghidra client. Then we can use AWS NLBs in front of Ghidra Server that allow us to setup custom Reverse DNS records. That PR never gained any traction, but I figured I'd make a shameless plug :)

@dtshepherd, Sorry, this is the first I have seen that PR - it must have slipped under the radar - can't seem to keep up :) I am unfamiliar with SNI so I will need to consider that PR.  

The canonical hostname use gets entangled in how we normalize server connection references to ensure proper connection re-use.  I suspect this needs to be re-worked to possibly rely on the IP address as a key and not the canonical hostname.

**Comment by ghidra1** [comment]
Any thoughts on how to affectively cache/idenfity a common/shared server connection.  I am starting to think this cannot be reliably done and must be based entirely on the original hostname/address specified.  Any mutation (i.e., IPAddr->Name or Name->IPAddr) can result in lost uniqueness.  

For instance, if a common canonical form of `127.0.0.1` is NOT treated the same as 'localhost' the use of each would require independent authentication (e.g., password prompt) and server connection.   In addition, use in Ghidra URL form would be treated as unique even though they refer to the same shared repo file (e.g., `ghidra://127.0.0.1/repo/file` and `ghidra://localhost/repo/file`).

**Comment by dtshepherd** [comment]
I'm confused why it matters if localhost is treated the same from 127.0.0.1.   A typical client will use one or the other, and not be flipping their use every time they connect.  Then, Ghidra client stores whatever they use.  Is the canonical name used for anything else besides the connection?

Alternatively, the server could return a UUID for unique identification.  Admittedly, I'm not an expect on RMI client/server interaction and I'm not sure if there's a way to return that without authenticating first.

Ultimately, the hostname used to connect shouldn't be mutated since in a cloud environment, the IP address is dynamic.  IP address may change daily, so the Ghidra client should always resolve the hostname IP when connecting to the server backend.

**Comment by dtshepherd** [comment]
Also, I just reviewed @peoplesmeat's updated PR #4928, I think his rework is a good compromise to fix the issue.  This allows reconnection using the original hostname provided by the user.

**Comment by dtshepherd** [comment]
So I spent a little more time reviewing the RMI connection handling. I think in the worst case, the RMI connection caching has to happen for each unique hostname or IP that maps to the same server.  But in practice, a user will use the same hostname in a Ghidra URL on the command-line or in their connection to the server in the GUI will not be changing hostnames during a given session.

If they change the URL or host they connect to, the connection cache (and authentication) would need to be refreshed.  That shouldn't be a common occurrence and everything still maps back to the same project and repo on the file system despite different host/IP.

**Comment by ghidra1** [comment]
@dtshepherd You are probably correct and I may be over-thinking things.  The worst that would happen is that the user would be required to re-authenticate and maintain multiple server connections if they are inconsistent in server hostname/FQDN use.  The server UUID approach could be used but would require a change to the server API which I prefer to avoid if possible.

**Comment by peoplesmeat** [comment]
I tried to balance the concerns about the host changing in this PR. This PR should behave identically to the current behaviour, with the exception that the user entered value is stored in the prp file. The caching mechanism will still refer to the canonicalized value.

**Comment by ghidra1** [comment]
@peoplesmeat The connection caching, as currently implemented, seems problematic for SNI Proxy case.   I am leaning towards using the hostname as specified by the user for any connection caching as well as the `project.prp` file as you had done originally.  This should solve any cache issue for the SNI Proxy case.

I am also looking into how best to present the server details to the user during authentication.   As well as server authentication concerns.  We currently have rather relaxed server validation on the client-side by default which assumes most server installations are OK with using a self-signed certificate.  The server was never really intended to accept connections from the internet and was primarly geared for use in a protected workgroup setting with user authentication only.   Performance considerations are also a factor for reasonable Ghidra Server deployments and use.

**Comment by ghidra1** [comment]
Desired behavior has been added to master branch and should get pushed next week.  Thanks for the PR but we chose to work in along with some other changes.

**Comment by dtshepherd** [comment]
Thanks! That's great!
