### ISSUE TITLE
Ghidra Server and CIS

### ISSUE THREAD

**Issue by t0ta11ed** [NationalSecurityAgency/ghidra#4925]
Is there any guidance or info on how to get Ghidra Server to properly run on a CIS-hardened server? 

By design there are some restrictions, particularly over the /tmp directory. I'm unable to get the parameters -Dwrapper.tmp.path or -Djna_tmpdir to stop using it. I've tried adding these to server.conf but this doesn't seem to change. The server won't start because of issues with the directory: 

`Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/jna17948382034945794661.tmp: /tmp/jna17948382034945794661.tmp: failed to map segment from shared object`

Pulling my hair out. Ideally, I shouldn't have to ditch CIS but not out of the question at this point.

**Comment by dev747368** [comment]
Could you describe how you put the params in server.conf?

I haven't tried anything yet, but at first glance it should be:

```wrapper.java.additional.10=-Djna.tmpdir=/other/path```

**Comment by t0ta11ed** [comment]
That's what I am using, although I used the next logical number in the ordering. Does it need to be .10? 

wrapper.java.additional.7=-Dwrapper.tmp.path
wrapper.java.additional.8=-Djna.tmpdir (Note I've also tried Djna_tmpdir)

Still get this when starting Server;

From wrapper.log; Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/jna11201110639933190708.tmp: /tmp/jna11201110639933190708.tmp: failed to map segment from shared object

Screen showing tmp paths haven't changed
![image](https://user-images.githubusercontent.com/30156914/214858647-69f5015c-1697-4bd5-b5c1-ca7d66dd6312.png)

**Comment by ghidra1** [comment]
It will be neccessary to get the initial wrapper.jar launch to have a similar settings (i.e., the process that reads server.conf).  This may require significant modification of the `ghidraSvr` scripts.  Since we do not use the standard YAJSW scripts it may be time for an overhall of our `ghidraSvr` script.  You can find the standard scripts within a clean unpack of the YAJSW distribution jar found in `Ghidra/Features/GhidraServer/data` to get an idea how they recommend launching.

I will open an internal ticket to address this.

**Comment by fenugrec** [comment]
Out of my league here, but what about a naive ` export _JAVA_OPTIONS=-Djava.io.tmpdir=/tmpdir_with_exec` or `java -Djava.io.tmpdir=/tmpdir_with_exec <ghidra invocation>`  ? I've been using that for a few applications that don't like when /tmp is noexec

**Comment by t0ta11ed** [comment]
> Out of my league here, but what about a naive ` export _JAVA_OPTIONS=-Djava.io.tmpdir=/tmpdir_with_exec` or `java -Djava.io.tmpdir=/tmpdir_with_exec <ghidra invocation>` ? I've been using that for a few applications that don't like when /tmp is noexec

I do have this set in server.conf and it works but only after the server is started from what I understand. It sounds like the wrapper launcher itself uses /tmp before we read the .conf file and that's an issue. 

Is there a way to tell Java not to use /tmp at all to avoid this? I am not a Java guy.

**Comment by ghidra1** [comment]
Options have to be forced onto java wrapper execution (see ghidraSvr script).  We have established an internal ticket to allow the tmp directory to be properly configured.

**Comment by t0ta11ed** [comment]
I'm not sure what changes are required so the only solution that currently works is to export _JAVA_OPTIONS, but this doesn't persist after a reboot. I can live with this assuming the fix is soon.

**Comment by ryanmkurtz** [comment]
Add the JVM command line arg to these calls to the wrapper in `server/ghidraSvr`:

`"${JAVA_CMD}" -jar "${WRAPPER_HOME}/wrapper.jar"`

**Comment by t0ta11ed** [comment]
After some trial and error, I am able to add these paths but they seem to get overridden: 

![image](https://user-images.githubusercontent.com/30156914/215569043-a31dea43-bfd2-456f-8344-aeb1473b910c.png)

**Comment by ryanmkurtz** [comment]
I'm implementing the fix for this now.  I opened a [bug with yajsw](https://sourceforge.net/p/yajsw/bugs/197/) because their documention references `jna.tmpdir` when it should be `jna_tmpdir`.

**Comment by t0ta11ed** [comment]
> I'm implementing the fix for this now. I opened a [bug with yajsw](https://sourceforge.net/p/yajsw/bugs/197/) because their documention references `jna.tmpdir` when it should be `jna_tmpdir`.

Thanks for the update. Is this in the 10.2.3 release? I didn't see anything in change notes.

**Comment by ryanmkurtz** [comment]
No, it didn't make it into 10.2.3.

**Comment by ryanmkurtz** [comment]
@t0ta11ed if possible, can you try out the master branch with the new `WRAPPER_TMPDIR` variable in `ghidraSvr`?  It works as far as I can tell but I didn't test on a system with a restricted `/tmp` dir, so i can't be 100% sure a rogue file isn't getting created there behind the scenes.

**Comment by t0ta11ed** [comment]
> @t0ta11ed if possible, can you try out the master branch with the new `WRAPPER_TMPDIR` variable in `ghidraSvr`? It works as far as I can tell but I didn't test on a system with a restricted `/tmp` dir, so i can't be 100% sure a rogue file isn't getting created there behind the scenes.

Happy to give that a whirl but not 100% sure how I would do that. I normally grab your release file. Would I be compiling it from the branch myself? Afaik, all you have to do is set /tmp to NOEXEC to recreate, which is what CIS controls are doing.
