### ISSUE TITLE
Problems with emulating PMOVZXBW (x86_64)

### ISSUE THREAD

**Issue by NeoZ16** [NationalSecurityAgency/ghidra#4926]
Binary is x86_64, Ghidra Version is the 10.2.2_PUBLIC release.

I tried emulating a x86_64 binary and it crashed at the instruction `66 42 0f  38 30 24 09 PMOVZXBW   XMM4,qword ptr [RCX + R9*0x1] `.
The first exception I got was `Unimplemented CALLOTHER pcodeop (pmovzxbw)`.
I took a look in the `ia.sinc`  file and found this:
```
define pcodeop pmovzxbw;
:PMOVZXBW XmmReg, m64      is vexMode=0 & $(PRE_66) & byte=0x0F; byte=0x38; byte=0x30; XmmReg ... & m64 { XmmReg = pmovzxbw(XmmReg, m64); }
:PMOVZXBW XmmReg1, XmmReg2 is vexMode=0 & $(PRE_66) & byte=0x0F; byte=0x38; byte=0x30; xmmmod=3 & XmmReg1 & XmmReg2 { XmmReg1 = pmovzxbw(XmmReg1, XmmReg2); }
```
I assume this is a stub and pmovzxbw is not really implemented.
Because of this I tried to create an implementation based on [https://www.felixcloutier.com/x86/pmovzx](https://www.felixcloutier.com/x86/pmovzx).

It looks like this:
```
define pcodeop pmovzxbw;
:PMOVZXBW XmmReg, m64      is vexMode=0 & $(PRE_66) & byte=0x0F; byte=0x38; byte=0x30; XmmReg ... & m64 {
    XmmReg[0,16] = zext(m64[0,8]);
    XmmReg[16,16] = zext(m64[8,8]);
    XmmReg[32,16] = zext(m64[16,8]);
    XmmReg[48,16] = zext(m64[24,8]);
    XmmReg[64,16] = zext(m64[32,8]);
    XmmReg[80,16] = zext(m64[40,8]);
    XmmReg[96,16] = zext(m64[48,8]);
    XmmReg[112,16] = zext(m64[56,8]);
}
:PMOVZXBW XmmReg1, XmmReg2 is vexMode=0 & $(PRE_66) & byte=0x0F; byte=0x38; byte=0x30; xmmmod=3 & XmmReg1 & XmmReg2 {
    XmmReg1[0,16] = zext(XmmReg2[0,8]);
    XmmReg1[16,16] = zext(XmmReg2[8,8]);
    XmmReg1[32,16] = zext(XmmReg2[16,8]);
    XmmReg1[48,16] = zext(XmmReg2[24,8]);
    XmmReg1[64,16] = zext(XmmReg2[32,8]);
    XmmReg1[80,16] = zext(XmmReg2[40,8]);
    XmmReg1[96,16] = zext(XmmReg2[48,8]);
    XmmReg1[112,16] = zext(XmmReg2[56,8]);
}
```

I tried this implementation with a small example and it seems to work for `66 0f 38 30 0c 25 00 20 40 00 PMOVZXBW   XMM1,qword ptr [v1]` .
However for an instruction that calculates the address where the data comes from (`66 41 0f 38 30 89 00 20 40 00 PMOVZXBW   XMM1,qword ptr [R9 + v1]`), it crashes with the exception `Index 1 out of bounds for length 1`.

I put together a small example and found the exception happens in [UniqueMemoryBank.java  setChunk Line135](https://github.com/NationalSecurityAgency/ghidra/blob/da94eb86bd2b89c8b0ab9bd89e9f0dc5a3157055/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/pcode/memstate/UniqueMemoryBank.java#L135).
It seems to have something to do with the alignment of the memory.
I don't really have an idea what the problem here is and would be really thankful if anyone could help.

Example assembler code:
```
;nasm -f elf64 -g assembler.asm && ld -g assembler.o && ./a.out

global _start

section .data
    align 16
    v1: dw 1, 2, 3, 4, 5, 6, 7, 8

section .bss

section .text
    _start:
    pmovzxbw xmm1, [v1]
    pmovzxbw xmm1, [v1 + R9 * 1]
    pabsb xmm1, xmm2
                            ; Call exit(3) syscall
                            ;       void exit(int status)
                            ;
    mov     ebx, 0          ; Arg one: the status
    mov     eax, 1          ; Syscall number:
    int     0x80
```

**Comment by nsadeveloper789** [comment]
@NeoZ16 It looks like you're trying this using a script with the old emulator. Please try it in the new one. You can do this from a script or the UI. From a script, I think you'll find the examples in https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Debug/Debugger/ghidra_scripts helpful.

Alternatively, from the UI, do the following:
1. Open your program in the Debugger.
2. In the static listing, right-click on the first instruction to emulate and click "Emulate Program in new Trace"
3. In the "Threads" window, click the step emulator forward button.

If you want to step one p-code op at a time, then steps 1 and 2 remain the same:
1. "
2. "
3. In the menus: File -> Configure. Click the Debugger category.
4. Enable the DebuggerPcodeStepperPlugin. A "P-Code Stepper" window will appear. Confirm/close all the config dialogs.
5. In the "P-Code Stepper" window, click the step p-code forward button.

Let us know if the issue persists here.

To "terminate" the emulation: You should see a "Emulate [program]" tab in the "Threads" window. Right-click that tab and click "Close."

**Comment by astrelsky** [comment]
@nsadeveloper789 what if debugging it is not an option?

**Comment by d-millar** [comment]
@astrelsky Probably not obvious from @nsadeveloper789's comment, but you don't actually have to debug the program to emulate it - you just have to open it in the Debugger.

**Comment by astrelsky** [comment]
> @astrelsky Probably not obvious from @nsadeveloper789's comment, but you don't actually have to debug the program to emulate it - you just have to open it in the Debugger.

I did pick up on that but decided to ask it anyway because it's not very obvious. I probably understand why it's in the debugger, but if I have something I don't want to accidentally detonate in my current environment, then I'm not opening the debugger.

Note that I was not aware that the emulator in the debugger was unrelated to debugging. I thought it was for emulating portions of a previous debugging session which you had traces for.

**Comment by d-millar** [comment]
Right, so it does both.  You can stop in the middle of a debugging session and emulate forward/backward using the existing state, you can load a trace and emulate from that, or you can start from nothing and emulate a static program generating state where you need it.

Your point is interesting, however - I can see wanting to set the debugger into a state where you CANNOT actually execute the real code on the processor.  Am adding a ticket...

**Comment by nsadeveloper789** [comment]
How thorough should we be here? My thought is to just disable/remove the "Debug" button in the toolbar. Would that suffice, or would you want to remove all things related to connecting to a real debugger?

**Comment by astrelsky** [comment]
> How thorough should we be here? My thought is to just disable/remove the "Debug" button in the toolbar. Would that suffice, or would you want to remove all things related to connecting to a real debugger?
> 
> This could be implemented as a separate tool dedicated to Emulation, or we could add a safety toggle of some sort to the Debugger. Thoughts?

Well, I think just disabling any sort of launch functionality and knowing I can protect me from myself would be sufficient. It could also just be me, being me, as I have also worried about accidentally detonating something locally when I meant to run it remotely in a vm.

However, I do think Emulation would warrant it's own tool. It would make it easier to find and help give it its chance to shine. I'm assuming most of the Debugger ui would be reused for this but with some things removed.
That's just my 2 cents. I haven't put much thought into just and this is mostly nonsensical rambling at this point 😅

**Comment by NeoZ16** [comment]
@nsadeveloper789 
Thanks, it seems like that was the problem.
I don't know if I overlooked something, but for me it was not really clear that EmulatorHelper and the underlying emulator should not be used anymore/are deprecated.

However one thing I can't figure out with the new emulator is how to create breakpoints.
I'm using the addBreakpoint Method, but there is now way to create an unconditional breakpoint.
I tired putting "1 = 1" or "TRUE" as the condition, but that just crashes the emulator.

**Comment by nsadeveloper789** [comment]
@NeoZ16 Use `1:1` as the condition. (The constant 1, encoded in 1 byte)

The EmulatorHelper is not "officially" deprecated, yet. That said, it's not receiving a lot of attention as we move our efforts toward the new one. We still use the old one for testing our processor models' semantics. It probably won't be deprecated until those are ported, which is a bit of an effort.

@astrelsky Thanks for the input. I'm currently leaning toward the new tool, as well. There's a handful of plugins that manage launching targets, that (once I sort of the dependency graph) I could just remove. I'll post a separate issue for this.

**Comment by nsadeveloper789** [comment]
@NeoZ16 I'm going to assume the `1:1` thing has resolved your issue. Feel free to re-open or create a new issue regarding breakpoints, if not.
