### ISSUE TITLE
Using multiple source input files in version tracking

### ISSUE THREAD

**Issue by rollsch** [NationalSecurityAgency/ghidra#4935]
I have the following files

Rev 1 elf with full debug info
Rev 2 Hex with nothing
Rev ... Hex with nothing
Rev 5 Hex with nothing
Rev 6 elf with full debug info
Rev 7 hex with nothing
Another 10 versions with hex only

I want to function and data match all the hex files. Currently I can do them one by one, however eg rev 7 will generally be a super set of rev 1 and rev 6 but with also some code missing  due to ifdefd out compile flags. (eg chunks of code added and removed to some of the methods,  also some brand new code) 

Rev 7 would be easy to annotate under version control if I could somehow use two input source files. 

Is there any way to make a version tracking project with two (or more) input files and then allow duplicate matches and pick the best one. As some things will match identically from rev 1 and some will match identically from rev 6, so you could easily do both them take the best confidence rating. 

Other than writing a custom plugin I couldn't think of any way to do this. 

I could do two version sessions, only take full 1 to 1 matches from each, then do another two version sessions for non 1:1 matches but I wouldn't have any really way to contrast the two to see which is giving better results.

Thoughts?

**Comment by ghidra007** [comment]
Unfortunately the Version Tracker is only meant to do matching between two programs. I think your idea to do two VT sessions and find all 1:1 first matches is your best option.  Hopefully you won't have many non 1:1's to deal with. You could always duplicate your destination file after you run the initial matches and have two VT sessions up side by side to compare. That would be a lot of open windows and probably very difficult to keep track of but you could at least compare them that way.
