### ISSUE TITLE
Bad instruction for `mov rax,[gs:0x30]`

### ISSUE THREAD

**Issue by hackedd** [NationalSecurityAgency/ghidra#4942]
**Describe the bug**
Analyzing a binary with `mov rax,[gs:0x30]` instruction (`65 67 48 a1 30 00 00 00`) results in a "Bad instruction" error.

**To Reproduce**
1. Analyze a program using this instruction
4. See bad instruction error

**Expected behavior**
I expected this instruction to be decoded. For example, from `objdump`:

```
0000000000401000 <.text>:
  401000:	65 67 a1 30 00 00 00 	addr32 mov eax,gs:0x30
  401007:	65 67 48 a1 30 00 00 	addr32 mov rax,gs:0x30
  40100e:	00 
  40100f:	65 67 a1 ff ff ff ff 	addr32 mov eax,gs:0xffffffff
  401016:	65 67 48 a1 ff ff ff 	addr32 mov rax,gs:0xffffffff
  40101d:	ff 
```

**Screenshots**
![Screenshot from 2023-01-31 10-46-00](https://user-images.githubusercontent.com/195070/215725409-44b17a1b-75c4-42d9-8b39-02fc8f1c3fb4.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Java Version: 18.0.2-ea
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub distro

**Comment by GhidorahRex** [comment]
Looks like we don't have a constructor for x86-64 32-bit memory access here. There might be other instructions this could be impacting.
