### ISSUE TITLE
Version Tracking Data Reference Match Correlator doesn't produce matches

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4950]
**Describe the bug**
Running the data reference match correlator doesn't produce matches for references from well defined data.

**To Reproduce**
1. Compile the sample with `gcc -g3 -O0 -Wall -Werror main.c -o main`
2. Compile the sample again with `gcc -Wall -Werror main.c -o main2` and then `strip --strip-unneeded main2 -o main2_stripped`
3. Load and run analyses on `main` and `main2_stripped`
4. Manually locate and label `main`, `getA`, `a_instance`, `getB` and `b_instance`.
5. Start a version tracking session and change the apply options to always replace data.
6. Run the "Exact Symbol Name Match" correlator.
7. Apply the matches for  `main`, `getA`, `a_instance`, `getB` and `b_instance`.
8. Verify that the markup has been properly applied to the destination program (sometimes it is not).
9. Filter out all algorithms except "Data Reference Match".
10. Run the "Data Reference Match" correlator.
11. See no matches.

**Expected behavior**
The results of the final "Data Reference Match" correlator should produce matches to `vtableA` and `vtableB`. After those matches have been accepted and applied, running the correlator again should then produce matches to `a_destructor`, `a_destuctor_in_charge`,  `a_say_hi`, `a_say_bye`, `b_destructor`, `b_destuctor_in_charge`,  `b_say_hi` and finally `b_say_bye`.

**Attachments**
[main.c.txt](https://github.com/NationalSecurityAgency/ghidra/files/10557571/main.c.txt)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22621.1194]
 - Java Version: 17.0.5
 - Ghidra Version: 10.3_DEV (this has been a problem since the beginning of time though)
 - Ghidra Origin: locally built

**Additional context**
There is much room for improvement and Version Tracking could really use some TLC.

**Comment by dragonmacher** [comment]
> There is much room for improvement and Version Tracking could really use some TLC.

Facts.  The tool has effectively been frozen in time, still full of promise and hope.

**Comment by ghidra007** [comment]
Have you tweaked the initial options for the data reference correlator to see if that changes anything?

**Comment by ghidra007** [comment]
I just tried it and I got two matches back from the data reference correlator - getA and getB. Have you checked your match filter to make sure you are seeing all matches and not just unaccepted ones? Since you already accepted those matches by symbol, you would not see them again if you have already accepted matches filtered out.

**Comment by ghidra007** [comment]
Yes the description: "Matches functions by the accepted data matches they have in common." does imply that it is a function correlator not a data correlator and that it is finding function matches based on known data references.  There currently isn't a data correlator that uses known function references to correlate data.

**Comment by astrelsky** [comment]
I may poke around with this depending on how complicated it is to implement a correlator. From a quick glance at the existing ones it doesn't look like it would be too difficult to add one.

**Comment by astrelsky** [comment]
> I may poke around with this depending on how complicated it is to implement a correlator. From a quick glance at the existing ones it doesn't look like it would be too difficult to add one.

Nevermind... package protected constructors

**Comment by astrelsky** [comment]
> > I may poke around with this depending on how complicated it is to implement a correlator. From a quick glance at the existing ones it doesn't look like it would be too difficult to add one.
> 
> Nevermind... package protected constructors

@ghidra007 any thoughts on making the package visibility of the correlator classes and methods public/protected? I don't see any reason for them to have package visibility and it would be nice to have plugins that provide correlators.

**Comment by dragonmacher** [comment]
I see no reason why these can't be public.

**Comment by astrelsky** [comment]
> I see no reason why these can't be public.

Well it turns out that they won't fit my use case anyway. The package visible ones were for `VTAbstractReferenceProgramCorrelator` and apparently a reference is only ever from a function and constant pointers don't exist in memory :p.
