### ISSUE TITLE
GhidraDev default module plugin fails to build out of the box

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4962]
I must have missed something, but these were the steps I have taken (roughly following https://voidstarsec.com/blog/ghidra-dev-environment):

```
gradle -I gradle/support/fetchDependencies.gradle init
gradle prepdev
gradle eclipse -PeclipsePDE
gradle buildGhidra
```

install the latest versions of eclipse, CDT, PyDev, and PDE

``File > Import > General > Existing Projects into Workspace``
Add both ``EclipseGhidraDevFeature`` and ``EclipseGhidraDevPlugin``
Add both ``_LaunchSupport`` and ``Framework Utility`` because Eclipse refuses to buiid without them

Eclipse complains about ``IPythonNature.JYTHON_VERSION_2_7`` in ``PyDevUtilsInternal.java`` which I replaced with "jython 2.7"

``File > Export > Plug-in Development > Deployable Features``
``Help > Install New Software``
Install ``ghidraDev``

``GhidraDev->New Ghidra Module Project``
Select just Plugin in the module templates. Link the ghidra build created by the ``gradle buildGhidra`` command run at the start.
``GhidraDev->Export->Ghidra Module Extension``

The build fails with errors like:
``Cannot find expected stylesheet: .../MyFirstGhidraPlugin/Framework/Help/src/main/resources/help/shared/DefaultStyle.css``

Copying the Framework folder from ghidra results in another error:
```
Exception in thread "main" ghidra.util.exception.AssertException: Errors parsing HTML file: help.html
Incorrect stylesheet defined - none match .../MyFirstGhidraPlugin/Framework/Help/src/main/resources/help/shared/DefaultStyle.css in file .../MyFirstGhidraPlugin/src/main/help/help/topics/myfirstghidraplugin/help.html
	Discovered stylesheets: [.../MyFirstGhidraPlugin/Framework/Help/src/main/resources/help/shared/Frontpage.css]
```
I'm inclined to believe that I must have missed something obvious in the documentation (or the template is not meant to be buildable?), so any help/advice would be most welcome - is there some command I should have run to get all the necessary files?

(For the record, deleting src/main/help skips building help and thus all these errors, so not the biggest deal)

**Comment by ryanmkurtz** [comment]
You didn't make any alterations to the new project that the wizard created for you?  It just failed to export as a new extension out of the box?

**Comment by dragonmacher** [comment]
We recently changed the help page stylesheet name.   I see you are still using the old style:

`[.../MyFirstGhidraPlugin/Framework/Help/src/main/resources/help/shared/Frontpage.css]`

The correct file should now be:

`/Ghidra/Framework/Help/src/main/resources/help/shared/DefaultStyle.css`

The error message implies that you your `Help` module is not up-to-date with the build system.

**Comment by ryanmkurtz** [comment]
Using a build of the current master (394c544544da619d63e375a9f9718df44fdd2113), i was not able to reproduce this.  I built a new GhidraDev Eclipse plugin the same way you described, installed it, created a new Module project linked against my built Ghidra, and then exported the module.  I used a local Gradle 7.6 to do the export.  I didn't have PyDev or CDT installed, but I don't those things are related to your Help error.

**Comment by sad-dev** [comment]
I updated to the current master (394c544) as well and repeated the same steps. 
![image](https://user-images.githubusercontent.com/55233728/217129617-c9c462f3-7c5f-4d73-831b-cc4472177dab.png)

``help.html`` still specifies ``Frontpage.css`` and appears to be a copy of ``GhidraBuild/Skeleton/src/main/help/help/topics/skeleton/help.html`` https://github.com/NationalSecurityAgency/ghidra/blob/394c544/GhidraBuild/Skeleton/src/main/help/help/topics/skeleton/help.html

**Comment by ryanmkurtz** [comment]
Ok, I am reproducing it now.  We'll get it fixed.  Thanks!
