### ISSUE TITLE
[Feature Request] macOS App Bundle Support?

### ISSUE THREAD

**Issue by 0x8ff** [NationalSecurityAgency/ghidra#4965]
**Is your feature request related to a problem? Please describe.**
Not really, but it would be nice IMO for Ghidra to have support for it.

**Describe the solution you'd like**
My feature request is to add [macOS bundle support](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1) to Ghidra, so I can launch Ghidra as a macOS ``.app`` from the Dock, Finder, or Launchpad.

**Describe alternatives you've considered**
N/A

**Comment by ryanmkurtz** [comment]
This is something that has come up in the past but we do not plan on supporting.  Generally speaking, we don't want to get into the custom-packaging game.
