### ISSUE TITLE
Sleigh extract range v1[x,y]

### ISSUE THREAD

**Issue by NeoZ16** [NationalSecurityAgency/ghidra#4966]
I'm trying to access a variable position via the extract range syntax, but all I get is an error message. Is it even possible to extract like that or does it have to be a hard coded integer? I didn't really find information in the manual about this.

My code:
```
    local test:1 = 1;
    if (XmmReg2[test, 1] == 1) goto <cond_true>;
```

The error:
```
ERROR ia.sinc line 7162: no viable alternative on IDENTIFIER: 'test':

    if (XmmReg2[test, 1] == 1) goto <cond_true>;
----------------^
 (SleighParser)  
```

**Comment by GhidorahRex** [comment]
To do a bit extract you would do `((XmmReg2 & (1 << test)) >> test)`. If you need to do a longer range you'll need to make a mask for that such as `mask:4 = (1 << length) - 1;`

**Comment by astrelsky** [comment]
@GhidorahRex out of curiosity, since the bitrange operator `v1[6,1]` just breaks down to the example you provided, is there a reason it requires constants?

**Comment by emteere** [comment]
I believe it is because the v1[6,1] operation is more of a convenience macro that expands into similar operations that @GhidorahRex suggested.

**Comment by astrelsky** [comment]
> I believe it is because the v1[6,1] operation is more of a convenience macro that expands into similar operations that @GhidorahRex suggested. 

Right, which shouldn't need to be constrained to a constant?
