### ISSUE TITLE
Cannot double click to edit DataType of parameters in Function Signature Window

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4970]
**Describe the bug**
Double clicking the datatype cells does not allow editing of the entries, although name is perfectly fine. I haven't had the time to bisect, but it appears to be a fairly new bug

![image](https://user-images.githubusercontent.com/55233728/217451308-3f336435-80fd-4c9c-9b6c-a532b3ede6fc.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: openjdk 17.0.5
 - Ghidra Version: 5b543c184

**Comment by dragonmacher** [comment]
I  see the issue and will fix.

**Comment by Wall-AF** [comment]
Please ensure `F2` works as an alternative to the mouse.

Also, any chance of keyboard acccelerators added to the various input places?

Also the subsequent dialog `Storage Address Editor` cannot be used without a mouse.  There's no way to move the caret out from the `Datatype` input box.
![image](https://user-images.githubusercontent.com/67698927/219866329-5ad74efa-b136-4303-b4dd-9720ad295b41.png)

**Comment by Wall-AF** [comment]
@ryanmkurtz please reopen this for 2 reasons:
1. Pressing `F2` in the **Datatype** column of dialog `Edit Function at ...` doesn't allow the user to change the type without having to use the mouse first (it does however enable the user to go to the `Storage Address Editor` dialog);
2. Once in the `Storage Address Editor` dialog, tabbing forward from the `Datatype`box or backward from the `Add`button, when no storage is allocated, appears to lose focus forever as continued tabbing (forward/backward) does nothing and has no visual feedback to tell the user they are actually in the `Storage Locations` table (that requires `Ctrl+[Shift+]Tab` to navigate out).

To solve 2, I suggest bypassing that table if it's empty.

**Comment by ryanmkurtz** [comment]
@Wall-AF Are you finding that the original issue has not been fixed?

**Comment by Wall-AF** [comment]
@ryanmkurtz Okay, mouse works fine.  Just seems daft to open another issue for keyboard, although I did create one prior to this #3561!

**Comment by dragonmacher** [comment]
@Wall-AF I will investigate the issues you mentioned above.

**Comment by dragonmacher** [comment]
@Wall-AF Here are my observations:

> 1.  Pressing F2 in the Datatype column of dialog Edit Function at ... doesn't allow the user to change the type without having to use the mouse first (it does however enable the user to go to the Storage Address Editor dialog);

If the cell containing the data type to be edited is selected, then F2 will start the edit.    Once the table itself has focus, you can use the arrow keys or the tab key to change the current cell selection.   If there is a cell selected, it will have a colored border.

> 2.  Once in the Storage Address Editor dialog, tabbing forward from the Datatypebox or backward from the Addbutton, when no storage is allocated, appears to lose focus forever as continued tabbing (forward/backward) does nothing and has no visual feedback to tell the user they are actually in the Storage Locations table (that requires Ctrl+[Shift+]Tab to navigate out).

In the Dark Theme, the empty table, when selected, has a blue border to indicate the table is focused.   The Nimbus theme appears to have no visual indicator of focus.   When the table is focused, you can press `Ctrl-Tab` to jump to the `Add` button, which will allow you to add an entry to the table.  From there you should be able to `Ctrl-Shift-Tab` to go back to the table, or simply `Ctrl-Tab` until you get back there.

**Comment by Wall-AF** [comment]
> > 1. Pressing F2 in the Datatype column of dialog Edit Function at ... doesn't allow the user to change the type without having to use the mouse first (it does however enable the user to go to the Storage Address Editor dialog);
> 
> If the cell containing the data type to be edited is selected, then F2 will start the edit. Once the table itself has focus, you can use the arrow keys or the tab key to change the current cell selection. If there is a cell selected, it will have a colored border.

@dragonmacher Here is my experience:

After moving the cursor using the keyboard only (on the Windows version of Ghidra running from Eclipse) to the required datatype, pressing `F2` does change the appearance of the cell (see image below):
![image](https://user-images.githubusercontent.com/67698927/223803828-5b2090d8-c0c8-4d3f-bf1b-6540a79f1199.png)
but it isn't editable and the customery datatype dropdown doesn't appear.  In fact the only keys that have any subsequent response are these: <Enter>, <Home>, <End>, <PageUp>, <PageDown> and arrow keys; all of which move you off the selection.
