### ISSUE TITLE
change the behavior of .ghidra/.ghidra-xx folder for settings recover

### ISSUE THREAD

**Issue by dummys** [NationalSecurityAgency/ghidra#498]
Is it possible to change the behavior of adding the version to the .ghidra folder where settings are stored ? 
Let me explain it why. On linux, if you use a dotfile manager on git for example to synchronise/add/remove settings for all your computer, it's unmanageable to track all those .ghidra-xx version, it would be way better to use only .ghidra/.ghidra and store all the settings here. therefore when creating a new computer, just put this .ghidra/.ghidra and it's working. Otherwise when you have a new version of ghidra, it will create a new .ghidra folder and if you add modification from a computer which have the .ghidra-9.0.2 version and you track only the .ghidra-9.0.1 version inside your dotfiles, then the modification is not applied. Are you creating new .ghidra folder only for backward compatibility problems ?

**Comment by ryanmkurtz** [comment]
Yes, the .ghidra-x.y.z are for backwards compatibility, and for the cases where you need to run different versions of Ghidra without them stomping on each other.  We will not be able to change this behavior for the foreseeable future.
