### ISSUE TITLE
x86-64 POPFQ decoded as POPFD

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#4980]
**Describe the bug**
The POPFQ instruction (0x9d) is currently being decoded as POPFD.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 17
 - Ghidra Version: 10.3_DEV 

**Additional context**
PUSHFQ (0x9c) is currently decoded correctly. Mirroring the removal of the opsize in POPFQ to match PUSHFQ appears to fix this.

**Comment by GhidorahRex** [comment]
Not only should `popfq` be the default here, but `popfd` is not encodable in 64-bit mode, so the second of the two constructors is invalid.
