### ISSUE TITLE
Using Ghidra as a library

### ISSUE THREAD

**Issue by aa-software2112** [NationalSecurityAgency/ghidra#4981]
Hello!

I did piece together some vague online information regarding this question, but I would like your teams' expertise on the matter.

I would like to use Ghidra as a library (say .jar - I know you provide documentation for creating this jar), but to subsequently: A) load a binary and analyze it B) switch between loaded binaries on-the-fly C) send Ghidra scripts to execute over a specific, loaded binary.

Is this functionality possible? Do you have any code snippets, or prior examples of this?

Appreciate the help, as always.

Regards,

Anthony

**Comment by ryanmkurtz** [comment]
It sounds like you want to mimic some of the things our headless analyzer does, but from the single jar in library mode.  This is possible.  After you've built your jar with `support/buildGhidraJar` and have it linked to your project as a library, I recommend creating a new `HeadlessAnalyzer` instance and using the methods it provides.  If this doesn't give you enough control, you can read through `HeadlessAnalyzer.java` to see how it's accomplishing things.  For example, it uses the `AutoImporter` class to load a new binary off the disk.

**Comment by aa-software2112** [comment]
> It sounds like you want to mimic some of the things our headless analyzer does, but from the single jar in library mode. This is possible. After you've built your jar with `support/buildGhidraJar` and have it linked to your project as a library, I recommend creating a new `HeadlessAnalyzer` instance and using the methods it provides. If this doesn't give you enough control, you can read through `HeadlessAnalyzer.java` to see how it's accomplishing things. For example, it uses the `AutoImporter` class to load a new binary off the disk.

Precisely what I wanted to do. Thanks so much.
