### ISSUE TITLE
Improving work with function arguments

### ISSUE THREAD

**Issue by Marisa-Chan** [NationalSecurityAgency/ghidra#4983]
MSVC compiler with enabled ``/LTCG (Link-time code generation)`` parameter creates functions where sometimes arguments passed in ESI/EDI/EAX registers to addition to stack/ecx. So editing every function is very painful. And few releases before changed behavior of adding new custom argument, and now it's does not automatically "expand" ``undefined`` type to, let's say ``undefined4`` when added argument in ESI register. So it's now needs in additional action to manually change it to ``undefined4``.
![image](https://user-images.githubusercontent.com/431509/219260440-8406871a-aa69-4816-9ce9-41a4b4605547.png)

Ideally I see solution in adding menu entry(on right mouse clicking on such ``unaff_ESI/in_stack_0000000c``) with action to automatic argument creation. Or just checkbox in settings to back automatic ``undefinedX`` type substitution to fit selected argument location.

**Comment by astrelsky** [comment]
If I remember correctly, the msvc documentation states something along the lines of, that LTCG for 32 bit x86, the compiler can pass function arguments wherever it wants. So effectively the calling convention does not apply.

**Comment by Marisa-Chan** [comment]
Yeah, that's why I think option for adding arguments easy will really helps
a lot.

чт, 16 февр. 2023 г., 19:04 Andrew Strelsky ***@***.***>:

**Comment by mumbel** [comment]
Yeah, wish the add argument was like sizeof(void *) or the pentry maxsize.  Having it default as a 1 byte still makes no sense to me. 
 https://github.com/NationalSecurityAgency/ghidra/issues/2225

**Comment by ghidra1** [comment]
Change applied which will allow larger storage size (custom storage) and auto-size increase if datatype is undefined (upto 8-bytes).  This will allow only the storage to be specified without changing the datatype for the undefined case.
