### ISSUE TITLE
[Bug] Auto Analysis doesn't respect max threads setting

### ISSUE THREAD

**Issue by Helloyunho** [NationalSecurityAgency/ghidra#4985]
**Describe the bug**
Auto Analysis feature doesn't respect its max threads setting. Process `decompile` gets summoned 10 times(the default max threads value) and not 4 times(the value I set)

**To Reproduce**
1. Open CodeBrowser
2. Go to [Edit] -> [Tool Options...] -> [Auto Analysis]
3. Set `Max Threads` to 4 (or any small number)
4. Analyze the program by [Analysis] -> [Auto Analysis 'Program Name'...]
5. Run analysis with default settings

**Expected behavior**
Process `decompile` get summoned up to 4 times.

**Screenshots**
<img width="467" alt="CleanShot 2023-02-16 at 23 42 04@2x" src="https://user-images.githubusercontent.com/10192625/219396758-c4a1df70-1c38-41d8-9495-0a096f942a4c.png">

**Attachments**
No Attachments.

**Environment (please complete the following information):**
 - Arch: arm64 (M1 Pro)
 - OS: macOS 13.2.1
 - Java Version: 19.0.2
 - Ghidra Version: 10.2.2
 - Ghidra Origin: Homebrew

**Additional context**
As you probably know, M1 Pro has 8 performance cores and 2 efficiency cores, 10 cores total. So it might be spawning threads based on the core count. But still, I think it should respect the setting the user sets.

**Comment by dragonmacher** [comment]
IIRC, the Parallel Decompiler is not using this property, but is using a system property instead. 

I have not verified, but  the Parallel Decompiler may be using these properties instead of the analysis options:
```
# The following property will limit the number of processor cores that Ghidra
# will use for thread pools. If not specified, it will use the default number 
# of processors returned from Runtime.getRuntime().getAvailableProcessors(). 
# Otherwise, it will use the min of the value returned from Runtime and the 
# value specified by the following property.
VMARGS=-Dcpu.core.limit=

# The following property is a way to exactly specify the number of processor 
# cores that Ghidra will use for thread pools.  Note: this will supersede the 
# above 'cpu.core.limit' value if it is set.
VMARGS=-Dcpu.core.override=
```

**Comment by Helloyunho** [comment]
> IIRC, the Parallel Decompiler is not using this property, but is using a system property instead.
> 
> I have not verified, but the Parallel Decompiler may be using these properties instead of the analysis options:
> 
> ```
> # The following property will limit the number of processor cores that Ghidra
> # will use for thread pools. If not specified, it will use the default number 
> # of processors returned from Runtime.getRuntime().getAvailableProcessors(). 
> # Otherwise, it will use the min of the value returned from Runtime and the 
> # value specified by the following property.
> VMARGS=-Dcpu.core.limit=
> 
> # The following property is a way to exactly specify the number of processor 
> # cores that Ghidra will use for thread pools.  Note: this will supersede the 
> # above 'cpu.core.limit' value if it is set.
> VMARGS=-Dcpu.core.override=
> ```

Hmm, where can I set those values? I want to try it later.

**Comment by sad-dev** [comment]
As mentioned in #2791, the size of the "Analysis" pool (which auto analysis uses to perform parallel decompilation) is clamped to ``min(10, Runtime.getRuntime().availableProcessors() + 1)`` if "cpu.core.override" is not set.

**Comment by astrelsky** [comment]
This seems like a setting that **should** be changeable in the tool options for the decompiler.
