### ISSUE TITLE
Incorrect handling for PTR_64 Dyld Chained Fixup

### ISSUE THREAD

**Issue by NyaMisty** [NationalSecurityAgency/ghidra#4986]
**Describe the bug**
When I load a MachO binary into Ghidra, many references are relocated to 0x20xxxxxxx instead of normal 0x10xxxxxxx. Which is actually wrong.

**To Reproduce**
1. Load the sample MachO (extracted from LINE 13.0.1) (see Attachments)
2. Goto address   `109d5db60`

**Expected behavior**
The relocated address for `0x109d5db60` would be correct, which would be `0x1087e9f60` instead of `0x2087e9f60`

Note: In IDA, the address would be resolve to 0x109d5db60

**Screenshots**

<img width="1440" alt="2023-02-17 00 43 34" src="https://user-images.githubusercontent.com/5344431/219431206-bd516361-9944-433c-989f-e7a6f8413bbb.png">

**Attachments**
[LINE_13.0.1.zst.1.txt](https://github.com/NationalSecurityAgency/ghidra/files/10758442/LINE_13.0.1.zst.1.txt)
[LINE_13.0.1.zst.2.txt](https://github.com/NationalSecurityAgency/ghidra/files/10758445/LINE_13.0.1.zst.2.txt)
[LINE_13.0.1.zst.3.txt](https://github.com/NationalSecurityAgency/ghidra/files/10758447/LINE_13.0.1.zst.3.txt)
    - Please manually merge three file and unzip them with zstd

**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.14.2] macOS 13
 - Java Version: [e.g. 11.0] 19.0.2
 - Ghidra Version: [e.g. 10.1.4] 10.3 (master branch commit `bfb0ed6e34b9c49fc73f4b4cc3db04e49add184d`), also tested on 10.2.3 Release
 - Ghidra Origin: locally built

**Comment by NyaMisty** [comment]
Note: I've done some basic research. The 0x10xxxxxx -> 0x20xxxxx happens here:
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MachoProgramBuilder.java#L1797

According to code, if an item is neither rebase (bound) not autheticated, the pointer will be directly added by imageBase, causing a 0x100000000 difference in this case.

Apparently, Ghidra confuses PTR_64 & PTR_64_OFFSET. According to comments in xnu source: https://opensource.apple.com/source/xnu/xnu-7195.81.3/EXTERNAL_HEADERS/mach-o/fixup-chains.h.auto.html
```
// DYLD_CHAINED_PTR_64/DYLD_CHAINED_PTR_64_OFFSET
struct dyld_chained_ptr_64_rebase
{
    uint64_t    target    : 36,    // 64GB max image size (DYLD_CHAINED_PTR_64 => vmAddr, DYLD_CHAINED_PTR_64_OFFSET => runtimeOffset)
                high8     :  8,    // top 8 bits set to this (DYLD_CHAINED_PTR_64 => after slide added, DYLD_CHAINED_PTR_64_OFFSET => before slide added)
                reserved  :  7,    // all zeros
                next      : 12,    // 4-byte stride
                bind      :  1;    // == 0
};
```

For DYLD_CHAINED_PTR_64, the target (actually file bytes) will be already vmAddr, which can be easily seen in `Original Bytes` column in Relocation Table window, and is different from PTR_64_OFFSET case described in https://github.com/NationalSecurityAgency/ghidra/issues/3572#issuecomment-960707297

So we actually don't need to add imageBase onto chainedValue at all. A possible fix would be:
```
--- a/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MachoProgramBuilder.java
+++ b/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MachoProgramBuilder.java
@@ -1794,7 +1794,9 @@ public class MachoProgramBuilder {
                        }
                        else {
                                newChainValue = DyldChainedPtr.getTarget(pointerFormat, chainValue);
-                               newChainValue += imageBaseOffset;
+                               if (pointerFormat == DyldChainType.DYLD_CHAINED_PTR_64_OFFSET) {
+                                       newChainValue += imageBaseOffset;
+                               }
                        }
 
                        if (!start || !program.getRelocationTable().hasRelocation(chainLoc)) {
```

**Comment by ryanmkurtz** [comment]
Finally getting to look at this, sorry for the delay.  I'm working towards the chained issue, but am getting distracted by some other things.  Has this binary been edited in any way?

**Comment by ryanmkurtz** [comment]
You proposed solution seems to work....I appreciate your debugging it.  I assume you didn't mean to have that first `newChainValue += imageBaseOffset;` line.

**Comment by ryanmkurtz** [comment]
Actually, there are other types that must remain relative to the image base, such as `DYLD_CHAINED_PTR_ARM64E_USERLAND24`.
