### ISSUE TITLE
SLEIGH: Jump instruction with address offset

### ISSUE THREAD

**Issue by philpem** [NationalSecurityAgency/ghidra#5002]
I'd like to add support to Ghidra for the Mitsubishi MELPS-740 series processors. These are variants of the NMOS 6502 with extra features and/or instructions. I've started work on a branch already:  https://github.com/philpem/ghidra/tree/philpem-add-melps740

One of the new instructions is `JSR \$FFii`, encoded as `22 ii`. This instruction performs a jump-subroutine (call) to an address in page `$FF`, named the "special page".

So far the best I've managed for a SLEIGH encoding is:

```
:JSRSPECIAL   imm8                  is op=0x22; imm8
```
Which gives a disassembled output of e.g. `JSRSPECIAL $DF`.

Is it possible to describe the Mitsubishi assembly syntax, e.g. `JSR \$FFDF` in SLEIGH?

**Comment by GhidorahRex** [comment]
This seems pretty reasonable. I would do something like this

```
specOff: "\$"^reloc is imm8 [reloc = 0xff00 + imm8; ] { export *:4 reloc; }

:JSRSPECIAL specOff    is op=0x22; specOff {...}
```

**Comment by philpem** [comment]
That's great, thanks. Looks like that works pretty well!

I obviously need to test this -- my plan was to compile a reference binary with a known-good 740 assembler, check the generated code against the Mitsubishi 740 documentation, then feed it to Ghidra and make sure it matches the source.

Is there an established design pattern for adding tests to processor modules, or at least including the test binaries/assembly source and testing instructions?

**Comment by philpem** [comment]
Another question open to SLEIGH experts ...

The MELPS-740 introduces a "T" flag. This changes the behaviour of the ADC, SBC, AND, ORA and EOR instructions. Instead of operating on the accumulator (A register), they operate on the zero-page memory location pointed to by the X register. To express that in SLEIGH --

With T=0 the 740 behaves like a 6502:
```
:ADC OP1     is (cc=1 & aaa=3 & T=0) ... & OP1
{
	local op1 = OP1;
	local tmpC = C;
	
	C = carry(A, op1);
	
	A = A + op1 + tmpC;

	resultFlags(A);
	V = C;
}
```

With T=1:
```
:ADC OP1     is (cc=1 & aaa=3 & T=1) ... & X & OP1
{
	local op1 = OP1;
	local tmpC = C;
	local tmpX = *:1 X;
	
	C = carry(tmpX, op1);
	
	tmpX = tmpX + op1 + tmpC;

	resultFlags(tmpX);
	V = C;
}
```

Unfortunately this syntax doesn't work; SLEIGH complains that "T" isn't a varnode.

I've also tried combining the two SLEIGH descriptions into one, and adding an `if` conditional in the code -- this got me a syntax error (SLEIGH was expecting a 'goto' statement after the 'if (T==0)'). I guess this could work if I used pcode-relative branching, but that seems like a bit of an icky solution.

A context variable seems like it could be what I need, but I'd somehow have to keep the T status flag and the context variable in sync - the T flag will be pushed onto and popped off of the stack as part of the status byte.

**Comment by GhidorahRex** [comment]
> Is there an established design pattern for adding tests to processor modules, or at least including the test binaries/assembly source and testing instructions?

We use the pcodetests for that. We don't really have another set of tests for the processor modules. Processors like ARM, x86, MIPS (all the main ones, really) have pcodetests defined in their modules. You can look at those for examples. If you need something more specific regarding the tests, we can look into what we need to do for that.

**Comment by GhidorahRex** [comment]
Since the initial issue seems to be resolved, if you need any additional help, please create another issue.
