### ISSUE TITLE
Running the command "gradle nodepJar" fails the build with an exception related to "Debugger-agent-frida"

### ISSUE THREAD

**Issue by tommai78101** [NationalSecurityAgency/ghidra#5006]
**Describe the bug**
I have cloned the repository in my `E:\` drive, and have checked out the `master` branch.

When running the command in a Windows 10 x64 Powershell command terminal:   `gradle nodepJar`, I get the following error message:

```
> Task :Debugger-agent-frida:nodepJar FAILED
Execution optimizations have been disabled for task ':Debugger-agent-frida:nodepJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'E:\ghidra\Ghidra\Debug\Debugger-gadp\build\libs\Debugger-gadp.jar'. Reason: Task ':Debugger-agent-frida:nodepJar' uses this output of task ':Debugger-gadp:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'E:\ghidra\Ghidra\Debug\Framework-Debugging\build\libs\Framework-Debugging.jar'. Reason: Task ':Debugger-agent-frida:nodepJar' uses this output of task ':Framework-Debugging:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'E:\ghidra\Ghidra\Debug\Framework-AsyncComm\build\libs\Framework-AsyncComm.jar'. Reason: Task ':Debugger-agent-frida:nodepJar' uses this output of task ':Framework-AsyncComm:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Debugger-agent-frida:nodepJar'.
> Cannot expand ZIP 'E:\ghidra\Ghidra\Debug\Debugger\build\libs\Debugger.jar' as it does not exist.
```

I have attached the full debug text message to this issue:

[debug.zip](https://github.com/NationalSecurityAgency/ghidra/files/10773602/debug.zip)

I do not see any identifiable information in the debug log I have attached.

**To Reproduce**
1. Update Gradle to version 7.6.
2. Update Java 17 LTS to Eclipse Temurin SDK 17.35.
3. Checkout the latest commit from `master` branch @ 4b50ba28
4. Run `gradle nodepJar`.
5. Wait until the very end, and observe the build will fail.

**Expected behavior**
I should see the `Debugger.jar` being output successfully in the `E:\ghidra\Ghidra\Debug\Debugger\build\libs\Debugger.jar` location.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro x64 21H2 Build 19044.2604
 - Java Version: OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
 - Ghidra Version: Dev build @ 4b50ba28
 - Ghidra Origin: Locally built

**Comment by d-millar** [comment]
This is being worked (see #4957).  However, in the meantime, you could probably just delete this project with relative immunity.  The additional functionality provided by the Frida extension is slight.

**Comment by tommai78101** [comment]
@d-millar I'm not that familiar with the project structure. May I ask where I can delete the project from the gradle build file? (Or rather, where can I comment out the gradle task, so it won't be built?)

**Comment by d-millar** [comment]
Not a gradle expert myself, but I think, if you move Ghidra/Debug/Debugger/Debugger-agent-frida/build.gradle to build.gradle.save or the equivalent, the problem will go away. (Won't have a chance to try this out myself, unfortunately, as i'm on the road today.)

**Comment by tommai78101** [comment]
@d-millar Thanks for the pointers. If I have any questions, I'll ask here for follow-ups. Stay safe on your travels.

**Comment by tommai78101** [comment]
@d-millar Just an update, I'm able to successfully build the `nodepJar` file.

I need to disable the following Gradle projects from being built:
* `Ghidra/Debug/Debugger-agent-frida`
* `Ghidra/Debug/Debugger-agent-lldb`

Both of these projects have errors when building with Gradle.

**Comment by d-millar** [comment]
Hmmmm, just trying this out myself, and I guess I'm confused regarding what you are trying to attempt.  I was able to build ghidra using "gradle -I gradle/support/fetchDependencies init" and "gradle buildGradle" using gradle 7.6, JDK 17, on Windows Server 2019 (which should be roughly equivalent to Windows 10).  I was also able to run "gradle nodepJar" from Debugger-agent-dbgeng.  If have built gdb and lldb modules on the same platform and, if need be, I guess I could test building the nodepJar from those directories and Debugger-agent-frida, but I am struggling to come up with a scenario in which you would either want or need to do this.  Judging from your description, you do not either, i.e. you're not trying to use Frida on a remote Windows box from a different box running Ghidra, are you?  Just trying to figure out how you got to the point where you're having problems....

**Comment by tommai78101** [comment]
@d-millar I was trying to figure out how to connect Ghidra on Windows to a GDB server on Windows. 

The changelogs for Ghidra v10.2.3 mentioned:

```
* Debugger. Added GDB connector support for Windows (tested with GDB 11.1 on msys64). (GP-869, Issue #2908)
```
so I figured I should look into the "IN-VM GDB local debugger" option when connecting a debugging target GDB to the Windows GDB server that is listening to a "IP address : Port".

Turns out, there are no steps or explanations on how to get that to work on Windows. I'm pretty lost here.

While browsing online, I saw some information from one of the maintainers of Ghidra mentioning about building `gradle nodepJar` to compile a debugger gdb JAR, which allows Ghidra to communicate using GADP protocol, since Windows currently doesn't support the "IN-VM GDB local debugger" due to lacking Pty (which I doubt this since the changelog mentioned otherwise).

https://github.com/NationalSecurityAgency/ghidra/discussions/2721?sort=top#discussioncomment-341880

It was around the section of that comment mentioning about this command line that I had trouble understanding what the -h\` flag is doing, and why there's a tilde next to it, and what the command flags for `--gadp-args`, `-H` and `-g` parts. 

```
java -jar Debugger-agent-gdb-nodep.jar -h`
``` 

So, I thought, "Why not? Let's try it out and see", and proceed to follow the steps from the comment. And that's how I got here. 

The whole comment chain hasn't been updated in a month or 2, so I was wondering maybe there are new changes in the latest Ghidra update (v10.2.3)?  As a side note, I don't think WSL uses `localhost`, but rather it uses a specific IP address that's created when WSL is launched. I used Ubuntu WSL, and I had to use `ip route` in WSL to obtain the `localhost` IP address that comes after `default via` text. But that is as far as I have gotten.

If there are more information about building a GADP JAR file using `gradle nodepJar`, that would be helpful.

**Comment by d-millar** [comment]
OK, I'm up to speed, I think.  I don't think you want to build the nodepJar.  (Technically, you can build the nodepJar for gdb by running "gradle nodepJar" in Debug/Debugger-agent-gdb, but really you don't need or want to do this.)

That said, you have two options - both assume you have a version of gdb on the server box (from msys or whoever).

If the client and server are the same machines, i.e. you're running Ghidra on the box where gdb is installed, you can now just use the "IN-VM GDB local debugger" option.  The Pty requirement is now supplied using ConPTY (which I did not know).  It apparently is slow but functional.

The other option is to use "GDB over SSH".  This requires that, in addition to gdb, you have the Windows equivalent of and sshd daemon running, i.e. you have to be able to ssh into the server.  Pointing the dialog at the msys version of gdb with either the local IP, the WSL IP, or a remote IP for the server "should" work.

Let us know if (when?) it doesn't, and we'll be happy to help troubleshoot.

**Comment by tommai78101** [comment]
@d-millar Thanks. I'll be posting in the Github issue below, since that issue tracks the IN-VM GNU gdb local debugger, while the one we currently are in tracks the compilation errors associated with `gradle nodepJar`.

https://github.com/NationalSecurityAgency/ghidra/issues/3562

**Comment by d-millar** [comment]
Not reproducible

**Comment by nsadeveloper789** [comment]
I think this boils down to Gradle foo. A task by that same name exists in at least 3 projects. If you want just to build the GDB one:

```
gradle Debugger-agent-gdb:nodepJar
```
