### ISSUE TITLE
arm64: cannot parse windows ntoskrnl.exe function parameters properly

### ISSUE THREAD

**Issue by limulidae** [NationalSecurityAgency/ghidra#5018]
**Describe the bug**
Load arm64 ntoskrnl (for example, [22621.1105](https://msdl.microsoft.com/download/symbols/ntoskrnl.exe/64C47E61103d000/ntoskrnl.exe))

The 1st parameter is not parsed correctly.

**To Reproduce**

load ntoskrnl.exe from ghidra
load symbol
look at PpmIdleSelectStates()
[ghidra10_2_3__nt_22621_1105_PpmIdleSelectStates.txt](https://github.com/NationalSecurityAgency/ghidra/files/10751542/ghidra10_2_3__nt_22621_1105_PpmIdleSelectStates.txt)
Its 1st parameter type is wrong: undefined8
and, param_1 is not referenced.

**Expected behavior**
1. The 1st parameter is int64 or something
2. The 1st parameter is referenced in the decompiled source

**Reference:**
https://github.com/NationalSecurityAgency/ghidra/issues/4901#issuecomment-1432399802

**Comment by emteere** [comment]
The parameters recovered correctly for me if the function __security_push_cookie() is set to inline, causing the code for the function to be  included in each function that calls it.

```
void PpmIdleSelectStates(longlong param_1,ulonglong param_2,undefined8 *param_3,undefined8 *param_4,
                        char *param_5,uint *param_6,uint *param_7,undefined8 *param_8)
```

We can add a call_fixup for the  __security_push_cookie function that will get the side-effects to the stack for the function without needing to inline, which would fix the issue automatically.  We'll have to take a closer look to see the best way to fix this.
