### ISSUE TITLE
ARM64 STR instructions have incorrect pcode with literal offsets 

### ISSUE THREAD

**Issue by adamprescott91** [NationalSecurityAgency/ghidra#5022]
**Describe the bug**
The STR instruction has incorrect PCODE which causes incorrect decompilation to be displayed when a literal offset is used in the instruction. The PCODE adds the offset to the destination register when the destination register should be unaffected by this instruction.
str x0, [x21], #0x8 results in the following PCODE being generated.

![STR_pcode](https://user-images.githubusercontent.com/3738889/220792498-808ab50e-1100-427f-b15a-c3ea7204fdb3.PNG)

**Expected behavior**
The PCODE should not have any effect on the destination register and should not have the x21 = INT_ADD x21, 8:8 line.
It should also have the first line be $U3d780:8 = INT_ADD x0, 8:8
As the offset is applied prior to writing the source data to the destination.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Java Version: open JDK version 19.0.1
 - Ghidra Version: 10.2.3
 - Ghidra Origin: Official GitHub release

**Comment by mumbel** [comment]
You should probably provide the instruction bytes (and possibly even an instruction manual reference showing why you think this is wrong given the amount of addressing modes).

this instruction does not look wrong to me when I look at the manual for `STR (immediate)`  `post-index` 64-bit, which is what the syntax of this instruction matches (`STR <Xt>, [<Xn|SP>], #<simm>`)

contents of Xt (x0) is stored in address in Xn (x21) and Xn (x21) is post-indexed by simm (8)

**Comment by adamprescott91** [comment]
Ah yep, I've misread the reference sheet I was looking at 👍 
Classic case of me thinking that the tool must be wrong because the output didn't make sense but its actually just the compiler doing some crazy stuff.
