### ISSUE TITLE
Objective-C 2 Class> Invalid index: 2251807873974800

### ISSUE THREAD

**Issue by drewcrawford** [NationalSecurityAgency/ghidra#5023]
**Describe the bug**
When analyzing the attached file, I get the error shown

**To Reproduce**
1.  File->Import File...
2. Select attached extracted file
3. Choose "yes" for "analyze now"
4. Deselect all options (or you can auto-analyze, but it will take longer)
5. Select "Objective-C Class" analysis and then "Analyze"

**Expected behavior**
Analyzes successfully

**Screenshots**
<img width="602" alt="Screenshot 2023-02-23 at 12 57 09 AM" src="https://user-images.githubusercontent.com/183400/220838783-ac351021-20be-4cee-8591-9d6d60436a5d.png">

**Attachments**
https://dr-droplr.s3.amazonaws.com/ShareSheet.zip

**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.14.2] 13.2.1 (22D68)
 - Java Version: [e.g. 11.0]: 17.0.6
 - Ghidra Version: [e.g. 10.1.4] 10.2.3
 - Ghidra Origin: [e.g. official GitHub distro, third party distro, locally built]: Github official

**Additional context**
This is an iOS binary from the dyld_cache of 16.3.1

**Comment by ryanmkurtz** [comment]
@drewcrawford How was this file extracted from the cache?

**Comment by ryanmkurtz** [comment]
For my own debugging notes, exception occurs here:
https://github.com/NationalSecurityAgency/ghidra/blob/10c7d641f092f946dd182630b444ab331dba7a31/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/analysis/ObjectiveC2_ClassAnalyzer.java#L311

**Comment by drewcrawford** [comment]
Steps to extract the file are

1.  Get ahold of iPhone14,7_16.3.1_20D67_Restore.ipsw
2. Extract as zip
3. Mount 098-24668-069.dmg
4. In ghidra, import /Volumes/SydneyD20D67.D27SystemCryptex/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e
5. If prompted, choose to import as filesystem
6. In the Ghidra picker, navigate to the image at System/Library/PrivateFrameworks/ShareSheet.framework/ShareSheet
7. Import this image
8. (Original issue can be reproduced at this point.)
9. File->Export Program.  Format:Binary

**Comment by ryanmkurtz** [comment]
Thanks, I just wanted to verify that you were indeed using the Ghidra filesystem feature to extract the dylib, as opposed to some other tool.
