### ISSUE TITLE
"Find Uses of Field" option fails to find all uses of a custom struct member

### ISSUE THREAD

**Issue by dennisbabkin** [NationalSecurityAgency/ghidra#503]
I've been playing with Ghidra and was able to find this (possible) bug in its "Find uses of field" option.

**To Reproduce**

In the "Data type manager" window right-click on a custom `struct` and select "Find Uses of Field":

![1](https://user-images.githubusercontent.com/25473659/56649077-4b0fb380-6639-11e9-8e2d-cb87f277ef05.png)

and select a custom `enum` member of that custom struct:

![2](https://user-images.githubusercontent.com/25473659/56649086-52cf5800-6639-11e9-8402-0a12b21441d7.PNG)

The resulting list will fetch some entries that were found:

![3](https://user-images.githubusercontent.com/25473659/56649121-62e73780-6639-11e9-9d56-b8aa09a04d81.PNG)

## BUG ##

The list it reports (see above) is **not compete**.

For example, this is the part of code in the same project that contains that same field (i.e. `activePartFlgs`) that was not found in the window above (marked with arrows):

![4](https://user-images.githubusercontent.com/25473659/56649852-c9b92080-663a-11e9-88a7-4ee4db925a02.PNG)

-------------------------------------

Just for completeness, here's the custom `struct` that I was searching the member of:

![5](https://user-images.githubusercontent.com/25473659/56649230-95913000-6639-11e9-863f-aae642ada48e.PNG)

and here's that actual custom `enum`:

![6](https://user-images.githubusercontent.com/25473659/56649265-a2158880-6639-11e9-8116-a58357928dc6.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Java Version: 11
 - Ghidra Version: 9.0.2

**Comment by dragonmacher** [comment]
This code has recently been changed in master.   I have no easy way to test the example given here.   If possible, please test against your original binary with a pull from master (or wait for 9.2).   If not possible to test, then let us know and I will close the ticket.

**Comment by ZereX666** [comment]
> This code has recently been changed in master. I have no easy way to test the example given here. If possible, please test against your original binary with a pull from master (or wait for 9.2). If not possible to test, then let us know and I will close the ticket.

Now, in version 10.2.3 I got the same bug...
