### ISSUE TITLE
GNU Demangler not available for ARM architecture

### ISSUE THREAD

**Issue by rewanthtammana** [NationalSecurityAgency/ghidra#5035]
## Is your feature request related to a problem? Please describe.

I was trying to decompile binaries in M1 mac but the decompilation feature doesn't seem to work due to it's dependency on GNU demanger.

Upon installing ghidra in fedora VM in M1 mac on ARM architecture, I see only files for `x86_64` architecture. Is it possible to compile these binaries for ARM architecture to extend the support?

<img width="652" alt="image" src="https://user-images.githubusercontent.com/22347290/221412137-31cfb92e-352f-480c-831d-4fa9113f488b.png">

## Describe the solution you'd like
Would love to have decompilation capabilities for ARM architecture

**Comment by ryanmkurtz** [comment]
Try running support/buildNatives to build the native binaries for your local platform.

**Comment by rewanthtammana** [comment]
Thanks a ton, @ryanmkurtz! I followed the [DevGuide](https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.2.2_build/DevGuide.md) and it worked.

![image](https://user-images.githubusercontent.com/22347290/221426171-9f80dfdb-f96f-4159-98ba-53a74716baec.png)
