### ISSUE TITLE
Decompiler: PowerPC: Some `fsel` instructions don't have branches

### ISSUE THREAD

**Issue by LukeSerne** [NationalSecurityAgency/ghidra#5038]
**Describe the bug**
Sometimes, the `fsel` instruction ends up being decompiled wrongly. The `fsel` instruction takes 4 floating-point registers as operands (`a`, `b`, `c` and `d`), and performs the operation `a = (b >= 0.0) ? c : d;`. However, sometimes, the decompiled code represents this instruction as `a = d;`.

**To Reproduce**
1. Compile `decomp_dbg`:
    1. Go to `SLEIGHHOME/Ghidra/Features/Decompiler/src/decompile/cpp`
    2. Run `make decomp_dbg`
2. Install the PowerPC Gekko/Broadway language ([repo](https://github.com/aldelaro5/ghidra-gekko-broadway-lang))
3. Extract `example_bad.xml` from [example.zip] and save it somewhere
4. Start the `decomp_dbg` program
5. `restore <path_to_example_bad_xml>`
6. `load function func`
7. `decompile`
8. `print C`
9. Observe that the decompiled output is:
```
double func(float *param_1)

{
  return (double)*param_1;
}
```

**Expected behavior**
The decompiled output in the result should contain a branch and look something more like:
```
double func(double param_1,float *param_2)

{
  if ((float)(param_1 - (double)*param_2) >= 0.0) {
    param_1 = (double)*param_2;
  } else {
    param_1 = param_1;
  }
  return param_1;
}
```

**Environment (please complete the following information):**
 - Ghidra Version: 10.2.3
 - Ghidra Origin: official Github release

**Additional context**
Interestingly enough, if the values are flipped, the code _is_ decompiled correctly. The xml file required to observe this is also included in the attached [example.zip], as `example_good.xml`.

Some preliminary research using the [DecompVis](https://github.com/LukeSerne/DecompVis) program indicates that the likely error is introduced already after the `heritage` decompiler rule. This program shows the state of the data flow graph after each decompiler rule, for every rule that is applied to a given function. I have included two screenshots of part of the data flow graph for both example functions. The red nodes are P-CODE operations (`PcodeOp`s), and the other nodes are `Varnode`s. Brown nodes represent address spaces, gray nodes represent constants, yellow nodes represent `Varnode`s that are inputs to the function, and all remaining `Varnode`s are green. The order of the arrows pointing into nodes also shows the order of the input `Varnode`s, from left to right. 

For the function that has wrong decompilation (left image), note how the inputs to the `MULTIEQUAL` P-CODE operation both lead to the same `%f1` register. As such, future rules will eliminate the `MULTIEQUAL` operation and thus the branch in the control flow. The function with the correct decompilation however, has two different inputs to the `MULTIEQUAL`, one of which comes from a function input `%f1` register. These two different origins also mean that no future rule will eliminate the `MULTIEQUAL`, and thus, the branch in the control-flow will persist into the final C code.

![data-flow-bad](https://user-images.githubusercontent.com/32435769/221438405-f22e5cd7-defe-41b6-8140-1b63e93be6fc.png) ![data-flow-good](https://user-images.githubusercontent.com/32435769/221438563-054adac8-7c1a-45fc-b275-11f076ade7f9.png)

[example.zip]: https://github.com/NationalSecurityAgency/ghidra/files/10834805/example.zip

**Comment by mumbel** [comment]
sounds like you should be filing this bug in that repo

**Comment by LukeSerne** [comment]
Hmm, you are correct. I initially thought that the raw P-CODE produced by the language definitions was correct, but it turns out that's not the case. As this is not a bug in Ghidra, I'll close this issue now.
