### ISSUE TITLE
Incorrect data types for DT_FINI_ARRAY/DT_INIT_ARRAY

### ISSUE THREAD

**Issue by mrexodia** [NationalSecurityAgency/ghidra#5039]
**Describe the bug**

The data types applied to the ELF init array are incorrect, making the reversing of init/fini functions confusing.

**To Reproduce**
1. Load a ELF shared library that has some init/fini functions
2. Go the the init/fini function of your choice
3. Right click -> References -> Show references to address

**Expected behavior**

You should get a reference to the function pointer from the init/fini array.

**Screenshots**

<img width="876" alt="image" src="https://user-images.githubusercontent.com/2458265/221558837-1e507827-a969-41a7-80ba-ddd2a2f86f9b.png">

**Environment (please complete the following information):**
 - OS: macOS 
 - Java Version: OpenJDK 19
 - Ghidra Version: 10.2.3
 - Ghidra Origin: GitHub Release

**Additional context**

The listing of the `.fini_array` and `.init_array`:

```
                             //
                             // .fini_array 
                             // SHT_FINI_ARRAY  [0x14c958 - 0x14c967]
                             // ram:0024c958-ram:0024c967
                             //
                             __DT_FINI_ARRAY                                 XREF[2]:     0024d100(*), 
                                                                                          _elfSectionHeaders::00000450(*)  
        0024c958 2c 68 12        dq         Elf64_Ehdr_00100000
                 00 00 00 
                 00 00
        0024c960 14 68 12        dq         126814h
                 00 00 00 
                 00 00
                             //
                             // .init_array 
                             // SHT_INIT_ARRAY  [0x14c968 - 0x14cf67]
                             // ram:0024c968-ram:0024cf67
                             //
                             __DT_INIT_ARRAY                                 XREF[2]:     0024d0e0(*), 
                                                                                          _elfSectionHeaders::00000490(*)  
        0024c968 c8 1e 14        dq         Elf64_Ehdr_00100000
                 00 00 00 
                 00 00

```

It looks like the offending code is here. If you manually change the data type to be a pointer everything is working as expected. I didn't try changing it in the code yet though...

https://github.com/NationalSecurityAgency/ghidra/blob/b4de95f4f5c5b2d22e2861a08f7f8f6b40f6e6a7/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/ElfProgramBuilder.java#L712

**Comment by mrexodia** [comment]
Here is a script that fixed it for my use case:

```java
//@author Duncan Ogilvie
//@category Analysis
//@keybinding
//@menupath Analysis.One Shot.Fix ELF init arrays
//@toolbar
// Reference: https://www.reddit.com/r/ghidra/comments/h07yoo/comment/fukuj1c

import ghidra.app.script.GhidraScript;
import ghidra.framework.cmd.CompoundCmd;
import ghidra.app.cmd.data.CreateArrayCmd;
import ghidra.program.model.data.PointerDataType;

public class FixELFInitArrays extends GhidraScript {
    @Override
    protected void run() throws Exception {
        var cmd = new CompoundCmd("Fix ELF init arrays");
        for (var block : getMemoryBlocks()) {
            var comment = block.getComment();
            if(comment.contains("SHT_PREINIT_ARRAY") || comment.contains("SHT_INIT_ARRAY") || comment.contains("SHT_FINI_ARRAY")) {
                var start = block.getStart();
                var pointerSize = start.getPointerSize();
                var count = block.getSize() / pointerSize;
                println(String.format("%s %s[%X]",
                        block.getName(),
                        block.getStart(),
                        count
                ));
                cmd.add(new CreateArrayCmd(start, (int)count, PointerDataType.dataType, 0));
            }
        }

        // Execute the commands (this allows us to undo)
        if(cmd.size() > 0) {
            cmd.applyTo(currentProgram);
            println(String.format("Applied %d array types!", cmd.size()));
        } else {
            println("No ELF init arrays found");
        }
    }
}
```

**Comment by ghidra1** [comment]
Pointers cannot genrally be applied to the init/fini arrays since relocations do not get applied to these and their data values must be adjusted to obtain the correct memory offset.  The data value will be adjusted for any prelink then again by an image base adjustment.

As you noticed in the `ElfProgramBuilder`, these tables are identified via the dynamic table (.e.g., .dynamic) and do get mark-up with references when the loader is successful at creating a functions at the corresponding memory location.  If this is not occuring properly we would need to diagnose why that is the case.   We would need to reproduce the issue to properly diagnose as the data values may be getting improperly adjusted during processing.  Are you able to share your binary or another that exhibits a similar issue?

**Comment by ghidra1** [comment]
I am unable to replicate your issue with Linux shared library import which does get marked-up as expected.  We would need a specific sample which exhibits the issue you describe.

**Comment by mrexodia** [comment]
Is it possible to share the binary privately? It’s available to the public, but I want to avoid sharing what I’m working on publicly.

**Comment by ghidra1** [comment]
You may email compressed sample to 48333018.ghidra1@gmail.com
Thanks

**Comment by mrexodia** [comment]
Done, I added both `ghidra1` and `ryanmkurtz`!

**Comment by ghidra1** [comment]
I have reproduced the issue and have a fix in the works.  Your sample actually applies relocations to the pointer tables.  I had to change the code to handle both this case and the case where no relocations are applied.

**Comment by mrexodia** [comment]
Awesome, thanks a lot!
