### ISSUE TITLE
increase script console output line limit

### ISSUE THREAD

**Issue by ITmustang** [NationalSecurityAgency/ghidra#5045]
I've noted that when i run some scripts, the output on script console is overwritten so i cannot see the entire script output on screen. hoping is there a solution to increase script console line limit? or pipe to a text file?

**Comment by dragonmacher** [comment]
There is an option for the console character limit in the tool options.  You can try changing that to see if it helps.  That is under the main menu at `Edit -> Tool Options` under `Console -> Character Limit`.

**Comment by ITmustang** [comment]
perfect, just what i needed, thanks! ill close issue.
