### ISSUE TITLE
Restore navigation stack on open

### ISSUE THREAD

**Issue by ChrisMGeiger** [NationalSecurityAgency/ghidra#505]
**Is your feature request related to a problem? Please describe.**
When opening an existing database, navigation starts at the top of the program (e.g. address 0)

**Describe the solution you'd like**
Navigation stack (previously visited functions) to be restored and current location to updated to last position. This navigation need not be synchronized to the server as different uses may have different areas they are working in.

**Describe alternatives you've considered**
This could possibly be incorporated as a plugin but I haven't explored the API or hooks for executing on close.

**Comment by dragonmacher** [comment]
There is a 9.0.5 fix for the cursor portion of this ticket.
The history restore is still being investigated.
