### ISSUE TITLE
How can I make available the options shown as "Ghidra does not know how to render state"?

### ISSUE THREAD

**Issue by Berylskid** [NationalSecurityAgency/ghidra#5057]
Some of the tool options and analyzer options are not available.

They are displayed as: `Ghidra does not know how to render state: (name)`

How can I make them configurable?
|||
|---|---|
| Ghidra version | 10.2.3 |
| Java Version | 17.0.6 |
| Platform | Windows 10 |

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/91955473/222647592-d3bfce98-6eb0-4269-88f6-1559b9640d67.png)
</details>

**Comment by dragonmacher** [comment]
I believe this was fixed in this commit: 7230df9de3fa3

Ghidra 10.3 will have this change.   In the meantime, the master branch has the change, which means it is available to you if you are willing to setup a dev environment and run in that mode.

**Comment by Berylskid** [comment]
Thank you for replying! I would like to set up a dev environment.
