### ISSUE TITLE
DataType Manager : Ghosts in the Preview Window

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5058]
**Describe the bug**
![image](https://user-images.githubusercontent.com/55233728/222680270-97c380ed-9e4b-4451-84e9-1a3ab067e0aa.png)

**To Reproduce**
1. Add the windows_vs12_64.gdt (standard archive)
2. Open ``accctrl.h/_ACTRL_ACCESS_ENTRY_LISTA`` with the Preview window open
3. Move your mouse up and down across the blue type names fast

**Comment by dragonmacher** [comment]
Is this a new issue for you?  Is this on Linux?   This is a known issue on some Linux distros.  But, this issue has been around for a long time.  If this is specific to a version of Ghidra, then this may be a different issue.

**Comment by sad-dev** [comment]
Yes it appears to be related to that issue. Feel free to close it as a duplicate?

**Comment by dragonmacher** [comment]
Closed as duplicate of #4451
