### ISSUE TITLE
How to retype global?

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#506]
I am looking at the following memory layout:

![2019-04-24 14_19_41-CodeBrowser_ ISI-5679__e03063ff5cbd787129a1c3bd34ec6f88dbb8a5c06073e7fb4ff1d8f60](https://user-images.githubusercontent.com/11869704/56659013-61029000-669c-11e9-9a3e-9156c6ce2c94.png)

... and I know that `GLOBAL_STRING` is an `std::string`. I created the following structure:

![2019-04-24 14_19_02-Structure Editor - std_string (e03063ff5cbd787129a1c3bd34ec6f88dbb8a5c06073e7fb4](https://user-images.githubusercontent.com/11869704/56659416-54326c00-669d-11e9-8943-766c6de80300.png)

But retyping the global `GLOBAL_STRING` to `std_string` yields the following error message:

![2019-04-24 14_19_29-Retype Failed](https://user-images.githubusercontent.com/11869704/56659074-87c0c680-669c-11e9-936f-107d4d15c256.png)

I assume this is because Ghidra has recorded references to the `capacity` and `size` field as well and is unwilling to remove these labels. I found no way to manually remove them, what is the proper way to do this?

**Comment by emteere** [comment]
Just clear any data types that are already defined in the memory locations covered by the structure.  Ghidra won't clear data out.

The references don't matter.

**Comment by huettenhain** [comment]
Ah, thank you so much. That worked flawlessly.

**Comment by ChrisMGeiger** [comment]
Also, if you select the correct number of bytes, then you can apply the desired type
