### ISSUE TITLE
Crash on consecutive script runs

### ISSUE THREAD

**Issue by h-hosseinzadeh** [NationalSecurityAgency/ghidra#5060]
**Describe the bug**
Over the last few days, Ghidra proceeds to crash entirely when I attempt to run a script for the second time in a row. Once the app is opened again, It proceeds to run the script once, and then crashes on attempt #2. It is regardless of what the script entails or what is being analyzed, something is simple as printing 'hello world' is enough to trigger it. I've tried reinstalling Ghidra to see if it solves the problem and have also tried using an older version to no avail.  

**To Reproduce**
1. Open any script
2. Run the script
3. Run the script again

Once the crash happens, Ghidra closes entirely and a .log crash report is created in my home directory which I've included here.

Host OS: Windows 11
Gurst OS: Ubuntu 22.04
Java version: 17.05
Ghidra version: 10.2.3
Origin: Official github distro

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
``` 
A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fee762a9d78, pid=3814, tid=4824

 JRE version: OpenJDK Runtime Environment (17.0.5+8) (build 17.0.5+8-Ubuntu-2ubuntu122.04)
 Java VM: OpenJDK 64-Bit Server VM (17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  [_multiarray_umath.cpython-310-x86_64-linux-gnu.so+0x2a9d78]  PyArray_Item_INCREF+0x28

 Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/happydragon/core.3814)

 If you would like to submit a bug report, please visit:
  Unknown
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.


---------------  S U M M A R Y ------------

Command Line: -Djava.system.class.loader=ghidra.GhidraClassLoader -Dfile.encoding=UTF8 -Duser.country=US -Duser.language=en -Duser.variant= -Dsun.java2d.opengl=false -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3 -Dcpu.core.limit= -Dcpu.core.override= -Dfont.size.override= -Dpython.console.encoding=UTF-8 -Xshare:off --add-opens=java.desktop/sun.awt.image=ALL-UNNAMED -Dsun.java2d.pmoffscreen=false -Dsun.java2d.xrender=true -Dsun.java2d.uiScale=1 -Dawt.useSystemAAFontSettings=on ghidra.Ghidra ghidra.GhidraRun

Host: 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz, 4 cores, 7G, Ubuntu 22.04.1 LTS
Time: Fri Mar  3 12:12:57 2023 CST elapsed time: 550.652183 seconds (0d 0h 9m 10s)
```

**Comment by ryanmkurtz** [comment]
Are you trying to do cpython things from your script?  

```
 C  [_multiarray_umath.cpython-310-x86_64-linux-gnu.so+0x2a9d78]  PyArray_Item_INCREF+0x28
 ```
looks suspect

**Comment by h-hosseinzadeh** [comment]
> Are you trying to do cpython things from your script?
>  C  [_multiarray_umath.cpython-310-x86_64-linux-gnu.so+0x2a9d78]  PyArray_Item_INCREF+0x28
> looks suspect

Yes! I have been using python as my scripting language. I also have the ghidrathon extension installed, but this problem did not exist up until now even though I've been using those for a while before this!

**Comment by ryanmkurtz** [comment]
I believe the issue is something to do with the Ghidrathon extension, which we do not support.  I would recommend you open an issue with that project.  Perhaps they have seen this issue before.
