### ISSUE TITLE
GADP agent not launched with correct JVM

### ISSUE THREAD

**Issue by pgalbraith** [NationalSecurityAgency/ghidra#5071]
**Describe the bug**
Debugger is using system JVM instead of application JVM to launch GADP agent.

**To Reproduce**
1. Install default system JDK 11 (`apt-get install default-jdk`).  Use sdkman to Install default local JDK 17 (`sdk install java`).  Install Ghidra.
2. Launch Ghidra, instruct it to use the local JDK 17 in `~/.sdkman/candidates/java/current`.
3. Add binary to project, launch debugger, attempt to connect to local GADP GDB target.

**Expected behavior**
GADP agent starts, debugging begins.

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: 17 (in `~/.sdkman/candidates/java/current`), 11 (in `/usr/bin/java` -> `/usr/lib/jvm/...`)
 - Ghidra Version: 10.2.3
 - Ghidra Origin: official GitHub distro 

** Error ** -- Ghidra reports using JDK 17.0.6, but the error is clearly actually from JDK 11 complaining that it cannot use Java 17 class files, so the GADB launcher is not using the JDK that was determined in LauncherSupport.jar.

java.lang.RuntimeException: Agent terminated with error: Error: LinkageError occurred while loading main class 
agent.gdb.gadp.GdbGadpServer
	java.lang.UnsupportedClassVersionError: agent/gdb/gadp/GdbGadpServer has been compiled by a more recent version of 
the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 
55.0

---------------------------------------------------
Build Date: 2023-Feb-08 1242 EST
Ghidra Version: 10.2.3
Java Home: /home/paul/.sdkman/candidates/java/17.0.6-tem
JVM Version: Eclipse Adoptium 17.0.6
OS: Linux 6.1.11-76060111-generic amd64

**Comment by pgalbraith** [comment]
I will close this as it's easy to work around and seems to fall into the same category as https://github.com/NationalSecurityAgency/ghidra/pull/1556 in that it's nice to have for launching on Linux, but that's about the extent of it.

This did not happen for me when running ghidraRun from a shell -- it only occurred when trying to run from a .desktop launcher, presumably because my local JDK would not be in the PATH for the launcher.  A separate shell script wrapper seems necessary anyways to call support/launch.sh in order to get Ghidra to launch Ghidra in the foreground, so explicity setting JAVA_HOME and forcing the JDK bin directory onto the path is a very acceptable workaround for me.

**Comment by d-millar** [comment]
@pgalbraith thanks for following up - I was trying to find another related ticket, but just haven't quite found time this week.  I do believe we have a more general fix in the current code based, which should go out with the next release.  glad you have a workaround until then!

**Comment by d-millar** [comment]
Just following up: changes were made to AbstractGadpLocalDebuggerModelFactory class to correct this problem across implementations.  The code is in the current master branch and will be released with 10.3.
