### ISSUE TITLE
Workflow when testing plugins?

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5073]
I was trying my hand at writing a plugin and found that testing it was rather tedious:

1.) Open Ghidra and Install Extension to load the plugin
2.) Reload Ghidra
3.) Open Ghidra and test stuff
4.) Uninstall plugin and close Ghidra
5.) Modify code, export as a "module extension" from Eclipse
6.) Go back to step 1

Is there some trick I've missed here? Ideally I would like to not have to reload Ghidra twice for every time I modify the plugin

**Comment by ryanmkurtz** [comment]
You should only ever need to export to an extension when you are ready to distribute the final product.

**Comment by dev747368** [comment]
watching a streamer developing a Ghidra extension in a non-Eclipse env, cmd line building, launching Ghidra, installing extension.... just to test a minor change was disheartening.

**Comment by ryanmkurtz** [comment]
They shouldn't be developing an extension, they should be developing a module.  No need to go through the extension installation process during development.  We also now support running out of development mode when Eclipse isn't present (4e0fa990fb6a090937719250c67ab52e3e1ea829).  It relys on gradle having done the compilation (`gradle jar`)

**Comment by astrelsky** [comment]
> watching a streamer developing a Ghidra extension in a non-Eclipse env, cmd line building, launching Ghidra, installing extension.... just to test a minor change was disheartening.
> 

I have never used eclipse (its trash) and I still don't have to do this. As long as everything is in the classpath and the GhidraClassLoader are used everything should work.

**Comment by dev747368** [comment]
> Also nice of you to just watch them suffer :p

Heh.  I was the one doing the suffering, they were doing their thing, probably not knowing better.  Also, I'm guessing for streamers the journey is more important than the destination, and backseat driving is probably frowned on.  :smile:

**Comment by sad-dev** [comment]
I couldn't get it to play nice with Jython (maybe my PyDev is too new?) but after disabling Python I was able to get it to just run with the debug button, nice!

> watching a streamer developing a Ghidra extension in a non-Eclipse env, cmd line building, launching Ghidra, installing extension.... just to test a minor change was disheartening.

You didn't see how many times I exported the extension and uninstalled/reinstalled it in Ghidra :)
