### ISSUE TITLE
Support cross references to global symbols in decompiler view

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#508]
I have mapped a keyboard shortcut to the _"Find References To"_ action of the _SymbolTreePlugin_ as this is very useful for quickly finding the known cross references to functions and global variables. Unfortunately, this action is not supported on global symbols in the decompiler view. Since it is possible to rename and retype globals from the decompiler, I am hoping that it is possible to add the option of finding cross references directly from the decompiler as well.

**Comment by ddbb2017** [comment]
Yeah, I'd second that.

**Comment by huettenhain** [comment]
Unless I am gravely mistaken, this is fixed by https://github.com/NationalSecurityAgency/ghidra/commit/5f19814d48c028304bb3d18d0027381a07973c96. Thank you very much @ryanmkurtz!
