### ISSUE TITLE
OMF Format: Better 16/32 bit detection

### ISSUE THREAD

**Issue by Gravelbones** [NationalSecurityAgency/ghidra#5081]
When I try to import a 16 bit OMF library it suggest using 32 bit language definition for import as default.
I would like it to have a 16 bit language definition as default.

From the OMF standard the 16/32 bit definition is in SEGHEAD records.
So instead of stopping the fast scan after any comments it should stop after the first SEGHEAD.
My tests so far shows the SEGHEAD are all either 16 or 32 bit, no mixed cases.

My studies of the Query interface leaves me a bit puzzeled as how to do the selection based on 16/32 bit when doing a query.
I can't really see how that should be done. So if I could have a few pointers on that, I would be grateful.

A follow up question.
Watcom doesn't use the translator comment type, but have a special comment record telling how it was compiled.
But that record may be deep inside the library. So only by doing a full "scan" could that be detected.
But since language definition isn't used during processing (except the 16/32 bit) part, as far as I can see, would it be possible
to change the language definition in the parse phase, but before the parsed information is saved?
I see that Microsoft has a similar record type, but also sometimes have a translator record.

**Comment by ryanmkurtz** [comment]
The import language suggestions are done by entries in the various process module's "opinion" files.  The only processor that has an entry for OMF is `x86.opinion`:
```
    <constraint loader="Relocatable Object Module Format (OMF)">
      <constraint compilerSpecID="windows">
        <constraint primary="i386" processor="x86"          endian="little" size="32" />
      </constraint>
      <constraint compilerSpecID="default">
        <constraint primary="i386" processor="x86"          endian="little" size="16" />
      </constraint>
      <constraint compilerSpecID="borlandcpp">
        <constraint primary="i386" secondary="borlandcpp" processor="x86"        endian="little" size="32" />
        <constraint primary="i386" secondary="codegearcpp" processor="x86"       endian="little" size="32" />
      </constraint>
      <constraint compilerSpecID="borlanddelphi">
        <constraint primary="i386" secondary="borlanddelphi" processor="x86"     endian="little" size="32" />
      </constraint>
      ```
The primary and secondary key parameters to `public static List<QueryResult> query(String loaderName, String primaryKey, String secondaryKey)` directly map to the above XML attributes.  For many opinion entries, these keys are values from the header that represent various machine types.  In other cases (like OMF), they are just strings that we define based on some other criteria.

**Comment by Gravelbones** [comment]
Some follow up questions.
Inside the x86.opinion file there are references to various compiler specs like "windows", "borlanddelphi" and so on but the cpsec files are called names like "x86win", "x86delphi" and so on.
Is there a mapping I am missing or should the name align with the cspec file names?
Also are there to be a 16/32/64 version if the compiler generate code for all 3 types?
E.g. x86delphi_16, x86delphi_32 ...
Should windows be microsoft, visualstudio or something like that as multiple compilers can generate code for windows.

**Comment by ryanmkurtz** [comment]
> Inside the x86.opinion file there are references to various compiler specs like "windows", "borlanddelphi" and so on but the cpsec files are called names like "x86win", "x86delphi" and so on.
> Is there a mapping I am missing or should the name align with the cspec file names?

They are defined in `x86.ldefs`.


> Also are there to be a 16/32/64 version if the compiler generate code for all 3 types?
> E.g. x86delphi_16, x86delphi_32 ...

I am a bit weak in this area, but it seems there is a different `cspec` file for each bit-version, each one using the same compiler id (i.e., `windows`).



> Should windows be microsoft, visualstudio or something like that as multiple compilers can generate code for windows.

Yes, this is something we have been talking about improving.
