### ISSUE TITLE
[Feature request] Add support for installation on Windows via winget

### ISSUE THREAD

**Issue by DerekTurtleRoe** [NationalSecurityAgency/ghidra#5084]
I can't currently script installation of Ghidra in a PowerShell script using winget. Adding support for installation via winget would allow people to script installation of Ghidra, as well as add another (arguably easier way) to install Ghidra via the command-line.

The solution I would like:
Add Ghidra to the official winget repository!

I tried to add the ZIP file to a GitHub repo and automate decompression and moving the files, but this seems needlessly complex when many people could benefit from Ghidra winget support, and it should be relatively low time/effort to add support for it.

Some resources on winget:

https://github.com/microsoft/winget-cli
https://github.com/microsoft/winget-pkgs

Adding support:
https://github.com/microsoft/winget-create
https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md

**Comment by ryanmkurtz** [comment]
We have received requests to support several different package managers and installers for various platforms, and our stance has always been that we do not want to get bogged down in platform-specific package management and distribution.   Perhaps this will change one day, in which case I will reopen this ticket.
