### ISSUE TITLE
Functions: revert renamed register used as parameter back to its original name

### ISSUE THREAD

**Issue by Mistranger** [NationalSecurityAgency/ghidra#5087]
Say, I have a function that uses registers for passing parameters and in function signature I have redefined some register as a function parameter (d0_imageNum):
![image](https://user-images.githubusercontent.com/10031125/224489113-1daa9afe-c8c5-46fe-b2d3-b435003002d3.png)

It is possible to clear the redefined register name back to original (d0) at some particular point of the function?

At the image above, the D0 register represents an image number only up to red line, after which it gets assigned with a different value (blue line)
But Ghidra shows "d0_imageNum" for each D0 register usage through the entire body of  function, creating unnecessary confusion and thus making the custom parameter names not as useful as they would have be.

**Comment by astrelsky** [comment]
`Edit`->`Tool Options`->`Listing Fields` uncheck "Markup Register Variable References"

**Comment by Mistranger** [comment]
Thanks, that solved the issue.
