### ISSUE TITLE
Setting a breakpoint in Ghidra doesn't work

### ISSUE THREAD

**Issue by SickAm3nte** [NationalSecurityAgency/ghidra#5088]
Hello guys,

we are debugging a native windows application (exe). The debugging process starts fine with the option "dbgeng locally via GADP".
The app is starting. We also see in the decompile window the source code. Everything is working great, but the only thing that is not working is to set a  breakpoint. If we do set the breakpoint via the interface it is everything grey and it is labeled as disabled.
If we pause the debugger and then set a breakpoint in the interpreter with the command "bp 0x<<address>>" and then resume the program we get the following error message:

Unable to insert breakpoint 0 at 00000001`400b550e, Win32 error 0n299
    "Nur ein Teil der ReadProcessMemory- oder WriteProcessMemory-Anforderung wurde abgeschlossen."
The breakpoint was set with BP.  If you want breakpoints
to track module load/unload state you must use BU.
bp0 at 00000001`400b550e failed

Have you guys any idea what the problem is here and how to solve it?
Thanks a lot for your help :).

With kind regards,
Björn

**Comment by d-millar** [comment]
Hi Bjorn,

Am guessing from the error that the address is not in the current set of loaded addresses.  

A couple of questions:
(1) does the Modules window appear to have a valid list of Modules?
(2) is your address in the address ranges specified?
(3) can you goto that address in the dynamic listing, e.g. select the window, hit G, and enter 0x...:8 ?
(4) if all of those are true, look in the Regions window - is that address in a region with rw permissions?
(5) if not, can you set a hardware breakpoint on the address from the Interpreter window?

Typically, I've seen this message if either I've miscalculated an address (e.g. used an address from the Static listing for a module loaded somewhere else), used an address in a module that hasn't loaded yet, picked an address that isn't writable, or launched the debugger with insufficient permissions.  That said, that particular message is often frequently a red herring. 

Best,
D
