### ISSUE TITLE
Any feature similar to IDA Pro's function chunks for resolving this situation?

### ISSUE THREAD

**Issue by mostthingsweb** [NationalSecurityAgency/ghidra#5089]
I came across an IDA Pro article that mirrors a problem I am having now in my analysis of an ARM Cortex M0 firmware: https://hex-rays.com/blog/igors-tip-of-the-week-87-function-chunks-and-the-decompiler/. How would one solve this situation with Ghidra?

**Comment by mumbel** [comment]
I would look at the FindSharedReturnFunctionsScript plugin (open script manager and search for this with filter).  That sounds like what you're looking for maybe
