### ISSUE TITLE
getLastInstruction() returns first program instruction

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#5090]
**Describe the bug**
FlatProgramAPI's `getLastInstruction` acts like get first program instruction.  It is using the wrong helper function to initialize the iterator.

`getLastData` correctly uses `Address address = currentProgram.getMaxAddress();`
`getLastInstruction` uses `Address address = currentProgram.getMinAddress();`

**Environment (please complete the following information):**
 - OS: 22.04
 - Java Version: 17.0.6
 - Ghidra Version: 0773637b0c79e2080754e0ea32d25808bd8afbe9
 - Ghidra Origin: eclipse

**Comment by ryanmkurtz** [comment]
Thanks.  Either this used to wrap around, or you are the first person to ever use this.

**Comment by mumbel** [comment]
Yeah I was wondering if false would wrap around or maybe it was a LE/BE quirk (I was on BE)
