### ISSUE TITLE
Option to disable hover popup e.g. Data Type Manager -> Preview Window

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5095]
**Is your feature request related to a problem? Please describe.**
Some bug in the JDK (tested with openjdk-17, openjdk-19 to no avail) on Linux ( #4451, #5058) causes grey rectangles which do not repaint in Ghidra on various Linux installations.

![image](https://user-images.githubusercontent.com/55233728/224882922-3798af39-bf9c-42d7-855f-34717418475b.png)

**Describe the solution you'd like**
A mitigation for this issue by allowing the configuration of various hovers/popups that are likely to trigger these errors on Linux installations

**Comment by sad-dev** [comment]
For now I am running with the following hack in ``DataTypesProvider.java``

```
OperatingSystem OS = Platform.CURRENT_PLATFORM.getOperatingSystem();
boolean displayPopup = OS != OperatingSystem.LINUX;
...
			else if (type == EventType.ENTERED && displayPopup) {
				//
				// The user hovered over the link--show something useful, like the path
				//
				JToolTip toolTip = new JToolTip();
				CategoryPath path = dt.getCategoryPath();
				toolTip.setTipText(path.toString());
				PopupWindow popup = new PopupWindow(toolTip);
				popup.setCloseWindowDelay(10000);
				popup.showPopup((MouseEvent) event.getInputEvent());
			}
```

**Comment by dragonmacher** [comment]
Here is a shot in the dark at fixing this.   Run this code from a script and then see if the problem still exists:
```
		ToolTipManager ttm = ToolTipManager.sharedInstance();
		ttm.setLightWeightPopupEnabled(false);
```

**Comment by sad-dev** [comment]
> 

No luck, unfortunately
