### ISSUE TITLE
C-Parser: Can't parse typedef that defines wchar_t

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#5108]
**Describe the bug**
I'm attempting to parse an embedded SDK that references standard headers that are also packaged with the toolchain. I've added pointed the parse configuration to the appropriate include folder, but when parsing `stddef.h`, I get an error:
```
C Parser:  Encountered errors during parse.
         in /Users/usr/gcc/lib/gcc/include/stddef.h near line 434
Error: Encountered " "wchar_t" "wchar_t "" at line 820, column 13.
```
The line itself after preprocessing in `CParserPlugin.out` is just `typedef int wchar_t;` which seems like a pretty simple typedef.  I thought maybe it was some type of collision with the built-in wchar_t, but replacing it with another built-in type only sometimes causes the error, some types seem to be just fine. Regardless, I'm not quite sure what's happening here. The C-Parser help doc states:
```
It is strongly suggested that the basic data type archive for the particular platform be open in the data type manager.  
When parsing C-Header files, undefined types will be used from the archives.  
If you are unsure of your target platforms core data types, it is suggested that the "generic_C_lib" archive, which defines ANSI-C functions and data types, be open.
```
However, I have no option to close the `BuiltInTypes` to determine if this is the culprit.

**To Reproduce**
Python snippet to reproduce:
```
from ghidra.app.util.cparser.C import CParser
parser = CParser(currentProgram.getDataTypeManager())
parser.parse('typedef int wchar_t;')  # This blows up:
```

```
	at ghidra.app.util.cparser.C.CParser.generateParseException(CParser.java:9074)
	at ghidra.app.util.cparser.C.CParser.jj_consume_token(CParser.java:8944)
	at ghidra.app.util.cparser.C.CParser.Declaration(CParser.java:1080)
	at ghidra.app.util.cparser.C.CParser.ExternalDeclaration(CParser.java:905)
	at ghidra.app.util.cparser.C.CParser.TranslationUnit(CParser.java:891)
	at ghidra.app.util.cparser.C.CParser.parse(CParser.java:770)
	at ghidra.app.util.cparser.C.CParser.parse(CParser.java:754)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
ghidra.app.util.cparser.C.ParseException: ghidra.app.util.cparser.C.ParseException: Encountered " "wchar_t" "wchar_t "" at line 1, column 13.
Was expecting one of:
    <VOLATILE> ...
    "static" ...
    <CONST> ...
   </SNIP>
```

**Expected behavior**
I'd expect the parser to handle the defined type from the toolchain's stddef.h.

**Environment (please complete the following information):**
 - OS: macOS 13.2.1
 - Java Version: Corretto-17.0.6.10.1
 - Ghidra Version: 10.2.3
 - Ghidra Origin: GitHub distro

**Comment by emteere** [comment]
You are right, you can't close the Builtin data types.  They will only be used if they are needed.
Really the documentation is a bit misleading and really refers to the generic_clib or windows_ archives.

Are you are parsing into your own file archive or into the program?
You should be able to re-define types, even the built-in ones.  Will have to track that down if you can't.

The parse.parse("typedef int wchar_t;"); does blow up as you mention.

The Cparser has wchar_t defined as a keyword in the grammer, which it really shouldn't be as it isn't a keyword in c.  I'll see if we can take it out and still parse other files with it removed.  Most likely they will have some sort of DEFINE that turns off the typedef of wchar_t to get around this issue which will need to be removed as they will no longer have the defintion.

I believe the way it is parsing now, which is go to the data type archives that are open and then to the buillt-in data types will allow for the removal of the definition for wchar_t in the grammer.

I hate to suggest this, but as a workaround you could comment out the definition until we can fully track down the issue.

**Comment by bdemick** [comment]
I am parsing into an archive, so I can apply the function types to multiple projects. I’ll fire up a Ghidra build from source and give the suggested workaround a shot in the meantime. Thanks for the quick feedback (as always)! Alternatively I might try to see if I can build the SDK libraries with debug info, since I do have tooling to generate data type archives that way.

**Comment by emteere** [comment]
Parsing of any random header file can be difficult, especially with the variety of special tags compiler writers can use and the age of the header file.  Embedded toolchains can be tricky as well.

Debug information is another way to go.

If you want to automate the parse, and not use the GUI, which I recommend, there are several scripts that show you how.

CreateDefaultGDTArchiveScript is an automation of the default .gdt files we release.  I know a bit dated, but we've been holding up re-parsing for some data types changes coming and changes to the parser to fix the many bugs that have been submitted (like this one)

CreateExampleGDTArchiveScript parses newer visualstudio archives.

CreateJNIArchiveScript parses JNI header files using an open CLIB archive to make the JNI dependent on the CLIB.

CreateACR8GDTArchiveScript automates parsing of gcc toolchains AVR8 header files, which must be parsed repetitively with different architectures set.  It creates a single archive with sub-folders for each avr8 variant in the toolchain.

**Comment by bdemick** [comment]
Not sure how I had missed the existence of these examples, but thank you. Will give this a shot as well, in the meantime.
