### ISSUE TITLE
Version Tracking: Custom Correlator matches are filtered out

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5109]
**Describe the bug**
Matches from custom/user correlators are filtered out, even when selected, unless all correlators are selected.

**Additional context**
There's not really much more applicable as far as the issue template goes.

**Comment by dragonmacher** [comment]
Ignoring the misspelling, this code suggests that if you have used a `VTAbstractProgramCorrelatorFactory`, then it will get discovered by the filter dialog and added as an option.  Does your correlator appear in the filter dialog?

```
	private List<String> getKnowAlgorithms() {
		List<String> list = new ArrayList<>();

		// add the manual match correlator, which doesn't have a factory, since it is only through an action.
		list.add(ManualMatchProgramCorrelator.NAME);
		list.add(ImpliedMatchProgramCorrelator.NAME);

		List<VTAbstractProgramCorrelatorFactory> instances =
			ClassSearcher.getInstances(VTAbstractProgramCorrelatorFactory.class);
		for (VTAbstractProgramCorrelatorFactory factory : instances) {
			list.add(factory.getName());
		}
		return list;
	}
```

**Comment by astrelsky** [comment]
It is added as an option.

**Comment by dragonmacher** [comment]
This is the code that applies the filter, based  on the checkboxes:
```
		@Override
		public boolean matchesStatus(VTMatch match) {
			if (!isSelected()) {
				return false;
			}
			VTMatchSet matchSet = match.getMatchSet();
			VTProgramCorrelatorInfo info = matchSet.getProgramCorrelatorInfo();
			String matchCorrelatorName = info.getName();
			return matchCorrelatorName.equals(algorithmName);
		}
```

Based on your description, my guess is that the value of `getName()` from your `correlator factory` and the  `correlator` it returns, do not match.

Here, the `algorithmName` is provided by the factory and the value of `matchCorrelatorName` is from the match, which was provided by your correlator when you created the match.

**Comment by astrelsky** [comment]
That was definitely the problem, thank you.
