### ISSUE TITLE
A decompiler window option to "Show References To" and "Edit data types"

### ISSUE THREAD

**Issue by ddbb2017** [NationalSecurityAgency/ghidra#511]
An option in the context menu to "Show References To" when right-clicking on functions and globals in the _decompiler window_:

![Untitled-2](https://user-images.githubusercontent.com/33359889/56706651-a1790280-66ca-11e9-959d-698a64ea3bcb.png)

And also a context menu option to "Edit data types" when you click on the custom data type. Currently it works only when someone clicks on a custom data type's definition, but it would be nice if it also worked after a click on a type cast, or if it's a member of another struct. (All this will greatly simplify work in Ghidra).

Ex:

    MyDataType type;
    ....
    pCVar = (MyDataType*)&type;        //On right-click on `MyDataType` here

Or another example:

    //Say, we have a custom type
    struct MyDataType{
        MyOtherType SubType;
    };

    ....
    
    pCVar = type.SubType;        //On right-click on `SubType` here to open definition of MyOtherType struct

**Comment by dragonmacher** [comment]
The first 2 requests have been addressed for 9.1.   The last request, to open the definition of a field access, can be done in 9.1 with 2 steps, which are: 1) right-click and open the type definition (which will be the parent type) and then 2) from the structure editor, select the row for the sub-type and then right-click to open its definition.
