### ISSUE TITLE
Extend Function Call Tree pane with setting to display function namespaces

### ISSUE THREAD

**Issue by goo99x** [NationalSecurityAgency/ghidra#5115]
**Is your feature request related to a problem? Please describe.**
When browsing large C++ binaries with common class function names, it can be difficult to navigate function trees without namespaces being displayed.

**Describe the solution you'd like**
Add an option to enable namespace display in function calls tree pane. Note that this may make trees very difficult to read given the side-by-side nature of the panel. Consider also adding an option to have a stacked split layout instead of a vertical split layout.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dragonmacher** [comment]
This should be easy.

**Comment by kscieslinski** [comment]
Hi, is there any update on this one? It seems to be a super useful feature :) @dragonmacher
