### ISSUE TITLE
Extend Function Call Tree panel to hide thunks in tree

### ISSUE THREAD

**Issue by goo99x** [NationalSecurityAgency/ghidra#5116]
**Is your feature request related to a problem? Please describe.**
When viewing function call trees that have thunks as intermediate calls/xrefs, the call tree nesting can, in the worst case, double in depth. 

**Describe the solution you'd like**
Add an option to remove/filter out function thunks from the call tree, leading to shallower call trees and easier navigation.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dragonmacher** [comment]
This should be easy.
