### ISSUE TITLE
Assuming register value doesn't update references

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#512]
I've selected function, have assumed some register value, but references that were created using previous register value have not been updated in disassembler, only in decompiler.

**Comment by lab313ru** [comment]
![изображение](https://user-images.githubusercontent.com/7189309/56732433-fa49a900-6765-11e9-9a6c-d69f5632e714.png)

As you see, register A6 has a value, but references are like this register has ZERO value.

**Comment by emteere** [comment]
The analysis currently does not trigger on changes to register settings.  The thinking was you don't know when modifications are finished and the derived changes should be applied.
The decompiler information is generated on the fly based on whatever the current information.  The references are actually committed to the database so they aren't updated immediately.

There are a couple of ways to force it.
   - clear one instruction in the function
   - select the function, or even just a byte in it, and kick off analysis restricted to the selection

There should be a better way to manage the derived changes, possibly a setting.  Although placing a register setting on a function is not a common occurrence.  Usually you place the setting individually on a function, or across an entire area as a global pointer.

**Comment by KaiEpic** [comment]
There should definetly be an button which reanalyse all references. Its impossible to find all wrong refs, or its veeery time consuming.
