### ISSUE TITLE
Call graph produces incorrect edges

### ISSUE THREAD

**Issue by niconaus** [NationalSecurityAgency/ghidra#5157]
**Describe the bug**
I have a binary compiled from position independent NASM. When I generate the calls graph, either for the entire program or a single function, there are edges missing, which are clearly present in both the disassembled x86-64 code and the decompiled C code. There are also edges that should not be there.

**To Reproduce**
I generated the calls graph by moving the cursor in the function body, and using the Graph -> Calls option.

**Expected behavior**
Calls graph should be complete, based on code.

**Screenshots**
In the screenshots below, it is clear that there is a call to perrf, but it does not show up in the calls graph. In addition, there is an edge to errf, which is not present in the code.
![Scherm­afbeelding 2023-03-22 om 10 39 27](https://user-images.githubusercontent.com/5683426/226939550-3556376d-f36a-41cd-9826-c3ef369ff2e0.png)
![Scherm­afbeelding 2023-03-22 om 10 40 31](https://user-images.githubusercontent.com/5683426/226939834-4bf58a62-eb0c-44f7-b47f-55639737f71d.png)
![Scherm­afbeelding 2023-03-22 om 10 41 10](https://user-images.githubusercontent.com/5683426/226940083-c3746e9e-0aa5-4e5f-93d1-9ab7cd747a68.png)

**Attachments**
Github does not allow me to attach the binary here.

**Environment (please complete the following information):**
 - OS: macOS 13.2.1
 - Java Version: 19.0.2
 - Ghidra Version: 10.2.2
 - Ghidra Origin:official GitHub distro

**Comment by ghidragon** [comment]
Can you show a screenshot of the listing for where errf and perrf are defined? Any chance they are at the same address?

**Comment by niconaus** [comment]
![Scherm­afbeelding 2023-03-23 om 10 54 58](https://user-images.githubusercontent.com/5683426/227243115-2e559139-6e9f-48d8-b315-b54cf7fdb23a.png)
![Scherm­afbeelding 2023-03-23 om 10 54 26](https://user-images.githubusercontent.com/5683426/227243118-0c4a1774-cabb-447b-8217-6723d3315afd.png)
Does this help? They seem to be two distinct locations

**Comment by ryanmkurtz** [comment]
It helps, but it sounds like we will need your binary. Would it be possible for you to share it?  One option would be to push it to a repo and invite us to it (or me) to the repo if it's private.

**Comment by ghidra1** [comment]
The default Call graph action uses the default block model specified by the Tool option "Subroutine Block Model" which defaults to "Multiple Entry".  This model is not well suited for graphing but can be useful for identifying entangled code.  A better suited block model is the "Isolated Entry Model" which can be used via the "**Graph->Calls Using Mode->Isolated Entry**" menu action.  I have recommended a change to the "**Graph->Calls**" action to always use the _Isolated Entry Model_.  Unfortunately much of the function entanglement in your sample occurs with fallthrough instructions which currently prevents the use of flow-overrides (e.g., CALL_RETURN) to improve function separation.

**Comment by ghidra1** [comment]
The "Isolated Entry Model" should provide a useable graph provided the binary is fully analyzed. On the binary you provided it seem to work well for us.  Are still looking at the same graph and binary?  Here is the graph I get using master branch and initiating graph from "counter" function.
![image](https://user-images.githubusercontent.com/48333017/228049152-3ef3cc27-5ee4-4b9b-844d-a538a90a9f4c.png)

**Comment by ryanmkurtz** [comment]
We can reopen this if we determine there is a problem that needs to be fixed.

**Comment by niconaus** [comment]
Thanks for the follow-up. In your screenshot, there should not be an edge from perrf to report. In the call graph for the entire binary, there is als an edge between errf and perrf that should not be there.

**Comment by ghidra1** [comment]
There is a fall-through at 1013db from "perrf" into "report".  If the call to "error_print" is non-returning you should set the "noreturn" attribute on that function using the Edit Function action.  Once that is done the graph now looks like this.
![image](https://user-images.githubusercontent.com/48333017/228051914-d410ab15-b634-4508-8c08-b5929ed9b0f8.png)

**Comment by niconaus** [comment]
That makes a lot of sense, thank you so much for all you help! As far as I'm concerned, this issue is solved.
