### ISSUE TITLE
Feature Request: Compiling for other distributions of Linux

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5168]
**Is your feature request related to a problem? Please describe.**
The output of ``gradle buildGhidra`` is, as the documentation says, "intended only to run on the platform on which it was built.". This makes distributing builds awkward even between Linux machines.

For example, I pulled the latest commit (acb07dd) and built on a fresh Ubuntu 22.04 VM (installing gradle 7.6, openjdk-17-jdk, gcc, g++) with ``gradle -I gradle/support/fetchDependencies.gradle init`` followed by ``gradle buildGhidra``. On an Ubuntu 20.04 machine,  ``ghidraRun`` seemingly works and I am able to open the ``CodeBrowser`` tool. However, the decompiler does not work, displaying errors like ``"Decompiler: Unable to initialize the DecompilerInterface: Broken pipe"``, due to the different version of ``GLIBC``

```
./Ghidra/Features/Decompiler/os/linux_x86_64/decompile: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Ghidra/Features/Decompiler/os/linux_x86_64/decompile)
./Ghidra/Features/Decompiler/os/linux_x86_64/decompile: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Ghidra/Features/Decompiler/os/linux_x86_64/decompile)
```

As the documentation seems to imply this is expected (or at least that inter-compatibility between Linux machines isn't guaranteed), I am filing this as a F/R rather than a bug.

**Describe the solution you'd like**
A means to compile for generic Linux installations.

**Comment by topia** [comment]
As the nature of the C compiler/C library, This seems to be resolved by "compilation environment", not a feature of Ghidra.
glibc doesn't provide forward compatibility like that but provides backward compatibility.
see also: python binary extensions' manylinux efforts: https://github.com/pypa/manylinux

**Comment by ryanmkurtz** [comment]
As @topia implied, it is within your control to compile in such a way that your native binaries will run on other distros.  This is how we build the Linux native binaries for our official multi-platform release.  

Knowing all of this now, what did you have in mind for a feature request?

**Comment by sad-dev** [comment]
I guess it was more of a (dumb) question than a feature request; I was hoping to get it done without having to fiddle with say, Docker/chroot.

Thanks both for your help.
