### ISSUE TITLE
Set a Domain Controller in Ghidra Server

### ISSUE THREAD

**Issue by t0ta11ed** [NationalSecurityAgency/ghidra#5170]
Is it possible to configure Ghidra server to use a specific domain controller with domain logins? This seems to fail if it queries a domain with multiple domain controllers in different sites. We get an authentication timeout, which I suspect is related to getting all domain controller IPs back from a DNS query for the domain, but the log isn't very helpful. This server is also running sssd as well. Some of the other sites would not be accessible. 

FINEST|377304/0|23-03-27 15:20:00|INFO  Authentication callbacks requested by x.x.x.x (GhidraServer)
FINEST|377304/0|23-03-27 15:20:09|INFO  Repository server handle requested (user@x.x.x.x) (RepositoryManager)
FINEST|377304/0|23-03-27 15:21:39|INFO  Login failed (Receive timed out) (user@x.x.x.x) (RepositoryManager)

**Comment by t0ta11ed** [comment]
> @t0ta11ed I'm guessing you are using "-a1" mode.
> 
> Could you try -a4 mode (jaas), and in the jaas.conf, enable the example_ad_ldap_auth section and fix it up to conform to your needs?

I wasn't aware -a4 had that option. Thanks! However, this fails with "Login failed (Cannot bind to LDAP server)" although I am definitely using the correct name/password. It's my understanding that Ghidra will attempt to bind as the user trying to login, The DCs have CIS controls applied so this may not be allowed. The Ghidra log doesn't provide much more information so I'm still troubleshooting.  I did try using secure and non-secure LDAP ports just for giggles. FWIW, the DCs will also only accept TLS 1.2 also.

**Comment by dev747368** [comment]
The specifics of AD ldap permissions are a bit out of my grasp.  As general advice, reading the javadoc for the LdapLoginModule (on Oracle's site) might help you in matching what your local AD setup requires when authenticating.

As an additional troubleshooting step, you might want to use command line openldap tools to bind to the AD ldap server just to see if it could be done in general and what steps are required.

**Comment by t0ta11ed** [comment]
> The specifics of AD ldap permissions are a bit out of my grasp. As general advice, reading the javadoc for the LdapLoginModule (on Oracle's site) might help you in matching what your local AD setup requires when authenticating.
> 
> As an additional troubleshooting step, you might want to use command line openldap tools to bind to the AD ldap server just to see if it could be done in general and what steps are required.

The server is already joined to the domain via realm/sssd. I'm not sure if that is related to the problem. That does validate a lot of connectivity and authentication, since we can login via SSH using our domain creds. What I am missing is a reason for the failure to bind. Thanks for the help.

**Comment by dev747368** [comment]
One idea I'm looking at that might help you is to go back to using the auth algo that -a1 mode uses.  -a1 is mostly a ease-of-use wrapper around another JAAS module called com.sun.security.auth.module.Krb5LoginModule.

It requires some java properties to be set (java.security.krb5.realm and java.security.krb5.kdc) and the jaas.conf might be as simple as:

```
example_krb_auth {
	com.sun.security.auth.module.Krb5LoginModule REQUIRED
	;
};
```
and somewhere in your server.conf:
```
wrapper.java.additional.50=-Djava.security.krb5.realm=all_uppercase_whatever_you_had_for_-d<ad_domain>
wrapper.java.additional.51=-Djava.security.krb5.kdc=ip_addr_of_domain_controller
```
-a1 mode would lookup the ip address of the controller via dns srv records, but in this case you will need to provide the value yourself.
 
The only other thing the -a1 mode did was allow fixing up usernames when they were "AD_DOMAIN/username" to be just "username".

**Comment by t0ta11ed** [comment]
a4 totally fixes the domain controller connectivity issue, but alas the binding problem. I'll take a look at -a1, but I'm about to use local accounts just to get this project done. I still think it's odd that LdapLoginModule isn't logging something more meaningful.
