### ISSUE TITLE
Diffview resets after version control checkin

### ISSUE THREAD

**Issue by hl037** [NationalSecurityAgency/ghidra#5177]
**Describe the bug**
When using version control, if a diffview was opened before doing the check in, it is close, and we have to redo the diff analysis all again.

**To Reproduce**
1. Open a binary
2. Do modification
3. Save it as another program
4. Open the first one again
5. Enable version control on the first one
6. use "Tool > Program differences"
7. apply a change
8. Check in

**What happens**
The diff view disapears, only the listing of the program is visible

**Expected behavior**
The main window should stay as is, keeping the diff result

**Environment (please complete the following information):**
 - OS: any
 - Java Version: any
 - Ghidra Version: 10.2.3
 - Ghidra Origin: Archlinux community/ghidra

**Comment by dragonmacher** [comment]
This is not something we will be fixing for the foreseeable future.  For now, we recommend you do not commit to source control a binary that is being used in a diff session.
