### ISSUE TITLE
Incorrect sign extension in enum values parsed from DWARF data

### ISSUE THREAD

**Issue by blbelew** [NationalSecurityAgency/ghidra#5180]
**Describe the bug**
Ghidra improperly parses enum values from DWARF data (in an x86_64 ELF file compiled by GCC; other formats not tested). One and two-byte values with the high bit set are incorrectly sign-extended to 4-byte values when they should be zero-extended. Additionally, exporting enums to C code produces signed values in the output when they should be unsigned. 

**To Reproduce**
Compile the example C code, incorrectEnumExample.c, like

 `gcc -g -ggdb3 -o incorrectEnumExample incorrectEnumExample.c`

```C
enum E {
  v0 = 0,
  v7F = 0x7F,
  v80 = 0x80,
  vFE = 0xFE,
  vFF = 0xFF,
  v100 = 0x100,
  v101 = 0x101,
  v7FFF = 0X7FFF,
  v8000 = 0x8000,
  v8001 = 0x8001,
  vFFFE = 0xFFFE,
  vFFFF = 0XFFFF,
  v10000 = 0x10000,
  v10001 = 0x10001,
  v7F0000 = 0x7F0000,
  v800000 = 0x800000,
  v800001 = 0x800001,
  vFFFFFE = 0xFFFFFE,
  vFFFFFF = 0xFFFFFF,
  v1000000 = 0x1000000,
  v7f000000 = 0x7f000000,
  v80000000 = 0x80000000,
  v80000001 = 0x80000001,
  vFFFFFFFE = 0xFFFFFFFE,
  vFFFFFFFF = 0XFFFFFFFF
};

int main()
{
  return vFF;
}
```

Import incorrectEnumExample into Ghidra, run analysis (all default options), then view in Data Type Manager:

Data Types -> incorrectEnumExample -> DWARF -> incorrectEnumExample.c -> E

The displayed values are incorrect:
```
| Name      |      Value |
|-----------+------------|
| v80000000 | 0x80000000 |
| v80000001 | 0x80000001 |
| v8000     | 0xffff8000 |
| v8001     | 0xffff8001 |
| v80       | 0xffffff80 |
| vFFFE     | 0xfffffffe |
| vFFFFFFFE | 0xfffffffe |
| vFE       | 0xfffffffe |
| vFFFF     | 0xffffffff |
| vFFFFFFFF | 0xffffffff |
| vFF       | 0xffffffff |
| v0        |        0x0 |
| v7F       |       0x7f |
| v100      |      0x100 |
| v101      |      0x101 |
| v7FFF     |     0x7fff |
| v10000    |    0x10000 |
| v10001    |    0x10001 |
| v7F0000   |   0x7f0000 |
| v800000   |   0x800000 |
| v800001   |   0x800001 |
| vFFFFFE   |   0xfffffe |
| vFFFFFF   |   0xffffff |
| v1000000  |  0x1000000 |
| v7f000000 | 0x7f000000 |

```
These values are wrong when the underlying enum value fits into 1 or 2 bytes with the high-bit set (but not 3 byte values); Ghidra is incorrectly sign-extending these values when they should be zero-extended.

This produces incorrect code when exporting the program. When right-clicking the E enum in the Data Type Manager and clicking "Export C Header", the following incorrect enum definition is generated:

```C
  typedef enum E {
      v80000000=-2147483648,
      v80000001=-2147483647,
      v8000=-32768,
      v8001=-32767,
      v80=-128,
      vFE=-2,
      vFFFE=-2,
      vFFFFFFFE=-2,
      vFF=-1,
      vFFFF=-1,
      vFFFFFFFF=-1,
      v0=0,
      v7F=127,
      v100=256,
      v101=257,
      v7FFF=32767,
      v10000=65536,
      v10001=65537,
      v7F0000=8323072,
      v800000=8388608,
      v800001=8388609,
      vFFFFFE=16777214,
      vFFFFFF=16777215,
      v1000000=16777216,
      v7f000000=2130706432
  } E;
```

This output demonstrates a second bug, which is that Ghidra is creating signed values in the output when the input is unsigned. This exact same output is also produced if we change our enum definition to be 
```C
#include <stdint.h>
enum class E : uint32_t { ... };
```
and compile with `g++` to be explicit about the fact that our enum values are 4-byte unsigned values. 

To confirm that the underlying DWARF information is correct, we can use GDB to load and display the values, which produces the expected result:

```
 $ gdb incorrectEnumExample
 (gdb) ptype enum E
 type = enum E {v0, v7F = 127, v80, vFE = 254, vFF, v100, v101, v7FFF = 32767, v8000, v8001, vFFFE = 65534, vFFFF, v10000, v10001, v7F0000 = 8323072,
   v800000 = 8388608, v800001, vFFFFFE = 16777214, vFFFFFF, v1000000, v7f000000 = 2130706432, v80000000 = 2147483648, v80000001, vFFFFFFFE = 4294967294,
   vFFFFFFFF}
```

**Expected behavior**
Displayed enum values match those in the source and DWARF information. 

**Screenshots**
[incorrectEnumExample](https://user-images.githubusercontent.com/129456842/228974948-f94b64b5-dde0-49cb-ba8c-bb938858ab4c.png)

**Attachments**
[incorrectEnumExample.c.txt](https://github.com/NationalSecurityAgency/ghidra/files/11116448/incorrectEnumExample.c.txt)

If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: openjdk 17.0.6 2023-01-17
 - Ghidra Version: 10.2.3
 - Ghidra Origin: official GitHub release

**Comment by dev747368** [comment]
I can duplicate this (depending on the gcc version).

If you go back far enough, gcc used to emit enum values in the DWARF with an explicit sign flag, so Ghidra could clue in a bit better.  Somewhere around gcc 5 it started emitting values as DW_FORM_data<1,2,4>, which has ambiguous signage in the DWARF standard and is up to the consumer of the value to decide.  For enums at least, it appears Ghidra chose unwisely.

[Godbolt](https://godbolt.org/) really helped in this case explore what the older gcc's used to do.

**Comment by blbelew** [comment]
@dev747368, with your clue about DW_FORM_data, I started poking around at my binary, compiled with GCC 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04), then used [pyelftools](https://github.com/eliben/pyelftools/blob/master/examples/dwarf_die_tree.py) to explore the DWARF info. Slightly modifying the `die_info_rec` function in that script to print out the full `str(die)` representation, I got the following output: 

```
      DIE tag=DW_TAG_enumeration_type
      DIE DW_TAG_enumeration_type, size=16, has_children=True
          |DW_AT_name        :  AttributeValue(name='DW_AT_name', form='DW_FORM_string', value=b'E', raw_value=b'E', offset=50)
          |DW_AT_enum_class  :  AttributeValue(name='DW_AT_enum_class', form='DW_FORM_flag_present', value=True, raw_value=b'', offset=52)
          |DW_AT_encoding    :  AttributeValue(name='DW_AT_encoding', form='DW_FORM_data1', value=7, raw_value=7, offset=52)
          |DW_AT_byte_size   :  AttributeValue(name='DW_AT_byte_size', form='DW_FORM_data1', value=4, raw_value=4, offset=53)
          |DW_AT_type        :  AttributeValue(name='DW_AT_type', form='DW_FORM_ref4', value=261, raw_value=261, offset=54)
          |DW_AT_decl_file   :  AttributeValue(name='DW_AT_decl_file', form='DW_FORM_data1', value=1, raw_value=1, offset=58)
          |DW_AT_decl_line   :  AttributeValue(name='DW_AT_decl_line', form='DW_FORM_data1', value=22, raw_value=22, offset=59)
          |DW_AT_decl_column :  AttributeValue(name='DW_AT_decl_column', form='DW_FORM_data1', value=12, raw_value=12, offset=60)
          |DW_AT_sibling     :  AttributeValue(name='DW_AT_sibling', form='DW_FORM_ref4', value=261, raw_value=261, offset=61)
      
        DIE tag=DW_TAG_enumerator
        DIE DW_TAG_enumerator, size=5, has_children=False
            |DW_AT_name        :  AttributeValue(name='DW_AT_name', form='DW_FORM_string', value=b'v0', raw_value=b'v0', offset=66)
            |DW_AT_const_value :  AttributeValue(name='DW_AT_const_value', form='DW_FORM_data1', value=0, raw_value=0, offset=69)
        
        DIE tag=DW_TAG_enumerator
        DIE DW_TAG_enumerator, size=6, has_children=False
            |DW_AT_name        :  AttributeValue(name='DW_AT_name', form='DW_FORM_string', value=b'v7F', raw_value=b'v7F', offset=71)
            |DW_AT_const_value :  AttributeValue(name='DW_AT_const_value', form='DW_FORM_data1', value=127, raw_value=127, offset=75)
        
        DIE tag=DW_TAG_enumerator
        DIE DW_TAG_enumerator, size=6, has_children=False
            |DW_AT_name        :  AttributeValue(name='DW_AT_name', form='DW_FORM_string', value=b'v80', raw_value=b'v80', offset=77)
            |DW_AT_const_value :  AttributeValue(name='DW_AT_const_value', form='DW_FORM_data1', value=128, raw_value=128, offset=81)

... 
```
This matches up with what you said, about the members of the enum having `DW_TAG_enumerator` types, with a `DW_AT_const_value` of form `DW_FORM_data1`, `DW_FORM_data2`, etc. As you mentioned, the DWARF spec specifically calls out `DW_FORM_data<n>` as having unspecified signage....

**HOWEVER**, the parent `DW_TAG_enumeration_type` for the `E` enum has a `DW_AT_encoding` of 7, which is `DW_ATE_unsigned`. This should be enough info for Ghidra to determine that all the child enumerator values are unsigned.

**Comment by blbelew** [comment]
I will also note that despite the spec saying `DW_FORM_data<n>` are of unspecified signedness, GDB always treats them as unsigned - see https://github.com/bminor/binutils-gdb/blob/master/gdb/dwarf2/attribute.c, specifically [attribute::form_is_unsigned](https://github.com/bminor/binutils-gdb/blob/master/gdb/dwarf2/attribute.c#L169) and `attribute::constant_value` - so perhaps that is a safer default choice.

**Comment by blbelew** [comment]
I confirmed that if I change the enum to explicitly include a negative value, the `DW_TAG_enumeration_type` for the enum changes to have a `DW_AT_encoding` value of 5, which is `DW_ATE_signed`. This means there is enough contextual information here for Ghidra to detect the signedness of the child `DW_TAG_enumerator` values. 

Ghidra's current `makeDataTypeForEnum` and `EnumDataType` classes don't actually check the `DW_AT_encoding` field, and assume all values are always signed.

**Comment by astrelsky** [comment]
> [Godbolt](https://godbolt.org/) really helped in this case explore what the older gcc's used to do.
> 
> 

You mean Compiler Explorer. Godbolt is the authors name. (Matt Godbolt)

**Comment by blbelew** [comment]
Thank you @dev747368 and @ryanmkurtz for the quick turnaround!
