### ISSUE TITLE
'Cancel' button of 'Parsing C Files' doesn't work

### ISSUE THREAD

**Issue by laqieer** [NationalSecurityAgency/ghidra#5181]
**Describe the bug**
"Cancel" button of "Parsing C Files" doesn't work.

**To Reproduce**
1. Go to 'File -> Parse C Source...'
2. Click on 'Parse to Program'
3. Click on 'Cancel' in 'Parsing C Files' dialogue
4. Click on 'Yes' on 'Cancel?' dialogue
5. See error: it doesn't cancel parsing

**Expected behavior**
It cancels parsing.

**Screenshots**
<img width="473" alt="截屏2023-03-31 10 12 29" src="https://user-images.githubusercontent.com/8841957/229005299-a7738b41-bcbc-41e3-8da5-5a3e1e665004.png">
<img width="472" alt="截屏2023-03-31 10 13 28" src="https://user-images.githubusercontent.com/8841957/229005407-946c48d4-05af-4b1a-9aab-87d401d7ba7e.png">

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: macOS 13.2.1 (22D68)
 - Java Version: openjdk 17.0.6 2023-01-17
 - Ghidra Version: 10.2.3
 - Ghidra Origin: official GitHub distro

**Additional context**
Parsing cannot be cancelled except clicking the 'Dismiss' button to close the 'Parse C Source' dialogue itself.
<img width="472" alt="截屏2023-03-31 10 23 14" src="https://user-images.githubusercontent.com/8841957/229006868-46e0c255-69db-4310-ad7d-2b4174d6d4a2.png">

**Comment by astrelsky** [comment]
Can confirm

**Comment by emteere** [comment]
Currently the pre-processor is interrupt-able between each header file begin parsed.  Once the final C-parse is started you are right the parse does not check to the normal cancel monitor.  If you have one large header file, you really don't get a chance to interrupt the parsing.

Checking of the task monitor can be added into the parsing code.
