### ISSUE TITLE
Specify gdt files in Apply Data Archives analyzer

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#5184]
**Is your feature request related to a problem? Please describe.**
The "Apply Data Archives" analyzer always uses built-in .gdt files. I suggest it should allow us to manually specify a different gdt archive to apply. For example, it uses `windows_vs12_64.gdt` for any x64 Windows PE file, but it isn't suitable for analyzing Windows kernel drivers. Instead, I want to load a Windows kernel specific .gdt archive file, which is generated by parsing the Windows WDK headers.

**Describe the solution you'd like**
Add an option in the "Apply Data Archives" analyzer for specifying the path of a gdt file.

**Describe alternatives you've considered**
Load the .gdt file in the Data Type Manager and then run Apply Function Data Types. But it's less convenient than automatically done by the analyzer.

**Additional context**
Ghidra version: 10.3 DEV master branch 11ac896fb3bd552f82954fee60b177feb5d18e3b

**Comment by ryanmkurtz** [comment]
Closed by 5396d68128d45f54615bfa97a56b1c8c6ddccd1e
