### ISSUE TITLE
Blue text in Install Extensions dialog is hard to read in Dark Mode

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#5193]
**Describe the bug**
Some text in the "Install Extensions" dialog is deep blue in boldface. It is hard to read in Dark Mode. See the screenshot. It's better to change it to white or another light color.

**To Reproduce**
1. Set the theme to Flat Dark Theme
2. Go to File -> Install Extensions ...
3. Click any extension name
4. See the text in the bottom panel

**Screenshots**
![install extensions dark mode](https://user-images.githubusercontent.com/16713498/230060549-bf7d4704-e6ea-4d78-970a-1e233a6f4f3f.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: OpenJDK 17.0.6
 - Ghidra Version: 10.3 DEV master branch 88d0110a091c2f0c6f89699242b4a75cd691b0dd
 - Ghidra Origin: locally built

**Comment by ryanmkurtz** [comment]
Fixed by a21c2c4347366ffa334d399f2a62ca8cc4d17951
