### ISSUE TITLE
Why is there no Chinese language setting？

### ISSUE THREAD

**Issue by mutu555** [NationalSecurityAgency/ghidra#5201]
I come from China and I really like this tool. It's really powerful and easy to use. But my English proficiency is very poor, which makes me love and hate this tool. I would like to have Chinese settings:)

**Comment by ryanmkurtz** [comment]
Duplicate of #1300.  We do not have the resource to support this.

**Comment by mutu555** [comment]
> #1300 的副本。我们没有资源来支持这一点。

Sorry, I didn't take this into account. But I am very grateful to you for creating this great software.

**Comment by XVilka** [comment]
@mutu555 we do though, you can use Cutter with a Chinese UI:
- https://cutter.re
- https://github.com/rizinorg/cutter

**Comment by mutu555** [comment]
> @mutu555 we do though, you can use Cutter with a Chinese UI:
> 
> * https://cutter.re
> * https://github.com/rizinorg/cutter

Thank you for providing me with this great thing! I am not very familiar with many things from abroad, but the one you recommended is a surprise! Thanks again!

**Comment by mutu555** [comment]
> @mutu555 we do though, you can use Cutter with a Chinese UI:
> 
> * https://cutter.re
> * https://github.com/rizinorg/cutter

Thank you for providing me with this great thing! I am not very familiar with many things from abroad, but the one you recommended is a surprise! Thanks again!
