### ISSUE TITLE
gdb doesn't find the binary file, if path contains space

### ISSUE THREAD

**Issue by LNx2** [NationalSecurityAgency/ghidra#5203]
**Describe the bug**
When the path to the binary file gdb wants to load, contains spaces, the spaces don't get properly escaped and gdb fails to open the file. Trying to escape the spaces or quoting doesn't work either.

**To Reproduce**
1. Open your project file with the debugger
2. Choose under 'Debugger' to "Debug <file> in GDB locally via GADP
3. Choose a correct file path that contains spaces
4. gdb fails to load the file

**Error message**

```
Error caused by request sequence: 1
launch_request {
  path {
    e: "Inferiors"
    e: "[1]"
  }
  argument {
    name: "args"
    value {
      string_value: "/home/user/file name containing space"
    }
  }
  argument {
    name: "starti"
    value {
      bool_value: true
    }
  }
}
: java.util.concurrent.CompletionException: agent.gdb.manager.impl.cmd.GdbCommandError: <GDB/MI2 -file-exec-and-symbols /home/user/file> caused '{msg=[/home/user/file: No such file or directory.]}'

```

**Environment:**
 - OS: Ubuntu 22.04.1
 - Java Version: openjdk 17.0.6 
 - Ghidra Version: 10.2.3
 - Ghidra Origin: GitHub

**Comment by nsadeveloper789** [comment]
I just submitted a fix for this for internal review. You will have to use double quotes to enclose the name of the binary, e.g.: `"/home/user/file name containing space" arg1 arg2`.
