### ISSUE TITLE
C PreProcessor Warning no path to include (existing file in path)

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5207]
**Describe the bug**
Attempting to parse the headers [here](https://github.com/PS5Dev/PS5SDK/tree/main/include) with the attached parser profile fails. While I'm sure it should fail at the moment, the `CParserPlugin.out` file is empty. Scrolling through the very long error popup dialog I see the following warning "WARNING: No path to #include <inttypes.h> /* int64_t, etc. */    Assuming not needed!". However, this file does exist, is in the include path and was the first parsed header. Note that the "Current Include Path:" in the error popup is missing 90% of the include path.

**To Reproduce**
1. Clone https://github.com/PS5Dev/PS5SDK to acquire the headers to parse.
2. Modify the attached parser profile to correct the paths.

**Expected behavior**
No warning, all files in the include path should be considered and errors should go to `CParserPlugin.out` so they are easy to find.

**Attachments**
[ps5sdk.prf.txt](https://github.com/NationalSecurityAgency/ghidra/files/11183027/ps5sdk.prf.txt)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22621.1485]
 - Java Version: 17.0.5
 - Ghidra Version: 10.3_DEV ca9a56b5f4d51eb2fb0ab66afe801aba30836591

**Additional context**
Probably related to #3310 if there is a header limit.

**Comment by emteere** [comment]
The comment at the end of the #include <inttypes.h> might be causing the issue.  Not sure why that isn't stripped off by the PreProcessor.  It may be the changes that were made a while back to try and keep line numbers consistent.  The include occurs in the PreProcessor, so my suspicion is the parsing of the filename to the include directive, and possibly some error checking and stripping of the filename needs to be done before trying to open the file.

There isn't a limit on the number of header files, so I don't think that is it.

There are about to be quite a few changes to the CParser gui.  The includes will be split from the Options section and the files will be red if there is no path to them.  They are red now, but they aren't really checked correctly with the include paths in the options section.  These changes probably don't help with this issue.

**Comment by astrelsky** [comment]
I'm assuming that it is just re-emitting the whole line it ingested in the warning and is not actually looking for "#include <inttypes.h> /* int64_t, etc. */" as a file.

**Comment by emteere** [comment]
No, that is what it is trying to "include"

The original line in archive.h was:   "#include __LA_STDINT_H /* int64_t, etc. */"
Is causing the issue.

The Pre-processor grammar has code for processing a type of include when it doesn't follow the form **#include <>** or **#include ""**.  It does do an expand of the define which really can't be parsed easily in a grammer, since you can really to anything in a pre-processor because it is text substitution.

**Comment by astrelsky** [comment]
> No, that is what it is trying to "include"
> 
> The original line in archive.h was: "#include __LA_STDINT_H /* int64_t, etc. */" Is causing the issue.
> 
> The Pre-processor grammar has code for processing a type of include when it doesn't follow the form **#include <>** or **#include ""**. It does do an expand of the define which really can't be parsed easily in a grammer, since you can really to anything in a pre-processor because it is text substitution.

Oh, I didn't notice that. Thank you.

**Comment by ryanmkurtz** [comment]
Fixed by 3f13d99079e7fb84987a19a57a4daa2e9b1cc73e
