### ISSUE TITLE
[FEATURE REQUEST] Expose API to free memory associated with decompiled functions

### ISSUE THREAD

**Issue by epi052** [NationalSecurityAgency/ghidra#5210]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Ghidra gets killed by the OS because it ate all of the system's memory when decompiling large functions, or many small functions programmatically.

**Describe the solution you'd like**
I'd like to have an API exposed that allows me to free the memory associated with a decompiled function.

**Describe alternatives you've considered**
Currently, I'm selective in my scripts about which functions I decompile and I cache results to disk so that I can pick up from where I left off when Ghidra inevitably dies.

I've tried things like `del FUNC` in conjunction with `System.gc()`, but Ghidra won't 🎶 let it go 🎶 

**Additional context**

**Comment by sad-dev** [comment]
You need to use reflection to expose the ``Cache<Function, DecompileResults> decompilerCache`` via ``decompilerPanel.controller.decompilerCache`` and calll ``invalidate(foo)``

**Comment by epi052** [comment]
awesome, I appreciate the insight! I'll give this a try.

**Comment by ghidra007** [comment]
Can you describe how you are decompiling functions programmatically? Are you disposing of them when you are done? Perhaps you can share your scripts here so we can try to identify the issue?

**Comment by epi052** [comment]
@ghidra007 sorry for the delayed response. Here's the basics of what i'm doing

```
def get_high_function():
    options = DecompileOptions()
    monitor = ConsoleTaskMonitor()
    
    iface = DecompInterface()
    iface.toggleSyntaxTree(True)
    iface.setSimplificationStyle('decompile')
    iface.openProgram(getCurrentProgram())
    iface.setOptions(options)
    
    result = iface.decompileFunction('some_function', 60, monitor)
    return result.getHighFunction()
```
```
highfunction = get_high_function()

for op in highfunction.getPcodeOps():
    yield op
```
```
varnode = op.getInputs()[0]
call_addr = varnode.getAddress()

callee = getFunctionAt(call_addr)
```
```
for descendent in op.getOutput().getDescendants():
    inputs = descendent.getInputs()
```

My assumption is that it's the `getHighFunction` call, that chews up the memory, but i don't know that for sure. 

I've tried using `del HIGHFUNC` and calling into jython's garbage collector to no avail.

**Comment by ryanmkurtz** [comment]
Have you tried calling `iface.dispose()`?
