### ISSUE TITLE
`java.lang.IllegalStateException: No transaction is open` when creating a program from Python script

### ISSUE THREAD

**Issue by kitor** [NationalSecurityAgency/ghidra#5215]
**Describe the bug**
When I try to create a program from Python script, the following exception occurs:
```
No transaction is open
java.lang.IllegalStateException: No transaction is open
    at ghidra.framework.data.DomainObjectTransactionManager.endTransaction(DomainObjectTransactionManager.java:147)
    at ghidra.framework.data.DomainObjectAdapterDB.endTransaction(DomainObjectAdapterDB.java:359)
    at ghidra.python.PythonPluginExecutionThread.run(PythonPluginExecutionThread.java:101)
```

If I ignore the error and try to save the program, I get the error that program is busy by `ghidra.python.PythonScript`.
Using "as is" to save the program seems to work fine though. No issues after reopening it.

No such error appears if the same script is run via Script Manager.

**To Reproduce**
1. Open any project
2. Open CodeBrowser (happens both if CodeBrowser is empty and if any other program is open in that window)
3. Go to Window -> Python
4. Paste the following script:
```python
from ghidra.program.util import DefaultLanguageService
from ghidra.program.model.lang import Processor

programName = "testProgram"
cpu = Processor.toProcessor("ARM")
langSvc = DefaultLanguageService.getLanguageService()
langDescs = langSvc.getLanguageDescriptions(cpu)
langDesc = next(x for x in langDescs if x.getLanguageID().toString() == "ARM:LE:32:Cortex")
language = langSvc.getLanguage(langDesc.getLanguageID())

compilerSpecDescs = langDesc.getCompatibleCompilerSpecDescriptions()
compilerSpecDesc = next(x for x in compilerSpecDescs if x.getCompilerSpecName() == "default")
compilerSpec =  language.getCompilerSpecByID( compilerSpecDesc.getCompilerSpecID())

prog = createProgram(programName, language, compilerSpec)
```

**Expected behavior**
No transaction errors thrown.

**Environment (please complete the following information):**
 - OS: Windows 11 22H2
 - Java Version: 17.0.6
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official distro

**Comment by ryanmkurtz** [comment]
This is happening because `createProgram()` also opens and switches to the new program, changing what `plugin.getCurrentProgram()` returns:

https://github.com/NationalSecurityAgency/ghidra/blob/85cc8ee883aad9c3bede7e62a0ffb75a1238989c/Ghidra/Features/Python/src/main/java/ghidra/python/PythonPluginExecutionThread.java#L96-L103

I will work on a fix.
