### ISSUE TITLE
export patched binary Windows/PE with added section 

### ISSUE THREAD

**Issue by haai** [NationalSecurityAgency/ghidra#5226]
I have a binary in PE format with a new section containing a patch added to the memory map.
When I export the binary to PE format again the patch section is not available in the exported binary.
Is this not supported or is this there some configuration missing?

**Comment by ryanmkurtz** [comment]
This is the release note for that feature: 

> Exporter. For programs imported with the PE and ELF loaders, new exporters are available that write back to the original file layout. Any file-backed bytes that were modified by the user in the program database will be reflected in the written file (except on relocations). Writing back a modified Memory Map is not supported. (GP-786, Issue #1501, #1505, #19)

If you have added a new section, you likely added a memory block.  The export will not work with this.
