### ISSUE TITLE
AVR: LDS opcodes aren't disassembled properly according to their data size constraints

### ISSUE THREAD

**Issue by ghost** [NationalSecurityAgency/ghidra#5231]
For XMEGA(256A3).

From: https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/Atmel/data/languages/avr8.sinc
```
# AVR processors with more than 64 KiB of RAM make use of the RAMP- registers
# to act as the high bits where the X, Y, or Z registers are used, or in direct
# addressing instructions.
#
# TODO: incorporate the use of RAMPX, RAMPY, RAMPZ in the LD, ST instructions
#       ELPM, and LDS instructions use RAMPZ and RAMPD
...
@endif
# lds Rd,k   Seem to get some problems here... but 16-bit instruction isn't available on all atmega64.
#  Furthermore, it will sometimes conflict with ldd Z+q for q=0x2_
:lds RdHi,K7addr is phase=1 & ophi5=0x14 & RdHi & K7addr { 
  RdHi = K7addr;
}
```

![image](https://user-images.githubusercontent.com/8112328/232837682-5ea61c07-a578-4d5a-90b5-0863273784c2.png)

Whereas the correct disassembly should be:

![image](https://user-images.githubusercontent.com/8112328/232837757-9c19c2bc-f73b-4c72-ad08-55045e300b57.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/8112328/232837757-9c19c2bc-f73b-4c72-ad08-55045e300b57.png)

A code sample facilitated by a colleague:

```
#include <stdint.h>

void foo(uint16_t param1, uint16_t param2)
{
    uint16_t aa;
    uint32_t dummy1[8];
    uint16_t bb;

     aa = param1;
     bb = param2;
}

```

It can be easily verified via godbolt or local compilation and disassembly via objdump.

We are looking forward to solving these as manual disassembly via objdump + dd from AVR flat binaries is very time consuming.

 - Java Version: [e.g. 11.0]
 - Ghidra Version: latest stable as of today
 - Ghidra Origin: official release

**Comment by GhidorahRex** [comment]
We don't currently have a definition for the ATtiny series. We should definitely add that and make sure the other AVR processors don't see LDS/STS.

In the meantime, you can modify the avr8.sinc file and delete the constructors until this gets addressed.

**Comment by GhidorahRex** [comment]
> Quick edit: what modifications do you suggest specifically for the SINC definition?

Remove/comment out the lines 910-912:
```
#:lds RdHi,K7addr is phase=1 & ophi5=0x14 & RdHi & K7addr { 
# RdHi = K7addr;
#}
```

And probably also at 1167 for good measure:
```
#:sts K7addr, RdHi      is phase=1 & ophi5=0x15 & RdHi & K7addr { 
#	K7addr = RdHi;
#}

see attached.
[avr8.sinc.txt](https://github.com/NationalSecurityAgency/ghidra/files/11265785/avr8.sinc.txt)

```
