### ISSUE TITLE
Missing function in `ghidra.app.util.bin.format.objecticeC.ObjecticeC1_Utilities` in version 10.2.3

### ISSUE THREAD

**Issue by michel-jubke** [NationalSecurityAgency/ghidra#5233]
When upgrading from version 10.1.2 to 10.2.3 some of my self written loaders cause problems due to the absence of the `createPointer(Program, Address)` function in `ghidra.app.util.bin.format.objecticeC.ObjecticeC1_Utilities` (part of the `Base.jar` archive).  
The function was there in 10.1.2 and is now missing, but it is still listed in the [Ghidra API](https://ghidra.re/ghidra_docs/api/ghidra/app/util/bin/format/objectiveC/ObjectiveC1_Utilities.html).

**Comment by astrelsky** [comment]
> When upgrading from version 10.1.2 to 10.2.3 some of my self written loaders cause problems due to the absence of the `createPointer(Program, Address)` function in `ghidra.app.util.bin.format.objecticeC.ObjecticeC1_Utilities` (part of the `Base.jar` archive).  
> The function was there in 10.1.2 and is now missing, but it is still listed in the [Ghidra API](https://ghidra.re/ghidra_docs/api/ghidra/app/util/bin/format/objectiveC/ObjectiveC1_Utilities.html).

That link is out of date. It is not the official documentation. The official documentation is distributed with ghidra.
