### ISSUE TITLE
Apply Function Signatures to renamed Labels which match windows API call's

### ISSUE THREAD

**Issue by irfan-eternal** [NationalSecurityAgency/ghidra#5234]
**Is your feature request related to a problem? Please describe.**
An other Paid decompiler has this very useful feature  i.e. when a function name matches a windows API it automatically applies it's function signature. I searched in the web if Ghidra has something like this. But I was not able to find. If this feature is there, It will help in many ways like identifying stack depth, stack variable reuse, better decompiled code etc..

**Describe the solution you'd like**
If  a function name matches a windows API Ghidra should automatically apply it's function signature.
![image](https://user-images.githubusercontent.com/107915402/233073360-ed23afba-1c86-416a-90e6-23e3dbbcd925.png)
Above image is an Example here the  Label GetSecurityInfo is a Windows API. it will be great if we can apply Function Signature for this

**Describe alternatives you've considered**
I checked if this Feature  is already  existing using Multiple Search Engines and also [posted](https://www.reddit.com/r/ghidra/comments/12fulq6/apply_function_signatures_to_renamed_labels_which/) in Reddit's Ghidra  community. But i was not able to find an answer. Which let me here to post it as a feature request

**Additional context**
Another Example
![image](https://user-images.githubusercontent.com/107915402/233076525-3f102c2d-b733-4a23-b3c7-74b212647ba2.png)

**Comment by astrelsky** [comment]
Set the type of `GetSecurityInfo` to `GetSecurityInfo *`

**Comment by irfan-eternal** [comment]
@astrelsky Sorry I know that my comment was too long. What I need now in short is indirect calls to Windows API using registers in Disassembly should use __stdcall calling convention. so that the stack depth are changed automatically

**Comment by astrelsky** [comment]
> @astrelsky Sorry I know that my comment was too long. What I need now in short is indirect calls to Windows API using registers in Disassembly should use __stdcall calling convention. so that the stack depth are changed automatically

This should already occur automatically. Usually when I see this the issue is elsewhere.

**Comment by irfan-eternal** [comment]
Thanks @astrelsky . My Decompiled code is much better now
