### ISSUE TITLE
Decompiler re-ordering assignment

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#5237]
I'm playing with a Ghidra/Processor definition and things are working surprisingly well so far, but I am seeing the decompiler re-ordering statements from the disassembly.  For the most part, if it's just assignments, I don't really care, but it seems to be moving an assignment above preceding function calls.  This is a particularly annoying movement:

  cnf.raRnti = (ulong)raRnti;
  memset(&cnf,0,0x18);

Where the function first clears out the "cnf" structure, then populates various fields.  The call to memset() is the very first thing that the function does, and the assignment to cnf.raRnti is nearly the last operation (before another function call to send the built message).

I'm sure that I'm just missing some information in one of the Ghidra/Processor/* spec files, but I haven't been able to find what it is..  Something in the .cspec that says that memory is altered?  Something in the .sinc that says that the instruction may affect memory?  It seems it's got to be there...  somewhere..

**Comment by ghidracadabra** [comment]
In the cspec, do you have the appropriate space marked as global and an entry for the stack pointer?  Cf. [here](https://github.com/NationalSecurityAgency/ghidra/blob/7891d2611549ec57fc81b13e9205ce37bd42b2d4/Ghidra/Processors/x86/data/languages/x86-64-gcc.cspec#L26)

**Comment by marcushall42** [comment]
Looks like it to me..  Some parts of the .cspec file are a little magic and I don't understand all of the implications of things.  And this file was inherited with the base code I started with, but it does seem to follow the same pattern as the file you pointed to -- as far as I can see.

[xtensa.cspec.txt](https://github.com/NationalSecurityAgency/ghidra/files/11323192/xtensa.cspec.txt)

**Comment by RootCubed** [comment]
I have been able to reproduce this issue too, with the default PowerPC 32-bit big endian processor definition. Seems like a decompiler bug rather than a processor definition bug. (Compiled .o file for easy reproduction: [reorder.zip](https://github.com/NationalSecurityAgency/ghidra/files/11326010/reorder.zip))

```assembly
.text

stwu      r1, -0xc(r1)
addi      r14, r3, 1
addi      r3, r1, 8
bl        func
stw       r14, 0x8(r1)
addi      r3, r1, 8
bl        func
addi      r1, r1, 0xc
blr  

func:
blr
```

This decompiles to
```c
void FUN_00010000(int param_1)

{
  int local_4;
  
  local_4 = param_1 + 1;
  FUN_00010024(&local_4);
  FUN_00010024(&local_4);
  return;
}
```

whereas it should be
```c
void FUN_00010000(int param_1)

{
  int local_4;
  
  FUN_00010024(&local_4);
  local_4 = param_1 + 1;
  FUN_00010024(&local_4);
  return;
}
```

**Comment by ghidracadabra** [comment]
@RootCubed OK, I can reproduce this.  Thanks for the example!  We'll take a look.
