### ISSUE TITLE
fails to start due java issue - in VM's

### ISSUE THREAD

**Issue by schnedann** [NationalSecurityAgency/ghidra#5244]
**Describe the bug**
ghidra fails to start due java issue inside of VM's (virtualbox)
Guest OS: Archlinux (see bugreport https://bugs.archlinux.org/task/75233)
Host OS: Archlinux + Windows 10
Computers: various Intel CPUs from iCore Gen 1 to recent ones, AMD Ryzen Gen2

also different versions of the java enviroment
 archlinux-java status
Available Java environments:
  java-11-openjdk
  java-17-openjdk (default)
  java-19-openjdk
...
All tested and even older ones --> all same behaviour as far as I can say

starting ghidra (in shell) gives:
ghidra
Exited with error. Run in foreground (fg) mode for more details.

running in debug mode:
/opt/ghidra/support/ghidraDebug
Listening for transport dt_socket at address: 18001
openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)
Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
at utility.module.ModuleUtilities.findModuleRootDirectoriesHelper(ModuleUtilities.java:89)
at utility.module.ModuleUtilities.findModuleRootDirectoriesHelper(ModuleUtilities.java:97)
at utility.module.ModuleUtilities.findModuleRootDirectoriesHelper(ModuleUtilities.java:97)
at utility.module.ModuleUtilities.findModuleRootDirectories(ModuleUtilities.java:81)
at utility.module.ModuleUtilities.findModuleRootDirectories(ModuleUtilities.java:114)
at ghidra.GhidraApplicationLayout.findGhidraModules(GhidraApplicationLayout.java:155)
at ghidra.GhidraApplicationLayout.<init>(GhidraApplicationLayout.java:70)
at ghidra.GhidraLauncher.initializeGhidraEnvironment(GhidraLauncher.java:99)
at ghidra.GhidraLauncher.launch(GhidraLauncher.java:48)
at ghidra.Ghidra.main(Ghidra.java:47)

Additional info:
pacman -Qi ghidra
Name : ghidra
Version : 10.1.4-1
Beschreibung : Software reverse engineering framework
Architektur : x86_64
URL :[ https://ghidra-sre.org/](https://ghidra-sre.org/)
Lizenzen : Apache
Gruppen : Nichts
Stellt bereit : Nichts
Hängt ab von : java-environment>=11 bash
Optionale Abhängigkeiten : python2: Python feature [Installiert]
pam: GhidraServer support [Installiert]
Benötigt von : ghidra-extension-ghidra-cpp-class-analyzer-git
Optional für : Nichts
In Konflikt mit : Nichts
Ersetzt : Nichts
Installationsgröße : 916,07 MiB
Packer : Frederik Schwan <[freswa@archlinux.org](mailto:freswa@archlinux.org)>
Erstellt am : Sa 21 Mai 2022 00:26:54 CEST
Installiert am : Do 30 Jun 2022 15:38:48 CEST
Installationsgrund : Ausdrücklich installiert
Installations-Skript : Nein
Verifiziert durch : Signatur

Steps to reproduce:
try to start ghidra
from gui - "nothing" happens
from cli - error message(s) as stated above

**Expected behavior**
just a normal start of ghidra

--> Note: the very same version of ghidra on the very same OS on the very same computer works 100% fine outside the VM!
--> Also: it used to work inside the VM before, I don't use ghidra that often, but at a certain point in time before mid of July 2022 it stopped working.

**Environment (please complete the following information):**
 - OS: Archlinux (ever since mid of July 2022)
 - inside VM (virtualbox)
 - Ghidra Version: first tested 10.1.4-1, current 10.2.3-1
 - Ghidra Origin: Archlinux repository - https://archlinux.org/packages/community/x86_64/ghidra/

**Comment by ryanmkurtz** [comment]
We don't produce this Arch Ghidra distribution.  If there is a problem launching [an official Ghidra release](https://github.com/NationalSecurityAgency/ghidra/releases) in your environment, we'll be happy to help you track down the problem.

**Comment by schnedann** [comment]
Guess what: Its just a normal Ghidra. Also: I would guess: it also fails with other Distributions.
And as a last Point: I am an 'ordinary user'. I just reported a bug. If you have any questions if and how the package on arch differs from what you call "[an official Ghidra release](https://github.com/NationalSecurityAgency/ghidra/releases)", please contact the Arch package's maintainer (by the way, you can look up how the package is build easyly here https://github.com/archlinux/svntogit-community/blob/packages/ghidra/trunk/PKGBUILD). Thanks.

I tried to supply all the information I have, and I do not use any other distribution, so I can't provide if it is a problem with the arch package (If you prove, the arch maintainer will start working but it's their policy to only fix such things) or if it is a general problem, You are in charge.

Also note: I have reported this bug 6 Month ago in the Arch bugtracker first - see my initial post - and the arch maintainer closed this bug with "works for me, report upstream". So I did. You are upstream. If you think this is wrong, please contact the maintainer in Arch directly, I am not a middleman.

**Comment by ryanmkurtz** [comment]
> Guess what: Its just a normal Ghidra.

Great, it sounds like I might be able to help you!  A couple questions/things to try to help us solve this issue:

1. Did you or something else change the file permissions of any of the files/folders in the Ghidra installation?
2. Are you running on a non-standard filesystem?
3. Can you please install (unzip) our official Ghidra 10.2.3 release [(download link)](https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.2.3_build/ghidra_10.2.3_PUBLIC_20230208.zip) into your $HOME directory and confirm it does not launch?  If it does not, can you paste in the exception again?  This will help me know I am debugging the same exact version you are running (and the line numbers will match up with what i'm looking at).

Thanks!

**Comment by ryanmkurtz** [comment]
I am able to reproduce this by removing read and execute permissions from one of Ghidra's module directories.

**Comment by ryanmkurtz** [comment]
Sounds good.  I am going to improve the error message that Ghidra outputs in this scenario, and consider that the fix for this ticket.  I think that's the best the Ghidra team can offer for a situation like this.
