### ISSUE TITLE
VLE branch using cr other than cr0 is not shown

### ISSUE THREAD

**Issue by amatus** [NationalSecurityAgency/ghidra#5246]
**Describe the bug**
VLE branch using cr other than cr0 is not shown. For example:
```
           0000e2a0 7a 0a 00 48     e_bne      LAB_0000e2e8
```
should be shown as `e_bne cr2,LAB_0000e2e8` because cr2 is used in this instruction.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: openjdk 17.0.6
 - Ghidra Version: 10.2.3
 - Ghidra Origin: github release

**Comment by GhidorahRex** [comment]
A somewhat annoying display bug. We don't seem to display the CR for ANY CR, including CR0.

We need to add the BI32 to the display, in particular the CR portion ,`BI_CR_VLE`. But only if we're using a conditional that depends on the CR, as opposed to the counter conditionals.
