### ISSUE TITLE
VLE e_sthu incorrectly displayed as sthu

### ISSUE THREAD

**Issue by amatus** [NationalSecurityAgency/ghidra#5247]
**Describe the bug**
VLE e_sthu incorrectly displayed as sthu despite having different encodings. For example:
```
           18 07 05 02     sthu       r0,0x2(r7)
```
should be `e_sthu r0,0x2(r7)`.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: openjdk 17.0.6
 - Ghidra Version: 10.2.3
 - Ghidra Origin: github release

**Comment by GhidorahRex** [comment]
Very minor fix. Need to add `e_` before the VLE constructor mnemonic.
