### ISSUE TITLE
All of Analysis seems to be....gone?

### ISSUE THREAD

**Issue by preland** [NationalSecurityAgency/ghidra#5250]
**Describe the bug**
Whenever loading an imported file with CodeBrowser, the "Analysis" menu option is not present. I am not sure at all what causes this. I was able to get Ghidra to work properly when I first ran it, but I have not been able to get it to work properly since, even when using the same exact file and project that worked previously. Ghidra was not updated or changed between the sessions.

**To Reproduce**
(Note: I am almost positive following these directions worked at first, but they have not worked since my first attempt)
1. Create a new project (non-shared)
2. Import a file
3. Set whatever options you want here, **it weirdly won't change later behavior at all**, whether it is the default or something completely arbitrary and nonsensical
4. Open the imported file by double clicking
5. No Analysis option in menu
**Expected behavior**
The analysis menu bar function, as well as other items, would be present

**Screenshots**
<img width="1392" alt="Screenshot 2023-04-21 at 8 50 27 PM" src="https://user-images.githubusercontent.com/89992615/233755593-1892135b-6d7b-4f23-b1dc-9b9cd5d22792.png">

Above is a screenshot of what the layout typically looks like.

**Attachments**
[crackme0x00.exe.zip](https://github.com/NationalSecurityAgency/ghidra/files/11300018/crackme0x00.exe.zip)
This is the file loaded in the screenshot

[misaka.zip](https://github.com/NationalSecurityAgency/ghidra/files/11300022/misaka.zip)
This is the file that I was able to successfully load at first, but have been unable to properly load since.
**Environment (please complete the following information):**
 - OS: MacOS 13.1
 - Java Version: 19.0.1
 - Ghidra Version: 10.2.3
 - Ghidra Origin: It was initially sourced directly from GitHub, until the issue began occurring. I then switched over to the homebrew distro, which has the same exact issue as the GitHub distro
**Additional context**

I am just starting out with using Ghidra, so I will admit that there is a fair chance that I am simply missing some very important information. I will say that I did my best to look elsewhere for solutions, but I couldn't find anything about this issue. Any help or advice is welcome.

**Comment by mumbel** [comment]
close the code browser window.

In the front-end window:  
`Tools` -> `Delete Tool` -> `CodeBrowser`
`Tools` -> `Import Default Tools` -> check CodeBrowser.tool -> press OK

Open code browser window, see if that fixed it or not

**Comment by preland** [comment]
This worked for me, thanks!

**Comment by aidanhasaknife** [comment]
If that worked, please close this issue.

**Comment by preland** [comment]
👍

**Comment by preland** [comment]
👍
