### ISSUE TITLE
Overriding variadic function to remove all extra parameters now fails to size parameters correctly

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#5268]
**Describe the bug**
Since commit 7891d2611, correcting parameters to variadic functions is not interpreting them correctly under apps using `x86-16.cspec`.

Eg. on opening my project and looking at a representative function I saw this:
```
void __cdecl16far Lm_DecayAdjust(long param_1)
{
   int unaff_BP;
   int iVar1;
   DgnLanguageModel_0xc2_t *pDVar2;
   
   iVar1 = unaff_BP + 1;
   pDVar2 = GetAllowableLangModel(*(IDX_ONE_BASED *)(param_1 + 6));
   if ((pDVar2 == NULL) || (pDVar2->pLmAdjust_0xbe == NULL)) {
      ReportFailure_0e38("sdlm.cpp",0x3b9,"No valid LM Adjustment module\n",(int)pDVar2,
                         (int)((ulong)pDVar2 >> 0x10),iVar1);
   }
   LmAdjust::RecalcDecayAndTieScale(pDVar2->pLmAdjust_0xbe);
   return;
}
```
after an attempt to fix this by overriding the signature (changing from `void ReportFailure_0e38(LPCSTR pszCategory, int iErrorLoc?, LPCSTR pszErrorReason, int, int, int)` to `void ReportFailure_0e38(LPCSTR pszCategory, int iErrorLoc?, LPCSTR pszErrorReason)`) using the same calling convention (`__cdecl16far`) Ghidra now produces:
```
void __cdecl16far Lm_DecayAdjust(long param_1)
{
   DgnLanguageModel_0xc2_t *pDVar1;
   
   pDVar1 = GetAllowableLangModel(*(IDX_ONE_BASED *)(param_1 + 6));
   if ((pDVar1 == NULL) || (pDVar1->pLmAdjust_0xbe == NULL)) {
      ReportFailure_0e38((LPCSTR)0x34f81038,(int)"User_Iterate" + 10,(LPCSTR)0x35da03b9);
   }
   LmAdjust::RecalcDecayAndTieScale(pDVar1->pLmAdjust_0xbe);
   return;
}
```
It is looking like Ghidra is now treating all 2-byte values as offsets to addresses (relative to the data segment `DS`)!

**To Reproduce**
1. Load the unzipped attached dump (from the Decompile menu `Debug Function Decompilation`
2. Override the call (as above)
3. See error

**Expected behavior**
Recognition of numbers vs pointers and correct interpretation of parameters.

**Screenshots**
N/A

**Attachments**
[dragon_Lm_DecayAdjust.zip](https://github.com/NationalSecurityAgency/ghidra/files/11325049/dragon_Lm_DecayAdjust.zip)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.3.1
 - Ghidra Version: [e.g. 10.3-DEV
 - Ghidra Origin: locally built - commit 7891d2611

**Additional context**

**Comment by Wall-AF** [comment]
Found the issue, in class `FunctionPrototype.java` replace the line:
https://github.com/NationalSecurityAgency/ghidra/blob/8dd584c9bca0fadae91ee0eecbcade178e2c2e1b/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/FunctionPrototype.java#L91
with:
`modelname = proto.getCallingConventionName();`

**Comment by Wall-AF** [comment]
Also, I can only assume that maybe the upgrade process isn't quiet correct, as all the function prototypes under `auto_proto` folder (and elsewhere) have been given the default calling convention `__stdcall`!

**Comment by ghidra1** [comment]
@Wall-AF the zip you supplied only contains an XML file which is inadequate for import.  Could you please provide a GZF export instead.

**Comment by Wall-AF** [comment]
I rolled back to commit 8242c31c4a8 and also had to zip the gzf!  [DRAGON_8242c31c4a8.zip](https://github.com/NationalSecurityAgency/ghidra/files/11334341/DRAGON_8242c31c4a8.zip)

**Comment by ghidra1** [comment]
Could you please confirm that the GZF was produced while in a good state prior to the upgrade.

**Comment by ghidra1** [comment]
It appears your gzf has already been subjected to the upgrade.  Could I get a copy prior to the upgrade if at all possible so I can verufy the upgrade did not cause any issue.

**Comment by ghidra1** [comment]
> Found the issue, in class `FunctionPrototype.java` 

Good find!  Thanks.  Will put fix in.

**Comment by Wall-AF** [comment]
Mmm, sorry, I don't seem to be able to go back despite taking a copy of the `*.rep` folder beforehand!

**Comment by astrelsky** [comment]
Is there any chance that this would have affected all indirect function calls (to a typed function pointer) as well?

**Comment by ghidra1** [comment]
> Also, I can only assume that maybe the upgrade process isn't quiet correct, as all the function prototypes under `auto_proto` folder (and elsewhere) have been given the default calling convention `__stdcall`!

I would need to see this occur in a sample during upgrade.  I will attempt to reproduce.

**Comment by astrelsky** [comment]
> Is there any chance that this would have affected all indirect function calls (to a typed function pointer) as well?

This was indeed the cause and 6799c19e19fa28f43fe2e31480a232edc0f74887 did fix it. The function pointer in question had a user defined `__gocall` convention for go.
