### ISSUE TITLE
Broken PascalStringDataType

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5272]
**Describe the bug**
The string length for PascalStringDataType is calculated incorrectly. The first 4 bytes are being read for the length of the string but the string is starting after the first 2 bytes.

**To Reproduce**
1. Write the following bytes to a file and import it as Data, LE, 64.
   `00 03 63 64 73 69 79 76 69 75 66 6E 73 76 00 76 67 66 62 6E 76 6D 64 6B 6D 62 66`
2. At the start of the data attempt to create a `PascalString`.
3. See failure to create the string.
4. Create an int at the start of the data, patch the data to be `3` and then clear it.
5. Attempt to create a `PascalString` at the start of the data.
6. See error.

**Environment (please complete the following information):**
 - Ghidra Version: 10.3_DEV a27250f459266a658e36c26ec611a4bd8da918eb

**Additional context**
I am on the latest commit but the problem definitely started sooner. I just didn't look hard enough to notice it was a bug.

**Comment by dev747368** [comment]
@astrelsky maybe I'm missing something from your description, you specified LE, but the bytes you gave in your example for the length field (00 03) would evaluate to 0x300 (ie. 768).

When I swapped the first 2 bytes around (00 03 -> 03 00), I get the string "cds".

**Comment by astrelsky** [comment]
> @astrelsky maybe I'm missing something from your description, you specified LE, but the bytes you gave in your example for the length field (00 03) would evaluate to 0x300 (ie. 768).
> 
> When I swapped the first 2 bytes around (00 03 -> 03 00), I get the string "cds".

🤦‍♂️ yes you are right, my mistake... again. I think this is the third time now I've submitted an issue for pascal strings and they were fine.

So now the bigger question is why the hell are the golang `runtime.interfacetype`'s `pkgpath` field string using a big endian size prefix.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/46897303/fc446a96-7fbe-40bf-8a73-573fadb8a57d)


Unfortunately I now have more questions then answers but at least I know what was going on there now. Thank you.



So I just had the wonderful idea of creating a `TypeDefDataType` to a `PascalString` and changing the endianess setting. Unfortunately it seems that a typedef is not allowed on a dynamic data type.

**Comment by dev747368** [comment]
@astrelsky I think I can help you out with that.  If you look at GoName.java, you can follow the logic in readStructure().

Basically, its a flag byte, a uleb128 length, then the variable length char array.

**Comment by astrelsky** [comment]
> @astrelsky I think I can help you out with that. If you look at GoName.java, you can follow the logic in readStructure().
> 
> Basically, its a flag byte, a uleb128 length, then the variable length char array.

Oh, that's annoying. Thank you. I was going to hack up a dynamic data type to deal with this and stick it in my jar of nonsense 😅. I get bothered by unmarked up data, especially strings.

I'll take a closer look at the `StructureReader` stuff when I need this again and have a clearer mind. It's not immediately how to use it but I suspect it wasn't exactly designed to be used outside of the go parsing stuff.
