### ISSUE TITLE
ELF loader discarding small zeroed segments not backed by any section

### ISSUE THREAD

**Issue by CmP-lt** [NationalSecurityAgency/ghidra#5273]
**Description of issue**
Current behavior of `ElfProgramBuilder` (illustrated with code fragments below) rests on assumption that when sections data is present, used segments consisting of only zero bytes with size of less than 256 bytes will be within a section and if they are not, they can be safely discarded. But in practice the above is not guaranteed, sections data may be incomplete or altered, in which case such segments may get discarded even if they are used.

**Proposed changes**
To adjust `ElfProgramBuilder`'s behavior to not discard segments that are specified by program headers with `p_type` field having `PT_LOAD` value.

**Context**
https://github.com/NationalSecurityAgency/ghidra/blob/80ccdadeba79cd42fb0b85796b55952e0f79f323/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/ElfProgramBuilder.java#L73-L76
https://github.com/NationalSecurityAgency/ghidra/blob/80ccdadeba79cd42fb0b85796b55952e0f79f323/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/ElfProgramBuilder.java#L324-L345

**Comment by ghidra1** [comment]
If section data is incomplete the loader will fill the remainder of the section with zeros regardless of file content.  This is the current convention for the majority of loaders, although this may not have been true in the past.  I will look into adding an ELF Lloader option to preserve all loaded segment data.

**Comment by CmP-lt** [comment]
> If section data is incomplete the loader will fill the remainder of the section with zeros regardless of file content.
With incomplete section data I meant when there is separate program header that describes loadable segment, but there isn't any section that includes (or is within) that segment's address range. It's not a typical encounter, but it's also not an issue as far as loaders are concerned (if my understanding of that is correct).

> I will look into adding an ELF Lloader option to preserve all loaded segment data.
That should work for cases that fall under description from the initial post, thank you.

Though, in general, is this heuristic of Ghidra's ELF loader to discard small zeroed segments (or segment parts) correct, considering that in principle any part of bytes loaded according to program headers may be used (regardless of what section headers have or don't have)?

**Comment by CmP-lt** [comment]
To answer my question above, the heuristic doesn't cause any harm for most cases in practice, but it may discard used segments or segment parts when section headers are modified or partially removed (for example, in attempt to confuse static analysis tools). Considering such possibility, wouldn't it be reasonable for Ghidra's ELF loader to prioritize program headers over section headers for deciding what to keep and what to discard?

**Comment by ghidra1** [comment]
The section headers do not influence what is kept or discarded other than to cause fragmentation of load segments.    Small load segments are frequently related to alignment only.  I would agree the zero-discard threshold of 255 bytes is probbaly too large.  In either case it would seem reasonable to make this an import option that could be changed or eliminated at the time of import.  Without the discard mechanism, the normal cases can have many useless segment blocks that clutter the memory map and program tree.

**Comment by CmP-lt** [comment]
I agree that having import option for this is reasonable. My questions above were to doubt the default behavior. If in most cases not discarding small zeroed segment parts indeed leads to many useless entries in memory map, then I can agree that having the heuristic enabled by default is more reasonable.

**Comment by ghidra1** [comment]
@CmP-lt yours is the first complaint in many years.  I am sure mechanism was not used many more complaints would come in regarding all the superfluous "unnamed" memory blocks.  That is why it was initially added, although, I don't recall the reasoning in the default threshold.
