### ISSUE TITLE
Show value of enum when hovering over it in decompiler view

### ISSUE THREAD

**Issue by madebr** [NationalSecurityAgency/ghidra#5286]
**Is your feature request related to a problem? Please describe.**
When working in the decompiler view, it is sometimes interesting to know what value a certain enum value really has.

Currently, you need to look up the type of the enum and open it in the enum editor.
Then you need to look for the name.
This process takes some time and can bring people out of their thought process.

**Describe the solution you'd like**

I think there are 2 possible solutions, which are both useful:
- show the value of the enum value in a little pop-up window. The window should disappear when the mouse moves to somewhere else.
- or, when right-clicking on the enum value, add an option to navigate to the enum value in the enum editor

**Describe alternatives you've considered**
(see above)

**Additional context**
none

**Comment by caheckman** [comment]
Hovering on a token representing an enum value, in most contexts, will give a pop-up window displaying the underlying constant value. if you right-click on the token and select "Edit Data Type", you get a dialog displaying the whole enum.

The one exception is if the enum value is part of a "case" label.  Hovering on these doesn't work currently.  We'll consider this a request to extend the hover functionality to these tokens.
