### ISSUE TITLE
Let GhidraFileChooser's CurrentDirectory can be edit

### ISSUE THREAD

**Issue by qux-bbb** [NationalSecurityAgency/ghidra#5291]
**Is your feature request related to a problem? Please describe.**
The GhidraFileChooser's CurrentDirectory should be edit.  

**Describe the solution you'd like**
`currentPathTextField.setEditable(true);`  

**Describe alternatives you've considered**
No.  

**Additional context**
I create a pr: https://github.com/NationalSecurityAgency/ghidra/pull/5290 , but "Merging is blocked".

**Comment by qux-bbb** [comment]
Actually we don't need to consider this issue, because we can change path by "File name" area.  
![thatsfine](https://github.com/NationalSecurityAgency/ghidra/assets/18598419/aaa1df76-d8c6-400e-9372-a7f144ad7a9d)

**Comment by qux-bbb** [comment]
@ryanmkurtz Thank you!

**Comment by ryanmkurtz** [comment]
Normally i'd happily take the credit for other people's work, but since @dragonmacher will probably see this, i should probably redirect the thanks to him since he implemented it.
