### ISSUE TITLE
How can I patch a .exe

### ISSUE THREAD

**Issue by peleon02** [NationalSecurityAgency/ghidra#530]
I'm trying to patch  .exe, when I have hex edited, and I press O, I'm not able to save it as exe binary, if I select binary is saved as test.exe.bin, and I cannot get it to work

**Comment by saruman9** [comment]
`test.exe.bin` file is actually `test.exe`, you should rename it. See also #19.

**Comment by ryanmkurtz** [comment]
Duplicate of #19.  You have to import the file as a raw binary if you want the export to still run.  We currently do not support going from a loaded memory image back into runnable file.

**Comment by Ristovski** [comment]
@ryanmkurtz Does "currently" mean this will become a feature somewhere down the line?

**Comment by eLeCtrOssSnake** [comment]
Still a real bug.............

**Comment by Kushagra3911** [comment]
Select the PE option,PE stands for Portable Executable
