### ISSUE TITLE
Demangler Generates Empty Structs When DWARF is Available

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#531]
**Describe the bug**
The Demangler generates an empty placeholder struct every time it demangles a symbol. This occurs even when the dwarf information has already been loaded and parsed.

**To Reproduce**
1. Analyze a c++ library/program with full dwarf debug information.
2. Find populated struct within the DWARF category.
3. Find empty 'placeholder struct' within the Demangled Category.

**Expected behavior**
Demangler should check for the existence of a struct with the target name in all opened databases and populate appropriately before creating an empty struct.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.437]
 - Java Version: 12.1
 - Ghidra Version: 9.2

**Additional context**
This is occurring while analyzing libstdc++ compiled with `--enable-debug CFLAGS="-gdwarf-2 -g3 -o0" CXXFLAGS="-gdwarf-2 -g3 -O0"` In the meantime I'm having my batch analysis script repopulate the empty structs, but they shouldn't be created in the first place. The only way I have managed to get an analysis on a program to apply the appropriate structs to a demangled class is by copying the demangled folder from a datatype archive to the programs archive before running the analysis. It appears that the demangler only checks to see if there is an existing structure in the Demangled category instead of every category.

**Comment by astrelsky** [comment]
This was my fault as I was trying to cheat by importing the dwarf information from the libraries and while using yara signatures for the class functions. Everything works as intended.

**Comment by ryanmkurtz** [comment]
Thanks for coming back to it and closing it out.
