### ISSUE TITLE
"Find uses of filed" option can't find all uses

### ISSUE THREAD

**Issue by ZereX666** [NationalSecurityAgency/ghidra#5310]
I got the same problem as the person here:
https://github.com/NationalSecurityAgency/ghidra/issues/503

I also got errors in the console after using this option:
https://pastebin.com/i6b55zyg

**Environment (please complete the following information):**
 - OS: Windows 11 Pro
 - Java Version: 11
 - Ghidra Version: 10.2.3
 - Ghidra Origin: official GitHub distro

**Comment by dragonmacher** [comment]
The exception listed here has been fixed in 836604e09.

I'm curious to know if the feature is still not finding expected uses after you have tried you code with this fix.   The fix will be in the upcoming release.  It is also available now if you pull and run from the repo.

**Comment by ZereX666** [comment]
Sorry for taking so long to answer. I used Dev build from 2023-May-26 1847 (Version 10.4) and have this error
https://pastebin.com/i8kCZ5ku

**Comment by dragonmacher** [comment]
Thanks for the trace.  Not sure under what conditions this can happen, but we can add a guard to keep the exception from happening.
