### ISSUE TITLE
Add auto-completion for datatypes keyed into the `Edit Function` dialog

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#5323]
**Is your feature request related to a problem? Please describe.**
When choosing a datatype for a variable in other panels (eg. the `Decompile:` panel) each key press offers the ability to pick the type from an ever diminishing list of types.  However this isn't available in the freeform text editing area of the `Edit Function` dialog.

**Describe the solution you'd like**
This dialog's freeform text area modified to take advantage of datatype auto-completion.

**Describe alternatives you've considered**
Adding/modifying the types in the  `Function Variables` section.  This works, but the workflow doesn't!

**Additional context**
It would also help in remembering the correct type, especially when you have related types using the same starting prefix!

**Comment by astrelsky** [comment]
Personally I use the free form edit function specifically for when I don't want the suggestions in my way and for copy/pasting entire signatures (and then removing keywords like const, struct, restrict and union which still aren't supported for some reason).

**Comment by Wall-AF** [comment]
I also use it that way @astrelsky.  Just another option, maybe?

I also look forward to be able to paste in the likes of:
```
HGLOBAL LoadResource(
  [in, optional] HMODULE hModule,
  [in]           HRSRC   hResInfo
);
```
without having to remove unsupported bits and bobs!

**Comment by ryanmkurtz** [comment]
We just discussed this and while we think it could be useful in some contexts, we don't see ourselves realistically ever prioritizing it high enough to work on it.

**Comment by Wall-AF** [comment]
Shame, I though it'd be straight forward, I would've use it a lot!  Never mind.  I understand there are lots of other far more important outstanding bugs/issues/feature requests.
