### ISSUE TITLE
Can't add keybinding for "Close Window" and other DockableToolBarManager actions?

### ISSUE THREAD

**Issue by comex** [NationalSecurityAgency/ghidra#533]
**Describe the bug**
Can't add a keybinding to close the current window/pane.

**To Reproduce**
1. Open the code browser.
2. Note that each pane has an "X" button at the top right, with tooltip "Close Window".
3. Go to Tool Options -> Key Bindings, and search for "Close Window".

**Expected behavior**
The action appears and can be bound to a key.

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Java Version: openjdk 11.0.2
 - Ghidra Version: trunk

**Additional context**
This would be useful for pop-up windows such as "Show References to Address".

Not sure if I'm missing some other way to bind it or some other convenient way to close the window.

**Comment by huettenhain** [comment]
Possibly related to #504.
