### ISSUE TITLE
Listing doesn't display label or namespace characters wrapped in angle brackets

### ISSUE THREAD

**Issue by CreepNT** [NationalSecurityAgency/ghidra#5334]
**Describe the bug**
In the Listing window, if a label or namespace contains more than 10 characters wrapped in angle brackets, the content of the angle brackets is not shown (as if it didn't exist).
For example, `<12345678901>::<12345678901>` will display as simply `<>::<>`.

This seems to only happen if more than ten characters are inside the angle brackets, and doesn't affect characters outside the angle brackets. Screenshots are all performed using numeric names but the characters inside the angle brackets seem irrelevant (happens if all characters are letters).

I have tested other types of brackets (`()`, `{}` and `[]`) and this behavior is only exhibited with angle brackets.

**To Reproduce**
1. Import any program (tested on ELFs loaded with custom loader, and standard PE]
2. Create a label containing more than 10 characters in angle brackets, such as `<12345678901>`
3. See that the label is displayed as `<>`

**Expected behavior**
The label displays as `<12345678901>`

**Screenshots**
With 10 or less characters in the angle brackets, everything functions properly.
![Less than 11 characters sample](https://github.com/NationalSecurityAgency/ghidra/assets/32939301/0a74957c-6d3f-4975-9264-128ed481da4d)

Adding a character to the name (11 in total) makes the angle brackets' content disappear in the listing.
![10 characters in namespace, 11 in name which becomes invisible](https://github.com/NationalSecurityAgency/ghidra/assets/32939301/73299750-0c60-4a26-b759-ba4a7e31b37e)

Identical behavior with the namespace (the Symbol Tree is not affected)
![11 characters in namespace which becomes invisible (no issue in Symbol Tree)](https://github.com/NationalSecurityAgency/ghidra/assets/32939301/54b6962d-5565-4053-b8e0-825fb2a5e07e)

Identical behavior when both are combined.
![11 characters in both](https://github.com/NationalSecurityAgency/ghidra/assets/32939301/f04f0a31-86ad-4458-be84-5c12a46cebda)

A more convoluted example, showing that characters outside angle brackets aren't affected.
![image](https://github.com/NationalSecurityAgency/ghidra/assets/32939301/ec2dcd58-7589-4e67-847f-ec75231c84d0)

Matching pairs of angle brackets are also not displayed (i.e. the outermost pair's content is hidden)
![Three matching pairs of angle brackets , only one displayed](https://github.com/NationalSecurityAgency/ghidra/assets/32939301/fa8844a9-7dfd-473a-9332-fdbd9d8de693)

Extreme case of this idea.
![7 pairs of angle brackets, only outermost displayed](https://github.com/NationalSecurityAgency/ghidra/assets/32939301/ee50220c-b264-494f-868d-ebb87a8f9653)

When mismatching pairs are present, the mismatching characters are treated as any other and displayed properly.
![Three opening angle brackets, only one closing](https://github.com/NationalSecurityAgency/ghidra/assets/32939301/2c985bc1-6988-4cfd-b32e-02106e9cd910)

**Environment:**
 - OS: Windows 10 Pro 22H2 build 19045.2965
 - Java Version: 17.0.7
 - Ghidra Version: 10.3
 - Ghidra Origin: official GitHub distro

**Comment by RootCubed** [comment]
This is intended behaviour - see 8bb02c4. It seems this can be disabled in Edit -> Tool Options -> Listing Fields -> Template Display options.
