### ISSUE TITLE
Alternative to FunctionEditorModel.apply?

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5339]
After commit a477689 ``FunctionEditorModel.apply`` is no longer public. This meant that some scripts I had no longer work. For example:

```
public class ExampleCustomStorageEditor extends GhidraScript{
	@Override
	public void run() throws Exception {
		Function foo = getFunctionContaining(currentAddress);
                ...
		DataTypeManagerService service = state.getTool().getService(DataTypeManagerService.class);
		FunctionEditorModel model = new FunctionEditorModel(service, foo);
		model.setUseCustomizeStorage(true);
		List<ParamInfo> params = model.getParameters();
                params.remove(currentLocation.getToken().getHighVariable().getSlot());
		model.apply();
	}
}
```

Is there an alternative that will allow me to adjust function storage from API?

**Comment by dragonmacher** [comment]
The `FunctionEditorModel` was not meant to be used directly, but was designed for the function editor dialog.   Typically in Ghidra we use commands to manipulate program information.  In this case, you should likely be using the `ApplyFunctionSignatureCmd`.

If you find that the function editor model performs work that you find useful, which is not in the command, then we likely need to update the command to be more robust, or create a new command.

**Comment by ghidra1** [comment]
The `Function.updateFunction` method with a Program transaction provides the most flexibility for updating a function with its params and storage.  The `ApplyFunctionSigantureCmd` does not facilitatesetting return/param storage and assume automatic storage should be used.
