### ISSUE TITLE
Import numpy in python crash Ghidra

### ISSUE THREAD

**Issue by 20urc3** [NationalSecurityAgency/ghidra#5345]
**Describe the bug**
Running python script that import numpy inside Ghidra GUI completely crash the software.

**To Reproduce**
1. Go to script > new script > python 2
2. "import numpy" inside the script
3. Run the script. See warning message. Then run the script again
4. Ghidra freeze/crash

**Additional context**
An both Win & Linux latest version

**Comment by astrelsky** [comment]
![image](https://github.com/NationalSecurityAgency/ghidra/assets/46897303/1f1f661e-ecdd-450b-bae0-65121b89689a)

Can't reproduce.

**Comment by 20urc3** [comment]
pip install numpy on your system firstly

**Comment by astrelsky** [comment]
> pip install numpy on your system firstly (sorry, i should have say it)
> 
> EDIT: you can actually run it, the first time. It's re-running the script that causes the crash.
> 

I have numpy installed. You cannot use cpython packages from jython. I'm assuming you have ghidrathon installed which is where this problem is coming from.

**Comment by ryanmkurtz** [comment]
As @astrelsky said, you are likely having an issue with a 3rd party Ghidra extension that provides CPython integration.  I recommend you file an issue with that extension's project.
