### ISSUE TITLE
"Original File" Exporter failed to export binaries with enabled "Export User Bytes Modification" option

### ISSUE THREAD

**Issue by OrionRafi3345** [NationalSecurityAgency/ghidra#5346]
**Describe the bug**
 "Original File" Exporter failed to export binaries with enabled "Export User Bytes Modification" option

**To Reproduce**
1. Load PE binary
2. Modify or left the binary as is (Outcome is same)
3. Go to File->Export Program
4. Select Format "Original File" 
5. Select Option "Export User Bytes Modification" 
6. Hit OK
7. "Export Results Summary" Windows Pops up Showing "Destination File Size: 0"
8. Check the Destination Directory
9. **NO FILE IS PRODUCED!**

**Expected behavior**
Should save the binaries to the destination with modified bytes

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Java Version: 17.0.5
 - Ghidra Version: 10.3
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
Doh, we'll get it fixed.  Thanks.
