### ISSUE TITLE
Adding reference doesn't update pseudo code

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#535]
I have such line:
![изображение](https://user-images.githubusercontent.com/7189309/56892775-532c8080-6a89-11e9-8248-61ec985c7d82.png)

I've pressed R to open reference editor, and added such info:
![изображение](https://user-images.githubusercontent.com/7189309/56892849-896a0000-6a89-11e9-8fa1-e823eb31ddc2.png)

Decompiler still doesn't know anything about this reference:
![изображение](https://user-images.githubusercontent.com/7189309/56892872-9c7cd000-6a89-11e9-9d48-05b596c4d017.png)

**Comment by emteere** [comment]
The decompiler is a simplification engine.  A6 would need to be set at the beginning of the function in order to recover the reference.  This is by design, and is necessary for type propagation and other analysis to occur.
