### ISSUE TITLE
DLL symbol export files (.exports) are not applied to some MFC DLLs

### ISSUE THREAD

**Issue by emuzychenko** [NationalSecurityAgency/ghidra#5351]
**Describe the bug**

When loading and analyzing EXE files that use various versions of MFC DLLs (that are imported only by ordinals, not by names), symbolic names are shown for some versions of MFC DLLs, but not for all.

For example, symbolic names are shown for mfc42.dll, but most likely it is because this version contains symbolic names inside the DLL itself (dumpbiin /exports shows the names).

For another example, mfc90u.dll version 9.00.21022.08 (supplied together with MS VS 2008) doesn't contain the names, so Ghidra always shows only ordinals.

Ghidra has the predefined .exports file for this DLL but doesn't use it. I supposed it is because different versions of this DLL use different set of ordinals, while common mfc90u.exports created for an unknown version, doesn't match.

So I ran Ghidra 10.1.3 that has created mfc90u.exports for the particular DLL, adding its version and date to the header. Of course, the file contains only ordinal numbers without their symbolic names. Then I have modified the name of the first visible ordinal, deleted my EXE from the project, re-imported it back, and ran the analyzis again. Ghidra 10.1.3 didn't show the modified symbol.

I copied mfc90u.exports to the home directories of Ghidra 10.2.3 and 10.3 (they didn't keep .exports files created by themselves, see #5348) and repeated the importing/analysis. Both versions didn't show the modified symbol too.

**To Reproduce**

1. Unpack test.exe and mfc90u.dll from the attached archive.

2. Run Ghidra 10.1.3 (10.3 and 10.2.3 don't keep .exports files, see #5348).

3. Import test.exe and see that mfc90u.exports file is created in "symbols\win32" subdirectory of Ghidra home directory.

4. Run the analyzis of test.exe.

5. In Symbol Tree, expand MFC90U.DLL. You will see only Ordinal_nnnn names. The first one is "Ordinal_1048".

6. Close CodeBrowser window without saving, close main Ghidra window.

7. Open mfc90u.exports file in "symbols\win32" subdirectory of Ghidra home directory. Locate "1048" and enter any name in NAME="Ordinal_1048". Save the file.

8. Run Ghidra, delete test.exe from the project, import it again, and run the analyzis. In Symbol Tree, expand MFC90U.DLL. You will see that the first entry is still "Ordinal_1048" (the modified name was not applied).

9. Copy the modified mfc90u.exports file to home directories of Ghidrd 10.2.3 and 10.3, create the projects and run the analyzis. You will see the same result (the modified name is not applied).

**Expected behavior**

If a matching export file is found in the home directory, it should be applied to the names.
Otherwise, PDB file lookup should be performed.
If there is no matching PDB file, default export files should be searches in Ghidra installation directory.

**Attachments**
[The example (EXE and DLL)](https://github.com/NationalSecurityAgency/ghidra/files/11507749/test.zip)

**Environment (please complete the following information):**
 - OS: Windows 7
 - Java Version: 20.0.1
 - Ghidra Version: 10.3, 10.2.3, 10.1.3
 - Ghidra Origin: official GitHub distro

**Comment by Wall-AF** [comment]
I mentioned the `hh` problem in this https://github.com/NationalSecurityAgency/ghidra/issues/2233#issuecomment-683346520.
I suggested replacing the `hh` with `kk`!

**Comment by ryanmkurtz** [comment]
Ahhh, definitely a case of too much going on in one ticket.

**Comment by emuzychenko** [comment]
@ryanmkurtz, Thank you for the suggestion about the time stamp. But I tried to create the .exports file using Ghidra's standard file as a template. Most of these files contain "?" for the date and version, so I kept the same values.

Should the timestamp in "DATE" represent the file's time? If so, which of Windows file times (creation or last write) should be placed there? And what should be used in "VERSION"?

BTW, should Ghidra skip timestamp/version comparison if the appropriate field contains "?"?

If such operations were logged in detail, it would be much more simpler to analyze what is wrong.

**Comment by mala-dev** [comment]
I have the same problem. No amount of manual tweaking of the mfc14u.exports file, putting it in the .ghidra directory, or fiddling with the import options, works. It doesn't get used, but an empty one with only ordinals is generated instead.

The one in the Ghidra directory looks like this `<LIBRARY NAME="mfc140u.dll" PATH="mfc140u.dll" DATE="?" VERSION="?">` whereas the generated one looks like this `<LIBRARY NAME="mfc140u.dll" PATH="C:\WINDOWS\system32\MFC140U.DLL" DATE="Fri Jun 10 07:52:28 CEST 2022" VERSION="14.32.31332.0">`

It's almost as if Ghidra fails to understand that an exports file already exists, regardless of date and version in the file header, but has no trouble overwriting it (it moves the copied one to mfcu14.exports.bak).
