### ISSUE TITLE
Please make the application log more verbose

### ISSUE THREAD

**Issue by emuzychenko** [NationalSecurityAgency/ghidra#5353]
**Is your feature request related to a problem? Please describe.**

Faced some problems with naming DLL imports (see #5348 and #5351), and trying to at least isolate the problem, I encountered that the application log is extremely meager. For example, after importing, loading and analyzing a 50..200 kb Windows executable that imports multiple DLLs and uses hundreds of functions, the log is less than a hundred lines, containing mainly the timing data. For my case (Ghidra doesn't apply export names to MFC DLLs imported by ordinals), the log contains no meaningful data that could help to isolate the problem.

In the documentation and the discussions, I found no information about controlling log verbosity level. But some lines contain "DEBUG" instead of "INFO", so I suppose that the maximum available verbosity is used by default.

**Describe the solution you'd like**

I would like to have as much verbose logging as much as it could help to understand any processing peculiarities, together with a verbosity control (levels 0-9 would be quite enough).

In common practice, every log should be verbose enough to understand what the application does (searching, loading and saving files, creating meaningful internal objects, changing processing modes etc.). Any unexpected conditions should be logged as well, not only severe/fatal ones.

Detailed logging will greatly help to isolate most problems and make problem reports more informative.

**Describe alternatives you've considered**

I think there are no alternatives to detailed logging.

**Comment by dragonmacher** [comment]
Currently in Ghidra you can control the logging via the log config file you tell Ghidra to use.  To see an example of this, see `{Install Dir}/support/launch.sh`.   This file has a line that uses a debug log file:
```
DEBUG_LOG4J="${SUPPORT_DIR}/debug.log4j.xml"
```
That file lives at `{Install Dir}/support/debug.log4j.xml`

The most comprehensive list of package names to use within our system that currently use logging can be found at:
[generic.log4jdev.xml](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/Generic/src/main/resources/generic.log4jdev.xml)

So, with little effort, you can copy the contents of that file into `{Install Dir}/support/debug.log4j.xml` and change the various log levels as desired.

With regard to the conceptual request of this issue, I'm sure you can imaging that adding logging to the entire application's feature set is a non-trivial task.    Since logging was not built into the various APIs originally, there will be much work required to add that at this point.   It seems that the best possible approach for adding logging is to do so on a feature-by-feature basis.  Thus, you can make a request for logging to be introduced into a particular process (e.g., import, analysis, editing).   In making such a request, it will be helpful to list the particular bits of information that you would find useful.

**Comment by emuzychenko** [comment]
@dragonmacher, sorry for the late reply. There was no notifications at all, however I have automatically subscribed to them (I don't use spam folders, all mail goes directly to the inbox).

> see `{Install Dir}/support/launch.sh`

I use Ghidra only in Windows. Does this work here? My application.log shows:

(LoggingInitialization) Using log config file: jar:file:/S:/Tools/Ghidra/10.3/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml  

How can I specify the logging config in Windows?

I didn't look about the logging in the installation dir, just looked in the settings and in the docs. In Linux, is it considered normal to change the settings in the common installation directory, not in the user profile one?

**Comment by dragonmacher** [comment]
> I use Ghidra only in Windows. Does this work here? My application.log shows:

You should have a `launch.bat` on Windows.

To run Ghidra with with the debug log config file defined in `launch.bat`, you will run Ghidra by double-clicking `{Install Dir}/support/ghidraDebug.bat`.   Using that batch file will signal to use the debug log config file I mentioned above.   

Once Ghidra is using `Install Dir}/support/debug.log4j.xml`, you can then modify that file directly to change log settings.  That will let you easily experiment to see what output you can change.  If you would like a more robust solution, then you will have to create you own custom batch file and pass the correct flags to Ghidra.  You can see examples of how Ghidra does this in the files I mentioned above.

> In Linux, is it considered normal to change the settings in the common installation directory, not in the user profile one?

Obviously, when installed in a shared dir, changing that dir is not done on a per-user basis.    I would suggest you install Ghidra in a personal directory while you modify log settings.  Once you know what you would like to change, then you can figure out how to use Ghidra in a common directly while specifying a custom log file if you plan to have one installation shared among multiple user accounts.

**Comment by emuzychenko** [comment]
@dragonmacher, thank you for the suggestions. First I tried to simply replace debug.log4j.xml with generic.log4jdev.xml, adding other XML files that it mentions, but Ghidra reported a format error. So I just added other loggers to native debug.log4j.xml, and the log appears to be a little more detailed, but there still are too few details for such a complicated software. For a project containing a test EXE file and a dependent mfc90u.dll, application.log contains just 18 lines after both files are imported. About ten lines are added during the analysis. I think this is obviously not enough to investigate almost any problem.

For example, when the files are added to the project, loaded and analyzed, their names/paths are not mentioned in the log at all. So it is impossible to understand which file the error message refers to. There are two messages "DEBUG ghidra.app.util.opinion.LibraryLookupTable got exception looking for .exports file (or parsing, etc.)". But there is no information about which .exports file does it look for, in which directory, which PE file it is related to, what is the error code, etc.

In addition, the information displayed in the "Import results summary" is not added to the log file, and can be viewed in the window only. It contains unclear messages too, for example: "WARNING! Using existing exports file for MFC90U.DLL which may not be an exact match". There is no information about the reason(s) why the file is considered unsuitable, we can only guess about them.

The application.log also cointains "INFO  ghidra.app.plugin.core.analysis.PdbUniversalAnalyzer Skipping PDB processing: missing PDB information in program metadata". It is not clear which file in the project this refers to. Both EXE and DLL files contain PDB information, both PDBs are accessible, IDA and WinDbg always find and successfully parsed them.

I would be like to find all relevant information in the log file, to analyze it myself, and provide informative bug reports to the developers. Without such details, I have no choice but just complain to the bugs. :)

Additionally, I see that the launch scripts add all files in the current directory to the command line. Is there any reason for this?

**Comment by emuzychenko** [comment]
@ryanmkurtz, I'm trying to understand why [symbolic names are not applied to mfc90u.dll exports](url). So I would be happy for any details in the application log file(s) that could provide useful information. Should I create additional requests for this?

**Comment by dragonmacher** [comment]
> I would be like to find all relevant information in the log file, to analyze it myself, and provide informative bug reports to the developers. 

I think you request is something that would make understanding Ghidra's processing much better.   However, as mentioned above, since Ghidra was not designed to do this initially, changing the code to do this now is a very large effort.  

> Additionally, I see that the launch scripts add all files in the current directory to the command line. Is there any reason for this?

Can you point out which file(s) is doing this?

**Comment by emuzychenko** [comment]
> Ghidra was not designed to do this initially

This is very strange to me. Ghidra was originally conceived as a complex and multifunctional software. With such software, detailed logging is the only way to efficiently investigate non-obvious bugs. So it should have such logging from the beginning.

> changing the code to do this now is a very large effort

I understand that it is hard to add a detailed logging from scratch. But Ghidra shows many real-time messages in its windows while processing. Maybe some of these messages contain useful information, but they are quickly replaced by each other, so it is impossible to read them all. Maybe it makes sense to direct them to the logging stream too.

> Can you point out which file(s) is doing this?

Sorry, this was my fault. Since I had to edit launch.bat and check the actual command line passed to Java, I added some additional lines of code, and they affected the ARGS variable by error.

**Comment by dragonmacher** [comment]
> This is very strange to me.

Perhaps, but it really depends upon how the product is to be used and supported.    For proprietary software, logging may be one of the only ways to understand what the tool is doing.  For open source projects, you can use the source code and development tools to see exactly how the tool works, which lessens the need for logging.   

> Maybe it makes sense to direct them to the logging stream too.

This is an interesting suggestion.   It makes me think of a system where each task/command/unit of work we have could be logging info such as: task name, start, finish and thread info.   Further, our service-level APIs could have more logging which also prints the current context, such as thread and task info for that thread.   This would certainly greatly improve forensics done using log files.    Unfortunately, even doing this would not help the implied issue in this ticket, that our import process and much of our analysis is not effectively using logging.
