### ISSUE TITLE
[Debugger] Insane memory usage

### ISSUE THREAD

**Issue by Guusggg** [NationalSecurityAgency/ghidra#5357]
Hi,

Ghidra: 
`ghidra_10.2.3_PUBLIC`
Java: 
```
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7)
OpenJDK 64-Bit Server VM (build 17.0.7+7, mixed mode)
```

My system has 30gb total memory. When I launch Ghidra, on the start screen (no tools opened), it uses around 400Mb of memory, which is really clean. When I launch the Debugger, memory climbs to 700Mb, which is very doable still. However, when I use the Ghidra Debug Agent to connect to my target, the memory spikes up untill around 25Gb, which is also the limit of my system. 

Somethings it freezes my computer and forces me to powercycle the computer. I'm not pointing fingers to the development team, but is there any way I can investigate why the memory usage is so massive? 

When I launch gdb and attach manually, the `gdb` process uses about 60Mb (in the terminal). The application I'm debugging is about 25Mb in memory. In my process list it's just the Java executable that uses 25Gb. The memory stays up to 25Gb after debugging until I close Ghidra completely, which to me might indicate a Java'ish memory leak.

Any tips or hints I could use to improve my experience?

Edit: Just tested out with `ghidra_10.3_PUBLIC` and it's the same. 
Another edit: When I just use `gdb` to start and then use the `attach` command, memory usage stays very nice at 2Gb. I think this is not an issue with Ghidra or `gdb` but since I'm using `winedbg` as frontend, I assume it has a problem there.
Another edit: When disabling `Read Memory` (which to me could be a huge source of memory use) changes nothing.

**Comment by d-millar** [comment]
@Guusggg Hey, we just noticed this on Thursday when I upgraded to gdb 13.1 to test another bug.  @dev747368 has a fix, which I believe fixes the problem, but (a) it’s non-trivial set of changes, and (b) it’s not clear why it hasn’t affected previous versions of gdb.  Which version of gdb are you running if you don’t mind my asking?

**Comment by Guusggg** [comment]
Hi,

Thank you for the fast response! I think you must be spot on, because I'm on `GNU gdb (GDB) 13.1`. It's not too big of a problem since I'm getting pretty familiar with `gdb`, but debugging in Ghidra is the dream! I can check if I can downgrade to 12.^ to see if that fixes anything. 

The way the memory only gets released after I close down Ghidra makes me a bit worried tho.

**Comment by d-millar** [comment]
Yes, so, for reasons that would probably be hard to remember/explain, we are pulling the  results from “maintenance info sections -all-objects” for each module, rather than making a single call and splitting out the results. Why exactly this results in unfreed memory for 13.1, but not, say, 9.2 is a good question and one I wish I understood better.  Will let you know when the fix has been added to the current source tree if you’d like to build your own.  If not, it will certainly be in 10.3.1.

**Comment by Guusggg** [comment]
Very good news that you've found the culprit! I'd rather stay on a more stable Ghidra version so I'll not be compiling it for myself. I have the patience to wait it out for 10.3.1 tho! 

Thank you very very much for the your time spent and have a great day.

**Comment by nsadeveloper789** [comment]
The changes were merged in this morning, but haven't been pushed to GitHub, yet. To be sure, it fixes a huge memory issue that we noticed with 13.1. There's a good chance this is the same issue you're seeing. Feel free to re-open if this persists in 10.3.1, once released.

**Comment by Guusggg** [comment]
Fantastic, thank you very much for the swift action! Much appreciated!
