### ISSUE TITLE
Changed bytes in .text section of DLL export incorrectly

### ISSUE THREAD

**Issue by relt-1** [NationalSecurityAgency/ghidra#5361]
**Describe the bug**
When modifying instructions and bytes in the .text section, there is a chance that some bytes will get saved completely incorrectly.

**To Reproduce**
1. Modify a sufficient amount of instructions in a DLL (in this case i am using the [Source](https://en.wikipedia.org/wiki/Source_(game_engine)) engine.dll)
2. Export program
3. Some of the bytes should be different than what you put in Ghidra

**Screenshots**
https://cdn.discordapp.com/attachments/336023718709035020/1109849787920023633/javaw_ZGaBbrOrma.mp4
The left tab shows the intended bytes, the right tab shows what has been exported. You can notice that some of the bytes change into complete garbage on the right tab, when the left tab shows what should have been exported.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.6
 - Ghidra Version: 10.3
 - Ghidra Origin: Github releases

**Comment by relt-1** [comment]
I have researched this topic very deeply, it turns out that the relocation table is what messes these bytes up.
Is there a way to modify the relocation table?

**Comment by ryanmkurtz** [comment]
Possibly related to #5346.  If possible, can you try building `master` and trying again?

**Comment by ryanmkurtz** [comment]
Likely fixed in 10.3.1.
