### ISSUE TITLE
Decompiler Edit Function action may not preserve calling convention used by Decompiler

### ISSUE THREAD

**Issue by ghidra1** [NationalSecurityAgency/ghidra#5366]
### Discussed in https://github.com/NationalSecurityAgency/ghidra/discussions/5358

<div type='discussions-op-text'>

<sup>Originally posted by **matcool** May 20, 2023</sup>
Previously, when opening the edit function signature popup it would default to the calling convention that the decompiler guessed, but now in 10.3 it always defaults to unknown along with the `Use Custom Storage` option being enabled.
Is there any way to revert this behavior? The old behavior was more convenient when renaming functions since the guessed cc was often right</div>

**Comment by ryanmkurtz** [comment]
Duplicate of #5367
