### ISSUE TITLE
Decompiler Edit Function action may not preserve Calling Convention used by Decompiler

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#5367]
### Discussed in https://github.com/NationalSecurityAgency/ghidra/discussions/5358

<div type='discussions-op-text'>

<sup>Originally posted by **matcool** May 20, 2023</sup>
Previously, when opening the edit function signature popup it would default to the calling convention that the decompiler guessed, but now in 10.3 it always defaults to unknown along with the `Use Custom Storage` option being enabled.
Is there any way to revert this behavior? The old behavior was more convenient when renaming functions since the guessed cc was often right</div>

**Comment by astrelsky** [comment]
![image](https://github.com/NationalSecurityAgency/ghidra/assets/46897303/9029a404-5e1e-469f-8906-d38fd655581d)

Currently on e25881828cd240d39dc31e6d2430ebba4124918c with a freshly imported and analyzed program loaded with dwarf.

🤔 this might be a separate regression with how the dwarf analyzer applies the function signature. Will leave it up to you if a new issue should be created or not. This issue might be hiding in other places as well.

**Comment by ghidra1** [comment]
@astrelsky How is this a regression?  Previously, there were issues where this dialog did not properly convey the "unknown" calling convention state for a function when it had never been established.  In addition to named calling conventions defined by the cspec, there is both an "unknown" and "default" state.  The "default" state will simply adopt the default calling convention defined by the cspec whatever it may be at the time of use.

**Comment by astrelsky** [comment]
> @astrelsky How is this a regression?  Previously, there were issues where this dialog did not properly convey/preserve the "unknown" calling convention state for a function when it had never been established.  In addition to named calling conventions defined by the cspec, there is both an "unknown" and "default" state.  The "default" state will simply adopt the default calling convention defined by the cspec whatever it may be at the time of use. 

Custom storage is being automatically set when it is not custom storage.

**Comment by astrelsky** [comment]
@ghidra1 I'm having difficulty getting it to occur consistently with different loaded programs. I'll open a separate ticket if I'm able to narrow down what's causing it.

**Comment by astrelsky** [comment]
@ghidra1 I've been unable to reproduce it since - and am now wondering if I accidentally did something stupid like build Ghidra but forget to extract the build afterwards 😅
