### ISSUE TITLE
Provide arm64 builds of decompile and sleigh binaries for macOS

### ISSUE THREAD

**Issue by crowell** [NationalSecurityAgency/ghidra#5370]
**Is your feature request related to a problem? Please describe.**
```
jeff@wasteland share/java/ghidra-10.3  $ cd ./Ghidra/Features/Decompiler/os/
jeff@wasteland Features/Decompiler/os  $ ls
linux_x86_64 mac_x86_64   win_x86_64
jeff@wasteland Features/Decompiler/os  $ file mac_x86_64/decompile
mac_x86_64/decompile: Mach-O 64-bit executable x86_64
```
Built are only mac_x86_64, these binaries should be fat, and support arm64 for better performance on Apple Silicon machines

**Describe the solution you'd like**
Built are only mac_x86_64, these binaries should be fat, and support arm64 for better performance on Apple Silicon machines

**Describe alternatives you've considered**
none

**Additional context**

**Comment by ryanmkurtz** [comment]
If Gradle provided an easy way to output a Universal Binary with both x86 and aarch64 included, I'd happily put that in both our `mac_x86_64` and `mac_arm_64` directories to address this.  Maybe someone else knows how to do this and could provide a PR we could evaluate, keeping in mind we only have access to an x86 mac for builds.

A few releases ago, we provided a `support/buildNatives` script that you can run on your aarch64 mac to quickly produce what you are looking for, assuming you have gcc/make or XCode installed.  When you build your own, it will override the one we provide.  This is the best we are willing to provide at the moment.  My general thinking is that if a user is hardcore enough to care about the performance our x86 native binaries running under Rosetta 2, they more than likely have the build tools needed to run `support/buildNatives`.  Doing this also has the advantage of Gatekeeper not quarantining our unsigned native binaries (we have no plans to ever sign them).

**Comment by ryanmkurtz** [comment]
I think I have a path forward on this.  It won't be a Universal Binary, but we might be able to generate working aarch64 binaries after all.  I'll get back to you when I have something working.

**Comment by ryanmkurtz** [comment]
@Wall-AF This ticket is about arm64 builds.

**Comment by Wall-AF** [comment]
@ryanmkurtz sorry, just thought I'd mention it here as well as #5296 because its in the same area.
