### ISSUE TITLE
Force Union Field doesn't work occasionally

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#5372]
**Describe the bug**
Force Union Field doesn't work occasionally.

**To Reproduce**
1. Download beep.sys and beep.pdb from the Microsoft Symbol server. (Links are in the "Attachment" section below)
2. Download Windows WDK gdt file: [windows_ntddk_x64_wdk_10_22000.zip](https://github.com/NationalSecurityAgency/ghidra/files/8540698/windows_ntddk_x64_wdk_10_22000.zip) Unzip it to get file windows_ntddk_x64_wdk_10_22000.gdt.
3. Analyze beep.sys: in the "Apply Data Archives" analyzer, choose windows_ntddk_x64_wdk_10_22000.gdt
4. Load beep.pdb
5. Go to function `BeepDeviceControl`. The second line is: `UVar1 = (p_Var3->Parameters).Create.EaLength;` Right click on `Create`, and then click "Force Field." Change the field from `Create` to `DeviceIoControl`.
6. You can see that the field is not changed.

**Expected behavior**
The field is changed to `DeviceIoControl`.

**Screenshots**
<img width="821" alt="beep2" src="https://github.com/NationalSecurityAgency/ghidra/assets/16713498/1ff16376-0fcb-4790-9bb8-05baf88ee6c6">
<img width="815" alt="beep3" src="https://github.com/NationalSecurityAgency/ghidra/assets/16713498/d323c386-62ed-474d-9bc0-b719acdc0577">

**Attachments**
beep.sys: https://msdl.microsoft.com/download/symbols/beep.sys/9982B7D7A000/beep.sys (SHA256: ee1d8afa35e5def21a43e8a21ad78ed76ef9e8f2182d0b69b3be84546f553fb4)
beep.pdb: https://msdl.microsoft.com/download/symbols/beep.pdb/E32AF5E2A769CEBDAD7F801AC5E9EA201/beep.pdb

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.6
 - Ghidra Version: 10.4 DEV e25881828cd240d39dc31e6d2430ebba4124918c
 - Ghidra Origin: locally built

**Comment by sad-dev** [comment]
I have similar results with the following binary (available from https://github.com/ucsb-seclab/popkorn-artifact/blob/main/datasets/CVE_sure/CorsairLLAccess64.sys)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/610e5a4d-c227-4cbf-a1cf-b50033c57c6e)

With the same GDT, the highlighted fields resist any attempt to override the union (although tbf the first is correct)
[CorsairLLAccess64.zip](https://github.com/NationalSecurityAgency/ghidra/files/11590442/CorsairLLAccess64.zip)

**Comment by sad-dev** [comment]
After several experiments, the ``Force Union`` feature feels extremely finicky.

Sometimes retyping the variable helps Ghidra guess e.g. setting the LHS to ``IO_STACK_LOCATION`` results in Ghidra allowing ``Overlay` and sometimes it is necessary to (inaccurately) remove a nested union from one of the _IRP structures.

Unfortunately this does mean that IDA is probably still the superior choice on Windows drivers

![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/cc3ff27a-3f0b-4ddd-86e5-4c50baea1700)

**Comment by pdinc-oss** [comment]
related issue #6465?
Should this get re-opened or open a new duplicate, issue is present on:

commit 3c8bb490ac9fd1691a4d5083c946c34f7198087b
Merge: 5ac69075e3 7a557c7d16
Author: Ryan Kurtz <ryanmkurtz@users.noreply.github.com>
Date:   Fri Jun 13 11:10:20 2025 -0400

    Merge remote-tracking branch 'origin/Ghidra_11.4'
