### ISSUE TITLE
CodeBrowser hangs when viewing certain functions

### ISSUE THREAD

**Issue by quietust** [NationalSecurityAgency/ghidra#5378]
**Describe the bug**
Under various circumstances I haven't been able to fully narrow down, the act of selecting certain functions causes the entire application to become unresponsive, consuming 100% of one CPU core until I manually terminate the Java process.

At least one case I've been able to reproduce is the act of flagging a function as "inline" and then trying to view another function that calls it more than once (and triggers the bug described in #3091). Oddly, the Decompiler window does _not_ need to be open for this to happen.

**To Reproduce**
1. Open the attached program (`/bin/ls` retrieved from Ubuntu 20.04.6 LTS x64) and analyze it with the default options
2. Edit the function definition for `FUN_001148c0`, check the "In Line" box, then press OK
3. Attempt to Go To address `0x00104df0`
4. Watch Ghidra become completely unresponsive, not even allowing the "Go To ..." window to disappear

**Expected behavior**
The application shouldn't hang.

**Attachments**
[ls.gz](https://github.com/NationalSecurityAgency/ghidra/files/11550144/ls.gz)

**Environment**
 - OS: Ubuntu 20.04.6 LTS x64 with Cinnamon window manager
 - Java Version: observed with both `Temurin-17.0.7+7` and `17.0.7+7-Ubuntu-0ubuntu120.04`
 - Ghidra Version: 10.3 PUBLIC
 - Ghidra Origin: official GitHub distro

**Additional context**
This did not occur in version 10.2.3

**Comment by astrelsky** [comment]
I noticed this myself yesterday using 10.4_DEV but don't know what caused it. It did eventually continue responding but took around a minute or two.

**Comment by dragonmacher** [comment]
If this happens again, please produce a stack dump so we can see where the UI is spending its time.  From a terminal:

```
jps
jstack <pid>
```

**Comment by dragonmacher** [comment]
Not sure exactly what the issue is, but clearly a livelock and not a deadlock.  

If this is preventing you from working, you can remove the `Stack Depth` field from the listing to prevent the issue.

**Comment by ab9rf** [comment]
a likely related issue: when i right-clicked on a function in the listing and selected "set stack depth change", everything locked up. i did not investigate getting a java stack dump at the time, but i can do more investigation if it would be useful

**Comment by dragonmacher** [comment]
> I did not investigate getting a java stack dump at the time, but i can do more investigation if it would be useful

This would be helpful.  I'm assuming it is the same issue, but it would be good to confirm.

**Comment by ab9rf** [comment]
> > I did not investigate getting a java stack dump at the time, but i can do more investigation if it would be useful
> 
> This would be helpful. I'm assuming it is the same issue, but it would be good to confirm.

ok, attached jstack captured while interface hung after right clicking on a function in the listing, and selecting "Function > Set Stack Depth Change"

[jstack.txt](https://github.com/NationalSecurityAgency/ghidra/files/11557814/jstack.txt)
