### ISSUE TITLE
Allow navigating to prev/next highlight range in decompiler

### ISSUE THREAD

**Issue by comex** [NationalSecurityAgency/ghidra#538]
**Is your feature request related to a problem? Please describe.**
I would like to jump among a variable's uses using the keyboard.  I can highlight the uses <s>using "Highlight Def-use"</s> by middle-clicking, but "Navigation" -> "Next/Previous Highlight Range" only works in listings, not in decompiler views.

**Describe the solution you'd like**
"Navigation" -> "Next/Previous Highlight Range" should support decompiler views.

Unfortunately, this seems less than straightforward to implement.  `DecompilerActionContext` extends `NavigatableActionContext`, but `Navigatable` is designed in terms of program locations (addresses), whereas ideally this would jump to a specific highlighted token; tokens don't have a 1:1 correspondence with addresses.

**Describe alternatives you've considered**
It would also be nice to have a "find variable uses" popup within the decompiler, similar to IDA and/or the "show references" view in Ghidra.  However, even if that existed,  "Next/Previous Highlight Range" would be a quicker/less disruptive way to jump around.

**Comment by dragonmacher** [comment]
I'd like to make sure I understand the request.   
While view a function in the Decompiler, you wish to jump quickly to each place a particular variable is used?

Currently in the Decompiler you can:

1. Perform a find action, pressing next to jump to each matching location
2. Middle-mouse on a token to highlight all uses of that token.

It sounds like you want a combination of these, where you select a variable and then press some button or keyboard combination that moves you to the next highlighted use of that variable.  Is that correct?

**Comment by comex** [comment]
Yes, that's correct.

(FWIW, I was confused when I mentioned "Highlight Def-use" in my original post; middle-click is what I was looking for, but I hadn't realized that it existed.  On the other hand, ideally "Next/Previous Highlight Range" would work in all situations where multiple tokens are highlighted, so it would also work for "Highlight Def-use" if someone actually wants that.)
