### ISSUE TITLE
The resulting target process has no mapping to the static image (macOS)

### ISSUE THREAD

**Issue by bagnongithub** [NationalSecurityAgency/ghidra#5380]
**Describe the bug**

When trying to debug a binary in LLDB locally IN-VM, the process fails. This is on macOS Ventura 13.3.1, brew llvm@14, gdb@13 and Ghidra 10.3, launching debugging in LLDB locally IN-VM. Installation and ghidra/support/buildNatives works well.

**To Reproduce**

1. Create a binary, for example,

gcc -x c - <<EOF
#include <stdio.h>

int main () {
  printf("Hello world!\n");
}
EOF

2. Create a Ghidra project, import and analyze the produced a.out binary.

3. Launch Debug a.out in LLDB locally IN-VM. This fails with the following messages at the debug console:

jar:file:ghidra/Ghidra/Framework/Docking/lib/Docking.jar!/images/dialog-warning.png	Launch a.out - .ProgramDB: The resulting target process has no mapping to the static image a.out - .ProgramDB. Intervention is required before static and dynamic addresses can be translated. Check the target's module list.	[]
	*** State Changed: 1	[]
jar:file:ghidra/Ghidra/Features/Base/lib/Base.jar!/images/dialog-warning_red.png	Value 56674 for Sessions[63c].Processes[63c].Threads[dd62]._tid does not conform to required type class java.lang.Long of schema LONG	[]	Wed May 24 18:58:25 EEST 2023
	*** Module Loaded: 2	[]
	*** Module Unloaded: 4	[]
	Selected first mapping offer: <Offer: 'LLDB on macOS x86_64' lang=x86:LE:64:default cs=gcc confidence=100 target=Sessions[63c].Processes[63c]>	[]
	Using os=macosx13.0.0 arch=x86_64	[]
jar:file:ghidra/Ghidra/Features/Base/lib/Base.jar!/images/dialog-warning_red.png
expected TargetExecutionState for _state, but got null	[]

**Expected behavior**

I would love this to work.

**Environment (please complete the following information):**

This is on macOS Ventura 13.3.1, brew llvm@14, gdb@13, openjdk@17 and Ghidra 10.3, official binary distro.

**Comment by d-millar** [comment]
@bagnongithub I guess per-the-previous-discussion the first thing I would check is whether the Module List contains an executable named a.out.  If not, you need to map the running executable to your imported a.out program.

I haven't tested your exact example on a Mac yet as I don't have easy access at this moment to a machine running Ventura 13.3.1.  I will in a couple of hours and can test it then.  In the meantime, I did run your example in Ubuntu using  llvm@14, openjdk@17, and the official Ghidra 10.3 distro without any issues, so am guessing this has something to do with differences on OSX, but....just guessing until I can test it.

**Comment by bagnongithub** [comment]
<img width="864" alt="Screenshot 2023-05-25 at 10 17 37" src="https://github.com/NationalSecurityAgency/ghidra/assets/81257432/aa7a9593-8a7d-42c9-9963-c9f4421dc501">

**Comment by bagnongithub** [comment]
<img width="432" alt="Screenshot 2023-05-25 at 10 18 13" src="https://github.com/NationalSecurityAgency/ghidra/assets/81257432/b13d4d24-115e-4741-9c8e-033482985153">

**Comment by d-millar** [comment]
Hmmm, OK - so guessing it just needed a refresh and opening Modules in the Objects viewer triggered that?  We used to auto-refresh the modules list, but turns out that's very expensive, esp. for kernel debugging.  I think @nsadeveloper789 has a decent workaround, so this should be improved with the next release.

**Comment by bagnongithub** [comment]
<img width="588" alt="Screenshot 2023-05-25 at 15 16 19" src="https://github.com/NationalSecurityAgency/ghidra/assets/81257432/5f05e599-ce1f-41aa-b6ce-92b977258047">

 I'm not sure, the listing seems complete from the beginning, no need to refresh.

**Comment by bagnongithub** [comment]
Solved by release 10.3.1, thanks a lot.
