### ISSUE TITLE
Compiling exported code

### ISSUE THREAD

**Issue by ThorvaldAagaard** [NationalSecurityAgency/ghidra#5385]
I have an old windows-program (32 bit) - probably compiled with visual studio as a C/C++ program.

I can load the program in Ghidra, and decompile it, but the exported c-code gives me a lot of compiler errors.

Some is due to missing declarations, and others are because of calling conventions.

So how is it intended that the generated C-code should be compiled?

**Comment by ryanmkurtz** [comment]
The exported "C-like" code is not designed to be compiled without some customization on the part of the user.  See #236 for additional discussion.
