### ISSUE TITLE
Ghidra 10.3 deletes storage type of function parameters when opening 10.2.2 project containing M68000 code

### ISSUE THREAD

**Issue by raminsadre** [NationalSecurityAgency/ghidra#5390]
**Describe the bug**

This looks like a serious bug that will cause people to lose work.  When opening a 10.2.2 project containing M68000 code with Ghidra 10.3, the storage information of function parameters is destroyed. More concretely, the following happens:
- In Ghidra 10.2.2, I have a project containing a function where the parameters have storage type "Stack" (either manually set by me or by the decompiler).
- When opening the project in Ghidra 10.3 (upgrading), the storage type of the parameters is changed to "Register" by Ghidra. If you have a project with hundred of functions, you have to manually repair all function signatures.

Below is a minimal example that demonstrates the problem.

**To Reproduce**
1. Start Ghidra 10.2.2 and import the attached file "test68.bin" into an active project. Use the following import parameters: Format "Raw Binary", Language "68000 default".
2. Open "test68.bin" in the code browser. You don't need to analyze it but it doesn't harm.
3. Go to address 0 and disassemble. Four machine instructions should appear (link.w, clr.l, unlk, rts)
4. Go to address 0 and create a new function.
5. Open the "edit function" dialog and add a new parameter "int v" to the function. Close the dialog.
6. Open the "edit function" dialog again and verify that the function has now a parameter "int v" in storage "Stack[0x4]:4". The calling convention is "__stdcall" (automatically set by Ghidra).
7. Save and close the project.
8. Close Ghidra 10.2.2. If you want, you can start Ghidra 10.2.2 again and verify that the function signature is still as described in step 6.
10. Start Ghidra 10.3 and open the same project.
11. Open "test68.bin" in the code browser.
12. Say "Upgrade" when Ghidra wants to upgrade the program file. Again, analyze if you want.
13. Look at the function that you created in step 5. You can see that **the storage type of the function parameter has changed**. The storage of parameter "v" is now register "d0:4".

**Expected behavior**
Ghidra 10.3 should not change the storage types of function parameters when upgrading a project created with Ghidra 10.2.2. In the above example, the storage of the parameter "v" should stay "Stack[0x4]:4" and not change to register "d0:4" when upgrading the project.

**Attachments**
Here is the file used in the above example. It's just 12 bytes (4 machine instructions).
[test68.zip](https://github.com/NationalSecurityAgency/ghidra/files/11582360/test68.zip)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: Java 20
 - Ghidra Version: 10.2.2 and 10.3. No extensions installed.
 - Ghidra Origin: official GitHub distro

**Comment by TomFLV** [comment]
A college and myself are facing issues with a MC68332 srec. 

try below, im curious what a ghidra pro gets. 

https://drive.google.com/file/d/1tSRLstMeQLZJkmTVV97UmkoKare07e25/view?usp=share_link

**Comment by raminsadre** [comment]
@TomFLV Is this some ECU firmware? I guess this should be discussed outside github.

**Comment by ghidra1** [comment]
The cause of this behavior is a change to the compiler specification for 68000 stdcall which added the use of register allocations before stack.  We will review the ABI for this and determine if this was done in error.  This change does not impact stored data and only affects the dynamic storage allocation scheme.

While we investigate you can modify your cspec file (`Ghidra/Processors/68000/data/languages/68000.cspec`) and remove the input pentry elements which indicate the use of registers DO,A0,D1,A1 prior to stack allocations.

Based on this [ABI doc](https://m680x0.github.io/doc/abi.html) it does appear the change was incorrect and may have been targeting a different ABI or calling convention.

**Comment by ghidra1** [comment]
The 68000.cspec change appears to have been targeting the ColdFire's optional __REGABI__ and should not have been applied to the default ABI.
