### ISSUE TITLE
Symbol Tree item length

### ISSUE THREAD

**Issue by kooroshh** [NationalSecurityAgency/ghidra#54]
Symbol tree's parent maximum length limited to 2/3 char is there any option to show full name of the element ? 
![image](https://user-images.githubusercontent.com/24514663/53901490-52acd600-4054-11e9-8b15-10aac4d34f50.png)

**Comment by nneonneo** [comment]
This is intentional - symbol tree groups together multiple symbols that start with the same prefix. Expand the tree to see symbols starting with cmd.
