### ISSUE TITLE
Ghidra fails to decompile 'Low-level Error: Unable to resolve type xxx'

### ISSUE THREAD

**Issue by AminoACID123** [NationalSecurityAgency/ghidra#5403]
**Describe the bug**
Ghidra fails to decompile certain function, showing 'Low-level Error: Unable to resolve type xxx'. The analyzed program is freshly imported and default auto-analysis is carried out.

**Comment by ryanmkurtz** [comment]
Can you provide the sample binary and the function address that is having the issue?  Also, what version of Ghidra are you using?

**Comment by AminoACID123** [comment]
[snmp.zip](https://github.com/NationalSecurityAgency/ghidra/files/11612368/snmp.zip)  
The error occurs at `FUN_0001f354` with the error message 'Low-level Error: Unable to resolve type IPAddr'.
I am using Ghidra 10.3 Release version.
