### ISSUE TITLE
Copying hidden template parameters should copy the full type

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5421]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I copy `shared_ptr<>` from the cast and then try to set the type and am greeted with 'Unrecognized data type of "shared_ptr<>"'.

**Describe the solution you'd like**
Copying `shared_ptr<>` should put the full type name into the clipboard.

**Describe alternatives you've considered**
Search frantically for which of the 10000 templated `shared_ptr<>` types it actually is and then correctly set the type. Alternatively you could also search frantically for the setting that hides the template parameters and temporarily disable it (you're own funeral if you choose this route).

Seems you can also just edit the datatype to copy the name.

**Additional context**
I like complaining

**Comment by dragonmacher** [comment]
From where are you trying to copy?  It sounds like you are trying to copy from the Decompiler, since you mention the cast.  

We are considering updating the Copy Special action in the Listing to handle this case, which would leave the default WYSIWYG behavior intact.   Would this help your workflow?

**Comment by astrelsky** [comment]
> From where are you trying to copy?  It sounds like you are trying to copy from the Decompiler, since you mention the cast.  
> 
> We are considering updating the Copy Special action in the Listing to handle this case, which would leave the default WYSIWYG behavior intact.   Would this help your workflow?

It would not. I would be copying it from the decompiler window.

As far as the WYSIWYG behavior, then right clicking on a shortened template type and choosing edit data type should go to edit a type named `shared_ptr<>` for all of them even if the underlying type is `shared_ptr<int>` or `shared_ptr<float>` ?

I used to just rename grossly large templated types and classes but I don't have to bother now that the display names are shortened. It's just a pain to get the correct type name when you need it.

**Comment by sad-dev** [comment]
Perhaps some ``Action`` that calls ``ClangTypeToken.getDataType().getBaseDataType()`` or similar to fill the clipboard?

**Comment by astrelsky** [comment]
@dragonmacher a NPE can occur (and is) in `DecompilerUtils::getFunction` if `program` is null.

**Comment by ryanmkurtz** [comment]
Giver a pull.

**Comment by astrelsky** [comment]
> Giver a pull.

Will do.
