### ISSUE TITLE
ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB: GDB terminated early or could not be  executed. Check your command line.

### ISSUE THREAD

**Issue by yazigegeda** [NationalSecurityAgency/ghidra#5423]
ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB: GDB terminated early or could not be 
executed. Check your command line.

![Screenshot_2023-06-06-21-10-57-60_8659c1e795b4b4239e38d87c88c077b3](https://github.com/NationalSecurityAgency/ghidra/assets/63853093/6acddc9e-745d-46c7-bfee-84d60bbc14d0)

**Comment by d-millar** [comment]
Hmmm, apologies if this is a stupid question, but you've checked that /bin/gdb-multiarch exists, is executable, is not a link, and can run on your system from a command line?

**Comment by d-millar** [comment]
Also, given you're using "gdb-multiarch,"  are you trying to connect to a remote target, i.e. something running a gdbserver?

**Comment by d-millar** [comment]
@yazigegeda OK, that's fine, but, looking at the entry in "GDB launch command" in the Launch dialog in your snapshot, you have entered "/bin/gdb-multiarch".  Is that a mistake?  Did you want "/bin/gdb"?

**Comment by d-millar** [comment]
Hmmm, very interesting.  If you would, try starting Ghidra using "support/ghidraDebug" instead of "ghidraRun".  That will leave the cmd shell up that started Ghidra.  With luck, when you hit "Connect", there will be a stack trace (or some clue as to what's going on) in the cmd shell traffic.  Also, are there any messages in the "Debug Console" window that suggest an error?

**Comment by d-millar** [comment]
Oh, one other question:  I see that you are root in your command line.  Are you running Ghidra as root?  Is root is required to run gdb for your target?

**Comment by d-millar** [comment]
OK, two suggestions from @nsadeveloper789:

(1) Try settting "Use existing session via new-ui" on (selected) and then follow the instructions.  You will basically start gdb from the command line and enter the command the dialog provides.

(2) Attempting to get more debug information, edit "support/launch.sh" and at line 50, add:
	VMARGS_FROM_LAUNCH_SH+=("-Dagent.gdb.manager.log=true")
This will generate a log file in /home/root/.ghidra/.ghidra_10.3_PUBLIC/GDB.log

**Comment by yazigegeda** [comment]
> OK, two suggestions from @nsadeveloper789:
> 
> (1) Try settting "Use existing session via new-ui" on (selected) and then follow the instructions. You will basically start gdb from the command line and enter the command the dialog provides.
> 
> (2) Attempting to get more debug information, edit "support/launch.sh" and at line 50, add: VMARGS_FROM_LAUNCH_SH+=("-Dagent.gdb.manager.log=true") This will generate a log file in /home/root/.ghidra/.ghidra_10.3_PUBLIC/GDB.log


Following your instructions, my problem has finally been resolved
