### ISSUE TITLE
C Parser generates incomplete gdt if there's mismatched pragma region

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#5427]
**Describe the bug**
C Parser generates an incomplete gdt archive if the source code contains mismatched `#pragma region`/`#pragma endregion` directives. Ghidra doesn't show any errors. Ghidra should ignore `#pragma region`/`#pragma endregion` directives, because they are VS-only and they have no effect on compilation.

**To Reproduce**
1. Save [guidTest.prf.txt](https://github.com/NationalSecurityAgency/ghidra/files/11679279/guidTest.prf.txt) to parserprofile folder. Update the MSVC version number in the include directories to match your VS version. (But make sure you are using Windows SDK 10.0.22621. Earlier SDK may not reproduce this issue.)
2. Parse guidTest.prf in CParser. The message says the parsing is successful.
3. In Data Type Manager, close all other archives, and then click Open File Archive -> Load guidTest.gdt
4. In Data Type Manager, search for `PNDIS_OID`, `_NDIS_REQUEST_TYPE`,  and `HttpIsHostHstsEnabled`. They do not exist in guidTest.gdt, but do exist in guidTest.gdt_CParser.out

If you parse the generated `guidTest.gdt_CParser.out` itself, you still get an incomplete gdt. Now remove all lines starting with `#pragma region` and `#pragma endregion` from `guidTest.gdt_CParser.out`. Parse this file again. This time, the generated gdt is complete.

**Expected behavior**
The CParser should either report an error, or fully parse the headers.

**Attachments**
[guidTest.gdt_CParser.out.txt](https://github.com/NationalSecurityAgency/ghidra/files/11679275/guidTest.gdt_CParser.out.txt) (To reduce size, I removed empty lines and lines starting with `///`)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: JDK 17
 - Ghidra Version: 10.3 PUBLIC
 - Ghidra Origin: official

**Additional context**
This impacts parsing VisualStudio22_64.prf

**Comment by xiaoyinl** [comment]
@emteere After some trial and errors, I figured out the real cause is `#pragma region` mismatch, rather than GUID definitions. Parsing this file, [guidTest.gdt_region_removed.out.txt](https://github.com/NationalSecurityAgency/ghidra/files/11712688/guidTest.gdt_region_removed.out.txt) (all `#pragma region`/`#pragma endregion` removed), generates the expected gdt.

**Comment by emteere** [comment]
Thanks for looking into it a bit more.

I looked at it today, hoping to get a fix into the next patch.  I discovered it is related to the pragma as you found, but is simply that the parser doesn't parse ',' unless the ',' is inside of '()'.  I should have a fix in soon for you.
