### ISSUE TITLE
DemanglerCmd not work?

### ISSUE THREAD

**Issue by dark-lbp** [NationalSecurityAgency/ghidra#544]
system: OSX 10.14.4
Java Version: 12
Ghidra Version: 9.0.2

Hi, i am trying to demangle symbol name using ghidra jython api using below codes.
```python
from ghidra.app.util.demangler.gnu import GnuDemangler
from ghidra.app.cmd.label import DemanglerCmd
>>> demangler = GnuDemangler()
>>> demangler
ghidra.app.util.demangler.gnu.GnuDemangler@5df19b8a
>>> symbol_dest_address=toAddr(0x001df10c)
>>> symbol_dest_address
001df10c
>>> symbol_name_address=toAddr(0x00232ba4)
>>> symbol_name_address
00232ba4
>>> symbol_name_string = createAsciiString(symbol_name_address).getValue()
>>> symbol_name_string
u'xsputn__7filebufPCci'
>>> sym_demangled = demangler.demangle(symbol_name_string, False)
>>> sym_demangled
undefined filebuf::xsputn(char const *,int)
>>> sym_demangled_name = sym_demangled.getSignature(False)
>>> sym_demangled_name
u'undefined filebuf::xsputn(char const *,int)'
>>> demangler_cmd = DemanglerCmd(symbol_dest_address, sym_demangled_name)
>>> demangler_cmd
Demangle Symbol
>>> demangler_cmd.applyTo(currentProgram, monitor)
True
>>> function = getFunctionAt(symbol_dest_address)
>>> # Before DemanglerCmd execute
>>> function
xsputn__7filebufPCci
>>> demangler_cmd = DemanglerCmd(symbol_dest_address, sym_demangled_name)
>>> demangler_cmd.applyTo(currentProgram, monitor)
True
>>> # After DemanglerCmd execute
>>> function
xsputn__7filebufPCci
```
I found example api from [VxWorksSymTab_5_4.java](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/GnuDemangler/ghidra_scripts/VxWorksSymTab_5_4.java), but looks like `DemanglerCmd` can't demangle the function name? or i just using it incorrectly?

**Comment by emteere** [comment]
The mangled string does not have the normally present mangled prefix on it (such as _Z).

If you pass the DemanglerCmd constructor a demanglerOptions object with setDamangleOnlyKnownPatterns(false), I believe the string with demangle for you.  In your example above you call the gnu demangler directly with the **demangler.demangle(symbol_name_string, False)**, which is equivalant using the DemanglerCmd().  You may get demangled results on things that are not mangled strings, so I would only do this if you know the string is mangled.

**Comment by dark-lbp** [comment]
@emteere Thanks! 
I thought `DemanglerCmd.applyTo` will update the original mangled string.
I have one more qustion, since `demangler.demangle` result might contain function parameters, is there any api can add parameter to a function?
