### ISSUE TITLE
one byte functions

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#5441]
**Describe the bug**
Ghidra creates 1-byte functions when the function is larger.  This is an impossible value in PowerPC as instructions are fixed length 4-bytes.  Not sure what triggers it.  Clearing all options and re-disassembling does not fix. Clear Flow and Repair will fix it sometimes it appears, but not always

The decompiler will only show the function when the cursor is on the first instruction other wise it will error out with 
`Exception while decompiling aabbccdd: java.lang.NullPointerException: Cannot invoke "String.getBytes()" because "val" is null`
or
`Exception while decompiling aabbccdd: java.lang.NullPointerException:`
or show something similar to
```
undefined FUN_aabbccdd()
{
    FUN_aabbccdd();
}
```

**Environment (please complete the following information):**
 - OS: 22.04
 - Java Version: 17.0.7
 - Ghidra Version: 10.3
 - Ghidra Origin: official

**Additional context**
The 1-byte instruction has been an issue a while, and probably this is a dup issue, but I've never seen the error behavior or the calling itself

**Comment by mumbel** [comment]
https://github.com/NationalSecurityAgency/ghidra/issues/5412

somewhat related to this maybe

some of these 1 byte functions have the first instruction, but then instead of the error or calling itself on the 2nd or later instruction, the function name will change to that of the "thunk"

**Comment by astrelsky** [comment]
If I remember correctly the elf load helper class has something that specifically creates 1 byte functions. The idea being that it just creates a function and entrypoint and then the disassemble entrypoint analyzer will take it from there.

**Comment by mumbel** [comment]
No, this file has one entry and I'm seeing hundreds maybe

**Comment by emteere** [comment]
For each function that the loader sees as a potential function, a one byte function is created that is supposed to be seen by the EntryPointAnalyzer and cleaned up.  If the one byte function exists, the loader "knows" it is a function.  The idea being you don't want to kick-off a bunch of analysis as part of the import process.
It may be a bug that these are being missed and not fixed up.

It can also happen from DWARF/PDB information applied to the program.

Do you have an example?

There is a script you can run, find instructions not inside functions that can identify these cases.

It is possible #5412 and the thunk analysis is causing the issue in some way.

**Comment by emteere** [comment]
You can run analysis again and it should clean them up, but this is a bug and you shouldn't have to.

**Comment by mumbel** [comment]
I have re-run analysis multiple times (default settings)

No, sorry can't share and haven't considered any possible minimization that could be shared.

I think ELF/DWARF/loader talk is a red herring.  I did not bring up any of that since I didn't think it's relevant.  This is an ELF wrapper of firmware, all it really provides is memory mapping.  There is 1 entry at .text offset 0x0, no DWARF, no symbols, no debug, no relocations.

**Comment by emteere** [comment]
So when you import it from scratch with no analysis are there any single byte functions with no disassembly?

Just making sure, but by re-run analysis I mean without clearing or changing anything on an already analyzed program.
One byte functions should get fixed.

For these 1byte function locations how are they reached, a jump or call or no references to them?

I'll have to check the code to see where a single byte function can get created.

The decompiler error you mention sounds familiar, it should not blow up, it should have a greyed out function.

There was a bug where the creation of a function got ahead of the disassembly.  That could be what is occurring here.
The bug sounds familiar for either 10.2.x or 10.3, but you are using 10.3, so it could be a similar issue.

**Comment by mumbel** [comment]
I'll hopefully have some free time this weekend to try reloading and see if I can gather more info from a clean slate

**Comment by mumbel** [comment]
10.3.2_DEV  (dc7caf0e285914f31f0e97fc0808e20ed0c69875)

```
ERROR Unexpected Exception: Cannot invoke "String.getBytes()" because "val" is null java.lang.NullPointerException: Cannot invoke "String.getBytes()" because "val" is null
	at ghidra.program.model.pcode.PackedEncode.writeString(PackedEncode.java:162)
	at ghidra.program.model.pcode.FunctionPrototype.encodePrototype(FunctionPrototype.java:323)
	at ghidra.program.model.pcode.HighFunction.encode(HighFunction.java:453)
	at ghidra.program.model.pcode.HighFunctionSymbol.encode(HighFunctionSymbol.java:77)
	at ghidra.program.model.pcode.HighSymbol.encodeMapSym(HighSymbol.java:567)
	at ghidra.app.decompiler.DecompileCallback.encodeResult(DecompileCallback.java:823)
	at ghidra.app.decompiler.DecompileCallback.encodeFunction(DecompileCallback.java:959)
	at ghidra.app.decompiler.DecompileCallback.getMappedSymbols(DecompileCallback.java:659)
	at ghidra.app.decompiler.DecompileProcess.getMappedSymbols(DecompileProcess.java:746)
	at ghidra.app.decompiler.DecompileProcess.readResponse(DecompileProcess.java:305)
	at ghidra.app.decompiler.DecompileProcess.sendCommandTimeout(DecompileProcess.java:538)
	at ghidra.app.decompiler.DecompInterface.decompileFunction(DecompInterface.java:784)
	at ghidra.app.decompiler.component.Decompiler.decompile(Decompiler.java:57)
	at ghidra.app.decompiler.component.DecompilerManager.decompile(DecompilerManager.java:175)
	at ghidra.app.decompiler.component.DecompileRunnable.monitoredRun(DecompileRunnable.java:108)
	at ghidra.util.task.RunManager$RunnerJob.doExecute(RunManager.java:334)
	at ghidra.util.task.RunManager$RunnerJob.run(RunManager.java:309)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:1)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
  (DecompileProcess.java:351) 
```

**Comment by mumbel** [comment]
maybe a call to setBody() got lost?  I put a breakpoint there and noticed various clear and re-create the function do not hit it, should that get hit everytime or does FunctionDB cache?

along the thunk comment,  getBody() does show 1 byte function on the first instruction, the second instruction getBody shows a thunk (4 instruction) and then another entry for the first instruction last 3 bytes to the end of the function.  Other functions do call this w/o thunk.

**Comment by emteere** [comment]
The calling convention String in your example is null.  That isn't supposed to happen and was a bug fixed in 10.3.
Very strange.  Must be getting set to null somehow.  UndefinedFunction.getCallingConventionName(), which is what you should have when that exception is thrown always returns "unknown"


If you are up for some debugging.
These may get a stacktrace that leads to the culprit.  There could be a bit of indirection though, depending on if the function creation is delayed, say from a possible function start pattern.

I think these are the only two places that will actually set/change the functions body.
Could you try putting a conditional debug breakpoint in:
FunctionManagerDB.createFunction:228  condition: body.getNumAddresses() == 1

Also at:
FunctionManagerDB.createFunction:982  condition: newBody.getNumAddresses() == 1

**Comment by mumbel** [comment]
@emteere   I appreciate the effort/fix.   was able to get them all correct (3301 of 445k for this new image I started with 10.3).  I don't think the following was reliably working before, but looks good now.

function window: filter on at most 1 byte, select all, select selection
listing window: clear with options (unchecked symbol/comment/function), clear flow and repair (checked data, flow)


I don't know if you assumed it would or wouldn't, but a full auto-analysis (defaults) didn't fix any.

I don't know when I'll start a new image to see if I run into a similar situation, but will update If I do.

**Comment by emteere** [comment]
Glad the changes worked better for you.

I think the stack trace should be a separate issue.  Something is not encoding correctly to send to the decompiler.

Not sure about the auto-analysis fixing the one byte functions if you run it again.  It should, but there could have been a state that was causing it not to occur.  I'd really have to see an example of it in that state and trace why the entry point analyzer wasn't fixing them.  It checks for any one byte functions and adds them to a set to be fixed later, it will also disassemble them if there isn't any defined data at the location.

Actually, I think I might have just found why they didn't get fixed.

Was the block where there were issues marked executable?

There is currently a check to filter out any non-executable locations at the start of the analyzer.  It may also explain some of the other issues.

The single byte function entry check was done to allow an importer that knows where function starts are located to mark them for the analyzers.  If an importer were to have created the one-byte functions, then the blocks should be correctly marked RWX.  The thinking was that importing should just get the program loaded as fast as possible, then possible long-running disassembly/analysis would run later.
