### ISSUE TITLE
Local variables as branch conditions are always false, even if they are later modified to true

### ISSUE THREAD

**Issue by anydream** [NationalSecurityAgency/ghidra#545]
**Notice that this issue cannot be reproduced in decompilation of System V AMD64 ABI files**
[sample.zip](https://github.com/NationalSecurityAgency/ghidra/files/3136714/sample.zip)

**Describe the bug**
Local variables as branch conditions are always false, even if they are later modified to true.
![problematic-assembly](https://user-images.githubusercontent.com/3724537/56959615-94538c00-6b80-11e9-9ad5-5f5ee70a8949.png)

**To Reproduce**
1. Compile the following C code in Windows using clang with `-O0`:
```cpp
#include <stdio.h>
int main()
{
	int a = 0;
	int *p = &a;
	
	for (;;)
	{
		if (a)
			puts("Hello world");
		
		*p = 1;
		puts("blabla");
	}
	
    return 0;
}
```
2. Decompile generated executable
3. Ghidra produce wrong result:
```cpp
void FUN_140001000(void)
{
    do {
        if (false) {
            puts("Hello world");
        }
        puts("blabla");
    } while( true );
}
```

**Expected behavior**
The correct result should be:
```cpp
    int a = 0;
    int *p = &a;
    do {
        if (a) {
            puts("Hello world");
        }
        *p = 1;
        puts("blabla");
    } while( true );
```

**Environment:**
 - OS: Windows 7 x64 SP1
 - Java Version: 11.0
 - Ghidra Version: 9.0.2

**Comment by saruman9** [comment]
Can't reproduce on Linux and Ghidra builded from 1cae5552 commit.
![2019-04-30_114904_564687992](https://user-images.githubusercontent.com/4244396/56950481-4322a880-6b3e-11e9-856c-4191fd056dfb.png)

**Comment by anydream** [comment]
[sample.zip](https://github.com/NationalSecurityAgency/ghidra/files/3130988/sample.zip)

I have uploaded Windows x64 sample.
Has that issue been fixed?

**Comment by caheckman** [comment]
I'm reproducing this. Thanks for the example. Stack analysis is being too cavalier with the (very unoptimized) constant stack reference stored on the stack . Trying to get a fix into master for the next update.

**Comment by caheckman** [comment]
Fix is in master. Closing
