### ISSUE TITLE
CParser can't parse pragma region with parentheses

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#5454]
**Describe the bug**
C Parser can't parse lines like this:
```
#pragma region System Family (kernel drivers) with Desktop Family for compat
```

**To Reproduce**
Parse the following C code in Ghidra CParser (x86:LE:64:default / windows):
```
#pragma region System Family (kernel drivers) with Desktop Family for compat
int functionA(int a, char *b);
#pragma endregion
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.7
 - Ghidra Version: 10.4 DEV 9e8392187201128bad2b2b2daa1dc5eb37a9b4ca
 - Ghidra Origin: locally built 

**Additional context**
This causes failure when parsing Windows WDK ndis.h.

**Comment by emteere** [comment]
Missed this one for the release.  Should have a fix for this soon, as well as #4692

The silently failing will also be fixed, so these types of issues will be much easier to diagnose.
