### ISSUE TITLE
Low-level Error: Cannot specify logical size for multiple piece join

### ISSUE THREAD

**Issue by itscharlie0110** [NationalSecurityAgency/ghidra#5457]
**Describe the bug**
I am trying to decompile some functions in a file. However, a lot of them fail and give me the error "Low-level Error: Cannot specify logical size for multiple piece join"

**Expected behavior**
I expected the code to be decompiled as it has been for many other functions within the same file.

**Attachments**
[libil2cpp.zip](https://github.com/NationalSecurityAgency/ghidra/files/11753474/libil2cpp.zip)
One problematic function:

Name: PlayerScript$UpdateFast | Address: 00d0eb78 | Size: 11212

**Environment (please complete the following information):**
 - OS: Windows 10 22H2
 - Java Version: 20
 - Ghidra Version: 10.2.3
 - Ghidra Origin: Official Github

**Comment by ryanmkurtz** [comment]
Can you supply some function addresses that produces the error?  I'm not seeing any with random clicking.

**Comment by ryanmkurtz** [comment]
Also, if you wouldn't mind, could you try out Ghidra 10.3.1?  That's what I was going to start with.

**Comment by itscharlie0110** [comment]
Hello, I did supply a function address, aswell as the function size (possibly could find it in the function list?). I do not know if the file I shared contains the function names so I will try and do that later. I will try using the suggest version and see if that does anything, will share my results later!

**Comment by itscharlie0110** [comment]
I updated to version 10.3.1 and it solved the issue. Thanks!!
