### ISSUE TITLE
decompiles bic instruction incorrectly

### ISSUE THREAD

**Issue by Muqi-Zou** [NationalSecurityAgency/ghidra#5458]
I run the latest version of Ghidra on a Nordic nrF52 PCA10040 firmware, which is ARMv7-M 32 bits. 
I choose the language ID: ARM:LEBE:32:v7LEInstruction (1.107) for Ghidra.
As you can see from the following picture, `r0 `  [subs](https://developer.arm.com/documentation/dui0473/m/arm-and-thumb-instructions/sub)  `r1` first. After that, `r0` [bic](url) with `0xff000000`. 
However, the return value is `param_1 - param_2 & 0xffffff;` rather than `(param_1 - param_2) & 0xffffff;`
![1686900433973](https://github.com/NationalSecurityAgency/ghidra/assets/54459497/61d5422e-a4d0-43f1-88a9-a6c83cd07ab4)

the binary for testing is attached
[nrf52_pca10040.zip](https://github.com/NationalSecurityAgency/ghidra/files/11767522/nrf52_pca10040.zip)

**Comment by astrelsky** [comment]
`param_1 - param_2 & 0xffffff;` and `(param_1 - param_2) & 0xffffff;` are equivalent.

https://en.cppreference.com/w/c/language/operator_precedence

**Comment by Muqi-Zou** [comment]
Ah, you are right, thanks!

**Comment by Muqi-Zou** [comment]
> `param_1 - param_2 & 0xffffff;` and `(param_1 - param_2) & 0xffffff;` are equivalent.
> 
> https://en.cppreference.com/w/c/language/operator_precedence

Hold on, this is not true. "-" in this issue is subtraction, not unary minus. Hence, `param_1 - param_2 & 0xffffff; `is same as `param_1 - (param_2 & 0xffffff);`, which is not same as `(param_1 - param_2) & 0xffffff;`

**Comment by astrelsky** [comment]
> > `param_1 - param_2 & 0xffffff;` and `(param_1 - param_2) & 0xffffff;` are equivalent.
> > https://en.cppreference.com/w/c/language/operator_precedence
> 
> Hold on, this is not true. "-" in this issue is a subtraction, not a unary minus. Hence, `param_1 - param_2 & 0xffffff; `is same as `param_1 - (param_2 & 0xffffff);`, which is not same as `(param_1 - param_2) & 0xffffff;`

It is subtraction which has precedence 4 vs bitwise AND with precedence 8.

Here is some proof.
https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:13,endLineNumber:10,positionColumn:13,positionLineNumber:10,selectionStartColumn:13,selectionStartLineNumber:10,startColumn:13,startLineNumber:10),source:'%0Aint+fun1(int+param_1,+int+param_2)+%7B%0A++++return+param_1+-+param_2+%26+0xffffff%3B%0A%7D%0A%0Aint+fun2(int+param_1,+int+param_2)+%7B%0A++++return+(param_1+-+param_2)+%26+0xffffff%3B%0A%7D%0A%0Aint+reversed(int+param_1,+int+param_2)+%7B%0A++++return+param_1+-+(param_2+%26+0xffffff)%3B%0A%7D%0A%0Aint+main()+%7B%0A++++%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:40.523138774380634,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1600,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O3',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+16.0.0+(Editor+%231)',t:'0')),k:27.329558708303217,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+16.0.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+16.0.0+(Compiler+%231)',t:'0')),k:32.14730251731615,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by Muqi-Zou** [comment]
mb, You are right
