### ISSUE TITLE
Building extension fails due to non existent help

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5459]
**Describe the bug**
Attempting to build a plugin where `src/main/help/help` doesn't exist will fail.
```
> Task :indexHelp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':indexHelp' (type 'JavaExec').
  - Type 'org.gradle.api.tasks.JavaExec' property '$1' specifies directory '{PLUGIN_PATH}\src\main\help\help' which doesn't exist.

    Reason: An input file was expected to be present but it doesn't exist.

    Possible solutions:
      1. Make sure the directory exists before the task is called.
      2. Make sure that the task which produces the directory is declared as an input.
```

**Expected behavior**
No such requirement.

**Environment (please complete the following information):**
 - Ghidra Version: 10.4_DEV 176bdea28ac55c7d6838c512ae966cdf3b3cd589

**Comment by dragonmacher** [comment]
Perhaps this is a philosophical issue.  You have a build file to which you have applied the gradle help plugin, but your module does not have help files, at least not yet.    We could have the gradle help plugin be smart enough to just emit a message and not fail.   I'm not sure how much this issue will occur outside of initial project setup.

I don't have a good sense of what the 'gradle way' is in this case.   If you apply the gradle java plugin, but have no source folders, is that a build failure?

**Comment by astrelsky** [comment]
It will never have help files. I have also noted in the past with other plugins that if the default help TOC file from the skeleton plugin is in the repo, building will also fail because it references something that doesn't exist.

I'm not sure what the change is/was as I did not change anything on my end and this was never an issue.

**Comment by dragonmacher** [comment]
> I'm not sure what the change is/was as I did not change anything on my end and this was never an issue.

The `helpProject.gradle` has had extensive changes recently.

My working assumption is that you have a custom module that is failing and that module has a build.gradle file with this entry:
```
apply from: "$rootProject.projectDir/gradle/helpProject.gradle"
```
Can you verify this is the case?

**Comment by astrelsky** [comment]
> > I'm not sure what the change is/was as I did not change anything on my end and this was never an issue.
> 
> The `helpProject.gradle` has had extensive changes recently.
> 
> My working assumption is that you have a custom module that is failing and that module has a build.gradle file with this entry:
> 
> ```
> apply from: "$rootProject.projectDir/gradle/helpProject.gradle"
> ```
> 
> Can you verify this is the case?

It is more or less this. You'll encounter other problems if you try to build this but those are unrelated since I have them "fixed" locally.
https://github.com/astrelsky/GhidraOrbis/blob/master/build.gradle

**Comment by dragonmacher** [comment]
Ok.  I think I see the issue.  Thanks!
