### ISSUE TITLE
 -D__builtin_va_list=void * not respected?

### ISSUE THREAD

**Issue by arminfelder** [NationalSecurityAgency/ghidra#546]
I tried to parse jni.h with the following arguments:
-D__STDC__
-D_POSIX_C_SOURCE
-D_BSD_SOURCE
-D__WORDSIZE=32
-D__builtin_va_list=void *
-D__DO_NOT_DEFINE_COMPILE
-D_Complex
-D_WCHAR_T
-D__NO_STRING_INLINES
-D__NO_LONG_DOUBLE_MATH
-D__signed__
-D__extension__=""
-D_Bool="bool"
-D__GLIBC_HAVE_LONG_LONG=1
-Daligned_u64=uint64_t

but it fails at the first occurrence of va_list , like "-D__builtin_va_list=void *" is not respected at all, the only way for me to get it parse is, to manually replace va_list with void* in the header file

**Comment by 0x6d696368** [comment]
`-D__builtin_va_list=void *` only defines `__builtin_va_list` to `void *`. Every occurrence of `va_list` will be unaffected.

**Comment by arminfelder** [comment]
ah, of course, thanks!
