### ISSUE TITLE
Decompiler RuleSubNormal breaks Split Varnode after first operation

### ISSUE THREAD

**Issue by ajmurphy520** [NationalSecurityAgency/ghidra#5473]
**Describe the bug**
Program on x86 uses 64 bit fixed point class internally. Fixed point multiplication is result = ((long long * long long) >> fractionBits). Decompiler rule DoubleIn correctly identifies 4 registers going into multiply function as two sets of double precision fields but the right shift after multiplication gets processed by RuleSubNormal into a form where double precision rules will not recognize the output of the shift as a double precision field. This causes all dependent operations to not be double precision.

Testing with locally build decompiler with RuleSubNormal disabled fixes the issue

**Expected behavior**
Generic decompilers rules should not prevent double precision rules from being applied more than once

**Screenshots**
With release decompiler
![image](https://github.com/NationalSecurityAgency/ghidra/assets/26012394/998d1969-3e42-4c3d-b84b-316ef2edf4dd)

with RuleSubNormal disabled (locally built)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/26012394/fa778cac-ff10-44c4-a456-be184f423ede)

**Attachments**
10.3.1 decompiler debug output
[calcFactory.zip](https://github.com/NationalSecurityAgency/ghidra/files/11820245/calcFactory.zip)

**Environment (please complete the following information):**
 - Ghidra Version: 10.3.1
 - Ghidra Origin: Official distribution

**Comment by ajmurphy520** [comment]
I added check to subnormal that I believe fixes the issue. On line 7247 I added this check
if ((op->getOut()->isPrecisLo() || op->getOut()->isPrecisHi()) && (insize - c - outsize)*8 != n) return 0;

**Comment by MarcusMWilliams** [comment]
1(225)-955-5783 Marcus Maurice Williams

**Comment by MarcusMWilliams** [comment]
Sorry wrong number,new number 1(225)-436-8491
