### ISSUE TITLE
Inlining function hangs Ghidra

### ISSUE THREAD

**Issue by madebr** [NationalSecurityAgency/ghidra#5474]
**Describe the bug**
When marking some functions as inline, Ghidra hangs.
Process Managers shows 100% usage on the core on which Ghidra is running.

**To Reproduce**
1. Download, import, open and run analysis on `LEGO1.DLL`
2. Go to `0x1003d281`
3. Right click and select `Edit Function Signature`
4. In the dialog, enable the `In Line` check box
5. Press OK

**Expected behavior**
Function is marked inline. When it is called somewhere, it is inlined.

**Screenshots**
none

**Attachments**
 [`LEGO1.DLL`](https://legoisland.org/download/LEGO1.DLL)

**Environment (please complete the following information):**
 - OS: Fedora Linux 38
 - Java Version: OpenJDK 20.0.1
 - Ghidra Version: 10.3
 - Ghidra Origin: official GitHub distro

**Additional context**
https://github.com/isledecomp/isle

**Comment by mumbel** [comment]
Have you tried 10.3.1?  Several 10.3 issues were closed for fixing inline analysis in 10.3.1

**Comment by madebr** [comment]
I was just about to say I just updated and it got fixed.
Thanks for the quick answer.
