### ISSUE TITLE
ghidra server: Connection to server failed

### ISSUE THREAD

**Issue by Kerblif** [NationalSecurityAgency/ghidra#5478]
I've set up a ghidra server and wireguard.

Wireshark shows that the request goes through, but there was no response. What could be the error?
![image](https://github.com/NationalSecurityAgency/ghidra/assets/44944577/7e318fc8-398a-43ef-aff2-ec0aedea6c45)

The following parameters were set in ghidra:

> wrapper.app.parameter.1=-a0
wrapper.app.parameter.2=-u
wrapper.app.parameter.3=-i 192.168.200.1 
wrapper.app.parameter.4=${ghidra.repositories.dir}

I've get this in console:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/44944577/bf271e88-406f-4b9f-be66-b795352e9db1)

And this in client:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/44944577/095a6f66-6303-4feb-b5a6-2590182c43ad)

By the way, when the ghidra client is launched on the server, the connection occurs.

**Comment by dev747368** [comment]
If the packet was getting through your server's firewall, there should be a response from the server's ip back to the client to establish the tcp connection.

Double check your server's firewall configuration.

**Comment by Kerblif** [comment]
Thank you, it helped
I completely forgot about firewall...
