### ISSUE TITLE
de-compile error - Pcode: XML comms: Unknown tag in function: scope 

### ISSUE THREAD

**Issue by godengo** [NationalSecurityAgency/ghidra#549]
**Describe the bug**
de-compile error - Pcode: XML comms: Unknown tag in function: scope 

1. De-compile error reported from:
ghidra/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/HighFunction.java/readXML():
...
			else {
				throw new PcodeXMLException("Unknown tag in function: " + subel.getName());
			}

2. Code to deal with scope tag commented out in (may not be germane): 
ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/funcdata.cc/restoreXml()
...
    //    else if ((*iter)->getName() == "scope") {
    //      const Element *scopeel = *iter;
    //      ScopeInternal *subscope = new ScopeInternal("",glb);
    //      subscope->restrictScope(this);
    //      glb->symboltab->restore_nonglobal_xml(scopeel,subscope);
    //    }

3.  Error signature from Debug Function Decompilation XML file contains the following extra tags:
</symbollist>
</scope>
<scope name="">
<parent>
</parent>
<symbollist> 

4.  Decompilation error can be resolved using Repair flow and selecting clear symbols

**To Reproduce**
same de-compile error occurred on several functions and in several binaries analyzed - cannot share binaries

**Expected behavior**
successful de-compile

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: MS Windows 10 Pro 
 - Java Version: openjdk 11.0.2
 - Ghidra Version: 9.0.2

**Additional context**

**Comment by caheckman** [comment]
I think I'm duplicating this.  Working on a fix.

**Comment by caheckman** [comment]
Committed a fix to master that should be available with the next update.
