### ISSUE TITLE
Parsing c source to program fails 

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5502]
**Describe the bug**
Attempting to parse c source to program results in a popup stating "A program architecture must be specified in order to parse to a file". Since I am parsing to the program and not to a file, this should not occur.

**To Reproduce**
1. Setup "Parse C Source" window to parse any trivial header.
2. Click "Parse to Program"
3. See error

**Comment by emteere** [comment]
You are right it should just parse using the Processor Architecture of the program being parsed into.
