### ISSUE TITLE
Support platform standard keyboard edit operations

### ISSUE THREAD

**Issue by tamlin-mike** [NationalSecurityAgency/ghidra#5505]
It would be nice if platform standard editing keys were working.

On Windows there are two sets of keyboard combinations for cut/copy/paste, both cemented since the very beginning of the platform.

First we have the beginners version:
- Cut: Ctrl+X
- Copy: Ctrl+C
- Paste: Ctrl+V.

They are currently the only ones that seems to work in Ghidra.

For more seasoned keyboard-warriors we have the following combos (part of what makes it possible to perform editing and navigation operations with one hand only, and without having to reposition that hand):
- Cut: Shift+Del
- Copy: Ctrl+Ins
- Paste: Shift+Ins

These do not work in Ghidra.

The lack of this basic functionality has many times led to stale data on the clipboard, resulting in great confusion, wrong information pasted, mis-navigation and some gnashing of teeth.

(I was torn between tagging this as a bug of feature request, due to the magnitude of of the omission)

**Comment by fenugrec** [comment]
I've personally found that shift+del, in e.g. text editors, can be sometimes really annoying. Example : to delete the end of a line : shift+end ; shift+del , it's easy to not quite release Shift enough, so you end up overwriting your clipboard instead of deleting. If I had a dollar every time I did that...

And as you know, many "popular" shortcuts inherited from windows assume a left hand on the left side of a QWERTY layout anyway : ctrl+A, S, W, R, Z,X,C,V ...

Out of curiosity, are you left handed ? Or using a non-standard kbd layout ?

**Comment by dragonmacher** [comment]
Java text widgets should support this by default (e.g., Text Areas, Text Fields, etc).  Java actions are different than the actions provided by Ghidra.  

Ghidra has actions for copy in a few places in the system.  Each Ghidra action is optionally bound to 1 keybinding.     There is currently no support for allowing multiple bindings to a single action.   Further, the system does not support adding duplicate actions, which prevents us from simply installing another version of the copy action with an alternate binding.   Thus, for us to support this request would require architectural changes.

You can change the default keybindings for the cut/copy/paste to be any binding you choose.   But, you cannot have those  actions respond to 2 different bindings, as mentioned above.   Thus, if you prefer `Ctrl-Ins` for `Copy`, then you can set that as the binding, but you will then lose the ability to use `Ctrl-C` for `Copy`.

While I appreciate the utility of your request, I cannot envision any other actions that would benefit from supporting multiple key bindings.  The amount of work required to update the system to support this for cut/copy/paste makes request a low priority for us.    Contrastingly, if other uses for this proposed feature arise, then we can re-evaluate the cost-benefit.

**Comment by tamlin-mike** [comment]
@fenugrec 
> If I had a dollar every time I did that...

Seems we have very different experience in this area. I have performed that operation probably millions of times over decades, and I can't recall ever having experienced that problem.

> Out of curiosity, are you left handed ?

No, these edit operations are simply committed to muscle memory since decades to do all text position and cut/copy/paste operations single-handed. I do a lot of code editing.

As for the "popular" shortcuts, I wouldn't say Ctr+W is especially popular. Depending on application it can be Write (a.k.a. Save), Close Window, Select Word, Erase Previous Word, ... (well, maybe that makes it popular, but certainly not consistent) :)

> Or using a non-standard kbd layout ?

Depends on what "non-standard" means to you. It's not en-US, but it is QWERTY.

Speaking of keyboard layout, Ghidra is is really only suitable for en-US kbd out-of-the-box. A very common operation is to create an array. On my kbd layout (.se) it's with Ghidra's current shortcuts in combination with its input handling method literally impossible to create an array with the default keyboard shortcut. So while that specific train has already left the station, it could perhaps provide food for thought on any future keyboard mappings.

@dragonmacher
>  Further, the system does not support adding duplicate actions [...]
> While I appreciate the utility of your request, I cannot envision any other actions that would benefit from supporting multiple key bindings

I can. I'm sure there must be some kind of keyboard input to cancel the "persistent selection" mode. I'd map Esc to it in a heartbeat if I knew how. Heck, make it double-Esc for all I care, so long as I can escape from the mode without being forced to change hand positions.

And for non-text-input-requiring dialogs, standard operations to move between buttons like Cursor-Left/Right key inputs to move between buttons don't work. That would be another mapping I'd add.

One could also add that an interactive application not behaving as expected in one of the most basic editing operations there are is a rather noticable omission of functionality, especially since literally _every_ other application _do_ behave properly.

But I understand your comment was not to solicit further input, but simply to convey "wontfix", so I won't bother you further with issues of badly designed UI/UX and improvements to it.

**Comment by fenugrec** [comment]
> > Out of curiosity, are you left handed ?

> No, these edit operations are simply committed to muscle memory

Yes, I'm ready to believe that, I also work a lot from the kbd; I just don't see how you're keeping your left hand at the left end of the kbd and somehow span left-ctrl + ins/del which is typically way at the other end of the kbd ? Or you move your left hand to the area near enter/backspace and use the right-ctrl + ins ? but that would be self-defeating.

> (well, maybe that makes it popular, but certainly not consistent) :)

Yes, I could have worded that differently; ignoring inconsistencies outside of the mostly-standard  S,Z,X,C,V;  the left quadrant is usually mapped to the more-useful-actions. Usually. Yes, I know about ctrl+O, ctrl+P, etc...


> Speaking of keyboard layout, Ghidra is is really only suitable for en-US kbd out-of-the-box.

Well that is understandable, given its history P )

Array shortcut :  agreed, actions mapped to < > { } [ ] quickly become usable on other layouts. I frequently alternate between 2 layouts and I find it just easier to use en-us in a lot of programs, rather than remembering where they hid '>' or '~' on whatever layout I'm using.

**Comment by dragonmacher** [comment]
> I can. I'm sure there must be some kind of keyboard input to cancel the "persistent selection" mode. I'd map Esc to it in a heartbeat if I knew how. Heck, make it double-Esc for all I care, so long as I can escape from the mode without being forced to change hand positions.
> 

You can do this now, assuming you mean using `Escape` to clear the selection.
- From the file menu press `Select`  
- Hover your mouse over `Clear Selection`
- Press `F4`
- Press `Escape` in the new dialog
- Press `OK`

This will bind `Escape` to clearing the selection.

> And for non-text-input-requiring dialogs, standard operations to move between buttons like Cursor-Left/Right key inputs to move between buttons don't work. That would be another mapping I'd add.

Fixing navigation is something we are actively working on.  This is a big effort and will take some time.  When complete, you should be able to navigate the entire application from the keyboard.

> One could also add that an interactive application not behaving as expected in one of the most basic editing operations there are is a rather noticable omission of functionality, especially since literally _every_ other application _do_ behave properly.
> 

This is a tricky thing to get right, considering there is no universal standard for UI/UX design.   To make the issue worse, Ghidra pre-dates some of the more modern application design paradigms.  At this point, being consistent within Ghidra is a major priority.   For other workflow issues, we rely on user feedback to take corrective action.   

> But I understand your comment was not to solicit further input, but simply to convey "wontfix", so I won't bother you further with issues of badly designed UI/UX and improvements to it.

Actually, I did intend to solicit more potential use cases specifically for mapping multiple keystrokes to the same action.   Fixing workflow issues is one of our higher priorities.  Naturally, some poor UI/UX issues are more deeply ingrained than others and will thus be more difficult and expensive to fix.

I did not mention this earlier explicitly, but, in case you were not aware, most Ghidra action keybinding can be changed in the options, which is accessible via the menu at `Edit` -> `Tool Options` -> `Key Bindings`.    With that being said, that dialog will not allow you to have copy/cut/paste bound to multiple bindings.   But, you can change them to your preferred bindings.
