### ISSUE TITLE
6809 decompiler: BNE ignores result of previous instruction

### ISSUE THREAD

**Issue by hjanetzek** [NationalSecurityAgency/ghidra#5508]
**Describe the bug**
I found several cases where the state of zero flag is not considered by BNE instruction decompilation. The screenshots show `while(true)` loops which are generated for `CMPA, BNE` and `DEC, BNE` instructions. The rom that I used runs correctly when tested in MAME.

**To Reproduce**
When needed I can provide the rom or the Ghidra project 
 
**Expected behavior**
The `while()` loop should depend on the the state of the status register  

**Screenshots**
![shot-2023-06-24_16-30-04](https://github.com/NationalSecurityAgency/ghidra/assets/1747/01a0b157-cc99-4b72-9a71-9ef2bb5a6fbc)
![shot-2023-06-28_20-08-55](https://github.com/NationalSecurityAgency/ghidra/assets/1747/98e105f0-8fc5-4163-8a14-34882fe2af8c)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Java Version: openjdk 20.0.1
 - Ghidra Version: 10.3
 - Ghidra Origin: Arch community repo

**Comment by hjanetzek** [comment]
Could this be related @GhidorahRex? https://github.com/NationalSecurityAgency/ghidra/commit/52d4aaf28584b4ff4b19070496b024d386316601

**Comment by hjanetzek** [comment]
ok, it appears to have to do with the S register - patching the DEC instruction to work U or X instead of S changes the decompilation result
![shot-2023-06-29_15-13-14](https://github.com/NationalSecurityAgency/ghidra/assets/1747/1cb14faa-33e9-4d43-b90a-57baf5e7ac45)

**Comment by GhidorahRex** [comment]
> Could this be related @GhidorahRex? [52d4aaf](https://github.com/NationalSecurityAgency/ghidra/commit/52d4aaf28584b4ff4b19070496b024d386316601)

I don't think so, but maybe. If that didn't resolve the issue, then it's probably not related.

If you edit the Listing Fields in the listing window and enable the PCode field it may be easier to see what's going on with the DEC instruction. I think the issue may be with the effective address calculation in the operand field.

**Comment by hjanetzek** [comment]
sorry forgot about the PCode column.. 
Apart from the first line (COPY S / COPY U) the DEC PCode looks identical

![shot-2023-06-29_16-03-55](https://github.com/NationalSecurityAgency/ghidra/assets/1747/39d1bd75-acaf-40d6-8548-119ac9bbdf31)
![shot-2023-06-29_15-59-34](https://github.com/NationalSecurityAgency/ghidra/assets/1747/e54a35b0-0100-47ae-8c6b-72063f274361)

**Comment by hjanetzek** [comment]
For the second case I've changed ADDA, CMPA to ADDB, CMPB which makes it produce a sensible decompilation result
![shot-2023-06-29_21-24-21](https://github.com/NationalSecurityAgency/ghidra/assets/1747/6c8264e5-f8e0-48e0-8b47-8968158b02ad)
![shot-2023-06-29_21-23-27](https://github.com/NationalSecurityAgency/ghidra/assets/1747/9e6a0133-0f92-4eaa-84ca-33e385e0f204)

**Comment by Pinoerkel** [comment]
> For the second case I've changed ADDA, CMPA to ADDB, CMPB which makes it produce a sensible decompilation result 

Hmmm, your comment made me check the instructions, you mentioned. To me, the definition of ADDB in 6x09.sinc looks fishy when compared to ADDA. setHFlag is called with A as the first parameter. Should it not be called with B? But then again, in your case you say, the ADDA, CMPA sequence does not behave as expected. So maybe it is a separate issue.
```
:ADDA OP1    is (op=0x8B | op=0x9B | op=0xAB | op=0xBB) ... & OP1
{
        setHFlag(A, OP1);
        addition(A, OP1);
}

:ADDB OP1    is (op=0xCB | op=0xDB | op=0xEB | op=0xFB) ... & OP1
{
        setHFlag(A, OP1);
        addition(B, OP1);
}
```

**Comment by GhidorahRex** [comment]
that flag in `ADDB` is definitely an issue, but I don't think it's what's going on here to cause these decompilation issues.

**Comment by Pinoerkel** [comment]
Yes, the half carry flag seems to get used quite rarely. If the issue is related to address computing, maybe the issue I found earlier in the [PUSHU](https://github.com/NationalSecurityAgency/ghidra/issues/5467) command is a possible fix. However, in the small code snippets posted here, I can not see a direct connection to this issue.

**Comment by hjanetzek** [comment]
Hey @Pinoerkel I've tried master with your changes (and compiled with sleigh) which made no difference for this issue. Would it help to upload my archived project here?

**Comment by Pinoerkel** [comment]
> Hey @Pinoerkel I've tried master with your changes (and compiled with sleigh) which made no difference for this issue. Would it help to upload my archived project here?

Hi. Uploading the project may not be necessary. I have constructed a minimal example for your first error case to reproduce the error and I too have the impression that the issue is connected to the stack register S. Basically what messes up your first example loop ist the BSR call to the _maybe_write_serial_display_ subroutine. On calling that, the stack register is of course pushed and pulled upon return. Something on the way seems to mess everything up. For that to happen, the function called does not even have to do anything but to NOP and RTS. You can check that by replacing the BSR instruction in your first example with two NOPs (opcode 12) to just not call it. The culprit candidates on your second example are the LBSR and PULS commands, but I did not test that yet.

**Comment by hjanetzek** [comment]
@Pinoerkel thanks for looking into it! This is currently a test project for me to see if I could reverse engineer a huge multiprocessor 6809 based device :)

I was just about to file an issue for the `compare` macro. Though if you have a PR in progress could you add this?
```
macro compare(reg, op)
{
        $(V) = sborrow(reg, op);
        local tmp = reg - op;
        setNZFlags(tmp);
---        $(C) = (tmp < op);
+++        $(C) = (reg < op);
}
```

**Comment by Pinoerkel** [comment]
> @Pinoerkel thanks for looking into it! This is currently a test project for me to see if I could reverse engineer a huge multiprocessor 6809 based device :)

Same here. I am just on a bug extermination mission to get some reverse engineering done. ;-)

> I was just about to file an issue for the `compare` macro. Though if you have a PR in progress could you add this patch?

Nice find. However, if you are correct, then the `subtraction `macro is also wrong and most likely the initial cause, why the `compare ` macro was messed up. Maybe, those two should look like this:
```
macro subtraction(reg, op)
{
        $(V) = sborrow(reg, op);
        $(C) = (reg < op);
        reg = reg - op;
        setNZFlags(reg);
}

macro compare(reg, op)
{
        $(V) = sborrow(reg, op);
        $(C) = (reg < op);
        local tmp = reg - op;
        setNZFlags(tmp);
}
```

**Comment by Pinoerkel** [comment]
I most likely have found the issue and it is a quite impactful one. The `Push2` and `Pull2` macros for 16 bit registers did apparently not use the correct endianness. The 6809 is big-endian, so the two macros in 6x09.sinc :
```
# Push 2 byte operand op2
macro Push2(reg, op)
{
        reg = reg - 1;
        *:2 reg = op;
        reg = reg - 1;
}

# Pull 2 byte operand op2
macro Pull2(reg, op)
{
        reg = reg + 1;
        op = *:2 reg;
        reg = reg + 1;
}
```
should most likely look like:
```
# Push 2 byte operand op2
macro Push2(reg, op)
{
        reg = reg - 2;
        *:2 reg = op;
}

# Pull 2 byte operand op2
macro Pull2(reg, op)
{
        op = *:2 reg;
        reg = reg + 2;
}
```
at least for me, this solves the issue with my minimal example. @hjanetzek: Can you please test this with your original issues?

**Comment by hjanetzek** [comment]
yea looks much better :)
![shot-2023-07-02_22-56-56](https://github.com/NationalSecurityAgency/ghidra/assets/1747/b00fdaa6-3e2b-45e1-9511-55b4c533090d)

Still seeing a some problems e.g. with auto-increment stack pointer in `ADDD ,S++` but that is for another issue

**Comment by GhidorahRex** [comment]
I can get fixes for these put in. Can't believe I missed the `compare` one!

**Comment by Pinoerkel** [comment]
@GhidorahRex : Thank you for the effort you put into this.

**Comment by Pinoerkel** [comment]
@GhidorahRex : I just noticed that in your version of the corrected `compare` macro with the addition of temporary variables, the register is modified at the end, although it should not be modified(in contrast to the `subtraction` macro).
