### ISSUE TITLE
Include ghidra jars in the SBoM

### ISSUE THREAD

**Issue by prabhu** [NationalSecurityAgency/ghidra#5513]
**Is your feature request related to a problem? Please describe.**
Currently, only external jars are included in the bom.json that gets included in the released zip.

https://github.com/NationalSecurityAgency/ghidra/blob/d2be76feb7ed755bb8474cfc1d5bcba7851ba3a1/gradle/support/sbom.gradle#L138

While such a list of external dependencies is useful for license compliance use cases, a comprehensive SBoM, including ghidra jars, is mandatory for vulnerability management use cases.

**Describe the solution you'd like**
Remove this condition - https://github.com/NationalSecurityAgency/ghidra/blob/d2be76feb7ed755bb8474cfc1d5bcba7851ba3a1/gradle/support/sbom.gradle#L147

Ensure sbom.gradle is invoked from the ROOT_PROJECT_DIR instead of `destinationDir` since some jars belonging to the GPL directory was also not found in bom.json

https://github.com/NationalSecurityAgency/ghidra/blob/d2be76feb7ed755bb8474cfc1d5bcba7851ba3a1/gradle/root/distribution.gradle#L360

```
# GPL directory
GPL/DMG/data/lib/hfsx_dmglib.jar
GPL/DMG/data/lib/hfsx.jar
GPL/DMG/data/lib/iharder-base64.jar
GPL/DMG/data/lib/DMG.jar
GPL/DMG/data/lib/csframework.jar
```

**Describe alternatives you've considered**
Generating SBoM with [cdxgen](https://github.com/CycloneDX/cdxgen), which generated a better list with 159 components (vs current 111) but did miss a few.

```
cdxgen -t jar -o cdxgen-sbom.json --deep .
jq '.components | length' cdxgen-sbom.json
159
```

**Additional context**

**Comment by ryanmkurtz** [comment]
I'm not sure why I didn't include the Ghidra jars...I'm going out of my way to exclude them.  I can make that change.

Would you mind including a list of all the missed components?  I can also look into getting them included.

**Comment by prabhu** [comment]
@ryanmkurtz Thank you so much for looking into this! The results from cdxgen aren't perfect, so I am looking into this [separately](https://github.com/CycloneDX/cdxgen/issues/374).

The current ground truth is the output from the find command for jars alone.

[jars.txt](https://github.com/NationalSecurityAgency/ghidra/files/11916021/jars.txt)

But note that ghidra does include more Python packages and other scripts, so a full comprehensive sbom will require generating (and merging) multiple SBoM files, and we might be in a situation where no tool is perfect.
