### ISSUE TITLE
Import fails to identify x86 programs

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5518]
**Describe the bug**
Commit 0c39626b73fa9a2fb068d870295bf8e488debc72 broke the identification of ELFs for `x86:LE:64:default:gcc`.

**To Reproduce**
1. Import an elf previously automatically identified as `x86:LE:64:default:gcc`

**Additional context**
Using the `x86.ldefs` file from the prior commit fixed the problem.

**Comment by xiaoyinl** [comment]
PE files are not identified as x86:LE:64:default:windows too.
<img width="376" alt="pe_language_not_detected" src="https://github.com/NationalSecurityAgency/ghidra/assets/16713498/df5d0fb0-590b-4a07-982b-75bf466421f4">
