### ISSUE TITLE
C parser fails on #pragma spanning multiple lines

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#5524]
**Describe the bug**
`#pragma` directives that are split into multiple lines via the `\` line continuation character are handled as if they span just one line.

**To Reproduce**
1. Open an instance of the Code Browser tool
2. Select "Parse C Source" from the "File" menu
3. Have one or more header files in the source files list that have a `#pragma` directive spanning multiple lines via the `\` line continuation character
4. Start the parsing process (any parse configuration, include paths do not matter, parse options do not matter either, and either choosing "Parse to Program" rather than "Parse to File..." will trigger the error)
5. The parsing process will not succeed

**Expected behavior**
`#pragma` directives spanning multiple lines are properly handled.

**Screenshots**

![Screenshot_20230704_061816](https://github.com/NationalSecurityAgency/ghidra/assets/235740/9b1f1d24-4fef-4afe-b057-8b7384904ad6)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Linux Arch x86-64
 - Java Version: 17.0.7
 - Ghidra Version: Github commit `c66ad6b047255f9e218dfe7051f3e0e065d0340d`
 - Ghidra Origin: locally built

**Additional context**
The grammar bit handling `#pragma` directives is technically correct in assuming directives do not span more than one line, but that is valid only *after* a preprocessor pass.  The C preprocessor joins all tokens together into a single line before passing the whole lot to the parser:

```bash
❯ cpp
#pragma multiple \
        lines \
        pragma
^D
# 0 "<stdin>"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "<stdin>"
#pragma multiple lines pragma

❯ clang-cpp
#pragma multiple \
        lines \
        pragma
^D
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 375 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
#pragma multiple lines pragma
```

**Comment by emteere** [comment]
I've duplicated the issue
