### ISSUE TITLE
Breakpoints are not displayed in Function Graph

### ISSUE THREAD

**Issue by alexey-kleymenov** [NationalSecurityAgency/ghidra#5532]
**Describe the bug**
In the latest Ghidra for Windows 10.3.1, when setting a breakpoint, it is correctly displayed in the Listing and Decompile view. However, there is nothing in the Function Graph view, the breakpoints are completely invisible there

**To Reproduce**
1. Go to any code line in any of the 3 views mentioned above
2. Set a breakpoint using any mean (K hotkey or right-click->Toggle Breakpoint
3. The Listing view has a gray dot breakpoint marker and a grayed-out line, the Decompiler view has only a gray dot breakpoint marker, but the Function Graph view has nothing

**Expected behavior**
The breakpoint markers should be seen in some form in all disassembly views

**Screenshots**
Attached
<img width="1108" alt="Screenshot 2023-07-06 at 14 07 24" src="https://github.com/NationalSecurityAgency/ghidra/assets/28760339/89dd2009-599b-4fda-9d07-1ce20a78096d">
<img width="1072" alt="Screenshot 2023-07-06 at 14 07 04" src="https://github.com/NationalSecurityAgency/ghidra/assets/28760339/e5f7908c-f65d-4743-8cae-017ad0aaa90f">

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: JDK 17
 - Ghidra Version: 10.3.1
 - Ghidra Origin: official GitHub distro

**Comment by d-millar** [comment]
@alexey-kleymenov  We don’t currently support any flavor of bookmark/marker the FunctionGraph right now AFAIK.  Will raise this at the next triage session as a possible new feature.

**Comment by alexey-kleymenov** [comment]
Thank you, that would be extremely useful! As far as I know, many engineers are using the Function Graph as the main interface during the analysis.

**Comment by nsadeveloper789** [comment]
Would a line highlight suffice, or are you hoping to also see icons/markers in the "margin"? We actually already have this defect documented internally, but your input here may help us flesh out the requirements.

**Comment by alexey-kleymenov** [comment]
Line highlight should be enough, in my opinion, at least as the first increment. The most important part is to start displaying breakpoints somehow so that people can start debugging using Function Graph, without breakpoints being displayed at all it is very challenging. I know some folks are used to clicking on the markers to set/remove breakpoints, but at least they can use hotkeys for that in the meantime. I guess icons can be added later if someone asks for them.
