### ISSUE TITLE
Wrong path conversion

### ISSUE THREAD

**Issue by JasonBourne0x90** [NationalSecurityAgency/ghidra#5538]
**Describe the bug**
You cannot start debugging executable which path contains a directory starts with character 0.
https://github.com/NationalSecurityAgency/ghidra/blob/d932173a25bdcb36171f5c0fbaf454ba24f0435d/Ghidra/Debug/Debugger-agent-dbgeng/src/main/java/agent/dbgeng/manager/cmd/DbgLaunchProcessCommand.java#L106

Here if you have path string where a directory name starts with character 0. It will be replaced by null character.
I didn't created a pull request because I don't know the motivation behind that line, so don't think just removing is a good idea).

**Comment by d-millar** [comment]
@JasonBourne0x90  Just curious, is this based on having actually created a directory starting with 0 or just reviewing the code.  I ask because am traveling right now with no real way to test, but, at a cursory glance, looks like the code is dealing with nulls, not zeroes.

**Comment by JasonBourne0x90** [comment]
I actually have my username starts with zero. And it said in command line window start C:\Users access denied. That's why I debugged....

**Comment by oldshensheep** [comment]
The code `output = output.replace("\\0", "\0")` replaces the string `\0` with the `NUL character`, which marks the end of a string. 

For example, the string `C:\Users\0xxxxxxxxxx` would become `C:\Users(NUL)xxxxxxxx`, and since the NUL character signifies the end of the string, the process will access `C:\Users` instead. That's why `interpreter window C:\Users access denied` , as the process lacks the necessary privileges to write to `C:\Users`.

**Comment by JasonBourne0x90** [comment]
just don't know what was the motivation behind this line. @d-millar wanted to do something but still don't understand what?

> The code `output = output.replace("\\0", "\0")` replaces the string `\0` with the `NUL character`, which marks the end of a string.
> 
> For example, the string `C:\Users\0xxxxxxxxxx` would become `C:\Users(NUL)xxxxxxxx`, and since the NUL character signifies the end of the string, the process will access `C:\Users` instead. That's why `interpreter window C:\Users access denied` , as the process lacks the necessary privileges to write to `C:\Users`.

**Comment by d-millar** [comment]
@oldshensheep Thanks for the clarification!  Not my code probably, but guessing the author was trying to account for Java string handling conventions.  Will check with him and amend if he agrees.

**Comment by d-millar** [comment]
Actually, might be my code - lol.  Am traveling right now but will fix it when I return.

**Comment by d-millar** [comment]
@JasonBourne0x90 @oldshensheep Thanks again for pointing this out - have put the fix in.  Just FYI, the reason for the line was to enable the user to enter multi-line environment options using /0 or \0 in the process launch dialog.  Not a great solution, although I don't have a better one, but certainly that logic should not have been applied to the command line and the working directory entry.
