### ISSUE TITLE
checkGradleVersion causes issues with included subprojects

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#5540]
**Describe the bug**

I wrote and maintain a plugin for Ghidra that consists of two subprojects in a subfolder each: The actual Ghidra plugin, and a Python component. For ease of use, the root folder has a `settings.gradle` that just contains `include ":GhidraJupyterKotlin"` (where `GhidraJupyterKotlin` is the subfolder with the actual Ghidra extension). This allows running all the usual gradle commands like `gradle buildExtension` right from the root folder, and saves changing the directory back and forth in my CI setup

With Ghidra 10.3 this now fails with:

```
* Where:
Script '/home/fmagin/ghidras/ghidra_10.3.1_PUBLIC/support/buildExtension.gradle' line: 341

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'GRADLE_MIN' for root project 'ghidra-jupyter-kotlin' of type org.gradle.api.Project.
```

This happens because in 

**To Reproduce**
1. Check out the plugin source https://github.com/GhidraJupyter/ghidra-jupyter-kotlin/tree/a1cb8eae8f0986c36ccce4e2c14e5e2e66d61a43
2. Run `gradle buildExtension /path/to/ghidra_10.3.1_PUBLIC`
3. Observe the build failure I described

**Expected behavior**

I would be happy if this worked as before, and I assume this was unintentionally broken. If there is some reason for the behavior, I'm fine with changing my project, but it seems like the application of the property and the check is just inconsistent in a way that still works for typical project, but not my project layout.

**Additional context**

This issue happens because the attribute `GRADLE_MIN` is set on the _extension_ i.e. in my case the project corresponding to the subfolder that actually contains the extension `project ':GhidraJupyterKotlin'`
https://github.com/NationalSecurityAgency/ghidra/blob/d932173a25bdcb36171f5c0fbaf454ba24f0435d/Ghidra/RuntimeScripts/Common/support/buildExtension.gradle#L36

But the check happens on the _root_ project, which in my case is the top folder of the repo, in my case `root project 'ghidra-jupyter-kotlin'`

https://github.com/NationalSecurityAgency/ghidra/blob/d932173a25bdcb36171f5c0fbaf454ba24f0435d/Ghidra/RuntimeScripts/Common/support/buildExtension.gradle#L508

I can work around this by deleting the `settings.gradle` again, and running Gradle from the subfoder, so now this isn't a big deal anymore, but it has took me a while to understand why this was failing in the first place.

I can also work around this by adding a `gradle.properties` to the root folder that contains the lines:
```gradle
GRADLE_MIN=1.0
GRADLE_MAX=100.0
```
because then the root project will have the requested attributes.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Java Version: [e.g. 11.0]
 - Ghidra Version: 10.3 and 10.3.1
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
I think this is just a copy/paste error from Ghidra's top-level `build.gradle` file.  Can you confirm that if you delete the `rootProject.` substrings from the `checkGradleVersion()` function, it works?  These variable are declared at the top of `buildExtension.gradle` so `rootProject` should not be needed.
