### ISSUE TITLE
Sleigh: logic for parallel-encoded opcode is ignored

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#5548]
In my architecture I have a parallel instructions encoding. It means that you can do some logic along with some moving in parallel. Here is an example:
```
parallel_move: reg1,reg2 is reg1; reg2 { reg2 = reg1; }

:lsl reg3 parallel_move is reg3; parallel_move {
 reg3 = reg3 << 1;
}
```

In result such an instruction should do both left shift and register assigning. But when I'm trying to implement this logic in sleigh, it just ignores left shift and only does a register assigning in the decompiler listing.

**Comment by lab313ru** [comment]
Adding `build parallel_move;` AFTER shifting has solved the problem.

**Comment by ryanmkurtz** [comment]
I am not a Sleigh guy.  Is there still a problem or can we close this?

**Comment by GhidorahRex** [comment]
It seems strange that the ordering would matter. That's not a sleigh issue. What if you explicitly put the `build parallel_move;` before the reg3 assignment?

Also, what are the assigned registers for reg1, reg2, and reg3?

**Comment by lab313ru** [comment]
Putting build parallel_move before the shift don't help.
Registers are just an example. The same happens for STORE and LOAD operations.

**Comment by GhidorahRex** [comment]
The reason I was asking was in case the decompiler was simplifying things out for the registers being the same.

**Comment by lab313ru** [comment]
i have enabled register space in globals to see every single assigning.

**Comment by GhidorahRex** [comment]
Could you provide the pcode for the disassembly and the decompiler output?

**Comment by lab313ru** [comment]
I will, but during this weekend.

**Comment by lab313ru** [comment]
Okay, my fault. It seems that specifying the `build parallel_move;` is mandatory in this case.
