### ISSUE TITLE
Macho loader omitting indirect symbols since 10.3

### ISSUE THREAD

**Issue by awarei** [NationalSecurityAgency/ghidra#5558]
**Describe the bug**
Between Ghidra release 10.2.3 and 10.3 there was a change to how the `MachoProgramBuilder` loaded some symbols. Commit a0473e8 modified symbol parsing by removing the function `processIndirectSymbols`. Due to this some symbols are now omitted during loading of certain machos. Where I noticed this is in machos with the following segments and sections (__TEXT_EXEC,__auth_stubs), (__DATA_CONST,__auth_got), and (__DATA_CONST,__got). From the commit message it appears that these symbols were thought to be duplicates and that does appear to be the case as a symbol still exists in the EXTERNAL memory block. However, there are xrefs to the symbols which were omitted and so not applying the symbol name in these other areas results in a loss of context.

**To Reproduce**
Example machos can be found in the arm64e architecture type on macOS systems (e.g. /bin/ls with the indirect symbols listed by `otool -Iv`). Loading the macho in Ghidra 10.2.3 and also in 10.3 (or later) will show that the indirect symbols don't appear anymore starting in 10.3.

**Expected behavior**
The indirect symbol names are applied.

**Environment (please complete the following information):**
 - OS: macOS 13.4
 - Java Version: 17.0
 - Ghidra Version: First seen in 10.3 and still seen in the latest 10.3.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
These were intentionally removed because if analysis is working correctly, things like the GOT should inherit labels that ultimately trace back to the thunks in the EXTERNAL block.  Is this not happening after analysis?  

For these indirect symbols we were using the section name as the namespace which caused problems with the demangler, since that only operates on global symbols.

**Comment by ryanmkurtz** [comment]
When I import /bin/ls from my macOS 13.4.1, i am getting `Unknown dyld info bind opcode d0` which seems to be messing things up.  Are you seeing that too?

**Comment by awarei** [comment]
I am not seeing any labels added at the indirect symbol locations after the standard default auto analysis for the /bin/ls example case. I am not getting the error you encountered on load. I used batch import and then opened the AARCH64 version.

**Comment by ryanmkurtz** [comment]
Ok, I will investigate further.

**Comment by awarei** [comment]
Yes, checking with Ghidra 10.3.2 and using `/bin/ls` from a macOS 13.5 system I see the same thing at this address after analysis. The operands field of "LAB_c009000000000007" is in red.

**Comment by ryanmkurtz** [comment]
Ok, thanks for checking.  This should be fixed in `master` now.
