### ISSUE TITLE
findBytes() option to not use regex

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#556]
**Describe the bug**
While trying to use findBytes java.lang.IllegalArgumentException is thrown due to the presence of b'\x28' or b'x\29' in the byteString parameter.

**To Reproduce**
1. Go to python interpreter
2. type "findBytes(currentProgram.getMinAddress(), b'\x28\x3F\x23\x00'))" 

**Expected behavior**
( and ) to be properly handled when input as a byte string.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.437]
 - Java Version: 12.1
 - Ghidra Version: 9.0.2

**Additional context**
This commonly occurs when attempting to search for pointers that have not yet been created. Attempting to delimit them from within jython causes the b'\x28' and b'\x29' values to be removed from the search when passed to findBytes.

**Comment by ryanmkurtz** [comment]
The findBytes() method is expecting a regular expression, so you would have to escape all special regular expression characters.  Did `findBytes(currentProgram.getMinAddress(), b'\\\x28\\\x3F\x23\x00')` not work for you?  It seems to work for me.

**Comment by astrelsky** [comment]
I had replaced them with a single escape instead \( instead of \\( and it resulted in results that had the ( or ) completely omitted.

The issue comes more from when using getBytes to retrieve bytes from an address and then using findBytes to find other instances of it. I did not expect it to treat it as a regular expression. Does adding the option to turn on/off regex sound like a reasonable solution?

**Comment by ryanmkurtz** [comment]
Yes, it sounds reasonable to me.  I'll switch this over to an enhancement request.

**Comment by dragonmacher** [comment]
There exists a method to find bytes that does not use string values:

    `public final Address find(Address start, byte[] values);`

Have you tried using this method?

**Comment by astrelsky** [comment]
> There exists a method to find bytes that does not use string values:
> 
> ```
> `public final Address find(Address start, byte[] values);`
> ```
> 
> Have you tried using this method?

The byte string would need to be converted to a Java byte[] first but it would probably work. When I initially raised the issue I didn't realize that Jython didn't require a wrapper like C-python does. I had though that there was a mistake when converting python regex to Java regex or something but that is clearly not the case.

I'm actually going to close this as I no longer see it as useful and didn't realize it was still open.

**Comment by TheMatt2** [comment]
There is a way to search for bytes in a file without using regular expressions, other than documented above.

There is a plain `findBytes()` function on the [`ghidra.program.model.mem.Memory()`] (https://ghidra.re/ghidra_docs/api/ghidra/program/model/mem/Memory.html#findBytes(ghidra.program.model.address.Address,ghidra.program.model.address.Address,byte%5B%5D,byte%5B%5D,boolean,ghidra.util.task.TaskMonitor)) class.

Here's how it could be used:

    Memory memory = currentProgram.getMemory();
    memory.findBytes(currentProgram.getMinAddress(), b'\x28\x3F\x23\x00', null, true, monitor);
