### ISSUE TITLE
Configurable GUI changes spoil functionality and are not persisted

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#5566]
**Describe the bug**
There are 3 issues related to the `Structure Editor` dialog and 1 general:
1. After removing the `Mnemonic` (or any of the non-editable) fields form the view (or moving them after editable ones), pressing `F2` to edit one of the editable fields now picks the previous field to edit (see screenshot 1) (could be related to the fix for #3561);
2. After opening a second dialog (by dragging one of the open tab's titlebar), subsequent requests to edit/view a sub-component always opens in the most recently opened `Structure Editor` **instead** of the one associated with the structure you're currently reviewing (this is used for checking if structures you've created elsewhere are equivalent and can therefore be merged);
3. With lots of open tab's, keyboard switching (using Sticky Keys) between the adjacent `Structure Editor` and the `CodeBrowser` window ceases to occur with the normal key sequence and you have to "lock" the `Alt` key then press `Tab` then "unlock" the `Alt` key (4 key presses instead of 2) to get it to switch windows;
4. Resizing of the columns isn't currently persistant (this occours across several dialogs).

**To Reproduce**
See description above.

**Expected behavior**
See description above.

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/67698927/1dc24d33-2ac1-4a2f-90c5-d07d24348e71)
Screenshot 1: Pressing `F2` on the selected `Comment` opens the editor for the `Name`

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.3.1
 - Ghidra Version: 10.1.4
 - Ghidra Origin: locally built

**Additional context**

**Comment by dragonmacher** [comment]
Regarding the various issues in this ticket:

1.   We fixed overall odd navigation while editing, including how it works when rearranging the default columns.
2.   We updated the placement algorithm to prefer the window that contains the focus owner, which should address this use case.
3.   We were unable to reproduce this.  There is upcoming work  related to this in the area of accessibility.
4.   This appears to be working as intended for me.   The changes to the column widths apply:
- when opening any subsequent structure editor
- when closing and reopening Ghidra, then opening a structure editor

The potentially confusing issue is that if you have multiple editors open, it will use the size information from the last editor that had columns resized (not necessarily the last editor you were working in before showing a new editor).

**Comment by Wall-AF** [comment]
Thanks, @dragonmacher. 1) and 2) look good so far.
3) Was probably never going to be easily reproduced.  (It's a wierd one!)
4) I've just dropped the `Mnemonic` column and resized the `Offset`&`Length` columns, closed Ghidra, saved the correct `Code Browser` (I use several) and restarted it (all from within Eclipse).  Upon the restart I opened the `Structure Editor` and the columns all returned to their default positions and sizes!

**Comment by dragonmacher** [comment]
For number 4, I just verified this works for me.  I made the suggested column changes and then exited Ghida via the Front End while leaving all windows open.   Does each of your Code Browser have a different name?

**Comment by Wall-AF** [comment]
Oops, my mistake, must've saved the wrong `Code Browser`!  However upon reopening, the window always returns to the centre of the screen never remembering its previous location!  Is that possible?

**Comment by dragonmacher** [comment]
This also appears to be working for me.   If I try this when opening a Code Browser and only edit 1 structure, then all is as expected when I restart and edit again--the window is in the last place I left it.  

I suspect that this may fail if there were many previously opened structure editors.  The code may find many choices of where to open the structure, just picking one of the group.

**Comment by Wall-AF** [comment]
Mmm, seems to be working this time!!!  Odd!
