### ISSUE TITLE
x64: failure to disassemble LIDT instructions

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5577]
**Describe the bug**
The following are several (de-duped) byte patterns that Ghidra fails to disassemble on an x64 program, with corresponding disassembly from Capstone/IDA

```
0f 01 9d 98 01 00 00
lidt [rbp + 0x198]

0f 01 9f f6 00 00 00
lidt [rdi + 0xf6]

0f 01 59 66
lidt [rcx + 0x66]

0f 01 5d f7
lidt [rbp - 9]
```
![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/bb64a68c-7f59-47d3-b216-70015e4b663b)

![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/aa2f2999-2b05-453b-93ac-754bd1534dab)

![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/2d52f550-4891-46af-9744-9279657c355d)

**Comment by GhidorahRex** [comment]
This is an issue with the constructors for the `LIDT` instruction. The 64-bit versions are specifying an opsize of 64, but the default opszize is 32 for 64-bit. The opsize parameter should be removed.

The `SIDT` instruction is also wrong here - it's using the 32-bit version, not the 64-bit version. It doesn't have the `$(LONGMODE_OFF)` restriction (but it should), and the `opsize=2` should be removed from the 64-bit version.
