### ISSUE TITLE
Colored assembly code in clipboard 

### ISSUE THREAD

**Issue by dingiso** [NationalSecurityAgency/ghidra#5589]
**Is your feature request related to a problem? Please describe.**
Can Ghidra copy a snippet of assembly code with highlighting, colors, and formatting like other text editors? I have tried formatting it, but there are no colors showing.

**Describe the solution you'd like**
The code after paste is look as good as it in the ghidra's Listing window.

**Comment by dragonmacher** [comment]
A workaround for now is to simply use a screen grab to capture small snippets.   

We are trying to better understand how you will use this feature.   How do you intend to use the colored copied text?

**Comment by dingiso** [comment]
Hi dragonmacher,

Thanks for your reply. I am trying to use this code snippet in my paper's figure. If it can be copied using HTML, it will be great.

There are many code beautification tools on the network, but they do not support the code style of Ghidra. Furthermore, none of them support the ARM assembly code.  If Ghidra can be copied into HTML in the clipboard, it will be great. Thanks. 

Thanks,
Dingisoul

**Comment by ghidra007** [comment]
Will not fix
