### ISSUE TITLE
Function Editor Window: Function signature with pointer-to-array argument is not parsed correctly

### ISSUE THREAD

**Issue by LukeSerne** [NationalSecurityAgency/ghidra#5594]
**Describe the bug**
Function arguments that are pointer to arrays need to be entered as `type[X] *param_1` (for an array of `X` elements of type `type`). This is not valid C syntax, which should be `type (*param_1) [X]` (for the same type). The valid syntax (`type (*param_1) [X]`) instead causes an error popup. I don't mind that `type[X] *` is accepted, since it might be a more obvious way to represent the pointer-to-array type, but I do think it's a problem that the correct C syntax is not parsed.

**To Reproduce**
1. Right-click a function name in the decompiler window
2. Click on 'Edit Function Signature'
3. In the main textbox at the top, try entering `uint (*param_1) [2]` as parameter.
4. See error popup

**Expected behavior**
I expected no error popup and the type of the corresponding parameter to be set to `uint[2] *`.

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/32435769/ace6e1e5-d4ee-461a-90ed-c61bc8018f4f)

**Environment (please complete the following information):**
 - OS: Linux
 - Ghidra Version: 10.3
 - Ghidra Origin: locally built

**Comment by ghidra1** [comment]
The Function Editor parser does not utilize the C-Parser and has many known limitations due to the variability of datatype names and representations which may be encountered within Ghidra.  There are very few rules which govern the naming of datatypes within Ghidra and pointer/array details are always expected before the parameter name and after the base-datatype name with the parameter name being optional: `<base-datatype> <pointer/array suffixes...> [<param-name>]`.

**Comment by LukeSerne** [comment]
@ghidra1:
> It may be possible to incorporate the C-Parser as a alternate parser. It cannot be used as the sole parser since it will fail to parse Ghidra datatype names in many cases but may be able to better handle user input in some cases.

Yeah, or maybe the C-Parser can be used as a fallback and only be used when the normal parser fails. Honestly, I think the format that the current parser supports is very nice, simple to understand and consistent with other types. The main reason I noticed this is because the decompiler uses the C convention of displaying pointer-to-array types as `base (*name) [X]`, and I figured this was weirdly inconsistent.

**Comment by ghidra1** [comment]
After further investigation and discussion it was decided that the parser within the Function Editor is specifically intended to cope with Ghidra datatype "naming/syntax" which is not consistent with C-syntax.  The Function Editor signature entry is also intended to cope with minor edits (e.g., parameter names) when C++ templates are present which the C-Parser is unable to cope with.  Therefor no change is planned at this time.  

Other datatype entry parsing throughout Ghidra utilize this same pointer/array naming syntax (e.g., parameter table entries, structure editor component entries, etc.).   This parse is also consistent with how these are rendered throughout Ghidra.
