### ISSUE TITLE
Data entries of variable length are not resized when data changes

### ISSUE THREAD

**Issue by LukeSerne** [NationalSecurityAgency/ghidra#5595]
**Describe the bug**
When changing the bytes of a variable of a type that does not have a fixed length (such as `TerminatedCString`), the size of the variable is not updated in the listing window.

**To Reproduce**
Steps to reproduce the behaviour from scratch - this bug also happens in existing memory regions and with other data types that do not have a fixed length.
1. Create a new memory region, initialized with 16 `NUL` bytes (`0x00`).
1. Go to the start of the new memory region
1. Set the type (`T`) to `TerminatedCString`
1. Use the bytes viewer to edit the first 10 bytes to `0x41` (`'A'`)
1. Notice how the literal shown in the listing view grows, but it continues to occupy the same number of bytes (1). The literal also has a red text colour, indicating that it's too big for the number of bytes it occupies. (See screenshot 1)
1. Go back to the listing view and recreate the type (`C` `Y`).
1. Go to the bytes viewer and edit the first byte to `NUL` (`0x00`).
1. Notice how the literal has become the empty string, is not coloured red, but still occupies 11 bytes. Additionally, the remaining 10 bytes that used to be part of the string are "missing" - the next address in the listing panel is `+0xb` instead of `+0x1`, and the bytes are "folded" away as if they are still part of the string. (See screenshot 2)

**Expected behaviour**
I expected the string to grow until the next available `NUL` byte, after the original `NUL` byte was changed. I expected the string to shrink until the first `NUL` byte after the first byte was changed to `NUL`.

**Screenshots**
![Screenshot 1](https://github.com/NationalSecurityAgency/ghidra/assets/32435769/d56e2e0d-5b3d-4d06-9a51-a8a58701f249)
![Screenshot 2](https://github.com/NationalSecurityAgency/ghidra/assets/32435769/0fa0acc6-5210-44f3-b907-f83dc2c7c5e7)

**Environment (please complete the following information):**
 - OS: Linux
 - Ghidra Version: 10.3
 - Ghidra Origin: locally built

**Additional context**
I'd argue both screenshots show (related) bugs. Growing the data until the next availably `NUL` might be difficult if it would cause the type to overlap with defined data at higher addresses. However, when there is no defined data there, growing the type should not be a problem. If there is a conflict, showing a popup about the data type conflict after the user has finished editing the bytes seems like a good solution.

**Comment by ghidra1** [comment]
This is a know limitation and we have no current plans to resolve.  This is just one of a few other data updated related issues that are known limitations.  Other known limitations include: 1) data reference updates when pointer bytes are modified or when pointers move within structure definition, 2) data instance settings applied to a memory location when associated data component is modified within associated structure.

**Comment by LukeSerne** [comment]
Thanks for the clarification. I think it's a bit unfortunate that there are no plans to resolve this, but luckily, it's not a big issue that comes up a lot (for me at least).
