### ISSUE TITLE
[Typo] Typo in Instruction Search Plugin

### ISSUE THREAD

**Issue by ReversingWithMe** [NationalSecurityAgency/ghidra#5596]
**Describe the bug**
Comment in the Plugin search file, working on a better way to report in batch instead of one-offs, would PR be preferred also for things like this?

ghidra/Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/instructionsearch/ui/InstructionSearchDialog.java 78
`pluain` should be `plugin`

**Comment by ryanmkurtz** [comment]
> would PR be preferred also for things like this

Yea, PR's for typos are probably preferred.
