### ISSUE TITLE
Apple Silicon having issues loading files into codebrowser

### ISSUE THREAD

**Issue by jumpeip** [NationalSecurityAgency/ghidra#5597]
**Describe the bug**
I have both an Intel based MacBook Pro and an Apple Silicon based M1 MAX MacBook Pro.  I have a Ghidra server running on a remnux virtual machine in my network.  The home network for using Ghidra has one windows 11 based which is running VMware pro that is running the remnux box hosting the Ghidra server and the 2 MacBook pros.  When Ghidra is launched on either MacBook, it connects very quickly to the server and authenticates.  When I select a file to work with to open in the codebrowser, the Intel based MacBook opens right away and I can browse the file.  However, when I click to open a file on the M1 Max based MacBook, it appears to launch the code browser, but the windows never opens and it appears to disconnect from the repository.  I cannot open any files when connecting to the repository.  Both MacBooks are running the (technically) same version of the IOS (13.4.1) and same version of Java (19.0.1).  One other issue is on the M1 Max based MacBook is that once you click to open the codebrowser, it does not open, BUT Ghidra is no longer responsive and you need to force quit the application.  

This only seems to be an issue when connecting to a shared repository.  If I run Ghidra locally on the M1 Max MacBook, it works fine.

**To Reproduce**
1. launch Ghidra
2. authenticate to remote repository
3. select file and click to open in codebrowser
4. Ghidra hangs after launching the codebrowser (no codebrowser window appears

**Expected behavior**
I would expect the M1 based MacBook to perform the same as the Intel based version by opening quickly to browse the file.

**Environment (please complete the following information):**
 - OS: macOS 13.4.1
 - Chipset: M1 Max chipset (Apple silicon)
 - Java Version: 19.0.1
 - Ghidra Version: 10.3.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
When the hang is happening, can you try to grab a java stack trace?  The commands to do so are:
* `jps` (note the pid of your ghidra process)
* `jstack <pid>`

**Comment by jumpeip** [comment]
Attached are the results of the two commands.  The one does show no route to host but the funny thing is, I authenticated fine and received a list of my files in the Repo.
[Ghidra java command results.pdf](https://github.com/NationalSecurityAgency/ghidra/files/12147289/Ghidra.java.command.results.pdf)

**Comment by ryanmkurtz** [comment]
Would you mind reattaching as a text file?

**Comment by dev747368** [comment]
I suspect that your issue is due to your network configuration, specifically any NATing or firewall going on between your client workstations and the Ghidra server running in the VM.

You could rule this out by running a Ghidra server instance locally on your problematic client and then connect to it using the localhost addr.  (using a throw-away project just to test the ability to perform the normal actions)

For a quick and easy way to startup a server instance, in ghidra_install_dir/server, run ```./ghidraSvr console```.  You will have to add a user account also (in the normal way).

What options did you configure in your server.conf, and what are the ipaddrs/subnets for the server and each client?  If you have a firewall configured, which ports did you open?

**Comment by jumpeip** [comment]
I am not so sure it's the networking.  Because I do authenticate to the server.  I verified this by entering a bad password.  Once logged in, I am presented with the entire repository.  I am running a standard ghidra server config file, nothing changed on it.  I will go and run the server on the M1 MacBook and see if I have any issues and report it back.

**Comment by jumpeip** [comment]
OK, here's what I did.  

on MacBook M1 chipset:
1) Installed and started a ghidra server
2) Added users and created a shared test repo
3) Opened the test repo and added files (around 50)
4) Added the files to version control
5) Checked out a file and opened in CodeBrowser (opened right away)

on Windows based laptop, Intel based Laptop, and Windows Intel based laptop running remnux VM
1) Launched Ghidra
2) Created share repo and connected to IP address of M1 Mac which listed the test repo
3) Opened the test repo and saw all files in the listing
4) Opened a file, checked it out and immediately opened in Code Browser

That should have verified network connectivity.  All of the systems and the VM connected successfully and opened files immediately

Now in reverse I already had a server running in a remux VM that everything can connect to

On Windows laptop and Intel based MacBook 
1) Launched Ghidra
2) Opened my malware repository
3) Opened a file which immediately opened the codebrowser window to analyze file

On M1 based Mac
1) Launched Ghidra
2) Opened my malware repository which is located on the Windows machine running VMWare running remnux
3) All files are presented from the repo
3) Double clicked a file to open ....... ghidra becomes unresponsive and I have to force quit


I can only think it might be something java based at this point. Not ruling out anything else but the fact the only laptop that has an issue if the Apple Silicon based MacBook.  I am at a loss right now. Yes, I don't have to use the M1 MacBook, but for work, I am testing all architectures for compatibility and this seemed to be an issue.
