### ISSUE TITLE
GhidraScript: AnalysisMode.DISABLED causes a transaction regardless of whether changes are made

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5599]
**Describe the bug**
Running the script below causes a transaction to be created (![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/4294b23d-f4aa-46fc-b76e-ec634b056768) lights up, undo available) even though no change has been done to the program.
```
import ghidra.app.script.GhidraScript;

public class ExampleScriptFail extends GhidraScript {
	@Override
	public AnalysisMode getScriptAnalysisMode() {
		return AnalysisMode.DISABLED;
	}
	@Override
	protected void run() throws Exception {
	}
}

```

**Environment (please complete the following information):**
Ghidra 8028c54

**Comment by ghidra1** [comment]
Disabling analysis still allows script to make changes within the transaction.  Its purpose is to get the AutAnalysisManager to ignore events such that follow-on analysis is not automatically triggered.  However, subsequent analysis could occur as a result of future interactions within the tool.

What does the undo tool tip indicate for the transaction "name"?  BTW, the popup which asks about auto-analysis will make a change to the program which records your response to the question.

**Comment by sad-dev** [comment]
It simply says "Auto Analysis"

![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/e35cdbd3-21a9-40ae-a5a1-5e908f7185df)

**Comment by ghidra1** [comment]
I am forced to speculate without seeing this first-hand.  One common cause of an unexpected Analysis transaction is the recording of the "Analyzed" state within the Program Information.  This is done to record if the user has made a decision to analyze or not-analyze and avoid asking the user when re-opening program at a later time.

**Comment by sad-dev** [comment]
It can be reproduced as follows on a locally built ( commit 26d4bd9 )

1. Create ExampleScriptFail.java in the ghidra_scripts folder with the following contents:
```


import ghidra.app.script.GhidraScript;

public class ExampleScriptFail extends GhidraScript {
	@Override
	public AnalysisMode getScriptAnalysisMode() {
		return AnalysisMode.DISABLED;
	}
	@Override
	protected void run() throws Exception {
	}
}

```
2. Create a fresh project and import a fresh file. Say no (don't ask again) and save.
3. Run ExampleScriptFail.java
4. Observe that the save icon has now lit up and the tool tip for "Undo Auto Analysis" appears

**Comment by ghidra1** [comment]
When the script runs in this mode (i.e., auto-analysis suspended or disabled) the script runs as an analysis task allowing it to block other analysis.  However, when it completes its execution the stored analysis times are updated with the time spent running the script.  You should see this if you examine the Program `Properties -> Program Information -> Analysis Times`.  These can be found under the menu `Edit->Options for ...`

**Comment by sad-dev** [comment]
The script I have provides the user an option to cancel without running (in case of hitting the wrong keybind) and performs various analysis e.g. temporary transactions, disassembly, etc. that will be rolled back (hence the AnalysisMode.DISABLED). Will I need to use something like ``runScript`` to handle this, e.g.


```
public class HeavyMetalWrapper extends GhidraScript {
	@Override
	protected void run() throws Exception {
            if (askYesNo(...)) {
                runScript("HeavyMetalMain.java")
            }
	}
}

public class HeavyMetalWrapper extends GhidraScript {
	@Override
	public AnalysisMode getScriptAnalysisMode() {
		return AnalysisMode.DISABLED;
	}
	...
}
```

**Comment by ghidra1** [comment]
The script itself is still consuming cycles - even if 1ms.  Knowing when not to accumulate time becomes problematic and would require an additional option or method callback on script.

**Comment by sad-dev** [comment]
> The script itself is still consuming cycles - even if 1ms. Knowing when not to accumulate time becomes problematic and would require an additional option or method callback on script. We are not currently checking time value for 0 since we assume if it ran is consumed some amount of time.

I see, it does seem difficult to change. I tried the runScript wrapper method outlined above and no luck either. Any suggestions how I can tweak my scripts?

**Comment by ghidra1** [comment]
I have made a change (GP-3717) which will avoid updating analysis times if there are no unsaved changes to the program.  Note that if a pre-existing change was made to the program and not saved the analysis time will still get updated.
