### ISSUE TITLE
Does ghidra support using external DWARF information?

### ISSUE THREAD

**Issue by ilch1** [NationalSecurityAgency/ghidra#56]
Can ghidra use dwarf information that is available in an external file? On macOS, the debug information is typically included in a `.dSYM` package external to the executable.

When trying to do `Analysis->Oneshot->DWARF`, I get the following:

```
Error during DWARFAnalyzer import
java.io.IOException: Abbreviation code 10901 not found in the abbreviation map for compunit Compilation Unit [Start:0x17bb2f] [Length:0x7] [AbbreviationOffset:0x0] [CompileUnit: not present]
```

**Comment by ryanmkurtz** [comment]
Sorry for the extremely long response time.  To answer your question, Ghidra currently cannot use DWARF information from an external file.

**Comment by psifertex** [comment]
It looks like https://github.com/NationalSecurityAgency/ghidra/commit/f023b8ad3f125f2285646df812737d6e1fa77e48 implemented at least some of this functionality.

See also: https://github.com/NationalSecurityAgency/ghidra/issues/3513
