### ISSUE TITLE
"Diamond" Tip of the Day seems to be inaccurate without qualification

### ISSUE THREAD

**Issue by saagarjha** [NationalSecurityAgency/ghidra#560]
**Describe the bug**
Ghidra [has a "Tip of the Day"](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/resources/ghidra/app/plugin/core/totd/tips.txt#L23) where it claims that the largest diamond ever found was 3106.75 carats. [According to Wikipedia](https://en.wikipedia.org/wiki/List_of_diamonds) (which of course is unquestionable truth) this would correspond to the [Cullinan Diamond](https://en.wikipedia.org/wiki/Cullinan_Diamond), which is the largest *gem-quality* diamond. However, the largest diamond is apparently a non-gem quality carbonado named [Sergio](https://en.wikipedia.org/wiki/Sergio_(carbonado)) that weighed 3167 carats. I think the tip should be changed to either refer to Sergio or qualify the statement so that it remains accurate.

**To Reproduce**
1. Open Ghidra until you see this Tip of the Day.

**Expected behavior**
The "Tip of the Day"s are factually correct.

**Screenshots**
<img width="508" alt="Screen Shot 2019-05-02 at 20 34 48" src="https://user-images.githubusercontent.com/13786931/57163399-eb867600-6da5-11e9-875e-238bf3f2c0b3.png">

**Environment (please complete the following information):**
 - OS: macOS Mojave 10.14.5 (18F127a)
 - Java Version: 12.0.1
 - Ghidra Version: 9.0.2

**Comment by ryanmkurtz** [comment]
Thanks for report this, let's get to the bottom of this bug.  First off, are you running Ghidra on a HiDPI monitor?  Ghidra has been known to have display issues on HiDPI monitors.

**Comment by saagarjha** [comment]
Yes, I've heard about this issue! I'm running Ghidra on my 2560×1600 built-in display, scaled at 2×. Would that be what's causing this problem?

**Comment by leijurv** [comment]
Perhaps the 2x scale is affecting the carat number?

**Comment by sraboy** [comment]
Weird. On Windows 10 1903, the tip clearly states that the largest diamond was 3167 carats. You should file a bug with the good folks at Apple.

**Comment by dev747368** [comment]
💎
