### ISSUE TITLE
Listing -> Choose Data Type : Not enough space to create Data

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5602]
**Describe the bug**
When trying to ``Choose Data Type`` action from a selection containing multiple non-aligned addresses on types like ``undefined3 and int3``, a message like "Create int3(s) failed: Not Enough space to create Data" is shown and the data is not created. This appears to be a regression as I have been able to create data from such selections before

**To Reproduce**
The following is some python code to be run from the interpreter:
```
import ghidra.program.model.address.AddressSet as AddressSet
k = AddressSet()
# Click somewhere off-aligned
k.add(currentAddress)
# Click somewhere else off-aligned
k.add(currentAddress)
createSelection(currentAddress)
```
Then right click the listing and select Choose Data Type , type ``int3`` or ``undefined3``

![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/6869af81-26a9-425e-ad20-8414554f49fb)

**Comment by ghidra1** [comment]
I am able to reproduce and it certainly appears to have the wrong behavior.

**Comment by ghidra1** [comment]
I think I can safely tone-down the forced alignment for spot placement of datatypes (single address locations).  While range-based selections would continue to enforce alignment.  This is done to ensure that if a run of data created is converted to an array that the datatype components would be properly aligned based upon the compiler specification (i.e., data organization).  

Could you indicate your program architecture being used and your rationale for using `int3` and how this likely relates to how the program's source code defined the data.

**Comment by sad-dev** [comment]
> I think I can safely tone-down the forced alignment for spot placement of datatypes (single address locations). While range-based selections would continue to enforce alignment. This is done to ensure that if a run of data created is converted to an array that the datatype components would be properly aligned based upon the compiler specification (i.e., data organization).
> 
> Could you indicate your program architecture being used and your rationale for using `int3` and how this likely relates to how the program's source code defined the data.

The binary is MIPS big-endian 32-bit (unknown compiler). The int3 is used as a part of a structure as follows:

```
char * stringBase;
void * imageBase;
int n;
SymStruct syms[n];

SymStruct {
  byte flags;
  int3 stringOffset;
  int symOffset;
}
```

where each of the SymStruct defines a symbol at ``imageBase + symOffset`` with name read from ``stringOffset + stringBase``.

**Comment by ghidra1** [comment]
There may still be restrictions within a structure where aligned-length will still be enforced.  I need to tone this down as well for non-packed structures but has not yet been done for forthcoming merge (GP-3675).  There are also some unresolved issues related to big-endian treatment for this situation.

I would assume this is not a valid C structure for the source code.  What would you expect the structure to look like in source code?  Are you doing this to compensate for lack of bitfield support in decompiler?

**Comment by sad-dev** [comment]
I just noticed some weird behaviour:

Create a SymStruct { byte, int3, int } in the listing and create Structure
![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/f5003107-7c19-40a5-b2d5-fd1ba03dc576)

![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/af97cfa2-a1ea-4461-b58c-d510cdacee39)

The int3 is size 4 and the dword has vanished
 
> I would assume this is not a valid C structure for the source code. What would you expect the structure to look like in source code? Are you doing this to compensate for lack of bitfield support in decompiler?

To be honest, I have no idea what the source code would look like, although I vaguely remember that certain structs like ``basic_string`` (https://shaharmike.com/cpp/std-string/) can be pretty weird in the decompiler

**Comment by ghidra1** [comment]
Yes, the current structure behavior is to force alignment.  My intention is to remove this behavior for non-packed structures (GP-3726).
