### ISSUE TITLE
The generated PcodeOp is incorrect

### ISSUE THREAD

**Issue by fjqisba** [NationalSecurityAgency/ghidra#5603]
For example,x86 instruction 
`pop dword ptr ss:[esp+0x24]`
Ghidra generate the following code:
`0x004d4bee:a5:	u0x00002500(0x0000000c:a5) = #0x24 + ESP(0x0000000b:a3)`
`0x004d4bee:a6:	u0x00007a00(0x0000000c:a6) = *(ram,ESP(0x0000000b:a3))`
`0x004d4bee:a7:	*(ram,u0x00002500(0x0000000c:a5)) = u0x00007a00(0x0000000c:a6)`
`0x004d4bee:a8:	ESP(0x0000000c:a8) = ESP(0x0000000b:a3) + #0x4`

The code can be simplified to:
[esp + 0x24] = [esp]
esp = esp + 0x4

However,When I try to execute this instruction in the debugger,the result is:
[esp + 0x28] = [esp]
esp = esp + 0x4

Here is the screenshot,before execute pop ins:
ESP = 0x0019FBF8
[0x0019FBF8] = 0x282
![1](https://github.com/NationalSecurityAgency/ghidra/assets/19220994/3175328c-1b79-4c3f-8ad7-16696681dd06)

After execute pop ins:
ESP = 0x0019FBFC
[0x19FC20] = 0x282
![2](https://github.com/NationalSecurityAgency/ghidra/assets/19220994/f02d171c-48be-4958-8073-57dcc2f436b4)

**Comment by sad-dev** [comment]
Similar to #4282

**Comment by GhidorahRex** [comment]
Duplicates #4282.
