### ISSUE TITLE
"./sleigh -n" Should Have Line Numbers

### ISSUE THREAD

**Issue by VGKintsugi** [NationalSecurityAgency/ghidra#561]
**Describe the bug**
I'm compiling my processor spec with "./sleigh -a <processor_dir>". I have the following warning:

> WARN  4 NOP constructors found (SleighCompile)  
>WARN  Use -n switch to list each individually (SleighCompile) 

Trying again with "./sleigh -n -a <processor_dir>" I get:

> WARN  NOP detected at null (SleighCompile)  
> WARN  NOP detected at null (SleighCompile)  
> WARN  NOP detected at null (SleighCompile)  
> WARN  NOP detected at null (SleighCompile)  
> WARN  4 NOP constructors found (SleighCompile) 

Which doesn't help me. I want to know at what line I have a NOP instruction. 

**To Reproduce**
1. Develop a processor spec with empty SLEIGH definitions for some of the instructions. 
2. Compile with ./sleigh -n -a

**Expected behavior**
I want to see line numbers in the output:
> WARN  NOP detected at line 1234 (SleighCompile)  
> WARN  NOP detected at line 1300 (SleighCompile)  
> WARN  NOP detected at line 1330 (SleighCompile)  
> WARN  NOP detected at line 2738 (SleighCompile)  
> WARN  4 NOP constructors found (SleighCompile)

**Comment by mumbel** [comment]
I looked into this a little, but made no progress really.  

In SleighCompiler.g, `pcode.recordNop(find(where));` find() has a null location.  Any other time in that `c != null`, the find() does return a location, but I never figured out where the OP_PCODE gets the filename/lineno assigned

**Comment by VGKintsugi** [comment]
I'm still having the same issue. You can take a look at my code here: https://github.com/VGKintsugi/Ghidra-SegaSaturn-Processor/tree/b83f74d58251fc2c51c6df012e52caf676a3ff77

**Comment by emteere** [comment]
I took a look, and fixed the issue by modifying the SleighCompiler.g file to pass down the constructor.  There are a few changes needed in other calls to the grammar.

**Comment by mumbel** [comment]
Any chances this makes 9.0.5 or 9.1?  (also maybe #745 )

**Comment by emteere** [comment]
Should be merged into main soon.  Already fixed, just lagging merges.

**Comment by ryanmkurtz** [comment]
Fixed [here](https://github.com/NationalSecurityAgency/ghidra/commit/5ecce280b86061c5b3a6c1f547d3ec270c5483cd).
