### ISSUE TITLE
Navigate to selected function in the "Function tags" window

### ISSUE THREAD

**Issue by vguttmann** [NationalSecurityAgency/ghidra#5613]
**Is your feature request related to a problem? Please describe.**
After having tagged functions and switching between them, it's always a hassle to actually navigate to them.

**Describe the solution you'd like**
The ability to just jump to functions based on the highlighted entry in the "Functions with Tag: [tag]" window, like the reference search does

**Describe alternatives you've considered**
A more easily accessible "Go to" window, but that still requires me to memorize or copy the address - and it works in the search!

**Additional context**
There is nothing more to this

**Comment by dragonmacher** [comment]
That table should be working as you suggest.  I think this is just an oversight.
