### ISSUE TITLE
Error importing any pe

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#5618]
**Describe the bug**
Importing any pe results in an error due to an "InvalidPathException: Illegal char <:> at index 2: /C:/Users/...".

Rough traceback (I'm on my phone)
AbstractLibrarySupportLoader.java:1036
^:478
^:103

**To Reproduce**
1. Import any PE with default options

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 17
 - Ghidra Version: 10.4_DEV

**Additional context**
Temporary workaround is to disable the "Perform Library Ordinal Lookup" option.

**Comment by ryanmkurtz** [comment]
> Rough traceback (I'm on my phone)

We do not support running on your phone at this time.

**Comment by ryanmkurtz** [comment]
Thx, i'll fix it.
