### ISSUE TITLE
RISCV-64 ELF kernel modules don't import cleanly if backreference local symbols are present

### ISSUE THREAD

**Issue by thixotropist** [NationalSecurityAgency/ghidra#5619]
**Describe the bug**

Ghidra doesn't handle RISCV kernel module imports cleanly.  

1. Ghidra incorrectly rejects ELF symbols like `.L1^B12`  because of the embedded 0x02 byte.  This likely breaks PC relative relocation.
2. Ghidra throws Invalid Address exceptions when importing valid ELF files where .GOT or .PLT sections have length 1 but are otherwise empty.  This has no effect on decompilation but significantly confuses relocation debugging.

**To Reproduce**

Import RISCV-64 kernel load modules (attached) with ghidra running in foreground

Look for console errors like:

```text
ERROR Failed to process GOT at 00100381: Insufficent memory at address 00100381 (length: 8 bytes) (ElfDefaultGotPltMarkup) ghidra.program.model.util.CodeUnitInsertionException: Insufficent memory at address 00100381 (length: 8 bytes)
```

Look for import errors like:

```text
There were too many messages to display.
29 messages have been truncated.

----- Loading /tmp/netconsole_ubuntu.ko -----
Skipping section [.note.GNU-stack] with invalid size 0x0
Error creating symbol: .L11 - Symbol name contains invalid characters: .L11
Error creating symbol: .L12 - Symbol name contains invalid characters: .L12
...
```

**Expected behavior**

1. local symbols including `^B` (and possibly `^F` )are accepted and made available for RISCV PC relative relocation handling.  Ideally, any null terminated ASCII or UTF-8 symbol is accepted, displayed, and referenced correctly.
2. ELF GOT and PLT sections with lengths less than 8 bytes are silently ignored.  

**Attachments**

[netconsole.ko.gz](https://github.com/NationalSecurityAgency/ghidra/files/12217002/netconsole.ko.gz)

`netconsole.ko` was extracted from `ubuntu-23.04-preinstalled-server-riscv64+unmatched.img`  A recent Fedora image shows similar behavior, while user-space binaries import cleanly  These images *may* have both been provided by SiFive.

**Environment:**
 - OS: Fedora 38
 - Java Version: 17.0.7
 - Ghidra Version: 10.3.2
 - Ghidra Origin: official GitHub distro

**Additional context**

readelf shows that these labels like `.L1^B1` and single-byte sections actually exist within the ELF file:

```console
$ readelf -Wa netconsole.ko
...
Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
...
 [21] .plt              PROGBITS        0000000000000380 001d40 000001 00  AX  0   0  1
 [22] .got              PROGBITS        0000000000000381 001d41 000001 00  WA  0   0  1
...
Relocation section '.rela__bug_table' at offset 0x97d0 contains 8 entries:
    Offset             Info             Type               Symbol's Value  Symbol's Name + Addend
0000000000000000  0000014200000023 R_RISCV_ADD32          000000000000029e .L1^B1 + 0
0000000000000000  0000014300000027 R_RISCV_SUB32          0000000000000000 .L0  + 0
0000000000000004  0000014400000023 R_RISCV_ADD32          0000000000000050 .LC2 + 0
0000000000000004  0000014500000027 R_RISCV_SUB32          0000000000000004 .L0  + 0
000000000000000c  0000014600000023 R_RISCV_ADD32          00000000000002d8 .L1^B2 + 0
000000000000000c  0000014700000027 R_RISCV_SUB32          000000000000000c .L0  + 0
0000000000000010  0000014400000023 R_RISCV_ADD32          0000000000000050 .LC2 + 0
0000000000000010  0000014800000027 R_RISCV_SUB32          0000000000000010 .L0  + 0
```

See https://stackoverflow.com/questions/65879012/what-do-pcrel-hi-and-pcrel-lo-actually-do  for a description of how these back references may be used in relocation

**Comment by thixotropist** [comment]
The symbols with names including \x02 or '^B' appear to be generated by the assembler to connect PC-relative relocation request pairs.  Once the relocation pairs have integer offsets assigned the names are ignored, and likely suppressed in other linkers.  If this is generally true, then Ghidra need not worry about preserving, displaying, or resolving such labels.  It should either accept them or ignore them without generating warning messages on input.

**Comment by thixotropist** [comment]
Sounds perfect - thanks!

**Comment by ghidra1** [comment]
I do not see the address error with your sample with the latest master branch.

**Comment by ghidra1** [comment]
I decided to format non-printable ASCII using ^Control char notation for consistency with readelf (e.g., ^B)

**Comment by thixotropist** [comment]
That should be fine.  I see that UTF-8 labels are nicely imported now.  Is it obvious that if \x01 appears as part of a unicode multibyte character in the label your formatting will *not* rewrite the label?

**Comment by ghidra1** [comment]
> That should be fine. I see that UTF-8 labels are nicely imported now. Is it obvious that if \x01 appears as part of a unicode multibyte character in the label your formatting will _not_ rewrite the label?

It should still work OK since it is working with codepoints not bytes.
