### ISSUE TITLE
Text rendering issues

### ISSUE THREAD

**Issue by Nemoumbra** [NationalSecurityAgency/ghidra#5632]
I don't know if this wasn't the case in some old Ghidra versions, but it's been like that for some time and I've confirmed both of the problems in the 10.3.2 version. I've got 3 mainly unrelated complaints.
1) The text in the Ghidra Help often gets corrupted like that:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/62447396/5d2e5913-9144-4e22-8aad-e4d21d59259e)
Or that:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/62447396/c8359c78-8ebd-4112-a7c7-650010a2e601)
The effects can be temporarily removed by selecting the whole section where the error occurred or scrolling iirc.

2) For some reason Ghidra really struggles with the Korean symbols:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/62447396/31fbf4b4-bf6f-4cc2-acc6-98dc639e84f5)
The setting "Render non-ASCII Unicode" is set to "all" in this image. It really is Korean...
![image](https://github.com/NationalSecurityAgency/ghidra/assets/62447396/37683c0c-8a9b-45d1-b2c1-c113b39cf8d9)
There's more than that... `™`, `△`, `＋`, `～`, `【` etc. were rendered as squares too the last time I saw them in Ghidra.

3) We also can see here that the labels for some reason don't support JP and KR hieroglyphs. I think there's even more they don't support knowing that the JP symbols are rendered fine. When I saw the addr pointers to these strings, I thought these two were of length 0.

**Describe the solution you'd like**
The symbols issue looks like an edge case that was never dealt with. I really hope it's not related to the Java GUI templates from the prehistoric age or things like that... It's a standard Unicode, we should be able to do something. The Help text corruption may be harder to fix, but I'm not a pro so I'm leaving this to the discretion of more experienced people.

**Describe alternatives you've considered**
There are no alternatives, we can just technically live without the proper text, but it's not gonna be very pleasant.

**Comment by dev747368** [comment]
There are some options in the support/launch.properties that can modify how java does GUI stuff, and may address your first issue:

```
# The following options affect rendering on different platforms.  It may be necessary to play
# with these settings to get Ghidra to display and perform optimally on HiDPI monitors or in VM's.
VMARGS=-Dsun.java2d.opengl=false
VMARGS_LINUX=-Dsun.java2d.pmoffscreen=false
VMARGS_LINUX=-Dsun.java2d.xrender=true
VMARGS_LINUX=-Dsun.java2d.uiScale=1
VMARGS_LINUX=-Dawt.useSystemAAFontSettings=on
VMARGS_WINDOWS=-Dsun.java2d.d3d=false
```

As far as the issue with displaying strings with characters from Korean, etc alphabets, that typically is controlled by your installed fonts.  The bytes that I can see in your screenshot (f0, c5, b0, etc) display just fine as Korean glyphs, on my machine with the fonts I have.

**Comment by Nemoumbra** [comment]
![image](https://github.com/NationalSecurityAgency/ghidra/assets/62447396/0981189a-2cd2-481a-b211-828a6f5f1bbf)
That's my current font settings. Can you tell me yours? I really doubt this has to do something with my Windows fonts bank. Doesn't Ghidra bundle the necessary stuff with it?

**Comment by dev747368** [comment]
No, Ghidra doesn't bundle any fonts.  It relies on your operating system, and the java jdk's configuration.

Now that you specified windows, I can say that you do have a bit more hurdles than non-windows when it comes to how fonts are handled in a java program.

Typically a single font (eg. Arial), won't specify a glyph for every character in the unicode standard.  When the font a program is using doesn't handle a specific character in a string, the drawing subsystem can fall-back to other fonts to provide a glyph for that character.

Java provides a jdk-level config file that specifies that information: the <jdk_dir>/lib/fontconfig.properties.

The jdk I'm using on my windows box has a fontconfig.properties.src file, which you have to rename to fontconfig.properties before it is used.

By default, it specifies, by name, several fall-back fonts for different alphabets (scripts), and for hangul it has:

```monospaced.plain.korean=GulimChe```

I don't have GulimChe installed, but I do have Malgun Gothic, so I changed my file to reflect that and all is good (for "monospaced" stuff in Ghidra).

If you did install the Gulim family of fonts, you probably wouldn't need to mess with this file.

Microsoft [says that gulim](https://learn.microsoft.com/en-us/typography/font-list/gulim) is something they distribute.

**Comment by Nemoumbra** [comment]
I've enabled Direct3D and so far it looks fine. Continuing to monitor.
Now.... the fonts... Well, it seems that the Gulim font family is not installed in Windows 10 by default. Downloading the additional Korean fonts solved the hieroglyphs issue (no need to touch the files in <jdk_dir>!)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/62447396/0147e5d9-fcaa-48fa-82f5-832afdb28875)
Not the label issue though...
...As for the other symbols, turns out I'm not very great at handling Unicode with Python2. I've fixed the script and the symbols are correct!

**Comment by ryanmkurtz** [comment]
Sounds good.  Feel free to close this issue if you think everything is resolved.

**Comment by Nemoumbra** [comment]
I would've done this by now if not for the one last part... Namely, the labels! I wrote about them in the 3rd paragraph.

**Comment by dev747368** [comment]
Ghidra purposely restricts the contents of automatically generated labels to only include characters that are ascii and limits the length (typically 32 characters).  (its not uncommon to find char[] buffers that aren't used as strings and are initialized with non-string data)

You can put any unicode string you want into a manually created label (except for the space ' ' character, and maybe a couple of others?)

**Comment by Nemoumbra** [comment]
I don't seem to have found any major issues with this since then. As for the labels, I've decided to make a Python script that would recreate the label at the current program address and use the whole string (if there is one and the cursor is at the first symbol, of course).
I'm closing this. Would it make sense to PR the script here in some way or not?
