### ISSUE TITLE
`AddressOutOfBoundsException` for `wordsize > 1` for default symbols

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#5633]
I have a space `ram` with `wordsize=3`. So a register max value is `$FFFFFF`.
Any register can contain a pointer into the `ram`. There are also special ports like `ram:$FFFF82`.
I created the `<default_symbols>` section in `pspec` to specify such a port.

`<symbol name="TPCR" address="ram:FFFF82" entry="false"/>`

But in result Ghidra gives me an error:
```
ERROR Task Error: Loading language 'lang:LE:24:default' - Uncaught Exception: ghidra.program.model.address.AddressOutOfBoundsException: 
Offset must be between 0x0 and 0x2ff, got 0xffff82 instead! (TaskBuilderTask) ghidra.program.model.address.AddressOutOfBoundsException: Offset must be between 0x0 and 0x2ff, got 0xffff82 instead!
	at ghidra.program.model.address.AbstractAddressSpace.makeValidOffset(AbstractAddressSpace.java:620)
	at ghidra.program.model.address.GenericAddressSpace.makeValidOffset(GenericAddressSpace.java:21)
```

**Comment by emteere** [comment]
How is the ram space and register space declared in the .slaspec file?

Almost seems like it could be declared:
define space mem type=ram_space size=1 wordsize=3;

The offset where it is complaining, I believe is a bytes offset.
So the minOffset for this delcaration 256 * 3 = 0x2ff
