### ISSUE TITLE
Building the M1 debugger bridge

### ISSUE THREAD

**Issue by nobbes** [NationalSecurityAgency/ghidra#5637]
I am trying to build the M1 debugger bridge and get some errors about the arm64 and x64 misconfiguration. I removed all targetPlatform in buildNatives.gradle (line 63-66) except "mac_arm_64", replaced the lldb path for the brew version ([issues/4035](https://github.com/NationalSecurityAgency/ghidra/issues/4035#issuecomment-1051006884)) and checked many files for architecture, without success. My configuration is the following:

```
$ lldb --version
lldb-1403.0.17.67
Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
$ which java
/opt/homebrew/opt/openjdk@17/bin/java
$ file /opt/homebrew/opt/openjdk@17/bin/java
/opt/homebrew/opt/openjdk@17/bin/java: Mach-O 64-bit executable arm64
$ java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Homebrew (build 17.0.8+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8+0, mixed mode, sharing)
$ echo $JAVA_HOME
/opt/homebrew/opt/openjdk@17
$ echo $LLVM_BUILD
/opt/homebrew/opt/llvm
$ echo $LLVM_HOME 
/opt/homebrew/opt/llvm
$ gradle -v

------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------

Build time:   2023-07-10 12:12:35 UTC
Revision:     a38ec64d3c4612da9083cc506a1ccb212afeecaa

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.8 (Homebrew 17.0.8+0)
OS:           Mac OS X 13.5 aarch64
```

The building gives the following output:
```
➜  Debugger-swig-lldb git:(master) ✗ gradle build       

> Configure project :
Gradle: 8.2.1
OS: Mac OS X
Arch: aarch64
Using platform: mac_arm_64

> Task :Debugger-swig-lldb:checkLLVM
Debugger-swig-lldb: using LLVM_HOME=/opt/homebrew/opt/llvm

> Task :Debugger-swig-lldb:linkMainSharedLibrary FAILED
ld: warning: ignoring file /opt/homebrew/opt/llvm/lib/liblldb.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: in '/opt/homebrew/opt/llvm/lib/libunwind.dylib', building for macOS-x86_64 but attempting to link with file built for macOS-arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Debugger-swig-lldb:linkMainSharedLibrary'.
> A build operation failed.
      Linker failed while linking liblldb-java.dylib.
  See the complete log at: file:///Users/user/git/ghidra/Ghidra/Debug/Debugger-swig-lldb/build/tmp/linkMainSharedLibrary/output.txt
   > Linker failed while linking liblldb-java.dylib.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 3s
135 actionable tasks: 38 executed, 97 up-to-date
```

Both files are compiled for arm64:
```
$ file /opt/homebrew/opt/llvm/lib/liblldb.dylib
/opt/homebrew/opt/llvm/lib/liblldb.dylib: Mach-O 64-bit dynamically linked shared library arm64
$ file /opt/homebrew/opt/llvm/lib/libunwind.dylib
/opt/homebrew/opt/llvm/lib/libunwind.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

Why it is still building for macOS-x86_64? Any hint is appreciated.

**Comment by d-millar** [comment]
@nobbes This is a bit of a guess, but try removing line 66 from buildNatives.gradle, i.e. I think you did the right thing in build.gradle but missed the one in buildNatives.gradle.  Am hoping this gets you past "gradle build" - let us know if it doesn't.

Judging from your notes (excellent job documenting the problem by-the-by), you may also have another problem when you got to run.  Namely, the current version of the debugger in master has files included that match lldb v16.  You're using v14.  There may be enough of a mismatch between the two to cause JNI mismatches (which will be very hard to diagnose).  The easiest solution is two upgrade lldb to v16.  That said, I could easily understand your not wanting to that.

The alternative is re-generating the SWIG files, i.e. running "gradle generateSwig".  The directions are in the Instructions file in Debugger-swig-lldb, but there are a number of gotchas:
(1) you will need to checkout the lldb source for v14, i.e. "git clone" the repo and "git checkout release/14.x"
(2) you will need to remove the reference to "-D__STDC_LIMIT_MACROS" in buildNatives.gradle
(3) you will need to edit lldb/bindings/interface/SBValueList.i and remove the references to %nothreadallow; and  %clearnothreadallow;
(4) you will need to remember to delete build/generated/src/main from debugger-swig-lldb
(5) you will still see a bunch of errors running "gradle build" in the debugger-swig-lldb directory and will have to delete a half dozen of so Java files that are creating problems
(Backward is sadly harder than forward)

Apologies in advance - we are working on a saner solution....

**Comment by nobbes** [comment]
Thank you so much, this helped a lot!

**Comment by d-millar** [comment]
Our pleasure!
