### ISSUE TITLE
key bindings in code browser (and probably elsewhere) are only conditionally available, which is very confusing

### ISSUE THREAD

**Issue by slippycheeze** [NationalSecurityAgency/ghidra#5638]
**Describe the bug**
Some key bindings in "Tool Options > Key Bindings" are only conditionally available.  For example, in the default Code Browser tool, `Add Enum Value` from `DataTypeManagerPlugin` is not available unless the "Enum Editor" window is *currently open* somewhere in the tool.

This was very, very confusing to me until I figured out the pattern; I'm pretty sure I still think that parts of Ghidra have terrible keyboard support when really I just haven't had whatever appropriate window open or whatever when looking to add one.

My guess is that when the window is closed the bindings / actions are "hidden" so that different tools (and, of course, their different available windows, etc) don't get all cluttered up with actions that they can't entirely use.

**To Reproduce**
1. Open Ghidra 10.3.2 PUBLIC on Java 20.0.2.
2. Open the *default* "Code Browser" tool.
3. Make sure there are **NO** `Enum Editor` windows open anywhere.  Close them if there are.
4. On the menu `Edit > Tool Options`
5. In the `Options for CodeBrowser` dialog, select `Key Bindings`
6. In `Filter` enter `enum` (filtering mode: "contains", only "allow globbing" set, all as default)
7. In the `Action Names` column, look for `Add Enum Value`.
8. OBSERVE: the action **is not** present.
9. Close the dialog.
10. Open the `Enum Editor` by editing/creating any enum.
11. Repeat steps 4-7 looking for `Add Enum Value` as an available action.
12. OBSERVE: the action **is** present, and any keybinding is shown.
13. Close the dialog.
14. Close the `Enum Editor` window, and make sure there are *NO* `Enum Editor` windows open anywhere.
15. Repeat steps 4-7, and observe that `Add Enum Value` has gone away again.

**Expected behavior**
*summary*: the keybind is always available and visible, when the structured editor is avaliable.

In my mind, though, the "Enum Editor" along with the "Structure Editor" and any other window that spawns multiple separate named instances, is "part" of the current tool.  It just isn't shown right now, because an open, empty window wouldn't make sense: each enum gets a new "instance" of the window, rather than reusing an existing window and just swapping out the "thing it is editing" binding.

So, I expect that, eg, `Enum/Structure Editor` actions will always be visible, if the `DataTypeManagerPlugin` is active and could create the respective window.

**Environment (please complete the following information):**
 - OS: Windows 11 22H2 (OS Build 22621.2070) x64
 - Java Version: temurin-jdk 20.0.2
 - Ghidra Version: 10.3.2 PUBLIC 2023-Jul-11 1640 EDT
 - Ghidra Origin: official github release, installed via scoop

scoop manifest: https://github.com/ScoopInstaller/Extras/blob/master/bucket/ghidra.json
specific artifact installed:
```
"url": "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.2_build/ghidra_10.3.2_PUBLIC_20230711.zip",
"hash": "a658677a87d0be12ab65bd7962f471875b81a2dd2ea35d69cc3201555ca1bd6f"
```

**Comment by dragonmacher** [comment]
This should work as you expect.   My guess is that it has to do with how those particular components are registering their actions.    At the very least, 1) once you have shown the Enum provider, it's actions should be remembered for that session.  Ideally, 2) the actions would all be registered at tool startup so that you can edit them, even though you have shown the provider.

We should be able to fix this for the code that we ship.  But, any 3rd-party plugin writers can still add providers that can have delayed loading/registration with the tool.   I can't think of any way to fix this issue.  But, if we can at least support 1 above, then there is at least a path to be able to edit such keybindings.
