### ISSUE TITLE
when "Automatically Save Tools" is enabled, changes to tool options are not saved

### ISSUE THREAD

**Issue by slippycheeze** [NationalSecurityAgency/ghidra#5639]
**Describe the bug**
keybinding changes in the Code Browser (default) tool were not saved for me: I'd bind `C-n` to `Add Enum Value` from the `DataTypeManagerPlugin`, cleanly exit ghidra, and on restart the binding would be lost.  this happened with other config changes, too.

this was fixed, kind of shockingly, by turning *off* "Automatically Save Tools", and then answering "yes" when prompted about saving changes.   now, config changes persist.

**To Reproduce**
1. Open Ghidra, and a project, so the "Edit > Tool Options" dialog for the project window is available.
2. Set "Automatically Save Tools" **ON** in the options.
3. Optionally, fully restart ghidra to demonstrate this is not related to current state.
4. Open the "Code Browser" (default) tool
5. Change a key binding; doesn't really matter which one.  Pretty sure this applies to other options too.  (`Add Enum Value` may not always be accessible; see #5638)
6. Cleanly exit ghidra however you want, and restart
7. in the "Code Browser", the key binding is no longer there.  lost.

**Expected behavior**
This all violates my expectations in two ways:

I expect that when I click "Apply" or "OK" after editing the "Tool Options", those options are persistently saved, forever.  The model of saving configuration as a separate step, eg, when closing the tool, or explicitly, is not what I expected at all.

I also expect, obviously, that if the tool is **automatically saved when closed**, closing it cleanly will save the configuration.  Which it doesn't, the point of this bug. :)

**Environment (please complete the following information):**
 - OS: Windows 11 22H2 (OS Build 22621.2070) x64
 - Java Version: temurin-jdk 20.0.2
 - Ghidra Version: 10.3.2 PUBLIC 2023-Jul-11 1640 EDT
 - Ghidra Origin: official github release, installed via scoop

scoop manifest: https://github.com/ScoopInstaller/Extras/blob/master/bucket/ghidra.json
specific artifact installed:
```
"url": "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.2_build/ghidra_10.3.2_PUBLIC_20230711.zip",
"hash": "a658677a87d0be12ab65bd7962f471875b81a2dd2ea35d69cc3201555ca1bd6f"
```

**Comment by dragonmacher** [comment]
As a workaround, when you hover over the action in the Enum Editor, you can press `F4` to assign a keybinding.   I verified that assigning a keybinding in this way will be saved with the tool automatically when you close it.
