### ISSUE TITLE
Cut text in Configure Tool dialog 'Experimental' package

### ISSUE THREAD

**Issue by danra** [NationalSecurityAgency/ghidra#564]
**Describe the bug**
The text in the Configure Tool for the 'Experimental' package is cut. The text should be shortened or the box size enlarged.

**Screenshots**
<img width="754" alt="Screen Shot 2019-05-04 at 22 23 43" src="https://user-images.githubusercontent.com/84245/57183881-845ae580-6ebb-11e9-9d89-2b2851f5b554.png">

**Environment (please complete the following information):**
 - OS: macOS 10.14.3
 - Ghidra Version: 9.0.2

**Comment by ryanmkurtz** [comment]
Addressed by #372

**Comment by danra** [comment]
Thanks @ryanmkurtz
