### ISSUE TITLE
Some math code doesn't decompile correctly as of 10.0.3 or later

### ISSUE THREAD

**Issue by HumanGamer** [NationalSecurityAgency/ghidra#5640]
**Describe the bug**
As of 10.0.3 some code related to math doesn't decompile correctly and this is still the case in 10.3.1.

In this example, in 10.0.2 output is correct
```c
fVar2 = (float10)globs::INPUT.msy * (float10)0.2083333 - (float10)50.0;
fVar2 = fVar2 * fVar2 * (float10)0.02;
if (mouseY < 240.0) {
  fVar2 = -fVar2;
}
lVar3 = __ftol(fVar2 * (float10)-0.25);
```
but in 10.0.3 or later the output is completely useless
```c
lVar3 = __ftol(in_register_00001000);
```

**To Reproduce**
1. Go to this repository and download the Ghidra project https://github.com/trigger-segfault/legorockraiders-analysis/blob/main/data/ghidra_archive/LegoRR.gar (at the time of writing, it is commit: 9e7675647c24ad5a2d29f61680036c8ee36ea18d)
3. Import the project and go to the function called Front_Menu_UpdateMousePosition
4. On 10.0.3 or later you will notice some of the math got screwed up. On 10.0.2 it will look correct.

**Expected behavior**
The code should output as it does in 10.0.2

**Screenshots**
I don't think screenshots are needed here.

**Attachments**
10.0.2 output:
```c
void __cdecl lego::front::Front_Menu_UpdateMousePosition(Menu *menu)
{
  uint uVar1;
  float10 fVar2;
  longlong lVar3;
  float mouseY;
  
  if ((menu->menuImage == (Image *)0x0) || ((*(byte *)&menu->flags & MENU_FLAG_CANSCROLL) == 0)) {
    globs::frontGlobs.scrollOffset.x = 0;
    globs::frontGlobs.scrollOffset.y = 0;
  }
  else {
                    /* HARDCODED SCREEN RESOLUTION!! */
    mouseY = (float)globs::INPUT.msy;
                    /* If mouseY is not between 200.0f and 280.0f. */
    if (((ushort)((ushort)(mouseY < 280.0) << 8 | (ushort)(mouseY == 280.0) << 0xe) == 0) || (mouseY < 200.0)) {
      uVar1 = menu->menuImage->height;
      if ((mouseY < 480.0) && ((globs::INPUT.mslb == 0 && (globs::INPUT.msrb == 0)))) {
        fVar2 = (float10)globs::INPUT.msy * (float10)0.2083333 - (float10)50.0;
        fVar2 = fVar2 * fVar2 * (float10)0.02;
        if (mouseY < 240.0) {
          fVar2 = -fVar2;
        }
        lVar3 = __ftol(fVar2 * (float10)-0.25);
        globs::frontGlobs.scrollOffset.y = globs::frontGlobs.scrollOffset.y + (int)lVar3;
      }
      if (0 < globs::frontGlobs.scrollOffset.y) {
        globs::frontGlobs.scrollOffset.y = 0;
      }
      if (SBORROW4(globs::frontGlobs.scrollOffset.y + -480,-uVar1) != (int)(globs::frontGlobs.scrollOffset.y + -480 + uVar1) < 0) {
        globs::frontGlobs.scrollOffset.y = 480 - uVar1;
        return;
      }
    }
  }
  return;
}
```

10.0.3 output:
```c
void __cdecl lego::front::Front_Menu_UpdateMousePosition(Menu *menu)
{
  uint uVar1;
  float fVar2;
  float10 in_register_00001000;
  longlong lVar3;
  
  if ((menu->menuImage == (Image *)0x0) || ((*(byte *)&menu->flags & MENU_FLAG_CANSCROLL) == 0)) {
    globs::frontGlobs.scrollOffset.x = 0;
    globs::frontGlobs.scrollOffset.y = 0;
  }
  else {
                    /* HARDCODED SCREEN RESOLUTION!! */
    fVar2 = (float)globs::INPUT.msy;
                    /* If mouseY is not between 200.0f and 280.0f. */
    if (((ushort)((ushort)(fVar2 < 280.0) << 8 | (ushort)(fVar2 == 280.0) << 0xe) == 0) || (fVar2 < 200.0)) {
      uVar1 = menu->menuImage->height;
      if ((fVar2 < 480.0) && ((globs::INPUT.mslb == 0 && (globs::INPUT.msrb == 0)))) {
        lVar3 = __ftol(in_register_00001000);
        globs::frontGlobs.scrollOffset.y = globs::frontGlobs.scrollOffset.y + (int)lVar3;
      }
      if (0 < globs::frontGlobs.scrollOffset.y) {
        globs::frontGlobs.scrollOffset.y = 0;
      }
      if (SBORROW4(globs::frontGlobs.scrollOffset.y + -480,-uVar1) != (int)(globs::frontGlobs.scrollOffset.y + -480 + uVar1) < 0) {
        globs::frontGlobs.scrollOffset.y = 480 - uVar1;
        return;
      }
    }
  }
  return;
}
```

10.3.1 output:
```c
void __cdecl lego::front::Front_Menu_UpdateMousePosition(Menu *menu)
{
  uint uVar1;
  float fVar2;
  float10 in_register_00001000;
  longlong lVar3;
  
  if ((menu->menuImage == (Image *)0x0) || ((*(byte *)&menu->flags & MENU_FLAG_CANSCROLL) == 0)) {
    globs::frontGlobs.scrollOffset.x = 0;
    globs::frontGlobs.scrollOffset.y = 0;
  }
  else {
                    /* HARDCODED SCREEN RESOLUTION!! */
    fVar2 = (float)globs::INPUT.msy;
                    /* If mouseY is not between 200.0f and 280.0f. */
    if ((280.0 < fVar2) || (fVar2 < 200.0)) {
      uVar1 = menu->menuImage->height;
      if ((fVar2 < 480.0) && ((globs::INPUT.mslb == 0 && (globs::INPUT.msrb == 0)))) {
        lVar3 = __ftol(in_register_00001000);
        globs::frontGlobs.scrollOffset.y = globs::frontGlobs.scrollOffset.y + (int)lVar3;
      }
      if (0 < globs::frontGlobs.scrollOffset.y) {
        globs::frontGlobs.scrollOffset.y = 0;
      }
      if (SBORROW4(globs::frontGlobs.scrollOffset.y + -480,-uVar1) != (int)(globs::frontGlobs.scrollOffset.y + -480 + uVar1) < 0) {
        globs::frontGlobs.scrollOffset.y = 480 - uVar1;
        return;
      }
    }
  }
  return;
}
```

**Environment (please complete the following information):**
 - OS: Windows 10 22H2 (OS Build 19045.3208)
 - Java Version: 17.0.6.10
 - Ghidra Version: 10.0.3-10.3.1 (last worked on 10.0.2)
 - Ghidra Origin: Github Releases

**Additional context**
The Ghidra project that I linked to demonstrate this issue is a decompilation of Lego Rock Raiders Masterpiece Edition (x86, Windows)
This bug happens with many functions in that Ghidra project, I just picked one to demonstrate. I would imagine there are other projects with this issue.

**Comment by caheckman** [comment]
This seems to be an upgrade problem.  The input parameter to the function __ftol is stored in the register ST0, but this location does not get updated properly when moving from 10.0.2 to a new version.

You can manually fix it in the new version by reassigning the input parameter to ST0.  This fixes the math errors you are seeing.

**Comment by HumanGamer** [comment]
@caheckman Wow, thanks! That worked.

Is this going to be fixed in a future version, or will the workaround still be necessary in the future?

**Comment by ghidra1** [comment]
@HumanGamer unfortunately the x86 language was not properly versioned when the registers were moved with the release of Ghidra 10.0.3.  Such a register movement requires a major language version change with an associated register mapping.  Unfortunately, this was not done and it is too late to do so.  I have created a Ghidra script `FixOldSTVariableStorageScript.java` which can be run against older programs such as yours to correct all ST0
..ST7 storage assignments.  This script will be included with future releases of Ghida so that others may use as well.  The script is intended to be run from new versions of Ghidra and was tested with Ghidra 10.4.
You will need to remove the `.txt` file extension which was required for attachment.
[FixOldSTVariableStorageScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/13049145/FixOldSTVariableStorageScript.java.txt)

**Comment by HumanGamer** [comment]
Awesome! Thanks.

**Comment by ghidra1** [comment]
@HumanGamer hold up - Forgot to handle function returns.  I need to update script.

**Comment by ghidra1** [comment]
[FixOldSTVariableStorageScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/13057193/FixOldSTVariableStorageScript.java.txt)
Here is the updated scripts which handles function returns as well.
