### ISSUE TITLE
SPARC does not handle manually restored return address after a call

### ISSUE THREAD

**Issue by Ninja3047** [NationalSecurityAgency/ghidra#5646]
**Describe the bug**
```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             rtems_status_code __stdcall rtems_string_to_pointer(char
             rtems_status_c    o0:4           <RETURN>
             char *            o0:4           s
             void * *          o1:4           n
             char * *          o2:4           endptr
                             rtems_string_to_pointer                         XREF[7]:     Entry Point(*), 
                                                                                          args_parse:400a2b9c(c), 
                                                                                          rtems_shell_main_medit:400a30a8(
                                                                                          rtems_shell_main_mfill:400a3184(
                                                                                          rtems_shell_main_mmove:400a35c8(
                                                                                          rtems_shell_main_mmove:400a35e0(
                                                                                          .debug_frame::000030c8(*)  
        40048b78 96 10 20 00     mov        0x0,o3
                                                      o3 = COPY 0:4
        40048b7c 82 13 c0 00     or         o7,g0,g1
                                                      g1 = INT_OR o7, 0:4
        40048b80 40 00 00 2d     call       rtems_string_to_unsigned_long                    rtems_status_code rtems_string_t
                                                      o7 = COPY 0x40048b80:4
                                                      didrestore = COPY 0:1
                                                      o7 = INT_OR g1, 0:4
                                                      CALL *[ram]0x40048c34:4
                                                      $Uff00:1 = INT_EQUAL didrestore, 0:1
                                                      CBRANCH *[ram]0x40048b88:4, $Uff00:1
                                                      RETURN o7
        40048b84 9e 10 40 00     _or        g1,g0,o7
                                                      o7 = INT_OR g1, 0:4
```

The following function in sparc has an optimization where it does not use the register window, but just stashes the return address to g1, and then restores it in the delay slot before performing a call. I've also tried to add a fallthrough override on the call to not fallthrough but that does not appear to affect the decompiler output. The decompilation of this function will start decompiling the next function over which does not seem correct.

**To Reproduce**
1. Open attached binary in Ghidra using the default selected Sparc architecture
2. Go to `rtems_string_to_pointer`
3. Look at decompilation

**Expected behavior**
 * The `or o7, g1, g0`/`call <X>`/`or g1, g0, o7` idiom should correctly identify the flow of the call as no fallthrough
 * the no fallthrough should inform the decompiler to not decompile the next function

**Screenshots**
<img width="2708" alt="Screenshot 2023-08-08 at 2 03 05 PM" src="https://github.com/NationalSecurityAgency/ghidra/assets/1284324/bba527e4-46ca-41a9-9345-ea36a0a1ee9d">

**Attachments**
[core-cpu1.zip](https://github.com/NationalSecurityAgency/ghidra/files/12294581/core-cpu1.zip)

**Environment (please complete the following information):**
 - OS: macOS 13.5
 - Java Version: 17.0.8
 - Ghidra Version: 10.3.2
 - Ghidra Origin: official Github Distro

**Additional context**

**Comment by ghidracadabra** [comment]
I'll take a closer look, but as a quick fix you could try right-clicking on the `call` instruction, selecting "Modify Instruction Flow..." and setting the flow to CALL_RETURN.

**Comment by Ninja3047** [comment]
that does appear to work, thanks

i also noticed that there's specific call/restore handling in the sparc analyzer but it only sets the instruction to no fallthrough but doesn't actually change the call to a CALL_RETURN. https://github.com/NationalSecurityAgency/ghidra/blob/74156281c66f999050700ad53999b45e2dce42dd/Ghidra/Processors/Sparc/src/main/java/ghidra/app/plugin/core/analysis/SparcAnalyzer.java#L86-L109
