### ISSUE TITLE
Feature request: Show all references to each struct field

### ISSUE THREAD

**Issue by ultimaweapon** [NationalSecurityAgency/ghidra#5652]
**Is your feature request related to a problem? Please describe.**
I need to keep track where each struct field read/write in its comment. I would be great if there are a feature to show all of references to the struct field.

**Describe the solution you'd like**
A feature to show all of references to each struct field.

**Describe alternatives you've considered**
Put a comment on each struct field. I'm currently using this method. It work but not great.

**Comment by astrelsky** [comment]
This feature already exists. In the data type manager window right click on the structure and select the option that says something like find all references to field.

**Comment by ultimaweapon** [comment]
Impressive! Thank you for the information.

**Comment by ultimaweapon** [comment]
> This feature already exists. In the data type manager window right click on the structure and select the option that says something like find all references to field. Note that the field must have a name.

After some usages of this feature I found out it is not reliable. Sometime some functions are missing.

**Comment by dragonmacher** [comment]
> After some usages of this feature I found out it is not reliable. Sometime some functions are missing.

To be able to fix the issue we need an example binary that shows the failure.

**Comment by ultimaweapon** [comment]
Okay. I'll report back when I find something useful. Thank you.
