### ISSUE TITLE
Unable to grok CALLOTHER override return value

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#5667]
**Describe the bug**
I am trying to implement a CALLOTHER override as shown in the Improving Disassembly and Decompilation guide.  This seems to be working fine so long as the PcodeOp has no return value, but for PcodeOps that do return a value, I get a
message:
  WARNING: Output of read_cp0_register destroyed by override!
and the decompiler window shows:
   Low-level Error: Output of call was determined prematurely

The warning in the listing is generated in PostCommentFieldFactory.java when a CALLOTHER PcodeOp is overridden and has a non-null output, so perhaps this is a known limitation, in which case it would be helpful if that was reflected in the Improving Disassemble and Decompilation guide.

I believe that this may be the underlying problem that was reported in Issue #304.

**To Reproduce**
Add a CALLOTHER_OVERRIDE_CALL override to a CALLOTHER PcodeOp that produces an output value.  In the case below, it is reading a coprocessor register:

Before Override:
        901ed5f4 f7 20 30 28     mfc0       a3,0x17,0x5
                                                      a3 = CALLOTHER "read_cp0_register", 23:1, 5:1, 0:1
After Override:
        901ed5f4 f7 20 30 28     mfc0       a3,0x17,0x5
                                                      a3 = CALL *[ram]0x6bfffff1:4, 23:1, 5:1, 0:1
                             WARNING: Output of read_cp0_register destroyed by override!

**Expected behavior**
I'm not particularly bothered by the warning in the listing window, but the decompiler failing on this function is a major impact.

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 23.04
 - Java Version: openjdk 11.0.20
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official GitHub distro

**Additional context**

**Comment by ghidracadabra** [comment]
The restriction is documented in the Ghidra Help (search for "Ref-Types" and scroll down to the table) but admittedly that's a bit hidden.  We can add a note to the class.

In general the overriding references work best on instructions whose SLEIGH definitions were written with overriding references in mind (and there are a number of existing definitions which should be updated).

**Comment by marcushall42** [comment]
Yes, the Improving Disassembly and Decompilation guide is where I learned of the override type, and that's been linked to by other web pages, so it's where others are likely to encounter it.

The help page says "can adversely affect decompilation" feels like an understatement, since it seems to crash the decompiler, but it is accurate, I guess.

In my case, the move from coprocessor register seemed like the sort of thing that would be convenient to be overridden.  In particular, I wanted to type the return to be a structure pointer.  Typing the source for the set coprocessor register works fine, so it just seemed like a logical next step.

It feels like the implementation is 90% complete, but I'm sure that the remaining 10% may take a disproportionate effort, so I'm just happy with what *is* there.  I certainly didn't expect the decompiler to completely shut down, though.
