### ISSUE TITLE
decompiler-local or function-local "human" labels, without adding to global label / symbol list

### ISSUE THREAD

**Issue by slippycheeze** [NationalSecurityAgency/ghidra#5674]
**Is your feature request related to a problem? Please describe.**
Large C++ functions that implement a "decision list" often use a shared return to handle cleanup and reporting.  This is decompiled nicely as `if (condition) { ...; goto LAB_18014d9b1; }` repeatedly, or as nested conditionals doing the same.

Sometimes there are two common exit paths (eg: success, failure), but even without it is relatively hard as a human to hold the specific meaning of `LAB_18014d9b1` in my head while looking at 180 lines (and 7916 characters) of decompiler output, as well as moving through called functions.

It is much easier to remember what `goto reject_this_connection;` means, but editing the label in the decompiler or listing view also adds `reject_this_connection` globally to the label list in the symbol tree, which is undesirable.  (especially for things like `goto cleanup` which are relatively commmon.)

**Describe the solution you'd like**
It seems to me that being able to rename or add a label "locally" to a function, the same way I can name stack and register values in the decompiler (by the HASH:... identity) or listing, would be entirely appropriate here.

The label is a "high level" human construct, but only relevant inside the current function, the same way that a "register" might have a high level Varnode associated during this function, but it implies nothing about any other function.

**Describe alternatives you've considered**
Right now my label list has a whole bunch of `reject_this_connection_18014d9b1` labels in it, because that at least disambiguates them for me; other "naming conventions" come with the same global pollution for something that will *never* be referenced outside the local function.

**Additional context**
A sanitized version of decompiler output for the function I'm currently working on, to illustrate exactly what I mean by "decision list" style functions follows.  It's brutally hacked to remove noise, so don't be surprised that it isn't "real" decompiler output.  I figure it illustrates the concept, and the concrete reality isn't needed for this feature request.

```c
bool __thiscall ShouldAcceptConnection(Server *this, ConnectRequest *packet, std::string *reason_to_reject)
{
    char *reason_to_reject_text;
    ulonglong reason_to_reject_length;

    reason_to_reject->length = 0;
    psVar6 = (char *)reason_to_reject;
    if (0xf < reason_to_reject->capacity) {
        psVar6 = (reason_to_reject->storage).c_str;
    }
    *psVar6 = '\0';

    if (GameInfo.max_players <= GameInfo.current_players) {
        reason_to_reject_length = 8;
        reason_to_reject_text = "GameFull";
        goto reject_this_connection_18014d9b1;
    }

    if (GameInfo.password.length != 0) {
        iVar4 = wcstr_compare(
                (packet->password).wc_str, (packet->password).length,
                GameInfo.password.wc_str, GameInfo.password.length
        )
        if (iVar4 != 0) {
            reason_to_reject_length = 8;
            reason_to_reject_text = "Password";
            goto reject_this_connection_18014d9b1;
        }
    }
    
    // repeat the above seven more times, some with significantly more complexity

    reason_to_reject_length = 0xb;
    reason_to_reject_text = "PlayerLevel";

reject_this_connection_18014d9b1:
    std::string::string(reason_to_reject,reason_to_reject_text,reason_to_reject_length);
    return false;
}
```

note: the `std::string` type models the internals of an MSVC C++ `std::string`, hand-written, hence the complexity in interactions, most of which I've elided.

**Comment by caheckman** [comment]
If you click on a label or address in the listing and select "Edit Label..." or "Add Label..." (bound to the 'L' key by default), the dialog has a drop down menu for namespace that lets you move the label into the function's namespace.  This will take the label out of the global symbol list.  Is this what you had in mind?
