### ISSUE TITLE
Cannot "Add To Program" with DefLoader

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#5676]
### Discussed in https://github.com/NationalSecurityAgency/ghidra/discussions/5673

<div type='discussions-op-text'>

<sup>Originally posted by **RadWolfie** August 17, 2023</sup>
I tried to look in known places in Ghidra to import .def file extension for Windows executable project. Yet, I came up with nothing other than "load pdb file" which isn't what I'm looking for. I have executable file has over 200 export names that need to be named from .def file in order to reverse engineer easier.

 I do see [DefLoader.java](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/DefLoader.java) file do exist yet seems doesn't connect with Windows' executable interface/context menus or something? Or Ghidra doesn't have def file extension import feature support built-in yet?

Another thing I do see in "Supported Formats" info window is "Module Definition (DEF)" except only show as raw binary from import file option which I'm pretty sure is wrong way to do it.
</div>

**Comment by RadWolfie** [comment]
Here's the [sample files](https://github.com/NationalSecurityAgency/ghidra/files/12380888/ghidra-exe-def-sample.zip) per requested by @ryanmkurtz. It contains .def, .exe, and .ord (from dumpbin tool) files. I am unable to remove underscore from the sample files. In our .def file does not have underscope in the API functions and does work fine.

**Comment by ryanmkurtz** [comment]
Thank you.  What generated the .def file?  Its format seems to be not quite what we expect.

**Comment by RadWolfie** [comment]
I'm not the founder of the project and we had it like that since beginning of the project many years ago. I don't recall anyone asked about what generated the def file. If I had to guess, it wasn't generated but added manually? Compilers doesn't care about whitespaces. I assumed the founder of the project preferred indent the columns for better visual. It's the similar way for dumpbin to have indent columns as well.

I'm using the actual reference of [xboxkrnl.exe.def](https://github.com/XboxDev/nxdk/blob/master/lib/xboxkrnl/xboxkrnl.exe.def) file to work with dumped xboxkrnl.exe file from xbox hardware console.

**Comment by ryanmkurtz** [comment]
I've researched the [DEF format](https://learn.microsoft.com/en-us/cpp/build/reference/exports?view=msvc-170) a bit and the files you are working with seem like they are valid, so we should update our parser.  We also need to enable "Add To Program" support in the `DefLoader`...I'm not sure why that got turned off.

**Comment by ryanmkurtz** [comment]
@RadWolfie if you are able to build Ghidra, you can test my changes here: https://github.com/ryanmkurtz/ghidra/tree/defloader

**Comment by RadWolfie** [comment]
Steps took to test your defloader branch:
1) Launch Ghidra from bat script (after finish build it).
2) Create new project.
3) Add ghidra-exe-def-sample / xboxkrnl.exe file(s) to project.
4) Open either executable file within project tree.
5) From main menu, File > Add to Program > select .def file for the executable project to add into program.
6) Dialog shows Format: **Module Definition (DEF) is listed as default** (was Raw Binary). Click OK button.

No error was reported for either one. I can see given def's symbol names are now used for both of them. After selective ordinal number of functions and data pointers investigation. I can confirm they are a match with past reverse engineered documented.

Thanks! Can't wait to see it gets upstream. 🥳

**Comment by ryanmkurtz** [comment]
Thanks for testing! I'll work on getting it upstream.
