### ISSUE TITLE
Mixed DEC and INC with LOCK prefix

### ISSUE THREAD

**Issue by jobermayr** [NationalSecurityAgency/ghidra#5677]
`F0FF08` should be `DEC.LOCK` [see Constructor line #'s: DEC(lockable.sinc:690)] not `INC.LOCK`.
@ekilmer, @ghidra1: ?
![image](https://github.com/NationalSecurityAgency/ghidra/assets/588670/fde964ba-3377-40a2-b752-3289bbc72c3d)

**Comment by GhidorahRex** [comment]
What version of Ghidra are you using?

I thought this might be a language issue, but the fact that the constructor and the instruction mnemonic disagree on what instruction it is suggests that something else might be going on.

**Comment by jobermayr** [comment]
It is on latest master c9f2819

**Comment by emteere** [comment]
It is possible that the compiled .sla file is out of sync .slaspec/.sinc source.  However it is also possible there is some hash-code collision issue with the prototypes and the prototype cache.  So as not to destroy the potential evidence of a problem, can you do the following:

If you clear and redisassemble, does the INC come back?
If you run the script ReloadSleighLanguage which recompiles the sleigh file and re-disassembles, does the instruction stay an INC?
If it does, clear the instruction and re-disassemble, is it still an INC?
If it is still an INC, exit ghidra then bring back up the location.  Is it still an INC?
Clear and re-disassemble. Is it still an INC?
Re-import and re-analyze, is it still an INC?

I suspect it will stop being an INC if the Sleigh is re-compiled, but I just didn't want to destroy your programs current state if there was some other bug/issue.

**Comment by GhidorahRex** [comment]
Is this file freshly imported, or did it go through a language upgrade? In general, there shouldn't be a disagreement between the reported instruction mnemonic and the mnemonic of the constructor of the instruction.

You may try deleting the `.sla` file from the languages directory and closing/reopening ghidra. It will force a recompile of the language module.

**Comment by jobermayr** [comment]
> If you run the script ReloadSleighLanguage which recompiles the sleigh file and re-disassembles, does the instruction stay an INC?

This helped. Thanks.

**Comment by ryanmkurtz** [comment]
@jobermayr Can this be closed?

**Comment by jobermayr** [comment]
Closing
