### ISSUE TITLE
Debugging application using remote target in gdb

### ISSUE THREAD

**Issue by axel7083** [NationalSecurityAgency/ghidra#5688]
Related issue https://github.com/NationalSecurityAgency/ghidra/issues/5386

I am using a GDB stub provided by an emulator, and I am trying to use the debugger properly on the "decompiled" code, but the breaks and other features are not working in the static side.

Here is the step I am following
1. In my ghidra project I open the file I am interesting to debug with "Debugger" 
<img width="285" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/42176370/db1d80b7-0606-4ac4-9db8-e524b1c49fe7">

2. Then I use the option to debug with GDB

<img width="467" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/42176370/6fe1bfd3-a15c-425d-a1a4-c0e6a01413b5">

3. I start the gdb interpreter (I am actually using gdb-multiarch from [mingw-w64-clang-x86_64-gdb-multiarch](https://packages.msys2.org/package/mingw-w64-clang-x86_64-gdb-multiarch?repo=clang64)) 

Once the target set i got the following

<img width="395" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/42176370/ede00046-4be8-4a1b-86ad-25843b04c1bd">

4. Cannot set breakpoint from the decompiler tab

When using the set breakpoint on the Dynamic tab, I am able to see them and make them works. However the one set in the decompiler tab are gray.

<img width="394" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/42176370/02e8bd44-dc3b-48c7-aa3f-d9af84dcabab">

> The addresses are perfectly matching between the dynamic and decompiler

**Comment by d-millar** [comment]
It sounds like the debugger is unable to map the static addresses to the dynamic addresses.  The static addresses are provided by the imported program; the dynamic addresses are provided by the debugger proper.  The mapping between them is provided by the commands "info proc mappings" and "maintenance info sections --all-objects".   

Not all targets implement these commands (emulators are notorious for this).  If your target does not support these commands, the Modules and Regions Listings will be empty.  If, as you indicated, the static and dynamic addresses are identical, you can select "Map one-to-one" from the pull-down on one of those listings (apologies - I don't have Ghidra available at the moment), and the debugger will just assume they are equal.

You can also map individual modules to address ranges at an offset if the static and dynamic ranges differ.  And, if need be, you can define the two commands that are missing to provide the debugger with the info it needs.  There are a number of posts in the GitHub Issues and Discussions pages that describe how to do this.

If any of the above isn't sufficiently clear or fails to get you going, let me know.  I can provide more explicit directions when I get to somewhere that I can run Ghidra from.

**Comment by axel7083** [comment]
Thanks you for the answer and explanation, really appreciate.

 > If, as you indicated, the static and dynamic addresses are identical, you can select "Map one-to-one" from the pull-down on one of those listings (apologies - I don't have Ghidra available at the moment), and the debugger will just assume they are equal.

My emulator break on startup. So when the gdb connects to the emulator, the f command give the address `0x02004800` (just for reference). As visible here

<img width="481" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/42176370/50d0a33b-72a4-40a1-a27a-bb7e91a5126a">

I can confirm that the imported program have matching addresses.

In the Regions tab, I had a region visible, I have the option to map to one of my block in my imported program

<img width="607" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/42176370/6d6077e9-ac48-4182-a12e-58edb57e8ccb">

But when I map it, and then set a breakpoint in the Decompiler option, I do not get the break set properly (missing base address ?) 

<img width="701" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/42176370/8fc9288f-9a4f-43bf-a3d3-2f5360cc147a">

In the GBD interpreter I also got the wrong address for the breakpoint

<img width="288" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/42176370/86998078-506e-451f-b786-c62619616c5f">

I think from this point, I think this is probably me just missing some configuration...

**Comment by d-millar** [comment]
OK, so, apologies, more detail definitely merited - I definitely led you astray.

By choosing that first option, you essentially said sm64dse lives in the address space 00000000-FFFFFFFF at address 0.  When you added the breakpoint in the Decompiler at 20048a4, it presumable looked at sm64dse, which I'm guessing has a base address of 2004000, subtracted the base address and added the breakpoint to dynamic memory at 8a4.  Not what you wanted.

So, I think one of two paths is the right solution (@nsadeveloper789 maybe will weight in here to make sure I'm not operating on insufficient caffeine):   (1) in the Modules windows, select the <=> button ("Map the current trace to the current program using identical addresses, or (2) in the Regions windows below the option you selected, choose "Map region to sm64dse" and set the Dynamic Base to be equal to the Static Base.  Am sure there's a difference between these two approaches (which I honestly can't remember at the moment), but one of them should do the right thing.

**Comment by d-millar** [comment]
Our pleasure - keep us posted if you hit more issues on our end!

**Comment by axel7083** [comment]
Just a small question, I get a lot of `Not supported on this target.` in the gdb interpreter, is it possible to know each time which command is not supported ?
