### ISSUE TITLE
API to access function parameter names

### ISSUE THREAD

**Issue by cblichmann** [NationalSecurityAgency/ghidra#569]
I'm trying to programmatically access function parameter names that are referenced by an `Instruction`'s operand.

I have code like this (hardcoded for my simple example binary):
```java
var instr = program.getListing().getInstructionAt(0x1420);
var cf = new CodeUnitFormat(new CodeUnitFormatOptions());
for (int i = 0; i < instr.getNumOperands(); i++)
  System.out.println("op #%d: \"%s\"", i, cf.getOperandRepresentationString(instr, 1);
```
The snippet above gives me the operand strings `dword ptr [RBP + local_c],param_1` and `EDI`, and the "Instruction Info" window agrees on that. However, the CodeBrowser seems to know more: ![Screenshot from 2019-05-06 01-00-42](https://user-images.githubusercontent.com/213059/57201576-040bb180-6f9b-11e9-82e7-e69e004378c5.png)

I have also unsuccessfully tried to access the various pieces of an instruction by using `Instruction::getOpObjects()`.

How do I properly access this information? Do I have to walk the `Function`'s stack `AddressSpace` and find references?

**Comment by saruman9** [comment]
You can use custom `CodeUnitFormatOptions​` ([see API documentation](http://ghidra.re/ghidra_docs/api/ghidra/program/model/listing/CodeUnitFormatOptions.html#%3Cinit%3E(ghidra.program.model.listing.CodeUnitFormatOptions.ShowBlockName,ghidra.program.model.listing.CodeUnitFormatOptions.ShowNamespace,java.lang.String,boolean,boolean,boolean,boolean,boolean,boolean,boolean))).

For example:
```java
Instruction instruction = currentProgram.getListing().getInstructionAt(currentAddress);
CodeUnitFormat codeUnitFormat = new CodeUnitFormat(
    new CodeUnitFormatOptions(
        CodeUnitFormatOptions.ShowBlockName.ALWAYS,
        CodeUnitFormatOptions.ShowNamespace.ALWAYS,
        "", true, true, true, true, true, true, true)
    );
for (int i = 0; i < instruction.getNumOperands(); i++) {
    printf("op #%d: \"%s\"\n",
        i,
        codeUnitFormat.getOperandRepresentationString(instruction, i)
    );
}
```
will give you, what you need.

**Comment by ryanmkurtz** [comment]
Thanks @saruman9, I will assume you've answered @cblichmann's question.

**Comment by cblichmann** [comment]
Thanks @saruman9, this is kind of what I was looking for. I'll still have to dive into the implemantion of the CodeFormatter though :)
