### ISSUE TITLE
Potentially illegal CPOOL references in JVM's SLEIGH definitions

### ISSUE THREAD

**Issue by kjcolley7** [NationalSecurityAgency/ghidra#5695]
https://github.com/NationalSecurityAgency/ghidra/blob/ba5fcdf4ede478ba1d394cc1efa7802099023510/Ghidra/Processors/JVM/data/languages/JVM.slaspec#L52

For both `CPOOL_PUTFIELD` and `CPOOL_ARRAYLENGTH`, these types are defined as `"16:4"` and `"17:4"`. The expected format of this parameter isn't well documented, but I'm assuming it's supposed to be `<value>:<bitwidth>`. Obviously, the values 16 and 17 don't fit in 4 bits (0-15).

I haven't encountered any specific problems caused by this. Rather, I just stumbled across this while writing my own SLEIGH definitions for a new processor module and looking at examples from other processors.

**Comment by ghidracadabra** [comment]
Sizes in SLEIGH are in bytes, not bits.  

Those particular definitions need to match the ones defined here: https://github.com/NationalSecurityAgency/ghidra/blob/0233f35d1fe487bf71cf0055a6cbfbe17c46bbdc/Ghidra/Processors/JVM/src/main/java/ghidra/app/util/pcodeInject/ConstantPoolJava.java#L37C1-L55C54
