### ISSUE TITLE
10.3.2 crashes when analyzing medium binary file

### ISSUE THREAD

**Issue by 20urc3** [NationalSecurityAgency/ghidra#5697]
**Describe the bug**
It appears that the latest version of Ghidra crashes when analyzing a medium binary file (+- 100mo FoxitPdfreader)

**To Reproduce**
- Unzip Ghidra release
- Import Foxit Pdf Reader 12.1.3.15356
- Open the file
- Start analyzing with default settings

**Expected behavior**
Just before the end of the analysis Ghidra crashes.

**Attachments**
Attached 2 hs_err files.
[hs_err_pid10992.log](https://github.com/NationalSecurityAgency/ghidra/files/12409963/hs_err_pid10992.log)
[hs_err_pid7548.log](https://github.com/NationalSecurityAgency/ghidra/files/12409964/hs_err_pid7548.log)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 17.0.7 64-bits
 - Target Binary: Foxit PDF reader 12.1.3.15356
 - Ghidra Version: 10.3.2
 - Ghidra Origin: official GitHub distro
[](url)

**Comment by 20urc3** [comment]
@ryanmkurtz **filename:** FoxitPDFReader1213_enu_Setup_Prom.exe **md5:** 1fc2140fe5a795c097468c2819e5bed8

**Comment by 20urc3** [comment]
@ryanmkurtz i've put the log files attached.

**Comment by ryanmkurtz** [comment]
That is appreciated...it looks like it potentially died during Garbage Collection.  This seems like more of an issue with your JDK.  Does it happen every time for you?  Can you try a different JDK?  Unfortunately if we can't reproduce it we will not be able to fix it (if it's even a Ghidra issue to begin with).

**Comment by 20urc3** [comment]
Hi, i've run the test:
- JDK 17.0.7 => crashes
- JDK 20.0.2 => don't crash

I wont investigate further but you have the logs if you really want to.
Thanks for your help
