### ISSUE TITLE
Compiler generated function to copy a structure onto the stack (`PUSH` for an object) interfers with later analysis

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#5702]
### Discussed in https://github.com/NationalSecurityAgency/ghidra/discussions/5491
The current inability to tell Ghidra that a function is equivalent to an assembly `PUSH` statement is causing misinterpretation of parameters already placed on the stack for the suubsequently called function.

The pseudo code below indicates a potentential call:
`a = fn1(x, y, PushObjectCopy(z, sizeof(z)), b);`

[Here's](https://github.com/NationalSecurityAgency/ghidra/files/12421436/dragon_FUN_1070_17a1.zip) an example function containing such a call.  (This is from a Windows 3.xx DLL (including the use of `far` pointers)!)

**Comment by ghidracadabra** [comment]
Have you tried using a callfixup?  If a callfixup is defined for `foo` then calls to `foo` will be replaced with a snippet of pcode during decompilation.  They can be defined in cspec files (see `x86win.cspec` for some examples).  You can also define one for a specific program as a specification extension (search the Ghidra help for "specification extension" for details).

**Comment by Wall-AF** [comment]
@ghidracadabra I'm unsure of how to attempt this!  The function `PushObjectCopy` already exists with this assembly:
```
                             void*32 __cdecl16far PushObjectCopy(void*32 pvSrc, size_
                               assume DS = 0x1210
             void *32          DX:2,AX:2      <RETURN>
             void *32          DX:2,AX:2      pvSrc
             size_t            CX:2           nCX

   1000:0843 5b             0           POP        BX
   1000:0844 07            -2           POP        ES
   1000:0845 2b e1         -4           SUB        SP,CX
   1000:0847 06           - ? -         PUSH       ES
                             LAB_1000_0848                                   XREF[1]:     StackRollbackNear?:1000:0841(j)  
   1000:0848 53           - ? -         PUSH       BX
   1000:0849 57           - ? -         PUSH       DI
   1000:084a 1e           - ? -         PUSH       DS
   1000:084b 8b fc        - ? -         MOV        DI,SP
   1000:084d 83 c7 08     - ? -         ADD        DI,0x8
   1000:0850 8c d3        - ? -         MOV        BX,SS
   1000:0852 8e c3        - ? -         MOV        ES,BX
   1000:0854 8e da        - ? -         MOV        DS,DX
   1000:0856 96           - ? -         XCHG       AX,SI
   1000:0857 fc           - ? -         CLD
   1000:0858 d1 e9        - ? -         SHR        CX,0x1
   1000:085a f3 a5        - ? -         MOVSW.REP  ES:DI,DS:SI
   1000:085c 13 c9        - ? -         ADC        CX,CX
   1000:085e f3 a4        - ? -         MOVSB.REP  ES:DI,DS:SI
   1000:0860 96           - ? -         XCHG       AX,SI
   1000:0861 1f           - ? -         POP        DS
   1000:0862 5f           - ? -         POP        DI
   1000:0863 cb           - ? -         RETF
```
the issue is that when it is called, Ghidra understands that the return address is put on the stack and subsequently removed after the call, but, even though I've modified each stackDepth with the value of the parameter (in the register `CX`) it isn't interpreted correctly and doesn't realise that a duplicate of the object pointed to by `pvSrc` has been placed on the stack!

Am I misunderstanding what you're saying I should do???  If so, could you show a full e2e example please?  Thanks.

**Comment by ghidracadabra** [comment]
I'm assuming that your issue relates to problems with Ghidra's decompilation (but I'm not 100% sure).

Roughly, Ghidra's decompiler works on one function at a time.  If `foo` contains a call to `bar`, the decompiler does not examine the body of `bar` while decompiling `foo`.  If information about the signature of `bar` has been saved to the program database, the decompiler will incorporate it into its decompilation.  If not, it will apply heuristics at each call site and make a best guess as to the parameters.

In general this is a reasonable strategy, but there is an issue with callees whose effects the decompiler needs to know.  A standard example is a function which puts some kind of exception handling stuff onto the stack.  If the decompiler thinks the stack pointer was restored by a callee, but the compiler knew that it wasn't, then there's a problem.  A "call fixup" replaces calls to certain functions with snippets of pcode which represent the information the decompiler needs to know about a callee.

It's not possible for us to produce an e2e example for every problematic binary, but I will create a ticket to add an example of creating a call fixup, importing it as a program specification, and applying it to a problematic function in the advanced usage Ghidra class (`improvingDisassemblyAndDecompilation.pdf`).

**Comment by Wall-AF** [comment]
In the `callfixup`, I'd need a implement a call (or inlined) to something like the macro below (if it is syntactially feasable - please advise):
```
macro push2y(x,y) {
  mysave:y = x;
  SP = SP -y;
  tmp:$(SIZE) = segment(SS,SP);
  *:y tmp = mysave;
}
```
where the `x`&`y` come from parameters to the function being fixed-up!

**Comment by Wall-AF** [comment]
Mmm, Ghidra doesn't like the below added to the cspec file!
```
  <callfixup name="PushObjectCopy">
    <pcode dynamic="true">
      <input name="pObj"/>
      <input name="nSize"/>
      <body><![CDATA[
        mysave:nSize = *pObj;
        SP = SP - nSize;
        tmp:$(SIZE) = segment(SS,SP);
        *:nSize tmp = mysave;
      ]]></body>
    </pcode>
  </callfixup>
```
I think that's what I need to achieve (logically).
It's failing on the required dynamic use of `:nSize` (the 2nd parameter to the function).  It seems to also be failing on resolving `$(SIZE)` - which I can hard code to `2`.

**Comment by astrelsky** [comment]
> Mmm, Ghidra doesn't like the below added to the cspec file!
> ```
>   <callfixup name="PushObjectCopy">
>     <pcode dynamic="true">
>       <input name="pObj"/>
>       <input name="nSize"/>
>       <body><![CDATA[
>         mysave:nSize = *pObj;
>         SP = SP - nSize;
>         tmp:$(SIZE) = segment(SS,SP);
>         *:nSize tmp = mysave;
>       ]]></body>
>     </pcode>
>   </callfixup>
> ```
> I think that's what I need to achieve (logically).
> It's failing on the required dynamic use of `:nSize` (the 2nd parameter to the function).  It seems to also be failing on resolving `$(SIZE)` - which I can hard code to `2`.

Don't add it to the cspec file. Put it in its own xml file add import it in the specification extensions menu (edit->options for program name -> specification extensions) or something like that.

**Comment by Wall-AF** [comment]
Thx @astrelsky.  However, I'm still getting the same issue in that the element after the `:` in `mysave:... = *pObj;` doesn't seem to allow vars!

**Comment by astrelsky** [comment]
> Thx @astrelsky. However, I'm still getting the same issue in that the element after the `:` in `mysave:... = *pObj;` doesn't seem to allow vars!

It looks like there are a few problems here actually. Sleigh doesn't allow subpiece to be dynamic, ie you can't do (mysave:nSize) but you could do (mysave:4). Also I don't think you can have named inputs in the specification extensions, you would have to use the registers directly.

You can try something like this. I'm not familiar with 16 bit x86 and it has been a while since I've messed with sleigh so don't expect this to work out of the box. It should get you started though.

[PushObjectCopy.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/12445249/PushObjectCopy.xml.txt)

**Comment by Wall-AF** [comment]
Thx, once again @astrelsky.  Had to replece `+=` as sleigh interpreter didn't!  Now I'm left with the correct stack adjustments, but the decompilation doesn't connect the variable names to the assembler ones!  I'll try to find a short example I can post here soon.

**Comment by Wall-AF** [comment]
Any further assistance here folks?

The fixup is now:
```
<callfixup name="PushObjectCopy">
<target name="PushObjectCopy"/>
<pcode>
<body><![CDATA[
	SP = SP + 4;
	pvSrc:4 = segment(DX,AX);
	SP = SP - CX;
	pvDst:4 = segment(SS,SP);
	<loop>
	if (CX <= 0) goto <end>;
	*:1 pvDst = *:1 pvSrc;
	pvDst = pvDst + 1;
	pvSrc = pvSrc + 1;
	CX = CX - 1;
	goto <loop>;
	<end>
]]></body>
</pcode>
</callfixup>
```
and partially works, but I'm experiencing odd output even in calls occuring before this gets used (see mainly the addition of `uVar8 = 01360; uVar7 = 0x1373;` in the highlighted section in the image below)!
![image](https://github.com/NationalSecurityAgency/ghidra/assets/67698927/c580caf1-bd62-4d43-83e8-a0e9729d514b)

**Comment by Wall-AF** [comment]
@ryanmkurtz not sure why this was closed, the issue still exists.

**Comment by Wall-AF** [comment]
All examples seem to be for more modern processors that in general are better supported.

**Comment by Wall-AF** [comment]
This is still outstanding, can it be reopened please?

**Comment by Wall-AF** [comment]
What's currently missing is that the stack changes aren't reflected through, leaving the decompiler not knowing the stack position which in turn breaks subsequent analysis.

**Comment by ryanmkurtz** [comment]
Deferring to @ghidracadabra

**Comment by Wall-AF** [comment]
@ghidracadabra I've followed the example in the `improvingDisassemblyAndDecompilation.pdf` doc and then tinkered with my `callfixup` and have successfully got it to reflect the correct stack change by replacing the body with just
`   SP = SP - CX + 4;`

However, whilst that fixes the stack and therefore the subsequent calls, Ghidra loses the context of what should have been copied onto the stack (i.e. the CX bytes)!  So, in the simple case below, Ghidra produces
```
   idVocab = ((DgnWordAdaptLm1_t *)this)->?nID_0x8;
   idWord = ((DgnWordAdaptLm1_t *)this)->field2_0x8;
   GetRelHigh();
   GetRelMid();
   relInf.nShortNewRelevance_0x4._2_2_ = in_stack_0000ffe6;
   relInf._0_6_ = in_stack_0000ffe0;
   relInf.?_0x8._0_2_ = (tmp10d0_0000_0xa_t *)0x686;
   relInf.?_0x8._2_2_ = unaff_CS;
   FUN_1080_0520(idVocab,idWord,relInf);
```
from
```
   1080:0639 c4 5e 06     014           LES        BX,SS:[BP + this]
   1080:063c 26 8b 77 06  014           MOV        SI,word ptr ES:[BX + 0x6]
   1080:0640 66 26 8b     014           MOV        EAX,dword ptr ES:[BX + 0x8]
             47 08
   1080:0645 66 89 46 fc  014           MOV        dword ptr SS:[BP + local_6],EAX
   1080:0649 9a a0 06     014           CALLF      GetRelHigh                                       long GetRelHigh(void)
             80 10
   1080:064e 66 c1 e0 10  014           SHL        EAX,0x10
   1080:0652 66 0f ac     014           SHRD       EAX,EDX,0x10
             d0 10
   1080:0657 66 89 46 f0  014           MOV        dword ptr SS:[BP + local_12],EAX
   1080:065b 9a aa 06     014           CALLF      GetRelMid                                        long GetRelMid(void)
             80 10
   1080:0660 66 c1 e0 10  014           SHL        EAX,0x10
   1080:0664 66 0f ac     014           SHRD       EAX,EDX,0x10
             d0 10
   1080:0669 66 89 46 f4  014           MOV        dword ptr SS:[BP + 
                                                   local_12.nShortNewRelevance_0x4],EAX
   1080:066d c4 5e 06     014           LES        BX,SS:[BP + this]
   1080:0670 66 26 8b     014           MOV        EAX,dword ptr ES:[BX + 0x18]
             47 18
   1080:0675 66 89 46 f8  014           MOV        dword ptr SS:[BP + local_12.?_0x8],EAX
   1080:0679 8d 46 f0     014           LEA        AX,[BP + local_12]
   1080:067c 8c d2        014           MOV        DX,SS
   1080:067e b9 0c 00     014           MOV        CX,0xc
   1080:0681 9a 43 08     014           CALLF      PushObjectCopy                                   void PushObjectCopy(void*32 pvSr
             00 10
   1080:0686 66 ff 76 fc  020           PUSH       dword ptr SS:[BP + local_6]
   1080:068a 56           024           PUSH       SI
   1080:068b 0e           026           PUSH       CS
   1080:068c e8 91 fe     028           CALL       FUN_1080_0520                                    void FUN_1080_0520(IDX_ONE_BASED
```
completely missing out the fact that the two `GetRel...()` functions return `long` values into two of the fields of `local_12` [^1] and that the 3rd field is from the 0x18th byte of the `this` object.  `local_12`(or `relInf`) is then what `PushObjectCopy` should be placing onto the stack!

Therefore the structure `relInf` is foobar'ed and bears no resemblance to reality!

How can this be overcome???

I've included a zipped copy of the xml produced from the `Debug Function Decompilation` of this function [here](https://github.com/user-attachments/files/19526546/dragon_1080_0631.zip)

[^1]: `RELVALSLONG` is typedef'd to `long` displaying the values as decimal.

**Comment by Wall-AF** [comment]
FYI, replacing the `callfixup` body with
```
	SP = SP + 4;
	<loop>
	if (CX <= 0) goto <end>;
	SP = SP - 1;
	pvDst:2 = segment(SS,SP);
	pvSrc:2 = segment(DX,AX);
	*:1 pvDst = *:1 pvSrc;
	AX = AX + 1;
	CX = CX - 1;
	goto <loop>;
	<end>
```
as I said, loses the stack change and produces the below instead!
```
   pThis = (DgnWordAdaptLm1_t *)this;
   idVocab = (tmp10d0_0000_0xa_t *)pThis->?nID_0x8;
   idWord = pThis->field2_0x8;
   local_12.nNewRelevance_0x0 = GetRelHigh();
   lVar3 = GetRelMid();
   local_12.nShortNewRelevance_0x4._0_2_ = (undefined2)lVar3;
   local_12.nShortNewRelevance_0x4._2_2_ = (undefined2)((ulong)lVar3 >> 0x10);
   local_12.?_0x8._0_2_ = (tmp10d0_0000_0xa_t *)pThis->field4_0x18;
   local_12.?_0x8._2_2_ = (undefined2)((ulong)pThis->field4_0x18 >> 0x10);
   pDVar1 = &local_12;
   for (iVar2 = 0xc; iVar2 != 0; iVar2 += -1) {
      uStack_14 = (undefined1)pDVar1->nNewRelevance_0x0;
      pDVar1 = (Dgn1080_068c_0xc_t *)((int)&pDVar1->nNewRelevance_0x0 + 1);
   }
   relInf.nNewRelevance_0x0._1_1_ = uStack_13;
   relInf.nNewRelevance_0x0._0_1_ = uStack_14;
   relInf._2_4_ = local_12.nNewRelevance_0x0;
   relInf.nShortNewRelevance_0x4._2_2_ = (undefined2)local_12.nShortNewRelevance_0x4;
   relInf.?_0x8._0_2_ = (tmp10d0_0000_0xa_t *)local_12.nShortNewRelevance_0x4._2_2_;
   relInf.?_0x8._2_2_ = (tmp10d0_0000_0xa_t *)local_12.?_0x8;
   FUN_1080_0520((IDX_ONE_BASED)idVocab,idWord,relInf);
```

**Comment by Wall-AF** [comment]
Turns out this is the internal function called `F_SPUSH@`!

**Comment by Wall-AF** [comment]
> [@ghidracadabra](https://github.com/ghidracadabra) I'm unsure of how to attempt this! The function `PushObjectCopy` already exists with this assembly:
> 
> ```
>                              void*32 __cdecl16far PushObjectCopy(void*32 pvSrc, size_
>                                assume DS = 0x1210
>              void *32          DX:2,AX:2      <RETURN>
>              void *32          DX:2,AX:2      pvSrc
>              size_t            CX:2           nCX
> 
>    1000:0843 5b             0           POP        BX
>    1000:0844 07            -2           POP        ES
>    1000:0845 2b e1         -4           SUB        SP,CX
>    1000:0847 06           - ? -         PUSH       ES
>                              LAB_1000_0848                                   XREF[1]:     StackRollbackNear?:1000:0841(j)  
>    1000:0848 53           - ? -         PUSH       BX
>    1000:0849 57           - ? -         PUSH       DI
>    1000:084a 1e           - ? -         PUSH       DS
>    1000:084b 8b fc        - ? -         MOV        DI,SP
>    1000:084d 83 c7 08     - ? -         ADD        DI,0x8
>    1000:0850 8c d3        - ? -         MOV        BX,SS
>    1000:0852 8e c3        - ? -         MOV        ES,BX
>    1000:0854 8e da        - ? -         MOV        DS,DX
>    1000:0856 96           - ? -         XCHG       AX,SI
>    1000:0857 fc           - ? -         CLD
>    1000:0858 d1 e9        - ? -         SHR        CX,0x1
>    1000:085a f3 a5        - ? -         MOVSW.REP  ES:DI,DS:SI
>    1000:085c 13 c9        - ? -         ADC        CX,CX
>    1000:085e f3 a4        - ? -         MOVSB.REP  ES:DI,DS:SI
>    1000:0860 96           - ? -         XCHG       AX,SI
>    1000:0861 1f           - ? -         POP        DS
>    1000:0862 5f           - ? -         POP        DI
>    1000:0863 cb           - ? -         RETF
> ```
> 
> the issue is that when it is called, Ghidra understands that the return address is put on the stack and subsequently removed after the call, but, even though I've modified each stackDepth with the value of the parameter (in the register `CX`) it isn't interpreted correctly and doesn't realise that a duplicate of the object pointed to by `pvSrc` has been placed on the stack!
> 
> Am I misunderstanding what you're saying I should do??? If so, could you show a full e2e example please? Thanks.

After adding the _loop_ into the fixup body (see below) the C produced is better, but I'm still getting strange assignments to the copied structure and some weird stack references!
```
<callfixup name="F_SPUSH">
<target name="F_SPUSH@"/>
<pcode>
<body><![CDATA[
	SP = SP + 4 - CX;
	<loop>
	if (CX <= 0) goto <end>;
	SP = SP + 1;
	pvDst:2 = segment(SS,SP);
	pvSrc:2 = segment(DX,AX);
	*:1 pvDst = *:1 pvSrc;
	AX = AX + 1;
	CX = CX - 1;
	goto <loop>;
	<end>
]]></body>
</pcode>
</callfixup>
```
With the above fixup for `F_SPUSH@` (formally `PushObjectCopy`) Ghidra is producing
```

/* WARNING: Function: F_SPUSH@ replaced with injection: F_SPUSH */
/* WARNING: numops = 4
   segment(3) - segment - spc->getName() = 'ram'
    */

void __thiscallcdecl16far DgnWordAdaptLm1_t::doAction(DgnWordAdaptLm1_t *this)
{
   IDX_Vocab idVocab_00;
   IDX_Word idWord;
   Dgn1080_068c_0xc_t relInf;
   undefined1 *pDVar1;
   int iVar1;
   DgnWordAdaptLm1_t *pThis;
   undefined2 seg;
   undefined2 unaff_SS;
   undefined1 in_stack_0000ffe0;
   undefined5 in_stack_0000ffe1;
   undefined2 in_stack_0000ffe6;
   Dgn1080_068c_0xc_t local_12;
   IDX_Vocab idVocab;
   
   seg = (undefined2)((ulong)this >> 0x10);
   pThis = (DgnWordAdaptLm1_t *)this;
   idVocab_00 = pThis->idVocab_0x6;
   idWord = pThis->field2_0x8;
   local_12.nNewRelevance_0x0 = getRelHigh();
   local_12.nShortNewRelevance_0x4 = getRelHighShort();
   local_12.?_0x8 = pThis->field4_0x18;
   pDVar1 = (undefined1 *)&local_12;
   for (iVar1 = 0xc; iVar1 != 0; iVar1 += -1) {
       in_stack_0000ffe0 = *pDVar1;
       pDVar1 = pDVar1 + 1;
   }
   relInf._1_5_ = in_stack_0000ffe1;
   relInf.nNewRelevance_0x0._0_1_ = in_stack_0000ffe0;
   relInf.nShortNewRelevance_0x4._2_2_ = in_stack_0000ffe6;
   relInf.?_0x8._0_2_ = (tmp10d0_0000_0xa_t *)0x686;
   relInf.?_0x8._2_2_ = (char *)"Null pointer passed as utt. buffer" + 0x19;
   FUN_1080_0520(idVocab_00,idWord,relInf);
   FUN_1040_013e(idVocab_00);
   return;
}
```

HELP!

**Comment by Wall-AF** [comment]
@ghidracadabra can you assist?

**Comment by Wall-AF** [comment]
Turns out that the return address is being assigned to the last 4 bytes of the structure.  So in the example below, the assembly
```
    10e8:1181 c7 46 a4 06   0e2           MOV        word ptr SS:[BP + local_5e],0x6
             00
    10e8:1186 66 8b 46 ea   0e2           MOV        EAX,dword ptr SS:[BP + idState]
    10e8:118a 66 89 46 a6   0e2           MOV        dword ptr SS:[BP + local_5e.idState_0x2],EAX
    10e8:118e 8d 46 a4     0e2           LEA        AX,[BP + local_5e]
    10e8:1191 8c d2        0e2           MOV        DX,SS
    10e8:1193 b9 0a 00     0e2           MOV        CX,0xa
    10e8:1196 9a 43 08 00   0e2           CALLF      F_SPUSH@                                         void F_SPUSH@(void*32 pvSrc, size_t nC
             10
    10e8:119b 66 ff 76 e2   0ec           PUSH       dword ptr SS:[BP + prevNextState]
    10e8:119f 66 ff 76 e6   0f0           PUSH       dword ptr SS:[BP + prevIdState]
    10e8:11a3 56           0f4           PUSH       SI
    10e8:11a4 9a ec 03 58   0f6           CALLF      updateStateWordsStateTrans                       DgnVocab_0x4d_t*32 updateStateWordsSta
             10
    10e8:11a9 83 c4 14     0f6           ADD        SP,0x14
```
is producing
```
            local_5e.nTransOpCode_0x0 = (6 | _6);
            local_5e.idState_0x2 = idState;
            stateTrans.nTransOpCode_0x0._1_1_ = uVar7;
            stateTrans.nTransOpCode_0x0._0_1_ = uVar4;
            stateTrans.idState_0x2._0_2_ = npsz;
            stateTrans.idState_0x2._2_2_ = seg3;
            stateTrans.field2_0x6._0_1_ = 0x9b;
            stateTrans.field2_0x6._1_1_ = 0x11;
            stateTrans.field2_0x6._2_1_ = (char)unaff_CS;
            stateTrans.field2_0x6._3_1_ = uVar6;
            updateStateWordsStateTrans(idVocab,prevIdState,prevNextState,stateTrans);
```
where `local_5e` is the object pushed onto the stack of size 10 bytes, using the below fixup (the commented lines are things I've tried!)
```
<callfixup name="F_SPUSH">
<target name="F_SPUSH@"/>
<pcode>
<body><![CDATA[
	SP = SP + 4;
#	local pvSrc:4 = segment(DX,AX);
	SP = SP - CX;
#	local pvDst:4 = segment(SS,SP);
#	<loop>
#	if (CX <= 0) goto <end>;
#	*:1 pvDst = *:1 pvSrc;
#	pvDst = pvDst + 1;
#	pvSrc = pvSrc + 1;
#	CX = CX - 1;
#	goto <loop>;
#	<end>
#	SP = SP - 4;
]]></body>
</pcode>
</callfixup>
```
Note that in the extract below
```
            stateTrans.field2_0x6._0_1_ = 0x9b;
            stateTrans.field2_0x6._1_1_ = 0x11;
            stateTrans.field2_0x6._2_1_ = (char)unaff_CS;
            stateTrans.field2_0x6._3_1_ = uVar6;
```
`CS:119b` is the address of the instruction following the call (hence the return address)
```
    10e8:1196 9a 43 08 00   0e2           CALLF      F_SPUSH@                                         void F_SPUSH@(void*32 pvSrc, size_t nC
             10
    10e8:119b 66 ff 76 e2   0ec           PUSH       dword ptr SS:[BP + prevNextState]
```

**Comment by Wall-AF** [comment]
@ryanmkurtz please reopen this issue as there's still the issue that the return address is still being inserted into the object, as in https://github.com/NationalSecurityAgency/ghidra/issues/5702#issuecomment-3501972184.

**Comment by ryanmkurtz** [comment]
Would you mind creating a new issue for that part?
