### ISSUE TITLE
Custom `AbstractLibrarySupportLoader`-derived loaders can only load external libraries from the local filesystem

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#5709]
**Describe the bug**
Custom `AbstractLibrarySupportLoader`-loaders can only load external libraries from the local filesystem.

**To Reproduce**
1. Create a custom loader derived from `AbstractLibrarySupportLoader` that needs to load external libraries from a custom filesystem.
2. Load a file the custom loader can handle and for which external libraries are added to the external manager inside the loader's `load` method.
3. `resolveLibraryFile` gets called in the loader but the `GFileSystem` passed to the method is always the local one.

**Expected behavior**
There should be a way to provide `GFileSystem`s that can be searched into for library files.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Linux Arch 6.4.12-arch1-1 x86_64
 - Java Version: Temurin 17.0.8
 - Ghidra Version: b261137b4093bc2cd9bf1f809a6c002e1b6d8d75
 - Ghidra Origin: locally built

**Additional context**
From what I can see the ability to span `GFileSystem`s is more or less already there but `AbstractLibrarySupportLoader.getLocalLibrarySearchPaths` is marked as `private`.  If it would be made `protected` then derived classes could add their own `GFileSystem` instances to the `FileSystemSearchPath` list returned by said method.

**Comment by ryanmkurtz** [comment]
I very recently added the `GFileSystem` support that you are currently seeing.  The primary goal of that was to add the ability to search for libraries in a `GFileSystem` container file that resides on disk, typically by absolute path from within the file system.  That fit in nicely with the current GUI component that lets you select and reorder directories (and now container files) to search.  As you saw I also added the ability to load "local" libraries from within a `GFileSystem`.  I've also thought about being able to select "system" libraries that reside within a `GFileSystem`, but that GUI component would have to get updated to be able to take something more advanced, like an `FSRL`.  This isn't very user friendly, and I didn't have a use-case, so I didn't pursue it.

What is your particular use case for this feature?  Did you envision using the `Load System Libraries From Disk` GUI component with this?

**Comment by agatti** [comment]
In my specific case I have executable files that pack dynamic libraries in their own custom filesystem at the end of the data segment.  So at the moment I have:

- GFileSystem for ROM images, to load executables and system DLLs.
- Loader for executable files (header parsing, segment splitting, initial analysis, etc.)
- GFileSystem for executables, to access embedded resource files and linked DLLs.
- Loader for DLL files (header parsing, analysis, etc.)

I just tried the GUI component in the loader options (I assume that's what you're talking about) but I can not provide two levels of indirection there (ROM -> Executable), and when extracting the executable into its own file and adding that to the paths list it does not get recognised as a supported GFileSystem.  All loaders and filesystems are working correctly when importing files.  The end result is that `resolveLibraryFile` gets called twice with same the local filesystem that way.

I hope I'm setting the paths wrong myself, if not then the methods providing `FileSystemSearchPath` instances (both local and system) should be made protected then?

**Comment by agatti** [comment]
There might have been a misunderstanding here, my bad.  The extractor works fine, it's that when selecting the executable in the file dialog triggered by the add button in the "Load system libraries from disk" dialog from the loader options screen, the file I chose is not considered as a GFileSystem but as a regular file (or path in this case) instead.  The file chooser is titled "Select Directory or Filesystem", but I can't see the "filesystem" part in that.

That said, let's ignore the ROM container for the moment - the executable I'm opening has a series of embedded resources and a flat table of named files along with their internal offsets and length.  Parsing those structures and whatnot works just fine on my end, however the executable itself performs its version of `dlopen()` using the file name that is present from that table.  Those embedded DLL files, once extracted, can be handled by my own DLL loader (along with system DLL files that are present in the ROM filesystem), so I cannot just map those segments (it's an embedded real mode x86 system) and hope for the best - there's further parsing involved, which is done by the DLL loader.

**Comment by agatti** [comment]
I forgot, `dlopen()` is in this case an `INT` call that is handled elsewhere outside the binary too.

**Comment by ryanmkurtz** [comment]
Without debugging these files myself, it's very hard for me to say where it's going wrong.  Since you are running out of our repo, might I suggest making the method you mentioned `protected` yourself, and sharing how that your version of the method solved the issue for you?

**Comment by ryanmkurtz** [comment]
Also, if you extract all the files from all of your file systems and lay them down on disk as they are laid out in the GFileSystem, does your loader find them all?

**Comment by agatti** [comment]
I'm quite sure the GFileSystem instances work fine.  I've drawn a quick sketch on how things are laid out (maybe I should have started with that...).

![Screenshot_20230828_200342](https://github.com/NationalSecurityAgency/ghidra/assets/235740/43350b96-668e-41e2-b1d4-b14f9ccb3a2b)

The linked DLLs are not part of the ROM filesystem and are effectively hidden from its GFileSystem instance.  So in the general case I have the ROM GFileSystem that creates an Executable AbstractLibrarySupportLoader that creates an Executable GFileSystem that creates one or more DLL AbstractLibrarySupportLoader.  Even if you unpack the ROM filesystem, the problems I mentioned in the previous comments still remain, as when I add a DLL path I want the Executable GFileSystem, not its local filesystem location.

My idea when asking for the access modifier change in those Ghidra methods was to indeed provide a reference of the GFileSystem that handles the executable's own file table and, if present, the reference of the filesystem's parent which is in this case the ROM loader.

Thanks for your time so far, and hope this clarifies things a bit - let me know if I missed anything important!

**Comment by agatti** [comment]
Before trying with changing the access modifiers I dug a bit into why the filesystem is not recognised.

So, `AbstractLibrarySupportLoader.getSystemLibrarySearchPaths`   sees the new entry pointing to the executable binary but when `FileSystemInstanceManager.getFilesystemRefMountedAt` is called, its `filesystems` HashMap is empty and thus it falls back to local paths.

Assuming that had worked, I found another issue with this approach.  I thought that a workaround could be to forcibly add entries path in `LibrarySearchPathManager` from the loader but if I load binaries from the ROM filesystem it becomes a real mess (I cannot drill down into filesystems from the file chooser dialog).  Assuming that the ROM filesystem gets unpacked first and executables are loaded directly, I noticed that the paths there are for the whole Ghidra installation and not for the current project/session (not that project-wide entries would work all the time, due to potential name conflicts between the embedded filesystems and the ROM's system libraries directory contents).

I'm going to look into overriding the search path providers and see what happens then.

**Comment by dev747368** [comment]
What happens if you rearrange your filesystems a little so that your Executable Filesystem provides both the .exe and linked .dlls/resources?  You would have to prevent your loaders from triggering on the .exe in the ROM file system, giving the Executable filesystem a chance to open and then present the exe (again) along with all the dlls, but this time they are at the same nesting level and things should work(???).

**Comment by agatti** [comment]
That's something I can quickly try tomorrow and let you know how it goes.

However that solves half the problem, as if the user forgets to enable loading system libraries in the loader options (which in this case calling them system libraries is already confusing, system libraries come from ROM images...), or if they don't add a new path entry pointing to the same executable they're loading, or if they forget to clear old entries that are persisted in `LibrarySearchPathManager` from previous sessions/projects, this can turn into a real mess real quick.  Hopefully making the library location providers as protected and overriding them in my loader can work - still working on that.

This platform is "peculiar" to say the least, as I end up bumping into all sorts of edge cases - like #5466 for example, and many more I haven't yet filed bugs for :)

**Comment by ryanmkurtz** [comment]
I just wanted to add that there is nothing requiring your Loader to extend AbstractLibrarySupportLoader if you are finding the options it is providing to not be a great fit for your use case. It might be easier to implement your own library support instead of trying to force it to work with our current model. Just something to consider.

**Comment by ryanmkurtz** [comment]
> So, AbstractLibrarySupportLoader.getSystemLibrarySearchPaths sees the new entry pointing to the executable binary but when FileSystemInstanceManager.getFilesystemRefMountedAt is called, its filesystems HashMap is empty and thus it falls back to local paths.

So you are saying this bit of code in `getSystemLibrarySearchPaths()` is not finding your inner file system when extracted as its own file on disk?
https://github.com/NationalSecurityAgency/ghidra/blob/7cc135eb6bfabd166cbc23f7951dae09a7e03c39/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/AbstractLibrarySupportLoader.java#L1069-L1081

**Comment by ryanmkurtz** [comment]
Can you share all of this so I can poke at it?

**Comment by agatti** [comment]
Let me try to extract just this bit into its own extension and see if it still happens.  If so I'll remove most of the parsing code and attach that project here (consider that it's written in Kotlin, but it shouldn't really matter).

**Comment by ryanmkurtz** [comment]
Feel free to invite me to a private repo too.

**Comment by agatti** [comment]
@ryanmkurtz I think I sorted the missing filesystem issue out - I had a dependency that brought in an old version of the Kotlin runtime library so I had two runtimes in `lib/`.  Updating that dependency and re-downloading jars in `lib/` solved the issue.

For a bit I thought I became insane as I recreated the project elsewhere and it just worked.  I still have no real idea on why it failed in this way, I had no classpath errors or warnings in the console when running Ghidra.  I'm really sorry for having led both you and @dev747368 into this, if only `gradle clean` would have deleted downloaded libraries too... :(

Now I can properly focus on overriding the library path providers and see where it goes.

Again, sorry for all of this.

**Comment by ryanmkurtz** [comment]
Ok, sounds good.  Looking at the code, it is very unlikely we will make those methods `protected` because they are tightly coupled with the options.  

Going back to your original problem/request....are you mainly asking for the ability to specify search paths that are nested more than 1 level deep into filesystems?

**Comment by agatti** [comment]
I see.  Pity, because once I made those changes in Ghidra I solved the embedded libraries issue with this:

```kotlin
override fun getLocalLibrarySearchPaths(
    provider: ByteProvider,
    options: List<Option>,
    log: MessageLog,
    monitor: TaskMonitor
): List<FileSystemSearchPath> {
    val defaultPaths =
        super.getLocalLibrarySearchPaths(provider, options, log, monitor)
            as MutableList<FileSystemSearchPath>
    FileSystemService.getInstance().probeFileForFilesystem(provider.fsrl, monitor, null)?.let {
        reference ->
        defaultPaths.add(FileSystemSearchPath(reference, null))
    }
    return defaultPaths
}
```

I can live with the ROM filesystem being unpacked elsewhere and that local filesystem path being added by hand in the loader options screen (incidentally, you may want to consider having per-project/per-session system library paths too), but basically what I would like to have is a way to influence search paths from a subclass of the abstract library loader.  As you mention I can just write my own library support, but I'd end up copying the whole class anyway and hope no breaking changes happen in Ghidra's filesystem/loader APIs.  I'll do that if that's my only way out of this but it doesn't hurt trying to avoid that if possible :)

Putting my admittedly uncommon use case aside, I guess having customisable paths for system libraries and looking for local libraries only in the same directory as the binary in question may be a limit to other use cases?

**Comment by ryanmkurtz** [comment]
Do you always want to load all libraries or have the user pick and choose?

**Comment by ryanmkurtz** [comment]
> I see. Pity, because once I made those changes in Ghidra I solved the embedded libraries issue with this:

Fear not...I'm not opposed to changing our code to get this somehow working for you...but just making that 1 method `protected` is not a complete solution so I'd like to avoid it.

For example, we could add a `protected getOtherLibarySearchPaths()` method that by gets called but by default does nothing and isn't tied to any of the existing options.  You could then override that to add whatever you'd like.

**Comment by ryanmkurtz** [comment]
Im still not understanding why the System Search Path option isn't working for you (on your extracted exe).  It's effectively doing the same thing your change to `getLocalLibrarySearchPaths()` is doing.

**Comment by ryanmkurtz** [comment]
Make any progress @agatti?

**Comment by agatti** [comment]
@ryanmkurtz Apologies for the delay, I thought I already answered some days ago.

Anyway, regarding whether I need to load all libraries or only a few, theoretically users may want to pick and choose which ones they want to bring in but frankly I don't think loading all the libraries instead of a subset is going to be a limitation in my specific case.  Not sure for other use cases though.

For why I cannot use the system libraries loader options GUI entry screen, it's mostly due to its paths persistence across Ghidra runs:

Let's say that I have an executable A that contains libraries B, C and D: the user loads the file, selects the executable as its container in the system libraries path dialog, then in the same dialog picks the directory where the ROM image filesystem was unpacked and continues.  If the executable contains a replacement for a ROM library and Ghidra strictly follows the paths order shown in the dialog then the user won't see the proper library being loaded in.

Then assume that the user deletes the file from the files list or closes the project or restarts Ghidra, and tries with another executable, B, which by accident contains a library also called D.  Depending on whether they add the executable or not in the system libraries path, then who knows what gets loaded.

Moreover, if due to an error in my code or if the executable is corrupted in just the wrong way, a library may be declared but my filesystem loader code might not be able to pick it up.  I would like to know and handle these cases, which may or may not trigger due to an "improper" system libraries path load order.

One may argue that it's an user error in all cases, but I as a user would expect *system* libraries being what is always available to all binaries regardless the executable/DLL I'm loading in for a specific platform, not what is effectively transient from that point of view.

Plus, still thinking as the user here, why do I have to select the same file twice?  Doesn't the loader already know what's inside the executable I chose? :)

**Comment by agatti** [comment]
I also thought of another potential issue.  Let's say that the user puts an executable into the system path and that executable contains a library called `USER32.DLL` or `libz.so` (unlikely, I know).  Once done with the file, in the same project, loads a Win32/Linux binary that links against `USER32.DLL` or `libz.so`.  Since paths are persisted the my loader could be called and will provide an useless file to the user, and the user won't figure it out until it starts digging into the listing as there's no summary screen with the files imported and their formats (similar to what the batch filesystem loader does), as far as I recall.

**Comment by ryanmkurtz** [comment]
Have you considered not even using the GFileSystem and library features and just having 1 Loader that loads everything into 1 program?  This will work if none of the addresses overlap in the various exe's and libraries.  I've done this with a some other formats, and it works quite well as long as the entire thing isn't too massive (or analysis could take a very long time).  I use new folders in the Program Tree to keep all the different components organized.

Aside from that idea, could you please summarize the feature requests/bug fixes you'd like to see put in place?  I must admit that I have gotten lost in all the different back and forth, and am unsure what units of work this ticket now represents.

**Comment by agatti** [comment]
Maybe that could work, although I'd have to make a few modifications to the loader first to see if a fix-up pass is actually possible as there may be overlaps in both .text and .data segments.

For the summary, what I'd like to see is a way to give AbstractLibrarySupportLoader a list of pre-resolved library files (as in, GFile instances or something similar) that are automatically imported once the main Program instance is created.  Libraries added that way should be processed like any other libraries but when it comes to path resolution should be independent from the default library/system paths, and - optionally - take precedence over system libraries with the same name but not over local library files.

Instead of an overridable method in AbstractLibrarySupportLoader I also thought on whether an implementation of ExternalManager.addExternalLibrary that would accept GFile instances could make sense but probably has some issues with regard to reference counts and files kept open.

**Comment by ryanmkurtz** [comment]
Sorry for the delay.

> Instead of an overridable method in AbstractLibrarySupportLoader I also thought on whether an implementation of ExternalManager.addExternalLibrary that would accept GFile instances could make sense but probably has some issues with regard to reference counts and files kept open.

The `ExternalManager` deals more with already-imported `Program`s, so that probably isn't the right place for interfacing with the `GFileSystem` stuff.

I think the right thing to do here is to provide an overridable method independent of the local and system search paths, and have it called before the local and system lookups.  If we did this, could you just disable the `Load Local...` option from your loader and "do your own thing" with this new method to get the results you want?

**Comment by agatti** [comment]
Yep, I guess that would work!

**Comment by agatti** [comment]
@ryanmkurtz thanks for the changes! Not sure if it's a Kotlin limitation but shouldn't `AbstractLibrarySupportLoader.FileSystemSearchPath` be marked as `protected` to be made available to derived classes?

**Comment by ryanmkurtz** [comment]
I fixed it, thanks!
