### ISSUE TITLE
Taskbar groups/naming

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#5713]
Not sure how this works honestly, or for differing OS.

If I have 5 CodeBrowsers open.  Win10 will have a group for ghidra. One front end and 5 CodBrowsers.  With hovering/preview you can only see the word CodeBrowser, would it be possible to just show the filename instead?

Hovering over each one by one will eventually popup the full process name, and of course can just cycle through them with alt tab or clicking.  Just wondering about on the initial click of the taskbar

**Comment by dev747368** [comment]
With win11 I get this when I hover over the task bar item for ghidra:
![Screenshot 2023-08-28 223017](https://github.com/NationalSecurityAgency/ghidra/assets/48332326/f38ae0e7-fab4-4ed6-b6fb-96d45e1cec41)

These platform specific things are a pain.  After fighting with Ubuntu's taskbar just to try to get it show anything in the icon, I dunno.

**Comment by mumbel** [comment]
I was seeing similar for win10.... you basically get the CodeBrowser and project text unless you hover.   Worth asking about at least, but figured there's not much that could be done.   I'm fine closing this issue; it made me look around and I found out the hover name pop-up as I was creating the issue, so workarounds def exist

**Comment by ryanmkurtz** [comment]
I just tried this on Windows 10, and it's showing the same thing that @dev747368 is showing.  It's just the Window title (i.e., `CodeBrowser(2): Test:/test.exe`.

I am not seeing any entries that just show the word `CodeBrowser`.  Maybe your previews are too small and the rest is getting chopped off?

**Comment by mumbel** [comment]
You have multiple code browsers open?

I have 'CodeBro...' currently.  Even with your examples add in a project name and any sort of directory layout, they'll all be the same string at first glance 



> Maybe your previews are too small and the rest is getting chopped of?

Mine in particular or windows... That is the issue I'm reporting, I as a user didn't do anything (confused by the question).

**Comment by ryanmkurtz** [comment]
The preview on Windows 10 is just showing the title of the Windows for me...i.e., `CodeBrowser(2): Test:/test.exe`.  I am assuming this is the case for everyone on Windows 10, but if you are seeing a substring of that, I am wondering if your resolution or something is causing your preview text to be truncated.

**Comment by ryanmkurtz** [comment]
I guess I'll close this.  It doesn't sound like there is much we can do anyway.
