### ISSUE TITLE
Structure Editor: searching for the "default" field name *should* find the exact field

### ISSUE THREAD

**Issue by slippycheeze** [NationalSecurityAgency/ghidra#5715]
**Is your feature request related to a problem? Please describe.**
In the "Structure Editor", pasting a **default** field name into the "Search:" field and hitting return will not match anything.  This makes copy/paste searching frustrating, and violates my expectations of "logical" behaviour for field names.

By "default" field name I mean what you get from `DataTypeComponent.getDefaultFieldName()`, and which is used when `DataTypeComponent.getFieldName() == null`.  

Concrete example: `field207229_0x34e90`[^1] can't be found; definition is:
<img width="481" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/306753/7358604c-4f8b-405f-b30f-6a6c61dbe1a6">

**Describe the solution you'd like**
1. Match the value is `Search:` against `DataTypeComponent.getDefaultFieldName()` if `.getFieldName()` is `null`.
2. ideally, make me very happy, and match against it **even if** `.getFieldName()` is **not** null, so that searching for `field207229_0x34e90` will always find a field at that ordinal and offset.
  - in this case, I expect that:
    - a "defined field", named or not, will be checked.  eg: `0x3297d  undefined8` and `0x34e8c uint foo`
    - an "undefined" and "unnamed" slot will be checked.  eg: `0x34e87  undefined`
    - a byte *inside* a defined field will **not** be checked.  eg:  `0x3297f, inside 0x3297d undefined8` is *not* matched.
4. be smart about it, and if the offset is present, match *only* the offset, so that `field207229_0x34e90` will match `field20000_0x34e90` after I define a bunch of earlier members that fill out "undefined" slots.
5. *if* the search text was erased or replaced, always jump to an exact match first, no matter where the "current" selected line is, so that `0x34e` will go to offset `0x34e` first, and only after that go to 0x340, etc, etc.

[^1]: yes, that is a real-world field I just searched for in an object 0x35D08 bytes large...  software developers, boy, I tell you, they do some unbelievable stuff sometimes.  it is mostly "first party" data, too, not that much of it is sub-objects embedded.

**Comment by dragonmacher** [comment]
I'm taking a peek at this.  I can see the code has a few issues.  Generally, for filtering or searching in tables we use a WYSIWYG approach.      Would searching for the text as it is rendered satisfy your use case(s)?

If not, can you elaborate?
