### ISSUE TITLE
the C++ demangler should "back-translate" standard STL type aliases like `std::string` from their raw types.

### ISSUE THREAD

**Issue by slippycheeze** [NationalSecurityAgency/ghidra#5725]
**Is your feature request related to a problem? Please describe.**
The "internal" name of some standard-defined STL types is painfully cumbersome, and gets in the way of human understanding.  Concretely, `std::string`, for example:

```c++
// ?ForceDefaultMeshFile@Actor@GAME@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
public: void __cdecl GAME::Actor::ForceDefaultMeshFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64) __ptr64
// this demangling courtesy demangler.com, because I already *did* what I'm asking manually in my project.
```

**Describe the solution you'd like**
`std::string` is defined to *always* be `std::basic_string<char,struct std::char_trains<char>,class std::allocator<char>>`.  unless someone kidnaps the C++ committee, it can't *ever* be anything else.

The C++ demangler should "know" these standardized identities, and instead provide the "right" translation:
```c++
public: void __cdecl GAME::Actor::ForceDefaultMeshFile(class std::string const & __ptr64) __ptr64
```

**Describe alternatives you've considered**
I got to the point I was about to write a script for this, and I realised I should instead ask for it to be implemented in the upstream demangler, or some related analyser: it *may* not be appropriate to do universally, but I can't see a reason why.  

I'll certainly automate this myself in a script if that is what it takes, though. :)

**Additional context**
I'm specifically, and only, thinking of aliases that are defined in the C++ STL specification, and really, mostly only care about the `std::basic_*` aliases in `<string>` and `<stream>`, plus their closely related headers.

**Comment by dragonmacher** [comment]
Sounds like a great idea.   Is there any source to help figure out 'standard' replaceable types?   It seems easy enough to support a file of known mappings.

**Comment by slippycheeze** [comment]
> Is there any source to help figure out 'standard' replaceable types?

I use https://en.cppreference.com/ for this, in the sense that it is my go-to reference for what the C++ standard says.  I don't know of any instant summary of the "pre-defined variants on template types" there, or elsewhere.

The concrete list I was thinking of is thankfully short, though, and I'm pretty sure the C++ committee try and avoid extending it too much over time. :)

- `std::basic_string` and `std::basic_string_view` shorthands: https://en.cppreference.com/w/cpp/string
	- `string`, `wstring`, `u8string`, `u16string`, and `u32string`, and their `string_view` pairs.
-  `<iostream>` and friends: https://en.cppreference.com/w/cpp/io
	- pretty much all the `*_base` templates here: `ios`, `{i,o,io}stream`, etc, have a well known alias for `char` and `wchar` 
- https://en.cppreference.com/w/cpp/regex/basic_regex

...and that'd be it, really.  the similarity of all of them is they are almost exclusively used on `char` and `wchar`, and rarely much else.

**Comment by XVilka** [comment]
In Rizin we use the same approach: https://github.com/rizinorg/rz-libdemangle
Issues that pointing out to some deficiency are welcome.
See this part: https://github.com/rizinorg/rz-libdemangle/blob/main/src/cxx.c#L32

**Comment by slippycheeze** [comment]
> Issues that pointing out to some deficiency are welcome.

https://github.com/rizinorg/rz-libdemangle/issues/55 — `std::regex` wasn't there, I think, but otherwise this is pretty much exactly what I had in mind.

**Comment by astrelsky** [comment]
> > Is there any source to help figure out 'standard' replaceable types?
> 
> I use https://en.cppreference.com/ for this, in the sense that it is my go-to reference for what the C++ standard says.  I don't know of any instant summary of the "pre-defined variants on template types" there, or elsewhere.
> 
> The concrete list I was thinking of is thankfully short, though, and I'm pretty sure the C++ committee try and avoid extending it too much over time. :)
> 
> - `std::basic_string` and `std::basic_string_view` shorthands: https://en.cppreference.com/w/cpp/string
> 	- `string`, `wstring`, `u8string`, `u16string`, and `u32string`, and their `string_view` pairs.
> -  `<iostream>` and friends: https://en.cppreference.com/w/cpp/io
> 	- pretty much all the `*_base` templates here: `ios`, `{i,o,io}stream`, etc, have a well known alias for `char` and `wchar` 
> - https://en.cppreference.com/w/cpp/regex/basic_regex
> 
> ...and that'd be it, really.  the similarity of all of them is they are almost exclusively used on `char` and `wchar`, and rarely much else.

I think you can just search for `std::basic_*`  to find everything. There are a few missing like `std::map` for example.
