### ISSUE TITLE
multi-line comment / notes / description associated with StructureDataType (and perhaps any DataType)

### ISSUE THREAD

**Issue by slippycheeze** [NationalSecurityAgency/ghidra#5736]
**Is your feature request related to a problem? Please describe.**
in my experience the data **structures** of a program are much more important than anything else to understanding the nature of it; certainly, during RE of stuff I've multiple times found I want to write some commentary about a data structure to describe the semantics of its use — until the sum of those semantics from different places finally tells me *what* it is a model for.

I can write endless commentary against a function, if I wish.  OTOH, I get only one single line for `UnknownClass015`, which I wanted to annotate with the list of "possible classes" based on a COMDAT shared function it included in the vftable.    I can't tell (yet) which of those it is, but it is certainly one of them, or derived from one of them.

**Describe the solution you'd like**
I'd like the "Description" of a `StructureDataType` to be comparable to the "Plate comment" of a function: able to support multi-line comments, and so forth.  

It'd be nice, but not essential, if the same were true of comments on DataTypeComponent members, so that they could have more description than is currently permitted.

(and if I was dreaming, I'd like to attach some extra structured data to that, so I could track `size` in terms of maturity: `undefined`, `inferred`, `from new/construct`, `locked`.  those being the degree of certainly I have about the size of a partially defined structure; right now they just text somewhere in that single line description.)

**Describe alternatives you've considered**
right now I dump large comments somewhere else like, eg, the constructor function plate comment, for the case where I wanted that list of possible "ISA" relationships.  and then add a "pointer" comment to the description, like "see constructor for possible class identities."

**Comment by dragonmacher** [comment]
We'd like some more info on how you would use this. 

Currently, you can  set and retrieve multi-line text from a structure by using `Composite.setDescription()` and `getDescription()`.  

The Listing will show multi-line text *for structure members* as EOL comments.     Would you like to see the structure's description appear in the Listing?   

The structure editor will remove newlines when displaying the comment.  It also does not allow you to enter multi-line text.    I'm assuming this is the primary request of this ticket, to be able to edit and view multi-line text inside of the structure editor.  Then, I'm assuming you would also like the ability to see structures's description in the listing, as you mentioned, similar to a plate comment.

Also worth mentioning, while you can see the structure member comments in the EOL field,  editing the comment does not update the structure, but instead creates a new EOL comment in the database.   This is not made clear to the user.
