### ISSUE TITLE
Structure Order field "TAB" order is very bad, and encourages breaking structure definitions :(

### ISSUE THREAD

**Issue by slippycheeze** [NationalSecurityAgency/ghidra#5738]
**Describe the bug**  (and **To Reproduce** steps)
In the structure editor "meta" section, the "TAB" order[^1] is bad on a "default" structure
1. (starting from manually putting focus in) `Name`
2. `align > default` (or whatever the current setting is; if manually set, it'll just direct there.)
3. `align > <manually set> > manual text field with 0x1`
4. `pack <checkbox>`
5. `Description`
6. `Category`, which is not editable or interactable
7. `Size`
8. `Alignment`, which is just the display field, like Category
9. *nowhere*: cursor is now stuck in the `Alignment` field, never to move again.

Normally this'd be an inconvenience, but in this case there are two destructive things that can be done "accidentally" simply by activating them:

1. If `align` for the Structure is "default", tabbing through will override it to an explicit `0x1`, which *will* destructively change layout on a packed structure, and
2. `pack <checkbox>`, which toggles if you hit `spacebar`; turning this on and off is **NOT** the same as never turning it on: it'll remove `undefined` bytes all over the place, then restore just enough of them to meet packing requirements.

root cause of this bug report: managing to tab into `pack <checkbox>` and type in what I wanted in the description field, which included spaces between words....  zap, structure modified so I could only discard all my changes and redo them.

**To Reproduce**
Folded into the description, because they were inseparable.

**Expected behavior**
The "TAB" order *should* be:
- the table of components
- `Search`, IMO, but YMMV, see 4.
1. `Name`
2. `Description`
4. `Size`
5. IMO, **stop here**, and loop back to either `Search:` or `Name`.
	- I'd go with "search" myself, but I can see good arguments either way.
	- ...or to the table of components.  it make sense enough, since you can edit it via keyboard, so ... maybe it'd be the right choice; if so, it ideally should "TAB" directly to `search` without navigating internally to the table.
6. `align`, but *never* change the active option on TAB, just select current control
7. `pack <checkbox>`
8. `pack <nested controls>`, which also should never *change* the option simply by hitting TAB
9. loop back, as with 4.

**Environment (please complete the following information):**
- OS: Windows 11 22H2 (OS Build 22621.2070) x64
- Java Version: temurin-jdk 20.0.2
- Ghidra Version: 10.3.2 PUBLIC 2023-Jul-11 1640 EDT
- Ghidra Origin: official github release, installed via scoop

**Additional context**
I have not checked other parts of the code for their keyboard navigation "correctness", but given the somewhtat quirky behaviour of editing text fields in the structure and enum editor text fields, I suspect this is just the "place I noticed": the problem is present elsewhere, just not in as destructive / annoying a fashion. :)

[^1]: as in, the order that controls get focus when I hit the "TAB" key to move to the next control.

**Comment by Wall-AF** [comment]
Also, pressing Ctrl+Z (undo) undoes changes outside of those attempted in the structure editor.  (Easy to loose something previously changed!)
