### ISSUE TITLE
"Add to program" only allows importing raw binary

### ISSUE THREAD

**Issue by rollsch** [NationalSecurityAgency/ghidra#5739]
**Describe the bug**
"Add to program" only allows importing raw binary despite the help button saying Intel Hex and many other formats are allowed

**To Reproduce**
Open an infineon tricore HEX file
analyze it
Click file -> add to program
Locate an intel hex file (eg .HEX or .H32 extension)
Format is preselected as "raw binary" and cannot be changed

**Expected behavior**
Hex and the formats listed in the supported formats window are allowed to be imported.
If possible the base address and length are populated. If the file is non noncontiguous it handles
this correctly or warns the user and allows you to handle it. 

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/1109554/26eea19a-f31c-466e-95a7-f138bce69b86)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/1109554/f233f863-31f5-45ee-99d8-5dc3aea5f253)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/1109554/e9b922c8-2912-4016-a32e-090a3cd1f9e0)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 11.0
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub distro

**Additional context**
How can I import an intel hex with several memory segments into my program without writing a script to do so? If I have a single flat hex file I can convert it to binary, import it, manually enter the address and length however sometimes I have a hex file with a large number of segments that are noncontiguous, doing this manually is very painful.

**Comment by ryanmkurtz** [comment]
I am having trouble reproducing this with a simple Intel hex file that I got [from Wikipedia](https://en.wikipedia.org/wiki/Intel_HEX):
```
:10010000214601360121470136007EFE09D2190140
:100110002146017E17C20001FF5F16002148011928
:10012000194E79234623965778239EDA3F01B2CAA7
:100130003F0156702B5E712B722B732146013421C7
:00000001FF
```
For the hex file that is not working with `Add To Program`, does that same exact file get **imported** correctly as an Intel hex file?  If so, can you attach it so i can debug?

**Comment by ryanmkurtz** [comment]
Sorry, I knew that was confusing when I wrote it. 

I can Add To Program with these 2 hex files just fine.  I Imported the first one, then Added To Program with the 2nd one.  Both processes allowed me to choose "Intel Hex" as the Format.

**Comment by rollsch** [comment]
I'm not sure. If you load a really big hex file as your base, analyse it. Here is a large hex file you could try this file, analysing it, then importing the file above as that is essentially what I did. Select Tricore 298 when analysing. Then do a second pass with aggressive instruction finder.

[tc1791 hex.zip](https://github.com/NationalSecurityAgency/ghidra/files/12571912/tc1791.hex.zip)

**Comment by ryanmkurtz** [comment]
Sorry but I still cannot reproduce your original problem.  I can select `Intel Hex` on every file you've provided when doing `Add To Program`.  I cannot reproduce your issue of only getting `Raw Binary` from the drop down.

**Comment by rollsch** [comment]
I guess it's a made up problem then. Let's close it out.

**Comment by rollsch** [comment]
Lol

**Comment by ryanmkurtz** [comment]
Apologies again...were you not asking me to close it out because I couldn't reproduce it?

**Comment by rollsch** [comment]
You don't seem interested in reproducing it so not much point continuing.

**Comment by ryanmkurtz** [comment]
If I was not interested in reproducing it, I would not be trying to reproduce it with the files you are kindly providing me.  I understand that it is probably frustrating that I am thus far unable to reproduce it, but I was happily willing to continue going back and forth to try to figure it out.  Apologies for not processing your sarcasm when you said to close the ticket.  If you would like to continue, please follow these steps:

1. Download Ghidra 10.3.3 from [here](https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.3_build/ghidra_10.3.3_PUBLIC_20230829.zip)
2. Import your file with Ghidra 10.3.3.  Post a screen shot of your import dialog window, and send me the md5 of the file you imported.  If you haven't attached that file to this ticket yet, please do so.
3. Open this newly imported program in the CodeBrowser, and do an Add To Program.   Again, post a screen shot of this Add To Program dialog (ideally showing Intel Hex is not available from the drop down), and send me the md5 of the file you Added To Program.  If you haven't attached that file to this ticket yet, please do so.

**Comment by rollsch** [comment]
Apologies if we unprofessional on my part. Would a screen recording be more useful? I'm happy to share all the files in working with if we remove the links after this discussion.

**Comment by ryanmkurtz** [comment]
Yes, a screen recording would definitely be very useful.

**Comment by rollsch** [comment]
Ok ill do my best to get you one today. If there anyway I can send it to you privately?

**Comment by ryanmkurtz** [comment]
Yes, you can send it to `ryanmkurtz.git@gmail.com`

**Comment by rollsch** [comment]
Thank you. Will be later today.

**Comment by rollsch** [comment]
It seems resaving the project, then re-opening and the problem is gone.

All I can think is it was mid analysis. Or I had multiple instances open perhaps, maybe the hex file was locked by another program.

Either way, I cannot reproduce it myself anymore either now.

So now we can close it out!

**Comment by ryanmkurtz** [comment]
Sounds good!
