### ISSUE TITLE
Decompile functions after a HeadlessAnalyze run

### ISSUE THREAD

**Issue by angriestalien** [NationalSecurityAgency/ghidra#574]
After an analysis I want to iterate through the functions and export each function as C code to a file. This is an example function I placed in DecompileResults. 
```
private void exportToC() {
		try {
			ClangTokenGroup grp = this.getCCodeMarkup();
			if(grp != null) {
				File tmpFile = new File("~/ctmp" + 
						"/" + this.function.getName() + ".c");
				PrintWriter writer = new PrintWriter(new FileOutputStream(tmpFile));
				PrettyPrinter printer = new PrettyPrinter(this.function, grp);
				DecompiledFunction decompFunc = printer.print(true);
				writer.write(decompFunc.getC());
				writer.close();
			}
		
		}
		catch (IOException e) {
			System.out.println(e.getStackTrace());
		}
    }
```

    

I need to know how to iterate through the functions and create a DecompileResults that calls the exportToC function.

Eventually, I would like an elegant solution but currently I am calling the exportToC function in the DecompilerResults.parseRawString function.
```
docroot = ClangXML.buildClangTree(parser, hfunc);
if (docroot == null) {
    errMsg = "Unable to parse C (xml)";
} 
this.exportToC();
```

I'm looking to do something like this

```
DecompInterface ifc = new DecompInterface();
for(var func : program.getFunctionManager().getFunctions(true)) {
        ifc.decompileFunction(func, 100000, null);
}
```
decompileFunction will eventually instantiate DecompileResults and call the parseRawString and  exportToC function.

Since the HeadlessAnalyze is in Features Base and Features Decompiler references Features Base, how might I create a task to iterate the analyzed functions after analyzing the program?

Any tips would be greatly appreciated.

I did look at #376. However, I want to hook the export after a HeadlessAnalyze run. Right after analyzeProgram call.

```
doSave = analyzeProgram(file.getAbsolutePath(), program) && !options.readOnly;
```

**Comment by dragonmacher** [comment]
There is a script that will do what you are discussing, the somewhat poorly named "Decompile".   See:

    'Ghidra/Features/Decompiler/ghidra_scripts/Decompile.java'

**Comment by angriestalien** [comment]
How would I add script options and where are the script options documented? The script returns before exporting any C.

```
if (!state.displayParameterGatherer("Script Options")) {
     return;
}
```

Will this export every function in the program? How can I filter based on function name?

**Comment by dragonmacher** [comment]
The Headless Analyzer documentation is in the installation:

    '<install dir>/support/support/analyzeHeadlessREADME.html'

The aforementioned Decompile script will export every function.  You can read the source code of that script to explore how it uses the `CppExporter` to export functions.   Specifically, in the `export` method, you can see that it uses the `ParallelDecompiler` to process all of the functions.   In order for you to add filtering to this process, you will have to write something similar to what the `CppExporter` does.

**Comment by dragonmacher** [comment]
> Since the HeadlessAnalyze is in Features Base and Features Decompiler references Features Base, how might I create a task to iterate the analyzed functions after analyzing the program?

When you write a script your classpath will include all known modules.  Thus, your script can access not only `Features Base`, but 'Features Decompiler` as well.

**Comment by angriestalien** [comment]
I was able to update the Decompile.java script to create c files.

In total the cat program exported 34 files.

Update the run function to:

```
        @Override
	public void run() throws Exception {
		var program = this.getCurrentProgram();
		DecompInterface ifc = new DecompInterface();
		ifc.openProgram(program);
		for(var func : program.getFunctionManager().getFunctions(true)) {
		        ifc.decompileFunction(func, 100000, null);
		}
	}
```

Add the exportToC function and call the exportToC function described in the above post. 

Debug configuration is:
```
ghidra.app.util.headless.AnalyzeHeadless /Users/username/ghidraTest newProject4 -import /Users/username/binaries/cat -postScript Decompile.java entry
```

**Comment by angriestalien** [comment]
Looking at it a little more, you can pull the exportToC function into Decompile.c.

```

	private void exportToC(DecompileResults results ) {
		try {
			ClangTokenGroup grp = results.getCCodeMarkup();
			if(grp != null) {
				File tmpFile = new File("Users/username/ctmp" + 
						"/" + results.getFunction().getName() + ".c");
				PrintWriter writer = new PrintWriter(new FileOutputStream(tmpFile));
				PrettyPrinter printer = new PrettyPrinter(results.getFunction(), grp);
				DecompiledFunction decompFunc = printer.print(true);
				writer.write(decompFunc.getC());
				writer.close();
			}
		}
		catch (IOException e) {
			System.out.println(e.getStackTrace());
		}
	}
	
	@Override
	public void run() throws Exception {
		var program = this.getCurrentProgram();
		DecompInterface ifc = new DecompInterface();
		ifc.openProgram(program);
		for(var func : program.getFunctionManager().getFunctions(true)) {
		        var results = ifc.decompileFunction(func, 100000, null);
		        exportToC(results);
		}
	}
```

**Comment by pabx06** [comment]
i had to export some c code/header:
not headless mode script: 

```
Function fun = getFunctionContaining(currentAddress);
AddressSetView adView = new AddressSet();
adView = adView.union(fun.getBody());
File choosed = askFile("Choose output Result", "choose");
CppExporter exporter = new CppExporter(true, true, true, false, null);
exporter.export(choosed, getCurrentProgram(), adView, getMonitor());
```

also you could use 
```
Set<Function> set = fun.getCalledFunctions(getMonitor());
```
to get needed functions recursively 

However didn't figure out the API on how to get global variable to be exported ie: data from ".rodata".
If some had it figured out.

**Comment by gemesa** [comment]
> There is a script that will do what you are discussing, the somewhat poorly named "Decompile". See:
> 
> ```
> 'Ghidra/Features/Decompiler/ghidra_scripts/Decompile.java'
> ```
> 
> As for running the script after analysis is finished, use the '-postScript' option

Does anyone know what happened to this script? Cant find it in new (11.2.1) releases.

**Comment by ryanmkurtz** [comment]
Looks like it was deleted as part of the solution to #1982 (82164402784b4b8c49033eb63a18d781be087dd0).
