### ISSUE TITLE
With two binaries open: "goto previous location" location should be kept separate for the two binaries

### ISSUE THREAD

**Issue by karsten-burger** [NationalSecurityAgency/ghidra#5750]
This is probably easy to fix:

When I have loaded two different binaries in the code browser, they show as two tabs.

I often switch between the two, since i do a function comparison manually, since the two functions are very large (about 1400 lines of decompiled code) and have many differences. Also "Function Comparison" has absolutely no help except showing them side-by-side, as compared with a Diff Tool like e.g. Meld.

But if I use Alt-left, the location will often be in the other binary (focus switched to other tab), and this is really confusing.

I would like that the previous location history is kept separate for the two tabs / binaries: if I go back then I go back only as I moved around in the current binary.

**Comment by slippycheeze** [comment]
FWIW, I'm torn: the "do what I mean" mind reading version would **sometimes** cross between binaries, and sometimes stay in the current binary.   In the current subject of my work, since the two DLL and one EXE export global variables and member functions to each other, I often cross over during a single pass through the code.

So, I've definitely wished the same thing sometimes, but other times, not so much.  I think now I'd probably open two separate code browsers and switch between them if the two programs were sufficiently unrelated — which does use separate history, I believe.

**Comment by dragonmacher** [comment]
We could provide a tool option that would restrict navigation to the focused binary.

In the meantime, admittedly less convenient, you can use the back button's drop-down  menu to pick the location you wish to go to.  The drop down indicates which binary contains the location.

**Comment by dragonmacher** [comment]
> I think now I'd probably open two separate code browsers and switch between them if the two programs were sufficiently unrelated — which does use separate history, I believe.

Also a good workaround.

**Comment by ryanmkurtz** [comment]
> Thank you. Should I close the issue?

Yes, please...thanks!

**Comment by dragonmacher** [comment]
> Yes, opening two Ghidra instances and thus separate browsers works. 

This may just be a semantic issue, but just in case, I will point out that you can run 2 different Code Browser tools within one running instance of Ghidra.   To do so, launch Ghidra and then open your program by double-clicking or dragging onto the Code Browser tool as normal.   Then, you can open a second tool by dragging the desired binary onto the Code Browser button at the top of the Front End (not the Code Browser tool running at the bottom of the Front End).

**Comment by dragonmacher** [comment]
If you just want to get `a'` back into the original project, then the simplest thing is to export and re-import into the original project, overwriting the original file.    If you have changes to `a` and `a'`, and you want to keep the changes in `a` and add the  changes from `a'`, then you should use the diff tool to do this.   You can still export/re-import `a'` into the original project.  Then,  open `a` in your Code Browser, launch the diff tool from the Listing's toolbar (the 'Open Diff View' action), and pick `a'`.

Once the 2 binaries are in the diff tool, you pull over changes as desired.

**Comment by dragonmacher** [comment]
Also, you don't need to export/re-import.   You should be able to pull programs across projects from the Front End using the menu `Project -> View Project...`.   That action will let you view multiple projects at once.   You can drag from a 'viewed project' into your current project.
