### ISSUE TITLE
DataPlugin should set stackPointers to false

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#5754]
**Describe the bug**
When setting the DataType via ChooseDataTypeAction (Data->Choose Data Type, or 'T'), the stackPointers value passed to CreateDataCmd() in DataPlugin.createDataAtLocation() is true.  I think that this leads to unexpected behavior and would be more predictable if it was set to false.

**To Reproduce**
Existing DataType is "pointer".

If I decide that it isn't really a pointer, but should be an int instead, I go to Data->Choose Data Type, type in "int", click OK, and the result is "int *".

Even if I decide to refine it to be a pointer to an int, so I enter "int *", I get "int **" instead.

If I discover that this pointer is actually a member of a structure that starts at that address, select out 12 bytes for the structure to sit in, then choose the datatype to be my 12-byte structure, I end up with three pointers to my structure.

**Expected behavior**
When I specify the datatype I want there, then I would expect that to be the datatype created.  It seems unexpected to get a pointer to the chosen DataType instead.

**Environment (please complete the following information):**
This is in Ghidra 10.1.5, but it has been a longstanding behavior.

**Additional context**
If there is a reason why the existing behavior is useful in some way, then perhaps a tool option could be used to set the behavior.

**Comment by ghidra1** [comment]
I did identify an error when choosing a datatype to apply on a selection (`DataPlugin.createDataForSelection` when instantiating `CreateDataBackgroundCmd`), however I do not see an issue for the `createDataAtLocation` case which does forward `stackPointers` param passed from `ChooseDataTypeAction`.  There are other cases (e.g., drag-n-drop) which do set `stackPointers=true`.
