### ISSUE TITLE
Debugging with GDB on Windows Host

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#5755]
I'm attempting to debug a remote target with a gdb stub from Windows. I've been able to use Cygwin's `gdb` to accomplish this on its own (within a Cygwin terminal), and have no issues using it directly this way, but wanted to see if I could get Ghidra's interface up. I keep getting:

```
ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB: Could not detect GDB's interpreter mode.
Try C:\cygwin64\bin\bash.exe -i mi2
```

The GDB launch command is: `C:\\cygwin64\\bin\\bash.exe --login -c '/usr/bin/gdb'`, which I've verified launches GDB as expected in a Windows cmd shell, and I'm able to connect to the GDB stub and debug as expected. I've tried adding the `-i mi2` option, but it doesn't seem to change anything or present any useful information. The version of GDB that I'm using in Cygwin is 9.2-1, and I'm on using Ghidra 10.3.3 on Windows 10 Pro. Are there any other recommended troubleshooting steps I can take here?

**Comment by d-millar** [comment]
@bdemick Hey, this is a bit of a guess, but try `C:\\cygwin64\\bin\\bash.exe --login -i -c '/usr/bin/gdb'`.  I'm not sure what actually happens if gdb is not run interactively.

**Comment by d-millar** [comment]
Apologies - left off a bit.  Try `C:\\cygwin64\\bin\\bash.exe --login -i -c '/usr/bin/gdb -i mi2'`.

**Comment by d-millar** [comment]
Looking at this a little more, I don't think you're going to be happy with the behavior mediated by the bash shell.  I can run a target, but basically only the Objects control pane and the Interpreter are working.  I believe this is because stdout/stderr are not being routed from gdb through the bash shell to Ghidra, although I'll need to do some more work to verify this.  The better approach, I think (haven't tried it yet) is to run gdbserver from a separate bash shell and connect to it from Ghidra using "gdb via SSH".

**Comment by d-millar** [comment]
*sigh* - nope, that's not going to work either

**Comment by bdemick** [comment]
My target is VMWare Workstation's GDB stub, so I don't have a lot of control over the target in this case, unfortunately.

**Comment by d-millar** [comment]
Hmmm.  Yes, you're definitely operating in a tricky environment.  Even if we get you past the bash/gdb issues, the gdbstub in VMWare provides you with a very limited perspective on the target.  For example, assuming you're running a full OS in VMWare, the thread list provided by gdb will actually be a processor list, and module/memory info are basically right out.

We have nascent support for this using Volatility-over-gdb, but it hasn't been released, except in beta form as an extension using our basically-untested traceRMI features.  Is your target OS Windows by any chance?

**Comment by bdemick** [comment]
Not Windows. Looks like this isn't a viable option for me at the moment, but it was really just a potential nice-to-have option if it worked. Appreciate all the troubleshooting!
