### ISSUE TITLE
Add "system info for bug report" to Ghidra, to copy the desired information to clipboard in markdown format...

### ISSUE THREAD

**Issue by slippycheeze** [NationalSecurityAgency/ghidra#5760]
**Is your feature request related to a problem? Please describe.**
When filing a bug report, y'all very reasonably ask for system details.   It is a somewhat annoying process to collect those all.

**Describe the solution you'd like**
menu: `Help > Copy Info for Bug Report` ⇒ clipboard contains all the details in ready-to-paste markdown, so I can just "select / C-v" them into place in the bug report.

**Describe alternatives you've considered**
I really only feel it when I have changed something on the system, because I copy/paste from my previous bug report.  but that probably also means you got a few reports for Ghidra 10.3.2 when I was really running 10.3.3 already, and just didn't remember...

**Additional context**
I'm suggesting this partly because it was the absolutely best tool to get *trustable* information out of our users in various large scale projects I worked on.  If we had the information as our tool would produce it, we could be 99 percent certain it was accurate and helpful.   If it was user-supplied, personally, I treated it as around 30 percent accurate at best. :)

The most useful "untrusted users" feature was one tool that spit out a CRC/checksum of the data, too, as part of what it asked to get.  Then if something felt off we could verify the data hadn't been hand edited, which very very occasionally someone felt the apparent need to do.

**Comment by ryanmkurtz** [comment]
I've wanted something like this too.

**Comment by slippycheeze** [comment]
I literally just discovered that `ghidra.util.Msg.showError(...)` has this useful little packet at the end of the `Details >>>` text pane:
```
---------------------------------------------------
Build Date: 2023-Aug-29 1442 EDT
Ghidra Version: 10.3.3
Java Home: C:\Users\danie\scoop\apps\temurin-jdk\current
JVM Version: Eclipse Adoptium 20.0.2
OS: Windows 11 10.0 amd64
Workstation: INYA
```

...which seems to cover it fairly well. :)

**Comment by ryanmkurtz** [comment]
Shall we close?

**Comment by slippycheeze** [comment]
> Shall we close?

I don't think so: my point was that the function to gather this information exists somewhere, so wiring it up into the "Help" menu shouldn't be too hard — to save someone rewriting the code that exists.

...but I'm fine if you want to call it done, and I'll just use a local script to bind it.  at the end of the day that'd solve /my/ problem well enough to be getting on with.
