### ISSUE TITLE
decomp_dbg cannot load function

### ISSUE THREAD

**Issue by jobermayr** [NationalSecurityAgency/ghidra#5771]
- Ghidra Version: Git 7737364

Try:
[FUN_f1061880.xml.log](https://github.com/NationalSecurityAgency/ghidra/files/12590170/FUN_f1061880.xml.log)

```
$ decomp_dbg
[decomp]> restore FUN_f1061880.xml
FUN_f1061880.xml successfully loaded: Intel/AMD 64-bit x86
[decomp]> load function FUN_f1061880
Execution error: Unknown function name: FUN_f1061880
```

**Comment by RootCubed** [comment]
Seems like that function is inside a namespace/class, doing `load function PGConfigurationDescriptor::FUN_f1061880` loads it successfully.

**Comment by jobermayr** [comment]
Thanks for the hint.
