### ISSUE TITLE
MemoryBlock.Contains

### ISSUE THREAD

**Issue by Xenios91** [NationalSecurityAgency/ghidra#5774]
When calling MemoryBlock.Contains(Address), if your Address object is not within RAM space, it will fail to find it even if traversing over constant space. It appears the "contains" method looks only in RAM space. It would be nice if we had an overloaded "contains" method where we could pass it an array or varargs of the space type we would like to check. 

For example:

`boolean hasAddress = MemoryBlock.contains(Address, AddressSpace.CONST);`

**Comment by ghidra1** [comment]
A memory block never contains "Constant" addresses.  The "CONST" address space is intended only to represent a a constant value in the form of an Address object and has no relation to "Memory".  You can always convert the constant value (CONST address.getOffset() ) to a memory Address within a specific AddressSpace before performing your check.
