### ISSUE TITLE
Idiomatic way of creating external data

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#578]
I develop script, which find all external references for raw binaries in automatic mode. When developing I was guided by a ELF loader: I create additional uninitialized memory blocks and thunked external functions:

```java
ExternalLocation externalLocation = currentProgram.getExternalManager()
        .addExtFunction(symbolLibrary.getProgram().getDomainFile().getName(),
                symbolLibrary.getName(),
                addressLibrary,
                SourceType.IMPORTED);
functionTarget.setThunkedFunction(externalLocation.getFunction());

```

I can create function in uninitialized memory only with API.

As a result I get external function with one reference (from original function) and original function with many true references (see the picture and table to understand what I mean):

![2019-05-07_104849_918013742](https://user-images.githubusercontent.com/4244396/57283483-e5e7a380-70b7-11e9-8463-f7f3f98f98e6.png)

| Name   | Reference Count | Symbol Type       | Source   | Location           |
|--------|-----------------|-------------------|----------|--------------------|
| memset |               1 | External Function | IMPORTED | External[0000103d] |
| memset |             176 | Thunk Function    | IMPORTED | 0000103d           |

But I can't do this for data (I didn't find needed API method for creating link between original data and external):

| Name           | Reference Count | Symbol Type   | Source   | Location           |
|----------------|-----------------|---------------|----------|--------------------|
| g_EXTERNAL_VAR |               0 | External Data | IMPORTED | External[0000100c] |
| g_EXTERNAL_VAR |             501 | Data Label    | IMPORTED | 0000100c           |

Temporary solution for quick jump to external file and viewing value of data: create comments with annotation (`0x0:{@program "/version_0/ROM@0000100c"}`).

**Questions**

1. How can I create external data in idiomatic way?
2. How can I create function in uninitialized memory block using GUI?

**Comment by emteere** [comment]
The ELF importer creates the uninitialized memory blocks because the relocation handler needs a real number to use for relocations that need to be fixed up in memory or instructions.  For example a call instruction or a reference created by multiple instructions needs a real address to call or else the instructions address calculation may not work.  If you don't need an interim location with a real address, I would skip creating the uninitialized memory block.

Normally if you want to create a reference to an external location you create the external address and create a reference to it either from code or from data.

In your data case you would create an external reference and optionally provide a program path and a label/address that should be associated with the reference.

I may not be entirely understanding your case, so I didn't want to point you in a direction not knowing if you really need an actual memory address for your reference.

2) An uninitialized memory block is the default type of block created when creating new blocks in the memory map.  There is an option on the create memory block dialog to make it initialized.

**Comment by saruman9** [comment]
Thank you. Now I understand why ELF importer creates the additional memory blocks.

1. It is not my case. I don't need an actual memory address for calculating. But if I will create the external address (external location) and a reference I won't get correct name of function (see #148), I can't make a quick jump to external program (I should open Symbol Tree → Imports → External Program → Needed Function/Data, on the other hand with the memory blocks Ghidra open external program after double clicking on thunked external function, for data as I already wrote I use comments with annotation).

2. I understand it. I rephrase the question: why I can create function in uninitialized memory only with API?

**Comment by emteere** [comment]
1) I think I understand the issue now.  What is the instruction that is used for the actual call/jump to the external?  If it is a CALLIND x, or JUMPIND x, then the reference override directly on the instruction won't work currently (coming in 9.1), The decompiler is using the actual calculated address for the indirection.  So the value the decompiler is using would be the place you would need to place a dummy function that would become a thunk to the external program.  So I see what you were attempting and you were on the right track. I'll have to play with it a bit more to give you better guidance.  But you should be able to:
   Create the fake EXTERNAL memory block, uninitialized for the external program locations.
       (you might not have to create the memory block if you use the API, not sure)
   Create a function of one byte at the appropriate location in the fake EXTERNAL memory block
   Create an external function with the correct name (not in the EXTERNAL memory block)
   Thunk the function in the fake EXTERNAL memory block to it

In 9.1, you will be able override the indirect call directly to the external location.  You will still have to provide the name within the one program as an external program reference.  We'll have to think about this to make sure it is done correctly.

2) When you create a function the GUI tries to figure out the functions body (address set) from the instructions found there.  If it can't, the function creation fails.  If you were to select a single byte, even without any defined instructions, I believe you could create the function from the GUI.

**Comment by saruman9** [comment]
1. Thanks for detailed instruction. I developed a script (not in public yet), that does everything, what you wrote. The solution has rough edges (additional fake memory blocks, fake functions for example), but I'm satisfied with the decision (and wait 9.1 version). I want to return to the original question: how can I create linked external global data (structures, strings, constants, etc)? I'm currently using fake memory blocks and comments with annotation now (as I already wrote, see the figure).

    ![2019-05-15_103719_890397842](https://user-images.githubusercontent.com/4244396/57757149-79932280-76fd-11e9-8aef-e94a4ae39656.png)
    Where `g_COOKIE` is fake global variable in uninitialized memory block, `0xdeadbeef` is value of global variable, `/ver_0/EXTERNAL_PROGRAM_0@000100c` is path to external program and address of the variable. I can quick open external location after double clicking on the comment.

2. Wow! Thank you! I'm surprised I hadn't realized that.

**Comment by emteere** [comment]
1. Are you hoping to get the value at the other end of the link and have the value used by the decompiler and other analysis, or just navigate to the location directly from the reference?

2. A little hidden.  Basic concept is functions need a body, if it can't be figured out, it needs to be provided.

If all the files are raw bytes and at non-overlapping addresses, have you considered importing them into the same program with add to program on import?  The only real drawback is if the processing of the other file has a file format like ELF, it can get tricky as the program can't be imported with add to program, and the program will be larger.  If that is the case, the files could be processed then the information applied.  I suppose the ELF file could be processed and applied with add to the current program as well, but that isn't supported currently.

The other program could be opened and the information retrieved as an option.  We've just never done that as it could be slow and use memory.  Although in reality, it would probably work at least for visual display.  Iterating through references or back references in multiple programs would be much more difficult to support.  There could be issues mixing objects from different programs.  There was an idea called a super program that pulled all these concepts together.

**Comment by emteere** [comment]
Do you have the option Edit->ToolOptions...->Navigation->ExternalNavigation set to NavigateToExternalProgram?

For data you can just create the external reference.  There currently isn't support for placing data at the external address as is supported for functions.  Also as mentioned in the previous post, the data items won't display from the external program, nor will the label change if the label in the external program changes.  We have thought about allow data definitions to be placed at the external address.  The decompiler likely won't pay attention to the data reference label.

**Comment by saruman9** [comment]
> Are you hoping to get the value at the other end of the link and have the value used by the decompiler and other analysis, or just navigate to the location directly from the reference?

Of course, the first is preferable, but I think, that it is not trivial task currently, so second will be enough to begin.

> If all the files are raw bytes and at non-overlapping addresses, have you considered importing them into the same program with add to program on import?

Sadly I have some shared libraries (it is raw bytes, not ELF/PE/Mach-O) and many files with overlapping addresses, that uses the libraries. Early (when Ghidra was not release) I used r2/IDA: I created project and imported the libraries for each file, then I imported already resolved information. It was painful, because I had to synchronize the results of reverse engineering. External programs in Ghidra is killer feature for me.

> There was an idea called a super program that pulled all these concepts together.

Can I see commented/dead code in repository or was the idea just an idea on paper?

> Do you have the option Edit->ToolOptions...->Navigation->ExternalNavigation set to NavigateToExternalProgram?

Cool! It works as I expected, thank you. I synchronize information about label changes and the data items using the script (should be run every time, when shared libraries was changed).

**Comment by emteere** [comment]
Getting the value at the other end of an external link at certain times isn't trivial and has many implications.  Getting the value from the other program wouldn't be too hard, but managing the programs for access at the right spots without a performance penalty would be tricky, and possibly expensive depending on the analysis.

Currently there isn't any code in the repository that implements the idea of a super program.

Glad it worked for you.  The option shouldn't be so hidden.  When you select on an external link, a dialog to navigate and/or turn on the navigation option should be shown so you know that you can navigate to the external program if you want.
