### ISSUE TITLE
Global strings in decompiler

### ISSUE THREAD

**Issue by gemini00** [NationalSecurityAgency/ghidra#579]
```
char s[] = {'w','o','r','l','d', '\n'};

int main() {
	printf("hello %s", s);
}
```
This snippet of code produce the following decompiled code
```
undefined8 main(void)
{
  printf("hello %s",s);
  return 0;
}
```

I was wondering if there's any chance to get the value of the char array instead of its name. Am i missing something?

I've compiled this snippet both for AARCH64 and x86_64 with gcc and it produce the same decompiled code.

In IDA hex-rays options if i untick "Print only constant string literals" i can get the following decompiled code:

```
int __cdecl main(int argc, const char **argv)
{
  printf("hello %s", "world\n");
  return 0;
}
```

Thank you in advance.

**Comment by dev747368** [comment]
It will depend on if the value is in a memory section that is read-only.

**Comment by gemini00** [comment]
Thank you for the answer, i solved the problem by setting the mutability to constant on the string. I consider this issue solved and closing it.

**Comment by dev747368** [comment]
👍

**Comment by EuanKirkhope** [comment]
if you go to the defined strings view, and right click a string the option "default settings" you can set the Mutability to constant and this will seemingly affect all strings everywhere!  Wish I found this ages ago!  It should be the default IMHO.
