### ISSUE TITLE
remaining count leading bits instructions

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#5790]
**Describe the bug**
There are a few remaining `cls` and `clz` type instructions that should be updated to use new lzcount() PCODE.  Ignoring all the vector/simd that are probably too complicated to use this anyways.

Really just noticed this while looking at AARCH64's 32/64-bit `cls` and `clz` 

but:

tricore `cls` and `cls.h` could maybe get optimized

RISC-V has unimpl `clz` and `clzw` 
- clz  register size, set to register size if no leading zero
- clzw  32-bit, set to 32 if no leading zero

HCS12 `BFFO` maybe?

68000 `ff1` maybe?

x86 `CLZERO` maybe?

Atmel `CLZ`

**Environment (please complete the following information):**
 - Ghidra Version: 4561e8335d3b62329c4afdf5a91bc6ce113b7002

**Comment by copumpkin** [comment]
Sorry if I'm misunderstanding since I'm unfamiliar with the inner workings of Ghidra, but shouldn't the `cls` be something other than `lzcount` since it's counting leading ones?
