### ISSUE TITLE
AARCH64 pair instructions

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#5791]
**Describe the bug**
Just auditing, so no specifics, and certainly could be incorrect, but looks like a few pair instructions could over-write its source register before the 2nd write

* `ldaxp`
* `ldnp`
* `ldp`
* `ldpsw`
* `ldxp`

**Environment (please complete the following information):**
 - Ghidra Version: 4561e8335d3b62329c4afdf5a91bc6ce113b7002

**Comment by GhidorahRex** [comment]
Nice find, thanks! Also looks like `ldpsw` is doing the incorrect operation. From the looks at it, it should be an `ldp` 32-bit with sign-extension.
