### ISSUE TITLE
After installing everything you need, it won’t start

### ISSUE THREAD

**Issue by boshkaoff** [NationalSecurityAgency/ghidra#5803]
I installed everything possible, but it still doesn’t see Java

**Screenshots**
https://imgur.com/a/NerLjrB

**Environment:**
 - OS: Windows 10 Pro 20H2
 - Java Version: 17.0.8.1
 - Ghidra Version: Latest

**Comment by ryanmkurtz** [comment]
You probably downloaded the source repository instead of the prebuilt release, which can be found here:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/5378554/879da28d-bbba-423c-9154-41edc7ae6292)

**Comment by boshkaoff** [comment]
IT WORKED tysm
