### ISSUE TITLE
How can I configure ghidra to show more WinAPI function parameters?

### ISSUE THREAD

**Issue by as0ni** [NationalSecurityAgency/ghidra#581]
I analyzed the program with "WindowsPE x86 Propagate External Parameters" and this certainly helps quite a bit. However, I'm not seeing comments for parameters of APIs like InternetOpenA and InternetOpenURLA (both in wininet.dll). 

I added wininet.dll to the project and loaded the appropriate PDB from the MS symbol server, but this did not help. 

I understand I can individually provide the function prototype from docs.microsoft.com, but this doesn't scale. 

Am I missing something? 

For additional clarity, I'm including two screenshots. The first shows parameters displayed in the comments:
<img width="692" alt="parameter_comments" src="https://user-images.githubusercontent.com/8812157/57480680-6819c880-726e-11e9-926f-fcd994e60004.png">

The second screenshot shows no parameters in the comments: 
<img width="638" alt="no_parameter_comments" src="https://user-images.githubusercontent.com/8812157/57480682-6819c880-726e-11e9-9269-fad398dfaec7.png">

**Comment by emteere** [comment]
The current mechanism would be to parse the windows header file(s) that includes the function signature you need.  In parsing the header files we included many of the windows header files, but not all.  In addition, the API method may have been added in a newer version of Visual Studio.
We're working towards a better solution that would include the matched API for the correct version of visual studio, or a choice of the correct version.

If you applied the .PDB, you might have to load the .PDB from the start, or re-run analysis after applying the .PDB file.  If you navigate to the import table entry for InternetOpenUrlA(), does it have parameters defined there?

**Comment by as0ni** [comment]
Thank you for the quick response! I did follow that process for loading the .PDB file, and unfortunately the function prototype in the import table is still `undefined InternetOpenUrlA(void)`. 

I did the following: 
- Created a project and pulled in both the malware sample and wininet.dll
- Loaded wininet.dll
- Loaded wininet.pdb
- Executed auto-analysis of wininet.dll (with "WindowsPE x86 Propagate External Parameters" checked)
- Ran auto-analysis of the malware with the same option selected
- Established an "association" between the two samples.

Sounds like there is not much more I can try at the moment, but I'm glad to hear something is in the works. 

Thanks again for your response and for supporting this awesome tool.

**Comment by as0ni** [comment]
One more question, before I make any assumptions: is there a way to manually parse a header file within the Ghidra interface?

**Comment by ryanmkurtz** [comment]
In the code browser tool, `File -> Parce C Source...`

**Comment by as0ni** [comment]
Thanks, I found that shortly after posting my last update :-(. So, I created a new parse configuration file, added wininet.h and used the parse options "-D_WIN32". 

Not sure if I'm supposed to use more/different parse options, but running that didn't add any more information.

**Comment by as0ni** [comment]
Found this great video by https://www.youtube.com/watch?v=u15-r5Erfnw by 0x6d696368 that addresses this very topic (and even this specific API). 

His gdt files are here, and they solved my issue: https://github.com/0x6d696368/ghidra-data/tree/master/typeinfo

**Comment by ariccio** [comment]
Pardon me if I may piggyback on this issue (sorry @emteere , I don't have an email for you?) but does ghidra parse the installed windows headers when I run analysis to gather the parameter information? I'm curious as to whether I can patch ghidra to pull in more parameter information. Namely, the annotations Microsoft has for the parameters. I have a feeling it will make some reverse engineering work a little bit easier, but as a C++ programmer, this java is way too obtuse for me to figure it out.

**Comment by dev747368** [comment]
@ariccio - you should probably open a new issue as this one was closed.  I'm not sure if emteere would see notifications just because you @ mentioned him.
