### ISSUE TITLE
Restore directory authentication in Ghidra Server

### ISSUE THREAD

**Issue by JonathonReinhart** [NationalSecurityAgency/ghidra#582]
Lots of organizations (small and large) use Active Directory or other LDAP servers to deal with the problem of having user authentication information spread out across various network services.

The [release notes for v9.0.1](https://www.ghidra-sre.org/releaseNotes_9.0.2.html#9_0_1) say:

> - Multi-User:Ghidra Server. Removed support for native OS authentication from Ghidra Server (removed modes -a2 and -a3) due to incompatibility with newer OS releases including Windows 10 and Windows Server 2016. Re-introduction of this will be considered for a future release.

It would be great if Ghidra Server could authenticate against a directory, instead of requiring a user database local to Ghidra Server.

The previous "Native OS password" mode only worked on Windows operating systems. It would be great if this were supported regardless of host OS. (In particular, I prefer running Linux servers.)

I think acceptable solutions are, in order of preference:
- Password-less Kerberos ([SPNEGO](https://en.wikipedia.org/wiki/SPNEGO)) authentication (would work with Active Directory)
  - This would likely require support in the Ghidra client as well
- LDAP authentication with password (would work with Active Directory)
- PAM authentication (which can be configured to work with either of the above)

Possible resources:
- https://github.com/bedrin/kerb4j
- https://directory.apache.org/api/java-api.html

**Comment by JonathonReinhart** [comment]
Hi @ryanmkurtz,

In the [release notes for 9.1](https://ghidra-sre.org/releaseNotes_9.1.html), I see the following:

> Multi-User:Ghidra Server. Added additional Ghidra Server authentication modes including: Active Directory via Kerberos and JAAS. The JAAS framework can facilitate use of LDAP, PAM, and other JAAS-supported extensions which utilize a login name and password. (GT-2658)

Thank you guys for adding back this feature. I'm not yet familiar with JAAS, but it appears to be just what Ghidra server needed.

Do you have a link to the Pull Request or commit which added this feature? I searched for JAAS in the PRs but didn't see anything.

And should this issue then be closed?

Thanks!

**Comment by ryanmkurtz** [comment]
Thanks for pointing this out, I'll close this ticket.

It was merged in at 309254d15f24732e329eda7daa882f2795cf863a
