### ISSUE TITLE
Decompilation fails with "Low-level Error: Unable to resolve type X"

### ISSUE THREAD

**Issue by programmeruser2** [NationalSecurityAgency/ghidra#5823]
**Describe the bug**
Ghidra is unable to decompile a function from a freshly imported binary, with the error being "Low-level Error: Unable to resolve type: [insert type here]". Default auto-analysis settings are used on the binary.

**To Reproduce**
1. Import the binary below into Ghidra
2. Use the default analysis options on the binary
3. Go to the decompilation tab for `main`. It will display `Low-level Error: Unable to resolve type: Modular`

**Expected behavior**
The function should decompile successfully.

**Attachments**
[functional_cpp_ii.zip](https://github.com/NationalSecurityAgency/ghidra/files/12709117/functional_cpp_ii.zip)

**Environment (please complete the following information):**
 - OS: Windows 10 build 19045.3448
 - Java Version: 17.0.1
 - Ghidra Version: 10.3.3
 - Ghidra Origin: Official Github release

**Additional context**
Source code of the binary: https://github.com/sahuang/my-ctf-challenges/blob/main/vsctf-2023/rev_functional-cpp-II/challenge/challenge.cpp

**Comment by caheckman** [comment]
This issue was addressed in Ghidra 10.4.  Commit 99da2a3e13688aa73d7045c595dc5cb1f41872a5.
