### ISSUE TITLE
GUI reset

### ISSUE THREAD

**Issue by purplebyteone** [NationalSecurityAgency/ghidra#5826]
Hi guys, is there a way to reset GUI back to original one?
![123](https://github.com/NationalSecurityAgency/ghidra/assets/17739404/c09f6b02-e0ae-4ad1-a4fd-cff3d2aa8504)

**Comment by ryanmkurtz** [comment]
Delete your CodeBrowser Tool from the Front End GUI, and then add it back in from `Tools -> Import Default Tools...`.

**Comment by purplebyteone** [comment]
Sorted, just closed app and deleted ./ghidra directory under ~ folder.
![image](https://github.com/NationalSecurityAgency/ghidra/assets/17739404/2405389b-ab1e-4429-9a5a-c78c746a7c08)

**Comment by purplebyteone** [comment]
@ryanmkurtz thank you for jumping in
