### ISSUE TITLE
sha256sum for 10.4 release does not match

### ISSUE THREAD

**Issue by crd477** [NationalSecurityAgency/ghidra#5839]
**Describe the bug**
 The provided SHA256SUM for the recent 10.4 release does not match that of the actual zip file.

**To Reproduce**
```
$ curl -OL https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.4_build/ghidra_10.4_PUBLIC_20230928.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  352M  100  352M    0     0  8665k      0  0:00:41  0:00:41 --:--:-- 8425k
$ cat ghidra.checksum
# this is value provided on the release download page
ed35bb29454e8f9134bf2e95efe000f5d915c3b28efbece852ff12ab2336cb75 ghidra_10.4_PUBLIC_20230928.zip
$ sha256sum -c ghidra.checksum 
ghidra_10.4_PUBLIC_20230928.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
$ sha256sum ghidra_10.4_PUBLIC_20230928.zip
6911d674798f145f8ea723fdd3eb67a8fae8c7be92e117bca081e6ef66acac19  ghidra_10.4_PUBLIC_20230928.zip
```

**Expected behavior**
 I expect the checksum to match.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: openjdk version "17.0.8" 2023-07-18
 - Ghidra Version: 10.4
 - Ghidra Origin: official GitHub distro

**Comment by mumbel** [comment]
`6911d674798f145f8ea723fdd3eb67a8fae8c7be92e117bca081e6ef66acac19`. seeing the same (@ghidra1 ping)

**Comment by ghidra1** [comment]
Appologies, I incorrectly posted the hash for the InstallationGuide.  Hash has been updated.  Thanks!

**Comment by crd477** [comment]
Thanks!  If it's not too much additional work, you might consider generating a checksum file, e.g., `ghidra.sha256sum`, as part of the release process.  It could be less error prone than updating the static text in the release notes each time.

**Comment by ghidra1** [comment]
I do produce a file during the build, but I copied the wrong entry from the file.  Copy paste error.

**Comment by crd477** [comment]
I'm sorry to belabor the point.  I wasn't clear enough.  I meant to additionally publish the _file_ called e.g., `ghidra.checksum` so that users can grab it and do `sha256sum -c ghidra.checksum`.  This helps to avoid copy/paste errors on both sides.
OK, I promise I'm finished now.
