### ISSUE TITLE
Import macho fails 

### ISSUE THREAD

**Issue by ViRo3** [NationalSecurityAgency/ghidra#5840]
**Describe the bug**
Importing provided binary into ghidra fails for most iOS 17+ binaries

**To Reproduce**
1. Import file
2. Use default import options
3. See error

**Expected behavior**
Should just import and work

**Screenshots**

**Attachments**
[MobileBackup](https://github.com/NationalSecurityAgency/ghidra/assets/87166847/4c190d55-61de-41d6-8278-be1df4484cbc)
(remove file extension)

**Environment (please complete the following information):**
 - OS: macOS 14.1
 - Java Version: BellSoft 17.0.8.1
 - Ghidra Version: 10.4
 - Ghidra Origin: Official release
 
<img width="824" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/87166847/543ef2e1-698f-4f8f-a007-c8f16e8ade44">

**Comment by ryanmkurtz** [comment]
Can you provide more info on the type of Mach-O's? Are they dylibs extracted from the cache, or standalone executables? Or something else?

**Comment by ryanmkurtz** [comment]
Maybe you provided one...it appears as a broken link on my phone GitHub app.

**Comment by ViRo3** [comment]
It wasn't letting me upload so I just altered the extension so it would let me. The binary was extracted from the cache.

**Comment by ryanmkurtz** [comment]
How did you extract it?  Our extractor or another?

**Comment by ViRo3** [comment]
I used https://github.com/blacktop/ipsw

ipsw dyld extract dyld_shared_cache_arm64e <insert what you extract>

**Comment by ryanmkurtz** [comment]
It looks like there are some sections that are not contained within their segments (in the file).  This breaks an assumption I have been making about the layout of Mach-O's, which up until now has been a seemingly correct assumption.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/5378554/505d00e1-26c0-4709-8a28-90a83d17ccaf)

@blacktop, is that something that is working as-intended on your end?

**Comment by ryanmkurtz** [comment]
Thanks @blacktop.

@ViRo3, in the meantime you could also try Ghidra's built in extractor, which I've made a lot of improvements to for 10.4.  You just open the dyld_shared_cache as a filesystem within Ghidra and import/export the components you need from the File System Browser GUI.

Closing this ticket as there is no immediate change to Ghidra that needs to take place.
