### ISSUE TITLE
Incorrect behaviour of decompiler when jump occurred to delayed instruction

### ISSUE THREAD

**Issue by VladLupashevskyi** [NationalSecurityAgency/ghidra#5866]
**Describe the bug**
It's quite common on Fujitsu FR processors to have a delayed instruction and have a branch on it.

I have come up with a small example to show the problem.

Here is the function:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/17516057/a7047f2d-3c11-4b94-bb37-7beffae2870b)

As we can see there is a jump instruction with delayed instruction at addresses `0x8000e` and `0x80010`. There is also a branch before on address `0x80008` that points to the delayed `ldi` instruction. From a processor point of view the delayed instruction has the same opcode as normal non-delayed one. It's a previous `jmp` instruction that determines next coming instruction as a delayed one. So the jump onto delayed `ldi` instruction is absolutely correct sequence.

If I point the cursor to the beginning of the function (as shown on previous screenshot), the decompiled function looks correct (Except for the message `WARNING: Instruction at (ram,0x00080010) overlaps instruction at (ram,0x0008000e)`):

![image](https://github.com/NationalSecurityAgency/ghidra/assets/17516057/42620f1d-b819-4ec7-88a6-a68c465d3165)

However as soon as I point to either address `0x80012` or `0x80014`, so in the area after delayed instruction (to which there is a conditional jump) and before instruction to which there is a non-conditional jump, I see the following in the decompiler view:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/17516057/c87d7be5-121e-4524-b754-1884e26d0770)

So somehow because of the feature of delayed instruction and conditional jump to it, decompiler cannot figure out that it's actually a part of a bigger function.

Moreover if I look at xrefs of RAM variables `DAT_00040000` and `DAT_00040010`, I see the following:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/17516057/651fbec3-5c3b-4d39-90d0-0da3a6278166)

`DAT_00040000`  is detected to be part of `FUN00080000`, however `DAT_00040010` is not detected to be a part of that function.

This behaviour makes it tricky to analyse functions, especially when jumping from XREFs, as I would always need to move cursor to the top of the function in disassembler to see the full function in decompiler.

**To Reproduce**
1. Download and install FR processor spec here: https://github.com/simeonpilgrim/ghidra_fujitsu_fr
2. Open binary (see Attachments) in CodeBrowser, select an offset of `0x80000`, as well as processor `FRn`.
3. Add memory region `0x40000` - `0x4001a` to see XREFs
4. Place cursor to the beginning of the function at address `0x80000` in disassembler and observe correct behaviour in decompiler view
5. Place cursor at address `0x80012` in disassembler and observe incorrect behaviour in decompiler

**Expected behavior**
- Decompiler must show the full function when cursor placed to addresses `0x80012` or `0x80014`
- All XREFs related to `FUN00080000` must include function name

**Attachments**
Binary of the example:

```
9B 4C 00 00 06 C0 A8 50 E2 03 9B 85 00 1A 9F 05 C0 04 C0 00 9B 4D 00 10 12 04 97 20 00 00 00 00
```

**Environment:**
 - OS: macOS 13.2.1
 - Java Version: 17.0.5
 - Ghidra Version: 10.3.3
 - Ghidra Origin: official GitHub distro
 - Processor: https://github.com/simeonpilgrim/ghidra_fujitsu_fr (master branch)

**Comment by emteere** [comment]
If you re-analyze, or delete the function and re-create it, does the issue correct itself?

**Comment by esaulenka** [comment]
> If you re-analyze, or delete the function and re-create it, does the issue correct itself?

No, looks like it cannot be fixed by any attempts of re-analyze.
I have the same issue with FR60 binary (don't know which compiler used here, but it use such 'branch to delayed instruction' almost in every function).

**Comment by emteere** [comment]
The decompiler will abide by the start of functions, and if code is not inside a function there is code that will walk back to the start of the function.  So there is probably two or three issues here.

- analysis should automatically recognize the added flow reference and fixup the function body
- Undefined function creation for the decompiler should walk back to the start of the function
- Possibly the function recovery is not considering the flow into the delay slot correctly

Will take a deeper look.

**Comment by VladLupashevskyi** [comment]
Hey @emteere, sorry for long response. I can confirm that re-analyzing/deleting and creating the function does not solve the issue.

**Comment by emteere** [comment]
I've duplicated it and should have at lease a basic fix in soon.  There's a simple fix for the function body creation.

There's a larger more invasive fix when there is no function defined, related to basic block models.  That might split into another issue, although it is very related.  Jumps into delay slots can be tricky for some of the processing/following algorithms if not done right, which they aren't now.
