### ISSUE TITLE
Make 'interrupt Python execution' command more discoverable

### ISSUE THREAD

**Issue by comex** [NationalSecurityAgency/ghidra#588]
**Is your feature request related to a problem? Please describe.**
I dumbly didn't realize the existence of Ctrl-I in the Python window to interrupt a running command, despite it being in the documentation.  It would be nice if it were more discoverable.

**Describe the solution you'd like**
- It should probably appear as a button in the toolbar or right-click menu option.
- It could also be a bindable action, in which case I would have noticed it when checking the Key Bindings settings.
- The normal shortcut to interrupt execution is Ctrl-C.  On macOS, at least under the System theme, Ctrl-C is not reserved for Copy (which is Cmd-C instead), so it would be nice to make Ctrl-C a default alias for Ctrl-I.  Alternately, Ctrl-C could interrupt on all platforms if there is no text selection, although that might be confusing.

**Comment by ryanmkurtz** [comment]
I believe Ctrl-I interrupts, but I don't have it in front of me.  It is specified in the help.

**Comment by comex** [comment]
Now I feel stupid. 😓 I will edit the report to be about discoverability.

**Comment by ryanmkurtz** [comment]
I made the interrupt and reset actions buttons with bindable/configurable keys.  It will be in the 9.1 release.
