### ISSUE TITLE
Unable to Import File: "java.nio.file.InvalidPathException: Illegal char <?> at index 0: ?C:\Program Files (x86)\sox-14-4-2\sox.exe"

### ISSUE THREAD

**Issue by HowlingFoxRouko** [NationalSecurityAgency/ghidra#5894]
**What happened**
When I go to File > Import File..., Ghidra acts as though it is about to load, and then it stops and throws this error.

**To Reproduce**
1. Go To "File"
2. Select "Import File..."
3. Select any .exe
After beginning the import, this error populates.

**Expected behavior**
I was anticipating the file to be imported to Ghidra. Unfortunately this doesn't seem to be the case.

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/13912530/b90d70fe-f2bc-4d04-b33f-2922e5c46d4c)

**Environment (please complete the following information):**
 - OS: Windows 10 22H2 19045.3570 (System locale: Japanese)
 - Java Version: 21.0
 - Ghidra Version: 10.4
 - Ghidra Origin: Official GitHub release

**Additional context**
This is potentially a skill issue; I had booted Ghidra straightaway and began trying to import the files. If that's not what I'm supposed to do, please do educate on how I can proceed. Thank you;;

**Comment by astrelsky** [comment]
It might be related to your system locale. Unfortunately I don't have a solution to offer. I just wanted to point it out since it is easy to miss and a developer might be more likely to see it in this comment.

**Comment by ryanmkurtz** [comment]
Yes, likely an issue with Japanese locale.  Did you add your own system library search paths to the loader options?  The issue seems to come from there.  This also likely won't matter, but I see you are using JDK 21 which we haven't tested much yet.  If you used JDK 17, we'd be narrowing down the problem space.

**Comment by HowlingFoxRouko** [comment]
> Did you add your own system library search paths to the loader options? The issue seems to come from there. 
I have not added anything, no. After downloading and running ghidra.bat, this was what happened when I attempted the importing of a file. :/
I do know that the \ character in Japanese IME is ¥, so I'm wondering if the programme is seeing that as an illegal character and replacing it with the "?" As shown in the screenshot. I don't have a ton of Java experience, and even less with JDK so I'm not certain.

> This also likely won't matter, but I see you are using JDK 21 which we haven't tested much yet. If you used JDK 17, we'd be narrowing down the problem space.
I will try this out to see if this resolves the issue for certain.

**Comment by ryanmkurtz** [comment]
I switched my Windows 10 local to Japanese and used JDK 21 with Ghidra 10.4, but I could not reproduce the exception you are seeing.

**Comment by HowlingFoxRouko** [comment]
How curious. I wonder if it is perhaps because of the source from which I'd downloaded the JDK. I'm not certain myself what could be causing this issue but I'm more than happy to provide any logs or screenshots.

**Comment by ryanmkurtz** [comment]
What does this window look like for you?

![image](https://github.com/NationalSecurityAgency/ghidra/assets/5378554/668b134f-5250-47d9-999c-caf4b0a1fa16)

I mainly want to see that path string in the title bar.

**Comment by astrelsky** [comment]
Oh wait, are you importing some kind of shortcut by any chance? I noticed it says "Error importing file: ChromeSetup.exe" but the error is when importing some "sox.exe".

**Comment by HowlingFoxRouko** [comment]
> What does this window look like for you?
> 
> ![image](https://user-images.githubusercontent.com/5378554/276917425-668b134f-5250-47d9-999c-caf4b0a1fa16.png)
> 
> I mainly want to see that path string in the title bar.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/13912530/8f2fe78a-78d8-4d7d-8654-b640fb5492d8)
This is how I have it set up presently. While ChromeSetup.exe is just a dummy file (the real importing file has the same experience) I think it is set up correctly?



> Oh wait, are you importing some kind of shortcut by any chance? I noticed it says "Error importing file: ChromeSetup.exe" but the error is when importing some "sox.exe".

I am not, I'm importing the exact ChromeSetup.exe that is downloaded onto this drive.

**Comment by ryanmkurtz** [comment]
What happens if you try to import files from the `C:\` drive?

**Comment by HowlingFoxRouko** [comment]
> What happens if you try to import files from the `C:\` drive?

Same result unfortunately.

**Comment by ryanmkurtz** [comment]
@programminglaboratorys What system locale are you using?

**Comment by ryanmkurtz** [comment]
@HowlingFoxRouko @programminglaboratorys, can you please report the output of running these 2 commands in your Ghidra Python Interpreter (you may need to sanitize your output if you have privacy concerns):

```python
from java.lang import System
System.getProperty("java.library.path")
```
Basically I am wondering if the bad character is in one of those paths.

**Comment by programminglaboratorys** [comment]
> @HowlingFoxRouko @programminglaboratorys, can you please report the output of running these 2 commands in your Ghidra Python Interpreter (you may need to sanitize your output if you have privacy concerns):
> 
> ```python
> from java.lang import System
> System.getProperty("java.library.path")
> ```
> 
> Basically I am wondering if the bad character is in one of those paths.

sorry for the late reply but yeah of course 
```python
>>> from java.lang import System
>>> System.getProperty("java.library.path")
u'C:\\Program Files\\Java\\jdk-17\\bin;C:\\Windows\\Sun\\Java\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\Python\\Python310\\Scripts\\;C:\\Program Files\\Python\\Python310\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Microsoft\\jdk-11.0.16.101-hotspot\\bin;C:\\Program Files\\Python310\\Scripts\\;C:\\Program Files\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\jdk1.8.0_351\\bin;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\mingw64\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\GitHub CLI\\;C:\\Program Files\\nodejs\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\WinMerge;C:\\Users\\ACER\\Documents\\platform-tools;C:\\Program Files\\Python\\Python3.8;C:\\Program Files\\Java\\jre-1.8\\bin;C:\\Program Files\\Java\\jdk-17;C:\\Program Files\\CMake\\bin;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\Python\\Python310\\Scripts\\;C:\\Program Files\\Python\\Python310\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Microsoft\\jdk-11.0.16.101-hotspot\\bin;C:\\Program Files\\Python310\\Scripts\\;C:\\Program Files\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\jdk1.8.0_351\\bin;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\mingw64\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\GitHub CLI\\;C:\\Program Files\\nodejs\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\WinMerge;C:\\Users\\ACER\\Documents\\platform-tools;C:\\Program Files\\Python\\Python3.8;C:\\Program Files\\Java\\jre-1.8\\bin;C:\\Program Files\\Java\\jdk-17;C:\\Program Files\\CMake\\bin;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;;;C:\\Users\\ACER\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;.'
```

**Comment by ryanmkurtz** [comment]
@programminglaboratorys, thank you. Unfortunately, i don't see any bad paths in there.  I will be putting in a little change that will catch the exception and gracefully log the error, allowing the import to succeed.  That change will close this ticket.  Perhaps when the change is in, you can try it out and report back with the error message that was logged.

**Comment by skavengeer** [comment]
I'm getting the same problem
Please fix problem or some insure

**Comment by dk4z5** [comment]
Testing in different versions:

- ghidra_10.2.2_PUBLIC   Works
- ghidra_10.4_PUBLIC     Not Working
- ghidra_11.0.1_PUBLIC  Not Working

Batch imports fails only with modern Windows PE option.

My workaround, import with 10.2.2 and analyse with the newer version

**Comment by ryanmkurtz** [comment]
@dk4z5 Can you paste in your 11.0.1 stack trace?

**Comment by nwk6661** [comment]
Getting the same thing - EN system locale, only special characters in the path are `-` and `_` in the executable name.

```
Illegal char <?> at index 0: ?
java.nio.file.InvalidPathException: Illegal char <?> at index 0: ?
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraryFromSearchPaths(AbstractLibrarySupportLoader.java:640)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraries(AbstractLibrarySupportLoader.java:533)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:104)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:336)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2024-Jan-30 1212 EST
Ghidra Version: 11.0.1
Java Home: C:\Program Files\Java\jdk-17.0.2
JVM Version: Oracle Corporation 17.0.2
OS: Windows 11 10.0 amd64
Workstation: NOAH-PC

```

@dk4z5 's workaround with importing with 10.2.2 works for me

**Comment by ryanmkurtz** [comment]
I'll fix this, thx
