### ISSUE TITLE
Unable to use the getHeadlessAnalysisTimeoutStatus() in post script method to detect a timeout

### ISSUE THREAD

**Issue by harshvp1621** [NationalSecurityAgency/ghidra#5895]
I am using the analyzeHeadless script to perform some headless analysis on various binaries and subsequently process the results with a postscript. I would like to detect whenever an analysis is terminated due to a timeout. However, I am unable to a proper API to check for timeouts. The `getHeadlessAnalysisTimeoutStatus` API mentioned in the docs here - [analyzeHeadlessREADME](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/RuntimeScripts/Common/support/analyzeHeadlessREADME.html) is not accessible in the postscript directly and does not seem to be a member function of the `currentProgram` object.

Example python postscript:

```
# Check for timeout here
status = getHeadlessAnalysisTimeoutStatus()
# Print functions
func_iterator = currentProgram.getListing().getFunctions(True)
for f in func_iterator:
        print(f.getName())
```
Is there a better way to check the analysis timeout status in the postscript?

**Comment by ryanmkurtz** [comment]
Sorry for the delay in answering this.  I think you being affected by #888.  You'll have to write your script in Java if you need to use this functionality.
