### ISSUE TITLE
Cannot create new project on Desktop

### ISSUE THREAD

**Issue by tonyGhi** [NationalSecurityAgency/ghidra#5896]
I cannot create a new project in Ghidra. I'm using Java version 21. Here's the error that comes up:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/148547220/65c03717-c580-440b-bd84-6611c578eea9)

Here's path in environment variable:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/148547220/b56d7645-5945-4366-9628-7e5db836ac7c)

**Comment by ryanmkurtz** [comment]
What directory are you trying to create the new project in?

**Comment by tonyGhi** [comment]
> What directory are you trying to create the new project in?

I tried  creating a new directory (folder) "test" on my desktop which came up with the original error shown above . I then tried using the Ghidra directory and still had the same error. I tried installing Java in the Ghidra directory also which did not work. I'm puzzled. I'm assuming it has something to do with the Java install.

**Comment by tonyGhi** [comment]
> Hmmm. I assume you can create directories at these locations outside of Ghidra?

Yes. No problems

**Comment by tonyGhi** [comment]
I managed to narrow down the problem. The error only occurs when I try to create a project on the Desktop or any directory located on the Desktop. I checked the permissions for the Desktop and all privileges are allowed. Hmmm...still investigating. But at least now I can create a project under my User Profile.

**Comment by ryanmkurtz** [comment]
I just tried Ghidra 10.4 with JDK 21 and had no issues creating a new project on a Windows 10 or 11 desktop.  I am going to close this issue assuming something is weird about your environment, but if you come across more info that points to a problem with Ghidra, please feel free to reopen.
