### ISSUE TITLE
Ghidra project homepage link

### ISSUE THREAD

**Issue by mathrock** [NationalSecurityAgency/ghidra#59]
README.md links to https://www.ghidra-sre.org/ which currently has placeholder content.  However, the site with the full content is available at https://ghidra-sre.org/.  Correct fix, may be to just fix the project site to serve up the same content via both domains.

**Comment by Ristovski** [comment]
Both addresses resolve to the same site for me, also confirmed by using `wget`.
Looks like it has already been fixed.

**Comment by ctubbsii** [comment]
Yeah, both appear to be A records, and have the same content for me, too.
`diff -urs <(curl --max-redirs 0 https://ghidra-sre.org) <(curl --max-redirs 0 https://www.ghidra-sre.org)`

**Comment by nneonneo** [comment]
You might have had the old page cached somehow?

**Comment by mathrock** [comment]
It's fixed for me now.
