### ISSUE TITLE
Cancel Export Program Doesn't Cancel

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#591]
**Describe the bug**
Clicking cancel when exporting to c does not function.

**To Reproduce**
1. Export program to c.
2. Click cancel.

**Expected behavior**
The decompilation to be aborted.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.475]
 - Java Version: 12.1
 - Ghidra Version: 9.2

**Comment by ryanmkurtz** [comment]
Thanks, I was able to reproduce this bug.

**Comment by astrelsky** [comment]
> Thanks, I was able to reproduce this bug.

No problem. Likely an easy fix.
