### ISSUE TITLE
Listing view (and exporting of C) option to show negative decimal values for signed types instead of hex values

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#5922]
**Is your feature request related to a problem? Please describe.**
I need to have the ability to chose when certain negative values are shown (and exportable) as negative decimal numbers and not in left in hex

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Manual conversion.

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
@Wall-AF, are you asking for a feature like: "show all scalars with the value of `0xffffffff` as `-1` in the Listing (and exported C)?  You mentioned "certain values", so I assume you don't want a global setting for all negative scalars.  If I am still not understanding, perhaps you can provide some specific examples of the workflow you are desiring.

**Comment by Wall-AF** [comment]
> "certain values"

I meant the ability to choose which set are shown as `decimal` (using the datatype and compiler to determine size/signedness).  I'm thinking there could be cases where a _carte blanche_ global setting may not be appreciated by everyone.

**Comment by ryanmkurtz** [comment]
I might be more confused now.  If you can imagine this feature existed the way you are envisioning it, can you list the steps you would take to activate it?

**Comment by Wall-AF** [comment]
Sorry to confuse you!  In the picture below you can see an example of some `C` (`Decompile:`Panel) that is referring to data stored in the data segment that I'll eventually need to export to another `C` file (the green highlighed array - in the `Listing:`Panel):
![image](https://github.com/NationalSecurityAgency/ghidra/assets/67698927/1e771693-8eae-4243-b97a-1295631f602d)
What I would like is to assign an attribute (probably from the `Context Menu`in the`Listing:`Panel, and/or via a datatype option) to tell Ghidra how to display/export values of that type.  There are the standard numeric representations like `hex`, `oct`, `decimal` (and for completeneess, `binary`, although I'm unsure of its usability) not forgetting signedness, and I've found a novel way my application suit uses to represent a `signed byte` (`-128 to +127`) by using an `unsigned byte` and subtracting `128` in calculations using that type which would be helpful too!  Hope this helps.

**Comment by Wall-AF** [comment]
Included [here](https://github.com/NationalSecurityAgency/ghidra/files/13256591/dragon_Pre__validate.zip) is a follow-up function that uses the allocted memory stored in those pointers.  By using illegal variable names I've annotated most of the indexing where possible and in comments otherwise.
___
An interesting compiler optimisation within this example function is that a couple of local variables are created based upon the address of the first element (beginning of) the `this` structure.  These are then used to point to differently sized (`int` vs `long`) array objects embedded within the `this` structure and are incremented by their appropriate size.  (The two examples I've named `pThis2Offset`&`pThis4Offset`.)  Can this kind of usage be understood and used to produce better `C` output?

**Comment by ryanmkurtz** [comment]
Sorry for the delayed response.  Have you tried `Data -> Settings/Default Settings` in the Listing context menu?

**Comment by Wall-AF** [comment]
![image](https://github.com/NationalSecurityAgency/ghidra/assets/67698927/afb7062b-1dc5-43cc-b8ab-b2778e8bf21d)
Just tried, but no satisfaction!

**Comment by ryanmkurtz** [comment]
Where did it not work for you?

**Comment by Wall-AF** [comment]
I RMB'd from the `Listing:`Panel on the highlighted array (pictured earlier) and changed that default setting for `sbyte`.

**Comment by Wall-AF** [comment]
Tbf, when I exported the whole code recently, the static/intialed values in the data segment(s) don't appear to be exported! How is this done?

**Comment by Wall-AF** [comment]
@ryanmkurtz any ideas?

**Comment by ryanmkurtz** [comment]
> Tbf, when I exported the whole code recently, the static/initialed values in the data segment(s) don't appear to be exported! How is this done?

I asked about this because I wasn't sure either, and apparently we don't export these.

**Comment by Wall-AF** [comment]
> > Tbf, when I exported the whole code recently, the static/initialed values in the data segment(s) don't appear to be exported! How is this done?
> 
> I asked about this because I wasn't sure either, and apparently we don't export these.

Should this be raised as a separate feature request, or can it be handled in this one?  (I have so many outstanding already!!)

**Comment by ryanmkurtz** [comment]
Yes that should really be its own ticket.

**Comment by ghidra1** [comment]
Data Settings can be used to influence Data value formatting within the listing but not the decompiler.  Unfortunately, Function variables/parameters and the decompiler do not support the format Settings mechanism.  The closest thing is the Convert actions which apply formatted equates to specific values at specific locations.

**Comment by Wall-AF** [comment]
> Data Settings can be used to influence Data value formatting within the listing but not the decompiler. Unfortunately, Function variables/parameters and the decompiler do not support the format Settings mechanism. The closest thing is the Convert actions which apply formatted equates to specific values at specific locations.

In this case, the `sbyte` data is shown in the `Listing:`Panel and the suggestion https://github.com/NationalSecurityAgency/ghidra/issues/5922#issuecomment-1804216289 had no effect on the array of `sbyte` data shown in the image in comment  https://github.com/NationalSecurityAgency/ghidra/issues/5922#issuecomment-1791432416.

**Comment by ghidra1** [comment]
An instance setting worked for me on the array
![image](https://github.com/NationalSecurityAgency/ghidra/assets/48333017/08fedb68-b79d-47b7-b52c-21d87a1bd4ce)

**Comment by ghidra1** [comment]
Default settings did not.  I will have to look into that use case for an array.

**Comment by Wall-AF** [comment]
Well, I don't know what to say!  I just went back to check again and it was correct.

Upon further investigation, the array needed to be closed and reopened for the setting to take effect.  (Sorry for that.)

I'll close this now.  Thanks.

**Comment by ghidra1** [comment]
One of the issues I fixed was the lack of a change event which was preventing the listing from updating immediately.
