### ISSUE TITLE
Processor M32R  Can't read language spec D:\GHIDRA\Ghidra\Processors\M32R\data\languages\m32r.sla

### ISSUE THREAD

**Issue by zaki1213-2** [NationalSecurityAgency/ghidra#5935]
Hi everyone .
I tried adding a Ghidra M32R Processor to Ghidra Version 10.2.3. Initially the Processor was not read by Ghidra, then I tried to repair the file in the language and then it was read by Ghidra but when I started reverse engineering, the error "Can't read language spec" occurred. D:\GHIDRA\Ghidra\Processors\M32R\data\languages\m32r.sla" how to solve this?
I downloaded it from https://github.com/ripnet/ghidra-m32r
![Screenshot 2023-11-07 165107](https://github.com/NationalSecurityAgency/ghidra/assets/126563494/42be4062-d4a2-4563-b355-d7e15bb718f9)

Please help me

**Comment by ryanmkurtz** [comment]
It's possible the `.sla` file has become corrupted for some reason.  You could try deleting it and restarting Ghidra.  It should attempt to recompile it.

**Comment by zaki1213-2** [comment]
> It's possible the `.sla` file has become corrupted for some reason. You could try deleting it and restarting Ghidra. It should attempt to recompile it.

I have tried that many times but the result is still the same, is it because that version of Ghidra can't read the processor?

**Comment by GhidorahRex** [comment]
The issue is with the m32r.pspec file. <memory_block> entries are missing the `initialized="false"` attribute.

**Comment by zaki1213-2** [comment]
what should I do about this problem? Should I use another version of Ghidra?

Pada Sel, 14 Nov 2023 pukul 19.51 GhidorahRex ***@***.***>
menulis:

**Comment by GhidorahRex** [comment]
You should edit the m32r.pspec file and add `initialized="false"`attribute to the `<memory_block>` tags.

**Comment by zaki1213-2** [comment]
how do I add it?

<default_memory_block>
<memory_block name="CS0" start_address="0x100000" length="0x100000"
mode="rw"/>
<memory_block name="CS1" start_address="0x200000" length="0x200000"
mode="rw"/>
<memory_block name="CS2" start_address="0x400000" length="0x200000"
mode="rw"/>
<memory_block name="CS3" start_address="0x600000" length="0x200000"
mode="rw"/>
<memory_block name="SFR" start_address="0x800000" length="0x4000"
mode="rw"/>
<memory_block name="RAM" start_address="0x804000" length="0x1C000"
mode="rw"/>
</default_memory_block>

Pada Jum, 17 Nov 2023 pukul 00.22 GhidorahRex ***@***.***>
menulis:

**Comment by GhidorahRex** [comment]
like this for each one: `<memory_block name="CS0" start_address="0x100000" length="0x100000" initialized="false" mode="rw"/>`

**Comment by zaki1213-2** [comment]
Thank you, that's possible, but there is one more question, why is the compilation result messy or bad? Do I have to change the file again?


in the function section there are some that don't seem to come from the bin file, such as RI_2 RI_3, is that an error when compiling?

![Screenshot 2023-11-17 043723](https://github.com/NationalSecurityAgency/ghidra/assets/126563494/14587406-7392-4e35-b10c-6105741ece95)
