### ISSUE TITLE
Batch Import of iOS App Folder fails to import some libraries

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#5937]
**Describe the bug**

If batch importing the folder of an iOS apps, some libraries fail to import

**To Reproduce**

Unpack the attached Archive and then batch import the `ReverseOneSignal.app` folder

**Expected behavior**
Minimum expectation: All binaries/libraries should get imported
Ideally: All binaries/libraries are imported and their references to each other are properly resolved. But I recognize that this will be tricky given that they won't be imported in the correct order, i.e. the first file imported is the main binary, and not the library it depends on. This might just be a fundamental limitation of the batch import?

**Screenshots**
Some libraries are missing
![image](https://github.com/NationalSecurityAgency/ghidra/assets/8415354/a614c6b1-90ed-4207-a276-0f0bb393b1ae)

**Attachments**

Demo App with various Libraries
[ReverseOneSignal.app.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/13305798/ReverseOneSignal.app.tar.gz)

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 17
 - Ghidra Version: 134806cbe46dcb71bb41ed19deae1dec840a846f
 - Ghidra Origin: Built locally

**Additional context**
@ryanmkurtz this definitely related to your recent changes around Mach-O.
I imported the same folder with Ghidra 10.4 and it imported all files correctly. Albeit without any resolving of symbols from other files.

The concrete issue is that the following exception is thrown during the import of the libraries that fail to show up afterwards

```
ERROR Import failed for OneSignalExtension (ImportBatchTask) java.io.IOException: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.symbol.Namespace.isExternal()" because "namespace" is null
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:100)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:884)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:99)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doImportApp(ImportBatchTask.java:152)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doImportBatchGroup(ImportBatchTask.java:128)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doBatchImport(ImportBatchTask.java:117)
	at ghidra.plugins.importer.tasks.ImportBatchTask.run(ImportBatchTask.java:92)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.symbol.Namespace.isExternal()" because "namespace" is null
	at ghidra.program.database.external.ExternalLocationDB.setName(ExternalLocationDB.java:255)
	at ghidra.app.util.opinion.MachoProgramBuilder.fixupExternalLibrary(MachoProgramBuilder.java:863)
	at ghidra.app.util.opinion.MachoProgramBuilder.processBindings(MachoProgramBuilder.java:834)
	at ghidra.app.util.opinion.MachoProgramBuilder.processBindings(MachoProgramBuilder.java:765)
	at ghidra.app.util.opinion.MachoProgramBuilder.build(MachoProgramBuilder.java:131)
	at ghidra.app.util.opinion.MachoProgramBuilder.buildProgram(MachoProgramBuilder.java:107)
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:90)
	... 12 more
 ```

**Comment by fmagin** [comment]
What seems to happen here is that during the import of `OneSignalExtension` following code tries to get the library at path `@rpath/OneSignalExtension.framework/OneSignalExtension`. I'm not sure where `libraryPaths` comes from, but this might be an edge case where a library for some reason also has _itself_ as the dependency?

```java
	private void fixupExternalLibrary(int libraryOrdinal, Symbol symbol, List<String> libraryPaths)
			throws InvalidInputException {
		ExternalManager extManager = program.getExternalManager();
		int libraryIndex = libraryOrdinal - 1;
		if (libraryIndex >= 0 && libraryIndex < libraryPaths.size()) {
			Library library = extManager.getExternalLibrary(libraryPaths.get(libraryIndex));
			ExternalLocation loc =
				extManager.getUniqueExternalLocation(Library.UNKNOWN, symbol.getName());
			if (loc != null) {
				loc.setName(library, symbol.getName(), SourceType.IMPORTED);
			}
		}
	}
```

`extManager.getExternalLibrary(libraryPaths.get(libraryIndex))` is `null` because the `library

**Comment by ryanmkurtz** [comment]
Thank you, i have a fix incoming.  You are right, it had to do with the library having itself as a dependency.  There is code to check for that, but it was slightly out of sync.

**Comment by ryanmkurtz** [comment]
A couple things to note:
* Batch import will never link external programs to each other.  That is considered "library loading", which is a unique feature of each Loader, and off by default.  The batch importer just uses the default options of each loader.  Library loading is intended to work by importing the main binary, setting the loader options to indicate you want library loading, where to look for libraries, recursion depth, etc.  
* In testing your attached sample, i've realized that we don't properly support `@rpath` .  I guess this just just a relative path from where the imported binary lives?  If you make another ticket for that, i'll try to get that working (i'll do it even if you don't make the ticket, but it would help with bookkeeping).

**Comment by fmagin** [comment]
> Batch import will never link external programs to each other. That is considered "library loading", which is a unique feature of each Loader, and off by default. The batch importer just uses the default options of each loader. Library loading is intended to work by importing the main binary, setting the loader options to indicate you want library loading, where to look for libraries, recursion depth, etc.

Is there some way to fix this up afterwards, or do I need to manually import the files in the correct order? I'd be fine with some script or analysis that needs to run to check if library is now available in the project, sets it as the external program, and then fixes the references

> In testing your attached sample, i've realized that we don't properly support @rpath . I guess this just just a relative path from where the imported binary lives? If you make another ticket for that, i'll try to get that working (i'll do it even if you don't make the ticket, but it would help with bookkeeping).

Done. This mechanism is a bit more complicated if I recall correctly

**Comment by ryanmkurtz** [comment]
> Is there some way to fix this up afterwards, or do I need to manually import the files in the correct order? I'd be fine with some script or analysis that needs to run to check if library is now available in the project, sets it as the external program, and then fixes the references

Yes, I'll respond in your other discussion about it.

**Comment by jdr-ableton** [comment]
@ryanmkurtz what discussion did this response end up in? I am facing a similar issue.
