### ISSUE TITLE
Batch Import Loader precedence

### ISSUE THREAD

**Issue by jonwilson030981** [NationalSecurityAgency/ghidra#595]
When the batch importer runs, it selects the highest priority file-system to process each file, and then runs all loaders which will accept the file. There doesn't appear any option to perform the converse (e.g. all file-systems which accept the file, but only the highest priority loader).

This behaviour can be seen in the [BatchInfo](https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/Base/src/main/java/ghidra/plugins/importer/batch/BatchInfo.java) in the methods **_processAsFS_** and **_processWithLoader_**.

I am looking to solve two problems:

1. What is the best way to create multiple file-systems which process the same file (but in different ways) and allow both to be run during the batch import process?

- I guess this is possible by creating a single file-system which carries out both types of functionality. Whilst this will work for two file-systems developed by the same person, the approach will not work for adding secondary processing to an existing file-type created by someone else. Alternatively it is possible to create a higher priority file-system which wraps the pre-existing one and uses it to perform the original functionality which providing its own, but this approach doesn't scale well.

2. How can I create a loader which will be used as a fallback only if no other higher priority loaders accept the file?

- The only way I can see so far is for the **_findSupportedLoadSpecs_** of a given loader to call into the **_LoaderService.getSupportedLoadSpecs_** to check for any other loaders which will accept the file, but this is not very performant since it essentially means all of the other higher priority loaders are called twice (or more as you add more fallback loaders).

In my case, the file-extensions are not proving a very useful filter since most of the files I am dealing with don't have any extensions. I am hoping that this is possible with the existing batch importer? 

Thanks for any advice you can offer.

**Comment by dev747368** [comment]
How attached are you to the batch importer interface?

At some point, you might be better off going to something like the headless analyzer to do your importing.

**Comment by jonwilson030981** [comment]
I suspected that might be the case. Just wanted to be sure I hadn't missed something.

**Comment by ryanmkurtz** [comment]
@jonwilson030981, did you have any more questions, or can we close this one out?

**Comment by jonwilson030981** [comment]
No thanks for the advice. Sorry didn't realise I was supposed to close it.

**Comment by ryanmkurtz** [comment]
You didn't need to close it...I was just making sure you got all your answers before I closed it.  Either way is fine though.

**Comment by jonwilson030981** [comment]
Thanks Ryan.
