### ISSUE TITLE
EmulatorHelper javadocs

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#5964]
**Describe the bug**
Maybe this is a change between 10.2->10.4, but I could not find the documentation for EmulatorHelper, it's referenced by one of the test classes, but not hyperlinked just the full package name so something thinks it's there but broken.  Did packages get shuffled/renamed?

**Comment by ryanmkurtz** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/eaf6f0e6461642ff8bde6c7606559fcf416d83f4/Ghidra/Framework/Emulation/build.gradle#L16-L22

It's missing 

```groovy
apply from: "$rootProject.projectDir/gradle/javadoc.gradle"
```

**Comment by mumbel** [comment]
Sweet, I didn't know how javadocs got included , now I do.  Glad I wasn't going insane
