### ISSUE TITLE
"Invalid segment start file location: ..." and "Failed to create ... memory block: Part of range ... already exists in memory." errors during MZ file import

### ISSUE THREAD

**Issue by haarlaj** [NationalSecurityAgency/ghidra#5970]
**Describe the bug**
I'm trying to import old DOS EXEs from late 80's to Ghidra. File imported recognizes the files as MZ x86 16bit Real mode files. When I try to import the files, Ghidra imports the file but shows lots of "Invalid segment start file location: " with negative addresses followed by "Failed to create ... memory block: Part of range ... already exists in memory." Ghidra seems to parse the MZ header and relocation table correctly but when the relocation table is applied something goes haywire.

**To Reproduce**
1. Download https://w140.com/tekwiki/images/8/88/063-0228-01.zip
1. Import disk1/CATS.EXE or disk2/UTIL.EXE to ghidra using "Old-style DOS Executable (MZ)" and "x86:LE:16:Real Mode:default"
2. Look to "Import Results Summary" -> "Additional Information"
3. See various "Invalid segment start file location: " with negative values followed by Failed to create "CODE_xxx" memory block: Part of range (.....) already exists in memory."

**Expected behavior**
Successful file import without errors

**Screenshots**
![cats_import](https://github.com/NationalSecurityAgency/ghidra/assets/32195719/eca8bbd0-75ef-47e0-ab84-bf34c793cba9)

**Environment (please complete the following information):**
 - OS: Fedora 38
 - Java Version: openjdk 17.0.8
 - Ghidra Version: 10.4
 - Ghidra Origin: official GitHub distro

**Additional context**
The software is an old measure equipment calibration software from 1989 for 80286/80386 and MS-DOS 3.1 or later.

**Comment by haarlaj** [comment]
Some additional observations about the problem.

I noticed that MemoryMap blocks start from CODE_42 so CODE_0 up to CODE_41 are missing completely.

![MemoryMap](https://github.com/NationalSecurityAgency/ghidra/assets/32195719/c66c4eca-5a52-4a0a-bd90-16393d240a69)

I compared this to the import error log and found that there are exactly 42 "Invalid segment start file location: " errors. 

![importlog](https://github.com/NationalSecurityAgency/ghidra/assets/32195719/4a0ef990-4b42-49df-b042-f96ac24d2521)

Just based on the code. Could there be some bug in how the segment offset is actually calculated? Missing segments are the first ones so is there some negative offset somewhere which offsets the first addresses to negative.

![segmentFileOffset](https://github.com/NationalSecurityAgency/ghidra/assets/32195719/a5102acf-cae7-47f5-979c-aa3f0e63965d)

https://github.com/NationalSecurityAgency/ghidra/blob/5e9cfe2419329094b6a83e9532f7a81f3e39126d/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MzLoader.java#L201C1-L206C5

![addressToFileOffset](https://github.com/NationalSecurityAgency/ghidra/assets/32195719/aebedfde-247d-45b8-abc4-c2e3599db457)

https://github.com/NationalSecurityAgency/ghidra/blob/5e9cfe2419329094b6a83e9532f7a81f3e39126d/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MzLoader.java#L475C1-L478C1

Also the error for the "Failed to create.. ..memory block_ " lines all share the same start address.

**Comment by haarlaj** [comment]
I finally got the ghidra working in debug mode and got some actual numbers. As suspected the first 42 blocks result in negative addresses.

For first codeblock with negative address:
segmentAddr 001d:000:  offset 464 (0x1d0) segment 29 (0x1d)

(segmentAddr.getSegment() - INITIAL_SEGMENT_VAL) & 0xffff:
(29 - 4096) & 0xffff = 61469

The addressToFileOffset function gets inputs as: segment = 61469, offset = 0.
e_cparhdr from dos header is 1664 (0x0680) and paragrahsToBytes(header.e_cparhdr()) returns 26624

In the end addressToFileOffset is evaluated:
(short) 61469 * 16 + 0 + 26624 = -38448
-4067 * 16 + 0 + 26624 = -38448

**Comment by haarlaj** [comment]
I'm pretty sure that the casting to short in `addressToFileOffset` is a bug. The function is used in three places where the segment is already kind of casted to uint16 using `& 0xffff`. The `(short)` will break the address if the segment is larger than 0x8000 as then it is processed as a negative input value. In this case the (short) segment should be replaced with (segment & 0xffff) but just the segment without casting would work fine too.

In my CATS.EXE file this introduces new errors in the processMemoryBlocks. The first SegmentedAddress 001d:0000 will wrap and return a addressToFileOffset 983504 (0xf01f0) which is larger than the file size. This will result for numBytes to be negative and MemoryBlockUtils.createUninitializedBlock throw an error "ghidra.program.model.address.AddressOutOfBoundsException: Address Overflow in subtract: 001d:0000 + 733448".

**Comment by ryanmkurtz** [comment]
I am taking a look at this now...I gotta get my head back into it though...

**Comment by ryanmkurtz** [comment]
I think i agree with you now about the wrong cast to short in `addressToFileOffset()`.  I honestly can't remember why I did that...it solved some problem at the time but I can't remember what.  Fixing that has lead to some other issues that I need to continue debugging...probably tomorrow.

**Comment by ryanmkurtz** [comment]
I believe i fixed the issues described in this issue.  If you have more issues with this binary, please open a new ticket and we can go from there.

**Comment by haarlaj** [comment]
Thanks. I'll do that if something comes up.
