### ISSUE TITLE
Add menu option to datatype editor to open another datatype

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#5975]
When using the datatype editor as an independent window, having the ability to open another datatype without having to switch plugins would help.

**Comment by dragonmacher** [comment]
To clarify, are you asking for the ability to edit a data type of your choosing from an existing editor, or from anywhere for that matter?

**Comment by Wall-AF** [comment]
> To clarify, are you asking for the ability to edit a data type of your choosing from an existing editor?

Yes.

**Comment by Wall-AF** [comment]
Although you've added some help text indicating a key combo for this, it should be added to either the buttons or the RMB popup as well.
