### ISSUE TITLE
Ghidra can not access external usb drive

### ISSUE THREAD

**Issue by cyrianR** [NationalSecurityAgency/ghidra#5976]
Hello, 

I've just installed ghidra using "snap install ghidra" but I'm facing an issue : I can not create a new project or import a file on my external usb drive, it just doesn't appear in the file explorer in ghidra. I didn't manage to find a similar issue but I guess it may be because of the way I installed ghidra.

Thank you in advance for your help.

**Comment by ryanmkurtz** [comment]
If your usb drive is mounted under `/media/`, can you just click on `My Computer` in the Ghidra file browser window, and then navigate to your usb drive that way?

**Comment by cyrianR** [comment]
> If your usb drive is mounted under `/media/`, can you just click on `My Computer` in the Ghidra file browser window, and then navigate to your usb drive that way?

That's what I tried, but there is just nothing in "My Computer / File system root / media /" when opening in Ghidra file browser. Although, I can find my usb drive as usual on my computer's file browser in /media/.

**Comment by ryanmkurtz** [comment]
Unfortunately i cannot reproduce this.  I tried both Ubuntu 22.04 and 23.10 with 2 different versions of Ghidra, and I was able to navigate to the `/media` directory and import files from it.  Specifically, I tested by mounting and importing the VirtualBox Guest Additions.

**Comment by cyrianR** [comment]
Ok thank you though, I will try again and come back to you if I make progress.

**Comment by ryanmkurtz** [comment]
Sounds good.  I am going to close it to indicate we are not actively working on it but please do come back with updates.

**Comment by trainer400** [comment]
Same problem here. I cannot even see the external USB from ghidra whereas it works fine with gnome and others
