### ISSUE TITLE
GhidraDevPlugin complains about JYTHON_VERSION_2_7 

### ISSUE THREAD

**Issue by antoniovazquezblanco** [NationalSecurityAgency/ghidra#5980]
**Describe the bug**
When trying to compile GhidraDevPlugin, eclipse complains:
```
JYTHON_VERSION_2_7 cannot be resolved or is not a field
```

This is because there is a dependency on PyDev and it has dropped support for python 2 in https://github.com/fabioz/Pydev/commit/5e91251821eaee2b1e8f8e5c3eca89de97441fe5 (Aug 2022).

**To Reproduce**
1. Fresh install of Eclipse
2. Install deps
3. Attempt to build GhidraDevPlugin

**Expected behavior**
A clean compilation.

**Screenshots**
NA

**Attachments**
NA

**Environment (please complete the following information):**
 - OS: Win 10 but I believe it is platform independent
 - Ghidra Version: Ghidra master branch (https://github.com/antoniovazquezblanco/ghidra/commit/bae8952aff4b60ef143252589c149288e3c0f742)
 - Ghidra Origin: Locally built from source

**Additional context**
NA

**Comment by ryanmkurtz** [comment]
Thank you...I will update the documentation and relevant error/status messages which say what version of PyDev we support.

**Comment by antoniovazquezblanco** [comment]
Thank you very much!
