### ISSUE TITLE
GhidraDevPlugin fails to link project to a Ghidra installation

### ISSUE THREAD

**Issue by antoniovazquezblanco** [NationalSecurityAgency/ghidra#5981]
**Describe the bug**
While linking a project to a Ghidra installation I get the "application.properties" not found error.
![imagen](https://github.com/NationalSecurityAgency/ghidra/assets/304193/78ce0635-eb17-43bd-a3bb-b998b4cdcbfb)

The exception raises in https://github.com/NationalSecurityAgency/ghidra/blob/bae8952aff4b60ef143252589c149288e3c0f742/GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin/src/main/java/ghidradev/ghidraprojectcreator/utils/GhidraProjectUtils.java#L361.

This is because my project is linked against an old installation that no longer exists.
I've also added some debug code to understand what is happening:
![imagen](https://github.com/NationalSecurityAgency/ghidra/assets/304193/cf4bb503-f690-4759-b65c-37357e06a0b5)

The output of the debug code:
![imagen](https://github.com/NationalSecurityAgency/ghidra/assets/304193/d2610f1b-ecee-49f9-907e-7cd561fa34d7)

**To Reproduce**
1. Go to eclipse and create a new Ghidra module plugin.
2. Move or rename your existing Ghidra installation.
3. Link the plugin project against the new Ghidra installation...

**Expected behavior**
To not see the exception and correctly link the project.

**Screenshots**
Added above.

**Attachments**
NA

**Environment (please complete the following information):**
 - OS: Win 10
 - Java Version: Adoptium JDK 17
 - Ghidra Version: https://github.com/NationalSecurityAgency/ghidra/commit/bae8952aff4b60ef143252589c149288e3c0f742
 - Ghidra Origin: locally built

**Additional context**
I can submit a patch that not only checks that the `IFolder` exists but that it also checks via `File` API to ensure that the Ghidra installation really exists.

Another option may be to directly try to create a `GhidraApplicationLayout` and if an exception is thrown, catch it and continue as the old installation is not present...

Any pointers?
Thanks

**Comment by ryanmkurtz** [comment]
Thanks, I'll make it handle this situation more gracefully.

**Comment by ryanmkurtz** [comment]
I think i have a fix working.  Turns out I didn't really need the layout....the path of the existing Ghidra project folder was good enough.

**Comment by antoniovazquezblanco** [comment]
Nice to hear that! Will test as soon as you upload. Thanks for the fast response!

**Comment by antoniovazquezblanco** [comment]
Thank you very much!
