### ISSUE TITLE
PDB.EXE Memory leaks due to improper use of COM interfaces

### ISSUE THREAD

**Issue by BlueSkeye** [NationalSecurityAgency/ghidra#599]
**Describe the bug**
PDB.EXE uses the DIA SDK to read pdb files. This is a COM based set of interfaces. COM interfaces MUST be released when of no more use. The current version of the source code doesn't enforce this rule.

Consequently objects allocated by the DIA SDK are not released until the PDB.EXE program comes to an end. This may lead to huge memory use for pdb files of some importance.

**To Reproduce**
1. Download symbols from Microsoft symbols server for NTOSKRNL.EXE version 10.0.17763.475
notice the resulting file size is 7,27 MBytes
2. Execute PDB.EXE on the downloaded file.
3. Under Visuel studio the peak memory consumption is 2,6 GBytes which is a 361 to 1 ratio compared to input file size !!!

**Expected behavior**
Release COM object interfaces when of no more use..

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 (not relevant though)
 - Java Version: N/A
 - Ghidra Version: N/A

**Additional context**
N/A

**Comment by ghizard** [comment]
Fixed by #674
