### ISSUE TITLE
Trouble building ghidra 

### ISSUE THREAD

**Issue by lcoriolan** [NationalSecurityAgency/ghidra#5991]
user@users-MacBook-Pro ghidra % gradle buildGhidra
> Configure project :
Gradle: 8.4
OS: Mac OS X
Arch: aarch64
Using platform: mac_arm_64

> Task :Generic:compileJava FAILED
/Users/USER/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/TreeValueSortedMap.java:653: error: types List<Entry<K,V>> and Deque<Entry<K,V>> are incompatible;
        protected class ValueSortedTreeMapEntrySet extends AbstractSet<Entry<K, V>>
                  ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in class TreeValueSortedMap
    V extends Object declared in class TreeValueSortedMap
/Users/user/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/TreeValueSortedMap.java:973: error: types List<K> and Deque<K> are incompatible;
        protected class ValueSortedTreeMapKeySet extends AbstractSet<K>
                  ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in class TreeValueSortedMap
/Users/user/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/TreeValueSortedMap.java:1211: error: types Deque<V> and List<V> are incompatible;
        protected class ValueSortedTreeMapValues extends AbstractCollection<V>
                  ^
  both define reversed(), but with unrelated return types
  where V is a type-variable:
    V extends Object declared in class TreeValueSortedMap
/Users/user/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/ValueSortedMap.java:39: error: types Deque<Entry<K,V>> and List<Entry<K,V>> are incompatible;
        public interface ValueSortedMapEntryList<K, V>
               ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in interface ValueSortedMapEntryList
    V extends Object declared in interface ValueSortedMapEntryList
/Users/user/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/ValueSortedMap.java:47: error: types Deque<K> and List<K> are incompatible;
        public interface ValueSortedMapKeyList<K> extends Set<K>, List<K>, Deque<K> {
               ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in interface ValueSortedMapKeyList
/Users/user/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/RestrictedValueSortedMap.java:253: error: types List<Entry<K,V>> and Deque<Entry<K,V>> are incompatible;
        public class RestrictedValueSortedMapEntryList implements ValueSortedMapEntryList<K, V> {
               ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in class RestrictedValueSortedMap
    V extends Object declared in class RestrictedValueSortedMap
/Users/user/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/RestrictedValueSortedMap.java:548: error: types List<K> and Deque<K> are incompatible;
        public class RestrictedValueSortedMapKeyList implements ValueSortedMapKeyList<K> {
               ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in class RestrictedValueSortedMap
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Generic:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 7s
4 actionable tasks: 1 executed, 3 up-to-date
USER@USERs-MacBook-Pro ghidra %

**Comment by mumbel** [comment]
Use an older version of Java and Gradle

**Comment by lcoriolan** [comment]
Yup I downgraded my version of java and fixed the issue

**Comment by KostyaSha** [comment]
It doesn't work with 17 and 21, but fine with 18.

**Comment by ryanmkurtz** [comment]
It should definitely work with JDK 17...that is our officially supported version and the one we test with every day.

**Comment by KostyaSha** [comment]
I have tried with 
```
$ java -version
java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
```
What exact version do you use?

**Comment by KostyaSha** [comment]
Updated to 17.0.9 and probably it builds fine (if cache is not making party here).

**Comment by nuschpl** [comment]
For me it does work neither on stable Adoptium JDK 17 nor the nigtly of of its JDK 17. Do you have any specific version it should work ?
Also is the bug the same as #5968 ? I've added potential reason [there](https://github.com/NationalSecurityAgency/ghidra/discussions/5968#discussioncomment-7964948)

**Comment by ryanmkurtz** [comment]
Ghidra should currently build on JDK 17 through 20.  JDK 21 is not currently supported.
