### ISSUE TITLE
ERROR: Multiple modules collided with the same name

### ISSUE THREAD

**Issue by annetteshajan** [NationalSecurityAgency/ghidra#5993]
Hi 
I am trying to write a plugin and install it in ghidra.
The method I follow is:
1. Write my plugin and build it with the GhidraDev module export function (which converts it to a zip)
2. I open ghidra from eclipse and I go to File -> Install Extensions and add the zip file
3. It asks me to restart ghidra. So I close ghidra and reopen it from eclipse.
Here it doesn't open claiming that "Multiple modules collided with the same name: <Pluginname>"
The two collisions are coming from <home>/.ghidra/.ghidra_10.5_DEV/Extensions/<Pluginname> and the actual location where I write the plugin.
I understand this issue has been brought up with #2193 . It asks to delete this folder which is getting cached.
The error doesn't come up when I delete the folder but the plugin itself is not installed when I restart ghidra in this case.
Any suggestions would help!

**Comment by ryanmkurtz** [comment]
The problem is when you launch your module project from Eclipse, it launches with that extension implicitly installed.  But since you also installed it via the front end GUI, that's a 2nd instance which causes the problem.
