### ISSUE TITLE
movdir64b disassembly 

### ISSUE THREAD

**Issue by irozents** [NationalSecurityAgency/ghidra#5997]
Hello,
As far as I understand, movdir64b isn't supported yet (?). Due to that, the decompiled function is broken into two separate functions, which makes the decompilation problematic to follow. Is there a way to let ghidra know to ignore the unsupported opcode and don't lose the function context, resulting in a complete decompiled function with a whole instead of two separate ones? 

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/94042792/2944693e-ecb4-48e0-88c3-33e6f0a6b4d5)

**Environment (please complete the following information):**
 - OS: Win 11
 - Java Version: JDK
 - Ghidra Version: openjdk 17.0.9 2023-10-17
 - Ghidra Origin: official GitHub distro
ghidra version: 10.4

Thanks!

**Comment by GhidorahRex** [comment]
I implemented a quick and dirty `movdir64b` instruction in sleigh. It's just a pcodeop, so nothing fancy. I added it around line 5575 or so of `ia.sinc`, but it should be able to be added almost anywhere. You can add that and then reload your program and it should disassemble.

```
m512: "64B ptr" Mem	    is Mem      { export *:64 Mem; }
define pcodeop movdir64b;
:MOVDIR64B    Reg16, m512 is $(LONGMODE_OFF) & vexMode=0 & $(PRE_66) & addrsize=0 & byte=0x0F; byte=0x38; byte=0xF8; Reg16 ... & m512 {
	movdir64b(Reg16, m512);
}
:MOVDIR64B    Reg32, m512 is $(LONGMODE_OFF) & vexMode=0 & $(PRE_66) & addrsize=1 & byte=0x0F; byte=0x38; byte=0xF8; Reg32 ... & m512 {
	movdir64b(Reg32, m512);
}

@ifdef IA64
:MOVDIR64B    Reg64, m512 is $(LONGMODE_ON) & vexMode=0 & $(PRE_66) & addrsize=1 & byte=0x0F; byte=0x38; byte=0xF8; Reg64 ... & m512 {
	movdir64b(Reg64, m512);
}

:MOVDIR64B    Reg64, m512 is $(LONGMODE_ON) & vexMode=0 & $(PRE_66) & byte=0x0F; byte=0x38; byte=0xF8; Reg64 ... & m512 {
	movdir64b(Reg64, m512);
}
@endif
```
