### ISSUE TITLE
Share an Eclipse Formater Profile

### ISSUE THREAD

**Issue by plucia-mitre** [NationalSecurityAgency/ghidra#5999]
Eclipse supports exporting and importing formatter profiles (Window>Preferences>Java>Code Style>Formatter). It'd be super handy to have an "official" formatter as part of the "Ghidra Java Coding Standards" page (downloadable) so Ghidra-specific standards can be applied automatically (as much as possible).

**Comment by dragonmacher** [comment]
This is something that we should include in the release.

(Drop the .txt extension after downloading)

[GhidraEclipseFormatter.xml.txt](https://github.com/NationalSecurityAgency/ghidra/files/13531863/GhidraEclipseFormatter.xml.txt)

**Comment by astrelsky** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/master/eclipse/GhidraEclipseFormatter.xml

**Comment by plucia-mitre** [comment]
Thanks for the link @astrelsky!

For reference, I was looking at this page and didn't see any reference to 
 the linked-to file: https://github.com/NationalSecurityAgency/ghidra/blob/master/GhidraDocs/GhidraCodingStandards.html

If/when the formatter profile is made part of the release it would be nice to update this html page with a link and/or more explicit reference.

**Comment by ryanmkurtz** [comment]
@plucia-mitre, are you wanting the formatter for use with the GhidraDev Eclipse plugin, or for development of Ghidra from within our git repo?

**Comment by plucia-mitre** [comment]
Both really. I have been doing both types of development recently.
