### ISSUE TITLE
Hide opcode bytes in listing?

### ISSUE THREAD

**Issue by Andoryuuta** [NationalSecurityAgency/ghidra#60]
Is there an option/way to disable showing the opcode bytes in the listing view?

I've been able to use a temporary workaround/solution to visually hide them, but it's not great:

1. Set the `Listing Fields -> Bytes Field -> Maximum Lines To Display` option to `1` to get rid of the extra newlines in the listing view.
2. Set the `Listing Display -> Bytes` color to the same as the background to visually hide the bytes.
![image](https://user-images.githubusercontent.com/8594162/53904104-295f5c00-3ffa-11e9-9e1a-554c31d56be5.png)

**Comment by yakamoz147** [comment]
Check out this button on the top right of the listing window. You can do all of that over there...

![image](https://user-images.githubusercontent.com/37738506/53904770-2048ac00-4047-11e9-92f5-bb363e466993.png)

**Comment by Andoryuuta** [comment]
@yakamoz147 Ah, perfect. Thank you!
