### ISSUE TITLE
Can attach values be used in disassembly actions?

### ISSUE THREAD

**Issue by jamchamb** [NationalSecurityAgency/ghidra#601]
The constructors documentation notes that attach values can't be used for constraints, but it's not clear whether they should be usable in the disassembly action section.

I have these attach values:

```
define token opbyte (8)
    ...
    dsp0_3 = (0,2)
;
attach values [ dsp0_3 ] [ 8 9 10 3 4 5 6 7 ];
```

When using `dsp0_3` in the display section it shows the expected attach value, but when I use it in a disassembly action like `[ dsp = inst_next + dsp0_3; ]` it always seems take on a value of 0.

**Comment by emteere** [comment]
I don't think the values in the attach can be used in the [action] as you are doing, although I don't think I've ever seen it used that way.
When you say it always comes out as 0, is that when the bits in (0,2) are b000?  I'm assuming it changes to another value if the bits are something else.

I would create a sub-constructor that computes the correct value for you based on the value of the bits.  I'm assuming you want to export an address computed by the action for display.  Unless there are many cases it will just be a little more verbose with a slightly large .sla file.

If the value of dsp doesn't need to be displayed, or If you really don't like doing it this way, you can just do the calculation in the instruction semantics and the constant address calculation or data flow simplification will replace the address with the correct one or propagate the calculation correctly.  Your attach should work there.

**Comment by jamchamb** [comment]
> When you say it always comes out as 0, is that when the bits in (0,2) are b000? I'm assuming it changes to another value if the bits are something else.

Correct, I should fix that to say it takes on the untranslated value. The initial issue I was running into with making a subconstructor was that modulo doesn't seem to be supported in the disassembly action either:
 
```
    [java] rx62t.sinc line 218: expecting RPAREN, unexpected token: '%':
    [java] dsp3: dsp is dsp0_3 [ dsp = inst_start + (((dsp0_3 - 3) % 8) + 3); ] {
    [java] --------------------------------------------------------^
```

I figured out a clunkier way to do the calculation but I think for more complicated value lists this would be very difficult:

```
dsp3: dsp is dsp0_3 [ dsp = inst_start + ((dsp0_3 + 5) - (((dsp0_3 + 5)/8))*8) + 3; ] {
	local tmp:4 = inst_start + (((zext(dsp0_3:1) - 3) % 8) + 3);
	export *[ram]:4 tmp;
}
```

**Comment by emteere** [comment]
If it is computable, then I would go with what you have done.  Glad you figured it out.  Could knowing where the next instruction starts based on the bytes finally consumed by the instruction decode have helped (inst_next) have helped with your computation?

For a more complicated list you can just do:

```
dsp3: dsp is dsp0_3=0 [ dsp = inst_start + 8; ]    { export *[ram]:4 dsp; }
dsp3: dsp is dsp0_3=1 [ dsp = inst_start + 9; ]    { export *[ram]:4 dsp; }
...
dsp3: dsp is dsp0_3=7 [ dsp = inst_start + 7; ]    { export *[ram]:4 dsp; }
```

**Comment by jamchamb** [comment]
Got it, thanks for the clarification.
