### ISSUE TITLE
SLEIGH: How to Check If Two Operands Are the Same Register?

### ISSUE THREAD

**Issue by VGKintsugi** [NationalSecurityAgency/ghidra#602]
I am working on a SuperH SH-2 processor module. I need to check if operand register N does not equal operand register M. The pseudo code is as follows:

`mov.b	@Rm+,Rn`

    void MOVBP (int m, int n)
    {
        R[n] = Read_8 (R[m]);
        if ((R[n] & 0x80) == 0)
            R[n] &= 0x000000FF;
        else
            R[n] |= 0xFFFFFF00;

        if (n != m)
            R[m] += 1;

        PC += 2;
    }
I am stumped as to how to do this. My SLEIGH definition is as follows:

    :mov.b  @rm_04_07+,rn_08_11  is opcode_12_15=0b0110 & rn_08_11 & rm_04_07 & opcode_00_03=0b0100 
    {
        rn_08_11 =  sext(*:1 rm_04_07);

        # BUGBUG: check rn != rm
        rm_04_07 = rm_04_07 + 1;
    }

rm_04_07 != rm_04_07 will obviously check the values of the registers which is not what I want. In C I want something like &rm_04_07 != &rm_04_07. How can I do this in SLEIGH? Thanks in advance.

**Comment by mumbel** [comment]
I think just use another field not attached is probably the correct way
```
:mov.b  @rm_04_07+,rn_08_11  is opcode_12_15=0b0110 & rn_08_11 & rm_04_07 & opcode_00_03=0b0100 & opcode_04_07 & opcode_08_11
{
    rn_08_11 =  sext(*:1 rm_04_07);

    # BUGBUG: check rn != rm
    if (op_04_07 == op_08_11) trap_or_goto_or_whatever();
    rm_04_07 = rm_04_07 + 1;
}
```
guess it depends why you need/want UNPREDICTABLE checks in the sinc and how it gets handled.  You could even do `op_04_07!=op_08_11` I think in the bit pattern and then the instruction wouldn't even disassemble

**Comment by VGKintsugi** [comment]
Thank you for the quick reply, I will give that a shot. I'm just trying to match the instruction definition correctly.
