### ISSUE TITLE
Version tracking unregistered option

### ISSUE THREAD

**Issue by Nemoumbra** [NationalSecurityAgency/ghidra#6026]
The text from one of the VT windows is trimmed and hovering doesn't result in the full string appearing. Function Minimum what? Size in bytes?

**To Reproduce**
Go to the Version Tracking tool and open the Version tracking wizard > Exact function bytes

**Expected behavior**
The string "Unregistered option" hints that something wasn't polished. Either it's just the text entry not configured, or maybe something else too.

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/62447396/4e0fd8c0-609e-4264-b6cb-9fb75a9c4cda)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: jdk-19.0.2
 - Ghidra Version: 10.4
 - Ghidra Origin: official GitHub distro

**Comment by dragonmacher** [comment]
There are multiple issues happening here.

1.  The clipped text should read `Function Minimum Size`
2.  The hover for the text should describe the option, or at least show the full text
3.  The text does not actually say, but it is referring to the number of addresses in the function body, which is the number of bytes

Regarding 1), I am not  seeing clipped text in my environment for any of Ghidra's themes, so this is clearly dependent upon the user's setup.

Number 2) is apparently an oversight in how VT adds options for correlators.   When adding options, the correlator should be registering any options it provides.    Additionally, the code that creates the hover should be smarter about the text used and should not say 'Ungegistered Option'.
