### ISSUE TITLE
Unhandled exception if MZ Loader tried to load file smaller than header says it is.

### ISSUE THREAD

**Issue by Hordeking** [NationalSecurityAgency/ghidra#6029]
Ghidra appears to look at the MZ header's reported exe size and proceeds to load that many blocks from the file we're looking at. If the file isn't at least as big as the header says it is, the loader throws an exception. It works fine if the file is larger than the header says.

Fixing the header to report the actual size of the file (or exec data) allows the loader to do its thing. Padding the file with bytes until it reaches the header's reported size also works.

**To Reproduce**

1. Find an exe (MZ header+exec data) with a header that reports a larger total size than the file, assuming the rest of the exe is correct and complete.
3. Load it with the MZ 16-bit loader
4. Watch it crash.

Note: Step one applies to standalone files. Ghidra will analyze the MZ stub of a PE file because there's data after the MZ such that Ghidra can load as much data as the header reports. If you extract the stub and put it in a standalone file and load it, it *will* cause Ghidra to throw the exception.

**Expected behavior**
A check that the file size is not smaller than the header-reported size, offers a recommendation if it is, and asks the user how to proceed (fail, ignore the header size in favor of the file size, enter a custom size, etc.).

**Environment (please complete the following information):**
 - Linux Mint 21.2
 - Java Version: 17.0.9
 - Ghidra Version: 10.4
 - Ghidra Origin: Official GitHub Distro

**Additional context**

I noticed this bug when I separated the MSDOS stub exe from the PE exec (setup.exe from windows xp disk, probably anything else build by visual studio in that era). The actual stub is only 0x79 (0d121) bytes long, but the header itself gives the size as 0x490 bytes, well past the end of the MZ exe stub, and several sectors into the PE portion. The header size is correct at 0x40, so DOS knows where to find the exec data. My guess is that it just loads the whole file and only checks the MZ sig and the header size, does any relocations required, and jumps straight to the code.

If I correct the size reported in the header to match the actual size of the stub, ghidra digests it with no issues. If I feed it the whole MZ+PE and analyze it as an MZ, it also works just fine.

**Comment by ryanmkurtz** [comment]
> If I correct the size reported in the header to match the actual size of the stub, ghidra digests it with no issues. If I feed it the whole MZ+PE and analyze it as an MZ, it also works just fine.

I'm not sure I see the bug here.  My understanding (please correct me if I'm wrong) is that you did surgery on a PE file, but didn't leave it in a consistent state.  Generally speaking we only try to load things like this if the actual Windows loader can load it...otherwise, we just consider it corrupt and the failure is the desired outcome.  

I am going to close this ticket, but I will reopen it if you make a strong case why we should support this specific type of header inconsistency.

**Comment by Hordeking** [comment]
>  My understanding (please correct me if I'm wrong) is that you did surgery on a PE file, but didn't leave it in a consistent state.
Incorrect. This is a stub whose filesize field is supposed to indicate the size of the stub itself, but does not. It executes perfectly in DOS, regardless of the size of that field. DOS literally does not care what bytes 02-03 and 04-05 say the executable's size is. It just loads the file using int 21h to wherever it wants, does the relocations, and jumps to the entry point. 

Ghidra however DOES care about what the filesize field says, even when the filesystem says something different. It probably allocates space based on that field, and when it gets to the end of that allocated space but the file itself hits an eof (which it will be if you cut off the PE stuff), the tool crashes.

**This is absolutely a bug.** Behavior in a live system (DOS) effectively tells me that the filesize in the MZ header is potentially not to be trusted. Ghidra should at least prompt the user for how to handle that situation and handle it gracefully instead of crashing without giving a clear reason. If someone is trying to analyze a fat executable, and they isolate just the one they want from it for any reason, they should still be able to analyze it without any further surgery, assuming that the rest of the file is valid.

**Comment by Hordeking** [comment]
A correction to the above when running the bare stub.
- FreeDOS, DOSemu, and DOSBox don't care and go by the filesystem size.
- MSDOS 6.22 checks it and actually throws an error about the exe being invalid.
- I didn't check on a windows system, but I assume it probably just looks for the PE signature or something and goes from there, ignoring the DOS stub entirely.
- A custom exe loader from an old booter game I've been working on reversing (it uses an exe format, but isn't using DOS), also doesn't check the size in the header, which reports a smaller executable than the filesystem does (and thus would not run into this issue anyway).

So what we have here is more modern software seems to potentially treat the exe size as untrusted. MSDOS probably just throws the error when it hits EOF earlier than it was expecting from the filesize field.

I still think it should be considered a bug due to the fact that it throws an exception without really saying why, different systems handle this differently, and could easily just be handled by a simple check of "if ( header.filesize < os.filesize ) { showmessage(); failgracefully(); }"

**Comment by ryanmkurtz** [comment]
Ok, I can ensure that it loads, and put out a warning if there is a mismatch.

**Comment by Hordeking** [comment]
That seems like a pretty solution to me.
