### ISSUE TITLE
InvalidPathException: Illegal char <"> at index 0:

### ISSUE THREAD

**Issue by skavengeer** [NationalSecurityAgency/ghidra#6030]
**Describe the bug**
 
We close insure but Ghidra ver 10.4 have a big problem=
Do not work when open file
"
Illegal char <"> at index 0: ...............java 
" 
I am sure  My java path is correct. My software when using java, work corecly.

Build Date: 2023-Sep-28 1301 EDT
Ghidra Version: 10.4
Java Home: C:\Program Files\Java\jdk-17.0.3.1
JVM Version: Oracle Corporation 17.0.3.1
OS: Windows 10 10.0 amd64

**Comment by ryanmkurtz** [comment]
Duplicate of #5894
