### ISSUE TITLE
Powershell 

### ISSUE THREAD

**Issue by SleepTheGod** [NationalSecurityAgency/ghidra#6031]
param(
    [string]$command
)

# Path to the Ghidra installation directory
$ghidraInstallDir = "$env:ProgramFiles\Ghidra"

# Check if Ghidra is installed
$ghidraInstalled = Test-Path $ghidraInstallDir

if (-not $ghidraInstalled) {
    Write-Host "Ghidra is not installed. Downloading and installing..."

    # Download Ghidra from the GitHub repository
    $ghidraDownloadURL = "https://github.com/NationalSecurityAgency/ghidra/archive/master.zip"
    $downloadPath = "$env:TEMP\ghidra.zip"
    Invoke-WebRequest -Uri $ghidraDownloadURL -OutFile $downloadPath

    # Extract Ghidra to the installation directory
    Expand-Archive -Path $downloadPath -DestinationPath $ghidraInstallDir
    Rename-Item -Path "$ghidraInstallDir\ghidra-master" -NewName "ghidra"

    # Remove the downloaded zip file
    Remove-Item -Path $downloadPath

    Write-Host "Ghidra has been installed to $ghidraInstallDir"
}

switch ($command) {
    "decompile" {
        # Here, you can specify the command or arguments to run Ghidra's decompile functionality
        # Example: Invoke-Expression "$ghidraInstallDir\ghidra\ghidra run-decompile-command"
        Write-Host "Running Ghidra's decompile functionality..."
    }
    "analyze" {
        # Here, you can specify the command or arguments to run Ghidra's analysis functionality
        # Example: Invoke-Expression "$ghidraInstallDir\ghidra\ghidra run-analyze-command"
        Write-Host "Running Ghidra's analysis functionality..."
    }
    "help" {
        Write-Host "Ghidra PowerShell Tool"
        Write-Host "Usage: ghidra <command>"
        Write-Host ""
        Write-Host "Available commands:"
        Write-Host "  decompile - Run Ghidra's decompile functionality"
        Write-Host "  analyze   - Run Ghidra's analysis functionality"
    }
    default {
        Write-Host "Command not recognized. Use 'ghidra help' for available commands."
    }
}

**Comment by ryanmkurtz** [comment]
I'm not sure the intent of this ticket ,so I am going to close it.  If you edit it to provide more context or clarify a question, we can always reopen it.

**Comment by SleepTheGod** [comment]
It is a way to port ghidra in powershell I figured I would share it
