### ISSUE TITLE
Decompiler exception in x86 code (regression)

### ISSUE THREAD

**Issue by sev-** [NationalSecurityAgency/ghidra#6034]
**Describe the bug**
Decompiler crashes when attempting to process one particular function. Happened between 10.3 and 10.3.3, still present in 10.4

**To Reproduce**
1. Create new project
2. Import the attached file (rename it to MAPNAV.DLL), it is a 16-bit NE executable. [MAPNAV.DLL](https://github.com/NationalSecurityAgency/ghidra/assets/365188/e5e22ac2-4adc-472b-b0d2-dd974039b748)

3. Start Ghidra and run autoanalysis with default parameters
4. Navigate to `_MAPNAV_MNEW` function in Exports
5. The decompiler window shows:

```
Exception while decompiling 1008:0041: Decompiler process died
```

**Expected behavior**
In Ghidra 10.3 (May 10) the function is being decompiled

```C++
undefined4 __stdcall16far
_MAPNAV_MNEW(undefined2 param_1,undefined2 param_2,undefined4 param_3,undefined2 param_4,
            undefined2 param_5)

{
  code **ppcVar1;
  int iVar2;
  undefined2 uVar3;
  undefined2 uVar4;
```

**Attachments**
[MAPNAV.DLL](https://github.com/NationalSecurityAgency/ghidra/assets/365188/e5e22ac2-4adc-472b-b0d2-dd974039b748) (20 kb)

**Environment (please complete the following information):**
 - OS: macOS 14.1 Sonoma
 - Java Version: 21.0.1
 - Ghidra Version: 10.3.3 and later
 - Ghidra Origin: official GitHub distro

**Additional context**

**Comment by ryanmkurtz** [comment]
Not sure why but I cannot download your attachment.

**Comment by sev-** [comment]
As I mentioned, you have to rename it. Download it as a blob, because I had to add .png extension to it due to limitation of GitHub which whitelist possible file names

**Comment by ryanmkurtz** [comment]
Issue is still present in the `master` branch.

**Comment by greenozon** [comment]
Regarding
>Navigate to _MAPNAV_NEW function in Exports
there is no such API, did you mean _MAPNAV_MNEW ?


![image](https://github.com/NationalSecurityAgency/ghidra/assets/765343/177958a2-e883-4721-93e1-5153aefdde43)

**Comment by sev-** [comment]
Yes, it was a typo. Shown correctly on the 10.3 decompiler output, though

**Comment by greenozon** [comment]
the freshly baked version 11.0 still has this bug:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/765343/356cae8c-56e8-4db1-a234-693ffefe04f7)
