### ISSUE TITLE
Can't detect a compiler for a PE binary with a custom MS-DOS stub

### ISSUE THREAD

**Issue by nm004** [NationalSecurityAgency/ghidra#6035]
**Describe the bug**
Ghidra is unable to detect a compiler for a PE binary with a custom MS-DOS stub, and thus cannot do some analysis, e.g. "Windows x86 PE RTTI Analyzer". In a real world example, [Steam](https://store.steampowered.com/about/) by Valve Corporation, namely `steam.exe`, contains a custom MS-DOS stub and third-party games published via Steam also contain custom MS-DOS stub.

**To Reproduce**
1. Open Project
2. Import PE binary with a custom MS-DOS stub
3. See About program.exe

**Expected behavior**
The compiler is set `visualstudio:unknown`

**Screenshots**
![Screenshot-from-2023-12-21-01-07-44](https://github.com/NationalSecurityAgency/ghidra/assets/99280467/8db5cd2b-b1ce-4e3f-92e3-d78621d005cc)

The picture above shows that the program `steam.exe` includes strings of MSVC mangled names, but ghidra says the compiler is unknown.

**Environment (please complete the following information):**
 - OS: Windows 11 / Linux
 - Java Version: 21
 - Ghidra Version: 10.4
 - Ghidra Origin: official GitHub distro

**Additional context**
This issue affects both 32 bit PE binary and 64 bit PE binary.

**Comment by nm004** [comment]
I found Ghidra currently determine the kind of compiler by searching "Rich header".
https://github.com/NationalSecurityAgency/ghidra/blob/6242fda158fed6c7dbbd6928a4a74371a212c373/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/PeLoader.java#L991

I am afraid that I don't know of a general fix for this. As a workaround, I can swap a custom MS-DOS header with MSVC header.

**Comment by dev747368** [comment]
If you know the compiler name that you think Ghidra should be using for your binary, you can edit that value before running any analysis by going to Edit | Options for 'yourbinary', Program Information -> Compiler.

**Comment by nm004** [comment]
> If you know the compiler name that you think Ghidra should be using for your binary, you can edit that value before running any analysis by going to Edit | Options for 'yourbinary', Program Information -> Compiler.

Thank you for the tip! It's very helpful. I'm going to close this issue for now because this way let Ghidra to be able to do RTTI analysis.
