### ISSUE TITLE
ActionContext changed from class to interface debugger

### ISSUE THREAD

**Issue by mfthomps** [NationalSecurityAgency/ghidra#6041]
I have a Debugger plugin that was last built with Ghidra 10.3
Since then, ActionContext was changed from a class to an interface (though https://ghidra.re/ghidra_docs/api/docking/ActionContext.html reports it is still a class).
My plugin defines a class that extends ActionContext to manage items in a panel list as follows:
import docking.ActionContext;

```
public class RESimBookMarkActionContext extends ActionContext {
    private final RESimBookMarksRow row;
    public RESimBookMarkActionContext(RESimBookMarksProvider provider, RESimBookMarksRow row,
            Component sourceComponent) {
        super(provider, row, sourceComponent);
        this.row = row;
    }
    public RESimBookMarksRow getRow() {
        return row;
    }
}
```
Is there a class that replaces the old ActionContext or do I need to have my class implement the interface?

**Comment by dragonmacher** [comment]
It was replaced with `docking.DefaultActionContext`.

**Comment by mfthomps** [comment]
Thanks!
