### ISSUE TITLE
Wrong to write "work from JDK 17+"

### ISSUE THREAD

**Issue by gmy77** [NationalSecurityAgency/ghidra#6046]
It's wrong to write that it works with JDK 17+ or 18+ or 19+. I installed 5 different versions from 18, 19, 20, 21, etc., upwards, and none, I repeat, none worked. The only unique and unrepeatable one that works is Oracle JDK 17.0.9+11_windows-x64_bin.exe. I went crazy finding a working distribution, thinking that the term 17+ meant from release 17 upwards... would be fine. **But NO. It means 17 AND THAT'S IT**.

**Comment by d-millar** [comment]
@gmy77 Sorry to hear you're having problems - with luck, we can help.  I think we may need more specifics, however.  What version of Windows are you runnning?  Which JDKs?  How do you install them?  What version of Ghidra?  Are you having problems running the Ghidra distribution?  Or building it from source?

Just as a point of reference, I just installed the Oracle JDKs (17, 18, 19, 20, 21) and the Amazon JDKs (17, 21) on Windows Server 2019.  The current Ghidra 11.0 release run from the distribution, launches cleanly, and appears to have no problems for all of those, so am guessing your setup differs in some important way.
