### ISSUE TITLE
PIC18 misleading decompilation when called function changes carry bit 

### ISSUE THREAD

**Issue by fidgetingbits** [NationalSecurityAgency/ghidra#606]
**Describe the bug** 

When working with PIC18, the decompiler seems to not correctly represent the carry bit
assignment across function returns.

**To Reproduce**

If we look at the following decompilation segment of a function:

```
      bVar4 = CARRY1(DAT_DATA_01b0,bVar5);
      DAT_DATA_01a9 = DAT_DATA_01b0 + bVar5;
      uVar2 = 8;
      do {
        uVar2 = FUN_CODE_003446(uVar2);
      } while (bVar4);
```

I would expect the loop, if bound by `bVar4`, to be indicated that `bVar4` is
changing, however nothing is being done with `bVar4` so it seems wrong.

The assembly associated with this is below, with the relevant instructions
prefixed with a *:

```
*     CODE:007852 b0 21           ADDWFC     offset DAT_DATA_01b0,w,BANKED                    = ??
      CODE:007854 a9 6f           MOVWF      offset DAT_DATA_01a9,BANKED                      = ??
      CODE:007856 a7 c1 f6 ff     MOVFF      DAT_DATA_01a7,TBLPTRL=>TBLPTR                    = ??
      CODE:00785a a8 c1 f7 ff     MOVFF      DAT_DATA_01a8,TBLPTRH=>TBLPTRH                   = ??
      CODE:00785e a9 c1 f8 ff     MOVFF      DAT_DATA_01a9,TBLPTRU=>TBLPTRU                   = ??
      CODE:007862 21 ee b2 f0     LFSR       FSR2,#0x1b2
*     CODE:007866 08 0e           MOVLW      #0x8
                              LAB_CODE_007868                                 XREF[1]:     CODE:00786c(j)  
*     CODE:007868 23 ec 1a f0     CALL       FUN_CODE_003446,0x0                              undefined FUN_CODE_003446()
*     CODE:00786c fd e2           BC         LAB_CODE_007868
```

From the decompilation see that `bVar4` is associated with the carry flag from
the `ADDWFC` assignment, which is the last time in the function an explicit use
of the carry bit occurred. However, as nothing else being done with the carry
flag in the loop that would affect the `BC` instruction, it is reasonable to
assume that it is the behavior of the called function itself that is changing
the carry bit.

If we look at the function:

```
     CODE:003446 09 00           TBLRD*+
     CODE:003448 f5 cf de ff     MOVFF      TABLAT=>TABLAT,POSTINC2=>POSTINC2                = ??
     CODE:00344c e8 06           DECF       WREG=>WREG,f,ACCESS                              = ??
     CODE:00344e 12 00           RETURN     0x0
```

We see it is basically just decrementing the working register, which is working
as a counter to read some number of bytes from the table register. The `DECF`
instruction sets or unsets the carry flag depending on the result.

This means that although the decompilation is sort of correct given that
`bVar4` is being used to represent the carry bit, it's also incorrect in that
it doesn't correctly indicate that the carry bit is changing during
the loop due to the `DECF`.

Originally I thought this might be due to `DECF` not updating the C flag, but I
checked the sleigh and pcode and confirmed it does update it:

```
:DECF srcREG, D, A		is op6=0x01 & srcREG & destREG & D & A	{ 
	#  0000 01da ffff ffff
	#  0000 0100 0000 0000  ->  DECF DAT_DATA_0000, w, ACCESS
	#  0000 0101 0000 0000  ->  DECF REG0x0, w, BANKED
	#  0000 0100 1101 1000  ->  DECF STATUS, w, ACCESS
	#  0000 0101 1101 1000  ->  DECF REG0xD8, w, BANKED
	#  0000 0110 0000 0000  ->  DECF DAT_DATA_0000, f, ACCESS
	#  0000 0111 0000 0000  ->  DECF REG0x0, f, BANKED
	#  0000 0110 1101 1000  ->  DECF STATUS, f, ACCESS
	#  0000 0111 1101 1000  ->  DECF REG0xD8, f, BANKED
	tmp:1 = srcREG;
	setSubtractFlags(tmp, 1); 
	tmp = tmp - 1;
	destREG = tmp;
	setResultFlags(tmp);
}

macro setSubtractFlags(op1,op2) {
	# op1 and op2 are assumed to be 8-bit values
	# NOTE:  carry flag is SET if there is NO borrow
	C = (op1 >= op2);
	DC = ((op1<<4) < (op2<<4));
	OV = sborrow(op1,op2);
}
```

and

```
     CODE:00344c e8 06           DECF       WREG=>WREG,f,ACCESS
                                      $U1220:1 = COPY WREG
                                      C = INT_LESSEQUAL 1:1, $U1220
                                      $U390:1 = INT_LEFT $U1220, 4:4
                                      $U3a0:1 = INT_LEFT 1:1, 4:4
                                      DC = INT_LESS $U390, $U3a0
                                      OV = INT_SBORROW $U1220, 1:1
                                      $U1220:1 = INT_SUB $U1220, 1:1
                                      WREG = COPY $U1220
                                      N = INT_SLESS $U1220, 0:1
                                      Z = INT_EQUAL $U1220, 0:1
```

**Expected behavior**

It would be nice if instead it was decompiled as:

```
      uVar2 = 8;
      do {
        uVar2 = FUN_CODE_003446(uVar2);
      } while (uVar2 >= 0);
```

Or at least indicate somehow that `bVar4` is changing as result of 
the `FUN_CODE_003446(uVar2);` call.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11.0
 - Ghidra Version: 9.0.2

**Comment by emteere** [comment]
The decompiler needs to make some assumptions about the calling convention, like flags registers are killed by a call.  You may need to give the decompiler more information using a custom calling convention.  Specify the C flag is returned by the function at FUN_CODE_003446 by editing its function signature.

Alternatively you can specify the function should be inlined, and the decompiler will weave in the effects of the called function.

For assembly with an anything goes calling convention, automatically discovering special handling can be error prone.  Normally flags registers are always killed by a call and not returned.

Does this code do this often so that the compiler might have used the carry flag when a boolean value was returned?  That might be automate-able.

**Comment by fidgetingbits** [comment]
> The decompiler needs to make some assumptions about the calling convention, like flags registers are killed by a call. You may need to give the decompiler more information using a custom calling convention. Specify the C flag is returned by the function at FUN_CODE_003446 by editing its function signature.

Thanks for the suggestions. It's great you can change the function signature to include those status flags, I hadn't seen that. 

One problem I see with it is that the storage associated with the return registers apparently must correlate to the size of the return datatype. So if I want to indicate both WREG and C are changing, I have to specify a short return type, which then understandably confuses the decompiler. 
Ex:
```
    cParm1 = 0x8;
    do {
      uVar6 = FUN_CODE_003446(cParm1);
      cParm1 = (char)uVar6;
    } while ((uVar6 & 0x100) != 0);
```

Maybe it should be filed as a separate issue, but it seems like status flags could possibly have some special designation where you can specify that status flags have no associated size with the returned datatype, but that they still change across function boundaries? Maybe a 'status' type when selecting the storage location.

If I change the return type to only be C, then I get something like:
```
    do {
      bVar2 = FUN_CODE_003446(cParm1);
    } while ((bVar2 & 1) != 0);
```
Which isn't really wrong, but still not ideal. The problem here is that the decompiled FUN_CODE_003446 becomes totally misleading:

```
char FUN_CODE_003446(char cParm1)

{
  return cParm1 != 0;
}
```
As it no longer shows the decrement at all. When it uses WREG it looks like this:

```
char FUN_CODE_003446(char cParm1)

{
  return cParm1 + -1;
}
```

I suppose it's worth noting also that the function in either case doesn't show the table read at all, whereas when the function is inlined (shown below) it does correctly show the read. I can file that as a separate bug if you'd like, though I'm not really sure what the solution would be, as it very much seems like an 'anything goes calling convention' function as you mentioned.

> Alternatively you can specify the function should be inlined, and the decompiler will weave in the effects of the called function.

This definitely seems to be the best approach for now, and what I'll use going forward. It is the only way that correctly shows what bounds the loop and the read.

```
    puVar8 = (undefined *)CONCAT12(DAT_DATA_018c,CONCAT11(DAT_DATA_018b,DAT_DATA_018a));
    cVar4 = 0x8;
    puVar1 = (undefined *)0x195;
    do {
      uVar7 = *puVar8;
      puVar8 = puVar8 + 1;
      pbVar2 = puVar1 + 1;
      *puVar1 = uVar7;
      bVar9 = cVar4 != 0;
      cVar4 = cVar4 + -1;
      puVar1 = puVar1 + 1;
    } while (bVar9);
```

> Does this code do this often so that the compiler might have used the carry flag when a boolean value was returned? That might be automate-able.

It is quite common throughout this firmware. I kind of suspect it is just the compiler being clever. I don't think in these cases it is actually trying to represent a boolean return. My guess is the function doesn't actually correlate to an actual C function with a return, but rather the compiler just turned these common repeating assembly stubs into a re-usable function in order to save code space.

I'm fine to close this if there is nothing you think can actually be fixed and you think that simply inlining in these scenarios is the correct solution.
