### ISSUE TITLE
is this sponsored by the cia federals?

### ISSUE THREAD

**Issue by mlodyskiny** [NationalSecurityAgency/ghidra#6065]
this is a serious question. also can i run this on templeos made by king terry the terrible??

**Comment by astrelsky** [comment]
No, it is very clearly created and maintained by the NSA as stated in the first sentence of the README.

**Comment by mlodyskiny** [comment]
are they going to give the federals any information about anything i reverse?

**Comment by ryanmkurtz** [comment]
As @astrelsky stated, Ghidra is developed by the National Security Agency (NSA).  The Ghidra program does not share any information you load into it....you control where your files are saved.  Ghidra optionally supports saving what you import to a potentially remote "Ghidra Server", but this is something you set up and intentionally connect to.

Ghidra also supports the installation of 3rd party extensions and scripts, which are not developed by the NSA.  If you use these, it will be up to you to vet them to make sure they behave as you expect them to.

**Comment by mlodyskiny** [comment]
ok i stick with ida.
