### ISSUE TITLE
get all key events in swing component

### ISSUE THREAD

**Issue by goatshriek** [NationalSecurityAgency/ghidra#6077]
**Is your feature request related to a problem? Please describe.**
I'm attempting to develop an extension to add a terminal emulator to Ghidra (JediTerm). Unfortunately, I've run into an issue with keybindings: the terminal only receives key events that aren't bound to an action in Ghidra. For example, trying to type "puts" results in "put" appearing followed by the search memory dialog opening since it's bound to "s".

After digging through Ghidra's native text editor and the interpreter panel and trying fruitlessly to copy their techniques, I came across the documentation for `KeyBindingOverrideKeyEventDispatcher` which suggests that Ghidra hooks Swing events before the components get them, and the only exceptions to this are for `JTextComponent` and `DockingDialog` instances. Since the terminal emulator is neither of these, it seems like I won't be able to get key events without some level of trickery. I'm not above trickery, but it is something I try to avoid.

**Describe the solution you'd like**
One possible solution that comes to mind is the addition of a marker interface that a component can implement to signify that it needs a first crack at key events. I'm sure there are other ways to solve this too, but I haven't been able to come up with a way to do it from the extension alone without changing Ghidra. Of course if there's something I've overlooked that will already let me do this that would be great!

**Describe alternatives you've considered**
I can of course add a text area below the terminal and force the users to type into this (similar to the existing interpreter implementation), but this will detract from the user experience. I'm also not sure how well it would work in tools that provide a TUI, which is one of the a primary things I want to support with this extension.

**Comment by dragonmacher** [comment]
> One possible solution that comes to mind is the addition of a marker interface that a component can implement to signify that it needs a first crack at key events.

We indeed used to have an interface just for this purpose.  It has been refactored away.  Now, you should be able to accomplish this by having your component 1) be focusable,  2) use a`KeyListener` and 3) consume the event.

As seen here in the dispatcher, the listeners get first crack at the event:

```java
        private boolean processComponentKeyListeners(KeyEvent keyEvent) {

		Component focusOwner = focusProvider.getFocusOwner();
		if (focusOwner == null) {
			return false;
		}

		KeyListener[] keyListeners = focusOwner.getKeyListeners();
		for (KeyListener listener : keyListeners) {
			int id = keyEvent.getID();
			switch (id) {
				case KeyEvent.KEY_TYPED:
					listener.keyTyped(keyEvent);
					break;
				case KeyEvent.KEY_PRESSED:
					listener.keyPressed(keyEvent);
					break;
				case KeyEvent.KEY_RELEASED:
					listener.keyReleased(keyEvent);
					break;
			}
		}

		return keyEvent.isConsumed();
	}
```

**Comment by goatshriek** [comment]
Thanks! I had tried a listener at one point, but must have bungled it somehow. I will give that specific combo of things a shot and report back here to confirm.

**Comment by goatshriek** [comment]
Thanks very much for your help, this did the trick.
