### ISSUE TITLE
Pointers in byte-mapped blocks don't add references by default

### ISSUE THREAD

**Issue by cczetier** [NationalSecurityAgency/ghidra#6081]
**Describe the bug**
A byte-mapped memory block containing data won't create references if that data is typed as a pointer, unlike typing a pointer in e.g. file mapped blocks.
Ghidra 11 added support for multiple memory blocks in overlay address spaces. The lack of automatic memory references means creating an overlay address space using byte-mapped memory blocks from the source address space will lack jumpable xrefs by default after analysis, which hampers reverse engineering.

**To Reproduce**
1. Create an ELF with a `.data` segment containing a pointer to another value in the `.data` segment, for example:
```c
int foo = 1;
int *bar = &foo;
int main() {
    return 0;
}
```
2. Create an overlay address space, and then a byte-mapped block containing a copy of `.data` in the new address space
```python
defaultSpace = currentProgram.getAddressFactory().getDefaultAddressSpace()
segmentSpace = currentProgram.createOverlaySpace("overlay", defaultSpace)
data = getMemoryBlock(".data")
currentProgram.getMemory().createByteMappedBlock("overlay.data", segmentSpace.getAddress(data.getStart().getOffset()), data.getStart(), data.getSize(), True)
```
3. Open `overlay.data` in the Listing
4. Create an int (Data > int) with the label label `overlay.foo` in the overlay at the offset `foo` is in the `.data` section (`00301010` for me)
5. Create a pointer (Data > pointer) in the overlay at the offset `bar` is in the `.data` section (`00301018` for me)
4. Observe the pointer data type was created, pointing to the address of our `overlay.foo` label in the overlay (`addr       overlay.data::00301010`), but no memory reference was added to `overlay.foo` and the label name is not resolved.
5. (As a work around) Select "References > Add Memory Reference" ("ctrl+alt+r" keybind by default) and see a memory reference can be added manually, which resolves the label (`addr       overlay.foo`) and adds an xref to `overlay.foo`.

**Expected behavior**
Pointers defined in a byte-mapped block should be added as memory references to their destination by default, instead of requiring "Add Memory Reference" to be ran manually. This is the normal behavior for non-byte-mapped address spaces, for example the normal `bar` pointer from the example ELF `.data` segment to it's own `.data` destination, and is also properly already done for code references by e.g. triggering disassembly in an overlay byte-mapped block that references data in the overlay.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: openjdk 17.0.7
 - Ghidra Version: 11.0
 - Ghidra Origin: Github distro

**Comment by ghidra1** [comment]
In your steps above I don't see where you initialized the memory bytes within the overlay space at Step#2
