### ISSUE TITLE
build error  [error: types Deque<Entry<K,V>> and List<Entry<K,V>> are incompatible]

### ISSUE THREAD

**Issue by vlsireddy** [NationalSecurityAgency/ghidra#6083]
Hi,

OS: Windows 11 [x64]
gradle: 8.5
visual studio: 2019

> Configure project :
Gradle: 8.5
OS: Windows 11
Arch: amd64 (gradle: x86-64)
Using platform: win_x86_64
Searching for latest Visual Studio and required components...
  -> Installation Directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
  -> VCTools Version (default): 14.29.30133
  -> SDK Directory (default): C:\Program Files (x86)\Windows Kits\10\
  -> SDK Version (default): 10.0.19041.0
  -> SDK Version (override): N/A

> Task :Generic:compileJava
C:\Users\mypc\Downloads\ghidra\Ghidra\Framework\Generic\src\main\java\ghidra\generic\util\datastruct\RestrictedValueSortedMap.java:253: error: types Deque<Entry<K,V>> and List<Entry<K,V>> are incompatible;
        public class RestrictedValueSortedMapEntryList implements ValueSortedMapEntryList<K, V> {
               ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in class RestrictedValueSortedMap
    V extends Object declared in class RestrictedValueSortedMap
C:\Users\mypc\Downloads\ghidra\Ghidra\Framework\Generic\src\main\java\ghidra\generic\util\datastruct\RestrictedValueSortedMap.java:548: error: types Deque<K> and List<K> are incompatible;
        public class RestrictedValueSortedMapKeyList implements ValueSortedMapKeyList<K> {
               ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in class RestrictedValueSortedMap
C:\Users\mypc\Downloads\ghidra\Ghidra\Framework\Generic\src\main\java\ghidra\generic\util\datastruct\ValueSortedMap.java:39: error: types Deque<Entry<K,V>> and List<Entry<K,V>> are incompatible;
        public interface ValueSortedMapEntryList<K, V>
               ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in interface ValueSortedMapEntryList
    V extends Object declared in interface ValueSortedMapEntryList
C:\Users\mypc\Downloads\ghidra\Ghidra\Framework\Generic\src\main\java\ghidra\generic\util\datastruct\ValueSortedMap.java:47: error: types Deque<K> and List<K> are incompatible;
        public interface ValueSortedMapKeyList<K> extends Set<K>, List<K>, Deque<K> {
               ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in interface ValueSortedMapKeyList
C:\Users\mypc\Downloads\ghidra\Ghidra\Framework\Generic\src\main\java\ghidra\generic\util\datastruct\TreeValueSortedMap.java:653: error: types Deque<Entry<K,V>> and List<Entry<K,V>> are incompatible;
        protected class ValueSortedTreeMapEntrySet extends AbstractSet<Entry<K, V>>
                  ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in class TreeValueSortedMap
    V extends Object declared in class TreeValueSortedMap
C:\Users\mypc\Downloads\ghidra\Ghidra\Framework\Generic\src\main\java\ghidra\generic\util\datastruct\TreeValueSortedMap.java:973: error: types Deque<K> and List<K> are incompatible;
        protected class ValueSortedTreeMapKeySet extends AbstractSet<K>
                  ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in class TreeValueSortedMap
C:\Users\mypc\Downloads\ghidra\Ghidra\Framework\Generic\src\main\java\ghidra\generic\util\datastruct\TreeValueSortedMap.java:1211: error: types Deque<V> and List<V> are incompatible;
        protected class ValueSortedTreeMapValues extends AbstractCollection<V>
                  ^
  both define reversed(), but with unrelated return types
  where V is a type-variable:
    V extends Object declared in class TreeValueSortedMap
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

> Task :Generic:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Generic:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 17s
4 actionable tasks: 1 executed, 3 up-to-date

C:\Users\mypc\Downloads\ghidra>

**Comment by ryanmkurtz** [comment]
This is because you built with JDK 21, which Ghidra doesn't properly support yet.  The official JDK that Ghidra supports is JDK 17.

**Comment by vlsireddy** [comment]
Hi,
   Thanks, that helps and build succeed.
