### ISSUE TITLE
Ghidra headless, reuse analysis results

### ISSUE THREAD

**Issue by mixern6** [NationalSecurityAgency/ghidra#6085]
I use Ghidra headless in my project to analyze crashes in libraries. Every time a crash occurs in a library, the decompile script initiates a lengthy analysis process. Is there a way to save the analysis results in the first run and reuse them in future runs to save the time, so that I could skip the analysis step and go straight to decompiling?

Here is an example  of the command line I use:

> "ghidra_11.0_PUBLIC/support/analyzeHeadless" "ghidra_11.0_PUBLIC" LibcAnalysis -import "/lib/x86_64-linux-gnu/libc.so.6" -scriptPath "ghidra_11.0_PUBLIC/"  -postscript "decompile_simple.py" address=0x126660 -overwrite

**Comment by dev747368** [comment]
When you use ```-import```, you are importing a fresh copy of the binary into your project.  analyzeHeadless can be used to import and analyze as separate steps depending on the startup options.  It may require you to change your workflow though.

**Comment by mixern6** [comment]
What should I change in the command line? If I change it to this:
>  "ghidra_11.0_PUBLIC/support/analyzeHeadless" "ghidra_11.0_PUBLIC" LibcAnalysis -scriptPath "ghidra_11.0_PUBLIC/" -postscript "decompile_simple.py" address=0x126660

The postscript throws an error that currentProgram is None

**Comment by mixern6** [comment]
If I don't specify the -import, I get the error even in the prescript:
> Traceback (most recent call last):
  File "C:\Data\ghidra_11.0_PUBLIC_20231222\prescript.py", line 43, in <module>
    options = getCurrentAnalysisOptionsAndValues(currentProgram)
        at ghidra.app.script.GhidraScript.getCurrentAnalysisOptionsAndValues(GhidraScript.java:1282)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
java.lang.NullPointerException: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.listing.Program.getOptions(String)" because "program" is null

Is it a bug, or I'm missing something?

**Comment by mixern6** [comment]
if I add
> -process "libc.so.6" -noanalysis

it works without the errors

**Comment by mixern6** [comment]
if I add
> -process "libc.so.6" -noanalysis

it works without the errors
