### ISSUE TITLE
Pcode Emulator ignores patched instructions

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#6086]
**Describe the bug**
When running the emulator and patching an unimplemented instruction, the new instruction is ignored and the old unimplemented one is still used.

**Comment by TheDauntless** [comment]
You'll need to provide a lot more information here. I did this technique yesterday and it worked.

Which binary? Which instructions? How did you start the trace? Which OS? Which version? Which architecture? etc.

**Comment by astrelsky** [comment]
> You'll need to provide a lot more information here. I did this technique yesterday and it worked.
> 
> Which binary? Which instructions? How did you start the trace? Which OS? Which version? Which architecture? Try to follow the issue template, as it asks for all of this information.

Start emulation, run up to an instruction (was unimplemented in my case), patch it, try to continue, see problem.

**Comment by nsadeveloper789** [comment]
This use case can be a bit tricky. Is this "pure" emulation, or are you forking from a live target?

After you've stepped the patched (or what should be patched) instruction, what is the full title of the "Threads" window, i.e., what is the stepping schedule?

Did you patch in the Dynamic listing or the Static listing?

One thing you might try is invalidating the emulation cache after the patch. In the menus: Debugger -> Configure Emulator -> Invalidate Emulator Cache. Then, try stepping again.

**Comment by astrelsky** [comment]
> This use case can be a bit tricky. Is this "pure" emulation, or are you forking from a live target?
> 
> After you've stepped the patched (or what should be patched) instruction, what is the full title of the "Threads" window, i.e., what is the stepping schedule?
> 
> Did you patch in the Dynamic listing or the Static listing?
> 
> One thing you might try is invalidating the emulation cache after the patch. In the menus: Debugger -> Configure Emulator -> Invalidate Emulator Cache. Then, try stepping again.

Pure emulation. Invalidating the emulator cache did work, **but** after clearing it, stepping didn't appear to do anything. I had to run it again until it stopped to continue.

**Comment by nsadeveloper789** [comment]
Sometimes the UI thinks it finished that instruction when it didn't. You might try stepping back one then forward again.
