### ISSUE TITLE
Debugger memory search doesn't find values unless these values were shown in memory window

### ISSUE THREAD

**Issue by unknown321** [NationalSecurityAgency/ghidra#6088]
**Describe the bug**
Memory search cannot find string, but after scrolling memory to strings' location, it is found.

**To Reproduce**
1. Start gdb and connect to remote target
2. Attach to process
3. Start debugger, attach to gdb via new-ui
4. Force full view in memory regions
5. Look for the string in memory (Window - Byte Viewer - Memory - Search - Memory, "Next"/"Prev"/"Search All"): string not found.
6. Look for the string in gdb:
```shell
(rr) find 0x9d600000,0x9d6ad000,{char[7]}"Impulse"
0x9d63d25b
0x9d642817
0x9d642865
```
7. Go to first found address in memory window
8. Look for the same string again - find one entry

**Expected behavior**
Look for a string - all string entries found immidiately without scrolling.

**Screenshots**

Before scrolling memory window, nothing found:

![2024-01-07-002851_582x386_scrot](https://github.com/NationalSecurityAgency/ghidra/assets/1469658/0f9d93ea-ac4f-4a67-83c1-37a2153ed5a4)

After scrolling memory window:

![2024-01-07-003816_3840x1080_scrot](https://github.com/NationalSecurityAgency/ghidra/assets/1469658/f3cf2142-015a-43ef-a583-4f0b53b42f6b)

**Attachments**

```shell
$ grep 9d600000 /proc/1946/maps
9d5c0000-9d600000 rw-s 13047000 00:0d 3268       /dev/mali
9d600000-9d6ad000 rw-p 00000000 00:00 0
```

**Environment (please complete the following information):**
 - OS: Debian 13
 - Java Version: amazon-corretto-17.0.9.8.1-linux-x64
 - Ghidra Version: 11.0
 - Ghidra Origin: official GitHub distro
 - GNU gdb (Debian 13.1-3) 13.1

**Additional context**

Gdb is spawned outside of Ghidra and remotely connected to process running on ARM device. Ghidra is connected to gdb via new-ui. Issue is also present in 10.4.

**Comment by nsadeveloper789** [comment]
This is a known issue. A full search of target memory is not implemented in Ghidra, and probably won't be for some time, if ever. The UI is really just a cache of the data available in the back-end debugger. As such, Ghidra can't technically search except for what it has seen. The search dialog we current present is actually the one inherited from the Static analysis suite, so it's just searching that cache.

The recommended approach is to just use the gdb CLI to perform the search, and then navigate to interesting addresses manually.

Alternatively, you can command Ghidra to download the full memory contents, which will then make its search feature more useful. **WARNING!**: This operation may not succeed without adverse consequences, up to and including permanent damage to the device and/or nearby property! Perhaps I'm being dramatic, but depending on the device and how robust its gdbstub is, things could go horribly wrong. We're not responsible for any damage. This will ruthlessly command gdb to retrieve _every_ block of memory from the device that it can. This may result in many, many invalid reads, or attempts to access IO-mapped addresses, etc. That said, here are the steps: 1) In the Dynamic listing, hit Ctrl-A (Select All). 2) Click the "Refresh Memory" button (looks like a little memory chip) in the local toolbar. Wait some time for that to complete :) . If you know what address ranges are actually valid, or are actually likely to contain the string, you can make the selection smaller which should improve performance and reliability.
