### ISSUE TITLE
DemangledFunctionPointer Unhandled NullPointerException

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#609]
**Describe the bug**
Constructing a new DemangledFunctionPointer and attempting to retreive its dataType prior to setting a return type will result in a NullPointerException.

**To Reproduce**
```
DataTypeManager dataTypeManager = getProgram().getDataTypeManager();
DataType vptr = new DemangledFunctionPointer().getDataType(dataTypeManager);
```

**Expected behavior**
A default void return type or some preventative measure.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.503]
 - Java Version: 12.0.1
 - Ghidra Version: 9.2

**Comment by dragonmacher** [comment]
This API is typically only used internally.   It is used by the Demangling code to build up data type representations as it parses mangled symbols.  

The fix will be in the 9.1 release.
