### ISSUE TITLE
How to add newlines in the message in `GhidraScript.askChoice`?

### ISSUE THREAD

**Issue by HJfod** [NationalSecurityAgency/ghidra#6094]
I'm trying to show a dialogue asking the user which of two options should be used when importing functions from another file. For legibility, it would be important to show the different options on their own lines. However, just adding newlines to the dialog's message doesn't seem to work.

I'm assuming some code somewhere is filtering out any control characters, but is there some other alternative I can use to create dialogs with multiple lines?

I am running Ghidra version 11.0 with Java version 17.0.9 under Windows 10 22H2.

```java
<A, B> Boolean askBromaConflict(String in, String what, A broma, B ghidra) throws Exception {
    switch (askChoice(
        "Conflict between Broma and Ghidra",
        MessageFormat.format(
            "Conflict between {1}s in {0}: \n" + 
            "Broma: {2} \n" +
            "Ghidra: {3} \n" + 
            "Should Broma's {1} be used or keep Ghidra's {1}?",
            in, what, broma, ghidra
        ),
        List.of("Use Broma", "Keep Ghidra", "Cancel Script"),
        null
    )) {
        case "Use Broma": return true;
        case "Keep Ghidra": return false;
        case "Cancel Script": throw new Error("Script cancelled");
    }
    return true;
}
```
![image](https://github.com/NationalSecurityAgency/ghidra/assets/60038575/4e60efec-88cf-43a9-959e-b2cea6897c7b)

**Comment by dragonmacher** [comment]
It seems that the built-in ask methods do not support newlines.  They make use of a `GLabel` internally, which extends `JLabel`.  `JLabel`'s do not support newlines. 

The various `ask` methods will not support this.  However, you can get the effect you desire with this snippet.  The only caveat is if the user cancels the dialog, it will not cancel the script, as do the `ask` methods.   So, if you need that behavior, you will have to check for `null` after the dialog returns.

```java

import docking.widgets.dialogs.InputWithChoicesDialog;
import ghidra.app.script.GhidraScript;
import ghidra.util.Swing;

...

	@Override
	public void run() throws Exception {

		String choice = Swing.runNow(() -> {
			InputWithChoicesDialog dialog =
				new InputWithChoicesDialog("Title", "<html>This is<br>my message",
					new String[] { "One", "Two" }, "Two", null);
			state.getTool().showDialog(dialog);
			return dialog.getValue();
		});

		println("Choice: " + choice);

		if (choice == null) {
			// the user cancelled the dialog
			return;
		}

	}
```

**Comment by HJfod** [comment]
Hello, that works perfectly! Thank you for the response!
