### ISSUE TITLE
Is it pronounced Ghidra or Ghidra?

### ISSUE THREAD

**Issue by hook-s3c** [NationalSecurityAgency/ghidra#61]
Please don't say "Ghidra"

**Comment by nneonneo** [comment]
Gee-druh, per https://github.com/NationalSecurityAgency/ghidra/wiki/Frequently-asked-questions#how-do-you-pronounce-ghidra.

**Comment by wrharper** [comment]
What about hydra? 🪦

**Comment by vientuliba** [comment]
g-hydra

**Comment by herrcore** [comment]
> g-hydra

https://github.com/user-attachments/assets/0ea9c8f9-7868-4407-8f5c-a332a83afa59

**Comment by wrharper** [comment]
After googling it is gee-dra or something like that, but g hydra is more hilarious 😂
