### ISSUE TITLE
Show address as well as symbol name in disassembly

### ISSUE THREAD

**Issue by rollsch** [NationalSecurityAgency/ghidra#6103]
Is it possible to show the address AND the function/ptr name in ghidra?

Eg
```
st.b [a8]0x36e8=>index1,index2 
st.b [a8]0x3745=>val2,d8
call function_b

st.b [a8]0x36e8=>index1,index2    index1 = 6002c868,  index2  = d2 
st.b [a8]0x3745=>val2,d8               val2, = 6002c8c5
call function_b                                function_b = 804449fa
```

This way I don't have to look up the address each time.

**Comment by ryanmkurtz** [comment]
Can you just hover on the symbol and see the address?

**Comment by ghidra1** [comment]
If you select the instruction the raw instruction will be displayed in the low-right status area of the window.
![image](https://github.com/NationalSecurityAgency/ghidra/assets/48333017/6a824dd3-9c93-46bc-9e52-7a436b957260)
