### ISSUE TITLE
Ghidra server NAT

### ISSUE THREAD

**Issue by MattMills** [NationalSecurityAgency/ghidra#6106]
So from looking at other tickets I understand Ghidra has an issue with NAT where it is opening multiple connections and in one of the connections it is providing an address to connect back to itself, thus if the connection is being NAT address translated you need to specify a public IP address it can use within that protocol. (Working much like old school FTP did)

I have a setup where I'd like to be able to use the server locally, as well as remotely, on either side of the NAT.

Is there any way to accomplish this (so far I've been restarting the server and adding/removing the IP depending on whether I want to use it locally or remotely, but that is getting irritating)? Alternatively, can you direct me to related code so I can try to either do some kind of deep packet inspection to NAT the address within the communicated data, move to a DNS entry so I can use split horizon DNS (DNS entry that has different IP addresses internally vs externally), or create a service that will connect to ghidra and then accept external connections and translate the necessary data on the fly?

Just out of curiosity, is there any reason why the server doesn't just communicate a port and the client use the address specified in the URL, or alternatively specify all the required host/port data within the URL or client side?

I suppose I may just setup a wireguard tunnel for this, but ideally I'd like to better understand (and better document) the issue itself.

Feel free to direct me to other issues if there is something already documenting all this that I've missed.

**Comment by ghidra1** [comment]
Although I have not tried this, you could use -ip option with a public DNS FQDN (i.e., hostname) and on your local host create a manual hosts entry which maps that name to the local IP address (i.e., 127.0.0.1).  This should prevent it  from using DNS to resolve the hostname supplied to Ghidra Server clients.

**Comment by MattMills** [comment]
Yeap that worked fine, although I used internal/external DNS records rather than hosts file.
