### ISSUE TITLE
Compare a binary file with a file containing the source code

### ISSUE THREAD

**Issue by Coualafool** [NationalSecurityAgency/ghidra#611]
Hello,
I am currently using ghidra for reverse engineering and wondering if it is possible to compare the binary file I am disassembling with the source code of an SDK used by the binary on which I am am working? 
Is it possible for Ghidra to do this work for me?

**Comment by philpem** [comment]
What is your objective, to identify the functions in the SDK?

I believe Ghidra has some kind of Function ID / FLIRT style functionality which is covered in the documentation.

You'd need to compile the SDK with debug information on, ideally with the same compiler as was used to compile the binary you're working on. Take the object files and turn them into signatures which Ghidra can load and use to identify the functions by pattern.

**Comment by terriblefire** [comment]
I have a similar question. Imagine I have *a* version of original source and a compiled binary which may have been done with a few changes that were never committed to source control. I essentially want to reverse engineer the changes.

Not expecting that Ghidra can do this easily. Just asking a question.

**Comment by ryanmkurtz** [comment]
Ghidra has the ability to compare differences in 2 binaries, but has no means to work with source code.
