### ISSUE TITLE
Struct members shown in disassembly but not in decompiler

### ISSUE THREAD

**Issue by joxeankoret** [NationalSecurityAgency/ghidra#6112]
**Describe the bug**

Struct members assigned to a local variable are correctly shown in the disassembly but they are not show in the decompilation, and they look odd, as show in the attached screenshot.

**To Reproduce**

1. Open DXCaptureReplay.dll from Windows 10, load the PDB, analyse it, etc...
2. Go to `CheckForWindowClosureImpl`.
3. Change `lpMessage` local variable type to `MSG`.
4. Assignments to strut members won't be shown properly in the decompiler while they will properly appear in the disassembly.

**Expected behavior**
Seeing the same member names in the disassembly and the decompiler.

**Screenshots**
![irudia](https://github.com/NationalSecurityAgency/ghidra/assets/2945834/668a8242-4975-4c26-9857-be9e05c496a6)

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 22.04.3 LT
 - Java Version: 17.0.9
 - Ghidra Version: 11.0
 - Ghidra Origin: Github

**Comment by joxeankoret** [comment]
PS: The "best" outcome here, however, would be to just collapse the 3 `ZEXT816()` calls into a single `memset(lpMessage, '\0', sizeof(MSG))` instruction.

**Comment by ghidra1** [comment]
The disassembly markup does not consider the access size which does not align with actual component sizes.  It simply identifies the location where the write occurs.

**Comment by ghidra1** [comment]
The decompiler will not show as structure member access since the accesses do not match-up properly with components.  The writes are compiler generated for simplified/rapid clearing of structure data.
