### ISSUE TITLE
after arm64 instruction patched , when export the program , not all patched bytes are applied

### ISSUE THREAD

**Issue by bb33bb** [NationalSecurityAgency/ghidra#6116]
**Describe the bug**
after arm64 instruction patched , when export the program , not all patched bytes are applied

**To Reproduce**
01-patch some arm64 program, i use a random arm64 xxx.ko file, it is randomly a cellphne driver
02-try to patch it
03-remember patch more than 0ne struction
04-export the program as original
05-diff the exported file with the original file

**Expected behavior**
patched more than 4 bytes, because we patched more than one struction

**Screenshots**
no

**Attachments**
no

**Environment (please complete the following information):**
 - OS:manjaro
 - Java Version: 17sdk
 - Ghidra Version:11.0 the last public release
 - Ghidra Origin:github

**Additional context**
no

**Comment by ryanmkurtz** [comment]
Was your patch on a relocation?

**Comment by bb33bb** [comment]
> Was your patch on a relocation?

yes, I think .

the following patch instruction

adrp x0, 0x150000
add x0,x0,#offset
bl printk

**Comment by ryanmkurtz** [comment]
As described in the Help for the "Original File" exporter:

> Relocation bytes are always restored to their original values, even if the user modifies them.

**Comment by bb33bb** [comment]
is there any possible to add function like this:
when i tried to patch some bytecode ,
01-find the relocation of this address
02-delete the relocation of this address
03-patch the code

I tried this method in BinaryNinja, and can successfully patch the *.ko in android.
