### ISSUE TITLE
FreeBSD Releases

### ISSUE THREAD

**Issue by schrodyn** [NationalSecurityAgency/ghidra#6117]
Would you please consider providing Ghidra releases for the FreeBSD UNIX OS? I maintain a VM just to use Ghidra and would prefer to use Ghidra natively on FreeBSD. I've tried to build Ghidra manually for FreeBSD but it fails as an unsupported OS.

**Comment by ryanmkurtz** [comment]
I've experimented a bit with Ghidra and FreeBSD and I feel like some things would be easy to support, and other things harder.  Assuming you'd be willing to install `bash`, it's easy to get Ghidra to launch.  It would also be easy for us to support running `support/buildNatives` from a Ghidra installation, so the user can produce FreeBSD-specific native components (decompiler, demangler, etc) for their installation.  I've actually already implemented this with success.  

I did not have success building the entire Ghidra repo from FreeBSD, because we don't have a FreeBSD compatible version of the [Protobuf Compiler](https://mvnrepository.com/artifact/com.google.protobuf/protoc), and I don't see one available [here](https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.21.8/).  Also, a prebuilt Debugger will currently fail to run FreeBSD.

So, a possible solution for a future Ghidra release would be:
1. Download Ghidra release
2. Install `bash`, `gcc`, `javac`, `gradle`.
3. From your extracted Ghidra release, run `support/buildNatives`
4. Launch Ghidra, and use everything but the debugger.

Would that have value to you?

I think i can rule out the possibility of us producing the FreeBSD native components for distribution with our official releases...we'd rather provide the user the means of producing their own missing components for the non-mainstream OS's.

**Comment by schrodyn** [comment]
Hello @ryanmkurtz,

Thank you for the suggestions.  I am more than happy if I can use Ghidra with everything except the debugger. Can you provide help with patching a Ghidra release to compile the native components on FreeBSD?

I just patched in FreeBSD as a supported OS and ran `./support/buildNatives`:

```
--- ghidra_11.0_PUBLIC/GPL/nativePlatforms.gradle       2023-12-22 09:54:42.000000000 +0000
+++ ghidra_11.0_PUBLIC.patched/GPL/nativePlatforms.gradle       2024-01-16 15:42:48.007217000 +0000
@@ -51,6 +51,9 @@
                case ~/Mac OS X.*/:
                        os = "mac"
                        break
+               case ~/FreeBSD.*/:
+                       os = "freebsd"
+                       break
                default:
                        throw new GradleException("Unrecognized platform operating system: $os")
        }
```

```
➜ ./support/buildNatives
Building natives in Ghidra...
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :Debugger-swig-lldb
OS: FreeBSD
Arch: amd64 (gradle: x86-64)
Using platform: freebsd_x86_64

> Configure project :Decompiler
OS: FreeBSD
Arch: amd64 (gradle: x86-64)
Using platform: freebsd_x86_64

> Configure project :PDB
OS: FreeBSD
Arch: amd64 (gradle: x86-64)
Using platform: freebsd_x86_64

> Task :Debugger-swig-lldb:buildNatives UP-TO-DATE
> Task :Decompiler:buildNatives UP-TO-DATE
> Task :PDB:buildNatives UP-TO-DATE

BUILD SUCCESSFUL in 10s
Building natives in GPL...

> Configure project :DemanglerGnu
OS: FreeBSD
Arch: amd64 (gradle: x86-64)
Using platform: freebsd_x86_64

> Task :DemanglerGnu:buildNatives UP-TO-DATE

BUILD SUCCESSFUL in 2s
```

As you can see the build was successful, however, when I opened a binary I get the following error during analysis:

```
os/null/decompile does not exist
---------------------------------------------------
Build Date: 2023-Dec-22 0936 EST
Ghidra Version: 11.0
Java Home: /usr/local/openjdk17
JVM Version: OpenJDK BSD Porting Team 17.0.9
OS: FreeBSD 14.0-RELEASE-p3 amd64
```

**Comment by ryanmkurtz** [comment]
That's because the Java side doesn't know about the `freebsd` target.  Since you can't do a full rebuild on FreeBSD, i recommend reusing the exiting `linux_x86_64` platform.  So, in your FreeBSD switch case in `nativePlatforms.gradle`, set `os = "linux"`.  Then, in `nativeBuildProperties.gradle` in the `toolChains` block, and an `else {` to the `isCurrentLinux()` block:
```
if (isCurrentLinux()) {
  gcc(Gcc) {
    if (isCurrentArm_64()) {
      target("linux_arm_64")
    }
    else {
      target("linux_x86_64")
    }
}
```
Then execute `support/buildNatives`.  Your new native components will live under (for example) `Ghidra/Features/Decompiler/build/os/linux_x86_64`, and Ghidra will give precedence to this one instead of the one we ship in `Ghidra/Features/Decompiler/os/linux_x86_64`.  FreeBSD looks enough like Linux for the rest of the code to just work (except the Debugger).

**Comment by schrodyn** [comment]
The build seems to have done more this time but I get the same error again, see below.

```
➜ diff -u ghidra_11.0_PUBLIC/GPL/nativePlatforms.gradle ghidra_11.0_PUBLIC.patched/GPL/nativePlatforms.gradle
--- ghidra_11.0_PUBLIC/GPL/nativePlatforms.gradle       2023-12-22 09:54:42.000000000 +0000
+++ ghidra_11.0_PUBLIC.patched/GPL/nativePlatforms.gradle       2024-01-16 16:46:54.285650000 +0000
@@ -51,6 +51,9 @@
                case ~/Mac OS X.*/:
                        os = "mac"
                        break
+               case ~/FreeBSD.*/:
+                       os = "linux"
+                       break
                default:
                        throw new GradleException("Unrecognized platform operating system: $os")
        }

➜ diff -u ghidra_11.0_PUBLIC/GPL/nativeBuildProperties.gradle ghidra_11.0_PUBLIC.patched/GPL/nativeBuildProperties.gradle
--- ghidra_11.0_PUBLIC/GPL/nativeBuildProperties.gradle 2023-12-22 09:54:42.000000000 +0000
+++ ghidra_11.0_PUBLIC.patched/GPL/nativeBuildProperties.gradle 2024-01-16 16:49:36.038611000 +0000
@@ -43,6 +43,9 @@
                                if (isCurrentArm_64()) {
                                        target("linux_arm_64")
                                }
+                else {
+                    target("linux_x86_64")
+                }
                        }
                }
                if (isCurrentMac()) {
```

```
➜ ./support/buildNatives
Building natives in Ghidra...

> Configure project :Debugger-swig-lldb
OS: FreeBSD
Arch: amd64 (gradle: x86-64)
Using platform: linux_x86_64

> Configure project :Decompiler
OS: FreeBSD
Arch: amd64 (gradle: x86-64)
Using platform: linux_x86_64

> Configure project :PDB
OS: FreeBSD
Arch: amd64 (gradle: x86-64)
Using platform: linux_x86_64

> Task :Debugger-swig-lldb:buildNatives UP-TO-DATE
> Task :Decompiler:CheckToolChain
> Task :Decompiler:compileDecompileLinux_x86_64ExecutableDecompileCpp
> Task :Decompiler:compileSleighLinux_x86_64ExecutableSleighCpp
> Task :PDB:buildNatives UP-TO-DATE
> Task :Decompiler:linkSleighLinux_x86_64Executable
> Task :Decompiler:linkDecompileLinux_x86_64Executable
> Task :Decompiler:buildNatives

BUILD SUCCESSFUL in 2m 27s
5 actionable tasks: 5 executed
Building natives in GPL...

> Configure project :DemanglerGnu
OS: FreeBSD
Arch: amd64 (gradle: x86-64)
Using platform: linux_x86_64

> Task :DemanglerGnu:CheckToolChain
> Task :DemanglerGnu:compileDemangler_gnu_v2_24Linux_x86_64ExecutableDemangler_gnu_v2_24C
> Task :DemanglerGnu:linkDemangler_gnu_v2_24Linux_x86_64Executable
> Task :DemanglerGnu:compileDemangler_gnu_v2_41Linux_x86_64ExecutableDemangler_gnu_v2_41C
> Task :DemanglerGnu:linkDemangler_gnu_v2_41Linux_x86_64Executable
> Task :DemanglerGnu:buildNatives

BUILD SUCCESSFUL in 2s
5 actionable tasks: 5 executed

➜ file Ghidra/Features/Decompiler/build/os/linux_x86_64/*
Ghidra/Features/Decompiler/build/os/linux_x86_64/decompile: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 14.0 (1400097), FreeBSD-style, with debug_info, not stripped
Ghidra/Features/Decompiler/build/os/linux_x86_64/sleigh:    ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 14.0 (1400097), FreeBSD-style, with debug_info, not stripped
```

But I get the same error again:

```
os/null/decompile does not exist
---------------------------------------------------
Build Date: 2023-Dec-22 0936 EST
Ghidra Version: 11.0
Java Home: /usr/local/openjdk17
JVM Version: OpenJDK BSD Porting Team 17.0.9
OS: FreeBSD 14.0-RELEASE-p3 amd64
```

**Comment by ryanmkurtz** [comment]
Makes sense.  It's because of this code on the Java side:
https://github.com/NationalSecurityAgency/ghidra/blob/3410dc1ad99bcc0449a993a054a38c2c5670269f/Ghidra/Framework/Utility/src/main/java/ghidra/framework/OperatingSystem.java#L19-L46

You could try adding a new line to `support/launch.properties`:
```
VMARGS=-Dos.name=linux
```

Warning: This caused my JVM to be very unhappy, but maybe your FreeBSD one won't mind it.

**Comment by schrodyn** [comment]
Hmm, that worked but I'm running into an error importing some files, not every file.

```
java.lang.ClassNotFoundException: jdk/net/LinuxSocketOptions
java.lang.AssertionError: java.lang.ClassNotFoundException: jdk/net/LinuxSocketOptions
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.newInstance(ExtendedSocketOptions.java:355)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.create(ExtendedSocketOptions.java:368)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.<clinit>(ExtendedSocketOptions.java:378)
	at jdk.net/jdk.net.ExtendedSocketOptions.<clinit>(ExtendedSocketOptions.java:203)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/sun.net.ext.ExtendedSocketOptions.getInstance(ExtendedSocketOptions.java:178)
	at java.base/sun.nio.ch.Net.<clinit>(Net.java:388)
	at java.base/sun.nio.ch.NioSocketImpl.create(NioSocketImpl.java:469)
	at java.base/java.net.ServerSocket.createImpl(ServerSocket.java:317)
	at java.base/java.net.ServerSocket.getImpl(ServerSocket.java:294)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:342)
	at ghidra.framework.store.FileIDFactory.createFileID(FileIDFactory.java:45)
	at ghidra.framework.data.DBContentHandler.createFile(DBContentHandler.java:59)
	at ghidra.program.database.ProgramContentHandler.createFile(ProgramContentHandler.java:61)
	at ghidra.framework.data.GhidraFolderData.createFile(GhidraFolderData.java:988)
	at ghidra.framework.data.GhidraFolder.createFile(GhidraFolder.java:317)
	at ghidra.app.util.opinion.Loaded.save(Loaded.java:166)
	at ghidra.app.util.opinion.LoadResults.save(LoadResults.java:124)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:398)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:336)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: jdk/net/LinuxSocketOptions
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.newInstance(ExtendedSocketOptions.java:352)
	... 27 more

---------------------------------------------------
Build Date: 2023-Dec-22 0936 EST
Ghidra Version: 11.0
Java Home: /usr/local/openjdk17
JVM Version: OpenJDK BSD Porting Team 17.0.9
OS: Linux 14.0-RELEASE-p3 amd64
```

**Comment by ryanmkurtz** [comment]
Bummer.  My next best solution is to build Ghidra on some other platform, but modify `OperatingSystem.findCurrentOperatingSystem()` so that if `System.getProperty("os.name").equals("FreeBSD")`, you immediately return `LINUX`.

Then, replace the `Utility.jar` file on your FreeBSD system with your newly built version.

**Comment by ryanmkurtz** [comment]
If you decide to try this, make sure you are working off of the `Ghidra.11.0_build` tag.

Also, remove that change i suggested from `support/launch.properties`.

**Comment by schrodyn** [comment]
Thank you. I will give that a try later on. I really appreciate your help with this. Feel like it's almost there - just a few more hacks needed ;)

**Comment by ryanmkurtz** [comment]
I was already set up to quickly do this: [Utility.jar.zip](https://github.com/NationalSecurityAgency/ghidra/files/13954039/Utility.jar.zip)

I zipped it so GitHub would let me attach it.

**Comment by schrodyn** [comment]
It works!!!!!!!! =) Thank you very much. I've imported a few samples and successfully run the analysis on them all. Decompilation looks good. Could browse around the binaries and even ran one script without errors.

Could you send me a patch for the changes you made? I'd like to be able to apply it to future releases as they come out.

**Comment by ryanmkurtz** [comment]
Glad to hear it worked out for you.  Here is the Java change I made:
```java
diff --git a/Ghidra/Framework/Utility/src/main/java/ghidra/framework/OperatingSystem.java b/Ghidra/Framework/Utility/src/main/java/ghidra/framework/OperatingSystem.java
index ecf65742b..5a6042b1a 100644
--- a/Ghidra/Framework/Utility/src/main/java/ghidra/framework/OperatingSystem.java
+++ b/Ghidra/Framework/Utility/src/main/java/ghidra/framework/OperatingSystem.java
@@ -37,6 +37,9 @@ public enum OperatingSystem {
 
        private static OperatingSystem findCurrentOperatingSystem() {
                String operatingSystemNameProperty = System.getProperty("os.name");
+               if (operatingSystemNameProperty.equals("FreeBSD")) {
+                       return LINUX;
+               }
                for (OperatingSystem operatingSystem : values()) {
                        if (operatingSystemNameProperty.toLowerCase().indexOf(
                                        operatingSystem.operatingSystemName.toLowerCase()) > -1) {
```

**Comment by ryanmkurtz** [comment]
I am going to discuss with the team adding a `bsd` platform to our official releases.  It will have the same limitations you've experienced (no full build, no debugger support), but it would enable `support/buildNatives` to run and have the Java code find the built components.  I'll keep this ticket open and let you know what comes of it.

**Comment by XVilka** [comment]
I don't know if you will check it on the CI automatically, but we have been happy with SourceHut for a while - it provides CI runners for FreeBSD, OpenBSD, and NetBSD. OpenBSD was particularly handy in catching some nasty bugs that even ASAN missed. I definitely can recommend it. Though for Ghidra as Java software, it should be less of a problem than for us - purely C software.

- https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd
- https://man.sr.ht/builds.sr.ht/compatibility.md#openbsd
- https://man.sr.ht/builds.sr.ht/compatibility.md#netbsd

**Comment by VVD** [comment]
For those who get here through a search: https://www.freshports.org/devel/ghidra

**Comment by jwntree** [comment]
Can I ask question?
Is there any technical reason why protobuf is provided via Maven by build processing?
Most operating systems already provide protobuf as a package.
I patched the Maven scripts and built it on illumos and It seems to work fine.

**Comment by ryanmkurtz** [comment]
> Can I ask question? Is there any technical reason why protobuf is provided via Maven by build processing? Most operating systems already provide protobuf as a package. I patched the Maven scripts and built it on illumos and It seems to work fine.

All platforms that Ghidra supports (windows, linux, macOS) would have to provide the version we require, which is not the case.
