### ISSUE TITLE
Incorrect sockaddr_in size

### ISSUE THREAD

**Issue by catsuryuu** [NationalSecurityAgency/ghidra#612]
**Describe the bug**
sockaddr_in size should be 16, not 24.
sin_zero field type should be uchar[8], not uchar[16].

**Environment:**
 - OS: [Ubuntu 16.04.6 LTS]
 - Java Version: [11.0.1]
 - Ghidra Version: [9.0.2]

**Comment by devnull850** [comment]
@ryanmkurtz @catsuryuu This appears to now be resolved and using uchar[8] for the sin_zero field.

**Comment by ryanmkurtz** [comment]
Yes, thank you
