### ISSUE TITLE
Analyzer problems with an Android ARM64 binary

### ISSUE THREAD

**Issue by kholia** [NationalSecurityAgency/ghidra#6120]
**Describe the bug**
Analyzer runs into problems when analyzing an Android ARM64 binary.

![Screenshot_2024-01-16_10-18-48](https://github.com/NationalSecurityAgency/ghidra/assets/79528/84ad6e3b-7143-4b04-8646-092e43207b81)

As a consequence, not all functions are discovered in the binary.

**To Reproduce**

- Grab the .apk from https://apkpure.net/apple-music/com.apple.android.music/download URL.

- unzip Apple\ Music_4.6.0-beta_Apkpure.apk

- Load the extracted 'lib/arm64-v8a/libandroidappmusic.so' file in Ghidra and analyze it.

**Expected behavior**

Things should just work as usual.

**Screenshots**

![Screenshot_2024-01-16_10-18-48](https://github.com/NationalSecurityAgency/ghidra/assets/79528/8e54fec1-fa30-423b-ba41-85d553bd27ae)

**Environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Java Version: OpenJDK 17.0.9 2023-10-17
 - Ghidra Version:  11
 - Ghidra Origin: Official GitHub distro
 
**Additional context**
Thanks for the help!

**Comment by ryanmkurtz** [comment]
Reproduced it in 11.0, but not in the `patch` branch for the upcoming 11.0.1 release.  Trying to track down what exactly fixed it.

**Comment by ryanmkurtz** [comment]
Fixed by 2848eb56a531ef9f366fb1209f11f6172504331d.

Duplicate of #6047.
Duplicate of #6068.
