### ISSUE TITLE
Get Bytes from Blocks extracted from BasicBlockModel

### ISSUE THREAD

**Issue by rrivera1849** [NationalSecurityAgency/ghidra#613]
I was wondering how I would go about getting the bytes that comprise each block outputted from BlockModel's such as BasicBlockModel. 

Thanks!

**Comment by saruman9** [comment]
`BasicBlockModel`'s methods inherited from class [`ghidra.program.model.block.SimpleBlockModel`](http://ghidra.re/ghidra_docs/api/ghidra/program/model/block/SimpleBlockModel.html).

```java
BasicBlockModel basicBlockModel = new BasicBlockModel(currentProgram);
CodeBlock[] codeBlock = basicBlockModel.getCodeBlocksContaining(currentAddress, monitor);
Listing listing = currentProgram.getListing();
CodeUnitIterator codeUnitIterator = listing.getCodeUnits(codeBlock[0], true);
while (codeUnitIterator.hasNext()) {
    printf("%s\n", codeUnitIterator.next());
}

```
