### ISSUE TITLE
Almost all functions from esp8266 lib/*.a files are being skipped during Function ID processing as NO_DEFINED_SYMBOL

### ISSUE THREAD

**Issue by wisemanny** [NationalSecurityAgency/ghidra#6135]
Team,

I am looking for advice. I am trying to reverse engineerr esp8266 firmware using Function ID. Espressif provides a list of .a files: https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/components/esp8266/lib

I tried importing them as .a files as well as unpacking to a set of .o files. I see they have debug information:
```
 10 Sections:
  9 Idx Name          Size      VMA       LMA       File off  Algn
  8   0 .literal      00000014  00000000  00000000  00000034  2**2
  7                   CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE
  6   1 .text         00000097  00000000  00000000  00000048  2**2
  5                   CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE
  4   2 .data         00000000  00000000  00000000  000000df  2**0
  3                   CONTENTS, ALLOC, LOAD, DATA
  2   3 .bss          00000000  00000000  00000000  000000df  2**0
  1                   ALLOC
18    4 .debug_frame  00000044  00000000  00000000  000000e0  2**2                                      1                   CONTENTS, RELOC, READONLY, DEBUGGING, OCTETS                                      2   5 .debug_info   00000247  00000000  00000000  00000124  2**0                                      3                   CONTENTS, RELOC, READONLY, DEBUGGING, OCTETS                                      4   6 .debug_abbrev 000001ef  00000000  00000000  0000036b  2**0                                      5                   CONTENTS, READONLY, DEBUGGING, OCTETS                                             6   7 .debug_loc    000000d3  00000000  00000000  0000055a  2**0                                      7                   CONTENTS, RELOC, READONLY, DEBUGGING, OCTETS                                      8   8 .debug_aranges 00000020  00000000  00000000  0000062d  2**0                                     9                   CONTENTS, RELOC, READONLY, DEBUGGING, OCTETS                                     10   9 .debug_line   00000220  00000000  00000000  0000064d  2**0                                     11                   CONTENTS, RELOC, READONLY, DEBUGGING, OCTETS
 12  10 .debug_str    00000206  00000000  00000000  0000086d  2**0
 13                   CONTENTS, READONLY, DEBUGGING, OCTETS
 14  11 .comment      00000022  00000000  00000000  00000a73  2**0
 15                   CONTENTS, READONLY
 16  12 .xtensa.info  00000038  00000000  00000000  00000a95  2**0
 17                   CONTENTS, READONLY
 18  13 .xt.lit       00000008  00000000  00000000  00000acd  2**0
 19                   CONTENTS, RELOC, READONLY
 20  14 .xt.prop      000000c0  00000000  00000000  00000ad5  2**0
```

But when I do Populate FidDb from programs.... I get such result:

```
3884 total functions visited
3 total functions added
3881 total functions excluded
Breakdown of exclusions:    NO_DEFINED_SYMBOL: 2624
    IS_THUNK: 0
    DUPLICATE_INFO: 0
    MEMORY_ACCESS_EXCEPTION: 0
    FAILS_MINIMUM_SHORTHASH_LENGTH: 1257
    FAILED_FUNCTION_FILTER: 0
```

Most of the functions are skipped because of NO_DEFINED_SYMBOL.

I tried exporting all global symbols to a txt file and used it as a common symbols file, still nothing. It skips most of the function. Is there anything I am missing?

**Comment by mumbel** [comment]
Your post is missing some serious details, like which binary you loaded to get that number, or what binary that output is even from, and how much you did after loading, if anything.  I loaded a single .o and got more than that without any issue.

One thing is relocations, which I don't know would effect all, but not for the symbols in my sample elf I tried.  All the relocations were just stubbed out with warnings, I've opened a pull request fixing the notable relocations based on binutils, I found zero documentation however.

**Comment by wisemanny** [comment]
@mumbel that ojdump was from one of the .o files I extracted from the .a files from esp8266 lib folder (linked above). I do not recall which one it was, but I tried a few and all gave the same result (in terms of what data in includes). I will do a new project, clean import and FidId gen and will make screenshots to post here.

**Comment by wisemanny** [comment]
I feel that my experience is the same so far. Either it is not ready, or requires more qualified usage. Well, at least we tried. Maybe someone can find a time to improve this.

**Comment by ghidra1** [comment]
Unfortunetly, it appears nobody has taken the time to implement ELF Relocations for the Xtensa processor.  This will have severe impact on the analysis of the object modules contained with the various library archives.  This issue should be resolved first.  Notice all the red-bookmarks within the listing when a .o is imported.

**Comment by ghidra1** [comment]
I imported a single .o file from one of the archives you identified - even with the relocation error - and it appeared to igest properly.
![image](https://github.com/NationalSecurityAgency/ghidra/assets/48333017/93e2f9c3-0413-4604-a1b6-74a8c42dcf4e)

**Comment by ghidra1** [comment]
All the .o program files must be analyzed.  If they are not analyzed there will be no functions to import.

**Comment by mumbel** [comment]
@ghidra1  https://github.com/NationalSecurityAgency/ghidra/pull/6138

I couldn't find a description of any besides trying to parse through binutils, but the R_XTENSA_32 seems to be the majority of it in terms of missing bytes... and since here they're .o not sure what unlinked even expects

**Comment by ghidra1** [comment]
@mumbel I have in a few cases (e.g., x86-64 and MIPS) taken the time to generate a GOT to facilitate external linkages.  I generally use the block name `%got` when I fabricate one on import.  Otherwise, the call to external functions are missing any type of symbol reference.  In the case of FID, it masks-off operand values making such references less significant.

**Comment by wisemanny** [comment]
> All the .o program files must be analyzed. If they are not analyzed there will be no functions to import. FID relies on the instructions associated with each function to generate a signature. Without analysis none of the functions will be disassembled.

Oh, that is good to know. I will try again. Thank you.

**Comment by wisemanny** [comment]
Yes, thanks.
