### ISSUE TITLE
dsPIC30F6014 getAddress returns different value based on quotes

### ISSUE THREAD

**Issue by lYlantis** [NationalSecurityAgency/ghidra#6136]
**Describe the bug**
Getting an address from the default address space using quotes versus no quotes changes the return value on a dsPIC30F6014 binary.

**To Reproduce**
1. Compile program with the [XC16 compiler](https://www.microchip.com/en-us/tools-resources/develop/mplab-xc-compilers/downloads-documentation#XC16):
```C
#include <xc.h>
int main(void);
unsigned int Add(unsigned int a, unsigned int b);
unsigned int x, y, z;

int main(void) {
  x = 2;
  y = 5;
  z = Add(x,y);
  return 0;
}

unsigned int Add(unsigned int a, unsigned int b) {
  return(a+b);
}
```
2. Compile for dsPIC30F6014:

```bash
xc16-gcc -mcpu=30f6014 -o add.elf add.c
```
3. Open up program in Ghidra 
4. Open up the python terminal and type the following
```
cp = currentProgram.getListing()
af = currentProgram.getAddressFactory()
das = af.getDefaultAddressSpace()

das.getAddress("0x1ca")
das.getAddress(0x1ca)
```

**Expected behavior**
I expect that the value in curr_pc and curr_pc2 are the same and point to rom:0001ca. 

**Screenshots**
![ghidra-currpc](https://github.com/NationalSecurityAgency/ghidra/assets/11239651/e0fe3acb-d619-46eb-8882-14c1d438d637)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 Linux 5.15.0-91-generic amd64
 - Java Version: 17.0.9
 - Ghidra Version: 10.3.3
 - Ghidra Origin: Ghidra Github.

**Additional context**
We wrote a new emulator based on the new emulation API from feedback in https://github.com/NationalSecurityAgency/ghidra/issues/5854. I ran into this issue when trying to validate our new setup. I tried the same series of commands on an x86 binary and both calls returned the same address. 

0xe5 is half of 0x1ca

**Comment by mumbel** [comment]
read the documentation. this is working as intended.

**Comment by ryanmkurtz** [comment]
Each address in PIC corresponds to 2 bytes.  When you use quotes, you are referencing the literal address.  When you use an integer value, you are using a byte offset (which accounts for all bytes), and Ghidra is mapping that to the corresponding address for this specific processor.  Hence the "0xe5 is half of 0x1ca".

While confusing, it is correct.

**Comment by lYlantis** [comment]
Thanks for the explanation!
