### ISSUE TITLE
M16C/56 Frimware reverse engineering with Ghidra

### ISSUE THREAD

**Issue by zaki1213-2** [NationalSecurityAgency/ghidra#6139]
Hi guys

I want to do reverse engineering for M16C/56 frimware but the ghidra I use 10.2.3 doesn't have M16C/56 language, what should I do?

**Comment by ryanmkurtz** [comment]
We do not currently support this processor.

**Comment by mumbel** [comment]
FYI  https://github.com/NationalSecurityAgency/ghidra/discussions/4804

**Comment by zaki1213-2** [comment]
> @zaki1213-2, you could try this: https://github.com/silverchris/m16c

I've tried installing this but my ghidra can't read it or it doesn't show up in the processor options, does he need another way to install it?

**Comment by ryanmkurtz** [comment]
I just tried it and got it working.  Download the repo, and unzip it to the `Ghidra/Processors/` directory.  Then, to get it to show up, you have to create an empty `Modules.manifest` file in the `m16c` directory.  This is the thing that Ghidra looks for when finding modules.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/5378554/48fb275e-091e-4da6-997c-7f95a39b9ff3)

**Comment by zaki1213-2** [comment]
> I just tried it and got it working. Download the repo, and unzip it to the `Ghidra/Processors/` directory. Then, to get it to show up, you have to create an empty `Modules.manifest` file in the `m16c` directory. This is the thing that Ghidra looks for when finding modules.
> 
> ![image](https://private-user-images.githubusercontent.com/5378554/299317025-48fb275e-091e-4da6-997c-7f95a39b9ff3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDIxODgsIm5iZiI6MTcwOTg0MTg4OCwicGF0aCI6Ii81Mzc4NTU0LzI5OTMxNzAyNS00OGZiMjc1ZS0wOTFlLTRkYTYtOTk3Yy03Zjk1YTM5YjlmZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMjAwNDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYyNTkzZDEzODgwZmE5NGNkODcyMmQyZTJiNDJlYWI0YjlhMzRmYzRmYjJlMGM1ZmNjYjU3NjA2N2ZiNWY4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SWHuJ49twgYYbHdBdz-IUpLn0uJktskqGBAP07ZkjCU)

after I read about the M16C it requires the Eclipse Ghidradev plugin. I don't understand how to install it and what the function of Eclipse Ghidradev is, I'm still a beginner in reverse engineering.

**Comment by zaki1213-2** [comment]
> I just tried it and got it working. Download the repo, and unzip it to the `Ghidra/Processors/` directory. Then, to get it to show up, you have to create an empty `Modules.manifest` file in the `m16c` directory. This is the thing that Ghidra looks for when finding modules.
> 
> ![image](https://private-user-images.githubusercontent.com/5378554/299317025-48fb275e-091e-4da6-997c-7f95a39b9ff3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDIxODgsIm5iZiI6MTcwOTg0MTg4OCwicGF0aCI6Ii81Mzc4NTU0LzI5OTMxNzAyNS00OGZiMjc1ZS0wOTFlLTRkYTYtOTk3Yy03Zjk1YTM5YjlmZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMjAwNDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYyNTkzZDEzODgwZmE5NGNkODcyMmQyZTJiNDJlYWI0YjlhMzRmYzRmYjJlMGM1ZmNjYjU3NjA2N2ZiNWY4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SWHuJ49twgYYbHdBdz-IUpLn0uJktskqGBAP07ZkjCU)

![Screenshot 2024-03-08 031202](https://github.com/NationalSecurityAgency/ghidra/assets/126563494/c0672f6a-cd1d-4b41-bf92-328edd1128d9)

and one more thing, why doesn't the function row appear on the m16c in the Function menu like on the Renesas V850/RH850 processor or on the M32R, can't the file be reverse engineered? Or do I have to install a plugin called Eclipse Ghidradev?

**Comment by ryanmkurtz** [comment]
You shouldn't need the Eclipse GhidraDev plugin for anything.  If they processor is showing up for you in Ghidra, you installed it correctly.

**Comment by zaki1213-2** [comment]
> You shouldn't need the Eclipse GhidraDev plugin for anything. If the processor is showing up for you in Ghidra, you installed it correctly.

yes the language appears but after I open the file, the contents of the Function menu are missing or no data appears for reverse. I don't know what's wrong, do I have to learn more about this or a regular m16C processor can't be used on an m16c/56 group , I got the github m16c url from here and suggested installing that plugin https://github.com/esaulenka/ghidra_m16c

**Comment by zaki1213-2** [comment]
![Screenshot 2024-03-08 232407](https://github.com/NationalSecurityAgency/ghidra/assets/126563494/7da15346-cbde-43f7-ada4-9d363d82c3f5)
What I mean by this is that nothing appears at all, the data that you want to reverse

**Comment by ryanmkurtz** [comment]
You might have to manually kick off disassembly by selecting an address (ideally the entry point) and pressing the `d` keyboard key.

**Comment by zaki1213-2** [comment]
> You might have to manually kick off disassembly by selecting an address (ideally the entry point) and pressing the `d` keyboard key.

Oh yeah, where can I learn more about Ghidra and its shortcuts? Usually I learn about Ida Pro but it's too difficult for me
