### ISSUE TITLE
Incorrect fd_set size

### ISSUE THREAD

**Issue by catsuryuu** [NationalSecurityAgency/ghidra#615]
**Describe the bug**
fd_set size should be 128, not 512.
fds_bits field type should be __fd_mask[32], not __fd_mask[128].

**Environment:**
 - OS: [Ubuntu 16.04.6 LTS]
 - Java Version: [11.0.1]
 - Ghidra Version: [9.0.2]

**Comment by ghidra1** [comment]
Issue should be resolved within archive(s) released with Ghidra 10.1
