### ISSUE TITLE
Added Change HTTP-Client User-Agent option to mitigate Symbol Server blacklist

### ISSUE THREAD

**Issue by sylv-io** [NationalSecurityAgency/ghidra#6152]
Greeting,
It is no longer possible to load the PDB from the Intel Symbol Server. https://software.intel.com/sites/downloads/symbols/
Looking at the logs, you can see that I get a http error 403 (Forbidden) as a response:

```
2024-01-25 14:44:37 DEBUG (HttpSymbolServer) HttpSymbolServer[https://software.intel.com/sites/downloads/symbols/]: Checking exist for []: https://software.intel.com/sites/downloads/symbols/ HEAD  
2024-01-25 14:44:37 DEBUG (HttpSymbolServer) HttpSymbolServer[https://software.intel.com/sites/downloads/symbols/]: Response: 403  
```

It looks like Intel has blacklisted the "Ghidra_HttpSymbolServer_client" User-Agent form from accessing the symbol server...

You can check this behavior with curl:
```
[sylv .ghidra_11.0_DEV]$ curl -o /dev/null -s -w "%{http_code}\n"  https://software.intel.com/sites/downloads/symbols/
200
[sylv .ghidra_11.0_DEV]$ curl --user-agent Ghidra_HttpSymbolServer_client -o /dev/null -s -w "%{http_code}\n"  https://software.intel.com/sites/downloads/symbols/
403
```

Is it possible to change the user agent used by Ghidra? If not, we should probably add an option to change the agent, or even not use an identifiable agent at all.

Any thoughts?

**Comment by sylv-io** [comment]
workaround:
Adapt `GHIDRA_USER_AGENT` in `Ghidra/Features/PDB/src/main/java/pdb/symbolserver/HttpSymbolServer.java`.

**Comment by sylv-io** [comment]
cc @dev747368

**Comment by dev747368** [comment]
@sylv-io, does the intel server have stuff that you need?

As issue #3109 notes, the intel server doesn't serve anything other than the original binary, not any pdbs.

I suspect that their url and the other non-pdb urls should be removed from the default list.

**Comment by sylv-io** [comment]
@dev747368 unfortunately, no. :/
I created this issue before looking at the contents of this server.
It makes sense to remove it from the default list :+1: 

However, imho we should still add a way to spoof the ua in case other servers adapt similar mechanisms.
