### ISSUE TITLE
RFC: Include BinExport as a native exporter format in Ghidra

### ISSUE THREAD

**Issue by cblichmann** [NationalSecurityAgency/ghidra#6154]
**Is your feature request related to a problem? Please describe.**
In order to use [BinDiff](https://github.com/google/bindiff) for program diffing, one needs to export binary disassembly first.
For Ghidra, there is the a version of the companion project BinExport, which exports into the protobuf based format the BinDiff expects. This is implemented as a Ghidra extension and is available here:
https://github.com/google/binexport/tree/main/java

Now, due to the way Ghidra handles extension versions, it is difficult for BinDiff to ship a precompiled extension that works out-of-the-box with multiple Ghidra versions, even when there should be no relevant API differences (like 10.3.2 -> 10.3.3).
Users often complain that they have to manually modify the `extension.properties` with the current version.

**Describe the solution you'd like**
Since BinExport (and BinDiff) are open source, in an ideal world, Ghidra would just include BinExport. What this might look like is up for discussion, but it could be as simple as shipping it as one of the default plugins, similar to "sample" or "MachineLearning", but have it enabled by default.

If this is accepted, I'd be happy to prepare the necessary pull requests to make this happen.

**Describe alternatives you've considered**
Instead of shipping BinExport as a default plugin, include it as a default exporter:

<img width="572" alt="Screenshot 2024-01-26 at 10 15 00" src="https://github.com/NationalSecurityAgency/ghidra/assets/213059/0d436ccb-2cb8-4ad3-9f79-78a9c76b7836">

**Additional context**
- https://github.com/google/binexport/issues/91 - example of the issues users are facing when there is a new Ghidra version, but no pre-compiled binaries yet.
- https://github.com/quarkslab/quokka - Another exporter, by Quarkslab. I can imagine that they might also want to be included after porting it to Ghidra.

**Comment by cblichmann** [comment]
That is good to know :)

I'd personally still like if BinExport would be natively supported, though. Not sure how complicated it is for you to take on another dependency (protobuf and the authoritative binexport2.proto file from the main BinExport repo - the latter could simply be copied, as it changes very infrequently and never in wire-incompatible ways).

**Comment by cblichmann** [comment]
Shall I prepare a PR adding BinExport so we have something more concrete to talk about?

**Comment by ryanmkurtz** [comment]
We'll discuss it, probably on Thursday, and I'll let you know how we'd like to proceed.

**Comment by ryanmkurtz** [comment]
@cblichmann, we talked about it, and agreed a PR would be a good next step to further evaluate the possibility of integration.  We noticed things like

https://github.com/google/binexport/blob/5795afc727e7ab66072ea12b38f3e9c978bfa046/java/src/main/java/com/google/security/binexport/BinExport2Builder.java#L431-L434

and it would be helpful to have something closer to a final version in hand.

**Comment by cblichmann** [comment]
Sounds good, I'll try and come up with a PR for this around next week.

**Comment by cblichmann** [comment]
@ryanmkurtz I uploaded a first version - obviously took a bit longer than a week :)

**Comment by ryanmkurtz** [comment]
Thanks!

**Comment by ryanmkurtz** [comment]
@cblichmann, is the exporter currently the only integration that exists between Ghidra and BinDiff?  Or are there other plugins that allow for things like visualization within Ghidra?

**Comment by cblichmann** [comment]
Currently the only integration, I haven't had time to do more. But it'd be useful to integrate with Ghidra's graph views eventually.

**Comment by ryanmkurtz** [comment]
We can reopen this if you return to it one day.
