### ISSUE TITLE
How to modify a `StructureDB`?

### ISSUE THREAD

**Issue by HJfod** [NationalSecurityAgency/ghidra#6155]
I'm trying to modify an existing class definition through a script, however `ProgramBasedDataTypeManager.getDataType` returns a `DataType` whose concrete type is `StructureDB`, which is not visible to scripts. Is there a way to convert the value to a `StructureDataType` and modify it through there? Or do I have to create a new `StructureDataType` and override the old definition, and if so, how do I iterate the fields of the old `StructureDB` to be able to copy them over to the new structure?

I'm using Ghidra 11.0 with JDK 17.0.9.

```java
final var manager = currentProgram.getDataTypeManager();
var classDataMembers = manager.getDataType(classDataTypePath);
classDataMembers.growStructure(4);
//               ~~~~~~~~~~~~~ Undefined, classDataMembers has type DataType
var asStruct = (StructureDataType) classDataMembers;
//             ~~~~~~~~~~~~~~~~~~~ Throws a ClassCastException since classDataMembers is a StructureDB instead
```

**Comment by astrelsky** [comment]
It is a `Structure`. Use the methods in the interface.

**Comment by HJfod** [comment]
Oh I see, don't know how I managed to overlook that while looking at the docs. Thank you!
