### ISSUE TITLE
Paths with a space are not supported

### ISSUE THREAD

**Issue by PatAtAlludo** [NationalSecurityAgency/ghidra#6163]
**Describe the bug**
If the target binary is on a path that includes a space the binary can not be accessed on Mac eg. /Volumes/MyPassport 4/Jira/ . This fails even with a symlink to that directory

**To Reproduce**
1. Open ghidra 
2. attempt to open a binary that is on a path that includes a space (ascii 0x20) such as "/Volumes/MyPassport 4/Jira/"
3. from the GUI there is no way to access any file on a path that has a space in it

**Expected behavior**
In most current operating systems paths and file names are allowed to have spaces. Weshould be able too open files that are on such a filesystem

**Screenshots**
n/a

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: [e.g. macOS 13.5.2 (22G91)
 - Java Version: openjdk version "21.0.1" 2023-10-17 LTS
                 OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
                 OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)
 - Ghidra Version: 11.0 2023-dec-22 0936 EST
 - Ghidra Origin: official GitHub distro 

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
I am not having issues with spaces.  Can you try to import a binary that is in a directory with spaces inside your home directory?  I am suspecting the issue has more to do with your mounted drive.

**Comment by PatAtAlludo** [comment]
An update to MacOS changed the mount point. In finder the path was still shown as /Volumes/My Passport/... but in the shell it was shown as /Volumes/MyPassport/... The inconsistency is what threw me off.
 Thanks!
