### ISSUE TITLE
ghidraGo does not navigate the visible cursor position in the code listing

### ISSUE THREAD

**Issue by blbelew** [NationalSecurityAgency/ghidra#6166]
**Describe the bug**
The GhidraGo plugin will open a CodeBrowser window with a listing for the specified symbol/address, but it doesn't actually center the visible display on that location; rather, the listing is "scrolled all the way up" to address 0. Pressing any navigation key, like up or down, *will* center the view on the desired address. So it seems like the GhidraGo plugin is setting the active cursor position, but not centering the view on it. 

**To Reproduce**
1. Set up and enable the GhidraGo plugin
2. Analyze a sample binary, go to any function in the listing, right click -> Copy Special -> Local GhidraURL. 
3. In a terminal, use ghidraGo to open the link, e.g. `ghidraGo ghidra:/home/user/.ghidra/project?/test.bin#08000000`
4. Ghidra will open up a code browser, but the listing will not display the specified address (e.g. 0x08000000) until hitting the up or down arrows.

**Expected behavior**
The GhidraGo plugin navigates the listing so the specified address/symbol is visible on the screen. 

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: 17.0.7
 - Ghidra Version: 11.0
 - Ghidra Origin: official github 11.0 release

**Comment by dragonmacher** [comment]
I was able to reproduce the issue.
