### ISSUE TITLE
Ghidra Headless Module not found module

### ISSUE THREAD

**Issue by smile-e3** [NationalSecurityAgency/ghidra#6172]
1. I can import utils module in ghidra
![image](https://github.com/NationalSecurityAgency/ghidra/assets/54340060/e0bf25b9-dc64-47b1-ba66-291512b16056)

2. headless error: ImportError: No module named utils when i in ghidra headless

![image](https://github.com/NationalSecurityAgency/ghidra/assets/54340060/2158a3ed-9065-4e0c-9526-80cb178db10b)

**Comment by smile-e3** [comment]
ghidra version is v11.0

**Comment by ryanmkurtz** [comment]
Are you using the built in Jython or a 3rd party CPython extension?  What is the `utils` module?  I don't have that.

**Comment by smile-e3** [comment]
> Are you using the built in Jython or a 3rd party CPython extension? What is the `utils` module? I don't have that.

I using the built in Jython，Used to generate graphics, possibly due to the use of headless mode, the third library of gui is prohibited from being called.
