### ISSUE TITLE
NAT works with Ghidra 9.0.2, files download etc.; Checkout function broken.

### ISSUE THREAD

**Issue by ILOVEPIE** [NationalSecurityAgency/ghidra#618]
**Describe the bug**
It is possible to get ghidra working through a NAT however checking out files always fails, the files download but the server never registers that they have been checked out. All other functions of ghidra work with this.

**To Reproduce**
1.  in the server wrapper you have to set the property java.rmi.server.hostname to your NAT's DNS hostname and java.rmi.server.useLocalHostname to true.

**Expected behavior**
Checkouts should succeed.

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: All
 - Java Version: Tested on 11.0 and 12.0
 - Ghidra Version: 9.0.2

**Additional context**
I suspect this is due to the client sending the public ip address along with the checkout information or something, I haven't actually looked at the code yet for this specific issue.

**Comment by ryanmkurtz** [comment]
#645
