### ISSUE TITLE
"Assignment to constant" stops decompilation process alltogether

### ISSUE THREAD

**Issue by PlasmaHH** [NationalSecurityAgency/ghidra#6181]
**Describe the bug**
When decompiling something and ghidra encounters what appears to it a write to some constant it will stop the decompilation of a function completely instead of just marking that one statement as possibly bogus

**To Reproduce**
* For MCS96 create a file containing all 0xFF and just at 0x2080 ( the entry point of most MCS96 CPUs) the bytes 0xcc 0x00 which is the instruction "POP ZR". 
* go to that location, ghidra will name it VECTOR_Reset and depending on the settings tries to decompile it or you manually have to make it
* It will error out on the decompilation window with "Low-level Error: Assignment to constant at r0x2080"

**Expected behavior**
Expected behaviour is to just continue with decompilation just like in the case of just writing to a read only location. In that case the decompilation contains some warnings about it, but otherwise works fine.

**Screenshots**
![Screenshot_20240202_084628](https://github.com/NationalSecurityAgency/ghidra/assets/1965659/7dcb28e4-b528-4de8-83ef-abd113f34021)

**Environment (please complete the following information):**
 - OS: linux kernel 6.7.1
 - Java Version: 17.0.9
 - Ghidra Version: 11
 - Ghidra Origin: opensuse tumbleweed 

**Additional context**
It seems that ghidra distinguishes between read only locations and constants. While for read only locations decompilation continues, this seems to be a harder error. However on that specific CPU "POP ZR" (which sounds nonsensical since ZR as the zero register will always return 0, a constant) is valid and will basically just change the stack pointer..

**Comment by ghidracadabra** [comment]
I can reproduce this.  Typically this sort of issue can be fixed by adjusting the pcode generated for the instruction.
