### ISSUE TITLE
Make decompiler preserve memory accesses that seem to make no change

### ISSUE THREAD

**Issue by PlasmaHH** [NationalSecurityAgency/ghidra#6184]
**Is your feature request related to a problem? Please describe.**
In certain situations there are reads and writes to memory locations that seem in the end to leave that location unchanged when exiting the function. However those might have consequences that ghidra is not aware of (e.g. memory mapped registers, synchronisation variables with other threads etc.)

For example:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/1965659/91a2268e-c045-4558-97da-c89be613196f)

Here all accesses to the BANK_SELECT variable are invisible in the C code, and would one compile it back, they would not be there. 

**Describe the solution you'd like**
I think that even though they seem to have no impact, such accesses should always be generated for the C code and only have an option to suppress them if so desired.

**Describe alternatives you've considered**
Making the .bss segment in which that variable resides will make ghidra recognize it:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/1965659/e06a8aee-9b0a-4eb7-9bb7-c68c4b4d1ad0)
However this would then also apply to all other variables in that segment, which is quite possibly not what is desired.

**Additional context**
A really useful solution/workaround for this whole thing that could also help possibly in other situations is that all datatypes could be made volatile, which would give maximum flexibility: it could be chosen per variable how it is handled, and even per function by making pointers to volatile. ( I still think the best would be to have ghidra per default recognize these reads/writes as this is the least surprising generated C code from the given assembler. If someone then wants more finegrained control they could disable it and make things volatile selectively )

**Comment by ghidracadabra** [comment]
You can make `BANK_SELECT` volatile without making the entire .bss section volatile by navigating to `BANK_SELECT`, right-clicking on it, Data->Settings... and then changing the "Mutability" to "volatile" (click in the Settings column to bring up a drop-down menu).

**Comment by PlasmaHH** [comment]
Ah, nice, thanks, yes that works. Being a C++ programmer my intuition was to make it part of the datatype but I was not aware of that field being a dropdown that could change
