### ISSUE TITLE
Sign executables in releases

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#621]
Unfortunately my antivirus has decided that gnu_demangler.exe , sleigh.exe, pdb.exe and decompile.exe are not safe and required removal. While it isn't something I'm worried about since they were just WS.Reputation.1 (ie "I don't know what this is do I'm going to delete it on you") risks, considering the NSA's reputation it is a good idea to sign the executables that are being released via [https://www.ghidra-sre.org/](url)

**Comment by ryanmkurtz** [comment]
We have no plans to sign our executables.  Instead, the route we decided to go is to allow the user to rebuild the native binaries from a ghidra release, which is described in #3387.  This will be available in the 10.1 release.
