### ISSUE TITLE
Better decompilation bitfield representation

### ISSUE THREAD

**Issue by theclub654** [NationalSecurityAgency/ghidra#6210]
Hello i was wondering if it would be possible to have in the de compiler to see which individual bit thats being referenced in the photo below if referencing palo->0x2D8 it manipulating a bitfeild but its kinda hard to read and know which bit field its reading 
![Screenshot 2024-02-08 191049](https://github.com/NationalSecurityAgency/ghidra/assets/61169936/175f3875-da0b-4003-9e8c-8deafa43db71)

**Comment by ryanmkurtz** [comment]
Duplicate of #647
