### ISSUE TITLE
Fractional UI Scaling + Text Scaling

### ISSUE THREAD

**Issue by Hordeking** [NationalSecurityAgency/ghidra#6211]
**Describe the solution you'd like**
Please implement fractional UI scaling if at all possible. I can modify launch.properties for some control of this, but with unity scaling, the user interface elements and disassembly texts are small and difficult to read on 1080p HD. On 2x, the text is much more readable, but the UI elements take up all of the screen and make it difficult to navigate. It would be nice if I could size up the text and icons a little without drastically rescaling EVERYTHING in the UI, including the splash screen and logo, project window, etc.

Likewise, on gedit/xed in linux, the GTK text editors allow you to scale up/down the text using ctrl-mousewheel (or in the settings dialog). It would be nice to do it without having to edit a config file and restart ghidra. Sometimes I just want to zoom in, look at something in the disassembly, then zoom back out, for instance. If only one thing could be implemented, I would ask for zoomable text to be implemented on a per window basis (decompiler window has a different zoom from disassembly, and so on)

Maybe these menu text and icon graphics can zoom a bit if one hovers over them like a tooltip?

This also kind of works in reverse on a 720p display, where I may also want to zoom out on a lot of the user elements, but keep the text the same size.

**Describe alternatives you've considered**
Played around with the operating system's fractional scaling facilities, but I liked the general scale things are displayed at at the default 1x, when I increased the OS UI elements, they also took up a lot more space than I wanted.

I tried playing with the theming in ghidra, but there I have to edit EACH piece of the theme individually. I don't necessarily want to zoom everything, or just a very few things, I have certain classes of things I would like to be zoomable (like text). Perhaps there's a nice solution this way like heritable styles, but I didn't really see them.

If you have some suggestions, I'm interested.

**Comment by qiratdahaf** [comment]
$ nano ~/gidhra/support/launch.properties

look for "VMARGS_LINUX=-Dsun.java2d.uiScale=1" & change value to 2.5
reload. it fixed the ui scaling issue for me
