### ISSUE TITLE
GhidraDev - A supported JDK is not associated with this Ghidra installation.

### ISSUE THREAD

**Issue by TimRegeant** [NationalSecurityAgency/ghidra#6215]
issue resolved...

**Comment by TimRegeant** [comment]
closed...

**Comment by foxtrotdev** [comment]
OK, how did you solve this?

**Comment by TimRegeant** [comment]
Hi, to solve this I had to specifically install version 17 of the JDK.

Since my linux system had version 21 installed I used this guide to install an alternative version of the JDK https://medium.com/@ayeshajayasankha/how-to-install-and-switch-between-alternative-java-versions-66b3671fc382.

Instead of downloading from the Oracle site I downloaded the v17 JDK at https://adoptium.net/temurin/archive/?version=17.

**Comment by foxtrotdev** [comment]
Thanks. I solved it too. Worth to note is that I had to download ghidra public instead of ghidra build.
