### ISSUE TITLE
Error disassembling a 68000 instruction?

### ISSUE THREAD

**Issue by TimRegeant** [NationalSecurityAgency/ghidra#6219]
Have a problem in the disassembly listing of a 68000 program.

Address 1816a should be the start of a routine, but it is locked as the low word of a long address.  Hovering over the red X shows "Error [Bad Instruction]: Failed to disassemble at 0001816a due to conflicting data (flow from 0001816a)"

![ghidra-error](https://github.com/NationalSecurityAgency/ghidra/assets/55998136/8e82ee1d-cdb3-4927-8c9a-7773ed2821f4)

It is only referenced in 1 BSR call:

![ghidra-references](https://github.com/NationalSecurityAgency/ghidra/assets/55998136/2071aa17-915a-4cc7-9b6f-f7e047b0d7ea)

But how do I refactor the disassembly to get the routine disassembled?  The code browser seems to lock the long 18168 as a data address which is strange since all the references to 18168 are word accesses as seen above. Any help is appreciated.

**Comment by ryanmkurtz** [comment]
If you have that adderss selected in the Listing, you can press `c` to clear what's there, and then `d` to disasemble.

**Comment by TimRegeant** [comment]
Thank you very much, that worked fine.
