### ISSUE TITLE
Allow untruncated comments

### ISSUE THREAD

**Issue by TimRegeant** [NationalSecurityAgency/ghidra#6221]
**Is your feature request related to a problem? Please describe.**

I am working with some bit-wise hardware registers and having the address description as a comment helps with clarity.  Ex)

![ghidra-hw-comment](https://github.com/NationalSecurityAgency/ghidra/assets/55998136/b3968fee-9586-4e22-8613-2865c01d6ede)

However, the comment in the listing window is truncated and doesn't show all the comment lines.

![ghidra-hw-comment-truncated](https://github.com/NationalSecurityAgency/ghidra/assets/55998136/1dd8d79a-4fe8-400d-a4d6-34463adfccfc)

**Describe the solution you'd like**

Would request:
A) An option to not truncate comments and show all lines of the comment in the listing.

B) Alternatively, would request line size and number of lines of the comment be configurable if solution A is not viable.

**Describe alternatives you've considered**

N/A

**Additional context**

Screenshots provided above.

**Comment by ryanmkurtz** [comment]
Also, for the `EOL` comment, you can adjust the Maximum Lines under `Edit -> Tool Options -> Listing Fields -> EOL Comments Field`.

**Comment by TimRegeant** [comment]
Plate is not optimal as it creates noise in analyzing the instruction sequence.  EOL works best with my use case.

Thanks for the Tool Options tip.  I was looking at Edit->Tool Options-> Listing Fields->Post-comments Field which didn't have a max lines options.  Now the listing is displaying all the lines.

![ghidra-hw-comment-truncated_b](https://github.com/NationalSecurityAgency/ghidra/assets/55998136/163443d2-956b-4d6a-81af-332600b3da15)

However, the comment is still truncated as can be seen in the screenshot.

**Comment by ryanmkurtz** [comment]
Can you just reside the field, making it wider?

**Comment by TimRegeant** [comment]
That would be good, but I don't see any grabber points in the Listing window to resize the field dynamically.  Is there a specific way to do that?

**Comment by ryanmkurtz** [comment]
In the toolbar for the Listing window, there is a little icon that looks like bricks.  That will allow you to fully customize all the fields in the listing.

**Comment by TimRegeant** [comment]
Ah, yes, that worked, thanks so much for the help.
