### ISSUE TITLE
Cant use GUI to create reference to overlay memory blocks

### ISSUE THREAD

**Issue by qrkyckling** [NationalSecurityAgency/ghidra#6245]
**Describe the bug**
Can't use "Reference Manager" to create a reference to other memory block.
Using the script "ResolvelX86or....." works though so it seems to be a problem in the GUI only.

**To Reproduce**
1. Go to "Reference MAnager"
2. Click on 'Add reference' (the PLUS sign)
3. Try to create a reference to "syscall::0"

**Expected behavior**
Expecting a reference to syscall::0 block where a function prototype has been created

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/621386/a91678de-ca2e-425f-a9ee-a6c5b9de2684)

While in 10.4 we have an extra window to specify the block name
![image](https://github.com/NationalSecurityAgency/ghidra/assets/621386/36bbcee2-d5da-4a1b-8999-f549ede9e177)

**Environment (please complete the following information):**
 - Java Version: 17.0.9
 - Ghidra Version: 11.0
 - Ghidra Origin: Problem exists in release 11.0, 11.1
 - Last correct version: 10.4

**Additional context**
Bisecting gives
0f95d266c35e6121b1b72ed802ac616eaa58dee7 is the first bad commit

**Comment by qrkyckling** [comment]
This seems to solve the problem for me.
This is probably not a correct patch in any way but proves that the filtering is failing while building the list of addresses.
Should give the original author a pretty good idea of how fix the problem :-)


--- a/Ghidra/Features/Base/src/main/java/ghidra/app/util/AddressInput.java
+++ b/Ghidra/Features/Base/src/main/java/ghidra/app/util/AddressInput.java
@@ -212,7 +212,7 @@ public class AddressInput extends JPanel implements FocusableEditor {
                int width = 0;
                for (AddressSpace space : spaces) {
                        if (!predicate.test(space)) {
-                               continue;
+                               //continue;
                        }
                        String s = space.toString();
                        width = Math.max(width, fm.stringWidth(s));

**Comment by ghidra1** [comment]
Issue is acknowledged.  We will look into adding a user-managed list of OTHER overlay spaces which may be included with the AddressInput control for this dialog.
