### ISSUE TITLE
How to go to the virtual address relative to image base with offset?

### ISSUE THREAD

**Issue by ntqbit** [NationalSecurityAgency/ghidra#6248]
Hello!

There is a way to go to file offset (`file(n)`), but I couldn't find a way to go to relative virtual address.
Is there a symbol defined for the image base, so I could use expression like `BASE+0x123465`, or dedicated function like `file(n)` to go to image base offset ?

Thanks!

**Comment by 90th** [comment]
Calculate image base manually using known RVA and file offset, then navigate using RVA+offset.

**Comment by ntqbit** [comment]
> Calculate image base manually using known RVA and file offset, then navigate using RVA+offset.

Why calculate it? One can obtain the image base from "Memory map" -> "Set Image Base" window.
I can calculate the virtual address manually, but it would be more convenient to have some symbol resolving to the image base.

**Comment by ryanmkurtz** [comment]
As far as I know, there is no standard symbol we create at the image base.  You would have to create a label there yourself, and use it in your goto expressions.

**Comment by ntqbit** [comment]
> As far as I know, there is no standard symbol we create at the image base. You would have to create a label there yourself, and use it in your goto expressions.

That's exactly what I needed. Forgot about labels.
Thank you!
