### ISSUE TITLE
Config Ghidra's shortcuts like Ida's shortcuts

### ISSUE THREAD

**Issue by yooo1999** [NationalSecurityAgency/ghidra#6252]
For many of us that use Ida long time there are shortcuts and some window we are so familiar with them , and it will very usefull to integrate them into Ghidra   :

Shortcuts: 

x - cross reference

Y change type of variable

N - rename function/variable name 

Shift+f12 , then Control+F search string

Shift +f3 then Control+F search function name

Window:
When you click cross reference (for example on function name) in Ida there  is a popup that show you the cross reference , it's very convenient

 I think these adjustments will make Ghidra more convenient for Ida users

**Comment by astrelsky** [comment]
No

**Comment by d-millar** [comment]
You can configure the shortcuts to be whatever you want them to be (more or less).  There are several excellent examples available for IDA-centric Ghidra key mappings files, such as:

https://github.com/JeremyBlackthorne/Ghidra-Keybindings
https://github.com/enovella/ida2ghidra-kb

**Comment by yooo1999** [comment]
@d-millar How can I import kbxml file ( [ida2ghidra-kb ](https://github.com/enovella/ida2ghidra-kb) to Ghidra?

**Comment by d-millar** [comment]
Mr.  Blackthorne’s instructions are probably better than mine:

In Ghidra's CodeBrowser, go to the menu Edit->Tool Options, then click KeyBindings on the left. On the bottom right, click the button Import and select the file ending in .kbxml in the repository. There's a button to restore defaults at any time too.
