### ISSUE TITLE
Ghidra and ida address inconsistent

### ISSUE THREAD

**Issue by smile-e3** [NationalSecurityAgency/ghidra#6256]
I found a problem. The offset addresses of the same function in Ghidra and IDA were inconsistent,When I analyzed the ko file.

Ghidra Address:
module_close function address: 0x0010024b

<img width="1391" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/54340060/a6e5afe3-d79f-43ba-b7b6-b3b07e91760b">

IDA Address
module_close function address：0x20F

<img width="1424" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/54340060/b99e9218-df19-435f-8815-af65ad3c4061">

use the gdb can access base address + 0x20F，can't not access base address + 0x0010024b

**Comment by d-millar** [comment]
@smile-e3 Am not entirely sure I understand the issue.  Gdb gets its base address from the loader, i.e. its base address is where the executable is actually loaded in memory (although it may force that value for consistency between runs).   If you are using IDA to launch gdb (or Ghidra, for that matter), it does its best to map the static program addresses to the dynamically-determined load address.  When used statically (without a debugger), Ghidra (and IDA) essentially choose an arbitrary base address and display addresses either calculated from that base or relative to some label (e.g. .text).  Ghidra is using 0x100000, in your case.  

So, when you say "can't not access base address + 0x0010024b," are you trying to access data in memory at the base address + 0x10024b via gdb?  If so, you have effectively added the real base plus Ghidra's artificial base plus the offset, which, I'm pretty sure, is not what you want and couldn't reasonably be expected to have valid data.  To calculate addresses in gdb from those in Ghidra, you'll need to subtract the artificial base (0x100000) and add the load address.

**Comment by smile-e3** [comment]
> @smile-e3 Am not entirely sure I understand the issue. Gdb gets its base address from the loader, i.e. its base address is where the executable is actually loaded in memory (although it may force that value for consistency between runs). If you are using IDA to launch gdb (or Ghidra, for that matter), it does its best to map the static program addresses to the dynamically-determined load address. When used statically (without a debugger), Ghidra (and IDA) essentially choose an arbitrary base address and display addresses either calculated from that base or relative to some label (e.g. .text). Ghidra is using 0x100000, in your case.
> 
> So, when you say "can't not access base address + 0x0010024b," are you trying to access data in memory at the base address + 0x10024b via gdb? If so, you have effectively added the real base plus Ghidra's artificial base plus the offset, which, I'm pretty sure, is not what you want and couldn't reasonably be expected to have valid data. To calculate addresses in gdb from those in Ghidra, you'll need to subtract the artificial base (0x100000) and add the load address.

Yes, I understand the base address situation
base address is 0x00100000 in Ghidra
The offset address is 0x0010024b-0x00100000=0x24b
base address is 0x00000000 in IDA, the offset address is 20F

**Comment by d-millar** [comment]
OK, on the same page - apologies for the delay, just wanted to make sure we were understanding each other....

So I have a guess, but it's definitely a guess - hoping you can confirm.  Ghidra always defaults the base address to 0x100000 (am pretty sure - will check with others in a bit).  Am guessing IDA is using the value from the ImageBase field in the NT_OPTIONAL_HEADER, obviously a reasonable loader strategy as well.  Can you verify the address in that field in your executable?  Should be roughly 0x010c in from the start of the vuln.ko section in IDA.

**Comment by d-millar** [comment]
OK, I lied - we're definitely using the ImageBase.  I would have thought IDA was too, so....   Any chance your executable is overloading sections?  (Any chance you can share/point us to a copy of the executable?)

**Comment by smile-e3** [comment]
> OK, I lied - we're definitely using the ImageBase. I would have thought IDA was too, so.... Any chance your executable is overloading sections? (Any chance you can share/point us to a copy of the executable?)好吧，我撒谎了 - 我们肯定在使用 ImageBase。我本来以为IDA也是，所以......您的可执行文件是否有可能使部分过载？（您有机会分享/指出我们可执行文件的副本吗？

Use default configuration analysis options. Okay, this is the KO file I analyzed.
[vuln.ko.zip](https://github.com/NationalSecurityAgency/ghidra/files/14444128/vuln.ko.zip)

**Comment by smile-e3** [comment]
> Thanks - and that helps! Good news is IDA and Ghidra almost agree, although I can see why that might not be obvious. In Ghidra (as in your screen capture) , "module_close" is at 0x10024b, i.e. the base address of 0x100000 + an offset of 0x24b. (I didn't realize this was an ELF in my previous post. I don't remember how we calculate the base address off the top of my head - I can look into that if you'd like - but we never set the base address to 0 as this creates collisions with the constant space.) In IDA, the base address is set to 0, and "module_close" is displayed at .text+0x20f. The .text section is located at the base address + 0x3c (in both Ghidra and IDA), so the actual address in IDA is the base address + 0x24b (i.e. 0x3c + 0x20f). So, the only real differences between IDA and Ghidra are the choice of a default base address (0 vs 0x100000) and the way the address is displayed (section+offset vs base_address+offset).

Thanks I understand, in order to be consistent with the offset address debugged in GDB, I need to use 0x24b-0x3c (the starting offset address of .text) = 0x20F
