### ISSUE TITLE
How do the NSA build the release packages (support for Windows/Linux/OSX in one zip)

### ISSUE THREAD

**Issue by agnosticlines** [NationalSecurityAgency/ghidra#626]
Hi folks,

I'm trying to build a ghidra fork currently, and I've built a docker file which will go through and build everything, but the outputted zip lacks the native binaries for osx and windows.

Could you share your setup for building these release packages?

I understand you have to run `gradle buildNatives_$OS$ARCH` but is this possible to do without running three seperate systems for building?

I'm also building with `gradle buildGhidra -PallPlatforms` which seems to include the run scripts which is useful, but doesn't seem to compile the natives. 

I guess what I'm asking is do you folks have any cross compilation setup? Or do you just build on three systems, if the latter how do you combine those cleanly?

**Comment by ryanmkurtz** [comment]
We do a full build on one of the systems, build just the natives on the other 2 systems, and use a simple script to put it all together and zip it up.  We don't really have anything sophisticated that is worth sharing...it's very specific to our machines.  You could also just do a full build on all 3 systems and then unzip them all on top of each other, and zip it back up.

**Comment by agnosticlines** [comment]
Appreciate the response! Just wanted to make sure there wasn't some weird gradle trick
