### ISSUE TITLE
68000: byte immediate instructions not displaying value correctly

### ISSUE THREAD

**Issue by jayoung99** [NationalSecurityAgency/ghidra#6260]
**Describe the bug**

Referencing this older issue here: 

https://github.com/NationalSecurityAgency/ghidra/discussions/6227#discussion-6211093

**To Reproduce**
Affects any of these instructions:

addi.b
andi.b
cmpi.b
eori.b
ori.b
subi.b

The Listing shows word size values if the high bit of the immediate byte value is set.

Ex)   
`000182b4 0c 00 00 ff    cmpi.b       #0xFFFF,D0b`

**Expected behavior**

Should display the byte value.

Ex)
`000182b4 0c 00 00 ff    cmpi.b       #0xFF,D0b`

**Additional context**

I have devloped a fix described here:

https://github.com/NationalSecurityAgency/ghidra/discussions/6241#discussioncomment-8609184

Could someone please review the proposed fix?

**Comment by GhidorahRex** [comment]
Really, we should be using `const8` instead of the raw `d8` for these instructions. See `andi.b` for example.

**Comment by jayoung99** [comment]
Excellent, that is much cleaner and works great.  Can you put the changes in the repository?

**Comment by agatti** [comment]
Would this fix #4191 as well?

**Comment by jayoung99** [comment]
> Would this fix #4191 as well?

Yes, should fix that also.
