### ISSUE TITLE
Accessibility: enableing/disabling analyzers with a keyboard nonfunctional

### ISSUE THREAD

**Issue by TheQuinbox** [NationalSecurityAgency/ghidra#6261]
**Describe the bug**
Using a screen reader, it's super unclear how you toggle the state of an analyzer. The standard keys to check/uncheck a checkbox don't work in the analyzers list. The way I currently have to do it is by focusing the cell in the table next to each analyzer that says true/false, route my mouse with NVDA+Shift+M, then left click with NVDA+Left bracket.
**To Reproduce**
1. Start NVDA and Ghidra.
2. Open the analyzers window.
3. Attempt to check/uncheck analyzers using standard keyboard navigation commands.

**Expected behavior**
In a perfect world, this list would function like a standard list of checkboxes that I can up and down arrow between, and check/uncheck with the space bar. In addition, there wouldn't be an extra cell to the left of each analyzer that says the state, it would be reported directly in the list.
**Environment (please complete the following information):**
 - OS: Windows 10 22H2
 - Java Version: openjdk 11.0.16.1 2022-08-12 LTS
 - Ghidra Version: 11.0.1-20240130
 - Ghidra Origin: Scoop for Windows

**Comment by dragonmacher** [comment]
Thanks for the info.  Fixing this widget is one of the changes we have on the horizon.
