### ISSUE TITLE
Help seems to be broken

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#6265]
**Describe the bug**

Looks like https://github.com/NationalSecurityAgency/ghidra/commit/a88106460b341515e92b88728c54a50349152057 breaks help files compilation.
It adds reference to the `help/topics/KeyboardNavigation/KeyboardNavigation.html` to the `Ghidra/Features/Base/src/main/help/help/TOC_Source.xml`, but there is no such file - now it located at `Features/Docking` subfolder, not `Features/Base`.

**To Reproduce**
1. git pull
2. gradle buildGhidra - it fails
3. comment out line with `tocdef id="Keyboard Navigation"` in `TOC_Source.xml`
4. try to build again

**Environment (please complete the following information):**
 - OS: Win10
 - Java Version: 18.0.1
 - Gradle 8.4
 - Ghidra Version: latest master
 - Ghidra Origin: 63e64d5b2 Thu Feb 29 11:43

**Comment by ryanmkurtz** [comment]
Hmmm, I am not reproducing this.

**Comment by astrelsky** [comment]
> Hmmm, I am not reproducing this.

Can reproduce.

**Comment by ryanmkurtz** [comment]
Seems to be Windows specific

**Comment by AshleyT3** [comment]
+1 (Windows)

**Comment by AshleyT3** [comment]
Seems KeyboardNavigation.html was removed but TOC_Source.xml not updated.
```
Found invalid help:
[JavaHelpValidator] - Found the following 1 invalid links:
Module Base - Missing TOC target ID for definition (<tocdef>):
        <tocdef id="Keyboard Navigation" text="Keyboard Navigation"
                target="help/topics/KeyboardNavigation/KeyboardNavigation.html" />
                [source file="C:\...\ghidra\Ghidra\Features\Base\src\main\help\help\TOC_Source.xml" (line:378)]
```

```
git show a881064
commit a88106460b341515e92b88728c54a50349152057
Author: ghidragon <106987263+ghidragon@users.noreply.github.com>
Date:   Tue Jan 30 11:57:54 2024 -0500
    GP-4267 Quick Action Dialog
...
-src/main/help/help/topics/KeyboardNavigation/KeyboardNavigation.htm||GHIDRA||||END|
...
```

**Comment by dragonmacher** [comment]
> Seems KeyboardNavigation.html was removed but TOC_Source.xml not updated.

It was actually moved (and renamed to end with ".html").

The fix was internal to the help build system and related to using a windows path to lookup into a map that is using standardized path slashes.
