### ISSUE TITLE
Improper Assembly

### ISSUE THREAD

**Issue by wetw0rk** [NationalSecurityAgency/ghidra#6273]
Hello Ghidra Team,

I'm disassembling a binary and it appears that Ghidra reads `0xF3, 0x6e` as `OUTSB.REP DX, RSI`. In IDA these opcodes are converted to `rep outsb`. Is there a reason my assembly looks like this in Ghidra? Is there maybe a setting I need to enable to view the assembly as I do in IDA?

Here is an additional example where another tool `shellnoob` reads `rep outsb` as `0xF3, 0x6E`.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/20763546/f85c28ad-f82e-4f88-8e76-e6c7f14fc665)

Vs Ghidra

![image](https://github.com/NationalSecurityAgency/ghidra/assets/20763546/c89c680a-c1c7-4ec9-b893-e0213fe29835)

This was tested on Version 11.0.1

Thank you

**Comment by wetw0rk** [comment]
Is `DX. RSI` just showing the registers modified by the instructions? Kind off like a comment?

**Comment by GhidorahRex** [comment]
Ghidra has a limitation that the first item in the instruction listing must be the mnemonic, so we put certain prefixes like `REP` and `LOCK` immediately following the mnemonic rather than before. But otherwise they agree on the disassembly.

**Comment by wetw0rk** [comment]
Ok awesome, thank you for the quick response!
