### ISSUE TITLE
Incorrect x86 decompilation produces empty loop

### ISSUE THREAD

**Issue by americusmaximus** [NationalSecurityAgency/ghidra#6275]
**Bug**
Incorrect x86 decompilation produces an empty loop, where it should not be empty.

**To Reproduce**
1. Create new Ghidra project.
2. Import the dll from [implode.zip](https://github.com/NationalSecurityAgency/ghidra/files/14482491/implode.zip)
3. Perform the code analysis.
4. Go to `crc32` exported function.
5. See empty loop in the decompiler view, while ASM view has a bunch of instructions.

**Expected behavior**
A better assembler decompilation is in place, or a visual indication that the parts of assembler was omitted and instructions are not shown/skipped.

**Screenshots**
Empty loop in the decompiler view (should not be empty):
![Loop](https://github.com/NationalSecurityAgency/ghidra/assets/75050995/3bf9130d-7002-416d-8138-238a63c1c380)

Assembler:
![ASM](https://github.com/NationalSecurityAgency/ghidra/assets/75050995/e8b80327-2c69-4df2-b6f7-a7289ec33a7a)

**Attachments**
[implode.zip](https://github.com/NationalSecurityAgency/ghidra/files/14482491/implode.zip)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: "17.0.8" 2023-07-18 LTS
 - Ghidra Version: 11.0.1 PUBLIC
 - Ghidra Origin: Official GitHub

**Comment by astrelsky** [comment]
If you change the return type to int, does it return iVar1?

**Comment by astrelsky** [comment]
What does it look like if you change the return type to int?

**Comment by americusmaximus** [comment]
Tank you. The modification brought things to light.

![Modified](https://github.com/NationalSecurityAgency/ghidra/assets/75050995/9f2fb04e-2abc-4a10-b025-ae077573c995)

**Comment by Wall-AF** [comment]
Add a third parameter also.

**Comment by americusmaximus** [comment]
Thank you all. My issue is solved.
