### ISSUE TITLE
MZ EXE loader segments get out of sync with Program Tree fragments

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#6277]
**Describe the bug**

Program Tree fragments start/end addresses do not reflect memory block adjustments applied by the MZ DOS EXE loader after blocks creation.

**To Reproduce**
1. Import the attached EXE file with default settings.
2. Open the file, skip the analysis (the issue still occurs even after analysis).
3. Bring into view the `CODE_2` block from the "Program Trees" pane.
4. Scroll down to the end, the block should end at 11C3:29DD, but the listing is cut off at 11C3:29CF.

**Expected behavior**
Program Tree fragments start/end addresses should match the ones from the Memory Map pane and listing should allow viewing the whole block.

**Screenshots**

![block_selection](https://github.com/NationalSecurityAgency/ghidra/assets/235740/0dea1b44-6f6f-491e-bff6-775449e33dbe)

**Attachments**
[mz_dos_blocks.zip](https://github.com/NationalSecurityAgency/ghidra/files/14491555/mz_dos_blocks.zip)

**Environment (please complete the following information):**
 - OS: Linux Arch x86_64
 - Java Version: 17.0.10
 - Ghidra Version: 11.1
 - Ghidra Origin: locally built at 317a8814883804f0c4f18c64d97411b1c6d6283e

**Additional context**
You can also try to bring `CODE_3` into view, the start offset does not consider the block adjustment - see screenshot.

**Comment by haarlaj** [comment]
I'm working on another DOS executable (CATS.EXE in bug report #5970) and it has the same behavior as this. It seems to be related to the CODE sections where the source is defined as empty in the memory map. The CODE segments where source is "mz" seem to work correctly.

**Comment by agatti** [comment]
@haarlaj I missed the detail about the lack of blocks' source!  From a quick look at the code it happens to blocks that are split and joined together as part of the adjustment process: https://github.com/NationalSecurityAgency/ghidra/blob/b82294b537ddfcdb66ac9ed1c84df11dbe772d41/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MzLoader.java#L293-L302

So I guess it's those extra blocks whose address bounds are not in sync with the program tree list.

**Comment by ryanmkurtz** [comment]
This is correct.  The initial Program Tree is automatically formed when the memory blocks are created.  Any kind of memory block manipulation that happens later will not be automatically reflected in the Program Tree...it requires manual fix up (which we are not currently doing).

**Comment by agatti** [comment]
It worked, thank you.  By the way, I cannot rename the newly created tree as "Program Tree" even when deleting the incorrectly created old tree.  Is it a bug (and if so, do you want me to file an issue for it)?
