### ISSUE TITLE
Custom char encodings

### ISSUE THREAD

**Issue by mendelmunkis** [NationalSecurityAgency/ghidra#628]
On occasion I deal with programs that have their own character mappings.
For such programs it would be nice to have a feature that allows me to create a new char encoding.

**Comment by dev747368** [comment]
Could you clarify your request a bit.
Are you referring to a custom way to map sequences of bytes to a character value (ie. in java, a unicode character)?
If so, look at java's java.nio.charset.Charset.  If its available in the jvm, Ghidra can use it.

**Comment by dev747368** [comment]
@mendelmunkis, any update, or can I close this issue?

**Comment by mendelmunkis** [comment]
Sorry i forgot to get around to closing it.
I dont have enough java knowledge to use it but yes that does answer my issue.
thanks.
