### ISSUE TITLE
Debugger plugin Static Mappings

### ISSUE THREAD

**Issue by mfthomps** [NationalSecurityAgency/ghidra#6280]
I've a debugger plug that, in Ghidra 10, used TraceModuleManager to add modules and then used DebuggerStaticMappingUtils.addMapping to perform the desired mapping.  That worked because, in my debugging setup, Ghidra 10 did not load any modules.  Now, in Ghidra 11, when I attach the debugger, Ghidra loads the module and sets the static mapping.  However the module range is wrong.  I can use TraceModule.setRange to set the range to what I want, but the mapping remains wrong.  If I try addMapping, it errors with a range conflict.  And I cannot get it to delete the existing mapping.  Of course I can then just click the "Map the current trace to the current program..." button to fix things.  But I'd like my plugin to fix things so the user does not have to.  Any suggestions on a approach to getting this working with Ghidra 11?
Thanks.

**Comment by nsadeveloper789** [comment]
So my first reaction is why is the module range incorrect? Would you consider that a bug on our end, or is this something odd in your setup? Are you willing to explain?

Otherwise, there should be a boolean flag `truncateExisting` that allows you to replace conflicting mappings instead of throwing an exception. Are you already setting this to true? If you can share the stack trace, it may help.

**Comment by mfthomps** [comment]
I don't understand why the module range is incorrect, though is is likely something in my setup.  My gdb server is part of Simics, which I use for RE.  I also use a customized gdb to display results of the monitor command.
My current use case is a 64-bit elf.  Ghidra sets the base address to 400238, which is the .interp section.  When I set the base back to 40000, the mapping works.  
I had missed the truncateExisting flag, and that fixed it.  
Thanks much for the help.

**Comment by nsadeveloper789** [comment]
No worries. Glad it worked. From what you're describing, I think the wrong range is from a bug on our end. If you do `maint info sections` in gdb, I imagine 400238 is the lowest start address of any section. Without the memory map (`info proc mappings`), Ghidra can't compute the actual module base. In future versions, we're considering just forcing module bases to be page aligned.
