### ISSUE TITLE
How to filter columns in the Version Tracking tool.

### ISSUE THREAD

**Issue by rollsch** [NationalSecurityAgency/ghidra#6281]
How do I add filters for the columns that are available in the version tracking matches. Eg I want the following filter.

votes >= 1, #conflicting <= 0, Multiple Source Labels <= 0

Eg I do not want to have to manually sort each column 1 by 1, then apply markup over and over (ultimately this will be scripted however it would be nice for the UI to have a simple filter function).

![image](https://github.com/NationalSecurityAgency/ghidra/assets/1109554/9bd168d3-60b5-4bbf-9115-7789ac43833b)

Am I missing something? There seems to be a few filters you can set up, but not a simple "hide these columns" like you'd see in any common grid control control.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/1109554/accf291f-66df-4023-8b51-01e487e0c112)

Also what are tags and what are they used for? 

![image](https://github.com/NationalSecurityAgency/ghidra/assets/1109554/9a53bbe6-f43d-4026-8139-b2c62dd12afe)

**Comment by rollsch** [comment]
This issue is related https://github.com/NationalSecurityAgency/ghidra/issues/6066

**Comment by dragonmacher** [comment]
Version Tracking is an old soul.  Most Ghidra tables now have the ability to perform custom filtering on any column.  VT was not updated to use this feature.   Using the 'More Filters' button you can tweak more column filters than are on the bottom of the widget.  But, not all columns are filterable at this time.

Tags are a simple markup mechanism that allows users to mark matches.   There are filters for tags as well.

**Comment by rollsch** [comment]
_Using the 'More Filters' button you can tweak more column filters than are on the bottom of the widget. But, not all columns are filterable at this time_

How do I add more items? Everything is selected and all I can see is the following

![image](https://github.com/NationalSecurityAgency/ghidra/assets/1109554/4c8404a8-b7c0-4567-8c68-546602adb52b)

**Comment by dragonmacher** [comment]
> How do I add more items? Everything is selected and all I can see is the following

What you see is the current list of available items for filtering.

**Comment by dragonmacher** [comment]
We have added Column Filters to the Version Tracking matches table.  You can use these column filters to do most of the filtering requested in this ticket.
