### ISSUE TITLE
Debugger gdb info proc mappings for 64-bit Linux

### ISSUE THREAD

**Issue by mfthomps** [NationalSecurityAgency/ghidra#6286]
Related to issue #3071
Based on advice from that issue, I've been using
```
"define info proc mappings",
                    "echo 0x0 0x0 0xbfffffff 0x0 lomem \\n",
                    "echo 0xc0000000 0xfffffff 0x800000 0x0 himem",
                    "end");
```
with success for 32 bit targets, and even 64-bit targets with low load addresses.  However now I have  a target so lib loaded in higher memory, e.g., 0x7f004fd22000, and I can't figure out how to set proc mappings to get that working.  Any ideas?

**Comment by d-millar** [comment]
@mfthomps The same should work with some 0s and fs added, e.g. Ghidra/Debug/Debugger-agent-gdb/data/scripts/fallback_info_proc_mappings.gdb.

**Comment by mfthomps** [comment]
Guess I overthought that one.  
Thanks!

**Comment by d-millar** [comment]
LOL - no problem!
