### ISSUE TITLE
Skip Project Manager

### ISSUE THREAD

**Issue by bartblaze** [NationalSecurityAgency/ghidra#629]
**Is your feature request related to a problem? Please describe.**
Sometimes, I don't want to create a new project/select a project but go straight to the Code Browser for some quick analysis - is there a way to skip the Project Manager?

**Describe the solution you'd like**
Possibility to go straight to the Code Browser, for example via an option in the settings/config, or using a command-line switch.

**Comment by dragonmacher** [comment]
To answer your question, there is not currently any way to avoid opening a project.

That being said, **you do not have to create a project for each binary you wish to open**.  One typical workflow is to have a general project around that you use for importing and exploring binaries.  You can think of such a project as a dumping ground for binaries, which can be added and deleted as you see fit.   

Ghidra will remember your last open project and reopen that the next time you launch Ghidra, as well as any tools that were open when it was closed.   Assuming speed of development/workflow is your desire, then I recommend you just leave your 'playground' project open, along with your Code Browser, and then just drag new binaries right into your Code Browser as you wish to explore them.

Note: to have Ghidra re-open with the previous state (e.g., open Code Browser, open binaries, etc), then when you shutdown, do so by closing the Project Window, **without closing the Code Browser first**.

**Comment by dragonmacher** [comment]
Closing the issue as we are not likely to make this change in the foreseeable future.

**Comment by bartblaze** [comment]
Thank you @dragonmacher, that was indeed what I am currently doing and is a good workaround. Have a great one, and thanks again for releasing Ghidra to the community!
