### ISSUE TITLE
Tricore DEXTR Instructions Incorrectly Calculating in Emulator

### ISSUE THREAD

**Issue by Jayson-Adams** [NationalSecurityAgency/ghidra#6303]
**Describe the bug:**
Tricore DEXTR instructions are incorrectly calculating in the emulator. 

**To Reproduce:**
1. Load up any Tricore V1.3/1.6 binary.
2. Emulate any DEXTR instruction with valid register data.
3. Verify incorrectly calculated data in out register.

**Expected behavior:**

**RRPW** Expected calculation is:
"D[c] = ((D[a], D[b]) << pos)[63:32]"
but current calculation is:
"D[c] = (D[a] << 32) | (D[b] << pos)"

**RRRR** Expected calculation is:
"D[c] = ((D[a], D[b]) << D[d])[63:32]"
but current calculation is:
"D[c] = (D[a] << 32) | (D[b] << D[d])"

**Environment (please complete the following information):**
 - OS: Windows 11 x64
 - Java Version: 21
 - Ghidra Version: 11.0.1
 - Ghidra Origin: Official Github 

**Additional context:**
Modified sinc as below, only tested RRPW but i think my calculations are correct.

```
# DEXTR D[c], D[a], D[b], pos (RRPW)
:dextr Rd2831,Rd0811,Rd1215,const2327Z is PCPMode=0 & Rd0811 & Rd1215 & op0007=0x77 ; Rd2831 & const2327Z & op1622=0x0
{
    local tmp:8 = (zext(Rd0811) << 32) | zext(Rd1215);
    tmp = (tmp << const2327Z) >> 32;
    Rd2831 = tmp[0,32];
}

# DEXTR D[c], D[a], D[b], D[d] (RRRR)
:dextr Rd2831,Rd0811,Rd1215,Rd2427 is PCPMode=0 & Rd0811 & Rd1215 & op0007=0x17 ; Rd2427 & Rd2831 & op1623=0x80
{
    local shiftAmount = Rd2427[0,5];
    local tmp:8 = (zext(Rd0811) << 32) | zext(Rd1215);
    tmp = (tmp << shiftAmount) >> 32;
    Rd2831 = tmp[0,32];
}
```

**Comment by mumbel** [comment]
#5756
