### ISSUE TITLE
[ClassNotFoundException: ghidraRun.bat, launch.bat] Cannot run Ghidra on Windows 11 with JDK 21

### ISSUE THREAD

**Issue by DataGhost4B3** [NationalSecurityAgency/ghidra#6304]
**Describe the bug**
Windows 11 machine with JDK 21.0.2 (LTS). Double clicking or running the `ghidraRun.bat` from cmd/terminal gives the following error when run in `fg` mode _(the default `bg` mode suppresses the error message)_:
```
Error: Could not find or load main class C:\Users\username\Desktop\ghidra
Caused by: java.lang.ClassNotFoundException: C:\Users\username\Desktop\ghidra
Press any key to continue . . .
```

**To Reproduce**
1. Download `ghidra_11.0.1_PUBLIC_20240130.zip` from the GitHub repo.
2. Extract and run the `ghidraRun.bat` script.

**Expected behavior**
Ghidra would run successfully and greet me with the license agreement prompt.

**Screenshots**
\<none that would add any more context to the problem\>

**Attachments**
\<none that would add any more context to the problem\>

**Environment (please complete the following information):**
 - OS: Windows 11 (Windows Version 10.0.22631.3155)
 - Java Version: Oracle JDK 21.0.2
 - Ghidra Version: 11.0.1
 - Ghidra Origin: official GitHub distro

**Additional context**
I added `JAVA_HOME`, `CLASSPATH` to path and added all `/bin` and home directories and the explicit path to the `utility.jar` file to `PATH`. Tried checking into some of the files in `Utility-src.zip` (such as `Ghidra.java`, `GhidraClassLoader.java`, `GhidraLauncher.java`, `GhidraLaunchable.java`, etc.) but could not resolve the issue. **I also tried running directly from the `launch.bat` script but failed with the same error.** Maybe I overlooked something? Incompatibility with Java version?

Any and all help would be appreciated! Thank you in advance.

**Comment by d-millar** [comment]
@DataGhost4B3 Hey and sorry to hear you're having problems!  I haven't been able to reproduce or diagnose your problem, and may have to discuss it with other on the team on Monday.  

Just as a data point, I downloaded the same version of java (21.0.2) and same version of Ghidra (11.0.1 from https://github.com/NationalSecurityAgency/ghidra/releases) on the same version of WIndows, extracted the distro to my Desktop, and successfully launched Ghidra via double-click and the command line, fg and bg.  I know that doesn't help you at all, but it does rule out the jdk as being the problem.

Two things I might suggest if you haven't already done so:
(1) Pull up the application.log in C:\Users\username\.ghidra\.ghidra_10.0.1_PUBLIC and check for any obvious error messages (other than the one you listed).  Also, maybe copy the last dozen or so lines and paste them here.
(2) Try moving your .ghidra to .ghidra.save and start with a completely fresh project.
(3) Try grabbing a new copy from github.  I know that seems a bit stupid, but I'm reaching.

**Comment by d-millar** [comment]
@DataGhost4B3 Apologies GitHub syntax parsing left us hanging there - the “application.log” file should be in the folder named “.ghidra_11.0.1_PUBLIC” in the folder named “.ghidra” in the user’s home directory.  Note the leading periods in the names of both folders (which may make them undiscoverable depending on how you searched).  That said, it’s quite possible Ghidra died before even generating the log file.  Will see if anyone else on the team has better ideas about what’s going on tomorrow!

**Comment by ryanmkurtz** [comment]
Before proceeding with debugging, it is likely going to be necessary to revert every debugging change you made to environment variables, and the Ghidra installation directory itself.  If you have JDK 17 or later on your PATH, you shouldn't need to change anything about your system or Ghidra for it to launch. 

Can you paste in your output of both the `java` and `javac` commands?

**Comment by d-millar** [comment]
OK, something in your environment has to be amiss.  If you open a "cmd" prompt and enter "set", what do you get?

**Comment by ryanmkurtz** [comment]
Also, FYI, in the future you can run `support/ghidraDebug.bat` so it runs in the foreground.

**Comment by ryanmkurtz** [comment]
I'd get rid of that `CLASSPATH` environment variable that you have set up.  You don't want that to interfere with anything.

**Comment by ryanmkurtz** [comment]
> @ryanmkurtz Yes it is just `ghidra/`. Actually the directory is in the Desktop so the full path is `C:\Users\username\Desktop\ghidra`.
> 
> Should I try extracting the zip directly into `C:\` or smth?

Sure, that would be a worthwhile test.

**Comment by d-millar** [comment]
Wow - more guessing....

Line 185 of your launch.bat reads:
set CMD_ARGS=%FORCE_JAVA_VERSION% %JAVA_USER_HOME_DIR_OVERRIDE% %VMARG_LIST% -cp "%CPATH%" ghidra.Ghidra %CLASSNAME% %ARGS%

**Comment by d-millar** [comment]
Sorry, I just wanted to confirm your launch.bat had “ghidra.Ghidra” before %CLASSNAME% as the error message suggests your’s might just have “ghidra”.

**Comment by d-millar** [comment]
Can I assume that’s Ghidra, not Gihdra?  😊

**Comment by ryanmkurtz** [comment]
On line 186 of `launch.bat` (right before `if "%BACKGROUND%"=="y" (`, can you add this line:

```batch
echo "%JAVA_CMD% %CMD_ARGS%
```

and show us your output?

**Comment by ryanmkurtz** [comment]
The problem is this part: `C:\ghidra jn=jupyter notebook  C:\ghidra jl=jupyter lab`.  Those should not be there.  Did you add anything to your `support/launch.properties` file?

**Comment by ryanmkurtz** [comment]
So you had something set in the Windows Registry?

The issue is that they were being passed to java as command line arguments, but because they didn't start with `-D` or `-X`, java assume they weren't properties, but rather the name of the class to try to launch.
