### ISSUE TITLE
NPE DWARF cannot invoke ... because unitHeader is null

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#6312]
**Describe the bug**
Cannot invoke "ghidra.app.util.bin.format.dwarf.DWARFUnitHeader.getStartOffset()" because "unitHeader" is null. DWARFProgram.java:329.

**To Reproduce**
1. Compile simple hello world sample via `clang -target i686-pc-windows-gnu -g3 main.c -o main.exe"
2. Import into ghidra 
3. Run analysis 

**Environment (please complete the following information):**
 - Ghidra Version: 11.1_DEV b82294b537ddfcdb66ac9ed1c84df11dbe772d41

**Comment by dev747368** [comment]
doh.  Causing a NPE when trying to log an error.  Nice.

**Comment by dev747368** [comment]
playing with clang on windows also exposed a typo that mixed up/transposed DW_FORM_implicit_const and DW_FORM_indirect.

**Comment by astrelsky** [comment]
> playing with clang on windows also exposed a typo that mixed up/transposed DW_FORM_implicit_const and DW_FORM_indirect.

Nice. I can't not use clang on windows because visual studio is terrible and I just want to do `clang main.c -o main.exe`. It makes life easier as long as the nightmare that is mingw is not involved.
