### ISSUE TITLE
Commit Functions/Params undoes custom storage

### ISSUE THREAD

**Issue by stgaine** [NationalSecurityAgency/ghidra#6318]
**Describe the bug**
Commit Functions/Params undoes custom storage

**To Reproduce**
1. Import a File - I chose ntoskrnl.exe, but you can use whatever. 
2. Open in Code Viewer and allow auto-analysis to complete. 
3. Choose some function that has a return value - I chose BgkSetCursor at random. 
4. For the sake of example, change the return register from whatever it is (EAX in this example) to something else by following the steps: Right click on function in decompiler -> Edit Function Signature -> Check "Use Custom Storage" -> Double click on the return register to bring up the Storage Address Editor -> Double click the storage register (EAX in this example) -> Change to something else, lets use "EBX" -> Press OK.
5. Verify that it took by re-checking the function signature.

<img width="563" alt="ChangeReturnRegister" src="https://github.com/NationalSecurityAgency/ghidra/assets/162327457/daf5bcda-a49f-4dd0-93f7-02a55455f877">

6. Right click on the function and choose "Commit Params/Return". Then re-open the function signature. It will have reverted to what it was during auto-analysis.
<img width="534" alt="AfterCommitParamsReturn" src="https://github.com/NationalSecurityAgency/ghidra/assets/162327457/f7041bf1-dc73-4b38-a73f-caea46da51af">

**Expected behavior**
The fact that a command that just says "Commmit" actually changes and *then* commits, is quite confusing. It should probably not change things before doing the commit. In the worst case, it should just do nothing in the case that no commit/params return actually needs to happen if the signature was modified.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: Corretto-17.0.10.7.1
 - Ghidra Version: 11.0.1
 - Ghidra Origin: official GitHub distro

**Comment by ghidra1** [comment]
The current results that you describe is the exact purpose of the action.  It is intended to commit what you see in the Decompiler to the Program's database which will in turn be reflected in the Listing.   It's unclear what you thought "commit" meant in the context of the Decompiler.  Did the Decompiler change following the commit action?  If so that would be more of a concern since it trying to lock-in its current state.

**Comment by ghidra1** [comment]
Sorry, I misconstrued your the situation you described.  After trying it I can confirm the behavior is rather unexpected and I will look into it in more detail.

**Comment by ghidra1** [comment]
It would appear that commit may always revert the return to its default state.  I have a fix in the works.  Thanks for reporting it.
