### ISSUE TITLE
Change initial background color of nodes in function graph

### ISSUE THREAD

**Issue by agnosticlines** [NationalSecurityAgency/ghidra#632]
Hi again folks, 

I'm currently building a dark ghidra plugin, it's coming along well, I've moved all the eye sore bits out, hover events correctly colored etc. I've looked all throughought the codebase but I cannot for the life of me figure out how to change the initial background color. Where is this defined?

![2019-05-27-22:30:17](https://user-images.githubusercontent.com/23334509/58439988-1034eb80-80cf-11e9-977f-faff2f1f5532.png)

Appreciate the help, sorry for the very narrow question, it's the last thing I need to submit a PR with the plugin :-)

**Comment by dragonmacher** [comment]
This is currently done at the lowest-level, inside of the `docking.widgets.fieldpanel.FieldPanel` class, which is itself a java `JPanel`.  Specifically, the instance field `backgroundColorModel` is initialized like so:

> 	private BackgroundColorModel backgroundColorModel =
                new DefaultBackgroundColorModel(Color.WHITE);

That class is contained inside of the `ghidra.app.util.viewer.listingpanel.ListingPanel`.   The Listing Panel is used by many views for displaying variable sized layouts, such as the **Byte Viewer** and the **Function Graph**.

The Field Panel has a `setBackgroundColor()` method that allows you to change the background color.    This method is accessible from the Listing Panel's `setTextBackgroundColor()` method.

The highest-level place for you to change this currently will most likely be inside of `ghidra.app.plugin.core.functiongraph.graph.vertex.ListingGraphComponentPanel`, inside of the constructor.   You can see this call in that constructor:

> defaultBackgroundColor = listingPanel.getTextBackgroundColor();

This code is not setting the value, but is instead relying on the default value supplied by the aforementioned `DefaultBackgroundColorModel`.

Ultimately, we wish to change this code to make the value updatable from the UI via the Tool Options.

**Comment by agnosticlines** [comment]
Ah excellent, yeah that's what I'm trying to create atm, is there an interest on your side to include this kind of functionality in core?

**Comment by agnosticlines** [comment]
It sadly does seem like a large refactor of the color model code is required, I guess the code base was never written to have custom themes added?

**Comment by agnosticlines** [comment]
![2019-05-28-18:46:47](https://user-images.githubusercontent.com/23334509/58499922-fd76f100-8178-11e9-8a06-d941560d4f8c.png)

Perfect :-)

**Comment by dragonmacher** [comment]
Yes, theme support was not anticipated as a need originally.   On our long TODO list is to support the idea of a Dark Mode, which we would implement by having all of our UI widgets support theming.  As I'm sure you can imagine, updating all (or most) of our widgets is quite a bit of work to do correctly.

**Comment by agnosticlines** [comment]
I've got most of them working, hovering, pop ups, UI elements. I can send you a patch file if you're interested? It's currently just hardcoded values, I'm working on a plugin to patch it, but it seems I can't override that constructor from inside a plugin :(

**Comment by dragonmacher** [comment]
No need to share the changes for now.  Like I mentioned, we intend to revisit this issue at a global tool scale in the future.
