### ISSUE TITLE
Static URL to download the latest version of Ghidra

### ISSUE THREAD

**Issue by jahatfi** [NationalSecurityAgency/ghidra#6324]
I’m trying to write a script that I can use to regularly download and/or update Ghidra to the latest version.  I’m currently struggling to do this as the download URL here on GitHub changes unpredictably due to the incrementing version number and the unpredictable publication date. Would it be possible to create a static URL that always points to the latest version for download?

This seems relevant: https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

Thanks!

**Comment by mumbel** [comment]
https://github.com/NationalSecurityAgency/ghidra/releases/latest

**Comment by dev747368** [comment]
I think this is the same request: https://github.com/NationalSecurityAgency/ghidra/discussions/2669

There is a link to an example script that someone else came up with using github-foo to get latest.

**Comment by jahatfi** [comment]
Thanks for the quick reply!

My apologies, I searched all the issues for “static download link“ and didn’t find that link.  It’s not quite what I’m looking for is. I’m hoping to do it without an API key, I admittedly I didn’t specify that originally. 

I think for now I can proceed by downloading the latest downloads HTML page and searching that content with a regular expression to find the actual link to the zip archive.
