### ISSUE TITLE
Ghidra fails to launch properly on macOS 14.3

### ISSUE THREAD

**Issue by canassa** [NationalSecurityAgency/ghidra#6327]
# Summary
Ghidra fails to launch properly on macOS 14.3, displaying only a blank, gray screen. The issue persists across multiple installation methods and versions of Ghidra.

<img width="1013" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/288227/d883240d-0fc6-4feb-9c32-d68bcca21d15">

# Steps to Reproduce

1. Attempt to launch Ghidra using the ghidraRun script.
2. Execute Ghidra with the command:

```bash
./launch.sh fg jdk Ghidra 4G "" ghidra.GhidraRun
```
3. Observe the output and the stuck gray launch screen.

# Actual Behavior

Ghidra opens to a blank, gray screen and does not proceed to the main interface. The terminal outputs Java version information and Ghidra initialization logs but then stops responding.

# Expected Behavior

Ghidra should complete its launch process, displaying the main interface and allowing for normal operation.

# Environment

| **Attribute**            | **Details**                                                                                     |
|--------------------------|-------------------------------------------------------------------------------------------------|
| **Operating System**     | macOS 14.3 (MacBook Pro M2)                                                                     |
| **Java Version**         | OpenJDK 17.0.10 (attempts were also made with Java 21)                                          |
| **Ghidra Versions Tested** | 11.0.1 and 10.4                                                                                |
| **Ghidra Origin**        | Attempted installations via Homebrew, official zip download from the NSA GitHub repository, and local build from source. |

# Detailed Description

The issue first appeared when attempting to run Ghidra through the provided ghidraRun script, resulting in a non-responsive gray screen. Further attempts using a more explicit launch command also resulted in the same issue, with the process halting after outputting initialization logs:

```bash
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode)
2024-03-16 14:41:31.889 java[36257:12578325] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
INFO  Using log config file: jar:file:/Users/canassa/code/src/NationalSecurityAgency/ghidra/build/dist/ghidra_11.0.1_DEV/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)
INFO  Using log file: /Users/canassa/.ghidra/.ghidra_11.0.1_DEV/application.log (LoggingInitialization)
INFO  Loading user preferences: /Users/canassa/.ghidra/.ghidra_11.0.1_DEV/preferences (Preferences)
INFO  Loading previous preferences: /Users/canassa/.ghidra/.ghidra_10.4_DEV/preferences (Preferences)
```

No further progress is made from this point, and Ghidra remains stuck on the gray screen.

# Troubleshooting Steps Attempted

- Reinstalling Ghidra from the official zip file
- Building Ghidra from source
- Trying different Java versions (17.0.10 and 21)
- Downgrading Ghidra

**Comment by ryanmkurtz** [comment]
I've been running on that version of macOS without problems. The 4th line of your output looks suspect. I've never seen that before. 

I can look into more on Monday.

**Comment by canassa** [comment]
Hi,

I've just updated to Sonoma 14.4, and now the problem has disappeared. I'm not sure if it was due to the OS version or if my computer simply needed a reboot. The warning "Secure coding is automatically enabled for restorable state!" remains, but the application is now opening.

I will close the issue.

**Comment by Rikitik** [comment]
I have this issue on old Windows 7. Laptop. No errers just an unresponsive command prompt
