### ISSUE TITLE
Ghidra 9.2.2 with ghidra_nodejs 9.2.2 - no format jsc for jsc files

### ISSUE THREAD

**Issue by foxtrotdev** [NationalSecurityAgency/ghidra#6328]
Hello. I managed to build a plugin for analyzing jsc files according to tutorial on https://github.com/PositiveTechnologies/ghidra_nodejs I have successfully added this plugin to ghidra 9.2.2. It seems to work for jsc sample files attached to the nodejs repo project. The decompiler view shows readable content. 

The problem occurs with what I think are newer jsc files. When I try to add this file to parse, I only get raw binary format. There is no suggestion to treat it as jsc.

<img width="612" alt="Screenshot 2024-03-16 at 20 50 22" src="https://github.com/NationalSecurityAgency/ghidra/assets/35732606/81a16c78-d588-41ec-a7b3-b7627ca30ab7">
<img width="612" alt="Screenshot 2024-03-16 at 20 53 19" src="https://github.com/NationalSecurityAgency/ghidra/assets/35732606/1346d3e7-78b3-43b9-b27a-9bb8ab9bcbec">

My question: can I somehow force ghidra to select jsc format? If so, how?

**Comment by ryanmkurtz** [comment]
You cannot force Ghidra to select the jsc format if the `ghidra_nodejs` extension does not support it.  You will need to reach out to that project to ask them to produce an updated version of their extension that supports this newer file format.
