### ISSUE TITLE
About the inconsistency between function definitions and function references in the decompiled code

### ISSUE THREAD

**Issue by 01ChenQing** [NationalSecurityAgency/ghidra#6339]
The function definition shown in the decompiled code is inconsistent with the one shown where this function is referenced.

definition:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/49928773/fbc102ee-0ba2-4e93-82d2-6944e68aa586)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/49928773/73e41792-b081-4291-bfe4-9bb23bf3a39b)

referenced:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/49928773/eeb4253d-227a-44ca-a646-02410764b477)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/49928773/74c85afe-40ae-4df6-87a7-7960b3415d25)

**Comment by ghidracadabra** [comment]
The discussion here is relevant:
https://github.com/NationalSecurityAgency/ghidra/issues/4640#issuecomment-1268758144

**Comment by 01ChenQing** [comment]
> This happens sometimes. AFAIK it is then up to you to decide which is correct and set the function spec accordingly. Ghidra will then use that spec everywhere.

> The discussion here is relevant: [#4640 (comment)](https://github.com/NationalSecurityAgency/ghidra/issues/4640#issuecomment-1268758144)

ok，Thx
