### ISSUE TITLE
Focus on function declaration in Edit Function dialog

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#635]
When using the _"Edit Function"_ action on a function, the focus of the dialog is on the name of the function, not the function declaration. Usually, if I only want to change the name of the function, I use the _"Rename Function"_ action, and I use _"Edit Function"_ mainly to alter the function signature.

Therefore, I would consider it more practical if the keyboard focus was on the function signature edit field by default when opening a new _"Edit Function"_ dialog.

**Comment by dragonmacher** [comment]
Sounds like a good enhancement.  I also noticed that the signature text component does not have undo/redo support.
