### ISSUE TITLE
Adding Graph Overview

### ISSUE THREAD

**Issue by Yao-Wen-Chang** [NationalSecurityAgency/ghidra#6351]
Hi Ghidra Team,

I'm new to Ghidra, having previously used IDA. One feature I particularly love in IDA is its ability to display assembly code with blocks to form graphs. This feature provides a clear visual representation of the flow.

I believe implementing a similar feature like Graph Overview in Ghidra would greatly benefit users. Currently, navigating through the code can be messy and overwhelming. A graph overview would offer a clearer understanding of the information flow within the codebase.

Thanks.

**Comment by ryanmkurtz** [comment]
Have you tried `Window -> Function Graph`?

**Comment by Yao-Wen-Chang** [comment]
I found it. Thanks a lot!
