### ISSUE TITLE
Version tracking: remove correlator from session?

### ISSUE THREAD

**Issue by kitor** [NationalSecurityAgency/ghidra#6352]
**Is your feature request related to a problem? Please describe.**
I created a version tracking session. Added correlation algorithm that turned out to not work well with my project for whatever reason. I don't see any option to remove that correlator from existing session.

In my particular case I added `exact symbol name match` over whole address space which slows the workflow a lot due to a lot of symbols. In hope to fix it I added it again, this time limited to address range which is interesting for me... which made it even worse as now it runs twice.

**Describe the solution you'd like**
Ability to remove correlation algorithm from existing session. 

**Describe alternatives you've considered**

Filtering matches by algorithm doesn't disable it running - in my case symbol match still takes a few seconds on each refresh even though it is not visible.
Starting a new version tracking session will lose all the prior matches.

**Additional context**
Maybe I'm just missing something? But I tried every button in version tracking window.

**Comment by ghidra007** [comment]
@kitor You currently cannot remove the matches from correlators but you can filter them out so you can't see them. There is a filter button on the bottom right of the match table that allows you to do this. You can also start over with a new session and not run the correlators you don't like.

**Comment by kitor** [comment]
Sure, that's what I written in alternatives. Unfortunately filtering doesn't stop processing happen, and with 70k+ matches every reload takes around 8-10 seconds on my 9th gen CPU... I ended up starting over. Yup, that's a firmware where project includes almost entire 32 bit address space...

At least that was pretty quick after some thinking. As I was only interested in already renamed functions it was easy to just accept everything not starting from `FUN_(.*)`

As for this feature, I see a potential to "prime" matching with `exact symbol name match` and then get rid of it. Unless there's another way to set "by hand" that function on X at source is Y at destination :)

**Comment by astrelsky** [comment]
> As for this feature, I see a potential to "prime" matching with `exact symbol name match` and then get rid of it. Unless there's another way to set "by hand" that function on X at source is Y at destination :)

This is what I've always done.

**Comment by ghidra007** [comment]
You can use the Functions window to manually make matches.  It's one match at a time because you have to id source and dest function then make match, and so on. 
You can also limit what VT correlators run against if you make selections in the source and/or destination program before running the correlators. This will speed things up and give you less results to deal with.

**Comment by ryanmkurtz** [comment]
Fixed by 7e9a24c6bc3ea0ac7f18ed9ad196d98f3435f3d5
