### ISSUE TITLE
Sparc:  CALL_RETURN inserted in middle of function

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#6356]
**Describe the bug**
Importing SPARC 32-bit  binary results in functions being cut short due to `call` setting CALL_RETURN flow override.  I've been looking at it while and cannot find any reason this happening.  

PCODE has two RETURN op and the other calls do not, only one, and the size in the extra is 8 seems odd with value 0.

```
o7 = COPY 0xADDR:4
didrestore = COPY 0:1
o0 = COPY X:4
CALL *[ram] 0xTARGET:4
// RETURN 0:8  in the bad case
$U1000:1 = INT_EQUAL didrestore, 0:1
CBRANCH *[ram] 0xADDR+8:4, $U1000:1
RETURN o7
```

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: 17.0.5
 - Ghidra Version: 11.0
 - Ghidra Origin: official GitHub distro

**Additional context**

**Comment by ghidracadabra** [comment]
The `CALL_RETURN` override inserts that extra `RETURN`.   One possibility is that the "Non-Returning Functions - Discovered" analyzer is applying that override (by default that analyzer will put a bookmark on all the functions it marks as non-returning).  If it is that analyzer, and it's really not a non-returning function, you could fix it up manually or analyze the binary again with that analyzer's settings modified.

This might also be related to #5646.  In your case, what is the instruction in the delay slot?  `mov` perhaps?

**Comment by mumbel** [comment]
Ahhh.  I noticed that noreturn got enabled, so that seems like the culprit maybe.

Yeah, the specific function I was looking at yesterday had three calls: good, bad, not disassembled, and they were all mov immediate into first arg in the delay slot.  So nothing removes the CALL_RETURN I guess in the analyzer and might as well start this image over.

(I get bit by this everytime my settings reset it seems, wish you guys would consider turning that off by default with that 2nd noreturn for ELF/PE/loader that has known symbols enabled for those, like memset is almost always marked no return when I start a fresh raw binary </rant>)
