### ISSUE TITLE
Know the users who have checked out file

### ISSUE THREAD

**Issue by tonybounty** [NationalSecurityAgency/ghidra#6359]
In order to change memory map of file in shared project, it is necessary to request "exclusive checkout" on this file. To request exclusive checkout all users must do an "undo checkout" first.

Unfortunately, it is impossible to (features requested) :
* know how many user checked out a file
* know which user have checked out 
* delete user from Project Access List with their "checked out" link to a file

So when there are lot of users who have checked out a file it's very annoying to ask for each user.

![Screenshot from 2024-03-27 11-02-06](https://github.com/NationalSecurityAgency/ghidra/assets/47276302/1adac6db-3443-4acd-97ce-a35bfd959cb3)

**Comment by ghidra1** [comment]
From the project tree right-clicking on a selected file you can view the list of active checkouts:  View Checkouts...

From the resulting dialog a user with ADMIN access to a specific repository, can if neccessary terminate specific checkouts.  Although this could really cause issues for the user who may have changes not yet checked-in it could be useful for cases where people have deleted the associated project from their computer is no longer involved with the poject.

**Comment by ghidra1** [comment]
A user with ADMIN priviledge can modify the project access list while connected to the server.  Action is available from the menu bar:  `Project->Edit Project Access List...`

**Comment by ghidra1** [comment]
Closing ticket since the capabilities you are looking for already exist.  Feel free to re-open with clarrification if this is not the case.
