### ISSUE TITLE
Ghidra.11.0.2 Missing demangler for Mac_x86_64

### ISSUE THREAD

**Issue by Jigyass** [NationalSecurityAgency/ghidra#6361]
The newest version of ghidra is missing demangler for Mac x86_64

**Comment by ryanmkurtz** [comment]
I see it in a fresh download.  Could your macOS Gatekeeper have quarantined it?

**Comment by Jigyass** [comment]
The gatekeeper kept deleting the demangler and the decompiler. The way I fixed it was to disable gatekeeper when downloading in the terminal using the command "sudo spctl --master-disable" and then running the install. It works after that. Thank you
