### ISSUE TITLE
Add support for Xtensa `l32r` instruction.

### ISSUE THREAD

**Issue by Frostie314159** [NationalSecurityAgency/ghidra#6364]
**Is your feature request related to a problem? Please describe.**
When reversing an esp32 binary, every function call ends up looking like this: `(*NULL)(...);`, since the `l32r` instruction isn't implemented yet.

**Describe the solution you'd like**
I'd like an implementation of the `l32r` instruction.

**Describe alternatives you've considered**
An alternative is to always look into the display listing and read the address manually, while this is possible, it's a bit tedious.

**Additional context**
None

**Comment by Frostie314159** [comment]
Here is the description of that instruction: https://0x04.net/~mwk/doc/xtensa.pdf#G11.36704

**Comment by pjsoberoi** [comment]
@Frostie314159 ,

What's the problem with L32R? I see it in xtensaInstructions.sinc: 


    # L32R - Load 32-bit PC-relative, pg. 382.
    :l32r at, srel_8_23_oex_sb2 is srel_8_23_oex_sb2 & at & op0 = 0b0001 {
        at = srel_8_23_oex_sb2;
    }

What am I missing?

**Comment by Frostie314159** [comment]
Ok, it turns out the instruction is implemented and something else was causing the issue. Thanks for the help anyways.
