### ISSUE TITLE
Please create UI in the 2024 style and not 1990

### ISSUE THREAD

**Issue by creotiv** [NationalSecurityAgency/ghidra#6365]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
Just make normal fast, clear and not so heavy UI. 

**Describe alternatives you've considered**

**Additional context**
When i look at it i remember my 10 years and SoftIce debugger

**Comment by ryanmkurtz** [comment]
Have you tried the flat light/dark themes? I find those to look more modern.

**Comment by d-millar** [comment]
Seriously now, Softice was killer!

**Comment by creotiv** [comment]
@d-millar problem that "was"
Also why not to use AI for analyzing?

**Comment by ryanmkurtz** [comment]
Closing this issue because what it is requesting is too vague.
