### ISSUE TITLE
Feature request: About  automatically resolves external symbols used in a program (Linux ELF)

### ISSUE THREAD

**Issue by 01ChenQing** [NationalSecurityAgency/ghidra#6368]
**Is your feature request related to a problem? Please describe.**
ghidra can organize different files as a project. For example, an executable and its dependent libraries are usually placed in the same project, but even if the executable and its dependent libraries are manually associated in the "External Programs" Window, the symbols in the executable still need to be manually associated with the dynamic link library in the "Symbol Tree" window.

**Describe the solution you'd like**
I want ghidra to automatically associate import and export symbols when I import an executable file and its dependent ".so" into the project, and when I click on the external function referenced in the decompcompiled code, I can automatically jump to the corresponding function of the target ".so"

**Describe alternatives you've considered**
When analyzing the structure of the target ELF file, the symbols are parsed by simulating the behavior of linux dynamic linker.
As much as I'd love to help build this feature, I'm not familiar with java

**Additional context**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/49928773/f6114de6-c818-4f37-8327-84dbc9495a6d)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/49928773/241e3c15-be3e-4f51-a428-d9927dc1e74e)

**Comment by dev747368** [comment]
Have you tried the ```External Symbol Resolver``` analyzer?

**Comment by 01ChenQing** [comment]
> Have you tried the `External Symbol Resolver` analyzer?

I tried set External Programs ,re-running the analysis and the External Symbol Resolver did give the correct references, which helped me a lot, but I still want ghidra to automatically associate the exported function to the analyzed executable when I import the .so .

**Comment by ryanmkurtz** [comment]
Ghidra should be doing this during the import if you set the `Load System Libraries From Disk` importer option, assuming it can find the libraries in the locations listed under the `Edit Paths` button.

**Comment by 01ChenQing** [comment]
> Ghidra should be doing this during the import if you set the `Load System Libraries From Disk` importer option, assuming it can find the libraries in the locations listed under the `Edit Paths` button.

Ah, that worked, thanks so much for the help.
