### ISSUE TITLE
Dessasembly open C++ Issue

### ISSUE THREAD

**Issue by maneco2** [NationalSecurityAgency/ghidra#6370]
[Server.exe]: failed to create TerminatedCString at 299daddc: Failed to resolve data length for TerminatedCString
Delay imports detected...

**Comment by ryanmkurtz** [comment]
What is at address `0x299daddc`?  Maybe the string there is very very large?  We'll need more information about the problem to be able to help.

**Comment by maneco2** [comment]
https://gist.github.com/maneco2/5cc16feccb4195d342d1d2947a0a96b4

**Comment by maneco2** [comment]
> What is at address `0x299daddc`? Maybe the string there is very very large? We'll need more information about the problem to be able to help.
The entire file compiled have 27mb, source code is a bit large

**Comment by ryanmkurtz** [comment]
Everything looks normal to me.

**Comment by maneco2** [comment]
possible implement the entire file here for check the problem?

**Comment by maneco2** [comment]
![image](https://github.com/NationalSecurityAgency/ghidra/assets/6583932/eb036534-b491-4c80-8556-207f1ab1b585)

**Comment by ryanmkurtz** [comment]
Apologies, but I don't see any issue with what you are posting.  I will likely need a better verbal description if I am to offer help.

**Comment by maneco2** [comment]
Tryng get features to my open source project from https://depmax64.com/ is a non oficial lineage2 game server emulator made in java. Ghidra look not open these file (depmax64) due any issue?
