### ISSUE TITLE
Arithmetic expressions other than addition in "Go To..." dialog do not work

### ISSUE THREAD

**Issue by treamology** [NationalSecurityAgency/ghidra#6379]
**Describe the bug**
When using the "Go To..." dialog to jump to a program location, the Ghidra manual states you should be able to type an arithmetic expression into the text box to be evaluated. While this works for addition, using any of the other supported operators from the manual cause a "No results for ..." error. 

**To Reproduce**
1. Select "Navigation > Go To..." in any program
2. Type an arithmetic expression using any of the supported operators `+ - * / << >>` or parenthesis
3. See that none of the operators besides `+` function as expected

**Expected behavior**
The expression is evaluated and the resulting location is jumped to.

**Screenshots**
![Screenshot from 2024-04-03 12-30-42](https://github.com/NationalSecurityAgency/ghidra/assets/13398095/f59e7887-2a4b-4459-998c-f133613f5836)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: 19.0.2
 - Ghidra Version: 11.0.1
 - Ghidra Origin: Official distribution

**Comment by ryanmkurtz** [comment]
Do you have something at address 0x20?

**Comment by ryanmkurtz** [comment]
Once i made a memory block that started at 0x0, your example worked for me.  However, something like `1 / 1` is not working for me.

**Comment by treamology** [comment]
Agh, my issue was that I was assuming some memory regions were contiguous when they really weren't, so the expressions were evaluating to an unmapped address. My apologies.

It *does* seems like there is an issue with calculating an absolute address with division or bitshifts (`4*2` works, but `4/2` does not). Perhaps a separate issue should be opened for this, but I'll go ahead and close this one.
