### ISSUE TITLE
Ghidra Keeps Freezing up

### ISSUE THREAD

**Issue by PatchByte** [NationalSecurityAgency/ghidra#6388]
**Describe the bug**
- Ghidra freezes up no matter where you click. (Only when you click of course, scrolling and so on works)

**To Reproduce**
- Do Copy Bytes on an address somewhere -> Ghidra Freezes -> Doesn't respond
- Kill Ghidra
- Start again 
- Ghidra now always freezes when clicking into it or gaining focus

**Expected behavior**
- Don't freeze up

**Screenshots**
- N/A

**Environment (please complete the following information):**
 - OS: Fedora 39 (! Wayland !)
 - Java Version: openjdk 17.0.9 2023-10-17
 - Ghidra Version: 11.0.2
 - Ghidra Origin: Github Distro 
 
**Attachments**
[jstck.txt](https://github.com/NationalSecurityAgency/ghidra/files/14896948/jstck.txt)

**Comment by dragonmacher** [comment]
We have seen in the past that the contents of the copy buffer on Linux can have in impact on the performance of Ghidra.    A simple  thing to try is to copy some simple text from a Linux text editor and then try using Ghidra again.
