### ISSUE TITLE
UnionDB cannot be cast to UnionDataType

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#6393]
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra%2FFramework%2FSoftwareModeling%2Fsrc%2Fmain%2Fjava%2Fghidra%2Fprogram%2Fmodel%2Flang%2Fprotorules%2FPrimitiveExtractor.java#L235

I don't think any more information is needed for this one. I'd put in the fix myself but I'm away from my laptop.

**Comment by find0x90** [comment]
Also seeing this, built on 10f0eb2318a6c1462d31b27d0b5339182d81a9bc from a few days ago.

**Comment by astrelsky** [comment]
> Also seeing this, built on 10f0eb2318a6c1462d31b27d0b5339182d81a9bc from a few days ago.

@find0x90 the fix is trivial. Just change every UnionDataType to Union in that file.
