### ISSUE TITLE
Sleigh: basic context variable usage occur error

### ISSUE THREAD

**Issue by ican-anhui** [NationalSecurityAgency/ghidra#6397]
**Describe the bug**
I am trying to add some unimplemented instruction based on github project(https://github.com/KodaSec/ghidra-microblaze), for xilinx(AMD) Micronblaze soft core processor , 
for adding the support for instruction 'imm imm', and make instruction 'swi rD, rA, imm' to be able to recognize 32bit immediate value, we add context variable usage in me_le.sinc as below:

```
define register offset=0xF0 size=4 contextreg;
define context contextreg
immflag = (0,0) noflow  #add a flag to indicate if one preceding ‘imm iMM’ instruction exist.
;
:imm imm is op2631=0b101100 & cd2125=0b00000 & cd1620=0b00000 & imm [immflag=0x1;globalset(inst_next,immflag);] {
   r18 = imm;  
}
:swi rD, rA, imm is op2631=0b111110 & rD & rA & imm & immflag=0x0 {
   local tmp:4 = rA + imm;
   *[ram]:4 tmp = *[ram]:4 rD;
 }
:swi rD, rA, imm is op2631=0b111110 & rD & rA & imm & immflag=0x1 {
   local tmp:4 = ((r18 << 16) + imm) + rA;
   *[ram]:4 tmp = *[ram]:4 rD;
 }
```
notes for above sleigh specification code: 
> when  'imm imm' matched, we set context variable 'immflag=0x01' to hint it. 
> and at the same time , we use the temp register r18 to hold the high 16bit immediate data for following 'swi' instruction.
> when immflag=0x0, 'swi' instruction is treated as using only 16bit immediate data;
> when immflag=0x1, 'swi' instruction is treated as using 32bit immediate data;

the machine code segment is 
```
        000149cc 01 00 60 30     addik      r3,r0,0x1
        000149d0 40 c2 00 b0     imm        0xc240
        000149d4 38 01 60 f8     swi        r3,r0,0x138
```
expected p-code disassembled result is : 
> (undefined4 *)(in_r0 + 0xc2400138) = *(undefined4 *)(in_r0 + 1);

but the real disassembled result is : 
> (undefined4 *)(in_r0 + 0x138) = *(undefined4 *)(in_r0 + 1);

you can see that :  the 'swi' instruction with 'immflag=0x01' never be matched.
i use the 'DebugSleighInstructionParse.java' script to see what had happened for this machine code segment, we got below:
"
DebugSleighInstructionParse.java> Running...
DebugSleighInstructionParse.java> 
NOTE: bitrange's number leftmost/most-significant bit as 0 (zero).
      This bit numbering agrees with the context field specification
      but differs from token field specification.  The bit correspondence
      for token fields depends upon the specific token size/endianess and
      current byte-offset of pattern matcher.

initial context bits: 00000000.00000000.00000000.00000000
resolving constructor for instruction bytes at: ram:000149cc
decide on instruction bits: byte-offset=0, bitrange=(24,29), value=0xc, bytes=00000001.00000000.01100000.(001100)00
   decendent constructors for decision node (complete tree dump ordered by line number):
   : {line# 139} addik <rD>, <rA>, <imm>
check pattern[1 of 1]: {line# 139} addik <rD>, <rA>, <imm>
   byte pattern: mask=11111100.00000000.00000000.00000000
           bytes[3-6]=00110000.01000000.11000010.00000000
          match-value=00110000.00000000.00000000.00000000 Matched
rD: resolving...
   rD: register r3 (size:4)
rA: resolving...
   rA: register r0 (size:4)
imm: TokenField = 0x1

Prototype parse successful: addik r3,r0,0x1
Instruction length = 4 bytes
Instr Mask:  00000000.00000000.00000000.11111100
Instr Value: 00000000.00000000.00000000.00110000
Op-0 Mask:   00000000.00000000.11100000.00000011
Op-0 Value:  00000000.00000000.01100000.00000000
Op-1 Mask:   00000000.00000000.00011111.00000000
Op-1 Value:  00000000.00000000.00000000.00000000
Op-2 Mask:   11111111.11111111.00000000.00000000
Op-2 Value:  00000001.00000000.00000000.00000000
DebugSleighInstructionParse.java> Finished!
DebugSleighInstructionParse.java> Running...
DebugSleighInstructionParse.java> 
NOTE: bitrange's number leftmost/most-significant bit as 0 (zero).
      This bit numbering agrees with the context field specification
      but differs from token field specification.  The bit correspondence
      for token fields depends upon the specific token size/endianess and
      current byte-offset of pattern matcher.

initial context bits: 00000000.00000000.00000000.00000000
resolving constructor for instruction bytes at: ram:000149d0
decide on instruction bits: byte-offset=0, bitrange=(24,29), value=0x2c, bytes=01000000.11000010.00000000.(101100)00
   decendent constructors for decision node (complete tree dump ordered by line number):
   : {line# 362} imm <imm>
check pattern[1 of 1]: {line# 362} imm <imm>
   byte pattern: mask=11111111.11111111.00000000.00000000
           bytes[2-5]=00000000.10110000.00111000.00000001
          match-value=00000000.10110000.00000000.00000000 Matched

>  Set immflag(0,0) = 0x1
>       Commit future value: immflag(0,0) = 0x1
> imm: TokenField = 0xc240
>       Commit future value at 000149d4: immflag(0,0) = 0x1

Prototype parse successful: imm 0xc240
Instruction length = 4 bytes
Instr Mask:  00000000.00000000.11111111.11111111
Instr Value: 00000000.00000000.00000000.10110000
Op-0 Mask:   11111111.11111111.00000000.00000000
Op-0 Value:  01000000.11000010.00000000.00000000
DebugSleighInstructionParse.java> Finished!
DebugSleighInstructionParse.java> Running...
DebugSleighInstructionParse.java> 
NOTE: bitrange's number leftmost/most-significant bit as 0 (zero).
      This bit numbering agrees with the context field specification
      but differs from token field specification.  The bit correspondence
      for token fields depends upon the specific token size/endianess and
      current byte-offset of pattern matcher.

initial context bits: 00000000.00000000.00000000.00000000
resolving constructor for instruction bytes at: ram:000149d4
decide on instruction bits: byte-offset=0, bitrange=(24,29), value=0x3e, bytes=00111000.00000001.01100000.(111110)00
   decendent constructors for decision node (complete tree dump ordered by line number):
   : {line# 434} swi <rD>, <rA>, <imm>
   : {line# 439} swi <rD>, <rA>, <imm>
decide on context bits: bitrange=(0,0), value=0x0, context=(0)0000000.00000000.00000000.00000000
   decendent constructors for decision node (complete tree dump ordered by line number):
   : {line# 434} swi <rD>, <rA>, <imm>

> check pattern[1 of 1]: {line# 434} swi <rD>, <rA>, <imm>
>    (  byte pattern: mask=11111100.00000000.00000000.00000000
>               bytes[3-6]=11111000.00001000.11000000.00000000
>              match-value=11111000.00000000.00000000.00000000 Matched
>    ) -and- (
>       context pattern: mask=10000000.00000000.00000000.00000000
>              context(0..31)=00000000.00000000.00000000.00000000
>                 match-value=00000000.00000000.00000000.00000000 Matched
>                   immflag(0,0) == 0x0 Match
>    ) Matched

rD: resolving...
   rD: register r3 (size:4)
rA: resolving...
   rA: register r0 (size:4)
imm: TokenField = 0x138

Prototype parse successful: swi r3,r0,0x138
Instruction length = 4 bytes
Instr Mask:  00000000.00000000.00000000.11111100
Instr Value: 00000000.00000000.00000000.11111000
Op-0 Mask:   00000000.00000000.11100000.00000011
Op-0 Value:  00000000.00000000.01100000.00000000
Op-1 Mask:   00000000.00000000.00011111.00000000
Op-1 Value:  00000000.00000000.00000000.00000000
Op-2 Mask:   11111111.11111111.00000000.00000000
Op-2 Value:  00111000.00000001.00000000.00000000
DebugSleighInstructionParse.java> Finished!
"
it seem that my context varialbe 'immflag' set as 0x01 by instruction 'imm', but during 'swi' matching, the context variable 'immflag'  is still 0x00.

**To Reproduce**
1. use the attached file 'Microblaze.zip'(my modification included) as sleigh specification for microblaze
[Microblaze.zip](https://github.com/NationalSecurityAgency/ghidra/files/14912606/Microblaze.zip)
2. use the attached file 'target_elf.zip' as target machine code file.
[target_elf.zip](https://github.com/NationalSecurityAgency/ghidra/files/14912631/target_elf.zip)
3. run ghidra to see the result as below picture from my run
![error_result001](https://github.com/NationalSecurityAgency/ghidra/assets/105571602/6c498415-f50e-49aa-8fa6-6078f980b485)

**Expected behavior**
expected p-code disassembled result is : 
> (undefined4 *)(in_r0 + 0xc2400138) = *(undefined4 *)(in_r0 + 1);

**Screenshots**
see picture 'error_result001' in 'To Reproduce' step 3

**Attachments**
see attached file [Microblaze.zip] and [target_elf.zip]

**Environment (please complete the following information):**
 - OS: [windows 11]
 - Java Version: [[21.0.2](https://github.com/NationalSecurityAgency/ghidra/issues/java_version)]
 - Ghidra Version: [11.0.1]
 - Ghidra Origin: [https://github.com/NationalSecurityAgency/ghidra/releases] 

**Additional context**
None

**Comment by GhidorahRex** [comment]
This looks correct. Did you make changes to the language and recompile, then attempt to reanalyze? You may need to clear the code bytes (make sure you clear the register values as well) then rerun. Or since you're just testing your language module, I would try reimporting the binary fresh.

I modified your `:swi` to add a 0 or 1 depending on the context so I could see it better, but as you can tell from the pcode it's using the r18 version.

![Screenshot at 2024-04-09 08-43-49](https://github.com/NationalSecurityAgency/ghidra/assets/49028988/c9b0a6aa-5696-4695-b172-a832d0afc630)

**Comment by ican-anhui** [comment]
> This looks correct. Did you make changes to the language and recompile, then attempt to reanalyze? You may need to clear the code bytes (make sure you clear the register values as well) then rerun. Or since you're just testing your language module, I would try reimporting the binary fresh.
> 
> I modified your `:swi` to add a 0 or 1 depending on the context so I could see it better, but as you can tell from the pcode it's using the r18 version.
> 
> ![Screenshot at 2024-04-09 08-43-49](https://private-user-images.githubusercontent.com/49028988/320850523-c9b0a6aa-5696-4695-b172-a832d0afc630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzU4NjksIm5iZiI6MTcxMjczNTU2OSwicGF0aCI6Ii80OTAyODk4OC8zMjA4NTA1MjMtYzliMGE2YWEtNTY5Ni00Njk1LWIxNzItYTgzMmQwYWZjNjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3NTI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTRkMzc2MjA5OGQ2ZTlhZWMyYWIwMTM5MjcxNDRlYWJhMTc1YWNiNzQ2MmFiMjcwMThlYTEwZGFkMzVjNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zXAcx7e5hg90L_j9sru_Puj1nHZPn8zaF7GiMFqDSrQ)

hi , GhidorahRex
 thanks for your responese to my issue.
 what i had done is adding my increasment stataments(mentioned by my issue 'Describe the bug' part) into 'mb_le.sinc' file to test if it works as expected. but no recompilation action executed.  coz this is my first try to use ghidra, maybe i missed some basic process for enabling changes of the language. if yes , please tell me how to do or where to study from.
could you please help to try reimporting my whole binary file , and see the result.
thanks.

**Comment by GhidorahRex** [comment]
If you close and re-open Ghidra, it should grab any updates. It may help to delete the mb_le.sla file. In addition, there is a ReloadSleighLanguage script that can be found in the script manager.

**Comment by ican-anhui** [comment]
> If you close and re-open Ghidra, it should grab any updates. It may help to delete the mb_le.sla file. In addition, there is a ReloadSleighLanguage script that can be found in the script manager.

hi, GhidorahRex
it can't reslove my issue by to close and reopen Ghidra . but by running ReloadSleighLanguage script , my issue get fixed.
below is my expection result:
![issue fixed](https://github.com/NationalSecurityAgency/ghidra/assets/105571602/4065a43e-a547-4a6e-b0d1-16e6170ef32a)
thanks!

**Comment by ican-anhui** [comment]
thanks!
