### ISSUE TITLE
Condence assignments using the += operator in decompiled code

### ISSUE THREAD

**Issue by henke37** [NationalSecurityAgency/ghidra#641]
**Describe the solution you'd like**
When the decompiler detects that a variable is read from, has a basic operation done on its value and then assigned back to the same variable, use the shorthand operators to avoid being needlessly verbose.

**Comment by ubitux** [comment]
In the decompiler, right click → Properties, then Options → Decompiler → Analysis, there is the option "Use inplace assignment operators".

**Comment by henke37** [comment]
Huh. That worked. I wonder if that should be enabled by default.
