### ISSUE TITLE
SLEIGH:  Subtable production not being selected as I expected...

### ISSUE THREAD

**Issue by marcushall42** [NationalSecurityAgency/ghidra#6411]
I'm working on a nanoMIPS processor sleigh code, and there's an odd ROTX instruction that I'm trying to get working, but I am being baffled by this behavior.

The ROTX is a "Rotate and Exchange" instruction that performs a somewhat complicated barrel shifter operation.  It has a source register, destination register, and three constants, "shift", "shiftx", and "stripe".  The instruction manual has a rather complicated python code snippet to describe the behavior, but rather than implement that directly (which involves 5 loops), I thought I could implement 5 stages of bit shifting instead.  The first stage involves the highest bit of "shift" and "shiftx" (and is complicated with the "stripe" bit as well), then the next stage involves bit3 of "shift" and "shiftx", etc.  I have different sleigh definitions for each stage for all 4 or 8 bit combinations from "shift" and "shiftx" (and "stripe").

The problem is that the proper subtable rule doesn't seem to be being selected.  I don't understand why that might be.

Here's the sleigh code:
```
rotx_5: is rt & rs & i4=0 & i10=0 & i6=0 { rt = rs; }
rotx_5: is rt & rs & i4=1 & i10=0 & i6=0
{ t:4 = rs&0xff00ff00; rt = (rs&0x00ff00ff)|(t>>16)|(t<<16); }
rotx_5: is rt & rs & i4=0 & i10=1 & i6=0
{ t:4 = rs&0x00ff00ff; rt = (rs&0xff00ff00)|(t>>16)|(t<<16); }
rotx_5: is rt & rs & i4=1 & i10=1 & i6=0 { rt = (rs>>16)|(rs<<16); }
rotx_5: is rt & rs & i4=0 & i10=0 & i6=1
{ t:4 = rs&0x0f0f0f0f; rt = (rs&0xf0f0f0f0)|(t>>16)|(t<<16); }
rotx_5: is rt & rs & i4=1 & i10=0 & i6=1
{ t:4 = rs&0xf00ff00f; rt = (rs&0x0ff00ff0)|(t>>16)|(t<<16); }
rotx_5: is rt & rs & i4=0 & i10=1 & i6=1
{ t:4 = rs&0x0ff00ff0; rt = (rs&0xf00f0f00f)|(t>>16)|(t<<16); }
rotx_5: is rt & rs & i4=1 & i10=1 & i6=1
{ t:4 = rs&0xf0f0f0f0; rt = (rs&0x0f0f0f0f)|(t>>16)|(t<<16); }

rotx_4: is      i3=0 & i9=0 { }
rotx_4: is rt & i3=1 & i9=0
{ t:4 = rt&0xf0f0f0f0; rt = (rt&0x0f0f0f0f)|(t>>8)|(t<<24); }
rotx_4: is rt & i3=0 & i9=1
{ t:4 = rt&0x0f0f0f0f; rt = (rt&0xf0f0f0f0)|(t>>8)|(t<<24); }
rotx_4: is rt & i3=1 & i9=1 { rt = (rt>>8)|(rt<<24); }

rotx_3: is      i2=0 & i8=0 { }
rotx_3: is rt & i2=1 & i8=0
{ t:4 = rt&0xcccccccc; rt = (rt&0x33333333)|(t>>4)|(t<<28); }
rotx_3: is rt & i2=0 & i8=1
{ t:4 = rt&0x33333333; rt = (rt&0xcccccccc)|(t>>4)|(t<<28); }
rotx_3: is rt & i2=1 & i8=1 { rt = (rt>>4)|(rt<<28); }

rotx_2: is      i1=0 & i7=0 { }
rotx_2: is rt & i1=1 & i7=0
{ t:4 = rt&0xaaaaaaaa; rt = (rt&0x55555555)|(t>>2)|(t<<30); }
rotx_2: is rt & i1=0 & i7=1
{ t:4 = rt&0x55555555; rt = (rt&0xaaaaaaaa)|(t>>2)|(t<<30); }
rotx_2: is rt & i1=1 & i7=1 { rt = (rt>>2)|(rt<<30); }

rotx_1: is      i0=0 { }
rotx_1: is rt & i0=1 { rt = (rt>>1)|(rt<<31); }

# ROTX - Rotate and eXchange  pg. 160.
:rotx rt, rs, shift, shiftx, stripe
    is i_op=0b100000 & rt & rs
    & i11_15=0b11010 & i7_10 & i6 & i5=0 & i0_4
    & rotx_5 & rotx_4 & rotx_3 & rotx_2 & rotx_1
    [ shift = i0_4+0; shiftx = i7_10<<1; stripe=i6+0; ] {
    build rotx_5;
    build rotx_4;
    build rotx_3;
    build rotx_2;
    build rotx_1;
}
```
And here's an example instruction:
```
        900f93d8 03 81 18 d2     rotx       a4,t5,0x18,0x8,0x0
                                                      $Uda00:4 = INT_AND t5, 0xff00ff00:4
                                                      $Uda80:4 = INT_AND t5, 0xff00ff:4
                                                      $Udb00:4 = INT_RIGHT $Uda00:4, 16:4
                                                      $Udb80:4 = INT_OR $Uda80:4, $Udb00:4
                                                      $Udc00:4 = INT_LEFT $Uda00:4, 16:4
                                                      a4 = INT_OR $Udb80:4, $Udc00:4
                                                      $Uf080:4 = INT_AND a4, 0xf0f0f0f0:4
                                                      $Uf100:4 = INT_AND a4, 0xf0f0f0f:4
                                                      $Uf180:4 = INT_RIGHT $Uf080:4, 8:4
                                                      $Uf200:4 = INT_OR $Uf100:4, $Uf180:4
                                                      $Uf280:4 = INT_LEFT $Uf080:4, 24:4
                                                      a4 = INT_OR $Uf200:4, $Uf280:4
                                                      $Uf900:4 = INT_AND a4, 0xcccccccc:4
                                                      $Uf980:4 = INT_AND a4, 0x33333333:4
                                                      $Ufa00:4 = INT_RIGHT $Uf900:4, 4:4
                                                      $Ufa80:4 = INT_OR $Uf980:4, $Ufa00:4
                                                      $Ufb00:4 = INT_LEFT $Uf900:4, 28:4
                                                      a4 = INT_OR $Ufa80:4, $Ufb00:4
                                                      $U10180:4 = INT_AND a4, 0xaaaaaaaa:4
                                                      $U10200:4 = INT_AND a4, 0x55555555:4
                                                      $U10280:4 = INT_RIGHT $U10180:4, 2:4
                                                      $U10300:4 = INT_OR $U10200:4, $U10280:4
                                                      $U10380:4 = INT_LEFT $U10180:4, 30:4
                                                      a4 = INT_OR $U10300:4, $U10380:4
                                                      $U10980:4 = INT_RIGHT a4, 1:4
                                                      $U10a00:4 = INT_LEFT a4, 31:4
                                                      a4 = INT_OR $U10980:4, $U10a00:4
```
Here, "shift" is 0x18, "shiftx" is "0x08" and "stripe" is 0.  It is selecting the rotx_5 subtable with i4=1, i10=0, i6=0, which is correct, then the rotx_4 subtable with i3=1,i9=0, which is wrong, it should be i3=1,i9=1.  Then it selects rotx_3 with i2=1,i8=0, but i3=0,i8=0.  It selects rotx_2 with i1=1,i7=0 instead of i1=0,i7=0.  And finally, rotx_1 with i0=1 instead of i0=0.

So, it seems to always be selecting the 2nd definition regardless of the qualifiers in the constraints.  As a debugging test, I added actions to assign temporaries (a:1 = i1; b:1 = i7;) into the actions for rotx_2's 2nd case and they were both copied from constant 0.

I'm clearly just missing something, but the longer I stare at this, the farther I am from seeing what I'm doing wrong..

Thanks for any insight!

**Comment by marcushall42** [comment]
Sure..

First off, I have a set of @defines to deal with big-endian vs little-endian:

```
@if ENDIAN == "big"
@define I0  0
@define I1  1
@define I2  2
@define I3  3
@define I4  4
...
@else
@define I0  16
@define I1  17
@define I2  18
@define I3  19
@define I4  20
```

Then, the ins32 token fields:

```
# Regular 32-bit instruction (use $I defines from above)
define token ins32(32)
..
    rt      = ($(I21),$(I25))
    rs      = ($(I16),$(I20))
    i7_10   = ($(I7),$(I10))
    i0_4    = ($(I0),$(I4))
    i10     = ($(I10),$(I10))
    i9      = ($(I9),$(I9))
    i8      = ($(I8),$(I8))
    i7      = ($(I7),$(I7))
    i6      = ($(I6),$(I6))
    i5      = ($(I5),$(I5))
    i4      = ($(I4),$(I4))
    i3      = ($(I3),$(I3))
    i2      = ($(I2),$(I2))
    i1      = ($(I1),$(I1))
    i0      = ($(I0),$(I0))
```
These were snipped from the definitions, but the pattern is pretty straightforward.

**Comment by GhidorahRex** [comment]
For something like this I usually find it helpful to add debug information to the constructor itself so I can see immediately from the disassembly which subconstructors are being selected:
```
rotx_4: 0 is      i3=0 & i9=0 { }
rotx_4: 1 is rt & i3=1 & i9=0
{ t:4 = rt&0xf0f0f0f0; rt = (rt&0x0f0f0f0f)|(t>>8)|(t<<24); }
rotx_4: 2 is rt & i3=0 & i9=1
{ t:4 = rt&0x0f0f0f0f; rt = (rt&0xf0f0f0f0)|(t>>8)|(t<<24); }
rotx_4: 3 is rt & i3=1 & i9=1 { rt = (rt>>8)|(rt<<24); }

:rotx rt, rs, shift, shiftx, stripe (rotx_5, rotx_4, rotx_3, rotx_2, rotx_1)
```

I played around with it real quick, and was able to see it using `rotx_4: 3 is rt & i3=1 & i9=1 { rt = (rt>>8)|(rt<<24); }
`  (the full debug output was `(1,3,0,0,0)` for the bytes `03 81 18 d2`, so I'm not sure what the difference is with your code. I didn't use your `#define` definitions for endianness but I was using BE.

**Comment by marcushall42** [comment]
Hmm...  What you show is certainly what I expected to happen..   But, I keep getting (1,1,1,1,1).  it isn't the declaration order, if I move things around, it doesn't change.  I even made this change:
     rotx_2:` 1:i1:i7 is rt & ii1=1 & ii7=0 & i1 & i7
and I get:
        900f93d8 03 81 18 d2     rotx       a4,t5,0x18,0x8,0x0 (1,1,1,1:0x0:0x0,1)
(I defined ii1 as (17,17) and ii7 as (23,23) directly, not using the @defined symbols.)
(Oh, there is an additional complication since the little endian seems to be stored the way that the PDP-11 stored longs, high half word, low byte first, then low half word, low byte first, so i0=16, i1=17, i2=18 .. i15=31, i16=0, i17=1, ... i31=15)

I was surprised that I can't do this:
     rotx_2:` 1:i1:i7 is rt & i1=1 & i7=0
which says "Constraining currently undefined operand: i1", but I expected the 'i1=1' to define i1..  Even:
    rotx_2:` 1:i1:i7 is rt & i1=1 & i7=0 & i1 & i7
gives the same error.  I don't know if that may be related to my problems, or if it's something else.

**Comment by GhidorahRex** [comment]
If you want to try to be extra debuggy, you can change the calculation like so:
```
rotx_4: 0(val) is      i3=0 & i9=0 [val=i3<<1|i9;] { }
rotx_4: 1(val)  is rt & i3=1 & i9=0 [val=i3<<1|i9;] 
{ t:4 = rt&0xf0f0f0f0; rt = (rt&0x0f0f0f0f)|(t>>8)|(t<<24); }
rotx_4: 2(val) is rt & i3=0 & i9=1 [val=i3<<1|i9;] 
{ t:4 = rt&0x0f0f0f0f; rt = (rt&0xf0f0f0f0)|(t>>8)|(t<<24); }
rotx_4: 3(val) is rt & i3=1 & i9=1 [val=i3<<1|i9;] { rt = (rt>>8)|(rt<<24); }
```
That should tell you exactly which pattern is being matched. Beyond that, all I can say is that it's possible your `#define` definitions are wrong. I would write out the tokens without any macros, and if you need to swap tokens between little and big endian, use a `#ifdef` around the entire token definition.

You can then try editing individual bits to figure out exactly what bit is being incorrectly flipped here.

**Comment by marcushall42** [comment]
Simplified my "rotx_2" subtable down to this:
'''
rotx_2: "2_0" is ii1=0 & ii7=0 { }
rotx_2: "2_1" is ii1=1 & ii7=0 { }
rotx_2: "2_2" is ii1=0 & ii7=1 { }
rotx_2: "2_3" is ii1=1 & ii7=1 { }
```
I still get case "2_1" output when I should be getting "2_0".  The nanoMipsLE.sla seems to look right:
```
<subtable_sym name="rotx_2" id="0x446" scope="0x0" numct="4">
 <constructor parent="0x446" first="1" length="4" line="0:1101">
 <print piece="2_0"/>
  <construct_tpl>
  <null/></construct_tpl>
 </constructor>
 <constructor parent="0x446" first="1" length="4" line="0:1102">
  <print piece="2_1"/>
  <construct_tpl>
   <null/></construct_tpl>
  </constructor>
 <constructor parent="0x446" first="1" length="4" line="0:1104">
  <print piece="2_2"/>
  <construct_tpl>
   <null/></construct_tpl>
  </constructor>
 <constructor parent="0x446" first="1" length="4" line="0:1106">
  <print piece="2_3"/>
  <construct_tpl>
   <null/></construct_tpl>
  </constructor>
 <decision number="4" context="false" start="16" size="1">
  <decision number="2" context="false" start="22" size="1">
   <decision number="1" context="false" start="0" size="0">
    <pair id="0">
     <instruct_pat>
      <pat_block offset="2" nonzero="1">
       <mask_word mask="0x82000000" val="0x0"/>
      </pat_block>
     </instruct_pat>
    </pair>
   </decision>
   <decision number="1" context="false" start="0" size="0">
    <pair id="1">
     <instruct_pat>
      <pat_block offset="2" nonzero="1">
       <mask_word mask="0x82000000" val="0x2000000"/>
      </pat_block>
     </instruct_pat>
    </pair>
   </decision>
  </decision>
  <decision number="2" context="false" start="22" size="1">
   <decision number="1" context="false" start="0" size="0">
    <pair id="2">
     <instruct_pat>
      <pat_block offset="2" nonzero="1">
       <mask_word mask="0x82000000" val="0x80000000"/>
      </pat_block>
     </instruct_pat>
    </pair>
   </decision>
   <decision number="1" context="false" start="0" size="0">
    <pair id="3">
     <instruct_pat>
      <pat_block offset="2" nonzero="1">
       <mask_word mask="0x82000000" val="0x82000000"/>
      </pat_block>
     </instruct_pat>
    </pair>
   </decision>
  </decision>
 </decision>
</subtable_sym>
```
I think this might be right...  Maybe..  Depends on what some fields here mean..  In the <pat_block> element, does the offset mean how many bytes into the instruction to start matching?  In my "03 81 18 d2" instruction bytes, if the 0x82 part of the mask aligns with the 0x18 byte, then it is looking at the bits that I think it should.  I'm not sure why it thinks there are three layers of decision, but the outermost seems to have 0 bits, so I'm not too bothered about it..

So, the 0x82 mask applied to the 0x18 instruction byte should yeild a value 0x0, which should match in the <pair id=0> section, which should presumably run the 0th constructor that prints "2_0".  And that seems to be what you get, but I seem to always be getting "2_1".

But, I *think* that this means that the sleigh is compiling properly (if my interpretation of the fields is correct).  I'm running ghidra 10.4, but I can't believe that there is a fundamental problem that could be causing this to be mis-interpreted..

**Comment by marcushall42** [comment]
Just saw your comment that I missed while I was messing around with the output..

I have defined symbols ii1 and ii7 as absolutes now ( ii1 = (17,17) and ii7 = (23,23))  Using this, I modified my subtable rules to look like:

```
rotx_2: 0(val) is      ii1=0 & ii7=0 [val=ii1<<1|ii7;]{ }
```
and I get the error:
```
Global symbol 'ii1' is not allowed in action expression (SleighCompile)
```
This seems like it should be telling me something, but I don't know what...

(BTW, thanks for all of your time helping to educate me along the way...)

**Comment by GhidorahRex** [comment]
Are you sure you're handling the LE correctly? Can you try big endian and see if you get the right values? Because the only thing I can figure out is that your LE case is wrong.

**Comment by marcushall42** [comment]
Well, okay.  After moving the bytes around to put them into big-endian order, it works!  I get:

```
        900f93d8 81 03 d2 18     rotx       a4,t5,0x18,0x8,0x0 (1,3,0,0,0)
```

But, for little endian, I get:

```
        900f93d8 03 81 18 d2     rotx       a4,t5,0x18,0x8,0x0 (1,1,1,1,1)
```

So, perhaps I am selecting the wrong bits.  For the rot2_x subtable, I want to be using what the instruction manual refers to as bit 1 and bit 7 (it shows things in big-endian mode).  Bit 1 is the 0x02 bit in the 0x18 byte and bit 7 is the 0x80 bit in the 0x18 byte.  In the little endian ordering, the bytes are arranged as "03 81 18 d2", so I want to be taking bits from the third byte.  With ghidra in little-endian mode, I think that the 0x02 bit of the 3rd byte is bit 17 and the 0x80 bit is bit 23.  Is this what you think it should be?  My bitfields for the main table seem to all line up properly, and other subtables seem to be working properly, it's just this one instruction that is giving me fits!

**Comment by marcushall42** [comment]
Looking at the .sla files, the only differences that I see pertaining to the rotx_2 subtable are:
```
#ifndef LE
<decision number="4" context="false" start="24" size="1">
<decision number="2" context="false" start="30" size="1">
#else /* LE */
<decision number="4" context="false" start="16" size="1">
<decision number="2" context="false" start="22" size="1">
#endif /* LE */
```
and
```
#ifndef LE
<pat_block offset="3" nonzero="1">
#else /* LE */
<pat_block offset="2" nonzero="1">
#endif /* LE */
```

I presume that the <decision> start value is a bit offset, and they differ by 8, which would be correct, and the <pat_block> offset value is a byte offset and they differ by 1, which is also right.  So, that leads me to believe that my bit numbering is working correctly.  Yet, the subtable selection just isn't working for the little-endian case.  Which, unfortunately, is what the target I'm working with is compiled as.
Maybe I'll just leave this as a user-defined pcodeop (what I have been doing until now) until I get the inspiration to look further into how ghidra digests the information and actually parses the instructions.

**Comment by GhidorahRex** [comment]
the rest of the MIPS files don't have tokens needing to be swapped for LE. Have you tried just leaving it alone and not using any redefinition for LE?

**Comment by marcushall42** [comment]
I expect that the normal MIPS is "proper little-endian", though.  The nanoMIPS seems to be weird because of the variable instruction length.  The opcode is normally in the highest 6 bits (bits 26-31 for 32-bit instructions, bits 10-15 for 16-bit instructions).   For big-endian, this is always the high 6 bits of the half-word at the PC address.  But, for little-endian, the first 2 bytes are the high half of a 32-bit instruction and the next 2 bytes are the low half (like the PDP-11 used to store 32-bit longs).  That way, looking at the first 16-bit value allows the processor to decode the opcode and therefore the instruction length.

I've discovered the SleighDebugLogger class and it's making me even more confused on how bit numbering is "supposed" to be.  My 4-byte opcode is:
 ```
   03  81  18  d2   == 00000011.10000001.00011000.11010010
```
In SleighDebugLogger's output it shows one line:
```
decide on instruction bits: byte-offset=0, bitrange=(24,27), value=0xd, bytes=00000011.10000001.00011000.(1101)0010
```
The bytes that it shows match up with what I think that they should be, and the field being tested makes sense with the constraint i11_15=0b11010 (only comparing the highest 4 bits), but the bit numbering gets a little funny here.  My BE/LE macros define i11_15 to be (27,31), which seems like that should be bits 3-7 of the 3rd byte.  SleighDebugLogger's output shows bits 4-7 of the 3rd byte in parenthesis, but calls it bitrange=(24,27).  Everything here seems to be doing the right thing, but I don't understand why it calls it bits 24-27.

Anyhow, following through the subtables, it looks like it builds the proper masks for the BE and LE cases, and in fact, the output from SleighDebugLogger produces the correct parse for my test BE file AND for the real LE target system.
```
Prototype parse successful: rotx a4,t5,0x18,0x8,0x0,1,3,0,0,0
Instruction length = 4 bytes
```
So, this is extremely puzzling.  This output seems to confirm that the SLEIGH is correct.  Indeed, now if I clear and re-disassemble the instruction IT COMES OUT CORRECT.  I'm not sure what I did that changed things...

**Comment by marcushall42** [comment]
Okay, new hypothesis.
There is some info about subtable selection that persists in the database that is not set when ghidra re-creates an instruction on startup, but is generated when the disassembler creates the instruction from undefined bytes.  Even if I revert my SLEIGH so that the pcode is just a call to a user defined pcodeop, then go back to actually generating real pcodeops, the pcode changes, but what drives the subtable selection is not set.  So, I have to select all of the "rotx" instructions, clear and re-disassemble them to get things right (or properly roll the version number and have ghidra re-disassemble the whole thing.)
I was certainly being sloppy and just exiting ghidra and re-running it, since that has always seemed to re-generate the right pcode even though I didn't roll the version number.  So, I was lulled into a false sense of what works "well enough" and committed pilot error.
Sorry to have taken so much attention, but I definitely learned a thing or ten on this!
