### ISSUE TITLE
In RegEx mode, the "Make selection" action in "Search Memory" results window only selects first address of matched region.

### ISSUE THREAD

**Issue by Varriount** [NationalSecurityAgency/ghidra#6415]
**Describe the bug**
The "Make selection" action in the "Search Memory" utility's "Search All" window only selects the first address of a matched region when memory was searched using a regular expression.

**To Reproduce**
1. Open the "Search Memory" utility.
2. In "Regular Expression" mode, construct a query that matches a region covering multiple addresses. Note that the query should be constructed in a way that prevents matches from overlapping each other.
3. Click the "Search All" button.
4. In the results window that appears, right-click an entry and click "Make selection".

**Expected behavior**
Like the other modes, select all addresses in a matched region, rather than the first address.

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/524596/a4293917-66bd-434a-af46-14fa2d3e78c4)

![image](https://github.com/NationalSecurityAgency/ghidra/assets/524596/a37515f2-63db-4464-9cc8-88e3f87435c0)

![image](https://github.com/NationalSecurityAgency/ghidra/assets/524596/c503c763-6f54-4807-8476-2dee02f4aad6)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: OpenJDK 17.0.2
 - Ghidra Version: 11.0.3
 - Ghidra Origin: Official build

**Additional context**
This behavior isn't consistent with the selection behavior exhibited by the other matching modes.

If someone can give me some general instructions on where to look/how to fix this bug, I'd be happy to devote some time to fixing it, as it's quite an impediment to my work at the moment (I'm looking for patterns of repetitive data in a GBA ROM). Unfortunately the Memory Searcher plugin seems (to me at least) a tad over-engineered and complicated for what it's doing - there's a lot of cross-interest logic spread out amongst the GUI and search components.

**Comment by ryanmkurtz** [comment]
I am not reproducing this.  Note that the program selection is made based on the rows in the table you also have selected.  In your screen shot, you only have the first row selected.

**Comment by Varriount** [comment]
> I am not reproducing this. Note that the program selection is made based on the rows in the table you also have selected. In your screen shot, you only have the first row selected.

Yes, however note that none of the rows in the table correspond to the (unselected) addresses highlighted as part of the match. I would expect that clicking "Make selection" on the first row in the table would select addresses `800fcc9`-`800fcce`.

For example, if I use "Hex" mode to search the same sequence:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/524596/9914b968-8a59-4a69-87c1-ec6ca77f4b48)

And select the same address:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/524596/499ce7a3-89a5-481c-bd99-09e92cedc990)

All addresses that were part of the match starting at that address were selected:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/524596/be47fbf5-17a9-47d3-94aa-8ece1be98f43)

**Comment by Varriount** [comment]
I'm not sure I understand - if this is so, why do the selection behaviors for the Hex and Regex modes differ?

**Comment by dragonmacher** [comment]
I see your point here.   It is not a bug, but was intentionally coded that way for reasons I don't know.    I'll poke around to see what I can figure out.
