### ISSUE TITLE
Class merging

### ISSUE THREAD

**Issue by henke37** [NationalSecurityAgency/ghidra#642]
**Is your feature request related to a problem? Please describe.**
As I work on a file, I tend to create a lot of automatic structs before I realize that several variables are all of the same type.

**Describe the solution you'd like**
When two or more structs are selected in the data type manager, the context menu (opened by right clicking) should include a command to merge the structs, replacing all occurrences of the types with one single type.

**Describe alternatives you've considered**
There aren't many alternatives here, you'd have to manually hunt down all instances of the types and manually merge the struct definitions.

**Additional context**
Rather conveniently, there is already struct merging, in that two revisions of the same struct can be merged. That logic can be repurposed for resolving the differences.

**Comment by nik0sc** [comment]
Inside the Data Type Manager pane you can drag struct A onto struct B. This will replace struct B with struct A.

**Comment by henke37** [comment]
Perfect.
