### ISSUE TITLE
Add Icon

### ISSUE THREAD

**Issue by jackby03** [NationalSecurityAgency/ghidra#6434]
Is your feature request related to a problem? Please describe.
Yes, the current process of launching our application involves navigating through the 'Start' menu or searching for the executable within the installation directory, which can be cumbersome and not user-friendly. I'm always frustrated when I need to quickly start the application for urgent security tasks and have to go through multiple steps to locate it.

Describe the solution you'd like
I would like an icon for a desktop shortcut to be created on Windows after installing the application. This icon would visually represent our tool and allow users to launch the application with a double-click, facilitating quick access and enhancing workflow efficiency, especially during incident response situations.

Describe alternatives you've considered
An alternative would be to provide an option during the installation process that asks users if they wish to create a desktop shortcut. Another possibility would be including a step in the application's documentation to instruct users on how to manually create a shortcut to the executable.

Additional context
Adding a desktop shortcut icon as a standard feature of our installation would improve user experience and provide a more direct and professional means of interacting with our tool. Users expect to be able to access security applications swiftly, as every second counts when responding to vulnerabilities or attacks. Here you might add screenshots or any other context that supports the feature request.

![Screenshot 2024-04-18 223357](https://github.com/NationalSecurityAgency/ghidra/assets/70082129/de019c45-4c30-4607-a6b7-b2064f9fb3ba)

**Comment by DeltaCoding0** [comment]
You can create a shortcut of "ghidraRun.bat" on desktop, then go to properties of that shortcut file you will find option to choose icon for this shortcut

ghidra icon is located in the "support" folder
