### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by phofers** [NationalSecurityAgency/ghidra#6452]
**Describe the bug**
There's a typo in README. It says:
"...to develop Ghidra and other cybersecurity tools for NSA to help protect our nation and its allies..."
It should say instead:
"...to develop Ghidra and other cybersecurity tools for _the_ NSA to help protect our nation and its allies..."

**To reproduce**
1. Read README

**Expected behavior**
The word "the" should be included in README.

**Screenshots**
![nsa spelling error](https://github.com/NationalSecurityAgency/ghidra/assets/100822843/8b7f531a-eafd-4233-868e-5a3140a29516)

**Attachments**

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Java Version: N/A
 - Ghidra Version: 11.0.3
 - Ghidra Origin: GitHub

**Comment by d-millar** [comment]
Yeah, we say "NSA" vs "the NSA".  If we change it to "the NSA", no one will believe it's us.  :)

**Comment by phofers** [comment]
> Yeah, we say "NSA" vs "the NSA". If we change it to "the NSA", no one will believe it's us. :)

Oh, sorry about that. I suppose I should do a _little_ bit of research before wasting your time on this.

**Comment by d-millar** [comment]
No problem - and now your good to go when you talk to folks at CIA.  :)
