### ISSUE TITLE
Create a PCodeCfgGraphTask from a Script

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#6459]
I want to graph the P-Code CFG of a function with more fine grained decompiler options than what the UI offers (e.g. to look at the differences between the "normalize" and the "decompile" simplifcation style).

The `PCodeCfgGraphTask` itself is public, but the constructor needs an argument of type `PcodeGraphSubType` and this enum is package private inside the `PCodeCfgGraphTask` class

How can I use the `PCodeCfgGraphTask` from a script/console ?

Or is this just an oversight and the `PcodeGraphSubType` should be made accessible from a script in some way?

**Comment by dragonmacher** [comment]
I think that is just an oversight.   I will update that enum to be public.
