### ISSUE TITLE
[PDB, VS6] Error when trying to import PDB from a binary compiled in VS6

### ISSUE THREAD

**Issue by SmileyAG** [NationalSecurityAgency/ghidra#6464]
**Describe the bug**
I'm not sure if this can be counted as a duplicate of #1062, because as I understood the meaning of that issue was that there was no support for the old PDB format at all (which is used in VS6 and older versions)

Support for importing old PDBs was added starting from 10.0 version according to the next comment: https://github.com/NationalSecurityAgency/ghidra/pull/1304#issuecomment-848860476

But as you can see in my issue, an error is thrown during processing in latest version of Ghidra (see the screenshot or `application.log`)

**To Reproduce**
- Import any binary and its .pdb into Ghidra that compiled in VS6.0 (1998) for analysis. Default analysis options were used.

**Screenshots**
![ghidra-error-when-importing-pdb-from-binary-compiled-in-vs6](https://github.com/NationalSecurityAgency/ghidra/assets/58108407/3c7e5650-7ee6-4103-a641-c5a6d7ac2186)

**Attachments**
[hltv-vs6-with-pdb.zip](https://github.com/NationalSecurityAgency/ghidra/files/15142514/hltv-vs6-with-pdb.zip)
[application.log](https://github.com/NationalSecurityAgency/ghidra/files/15142515/application.log)

**Environment (please complete the following information):**
 - OS: [Windows 10, 64 bit]
 - Java Version: [jdk-17.0.2]
 - Ghidra Version: [11.0.3]
 - Ghidra Origin: [official GitHub distro]

**Comment by ghizard** [comment]
I will look into the PDB parsing to see what is going on.
