### ISSUE TITLE
Cannot build using Gradle 7.4.2

### ISSUE THREAD

**Issue by benzhi** [NationalSecurityAgency/ghidra#6472]
I've pulled the latest Ghidra code and try to follow the steps specified in readme.md. 
Init works if I disable the hash-checks.
`gradle prepdev` and `gradle buildGhidra` fail, no matter what I try. I get the following error:
```
Execution failed for task ':Utility:compileJava'.
> error: invalid source release: 17
```

I have Temurin JDK 17.0.5+8 installed.

Following information from Gradle:
Gradle: 7.4.2
OS: Windows 10
Arch: amd64 (gradle: x86-64)
Using platform: win_x86_64
Searching for latest Visual Studio and required components...
  -> Visual Studio not found!

The last warning is incorrect: I have Visual Studio 2022 installed.

I tried a suggested ugrade command (gradle wrapper --gradle-version 8.7) from the gradle site, because I read that I would at least need gradle 8 to run JDK 17, which says "BUILD SUCCESSFUL in 5s", but my version is not upgraded. Any help would be very welcome!

**Comment by benzhi** [comment]
@ryanmkurtz , this is the output.
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Microsoft 11.0.12+7)
OS:           Windows 10 10.0 amd64

**Comment by ryanmkurtz** [comment]
You an see from that output that gradle is using Java 11.0.12.  It needs to be using 17+.

**Comment by ryanmkurtz** [comment]
I'm going to assume this will work fine once you have gradle using the correct java version, so I'm closing.  Feel free to comment with additional questions if you are still having issues.

**Comment by benzhi** [comment]
Thanks! I will give it a try tonight and let you know!

Op wo 1 mei 2024 om 17:36 schreef Ryan Kurtz ***@***.***>:

**Comment by benzhi** [comment]
@ryanmkurtz , thanks again! That was (obviously) the problem. I thought I needed to upgrade Gradle to use 17, sorry for the noobish question
