### ISSUE TITLE
Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section.

### ISSUE THREAD

**Issue by Dzhake** [NationalSecurityAgency/ghidra#6474]
**Describe the bug**
I'm not sure if this is a bug.. probably no, but I didn't find any place where I can ask help.

As I understood ghidra requires Java and JDK. So, I installed latest java version (`Program Files (x86)/Java/` contains folder `jre1.8` now), and added `C:\Program Files (x86)\Java\jre-1.8\bin\` to PATH, which fixed some issue. But now I get "Failed to find a supported JDK." each time I try to run ghidra. I downloaded JDK from https://adoptium.net/temurin/releases/, (Windows,x64,JDK,17 - LTS), unzipped it in `C:\Program Files (x86)\jdk-17.0.11+9\`, and added `C:\Program Files (x86)\jdk-17.0.11+9\bin\` to PATH. Nothing changed. I tried installing x86 JDK, putting JDK inside `Program Files (x86)/Java/` next to `jre1.8`, refering to `...\jdk-17.0.11+9\` without `bin\` in PATH, but nothing helped.

I'm also a bit confused about `java` and `jdk`, because installation guide is not very clear about those..

**To Reproduce**
(sorry, as i said above this is more of "pls help" post than bug report)

**Expected behavior**
I expected that ghidra will launch successfully.

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/74411975/6a77cb1c-00d4-4a24-bbb5-715b3fdd8974)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/74411975/ee0455a7-ad10-446f-a0f2-f470b1d41887)

**Attachments**
...

**Environment (please complete the following information):**
 - OS: Windows 10 ("OS build" in about says "19045.4291", but i'm not sure if this is related)
 - Java Version: (I'm confused about this)
 - Ghidra Version: 11.0.3
 - Ghidra Origin: official GitHub distro

**Additional context**
...

**Comment by Wall-AF** [comment]
Have you set `JAVA_HOME=C:\Program Files (x86)\jdk-17.0.11+9`?

**Comment by Dzhake** [comment]
No. Where do i do that?

**Comment by ryanmkurtz** [comment]
`C:\Program Files (x86)` is usually intended for 32-bit applications.  Are you downloading the 32-bit or 64-bit version of JDK 17?

**Comment by ryanmkurtz** [comment]
What is the output if you run `java -version` from the command line?  What about `javac -version`?

**Comment by Dzhake** [comment]
![image](https://github.com/NationalSecurityAgency/ghidra/assets/74411975/1de226cf-cd08-462f-84b8-4699e7ffbd54)
I have no clue did I download 32-bit or 64-bit version of JDK, sorry. If that's related to x64/x86 then I tried both.

**Comment by ryanmkurtz** [comment]
What is probably happening is that Ghidra is using your Java 1.8 JRE to try to find a compatible version of the JDK to run with (17+), but Ghidra doesn't know to look in `C:\Program Files (x86)`.  It looks here:
```java
		javaRootInstallDirs.add(new File("C:\\Java"));
		javaRootInstallDirs.add(new File("C:\\Program Files\\Java"));
		javaRootInstallDirs.add(new File("C:\\Program Files\\Amazon Corretto"));
		javaRootInstallDirs.add(new File("C:\\Program Files\\Eclipse Adoptium"));
		javaRootInstallDirs.add(new File("C:\\Program Files\\Microsoft"));
```

You have a couple of options:
* Adjust your PATH so your JDK 17 appears before your JRE 1.8.  This would result in `java -version` reporting java 17 rather than 8.
* Edit your Ghidra `support/launch.properties` file and set the `JAVA_HOME_OVERRIDE` variable to `C:\Program Files (x86)\jdk-17.0.11+9`
* Move your JDK 17 installation to one of those locations i listed above.

**Comment by Dzhake** [comment]
Tried settings `JAVA_HOME_OVERRIDE`, but it didn't work. So I put JDK in `C:/Program Files/` (now i understand that this is pretty pointless... beucase i didn't move it to any of locations above), then edited PATH variable and moved it to top. It works now!!! Thank you so much ❤️
