### ISSUE TITLE
Ghidra build from source fails with C compilation errors on Fedora 40 with gcc 14.0.1 

### ISSUE THREAD

**Issue by thixotropist** [NationalSecurityAgency/ghidra#6478]
**Describe the bug**
`gradle buildGhidra` fails on Fedora 40 with its default gcc 14.0.1

**To Reproduce**
1. Demonstrate a successful build of the master branch on a Fedora 39 system
2. Upgrade to Fedora 40
3. Attempt `gradle buildGhidra` 
4. See multiple C compilation errors thrown when compiling Ghidra/Debug/Framework-Debugging/src/{expCloneExec/c/expCloneExec.c,expFork/c/expFork.c,expSpin/c/expSpin.c,expTypes/c/expTypes.c}

**Expected behavior**
A clean build without GCC `incompatible pointer type`, `implicit-function-declaration`, and `implicit-int` errors

**Environment :**
 - OS: Fedora 40 with its default gcc 14.0.1 toolchain
 - Java Version: NA - only  C compilation is affected
 - Ghidra Version: 11.1-DEV
 - Ghidra Origin: official GitHub distro 

**Additional context**
The compilation errors can be resolved by adding `#include <unistd.h>` in three files and this patch:

```text
diff --git a/Ghidra/Debug/Framework-Debugging/src/expTypes/c/expTypes.c b/Ghidra/Debug/Framework-Debugging/src/expTypes/c/expTypes.c
index 33ee6f38da..ba97e80992 100644
--- a/Ghidra/Debug/Framework-Debugging/src/expTypes/c/expTypes.c
+++ b/Ghidra/Debug/Framework-Debugging/src/expTypes/c/expTypes.c
@@ -38,7 +38,7 @@ typedef enum _myenum {
 typedef void (*myfunc_p)(int arg0, long arg1);
 typedef void (*myvargfunc_p)(int arg0, long arg1, ...);
 
-typedef myundef;
+typedef int myundef;
 
 int int_var;
 void* void_p_var;
@@ -86,11 +86,11 @@ int main(int argc, char** argv) {
     printf("complex: %d\n", sizeof(complex_var));
     printf("double complex: %d\n", sizeof(double_complex_var));
     
-    register mycomplex_p cparts = &complex_var;
+    register mycomplex_p cparts = (struct _mycomplex *) &complex_var;
     printf("single real: %f\n", cparts->real);
     printf("single imag: %f\n", cparts->imag);
     
-    mydoublex_p dparts = &double_complex_var;
+    mydoublex_p dparts = (struct _mydoublex *) &double_complex_var;
     printf("double real: %g\n", dparts->real);
     printf("double imag: %g\n", dparts->imag);
```
The full patch can also be found at 
https://github.com/thixotropist/ghidra/commit/bd05cff4a220959bb42e5049d5c3619707d9b2a1

That's likely not the best way to resolve the issue on all platforms and with all supported C compilers.

**Comment by jobermayr** [comment]
> The full patch can also be found at [thixotropist@bd05cff](https://github.com/thixotropist/ghidra/commit/bd05cff4a220959bb42e5049d5c3619707d9b2a1)
> 
Or as part of #5418

**Comment by nsadeveloper789** [comment]
I'll have to look a little more carefully when I get a moment.

On one hand, I was intentionally trying to generate an "undefined" type in the C source, so using `int` may not be what I want (although, if it's implicitly an `int`, then I'm already not getting what I want....) On the other, I don't think any test case is consuming the expTypes binary, anyway.... I'll evaluate the possibility of just deleting it. The addition of the `#include` seems perfectly reasonable to me.
