### ISSUE TITLE
It doesn't demangle PEF function names (classic mac): GCC < 3.0 / CodeWarrior format

### ISSUE THREAD

**Issue by Piruzzolo** [NationalSecurityAgency/ghidra#648]
**Describe the bug**
For instance, after autoanalysis with PEF debug enabled I see in decompiled code `.scroll__10TTextPanelFUcsi` instead of `TTextPanel::scroll((unsigned char, short, int))` as the name of a function. 

The file was almost certainly compiled with CodeWarrior on MacOS 8 or 9.

**Comment by Piruzzolo** [comment]
See issue 675

**Comment by emteere** [comment]
You can try turning off the Analysis->Demangler->OnlyDemangleKnownMangledSymbols. This can cause symbols that aren't mangled to demangle.
A simpler way is to run the DemangleSymbolScript on that symbol to see if the symbol can be demangled.  This should work as long as the demangle routine can either just keep the '.', or strip it off and the demangling is the same.

Normally a symbol has the _Z in front of it if it is mangled.  If this works, I suppose an option for the pre-characters that must be present could be added, or the '.' could be added as a pre-character that is accepted.

**Comment by Piruzzolo** [comment]
@emteere it doesn't work :(

**Comment by Piruzzolo** [comment]
The GNU c++filt utility partially does the job: it implements the old GCC format, very similar to the VisualAge one

**Comment by Piruzzolo** [comment]
The old GCC demangling format could be implemented using the C demangler, see [here](https://github.com/NationalSecurityAgency/ghidra/blob/b6b9b27128ab78c27fc71cfacf9b502470af4fce/GPL/DemanglerGnu/src/demangler_gnu/c/cplus-dem.c#L270). It requires just a few changes to the demangle api.

**Comment by dragonmacher** [comment]
Much has changed in demangler.   This seems to be working now.
