### ISSUE TITLE
make a button that shows tommy parky

### ISSUE THREAD

**Issue by unfunnylaugh** [NationalSecurityAgency/ghidra#6481]
![thomas](https://github.com/NationalSecurityAgency/ghidra/assets/129692077/032bcce1-0046-48ba-8a9b-5e2ac71ddaab)

**Comment by unfunnylaugh** [comment]
button i meant

**Comment by thecatontheceiling** [comment]
the first half of your name is accurate

**Comment by unfunnylaugh** [comment]
shut up tommy parky is funny

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Não
contém vírus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
