### ISSUE TITLE
error importing file

### ISSUE THREAD

**Issue by DogeWatch** [NationalSecurityAgency/ghidra#6497]
**Describe the bug**
Import file error
Invalid index: 24576
java.io.IOException: Invalid index: 24576

**Screenshots**
<img width="885" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/13670813/323502c5-8638-422c-b036-3a45fbf1385f">

**Attachments**
[fc68fc890e0d34c331d58c592f87d8058522498b50daa2b9d65d0b877e4fc7c9.zip](https://github.com/NationalSecurityAgency/ghidra/files/15271927/fc68fc890e0d34c331d58c592f87d8058522498b50daa2b9d65d0b877e4fc7c9.zip)

**Environment (please complete the following information):**
 - OS: macOS 14.4.1
 - Java Version: 17.0.1
 - Ghidra Version: 11.0.3
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
Can you provide some background info on this binary?  The segments seem to exceed the length of the file.  Is that intentional shenanigans or is the binary corrupt?
