### ISSUE TITLE
Decompile virtual function calls as c++ style calls

### ISSUE THREAD

**Issue by henke37** [NationalSecurityAgency/ghidra#650]
**Is your feature request related to a problem? Please describe.**
Many a target binary is made in C++ and as such is likely to use this functionality.

**Describe the solution you'd like**
Decompile the call to c++ style code.

**Describe alternatives you've considered**
The only other option is to manually define vtables and deal with two arrow operators on the callsite. Which is at best ugly and very likely to be a lot of boring work.

**Comment by pedrovanzella** [comment]
This is a duplicate of #516

**Comment by henke37** [comment]
I thought I checked that specific issue. Oh well.
