### ISSUE TITLE
Disassembly on e200z PowerPC not working

### ISSUE THREAD

**Issue by Walke256** [NationalSecurityAgency/ghidra#6532]
I've been working on some binary files that have been compiled for SPC563M64 (e200z335). I know that now, but when I started on the first file a year ago, I only knew it would be for PowerPC. I managed to disassemble some code (I think it was done automatically during analysis) with Ghidra 10.3, choosing PowerISA-VLE-64-32addr. It resulted in 5 functions in the symbol tree and some additional functions (like below) that are greyed out and not visible in the symbol tree), containing variable length instructions (see example below), without halt_baddata() signatures. Whether the binary was actually compiled for VLE or default Power Architecture is not clear to me.

Example code:

        000a097c 9f bf           se_stb     r27,0xf(r31)
        000a097e 53 cd 9f 1c     e_lwz      r30,-0x60e4(r13)
        000a0982 c1 7e           se_lwz     r7,0x4(r30)
        000a0984 74 86 20 37     e_rlwinm   r6,r4,0x4,0x0,0x1b
        000a0988 04 67           se_add     r7,r6
        000a098a c3 77           se_lwz     r7,0xc(r7)
        000a098c 74 66 de 3f     e_rlwinm   r6,r3,0x1b,0x18,0x1f
        000a0990 6c 36           se_slwi    r6,0x3
        000a0992 7c a7 30 ae     lbzx       r5,r7,r6
        000a0996 74 66 04 21     e_rlwinm   r6,r3,0x0,0x10,0x10
        000a099a 00 e6           se_extzh   r6
        000a099c 2a 06           se_cmpi    r6,0x0
        000a099e e2 12           se_bne     cr0,LAB_000a09c2
        000a09a0 1c ed 9f 20     e_add16i   r7,r13,-0x60e0
        000a09a4 74              ??         74h    t
        000a09a5 86              ??         86h
        000a09a6 10 3b 7c 67     evmwhssfa  r1,r27,r15
        000a09aa 30 2e 74 a6     e_lbz      r1,DAT_000074a6(r14)                             = FFh
        000a09ae 20 37           se_addi    r7,0x4
        000a09b0 04 36           se_add     r6,r3
        000a09b2 18 a6 80 80     e_addi     r5,r6,0x80
        000a09b6 00 cf           se_extzb   r31
        000a09b8 c0 65           se_lwz     r6,0x0(r5)
        000a09ba 77 e6 83 1e     e_rlwimi   r6,r31,0x10,0xc,0xf
        000a09be d0 65           se_stw     r6,0x0(r5)
        000a09c0 e8 07           se_b       LAB_000a09ce
                             LAB_000a09c2                                    XREF[1]:     000a099e(j)  
        000a09c2 c5 7e           se_lwz     r7,0x14(r30)
        000a09c4 00 b7           se_mtctr   r7
        000a09c6 77 e4 06 3f     e_rlwinm   r4,r31,0x0,0x18,0x1f
        000a09ca 48 06           se_li      r6,0x0
        000a09cc 00 07           se_bctrl
                             LAB_000a09ce                                    XREF[1]:     000a09c0(j)  
        000a09ce 1b c1 08 18     e_lmw      r30,0x18(r1)
        000a09d2 c9 01           se_lwz     r0,0x24(r1)
        000a09d4 00 90           se_mtlr    r0
        000a09d6 21 f1           se_addi    r1,0x20
        000a09d8 00 04           se_blr

Now, one year later, I don't get any code in the binaries disassembled during analysis. By now I work with Ghidra 11.0.3, but it does not matter what PowerPC architecture I use, and also I cannot reproduce the results I had last year, even if I use Ghidra 10.3. If I force disassemble the areas that seemed fine (again using PowerISA VLE language) I get a different result, with only 32bit instructions (so no variable length) and a lot of halt_baddata() signatures. It kind of resembles what I read in issue #5856, although I do see in the examples of that issue some VLE instructions. Because I now know, the CPU is e200z335 core, I tried the settings provided in https://github.com/mborgerson/ghidra/commit/0287403adfe52aad6f9013712f285d0bae0cacaa by @mborgerson but this does not change the situation. I did not get the code from the aforementioned commit built because the Gradle build had troubles finding Visual Studio tools, so I took the changes from the commit into my current Ghidra instance (11.0.3).

Same code, current disassembly:

        000a097c 9f bf 53 cd     stbu       r29,0x53cd(r31)
                             -- Length Override: 2 (actual length is 4)
                             -- Fallthrough: 000a0980
        000a097e 53              ??         53h    S
        000a097f cd              ??         CDh
                             LAB_000a0980                                    XREF[1]:     000a097c  
        000a0980 9f 1c c1 7e     stbu       r24,-0x3e82(r28)
                             -- Length Override: 2 (actual length is 4)
                             -- Fallthrough: 000a0984
        000a0982 c1              ??         C1h
        000a0983 7e              ??         7Eh    ~
                             LAB_000a0984                                    XREF[1]:     000a0980  
        000a0984 74 86 20 37     andis.     r6,r4,0x2037
From here nothing is disassembled and an error for a bad instruction is displayed at 0xa0988:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/169972903/f896ed3a-8796-4b3a-9c39-734ece56f65d)

I don't have original code, so I provided some example instructions. If the problem is, the instructionset is incomplete (like mentioned in #5856), I'd be happy to help out completing instructions (if I know how, I did not contribute any code to the project so far).

Some info on my environment: Windows 10, Eclips Temurin JDK with Hotspot 17.0.5+8 (X64), Ghidra versions 10.3 and 11.0.3

**Comment by PTDreamer** [comment]
Hi, I'm working on target (motorcycle ECU) with the same processor. Ghidra decompiles the code properly. Make sure you set the VLE register to "1" before analyzing.  Select all code, CTRL+R, search for "vle", set it to "1".

**Comment by Walke256** [comment]
Hey @PTDreamer, thank you so much for your response! I did not know the "Set Register Value..." option! I had been searching Power ISA documentation for register addresses, but without success. This did the trick for me, thanks!

**Comment by Walke256** [comment]
@PTDreamer, it really helped a lot. I seem to be able to dissassemble a huge block of code (close to 1MB). Still having trouble, though, to find some logical references to known (ignition, injection) map addresses in the ROM file, and CPU addresses, such as CAN messageboxes, digital and analog inputs, timers, etc. Somehow I feel, like I am still missing something crucial. I see a lot happens in code with an in_r13 variable, pointing to register r13 in the assembly (which before the function calls in calling functions never really seems to be set). Also, in the CPU manual, I find multiple registers but not a general register configuration where it could point to, so I am really clueless how to proceed. Do you have any further tips?
p.s. I also tried working with some special E200 configurations, picked from a fork of mborgerson but that fails to disassemble lots of code. Where it succeeds, it seems largely to overlap with the regular Power ISA VLE disassembly.

**Comment by PTDreamer** [comment]
The ABI defines r13 as the small data area pointer (SDA) and R2 as SDA2. You   need to find where those are set (near the entry point) and then use the same method you used for VLE to define them throughout the code.
Now about map data not being referenced that can be related to the use of the MMU and TLBs. There are special opcodes to set these up so is should be easy to find.

**Comment by PTDreamer** [comment]
Fill free to DM me if you need further help, it seems we are working on similar targets so we can probably exchange some notes

**Comment by Walke256** [comment]
> The ABI defines r13 as the small data area pointer (SDA) and R2 as SDA2. You need to find where those are set (near the entry point) and then use the same method you used for VLE to define them throughout the code. Now about map data not being referenced that can be related to the use of the MMU and TLBs. There are special opcodes to set these up so is should be easy to find.

Thanks! I will check those out! (y)

**Comment by 2786524793-boop** [comment]
> 您好，我正在使用相同的处理器对目标设备（摩托车ECU）进行分析。Ghidra 可以正确反编译代码。请确保在分析之前将 VLE 寄存器设置为“1”。选中所有代码，按 CTRL+R，搜索“vle”，将其设置为“1”。

I'm also analyzing the motorcycle, but GitHub doesn't have the PowerPC e200z3 model - what should I do
