### ISSUE TITLE
ARM: TEQP instruction fails to decode

### ISSUE THREAD

**Issue by philpem** [NationalSecurityAgency/ghidra#654]
**Describe the bug**
The disassembler cannot disassemble some variants of the ARM TEQ instruction.

**To Reproduce**
Load the following code block in to Ghidra:
```
        00000270 01 00 31 e3     teq      r1,#0x1
        00000274 1c 00 00 1a     bne      LAB_000002ec
                             LAB_00000278                                    XREF[1]:     000002fc(j)  
        00000278 c2              ??       C2h
        00000279 f3              ??       F3h
        0000027a 3f              ??       3Fh    ?
        0000027b e3              ??       E3h
        0000027c 00 00 a0 e1     cpy      r0,r0
        00000280 14 27 9f e5     ldr      r2,[Service_ADFSPoduleIDE_Response.r2_addrNewCtlr]= null
```

Note that this is ARM little-endian, v7.

**Expected behavior**
Per shell-storm.org/online/Online-Assembler-and-Disassembler/

```
0x0000000000000000:  C2 F3 3F E3    teq pc, #0x8000003
0x0000000000000004:  03 F0 3F E3    teq pc, #3
```

Per http://www.keil.com/support/man/docs/armasm/armasm_dom1361289912729.htm -- use of SP or PC is deprecated as of ARMv6T2 and above, but is available in ARMv5.  (Indeed it's widely used in 26-bit ARM code e.g. old Acorn ARM RISC OS modules and similar)

**Environment (please complete the following information):**
 - OS: Linux - Ubuntu 18.04.2 LTS "bionic"
 - Java Version: 11.0.3
 - Ghidra Version: 9.0.2

**Comment by mumbel** [comment]
That seems like an unpredictable instruction.  It's ignoring the the SBZ field in bits 12-15 looks like

**Comment by philpem** [comment]
Looking further into this, it looks like it's actually a TEQP - a special-case of TEQ which is used on 26bit ARM:

https://www.heyrick.co.uk/armwiki/The_Status_register#Changing_processor_status

**Comment by philpem** [comment]
I've added a PR with a noddy fix for this (more like a workaround).

The ideal fix would map the 26bit PSR bits onto the CPSR and update it accordingly.

**Comment by philpem** [comment]
Documentation reference:

http://datasheets.chipdb.org/ARM/arm.pdf 
ARM DDI 0100E, ARM Architecture Reference Manual
Page A8-6, "26-bit PSR update instructions"

> In 26-bit architectures, the MSR and MRS instructions are not supported. Instead, variants of the CMN, CMP, TEQ and TST instructions are used to write just the PSR part of R15 without affecting the PC part. These 26-bit-only variants are called CMNP, CMPP, TEQP and TSTP, and are distinguished by having instruction bits[15:12] equal to 0b1111. These bits are equal to 0b0000 in the normal variants of these instructions.
> These instructions write their ALU result directly to the PSR part of register 15 (only N, Z, C, and V are affected in User mode).
> When the processor is in User mode, only the condition codes are affected. All other modes allow all PSR bits to be altered.
