### ISSUE TITLE
Cannot enable BSim

### ISSUE THREAD

**Issue by alexdevsec** [NationalSecurityAgency/ghidra#6547]
**Describe the bug**

I'm trying to enable the BSim tool and it gives me an error that it has an unresolved dependency "Ghidra.app.decompiler.DecompilerHighlightService". 

**To Reproduce**
1. Go to the main Ghidra window
2. Select "Tools -> Create Tool:
3. Check to enable Sim
4. See error, and Bsim. is never actually enabled.

**Expected behavior**
I'd expect BSim to be enabled

**Screenshots**

<img width="801" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/47580386/ffecbcbd-8e8c-4b6e-9f68-96f4b164667a">

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
- OS: macOS Sonoma 14.4
- Java Version: 17.0.1
 - Ghidra Version: 11.0.3 Build PUBLIC
 - Ghidra Origin: Download zip from ghidra-SRE

**Comment by ryanmkurtz** [comment]
I'm reproducing this.

**Comment by ghidra1** [comment]
The issue may stem from the facy that service providers must be plugins.  In the case of the `DecompilerHighlightService` the service provider is not a plugin.  Although the DecompilerPlugin provides the service it does not implement the interface.
