### ISSUE TITLE
Ghidra does not respect OS blink settings

### ISSUE THREAD

**Issue by LATENTBOUNCE** [NationalSecurityAgency/ghidra#6570]
You can remove some of the blinking:

1. Edit -> Tools Options
2. Options -> Listing Fields -> Cursor
3. Disable "Blink Cursor"

This disables blinking in the Listing field, but not in the Decompile Window, nor in any of the text boxes. Plus Ghidra does not respect system set blink settings.

For some this makes it difficult to use the software, which would be a shame if it is easy to fix.

**Comment by kermitfrog** [comment]
As commented in #2614 this is not fixed, but actually gotten worse.
EDIT: Nevermind - I did not find the setting at first (for anyone looking for this: it's only available in the tool settings when opened from the main window), a closer look at the MR led me to the right option, but you might want to remove the one for Listing Fields, as it does not seem to be doing anything now.
