### ISSUE TITLE
Cannot Load Win PE Import Table

### ISSUE THREAD

**Issue by cubictriangle** [NationalSecurityAgency/ghidra#6571]
**Describe the bug**
Ghidra cannot load the import table if the size value in optional header is too big.
But Windows Operating System do not use the size value in optional header to decide the size of the import table.
The import table is null-terminated, OS will stop loading when it find an all 0 import directory.

**To Reproduce**
1. Choose a Win PE executable file.
2. Open the exe file using a hex editor (ImHex for example).
3. Change the value of import table size in optional header to a very large number (0xFF FF FF FF for example).
4. Save the change and close the file.
5. Open the Ghidra and create a new project.
6. Import the exe file into the Ghidra.
7. Click on imported file in Ghidra and Click 'Yes' when Ghidra ask to analyze it.
8. Wait.
9. Click "Imports" in "Symbol Tree" and you will see nothing.
10. If you check the IAT and CALL instructions which call those import functions, you would not see the function names.

**Expected behavior**
"Imports" in "Symbol Tree" should shows imported libraries and functions.
IAT should shows the libraries and functions name.
When calling import function, CALL instructions should be followed by the libraries and functions name.

**Screenshots**
This is what Ghidra should be:
![should-be](https://github.com/NationalSecurityAgency/ghidra/assets/115812485/4fe2c57e-f5ee-41ed-8790-c40b39c8e509)

This is what it actually looks:
![actually-looks](https://github.com/NationalSecurityAgency/ghidra/assets/115812485/f2e72360-9068-4831-bdf9-e415e9921d56)

The only difference is the value of import table size in optional header.
And this program can run just fine.
![ninja-too-big-import-table-size](https://github.com/NationalSecurityAgency/ghidra/assets/115812485/c86d5219-8b05-423e-a864-bf3959249f51)

**Attachments**
None

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10
 - Java Version: openjdk 22.0.1
 - Ghidra Version: 11.0.3
 - Ghidra Origin: official GitHub distro

**Additional context**
None

**Comment by ryanmkurtz** [comment]
Do you know if this is a unique feature of just the Import Table Data Directory, or do other Data Directories ignore the size too?
