### ISSUE TITLE
Pop-up window not getting focus

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#6576]
**Describe the bug**
Double clicking an enum or struct which opens the enum editor or struct editor window (may also be others) from data type manager does not get focus (window is behind code-browser window).  If the enum editor or struct editor window is already open it does get focus when double clicking the enum/struct.

**Environment (please complete the following information):**
Ghidra Version: 11.2  (fb844be1f61d71063b1e392f319d352cdd19b962)
Ghidra Release: DEV
Ghidra Build Date: 2024-May-24
Ghidra Revision: ???
Ghidra Development Mode: true
OS Name: Linux
OS Arch: amd64
OS Version: 6.5.0-35-generic
OS Pretty Name: Ubuntu 22.04.4 LTS
Java Vendor: Private Build
Java Version: 17.0.10

**Comment by dragonmacher** [comment]
I'm fixing the log messages.  

However, I am unable to reproduce the windowing issue.

**Comment by mumbel** [comment]
yeah, doesn't look like logs are related to the struct in background or foreground after trying it more, triggering it w/o them (i think maybe its just if the struct has a pointer in it or not to get the log?)

**Comment by mumbel** [comment]
was able to bisect down to 495dc4df663250d1f3db1d1c7ec7c68b0d2a230c

**Comment by dragonmacher** [comment]
Thanks for the help!    I have a fix in review.

**Comment by mumbel** [comment]
11.2?

**Comment by dragonmacher** [comment]
> 11.2?

Correct

**Comment by mumbel** [comment]
Awesome, thanks!

**Comment by ryanmkurtz** [comment]
> > 11.2?
> 
> Correct. I will also add this to the patch branch so it will go out in 11.1.1.

0e2d4a182cffa8c142a8fef3afc82181ccff7f11

**Comment by mumbel** [comment]
This is still pretty buggy with 11.1.2

If I double click a data type in the dtm the odds that the struct editor gets focus/foreground is not 100%

And I didn't notice this before when filing originally, but it will also not make that tab in the struct editor on top 100% of the time if multiple structs are open for editing

**Comment by dragonmacher** [comment]
@mumbel We added code which may fix the issue related to the editors not getting focus.   Since we were unable to reproduce the issue, we are guessing at the solution.   When you have the opportunity, we hope you can try our fix, which is in here: https://github.com/NationalSecurityAgency/ghidra/commit/f20275ed0465d667d22dc32406a31ddec2811afc

Thanks!

**Comment by mumbel** [comment]
Sure, I'll try to get a build this weekend and see if it repros  (though i don't know if I've built master since the java/gradle bump, so hopefully that doesn't mess with me)

**Comment by mumbel** [comment]
@dragonmacher   I attempted to repro some of the issues I've noticed in 11.1.2 and wasn't able.  hopefully squashed :+1:

**Comment by dragonmacher** [comment]
> @dragonmacher I attempted to repro some of the issues I've noticed in 11.1.2 and wasn't able. hopefully squashed 👍

Awesome, thanks!
