### ISSUE TITLE
Access is denied when opening ghidra

### ISSUE THREAD

**Issue by gordonmike** [NationalSecurityAgency/ghidra#6579]
Im getting access is denied when opening ghidra, i read the installation guide and also set the path variable, when i open ghidra it asks for path to jdk even when i put it to path, so i put the path to jdk home directory but it says access is denied, same with admin.

![Screenshot 2024-05-25 175955](https://github.com/NationalSecurityAgency/ghidra/assets/68188670/84872ad0-5215-4cbd-9779-f24534fdfff8)

**Comment by d-millar** [comment]
OK, probably a stupid question, but…. what are the permissions on “C: \Users\cordt\.ghidra\.ghidra_11.0.3_PUBLIC\java_home.save”?

**Comment by gordonmike** [comment]
tbh i cant find the file java_home?

**Comment by gordonmike** [comment]
has anyone else has the same problem before?
can you help me please?

**Comment by d-millar** [comment]
Note the dots!   .ghidra and .ghdra_xxx are hidden directories.

**Comment by gordonmike** [comment]
@d-millar java_home.save has full permissions

**Comment by gordonmike** [comment]
pasted ghidra in user\username and unhidden the folder user\username, if urs not hidden hide then unhide including files.
