### ISSUE TITLE
Upgrade Ghidra FW

### ISSUE THREAD

**Issue by yooo1999** [NationalSecurityAgency/ghidra#6623]
Maybe you can add a feature to upgrade Ghidra inline the Ghidra.
For example now I have Ghidra 11.0.1 in Windows and I want to upgrade for 11.1  , and all configurations will saved (remote server etc.)

Maybe add a button in help menu that do the upgrade process automatically

**Comment by ryanmkurtz** [comment]
This is a fine idea, but we prefer to keep our simple download/unzip process and put our resources elsewhere.
