### ISSUE TITLE
UI doesn't react to clicks after using mouse button4/5 to navigate back/foward

### ISSUE THREAD

**Issue by BhaaLseN** [NationalSecurityAgency/ghidra#6624]
**Describe the bug**
After using the thumb buttons on the mouse (normally Button4 and Button5 in most tools that allow mappings,) none of the windows react to regular left/right clicks. This isn't even limited to the disassembly UI, but also to other windows such as the Script manager or the Ghidra main window.

**To Reproduce**
0. Have a mouse with thumb buttons that map to "Next Location in History" and "Previous Location in History".
1. Open any function that calls other functions (in my case: a constructor that calls base constructors)
2. Double-click on a function to navigate to it (in my case: the base constructor)
3. Repeat if necessary.
4. Use the thumb button to navigate backwards to the first function.
5. Double-click the next function to get a clearer picture of what happens.

**Expected behavior**
I expect this to navigate backwards to the original function (which happens) so I can continue looking at other functions that are called (which doesn't work since clicks appear to be non-functional.)

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 19.0.1
 - Ghidra Version: 11.1
 - Ghidra Origin: official GitHub distro

**Additional context**
I was excited to try 11.1 after #208 was scheduled to land here. And while it works, it seems to eat mouse events for a while.

I _can_ get out of this supposedly mouse-locked situation by using the thumb buttons to navigate around (mostly back, I haven't observed going forward fixing anything.) At some point, clicks work again.

No logs unfortunately, the console is empty. The script from #208 did not show this issue.

**Comment by dragonmacher** [comment]
I see a few bugs related to this feature.      We will have a fix for this for our next patch release.

**Comment by BhaaLseN** [comment]
Yeah, it seems quite flaky too; it works a few times then starts blocking the UI. Next few attempts always block, then it works again for a few more times.

At the moment, I unbound the keys and went back to the old script; but I'll gladly give it a shot if theres a build available somewhere.
_(I could probably build it myself, but I haven't used Eclipse in years, so I don't know how quickly I'd be up to speed.)_

**Comment by ryanmkurtz** [comment]
[Building should be pretty easy](https://github.com/NationalSecurityAgency/ghidra#build).  You don't need Eclipse.
