### ISSUE TITLE
noticed a suspicious piece of code....

### ISSUE THREAD

**Issue by swpq** [NationalSecurityAgency/ghidra#6632]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.14.2]
 - Java Version: [e.g. 11.0]
 - Ghidra Version: [e.g. 10.1.4]
 - Ghidra Origin: [e.g. official GitHub distro, third party distro, locally built] 

**Additional context**
why u rat me??
why u rat me??
why u rat me??

**Comment by swpq** [comment]
why u rat me??

**Comment by swpq** [comment]
why u rat me??

**Comment by swpq** [comment]
why u rat me??

**Comment by swpq** [comment]
I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM I LOVE THE NSA I LOVE THE NSA THERE IS NO RAT IN THIS PROGRAM

**Comment by XVilka** [comment]
@ryanmkurtz this issue probably could be deleted completely to reduce the trash in the history.
