### ISSUE TITLE
Debugger "qemu + gdb" does not work

### ISSUE THREAD

**Issue by electricworry** [NationalSecurityAgency/ghidra#6634]
**Describe the bug**
Attempting to open the "qemu + gdb" results in the following error:

```
Failed to launch 'target' due to an exception:
java.lang.ClassCastException: class java.lang.String cannot be cast to class ghidra.framework.plugintool.
AutoConfigState$PathIsFile (java.lang.String is in module java.base of loader 'bootstrap'; ghidra.framework.plugintool.AutoConfigState%PathIsFile is in unnamed module of loader ghidra.GhidraClassLoader ...)
```

**To Reproduce**
1. From the Ghidra active project window, drag a program onto the Debugger tool in the tool chest
2. In Debugger, select the debugger tool icon > configure and launch 'target' using > qemu + gdb

**Expected behavior**
The qemu+gdb parameter dialog should be displayed instead.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: openjdk 17.0.11 2024-04-16
 - Ghidra Version: 11.1
 - Ghidra Origin: official GitHub distro

**Additional context**
The problem seems to be with the environment variable `GHIDRA_LANG_EXTTOOL_qemu` in the file `Ghidra/Debug/Debugger-agent-gdb/data/debugger-launchers/qemu-gdb.sh`. Replacing all three instances of `GHIDRA_LANG_EXTTOOL_qemu` in that file with an alternative string resolves the issue. Is there something problematic about that choice of environment variable name?

**Comment by nsadeveloper789** [comment]
Interesting. I think I know the right fix, but yeah, it's related to the env variable name. That name is "magical" in that the default value is derived from a property in the language spec. Looks like I forgot to convert that `String` default to a `PathIsFile`. The workaround you did should be fine. You just won't get a default value. I'll put a ticket in on our end.
