### ISSUE TITLE
gdb version of util.py doesn't correctly parse gdb versions with a dash in them.

### ISSUE THREAD

**Issue by lexknuther** [NationalSecurityAgency/ghidra#6646]
**Describe the bug**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../ghidra/Ghidra/Debug/Debugger-agent-gdb/build/pypkg/src/ghidragdb/__init__.py", line 16, in <module>
    from . import util, commands, parameters
  File ".../ghidra/Ghidra/Debug/Debugger-agent-gdb/build/pypkg/src/ghidragdb/util.py", line 34, in <module>
    GDB_VERSION = _compute_gdb_ver()
  File ".../ghidra/Ghidra/Debug/Debugger-agent-gdb/build/pypkg/src/ghidragdb/util.py", line 31, in _compute_gdb_ver
    return GdbVersion(full, int(major), int(minor))
ValueError: invalid literal for int() with base 10: '1-5'
Error while executing Python code.

Output of show version:
GNU gdb (GDB) Red Hat Enterprise Linux 12.1-5.el9

**To Reproduce**
1.  Debug any binary with gcc-toolset-12/13 on any RHEL or Oracle Linux distribution

**Expected behavior**
Version parsed correctly.  Ideally, a regular expression could be used to extract the version parts and ignore the '-'.

**Environment (please complete the following information):**
 - OS: RHEL 9.4
 - Java Version: 21
 - Ghidra Version: 11.2
 - Ghidra Origin: official GitHub distro

**Additional context**

**Comment by d-millar** [comment]
@lexknuther Thanks for the heads up - don't have an easily accessible copy of RHEL 9.4.  Any chance you could send us your "show version" result?  (The logic still works on the copies of RHEL I have at hand.)

**Comment by lexknuther** [comment]
I included the output in the bug report.

**Comment by d-millar** [comment]
Ah, my mistake - overlooked it!!!
