### ISSUE TITLE
HighFunction.getVarnodes(AddrSpace) does not return Varnodes with negative offsets

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#6652]
**Describe the bug**
As described in #6307 , the underlying ``VarnodeBank.locRange`` method used to compute the Varnodes in the AddressSpace uses 0 as a lower bound. This means that varnodes with negative offsets e.g. stack are not returned, as shown below (when clicking on a token corresponding to a stack address)

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/b8a16ccd-6bf1-43d8-8869-611c73e891d5)

**Comment by ryanmkurtz** [comment]
Closed by f6dfa0964acb2ee3379a1c4f7f94a95ed7a9cba4
