### ISSUE TITLE
CodeBrowser focuses on menu bar after releasing forward/back hotkey (containing `alt`)

### ISSUE THREAD

**Issue by shuffle2** [NationalSecurityAgency/ghidra#6654]
**Describe the bug**
CodeBrowser focuses on menu bar after releasing forward/back hotkey (containing `alt`)

**To Reproduce**
Navigate in the disasm view such that location history will be populated.
Use `alt+` `left arrow`, `right arrow` to navigate back and forth through the history.
Note that sometimes, releasing the `alt` key results in focus being transferred to CodeBrowser's File...Edit...Analysis...etc menubar (the cursor in disasm view will be lighter color, and text in the menubar will have hotkey characters underlined).
-> need to hit `esc` or `alt` again to return focus to disasm view.

**Expected behavior**
Focus does not leave original window view.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22631.3737]
 - Java Version: jdk-21.0.3+9
 - Ghidra Version: 3ec2dfb2011579933c43177e4d38d204ff248b7d
 - Ghidra Origin: locally built

**Additional context**
This is not a new problem (not related to recent focus changes).

**Comment by dragonmacher** [comment]
I tried this on Linux, Mac and Windows.   Windows is the only OS I see the the problem on.  I'm investigating the issue more.

**Comment by dragonmacher** [comment]
As a workaround, you can remap the keybindings to not use the Alt key.

**Comment by dragonmacher** [comment]
We have no plans to make any changes to address this issue at this time.
