### ISSUE TITLE
Continuing from a breakpoint in GDB 9.2 fails.

### ISSUE THREAD

**Issue by forky2** [NationalSecurityAgency/ghidra#6666]
**Describe the bug**
Following on from #6656, when using the gdb debugger profile with GDB 9.2, on continue from a breakpoint the python hook `on_stop` fails with the following error:

```
Traceback (most recent call last):
  File "/home/forky2/ghidra_11.1.1_PUBLIC/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/hooks.py", line 161, in _func
    return func(*args, **kwargs)
  File "/home/forky2/ghidra_11.1.1_PUBLIC/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/hooks.py", line 311, in on_stop
    state.record("Stopped")
  File "/home/forky2/ghidra_11.1.1_PUBLIC/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/hooks.py", line 89, in record
    commands.put_frames()
  File "/home/forky2/ghidra_11.1.1_PUBLIC/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/commands.py", line 1400, in put_frames
    f = newest_frame(gdb.selected_frame())
gdb.error: No frame is currently selected.
Python Exception <class 'gdb.error'> No frame is currently selected.: 
```

**To Reproduce**
1. Create an x86_64 helloworld:
    ```
    gcc -x c -o helloworld - <<EOF
    #include <stdio.h>
    
    int main(int argc, char *argv[])
    {
        printf("Hello, world!\n");
        return 0;
    }
    EOF
    ```
2. Run Ghidra 11.1.1 with the python patch from #6656 applied.
3. Import helloworld to Ghidra project
4. Start a gdb debugger session with the default parameters
5. GDB breaks on _start()
6. Press F5 or enter `continue` into GDB Terminal
7. Exception as above is thrown

**Expected behavior**
Program should run to termination with no exception.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3
 - Java Version: OpenJDK 21.0.3
 - Ghidra Version: 11.1.1
 - Ghidra Origin: official GitHub distro
 - GDB Version: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.2) 9.2

**Additional context**
Apologies for raising multiple issues that affect an older version of GDB. No offense will be taken if you decide that GDB 9.2 is too old. I'm mainly raising because I like Ghidra and many people's initial experience of the debugger will be using it against these older versions due to them being the default in LTS releases of certain distros.

So far I have confirmed that the issue doesn't occur in GDB 13.2 which I built for testing. I think GDB 9.2 is erroneously calling the `on_stop` hook.

**Comment by qvipin** [comment]
yo congrats ur issue 6666

**Comment by d-millar** [comment]
OK, I might have a guess on this one.  I believe the issue is that many of the commands we're using to record state when the debugger stops are not valid in the group:memory catchpoint for gdb 9.2 (and possibly 10.2, as well).  As a test, if you're up for it, at the initial break issue the command "info breakpoints" in the Terminal.  One of the breakpoints (very likely the first) will be marked "catchpoint".  Delete that breakpoint (i.e. "delete 1").

If my guess is correct, the behavior should be unproblematic (well, at least as far as this isuse goes) afterwards.

**Comment by forky2** [comment]
Thanks. I'm out of the office today but I'll test tomorrow.

**Comment by forky2** [comment]
@d-millar you are correct:

```
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.2) 9.2
...
(gdb) info b
Num     Type           Disp Enb Address            What
1       catchpoint     keep y                      syscalls "mmap, mprotect, munmap, brk, mremap, msync, mincore, madvise, shmat, shmdt, mlock, munlock, mlockall, munlockall, remap_file_pages, mbind, set_me
mpolicy, get_mempolicy, migrate_pages, move_pages" 
        silent
        hooks-ghidra event-memory
        cont
(gdb) delete 1
(gdb) c
Continuing.
Hello, world!
[Inferior 1 (process 999036) exited normally]
(gdb)
```
