### ISSUE TITLE
debugger: Continuing from a breakpoint in GDB scripts fails

### ISSUE THREAD

**Issue by gteroy** [NationalSecurityAgency/ghidra#6678]
**Describe the bug**
Continue from a breakpoint in gdb script cause python hook on_stop fails with the following error. This may relates to #6666 

```
Breakpoint 3, 0x000055ea00d8414f in main ()
0xd8414f rdi=0xda867710
Traceback (most recent call last):
  File "/ghidra_11.2_DEV/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/hooks.py", line 167, in _func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ghidra_11.2_DEV/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/hooks.py", line 317, in on_stop
    state.record("Stopped")
  File "/ghidra_11.2_DEV/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/hooks.py", line 89, in record
    commands.put_frames()
  File "/ghidra_11.2_DEV/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/commands.py", line 1404, in put_frames
    f = newest_frame(gdb.selected_frame())
                     ^^^^^^^^^^^^^^^^^^^^
gdb.error: No frame is currently selected.
Python Exception <class 'gdb.error'>: No frame is currently selected.
```

**To Reproduce**
1. Create an x86_64 helloworld: 
```c
#include <stdio.h>

int main(int argc, char *argv[])
{
    while (1)
    {
        printf("Hello, world!\n"); // break and continue here
    }

    return 0;
}
```
3. Run Ghidra 11.2
4. Import helloworld to Ghidra project
5. Start a gdb debugger session with the default parameters
6. GDB breaks on _start()
7. Load gdb script with `source /path/to/gdbscript` in `GDB Terminal` as follows:
```gdb
b *0x55ea00d8414f
command
    printf "0x%x rdi=0x%x\n", $pc, $rdi
    c
end
```
8. Press F5 or enter `continue` into `GDB Terminal`
9. Exception as above is thrown

**Expected behavior**
Program should run and let the gdb script do prints in a loop with no exception.

**Environment (please complete the following information):**
 - OS: [Debian GNU/Linux 12 \n \l]
 - Java Version: [openjdk 21.0.3 2024-04-16]
 - Ghidra Version: [Ghidra build from master 93eed8011cb589b7bda96ef53445efd4ccc4ac91]
 - Gdb version: [GNU gdb (Debian 13.1-3) 13.1]

**Comment by d-millar** [comment]
@gteroy I have a handle on this, but the solution may be quite complicated.  Need to discuss the solution with the team to verify I'm not doing more damage than good with my current fix.  Just wanted to say thanks, in the meantime, for supplying the working example and all the details - helps immensely!
