### ISSUE TITLE
address not found in program memory

### ISSUE THREAD

**Issue by 3052** [NationalSecurityAgency/ghidra#6680]
I entered a DLL, but for a function argument I get the message:

> Address not found in program memory

> ![ghidra](https://github.com/NationalSecurityAgency/ghidra/assets/147215885/f82fc826-5b01-4fc0-aaed-18faf74777fc)

but if I load the same DLL in IDA Pro, it works:

> ![ida](https://github.com/NationalSecurityAgency/ghidra/assets/147215885/b3b34dd6-af36-41cb-8860-be925525cea5)

**Comment by ghizard** [comment]
Which version of Ghidra are you using?
What address does IDA Pro have for that second string?

**Comment by ryanmkurtz** [comment]
Can you please attach your binary?

**Comment by 3052** [comment]
I am at work - soon as I get home I will attach files and answer questions

**Comment by 3052** [comment]
> Which version of Ghidra are you using?

`ghidra_11.1.1_PUBLIC`

> What address does IDA Pro have for that second string?

```
.rdata:0000000180720650 _DIRECTLINK_PROVISIONING_BOOTSTRAP_URL__3QBGB text
"UTF-16LE", "https://prp.spserv.microsoft.com/PRProvisioning/Boo"
```

> Can you please attach your binary?

https://github.com/3052/play-ready/releases/download/v1.0.0/Windows.Media.Protection.PlayReady.zip

**Comment by ryanmkurtz** [comment]
Looks like we are saying that parameter is a 4-byte value instead of an 8-byte value.  I would suspect a PDB issue.

**Comment by ghizard** [comment]
Dug into PDB and sizeof(long) for AARCH64 win ABI, but false direction.  Then noticed stack issue.  Nearly certain AARCH64_win stack alignment needs to be changed from 4 to 8; initial inspection seems to verify this.
