### ISSUE TITLE
Unable to render the complete GUI

### ISSUE THREAD

**Issue by TensShinet** [NationalSecurityAgency/ghidra#669]
**Describe the bug**
I have downloaded the  ghidra and jdk11.**And I can't open the complete GUI**

like this:

https://ibb.co/ZmJXwQv

**To Reproduce**
+ download  ghidra_9.0.4_PUBLIC_20190516.zip
+ unzip  ghidra_9.0.4_PUBLIC_20190516.zip
+ install jdk11
+ ./ghidraRun

**Expected behavior**

open the complete GUI

**Environment**

+ OS: Ubuntu 18.04
+ java: java -version
```
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

```
+ Ghidra Version: ghidra_9.0.4

**Comment by ryanmkurtz** [comment]
In support/launch.properties, try changing `VMARGS=-Dsun.java2d.xrender=false` to `true`.

**Comment by TensShinet** [comment]
It works!!! Thanks !!!

**Comment by ryanmkurtz** [comment]
Sure thing!
