### ISSUE TITLE
Hash mismatch

### ISSUE THREAD

**Issue by danzek** [NationalSecurityAgency/ghidra#67]
The main Ghidra website shows the following SHA-256 hash for the zip file:

    3b65d29024b9decdbb1148b12fe87bcb7f3a6a56ff38475f5dc9dd1cfc7fd6b2  ghidra_9.0_PUBLIC_20190228.zip

However, the actual SHA256 sum is:

    e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  ghidra_9.0_PUBLIC_20190228.zip

Has the file download been compromised in some way, or is the hash just wrong?

**Comment by cwgreene** [comment]
I just downloaded the package and it yielded 3b65d29024b9decdbb1148b12fe87bcb7f3a6a56ff38475f5dc9dd1cfc7fd6b2. Can you put your version somewhere?

**Comment by jdillard** [comment]
I just downloaded it and got the same:

```
shasum -a 256 ghidra_9.0_PUBLIC_20190228.zip
3b65d29024b9decdbb1148b12fe87bcb7f3a6a56ff38475f5dc9dd1cfc7fd6b2  ghidra_9.0_PUBLIC_20190228.zip
```

**Comment by cwgreene** [comment]
Well that's exciting; hold onto your magic zip. :)

**Comment by ctubbsii** [comment]
The download matches the checksum on the website for me. Perhaps your copy got corrupted somehow. Have you tried downloading with a different browser?

**Comment by danzek** [comment]
I re-downloaded and got the right one, weird. Confirmed I cannot even unzip what was downloaded. Must've been a fluke/corrupt download.

**Comment by danzek** [comment]
@ctubbsii yeah I used a different browser (Safari instead of Firefox loaded with plugins that block a bunch of things). So I'd consider this closed. Was just a corrupt download, file size not even correct and was a corrupt zip file.

**Comment by danzek** [comment]
I chalk this up to a PICNIC error: **p**roblem **i**n chair, **n**ot **i**n **c**omputer 😛
