### ISSUE TITLE
BSIM "Database already in use by another process" error when running in headless mode 

### ISSUE THREAD

**Issue by je0xffrey** [NationalSecurityAgency/ghidra#6703]
**Describe the bug**
Any attempt to query an H2 database from a script in headless mode returns the error `Database already in use by another process` if that H2 database has been queried before by another Ghidra client that is still running. The Ghidra client must be fully terminated in order to free up this database. After looking at the H2 [reference](http://www.h2database.com/html/advanced.html#file_locking_protocols) the problem could be caused by the client connection not being closed properly after a query finishes. The reference also mentions that if the process that opens the database terminates, the lock file will get automatically deleted, which explains why a full shutdown fixes the issue.

**To Reproduce**
1. Perform any sort of local BSIM query from the Ghidra client with an H2 database. 
3. Close out of all BSIM related output windows in the program.
4. Now attempt to perform a BSIM query from a script running in headless mode with this same database.
5. The error `Database already in use by another process` will appear. 

**Expected behavior**
After performing a query from a local client, the Connection should be terminated correctly so that the database lock is released without having to restart the client. Calling `database.close()` should also properly release this lock when running from a script`s context. 

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java Version: 17.0
 - Ghidra Version: 11.1.1
 - Ghidra Origin: official GitHub distro

**Comment by ghidra1** [comment]
Ghidra uses a connection pool for each database connection.  The purpose of the pool is to avoid repeated opening and closing of connections.  This is done for performance reasons and is particularly beneficial with H2 file database.  Potential options to address this are:
1. Provide GUI control to dispose the connection pool if not currently in-use.  This could be facilitate via the connection panel.
2. Enable use of H2 "mixed-mode" which would turn the Ghidra GUI client into a multi-access H2 server for a specific H2 database files.  We have not yet tried this but it seems like it could be used for certain use cases. This mode wuold certanily have some limitations and would not address purely headless parellel multi-processing without GUI use. 
@je0xffrey Curious what your thoughts are on the two partial solutions.

**Comment by je0xffrey** [comment]
Thanks for the response. I looked into the H2 "mixed-mode" and that approach looks like it could resolve the issue. I'm personally more in favor of this because it would fix the bug and not require any user interaction with the client. For my use case, I'm not really concerned with the additional processing time added by the second connection in mixed-mode, I just want to ensure that I can utilize both BSIM manually in my client and my headless scripts interchangeably (without having to restart my client).

**Comment by ghidra1** [comment]
The mixed-mode still has the potential issue of  the "server" terminating while in-use by one or more headless clients.  Unclear how to midigate this and the problems that it could cause.  There is also the issue of limited number of connections that the mixed-mode server would permit which could also lead to trouble if parallel headless is attempted (i.e., too many open connections)

**Comment by je0xffrey** [comment]
Just brainstorming now but would the potential issues be resolved if there was an option in the connection panel to swap connection modes between embedded (the default) and mixed-mode with the main Ghidra client acting as the first server connection? That way we will avoid the race condition caused by parallel headless runners exiting early. Also is there a max limit for open connections with mixed-mode? If you think discarding the connection pool is an easier fix, I'm open to it as well.

**Comment by ghidra1** [comment]
The connection pool is important based upon all the different code which needs a connection - particularly in the GUI case.  Until I attempt to integrate it's not yet clear how best to manage the mixed-mode use.  I will also have to experiment with all the potential multi-process failure cases.

**Comment by ghidra1** [comment]
We currently have too many complicating factors to allow for the use of H2 mixed-mode, including:
- our disabling auto-commit
- our in-memory caching of database content
I have made another change (currently in-review) to the BSim Server Manager dialog which improves database status and provide a connect/disconnect action.  An idle H2 connection could can know be disconnected without its removal allowing for a single headless analyzer to use the same database while the GUI remains active.

**Comment by je0xffrey** [comment]
Gotcha thanks for looking into this.
