### ISSUE TITLE
Debugger failed to open gdb on Windows 11

### ISSUE THREAD

**Issue by ktfth** [NationalSecurityAgency/ghidra#6706]
**Describe the bug**
Failure to analyze a simple exe file.

**To Reproduce**
1. Open exe on debugger
2. Use the button to start debugging
3. Choose any option to use gdb
4. The result is the screen pasted here

**Expected behavior**
Open dgb on ghidra

**Screenshots**
![investigation](https://github.com/NationalSecurityAgency/ghidra/assets/44123854/362821fe-28bb-4c55-b2c8-e8389ffb10a4)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: ?
 - Ghidra Version: ?
 - Ghidra Origin: official GitHub distro

**Comment by d-millar** [comment]
@ktfth What parameters did you use in the dialog box?

**Comment by d-millar** [comment]
Perhaps more specifically, what version of gdb are you attempting to run?   Is it compiled for Windows proper or the WSL?  And is it in the system PATH or did you specify a full path?

**Comment by ktfth** [comment]
![image](https://github.com/NationalSecurityAgency/ghidra/assets/44123854/dc78c7b5-2810-450a-b58e-0ca104186996)

ghidra_11.1.1_PUBLIC

Running directly on Windows 11, without WSL.

I specify the full path.

**Comment by d-millar** [comment]
Well, couple of issue here.  The Dev-Cpp version of gdb uses a fairly archaic version of Python (3.8).  I'm not sure how well (if at all) Ghidra will work with that version.  Also, am guessing the console message at startup indicated you haven't installed psutil or protobuf==3.20.3.  It's not obvious to me how to do installs in Dev-Cpp's version of python.  (I haven't ever been able to run "python -m pip install ..." from their version.)   Can you verify there are related errors in the terminal?  Also, how do you feel about re-compiling their gdb.exe using a more current Python?

**Comment by ktfth** [comment]
I tried with Mingw and failed too, but I can run again with a different and custom installation as suggested. Give some time to get on my machine.

**Comment by ktfth** [comment]
@d-millar Here the stack trace of the failed procedure:

GetLastError() returned 193
com.sun.jna.LastErrorException: GetLastError() returned 193
	at ghidra.pty.windows.ConPtyChild.session(ConPtyChild.java:108)
	at ghidra.pty.windows.ConPtyChild.session(ConPtyChild.java:36)
	at ghidra.pty.PtyChild.session(PtyChild.java:68)
	at ghidra.app.plugin.core.debug.gui.tracermi.launcher.AbstractTraceRmiLaunchOffer.runInTerminal(AbstractTraceRmiLaunchOffer.java:478)
	at ghidra.app.plugin.core.debug.gui.tracermi.launcher.AbstractScriptTraceRmiLaunchOffer.launchBackEnd(AbstractScriptTraceRmiLaunchOffer.java:119)
	at ghidra.app.plugin.core.debug.gui.tracermi.launcher.AbstractTraceRmiLaunchOffer.launchProgram(AbstractTraceRmiLaunchOffer.java:627)
	at ghidra.app.plugin.core.debug.gui.tracermi.launcher.TraceRmiLauncherServicePlugin$ConfigureAndLaunchTask.run(TraceRmiLauncherServicePlugin.java:123)
	at ghidra.app.services.ProgressService.lambda$execute$0(ProgressService.java:123)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

---------------------------------------------------
Build Date: 2024-Jun-14 1025 EDT
Ghidra Version: 11.1.1
Java Home: C:\Program Files\Microsoft\jdk-21.0.3.9-hotspot
JVM Version: Microsoft 21.0.3
OS: Windows 11 10.0 amd64
Workstation: GARDEN

**Comment by d-millar** [comment]
Thanks for the stack trace - unfortunately, that's one of those stack traces that isn't terribly helpful, i.e. it's telling you some executable or some library is missing, corrupt, or misbehaving in an unspecified way.   Are there, by any chance, any other errors in the DebugConsole and/or, if you run using support/ghidraDebug vs. ghidraRun, does anything precede that stack trace in the terminal?  Am assuming your HelloWorld.c looks something like "#include<stdio.h>  inr main() {printf("HelloWorld\n");} - yell if it's anything more complicated - and was compiled with whatever version of gcc matches your gdb.  Can you send us the exact version of gdb you have installed and, if you built it from scratch, the version of Python it was compiled with.  I'd love to be able to reproduce the error, but so far haven't had much luck.

**Comment by ktfth** [comment]
Oh, nice!

GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.

Python 3.12.2

**Comment by ktfth** [comment]
And yes, my hello world, have this kind of settled code.

**Comment by d-millar** [comment]
OK, that helps - let me take another shot at debugging this.

**Comment by d-millar** [comment]
Hmm, OK, maybe a stupid question, but I have to ask:  when you say you're using Python 3.12.2, is that the version of Python you have installed in Windows or the version compiled into gdb?  I.e. if you run gdb, enter "pi" to get into the python shell, then issue the commands "import sys" and "sys.version", is "sys.version" reporting 3.12.2?   I ask because that seems like very odd combination, i.e. a very very old versionof gdb running an almost current version of Python.

**Comment by ktfth** [comment]
Sorry about that, maybe this is the problem, the gdb version just popped out this to me:

Python scripting is not supported in this copy of GDB.

**Comment by d-millar** [comment]
No worries - that's definitely a problem (if not the problem).  If possible, grab a copy of gdb 13 or 14 compiled with Python versions >= 3.9.  We haven't tested against gdb 15 (and there are always issue with new versions).

**Comment by ktfth** [comment]
Updated the ghidra to latest version, worked with msys64 gdb installed by pacman.

Thank you so much @d-millar!

**Comment by d-millar** [comment]
Excellent - keep us posted.  Am sure you'll hit other bugs down the line!  :)
