### ISSUE TITLE
Mac doesn't show loop arrows next to binary M1 Mac

### ISSUE THREAD

**Issue by wulfcare** [NationalSecurityAgency/ghidra#6707]
**Describe the bug**
M1 mac laptop is unable to see loop arrows next to binary.

**Expected behavior**
Should be able to see loop / branch jumps on left side of binary.

**Screenshots**
First image is how it should look. 
Second image is on an m1 mac where the control flow arrows wont display.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/24600608/a0c6e8ad-887f-4fe4-9751-9ecc74b88b7b)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/24600608/4189ebc9-c581-4086-981d-364d4a7cff6d)

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: macOS 14.5 Sonoma
 
 - Java Version: java 22.0.1 2024-04-16, Java(TM) SE Runtime Environment (build 22.0.1+8-16), Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
 
 - Ghidra Version: 11.1.1
 - 
 - Ghidra Origin: Github 

**Additional context**

**Comment by ryanmkurtz** [comment]
What happens if you grab that left panel (where the 3 dots are) and drag it to the right?

**Comment by wulfcare** [comment]
> What happens if you grab that left panel (where the 3 dots are) and drag it to the right?

That worked perfectly, thank your Ryan!
