### ISSUE TITLE
Build failure with Gradle 8.9

### ISSUE THREAD

**Issue by find0x90** [NationalSecurityAgency/ghidra#6724]
**Describe the bug**
Seeing the following error when attempting to build Ghidra:

```
> Configure project :Debugger-agent-dbgeng
WARNING: dbgmodel.tlb omitted from ghidradbg python package

Found existing files in the project directory: '<redacted>/ghidra'.
Directory will be modified and existing files may be overwritten.  Continue? (default: no) [yes, no]
```

I'm not sure how to continue past this. Trying 'yes' and 'no' seem to cause issues as well as the `--overwrite` option.

**To Reproduce**
Attempt to build the latest stable release with Gradle 8.9

**Expected behavior**
Successful build.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: macOS 15.0
 - Java Version: 21
 - Ghidra Version: stable branch 75f08aa0b4ad263343c7c4d43b3c42f536d7864f
 - Ghidra Origin: locally built

**Additional context**
https://docs.gradle.org/current/release-notes.html

Might be caused by `Build init does not override existing build files by default` on the above page.

**Comment by ryanmkurtz** [comment]
Is this when you ran `gradle -I gradle/support/fetchDependencies.gradle init`?

If so, try replacing that `init` at the end with `help`.  Gradle seems to need some task name there, and we've always used `init` because it was basically a no-op.  But, now it seems to actually do something.  So, try:

```
gradle -I gradle/support/fetchDependencies.gradle help
```

**Comment by ryanmkurtz** [comment]
Not having a task name at the end also works fine.  I think we suggested using `init` because it produced the least spam at the end.

```
gradle -I gradle/support/fetchDependencies.gradle
````

**Comment by find0x90** [comment]
That worked, thanks! Using `gradle -I gradle/support/fetchDependencies.gradle` with no task name produced more text output, like you said, but everything built successfully.
