### ISSUE TITLE
How can I disable switch/case analysis?

### ISSUE THREAD

**Issue by mh-** [NationalSecurityAgency/ghidra#673]
I'm trying to analyse PIC16F code using the current development version of Ghidra from git, and there are a some places where Ghidra comes up with bogus switch/case statements that don't really seem to exist, and that don't come up with correct code either. Most case statements end in halt_baddata();

I want to disable this and therefore I un-checked "Decompiler Switch Analysis" and "PIC Switch Tables" in Analysis Options; but Ghidra keeps doing this. 
Is there another place where I could tell Ghidra to not try to find switch/case statements?

**Comment by emteere** [comment]
The decompiler will always try to recover switch statements, since its analysis is dynamic.  Turning off those options only stops the laying down of the switch references and disassembling the code for the switch cases.  If the references are being layed down on the jump, and the case code disassembled, then there is a bug.

Can you post a sample? (bytes, and decompilation) Are they actually switch statements that are not being figured out correctly?
It is also possible that the JUMP is really a return or a call.  You can modify the flowtype of the jump to stop the analysis.  In your case if you turn the JUMP into a CALL_RETURN, then the decompiler will stop the switch.

The incorrect recovery is an indication that there is a problem with the flow, a global variable that gives context is needed, or possibly an instruction is not implemented right, or something else entirely...?

**Comment by mh-** [comment]
Thank you for the explanation!

You are right, there were problems with the flow (outside of the area I was looking at), they were caused by branching to incorrect addresses, because the PIC16F's PCLATH register wasn't handled correctly in higher code memory segments by my interim version of https://github.com/NationalSecurityAgency/ghidra/pull/667 - when I fixed that, most of the erroneous switch statements went away.

There's one left that keeps puzzling me:
```
CODE:1497 47 06           XORWF      DAT_DATA_0047,w                                  = ??
CODE:1498 48 04           IORWF      DAT_DATA_0048,w                                  = ??
CODE:1499 03 1d           BTFSS      STATUS,#0x2
CODE:149a 9d 2c           GOTO       offset LAB_CODE_149d
CODE:149b 50 01           MOVLB      #0x10
CODE:149c 9e 12           BCF        offset NVMCON1,#0x5                              = ??
                             LAB_CODE_149d                                   XREF[1]:     CODE:149a(j)  
CODE:149d 34 30           MOVLW      #0x34
```

decompiles to

```
        if ((DAT_DATA_004c ^ DAT_DATA_0047 | DAT_DATA_0048) == 0) {
          bVar9 = read_sfr_1(NVMCON1);
          write_sfr_1(NVMCON1,bVar9 & 0xdf);
        }
        else {
          switch((ushort)bVar6 & 0x78) {
          case 0:
            goto code_r0x049d;
          case 0x20:
                    /* WARNING: Bad instruction - Truncating control flow here */
            halt_baddata();
          case 0x30:
                    /* WARNING: Bad instruction - Truncating control flow here */
            halt_baddata();
          case 0x40:
          (...)
```

And that apparently happens because the decompiler thinks that the `CODE:149a 9d 2c           GOTO       offset LAB_CODE_149d` instruction goes to 049d instead of 149d. When I move the cursor though the Decompile window, the Listing window suddenly goes to 049d.
The disassembler got it right (149d), and when I do "Set Register Values..." for address 149a, the PCLATH register is already shown as 14hex - manually trying to set it again doesn't change anything.

Any idea how I could correct this behaviour?

**Comment by emteere** [comment]
Is the decompile window grey?  The decompiler will only pick up the PCLATH setting at the beginning of the function.

Can you post the entire functions bytes?

**Comment by mh-** [comment]
The decompile window is white.
But the PCLATH handling seems to be a bit strange indeed.
The function starts at 1458:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/6257627/59406016-e0fbcb00-8dac-11e9-8d26-dc3519b06674.png">
but there is no entry in the Register Manager for PCLATH for this address:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/6257627/59406050-08eb2e80-8dad-11e9-8ab0-d648fe4cb35f.png">

I can set PCLATH to 0x14 there, this is the pre-recommended value in the Set Register Values... dialog:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/6257627/59406137-4e0f6080-8dad-11e9-9d1a-6050ae431b5b.png">

Now the listing shows "assume PCLATH = 0x14" at the start of the function:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/6257627/59406190-89119400-8dad-11e9-9565-e6f2294bac51.png">

It doesn't change the behaviour at 149a, though:
The compiler still believes that this GOTO goes to r0x**0**49d, instead of **1**49d:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/6257627/59406414-6fbd1780-8dae-11e9-9b6c-71b0b2af19a7.png">

Attached please find an exported version of the function, slightly modified, and when I import this, the decompile window is indeed grey. But the behaviour at 149a is the same. 
[jump-problem-at-149a-2.hex.zip](https://github.com/NationalSecurityAgency/ghidra/files/3284402/jump-problem-at-149a-2.hex.zip)
It's PIC16F153xx code, I use https://github.com/NationalSecurityAgency/ghidra/pull/667 for this.

Thanks a lot for your help!

**Comment by mh-** [comment]
Some debugging showed that the decompiler will try to find jumptables (`jumpbasic` style) for switch/case statements at every PIC `GOTO` instruction; that's because `GOTO` is declared as a `BRANCHIND` instruction: `goto [absAddr11];` - cf. https://github.com/NationalSecurityAgency/ghidra/blob/master/GhidraDocs/languages/html/sleigh_ref.html#branchref.htmltable - the same applies to `CALL`.

It makes sense that the decompiler expects a compiler to use indirect branching for switch/case statements, but `GOTO` and `CALL` aren't really such instructions, are they? 

However, I haven't been able to successfully modify the PIC .sinc files to get rid of the indirect addressing type, somehow the PCLATH handling became all messed up :(
