### ISSUE TITLE
NPE: Cannot invoke "java.net.URL.toExternalForm()" because "url" is null

### ISSUE THREAD

**Issue by itsallmathematics** [NationalSecurityAgency/ghidra#6734]
**Describe the bug**
I have Eclipse IDE For Java Developers v4.32.0 linked with Ghidra using GhidraDev that came with the latest release of Ghidra as of this post. I am working on a Java Ghidra Script and when I right click -> Debug As -> Ghidra, while the loading splash screen is up, the Eclipse debugger breaks on line 120 of GhidraHelpService.class `String asString = url.toExternalForm();`. Once I continue past that break, the follow exception is displayed in the console:

```
NullPointerException - Cannot invoke "java.net.URL.toExternalForm()" because "url" is null (SwingExceptionHandler) java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "url" is null
	at ghidra.base.help.GhidraHelpService.mapHelpToModule(GhidraHelpService.java:120)
	at ghidra.base.help.GhidraHelpService.findHelpSetsByModule(GhidraHelpService.java:104)
	at ghidra.base.help.GhidraHelpService.loadHelpSets(GhidraHelpService.java:85)
	at ghidra.base.help.GhidraHelpService.<init>(GhidraHelpService.java:60)
	at ghidra.base.help.GhidraHelpService.install(GhidraHelpService.java:51)
	at ghidra.GhidraRun.lambda$launch$1(GhidraRun.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
Aside from the obvious, I don't know the cause of this or how to fix it. I did read #5327 and #3374 which seem related, but the circumstances are different. I am not creating an extension, I am working on a GhidraScript and additionally, I did not download the sources, but I downloaded/installed the release. Furthermore, I have not been able to locate any file named `base_map.xml` anywhere in the ghidra directory. Last, I saw some comments about "deleting the build directory", and am unsure what that would be in this case, I didn't knowingly create a build directory and haven't seen one in eclipse-workspace/GhidraScripts/bin for example.
**To Reproduce**
1. Open Eclipse IDE
2. Create a new GhidraScript or open an existing one
3. Right click in the script, click Debug As -> Ghidra

**Expected behavior**
Ghidra starts up normally and I debug the script.

**Environment (please complete the following information):**
 - OS: Fedora 38
 - Java Version: 21.0.3 and 17.0.11
 - Ghidra Version: 11.1.2
 - Ghidra Origin: GitHub distro
**Additional context**
This only occurs when debugging with Eclipse, not when running Ghidra normally via ./ghidraRun.

**Comment by dragonmacher** [comment]
The comments relating to the `build` directory relate to having run a `gradle` command(s) in your installation.   If you have not run any gradle commands, then I don't think this will apply to you.   *Have you run any gradle commands in your installation?*

****

`base_map.xml` is a help artifact that gets built for the distribution (or when you build help via gradle).   The installation you are using should contain `base_map.xml` inside of the `Base.jar` located in:
```
{ghidra install dir}/Ghidra/Features/Base/lib
```
If you are not doing any building from the command-line using gradle, then you do not need to worry about this file, as it will be in the distribution.    


****

I believe there had been a change related to the eclipse `GhidraDev` plugin that fixed the issue for #3374.    

@ryanmkurtz may be able to confirm the correct usage of the `GhidraDev` plugin.

**Comment by itsallmathematics** [comment]
> _Have you run any gradle commands in your installation?_

No.

> `base_map.xml` is a help artifact that gets built for the distribution (or when you build help via gradle). The installation you are using should contain `base_map.xml` inside of the `Base.jar` located in:
> 
> ```
> {ghidra install dir}/Ghidra/Features/Base/lib
> ```
> 
> If you are not doing any building from the command-line using gradle, then you do not need to worry about this file, as it will be in the distribution.
Ok, I'm sure it's there.

**Comment by dragonmacher** [comment]
If you are willing to try to debug the issue, then I can tell you where to put a breakpoint and what to check.   Place a breakpoint inside of:

`resources.ResourceManager.java` at line 81

The method should look like this:

```
	public static URL getResource(String filename) {
		URL url = classLoader.getResource(filename);
		if (url != null) {
			return url;
		}

		url = getResource(getTestSearchPaths(), filename);
		return url;
	}
```

Line 81 should be this:

`url = getResource(getTestSearchPaths(), filename);`

When you try to run Ghidra again, hitting this breakpoint should mean there is a resource being requested that cannot be found.   I'd like to know the value of `filename` at this point.

Presumably there is an entry(ies) on your classpath that should not be there.  Knowing the value of `filename` should help.

**Comment by itsallmathematics** [comment]
@dragonmacher Sure! The `filename` is `help/Base_HelpSet_en_US.hs`.

**Comment by dragonmacher** [comment]
I'm seeing that entry too.   This method is called from multiple places, some of which handle the `null` case correctly.

For my setup, I'm seeing the following list of files that are not queried from the problematic code.  These files do not exist and the `null` value returned is handled:
```
 help/Base_HelpSet_en_US.hs
 help/Base_HelpSet_en.hs
```


This list is a sample of files that should all have a non-null return value from `getResources()`:
```
 help/Base_HelpSet.hs
 help/Dummy_HelpSet.hs
 help/Jython_HelpSet.hs
 help/FileFormats_HelpSet.hs
 help/VersionTrackingBSim_HelpSet.hs
 help/ProgramGraph_HelpSet.hs
 help/ProgramDiff_HelpSet.hs
 help/Base_HelpSet.hs
 help/Docking_HelpSet.hs
 help/FunctionGraph_HelpSet.hs
 help/GraphServices_HelpSet.hs
 help/GraphFunctionCalls_HelpSet.hs
 help/Decompiler_HelpSet.hs
 help/VersionTracking_HelpSet.hs
 help/sample_HelpSet.hs
 help/PDB_HelpSet.hs
 help/Debugger_HelpSet.hs
 help/ByteViewer_HelpSet.hs
```

If you are willing, I'd like to see what filenames are returning `null` that are not part of the first group that I listed.  You should be able to keep pressing `play` every time your breakpoint is hit, noting the filename that you see each time.

I'm curious to know a handful of the filenames that are returning null for you.

**Comment by itsallmathematics** [comment]
@dragonmacher I'll go do this in a few mins; btw do you know a temporary workaround for me to get Ghidra fired up for debugging? I was thinking maybe I could replace some value somewhere to get it to continue, but am unsure as I'm pretty new to Ghidra development and also Java isn't exactly my forte.

**Comment by dragonmacher** [comment]
The `SampleTablePlugin` is an extension that we ship in a build.   Do you know if you installed that extension?  

You can try removing it from the installation.  With Ghidra closed, 

- Open a filesystem browser and find `{Ghidra install dir}/Extensions/Ghidra`
- There should be a file named `ghidra_{version}_SampleTablePlugin.zip`
- Move that file out of the installation (or simply delete it)

Restart Ghidra to see if that fixes the issue.

**Comment by itsallmathematics** [comment]
@dragonmacher Yes, I had just recently enabled that extension. I simply disabled it in the File -> Install Extensions menu of the Project window and I was able to enter Ghidra in debug mode. Thank you! :)

**Comment by dragonmacher** [comment]
You're welcome!   I will investigate to see if I can reproduce that myself.
