### ISSUE TITLE
Decompile char-array initialisation

### ISSUE THREAD

**Issue by shapaz** [NationalSecurityAgency/ghidra#6736]
**Describe the bug**
When the code initialises a char array from a string literal, e.g.:
```
  char s[] = "This is a string";
```
ghidra misinterprets the array as several integer variables, and decompiles the code into initialising them with nonsensical values, e.g.:
```
  undefined8 uStack_28;
  undefined8 uStack_20;
  undefined local_18;
  
  uStack_28 = 0x2073692073696854;
  uStack_20 = 0x676e697274732061;
  local_18 = 0;
```
Even after retyping the first variable as correct array type (e.g. "char[17]") the array initialisation is still cumbersome, e.g.:
```
  char uStack_28 [17];
  
  uStack_28[0] = 'T';
  uStack_28[1] = 'h';
  uStack_28[2] = 'i';
  uStack_28[3] = 's';
  uStack_28[4] = ' ';
  uStack_28[5] = 'i';
  uStack_28[6] = 's';
  uStack_28[7] = ' ';
  uStack_28[8] = 'a';
  uStack_28[9] = ' ';
  uStack_28[10] = 's';
  uStack_28[0xb] = 't';
  uStack_28[0xc] = 'r';
  uStack_28[0xd] = 'i';
  uStack_28[0xe] = 'n';
  uStack_28[0xf] = 'g';
  uStack_28[0x10] = '\0';
```

**To Reproduce**
1. Create a binary:
```
echo '#include <stdio.h>
int main()
{
    char s[] = "This is a string";
    puts(s);
    return 0;
}
' > str_init.c && gcc str_init.c
```
2. Auto-analyse with ghidra then see decompilation of `main`.

**Expected behavior**
Array initialisation from string literal, e.g.:
```
  char uStack_28 [17] = "This is a string";
```
IDA's decompiling is also plausible:
```
  char s[32]; // [rsp+0h] [rbp-20h] BYREF

  strcpy(s, "This is a string");
```

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: 17.0.11
 - Ghidra Version: 11.1.1
 - Ghidra Origin: snap repo

**Comment by shapaz** [comment]
Might be a duplicate of issue #4461.

**Comment by ryanmkurtz** [comment]
Duplicate of #6431.  This is fixed in the `master` branch if you wanted to do a build and test it.
