### ISSUE TITLE
Demangler GNU> Apply failure

### ISSUE THREAD

**Issue by commonuserlol** [NationalSecurityAgency/ghidra#6740]
**Describe the bug**
Demangler unable to process some symbols in Code Browser

**To Reproduce**
You'll need a binary with applied metadata, I can send .gar if you need
1. Go to 'Code Browser'
2. Click on 'Analysis -> One Shot -> Demangler GNU' (this also present in "full" analysis)
3. See error

**Expected behavior**
Demangled names like `bool MethodInfo::System::Array::InternalArray__ICollection_Contains<Photon::Deterministic::DeterministicNetwork::NetworkSend>(Photon::Deterministic::DeterministicNetwork::NetworkSend)`

**Attachments**
```
INFO  (AutoAnalysisManager) Analysis Log Messages
There were too many messages to display.
29887 messages have been truncated.

Demangler GNU> Apply failure (DemangledFunction: IllegalArgumentException: Defined data at address: 027611e8)
	_ZN10MethodInfo6System7Runtime16CompilerServices13CallSite_1_T_3__cIN6System7Runtime16CompilerServices13CallSite_1_T_1TEE36_CreateCustomNoMatchDelegate_b__18_0EN6System10Reflection13ParameterInfoE
Demangler GNU> Apply failure (DemangledFunction: IllegalArgumentException: Defined data at address: 03506840)
	_ZN10MethodInfo6System9Threading5Tasks8Parallel21__c__DisplayClass17_0IN6System6ObjectEE15_ForWorker_b__1Ev

... a lot of these messages

Demangler GNU> Apply failure (DemangledFunction: IllegalArgumentException: Defined data at address: 02fc4808)
	_ZN10MethodInfo6System12ArraySegmentIhE45System_Collections_Generic_ICollection_T__AddEh
Demangler GNU> Apply failure (DemangledFunction: IllegalArgumentException: Defined data at address: 02fc4828)
	_ZN10MethodInfo6System11Collections7Generic12HashSet_1_T_10EnumeratorIN6System4Linq11Expressions11Interpreter14LabelScopeInfoEE11get_CurrentEv
  
INFO  (AutoAnalysisManager) -----------------------------------------------------
    Demangler GNU - One Time                  16.216 secs
-----------------------------------------------------
     Total Time   16 secs
-----------------------------------------------------
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 22.0.2
 - Ghidra Version: 11.1.2
 - Ghidra Origin: GitHub

**Additional context**
both `c++filt` from binutils and ghidra's demangler in from CLI have correct result, perhaps Code Browser can't apply it?

**Comment by dragonmacher** [comment]
The messages indicate that the demangler found a function(s) and could not apply the function at the address of the mangled symbol since there is already data applied at that address.   It appears as thought something, either an auto-analyzer, user script or the user directly, has applied data at these addresses where there are mangled function names.   If no data had been applied, then the demangler should have applied the demangled symbol name and created a function at each of these locations.

**Comment by commonuserlol** [comment]
Well, mangled names were already applied by script. Is there workaround to force demangler overwrite user-defined mangled names with demangled?

**Comment by dragonmacher** [comment]
If the label and data at the address is cleared, then re-running the demangler analyzer should work as expected.

**Comment by commonuserlol** [comment]
Label cannot be removed since it's not kind of debug symbols - it's metadata applied (and generated) by script :(

**Comment by dragonmacher** [comment]
I was a bit unclear earlier.   If there is already a function symbol applied an address and it has a function signature with a `SymbolType` value of `USER_DEFINED`, then that function will not be updated.

In you case, it appears as though you do not have a function at the failing addresses, but you have data instead.   If that is true, then no function is created, nor is the demangled label applied at that address.

**Comment by commonuserlol** [comment]
Yeah it's not a function, it's a data with mangled label. Can demangler be forced to update label?

**Comment by dragonmacher** [comment]
The demangler thinks it is a function.    The current system will not apply the label in this case.

You should be able to write a script that will demangle the symbol and then add the label.  We have examples of scripts that show how to use the demangler.  It should be fairly simple to write.

**Comment by commonuserlol** [comment]
Ahh alright, I'm pretty sure that demangler example somewhere in ghidra. Thanks
