### ISSUE TITLE
Issue with SHA256 Hash Matching

### ISSUE THREAD

**Issue by ghumphr** [NationalSecurityAgency/ghidra#6752]
**Describe the bug**
The SHA256 hash for yajsw-stable-13.09.zip does not match

**To Reproduce**
Execute this command on ubuntu-devel: `wget https://github.com/NationalSecurityAgency/ghidra/archive/refs/heads/master.zip && unzip master.zip && cd ghidra-master && gradle -I gradle/support/fetchDependencies.gradle`

**Expected behavior**
The SHA256 hashes for the downloaded dependencies should match.

**Screenshots**
![image](https://github.com/user-attachments/assets/d508029f-c131-4f73-8a16-dd467cf092fc)

**Environment (please complete the following information):**
 - OS: Linux b70e2492694b 5.15.153.1-microsoft-standard-WSL2 # 1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 - Java Version: openjdk 21.0.4-ea 2024-07-16
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official GitHub distro

**Additional context**
I'm uncertain about whether this is a serious issue, but since it is potentially very serious, I thought I should ask.

**Comment by ryanmkurtz** [comment]
I just tried the `fetchDependencies.gradle` script and I am unable to reproduce this.  So, there is nothing inherently wrong with our code, the expected hash, or the URL.  You will likely need to do some trouble shooting on your end, since the problem seems specific to your connection.

**Comment by ghumphr** [comment]
That's interesting. This was a persistent issue yesterday, affecting all of the SourceForge dependencies. I performed manual downloads, and the hashes matched.

The script appears to be working as intended today. I'm going to chalk this up as some kind of transient issue affecting SourceForge.
