### ISSUE TITLE
Split Block show incorrect value for Block Length

### ISSUE THREAD

**Issue by mediotex** [NationalSecurityAgency/ghidra#6756]
Ghidra, in "Memory Map" > "Split a block", show incorrect value for Block Length:
when we need to split a RAM block into two smaller memory blocks, and enter an **End address** for the first block (block to split), Ghidra show incorrect value for Block Length: `0x79a4d1`, instead of `0x79a4d0`. This changes values of the second part of the block (.data). 
Initial data:
```
.text start: 0x80004000
.text end: 0x8079e4d0
.text length: 0x79a4d0
.data start: 0x8079e4d4
.data end: 0x8093e220
.data length: 0x19fd4c
```
![ram](https://github.com/user-attachments/assets/afd990a7-f691-4f37-a8fb-a8ea2a624db7)

**Comment by ryanmkurtz** [comment]
A block length of `0x79a4d1` looks right to me.  Start and End Address are inclusive.  For example, if Start Address and End Address were both `0x0`, The block length would be `0x1`.  Unless i'm missing something...which seems to be happening more and more lately.

**Comment by mediotex** [comment]
The remaining values (for New Block) Ghidra calculates automatically based on End Address of RAM block?
