### ISSUE TITLE
[SVD] Support for    <peripheral derivedFrom="OTHER">

### ISSUE THREAD

**Issue by zdanek** [NationalSecurityAgency/ghidra#6766]
I found that Ghidra does not support "inheritance" from fully defined peripherals.
For example I found nrf51 SVD that fully defines TIMER0 and then TIMER1 and TIMER2 inheriting from TIMER0 and adding only differences. For example (simplified, but taken from SVD)

```
<peripheral>
      <name>TIMER0</name>
      <version>522</version>
      <description>Timer 0.</description>
      <baseAddress>0x40008000</baseAddress>
      <groupName>TIMER</groupName>
      <size>32</size>
      <access>read-write</access>
      <headerStructName>TIMER</headerStructName>


      <addressBlock>
        <offset>0</offset>
        <size>0x1000</size>
        <usage>registers</usage>
      </addressBlock>

<!-- and so on... ->
</peripheral>

 <peripheral derivedFrom="TIMER0">
      <name>TIMER1</name>
      <version>522</version>
      <description>Timer 1.</description>
      <baseAddress>0x40009000</baseAddress>
      <access>read-write</access>
      <interrupt>
        <name>TIMER1</name>
        <value>9</value>
      </interrupt>
    </peripheral>

    <peripheral derivedFrom="TIMER0">
      <name>TIMER2</name>
      <version>522</version>
      <description>Timer 2.</description>
      <baseAddress>0x4000A000</baseAddress>
      <access>read-write</access>
      <interrupt>
        <name>TIMER2</name>
        <value>10</value>
      </interrupt>
    </peripheral>

```

Are there any plans to implement support for _derivedFrom_?

**Comment by emteere** [comment]
Are you refering to the [SVD-Loader-Ghidra](https://github.com/leveldown-security/SVD-Loader-Ghidra) project?

If so, you would need to request a change with the above github project.

**Comment by zdanek** [comment]
@emteere not sure, since SVD-Loader-Ghidra is a script.
I've been using _File->Load SVD File..._ 
Is it a shortcut to a script? My intuition whispers that is not thus I created an issue / feature request :)

**Comment by antoniovazquezblanco** [comment]
I think you are using an extension I've made...
https://github.com/antoniovazquezblanco/GhidraSVD

:D

**Comment by zdanek** [comment]
> I think you are using an extension I've made... https://github.com/antoniovazquezblanco/GhidraSVD
> 
> :D

Nice to meet you :) Good extension.
Does it integrated with Ghidra in such way that this has it's own menu entry? 
Shall I post there a reature request regarding that __derivedFrom__ SVD attribute?

**Comment by antoniovazquezblanco** [comment]
> Nice to meet you :) Good extension.

❤️ 

>  Does it integrated with Ghidra in such way that this has it's own menu entry?

Yes

>  Shall I post there a reature request regarding that derivedFrom SVD attribute?

I think so. This issue here should be closed also in my opinion.

Thanks
