### ISSUE TITLE
Can't open gdt for editing

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#6768]
**Describe the bug**
Attempting to open a gdt file archive I have created does nothing.

**To Reproduce**
1. Go to the archive in the datatype manager
2. Right click on it
3. Select "Open For Editing"
4. See nothing happen
5. See "{date} {time} DEBUG (PackedDatabaseCache) Using cached packed database: {path}" added to the log.
6. Go back to step 1 and repeat forever

**Expected behavior**
The archive should be opened for editing.

**Attachments**
[libjvm.gdt.zip](https://github.com/user-attachments/files/16400660/libjvm.gdt.zip)

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22631.3880]
 - Java Version: 22.0.1
 - Ghidra Version: 11.2_DEV ~ 2517a3234822de74e05e642a55f79d8f3b4c5198

**Additional context**
This doesn't happen with every gdt archive. Even others in the same directory are fine.

**Comment by ghidra1** [comment]
I assume you get an error "Transaction already started"

This is a regression bug when undo/redo support was added for archives.  A fix is on the way.

**Comment by astrelsky** [comment]
> I assume you get an error "Transaction already started"
> 
> This is a regression bug when undo/redo support was added for archives. A fix is on the way.

I don't get any error. Absolutely nothing happens. I have the log level set to debug as well. The only thing logged when attempting to open for editing is "{date} {time} DEBUG (PackedDatabaseCache) Using cached packed database: {path}"

**Comment by ghidra1** [comment]
@astrelsky Fix has been pushed.  Please let me know if the issue is resolved.  If not, I will re-open and continue Triage.

**Comment by astrelsky** [comment]
> @astrelsky Fix has been pushed.  Please let me know if the issue is resolved.  If not, I will re-open and continue Triage.

It does appear to be fixed, thank you.
