### ISSUE TITLE
[BSim] Difficulty specifying programs in BSim `generatesigs` command line utility.

### ISSUE THREAD

**Issue by harmansmithandsons** [NationalSecurityAgency/ghidra#6777]
I would like to use the BSim command line utility to generate signatures for specific programs in a project. I am currently able to use the utility to generate signatures for an entire project at once, but I would like to be able to specify one particular program at a time.

When I generate signatures for an entire project, I execute the following command:
`./bsim generatesigs ghidra:/Users/hsmith/dummy-proj --bsim file:/Users/hsmith/projects/bsim/database/test-db`
The result of this is successfully populating the database `test-db` with signatures for every program contained in the project `dummy-proj`. This is working as desired on my end.

However, when I slightly edit the command to specify a program `programA` within the `dummy-proj` project, like so:
`./bsim generatesigs ghidra:/Users/hsmith/dummy-proj/programA --bsim file:/Users/hsmith/projects/bsim/database/test-db`
it returns "ERROR Projector repository not found (BSimLaunchable)". 

Would there be a different path syntax for running the command line tool on a specific program as opposed to an entire project?

**Comment by ghidra1** [comment]
That is the incorrect URL form for a local project program file.  Local project file URL has the form:  'ghidra:/[<project-path>/]<project-name>?/<program-path>'

**Comment by harmansmithandsons** [comment]
Thank you, I wasn't aware of that.
