### ISSUE TITLE
"Shared Return Calls" Analyzer should not trigger when call goes to back to current function.

### ISSUE THREAD

**Issue by mh-** [NationalSecurityAgency/ghidra#678]
**Is your feature request related to a problem? Please describe.**
Functions that have a GOTO instruction which jumps to the beginning of the function (which effectively implements a loop) are decompiled to some apparently recursive construction.

**Describe the solution you'd like**
If the branch command jumps back to the function in which the branch command is located, the "Shared Return Calls" Analyzer should apply a "BRANCH" instruction flow (and not a "CALL_RETURN").

**Describe alternatives you've considered**
- manually checking all "Flow Override" occasions in the listing and correcting the cases explained above.
- not using "Shared Return Calls" Analyzer

**Comment by emteere** [comment]
The Shared Return Analyzer should not be changing the flow of the branch to the beginning of the function.  I believe there is code to stop that.  Doing so, I would consider a bug.

Is the branch instruction part of the functions body, meaning can you Select->Function, and the beginning of the function is also selected?

 Can you provide an example?

**Comment by mh-** [comment]
Here's an example (see CODE:00c6):
<img width="764" alt="Ghidra Flow Override at CODE-00c6" src="https://user-images.githubusercontent.com/6257627/59405230-03d8b000-8daa-11e9-8c6d-b9c901a508e3.png">
Yes, the branch instruction is part of the function's body, i.e. with Select->Function, the beginning of the function is also selected.

**Comment by emteere** [comment]
That shouldn't happen, I'll have to check out the code.
