### ISSUE TITLE
RFC: YARA auto-analysis extension

### ISSUE THREAD

**Issue by subreption-research** [NationalSecurityAgency/ghidra#6781]
We are planning to develop a plugin or extension for enriching auto-analysis, using YARA rulesets. At the moment there is a script to provide similar functionality but it seems like this functionality might be best suited for an auto-analysis plugin at this point, in our opinion.

We would like to know if there are plans already, or ongoing efforts, for such development, in which case we would like to know what framework or bindings have been chosen to implement YARA support.

At the moment there  is yara-java (https://github.com/p8a/yara-java/) which is not readily maintained per se, and not much else.
This is likely our chosen library to implement the component, unless something better exists or there are concerns about its adequacy.

We also intend to evaluate the possibility of releasing the resulting component (sans our own signature sets and tooling to generate them), and that begs the question if there is a chance of inclusion into Ghidra, in which case it is best to know your code style preferences and other guidelines beforehand.

**Comment by ghidra2** [comment]
We do not have any immediate plans to extend the Ghidra script called RunYARAFromGhidra.py.

I could not comment on the possibility of including your plugin into Ghidra unless I have had the opportunity to evaluate the plugin.

There could be some risk of basing your plugin on a library if that library is not maintained.

Developing your work as a Ghidra extension would facilitate our testing and evaluation.  See the Ghidra Help Topic called "Extension Installation." If you decide to submit a Pull Request, then please use the following guidelines:

https://github.com/NationalSecurityAgency/ghidra/blob/master/CONTRIBUTING.md.

https://github.com/NationalSecurityAgency/ghidra/blob/master/GhidraDocs/GhidraCodingStandards.html

Also, you may find using GhidraSharedPreferences.epf useful (/path/to/Ghidra/support/)

**Comment by kweatherman** [comment]
Additional data for note #2.
In an email exchange with Luigi Auriemma around the time (two years ago), he pointed out to me there was no license requirements for use of his signature DB.
Essentially waiving any license requirements. If nothing else I wanted to acknowledge, give him credit for his (and some unnamed contributors) DB.

I was asserting a MIT License for my own code, but that being said, if there is any conflicts at all, I'll just wave the license completely for you use.

All my projects are free and open source, hopping that people in the development, security, and reverse engineering fields might find them useful. I started adding a license after I got a little miffed that someone created a derivative project of mine, using the same name and not giving me credit for it about five years ago.

Glad and honored you've added the support to Ghidra.

**Comment by ryanmkurtz** [comment]
No need to reopen this issue.  It's primary purpose was to ask a question about our existing or future yara plans, which I believe we answered.  If you plan on submitting a PR, there is no need to create an accompanying issue with it...just the PR will work fine.  Thanks!

**Comment by ryanmkurtz** [comment]
Ok.  I personally will not have any time to review a private repo, but will be happy offer some comments on a public PR.

**Comment by ryanmkurtz** [comment]
`Analyzer.added()` throws `CancelledException`, so you really just want any uncaught `CancelledException`'s to bubble up to and out of that method and the framework will then handle it appropriately.  You would typically call the various cancel() methods in a loop so they don't block the user clicking the cancel button in the lower right of the GUI.  If all my methods throw `CancelledException`, i usually just use `monitor.increment()` or `monitor.checkCancelled()` and call it a day.

We aim to support the following platforms:
* macos_arm_64
* macos_x86_64
* linux_x86_64
* linux_arm_64
* win_x86_64

We've also recently starting adding various forms of support for:
* freebsd_x86_64 (builds and runs, but no debugger support)
* win_arm_64 (doesn't build, but runs)

If you are introducing native components, we'd at least want support for that top set.  I assume your native components reside in a jar?  What platforms does it support?

**Comment by ghidra2** [comment]
Our team discussed this today and we've decided that we would like to see this gain some traction as a popular 3rd party extension before we give further consideration into merging it into Ghidra.  This is why our extension mechanism exists.  Additionally, we try to minimize the amount of 3rd party libraries, especially 3rd party native libraries, that we include in our releases.  We are interested in seeing how this aspect of your extension evolves over time as well.
