### ISSUE TITLE
Tabs in modals fail to focus

### ISSUE THREAD

**Issue by nmggithub** [NationalSecurityAgency/ghidra#6782]
**Describe the bug**
This is an intermittent bug, but I will do my best to explain it. Basically, in several places where there is a TabView (or whatever it is called), it seems Ghidra is unable to focus specific tabs (see reproduction steps for more information).

**To Reproduce**
1. Perform a search or open a struct in the Structure Editor (both are modals with tabs)
2. Perform another search or open another struct (should add a tab to the modal and focus it)
3. Observe the modal opening, but the new tab not focusing

**Expected behavior**
The search results and/or Structure Editor opens and the newly opened tab is focused

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: macOS 14.6
 - Java Version: 22.0.1
 - Ghidra Version: 11.1.2
 - Ghidra Origin: GitHub releases

**Additional context**
This is intermittent, but I have noticed it enough to where it is frustrating. This was not happening on the version I used previously: 11.0.3.

**Comment by dragonmacher** [comment]
May be related to #6576
