### ISSUE TITLE
Is the information panel we refer to as File Offset the RVA?

### ISSUE THREAD

**Issue by maskelihileci** [NationalSecurityAgency/ghidra#6794]
Describe the bug :

As stated in the subject line, I am looking for the Copy RVA feature, but I am not reaching the correct result

To Reproduce :

![image](https://github.com/user-attachments/assets/82355852-0cc8-4a18-a4f5-c265c2022d37)

Expected behavior :

To provide the correct RVA value.

**Screenshots**

![image](https://github.com/user-attachments/assets/7836b59d-c8a0-4734-95b2-515df7311991)

**Environment (please complete the following information):**
 - OS: [Windows 10 22H2]
 - Java Version: [17.0.9]
 - Ghidra Version: [11.1.2]
 - Ghidra Origin: [e.g. official GitHub distro, third party distro, locally built]

**Comment by ryanmkurtz** [comment]
No, the File Offset is not the RVA.  Generally speaking, the RVA is `(Address - Imagebase)`.  We don't have a field for that, but if you hover on an address, it is listed as `Imagebase Offset`.

**Comment by maskelihileci** [comment]
Then let's change the topic to a feature request. We are looking forward to 'GO TO RVA' and 'COPY RVA' features. Good luck.
