### ISSUE TITLE
Add ability to RegExp search through all function decompilations

### ISSUE THREAD

**Issue by djf82** [NationalSecurityAgency/ghidra#6795]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to find decompiled code that matches a certain pattern. Like find code that access a certain index into an array, or use of particular parameter in a certain way. Manually doing this takes too long.

**Describe the solution you'd like**
Have a "Decompilation search", which would allow specifying a `RegExp` which would scan over every functions' decompilation lines.

**Describe alternatives you've considered**
I have written a basic Ghidra Python script for this, but it is not that fast, and the output isn't tabulated nicely like the other search Ghidra mechanisms (though perhaps I could work out how to do that).

**Additional context**
No additional context.

**Comment by dragonmacher** [comment]
Such a service already exists for finding references to data types.   The same general principle of parallel decompiling could be used to create a general purpose text search feature for decompiled output.

**Comment by Skelp** [comment]
Not much has happened since. I really needed this feature, so I decided to create a Jython script while ghidra does not support this natively.
https://gitlab.com/-/snippets/4782010
