### ISSUE TITLE
Impossible to re-target debugger after submitting target once

### ISSUE THREAD

**Issue by Smileynator** [NationalSecurityAgency/ghidra#6803]
**Describe the bug**
After using the debuggers "Debug X in dbgeng locally IN-VM" or similar options once, you can not change the path you give to the console line.

**To Reproduce**
1. Open any exe in the debugger
2. Start the debugger IN-VM
3. Ghidra will prompt once "Command line: "<Path to file you have open>
4. Accept path
5. You can now never see this dialog again for this project/file

**Expected behavior**
Either prompt always, or give an option to reset the prompt, clear the path, anything that works to circumvent the issue.

**Environment (please complete the following information):**
 - OS: Win 10 - up to date patches
 - Ghidra Version: 11.1.2
 - Ghidra Origin: Official Ghidra repo

**Additional context**
A workaround is to rename or delete the file you pointed to, this will invalidate the path, and re-prompt the user for a path again.
Sadly, if you ever point it to CMD or something else you cannot simple rename or delete, you no longer have that option either. (Which brings me here)
The behavior is especially annoying when you are working on a DLL and accidentally accepted the DLL as target as opposed to the EXE that will actually use the DLL. Or anything similarly annoying to start by just "running the targeted file".

**Comment by d-millar** [comment]
@Smileynator The "Debug X in dbgeng locally IN-VM" is basically the easy button for running the program open in the Static Listing with the least possible effort.  If you want to do anything more complicated, you'll need to use the "Launch (X)" button in the Objects View, e.g. for adding parameters or resetting the command line.  You can so the latter by either launching with the "Debug X" button, killing the process, and using "Launch (X)" or, more straightforwardly, by connecting an "MS dbgeng.dll" session from the "Debugger Targets" view and then using the "Launch (X)" button.

We realize this is not perhaps immediately obvious, which is one of the reasons the "Debugger Targets/Objects" combination is being deprecated and replaced with the "Connections/Model" python-based debugger.

**Comment by Smileynator** [comment]
Ok, yes, i got that to work.
I have to admit, this was anything but obvious to a starter, and i am sure it might have been in the documentation somewhere in hindsight.
Since this path you outlined works just fine, i would encourage getting rid of that old button in favor of the more nuanced but not at all more complicated route, so that all the guides people will follow online, can switch to that as well.

Thanks for the help, i can experiment with my launch options now 👍
