### ISSUE TITLE
"Applying packing may drastically change this structure..."

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#6808]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm prompted with this pop-up when finished making a datatype and making it aligned according to the compiler.

**Describe the solution you'd like**
Setting to suppress this.

**Describe alternatives you've considered**
git revert ...

**Comment by ghidra1** [comment]
I am in the process of adding undo/redo to the structure editor which will likely eliminate the need to warm the user.  This warning  was added after users complained about losing their edits when accidentally enabling packing.

**Comment by Wall-AF** [comment]
> I am in the process of adding undo/redo to the structure editor which will likely eliminate the need to warm the user. This warning was added after users complained about losing their edits when accidentally enabling packing.

Will this `undo` feature be local to each structure?  I.e. `Ctrl+z` will ONLY affect the current structures editable changes[^1] and not changes that maybe undergoing in another structure or elsewhere.
[^1]: will a history be available, or just the current edit?

**Comment by ghidra1** [comment]
Undo/Redo will be local to each structure/union editor although certain external changes (e.g., undo/redo of  associated program or datatype archive, modification of dependency datatype, etc.)  can cause the editor's undo stack to clear within the editor.  This is neccessary to avoid inconsistencies of dependency datatypes used by an editor which could trigger conflicts if undo/redo were allowed and the edit applied.  

Not sure what you mean by history.  There will be an undo/redo stack with a terse description of a the next change which can be undone or redone (e.g., 20 undoes).  It does not have a undo/redo history pulldown as does the Program.

**Comment by astrelsky** [comment]
> I am in the process of adding undo/redo to the structure editor which will likely eliminate the need to warm the user. This warning was added after users complained about losing their edits when accidentally enabling packing.

Understood.

Doesn't everybody just save their work every 2 seconds though? Most of the time my problem is I can't undo something because I compulsively saved.

**Comment by dragonmacher** [comment]
We have discussed using a model that allows for an undo history, even after a save operation.

**Comment by astrelsky** [comment]
> We have discussed using a model that allows for an undo history, even after a save operation.

fwiw I wasn't actually complaining about it here, it was just circumstantial.

**Comment by ghidra1** [comment]
The popup has been eliminated.
