### ISSUE TITLE
ghidra.program.database.code.InstructionDB does not return complete/correct operand data for aarch64 ld1r instruction

### ISSUE THREAD

**Issue by mike-hunhoff** [NationalSecurityAgency/ghidra#6817]
**Describe the bug**
`ghidra.program.database.code.InstructionDB` does not return complete/correct operand data for aarch64 `ld1r` instruction e.g.
![Screenshot from 2024-08-14 16-35-53](https://github.com/user-attachments/assets/3c3f581e-a93d-4c51-b611-da5c288f5f32)

**To Reproduce**
1. Load and analyze https://github.com/mandiant/capa-testfiles/blob/3c790887a3f3aa671b2ccc1ec1fd14feff354f5c/aarch64/d1e6506964edbfffb08c0dd32e1486b11fbced7a4bd870ffe79f110298f0efb8.elf_
2. Execute code shown above for instruction at 0x119970

**Expected behavior**
I'd expect the number of operands to equal two, and the arrangement specifier to be fully represented, resulting in the following output:
```
(0, [v, 0, ., 1, 6, B])
(1, [x20])
```

**Environment:**
 - OS: Ubuntu 24
 - Java Version: 17
 - Ghidra Version: 11.1
 - Ghidra Origin: GitHub distro

**Comment by ghidra1** [comment]
This effectively duplicates #6821 and is not a bug as discussed in that issue.

**Comment by ghidra1** [comment]
Your example appears to have a print-piece which is empty.  This is likely due to a constructor which may have  an additional "operand" with a default case where it need not be specified.
