### ISSUE TITLE
Ghidra does not correctly import dylibs from dyld shared caches

### ISSUE THREAD

**Issue by pwmoore** [NationalSecurityAgency/ghidra#682]
**Describe the bug**
iOS devices ship with all shared libraries (dylibs) in a unified cache. Ghidra seems to offer the feature to import individual dylibs from a shared cache, but does not seem to parse them correctly.

**To Reproduce**
1. Open a new project
2. Choose "File->Import File"
3. Select the dyld_shared_cache_arm64[e] file.
4. Choose File System.
5. Select the dylib to import (i.e. Foundation)
6. Continue normal import steps

**Expected behavior**
IDA Pro successfully imports a dylib from a shared cache as if they were individual dylib files. It correctly locates the Mach-O header and processes the dylib. 

**Screenshots**
The first screenshot shows IDA 7.2's listing of Foundation.framework from an iPhone XS 12.3.1 shared cache. The cache can be retrieved from the IPSW [here](http://updates-http.cdn-apple.com/2019SpringFCS/fullrestores/041-68319/CC1D6332-7C96-11E9-A9E7-37F06256CCDB/iPhone11,2_12.3.1_16F203_Restore.ipsw).

<img width="1680" alt="Screen Shot 2019-06-11 at 11 10 15 PM" src="https://user-images.githubusercontent.com/417112/59354251-c49b5800-8cf2-11e9-8ffd-269bbd591ed0.png">

Note that IDA has correctly located the dylib's Mach-O header and parsed it correctly. However, in Ghidra, the load address isn't a Mach-O header at all.

<img width="1678" alt="Screen Shot 2019-06-12 at 9 15 41 AM" src="https://user-images.githubusercontent.com/417112/59354259-ca913900-8cf2-11e9-8e1d-c6815eea6c07.png">

In the next two screenshots I am trying to show the NSLog() function. The correct function is displayed in IDA here: 

<img width="1678" alt="Screen Shot 2019-06-12 at 9 21 40 AM" src="https://user-images.githubusercontent.com/417112/59354717-9ff3b000-8cf3-11e9-98dc-75f6d09e4607.png">

But Ghidra has just placed the NSLog() label in the middle of some other code.

<img width="1679" alt="Screen Shot 2019-06-12 at 9 21 18 AM" src="https://user-images.githubusercontent.com/417112/59354729-a6822780-8cf3-11e9-894e-6b567474caaf.png">

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Java Version: 11.0.3
 - Ghidra Version: 9.0.4

**Comment by ryanmkurtz** [comment]
Thanks for reporting this, it's something we are aware of and its in the queue.  I chose to implement a new loader for the entire DYLD cache first, since things like jtool do a good job of extracting DYLIB's which can then be fed into Ghidra.  The new loader will be released in Ghidra 9.1, but it's currently in master if you want to try it out...I would love some feedback.  It's main limitation right now is speed, since there are so many embedded DYLIB's to analyze.  

I do plan on investigating this issue though.

**Comment by pwmoore** [comment]
Awesome, I'll try and get the master branch going sometime this week and let you know how it goes.

**Comment by pwmoore** [comment]
So I started playing around a little with the master branch and loading an entire dyld cache, and I have to say I'm impressed. It managed to load the entire cache... I had to first bump up the amount of memory, and as expected its a little slow, but it did it, which is something IDA can't do. :) I'm still playing around with it, but I did notice that it doesn't seem to be picking up symbol names. See the attached screenshot for NSLog (the same function above). Should I open a new issue for this or any other issues with the master branch?

Thanks for the awesome work so far on this, I'm excited to see where you guys take it.

<img width="1635" alt="Screen Shot 2019-06-24 at 1 29 46 AM" src="https://user-images.githubusercontent.com/417112/59993920-0051ee00-9620-11e9-8973-71ccc6012e02.png">

**Comment by ryanmkurtz** [comment]
Thanks for the positive feedback!  Sure, I think new issues that pertain to the DYLD loader would be best...we can keep this issue about the DYLD filesystem and extracting individual DYLIB's from it.

**Comment by ryanmkurtz** [comment]
Hmmm, all the symbol addresses seem to have been truncated to 32-bits.  When I fix that hopefully that will fix the behavior you are seeing.

**Comment by ryanmkurtz** [comment]
The symbol issue should be fixed now.

**Comment by blacktop** [comment]
Another way to split the dyld is to use Xcode, however, when I load the split dylib into Ghidra it does not recognize it as a macho or what processor to use??

jtool split:

```bash
$ head -c 100 dyld_shared_cache.JavaScriptCore|hexdump -C

00000000  cf fa ed fe 0c 00 00 01  02 00 00 00 06 00 00 00  |................|
00000010  16 00 00 00 d8 0e 00 00  85 00 11 c2 00 00 00 00  |................|
00000020  19 00 00 00 68 03 00 00  5f 5f 54 45 58 54 00 00  |....h...__TEXT..|
00000030  00 00 00 00 00 00 00 00  00 f0 14 88 01 00 00 00  |................|
00000040  00 90 d3 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 90 d3 00 00 00 00 00  05 00 00 00 05 00 00 00  |................|
00000060  0a 00 00 00                                       |....|
00000064
```

Xcode split:

```bash
$ head -c 4200 System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore|hexdump -C
00000000  ca fe ba be 00 00 00 01  01 00 00 0c 00 00 00 02  |................|
00000010  00 00 10 00 01 03 d0 00  00 00 00 0c 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001000  cf fa ed fe 0c 00 00 01  02 00 00 00 06 00 00 00  |................|
00001010  16 00 00 00 d8 0e 00 00  85 00 11 42 00 00 00 00  |...........B....|
00001020  19 00 00 00 68 03 00 00  5f 5f 54 45 58 54 00 00  |....h...__TEXT..|
00001030  00 00 00 00 00 00 00 00  00 f0 14 88 01 00 00 00  |................|
00001040  00 90 d3 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00001050  00 90 d3 00 00 00 00 00  05 00 00 00 05 00 00 00  |................|
00001060  0a 00 00 00 00 00 00 00                           |........|
```
Notice that Xcode seems to be wrapping the machO in a CAFEBABE ??

**Comment by blacktop** [comment]
**UPDATE:** I tried using XCode 11 beta and it seems to not wrap it in the CAFEBABE so... nevermind 😖 


 👁 ❤️ 🐉

**Comment by tmm1** [comment]
Is the best way to use ghidra still to either load the entire cache or use another tool to split first?

**Comment by charlesomer** [comment]
Is it still only possible to decompile a framework successfully by loading the whole cache? If so, does anyone know of a working guide to extract frameworks?

**Comment by ryanmkurtz** [comment]
You could use something like [jtool](http://newosxbook.com/tools/jtool.html) to extract the component you care about, and then import it into Ghidra.

**Comment by charlesomer** [comment]
Does jtool still work? I can't get jtool or jtool2 to extract a framework from the `dyld_shared_cache_arm64e` or `dyld_shared_cache_x86_64` found on macOS. Using this command for jtool2: `jtool2 -e AirPlayReceiver ./dyld_shared_cache_x86_64`. Results in errors similar to: `Warning: File is likely truncated (or header corrupt?) Binding opcodes falls outside file`.

**Comment by ryanmkurtz** [comment]
I haven't tested jtool in a long time so it's definitely possible this solution will no longer work.

**Comment by charlesomer** [comment]
Yeah it looks like (at least for what I’m trying), jtool doesn’t work with the current macOS cache. Which leaves little options left by the looks of it. I tried increasing the ram allocated to 15GB and Ghidra still couldn’t open the entire cache unfortunately either :(

**Comment by mrakers** [comment]
@ryanmkurtz @charlesomer 
This is a bit late but the best way to extract dylibs from the cache is to use the sample binary Apple provides. You simply compile the sample binary found at the bottom of the file found here - https://opensource.apple.com/source/dyld/dyld-750.5/launch-cache/dsc_extractor.cpp.auto.html

Note: However this is by no means a perfect solution and is annoying because this requires you to have a Mac.
