### ISSUE TITLE
Debugger does not halt after step over or step out of call to printf when using gdb

### ISSUE THREAD

**Issue by Erikun** [NationalSecurityAgency/ghidra#6822]
**Describe the bug**
When stepping over or stepping out of printf, the debugger does not halt on the next instruction but instead continues the program to its end.
**To Reproduce**
1. Compiler program fibber.c (code at the end) and import into project and analyze it.
2. Open in debugger and select Debugger > Configure and Launch fibber_bin using... > gdb
3. Choose Run command: Start in the popup window and press Launch
![Screenshot from 2024-08-17 17-13-51](https://github.com/user-attachments/assets/2748a73f-7845-476a-90c9-c9f0f47864cc)
4. Debugger stops in main on instruction 0x001011b4, Dynamic - Auto PC window has not Disassembled after call to printf
![Screenshot from 2024-08-17 17-16-49](https://github.com/user-attachments/assets/91be3bfc-206a-418d-9966-95db30c6fe41)

5. Click "Step over" until on call to printf
6. Click "Step over" again, instead of halting on next instruction program runs to the end and exits normally.

**Expected behavior**
Program would halt on instruction after call to printf.

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Ubuntu 22 and 24
 - Java Version: 21.0.4
 - Ghidra Version: 11.1.2
 - Ghidra Origin: Github distro
 - GDB Version: 12 and 15.0.50 

**Additional context**
Tested with program
```
// fibber.c: A simple recursive Fibbonacci sequence calculation program
#include <stdio.h>

unsigned int fibbonacci(unsigned int n){
    if(n <= 1){
        return n;
    }
    else{
        return (fibbonacci(n-1) + fibbonacci(n-2));
    }
}

int main(){
    unsigned int n = 10;

    printf("First %d elements of the Fibbonacci sequence: ", n);

    for(unsigned int i = 0; i < n; i++){
        printf("%d ", fibbonacci(i));
    }
    printf("\n");
    return 0;
}
```

**Comment by d-millar** [comment]
@Erikun  Looking into this - can definitely reproduce what you're seeing (and definitely a bug).  No clue yet as to why this is happening.  More soon.

**Comment by nsadeveloper789** [comment]
I've found the cause and a workaround. We use a catchpoint to detect changes to the memory map. If you type `info breakpoint` into the Terminal right after launch, you can see it.

This issue, I believe, is that the *first* call to printf causes the module to be lazily loaded, which hits this catchpoint. We have a command list in there, intending to avoid actually breakpoint, ends with `cont`. Sadly, I suspect this final `cont` overrides your `nexti` or Step Over button.

You can work around the issue by typing `dis 1` into the Terminal after launch. You'll have to refresh the Memory Map on your own from that point on, though. If it seems your program counter has disappeared into nowhere (i.e., the dynamic listing stops tracking), then right-click the Memory node in the Model panel and select "Refresh Memory."

Clearly, this is a big problem. I guess we'll want an alternative for automatic memory refresh....
