### ISSUE TITLE
Can't view text in certain windows of Ghidra on RHEL 9.4

### ISSUE THREAD

**Issue by itsallmathematics** [NationalSecurityAgency/ghidra#6831]
**Describe the bug**
I am unable to view the text in Listing, Decompile, and Console - Scripting Windows nor am I able to view the text in the "Dragon logo" splash screen at startup. In fact, I was unable to even view The Ghidra & Java versions on the splash screen, but retrieved them using an alternate method. The only notable change I've made to the system recently is that I upgraded from RHEL 9.2 to RHEL 9.4.

**NOTE:** The text glitches in and out when I scroll around the affected windows/highlight with the cursor, but this is completely breaking because at no point is any significant amount of text visible, it is maybe a string or 2 at a time at most, and the string that is visible is not necessarily the one I have highlighted with the cursor. Also, yes, I have tried rebooting a few times to make sure it wasn't a strange one-off glitch.

**To Reproduce**
Start ghidra using ./GhidraRun and the behavior occurs at the splash screen, and subsequently on the Decompiler, Listing, and Console - Scripting windows.

**Expected behavior**

**Screenshots**

**Attachments**
![Ghidra_GUI_Bug](https://github.com/user-attachments/assets/fabdf900-1654-4426-8239-4c3ecb7f3c79)

**Environment:**
 - OS: RHEL 9.4
 - Java Version: 21.0.3
 - Ghidra Version: 11.1.2
 - Ghidra Origin: Official GitHub Distro

**Additional context**
If it is known which component is having the bug, I am willing to try debug steps and/or workarounds. I am just not familiar which component that could be causing this, but I could guess some sort of bug between the GUI framework and display renderer or video driver?

**Comment by astrelsky** [comment]
I suspect this may be a theming issue. Try playing with the theme configuration to see if it helps. It is available in the edit menu of the first window you get when you open Ghidra.

**Comment by ryanmkurtz** [comment]
@itsallmathematics I cannot reproduce this.  Are you still having the issue?

**Comment by ryanmkurtz** [comment]
Are you on RHEL too?

**Comment by ryanmkurtz** [comment]
@itsallmathematics can you try setting `VMARGS=-Dsun.java2d.opengl=false` in `support/launch.properties` to `true` to see if that has any effect?
