### ISSUE TITLE
No X11 Display Variable was set

### ISSUE THREAD

**Issue by nightgla55** [NationalSecurityAgency/ghidra#6835]
I have a freshly built version of Ghidra on my Ubuntu 22.04 server that is not wanting to launch a window. When I ran ghidraDebug I saw the error messages about: "No x11 display variable was set, or no headful library support was found, but this program performed an operation which requires it".

I am opening it through a local Gnome desktop, and have the appropriate version Java installed and in use, and my env variables are correctly exported. Is there something to do with compatibility between Ghidra and Ubuntu together that I am missing? Any help, greatly appreciated.

**Comment by ryanmkurtz** [comment]
Did you install Java through apt? If so, what package did you install? You have to be careful not to install the headless version of the JDK that they like to offer by default.

**Comment by nightgla55** [comment]
Hey @ryanmkurtz thank you for the help. That was indeed the issue. Something so simple- awesome note to self.

Good to step away and come back with fresh eyes, can't believe I missed it! Thank you again.
