### ISSUE TITLE
Searching for symbol in big binary lags UI.

### ISSUE THREAD

**Issue by teropentis64** [NationalSecurityAgency/ghidra#6847]
**Is your feature request related to a problem? Please describe.**
Trying to search for a symbol in a big binary freezes / heavily lags UI.

**Describe the solution you'd like**
Add option to make search field ("Filter" field to be precise) do it's action on some user feedback. For example clicking "enter" key. Sometimes updating results on every key input makes it extremely slow.

**Comment by dragonmacher** [comment]
Which search feature are you using?  We have quite a few.  Please list the steps you used to exhibit the behavior.

**Comment by teropentis64** [comment]
The stuck module is "Symbol Tree" on the left side. If it's stuck, it's always with "Expanding nodes..." text. I just encountered it. Ghidra is not responding, there is 13GB of memory left, and CPU usage is at 50% total.

**Comment by dragonmacher** [comment]
I see.  A thread dump will help us determine what is happening when you get into this state.  

From a terminal you can run these commands:
```
jps
jstack <Ghidra pid>
```

**Comment by teropentis64** [comment]
Sure thing. As previously, Ghidra is stuck on on Expanding nodes...
[log.txt](https://github.com/user-attachments/files/16732706/log.txt)
![log2](https://github.com/user-attachments/assets/c77f6098-c137-4252-957e-aa8fbcfd0b4f)

**Comment by dragonmacher** [comment]
Something to try: before you open your binary, you can open the Code Browser and then close the Symbol Tree.  After re-opening your binary, see if the issue persists.  I'd like to isolate the Symbol Tree to verify that is the issue.

**Comment by dragonmacher** [comment]
The issue appears to be an infinite loop inside of the Mac `AppKit Thread`:

```
	at sun.lwawt.macosx.LWCToolkit.doAWTRunLoopImpl(java.desktop@22.0.2/Native Method)
	at sun.lwawt.macosx.LWCToolkit.doAWTRunLoop(java.desktop@22.0.2/LWCToolkit.java:938)
	at sun.lwawt.macosx.LWCToolkit.invokeAndWait(java.desktop@22.0.2/LWCToolkit.java:740)
	at sun.lwawt.macosx.LWCToolkit.invokeAndWait(java.desktop@22.0.2/LWCToolkit.java:685)
	at sun.lwawt.macosx.CAccessibility.invokeAndWait(java.desktop@22.0.2/CAccessibility.java:136)
	at sun.lwawt.macosx.CAccessibility.invokeAndWait(java.desktop@22.0.2/CAccessibility.java:129)
	at sun.lwawt.macosx.CAccessibility.getChildrenAndRolesRecursive(java.desktop@22.0.2/CAccessibility.java:764)
```

We been working on accessibility over the last year.  It's possible we have introduce code that can trigger this infinite loop.  We will investigate this.

**Comment by dragonmacher** [comment]
This may be related this:

https://github.com/corretto/corretto-17/issues/132

**Comment by teropentis64** [comment]
The issue only appears when the Filter field is populated with something. I can try using CMD+T symbol menu and report back, but I think it's highly related to revealing these trees. I don't have any accessibility options enabled but I can try the solution provided in linked issue.

**Comment by teropentis64** [comment]
Also, is there any recommended JDK version for Ghidra ? I was using the newest one before, and switched to mentioned JDK11 and I already can see difference in snappiness of Ghidra (maybe just a placebo though).

**Comment by dragonmacher** [comment]
This is the link we provide on the main github page (jdk 21): https://adoptium.net/temurin/releases/

You can always try different implementations as needed.   I don't have a personal recommendation for what is best on the Mac.

**Comment by teropentis64** [comment]
Seems like JDK 17 fixed my issue. Even more, Ghidra feels a lot snappier, now I'm certain thats the case. Thanks!
