### ISSUE TITLE
Ability to control "Code unit" font in tables.

### ISSUE THREAD

**Issue by teropentis64** [NationalSecurityAgency/ghidra#6853]
**Is your feature request related to a problem? Please describe.**
The font in "Code unit" (which also appears in other places) is not exposed through theme editor.

**Describe the solution you'd like**
Ability to change the font.

The font is extremely hard to read on smaller screens (and overall, in my opinion). The font is different on macOS so I guess it's just some variable from JDK ? Could Ghidra declare it's own so we can change it ?

![sdx](https://github.com/user-attachments/assets/40f2e0e7-842f-434a-8d23-a089a49f5305)

**Comment by dragonmacher** [comment]
Currently that column uses a font derived from the table font.  We can look into making that font separately configurable.  For now, you can change the size of that font in the theme editor by changing the value of `font.table.base`.

(This does not appear to update all tables in real-time, as intended.  For example, I tested this in a Search Results table.  When I made the value of that property larger, I had to perform the search again to see the change.)

**Comment by teropentis64** [comment]
Before I made an issue, I changed all the fonts in theme editor to another one, restarted Ghidra and looked so I can be sure that I'm not in the wrong. That font stayed the same (I guess it's Courier New ?).

I double checked, did as You said, changed the font again and restarted Ghidra. The font in Code unit stayed the same, the one on the left changed though but with that I didn't had any problem.

**Comment by dragonmacher** [comment]
I did not try changing the style, only the size.   The style will always end up being 'monospaced' due to how the code is written now.  The size is currently changeable though.  This is what I am seeing:

![image](https://github.com/user-attachments/assets/75fb8fc4-b1cb-4299-bab1-a239a9ce5c9e)

**Comment by teropentis64** [comment]
I've already changed [font.monospaced] global in theme editor and it got applied everywhere (listing, decompiler etc.) except that Code unit...

**Comment by dragonmacher** [comment]
That is something we would need to fix.   The current render for that column is using a font based on this code:

```java
fixedWidthFont = new Font("monospaced", f.getStyle(), f.getSize());
```

This code is not using the theme value of `monospaced`, but using what the JDK resolves for that value.  This is something that we can likely fix in a future release.  As you can see in the code, the style (bold/italic) and the size are updated.  This happens now  when you change the value of `font.table.base`.

Changing the value of `font.monospaced` in the Theme Editor will affect any fonts in the Ghidra system that directly access the property `font.monospaced`, like this:
```java
Font f = Gui.getFont("font.monospaced");
```

But that will *not* affect any code that directly creates a font like this:
```java 
Font f = new Font("monospaced", style, size);
```

As mentioned at the top of this post, the renderer is using the incorrect lookup.

**Comment by teropentis64** [comment]
So if I change JDK value for 'monospaced' it should work, right ? I don't really mind changing it for now as I only use Java for Ghidra in a VM.

**Comment by dragonmacher** [comment]
I have never done this before.  I'm pretty sure there is a way to override the fonts used by the JDK.   This link outlines how it all works and shows how to change values:

https://docs.oracle.com/en/java/javase/11/intl/font-configuration-files.html

However, I'm not sure how well this is supported.  That page is for Java 11.  Also, that page mentions: 
```
For Windows, font configuration files are required.

For macOS, font configuration files are unsupported.

For Linux and Solaris: the Oracle JDK is moving away from providing custom font configuration files on Linux platforms
```

I have no sense of how easy or how well supported font changes are in modern JVMs.  If you figure out a way to make it work, please update the ticket.

**Comment by teropentis64** [comment]
I was able to change it. Heres how:
1. Navigate to your JDK/lib folder
2. Change filename of "fontconfig.properties.src" to "fontconfig.properties".
3. Replaced Courier New references:
- monospaced.plain.alphabetic=Courier New -> monospaced.plain.alphabetic=JetBrains Mono
- monospaced.plain.hebrew=Courier New -> ...
- monospaced.bold.alphabetic=Courier New Bold -> monospaced.bold.alphabetic=JetBrains Mono Bold
- etc. etc.

Please note I have JBR (jetbrains edition of jdk) and I have JetBrains Font inside of fonts folder. I didn't test if it matters for resolving font names.
