### ISSUE TITLE
BUILD FAILED at Task `:Utility:compileJAVA`

### ISSUE THREAD

**Issue by LelouchFR** [NationalSecurityAgency/ghidra#6854]
**Describe the bug**

I cannot compile ghidra by following the installation guide.

**To Reproduce**

1. download source code and run the commands found on the README:

```bash
git clone https://github.com/NationalSecurityAgency/ghidra.git
cd ghidra
gradle -I gradle/support/fetchDependencies.gradle
gradle buildGhidra
```

2. getting an error when running the command `gradle buildGhidra`:

```bash
> Configure project :
Java: 17
Gradle: 8.7
Python3 command:  python3 (version 3.12)
Python3 pip version: 24.1.2
OS: Linux
Arch: amd64 (gradle: x86-64)
Using platform: linux_x86_64

> Configure project :Debugger-agent-dbgeng
WARNING: dbgmodel.tlb omitted from ghidradbg python package

> Task :Utility:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Utility:compileJava'.
> error: invalid source release: 21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Expected behavior**

Succesfully Compile Ghidra

**Screenshots**

![image](https://github.com/user-attachments/assets/e6610ed0-a3dc-4b03-9961-f198959c59fd)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Gentoo GNU/Linux
 - Java Version: 17.0
 - Ghidra Version: 11.1.2 (latest)
 - Ghidra Origin: official GitHub distro 
 - JAVA_HOME: `/usr/lib/jvm/openjdk-bin-17`
 - Gradle Version: 8.7

**Additional context**
I installed every single dependency needed (at least all noted on the README file)

**Comment by mumbel** [comment]
```
* What went wrong:
Execution failed for task ':Utility:compileJava'.
> error: invalid source release: 21
```
you're using 17, change to 21

**Comment by LelouchFR** [comment]
> ```
> * What went wrong:
> Execution failed for task ':Utility:compileJava'.
> > error: invalid source release: 21
> ```
> 
> you're using 17, change to 21

Thanks, works all fine now !
