### ISSUE TITLE
`Find uses of` in struct editor is gone

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#6868]
**Describe the bug**
Struct editor no longer has `find uses of` right click menu item.  Enum editor still does, and DTM has it for both

**Environment (please complete the following information):**

Ghidra Version: 11.2
Ghidra Release: DEV
Ghidra Build Date: 2024-Aug-30 1620 CDT
Ghidra Revision: 184180d54dbdf3db3c030ead3772f6f8f46f9d72
Ghidra Development Mode: false
OS Name: Linux
OS Arch: amd64
OS Version: 6.8.0-40-generic
OS Pretty Name: Ubuntu 22.04.4 LTS
Java Vendor: Ubuntu
Java Version: 21.0.4

**Comment by dragonmacher** [comment]
Looks like an issue with enablement, which prevents it from appearing in the menu.
