### ISSUE TITLE
Enum table sorting occurs before completion of `tab`

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#6873]
**Describe the bug**
This feels like a bug.

If I'm editing an enum while its sorted by name.  I create a new entry, I type a name which would resort the table, while the text box is active/editable I press tab.  The new name is sorted and the order of the rows change, then the cursor moves over to value column in the same row presorted, editing an entry that is unrelated to the new entry.

I can't think of any tools I use that have active sorting like this to compare/contrast, but this feels like it should keep the cursor with the new entry

**Environment (please complete the following information):**
Ghidra Version: 11.1.2
Ghidra Release: PUBLIC
Ghidra Build Date: 2024-Jul-09 1157 EDT
Ghidra Revision: 68cad06ddfae2b92c03054357c67c32f2d0553a8
Ghidra Development Mode: false
OS Name: Linux
OS Arch: amd64
OS Version: 6.8.0-40-generic
OS Pretty Name: Ubuntu 22.04.4 LTS
Java Vendor: Ubuntu
Java Version: 21.0.4

**Additional context**

**Comment by dragonmacher** [comment]
I agree that this is quite silly.  I'm surprised nobody has complained of this yet.

**Comment by Wall-AF** [comment]
> I agree that this is quite silly. I'm surprised nobody has complained of this yet.

This is annoying, but there are sooooo many other more pressing issues (in my case)!
