### ISSUE TITLE
Ghidra takes 10 seconds to respond to actions

### ISSUE THREAD

**Issue by Martmists-GH** [NationalSecurityAgency/ghidra#6892]
**Describe the bug**
In the Code browser tool, clicking anywhere in the listing or decompiler causes the tool to freeze for 9-10 seconds.

**To Reproduce**
1. Open a program in Ghidra
2. Open Code Browser

**Expected behavior**
It works like normal without freezing

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Java Version: 17.0.12 (OpenJDK)
 - Ghidra Version: 11.0.3
 - Ghidra Origin: Arch Linux `extra` repository

**Comment by Martmists-GH** [comment]
Might be related to having large amounts of data on the clipboard, restarting Ghidra after clearing it seemed to fix it.

**Comment by dragonmacher** [comment]
We have seen issues similar to this with clipboard content on Linux in the past.   It seemed to be related to content copied outside of Ghidra.   Copying something small from Ghidra into the clipboard should reset this behavior.

**Comment by ryanmkurtz** [comment]
Duplicate of #5085
