### ISSUE TITLE
Documentation: DevGuide.md should reflect that GhidraDev is included in settings.gradle

### ISSUE THREAD

**Issue by mh-** [NationalSecurityAgency/ghidra#691]
**Describe the bug**
The current version of the DevGuide at https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md states:
>  By default, the GhidraDev project is excluded from the build. To enable it, uncomment it in settings.gradle.

This is not correct, currently settings.gradle at https://github.com/NationalSecurityAgency/ghidra/blob/master/settings.gradle DOES include GhidraDev by default.

As a result, the "Get Dependencies for GhidraDev" steps need to be executed always.
Therefore, they should be mentioned in an earlier section of the DevGuide.

**To Reproduce**
Follow the steps in DevGuide.md with a fresh git clone.

**Expected behavior**
All builds should work after the mentioned dependencies have been installed.
But if the "Get Dependencies for GhidraDev" step has not been done, Ghidra build fails.

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Ghidra Version: git clone

**Comment by ryanmkurtz** [comment]
We just made a lot of changes to the DevGuide.  This should be fixed now.
