### ISSUE TITLE
Import base address should allow for `0x`

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#6912]
**Describe the bug**
When importing a new binary and setting the base address, the input box does not allow for the value to start with `0x`

the box is only hex... Is this some hard code logic to avoid someone entering decimal but then accidentally breaking 0x parsing?

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: 17
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official GitHub

**Comment by ryanmkurtz** [comment]
#3157

**Comment by mumbel** [comment]
Helps as a reference, but it's closed/abandoned and no comments were addressed in code.  You'd have to search is:closed to even find it for an unfixed 'issue".  Opening an issue so it's actually tracked.

**Comment by astrelsky** [comment]
> Helps as a reference, but it's closed/abandoned and no comments were addressed in code. You'd have to search is:closed to even find it for an unfixed 'issue". Opening an issue so it's actually tracked.

I must have scared them away.
