### ISSUE TITLE
reducing size of large struct freezes ghidra permanently or until process is killed

### ISSUE THREAD

**Issue by agoschie** [NationalSecurityAgency/ghidra#6936]
**Describe the bug**
Ghidra was frozen for 6+ hours with 100% cpu usage. Monitors showed CPU graph with noisy high cpu usage, maximum boost frequency and stable elevated temperatures. The cause was reducing a giant structs size. It has to be a bug because by MANUALLY selecting the fields and reducing the size in smaller chunks of O(log base 2), you can easily achieve the same goal in a few minutes without freezing ghidra. So the same algorithm could be implemented as a temporary work around if the development team so chooses.

**To Reproduce**
1. Make a struct in the data type manager and set its size to 0xfff. Save.
2.  Edit the struct again and declare random fields with trivial types. Save.
3.  Edit the struct again and set its size to 0xffffff. Save.
4.  Edit the struct again and reduce its size by one hex digit or something similar (0xfffff or 0x11111). Save.
5.  Ghidra freezes indefinitely with 100% cpu usage.

**Expected behavior**
The struct should be resized after a minute of processing.

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - Java Version: Open JDK jdk-22.0.2
 - Ghidra Version: ghidra_11.1.2_PUBLIC
 - Ghidra Origin: official GitHub distro

**Additional context**
The struct editor is open. Manually reducing the struct size by iteratively selecting the fields in O(log base 2) and deleting them in smaller chunks does not freeze Ghidra.

**Comment by ryanmkurtz** [comment]
Duplicate of #6504

**Comment by agoschie** [comment]
This is not a duplicate. This is not a slow down. Ghidra is getting locked in a permanent loop and using 100% cpu. I ran it for 6+ hours and it showed no signs of stopping. I can easily reduce a struct size by manually selecting fields and deleting chunks of it until I reach the desired offset.

**Comment by ghidra1** [comment]
Could you please verify that your problem is resolved with the 11.2 release.  Thanks
