### ISSUE TITLE
Font Support

### ISSUE THREAD

**Issue by sunbo2001** [NationalSecurityAgency/ghidra#6940]
Currently, When I writing a comment in decompiler window or disassembly window with some chinese characters, these characters can not be displayed correctly(just some black square). So I guess that all "CJK" characters will also appear this phenomenon.
I wish ghidra could support all these characters.

**Comment by dragonmacher** [comment]
IIRC, you need to install a font that supports those extended characters.   Ghidra does not ship any fonts, but instead relies on the OS's fonts.  Thus, you can install new fonts on your OS and tell Ghidra to use them.

**Comment by dev747368** [comment]
An earlier issue that may help is #5632
