### ISSUE TITLE
V850ES-Fx3 bin won't disassemble properly

### ISSUE THREAD

**Issue by rkoziolrk** [NationalSecurityAgency/ghidra#6942]
Hello everyone, I'm trying to disassemble a NEC/Renesas V850ES-Fx3 processor file using V850:LE:32:default. Most of the file is OK but there are some instructions that do not disassemble in Ghidra. With v850-elf-objdump.exe output seems to be complete.

Ghidra:

                             LAB_00006cb6                                    XREF[2]:     FUN_00017382:00017438 (*) , 
                                                                                          FUN_000177be:000177c8 (*)   
        00006cb6 00  02           callt      0x0
        00006cb8 ff  01           cmp        lp,r0
        00006cba 01  02           callt      0x1
        00006cbc 00  02           callt      0x0
        00006cbe 02  02           callt      0x2
        00006cc0 01  03           sld.b      0x1 [ep],r0
        00006cc2 03  02           callt      0x3
        00006cc4 02  04           sld.h      0x4 [ep],r0
        00006cc6 04  02           callt      0x4
        00006cc8 03  05           sst.w      0x4 [ep],r0
        00006cca 05  02           callt      0x5
        00006ccc 04  06  06  01    addi       0x106 ,gp,r0
        00006cd0 05              ??         05h
        00006cd1 07              ??         07h
        00006cd2 07              ??         07h
        00006cd3 01              ??         01h
        00006cd4 06  08           mov        r6,r1
        00006cd6 08              ??         08h
        00006cd7 00              ??         00h
        00006cd8 07  09           or         r7,r1
        00006cda 09              ??         09h
        00006cdb 00              ??         00h
        00006cdc 08  0a           mov        0x8 ,r1
        00006cde 0a              ??         0Ah
        00006cdf 00              ??         00h
        00006ce0 09  0b           sld.b      0x9 [ep],r1
        00006ce2 0b              ??         0Bh
        00006ce3 00              ??         00h
        00006ce4 0a  0c           sld.h      0x14 [ep],r1
        00006ce6 0c              ??         0Ch
        00006ce7 00              ??         00h
        00006ce8 0b  0d           sst.w      0x14 [ep],r1
        00006cea 0d              ??         0Dh
        00006ceb 00              ??         00h
        00006cec 0c  0e  0e  00    addi       0xe ,r12 ,r1
        00006cf0 0d  0f  0f  00    ld.b       0xf [r13 ],r1
        00006cf4 0e  10           mov        r14 ,r2
        00006cf6 10              ??         10h
        00006cf7 00              ??         00h
        00006cf8 0f  11           or         r15 ,r2
        00006cfa 11              ??         11h
        00006cfb 00              ??         00h
        00006cfc 10  12           mov        -0x10 ,r2
        00006cfe 12              ??         12h
        00006cff 00              ??         00h
        00006d00 11  13           sld.b      0x11 [ep],r2
        00006d02 13              ??         13h
        00006d03 00              ??         00h
        00006d04 12  ff  05  08    ld.b       0x805 [r18 ],lp

v850-elf-objdump.exe -b binary -D v850.bin -m v850e2v3:

    6cb6:	00 02       	callt	0
    6cb8:	ff 01       	cmp	lp, r0
    6cba:	01 02       	callt	1
    6cbc:	00 02       	callt	0
    6cbe:	02 02       	callt	2
    6cc0:	01 03       	sld.b	1[ep], r0
    6cc2:	03 02       	callt	3
    6cc4:	02 04       	sld.h	4[ep], r0
    6cc6:	04 02       	callt	4
    6cc8:	03 05       	sst.w	r0, 4[ep]
    6cca:	05 02       	callt	5
    6ccc:	04 06 06 01 	addi	262, gp, r0
    6cd0:	05 07 07 01 	ld.b	263[r5], r0
    6cd4:	06 08       	mov	r6, r1
    6cd6:	08 00       	.short	0x0008
    6cd8:	07 09       	or	r7, r1
    6cda:	09 00       	.short	0x0009
    6cdc:	08 0a       	mov	8, r1
    6cde:	0a 00       	.short	0x000a
    6ce0:	09 0b       	sld.b	9[ep], r1
    6ce2:	0b 00       	.short	0x000b
    6ce4:	0a 0c       	sld.h	20[ep], r1
    6ce6:	0c 00       	.short	0x000c
    6ce8:	0b 0d       	sst.w	r1, 20[ep]
    6cea:	0d 00       	.short	0x000d
    6cec:	0c 0e 0e 00 	addi	14, r12, r1
    6cf0:	0d 0f 0f 00 	ld.b	15[r13], r1
    6cf4:	0e 10       	mov	r14, r2
    6cf6:	10 00       	.short	0x0010
    6cf8:	0f 11       	or	r15, r2
    6cfa:	11 00       	.short	0x0011
    6cfc:	10 12       	mov	-16, r2
    6cfe:	12 00       	.short	0x0012
    6d00:	11 13       	sld.b	17[ep], r2
    6d02:	13 00       	.short	0x0013
    6d04:	12 ff 05 08 	ld.b	2053[r18], lp

**Comment by mumbel** [comment]
This looks like .data, are you sure it's .text?

**Comment by GhidorahRex** [comment]
`ld.b` struck me as an odd one to not disassemble properly. I tested in a dummy program and `05 07 07 01` disassembles to `05 07 07 01      ld.b       0x107[tp],r0` which matches the objdump output. Everything else there looks like junk.

**Comment by rkoziolrk** [comment]
OK, I changed the language to the one from Ghidra and it worked, but I still have another issue in the same file:

Ghidra:

         00006d76 00 00           nop
         00006d78 00 01           or                      r0,r0
         00006d7a 00 00           nop
         00006d7c 20 f4           sld.h                   0x40[ep],ep
         00006d7e ff ff 00 f4      cmovf.s                 0x0,lp,lp,ep
         00006d82 ff              ??                      FFh
         00006d83 ff              ??                      FFh
         00006d84 40 fc           sld.h                   0x80[ep],lp
         00006d86 ff              ??                      FFh
         00006d87 ff              ??                      FFh
         00006d88 00 02           callt                   0x0
         00006d8a 00 00           nop
         00006d8c 22 f4           sld.h                   0x44[ep],ep
         00006d8e ff ff 02 f4      cmovf.s                 0x1,lp,lp,ep
         00006d92 ff              ??                      FFh
         00006d93 ff              ??                      FFh
         00006d94 42 fc           sld.h                   0x84[ep],lp
         00006d96 ff ff 00 00      rie                     0x1f,0xf
         00006d9a 00 00           nop


v850-elf-objdump.exe -b binary -D v850.bin -m v850e2v3:

    6d76:	00 00       	nop	
    6d78:	00 01       	or	r0, r0
    6d7a:	00 00       	nop	
    6d7c:	20 f4       	sld.h	64[ep], ep
    6d7e:	ff ff 00 f4 	cmovf.s	0, lp, lp, ep
    6d82:	ff ff 40 fc 	.long	0xfc40ffff
    6d86:	ff ff 00 02 	.long	0x0200ffff
    6d8a:	00 00       	nop	
    6d8c:	22 f4       	sld.h	68[ep], ep
    6d8e:	ff ff 02 f4 	cmovf.s	1, lp, lp, ep
    6d92:	ff ff 42 fc 	.long	0xfc42ffff
    6d96:	ff ff 00 00 	rie	
	...
    6db6:	00 00       	nop

**Comment by GhidorahRex** [comment]
Still looks like a data section

**Comment by rkoziolrk** [comment]
Could you tell me is it dbtrap, divh or data? (manually set to word)

         00000110 80 07 10 60      jr                      LAB_00006120
         00000114 40 f8           dw                      F840h
         00000116 40 f8           dw                      F840h
         00000118 40 f8           divh                    r0,lp
         0000011a 40 f8           dw                      F840h
         0000011c 40 f8           dw                      F840h
         0000011e 40 f8           dw                      F840h
         00000120 80 07 10 60      jr                      LAB_00006130
         00000124 40 f8           dw                      F840h
         00000126 40 f8           dw                      F840h
         00000128 40 f8           dw                      F840h
         0000012a 40 f8           dw                      F840h
         0000012c 40 f8           dw                      F840h
         0000012e 40 f8           dw                      F840h
         00000130 80 07 10 60      jr                      LAB_00006140

objdump:
```
     110:	80 07 10 60 	jr	0x6120
     114:	40 f8       	dbtrap	
     116:	40 f8       	dbtrap	
     118:	40 f8       	dbtrap	
     11a:	40 f8       	dbtrap	
     11c:	40 f8       	dbtrap	
     11e:	40 f8       	dbtrap	
     120:	80 07 10 60 	jr	0x6130
     124:	40 f8       	dbtrap	
     126:	40 f8       	dbtrap	
     128:	40 f8       	dbtrap	
     12a:	40 f8       	dbtrap	
     12c:	40 f8       	dbtrap	
     12e:	40 f8       	dbtrap	
     130:	80 07 10 60 	jr	0x6140
```

**Comment by GhidorahRex** [comment]
It's almost certainly data. Notice how the `jr` instructions are the same repeating data? I'm closing this, since there's no evidence that there's issues with the V850 disassembly here.

**Comment by kirya-dev** [comment]
Still not properly disassemble & decompiled :(
