### ISSUE TITLE
Is there a decompiler test suite/docs?

### ISSUE THREAD

**Issue by paulsapps** [NationalSecurityAgency/ghidra#695]
I'm interested in learning about the decompiler in order to improve it. However I can't see any in depth tests?

For example there is a test that constructs a "toy" program and decompiles it but the assert is only checking in the resulting string is not null or empty.

It would be nice to have a set of tests that pass in decompiler input and check the expected output. This could be done generating a C AST from the decompiler output and comparing with another AST generated from the expected output?

**Comment by dragonmacher** [comment]
Unfortunately, you are correct--there are not Decompiler tests in the repo.

I believe that successful contributions to the Decompiler are predicated upon having a thorough battery of tests available.  Hopefully we can provide these in the near future.

**Comment by ServedInSilence** [comment]
21
 

Sent: Monday, June 17, 2019 at 5:51 AM
