### ISSUE TITLE
Trackpad scrolling on macOS in Ghidra Help is way too fast

### ISSUE THREAD

**Issue by hippietrail** [NationalSecurityAgency/ghidra#6952]
**Describe the bug**
Scrolling in Ghidra's Help on Mac using the usual two-finger trackpad gesture is much faster than on other Mac apps, and so fast that it's easy to get lost rather than casually moving down as you're reading.

**To Reproduce**
1. Open Ghidra on macOS
2. Open Ghidra Help
3. Scroll up and down in the main help window using the two-finger gesture on the mousepad
4. Scroll up and down in any other app, or even other parts of Ghidra the same way.

**Expected behavior**
Ghidra Help should scroll at the same or similar speed as other apps and other parts of Ghidra, at a comfortable pace the user can follow.

**Screen recording**
https://github.com/user-attachments/assets/fdc36f07-53ef-4148-8f71-0cbd61e451eb  
(is it possible to embed a video here? couldn't get it to work)

**Environment (please complete the following information):**
 - OS: macOS 14.4 (23E214)
 - Java Version: 19.0.1
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
I've noticed this on my mac too

**Comment by dragonmacher** [comment]
@hippietrail I can reproduce this using the Flat Light or Flat Dark themes.   The Mac theme works as expected for me.   

Which theme are you using?

**Comment by hippietrail** [comment]
> @hippietrail I can reproduce this using the Flat Light or Flat Dark themes. The Mac theme works as expected for me.
> 
> Which theme are you using?

I'm not usually one for messing with themes but I actually did change themes at some point to "Flat Dark Theme" I believe. At some point Ghidra told me I'd changed the theme and couldn't modify the current one and it prompted me for a name to save it under, which is the one I'm actually using. But it seems to be based on Flat Dark and does suffer from help scrolling too fast.

**Comment by dragonmacher** [comment]
I'm investigating a fix for this issue.
