### ISSUE TITLE
`gradle prepdev` is causing a build failure

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#6962]
**Describe the bug**
`gradle prepdev` is now causing build failure on `Task :PyGhidra:installEditablePyGhidra`

**To Reproduce**
1. On Windows, setup your system to build Ghidra from the repo.
2. Run `gradle prepdev`.
3. See build failure.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: Temurin-21.0.3+9
 - Ghidra Version: 11.2
 - Ghidra Origin: locally built

**Comment by ryanmkurtz** [comment]
What version of Python do you have installed?

**Comment by Wall-AF** [comment]
> What version of Python do you have installed?

3.12.5

**Comment by ryanmkurtz** [comment]
What Python distribution is it?  Installed from python.org?  Windows App Store?  Something else?

**Comment by Wall-AF** [comment]
> What Python distribution is it? Installed from python.org? Windows App Store? Something else?

Don't remember!  Probably App Store.

**Comment by ryanmkurtz** [comment]
Someone else recently had a similar issue because they had a mingw64 version of python that gradle was picking up.  It's very hard to say without more information.

**Comment by Wall-AF** [comment]
C:\Users\...>where python
C:\Users\...\AppData\Local\Microsoft\WindowsApps\python.exe

**Comment by Wall-AF** [comment]
Path=C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot\\bin;C:\Gradle\gradle-8.5\bin;C:\PortableGit\bin;D:\Utilities;D:\Utilities\CMD;C:\Program Files\dotnet\;C:\Users\...\AppData\Local\Microsoft\WindowsApps;C:\Users\...\.dotnet\tools

**Comment by ryanmkurtz** [comment]
Did it make a `build/venv/` directory?  Can you list what is in `build/venv/Scripts`?

**Comment by Wall-AF** [comment]
> Did it make a `build/venv/` directory? Can you list what is in `build/venv/Scripts`?

Yes.
```
 Directory of D:\GIT_Sources\Ghidra\ghidra\build\venv\Scripts

27/09/2024  14:36    <DIR>          .
27/09/2024  14:36    <DIR>          ..
27/09/2024  14:36             2,070 activate
27/09/2024  14:36             1,008 activate.bat
27/09/2024  14:36            26,199 Activate.ps1
27/09/2024  14:36               393 deactivate.bat
27/09/2024  14:36           108,417 pip.exe
27/09/2024  14:36           108,417 pip3.12.exe
27/09/2024  14:36           108,417 pip3.exe
27/09/2024  14:36           270,104 python.exe
27/09/2024  14:36           258,840 pythonw.exe
               9 File(s)        883,865 bytes
```

**Comment by ryanmkurtz** [comment]
Oh, you might need to do a `gradle -I gradle/support/fetchDependencies.gradle`

**Comment by Wall-AF** [comment]
> Oh, you might need to do a `gradle -I gradle/support/fetchDependencies.gradle`

I do that every time I rebuild.  My build command was:
`CALL gradle --init-script gradle/support/fetchDependencies.gradle cleanEclipse eclipse prepDev -PeclipsePDE buildNatives %*`
until I removed `prepDev`.
And yes, Ive run it before I retried `gradle prepdev`.

**Comment by ryanmkurtz** [comment]
You might need to put some prints in `Ghidra/Features/PyGhidra/build.gradle` to try to help troubleshoot.  Or, you can try adding a `-x :PyGhidra:installEditablePyGhidra` to your build command to skip that task...at least for now.

**Comment by Wall-AF** [comment]
> You might need to put some prints in `Ghidra/Features/PyGhidra/build.gradle` to try to help troubleshoot. Or, you can try adding a `-x :PyGhidra:installEditablePyGhidra` to your build command to skip that task...at least for now.

I'm happy to debug, but can you say what and where?  I'm not a gradle person!!!

**Comment by ryanmkurtz** [comment]
Sure, the relevant parts of that gradle file are:

```groovy
// Install JPype into the development virtual environment
task installJPype(type: Exec) {
	dependsOn(":createPythonVirtualEnvironment")
	
	File depsDir = file("${DEPS_DIR}/PyGhidra")
	File binRepoDir = file("${BIN_REPO}/ExternalPyWheels")
	def dir = depsDir.exists() ? depsDir : binRepoDir
	
	commandLine "$PYTHON3_VENV", "-m", "pip", "install", "--no-index", "-f", "$dir", "JPype1"
}

// Install PyGhidra in editable mode to the development virtual environment
task installEditablePyGhidra(type: Exec) {
	dependsOn("installJPype")
	
	File depsDir = file("${DEPS_DIR}/PyGhidra")
	File binRepoDir = file("${BIN_REPO}/ExternalPyWheels")
	def dir = depsDir.exists() ? depsDir : binRepoDir

	commandLine "$PYTHON3_VENV", "-m", "pip", "install", "-e", "src/main/py", "--no-index", "-f", "$dir"
}

if (findPython3(false)) {
	rootProject.prepDev.dependsOn installEditablePyGhidra
}
```
The `dependOn` lines sets up the task dependencies.  I guess it would be useful to first check the `commandLine` in the failing task, to make sure it looks valid.  Maybe you can print it and try running it manually in a shell.  Something like:
```groovy
println "$PYTHON3_VENV $dir"
```
and then reforming that command.  Running it manually might reveal the real error.

**Comment by Wall-AF** [comment]
My original complete output is:
```
D:\GIT_Sources\Ghidra\ghidra>gradle prepDev

> Configure project :
Java: 21
Gradle: 8.5
Python3 command:  py (version 3.12)
Python3 pip version: 24.0
OS: Windows 11
Arch: amd64 (gradle: x86-64)
Using platform: win_x86_64
Searching for latest Visual Studio and required components...
  -> Installation Directory: C:\Program Files\Microsoft Visual Studio\2022\Community
  -> SDK Directory (default): C:\Program Files (x86)\Windows Kits\10\
  -> SDK Version (default): 10.0.19041.0
  -> SDK Version (override): N/A
Python3 command:  py (version 3.12)
Python3 pip version: 24.0

> Configure project :PyGhidra
Python3 command:  py (version 3.12)
Python3 pip version: 24.0

> Task :PyGhidra:installJPype
Looking in links: d:\GIT_Sources\Ghidra\ghidra\dependencies\PyGhidra
Requirement already satisfied: JPype1 in d:\git_sources\ghidra\ghidra\build\venv\lib\site-packages (1.5.0)
Requirement already satisfied: packaging in d:\git_sources\ghidra\ghidra\build\venv\lib\site-packages (from JPype1) (23.2)

> Task :PyGhidra:installEditablePyGhidra FAILED
Looking in links: d:\GIT_Sources\Ghidra\ghidra\dependencies\PyGhidra
Obtaining file:///D:/GIT_Sources/Ghidra/ghidra/Ghidra/Features/PyGhidra/src/main/py
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error

  pip subprocess to install build dependencies did not run successfully.
  exit code: 1

  [4 lines of output]
  Looking in links: d:\GIT_Sources\Ghidra\ghidra\dependencies\PyGhidra
  Processing d:\git_sources\ghidra\ghidra\dependencies\pyghidra\setuptools-68.0.0-py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
  ERROR: No matching distribution found for wheel
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PyGhidra:installEditablePyGhidra'.
> Process 'command 'D:\GIT_Sources\Ghidra\ghidra/build/venv/Scripts/python.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 7s
144 actionable tasks: 58 executed, 86 up-to-date
```

**Comment by ryanmkurtz** [comment]
Ok, I guess this is the real issue then:

```
Processing d:\git_sources\ghidra\ghidra\dependencies\pyghidra\setuptools-68.0.0-py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
  ERROR: No matching distribution found for wheel
```

Unfortunately my day must come to and end, but I can continue trouble shooting that first thing Monday morning.  Perhaps we need a newer version of setuptools installed into the virtual environment?  I'll have to play with it.  Sorry for the inconvenience.

**Comment by ryanmkurtz** [comment]
In the meantime, you can edit this `if` to remove the `prepdev` dependency if you want to move forward:

```groovy
if (findPython3(false)) {
	rootProject.prepDev.dependsOn installEditablePyGhidra
}
```

**Comment by Wall-AF** [comment]
Mmm, don't see the debug line!  (I placed `println "$PYTHON3_VENV $dir"` inside the task, just before the line starting `commandLine ...`.

**Comment by ryanmkurtz** [comment]
It's ok, I think that `setuptools` thing is the issue.  I'll have to try to reproduce it on my end probably.

**Comment by Wall-AF** [comment]
> Ok, I guess this is the real issue then:
> 
> ```
> Processing d:\git_sources\ghidra\ghidra\dependencies\pyghidra\setuptools-68.0.0-py3-none-any.whl
>   ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
>   ERROR: No matching distribution found for wheel
> ```
> 
> Unfortunately my day must come to an end, but I can continue trouble shooting that first thing Monday morning. Perhaps we need a newer version of setuptools installed into the virtual environment? I'll have to play with it. Sorry for the inconvenience.

I'm busy sailing in the RS Venture Connect World Championship starting tomorrow, I'll be free again in  week!

**Comment by Wall-AF** [comment]
> Mmm, don't see the debug line! (I placed `println "$PYTHON3_VENV $dir"` inside the task, just before the line starting `commandLine ...`.

Duh!  Found it, ran it and the command/results are:
```
D:\GIT_Sources\Ghidra\ghidra>build\venv\Scripts\python.exe D:\GIT_Sources\Ghidra\ghidra\dependencies\PyGhidra
D:\GIT_Sources\Ghidra\ghidra\build\venv\Scripts\python.exe: can't find '__main__' module in 'D:\\GIT_Sources\\Ghidra\\ghidra\\dependencies\\PyGhidra
```

**Comment by Wall-AF** [comment]
I ran it again (with the parameters this time) and below is the results:
```
D:\GIT_Sources\Ghidra\ghidra>cd D:\GIT_Sources\Ghidra\ghidra\Ghidra\Features\PyGhidra
D:\GIT_Sources\Ghidra\ghidra\Ghidra\Features\PyGhidra>D:\GIT_Sources\Ghidra\ghidra/build/venv/Scripts/python.exe -m pip install -e src/main/py --no-index -f D:\GIT_Sources\Ghidra\ghidra\dependencies\PyGhidra
Looking in links: d:\GIT_Sources\Ghidra\ghidra\dependencies\PyGhidra
Obtaining file:///D:/GIT_Sources/Ghidra/ghidra/Ghidra/Features/PyGhidra/src/main/py
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Looking in links: d:\GIT_Sources\Ghidra\ghidra\dependencies\PyGhidra
      Processing d:\git_sources\ghidra\ghidra\dependencies\pyghidra\setuptools-68.0.0-py3-none-any.whl
      ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
      ERROR: No matching distribution found for wheel
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by TheDauntless** [comment]
As additional info, it's failing for me on MacOS with python installed via brew:

```
➜  ghidra git:(master) gradle prepdev eclipse buildNatives


> Configure project :
Java: 23
Gradle: 8.10.2
Python3 command:  python3 (version 3.12)
Python3 pip version: 24.2
OS: Mac OS X
Arch: aarch64
Using platform: mac_arm_64
Python3 command:  python3 (version 3.12)
Python3 pip version: 24.2

> Configure project :Debugger-agent-dbgeng
WARNING: dbgmodel.tlb omitted from ghidradbg python package

> Configure project :PyGhidra
Python3 command:  python3 (version 3.12)
Python3 pip version: 24.2

> Task :PyGhidra:installJPype
Looking in links: /Users/jeroen/Projects/ghidra/dependencies/PyGhidra
Requirement already satisfied: JPype1 in /Users/jeroen/Projects/ghidra/build/venv/lib/python3.12/site-packages (1.5.0)
Requirement already satisfied: packaging in /Users/jeroen/Projects/ghidra/build/venv/lib/python3.12/site-packages (from JPype1) (23.2)

> Task :PyGhidra:installEditablePyGhidra FAILED
Looking in links: /Users/jeroen/Projects/ghidra/dependencies/PyGhidra
Obtaining file:///Users/jeroen/Projects/ghidra/Ghidra/Features/PyGhidra/src/main/py
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Looking in links: /Users/jeroen/Projects/ghidra/dependencies/PyGhidra
      Processing /Users/jeroen/Projects/ghidra/dependencies/PyGhidra/setuptools-68.0.0-py3-none-any.whl
      ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
      ERROR: No matching distribution found for wheel
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PyGhidra:installEditablePyGhidra'.
> Process 'command '/Users/jeroen/Projects/ghidra/build/venv/bin/python3'' finished with non-zero exit value 1
```
I tried updating setuptools in the venv but that didn't work:

```
pip install setuptools
Collecting setuptools
  Downloading setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Downloading setuptools-75.1.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 15.5 MB/s eta 0:00:00
Installing collected packages: setuptools
Successfully installed setuptools-75.1.0
```

I also specifically tried version 68, but the error stays the same.

**Comment by TheDauntless** [comment]
If you manually download the [wheel distribution](https://pypi.org/project/wheel/#files) and put it in the `dependencies/PyGhidra` folder the build works.

The pip command is configured to not download from additional repositories (which is probably intentional), but then why isn't wheel packed with the project?

```
full command: /Users/jeroen/Projects/ghidra/build/venv/bin/python3 /Users/jeroen/Projects/ghidra/build/venv/lib/python3.12/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /private/var/folders/xh/vcbktqr91dj_rx3yr_7rr0gr0000gn/T/pip-build-env-libbm7vr/overlay --no-warn-script-location --disable-pip-version-check -v --no-binary :none: --only-binary :none: --no-index --find-links /Users/jeroen/Projects/ghidra/dependencies/PyGhidra -- setuptools wheel
```

**Comment by ryanmkurtz** [comment]
@Wall-AF can you test out this change?

```diff
+++ b/gradle/support/fetchDependencies.gradle
@@ -188,7 +188,7 @@ ext.deps = [
                name: "wheel-0.37.1-py2.py3-none-any.whl",
                url: "https://files.pythonhosted.org/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl",
                sha256: "4bdcd7d840138086126cd09254dc6195fb4fc6f01c050a1d7236f2630db1d22a",
-               destination: file("${DEPS_DIR}/Debugger-rmi-trace/")
+               destination: [file("${DEPS_DIR}/Debugger-rmi-trace/"), file("${DEPS_DIR}/PyGhidra/")]
        ],
        [
                name: "Pybag-2.2.12-py3-none-any.whl",
```

**Comment by ryanmkurtz** [comment]
> PS: After importing the project into Eclipse, I had to manually import the run configuration (File > Import > Run configuration) from ./Ghidra/Features/Base/.launch. This isn't mentioned in the advanced startup guide.

@TheDauntless You shouldn't have had to do this.  Eclipse often does not initially put the run configuration in the favorites menu until the first time you run it...you have to dig into the run configurations settings to run it for the first time.  But, you are saying it wasn't in there either?  Which specific run configuration are you talking about?

**Comment by ryanmkurtz** [comment]
> @Wall-AF can you test out this change?

It fixed the issue for me, so I pushed it.  We can reopen if you still have the issue.

**Comment by TheDauntless** [comment]
@ryanmkurtz  The proposed fix works for me.

I've downloaded a fresh clone and used a fresh eclipse workspace. This is what I get after importing:

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/86c70465-4162-4ed6-bea5-c61f51c460b3">

**Comment by ryanmkurtz** [comment]
Can you check your filters with that little filter icon?

**Comment by TheDauntless** [comment]
@ryanmkurtz 
There were two filters active, but disabling them didn't help:
<img width="1551" alt="image" src="https://github.com/user-attachments/assets/86a31534-2842-4585-b80f-5ea490f91be6">

I've tried a bunch more times, and the only thing that seems to work is closing the workspace and opening it again. Seems like an eclipse bug, so up to you if you want to include it in the documentation.

**Comment by Wall-AF** [comment]
> @Wall-AF can you test out this change?
> 
> ```diff
> +++ b/gradle/support/fetchDependencies.gradle
> @@ -188,7 +188,7 @@ ext.deps = [
>                 name: "wheel-0.37.1-py2.py3-none-any.whl",
>                 url: "https://files.pythonhosted.org/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl",
>                 sha256: "4bdcd7d840138086126cd09254dc6195fb4fc6f01c050a1d7236f2630db1d22a",
> -               destination: file("${DEPS_DIR}/Debugger-rmi-trace/")
> +               destination: [file("${DEPS_DIR}/Debugger-rmi-trace/"), file("${DEPS_DIR}/PyGhidra/")]
>         ],
>         [
>                 name: "Pybag-2.2.12-py3-none-any.whl",
> ```

By running the command `gradle -I gradle\support\fetchDependencies.gradle` first, `gradle prepDev` now works.  Thanks.
