### ISSUE TITLE
Import failure may be due to missing opinion for "PeLoader"

### ISSUE THREAD

**Issue by 0xh3xa** [NationalSecurityAgency/ghidra#6966]
Describe the bug
`
ERROR NOTE: Import failure may be due to missing opinion for "PeLoader". If so, please contact Ghidra team for assistance. (HeadlessAnalyzer)  `

To Reproduce

` ./analyzeHeadless  ~/reverse project -import binaries -loader PeLoader -loader-loadSystemLibraries true`

Environment:

OS: any Linux
Java Version: 17
Ghidra Version: 11.2
Ghidra Origin: official build

**Comment by ryanmkurtz** [comment]
Are there non-PE files in that `binaries` directory?

**Comment by 0xh3xa** [comment]
@ryanmkurtz they are PE files
