### ISSUE TITLE
Missing run files in release 11.2

### ISSUE THREAD

**Issue by ReversingWithMe** [NationalSecurityAgency/ghidra#6967]
**Describe the bug**
Ghidra 11.2 release file does not contain ghidraRun in root directory, only a LICENSE file

Did the entrypoint get moved into support now?

**Comment by mumbel** [comment]
Cannot reproduce.  Id verify your zip size/hash matches

**Comment by ReversingWithMe** [comment]
When downloading zip, I had corrupted it somehow, good call mumbel!
