### ISSUE TITLE
Allow "backspace" key to be bound

### ISSUE THREAD

**Issue by teropentis64** [NationalSecurityAgency/ghidra#6972]
**Is your feature request related to a problem? Please describe.**
The default macOS keyboard (Magic Keyboard) doesn't have "delete" key.

I can understand that many people use third-party keyboards on Apple computers but if Ghidra wants to conform to mac application design it should be changed to backspace (even better, cmd+backspace). The backspace key is treated as the default "delete" key across macOS applications.

Currently, we can't assign anything to backspace key as it's treated as "remove key binding" key. Maybe just add button  to UI to clear key binding and allow users to assign any key they want to anything. The same goes for enter key, which we could map to "navigate forward".

![bck](https://github.com/user-attachments/assets/4e7031d7-3a49-44d1-abd9-1b5ef329d2c1)

**Comment by ryanmkurtz** [comment]
The "delete" key should just be `fn + delete`.  I am able to bind to this.  It sounds like you are just asking to be able to bind the backspace key, regardless of platform.  Correct?

**Comment by teropentis64** [comment]
Yes, I'm familiar with fn - delete key but "unlocking" backspace to binding would (in my opinion) benefit Ghidra overall.
