### ISSUE TITLE
Build does not working

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#698]
**Describe the bug**
The building of Ghidra failed due to missing Jyton configuration. Note, I use gradlew script to run 5.0 version, but I believe this in no way could cause issue. If 

**To Reproduce**
1. Clone Ghidra on new computer
2. Follow instructions in DevGuide.md to download dependencies and set repositories.
3. run `gradlew` from the root of the project.

**Expected behavior**
Build should work without errors. and documentation should have steps for setting up Jyton

**Screenshots**
```
* What went wrong:
A problem occurred evaluating project ':Python'.
> Could not resolve all files for configuration ':Python:jython'.
   > Cannot resolve external dependency org.python:jython-standalone:2.7.1 because no repositories are defined.
     Required by:
         project :Python
```

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.02
 - Ghidra Version: cafbb77db0a2120c529aef45d2d6bc47fa1edc29

**Additional context**

**Comment by kant2002** [comment]
Sorry to bother. Figure out gradlew magic. Has to read more RTFM

**Comment by OrenGitHub** [comment]
I'm having the same issue exactly. How was it solved?

**Comment by OrenGitHub** [comment]
Just to make this thread useful in the future, here is what solved it for me:
Instead of just
```
$ gradle
```
I ran:
```
$ gradle --init-script gradle/support/fetchDependencies.gradle init
```

**Comment by nauliajati** [comment]
> Just to make this thread useful in the future, here is what solved it for me:
> Instead of just
> 
> ```
> $ gradle
> ```
> 
> I ran:
> 
> ```
> $ gradle --init-script gradle/support/fetchDependencies.gradle init
> ```

Thanks, you helped me a lot.
