### ISSUE TITLE
Option ROM Loader

### ISSUE THREAD

**Issue by bog-dan-ro** [NationalSecurityAgency/ghidra#6986]
It will be great if ghidra will be able to read the GPU's rom headers, this way it can provide a great decompile experience.

Legacy PCI Expansion ROM Header:
```
struct pci_expansion_rom_header {
    uint16_t signature;        // 0x55AA
    uint8_t  size;             // Size of the ROM image in 512-byte blocks
    uint8_t  initialization[3];// Initialization code
    uint16_t pci_data_offset;  // Offset to PCI Data Structure
    uint16_t pnp_data_offset;  // Offset to PnP Expansion Header (optional)
};

struct pci_data_structure {
    uint32_t signature;        // "PCIR" (0x52494350)
    uint16_t vendor_id;
    uint16_t device_id;
    uint16_t device_list_offset;// Pointer to list of supported devices
    uint16_t pci_data_structure_length;
    uint8_t  pci_data_structure_revision;
    uint8_t  class_code[3];
    uint16_t image_length;     // Length of the entire ROM image in 512-byte blocks
    uint16_t revision_level;
    uint8_t  code_type;        // Type of code in this ROM (0 = x86, 1 = Open Firmware)
    uint8_t  last_image_indicator;
    uint16_t max_runtime_image_length;
};
```
UEFI PCI Expansion ROM Header:
```
struct efi_pci_expansion_rom_header {
    struct pci_expansion_rom_header legacy_header;
    struct pci_data_structure pci_data_structure;
    uint16_t efi_signature;    // 0x0EF1
    uint16_t efi_subsystem;
    uint16_t efi_machine_type;
    uint16_t compression_type;
    uint8_t  reserved[8];
    uint16_t efi_image_header_offset;
    uint16_t pcir_offset;
};

struct efi_image_header {
    uint32_t signature;        // "PE\0\0" or "TE\0\0" for compressed images
    uint16_t machine;
    uint16_t number_of_sections;
    uint32_t time_date_stamp;
    uint32_t pointer_to_symbol_table;
    uint32_t number_of_symbols;
    uint16_t size_of_optional_header;
    uint16_t characteristics;
    // ... more fields follow in the actual PE/COFF header
};
```

**Comment by ryanmkurtz** [comment]
Something like this would typically be done by a Ghidra `Loader`.  Are you using a 3rd party loader for this type of binary?

**Comment by bog-dan-ro** [comment]
> Something like this would typically be done by a Ghidra `Loader`. Are you using a 3rd party loader for this type of binary?

Nope, I'm using the official ghidra 11.1.2

**Comment by ryanmkurtz** [comment]
This is pretty niche...have you considered just making the structures in Ghidra and saving them off for your future projects?

**Comment by bog-dan-ro** [comment]
I think a better subject for this task is `Option ROM loader` instead of `Video Cards BIOS headers` as `Option ROMs` are not limited to video cards only, but they are found in mostly all PCI[e] cards (network, sound, etc.) . 
Considering that this code is executed by the BIOS when the computer starts, it's quite a security concern. IMHO, this is the main reason why ghidra should have proper suport for it.

Deompiling legacy Option ROMs is quite easy, you need to import it as 16 bit x86 real mode, go to address 0000:0003 and start the decompilation (the PCIR header is not important).

The problem is with modern Option ROMs (EFI) which might be compressed. We need to parse the COFF header to identify the architecture, entry point, etc, but that's not a problem as ghidra already knows how to parse `PE32/PE32+/COFF`  bins.

P.S. There is also a third Option ROM code type (Open Firmware) which uses `FCode (based on Forth language)` which is not handled at all by ghidra, but that's not a big issue as Open Firmware it's pretty much dead.

**Comment by ryanmkurtz** [comment]
Ok, so you are asking for an Option ROM Loader. Can you please link in the spec for the binary file format, and maybe include some samples?

**Comment by bog-dan-ro** [comment]
The PCI specs are not free, but there are many other docs and implementations out there which contains that info:
https://github.com/tianocore/edk2/tree/master/BaseTools/Source/C/EfiRom
https://github.com/tianocore/edk2/blob/master/MdePkg/Include/IndustryStandard/Pci22.h
https://github.com/tianocore/edk2/blob/master/MdePkg/Include/IndustryStandard/Pci30.h

https://uefi.org/sites/default/files/resources/UEFI_Spec_2_1.pdf (`13.4.2 PCI Option ROMs` page 577).

I forgot to mention that besides the machine dependent code, the EFI also supports EBC (see https://uefi.org/specs/UEFI/2.10/22_EFI_Byte_Code_Virtual_Machine.html ) which it seems it not supported by ghidra.

For samples any modern rom should do, I attached a couple of video cards [roms](https://github.com/user-attachments/files/17258069/roms.tar.gz) for you:
* `rx-7900-xt.rom` is one of the most complex as it contains the legacy and also a compressed efi rom.
* `xvr100.rom` is the least important as it contains the sun xvr 100 video card, which uses FCode

**Comment by ryanmkurtz** [comment]
Thanks, I'll bring this up to the team.

**Comment by ryanmkurtz** [comment]
Our team discussed this feature request.  We think it would be a cool thing to add, but there is just not demand for it to justify putting resources on it at the moment.  If more people start expressing a need for it, we might reconsider its priority.  In the meantime, it's a perfect candidate for a 3rd party Ghidra Extension, if you or someone else in the community is interested in working on it.

**Comment by cyrozap** [comment]
Unless I'm mistaken, I believe the third-party [Ghidra Firmware Utilities extension](https://github.com/al3xtjames/ghidra-firmware-utils) already has most if not all of the requested functionality.

**Comment by bog-dan-ro** [comment]
@cyrozap you're right, it has most of the features.
