### ISSUE TITLE
Batch import Excel app fails on Macos

### ISSUE THREAD

**Issue by teta2k** [NationalSecurityAgency/ghidra#6989]
**Describe the bug**
On a Macbook M1, cannot import the Microsoft Excel app (neither aarch64, nor x86-64).
```
ERROR | (ImportBatchTask) Import failed for AARCH64-64-cpu0x0 java.io.IOException: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.symbol.Namespace.isExternal()" because "namespace" is null
-- | -- | -- | --
  |   |   | at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:120)
  |   |   | at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:825)
  |   |   | at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
  |   |   | at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:129)
  |   |   | at ghidra.plugins.importer.tasks.ImportBatchTask.doImportApp(ImportBatchTask.java:151)
  |   |   | at ghidra.plugins.importer.tasks.ImportBatchTask.doImportBatchGroup(ImportBatchTask.java:127)
  |   |   | at ghidra.plugins.importer.tasks.ImportBatchTask.doBatchImport(ImportBatchTask.java:116)
  |   |   | at ghidra.plugins.importer.tasks.ImportBatchTask.run(ImportBatchTask.java:91)
  |   |   | at ghidra.util.task.Task.monitoredRun(Task.java:134)
  |   |   | at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
  |   |   | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  |   |   | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  |   |   | at java.base/java.lang.Thread.run(Thread.java:1583)
  |   |   | Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.symbol.Namespace.isExternal()" because "namespace" is null
  |   |   | at ghidra.program.database.external.ExternalLocationDB.setName(ExternalLocationDB.java:255)
  |   |   | at ghidra.app.util.bin.format.macho.commands.chained.DyldChainedFixups.fixupExternalLibrary(DyldChainedFixups.java:196)
  |   |   | at ghidra.app.util.bin.format.macho.commands.chained.DyldChainedFixups.fixupChainedPointers(DyldChainedFixups.java:167)
  |   |   | at ghidra.app.util.opinion.MachoProgramBuilder.processChainedFixups(MachoProgramBuilder.java:885)
  |   |   | at ghidra.app.util.opinion.MachoProgramBuilder.build(MachoProgramBuilder.java:145)
  |   |   | at ghidra.app.util.opinion.MachoProgramBuilder.buildProgram(MachoProgramBuilder.java:122)
  |   |   | at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:110)
  |   |   | ... 12 more
```
**To Reproduce**
1) New project
2) Batch import /Applications/Microsoft Excel.app/Contents/MacOS/Microsoft Excel.

**Expected behavior**
Import should work, like it does with other Office apps.

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: macos 15.0
 - Java Version: 21.0.2
 - Ghidra Version: 11.2, 11.1
 - Ghidra Origin: official GitHub distro

**Additional context**

**Comment by ryanmkurtz** [comment]
I made a change for the upcoming Ghidra 11.2.1 release that will allow you to get past this particular error.  It doesn't solve the root of the issue, but without the binary it's the best I can do for now.

**Comment by teta2k** [comment]
@ryanmkurtz Thanks, I appreciate it!

**Comment by 0xbf00** [comment]
@ryanmkurtz In case you'd like to debug this issue further, I noticed the same issue happening with `Alfred Framwork` from `Alfred.app`, version 5.5.1. You can download the `dmg` file free of charge here: https://cachefly.alfredapp.com/Alfred_5.5.1_2273.dmg

I only tested `Alfred 5.app/Contents/Frameworks/Alfred Framework.framework/Versions/A/Alfred Framework`, which is affected by the same error (same stacktrace).

**Comment by ryanmkurtz** [comment]
Thank you, I'll look at it today!

**Comment by ryanmkurtz** [comment]
I found the cause of the issue...one of the external programs had a space in it and that wasn't being handled consistently.  Should be good to go now...thanks!
