### ISSUE TITLE
Support building of Ghidra using VS2019

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#699]
**Is your feature request related to a problem? Please describe.**
I cannot build Ghidra without having installed VS2017

**Describe the solution you'd like**
Support for both VS2017 and VS2019

**Additional context**
I may fix that and send PR for suporting both scenarios.

**Comment by ghidra1** [comment]
I suspect you will be able to build by making a few quick changes:
- modify GPL/nativeBuildProperties.gradle to reflect VS2019 paths
- updating the PDB Visual Studio solution/project files using VS 2019 (see Ghidra/Features/PDB/src/pdb/pdb.sln)
- If you will be targeting support for Windows 7 or 8 you will need to download the [Windows 8.1 SDK](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive)

**Comment by kant2002** [comment]
@ghidra1 can you take a look at the PR? Would be glad to hear any feedback

**Comment by kant2002** [comment]
Ping @ghidra1

**Comment by ryanmkurtz** [comment]
Responded [here](https://github.com/NationalSecurityAgency/ghidra/pull/730#issuecomment-511822243).
