### ISSUE TITLE
utility.applicaiton namespace misspelled

### ISSUE THREAD

**Issue by backerman** [NationalSecurityAgency/ghidra#7]
**Describe the bug**
Ghidra contains a namespace `utility.applicaiton`

**To Reproduce**
1. Look in `Ghidra/Framework/Utility/Lib/utility/applicaiton`.
2. Note that it exists and that the correct spelling is "application".

**Expected behavior**
Namespace should be spelled correctly.

**Environment (please complete the following information):**
 - OS: Arch Linux amd64
 - JDK: OpenJDK 11.0.2

**Comment by ryanmkurtz** [comment]
This will be fixed in our next release.
