### ISSUE TITLE
在使用ghidraRun.bat启动ghidra后ghidraRun.bat出错

### ISSUE THREAD

**Issue by 867315310** [NationalSecurityAgency/ghidra#7005]
在使用ghidraRun.bat启动ghidra后ghidraRun.bat提示“......，你可以使用CTRL+d关闭此终端”，但实际上CTRL+d无法关闭此终端，只能用任务管理器结束任务。

**Comment by ryanmkurtz** [comment]
Can you please repost in English?  We cannot read enough of this to understand your issue.

**Comment by 867315310** [comment]
After using ghidraRun.bat to start ghidra, it prompts "..., you can use CTRL+d to close this terminal". However, in reality, CTRL+d cannot close this terminal and can only end the task using the task manager.

**Comment by topia** [comment]
I replied on the newer issue #7384.
