### ISSUE TITLE
Misleading application logs regarding Java decompilation

### ISSUE THREAD

**Issue by leveled** [NationalSecurityAgency/ghidra#701]
**Describe the bug**
In the application logs some DEBUG lines are written indicating that JAD is not present so Java Decompilation features are not available. However, I do not believe JAD is used for Java Decompilation in Ghidra at the moment, as it seems to work fine without it. If some features are gated behind JAD, I would suggest adopting another Java decompiler as JAD is deprecated.

```
2019-06-19 08:06:16 DEBUG (JadProcessWrapper) os/osx64/jad does not exist
2019-06-19 08:06:16 DEBUG (JadProcessWrapper) Java Decompiler (JAD) not present, some features not available until installed in:
2019-06-19 08:06:16 DEBUG (JadProcessWrapper)   Ghidra/Features/FileFormats/os/[your_os]/jad[.exe]
```

**To Reproduce**
1. Open up an APK (such as [this](https://github.com/markushi/android-ui/blob/master/example.apk)).
2. Observe the application.log file in ~/.ghidra/ghidra_version/
3. Note the debugging information, Java decompilation of extracted files should still occur normally

**Expected behavior**
Debugging statements should either be removed, or there should be further documentation regarding what is gated behind JAD. 

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Java Version: 12.0.1
 - Ghidra Version: 9.0.4

**Comment by dev747368** [comment]
JAD is required for a few right-click actions in the file system browser: export jar to eclipse, decompile jar, and opening a .class file as a "filesystem" that turns it into a .java text file.
