### ISSUE TITLE
In the Script Manager window the "In T..." and "Status" column headers cannot be resized

### ISSUE THREAD

**Issue by hippietrail** [NationalSecurityAgency/ghidra#7013]
**Describe the bug**
Other column headers can be resized by click-dragging with the mouse, but not the two leftmost columns. I don't even know what the full name of the "In T..." column is.

**To Reproduce**
1. Go to Script Manager
2. Hover over separators between the left two pairs of column headers

**Expected behavior**
The mouse pointer icon should change to the resizing icon and let you click and drag on the separators to move them left and right. As the other separators allow.

**Screen shots**
https://github.com/user-attachments/assets/40b1dc7c-ca59-41da-86c5-c6723b0274c0

**Environment (please complete the following information):**
 - OS: macOS 14.4
 - Java Version: 23
 - Ghidra Version: 11.2
 - Ghidra Origin: official GitHub distro
 
**Additional context**
I tried every theme and it makes no difference.

**Comment by ryanmkurtz** [comment]
Duplicate of #6918
