### ISSUE TITLE
Renaming structure fields repeatedly moves focus to adjacent cell

### ISSUE THREAD

**Issue by huettenhain** [NationalSecurityAgency/ghidra#703]
**Description**
When editing the name of a variable in the structure editing dialog using the keyboard shortcut (<kbd>F2</kbd> in the illustration below), performing the same operation again causes the focus to switch to the data type field and vice versa. This happens even though the same cell remains highlighted:

![struct_rename](https://user-images.githubusercontent.com/11869704/59808671-86f38c00-92fd-11e9-808c-cdaad4cd70f6.gif)

The expected behavior would be that the focus does not change at all.

**Environment (please complete the following information):**
 - OS: Windows 10, Version 1809, OS Build 17763.437
 - Java Version: 11.0.2
 - Ghidra Version: 9.0.2

**Comment by huettenhain** [comment]
Dear @ryanmkurtz, unfortunately I am still seeing a similar issue in v9.1-PUBLIC:

![problem](https://user-images.githubusercontent.com/11869704/68592933-861deb00-0494-11ea-921a-633db97220dd.gif)

**Comment by dragonmacher** [comment]
I fixed the case you described originally. 

I verified the second case you have shown is still broken.  Thanks for the effective screenshot.

**Comment by huettenhain** [comment]
The least I can do really, Thank you (and the remaining team) for this amazing tool and your tireless efforts to handle requests and bug reports.
