### ISSUE TITLE
RTTI Analyzer stops processing vftable with references to the middle for some reference types

### ISSUE THREAD

**Issue by hiimjustin000** [NationalSecurityAgency/ghidra#7045]
**Describe the bug**
When it comes to processing virtual function tables (vftables, or vtables), at least on Windows binaries, Ghidra stops as soon as there is a label in the middle.

**To Reproduce**
1. Analyze a binary with a virtual function table
2. Scroll down to the table
3. See error

**Expected behavior**
The whole table would be processed.

**Screenshots**
![image](https://github.com/user-attachments/assets/a557080d-3110-464d-a7f4-44b83e8af134)

**Environment (please complete the following information):**
 - OS: Windows 11 23H2 (10.0.22631.4317)
 - Java Version: 21.0.4
 - Ghidra Version: 11.2
 - Ghidra Origin: GitHub

**Additional context**
This gets way too annoying, as I cannot extend the table for the missing functions without it giving a "Data type too large" error.

**Comment by hiimjustin000** [comment]
I have updated the title to clarify that this is RecoverClassesFromRTTIScript's doing, as I have just found this out.

**Comment by hiimjustin000** [comment]
What is happening is that there are function pointers that span the entire length of the vftable, but due to there being labels thrown in the middle, RecoverClassesFromRTTIScript thinks it's the end of the table.

You could probably make an option to go past anyway, but I don't know if there is anything in Windows PE that signals the end of a vftable.

**Comment by ghidra007** [comment]
> What is happening is that there are function pointers that span the entire length of the vftable, but due to there being labels thrown in the middle, RecoverClassesFromRTTIScript thinks it's the end of the table.
> 
> You could probably make an option to go past anyway, but I don't know if there is anything in Windows PE that signals the end of a vftable.

I understand, thanks. Can you look at one of the tables before running the script and see if the function pointers past the reference are included in the array that the rtti analyzer makes or if that also only includes ones up to the reference?

**Comment by hiimjustin000** [comment]
What reference?

**Comment by ghidra007** [comment]
> What reference?

I mean past the label in the middle.

**Comment by ghidra007** [comment]
> It only includes ones up to the reference.

Thanks.

**Comment by ghidra007** [comment]
@hiimjustin000 Can you go to address 140535fb0 in your example above then right mouse on the address and choose References -> Show References To Address and share an image of the resulting table here? Apparently there is some smarts for allowing certain reference types in the middle of these tables but for some reason isn't working in your case. Thanks!

**Comment by hiimjustin000** [comment]
Update: I got a new version of this binary, and a new analysis points to the possibility that this may have been somewhat fixed in an 11.1.x or 11.2.x version of Ghidra.

It's better at this now, but this still happens from time to time.

Here's the image you asked for:
![image](https://github.com/user-attachments/assets/c8277632-048c-4289-959d-f53ac8090e0e)

**Comment by ghidra007** [comment]
> Update: I got a new version of this binary, and a new analysis points to the possibility that this may have been somewhat fixed in an 11.1.x or 11.2.x version of Ghidra.
> 
> It's better at this now, but this still happens from time to time.
> 
> Here's the image you asked for, from the old binary: ![image](https://private-user-images.githubusercontent.com/52604018/386796318-c8277632-048c-4289-959d-f53ac8090e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDYxMTUsIm5iZiI6MTczMTk0NTgxNSwicGF0aCI6Ii81MjYwNDAxOC8zODY3OTYzMTgtYzgyNzc2MzItMDQ4Yy00Mjg5LTk1OWQtZjUzYWM4MDkwZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE2MDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNmUxN2I3ZDUwYWVhZWE2ZWJhN2EwNjg3MGFkODYwZGM4ZGJlY2MxYjIxMmE4MDU0OWE4YjFiNjJmNjU1NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iCbt2ArZeqOmli_azBHrJZ9CDN3CJmR1Y-zt95LN7rg)

I'm sorry, I thought you were using a new analysis in 11.2. The pictured one should be allowed in the middle of a vftable. It sounds like it is now with analysis in 11.2. I am going to close the ticket but if you find any examples that are still happening with new analysis please reopen the ticket and share the reference type information to the address where the table stops. Thanks!
