### ISSUE TITLE
Eclipse GhidraDev: Run Configuration not installing plugin

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#7047]
My normal workflow when testing my plugin is to run them via GhidraDev's run configuration
![image](https://github.com/user-attachments/assets/f8e66157-c937-43e3-a0c0-46570035757c)

This would normally run the linked Ghidra with the plugin 'temporarily' loaded. This has suddenly broken for me - ghidra runs but extension is not loaded. Clearing ~/.config and other directories has not worked. 

The plugin can still be built and loaded into Ghidra as normal. Installing the plugin causes the Run configuration to raise an error, so I am flummoxed as to why things are breaking. How do I go about debugging this?

I am using the public release of 11.2 and the GhidraDev in the Extensions/Eclipse folder

**Comment by sad-dev** [comment]
I managed to fix it (for now). Referencing a new module project, I replaced several entries in ``.classpath`` :

Old:
```<classpathentry kind="src" path="src/main/java"/>```
New:
```<classpathentry kind="src" output="bin/main" path="src/main/java"/>```

**Comment by antoniovazquezblanco** [comment]
I am also suffering this... I am wondering if this should be kept open until the devs confirm they are aware of this...

**Comment by ryanmkurtz** [comment]
Can you include the error here?

**Comment by antoniovazquezblanco** [comment]
No errors are shown. When the run button is hit, the instance of Ghidra does not load any of the debugged code...
This is solved by changing entries in `.classpath`:

Old:
`<classpathentry kind="src" path="src/main/java"/>`
New:
`<classpathentry kind="src" output="bin/main" path="src/main/java"/>`

**Comment by ryanmkurtz** [comment]
I'm not sure why this is happening.  Are you all running `Ghidra 11.2` with `GhidraDev 4.0.0.202408290705`?  Here is the code that sets up the new project, and you can see it setting the output folder for each source folder.  Explicitly setting the output folder is a somewhat recent change I put in though.  Were your Eclipse projects perhaps already created by an older version of GhidraDev?

https://github.com/NationalSecurityAgency/ghidra/blob/710e2a8ba3a2dc9e3af967297259a9ddad49d0a7/GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin/src/main/java/ghidradev/ghidraprojectcreator/utils/GhidraModuleUtils.java#L65-L126

**Comment by ryanmkurtz** [comment]
Thank you.  If you could also include the entire `.classpath` file, that would be helpful too.  I don't expect Ghidra 11.2.1 to make any difference for this issue.

**Comment by John-Zetier** [comment]
I am on Ghidra 11.2 and am using GhidraDev version 4.0.0.202408290705. The plugin I am working on was also created by a previous version of Ghidra.

**Comment by ryanmkurtz** [comment]
To get it to work with Ghidra 11.2, did you perform a `Link Ghidra` operation?

**Comment by John-Zetier** [comment]
Yes I did

**Comment by antoniovazquezblanco** [comment]
Starting with a clean eclipse and up to date dev plugin:
![imagen](https://github.com/user-attachments/assets/6acea132-34f8-4b6e-bdc8-82ca2276ce9f)

Using a clean clone of a recent extension I've started with (https://github.com/antoniovazquezblanco/GhidraExtendedSourceParser). No Eclipse config, just the gradle build file and Extension sources...
![imagen](https://github.com/user-attachments/assets/24b0303d-d8e7-4613-89f8-a7dee8da2d53)

Importing project as Ghidra module...
![imagen](https://github.com/user-attachments/assets/6b265dd7-291d-4ac2-be79-1d78dc5eeb87)

Using default values and linking against Ghidra 1.2.1. Project builds and allows me to run in Ghidra:
![imagen](https://github.com/user-attachments/assets/8ab48bd8-f5b0-4ec6-90c6-d354d362b29d)

Ghidra does NOT show signs of correctly loading the plugin...
Please find attached the generated classpath...
[classpath.txt](https://github.com/user-attachments/files/17653587/classpath.txt)

Maybe, what I forgot about, was to mention that I was importing the plugin. Does it now make sense?
Thanks!

**Comment by ryanmkurtz** [comment]
Thanks, I'll try to reproduce that tomorrow morning.

**Comment by ryanmkurtz** [comment]
> Maybe, what I forgot about, was to mention that I was importing the plugin. Does it now make sense?

This ended up being the key piece of information.  I see the issue and will get it fixed.  Thanks!

**Comment by ryanmkurtz** [comment]
Out of curiosity, has anyone here tried the new VSCode support yet?

**Comment by antoniovazquezblanco** [comment]
Not yet, but I prefer VSCode over Eclipse. May give it a go...

**Comment by ryanmkurtz** [comment]
It's fairly basic support at this point, you just run the [VSCodeProjectScript.java](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/ghidra_scripts/VSCodeProjectScript.java) GhidraScript from the Script Manager, and it creates a project for you that is tied that whatever version of Ghidra you ran the script from.  I think it works quite well though.  I am hoping to get more feedback on it.  I don't think many people have discovered it yet.

**Comment by antoniovazquezblanco** [comment]
Tanks!

**Comment by ryanmkurtz** [comment]
FYI I released a new Ghidra 4.0.1 to our [ghidra-data](https://github.com/NationalSecurityAgency/ghidra-data) repo, which you can use as an update site in Eclipse:

[Here](https://github.com/NationalSecurityAgency/ghidra/tree/master/GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin#manual-installation-in-eclipse-online) are some instructions for setting that up.
