### ISSUE TITLE
BSimElasticPlugin: Java class file version is too new for Elasticsearch 8.8.1

### ISSUE THREAD

**Issue by jordanjohnson56** [NationalSecurityAgency/ghidra#7054]
**Describe the bug**
The Java class file found in `lsh.zip`, the plugin for Elasticsearch, is too new to be recognized by Elasticsearch version 8.8.1. When the plugin is installed, Elasticsearch prints the following error message:

> org/elasticsearch/plugin/analysis/lsh/AnalysisLSHPlugin has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 64.0

I believe the fix is to update Elasticsearch to a newer version, but doing so prints the following message when attempting to install the plugin:

> java.lang.IllegalArgumentException: Plugin [lsh] was built for Elasticsearch version 8.8.1 but version [any other version] is running

It looks like the plugin will need to be updated to work with a newer version of Elasticsearch running a newer Java Runtime.

**To Reproduce**
NOTE: I had to add `libsDirName='ziplayout'` to the `build.gradle` file in `Ghidra/Extensions/BSimElasticPlugin/` _before building Ghidra_ to be able to get a correct `lsh.zip` file. See #7051 for more info.

1. Install the BSimElasticPlugin extension from the Ghidra UI or by unzipping the `ghidra_11.2_DEV_20241014_BSimElasticPlugin.zip` archive from `Extensions/Ghidra/` to `Ghidra/Extensions/` (I used the latter method).
2. Locate the `lsh.zip` file in `Ghidra/Extensions/BSimElasticPlugin/data/`.
3. Install this plugin in Elasticsearch and restart Elasticsearch to see the error message.

**Expected behavior**
The plugin should install and Elasticsearch should run without plugin-related errors.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version: 21.0.4 (Ghidra), 20.0.1 (Elasticsearch)
 - Ghidra Version: 11.2
 - Ghidra Origin: locally built

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
Fixed by 977e6be67f0ade11a36294d6b062055227590ca5
