### ISSUE TITLE
Has the 'dbg via SSH' been removed in Ghidra version 11.2?

### ISSUE THREAD

**Issue by daekp** [NationalSecurityAgency/ghidra#7069]
I recently updated to version 11.2, but I can't find the 'GDB via SSH' option. 

Is the 'dbg via SSH' feature no longer supported?

![image](https://github.com/user-attachments/assets/a0918b69-2300-4eb4-8888-434537404cee)

**Comment by nsadeveloper789** [comment]
It was accidentally removed from the Windows version when we overhauled our connector system. An update to fix this was just accepted internally, but hasn't made it into the repo yet. Once it arrives, some new `.bat` files will appear here https://github.com/NationalSecurityAgency/ghidra/tree/patch/Ghidra/Debug/Debugger-agent-gdb/data/debugger-launchers (mirroring the `.sh` files). You should just be able to download `ssh-gdb.bat` and manually patch it in by copying it into the same directory of your installation.

**Comment by daekp** [comment]
Thank you for your response

**Comment by ryanmkurtz** [comment]
Fixed by 8b899fe9866386680d972f91431e18721ee4c8bf
