### ISSUE TITLE
Sleigh: handling complex memory mapping

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#707]
I'm trying to add support for Freescale/NXP HCS12 microcontrollers.
They have 23-bit address space (classic flat Von Neumann machine - with peripheral, ram and rom in same place), but only 16-bit address registers. 

To handle all addresses, MCU makers added special peripheral - `Memory Mapping Control module`. In simpliest case, it have only one control register - `PPAGE`.
In few words, it works as follows:
- if CPU reads from addr 0 .. 0x3fff, it directly access to registers / RAM with same physical address.
- if CPU reads from addr 0x4000...0x7fff, it refers to last but one flash page, with physical address 0x7F8000 .. 007FBFFF
- if CPU reads from 0xC000..0xFFFF, it refers to last flash page, with addresses 0x7FC000 .. 007FFFFF
- and if CPU reads from hole (Freescale called it 'window') 0x8000..0xBfff, joins the game PPAGE reg: 
`phys_addr = 0x40 0000 + (PPAGE << 13) + (local_addr & 0x3fff)`

More detailed explanation can be found in [AN3784](https://www.nxp.com/docs/en/application-note/AN3784.pdf)

The essense of the question: what is correct way to write this conditions in slaspec file ?

PS next generation of this core, HCS12X, has same logic to access RAM and EEPROM, with different memory 'windows' and diffrent offset registers.

**Comment by mumbel** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/cafbb77db0a2120c529aef45d2d6bc47fa1edc29/Ghidra/Framework/SoftwareModeling/data/languages/processor_spec.rxg#L136

I've been kind of looking at this as well, but hadn't implemented anything, but this looks like what would provide that functionality

**Comment by ryanmkurtz** [comment]
If @mumbel's answer was not sufficient, we can reopen.
