### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by zglozman** [NationalSecurityAgency/ghidra#7074]
**Is your feature request related to a problem? Please describe.**
I like to keep my ghidra up to date

**Describe the solution you'd like**
I would like to (a) notify of new versions, and (b) have an option to automatically download and upgrade ghidra. 

**Describe alternatives you've considered**

**Additional context**
If the team is open to such functionality, i would like to try to make a contribution

**Comment by astrelsky** [comment]
(a) is already provided by Github. In the repo, click the down arrow on the "watch" icon and choose "custom".
![image](https://github.com/user-attachments/assets/7896c5f4-64d0-4bdb-ad9f-10199b74301e)

**Comment by ryanmkurtz** [comment]
a) @astrelsky's recommendation is best...GitHub should do a sufficient job in notifying you about new releases
b) We have no plans on supporting this.
