### ISSUE TITLE
`bsim_ctl start` fails on Fedora 40

### ISSUE THREAD

**Issue by gemesa** [NationalSecurityAgency/ghidra#7084]
**Describe the bug**
`bsim_ctl start` fails on Fedora 40. After some investigation I found that the issue arises from Fedora using a much newer OpenSSL version (3.2.2) compared to Ubuntu 22.04 (3.0.2). This newer version does not work well with PostgreSQL 15.3.

**To Reproduce**

1. Install Fedora (or any other distro with newer packages)
2. Install Ghidra 11.2 from the releases or build master branch from source, then:

```
$ cd Ghidra/Features/BSim
$ ./make-postgres.sh
$ cd ../../../
$ ./support/bsim_ctl start ~/git-repos/bsim-db/            
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
Server started
SSL error: Remote host terminated the handshake
Server shutdown complete
```

There is no useful information in the log file generated by `pg_ctl`.

**Expected behavior**
```
$ ./support/bsim_ctl start ~/git-repos/bsim-db/           
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
Server started
BSim extension enabled
```

I have installed [OpenSSL 3.0.2](https://github.com/openssl/openssl/releases/tag/openssl-3.0.2) from source (to `/usr/local/ssl`) and it fixed the problem:

```
$ LD_PRELOAD=/usr/local/ssl/lib64/libssl.so:/usr/local/ssl/lib64/libcrypto.so ./support/bsim_ctl start ~/git-repos/bsim-db/
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
Server started
BSim extension enabled

```

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Linux fedora 6.10.12-200.fc40.x86_64
 - Java Version: openjdk 21.0.4 2024-07-16 LTS
 - Ghidra Version: 11.3_DEV
 - Ghidra Origin: locally built from the GitHub repo without any changes (commit [64b70d8e](https://github.com/NationalSecurityAgency/ghidra/commit/64b70d8ef72fdc6b77624546efe89372f97ea827))

**Additional context**
N/A

**Comment by gemesa** [comment]
This issue relates to #6115

**Comment by ghidra1** [comment]
We will be updating to postgresql 15.10 which works with openssl 3.2.2
