### ISSUE TITLE
GCC-9.1.0 Binaries Undemangled Symbols

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#711]
**Describe the bug**
Mangled symbols containing the char8_t type are not demangled properly.

**To Reproduce**
1. Create label _ZTSSt7codecvtIDiDu11__mbstate_tE
2. Attempt to demangle
3. Get no demangled result.

**Expected behavior**
The mangled label "_ZTSSt7codecvtIDiDu11__mbstate_tE" to be demangled to "typeinfo name for std::codecvt<char32_t, char8_t, __mbstate_t>"

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.557]
 - Java Version: 12.0.1
 - Ghidra Version: 9.0.4

**Comment by ryanmkurtz** [comment]
We haven't had a chance to look at your pull-request yet, but I'll move it forward internally so someone who knows more about demangling can begin to take a look at it.

**Comment by astrelsky** [comment]
> We haven't had a chance to look at your pull-request yet, but I'll move it forward internally so someone who knows more about demangling can begin to take a look at it.

Ok. The changes are directly from gcc and I have the gcc commits linked in the pr.
