### ISSUE TITLE
Windbg runs slowly 

### ISSUE THREAD

**Issue by txgxbj** [NationalSecurityAgency/ghidra#7111]
**Describe the bug**
During the dynamic debugging process, pressing the F12 key after the breakpoint made the program run very slowly, one step per second. I tried various methods, such as pressing the F5 key and checking the system hardware, but none of them changed.

**To Reproduce**
1. Load the debugged file a.exe. into the Ghidra debugger. Use Windbg.
2. Add the next breakpoint bp1 in the disassembly dialog box of a.exe.
3. Add the next breakpoint bp1 in the disassembly dialog box of a.exe
4. Press the F12 key to run, and the program runs very slowly, with one line of code per second. I don't know what the problem is.

**Expected behavior**
After pressing the F12 key, it should quickly run to the next breakpoint

**Environment (please complete the following information):**
 - OS: [windows 10 64bit]
 - Java Version: [21.0.5]
 - Ghidra Version: [e.g. 11.13]
 - Ghidra Origin: [ locally built]

**Comment by d-millar** [comment]
I guess I need a little more explanation about your set-up.  What options are you using with dbgeng (or are you really using windbg proper)?  What are F5 and F12 mapped to?  When you say the "disassembly dialog", do you mean the Static Listing or the Dynamic Listing or something else?  Is there anything particularly unique about this executable or are you seeing this behavior for every executable?  (A pciture would help if you can provide one.)

**Comment by txgxbj** [comment]
Hello!  
Thank you for helping me analyze the problem. I'm sorry that I couldn't express myself clearly. Below, I will rephrase the current issue. 
﻿ 
To Reproduce  
Steps to reproduce the behavior:  
![1](https://github.com/user-attachments/assets/961bad37-15db-4db6-9195-4a7b96553057)

Step 1  : Import program 'multicastreceiver. exe'   
Step 2  : Start dynamic debugging   
Step 3  : Use default options for 'Analysis'   
Step 4  : Break the breakpoint and press the F12 key. At this point, the program runs very slowly, running one line of disassembly code per second?  
I have edited screenshots of each step into a single image, which is attached. 
﻿ 
Expected behavior  
After pressing the F12 key, it should quickly run to the next breakpoint  
﻿  
Environment (please complete the following information):  
Java Version: [21.0.5]  
Ghidra Version: [e.g. 11.13]  
Ghidra Origin: [ locally built] 
Version: Windows 10 Professional Edition  
Version number: 22H2  
Installation date: May 11, 2024  
Internal version of operating system: 19045.5011  
Equipment Name: DESKTOP IQBK6HH  
Processor: Intel (R) Xeon (R) CPU E5-2450 0 @ 2.10GHz 2.10 GHz  
Machine RAM: 16.0GB  
System type: 64 bit operating system, based on x64 processor  
Pen and Touch: No pen or touch input available for this monitor  
Experience: Windows Feature Experience Pack 1000.19060.1000.0 
﻿ 
I have tried several methods to solve the problem, but none have been successful  :
1. Ghidra: Is the configuration correct. Whether there are too many running programs, etc.  
2. Executable file: Select official Qt sample programs and programs in other programming languages  
3. Hardware: Check the usage of the hardware at that time

![1](https://github.com/user-attachments/assets/cc7636cc-7d80-4f12-8486-de0543106c9b)

**Comment by d-millar** [comment]
@txgxbj  Was able to repeat your experience, but I have to ask... do you really want/need to use F12?  F12 is step-out.  In Windows, this means literally that - they are going to single-step the processor until you leave the routine.  If the routine is short, that's not usually terrible, but you're still forcing an interrupt, sending that message back to the debugger, and forcing the debugger to respond to the new state.  If you're using breakpoints, I'm thinking you really want to hit "Resume".  Am I missing something here?

**Comment by txgxbj** [comment]
@d-millar  After reading your reply, I understand the problem. Thank you for your help.
