### ISSUE TITLE
Make DWARF analyzer also parse data types

### ISSUE THREAD

**Issue by Martmists-GH** [NationalSecurityAgency/ghidra#7117]
**Is your feature request related to a problem? Please describe.**
Currently when analyzing a binary the DWARF types don't seem to be applied, and there's also no script to apply it. From what I've found online I also tried the following script but it didn't seem to do much:

```java
public class DumpGDTFromDWARF extends GhidraScript {
    protected void run() {
        if (ghidra.app.util.bin.format.dwarf4.next.DWARFProgram.isDWARF(currentProgram)){
            var dtm = currentProgram.getDataTypeManager();
            var cmd = new CaptureFunctionDataTypesCmd(dtm, currentProgram.getMemory(), null);
            cmd.applyTo(currentProgram);
            dtm.close();
        } else {
            System.out.println("Not a DWARF binary!");
        }
    }
}
```

**Describe the solution you'd like**
Add a way to parse DWARF types to the program.

**Describe alternatives you've considered**
I tried dumping types with `aarch64-none-elf-gdb` using `info types` and `ptype`, but those both seem to segfault while handling the types.

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
Can you attach your binary?
