### ISSUE TITLE
SymbolType is missing a LABEL static field

### ISSUE THREAD

**Issue by rgov** [NationalSecurityAgency/ghidra#712]
There is no `SymbolType.LABEL` which seems expected considering there are `SymbolType.FUNCTION` et al.

**Environment:**
 - OS: macOS 10.14.5
 - Java Version: 12.0.1
 - Ghidra Version: 9.0.4

**Comment by rgov** [comment]
It seems to be called `SymbolType.CODE`.

https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/symbol/SymbolType.java#L28

**Comment by ryanmkurtz** [comment]
@rgov can I close this out?

**Comment by rgov** [comment]
Well, it's definitely counterintuitive that the "Label" symbol type constant is called `CODE` while all the other ones match pretty closely. Is there a reason why it shouldn't change to `LABEL` or the description change to `"Code"`?

**Comment by ryanmkurtz** [comment]
It looks like we recently renamed the name to "Label" but didn't fix up the name of the variable, probably for backwards compatibility purposes.  We should rename it to `LABEL`, and deprecate `CODE`, removing it in a few releases so we don't break anything.
