### ISSUE TITLE
Why was `Scalar.add` removed?

### ISSUE THREAD

**Issue by nmggithub** [NationalSecurityAgency/ghidra#7122]
Commit c099ad70772f852c31d9cca039696e253039f3e4 removed the `add` method for the `Scalar` class. 

There are two issues with this:

1. It's still documented in the JavaDoc: https://ghidra.re/ghidra_docs/api/ghidra/program/model/scalar/Scalar.html#add(long)
2. While it may be unused internally (based on the commit message), it is still useful for plugins and extensions (such as the one I am attempting to write right now).

Why was it removed, and can it be added back?

**Comment by dev747368** [comment]
I'm the guilty party that removed it.

I can't remember any specific animus toward that method other than it wasn't called by any of our code, and not having a clear use case for adding values that can have different bit lengths.

BTW, the URL you linked to is not a website associated with the project.  Its just someone that grabbed that domain name and put up some static pages.

**Comment by nmggithub** [comment]
Thanks for the note. Is there any official page for the JavaDocs?

**Comment by dev747368** [comment]
No, we have not published the javadocs on a public website. :man_shrugging:

**Comment by nmggithub** [comment]
That does feel like a missed opportunity (that, and the lack of general documentation around plugin development). I do hope there is more in the future.

**Comment by mumbel** [comment]
have you ever looked in the docs/ directory... in any release?

**Comment by nmggithub** [comment]
> have you ever looked in the docs/ directory... in any release?

I have, to some degree. But I personally find it a tad odd to not some way to access docs separate from the actual releases, as most projects provide such a thing.

But perhaps that's just a matter of preference.
