### ISSUE TITLE
GUI: FlatDark theme minor improvement

### ISSUE THREAD

**Issue by esaulenka** [NationalSecurityAgency/ghidra#7134]
**Is your feature request related to a problem? Please describe.**

During analysis it's often important to know what is the cursor position in the inactive ghidra's windows.
Let's say, the last selected reference in the references window.

In the current 'Flat Dark' theme inactive cursor is too close to common background color:

![image](https://github.com/user-attachments/assets/9bf2ee9c-49e2-430a-a7ca-cddd918d0095)

**Describe the solution you'd like**

I have changed this color to the 0e6666 and it looks much better:
![image](https://github.com/user-attachments/assets/9a781ee9-38e7-45b5-ab72-98d95aad1597)

I don't understand, how to do it correctly, so I just patched this line 
`[color]laf.palette.color.59 = #0e6666 // !!! was #0f2a3d`
that referenced by
```
[laf.color]List.selectionInactiveBackground = [color]laf.palette.color.59
[laf.color]Table.selectionInactiveBackground = [color]laf.palette.color.59
[laf.color]Tree.selectionInactiveBackground = [color]laf.palette.color.59
```

in the `.theme` file.

**Comment by esaulenka** [comment]
Hello!
What do you mean, when set 'waiting on customer' status?
I need to provide some more info?

**Comment by ryanmkurtz** [comment]
I think it was a mistake.  I pinged @dragonmacher about it.

**Comment by dragonmacher** [comment]
We can update the theme settings we ship to change that color value.  As it stands now, that inactive table selection color is defined by the Dark FlatLaf itself internally.   I, as well as a few others, agree that it is hard to see that color.    I have no issue with overriding the value.  The color you picked is easy to see, but also looks somewhat bright, like the focused color does.   If we can find a reasonable middle-ground, then I'll make the change.

**Comment by esaulenka** [comment]
Ok, understood. Let's use #0B4D4D for it.

inactive cursor:
![image](https://github.com/user-attachments/assets/5059b613-61aa-452a-819e-b8ba0b9ae209)

and active cursor (just to compare, no changes here):
![image](https://github.com/user-attachments/assets/fcb719db-c1cb-405a-8330-23a49c5affcb)
