### ISSUE TITLE
Request for Python 3.13 support

### ISSUE THREAD

**Issue by gemesa** [NationalSecurityAgency/ghidra#7141]
**Is your feature request related to a problem? Please describe.**

Fedora 41 has been released and after upgrading I noticed that the default Python version is 3.13 which is currently [not supported](https://github.com/NationalSecurityAgency/ghidra/blob/master/README.md?plain=1#L51).

After adding version 3.13 [here](https://github.com/NationalSecurityAgency/ghidra/blob/master/build.gradle#L52) and [here](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/PyGhidra/src/main/py/pyproject.toml#L29),  `gradle buildGhidra` completes successfully but `gradle prepdev eclipse buildNatives` still fails:

```
$ gradle prepdev eclipse buildNatives

> Configure project :
Java: 21
Gradle: 8.10.2
Python3 command: [python3] (version 3.13)
Python3 pip version: 24.2
OS: Linux
Arch: amd64 (gradle: x86-64)
Using platform: linux_x86_64

> Configure project :Debugger-agent-dbgeng
WARNING: dbgmodel.tlb omitted from ghidradbg python package

> Task :PyGhidra:installJPype FAILED
Looking in links: /home/gemesa/git-repos/ghidra/dependencies/PyGhidra
ERROR: Could not find a version that satisfies the requirement JPype1 (from versions: none)
ERROR: No matching distribution found for JPype1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PyGhidra:installJPype'.
> Process 'command '/home/gemesa/git-repos/ghidra/build/venv/bin/python3'' finished with non-zero exit value 1
```

I guess [this](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/PyGhidra/build.gradle#L37) should be updated somehow.

**Describe the solution you'd like**
Support for Python 3.13.

**Describe alternatives you've considered**
I can install earlier version(s) (3.11, 3.12, ...) but my preference is to use the default one (3.13).

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
We are waiting on JPype to release a new version that supports 3.13.  As soon as they do, i plan on incorporating.

**Comment by ryanmkurtz** [comment]
JPype 1.5.1 has been released and I am working on the upgrade.  Initial testing against Python 3.13 looks good.

**Comment by ryanmkurtz** [comment]
I'm currently tracking https://github.com/jpype-project/jpype/issues/1242 to see what the turnaround on a fix will be.  If it seems like it will be soonish I'll wait for that version before upgrading.

**Comment by gemesa** [comment]
Awesome, thank you for taking care of this.
