### ISSUE TITLE
Another 'Cannot invoke "java.net.URL.toExternalForm()" because "url" is null' crash

### ISSUE THREAD

**Issue by hippietrail** [NationalSecurityAgency/ghidra#7145]
I've just run into the same null reference crash as described in #3374 and #6734 
<img width="706" alt="Screenshot 2024-11-03 at 2 26 19 pm" src="https://github.com/user-attachments/assets/5af28e14-cf4a-4653-888f-c8b3d220cce1">
```
ERROR Error: Uncaught Exception! 
NullPointerException - Cannot invoke "java.net.URL.toExternalForm()" because "url" is null (SwingExceptionHandler) java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "url" is null
	at ghidra.base.help.GhidraHelpService.mapHelpToModule(GhidraHelpService.java:120)
	at ghidra.base.help.GhidraHelpService.findHelpSetsByModule(GhidraHelpService.java:104)
	at ghidra.base.help.GhidraHelpService.loadHelpSets(GhidraHelpService.java:85)
	at ghidra.base.help.GhidraHelpService.<init>(GhidraHelpService.java:60)
	at ghidra.base.help.GhidraHelpService.install(GhidraHelpService.java:51)
	at ghidra.GhidraRun.lambda$launch$1(GhidraRun.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```
But I seem to be getting there a different way and those are both closed as fixed so filing this as a new report.

Ghidra 11.2
GhidraDev 4.0.0.202408290705
MacOs 15.0.1

In my case I have 11.2 which I download and use to work with GhidraDev on my project RetroGhidra.
And I also have a copy of the Ghidra repo where I work on my own Ghidra features.
For the past few weeks I have been running either one or both of these in separate mac App instances using `open -n` from the terminal with no problems. Sometimes I closed one and opened it later, sometimes the other.

But last night when my laptop was a bit too warm I closed all my Ghidras and all my Eclipses to let it cool down.

Now when I open Ghdra 11.2 via `ghidraRun` and choose my "Retro" option from the dropdown of the "bug" tool in the toolbar, the usual way I test my RetroGhidra project, I hit this exact null pointer exception described.

The only things I've done differently are:
1. I just renamed one of my source files for a `Loader`
2. I deleted an old empty eclipse directory from my home directory
3. last night I installed a `Loader` from GitHub. Which worked fine before I closed everything down. It still works if I run Ghidra 11.2 outside of Eclipse. https://github.com/lab313ru/ghidra_sega_ldr

**Comment by hippietrail** [comment]
OK it turns out that "ghidra_sega_ldr" was the culprit, but it was hard to track down.

- The crash didn't give a hint.
- Trying to find where the extension was in my filesystem was very difficult. I hunted in the Ghidra directory and searched for the name of the extension and just "sega" and other combinations in the Finder, even on the whole computer

Finally I started my Ghidra 11.2 outside of Eclipse and went to File/Install extensions where I could see that the extension was in fact for 11.1.2 and this dialog also told me that it was installed in ~/Library which makes sense but that's a hidden folder that some Mac users might not even know about. I don't know whether that's why the Finder couldn't locate it or not.

I think I forgot that I got some kind of warning when I installed the extension saying it was for the wrong version since it worked until I ran into this problem.

I'm not sure if there's anything that can be "fixed" to make this a harder trap to fall into or an easier one to get out of? Leaving it open for now.

**Comment by dragonmacher** [comment]
> I'm not sure if there's anything that can be "fixed" to make this a harder trap to fall into or an easier one to get out of? Leaving it open for now.

Not really anything we can do at the point of the exception.  I would probably be possible to write some code to detect that an extension or module has been added that does not correctly have help setup.   Since this happens so infrequently, we haven't put any effort to try to improve this type of validation.
