### ISSUE TITLE
Update Arch package

### ISSUE THREAD

**Issue by ERedstone** [NationalSecurityAgency/ghidra#7146]
**Is your feature request related to a problem? Please describe.**
arch package is still 11.0.3 while the most recent is 11.2

**Describe the solution you'd like**
update the arch package

**Describe alternatives you've considered**
update the arch package ;-;

**Comment by gemesa** [comment]
Go contact the package maintainer then:
https://archlinux.org/packages/extra/x86_64/ghidra/
https://archlinux.org/packages/?maintainer=anthraxx

**Comment by ryanmkurtz** [comment]
This project doesn't not maintain the Arch package.  You will have to follow the links that @gemesa has provided.
