### ISSUE TITLE
Ghidra Debugger is not working

### ISSUE THREAD

**Issue by nizarakbarm** [NationalSecurityAgency/ghidra#7154]
I am using ghidra_11.2_PUBLIC_20240926 and i placed all of it inside /usr/local/ghidra. When i tried debugging using qemu + gdb or only gdb, it will always end up with undefined command "ghidra". 
![undefined_ghidra](https://github.com/user-attachments/assets/88431d49-70a0-4a48-af77-3b506dd551a3)

If i tried to check in the terminal window, it shows that ghidra not in executable format.

![ghidra_not_in_executable_format](https://github.com/user-attachments/assets/eb19a5bc-397d-4a75-a226-f669283de02d)

I think this is happening because ghidra_11.2_PUBLIC_20240926  is using ghidraRun which is not executable format but bash shell.

And unfortunately the installation guide in https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_11.2_build/GhidraDocs/InstallationGuide.html also not in sync with the latest update.

detail of environment:
Ghidra: 11.2
Python: 3.12.3
JDK: openjdk-21-jdk

**Comment by d-millar** [comment]
@nizarakbarm Generally this means the version of python in your path (in your case, 3.12.3) is not consistent with the version of python compiled into gdb.  You can check the latter by opening up python, typing "pi" to get the python interface, and then issuing the commands, "import sys" and "sys.version".

**Comment by nsadeveloper789** [comment]
Click the **Keep** button and then scroll to the *very top* of the Terminal. It could be any number of things (including the python version mismatch @d-millar mentioned. But, if we look for the first warning/error messages in the Terminal, we'll have a much better idea.

As for the InstallationGuide, you are partially correct: We require a newer version of `Pybag` than the guide says, but that's only applicable to Windows. The required version of `protobuf` is still `==3.20.3`. If you install a later version, you may get import errors leading to this `Undefined command "ghidra"` error.

FWIW, we are pretty good about publishing to PyPI (https://pypi.org/project/ghidragdb/), so you might be able to resolve this simply:
```bash
pip3 install ghidragdb
```

**Comment by nizarakbarm** [comment]
The python version in GDB and outside GDB is actually the same but i forgot to include my screenshot before. Or is it because  the python vritual environment is not loaded when running ghidraRun?

![ghidra_python_version](https://github.com/user-attachments/assets/3f90d7ab-3c58-4081-954d-961ffd96bd8d)

**Comment by nizarakbarm** [comment]
Even when tried with activate the virtual environment and run ghidra with `source /usr/local/ghidra/Ghidra/Debug/bin/activate.fish && ./ghidraRun`, it still has the same problem.

![ghidraRun_activate_virtualenv_first](https://github.com/user-attachments/assets/5f8811f0-6f97-42b8-8bf8-3cd159d4cce5)

**Comment by nsadeveloper789** [comment]
gdb's embedded Python does not respect the virtual environment, sadly. The "easiest" thing to do is to just pip install outside any venv. You'll need to pass the `--break-system-packages` [sic] flag.

If you insist on a venv, you are off the beaten path. There may be workarounds:

1. In your `.gdbinit`, you'll need to shell out to python and have it print out `sys.path`, and then invoke gdb's embedded python to override its `sys.path` to match. I've never tried this myself, but in theory, that should get gdb's python to import packages from whatever venv was active, presumably when you started `ghidraRun`.

2. Another possible workaround: Edit `<ghidra>/Ghidra/Debug/Debugger-agent-gdb/data/debugger-launchers/qemu-gdb.sh`. In there, you should see some setup of the `PYTHONPATH`. Add your venv's path to that. To figure out what path(s) you might need to add, start `python` from your venv, and then `import sys; print(sys.path)`.

**Comment by nizarakbarm** [comment]
Oh, so it is ok to edit the PYTHONPATH in the shell file. I will tried that tomorrow morning, I need to sleep now because i am still human currently.  At least, now i know that it is possible to uncomment the shell variable in the bash file and change the value.

**Comment by nizarakbarm** [comment]
I think i found the problem: 
```
(Debug)  devnull  /usr/local/ghidra/Ghidra/Debug  
$ python3                                                                                                                                     463ms
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ghidragdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/ghidra/Ghidra/Debug/lib/python3.12/site-packages/ghidragdb/__init__.py", line 16, in <module>
    from . import util, commands, parameters
  File "/usr/local/ghidra/Ghidra/Debug/lib/python3.12/site-packages/ghidragdb/util.py", line 20, in <module>
    import gdb
ModuleNotFoundError: No module named 'gdb'
>>> 
```
Based on this, maybe i need to reinstall gdb.

**Comment by nizarakbarm** [comment]
Found the solution, beside setting the PYTHONPATH i need to copy the content of site-packages from my virtual environment to data directory of gdb:
```
sudo cp -rf lib/python3.12/site-packages/* /usr/share/gdb/python
```
or 
```
sudo rsync -Paz  lib/python3.12/site-packages/* /usr/share/gdb/python
```

The gdb data directory can be different depends on the linux distribution.
But i have debugging warning like this:
```
The module /usr/lib/debug/.build-id/35/3e1b6cb0eebc08cf3ff812eae8a51b4efd684e.debug was not found in the project
---------------------------------------------------
Build Date: 2024-Sep-26 1444 EDT
Ghidra Version: 11.2
Java Home: /usr/lib/jvm/java-21-openjdk-amd64
JVM Version: Ubuntu 21.0.4
OS: Linux 6.8.0-47-generic amd64
```
and
```
The module /lib64/ld-linux-x86-64.so.2 was not found in the project
---------------------------------------------------
Build Date: 2024-Sep-26 1444 EDT
Ghidra Version: 11.2
Java Home: /usr/lib/jvm/java-21-openjdk-amd64
JVM Version: Ubuntu 21.0.4
OS: Linux 6.8.0-47-generic amd64
```

but it didn't stop the debugging process.

**Comment by nizarakbarm** [comment]
Even debugger can run with the solution i provided, there is still quite many warning error of python ghidra library so i give up using virtual environment. And i will use:
```
python3 -m pip install --no-index -f Debugger-rmi-trace/pypkg/dist -f Debugger-agent-gdb/pypkg/dist psutil protobuf --break-system-packages
```
as i see there is no conflict of protobuf and psutil my operating system.

**Comment by nizarakbarm** [comment]
After giving up using virtual env and try to install using --break-system-packages, debugger run normally, but there is quite many error in the terminal window of gdb:
```
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:67: SyntaxWarning: invalid escape sequence '\['
  AVAILABLE_PATTERN = re.compile('Available\[(?P<pid>\\d*)\]')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:68: SyntaxWarning: invalid escape sequence '\['
  BREAKPOINT_PATTERN = re.compile('Breakpoints\[(?P<breaknum>\\d*)\]')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:69: SyntaxWarning: invalid escape sequence '\['
  BREAK_LOC_PATTERN = extre(BREAKPOINT_PATTERN, '\[(?P<locnum>\\d*)\]')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:70: SyntaxWarning: invalid escape sequence '\['
  INFERIOR_PATTERN = re.compile('Inferiors\[(?P<infnum>\\d*)\]')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:71: SyntaxWarning: invalid escape sequence '\.'
  INF_BREAKS_PATTERN = extre(INFERIOR_PATTERN, '\.Breakpoints')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:72: SyntaxWarning: invalid escape sequence '\.'
  ENV_PATTERN = extre(INFERIOR_PATTERN, '\.Environment')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:73: SyntaxWarning: invalid escape sequence '\.'
  THREADS_PATTERN = extre(INFERIOR_PATTERN, '\.Threads')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:74: SyntaxWarning: invalid escape sequence '\['
  THREAD_PATTERN = extre(THREADS_PATTERN, '\[(?P<tnum>\\d*)\]')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:75: SyntaxWarning: invalid escape sequence '\.'
  STACK_PATTERN = extre(THREAD_PATTERN, '\.Stack')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:76: SyntaxWarning: invalid escape sequence '\['
  FRAME_PATTERN = extre(STACK_PATTERN, '\[(?P<level>\\d*)\]')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:77: SyntaxWarning: invalid escape sequence '\.'
  REGS_PATTERN = extre(FRAME_PATTERN, '\.Registers')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:78: SyntaxWarning: invalid escape sequence '\.'
  MEMORY_PATTERN = extre(INFERIOR_PATTERN, '\.Memory')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:79: SyntaxWarning: invalid escape sequence '\.'
  MODULES_PATTERN = extre(INFERIOR_PATTERN, '\.Modules')
/usr/local/ghidra/Ghidra/Debug/Debugger-agent-gdb/pypkg/src/ghidragdb/methods.py:80: SyntaxWarning: invalid escape sequence '\['
  MODULE_PATTERN = extre(MODULES_PATTERN, '\[(?P<modname>.*)\]')
Reading symbols from /home/devnull/learn_c/string...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
(No debugging symbols found in /home/devnull/learn_c/string)
Connected to Ghidra 11.2.1 at 127.0.0.1:44151
Starting program: /home/devnull/learn_c/string 

Program stopped.
0x00007ffff7fe4540 in _start () from /lib64/ld-linux-x86-64.so.2
```
Is this normal?

**Comment by nsadeveloper789** [comment]
Yes, those warnings on the XXX_PATTERN things are normal. We were developing on an older version of python, so we already accrued some lint, which is what you're seeing here.

It's also normal to see the bits about modules not being in the project. Those entries will appear in the Debug Console window and give you some buttons if you would like to import them. Otherwise, if you don't care about those modules, don't import them. You'll still see the module contents in the Dynamic window, but the static Listing will have nothing to track along with.

**Comment by nizarakbarm** [comment]
Oh ok, it seem that the problem solved now. I misunderstood those error too as a problem because virtual environment so i change to not use virtual environment but actually this solution already solve the problem in virtual environment too:
```
sudo cp -rf lib/python3.12/site-packages/* /usr/share/gdb/python
```
But need to set the PYTHONPATH in the debugger script too.

But better backup the directory of /usr/share/gdb/python first. If there is no conflict of psutil and protobuf in the operating system, it is also safe to use this directly:
```
python3 -m pip install --no-index -f Debugger-rmi-trace/pypkg/dist -f Debugger-agent-gdb/pypkg/dist psutil protobuf --break-system-packages
```
 This case can be closed now.

**Comment by nsadeveloper789** [comment]
Good deal. Seems we might want to note about the `--break-system-packages`  flag in our setup/help documentation, or figure out a way to play nicely with venv.... Thanks!
