### ISSUE TITLE
How to parse C files with stdint.h types

### ISSUE THREAD

**Issue by KevOrr** [NationalSecurityAgency/ghidra#716]
I have a C file that includes structs whose members are of one of the `stdint.h` types (e.g. `uint8_t`, `int32_t`, `int_fast8_t`, etc). When I add this file to the "Source files to parse", and hit "Parse to Program", I get the following error:

```
C Parser: Encountered errors during parse.
    in <file> near line -5
    near token: null
    Last Valid Datatype: foo
    Check around CParserPlugin.out around line: 96
```

`CParserPlugin.out` is:
```
95  struct pa_channel_map {
96      uint8_t channels;
97      pa_channel_position_t map[32];
98  };
```

How do I parse this file without manually defining the stdint types?

**Comment by emteere** [comment]
In your case, you would need to add stdint.h to your list of header files before the header file you wish to parse.

Currently parsing doesn't pull the types from the already open archives until the header files are all parsed.  Then a reconciliation of equivalent types is done on the newly parsed data types.  This was designed that way so that the parse was not affected by existing data type.  Parsing can be finicky, potentially adding new types along with using existing ones.  So it is a catch-22.

It is possible that a flag could be added to look up undefined types in open archives, which would allow your file to parse.  We've had this on the list to check into.  I don't think it would be that complicated to add as the archives are already available to the parser.

**Comment by KevOrr** [comment]
@emteere thanks for your response. I have one question though.

> In your case, you would need to add stdint.h to your list of header files before the header file you wish to parse

I'm using the built-in linux64 profile (can't remember the exact name), and `stdint.h` is included in that list, and is listed before my own header file. However, `stdint.h`, as well as all of the headers associated with any of the default profiles, is highlighted in red. Does the color indicate that they are part of a default profile, or does it mean they couldn't be found, or something else?

**Comment by Cih2001** [comment]
@KevOrr I have the same exact problem that you described. did you find any solution?

**Comment by KevOrr** [comment]
Unfortunately no, although I haven't played around with custom headers since around the time of the last comment

**Comment by stryker2k2** [comment]
Any update on this?  I understand @emteere suggestion here but unclear about the means of execution.  Is @emteere suggesting that we download a copy of `stdint.h` and add it to our *.prf inside of the "Parse C Source" window?  Or is the suggestion to place `#include stdint.h` in our actual header file that we are parsing into our program?

**Comment by therealchjones** [comment]
Workaround for types defined in archives but not used during import/parsing:

1. In the data type manager, filter then right-click on the needed files. (In the case of many programs that need only "standard" definitions like the above, types.h and stdint.h will suffice.) Export the C headers of the file:
![dtm-export](https://user-images.githubusercontent.com/4241732/113156357-e804ff00-9207-11eb-97ea-2426ab199245.png)

2. In the C parser dialog, empty all files and options (the "eraser" icon). Add the newly exported headers as well as the header for the program you're analyzing:
![parse-dialog](https://user-images.githubusercontent.com/4241732/113156655-30242180-9208-11eb-83f0-9d02947a29b7.png)

Certainly further customization may be needed for appropriate choices of archive files to export-then-import or other issues, but this solves the specific case of the OP and many other similar ones.

**Comment by therealchjones** [comment]
FWIW, this appears to be associated with a documentation error. See #2885.

**Comment by LegNeato** [comment]
Just want to mention I hit this bug my very first time doing _anything_ with ghidra. It is extremely counterintuitive these are picked up in one situation and throw an error in another.

**Comment by emteere** [comment]
The Cparser has had some refactoring, bug fixes, and better error reporting completed in an upcoming change.
Types that are unsatisfied from parsing will be looked up in any open archives.
In addition any types that are equivalent from any open archive with a parsed data type will use the data type from the archive.
After parsing you can disconnect the data types from the dependent archive if you no longer want to synchronize with dependent archive.
There are also three options on the warning dialog to Use Open Archives, Don't Use Open Archives, and Cancel.

This was always a planned change, but there needed to be some refactoring and cleanup.
