### ISSUE TITLE
Support for Resolving Indirect Function Pointers to Direct Calls in Decompiled View

### ISSUE THREAD

**Issue by gtnick19** [NationalSecurityAgency/ghidra#7168]
In Ghidra, I'm working with functions that use indirect pointers (e.g., single or double indirect calls) to call other functions, often represented by BLX instructions in ARM assembly. I need a way to automatically replace these indirect function pointers in the decompiled view with the actual function names, showing direct calls (e.g., disable_interrupts() instead of (*(code *)PTR_disable_interrupts)). Is there a way to force Ghidra’s decompiler to fully dereference these function pointers and display the resolved function names in place of the indirect calls? Despite adding direct references and flow overrides, I haven't found a way for the decompiler to reflect these changes, and manual re-decompilation attempts haven’t resolved the issue.

**Comment by astrelsky** [comment]
Set their mutability to constant.

**Comment by gtnick19** [comment]
This works, thank you!
