### ISSUE TITLE
Sleigh documentation is not clear around "pseudo instructions"

### ISSUE THREAD

**Issue by hippietrail** [NationalSecurityAgency/ghidra#7177]
**Describe the bug**
I consider this flaw in the documentation to be serious enough to qualify as a bug rather than a feature request.

About 15 of the Processors included with Ghidra have a "pseudo instructions" section (6502, 8048, 8085, CR16C, Dalvik, HCS_HC, HCS_HC12, XGATE, JVM, m8c, 6805, MCS96, PIC24, PPC, and Z80). But this is a term that is used only once in the Sleigh docs, and seems to not be used the same way.

In the processors it seems to cover constructors that start with an identifier followed by a colon. From 6502:
```
################################################################
# Pseudo Instructions
################################################################

define pcodeop readIRQ;

################################################################
REL: reloc		is rel	[ reloc = inst_next + rel; ] { export *:2 reloc; } 

# Immediate
OP1: "#"imm8    is bbb=2; imm8			{ tmp:1 = imm8; export tmp; }
# Zero Page
OP1: imm8       is bbb=1; imm8			{ export *:1 imm8; }
```
As opposed to "normal"? instructions that begin with a colon followed by an identifier:
```
# Instructions

:ADC OP1     is (cc=1 & aaa=3) ... & OP1
{
```
The one place in the docs uses this example: "... the disassembler should print a pseudo-instruction _clr_":
```
:xor r1,r2 is opcode=0xcd & r1 & r2 { r1 = r1 ^ r2; }
:clr r1    is opcode=0xcd & r1 & r1=r2 { r1 = 0; }
```
But the `clr` here uses the "mnemonic" field, unlike how "pseudo instruction" seems to be used in the sleigh files.

In fact I was and still am confused about these two kinds of constructors, and I feel this is also not well explained in the docs.

It seems that the optional identifier to the left of the colon and the colon itself are part of the "table header". No more specific term than "identifier" appears to be used. So I suppose "table identifier". The optional identifier to the right of the colon is then part of the "display section" does have a specific term "mnemonic".

I'm not sure if it's meaningful to omit both the optional table identifier and the optional mnemonic. On the other hand it is meaningful to use both, but it's only used six times, in JVM and SparcV9.

I think more people would be writing more sleigh processor definitions if these things were easier to follow for a beginner. I know it's hard to write documentation that's easy for beginners to follow on a topic you understand deeply.

For instance, here's a few things I'd like to do in my sleigh files, but actually I still don't understand well enough to know if they are possible:

1. Many processors have large groups of instructions with the same syntax, addressing modes, and binary representation, expect the mnemonics differ. I realize this mostly only applies to disassembly and not decompiling. I'm only doing disassembly yet but I can't figure out how to do this using pseudo instructions.
2. My processor has 17 ways of encoding an operand type it calls 'gdest'. There are several combining patterns it uses such as an `FF` means the operand will be the following 16 bits rather than the usual 8 bits occupied by the `FF`, and three 1-bit fields that indicate to use an index or to use indirect vs direct. So far I write out all 17. Also, instructions may have one, two or three 'gdest' fields. So I actually write all 17 out three times (gdestb, gdestc). I don't know if I can reduce either of these types redundancy using pseudo instructions.
3. I'd like to add an extra layer in addresses where they get replaced by a standard symbol if they have a specific value. I tried several ways to introduce an "Address" pseudo instruction but couldn't get it to work.

At least several of these seems like they should be doable with a proper understanding of pseudoinstructions. A couple I'm less sure.

If the documentation was clearer and matched the terminology in the included sleigh files it might be easier to know which kinds of things are not possible as well as how to implement the things which are possible, but hard to figure out.

**Comment by astrelsky** [comment]
They are pseudo pcode operations not instructions. See section "4.6. User-Defined Operations" of the sleigh manual.

`...` is not related to this at all. See section "7.4.4.2. The '...' Operator" of the sleigh manual.

**Comment by hippietrail** [comment]
> They are pseudo pcode operations not instructions. See section "4.6. User-Defined Operations" of the sleigh manual.

Hmm okay. There's a fair bit there I haven't fully understood yet either, but I'll give it another go.

> `...` is not related to this at all. See section "7.4.4.2. The '...' Operator" of the sleigh manual.

Same with this. I've read that section many times and so far I haven't needed the ellipsis operator even when I thought I was dealing with variable length instructions.

I'm glad some people find it easy to follow.

**Comment by hippietrail** [comment]
I'm closing this now that I see that pseudo instructions are about p-code. I'll keep trying to understand what I don't get yet.
