### ISSUE TITLE
Accessing substring

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#718]
Is there any trick to getting substrings in the decompiler.  For a trivial example a string "hello world", my code wants to use that null terminator as the empty string reference.  Listing shows `=""` and decompiler has `"hello world"+0xb`.  (If I undefined "hello world" then decompiler picks up the "")

Edit. Noticing it's not always this case.  The code I'm looking that does have it is a +0xb9 offset

**Comment by emteere** [comment]
You might be able to put a label at the "".  The decompiler might pay attention to the new label, then re-define the "hello world" string.
