### ISSUE TITLE
Modal menu windows (Structure editor, Reference list, etc.) are not rendered on Windows

### ISSUE THREAD

**Issue by gynt** [NationalSecurityAgency/ghidra#7180]
**Describe the bug**
Since today I experience a bug with Ghidra 11.1.1 which involves certain windows never being rendered, such as the Structure editor.

**To Reproduce**
1. Open a Ghidra program
2. Create a new structure
3. Wait a second
4. See no window although alt+tab lists the window (white)

**Expected behavior**
The structure editor window to be available and rendered.

**Screenshots**
![image](https://github.com/user-attachments/assets/c2305457-581d-4ecf-a4d6-5cb3de466399)

**Attachments**
NA

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 21.0
 - Ghidra Version: 11.1.1
 - Ghidra Origin: Official GitHub distro

**Additional context**
Started without a logical trigger such as a version update, upgrade, or another situation. I was using an outdated JDK (17.0), but upgrading to 21.0 didn't solve the issue. Is there some kind of cache I can clear that could solve this issue?

**Comment by ryanmkurtz** [comment]
Can you try Ghidra 11.2.1?

**Comment by gynt** [comment]
I managed to get this sort of solved, by right-clicking the white window as displayed in the screenshot from the original post, I get a context menu. 

![image](https://github.com/user-attachments/assets/95ebc0cf-71b2-4fc2-8433-432a06334757)

If I click maximize, then the window reappears again. If I can have a guess, it may have to do with the window not knowing on which Display screen it should be showing itself.

If I run into this again in the future, I will reopen.
