### ISSUE TITLE
Not Native Wayland Compatible Yet ?

### ISSUE THREAD

**Issue by Greatz08** [NationalSecurityAgency/ghidra#7210]
I am using hyprland (wayland compositor) and in this altho app is functional and working fine but the gui is overall blurry and since app gui is already kinda old style with that it makes things much more ugly in my opinion so i have doubts regarding wayland compatibility.
In my hyprland other apps are working fine as they are using wayland natively but this app is using xwayland which i think is the cause of this issue so is there anyway to force it run in wayland mode ? I tried with different environmental variable changes to force it to use wayland but still issue present so if possible do guide me on this.

Thankyou very much for this awesome open source project :-)

**Comment by ryanmkurtz** [comment]
We wouldn't really be controlling anything at the wayland level...that kind of things come from the JDK itself.  Maybe play with these values in `launch.properties`?

https://github.com/NationalSecurityAgency/ghidra/blob/22ddbc3f4b7363ad3694879038adeceb12ca96c6/Ghidra/RuntimeScripts/Common/support/launch.properties#L18-L25

**Comment by XVilka** [comment]
@Greatz08 the problem of JDK with Wayland is a long term project, and currently some JetBrains developers are leading the way. It would take couple more years probably to get new JDK released then propagated in all distributions and systems to solve this:
- https://youtrack.jetbrains.com/issue/JBR-3206
- https://wiki.openjdk.org/display/wakefield/Pure+Wayland+toolkit+prototype
- https://wiki.openjdk.org/display/wakefield/Work+breakdown

**Comment by DerEchteJoghurt** [comment]
Is there any update on this? It looks like WLToolkit is now stable enough.
IntelliJ-based IDEs are now using wayland by default: https://blog.jetbrains.com/platform/2026/02/wayland-by-default-in-2026-1-eap/

**Comment by ryanmkurtz** [comment]
Seems like you could add `VMARGS_LINUX=-Dawt.toolkit.name=WLToolkit` to `support/launch.properties` to test it?

**Comment by ryanmkurtz** [comment]
> Seems like you could add `VMARGS_LINUX=-Dawt.toolkit.name=WLToolkit` to `support/launch.properties` to test it?

Actually it looks like this isn't available in standard JDK's yet.

**Comment by claui** [comment]
> Seems like you could add `VMARGS_LINUX=-Dawt.toolkit.name=WLToolkit` to `support/launch.properties` to test it?

Using the [Wakefield](https://github.com/openjdk/wakefield) JDK ([AUR package](https://aur.archlinux.org/packages/jdk-openjdk-wakefield)), I’ve been able to launch Ghidra in Wayland:

```sh
JAVA_HOME=/usr/lib/jvm/java-25-openjdk-wakefield \
  /opt/ghidra/support/launch.sh bg jdk Ghidra '' \
  -Dawt.toolkit.name=WLToolkit ghidra.GhidraRun
```

and with HiDPI scaling:

```sh
JAVA_HOME=/usr/lib/jvm/java-25-openjdk-wakefield \
  /opt/ghidra/support/launch.sh bg jdk Ghidra '' \
  '-Dawt.toolkit.name=WLToolkit -Dsun.java2d.uiScale=2' \
  ghidra.GhidraRun
```

Screenshot from a 2x display on Sway:

<img width="2310" height="1600" alt="Image" src="https://github.com/user-attachments/assets/ad7bd811-3c0d-492e-93bb-626b918c2a69" />

**Comment by DerEchteJoghurt** [comment]
> Using the [Wakefield](https://github.com/openjdk/wakefield) JDK ([AUR package](https://aur.archlinux.org/packages/jdk-openjdk-wakefield)), I’ve been able to launch Ghidra in Wayland:

Awesome! I can confirm this makes launching Ghidra in Wayland possible.

Unfortunately this doesn't fix the scaling issues I was hoping to get rid of with native Wayland support. On a 4K monitor the UI is way too small and with `-Dsun.java2d.uiScale=2` it's too big for my 1440p monitor. I was hoping this would respect the scaling settings set in my wayland compositor (niri).

I'm not sure if this is something that needs to be implemented on Ghidra's end or if this is something on wakefields side.
