### ISSUE TITLE
Decompiler runs indefinitely / runs out of memory when a structure field is updated.

### ISSUE THREAD

**Issue by DualTachyon** [NationalSecurityAgency/ghidra#7212]
**Describe the bug**
The decompiler never ends / gobbles up all the memory when a certain structure field is updated.

**To Reproduce**
1) Import the .gzf, double click it, click "No" when Ghidra asks to analyse the database.
2) Go to the function "CCard_GetInstance"

No decompilation is observed and the progress bar is running indefinitely, because the field was added before saving.

3) Go to the structure "CCardInfo_t", and clear "CObject_79bccf90" at offset 0x18.

Now the decompilation works right away, once the field is cleared.

I've seen decompiler.exe grow over 10GB of RAM and gave up waiting for it to fill up my 32GB as it takes quite a while.

**Expected behavior**
Decompilation should not run indefinitely.

**Screenshots**

**Attachments**
I would prefer if the Ghidra database was not shared publicly.
Please let me know how I can supply this to you (email, some shared folder, etc).

**Environment (please complete the following information):**
 - OS: Windows 10 and 11, each with latest updates
 - Java Version: openjdk version "21.0.4" 2024-07-16 LTS
 - Ghidra Version: Public release 11.2.1, but it also happens with the latest master branch (grabbed @ commit ac58d20693c7d6e9b015d9e20b592bb2c02efba7)
 - Ghidra Origin: Both official GitHub distro and locally built.

**Additional context**

**Comment by DualTachyon** [comment]
There is another function that also "never ends" in the decompiler, it is labelled "big_deinit_function".
For this new one, I don't know which structure might be affecting it.

**Comment by DualTachyon** [comment]
> There is another function that also "never ends" in the decompiler, it is labelled "big_deinit_function". For this new one, I don't know which structure might be affecting it.

I fixed this one by correcting some type in a child function... So I suspect the problem in my original post is similar. Fixing a type would get rid of the infinite loop.

**Comment by kotcrab** [comment]
Here is a minimal example in gzf to reproduce this issue: [link](https://dl.kotcrab.com/tmp/issue-mips32.gzf).

It has only one function and two structures. After opening it just change the first function param to `Foo*` and the issue will trigger. Decompilation never ends and the decompiler process is using more and more memory.

Note that if you edit `Foo` structure and retype `ShortArray` field to simply `short[8]` then the decompilation finishes instantly.

Triggers issue:
![image](https://github.com/user-attachments/assets/20d4020a-36e2-42d9-8158-a37aa6c8b77d)

Works:
![image](https://github.com/user-attachments/assets/afdc879c-19cd-4d1c-aa36-665b752e15ee)

Ghidra 11.1.2 doesn't have this issue.

**Comment by DualTachyon** [comment]
Thanks for the fix! I can confirm all instances of endless decompilation are now gone.
