### ISSUE TITLE
Blatantly wrong decompilation (GBA)

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [NationalSecurityAgency/ghidra#7215]
![image](https://github.com/user-attachments/assets/816f18b1-2004-453c-9fb2-f9bcf4281aaa)
should be:
```
            gCurrentProjectile.pOam = (FrameData *)&sOam_58eb58;
            gCurrentProjectile.animationDurationCounter = 0;
            gCurrentProjectile.currentAnimationFrame = 0;
            gCurrentProjectile.timer = 0x46;
            gCurrentProjectile.movementStage++;
```

**Comment by emteere** [comment]
What the decompiler produces, IMHO, is more correct than using ++.
The value of movementStage is tested for ==1 to enter the scope that contains the instruction.
So at that line of code, movementStage should always be set movementStage = 2;
It is essentially a constant of 2 at that point.  To use ++ would be more confusing to read the code.

If it was inside of a loop, or code that could branch back to that statement, I would agree with you.
