### ISSUE TITLE
Add an executable launcher that can be pinned on task bar and startmenu

### ISSUE THREAD

**Issue by cowanweks** [NationalSecurityAgency/ghidra#7223]
Add the ability to launch ghidra with a start menu and taskbar icon.Launching ghidra on windows is always frustrating.

It would be easier if there could be an icon to launch the application directly from the start menu or task bar.

Something like below would be better,

![Screenshot 2024-11-25 144406](https://github.com/user-attachments/assets/4f357db6-5ad1-480d-916b-d6f46ae97570)

**Comment by cowanweks** [comment]
please assign me the issue, I already have the fix for that

**Comment by ryanmkurtz** [comment]
We used to provide something like this, but have decided to go the route of keeping our cross-platform support as simple and consistent as possible.
