### ISSUE TITLE
[API] Function count different in GhidraScript vs not w/ headless API

### ISSUE THREAD

**Issue by Cazra** [NationalSecurityAgency/ghidra#7224]
**Describe the bug**
I'm running Ghidra headless using its API and I've got some code that does some post-processing on the Program object after it is analyzed with Ghidra's headless analyzer. I've noticed that if I try to get the functions for the program within the context of a GhidraScript vs within just the same context as the headless analyzer, the number of functions yielded via `program.getListing().getFunctions(true)` differs. 

E.g. For the "Paranoid Fish" (https://github.com/a0rtega/pafish) program, I'm getting 147 total functions when running my postprocessor code in a GhidraScript. When I run the same postprocessor code not as a GhidraScript, I'm getting 145 total functions.

**To Reproduce**
1. Using Ghidra's API from the `ghidra.jar` file produced by the `buildGhidraJar` utility, analyze a program with the Ghidra headless analyzer API: `AutoAnalysisManager.getAnalysisManager(myProgram).startAnalysis(myMonitor)`
2. After call to `startAnalysis` completes, use `myProgram.getListing().getFunctions(true)` and count the number of functions.
3. Execute a GhidraScript that uses `myProgram.getListing().getFunctions(true)` and counts the number of functions in there.
4. Observe a difference in the count of functions depending on the context in which the postprocessor code runs.

**Expected behavior**
Function count in both versions of the post processor code (GhidraScript vs not in GhidraScript) is expected to be the same.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS
 - Java Version: 21.0.4
 - Ghidra Version: 11.2.1
 - Ghidra Origin: official GitHub distro

Here is the full (minimal) post-processor code I'm trying to run which I'm experiencing this discrepancy with:
```
    public void resolveUndefinedFunctions(Program program, TaskMonitor monitor)
            throws CancelledException {
        // Mostly just snarfed from an existing Ghidra script.
        AddressSet orphanSet = new AddressSet();
        Listing listing = program.getListing();

        InstructionIterator initer = listing.getInstructions(program.getMemory(), true);
        while (initer.hasNext() && !monitor.isCancelled()) {
            Instruction instruct = initer.next();
            orphanSet.addRange(instruct.getMinAddress(), instruct.getMaxAddress());
        }
        FunctionIterator iter = listing.getFunctions(true);
        while (iter.hasNext() && !monitor.isCancelled()) {
            Function f = iter.next();
            orphanSet.delete(f.getBody());
        }

        logger.info("resolveUndefinedFunctions orphan set size: %s".formatted(orphanSet.getNumAddressRanges()));

        if (orphanSet.getNumAddressRanges() == 0) {
            return;
        }

        int newFuncCount = 0;
        int blockCount = 0;

        IsolatedEntrySubModel submodel = new IsolatedEntrySubModel(program);
        CodeBlockIterator subIter = submodel.getCodeBlocksContaining(orphanSet, monitor);
        while (subIter.hasNext()) {
            CodeBlock block = subIter.next();
            blockCount++;
            Address deadStart = block.getFirstStartAddress();
            Function func = listing.getFunctionContaining(deadStart);
            if (func != null) {
                orphanSet.delete(deadStart,deadStart);
                continue;
            }

            Instruction instr = listing.getInstructionAt(deadStart);

            while (instr != null) {
                Function fun = listing.getFunctionContaining(instr.getAddress());
                if (fun != null) {
                    break;
                }
                boolean funCreated = createFunctionAt(program, instr.getAddress());
                if (funCreated) {
                    printf("Function created at %s.\n",instr.getAddress());
                    newFuncCount++;
                }
                instr = instr.getNext();
            }

        }
        logger.info("Count of resolved undefined functions: %s".formatted(newFuncCount));

        FunctionIterator fiter = program.getListing().getFunctions(true);
        int fcount = 0;
        for (Function func : fiter) {
            fcount++;
        }
        logger.info("Total function count: %s".formatted(fcount));
    }

    protected boolean createFunctionAt(Program program, Address entry) {
        Function func = program.getFunctionManager().getFunctionAt(entry);
        if (func == null) {
            CreateFunctionCmd createFunctionCmd = new CreateFunctionCmd(entry);
            createFunctionCmd.applyTo(program);
            func = program.getFunctionManager().getFunctionAt(entry);
            if (func == null) {
                return false;
            }
            return true;
        }
        return false;
    }
```

**Comment by ryanmkurtz** [comment]
Similar to #2639 and #5531

**Comment by Cazra** [comment]
Updated to include minimal sample code exhibiting the discrepancy.

**Comment by Cazra** [comment]
I think there is some misunderstanding. I'm not running the headless analyzer with the `analyzeHeadless` utility packaged with Ghidra. I built the `ghidra.jar` file using the `buildGhidraJar` utility, and I'm using that in a custom Java application.

**Comment by ryanmkurtz** [comment]
Yes, there was as misunderstanding.  I was confused by your use of the term `postScript`, which only has meaning to me in the context of a `HeadlessAnalyzer` Java object.

I now get that you are using a `ghidra.jar` as a library being used by some other program, but why are not going through the `HeadlessAnalyzer` class API?  This is the same API that calling `analyzeHeadless` from the command line uses.

Your use case would make more sense to me if i could see all of your code.  For example, I don't understand how you are getting `myProgram`.

**Comment by Cazra** [comment]
I'm not going through the `HeadlessAnalyzer` class API because I need access to the Program object after the analysis for my postprocessing and output needs (not as a postscript).

This is how the application is getting `myProgram`:
```
public Program loadProgram(File exeFile, TaskMonitor monitor) throws VersionException, InvalidNameException, DuplicateNameException, CancelledException, IOException {
	ProjectManager projectManager = new MyProjectManager() {};
	ProjectLocator locator = new ProjectLocator("absolute/path/to/projects/", "MyProject");

	Project project = new DefaultProject(projectManager , locator, false);
	MessageLog log = new MessageLog();

	LoadResults<Program> progLoadResults = AutoImporter.importByUsingBestGuess(exeFile, project , null, this, log, monitor);
	return progLoadResults.getPrimaryDomainObject();
}

// This exists just to allow access to the constructor
private static class MyProjectManager extends DefaultProjectManager {}
```

**Comment by ryanmkurtz** [comment]
After the HeadlessAnalyzer is finished, you should be able to open up the program from the project with something like

```java
DomainFile domainFile = project.getProjectData().getFile("/path/to/program/in/project");
Program program = (Program) df.getDomainObject(consumer, true, true, monitor);
```

**Comment by Cazra** [comment]
ok. I'll try redesigning my application to use that instead. Thanks!

**Comment by Cazra** [comment]
I'm having some issues with `DomainFile df = project.getProjectData().getFile(`path/to/my/sample.exe`)`. When I call this with the path to the exe I'm trying to analyze, the domainFile I get back is null. Is there some additional setup I need to do?

**Comment by Cazra** [comment]
The project is a temporary project that I create just before doing the headless analysis. It is then deleted afterwards. Should I try copying my program into the project's folder before analyzing it and get the DomainFile for that?

**Comment by ryanmkurtz** [comment]
I just wanted you to make sure your path string was right.  I forget if it should start with a `/`.  You could also try looping through as a sanity check with something like `projectData.getRootFolder().getFiles()`.  These are all just debugging suggestions.

**Comment by Cazra** [comment]
Okay, I finally got that to get the DomainFile correctly. I had to copy my exe into the project's folder, then construct a path that looks like `/myProgram.exe` corresponding to the actual path `rootFolderPath/projectName/myProgram.exe`.

It seems that in the results, I'm still seeing the original issue where it is missing the couple of functions though. :/

**Comment by ryanmkurtz** [comment]
Can you share how you calling the HeadlessAnalyzer class?

**Comment by Cazra** [comment]
```
	public void processLocal(String projectLocation, String projectName, String rootFolderPath,
			File file, ProgramHandler programHandler, TaskMonitor monitor) throws IOException {

		// If we are importing, need some files to import or at least a script to run!
		if ((filesToImport == null || filesToImport.size() == 0)) {
			Msg.warn(this, "REPORT: Nothing to do ... must specify file(s) for import.");
			return;
		}

		// // If importing, add trailing slash if it isn't there so that non-existent folders are created
		if (!rootFolderPath.endsWith("/")) {
			rootFolderPath += "/";
		}

		// Open the Ghidra project.
		File dir = new File(projectLocation);
		ProjectLocator locator = new ProjectLocator(dir.getAbsolutePath(), projectName);
		if (locator.getProjectDir().exists()) {
			project = openProject(locator);
		}
		else {
			Msg.info(this, "Creating " + (options.deleteProject ? "temporary " : "") +
				"project: " + locator);
			project = getProjectManager().createProject(locator, null, false);
		}
		project.close();

		// Analyze each file in `filesToImport` using HeadlessAnalyzer.
		try {
			Msg.info(this, "Doing headless analysis on sample %s".formatted(file.getAbsolutePath()));

			// Copy the sample into the project's folder.
			File projectFile = new File(locator.getProjectDir().getPath() + "/" + file.getName());
			Files.copy(Paths.get(file.getPath()), Paths.get(projectFile.getPath()));
				
			List<File> singleFileList= new ArrayList<>();
			singletonList.add(file);

			Program program = null;
			try {
				// Perform the headless analysis.
				HeadlessAnalyzer analyzer = HeadlessAnalyzer.getInstance();
				analyzer.processLocal(projectLocation, projectName, rootFolderPath, singleFileList);

				// Need to get the path of the sample relative to the rootFolderPath.
				String filePathInProject = "/" + file.getName();
				Msg.info(this, "Path to exe in project: %s".formatted(filePathInProject));

				// Access the program and run the postprocessing hook on it.
				project = openProject(locator);
				DomainFile df = project.getProjectData().getFile(filePathInProject);
				program = (Program) df.getDomainObject(programHandler, true, true, monitor);
				programHandler.postProcessHandler(program);
			}
			catch (Exception e) {
				String logErrorMsg = file.getAbsolutePath() + " Error during analysis: " + e.getMessage();
				Msg.error(this, logErrorMsg);
				e.printStackTrace();
			}
			finally {
				program.release(programHandler);
			}
		}
		finally {
			// Delete the temporary Ghidra projects folder.
			project.close();
			FileUtilities.deleteDir(locator.getProjectDir());
			locator.getMarkerFile().delete();
		}
	}

	private Project openProject(ProjectLocator locator) throws IOException {
		Project tempProject;

		if (options.deleteProject) {
			Msg.warn(this, "Project already exists and will not be deleted: " + locator);
			options.deleteProject = false;
		}

		Msg.info(this, "Opening existing project: " + locator);
		try {
			tempProject = new HeadlessProject(getProjectManager(), locator);
		}
		catch (NotOwnerException e) {
			log.error("Failed to open project due to {}", e.getMessage(), e);
			throw new IOException(e);
		}
		catch (LockException e) {
			log.debug("Failed to open project due to {}", e.getMessage(), e);
			throw new IOException(e);
		}

		return tempProject;
	}

	private HeadlessGhidraProjectManager getProjectManager() {
		if (projectManager == null) {
			projectManager = new HeadlessGhidraProjectManager();
		}
		return projectManager;
	}

	/**
	 * Ghidra project class required to gain access to specialized project constructor
	 * for URL connection.
	 */
	private static class HeadlessProject extends DefaultProject {
		HeadlessProject(HeadlessGhidraProjectManager projectManager, ProjectLocator projectLocator)
				throws NotOwnerException, LockException, IOException {
			super(projectManager, projectLocator, false);
		}
	}

	private static class HeadlessGhidraProjectManager extends DefaultProjectManager {
		// this exists just to allow access to the constructor
	}
```

**Comment by ryanmkurtz** [comment]
What is this doing?  
```
programHandler.postProcessHandler(program);
```

I was expecting you to use `analyzer.getOptions().setPostScripts()` to execute your GhidraScripts.

**Comment by ryanmkurtz** [comment]
The goal in suggesting the use of the `HeadlessAnalyzer` class was to mimic what happens when you run from the command line.

**Comment by Cazra** [comment]
That bit is running the code from the original post that I was originally running as a post-processor script. Then I was tasked with refactoring things so that the same post-processor code runs in the same Java context as the rest of the application. That's when I discovered the discrepancy in the function count.

**Comment by ryanmkurtz** [comment]
What do you mean "in the same Java context?"  GhidraScripts are run in the same JVM as the Ghidra application.

**Comment by Cazra** [comment]
I mean like the GhidraScripts don't have access to modules from the rest of my application, only those present in the GhidraScripts path, and they appeared to me to run in a separate JVM. I observed this like a few versions (about a year) ago. Maybe it's not like that now? Or maybe my observations were wrong. I don't know.

**Comment by Cazra** [comment]
Okay, I see that you're right now about GhidraScripts running in the same JVM.

**Comment by Cazra** [comment]
Is there a way to access modules in elsewhere in my application from within the GhidraScript? If that's possible, I think I could work with my postprocessing code running as a GhidraScript.

**Comment by ryanmkurtz** [comment]
I'm thinking the problem might have something to do with how GhidraScripts now use OSGi.  Tomorrow i'll take a look at that.  I think we are explicitly specifying what packages get imported into the GhidraScript and it might just be Ghidra-related ones.

**Comment by ryanmkurtz** [comment]
What error do you get at runtime when it can't find your application's classes?

**Comment by Cazra** [comment]
Nevermind, it seems that I am able to call modules in my application's jar from a GhidraScript after all. :)
