### ISSUE TITLE
Condense filler bytes in the middle of a function

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [NationalSecurityAgency/ghidra#7232]
GBA games have filler alignment bytes in the middle of functions in addition to between functions.
Some random example:
![image](https://github.com/user-attachments/assets/c0782211-81a9-489d-86fc-1ac6ebcb6feb)

**Comment by ryanmkurtz** [comment]
In the Script Manager, type `Condense` into the filter.  You will see some scripts there than might help you.

**Comment by ryanmkurtz** [comment]
Sounds like the perfect use for a custom script that you create.  That is too specific to add to Ghidra as a general purpose feature.
