### ISSUE TITLE
Keyboard way to clear selection has recently stopped working

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#7241]
Having upgraded to commit 6a818106fd, pressing `Esc` no longer clears a selection from either the `Listing:` or `Decompile:` panels.  Is there a keyboard alternative I've missed, or could one please be re-established?

**Comment by dragonmacher** [comment]
I probably broke this.  I'll look into it.

**Comment by dragonmacher** [comment]
It seems a bit strange to me that we had bound Esc to clear a selection.   I can't think of any other tools that work this way.  How would you feel about something different?  Perhaps Ctrl-Esc ?

**Comment by Wall-AF** [comment]
`Esc` is easier, 1 keystroke instead of 2!  Also, currently when performing a _redo_ (by pressing `Ctrl+Shify+z`), selection automatically starts up so subsequent cursor moves using the arrow keys extends a new selection making `Esc` very helpful in this situtation too!

**Comment by hippietrail** [comment]
> It seems a bit strange to me that we had bound Esc to clear a selection. I can't think of any other tools that work this way. How would you feel about something different? Perhaps Ctrl-Esc ?

The one place I can think of where I always use this is the URL bar of Chrome.

**Comment by Wall-AF** [comment]
@ryanmkurtz Please reeopen this issue.

There are still some situtations not covered by this fix, when deciding not to rename something in the following panels:
1) `Program Trees` 
2) `Symbol Tree`
3) `Data Type Manager` - all of them
4) `Enum Editor`
5) `Structure Editor` - `Name` & `Comment` fields, strangely not the `DataType` field
Their maybe more!

**Comment by dragonmacher** [comment]
I tried editing and pressing Escape to cancel the edit in the providers from your list above.  All edits seem to cancel as expected for me.

Can you give more information about what you are trying and the behavior you are seeing?

**Comment by Wall-AF** [comment]
The image below is representative of 1-3 & 5
![Image](https://github.com/user-attachments/assets/52d30925-5147-45c9-a0a6-2f392bfae9c2)
Pressing `<Esc>` does nothing, `<Enter>` is the only option to get out of editing mode!  Even pressing `<Tab>` (in 1-3) doesn't cancel it, but in 5 it moves to the next editable field.

With the `Enum Editor`(4)
![Image](https://github.com/user-attachments/assets/dfd7ab60-e165-455d-9b3c-86656d34353d)
Pressing `<Esc>` brings up this dialogue
![Image](https://github.com/user-attachments/assets/4184fbed-1d65-48dd-aa2b-b49b85dab093)
where choosing the 1st option closes the editor, allowing you to discard all updates (not helpful when several changes have been made), and the 2nd does nothing.

This is on a Windows 11 version 23H2 (OS build 22631.4751) machine,

**Comment by Wall-AF** [comment]
I don't know if this is significant, but I have multiple `CodeBrowser` independent windows open simultaneously.  (Navigation is easier this way.)

**Comment by dragonmacher** [comment]
I was able to reproduce it now.  Thanks for the info.

**Comment by Wall-AF** [comment]
Don't know if this is related but in the `Structure Editor`, if you change either the `Name`or`Comment` fields and close the editor without saving, no prompt is given and the changes are lost.  Changes in every other field result in a prompt to save if you haven't already!

**Comment by dragonmacher** [comment]
It is indeed related.

**Comment by Wall-AF** [comment]
While you're looking at this, there's a great feature in the `Structure Editor` member table that when you press `<F2>` to enter an editable component (and the highlighted field isn't editable) it automatically moves to the next one that is. Could this be applied to the `Edit Function` `Function Return/Parameters` table as that would be very helpful.

**Comment by Wall-AF** [comment]
@dragonmacher thanks.

**Comment by dragonmacher** [comment]
> [@dragonmacher](https://github.com/dragonmacher) thanks.

You're welcome.  The most recent fix only addressed the Escape issue.  I'm now exploring your last request regarding F2 in the function editor table.

**Comment by Wall-AF** [comment]
> While you're looking at this, there's a great feature in the `Structure Editor` member table that when you press `<F2>` to enter an editable component (and the highlighted field isn't editable) it automatically moves to the next one that is. Could this be applied to the `Edit Function` `Function Return/Parameters` table as that would be very helpful.

Thanks once again @dragonmacher.  This is handy, although it does work slightly differently but just as great.

**Comment by Wall-AF** [comment]
This has reared its ugly head again since commit e804e1a01d!

**Comment by dragonmacher** [comment]
We fixed quite a few issues related to this ticket.   Which of these features is not working for you?

**Comment by Wall-AF** [comment]
Pressing `Esc` no longer clears a selection from either the Listing: or Decompile: panels.

**Comment by dragonmacher** [comment]
I just tried this in master.   This is working in the Listing.   It is not working in the Decompiler, but I don't think we have an action for it to work in the Decompiler.

I had to add the `Esc` key binding in my options.  Once I did that, it worked as expected in the Listing.

**Comment by Wall-AF** [comment]
Oh thanks  I'll try it tomorrow.

**Comment by Wall-AF** [comment]
Can't find `Clear Selection` (or equivalent) in the below option list!  What am I missing?
![Image](https://github.com/user-attachments/assets/1976fcbd-6b85-42f0-b6d0-33cf24abd465)
The `KeyBinding` for the `CodeBrowserSelectorPlugin` is already set to `ESCAPE`.

**Comment by Wall-AF** [comment]
Btw @dragonmacher, when in the `Listing:`panel, if you select a small portion of text,, say a class/namespace qualifier to copy, pressing `<ESC>` doesn't clear that selection either!

**Comment by dragonmacher** [comment]
![Image](https://github.com/user-attachments/assets/fc052704-d05d-4d93-8b9c-a01a5b960265)

Regarding the word-based selection, I'm not sure that has ever worked.   The current action changes `Program Selection`s, but the single word text selection is a character selection.   We could fix that, if it is deemed useful.

**Comment by Wall-AF** [comment]
> ![Image](https://github.com/user-attachments/assets/fc052704-d05d-4d93-8b9c-a01a5b960265)

That's already set and whole lines do clear in the `Listing:` panel.  Couldn't find the equivalent for the `Decompile:` panel!

> 
> Regarding the word-based selection, I'm not sure that has ever worked. The current action changes `Program Selection`s, but the single word text selection is a character selection. We could fix that, if it is deemed useful.

It used to.

**Comment by dragonmacher** [comment]
Looks like your are right.  I see that it cleared character selections in an older version.

**Comment by dragonmacher** [comment]
This should be fixed in master.

**Comment by Wall-AF** [comment]
> This should be fixed in master.

It still does not work fom the `Decompile:` panel.

**Comment by dragonmacher** [comment]
That is correct.  The feature was not designed to work in the Decompiler.   However, I have a change in review that should fix this.

**Comment by Wall-AF** [comment]
> That is correct. The feature was not designed to work in the Decompiler. However, I have a change in review that should fix this.

Maybe so, but it used to.
