### ISSUE TITLE
"Select File to Import" dialog doesn't remember the last directory if it was used to import via a `FileSystem`

### ISSUE THREAD

**Issue by hippietrail** [NationalSecurityAgency/ghidra#7266]
**Describe the bug**
When you import a file with the "Select a File to Import" dialog, it remembers the last directory if you imported a file directly.
But it does not remember the last directory if you imported a file from a `FileSystem` (zip, tarball, disk image, etc) in the directory.

**To Reproduce**
1. Identify two directories on your system. One with some zips or tarballs, and another with just regular files.
2. Import a regular file the latter directory.
3. Use import again. Notice that this time you didn't have to navigate to the same directory.
4. Import a file from inside a zip or tarball from the former directory.
5. Use import again. Notice that this time it did not remember the same directory and you had to navigate to it again.

**Expected behavior**
Select File to Import dialog remember the last used directory no matter whether it was used to load a file directory or load a file from within a `FileSystem`.

**Environment (please complete the following information):**
 - OS: macOS 15.0.1
 - Java Version: 23
 - Ghidra Version: 11.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
I thought I fixed this in master. I'll check tomorrow.

**Comment by hippietrail** [comment]
> I thought I fixed this in master. I'll check tomorrow.

I haven't built my local repo for a while. I'll give it a look.

**Comment by ryanmkurtz** [comment]
Already fixed by 95321015d947b2c0d74d8b06f03109bfb8af2541

**Comment by ryanmkurtz** [comment]
I see this was fixed in 11.2 which is what you said you were using, so i'll have to look into the behavior you describe.

**Comment by hippietrail** [comment]
> 9532101

I can now confirm that it also happens in my build of the repo and in 11.2.1

**Comment by ryanmkurtz** [comment]
I think the work i did was to make it remember `File -> Open File System`, but if you are doing `File -> Import File` and then selecting a file system...it may not use that is the last location for your next Import File.  Does that describe the behavior your are seeing?

**Comment by hippietrail** [comment]
> I think the work i did was to make it remember `File -> Open File System`, but if you are doing `File -> Import File` and then selecting a file system...it may not use that is the last location for your next Import File. Does that describe the behavior your are seeing?

Yes when I'm working on my Loaders and FileSystems I'm always just pressing the "i" key to import a file and then double-click on a filesystem. I've rarely used "Open File System".
