### ISSUE TITLE
Windows PE with incorrect length in IMAGE_DEBUG_MISC

### ISSUE THREAD

**Issue by kapstok** [NationalSecurityAgency/ghidra#7285]
Hello,

I have a question related to finding a solution for a problem with decompiling a Windows PE. I take the master branch (as of writing 97aadfa05aa63a3e667ccf6ea9647dfae152074a) as base for the comment I make per line.

When Ghidra tries to import the executable, a part of the executable is read containing the bytes:

```
01 00 00 00  00 00 00 00  00 00 00 00  47 6F 4C 69  6E 6B 2E 64 62 67 00
```

These bytes represent an `IMAGE_DEBUG_MISC` struct. So the code in Ghidra is eventually executed at `DebugMisc.java:79`:

```java
		reader.setPointerIndex(index);

		dataType = reader.readNextInt();
		length = reader.readNextInt();    // <--- Line 79
		unicode = reader.readNextByte() == 1;
		reserved = reader.readNextByteArray(3);
		if (length > 0) {
			actualData =
				(unicode ? reader.readNextUnicodeString(length) : reader.readNextAsciiString());
		}
```

Here, the length will be determined by the value of the bytes that are currently read. At time of execution, the value will be 0 (so length will be 0 as well). This will lead to further problems in the execution (at `DebugMisc.java:167`):

```java
struct.add(new StringDataType(), length - 12, "Data[]", "Actual data");
```

Having a negative length will eventually result in an error (at `DataTypeComponentImpl.java:373`):

```java
		if (length <= 0) {
			throw new IllegalArgumentException("Positive length must be specified for " +
				dataType.getDisplayName() + " component");
		}
```

Now I would think this could be solved by looking for the `sizeOfData` from `DebugDirectory` and use that if it is bigger than the length that was provided by the PE:

```java
length = reader.readNextInt();
// (...)
if (debugDir.getSizeOfData() > length) {
    length = debugDir.getSizeOfData();
}
```

This works, but it seems as a very fragile solution. Is there a way to fix this problem with a less fragile code?
Would it be worth the effort to come up with a solution that could potentially be merged with Ghidra? 

Kind regards,
Jan

**Comment by d-millar** [comment]
Any chance you could point us at the actual executable?  The tricky part in most of these fixes is making sure Ghidra’s loader behaves in the same way the Window’s loader does.

**Comment by kapstok** [comment]
This is where I downloaded the executable from:
https://github.com/ksw2000/x64-NASM-Practice/raw/7ad65a21e73414b774b50c7c4f0f100db603b60f/tools/GoLink.exe

**Comment by d-millar** [comment]
OK, am putting a ticket in for this (and probably the fix).   The windows loader essentially ignores this data, so I guess I'm less concerned on that front.  Am leaning toward defaulting the length to 12 and increasing it by actualData.length()+1 if the unicode field is not set and the actualData.length()+13 < IMAGE_SIZEOF_DEBUG_DIRECTORY.  Thoughts?

**Comment by kapstok** [comment]
I think that an alternative could be that you could guess the length by first reading 12 bytes, and then count the amount of ASCII bytes until you see byte `00`. Then check if the length as described by IMAGE_DEBUG_MISC is equal to `12 + amount of ASCII bytes`. If this is not equal, use the length we guessed. I don't know if this is the same way how actualData is retrieved. And this would not work with unicode and it is still a bit error prone. So I don't know if this is the best solution, but why not mention it? I also don't know if there could be more data after IMAGE_DEBUG_MISC struct in a debug directory. My solution could also work if this is the case.

And obviously I would recommend to log on debug level that we see an incorrect length. If some bug occurs with an executable because we make wrong assumptions here, I can imagine debugging would be more difficult than necessary.

And we could consider informing the user that the executable that is imported, does something unorthodox, namely giving an incorrect length.

**Comment by kapstok** [comment]
And you could combine this with the solution you suggested: first look at the length from IMAGE_DEBUG_MISC and compare it with the guessed length. If they're not equal, also check if the guessed length is smaller or equal to IMAGE_SIZEOF_DEBUG_DIRECTORY before using the guessed length.

**Comment by d-millar** [comment]
@kapstok The call that retrieves actualData will pull until it finds the null, so I think we're on the same page here.  If the length is non-zero, I'm going to defer to the reported length.  My impression is that allowing zero is basically a shortcut to tell the consumer that there's better info available elsewhere.  That said, per your original point, given it's allowed, we shouldn't be creating negative lengths and throwing related errors.  I have a fix in - should be in master in a few days.  Pretty wild to actually see this field in use - I literally haven't since this used in a decade.  :)

**Comment by kapstok** [comment]
Ah, great to have a fix quickly. If I accidentally stumble again upon some ancient field that makes Ghidra throw an error, I'll let you know ;)
