### ISSUE TITLE
Pasting into bytes editor not working

### ISSUE THREAD

**Issue by orangecms** [NationalSecurityAgency/ghidra#7290]
**Describe the bug**
The bytes editor, essentially like a hex editor, lets me manually enter data. There is a toggle to turn on/off editing, and there is a paste button. With edit turned on, I cannot paste though; it has no effect. I copied data from elsewhere within the bytes editor, being unsure about the format, though to no avail. I verified that the data is in my clipboard, being able to paste it in another app.

**To Reproduce**
1. Open the bytes editor
2. Toggle edit on
3. Select + copy data from the editor
4. Try pasting it elsewhere in the editor, using the button or Ctrl+V, neither works

Alternatively, write down some hex value in some other app, say `1234abcd`, and try copy-pasting that.

**Expected behavior**
The data should be pasted.

**Screenshots**
n/a

**Attachments**
n/a

**Environment (please complete the following information):**
 - OS: Pop!_OS (Ubuntu derivative)
 - Java Version: no idea, whatever Flatpak does
 - Ghidra Version: 11.2.1
 - Ghidra Origin: Flatpak

**Additional context**
n/a

**Comment by d-millar** [comment]
Did you clear any code/data at the location where you pasted the bytes?

**Comment by orangecms** [comment]
Oh whew, indeed, pasting works when I remove the type annotations I had already prepared.
Thank you!

This issue may turn into an enhancement suggestion then to allow pasting either way. A prompt dialog is shown anyway.
