### ISSUE TITLE
Disable sidewards/horizontal scrolling

### ISSUE THREAD

**Issue by Bixilon** [NationalSecurityAgency/ghidra#7297]
**Is your feature request related to a problem? Please describe.**
I am really frustrated, because ghidra is pretty much unusable for me on a laptop. Everytime I am scrolling through code, I am accidentially scrolling sidewards (it just happens on a touchpad) and the threshold is so low, that I am instantly going back or forward thus jumping through code.

See: https://www.reddit.com/r/ghidra/comments/1fv1uzh/jumping_to_different_places_when_scrolling/?rdt=48158
**Describe the solution you'd like**
Option to disable sidewards forward/backwards going.

Thank you!

**Comment by ryanmkurtz** [comment]
Are you on a mac?

**Comment by Bixilon** [comment]
No, on kde linux. There is no option to disable horizontal scrolling easily on wayland.

**Comment by ryanmkurtz** [comment]
This seems to be a duplicate of #7024.  Can you please read through that thread to see if any of the suggestions work for you?

**Comment by Bixilon** [comment]
Yes, that is an exect duplicate. However the workaround does work, but only for the decompiler and not for the disassembler.
