### ISSUE TITLE
Access denied when selection options while importing file

### ISSUE THREAD

**Issue by sylveon** [NationalSecurityAgency/ghidra#73]
**Describe the bug**
Ghidra attempts to open a file in its installation folder in write instead of opening it in read-only.

**To Reproduce**
1. Install Ghidra in a read-only location (like Program Files)
2. Import a file in a new project
3. In the import dialog, press "Options..."

**Expected behavior**
No error, options window opens

**Screenshots**
![image](https://user-images.githubusercontent.com/6440374/53915392-d0112000-402d-11e9-9a25-d18226dd9ba4.png)

**Environment (please complete the following information):**
 - Windows 10 October 2018 update
 - Ghira 9.0 public release

**Comment by sylveon** [comment]
If I ignore this problem and continue with the import, more of the same error happens

![image](https://user-images.githubusercontent.com/6440374/53915688-69403680-402e-11e9-9b1b-3046d927e5df.png)

![image](https://user-images.githubusercontent.com/6440374/53915697-6e9d8100-402e-11e9-8f27-c371a6705f6a.png)

**Comment by gnooby22** [comment]
Install Ghidra where you have write permission as a user.

**Comment by sylveon** [comment]
If that's the case, (and if Ghidra gets an installer at some point) wouldn't it be a better idea to use a per-user profile folder somewhere to store the compiled spec, or distribute pre-compiled specs?

**Comment by nsadeveloper789** [comment]
The pre-compiled specs should be included in the distribution package. It's likely the timestamps on your ```.sla``` files got munged. We just added an explanation to our FAQ.
