### ISSUE TITLE
repne stosd/stosb loop not recognized by the decompiler

### ISSUE THREAD

**Issue by reversodroid** [NationalSecurityAgency/ghidra#731]
**Describe the bug**

`repne stosd/stosb` don't get properly identified by the decompiler and result in two single instructions instead of loops.
The asm instructions do not seem to disas the `repne` either.

I've attached the screenshots below with the same code as seen by IDA.

The binary is also attached below.

**Screenshots**

Below are screenshots of how ghidra sees the code:

![ghidra_decompil](https://user-images.githubusercontent.com/52283212/60378262-e03e7800-99ed-11e9-8b15-80c214bf8cd6.png)

![ghidra_asm](https://user-images.githubusercontent.com/52283212/60378260-d1f05c00-99ed-11e9-82d3-9e8a701c9d4f.png)

and how IDA sees it:

![ida_decompil](https://user-images.githubusercontent.com/52283212/60378265-eaf90d00-99ed-11e9-8cf1-9f29ab2aee4c.png)

![ida_asm](https://user-images.githubusercontent.com/52283212/60378268-ee8c9400-99ed-11e9-8e30-75b606aa378c.png)

**Attachments**

This file is the binary where the issue was found. **WARNING** this is a malware, do not execute (zip password is *infected*)

[3f370462d267298a130624ee61f603ac_unpacked.exe.zip](https://github.com/NationalSecurityAgency/ghidra/files/3341289/3f370462d267298a130624ee61f603ac_unpacked.exe.zip)

**Environment:**

 - Java Version: openjdk 12.0.1
 - Ghidra Version: 9.0.4

**Comment by caheckman** [comment]
Hmm.  "repne stosb" and "repne stosd" aren't technically legal assembly.  However, the byte encodings "F2 AA" and "F2 AB" seem to get executed as "rep stosb" and "rep stosd".
