### ISSUE TITLE
Decompilation failure due to overlapping input varnodes

### ISSUE THREAD

**Issue by metal-crow** [NationalSecurityAgency/ghidra#732]
**Describe the bug**
When decompiling the attached function, the decompiler fails with the error "Low-level Error: Overlapping input varnodes". I've attached the debug function decompilation output, which hopefully should be enough to replicate it, but i can upload the repo or other outputs as needed.

Hex-Rays does successfully decompile this function, the output of which i have also attached.

**Attachments**
[Ghidra debug output](https://github.com/NationalSecurityAgency/ghidra/files/3341425/debug.txt)
[Hex-Rays decompilation output](https://github.com/NationalSecurityAgency/ghidra/files/3341435/ida_output.txt)

**Environment:**
 - OS: Windows 10 Pro Version 1809
 - Java Version: 11.0.3
 - Ghidra Version: 9.0.4

**Comment by caheckman** [comment]
Duplicating this. Here is a workaround patch. It should work either on a distribution (i.e. 9.0.4) or on a pull of the repo.  From the root direction
`patch -p1 < ~/killedbycallpatch.txt`

[killedbycallpatch.txt](https://github.com/NationalSecurityAgency/ghidra/files/3360112/killedbycallpatch.txt)

**Comment by caheckman** [comment]
Implemented a more complete fix, which should be in master with the next update.
