### ISSUE TITLE
Using dbgeng the Debugger launches the program with unexpected current directory causing EXE launch to fail

### ISSUE THREAD

**Issue by gynt** [NationalSecurityAgency/ghidra#7329]
**Is your feature request related to a problem? Please describe.**
Using python + dbgeng as the debugging setup, the .exe is launched with `Ghidra/Debug/Debugger-agent-dbgeng/data/debugger-launchers` as the current directory for the process. This is unexpected, as typically, the current directory for a process is either the path to the folder containing the .exe, or the path of the calling process. Since the program is launched within `debugger-launchers`, an .exe fails to launch if it expects files and folders relative to the .exe location.

**Describe the solution you'd like**
I would like the solution that we can specify which directory the program will be run in.

**Describe alternatives you've considered**
Manipulating the exe to set the current directory to the folder the .exe is in. Hacky at best.

**Additional context**
I am on 11.1, not sure if it has been addressed since then, I can't find any mention of it on GitHub. I searched using `Debugger Current Directory`

**Comment by d-millar** [comment]
@gynt If you use the extended version of the launcher, you can set the “Initial Directory”.

**Comment by gynt** [comment]
> @gynt If you use the extended version of the launcher, you can set the “Initial Directory”.

@d-millar How can I use the extended version? Where is it located? Or is that an 11.2 feature?

![image](https://github.com/user-attachments/assets/4cf74f2d-bc14-4286-8a6e-4a980c5d0b95)

![image](https://github.com/user-attachments/assets/44c66077-3c82-436b-9f3f-a91cd2dc6fbd)

**Comment by d-millar** [comment]
Yes, sorry - 11.2.  The launcher is listed as “dbgeng-ext”.

**Comment by Redplcs** [comment]
I'm sorry for opening this issue, but I have same problem and I could not update ghidra. I've tried to launch debugger on 11.2 version, but I'm getting error with "frontend is 11.2, but backend is 11.1". I have no idea how to resolve it, so I keep staying on 11.1

My question: Is there any command prompt for dbgeng on 11.1 to change initial directory?

**Comment by d-millar** [comment]
@Redplcs Right, not the greatest message, I'm afraid.  What it's really saying is "You're using Ghidra 11.2, but the version of Python being used has modules installed (ghidratrace, ghidradbg, ghidragdb, ghidralldb) from 11.1.  The solution kind of depends on how you've installed things.  Specifically, the launchers for the various debugger agents attempt to build up a PYTHONPATH with the current versions and use that to find the modules, but, if you pip-installed versions, the pip-installed versions are going to override those from the PYTHONPATH.

The first thing I would do is make sure you know the path to the version of Python being executed.  (Maybe not a problem, but I have multiple versions of Python around and always get burned by this.)  Next, use "python -m site" to find the site-packages (or dist-packages) it uses.  Ignoring the GHIDRA_HOME packages, check those paths for any ghidraXXX packages.  Presumably, you'll find some marked 11.1 which you'll want to delete.

If that's not the case (or it doesn't solve the problem), give us another shout!
