### ISSUE TITLE
How to get the address of vertex in Function graph by using some python api?

### ISSUE THREAD

**Issue by Kingkingyoung** [NationalSecurityAgency/ghidra#734]
I want to get the basic block in Function graph by containing address,and then get the start address and end address of it.How to get it?

**Comment by saruman9** [comment]
See #92, #444, #613.

**Comment by ryanmkurtz** [comment]
Thanks, @saruman9.  Did you get what you needed from that @Kingkingyoung?

**Comment by Kingkingyoung** [comment]
> Thanks, @saruman9. Did you get what you needed from that @Kingkingyoung?
Not yet,Code Block or Code unit is not what I want.I want to get a vertex(in function graph view) start/end address by a containg address.I found getBasicBlocks() in ghidra.program.model.pcode.PcodeSyntaxTree and the class PcodeBlockBasic seems has start/end address.But I have not find how to get it properly.How to get it or 
![vertex](https://user-images.githubusercontent.com/16135248/60474943-6fc28000-9ca7-11e9-832a-7cba3ef0ccda.PNG)
e.g I want to get address 8e48 and 8e59 by any address in this block

**Comment by saruman9** [comment]
```python
from ghidra.program.model.block import BasicBlockModel

basicBlockModel = BasicBlockModel(currentProgram)
codeBlocks = basicBlockModel.getCodeBlocksContaining(currentAddress, monitor)
listing = currentProgram.getListing()

for codeBlock in codeBlocks:
    print listing.getCodeUnitContaining(addressRange.getMinAddress()).getAddress(), listing.getCodeUnitContaining(addressRange.getMaxAddress()).getAddress()
```

**Comment by Kingkingyoung** [comment]
> ```python
> from ghidra.program.model.block import BasicBlockModel
> 
> basicBlockModel = BasicBlockModel(currentProgram)
> codeBlocks = basicBlockModel.getCodeBlocksContaining(currentAddress, monitor)
> listing = currentProgram.getListing()
> 
> for codeBlock in codeBlocks:
>     print listing.getCodeUnitContaining(codeBlock.getMinAddress()).getAddress(), listing.getCodeUnitContaining(codeBlock.getMaxAddress()).getAddress()
> ```

Thanks! This is exactly what I want.Thanks again!

**Comment by Kingkingyoung** [comment]
> ```python
> from ghidra.program.model.block import BasicBlockModel
> 
> basicBlockModel = BasicBlockModel(currentProgram)
> codeBlocks = basicBlockModel.getCodeBlocksContaining(currentAddress, monitor)
> listing = currentProgram.getListing()
> 
> for codeBlock in codeBlocks:
>     print listing.getCodeUnitContaining(codeBlock.getMinAddress()).getAddress(), listing.getCodeUnitContaining(codeBlock.getMaxAddress()).getAddress()
> ```

And I will close this issue.

**Comment by ryanmkurtz** [comment]
Thanks @saruman9!
