### ISSUE TITLE
Decompiler shows MAX_INT instead of -1 ?

### ISSUE THREAD

**Issue by Piruzzolo** [NationalSecurityAgency/ghidra#735]
I have the following PowerPC disassembly (pcode on the right)

![data1](https://user-images.githubusercontent.com/11365978/60387977-29083680-9aab-11e9-8e46-fc05878430bb.png)

As you can see, it loads an immediate value (`li` opcode). 

Here what I see in the decompiler:

![data2](https://user-images.githubusercontent.com/11365978/60387989-59e86b80-9aab-11e9-9ce1-d33ab2026b0b.png)

Could this be improved?

**Comment by nik0sc** [comment]
Well it looks like the type of uVar2 should be signed instead of unsigned?

**Comment by Piruzzolo** [comment]
Yep, that's indeed be the problem. Maybe Ghidra could detect it and change types accordingly?

**Comment by nik0sc** [comment]
I'm not sure what you mean, Ghidra can't infer that `r3 <- EXTS(64, ffff)` is supposed to represent -1 or MAX_INT, that's why it lets you set the types of variables in the decompiler.

**Comment by Piruzzolo** [comment]
We could make it heuristically assume it is a -1 and show a comment saying it is just assumed, then if we find it's wrong we may have a little option to chenge it to MAX_INT. 
Or the opposite, based on a option set in the preferences. Or nothing, as we like. Also we could introduce a keyboard shortcut/button to toggle it when highlighting the number.
I guess defaulting with -1 is fine most of the time (true? I rarely see a MAX_INT comparison in my reversed code). An heuristic to go with MAX_INT could be something like when we find a comparison expression with `abs()`, maybe, but enumerating all cases would be way too complex I guess.
