### ISSUE TITLE
project 8051

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#736]
Using master, running `gradle test` results in `Could not resolve project :8051`

**Comment by ryanmkurtz** [comment]
Did that error appear immediately when you ran the command, or deep into the tests?

**Comment by mumbel** [comment]
I think it was pretty early on.  I basically ending up copy the x86 build.gradle to 8051 and cleaned up strings to get around it

**Comment by ryanmkurtz** [comment]
Good catch with the `apply plugin: 'java'`.  We recently changed a lot about how these project build.gradle files look, and it looks like this project slipped through the cracks.  I also noticed that this project's script, Update8051.java, doesn't get included in Eclipse as source.  It's probably related.

**Comment by ryanmkurtz** [comment]
@mumbel, I made a change that might fix this.  Would you mind trying it out? I can't reproduce your exact issue.

**Comment by mumbel** [comment]
Np, i will report back if broken
