### ISSUE TITLE
Broken link in the Contributing/Contributor's Guide

### ISSUE THREAD

**Issue by HenryGlendening** [NationalSecurityAgency/ghidra#74]
**Describe the bug**
There is a link on the 'Contributor's Guide' (CONTRIBUTING.md) for the text 'developer's guide' that leads to a GithHub 404 error page

**To Reproduce**
1. Go to CONTRIBUTING.md
2. Scroll to the section near the bottom, 'Getting Started'
3. Click on the linked text for 'developer's guide'
4. See 404 error

**Expected behavior**
I expect my browser to navigate to the 'developer's guide'

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 12.0.2

**Comment by ctubbsii** [comment]
Closing as duplicate of #11
