### ISSUE TITLE
IDA XML Exporter Fails on Stack Variable Comments

### ISSUE THREAD

**Issue by bclodfelter1024** [NationalSecurityAgency/ghidra#748]
**Describe the bug**
1) IDA Export XML plug in fails when exporting IDA database when function stack variables have comments.
2) Failure message itself fails to properly display failure message. 

**To Reproduce**
1. Open IDA with Program Database that has commented stack variables
2. Run IDA XML Exporter (Edit, Plugins, XML Exporter)
3. Select all options on Option screen.
4. Press 'OK'
5. Supply filename when requested, Press Save.
6. Error message appears. Error message itself fails with name space error.

**Expected behavior**
No error message. Successful export.

**Screenshots**

**Attachments**

**Environment (please complete the following information):**
 - OS: Win10 Home, Version	10.0.18362 Build 18362
 - Java Version: JAVA_VERSION="11.0.2", JAVA_VERSION_DATE="2019-01-15"
 - Ghidra Version: [e.g. 9.0.4]
 - IDA Version 7.3.190614 Windows x64 (32-bit address size)

**Additional context**
Apparent bug in IDAXML.PY file supplied with Ghidra.
Starting at Line 1536:
            if regcmt != None:
                regcmt  = ida_lines.tag_remove(regcmt + " ", 0)
            if rptcmt != None:
                rptrcmt = ida_lines.tag_remove(rptcmt + " ", 0)

Method ida_lines.tag_remove() accepts only one argument. The calls on lines 1537, and 1539 have two, resulting in an error when a regular or repeating comment is attached to a stack variable causing these lines to execute.

IDAXML.PY file also adds a space character to strings passed to tag_remove. A comment in the file indicates that this is necessary to avoid trimming the last character of the supplied string. This did not appear to be necessary with my setup.

Corrected code:
	if regcmt != None:
		regcmt	= ida_lines.tag_remove(regcmt) 
	if rptcmt != None:
		rptrcmt = ida_lines.tag_remove(rptcmt) 

2) Error message screen text error. 

The file XML_Exporter.py line 61:
            except:
                ida_kernwin.hide_wait_box()
                msg = "***** Exception occurred: XML Exporter failed! *****"
                print "\n" + msg + "\n", sys.exc_type, sys.exc_value
                idc.warning(msg)

When this code is executed access to sys.exc_type and sys.exc_value results in this error:
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/Program Files/IDA Starter 7.3/plugins/xml_exporter.py", line 64, in run
    print "\n" + msg + "\n", sys.exc_type, sys.exc_value
NameError: global name 'sys' is not defined

**Comment by zt-chen** [comment]
I've created a pull request(#3309) for this issue. It works for me on ida 7.0
