### ISSUE TITLE
Simplify `a >> 31` to 0 for integer a?

### ISSUE THREAD

**Issue by Piruzzolo** [NationalSecurityAgency/ghidra#751]
When we have `val >> 31`, with val as `int`, coming from i.e the x86 `SHR `instruction

`c1 ee 1f           SHR   ESI,0x1f`

IDA Pro simplifies it to `0`, i.e. discards it (see below). Would it be formally correct to implement in Ghidra?

Here what Ghidra does:

```C
    uVar7 = this->a / 3 + (this->a >> 31);
    iVar12 = (uVar7 >> 31) + uVar7;
    uVar7 = *(int *)&this->b / 3 + (*(int *)&this->b >> 31);
    iVar10 = (uVar7 >> 31) + uVar7;
```

IDA:

```C
  v1 = this;
  v2 = this->a / 3;
  v3 = this->b / 3;
  v30 = this->a / 3;
  v32 = this->b / 3;
```

The vars ar all `int`

**EDIT**

Done some experiments, it looks like it gives `0` if the number is positive, `-1` if negative or if overflows.
So it must be a valid simplification. It would be appliable if `var` is a positive constant and if `unsigned`?

**Comment by partoftheworlD** [comment]
you can fix it yourself in ia.sinc

:SHR rm32,imm8  is vexMode=0 & opsize=1 & byte=0xC1; rm32 & check_rm32_dest ... & reg_opcode=5 ... ; imm8     
{   
    local count = imm8 & 0x1f;
    if ( count == 0x1f) goto <END>;
    local tmp = rm32;
    rm32 = rm32 >> count;
    build check_rm32_dest;
    shrflags(tmp, rm32,count);
    shiftresultflags(rm32,count);
    <END>
}

**Comment by Piruzzolo** [comment]
Is it correct though? The Intel manual says it is to be set to the `LSB` (`CF ← LSB(DEST)`), but I don't know if doing so it prevents optimizations. I've created a PR for this

**Comment by partoftheworlD** [comment]
I think not. It is rather a fix in haste, while we wait for a normal fix from developers.

**Comment by Piruzzolo** [comment]
It should be better implemented with a decompiler `Rule`, I guess. We need to specify this is valid only for unsigned/positive constants or stuff like that

**Comment by mumbel** [comment]
> Done some experiments, it looks like it gives 0 if the number is positive, -1 if negative or if overflows.

This statement is confusing because (with MSB==1 and count==0x1f) SAR is signed divide by 2, imm8 times, would result in -1.  While SHR is unsigned divide by 2, imm8 times, would result in 1.  How are you getting -1?

I don't see how you can just categorically `if reduce count=0x1f` to result in 0 (in either case).

Also your current fix changes this instruction to a NOP if 0x1f, removing any changes to flags and the destination register

**Comment by Piruzzolo** [comment]
@mumbel yep, probably I've made a mistake, I'm a bit confused. For which range does it work?

**Comment by caheckman** [comment]
A shift of a 4-byte value by 31 bits is definitely not identically zero.  The '>> 31' artefact you are seeing in the original example is more likely something to do with the decompiler's simplification of optimized division, there is some work going on with the rule. We would need to see the bytes of the function to be sure, preferably via the "Debug Function Decompilation" action.

**Comment by Piruzzolo** [comment]
I've dumped two versions of the same function, from a PPC binary and from an x86 one, and they both have that issue. The function is not the one of the reported snipped above, but the (mis)behavior is exactly the same. 
[dump.zip](https://github.com/NationalSecurityAgency/ghidra/files/3365864/dump.zip)

**Comment by caheckman** [comment]
Thanks, I'm duplicating this, working on a fix.

**Comment by caheckman** [comment]
A fix for this issue has been committed to master.

**Comment by mumbel** [comment]
@caheckman @ryanmkurtz  Just checking if this got moved over to github or still queued to move, expected changes in decompile/cpp I guess, but if fix was elsewhere sorry for the noise.

**Comment by ryanmkurtz** [comment]
GitHub is up to date with master.  Will have to check with @caheckman, but I'm guessing it was done someone near the top of t[his list of commits](https://github.com/NationalSecurityAgency/ghidra/commits?author=caheckman&since=2019-07-01&until=2019-08-01).  Maybe closing this ticket just fell through the cracks.

**Comment by mumbel** [comment]
Yup you're right, sorry I had only looked at the `20 days ago`
