### ISSUE TITLE
PowerPC VLE spec for e_rlwinm instruction is wrong

### ISSUE THREAD

**Issue by nik0sc** [NationalSecurityAgency/ghidra#752]
**Describe the bug**
Under PowerPC VLE instruction set, the `e_rlwinm` instruction results in incorrect pcode which results in wrong output in the decompiler. It also results in `Removing unreachable block` warnings printed at the top of the decompiler output.

**To Reproduce**
1. Load the sprintf binary attached using the `PowerPC:BE:64:VLE-32addr (1.5)` language
2. Disassemble using VLE (F12)
3. Scroll down to `74 0b 10 3b` instruction at +0x100, this is supposed to shift r0 left by 2 but this isn't interpreted correctly and the case labels come out wrong as well

**Expected behavior**
`e_rlwinm r11, r0, 0x2, 0x0, 0x1d` should result in the operation `r11 <- (r0 << 2) & 0xfffffff0`. In my code this is used to calculate offsets into a jump table and the address at that offset is used for a `se_bctr` instruction later on (ie. branching to the address in the jump table). Instead the `<< 2` never happens and the offsets are all wrong in the decompiler.

**Screenshots**
![sprintf_bad](https://user-images.githubusercontent.com/24191562/60581242-09c61d80-9db9-11e9-8156-88294ddfea01.PNG)
This is the original buggy output.

![sprintf_fixed](https://user-images.githubusercontent.com/24191562/60581254-0c287780-9db9-11e9-91bd-4fe39a35ee35.PNG)
This is the output after patching the `ppc_vle.sinc` file (see "Additional context" section), note how the case labels make sense because the computed offset from `e_rlwinm` is correct

**Attachments**
The sprintf function binary in question, in hex form (base is 0xe61e8)
[sprintf_ppcvle.txt](https://github.com/NationalSecurityAgency/ghidra/files/3354329/sprintf_ppcvle.txt)

Exported sprintf function (remove the .zip before opening in Ghidra)
[sprintf_ppcvle.bin.gzf.zip](https://github.com/NationalSecurityAgency/ghidra/files/3354430/sprintf_ppcvle.bin.gzf.zip)

**Environment (please complete the following information):**
 - OS: Windows 10 1903
 - Java Version: `openjdk 12.0.1 2019-04-16`
 - Ghidra Version: 9.0.4

**Additional context**
A simple fix is to copy the constructor from `ppc_instructions.sinc` to `ppc_vle.sinc`. So now my e_rlwinm looks like
```
# 64 bit VLE variant
:e_rlwinm A,S,SHL,MBL,ME			is $(ISVLE) & OP=29 & BIT_0=1 & MBL & ME & A & SHL & S & rotmask {
	shift:1 = SHL;
	tmp:4 = S:4;
	tmp2:4 = (tmp<<shift)|(tmp>>(32-shift)); 
	A = zext(tmp2 & rotmask);	
}
```
Of course, not all VLE instructions behave exactly the same as their full-length counterparts so this might not work for all cases.

**Comment by nik0sc** [comment]
Piggybacking on this issue. The sleigh spec for the `wrteei` instruction is also wrong somehow. In `ppc_embedded.sinc`: 
```
#wrteei 0       0x7c 00 01 46
:wrteei BIT_16	is OP=31 & BIT_16 & XOP_1_10=163
{
	WriteExternalEnableImmediate(BIT_16:1);
}
```

This looks correct, after all according to the [Book E spec](https://www.nxp.com.docs/en/user-guide/BOOK_EUM.pdf), bit 16 indicates the immediate value to put into the MSR[EE] bit. So `7c 00 01 46` is `wrteei 0` and `7c 00 81 46` is `wrteei 1`. But in the disassembly view both of these instructions appear as `wrteei 0x0`!
![wrteei0](https://user-images.githubusercontent.com/24191562/60714509-c81aab80-9f4d-11e9-8cfd-bbdedc9b8a0c.PNG)
![wrteei1](https://user-images.githubusercontent.com/24191562/60714513-c9e46f00-9f4d-11e9-9b47-a2a9a22b249d.PNG)

**Comment by GhidorahRex** [comment]
@nik0sc - The NB issue is wrong for both e_rlwinm and e_rlwimi, both should use MB=(6,10) instead of (11,15).

For wrteei, the bit format is sleigh is reversed from what the manual says. BIT_16 here should actually be BIT_15.

These should both be addressed. Good ifnds.

**Comment by ryanmkurtz** [comment]
77665a8945274b683cae30e96f826197f95c99e5
