### ISSUE TITLE
Renaming an UndefinedFunction causes UnsupportedOperationException

### ISSUE THREAD

**Issue by void4** [NationalSecurityAgency/ghidra#753]
**Describe the bug**
Renaming an UndefinedFunction causes UnsupportedOperationException.

**To Reproduce**
1. Go to the Decompiler window
2. Right click on an UndefinedFunction name
3. Select "Rename Function"

**Expected behavior**
Maybe show a hint that a function has to be created manually first in the assembly editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/11392207/60589911-ee4c1a00-9d9a-11e9-8b68-6f754d923ed2.png)

**Environment:**
Build Date: 2019-May-16 1545 EDT
Ghidra Version: 9.0.4
Java Home: /usr/lib/jvm/jdk-12.0.1
JVM Version: Oracle Corporation 12.0.1
OS: Linux 4.18.0-25-generic amd64

**Comment by void4** [comment]
Solution: It is necessary to create the function manually in the assembly window: right click -> create function. Maybe instead of the error message, a hint could be useful.

**Comment by adamopolous** [comment]
Thanks for catching this. At the very least we should prevent users from attempting to rename the undefined function.
