### ISSUE TITLE
Broken analysis privateframeworks from dyld caches

### ISSUE THREAD

**Issue by dukebarman** [NationalSecurityAgency/ghidra#758]
**Describe the bug**
PrivateFrameworks analysis from dyld cache is broken.

**To Reproduce**
1. Import arm64 dyld cache to project as a "File System" (as a "File" works after commit for #682, but slowly)
2. Import any file from new window and PrivateFrameworks folder
3. Open this file in CodeBrowser
4. See errors. For example: "Failed to create "no return" function __la_symbol_ptr::___stack_chk_fail...". Functions and classes are empty

**Expected behavior**
Working analysis

**Screenshots**
![image](https://user-images.githubusercontent.com/1186777/60662674-af36cb00-9e65-11e9-9638-52f0ff4bd3f0.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 19.04
 - Java Version: 11.0.3
 - Ghidra Version: From source - master branch (2019-Jul-02 Build)

**Comment by ryanmkurtz** [comment]
I think this is just a duplicate of #682, which is reporting broken behavior when importing DYLIB's from the DYLD file system.  That issue derailed a bit into testing out the new DYLD loader, but the issue is still active for what you reporting.
