### ISSUE TITLE
Windows GCC Incorrect Primary Symbols Set (Bug)

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#761]
**Describe the bug**
While analyzing a windows binary compiled with gcc, the symbols prefixed with their section followed by $ are set as the primary symbol. This behavior causes virtually all symbols to remain mangled.

Below is an example of the symbols at a function address.
```
text$_ZN9__gnu_cxx13stdio_filebufIcSt11char_traitsIcEE4fileEv (primary)
__ZN9__gnu_cxx13stdio_filebufIcSt11char_traitsIcEE4fileEv
.text$_ZN9__gnu_cxx13stdio_filebufIcSt11char_traitsIcEE4fileEv
```

**To Reproduce**
1. Compile program with mingw64
2. Open program in ghidra and run analyzer.
4. See wrong symbol set to primary.

**Expected behavior**
The symbol without the section name prefix should be set as primary.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.557]
 - Java Version: 12.0.1
 - Ghidra Version: 9.0.4

**Additional context**

**Comment by ghidra1** [comment]
After import and before auto-analysis you could try removing all text$ and .text$ labels (and others with such a pattern).  These symbols appear redundant.  A GhidraScript could be easily used to accomplish this task.  Not sure what the fallout may be for external symbols and their associated references.  Do you see similar issues with your external symbols?

**Comment by astrelsky** [comment]
I will be able to check if external symbols are affected in an hour or so. The main issue from this is that nothing gets demangled during analysis.

Would there be an issue with the demangler iterating over all the symbols at an address instead of just the primary one to check if one is mangled? It could then set which one is primary after demangling.

**Comment by astrelsky** [comment]
> After import and before auto-analysis you could try removing all text$ and .text$ labels (and others with such a pattern). These symbols appear redundant. A GhidraScript could be easily used to accomplish this task. Not sure what the fallout may be for external symbols and their associated references. Do you see similar issues with your external symbols?

So the issue doesn't occur for dynamically linked symbols only static ones. Strangely enough the relocation table is empty and program.getRelocationTable().isRelocatable() always returns false even though there clearly are relocations.

**Comment by ghidra1** [comment]
Using the primary symbol is how Ghidra avoids demangling multiple mangled symbols at the same location or demangling the same symbol more than once.  The symbol stacking order has been problematic to demangling in the past for the same reasons you have identified.      I will have to allow someone else to speak to what I presume are PE relocation issues.  Are there red bookmarks at the relocation locations?

**Comment by astrelsky** [comment]
> Using the primary symbol is how Ghidra avoids demangling multiple mangled symbols at the same location or demangling the same symbol more than once. The symbol stacking order has been problematic to demangling in the past for the same reasons you have identified. I will have to allow someone else to speak to what I presume are PE relocation issues. Are there red bookmarks at the relocation locations?

The relocations are valid and function as they are supposed to. Upon double clicking the relocation it opens the dll in ghidra and jumps to the function. Just nothing appears in the relocation table and it's being reported as non-relocatable.

Could the PE loader automatically remove the symbols upon loading since this only occurs with mingw binaries? There are 2 extra unnecessary symbols for every single symbol.
