### ISSUE TITLE
MapLoader "Add To Program" not working + parse errors

### ISSUE THREAD

**Issue by Piruzzolo** [NationalSecurityAgency/ghidra#762]
I've read in the guide (`Help->Contents`) that Ghidra can import memory MAP files, like those generated by MSVC. But I was not able to import it. 

Is the feature present/enabled? Maybe I have to follow some procedure I'm unaware of?
Thanks 😄

**Comment by ryanmkurtz** [comment]
I believe if you go to File->Add To Program... from your your PE file's Code Browser window you can load the corresponding map file.  Let me know if that doesn't work.

**Comment by Piruzzolo** [comment]
Just retried, it doesn't work. I chose the Code Browser window after loading the exe, then File->Add to program. The extension .MAP doesn't show up in the type list. If I choose All Files I can select the map file, but then I can't choose the MAP format, only Raw Binary present. And in fact it loads it as a binary

**Comment by ryanmkurtz** [comment]
Ok I'll investigate...thanks!

**Comment by ryanmkurtz** [comment]
There are a couple of issues here:

1. The MapLoader was not declaring that is supports loading into an existing program. 
2. The parsing of the .map file failed for the simple samples I produced.  

I am going to change this to a bug.  I believe I have it fixed...I just need to do more testing to verify.

**Comment by Piruzzolo** [comment]
Does the MAP importer also take the "FIXUPS:" section into consideration?

**Comment by ryanmkurtz** [comment]
No, it's just doing symbols.  If you think that would add value feel free to make a new enhancement request.

**Comment by aboood40091** [comment]
This still happens to me on Ghidra v9.1.2...

**Comment by ryanmkurtz** [comment]
You are not getting MapLoader as a choice?

**Comment by aboood40091** [comment]
Yes. I have the v9.1.2 release, which is currently the latest on the download page.

**Comment by ryanmkurtz** [comment]
Can you post your map file?

**Comment by aboood40091** [comment]
I would rather not post it here; is it fine if I send it by email?

**Comment by ryanmkurtz** [comment]
Sure, this will be good for 10 minutes: `avrdqhxxjjucktomgn@awdrt.org`

**Comment by aboood40091** [comment]
That time limit caught me off-guard, haha.
Hoping I made it in time...

**Comment by ryanmkurtz** [comment]
Hmm I didn't get it...not sure if it will come through.  

The MapLoader only cares about a couple of things to determine if it can load a file.  First, the filename has to end in `.map`.  Second, there has to be a line that reads **Publics by Value**.  Following that line has to be lines with at least 3 tokens, the 3rd of which is an address. 

Does your file meet those requirements?

**Comment by aboood40091** [comment]
Does not seem like it.

**Comment by ryanmkurtz** [comment]
This is what it looks for:

```
/**
 * A {@link Loader} for processing Microsoft MAP files.
 * <p>
 * Sample .map file section we parse to extract symbol information:
 * <pre>
 *   ...
 *   ...
 *   ...
 *
 *   Address         Publics by Value              Rva+Base               Lib:Object
 *   
 *  0000:00000000       ___safe_se_handler_table   0000000000000000     &lt;absolute&gt;
 *  0000:00000000       ___safe_se_handler_count   0000000000000000     &lt;absolute&gt;
 *  0000:00000000       __ImageBase                0000000140000000     &lt;linker-defined&gt;
 *  0001:00000040       foo                        0000000140001040 f   foo.obj
 *  0001:000000c0       bar                        00000001400010c0 f   foo.obj
 *  
 *  ...
 *  ...
 *  ...
 *  </pre>
 */
```

**Comment by aboood40091** [comment]
Yeah, it doesn't match.
I haven't tried making Python plugins for Ghidra yet, but maybe I can make one to parse this special format.

**Comment by ryanmkurtz** [comment]
There may be other parts of the map file that the MapLoader doesn't know how to make use of, so it doesn't even present as an option.  For example, #767.  Maybe that's your situation too.  If so, you could create a new ticket asking for the new feature to be added.

**Comment by aboood40091** [comment]
The layout of the map file I have differs greatly from the one you showed, so it isn't a simple matter of new features.
Thanks for the help; I will see if I can make a plugin to parse it.

**Comment by rollsch** [comment]
How do you actually access the map loader within the ghidra UI? I can't find anywhere to actually launch it.

**Comment by ryanmkurtz** [comment]
From your CodeBrowser tool, you must use `File -> Add To Program` for the `MapLoader` to show up as a choice (assuming you've selected a valid map file)

**Comment by rollsch** [comment]
All I can see is binary as the options.

I managed to world around the issue by exporting the symbols manually from the elf project, then massage into space delimited and use the symbol importer script. I find it odd that the built in symbol importer script doesn't support the standard symbol export format though.

**Comment by ryanmkurtz** [comment]
MapLoader is only a choice if your program is a PE.

**Comment by rollsch** [comment]
I was using elf and h32 so that explains why.
