### ISSUE TITLE
MIPS ELF loader issues

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#764]
While trying to repro/minimize my issue in #729 came across missing relocation support for `R_MIPS_GPREL32`.  The big switch in `MIPS_ElfRelocationHandler` does include a few GP relocation types, so maybe this was an oversight or there's a significant difference in the relocation.  The loader also fails to allocate space for _gp_disp (?).  In another test (which I didn't keep that exact src/bin for some reason) it showed a failure to allocate the `.rel.rodata` section where the switch offsets are stored (which would probably prevent looking up GP anyways in either case maybe).

```
Skipping empty section[.data]
Skipping empty section[.bss]
Skipping empty section[.mdebug.abi32]
Unable to place symbol due to non-loaded section: .mdebug.abi32 - value=0x0, section=.mdebug.abi32
No Memory for symbol: _gp_disp - 0x0
Created %got.text block required for relocation processing (gp=0x19ff0)
Unhandled Elf Relocation: Type = 12 (0xc) at 000103e0 (Symbol = .text)
...
```

```
/*  test.c  Dummy switch statement
 *  $ mipsel-linux-gnu-gcc --version
 *  mipsel-linux-gnu-gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
 *  $ mipsel-linux-gnu-gcc -fPIC -c test.c
 */
// dummy func just so helloworld isnt at 0x10000
int
foobar(int a, int b, int c)
{
  return a + b + c;
}

int
helloworld(int a, int b, int c)
{
  int i,x;
  if (c > 64 || c < 0)
    return 0;
  switch(c) {
  case 0: return a + b;
  case 1: return a - b;
  case 4: return b - a;
  case 5: return a * b;
  case 9: return a / b;
  case 10: return a ^ b;
  case 15: return a & b;
  case 17: return a && b;
  case 20: return a | b;
  case 21: return a << b;
  case 27: return a >> b;
  case 33: return a % b;
  case 34: return a||b;
  case 38: return a > b;
  case 40: return a < b;
  case 41: return ~a;
  case 45: return a <= b;
  case 47: return a >= b;
  case 50: return b;
  case 51:
    x = 1;
    for (i = 0; i < b; i++)
      x *= a;
    return x;
  case 52:
    x = 1;
    for (i = 0; i < a; i++)
      x *= b;
    return x;
  case 55: return b / a;
  case 59: return b % a;
  case 63: return b << a;
  case 64: return b >> a;
  default: return a; 
  }
}

```

9.0.4

**Comment by ghidra1** [comment]
Implemented ELF relocation types for all language modules is in no way complete and has generally been filled-out as needed.  I will try to reproduce with your sample.  Any suggested code fixes are welcome.

**Comment by mumbel** [comment]
@ghidra1 trying to figure out the relocation stuff, but not having much luck, its making a little more sense each time I look at it though.  I did try for a bit when I made this post.  And I very much agree with your comment about generating linker artifacts after looking at this a bit more.

The section allocation ended up being a larger issue than I originally thought (`ELF unable to find unallocated memory required for %got.rodata`)  which prevented me getting a GP value.

At least in this sample `%got.text` gets the range [00011000, ffffffff] and then there is no memory left for `%got.rodata`.  In `allocateLinkageBlock` where there is an EXTERNAL, should that range maybe be aligned then add the size-1, which would give [00011000, 00020fff] leaving room in [00021000, ffffffff] for the `%got.rodata`.  I dont know if this would then do incorrect things with GP.

the relocation is then pretty straight forward:
```
local symbol:  S + A + GP0 - GP
global symbol: S + A - GP

GP  - Represents the final gp value, i.e. _gp symbol
GP0 - Represents the gp value used to create the relocatable object
```
again for this sample, it is local, so it would be something like: `value = symbolValue + oldValue + 0x11000 - gp` but I dont know how/what to calculate the 0x11000 from, assuming the section allocation is even close to correct code/assumptions.

**Comment by ghidra1** [comment]
I have put a fix in for the ELF MIPS relocations which should get pushed to master tomorrow.  

The message regarding _gp_disp can be ignored.  This is a ELF MIPS relocation marker symbol.  I have not found a good place in the code to prevent the normal symbol processing which is also causing it to improperly appear in the EXTERNAL block, although its' presence should have no negative impacts.

**Comment by ryanmkurtz** [comment]
[Fixed](https://github.com/NationalSecurityAgency/ghidra/commit/5cde1bd48d04007d078fe4c7509e370920263eab).
