### ISSUE TITLE
Stack Frame Editor

### ISSUE THREAD

**Issue by evanpjensen** [NationalSecurityAgency/ghidra#77]
**Describe the bug**
Right clicking on stack local variables doesn't present the option to open the stack frame editor in the context menu. 

**To Reproduce**
Press f1 
search for "stack frame editor"
Attempt to use the feature as described

**Expected behavior**
A stack frame editor appears

**Environment (please complete the following information):**
 - ubuntu 18.04
 - ghidra 9.0

**Comment by partoftheworlD** [comment]
Temporary solution. You can bind a key for using stack frame editor.
https://imgur.com/a/Sb8m2OA

**Comment by dragonmacher** [comment]
Currently this action is available from the function name by right-clicking and selecting `Function->Edit Stack Frame...`

**Comment by dragonmacher** [comment]
So, this seems to function as expected when working with normal functions.   I did observe the behavior reported in this ticket when right-clicking on params/variables in a *thunk function*. 

Closing this, as the normal workflow works as expected.
