### ISSUE TITLE
Is there any way to search for instructions?

### ISSUE THREAD

**Issue by nikhilh-20** [NationalSecurityAgency/ghidra#772]
If I want to search for ALL instances of "CALL EDI" in the program text, is there any class / method that does this? Thanks!

**Comment by saruman9** [comment]
You can find examples in the Script Manager, see `Search` → `InstructionPattern` directory.

**Comment by lmstearn** [comment]
Apologies, very much in no-man's land with this - as there probably is an answer somewhere despite the "best" Google-fu.
Does Ghidra (or somebody else) host a table of "common" search patterns such as class construction-destruction, object creation-nullification, structs, vectors, arrays and so on. Googling says no.
The aim here is to search or filter the program listing for all occurrences of the _creation_ of some type of _gui_, see this [FASM example](https://stackoverflow.com/a/22252976/2128797) using `invoke`. No doubt there are many in today's programs, most likely enough to break the 500 output limit rule.
Is there a simple alternative?
Thanks.
