### ISSUE TITLE
How to cleanly handle overlapping memory regions?

### ISSUE THREAD

**Issue by hedgeberg** [NationalSecurityAgency/ghidra#773]
So, I've been working on implementing RL78 in Sleigh, and I've hit an edge case I can't seem to find a way around that really seems to be messing with the decompiler. 

Basically, in RL78, the memory space is 20 bits, but the stack pointer is 16 bits. To handle this, the architecture engineers restricted the stack space to the range from 0xF0000 to 0xFFEFF (0xFFF00 - 0xFFFFF is the register page). I can work around this one of 2 ways, both of which have issues:
1. writing macros that always add a zero-extended SP into a constant of 0xF0000 and using that address for pop/push, but this screws up the decompiler because the stack accesses don't line up with where it thinks the stack is, as far as I can tell.
2. defining the stack as its own space, which fixes the issue of bad decompiling, but fails to take into account the fact that this is a unified memory space where the stack can be written to via other methods. 

The preferred way I'd fix this would be one of a few methods -- first, just use one address space and create some kind of virtual register of some sort that is the stack pointer in the lower 16 bits and a constant in the upper 4, so that way I could set   ```<stackpointer register="virtualSP" space="ram"/>```
in the .pspec file and have it just play nice. 
--second, do some kind of nested memory mapping, such that the stack region is functionally just an offset into the ram space. bit/byte mapping seems like it would maybe do this, except that it doesnt seem to actually allow the kind of clean handling im hoping for. 

Is there any way to accomplish this kind of nasty mapping and have the decompiler understand that the stackpointer has an implicit offset? Or am I just SOL on this one?

**Comment by emteere** [comment]
There is a third method that you can use that has been done in other processor modules like the 16-bit x86 where you essentially have two parts to the address access.  If both parts aren't known, then the decompiler will use the value of the SP as an offset.  The segment() user op is used along with some pcode attachment in the .cspec.

I would try your second route first.  I think this will work but there might be issues I'm not thinking about.  Define the byte mapped stack block, but don't actually initialize the bytes in the .pspec file.  Create a byte mapped memory block in the stack address space on top of the ram address space.  I think this should work even though the address spaces are slightly different sizes.  The stack address space would be size 2, and the main memory size 3.

There can be side-effects from either method, and sometimes they aren't apparent until you try it.

**Comment by hedgeberg** [comment]
So, when you say the second, do you mean the second ifeal, with the nested memory mapping? Because if so, how would I go about that? Byte-mapping creates 2 separate memory spaces, and ideally I'd like it to be clear that this is 1 whole

**Comment by hedgeberg** [comment]
Sorry accidentally closed issue while typing out response. Reopening while I finish typing this out.

**Comment by hedgeberg** [comment]
So, when you say the second, do you mean the second ideal, with the nested memory mapping? Because if so, how would I go about that? Byte-mapping creates 2 separate memory spaces, and ideally I'd like it to be clear that this is 1 united memory space. Byte mapping a stack-specific region over ram is what I'm doing now, and it's definitely messier than I'd like. Would there be a way to make a single big memory space that represents all of memory, byte-map the different regions into that memory space, and then hide the component segments so that it appears as one unified space? If not, and I were willing to modify the codebase and go about submitting a pull request, how would I start? 

Also, could you maybe give a bit more detail about how the x86 solution you mentioned works? Any idea which files in the x86 sleigh rats nest I should look at? I'd like to at least give it a shot, see what kind of results it yields.

**Comment by hedgeberg** [comment]
(for what it's worth, I've been pushing my (extremely messy, sorry, still getting the hang of this) sleigh code to github.com/hedgeberg/rl78_sleigh if you have thoughts on what to change/where. The ISA programmer's manual for the arch is in the docs folder, if the behavior here is unclear)

**Comment by hedgeberg** [comment]
Hey, seems like you guys are super busy and I've currently got my sleigh stuff working well enough fo the time being via byte mapping, so I'm going to go ahead and close this to get it out of your queue. Thanks for the help @emteere.
