### ISSUE TITLE
Decompiled f64 literals lack precision (e.g. for 1/4294967296.0)

### ISSUE THREAD

**Issue by YellowAfterlife** [NationalSecurityAgency/ghidra#778]
**Describe the bug**
Decompiled floating-point literals seem to cap at max fractional digits, which results in small enough values being displayed as 0.00000000

**To Reproduce**
1. Compile the following DLL from a fresh unmanaged C++ DLL project in VS2019 with platform tools v142 and targeting x86:
```cpp
#include "pch.h"
extern "C" __declspec(dllexport) double __cdecl test(double a) {
	return a / 4294967296.0;
}
BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved) {
    return TRUE;
}
```
2. Create a Ghidra project, add the DLL to it, and run analyzer with default settings
3. Navigate to the `test` function in Exports and take a look at decompile view.
You get this:
```cpp

float10 __cdecl _test(double param_1)

{
                    /* 0x1000  1  test
                       Symbol Ref: _test */
  return (float10)param_1 * (float10)0.00000000;
}
```
or, if you retype the return value to double, 
```cpp
double __cdecl _test(double param_1)

{
                    /* 0x1000  1  test
                       Symbol Ref: _test */
  return param_1 * 0.00000000;
}
```
Produced literal vs minimum literal where you can see the value:
```cpp
0.00000000
0.00000000023283064365
```
so just a couple digits short really.

Looking at hex view still works though.

**Expected behavior**
Given a literal with a bunch of leading zeroes, could keep bumping the precision until at least one non-zero digit shows up, and then add 2-3 extra digits after that.

As another approach to the problem, in one of the past projects I pre-generated a (float literal bytes) -> (C++ literal value) lookup table for a number of `a/b` combinations that produce literals that require >7 fractional digits to represent, as well as `pi*a/b` and common bit-based ones (`1/(1<<a)`, `1/((1<<a)-1)`), which allowed to output easier-to-read literals (`(3/7)` vs `0.42857142...`) in common scenarios.

**Attachments**
[Pre-compiled version of the sample DLL](https://github.com/NationalSecurityAgency/ghidra/files/3382732/TestCPPDLL.zip)

**Environment (please complete the following information):**
* OS: Win10, build 17134
* Java Version: 12.0.1
* Ghidra Version: 9.0.4

**Comment by leo60228** [comment]
This can occur in actual code. I have code where the source is approximately `((float) rand()) * (1.0 / RAND_MAX)` that gets decompiled as `(float) iVar1 * 0.0000000`.

**Comment by caheckman** [comment]
Changes to fix this are available in master branch currently and will be in the 9.2 release.  The decompiler now prints floating-point values with full precision using the minimal length representation.

**Comment by caheckman** [comment]
This change is now in the master branch.

**Comment by YellowAfterlife** [comment]
Thank you!
