### ISSUE TITLE
Share project p2p

### ISSUE THREAD

**Issue by Piruzzolo** [NationalSecurityAgency/ghidra#779]
A p2p- based approach is much better than any server based/centralized one. There are nice libraries such as [libp2p](https://github.com/libp2p) that can make it easy and trasparent to deal with connection, peer discovery etc. in a distributed way

**Comment by ryanmkurtz** [comment]
Thank you for the suggestion, but we have no plans on rearchitecting how we handle shared projects for the foreseeable future.
