### ISSUE TITLE
specl file

### ISSUE THREAD

**Issue by xzcvczx** [NationalSecurityAgency/ghidra#782]
ghidra/Ghidra/Processors/PIC/data/languages/pic18.slaspec:7

```
#
# NOTES	-
#   1. If a specific PIC-18 has a different register set, this file and the pic18.specl file may be copied/renamed and
#      slightly modified to specify a the correct Register File Map.  The following register definitions must be preserved: 
#	   STATUS, STKPTR, PCLAT (PCL, PCLATH, PCLATU), TOS (TOSL, TOSH, TOSU), FSR0 (FSR0L, FSR0H), FSR1 (FSR1L, FSR1H), FSR2 (FSR2L, FSR2H),
#      PROD (PRODL, PRODH)
```

as there doesn't seem to be a specl file can you advise which one it is replaced with

**Comment by mumbel** [comment]
Looking the Java it looks like that file type/extension is deprecated, so that comment should probably be removed/edited

**Comment by emteere** [comment]
It should be .pspec instead of .specl.
That said it does appear to be a badly formatted comment in need of an update.
