### ISSUE TITLE
Incorrect Z80 instruction LD A,HL in exported text/assembly files.

### ISSUE THREAD

**Issue by Colpocorto** [NationalSecurityAgency/ghidra#793]
**To Reproduce**
1. Create a Project
2. Click on Create Tool
3. Select Ghidra Core
4. On the newly created tool, click on File... and Import File.
5. Select any Z80 executable file (e.g. a vintage arcade ROM file or a CP/M .com program).
6. Do a basic disassembling process and spot a **LD A,(HL)** instruction.
7. Now click on File... Export... and create an output file in ASCII or HTML format.
8. Open the new ascii or html format file and inspect the LD A,(HL) instruction: it is written as **LD A,HL** (without parenthesis), which is not a valid Z80 mnemonic.

**Expected behavior**
All occurrences of **LD A,(HL)** must use parenthesis.

**Screenshots**
![image](https://user-images.githubusercontent.com/24856281/61335228-0c9b2680-a82d-11e9-8122-1089cdd9942f.png)

**Environment (please complete the following information):**
 - OS: Windows 7 64bit / Linux 64bit
 - Java Version:  11
 - Ghidra Version: 9.0.4

**Comment by GhidorahRex** [comment]
The problem isn't just with LD A, (HL) or just with the exporter. I see it with many Z80 instructions: SBC A, (HL), LD (BC), A, etc. The Disassembled View plugin mangles the parentheses as well (but only chops off one of them).

**Comment by Colpocorto** [comment]
I reported this bug more than one year ago; it has not even been assigned yet. Open-source brings many benefits, they said...

**Comment by Colpocorto** [comment]
2+ years, still nothing...

**Comment by ryanmkurtz** [comment]
Closed by 6f80f8bd3c6559fc5ed280b6050b3af6be76f4f2
