### ISSUE TITLE
Add Ghidra to Maven Central (or another Maven repository)

### ISSUE THREAD

**Issue by big-boy-vr** [NationalSecurityAgency/ghidra#799]
**Is your feature request related to a problem? Please describe.**
In order to create applications/libraries depending on Ghidra, one must either a) package the single jar and use it as a dependency (which is a 150+MB jar, mostly composed of unused resources) or b) customise the classpath significantly. Furthermore, it requires developers of these applications/libraries to have Ghidra installed locally in order to build applications using Ghidra. Libraries depending on Ghidra which are exported to Maven Central or used via jitpack or similar cannot explicitly declare the dependency to be used by other projects and would need to package Ghidra within the jar (shadowed) to be used by other projects.

**Describe the solution you'd like**
Add Ghidra to Maven Central or another Maven repository. Preferably, this would allow for the archival of all features individually so that these dependencies can be selectively collected as-necessary.

**Describe alternatives you've considered**
As workarounds, one can simply have Ghidra installed locally and significantly customise the gradle/maven buildscripts or single-jar the application. Local maven repos can be spun up by developers, but this is also significantly sub-optimal.

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
At this time we have no plans to distribute Ghidra outside of how we are currently doing it on GitHub.  Apologies for any inconveniences this might cause.
