### ISSUE TITLE
Parse C Source Failure

### ISSUE THREAD

**Issue by icykoneko** [NationalSecurityAgency/ghidra#80]
**Describe the bug**
When using the Parse C Source to import data types, the C Parser encounters errors.  If I change the parse options to `-v6`, you can see more information where it appears to mess up handling `#ifdef`/`#endif` pairs.

**To Reproduce**
1. Click File > Parse C Source... from the menu in an open project.
2. Create a new parse configuration profile and clear it.
3. Add a simple header file (hello.h below) to the list.
4. In Parse Options, set the following:
```
-D_WIN32
-v6
```
5. Click Parse to Program

**Expected behavior**
The header should have been parsed correctly.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
`hello.h`
```
#ifndef HELLO_H
#define HELLO_H

#ifndef _WIN32
    #define _WIN32
#endif

// This should show up... but the parse never gets this far...
int foo(int bar);

#endif
```

`CParserOutput.txt`:
```

#line 1: "D:\dev\temp\hello.h"
D:\dev\temp\hello.h'1 IFNDEF: Line 1: D:\dev\temp\hello.h Check isNDef ifndef True
Line 1: D:\dev\temp\hello.h Check isNDef HELLO_H True
 [1]IfNDef true : true

Line 2: D:\dev\temp\hello.h Check isDef HELLO_H False
 D:\dev\temp\hello.h'2: Defining: HELLO_H

D:\dev\temp\hello.h'4 IFNDEF: Line 4: D:\dev\temp\hello.h Check isNDef ifndef True
Line 4: D:\dev\temp\hello.h Check isNDef _WIN32 False
 [2]IfNDef false : false
Line 5: D:\dev\temp\hello.h Check isDef _WIN32 True
 PreProcessor: D:\dev\temp\hello.h'5: _WIN32 aready defined. Undefine first.

```

**Comment by icykoneko** [comment]
Noticed this in the user log, might be useful:
```
2019-03-06 | 19:43:15 | INFO | (PreProcessor) Defs: containsKey: _WIN32 = true 1
-- | -- | -- | --
2019-03-06 | 19:43:15 | INFO | (CParserPlugin) parse D:\dev\temp\hello.h
2019-03-06 | 19:43:15 | ERROR | (PreProcessor) Imbalance in sequence/nesting of compile-time conditions/logic in input file D:\dev\temp\hello.h
2019-03-06 | 19:43:15 | ERROR | (PreProcessor)               [HELLO_H, _WIN32]
2019-03-06 | 19:43:15 | INFO | (CParserTask$3) Parse Errors: C Parser:  Encountered errors during parse.
  |   |   | in D:\dev\temp\hello.h near line 1
  |   |   | near token: "D:\dev\temp\hello.h"
  |   |   | Last Valid Datatype: - none -
  |   |   | Check around CParserPlugin.out around line: 3
```

**Comment by emteere** [comment]
Change the -v6 to -v0, or remove the -v flag altogether
The use of -v is really for debugging the internal parser.

The way the CParsing works is there is a CPP phase that parses all the files first as a normal compiler would. The output of the CPP phase is left in the CParserPlugin.out file so that you can see exactly what the second phase the real C parse is going to parse.  By using the -v6 flag, debug messages from the CPP phase are intermixed into the CParserPlugin.out file that the C parsing phase will attempt to parse.

Getting the definitions and the header files can be difficult when parsing header files.  This could be streamlined with more options to make this easier.

**Comment by icykoneko** [comment]
I tried removing "-v6", and tried "-v0".  Both cases result in Ghidra saying it succeeded, but it doesn't end up importing the foo(int bar) function def.

**Comment by emteere** [comment]
After your parse fails.  What is left in the CparserPlugin.out file?

**Comment by icykoneko** [comment]
I got it to work!  Problem was I didn't have the compiler on my PATH.  (When you mentioned that in your previous comment, I though to try it, and it worked.  Might want to have that stated in documentation to help others.

**Comment by emteere** [comment]
Not sure what you mean by compiler in your path.  An internal home grown CPP and c parsing Grammer is used.  There isn't a dependency on a compiler.

If you had a more complicated header file that included other header files, you might need to include those paths with -I.

Glad you got it to work.  It might be there is a bug with the -v flag and there was a stale state that was cleared when ghidra was restarted.
