### ISSUE TITLE
MIPS: import name in decompiler bug

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#803]
I've added external library:
```
Library psyqLib = symTbl.createExternalLibrary("PSYQ.LIB", SourceType.IMPORTED);
```

I've created imported function:
```
listing.createData(refAddr, PointerDataType.dataType);
refMgr.addExternalReference(refAddr, "PSYQ.LIB", "memchr", refAddr, SourceType.IMPORTED, 0, RefType.DATA);
```

In disassembler it looks good:
```
00000918  a7 02 00 0c         jal                 memchr
```

But in decompiler it uses a wrong name:
```
iVar5 = func_0x00000a9c(piVar7,0,local_38);
```

`memchr` in disassembler:
```
*************************************************************************
*                                            SUBROUTINE                                           
*************************************************************************
void * memchr(void * __s, int __c, size_t __n)
                       void *                        v0:4                   <RETURN>
                       void *                        a0:4                   __s
                       int                             a1:4                   __c
                       size_t                        a2:4                   __n
         memchr                                                                         XREF[1]:          sprintf:00000918(c)  
             00000a9c                             addr             PSYQ.LIB::memchr
```

Reference info in disassembler:
![изображение](https://user-images.githubusercontent.com/7189309/61452161-d3b19d80-a963-11e9-86a6-17dd3fcf6b71.png)

When I'm pressing `L` to rename `func_0x00000a9c` it shows me `memchr`:
![изображение](https://user-images.githubusercontent.com/7189309/61452205-f04dd580-a963-11e9-8a7f-d7ee072bf5e8.png)

**Comment by lab313ru** [comment]
Sometimes it doesn't allow to change the function name in decompiler at all. Pressing `L` doesn't work.

**Comment by ghidra1** [comment]
The decompiler generally relies on function thunks or address tables to be redirected to an external function.   I don't believe the decompiler will respond well to an external reference placed directly on an instruction within the decompiler function since it requires a real memory address within the pcode and not a fake EXTERNAL space address.   Within ELF the .got, .plt sections or EXTERNAL "block" frequently contain thunk functions produced by the importer for this purpose.  Before you added the external reference what was the jal instruction referencing?  Is there a relocation on the jal instruction which was not handled properly?

**Comment by lab313ru** [comment]
It is not an elf file, but an object file with manually parsed "patches" (relocations). So, I'm just creating ".imports" section, creating imported lines, then placing references to every import.

**Comment by lab313ru** [comment]
So, in my case I don't have any thunk function to be called. I just have import numbers, and a patch table, which references some calls to these imports. How should I manage it?

**Comment by lab313ru** [comment]
Dealt with this by creating functions for import addresses (they were subroutines before).

**Comment by ghidra1** [comment]
If you have addresses for each function you can do that, although that does not facilitate navigation linkage to other project files which may contain the actual function.  If this is required a thunk function can refer to am External Location function which is linked to an external program file.

**Comment by lab313ru** [comment]
But what if it is just an object file that contains something like `extern SUPER_SYMBOL`, and doesn't specify in which binary and library. How should I show it to user?

**Comment by ghidra1** [comment]
It depends upon your objectives.  If you have prelinked external function addresses (as it sounds like for your case) referenced by the code, creating function symbols at those locations may suffice, although the functions will only appear in the function table/tree and be referenced at the call sites.

If it matters to you what Library those symbols map to, additional work will need to be done to locate them and link them up via an external function.  If you have no information to indicate a list of relevant libraries, I'm not sure how you would identify the library mapping.  Elf binaries indicate a list of libraries and their search order.

What is the format of your object file?

**Comment by lab313ru** [comment]
Format is PSX PsyQ OBJ. I wrote a loader for it in my ghidra_psx_ldr
already and just added names at these addresses. But when I want to specify
that every address is external, it shows result as this issue references.

вт, 23 июл. 2019 г. в 17:00, ghidra1 <notifications@github.com>:

**Comment by ghidra1** [comment]
You could try something like the logic below to convert your function to thunks to an External Function.  I have not tested this but it should be close.   The key is that the call instruction pcode can only refer to a memory address while the external function has a fake non-memory address.  This prevent the call instruction from referring directly to the external function in the fake external space. 

`void convertFunctionToExternalThunk(Function f) {
		
		if (f.isThunk() || f.isExternal()) {
			throw new IllegalArgumentException("Invalid function specified");
		}
		Program program = f.getProgram();
		Symbol s = f.getSymbol();
		SymbolPath namespacePath = new SymbolPath(s.getParentNamespace().getSymbol());
		try {
			Msg.debug(CreateFunctionCmd.class, "Creating external function symbol: " + s.getName());
			ExternalManager extMgr = program.getExternalManager();
			ExternalLocation extLoc =
				extMgr.addExtFunction(Library.UNKNOWN, s.getName(), null, s.getSource());
			Library lib = extMgr.getExternalLibrary(Library.UNKNOWN);
			Namespace ns = NamespaceUtils.createNamespaceHierarchy(namespacePath.getPath(), lib, program, SourceType.ANALYSIS);
			lib.setParentNamespace(ns);
			f.setParentNamespace(program.getGlobalNamespace()); 
			f.setThunkedFunction(extLoc.getFunction());
		}
		catch (DuplicateNameException | InvalidInputException | CircularDependencyException e) {
			// ignore - unexpected
		}
	}`

**Comment by ghidra1** [comment]
I suggest you import a sample Elf binary (e.g., bash) to see how the results of such a thunk to external function appear.
