### ISSUE TITLE
[AVR-GCC] Default symbols are not loaded

### ISSUE THREAD

**Issue by Sh3idan** [NationalSecurityAgency/ghidra#807]
**Describe the bug**
Symbols describe in the avr8.pspec are not loaded. At code:0x0, the symbol should be "Reset" but FUN_code_000034 is written.

**To Reproduce**
1. Compile a simple program with the last version of Arduino IDE
2. Load the .elf binary in Ghidra
3. Analyze the binary with the default parameters
4. Go to code:0x0
5. See the error

**Expected behavior**
Load symbols !

**Screenshots**
-

**Attachments**
-

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 11.0
 - Ghidra Version: 9.4

**Additional context**
-

**Comment by astrelsky** [comment]
When you add the program to ghidra you need to select options and check to apply processor defined labels.

**Comment by Sh3idan** [comment]
Oh Thanks. I never see this view before.

**Comment by rickhousley** [comment]
Is there a way to re-apply this post loading? E.g. after analysis and modifications have already been completed?

**Comment by ryanmkurtz** [comment]
No, you would have to write a script to do it.
