### ISSUE TITLE
Get datatype from GhidraClass

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#814]
How may I retrieve the correct datatype which corresponds to a GhidraClass? I tried taking both the ID and the Universal ID of the class and its symbol but according to the datatype manager these id's are different.

Trying to convert the full namespace to a DataTypePath won't work if if it has been demangled, is from dwarf info, etc.

**Comment by ghidra1** [comment]
We are hoping to improve this and create a strong relationship which can withstand name changes, etc.  Currently, the utility method VariableUtilities.findExistingClassStruct(GhidraClass, DataTypeManager).  There are other static methods on this utility class which may be of help.  This utility makes use of related methods in the DataTypeUtilities which attempt to fuzz a namespace path into the search criteria.  Keep in mind that renaming a GhidraClass will not rename or reparent the associated structure.  At present, this must be done explicitly.

**Comment by astrelsky** [comment]
> We are hoping to improve this and create a strong relationship which can withstand name changes, etc. Currently, the utility method VariableUtilities.findExistingClassStruct(GhidraClass, DataTypeManager). There are other static methods on this utility class which may be of help. This utility makes use of related methods in the DataTypeUtilities which attempt to fuzz a namespace path into the search criteria. Keep in mind that renaming a GhidraClass will not rename or reparent the associated structure. At present, this must be done explicitly.

Ah yes this is exactly what I was looking for thank you.
