### ISSUE TITLE
Structure Components not updated (Ghidra 9.1)

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#818]
This was likely caused by changes during the addition of bitfields to the Structure interface.

**Describe the bug**
Copying or creating a new structure, using replaceWith(dt) and then clearing/deleting components results in structure with the same components as the original dt.

**To Reproduce**
1. Create a StructureDataType (parent) and add two components
2. Create a new StructureDataType (child) with the same name and same DataTypeManager but a different CategoryPath.
3. use child.replaceWith(parent)
4. use child.clearComponent(1)
5. Check the child structure in the DataTypeManager and find that the parent structures component 1 still exists within child with the same name and comment.

**Expected behavior**
The cleared/deleted component to be non existent in the child structure.

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17763.615]
 - Java Version: 12.0.1
 - Ghidra Version: 9.1 https://github.com/NationalSecurityAgency/ghidra/commit/c7f934c9d1fcc55731d7d388e46407fd4775072b

**Additional context**
Just for additional context, this is the exact method being used. The AbstractClassTypeInfoModel model and GnuUtils classes are part of additions for a GnuRtti analyzer and are still in a private repo. The names of the functions should give a good enough idea of what is going on though.
```
private Structure convertParentToVirtual(AbstractClassTypeInfoModel parent, CategoryPath path) {
        DataTypeManager dtm = program.getDataTypeManager();
        Structure parentStruct = parent.getClassDataType();
        Set<AbstractClassTypeInfoModel> bases = parent.getVirtualBases();
        if (bases.isEmpty()) {
            // no virtual bases to remove.
            return parentStruct;
        }
        Set<String> vBaseNames = new HashSet<>(bases.size());
        for (AbstractClassTypeInfoModel base : bases) {
        	vBaseNames.add(base.getName());
        }
        StructureDataType struct = new StructureDataType(path, parent.getName(), 0, dtm);
        // copy all the parents components.
        struct.replaceWith(parentStruct);
        for (DataTypeComponent comp : parentStruct.getComponents()) {
        	if (vBaseNames.contains(comp.getDataType().getName())) {
        		// remove all virtual bases from the parent
        		while (struct.getLength() > comp.getOffset()) {
                        	struct.deleteAtOffset(comp.getOffset());
                        } break;
        	}
        }
        if (struct.getNumDefinedComponents() == 0) {
        	int length = struct.getLength() - 1;
        	struct.deleteAll();
        	struct.add(GnuUtils.getVptr(dtm), program.getDefaultPointerSize(), "_vptr", null);
        	struct.growStructure(length - struct.getLength());
        }
        // return the new struct which correctly resembles the virtual parent to be inherited.
        return struct;
    }
```
There are also some other strange things going on. I'm attaching some picture of them.
![structure_bug](https://user-images.githubusercontent.com/46897303/61582686-cc24fc80-aafb-11e9-9be0-32197aea3c17.PNG)

**Comment by dev747368** [comment]
It would really help if you could come up with a small, self-contained example that showed the problem.

For instance, your example isn't showing how the new struct you create via "new StructureDataType()" is getting added to the program's DTM, or what it looks like after removing the field from the structure.

**Comment by astrelsky** [comment]
> It would really help if you could come up with a small, self-contained example that showed the problem.
> 
> For instance, your example isn't showing how the new struct you create via "new StructureDataType()" is getting added to the program's DTM, or what it looks like after removing the field from the structure.

So, strangely enough, I can no longer get this to occur. I'm going to close this but if it occurs again and I can provide a simple ghidra script to duplicate it then I will reopen it.
