### ISSUE TITLE
Mips: opcodes with underline?

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#819]
Sometimes disassembler gives me opcodes like `_nop`, `_sll`, `_sw`, etc...

It is possible to get them by disassembly but impossible to assemble back? Bug?

**Comment by mumbel** [comment]
those are the instructions in the delay slot

**Comment by ghidra1** [comment]
As @mumbel  indicated this notation is added dynamically.  When entering into the assembler the '_' prefix should be omitted.  This is not considered a bug.
