### ISSUE TITLE
Wildcards when using Memory Search doesn't work as intended

### ISSUE THREAD

**Issue by nithax** [NationalSecurityAgency/ghidra#82]
**Describe the bug**
When using the 'Memory Search' from Search > Memory, the 'wildcard' option doesn't work as intended. It seems like it's replacing "?" with 00 instead of an actual wildcarded value.

**To Reproduce**
1. Go to Search in the Menu tab
2. Click on 'Memory'
3. Type out any AOB with a wildcard. I used '64 A1 ? ? ? ?'  (mov eax, ? ? ? ? )
4. Click 'Search All' 
5. Notice that the search results only give 64 A1 00 00 00 00 results.

**Expected behavior**
Expected similar behavior as IDA giving any result including the 00 00 00 00 ones.

**Screenshots**
https://i.imgur.com/v8I4N1e.png

**Environment**
 - OS: Windows 10
 - Version: 9.0 PUBLIC

**Comment by Randshot** [comment]
@nithax It seems you need to use dots `.` for wildcards.
e.g.:```
64 A1 . . . .
```

**Comment by nithax** [comment]
Just tried "." instead of "?" and I get the same results. Definitely something wrong here

https://i.imgur.com/JFfAtjI.png

**Comment by Randshot** [comment]
I had success with removing the spaces between the dots/questionmarks:
`64 A1 ........` or `64 A1 ????????`

**Comment by nithax** [comment]
Ah thanks @Randshot , that works.
