### ISSUE TITLE
SAXParseException when loading binary

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#820]
9.0.4 (javac 11.0.2) for both for `ghidraRun` and `sleigh`

Writing some SLEIGH (https://github.com/mumbel/ghidra/tree/riscv) and it compiles with the sleigh tool with no ERROR, several unreferenced and unused WARN, but it does generate an output file.

Probably just based on last modified time of sinc, when importing a test binary, Ghidra locks up when I click OK or Options.  Eventually I'll xkill and reload Ghidra, this leads to a popup error when I try to click OK/Options. 
```
RuntimeException - org.xml.sax.SAXParseException; lineNumber: 581359; columnNumber: 31; XML document structures must start and end within the same entity.
java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 581359; columnNumber: 31; XML document structures must start and end within the same entity.`
```

The development has gone smoothly so far, only recently I started adding aliases/psuedo-instructions so I assume this is the cause.  Adding the opcodes in bit pattern of pairs of instructions for things like: 

- reg1!=reg2 and reg1=reg2
- reg!=zero and reg=zero
- imm!=0 and imm=0

Will be trying master and reducing the SLEIGH, but wanted to go ahead and report since it didn't error out in `sleigh`

**Comment by mumbel** [comment]
Wondering now if its an OOM issue, switched from a VM to laptop and it doesn't error out/lock up in 9.0.4.  No issues in launching from eclipse either (have been just copying RISCV to 9.0.4 to test SLEIGH).

**Comment by ryanmkurtz** [comment]
We typically see this when Ghidra is killed while it's in the middle of compiling a processor.  The .sla file that gets written to disk is incomplete and cannot be parsed the next time Ghidra is started.  Could that describe the behavior you are seeing?

**Comment by mumbel** [comment]
After launching ghidra, after modifying SLEIGH, it would just sit there.  I left it for a minute+ and it never finished compiling. this is self inflicted the second time around since i killed it while it's compiling.  I had zero issues after switching from a VM to laptop, so must be a resource issue in the VM.  I made a bunch of changes so I'll try VM again to see if it ever finishes (I'll leave it for longer).

Thanks for verifying the issue.
