### ISSUE TITLE
Disassembly error on x86_64 for "movbe word [r15 + rax*2], cx"

### ISSUE THREAD

**Issue by find0x90** [NationalSecurityAgency/ghidra#822]
**Describe the bug**
Ghidra doesn't doesn't recognize the bytes "66410f38f10c47" for x86_64.

These bytes disassemble as "movbew  %cx, (%r15,%rax,2)" in objdump and "movbe word [r15 + rax*2], cx" in radare2. 

**To Reproduce**
Download the test.txt below (A flat file containing the bytes. The '.txt' extension is to allow uploading to GitHub)
Load it as a flat binary. 
Select x86, default, 64, little, gcc for the language.
Don't autoanalyze.
Try to disassemble at address 0x0.

**Expected behavior**
The bytes should disassemble to "movbe word [r15 + rax*2], cx".

**Screenshots**
N/A

**Attachments**
[test.txt](https://github.com/NationalSecurityAgency/ghidra/files/3415110/test.txt)

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Java Version: 11.0.2
 - Ghidra Version: 9.1 (built from master: c7f934c9d1fcc55731d7d388e46407fd4775072b)

**Additional context**
Disassembling at address 0x1 and 0x2 both disassemble to slightly different instructions. 
00000001 41 0f 38 f1 0c 47 MOVBE dword ptr [R15 + RAX * 0x2],ECX
00000002 0f 38 f1  0c 47 MOVBE dword ptr [RDI + RAX * 0x2],ECX
Maybe a case is missing for the combination of a data size override prefix with a REX prefix for the definition of MOVBE?

**Comment by mumbel** [comment]
I dont know intel very well, but
```
--- a/Ghidra/Processors/x86/data/languages/ia.sinc
+++ b/Ghidra/Processors/x86/data/languages/ia.sinc
@@ -3712,6 +3712,7 @@ define pcodeop swap_bytes;
 :MOVBE m16, Reg16       is vexMode=0 & opsize=0 & mandover=0 & byte=0xf; byte=0x38; byte=0xf1; Reg16 ... & m16  { m16 = swap_bytes( Reg16 ); }
 :MOVBE m32, Reg32       is vexMode=0 & opsize=1 & mandover=0 & byte=0xf; byte=0x38; byte=0xf1; Reg32 ... & m32  { m32 = swap_bytes( Reg32 ); }
 @ifdef IA64
+:MOVBE m16, Reg16       is vexMode=0 & opsize=0 & mandover=1 & byte=0xf; byte=0x38; byte=0xf1; Reg16 ... & m16  { m16 = swap_bytes( Reg16 ); }
 :MOVBE Reg64, m64       is vexMode=0 & opsize=2 & mandover=0 & byte=0xf; byte=0x38; byte=0xf0; Reg64 ... & m64  { Reg64 = swap_bytes( m64 ); }
 :MOVBE m64, Reg64       is vexMode=0 & opsize=2 & mandover=0 & byte=0xf; byte=0x38; byte=0xf1; Reg64 ... & m64  { m64 = swap_bytes( Reg64 ); }
 @endif

```

might at least get the disassembler working

**Comment by find0x90** [comment]
@mumbel thanks! I will try that patch as a workaround for now.

**Comment by ryanmkurtz** [comment]
071f98e18bb28afd242efeb395a9d7585a7b26e2
