### ISSUE TITLE
Batch import of object files from archive with analyzeHeadless?

### ISSUE THREAD

**Issue by rgov** [NationalSecurityAgency/ghidra#823]
When I use the UI to import an archive file, I'm prompted to batch import the object files inside it. Is that possible with analyzeHeadless?

**Comment by dev747368** [comment]
Not at this time.  However, GFileSystem API is generally accessible, and you could implement something in a script that ran in the analyzeHeadless session.

The MSLibBatchImportWorker and MSLibBatchImportGenerator scripts are other examples that might point you in the right direction.
