### ISSUE TITLE
Version Control Diff and Revert 

### ISSUE THREAD

**Issue by metal-crow** [NationalSecurityAgency/ghidra#824]
Using the Ghidra version control system for a shared repository, i recently had a problem where i wanted to undo a specific commit that changed a significant amount of the binary that was discovered to be incorrect some commits later (i modified the control flow for a function which caused a reanalysis of the binary and resulted in some code being cleared).
I was wondering if Ghidra offers a way to either take all the changes from one commit and apply them to another (the program differences tool allows you to do one at a time, but not in batch), or if, more conveniently and like git, Ghidra supported ways to revert specific commits.

**Comment by ghidra1** [comment]
Ghidra is limited to:
1. Removing the newest or oldest stored version
2. Viewing or diffing against any stored version
3. Checking out the latest version

You can open and save an old version and apply differences to build-up a new file.  Nothing like what you are asking for exists.
