### ISSUE TITLE
SLEIGH docs do not indicate that that only 1 register space is allowed.

### ISSUE THREAD

**Issue by hedgeberg** [NationalSecurityAgency/ghidra#828]
If 2 register spaces are defined in the SLEIGH definition for an ISA, it will compile to .sla perfectly well, but on loading a project using the ISA, Ghidra will produce an error. 

after searching the code base, the following can be found in DefaultAddressSpace:

```
else if (space.getType() == AddressSpace.TYPE_REGISTER) {
	if (registerSpace != null || !space.getName().equalsIgnoreCase("register")) {
		// Ghidra address encoding only handles a single register space
		throw new IllegalArgumentException(
			"Ghidra can only support a single Register space named 'register'");
		}
	registerSpace = space;
}
```
However, the documentation for SLEIGH makes no indication of this. Is that because the register space limit of 1 is planned to be changed, or is this the permanent state of Ghidra? If there are no plans to change this limit, it might be wise to add some sort of warning like the ones in other parts of the documentation. 

In addition, it might also be worth changing the error, as it makes it sound like Ghidra would have no issue with handling multiple register spaces if it werent for the hardcoded name.

**Comment by ghidra1** [comment]
The sleigh "register" space is intended to represent internal registers to a processor which have no specific offset defined by the processor architecture.  Registers can be placed within this space at any offset which suits your needs.  If the processor architecture defines an addressable space containing registers, that space should be defined as a ram space with appropriate dimensions (e.g., size, wordsize).

**Comment by hedgeberg** [comment]
Understood, my bigger issue is more with the lack of documentation in SLEIGH and the bad error information when this failure is encountered.
