### ISSUE TITLE
Font size is unchangeable?

### ISSUE THREAD

**Issue by soatok** [NationalSecurityAgency/ghidra#83]
**Is your feature request related to a problem? Please describe.**

The font is rather small in CodeBrowser and there is no obvious means to make the font larger. I like to use size 16 font (for Liberation Mono).

**Describe the solution you'd like**

An obvious place to make the editor's font larger. Possibly a `File > Preferences` window that lets you customize the UI?

**Describe alternatives you've considered**

Searched the help file, tried to locate the settings.

**Comment by nithax** [comment]
It's located in Edit > Tools Options > Listing Display

https://i.imgur.com/uEyI6Zb.png

**Comment by soatok** [comment]
Thanks! My other recommendation would be to make this easily found by searching for "font" or "font size" in the help document.

**Comment by c02y** [comment]
It seems this only affects font in `Listing` window, is it able to change all the font in the whole Ghidra program, including all the windows, settings, menu bar.

The default font in Ghidra is so weird, seems aged, totally different from the font in my system.

Platform: Manjaro+KDE

![ghidra](https://user-images.githubusercontent.com/2135996/67061168-0ac96200-f192-11e9-802b-526972a4a0a8.png)

**Comment by endeavour** [comment]
This worked for me on Manjaro + KDE:

Edit ```/opt/ghidra/support/launch.properties``` and change the line:
```VMARGS_LINUX=-Dsun.java2d.uiScale=1```
to
```VMARGS_LINUX=-Dsun.java2d.uiScale=2```

**Comment by RenaKunisaki** [comment]
> This worked for me on Manjaro + KDE:
> 
> Edit `/opt/ghidra/support/launch.properties` and change the line:
> `VMARGS_LINUX=-Dsun.java2d.uiScale=1`
> to
> `VMARGS_LINUX=-Dsun.java2d.uiScale=2`

That works, but you can't set it to eg 1.5, so for me the choices are too small or too big.

**Comment by dragonmacher** [comment]
> That works, but you can't set it to eg 1.5, so for me the choices are too small or too big.

Another option, albeit crude, is to use the global font override in the properties file:
`VMARGS=-Dfont.size.override=`

You can make this whatever you wish, but it affects all widgets and often does not look attractive.

**Comment by iortego42** [comment]
On Edit > Tools Options, I added a filter 'font' to see all fields related with font features. then select them and i can manually set the size and font family.
I need to change it over multiple fields because each of them applys on diferent windows of Ghidra.

**Comment by dragonmacher** [comment]
Fonts can now be changed via the theme system.   This is not done in the Code Browser (greed dragon) tool, but instead in the Front End (primary window) tool via `Edit -> Theme -> Configure`

From there you can change the font size globally with the toolbar buttons at the top of the window.  You can also change the size and type of individual fonts as desired.
