### ISSUE TITLE
Use the native open dialog for importing

### ISSUE THREAD

**Issue by rgov** [NationalSecurityAgency/ghidra#830]
The file import dialog is a little jarring to use on macOS, as it is significantly different than the native open dialog. I understand that it's not likely that Ghidra will behave or look like a regular macOS app, but in this case, couldn't the system APIs just be used?

<img width="912" alt="image" src="https://user-images.githubusercontent.com/108767/61737962-48674c00-ad57-11e9-8e3f-163528d705b7.png">

Note that important features are missing such as:

* User's bookmarks, network shares, tagged documents, etc. in the sidebar
* The file preview (Quick Look) pane
* Different browsing modes such as Miller columns
* A search field
* Automatic refresh

Also an important consistency detail is that the "Cancel" button goes on the left in Mac apps.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/108767/61738018-616ffd00-ad57-11e9-8afd-94ef0a9dca7a.png">

**Comment by dragonmacher** [comment]
I believe the correct path is to use the native chooser where possible.

Originally, we chose to use our own version of the chooser for the following reasons:

- **Background thread capability to handle slow network shares**
- Uniform look-and-feel across platforms
- Lack of native chooser API support

Much has changed since we created our own chooser.  It is worth exploring the possibility of abandoning our chooser in favor of the native platform's version.

**Comment by Piruzzolo** [comment]
It would be a big usability improvement on Windows too, the path to file is currently non pasteable directly from Explorer, so one has to manually move to the right folder

**Comment by ghidra1** [comment]
If using the file Explorer you can simply drag the file onto Ghidra to invoke the import on that file.  No chooser required for the drag-n-drop case.

**Comment by dragonmacher** [comment]
We researched this a bit and found no simple API for using the native chooser.  The JavaFX API does have this capability, but we use Swing.  Using JavaFX from Swing is possible, but would significantly increase the complexity of our development and build processes.

As @ghidra1 pointed out, you can have a native file chooser running along side of Ghidra, dragging files from the chooser into Ghidra as desired.

**Comment by dragonmacher** [comment]
@Piruzzolo For what it is worth, the path text field on the file chooser is not editable.  However, you can type/past directory paths in to the 'File name' text field, pressing Enter when you are done.  This will cause the chooser to load the entered directory.
