### ISSUE TITLE
What is pcodeTest

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#833]
During my attempts to setup CI, I found following command `pcodeTestReport`  All 6 tests was failing for me, so I was curious what's this.

**Comment by mumbel** [comment]
A link to recon slides talking about it. 
Starts around 36/51
https://github.com/NationalSecurityAgency/ghidra/wiki/files/recon2019.pdf

**Comment by ghidra1** [comment]
These tests have a corresponding compiled pcodetest binary which must be created before the tests can be run.  We did not want to compile and store these test binaries within the repository.  The C source which must be built separately for each test can be found within the Ghidra SleighDevTools extension module.  This extension must be installed/unpacked to access the source which also include python build scripts.  You will need to obtain the appropriate cross-build toolchain and adjust the build scripts for your environment before building the pcodetest binary.  There is a README file but as you will see it is rather involved and not well documented.

**Comment by ryanmkurtz** [comment]
I think this was sufficiently answered...closing.

**Comment by kant2002** [comment]
thanks
