### ISSUE TITLE
Disassembly error on x86_64 for "lahf" and "sahf"

### ISSUE THREAD

**Issue by find0x90** [NationalSecurityAgency/ghidra#837]
**Describe the bug**
Ghidra doesn't doesn't recognize the bytes "9f" and "9e" for x86_64.

**To Reproduce**
Download the lahf.txt and sahf.txt files below (Flat files containing the bytes. The '.txt' extension is to allow uploading to GitHub)
Load each as a flat binary.
Select x86, default, 64, little, gcc for the language.
Don't autoanalyze.
Try to disassemble at address 0x0.

**Expected behavior**
The bytes should disassemble to "lahf" and "sahf".

ndisasm disassembles these as "lahf" and "sahf", respectively. 
```
ndisasm -b64 ./lahf.txt
00000000  9F                lahf
```
```
ndisasm -b64 ./sahf.txt
00000000  9E                sahf
```

**Screenshots**
N/A

**Attachments**
[lahf.txt](https://github.com/NationalSecurityAgency/ghidra/files/3432792/lahf.txt)
[sahf.txt](https://github.com/NationalSecurityAgency/ghidra/files/3432793/sahf.txt)

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Java Version: OpenJDK 11.0.2
 - Ghidra Version: 9.1 (built from master: fa20ba376266011b9e733a9df9254c2c734bfdd2)

**Additional context**
[Intel® 64 and IA-32 Architectures Software Developer’s Manual Volume 2 (2A, 2B, 2C & 2D): Instruction Set Reference, A-Z](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf) notes on page 616 (LAHF) and page 1232 (SAHF) that `CPUID.80000001H:ECX.LAHF-SAHF[bit 0] = 1` must be true for these instructions to decode and execute, they are otherwise undefined. I'm not sure how Ghidra should handle instructions that are gated by CPUID flags but using the [MacCPUID](https://software.intel.com/en-us/download/download-maccpuid) from Intel's website shows that the bit is set on my MacBook which hardly has an unusual CPU. So, unless this causes issues, this should probably disassemble under x86_64.

**Comment by mumbel** [comment]
That's pretty runtime specific based on the cpuid instruction, I could see leaving that not implemented.  You could get around it by removing the `& bit64=0` in ia.sinc for `:lahf` and `:sahf`.  If it's a localized/minimal issue, I think you could highlight the byte and press Ctrl+r and change contextreg(32) to 0

**Comment by find0x90** [comment]
Changing contextreg(32) to 0 does allow it to disassemble. I didn't know you could configure that outside of the language selection before loading a file, let alone configure it per instruction/memory-range. That is a useful workaround, thanks!

Maybe adding this isn't as simple as I think, I'm really not aware of the potential impact. That being said, I checked [LLVM's feature definitions for x86 targets](https://github.com/llvm-mirror/llvm/blob/master/lib/Target/X86/X86.td) `FeatureLAHFSAHF` is specified as a feature for many microarchitectures, both Intel and AMD. On the other hand, these instructions are probably not particularly common so this issue isn't all that disruptive. More problematic than the individual instruction failing to disassemble is that it stops code analysis when it is encountered. 

Assuming this change would cause no other issues, I would prefer if it was added. Especially since I don't know of a way of specifying microarchitecture or configuring CPUID with Ghidra and neither byte is repurposed in long mode.
