### ISSUE TITLE
Disconnect client from server during runtime.

### ISSUE THREAD

**Issue by LucienBrule** [NationalSecurityAgency/ghidra#838]
**Is your feature request related to a problem? Please describe.**

As a User of the Ghidra Client Workspace tool, I would like the ability to disconnect from the currently associated Ghidra Server. 

**Describe the solution you'd like**
The button in the lower right should disconnect from the server, as currently, you can only connect to the server by clicking this button.

**Describe alternatives you've considered**
Currently, to solve this problem you can close the whole application and you will be disconnected.

**Additional context**
![Screen Shot 2019-07-25 at 12 44 14 PM](https://user-images.githubusercontent.com/6063022/61903978-b6884c00-aeda-11e9-9195-05824cd376b7.png)

**Comment by dev747368** [comment]
There are some technical issues that make adding this feature not feasible.
