### ISSUE TITLE
Where is actual source code of ghidra?

### ISSUE THREAD

**Issue by KiYugadgeter** [NationalSecurityAgency/ghidra#84]
I don't found actual source code of ghidra.
Where I can see?

**Comment by recvfrom** [comment]
Check out https://github.com/NationalSecurityAgency/ghidra/wiki/Frequently-asked-questions#where-is-the-complete-ghidra-source-code

**Comment by holygeek** [comment]
See also: https://github.com/kelseyhightower/nocode (sorry can't resist).
