### ISSUE TITLE
Get Tool from Analyzer

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#840]
I'm looking to retrieve the Tool from within an analyzer so I can use the FillOutStructureCmd to populate a class components before setting its super classes in place.

**Comment by ryanmkurtz** [comment]
Here's how an existing analyzer does it:
https://github.com/NationalSecurityAgency/ghidra/blob/6d4908f0cdb32b0cbd3954c4a416e721a168e54e/Ghidra/Features/MicrosoftCodeAnalyzer/src/main/java/ghidra/app/plugin/prototype/MicrosoftCodeAnalyzerPlugin/WindowsResourceReferenceAnalyzer.java#L79-L81

**Comment by astrelsky** [comment]
> Here's how an existing analyzer does it:
> https://github.com/NationalSecurityAgency/ghidra/blob/6d4908f0cdb32b0cbd3954c4a416e721a168e54e/Ghidra/Features/MicrosoftCodeAnalyzer/src/main/java/ghidra/app/plugin/prototype/MicrosoftCodeAnalyzerPlugin/WindowsResourceReferenceAnalyzer.java#L79-L81

Thank you.
