### ISSUE TITLE
Making use of the segment op?

### ISSUE THREAD

**Issue by hedgeberg** [NationalSecurityAgency/ghidra#841]
Hey guys, I've been trying to make use of the segment() userop as suggested by @emteere, but it continues to give me issues. 

I built the following segmentop section into my .cspec file:
```
  <segmentop space="ram" userop="segment" baseinsize="1" innerinsize="2" farpointer="yes">
    <baseop code="INT_ZEXT"/>
    <baseop code="INT_LEFT" value="16"/> 
    <innerop code="INT_ZEXT"/>
  </segmentop> 
```

and I try calling it in my SLEIGH binding as `local addr:3 = segment(0xF:1, offset);` where `offset` is an arg with value 0xfdde. I expect this to produce a pointer that the decompiler recognizes as such to address 0xffdde, but instead the disassembler generates the following calculated offset: `=>DAT_ram_010cde`.
In addition, the decompiler handles this particularly badly, alternating between crashing due to an unhandled error and deciding to eliminate the segment altogether and just dereference one of the constants used to build that value of 0xfdde.

I'm clearly doing something wrong, but as far as I can tell I'm using it the exact same way its used in the x86-16 library. If anyone could help me figure out what I'm doing wrong, it would be much appreciated.

**Comment by GregoryMorse** [comment]
Wlell 0x10cde-0xfdde=0xF00 so your segment got an 8 bit shift not a 16 bit shift.  This is likely since you are trying to merge a single byte segment register with a 2 byte offset.  Possibly a bug in the code when the baseinsize!=innerinsize.

**Comment by mumbel** [comment]
What does the final pcode look like for that example instruction?

**Comment by GregoryMorse** [comment]
```local offset:2 = 0xfdde;
local addr:3 = segment(0xF:1, offset);```

```<op code="1"><seqnum space="ram" offset="0x10000000" uniq="0x0"/><addr space="unique" offset="0x15c60" size="2"/><addr space="const" offset="0xfdde" size="2"/></op><op code="9"><seqnum space="ram" offset="0x10000000" uniq="0x1"/><addr space="unique" offset="0x15c80" size="3"/><addr space="const" offset="0x0" size="4"/><addr space="const" offset="0xf" size="1"/><addr space="unique" offset="0x15c60" size="2"/></op>
```

**Comment by hedgeberg** [comment]
I played a lot with the shift value, including deleting the shift opcode in the binding definition altogether. It never made any difference, so I thought it was failing to resolve, but when I set force="true" in the cpsec, it never threw the exception that was specified in userop.cc, meaning its resolving fine. In fact, no values in the cspec file make any actual difference in result. 

I'll get a snippet of the pcode later for you, maybe we can puzzle this out. 

The more I play with it though, the more I think sleigh's stateless parser model and this ISA aren't really meant for each other. The de-compiler really doesn't like that pointers don't map directly to the intended region of memory. If there were a way to change the argument parsing mechanism for load/store operations such that the de-compiler ignored the steps to building the value and just used the final value for decompiling, I think that would work, but no matter how many ways I've tried to rework the constructors it just doesn't seem to change the decompilation, since there's no differentiation between pcode used to build the argument values and the pcode used for the actual body of the instruction.

**Comment by hedgeberg** [comment]
Ok, sorry for the day or 2 of delay @GregoryMorse @mumbel, just got around to getting some documentation for this.

Note that, for the purposes of any examples here, `...` is used to reprees

This is the slice of rl78.slaspec that is relevant to this issue:

```
define token op1b (8)
	op1b_byte = (0,7)
;
    ...
define token immediates_16bit (8)
	imm16 = (0,15)
;
    ...
define pcodeop segment;
    ...
b_offset_word: disp16[B] is B & disp16
		{ local base:1 = 0x0F;
		  local loc:3 = segment(base, disp16);
		  export *[ram]:2 loc; }
    ...
:MOVW b_offset_word,AX 			is op1b_byte=0x58; b_offset_word & AX
{
	b_offset_word = AX;
}
```
and this is the segmentop definition in my .cspec file. Duplicated here for thoroughness sake, even though its in the original post:

```
  <segmentop space="ram" userop="segment" baseinsize="1" innerinsize="2" force="true" farpointer="yes">
    <baseop code="INT_ZEXT"/>
    <baseop code="INT_LEFT" value="16"/> 
    <innerop code="INT_ZEXT"/>
  </segmentop> 
```

Just confirmed this is building, I'll dig up the compiled section in the .sla file in a second, as well as an example of the pcode representation in CodeBrowser.

**Comment by hedgeberg** [comment]
Ok, here's the pcode generated by the code browser's analysis. Note that right before this, B was set to 0xC0 (signed, 8 bits) and AX was set to 0:

```
      ram:000d8c 58 20 fe                            MOVW         0xfe20[B]=>DAT_ram_010cde,AX
                                                      $U11c0:2 = INT_ZEXT B
                                                      $U11e0:2 = INT_ADD 0xfe20:2, $U11c0
                                                      $U1200:3 = CALLOTHER "segment", 15:1, $U11e0
                                                      $U1210:2 = COPY AX
                                                      STORE ram($U1200), $U1210
```

I'll find the .SLA snippets responsible for the decoding of this instruction in a moment.

**Comment by hedgeberg** [comment]
Ok, finally, the following are all taken from rl78.sla.

Here's the MOVW instruction's definition:
```
<constructor parent="0x0" first="1" length="3" line="893">
    <oper id="0x139"/>
    <oper id="0x13a"/>
    <print piece="MOVW"/>
    <print piece=" "/>
    <opprint id="0"/>
    <print piece=","/>
    <opprint id="1"/>
    <construct_tpl>
        <null/>
        <op_tpl code="BUILD">
            <null/>
            <varnode_tpl>
                <const_tpl type="spaceid" name="const"/>
                <const_tpl type="real" val="0x0"/>
                <const_tpl type="real" val="0x4"/>
            </varnode_tpl>
        </op_tpl>
        <op_tpl code="COPY">
            <varnode_tpl>
                <const_tpl type="handle" val="0" s="space"/>
                <const_tpl type="handle" val="0" s="offset"/>
                <const_tpl type="handle" val="0" s="size"/>
            </varnode_tpl>
            <varnode_tpl>
                <const_tpl type="spaceid" name="register"/>
                <const_tpl type="real" val="0x18"/>
                <const_tpl type="real" val="0x2"/>
            </varnode_tpl>
        </op_tpl>
    </construct_tpl>
</constructor>
```

here's b_offset_word's operand definition section:
```
<operand_sym name="b_offset_word" id="0x139" scope="0x4d" subsym="0xc6" off="1" base="-1" minlen="2" index="0">
    <operand_exp index="0" table="0x0" ct="0x30"/>
</operand_sym>
```

and here's b_offset_word's subtable definion:
```
<subtable_sym name="b_offset_word" id="0xc6" scope="0x0" numct="1">
   <constructor parent="0xc6" first="4" length="2" line="553">
      <oper id="0xc8" />
      <oper id="0xc7" />
      <opprint id="1" />
      <print piece="[" />
      <opprint id="0" />
      <print piece="]" />
      <construct_tpl>
         <handle_tpl>
            <const_tpl type="spaceid" name="ram" />
            <const_tpl type="real" val="0x2" />
            <const_tpl type="spaceid" name="unique" />
            <const_tpl type="real" val="0x1200" />
            <const_tpl type="real" val="0x3" />
            <const_tpl type="spaceid" name="unique" />
            <const_tpl type="real" val="0x1210" />
         </handle_tpl>
         <op_tpl code="INT_ZEXT">
            <varnode_tpl>
               <const_tpl type="spaceid" name="unique" />
               <const_tpl type="real" val="0x11c0" />
               <const_tpl type="real" val="0x2" />
            </varnode_tpl>
            <varnode_tpl>
               <const_tpl type="spaceid" name="register" />
               <const_tpl type="real" val="0x1b" />
               <const_tpl type="real" val="0x1" />
            </varnode_tpl>
         </op_tpl>
         <op_tpl code="INT_ADD">
            <varnode_tpl>
               <const_tpl type="spaceid" name="unique" />
               <const_tpl type="real" val="0x11e0" />
               <const_tpl type="real" val="0x2" />
            </varnode_tpl>
            <varnode_tpl>
               <const_tpl type="handle" val="1" s="space" />
               <const_tpl type="handle" val="1" s="offset" />
               <const_tpl type="real" val="0x2" />
            </varnode_tpl>
            <varnode_tpl>
               <const_tpl type="spaceid" name="unique" />
               <const_tpl type="real" val="0x11c0" />
               <const_tpl type="real" val="0x2" />
            </varnode_tpl>
         </op_tpl>
         <op_tpl code="CALLOTHER">
            <varnode_tpl>
               <const_tpl type="spaceid" name="unique" />
               <const_tpl type="real" val="0x1200" />
               <const_tpl type="real" val="0x3" />
            </varnode_tpl>
            <varnode_tpl>
               <const_tpl type="spaceid" name="const" />
               <const_tpl type="real" val="0x0" />
               <const_tpl type="real" val="0x4" />
            </varnode_tpl>
            <varnode_tpl>
               <const_tpl type="spaceid" name="const" />
               <const_tpl type="real" val="0xf" />
               <const_tpl type="real" val="0x1" />
            </varnode_tpl>
            <varnode_tpl>
               <const_tpl type="spaceid" name="unique" />
               <const_tpl type="real" val="0x11e0" />
               <const_tpl type="real" val="0x2" />
            </varnode_tpl>
         </op_tpl>
      </construct_tpl>
   </constructor>
   <decision number="1" context="false" start="0" size="0">
      <pair id="0">
         <instruct_pat>
            <pat_block offset="0" nonzero="0" />
         </instruct_pat>
      </pair>
   </decision>
</subtable_sym>
```

and here's AX, although I doubt that helps too much
```
<operand_sym name="AX" id="0x13a" scope="0x4d" subsym="0x2f" off="1" base="-1" minlen="0" index="1">
    <operand_exp index="1" table="0x0" ct="0x30"/>
</operand_sym>
```

**Comment by hedgeberg** [comment]
Still convinced I'm doing something wrong, frankly, and I don't think this is a bug, but I also don't understand the sleigh XML spec well enough to be able to read the compiled result well frankly. If anyone has any input, would be much appreciated. Thanks!

**Comment by mumbel** [comment]
after reading through the .cc and this... it makes no sense to me sorry.  Im getting base=(0xf << 16) + inner=(0xfe20 + 0xc0) = 0xffee0 . is this example still targeting 0xffdde?

have you tried just a simple test run with the instruction doing  (0xF0000 + imm16 + B) w/o using the segment pcodeop just to verify that its reading the rest of the state correctly

(im sure its just you copying over, but `define token immediates_16bit (8)` ,8 is a typo right?)

**Comment by hedgeberg** [comment]
Aw shoot i'm sorry, total spaceout on both. 
It's supposed to be 0xffdde instead of 0xffee0 because there's 2 dec (decrement) opcodes right beforehand, because this is being used in a meminit loop. Here's the disassembly w/o pcode:

```
      ram:000d87 53 c0                               MOV          B,#0xc0
      ram:000d89 f6                                  CLRW         AX
  -> LAB_ram_000d8a       XREF[1]:  ram:000d8f(j)  
 |    ram:000d8a 93                                  DEC          B
 |    ram:000d8b 93                                  DEC          B
 ---  ram:000d8c 58 20 fe                            MOVW         0xfe20[B]=>DAT_ram_010cde,AX
      ram:000d8f df f9                               BNZ          $LAB_ram_000d8a
```
CLRW is clear word, AX is a register pair, so at the entry to the loop at 0x0d8a AX = 0 and B = 0xc0, so its rolling up the initial stack area and 0ing it. 

And yeah, that was a mistake because I changed some things in that to clarify my garbled syntax (this was a project for the purpose of learning sleigh, and I haven't gone back to refactor some of the garbled tokens and constructors yet, its kind of a mess rn). I've edited it now, sorry for the mix-up.

Anyway, to make sure its all clear at this point: the issue here is that, as far as I can tell, its performing an 8-bit shift on the first operand and adding that to the second operand, regardless of the pcode in the segmentop definition in the .cspec file. And as far as anyone here can tell, there's no reason for this? Wondering if I need to consider converting this question into a bug report.

**Comment by hedgeberg** [comment]
Oh, also I should note that that that's a signed add, and I screwed up and did zext(b) instead of sext(b), fixing that now too. Full of mistakes on this one, but the offset shown in the disassembly is correct because this db was from when I submitted the bug. Ive since rolled back my changes, then un-rolled-back for the sake of making this issue, so that's why the errors got in there but the offset wasn't changed to reflect the mistakes. Basically, the pcode in the message, if youre reading this now, should be correct, offset and all. Sorry again for another mixup.

**Comment by GregoryMorse** [comment]
So basically you have (top varnode is output, followed by its inputs):
unique:1200:3=CALLOTHER(const:0:4, const:f:1, SEXT(register:1b)+space:offset:2)
CALLOTHER(const:0:4, … would be converted to SEGMENTOP - presuming number 0 is the segmentop and this is not a parseVolatile, parseJumpAssist or callotherfixup operation

**Comment by hedgeberg** [comment]
Yeah, that's my understanding as well, so then the question becomes what am I doing wrong? Because, as I understand it, this should be correct?

**Comment by GhidorahRex** [comment]
This question is fairly old now. I'm going to close it, but if there's still an issue here, we can reopen it. My  best guess @hedgeberg is that you possibly weren't restarting ghidra after every change to the .psec files. It's not enough to just run the reloadSleighLanguage script.
