### ISSUE TITLE
Plans for a Ghidra book?

### ISSUE THREAD

**Issue by Solumnant** [NationalSecurityAgency/ghidra#843]
I was wondering whether the developers of Ghidra were aware of any projects to write a book on Ghidra usage, similar to The IDA Pro Book. Both to document the usage of standard features and to document features that IDA pro doesn't possess.

I know there would be hurdles for experienced Ghidra developers to write a book on it's usage, but it would be nice to have some more extensive educational documentation for the program, as right now all RE books document how to use IDA Pro's features to achieve objectives.

It's possible that people are waiting to write a book on Ghidra once it's feature set becomes more stable and the open source community gets into the swing of contributing to the project, but I just thought I'd ask.

**Comment by dev747368** [comment]
Sorry, we're not aware of anything.

As a general FYI to anyone seeing this issue, we have a lot of docs in our in-program help pages and in the GhidraDocs/GhidraClass directory in our source tree.

**Comment by trietptm** [comment]
The Ghidra Book by Chris Eagle and Kara Nance: https://nostarch.com/GhidraBook
