### ISSUE TITLE
Remote Project Archive locked to 32-bit

### ISSUE THREAD

**Issue by lckehau** [NationalSecurityAgency/ghidra#844]
**Describe the bug**
This is halfway between a bug and a feature request.

It appears that remote Project Archives (rPA) default to 32-bit pointer size and that there is not mechanism to enforce 64-bit sizes.  One particularly noticeable side effect of this is that structs with pointer fields will gain a number of _undefined_ entries if unaligned, or shrink if aligned.

**To Reproduce**
1. Stand up a remote project...
2. Import a 64-bit file to the remote project
3. Create a dummy structure with pointer-type fields, in the imported file's File Archive
4. Through the **Data Type Manager**, create a Project Archive
5. Copy the dummy structure from the File Archive to the Project Archive
   * the dummy structure will have incorrect pointer sizes, and may change size of "Align" is set
   * attempts to force the type back to 64-bit via the _generic_clib_64_ archive will silently fail
6. Rename the dummy structure in the Project Archive
7. Copy the renamed dummy structure from the Project Archive back to the File Archive
   * the structure will return to 64-bit form if "Align" is not set
   * the structure returns to 64-bit form with offsets preserved (@dev747368)

**Expected behavior**
Expected archive size to be settable or modifiable, or for some override mechanism (forcing types to use _generic_clib_64_) to properly set pointer sizes to 64-bit.

Note: Through the Ghidra API, local/remote file and local project archives can have their pointer size's modified.  However, an extended search for a similar operation on remote project archives did not appear fruitful (though that definitely does not rule such a mechanism out entirely).

**Environment (please complete the following information):**
 - OS: Windows 10 - 64 bit
 - Java Version: 11.02
 - Ghidra Version: 9.0.4

**Comment by dev747368** [comment]
When a data type is copied to an archive and is not attached to a program anymore (which is where the data type organization is specified), yes, sizes may change in some types.

If that data type is copied back into a compatible program, the structure definition will match the original.

The other issues you raise (remote, various pre-built data type archives) aren't really relevant.

The main deciding factor (for structures) is the alignment option.  Alignment "on" means "use current compiler / language settings".  Alignment "off" means "user defined offsets".
Of course, even with alignment off, the fields could still change size, but they will stay at the offset you originally defined.

The pre-built data type archives that are included in Ghidra follow the same rules.  If you copy an aligned struct meant for windows 32 bit and put it in a 64 bit linux binary, the fields could be resized and re-aligned and probably won't make much sense.

You may see stuff about linkages between data types in data type archives and where they are copied to.  That it a mechanism to allow updating / synchronizing changes to shared archives into your program.

**Comment by lckehau** [comment]
My concern with alignment was that a type which had its size modified due to alignment would not be corrected when imported back into a 64bit program.  I tested this and it performs as you've described, and so I'll update the original issue to reflect that.  Thank you for your explanation of this.

The intent of using a separate project archive and placing all data structures strictly within this separate archive was to avoid needing to commit/update (i.e. via the linkages) between archives of multiple different files. Do you have recommendations for how to achieve this other than manually committing/updating each file on changes?

**Comment by dev747368** [comment]
I'm not sure if I'm completely understanding your question, but it seems like you are asking about reducing the work associated with maintaining a data type archive that could be shared between multiple related programs.
In general, each program that has data types that are linked to an external data type archive will need to perform a "Update Datatypes from" -> "your_external_archive" whenever it was appropriate to pull in updated data types.
Think of it in terms of source control, where the developer typically chooses when to checkin, pull, revert, etc.

**Comment by lckehau** [comment]
That answered my question exactly, thank you very much. I'll go ahead and close the issue as well as it doesn't seem like there was actually an underlying bug to begin with. Thanks again!
