### ISSUE TITLE
Getting byte representation of operand in instruction

### ISSUE THREAD

**Issue by bufu1003** [NationalSecurityAgency/ghidra#847]
Currently cycling through operands in instructions using the following code: 

```for index, unit in enumerate(codeunits):
                    prototype = unit.getPrototype()
                    context = unit.getInstructionContext()
                    numOperands = prototype.getNumOperands()
                    for i in range(0,numOperands):
                        operandInt = prototype.getOpType(i,context)
                        if (operandType.isAddress(operandInt)):
                            #TODO 
                            print("[OPERAND BYTE CODE")
```

However, I can't anything in the docs on getting the byte value of an operand within an instruction. I've probed getting operand byte values using the operand's mask, but due to gaps in my own knowledge can't quite figure out how to use masks to get byte code for operands. 

Thank you for the help!

**Comment by dev747368** [comment]
look at ScalarOperandListingHover.getOperand() and how its used to get an idea of how to do this.

Basically, if the OpObject its a Scalar, you can get the numeric value from it.
