### ISSUE TITLE
Plugin Dev: QueryOpinionService and automatic processor selection

### ISSUE THREAD

**Issue by hank** [NationalSecurityAgency/ghidra#860]
I've written a Loader and Analyzer for the ESP8266, based on the Xtensa architecture plugin. The Xtensa plugin is installed and working great, and the Loader will help map things into memory so hopefully XREF starts working. I've run into a snag: I don't understand QueryOpinionService and these primary and secondary keys. I think I have my XML correct, but it refuses to automatically select Xtensa as the language no matter what I do.

https://github.com/hank/ghidra-esp8266/blob/master/GhidraESP8266_2/src/main/java/ghidraesp8266_2/GhidraESP8266_2Loader.java

![image](https://user-images.githubusercontent.com/8534/62182580-13de2c00-b325-11e9-8ae1-3c685e87c654.png)

Please help! Looking forward to using this plugin.

ghidra-xtensa: https://github.com/yath/ghidra-xtensa

**Comment by ryanmkurtz** [comment]
Each processor has an "opinion" file that controls what Loaders are supported under various conditions.  The primary key is typically tied to the Loader's file format's architecture field structure.  Take the PeLoader for example.  The PeLoader's [FileHeader](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#file-headers) structure specifies a [Machine Type](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#machine-types) in the `Machine` field.  In the `x86.opinion` file, there is an entry for the PeLoader (Portable Executable) with a primary key that matches the 32 and 64-bit x86 `Machine Type` values.  The PeLoader's findSupportedLoadSpec() method parses the FileHeader to get the `Machine Type`.  It then passes the primary key to the `QueryOpinionService`, which parses the opinion files for all of the processors, which results in the Language drop-down getting populated with the supported processor/compilers for that processor/loader combo.

So, you will need to map your loader to your processor in the processor's opinion file.  Let me know if something still doesn't make sense...I probably didn't explain it that clearly.

**Comment by ryanmkurtz** [comment]
Also, you don't need to use the `QueryOpinionService` if your loader's supported architecture set is tiny (or exactly 1).  Take a look at the JVM processor:
https://github.com/NationalSecurityAgency/ghidra/blob/c67b9e44bba62e6c49c3785606bba58c6d9f76be/Ghidra/Processors/JVM/src/main/java/ghidra/app/util/opinion/JavaLoader.java#L59-L60
It simply returns a `LoadSpec` that contains one `LanguageCompilerSpecPair`.

**Comment by hank** [comment]
Thanks very much I'll put this to use soon!
