### ISSUE TITLE
Can Ghidra do backward symbolic execution?

### ISSUE THREAD

**Issue by pythonpsycho1337** [NationalSecurityAgency/ghidra#866]
Hi

I am searching for a tool which can do backwards symbolic execution on x86 binaries. More specifically, I would like to give the tool a program state(PC value + registers + memory content) and have it give me a set of inputs to the program that would result in that state. Can Ghidra do this?

**Comment by ryanmkurtz** [comment]
Ghidra does not do this.  Have you looked into [angr](https://docs.angr.io/core-concepts/solver)?
