### ISSUE TITLE
Allow Ghidra Server admins to add users dynamically rather than queuing a command

### ISSUE THREAD

**Issue by Enigmatrix** [NationalSecurityAgency/ghidra#868]
Currently, we have to use `svrAdmin -add $USER` to add a user into the server. However, this command merely queues the action, and the user will only be added when the server runs again (or, if already started, restarted). This is not a good option in a server that is being used 24/7, with new users being added periodically, especially when a user starts a long-running check-in and the server has to restart just to add a user.

The ghidra server should allow adding users dynamically (e.g. exposing [UserManager](https://github.com/NationalSecurityAgency/ghidra/blob/1cae5552f683291fe142a706c2efef91e3249da6/Ghidra/Features/GhidraServer/src/main/java/ghidra/server/UserManager.java) to the client) by server admins.

**Comment by dev747368** [comment]
Unless something is going wrong with your install, new users will be added without restarting the server.
Yes, there is a file queued into a directory, but pretty much any activity on the server will process that queue and cause the user to be added to the system.

**Comment by Enigmatrix** [comment]
Seems like some other error. I will close this isue

**Comment by tt2000** [comment]
@dev747368 Can you elaborate on "any activity"? Because I'd like to trigger such an activity to get my new user as soon as possible. That said, I experience the same problem as @Enigmatrix but on Ghidra 10.0.3.
