### ISSUE TITLE
'Unsort' ability on 'Ghidra Table Headers'

### ISSUE THREAD

**Issue by nithax** [NationalSecurityAgency/ghidra#87]
**Is your feature request related to a problem? Please describe.**
Program speed is significantly slowed down when multiple windows such as "Functions", "Defined Strings" are visible due to them having to constantly sort.

**Describe the solution you'd like**
A simple right-click method with the option to 'Unsort' the entire tableset. This is what IDA does and it is extremely efficient in speeding up actions.

**Comment by Ristovski** [comment]
This is very annoying when patching instructions while having the "Defined Strings" view open.
