### ISSUE TITLE
GhidraScreenShotGenerator class is missing

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#875]
**Describe the bug**
Bunch of tests in the `Tests/IntegrationTests/src/screen` folder derive from the `GhidraScreenShotGenerator` class which is missing, at least I do not know where it is located.

**To Reproduce**
1. run `gradle screenShots`
2. See error

**Comment by adamopolous** [comment]
Hi @kant2002 ,
That class should be available under `Ghidra/Features/Base/src/main/java/help/screenshot`
Do you not see it there?

**Comment by kant2002** [comment]
@adamopolous I do see it now, I somehow miss it. But Idea still does not pickup Base project as dependency. I clearly see 
```
testCompile project(path: ':Base', configuration: 'testArtifacts')
```
in the build.gradle

When I add `println projectPath` before https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Test/IntegrationTest/build.gradle#L17

I receive following output

```
Ghidra/Processors/68000
Ghidra/Processors/8051
Ghidra/Processors/AARCH64
Ghidra/Processors/ARM
Ghidra/Processors/Atmel
Ghidra/Features/Base
Ghidra/Features/BytePatterns
Ghidra/Features/ByteViewer
Ghidra/Processors/Dalvik
Ghidra/Processors/DATA
Ghidra/Framework/DB
Ghidra/Features/DebugUtils
Ghidra/Features/Decompiler
Ghidra/Features/DecompilerDependent
Ghidra/Framework/Demangler
GPL/DMG
Ghidra/Framework/Docking
Ghidra/Features/FileFormats
Ghidra/Framework/FileSystem
Ghidra/Features/FunctionGraph
Ghidra/Features/FunctionGraphDecompilerExtension
Ghidra/Features/FunctionID
Ghidra/Framework/Generic
GhidraBuild/EclipsePlugins/SleighEditor/ghidra.xtext.sleigh
GhidraBuild/EclipsePlugins/SleighEditor/ghidra.xtext.sleigh.ide
GhidraBuild/EclipsePlugins/SleighEditor/ghidra.xtext.sleigh.tests
GhidraBuild/EclipsePlugins/SleighEditor/ghidra.xtext.sleigh.ui
GhidraBuild/EclipsePlugins/SleighEditor/ghidra.xtext.sleigh.ui.tests
GhidraBuild/EclipsePlugins/GhidraDev/GhidraDevPlugin
GhidraDocs
Ghidra/Features/GhidraServer
Ghidra/Features/GnuDemangler
Ghidra/Framework/Graph
Ghidra/Features/GraphFunctionCalls
Ghidra/Framework/Help
Ghidra/Test/IntegrationTest
```

which miss Base project, maybe that's the cause. Not sure.

**Comment by kant2002** [comment]
If you take a look at #876 maybe this will be another symptom. From what I see now, after quick grance, `p.plugins.withType(JavaPlugin)` filter out the Base project and possible other important for that task project.

**Comment by adamopolous** [comment]
Turns out there are a several dependency errors with running the screenShots task so there's some work to do here. But FYI - the screenshot tasks are really only run via Eclipse so it's not a priority for us to get it working via gradle.  I'll take a look though, and see if it's easy to clean up.

**Comment by kant2002** [comment]
ok. make sense. I initially thought that something is missing. but if it is dependencies error, I can play with that too. I really do not want to be anywhere near Eclipse, so I can volunteer to make Gradle work 😄

**Comment by adamopolous** [comment]
It's ok - I've got a working version already.  Thanks for catching this though; it's good to clean this stuff up.
