### ISSUE TITLE
Typo in MIPS processor manual index - mipsMic.idx

### ISSUE THREAD

**Issue by ckuethe** [NationalSecurityAgency/ghidra#88]
**Describe the bug**
The header has "Architecture" spelled incorrectly, and references document `MD00097` while the actual document ID is `MD00087`. I was unable to find any `MD00097`, while `MD00087` is indeed "MIPS® Architecture For Programmers Volume II-A: The MIPS64® Instruction Set Reference Manual" 

**To Reproduce**
1. `head $GHIDRA_DIR/Ghidra/Processors/MIPS/data/manuals/mipsMic.idx`
2. Note the errors in the header

**Expected behavior**

**Environment (please complete the following information):**
- Version ghidra_9.0_PUBLIC_20190228

**Additional context**

Including patch here until such time as source is uploaded.

```
--- Ghidra/Processors/MIPS/data/manuals/mipsMic.idx.orig	2019-03-06 23:21:08.758478594 -0800
+++ Ghidra/Processors/MIPS/data/manuals/mipsMic.idx	2019-03-06 23:21:26.734729754 -0800
@@ -1,4 +1,4 @@
-@MD00087-2B-MIPS64BIS-AFP-06.03.pdf [MIPS Architecutre For Programmers Volume II-A: The MIPS64 Instruction Set Reference Manual, MD00097 6.03, September 4, 2015]
+@MD00087-2B-MIPS64BIS-AFP-06.03.pdf [MIPS Architecture For Programmers Volume II-A: The MIPS64 Instruction Set Reference Manual, MD00087 6.03, September 4, 2015]
 abs.s,41
 abs.d,41
 abs.ps,41
```

**Comment by nneonneo** [comment]
The filename also says MD00087, so it's pretty clear that's the file that was intended.
