### ISSUE TITLE
Please support Haiku OS!

### ISSUE THREAD

**Issue by rjzak** [NationalSecurityAgency/ghidra#883]
**Is your feature request related to a problem? Please describe.**
Not related to a problem/issue with Ghidra.

**Describe the solution you'd like**
I'd like to see support for [Haiku OS](https://www.haiku-os.org/) for Ghidra. Haiku is a fun, Unix-like operating system which is rather lightweight and fast. Haiku has Java support from [OpenJDK](https://openjdk.java.net/projects/haiku-port/) and currently uses gcc-8.3. The dependencies needed for Ghidra are present, or already work.

**Describe alternatives you've considered**
I've attempted to port Ghidra to Haiku myself, and managed to get most of it working on my own. See https://github.com/rjzak/ghidra. It's not perfect though. Ghidra can't parse Haiku's executables, even though they're ELFs (but seems to be able to parse Linux ELFs and PE32 just fine).

**Additional context**
Shouldn't be hard to maintain this port, I've started work on it and am happy to help see it through. Just need a little bit of help.
In case of "Pic or it didn't happen" https://twitter.com/rjzak/status/1158927482273316865/photo/1

**Comment by ryanmkurtz** [comment]
Hello, can you please provide more information on the ELF parsing problem?  Was the binary not recognized as an ELF, or did the ELF loader throw an exception while trying to parse it?

**Comment by rjzak** [comment]
This seems to be resolved with the 9.1-DEV updates. Previously, it seemed that 9.0.3 would try to parse it as an iOS package, then give an error about not being able to read it. I'll go back and screenshot it.

**Comment by ryanmkurtz** [comment]
I'm glad it's working now.  Unfortunately, we will not be able to offer build-related support for Haiku OS at this time.  We've had some recent discussions about this kind of thing in other issues/pull-requests but the general reason is because we don't have the internal resources to properly support (and test) against additional platforms.   Any Ghidra builds for Haiku will have to be maintained by the community.

**Comment by kant2002** [comment]
@rjzak in case you are interesting in limited build-time support, you can go to [my fork](https://github.com/kant2002/ghidra-official) were we can attempt to make build working.
