### ISSUE TITLE
[IDA-XML] Exporter fail on memory references

### ISSUE THREAD

**Issue by DarkaMaul** [NationalSecurityAgency/ghidra#885]
**Describe the bug**
While exporting a binary in IDA as a XML for Ghidra, the exporter fails while exporting a memory reference to a value which is not a pointer.

**To Reproduce**
The following bug is happening with clang-check (but is not related to the binary).

In function ``export_memory_references()`` [Line: 1179, File: idaxml.py],
```python
target = (self.get_data_value(addr) - ri.tdelta + ri.base)
```
However, the computation of target may overflow from 2**64, hence leading to the following error a few lines later  [L1203]:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/ida/ida-7.2/python/idaxml.py", line 1204, in export_memory_reference
    if ida_bytes.is_mapped(target) == False:
  File "/opt/ida/ida-7.2/python/ida_bytes.py", line 405, in is_mapped
    return _ida_bytes.is_mapped(*args)
TypeError: in method 'is_mapped', argument 1 of type 'ea_t'
```

```python
if ida_bytes.is_mapped(target) == False:
```

**Expected behavior**
The exporter would succeeded.

**Attachments**
The version of clang-check used is from llvm-7, without any modifications.
Since the file is large, please find it here: https://we.tl/t-qR6nCkrZku

**Quick reproduction (using clang-check)**
In IDAPython:
```python
import idaxml;
xml_export = idaxml.XmlExporter(1);
xml_export.filename = 'out.xml';
xml_export.xmlfile = xml_export.open_file(xml_export.filename, "w")
xml_export.export_memory_reference(0x2a2de08, 0)
```

**Environment (please complete the following information):**
 - OS: Debian Testing
 - Java Version: Not related
 - Ghidra Version: 9.0

**Additional context**
IDA Version 7.2

**Comment by ryanmkurtz** [comment]
Looks very similar to #213.

**Comment by ryanmkurtz** [comment]
@DarkaMaul, if you are in a position to easily test this, can you replace the line you mentioned with the following line to see if this will fix it?

`target = (self.get_data_value(addr) - ri.tdelta + ri.base) & ((1 << 64) - 1)`

**Comment by DarkaMaul** [comment]
> @DarkaMaul, if you are in a position to easily test this, can you replace the line you mentioned with the following line to see if this will fix it?
> 
> `target = (self.get_data_value(addr) - ri.tdelta + ri.base) & ((1 << 64) - 1)`

This does work as a fix (it's the one I did myself) however, I'm unsure of the meaning of it.

If the value of ``target`` is more than 2**64, it means that ``get_data_value`` did not return a pointer so it should not be written in the export file.

In my opinion (as far as I understand), a better fix would be :
```python

        if target >= self.max_ea or ida_bytes.is_mapped(target) == False:
            return
```

**Comment by ryanmkurtz** [comment]
In #213, the memory reference was actually intended to be a negative number.  Is that the case for you too?

**Comment by ryanmkurtz** [comment]
I'll just go ahead with the proposed change.
