### ISSUE TITLE
Inline temporary local variable

### ISSUE THREAD

**Issue by sollyucko** [NationalSecurityAgency/ghidra#886]
**Is your feature request related to a problem? Please describe.**
Frequently, a variable is created that is only read right after assignment.

**Describe the solution you'd like**
It would be helpful if Ghidra would automatically inline these kinds of assignments, or at least allow it to be done manually.

**Describe alternatives you've considered**
- Renaming the variable to `temp` or something similar: only renames one instance, and does not allow them to have the same name, besides the initially assigned one. This also indicates that Ghidra is capable of the necessary flow-control analysis.

**Additional context**
This issue is pretty much the same as <https://github.com/NationalSecurityAgency/ghidra/issues/747>.

The executable I'm currently working on is available from <https://www.pwnadventure.com/>.

Before rename:
![Screenshot](https://user-images.githubusercontent.com/15565481/62648003-d75f9100-b91f-11e9-929a-3e02a993d57f.png)

After rename:
![Screenshot](https://user-images.githubusercontent.com/15565481/62648056-fb22d700-b91f-11e9-9643-169d770d0c9d.png)

**Comment by mumbel** [comment]
if you know its a dup, why clutter the issues? just add to that issue
