### ISSUE TITLE
Does anyone have an example of using ctypes with Ghidra?

### ISSUE THREAD

**Issue by kshomper** [NationalSecurityAgency/ghidra#887]
I am writing a python script that depends on the module ctypes, which in turn depends on the native _ctypes module from CPython. I've tried to use the [JyNI project](https://awesomeopensource.com/project/Stewori/JyNI) to access _ctypes, but keep failing with a ClassNotFound error from the Jython installer during ghidra initialization.

Has anyone had success in accessing CPython capabilities such as ctypes through the Jython environment?

**Comment by ryanmkurtz** [comment]
You might want to check out the [ghidra-bridge](https://pypi.org/project/ghidra-bridge/) project.
