### ISSUE TITLE
Loader doesn't recognise 64 bit XCOFF binaries for POWER9.

### ISSUE THREAD

**Issue by friedphish** [NationalSecurityAgency/ghidra#891]
**Issue Description**
When attempting to open an XCOFF-64 binary (compiled for the Power9 architecture, on AIX, using IBM's compiler suite), GHIDRA does not recognise the binary at all and I cannot seem to find a "sane" way to load the binary.

**To Reproduce**
Try open the linked file in GHIDRA, it doesn't seem to recognise the format at all. This is just one random binary that was causing issues.
Link to file: https://ufile.io/n4u42uom

(Apologies for the crap filehost link, I couldn't find a way to attach the binary - I'll upload elsewhere later).

**Expected Behaviour**
GHIDRA would handle this as it has good PPC support and an XCOFF loader.

**Comment by ryanmkurtz** [comment]
I don't think we actually have an XCOFF loader, despite having some of the file format implemented.  Duplicate of #385.

**Comment by ryanmkurtz** [comment]
I am going to close this as a duplicate.  If you want to carry on the conversation, let's use issue #385.  Thanks!
