### ISSUE TITLE
Build for Windows does not working in CI

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#898]
**Describe the bug**
I attempt to make Ghidra build in CI environment. I download bison and flex, and that part seems to be working, but when building native projects, VS configuration does not picked up and `MSVC_SDK_VERSION` and `MSVC_TOOLS_VERSION` does not setup properly.

The issue locates somewhere here: https://github.com/NationalSecurityAgency/ghidra/blob/master/GPL/nativeBuildProperties.gradle#L36-L50

where you build following command line 
```
cmd /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 > nul && cmd /c echo %WINDOWSSDKVERSION%
```
to get environment variable %WINDOWSSDKVERSION%

console displays following
```
Visual Studio Path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise 
Visual Studio SDK Version: 
Visual Studio VCTools Version:
```

When I make same command in the CMD on my PC it does not work as expected, but when I run `gradle build` then everything working as needed and environment variables propagated.

I try to understand how it is executed by gradle, and seems to be that it is working due to some kind of gradle magic.

I was try different way to invoke commands, but I'm out of ideas for now.

**To Reproduce**
Not sure
1. Go to https://codevision.visualstudio.com/Ghidra/_build/results?buildId=10842&view=logs&j=9823409e-c361-5496-c4fe-fac696441272
2. See error

**Comment by ryanmkurtz** [comment]
Any luck resolving this?  I'm not sure how much help we can be with debugging this specific environment.

**Comment by kant2002** [comment]
No, but given that you cannot help me, I will put more time into that. Would like to create small change, for you to consider. I think ways to make it either:
- Make temporary bat file and execute it. (Practical, but I don't like that idea)
- Understand how Gradle parse command lines and why difference in behavior from CMD and inside Gradle. (Slightly more complicate to understand for me, but likely better for your team)

Would like to understand your position on that, that's why I post issue in first place.

**Comment by ryanmkurtz** [comment]
Did you add the `echo %WINDOWSSDKVERSION%`?  That doesn't seem to match what's in master.

**Comment by kant2002** [comment]
Current code does not work for me in MS hosted Azure DevOps environment. 

The only difference in `GPL/nativeBuildProperties.gradle` is the code which detect location for VS version, but after that invocation of vcvarsall.bat the same as official Ghidra version. At least when I file the issue, now I have slightly more changes, but mostly add for debugging.

I actually manage to make it work, so command now following:

```
cmd /v /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 > nul && cmd /c echo !WINDOWSSDKVERSION!"
```

as you can see `/v` and putting additional quotes around command line.

Changes captured in #938 make build pass for me.
