### ISSUE TITLE
m68k/coldfire disassembles immediate -1 in mov3q instruction as 0

### ISSUE THREAD

**Issue by zhuyifei1999** [NationalSecurityAgency/ghidra#905]
**Describe the bug**
According to [NXP ColdFire Programmer's Reference Manual](https://www.nxp.com/docs/en/reference-manual/CFPRM.pdf), page 122, the data value 0 in the immediate data field represent -1 instead of 0. Ghidra does not implement this edge case.

**To Reproduce**
1. Create a file with contents as `\xa1\x50`, eg. by `$ echo -ne '\xa1\x50' > test`
2. Open the file in ghidra, format: Raw binary, language: 68000/Coldfire
3. Disassemble the code in CodeBrowser
4. See it is `00000000 a1 50           mov3q      #0x0,(A0)`. The decompiled code 
also show `*in_A0 = 0;`
5. Compare it with binutils:
```
$ objdump -b binary -m m68k -D test

test:     file format binary


Disassembly of section .data:

00000000 <.data>:
   0:	a150           	mov3ql #-1,%a0@
```

**Expected behavior**
The disassembly should be `00000000 a1 50           mov3q      #-1,(A0)` or `00000000 a1 50           mov3q      #0xffffffff,(A0)`. The decompiled code should be `*in_A0 = -1;` or `*in_A0 = 0xffffffff;`

**Environment (please complete the following information):**
 - OS: Gentoo Linux
 - Java Version: 11.0.4
 - Ghidra Version: 9.0.x-DEV

**Additional context**
As far as I am aware this instruction is not part of the legacy m68k architecture (not part of [Motorola M68000 Family Programmer's Reference Manual](https://www.nxp.com/files-static/archives/doc/ref_manual/M68000PRM.pdf)) so I am unaware of where this 'edge case' does not apply.

Likely related to above, Capstone cannot disassemble this instruction. IDA version 6.95.160808 (32-bit) disassembles this instruction correctly.

**Comment by mumbel** [comment]
this might be a fix in Ghidra/Processors/68000/data/languages/68000.sinc
```
-d3bits: d911                   is d911                                         { export *[const]:1 d911; }
+attach values d911 [ -1 1 2 3 4 5 6 7 ];
 :mvs.b: eab, reg9dn            is (op=0x7 & op68=4 & reg9dn )... &eab          { reg9dn = sext(eab); }
 :mvs.w: eaw, reg9dn            is (op=0x7 & op68=5 & reg9dn )... &eaw          { reg9dn = sext(eaw); }
 :mvz.b: eab, reg9dn            is (op=0x7 & op68=6 & reg9dn )... &eab          { reg9dn = zext(eab); }
 :mvz.w: eaw, reg9dn            is (op=0x7 & op68=7 & reg9dn )... &eaw          { reg9dn = zext(eaw); }
-:mov3q "#"^d3bits, eal         is (op=0xa & op68=5 & d3bits )... &eal          { eal = zext(d3bits); }
+:mov3q "#"^d911, eal           is (op=0xa & op68=5 & d911 )... &eal            { eal = d911; }
```

**Comment by ryanmkurtz** [comment]
Fixed [here](https://github.com/NationalSecurityAgency/ghidra/commit/59aa00dfb7a2930bdb30c3b40ff4c92eb12b8f45).
