### ISSUE TITLE
Case insensitive importing of referenced PE libraries

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#906]
9.0.4

A PE will look for `KERNEL32.DLL` for example.  When previously importing kernel32.dll, the default name is `kernel32.dll`.  When Ghidra searches through the list of imported files for this new PE being imported the result is `not found`.  Could PE imports be case insensitive in this search?

Very trivial to add after the fact manually, or to just rename from `kernel32.dll` to `KERNEL32.DLL` so there are work arounds (is the import always uppercase in the PE?).

The relevant code that prints `not found` kind of looked like it was indifferent of the executable format so there might be issues depending on the targets deciding case insensitive or not.

**Comment by ryanmkurtz** [comment]
I think that was the intent for the `PeLoader`:
https://github.com/NationalSecurityAgency/ghidra/blob/8caa0b0f4c55bb5862f11b3b7e911cf79b826a3d/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/PeLoader.java#L194-L197
I'll have to debug it to see why that's not working.

**Comment by ryanmkurtz** [comment]
The `get` here is case sensitive...that's the problem.  
https://github.com/NationalSecurityAgency/ghidra/blob/8caa0b0f4c55bb5862f11b3b7e911cf79b826a3d/Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/AbstractLibrarySupportLoader.java#L459
We'll have to some up with something more clever.

**Comment by mumbel** [comment]
Thanks for verifying this.  I wasn't sure how/what the domain objects could know/do/access.
