### ISSUE TITLE
Question regarding naming variable from DWARF DIE

### ISSUE THREAD

**Issue by andreyliu** [NationalSecurityAgency/ghidra#913]
I am working on a project where I am interested in comparing the names of variables in the decompiled code with and without using DWARF DIE info. I would like to know where the variable information is stored for a function and how that information changes when using DWARF DIE, specifically when the number of local variables differs when decompiling using DWARF info.

**Comment by dev747368** [comment]
First, don't expect too much from the DWARF local variable import.  Local variables move around alot and our import only attempts to pull in basic info.  The Ghidra local var instances created during DWARF import won't always match up with decompiler meta-data.
