### ISSUE TITLE
Support Visual Studio 2019

### ISSUE THREAD

**Issue by mendax47** [NationalSecurityAgency/ghidra#918]
**Is your feature request related to a problem? Please describe.**
Can't Build With Visual Studio 2019

**Describe the solution you'd like**
Abut To Build With Visual Studio 2019

**Comment by kant2002** [comment]
This is out of scope for Ghidra team, See https://github.com/NationalSecurityAgency/ghidra/pull/730 for discussion. If you want to have VS2019 support, you can try [my fork](https://github.com/kant2002/ghidra-official) where I concentrate mostly on small things which cannot be supported by official fork. VS2019 is included.

**Comment by mendax47** [comment]
If it's impossible then try to use a build server so that everyone can use the master build...
