### ISSUE TITLE
Iterate over basic block in Java or Python scripts

### ISSUE THREAD

**Issue by occia** [NationalSecurityAgency/ghidra#92]
Is there a way to iterate over basic block? I found the Function level and Instruction Level API, but no way to manipulate the Basic Block. Thank you.

**Comment by dragonmacher** [comment]
You can look at the SubsToFuncsScript that is included in the distribution.   This accessible from the Script Manager.  This will show the basics of walking the program's code blocks, as well as the interface of the code block.   From that script:

		BlockModelService blockModelService = state.getTool().getService(BlockModelService.class);
		CodeBlockModel cbm = blockModelService.getActiveSubroutineModel();
		AddressSetView addrset =
			currentSelection == null ? (AddressSetView) currentProgram.getMemory()
					: currentSelection;
		CodeBlockIterator cbIter = cbm.getCodeBlocksContaining(addrset, monitor);
		while (cbIter.hasNext()) {
			CodeBlock block = cbIter.next();
			...
			...
		}
