### ISSUE TITLE
C-Parser: pack pragmas not complete

### ISSUE THREAD

**Issue by InBetweenNames** [NationalSecurityAgency/ghidra#927]
**Describe the bug**
The C parser errors out on header files using the following type of pack pragmas:

~~~
 #pragma pack(push)
 #pragma pack(n)
~~~

This is common in older Windows headers.

**To Reproduce**
Attempt to parse any header file using the above pragmas.  Consider `pshpack8.h` in Visual Studio 6.0 for example.

**Expected behavior**
The packing pragmas in the example should be handled the same as the following, which is a syntax that does work:

~~~
#pragma pack(push, n)
~~~

**Environment (please complete the following information):**
 - OS: Windows 10 1903
 - Java Version: 12
 - Ghidra Version: 9.0.4

**Additional context**
Pull Request #926 can be amended to remove `-Dpack(push)` from `VisualStudio6.prf` if this is fixed.

I'm willing to submit a patch for this if needed.  Thank you!

**Comment by emteere** [comment]
This issue was addressed in 10.1.x.
pack and the mechanism windows header files use to set the pack value with multiple includes of pshpack8.h is supported.
