### ISSUE TITLE
state.getTool() failing in headless mode only

### ISSUE THREAD

**Issue by narmour** [NationalSecurityAgency/ghidra#934]
Hi,

I have a jython script that loads some datatypes via a .gdt file. I'm using  

`service = state.getTool().getService(DataTypeManagerService)
  service.openArchive(loadDataFile("name"),False)
`
to accomplish this.

This works perfectly fine if I run the script from the GUI.

However in headless mode, state.getTool() returns None, causing the above code to fail.
` service = state.getTool().getService(DataTypeManagerService)
AttributeError: 'NoneType' object has no attribute 'getService'`

`state:  ghidra.app.script.GhidraState@5fb52c68`
Is there a headless flag I am missing that is needed to get this to work? Or is getTool() not allowed in headless mode?

Here is my headless cmd line:

`./analyzeHeadless /path/to/proj projname -import /path/to/binary -scriptPath /path/to/scripts -postScript myPythonScript.py`

Thanks.

**Comment by dragonmacher** [comment]
There is no tool in headless mode.

**Comment by narmour** [comment]
Are you familiar with a headless-friendly way of getting to the DataTypeManagerService?

**Comment by dragonmacher** [comment]
Try this:

```
AutoAnalysisManager aam = AutoAnalysisManager.getAnalysisManager(currentProgram);
DataTypeManagerService dtm = aam.getDataTypeManagerService();
```

**Comment by narmour** [comment]
Your first suggestion worked perfectly... Thanks!!

I noticed that openArchive also doesn't play nicely with headless.. openDataTypeArchive() works though... 

Appreciate the speedy response time
