### ISSUE TITLE
Application Properties Non-existent?

### ISSUE THREAD

**Issue by jpc0016** [NationalSecurityAgency/ghidra#940]
Good afternoon,

While attempting to install Ghidra in a Kali VM (GNOME 3.30.2, 64-bit, 2019), I ran into errors while linking to JDK.  Ghidra fails to start because it cannot link to the JDK folder:

`Application properties file does not exist: /root/Desktop/ghidra_9.0.4_PUBLIC_20190516/ghidra_9.0.4/Ghidra/application.properties

Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section.`

  I followed the Ghidra Installation Guide and added the path to ~/.bashrc:

`export PATH=/root/Downloads/jdk-11.0.4+11/bin:$PATH`

  I doublechecked my Ubuntu 19 machine with Ghidra 9.0.4 installed and confirmed the path format.  I'm at a loss as to what this could be because I keep changing the ~/.bashrc line with no change.  Help is appreciated!

**Comment by ryanmkurtz** [comment]
Is

`/root/Desktop/ghidra_9.0.4_PUBLIC_20190516/ghidra_9.0.4/Ghidra/application.properties`

actually there?  That's the file that defines what version of Java Ghidra should use, so if it can't find or parse it, it won't be able to find Java.

**Comment by jpc0016** [comment]
Going to check when I get home.  Thanks!

**Comment by jpc0016** [comment]
The output of echo $(java -version) was:

```
openjdk version "11.0.4" 2019-07-19
openJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
openJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

I could not find application.properties in the /Ghidra/ folder.  Thanks Ryan!

**Comment by ryanmkurtz** [comment]
Ok, I would download another copy of Ghidra and do a fresh install.
