### ISSUE TITLE
Where ghidra?

### ISSUE THREAD

**Issue by KORuL** [NationalSecurityAgency/ghidra#95]
where can I download ghidra?

**Comment by AlexGustafsson** [comment]
The first Google result takes you to this site: https://www.nsa.gov/resources/everyone/ghidra/, which in turn takes you to this site: https://ghidra-sre.org where you can download Ghidra.

I assume GitHub issues are for bugs and similar issues. Please read the issue template and contribution guide.

**Comment by KORuL** [comment]
Sorry, just from my country without a VPN site did not open)

**Comment by KORuL** [comment]
I found a way, thanks
