### ISSUE TITLE
https://ghidra-sre.org/ is not accesible

### ISSUE THREAD

**Issue by sharpblade4** [NationalSecurityAgency/ghidra#953]
**Describe the bug**
I want to try this platform without building it from source myself. I understood that the official version is published throught the site https://ghidra-sre.org/ . I tried reaching it from different LANs across my country in the past week but I couldn't I get blocked with the message: 
403 ERROR
The request could not be satisfied.
Request blocked. 
Generated by cloudfront (CloudFront)
Request ID: m7jI2GVH3o04oSD-th7IyttSWMc_0BLV9cr_-4bDag20WiIneep8SA==

**To Reproduce**
1. Go to https://ghidra-sre.org/

**Expected behavior**
The site will appear

**Environment (please complete the following information):**
 - OS: Windows 10, Linux debian jessie, Android 9
 - Web browser: chrome 76.0.3809.132

**Comment by kant2002** [comment]
@sharpblade4  See #32 for discussion.

**Comment by sharpblade4** [comment]
@kant2002  thanks. I'll close this duplicate. Weird that cloudfront blocks valid IPs.
