### ISSUE TITLE
Copying from Memory Map produces table with first row as header

### ISSUE THREAD

**Issue by carlreinke** [NationalSecurityAgency/ghidra#957]
**Describe the bug**
When copying from Memory Map, the text representation of the table contains the first row in the header.

**To Reproduce**
1. Open "Memory Map".
1. Select some rows.
1. Right click > Copy > Copy
1. Paste and get something like:
```
1000 | 1000:0000 | 1000:fd0f | 0xfd10 | true | true | true | false | Default | true | mz |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1fd1 | 1fd1:0000 | 1fd1:fc7f | 0xfc80 | true | true | true | false | Default | true |   |  
2f99 | 2f99:0000 | 2f99:94af | 0x94b0 | true | true | true | false | Default | true |   |  
```

**Expected behavior**
Header contains actual column names rather than first row.

**Environment:**
 - OS: Windows 10
 - Java Version: 12.0.2
 - Ghidra Version: 9.0.4

**Comment by ryanmkurtz** [comment]
Hmmm, i cannot reproduce this.

**Comment by carlreinke** [comment]
Okay, actually it's just GitHub formatting the table when I paste it -- not Ghidra's fault.
