### ISSUE TITLE
Loader Module for N64 roms

### ISSUE THREAD

**Issue by zeroKilo** [NationalSecurityAgency/ghidra#959]
hi,
I wrote a loader module for N64 roms here https://github.com/zeroKilo/N64LoaderWV maybe you want to add it to your loaders, as ghidra has a mips decompiler. thanks for your time
greetz

**Comment by ryanmkurtz** [comment]
Great work on writing a custom loader!  Maintaining the loader yourself as a 3rd party extension is the way to go for this one though.
