### ISSUE TITLE
Creating function reference in disasm doesn't create one for decompiler

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#962]
I have a call to indirect location:
```
// dos.library->Open( name/d1, accessMode/d2 )
0021f7ac  4e ae ff e2            jsr                (-0x1e,A6)
```
I know where it will jump, but adding references (both at jsr and at A6) to that address doesn't work for decompiler.

![изображение](https://user-images.githubusercontent.com/7189309/64077327-3a9ed200-ccd8-11e9-82e5-19bad2b814ff.png)

There is no valid location here:
![изображение](https://user-images.githubusercontent.com/7189309/64077333-4b4f4800-ccd8-11e9-89fe-8f9cfcd59ddf.png)

**Comment by ghidra1** [comment]
Ghidra 9.1 will include additional CALL/JUMP reference overrides which may address your use case.  I believe this has been merged into the master branch (see GT-2885 commits).  You will need to use one of the OVERRIDE reference types.

**Comment by lab313ru** [comment]
It doesn't work.

![изображение](https://user-images.githubusercontent.com/7189309/64480063-7b5f8500-d1c9-11e9-8cc8-39975b2bca0d.png)

**Comment by lab313ru** [comment]
It works this way:

![изображение](https://user-images.githubusercontent.com/7189309/64480106-53bcec80-d1ca-11e9-9b1f-7f4eac3bfe7a.png)
