### ISSUE TITLE
Identical entities: ParameterDefinition and ParameterImpl

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#963]
But both have different usages:
`ParameterImpl` can be used for function parameters (`func.updateFunction`), the first one - only for `FunctionDefinitionDataType`.

Merging them will allow to use custom storage arguments in function definitions too.

**Comment by ghidra1** [comment]
At this point in time we do not support varnode storage concepts for FunctionDefinitions and the associated ParameterDefinition.  We are currently examining improvements which may facilitate such a concept but a near-term change is unlikely.
