### ISSUE TITLE
Method equals() in Varnode.java is implemented incorrectly.

### ISSUE THREAD

**Issue by plowsec** [NationalSecurityAgency/ghidra#97]
**Describe the bug**
The method equals(...) in Varnode.java is implemented incorrectly. As a result, standard collections such as (Hash)Map will allow duplicate keys or fail completely.

**To Reproduce**
1. Store several instances of Varnode in a HashMap, notice that duplicate keys appear.
2. Open ghidra_9.0_PUBLIC_20190228/ghidra_src/SoftwareModeling-src/ghidra/program/model/pcode/Varnode.java in an editor, notice that the equals' implementation is wrong (== instead of equals on spaceID comparison).

**Expected behavior**
Equals MUST be implemented correctly to respect the preconditions of most Java standard collections.

**Solution**
Replace the "==" with equals, as follows:
```
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if (o == this)
			return true;
		if (!(o instanceof Varnode))
			return false;

		Varnode vn = (Varnode) o;
		if (!vn.isFree())
			return false;

		return (this.offset == vn.getOffset() && this.size == vn.getSize() && this.spaceID.equals(vn.getSpace()));
	}

**Comment by dragonmacher** [comment]
I believe there is some confusion here.   The 'spaceID' field is a Java int.   Thus, the '==' is correct here.

**Comment by plowsec** [comment]
Oops forgive me, indeed I mixed up things a little with the version if fixed on my end. Still, your "equals"  _is_ incorrect (have you even tested it?). For two separate instances, describing the same information, you will have an equals that returns false where it should return true.

I believe you should compare the field "address" as well. The same stands for the hashCode method. In your current situation, two separate instances of Varnode (but with the same field values) will have a different hashcode, thus HashMap will not be able to check keys for equality (both equals and hashCode are required to be correct).

Here is a more correct implementation:
```  
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Varnode tVarnode = (Varnode) o;
        return size == tVarnode.size &&
                spaceID == tVarnode.spaceID &&
                offset == tVarnode.offset &&
                Objects.equals(address, tVarnode.address);
    }

    @Override
    public int hashCode() {
        return Objects.hash(address, size, spaceID, offset);
    }
```

I fear that you won't bother to check, so here it is (with your bug):
```
     if(!varnode.equals(node))   {
            println(":o ");
            println(node.toString());
            println(varnode.toString());
            println("offset = " + node.getOffset() + " size = " + node.getSize() + " size = " + node.getSpace());
            println("offset = " + varnode.getOffset() + " size = " + varnode.getSize() + " size = " + varnode.getSpace());
            println(node.hashCode() + " " + varnode.hashCode());
            println(String.valueOf(node.equals(varnode)));
        }
```

And then this dummy test outputs:
```
Test.java> :o 
Test.java> (register, 0x8, 8)
Test.java> (register, 0x8, 8)
Test.java> offset = 8 size = 8 size = 420
Test.java> offset = 8 size = 8 size = 420
Test.java> 1721 417
Test.java> false
```

As you can see, the hash codes are different. This can be the wanted behavior on your side, for instance it is the case for the mutable StringBuilder in the standard library. But I would consider it bad design in the case of Varnode.

**Comment by dragonmacher** [comment]
You are correct.   This method violates the spirit of the Object.equals() method, specifically, 'generally...equal objects must have equal hash codes.'

Thank you for the extra effort above.
