### ISSUE TITLE
Data Type Chooser Dialog size checking bug on 16-bit targets

### ISSUE THREAD

**Issue by Arcnor** [NationalSecurityAgency/ghidra#970]
**Describe the bug**
When you use the Data Type Chooser Dialog (default hotkey "T") to assign a type to a region of data, it checks that you're not going to clobber any existing declared type beforehand, which is good.

However, on a 16-bit target (like old MS-DOS executables) the size calculation is incorrect when using pointers/arrays and similar structures and it will do the check as if those pointers are 4 bytes long, while they are really 2 bytes long.

**To Reproduce**
On a 16 bit target, try to create a pointer on a location which is only 2 bytes long. Check screenshot

**Screenshots**
![GhidraDataTypeBug](https://user-images.githubusercontent.com/28616/64231230-e87fcb80-cee6-11e9-9b20-f44c26507df9.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Java Version: 11.0
 - Ghidra Version: 9.0.4

**Comment by Arcnor** [comment]
Also, interestingly enough, pressing Y (to apply the last type I used, and having such type being a pointer) will work

**Comment by dev747368** [comment]
@Arcnor, I think this may have been addressed in commit 120d4241e5e2aaecefa81989633768f9a8824a8c (https://github.com/NationalSecurityAgency/ghidra/commit/120d4241e5e2aaecefa81989633768f9a8824a8c), which was committed just a few days ago.

Are you able to build and try it out?

**Comment by Arcnor** [comment]
Sure, I'll give it a go and report back. Thanks!

**Comment by Arcnor** [comment]
Looks like it's fixed on master, yeah, thanks!

**Comment by Arcnor** [comment]
@dev747368 it looks like this is happening again on master, could it be?
