### ISSUE TITLE
Unexpected ZEXT32 on 16-bit targets

### ISSUE THREAD

**Issue by Arcnor** [NationalSecurityAgency/ghidra#971]
**Describe the bug**
When decompiling a function on a 16 bit target, I'm encountering a lot of `ZEXT32` on the decompiler when using structure fields, which I assume is `zero extend to 32 bits`. However, as mentioned, I'm on a 16 bit target, so such extension should not take place.

**To Reproduce**
Create a structure and assign it to some field that is used in the code. When the field is dereferenced, you'll see the `ZEXT32`.

**Screenshots**
![GhidraZEXT32Bug](https://user-images.githubusercontent.com/28616/64233614-7e6a2500-ceec-11e9-9680-f74183e20054.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Java Version: 11.0
 - Ghidra Version: 9.0.4

**Comment by Arcnor** [comment]
Ok, I don't think it's happening when dereferencing a structure field, but just any dereference, it's probably just coincidence.

**Comment by Arcnor** [comment]
I've found MANY (as in more than 10) PRs opened by @GregoryMorse that might fix this and other problems I've reported, but for some reason haven't been merged yet?

**Comment by GregoryMorse** [comment]
Fixed by #842 - I am guessing since these PRs involve the core decompiler they are requiring special review.  I am also hoping for some feedback and discussion or merging of these PRs soon :)>

**Comment by caheckman** [comment]
The generation of bad ZEXT32 operations should be resolved in 9.1
