### ISSUE TITLE
sleighCompile out of heap space

### ISSUE THREAD

**Issue by rolandh** [NationalSecurityAgency/ghidra#972]
**Describe the bug**
Trying to build the latest ghidra commit I get a crash during the build process. Everything builds fine except for java docs.

> Task :6502:sleighCompile FAILED
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

FAILURE: Build failed with an exception.

Execution failed for task ':6502:sleighCompile'.
> Process 'command 'C:\Program Files (x86)\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin\java.exe'' finished with non-zero exit value 1

Crashed during > Task :createJavadocs

**To Reproduce**
gradle buildGhidra

**Expected behavior**
Doesn't crash during > Task :createJavadocs

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Java Version: 11.0.4.11

gradle -v
Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (AdoptOpenJDK 11.0.4+11)
OS:           Windows 10 10.0 x86

Is there any way to bypass building the java docs?

**Comment by ryanmkurtz** [comment]
`gradle buildGhidra -x zipJavadocs`

**Comment by ryanmkurtz** [comment]
How much memory does your build system have?

**Comment by rolandh** [comment]
32gb of RAM and a 12 core threadripper. Unsure why it is getting out of memory.

I will build with the flag above.

**Comment by rolandh** [comment]
Update: Build still fails with -x zipJavadocs

```
..\ghidra>gradle buildGhidra -x zipJavadocs

> Task :6502:sleighCompile
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

> Task :6502:sleighCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':6502:sleighCompile'.
> Process 'command 'C:\Program Files (x86)\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin\java.exe'' finished with non-zero exit value 1
```

**Comment by ryanmkurtz** [comment]
What build tools are x86 rather than x64?

What happens if you just do:

`gradle sleighCompile`

**Comment by ryanmkurtz** [comment]
Any updates?

**Comment by rolandh** [comment]
```
\ghidra>gradle sleighCompile
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :6502:sleighCompile FAILED
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':6502:sleighCompile'.
> Process 'command 'C:\Program Files (x86)\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
23 actionable tasks: 1 executed, 22 up-to-date
```

Any ideas how I can get past this?

**Comment by ryanmkurtz** [comment]
I'd glad you got it sorted out and are liking Ghidra.  I'm going to look into improving some of the roadblocks you ran into here, like having gradle print out a useful message if it's trying to use a 32-bit Java.
