### ISSUE TITLE
Failures occuer after running tests

### ISSUE THREAD

**Issue by EmpRamses** [NationalSecurityAgency/ghidra#974]
I have downloaded the latest code for now(2019.9.4 7:34 UTC)
Then I build  it and run tests as the developer's guide.
After that, nearly 300 failures occur.
Is that mean something I do wrong? Or these failures are not important.

ps. I've build a repo to display these failures as the following url.
https://empramses.github.io/GhidraReports/

**Comment by ryanmkurtz** [comment]
Our testing framework is going through a lot of changes right now, so it's not surprising we are seeing a lot of failures.  They will most likely be addressed today.  Keep an eye out for new commits that mention tests being fixed.

**Comment by EmpRamses** [comment]
@ryanmkurtz Thanks for your reply. I'll be watching on new releases of Ghidra.
