### ISSUE TITLE
68000: Multiple registers returning

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#984]
For example, I have a function that reads `(A0)` to `D0` which is return result, and also changes `A0`, because of operation `(A0)+` or `-(A0)`, or `adda.l A0, #4`.

Is it possible to specify that some function changes multiple registers?

**Comment by Arcnor** [comment]
You can check "Use Custom Storage" when editing a function, then double click on the Storage cell  related to the return (it will be `D0:4` for example). You can then add another register there, or change the return value in any way.

**Comment by lab313ru** [comment]
But it does require special returning type for that. For example I want to 
return one word register and one dword. 6 bytes. What type should I use?

**Comment by Arcnor** [comment]
Well, you can create a struct with two fields and try returning that, not sure if it will work but it might.

Otherwise, I'm not really sure, maybe somebody has a better answer 🙂

**Comment by lab313ru** [comment]
Seems that you're right. It is possible to create a structure, which will store all registers, and then set it as the return type, with specifying which registers it will store.

**Comment by Arcnor** [comment]
Glad it worked!
