### ISSUE TITLE
Answers to Advanced Development Class labs 

### ISSUE THREAD

**Issue by tneale-gt** [NationalSecurityAgency/ghidra#987]
I'm particularly interested in the labs where a plugin is developed (Labs 6 through 9) and labs 11 through 13. Are there any example answers to these labs?

**Comment by ryanmkurtz** [comment]
Nope, we don't have answers to those.  If something in particular doesn't make sense feel free to ask though...I'm sure we can help.

**Comment by ryanmkurtz** [comment]
I'm going to close this ticket.  Please create new issues for specific questions you might have.
