### ISSUE TITLE
Updated Graph View (Nested Code Layout)Is Buggy

### ISSUE THREAD

**Issue by ebfe2326** [NationalSecurityAgency/ghidra#994]
**Describe the bug**
A new feature was added to the development version of Ghidra under the Tool Options / Function Graph / Nested Code Layout to "Route Edges Around Vertices"  In general, the view is much better than the previous, but it is still fairly buggy.  Maybe 20% of the edges don't get routed around the code blocks and still go through the code blocks.  Sometimes they go straight through the middle, sometimes just through the edges.  Additionally, if you don't use the default code block layout, the graphing algorithm seems to get very buggy.  With the default field sizes, the graphing algorithm is maybe making 20% mistakes, but the field size for the instruction operands is too small to even see the operand in the graph view.  When I increase the size of the fields in the graph view so that I can view the entire instruction, operand, and comment, the graphing algorithm becomes much more buggy and is failing maybe 40% of the time.  With the increased field sizes, you also get many more overlapping edges instead of having them distinct.  Once the edges overlap, it because very difficult to read and determine where the edge starts or ends. 

In either case, if the new features worked consistently, it would be enormously helpful and close to using other tools such as Ida Pro.  There are many situations where it is desirable or necessary to use the graph view over the decompiler.  In those situations of using the graph view, the portions where the edges go straight through code blocks makes it almost unusable because it's nearly impossible to follow where the control flow logic.  If this feature could be fixed to work consistently to the same accuracy as IdaPro, binary ninja, or radare2, it would make Ghidra a very attractive alternative.
I put a few screenshots below for examples with captions for comments.

Figure 1 shows several edges still going through the code blocks, though near the edge instead of straight through the middle.  This tool is using the default field sizes.
![image](https://user-images.githubusercontent.com/44279601/64724899-602e9700-d4a1-11e9-8606-a9c2fe0f3b7b.png)

Figure 2 shows an example where the edge is still going straight through the middle of a code block.  This tool is using the default field sizes.
![image](https://user-images.githubusercontent.com/44279601/64725055-be5b7a00-d4a1-11e9-99b8-dec903badbac.png)

Figure 3 shows the same image as Figure 2 except for the default field sizes are not used.  In this case, I expanded the fields so that I could see the entire instruction, operands, and comments.  In this case, you can see the graphing algorithm has a major problem with the new field sizes.  Note that instead of the edges only going through the middle of 1 block, the edges go through 3 blocks and there are several overlapping edges that are indistinguishable.
![image](https://user-images.githubusercontent.com/44279601/64726206-21e6a700-d4a4-11e9-8477-c55f0fcb26a3.png)

**To Reproduce**
Open any moderatly complex malware file

**Expected behavior**
Ideally, if the edges can be routed around all code blocks so they do not go  through any existing code block regardless of the code block field sizes used.  It would also be very helpful to have the edges not overlap because it because extremely difficult to determine where the edge goes if you have overlapping lines.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: openJDK 12
 - Ghidra Version: 9.1 (development built off of github page to test out new feature)

**Comment by dragonmacher** [comment]
The images above are helpful to show the issues you have found.   We should be able to fix most of these pretty easily.

**Comment by dragonmacher** [comment]
One thing you can try is to disable the 'Use Condensed Layout' option, which is enable by default.   This will fix some of the issues with edges flowing behind vertices.

**Comment by ebfe2326** [comment]
Thanks for the quick response.  I tried to disable the "Use Condensed Layout", but it didn't correct the issue.  I redid one of the screen shots in case it's helpful with the condensed layout turned off.  Just as an FYI, if I turn off the condensed layout, the graph gets so spread out it makes it difficult to follow because you end up only seeing virtually only one code block on the screen at a time.  The spacing of the condensed layout seems to be pretty good in general so that you can see enough on the screen.  The places where the edges properly route around the code blocks works great.  It's just a problem where they don't get properly routed or get multiple over-lapping lines.
![image](https://user-images.githubusercontent.com/44279601/64745387-b1587e00-d4d5-11e9-8027-6a1fb127c445.png)

**Comment by dragonmacher** [comment]
There is a fix in the 9.1 branch that addresses the biggest offending edge in the above screen shot.  There are also another couple bug fixes in progress to address the edges getting clipped by vertices.

**Comment by ebfe2326** [comment]
thanks for the update.  2 quick follow on questions.

When you say there is a fix in the 9.1 branch for the biggest offender, does that mean I can generate a new build myself now to see how well the fix works?

for the additional bug fixes in work, is there anyway for me to track when the fixes are implemented so that i can test them out?

thanks again for all the support!

**Comment by dragonmacher** [comment]
The first fix has been committed to 9.1, which means you should be able to build and test it.

The second bug fix branch is winding through review, but is not yet committed to 9.1.   I will update this ticket once the fix has been merged in.

**Comment by ebfe2326** [comment]
thanks for all the hard work on Ghidra.  I built a new version of Ghidra to test and can definitely see an improvement.  Hopefully the second bug fix will correct more of the problems.  

I'm assuming that when you say the first bug fix was for the biggest offender, that you are referring to when the edges go straight through the middle of a code block versus near the edges.  If that is the case, i wanted to provide some feedback that while it looks like it's doing better, there still seems to be something a little off in the logic.  I analyzed my example file and found several places where there are edges still going through the middle of the code blocks versus being near the edges.  I put one screenshot here if it's helpful.

![image](https://user-images.githubusercontent.com/44279601/65101593-8dde7900-d996-11e9-8e54-744fb5abf6b3.png)

If i'm misinterpreting what you were referencing as the biggest offender, no worries.  I'll test it out again once the 2nd bug fix is included.  I just wanted to provide some quick feedback as an FYI in case the routing algorithm is working better on your test files so that you have more information.

Keep up the good work.

**Comment by ryanmkurtz** [comment]
The new fixes are now in master.

**Comment by dragonmacher** [comment]
The first fix addressed the odd case where an edge could degenerate into a spaghetti-like leviathan, with nonsensical protrusions.   The second fix addresses the issue above, the lines traveling behind vertices.

Keep us posted if there are still degenerate cases after these fixes.  

Thanks for the testing help.

**Comment by ebfe2326** [comment]
i built a new version of Ghidra to test out the fixes.  I can see an improvement, particularly in that first case you mentioned.  For the second situation with lines traveling behind vertices, i think it got better, but unfortunately there's still a fair number of occurances with the lines going behind the code blocks.  I put a few examples below.  I tried testing it both with the default code block sizes and with a view where I expanded the field sizes so the instructions are fully shown.  It didn't seem like one view did particularly better than the other.  It's a little strange because there are places with the default field sizes that are having the problem but are ok in the expanded field  sizes and vice versus.  I tried looking, but I can't seem to find any type of pattern where the edges are going behind the code blocks.  For some reason, it just seems like the routing algorithm can't always identify the code block locations.  In some situations, the edges cut straight through the middle of a code block.  In other situations, the edges try to route around the code blocks, but don't quite make it and still go through the code block, just near the edge instead of through the middle.

![image](https://user-images.githubusercontent.com/44279601/65176745-67b2ea80-da23-11e9-88a4-4fa4d8cca6eb.png)

Note in this second image, the purple line that's doing a funny route around the code blocks is the same line in the first image that went straight  through the middle of the the code blocks.  For some reason, the first situation the algorithm didn't seem to know the code blocks were there, but the 2nd situation it seemed to know the location of the code blocks.  You can also see the green lines going through the code blocks again; near the middle in one code block but near the edge in another code block


![image](https://user-images.githubusercontent.com/44279601/65176884-a648a500-da23-11e9-862e-3eeb4a305c6c.png)


I think the improvements are really helpful for Ghidra.  Compared to the other available tools like binary ninja or ida pro, the decompiler is a nice addition, but the graph view is a little more of a subtraction.  It makes deciding to use Ghidra a little more difficult because you need to decide if the decompiler addition is worth the graphing subtraction.  I think if it's possible to improve these graphing routing algorithms so they are in line with the other available tools, it makes Ghidra much more competitive because you can decide to use it without losing anything from the other tools.  You would only be gaining functionality.

If I should put these images in a new bug request since this ticket was closed, let me know.  I'm guessing this graphing problem must be more complicated then it seems and i appreciate all the work you guys are putting into the tool.

**Comment by dragonmacher** [comment]
Having the images here is fine, since we are actively examining the issue.

It appears from your samples that there are still bugs in the algorithm.   That being said, there will be cases that degenerate when the graph gets too complicated.   This layout, and graph layouts in general, seek a pleasing aesthetic by valuing symmetry and minimal edge crossings.   The original edge layout algorithm minimizes crossings by combining edges flowing to the same end point.   The new mode of routing around vertices means that we will get more edge crossings, including times where the edges travels behind vertices.   This is even more likely when we condense the vertices to save space.    Ideally, we can fix the bugs causing the edges to flow behind the vertices, which will make the graph easier to read.  But, all of the competing requirements mean that there is no real perfect solution.

It is possible that we can create different layouts for the Function Graph that are easier to use/read, depending upon what the user is trying to accomplish.  I have experimented with other layouts and have found the current one to be the best for quick visual scanning and for determining overall high-level function flow.   It is possible that a more simplistic layout would make following individual edge flow easier.     If you get the time, then the best way forward is to create a new ticket  requesting a new graph layout, with descriptions of your typical workflow(s) included.   This information will be valuable if we decide to allocate resources to this area.

Regarding this ticket specifically, we will investigate the issues you have shown above and update this ticket if we have any new related fixes.

**Comment by dragonmacher** [comment]
I have already found another bug; still looking for more edge cases.

Also, in case I didn't mention it, you can always select an edge by clicking it if you are having trouble following its path through the graph.   Once the edge is selected, it becomes emboldened, making it much easier to follow.   (Also, fun tip: you can double-click and edge to navigate to each endpoint.)

**Comment by dragonmacher** [comment]
There is a bug fix making its way through code review, but I don't think it will fix the issues you have reported.

I did find cases that looked similar to your screen shots.   When you see the edges move behind the vertices, as you have shown above, try turning off the 'Use Condensed Layout' feature to see if they no longer get clipped.   If they are still clipped, then that is a bug; if they are no longer clipped, then that is a flaw of how the algorithm currently works.

It is possible that we could fix the algorithmic flaw, but that is not likely to happen for the 9.1 release, as it could require much more work.

**Comment by ebfe2326** [comment]
Not sure if it's good news or bad, but I turned off the "Use Condensed Layout" feature and the problem was fixed.  I went through the entire binary and didn't see any location where the edges were going behind any of the code blocks.  They always seemed to route around the code blocks properly.

I agree with your assessment that the current layout is pretty good for visual scanning the function flow.  I think if the algorithm can be fixed for a future release so that it works as is while still using the condensed layout, the solution would be pretty good.  The condensed layout is definitely preferable as the graph gets a little too spread out without it, but i can uncheck the option for now.  

When the algorithm works, the only major downside I've seen is that it looks like a fair number of edges get overlapped so that you can't distinguish between them without clicking on one to highlight it.  If it were possible to fix the algorithm for a future release and also have some type of minimum separation between all of the edges, I think it would be comparable to the other RE tools.  I'm not quite sure, but it sounds like the overlapping edges might be a design choice for aesthetics rather than a bug though.
