### ISSUE TITLE
Latent support for VS 2019

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#999]
**VS2019 not supported officially.**
Right now Ghidra team does not support VS2019 and does not have capacity to do that. At the same time community regularly asking for that. 

**Describe the solution you'd like**
I would like small change in the build process, specifically in the `vsconfig.gradle` in the manner similar to https://github.com/NationalSecurityAgency/ghidra/pull/730 . More specifically to have function for look for VS locations based on version and edition. In official version you will have only VS2017 enabled, and who want to maintain fork (or small customaization, if you like) can do that with less effort. 
Also the build PDB project using `devenv` does not allow to specify parameter, I would like that to be switched to MSBuild if possible.

**Describe alternatives you've considered**
Other way, which I look which is viable is to have ability to specify VS version and edition and Windows SDK as gradle parameters, to support overriding of VS version and Windows SDK version 

**Additional context**
I want to ask you for solution which would be less burden for you, at the same time, allow for better configuration to work in different environment then yours.
I also willing to do all legwork with implementation, since this is me who need this.

**Comment by XVilka** [comment]
You might want to consider to use clang-cl - it's [compatible with MSVC](https://clang.llvm.org/docs/MSVCCompatibility.html), and recently both Google and Mozilla switched to use it for building Chrome and Firefox respectively. Moreover, you will get ASAN, UBSAN, whatever for free (at Windows platform):
- http://blog.llvm.org/2018/03/clang-is-now-used-to-build-chrome-for.html
- http://blog.llvm.org/2018/11/30-faster-windows-builds-with-clang-cl_14.html
- https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites

**Comment by ghidra1** [comment]
While this is an interesting idea, I would think that it does not help with the SDK version and path concerns which would still need to be handled.  In addition, there is the integration with Gradle for the Windows platform.

**Comment by ryanmkurtz** [comment]
@kant2002, can you give the latest changes a try?

**Comment by kant2002** [comment]
@ryanmkurtz working without anything from my side

**Comment by kant2002** [comment]
Big thanks!

**Comment by ryanmkurtz** [comment]
Great, thanks for your contributions and helping to drive it forward!
